### ISSUE TITLE
nchar Chinese character issue

### ISSUE THREAD

**Issue by DarkGodOne** [taosdata/TDengine#10030]
服务端部署环境：
树莓派arm64版本2.4.0

客户端环境：
windows10 64位版本2.4.0官方客户端
树莓派上的客户端不允许输入中文，所以没法测试

超级表创建了一个NCHAR(10)的字段，插入“你好啊”，实际只插入了“你好”，如图：
![image](https://user-images.githubusercontent.com/12151282/151110651-ddf6fe80-03f9-40d2-aecf-dcccec12425f.png)

但是当插入“你好安逸”，实际插入“你好安”
![image](https://user-images.githubusercontent.com/12151282/151110837-aa837c21-4305-414e-ac7c-05376a068d2b.png)

后面又插入“你好安逸啊”，实际插入“你好安逸啊”
![image](https://user-images.githubusercontent.com/12151282/151110891-05a30e8a-49f6-4c24-a8ba-f4d457ac4f97.png)

**Comment by yu285** [comment]
我们看下

**Comment by yu285** [comment]
可以添加微信 15652223354做具体问题排查
