### ISSUE TITLE
After dropping database , restful still see the data

### ISSUE THREAD

**Issue by Kolo7** [taosdata/TDengine#10041]
**Bug Description**
删除数据库后，通过`curl -X POST http://taos-cluster-01:6041/rest/sql`接口依然能查到数据，这导致blm_prometheus无法自动建表。
重启taosd后问题解决。

**To Reproduce**
1. 通过blm_prometheus写入数据到taos
2. 删除写入的整个prometheus数据库
3. blm_prometheus报错：表不存在

**Environment (please complete the following information):**

- OS: CentOS 7.0
- Memory：16G, CPU：8核, current Disk Space：500G SSD
- TDengine Version ：2.3.5.0

分析应该是由于删除数据库后，元数据的缓存没清理

**Comment by Kolo7** [comment]
描述下我的架构：
prometheus 远程写入到blm_prometheus插件，然后由blm_prometheus写入到taosdb。我将原来的自动创建的prometheus数据库整个删除了，发现blm_prometheus一直报错表不存在，排查发现http://taos-cluster-01:6041/rest/sql接口返回表元数据是存在的，但实际上整个库都被删除。重启后问题得到解决。

**Comment by yu285** [comment]
reset query cache 命令可以更新缓存的
