### ISSUE TITLE
Hope support MAC client

### ISSUE THREAD

**Issue by ZhangChengJi** [taosdata/TDengine#10052]
/Users/zcj/go/pkg/mod/github.com/taosdata/driver-go@v0.0.0-20210609071024-b8f76da4a708/taosSql/ctaos.go:21:10: fatal error: 'taos.h' file not found
#include <taos.h>

**Comment by yu285** [comment]
it is a part of our future plan

**Comment by douxu** [comment]
# github.com/taosdata/driver-go/v2/wrapper
../../../go/pkg/mod/github.com/taosdata/driver-go/v2@v2.0.1/wrapper/field.go:4:10: fatal error: 'taos.h' file not found
#include <taos.h>
         ^~~~~~~~
1 error generated.

**Comment by sangshuduo** [comment]
@douxu  you can build and install with TDengine source code on Mac.

**Comment by liu-xinhui** [comment]
Server is linux，but the develop computer is mac, I only need jdbc client can use in mac. Server is not need

**Comment by jtao1735** [comment]
> Server is linux，but the develop computer is mac, I only need jdbc client can use in mac. Server is not need

There are two JDBC drivers for TDengine, please use JDBC-REST on Mac.

**Comment by luckmao** [comment]
什么时候支持mac 开发？

**Comment by YmilitaryM** [comment]
> > Server is linux，but the develop computer is mac, I only need jdbc client can use in mac. Server is not need
> 
> There are two JDBC drivers for TDengine, please use JDBC-REST on Mac.
when I want to use consumer function for TDengine, JDBC-REST won't success

**Comment by zw18** [comment]
.

**Comment by arielyang** [comment]
We care already support macOS: https://docs.taosdata.com/get-started/package/
