### ISSUE TITLE
query result is not correct  with interval、fill and two or more tags

### ISSUE THREAD

**Issue by xiaoye513** [taosdata/TDengine#10083]
**Bug Description**
如下图，两个查询语句是一样的、只是左边多查了一个tag， 但得到的同一个点的结果却不一样；
右图才是正确的，12点前没有数据；
所以问题是在多个tag的时候 自动填充的数据不对，也暂时看不出这个填充逻辑  

**Screenshots**
![image](https://user-images.githubusercontent.com/17876572/151503146-f3ba2b31-8caf-455b-84e1-f2358bbae5c7.png)

**Environment (please complete the following information):**
 - TDengine Version [2.4.0.0]

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
