### ISSUE TITLE
how to improve write throughput using JDBC?

### ISSUE THREAD

**Issue by double-7** [taosdata/TDengine#1012]
**环境描述**
OS：Ubuntu 18.04.1 LTS虚拟机
mem: 3G
disk：20G
java：jdk1.8
TDengine：1.6.4.4
jdbc测试程序与TDengine程序位于同一台设备上

**问题描述** 
使用jdbc测试TDengine数据库性能，发现测试性能无法和介绍中差距有点大。在单线程，单表，一条sql一条请求写入条件下900条左右/秒。
(
** TDengine与InfluxDB对比测试**
应用案例中使用c客户端在单线程，单表，一条sql一条请求的写入环境下达到26824条/秒
）
请问怎么才能使用java客户端程序写入速度，达到或者接近介绍中的使用C客户端程序写入速度。

**测试结果**
![image](https://user-images.githubusercontent.com/24646801/71441855-52460e80-273e-11ea-8e76-a1c0f07a86ba.png)

**操作流程**
1：代码打成jar包
2：java -jar xxx.jar

**代码截图**
![image](https://user-images.githubusercontent.com/24646801/71441615-2bd3a380-273d-11ea-8002-eded3e830485.png)
![image](https://user-images.githubusercontent.com/24646801/71441698-84a33c00-273d-11ea-9982-3fa2bdc4f759.png)
![image](https://user-images.githubusercontent.com/24646801/71441706-8b31b380-273d-11ea-80ab-19324e1b0849.png)
![image](https://user-images.githubusercontent.com/24646801/71441715-97b60c00-273d-11ea-84cf-fae742945fde.png)
![image](https://user-images.githubusercontent.com/24646801/71441722-9dabed00-273d-11ea-8d2b-e32a6c078fae.png)

**代码**
···
package priv.dyf.taos_demo;

import com.taosdata.jdbc.TSDBDriver;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;

/**
 * @ClassName
 * @Description
 * @Author dyf
 * @Date 2019/12/25
 * @Version 1.0
 */
public class TaosDemo {
    private final Connection conn;
    private volatile long dataTime = 1577264421614L;
    private final int max = 10000;

    public TaosDemo() throws ClassNotFoundException, SQLException {
        String os = System.getProperty("os.name");
        System.out.println(os);
        Class.forName("com.taosdata.jdbc.TSDBDriver");
        if (os.toLowerCase().startsWith("win")) {
            String jdbcUrl = "jdbc:TAOS://192.168.104.204:6030/log?user=root&password=taosdata";
            Properties connProps = new Properties();
            connProps.setProperty(TSDBDriver.PROPERTY_KEY_USER, "root");
            connProps.setProperty(TSDBDriver.PROPERTY_KEY_PASSWORD, "taosdata");
            conn = DriverManager.getConnection(jdbcUrl, connProps);
        } else {
            String jdbcUrl = "jdbc:TAOS://127.0.0.1:6030/log?user=root&password=taosdata";
            Properties connProps = new Properties();
            connProps.setProperty(TSDBDriver.PROPERTY_KEY_USER, "root");
            connProps.setProperty(TSDBDriver.PROPERTY_KEY_PASSWORD, "taosdata");
            connProps.setProperty(TSDBDriver.PROPERTY_KEY_CONFIG_DIR, "/etc/taos");
            connProps.setProperty(TSDBDriver.PROPERTY_KEY_CHARSET, "UTF-8");
            connProps.setProperty(TSDBDriver.PROPERTY_KEY_LOCALE, "en_US.UTF-8");
            connProps.setProperty(TSDBDriver.PROPERTY_KEY_TIME_ZONE, "UTC-8");
            conn = DriverManager.getConnection(jdbcUrl, connProps);
        }
    }

    //清除数据
    public void clearData() throws Exception {
        Statement stmt = conn.createStatement();
        stmt.executeUpdate("drop database if exists db_demo");
        stmt.close();
    }
    //创建库，表
    public void createDemoTable() throws Exception {
        Statement stmt = conn.createStatement();
        // 创建库
        stmt.executeUpdate("create database if not exists db_demo");
        stmt.executeUpdate("use db_demo");
        //创建stb
        String stbSql = "create table if not exists stb_demo (dataTime timestamp, dataVal int,dataQuality int) " +
                "tags(tag1 binary(48), tag2 binary(48),tag3 binary(48),tag4 binary(48),tag5 binary(48))";
        int stbNum = stmt.executeUpdate(stbSql);
        System.out.printf("create stb :%s\n", stbNum);
        //创建tb
        String sTableName = "stb_demo",tableName = "tb_demo";
        String tag1 = "tag1", tag2 = "tag2", tag3 = "tag3", tag4 = "tag4", tag5 = "tag5";
        String sql = String.format("create table if not exists %s using %s tags('%s','%s','%s','%s','%s')",
                tableName, sTableName, tag1, tag2, tag3, tag4, tag5);
        int tbNum = stmt.executeUpdate(sql);
        System.out.printf("create tb :%s\n", tbNum);
        stmt.close();
    }

    //插入数据
    public void insertData() throws Exception {
        Statement stmt = conn.createStatement();
        stmt.executeUpdate("use db_demo");

        long startTime = System.currentTimeMillis();
        for (int i = 0; i < max; i++) {
            dataTime++;
            stmt.executeUpdate("insert into tb_demo values(" + dataTime + ", 1, 193)");
        }
        long endTime = System.currentTimeMillis() - startTime;
        System.out.printf("end:%s,speed:%s\n", endTime, max / (endTime / 1000));
        stmt.close();
    }

    //关闭资源
    public void close() {
        try {
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        try {
            TaosDemo demo = new TaosDemo();
            demo.clearData();
            demo.createDemoTable();
            demo.insertData();
            demo.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
···

**Comment by hjxilinx** [comment]
1. 更改一下的您的程序，不要拼接sql.
使用```StringBuilder```。

```
stmt.executeUpdate("insert into tb_demo values(" + dataTime + ", 1, 193)");
```
2. 您可以试一试批量写入，因为单条写入受请求往返的限制。

**Comment by double-7** [comment]
> 1. 更改一下的您的程序，不要拼接sql。
>    使用`StringBuilder`。
> 
> ```
> stmt.executeUpdate("insert into tb_demo values(" + dataTime + ", 1, 193)");
> ```
> 
> 1. 您可以试一试批量写入，因为单条写入受请求往返的限制。

1：900条/S的速度核心应该是数据库读写的原因，我更改为StringBuilder后提升并不大。
2：官方测试demo中2.5W的单请求，单客户端的读写性能。
3：所以我想请问下您这边的环境有什么特别的配置吗，例如象mysql的 innodb_flush_log_at_trx_commit的配置而没有在文档中体现，还是说一切都是默认配置。

**Comment by hjxilinx** [comment]
没有特殊的配置。
如果您希望能够复现测试中的效果，可以使用完全相同的硬件配置来测试。JDBC与c的性能有较大差距，并且差距在不同的机器上还不太相同。
另，您的机器的CPU的主频多少？

**Comment by double-7** [comment]
> 没有特殊的配置。
> 如果您希望能够复现测试中的效果，可以使用完全相同的硬件配置来测试.JDBC与Ç的性能有较大差距，并且差距在不同的机器上还不太相同。
> 另，您的机器的CPU的主频多少？

我重新部署了新的服务器。

**Comment by double-7** [comment]
> 没有特殊的配置。
> 如果您希望能够复现测试中的效果，可以使用完全相同的硬件配置来测试.JDBC与Ç的性能有较大差距，并且差距在不同的机器上还不太相同。
> 另，您的机器的CPU的主频多少？

我重新部署了服务器环境后测试应该正常。
1.OS：CentOS Linux release 7.0.1406 (Core) / x86_64
2.JDK：1.8.0_11
3.内存：4G
4.Cpu：Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz(2物理核心，4逻辑核心)
5.数据库：
TDengine-1.6.4.4
Mysql-5.7.16

![image](https://user-images.githubusercontent.com/24646801/71704843-9e1c4600-2e17-11ea-97b9-07086ab02953.png)

因为没有主频3.90Ghz机器,所以根据结果推断贵司的TDengine，比较吃CPU核心和主频。
