### ISSUE TITLE
log.slowquery table doesnt update along with db update

### ISSUE THREAD

**Issue by jamesdzhang** [taosdata/TDengine#10131]
**Bug Description**
log.slowquery table maintain old versions schema even after a db update is complete.

**To Reproduce**
1. install 2.2.0.2 ver of db
2. update db to 2.4
3. describe log.slowquery and may find that schema of this table is still the old version.

**Expected Behavior**
table log.slwoquery should be in v2.4's schema.

**Screenshots**
![image](https://user-images.githubusercontent.com/3303110/152905889-287cace2-93a2-49d0-88bc-83c5fa95be2e.png)

**Environment (please complete the following information):**
 - OS: [CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [2.4]

**Comment by yu285** [comment]
There is no change for this table

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
