### ISSUE TITLE
Can taos store large text fields

### ISSUE THREAD

**Issue by IZ-ONE** [taosdata/TDengine#10135]
I need to migrate from postgresql to taos, there is a text field in the table (to store large text), does taos have a data type that can store large text, and what is the maximum length of nchar

**Comment by yu285** [comment]
16kb  is  the max size for each row

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。
（3.x 目前单行最大支持 64k）
操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
