### ISSUE TITLE
Does source compilation support MIPS architecture of Godson CPU？Does tdengine source code compilation support the MIPS architecture of the loongson CPU？

### ISSUE THREAD

**Issue by junxuezheng** [taosdata/TDengine#1016]
tdengine源码编译是否支持龙芯CPU的mips架构？
Does tdengine source code compilation support the MIPS architecture of the loongson CPU？

**Comment by plum-lihui** [comment]
目前还不支持，现在优先在搞arm架构，然后才会搞mips。还需要点时间。

**Comment by sangshuduo** [comment]
目前支持了 MIPS64 架构， cmake .. -DCPUTYPE=mips64 ，我们这里缺乏硬件进行测试，欢迎向我们报在 MIPS64 架构使用 TDengine 遇到的问题
