### ISSUE TITLE
restful connector: database authentification failure when '@' exists in the password

### ISSUE THREAD

**Issue by colo1994** [taosdata/TDengine#1017]
使用这个接口获取请求时：http://xx:6020/rest/login/root/abcd@1234 密码中含有@符号后验证失败。
改为adbcd_1234时验证正常，abcd@1234这个密码在服务端是可以通过的。

**Comment by guanshengliang** [comment]
OK, Let me fix this bug

**Comment by guanshengliang** [comment]
![image](https://user-images.githubusercontent.com/28882257/71758018-cb2f2e00-2ed5-11ea-85c4-a18587f91433.png)

This issue cannot be reproduced in 1.6.4.4, it should have been fixed

**Comment by guanshengliang** [comment]
![image](https://user-images.githubusercontent.com/28882257/71758095-92438900-2ed6-11ea-81cb-3e15293f08b2.png)

This issue cannot be reproduced in 1.6.4.4, it should have been fixed

**Comment by guanshengliang** [comment]
There is no response to this issue for a long time, and this issue has been fixed in 2.0 version, so close it
