### ISSUE TITLE
Count或没有匹配数据的条件查询很慢

### ISSUE THREAD

**Issue by Alsmile** [taosdata/TDengine#10188]
业务需求：数据点是动态后台管理配置的，数据名称和类型不固定。
看到[3802 ](https://github.com/taosdata/TDengine/issues/3802) 说，用不用超级表差别不大，因此没用超级表，表结构设计成：
create table if not exists dataLogs  (time timestamp, index tinyint, f double, i bigint, b bool, s nchar(100), f0 double, i0 bigint, b0 bool, s0 nchar(100), deviceId nchar(64), description nchar(64) );

因为不确定数据类型，就用f,i,b,s等表示最终实际数据和类型

数据量：实际几百亿。目前测试环境：3个亿

问题1： Count非常慢
select count(*) from dataLogs where  deviceId='opcua-1'  and  description='模拟量163'  order by time desc;

```
taos>  select count(*) from dataLogs where  deviceId='opcua-1'  order by time desc ;
       count(*)        |
========================
             242401844 |
Query OK, 1 row(s) in set (12.069990s)

```

问题2： 没有匹配数据的情况下，select 非常慢
select * from dataLogs where  deviceId='opcua-1'  and  description='1111不存在'  order by time desc;

```
taos>  select * from dataLogs where  deviceId='opcua-1'  and  description='xxxxx'  order by time desc limit 100;
Query OK, 0 row(s) in set (46.243749s)
```

问题3：当存在非常慢的查询时，好像会影响(阻塞？)其他本身不慢的查询

期望： 查询1s内

解决：
1、应该动态根据deviceId和description分子表吗？
2、这种情况，最佳解决方案应该是怎么样的

**Comment by yu285** [comment]
nchar比较多，1个nchar=4个binary，如果没有中文等非ascII字符不要使用。

其次，nchar/binary不是变长，请不要随意给值，符合业务就行

这个会比较影响性能，请先试试调整

**Comment by Alsmile** [comment]
按 tags (deviceId nchar(64), description nchar(64)) 分子表了，基本能解决问题，特别是问题2
