### ISSUE TITLE
(python3)关于taos链接依赖包的使用问题

### ISSUE THREAD

**Issue by weilisikaili** [taosdata/TDengine#1019]
一:  ubuntu系统,正常安装TDengine后,测试可以正常使用.1.创建python3虚拟环境, pip install taos  安装taos时pip自动安装了click依赖包 ; python脚本写入 import taos 可以正常执行; 当我正常使用时我写下数据库链接代码:conn = taos.connect(host="127.0.0.1", user="root", password="taosdata", config="/etc/taos")
cl = conn.cursor()
报错就出来了,控制台提示我taos依赖包没有connect这个属性或方法; 我很意外,去查看taos源码,发现整个依赖包加上__init__.py总共只有五个文件,分别是:bio.py,cli.py,config.py,web.py;且文件中并不包含文档上写的那些方法.;  
请问我是否操作有误,此依赖包是否不是客户端的链接依赖包? 官方文档在这一方面并没有说明.

**Comment by hfcn123** [comment]
我也是遇到了，是不是引入的包有误啊，你最后怎么解决的
