### ISSUE TITLE
insert data failed

### ISSUE THREAD

**Issue by DarkGodOne** [taosdata/TDengine#10227]
使用的程序版本是2.4.0.0
相同的超级表定义，表名中带下划线和不带下划线导致插入失败，windows和linux版本都是一样的结果
我看官网的表名是允许字母、数字、下划线的，这个应该是个bug

截图：
![image](https://user-images.githubusercontent.com/12151282/153694485-23b1cadc-faa5-42b4-9f09-30302de23abc.png)

**Comment by DarkGodOne** [comment]
补充下，带一个下划线，可以，带两个就不行，=。=
![image](https://user-images.githubusercontent.com/12151282/153694561-e276fe0e-0064-45f6-bdf7-b9cb93fcb85b.png)

**Comment by yu285** [comment]
我们检查下，多谢反馈

**Comment by yu285** [comment]
我们没能复现，可以添加一下微信15652223354，我们具体看下
