### ISSUE TITLE
JNI ERROR (2354): Ref is not there

### ISSUE THREAD

**Issue by Jackhzf** [taosdata/TDengine#10234]
JDBC-JNI: jar包2.0.37
TDengine-client-2.4.0.7-Windows-x64
TDengine-server-2.4.0.7-Linux-x64.tar

在windows中使用taos Shell可以链接成功
java中使用JDBC-JNI链接就报错

**Comment by Jackhzf** [comment]
本地配置节点解决问题

**Comment by xiaoduan-kougukougu** [comment]
能问一下本地配置节点是指的什么吗，我也遇到了与你相同的问题

**Comment by liu-xinhui** [comment]
@Jackhzf 修改host吗，为啥我已经修改了hosthome和hosts，仍然不行

**Comment by xiaoduan-kougukougu** [comment]
> @Jackhzf 修改host吗，为啥我已经修改了hosthome和hosts，仍然不行

我昨天弄好了，不知道能不能帮到你。
因为我这用了k8s所以映射出来的端口就不是6030，问题就是在这，我使用我外部映射的端口taos内部还是用的以前的6030-6042的端口，所以服务端内部对外暴露的端口要保持一致才行，然后就把服务端内部的端口也改了，意思就是不能映射成其它端口。

**Comment by liu-xinhui** [comment]
@Jackhzf 多谢了，问题已经解决了，我的端口映射内外是一致的，client是通过外网地址访问的server。但是server防火墙只开放了6030-6042的tcp通道，把udp也开放就好了
