### ISSUE TITLE
Docker image usage question

### ISSUE THREAD

**Issue by wangyjx** [taosdata/TDengine#10238]
Not able to query in Taos  client.  Don't know if I do anything wrong.

steps:

1. pull docker image version 2.4.0.5 in docker deskop for windows.
2. docker image successfully started.
3. I can use curl to query. 

 curl -H 'Authorization: Basic cm9vdDp0YW9zZGF0YQ==' -d 'use log;select count(*) from log;' 127
.0.0.1:6041/rest/sql
_{"status":"succ","head":["affected_rows"],"column_meta":[["affected_rows",4,4]],"rows":1,"data":[[0]]}_

4. when use taos client, it can "show databases;" and also the "use log", but when use select query, it shows "DB error: Unable to establish connection",

for example:

taos> show databases;

 log    | 2022-02-14 09:15:07.737 |      11 |        1 |     1 |    1 |     10 | 30       |         1 |       3 |       100 |    4096 |    1 |        3000 |    2 |         0 | us        |      0 | ready      |

Query OK, 1 row(s) in set (0.004460s)

taos> use log;
Database changed.

taos> show tables;

table_name           |      created_time       | columns |          stable_name           |          uid          |     tid     |    vgId     |
==================================================================================
 restful_1                      | 2022-02-14 09:15:07.792 |      64 | restful_info                   |       562950121200313 |          10 |           2 |
 acct_root                      | 2022-02-14 09:15:07.763 |      22 | acct                           |       562950003756570 |           3 |           2 |
 cluster_info                   | 2022-02-14 09:15:07.769 |      14 |                                |       562950037311599 |           5 |           2 |
 dnode_1                        | 2022-02-14 09:15:07.773 |      31 | dnodes_info                    |       562950054089286 |           6 |           2 |
 vgroup_2                       | 2022-02-14 09:15:36.817 |       7 | vgroups_info                   |       562950137977701 |          11 |           2 |
 dn1                            | 2022-02-14 09:15:07.760 |      15 | dn                             |       562949986979254 |           2 |           2 |
 slowquery                      | 2022-02-14 09:15:07.766 |       5 |                                |       562950020534042 |           4 |           2 |
 disks_1                        | 2022-02-14 09:15:07.778 |       7 | disks_info                     |       562950070867055 |           7 |           2 |
 log                            | 2022-02-14 09:15:07.752 |       4 |                                |       562949970201286 |           1 |           2 |
 grants_info                    | 2022-02-14 09:15:07.787 |       4 |                                |       562950104422426 |           9 |           2 |
 dnode_1_log                    | 2022-02-14 09:15:07.784 |       3 | logs                           |       562950087645113 |           8 |           2 |

taos> select count(*) from log;

**DB error: Unable to establish connection (18.058052s)**

**Comment by yu285** [comment]
did we expose the port 6030 out ?

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
