### ISSUE TITLE
How to fetch data by time(without year and month and day)

### ISSUE THREAD

**Issue by fake2ky** [taosdata/TDengine#10235]
在数据库当中我只想查询出两个时间点内的数据（如：取9:00:00至18:00:00的数据，不管日期部分）
1. 我尝试过查询taos文档, 并没有找到帮助.
2. issue没有也没找到相关需求, 还发现 针对某一字段的过滤只支持单一时间区间过滤条件? 
https://github.com/taosdata/TDengine/issues/3943
3. 搜索引擎也没得到有效的答案.

目前我只能查出所有数据再去筛选掉大部分没用的时间数据，请问我可以怎么处理。

**Comment by yu285** [comment]
这个当前还不能支持

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
