### ISSUE TITLE
The data dump out  with taosdump  is too large to import 

### ISSUE THREAD

**Issue by twtmiss** [taosdata/TDengine#10245]
TDengine数据库版本：2.4.0.4
taosdump版本：1.2.0_f4759ff

使用命令：`taosdump -u root -p -D database_name -B 100 -T 8` 成功导出数据库数据。

使用命令：`taosdump -i tdengineBak -T 8 -uroot -p` 导入至数据库，提示有1600多万行写入失败。

<img width="964" alt="image" src="https://user-images.githubusercontent.com/36953621/153809125-15e6b6de-e071-4563-85d4-ccaa12efee63.png">

后续查询有很多数据丢失了，我看了下`taosdump`命令也没有了`-t`参数，应该是用什么命令完整的将数据库数据导出来，并恢复至另一处？
<img width="686" alt="image" src="https://user-images.githubusercontent.com/36953621/153809254-9b674018-7b7a-479e-822b-4817130ad4ee.png">

**Comment by sangshuduo** [comment]
表的列数比较多或者比较长，导致 WAL size exceeds limit 错误，请使用 -B 参数调整为一个相对较小的值，默认为 16384

**Comment by twtmiss** [comment]
> 表的列数比较多或者比较长，导致 WAL size exceeds limit 错误，请使用 -B 参数调整为一个相对较小的值，默认为 16384

我尝试了将`-B`参数调整为100、30、3、1和默认参数。
设置为 100、30、3 时均提示1600w+导入失败
设置为 1 时提示 1700w+ 导入失败
设置为默认参数时提示1750w+ 导入失败

请问有什么比较好的数据库迁移方案吗？

**Comment by sangshuduo** [comment]
> > 表的列数比较多或者比较长，导致 WAL size exceeds limit 错误，请使用 -B 参数调整为一个相对较小的值，默认为 16384
> 
> 我尝试了将`-B`参数调整为100、30、3、1和默认参数。 设置为 100、30、3 时均提示1600w+导入失败 设置为 1 时提示 1700w+ 导入失败 设置为默认参数时提示1750w+ 导入失败

导入失败都是 WAL size exceeds limit 吗？方便把表结构贴一下吗？describe 超级表名字的输出。

> 
> 请问有什么比较好的数据库迁移方案吗？

**Comment by twtmiss** [comment]
> 导入失败都是 WAL size exceeds limit 吗？方便把表结构贴一下吗？describe 超级表名字的输出。

总共有两张超级表：
- `message_detail_super`下有123张子表，共计343w条数据
- `message_info_super`下有1637张子表，共计4001w条数据
```
create table if not exists iec_tdengine.message_detail_super(
            ts timestamp,
            currentTimeMillis nchar(18),
            ip nchar(18),
            port int,
            messageHexString nchar(800),
            isContinuous bool,
            messageLength int,
            transferReason int,
            terminalAddress int,
            messageAddress int,
            isMessage bool,
            isQualifiers bool,
            isTimeScaleExit bool,
            timeScale timestamp,
            hexString nchar(20)
) tags(location nchar(64), groupId nchar(7))

create table if not exists iec_tdengine.message_info_super(
            ts timestamp,
            currentTimeMillis nchar(18),
            ipPort nchar(25),
            messageAddress int,
            messageInfoString nchar(20),
            messageInfoValue float,
            qualifiersType int,
            messageInfoLength int
) tags(location nchar(64), groupId nchar(7))
```

**Comment by sangshuduo** [comment]
> > 导入失败都是 WAL size exceeds limit 吗？方便把表结构贴一下吗？describe 超级表名字的输出。
> 
> 我看了下日志，导入失败全部都是`WAL size exceeds limit ` 总共有两张超级表：
> 
>     * `message_detail_super`下有123张子表，共计343w条数据
> 
>     * `message_info_super`下有1637张子表，共计4001w条数据
> 
> 
> ```
> create table if not exists iec_tdengine.message_detail_super(
>             ts timestamp,
>             currentTimeMillis nchar(18),
>             ip nchar(18),
>             port int,
>             messageHexString nchar(800),
>             isContinuous bool,
>             messageLength int,
>             transferReason int,
>             terminalAddress int,
>             messageAddress int,
>             isMessage bool,
>             isQualifiers bool,
>             isTimeScaleExit bool,
>             timeScale timestamp,
>             hexString nchar(20)
> ) tags(location nchar(64), groupId nchar(7))
> 
> create table if not exists iec_tdengine.message_info_super(
>             ts timestamp,
>             currentTimeMillis nchar(18),
>             ipPort nchar(25),
>             messageAddress int,
>             messageInfoString nchar(20),
>             messageInfoValue float,
>             qualifiersType int,
>             messageInfoLength int
> ) tags(location nchar(64), groupId nchar(7))
> ```

好的，我们重现一下

其他数据迁移工具可以考虑使用 dataX https://github.com/taosdata/datax

**Comment by twtmiss** [comment]
> 好的，我们重现一下
> 其他数据迁移工具可以考虑使用 dataX https://github.com/taosdata/datax

好的，不好意思给您添麻烦了

**Comment by sangshuduo** [comment]
> > 好的，我们重现一下
> > 其他数据迁移工具可以考虑使用 dataX https://github.com/taosdata/datax
> 
> 好的，不好意思给您添麻烦了

别客气，谢谢你使用 TDengine

**Comment by sangshuduo** [comment]
@twtmiss 我这里重现不出来这个问题，我用 taosdemo 模拟相同宽度的数据写入，命令行参数如下：

```
taosdemo -A nchar\(64\),nchar\(7\) -b nchar\(18\),nchar\(18\),int,nchar\(800\),bool,int,int,int,int,bool,bool,bool,timestamp,nchar\(20\) -t 2000 -n 20000 -I stmt -y -r 100
```

用 -r 来控制一次写入的行数（BATCH），至少 100 是没问题的。同样用 taosdump 把这个数据库备份下来后用 taosdump -B 100 写回去也可以成功。

如果方便的话，假设使用默认的路径设置，可以 grep 'wal len' /var/log/taos/taosdlog\* 看看输出是什么

**Comment by twtmiss** [comment]
> grep 'wal len' /var/log/taos/taosdlog*

很感谢您这么长时间了还在关注这个问题

以下是我使用 `grep 'wal len' /var/log/taos/taosdlog*`命令输出的内容， 请问您方便的话可以告诉我下您的邮箱，我将一周前备份数据库压缩包通过邮件发给您可以吗？

```
twtmiss@twtmiss:~$ grep 'wal len' /var/log/taos/taosdlog*
02/16 08:49:18.532486 00011310 VND ERROR vgId:4, wal len:3165344 exceeds limit, hver:0
02/16 08:49:18.905352 00011310 VND ERROR vgId:4, wal len:3511688 exceeds limit, hver:0
02/16 08:49:19.008347 00011310 VND ERROR vgId:3, wal len:3511320 exceeds limit, hver:0
02/16 08:49:19.083504 00011310 VND ERROR vgId:4, wal len:3512440 exceeds limit, hver:0
02/16 08:49:19.132055 00011310 VND ERROR vgId:4, wal len:3506328 exceeds limit, hver:0
02/16 08:49:19.373121 00011310 VND ERROR vgId:4, wal len:3512952 exceeds limit, hver:0
02/16 08:49:19.480360 00011310 VND ERROR vgId:4, wal len:3507144 exceeds limit, hver:0
02/16 08:49:19.521276 00011310 VND ERROR vgId:3, wal len:3506504 exceeds limit, hver:0
02/16 08:49:19.547765 00011310 VND ERROR vgId:3, wal len:3512712 exceeds limit, hver:0
02/16 08:49:19.718170 00011310 VND ERROR vgId:3, wal len:3512728 exceeds limit, hver:0
02/16 08:49:19.720578 00011310 VND ERROR vgId:4, wal len:3506600 exceeds limit, hver:0
02/16 08:49:19.785512 00011310 VND ERROR vgId:4, wal len:3508040 exceeds limit, hver:0
02/16 08:49:19.981166 00011310 VND ERROR vgId:4, wal len:3512648 exceeds limit, hver:0
02/16 08:49:20.181093 00011310 VND ERROR vgId:3, wal len:3513048 exceeds limit, hver:0
02/16 08:49:20.353254 00011310 VND ERROR vgId:3, wal len:3508376 exceeds limit, hver:0
02/16 08:49:20.492651 00011310 VND ERROR vgId:4, wal len:3508536 exceeds limit, hver:0
02/16 08:49:20.597257 00011310 VND ERROR vgId:4, wal len:3508024 exceeds limit, hver:0
02/16 08:49:20.845516 00011310 VND ERROR vgId:3, wal len:3507896 exceeds limit, hver:0
02/16 08:49:20.924365 00011310 VND ERROR vgId:3, wal len:3512552 exceeds limit, hver:0
02/16 08:49:21.061386 00011310 VND ERROR vgId:3, wal len:3165384 exceeds limit, hver:0
02/16 08:49:21.535810 00011310 VND ERROR vgId:3, wal len:3198551 exceeds limit, hver:0
02/16 08:49:21.732973 00011310 VND ERROR vgId:3, wal len:3506360 exceeds limit, hver:0
02/16 08:49:22.568627 00011310 VND ERROR vgId:3, wal len:3385488 exceeds limit, hver:0
02/16 08:49:22.578011 00011310 VND ERROR vgId:3, wal len:3506616 exceeds limit, hver:0
02/16 08:49:22.784500 00011310 VND ERROR vgId:3, wal len:3507272 exceeds limit, hver:0
02/16 08:49:22.896061 00011310 VND ERROR vgId:3, wal len:3512616 exceeds limit, hver:0
02/16 08:49:23.297240 00011310 VND ERROR vgId:3, wal len:3505320 exceeds limit, hver:0
02/16 08:49:23.402593 00011310 VND ERROR vgId:3, wal len:3508776 exceeds limit, hver:0
02/16 08:49:23.456761 00011310 VND ERROR vgId:3, wal len:3512184 exceeds limit, hver:0
02/16 08:49:23.540748 00011310 VND ERROR vgId:3, wal len:3508136 exceeds limit, hver:0
02/16 08:49:24.156156 00011310 VND ERROR vgId:3, wal len:3173851 exceeds limit, hver:0
02/16 08:49:24.180022 00011310 VND ERROR vgId:3, wal len:3510984 exceeds limit, hver:0
02/16 08:49:24.183894 00011310 VND ERROR vgId:3, wal len:3507800 exceeds limit, hver:0
02/16 08:49:24.259011 00011310 VND ERROR vgId:3, wal len:3512248 exceeds limit, hver:0
02/16 08:49:24.505975 00011310 VND ERROR vgId:3, wal len:3508296 exceeds limit, hver:0
02/16 08:49:24.833534 00011310 VND ERROR vgId:4, wal len:3193120 exceeds limit, hver:0
02/16 08:49:24.908037 00011310 VND ERROR vgId:3, wal len:3508296 exceeds limit, hver:0
02/16 08:49:25.201654 00011310 VND ERROR vgId:3, wal len:20901450 exceeds limit, hver:0
02/16 08:49:25.227470 00011310 VND ERROR vgId:3, wal len:3506776 exceeds limit, hver:0
02/16 08:49:25.522286 00011310 VND ERROR vgId:4, wal len:3505224 exceeds limit, hver:0
02/16 08:49:26.107309 00011310 VND ERROR vgId:3, wal len:3505560 exceeds limit, hver:0
02/16 08:49:26.110061 00011310 VND ERROR vgId:4, wal len:3512456 exceeds limit, hver:0
02/16 08:49:26.155219 00011310 VND ERROR vgId:4, wal len:3505992 exceeds limit, hver:0
02/16 08:49:26.223911 00011310 VND ERROR vgId:4, wal len:3187535 exceeds limit, hver:0
02/16 08:49:26.399133 00011310 VND ERROR vgId:4, wal len:3514056 exceeds limit, hver:0
```

**Comment by sangshuduo** [comment]
这是之前的。这样你先 systemctl stop taosd
,然后删除原来的log，再systemctl start taosd启动。然后用taosdump -B 1 -i <文件所在目录>，如果出错然后再grep wal 看看，log可以压缩发给我 sangshuduo AT gmail.com

**Comment by twtmiss** [comment]
> 这是之前的。这样你先 systemctl stop taosd ,然后删除原来的log，再systemctl start taosd启动。然后用taosdump -B 1 -i <文件所在目录>，如果出错然后再grep wal 看看，log可以压缩发给我 sangshuduo AT gmail.com

我之前参考网上的教程，一直将`-B`参数用在了导出的命令中，没有在导入的命令中使用。
在导入的命令中使用了`-B`参数提示全部导入成功了。

真的很感谢您，不好意思给您添了这么多的麻烦
<img width="296" alt="image" src="https://user-images.githubusercontent.com/36953621/154970838-7d016a52-7248-4dd7-ad8e-cdb8699a0030.png">

**Comment by sangshuduo** [comment]
@twtmiss 你可以尝试一个大一些的 batch，可以获得更快的恢复速度。另外提醒我们应该提示用户 -B 在备份的时候是无效的参数。谢谢

**Comment by twtmiss** [comment]
> @twtmiss 你可以尝试一个大一些的 batch，可以获得更快的恢复速度。另外提醒我们应该提示用户 -B 在备份的时候是无效的参数。谢谢

好的，我稍后尝试一下，谢谢您啦
