### ISSUE TITLE
taosBenchmark not worked

### ISSUE THREAD

**Issue by zhouyf605** [taosdata/TDengine#10244]
安装taos-tools  1.0.0 或者1.2.0  准备做压测  都是报以下错误
系统centos 8.2
./taosBenchmark --help
./taosBenchmark: symbol lookup error: ./taosBenchmark: undefined symbol: taos_schemaless_insert

**Comment by sangshuduo** [comment]
需要安装 TDengine client 或者 TDengine server 安装包

**Comment by zhouyf605** [comment]
是先安装的tdengine  2.2.2.10 版本 的  后安装的td-tools  而且发现卸载td-tools 他会把   server的taosdump  删除掉  有两个server 安装的可执行文件被tools 卸载删除掉了

**Comment by zhouyf605** [comment]
明白了   taostools  1.2.0  uninstall 脚本卸载直接把  tdserver taosdump 和taosdemo 的软链接删除了   可以优化下  检测本机有tdserver  不要删除这两个软链接

**Comment by sangshuduo** [comment]
> 明白了 taostools 1.2.0 uninstall 脚本卸载直接把 tdserver taosdump 和taosdemo 的软链接删除了 可以优化下 检测本机有tdserver 不要删除这两个软链接

谢谢建议，安装包方面我们还会再优化调整，不过 TDengine 建议直接用 2.4 最新版本（目前是 2.4.0.7）
