### ISSUE TITLE
the version mapping relationship between ekuiper and  tdengine

### ISSUE THREAD

**Issue by 1486756632** [taosdata/TDengine#10252]
现在做EdgeXFoundry 的项目，用ekuiper 规则引擎向tdengine 存数据，ekuiper 默认版本是1.4，tdengine 该用什么版本？如果要往前兼容，ekuiper 和tdengine 的版本对应关系是什么？

**Comment by SuperRxan** [comment]
eKuiper 对 tdengine 是以插件形式支持的, 需要用到 tdengine 的客户端驱动。
用户在使用插件时，需要安装 tdengine client 到宿主机上，然后插件才能工作。其中tdengine client的版本是由用户自己指定
，是由 tdengine server 决定的，意味着tdengine client 与 server 版本号必须一致。
可参考这里的说明 https://github.com/lf-edge/ekuiper/blob/master/docs/zh_CN/extension/native/sinks/tdengine.md#%E5%AE%89%E8%A3%85%E6%8F%92%E4%BB%B6

建议您用 1.4 及以后的 kuiper。tdengien 用2.2 及以后版本，目前最新的tdengien为2.4.0.7。如果您用tdengine server 2.4.0.7, 那么安装 kuiper 的 tdengien 插件时，需要指定安装参数为 2.4.0.7

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
