### ISSUE TITLE
vgroup init failed , when creating tables

### ISSUE THREAD

**Issue by Allenscript** [taosdata/TDengine#1025]
运行环境：Ubuntu 12.04  arm32
tdengine 版本：1.6.4
编译环境：gcc 4.8.3
在执行创建表操作的时候，间歇性偶尔的出现创建失败，频率不定，时间不定
重启taosd大部分时间可解决问题
错误log为0.databasename.tablename，vgroup init failed

这是否为bug？

**Comment by plum-lihui** [comment]
请能将建表操作步骤，以及日志文件发送给我们分析一下吗？huili@taosdata.com。
日志估计比较大，可以过滤其中 ERROR 的行，估计就能知道具体原因。
多谢！

**Comment by guanshengliang** [comment]
Several error codes will be added in the next version to clear the reason of the problem
