### ISSUE TITLE
after changing database keep ,no space released

### ISSUE THREAD

**Issue by Bo101010** [taosdata/TDengine#10273]
**Bug Description**
缩短database keep参数后，存储空间没有释放

**To Reproduce**
1.  搭建3*dnodes集群, verson=2.2.2.10
2.  使用tasdemo 把测试数据写入db，replica=3,  keep=3650,  days=10， 测试数据都是2017年的数据。
3.  单节点vnodes磁盘使用1.7GB
4.  alter database test keep 365
5.  select test db中的数据为空， 可以理解，因为数据是2017年的。
6.  vnodes磁盘仍然使用1.7GB，  不能理解。

**Expected Behavior**
vnodes 磁盘空间释放到一个很小的值。

**Screenshots**

**Environment (please complete the following information):**

 - TDengine Version 2.2.2.10

**Comment by yu285** [comment]
一般来说，是需要触发下一次落盘的时候清理数据。

所以可以试着停一下服务，触发落盘

**Comment by Bo101010** [comment]
> 一般来说，是需要触发下一次落盘的时候清理数据。
> 
> 所以可以试着停一下服务，触发落盘

确实重启一个节点，这个节点的磁盘空间就释放了。  请问“触发落盘”的条件什么？  其他两个节点在没有操作的情况下，始终没有磁盘空间回收。

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
