### ISSUE TITLE
timestamp is too big ,and  dump error resulted

### ISSUE THREAD

**Issue by ximply** [taosdata/TDengine#10284]
**Environment (please complete the following information):**
 - OS: CentOS Linux release 7.9.2009 (Core), Linux 5.4.171-1.el7.elrepo.x86_64 #1 SMP Mon Jan 10 18:01:24 EST 2022 x86_64 x86_64 x86_64 GNU/Linux
 - Memory: 64GB  
 - CPU: 40
 - Disk Space: 60TB
 - TDengine Version: 2.4.0.5

 - 如果插入的时间戳字段的值比表中时间戳字段规定大会导致节点挂掉（例如：微秒 往 毫秒 写入）

**Comment by yu285** [comment]
可以提供一下具体的建表语句和复现节点宕掉的sql吗

**Comment by ximply** [comment]
跟特定的sql没有关系，就是时间字段值超出范围就宕了，改成一致的就正常了

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
