### ISSUE TITLE
JDBC Sql Query Count(*) isnull function not supported 

### ISSUE THREAD

**Issue by huangye123** [taosdata/TDengine#10304]
**Bug Description**
select count(*) from table   ===>support

select isnull(count(*),0) from table   ===>not support

ISNULL
   使用指定的替换值替换 NULL。
语法
      ：ISNULL ( check_expression , replacement_value )
参数
   check_expression  将被检查是否为 NULL的表达式。如果不为NULL，这直接返回 该值，也就是 check_expression 这个表达式。如果为空这个直接返回 replacement_value这个表达的内容。。。。check_expression 可以是任何类型的。

**Comment by yu285** [comment]
目前还不支持这个函数

**Comment by huangye123** [comment]
能否新版本增加一下支持呢，比较基本的SQL函数

**Comment by yu285** [comment]
> 能否新版本增加一下支持呢，比较基本的SQL函数

这是我们的刚需功能吗，可以添加下微信 15652223354 沟通下。
