### ISSUE TITLE
where user-info and password saved ？

### ISSUE THREAD

**Issue by zhouyf605** [taosdata/TDengine#10316]
td 用户信息 密码 等保存在哪里  需要迁移  taosdump 没有看到这些表和数据信息
create user test pass 'aaaaaaaa';
alter user test privileges read;

**Comment by yu285** [comment]
需要在新库中自行创建～

**Comment by zhouyf605** [comment]
mnode 的wal  文件里面      迁移要重新创建的   账号密码    还没个show create user 命令

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
