### ISSUE TITLE
taos_subscribe function uses union all to subscribe to multiple tables and raises an exception when taos_fetch_row fetches data

### ISSUE THREAD

**Issue by Eric-Leng** [taosdata/TDengine#10367]
// TDengineTest2.cpp : 此文件包含 "main" 函数。程序执行将在此处开始并结束。
//

#include <iostream>
#include <taos.h>
#include "taoserror.h"
#include <inttypes.h>
#include <Windows.h>
#include <WinBase.h>

int nTotalRows;

void print_result(TAOS_RES* res, int blockFetch) {
	TAOS_ROW    row = NULL;
	int         num_fields = taos_num_fields(res);
	TAOS_FIELD* fields = taos_fetch_fields(res);
	int         nRows = 0;

	if (blockFetch) {
		nRows = taos_fetch_block(res, &row);
		// for (int i = 0; i < nRows; i++) {
		//  taos_print_row(buf, row + i, fields, num_fields);
		//  puts(buf);
		//}
	}
	else {
		while ((row = taos_fetch_row(res))) {
			char buf[4096] = { 0 };
			taos_print_row(buf, row, fields, num_fields);
			puts(buf);
			nRows++;
		}
	}

	nTotalRows += nRows;
	printf("%d rows consumed.\n", nRows);
}

void subscribe_callback(TAOS_SUB* tsub, TAOS_RES* res, void* param, int code) { print_result(res, *(int*)param); }

void check_row_count(int line, TAOS_RES* res, int expected) {
	int      actual = 0;
	TAOS_ROW row;
	while ((row = taos_fetch_row(res))) {
		actual++;
	}
	if (actual != expected) {
		printf("line %d: row count mismatch, expected: %d, actual: %d\n", line, expected, actual);
	}
	else {
		printf("line %d: %d rows consumed as expected\n", line, actual);
	}
}

void do_query(TAOS* taos, const char* sql) {
	TAOS_RES* res = taos_query(taos, sql);
	taos_free_result(res);
}

void run_test(TAOS* taos) {
	do_query(taos, "drop database if exists test;");

	Sleep(1000);
	do_query(taos, "create database test2;");
	Sleep(1000);
	do_query(taos, "use test2;");

	Sleep(1000);
	do_query(taos, "create table meters2(ts timestamp, a int)");

	do_query(taos, "create table meters3(ts timestamp, a int)");

	do_query(taos, "insert into meters2 values('2020-01-01 00:00:00.000', 2);");
	do_query(taos, "insert into meters2 values('2020-01-01 00:01:00.000', 2);");
	do_query(taos, "insert into meters2 values('2020-01-01 00:02:00.000', 2);");
	do_query(taos, "insert into meters2 values('2020-01-01 00:00:00.000', 2);");
	do_query(taos, "insert into meters2 values('2020-01-01 00:01:00.000', 2);");
	do_query(taos, "insert into meters2 values('2020-01-01 00:02:00.000', 2);");
	do_query(taos, "insert into meters2 values('2020-01-01 00:03:00.000', 2);");
	do_query(taos, "insert into meters2 values('2020-01-01 00:00:00.000', 2);");
	do_query(taos, "insert into meters2 values('2020-01-01 00:01:00.000', 2);");
	do_query(taos, "insert into meters2 values('2020-01-01 00:01:01.000', 2);");
	do_query(taos, "insert into meters2 values('2020-01-01 00:01:02.000', 2);");
	do_query(taos, "insert into meters2 values('2020-01-01 00:01:02.000', 2);");
	do_query(taos, "insert into meters2 values('2020-01-01 00:01:02.000', 2);");
	do_query(taos, "insert into meters2 values('2020-01-01 00:01:02.000', 2);");
	do_query(taos, "insert into meters2 values('2020-01-01 00:01:02.000', 2);");
	do_query(taos, "insert into meters2 values('2020-01-01 00:01:02.000', 2);");
	do_query(taos, "insert into meters2 values('2020-01-01 00:01:02.000', 2);");
	do_query(taos, "insert into meters2 values('2020-01-01 00:01:02.000', 2);");

	do_query(taos, "insert into meters3 values('2020-01-01 00:00:00.000', 3);");
	do_query(taos, "insert into meters3 values('2020-01-01 00:01:00.000', 3);");
	do_query(taos, "insert into meters3 values('2020-01-01 00:02:00.000', 3);");
	do_query(taos, "insert into meters3 values('2020-01-01 00:00:00.000', 3);");
	do_query(taos, "insert into meters3 values('2020-01-01 00:01:00.000', 3);");
	do_query(taos, "insert into meters3 values('2020-01-01 00:02:00.000', 3);");
	do_query(taos, "insert into meters3 values('2020-01-01 00:03:00.000', 3);");
	do_query(taos, "insert into meters3 values('2020-01-01 00:00:00.000', 3);");
	do_query(taos, "insert into meters3 values('2020-01-01 00:01:00.000', 3);");
	do_query(taos, "insert into meters3 values('2020-01-01 00:01:01.000', 3);");
	do_query(taos, "insert into meters3 values('2020-01-01 00:01:02.000', 3);");
	do_query(taos, "insert into meters3 values('2020-01-01 00:01:02.000', 3);");
	do_query(taos, "insert into meters3 values('2020-01-01 00:01:02.000', 3);");
	do_query(taos, "insert into meters3 values('2020-01-01 00:01:02.000', 3);");
	do_query(taos, "insert into meters3 values('2020-01-01 00:01:02.000', 3);");
	do_query(taos, "insert into meters3 values('2020-01-01 00:01:02.000', 3);");
	do_query(taos, "insert into meters3 values('2020-01-01 00:01:02.000', 3);");
	do_query(taos, "insert into meters3 values('2020-01-01 00:01:02.000', 3);");

	// super tables subscription
	Sleep(1000);

	TAOS_SUB* tsub = taos_subscribe(taos, 0, "test2", "select * from meters3 union all select * from meters2; ", NULL, NULL, 0);
	TAOS_RES* res = taos_consume(tsub);
	print_result(res, 0);
// 	check_row_count(__LINE__, res, 18);
// 
// 	res = taos_consume(tsub);
// 	check_row_count(__LINE__, res, 0);
// 
// 	do_query(taos, "insert into meters2 values('2020-01-01 00:02:00.001', 2);");
// 	do_query(taos, "insert into meters3 values('2020-01-01 00:01:03.000', 3);");
// 	res = taos_consume(tsub);
// 	check_row_count(__LINE__, res, 2);
// 
// 	do_query(taos, "insert into meters2 values('2020-01-01 00:01:02.001', 2);");
// 	do_query(taos, "insert into meters3 values('2020-01-01 00:03:00.001', 2);");
// 	res = taos_consume(tsub);
// 	check_row_count(__LINE__, res, 2);
// 
// 	do_query(taos, "insert into meters2 values('2020-01-01 00:03:00.002', 2);");
// 	do_query(taos, "insert into meters3 values('2020-01-01 00:03:00.002', 3);");
// 	res = taos_consume(tsub);
// 	check_row_count(__LINE__, res, 1);

	// keep progress information and restart subscription
	taos_unsubscribe(tsub, 1);
// 	do_query(taos, "insert into t0 values('2020-01-01 00:04:00.000', 0);");
// 	tsub = taos_subscribe(taos, 1, "test", "select * from meters2;", NULL, NULL, 0);
// 	res = taos_consume(tsub);
// 	check_row_count(__LINE__, res, 24);
// 
// 	// keep progress information and continue previous subscription
// 	taos_unsubscribe(tsub, 1);
// 	tsub = taos_subscribe(taos, 0, "test", "select * from meters;", NULL, NULL, 0);
// 	res = taos_consume(tsub);
// 	check_row_count(__LINE__, res, 0);
// 
// 	// don't keep progress information and continue previous subscription
// 	taos_unsubscribe(tsub, 0);
// 	tsub = taos_subscribe(taos, 0, "test", "select * from meters;", NULL, NULL, 0);
// 	res = taos_consume(tsub);
// 	check_row_count(__LINE__, res, 24);
// 
// 	// single meter subscription
// 
// 	taos_unsubscribe(tsub, 0);
// 	tsub = taos_subscribe(taos, 0, "test", "select * from t0;", NULL, NULL, 0);
// 	res = taos_consume(tsub);
// 	check_row_count(__LINE__, res, 5);
// 
// 	res = taos_consume(tsub);
// 	check_row_count(__LINE__, res, 0);
// 
// 	do_query(taos, "insert into t0 values('2020-01-01 00:04:00.001', 0);");
// 	res = taos_consume(tsub);
// 	check_row_count(__LINE__, res, 1);
// 
// 	taos_unsubscribe(tsub, 0);
}

static void queryDB(TAOS *taos,const char *command) {
	int       i;
	TAOS_RES *pSql = NULL;
	int32_t   code = -1;

	for (i = 0; i < 5; i++) {
		if (NULL != pSql) {
			taos_free_result(pSql);
			pSql = NULL;
		}

		pSql = taos_query(taos, command);
		code = taos_errno(pSql);
		if (0 == code) {
			break;
		}
	}

	if (code != 0) {
		fprintf(stderr, "Failed to run %s, reason: %s\n", command, taos_errstr(pSql));
		taos_free_result(pSql);
		taos_close(taos);
		exit(EXIT_FAILURE);
	}

	taos_free_result(pSql);
}

void Test(TAOS *taos, char *qstr, int index) {
	printf("==================test at %d\n================================", index);
	queryDB(taos, "drop database if exists demo");
	queryDB(taos, "create database demo");
	TAOS_RES *result;
	queryDB(taos, "use demo");

	queryDB(taos,
		"create table m1 (ts timestamp, ti tinyint, si smallint, i int, bi bigint, f float, d double, b binary(10))");
	printf("success to create table\n");

	int i = 0;
	for (i = 0; i < 10; ++i) {
		sprintf(qstr, "insert into m1 values (%" PRId64 ", %d, %d, %d, %d, %f, %lf, '%s')",
			(uint64_t)(1546300800000 + i * 1000), i, i, i, i * 10000000, i * 1.0, i * 2.0, "hello");
		printf("qstr: %s\n", qstr);

		// note: how do you wanna do if taos_query returns non-NULL
		// if (taos_query(taos, qstr)) {
		//   printf("insert row: %i, reason:%s\n", i, taos_errstr(taos));
		// }
		TAOS_RES *result1 = taos_query(taos, qstr);
		if (result1 == NULL || taos_errno(result1) != 0) {
			printf("failed to insert row, reason:%s,%d\n", taos_errstr(result1), taos_errno(result1));
			std::cout << "1:"<< TAOS_SYSTEM_ERROR(-2147483627) << "\n";
			taos_free_result(result1);
			exit(1);
		}
		else {
			printf("insert row: %i\n", i);
		}
		taos_free_result(result1);
	}
	printf("success to insert rows, total %d rows\n", i);

	// query the records
	sprintf(qstr, "SELECT ti FROM m1");
	result = taos_query(taos, qstr);
	if (result == NULL || taos_errno(result) != 0) {
		printf("failed to select, reason:%s\n", taos_errstr(result));
		taos_free_result(result);
		exit(1);
	}

	TAOS_ROW    row;
	int         rows = 0;
	int         num_fields = taos_field_count(result);
	TAOS_FIELD *fields = taos_fetch_fields(result);

	printf("num_fields = %d\n", num_fields);
	printf("select ti from table, result:\n");
	// fetch the records row by row
	while ((row = taos_fetch_row(result))) {
		char temp[1024] = { 0 };
		rows++;
		taos_print_row(temp, row, fields, num_fields);
		printf("%s\n", temp);
	}

	taos_free_result(result);
	printf("====demo end====\n\n");
}

int main()
{
//     std::cout << "Hello World!\n";
// 	TAOS *taos = taos_connect("192.168.3.147", "root", "taosdata", "test", 0);
// 	if (taos == NULL) {
// 		printf("failed to connect to server, reason:%s\n", "null taos" /*taos_errstr(taos)*/);
// 		exit(1);
// 	}
// 	char qstr[1024];
// 	for (int i = 0; i < 100; i++) {
// 		Test(taos, qstr, i);
// 	}
// 	taos_close(taos);
// 	taos_cleanup();

	const char* host = "127.0.0.1";
	const char* user = "root";
	const char* passwd = "taosdata";
	const char* sql = "select * from meters;";
	const char* topic = "test-multiple";
	int         async = 1, restart = 0, keep = 1, test = 1, blockFetch = 0;

	TAOS* taos = taos_connect("192.168.3.147", "root", "taosdata", NULL, 0);
	if (taos == NULL) {
		printf("failed to connect to db, reason:%s\n", taos_errstr(taos));
		exit(1);
	}

	if (test) {
		run_test(taos);
		taos_close(taos);
		exit(0);
	}

	taos_select_db(taos, "test");
	TAOS_SUB* tsub = NULL;
	if (async) {
		// create an asynchronized subscription, the callback function will be called every 1s
		tsub = taos_subscribe(taos, restart, topic, sql, subscribe_callback, &blockFetch, 1000);
	}
	else {
		// create an synchronized subscription, need to call 'taos_consume' manually
		tsub = taos_subscribe(taos, restart, topic, sql, NULL, NULL, 0);
	}

	if (tsub == NULL) {
		printf("failed to create subscription.\n");
		exit(0);
	}

	if (async) {
		getchar();
	}
	else
		while (1) {
			TAOS_RES* res = taos_consume(tsub);
			if (res == NULL) {
				printf("failed to consume data.");
				break;
			}
			else {
				print_result(res, blockFetch);
				getchar();
			}
		}

	printf("total rows consumed: %d\n", nTotalRows);
	taos_unsubscribe(tsub, keep);
	taos_close(taos);

	return 0;
}

**Comment by yu285** [comment]
we will check on this

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
