### ISSUE TITLE
Is this speed normal for a super table query?

### ISSUE THREAD

**Issue by Aarthas** [taosdata/TDengine#10394]
部署环境：
单机本地部署
系统：ubuntu 20
硬件：4核16G
表结构如下
<img width="1328" alt="WeChat68333be79831c39a8edc815f6e16f506" src="https://user-images.githubusercontent.com/5847572/155542988-75021875-ccf4-4d7b-a505-dd60d17ced43.png">

有157w的数据
使用查询超级表
select * from s_raw where type='register' limit 100；
<img width="1218" alt="WeChat6bb8cbe71f602b41d7fdd8aef4e50eac" src="https://user-images.githubusercontent.com/5847572/155543325-69653c39-8067-49a6-96c3-29967c696070.png">

耗时3s。

若800w数据，执行select * from s_raw where type='register' limit 100；需要耗时 5s，这个正常吗？

看文档，对超级表 的查询应该是很快的。

**Comment by fenghua1997** [comment]
binary设置的过长会影响读写效率的，可根据实际情况配置长度
