### ISSUE TITLE
建议为issue设置labels

### ISSUE THREAD

**Issue by qinzuoyan** [taosdata/TDengine#104]
建议项目的owner可以预设一些label类型，譬如bug, typo, feature, build, refactor, test等等，这样在创建issue时可以指定label进行分类

**Comment by jtao1735** [comment]
是的，必须的

**Comment by hzcheng** [comment]
@qinzuoyan 我们也在探索开源的管理，非常感谢您的建议，希望您继续关注，并提出建议，非常感谢！
