### ISSUE TITLE
Feedback on my experience with TDengine.

### ISSUE THREAD

**Issue by 1486756632** [taosdata/TDengine#10405]
之前有幸看过一篇陶总写的文章，让用户满意之前，要先让程序员满意，当时觉得写的非常好。
以下说点自己用tdengine的体验。
使用tdengine 有三个月了，非常牛逼的性能，暂时还没用到过，目前用到的案例就两个，一个是datax同步数据、一个是edgexfoundry 存储数据。自己遇到的问题都是一些连接问题、缓存问题、jdk权限问题、ekuiper 升级后插件和tdengine不兼容的问题，都是一些基础问题，但是2.4.0.0 到2.4.0.7 这些问题还是存在。给我的感觉是，我本来是想白嫖一下产品的，结果跑过来给taos免费当了一把测试

**Comment by zhouyf605** [comment]
问题相当的多     兼容问题  udp 协议问题    连接问题FQDN  不能解析你提示下哪个域名不能解析  就说不能解析  添加负载均衡下面还要创建两个监听

**Comment by fenghua1997** [comment]
FQDN不能解析这样的异常报错，我们会让报错信息更加友好。
关于协议、缓存、jdk权限等问题，具体的场景能提供一下吗？
