### ISSUE TITLE
mac m1   taospy.     import taos  error

### ISSUE THREAD

**Issue by kevinlim** [taosdata/TDengine#10432]
taos.error.InterfaceError: [0xffff]: unable to load taos C library: dlopen(libtaos.dylib, 0x0006): tried: 'libtaos.dylib' (no such file), '/usr/lib/libtaos.dylib' (no such file), '/Users/kevinlin/mywar/libtaos.dylib' (no such file), '/usr/lib/libtaos.dylib' (no such file)

**Comment by sangshuduo** [comment]
So far the Mac is still not officially supported. You need to compile TDengine yourself to generate libtaos.dylib.

**Comment by arielyang** [comment]
> My computer is a MAC M1. I built it according to the method on the official website, but I still have this problem.
> mkdir debug && cd debug
> cmake .. && cmake --build .
> Exception in thread "main" java.lang.UnsatisfiedLinkError: ...... (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')

I'm not sure what's your problem? Want to build taosd or use tospy? I saw you paste Java error.

**Comment by Booooooger** [comment]
> 

有计划什么时间支持吗？
