### ISSUE TITLE
error: import csv file

### ISSUE THREAD

**Issue by saiyn** [taosdata/TDengine#1045]
执行`import into ed211_p867857035305833 file temp.csv`一直报错
`DB error: invalid SQL: near "BLE" syntax error`
csv文件如下，完全搞不懂“BLE”是哪里来的

`ts,speed,slide_oil_mpa,slide_oil_tem,water_out_tem,water_mpa,air_start_mpa,fuel_oil_mpa,air_press_mpa,alarm1,alarm2
'2019-12-27 13:48:35',170,0.0,0,23,0.0,0.0,0.0,0.0,32,240
'2019-12-27 13:48:36',168,0.0,0,23,0.0,0.0,0.0,0.0,32,240
'2019-12-27 13:48:37',166,0.0,0,23,0.0,0.0,0.0,0.0,32,240
'2019-12-27 13:48:38',168,0.0,0,23,0.0,0.0,0.0,0.0,32,240
'2019-12-27 13:48:39',166,0.0,0,23,0.0,0.0,0.0,0.0,32,240
'2019-12-27 13:48:40',162,0.0,0,23,0.0,0.0,0.0,0.0,32,240
'2019-12-27 13:48:41',164,0.0,0,23,0.0,0.0,0.0,0.0,32,240
`

**Comment by hjxilinx** [comment]
can you please provide more detailed information.
taosd versioin?
platform of client, Windows or Linux?

I have try the script you provided above, and get the following results.
![屏幕快照 2020-01-02 下午1 39 48](https://user-images.githubusercontent.com/8252296/71653067-6c4aa700-2d65-11ea-94a5-fab7092ac39b.png)

**Comment by saiyn** [comment]
thank for your help, please check following more specific infor
![taos-version](https://user-images.githubusercontent.com/7022424/71655384-65299600-2d71-11ea-8bc8-c8eadc552e68.png)

![tables](https://user-images.githubusercontent.com/7022424/71655390-71adee80-2d71-11ea-9474-e4fdb1a6fb57.png)

![select](https://user-images.githubusercontent.com/7022424/71655399-796d9300-2d71-11ea-90b9-92cc1b80bea2.png)

**Comment by hjxilinx** [comment]
How many records are imported before the error occurs?

**Comment by saiyn** [comment]
no import success, all import cmd failed, and just very few insert before.

![count](https://user-images.githubusercontent.com/7022424/71703105-fd755880-2e0d-11ea-8b95-3993ad8c8d09.png)

**Comment by saiyn** [comment]
since just a few insert data in the table, I dump them out here.

[dump.tar.gz](https://github.com/taosdata/TDengine/files/4017901/dump.tar.gz)

**Comment by hjxilinx** [comment]
OK, it would be helpful if you could show me the client log, namely  ```taoslogxx``` or something located in ```/var/log/taos``` by default. But make sure the option ```debugflag 135``` is set in the configuration file before you execute the ```import``` command.

If the log file is too large to post here, you can email it to   <hjliao@taosdata.com>;

**Comment by saiyn** [comment]
ok, here is  what i think you want to check in the log:

![taolog](https://user-images.githubusercontent.com/7022424/71704797-69a88a00-2e17-11ea-9980-523d1dbed9ca.png)

and below is the whole logfile


[taoslog.tar.gz](https://github.com/taosdata/TDengine/files/4017994/taoslog.tar.gz)

**Comment by hjxilinx** [comment]
I've checked the log file already, but failed to figure out what happened.
So, could you please sent me some script of you data set if possible, I' ll try it.

**Comment by saiyn** [comment]
what do you mean of "some script of data set" and from the log I think the problem is "no records(-1) in file temp.csv", so could you please help me check why tdegine says no records in temp.csv?

[temp_csv.tar.gz](https://github.com/taosdata/TDengine/files/4019039/temp_csv.tar.gz)

**Comment by hjxilinx** [comment]
The data file you post, I have tried myself, and get 18 records into the db. 
The last row failed to loaded to db because the last two records have identical timestamp.

**Comment by hjxilinx** [comment]
I could provide remote assistance by logining into your computer to check what happened if it is convenient for you tomorrow morning.

**Comment by saiyn** [comment]
真是无语了，你们为什么不在文档里面加上注释：import csv文件时，csv文件不能带表头字段，而只能是数据。
@hjxilinx 当你看到我贴出来的csv文件时，你为什么没有提醒我需要去掉csv文件的第一行表头？难道你有直接import我贴出来的csv文件，一点没有修改直接就import成功了？

**Comment by saiyn** [comment]
thanks for your help, after so many days later i just figure out that the csv file should not contains header info.

**Comment by arthur19q3** [comment]
When comparing the CSV handling capabilities of TaosEngine with ClickHouse's latest updates, it's apparent that TaosEngine developers might not have fully considered user convenience and common needs. ClickHouse's automatic detection of headers in CSV files starting from version 23.1 illustrates a significant improvement in usability and efficiency, a feature that if absent in TaosEngine, could be viewed as a lack of responsiveness to the practical requirements of users.
