### ISSUE TITLE
Using distinct to manipulate label columns

### ISSUE THREAD

**Issue by WangJingLoong** [taosdata/TDengine#10469]
- OS: [e.g. CentOS 8.0]
 - TDengine Version [2.4.0.5]
官网介绍可以使用distinct对标签列和普通列，
可是我使用 标签列提示错误
![image](https://user-images.githubusercontent.com/100544530/156108259-b6314018-abb2-422f-93e7-86bc278090a0.png)

**Comment by fenghua1997** [comment]
您可以在 select distinct mytype 后面加上 ts 字段试试。

**Comment by WangJingLoong** [comment]
> 您可以在 select distinct mytype 后面加上 ts 字段试试。

本身ts就是唯一的。。。
加上了ts，相当于distinct函数失效了啊没法去重了就。。。

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
