### ISSUE TITLE
When TDengine cluster was configured under the SLB , can‘t be connected

### ISSUE THREAD

**Issue by zhouyf605** [taosdata/TDengine#10470]
td 集群挂到负载均衡后面  内网ip 访问 因为可以配置集群节点的本地解析没有问题，外网访问报错  明显是要检测心跳没有响应  集群是正常的  

我不明白为啥客户端要去检测心跳？  心跳不应该是集群内部mnode 内部检测么 ？  集群内部都是FQDN的   客户端请求Ep   Ep 返回可以使用的mnode  dnode  处理后面的连接请求就可以了啊  

hosts 文件
外网ip    td.taos.com

taos.cfg 
firstEp:                td.taos.com:16030

debug 信息

==================================================
                new log file                      
==================================================
03/01 13:39:12.935000 00005112 UTL all debug flag are set to 135
03/01 13:39:12.935000 00005112 UTL all debug flag are set to 135
03/01 13:39:12.944000 00005112 UTL localEp is: USER-20200213VQ:6030
03/01 13:39:12.944000 00005112 UTL timezone not configured, use default
03/01 13:39:12.945000 00005112 UTL locale not configured, set to default:Chinese (Simplified)_People's Republic of China.936
03/01 13:39:12.945000 00005112 UTL charset not configured, set to default:cp936
03/01 13:39:12.945000 00005112 UTL    check global cfg completed
03/01 13:39:12.945000 00005112 UTL ==================================
03/01 13:39:12.945000 00005112 UTL         config & system info:
03/01 13:39:12.945000 00005112 UTL ==================================
03/01 13:39:12.945000 00005112 UTL  firstEp:                td.taos.com:16030 
03/01 13:39:12.945000 00005112 UTL  secondEp:               USER-20200213VQ:6030 
03/01 13:39:12.945000 00005112 UTL  fqdn:                   USER-20200213VQ 
03/01 13:39:12.945000 00005112 UTL  serverPort:             6030 
03/01 13:39:12.945000 00005112 UTL  configDir:              C:\TDengine\cfg 
03/01 13:39:12.945000 00005112 UTL  logDir:                 C:\TDengine\log 
03/01 13:39:12.945000 00005112 UTL  scriptDir:              C:/TDengine/script 
03/01 13:39:12.945000 00005112 UTL  arbitrator:              
03/01 13:39:12.945000 00005112 UTL  numOfThreadsPerCore:    1.000000 
03/01 13:39:12.945000 00005112 UTL  maxNumOfDistinctRes:    10000000 
03/01 13:39:12.945000 00005112 UTL  rpcTimer:               300(ms)
03/01 13:39:12.945000 00005112 UTL  rpcMaxTime:             600(s)
03/01 13:39:12.945000 00005112 UTL  rpcForceTcp:            0 
03/01 13:39:12.945000 00005112 UTL  shellActivityTimer:     3(s)
03/01 13:39:12.945000 00005112 UTL  compressMsgSize:        524288 
03/01 13:39:12.945000 00005112 UTL  maxSQLLength:           1048576(byte)
03/01 13:39:12.945000 00005112 UTL  maxWildCardsLength:     100(byte)
03/01 13:39:12.945000 00005112 UTL  maxNumOfOrderedRes:     1000000 
03/01 13:39:12.945000 00005112 UTL  keepColumnName:         1 
03/01 13:39:12.945000 00005112 UTL  timezone:               not configured 
03/01 13:39:12.945000 00005112 UTL  locale:                 Chinese (Simplified)_People's Republic of China.936 
03/01 13:39:12.945000 00005112 UTL  charset:                cp936 
03/01 13:39:12.945000 00005112 UTL  numOfLogLines:          10000000 
03/01 13:39:12.945000 00005112 UTL  logKeepDays:            0 
03/01 13:39:12.945000 00005112 UTL  asyncLog:               1 
03/01 13:39:12.945000 00005112 UTL  debugFlag:              135 
03/01 13:39:12.945000 00005112 UTL  rpcDebugFlag:           135 
03/01 13:39:12.945000 00005112 UTL  tmrDebugFlag:           131 
03/01 13:39:12.945000 00005112 UTL  cDebugFlag:             135 
03/01 13:39:12.945000 00005112 UTL  jniDebugFlag:           135 
03/01 13:39:12.945000 00005112 UTL  odbcDebugFlag:          135 
03/01 13:39:12.945000 00005112 UTL  uDebugFlag:             135 
03/01 13:39:12.945000 00005112 UTL  qDebugFlag:             135 
03/01 13:39:12.945000 00005112 UTL  tsdbDebugFlag:          135 
03/01 13:39:12.945000 00005112 UTL  gitinfo:                238545f71370b3b75db5ba653b2f06fa81faa894 
03/01 13:39:12.945000 00005112 UTL  gitinfoOfInternal:      63d0854c8436996e385efc2a5b32661dcd4292ff 
03/01 13:39:12.945000 00005112 UTL  buildinfo:              Built at 2021-12-16 16:23:11 
03/01 13:39:12.945000 00005112 UTL  version:                2.2.2.10 
03/01 13:39:12.945000 00005112 UTL  maxBinaryDisplayWidth:  30 
03/01 13:39:12.945000 00005112 UTL  tempDir:                C:\Users\ADMINI~1\AppData\Local\Temp 
03/01 13:39:12.945000 00005112 UTL  os numOfCores:          4
03/01 13:39:12.945000 00005112 UTL  os totalMemory:         3884(MB)
03/01 13:39:12.945000 00005112 UTL ==================================
03/01 13:39:12.945000 00005112 UTL  dataDir: C:/TDengine/data level:0 primary:1
03/01 13:39:12.945000 00005112 UTL ==================================
03/01 13:39:12.948000 00005112 TSC starting to initialize client ...
03/01 13:39:12.948000 00005112 TSC Local End Point is:USER-20200213VQ:6030
03/01 13:39:12.949000 00005112 UTL tsc scheduler is initialized, numOfThreads:2
03/01 13:39:12.949000 00005112 TSC client task queue is initialized, numOfWorkers: 2
03/01 13:39:12.949000 00005112 UTL tmr scheduler is initialized, numOfThreads:1
03/01 13:39:12.950000 00005112 TSC TableMeta:0000000000479300, vgroup:00000000004791C0 is initialized
03/01 13:39:12.950000 00005112 TSC client is initialized successfully
03/01 13:39:12.950000 00005064 UTL cache refresh thread starts
03/01 13:39:12.950000 00005112 TSC try to create a connection to (null):6030, user:root db:(null)
03/01 13:39:12.950000 00005112 UTL pool:000000000049B100 is setup, maxId:5000
03/01 13:39:12.950000 00005112 UTL open udp socket:0x0:0
03/01 13:39:12.951000 00005112 UTL open udp socket:0x0:0
03/01 13:39:12.951000 00006276 RPC TSC UDP thread is created, index:0
03/01 13:39:12.951000 00005112 RPC TSC UDP connection is initialized, ip:0:0 threads:2
03/01 13:39:12.951000 00005112 RPC TSC rpc is opened, threads:2 sessions:5000
03/01 13:39:12.951000 00005112 UTL cache:rpcObj, key:000000000024EFA0, 0000000004A63E20 added into cache, added:1646113152951, expire:1646113157951, totalNum:1 totalSize:606bytes size:520bytes
03/01 13:39:12.951000 00005112 TSC 0x2 new SqlObj from 0000000004A64050, total in tscObj:1, total:1
03/01 13:39:12.951000 00005096 RPC TSC UDP thread is created, index:1
03/01 13:39:12.951000 00005112 TSC 0x2 SQL cmd:connect will be processed, name:, type:0
03/01 13:39:12.951000 00005112 RPC TSC 0000000004C501B8 client connection is allocated, uid:0x4c5698b
03/01 13:39:12.951000 00005112 RPC TSC UDP connection is setup, ip:1966ab4:16030 localPort:50790
03/01 13:39:12.952000 00005112 RPC TSC 0000000004C501B8 0000000000000002, connect is sent to td.taos.com:16030, len:377 sig:0x01000000:0x00000000:20852
03/01 13:39:12.959000 00005096 RPC TSC 0000000004C501B8 0000000000000002, connect-rsp received from 0x1966ab4:16030, parse code:0x0 len:811 sig:0xda100000:0x01000000:20852 code:0x0
03/01 13:39:12.959000 00005096 TSC 0x2 reset retry counter to be 0 due to success rsp, old:0
03/01 13:39:12.960000 00005096 TSC 0x2 SQL cmd:connect, code:success rspLen:723
03/01 13:39:12.960000 00005096 TSC 0x2 epSet.fqdn[0]: td-cluster01.taos.com, pObj:0000000004A64050
03/01 13:39:12.960000 00005096 TSC 0x2 epSet.fqdn[1]: td-cluster02.taos.com, pObj:0000000004A64050
03/01 13:39:12.960000 00005096 TSC 0x2 epSet.fqdn[2]: td-cluster03.taos.com, pObj:0000000004A64050
03/01 13:39:12.960000 00005096 TSC 0x3 new SqlObj from 0000000004A64050, total in tscObj:2, total:2
03/01 13:39:12.960000 00005096 TSC 0x3 HB is allocated, pObj:0000000004A64050
03/01 13:39:12.960000 00005112 TSC 0000000004A64050 DB connection is opening, rpcObj: 0000000004A63E20, dnodeConn:000000000048B160
03/01 13:39:12.960000 00005112 TSC 0x2 free sqlObj in cache
03/01 13:39:12.960000 00005112 TSC 0x2 free SqlObj, total in tscObj:1, total:1
03/01 13:39:12.960000 00005112 TSC 0x2 start to free sqlObj
03/01 13:39:12.960000 00005112 TSC 0x2 addr:0000000004A643C0 free completed
03/01 13:39:14.464000 00002496 TSC 0x3 SQL cmd:heart-beat will be processed, name:, type:0
03/01 13:39:14.464000 00002496 RPC TSC 0000000004C50330 client connection is allocated, uid:0x4c519b9
03/01 13:39:14.464000 00002496 RPC TSC UDP connection is setup, ip:1966ab4:6030 localPort:50789
03/01 13:39:14.464000 00002496 RPC TSC 0000000004C50330 0000000000000003, heartbeat is sent to td-cluster02.taos.com:6030, len:140 sig:0x02000000:0x00000000:42
03/01 13:39:14.769000 00002496 RPC TSC 0000000004C50330 0000000000000003, expected heartbeat-rsp is not received
03/01 13:39:14.769000 00002496 RPC TSC 0000000004C50330 0000000000000003, re-send msg:heartbeat to td-cluster02.taos.com:6030
03/01 13:39:14.769000 00002496 RPC TSC 0000000004C50330 0000000000000003, heartbeat is sent to td-cluster02.taos.com:6030, len:140 sig:0x02000000:0x00000000:42
03/01 13:39:15.069000 00002496 RPC TSC 0000000004C50330 0000000000000003, expected heartbeat-rsp is not received
03/01 13:39:15.069000 00002496 RPC TSC 0000000004C50330 0000000000000003, re-send msg:heartbeat to td-cluster02.taos.com:6030
03/01 13:39:15.069000 00002496 RPC TSC 0000000004C50330 0000000000000003, heartbeat is sent to td-cluster02.taos.com:6030, len:140 sig:0x02000000:0x00000000:42
03/01 13:39:15.369000 00002496 RPC TSC 0000000004C50330 0000000000000003, expected heartbeat-rsp is not received
03/01 13:39:15.369000 00002496 RPC TSC 0000000004C50330 0000000000000003, re-send msg:heartbeat to td-cluster02.taos.com:6030
03/01 13:39:15.369000 00002496 RPC TSC 0000000004C50330 0000000000000003, heartbeat is sent to td-cluster02.taos.com:6030, len:140 sig:0x02000000:0x00000000:42
03/01 13:39:15.669000 00002496 RPC TSC 0000000004C50330 0000000000000003, expected heartbeat-rsp is not received
03/01 13:39:15.669000 00002496 RPC TSC 0000000004C50330 0000000000000003, failed to send msg:heartbeat to td-cluster02.taos.com:6030
03/01 13:39:15.669000 00002496 RPC TSC 0000000004C50330 0000000000000003, rpc connection is released
03/01 13:39:15.674000 00002496 RPC TSC 0000000000000003, connection error happens

**Comment by fenghua1997** [comment]
请注意配置 udp 转发

**Comment by xiaohuizhang** [comment]
请问如何配置，有相关文档吗

**Comment by zhouyf605** [comment]
TD集群就是按照官网文档配置的，slb 我们是天翼云的slb  应该就是nginx 基于连接的tcp 转发   这个网上有很多的







在 2022-10-09 17:06:02，"张晓晖" ***@***.***> 写道：

请问如何配置，有相关文档吗
