### ISSUE TITLE
官网使用文档不够明细

### ISSUE THREAD

**Issue by kevinsingapore** [taosdata/TDengine#105]
官网使用文档不够明细，希望可以更细化。

**Comment by hzcheng** [comment]
非常感谢您的建议。由于我们还在摸索开源，有些事情做的确实不够周到。我们会尽力完善，非常感谢您的关注。

**Comment by Adhders** [comment]
> 非常感谢您的建议。由于我们还在摸索开源，有些事情做的确实不够周到。我们会尽力完善，非常感谢您的关注。

怎么注册账户这么基本的内容都没有啊，以下参数怎么设置啊？
   # @host     : TDengine server IP address 
    # @user     : Username used to connect to TDengine server
    # @password : Password 
    # @database : Database to use when connecting to TDengine server
    # @config   : Configuration directory

**Comment by guanshengliang** [comment]
您可以详细描述要实现的功能

TDengine开源版，只存在用户概念，没有账户概念
