### ISSUE TITLE
DB error: syntax error near "topic nchar(255),  qos tinyint,  payload bin (0.000000s) with simple test case.

### ISSUE THREAD

**Issue by zhonghuali** [taosdata/TDengine#10504]
**Bug Description**
DB error: syntax error near "topic nchar(255),  qos tinyint,  payload bin (0.000000s) with simple test case.

**To Reproduce**
跟随这个列子:https://docs.emqx.com/zh/enterprise/v4.4/rule/backend_tdengine.html#%E5%8E%9F%E7%94%9F%E6%96%B9%E5%BC%8F-%E4%BC%81%E4%B8%9A%E7%89%88

1. 启动tdengine容器 ,版本 tdengine/tdengine:2.4.0.7
2. window 环境,taos shell 
3. create database test;
4. use test;
CREATE TABLE t_mqtt_msg (
  ts timestamp,
 	msgid NCHAR(64),
  topic NCHAR(255),
  qos TINYINT,
  payload BINARY(1024),
  arrived timestamp
);
5. See error
DB error: syntax error near "topic nchar(255),  qos tinyint,  payload bin (0.000000s) 
**Expected Behavior**
should be created successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/8972381/156330959-0f678e3f-717e-4fb6-9618-f2817f88fa6f.png)

**Additional Context**
如果创建语句里的, 字段topic,改成 topic1,则可以成功. 
CREATE TABLE t_mqtt_msg (  ts timestamp,  msgid NCHAR(64),  topic1 NCHAR(255),  qos TINYINT,  payload BINARY(1024),  arrived timestamp );

**Comment by fenghua1997** [comment]
你好，topic 是 TDengine 保留的关键词，相关关键词您可以在 https://www.taosdata.com/docs/cn/v2.0/administrator#tdengine-2 文档上查看 「TDengine 参数限制与保留关键字」部分。

**Comment by zhonghuali** [comment]
了解,如果错误提示能更有好些,就更好了
