### ISSUE TITLE
 taos-jdbcdriver  throw exception: String index out of range: -5  when rest model with param  timestampFormat=UTC 

### ISSUE THREAD

**Issue by liangbinc** [taosdata/TDengine#10514]
**Bug Description**

**To Reproduce**
1.  jdbc:TAOS-RS://hostip:6041/dbname?timezone=Asia/Shanghai&charset=UTF-8&locale=en_US.UTF-8&timestampFormat=UTC
2.  sql:  select sum(car_num) as flowrate from dbname.target WHERE ts>='2022-03-01 16:00:38' and ts<'2022-03-02 17:00:38' and dimension_type=1  and target_type =1 interval(1h) sliding(15m) fill(value,0)  
3. Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -5
	at java.lang.String.substring(String.java:1967)
	at com.taosdata.jdbc.rs.RestfulResultSet.parseTimestampColumnData(RestfulResultSet.java:243)
	at com.taosdata.jdbc.rs.RestfulResultSet.parseColumnData(RestfulResultSet.java:184)
	at com.taosdata.jdbc.rs.RestfulResultSet.<init>(RestfulResultSet.java:99)

**Expected Behavior**
`The right result : `{"status":"succ","head":["ts","flowrate"],"column_meta":[["ts",9,8],["flowrate",5,8]],"data":[["2022-03-01T15:15:00.000000+0800",0],["2022-03-01T15:30:00.000000+0800",0],["2022-03-01T15:45:00.000000+0800",0],["2022-03-01T16:00:00.000000+0800",0],["2022-03-01T16:15:00.000000+0800",0],["2022-03-01T16:30:00.000000+0800",0],["2022-03-01T16:45:00.000000+0800",0],["2022-03-01T17:00:00.000000+0800",0],["2022-03-01T17:15:00.000000+0800",0],["2022-03-01T17:30:00.000000+0800",0],["2022-03-01T17:45:00.000000+0800",0],["2022-03-01T18:00:00.000000+0800",0],["2022-03-01T18:15:00.000000+0800",0],["2022-03-01T18:30:00.000000+0800",0],["2022-03-01T18:45:00.000000+0800",0],["2022-03-01T19:00:00.000000+0800",0],["2022-03-01T19:15:00.000000+0800",0],["2022-03-01T19:30:00.000000+0800",0],["2022-03-01T19:45:00.000000+0800",0],["2022-03-01T20:00:00.000000+0800",0],["2022-03-01T20:15:00.000000+0800",0],["2022-03-01T20:30:00.000000+0800",0],["2022-03-01T20:45:00.000000+0800",0],["2022-03-01T21:00:00.000000+0800",0],["2022-03-01T21:15:00.000000+0800",0],["2022-03-01T21:30:00.000000+0800",0],["2022-03-01T21:45:00.000000+0800",0],["2022-03-01T22:00:00.000000+0800",0],["2022-03-01T22:15:00.000000+0800",0],["2022-03-01T22:30:00.000000+0800",0],["2022-03-01T22:45:00.000000+0800",0],["2022-03-01T23:00:00.000000+0800",0],["2022-03-01T23:15:00.000000+0800",0],["2022-03-01T23:30:00.000000+0800",0],["2022-03-01T23:45:00.000000+0800",0],["2022-03-02T00:00:00.000000+0800",0],["2022-03-02T00:15:00.000000+0800",0],["2022-03-02T00:30:00.000000+0800",0],["2022-03-02T00:45:00.000000+0800",0],["2022-03-02T01:00:00.000000+0800",0],["2022-03-02T01:15:00.000000+0800",0],["2022-03-02T01:30:00.000000+0800",0],["2022-03-02T01:45:00.000000+0800",0],["2022-03-02T02:00:00.000000+0800",0],["2022-03-02T02:15:00.000000+0800",0],["2022-03-02T02:30:00.000000+0800",0],["2022-03-02T02:45:00.000000+0800",0],["2022-03-02T03:00:00.000000+0800",0],["2022-03-02T03:15:00.000000+0800",0],["2022-03-02T03:30:00.000000+0800",0],["2022-03-02T03:45:00.000000+0800",0],["2022-03-02T04:00:00.000000+0800",0],["2022-03-02T04:15:00.000000+0800",0],["2022-03-02T04:30:00.000000+0800",0],["2022-03-02T04:45:00.000000+0800",0],["2022-03-02T05:00:00.000000+0800",0],["2022-03-02T05:15:00.000000+0800",0],["2022-03-02T05:30:00.000000+0800",0],["2022-03-02T05:45:00.000000+0800",0],["2022-03-02T06:00:00.000000+0800",0],["2022-03-02T06:15:00.000000+0800",0],["2022-03-02T06:30:00.000000+0800",0],["2022-03-02T06:45:00.000000+0800",0],["2022-03-02T07:00:00.000000+0800",0],["2022-03-02T07:15:00.000000+0800",0],["2022-03-02T07:30:00.000000+0800",0],["2022-03-02T07:45:00.000000+0800",0],["2022-03-02T08:00:00.000000+0800",0],["2022-03-02T08:15:00.000000+0800",0],["2022-03-02T08:30:00.000000+0800",0],["2022-03-02T08:45:00.000000+0800",0],["2022-03-02T09:00:00.000000+0800",0],["2022-03-02T09:15:00.000000+0800",0],["2022-03-02T09:30:00.000000+0800",0],["2022-03-02T09:45:00.000000+0800",0],["2022-03-02T10:00:00.000000+0800",0],["2022-03-02T10:15:00.000000+0800",0],["2022-03-02T10:30:00.000000+0800",0],["2022-03-02T10:45:00.000000+0800",0],["2022-03-02T11:00:00.000000+0800",0],["2022-03-02T11:15:00.000000+0800",0],["2022-03-02T11:30:00.000000+0800",0],["2022-03-02T11:45:00.000000+0800",0],["2022-03-02T12:00:00.000000+0800",0],["2022-03-02T12:15:00.000000+0800",0],["2022-03-02T12:30:00.000000+0800",0],["2022-03-02T12:45:00.000000+0800",0],["2022-03-02T13:00:00.000000+0800",0],["2022-03-02T13:15:00.000000+0800",0],["2022-03-02T13:30:00.000000+0800",0],["2022-03-02T13:45:00.000000+0800",0],["2022-03-02T14:00:00.000000+0800",0],["2022-03-02T14:15:00.000000+0800",0],["2022-03-02T14:30:00.000000+0800",0],["2022-03-02T14:45:00.000000+0800",0],["2022-03-02T15:00:00.000000+0800",0],["2022-03-02T15:15:00.000000+0800",0],["2022-03-02T15:30:00.000000+0800",0],["2022-03-02T15:45:00.000000+0800",209],["2022-03-02T16:00:00.000000+0800",431],["2022-03-02T16:15:00.000000+0800",440],["2022-03-02T16:30:00.000000+0800",440],["2022-03-02T16:45:00.000000+0800",231],["2022-03-02T17:00:00.000000+0800",9]],"rows":104}``

**Screenshots**
`curl -u root:taosdata -d "select sum(car_num) as flowrate from ctfo_crossing.target WHERE ts>='2022-03-01 16:00:38' and ts<'2022-03-02 17:00:38' and dimension_type=1  and target_type =1 interval(1h) sliding(15m) fill(value,0)" localhost:6041/rest/sqlutc/ctfo_crossing

{"status":"succ","head":["ts","flowrate"],"column_meta":[["ts",9,8],["flowrate",5,8]],"data":[["2022-03-01T07:15:00Z",0],["2022-03-01T07:30:00Z",0],["2022-03-01T07:45:00Z",0],["2022-03-01T08:00:00Z",0],["2022-03-01T08:15:00Z",0],["2022-03-01T08:30:00Z",0],["2022-03-01T08:45:00Z",0],["2022-03-01T09:00:00Z",0],["2022-03-01T09:15:00Z",0],["2022-03-01T09:30:00Z",0],["2022-03-01T09:45:00Z",0],["2022-03-01T10:00:00Z",0],["2022-03-01T10:15:00Z",0],["2022-03-01T10:30:00Z",0],["2022-03-01T10:45:00Z",0],["2022-03-01T11:00:00Z",0],["2022-03-01T11:15:00Z",0],["2022-03-01T11:30:00Z",0],["2022-03-01T11:45:00Z",0],["2022-03-01T12:00:00Z",0],["2022-03-01T12:15:00Z",0],["2022-03-01T12:30:00Z",0],["2022-03-01T12:45:00Z",0],["2022-03-01T13:00:00Z",0],["2022-03-01T13:15:00Z",0],["2022-03-01T13:30:00Z",0],["2022-03-01T13:45:00Z",0],["2022-03-01T14:00:00Z",0],["2022-03-01T14:15:00Z",0],["2022-03-01T14:30:00Z",0],["2022-03-01T14:45:00Z",0],["2022-03-01T15:00:00Z",0],["2022-03-01T15:15:00Z",0],["2022-03-01T15:30:00Z",0],["2022-03-01T15:45:00Z",0],["2022-03-01T16:00:00Z",0],["2022-03-01T16:15:00Z",0],["2022-03-01T16:30:00Z",0],["2022-03-01T16:45:00Z",0],["2022-03-01T17:00:00Z",0],["2022-03-01T17:15:00Z",0],["2022-03-01T17:30:00Z",0],["2022-03-01T17:45:00Z",0],["2022-03-01T18:00:00Z",0],["2022-03-01T18:15:00Z",0],["2022-03-01T18:30:00Z",0],["2022-03-01T18:45:00Z",0],["2022-03-01T19:00:00Z",0],["2022-03-01T19:15:00Z",0],["2022-03-01T19:30:00Z",0],["2022-03-01T19:45:00Z",0],["2022-03-01T20:00:00Z",0],["2022-03-01T20:15:00Z",0],["2022-03-01T20:30:00Z",0],["2022-03-01T20:45:00Z",0],["2022-03-01T21:00:00Z",0],["2022-03-01T21:15:00Z",0],["2022-03-01T21:30:00Z",0],["2022-03-01T21:45:00Z",0],["2022-03-01T22:00:00Z",0],["2022-03-01T22:15:00Z",0],["2022-03-01T22:30:00Z",0],["2022-03-01T22:45:00Z",0],["2022-03-01T23:00:00Z",0],["2022-03-01T23:15:00Z",0],["2022-03-01T23:30:00Z",0],["2022-03-01T23:45:00Z",0],["2022-03-02T00:00:00Z",0],["2022-03-02T00:15:00Z",0],["2022-03-02T00:30:00Z",0],["2022-03-02T00:45:00Z",0],["2022-03-02T01:00:00Z",0],["2022-03-02T01:15:00Z",0],["2022-03-02T01:30:00Z",0],["2022-03-02T01:45:00Z",0],["2022-03-02T02:00:00Z",0],["2022-03-02T02:15:00Z",0],["2022-03-02T02:30:00Z",0],["2022-03-02T02:45:00Z",0],["2022-03-02T03:00:00Z",0],["2022-03-02T03:15:00Z",0],["2022-03-02T03:30:00Z",0],["2022-03-02T03:45:00Z",0],["2022-03-02T04:00:00Z",0],["2022-03-02T04:15:00Z",0],["2022-03-02T04:30:00Z",0],["2022-03-02T04:45:00Z",0],["2022-03-02T05:00:00Z",0],["2022-03-02T05:15:00Z",0],["2022-03-02T05:30:00Z",0],["2022-03-02T05:45:00Z",0],["2022-03-02T06:00:00Z",0],["2022-03-02T06:15:00Z",0],["2022-03-02T06:30:00Z",49],["2022-03-02T06:45:00Z",49],["2022-03-02T07:00:00Z",49],["2022-03-02T07:15:00Z",49],["2022-03-02T07:30:00Z",0],["2022-03-02T07:45:00Z",0],["2022-03-02T08:00:00Z",0],["2022-03-02T08:15:00Z",0],["2022-03-02T08:30:00Z",0],["2022-03-02T08:45:00Z",0],["2022-03-02T09:00:00Z",0]],"rows":104}`

**Environment (please complete the following information):**
 - OS: client in windows ; TDengine in docker container
 - TDengine 2.2.0.5 upgrade 2.4.0.0:
 

**Additional Context**

curl -u root:taosdata -d "select sum(car_num) as flowrate from ctfo_crossing.target WHERE ts>='2022-03-01 16:00:38' and ts<'2022-03-02 17:00:38' and dimension_type=1  and target_type =1 interval(1h) sliding(15m) fill(value,0)" localhost:6041/rest/sqlutc/ctfo_crossing

The time timestamp format "2022-03-02T02:00:00Z"  

The jdbc-driver code: com.taosdata.jdbc.rs.RestfulResultSet#parseTimestampColumnData

`case UTC: {
                String value = row.getString(colIndex);
                if (value.lastIndexOf(":") > 19) {
                    ZonedDateTime parse = ZonedDateTime.parse(value, rfc3339Parser);
                    long nanoAdjustment;
                    if (value.length() > 32) {
                        // ns timestamp: yyyy-MM-ddTHH:mm:ss.SSSSSSSSS+0x:00
                        this.timestampPrecision = TimestampPrecision.NS;
                    } else if (value.length() > 29) {
                        // ms timestamp: yyyy-MM-ddTHH:mm:ss.SSSSSS+0x:00
                        this.timestampPrecision = TimestampPrecision.US;
                    } else {
                        // ms timestamp: yyyy-MM-ddTHH:mm:ss.SSS+0x:00
                        this.timestampPrecision = TimestampPrecision.MS;
                    }
                    return Timestamp.from(parse.toInstant());
                } else {
                    long epochSec = Timestamp.valueOf(value.substring(0, 19).replace("T", " ")).getTime() / 1000;
                    int fractionalSec = Integer.parseInt(value.substring(20, value.length() - 5));
                    long nanoAdjustment;
                    if (value.length() > 32) {
                        // ns timestamp: yyyy-MM-ddTHH:mm:ss.SSSSSSSSS+0x00
                        nanoAdjustment = fractionalSec;
                        this.timestampPrecision = TimestampPrecision.NS;
                    } else if (value.length() > 29) {
                        // ms timestamp: yyyy-MM-ddTHH:mm:ss.SSSSSS+0x00
                        nanoAdjustment = fractionalSec * 1000L;
                        this.timestampPrecision = TimestampPrecision.US;
                    } else {
                        // ms timestamp: yyyy-MM-ddTHH:mm:ss.SSS+0x00
                        nanoAdjustment = fractionalSec * 1000_000L;
                        this.timestampPrecision = TimestampPrecision.MS;
                    }
                    ZoneOffset zoneOffset = ZoneOffset.of(value.substring(value.length() - 5));
                    Instant instant = Instant.ofEpochSecond(epochSec, nanoAdjustment).atOffset(zoneOffset).toInstant();
                    return Timestamp.from(instant);
                }
            }
`

**Comment by liangbinc** [comment]
In a word , the format of timestamp results returned by the TDengine server after upgrading is inconsistent

**Comment by fenghua1997** [comment]
ok,we will check on this.

**Comment by fenghua1997** [comment]
Have you upgraded the version of taos-jdbcdriver？
Ensure that the version is later than 2.0.36.
![image](https://user-images.githubusercontent.com/70138133/156687248-e747f5b1-a72e-4450-aba0-f0ba0c6af70e.png)

**Comment by liangbinc** [comment]
After  driver version upgrade , the question still remains;You also can check again;

**Comment by fenghua1997** [comment]
Thanks for your feedback. we will arrange to check it.
