### ISSUE TITLE
Process finished with exit code -1073740940 (0xC0000374)

### ISSUE THREAD

**Issue by 123listen** [taosdata/TDengine#1051]
共创建了1万表 ，每张表每次批量插入100条，循环插入到第36次时，程序退出显示信息Process finished with exit code -1073740940 (0xC0000374)，请问该报错信息是什么意思？一般是TDEngine的什么限制导致了，我发现重新安装TDEngine时，数据发送又可继续

**Comment by hjxilinx** [comment]
能否提供更详细的信息，你的程序是什么语言的，TDengine的版本号等信息。

**Comment by 123listen** [comment]
数据写入程序是用java写的，TDEngine的安装版本是TDEngine-1.6.4.4，这是个必现问题

**Comment by sangshuduo** [comment]
@123listen 请试试新版本 2.0.3.1 和 JDBC driver 2.0.4 看还有没有问题

**Comment by sangshuduo** [comment]
@123listen 请试试新版本 2.0.3.1 和 JDBC driver 2.0.4 看还有没有问题

**Comment by yuhuafeng1109** [comment]
这个问题我在2.0.10.0版本中也出现了，只是进行一般的查询操作，数据量几十兆，请问现在有什么解决方案吗

**Comment by sangshuduo** [comment]
@yuhuafeng1109 如果能重现请报一个 issue ，把 debugFlag 改成 135 并请贴 log 到 Github 上。建议先升级到最新版本。
