### ISSUE TITLE
A typo break both Taos shell and Http connector

### ISSUE THREAD

**Issue by squ** [taosdata/TDengine#106]
A typo break both Taos shell and Http connector.  

No response and can't be interrupt.  ("，" should be ",")

![image](https://user-images.githubusercontent.com/2545334/61449819-54829080-a988-11e9-91cd-547ce575174b.png)

**Comment by hzcheng** [comment]
It is a bug in shell, it will be fixed soon

**Comment by guanshengliang** [comment]
This issue has been fixed and submitted
