### ISSUE TITLE
query is slow when using python connector in the windows

### ISSUE THREAD

**Issue by hexuejian** [taosdata/TDengine#1060]
windows上使用python的连接，查询数据很慢，tdengine版本

**Comment by fangpanpan** [comment]
请问您可以具体描述一下查询的情况，比如查询的语句，查询的数据大小，查询的速度（和taos shell 相比的情况）。方便的话可以将服务端和客户端的日志都发给我们吗？
日志： 服务端在/var/log/taos, 客户端在c:\TDengine\log
配置文件：服务端在/etc/taos/taos.cfg, 客户端在c:\TDengine\cfg\taos.cfg
可以先清空日志,， 然后在配置文件里面加上debugflag 135, 然后再重启服务端sudo systemctl restart taosd后开始执行查询操作即可。
