### ISSUE TITLE
A segment fault occurred while Using the taosdump tool of TDengine enterprise edition to export the data.

### ISSUE THREAD

**Issue by zhouyf605** [taosdata/TDengine#10606]
td 企业版 taosdump 导出   segment fault   
centos 7.6
td 企业版  2.2.2.8

Mar  7 23:29:21 h1 kernel: taosdump[2246]: segfault at 99ab ip 00007fe45dd31079 sp 00007fe442443600 error 4 in libc-2.17.so[7fe45dce4000+1c4000]
Mar  7 23:29:22 h1 abrt-hook-ccpp: Process 2224 (taosdump) of user 0 killed by SIGSEGV - dumping core
Mar  7 23:29:25 h1 abrt-server: Executable '/usr/local/taos/bin/taosdump' doesn't belong to any package and ProcessUnpackaged is set to 'no'
Mar  7 23:29:25 h1 abrt-server: 'post-create' on '/var/spool/abrt/ccpp-2022-03-07-23:29:22-2224' exited with 1
Mar  7 23:29:25 h1 abrt-server: Deleting problem directory '/var/spool/abrt/ccpp-2022-03-07-23:29:22-2224'

**Comment by zhouyf605** [comment]
taosdump   -u root -p   -E "2022-02-01T00:00:00.000+0800" -D iot -B 30  -o /tdback

**Comment by fenghua1997** [comment]
稍等，我们给您看看

**Comment by zhouyf605** [comment]
好的  刚才又运行了下   很快就又导出失败了  这个之前我导出过6个月的数据没有报错   这次就报错了  不知道什么原因触发了bug   之前导出没有设置-E  应该是这样的    所以我怀疑是和这个-S   -E  可能有关系

**Comment by fenghua1997** [comment]
taosdump 加额外参数就出问题了吗？
您可以和您的销售或售后团队反映一下，他们会给您调试，判断是哪儿出的问题

**Comment by zhouyf605** [comment]
是企业版 的  暂时已经没有时间调试分析了   时间紧张   自己研究曲线救国吧
