### ISSUE TITLE
How can I upgrade taosd online from 2.2.2.10 to 2.4.0.10

### ISSUE THREAD

**Issue by Bo101010** [taosdata/TDengine#10632]
请问如何从taosd版本从2.2.2.10在线升级到2.4.0.10。集群模式。

**Comment by boxiaobj** [comment]
不支持2.2.x在线升级到2.4.x，需要停服升级。
建议先备份数据，做好测试验证，再实施升级。
如果子表数不是特别多的话(例如，不超过1000万)，升级重启过程在20分钟以内。前提是需要先做好验证。

**Comment by Bo101010** [comment]
Thanks @boxiaobj  ,   实际上我们升级是为了使用“SELECT INTERP”， 按照文档需要版本大于2.3.1。 从2.2.10到2.3.x能在线升级吗？ 如果不能在线升级，有没其他替代方法可以使用到“select interp”?

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
