### ISSUE TITLE
How to configure TDengine memory usage?

### ISSUE THREAD

**Issue by hhstu** [taosdata/TDengine#10655]
我希望通过配置减少 TDengine 的使用内存

**Comment by fenghua1997** [comment]
对于一个 vnode，使用的内存大小为：cache （内存块大小）* blocks（内存块个数）。
你可以试着改这两个参数。

**Comment by hhstu** [comment]
How  to update the cache size  for  existed database ? @fenghua1997

**Comment by fenghua1997** [comment]
> How to update the cache size for existed database ? @fenghua1997

The cache cannot be changed for existed databases, only blocks can be changed：
ALTER DATABASE BLOCKS n

**Comment by hhstu** [comment]
Get, thanks
