### ISSUE TITLE
插入大量数据时报错，不是invalid，请关注。

### ISSUE THREAD

**Issue by runzhiwang** [taosdata/TDengine#107]
07/18 18:21:40.920805 7f9601177700 DND vid:3, committing to file, firstKey:1886976000000 lastKey:2252870340000 ssid:0 esid:1000
07/18 18:21:40.949253 7f9609b17700 ERROR DND vid:3 sid:1 id:0.db.v0, all blocks are not committed yet....
07/18 18:21:41.043271 7f9601177700 DND vid:3, committing is over
07/18 18:21:41.323150 7f9601177700 DND vid:3, committing to file, firstKey:1887840000000 lastKey:2254850340000 ssid:0 esid:1000
07/18 18:21:41.449334 7f9601177700 DND vid:3, committing is over
07/18 18:21:41.721187 7f9601177700 DND vid:3, committing to file, firstKey:1888704000000 lastKey:2256770340000 ssid:0 esid:1000
07/18 18:21:41.749997 7f9609b17700 ERROR DND vid:3 sid:1 id:0.db.v0, all blocks are not committed yet....
07/18 18:21:41.865328 7f9601177700 DND vid:3, committing is over
07/18 18:21:42.122427 7f9601177700 DND vid:3, committing to file, firstKey:1889568000000 lastKey:2258690340000 ssid:0 esid:1000
07/18 18:21:42.244664 7f9601177700 DND vid:3, committing is over
07/18 18:21:42.522530 7f9601177700 DND vid:3, committing to file, firstKey:1890432000000 lastKey:2260550340000 ssid:0 esid:1000
07/18 18:21:42.655350 7f9601177700 DND vid:3, committing is over
07/18 18:21:42.920025 7f9601177700 DND vid:3, committing to file, firstKey:1891296000000 lastKey:2262530340000 ssid:0 esid:1000
07/18 18:21:43.056284 7f9601177700 DND vid:3, committing is over

int main(int argc, char *argv[]) {
   taos_init();
   TAOS *taos = taos_connect("127.0.0.1", "root", "taosdata", NULL, 0);
   if (taos == NULL) {
     printf("failed to connect to server, reason:%s\n", taos_errstr(taos));
     exit(1);
   }

   if (taos_query(taos, "create database db") != 0) {
     printf("failed to create database, reason:%s\n", taos_errstr(taos));
     exit(1);
   }

   taos_query(taos, "use db");

   char sql[65000] = {0};
   srand((unsigned)time(NULL));
   int begin = time(NULL);
   for (int table = 0; table < 1; ++table) {
     sprintf(sql, "create table v%d(ts timestamp, longitude bigint, latitude bigint, altitude int, direction int, velocity int, card int, model binary(10))", table);
     if (taos_query(taos, sql) != 0) {
       printf("failed to create table t%d, reason:%s\n", table, taos_errstr(taos));
       exit(1);
     }

     for (int loop = 0; loop < 50000; loop++) {
        //printf("loop:%d\n", loop);
           int len = sprintf(sql, "insert into v%d values", table);
           for (int row = 0; row < 1000; row++) {
              //printf("row:%d\n", row)
              len += sprintf(sql + len, "(%ld,%d,%d,%d,%d,%d, %d, t%d)", 1561910400000L + 60000L * (row + loop * 1000L), rand()%100000, rand()%100000, rand()%100000, rand() % 100000 , rand() % 100000, rand() % 100000, rand() % 100000);
           }
           if (taos_query(taos, sql) != 0) {
             printf("failed to insert table t%d, reason:%s\n", table, taos_errstr(taos));
           }
     }
   }
   int end = time(NULL);
   printf("insert finished, time spend %d seconds", end - begin);
}

**Comment by hzcheng** [comment]
您好，这个不应该是错误，应该是个警告，原因是由于写入速度太快，硬盘落盘速度太快跟不上写入速度，应该是个WARN

**Comment by runzhiwang** [comment]
@hzcheng  不是  我确实写不进去数据了 程序直接结束了

**Comment by hzcheng** [comment]
抱歉，正在看，谢谢

**Comment by hzcheng** [comment]
@runzhiwang 您好，我重复了您的代码后，确实不是bug，原因是因为我们的数据保留机制。一个数据库在默认情况下保留10年的数据，而您的代码里面，一张表的时间跨度随着写入，远远超过了十年，因此您用count统计的时候，确实数据量没有增加，但是新的数据是写进去了的，老的数据被删除了。

您可以选择将行与行之间的时间戳跨度减小，从而将数据变成都是10年以内的。

如果您非要保留更长时间的数据，您可以在创建数据库的时候加参数：
```
create database db keep 36500;
```
其中的36500是指36500天，也就是大约100年。
