### ISSUE TITLE
Settings update data, but not available

### ISSUE THREAD

**Issue by 704667987** [taosdata/TDengine#10740]
您好：
我看到 常见问题列表中有这段说明：
“此外，从 2.1.7.0 版本开始，支持将 UPDATE 参数设为 2，表示“支持部分列更新”。也即，当 UPDATE 设为 1 时，如果更新一个数据行，其中某些列没有提供取值，那么这些列会被设为 NULL；而当 UPDATE 设为 2 时，如果更新一个数据行，其中某些列没有提供取值，那么这些列会保持原有数据行中的对应值。”

我们使用场景中有用到 UPDATE 设为 2 的这种场景，但我测试了一下没有效果。一直不成功。不知是什么原因。 

![1647245304](https://user-images.githubusercontent.com/33055155/158130504-6c97129c-a6b7-4e62-b2d5-703c1fbfdb7f.png)

**Comment by fenghua1997** [comment]
你好，可以 show databases\G; 查看具体库的参数哦

**Comment by 704667987** [comment]
> 你好，可以显示数据库\G; 查看具体库的参数哦

怎么 查看具体库的参数！？ 客户端用的是 client-2.2.2.10-windows

**Comment by fenghua1997** [comment]
show databases\G 找一下看啊
或者 show create database XXX\G

**Comment by 704667987** [comment]
我换了一个版本2.4.0.0 ，还是一定要填写全部参数下才能更新，只要更新一个参数就提示出错。
![1647398945(1)](https://user-images.githubusercontent.com/33055155/158507543-d2291f92-616b-4b5d-a09c-979f9ad2978e.png)

**Comment by fenghua1997** [comment]
可能是因为 values 前面没指定字段，不确定更新的是哪一个列。
可以指定了再试试

**Comment by 704667987** [comment]
您的话提醒了我， 我加了项插入就可以了。 你们文档可以说明得更清析一下，毕竟你们不是用SQL 的update 语句， 谢谢了！
![1647400500(1)](https://user-images.githubusercontent.com/33055155/158509618-15b92849-9ca1-4936-a6a7-ac32e66a125f.png)

**Comment by fenghua1997** [comment]
客气了，感谢反馈，我们会持续改进文档
