### ISSUE TITLE
restful  driver, insert into  using metrics values.  invalid.

### ISSUE THREAD

**Issue by zhmeng** [taosdata/TDengine#10742]
1. 用 restful driver 连接 tsengine.
2. 写入数据，采用 insert into using metrics values. 这个语法，即没有子表的时候采用超级表创建。
3. 接口返回 Table does not exist. 

采用的是  com:taosdata.jdbc:jdbc:taos-jdbcdriver:2.0.34

**Comment by zhmeng** [comment]
直接通过 taos 终端,相同的语句是可以正常写入的。 是否 restful 接口不支持 insert using 超级表的这种用法？

**Comment by zhmeng** [comment]
insert into sentinel.sub_metrics_testtwo (
            ts,
            app,
            originApp,
            appMachine,
            resource,
            passQps,
            blockQps,
            successQps,
            exceptionQps,
            rt,
            count,
            resourceCode
        ) USING metrics TAGS ('testtwo') values (
            '2022-03-14 16:35:02.0',
            'testtwo',
            'test-two',
            'test-two_1722114544_66090',
            'nodeA',
            2,
            2,
            2,
            0,
            34.0,
            1,
            104993407
        )

**Comment by fenghua1997** [comment]
using 的超级表 metrics 前面加上库名 sentinel 试试

**Comment by zhmeng** [comment]
好的，🙏 可以了
