### ISSUE TITLE
The issue of TDengine upgrade 

### ISSUE THREAD

**Issue by czwer** [taosdata/TDengine#10759]
你好，在使用TDengine时，遇到从ver-2.0.9.0版本升级到ver-2.4.0.7和ver-2.4.0.10后批量保存时速度降低了5~6倍，后取消了升级。能否在官网上发布下哪些是稳定版本，及版本使用推荐（版本引用情况）吗？

**Comment by fenghua1997** [comment]
感谢反馈。请问批量保存指的是批量写入吗？可以把具体语句、表结构发一下呢
目前 2.4 就是 TDengine 的稳定版（相对于 2.3 来讲）
