### ISSUE TITLE
Super table aggregation query bug

### ISSUE THREAD

**Issue by lovegrave** [taosdata/TDengine#10775]
select   max(daily_flow_of_import) importData,  max(daily_flow_of_export) exportData, avg(water_quality) waterData, count(water_quality) item_num, devicecode deviceCode    from d_bwqnw.s_ymofq1zbwkljjrao    where ts between '2022-03-15 00:00:00' and '2022-03-15 23:59:59'  interval(1d)  group by devicecode

上面是原sql，得到的数据
![image](https://user-images.githubusercontent.com/39576272/158558146-edb9ba4c-c33c-4548-9bfc-fb4c15352477.png)

select            max(daily_flow_of_import) importData,            max(daily_flow_of_export) exportData,            avg(water_quality) waterData,            count(water_quality) item_num,             devicecode deviceCode         from d_bwqnw.s_ymofq1zbwkljjrao          where ts between '2022-03-15 00:00:00' and '2022-03-15 23:59:59'  and devicecode = '7mDfUuLso9'  interval(1d)  group by devicecode

这个是单个设备的sql

结果
![image](https://user-images.githubusercontent.com/39576272/158558784-29420f16-f13f-4d5f-b833-bbc4b771df7f.png)

请问：这个属于什么问题呢，我是安装的docker 版本

**Comment by lovegrave** [comment]
补充：直接通过超级表的统计结果，group by devicecode, 得到的设备的统计值，waterdata 这个值，有十几个设备返回的null,其他是正常的

**Comment by fenghua1997** [comment]
此超级表中，就 devicecode 字段是 tag ？可以提供一下表结构吗，我们复现一下

**Comment by lovegrave** [comment]
{ "res": true, "count": 25, "data": [ { "Field": "ts", "Type": "TIMESTAMP", "Length": 8, "Note": "" }, { "Field": "sumppump_failure_1", "Type": "INT", "Length": 4, "Note": "" }, { "Field": "sumppump_output_collecting_well_1", "Type": "INT", "Length": 4, "Note": "" }, { "Field": "sumppump_failure_2", "Type": "INT", "Length": 4, "Note": "" }, { "Field": "sumppump_output_collecting_well_2", "Type": "INT", "Length": 4, "Note": "" }, { "Field": "inlet_instantaneous_flow", "Type": "DOUBLE", "Length": 8, "Note": "" }, { "Field": "outlet_instantaneous_flow", "Type": "DOUBLE", "Length": 8, "Note": "" }, { "Field": "cumulative_import_flow", "Type": "DOUBLE", "Length": 8, "Note": "" }, { "Field": "cumulative_export_flow", "Type": "DOUBLE", "Length": 8, "Note": "" }, { "Field": "daily_flow_of_import", "Type": "DOUBLE", "Length": 8, "Note": "" }, { "Field": "daily_flow_of_export", "Type": "DOUBLE", "Length": 8, "Note": "" }, { "Field": "sump_water_level_alarm", "Type": "INT", "Length": 4, "Note": "" }, { "Field": "cod_channel_1", "Type": "DOUBLE", "Length": 8, "Note": "" }, { "Field": "aerationfan_failure_1", "Type": "INT", "Length": 4, "Note": "" }, { "Field": "aerationfan_run_1", "Type": "INT", "Length": 4, "Note": "" }, { "Field": "lift_fan_failure_1", "Type": "INT", "Length": 4, "Note": "" }, { "Field": "bt_pump_failure", "Type": "INT", "Length": 4, "Note": "" }, { "Field": "rodm", "Type": "INT", "Length": 4, "Note": "" }, { "Field": "pressed_stop", "Type": "INT", "Length": 4, "Note": "" }, { "Field": "dt_low_water_level", "Type": "DOUBLE", "Length": 8, "Note": "" }, { "Field": "sumppump_status_1", "Type": "INT", "Length": 4, "Note": "" }, { "Field": "sumppump_status_2", "Type": "INT", "Length": 4, "Note": "" }, { "Field": "aerationfan_status_1", "Type": "INT", "Length": 4, "Note": "" }, { "Field": "water_quality", "Type": "DOUBLE", "Length": 8, "Note": "" }, { "Field": "devicecode", "Type": "NCHAR", "Length": 64, "Note": "TAG" } ] }

**Comment by lovegrave** [comment]
![image](https://user-images.githubusercontent.com/39576272/158566244-45839435-1028-4246-8548-68314c9046dd.png)
造化弄人，如果你们需要数据，可以联系我

**Comment by fenghua1997** [comment]
> ![image](https://user-images.githubusercontent.com/39576272/158566244-45839435-1028-4246-8548-68314c9046dd.png) 造化弄人，如果你们需要数据，可以联系我

好的，皂滑弄人
