### ISSUE TITLE
how to get head of table by using python

### ISSUE THREAD

**Issue by Qxxxx** [taosdata/TDengine#10794]
Hi Tdengine teams,

- After cursor.fetchall() (python), I only get pure data without head. Is there a way to get the head of the table? And the purpose is to make a pandas dataframe. If there is an elegant way to do that is also grateful.

- Another question is the minimum interval of time is ms? is that possible to change it to second, hour even date?

Thanks a lot.

**Comment by Qxxxx** [comment]
我发现原来大家都用中文，我用中文再打一遍吧。

- cursor.fetchall() (python) 没有表头数据，咋获取表头啊，目的是为了dataframe 如果有更优雅的方法就更好啦
- 现在默认最小时间颗粒度是ms， 有没有可能变成分钟或者每天这种？

**Comment by fenghua1997** [comment]
可以通过 connection.query 方法直接输命令查询的，在下面页面搜索🔍 ：
https://www.taosdata.com/docs/cn/v2.0/connector#python

**Comment by Qxxxx** [comment]
查询命令是啥呢？

**Comment by fenghua1997** [comment]
desc dbname.tbname 这样子

**Comment by fenghua1997** [comment]
时间精度的话，PRECISION 参数控制，目前只支持 毫秒 微秒 和 纳秒的（默认豪秒），若想精度变粗，还是用代码做处理吧

**Comment by Qxxxx** [comment]
好的非常感谢，问题解决了。
