### ISSUE TITLE
使用FILL(PREV)时，使用前一个非NULL值填充，是不是应该用同一个设备（表）的值，而不是用结果集的上一条数据填充

### ISSUE THREAD

**Issue by DarkGodOne** [taosdata/TDengine#10825]
您好，
想确认下fill关键字的插值填充机制，我有一个超级表用于存储多个设备的温度数据，现在我使用interval(1h)统计每个小时的数据，使用fill字段填充前值，有的设备一直没有上报温度数据，理论上应该是NULL，但是实际返回结果中，直接使用了上一条数据进行了填充，这样是否合理呢？？是否应该按照分组，各自组内进行填充呢
select LAST(area),LAST(temphome) from heatingbuild   where  ts >= '
2022-03-17 15:15:32'  and ts <= now  interval(1h,0h) FILL(PREV)    group by buildingid,nodeid,dependence order by buildingid;

**Comment by fenghua1997** [comment]
你使用的是 FILL(PREV)，于是就用前一个非 NULL 值来填充的数据磊。

FILL 语句指定某一窗口区间数据缺失的情况下的填充模式。填充模式包括以下几种：
不进行填充：NONE（默认填充模式）。
VALUE 填充：固定值填充，此时需要指定填充的数值。例如：FILL(VALUE, 1.23)。
PREV 填充：使用前一个非 NULL 值填充数据。例如：FILL(PREV)。
NULL 填充：使用 NULL 填充数据。例如：FILL(NULL)。
LINEAR 填充：根据前后距离最近的非 NULL 值做线性插值填充。例如：FILL(LINEAR)。
NEXT 填充：使用下一个非 NULL 值填充数据。例如：FILL(NEXT)。

具体细节可在官网文档搜索哦

**Comment by DarkGodOne** [comment]
我的意思是，当使用FILL(PREV)时，使用前一个非NULL值填充，是不是应该是同一个设备（表）的值，现在的情况是，B设备使用了A设备的数据进行填充，这样是不对的
还是说咱们设计的插值填充，都是以结果集为准，使用前一条数据进行填充么？

**Comment by enix223** [comment]
+1 #22472
