### ISSUE TITLE
Dnodes are disconnected because the query data is too large.

### ISSUE THREAD

**Issue by yangweng** [taosdata/TDengine#10842]
运行配置:
3/19 11:24:38.871914 00005950 UTL  firstEp:                192.168.0.1:6030 
03/19 11:24:38.871918 00005950 UTL  secondEp:              192.168.0.2:6030 
03/19 11:24:38.871922 00005950 UTL  fqdn:                   192.168.0.3
03/19 11:24:38.871926 00005950 UTL  serverPort:             6030 
03/19 11:24:38.871930 00005950 UTL  configDir:              /etc/taos 
03/19 11:24:38.871933 00005950 UTL  logDir:                 /data/taos/log 
03/19 11:24:38.871937 00005950 UTL  scriptDir:              /etc/taos 
03/19 11:24:38.871940 00005950 UTL  arbitrator:              
03/19 11:24:38.871944 00005950 UTL  numOfThreadsPerCore:    1.000000 
03/19 11:24:38.871950 00005950 UTL  numOfCommitThreads:     4 
03/19 11:24:38.871954 00005950 UTL  ratioOfQueryCores:      1.000000 
03/19 11:24:38.871958 00005950 UTL  maxNumOfDistinctRes:    10000000 
03/19 11:24:38.871962 00005950 UTL  numOfMnodes:            1 
03/19 11:24:38.871965 00005950 UTL  vnodeBak:               1 
03/19 11:24:38.871969 00005950 UTL  telemetryReporting:     1 
03/19 11:24:38.871972 00005950 UTL  dnodeNopLoop:           0 
03/19 11:24:38.871976 00005950 UTL  balance:                1 
03/19 11:24:38.871980 00005950 UTL  balanceInterval:        300 
03/19 11:24:38.871983 00005950 UTL  offlineInterval:        3 
03/19 11:24:38.871987 00005950 UTL  role:                   0 
03/19 11:24:38.871991 00005950 UTL  maxTmrCtrl:             512 
03/19 11:24:38.871994 00005950 UTL  monitorInterval:        30(s)
03/19 11:24:38.871998 00005950 UTL  monitorReplica:         1 
03/19 11:24:38.872002 00005950 UTL  offlineThreshold:       864000(s)
03/19 11:24:38.872005 00005950 UTL  rpcTimer:               300(ms)
03/19 11:24:38.872009 00005950 UTL  rpcMaxTime:             600(s)
03/19 11:24:38.872012 00005950 UTL  rpcForceTcp:            0 
03/19 11:24:38.872016 00005950 UTL  statusInterval:         1(s)
03/19 11:24:38.872020 00005950 UTL  shellActivityTimer:     3(s)
03/19 11:24:38.872023 00005950 UTL  minSlidingTime:         10(ms)
03/19 11:24:38.872027 00005950 UTL  minIntervalTime:        1(ms)
03/19 11:24:38.872030 00005950 UTL  maxStreamCompDelay:     20000(ms)
03/19 11:24:38.872034 00005950 UTL  maxFirstStreamCompDelay:10000(ms)
03/19 11:24:38.872040 00005950 UTL  retryStreamCompDelay:   10000(ms)
03/19 11:24:38.872044 00005950 UTL  streamCompDelayRatio:   0.100000 
03/19 11:24:38.872049 00005950 UTL  maxVgroupsPerDb:        32 
03/19 11:24:38.872052 00005950 UTL  maxTablesPerVnode:      9000000 
03/19 11:24:38.872056 00005950 UTL  minTablesPerVnode:      1000 
03/19 11:24:38.872059 00005950 UTL  tableIncStepPerVnode:   1000 
03/19 11:24:38.872063 00005950 UTL  cache:                  16(Mb)
03/19 11:24:38.872067 00005950 UTL  blocks:                 6 
03/19 11:24:38.872070 00005950 UTL  days:                   10 
03/19 11:24:38.872074 00005950 UTL  keep:                   3650 
03/19 11:24:38.872077 00005950 UTL  minRows:                100 
03/19 11:24:38.872081 00005950 UTL  maxRows:                4096 
03/19 11:24:38.872084 00005950 UTL  precision:              0 
03/19 11:24:38.872090 00005950 UTL  comp:                   2 
03/19 11:24:38.872094 00005950 UTL  walLevel:               1 
03/19 11:24:38.872097 00005950 UTL  fsync:                  3000 
03/19 11:24:38.872101 00005950 UTL  replica:                1 
03/19 11:24:38.872104 00005950 UTL  partitions:             4 
03/19 11:24:38.872108 00005950 UTL  quorum:                 1 
03/19 11:24:38.872111 00005950 UTL  update:                 0 
03/19 11:24:38.872115 00005950 UTL  cachelast:              0 
03/19 11:24:38.872118 00005950 UTL  compressMsgSize:        524288 
03/19 11:24:38.872122 00005950 UTL  compressColData:        -1 
03/19 11:24:38.872126 00005950 UTL  maxSQLLength:           1048576(byte)
03/19 11:24:38.872129 00005950 UTL  maxWildCardsLength:     100(byte)
03/19 11:24:38.872133 00005950 UTL  maxRegexStringLen:      128(byte)
03/19 11:24:38.872136 00005950 UTL  maxNumOfOrderedRes:     100000 
03/19 11:24:38.872140 00005950 UTL  queryBufferSize:        -1(byte)
03/19 11:24:38.872144 00005950 UTL  retrieveBlockingModel:  0 
03/19 11:24:38.872147 00005950 UTL  keepColumnName:         0 
03/19 11:24:38.872151 00005950 UTL  timezone:               (IST, +0500) 
03/19 11:24:38.872154 00005950 UTL  locale:                 en_US.UTF-8 
03/19 11:24:38.872158 00005950 UTL  charset:                UTF-8 
03/19 11:24:38.872161 00005950 UTL  maxShellConns:          50000 
03/19 11:24:38.872165 00005950 UTL  maxConnections:         5000 
03/19 11:24:38.872168 00005950 UTL  minimalLogDirGB:        1.000000(GB)
03/19 11:24:38.872172 00005950 UTL  minimalTmpDirGB:        1.000000(GB)
03/19 11:24:38.872176 00005950 UTL  minimalDataDirGB:       2.000000(GB)
03/19 11:24:38.872179 00005950 UTL  mnodeEqualVnodeNum:     4 
03/19 11:24:38.872183 00005950 UTL  flowctrl:               1 
03/19 11:24:38.872186 00005950 UTL  slaveQuery:             1 
03/19 11:24:38.872190 00005950 UTL  adjustMaster:           1 
03/19 11:24:38.872194 00005950 UTL  http:                   1 
03/19 11:24:38.872197 00005950 UTL  mqtt:                   0 
03/19 11:24:38.872201 00005950 UTL  monitor:                1 
03/19 11:24:38.872204 00005950 UTL  stream:                 1 
03/19 11:24:38.872208 00005950 UTL  topicBinaryLen:         16000 
03/19 11:24:38.872211 00005950 UTL  httpEnableRecordSql:    0 
03/19 11:24:38.872215 00005950 UTL  telegrafUseFieldNum:    0 
03/19 11:24:38.872218 00005950 UTL  httpMaxThreads:         4 
03/19 11:24:38.872222 00005950 UTL  restfulRowLimit:        10240 
03/19 11:24:38.872225 00005950 UTL  httpDbNameMandatory:    0 
03/19 11:24:38.872229 00005950 UTL  httpKeepAlive:          30000 
03/19 11:24:38.872232 00005950 UTL  numOfLogLines:          10000000 
03/19 11:24:38.872236 00005950 UTL  logKeepDays:            0 
03/19 11:24:38.872239 00005950 UTL  asyncLog:               1 
03/19 11:24:38.872243 00005950 UTL  debugFlag:              0 
03/19 11:24:38.872246 00005950 UTL  mDebugFlag:             131 
03/19 11:24:38.872250 00005950 UTL  dDebugFlag:             135 
03/19 11:24:38.872253 00005950 UTL  sDebugFlag:             135 
03/19 11:24:38.872257 00005950 UTL  wDebugFlag:             135 
03/19 11:24:38.872261 00005950 UTL  sdbDebugFlag:           131 
03/19 11:24:38.872266 00005950 UTL  rpcDebugFlag:           131 
03/19 11:24:38.872269 00005950 UTL  tmrDebugFlag:           131 
03/19 11:24:38.872273 00005950 UTL  cDebugFlag:             131 
03/19 11:24:38.872276 00005950 UTL  jniDebugFlag:           131 
03/19 11:24:38.872280 00005950 UTL  odbcDebugFlag:          131 
03/19 11:24:38.872284 00005950 UTL  uDebugFlag:             131 
03/19 11:24:38.872287 00005950 UTL  httpDebugFlag:          131 
03/19 11:24:38.872291 00005950 UTL  mqttDebugFlag:          131 
03/19 11:24:38.872294 00005950 UTL  monDebugFlag:           131 
03/19 11:24:38.872298 00005950 UTL  qDebugFlag:             131 
03/19 11:24:38.872301 00005950 UTL  vDebugFlag:             135 
03/19 11:24:38.872305 00005950 UTL  tsdbDebugFlag:          131 
03/19 11:24:38.872308 00005950 UTL  cqDebugFlag:            131 
03/19 11:24:38.872312 00005950 UTL  enableRecordSql:        0 
03/19 11:24:38.872317 00005950 UTL  enableCoreFile:         0 
03/19 11:24:38.872320 00005950 UTL  gitinfo:                41243cbb2a43e76787b31977d278c4f4ffbcd4a4 
03/19 11:24:38.872324 00005950 UTL  gitinfoOfInternal:      NULL 
03/19 11:24:38.872328 00005950 UTL  buildinfo:              Built at 2022-03-11 17:12 
03/19 11:24:38.872331 00005950 UTL  version:                2.4.0.12 
03/19 11:24:38.872335 00005950 UTL  maxBinaryDisplayWidth:  30 
03/19 11:24:38.872338 00005950 UTL  tempDir:                /tmp/ 
03/19 11:24:38.872342 00005950 UTL  tsdbMetaCompactRatio:   0 
03/19 11:24:38.872345 00005950 UTL  deadLockKillQuery:      1 
03/19 11:24:38.872349 00005950 UTL  clientMerge:            0 
03/19 11:24:38.872352 00005950 UTL  defaultJSONStrType:     nchar 
03/19 11:24:38.872356 00005950 UTL  smlChildTableName:       
03/19 11:24:38.872360 00005950 UTL  smlTagNullName:         _tag_null 
03/19 11:24:38.872363 00005950 UTL  walFlushSize:           1024(Mb)
03/19 11:24:38.872367 00005950 UTL  lossyColumns:            
03/19 11:24:38.872370 00005950 UTL  fPrecision:             0.000000 
03/19 11:24:38.872374 00005950 UTL  dPrecision:             0.000000 
03/19 11:24:38.872378 00005950 UTL  maxRange:               500 
03/19 11:24:38.872382 00005950 UTL  range:                  100 
03/19 11:24:38.872386 00005950 UTL  os pageSize:            4096(KB)
03/19 11:24:38.872390 00005950 UTL  os openMax:             1048576
03/19 11:24:38.872393 00005950 UTL  os streamMax:           16
03/19 11:24:38.872397 00005950 UTL  os numOfCores:          8
03/19 11:24:38.872400 00005950 UTL  os totalMemory:         31702(MB)
03/19 11:24:38.872406 00005950 UTL  os sysname:             Linux
03/19 11:24:38.872409 00005950 UTL  os nodename:            192.168.0.1
03/19 11:24:38.872413 00005950 UTL  os release:             4.14.268-205.500.amzn2.x86_64
03/19 11:24:38.872416 00005950 UTL  os version:             #1 SMP Wed Mar 2 18:38:38 UTC 2022
03/19 11:24:38.872420 00005950 UTL  os machine:             x86_64
03/19 11:24:38.872423 00005950 UTL  dataDir: /data/taos/lib
03/19 11:24:38.872427 00005950 UTL ==================================
03/19 11:24:38.872431 00005950 DND step:dnode-globalcfg is initialized
03/19 11:24:38.872458 00005950 TFS disk /data/taos/lib is mounted to tier level 0 id 0
03/19 11:24:38.872991 00005950 UTL ==================================
03/19 11:24:38.872997 00005950 UTL  os totalDisk:           999.511719(GB)
03/19 11:24:38.873002 00005950 UTL  os usedDisk:            56.168186(GB)
03/19 11:24:38.873006 00005950 UTL  os availDisk:           943.343506(GB)
03/19 11:24:38.873010 00005950 UTL ==================================

查询语句:
select count(*) form user_login_log where ts > now-1d;

taos 提示：
connect failed, reason: Unable to establish connection.

taosd version: 2.4.0.12
我改了这2个参数引起的。
 maxVgroupsPerDb:        32 
maxTablesPerVnode:      9000000
子表超多。引起这个问题

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
