### ISSUE TITLE
 The new version taos_affected_rows return value is abnormal

### ISSUE THREAD

**Issue by maikebing** [taosdata/TDengine#10881]
执行一条sql语句， 例如

`INSERT INTO d1001 USING METERS TAGS("Beijng.Chaoyang", 2) VALUES(now, 10.2, 219, 0.32);`

 taos_affected_rows返回 100688522  
这个值难道不应该是返回影响行数吗？

**Comment by fenghua1997** [comment]
感谢反馈，新版本具体指的哪个版本？

**Comment by fenghua1997** [comment]
能详细说一下复现的方式吗
taos_affected_rows 我们测着结果返回是 1

**Comment by maikebing** [comment]
客户端是 TDengine-client-2.4.0.12-Linux-x64.tar.gz
服务端是 tdengine/tdengine:2.4.0.12
使用的是   c# 

用的是  
```
     [DllImport("taos", EntryPoint = "taos_affected_rows", CallingConvention = CallingConvention.Cdecl)]
        static extern public int AffectRows(IntPtr res);
```
执行任意sql均返回奇怪的值。

**Comment by xleili** [comment]
这个问题还存吗？
我尝试在2.4.0.12复现。我的affected rows 是正常的。
![image](https://user-images.githubusercontent.com/85657333/159649863-646f8171-44bd-4812-a1e8-d38b866ecb5b.png)

**Comment by maikebing** [comment]
2.4.0.12  存在。 linux 64位 

https://github.com/IoTSharp/EntityFrameworkCore.Taos/blob/master/src/Example/

**Comment by maikebing** [comment]
是我的问题， 感谢提醒。
