### ISSUE TITLE
INTERVAL

### ISSUE THREAD

**Issue by 759085503** [taosdata/TDengine#10899]
![image](https://user-images.githubusercontent.com/26373061/159429019-34c790bc-69ea-4626-9f54-f8a88e09be7f.png)
为什么查询时间会是我没有的时间。

**Comment by 759085503** [comment]
请问是我的写法有问题吗

**Comment by 759085503** [comment]
版本是2.4.0.0，  服务端是liunx ，客户端是window

**Comment by fenghua1997** [comment]
因为你做了 interval 进行降采样，时间按照你给的23分钟进行了聚合

**Comment by 759085503** [comment]
那也不超出我的查询时间范围吧，这样是对的？

**Comment by 759085503** [comment]
![image](https://user-images.githubusercontent.com/26373061/159438582-d071e564-3f45-4334-a3e0-6cad0d99754d.png)
那使用TDengineGUI这个工具查询为什么又是对的呢

**Comment by fenghua1997** [comment]
在 GUI 上执行语句 的 interval 值变了吧，是46m吗？

**Comment by 759085503** [comment]
好吧，我在完整测试一遍可以了吗    /尴尬

**Comment by 759085503** [comment]
![image](https://user-images.githubusercontent.com/26373061/159441219-5e8a395c-67e2-4e8a-8ecc-e3b8b07860be.png)

select last(tagvalue) as tagvalue from sisdatatest.hisdatatest where tagname ='DCS2_2OPC_SPD_MEDN1_R00001' and ts BETWEEN '2020-01-01 00:00:00' AND '2020-02-02 00:00:00' INTERVAL(23m)

**Comment by 759085503** [comment]
![image](https://user-images.githubusercontent.com/26373061/159441495-c7dd494b-c123-4d48-b9df-92c5ce1638c2.png)
select first(tagvalue) as tagvalue from sisdatatest.hisdatatest where tagname ='DCS2_2OPC_SPD_MEDN1_R00001' and ts BETWEEN '2020-01-01 00:00:00' AND '2020-02-02 00:00:00' INTERVAL(23m)

**Comment by 759085503** [comment]
时间不一样值也不会一样，一个是last 一个是first

**Comment by 759085503** [comment]
你看错了，都是23m

**Comment by 759085503** [comment]
好像有一点规律，比如1-10是可以的11，13，不行。比如12就可以。  除以60的可以除断的都可以。不过40是可以的41-45就不行了。   我觉得你们处理这一块的算法写的有问题。
