### ISSUE TITLE
TDengine client connection high available ( JDBC-RESTful )

### ISSUE THREAD

**Issue by matchmen** [taosdata/TDengine#10900]
java程序中，JDBC-RESTful如何实现高可用。

**Comment by matchmen** [comment]
JDBC-RESTful 高可用只能自己实现吗？

**Comment by fenghua1997** [comment]
restful 也可以在连接串url或者Properties上指定配置文件路径的，具体格式可以见文档：
https://www.taosdata.com/docs/cn/v2.0/connector/java#
客户端连接的高可用也可以参考：
https://www.taosdata.com/blog/2021/04/16/2287.html

**Comment by matchmen** [comment]
连接串是逗号分割，类似于jdbc:TAOS-RS://xxxxx:6041/databasename,jdbc:TAOS-RS://xxxxxxx:6041/databasename对吧

**Comment by matchmen** [comment]
https://www.taosdata.com/docs/cn/v2.0/connector/java# 里面没找到连接串url样例

**Comment by matchmen** [comment]
可以给一个【restful 也可以在连接串url上指定配置文件路径】例子吗？实在找不到对应的配置

**Comment by matchmen** [comment]
尝试了类似 JDBC-JNI 的配置    jdbc:TAOS://:/test?user=root&password=taosdata&cfgdir=taos   不行

**Comment by jandison** [comment]
> 
有相关案例吗？

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
