### ISSUE TITLE
Query interrupted (failed to connect to server)

### ISSUE THREAD

**Issue by weilisikaili** [taosdata/TDengine#1090]
我在taos中创建表,包含字段humidity(float)
插入70万条数据,字段humidity存入的数据一共是12位,小数点前7位小数点后5五位
taos终端执行select max(temperature) from tb;
始终报错无法链接服务,查询中断

**Comment by hjxilinx** [comment]
您的可以尝试pull最新的版本，自己编译试一下。 @weilisikaili

**Comment by weilisikaili** [comment]
taos是最新版本的,我将字段类型修改为double之后,taos是不支持针对float的某些查询吗,找了一下原因有的是说精度丢失的原因不知道是不是.

**Comment by plum-lihui** [comment]
是之前的版本有一个bug，最新的版本我们已经解决了。对于float、double应该都没有问题了。请再试试。
