### ISSUE TITLE
TDengine client reported an error

### ISSUE THREAD

**Issue by GoodEnoughMan** [taosdata/TDengine#10909]
TDengine 客户端连接报错
报错为：  unable to establish  connection

**Comment by fenghua1997** [comment]
可以先通过官网文档的内容进行排查：
 https://www.taosdata.com/docs/cn/v2.0/faq
若还是不行，加我 wechat ：Deja_vu_4u

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
