### ISSUE TITLE
Taosdump error: SQL syntax error

### ISSUE THREAD

**Issue by peterchenhdu** [taosdata/TDengine#10929]
**Bug Description**
taosdump备份的SQL语法错误，无法恢复

**To Reproduce**
1. 使用命令执行备份`taosdump -c /etc/taos -o /data/bak/1648004176408 cp_db_test20211214_004 cp_tb_test_001 -t 500 -B 160 -T 32`
2. 使用命令执行恢复`taosdump -c /etc/taos -i /data/bak/1648004176408 -T 10`
3. 报错如下
![image](https://user-images.githubusercontent.com/12928352/159633643-5d26323a-4e15-4b17-9a68-b1276444b251.png)
start to dispose 9 files in /data/bak/1648004176408
Success Open input file: /data/bak/1648004176408/dbs.sql
, Success Open input file: /data/bak/1648004176408/cp_db_test20211214_004.0.sql
ERROR: Failed to run <CREATE TABLE IF NOT EXISTS cp_db_test20211214_004.cp_tb_test_001_1 USING cp_db_test20211214_004.cp_tb_test_001 TAGS (''1'', ''1'');>, reason: syntax error near "1'', ''1'');"
ERROR: dumpInOneFile() LN2817, error sql: lineno:1, file:/data/bak/1648004176408/cp_db_test20211214_004.0.sql
, Success Open input file: /data/bak/1648004176408/cp_db_test20211214_004.1.sql
![image](https://user-images.githubusercontent.com/12928352/159633749-00c7447e-78cc-426e-98eb-0ab57705460c.png)

![image](https://user-images.githubusercontent.com/12928352/159633749-00c7447e-78cc-426e-98eb-0ab57705460c.png)

**Environment**
 - OS: CentOS 7.6
 - TDengine Version 2.2.2.0

简单说，如果TAG是NCHAR类型，备份下来的子表建表语句
CREATE TABLE IF NOT EXISTS cp_db_test20211214_004.cp_tb_test_001_hello_world USING cp_db_test20211214_004.cp_tb_test_001 TAGS (' 'hello_world' ', ‘ '11' ’);
TAG值被”单引号空格单引号“包围。。。。。。。

**Comment by sangshuduo** [comment]
2.2 版本的 taosdump 已不再维护，请升级至 2.4 最新版本和 taosTools （包含 taosdump）最新版本。
