### ISSUE TITLE
I cannot use windows client connect to the server

### ISSUE THREAD

**Issue by liu-xinhui** [taosdata/TDengine#10961]
Server deploy in `centos 7.6` use `Docker`, I can use taos client in `docker exec -it tdengine bash`
But I cannot connect to the server with `windows x64 client`.

client version：`version: 2.4.0.12`
server version: `2.4.0.12`

![image](https://user-images.githubusercontent.com/7698511/159846635-c918eb62-11a4-4613-b808-e8ce10249ef1.png)
![image](https://user-images.githubusercontent.com/7698511/159846647-5a6868d7-4907-438c-87cc-1bde586762f5.png)
![image](https://user-images.githubusercontent.com/7698511/159846658-f14d9d43-5aed-4974-b0a9-2c11bcf0b8bc.png)

**Comment by yu285** [comment]
take care of  UDP sometimes not stable ,use rcpforceTCP   1 in taos.cfg
sometimes network issue hard to locate ，please feel free to add our Wechat ：15652223354 for more investigation.
