### ISSUE TITLE
There is a performance doubt about taos_subscribe、taos_consume 、taos_fetch_row？

### ISSUE THREAD

**Issue by thicktao** [taosdata/TDengine#10964]
**Performance Issue** 
There is a performance doubt about taos_subscribe、taos_consume 、taos_fetch_row：
**Problem Description** 
1、TDengine.Subscribe(_connection,  0, “topic.historyrecord.test2”, “SELECT * FROM historyrecordsecond  WHERE CreateTime>'2022-03-24 13:34:00.000000'   ”, IntPtr.Zero, IntPtr.Zero, 1000); 
every invoke calls 4000+ms;
![image](https://user-images.githubusercontent.com/40555417/159849936-70feae49-cdfe-4c2e-927a-47ef9a162965.png)
2、 TDengine.FetchRows(taos) every calls 4000+ms， Whether there is data or not;
3、TDengine.Consume calls 4000+ms ,the second time start every calls 4000ms+;

code like below:
```
         //订阅
         public void Subcribe<T>(string sql, string topic, Action<List<T>> callBack, int interaval = 1000,
            bool restart = false,
            bool keepProgress = true)
        where T : new()
          {
              var sub = TDengine.Subscribe(_connection, restart ? 1 : 0, topic, sql, IntPtr.Zero, IntPtr.Zero, interaval);
                  if (sub == IntPtr.Zero)
                  {
                      LogHelper.Error($"Subscribe返回地址为空！订阅{topic} Sql:{sql} 失败!");
                      return;
                  }
                  LogHelper.Info($"订阅{topic} Sql:{sql} 成功!");
                  Task.Run(() =>
                  {
                      try
                      {
                          while (true)
                          {
                              var result = TDengine.Consume(sub);
                              var list = TaosResultUtils.GetListResult<T>(sql, result);
                              callBack(list);
                              // 等待1秒，避免频繁调用 consume，给服务端造成压力
                              Thread.Sleep(10);
                          }
                      }
                      catch (Exception ex)
                      {
                          LogHelper.Error($"订阅{topic} Sql:{sql} 失败：", ex);
                      }
                      finally
                      {
                          TDengine.Unsubscribe(sub, keepProgress ? 1 : 0);
                          LogHelper.Info($"完成取消订阅{topic} Sql:{sql}!");
                      }
                  });
           }


   /// <summary>
        /// 获取结果列表
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="sql"></param>
        /// <param name="addr"></param>
        /// <returns></returns>
        public static List<T> GetListResult<T>(string sql, IntPtr addr)
       where T : new()
        {
            var code = TDengine.ErrorNo(addr);
            if (code != 0)
            {
                TaosException.ThrowExceptionForRc(sql, new TaosErrorResult() { Code = code, Error = TDengine.Error(addr) });
            }
            var metas = TDengine.FetchFields(addr);
            Dictionary<string, int> metaMaps = new Dictionary<string, int>();
            for (int i = 0; i < metas.Count; i++)
            {
                metaMaps.Add(metas[i].name.ToLower(), i);
            }
            List<T> list = new List<T>();
            var propertyInfos = TdUtils.GetPropertyInfos(typeof(T)).Where(prop => metaMaps.ContainsKey(prop.Name.ToLower())).ToList();
            IntPtr rowdata;
            while ((rowdata = TDengine.FetchRows(addr)) != IntPtr.Zero)
            {
                var obj = new T();
                foreach (var prop in propertyInfos)
                {
                    var order = metaMaps[prop.Name.ToLower()];
                    var value = GetValue(metas, rowdata, order);
                    if (!Equals(value, DBNull.Value))
                    {
                        prop.SetValue(obj, value, null);
                    }
                }
                list.Add(obj);
            }
            //TDengine.FreeResult(addr);
            return list;
        }

      //TDengine.cs:

        [DllImport("taos", EntryPoint = "taos_subscribe", CallingConvention = CallingConvention.Cdecl)]
        public static extern TAOS_SUB Subscribe(TAOS taos, int restart, string topic, string sql, IntPtr fp,
            IntPtr param, int interaval);
        /// <summary>
        /// 同步调用
        /// </summary>
        /// <param name="tsub"></param>
        /// <returns></returns>
        [DllImport("taos", EntryPoint = "taos_consume", CallingConvention = CallingConvention.Cdecl)]
        public static extern TAOS_RES Consume(TAOS_SUB tsub);
        /// <summary>
        /// 取消订阅
        /// </summary>
        /// <param name="tsub"></param>
        /// <param name="keepProgress">参数 keepProgress 不为0，API会保留订阅的进度信息</param>
        [DllImport("taos", EntryPoint = "taos_unsubscribe", CallingConvention = CallingConvention.Cdecl)]
        public static extern void Unsubscribe(TAOS_SUB tsub, int keepProgress);


```

Environment (please complete the following information):
OS: CentOS Linux release 7.9.2009 (Core)
Memory, CPU, current Disk Space
TDengine Version 2.4.0.12
dotnetcore 3.1 console program windows client

**Comment by xleili** [comment]
Do you mean the bellow Interfaces has latency, they didn't response as fast as you wish?
1：TDengine.Subscribe() 
2：TDengine.FetchRows(taos)
3：TDengine.Consume()

how about using normal APIs like taos_query(), will that response in a very short time?

**Comment by thicktao** [comment]
@xleili yes，taos_query() reponsed in avery short time !

**Comment by xleili** [comment]
`  [DllImport("taos", EntryPoint = "taos_subscribe", CallingConvention = CallingConvention.Cdecl)]
        public static extern TAOS_SUB Subscribe(TAOS taos, int restart, string topic, string sql, IntPtr fp,
            IntPtr param, int interaval);
        /// <summary>
        /// 同步调用
        /// </summary>
        /// <param name="tsub"></param>
        /// <returns></returns>
        [DllImport("taos", EntryPoint = "taos_consume", CallingConvention = CallingConvention.Cdecl)]
        public static extern TAOS_RES Consume(TAOS_SUB tsub);
        /// <summary>
        /// 取消订阅
        /// </summary>
        /// <param name="tsub"></param>
        /// <param name="keepProgress">参数 keepProgress 不为0，API会保留订阅的进度信息</param>
        [DllImport("taos", EntryPoint = "taos_unsubscribe", CallingConvention = CallingConvention.Cdecl)]
        public static extern void Unsubscribe(TAOS_SUB tsub, int keepProgress);`

Among these code, TAOS_RES and TAOS_SUB is defined by yourself. Actually they should be a pointer (IntPtr).

**Comment by xleili** [comment]
If you want to write introp method yourself you can refer:
https://github.com/taosdata/TDengine/blob/develop/src/connector/C%23/src/TDengineDriver/TDengineDriver.cs

**Comment by thicktao** [comment]
@xleili   
TAOS_RES and TAOS_SUB is defined as pointer，it reference the tdenginedriver.cs:
    using TAOS = System.IntPtr;
    using TAOS_RES = System.IntPtr;
    using TAOS_SUB = System.IntPtr;

        [DllImport("taos", EntryPoint = "taos_subscribe", CallingConvention = CallingConvention.Cdecl)]
        public static extern TAOS_SUB Subscribe(TAOS taos, int restart, string topic, string sql, IntPtr fp,
            IntPtr param, int interaval);
        /// <summary>
        /// 同步调用
        /// </summary>
        /// <param name="tsub"></param>
        /// <returns></returns>
        [DllImport("taos", EntryPoint = "taos_consume", CallingConvention = CallingConvention.Cdecl)]
        public static extern TAOS_RES Consume(TAOS_SUB tsub);
        /// <summary>
        /// 取消订阅
        /// </summary>
        /// <param name="tsub"></param>
        /// <param name="keepProgress">参数 keepProgress 不为0，API会保留订阅的进度信息</param>
        [DllImport("taos", EntryPoint = "taos_unsubscribe", CallingConvention = CallingConvention.Cdecl)]
        public static extern void Unsubscribe(TAOS_SUB tsub, int keepProgress);

**Comment by xleili** [comment]
Is this problem still exists in synchronous context? since in my experience they response much faster than you experienced.

**Comment by thicktao** [comment]
yes, it always exists,Especially taos_fetch_row, it has a great influence on me

**Comment by xleili** [comment]
你是说，fetch_row() 返回慢。还是解析fetch_row 返回的内存块慢？

**Comment by xleili** [comment]
或者远程看看

**Comment by thicktao** [comment]
1、     TDengine.FetchRows 调用的是下面taos_fetch_row
   [DllImport("taos", EntryPoint = "taos_fetch_row", CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr FetchRows(IntPtr res);

2、总共结果集200行，list添加200行后，进行下一次while进行判断时获取TDengine.FetchRows(addr)==IntPtr.Zero时，耗时非常高，总耗时1900ms，其中1800ms+的耗时在这次空地址时判断。
        while ((rowdata = TDengine.FetchRows(addr)) != IntPtr.Zero)
            {
                var obj = new T();
                foreach (var prop in propertyInfos)
                {
                    var order = metaMaps[prop.Name.ToLower()];
                    var value = GetValue(metas, rowdata, order);
                    if (!Equals(value, DBNull.Value))
                    {
                        prop.SetValue(obj, value, null);
                    }
                }
                list.Add(obj);
                //count++;
                //if (count == 200)
                //{

                //}
            }
3、如果需要远程，我这边需要提供什么？
@xleili

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
