### ISSUE TITLE
The query result of time filtering condition is abnormal when using interval query

### ISSUE THREAD

**Issue by DarkGodOne** [taosdata/TDengine#10970]
异常结果如图，我时间限定只查询23号的数据，但是使用不同的interval会出现22号的数据
![image](https://user-images.githubusercontent.com/12151282/159869714-5dd29a78-dcc9-44e9-91e1-14c68a49f2da.png)

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
