### ISSUE TITLE
Compilation issues with ARMv7 devices

### ISSUE THREAD

**Issue by kami0314** [taosdata/TDengine#10989]
ubuntu18.04，armv7设备编译是否可以支持？就是命令 `cmake .. -DCPUTYPE=aarch32 && cmake --build `吗？.
是否有什么依赖的最低版本要求吗？

**Comment by sangshuduo** [comment]
cmake 3.0 以上，gcc 4.8.5 以上，Ubuntu1804 都可以满足

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
