### ISSUE TITLE
jdbc query and result error

### ISSUE THREAD

**Issue by lhd951220** [taosdata/TDengine#1099]
**Bug Description**
使用JDBC查询TDengine数据库，当查询数值和时间时，数值和时间都会左移16位。

**To Reproduce**
1. 使用mybatis查询TDengine数据库，sql =》 select * from people

**Screenshots**
这是直接在内置客户端查询的结果
![image](https://user-images.githubusercontent.com/41251046/71960584-5ab74280-3230-11ea-8921-ac9cb08bb853.png)

这是通过mybatis查询的结果
![image](https://user-images.githubusercontent.com/41251046/71960760-c26d8d80-3230-11ea-880d-cc0798f1760c.png)

**Environment (please complete the following information):**
 - OS: CentOS 7.0
 - TDengine Version 1.6.4.0

**Comment by xieyinglin** [comment]
请问 mybatis 查询 time，amount 之后分别对应的映射类型是？

**Comment by lhd951220** [comment]
> 请问 mybatis 查询 time，amount 之后分别对应的映射类型是？

time 对应  Date
amount  对应  Integer

数据库里面， amount是int类型的
![image](https://user-images.githubusercontent.com/41251046/71973467-002ae000-324a-11ea-858c-a2f2eb2503d8.png)

**Comment by xieyinglin** [comment]
tdengine 的主键为时间戳，请使用 java.sql.Timestamp ，我这边测试没问题
![image](https://user-images.githubusercontent.com/41858839/71974733-328a0c80-324d-11ea-81ec-cbbae52d4227.png)

taos shell 中查询
![image](https://user-images.githubusercontent.com/41858839/71974755-4170bf00-324d-11ea-9272-c5eda833cd0d.png)

对应的 javabean
![image](https://user-images.githubusercontent.com/41858839/71974792-53eaf880-324d-11ea-9a02-3434927595d2.png)

**Comment by lhd951220** [comment]
@xieyinglin 我改成跟您说的一样，但是我查询出来的结果还是错误的。而且我还有聚合函数查询，查询出来的结果也是错误的，数值在原始数据上也是左移16位。

**Comment by xieyinglin** [comment]
你的程序是跑在 windows 上么，如果是先是用windows cmd client 查询下结果对不对

**Comment by lhd951220** [comment]
@xieyinglin 是的，跑在window上，但是我使用window client会直接闪退，没有找到闪退的解决方法。然后我重新开启一个新的项目去测试，发现结果还是一样

**Comment by xieyinglin** [comment]
可以先升级到最新版本再测试下，如果还发生闪退，可以先在 C:\TDengine\cfg\taos.cfg 中开启 debugFlag 135 ，然后查看 C:\TDengine\log\ 目录下的日志

**Comment by lhd951220** [comment]
@xieyinglin 我使用window client查询都是没有结果返回的
![image](https://user-images.githubusercontent.com/41251046/72032592-c2ba6700-32ca-11ea-8309-9f467323350d.png)

**Comment by xieyinglin** [comment]
你的 client 和 server 版本不一致，请先将 client 和 server 都升级为相同版本的最新版

**Comment by lhd951220** [comment]
@xieyinglin 好的，我全部升级到最新版试一下

**Comment by lhd951220** [comment]
@xieyinglin 谢谢您，升级到最新版之后读取数据全部都是正常的了
