### ISSUE TITLE
compile errror on centos6.8

### ISSUE THREAD

**Issue by HonestQiao** [taosdata/TDengine#11]
[root@VM_007_centos build]# cmake —build .
……
/root/soft/TDengine/src/rpc/src/ttcpclient.c: In function 'taosOpenTcpClientConnection':
/root/soft/TDengine/src/rpc/src/ttcpclient.c:276: error: 'EPOLLWAKEUP' undeclared (first use in this function)
/root/soft/TDengine/src/rpc/src/ttcpclient.c:276: error: (Each undeclared identifier is reported only once
/root/soft/TDengine/src/rpc/src/ttcpclient.c:276: error: for each function it appears in.)
gmake[2]: Leaving directory `/root/soft/TDengine/build'
gmake[2]: *** [src/rpc/CMakeFiles/trpc.dir/src/ttcpclient.c.o] Error 1
gmake[1]: Leaving directory `/root/soft/TDengine/build'
gmake[1]: *** [src/rpc/CMakeFiles/trpc.dir/all] Error 2
gmake: *** [all] Error 2
[root@VM_007_centos build]# cat /etc/iss
issue      issue.net
[root@VM_007_centos build]# cat /etc/issue
CentOS release 6.8 (Final)
Kernel \r on an \m

[root@VM_007_centos build]# cmake --version
cmake version 2.8.12.2

**Comment by caoxinjava001** [comment]
centos 6.5 同样的问题
cd /home/sofe/Td/TDengine/TDengine-master/build/src/rpc && /usr/bin/cc  -DLINUX -D_LIBC_REENTRANT -D_LINUX -D_M_X64 -D_REENTRANT -D__USE_POSIX -g -std=gnu99 -Wall -fPIC -malign-double -Wno-char-subscripts -malign-stringops -msse4.2 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILE -O0 -DDEBUG -I/home/sofe/Td/TDengine/TDengine-master/src/inc -I/home/sofe/Td/TDengine/TDengine-master/src/rpc/./inc    -o CMakeFiles/trpc.dir/src/ttcpclient.c.o   -c /home/sofe/Td/TDengine/TDengine-master/src/rpc/src/ttcpclient.c
/home/sofe/Td/TDengine/TDengine-master/src/rpc/src/ttcpclient.c: In function ‘taosOpenTcpClientConnection’:
/home/sofe/Td/TDengine/TDengine-master/src/rpc/src/ttcpclient.c:276: error: ‘EPOLLWAKEUP’ undeclared (first use in this function)
/home/sofe/Td/TDengine/TDengine-master/src/rpc/src/ttcpclient.c:276: error: (Each undeclared identifier is reported only once
/home/sofe/Td/TDengine/TDengine-master/src/rpc/src/ttcpclient.c:276: error: for each function it appears in.)
gmake[2]: Leaving directory `/home/sofe/Td/TDengine/TDengine-master/build'
gmake[2]: *** [src/rpc/CMakeFiles/trpc.dir/src/ttcpclient.c.o] Error 1
gmake[1]: Leaving directory `/home/sofe/Td/TDengine/TDengine-master/build'
gmake[1]: *** [src/rpc/CMakeFiles/trpc.dir/all] Error 2

**Comment by caoxinjava001** [comment]
centos 6.5 同样的问题
cd /home/sofe/Td/TDengine/TDengine-master/build/src/rpc && /usr/bin/cc  -DLINUX -D_LIBC_REENTRANT -D_LINUX -D_M_X64 -D_REENTRANT -D__USE_POSIX -g -std=gnu99 -Wall -fPIC -malign-double -Wno-char-subscripts -malign-stringops -msse4.2 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILE -O0 -DDEBUG -I/home/sofe/Td/TDengine/TDengine-master/src/inc -I/home/sofe/Td/TDengine/TDengine-master/src/rpc/./inc    -o CMakeFiles/trpc.dir/src/ttcpclient.c.o   -c /home/sofe/Td/TDengine/TDengine-master/src/rpc/src/ttcpclient.c
/home/sofe/Td/TDengine/TDengine-master/src/rpc/src/ttcpclient.c: In function ‘taosOpenTcpClientConnection’:
/home/sofe/Td/TDengine/TDengine-master/src/rpc/src/ttcpclient.c:276: error: ‘EPOLLWAKEUP’ undeclared (first use in this function)
/home/sofe/Td/TDengine/TDengine-master/src/rpc/src/ttcpclient.c:276: error: (Each undeclared identifier is reported only once
/home/sofe/Td/TDengine/TDengine-master/src/rpc/src/ttcpclient.c:276: error: for each function it appears in.)
gmake[2]: Leaving directory `/home/sofe/Td/TDengine/TDengine-master/build'
gmake[2]: *** [src/rpc/CMakeFiles/trpc.dir/src/ttcpclient.c.o] Error 1
gmake[1]: Leaving directory `/home/sofe/Td/TDengine/TDengine-master/build'
gmake[1]: *** [src/rpc/CMakeFiles/trpc.dir/all] Error 2

**Comment by guanshengliang** [comment]
Thanks for opening this issue. We have already fixed this bug and committed it!
