### ISSUE TITLE
CPU突然暴增至100%

### ISSUE THREAD

**Issue by squ** [taosdata/TDengine#110]
Ubuntu 14.04.5 LTS
taosd: build from code

稳定运行时长36h后，突然CPU暴增至100%，然后taosd进程挂掉。
客户端使用http协议，访问量没有暴增。

![Screenshot_20190718_222118](https://user-images.githubusercontent.com/2545334/61465887-878a4b80-a9ab-11e9-9a93-4b8dfd667697.jpg)

![Screenshot_20190718_222004](https://user-images.githubusercontent.com/2545334/61465884-86f1b500-a9ab-11e9-9288-8ce6f7c28c1f.jpg)

**Comment by guanshengliang** [comment]
您可以把测试程序发给我吗，我试试可不可以重现这个问题。
邮件发到slgaun@taosdata.com即可

**Comment by guanshengliang** [comment]
Thanks for opening this issue. We have already fixed this bug and committed it!
