### ISSUE TITLE
Use Schemaless to write influxdb line protocol data. Error if single quotes exist in string, even if escaped.

### ISSUE THREAD

**Issue by liujianming04** [taosdata/TDengine#11073]
**Bug Description**
使用schemaless写入influx行协议数据，如果字符串中存在单引号，会写入报错，转义了也不行

**To Reproduce**
打印出来的是influx行协议数据，直接传到接口，单引号转义和不转义都报错，去掉单引号就能写入成功。

<img width="909" alt="0" src="https://user-images.githubusercontent.com/64473697/160517562-08a40cf2-425b-4ab2-94ca-75e2969ce666.png">

<img width="909" alt="1" src="https://user-images.githubusercontent.com/64473697/160517580-5dc75eba-43e7-499a-88aa-c08d3b206a68.png">

**Expected Behavior**
单引号无需转义，直接写入

**Screenshots**
无

**Environment (please complete the following information):**
 - TDengine Version 2.4.0.14

**Additional Context**
无

**Comment by fenghua1997** [comment]
已在 2.4、develop 分支修复，可关注 2.4 下个发布版本。（应该是 2.4.0.16 ）
