### ISSUE TITLE
When the field type is binary and taos_fetch_row returns more than 1000 rows, the subsequent result is abnormal

### ISSUE THREAD

**Issue by pigwing** [taosdata/TDengine#11099]
**Bug Description**
C#驱动,当调用taos_fetch_row的时候,IntPtr rowdata = TDengine.FetchRows(res);
当读取超过1000行以后,binary类型的字段读取的结果会按照前面字段的长度返回.
下图为读取小于1000行的时候
![31594b918170e0fbf9cb1b503c8b95a](https://user-images.githubusercontent.com/8393545/160584769-0d52cd08-d034-4373-8969-49f17e96ba61.png)
结束分别为pressure和temperature,
当有部分结果超出1000行以后,
![2ecb162144ec3f3f1d12d5bd9e14e41](https://user-images.githubusercontent.com/8393545/160584948-55b2af3a-64a0-40ea-8d22-94faa7e395bd.png)
temperature后面出现了essure,把前面的pressure中的pressure叠加进去了,其实也就是读取了前面结果等长长度,
再看下面一张图
![ae28e3839a3d122f85218d8239d3510](https://user-images.githubusercontent.com/8393545/160585232-671b85b9-6668-4cdd-9914-658fb272191a.png)
只要pressure后面的结果都超出1000行.则都出现叠加了essure变为了temperatureessure
其实就是,前面binary字段,内容是one-levle-pressure后面再出现了one-temperature,后面的内容跟前面不等长了,内容截取就取了前面内容的长度进行截取,但这个问题只是存在大于1000行的情况.

**Environment (please complete the following information):**
 - OS: windows,Linux
 - TDengine Version 2.4所有版本

**Comment by pigwing** [comment]
case TDengineDataType.TSDB_DATA_TYPE_BINARY:
                string v8 = Marshal.PtrToStringAnsi(data);

以上的返回类型

**Comment by xleili** [comment]
感谢反馈，我检查一下，有问题我改过来

**Comment by xleili** [comment]
这个问题导致的现象是什么？程序崩溃了还是读到的数据不正确。执行的sql语句是`select * from XX` 吗？或者说是其他的sql。确实有查询的结果被覆盖了的bug，已经修改了，根据taosc提供的接口fetch_length 来获取长度。
https://github.com/taosdata/TDengine/blob/develop/src/connector/C%23/examples/lib/Utils.cs#L221-L296

**Comment by pigwing** [comment]
@xleili 使用select * from table where  in('a','b','c')的方式查询.a,b,c的查询条件字段都是binary的,目前我的解决方式是用循环...往下发3条指令解决这个问题,但是效率非常低.毕竟in了很多查询条件,并且这个binary的字段是一个tag

**Comment by pigwing** [comment]
没报错,都有返回数据,只是数据返回不正确,返回出来的binary字段上的内容,有串到前面的内容,也就是memory.copy(0, len);这个len是上一行内容的len,如果下一行内容短了,这个len也是根据上一行内容的len截取,我目前理解是这样的,不知道是否正确,因为看我发的那三张图就这个情况.

**Comment by pigwing** [comment]
请问驱动什么时候上线呢,若无法使用in,会很影响效率.^_^

**Comment by pigwing** [comment]
还有这个,目前2.4.14的动态库中还是缺少这几个函数
https://github.com/taosdata/TDengine/pull/10896

**Comment by xleili** [comment]
> 请问驱动什么时候上线呢,若无法使用in,会很影响效率.^_^

1：这个驱动指的是C#的driver吗？如果是那么这驱动需要支持什么新函数吗？

**Comment by xleili** [comment]
> 还有这个,目前2.4.14的动态库中还是缺少这几个函数 #10896

这个我看，你已经提交了pr，需要在C# driver也做支持吗？

**Comment by xleili** [comment]
> 没报错,都有返回数据,只是数据返回不正确,返回出来的binary字段上的内容,有串到前面的内容,也就是memory.copy(0, len);这个len是上一行内容的len,如果下一行内容短了,这个len也是根据上一行内容的len截取,我目前理解是这样的,不知道是否正确,因为看我发的那三张图就这个情况.

超过1000行，返回结果不正确的问题。可以用我给你的链接里的代码（用接口FetchLengths()获取每个字段的length的数组）可以解决吗？

**Comment by pigwing** [comment]
可以动态库有导出就好,c#的dllimport我已经写了.在Linux不报错,在windows报缺少函数.

**Comment by xleili** [comment]
> 可以动态库有导出就好,c#的dllimport我已经写了.在Linux不报错,在windows报缺少函数.

这个下次发版应该就会有了。应该这一两周会发一版吧。

**Comment by pigwing** [comment]
![image](https://user-images.githubusercontent.com/8393545/160769625-da514a6f-9c9d-45b4-9c17-1bc25e0ea902.png)
![image](https://user-images.githubusercontent.com/8393545/160769677-e4116a7f-f934-4f45-a35f-cca9921dec77.png)
fetch_length 函数我这边获取不到长度呢.

**Comment by pigwing** [comment]
获取到的地址是0的.FieldCount获取到5是正常的.

**Comment by pigwing** [comment]
哦,我知道了...要放在TDengine.FetchRows后

**Comment by xleili** [comment]
问题已经解决，先做关闭处理。有问题可以再次打开
