### ISSUE TITLE
How to connect to tdengine on k8s by windows client 

### ISSUE THREAD

**Issue by gamechanger3** [taosdata/TDengine#11098]
**General Questions**
客户端怎样访问6030端口
所有的yaml文件都是官网的例子
service如下
![image](https://user-images.githubusercontent.com/26455226/160579730-b604c321-dc81-486c-83cd-d416c4f84679.png)

结果
![image](https://user-images.githubusercontent.com/26455226/160578903-fa8aa2b5-c8ee-469d-b5e7-e06bf2cdb8b5.png)

多谢！

**Comment by wuxingwang1997** [comment]
k8s方式部署的 不能通过6030 来登录的

**Comment by gamechanger3** [comment]
col
