### ISSUE TITLE
Error decompress in LZ4 algorithm!

### ISSUE THREAD

**Issue by squ** [taosdata/TDengine#111]
某次taosd挂掉，run命令taosd重新启动，报错

decomp_size:-1, Error decompress in LZ4 algorithm!
: No such file or directory

**Comment by guanshengliang** [comment]
Thanks for opening this issue. We have already fixed this bug and committed it!

**Comment by huangyuefeng** [comment]
我也踩这个坑了，/bin/taosd就会复现，感谢fixed。
