### ISSUE TITLE
This machine cannot connect to TDengine , error msg:  ERROR failed to connect to database, reason:Ref is not there

### ISSUE THREAD

**Issue by wzh2010git** [taosdata/TDengine#11108]
1.服务端: https://www.taosdata.com/assets-download/TDengine-server-2.4.0.14-Linux-x64.rpm
2.客户端: https://www.taosdata.com/assets-download/TDengine-client-2.4.0.14-Linux-x64-Lite.tar.gz
本机使用taos也无法连接,FQDN已配置(app-1),重启过好几次了
![td-error](https://user-images.githubusercontent.com/45517225/160630958-af66e49f-2549-45e6-8998-91b51e4c9b12.png)
端口也是可用的
![telnet](https://user-images.githubusercontent.com/45517225/160636804-1b8871b3-b331-425b-9764-c41f480d8183.png)

日志报错如下
![td-error2](https://user-images.githubusercontent.com/45517225/160631741-60c0dbb0-0e05-4778-9f32-1d5aedb7ddf6.png)
全部日志
[log.zip](https://github.com/taosdata/TDengine/files/8372333/log.zip)

**Comment by wzh2010git** [comment]
@fenghua1997 为什么要把我的的中文标题改成因英文

**Comment by fenghua1997** [comment]
@wzh2010git  为了让其他国家程序猿👨🏻‍💻也能看懂大致是什么问题。
请查看 6030-6042 的 tcp、**udp** 端口是否都已经放开

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
