### ISSUE TITLE
Getting "DB error: Permission denied" after importing data using taosdump

### ISSUE THREAD

**Issue by cdiwadkar16** [taosdata/TDengine#11116]
I exported data in my Linux VM using taosdump. TDengine version is 2.4.0.12.

Then on Azure VM I imported the files created by taosdump. TDengine version on Azure VM is also 2.4.0.12.

I can see that the database is imported, the super table and tables are imported.

If I try to do "select count(*) from powerload" (powerload is super table) I get "DB error: permission denied"
However I can do "select count(*) from <subtables>" and it works.
If I start taos shell with "sudo taos" I can do "select count(*) from powerload" and it works.

![showstablesandtables](https://user-images.githubusercontent.com/94201190/160750021-c702f9b1-1c9e-45b5-8651-d82e59bbe654.png)
![countFromStablesVsTables](https://user-images.githubusercontent.com/94201190/160750037-b6b6bf82-24a5-436e-b60f-33d6a08a32fa.png)
![sudoTaos](https://user-images.githubusercontent.com/94201190/160750046-f96efcc9-34a2-4ba7-9b7e-fd2a968d77f4.png)
![permissions](https://user-images.githubusercontent.com/94201190/160750059-c80ca8ce-4cec-4f7d-937c-80fa0fe2b18d.png)

**Comment by cdiwadkar16** [comment]
Not sure if this is a bug or if it's an issue with how TDengine was installed on the Azure VM.

**Comment by cdiwadkar16** [comment]
[tdshow@tdshow ~]$ more dump_result.txt 
========== arguments config =========
taosdump version 1.3.3-3-gf36b07f_f36b07f
host: (null)
user: root
password: taosdata
port: 0
outpath: 
inpath: nyisdo
resultFile: ./dump_result.txt
all_databases: false
databases: 0
databasesSeq: (null)
schemaonly: false
with_property: true
answer_yes: false
avro codec: snappy
data_batch: 16383
thread_num: 8
allow_sys: false
escape_char: true
isDumpIn: 1
arg_list_len: 0
debug_print: 0
========== DUMP IN ========== 
# DumpIn start time:                   2022-03-30 03:33:59
========== arguments config =========
taosdump version 1.3.3-3-gf36b07f_f36b07f
host: (null)
user: root
password: taosdata
port: 0
outpath: 
inpath: nyiso
resultFile: ./dump_result.txt
all_databases: false
databases: 0
databasesSeq: (null)
schemaonly: false
with_property: true
answer_yes: false
avro codec: snappy
data_batch: 16383
thread_num: 8
allow_sys: false
escape_char: true
isDumpIn: 1
arg_list_len: 0
debug_print: 0
========== DUMP IN ========== 
# DumpIn start time:                   2022-03-30 03:34:07

**Comment by fenghua1997** [comment]
I think the user is not authorized enough, you can change the TDengine data, log file directory permissions : chmod 777

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
