### ISSUE TITLE
How to modify root's password when I have forgot it?

### ISSUE THREAD

**Issue by JasonM528** [taosdata/TDengine#1112]
The manual documents tells us using "ALTER USER" to modify user's password in CLI mode. But if I forget root's pawword and it already not the default password, how can I reset it?
![20200109185758](https://user-images.githubusercontent.com/42922735/72062459-d12c7100-3312-11ea-89ca-d33d9e3a440c.png)

**Comment by guanshengliang** [comment]
There is currently no way, we will consider it in the future

**Comment by guanshengliang** [comment]
已经处理并提交到master分支，您可以拉master分支代码编译。或者等待几天后的2.0.1.1版本

具体步骤如下：
为taosd增加了-A参数，执行taosd -A命令，可以在当前目录生成auth.txt，里面包含加密后的用户授权信息，内容类似：
- user: _root auth:YQou5ojNqeckiF4jzSz97nJvb3QAAAAAAAAAAAAAAAA=
- user: monitor auth:YQou5ojNqeckiF4jzSz97nJvb3QAAAAAAAAAAAAAAAA=
- user: root auth:3MW+0EhR/shUwDWy5AJjtnJvb3QAAAAAAAAAAAAAAAA=

为taos增加了-A参数，使用taos -A  3MW+0EhR/shUwDWy5AJjtnJvb3QAAAAAAAAAAAAAAAA= ，可在无密码明文的情况下，登录数据库

**Comment by guanshengliang** [comment]
2.0.1.1版本已经发布，您可以验证一下

**Comment by guanshengliang** [comment]
There is no response to this issue for a long time, and this issue has been fixed in 2.0.1.1 version, so close it

**Comment by tjnh05** [comment]
@guanshengliang  Is there any solution to set password of user root while launching the service taosd? for example, set the environment variable TAOS_ROOT_PASSWORD as what mysqld do  ( environment MYSQL_ROOT_PASSWORD). Thanks.
