### ISSUE TITLE
When will the MAC OS Server be released.

### ISSUE THREAD

**Issue by kevinlim** [taosdata/TDengine#11136]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the circumstance is and what the associated problem is. Ex. I'm using TDengine for this use case: [...]. But I'm always frustrated when [...]

**Describe your desired behavior**
A clear and concise description of what you want to happen. Ex. I want TDengine to be able to do [...] when I try to do [...] with it.

**Describe your solutions/suggestions if you've any**
A clear and concise description of any solutions/suggestions to this problem or features you've considered.

**Additional context**

**Comment by fenghua1997** [comment]
这个没法给准确时间呢，大概会在我们 3.0 版本之后，目前可使用 docker 。

**Comment by guixincui** [comment]
可以通过源码在mac构建。构建成功无错误

**Comment by kevinlim** [comment]
> 可以通过源码在mac构建。构建成功无错误
有构建成功的教程可以分享下吗？     
我的mac m1 ,  构建过程中遇到不少麻烦

**Comment by yu285** [comment]
3.x 版本已经有mac服务端了，欢迎去官网使用体验https://docs.taosdata.com/
