### ISSUE TITLE
failed to install and run TDengine in the Mac docker virtual machine

### ISSUE THREAD

**Issue by 3-years-Czech** [taosdata/TDengine#1116]
当我在MAC的docker虚拟机（Ubuntu16 LTS系统）里安装deb包是报错为：
cp : cannot stat '%{init_d_dir}/taosd':No such file or directory
update-rc.d :error: initscript does not exit:/etc/init.d/taosd
于是我尝试使用源码安装，安装完成的启动中报错
UTL failed to get charset, please set the valid charset in config file

**Comment by liu0x54** [comment]
you can pull the tdengine/tdengine:latest image from dockerhub, which is based on the opensource 1.6.4.5 version.

**Comment by liu0x54** [comment]
Another solution is set the image ENV as below:
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8
-----
and  add a line in taos.cfg:

charset UTF-8

**Comment by 3-years-Czech** [comment]
刘先生：
       您好！
       很感谢你的提议为我解决了在苹果虚拟机上安装TDengine的问题。但是我在linux系统（具体版本为Linux version 4.15.0-88-generic (buildd@lgw01-amd64-036) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1))）上运行taosd服务器总是失败，您能帮助我解决这个问题吗？













At 2020-01-11 17:13:17, "Tao Liu" <notifications@github.com> wrote:

Another solution is set the image ENV as below:
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

and add a line in taos.cfg:

charset UTF-8

**Comment by liu0x54** [comment]
失败有没有什么提示信息？把打印信息贴上来吧

**Comment by shanlanCoding** [comment]
> 失败有没有什么提示信息？把打印信息贴上来吧

Ubuntu 16.04启动报错，查询日志后信息如下：
```shell
==================================================
                new log file
==================================================
03/20 09:02:24.404620 28498 7f1e4c14b700 UTL timezone not configured, set to system default:Asia/Shanghai (CST, +0800)
03/20 09:02:24.404634 28498 7f1e4c14b700 UTL locale not configured, set to system default:C
03/20 09:02:24.404640 28498 7f1e4c14b700 UTL failed to get charset, please set the valid charset in config file

```

**Comment by sangshuduo** [comment]
@s

**Comment by sangshuduo** [comment]
@shanlanCoding 后来问题解决了吗？
