### ISSUE TITLE
The TDengine is down, and the restart fails .135 logs do not show details.

### ISSUE THREAD

**Issue by qwe6887070** [taosdata/TDengine#11161]
### 系统运行环境
1、centos7.6  64  64G  1000G
2、数据库版本为2.2.0.5
3、单台测试使用
### 附件如下
![lALPJw1WRY2xyWnNASfNAxo_794_295](https://user-images.githubusercontent.com/62088375/161002229-ba55064c-bac1-4421-bc30-f535b0f3dc13.png)
[log&config.zip](https://github.com/taosdata/TDengine/files/8387023/log.config.zip)

**Comment by fenghua1997** [comment]
问题不太好定位。推荐升级到目前 2.4 的最新版

**Comment by qwe6887070** [comment]
> 

数据迁移该如何处理

**Comment by fenghua1997** [comment]
备份下各个节点的数据文件目录就行了。

升级具体步骤：
0.确保集群节点状态正常（show dnodes;），读写无问题。
1.在所有节点停止数据库服务systemctl stop taosd
2.备份数据文件目录下的所有内容 到数据文件目录之外。
3.分别cd进入各个节点的数据文件目录
4.tree命令检查所有vnode目录下的wal目录是否为空
5.如果为空，进入步骤7
6.如果非空，启动数据库进程，再关闭，直到wal全部为空。
7.在数据库服务taosd停止的状态下，分别在所有节点执行rmtaos  卸载（不会删数据文件和配置文件，但最好备份数据），然后安装新版本。(./install.sh)
8.分别启动所有节点的taosd服务，systemctl start taosd。
9.show dnodes检查节点状态
10.检查数据。

注：新版本 http 组件从 taosd 分离出来了，成为独立的服务进程：taosadapter，systemctl start taosadapter 启动，详情请看官网文档
