### ISSUE TITLE
Whether the TDengine supports asof join?

### ISSUE THREAD

**Issue by tankpanv** [taosdata/TDengine#11196]
你好，我尝试在TDengine 使用 asof join，但是在相关文档上没有找到关于asof join 的说明，请问一下TDengine 支持asof join吗

**Comment by fenghua1997** [comment]
目前还不支持 asof join 语句

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
