### ISSUE TITLE
Could you clarify in the manual that whether the csv file with header can be imported into the database?

### ISSUE THREAD

**Issue by saiyn** [taosdata/TDengine#1119]
import csv文件时不支持带表头的csv文件，这个问题我相信应该困扰过很多开发者。我感觉非常有必要至少在文档中注释情况，不然浪费开发者很多时间。

相关issue案例：

[https://github.com/taosdata/TDengine/issues/596](url)

[https://github.com/taosdata/TDengine/issues/1045](url)

**Comment by hjxilinx** [comment]
Thanks, we will fix this ASAP.
