### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [taosdata/TDengine#112]
Would you like to add more error handling for return values from functions like the following?
- [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [httpInitSystem](https://github.com/taosdata/TDengine/blob/6d17dbc0f89048a4316a2b38175a818d808625be/src/modules/http/src/httpSystem.c#L38)
- [pthread_mutex_init](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex.") ⇒ [taosMemPoolInit](https://github.com/taosdata/TDengine/blob/6d17dbc0f89048a4316a2b38175a818d808625be/src/util/src/tmempool.c#L65)

**Comment by hzcheng** [comment]
Sure. That's what we must do. Thank you!

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

**Comment by sangshuduo** [comment]
@elfring we are using coverity scan for static source code analysis.

**Comment by elfring** [comment]
Does [this analysis tool](https://scan.coverity.com/projects/tdengine "Coverity Scan for TDengine") present any remaining open issues (which I pointed out)?

**Comment by sangshuduo** [comment]
@elfring Thanks for your suggestion. I did not check whether your report is fixed or not since the project is continuing to improve and the code is always refactoring to make code quality better.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by sangshuduo** [comment]
@elfring totally agree with you. but we also need balance among quality, engineering, and schedule.

**Comment by elfring** [comment]
How do you think about to reopen this issue?

**Comment by sangshuduo** [comment]
Sure if the issue you reported is still exist.
