### ISSUE TITLE
How to improve the inserting speed at first time? Now for the same insertion, it takes about 350ms at the first time and takes about 20ms at the second time or later.

### ISSUE THREAD

**Issue by langshuo** [taosdata/TDengine#1123]
**Bug Description**
同样的insert语句段，第一次执行需要350毫秒，第二次以后只需要20毫秒左右，如何提高第一次执行插入数据语句的执行速度。
截图：
![批注 2020-01-12 172707](https://user-images.githubusercontent.com/49328505/72216809-d4b53780-3560-11ea-9ebb-3541560832c9.png)

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.7]
 - TDengine Version [e.g. 1.6.4.3]

**Comment by langshuo** [comment]
insert语句如下，id是timest类型。
INSERT INTO  CJGF_NBQ_001_001 (id,YC0101) VALUES (0,1) CJGF_NBQ_001_002 (id,YC0101) VALUES (0,1) CJGF_NBQ_001_003 (id,YC0101) VALUES (0,1) CJGF_NBQ_001_004 (id,YC0101) VALUES (0,1) CJGF_NBQ_001_005 (id,YC0101) VALUES (0,1) CJGF_NBQ_001_006 (id,YC0101) VALUES (0,1) CJGF_NBQ_001_007 (id,YC0101) VALUES (0,1) CJGF_NBQ_001_008 (id,YC0101) VALUES (0,1) CJGF_NBQ_001_009 (id,YC0101) VALUES (0,1) CJGF_NBQ_001_010 (id,YC0101) VALUES (0,1) CJGF_NBQ_001_011 (id,YC0101) VALUES (0,1) CJGF_NBQ_001_012 (id,YC0101) VALUES (0,1) CJGF_NBQ_001_013 (id,YC0101) VALUES (0,1) CJGF_NBQ_001_014 (id,YC0101) VALUES (0,1)

**Comment by plum-lihui** [comment]
应该是第一次需要获取table的meta，所以需要多花费一些时间。如果想提高第一次执行插入速度，那就得提前获取一下table的meta。TDengine提供了一个批量获取meta的API：int taos_load_table_info(TAOS *taos, const char* tableNameList);  其中 tableNameList是需要后meta的tables，比如："CJGF_NBQ_001_001,CJGF_NBQ_001_002,CJGF_NBQ_001_003,CJGF_NBQ_001_004".
