### ISSUE TITLE
last_row 用法问题，last_row还有其他方式吗？

### ISSUE THREAD

**Issue by thicktao** [taosdata/TDengine#11253]
**General Questions**
我想查询出两个子表的最后一行数据，貌似下面的语句只能查出deviceid=5的设备
select last_row(propertyid)  from historyrecordsecond where deviceid in (5,6);
![image](https://user-images.githubusercontent.com/40555417/161904815-979505ad-478e-49f3-8cb7-0b95d7a83644.png)

只能通过union all的方式来：
select last_row(propertyid)  from historyrecordsecond where deviceid in (5) 
union all 
select last_row(propertyid)  from historyrecordsecond where deviceid in (6);
![image](https://user-images.githubusercontent.com/40555417/161904779-08416fee-4895-46c0-9366-a711ee3c75e9.png)

**Comment by fenghua1997** [comment]
deviceid 是 tag 字段吧
试试 select last_row(*)  from historyrecordsecond  where deviceid in (5,6)  group by deviceid
可查相关子表的最后一行

**Comment by thicktao** [comment]
@fenghua1997 好的，已经OK，非常感谢
