### ISSUE TITLE
cachelast=1 does not take effect，last_row  may not use cache？

### ISSUE THREAD

**Issue by thicktao** [taosdata/TDengine#11277]
![image](https://user-images.githubusercontent.com/40555417/162125595-74d10734-4558-483a-b33d-ffcb525aac48.png)
目前数据5000W，查询 select last_row(*) from historyfamily where deviceid in (1);性能较低。

```
DROP DATABASE IF EXISTS historys;
CREATE DATABASE historys KEEP 1095 DAYS 10 BLOCKS 64 UPDATE 1;

CREATE STABLE historyfamily (
CreateTime TIMESTAMP ,
deviceid BIGINt,
DeviceCode BINARY(100),
DevicePointName NCHAR(200),
InsertTime TIMESTAMP ,
IsError bool,
IsAlarm bool,
devstate TINYINT,
StateVar NCHAR(30),
Concentration DOUBLE
)
TAGS (
ProjectId BIGINt,
ProjectName NCHAR(200));
```

版本：Dengine-server-2.4.0.10-Linux-x64.rpm
配置：/etc/taos/taos.cfg中
![image](https://user-images.githubusercontent.com/40555417/162125862-682a6402-ee45-437f-9c59-c60b761c856b.png)
taosd -C 显示cachelast=1:
![image](https://user-images.githubusercontent.com/40555417/162125839-b247a9c1-5739-47a7-a78d-6770e4e50a9f.png)
服务器：三节点，8U,16G

**Comment by fenghua1997** [comment]
命令行中执行 show databases\G 看看所查的数据库的这个参数值是不是 0

**Comment by fenghua1997** [comment]
把条件里面的 in 改为 = 试试？看看有没有变化
然后还可以执行一下下面两个 sql ，对比一下三个语句的速度先
select last_row(*) from  historyfamily  where deviceid=1  group by tbname
select last_row(*) from 子表名
都执行完后把结果发出来吧  定位下问题

**Comment by thicktao** [comment]
![image](https://user-images.githubusercontent.com/40555417/162165877-dca4a479-e5c9-4456-ab6d-40454c96b2c8.png)
![image](https://user-images.githubusercontent.com/40555417/162166043-ef50cb0e-00c6-445e-9a4f-af0264952123.png)
![image](https://user-images.githubusercontent.com/40555417/162166156-ea7855af-c341-40ed-87b4-035f3b023d9a.png)
直接子表最快

**Comment by fenghua1997** [comment]
select last_row() from historyfamily where deviceid=1 group by tbname
这句后面就 group by tbname    看有没有走缓存

**Comment by thicktao** [comment]
![image](https://user-images.githubusercontent.com/40555417/162340942-d29316ff-3c13-42a4-90aa-e47e07b1549b.png)
![image](https://user-images.githubusercontent.com/40555417/162341161-52f8a644-d40d-4b34-9907-e18f08bf6ec5.png)

1、走tags比较筛选比较快，
2、和where 条件顺序无关；
3、感觉和group by每有关系

**Comment by thicktao** [comment]
这个deviceid in 的列表 越多，即使走内存也比较慢哦

**Comment by gccgdb1234** [comment]
**走tags比较筛选比较快**：是的，**请尽量使用tag进行筛选，避免用普通列**，从测试结果也可以看出这个规律。这个行为符合设计预期。
