### ISSUE TITLE
some typo and misleading contents in TDengine manual

### ISSUE THREAD

**Issue by qinzuoyan** [taosdata/TDengine#113]
In `TDengine_User_Manual_cn.pdf`:

- chapter 7.7:
  ```
  注意事项：
  1. 同时进行多个字段的范围过滤需要使用关键词 AND 进行连接不同的查询条件，暂不支持 OR 连接的查询条件。
  2. 针对某一字段的过滤只支持单一区间的过滤条件。例如 value>20 and value<30 是合法的过滤条件 , 而 value< 20 AND value<>5 是非法的过滤条件。
  ```
  注：
  * `暂不支持 OR 连接的查询条件` 这句话与实际表现不一致（或者至少文档这里说明不够全面），让人困惑。我测试发现是可以对多个字段使用OR连接的查询条件的，譬如：`select * from thermometer where ts>=now-1h or degree>10;`。
  * 如果查询使用了非法的过滤条件，taosd居然会core掉。这个已经另外提了一个issue并解决 #91 。

- chapter 8.1: `连接库` -> `链接库`
  ```
  taosc 一个软件模块是TDengine 给应用提供的驱动程序（ driver 内嵌 于 JDBC 、ODBC driver 中 或者 C 语言连接库里。
  ```

- chapter 8.4
  ```
  如果 离线时间超过一定时长（时长由配置参数 offlineThreshold 决定），该 dnode 将被 mnode 强制剔除出集群。该 dnode 上的 vnodes 如果副本数大于一，系统将自动在其他 dnode 上创建新的副本，以保证数据的副本数。
  ```
  注：`该dnode上的vnodes如果副本数大于一` 这句话有歧义。本意可能是说：该dnode上正在服务的vnodes，如果配置的副本数大于1，该dnode下线后，副本数减少，就自动在其他dnode上补充新的副本。另外，此处没有说明副本数等于1的情况，这种情况下会导致停服甚至丢数据？我觉得需要说明清楚。

- chapter 10.6: `tianjing` -> `tianjin`
  ```
  SELECT COUNT(*), AVG(degree), MAX(degree), MIN(degree)
  FROM thermometer
  WHERE location='beijing' or location='tianjing'
  GROUP BY location, type;
  ```

- chapter 10.6: `name` -> `location`
  ```
  SELECT COUNT(*), AVG(degree), MAX(degree), MIN(degree)
  FROM thermometer
  WHERE name<>'beijing' and ts>=now-1d
  INTERVAL(10M)
  GROUP BY location, type;
  ```

**Comment by hzcheng** [comment]
Thank you very much. We will fix it.
