### ISSUE TITLE
Group by primary key aggregation, return no  primary key ( ts )

### ISSUE THREAD

**Issue by chenaiyuan** [taosdata/TDengine#11317]
问题:
taos> select sum(current) from meters where ts>='2017-07-14 10:40:00.000'and ts<='2017-07-14 10:40:00.002' group by ts;
       sum(current)        |
============================
           96806.650161743 |
           94416.284561157 |
           96416.978836060 |
Query OK, 3 row(s) in set (0.836882s)

taos> select ts,sum(current) from meters where ts>='2017-07-14 10:40:00.000'and ts<='2017-07-14 10:40:00.002' group by ts;

DB error: invalid operation: only one selectivity function allowed in presence of tags function (0.000864s)

现在的需求：
统计所有的设备或者是一定范围的设备在一定时间范围的汇总值。设备的数据是规律的，10分钟一条数据。

**Comment by chenaiyuan** [comment]
![image](https://user-images.githubusercontent.com/48537400/162407784-73296754-d3c8-4cc2-95d5-a0610cdcb99a.png)

**Comment by fenghua1997** [comment]
数据是 10 分钟规律写入的话，可以看一下 interval 能不能满足汇总需求：
https://www.taosdata.com/docs/cn/v2.0/architecture#%E6%8C%89%E6%97%B6%E9%97%B4%E8%BD%B4%E8%81%9A%E5%90%88%E3%80%81%E9%99%8D%E9%87%87%E6%A0%B7%E3%80%81%E6%8F%92%E5%80%BC

**Comment by gccgdb1234** [comment]
select ts,sum(current) from meters where ts>='2017-07-14 10:40:00.000'and ts<='2017-07-14 10:40:00.002' group by ts;
这条语句的实际结果是 每个时间点 上所有设备（子表）的current之和
而实际需求是  "统计所有的设备或者是一定范围的设备在一定时间范围的汇总值。设备的数据是规律的，10分钟一条数据"

如果是这样的需求的话，我觉得去掉 "group by ts"就可以了。
