### ISSUE TITLE
Compilation under MacOS

### ISSUE THREAD

**Issue by jasonjoo2010** [taosdata/TDengine#1133]
**Describe your desired behavior**
There are errors compiling under MacOS(10.15 Catalina)

**Describe your solutions/suggestions if you've any**
I am working on it.

**Additional context**
I just found some os dependent headers / implementations and i am curious that does it work in older MacOS? There are actually kinds of errors under 10.15(maybe because updated clang/headers introduced).

It's not a big deal and i am working on it.

Another question is that i want to test TDE on a project related stats replacing influxdb but i just concerned about the license. May i test and use it without publishing our business codes?

**Comment by jasonjoo2010** [comment]
Oh after some works compiling has completed successful with no error and no warning bug there is only `tao` in `build/bin`.

So the codes opened source till now are only for `client`?

**Comment by jasonjoo2010** [comment]
Oh I found the problem and try to solve it further to see if it can be migrated to BSD system.

**Comment by guanshengliang** [comment]
Although many people develop on mac, few people use mac in production environment. So there are currently no plans to compile the server on Mac. 

Earlier versions of the client on the Mac were able to compile, but as the version evolved, there was not enough energy to focus on this. After the Spring Festival, we will package the compiled mac client and download it on the official website.

Compiling on different operating systems and architectures is a challenge, but compiling is only one problem, more problems are testing, and the recurrence/repair of bugs after they occur. Therefore, the official does not have enough energy to provide too much operating system support.

**Comment by guanshengliang** [comment]
I am not very clear about the open source license.
Our original intention is to prevent cloud service providers bypass us to provide services

**Comment by jasonjoo2010** [comment]
> I am not very clear about the open source license.
> Our original intention is to prevent cloud service providers bypass us to provide services

Yep got it and i have fixed the compilation issue of client on mac.
Now i continue to work on server, demo, dump. I will check if there are too much changes especially essential changes. If not, maybe i can contribute a PR and we can check if it was worth to support.
Surely it only enables one more environment for developing but not deploying. I agree with you at this point.

About the license.
AGPL has so much transitivity and it requires all projects used AGPL project, no matter directly or remotely through some kinds of RPC protocol, should be opened source, too. In commercial scenario it's not friendly compared to LGPL/Apache/MIT. Maybe if it can be allowed in non-cloud service provider like scenario you can migrate it to an alternated license based on `AGPL`. And it can enable more power from open source community i think.

**Comment by jasonjoo2010** [comment]
Oh it's almost done except the last small module `http`. It's hardcode programmed with `epoll` which different system has different similar implementation. What the main function of it and is it an important module?

If it's an important module it's better to integrate `libev` or something like that to get better performance and better compatibility.

**Comment by JulianZhao** [comment]
@guanshengliang 
Is the  mac client ready for download? thanks.

**Comment by guanshengliang** [comment]
On some macs, the udp package cannot exceed 64k, so although the 1.6 version of the mac can be compiled, it is not released
Version 2.0 will be included in the development plan.
If you need to develop on mac, you can consider using docker

**Comment by jasonjoo2010** [comment]
> On some macs, the udp package cannot exceed 64k, so although the 1.6 version of the mac can be compiled, it is not released
> Version 2.0 will be included in the development plan.
> If you need to develop on mac, you can consider using docker

Thank you for your information, guan

**Comment by jasonjoo2010** [comment]
I will close it now due to no further question.
