### ISSUE TITLE
Error reported when I build

### ISSUE THREAD

**Issue by jingjianhe** [taosdata/TDengine#11335]
**Bug Description**
# github.com/taosdata/driver-go/v2/wrapper
vendor/github.com/taosdata/driver-go/v2/wrapper/stmt.go:54:13: could not determine kind of name for C.taos_stmt_set_tbname
vendor/github.com/taosdata/driver-go/v2/wrapper/stmt.go:35:14: could not determine kind of name for C.taos_stmt_set_tbname_tags

**To Reproduce**
1. centos 7 go 1.15.15
2. 之前用的是 github.com/taosdata/driver-go/taosSql,现在更新项目后发现之前的import 报错不是最新的  我就使用了重构后的v2版本发生上面的报错，

**Comment by sangshuduo** [comment]
TDengine client 版本太低了吧

**Comment by jingjianhe** [comment]
> TDengine client 版本太低了吧

我部署用的是tdengine的容器，tdengine client 装在linux上，client版本和数据库server版本是对应的，都是2.0.16.0，client的版本和server版本可以不对应么

**Comment by jingjianhe** [comment]
> TDengine client 版本太低了吧

谢谢您  确实是版本低了
太感谢了
