### ISSUE TITLE
Python connector document error 

### ISSUE THREAD

**Issue by feverwind** [taosdata/TDengine#1134]
**Bug Description**
In document [Python-Connector](https://www.taosdata.com/cn/documentation/connector/#Python-Connector)，the example miss ‘）'
`print("Row%d: ts=%s, temperature=%d, humidity=%f" %(irow, data[irow][0], data[irow][1],data[irow][2])`

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by localvar** [comment]
Thanks for pointing this out, we will revise the documentation.
