### ISSUE TITLE
Whether the string of indefinite length is supported ？DB error: invalid operation: (Argument list too long) 

### ISSUE THREAD

**Issue by tankpanv** [taosdata/TDengine#11358]
你好，我在尝试使用tdengine存储字符串类型的内容，由于字符串是在程序中执行生成，我无法事先确定字符串长度。可是在数量类型里我找不到string类型。只有nchar类型。nchar类型需要设置长度。如果我设置nchar的长度数值比较大，比如设为2048长度，会不会我在存储的时候该字段为空字符串的时候也会占2048的空间

**Comment by fenghua1997** [comment]
你好，目前只有定长的，像 vachar 这样的不定长的未来会在新版本支持。
在存储的时候我们会对未利用到的空间进行压缩，不会占这么多的存储空间。

**Comment by gccgdb1234** [comment]
nchar()实际占用空间取决于实际值，但最大允许的值长度取决于定义。 @tankpanv
