### ISSUE TITLE
After the cluster is set up, the taos built-in database log shows that synchronization is in progress, but there is only one replica

### ISSUE THREAD

**Issue by huchaogithup** [taosdata/TDengine#11361]
![image](https://user-images.githubusercontent.com/44936431/162612032-bdf5b2fc-ef0d-4732-ba05-f6f400ad7693.png)
![image](https://user-images.githubusercontent.com/44936431/162612042-3a18c6ca-50de-4045-a9c2-e0b9ac768db7.png)
节点添加成功
![image](https://user-images.githubusercontent.com/44936431/162612074-aed27441-0d23-41f5-a693-8869bf8fd184.png)
log数据的replica为1
![image](https://user-images.githubusercontent.com/44936431/162612108-ff4136af-0f7e-4e10-9ce5-f927e673616e.png)
目前vg2显示都是正常
当创建自己数据库，创建超表插入数据后，log的vg2显示同步副本，但是副本数量只有一个
![image](https://user-images.githubusercontent.com/44936431/162612156-104974cc-519d-4a38-acc0-0c5047fe6946.png)
后台日志
![image](https://user-images.githubusercontent.com/44936431/162612540-9742fcb2-a7e7-469c-b3ee-691a3ccf6c84.png)

**Comment by gccgdb1234** [comment]
@huchaogithup 具体版本是？这个现象可以重现
