### ISSUE TITLE
2.4.0.16 C# driver insert Chinese error : Illegal byte sequence

### ISSUE THREAD

**Issue by pigwing** [taosdata/TDengine#11362]
**Bug Description**
TDengine.Query(conn, commandText);后
返回的intPrt不为0,TDengine.Error显示Illegal byte sequence

**Environment (please complete the following information):**
 - OS: windows
 - Memory, CPU, current Disk Space
 - TDengine Version 2.4.0.16

**Comment by xleili** [comment]
这个问题是应为是C#在window上是使用的UFT-16的编码。C# driver 已经修复过这个问题了。
可以参考：https://github.com/taosdata/TDengine/blob/d27b25a6780ca4f3dd357470c44a476418668996/src/connector/C%23/src/TDengineDriver/TDengineDriver.cs#L232-L239

**Comment by xleili** [comment]
https://github.com/taosdata/TDengine/issues/9973

**Comment by pigwing** [comment]
已经是做过转码了,这个版本前是没问题的.16又重新出现了.

**Comment by xleili** [comment]
那我再找找问题

**Comment by wuyupengcool** [comment]
版本.16 客户端 sql  字符串字段插入也出现该问题  字符串 中有个‘-’

**Comment by wuyupengcool** [comment]
> 是的

**Comment by wuyupengcool** [comment]
> > 版本.16 客户端 sql 字符串字段插入也出现该问题 字符串 ‘郑州轻工业学校-郑上路校区‘
> 
> 这里的客户端，指的是windows段的taos-shell 吗？

是的 字段 nchar(100) windows  客户端 插入 INSERT INTO TEST values(NOW,'郑州轻工业学校-郑上路校区'); 报错   暂时换BINARY 字段了

**Comment by pigwing** [comment]
> > 版本.16 客户端 sql 字符串字段插入也出现该问题 字符串 ‘郑州轻工业学校-郑上路校区‘
> 
> 这里的客户端，指的是windows段的taos-shell 吗？

.16这几天用起来还有个比较严重的问题.Linux下,经常性会查询超时,很频繁抛出Ref is not there异常,切换回.14就一切正常了.
