### ISSUE TITLE
How should table names be defined in table structure design?

### ISSUE THREAD

**Issue by fatcarter** [taosdata/TDengine#11389]
在文档的例子中使用了随机的数据表名称， 例如d001,d002等，如果使用这种随机的表名，下次相同tag的数据该如何找到对应的表名插入？ 
如果使用固定字符串+tag值作为表名的话，例如meter_SN01, meter_SN02, 这种情况下，如果新增一个tag就需要更改表的名字，否则就不能按照新的tag进行分表；
请问，在td的设计中，数据表的表名应该如何定义？

**Comment by gccgdb1234** [comment]
You can use schemaless write without worrying about the table name. Please refer to below link for details.
https://www.taosdata.com/docs/cn/v2.0/insert#schemaless
