### ISSUE TITLE
Telegraf failed to write to TDengine

### ISSUE THREAD

**Issue by devbiu** [taosdata/TDengine#11382]
![image](https://user-images.githubusercontent.com/99388822/162694622-1ea7e46a-4a54-466a-915e-1aa99921c8b4.png)
重启之后 数据库以及超级表创建成功,但是子表没有,所以报表不存在的错误?? taos连接的是本机地址  telegraf 版本是 1.22.0 taos版本是 2.4.0.14

**Comment by huskar-t** [comment]
@devbiu 
Please follow this guide <https://www.taosdata.com/blog/2020/09/11/1824.html> to configure fqdn
