### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by MasonYangD** [taosdata/TDengine#1139]
taosd version:1.6.4.3
当执行sql: select count(*) from agentcalldetail where answertime='2020-01-01 00:00:00.000000'
备注：answertime类型为TIMESTAMP，非第一个time字段
状态：taosd服务直接崩掉
控制台报错信息：
taosd: /mnt/hgfs/work/TDrelease/community/src/system/detail/src/vnodeFilterFunc.c:159: equal_i64: Assertion `*(int64_t *)minval < *(int64_t *)maxval' failed.
Aborted (core dumped)

**Comment by hjxilinx** [comment]
您可以尝试将版本升级到1.6.4.5试一试。
