### ISSUE TITLE
Questions about cachelast and cache usage

### ISSUE THREAD

**Issue by chenaiyuan** [taosdata/TDengine#11456]
问题描述：
1.使用参数CACHELAST创建数据库
CREATE DATABASE znn_test KEEP 365 DAYS 10 BLOCKS 6 UPDATE 2 CACHELAST 2;
2.插入测试数据
INSERT INTO d2 USING meters TAGS ('2', 2) VALUES ('2022-04-10 14:14:00.000', 10.2, 219, 0.32);
INSERT INTO d2(ts, voltage)  USING meters TAGS ('2', 2) VALUES ('2022-04-10 14:17:00.000', 219);
3.使用last_row查询，结果却返回的是个null
 select last_row(current) from d2;
       current        |
=======================
                 NULL |

疑问：我在创建数据库的时候把CACHELAST参数设置成了2，按理说 select last_row(current) from d2;的时候应该返回的是不为空的列值，返回的是10.2才对。是我使用的方式不对还是对这个参数理解的有问题？

**Comment by gccgdb1234** [comment]
Please use "select last(current) from d2;"
when using last_row(column), it firstly fetches the last row (regardless of the value) and return the specified column.

**Comment by gccgdb1234** [comment]
Here is the description for the two functions:
last_row: 返回表/超级表的最后一条记录
last: 统计表/超级表中某列的值最后写入的非 NULL 值。

**Comment by chenaiyuan** [comment]
last会从cache里面取数据吗。现在想验证cachelast 和 cache的查询性能

**Comment by gccgdb1234** [comment]
@chenaiyuan 这个问题是否可以关闭？cache和cacheLast的使用文档上有介绍。
