### ISSUE TITLE
An error occurred in the query minimum

### ISSUE THREAD

**Issue by eltonchaw7** [taosdata/TDengine#1146]
![wx_camera_1579168651694](https://user-images.githubusercontent.com/53032426/72516598-e19d9800-388c-11ea-9776-4e97e8e0ed0f.jpg)

**Comment by hjxilinx** [comment]
您好，您使用的TDengine是什么版本？

**Comment by eltonchaw7** [comment]
1.6.4.4

**Comment by sangshuduo** [comment]
请试试新版本
