### ISSUE TITLE
Using Mybatis is not supported  this judgment of != or <>

### ISSUE THREAD

**Issue by caiqiqqq** [taosdata/TDengine#11471]
我在使用mybits 写sql语句的时候，发现好像不支持 ！= 这种操作
同一条sql。我在 shell中能够查询到，
使用RS 链接方式也能查询到，
但是使用 druid链接池。的这种链接方式就不是查询不到，把！= 这个条件去掉，就能查询到，
deleted 类型 我设置为BOOL 
查询结果  sell能够查询到，  RS 能够查询到，druid 查询没有结果

后来我把 deleted 类型换成。int。也发现查询不到 

查询结果。sell能够查询到，RS 能够查询到，  druid。查询没有结果

下面的是我sql 语句

select LAST(*) from  gateway_072021320021  WHERE deleted <> 1 or deleted is null

tdeng 版本2.4。

**Comment by huolibo** [comment]
我在做测试时发现 mybatis xml 中不支持 <>
将 sql 改做 `select LAST(*) from gateway_072021320021 WHERE deleted != 1 or deleted is null` 呢？
