### ISSUE TITLE
How to migrate mysql data to TDengine.

### ISSUE THREAD

**Issue by dev007-art** [taosdata/TDengine#11498]
mysql的数据怎么迁移到TDengine里面，有老哥有方案吗

**Comment by huolibo** [comment]
现在有很多成熟的工具可以用作数据迁移。比如 Kafka Connector，但需要编写 source、sink 模块代码。
阿里开源了一款专门做数据迁移的工具：dataX，并且 TDengine 官方已经为此工具编写了 plugins，可以做到 0 代码丛 MySQL 迁移数据至 TDengine。详见[dataX](https://github.com/taosdata/DataX)

**Comment by dingbo8128** [comment]
https://github.com/taosdata/DataX/blob/master/tdenginewriter/doc/tdenginewriter-CN.md
