### ISSUE TITLE
连续两次拒绝服务的 log 如下

### ISSUE THREAD

**Issue by squ** [taosdata/TDengine#115]
taosd: /root/TDengine-master/src/system/src/vnodeCache.c:628: vnodeQueryFromCache: Assertion `key >= pQuery->skey' failed.

**Comment by guanshengliang** [comment]
看来您测试比较认真，请和我们建立联系，以便更好的解决提交的BUG
slguan@taosdata.com

**Comment by guanshengliang** [comment]
邮箱中可以包含您的一些联系方式

**Comment by guanshengliang** [comment]
Thanks for opening this issue. We have already fixed this bug and committed it!
