### ISSUE TITLE
select sum(current) from (SELECT last(current) FROM meters WHERE ts >= '2022-04-10 00:00:00.000' AND ts < '2022-04-11 00:00:00.000' INTERVAL(1m) FILL(PREV) group by tbname) interval (1m) ;

### ISSUE THREAD

**Issue by chenaiyuan** [taosdata/TDengine#11513]
以meters表为例：
每个子表下的每条数据的时间间隔最小为1分钟
![image](https://user-images.githubusercontent.com/48537400/163503123-71d901ea-a99a-4024-a71e-76c97c221157.png)

需求是这样的，以1分钟为一个计量点，绘制整个地市下所有电表的总电流曲线。
在这里以tbname分组，查询每个区间下的每个电表的的last current,因为是有些设备数据可能没有采集回来，或者是该设备不是1分钟采集一次，而是10分钟或15分钟的频率。
现在我的测试数据是设备30万，发现执行上面的sql根本执行不出来，估计要执行很久。
我把时间区间改成ts >= '2022-04-10 00:00:00.000' AND ts < '2022-04-11 00:10:00.000'，结果可以查询出来，但是也花费的10秒多。
类似于这种需求，有没有什么解决方案。

**Comment by gccgdb1234** [comment]
create table sum_current as select sum(current) from meters interval(1m) sliding(1m);
然后每隔一分钟，select last(sum_current) from sum_current;

**Comment by chenaiyuan** [comment]
select sum(current) from meters interval(1m) sliding(1m);  
这样有个问题，有些设备时15分钟采集频率 比如说00：00，00：15
在00：01到00：14这个每分钟的时间窗口，这样做sum，是不会计算这个电表值的。
我们的需求是在00：01到00：14的时候，使用这个电表00:00采集的数据做sum

**Comment by gccgdb1234** [comment]
> select sum(current) from meters interval(1m) sliding(1m); 这样有个问题，有些设备时15分钟采集频率 比如说00：00，00：15 在00：01到00：14这个每分钟的时间窗口，这样做sum，是不会计算这个电表值的。 我们的需求是在00：01到00：14的时候，使用这个电表00:00采集的数据做sum

是有点问题，所以我删除了原先的建议，正在试其它的

**Comment by gccgdb1234** [comment]
**需求是这样的，以1分钟为一个计量点，绘制整个地市下所有电表的总电流曲线**。

从绘制总电流曲线的应用端出发，每一分钟执行一次以下SQL就可以，然后可以把结果存在一张特殊的表中，可以仍然带上时间戳。
select sum(current) from (select ts, last(current) from meters group by tbname);
在我本机，cacheLast=2的情况下，30万张子表，上述语句执行时间在一秒钟以内；如果是服务器会更快。
以一分钟的间隔来执行它完全不是问题。

**Comment by chenaiyuan** [comment]
现在的思路确实是这么一个思路 。   只不过是这30万属于省级设备量。我们展示这个曲线有多级维度。省、市、县、所、台区多级。估计每分钟要执行的sql比较多，可能几千条，不知道数据库能不能抗的住

**Comment by gccgdb1234** [comment]
可以这样子从应用端出发来降低数据库负载
从数据模型上：
1. 有这些超级表：电表，台区，所，县，市，省
2. 一个电表一张表；2.一个台区一张表；3.一个所一张表；4. 一个县一 张表；5.一个市一张表；6.一个省一张表
在应用端
1. 首先从数据库只筛选台区，通过tag来筛选出属于一个台区的子表，将所有台区的结果写入一个台区的超级表
比如 select sum(current) from (select ts, last(current) where "台区" = "abc" group by tbname);
将结果写入台区表
2. 然后从台区结果聚合成所的结果，依此类推

**Comment by chenaiyuan** [comment]
好的 多谢

**Comment by chenaiyuan** [comment]
insert的时候可以修改tag吗  tag只能通过alter修改吗

**Comment by gccgdb1234** [comment]
insert into tb1 using meters TAGS ("beijing", "1")
insert into tb1 using meters TAGS("beijing", "1")
是这样吗？
如果是的话，第二条insert插入成功，因为tb1已经存在，后面的using和TAGS会被忽略
