### ISSUE TITLE
About Tables Design

### ISSUE THREAD

**Issue by RainWong** [taosdata/TDengine#1152]
您好 TDengine，
请问以下业务情景如何设计表会更有利于后续的查询、分析和统计?
1、100台生产设备，每台设备有设备的属性（如所属车间、设备编号、维护人等）
2、每台设备有近300个采集指标，100个报警指标，每个指标也有自己的属性（如所属组、指标名称、指标编号、指标类型、PLC地址），指标的采集频率并不是全部都相同的

我的想法：
1、一台设备一个表，可能无法记录指标的属性
2、一个指标一个表，会不会导致表太多，分析汇总困难，或影响性能

感谢！

**Comment by hjxilinx** [comment]
采集频率不同的指标不能放在同一个表中。
所以同一个设备的指标无法放在同一个表中。
可以考虑使用单值模型来存储，每个表一个指标。100*300 = 30000万表不多。
我的问题是，不同的指标有同时查询的需求吗？

**Comment by liu0x54** [comment]
首先一个指标一个表是可以的，你目前的数据来看是完全足够的。
建议先把数据划分清楚，按照数据名称，数据标签，数据值来划分。
数据名称是这类数据的总称，比设备有个电压测量量A，则这个数据名称就是电压A；
数据标签是用来区分这个数的，比如是哪个车间的哪台设备的电压A，那么车间，设备编号，维护人员，都可以作为标签，因为这些不会发生变化，通过这些标签值可以唯一确定这个数据是来自哪里；
数据值就是这个数据的类型。如果是跟其他数据无关，也不会同时上报，即这个数据报上来的时间戳是跟其他数据没有关系的，独立的，那么这个数据就是一个标量数据，就单独建一个超级表来存这类数据；
而如果一组数据是同时上报的，每次上报都有，而且共用一个时间戳，那么这组数据可以看做是一个矢量，可以用一个超级表来存储。
采用以上原则，把数据划分清楚了，建表的思路就比较清楚了

**Comment by RainWong** [comment]
@hjxilinx 确实存在查询某台设备所有或部分指标值的情况，比如当某两个指标值超出范围时，报警。车间大屏实时显示该设备所有指标的采集值。请问能否实现？
@liu0x54 多谢指导，我先按照你的指引做一下试验。

**Comment by sangshuduo** [comment]
@RainWong 现在还有问题吗？
