### ISSUE TITLE
stables tag Questions

### ISSUE THREAD

**Issue by chenaiyuan** [taosdata/TDengine#11531]
insert的时候可以修改tag吗 tag只能通过alter修改吗

**Comment by gccgdb1234** [comment]
不能
insert into tb1 using meters TAGS ("beijing", "1")
insert into tb1 using meters TAGS("beijing", "1")
第二条insert插入成功，因为tb1已经存在，后面的using和TAGS会被忽略，所以不能用insert修改Tag

**Comment by chenaiyuan** [comment]
只有这一种方式取修改子表的tag是吧

**Comment by gccgdb1234** [comment]
只有一种方式修改tag

alter tableName set tag tagName=tagValue;
