### ISSUE TITLE
jdbc Questions

### ISSUE THREAD

**Issue by chenaiyuan** [taosdata/TDengine#11535]
JNI ERROR (2354): Ref is not there

**Comment by huolibo** [comment]
maybe the taosd is not working

**Comment by chenaiyuan** [comment]
在安装的那台服务器运行taos 是没有问题的

**Comment by huolibo** [comment]
java程序和taosd没在用一台机器上运行？是不是FQDN没有配置正确？

**Comment by chenaiyuan** [comment]
taosd在lunix上  java程序在window上   window客户端我已经安装了    我自己电脑上虚拟机安装的taosd使用java程序就可以访问。安装在服务器上的taos就报上面的错。

**Comment by huolibo** [comment]
你windows上的 hosts 应该加上服务器安装的FQDN。具体可以参考：https://www.taosdata.com/blog/2020/09/11/1824.html
