### ISSUE TITLE
sql question about orderby

### ISSUE THREAD

**Issue by chenaiyuan** [taosdata/TDengine#11547]
有这样一个需求。以meters表为例：
计算每个groupid下的最新总电流值，并且按倒叙排序：
1.获取每一个电表的最新值和groupid 
select groupid,last(current) from meters group by tbname。
2.以步骤1的结果做子查询,获取每个groupid的总电流值
select groupid,sum(current) from (
select groupid,last(current) from meters group by tbname
) group by groupid;

但是发现没有方法进行排序操作了，有什么解决方法

**Comment by gccgdb1234** [comment]
这个功能目前可能还不支持，  @hjxilinx 麻烦确认一下 是否支持用 select sum(current) as sum order by sum来排序

**Comment by hjxilinx** [comment]
对，暂时还不行。

**Comment by gccgdb1234** [comment]
这个功能目前不在支持计划中。
