### ISSUE TITLE
jdbc question

### ISSUE THREAD

**Issue by chenaiyuan** [taosdata/TDengine#11566]
![image](https://user-images.githubusercontent.com/48537400/163671223-6b21f54f-81c7-41d0-a9d6-2fdc43590646.png)

TDengine版本 2.4.0.12
jdbc-driver   2.0.37
show databases 可以执行成功
select count(*) from meters; 却报数据库连接失败
这是我的url:
String jdbcUrl = "jdbc:TAOS://" + host + ":6030/znn_test?debugFlag=135&asyncLog=0";
Connection connection = DriverManager.getConnection(jdbcUrl, "root", "taosdata");

**Comment by chenaiyuan** [comment]
![image](https://user-images.githubusercontent.com/48537400/163671405-5a70c3ce-6fed-4412-954c-dac637db5cff.png)

**Comment by chenaiyuan** [comment]
刚才测了一下  删库、新建库、新建超级表都是可以的。insert  select不行

**Comment by chenaiyuan** [comment]
使用的代码就是这个2.4.0.12这个安装包里面的JDBCDemo这个工程

**Comment by sangshuduo** [comment]
检查一下 6030-6042 TCP 和 UDP 是不是没开全

**Comment by chenaiyuan** [comment]
我的防火墙是关闭的

**Comment by huolibo** [comment]
给下 /var/log/taos/* 中的日志吧，便于定位问题。

**Comment by sangshuduo** [comment]
https://www.taosdata.com/docs/cn/v2.0/faq

遇到错误“Unable to establish connection”, 我怎么办？

客户端遇到连接故障，请按照下面的步骤进行检查：

    检查网络环境
        云服务器：检查云服务器的安全组是否打开 TCP/UDP 端口 6030-6042 的访问权限
        本地虚拟机：检查网络能否 ping 通，尽量避免使用localhost 作为 hostname
        公司服务器：如果为 NAT 网络环境，请务必检查服务器能否将消息返回值客户端

    确保客户端与服务端版本号是完全一致的，开源社区版和企业版也不能混用

    在服务器，执行 systemctl status taosd 检查taosd运行状态。如果没有运行，启动taosd

    确认客户端连接时指定了正确的服务器 FQDN (Fully Qualified Domain Name —— 可在服务器上执行 Linux 命令 hostname -f 获得），FQDN 配置参考：[一篇文章说清楚 TDengine 的 FQDN](https://www.taosdata.com/blog/2020/09/11/1824.html)。

    ping 服务器 FQDN，如果没有反应，请检查你的网络，DNS 设置，或客户端所在计算机的系统 hosts 文件。如果部署的是 TDengine 集群，客户端需要能 ping 通所有集群节点的 FQDN。

    检查防火墙设置（Ubuntu 使用 ufw status，CentOS 使用 firewall-cmd --list-port），确认 TCP/UDP 端口 6030-6042 是打开的

    对于 Linux 上的 JDBC（ODBC, Python, Go 等接口类似）连接, 确保libtaos.so在目录/usr/local/taos/driver里, 并且/usr/local/taos/driver在系统库函数搜索路径LD_LIBRARY_PATH里

    对于 Windows 上的 JDBC, ODBC, Python, Go等连接，确保C:\TDengine\driver\taos.dll在你的系统库函数搜索目录里 (建议taos.dll放在目录 C:\Windows\System32)

    如果仍不能排除连接故障

        Linux 系统请使用命令行工具 nc 来分别判断指定端口的 TCP 和 UDP 连接是否通畅 检查 UDP 端口连接是否工作：nc -vuz {hostIP} {port} 检查服务器侧 TCP 端口连接是否工作：nc -l {port} 检查客户端侧 TCP 端口连接是否工作：nc {hostIP} {port}

        Windows 系统请使用 PowerShell 命令 Net-TestConnection -ComputerName {fqdn} -Port {port} 检测服务段端口是否访问

    也可以使用 taos 程序内嵌的网络连通检测功能，来验证服务器和客户端之间指定的端口连接是否通畅（包括 TCP 和 UDP）：[TDengine 内嵌网络检测工具使用指南](https://www.taosdata.com/blog/2020/09/08/1816.html)。

6. 遇到错误“Unexpected generic error in RPC”或者“Unable to resolve FQDN”，我怎么办？

产生这个错误，是由于客户端或数据节点无法解析 FQDN（Fully Qualified Domain Name）导致。对于 TAOS Shell 或客户端应用，请做如下检查：

    请检查连接的服务器的 FQDN 是否正确，FQDN 配置参考：[一篇文章说清楚 TDengine 的 FQDN](https://www.taosdata.com/blog/2020/09/11/1824.html)
    如果网络配置有 DNS server，请检查是否正常工作
    如果网络没有配置 DNS server，请检查客户端所在机器的 hosts 文件，查看该 FQDN 是否配置，并是否有正确的 IP 地址
    如果网络配置 OK，从客户端所在机器，你需要能 ping 该连接的 FQDN，否则客户端是无法连接服务器的
    如果服务器曾经使用过 TDengine，且更改过 hostname，建议检查 data 目录的 dnodeEps.json 是否符合当前配置的 EP，路径默认为 /var/lib/taos/dnode。正常情况下，建议更换新的数据目录或者备份后删除以前的数据目录，这样可以避免该问题。
    检查 /etc/hosts 和 `/etc/hostname 是否是预配置的 FQDN
