### ISSUE TITLE
jdbc Questions

### ISSUE THREAD

**Issue by chenaiyuan** [taosdata/TDengine#11574]
使用TSDBPreparedStatement 做插入多张子表的时候：
参数只能是list吗
pstmt.setTimestamp(0, tsList);
如果我当前情况是子表很多，但是每个子表只有一条记录。我都需要new一个list存放数值吗？

`private static void bindFloat(Connection conn) throws SQLException {
        String sql = "insert into ? using stable2 tags(?,?) values(?,?,?)";

        TSDBPreparedStatement pstmt = conn.prepareStatement(sql).unwrap(TSDBPreparedStatement.class);

        for (int i = 1; i <= numOfSubTable; i++) {
            // set table name
            pstmt.setTableName("t2_" + i);
            // set tags
            pstmt.setTagFloat(0, random.nextFloat());
            pstmt.setTagDouble(1, random.nextDouble());
            // set columns
            ArrayList<Long> tsList = new ArrayList<>();
            long current = System.currentTimeMillis();
            for (int j = 0; j < numOfRow; j++)
                tsList.add(current + j);
            pstmt.setTimestamp(0, tsList);

            ArrayList<Float> f1List = new ArrayList<>();
            for (int j = 0; j < numOfRow; j++)
                f1List.add(random.nextFloat());
            pstmt.setFloat(1, f1List);

            ArrayList<Double> f2List = new ArrayList<>();
            for (int j = 0; j < numOfRow; j++)
                f2List.add(random.nextDouble());
            pstmt.setDouble(2, f2List);

            // add column
            pstmt.columnDataAddBatch();
        }
        // execute
        pstmt.columnDataExecuteBatch();
        // close if no try-with-catch statement is used
        pstmt.close();
    }`

**Comment by huolibo** [comment]
TSDBPreparedStatement目的是对数据表中有大量数据进行操作时，同一批次可以传输大量的数据，避免i/o耗时。
如果是多张子表且每张数据量较小建议直接使用sql进行插入，可以直接拼接多个语句。详见：[insert SQL](https://www.taosdata.com/docs/cn/v2.0/taos-sql#insert)
