### ISSUE TITLE
install question

### ISSUE THREAD

**Issue by chenaiyuan** [taosdata/TDengine#11582]
![image](https://user-images.githubusercontent.com/48537400/163746518-7dcb69e1-c356-4666-adfe-e5372120618d.png)
![image](https://user-images.githubusercontent.com/48537400/163746666-272c75e4-c923-405d-981b-eec636ae51bf.png)

**Comment by chenaiyuan** [comment]
install的时候：
This is an officially unverified linux system,
 if there are any problems with the installation and operation, 
 please feel free to contact taosdata.com for support.
taosd 服务不支持 chkconfig
taosd 服务不支持 chkconfig

然后启动不起来：
[root@iZbp1b8tsfbyhbe9r48zlaZ bin]# taosd
taosd: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by taosd)
taosd: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/lib/libtaos.so.1)

**Comment by sangshuduo** [comment]
看起来是系统太老了，目前只支持 CentOS 7 和 Ubuntu 1804 以上的系统
