### ISSUE TITLE
关于官方的测试报告，有没有实际做过测试验证的

### ISSUE THREAD

**Issue by withgakki** [taosdata/TDengine#116]

**Comment by hjxilinx** [comment]
The performance comparison report, as well as the involved data generator, source code, based on latest version of TDengine and other databases will be released soon.

**Comment by malinco** [comment]
@withgakki 在服务器上测过车联网博客的数据，写入性能下降35%，查询性能反而比官网的测试结果好很多。注：服务器 48核，512G内存。

**Comment by withgakki** [comment]
@malinco  额，官网不是在单核16G 的情况下么。。。你的最大写入性能大概多少

**Comment by guanshengliang** [comment]
您可以参考
https://www.taosdata.com/blog/2019/07/19/tdengine与influxdb对比测试/

TDengine每秒能处理的请求数很大，但是写入速度除和并发请求数有关外，还和硬盘写入速度有关

如果采集数据值比较规律，TDengine可以压缩的很好，那么落盘数据量会小，写入速度非常快，如果完全随机随机数据，那么写入速度会有所下降。
