### ISSUE TITLE
When the query is combined with FILL and group by, the data is not from the same device

### ISSUE THREAD

**Issue by DarkGodOne** [taosdata/TDengine#11601]
执行sql：select last(ts),last(temphome) from heatingbuild where buildingid like '110113013006001-09-01%' and ts > "2022-04-11 15:00:00" and ts < "2022-04-11 16:00:00" interval(10m) group by buildingid >> aa.csv;
得到的结果：
![image](https://user-images.githubusercontent.com/12151282/163792392-38c450ec-7a1f-4b2f-9b14-4656dc43b637.png)

执行sql：select last(ts),last(temphome) from heatingbuild where buildingid like '110113013006001-09-01%' and ts > "2022-04-11 15:00:00" and ts < "2022-04-11 16:00:00" interval(10m) fill(prev) group by buildingid >> bb.csv;
得到的结果：
![image](https://user-images.githubusercontent.com/12151282/163792606-63056e58-0799-4105-8aca-8a2218dbcfa7.png)

填充的数值并不是同一个设备的数据，这样是不合理的，应该使用同一个设备的数据填充吧
使用的版本2.4.0.5

**Comment by fenghuazzm** [comment]
之前问过这个逻辑，查询的如果是超级表，那插值就按照整个超级表的数据集进行插值的呢。
如果想填充来自同一设备的数据集，可以对子表进行查询、插值。

**Comment by fenghuazzm** [comment]
这个需求我记一下，你看理解的对不对：FILL 和 groupby 组合查询超级表，希望插值的数据集按照 groupby 区分。

**Comment by DarkGodOne** [comment]
对的，如果不是按照groupby区分，填写的不是一个设备的数据，肯定有问题

**Comment by enix223** [comment]
any update?
