### ISSUE TITLE
ALTER TABLE tb_name SET TAG tag_name=new_tag_value;

### ISSUE THREAD

**Issue by chenaiyuan** [taosdata/TDengine#11635]
现在可以在一个语句中对多个tag修改吗

**Comment by gccgdb1234** [comment]
不能，一次只能修改一个tag

**Comment by chenaiyuan** [comment]
那电表的档案变动了那岂不是要执行多条alter语句，如果有多个tag的话

**Comment by gccgdb1234** [comment]
是这样子，如果多个tag值要修改的话，要分开执行
没有支持一次修改多个tag是考虑到修改元数据本身是稀疏操作，不会产生多大负载，所以简化了行为。

**Comment by gccgdb1234** [comment]
一次修改多个tag值的功能目前不在支持计划中。
