### ISSUE TITLE
I need help with the use of TDengine

### ISSUE THREAD

**Issue by weilisikaili** [taosdata/TDengine#1163]
我在TDengine创建表,除了主键其他全为double类型;
然后我使用taos的python语言connect包的execute方法执行以下语句
insert into test values ('2019-12-18 00:00:00', 0.000000, 0.000000, 0.000000, 50.029999, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 1.307367, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 225.081985, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 10.200000, 10.100000, 0.021940, 224.994232, 0.065820, 1579368000000.000000, 224.862579, 1.000000, 1.000000, 0.000000, 0.001600, 1.000000, 0.131640, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000)
始终报错invalid SQL: syntax error near ")" (invalid data or symbol)
我已确认符号都是英文符号,

**Comment by weilisikaili** [comment]
刚刚试了一下,指定列插入数据可以,但是不指定始终会报错

**Comment by plum-lihui** [comment]
我们按照你的表格式验证一下。有可能我们复现不了，你能把配置文件的调试开关打开（debugflag    135），然后把调试日志文件发送给过来，我们分析一下吗？
多谢！

**Comment by plum-lihui** [comment]
我在最新的版本上验证了一下，是可以成功的。这是我的测试代码。请参考。如果还有问题，请随时联系。

"""
This is the sample code for TDengine python2 client.
"""
import taos
import sys
import datetime
import random

def exitProgram(conn):
    conn.close()
    sys.exit()

if __name__ == '__main__':
    start_time = datetime.datetime(2020, 1, 21)
    time_interval = datetime.timedelta(seconds=60)

    # Connect to TDengine server.
    # 
    # parameters:
    # @host     : TDengine server IP address 
    # @user     : Username used to connect to TDengine server
    # @password : Password 
    # @database : Database to use when connecting to TDengine server
    # @config   : Configuration directory
    conn = taos.connect(host="0.0.0.0", user="root", password="taosdata", config="/etc/taos")
    
    print(conn)

    # Generate a cursor object to run SQL commands
    c1 = conn.cursor()
    
    print(c1)

    # Create a database named db
    try:
        c1.execute('create database dbd')
    except Exception as err:
        conn.close()
        raise(err)
    
    print("create database ok!")    
    # use database
    try:
        c1.execute('use dbd')
    except Exception as err:
        conn.close()
        raise(err)


    # create table
    try:
        c1.execute('create table if not exists dt (ts timestamp,    c1 double,     c2 double,     c3 double,    c4 double,    c5 double,    c6 double,    c7 double,    c8 double,    c9 double,    c10 double,    c11 double,    c12 double,    c13 double,    c14 double,    c15 double,    c16 double,    c17 double,    c18 double,    c19 double,    c20 double,    c21 double,    c22 double,    c23 double,    c24 double,    c25 double,    c26 double,    c27 double,    c28 double,    c29 double,    c30 double,    c31 double,    c32 double,    c33 double,    c34 double,    c35 double,    c36 double,    c37 double,    c38 double,    c39 double,    c40 double,    c41 double,    c42 double,    c43 double,    c44 double,    c45 double,    c46 double,    c47 double,    c48 double,    c49 double,    c50 double,    c51 double,    c52 double,    c53 double,    c54 double,    c55 double,    c56 double,    c57 double,    c58 double,    c59 double,    c60 double,    c61 double,    c62 double)')
    except Exception as err:
        conn.close()
        raise(err)

    print("create table ok!") 
    # insert data 
    try:
       #c1.execute("insert into dt values ('%s', %d, %f, '%s')" % (start_time, random.randint(1,10), random.randint(1,10)/10.0, 'hello'))
       c1.execute("insert into dt values ('2019-12-18 00:00:00', 0.000000, 0.000000, 0.000000, 50.029999, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 1.307367, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 225.081985, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 10.200000, 10.100000, 0.021940, 224.994232, 0.065820, 1579368000000.000000, 224.862579, 1.000000, 1.000000, 0.000000, 0.001600, 1.000000, 0.131640, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000)")
    except Exception as err:
        conn.close()
        raise(err)
        
    print("insert data ok!") 
    # query data and return data in the form of list
    try:
        c1.execute('select * from dbd.dt')
    except Exception as err:
        conn.close()
        raise(err)

    # Column names are in c1.description list
    cols = c1.description
    # Use fetchall to fetch data in a list
    data = c1.fetchall()

    try:
        c1.execute('select * from dbd.dt')
    except Exception as err:
        conn.close()
        raise(err)

    # Use iterator to go through the retreived data
    for col in c1:
        print(col)

    conn.close()

**Comment by Aironchu** [comment]
Hello,我正在尝试使用3.0版本.
在使用函数DIFF()查询时遇到了错误提示：
  DB error: Invalid parameter data type : diff (0.000364s)

我尝试之后发现diff()内的字段如果是BIG_INT UNSIGNED时会有这个错误提示，而DIFF()的字段如果是DOUBLE或者TIMESTAMP，则一切正常。
请告诉我 BIG_INT UNSIGNED  是否不能用于DIFF函数？

**Comment by sangshuduo** [comment]
> Hello,我正在尝试使用3.0版本. 在使用函数DIFF()查询时遇到了错误提示： DB error: Invalid parameter data type : diff (0.000364s)
> 
> 我尝试之后发现diff()内的字段如果是BIG\_INT UNSIGNED时会有这个错误提示，而DIFF()的字段如果是DOUBLE或者TIMESTAMP，则一切正常。 请告诉我 BIG\_INT UNSIGNED 是否不能用于DIFF函数？

谢谢，我们会在近期支持这个功能
