### ISSUE TITLE
simple query timeout

### ISSUE THREAD

**Issue by amy-habor** [taosdata/TDengine#11653]
一个简单的查询
select * from stable where ts < time limit a, b
有时候几十毫秒就可以查出来
但是查几次就会出现一次需要20秒才能查出来的情况
20秒这种是什么问题呢，每次超时都是20秒

**Comment by gccgdb1234** [comment]
我本地没有复现出来，尝试了几十次都是几十毫秒的级别。
麻烦分享一下具体的配置，比如超级表内有多少张子表，每张子表有多少数据量，limit a,b的具体值，等等
如果是用taosBenchmark插入的数据，请分享一下相应的json配置文件 。

**Comment by amy-habor** [comment]
> 

15张子表，有两张子表是10-20w数据，剩下的都是不到1k
limit 0, 20
数据是通过测试服务一条一条插入的

**Comment by gccgdb1234** [comment]
我有15张子表，每张表20万条记录
重复了约30次，每次都稳定在3ms左右完成。

**Comment by amy-habor** [comment]
> 
我使用GUI工具查看数据，跟子表的数据量无关，有的时候就是秒刷新，有时候也是20秒

**Comment by gccgdb1234** [comment]
这和你环境中的网络延迟有关吧？

**Comment by amy-habor** [comment]
> 

我连接的是本地服务器虚拟机里安装的taos，直接在这台虚拟机上执行查询语句，也是会出现偶尔20秒的情况

**Comment by amy-habor** [comment]
`taos> select count(1) from vibration_temperature;
       count(1)        |
========================
                665369 |
Query OK, 1 row(s) in set (20.011687s)

taos> select count(1) from vibration_temperature;
       count(1)        |
========================
                665373 |
Query OK, 1 row(s) in set (0.001231s)

taos> select count(1) from vibration_temperature;
       count(1)        |
========================
                665373 |
Query OK, 1 row(s) in set (0.001238s)`
就是这样，同样的查询，过段时间就有一次需要20秒来查询，20秒时间是固定的，但是我找不到什么20秒的配置

**Comment by amy-habor** [comment]
找到问题了，是fqdn解析时间20秒
我把hostname配置到hosts里，就不会出现查询20秒的情况了

**Comment by gccgdb1234** [comment]
great
