### ISSUE TITLE
Can I access TDengine directly using IP ？

### ISSUE THREAD

**Issue by ypyaaa** [taosdata/TDengine#11666]
tdengine 能不能用IP直接访问 而非配置FQDN

**Comment by plum-lihui** [comment]
直接在taos.cfg中将fqdn配置成ip地址也是可访问的。

**Comment by plum-lihui** [comment]
`root@trd04 /etc/taos $ taos -h 192.168.0.203

Welcome to the TDengine shell from Linux, Client Version:2.4.0.0
Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.
taos> show dnodes;   
id   |           end_point        | vnodes | cores  |   status   | role  |       create_time       |      offline reason    | ========================================================================      
 1  | 192.168.0.203:6030     |      0     |     24   | ready     | any   | 2022-04-21 09:20:47.853 |                          |      
  2 | 192.168.0.204:6030     |      1     |     24   | ready     | any   | 2022-04-21 09:29:19.652 |                          |
Query OK, 2 row(s) in set (0.002829s)
taos> 
`

**Comment by ypyaaa** [comment]
> `root@trd04 /etc/taos $ taos -h 192.168.0.203
> 
> Welcome to the TDengine shell from Linux, Client Version:2.4.0.0 Copyright (c) 2020 by TAOS Data, Inc. All rights reserved. taos> show dnodes; id | end_point | vnodes | cores | status | role | create_time | offline reason | ======================================================================== 1 | 192.168.0.203:6030 | 0 | 24 | ready | any | 2022-04-21 09:20:47.853 | | 2 | 192.168.0.204:6030 | 1 | 24 | ready | any | 2022-04-21 09:29:19.652 | | Query OK, 2 row(s) in set (0.002829s) taos> `

ok 可以了 谢谢

**Comment by ypyaaa** [comment]
close
