### ISSUE TITLE
time func is not working

### ISSUE THREAD

**Issue by chenaiyuan** [taosdata/TDengine#11698]
![image](https://user-images.githubusercontent.com/48537400/164355887-05e92d0d-4ae8-4d25-910d-f717c7ee79c5.png)

**Comment by chenaiyuan** [comment]
serve版本 2.4.0.12

**Comment by gccgdb1234** [comment]
无法复现
是不是误用了全角的（），确认一下用半角()

**Comment by chenaiyuan** [comment]
确实是英文的括号阿

**Comment by gccgdb1234** [comment]
2.4.0.14可以复现，可能是bug，我联系相应人员确认一下。

**Comment by gccgdb1234** [comment]
now()这个函数在2.4.0.x版本中目前还不支持。在最新的develop分支上支持。你可以自己从develop分支编译新版本。

**Comment by chenaiyuan** [comment]
2.4.0.x  是不是时间函数都不支持阿

**Comment by gccgdb1234** [comment]
是的

**Comment by chenaiyuan** [comment]
![image](https://user-images.githubusercontent.com/48537400/164357615-3ed3ebf5-093c-4fe9-b656-b3c8adc4ea55.png)
我一开始还以为你们这个文档写错了呢   我没有看见2.6的安装包阿  怎么就从 2.6.0.0 版本开始了呢

**Comment by chenaiyuan** [comment]
2.6这个版本上生产环境不太适合吧

**Comment by gccgdb1234** [comment]
还没有正式发布，文档提前了。
