### ISSUE TITLE
The performance of batch insert of multiple tables is not as expected

### ISSUE THREAD

**Issue by life-not-ifelse** [taosdata/TDengine#11734]
2000个设备，设计了2000张表，每秒生成一条数据，按照一下语法
INSERT INTO d1001 VALUES ('2021-07-13 14:06:34.630', 10.2, 219, 0.32) 
                      d1002 VALUES ('2021-07-13 14:06:34.255', 10.27, 0.31）
拼装sql，
用springboot+mybatis测试   同时插入2000张表  每张表1条数据  需要30秒
部署tdengine的机器配置如下：64核 内存376G
请问这是为什么   

2000张表 每个表2个字段  一个时间  一个100长度的字符串

我试着改为400张表  前10来次插入还是很快的   在后面大概每次插入就需要十几秒的时间

**Comment by life-not-ifelse** [comment]
我在下午的测试当中  他的插入速度变的正常（2000张表同时插入1条数据【拼装成一个sql语句】不会出现需要30秒这么长的时间）了起来   目前原因不太清楚   正在查看测试代码的逻辑是否有错

**Comment by life-not-ifelse** [comment]
果然有问题，现在的逻辑变成了2000个设备，每个设备20个指标，每个设备的每一个指标一张表，我在插入的时候通过using这个关键字如果表不存在的话创建表，这就导致刚开始这40000张表没有创建好，插入效率极低，在持续测试过程中，这40000张表渐渐的都创建好了，插入效率也就上来了

**Comment by life-not-ifelse** [comment]
果然有问题，现在的逻辑变成了2000个设备，每个设备20个指标，每个设备的每一个指标一张表，我在插入的时候通过using这个关键字如果表不存在的话创建表，这就导致刚开始这40000张表没有创建好，插入效率极低，在持续测试过程中，这40000张表渐渐的都创建好了，插入效率也就上来了

**Comment by gccgdb1234** [comment]
在自动建表阶段的性能是不可能与纯插入数据相比的。以上行为是正常现象。建表是一次性操作，影响的时间段比较短。

**Comment by life-not-ifelse** [comment]
谢谢解答
