### ISSUE TITLE
alter stable add columns?

### ISSUE THREAD

**Issue by wangyongalfred** [taosdata/TDengine#11746]
for now,only one column can be add to stable for one time.
but sometimes, there could be multi columns to be added.
i hope the sql could support multi columns.

is there any plan for it ?

i use version 2.2.1.1 
^^

**Comment by gccgdb1234** [comment]
We are planning to support this functionality: add/change multiple columns or tags in single command. But the priority is not pretty high, possibly in 3.x version.
