### ISSUE TITLE
suggest to add spot update item of taosdata 

### ISSUE THREAD

**Issue by sexbee** [taosdata/TDengine#1174]
试用了一段时间，感觉如果taosdata能增加点修改功能，结合字典数据库，将更大有可为，可能某些场景下完全排除mongo。点修改指时间戳不动情况下，对单条数据可进行修改保存非常必要，不知道实现起来是否困难。

**Comment by sexbee** [comment]
或能增加config里开关，按需启用或关闭点修改功能。

**Comment by hjxilinx** [comment]
谢谢您的建议，我们已经有这方面的考虑，但是具体时间还未确定。
