### ISSUE TITLE
Error reported when writing influx row protocol data using schemaless with a field of the same name in a property with different case

### ISSUE THREAD

**Issue by liujianming04** [taosdata/TDengine#11758]
**Bug Description**
使用schemaless写入influx行协议数据，属性中存在同名字段（大小写不一样），会报错

**To Reproduce**
接口地址：http://xxxx:6041/influxdb/v1/write?db=db_61e753468ecb3800497311bd&u=root&p=taosdata&precision=ms
请求主体（数据）：
type_61e753468ecb3800497311bd_19gqMPJ3Os1,__ct_name__=ct_type_19gqMPJ3Oso_19gBnvupzB6,__deviceId__=19gBnvupzB6 **La$f=257.65**,Timestamp$f=1650607683.76,__assetId__=L"nx_devzy001_inst02",__calculate_time__=1650607683880i,__cloud_time__=1650607683781i,__create_time__=1650607683762i,__metricsType__=0i,__write_time__=1650610367037i,bool_test$b=true,duration$i=10i,int_test$i=-46i,**la$f=78.0**,lb$f=78.0,lc$f=29.0,number_test$f=-46.0,string_test$s=L"Hello你好！",times_int_val$i=1650607683762i,workstatus$i=1i 1650607683762

**Expected Behavior**
自动建表时对于字段，需要区分大小写，对于La和la，应该认为不同的字段。

**Screenshots**
![image](https://user-images.githubusercontent.com/64473697/164651889-0c17c174-0ad1-408b-90c4-cb4ad3d80651.png)

**Environment (please complete the following information):**
 - TDengine Version ：2.4.0.16

**Comment by fenghuazzm** [comment]
在表、字段的命名规则中，也是不区分大小写的

**Comment by liujianming04** [comment]
![image](https://user-images.githubusercontent.com/64473697/164952495-abd65c9e-1294-4d7e-ba87-99443a256645.png)


我看表示区分大小写的，不加反引号就会找不到表。

**Comment by liujianming04** [comment]
![image](https://user-images.githubusercontent.com/64473697/165231025-3dd5b8ef-40d2-4eac-820b-5848ebd99a1b.png)

taos> CREATE STABLE IF NOT EXISTS power.meters1 (ts timestamp, `La` int) TAGS (deviceId binary(64));
Query OK, 0 of 0 row(s) in database (0.002952s)

taos> CREATE STABLE IF NOT EXISTS power.meters2 (ts timestamp, La int) TAGS (deviceId binary(64));
Query OK, 0 of 0 row(s) in database (0.002309s)

taos> CREATE STABLE IF NOT EXISTS power.meters3 (ts timestamp, la int) TAGS (deviceId binary(64));
Query OK, 0 of 0 row(s) in database (0.002241s)

taos> desc power.meters1;
                       Field                        |         Type         |   Length    |   Note   |
=====================================================================================================
 ts                                                 | TIMESTAMP            |           8 |          |
 La                                                 | INT                  |           4 |          |
 deviceid                                           | BINARY               |          64 | TAG      |
Query OK, 3 row(s) in set (0.000608s)

taos> desc power.meters2;
                       Field                        |         Type         |   Length    |   Note   |
=====================================================================================================
 ts                                                 | TIMESTAMP            |           8 |          |
 la                                                 | INT                  |           4 |          |
 deviceid                                           | BINARY               |          64 | TAG      |
Query OK, 3 row(s) in set (0.000428s)

taos> desc power.meters3;
                       Field                        |         Type         |   Length    |   Note   |
=====================================================================================================
 ts                                                 | TIMESTAMP            |           8 |          |
 la                                                 | INT                  |           4 |          |
 deviceid                                           | BINARY               |          64 | TAG      |
Query OK, 3 row(s) in set (0.000427s)

taos>

**Comment by gccgdb1234** [comment]
字段名在内部 统一转为了小写。
所以不能同时存在 La, la, lA，LA 的字段，它们在内部都会被转换为 小写的 “la”

**Comment by liujianming04** [comment]
但是desc显示表结构的时候，却是La，只是显示的问题吗？如果建表使用La，desc也是La。在数据插入时，字段写成la会报错，说la列不存在。
![image](https://user-images.githubusercontent.com/64473697/165233210-effd9cb2-ec18-4ec6-895a-5cd92c5efdaa.png)

**Comment by liujianming04** [comment]
> 字段名在内部 统一转为了小写。 所以不能同时存在 La, la, lA，LA 的字段，它们在内部都会被转换为 小写的 “la”

如果说都转了小写，那么desc显示应该也是小写la，就是说无论建表的时候有没有加反引号，都会是小写的la，在insert的时候无论加不加反引号，都是认为小写的la，能写入成功。但是实际情况是，加了反引号就是大写，不加才是转小写，建表是La，insert指定是la，报字段不存在，那不就是小写的la不存在吗？只存在大写的La，要不然怎么会报错？

感觉有点矛盾，或者我理解的还不够透彻

**Comment by gccgdb1234** [comment]
使用转义符是保留大小写的。
如果不使用转义符则统一转为了小写。
