### ISSUE TITLE
Inside the container, direct IP connection to TDengine is intermittent

### ISSUE THREAD

**Issue by ypyaaa** [taosdata/TDengine#11750]
![bfd8e458e5466af57d3f85775a567e8](https://user-images.githubusercontent.com/19565638/164627896-43e62562-2ed4-4bfa-9ae2-502ed40da2ad.jpg)
在容器内部 客户端连接tdengineserver端时断时续
![57bed3b06d357a3be5f6e35289548a3](https://user-images.githubusercontent.com/19565638/164628031-577499a8-ece8-4114-8323-df685ca9955a.png)
服务端报连接正常 客户端却显示失败

**Comment by ypyaaa** [comment]
。。。没人会吗？

**Comment by yu285** [comment]
没有数据库版本信息，代码信息，驱动版本信息，无法定位
