### ISSUE TITLE
mybatis + druid + taos ，multiple data source switching ，this operation is NOT supported currently

### ISSUE THREAD

**Issue by ZookeeperLine** [taosdata/TDengine#11756]
mybatis + druid + taos 多数据源切换，然后切换 至  taos 上，新增数据提示 ：this operation is NOT supported currently

**Comment by huaweihomelq** [comment]
用最新版本的taos java 驱动，还是有这个错误

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

**Comment by niquxx** [comment]
我也有同样的问题；我使用的是
        ````xml
        <dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>3.0.0</version>
        </dependency>
        ````

**Comment by niquxx** [comment]
我也有同样的问题，我使用的都是3.x的版本，maven配置的也是3.0.0
```<dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>3.0.0</version>
        </dependency>
 ```

**Comment by niquxx** [comment]
贴错了，重新贴一下
> ```
        <dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>3.0.0</version>
        </dependency>
