### ISSUE TITLE
I want to try TDengine edge computing, but TDengine failed to start, the error is that the disk is too small

### ISSUE THREAD

**Issue by ruixiwu** [taosdata/TDengine#11776]
我的ARM盒子总共500M空间， 所说tsengine支持边缘计算， 结果启动时遇到如下问题：

04/23 11:23:14.537519 00000582 DND step:dnode-cfg is initialized
04/23 11:23:14.538325 00000582 DND dnode eps is initialized
04/23 11:23:14.538937 00000582 DND step:dnode-eps is initialized
04/23 11:23:14.539717 00000582 DND dnode minfos is initialized
04/23 11:23:14.540205 00000582 DND step:dnode-minfos is initialized
04/23 11:23:14.540970 00000582 WAL wal module is initialized, rsetId:3
04/23 11:23:14.541919 00000582 DND step:dnode-wal is initialized
04/23 11:23:14.543181 00000582 DND step:dnode-sync is initialized
04/23 11:23:14.544217 00000582 DND ERROR free disk size: 0.240799 GB, too little, quit
04/23 11:23:14.545224 00000582 DND ERROR failed to check item:disk
# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root                 3.5G    588.7M      2.7G  17% /
devtmpfs                222.1M         0    222.1M   0% /dev
tmpfs                   246.6M         0    246.6M   0% /dev/shm
tmpfs                   246.6M         0    246.6M   0% /tmp
tmpfs                   246.6M         0    246.6M   0% /run
# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root                 3.5G    588.8M      2.7G  17% /
devtmpfs                222.1M         0    222.1M   0% /dev
tmpfs                   246.6M         0    246.6M   0% /dev/shm
tmpfs                   246.6M         0    246.6M   0% /tmp
tmpfs                   246.6M         0    246.6M   0% /run

_Originally posted by @ruixiwu in https://github.com/taosdata/TDengine/issues/5301#issuecomment-1107454229_

**Comment by ruixiwu** [comment]
# pwd
/usr/local/tdengine2.4/taos/bin
# ./taosd -v
04/23 11:38:11.171510 00000594 DND start to initialize TDengine
04/23 11:38:11.179636 00000594 DND step:dnode-tfile is initialized
04/23 11:38:11.180927 00000594 DND step:dnode-rpc is initialized
04/23 11:38:11.183799 00000594 UTL localEp is: buildroot:6030
04/23 11:38:11.186582 00000594 UTL ERROR open file:/proc/594/io failed
04/23 11:38:11.189376 00000594 UTL WARN timezone not configured, set to system default: (UTC, +0000)
04/23 11:38:11.190714 00000594 UTL WARN locale not configured, set to system default:C
04/23 11:38:11.191983 00000594 UTL WARN can't get locale and charset from system, set it to UTF-8
04/23 11:38:11.193801 00000594 UTL    check global cfg completed
04/23 11:38:11.194953 00000594 UTL ==================================
04/23 11:38:11.195874 00000594 UTL    taos config & system info:
04/23 11:38:11.196635 00000594 UTL ==================================

**Comment by ruixiwu** [comment]
我的环境是 armv7l   buildroot版本， 一个小盒子， 用于边缘网关的

**Comment by ruixiwu** [comment]
04/23 11:38:15.855516 00000600 DND start to initialize TDengine
04/23 11:38:15.857657 00000600 DND step:dnode-tfile is initialized
04/23 11:38:15.859872 00000600 DND step:dnode-rpc is initialized
04/23 11:38:15.862706 00000600 UTL localEp is: buildroot:6030
04/23 11:38:15.865798 00000600 UTL ERROR open file:/proc/600/io failed
04/23 11:38:15.867155 00000600 UTL WARN timezone not configured, set to system default: (UTC, +0000)
04/23 11:38:15.868111 00000600 UTL WARN locale not configured, set to system default:C
04/23 11:38:15.869307 00000600 UTL WARN can't get locale and charset from system, set it to UTF-8
04/23 11:38:15.870660 00000600 UTL    check global cfg completed
04/23 11:38:15.871574 00000600 UTL ==================================
04/23 11:38:15.872317 00000600 UTL    taos config & system info:
04/23 11:38:15.872983 00000600 UTL ==================================
04/23 11:38:15.873570 00000600 UTL  firstEp:                buildroot:6030
04/23 11:38:15.874290 00000600 UTL  secondEp:               buildroot:6030
04/23 11:38:15.874915 00000600 UTL  fqdn:                   buildroot
04/23 11:38:15.875655 00000600 UTL  serverPort:             6030
04/23 11:38:15.876078 00000600 UTL  configDir:              /etc/taos
04/23 11:38:15.876541 00000600 UTL  logDir:                 /var/log/taos
04/23 11:38:15.876665 00000600 UTL  scriptDir:              /etc/taos
04/23 11:38:15.876761 00000600 UTL  arbitrator:
04/23 11:38:15.877156 00000600 UTL  numOfThreadsPerCore:    1.000000
04/23 11:38:15.877629 00000600 UTL  numOfCommitThreads:     4
04/23 11:38:15.877760 00000600 UTL  ratioOfQueryCores:      1.000000
04/23 11:38:15.878145 00000600 UTL  maxNumOfDistinctRes:    10000000
04/23 11:38:15.878263 00000600 UTL  numOfMnodes:            1
04/23 11:38:15.878357 00000600 UTL  vnodeBak:               1
04/23 11:38:15.878987 00000600 UTL  telemetryReporting:     1
04/23 11:38:15.879128 00000600 UTL  dnodeNopLoop:           0
04/23 11:38:15.879568 00000600 UTL  tcpConnTimeout:         1000(ms)
04/23 11:38:15.879684 00000600 UTL  syncCheckInterval:      1500(ms)
04/23 11:38:15.879873 00000600 UTL  balance:                0
04/23 11:38:15.880289 00000600 UTL  balanceInterval:        300
04/23 11:38:15.880513 00000600 UTL  offlineInterval:        3
04/23 11:38:15.880999 00000600 UTL  keepTimeOffset:         0
04/23 11:38:15.881394 00000600 UTL  role:                   0
04/23 11:38:15.881508 00000600 UTL  maxTmrCtrl:             512
04/23 11:38:15.881859 00000600 UTL  monitorInterval:        30(s)
04/23 11:38:15.881977 00000600 UTL  monitorReplica:         1
04/23 11:38:15.882073 00000600 UTL  offlineThreshold:       864000(s)
04/23 11:38:15.882523 00000600 UTL  rpcTimer:               300(ms)
04/23 11:38:15.882636 00000600 UTL  rpcMaxTime:             600(s)
04/23 11:38:15.882727 00000600 UTL  rpcForceTcp:            0
04/23 11:38:15.883074 00000600 UTL  statusInterval:         1(s)
04/23 11:38:15.883194 00000600 UTL  shellActivityTimer:     3(s)
04/23 11:38:15.883284 00000600 UTL  minSlidingTime:         10(ms)
04/23 11:38:15.883705 00000600 UTL  minIntervalTime:        1(ms)
04/23 11:38:15.883817 00000600 UTL  maxStreamCompDelay:     20000(ms)
04/23 11:38:15.883907 00000600 UTL  maxFirstStreamCompDelay:10000(ms)
04/23 11:38:15.883997 00000600 UTL  retryStreamCompDelay:   10000(ms)
04/23 11:38:15.884395 00000600 UTL  streamCompDelayRatio:   0.100000
04/23 11:38:15.884538 00000600 UTL  maxVgroupsPerDb:        0
04/23 11:38:15.885017 00000600 UTL  maxTablesPerVnode:      1000000
04/23 11:38:15.885132 00000600 UTL  minTablesPerVnode:      1000
04/23 11:38:15.885224 00000600 UTL  tableIncStepPerVnode:   1000
04/23 11:38:15.885503 00000600 UTL  cache:                  16(Mb)
04/23 11:38:15.886028 00000600 UTL  blocks:                 6
04/23 11:38:15.886243 00000600 UTL  days:                   10
04/23 11:38:15.886343 00000600 UTL  keep:                   3650
04/23 11:38:15.886432 00000600 UTL  minRows:                100
04/23 11:38:15.886840 00000600 UTL  maxRows:                4096
04/23 11:38:15.887012 00000600 UTL  precision:              0
04/23 11:38:15.887481 00000600 UTL  comp:                   2
04/23 11:38:15.887602 00000600 UTL  walLevel:               1
04/23 11:38:15.887694 00000600 UTL  fsync:                  3000
04/23 11:38:15.887780 00000600 UTL  replica:                1
04/23 11:38:15.888177 00000600 UTL  partitions:             4
04/23 11:38:15.888288 00000600 UTL  quorum:                 1
04/23 11:38:15.888379 00000600 UTL  update:                 0
04/23 11:38:15.889192 00000600 UTL  cachelast:              0
04/23 11:38:15.889345 00000600 UTL  compressMsgSize:        524288
04/23 11:38:15.889835 00000600 UTL  compressColData:        -1
04/23 11:38:15.889959 00000600 UTL  maxSQLLength:           1048576(byte)
04/23 11:38:15.890170 00000600 UTL  maxWildCardsLength:     100(byte)
04/23 11:38:15.890528 00000600 UTL  maxRegexStringLen:      128(byte)
04/23 11:38:15.891057 00000600 UTL  maxNumOfOrderedRes:     1000000
04/23 11:38:15.891275 00000600 UTL  queryBufferSize:        -1(byte)
04/23 11:38:15.891381 00000600 UTL  retrieveBlockingModel:  0
04/23 11:38:15.891475 00000600 UTL  keepColumnName:         1
04/23 11:38:15.891878 00000600 UTL  timezone:                (UTC, +0000)
04/23 11:38:15.891994 00000600 UTL  locale:                 C
04/23 11:38:15.892085 00000600 UTL  charset:                UTF-8
04/23 11:38:15.892490 00000600 UTL  maxShellConns:          50000
04/23 11:38:15.892706 00000600 UTL  maxConnections:         5000
04/23 11:38:15.892809 00000600 UTL  minimalLogDirGB:        1.000000(GB)
04/23 11:38:15.893217 00000600 UTL  minimalTmpDirGB:        1.000000(GB)
04/23 11:38:15.893340 00000600 UTL  minimalDataDirGB:       2.000000(GB)
04/23 11:38:15.893708 00000600 UTL  mnodeEqualVnodeNum:     4
04/23 11:38:15.893903 00000600 UTL  flowctrl:               1
04/23 11:38:15.894282 00000600 UTL  slaveQuery:             1
04/23 11:38:15.894399 00000600 UTL  adjustMaster:           1
04/23 11:38:15.894756 00000600 UTL  http:                   1
04/23 11:38:15.894866 00000600 UTL  mqtt:                   0
04/23 11:38:15.895288 00000600 UTL  monitor:                1
04/23 11:38:15.895769 00000600 UTL  stream:                 1
04/23 11:38:15.895973 00000600 UTL  topicBinaryLen:         16000
04/23 11:38:15.896344 00000600 UTL  httpEnableRecordSql:    0
04/23 11:38:15.896459 00000600 UTL  telegrafUseFieldNum:    0
04/23 11:38:15.896814 00000600 UTL  httpMaxThreads:         2
04/23 11:38:15.897020 00000600 UTL  restfulRowLimit:        10240
04/23 11:38:15.897397 00000600 UTL  httpDbNameMandatory:    0
04/23 11:38:15.897510 00000600 UTL  httpKeepAlive:          30000
04/23 11:38:15.897864 00000600 UTL  numOfLogLines:          10000000
04/23 11:38:15.898071 00000600 UTL  logKeepDays:            0
04/23 11:38:15.898438 00000600 UTL  asyncLog:               1
04/23 11:38:15.898549 00000600 UTL  debugFlag:              0
04/23 11:38:15.898912 00000600 UTL  mDebugFlag:             131
04/23 11:38:15.899023 00000600 UTL  dDebugFlag:             135
04/23 11:38:15.899560 00000600 UTL  sDebugFlag:             135
04/23 11:38:15.899680 00000600 UTL  wDebugFlag:             135
04/23 11:38:15.899772 00000600 UTL  sdbDebugFlag:           131
04/23 11:38:15.899860 00000600 UTL  rpcDebugFlag:           131
04/23 11:38:15.900267 00000600 UTL  tmrDebugFlag:           131
04/23 11:38:15.900466 00000600 UTL  cDebugFlag:             131
04/23 11:38:15.900952 00000600 UTL  jniDebugFlag:           131
04/23 11:38:15.901076 00000600 UTL  odbcDebugFlag:          131
04/23 11:38:15.901845 00000600 UTL  uDebugFlag:             131
04/23 11:38:15.901975 00000600 UTL  httpDebugFlag:          131
04/23 11:38:15.902162 00000600 UTL  mqttDebugFlag:          131
04/23 11:38:15.902259 00000600 UTL  monDebugFlag:           131
04/23 11:38:15.902346 00000600 UTL  qDebugFlag:             131
04/23 11:38:15.902429 00000600 UTL  vDebugFlag:             135
04/23 11:38:15.902851 00000600 UTL  tsdbDebugFlag:          131
04/23 11:38:15.902963 00000600 UTL  cqDebugFlag:            131
04/23 11:38:15.903104 00000600 UTL  enableRecordSql:        0
04/23 11:38:15.903503 00000600 UTL  enableCoreFile:         0
04/23 11:38:15.903611 00000600 UTL  gitinfo:                f0ee1875ad200ab3280cdb4f94d4b70ab51135dc
04/23 11:38:15.904053 00000600 UTL  gitinfoOfInternal:      NULL
04/23 11:38:15.904168 00000600 UTL  buildinfo:              Built at 2022-04-09 09:45
04/23 11:38:15.904281 00000600 UTL  version:                2.4.0.16
04/23 11:38:15.904446 00000600 UTL  maxBinaryDisplayWidth:  30
04/23 11:38:15.904883 00000600 UTL  tempDir:                /tmp/
04/23 11:38:15.905338 00000600 UTL  tsdbMetaCompactRatio:   0
04/23 11:38:15.905841 00000600 UTL  deadLockKillQuery:      1
04/23 11:38:15.906054 00000600 UTL  clientMerge:            0
04/23 11:38:15.906439 00000600 UTL  defaultJSONStrType:     nchar
04/23 11:38:15.906554 00000600 UTL  smlChildTableName:
04/23 11:38:15.906918 00000600 UTL  smlTagNullName:         _tag_null
04/23 11:38:15.907120 00000600 UTL  walFlushSize:           1024(Mb)
04/23 11:38:15.907487 00000600 UTL  lossyColumns:
04/23 11:38:15.907598 00000600 UTL  fPrecision:             0.000000
04/23 11:38:15.907985 00000600 UTL  dPrecision:             0.000000
04/23 11:38:15.908439 00000600 UTL  maxRange:               500
04/23 11:38:15.908558 00000600 UTL  range:                  100
04/23 11:38:15.909007 00000600 UTL  os pageSize:            4096(KB)
04/23 11:38:15.909233 00000600 UTL  os openMax:             1024
04/23 11:38:15.909482 00000600 UTL  os streamMax:           16
04/23 11:38:15.910007 00000600 UTL  os numOfCores:          1
04/23 11:38:15.910210 00000600 UTL  os totalMemory:         493(MB)
04/23 11:38:15.910714 00000600 UTL  os sysname:             Linux
04/23 11:38:15.910878 00000600 UTL  os nodename:            buildroot
04/23 11:38:15.910979 00000600 UTL  os release:             4.19.94-gbe5389fd85
04/23 11:38:15.911366 00000600 UTL  os version:             #89 PREEMPT Mon Sep 6 19:27:53 CST 2021
04/23 11:38:15.911582 00000600 UTL  os machine:             armv7l
04/23 11:38:15.911697 00000600 UTL  dataDir: /var/lib/taos
04/23 11:38:15.912101 00000600 UTL ==================================
04/23 11:38:15.912218 00000600 DND step:dnode-globalcfg is initialized
04/23 11:38:15.913064 00000600 TFS disk /var/lib/taos is mounted to tier level 0 id 0
04/23 11:38:15.914548 00000600 UTL ==================================
04/23 11:38:15.915607 00000600 UTL  os totalDisk:           3.488838(GB)
04/23 11:38:15.916319 00000600 UTL  os usedDisk:            0.574978(GB)
04/23 11:38:15.917045 00000600 UTL  os availDisk:           2.733459(GB)
04/23 11:38:15.917693 00000600 UTL ==================================
04/23 11:38:15.918127 00000600 DND dnode storage is initialized at /var/lib/taos/dnode
04/23 11:38:15.918254 00000600 DND step:dnode-storage is initialized
04/23 11:38:15.919377 00000600 DND dnode cfg is initialized
04/23 11:38:15.919838 00000600 DND step:dnode-cfg is initialized
04/23 11:38:15.920712 00000600 DND dnode eps is initialized
04/23 11:38:15.921194 00000600 DND step:dnode-eps is initialized
04/23 11:38:15.921863 00000600 DND dnode minfos is initialized
04/23 11:38:15.922302 00000600 DND step:dnode-minfos is initialized
04/23 11:38:15.923330 00000600 WAL wal module is initialized, rsetId:3
04/23 11:38:15.924185 00000600 DND step:dnode-wal is initialized
04/23 11:38:15.925895 00000600 DND step:dnode-sync is initialized
04/23 11:38:15.926817 00000600 DND ERROR free disk size: 0.240799 GB, too little, quit
04/23 11:38:15.927831 00000600 DND ERROR failed to check item:disk

**Comment by gccgdb1234** [comment]
需要至少 2G 磁盘空间。

**Comment by nasservb** [comment]
we have the same problem with version 3.0.1.4
```bash
tdengin DND ERROR free disk size: 0.970612 GB, too little, require 1.000000 GB at least at least, quit tdengin -
```

**Comment by Byrontoo** [comment]
we have the same problem with version 3.0.1.4 too.
