### ISSUE TITLE
Change the alter tag value sql syntax

### ISSUE THREAD

**Issue by hjxilinx** [taosdata/TDengine#118]
Change the sql syntax:
ALTER TABLE table_name TAG tag_col=tag_val

to:
ALTER TABLE table_name SET TAG tag_col=tag_val

**Comment by JulianZhao** [comment]
Does it support WHERE clause? like:
```
ALTER TABLE table_name SET TAG tag_col=tag_val WHERE tag_col=old_tag_val
```
