### ISSUE TITLE
Why limit the length of NCHAR and BINARY

### ISSUE THREAD

**Issue by rxl19990103** [taosdata/TDengine#11806]
我想存储一些长文本，但是NCHAR 和BINARY支持的长度太小，有什么办法放开吗

**Comment by hjxilinx** [comment]
你需要存储的数据长度大概是多少？

**Comment by zmayu** [comment]
Welcome to the TDengine shell from Linux, Client Version:2.4.0.26
taos> ALTER TABLE `st_service_record` MODIFY COLUMN request nchar(4095);

DB error: invalid operation: invalid binary/nchar column length (0.000765s)
