### ISSUE TITLE
What will happend when decrease the database variables "replica"?

### ISSUE THREAD

**Issue by Chenxwi** [taosdata/TDengine#11823]
Version-2.4.0.16

When I change replica from 1 to 2, The disk usage to double.

But the disk usage not change when decrease the replica from 2 to 1 .

Will disk auto release?

**Comment by fenghuazzm** [comment]
The data files will not be deleted automatically after the database replica parameters are changed  from 2 to 1 .

**Comment by Chenxwi** [comment]
> 

thanks
