### ISSUE TITLE
Assertion `qualifiedCol' failed

### ISSUE THREAD

**Issue by sanliang125** [taosdata/TDengine#1188]
**Bug 描述**
在执行一段查询sql时，也许是我的sql语句或语法有问题，执行sql的时候直接退出了当前查询连接。
报错信息如下：
*taos> select last(ts),intensity, sc_name  scName, sc_id as scId, sc_loc as scLoc,    unit,   remark,  status  from arc_intensity  where sc_id='001'   and status=0;*
*taos: /root/workspace/tdengine/TDengine/src/client/src/tscSQLParser.c:5252: doUpdateSqlFunctionForColPrj: Assertion `qualifiedCol' failed.*
*Aborted*
状态：
      直接退出了当前客户端连接。

**截图**
![image](https://user-images.githubusercontent.com/29949952/73803047-895a1600-47fa-11ea-92b2-827eb8e0e984.png)

**环境信息**
 - OS: CentOS 7.0
 - TDengine Version [1.6.4.4]

**构建过程**
1.创建超级表
     *create table arc_intensity(ts timestamp, intensity int)  tags(sc_name binary(30),sc_id binary(30),sc_loc binary(100),unit binary(10),remark binary(100),extend1 binary(100),extend2 binary(100));*
2.创建子表
     *create table  arc_intensity_01 using arc_intensity tags("1号","001","左","lux","","","",0);*
3.随便在子表中插入数据
4.执行查询
   查询最后一条数据，同时查询tags
    *select last(ts),intensity, sc_name  scName, sc_id as scId, sc_loc as scLoc,    unit,   remark,  status  from arc_intensity  where sc_id='001'   and status=0;*
**预期结果**
即使是我的语法错误或者执行失败，都不应该断开当前客户端的连接，这个问题有时候很致命。

**Comment by plum-lihui** [comment]
你好！我们来复现一下问题，请能帮忙将建表语句给一下吧。多谢！

**Comment by sanliang125** [comment]
> 你好！我们来复现一下问题，请能帮忙将建表语句给一下吧。多谢！

已经更新构建语句。

**Comment by plum-lihui** [comment]
你使用的哪个版本？我再最新的develop分支上验证了一下，不会挂了，只会提示语句错误。测试过程如下：
taos> use db;
Database changed.

taos> create table arc_intensity(ts timestamp, intensity int) tags(sc_name binary(30),sc_id binary(30),sc_loc binary(100),unit binary(10),remark binary(100),extend1 binary(100),extend2 binary(100));
Query OK, 1 row(s) affected (0.000562s)

taos> create table arc_intensity_01 using arc_intensity tags("1号","001","左","lux","","","");
Query OK, 1 row(s) affected (0.000648s)

taos> select last(ts),intensity, sc_name scName, sc_id as scId, sc_loc as scLoc, unit, remark, status from arc_intensity where sc_id='001' and status=0;

DB error: invalid SQL: invalid column name
taos>

**Comment by plum-lihui** [comment]
请下载最新代码再测试吧。如果还有问题，请随时通知我们。多谢！

**Comment by sanliang125** [comment]
> 你使用的哪个版本？我再最新的develop分支上验证了一下，不会挂了，只会提示语句错误。测试过程如下：
> taos> use db;
> Database changed.
> 
> taos> create table arc_intensity(ts timestamp, intensity int) tags(sc_name binary(30),sc_id binary(30),sc_loc binary(100),unit binary(10),remark binary(100),extend1 binary(100),extend2 binary(100));
> Query OK, 1 row(s) affected (0.000562s)
> 
> taos> create table arc_intensity_01 using arc_intensity tags("1号","001","左","lux","","","");
> Query OK, 1 row(s) affected (0.000648s)
> 
> taos> select last(ts),intensity, sc_name scName, sc_id as scId, sc_loc as scLoc, unit, remark, status from arc_intensity where sc_id='001' and status=0;
> 
> DB error: invalid SQL: invalid column name
> taos>

1.6.4.4
