### ISSUE TITLE
官方文档中数据存储原理的疑问

### ISSUE THREAD

**Issue by zhangchi0923** [taosdata/TDengine#119]
head文件的中的表1，表2是同一台智能电表的数据按时间维度分表吗？也就是说vnode0下的两个文件组是同一个智能电表对应的表按照时间范围的分片，这样理解对吗？
![文件组](https://user-images.githubusercontent.com/27287620/61525143-69275d00-aa4a-11e9-94d2-661820e17634.png)

![head文件结构](https://user-images.githubusercontent.com/27287620/61524987-29f90c00-aa4a-11e9-802d-849ccdcf4be2.png)

**Comment by hjxilinx** [comment]
对，按照时间段进行的切片。如果不修改数据库建库默认参数，1804存储的10天的数据，1805存储的是1804之后的10天的数据。并不一定是一个表，是从属于这个虚拟节点的所有表的数据。

**Comment by zhangchi0923** [comment]
> 对，按照时间段进行的切片。如果不修改数据库建库默认参数，1804存储的10天的数据，1805存储的是1804之后的10天的数据。并不一定是一个表，是从属于这个虚拟节点的所有表的数据。

对不起，想了好久没能明白您的意思。你说：对，却又说并不一定是一个表，那表1、表2到底是不是来自同一个设备的表按照时间的分表呢？还是说vnode中维护了许多设备的表，表1、表2是属于不同设备？

**Comment by hjxilinx** [comment]
抱歉。准确地说是：1个vnode文件中存储了归属于该vnode的全部表的数据。
对于设备而言，我们建议建模的时候每个设备一张表。

**Comment by zhangchi0923** [comment]
> 抱歉。准确地说是：1个vnode文件中存储了归属于该vnode的全部表的数据。
> 对于设备而言，我们建议建模的时候每个设备一张表。

好的，现在已经明白了
