### ISSUE TITLE
ALTER TABLE tb_name SET TAG tag_name=new_tag_value;

### ISSUE THREAD

**Issue by chenaiyuan** [taosdata/TDengine#11905]
这个语句执行效率怎么样，我这测试的不是很快    600个alter语句2、3秒。

**Comment by fenghuazzm** [comment]
咱这边是什么场景，有频繁的改标签值的需求吗

**Comment by chenaiyuan** [comment]
有个定时任务，一天一更新档案，就是测了一下alter的效率。实际上不会很多

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
