### ISSUE TITLE
How do I make a CDH available TDengine Parcel package ?

### ISSUE THREAD

**Issue by Anme47854** [taosdata/TDengine#11917]
甲方需求在CDH上部署Tdengine，并展示了他们成功的案例，但在网络上的资料少之又少，https://blog.csdn.net/weixin_40670099/article/details/111874424 这篇文章里的parcel包结构该放什么呢？

**Comment by ljluestc** [comment]
创建parcel包目录结构：包含你的服务组件和一个meta目录。
在meta目录中创建parcel.json文件：该文件记录了你的服务信息，如版本、所属用户、适用的CDH平台版本等。
在meta目录中创建dsmaster_env.sh文件（根据你的服务需求）：声明你的服务运行时所需的一些变量环境。
打包parcel包：执行打包命令将文件打成parcel包，并生成.sha哈希校验文件。
制作csd jar：创建csd目录，其中包含服务的规则描述文件service.sdl、图标文件和启停脚本等。
打包csd jar：执行打包命令将csd目录打成csd jar包。
分发激活parcel包：将parcel包和csd jar包拷贝到CDH的相应目录，然后在Cloudera Manager界面上分发和激活parcel包。
添加服务：在Cloudera Manager界面上添加你的服务，并根据需要配置相应的参数。
等待执行成功：等待服务添加和部署成功。
