### ISSUE TITLE
Error when using Schemaless to write row protocol data with \n , influxdb can write \n

### ISSUE THREAD

**Issue by liujianming04** [taosdata/TDengine#11916]
**Bug Description**
数据：weather2,altitude=1001,area=南 La1="\n",la=-5,Aa=3,aa=44

influx写入：
![image](https://user-images.githubusercontent.com/64473697/165426360-2abc7352-4f1e-4ea1-a1fe-8cf030ea6111.png)

结果
![image](https://user-images.githubusercontent.com/64473697/165426397-fec8e8d1-28d8-4d94-8e94-52a338a8415c.png)

tdengine写入报错
![image](https://user-images.githubusercontent.com/64473697/165426742-8a324941-5705-40e4-bfda-c96fa9d8c6af.png)

将\n转义成\\n是可以的

**Expected Behavior**
对标influx，不需要对\n做转义，也能写入

版本：2.4.0.16

**Comment by fenghuazzm** [comment]
influxdb 这样写入确实没问题，上周已做同步，我们会及时跟进。

**Comment by fenghuazzm** [comment]
已在 2.4.0.26、2.6.0.4 版本上做了修复
