### ISSUE TITLE
NULL pointer dereference in the file tscUtil.c

### ISSUE THREAD

**Issue by starbugreport** [taosdata/TDengine#1195]
In the file tscUtil.c, a NULL pointer dereference may occur in the function
tscGetMetricMetaCacheKey(SSqlCmd* pCmd, char* str, uint64_t uid).

In this function, there is a for loop which uses the expression
"pMeterMetaInfo->numOfTags" in the loop condition.

The pointer pMeterMetaInfo may be NULL when it was initialized:
SMeterMetaInfo* pMeterMetaInfo = tscGetMeterMetaInfoByUid(pCmd, uid, &index);

The reason is that the function
tscGetMeterMetaInfoByUid() may return NULL.
Because, when (pCmd->numOfTables == 0),
tscGetMeterMetaInfo() returns NULL.

**Comment by hjxilinx** [comment]
Yes, this case may happen if pCmd->numOfTables equals 0, the numOfTables equals 0 only when handling the heart beat ```pSql``` object. 

Please ref to https://github.com/taosdata/TDengine/blob/develop/src/client/src/tscServer.c , line: 769.
```    assert((pQueryInfo->numOfTables == 0 && pQueryInfo->command == TSDB_SQL_HB) || pQueryInfo->numOfTables > 0);```

In all other cases, the caller of  ```tscGetMeterMetaInfoFromQueryInfo``` makes sure that this function  ```tscGetMeterMetaInfoFromQueryInfo``` will always return a not ```NULL``` value.
