### ISSUE TITLE
failed to execute batch bind,reason:Need to reconfigure table

### ISSUE THREAD

**Issue by chenaiyuan** [taosdata/TDengine#11966]
多加了两个字段然后报这个错了

**Comment by fenghuazzm** [comment]
TDengine 是什么版本呢？

**Comment by chenaiyuan** [comment]
2.4.0.12

**Comment by theflash1264** [comment]
解决了吗 我的也是这个问题

**Comment by BrianSpace** [comment]
如果有修改字段之前创建的子表，我尝试的结果是删除老的表可以解决这个问题。

**Comment by theflash1264** [comment]
> 如果有修改字段之前创建的子表，我尝试的结果是删除老的表可以解决这个问题。

不能删表

**Comment by fenghuazzm** [comment]
如果是参数绑定的方式导致的，可参考： https://github.com/taosdata/TDengine/issues/14496
