### ISSUE TITLE
DB error: App error

### ISSUE THREAD

**Issue by sanliang125** [taosdata/TDengine#1197]
**Bug 描述**
使用连续查询功能，有创建成功的信息，但是进行查询该表时，出现以上错误。

**Bug 截图**
![image](https://user-images.githubusercontent.com/29949952/74086450-d6214380-4abd-11ea-9cad-511e27c02e95.png)
**问题 重现**
1.准备创建一个连续查询，语法如下:
*create table abcd as select first(ts),first(voltage),first(tbname) from load_voltage interval(2s) sliding(1s);*
    我想从一个表中查询出这个连续查询周期中的第一条数据的内容，与这条数据所在的表名。
2. 执行上面语句信息反馈如下：
*02/08 21:52:07.840666 7f3aeb7fe700 ERROR UTL Illegal data type 0 or data type length 367
Query OK, 1 row(s) affected (0.000841s)*
3.然后我查询了一下该表
 *select \* from abcd;*
4.查询结果如下：
  DB ERROR:app error;

**环境信息:**
 - OS: [e.g. CentOS 7.0]
 - TDengine Version [e.g. 1.6.4.4 ]

**Comment by plum-lihui** [comment]
你好！请将load_voltage 表的创建语句给一下吧。我们来复现、定位问题。
多谢！

**Comment by plum-lihui** [comment]
创建的连续查询语句有问题，不能有 first(tbname) 。你去掉后，再试试，应该没有问题了。
我们增强一下对这个语句的检测。

**Comment by sanliang125** [comment]
> 创建的连续查询语句有问题，不能有 first(tbname) 。你去掉后，再试试，应该没有问题了。
> 我们增强一下对这个语句的检测。

是的，我知道我这个语句可能有问题，只是觉得输出信息有点不太理解。
