### ISSUE TITLE
TDengine connectors support c#

### ISSUE THREAD

**Issue by geffzhang** [taosdata/TDengine#12]
Microsoft releases Open source cross-platform .net core https://github.com/dotnet, Upcoming Release 3.0. As a popular language, c# has an advantage in cloud-native application development, Is there someone started to implement the c# connectors?

**Comment by caizhiyuan** [comment]
求.net core api

**Comment by lishewen** [comment]
来支持张队、支持.net core

**Comment by FeynmanLoo** [comment]
来支持张队、支持.net core

**Comment by lantianning** [comment]
来支持张队、支持.net core

**Comment by leegkon** [comment]
.net core跟物联网绝配，必须要支持啊

**Comment by jyizheng** [comment]
我有兴趣研究一下

**Comment by tmoonlight** [comment]
同求

**Comment by conan198581** [comment]
支持张队，支持.net core

**Comment by ILAOHE** [comment]
期待.net core api

**Comment by linrb** [comment]
支持张队，支持.net core

**Comment by myFirstway** [comment]
期待.net core connectors

**Comment by xiexingen** [comment]
期待.net core支持

**Comment by jasonwang1109** [comment]
期待

**Comment by geffzhang** [comment]
Entity, Framework, EF, Core, Data, O/RM, entity-framework-core,TDengine https://github.com/maikebing/Maikebing.EntityFrameworkCore.Taos

**Comment by guanshengliang** [comment]
我们会在7月27日提交windows客户端代码，但是nuget包还需要再等等

**Comment by guanshengliang** [comment]
关于C#的问题，请到 #51 继续提问
TDengine团队在研发计划中增加`dapper`框架的支持
