### ISSUE TITLE
failed to execute batch bind,reason: Unable to establish connection

### ISSUE THREAD

**Issue by chenaiyuan** [taosdata/TDengine#12009]
程序启动执行一段时间没有什么问题  
出现两次这样的问题：程序分别执行了4个小时 、10个小时
然后就报这个错了 
我执行了 show connections  
看连接数据也不是很多 才30多个

**Comment by gccgdb1234** [comment]
常见原因是服务端负载过重。

**Comment by chenaiyuan** [comment]
怎么看服务端的负载情况
