### ISSUE TITLE
insert data, display error

### ISSUE THREAD

**Issue by tianyuningmou** [taosdata/TDengine#12010]
## **Bug Description**

**Environment (please complete the following information):**
 - OS: `ubuntu20`
 - TDengine Version: 2.4

#### stable schema: 
      create stable road_network_hour (
          ts timestamp,
          lossPctStatistics_max float,
          lossPctStatistics_min float,
          lossPctStatistics_avg float,
          rttMsStatistics_max float,
          rttMsStatistics_min float,
          rttMsStatistics_avg float,
          totalNum int,
          successNum int,
          grid nchar(1024)
      ) tags (
          hourStarttime float,
          hostName nchar(128),
          host tinyint,
          city smallint,
          roadInfo nchar(128),
          point_longitude float,
          point_latitude float
      );

#### insert_sql:
```
insert into road_network_hour_pacifica_cn_51_1 using road_network_hour  
tags (1650423600000, 'pacifica-cn-51', 1, 2, 'rs_w999960_rs_w184923#1',  2496004.1580127412, 799203.7771546503) 
values ( 1651030472998, 0, 0, 0, 0.127188, 0.070923, 0.10193647222222221, 36, 36, '{"gridX": "24960050", "gridY": "7992267", "gridLengthMeter": 10, "gridFactor": 1, "gridPoint": [{"latitude": 799226.7, "longitude": 2496005}, {"latitude": 799226.7, "longitude": 2496005.1}, {"latitude": 799226.8, "longitude": 2496005.1}, {"latitude": 799226.8, "longitude": 2496005}], "centralPoint":
 {"latitude": 799226.75, "longitude": 2496005.05}, "roadPoint": {"roadId": "rs_w999960_rs_w184923", "pointIndex": 1, "point": {"latitude": 799203.7771546503, "longitude": 2496004.1580127412}, "hdmapUid": "MASTER_cn_shenzhen_55447"}}'
);
```

#### display:
2022-04-27 11:34:32.998 |               0.00000 |               0.00000 |               0.00000 |              0.12719 |              0.07092 |              0.10194 |          36 |          36 | {"gridX": "24960050", "grid... |  1650243534848.00000 | pacifica-cn-51                 |    1 |      2 | **rs_w144383_rs_w144397#2        |        2495131.25000 |         803206.**

#### but when I create a new stable, execute the insert_sql, data is ok.

**Comment by fenghuazzm** [comment]
I executed it according to your SQL and did not reproduce the problem
