### ISSUE TITLE
Is WAL log performance bottleneck in general cases?

### ISSUE THREAD

**Issue by tigerhu2008** [taosdata/TDengine#12078]
**General Questions**
According to the design, if WAL log is used, the data is always written to the log file firstly, then in general cases, is it the bottleneck for write performance? Thanks.

**Comment by tigerhu2008** [comment]
@tomchon would you please shed some light?  Or will it become a bottleneck in some cases?

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

**Comment by tomchon** [comment]
> @tomchon would you please shed some light? Or will it become a bottleneck in some cases?
WAL logging is not a bottleneck ，You can review section 3.2.5 of the reports-https://www.taosdata.com/performance-comparison-influxdb-and-timescaledb-vs-tdengine @tigerhu2008
