### ISSUE TITLE
Please support case when and arithmetic operator in TDengine SQL

### ISSUE THREAD

**Issue by xiangsf** [taosdata/TDengine#12095]
目前的sql语法，过于简陋，在实际的业务场景中，会很容易受到限制。
场景举例：
select 
        code
       ,sum(1) as cnt
       ,sum(case when side='buy' then 1 end) as buy_cnt 
       ,sum(value1 + value2) as value
 from trade_log
group by code

这个SQL语法非常常见，也非常实用。 目前缺乏这方面的支持，需要自行在程序中做预处理，应用程序的复杂度急剧提升

**Comment by hjxilinx** [comment]
请稍等。
我们在后续的版本中会提供 case when 的支持。

**Comment by 0x5487** [comment]
Does tdengine support `sum(value1 * value2)` in SQL at the moment?

**Comment by shymonk** [comment]
Does tdengine support case-when sql syntax for v3.0.0?
