### ISSUE TITLE
Can't show modified table schema in terminal after modifying by JDBC

### ISSUE THREAD

**Issue by easypickings** [taosdata/TDengine#12105]
**Bug Description**
I successfully executed an `ALTER (S)TABLE ...` SQL through JDBC. However, when query the table schema in a previously opened taos client in terminal, it didn't show the updated schema. Only after a logout and re-login the updated schema is shown.

**To Reproduce**
1. open a taos client in terminal `taos -u root -p taosdata -d test`
2. execute a SQL in JDBC, like `ALTER STABLE stb_test ADD COLUMN col INT;`
3. query table schema by `DESC stb_test;` or `SHOW CREATE STABLE stb_test;`
4. cannot see the column `col`
5. quit the client and re-open one
6. repeat 3. and now `col` appears

**Expected Behavior**
I think the column `col` should be seen immediately in step 4.

**Environment (please complete the following information):**
 - OS: CentOS Linux release 7.9.2009 (Core)
 - TDengine Version 2.4.0.7

**Comment by fenghuazzm** [comment]
Thanks for the feedback.
What is the JDBC connector version ?

**Comment by yu285** [comment]
I guess it's a JDBC-JNI connection, right?

**Comment by easypickings** [comment]
> 

Yep

**Comment by easypickings** [comment]
> I guess it's a JDBC-JNI connection, right?

Yep

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
