### ISSUE TITLE
The INTERVAL clause is not compatible between TDengine 2.2.2.0 and 2.4.0.18 .

### ISSUE THREAD

**Issue by kuunnss** [taosdata/TDengine#12109]
左图为2.4.0.18返回的首列时间字段
右图为2.2.2.0返回的首列时间字段
2.4.0.18这两个字段字段名因为一致，导致不好解析，能支持两个字段名称区分吗？
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/34533698/166856391-0ce46421-147b-4797-9b31-361b5e16889b.png">

**Comment by fenghuazzm** [comment]
结论：用户有对数据做过备份，已回退到原先版本。
