### ISSUE TITLE
v2407,last_row udf error when blank sub table exists

### ISSUE THREAD

**Issue by jamesdzhang** [taosdata/TDengine#12135]
with tdengine v2.4.0.7
whenever there is a blank sub table, the whole stable can not be applied with last_row udf. it will throw error : [ TDengine ERROR (704): sql: select last_row(*) from db.stable group by tag;, desc: Unexpected generic error in query]

Steps to reproduce:
1 create  a stable and create some sub tables with data
2 create a sub table fill with no data
3 run [select last_row(*) from db.stabe ] will get error.

If you drop the blank sub tables, the last_row udf will work as usal.

**Comment by fenghuazzm** [comment]
We did not reproduce this problem in the latest version of 2.4, you can upgrade and try again .

**Comment by jamesdzhang** [comment]
add on:
the blank sub tables is out of keep days.  you may reproduce it by making  some sub tables are sweep to blank.

**Comment by fenghuazzm** [comment]
I constructed such a stable and changed the keep value of the database after writing data, leaving one of the child tables empty：
![image](https://user-images.githubusercontent.com/70138133/167293047-6033870b-8706-4a04-a1ed-d9daa7f52472.png)
But no errors are thrown：
![image](https://user-images.githubusercontent.com/70138133/167293122-224c2bec-4d6f-41d2-85a4-9b4920a8f97b.png)

**Comment by fenghuazzm** [comment]
> add on: the cause of blank sub tables is that they are out of keep days. you may reproduce it by making some sub tables are sweep to blank.

Did you execute this function on a sub table that was already empty.

**Comment by jamesdzhang** [comment]
whats ur db config.
If ur case is okay with last_row. I guess its about db config.
Mine is : [CREATE DATABASE test REPLICA 2 QUORUM 1 DAYS 1 KEEP 30 CACHE 16 BLOCKS 8 MINROWS 100 MAXROWS 4096 WAL 2 FSYNC 30000 COMP 1 CACHELAST 2 PRECISION 'ms' UPDATE 0]
My stable contains binary colums;
u may try it one more time.

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
