### ISSUE TITLE
JDBC TSDBPreparedStatement bug

### ISSUE THREAD

**Issue by easypickings** [taosdata/TDengine#12130]
**Bug Description**
When using JDBC PreparedStatement::addBatch to add a SQL, the double quotes in SQL can be falsely omitted.
**To Reproduce**
1. create a stable `create stable stb (ts timestamp, col int) tags (nchar_tag nchar(8));`
2. create a table using PreparedStatement:
```java
String sql = "create table tb using stb (nchar_tag) tags ('\"abc\"')";
Connection conn = getConn();
PreparedStatement pstmt = conn.prepareStatement(sql);
pStmt.addBatch();
pStmt.executeBatch();
conn.close();
```
3. query `show create table tb` and get `CREATE TABLE tb USING stb TAGS ("abc")`

**Expected Behavior**
The tag should be `"abc"`. If executing the sql in terminal, the query gets `CREATE TABLE tb USING stb TAGS (""abc"")`.

**Environment (please complete the following information):**
- OS: CentOS Linux release 7.9.2009 (Core)
- TDengine Version 2.4.0.7
- JDBC version taos-jdbcdriver-2.0.37 with JNI connection

**Comment by huolibo** [comment]
嗯，经测试存在此问题，下个版本修复。
