### ISSUE TITLE
TDengine-client-2.4.0.18,  ln: /usr/include/taos.h: No such file or directory

### ISSUE THREAD

**Issue by yanni-coffee** [taosdata/TDengine#12139]
**Bug Description**

install go driver with err  

1、go.mod

```
github.com/taosdata/driver-go/v2 develop
```
2、go get ./...

```
 ../../../../go/pkg/mod/github.com/taosdata/driver-go/v2@v2.0.1-0.20220324063052-903e5bdd86e5/wrapper/asynccb.go:7:10: fatal error: 'taos.h' file not found

```

**Environment (please complete the following information):**
 - OS: [macOs 12.3.1 / Intel Core i9]

**Additional Context**
TDEngine has installed，Maybe I need to compile the client and install it?

**Comment by sangshuduo** [comment]
@yanni-coffee so far there is no TDengine official release for macOS. You need to compile it from the source code.

**Comment by yanni-coffee** [comment]
@sangshuduo   TDEngine has installed
```
mkdir debug  && cd debug && cmake .. && cmake --build . && sudo make install 
```

**Comment by sangshuduo** [comment]
> @sangshuduo TDEngine has installed
> 
> ```
> mkdir debug  && cd debug && cmake .. && cmake --build . && sudo make install 
> ```

the header file on macOS should be installed at /usr/local/include. go driver needs support that against the darwin system. Would you like to submit a PR in the driver-go repo?

**Comment by yanni-coffee** [comment]
好的

**Comment by yanni-coffee** [comment]
@sangshuduo  好的

**Comment by yanni-coffee** [comment]
我的问题解决了， go-driver 并不需要任何修改， 现在总结一下问题：

1、我自己在mac上以docker的方式启动 taosd， 现在官方 docker 的最新版是 [2.4.0.18](https://hub.docker.com/layers/tdengine/tdengine/tdengine/2.4.0.18/images/sha256-ef518df65b441de50b19d865bbade2c745d6020b4250a41924ae70b48b67e437?context=explore)

2、TDengine 在  develop 下的版本是2.4.0.0，  需要注意一致性
