### ISSUE TITLE
Use schemaless to write a json string to TDengine, which randomly escapes and does not escape for " .

### ISSUE THREAD

**Issue by liujianming04** [taosdata/TDengine#12159]
**Bug Description**
同样的造数工具，造了一批数据，都包含json字符串，但是发现部分json串里面的双引号是带反斜杠转义，部分是不带的，随机出现。

**To Reproduce**
两条数据：
"{\"jsonAttri\":{\"jsonC\":\"52\",\"jsonB\":{\"jsonB1\":\"B111\",\"jsonB2\":\"51\"},\"jsonA\":\"69\",\"jsonG\":\"56\",\"jsonF\":\"55\",\"jsonE\":\"54\",\"jsonD\":\"53\",\"jsonK\":\"2022-05-06 14:48:50\",\"jsonJ\":\"14:48:50\",\"jsonI\":\"2022-05-06\",\"jsonH\":\"0\",\"jsonL\":\"61\"},\"_deviceId\":\"19lCbn2RSwg\",\"binaryAttri\":\"01001101\",\"modelType\":\"device\",\"logicalInterfaceId\":\"19lsrOIHzY4\",\"metricsType\":0,\"strAttri\":\"String46\",\"tenantId\":\"625e242160287e0049dbd374\",\"calculate_time\":1651819730696,\"intAttri\":47,\"boolAttri\":true,\"assetId\":\"deviceallattri04191\",\"physicalInterfaceId\":\"19lsrOIHzY4\",\"deviceTypeId\":\"19lsrOIHzY4\",\"numAttri\":48.48,\"timestamp\":1651819730678,\"cloud_time_\":1651819730678}"

 

"{\"jsonAttri\":{\"jsonC\":\"53\",\"jsonB\":{\"jsonB1\":\"B111\",\"jsonB2\":\"52\"},\"jsonA\":\"107\",\"jsonG\":\"57\",\"jsonF\":\"56\",\"jsonE\":\"55\",\"jsonD\":\"54\",\"jsonK\":\"2022-05-06 14:49:00\",\"jsonJ\":\"14:49:00\",\"jsonI\":\"2022-05-06\",\"jsonH\":\"0\",\"jsonL\":\"62\"},\"_deviceId\":\"19lCbn2RSwg\",\"binaryAttri\":\"10000011\",\"modelType\":\"device\",\"logicalInterfaceId\":\"19lsrOIHzY4\",\"metricsType\":0,\"strAttri\":\"String47\",\"tenantId\":\"625e242160287e0049dbd374\",\"calculate_time\":1651819740905,\"intAttri\":48,\"boolAttri\":false,\"assetId\":\"deviceallattri04191\",\"physicalInterfaceId\":\"19lsrOIHzY4\",\"deviceTypeId\":\"19lsrOIHzY4\",\"numAttri\":49.49,\"timestamp\":1651819740805,\"cloud_time_\":1651819740805}"

利用schemaless写入tdengine的结果：
![image](https://user-images.githubusercontent.com/64473697/167098169-2611d42d-398c-4867-bc0a-81a65f03810e.png)

![image](https://user-images.githubusercontent.com/64473697/167098207-f3f1b614-150c-47f9-9d86-f6f1c96157c8.png)

**Expected Behavior**
统一格式，不带反斜杠转义

 - TDengine Version [2.4.0.16]

**Comment by liujianming04** [comment]
可能是业务逻辑导致的，我优先排查，不占用官方资源

**Comment by liujianming04** [comment]
排查发现：
同时插入9行是没问题的：
![image](https://user-images.githubusercontent.com/64473697/167248639-9e4054a6-8371-42e4-9166-43f0321718fb.png)


但是，一旦同时插入10行以上，就有问题
![image](https://user-images.githubusercontent.com/64473697/167248666-1e815b41-f131-445e-a2c0-b61a5a58f5b8.png)


我的场景是从kafka拉取json格式的工况，工况中包含子json，然后写入到tdengine。经测试，一次拉取9条以下写入tdengine没问题，但是拉取10条及以上就有问题。

**Comment by liujianming04** [comment]
用sql写10条数据，则正常：

sql:
insert into power.a1001 (ts, aa) values
('2022-03-01 09:07:33.016',  '{"country":"zhongguo","districtCode":440112,"city":"guangzhou","latitude":23.099513,"district":"tianhe","locationSource":"GPS","state":"yazhou","longitude":113.543128}') 
('2022-03-02 09:07:33.016',  '{"country":"zhongguo","districtCode":440112,"city":"guangzhou","latitude":23.099513,"district":"tianhe","locationSource":"GPS","state":"yazhou","longitude":113.543128}') 
('2022-03-03 09:07:33.016',  '{"country":"zhongguo","districtCode":440112,"city":"guangzhou","latitude":23.099513,"district":"tianhe","locationSource":"GPS","state":"yazhou","longitude":113.543128}') 
('2022-03-04 09:07:33.016',  '{"country":"zhongguo","districtCode":440112,"city":"guangzhou","latitude":23.099513,"district":"tianhe","locationSource":"GPS","state":"yazhou","longitude":113.543128}') 
('2022-03-05 09:07:33.016',  '{"country":"zhongguo","districtCode":440112,"city":"guangzhou","latitude":23.099513,"district":"tianhe","locationSource":"GPS","state":"yazhou","longitude":113.543128}') 
('2022-03-06 09:07:33.016',  '{"country":"zhongguo","districtCode":440112,"city":"guangzhou","latitude":23.099513,"district":"tianhe","locationSource":"GPS","state":"yazhou","longitude":113.543128}') 
('2022-03-07 09:07:33.016',  '{"country":"zhongguo","districtCode":440112,"city":"guangzhou","latitude":23.099513,"district":"tianhe","locationSource":"GPS","state":"yazhou","longitude":113.543128}') 
('2022-03-08 09:07:33.016',  '{"country":"zhongguo","districtCode":440112,"city":"guangzhou","latitude":23.099513,"district":"tianhe","locationSource":"GPS","state":"yazhou","longitude":113.543128}') 
('2022-03-09 09:07:33.016',  '{"country":"zhongguo","districtCode":440112,"city":"guangzhou","latitude":23.099513,"district":"tianhe","locationSource":"GPS","state":"yazhou","longitude":113.543128}') 
('2022-03-10 09:07:33.016',  '{"country":"zhongguo","districtCode":440112,"city":"guangzhou","latitude":23.099513,"district":"tianhe","locationSource":"GPS","state":"yazhou","longitude":113.543128}') ;

![image](https://user-images.githubusercontent.com/64473697/168023688-8cf49c63-67e0-4d35-9f38-8fc590b920e3.png)

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
