### ISSUE TITLE
stable exists  in 'show stables', but it does not exist when querying the stable

### ISSUE THREAD

**Issue by xiaozan-dev** [taosdata/TDengine#12173]
stable 'RPCContext' exists in 'show stables'; 
but 
"DB error: Table does not exist (0.000917s)"
is thrown in query 'select * from RPCContext;'

![image](https://user-images.githubusercontent.com/35387973/167135389-95cc37ab-c653-47b9-b0d1-e9a1f3053a3d.png)

**Comment by xiaozan-dev** [comment]
tdengine version: 2.4.0.18

**Comment by lczz89** [comment]
加引号应该可规避，`table_name`

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
