### ISSUE TITLE
document invalidation

### ISSUE THREAD

**Issue by day0n** [taosdata/TDengine#12181]
[Writing TDengine tests](https://github.com/taosdata/tests/tree/develop)  in the Chinese documentation [to become a community contributor](https://www.taosdata.com/contributor)  is 404 not found page.

**Comment by day0n** [comment]
I found the test documentation [here](https://github.com/taosdata/TDengine/blob/develop/tests/How-To-Run-Test-And-How-To-Add-New-Test-Case.md). Hope you guys can fix this Chinese document.

**Comment by arielyang** [comment]
Fixed: https://www.taosdata.com/contributor

Thanks!

**Comment by day0n** [comment]
Thanks！
