### ISSUE TITLE
go connector cross compilation

### ISSUE THREAD

**Issue by daxiabiluo** [taosdata/TDengine#1221]
I have done cross-compilation of TDengine in ubuntu, and it runs normally in the arm system after testing. Now you need to cross compile the go connector, enter the following information:

root@hubin-virtual-machine:~/go/src# go build goConnector.go 
# github.com/taosdata/taosSql
/usr/local/arm/gcc-linaro-arm-linux-gnueabihf-4.8-2014.04_linux/bin/../lib/gcc/arm-linux-gnueabihf/4.8.3/../../../../arm-linux-gnueabihf/bin/ld: warning: libatomic.so.1, needed by /usr/lib/libtaos.so, not found (try using -rpath or -rpath-link)
# github.com/taosdata/taosSql
github.com/taosdata/taosSql/result.go:53:14: type [1073741824]_Ctype_struct_taosField larger than address space
github.com/taosdata/taosSql/result.go:53:14: type [1073741824]_Ctype_struct_taosField too large
root@hubin-virtual-machine:~/go/src# 

libtaos.so uses the files under build / lib generated by TDengine cross compilation

**Comment by plum-lihui** [comment]
We haven't started the work yet. It will take a while.

**Comment by plum-lihui** [comment]
目前2.0版本都能支持go connector了，请pull最新代码编译即可。
多谢！
