### ISSUE TITLE
odbc cann't connect without a predefined DSN

### ISSUE THREAD

**Issue by hcwang512** [taosdata/TDengine#12268]
**Is your feature request related to a problem? Please describe.**

**Describe your desired behavior**
odbc also support connect to database using connection string without a predefined dsn in config file odbc.ini, please see the example in https://dev.mysql.com/doc/connector-odbc/en/connector-odbc-configuration-connection-without-dsn.html.
At present, odbc connection requires a dsn parameters. It's not easy to use in a environment where database can be added dynamically. It will be great if we can connect to tdengine without configure odbc.ini at first.

**Describe your solutions/suggestions if you've any**
read parameters from connection string

**Additional context**

**Comment by freemine** [comment]
"It's not easy to use in a environment where database can be added dynamically."
do you mean that you wanna use taos-odbc-driver in a way where this taos-odbc-driver has not been registered yet into system?

**Comment by hcwang512** [comment]
> "It's not easy to use in a environment where database can be added dynamically." do you mean that you wanna use taos-odbc-driver in a way where this taos-odbc-driver has not been registered yet into system?
> 
> Just FYI: http://www.unixodbc.org/odbcinst.html

yes, taos-odbc-driver has not been registered into system. odbcinst can solve the problem. We prefer to use odbc without a config file and just concat the parameters into a connection string, and odbc can connect to a datasource with the connection string.

**Comment by hcwang512** [comment]
Thanks a lot @freemine 
I will close the issue.
