### ISSUE TITLE
Java schemaless write tag with comma

### ISSUE THREAD

**Issue by xtxz** [taosdata/TDengine#12280]
tdengine version：2.4.0.7
插入字符串的tag：name="{1,}(?:,[0-9]{1,})*}/products" 
被识别为：}(?:,[0-9]{1,})*}/products"... | NCHAR                |          14 | TAG      |
当把字符串里面的逗号去掉后，写入正常
怀疑是对字符串里面的第一个逗号识别存在问题

**Comment by xtxz** [comment]
你好，我这边用的是SchemalessProtocolType.LINE，经过对tag的缩减，测试代码如下：
SchemalessWriter writer = new SchemalessWriter(conn);
                        String ss = "test_stat,http_code=\"200\",name=\"/t1/test/{test:[0-9]{1,}(?:,[0-9]{1,})*}/products\" total_time=388.1 1652089066000";
                        writer.write(ss, SchemalessProtocolType.LINE, SchemalessTimestampType.MILLI_SECONDS);
报错如下：
 Invoke influxdb write error:
java.sql.SQLException: TDengine ERROR (2350): failed to insertLines
当我把字符串里的逗号去掉则能正常插入

**Comment by huolibo** [comment]
测试在 line 协议下确实存在此问题。不属于 java 连接器的情况，已经通知数据库负责人员修改。

**Comment by xtxz** [comment]
补充说明，line模式里面的字符串的双引号，会被识别为tag的一部分，例如name="xxx"，正确的tag应该为xxx，但line模式tag会变为"xxx"

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
