### ISSUE TITLE
Comparison between TDengine and InfluxDB  

### ISSUE THREAD

**Issue by jtao1735** [taosdata/TDengine#123]
For the performance and functionality comparison between InfluxDB and TDengine, please check https://www.taosdata.com/blog/2019/07/19/tdengine%e4%b8%8einfluxdb%e5%af%b9%e6%af%94%e6%b5%8b%e8%af%95/

You are welcome to clone the testing code and make changes to fit your own testing scenarios

**Comment by withgakki** [comment]
@guanshengliang 
![DBengine](https://user-images.githubusercontent.com/39128271/61617946-5d33d900-ac9e-11e9-9645-d000963c4074.png)
can you tell me the reason

**Comment by guanshengliang** [comment]
We have already fixed this bug in #130 and committed it!
