### ISSUE TITLE
ERROR DND to lock file:/var/lib/taos/.running ret:-1

### ISSUE THREAD

**Issue by elephantjohn** [taosdata/TDengine#1230]
today I installed toas and going to used it, after i build and install , the command "taos" runs well ,but the command "toasd" returns some error  as follows ,just like  the issue: #476 

```
use taosd command to start service,then failed.The error log is shown below:
09/08 14:55:05.324749 7f31f1a17740 UTL timezone not configured, set to system default: (CST, +0800)
09/08 14:55:05.324852 7f31f1a17740 UTL locale not configured, set to system default:en_US.UTF-8
09/08 14:55:05.324879 7f31f1a17740 UTL charset not configured, set to system default:UTF-8
09/08 14:55:05.324963 7f31f1a17740 ERROR DND failed to lock file:/var/lib/taos/.running ret:-1, database may be running, quit
```

can anyone tell me how to solve? thank u very much

**Comment by plum-lihui** [comment]
Is there already a taosd process running? 
To TDengine , can not run multiple taosd in one system at the same time.

**Comment by elephantjohn** [comment]
> Is there already a taosd process running?
> To TDengine , can not run multiple taosd in one system at the same time.

thanks for your reply.
i ran "ps aux | grep taosd " and "ps aux | grep taos" ,and there are no process info returned ,so i think there is  no process running  (I am not very sure how to tell if the taos program is already running)

**Comment by sangshuduo** [comment]
May I know if you still have this issue?
