### ISSUE TITLE
Build script secretly doing Maven install

### ISSUE THREAD

**Issue by stevel032** [taosdata/TDengine#1234]
**Bug Description**
The build script itself, when building the software, actually tries to "install" Java artifacts into my home directory outside the build directories

**To Reproduce**
Download software, build, and watch the commands.

**Expected Behavior**
I'd expect everything to be done in the ..../build directory, without touching anything outside, especially my own Java environment.

**Screenshots**
Portion of the build output is pasted below:
```
[100%] build jdbc driver
cd /home/stevel/workspace/TDengine/build/src/connector/jdbc && mvn -Dmaven.test.skip=true install -f /home/stevel/workspace/TDengine/src/connector/jdbc/pom.xml
```

As you can see, the CMake script is doing "mvn install" during a normal build (equivalent to "mvn compile"). In such a case, it should NOT install anything into my ~/.m2 directory!

**Environment (please complete the following information):**
 - OS: Ubuntu 18.4
 - Memory, CPU, current Disk Space: Plenty
 - TDengine Version 1.6.5.4

**Additional Context**
None and thank you all!

**Comment by plum-lihui** [comment]
OK。Only package in the compilation script, do not install the jar package to this machine。

**Comment by stevel032** [comment]
Cool... does this mean it's been corrected?
