### ISSUE TITLE
Whether setting the database update parameter to 1 will cause storage, query, or other performance degradation

### ISSUE THREAD

**Issue by Aismiler** [taosdata/TDengine#12364]
tdengine版本 2.0.9.1
我现在有频率不是很高的修改数据库中某个时间的值的需求，阅读文档后发现，我现在使用的版本支持修改，请问，当我在创建数据库时把update设为1会不会导致存储查询或者其他方面的性能损失，谢谢。

**Comment by ljluestc** [comment]
在Tdengine中，将数据库的更新参数（update）设置为1不会导致存储、查询或其他方面的性能损失。更新参数（update）用于指定在写入新数据时是否对旧数据进行更新，其取值可以是0或1。

当将更新参数设置为1时，表示在写入新数据时会对旧数据进行更新，这可以用于修改数据库中某个时间的值。这种更新操作是原子性的，可以确保数据的一致性。更新参数的设置不会对存储、查询或其他性能方面产生明显的负面影响。

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
