### ISSUE TITLE
Add support for cgo on MS Windows?

### ISSUE THREAD

**Issue by stevel032** [taosdata/TDengine#1239]
Some guy has already done this, would you consider adding/merging this into your code base?

基于TDengine-ver-1.6.4.4在windows 10下cmake+msys2编译(windows cgo 使用)

https://copyfuture.com/blogs-details/20191230065628877gxe1ddk3m3ak1ku

**Comment by plum-lihui** [comment]
已经merge了，只是我们没有还没有正式在发布包中发布。可以自己编译：https://www.taosdata.com/blog/2020/01/06/1093.html。
后续我们考虑编译出来，放到正式的发布版本中。
多谢！
