### ISSUE TITLE
How do I compile the Windows client myself?

### ISSUE THREAD

**Issue by stevel032** [taosdata/TDengine#1240]
I see that this project has a milestone called "Release Windows Client", but I looked at various places and couldn't find how I can compile the Windows client myself. For security reasons, I really don't want to download binary files onto my machine and execute. Can you share the compile steps? or offer a pointer or two to the instructions?

**Comment by sangshuduo** [comment]
If it is a Windows operating system

   1.Use command line tool of VS2013 or higher version
     mkdir build; cd build;
     cmake -G "NMake Makefiles" ..
     nmake install

tips: run "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat amd64" first

   2.Use the VS development interface tool
     mkdir build; cd build;
     cmake -A x64 ..
     open the file named TDengine.sln
