### ISSUE TITLE
Program terminated with signal 11, Segmentation fault. 

### ISSUE THREAD

**Issue by sunashe** [taosdata/TDengine#1241]
**Bug Description**
[root@test-trace-other_app-020044 bin]# ./taosd -c /etc/taos/
02/20 07:35:27.066049 7066 7f6dca4b6700 UTL timezone not configured, set to system default: (Local time zone must be set--see zic manual page, +0000)
02/20 07:35:27.066079 7066 7f6dca4b6700 UTL charset not configured, set to system default:UTF-8
Invalid locale:zh_CN.UTF-8, please set the valid locale in config file
02/20 07:35:27.066148 7066 7f6dca4b6700 UTL Invalid locale:zh_CN.UTF-8, please set the valid locale in config file

02/20 07:35:27.067886 7066 7f6dca4b6700 UTL    taos config & system info:
02/20 07:35:27.067901 7066 7f6dca4b6700 UTL ==================================
02/20 07:35:27.067904 7066 7f6dca4b6700 UTL  localIp:                100.73.20.44
02/20 07:35:27.067908 7066 7f6dca4b6700 UTL  httpIp:                 0.0.0.0
02/20 07:35:27.067911 7066 7f6dca4b6700 UTL  httpPort:               6020
02/20 07:35:27.067914 7066 7f6dca4b6700 UTL  mgmtShellPort:          6030
02/20 07:35:27.067916 7066 7f6dca4b6700 UTL  vnodeShellPort:         6035
02/20 07:35:27.067919 7066 7f6dca4b6700 UTL  configDir:              /etc/taos/
02/20 07:35:27.067921 7066 7f6dca4b6700 UTL  logDir:                 /var/log/taos
02/20 07:35:27.067931 7066 7f6dca4b6700 UTL  scriptDir:              /etc/taos
02/20 07:35:27.067934 7066 7f6dca4b6700 UTL  dataDir:                /var/lib/taos
02/20 07:35:27.067936 7066 7f6dca4b6700 UTL  numOfThreadsPerCore:    1.000000
02/20 07:35:27.067947 7066 7f6dca4b6700 UTL  ratioOfQueryThreads:    0.500000
02/20 07:35:27.067959 7066 7f6dca4b6700 UTL  numOfVnodesPerCore:     8
02/20 07:35:27.067962 7066 7f6dca4b6700 UTL  numOfTotalVnodes:       0
02/20 07:35:27.067964 7066 7f6dca4b6700 UTL  tables:                 1000
02/20 07:35:27.067967 7066 7f6dca4b6700 UTL  cache:                  16384(byte)
02/20 07:35:27.067969 7066 7f6dca4b6700 UTL  rows:                   4096
02/20 07:35:27.067972 7066 7f6dca4b6700 UTL  fileBlockMinPercent:    0.050000
02/20 07:35:27.067975 7066 7f6dca4b6700 UTL  ablocks:                4
02/20 07:35:27.067977 7066 7f6dca4b6700 UTL  tblocks:                100
02/20 07:35:27.067980 7066 7f6dca4b6700 UTL  affectedRowsMod:        0
02/20 07:35:27.067982 7066 7f6dca4b6700 UTL  monitorInterval:        30(s)
02/20 07:35:27.067985 7066 7f6dca4b6700 UTL  rpcTimer:               300(ms)
02/20 07:35:27.067987 7066 7f6dca4b6700 UTL  rpcMaxTime:             600(s)
02/20 07:35:27.067990 7066 7f6dca4b6700 UTL  ctime:                  3600(s)
02/20 07:35:27.067992 7066 7f6dca4b6700 UTL  statusInterval:         1(s)
02/20 07:35:27.067994 7066 7f6dca4b6700 UTL  shellActivityTimer:     3(s)
02/20 07:35:27.067997 7066 7f6dca4b6700 UTL  meterMetaKeepTimer:     7200(s)
02/20 07:35:27.067999 7066 7f6dca4b6700 UTL  metricMetaKeepTimer:    600(s)
02/20 07:35:27.068002 7066 7f6dca4b6700 UTL  maxUsers:               1000
02/20 07:35:27.068004 7066 7f6dca4b6700 UTL  maxDbs:                 1000
02/20 07:35:27.068006 7066 7f6dca4b6700 UTL  maxTables:              650000
02/20 07:35:27.068009 7066 7f6dca4b6700 UTL  maxVGroups:             1000
02/20 07:35:27.068011 7066 7f6dca4b6700 UTL  minSlidingTime:         10(ms)
02/20 07:35:27.068014 7066 7f6dca4b6700 UTL  minIntervalTime:        10(ms)
02/20 07:35:27.068016 7066 7f6dca4b6700 UTL  maxStreamCompDelay:     20000(ms)
02/20 07:35:27.068018 7066 7f6dca4b6700 UTL  maxFirstStreamCompDelay:10000(ms)
02/20 07:35:27.068021 7066 7f6dca4b6700 UTL  retryStreamCompDelay:   10(ms)
02/20 07:35:27.068023 7066 7f6dca4b6700 UTL  clog:                   1
02/20 07:35:27.068026 7066 7f6dca4b6700 UTL  comp:                   2
02/20 07:35:27.068028 7066 7f6dca4b6700 UTL  days:                   10
02/20 07:35:27.068031 7066 7f6dca4b6700 UTL  keep:                   3650
02/20 07:35:27.068033 7066 7f6dca4b6700 UTL  defaultDB:
02/20 07:35:27.068036 7066 7f6dca4b6700 UTL  defaultUser:            root
02/20 07:35:27.068038 7066 7f6dca4b6700 UTL  sockettype:             udp
02/20 07:35:27.068041 7066 7f6dca4b6700 UTL  compressMsgSize:        -1
02/20 07:35:27.068044 7066 7f6dca4b6700 UTL  maxSQLLength:           65380(byte)
02/20 07:35:27.068046 7066 7f6dca4b6700 UTL  timezone:                (Local time zone must be set--see zic manual page, +0000)
02/20 07:35:27.068051 7066 7f6dca4b6700 UTL  locale:                 zh_CN.UTF-8
02/20 07:35:27.068054 7066 7f6dca4b6700 UTL  charset:                UTF-8
02/20 07:35:27.068056 7066 7f6dca4b6700 UTL  maxShellConns:          2000
02/20 07:35:27.068059 7066 7f6dca4b6700 UTL  maxMeterConnections:    10000
02/20 07:35:27.068062 7066 7f6dca4b6700 UTL  maxMgmtConnections:     2000
02/20 07:35:27.068064 7066 7f6dca4b6700 UTL  maxVnodeConnections:    10000
02/20 07:35:27.068067 7066 7f6dca4b6700 UTL  minimalLogDirGB:        0.100000(GB)
02/20 07:35:27.068069 7066 7f6dca4b6700 UTL  minimalTmpDirGB:        0.100000(GB)
02/20 07:35:27.068072 7066 7f6dca4b6700 UTL  minimalDataDirGB:       0.500000(GB)
02/20 07:35:27.068075 7066 7f6dca4b6700 UTL  http:                   1
02/20 07:35:27.068077 7066 7f6dca4b6700 UTL  monitor:                1
02/20 07:35:27.068080 7066 7f6dca4b6700 UTL  monitorDbName:          log
02/20 07:35:27.068082 7066 7f6dca4b6700 UTL  httpCacheSessions:      100
02/20 07:35:27.068091 7066 7f6dca4b6700 UTL  httpEnableRecordSql:    0
02/20 07:35:27.068093 7066 7f6dca4b6700 UTL  telegrafUseFieldNum:    0
02/20 07:35:27.068096 7066 7f6dca4b6700 UTL  httpMaxThreads:         2
02/20 07:35:27.068098 7066 7f6dca4b6700 UTL  restfulRowLimit:        10240
02/20 07:35:27.068101 7066 7f6dca4b6700 UTL  httpEnableCompress:     0
02/20 07:35:27.068103 7066 7f6dca4b6700 UTL  numOfLogLines:          10000000
02/20 07:35:27.068105 7066 7f6dca4b6700 UTL  asyncLog:               1
02/20 07:35:27.068108 7066 7f6dca4b6700 UTL  debugFlag:              131
02/20 07:35:27.068110 7066 7f6dca4b6700 UTL  mDebugFlag:             135
02/20 07:35:27.068113 7066 7f6dca4b6700 UTL  dDebugFlag:             131
02/20 07:35:27.068120 7066 7f6dca4b6700 UTL  sdbDebugFlag:           135
02/20 07:35:27.068123 7066 7f6dca4b6700 UTL  rpcDebugFlag:           131
02/20 07:35:27.068125 7066 7f6dca4b6700 UTL  tmrDebugFlag:           131
02/20 07:35:27.068127 7066 7f6dca4b6700 UTL  cDebugFlag:             131
02/20 07:35:27.068130 7066 7f6dca4b6700 UTL  jniDebugFlag:           131
02/20 07:35:27.068144 7066 7f6dca4b6700 UTL  odbcDebugFlag:          131
02/20 07:35:27.068147 7066 7f6dca4b6700 UTL  uDebugFlag:             131
02/20 07:35:27.068150 7066 7f6dca4b6700 UTL  httpDebugFlag:          131
02/20 07:35:27.068152 7066 7f6dca4b6700 UTL  monitorDebugFlag:       131
02/20 07:35:27.068159 7066 7f6dca4b6700 UTL  qDebugFlag:             131
02/20 07:35:27.068162 7066 7f6dca4b6700 UTL  tscEnableRecordSql:     0
02/20 07:35:27.068164 7066 7f6dca4b6700 UTL  enableCoreFile:         0
02/20 07:35:27.068166 7066 7f6dca4b6700 UTL  gitinfo:                918cb2220f6a1f71966f7e94e697885d50fc241f
02/20 07:35:27.068169 7066 7f6dca4b6700 UTL  gitinfoOfInternal:
02/20 07:35:27.068171 7066 7f6dca4b6700 UTL  buildinfo:              Built by root at 2020-02-09 11:06
02/20 07:35:27.068174 7066 7f6dca4b6700 UTL  version:                1.6.5.5
02/20 07:35:27.068176 7066 7f6dca4b6700 UTL  dataDir:                /var/lib/taos
02/20 07:35:27.068559 7066 7f6dca4b6700 UTL  os pageSize:            4096(KB)
02/20 07:35:27.068574 7066 7f6dca4b6700 UTL  os openMax:             65535
02/20 07:35:27.068578 7066 7f6dca4b6700 UTL  os streamMax:           16
02/20 07:35:27.068582 7066 7f6dca4b6700 UTL  os numOfCores:          4
02/20 07:35:27.068585 7066 7f6dca4b6700 UTL  os totalDisk:           44.697632(GB)
02/20 07:35:27.068594 7066 7f6dca4b6700 UTL  os totalMemory:         7872(MB)
02/20 07:35:27.068602 7066 7f6dca4b6700 UTL  os sysname:             Linux
02/20 07:35:27.068606 7066 7f6dca4b6700 UTL  os nodename:            test-trace-other_app-020044
02/20 07:35:27.068609 7066 7f6dca4b6700 UTL  os release:             2.6.32-431.el6.x86_64
02/20 07:35:27.068613 7066 7f6dca4b6700 UTL  os version:             #1 SMP Fri Nov 22 03:15:09 UTC 2013
02/20 07:35:27.068617 7066 7f6dca4b6700 UTL  os machine:             x86_64
02/20 07:35:27.068621 7066 7f6dca4b6700 UTL ==================================
02/20 07:35:27.068627 7066 7f6dca4b6700 DND Server IP address is:100.73.20.44
02/20 07:35:27.068636 7066 7f6dca4b6700 DND starting to initialize TDengine ...
02/20 07:35:27.068814 7066 7f6dca4b6700 MND starting to initialize TDengine mgmt ...
02/20 07:35:27.069485 7066 7f6dca4b6700 MND dnode first access, set total vnodes:50
02/20 07:35:27.086101 7066 7f6dca4b6700 MND TDengine mgmt is initialized successfully
02/20 07:35:27.088828 7066 7f6dca4b6700 DND vid:0, cache pool is allocated:0xd5ff40
02/20 07:35:27.089014 7066 7f6dca4b6700 DND vid:0, commit log is initialized
02/20 07:35:27.089038 7066 7f6dca4b6700 DND vid:0, storage initialized, version:407110 fileId:1831 numOfFiles:4
02/20 07:35:27.089131 7066 7f6dca4b6700 DND vid:1, cache pool is allocated:0xd605c0
02/20 07:35:27.089267 7066 7f6dca4b6700 DND vid:1, commit log is initialized
02/20 07:35:27.089291 7066 7f6dca4b6700 DND vid:1, storage initialized, version:9 fileId:1821 numOfFiles:2
02/20 07:35:27.089371 7066 7f6dca4b6700 DND vid:2, cache pool is allocated:0xd60630
02/20 07:35:27.089527 7066 7f6dca4b6700 DND vid:2, commit log is initialized
02/20 07:35:27.089547 7066 7f6dca4b6700 DND vid:2, storage initialized, version:8009656 fileId:1822 numOfFiles:3
02/20 07:35:27.089648 7066 7f6dca4b6700 DND vid:3, cache pool is allocated:0xd616b0
02/20 07:35:27.089753 7066 7f6dca4b6700 DND vid:3, commit log is initialized
02/20 07:35:27.089773 7066 7f6dca4b6700 DND vid:3, storage initialized, version:73156 fileId:1821 numOfFiles:1
02/20 07:35:27.089840 7066 7f6dca4b6700 DND vid:4, cache pool is allocated:0xd72b70
02/20 07:35:27.089918 7066 7f6dca4b6700 DND vid:4, commit log is initialized
02/20 07:35:27.089937 7066 7f6dca4b6700 DND vid:4, storage initialized, version:39979 fileId:1821 numOfFiles:1
02/20 07:35:27.090019 7066 7f6dca4b6700 DND vid:5, cache pool is allocated:0xd730e0
02/20 07:35:27.090126 7066 7f6dca4b6700 DND vid:5, commit log is initialized
02/20 07:35:27.090147 7066 7f6dca4b6700 DND vid:5, storage initialized, version:971869 fileId:1821 numOfFiles:1
02/20 07:35:27.090237 7066 7f6dca4b6700 DND vid:6, cache pool is allocated:0xd73150
02/20 07:35:27.090341 7066 7f6dca4b6700 DND vid:6, commit log is initialized
02/20 07:35:27.090364 7066 7f6dca4b6700 DND vid:6, storage initialized, version:38 fileId:1831 numOfFiles:2
02/20 07:35:27.090441 7066 7f6dca4b6700 DND vid:7, cache pool is allocated:0xd73300
02/20 07:35:27.090575 7066 7f6dca4b6700 DND vid:7, commit log is initialized
02/20 07:35:27.090597 7066 7f6dca4b6700 DND vid:7, storage initialized, version:0 fileId:0 numOfFiles:0
02/20 07:35:27.090676 7066 7f6dca4b6700 DND vid:8, cache pool is allocated:0xd997e0
02/20 07:35:27.090766 7066 7f6dca4b6700 DND vid:8, commit log is initialized
02/20 07:35:27.090780 7066 7f6dca4b6700 DND vid:8, storage initialized, version:897189 fileId:1831 numOfFiles:2
02/20 07:35:27.090855 7066 7f6dca4b6700 DND vid:9, cache pool is allocated:0xd99130
02/20 07:35:27.090968 7066 7f6dca4b6700 DND vid:9, commit log is initialized
02/20 07:35:27.090997 7066 7f6dca4b6700 DND vid:9, storage initialized, version:0 fileId:0 numOfFiles:0
02/20 07:35:27.091068 7066 7f6dca4b6700 DND vid:10, cache pool is allocated:0xdbfb70
02/20 07:35:27.091197 7066 7f6dca4b6700 DND vid:10, commit log is initialized
02/20 07:35:27.091221 7066 7f6dca4b6700 DND vid:10, storage initialized, version:41005362 fileId:1831 numOfFiles:2
02/20 07:35:27.091315 7066 7f6dca4b6700 DND vid:11, cache pool is allocated:0xdbf600
02/20 07:35:27.091425 7066 7f6dca4b6700 DND vid:11, commit log is initialized
02/20 07:35:27.091446 7066 7f6dca4b6700 DND vid:11, storage initialized, version:1000 fileId:1792 numOfFiles:4
02/20 07:35:27.091552 7066 7f6dca4b6700 DND vid:12, cache pool is allocated:0xde55c0
02/20 07:35:27.091622 7066 7f6dca4b6700 DND vid:12, commit log is initialized
02/20 07:35:27.091636 7066 7f6dca4b6700 DND vid:12, storage initialized, version:0 fileId:0 numOfFiles:0
02/20 07:35:27.091755 7066 7f6dca4b6700 DND vid:13, cache pool is allocated:0xde60a0
02/20 07:35:27.091854 7066 7f6dca4b6700 DND vid:13, commit log is initialized
02/20 07:35:27.091876 7066 7f6dca4b6700 DND vid:13, storage initialized, version:22794965 fileId:1831 numOfFiles:1
02/20 07:35:27.091946 7066 7f6dca4b6700 DND vid:19, cache pool is allocated:0xde5b30
02/20 07:35:27.092031 7066 7f6dca4b6700 DND vid:19, commit log is initialized
02/20 07:35:27.092046 7066 7f6dca4b6700 DND vid:19, storage initialized, version:5337556 fileId:1821 numOfFiles:3
02/20 07:35:27.092108 7066 7f6dca4b6700 DND vid:22, cache pool is allocated:0xde5ce0
02/20 07:35:27.092204 7066 7f6dca4b6700 DND vid:22, commit log is initialized
02/20 07:35:27.092220 7066 7f6dca4b6700 DND vid:22, storage initialized, version:1473 fileId:1821 numOfFiles:2
02/20 07:35:27.092289 7066 7f6dca4b6700 DND vid:34, cache pool is allocated:0xe0ed50
02/20 07:35:27.092373 7066 7f6dca4b6700 DND vid:34, commit log is initialized
02/20 07:35:27.092394 7066 7f6dca4b6700 DND vid:34, storage initialized, version:42696 fileId:1821 numOfFiles:2
02/20 07:35:27.092460 7066 7f6dca4b6700 DND vid:35, cache pool is allocated:0xe0ee30
02/20 07:35:27.092677 7066 7f6dca4b6700 DND vid:35, commit log is initialized
02/20 07:35:27.092698 7066 7f6dca4b6700 DND vid:35, storage initialized, version:3284903 fileId:1829 numOfFiles:10
02/20 07:35:27.093130 7066 7f6dca4b6700 DND vid:0, status:offline, start to open
02/20 07:35:27.093199 7066 7f6dca4b6700 DND vid:0, sessions:33, shell is opened
02/20 07:35:27.093220 7066 7f6dca4b6700 DND vid:0, status:master numOfPeers:0
02/20 07:35:27.093233 7066 7f6dca4b6700 DND vid:0, stream role is changed from stop to start
02/20 07:35:27.093256 7066 7f6dca4b6700 DND vid:0, vnode is opened, openVnodes:1, status:master
02/20 07:35:27.093264 7066 7f6dca4b6700 DND vid:1, status:offline, start to open
02/20 07:35:27.093337 7066 7f6dca4b6700 DND vid:1, sessions:1001, shell is opened
02/20 07:35:27.093350 7066 7f6dca4b6700 DND vid:1, status:master numOfPeers:0
02/20 07:35:27.093357 7066 7f6dca4b6700 DND vid:1, stream role is changed from stop to start
02/20 07:35:27.093369 7066 7f6dca4b6700 DND vid:1, vnode is opened, openVnodes:2, status:master
02/20 07:35:27.093382 7066 7f6dca4b6700 DND vid:2, status:offline, start to open
02/20 07:35:27.093431 7066 7f6dca4b6700 DND vid:2, sessions:1001, shell is opened
02/20 07:35:27.093448 7066 7f6dca4b6700 DND vid:2, status:master numOfPeers:0
02/20 07:35:27.093456 7066 7f6dca4b6700 DND vid:2, stream role is changed from stop to start
02/20 07:35:27.093468 7066 7f6dca4b6700 DND vid:2, vnode is opened, openVnodes:3, status:master
02/20 07:35:27.093479 7066 7f6dca4b6700 DND vid:3, status:offline, start to open
02/20 07:35:27.093568 7066 7f6dca4b6700 DND vid:3, sessions:1001, shell is opened
02/20 07:35:27.093593 7066 7f6dca4b6700 DND vid:3, status:master numOfPeers:0
02/20 07:35:27.093604 7066 7f6dca4b6700 DND vid:3, stream role is changed from stop to start
02/20 07:35:27.093618 7066 7f6dca4b6700 DND vid:3, vnode is opened, openVnodes:4, status:master
02/20 07:35:27.093625 7066 7f6dca4b6700 DND vid:4, status:offline, start to open
02/20 07:35:27.093662 7066 7f6dca4b6700 DND vid:4, sessions:1001, shell is opened
02/20 07:35:27.093674 7066 7f6dca4b6700 DND vid:4, status:master numOfPeers:0
02/20 07:35:27.093681 7066 7f6dca4b6700 DND vid:4, stream role is changed from stop to start
02/20 07:35:27.093693 7066 7f6dca4b6700 DND vid:4, vnode is opened, openVnodes:5, status:master
02/20 07:35:27.093701 7066 7f6dca4b6700 DND vid:5, status:offline, start to open
02/20 07:35:27.093748 7066 7f6dca4b6700 DND vid:5, sessions:1001, shell is opened
02/20 07:35:27.093769 7066 7f6dca4b6700 DND vid:5, status:master numOfPeers:0
02/20 07:35:27.093794 7066 7f6dca4b6700 DND vid:5, stream role is changed from stop to start
02/20 07:35:27.093809 7066 7f6dca4b6700 DND vid:5, vnode is opened, openVnodes:6, status:master
02/20 07:35:27.093826 7066 7f6dca4b6700 DND vid:6, status:offline, start to open
02/20 07:35:27.093872 7066 7f6dca4b6700 DND vid:6, sessions:1001, shell is opened
02/20 07:35:27.093884 7066 7f6dca4b6700 DND vid:6, status:master numOfPeers:0
02/20 07:35:27.093891 7066 7f6dca4b6700 DND vid:6, stream role is changed from stop to start
02/20 07:35:27.093904 7066 7f6dca4b6700 DND vid:6, vnode is opened, openVnodes:7, status:master
02/20 07:35:27.093916 7066 7f6dca4b6700 DND vid:7, status:offline, start to open
02/20 07:35:27.093970 7066 7f6dca4b6700 DND vid:7, sessions:1001, shell is opened
02/20 07:35:27.093986 7066 7f6dca4b6700 DND vid:7, status:master numOfPeers:0
02/20 07:35:27.093993 7066 7f6dca4b6700 DND vid:7, stream role is changed from stop to start
02/20 07:35:27.094006 7066 7f6dca4b6700 DND vid:7, vnode is opened, openVnodes:8, status:master
02/20 07:35:27.094012 7066 7f6dca4b6700 DND vid:8, status:offline, start to open
02/20 07:35:27.094060 7066 7f6dca4b6700 DND vid:8, sessions:1001, shell is opened
02/20 07:35:27.094077 7066 7f6dca4b6700 DND vid:8, status:master numOfPeers:0
02/20 07:35:27.094095 7066 7f6dca4b6700 DND vid:8, stream role is changed from stop to start
02/20 07:35:27.094122 7066 7f6dca4b6700 DND vid:8, vnode is opened, openVnodes:9, status:master
02/20 07:35:27.094138 7066 7f6dca4b6700 DND vid:9, status:offline, start to open
02/20 07:35:27.094190 7066 7f6dca4b6700 DND vid:9, sessions:1001, shell is opened
02/20 07:35:27.094205 7066 7f6dca4b6700 DND vid:9, status:master numOfPeers:0
02/20 07:35:27.094211 7066 7f6dca4b6700 DND vid:9, stream role is changed from stop to start
02/20 07:35:27.094225 7066 7f6dca4b6700 DND vid:9, vnode is opened, openVnodes:10, status:master
02/20 07:35:27.094236 7066 7f6dca4b6700 DND vid:10, status:offline, start to open
02/20 07:35:27.094287 7066 7f6dca4b6700 DND vid:10, sessions:1001, shell is opened
02/20 07:35:27.094307 7066 7f6dca4b6700 DND vid:10, status:master numOfPeers:0
02/20 07:35:27.094316 7066 7f6dca4b6700 DND vid:10, stream role is changed from stop to start
02/20 07:35:27.094341 7066 7f6dca4b6700 DND vid:10, vnode is opened, openVnodes:11, status:master
02/20 07:35:27.094350 7066 7f6dca4b6700 DND vid:11, status:offline, start to open
02/20 07:35:27.094388 7066 7f6dca4b6700 DND vid:11, sessions:1001, shell is opened
02/20 07:35:27.094398 7066 7f6dca4b6700 DND vid:11, status:master numOfPeers:0
02/20 07:35:27.094404 7066 7f6dca4b6700 DND vid:11, stream role is changed from stop to start
02/20 07:35:27.094417 7066 7f6dca4b6700 DND vid:11, vnode is opened, openVnodes:12, status:master
02/20 07:35:27.094433 7066 7f6dca4b6700 DND vid:12, status:offline, start to open
02/20 07:35:27.094463 7066 7f6dca4b6700 DND vid:12, sessions:1001, shell is opened
02/20 07:35:27.094481 7066 7f6dca4b6700 DND vid:12, status:master numOfPeers:0
02/20 07:35:27.094490 7066 7f6dca4b6700 DND vid:12, stream role is changed from stop to start
02/20 07:35:27.094548 7066 7f6dca4b6700 DND vid:12, vnode is opened, openVnodes:13, status:master
02/20 07:35:27.094580 7066 7f6dca4b6700 DND vid:13, status:offline, start to open
02/20 07:35:27.094637 7066 7f6dca4b6700 DND vid:13, sessions:1001, shell is opened
02/20 07:35:27.094667 7066 7f6dca4b6700 DND vid:13, status:master numOfPeers:0
02/20 07:35:27.094677 7066 7f6dca4b6700 DND vid:13, stream role is changed from stop to start
02/20 07:35:27.094694 7066 7f6dca4b6700 DND vid:13, vnode is opened, openVnodes:14, status:master
02/20 07:35:27.094709 7066 7f6dca4b6700 DND vid:19, status:offline, start to open
02/20 07:35:27.094768 7066 7f6dca4b6700 DND vid:19, sessions:1001, shell is opened
02/20 07:35:27.094789 7066 7f6dca4b6700 DND vid:19, status:master numOfPeers:0
02/20 07:35:27.094798 7066 7f6dca4b6700 DND vid:19, stream role is changed from stop to start
02/20 07:35:27.094822 7066 7f6dca4b6700 DND vid:19, vnode is opened, openVnodes:15, status:master
02/20 07:35:27.094838 7066 7f6dca4b6700 DND vid:22, status:offline, start to open
02/20 07:35:27.094886 7066 7f6dca4b6700 DND vid:22, sessions:1001, shell is opened
02/20 07:35:27.094904 7066 7f6dca4b6700 DND vid:22, status:master numOfPeers:0
02/20 07:35:27.094913 7066 7f6dca4b6700 DND vid:22, stream role is changed from stop to start
02/20 07:35:27.094943 7066 7f6dca4b6700 DND vid:22, vnode is opened, openVnodes:16, status:master
02/20 07:35:27.094967 7066 7f6dca4b6700 DND vid:34, status:offline, start to open
02/20 07:35:27.095021 7066 7f6dca4b6700 DND vid:34, sessions:1001, shell is opened
02/20 07:35:27.095040 7066 7f6dca4b6700 DND vid:34, status:master numOfPeers:0
02/20 07:35:27.095049 7066 7f6dca4b6700 DND vid:34, stream role is changed from stop to start
02/20 07:35:27.095072 7066 7f6dca4b6700 DND vid:34, vnode is opened, openVnodes:17, status:master
02/20 07:35:27.095088 7066 7f6dca4b6700 DND vid:35, status:offline, start to open
02/20 07:35:27.095146 7066 7f6dca4b6700 DND vid:35, sessions:1001, shell is opened
02/20 07:35:27.095172 7066 7f6dca4b6700 DND vid:35, status:master numOfPeers:0
02/20 07:35:27.095182 7066 7f6dca4b6700 DND vid:35, stream role is changed from stop to start
02/20 07:35:27.095213 7066 7f6dca4b6700 DND vid:35, vnode is opened, openVnodes:18, status:master
02/20 07:35:27.095244 7066 7f6dca4b6700 DND vnode is initialized successfully
02/20 07:35:27.095262 7066 7f6dca4b6700 HTP starting to initialize http service ...
02/20 07:35:27.097965 7066 7f6dca4b6700 DND TDengine is initialized successfully
02/20 07:35:27.098013 7066 7f6d110da700 HTP http service init success at ip:0.0.0.0:6020
02/20 07:35:27.109646 7066 7f6dc67cb700 MON starting to initialize monitor service ..
02/20 07:35:27.109920 7066 7f6dc8630700 MND user:monitor login from 100.73.20.44, code:0
段错误 (core dumped)

![](https://gitee.com/sunashe/The-picture-of-the-sunashe/raw/master/k2n0gc.png)

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**
![](https://gitee.com/sunashe/The-picture-of-the-sunashe/raw/master/k2n0gc.png)

**Environment (please complete the following information):**
Linux test-trace-other_app-020044 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
community version: 1.6.5.5

**Additional Context**

**Comment by sangshuduo** [comment]
@sunashe 我们发布了 2.0.3.0 版本，请使用新版本
