### ISSUE TITLE
Every time you update the table structure, you need to restart the taosadapter to ensure that there are operations under it. This table will not report errors

### ISSUE THREAD

**Issue by DouglasJun** [taosdata/TDengine#12415]
How to solve this situation?

**Comment by fenghuazzm** [comment]
What changes have been made to the table structure?
Write operations after modifying the table structure automatically refresh meta Data.
If only data is queried after the table structure is updated, run the `reset query cache` command to refresh meta data.

**Comment by DouglasJun** [comment]
> What changes have been made to the table structure? Write operations after modifying the table structure automatically refresh meta Data. If only data is queried after the table structure is updated, run the `reset query cache` command to refresh meta data.


for example:
I hava a java program ,It's  to reading the scheam from TDengine, like 'desc test'; 
but now ,I need to add a new column to the table test,  I just use 'drop table test' and then add the new column to the test ,next:create the table test with the new column.
  when I run the  same program, the result I get is old table test‘s’ schema. not including the new column.
   I solve this problem through  run the command : systemctl restart taosadapter

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
