### ISSUE TITLE
install.sh is not working on Linux RedHat System

### ISSUE THREAD

**Issue by xiaopingcs** [taosdata/TDengine#12427]
**Bug Description**
install.sh is not working on Linux RedHat System

**To Reproduce**
1. Down TDengine install package from https://docs.taosdata.com/get-started
2. tar -zxf TDengine-server-2.4.0.16.tar.gz
3. cd TDengine-server-2.4.0.16
4. run ./install.sh

**Expected Behavior**
install.sh should work on Linux RedHat System

**Screenshots**
N/A

**Environment (please complete the following information):**
 -  osinfo: Red Hat Enterprise Linux Server
 -  Red Hat Enterprise Linux Server 7.9 (Maipo)
 -  cpe:/o:redhat:enterprise_linux:7.9:GA:server
 -  TDengine Version [2.4.0.16]

**Additional Context**
N/A

**Comment by yunwei37** [comment]
Hi there! I would like to work on this.

**Comment by auula** [comment]
> 

Do you have any relevant detailed error information, it is still a little difficult to reproduce the redhat environment, we can try it on centos7, I want to receive this task, can you please provide detailed error information!

**Comment by xiaopingcs** [comment]
> > 
> 
> Do you have any relevant detailed error information, it is still a little difficult to reproduce the redhat environment, we can try it on centos7, I want to receive this task, can you please provide detailed error information!

@dongyanqiong can you help? this is relate to TS-1473

**Comment by auula** [comment]
> > > 
> > 
> > 
> > Do you have any relevant detailed error information, it is still a little difficult to reproduce the redhat environment, we can try it on centos7, I want to receive this task, can you please provide detailed error information!
> 
> @dongyanqiong can you help? this is relate to TS-1473

我们也可以中文交流，我不太了解`TS-1473`，如果是脚本问题我可以给你修复试试，我的技术栈是`Go`.

**Comment by xiaopingcs** [comment]
> > > > 
> > > 
> > > 
> > > Do you have any relevant detailed error information, it is still a little difficult to reproduce the redhat environment, we can try it on centos7, I want to receive this task, can you please provide detailed error information!
> > 
> > 
> > @dongyanqiong can you help? this is relate to TS-1473
> 
> 我们也可以中文交流，我不太了解`TS-1473`，如果是脚本问题我可以给你修复试试，我的技术栈是`Go`.

这个应该是脚本的问题，看脚本截图里面没有验证redhad, 你可以在虚拟机里面安装一个Red Hat Enterprise Linux Server 7.9 试试
<img width="650" alt="image" src="https://user-images.githubusercontent.com/65699335/172811839-f5bb0951-0e17-4873-8928-3aad4b6cf546.png">

**Comment by auula** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Do you have any relevant detailed error information, it is still a little difficult to reproduce the redhat environment, we can try it on centos7, I want to receive this task, can you please provide detailed error information!
> > > 
> > > 
> > > @dongyanqiong can you help? this is relate to TS-1473
> > 
> > 
> > 我们也可以中文交流，我不太了解`TS-1473`，如果是脚本问题我可以给你修复试试，我的技术栈是`Go`.
> 
> 这个应该是脚本的问题，看脚本截图里面没有验证redhad, 你可以在虚拟机里面安装一个Red Hat Enterprise Linux Server 7.9 试试 <img alt="image" width="650" src="https://user-images.githubusercontent.com/65699335/172811839-f5bb0951-0e17-4873-8928-3aad4b6cf546.png">

你的图片失效了，我这边看不到，我尝试一下，如果可以我可以修复这个问题。

**Comment by auula** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > Do you have any relevant detailed error information, it is still a little difficult to reproduce the redhat environment, we can try it on centos7, I want to receive this task, can you please provide detailed error information!
> > > > 
> > > > 
> > > > @dongyanqiong can you help? this is relate to TS-1473
> > > 
> > > 
> > > 我们也可以中文交流，我不太了解`TS-1473`，如果是脚本问题我可以给你修复试试，我的技术栈是`Go`.
> > 
> > 
> > 这个应该是脚本的问题，看脚本截图里面没有验证redhad, 你可以在虚拟机里面安装一个Red Hat Enterprise Linux Server 7.9 试试 <img alt="image" width="650" src="https://user-images.githubusercontent.com/65699335/172811839-f5bb0951-0e17-4873-8928-3aad4b6cf546.png">
> 
> 我尝试一下，如果可以我可以修复这个问题。

**Comment by xiaopingcs** [comment]
This issue has been fixed in 2.4 and 2.6
