### ISSUE TITLE
make error 1.6.5.5

### ISSUE THREAD

**Issue by sunashe** [taosdata/TDengine#1242]
ithub/TDengine/build/src/util/CMakeFiles/tutil.dir/DependInfo.cmake --color=
Scanning dependencies of target tutil
make[2]: Leaving directory `/data/github/TDengine/build'
make -f src/util/CMakeFiles/tutil.dir/build.make src/util/CMakeFiles/tutil.dir/build
make[2]: Entering directory `/data/github/TDengine/build'
/usr/bin/cmake -E cmake_progress_report /data/github/TDengine/build/CMakeFiles 73
[ 11%] Building C object src/util/CMakeFiles/tutil.dir/src/tmempool.c.o
cd /data/github/TDengine/build/src/util && /usr/bin/cc  -DLINUX -DLITE -DTSDB_REPLICA_MAX_NUM=1 -DUSE_LIBICONV -D_LIBC_REENTRANT -D_M_X64 -D_REENTRANT -D__USE_POSIX -g -std=gnu99 -Wall -fPIC -malign-double -g -malign-stringops -msse4.2 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILE -O0 -DDEBUG -I/data/github/TDengine/src/inc -I/data/github/TDengine/src/os/linux/inc    -o CMakeFiles/tutil.dir/src/tmempool.c.o   -c /data/github/TDengine/src/util/src/tmempool.c
/usr/bin/cmake -E cmake_progress_report /data/github/TDengine/build/CMakeFiles 74
[ 12%] Building C object src/util/CMakeFiles/tutil.dir/src/shash.c.o
cd /data/github/TDengine/build/src/util && /usr/bin/cc  -DLINUX -DLITE -DTSDB_REPLICA_MAX_NUM=1 -DUSE_LIBICONV -D_LIBC_REENTRANT -D_M_X64 -D_REENTRANT -D__USE_POSIX -g -std=gnu99 -Wall -fPIC -malign-double -g -malign-stringops -msse4.2 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILE -O0 -DDEBUG -I/data/github/TDengine/src/inc -I/data/github/TDengine/src/os/linux/inc    -o CMakeFiles/tutil.dir/src/shash.c.o   -c /data/github/TDengine/src/util/src/shash.c
/usr/bin/cmake -E cmake_progress_report /data/github/TDengine/build/CMakeFiles
[ 12%] Building C object src/util/CMakeFiles/tutil.dir/src/tglobalcfg.c.o
cd /data/github/TDengine/build/src/util && /usr/bin/cc  -DLINUX -DLITE -DTSDB_REPLICA_MAX_NUM=1 -DUSE_LIBICONV -D_LIBC_REENTRANT -D_M_X64 -D_REENTRANT -D__USE_POSIX -g -std=gnu99 -Wall -fPIC -malign-double -g -malign-stringops -msse4.2 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILE -O0 -DDEBUG -I/data/github/TDengine/src/inc -I/data/github/TDengine/src/os/linux/inc    -o CMakeFiles/tutil.dir/src/tglobalcfg.c.o   -c /data/github/TDengine/src/util/src/tglobalcfg.c
/usr/bin/cmake -E cmake_progress_report /data/github/TDengine/build/CMakeFiles 75
[ 13%] Building C object src/util/CMakeFiles/tutil.dir/src/ttypes.c.o
cd /data/github/TDengine/build/src/util && /usr/bin/cc  -DLINUX -DLITE -DTSDB_REPLICA_MAX_NUM=1 -DUSE_LIBICONV -D_LIBC_REENTRANT -D_M_X64 -D_REENTRANT -D__USE_POSIX -g -std=gnu99 -Wall -fPIC -malign-double -g -malign-stringops -msse4.2 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILE -O0 -DDEBUG -I/data/github/TDengine/src/inc -I/data/github/TDengine/src/os/linux/inc    -o CMakeFiles/tutil.dir/src/ttypes.c.o   -c /data/github/TDengine/src/util/src/ttypes.c
/usr/bin/cmake -E cmake_progress_report /data/github/TDengine/build/CMakeFiles
[ 13%] Building C object src/util/CMakeFiles/tutil.dir/src/tcache.c.o
cd /data/github/TDengine/build/src/util && /usr/bin/cc  -DLINUX -DLITE -DTSDB_REPLICA_MAX_NUM=1 -DUSE_LIBICONV -D_LIBC_REENTRANT -D_M_X64 -D_REENTRANT -D__USE_POSIX -g -std=gnu99 -Wall -fPIC -malign-double -g -malign-stringops -msse4.2 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILE -O0 -DDEBUG -I/data/github/TDengine/src/inc -I/data/github/TDengine/src/os/linux/inc    -o CMakeFiles/tutil.dir/src/tcache.c.o   -c /data/github/TDengine/src/util/src/tcache.c
/data/github/TDengine/src/util/src/tcache.c: In function 'taosUpdateCacheImpl':
/data/github/TDengine/src/util/src/tcache.c:511: warning: implicit declaration of function '__atomic_add_fetch'
/data/github/TDengine/src/util/src/tcache.c:511: error: '__ATOMIC_SEQ_CST' undeclared (first use in this function)
/data/github/TDengine/src/util/src/tcache.c:511: error: (Each undeclared identifier is reported only once
/data/github/TDengine/src/util/src/tcache.c:511: error: for each function it appears in.)
/data/github/TDengine/src/util/src/tcache.c: In function 'taosAddToCacheImpl':
/data/github/TDengine/src/util/src/tcache.c:553: error: '__ATOMIC_SEQ_CST' undeclared (first use in this function)
/data/github/TDengine/src/util/src/tcache.c: In function 'taosDecRef':
/data/github/TDengine/src/util/src/tcache.c:611: warning: implicit declaration of function '__atomic_sub_fetch'
/data/github/TDengine/src/util/src/tcache.c:611: error: '__ATOMIC_SEQ_CST' undeclared (first use in this function)
/data/github/TDengine/src/util/src/tcache.c: In function 'taosGetDataFromCache':
/data/github/TDengine/src/util/src/tcache.c:671: error: '__ATOMIC_SEQ_CST' undeclared (first use in this function)
make[2]: *** [src/util/CMakeFiles/tutil.dir/src/tcache.c.o] Error 1
make[2]: Leaving directory `/data/github/TDengine/build'
make[1]: *** [src/util/CMakeFiles/tutil.dir/all] Error 2
make[1]: Leaving directory `/data/github/TDengine/build'
make: *** [all] Error 2

**Comment by plum-lihui** [comment]
您的编译环境是什么系统呢？另外，您说下载的1.6.5.5版本的安装包后，运行也出现错误，也是在同样的系统上吗？

**Comment by plum-lihui** [comment]
gcc版本至少需要4.7以上才会支持__atomic_load_n((ptr), __ATOMIC_SEQ_CST)。

**Comment by plum-lihui** [comment]
原因是编译的gcc版本4.4.7。升级后，编译成功。
安装包运行的错误，应该系统中glibc库不匹配。

**Comment by stevel032** [comment]
Shouldn't we be able to detect such issues in our CMake file and report the error correctly?

**Comment by plum-lihui** [comment]
是的，应该在cmakelists中设置一个gcc版本号的限制。我找一下cmake的设置命令。
