### ISSUE TITLE
select count(*) from mysupertable cause taosd crashed

### ISSUE THREAD

**Issue by alon-zhong** [taosdata/TDengine#1243]
**Bug Description**
1.run sql "select count(*) from mysupertable” on server shell, taosd crashed
2.press Ctrl+C, get debug info:
^Ctaos: /home/ubuntu/release_workspace/TDinternal/community/src/client/src/tscServer.c:1159: tscRetrieveFromVnodeCallBack: Assertion `pState->numOfCompleted < pState->numOfTotal && pState->numOfCompleted >= 0 && pPObj->numOfSubs == pState->numOfTotal' failed.
taos: /home/ubuntu/release_workspace/TDinternal/community/src/client/src/tscServer.c:1159: tscRetrieveFromVnodeCallBack: Assertion `pState->numOfCompleted < pState->numOfTotal && pState->numOfCompleted >= 0 && pPObj->numOfSubs == pState->numOfTotal' failed.
Aborted

**Environment :
 - OS:  ubuntu 16.4
 - Memory 32G, CPU, current Disk Space 400G
 - TDengine Version: 1.6.5.5

**Comment by hjxilinx** [comment]
I have fixed the issue. You can pull the latest ver 1.6.5.5 and try again.

**Comment by LLCastle** [comment]
这个邮件怎么取消，构成骚扰了，谢谢！-------- 原始邮件 --------发件人： haojun Liao <notifications@github.com>日期： 2020年2月27日周四 21:47收件人： taosdata/TDengine <TDengine@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： Re: [taosdata/TDengine] select count(*) from mysupertable cause taosd crashed (#1243)Closed #1243.
