### ISSUE TITLE
taosBenchmark crash

### ISSUE THREAD

**Issue by xiaopingcs** [taosdata/TDengine#12433]
**Bug Description**
taosBenchmark crash

**To Reproduce**
1. Build taosd and taosBenchmark  in latest develop branch 
2. start taosd
3. taosBenchmark -f insert.json
`{
"filetype": "insert",
"cfgdir": "/etc/taos/",
"host": "127.0.0.1",
"port": 6030,
"user": "root",
"password": "taosdata",
"thread_count": 8,
"thread_count_create_tbl": 8,
"result_file": "./insert_res.txt",
"confirm_parameter_prompt": "no",
"insert_interval": 0,
"interlace_rows": 5,
"num_of_records_per_req": 50,
"databases": [
{
"dbinfo": {
"name": "db",
"drop": "yes",
"vgroups": 1
},
"super_tables": [
{
"name": "stb1",
"child_table_exists": "no",
"childtable_count": 80000,
"childtable_prefix": "stb1_",
"auto_create_table": "no",
"batch_create_tbl_num": 50000,
"data_source": "rand",
"insert_mode": "taosc",
"insert_rows": 10,
"interlace_rows": 5,
"insert_interval": 0,
"max_sql_len": 10000000,
"disorder_ratio": 0,
"disorder_range": 1000,
"timestamp_step": 10,
"sample_format": "csv",
"use_sample_ts": "no",
"tags_file": "",
"columns": [
{
"type": "INT"
},
{
"type": "DOUBLE",
"count": 100
},
{
"type": "BINARY",
"len": 400,
"count": 10
},
{
"type": "nchar",
"len": 200,
"count": 20
}
],
"tags": [
{
"type": "TINYINT",
"count": 2
},
{
"type": "BINARY",
"len": 16,
"count": 2
}
]
}
]
}
]
}`

**Expected Behavior**
taosBenchmark -f insert.json should not crash

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: [ubuntu 20.04]
 - TDengine Version [2.4.0.0]

**Additional Context**
N/A

**Comment by zhangbiyun** [comment]
I can not reproduce this issue. Could you hint some addtional information(eg. reproduce steps, crash error message).

**Comment by xiaopingcs** [comment]
> I can not reproduce this issue. Could you hint some addtional information(eg. reproduce steps, crash error message).

@zhangbiyun Thanks, this issue is not reproducible now, it should be fixed. Closing this issue.
