### ISSUE TITLE
fix issues in benchInsert.c

### ISSUE THREAD

**Issue by xiaopingcs** [taosdata/TDengine#12431]
**Bug Description**
fix issues in benchInsert.c found by Coverity Scan

**To Reproduce**
N/A

**Expected Behavior**
fix issues in benchInsert.c found by Coverity Scan
    Type                     Impack     File                                                                            function
1. Resource leak	High	TDengine/src/kit/taos-tools/src/benchInsert.c	startMultiThreadInsertData
2. Resource leak	High	TDengine/src/kit/taos-tools/src/benchInsert.c	startMultiThreadInsertData
3. Constant expression result	Medium	TDengine/src/kit/taos-tools/src/benchInsert.c	startMultiThreadInsertData
4. Resource leak	High	TDengine/src/kit/taos-tools/src/benchInsert.c	getSuperTableFromServer
5. Uninitialized scalar variable	High	TDengine/src/kit/taos-tools/src/benchInsert.c	execInsert
6. Dereference before null check	Medium	TDengine/src/kit/taos-tools/src/benchInsert.c	syncWriteProgressive

**Environment (please complete the following information):**
N/A

**Additional Context**
N/A

**Comment by fansehep** [comment]
please assign it to me, this my pr https://github.com/taosdata/taos-tools/pull/220

**Comment by fansehep** [comment]
And the pull request has been merge the develop(master) branch. https://github.com/taosdata/taos-tools/pull/221. but some problems i don't understand, if you can give me more important information about the problem. i think i can fix all.

**Comment by xiaopingcs** [comment]
> And the pull request has been merge the develop(master) branch. [taosdata/taos-tools#221](https://github.com/taosdata/taos-tools/pull/221). but some problems i don't understand, if you can give me more important information about the problem. i think i can fix all.

@fansehep Thanks for you PR, we will fix the rest issues.
