### ISSUE TITLE
taosBenchmark subscribe crash

### ISSUE THREAD

**Issue by xiaopingcs** [taosdata/TDengine#12434]
**Bug Description**
taosBenchmark subscribe crash

**To Reproduce**
1. Build taosd, taosBenchmark  in latest develop branch
2. go to 'TDengine/src/kit/taos-tools/example'
3. execute taosBenchmark -f insert_csv.json
4. execute taosBenchmark -f subscribe.json

**Expected Behavior**
taosBenchmark -f subscribe.json should not crash

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: [ubuntu 20.04]
 - TDengine Version [2.4.0.0]

**Additional Context**
taosBenchmark: /root/pxiao/TDengine/src/client/src/tscUtil.c:4194: doInitSubState: Assertion `pSql->subState.numOfSub == 0 && pSql->pSubs == NULL && pSql->subState.states == NULL' failed.

**Comment by gccgdb1234** [comment]
The PR has been merged, close this issue.
