### ISSUE TITLE
when  run a demo about  subscribe/cousume feature , Segmentation fault has  occurred. 

### ISSUE THREAD

**Issue by ben00007** [taosdata/TDengine#1244]
1. here is my code

```python
import taos
import pandas as pd
import tushare as ts

if __name__ == '__main__':
    conn = taos.connect(host="127.0.0.1", user="root", password="taosdata", database="db" , config="/etc/taos" )   
    # Generate a cursor object to run SQL commands
    sub = conn.subscribe(True, "test", "select * from t;", 1000)

    for i in range(0,10):
        data = sub.consume()
        for d in data:
            print(d)

    sub.close()
    conn.close()
```

Segmentation fault has  occurred. 

2. Environment
 - OS:  CentOS 7.5
 - Memory 16G , CPU 8core
 - TDengine Version  :community client version:1.6.5.5 community server version:1.6.5.5
- python Version 2.7

**Comment by ben00007** [comment]
not fix . the  issue  still exists

**Comment by localvar** [comment]
@ben00007 , could you please provide more information of this issue? for example: which line causes the crash? and it will be greate help if the call stack could be attached.

because, though the issue was mistakenly closed last night, the new commit fix it in my side, and I cannot reproduce it any more.

thanks.

**Comment by ben00007** [comment]
一. when  run a demo about subscribe/cousume feature ,  Segmentation fault info 
   version TDengine-server-1.6.5.5-Linux-x64.rpm   

"Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /usr/lib64/python2.7/site-packages/numpy/core/../.libs/libgfortran-ed201abd.so.3.0.0
Core was generated by `python testsub.py'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f05efe43057 in __strcpy_sse2_unaligned () from /lib64/libc.so.6
"
here is  code

import taos
import pandas as pd
if __name__ == '__main__':
    conn = taos.connect(host="127.0.0.1", user="root", password="taosdata", database="db" , config="/etc/taos" )   
    # Generate a cursor object to run SQL commands
    sub = conn.subscribe(True, "test", "select * from t;", 1000)

    for i in range(0,10):
        data = sub.consume()
        for d in data:
            print(d)

    sub.close()
    conn.close()


二. version fix1244  ，fix  the  above  issue ，but  maybe have  new issue that exec simple select sql  cause  segmentation fault   。new issue not exists in 1.6.5.5 version.

Core was generated by `python testsql.py'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f190d7ba697 in taos_fetch_fields (res=0x226cdd0) at /data/tdengine/compile/TDengine-develop/src/client/src/tscSql.c:319
319       return pQueryInfo->fieldsInfo.pFields;

here is   code 

import taos
import pandas as pd

if __name__ == '__main__':
    conn = taos.connect(host="127.0.0.1", user="root", password="taosdata", database="db" , config="/etc/taos" )
    sql = "SELECT * FROM t"
    df = pd.read_sql(sql, con=conn)
    print(df)

**Comment by ben00007** [comment]
Is the  subscribe/consume  feature  ok ?  try to  run  above  subscribe/consume  demo , when   insert data to table  t,   the  return  of sub.consume()  is  []  . don't  know where is  the problem . but don't have any error 。

**Comment by ben00007** [comment]
step1 :update  python to  python3.7，update  glibc to glibc.2.23,  update glibc to gcc 9.20.
step 2: reinstall taos1.6.5.5 verssion .
step 3: run taos client ,  
prompt the  information   ,it confuses  me
[root@ecs-f287 src]# taos
Usage: taos [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  about      Print information about Taos
  bio        Lookup Taos personell bio information.
  contact    Send a contact request to taos
  subscribe  Send a service subscription request to taos

**Comment by localvar** [comment]
@ben00007 , we are still investigating this issue, will get you updated if we have some progress.

**Comment by ben00007** [comment]
tks,  firstly tell me , which version is ok  about  basic   feature  and  sub/consume  feature   in any env.

**Comment by localvar** [comment]
you can `git checkout fdfcc4a` to verify the sub/consume feature, please note this is an intermediate version and other features may refuse to work.

**Comment by ben00007** [comment]
tks,   sub/consume feature   is ok    in fdfcc4a  version 。
