### ISSUE TITLE
select count(*)  query quantity problem

### ISSUE THREAD

**Issue by wuyupengcool** [taosdata/TDengine#12468]
select count(*) from tablename  如果未搜索到数据建议返回一行 数量为0 当前返回空行 ，造成 jdbc 搜索不便

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。
该特性已经在 3.x 中支持。
具体迁移操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
