### ISSUE TITLE
When using NodeJS, the more rows the query returns, the slower the query takes?

### ISSUE THREAD

**Issue by LeeonC** [taosdata/TDengine#12573]
![image](https://user-images.githubusercontent.com/64949066/168719219-26edea5e-a906-4485-9e02-e452af782bb8.png)
需要查询一段时间内符合条件的所有数据去做排序，现有的聚合函数不适用，只能通过查询所有数据进行计算。

**Comment by fenghuazzm** [comment]
咱们是什么版本？顺便贴一下表的结构吧，是不是有宽字符字段

**Comment by LeeonC** [comment]
好像和表结构没什么关系，我使用springboot+mybatis速度很快。但是用NodeJs的方式就会出现这样的问题。

**Comment by LeeonC** [comment]
是cusor.fetchall()效率太低了

**Comment by LeeonC** [comment]
是的，行数越多越慢。
SELECT * FROM scet_hb_mix.data_analysis  
where time BETWEEN ?   AND  ?     
AND (devId IN (?) OR stId IN (?)) 
AND value <> 0
用了cursor.query(sql,true);
也用了cursor.execute();用cursor.fetchall()接收结果慢。
看了源码就是cursor.fetchall()的时候慢。


> @LeeonC 查询吧的内容越多，返回的 越慢？

**Comment by LeeonC** [comment]
能修复这个问题吗，不行的话只能放弃用这个数据库了。

**Comment by xleili** [comment]
另外您在https://github.com/taosdata/TDengine/issues/12573#issuecomment-1128438358 提到用 springboot + mybaits 就很快。确实存在这种情况。我用java 也执行了上面这些查询这写sql，返回速度也是比nodejs 快。 java 用相同的方式去解析sql返回的data block的速度比nodejs 快很多。 所以还会有这种显现。
这应该是nodejs 语言的特性。

**Comment by LeeonC** [comment]
最后一个小小的问题，就是类似下面执行完query或execute之后的打印，是否可以去掉或做成一个参数项是否输出。监控数据插入的频次和频率本身就比较高，比较影响查看其它的输出。
Query OK, 1000 row(s) in set (0.28727220s)
Query OK, 10000 row(s) in set (3.02643780s)
Query OK, 20000 row(s) in set (6.04120150s)
Query OK, 50000 row(s) in set (15.18304630s)

**Comment by xleili** [comment]
> 最后一个小小的问题，就是类似下面执行完query或execute之后的打印，是否可以去掉或做成一个参数项是否输出。监控数据插入的频次和频率本身就比较高，比较影响查看其它的输出。 Query OK, 1000 row(s) in set (0.28727220s) Query OK, 10000 row(s) in set (3.02643780s) Query OK, 20000 row(s) in set (6.04120150s) Query OK, 50000 row(s) in set (15.18304630s)

这个可以实现，下次node 连接发版得时候，会把execute 和query 执行后的打印改成可配置项。用户自己选择打印或者不打印

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
