### ISSUE TITLE
java springboot mybatis  select count(*)  from table . 报错  invalid variables

### ISSUE THREAD

**Issue by xj1430688054** [taosdata/TDengine#12572]
taos
Welcome to the TDengine shell from Linux, Client Version:2.0.20.10
Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.
![image](https://user-images.githubusercontent.com/44515842/168716166-0437e33d-e2fd-4491-a9a2-365eeb86b8af.png)

error log 
![image](https://user-images.githubusercontent.com/44515842/168716206-9d0f4742-68a5-4cc3-8c66-afd0fc6b04d8.png)

code:
![image](https://user-images.githubusercontent.com/44515842/168716314-1ce835f7-093e-4eae-8f0d-6da3f20aae89.png)

dao:
![image](https://user-images.githubusercontent.com/44515842/168716352-bd2ccf86-e325-4739-922b-0ac27d2415da.png)

mapper
![image](https://user-images.githubusercontent.com/44515842/168716393-bc4e66e0-e443-4fdc-962f-55322c9a0ac6.png)

个人分析 ， select count(*) from table ， 或者select 1 from table limit 1 等sql， 因查询字段非数据库字段， 导致类型找不到报错

**Comment by xj1430688054** [comment]
我应该怎么解决这个问题，  模板程序来自  /usr/local/taos/examples/JDBC/springbootdemo  ，  测试过模板程序的select count(*) 也报错

**Comment by fenghuazzm** [comment]
你的 TDengine 及 jdbc-driver 的版本都太旧了，可以都更新到最新版本了再试试这个

**Comment by xj1430688054** [comment]
线上的版本是这个，  有很多数据， 我如何在保存数据的情况下进行更新版本。

**Comment by fenghuazzm** [comment]
> 线上的版本是这个， 有很多数据， 我如何在保存数据的情况下进行更新版本。

加我微信号：Deja_vu_4u
我发你详细步骤吧

**Comment by xj1430688054** [comment]
已解决， 5*评价

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
