### ISSUE TITLE
The last,first functions failed in the select statement. This problem arises in 2.4.0.16. But 2.4.07 is good

### ISSUE THREAD

**Issue by zhonghuali** [taosdata/TDengine#12589]
**Bug Description**
选择函数last,first无法在select语句中使用,
一个错误出现"invalid operation: invalid arithmetic expression in select clause"

**To Reproduce**
1. 准备环境2.4.0.16和2.4.07的docker tdengine sever
2. 分别执行如下语句:
select last(cpu_system)-first(cpu_system) from log.dnode_1 where (ts>=now-30d) and ts< now interval(1d)

4. 在版本2.4.0.16,得到如下错误:"invalid operation: invalid arithmetic expression in select clause"

当在低版本2.4.07,可以得到结果如下:
![e656d6461fcb414223627a2eda41c63](https://user-images.githubusercontent.com/8972381/168787414-a9f482e8-7577-49fa-9d36-e828a2247f1c.png)

**Expected Behavior**
work as before

**Screenshots**

**Environment (please complete the following information):**
 - OS: tdengine office docker image
 - Memory, CPU, current Disk Space
 - TDengine Version [2.4.0.16 and 2.4.07]

**Additional Context**

**Comment by fenghuazzm** [comment]
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/70138133/170219498-b5ea5c9b-b077-422b-b98c-2ac5df6785a3.png">
我在 2.4.0.20 上试着是能用的

**Comment by zhouyf605** [comment]
2.4.0.10 上面不行

**Comment by zhonghuali** [comment]
verified ,it work fine in tdengine/tdengine:2.4.0.25

**Comment by zhonghuali** [comment]
Hi ,it's unfortunately the data returned still not correct in 2.4.0.25. I tested the follow sqls in tdengine log schema. 
1. select last(mem_system)-first(mem_system) from log.dn where (ts>=now-30d) and ts< now interval(1d)
the returned resutl: all values are zero. 
{ "res": true, "count": 31, "data": [ { "ts": "2022-05-10 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-05-11 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-05-12 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-05-13 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-05-14 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-05-15 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-05-16 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-05-17 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-05-18 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-05-19 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-05-20 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-05-21 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-05-22 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-05-23 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-05-24 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-05-25 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-05-26 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-05-27 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-05-28 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-05-29 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-05-30 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-05-31 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-06-01 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-06-02 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-06-03 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-06-04 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-06-05 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-06-06 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-06-07 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-06-08 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 }, { "ts": "2022-06-09 00:00:00.000000", "last(mem_system)-first(mem_system)": 0 } ] }

but the acutal Difference value is not same . please the snapshot:
![image](https://user-images.githubusercontent.com/8972381/172811278-02335ea1-bf6e-4d21-ab33-d14cf818ca96.png)

2. select last(band_speed)-first(band_speed) from log.dn where (ts>=now-30d) and ts< now interval(1d)
the returned resutl: all values are zero. 

{ "res": true, "count": 31, "data": [ { "ts": "2022-05-10 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-05-11 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-05-12 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-05-13 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-05-14 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-05-15 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-05-16 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-05-17 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-05-18 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-05-19 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-05-20 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-05-21 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-05-22 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-05-23 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-05-24 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-05-25 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-05-26 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-05-27 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-05-28 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-05-29 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-05-30 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-05-31 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-06-01 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-06-02 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-06-03 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-06-04 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-06-05 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-06-06 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-06-07 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-06-08 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 }, { "ts": "2022-06-09 00:00:00.000000", "last(band_speed)-first(band_speed)": 0 } ] }

but the acutal Difference value is not same . please the snapshot:
![image](https://user-images.githubusercontent.com/8972381/172811434-b65fd900-1210-46ca-87de-94afb1daf439.png)

**Comment by fenghuazzm** [comment]
感谢反馈，first、last 进行四则运算的这个问题我们看下

**Comment by zhonghuali** [comment]
Hello, Can anyone tell when and which branch this bug would be fixed ?

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
