### ISSUE TITLE
在查询一列的在一个时间段内的增量值时候,报错 invalid operation: invalid arithmetic expression in select clause.

### ISSUE THREAD

**Issue by zhonghuali** [taosdata/TDengine#12588]
question:
如何查询一列的在一个时间段内的增量值?
比如设备上报的功率是累计功率,存入库里后,需要计算一天,一个月的功率增量是多少.
我用如下的sql:
select last(actEnergy)-first(actEnergy) from device_01040332220106000181 where (ts>=now-30d) and ts< now interval(1d)
无法执行,报错 invalid operation: invalid arithmetic expression in select clause.

看起来select不支持last ,first 的计算. 这个应该是可以的吧
正确的sql应该如何使用?
谢谢

**Comment by zhonghuali** [comment]
这个错误在2.4.0.16发现的.在2.4.07是好的.这应该是个bug

**Comment by fenghuazzm** [comment]
> 
我在 2.4.0.20 上试着也可以做计算
