### ISSUE TITLE
Is there any limitation on the data size of community version?

### ISSUE THREAD

**Issue by thisisrui** [taosdata/TDengine#1258]
社区版单表数据量是否有上限，上限是多少，超过上限会怎样？

**Comment by liu0x54** [comment]
There is no limitation on data size. There is only a limitation on how long the data will be stored on the disk and it's decided by the configuration of 'keep' arguments when create database.
Another limitation related to the data size is the numbers of columns of a table, that is total 256 columns including values and tags.
