### ISSUE TITLE
Hope the topN function support "group by" operation

### ISSUE THREAD

**Issue by lqju** [taosdata/TDengine#1260]
背景：
对分组查询的数据排序，取前N条做展示。类似mysql的：group by filed1 order by count limit 10.

**Comment by hjxilinx** [comment]
您说的是针对普通列的group by是吗？

**Comment by lqju** [comment]
是的。

**Comment by lqju** [comment]
> 您说的是针对普通列的group by是吗？

是的。针对超级表的tags列做group by，然后取topN。

**Comment by Shawshank-Smile** [comment]
Not supported yet, group by tag is supported.
