### ISSUE TITLE
When TDengine and mysql are configured as dual data sources and tags syntax is used, incompatible errors are reported

### ISSUE THREAD

**Issue by lchuai2018** [taosdata/TDengine#12618]
![Dingtalk_20220517234930](https://user-images.githubusercontent.com/36941817/168854378-28483973-ca0e-4de1-a6d6-916d8859e65f.jpg)

### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'tags
        (
        erpSku nchar
        (
            64
        ),
        ' at line 19
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'tags
        (
        erpSku nchar
        (
            64
        ),
        ' at line 19

**Comment by springbootyp** [comment]
请问你解决了嘛 出现同样的问题

**Comment by yu285** [comment]
没有版本信息无法进行问题判断。

另外 2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
