### ISSUE TITLE
RPC ERROR SHELL    reason:No such file or directory

### ISSUE THREAD

**Issue by liqilong2017** [taosdata/TDengine#12624]
版本：2.0.9.1

05/14 00:50:18.134974 0x7f30bb7fe700 RPC ERROR SHELL 0x2057048 0x1112, failed to send, msgLen:96 written:-1, reason:No such file or directory
05/14 04:30:22.160282 0x7f30afffb700 RPC ERROR SHELL 0x20617b8 0x75, failed to send, msgLen:96 written:-1, reason:No such file or directory
05/14 07:00:18.165008 0x7f30afffb700 RPC ERROR SHELL 0x2068468 0x2cea, failed to send, msgLen:96 written:-1, reason:No such file or directory
05/14 10:50:20.104454 0x7f3056ffd700 RPC ERROR SHELL 0x206e9c0 0x248, failed to send, msgLen:1518 written:-1, reason:Success
05/14 11:00:22.156334 0x7f30afffb700 RPC ERROR SHELL 0x206ee28 0xa2, failed to send, msgLen:96 written:-1, reason:No such file or directory
05/14 12:10:18.110279 0x7f30bb7fe700 RPC ERROR SHELL 0x206f9e8 0x286, failed to send, msgLen:96 written:-1, reason:No such file or directory
05/16 09:00:21.070091 0x7f30c2ffd700 RPC ERROR SHELL 0x20287a0 0x5, failed to send, msgLen:1518 written:-1, reason:Success
05/16 09:14:08.288291 0x7f30c17fa700 RPC ERROR SHELL 0x202a500 0x16a, failed to send, msgLen:96 written:-1, reason:No such file or directory
05/16 09:53:30.616840 0x7f30bb7fe700 RPC ERROR SHELL 0x2031bf8 0x8e, failed to send, msgLen:96 written:-1, reason:No such file or directory
05/16 09:55:36.277033 0x7f30c2ffd700 RPC ERROR SHELL 0x2031d70 0x12, failed to send, msgLen:1518 written:-1, reason:Success
05/16 17:18:08.750109 0x7f30c2ffd700 MND ERROR msg:0x7f3038000a60, app:0xd table:0.saas.var_id_2, failed to get table meta, table not exist
05/16 17:19:22.583733 0x7f3056ffd700 MND ERROR msg:0x7f3038000a60, app:0x6 table:0.saas.var_id_2, failed to get table meta, table not exist
05/16 17:33:29.600532 0x7f30c2ffd700 RPC ERROR SHELL 0x203a028 0x4bde, failed to send, msgLen:2428 written:-1, reason:Success
05/17 08:30:22.153586 0x7f30c0ff9700 RPC ERROR SHELL 0x20e5ab8 0xd7, failed to send, msgLen:96 written:-1, reason:No such file or directory
05/17 08:50:22.158839 0x7f30afffb700 RPC ERROR SHELL 0x20e5da8 0xad, failed to send, msgLen:96 written:-1, reason:No such file or director

数据是从其他环境导进去的、然后日志里会有这种报错；然后 执行show queries 的结果 如下：
![image](https://user-images.githubusercontent.com/36256621/168937936-e2595cec-e7b7-4193-baa5-886cccca7c5c.png)

请协助排查、谢谢

**Comment by fenghuazzm** [comment]
报这个错是伴随着有什么现象呢？

**Comment by liqilong2017** [comment]
业务侧 一直在等这个 SQL 执行结果、不能继续执行；
show queries; 查询出来的SQL、我直接复制出来、可以直接运行；

**Comment by liqilong2017** [comment]
业务侧 一直在等这个 SQL 执行结果、不能继续执行；
show queries; 查询出来的SQL、我直接复制出来、可以直接运行；

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
