### ISSUE TITLE
How to change the server ip？

### ISSUE THREAD

**Issue by wsf1990** [taosdata/TDengine#1262]
I have a phisical server,which has two ip, one is public and another is local. I found my taosd service bind the public ip. When I use `netstat` to check 6020 port,which shows its bind to 0.0.0.0. Now I want to change the ip to local. But even I set all of the `intervalIp` and `publicIp` and `privateIp` in `/etc/taos/taos.cfg` to my local ip. I still can connect the server use local ip and public ip.

So how can I configure the server's connect ip? my taos version is 1.6.5.3.

**Comment by liu0x54** [comment]
The community version TDengine currently does not limit the ingress IP to the configured IP. You can connect to TDengine only if you can connect to the server, no matter from which IP.
