### ISSUE TITLE
Need a new sql grammar to modify table's multiple tags value

### ISSUE THREAD

**Issue by MrAccle** [taosdata/TDengine#12659]
**Is your feature request related to a problem? Please describe.**
I have a business scenario for modify table's multiple tag value. But i can't find the sql to realize this scenario in official document.
So that i need to execute this  **"ALTER TABLE tb_name SET TAG tag_name=new_tag_value;"** sql multiple times. 

**Describe your desired behavior**
Need a new sql grammar to modify table's multiple tags value

**Describe your solutions/suggestions if you've any**
new a sql grammar like this.
![image](https://user-images.githubusercontent.com/25242380/169017608-c1cddcfb-109f-4d8c-b1a8-97ff0d45bbed.png)

**Additional context**

**Comment by fenghuazzm** [comment]
Hello , TDengine can only alter one at a time currently.
Thank you for your feedback. We will follow up this issue later .

**Comment by MrAccle** [comment]
thx
