### ISSUE TITLE
What's the difference between the connection pool for TDengine and for other Database? How to use the connection pool in case nodejs connecting to TDengine？

### ISSUE THREAD

**Issue by housheng4** [taosdata/TDengine#1265]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the circumstance is and what the associated problem is. Ex. I'm using TDengine for this use case: [...]. But I'm always frustrated when [...]

**Describe your desired behavior**
A clear and concise description of what you want to happen. Ex. I want TDengine to be able to do [...] when I try to do [...] with it.

**Describe your solutions/suggestions if you've any**
A clear and concise description of any solutions/suggestions to this problem or features you've considered.

**Additional context**

**Comment by liu0x54** [comment]
There's a connection pool inside the TDengine, so the application doesn't need a third party connection pool to connecting TDengine, just choose the connector provide by TDengine accordingly.

**Comment by housheng4** [comment]
> TDengine内部有一个连接池，因此应用程序不需要第三方连接池来连接TDengine，只需相应地选择TDengine提供的连接器即可。

但是没有在nodejs连接器中看到类似其他数据库的createpool函数呀，请问下tdengine的连接池接口在哪里？

**Comment by liu0x54** [comment]
> > TDengine内部有一个连接池，因此应用程序不需要第三方连接池来连接TDengine，只需相应地选择TDengine提供的连接器即可。
> 
> 但是没有在nodejs连接器中看到类似其他数据库的createpool函数呀，请问下tdengine的连接池接口在哪里？
不用考虑pool的事情，直接建立连接，然后保持这个连接，写入查询的的时候复用就行

**Comment by housheng4** [comment]
> > > TDengine内部有一个连接池，因此应用程序不需要第三方连接池来连接TDengine，只需相应地选择TDengine提供的连接器即可。
> > 
> > 
> > 但是没有在nodejs连接器中看到类似的其他数据库的创建池函数呀，请问下tdengine的连接池接口在哪里？
> > 不用考虑池的事情，直接建立连接，然后保持这个连接，写入查询的时间间隔就行

恩，明白了。非常感谢您的解答
