### ISSUE TITLE
taosdump backup super table data volume is incorrect

### ISSUE THREAD

**Issue by 2779382063** [taosdata/TDengine#12654]
I have a 3-node cluster, a power library(3replica, precision us), and only one meter super table. All sub-tables in it are created based on the meters super table, and a total of 30 million data has been written. . The data from taosdump power meters -o /usr/local/taosd/backup is less than 30 million, and the number of rows of data from each dump is different, may I ask why?

Version：2.4.0.18

there is an error： cat /var/log/taos/taosdlog.0 

05/18 16:14:26.101386 00007219 VND ERROR vgId:307, invalid qId in retrieving result, code:Invalid handle, QInfo:54402400145097924
05/18 16:14:38.594190 00007223 VND ERROR vgId:297, invalid qId in retrieving result, code:Invalid handle, QInfo:54402400149668193
05/18 16:27:11.182363 00007236 DND user:root, send auth msg to mnodes
05/18 16:27:11.182687 00007237 DND user:root, send auth msg to mnodes
05/18 16:27:11.184235 00007236 DND user:root, auth msg received from mnodes
05/18 16:27:11.184281 00007237 DND user:root, auth msg received from mnodes
05/18 16:27:11.184358 00007236 DND user:root, send auth msg to mnodes
05/18 16:27:11.184386 00007237 DND user:root, send auth msg to mnodes
05/18 16:27:11.186876 00007236 DND user:root, auth msg received from mnodes
05/18 16:27:11.186947 00007236 DND user:root, send auth msg to mnodes
05/18 16:27:11.186969 00007237 DND user:root, auth msg received from mnodes
05/18 16:27:11.187080 00007237 DND user:root, send auth msg to mnodes
05/18 16:27:11.187854 00007236 DND user:root, auth msg received from mnodes
05/18 16:27:11.189309 00007237 DND user:root, auth msg received from mnodes
05/18 16:27:12.281791 00007236 DND user:root, send auth msg to mnodes
05/18 16:27:12.281847 00007237 DND user:root, send auth msg to mnodes
05/18 16:27:12.282224 00007236 DND user:root, auth msg received from mnodes
05/18 16:27:12.282231 00007237 DND user:root, auth msg received from mnodes
05/18 16:28:07.927753 00007236 DND user:root, send auth msg to mnodes
05/18 16:28:07.927881 00007237 DND user:root, send auth msg to mnodes
05/18 16:28:07.931261 00007236 DND user:root, auth msg received from mnodes
05/18 16:28:07.931341 00007237 DND user:root, auth msg received from mnodes
05/18 16:28:07.958980 00007237 DND user:root, send auth msg to mnodes
05/18 16:28:07.959075 00007236 DND user:root, send auth msg to mnodes
05/18 16:28:07.959904 00007237 DND user:root, auth msg received from mnodes
05/18 16:28:07.959927 00007236 DND user:root, auth msg received from mnodes
05/18 16:28:07.960012 00007236 DND user:root, send auth msg to mnodes
05/18 16:28:07.960570 00007237 DND user:root, send auth msg to mnodes
05/18 16:28:07.961301 00007236 DND user:root, auth msg received from mnodes
05/18 16:28:07.961318 00007237 DND user:root, auth msg received from mnodes
05/18 16:28:08.402459 00007236 DND user:root, send auth msg to mnodes
05/18 16:28:08.403177 00007236 DND user:root, auth msg received from mnodes
05/18 16:29:05.037307 00007219 VND ERROR vgId:297, invalid qId in retrieving result, code:Invalid handle, QInfo:54402401923177384

**Comment by 2779382063** [comment]
taosdump version 1.4.2-2-g9815e30_b269ee2

**Comment by hufeng-tany** [comment]
这。。。。我刚想用这个功能做冷备，看来可以先放一放了

**Comment by fenghuazzm** [comment]
> 

和这位用户交流了，他的数据量非常多，taosdump 读取数据的时候执行超时了。修改超时参数后就没了问题，你可以先试试，有问题我再帮你看。

**Comment by fenghuazzm** [comment]
> 这。。。。我刚想用这个功能做冷备，看来可以先放一放了

和这位用户交流了，他的数据量非常多，taosdump 读取数据的时候执行超时了。修改超时参数后就没了问题，你可以先试试，有问题我再帮你看。
