### ISSUE TITLE
windows failed to connect to server

### ISSUE THREAD

**Issue by daxiabiluo** [taosdata/TDengine#1269]
1.我编译了一个arm版本的taosd和taos，在arm板上能正常连接
2.直接在windows上安装了TDengine-client-1.6.5.5-Windows-x64.exe，然后taos.exe -h 服务器IP，连接失败
3.客户端log信息如下：
02/27 17:23:45.211000 0x7324 UTL  gitinfo:                3264067e97300c84caa61ac909d548c9ca56de6b 
02/27 17:23:45.211000 0x7324 UTL  gitinfoOfInternal:      da88f4a2474737d1f9c76adcf0ff7fd0975e7342 
02/27 17:23:45.211000 0x7324 UTL  buildinfo:              Built by root at 2020-02-05 14:38 
02/27 17:23:45.211000 0x7324 UTL  version:                1.6.5.4 
02/27 17:23:45.211000 0x7324 UTL  dataDir:                C:/TDengine/data
02/27 17:23:45.211000 0x7324 UTL ==================================
02/27 17:23:45.218000 0x14076 ERROR RPC TSC-mgmt msg is messed up, dataLen:116 processedLen:0 count:0 msgLen:32
02/27 17:23:45.518000 0x14076 ERROR RPC TSC-mgmt msg is messed up, dataLen:116 processedLen:0 count:0 msgLen:32
02/27 17:23:46.118000 0x14076 ERROR RPC TSC-mgmt msg is messed up, dataLen:116 processedLen:0 count:0 msgLen:32
02/27 17:23:47.318000 0x14076 ERROR RPC TSC-mgmt msg is messed up, dataLen:116 processedLen:0 count:0 msgLen:32
02/27 17:23:49.718000 0x14076 ERROR RPC TSC-mgmt msg is messed up, dataLen:116 processedLen:0 count:0 msgLen:32
02/27 17:23:50.018000 0x14076 ERROR RPC TSC-mgmt msg is messed up, dataLen:116 processedLen:0 count:0 msgLen:32
02/27 17:23:50.618000 0x14076 ERROR RPC TSC-mgmt msg is messed up, dataLen:116 processedLen:0 count:0 msgLen:32
02/27 17:23:51.818000 0x14076 ERROR RPC TSC-mgmt msg is messed up, dataLen:116 processedLen:0 count:0 msgLen:32

**Comment by shitoupai** [comment]
跟我的类似。

客户端不能连接远程的数据库，本地可以【客户端，服务器都是linux】

服务器端日志：
02/28 12:13:11.504414 1046 7f081490b700 ERROR RPC MND-shell msg is messed up, dataLen:185 processedLen:0 count:0 msgLen:0
02/28 12:13:11.806505 1046 7f081490b700 ERROR RPC MND-shell msg is messed up, dataLen:185 processedLen:0 count:0 msgLen:0
02/28 12:13:12.406726 1046 7f081490b700 ERROR RPC MND-shell msg is messed up, dataLen:185 processedLen:0 count:0 msgLen:0

客户端日志：
02/29 01:06:18.573813 7f5f2fd1e700 ERROR TSC 0x99c490 reach the max retry:2, code:29

**Comment by plum-lihui** [comment]
arm板子是64位的，还是32位的？   
x64的windows与arm的互通还没有验证过。

**Comment by daxiabiluo** [comment]
arm是32位的。
然后我昨天还做了个测试：在64位虚拟机上安装了服务端，用arm板的客户端可以连接成功，但是用windows服务端连接失败，日志信息和之前发的一致

**Comment by plum-lihui** [comment]
从这个日志看，估计是两端对消息结构的处理不一致。

**Comment by daxiabiluo** [comment]
又进行了一次测试，发现之前的说法不对：arm板也不能正常连接到64位虚拟机上的服务端（通过deb安装）。
之前觉得能连接成功是因为在arm板上运行./taos -h 192.168.0.48会弹出taos>，但是今天才发现用这个命令连接到的服务器还是本地的服务器，查询到的数据都是本地的。
将本地taosd停止之后再运行./taos -h 192.168.0.48，打印Failed to check Server Edition, Reason:29:failed to connect to server

如果是“两端对消息结构的处理不一致”，请问怎么解决

**Comment by daxiabiluo** [comment]
用两台电脑虚拟机安装了TDengine-server-1.6.5.5-Linux-x64.deb，可以相互连接成功，但是用windows还是连接失败DB error: failed to connect to server

**Comment by plum-lihui** [comment]
1、arm版本 与  x64版本的互通的计划，比较靠后，暂时还没法解决。
2、windows链接失败，看一下是不是版本不匹配（客户端和服务端的版本必须一致）、以及防火墙是否有影响？可以排查一下。

**Comment by daxiabiluo** [comment]
虚拟机上的版本是1.6.5.5，windows上安装的是TDengine-client-1.6.5.5-Windows-x64.exe，但是显示client版本是1.6.5.4
刚在官网重新下载了个TDengine-client-1.6.5.5-Windows-x64.exe，现在windows可以正常连接上虚拟机了
