### ISSUE TITLE
Ts primary key time column cannot use like

### ISSUE THREAD

**Issue by hufeng-tany** [taosdata/TDengine#12728]
我的版本2.2.0.5
若使用主键ts，作为where 条件中，ts like 。。
就会报错，请问为何ts 列不能作为like的条件列呢？？？？？

**Comment by lrzl** [comment]
ts列是时间类型吧？字符串才支持like

**Comment by hufeng-tany** [comment]
你好！你的邮件我已经收到，我会尽快查看
胡峰
