### ISSUE TITLE
After the TDengine is connected in RESTful mode and SQL is executed, an error occurs in the query table：Table does not exist

### ISSUE THREAD

**Issue by Mitsuhazxy** [taosdata/TDengine#12732]
使用RESTful方式连接到TDEngine，使用Druid生成DataSource，新建JdbcTemplate执行excute(sql)建表语句，客户端内可以查到该表，查询表结构和表数据提示Table does not exist。

1.Druid版本1.2.6
2.SpringBoot版本2.1.4
3.TDEngine版本2.4.0.14

![image](https://user-images.githubusercontent.com/40455446/169434358-241b41c7-1058-4621-84b3-faef3f3307a1.png)

![image](https://user-images.githubusercontent.com/40455446/169434414-415cd48f-d410-43b2-8b3c-a891e6f2bcbc.png)

**Comment by Mitsuhazxy** [comment]
有能解决一下嘛

**Comment by fenghuazzm** [comment]
感觉是元数据出现了不同步，可以加陈工微信：a15652223354
他给你远程调试一下

**Comment by codenergy** [comment]
2.2.2.10版本也遇到了，偶发性，这个到底咋回事

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
