### ISSUE TITLE
DB error: invalid operation: not support column types

### ISSUE THREAD

**Issue by lrzl** [taosdata/TDengine#12737]
**Bug Description**
使用INTERP函数出现not support column types问题

**To Reproduce**
1. 创建unittest库 `
CREATE DATABASE IF NOT EXISTS unittest REPLICA 1 QUORUM 1 DAYS 10 KEEP 3650 CACHE 16 BLOCKS 6 MINROWS 100 MAXROWS 4096 FSYNC 3000 CACHELAST 0 COMP 2 PRECISION 'ms' UPDATE 0;
`
2. 创建超级表： `CREATE STABLE IF NOT EXISTS wind (ts TIMESTAMP,direction DOUBLE,speed DOUBLE) TAGS(sensor NCHAR(32),city NCHAR(32))`
3. 导入数据，见附件[taos.zip](https://github.com/taosdata/TDengine/files/8735707/taos.zip)
4. 执行sql语句：   `SELECT INTERP (*) FROM wind;`  或 `SELECT INTERP (*) FROM wind EVERY(5s) FILL(NEXT);`
出现错误: DB error: invalid operation: not support column types
**Screenshots**
![image](https://user-images.githubusercontent.com/32292315/169445234-87217ff1-612a-491e-a4a3-bb2087442cf2.png)

**Environment (please complete the following information):**
 - OS: archlinux 和 centos7.8 都尝试过
 - TDengine Version 2.4.0.20

**Comment by fenghuazzm** [comment]
INTERP 只能对数值字段使用呢，可以将 * 换为具体数值字段试试

**Comment by lrzl** [comment]
> INTERP 只能对数值字段使用呢，可以将 * 换为具体数值字段试试

用单个数值型字段会出现这个问题：`SELECT INTERP(speed) FROM wind EVERY(5s) FILL(NEXT);`

![image](https://user-images.githubusercontent.com/32292315/169457753-3660fc50-9e34-4841-a7fa-5a2da0fcbcc4.png)

DB error: invalid operation: TWA/Diff/Derivative/Irate/CSUM/MAVG/SAMPLE/INTERP/Elapsed are not allowed to apply to super table directly (0.004709s)

另外之前INTERP (*)写法在2.2.2.10版本都挺好的，为什么到2.4.0.20就不支持了？我看文档并没有说对这个有变动

**Comment by fenghuazzm** [comment]
文档里面有分两个版本的用法，是有区别了，可以详细看下文档。
