### ISSUE TITLE
一秒内无法插入多条数据，即使毫秒数改变也不行

### ISSUE THREAD

**Issue by ekinjohn** [taosdata/TDengine#1275]

**Comment by plum-lihui** [comment]
请将插入的sql语句贴出来，我们分析一下。
多谢！

**Comment by ekinjohn** [comment]
import INTO d_sensor123456789000002 USING d_sensor TAGS('123456789000002') (ts,sessionid,seq,longitude,latitude,speed,accx,accy,accz,gyrox,gyroy,gyroz,extra) VALUES ('2020-02-29 05:32:25:162','123456789000002', 1,0,0,0,1136,-711,5318,653,439,-1030,'null');
