### ISSUE TITLE
Using `taos` command to exec `SHOW CREATE DATABASE db_name;`, bash return ellipsis.

### ISSUE THREAD

**Issue by woorui** [taosdata/TDengine#12760]
**Bug Description**
Using `taos` command to exec `SHOW CREATE DATABASE db_name;`, bash return the incomplete statement with ellipsis.

**To Reproduce**
1. create a databse.
2. exec `SHOW CREATE DATABASE db_name;`

**Expected Behavior**
return the complete sql statement.

**Screenshots**
```
taos> SHOW CREATE DATABASE db_name;
            Database            |        Create Database         |
==================================================================
 server_event                   | CREATE DATABASE db_nam... |
Query OK, 1 row(s) in set (0.016727s)
```

**Environment (please complete the following information):**
 - taos version: 2.4.0.12

**Comment by fenghuazzm** [comment]
SHOW CREATE DATABASE db_name\G;
The statement will display completely.
