### ISSUE TITLE
Question about Interval function

### ISSUE THREAD

**Issue by ilylx** [taosdata/TDengine#12828]
比如按设备ID分表，

SELECT first(current) FROM meters INTERVAL(10s);

这种查询结果，怎么知道每个记录都是哪个设备的?

**Comment by fenghuazzm** [comment]
若是用子表名来区分可以这样：
SELECT first(current),tbname FROM meters INTERVAL(10s);

**Comment by ilylx** [comment]
SELECT first(*),tbname FROM meters INTERVAL(10s);  
这样不行

**Comment by ilylx** [comment]
@fenghuazzm 有没有什么变通的方法实现？

**Comment by ilylx** [comment]
![0402b2d1032ce8e2b5ffd35d36f83e9](https://user-images.githubusercontent.com/83160341/169733877-089ae183-a373-44ea-94e1-625968cbb526.png)
