### ISSUE TITLE
count(*) millions of data queries are slow

### ISSUE THREAD

**Issue by helloxdan** [taosdata/TDengine#12823]
环境：window WSL Ubuntu-20.0.4   
版本：TDengine-server-2.4.0.16-Linux-x64
单节点
硬件：thinkpad 笔记本，i7，4核，32G内存

问题：
1）几百万数据要查一分钟，可能是什么原因。是安装环境问题？ 

taos> show dnodes;
   id   |           end_point            | vnodes | cores  |   status   | role  |       create_time       |      offline reason      | 
      1 | xdan.localdomain:6030          |     13 |      8 | ready      | any   | 2022-04-17 15:20:26.454 |                          |
Query OK, 1 row(s) in set (0.075000s)

taos> show vgroups;
    vgId     |   tables    |  status  |   onlines   | v1_dnode | v1_status | compacting  | 
           7 |        4000 | ready    |           1 |        1 | master    |           0 |
           8 |        4000 | ready    |           1 |        1 | master    |           0 |
           9 |        3250 | ready    |           1 |        1 | master    |           0 |
          10 |        3000 | ready    |           1 |        1 | master    |           0 |
          14 |        3000 | ready    |           1 |        1 | master    |           0 |
          15 |        3000 | ready    |           1 |        1 | master    |           0 |
          16 |        3000 | ready    |           1 |        1 | master    |           0 |
          17 |        3000 | ready    |           1 |        1 | master    |           0 |
Query OK, 8 row(s) in set (0.149000s)

taos> select count(trade_date) from stock_daily;
   count(trade_date)   | 
               **5186586** |
Query OK, 1 row(s) in set (**56.357000s**)

**Comment by helloxdan** [comment]
超级表，有4800个子表
  desc stock_daily;
             Field              |         Type         |   Length    |   Note   |
=================================================================================
 trade_date                     | TIMESTAMP            |           8 |          |
 open                           | FLOAT                |           4 |          |
 high                           | FLOAT                |           4 |          |
 low                            | FLOAT                |           4 |          |
 close                          | FLOAT                |           4 |          |
 pre_close                      | FLOAT                |           4 |          |
 change                         | FLOAT                |           4 |          |
 pct_chg                        | FLOAT                |           4 |          |
 vol                            | FLOAT                |           4 |          |
 amount                         | FLOAT                |           4 |          |
 adj_factor                     | FLOAT                |           4 |          |
 ts_code                        | NCHAR                |          15 | TAG      |

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
