### ISSUE TITLE
The Windows client does not support the -p argument to input password 

### ISSUE THREAD

**Issue by xiaodongde** [taosdata/TDengine#1282]
C:\TDengine>taos -h 139.8.56.34 -p abc123
wrong options
taos shell is used to test the TDEngine database

**Comment by plum-lihui** [comment]
需要指定用户，比如使用root登录：
c:\TDengine> taos -h 139.8.56.34 -u root -p 回车
Welcome to the TDengine shell from windows， client version：1.6.5.5 Enter password：
然后输入密码就可以了

**Comment by xiaodongde** [comment]
OK
