### ISSUE TITLE
windows docker tdengine  + c client can‘t work

### ISSUE THREAD

**Issue by arilink** [taosdata/TDengine#12867]
1.windows 10安装了docker 并且参考https://docs.taosdata.com/train-faq/docker 部署了TDengine
2.TDengine gui可以正常操作
3.服务端启动 taosd | grep -i fqdn     cat /var/lib/taos/dnode/dnodeEps.json 结果为tdengine-server
4.windows/System32/drivers/etc/hosts 里增加 192.168.0.122 tdengine-server
5.ping tdengine-server 成功
6.调整防火墙设置 增加入站规则 tcp/udp 对应的端口也开启了
7.客户端可以连接  但是无法新建表格 插入数据

**Comment by arilink** [comment]
8.在windows上安装了taosc  show database等一系列操作都是正常的 并且使用TDengineGUI也是可以正常连接到数据库 说明TDengine的整个环境部署是正常的
9.我使用QT+mingw开发 调用taos.dll动态库 项目中引入了tao.h 和taoserror.h  使用taos_connect()可以正常连接 但是后续的建库 建表 插入数据都无法正常操作 要么提示Unable to establish connection 要么提示database已存在
10.因为TDengine默认是采用的同步操作，所以我尝试在线程中执行写入操作 问题依然存在

**Comment by Sejon** [comment]
我也遇到这个问题，解决了吗

**Comment by yu285** [comment]
> 
可以添加微信 15652223354 做具体排查
