### ISSUE TITLE
The count() function returns Null when zero data is found

### ISSUE THREAD

**Issue by ohXiaoMing996** [taosdata/TDengine#12861]
查询数据时报异常，通过排查 发现时 某一个查询 在使用 count(*) 时 查询到 0 条数据 ，而返回类型定义的为 integer 所以 返回了 Null 因此 赋值给 Int 时 报了 异常

**Comment by ljluestc** [comment]
在Tdengine中，当查询结果中没有匹配的数据时，count()函数会返回Null。这是设计上的行为。

当你使用count(*)函数查询表中的行数或特定条件的结果时，如果没有找到匹配的行，count()函数将返回Null，而不是零。这是为了区分实际的计数为零和查询结果为空或未定义的情况。

如果你将count()的结果赋值给一个整数变量，确保处理Null值的可能性。你可以使用条件语句或函数如IFNULL()或COALESCE()来处理Null值，并赋予一个默认值或相应地处理它们。

下面是一个在Tdengine中将count()的结果赋值给整数变量时处理Null值的示例：

```
DECLARE @count INT;
SET @count = IFNULL(count(*), 0); -- 如果count()返回Null，则赋值为0
```

**Comment by feiyangbeyond** [comment]
> 在Tdengine中，当查询结果中没有匹配的数据时，count()函数会返回Null。这是设计上的行为。
> 
> 当你使用count(*)函数查询表中的行数或特定条件的结果时，如果没有找到匹配的行，count()函数将返回Null，而不是零。这是为了区分实际的计数为零和查询结果为空或未定义的情况。
> 
> 如果你将count()的结果赋值给一个整数变量，确保处理Null值的可能性。你可以使用条件语句或函数如IFNULL()或COALESCE()来处理Null值，并赋予一个默认值或相应地处理它们。
> 
> 下面是一个在Tdengine中将count()的结果赋值给整数变量时处理Null值的示例：
> 
> ```
> DECLARE @count INT;
> SET @count = IFNULL(count(*), 0); -- 如果count()返回Null，则赋值为0
> ```

有 IFNULL 这个函数？

**Comment by 516562160** [comment]
IFNULL 和IS NOT NULL ? count(*) : 0能用？我试了sql报错啊

**Comment by yu285** [comment]
3.x 已经支持count 返回 0 的特性。

2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
