### ISSUE TITLE
The interval query causes core dump

### ISSUE THREAD

**Issue by maoxz89** [taosdata/TDengine#12880]
![06f29a2004dda9f3361ae44f4b25b13](https://user-images.githubusercontent.com/106085619/169825670-f78c1a4d-427c-4c12-939d-deba803d22d1.png)
如图 core dump

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
