### ISSUE TITLE
It is recommended to upgrade the dependent fastjson version 

### ISSUE THREAD

**Issue by znznz** [taosdata/TDengine#12882]
根据Fastjson官方说明， fastjson 1.2.80及以下存在风险，建议升级依赖的fastjson 版本

fastjson已使用黑白名单用于防御反序列化漏洞，经研究该利用在特定条件下可绕过默认autoType关闭限制，攻击远程服务器，风险影响较大。建议fastjson用户尽快采取安全措施保障系统安全
官方链接 https://github.com/alibaba/fastjson/wiki/security_update_20220523

**Comment by fenghuazzm** [comment]
感谢提醒！我们注意到了，已采取措施
