### ISSUE TITLE
S-table sort query by timestamp is particularly slow

### ISSUE THREAD

**Issue by wangdijie** [taosdata/TDengine#12894]
超级表按照ts倒叙查询分页的时候非常慢，把排序去掉就非常快，数据一共也才6万多条，版本是2.1.2
`select * from st_attribute_message order by ts desc limit 10;`

请教是查询语句的问题呢还是其他环境版本的问题？

**Comment by fenghuazzm** [comment]
order by 后 limit 这个功能在 2.4 的版本得到了优化，性能强了非常多，可以升级了再试试

**Comment by xiaofuliang** [comment]
@wangdijie 解决了吗？遇到同样的问题

**Comment by wangdijie** [comment]
> @wangdijie 解决了吗？遇到同样的问题

版本问题，升级版本就好了

**Comment by xiaofuliang** [comment]
limit 比较后面的页数，还是会有这样的问题，例如limit 0.20不会 慢，limit 20000，20 加上order by ts就会慢，你是升级到多少版本

**Comment by wangdijie** [comment]
> limit 比较后面的页数，还是会有这样的问题，例如limit 0.20不会 慢，limit 20000，20 加上order by ts就会慢，你是升级到多少版本

我当时遇到的问题是有order by会变慢，升级到最新版就很快了。当时的最新版是2.4.0.20。

刚才试着查了下，速度还可以，两秒左右。
`select * from st_attribute_message 
order by ts desc 
limit 20000,20`

**Comment by ptrjeffrey** [comment]
这个确实比较慢，2.6的版本，
SELECT * FROM  stable ORDER BY ts DESC LIMIT 20 OFFSET 195000
花了>5秒。因为一共就20万数据不到，这个感觉不正常。用的是api查的

**Comment by zuodengchao** [comment]
3.0 也比较慢，根本查询不出来

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
