### ISSUE TITLE
There is no result information printed in the screen when using TDengine client shell.

### ISSUE THREAD

**Issue by sunhao1005** [taosdata/TDengine#1292]
TDengine 服务端命令行查询等操作不打印任何信息，通过windows客户端连接本地虚拟机服务端，连接成功，但所有操作同样不打印任何信息。只有通过代码连接查询等功能正常(ubuntu1804)

**Comment by plum-lihui** [comment]
是taos  shell上执行命令，没有任何输出吗？请截图给我们看看。
多谢！

**Comment by sunhao1005** [comment]
![批注 2020-03-03 100708](https://user-images.githubusercontent.com/44885759/75736110-53477d80-5d37-11ea-8b3c-db196da8ddb2.png)
![批注 2020-03-03 100757](https://user-images.githubusercontent.com/44885759/75736113-5478aa80-5d37-11ea-8cc7-740f94862b52.png)
之前我通过代码创建了数据库test01，在test01里创建了表t（create table test01.t (ts timestamp, speed int);），数据库原本是两条数据，截图测试时添加了一条（insert into test01.t values ('2020-02-22 00:00:00', 22)），先通过命令行执行，无反应，通过代码查询不到，通过代码我再执行插入，成功插入，可以查询到。截图里有打印信息。

**Comment by sunhao1005** [comment]
之前我通过代码创建了数据库test01，在test01里创建了表t（创建表test01.t（ts时间戳，速度int）；），数据库原本是两个数据，截图测试时添加了一条（插入test01。 t values（'2020-02-22 00:00:00'，22）），先通过命令行执行，无反应，通过代码查询不到，通过代码我再执行插入，成功插入，可以查询到。截图里有详细打印信息。






------------------ 原始邮件 ------------------
发件人:&nbsp;"plum-lihui"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月2日(星期一) 下午4:48
收件人:&nbsp;"taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送:&nbsp;"像我这样的人"<2417291999@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [taosdata/TDengine] TDengine 服务端命令行查询等操作不打印任何信息 (#1292)




是taos  shell上执行命令，没有任何输出吗？请截图给我们看看。
 多谢！
  
— 
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by liu0x54** [comment]
> ![批注 2020-03-03 100708](https://user-images.githubusercontent.com/44885759/75736110-53477d80-5d37-11ea-8b3c-db196da8ddb2.png)
> ![批注 2020-03-03 100757](https://user-images.githubusercontent.com/44885759/75736113-5478aa80-5d37-11ea-8cc7-740f94862b52.png)
> 之前我通过代码创建了数据库test01，在test01里创建了表t（create table test01.t (ts timestamp, speed int);），数据库原本是两条数据，截图测试时添加了一条（insert into test01.t values ('2020-02-22 00:00:00', 22)），先通过命令行执行，无反应，通过代码查询不到，通过代码我再执行插入，成功插入，可以查询到。截图里有打印信息。

You need include a ";" at the end of the SQL. Try "select * from test01.t;" instead of "select * from test01.t".

**Comment by sunhao1005** [comment]
You need to print an error message instead of a syntax error. There is no prompt, which can be misleading.😂😂

**Comment by liu0x54** [comment]
> You need to print an error message instead of a syntax error. There is no prompt, which can be misleading.😂😂

You know, the TDengine is written in C, not golang, 😂

**Comment by sunhao1005** [comment]
So you need to work hard to improve it，加油！💪

**Comment by plum-lihui** [comment]
sql是以分号作为结束的，没有输入分号之前，一直在等待输入，直到分号为止。所以在分号之前是无法提示的。

**Comment by sunhao1005** [comment]
但是这是shell命令行，大家习惯敲回车结束，而不是用“；”，所以可以考虑考虑用户体验，或者直接出图形化界面，就没有这种争论了。个人浅见（要从用户的角度考虑问题）。
