### ISSUE TITLE
error “create database banch_test error [0xb] Unable to establish connection” in bench-testing of driver-go  

### ISSUE THREAD

**Issue by tangjiang** [taosdata/TDengine#12929]
**Bug Description**
运行 bench/valgrind/main.go ，执行到
_, err = db.Exec("create database if not exists bench_test") 时，出现
create database banch_test error [0xb] Unable to establish connection情况。
奇怪的是：但重新运行，会偶发性的成功

另：执行 taosSql/driver_test.go 的测试代码是成功的

**To Reproduce**
1.拉取代码 https://github.com/taosdata/driver-go
2. 基于vscode对bench/valgrind/main.go进行调试
3. 执行到 _, err = db.Exec("create database if not exists bench_test") 报错：create database banch_test error [0xb] Unable to establish connection

**Expected Behavior**
db.Exec(...) Successfully 

**Screenshots**
![image](https://user-images.githubusercontent.com/442520/170010069-10fe9ab9-c63e-4b00-9c5c-69a2d062e0ea.png)

**Environment (please complete the following information):**
 - OS:Ubuntu 22.04
 - TDengine Version [2.4.0.18]  
 - TDEngine基于docker镜像运行， 镜像版本：tdengine/tdengine:2.4.0.18
 - 安装的TDengine-client版本是2.4.0.18， 下载地址：https://www.taosdata.com/assets-download/TDengine-client-2.4.0.18-Linux-x64.tar.gz

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
