### ISSUE TITLE
DB error: invalid operation: TWA/Diff/Derivative/Irate/CSUM/MAVG/SAMPLE/INTERP/Elapsed are not allowed to apply to super table directly

### ISSUE THREAD

**Issue by lrzl** [taosdata/TDengine#12959]
**Bug Description**
使用INTERP函数出现invalid operation问题

**To Reproduce**
1.创建unittest库 CREATE DATABASE IF NOT EXISTS unittest REPLICA 1 QUORUM 1 DAYS 10 KEEP 3650 CACHE 16 BLOCKS 6 MINROWS 100 MAXROWS 4096 FSYNC 3000 CACHELAST 0 COMP 2 PRECISION 'ms' UPDATE 0;
2.创建超级表： CREATE STABLE IF NOT EXISTS wind (ts TIMESTAMP,direction DOUBLE,speed DOUBLE) TAGS(sensor NCHAR(32),city NCHAR(32))
3.导入数据，见附件[taos.zip](https://github.com/taosdata/TDengine/files/8735707/taos.zip)
4.执行sql语句： `SELECT INTERP(speed) FROM wind EVERY(5s) FILL(NEXT);`
出现DB error: invalid operation: TWA/Diff/Derivative/Irate/CSUM/MAVG/SAMPLE/INTERP/Elapsed are not allowed to apply to super table directly

**Screenshots**

![image](https://user-images.githubusercontent.com/32292315/169457753-3660fc50-9e34-4841-a7fa-5a2da0fcbcc4.png)

![image](https://user-images.githubusercontent.com/32292315/169458940-31bc1165-31bb-426a-8ea6-0e6fcd116acf.png)

**Environment (please complete the following information):**
 - OS: centos7
 - Memory, CPU, current Disk Space
 - TDengine Version 2.4.0.20

**Comment by fenghuazzm** [comment]
![image](https://user-images.githubusercontent.com/70138133/170261923-d0749eac-f778-4e49-a259-e03d32340ba7.png)
不能够直接这样作用于超级表
