### ISSUE TITLE
Question about REAL WAL sync write

### ISSUE THREAD

**Issue by tigerhu2008** [taosdata/TDengine#12962]
**General Questions**
Looks like currently a thread is used to sync log to physical storage media while another thread is used to write(to DRAM or FS page cache), thus it can't realize 100% real sync write even fsyncPeriod is set to zero.  Do we have any plan to implement real sync write? Correct me if i am wrong. Thanks.

**Comment by ljluestc** [comment]
In Tdengine, the current behavior is that one thread is used to synchronize logs to physical storage media, while another thread is responsible for writing to DRAM or the file system page cache. This design does not achieve 100% real synchronous write, even if fsyncPeriod is set to zero.

**Comment by sangshuduo** [comment]
[https://docs.tdengine.com/taos-sql/database/#parameters](https://docs.tdengine.com/taos-sql/database/#parameters
)

WAL_FSYNC_PERIOD: specifies the interval (in milliseconds) at which data is written from the WAL to disk. This parameter takes effect only when the WAL parameter is set to 2. The default value is 3000. Enter a value between 0 and 180000. The value 0 indicates that incoming data is immediately written to disk.
