### ISSUE TITLE
Running in docker container, the ports of TDengine are mirrored and can not connect to TDengine use JDBC connector from the host system.

### ISSUE THREAD

**Issue by vannewang** [taosdata/TDengine#1298]
docker-compose  ports如下
### - 7020-7039:6020-6039/udp
docker可以启动成功,windows客户端已安装,版本都是1.6.5.5

application.properites配置如下:
spring.datasource.driver-class-name=com.taosdata.jdbc.TSDBDriver
spring.datasource.url=jdbc:TAOS://192.168.35.55:7035/log
spring.datasource.username=root
spring.datasource.password=taosdata

启动项目报错
failed to connect to server
请问这个问题能解决吗

**Comment by vannewang** [comment]
客户端配置文件对应端口已修改,并且可以在windows客户端直接用命令行   ./taos.exe -h 192.168.35.55 -P 7030连接上

# http service port, default tcp[6020]
# httpPort              7020
# port for MNode connect to Client, default udp[6030-6034] tcp[6030]
# mgmtShellPort         7030
# port for DNode connect to Client, default udp[6035-6039] tcp[6035]
# vnodeShellPort        7035


日志信息如下:
### 1. 直接使用命令行连接:
03/03 09:36:59.234000 0x16236 UTL timezone not configured, use default
03/03 09:36:59.248000 0x16236 UTL locale not configured, set to default:Chinese_China.936
03/03 09:36:59.248000 0x16236 UTL charset not configured, set to default:cp936
03/03 09:36:59.248000 0x16236 UTL    taos config & system info:
03/03 09:36:59.248000 0x16236 UTL ==================================
03/03 09:36:59.248000 0x16236 UTL  localIp:                0.0.0.0 
03/03 09:36:59.248000 0x16236 UTL  mgmtShellPort:          7030 
03/03 09:36:59.248000 0x16236 UTL  vnodeShellPort:         6035 
03/03 09:36:59.248000 0x16236 UTL  configDir:              C:/TDengine/cfg 
03/03 09:36:59.248000 0x16236 UTL  logDir:                 C:/TDengine/log 
03/03 09:36:59.248000 0x16236 UTL  scriptDir:              C:/TDengine/script 
03/03 09:36:59.248000 0x16236 UTL  numOfThreadsPerCore:    1.000000 
03/03 09:36:59.248000 0x16236 UTL  affectedRowsMod:        0 
03/03 09:36:59.248000 0x16236 UTL  rpcTimer:               300(ms)
03/03 09:36:59.248000 0x16236 UTL  rpcMaxTime:             600(s)
03/03 09:36:59.248000 0x16236 UTL  shellActivityTimer:     3(s)
03/03 09:36:59.248000 0x16236 UTL  meterMetaKeepTimer:     7200(s)
03/03 09:36:59.248000 0x16236 UTL  metricMetaKeepTimer:    600(s)
03/03 09:36:59.248000 0x16236 UTL  defaultDB:               
03/03 09:36:59.248000 0x16236 UTL  defaultUser:            root 
03/03 09:36:59.248000 0x16236 UTL  sockettype:             udp 
03/03 09:36:59.248000 0x16236 UTL  compressMsgSize:        -1 
03/03 09:36:59.248000 0x16236 UTL  maxSQLLength:           65380(byte)
03/03 09:36:59.248000 0x16236 UTL  timezone:               not configured 
03/03 09:36:59.248000 0x16236 UTL  locale:                 Chinese_China.936 
03/03 09:36:59.248000 0x16236 UTL  charset:                cp936 
03/03 09:36:59.248000 0x16236 UTL  numOfLogLines:          10000000 
03/03 09:36:59.248000 0x16236 UTL  asyncLog:               1 
03/03 09:36:59.248000 0x16236 UTL  debugFlag:              131 
03/03 09:36:59.248000 0x16236 UTL  rpcDebugFlag:           131 
03/03 09:36:59.248000 0x16236 UTL  tmrDebugFlag:           131 
03/03 09:36:59.248000 0x16236 UTL  cDebugFlag:             131 
03/03 09:36:59.248000 0x16236 UTL  jniDebugFlag:           131 
03/03 09:36:59.248000 0x16236 UTL  odbcDebugFlag:          131 
03/03 09:36:59.248000 0x16236 UTL  uDebugFlag:             131 
03/03 09:36:59.248000 0x16236 UTL  qDebugFlag:             131 
03/03 09:36:59.248000 0x16236 UTL  gitinfo:                918cb2220f6a1f71966f7e94e697885d50fc241f 
03/03 09:36:59.248000 0x16236 UTL  gitinfoOfInternal:      da88f4a2474737d1f9c76adcf0ff7fd0975e7342 
03/03 09:36:59.248000 0x16236 UTL  buildinfo:              Built by root at 2020-02-09 11:09 
03/03 09:36:59.248000 0x16236 UTL  version:                1.6.5.5 
03/03 09:36:59.248000 0x16236 UTL  dataDir:                C:/TDengine/data
03/03 09:36:59.248000 0x16236 UTL ==================================

### 2.使用java代码连接
03/03 09:37:52.434000 0x5956 UTL timezone not configured, use default
03/03 09:37:52.449000 0x5956 UTL locale not configured, set to default:Chinese_China.936
03/03 09:37:52.449000 0x5956 UTL charset not configured, set to default:cp936
03/03 09:37:52.449000 0x5956 UTL    taos config & system info:
03/03 09:37:52.449000 0x5956 UTL ==================================
03/03 09:37:52.449000 0x5956 UTL  localIp:                0.0.0.0 
03/03 09:37:52.449000 0x5956 UTL  mgmtShellPort:          6030 
03/03 09:37:52.449000 0x5956 UTL  vnodeShellPort:         6035 
03/03 09:37:52.449000 0x5956 UTL  configDir:              C:/TDengine/cfg 
03/03 09:37:52.449000 0x5956 UTL  logDir:                 C:/TDengine/log 
03/03 09:37:52.449000 0x5956 UTL  scriptDir:              C:/TDengine/script 
03/03 09:37:52.449000 0x5956 UTL  numOfThreadsPerCore:    0.000000 
03/03 09:37:52.449000 0x5956 UTL  affectedRowsMod:        0 
03/03 09:37:52.449000 0x5956 UTL  rpcTimer:               300(ms)
03/03 09:37:52.449000 0x5956 UTL  rpcMaxTime:             600(s)
03/03 09:37:52.449000 0x5956 UTL  shellActivityTimer:     3(s)
03/03 09:37:52.449000 0x5956 UTL  meterMetaKeepTimer:     7200(s)
03/03 09:37:52.449000 0x5956 UTL  metricMetaKeepTimer:    600(s)
03/03 09:37:52.449000 0x5956 UTL  defaultDB:               
03/03 09:37:52.449000 0x5956 UTL  defaultUser:            root 
03/03 09:37:52.449000 0x5956 UTL  sockettype:             udp 
03/03 09:37:52.449000 0x5956 UTL  compressMsgSize:        -1 
03/03 09:37:52.449000 0x5956 UTL  maxSQLLength:           65380(byte)
03/03 09:37:52.449000 0x5956 UTL  timezone:               not configured 
03/03 09:37:52.449000 0x5956 UTL  locale:                 Chinese_China.936 
03/03 09:37:52.449000 0x5956 UTL  charset:                cp936 
03/03 09:37:52.449000 0x5956 UTL  numOfLogLines:          10000000 
03/03 09:37:52.449000 0x5956 UTL  asyncLog:               1 
03/03 09:37:52.449000 0x5956 UTL  debugFlag:              131 
03/03 09:37:52.449000 0x5956 UTL  rpcDebugFlag:           131 
03/03 09:37:52.449000 0x5956 UTL  tmrDebugFlag:           131 
03/03 09:37:52.449000 0x5956 UTL  cDebugFlag:             131 
03/03 09:37:52.449000 0x5956 UTL  jniDebugFlag:           131 
03/03 09:37:52.449000 0x5956 UTL  odbcDebugFlag:          131 
03/03 09:37:52.449000 0x5956 UTL  uDebugFlag:             131 
03/03 09:37:52.449000 0x5956 UTL  qDebugFlag:             131 
03/03 09:37:52.449000 0x5956 UTL  gitinfo:                918cb2220f6a1f71966f7e94e697885d50fc241f 
03/03 09:37:52.449000 0x5956 UTL  gitinfoOfInternal:      da88f4a2474737d1f9c76adcf0ff7fd0975e7342 
03/03 09:37:52.449000 0x5956 UTL  buildinfo:              Built by root at 2020-02-09 11:09 
03/03 09:37:52.449000 0x5956 UTL  version:                1.6.5.5 
03/03 09:37:52.449000 0x5956 UTL  dataDir:                C:/TDengine/data
03/03 09:37:52.449000 0x5956 UTL ==================================
03/03 09:38:01.467000 0x12508 ERROR TSC 000000000073E0D0 reach the max retry:2, code:29
03/03 09:38:01.467000 0x5956 ERROR JNI jobj:000000001AA4A8A8, conn:0000000000000000, connect to database failed, host=192.168.35.55, user=root, dbname=log, port=7030
03/03 09:38:01.467000 0x5956 ERROR JNI jobj:000000001AA4A838, connection is closed

**Comment by liu0x54** [comment]
Try to modify the configuration in the C:/TDengine/cfg/taos.cfg, 
modify  mgmtShellPort: 6030 to  mgmtShellPort: 7030, vnodeShellPort: 6035 to vnodeShellPort: 7035.
Maybe this will help

**Comment by vannewang** [comment]
您说的客户端C：/TDengine/cfg/taos.cfg已经改过了(在第二条的大字那边) , 并没有生效

并且我用新的镜像重新部署了一个端口映射为
   - 6020-6039:6020-6039
   - 6020-6039:6020-6039/udp
的docker-compose.yml文件,这样就启动成功了(这个时候windows客户端的taos.cfg端口都是7开头的)


这个问题是因为windows配置没有加载成功吗

**Comment by vannewang** [comment]
![demo](https://user-images.githubusercontent.com/46670766/75747039-e0e69580-5d56-11ea-857b-a7a07fea8fc7.png)

**Comment by liu0x54** [comment]
可能会存在一些问题，我们服务器给客户端驱动中会将自己的端口带在消息里，这样端口映射会造成服务端和客户端保存的端口不一致。这是个限制，暂时不支持服务端和客户端的端口不一致，如果要避开某些端口被占用的情况，建议客户端和服务端的端口一起改，并保持一致

**Comment by vannewang** [comment]
经过测试 , 您说的方法可行,我的本地windows环境有些问题才导致出现这样的问题
