### ISSUE TITLE
some problems about go connector in the windows os

### ISSUE THREAD

**Issue by daxiabiluo** [taosdata/TDengine#1299]
1.TDengine-client-1.6.5.5-Windows-x64.exe安装之后driver目录下只包含taos.dll,taos.lib,taos.exp,不包含libtaos.dll、libtaos.dll.a。
2.只能根据《TDengine GO windows驱动的编译和使用》博客进行编译，但是make出错
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64
-mingw32/bin/ld.exe: CMakeFiles/taos.dir/objects.a(tscFunctionImpl.c.obj):tscFun
ctionImpl.c:(.text+0x5277): undefined reference to `getPercentile'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64
-mingw32/bin/ld.exe: CMakeFiles/taos.dir/objects.a(tscFunctionImpl.c.obj):tscFun
ctionImpl.c:(.text+0x528f): undefined reference to `tMemBucketDestroy'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64
-mingw32/bin/ld.exe: CMakeFiles/taos.dir/objects.a(tscFunctionImpl.c.obj):tscFun
ctionImpl.c:(.text+0x5325): undefined reference to `tMemBucketPut'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64
-mingw32/bin/ld.exe: CMakeFiles/taos.dir/objects.a(tscFunctionImpl.c.obj):tscFun
ctionImpl.c:(.text+0x53c2): undefined reference to `tMemBucketPut'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64
-mingw32/bin/ld.exe: CMakeFiles/taos.dir/objects.a(tscFunctionImpl.c.obj):tscFun
ctionImpl.c:(.text+0x74b2): undefined reference to `tMemBucketCreate'
collect2.exe: error: ld returned 1 exit status
src/client/CMakeFiles/taos.dir/build.make:430: recipe for target 'build/lib/libt
aos.dll' failed
make[2]: *** [build/lib/libtaos.dll] Error 1
make[2]: Leaving directory 'C:/Users/Administrator/Desktop/TDengine-develop/debu
g'
CMakeFiles/Makefile2:790: recipe for target 'src/client/CMakeFiles/taos.dir/all'
 failed
make[1]: *** [src/client/CMakeFiles/taos.dir/all] Error 2
make[1]: Leaving directory 'C:/Users/Administrator/Desktop/TDengine-develop/debu
g'
Makefile:154: recipe for target 'all' failed
make: *** [all] Error 2

3.希望可以直接提供libtaos.dll和libtaos.dll.a，不需要进行编译

**Comment by plum-lihui** [comment]
好的，我们计划一下，考虑将go的windows库也打包进去。

**Comment by daxiabiluo** [comment]
1.之前是再win7上编译的，现在在win10上编译成功，有可能是编译环境的问题把
2.但是现在go run taosapp.go会报错：cannot find -ltaos和一系列cannot find其他库
3.已经修改了result.go和taosSqlCgo.go，如下：
#cgo CFLAGS : -IC:/TDengine/include
#cgo LDFLAGS: -LC:/TDengine/go -ltaos
（将debug\build\lib里的库放到了C:/TDengine/go里）

**Comment by plum-lihui** [comment]
我们已经发布了2.0.5.0版本，包括windwos GO驱动，请下载使用。
