### ISSUE TITLE
A new tag field is added to the supertable. However, when data is written to an existing subtable, the tag value is NULL .

### ISSUE THREAD

**Issue by clcl2** [taosdata/TDengine#13006]
1.创建超级表: create table test (
                                  pos_time TIMESTAMP,
                                  acc_status SMALLINT
)
    tags(
            device_id nchar(32)
        ) ;
2.执行 insert into d1001 using ampere tags('test', '2','2','2') VALUES (now,123);
insert into test_233 using test tags ('233') values ('2022-05-26 00:00:10',2);
3.这时候test 超级表tag数量是1,后来我想在test超级表加多个tag值变成2个
ALTER STABLE test ADD TAG app_code nchar(32);
4.执行 ALTER TABLE ampere ADD TAG variable_id BINARY(50);

5.继续执行 创建了一个新的子表 test_233 ：
insert into test_233 using test tags ('233','vin') values ('2022-05-26 00:00:10',2);

但是我发现去查询超级表的时候 test 表的数据 第2个tag 为 null，第一个个tag有数据
![image](https://user-images.githubusercontent.com/41424119/170402398-d8edb010-d330-4ce5-9ea6-eb6e23227db2.png)
![image](https://user-images.githubusercontent.com/41424119/170402443-1b955dc7-a31f-425e-932e-616428985911.png)
![image](https://user-images.githubusercontent.com/41424119/170403007-ec7e77d4-3e8c-480f-97c0-d2dc184749e4.png)

后来尝试新建了一张子表test_233_vin，并写入数据，发现tag有数据

**Comment by fenghuazzm** [comment]
最后重新创建一张新的子表，是没问题的，但在添加 tag 字段之前的子表，需要这样修改：
ALTER TABLE tb_name SET  TAG  tag_name=new_tag_value;

**Comment by clcl2** [comment]
但是生产环境已经有上百万子表了，逐个执行难度较大。后续会考虑写入并创建表的sql语句去动态更新子表tag值么

**Comment by clcl2** [comment]
>但是生产环境已经有上百万子表了，逐个执行难度较大。后续会考虑写入并创建表的sql语句去动态更新子表tag值么

**Comment by clcl2** [comment]
> 最后重新创建一张新的子表，是没问题的，但在添加 tag 字段之前的子表，需要这样修改： ALTER TABLE tb_name SET TAG tag_name=new_tag_value;

但是生产环境已经有上百万子表了，逐个执行难度较大。后续会考虑写入并创建表的sql语句去动态更新子表tag值么

**Comment by skyqqcloud** [comment]
> 最后重新创建一张新的子表，是没问题的，但在添加 tag 字段之前的子表，需要这样修改： ALTER TABLE tb_name SET TAG tag_name=new_tag_value;

请问这个问题会修复吗，我们也遇到类似的问题。随着业务需求变化，需要对历史表增加新Tag(例如location，然后利用这个location在select时做筛选),而且这个location是可能会随设备发生变化的，要是新增的Tag不能用insert语句修改那就没法用了

**Comment by clownlanko** [comment]
我这边也有同样的问题存在。按照甲方设计的表，存在一个tag为分类，它的值有不同的类型，当insert时不会发生改变。

**Comment by yu285** [comment]
这个是设计，不是bug . 只能随时修改。或者，不同的值作为不同的表
