### ISSUE TITLE
Python is slow to insert data for the first time

### ISSUE THREAD

**Issue by xiaohuizhang** [taosdata/TDengine#13019]
1. 用的是python原生连接做的测试
2. 10w张子表，10w条数据，这是极限情况，1张表插入一条数据
问题：
      启动程序后，第一次插入总是很慢，足足需要200s左右，但是后续的插入就很快，毫秒级的。这个是什么原因？

**Comment by fenghuazzm** [comment]
10w 张子表，初次执行插入需要先建 10w 个子表的结构以及标签值，就会慢一些

**Comment by xiaohuizhang** [comment]
谢谢你的回复。
一开始我也想到这个问题了，所以在第二次测试的时候，子表已经创建好了，但是第一次插入的速度是还是慢的，没有多大的提升。

**Comment by iwccsbfb** [comment]
可能和建立緩存有關係吧 - 第一次需要建立緩存

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
