### ISSUE TITLE
After the OpenTSDB JSON example is run, the real data cannot be queried in taos shell.

### ISSUE THREAD

**Issue by lovesw** [taosdata/TDengine#13069]
**Bug Description**
OpenTSDB JSON 的官方demo例子运行后，无法查询出数据

![image](https://user-images.githubusercontent.com/17812536/170619290-9931ce26-c233-41f0-a42a-713580985155.png)

**Comment by fenghuazzm** [comment]
咱是用什么代码跑的？我这边用 python 跑着没问题

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
