### ISSUE TITLE
请问什么时候能够支持数据修改?

### ISSUE THREAD

**Issue by rwayan** [taosdata/TDengine#131]
在恶劣网络环境中，数据采集错误，没有办法人工修复的话，会导致结果严重失真。请问设计团队是如何考虑这个问题的？

**Comment by eurake** [comment]
根据存储引擎的设计,更改数据的成本有点大

**Comment by 625781186** [comment]
![image](https://user-images.githubusercontent.com/30521429/61592209-b4846b80-ac02-11e9-9004-a53b46cfc550.png)
所以这个意思是 对一个数据 进行多次备份?
要改的时候创建一个节点?
我不知道我这样理解对不对

**Comment by fengshaoxie** [comment]
> 在恶劣网络环境中，数据采集错误，没有办法人工修复的话，会导致结果严重失真。请问设计团队是如何考虑这个问题的？

我觉得更改数据不现实，工业中一般只是采集显示，不会进行修改的。你的软件能进行修改，人家会质疑你数据的可靠性。

**Comment by plum-lihui** [comment]
TDengine暂时还不支持数据的修改，后续会考虑增加支持。

**Comment by wanliofficial** [comment]
是的，数据采集应该还是要支持能修改，不能搞一刀切卡死修改的权限，甚至是删除的权限~
