### ISSUE TITLE
TDengine Server Support on the Windows platform ？

### ISSUE THREAD

**Issue by JalynFang** [taosdata/TDengine#1314]
请教下，TDengine Server端不支持windows平台，是否可能通过cygwin打包成可在windows上运行？

我在cygwin环境下安装后，不能正常运行；拉源码编译报错：
CMake Error at CMakeLists.txt:135 (MESSAGE):
  The current platform is not Linux/Darwin/Windows, stop compile

**Comment by liu0x54** [comment]
可以试试在windows docker环境下运行，拉取tdengine/tdengine镜像，在docker中运行

**Comment by Shawshank-Smile** [comment]
The TDengine Server haven't support windows platform yet, and may be we have no plan to support windows platform.
