### ISSUE TITLE
taos_connect crashed

### ISSUE THREAD

**Issue by paopaol** [taosdata/TDengine#1316]
**Bug Description**
`taos = taos_connect(host, user,pass, NULL, 0);` crashed
host is "127.0.0.1"
user is "root"
pass is "taosdata"

**To Reproduce**
just connect

**Screenshots**
![2020-03-05 16-18-01屏幕截图](https://user-images.githubusercontent.com/6983082/75961412-f269a200-5efc-11ea-9a7e-8ce5597c2baf.png)

**Environment (please complete the following information):**
 - OS:ubuntu 18.04
 - TDengine Version TDengine-ver-1.6.5.6

**Comment by plum-lihui** [comment]
Is the client application running on the same machine as the taosd service?

**Comment by cshlxm** [comment]
almost same error. The taosd(version 1.6.5.6) run on the armhf(cpu:rk3288 ,os : ubuntu 1804) platform.when I connected from windows client( version 1.6.5.6) ,execute commands below, It happens, Taosd crashed. 
![image](https://user-images.githubusercontent.com/4603098/76146991-0404a280-60d3-11ea-930f-85b08bd8df5e.png)
![image](https://user-images.githubusercontent.com/4603098/76147000-24346180-60d3-11ea-9f3d-4a2e653c6e9d.png)

**Comment by paopaol** [comment]
resolved.i rename the tMd5.cpp/h all signature.eg:MD5Init-->tMD5Init.....then it works fine.
i think maybe , the md5 function already exits in my ubuntu system.and taos used the system md5 library but taos's self.then crashed

**Comment by Shawshank-Smile** [comment]
Thank you, good luck.
