### ISSUE TITLE
请问能否支持金融数据场景？

### ISSUE THREAD

**Issue by rwayan** [taosdata/TDengine#132]
金融数据跟IoT数据的相似程度很高，请问能否支持这类应用？

**Comment by francis-du** [comment]
### 金融别想了，不是做金融的东西，兄弟，劝你善良~

**Comment by francis-du** [comment]
### @rwayan 金融别想了，不是做金融的东西，兄弟，劝你善良~

**Comment by jtao1735** [comment]
当然支持。每只股票单独建立一张表即可
