### ISSUE TITLE
DB error: server-client date time unsynced

### ISSUE THREAD

**Issue by daconglee** [taosdata/TDengine#1324]
C:\TDengine>taos.exe -h 192.168.181.32 -s "use db; show tables;"

Welcome to the TDengine shell from windows, client version:1.6.5.6
DB error: server-client date time unsynced

[root@localhost ~]# taos

Welcome to the TDengine shell from linux, community client version:1.6.5.6 community server version:1.6.5.6
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

taos>

**Comment by plum-lihui** [comment]
What's the difference between windows time and Linux time?
Don't they sync NTP time?

**Comment by daconglee** [comment]
内网，服务器时间没办法和windows的客户端进行时间同步。

**Comment by Shawshank-Smile** [comment]
May you do the time synchronization manually
