### ISSUE TITLE
ubuntu安装执行报错

### ISSUE THREAD

**Issue by godatabus** [taosdata/TDengine#133]
$ sudo dpkg -i tdengine-1.6.1.0.deb
Selecting previously unselected package tdengine.
(Reading database ... 44843 files and directories currently installed.)
Preparing to unpack tdengine-1.6.1.0.deb ...
Unpacking tdengine (1.6.1.0) ...
Setting up tdengine (1.6.1.0) ...
Start to install TDEngine...
sed: can't read /etc/inittab: No such file or directory
Couldn't find an alternative telinit implementation to spawn.
cp: cannot stat '%{init_d_dir}/taosd': No such file or directory
grep: /etc/inittab: No such file or directory
update-rc.d: error: unable to read /etc/init.d/taosd

TDengine is installed successfully!

To configure TDengine : edit /etc/taos/taos.cfg
To start TDengine     : sudo update-rc.d taosd default   for the first time
                      : sudo service taosd start  after
To access TDengine    : use taos in shell

TDengine is installed successfully!
$ taos
07/20 19:59:47.913292 7f4709e50b80 ERROR UTL open file:/proc/119/io failed
07/20 19:59:47.927421 7f4709e50b80 ERROR UTL setsockopt SO_NO_CHECK failed: 92 (Protocol not available)
TSDB error: App error

**Comment by johnnyhou327** [comment]
@godatabus 您的安装环境是什么？windows下的linux subsystem会有这个问题，如果是这种环境建议您换一下，用虚拟机或者docker来测试。

**Comment by guanshengliang** [comment]
这个问题我们已经修复，下周一之前会上传代码

**Comment by zimengpan** [comment]
> #339 已经为WSL提供了暂时的支持，请再尝试一下 

> #339 has provided with a temporary workaround, please pull and try again

**Comment by junwei-lab** [comment]
> 这个问题我们已经修复，下周一之前会上传代码

我用TDengine-server-1.6.5.7-Linux-x64在windows上的ubuntu上安装，还是报这个错
Start to install TDEngine...
Couldn't find an alternative telinit implementation to spawn.
cp: cannot stat '%{init_d_dir}/taosd': No such file or directory
update-rc.d: error: unable to read /etc/init.d/taosd

TDengine is installed successfully!

To configure TDengine : edit /etc/taos/taos.cfg
To start TDengine     : sudo update-rc.d taosd default   for the first time
                      : sudo service taosd start  after
To access TDengine    : use taos in shell

TDengine is installed successfully!
root@MININT-TEPJ9RD:/home# sudo systemctl start taosd
System has not been booted with systemd as init system (PID 1). Can't operate.
