### ISSUE TITLE
The password change is invalid in version 2.6.0.1

### ISSUE THREAD

**Issue by xibaoning** [taosdata/TDengine#13336]
taos命令行: ALTER USER root PASS '123456'; 
提示修改成功:Query OK, 0 of 0 row(s) in database (0.120000s)
但密码并没有改变, 还是安装时候的默认密码

version:                2.6.0.1

**Comment by fenghuazzm** [comment]
感谢反馈，我试试

**Comment by bioinformatist** [comment]
确实，我也遇到了这个问题，是语法变了但是文档未更新吗？ @fenghuazzm

**Comment by fenghuazzm** [comment]
> 确实，我也遇到了这个问题，是语法变了但是文档未更新吗？ @fenghuazzm

目前是有这个问题，2.6 下次发版的时候会解决了。（大概明天晚上）

**Comment by bioinformatist** [comment]
@fenghuazzm 目前使用上没有这种问题了，我已经在开发环境里更新到最新（2.6.0.4）了

**Comment by fenghuazzm** [comment]
> @fenghuazzm 目前使用上没有这种问题了，我已经在开发环境里更新到最新（2.6.0.4）了
好的👌
