### ISSUE TITLE
关于TDengine client 的系统适配问题。

### ISSUE THREAD

**Issue by yaqiangxue** [taosdata/TDengine#13351]
1. 我目前的系统是centos6.9 ,我升级原生gcc/g++ 4.4.7 到了4.8.1、在使用官方提供的client 库时，发现需要GLIBC_2.14。而我这里时2.12。 我的生产环境也是centos 6.9 ,不敢随便升级glibc .于是我尝试在centos6.9下编译，结果困难重重。

2. 我想请问，是否有centos7一下版本的 TDengine client 提供， 是否它能在centos6.9下编译通过。如果不行，请告知一下。我让他们升级centos7 .谢谢、

**Comment by sangshuduo** [comment]
TDengine 本身没有什么依赖，对 gcc 要求 4.8 以上， cmake 要求 3.0 以上。编译遇到的是什么问题？能否贴一下错误输出信息？

**Comment by yaqiangxue** [comment]
> 

-- Build files have been written to: /root/TDengine/debug
[  4%] Built target z
[  5%] Built target lz4
[  5%] Built target cJson
[  5%] Built target rmonotonic
[ 12%] Built target lua
[ 12%] Building C object deps/TSZ/CMakeFiles/TSZ.dir/zstd/compress/zstd_compress.c.o
{standard input}: Assembler messages:
{standard input}:11678: Error: no such instruction: `shrx %eax,%ecx,%eax'
{standard input}:11913: Error: no such instruction: `shrx %eax,%ecx,%eax'
make[2]: *** [deps/TSZ/CMakeFiles/TSZ.dir/zstd/compress/zstd_compress.c.o] Error 1
make[1]: *** [deps/TSZ/CMakeFiles/TSZ.dir/all] Error 2
make: *** [all] Error 2

这是之前的，我想编一个TDengine client 的库 ，是编译这个github的代码还是别的地方？

**Comment by yaqiangxue** [comment]
我已找到解决办法。我在我虚拟机里centos6.9上编译了个新的glibc 2.15，，但是我没make install 。我把它库的目录分别给到了我makefile 里的库目录和 -rpath .这样编译的时候，能过去，运行的时候，会去-rpath 指定的目录照glibc的相关内容。可以运行了。
