### ISSUE TITLE
文档数据查询章节的最后一个时间维度聚合的例子查询失败

### ISSUE THREAD

**Issue by colo1994** [taosdata/TDengine#1337]
官网例子
**针对传感器采集的数据，以10分钟为一个阶段，计算过去24小时的温度数据的平均值、最大值、温度的中位数、以及随着时间变化的温度走势拟合直线。如果没有计算值，用前一个非NULL值填充。**
```
SELECT AVG(degree),MAX(degree),LEASTSQUARES(degree), PERCENTILE(degree, 50) FROM sensor
  WHERE TS>=NOW-1d
  INTERVAL(10m)
  FILL(PREV);
```
实际上这样子查询的话，因为TS没有指定一个最大值，会导致数据一直查询，返回结果就是：
_DB error: invalid SQL: start(end) time of query range required or time range too large_

而文档的上面说明是：
**使用FILL语句的时候可能生成大量的填充输出，务必指定查询的时间区间**
那么修改一下查询的语句正常了
```
SELECT AVG(degree),MAX(degree),LEASTSQUARES(degree), PERCENTILE(degree, 50) FROM sensor
  WHERE TS>=NOW-1d and ts <=now
  INTERVAL(10m)
  FILL(PREV);
```
我本以为是默认时间聚合计算至当前时间前补0的，估计是计算时候不指定区间就一直计算。

同理如果SQL的查询语句改为 
```
SELECT AVG(degree),MAX(degree),LEASTSQUARES(degree), PERCENTILE(degree, 50) FROM sensor
  **WHERE TS<=NOW-1d** 
  INTERVAL(10m)
  FILL(PREV);
```
那么会从数据库默认开始的时间1970年的时间戳开始计算

**Comment by Shawshank-Smile** [comment]
Thank you, nice suggestion.
