### ISSUE TITLE
Provides support for modifying column names

### ISSUE THREAD

**Issue by Yanxiaolong1998** [taosdata/TDengine#13398]
有需要修改字段的情况，但是发现没有方法去修改，希望后期能出一个解决方案

**Comment by fenghuazzm** [comment]
是否指的修改字段名。
目前 tags 标签字段名可修改，普通字段名不能修改，只能先删除后增加。
需求已记下了，可以说说场景吗。

**Comment by Yanxiaolong1998** [comment]
> 是否指的修改字段名。 目前 tags 标签字段名可修改，普通字段名不能修改，只能先删除后增加。 需求已记下了，可以说说场景吗。
。
但是删除后该列的数据就不在了吧。   我们对接第三方设备时，有字段映射，后期发现字段名映射出错，需要修改超级表和表的字段，查看文档就只有删除和新增。

**Comment by fenghuazzm** [comment]
请问使用的是什么版本的 TDengine ？
如果版本较旧， taosdump 导出的是 sql 文件，可以改下语句的字段名后导入。如果是 2.4 及之后的版本暂时就没办法。
不过这个需求我记录下了。

**Comment by Yanxiaolong1998** [comment]
> 请问使用的是什么版本的 TDengine ？ 如果版本较旧， taosdump 导出的是 sql 文件，可以改下语句的字段名后导入。如果是 2.4 及之后的版本暂时就没办法。 不过这个需求我记录下了。

2.4.0.20了，那确实没办法了

**Comment by liu-shao-jie** [comment]
3.3.6.3版本还有办法吗
