### ISSUE TITLE
如果这个数据库需要接入上万的设备的数据存储是否有问题？

### ISSUE THREAD

**Issue by JessenGan** [taosdata/TDengine#1339]
针对这个数据库在物联网中的应用场景，如果要给每个设备都创建一个表，设备量上万（最大可能超过200W）的数据存入这个数据库中，那么在这个数据库中就会存在上万（200W个设备）的设备表会不会出现性能问题？在系统架构过程中，需要注意哪些技术来避免出现性能问题。

**Comment by Shawshank-Smile** [comment]
piece of cake to TDengine. We have made a conversation yet by wechat ?
