### ISSUE TITLE
tao>命令行能执行的SQL语句，在C程序中执行报错。。。

### ISSUE THREAD

**Issue by density1970** [taosdata/TDengine#134]
如下图：
程序中运行报错：
![图片1](https://user-images.githubusercontent.com/33368407/61579614-2fce1a80-ab3a-11e9-97fa-56d7c1d11b9f.png)

taos命令行执行结果:
![图片2](https://user-images.githubusercontent.com/33368407/61579617-3a88af80-ab3a-11e9-8de8-1d8ecd7f6fc1.png)

**Comment by hzcheng** [comment]
这种导出方式只能在shell中，不是TDengine客户端库中的功能。
