### ISSUE TITLE
USE DB error: Unable to establish connection

### ISSUE THREAD

**Issue by xibaoning** [taosdata/TDengine#13406]
docker环境, 宿主机已做映射, 通信以及taos操作127.0.0.1都比较正常,
但非常大几率在连接taos后第一次使用 use db时出现Unable to establish connection,
然后重复执行use db命令才会成功:Query OK, 0 of 0 row(s) in database  一般第二次执行就成功了

版本:2.6.0.1

**Comment by fenghuazzm** [comment]
use db 后能做查询、写入操作吗？

**Comment by xibaoning** [comment]
可以, 只要use成功, 后面做什么都可以

**Comment by xibaoning** [comment]
嗯, 后面再观察看看, 会不会是只暴露了6030的UDP原因, 目前的端口:
      - "6030:6030"
      - "6030:6030/udp"
      - "6041:6041"

**Comment by fenghuazzm** [comment]
嗯啊，端口开少了
6030-6042 上的 TCP/UDP 都需要开

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
