### ISSUE TITLE
Call cmake failed when compiling the TDengine Go connector on the windows 10 platform.

### ISSUE THREAD

**Issue by lgh-dev** [taosdata/TDengine#1342]
报错截图如下：
![image](https://user-images.githubusercontent.com/17794996/76371713-16ead180-6376-11ea-8b27-226c7b1dc5d5.png)

完全是按照https://www.taosdata.com/blog/2020/01/06/1093.html教程一步步执行。
gcc --version打印如下：
![image](https://user-images.githubusercontent.com/17794996/76371751-3f72cb80-6376-11ea-86f0-0862d6d5beff.png)

希望能尽快解决，谢谢！

另外说一句，本人对c和c++不熟悉，如果是其他语言集成TDengine，以目前这个上手难度来看，劝退了很多其他语言的开发者。建议还是维护不同语言版本的驱动，如果暂时做不到，那么这些需要编译获取的文件最好直接提供下载，免掉c/c++编译环境的搭建。

而且提供原生go语言的驱动对于go语言的项目而已是有很大意义的。go语言项目都会编译为单个二进制文件，可以交叉编译到不同环境，但是cgo模式会破坏这种优势，引入了c/c++的编译、依赖、环境等相关问题，提高了部署难度等。让开发人员同时应对两种语言的问题并集，只获取两种语言的优势的交集。

**Comment by Shawshank-Smile** [comment]
JDBC、ODBC、RESTful are supported，https://www.taosdata.com/cn/documentation/connector/
Maybe we can try some other way.

**Comment by sangshuduo** [comment]
看起来是debug目录下有前面生成过的NMake 格式的文件。可以把debug目录下内容全删掉再来一次试试
