### ISSUE TITLE
About CPU and memory usage high

### ISSUE THREAD

**Issue by xiaohuizhang** [taosdata/TDengine#13422]
您好，我在测试中发现集群的资源使用有点不符合预期
环境如下：3个节点的集群，每个节点的资源配置是4核，32G 。一个超级表，300万-900万子表不等。
                  只有插入操作，没有查询操作，
                  每秒的入库量是20万-80万不等，依据资源的使用情况调整
问题： 经过一下午的测试，发现下面2个问题
           1. 内存的使用率居高，即使插入操作停止了，内存依然是只增不减，从一开始的5G已经增长到21G ，这是什么原因造成的？
           2. CPU经常会飙升至100%，经过观察是数据压缩的时候会出现，这是正常的吗？对于CPU的配置是否有配置要求？
           
![2022-06-02 17-59-38屏幕截图](https://user-images.githubusercontent.com/2887968/171606005-22d4d6f1-798f-44cc-8d15-3e43318739f2.png)

**Comment by fenghuazzm** [comment]
插入操作停止了不代表数据会立刻落盘，伴随大量的查询是会导致内存出现这种情况。可以查看预设的 buffer pool 大小：https://docs.taosdata.com/operation/planning

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
