### ISSUE TITLE
Remove duplicated data

### ISSUE THREAD

**Issue by lich0821** [taosdata/TDengine#13439]
**求助**

数据来自第三方（[12239](https://github.com/taosdata/TDengine/issues/12239)中有提及），数据每天更新但只有时间没有日期，需要自己补充日期。我将昨天的数据补充成了今天的日期（6月3日），于是TDengine里6月2日和6月3日的数据是一样的。现在希望把6月3号的数据删除。

查SQL手册和FAQ得知，目前TDengine不支持删除行。请问有什么方法可以解决该问题？谢谢～

我想到一个办法：创建新库和新表，将截止6月2日的数据写入到新的库表里。这些数据分散在3个库，每个库一张超级表，共大概1万张子表，数据量为：16608379110 + 316072090 + 226000882。但这方法看起来操作很复杂。

**Comment by fenghuazzm** [comment]
你这样做是可以的，现在社区版确实不支持删除行数据

**Comment by lich0821** [comment]
> 你这样做是可以的，现在社区版确实不支持删除行数据

好的，感谢确认。有样例SQL完成这个操作吗？

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
