### ISSUE TITLE
Remote connection and password change problems

### ISSUE THREAD

**Issue by tenyears94** [taosdata/TDengine#13484]
version：2.6.0.1
问题：
1、修改root密码，提示成功，但是实际上是没成功的。（此处建议可否参考redis，将端口、密码等放在`taos.cfg`文件内设置）；
2、远程连接失败，参考官网的IDEA连接，错误见下图；下载官方的`TDengineGUI`工具同样提示连接失败（本地客户端可正常连接，代码连接也没问题）
![image](https://user-images.githubusercontent.com/49542458/172053968-fa984564-5558-471a-a203-ae6dee497e47.png)

**Comment by fenghuazzm** [comment]
感谢反馈，2.6.0.1 修改密码目前确实有这个问题，正在修复中，下次发版会给解决

**Comment by fenghuazzm** [comment]
TDengineGUI 工具使用到了 RESTful 接口，服务端开启如下服务先：systemctl start taosadapter
