### ISSUE TITLE
与OPC的接口什么时候能开发完成

### ISSUE THREAD

**Issue by smhjs** [taosdata/TDengine#135]
我们是做工业大数据的，现在基本上是PI，phd。期待能无缝对接opc协议

**Comment by jtao1735** [comment]
早在我们计划之中，但人手不够，欢迎加入进来，作为contributor, 一起开发OPC接口

**Comment by eurake** [comment]
出设计文档

**Comment by guanshengliang** [comment]
您如果有相关资料，可以发给我参考一下
slguan@taosdata.com

**Comment by guanshengliang** [comment]
以便我评估一下工作量和启动时间
