### ISSUE TITLE
compile TDEngine on armv7 , Failure occurred

### ISSUE THREAD

**Issue by luhterluo** [taosdata/TDengine#13524]
/home/lutherluo/workspace/TDengine-develop/src/util/src/tcache.c:357:28: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
   if (ptNode->signature != (uint64_t)ptNode) {
                            ^
/home/lutherluo/workspace/TDengine-develop/src/util/src/tcache.c: In function 'taosCacheRelease':
/home/lutherluo/workspace/TDengine-develop/src/util/src/tcache.c:390:27: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
   if (pNode->signature != (uint64_t)pNode) {
                           ^
/home/lutherluo/workspace/TDengine-develop/src/util/src/tcache.c: In function 'taosCreateCacheNode':
/home/lutherluo/workspace/TDengine-develop/src/util/src/tcache.c:581:28: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
   pNewNode->signature    = (uint64_t)pNewNode;

**Comment by luhterluo** [comment]
Bellow is the cmake output :

cmake .. -DCPUTYPE=aarch64

[linux-devkit]:~/workspace/TDengine-develop/build> cmake .. -DCPUTYPE=aarch64 
-- The CXX compiler identification is GNU 6.2.1
-- Check for working CXX compiler: /home/lutherluo/ti-processor-sdk-linux-rt-am57xx-evm-04.03.00.05/linux-devkit/sysroots/x86_64-arago-linux/usr/bin/arm-linux-gnueabihf-g++
-- Check for working CXX compiler: /home/lutherluo/ti-processor-sdk-linux-rt-am57xx-evm-04.03.00.05/linux-devkit/sysroots/x86_64-arago-linux/usr/bin/arm-linux-gnueabihf-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Community directory: /home/lutherluo/workspace/TDengine-develop
-- The C compiler identification is GNU 6.2.1
-- Check for working C compiler: /home/lutherluo/ti-processor-sdk-linux-rt-am57xx-evm-04.03.00.05/linux-devkit/sysroots/x86_64-arago-linux/usr/bin/arm-linux-gnueabihf-gcc
-- Check for working C compiler: /home/lutherluo/ti-processor-sdk-linux-rt-am57xx-evm-04.03.00.05/linux-devkit/sysroots/x86_64-arago-linux/usr/bin/arm-linux-gnueabihf-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- build with TSZ enabled
-- The shell is: dash

-- The current os is Ubuntu
-- The current platform is Linux 32-bit
-- The distro is Ubuntu
-- input cpuType: aarch64
-- platform arch:arm64
-- The user specified osType is unknown: 
-- linux32 is defined
-- arm64 is defined
 Will _not_ build taos_tools! 
Enable lua
-- CMAKE_CXX_COMPILER_ID: GNU
-- Project source directory: /home/lutherluo/workspace/TDengine-develop
-- Project binary files output path: /home/lutherluo/workspace/TDengine-develop/build
-- Project executable files output path: /home/lutherluo/workspace/TDengine-develop/build/build/bin
-- Project library files output path: /home/lutherluo/workspace/TDengine-develop/build/build/lib
-- MVN is not installed and JDBC is not compiled
-- Build Debug Version as default
fatal: Not a git repository (or any of the parent directories): .git
-- git log result:
-- not a git repository
fatal: Not a git repository (or any of the parent directories): .git
-- git log result:
-- not a git repository
-- ============= compile version parameter information start ============= 
-- ver number:2.7.0.0
-- compatible ver number:2.0.0.0
-- community commit id:no git commit id
-- internal commit id:
-- build date:2022-06-07 03:20:18
-- ver type:stable
-- ver cpu:aarch64
-- os type:Linux
-- ============= compile version parameter information end  ============= 
-- Use the iconv functions in GLIBC

 use original embedded httpd 

-- Found FLEX: /usr/bin/flex (found version "2.6.4") 
-- Looking for SQLExecute
-- Looking for SQLExecute - not found
CMake Warning at src/connector/odbc/CMakeLists.txt:61 (message):
  odbc requirement not satisfied, please install unixodbc-dev.  Check detail
  in
  /home/lutherluo/workspace/TDengine-develop/build/CMakeFiles/CMakeError.log
Call Stack (most recent call first):
  src/connector/odbc/CMakeLists.txt:93 (check_odbc_requirement)


-- Configuring done
-- Generating done
-- Build files have been written to: /home/lutherluo/workspace/TDengine-develop/build

**Comment by sangshuduo** [comment]
目前还不支持交叉编译

**Comment by luhterluo** [comment]
It has been solved.
Thanks a lots!
