### ISSUE TITLE
taosd 服务起不来了，Failed to start TDengine server service.(vnode tsdb data file has wrong size , report to upper layer to fix it)

### ISSUE THREAD

**Issue by OrangeEffects** [taosdata/TDengine#13529]
taosd 服务起不来了
从日志看有文件损坏

06/06 20:46:05.324985 00007926 TDB ERROR vgId:45 failed to open DFileSet 1774 since No such file or directory, continue
06/06 20:46:05.327291 00007947 TDB ERROR vgId:44 data file /home/taos/data/vnode/vnode44/tsdb/data/v44f1100.smal-ver3533 has wrong size 3736 expected 6960, report to upper layer to fix it
06/06 20:46:05.330957 00007941 TDB ERROR vgId:40 data file /home/taos/data/vnode/vnode40/tsdb/data/v40f1881.smad-ver2882 has wrong size 144648 expected 147292, report to upper layer to fix it
06/06 20:46:05.331410 00007926 TDB ERROR vgId:45 data file /home/taos/data/vnode/vnode45/tsdb/data/v45f1774.smal-ver3357 not exist, report to upper layer to fix it
06/06 20:46:05.331453 00007926 TDB ERROR vgId:45 data file /home/taos/data/vnode/vnode45/tsdb/data/v45f1774.smad-ver3273 has wrong size 100984 expected 128776, report to upper layer to fix it
06/06 20:46:05.331866 00007926 TDB ERROR vgId:45 data file /home/taos/data/vnode/vnode45/tsdb/data/v45f1794.smal-ver3044 has wrong size 2964 expected 5416, report to upper layer to fix it
06/06 20:46:05.332263 00007945 TDB ERROR vgId:42 data file /home/taos/data/vnode/vnode42/tsdb/data/v42f1876.smad-ver3547 has wrong size 512 expected 3736, report to upper layer to fix it
06/06 20:46:05.353404 00007929 TDB ERROR vgId:48 data file /home/taos/data/vnode/vnode48/tsdb/data/v48f1096.smal-ver3495 has wrong size 193816 expected 197040, report to upper layer to fix it
06/06 20:46:05.356386 00007929 TDB ERROR vgId:48 data file /home/taos/data/vnode/vnode48/tsdb/data/v48f1855.smal-ver3558 has wrong size 2156 expected 3800, report to upper layer to fix it
06/06 20:46:05.364780 00007931 TDB ERROR vgId:50 data file /home/taos/data/vnode/vnode50/tsdb/data/v50f1096.smal-ver3609 has wrong size 145564 expected 148788, report to upper layer to fix it
06/06 20:46:05.365196 00007931 TDB ERROR vgId:50 data file /home/taos/data/vnode/vnode50/tsdb/data/v50f1156.smal-ver3452 has wrong size 2964 expected 5416, report to upper layer to fix it
06/06 20:46:05.367196 00007931 TDB ERROR vgId:50 data file /home/taos/data/vnode/vnode50/tsdb/data/v50f1777.smal-ver3422 has wrong size 41656 expected 44300, report to upper layer to fix it
06/06 20:46:05.368881 00007931 TDB ERROR vgId:50 data file /home/taos/data/vnode/vnode50/tsdb/data/v50f1870.smad-ver3114 has wrong size 512 expected 3156, report to upper layer to fix it
06/06 20:46:05.369051 00007930 TDB ERROR vgId:49 data file /home/taos/data/vnode/vnode49/tsdb/data/v49f1777.smal-ver3179 has wrong size 45360 expected 47812, report to upper layer to fix it
06/06 20:46:05.369388 00007932 TDB ERROR vgId:51 data file /home/taos/data/vnode/vnode51/tsdb/data/v51f1192.smal-ver3478 has wrong size 3736 expected 6188, report to upper layer to fix it
06/06 20:46:05.369943 00007930 TDB ERROR vgId:49 data file /home/taos/data/vnode/vnode49/tsdb/data/v49f1855.smal-ver3581 has wrong size 1320 expected 2128, report to upper layer to fix it
06/06 20:46:05.372109 00007927 TDB ERROR vgId:46 data file /home/taos/data/vnode/vnode46/tsdb/data/v46f1780.smad-ver3554 has wrong size 3156 expected 5800, report to upper layer to fix it
06/06 20:46:05.372304 00007928 TDB ERROR vgId:47 data file /home/taos/data/vnode/vnode47/tsdb/data/v47f1764.smal-ver3321 has wrong size 2964 expected 5416, report to upper layer to fix it
06/06 20:46:05.373716 00007928 TDB ERROR vgId:47 data file /home/taos/data/vnode
06/06 20:46:05.375017 00007928 TDB ERROR vgId:47 data file /home/taos/data/vnode
06/06 20:46:05.670884 00007926 VND ERROR vgId:45, failed to open tsdb(state: 2),
06/06 20:46:05.670933 00007926 DND ERROR vgId:45, failed to open vnode by thread
06/06 20:46:05.671135 00007947 VND ERROR vgId:44, failed to open tsdb(state: 2),
06/06 20:46:05.671166 00007947 DND ERROR vgId:44, failed to open vnode by thread
06/06 20:46:05.681374 00007941 VND ERROR vgId:40, failed to open tsdb(state: 2),
06/06 20:46:05.681413 00007941 DND ERROR vgId:40, failed to open vnode by thread
06/06 20:46:05.681551 00007945 VND ERROR vgId:42, failed to open tsdb(state: 2),
06/06 20:46:05.681583 00007945 DND ERROR vgId:42, failed to open vnode by thread
06/06 20:46:05.685989 00007929 VND ERROR vgId:48, failed to open tsdb(state: 2),
06/06 20:46:05.686020 00007929 DND ERROR vgId:48, failed to open vnode by thread
06/06 20:46:05.691219 00007932 VND ERROR vgId:51, failed to open tsdb(state: 2),
06/06 20:46:05.691242 00007932 DND ERROR vgId:51, failed to open vnode by thread
06/06 20:46:05.691252 00007927 VND ERROR vgId:46, failed to open tsdb(state: 2),
06/06 20:46:05.691275 00007927 DND ERROR vgId:46, failed to open vnode by thread
06/06 20:46:05.692223 00007930 VND ERROR vgId:49, failed to open tsdb(state: 2),
06/06 20:46:05.692249 00007930 DND ERROR vgId:49, failed to open vnode by thread
06/06 20:46:05.694734 00007928 VND ERROR vgId:47, failed to open tsdb(state: 2),
06/06 20:46:05.694753 00007928 DND ERROR vgId:47, failed to open vnode by thread
06/06 20:46:05.694773 00007931 VND ERROR vgId:50, failed to open tsdb(state: 2),
06/06 20:46:05.694799 00007931 DND ERROR vgId:50, failed to open vnode by thread
06/06 20:46:10.455685 00007908 DND ERROR there are total vnodes:25, failed:10

**Comment by OrangeEffects** [comment]
官方有没有容错或者恢复机制？
 (┬┬﹏┬┬)
损坏的部分数据丢掉也能接收，活过来就行

**Comment by OrangeEffects** [comment]
> 

Tdengine 2.4.0.5
centos 7
CPU 12C/24T
Mem 64G 
HDD 64T RAID5

硬件资源比较充足，磁盘没问题

出问题时：
没做任何运维操做，没有配置改动
有个客户端在常态化插入数据，插入的部分数据存在时间戳问题，被日志记录下来（查更早的日志，也有出现过数据时间戳问题，这个应该是业务层面问题，不至于导致服务挂掉）

**Comment by OrangeEffects** [comment]
出问题这一分钟的日志：

从“failed to insert data since Timestamp data out of range”能看出数据库大概还在正常跑
接着 VND 和 TDB 的一系列后台操作，看上去也没问题
然后 “DND there are total vnodes:25, opened:16” “DND ERROR there are total vnodes:25, failed:9” 服务就挂了


//--------------------------------------------------------------------------------------------------

06/06 12:10:05.244212 00007702 VND vgId:37, start commit, fver:4014153655 vver:4014923964
06/06 12:10:05.244236 00007685 TDB vgId:37 start to commit! keyFirst 1543547470000 keyLast 1654488061000 numOfRows 8247308 meta rows: 0
06/06 12:10:09.157943 00007706 WAL vgId:41, file:/home/taos/data/vnode/vnode41/wal/wal50, restore success, wver:4000301981
06/06 12:10:09.157987 00007706 VND vgId:41, start commit, fver:3999677947 vver:4000301981
06/06 12:10:09.158053 00007684 TDB vgId:41 start to commit! keyFirst 1543547621000 keyLast 1654487993000 numOfRows 6572761 meta rows: 0
06/06 12:10:09.836968 00007705 TDB ERROR vgId:40 table alm_ba86f2db82eede404 tid 22197 uid 11259371487997794 timestamp is out of range! now 1654488609836 minKey -1499111390164 maxKey 1655352609836$
06/06 12:10:09.837007 00007705 TDB ERROR vgId:40 failed to insert data since Timestamp data out of range
06/06 12:10:09.837432 00007705 TDB ERROR vgId:40 table v_ba86f2db82eede404 tid 22194 uid 11259371437665434 timestamp is out of range! now 1654488609837 minKey -1499111390163 maxKey 1655352609837 r$
06/06 12:10:09.837446 00007705 TDB ERROR vgId:40 failed to insert data since Timestamp data out of range
06/06 12:10:09.837558 00007705 TDB ERROR vgId:40 table veh_ba86f2db82eede404 tid 22198 uid 11259371504775256 timestamp is out of range! now 1654488609837 minKey -1499111390163 maxKey 1655352609837$
06/06 12:10:09.837570 00007705 TDB ERROR vgId:40 failed to insert data since Timestamp data out of range
06/06 12:10:09.837682 00007705 TDB ERROR vgId:40 table mot_ba86f2db82eede404 tid 22195 uid 11259371454442942 timestamp is out of range! now 1654488609837 minKey -1499111390163 maxKey 1655352609837$
06/06 12:10:09.837694 00007705 TDB ERROR vgId:40 failed to insert data since Timestamp data out of range
06/06 12:10:09.837796 00007705 TDB ERROR vgId:40 table mm_ba86f2db82eede404 tid 22199 uid 11259371521552882 timestamp is out of range! now 1654488609837 minKey -1499111390163 maxKey 1655352609837 $
06/06 12:10:09.837807 00007705 TDB ERROR vgId:40 failed to insert data since Timestamp data out of range
06/06 12:10:10.975368 00007705 VND vgId:40, start commit, fver:4005820628 vver:4006679321
06/06 12:10:10.975399 00007705 WAL vgId:40, file:/home/taos/data/vnode/vnode40/wal/wal50, restore success, wver:4006679321
06/06 12:10:10.975422 00007705 WAL vgId:40, file:/home/taos/data/vnode/vnode40/wal/wal51, will be restored
06/06 12:10:10.976596 00007705 WAL vgId:40, file:/home/taos/data/vnode/vnode40/wal/wal51, restore success, wver:4006679363
06/06 12:10:12.361168 00007683 TDB vgId:36 commit over, succeed
06/06 12:10:12.361194 00007683 VND vgId:36, commit over, fver:4009341760 vver:4009341760
06/06 12:10:12.361468 00007683 VND vgId:36, successed to write /home/taos/data/vnode/vnode36/version.json, fver:4009341760
06/06 12:10:13.977308 00007683 TDB vgId:40 start to commit! keyFirst 1626518402000 keyLast 1654487993000 numOfRows 8411549 meta rows: 0
06/06 12:10:14.093445 00007701 WAL vgId:36, wal:0x7fc1dd3f1670 file:/home/taos/data/vnode/vnode36/wal/wal51, it is removed
06/06 12:10:14.093652 00007701 VND vgId:36, sync role changed from offline to master
06/06 12:10:14.114687 00007701 VND vgId:53, load vnode cfg successfully, replcia:1
06/06 12:10:14.114697 00007701 VND vgId:53, dnode:1, wl03:6040
06/06 12:10:14.114900 00007701 VND vgId:53, read /home/taos/data/vnode/vnode53/version.json successfully, fver:290
06/06 12:10:14.218987 00007701 WAL vgId:53, file:/home/taos/data/vnode/vnode53/wal/wal1, will be restored
06/06 12:10:14.219045 00007701 WAL vgId:53, file:/home/taos/data/vnode/vnode53/wal/wal1, restore success, wver:0
06/06 12:10:14.219113 00007701 WAL vgId:53, wal:0x7fc1dd42b3f0 file:/home/taos/data/vnode/vnode53/wal/wal1, it is removed
06/06 12:10:14.219373 00007701 VND vgId:53, sync role changed from offline to master
06/06 12:10:19.147806 00007686 TDB vgId:52 commit over, succeed
06/06 12:10:19.147831 00007686 VND vgId:52, commit over, fver:3978935826 vver:3978935826
06/06 12:10:19.148280 00007686 VND vgId:52, successed to write /home/taos/data/vnode/vnode52/version.json, fver:3978935826
06/06 12:10:19.152123 00007685 TDB vgId:37 commit over, succeed
06/06 12:10:19.152135 00007685 VND vgId:37, commit over, fver:4014923964 vver:4014923964
06/06 12:10:19.152259 00007685 VND vgId:37, successed to write /home/taos/data/vnode/vnode37/version.json, fver:4014923964
06/06 12:10:21.444776 00007700 WAL vgId:52, wal:0x7fc1e14553b0 file:/home/taos/data/vnode/vnode52/wal/wal51, it is removed
06/06 12:10:21.444991 00007700 VND vgId:52, sync role changed from offline to master
06/06 12:10:21.669750 00007702 WAL vgId:37, wal:0x7fc1d53f09c0 file:/home/taos/data/vnode/vnode37/wal/wal52, it is removed
06/06 12:10:21.669942 00007702 VND vgId:37, sync role changed from offline to master
06/06 12:10:24.986820 00007684 TDB vgId:41 commit over, succeed
06/06 12:10:24.986844 00007684 VND vgId:41, commit over, fver:4000301981 vver:4000301981
06/06 12:10:24.987106 00007684 VND vgId:41, successed to write /home/taos/data/vnode/vnode41/version.json, fver:4000301981
06/06 12:10:26.930172 00007706 WAL vgId:41, wal:0x7fc1c53f17b0 file:/home/taos/data/vnode/vnode41/wal/wal50, it is removed
06/06 12:10:26.930367 00007706 VND vgId:41, sync role changed from offline to master
06/06 12:10:31.968980 00007683 TDB vgId:40 commit over, succeed
06/06 12:10:26.930367 00007706 VND vgId:41, sync role changed from offline to master
06/06 12:10:31.968980 00007683 TDB vgId:40 commit over, succeed
06/06 12:10:31.969006 00007683 VND vgId:40, commit over, fver:4006679321 vver:4006679363
06/06 12:10:31.969216 00007683 VND vgId:40, successed to write /home/taos/data/vnode/vnode40/version.json, fver:4006679321
06/06 12:10:34.263036 00007705 VND vgId:40, start commit, fver:4006679321 vver:4006679363
06/06 12:10:34.263150 00007686 TDB vgId:40 start to commit! keyFirst 1654180536000 keyLast 1654487992000 numOfRows 530 meta rows: 0
06/06 12:10:35.031707 00007686 TDB vgId:40 commit over, succeed
06/06 12:10:35.031738 00007686 VND vgId:40, commit over, fver:4006679363 vver:4006679363
06/06 12:10:35.032024 00007686 VND vgId:40, successed to write /home/taos/data/vnode/vnode40/version.json, fver:4006679363
06/06 12:10:35.240617 00007705 WAL vgId:40, wal:0x7fc1d13eff80 file:/home/taos/data/vnode/vnode40/wal/wal50, it is removed
06/06 12:10:35.240682 00007705 WAL vgId:40, wal:0x7fc1d13eff80 file:/home/taos/data/vnode/vnode40/wal/wal51, it is removed
06/06 12:10:35.240829 00007705 VND vgId:40, sync role changed from offline to master
06/06 12:10:35.240962 00007675 DND there are total vnodes:25, opened:16
06/06 12:10:35.240998 00007675 DND ERROR there are total vnodes:25, failed:9
06/06 12:10:35.241721 00007675 DND total vnodes:16 are all closed
06/06 12:10:35.280550 00007675 DND inter-dnodes RPC server is closed
06/06 12:10:35.328435 00007675 DND dnode inter-dnodes rpc client is closed
06/06 12:10:35.328561 00007675 UTL worker:vmgmt is closed
06/06 12:10:35.541977 00007682 UTL cache:qhandle_2 will be cleaned up
06/06 12:10:35.542860 00007682 WAL vgId:2, wal:0x7fc204034110 file:/home/taos/data/vnode/vnode2/wal/wal1, it is removed
06/06 12:10:36.044681 00007682 UTL cache:qhandle_29 will be cleaned up
06/06 12:10:36.065623 00007682 WAL vgId:29, wal:0x7fc1fc098ac0 file:/home/taos/data/vnode/vnode29/wal/wal1, it is removed
06/06 12:10:36.517582 00007682 UTL cache:qhandle_30 will be cleaned up
06/06 12:10:36.537995 00007682 WAL vgId:30, wal:0x7fc1f8098b50 file:/home/taos/data/vnode/vnode30/wal/wal1, it is removed
06/06 12:10:37.039841 00007682 UTL cache:qhandle_31 will be cleaned up
06/06 12:10:37.056647 00007682 WAL vgId:31, wal:0x7fc1f0098a90 file:/home/taos/data/vnode/vnode31/wal/wal1, it is removed
06/06 12:10:37.558811 00007682 UTL cache:qhandle_32 will be cleaned up
06/06 12:10:37.576135 00007682 WAL vgId:32, wal:0x7fc1f4098630 file:/home/taos/data/vnode/vnode32/wal/wal1, it is removed
06/06 12:10:38.027720 00007682 UTL cache:qhandle_33 will be cleaned up
06/06 12:10:38.044794 00007682 WAL vgId:33, wal:0x7fc1e8098640 file:/home/taos/data/vnode/vnode33/wal/wal1, it is removed
06/06 12:10:38.546181 00007682 UTL cache:qhandle_34 will be cleaned up
06/06 12:10:38.564790 00007682 WAL vgId:34, wal:0x7fc1ec098210 file:/home/taos/data/vnode/vnode34/wal/wal1, it is removed
06/06 12:10:39.016533 00007682 UTL cache:qhandle_35 will be cleaned up
06/06 12:10:39.027804 00007682 WAL vgId:35, wal:0x7fc1e009ad10 file:/home/taos/data/vnode/vnode35/wal/wal1, it is removed
06/06 12:10:39.529754 00007682 UTL cache:qhandle_36 will be cleaned up
06/06 12:10:39.583784 00007682 WAL vgId:36, wal:0x7fc1dd3f1670 file:/home/taos/data/vnode/vnode36/wal/wal1, it is removed
06/06 12:10:40.035542 00007682 UTL cache:qhandle_37 will be cleaned up
06/06 12:10:40.088896 00007682 WAL vgId:37, wal:0x7fc1d53f09c0 file:/home/taos/data/vnode/vnode37/wal/wal1, it is removed
06/06 12:10:40.540185 00007682 UTL cache:qhandle_38 will be cleaned up
06/06 12:10:40.591745 00007682 WAL vgId:38, wal:0x7fc1d93ef860 file:/home/taos/data/vnode/vnode38/wal/wal1, it is removed
06/06 12:10:41.043435 00007682 UTL cache:qhandle_39 will be cleaned up
06/06 12:10:41.093096 00007682 WAL vgId:39, wal:0x7fc1cd401860 file:/home/taos/data/vnode/vnode39/wal/wal1, it is removed
06/06 12:10:41.544826 00007682 UTL cache:qhandle_40 will be cleaned up
06/06 12:10:41.598382 00007682 WAL vgId:40, wal:0x7fc1d13eff80 file:/home/taos/data/vnode/vnode40/wal/wal1, it is removed
06/06 12:10:42.050069 00007682 UTL cache:qhandle_41 will be cleaned up
06/06 12:10:42.101722 00007682 WAL vgId:41, wal:0x7fc1c53f17b0 file:/home/taos/data/vnode/vnode41/wal/wal1, it is removed
06/06 12:10:42.553453 00007682 UTL cache:qhandle_52 will be cleaned up
06/06 12:10:42.600370 00007682 WAL vgId:52, wal:0x7fc1e14553b0 file:/home/taos/data/vnode/vnode52/wal/wal1, it is removed
06/06 12:10:42.553453 00007682 UTL cache:qhandle_52 will be cleaned up
06/06 12:10:42.600370 00007682 WAL vgId:52, wal:0x7fc1e14553b0 file:/home/taos/data/vnode/vnode52/wal/wal1, it is removed
06/06 12:10:43.052112 00007682 UTL cache:qhandle_53 will be cleaned up
06/06 12:10:43.052589 00007682 WAL vgId:53, wal:0x7fc1dd42b3f0 file:/home/taos/data/vnode/vnode53/wal/wal1, it is removed
06/06 12:10:43.054422 00007675 DND dnode vwrite is closed
06/06 12:10:43.054624 00007675 UTL worker:vfetch is closed
06/06 12:10:43.055611 00007675 UTL worker:vquery is closed
06/06 12:10:43.751452 00007675 WAL wal module is cleaned up
06/06 12:10:43.752155 00007675 DND Failed to start TDengine, please check the log at:/home/taos/log

**Comment by OrangeEffects** [comment]
找到出问题的关键时间点了：

start commit ，提交了大量数据，写文件，操作没有完成（没有等到 commit over）
shut down signal is 6 意思就是程序崩溃了（大概就这几个情况：内存多次free、执行abort函数、执行assert函数）
new note 是服务重启，新的一轮，后边就起不来了


06/06 12:08:32.942529 00101292 SDB vgId:1, update mnodes role, replica:1
06/06 12:08:32.942540 00101292 SDB vgId:1, mnode:1, role:master
06/06 12:08:32.942548 00101292 MND vgId:1, update mnodes epSet, numOfMnodes:1
06/06 12:08:32.942557 00101292 MND vgId:1, mnodes epSet is set, num:1 inUse:0
06/06 12:08:32.942564 00101292 MND vgId:1, mnode:1, fqdn:wl03 shell:6030 peer:6035
06/06 12:08:32.949746 00101292 MND WARN show type:show grants is not support
06/06 12:08:34.299847 00101272 VND vgId:40, start commit, fver:4005820628 vver:4006679321
06/06 12:08:34.300438 00101213 TDB vgId:40 start to commit! keyFirst 1626518402000 keyLast 1654487993000 numOfRows 8411549 meta rows: 0
06/06 12:08:34.690710 00101213 DND shut down signal is 6
06/06 12:08:34.690758 00101213 DND sender PID:101201 cmdline:/usr/bin/taosd
06/06 12:09:27.609707 00007675 ==================================================
06/06 12:09:27.609720 00007675 ===================  new note  ===================
06/06 12:09:27.609727 00007675 ==================================================
06/06 12:09:27.609763 00007675 DND step:dnode-tfile is initialized
06/06 12:09:27.609780 00007675 DND step:dnode-rpc is initialized

**Comment by fenghuazzm** [comment]
好的，我们看下

**Comment by OrangeEffects** [comment]
gdb 调试core dump文件

发现写(vnode/vnode40/tsdb/data/v40f1881.smad-ver2882)文件时崩溃了
定位到代码 ASSERT(pDFile->info.size == toffset)
查看变量发现这两个数确实不一致(size = 135424 , toffset = 144648)


//-----------
gdb

gdb /usr/bin/taosd /core.101201
...
Core was generated by `/usr/bin/taosd'.
Program terminated with signal 6, Aborted.
#0  0x00007fd68f122387 in raise () from /lib64/libc.so.6

(gdb) bt
#0  0x00007fd68f122387 in raise () from /lib64/libc.so.6
#1  0x00007fd68f123bb8 in abort () from /lib64/libc.so.6
#2  0x00007fd68f11b1a6 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007fd68f11b252 in __assert_fail () from /lib64/libc.so.6
#4  0x00007fd68fdea732 in tsdbAppendDFile (offset=0x7fd67d3aac30, nbyte=100, buf=0x7fcdf44071a8, pDFile=0x7fd67d3abbe0)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/inc/tsdbFile.h:260
#5  tsdbWriteBlockImpl (pRepo=0x7fd6340010e0, pTable=0x7fd6344d3f80, pDFile=0x7fd67d3ab960, pDFileAggr=0x7fd67d3abbe0, pDataCols=0x7fcdf41f00c0, pBlock=0x7fd67d3aaf60, isLast=false, isSuper=true,
    ppBuf=0x7fd67d3ab7f8, ppCBuf=0x7fd67d3ab800, ppExBuf=0x7fd67d3ab808) at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbCommit.c:1196
#6  0x00007fd68fdeabe4 in tsdbWriteBlock (pCommith=0x7fd67d3ab100, pDFile=0x7fd67d3ab960, pDataCols=0x7fcdf41f00c0, pBlock=0x7fd67d3aaf60, isLast=false, isSuper=true)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbCommit.c:1227
#7  0x00007fd68fdeae80 in tsdbCommitMemData (pCommith=0x7fd67d3ab100, pIter=0x7fcdf40292c0, keyLimit=1626601808999, toData=true)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbCommit.c:1278
#8  0x00007fd68fde8f1a in tsdbCommitToTable (pCommith=0x7fd67d3ab100, tid=8312) at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbCommit.c:1006
#9  0x00007fd68fde7cd1 in tsdbCommitToFile (pCommith=0x7fd67d3ab100, pSet=0x7fd482b57490, fid=1882) at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbCommit.c:742
#10 0x00007fd68fde790f in tsdbCommitTSData (pRepo=0x7fd6340010e0) at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbCommit.c:667
#11 0x00007fd68fde36d2 in tsdbCommitData (pRepo=0x7fd6340010e0) at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbCommit.c:108
#12 0x00007fd68fdd585b in tsdbLoopCommit (arg=0x0) at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbCommitQueue.c:188
#13 0x00007fd68f4c1ea5 in start_thread () from /lib64/libpthread.so.0
#14 0x00007fd68f1ea96d in clone () from /lib64/libc.so.6

//-----------
查看源码
/src/tsdb/inc/tsdbFile.h


// =============== SDFile
typedef struct {
  uint32_t magic;
  uint32_t len;
  uint32_t totalBlocks;
  uint32_t totalSubBlocks;
  uint32_t offset;
  uint64_t size;
  uint64_t tombSize;
  uint32_t fver;
} SDFInfo;

typedef struct {
  SDFInfo info;
  TFILE   f;
  int     fd;
  uint8_t state;
} SDFile;

static FORCE_INLINE int tsdbAppendDFile(SDFile* pDFile, void* buf, int64_t nbyte, int64_t* offset) {
  ASSERT(TSDB_FILE_OPENED(pDFile));

  int64_t toffset;

  if ((toffset = tsdbSeekDFile(pDFile, 0, SEEK_END)) < 0) {
    return -1;
  }

  ASSERT(pDFile->info.size == toffset);  //------- line 260

  if (offset) {
    *offset = toffset;
  }

  if (tsdbWriteDFile(pDFile, buf, nbyte) < 0) {
    return -1;
  }

  pDFile->info.size += nbyte;

  return (int)nbyte;
}

//-----------
继续gdb

(gdb) f 4
#4  0x00007fd68fdea732 in tsdbAppendDFile (offset=0x7fd67d3aac30, nbyte=100, buf=0x7fcdf44071a8, pDFile=0x7fd67d3abbe0)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/inc/tsdbFile.h:260
260     in /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/inc/tsdbFile.h

(gdb) info locals
toffset = 144648

(gdb) p *(SDFile *) 0x7fd67d3abbe0
$1 = {info = {magic = 3911217141, len = 0, totalBlocks = 0, totalSubBlocks = 0, offset = 0, size = 135424, tombSize = 0, fver = 0}, f = {level = 0, id = 0,
    rname = "vnode/vnode40/tsdb/data/v40f1881.smad-ver2882", '\000' <repeats 82 times>, aname = "/home/taos/data/vnode/vnode40/tsdb/data/v40f1881.smad-ver2882", '\000' <repeats 66 times>},
  fd = 72, state = 0 '\000'}

**Comment by zhangbiyun** [comment]
@OrangeEffects 您用集群了吗？

**Comment by gccgdb1234** [comment]
这个修复 可以让 taosd 不会crash，但taosd重启之后能够从文件的错误状态中恢复吗？

**Comment by zhangbiyun** [comment]
> 这个修复 可以让 taosd 不会crash，但taosd重启之后能够从文件的错误状态中恢复吗？

如果已经破坏的数据文件没有被备份，很难恢复了。
这个修正的效果，可以在commit失败后，不会像assert那样crash，而且在失败返回前打开的数据文件被写回磁盘。
正常写回磁盘的文件没有被破坏，所以重启taosd会正常启动。

PS：由于@OrangeEffects的案例，比较紧急，所以就没有按照正常的流程来复现，收集日志来处理，
而是计划把这个修正直接应用在客户场景里面验证。

**Comment by gccgdb1234** [comment]
这个修复 有些问题，详细的意见见 PR
