### ISSUE TITLE
"open file:/proc/1251/io failed", error in ARMV7l ti-board environment

### ISSUE THREAD

**Issue by luhterluo** [taosdata/TDengine#13573]
The following error occurred while starting the taosd ,  Root privileges,   In ARMV7l ti-board environment

How to solve it ?  "open file:/proc/1251/io failed", 

root@AM57xx-Tronlong:/run/media/sda2/home/root/TDEngine/bin# ./taosd                 
06/07 17:57:02.428275 00001251 DND start to initialize TDengine
06/07 17:57:02.428711 00001251 DND step:dnode-tfile is initialized
06/07 17:57:02.428868 00001251 DND step:dnode-rpc is initialized
06/07 17:57:02.429845 00001251 UTL localEp is: AM57xx-Tronlong:6030
06/07 17:57:02.430948 00001251 UTL ERROR open file:/proc/1251/io failed
06/07 17:57:02.431422 00001251 UTL WARN timezone not configured, set to system default:Asia/Shanghai (CST, +0800)
06/07 17:57:02.431595 00001251 UTL WARN locale not configured, set to system default:C
06/07 17:57:02.431738 00001251 UTL WARN can't get locale and charset from system, set it to UTF-8
06/07 17:57:02.432078 00001251 UTL    check global cfg completed
06/07 17:57:02.432216 00001251 UTL ==================================
06/07 17:57:02.432346 00001251 UTL    taos config & system info:
06/07 17:57:02.432468 00001251 UTL ==================================
06/07 17:57:02.432660 00001251 UTL  firstEp:                AM57xx-Tronlong:6030 
06/07 17:57:02.432795 00001251 UTL  secondEp:               AM57xx-Tronlong:6030 
06/07 17:57:02.432920 00001251 UTL  fqdn:                   AM57xx-Tronlong 
06/07 17:57:02.433044 00001251 UTL  serverPort:             6030 
06/07 17:57:02.433167 00001251 UTL  configDir:              /etc/taos 
06/07 17:57:02.433289 00001251 UTL  logDir:                 /var/volatile/log/taos 
06/07 17:57:02.433413 00001251 UTL  scriptDir:              /etc/taos

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
