### ISSUE TITLE
我弱鸡，请问下，速度提升的主要因素是？因为纯C语言 还是 架构设计 还是？

### ISSUE THREAD

**Issue by guotong1988** [taosdata/TDengine#136]
对速度提升的贡献占比是？
感谢！

**Comment by eurake** [comment]
当然是架构设计, 根据物联网数据结构的特征, 主要存储引擎的实现

**Comment by sailing0505** [comment]
> 对速度提升的贡献占比是？
> 感谢！
我的理解是因为对物联网的使用特点做了特殊的优化，相应的存储结构就保证了数据查询跟聚合的高性能。不算是一个通用的DB，但是很适合物联网的场景。你可以看看这两篇博客，写的不错
https://www.taosdata.com/blog/2019/07/11/tdengine%e6%9e%b6%e6%9e%84%e8%ae%be%e8%ae%a1%e4%b8%8e%e5%ad%98%e5%82%a8%e7%bb%93%e6%9e%84/
https://www.taosdata.com/blog/2019/07/09/%e7%89%a9%e8%81%94%e7%bd%91%e3%80%81%e8%bd%a6%e8%81%94%e7%bd%91%e3%80%81%e5%b7%a5%e4%b8%9a%e4%ba%92%e8%81%94%e7%bd%91%e5%a4%a7%e6%95%b0%e6%8d%ae%e5%b9%b3%e5%8f%b0%ef%bc%8c%e4%b8%ba%e4%bb%80%e4%b9%88/

**Comment by oknochoice** [comment]
a

**Comment by oknochoice** [comment]
作者含糊不愿意明说
也没有和mongodb比较
架构没看出来
个人判断主要是 对写入成功的判断标准不一样
有的入内存算成功 有的入磁盘算成功 有的入备份磁盘算成功
细节不说 没法判断

**Comment by guanshengliang** [comment]
请看白皮书，应该已经讲的很清楚，没有含糊
或者一定要了解细节，可以钻研下代码

**Comment by guanshengliang** [comment]
速度提升核心点架构设计，这毫无疑问。
TDengine的数据模型决定了其速度必然优于其他产品，当然C语言相比java语言开发的系列产品，性能上肯定也是有所提升的。

**Comment by oknochoice** [comment]
我当然看了啊
数据的连续性 存放？完全胡扯了。
每个设备的数据连续存放快，还是所有设备的数据混合起来连续存放快？
当然是后者了。因为后者更容易达到磁盘上的连续性写。

**Comment by oknochoice** [comment]
看代码也要有的放矢 你告我 TDengine的写入成功的 判断标准是什么 我去验证。

**Comment by guanshengliang** [comment]
不能只考虑写入速度，还要考虑查询速度。

您说的所有设备的数据混合起来连续存放，一定是写入最快的。

但是查询某一台设备时，也需要遍历这个数据集，那么查询速度会慢。

需要在这之间进行平衡，才能达到最优性能表写。

写入流程可以看下图

![image](https://user-images.githubusercontent.com/28882257/61762763-989ce780-ae05-11e9-9162-ad35b5747721.png)

**Comment by cling60** [comment]
> 看代码也要有的放矢 你告我 TDengine的写入成功的 判断标准是什么 我去验证。

![image](https://user-images.githubusercontent.com/5766489/61763013-68097d80-ae06-11e9-8ddb-cb875de940b3.png)

已经写出来了，如果在落盘之前宕机是不是数据就丢了？这应该是你关心的

**Comment by guanshengliang** [comment]
@cling60  正解

TDengine通过Commitlog来保证宕机数据不丢失，这个Mysql的机制是相同的

**Comment by cling60** [comment]
> @cling60 正解
> 
> TDengine通过Commitlog来保证宕机数据不丢失，这个Mysql的机制是相同的

看了一下代码，这块上面的兄弟担心的是对的，Commitlog也没有立即写入文件，这是决定性能的关键，也就是说如果突然宕机，近期数据会丢失，要看业务场景是否可以忍受了

**Comment by guanshengliang** [comment]
Commitlog采用内存映射文件进行，写入commitlog就等于写入硬盘的，参考

https://blog.csdn.net/qq_14989227/article/details/79328089

**Comment by zhangqhn** [comment]
> Commitlog采用内存映射文件进行，写入commitlog就等于写入硬盘的，参考
> 
> https://blog.csdn.net/qq_14989227/article/details/79328089

性能和数据安全性是一个矛盾， 前面的兄弟说 “突然宕机，近期数据会丢失” 的问题：
如果要最高的安全性，那么每条写入的数据必须要刷盘， 不可能有高的写入性能（批量写入除外，比如：每次写入1000条数据，以1000条数据做一次刷盘，也能提供较高的性能）。
就算在关系库mysql的innodb存储引擎中，也提供了 innodb_flush_log_at_try_commit 参数来平衡性能和安全性的平衡。
但是，针对物联网场景，数据安全性要求比关系库低，可以更偏向高性能。但是不能简单理解为“Commitlog采用内存映射文件进行，写入commitlog就等于写入硬盘的”。

**Comment by guanshengliang** [comment]
Commitlog是可以保证数据安全性的，很多做实时数据库的公司也是采用的这种方法

**Comment by zhangqhn** [comment]
这么用肯定是没问题的，而且在目前来说，这也是最适合物联网的方式， 上面的意思是，一定不能简单的认为所有数据都是安全的， 对于最新写入的数据，发生宕机时确实会丢一部分数据，至于丢多少数据，取决于上次刷新到磁盘后又写入了多少数据...

**Comment by cling60** [comment]
> 这么用肯定是没问题的，而且在目前来说，这也是最适合物联网的方式， 上面的意思是，一定不能简单的认为所有数据都是安全的， 对于最新写入的数据，发生宕机时确实会丢一部分数据，至于丢多少数据，取决于上次刷新到磁盘后又写入了多少数据...

所以要根据具体的业务情况做出选择，可以在写入内存之后msync测试性能是多少，应该会降低不少

**Comment by guanshengliang** [comment]
@zhangqhn  看来研究颇多

但是回到这个Issue要讨论的问题，TDengine的高性能源于它对于时序数据的一系列假设，及针对这些假设所做的创新设计：
1：一台设备一张表，让一台设备的数据插入查询性能无人能比；
2：超级表，解决表数量过多，表之间的聚合问题

**Comment by zhangqhn** [comment]
我是做实时数据库出来的， 其实“一台设备一张表” 产生的影响是什么？ 
无非是：每个表（或设备） 使用一个 数据块， 而不会像关系库一样，多个设备的数据写入到一个块中。 
实时库就是这么做的， 只是叫法不一样而已，实时库中叫 测点，不同的测点会分配不同的块， 其他的时序库叫 Metric , 你们只是换了个名字，并没有实际的创新....

**Comment by guanshengliang** [comment]
很多方法都是共通的，不存在绝对的革新，看怎么理解了

**Comment by zhangqhn** [comment]
> 很多方法都是共通的，不存在绝对的革新，看怎么理解了

实时库的应用比较窄，不是那么多人能接触到， 
而且：不管是国外的 PI, edna 还是国内的庚顿、麦杰 等，都不提供产品下载的链接，想用都用不到。
另外，由于各种原因，实时库都很难用（厂家会提供一堆配套的产品，比如：组态，数据采集等，尽量不写代码，如果写代码做项目真的真的很难用）， 里面还有一些特有的概念，
想要推广更是难上加难， 能顺应市场的需求，推出一款好用的产品，本身就很有意义，而且：并不是说一个产品必须要有独一无二的创新。
最后： 据我所知（我也不能知道所有实时库产品的），实时库 没有做 多个测点的聚合查询，也就是你们提供的超级表。

**Comment by guanshengliang** [comment]
应该有些公司的产品是有的，或者是数据库层在做，或者是应用层在做，但是开源的产品目前应该还没有。
不论怎么样，开源还是值得鼓励的，可以让大家更了解相关技术。从21世纪开始，中国IT技术的发展还是比较依赖于开源产品的。

**Comment by oknochoice** [comment]
> 不能只考虑写入速度，还要考虑查询速度。
> 
> 您说的所有设备的数据混合起来连续存放，一定是写入最快的。
> 
> 但是查询某一台设备时，也需要遍历这个数据集，那么查询速度会慢。
> 
> 需要在这之间进行平衡，才能达到最优性能表写。
> 
> 写入流程可以看下图
> 
> ![image](https://user-images.githubusercontent.com/28882257/61762763-989ce780-ae05-11e9-9162-ad35b5747721.png)


结果是什么呢？
难道就是 你以写入内存的速度去对比 别人写入磁盘的速度吗 ？
所以 要对比 也要对比 sqlite或mongodb的内存数据库。

而且 物联网数据库 主要是要应对海量数据的写 而不是读
20w个设备 闲时 每3秒生成一条数据
一秒要入库 8w条数据
这最低要求了吧 你觉得哪个数据库能写得进去？

**Comment by oknochoice** [comment]
> > Commitlog采用内存映射文件进行，写入commitlog就等于写入硬盘的，参考
> > https://blog.csdn.net/qq_14989227/article/details/79328089
> 
> 性能和数据安全性是一个矛盾， 前面的兄弟说 “突然宕机，近期数据会丢失” 的问题：
> 如果要最高的安全性，那么每条写入的数据必须要刷盘， 不可能有高的写入性能（批量写入除外，比如：每次写入1000条数据，以1000条数据做一次刷盘，也能提供较高的性能）。
> 就算在关系库mysql的innodb存储引擎中，也提供了 innodb_flush_log_at_try_commit 参数来平衡性能和安全性的矛盾。
> 但是，针对物联网场景，数据安全性要求比关系库低，可以更偏向高性能。但是不能简单理解为“Commitlog采用内存映射文件进行，写入commitlog就等于写入硬盘的”，写入到最终落盘还是有个时间段的。

刷盘得间隔 以文件系统的 page size 大小最为合适

**Comment by zhangqhn** [comment]
> > > Commitlog采用内存映射文件进行，写入commitlog就等于写入硬盘的，参考
> > > https://blog.csdn.net/qq_14989227/article/details/79328089
> > 
> > 
> > 性能和数据安全性是一个矛盾， 前面的兄弟说 “突然宕机，近期数据会丢失” 的问题：
> > 如果要最高的安全性，那么每条写入的数据必须要刷盘， 不可能有高的写入性能（批量写入除外，比如：每次写入1000条数据，以1000条数据做一次刷盘，也能提供较高的性能）。
> > 就算在关系库mysql的innodb存储引擎中，也提供了 innodb_flush_log_at_try_commit 参数来平衡性能和安全性的矛盾。
> > 但是，针对物联网场景，数据安全性要求比关系库低，可以更偏向高性能。但是不能简单理解为“Commitlog采用内存映射文件进行，写入commitlog就等于写入硬盘的”，写入到最终落盘还是有个时间段的。
> 
> 刷盘得间隔 以文件系统的 page size 大小最为合适

这里说的间隔有时间的间隔，也有写入数据量的间隔， 对于机械盘来说，文件系统的 page size 太小，性能不会高，这个需要实际测试调整的...

**Comment by guanshengliang** [comment]
@oknochoice  说话不用总是带着情绪，完全可以慢慢聊
TDengine当然不是内存库，前面的写入流程图是一种写入策略。
如果确实有兴趣，可以按照下面的例子试试写入和查询，具体可以参考
https://www.taosdata.com/blog/2019/07/19/tdengine与influxdb对比测试/

**Comment by foobar** [comment]
感谢开源这个优秀的时序数据库。看了这个对比测试，感觉不是apple2apple的，因为influxdb默认是同步写磁盘的，而tdengine异步落盘，所以写入性能的差距是misleading的。希望能完善下测试的参数配置说明。

**Comment by oknochoice** [comment]
> @oknochoice 说话不用总是带着情绪，完全可以慢慢聊
> TDengine当然不是内存库，前面的写入流程图是一种写入策略。
> 如果确实有兴趣，可以按照下面的例子试试写入和查询，具体可以参考
> [https://www.taosdata.com/blog/2019/07/19/tdengine与influxdb对比测试/](https://www.taosdata.com/blog/2019/07/19/tdengine%E4%B8%8Einfluxdb%E5%AF%B9%E6%AF%94%E6%B5%8B%E8%AF%95/)

我就是 带情绪了 怎么招吧？
我提出的质疑 一个也不回答
就吹 数据库 NB
你要说明 为什么快？ 目前的结果就是 以内存写入速度 比 人家磁盘写入速度嘛
当然也要 回应 一个小公司 的 每秒8w入库 到底是 应该 解决 写还是读？

**Comment by oknochoice** [comment]
> > > > Commitlog采用内存映射文件进行，写入commitlog就等于写入硬盘的，参考
> > > > https://blog.csdn.net/qq_14989227/article/details/79328089
> > > 
> > > 
> > > 性能和数据安全性是一个矛盾， 前面的兄弟说 “突然宕机，近期数据会丢失” 的问题：
> > > 如果要最高的安全性，那么每条写入的数据必须要刷盘， 不可能有高的写入性能（批量写入除外，比如：每次写入1000条数据，以1000条数据做一次刷盘，也能提供较高的性能）。
> > > 就算在关系库mysql的innodb存储引擎中，也提供了 innodb_flush_log_at_try_commit 参数来平衡性能和安全性的矛盾。
> > > 但是，针对物联网场景，数据安全性要求比关系库低，可以更偏向高性能。但是不能简单理解为“Commitlog采用内存映射文件进行，写入commitlog就等于写入硬盘的”，写入到最终落盘还是有个时间段的。
> > 
> > 
> > 刷盘得间隔 以文件系统的 page size 大小最为合适
> 
> 这里说的间隔有时间的间隔，也有写入数据量的间隔， 对于机械盘来说，文件系统的 page size 太小，性能不会高，这个需要实际测试调整的...

永远是 B树节点大小 达到的 page size 后 速度才会最大
实际情况 是不提供接口 配置这个选项
所以才需要 实际测试

**Comment by zhangqhn** [comment]
> > > > > Commitlog采用内存映射文件进行，写入commitlog就等于写入硬盘的，参考
> > > > > https://blog.csdn.net/qq_14989227/article/details/79328089
> > > > 
> > > > 
> > > > 性能和数据安全性是一个矛盾， 前面的兄弟说 “突然宕机，近期数据会丢失” 的问题：
> > > > 如果要最高的安全性，那么每条写入的数据必须要刷盘， 不可能有高的写入性能（批量写入除外，比如：每次写入1000条数据，以1000条数据做一次刷盘，也能提供较高的性能）。
> > > > 就算在关系库mysql的innodb存储引擎中，也提供了 innodb_flush_log_at_try_commit 参数来平衡性能和安全性的矛盾。
> > > > 但是，针对物联网场景，数据安全性要求比关系库低，可以更偏向高性能。但是不能简单理解为“Commitlog采用内存映射文件进行，写入commitlog就等于写入硬盘的”，写入到最终落盘还是有个时间段的。
> > > 
> > > 
> > > 刷盘得间隔 以文件系统的 page size 大小最为合适
> > 
> > 
> > 这里说的间隔有时间的间隔，也有写入数据量的间隔， 对于机械盘来说，文件系统的 page size 太小，性能不会高，这个需要实际测试调整的...
> 
> 永远是 B树节点大小 达到的 page size 后 速度才会最大
> 实际情况 是不提供接口 配置这个选项
> 所以才需要 实际测试

对于机械盘来说，每次写入都包括寻道时间和写入时间，写入时间与写入数据的长度和磁盘转速有关，如果：页大小为 4KB， 要写入40KB的内容。
（1）写10次，每次4K，这里会有10次寻道时间。
（2）写1次，40K，这里只有1次寻道时间。
而写入时间是一定的，所以1次写入会快过10次写入。

固态盘不需要寻道， 另说...

**Comment by guanshengliang** [comment]
@oknochoice 我不会再回答你的问题，我也没义务回答你的问题

这个帖子讨论的比较热烈，接下来我会邀请跟多的人参与讨论

**Comment by guanshengliang** [comment]
commitlog可以保证数据不丢

当客户端发起一次请求时，只要TDengine的服务端返回写入成功，那这条数据就不会丢

可以实际测试，启动一个客户端不断写入数据，成功写入的数据记录下来，同时启停数据库服务，验证一下数据是否丢失

**Comment by zhangqhn** [comment]
这个测试应该是 给服务器断电， 因为已经写入到 内存映射文件中后，启停数据库服务肯定不会丢的。

**Comment by guanshengliang** [comment]
@zhangqhn  说的对，上面提到的确实只是TDengine发生异常情况下的场景

**Comment by foobar** [comment]
@guanshengliang
写内存映射文件与落盘是两回事，你man msync看下。
写入场景瓶颈是io,所以与influxdb的对比是有问题的。
掉电场景是每个数据库都需要处理的，内存映射方式会导致问题更复杂。从代码看，partial write好像没有recover处理。

**Comment by oknochoice** [comment]
> > > > > > Commitlog采用内存映射文件进行，写入commitlog就等于写入硬盘的，参考
> > > > > > https://blog.csdn.net/qq_14989227/article/details/79328089
> > > > > 
> > > > > 
> > > > > 性能和数据安全性是一个矛盾， 前面的兄弟说 “突然宕机，近期数据会丢失” 的问题：
> > > > > 如果要最高的安全性，那么每条写入的数据必须要刷盘， 不可能有高的写入性能（批量写入除外，比如：每次写入1000条数据，以1000条数据做一次刷盘，也能提供较高的性能）。
> > > > > 就算在关系库mysql的innodb存储引擎中，也提供了 innodb_flush_log_at_try_commit 参数来平衡性能和安全性的矛盾。
> > > > > 但是，针对物联网场景，数据安全性要求比关系库低，可以更偏向高性能。但是不能简单理解为“Commitlog采用内存映射文件进行，写入commitlog就等于写入硬盘的”，写入到最终落盘还是有个时间段的。
> > > > 
> > > > 
> > > > 刷盘得间隔 以文件系统的 page size 大小最为合适
> > > 
> > > 
> > > 这里说的间隔有时间的间隔，也有写入数据量的间隔， 对于机械盘来说，文件系统的 page size 太小，性能不会高，这个需要实际测试调整的...
> > 
> > 
> > 永远是 B树节点大小 达到的 page size 后 速度才会最大
> > 实际情况 是不提供接口 配置这个选项
> > 所以才需要 实际测试
> 
> 对于机械盘来说，每次写入都包括寻道时间和写入时间，写入时间与写入数据的长度和磁盘转速有关，如果：页大小为 4KB， 要写入40KB的内容。
> （1）写10次，每次4K，这里会有10次寻道时间。
> （2）写1次，40K，这里只有1次寻道时间。
> 而写入时间是一定的，所以1次写入会快过10次写入。
> 
> 固态盘不需要寻道， 另说...

当然不讨论固体硬盘了
机械硬盘模型 以寻道时间计算 忽略其他时间
问题是一次入盘 并不是一次寻道啊 包括日志 索引等是需要各自寻道的
你说的仅仅是 数据部分 
我说的是 最好避免日志索引等同一页上的重复寻轨

**Comment by oknochoice** [comment]
> @oknochoice 我不会再回答你的问题，我也没义务回答你的问题
> 
> 这个帖子讨论的比较热烈，接下来我会邀请跟多的人参与讨论

你从来就没回答过我的问题 好吗？
我问你 为什么快？
你跟我讨论落盘 间隔
问题是你和其他数据库 比较时
落盘 更本就不参与 入库是否成功

真是费劲

**Comment by WangYangA9** [comment]
冷静，冷静，好好的技术讨论没必要也不应该带上火气

**Comment by jtao1735** [comment]
TDengine第一版就有msync强制落盘，后来我们考虑到有多副本，而且每个副本也都有commit log, 因此就去掉了msync。加上之后，大概写入的速度会降低30%。即使降低30%，写入速度也远超InfluxDB。速度快是由我们数据模型决定的。对于单机版，我们或许可以加一个选项，采用强制落盘还是不强制落盘。

**Comment by jtao1735** [comment]
要让数据快，无论是插入还是查询，就是要最大程度的减少磁盘IO次数，减少网络IO次数。建议大家多实际测试一下，光靠嘴巴说没说服力。欢迎把源码修改，加上msync之后测，与InfluxDB做对比。而且建议只用1G内存，但写入100G的数据来测。

**Comment by riyun1989** [comment]
怼天怼地怼空气的不好，技术讨论嘛要就事论事，不要夹带个人情绪大兄dei，大家都是成年人了，这个圈子说大不大说小不小，万一你周围同事或者领导看到你这样，多尴尬啊不是

**Comment by runzhiwang** [comment]
TDengine适用于物联网，那有哪些场景InfluxDB能用，TDengine用不了的吗？

**Comment by oknochoice** [comment]
> TDengine第一版就有msync强制落盘，后来我们考虑到有多副本，而且每个副本也都有commit log, 因此就去掉了msync。加上之后，大概写入的速度会降低30%。即使降低30%，写入速度也远超InfluxDB。速度快是由我们数据模型决定的。对于单机版，我们或许可以加一个选项，采用强制落盘还是不强制落盘。

不是要强制落盘，是要入盘的时候返回入库成功。
而且io的多少 基本是业务需求。
要不然别人比较数据库的时候 都比 单条录入和批量录入的情况呢？

我们讨论为什么会有 10x速？
现在最起码你承认 降30% 就是7x速。
现在慢慢研究为什么比别人快7x。

你的数据库快 绝不是一句 模型先进 就能比别人快10倍。

**到现在为止 你们对我提出的 和他家数据库比较时 入库成功标准是什么 都没有正面回答**
顾左右而言他 现在这个也只能算间接回答

我为什么愤怒？
号称科学却 面对质疑 不直接回答

**Comment by oknochoice** [comment]
> 怼天怼地怼空气的不好，技术讨论嘛要就事论事，不要夹带个人情绪大兄dei，大家都是成年人了，这个圈子说大不大说小不小，万一你周围同事或者领导看到你这样，多尴尬啊不是

情绪肯定要有的 因为是人就有情绪 只要不带脏字 就可以了
程序员 又不是搞人事的 还顾那么多？
就他们这搞程序的 态度 我也不稀罕

**Comment by oknochoice** [comment]
为什么我对 **入库成功标准** 揪着不放
因为入内存入磁盘 速度不一样
直接讲 就是 不能以自己**大批量一次录入** 去对比别人家的 **小批量多次录入**

**Comment by oknochoice** [comment]
为什么我对 **入库成功标准** 揪着不放
因为入内存入磁盘 速度不一样
就会间接遭成 以自己**大批量一次录入** 去对比别人家的 **小批量多次录入**
这样就不公平了 因为别人也能做 大批量一次录入

**Comment by oknochoice** [comment]
> 要让数据快，无论是插入还是查询，就是要最大程度的减少磁盘IO次数，减少网络IO次数。建议大家多实际测试一下，光靠嘴巴说没说服力。欢迎把源码修改，加上msync之后测，与InfluxDB做对比。而且建议只用1G内存，但写入100G的数据来测。

靠嘴当然是有用的
理论上能质疑的 就不需要做实验
理论上质疑不了的 才要做实验
实验的成本很高的 哪有那么多人力物力 去做啊
了解一下 第一性原理

**Comment by cling60** [comment]
> 为什么我对 **入库成功标准** 揪着不放
> 因为入内存入磁盘 速度不一样
> 直接讲 就是 不能以自己**大批量一次录入** 去对比别人家的 **小批量多次录入**






> > 要让数据快，无论是插入还是查询，就是要最大程度的减少磁盘IO次数，减少网络IO次数。建议大家多实际测试一下，光靠嘴巴说没说服力。欢迎把源码修改，加上msync之后测，与InfluxDB做对比。而且建议只用1G内存，但写入100G的数据来测。
> 
> 靠嘴当然是有用的
> 理论上能质疑的 就不需要做实验
> 理论上质疑不了的 才要做实验
> 实验的成本很高的 哪有那么多人力物力 去做啊
> 了解一下 第一性原理

你对开源的诉求太大了，大家都有工作，没有义务或者时间告诉你你想知道的一切。
代码都开源了，自己看就行了，没有刷盘几天前我已经告诉你了，看代码大概用时20分钟，有这扯皮的时间估计你已经把所有的代码撸完了。

**Comment by jtao1735** [comment]
> > 要让数据快，无论是插入还是查询，就是要最大程度的减少磁盘IO次数，减少网络IO次数。建议大家多实际测试一下，光靠嘴巴说没说服力。欢迎把源码修改，加上msync之后测，与InfluxDB做对比。而且建议只用1G内存，但写入100G的数据来测。
> 
> 靠嘴当然是有用的
> 理论上能质疑的 就不需要做实验
> 理论上质疑不了的 才要做实验
> 实验的成本很高的 哪有那么多人力物力 去做啊
> 了解一下 第一性原理

请看文档 https://www.taosdata.com/cn/documentation/data-model-and-architecture/#%E6%95%B0%E6%8D%AE%E5%AD%98%E5%82%A8
以及文档 https://www.taosdata.com/cn/documentation/more-on-system-architecture/#%E5%AD%98%E5%82%A8%E8%AE%BE%E8%AE%A1 
我们对存储有详细介绍，而且源码也完全公开，没有任何必要copy & paste一次。

最重要的是，你可以不相信我们的测试结论，可以自己测试。这个博客还提供了详细的步骤和源程序，https://www.taosdata.com/blog/2019/07/19/tdengine%e4%b8%8einfluxdb%e5%af%b9%e6%af%94%e6%b5%8b%e8%af%95/

**Comment by oknochoice** [comment]
> > 为什么我对 **入库成功标准** 揪着不放
> > 因为入内存入磁盘 速度不一样
> > 直接讲 就是 不能以自己**大批量一次录入** 去对比别人家的 **小批量多次录入**
> 
> > > 要让数据快，无论是插入还是查询，就是要最大程度的减少磁盘IO次数，减少网络IO次数。建议大家多实际测试一下，光靠嘴巴说没说服力。欢迎把源码修改，加上msync之后测，与InfluxDB做对比。而且建议只用1G内存，但写入100G的数据来测。
> > 
> > 
> > 靠嘴当然是有用的
> > 理论上能质疑的 就不需要做实验
> > 理论上质疑不了的 才要做实验
> > 实验的成本很高的 哪有那么多人力物力 去做啊
> > 了解一下 第一性原理
> 
> 你对开源的诉求太大了，大家都有工作，没有义务或者时间告诉你你想知道的一切。
> 代码都开源了，自己看就行了，没有刷盘几天前我已经告诉你了，看代码大概用时20分钟，有这扯皮的时间估计你已经把所有的代码撸完了。

那你就不要说 不要告诉我
我没问你 我只是质疑你

**Comment by riyun1989** [comment]
兄dei，笑死我了法院见！

**Comment by oknochoice** [comment]
> > > 要让数据快，无论是插入还是查询，就是要最大程度的减少磁盘IO次数，减少网络IO次数。建议大家多实际测试一下，光靠嘴巴说没说服力。欢迎把源码修改，加上msync之后测，与InfluxDB做对比。而且建议只用1G内存，但写入100G的数据来测。
> > 
> > 
> > 靠嘴当然是有用的
> > 理论上能质疑的 就不需要做实验
> > 理论上质疑不了的 才要做实验
> > 实验的成本很高的 哪有那么多人力物力 去做啊
> > 了解一下 第一性原理
> 
> 请看文档 https://www.taosdata.com/cn/documentation/data-model-and-architecture/#%E6%95%B0%E6%8D%AE%E5%AD%98%E5%82%A8
> 以及文档 https://www.taosdata.com/cn/documentation/more-on-system-architecture/#%E5%AD%98%E5%82%A8%E8%AE%BE%E8%AE%A1
> 我们对存储有详细介绍，而且源码也完全公开，没有任何必要copy & paste一次。
> 
> 最重要的是，你可以不相信我们的测试结论，可以自己测试。这个博客还提供了详细的步骤和源程序，https://www.taosdata.com/blog/2019/07/19/tdengine%e4%b8%8einfluxdb%e5%af%b9%e6%af%94%e6%b5%8b%e8%af%95/

能不能不要 搞这个啊 
你就说 你的对比 会不会造成
自己大批量一次录入 去对比别人家的 小批量多次录入

**Comment by oknochoice** [comment]
> 兄dei，笑死我了法院见！

哈哈哈 
怼的 开心就好 
本来就是没事 瞎讨论呢

**Comment by jtao1735** [comment]
> > > > 要让数据快，无论是插入还是查询，就是要最大程度的减少磁盘IO次数，减少网络IO次数。建议大家多实际测试一下，光靠嘴巴说没说服力。欢迎把源码修改，加上msync之后测，与InfluxDB做对比。而且建议只用1G内存，但写入100G的数据来测。
> > > 
> > > 
> > > 靠嘴当然是有用的
> > > 理论上能质疑的 就不需要做实验
> > > 理论上质疑不了的 才要做实验
> > > 实验的成本很高的 哪有那么多人力物力 去做啊
> > > 了解一下 第一性原理
> > 
> > 
> > 请看文档 https://www.taosdata.com/cn/documentation/data-model-and-architecture/#%E6%95%B0%E6%8D%AE%E5%AD%98%E5%82%A8
> > 以及文档 https://www.taosdata.com/cn/documentation/more-on-system-architecture/#%E5%AD%98%E5%82%A8%E8%AE%BE%E8%AE%A1
> > 我们对存储有详细介绍，而且源码也完全公开，没有任何必要copy & paste一次。
> > 最重要的是，你可以不相信我们的测试结论，可以自己测试。这个博客还提供了详细的步骤和源程序，https://www.taosdata.com/blog/2019/07/19/tdengine%e4%b8%8einfluxdb%e5%af%b9%e6%af%94%e6%b5%8b%e8%af%95/
> 
> 能不能不要 搞这个啊
> 你就说 你的对比 会不会造成
> 自己大批量一次录入 去对比别人家的 小批量多次录入

建议你先认真看完测试报告再评论，就这个问题，我不会再回复你

**Comment by kechundu** [comment]
> @zhangqhn 看来研究颇多
> 
> 但是回到这个Issue要讨论的问题，TDengine的高性能源于它对于时序数据的一系列假设，及针对这些假设所做的创新设计：
> 1：一台设备一张表，让一台设备的数据插入查询性能无人能比；
> 2：超级表，解决表数量过多，表之间的聚合问题

感觉对某些物联网场景是适用的

**Comment by sailing0505** [comment]
> > 兄dei，笑死我了法院见！
> 
> 哈哈哈
> 怼的 开心就好
> 本来就是没事 瞎讨论呢

** stop talking, show me your code. **

**Comment by leaout** [comment]
tdengine的插入速度 竟然可以和c++ vector emplace_back() 的性能差不多，其实就是在写内存呗
