### ISSUE TITLE
drop child table how can free disk space

### ISSUE THREAD

**Issue by xibaoning** [taosdata/TDengine#13625]
删除子表能释放磁盘空间么, 什么时机释放呢,  删除子表好些天了好像没有释放磁盘空间

**Comment by fenghuazzm** [comment]
drop 表之后需要手动执行 COMPACT 指定表所在库的 vnodeid 进行碎片整理，能收缩磁盘空间，语法：
COMPACT VNODES IN (vg_id1, vg_id2, ...)
注：COMPACT 碎片重整是高 IO 操作，可能会影响此刻性能。
