### ISSUE TITLE
Unable to establish connection by Windows Client to Linux Server 

### ISSUE THREAD

**Issue by tangbing2014** [taosdata/TDengine#13631]
==================================================
                new log file                      
==================================================
06/09 10:25:04.714000 00028488 UTL all debug flag are set to 143
06/09 10:25:04.714000 00028488 UTL all debug flag are set to 143
06/09 10:25:04.714000 00028488 UTL localEp is: nvwa:6030
06/09 10:25:04.714000 00028488 UTL dataDir:C:/TDengine/data, level:0 primary:1 is configured
06/09 10:25:04.714000 00028488 UTL dataDir:C:/TDengine/data, level:0 primary:1 is configured by default
06/09 10:25:04.715000 00028488 UTL ERROR Invalid locale:en_US.UTF-8, please set the valid locale in config file
06/09 10:25:04.715000 00028488 UTL    check global cfg completed
06/09 10:25:04.715000 00028488 UTL ==================================
06/09 10:25:04.715000 00028488 UTL    taos config & system info:
06/09 10:25:04.715000 00028488 UTL ==================================
06/09 10:25:04.715000 00028488 UTL  firstEp:                nvwa:6030 
06/09 10:25:04.715000 00028488 UTL  secondEp:               nvwa:6030 
06/09 10:25:04.715000 00028488 UTL  fqdn:                   nvwa 
06/09 10:25:04.715000 00028488 UTL  serverPort:             6030 
06/09 10:25:04.715000 00028488 UTL  configDir:              C:\TDengine\cfg 
06/09 10:25:04.715000 00028488 UTL  logDir:                 C:\TDengine\log 
06/09 10:25:04.715000 00028488 UTL  scriptDir:              C:/TDengine/script 
06/09 10:25:04.715000 00028488 UTL  arbitrator:             nvwa:6042 
06/09 10:25:04.715000 00028488 UTL  numOfThreadsPerCore:    1.000000 
06/09 10:25:04.715000 00028488 UTL  maxNumOfDistinctRes:    10000000 
06/09 10:25:04.715000 00028488 UTL  rpcTimer:               300(ms)
06/09 10:25:04.715000 00028488 UTL  rpcMaxTime:             600(s)
06/09 10:25:04.715000 00028488 UTL  rpcForceTcp:            0 
06/09 10:25:04.715000 00028488 UTL  shellActivityTimer:     3(s)
06/09 10:25:04.715000 00028488 UTL  compressMsgSize:        524288 
06/09 10:25:04.715000 00028488 UTL  compressColData:        -1 
06/09 10:25:04.715000 00028488 UTL  maxSQLLength:           1048576(byte)
06/09 10:25:04.715000 00028488 UTL  maxWildCardsLength:     100(byte)
06/09 10:25:04.715000 00028488 UTL  maxRegexStringLen:      128(byte)
06/09 10:25:04.715000 00028488 UTL  maxNumOfOrderedRes:     1000000 
06/09 10:25:04.715000 00028488 UTL  keepColumnName:         1 
06/09 10:25:04.715000 00028488 UTL  timezone:               UTC-8 
06/09 10:25:04.715000 00028488 UTL  locale:                 en_US.UTF-8 
06/09 10:25:04.715000 00028488 UTL  charset:                UTF-8 
06/09 10:25:04.715000 00028488 UTL  numOfLogLines:          10000000 
06/09 10:25:04.715000 00028488 UTL  logKeepDays:            0 
06/09 10:25:04.715000 00028488 UTL  asyncLog:               1 
06/09 10:25:04.715000 00028488 UTL  debugFlag:              143 
06/09 10:25:04.715000 00028488 UTL  rpcDebugFlag:           143 
06/09 10:25:04.715000 00028488 UTL  tmrDebugFlag:           143 
06/09 10:25:04.715000 00028488 UTL  cDebugFlag:             143 
06/09 10:25:04.715000 00028488 UTL  jniDebugFlag:           143 
06/09 10:25:04.715000 00028488 UTL  odbcDebugFlag:          143 
06/09 10:25:04.715000 00028488 UTL  uDebugFlag:             143 
06/09 10:25:04.715000 00028488 UTL  qDebugFlag:             143 
06/09 10:25:04.715000 00028488 UTL  tsdbDebugFlag:          143 
06/09 10:25:04.715000 00028488 UTL  gitinfo:                0b8cf96115265eb6cd2df4d106d402ce3bf838e8 
06/09 10:25:04.715000 00028488 UTL  gitinfoOfInternal:      5c4f688e8ae8096dbd21bbe0e962969c000c98f0 
06/09 10:25:04.715000 00028488 UTL  buildinfo:              Built at 2022-05-28 11:15:50 
06/09 10:25:04.715000 00028488 UTL  version:                2.6.0.0 
06/09 10:25:04.715000 00028488 UTL  maxBinaryDisplayWidth:  30 
06/09 10:25:04.715000 00028488 UTL  tempDir:                C:\Users\20011695\AppData\Local\Temp 
06/09 10:25:04.715000 00028488 UTL  defaultJSONStrType:     nchar 
06/09 10:25:04.715000 00028488 UTL  smlChildTableName:       
06/09 10:25:04.715000 00028488 UTL  smlTagNullName:         _tag_null 
06/09 10:25:04.715000 00028488 UTL  walFlushSize:           1024(Mb)
06/09 10:25:04.715000 00028488 UTL  shortcutFlag:           0 
06/09 10:25:04.715000 00028488 UTL  os numOfCores:          8
06/09 10:25:04.715000 00028488 UTL  os totalMemory:         16202(MB)
06/09 10:25:04.715000 00028488 UTL ==================================
06/09 10:25:04.715000 00028488 UTL  dataDir: C:/TDengine/data level:0 primary:1
06/09 10:25:04.715000 00028488 UTL ==================================
06/09 10:25:04.715000 00028488 UTL rsetId:1 is opened, max:200, fp:00007FFC00291F20 refSetNum:1
06/09 10:25:04.718000 00028488 TSC starting to initialize client ...
06/09 10:25:04.718000 00028488 TSC Local End Point is:nvwa:6030
06/09 10:25:04.718000 00028488 UTL tsc scheduler is initialized, numOfThreads:4
06/09 10:25:04.718000 00028488 TSC client task queue is initialized, numOfWorkers: 4
06/09 10:25:04.718000 00028488 TMR ttimer monotonic clock source:POSIX clock_gettime
06/09 10:25:04.719000 00028488 UTL tmr scheduler is initialized, numOfThreads:1
06/09 10:25:04.719000 00028488 TMR timer module is initialized, number of threads: 1
06/09 10:25:04.719000 00028488 TMR TSC timer controller is initialized, number of timer controllers: 1.
06/09 10:25:04.719000 00028488 TMR TSC timer[id=0] does not exist
06/09 10:25:04.719000 00028488 TMR TSC timer[id=1, fp=00007FFC0027A800, param=0000000000000000] started
06/09 10:25:04.719000 00028488 UTL rsetId:2 is opened, max:40960, fp:00007FFC002831A0 refSetNum:2
06/09 10:25:04.719000 00028488 UTL rsetId:3 is opened, max:200, fp:00007FFC00285770 refSetNum:3
06/09 10:25:04.719000 00028488 TSC client is initialized successfully
06/09 10:25:04.719000 00028488 UTL pool:000001F87F53BC60 is setup, maxId:5000
06/09 10:25:04.719000 00028488 TMR ttimer monotonic clock source:POSIX clock_gettime
06/09 10:25:04.719000 00028488 TMR TSC timer controller is initialized, number of timer controllers: 2.
06/09 10:25:04.719000 00013392 UTL cache refresh thread starts
06/09 10:25:04.720000 00028488 TMR TSC timer[id=0] does not exist
06/09 10:25:04.720000 00028488 TMR TSC timer[id=2, fp=00007FFC0029C210, param=000001F80F3C4420] started
06/09 10:25:04.720000 00028488 UTL open udp socket:0x0:0
06/09 10:25:04.721000 00028488 UTL open udp socket:0x0:0
06/09 10:25:04.721000 00023124 RPC TSC UDP thread is created, index:0
06/09 10:25:04.721000 00028488 UTL open udp socket:0x0:0
06/09 10:25:04.721000 00002772 RPC TSC UDP thread is created, index:1
06/09 10:25:04.721000 00028488 UTL open udp socket:0x0:0
06/09 10:25:04.722000 00010132 RPC TSC UDP thread is created, index:2
06/09 10:25:04.722000 00028488 RPC TSC UDP connection is initialized, ip:0:0 threads:4
06/09 10:25:04.722000 00028488 RPC TSC rpc is opened, threads:4 sessions:5000
06/09 10:25:04.722000 00028488 UTL cache:rpcObj, key:00000010FD5FE590, 000001F87FCC0770 added into cache, added:1654741504722, expire:1654741509722, totalNum:1 totalSize:607bytes size:520bytes
06/09 10:25:04.722000 00028488 UTL rsetId:3 p:000001F87E2CF7B0 rid:2 is added, count:2
06/09 10:25:04.722000 00028488 UTL rsetId:3 p:000001F87E2CF7B0 rid:2 is acquired
06/09 10:25:04.722000 00028488 UTL rsetId:2 p:000001F87FB90320 rid:2 is added, count:2
06/09 10:25:04.722000 00028488 TSC 0x2 new SqlObj from 000001F87E2CF7B0, total in tscObj:1, total:1
06/09 10:25:04.722000 00028488 TSC 0x2 SQL cmd:connect will be processed, name:, type:0
06/09 10:25:04.722000 00020252 RPC TSC UDP thread is created, index:3
06/09 10:25:04.722000 00028488 RPC malloc mem:000001F87FB90AD0 size:1122
06/09 10:25:04.722000 00028488 UTL rsetId:1 p:000001F87FB90AD0 rid:2 is added, count:2
06/09 10:25:04.729000 00028488 RPC TSC 000001F8113ED1B8 client connection is allocated, uid:0x113f53c2
06/09 10:25:04.729000 00028488 RPC TSC UDP connection is setup, ip:53f5a8c0:6030 localPort:55187
06/09 10:25:04.729000 00028488 RPC TSC 000001F8113ED1B8 0000000000000002, connect is sent to nvwa:6030, len:378 sig:0x01000000:0x00000000:16939
06/09 10:25:04.730000 00028488 TMR TSC timer[id=0] does not exist
06/09 10:25:04.730000 00028488 TMR TSC timer[id=3, fp=00007FFC00296F30, param=000001F8113ED1B8] started
06/09 10:25:05.035000 00024300 TMR TSC adding expired timer[id=3, fp=00007FFC00296F30, param=000001F8113ED1B8] to queue.
06/09 10:25:05.035000 00024300 TMR timer[id=3] has been added to queue.
06/09 10:25:05.035000 00011428 TMR TSC timer[id=3, fp=00007FFC00296F30, param=000001F8113ED1B8] execution start.
06/09 10:25:05.035000 00011428 RPC TSC 000001F8113ED1B8 0000000000000002, expected connect-rsp is not received
06/09 10:25:05.035000 00011428 RPC TSC 000001F8113ED1B8 0000000000000002, re-send msg:connect to nvwa:6030
06/09 10:25:05.035000 00011428 RPC TSC 000001F8113ED1B8 0000000000000002, connect is sent to nvwa:6030, len:378 sig:0x01000000:0x00000000:16939
06/09 10:25:05.035000 00011428 TMR TSC timer[id=4, fp=00007FFC00296F30, param=000001F8113ED1B8] started
06/09 10:25:05.035000 00011428 TMR TSC timer[id=3, fp=00007FFC00296F30, param=000001F8113ED1B8] execution end.
06/09 10:25:05.335000 00024300 TMR TSC adding expired timer[id=4, fp=00007FFC00296F30, param=000001F8113ED1B8] to queue.
06/09 10:25:05.335000 00024300 TMR timer[id=4] has been added to queue.
06/09 10:25:05.335000 00011428 TMR TSC timer[id=4, fp=00007FFC00296F30, param=000001F8113ED1B8] execution start.
06/09 10:25:05.335000 00011428 RPC TSC 000001F8113ED1B8 0000000000000002, expected connect-rsp is not received
06/09 10:25:05.335000 00011428 RPC TSC 000001F8113ED1B8 0000000000000002, re-send msg:connect to nvwa:6030
06/09 10:25:05.335000 00011428 RPC TSC 000001F8113ED1B8 0000000000000002, connect is sent to nvwa:6030, len:378 sig:0x01000000:0x00000000:16939
06/09 10:25:05.335000 00011428 TMR TSC timer[id=5, fp=00007FFC00296F30, param=000001F8113ED1B8] started
06/09 10:25:05.335000 00011428 TMR TSC timer[id=4, fp=00007FFC00296F30, param=000001F8113ED1B8] execution end.
06/09 10:25:05.640000 00024300 TMR TSC adding expired timer[id=5, fp=00007FFC00296F30, param=000001F8113ED1B8] to queue.
06/09 10:25:05.640000 00024300 TMR timer[id=5] has been added to queue.
06/09 10:25:05.640000 00011428 TMR TSC timer[id=5, fp=00007FFC00296F30, param=000001F8113ED1B8] execution start.
06/09 10:25:05.640000 00011428 RPC TSC 000001F8113ED1B8 0000000000000002, expected connect-rsp is not received
06/09 10:25:05.640000 00011428 RPC TSC 000001F8113ED1B8 0000000000000002, re-send msg:connect to nvwa:6030
06/09 10:25:05.640000 00011428 RPC TSC 000001F8113ED1B8 0000000000000002, connect is sent to nvwa:6030, len:378 sig:0x01000000:0x00000000:16939
06/09 10:25:05.640000 00011428 TMR TSC timer[id=6, fp=00007FFC00296F30, param=000001F8113ED1B8] started
06/09 10:25:05.640000 00011428 TMR TSC timer[id=5, fp=00007FFC00296F30, param=000001F8113ED1B8] execution end.

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
