### ISSUE TITLE
Timestamp type, when data is combined through getObject. If the version 2.0.16.0 TDengine is combined with the version 2.0.38 JDBC driver, the string type is obtained. If the version 2.4.0.4 TDengine is combined with the version 2.0.38 JDBC driver, the normal type is obtained

### ISSUE THREAD

**Issue by youchengyang** [taosdata/TDengine#13633]
**Bug Description**
时间戳类型，通过getObject获取数据。2.0.16.0版本的库，2.0.38版本的jdbc驱动，拿到是string，2.4.0.4版本的库，2.0.38版本的jdbc驱动，正常拿到类型
**To Reproduce**

		List<LinkedHashMap<String, Object>> list = new ArrayList<>();
        DataSource dataSource = getDataSource();
        
        try (Connection connection = dataSource.getConnection()) {
            Statement statement = connection.createStatement();
            boolean isResultSet = statement.execute(sql);
            if (isResultSet) {
                ResultSet resultSet = statement.getResultSet();
                ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                int columns = resultSetMetaData.getColumnCount();
                while (resultSet.next()) {
                    LinkedHashMap<String, Object> map = new LinkedHashMap<>();
                    for (int i = 1; i <= columns; i++) {
                        map.put(resultSetMetaData.getColumnLabel(i), resultSet.getObject(resultSetMetaData.getColumnLabel(i)));
                    }
                    list.add(map);
                }
            }
            return list;

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by fenghuazzm** [comment]
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/70138133/172760925-741d726c-a660-47ee-9063-c0f7c136d8b9.png">
是有版本对应要求的

**Comment by huolibo** [comment]
由于 TDengine 第一列都是 Timestamp 类型。所以我写了一个测试用例仅验证第一列类型，如下：
```java
package com.taosdata.jdbc;

import org.junit.Assert;
import org.junit.Test;

import java.sql.*;

public class TimestampTest {

    @Test
    public void getTimestamp() throws SQLException {
//        String url = "jdbc:TAOS://127.0.0.1:6030/?user=root&password=taosdata";
        String url = "jdbc:TAOS-RS://127.0.0.1:6041/?user=root&password=taosdata";
        String sql = "select * from log.dn";
        try (Connection connection = DriverManager.getConnection(url)) {
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery(sql);
            ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
            while (resultSet.next()) {
                Object object = resultSet.getObject(resultSetMetaData.getColumnLabel(1));
                System.out.printf("%s - %s - %s\n", resultSetMetaData.getColumnLabel(1), object, object.getClass());
                Assert.assertTrue(object instanceof Timestamp);
            }
        }
    }
}
```
可以在获取 Object 环境下测试 case 是否可以通过, 并切换下连接方式看下情况。如果存在 error， 请给出打印结果。

**Comment by huolibo** [comment]
并且建议升级服务端版本，2.0.38 JDBC connector 不支持 2.0.16 服务端。

**Comment by youchengyang** [comment]
明白，不过之前我们按照你们的官方文档指定的驱动做，也是存在一些问题的，所以后续才换了这个驱动。那就这样把，我明白什么原因了

**Comment by youchengyang** [comment]
> <img alt="image" width="1359" src="https://user-images.githubusercontent.com/70138133/172760925-741d726c-a660-47ee-9063-c0f7c136d8b9.png">
> 
> 是有版本对应要求的

建议咱们高版本尽量向下兼容，我之前选择这个驱动版本就是因为按照指定的驱动版本做，都会有一些问题，所以后续我才统一使用这个驱动版本来兼容各个版本的数据库的

**Comment by huolibo** [comment]
嗯，原则上确实要做好兼容性。但高版本在一些情况下不可避免的要做调整。
之后如果有不兼容的 API 修改尽量到在 版本变更 中做好说明。

**Comment by youchengyang** [comment]
> 
现在我使用的是2.0.38的驱动，来兼容所有版本的数据库客户端
