### ISSUE TITLE
Database Subtable size

### ISSUE THREAD

**Issue by xiaohuizhang** [taosdata/TDengine#13641]
您好，
有什么方法能统计出一个子表的占用磁盘大小?

**Comment by fenghuazzm** [comment]
SELECT _block_dist() FROM { tb_name | stb_name }
此函数可以对子表使用。
详细信息可见：
https://docs.taosdata.com/taos-sql/select/#_block_dist-%E5%87%BD%E6%95%B0

**Comment by xiaohuizhang** [comment]
在配置文件中，comp=0，查询结果出来Comp=[1.1687]
文档的解释是：Comp=[0.23] 压缩后的数据块的大小除以原始数据的所获得的压缩比例： 23%（Comp），及压缩后的数据规模是原始数据规模的 23%。
那意思是说，不压缩的情况下，占用的比原始数据大？

**Comment by gccgdb1234** [comment]
数据在存储中需要组织，需要一定的额外开销。

**Comment by xiaohuizhang** [comment]
数据已不再进行插入，查询的表大小的时候，RowsInMem=[2312789]这个属性值一直不变化，内存一直有这么多条数据？这个在内存中的数据多久会刷进磁盘中？

**Comment by xiaohuizhang** [comment]
RowsInMem=[2312789]数据在内存中，会影响Size=[3815138.434(Kb)] 这个属性值吗？

**Comment by xiaohuizhang** [comment]
重启taosd后，内存里的数据刷进了磁盘，size的大小也增加了。
在taos.cfg里没有配置cacheLast这个属性值，缺省值是0，那应该是不缓存。
请问，在缓存中的数据跟这个cacheLast有关系么？

**Comment by fenghuazzm** [comment]
cacheLast 参数是缓存的最近一行或者一列的数据，方便快速查询。
而写入后你看到的缓存 RowsInMem 是在 buffer pool 中，是由每个 vnode 的 cache * blocks 决定，写入量超过 buffer pool 一定比例会触发部分数据的落盘，当然重启服务会将缓存全部落盘。
所有这不是一个概念，这些在文档上都能搜索到。
