### ISSUE TITLE
Using the data subscribe, the consume() method causes the process to crash

### ISSUE THREAD

**Issue by GuoLijuan** [taosdata/TDengine#13685]
问题描述：
1.建立监听connection，此时订阅的ip可达
2.同步处理订阅的数据，调用 sub.consume()，因没有订阅数据到达，阻塞
3.约1min后订阅的ip不可达
4.没有重新建立订阅ip的connection，步骤2一直处理阻塞状态
5.约15分钟后，步骤2的代码导致主进程crash，报错内容：segfault at 0 ip 00007f2fa73e4997 sp 00007f2f46ffb780 error 4 in libtaos.so.2.4.0.12[7f2fa724f000+390000]

**Comment by zhangbiyun** [comment]
Hi,  Who can give me a sample program for reproducing, I want to try to fix it.

**Comment by GuoLijuan** [comment]
> Hi, Who can give me a sample program to reproduce, I want to try to fix it.


conn = taos.connect(host="", user="", password="")
sub = conn.subscribe(False, "topic", "sql", 2000)


data = sub.consume()

当 conn的 host网络不通时，约15分钟后，data=sub.consume() 导致进程crash
怀疑是 conn连接在网络不通时，导致内存泄露了

**Comment by zhangbiyun** [comment]
Thanks. Using demo program can reproduce this issue.
[Uploading subscribe_demo.py…]()

**client log**
root@ubuntu:/home/user/Desktop/workspace/TDengine/docs-examples/python# python3 subscribe_demo.py 
taos connect failed, reason: Unable to establish connection.

Traceback (most recent call last):
  File "subscribe_demo.py", line 30, in <module>
    conn = taos.connect(host="192.168.0.101",user="root",password="taosdata")
  File "/usr/local/lib/python3.8/dist-packages/taos/__init__.py", line 64, in connect
    return TaosConnection(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/taos/connection.py", line 24, in __init__
    self._conn = self._chandle.connect(self._host, self._user, self._password, self._database, self._port)
  File "/usr/local/lib/python3.8/dist-packages/taos/cinterface.py", line 1243, in connect
    return taos_connect(host, user, password, db, port)
  File "/usr/local/lib/python3.8/dist-packages/taos/cinterface.py", line 214, in taos_connect
    raise ConnectionError(errstr, errno)
taos.error.ConnectionError: [0x000b]: Unable to establish connection

**taosd debug log**
06/13 12:44:18.160732 00001482 UTL ERROR failed to connect socket, ip:0x101007f, port:6030(poll error/conn timeout)
06/13 12:44:18.160791 00001482 RPC ERROR failed to connect to:0x101007f:6030
06/13 12:44:18.160801 00001482 RPC ERROR TSC 0x8f6, failed to set up connection(Unable to establish connection)
06/13 12:44:19.163999 00001144 UTL ERROR failed to connect socket, ip:0x101007f, port:6030(poll error/conn timeout)
06/13 12:44:19.164058 00001144 RPC ERROR failed to connect to:0x101007f:6030
06/13 12:44:19.164070 00001144 RPC ERROR TSC 0x8f6, failed to set up connection(Unable to establish connection)
06/13 12:44:19.168963 00001482 MON ERROR failed to execute cmd: show dnodes, reason:Unable to establish connection
06/13 12:44:20.171137 00001482 UTL ERROR failed to connect socket, ip:0x101007f, port:6030(poll error/conn timeout)
06/13 12:44:20.171293 00001482 RPC ERROR failed to connect to:0x101007f:6030
06/13 12:44:20.171313 00001482 RPC ERROR TSC 0x8f7, failed to set up connection(Unable to establish connection)
06/13 12:44:21.180481 00001144 UTL ERROR failed to connect socket, ip:0x101007f, port:6030(poll error/conn timeout)
06/13 12:44:21.180541 00001144 RPC ERROR failed to connect to:0x101007f:6030
06/13 12:44:21.180549 00001144 RPC ERROR TSC 0x8f7, failed to set up connection(Unable to establish connection)
06/13 12:44:21.183614 00001482 MON ERROR failed to execute cmd: show vnodes "ubuntu:6030", reason:Unable to establish connection
06/13 12:44:22.185403 00001482 UTL ERROR failed to connect socket, ip:0x101007f, port:6030(poll error/conn timeout)
06/13 12:44:22.185464 00001482 RPC ERROR failed to connect to:0x101007f:6030
06/13 12:44:22.185472 00001482 RPC ERROR TSC 0x8f8, failed to set up connection(Unable to establish connection)
06/13 12:44:23.190521 00001144 UTL ERROR failed to connect socket, ip:0x101007f, port:6030(poll error/conn timeout)
06/13 12:44:23.190627 00001144 RPC ERROR failed to connect to:0x101007f:6030
06/13 12:44:23.190643 00001144 RPC ERROR TSC 0x8f8, failed to set up connection(Unable to establish connection)
06/13 12:44:23.200395 00001482 MON ERROR failed to execute cmd: show mnodes, reason:Unable to establish connection
06/13 12:44:24.202441 00001482 UTL ERROR failed to connect socket, ip:0x101007f, port:6030(poll error/conn timeout)
06/13 12:44:24.202509 00001482 RPC ERROR failed to connect to:0x101007f:6030
06/13 12:44:24.202519 00001482 RPC ERROR TSC 0x8fa, failed to set up connection(Unable to establish connection)
06/13 12:44:24.209236 00001144 TSC WARN 0x8f9 Async insertion completed, total inserted:0 rows, numOfFailed:1, numOfTotal:1
06/13 12:44:25.210848 00001144 UTL ERROR failed to connect socket, ip:0x101007f, port:6030(poll error/conn timeout)
06/13 12:44:25.210922 00001144 RPC ERROR failed to connect to:0x101007f:6030
06/13 12:44:25.210934 00001144 RPC ERROR TSC 0x8fb, failed to set up connection(Unable to establish connection)
06/13 12:44:26.216183 00001144 UTL ERROR failed to connect socket, ip:0x101007f, port:6030(poll error/conn timeout)
06/13 12:44:26.216268 00001144 RPC ERROR failed to connect to:0x101007f:6030
06/13 12:44:26.216282 00001144 RPC ERROR TSC 0x8fb, failed to set up connection(Unable to establish connection)
06/13 12:44:26.224103 00001144 TSC ERROR 0x8f9 get multi-tableMeta failed, code:Unable to establish connection
06/13 12:44:26.224283 00001489 TSC ERROR 0x8f9 async result callback, code:Unable to establish connection
06/13 12:44:26.224408 00001482 MON ERROR failed to save dnode_1 info, reason:Unable to establish connection, sql:insert into log.dnode_1 values(1655095440000000, 0, 0.204018, 0.258945, 4, 156.925781, 1755.917969, 7915, 0.000000, 17.018047, 58.313305, 0.000000, 0.000000, 0.003070, 0.003050, 0.000000, 0.000521, 0, 0.000000, 0, 0.000000, 11, 11, 0.366667, 11, 11, 0.366667, 0, 0, 0, false)
06/13 12:44:27.225699 00001482 UTL ERROR failed to connect socket, ip:0x101007f, port:6030(poll error/conn timeout)
06/13 12:44:27.225757 00001482 RPC ERROR failed to connect to:0x101007f:6030
06/13 12:44:27.225765 00001482 RPC ERROR TSC 0x8fc, failed to set up connection(Unable to establish connection)

**Comment by GuoLijuan** [comment]
> above

我这边环境是，先建立连接，然后断开连接，sub.consume() 会出现问题

这个有什么建议的解决方法吗？

**Comment by zhangbiyun** [comment]
> 我这边环境是，先建立连接成功，sub.consume() 同步处理没有问题；然后断开网络，sub.consume() 会阻塞，约15分钟后，引起主进程crash

请问主进程是客户端的sub.consume()进程，还是taosd的服务进程。和我列的错误现象，不一样是么？

**Comment by zhangbiyun** [comment]
> 实例代码 1、在A服务器上跑demo，在启动demo时，A服务器到B(host_ip)服务器网络是通的 2、demo启动成功后，A到B(host_ip)网络中断 3、等待约15分钟左右，会报错
 
我还在复现。有没有一些关键性的日志。发一下客户端的详细错误堆栈和服务端taosd的日志信息（在/etc/taos/taos.cfg文件调高下日志级别）

**Comment by GuoLijuan** [comment]
> > 实例代码 1、在A服务器上跑demo，在启动demo时，A服务器到B(host_ip)服务器网络是通的 2、demo启动成功后，A到B(host_ip)网络中断 3、等待约15分钟左右，会报错
> 
> 我还在复现。有没有一些关键性的日志。发一下客户端的详细错误堆栈和服务端taosd的日志信息（在/etc/taos/taos.cfg文件调高下日志级别）

taoslog2.o文件从connection断开后，频繁写这些日志

06/14 09:37:31.367732 00019027 TSC 0x3 send heartbeat in 1500ms
06/14 09:37:31.671570 00019021 RPC TSC 0x7f81b81ebcc0 0x5, expected heartbeat-rsp is not received
06/14 09:37:31.671601 00019021 RPC TSC 0x7f81b81ebcc0 0x5, re-send msg:heartbeat to 192.168.2.77:6030
06/14 09:37:31.671665 00019021 RPC TSC 0x7f81b81ebcc0 0x5, heartbeat is sent to 192.168.2.77:6030, len:1826 sig:0x4a000000:0x00000000:28695
06/14 09:37:31.976518 00019021 RPC TSC 0x7f81b81ebcc0 0x5, expected heartbeat-rsp is not received
06/14 09:37:31.976547 00019021 RPC TSC 0x7f81b81ebcc0 0x5, re-send msg:heartbeat to 192.168.2.77:6030
06/14 09:37:31.976612 00019021 RPC TSC 0x7f81b81ebcc0 0x5, heartbeat is sent to 192.168.2.77:6030, len:1826 sig:0x4a000000:0x00000000:28695
06/14 09:37:32.281561 00019021 RPC TSC 0x7f81b81ebcc0 0x5, expected heartbeat-rsp is not received
06/14 09:37:32.281589 00019021 RPC TSC 0x7f81b81ebcc0 0x5, re-send msg:heartbeat to 192.168.2.77:6030
06/14 09:37:32.281654 00019021 RPC TSC 0x7f81b81ebcc0 0x5, heartbeat is sent to 192.168.2.77:6030, len:1826 sig:0x4a000000:0x00000000:28695
06/14 09:37:32.586545 00019021 RPC TSC 0x7f81b81ebcc0 0x5, expected heartbeat-rsp is not received
06/14 09:37:32.586574 00019021 RPC TSC 0x7f81b81ebcc0 0x5, failed to send msg:heartbeat to 192.168.2.77:6030
06/14 09:37:32.586587 00019021 RPC TSC 0x7f81b81ebcc0 0x5, rpc connection is released
06/14 09:37:32.591509 00019021 RPC TSC 0x5, connection error happens
06/14 09:37:32.591526 00019021 TSC 0x5 SQL cmd:heart-beat, code:Unable to establish connection rspLen:0
06/14 09:37:32.591533 00019021 TSC 5 heartbeat failed, code:Unable to establish connection
06/14 09:37:32.591537 00019021 TSC 0x5 send heartbeat in 1500ms
06/14 09:37:32.871558 00019021 TSC 0x3 SQL cmd:heart-beat will be processed, name:, type:0
06/14 09:37:32.871632 00019021 RPC TSC 0x7f81b847f188 0x3, heartbeat is sent to 127.0.0.1:6030, len:121 sig:0x01000000:0x05000000:51427
06/14 09:37:32.871934 00019027 RPC TSC 0x7f81b847f188 0x3, heartbeat-rsp received from 0x100007f:6030, parse code:0x0 len:742 sig:0x05000000:0x01000000:51427 code:0x0
06/14 09:37:32.871969 00019027 TSC 0x3 reset retry counter to be 0 due to success rsp, old:0
06/14 09:37:32.871978 00019027 TSC 0x3 SQL cmd:heart-beat, code:success rspLen:674
06/14 09:37:32.871984 00019027 TSC 0x3 send heartbeat in 1500ms
06/14 09:37:33.100652 00019023 UTL rpcObj refresh thread scan
06/14 09:37:34.096630 00019021 TSC 0x5 SQL cmd:heart-beat will be processed, name:, type:0
06/14 09:37:38.101973 00019023 UTL rpcObj refresh thread scan
06/14 09:37:43.103232 00019023 UTL rpcObj refresh thread scan
06/14 09:37:44.106972 00019021 RPC TSC 0x7f81b81ebe38 client connection is allocated, uid:0xb81f0a3b
06/14 09:37:44.107004 00019021 RPC TSC UDP connection is setup, ip:4d02a8c0:6030 localPort:33043
06/14 09:37:44.107049 00019021 RPC TSC 0x7f81b81ebe38 0x5, heartbeat is sent to 192.168.2.77:6030, len:1826 sig:0x4b000000:0x00000000:458
06/14 09:37:44.107168 00019021 TSC 0x3 SQL cmd:heart-beat will be processed, name:, type:0
06/14 09:37:44.107294 00019021 RPC TSC 0x7f81b847f188 0x3, heartbeat is sent to 127.0.0.1:6030, len:121 sig:0x01000000:0x05000000:51428
06/14 09:37:44.107626 00019027 RPC TSC 0x7f81b847f188 0x3, heartbeat-rsp received from 0x100007f:6030, parse code:0x0 len:742 sig:0x05000000:0x01000000:51428 code:0x0
06/14 09:37:44.107648 00019027 TSC 0x3 reset retry counter to be 0 due to success rsp, old:0
06/14 09:37:44.107653 00019027 TSC 0x3 SQL cmd:heart-beat, code:success rspLen:674
06/14 09:37:44.107658 00019027 TSC 0x3 send heartbeat in 1500ms
06/14 09:37:44.411571 00019021 RPC TSC 0x7f81b81ebe38 0x5, expected heartbeat-rsp is not received
06/14 09:37:44.411633 00019021 RPC TSC 0x7f81b81ebe38 0x5, re-send msg:heartbeat to 192.168.2.77:6030
06/14 09:37:44.411706 00019021 RPC TSC 0x7f81b81ebe38 0x5, heartbeat is sent to 192.168.2.77:6030, len:1826 sig:0x4b000000:0x00000000:458



06/14 09:37:44.716549 00019021 RPC TSC 0x7f81b81ebe38 0x5, expected heartbeat-rsp is not received
06/14 09:37:44.716587 00019021 RPC TSC 0x7f81b81ebe38 0x5, re-send msg:heartbeat to 192.168.2.77:6030
06/14 09:37:44.716654 00019021 RPC TSC 0x7f81b81ebe38 0x5, heartbeat is sent to 192.168.2.77:6030, len:1826 sig:0x4b000000:0x00000000:458
06/14 09:37:45.021594 00019021 RPC TSC 0x7f81b81ebe38 0x5, expected heartbeat-rsp is not received
06/14 09:37:45.021623 00019021 RPC TSC 0x7f81b81ebe38 0x5, re-send msg:heartbeat to 192.168.2.77:6030
06/14 09:37:45.021683 00019021 RPC TSC 0x7f81b81ebe38 0x5, heartbeat is sent to 192.168.2.77:6030, len:1826 sig:0x4b000000:0x00000000:458
06/14 09:37:45.326508 00019021 RPC TSC 0x7f81b81ebe38 0x5, expected heartbeat-rsp is not received
06/14 09:37:45.326540 00019021 RPC TSC 0x7f81b81ebe38 0x5, failed to send msg:heartbeat to 192.168.2.77:6030
06/14 09:37:45.326566 00019021 RPC TSC 0x7f81b81ebe38 0x5, rpc connection is released
06/14 09:37:45.331463 00019021 RPC TSC 0x5, connection error happens
06/14 09:37:45.331511 00019021 TSC 0x5 SQL cmd:heart-beat, code:Unable to establish connection rspLen:0
06/14 09:37:45.331518 00019021 TSC 5 heartbeat failed, code:Unable to establish connection
06/14 09:37:45.331522 00019021 TSC 0x5 send heartbeat in 1500ms
06/14 09:37:45.611557 00019021 TSC 0x3 SQL cmd:heart-beat will be processed, name:, type:0
06/14 09:37:45.611688 00019021 RPC TSC 0x7f81b847f188 0x3, heartbeat is sent to 127.0.0.1:6030, len:121 sig:0x01000000:0x05000000:51429
06/14 09:37:45.612043 00019027 RPC TSC 0x7f81b847f188 0x3, heartbeat-rsp received from 0x100007f:6030, parse code:0x0 len:742 sig:0x05000000:0x01000000:51429 code:0x0
06/14 09:37:45.612081 00019027 TSC 0x3 reset retry counter to be 0 due to success rsp, old:0
06/14 09:37:45.612090 00019027 TSC 0x3 SQL cmd:heart-beat, code:success rspLen:674
06/14 09:37:45.612097 00019027 TSC 0x3 send heartbeat in 1500ms
06/14 09:37:46.836502 00019021 TSC 0x5 SQL cmd:heart-beat will be processed, name:, type:0
06/14 09:37:48.104719 00019023 UTL rpcObj refresh thread scan
06/14 09:37:53.106073 00019023 UTL rpcObj refresh thread scan
06/14 09:37:55.387409 00019029 RPC TSC 0x7f81b81e5478 FD:0x7f818c000fe0 epoll errors
06/14 09:37:55.387524 00019029 RPC TSC 0x7f81b81e5478 0x6, link is broken
06/14 09:37:55.387577 00019029 RPC TSC 0x7f81b81e5478 TCP connection will be closed, FD:0x7f818c000fe0
06/14 09:37:55.387600 00019029 RPC TSC 0x7f81b81e5478 0x6, rpc connection is released
06/14 09:37:55.387640 00019029 RPC TSC 0x7f81b81e5478 TCP connection is closed, FD:0x7f818c000fe0 fd:-1 numOfFds:0
06/14 09:37:56.848010 00019021 RPC TSC 0x7f81b81ebfb0 client connection is allocated, uid:0xb81f7105
06/14 09:37:56.848043 00019021 RPC TSC UDP connection is setup, ip:4d02a8c0:6030 localPort:42933
06/14 09:37:56.848111 00019021 RPC TSC 0x7f81b81ebfb0 0x5, heartbeat is sent to 192.168.2.77:6030, len:1826 sig:0x4c000000:0x00000000:26396
06/14 09:37:56.848227 00019021 TSC 0x3 SQL cmd:heart-beat will be processed, name:, type:0
06/14 09:37:56.848378 00019021 RPC TSC 0x7f81b847f188 0x3, heartbeat is sent to 127.0.0.1:6030, len:121 sig:0x01000000:0x05000000:51430
06/14 09:37:56.848432 00019021 RPC TSC 0x6, connection error happens
06/14 09:37:56.848460 00019021 TSC WARN 0x6 it shall renew table meta, code:Unable to establish connection, retry:1
06/14 09:37:56.848505 00019021 TSC 0x6 update table meta:0.operation.log, old meta numOfTags:0, numOfCols:2, uid:5910974527751587
06/14 09:37:56.848573 00019021 TSC 0x6 remove table meta 0.operation.log, numOfRemain:0
06/14 09:37:56.848607 00019021 TSC 0xe new SqlObj from 0x7f81a8163350, total in tscObj:4, total:5
06/14 09:37:56.848615 00019021 TSC 0x6 new pSqlObj:0xe to get 1 tableMeta, vgroupInfo:0, udf:0, msg size:29
06/14 09:37:56.848621 00019021 TSC 0x6 metaRid from 0x7 to 0xe
06/14 09:37:56.848625 00019021 TSC 0xe SQL cmd:multi-meta will be processed, name:, type:0
06/14 09:37:56.848636 00019021 RPC TSC 0x7f81b81ec128 client connection is allocated, uid:0xb81fa5c6
06/14 09:37:56.849076 00019027 RPC TSC 0x7f81b847f188 0x3, heartbeat-rsp received from 0x100007f:6030, parse code:0x0 len:742 sig:0x05000000:0x01000000:51430 code:0x0
06/14 09:37:56.849119 00019027 TSC 0x3 reset retry counter to be 0 due to success rsp, old:0
06/14 09:37:56.849133 00019027 TSC 0x3 SQL cmd:heart-beat, code:success rspLen:674
06/14 09:37:56.849143 00019027 TSC 0x3 send heartbeat in 1500ms
06/14 09:37:58.107555 00019023 UTL rpcObj refresh thread scan

/var/log/messages文件
在连接断开约15分钟后
Jun 14 09:37:59 username kernel: hamand[19017]: segfault at 4 ip 00007f81bb30b4d8 sp 00007f81bb24c750 error 4 in libtaos.so.2.4.0.12[7f81bb24f000+390000]
Jun 14 09:37:59 username systemd: main-processd.service: main process exited, code=killed, status=11/SEGV
Jun 14 09:37:59 username systemd: Unit main-processd.service entered failed state.
Jun 14 09:37:59 username systemd: main-processd.service failed.

**Comment by GuoLijuan** [comment]
> > 实例代码 1、在A服务器上跑demo，在启动demo时，A服务器到B(host_ip)服务器网络是通的 2、demo启动成功后，A到B(host_ip)网络中断 3、等待约15分钟左右，会报错
> 
> 我还在复现。有没有一些关键性的日志。发一下客户端的详细错误堆栈和服务端taosd的日志信息（在/etc/taos/taos.cfg文件调高下日志级别）

使用下面的demo可以复现问题
启动demo后，打印出retry:1后，中断到taosd服务器的网络
console打印到 约 retry:9 后，主进程会挂掉
main process, retry: 9
Segmentation fault



"""
Python asynchronous subscribe demo.
run on Linux system with: python3 subscribe_demo.py
"""
from threading import Thread

import taos
import time


def consume():
    host_ip = ''
    username = ''
    password = ''
    conn = taos.connect(host=host_ip,
                        user=username,
                        password=password)
    restart = False
    interval = 2000  # consumption interval in microseconds.
    topic = "topic-meter-current-bg" # Error topic
    sql = "select * from power.meters where current > 10"  # Error sql
    print("begin to consume")
    sub = conn.subscribe(restart, topic, sql, interval)
    while True:
        data = sub.consume()
        print(f"consume data:{data}")
        for d in data:
            print(f"consume data:{data}")


def consume_in_thread():
    t = Thread(target=consume)
    t.setDaemon(True)
    t.start()


def main():
    consume_in_thread()
    retry = 1
    while True:
        print(f"main process, retry: {retry}")
        retry += 1
        time.sleep(2*60)


if __name__ == '__main__':
    main()

**Comment by zhangbiyun** [comment]
@GuoLijuan 在最新的代码编译版本上没有复现。升级下版本试试

main process, retry: 1
begin to consume
consume data:<taos.result.TaosResult object at 0x7f65df849070>
consume data:<taos.result.TaosResult object at 0x7f65df849070>
consume data:<taos.result.TaosResult object at 0x7f65df849070>
consume data:<taos.result.TaosResult object at 0x7f65df849070>
consume data:<taos.result.TaosResult object at 0x7f65df849070>
consume data:<taos.result.TaosResult object at 0x7f65df849070>
consume data:<taos.result.TaosResult object at 0x7f65df849400>
consume data:<taos.result.TaosResult object at 0x7f65df849460>
consume data:<taos.result.TaosResult object at 0x7f65df849490>
consume data:<taos.result.TaosResult object at 0x7f65df8494f0>
consume data:<taos.result.TaosResult object at 0x7f65df849070>
consume data:<taos.result.TaosResult object at 0x7f65df849400>
consume data:<taos.result.TaosResult object at 0x7f65df849460>
consume data:<taos.result.TaosResult object at 0x7f65df849490>
consume data:<taos.result.TaosResult object at 0x7f65df8494f0>
consume data:<taos.result.TaosResult object at 0x7f65df849070>
consume data:<taos.result.TaosResult object at 0x7f65df849400>
consume data:<taos.result.TaosResult object at 0x7f65df849460>
consume data:<taos.result.TaosResult object at 0x7f65df849490>
consume data:<taos.result.TaosResult object at 0x7f65df8494f0>
consume data:<taos.result.TaosResult object at 0x7f65df849070>
consume data:<taos.result.TaosResult object at 0x7f65df849400>
consume data:<taos.result.TaosResult object at 0x7f65df849460>
consume data:<taos.result.TaosResult object at 0x7f65df849490>
main process, retry: 2
main process, retry: 3
main process, retry: 4
main process, retry: 5
main process, retry: 6
main process, retry: 7
main process, retry: 8
main process, retry: 9
consume data:<taos.result.TaosResult object at 0x7f65df8494f0>

**Comment by GuoLijuan** [comment]
> @GuoLijuan 在最新的代码编译版本上没有复现。升级下版本试试
> 
> main process, retry: 1 begin to consume consume data:<taos.result.TaosResult object at 0x7f65df849070> consume data:<taos.result.TaosResult object at 0x7f65df849070> consume data:<taos.result.TaosResult object at 0x7f65df849070> consume data:<taos.result.TaosResult object at 0x7f65df849070> consume data:<taos.result.TaosResult object at 0x7f65df849070> consume data:<taos.result.TaosResult object at 0x7f65df849070> consume data:<taos.result.TaosResult object at 0x7f65df849400> consume data:<taos.result.TaosResult object at 0x7f65df849460> consume data:<taos.result.TaosResult object at 0x7f65df849490> consume data:<taos.result.TaosResult object at 0x7f65df8494f0> consume data:<taos.result.TaosResult object at 0x7f65df849070> consume data:<taos.result.TaosResult object at 0x7f65df849400> consume data:<taos.result.TaosResult object at 0x7f65df849460> consume data:<taos.result.TaosResult object at 0x7f65df849490> consume data:<taos.result.TaosResult object at 0x7f65df8494f0> consume data:<taos.result.TaosResult object at 0x7f65df849070> consume data:<taos.result.TaosResult object at 0x7f65df849400> consume data:<taos.result.TaosResult object at 0x7f65df849460> consume data:<taos.result.TaosResult object at 0x7f65df849490> consume data:<taos.result.TaosResult object at 0x7f65df8494f0> consume data:<taos.result.TaosResult object at 0x7f65df849070> consume data:<taos.result.TaosResult object at 0x7f65df849400> consume data:<taos.result.TaosResult object at 0x7f65df849460> consume data:<taos.result.TaosResult object at 0x7f65df849490> main process, retry: 2 main process, retry: 3 main process, retry: 4 main process, retry: 5 main process, retry: 6 main process, retry: 7 main process, retry: 8 main process, retry: 9 consume data:<taos.result.TaosResult object at 0x7f65df8494f0>

1、升级版本是指升级taos client 吗？
2、你复现使用的taos client版本是多少？
3、建议尝试断网时间延长到20分钟，看看是否会复现？

**Comment by zhangbiyun** [comment]
@GuoLijuan 

> > 1、升级版本是指升级taos client 吗？（目前使用的是v2.4.0.12）
> > 2、你复现使用的taos client版本是多少？

root@ubuntu:/home/user/Desktop# taos

Welcome to the TDengine shell from Linux, Client Version:2.7.0.0
Copyright (c) 2022 by TAOS Data, Inc. All rights reserved.

> > 3、建议尝试断网时间延长到20分钟，看看是否会复现？

retry:71 没复现

main process, retry: 71
consume data:<taos.result.TaosResult object at 0x7f838437d160>
consume data:<taos.result.TaosResult object at 0x7f838437d190>

**Comment by GuoLijuan** [comment]
@zhangbiyun 你好 tdengine怎么升级呢？参考哪个手册？谢谢

**Comment by fenghuazzm** [comment]
这儿有个离线升级的博客
https://www.taosdata.com/blog/2022/06/07/10222.html

**Comment by GuoLijuan** [comment]
> @GuoLijuan
> 
> > > 1、升级版本是指升级taos client 吗？（目前使用的是v2.4.0.12）
> > > 2、你复现使用的taos client版本是多少？
> 
> root@ubuntu:/home/user/Desktop# taos
> 
> Welcome to the TDengine shell from Linux, Client Version:2.7.0.0 Copyright (c) 2022 by TAOS Data, Inc. All rights reserved.
> 
> > > 3、建议尝试断网时间延长到20分钟，看看是否会复现？
> 
> retry:71 没复现

@zhangbiyun 
升级到官网上最新的版本 2.6.0.7 复现该问题
segfault at 4 ip 00007f10e714ee32 sp 00007f10e3b969a0 error 4 in libtaos.so.2.6.0.4[7f10e708b000+3b3000]

是否可以提供下 2.7.0.0 版本？

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
