### ISSUE TITLE
There is an error in the log says that a SQL is wrong, but copy the SQL and run it in the client shell, the result is success.

### ISSUE THREAD

**Issue by xaseven** [taosdata/TDengine#1368]
日志：
TAOS DRIVER 2020/03/13 20:01:04 taosSqlCgo.go:62: taos_query() failed: timestamp out of range
TAOS DRIVER 2020/03/13 20:01:04 taosSqlCgo.go:63: taosQuery() input sql:INSERT INTO PGW134840E1170415180102180506001Z USING device TAGS (PGW134840E1170415180102180506001Z) VALUES (1584100862967,200313200049,0,0,1000,933,518,0,0,660,99,16,3256,3209,15,1,0,640,630,660,0,0,4000,0,0,0,0,0,93,0,0,3209,3236,3232,3246,3244,3248,3221,3232,3252,3238,3248,3232,3241,3245,3256,3231,0,0,0,0);

日志中的SQL语句却在控制台能执行成功；

类似错误经常发生，不知为何。
我用的是Golang的驱动连接的；记录日志的地方在 taosSql\taosSqlCgo.go的 func (mc *taosConn) taosQuery(sqlstr string) (int, error) {...}中。

**Comment by plum-lihui** [comment]
1、请将配置文件的中调试开关打开：将下面两句添加到配置文件里面（/etc/taos/taos.cfg）
debugflag                   135
tscEnableRecordSql    1
2、然后重新测试
3、将日志文件压缩打包发送给我们来分析：/var/log/taos/
多谢！

**Comment by xaseven** [comment]
好的，设置好了，taosd 也重启了，有了问题后日志文件怎么发给你？

**Comment by xaseven** [comment]
上次发给您的日志是按照您所描述的已经做好更改后产生的，当然也包括没有更改前产生的内容。

这块我已经在上次邮件里说明了，上次更改配置文件后，已经重启了taosd的服务。

我现在把完整的配置文件发给您，看下是否其他参数没有开启的原因？

（附件为配置文件）



谢谢


戚宗伟 18500682685


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"plum-lihui"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月14日(星期六) 下午5:31
收件人:&nbsp;"taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送:&nbsp;"戚宗伟"<xaseven@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [taosdata/TDengine] 日志中发现一条SQl执行错误，然而在命令行下执行此SQL语句却能成功 (#1368)





 
1、请将配置文件的中调试开关打开：将下面两句添加到配置文件里面（/etc/taos/taos.cfg）
 debugflag                   135
 tscEnableRecordSql    1
 2、然后重新测试
 3、将日志文件压缩打包发送给我们来分析：/var/log/taos/
 多谢！
