### ISSUE TITLE
有example吗？

### ISSUE THREAD

**Issue by dcmr** [taosdata/TDengine#137]
有example吗？

**Comment by Summerdou** [comment]
刚接触这个数据库，还不知道怎么用，能用在什么地方

**Comment by fengshaoxie** [comment]
> 刚接触这个数据库，还不知道怎么用，能用在什么地方

可以用在工业物联网中

**Comment by johnnyhou327** [comment]
@dcmr @Summerdou  请查看一下readme中的操作和官网文档[Quick Start](https://www.taosdata.com/en/getting-started/#快速上手)。后面我们会增加更多的例子。
