### ISSUE TITLE
Unable to resolve FQDN on kubernetes pod.

### ISSUE THREAD

**Issue by kaybinwong** [taosdata/TDengine#13775]
**Bug Description**
Unable to resolve FQDN on kubernetes pod.
1/ taos.cfg had bean set
2/ /etc/hosts had been set
![image](https://user-images.githubusercontent.com/5570216/173306109-c65f04d6-4622-4b7a-be0e-8b8b5e5af97c.png)

![image](https://user-images.githubusercontent.com/5570216/173304081-28412dc3-3d39-49b1-a78b-7251aa848fa1.png)

**To Reproduce**
dockerfile
![image](https://user-images.githubusercontent.com/5570216/173304804-0a8801e7-cd64-42f6-9011-8e786a23e6e0.png)

**Expected Behavior**
the pod connect to taos-server successfully

**Environment (please complete the following information):**
 - OS: 
 k8s 1.23
 - Memory, CPU, current Disk Space
 - TDengine Version 
 c & s are both 2.6.0.1

the network is reachable on other pod which running by kubectl
```
[root@node1 traderdata]# kubectl run busybox -n mizar --image=busybox -- ping taosd.infra -c 10
pod/busybox created
```
![image](https://user-images.githubusercontent.com/5570216/173305115-cf3aad6c-0a72-441e-9300-87b1bd409441.png)

**by the way, is it necessary to set /etc/taos/taos.cfg on every client?**

**Comment by yu285** [comment]
我们不建议开源用户使用 k8s,运维复杂，容易带来很多未知问题， 除非可以自己维护好。

另外 2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
