### ISSUE TITLE
关于prepared statement

### ISSUE THREAD

**Issue by yushengery** [taosdata/TDengine#1378]
Hello， 
我现在打算研究TDengine用于存储我们游戏产品的所有客户端、服务器之间的数据包，用于分析用户操作以及服务器的响应状况，因为通信协议是protobuf，所以我们想将这些二进制的数据存到TDengine的binary类型字段里面，请问这样做是否可行。
所以我在测试的时候就想使用prepared stmt来做二进制字段的insert操作，请问
```
typedef struct TAOS_BIND {
  int            buffer_type;
  void *         buffer;
  unsigned long  buffer_length;  // unused
  unsigned long *length;  //这个length为什么要通过指针传入呢？
  int *          is_null;
  int            is_unsigned;  // unused
  int *          error;        // unused
} TAOS_BIND;
```
另外请教有关于prepared stmt的一些实例代码吗？

**Comment by Shawshank-Smile** [comment]
Let us make a try, I think binary type will work, but not sure.

**Comment by localvar** [comment]
@yushengery 这个结果是按照最大程度兼容mysq的标准l编写的，在mysql中输出参数，此时通过指针可以返回输出数据的长度。

prepare示例代码代码已经提交，稍后合并到develop分支后，即可查看：tests/examples/c/prepare.c
