### ISSUE TITLE
insert csv data into table give unexpected result

### ISSUE THREAD

**Issue by physercoe** [taosdata/TDengine#138]
data in test.csv is as follows:
_2018-03-30 21:13:00,1.0000,2.00000,3.00000,4.00000,5_

when create a table in tdengine:

`taos> create table bar (dt timestamp, o float, c float, h float, l float, v int);`
`Query OK, 1 row(s) affected (0.001001s)`

`taos> insert into bar file test.csv;`
`Query OK, 1 row(s) affected (0.001355s)`

`taos> select * from bar;`
`          dt          |         o          |         c          |         h          |         l          |     v`     
`==========================================================`
` 18-03-30 21:13:00.000|         -3.00000|           -30.00000|            21.00000|       0.00000|   0| ` 
`Query OK, 1 row(s) in set (0.001625s)`

the above result shows the fields in table bar  except the timestamp are not the data in test.csv file, why?

**Comment by johnnyhou327** [comment]
@physercoe thanks for reporting this issue. In the csv file, timestamps with a string format like "YYYY-MM-DD HH:mm:SS.sss" should be quoted. If you're using epoch timestamps in the csv file, then please don't quote the timestamp. So try organize the data in the test.csv file like this:
<pre>"2018-03-30 21:13:00",1.0000,2.00000,3.00000,4.00000,5</pre>
Also all data columns of string types (``binary``, ``nchar``) should also be quoted in the .csv file.

**Comment by physercoe** [comment]
thanks, it works,  though not a very convenient way since the file format is different from common one, perhaps it will be better to assign an option parameter in the command(such as "import into bar file test.csv format xx") than to change the original data file~

Another question is whether Tdengine can import/insert selected columns in the csv file, i.e., the test.csv is like this:
`2018-03-30 21:13:00",1.0000,2.00000,3.00000,4.00000,5,6,7,8`
and I just want to import the 1st,2nd,3rd,4th,9th column into the table bar, is there a way to do this?

**Comment by plum-lihui** [comment]
Sorry，this function is not supported！

**Comment by physercoe** [comment]
OK～
Maybe TDengine can support this kind of functions in the future~
