### ISSUE TITLE
The taosd service memory usage has been increasing from 10% to 100%, causing the service to restart

### ISSUE THREAD

**Issue by wuyongx** [taosdata/TDengine#13825]
**Performance Issue** 
1、内存使用一直在上涨从10%，一直达到100%。
2、重启TDengine之后，内存使用降到10%，然后一直增长直到100%。

**To Reproduce**
期望解决内存一直上涨的问题。

**Screenshots**
<img width="1563" alt="截屏2022-06-14 18 48 52" src="https://user-images.githubusercontent.com/5822929/173561141-c55953f7-cc2c-4410-b311-6464fcc31c5e.png">
<img width="1130" alt="截屏2022-06-14 18 34 36" src="https://user-images.githubusercontent.com/5822929/173561641-7ea19f99-a7f2-4141-9622-a9a7a8cbcc48.png">
<img width="1616" alt="截屏2022-06-10 19 45 26" src="https://user-images.githubusercontent.com/5822929/173561666-a5cc7722-7cfb-44c3-a1f3-6e0172557b61.png">

**Environment (please complete the following information):**

* OS: [Red Hat Enterprise Linux Server release 7.6 ]
* Memory, CPU, current Disk Space ：5台数据节点 。8C 24G  ,500G  
* TDengine Version [2.4.0.7]

**Comment by fenghuazzm** [comment]
这些节点的内存都升到了 100% 吗？
请问是有在做什么操作呢，是否写入的同时伴随大量读取

**Comment by wjehovah** [comment]
5个节点，2个有90%，其他3个80%~90% 不等。
1、写入操作一直有。 看截图，大概60cps
2、读取是也没查询的，最近也没有很频繁。

**Comment by fenghuazzm** [comment]
这种情况感觉是咱们 taosd 的 buffer pool 容量参数给大了一些，请看如下规划、控制大小：
https://docs.taosdata.com/operation/planning
