### ISSUE TITLE
The TDengine deployed on Kubernetes loses data after the image version is upgraded

### ISSUE THREAD

**Issue by wuxingwang1997** [taosdata/TDengine#13845]
更换镜像，存在数据丢失的问题，想了解下如何不丢失数据的情况下做 版本升级，备份数据k8s不支持6030端口连接，我该怎么操作呢

**Comment by yu285** [comment]
我们不建议开源用户使用k8s，运维复杂，除非可以自处理好。官方不好给到支持。 

另外，2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
