### ISSUE TITLE
How do I use TDengine with IDEA database management tools？

### ISSUE THREAD

**Issue by Booooooger** [taosdata/TDengine#13852]
主要是在按照文档指示过程中遇到的一点小问题；文档地址：https://www.taosdata.com/2020/08/27/1767.html

文档中说因为官方的taos-jdbcdriver依赖Apache-common，导致无法在IDEA DataSource中不能直接运行。为此，博主重新编译了一个jar文件，去除了apache-common的依赖。并提供了下载地址

https://download.csdn.net/download/zjq852533445/12709922

由于这是CSDN的下载地址，虽然不需要下载积分，但是碍于CSDN的策略需要下载码，导致无法正常下载。

所以在这里请求下，能否单独提供一个下载地址

**Comment by fenghuazzm** [comment]
您好，不需要去下载 CSDN 那个旧版本。我看了一下确实缺点依赖，可以这样简单操作一下：
1. 克隆最新 jdbc-conn 的代码到本地（或者直接下载）：  git clone https://github.com/taosdata/taos-connector-jdbc.git
2. 进入此目录：cd taos-connector-jdbc
3. 编译、打 jar 包：mvn clean install -D maven.test.skip=true
4. 进入 target 目录得到 taos-jdbcdriver-2.0.XX-dist.jar 的 jar 包，idea 加载这个驱动、添加数据源。
5. 测试一下这个连接，提示缺什么依赖就打上，网上搜一下相应 jar 包，我拿 RESTful 连接串做示例。

<img width="551" alt="image" src="https://user-images.githubusercontent.com/70138133/175815855-feec0c13-0b25-4780-b76a-19e5c332fe1e.png">

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/70138133/175815797-c5bfc64a-692b-4579-a637-141040f5eb94.png">

完毕了最后测试发现出现黄色感叹号小错误，不影响使用。
RESTful 由于连接本身没状态，想看哪个表的数据需要改下 url 后面的 DB。
JNI 方式需要安装 TDengine 客户端。

**Comment by fenghuazzm** [comment]
本人 DBeaver 等工具也是这样简单设置了查看的。
若对上述有疑问可加本人微信：Deja_vu_4u 讨论。
