### ISSUE TITLE
TDengine启动失败：ERROR TMR Failed to create timer 

### ISSUE THREAD

**Issue by shanlanCoding** [taosdata/TDengine#1388]
**Bug Description**
通过：systemctl start taosd.service启动
查询状态：systemctl status taosd，结果是失败
通过命令：`cat "/var/log/taos/taosdlog.1"`查询日志，发行报错如下：
`03/20 10:28:01.883841 26781 7f4987f6d700 ERROR TMR Failed to create timer`

**To Reproduce**
1. 通过：systemctl start taosd.service启动
2. 查询状态：systemctl status taosd，结果是失败
3. 通过命令：`cat "/var/log/taos/taosdlog.1"`查询日志，发行报错如下：
`03/20 10:28:01.883841 26781 7f4987f6d700 ERROR TMR Failed to create timer`

**Expected Behavior**
希望TDengine 能够正常启动

**Screenshots**
![image](https://user-images.githubusercontent.com/44717382/77131246-f7e6f080-6a95-11ea-9cda-d530639bc754.png)

![image](https://user-images.githubusercontent.com/44717382/77131382-72177500-6a96-11ea-9b7a-a5c9134ab9ac.png)

**Environment (please complete the following information):**
 - OS: [Ubuntu 16.04.5 LTS (GNU/Linux 4.15.18-12-pve x86_64)]
 - Memory 4GB , CPU 4, current Disk Space 60GB
 - TDengine Version [TDengine-server-1.6.5.5-Linux-x64.deb]

**Additional Context**

**Comment by plum-lihui** [comment]
是使用root权限启动的taosd服务吗？

**Comment by shanlanCoding** [comment]
> 是使用root权限启动的taosd服务吗？

没有sudo ，但是是root权限。

**Comment by shanlanCoding** [comment]
> 是使用root权限启动的taosd服务吗？

我添加了微信“tdengine”，回复了加群的关键字，但是没有人添加我进入微信群，是方法不对吗？

**Comment by Shawshank-Smile** [comment]
Try this:
systemctl start taosd

**Comment by shanlanCoding** [comment]
> 试试这个：
> systemctl start taosd

Thanks you , But still not.

**Comment by Shawshank-Smile** [comment]
Add wechat 13720014098， Let me have a look。

**Comment by Shawshank-Smile** [comment]
The virtual machine is a MONSTER，we decide to make a new one。
