### ISSUE TITLE
请问,为什么更新到最新版本,输入用户名密码依然授权失败呢

### ISSUE THREAD

**Issue by pigwing** [taosdata/TDengine#139]
root@ubuntu-server:~# taos -u root -p
Enter password: taosdata
TSDB error: authentication failure

利用官方上面的用户名密码
-u, -- user: 链接TDengine服务器的用户名，缺省为root
-p, --password: 链接TDengine服务器的密码，缺省为taosdata

**Comment by johnnyhou327** [comment]
@pigwing 试试把/var/lib/taos/下的文件全部删掉，然后重启服务，再登陆试试。之前版本中密码存储没有加密，因此做了改动。升级到最行版本后，之前的数据文件可能没删掉，校验用的还是未加密的密码，因此出现密码不正确。

**Comment by pigwing** [comment]
@johnnyhou327 好了,谢谢.
