### ISSUE TITLE
column include -nan value, query return invalid value

### ISSUE THREAD

**Issue by xibaoning** [taosdata/TDengine#13906]
研究怎样查询-nan时发现问题:

数据库版本 2.6.0.4
//查询1
taos> select ts,Open,High,Low,Close,volume from dce_p09_day1 where ts>'2017-09-18' and open<0;
           ts            |         open         |         high         |         low          |        close         |   volume    |
====================================================================================================================================
 2017-09-19 00:00:00.000 |                 -nan |                 -nan |                 -nan |           5666.00000 |         173 |
 2017-11-01 00:00:00.000 |                 -nan |                 -nan |                 -nan |           5632.00000 |         798 |
Query OK, 2 row(s) in set (0.001684s)

//查询2
taos> select ts,Open,High,Low,Close,volume from dce_p09_day1 where ts>'1900-01-01' and open<0;
Query OK, 0 row(s) in set (0.002494s)

如上2个例子, 第2个不能查询出结果,  

另外查询列中有-nan值的sql正确写法是什么呢

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
