### ISSUE TITLE
DB error: invalid operation: invalid column name

### ISSUE THREAD

**Issue by nightkids2008** [taosdata/TDengine#13935]
当前环境：
TDengine 服务端 版本为：2.6.0.4 , 运行环境为 centos7.8
TDengine 客户端 版本为：2.6.0.4 ，运行环境为win10
JDBC 驱动版本为：com.taosdata.jdbc:taos-jdbcdriver:2.0.39

问题截图：
![1655448572748](https://user-images.githubusercontent.com/13149107/174241861-e7f13384-3591-4843-9851-aacde58aad3a.png)

问题描述：
当前表的描述中，存在列”pStatus”，但是通过语句 “select ts,pStatus from jiningzhongchang.equipment_cjk1620_1 ;”指定列来进行查询时，却返回错误 “DB error: invalid operation: invalid column name”

**Comment by fenghuazzm** [comment]
看表结构有个字段是 pStatus ，估计是建表时候加了 `` 反斜杠（不然默认都会变成小写字符）
查询的时候这样：select ts,`pStatus` from jiningzhongchang.equipment_cjk1620_1    就可以了

**Comment by fenghuazzm** [comment]
`pStatus` 前后加上 `` 。默认有 markdown 效果 : )

**Comment by nightkids2008** [comment]
使用无模式进行的insert操作，语句中并没有`` 反斜杠

**Comment by fenghuazzm** [comment]
> 使用无模式进行的insert操作，语句中并没有`` 反斜杠

无模式写入，默认带了反引号。我觉得你可以先试试我上面说的

![image](https://user-images.githubusercontent.com/70138133/174274965-6f157841-7b74-49fc-a7ae-a2cb3f68abca.png)

**Comment by nightkids2008** [comment]
目前，应用程序中，拼接无模式的行协议数据时，把表名、tag名、field名统统转化成了小写。现已解决这个问题。
