### ISSUE TITLE
Submit flink task and cancel ，the error occur ： No suitable driver found for jdbc:TAOS://hadoop001:6030?user=root&password=taosdata

### ISSUE THREAD

**Issue by ambitfly** [taosdata/TDengine#13944]
在flink集群测试实时把pulsar的数据写入TDengine的时候，第一次提交任务可以运行成功，然后把任务cancel掉后，再次启动就会报No suitable driver found for jdbc:TAOS://hadoop001:6030?user=root&password=taosdata错误，导致任务提交失败，后续提交任务都会失败，报同样的错误。windows本地环境和linux本地环境都没有问题。

**Comment by fenghuazzm** [comment]
可以尝试把 jdbc 的 jar 包放到每个 flink 的节点 lib 目录，然后执行不带依赖包的写入程序。或者直接使用 Restful 接口方式走 6041 端口。

**Comment by ambitfly** [comment]
这两种方法都尝试了，都不行。我发现flink的类加载机制不是双亲委派机制，flink默认会先由用户自己的类加载器加载。所以我怀疑虽然他们的源头相同，但不是同一个类加载器加载，导致后面的flink任务的类加载失败以至于找不带合适的驱动。因为我不是很了解jdbc的驱动实现，这只是我的猜测。基于这个猜测我想到了两种解决方案。第一种，使用 单作业模式提交flink作业
第二种，修改flink配置文件，使得com.taosdata.jdbc.路径下的类加载的时候通过双亲委派机制加载，这样只有一个类加载器了。我将在周一的时候尝试这两种方案。
