### ISSUE TITLE
taos connect diffent host Invalid database name

### ISSUE THREAD

**Issue by xibaoning** [taosdata/TDengine#13989]
某台主机启动了2个td主数据库容器,  版本: 2.6.0.4
docker容器1端口:  6030-6042:6030-6042   数据库名: future
docker容器2端口:  16030-16042:6030-6042  数据库名: futuretick

宿主机taos命令登录容器2 16030,链接成功,show databases命令正常显示: 
![image](https://user-images.githubusercontent.com/48142659/174473980-b36f2e75-8dbb-4c21-8814-8c1b3a25aa65.png)

使用use futuretick时提示错误: DB error: Invalid database name (0.002000s)
使用use future 正常 (其实错了, 用到容器1的数据库了)

上面的意思:  登录到容器2服务器, 数据库也显示的容器2, 但切换数据库时却使用了容器1的数据库, 好像内部隔离混乱
生产环境: 对相同主机上2个td服务, 读取容器1的数据, 插入到容器2中,  但目前并没有能正常工作

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
