### ISSUE TITLE
insert into ... file .....csv not work

### ISSUE THREAD

**Issue by alon-zhong** [taosdata/TDengine#1406]
**Bug Description**
taos> create table temp_table_1(ts timestamp,v1 float);
Query OK, 1 row(s) affected (0.000698s)

taos> select count(*) from temp_table_1;
Query OK, 0 row(s) in set (0.218074s)

taos> insert into temp_table_1 file /root/temp_table_1.csv;

DB error: invalid table

=====================
temp_table_1.csv has only one row:
1563262800000,12.58

**Environment (please complete the following information):
 - TDengine Version [e.g. 1.6.5.6]

**Comment by Shawshank-Smile** [comment]
This may be caused by the csv, which is edited in windows.

 insert into testtb file ~/testfile/3.10-input_data.txt; 
 select * from testtb; 
 select * from testtb >> ~/testfile/3.10-output_data.txt;
