### ISSUE TITLE
1.6.2.2 crash

### ISSUE THREAD

**Issue by sunashe** [taosdata/TDengine#1407]
**Bug Description**
跑着跑着crash了，然后启动不了了。

**To Reproduce**
。。。

**Expected Behavior**
。。。

**Screenshots**

**Environment (please complete the following information):**
 - OS: centos6.5
 - Memory, CPU, current Disk Space
256G 32c64 
2.6.32-696.1.1.el6.x86_64 #1 SMP Tue Apr 11 17:13:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
 - TDengine Version [e.g. 1.6.1.7]
1.6.2.2

**Additional Context**

**Comment by sunashe** [comment]
gdb ./bin/taosd core.128754
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-92.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /data/tdengine/taos/bin/taosd...done.
[New Thread 128786]
[New Thread 128768]
[New Thread 128756]
[New Thread 128758]
[New Thread 128755]
[New Thread 128769]
[New Thread 128767]
[New Thread 128779]
[New Thread 128757]
[New Thread 128754]
[New Thread 128770]
[New Thread 128778]
[New Thread 128759]
[New Thread 128771]
[New Thread 128777]
[New Thread 128761]
[New Thread 128766]
[New Thread 128764]
[New Thread 128772]
[New Thread 128776]
[New Thread 128765]
[New Thread 128762]
[New Thread 128763]
[New Thread 128773]
[New Thread 128760]
[New Thread 128775]
[New Thread 128774]
Reading symbols from /lib64/libpthread.so.0...(no debugging symbols found)...done.
[Thread debugging using libthread_db enabled]
Loaded symbols for /lib64/libpthread.so.0
Reading symbols from /lib64/libm.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libm.so.6
Reading symbols from /lib64/librt.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/librt.so.1
Reading symbols from /lib64/libc.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libc.so.6
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2
Reading symbols from /lib64/libgcc_s.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libgcc_s.so.1
Core was generated by `./bin/taosd -c /etc/taos/'.
Program terminated with signal 6, Aborted.
#0  0x0000003ce9232495 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.209.el6_9.2.x86_64 libgcc-4.4.7-18.el6_9.2.x86_64
(gdb) bt
#0  0x0000003ce9232495 in raise () from /lib64/libc.so.6
#1  0x0000003ce9233c75 in abort () from /lib64/libc.so.6
#2  0x0000003ce92703a7 in __libc_message () from /lib64/libc.so.6
#3  0x0000003ce9275dee in malloc_printerr () from /lib64/libc.so.6
#4  0x0000003ce9278c3d in _int_free () from /lib64/libc.so.6
#5  0x000000000045b451 in vnodeCommitMultiToFile (pVnode=0x7f1a9516a210, ssid=0, esid=102400) at /data/TDengine-ver-1.6.2.2/src/system/src/vnodeFile.c:866
#6  0x000000000045b4c1 in vnodeCommitToFile (param=0x7f1a9516a210) at /data/TDengine-ver-1.6.2.2/src/system/src/vnodeFile.c:876
#7  0x0000003ce9607aa1 in start_thread () from /lib64/libpthread.so.0
#8  0x0000003ce92e8bcd in clone () from /lib64/libc.so.6
(gdb) up 5
#5  0x000000000045b451 in vnodeCommitMultiToFile (pVnode=0x7f1a9516a210, ssid=0, esid=102400) at /data/TDengine-ver-1.6.2.2/src/system/src/vnodeFile.c:866
866	  tfree(pOldCompBlocks);
(gdb) info locals
vnode = 64
data = {0x7edeb6c1a048, 0x7edeb6c22056, 0x7edeb6c2a064, 0x7edeb6c32072, 0x7edeb6e32080, 0x7edeb6e3a08e, 0x0 <repeats 195 times>, 0x3ce8e09696, 0x0, 0x7edebff37c40, 0x0, 0x7edebff37c40, 0x6, 0x7f1ad00e7a80,
  0xb3e3f58e, 0x3ce8e09fe2, 0x0, 0x2cf8fd6, 0xe, 0x3ce92032bc, 0x0, 0x7edebff37dc0, 0x3ce9203c48, 0x3ce920ce10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7f1ad00fe658, 0x0, 0x7f1ad00e7d08, 0x7f1ad00e74c8,
  0x3ce9602fa0, 0x3ce9210758, 0x3ce96013f8, 0x500000000, 0x100000613, 0x0, 0x0, 0x7f1ad00fe9b0, 0x7edebff37e10, 0x7edebff37e38, 0x7f1ad00fe658, 0x7f1ad00e7d08, 0xb3e3f58e, 0x3ce8e0a26a, 0x0, 0x7f1ad00e7d08,
  0x5, 0x0, 0x1, 0x7f1ad00fe658, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7f1ad00fe9b0, 0x7edebff37dc0, 0x0}
cdata = {0x7edeb6e3ce48, 0x7edeb6e44e56, 0x7edeb6e4ce64, 0x7edeb6e54e72, 0x7edeb7054e80, 0x7edeb705ce8e, 0x0 <repeats 250 times>}
buffer = 0x0
dmem = 0x7edaca3d3048 <Address 0x7edaca3d3048 out of bounds>
cmem = 0x7edaca5f5e48 <Address 0x7edaca5f5e48 out of bounds>
hmem = 0x7edac729b010 <Address 0x7edac729b010 out of bounds>
tmem = 0x7edaca818c48 <Address 0x7edaca818c48 out of bounds>
pObj = 0x9f1ffb0
compInfo = {uid = 0, last = -1, numOfBlocks = 792341410966229, delimiter = 1648573556, checksum = 368964, compBlocks = 0x7edebff36d20}
pHeader = 0x7edaca818c50
meterInfo = 0x7edaca8e0c54
pMeter = 0x7edaca8e0cec
query = {numOfCols = 0, order = {order = 0, orderColId = 0}, keyIsMet = 0 '\000', over = 0 '\000', fileId = 0, hfd = 0, dfd = 0, lfd = 0, pBlock = 0x0, pFields = 0x0, numOfBlocks = 0, blockBufferSize = 0,
  currentSlot = 0, firstSlot = 0, slot = 0, pos = 0, key = 0, compBlockLen = 0, blockId = 0, skey = 0, ekey = 0, nAggTimeInterval = 0, intervalTimeUnit = 0 '\000', numOfOutputCols = 0, interpoType = 0,
  checkBufferInLoop = 0, limit = {limit = 0, offset = 0}, rowSize = 0, dataRowSize = 0, pGroupbyExpr = 0x0, pSelectExpr = 0x0, colList = 0x0, numOfFilterCols = 0, pFilterInfo = 0x0, defaultVal = 0x0,
  lastKey = 0, pointsRead = 0, pointsToRead = 0, pointsOffset = 0, sdata = 0x0, tsData = 0x0}
colList = {{data = {colId = 0, type = 0, bytes = 0, filterOn = 0, lowerRelOptr = 0, upperRelOptr = 0, filterOnBinary = 0, {{lowerBndi = 0, upperBndi = 0}, {lowerBndd = 0, upperBndd = 0}, {pz = 0,
          len = 0}}}, colIdx = 0, colIdxInBuf = 0, req = {0, 0}} <repeats 256 times>}
pExprs = {{pBase = {functionId = 0, numOfParams = 0, colInfo = {colId = 0, colIdx = 0, colIdxInBuf = 0, isTag = false}, arg = {{argType = 0, argBytes = 0, argValue = {d = 0, i64 = 0, pz = 0x0}}, {
          argType = 0, argBytes = 0, argValue = {d = 0, i64 = 0, pz = 0x0}}, {argType = 0, argBytes = 0, argValue = {d = 0, i64 = 0, pz = 0x0}}}}, pBinExprInfo = {pBinExpr = 0x0, numOfCols = 0,
      pReqColumns = 0x0}, resBytes = 0, resType = 0} <repeats 256 times>}
commitAgain = 0
headLen = 0
sid = 1
col = 6
pointsRead = 0
pointsReadLast = 0
pCompBlock = 0x0
pCfg = 0x7f1a9516a214
chksum = 0
headInfo = {totalStorage = -11939071326}
pOldCompBlocks = 0x3ce920ce10 "r\006"
maxBytesPerPoint = 546
minBytesPerPoint = 546
tcachblocks = 0
hmsize = 51609656
dmsize = 2240000
cmsize = 2240000
tmsize = 819212
misize = 15564952
totalSize = 72473820
maxOldBlocks = 1
__PRETTY_FUNCTION__ = "vnodeCommitMultiToFile"
compInfoOffset = 60
(gdb) quit

**Comment by Shawshank-Smile** [comment]
Maybe we have discussed this phenomenon already. As you said, the TDengineon the other same machine is running well. Looking forward this show again.

**Comment by plum-lihui** [comment]
这个版本有点太老了，建议升级到最新版本再测试。
