### ISSUE TITLE
Continuous Query question

### ISSUE THREAD

**Issue by hj2252796369** [taosdata/TDengine#14097]
我想实现每年的同比分析， 使用滑动窗口怎么实现每个月的滑动？

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

**Comment by yu285** [comment]
3.x 的流计算拥有更好更完善的流计算机制，建议使用体验。
