### ISSUE TITLE
Idea references the TDengine driver JAR package will cause an error

### ISSUE THREAD

**Issue by 18555308695** [taosdata/TDengine#14108]
![7e12c6297a3a235b556a80dc4985767](https://user-images.githubusercontent.com/67681235/174954814-01be56bf-06a1-4ed2-9257-4e233142b9dd.png)

![27a545b5b3e86525dbf08c20334dfd9](https://user-images.githubusercontent.com/67681235/174954841-0580a6ae-3db2-4ba1-9929-96bf73147db2.png)

1: 引用tdengine驱动时，要同步添加额外引用。 否则无法连接。
2: git重新编译 添加额外引用

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
