### ISSUE TITLE
connect server successfully, but failed when select or insert.

### ISSUE THREAD

**Issue by arbilence** [taosdata/TDengine#14105]
1. connect server success.
2. show databases success.
3. use log success.
4. show tables success.
5. select * from restful_1;  failed.

taos -h 192.168.23.130

Welcome to the TDengine shell from Windows, Client Version:2.4.0.26
Copyright (c) 2022 by TAOS Data, Inc. All rights reserved.

taos> use log;
Query OK, 0 of 0 row(s) in database (0.001000s)

taos> show tables;
           table_name           |      created_time       | columns |          stable_name           |          uid          |     tid     |    vgId     |
==========================================================================================================================================================
 restful_1                      | 2022-06-22 11:22:57.986 |      64 | restful_info                   |       562950121200246 |          10 |           2 |
 acct_root                      | 2022-06-22 11:22:57.952 |      22 | acct                           |       562950003756674 |           3 |           2 |
 cluster_info                   | 2022-06-22 11:22:57.957 |      14 |                                |       562950037311555 |           5 |           2 |
 dnode_1                        | 2022-06-22 11:22:57.965 |      31 | dnodes_info                    |       562950054089222 |           6 |           2 |
 vgroup_2                       | 2022-06-22 11:23:27.019 |       7 | vgroups_info                   |       562950137977790 |          11 |           2 |
 dn1                            | 2022-06-22 11:22:57.949 |      15 | dn                             |       562949986979254 |           2 |           2 |
 slowquery                      | 2022-06-22 11:22:57.954 |       5 |                                |       562950020534146 |           4 |           2 |
 disks_1                        | 2022-06-22 11:22:57.973 |       7 | disks_info                     |       562950070867011 |           7 |           2 |
 log                            | 2022-06-22 11:22:57.942 |       4 |                                |       562949970201091 |           1 |           2 |
 grants_info                    | 2022-06-22 11:22:57.982 |       4 |                                |       562950104422530 |           9 |           2 |
 dnode_1_log                    | 2022-06-22 11:22:57.979 |       3 | logs                           |       562950087645046 |           8 |           2 |
Query OK, 11 row(s) in set (0.079000s)

taos> select * from restful_1;

DB error: Unable to establish connection (126.288000s)
taos>

**Comment by arbilence** [comment]
server ip changed，client hosts ip is not the right.
now it's ok.

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
