### ISSUE TITLE
fix issues found by Coverity Scan in qExecutor.c

### ISSUE THREAD

**Issue by xiaopingcs** [taosdata/TDengine#14122]
**Bug Description**
fix issues found by Coverity Scan in qExecutor.c

**To Reproduce**
N/A

**Expected Behavior**
fix following issues
| issue type                 | category                   |         file path          |         function          |     line number  |
| -------------------------- | -------------------------- | -------------------------- | -------------------------- | --------------- |
| Resource leak | Resource leaks | TDengine/src/query/src/qExecutor.c | createOrderOperatorInfo | 5945 |
| Calling risky function | Security best practices violations| TDengine/src/query/src/qExecutor.c | createProjectOperatorInfo | 7585 |
| Resource leak | Resource leaks | TDengine/src/query/src/qExecutor.c | createSLimitOperatorInfo | 8133 |
| Calling risky function | Security best practices violations | TDengine/src/query/src/qExecutor.c |createTimeEveryOperatorInfo | 7768 |
| Explicit null dereferenced | Null pointer dereferences | TDengine/src/query/src/qExecutor.c | doEveryInterpolation | 6499 |
| Dereference after null check | Null pointer dereferences | TDengine/src/query/src/qExecutor.c | doEveryInterpolation | 6591 |
| Dereference after null check | Null pointer dereferences | TDengine/src/query/src/qExecutor.c | doEveryInterpolation | 6591 |
| Dereference after null check | Null pointer dereferences | TDengine/src/query/src/qExecutor.c | doEveryInterpolation | 6525 |
| Unchecked return value | Error handling issues | TDengine/src/query/src/qExecutor.c | doInitQInfo | 5100 |

**Screenshots**
N/A

**Environment (please complete the following information):**
N/A

**Additional Context**
above issues found by https://scan.coverity.com/projects/tdengine?tab=overview

**Comment by zhihaop** [comment]
Pick up challenge @xiaopingcs.
