### ISSUE TITLE
fix issues found by Coverity Scan in qAggMain.c

### ISSUE THREAD

**Issue by xiaopingcs** [taosdata/TDengine#14121]
**Bug Description**
fix issues found by Coverity Scan in qAggMain.c

**To Reproduce**
N/A

**Expected Behavior**
fix following issues
| issue type                 | category                   |         file path          |         function          |     line number  |
| -------------------------- | -------------------------- | -------------------------- | -------------------------- | --------------- |
| Sizeof not portable | Code maintainability issues  | TDengine/src/query/src/qAggMain.c | do_bottom_function_add | 2441 |
| Sizeof not portable  | Code maintainability issues  | TDengine/src/query/src/qAggMain.c | do_bottom_function_add | 2433 |
| Calling risky function | Security best practices violations | TDengine/src/query/src/qAggMain.c | do_reservoir_sample | 5052 |
| Sizeof not portable | Code maintainability issues | TDengine/src/query/src/qAggMain.c | do_tail_function_add | 5757 |
| Sizeof not portable | Code maintainability issues | TDengine/src/query/src/qAggMain.c	| do_tail_function_add | 5752 |
| Sizeof not portable | Code maintainability issues	| TDengine/src/query/src/qAggMain.c	| do_top_function_add | 2417 |
| Sizeof not portable | Code maintainability issues	| TDengine/src/query/src/qAggMain.c	| do_top_function_add | 2409 |

**Screenshots**
N/A

**Environment (please complete the following information):**
N/A

**Additional Context**
above issues found by https://scan.coverity.com/projects/tdengine?tab=overview

**Comment by fansehep** [comment]
Please assign to me, this my pull request https://github.com/taosdata/TDengine/pull/14270
