### ISSUE TITLE
fix issues found by Coverity Scan in monMain.c 

### ISSUE THREAD

**Issue by xiaopingcs** [taosdata/TDengine#14123]
**Bug Description**
fix issues found by Coverity Scan in monMain.c 

**To Reproduce**
N/A

**Expected Behavior**
fix following issues
| issue type                 | category                   |         file path          |         function          |     line number  |
| -------------------------- | -------------------------- | -------------------------- | -------------------------- | --------------- |
| Argument cannot be negative | Error handling issues | TDengine/src/plugins/monitor/src/monMain.c | monBuildDnodeMnodeSql | Various |
| Argument cannot be negative | Error handling issues | TDengine/src/plugins/monitor/src/monMain.c | monBuildDnodeUptimeSql | 873 |
| Argument cannot be negative | Error handling issues | TDengine/src/plugins/monitor/src/monMain.c | monBuildDnodeVnodesSql | 960 |
| Argument cannot be negative | Error handling issues | TDengine/src/plugins/monitor/src/monMain.c | monBuildDnodesTotalSql | 677 |
| Argument cannot be negative | Error handling issues | TDengine/src/plugins/monitor/src/monMain.c | monBuildMasterUptimeSql | 640 |
| Argument cannot be negative | Error handling issues | TDengine/src/plugins/monitor/src/monMain.c | monBuildMnodesTotalSql | 706 |
| Argument cannot be negative | Error handling issues | TDengine/src/plugins/monitor/src/monMain.c | monGetVgroupsTotalStats | 740 |
| Argument cannot be negative | Error handling issues | TDengine/src/plugins/monitor/src/monMain.c | monGetVnodesTotalStats | 797 |
| Out-of-bounds access | Memory - corruptions | TDengine/src/plugins/monitor/src/monMain.c | monSaveDnodeLog | 1395 |
| Unintentional integer overflow | Integer handling issues | TDengine/src/plugins/monitor/src/monMain.c | monSaveDnodesInfo | 1063 |

**Screenshots**
N/A

**Environment (please complete the following information):**
N/A

**Additional Context**
N/A

**Comment by fansehep** [comment]
Please assign to me, this is my pull request. https://github.com/taosdata/TDengine/pull/14269
