### ISSUE TITLE
C++ Client is suspending when app excute taos_cleanup()

### ISSUE THREAD

**Issue by arbilence** [taosdata/TDengine#14143]
1.version: 2.6.0.4
2.connect server success.
3.Client is suspending when app excute taos_cleanup().

such as the code:
    if(m_taos) {
        taos_close(m_taos);
->        taos_cleanup();
    }
    
    return true; //not excuted

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
