### ISSUE TITLE
查询COUNT聚合统计

### ISSUE THREAD

**Issue by klxtang** [taosdata/TDengine#1417]
需统计，数据条目总数、数据条目今天总数和数据条目当月总数

SQL示例：select count(*),count(create_time > '2020-03-25 00:00:00') as today_nums from warning group by plant_code,plant_name;

SQL符合MySQL语法，不知在TDengine中，应该怎么写呢

**Comment by Shawshank-Smile** [comment]
This is still not supported. Try sql as follows for several times to replace. 
select XXX where XXX

Thank you.
