### ISSUE TITLE
探讨TDengine速度提升的原因和局限。

### ISSUE THREAD

**Issue by runzhiwang** [taosdata/TDengine#142]
调研了下，有如下一个问题。
问题： TDengine这种按设备分表的假设不知道是否一定成立？如果用户设备很少，但每个设备的数据很多，那就退化成单纯的时序数据库了，这种情况下你们测过TDengine和InfluxDB的性能对比吗？我看了下你们的测试，单表数据都只是几千条。
TDengine优化点：TDengine根据时间和设备对存储做了优化，导致读写速度快： 1.每个设备的数据是独立的，每个设备一张表，根据设备号查询不会去查其他设备的数据；2.再按时间将每个设备的大表分成小表，再将小表按时间分成块，块内数据都是按时间有序，所以可以顺序写，按时间二分查找的读以上两个原因导致TDengine在按时间、设备的查询会很快，但如果查询不是时间、设备作为筛选条件，效率也会低 。而且TDengine的这两种存储上的优化，尤其是按设备分表，并不适合其他场景，和hadoop没有可比性。初步比较TDengine和InfluxDB：InfluxDB不会将不同设备的数据分开，TDengine按设备分表是为了保证每个块内的数据都是按时间有序的。如果TDengine不按设备分表，设备A在19:00、19:01产生两条数据，设备B在19:00产生数据，因为网络延迟等，导致设备B的这条数据比设备A的两条数据晚到TDengine，则存储的数据就是：设备A19:00数据、设备A19:01数据、设备B19:00数据，无法保证按时间有序。所以TDengine假定了数据一定能按设备分表，且单表数据不多，这个假设不一定成立。

**Comment by zhangqhn** [comment]
这个观点很奇特，我是TDengine的竞争对手，也忍不住要说几句：
首先：TDengine 根据时间和设备对存储做优化， 这个是没问题的， 对于解决一个专用场景的产品，肯定会利用这个专用场景的特点。
其次：“如果查询不是时间、设备作为筛选条件，效率也会很低。”  这个就更奇葩了， 在这种场景下，时间和设备就是主键， 是索引。。。  就算在关系库中， 也会建各种索引来优化查询， 怎么你不会说：关系库也不能建索引，必须每次都查全量的数据。

但是对于写入必须是时间有序的，这一点我不是太能理解， 因为采集频率高一些的话，确实不能保证数据有序到达。看看后面会有什么优化。

评价一个产品一定要在产品的应用场景，脱离了应用场景是没有意义的。

**Comment by zhangqhn** [comment]
补充一点：InfluxDB不会将不同设备的数据分开， 就不能有其他的产品将不同的设备数据分开吗？？？
其实在内部InfluxDB也会将不同设备的数据整理存放在一起，也就是将不同设备的数据分开， 只是没有提出说每个设备必须分开建表而已。。。

**Comment by runzhiwang** [comment]
@zhangqhn  1.我没说“根据时间和设备对存储做优化”这个有问题。2.“如果查询不是时间、设备作为筛选条件，效率也会很低”这个不是事实？ 3.我说了“不能将不同的设备数据分开”？ 4.你完美的避开了我提问的问题  5.我说了TDengine提升性能的原因，而你曲解我是在说他们这样做不对。

**Comment by guotong1988** [comment]
mark

**Comment by zhangqhn** [comment]
好吧， 你说的对， 但是你提出的问题， 按设备分表的假设是否成立？ 这只是一个逻辑管理问题，只是TDengine将这种逻辑定义为表，实时数据库的概念是 标签， 其他时序数据库是Metric， 作用都是一样，叫法不同而已。所以这个也不是什么问题。。。

**Comment by runzhiwang** [comment]
@zhangqhn 我只是问按设备分表否成立，因为我也不确定，毕竟不是做物联网的，所以这是咨询大家的意见，不是反问句。

**Comment by fengshaoxie** [comment]
> @zhangqhn 我只是问按设备分表否成立，因为我也不确定，毕竟不是做物联网的，所以这是咨询大家的意见，不是反问句。

有个问题：当单个文件的大小达到10个G，不知道查询速度是否会受到影响

**Comment by zhangchi0923** [comment]
@runzhiwang 对于你前半部分的疑问，TDengine的定位就是物联网场景，而陶老师的博客中指出这种场景下的查询绝大多数都是针对某一时间段或某一组设备。作者将TDengine和Hadoop进行对比，也是在这种场景下的。通用大数据场景Hadoop还是很强的，作者也承认了这一点。后半部分时间的问题我也有同样的疑惑，时间主键是数据生成时间还是写入时间？

**Comment by runzhiwang** [comment]
@guanshengliang 请教个问题，TDengine好像没有LSM、TSM等存储引擎。现在TDengine的测试数据不大，如果数据量大了，在磁盘上找数据能保证性能吗？

**Comment by jtao1735** [comment]
TDengine的存储详细设计请大家看：https://www.taosdata.com/cn/documentation/more-on-system-architecture/#%E5%AD%98%E5%82%A8%E8%AE%BE%E8%AE%A1 我不用copy & paste了。基于我们每个设备一张表的设计，单个设备数据的写入和查询速度肯定是最好的，而且单个设备的数据量能存多大完全取决于你存储有多大。对于多个设备之间的查询，请看我们超级表的设计

**Comment by luyizhizaio** [comment]
准备测试一下
