### ISSUE TITLE
Abnormal compression ratio test: the output between two groups of data is quite different.

### ISSUE THREAD

**Issue by LLCastle** [taosdata/TDengine#1421]
**测试数据描述：**
每行包含2个监测值（浮点型和整型），总共写入1亿条数据，**创建一个超级表和一个子表**，field和tags如下：
Filed：ts(timestamp)，temperature(int)，humidity(float)
Tags：devname(binary)，devid(int)，devgroup(int)

**测试一：**
数据生成导入方法：https://github.com/taosdata/TDengine/tree/develop/tests/comparisonTest
**测试结果：源数据大小：1945.6MB；压缩后大小：645MB；**

**测试二：**
数据生成导入方法：https://github.com/taosdata/TDengine/tree/develop/importSampleData
**测试结果：源数据大小：1331.2MB；压缩后大小：25MB；**

**Comment by Shawshank-Smile** [comment]
Related to the contain of the data.

**Comment by LLCastle** [comment]
> Related to the contain of the data and the compression level.

昨天查看了一下测试2写入的数据基本都是重复数据，所以压缩比较大，重新造的随机数测试（范围在-3到3之间），压缩比在4：1左右，达不到你们宣传的10：1，你们测出的10：1是一个什么场景情况？

**Comment by Shawshank-Smile** [comment]
TDengine的是列式存储，工业数据一般每个数据都在一定范围内波动.TDengine首先取绝对差值，然后二次压缩。如果数据相似度较高，10%以内是没有问题的。高工（我们已经通过微信交流了），数据是随机的，很难压缩。可以使用同样的数据，对比其他数据库的压缩比，就知道TDengine的压缩比的厉害了。
