### ISSUE TITLE
python: double free or corruption (!prev)

### ISSUE THREAD

**Issue by 1406990759** [taosdata/TDengine#1426]
**Bug Description**
插入偶尔崩溃退出  
报错sql语句重启插入正常

**sql**
```
INSERT INTO  
 ant.worker_1d032eb3  USING  ant.ant_runtime_logs_other  TAGS ('1d032eb3', 'ERROR')  (ts, create_ts, message, ts_interval, process, lineno, levelno, pathname, exc_text) VALUES (1585194029475767, 1585169948998319, '_items', 24080477.44116211, 14, 78, 40, '/usr/local/lib/python3.7/site-packages/raven/utils/serializer/manager.py', 'Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pony/orm/dbapiprovider.py", line 52, in wrap_dbapi_exceptions
    return func(provider, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pony/orm/dbapiprovider.py", line 230, in connect
    return provider.pool.connect()
  File "/usr/local/lib/python3.7/site-packages/pony/orm/dbapiprovider.py", line 351, in connect
    pool._connect()
  File "/usr/local/lib/python3.7/site-packages/pony/orm/dbapiprovi')
```

**Screenshots**
 
![WX20200326-161132](https://user-images.githubusercontent.com/20317001/77624272-866ade80-6f7c-11ea-87d7-f37a880e080e.png)

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.5.6]

**Comment by Shawshank-Smile** [comment]
1) systemctl stop taosd
2) rm –rf /var/log/taos
3) Add one line “debugFlag 135” to the file /etc/taos/taos.cfg
4) systemctl start taosd
5)Try the problem again
6) Conpress and sent me the file in /var/log/taos
7) Thank you!
