### ISSUE TITLE
Error reporting of JDBC query  in Windows Environment

### ISSUE THREAD

**Issue by only311** [taosdata/TDengine#1427]
![image](https://user-images.githubusercontent.com/32408192/77628630-41967600-6f83-11ea-8cec-56e28ed864fd.png)
 
运行环境Windows   驱动版本1.6.5.6
查询语句出错，目前只出现过一次
select * from db.task_log  WHERE task_id='6fdc0818-6002-4d72-9261-09119ef3d424'

**Comment by Shawshank-Smile** [comment]
1) systemctl stop taosd
2) rm –rf /var/log/taos
3) Add one line “debugFlag 135” to the file /etc/taos/taos.cfg
4) systemctl start taosd
5)Try the problem again
6) Conpress and sent me the file in /var/log/taos
7) Thank you!
