### ISSUE TITLE
RPC ERROR SHELL ... reason: Broken pipe

### ISSUE THREAD

**Issue by tanqr** [taosdata/TDengine#14286]
版本： 2.6.0.4
taosd的 taosinfo.0 日志中一直在刷如下报错：
RPC ERROR SHELL  .......， failed to send, msgLen: 1443 written: -1, reason: Broken pipe

**Comment by fenghuazzm** [comment]
报这个错前有做什么操作？
日志信息少了一些，可临时改日志级别 debugflag 143 级别后看看更详细的报错信息
