### ISSUE TITLE
ERROR user:monitor, auth msg received from mnodes, error:Unable to establish connection

### ISSUE THREAD

**Issue by yangliang1111** [taosdata/TDengine#14295]
06/27 20:21:09.850056 00021218 UTL cache:stable-vgroup-list will be cleaned up
06/27 20:21:09.850123 00021218 MON ERROR failed to connect to database, reason:Unable to establish connection
06/27 20:21:10.169918 00021227 DND ERROR user:monitor, auth msg received from mnodes, error:Unable to establish connection
06/27 20:21:11.394917 00021227 DND ERROR user:monitor, auth msg received from mnodes, error:Unable to establish connection
06/27 20:21:12.619929 00021227 DND ERROR user:monitor, auth msg received from mnodes, error:Unable to establish connection
06/27 20:21:13.350092 00021218 UTL cache:stable-vgroup-list will be cleaned up
06/27 20:21:13.350210 00021218 MON ERROR failed to connect to database, reason:Unable to establish connection
06/27 20:21:13.844922 00021227 DND ERROR user:monitor, auth msg received from mnodes, error:Unable to establish connection
06/27 20:21:15.069908 00021227 DND ERROR user:monitor, auth msg received from mnodes, error:Unable to establish connection
06/27 20:21:16.294918 00021227 DND ERROR user:monitor, auth msg received from mnodes, error:Unable to establish connection
06/27 20:21:16.850086 00021218 UTL cache:stable-vgroup-list will be cleaned up
06/27 20:21:16.850174 00021218 MON ERROR failed to connect to database, reason:Unable to establish connection
06/27 20:21:17.519932 00021227 DND ERROR user:monitor, auth msg received from mnodes, error:Unable to establish connection
06/27 20:21:18.744890 00021227 DND ERROR user:monitor, auth msg received from mnodes, error:Unable to establish connection

**Comment by ora-guo** [comment]
请问下，你这个问题解决了吗？我也遇到相同问题了

**Comment by yu285** [comment]
> 请问下，你这个问题解决了吗？我也遇到相同问题了

版本号是？另外检查下服务端进程是否正常。
