### ISSUE TITLE
curl获取token问题

### ISSUE THREAD

**Issue by hwj3747** [taosdata/TDengine#143]
![1](https://user-images.githubusercontent.com/20252639/61604618-dae2ef00-ac74-11e9-99b0-44922c26e5b6.png)
如上文档上讲的获取token，但是实际操作上返回错误，求解
![2](https://user-images.githubusercontent.com/20252639/61604645-f3eba000-ac74-11e9-855e-5b638493ef6f.png)

**Comment by johnnyhou327** [comment]
Hi @hwj3747 ，pdf版本的文档是针对商业版本的，跟开源版本有些地方稍有出入。开源版本token都用base64做的，也就是basic authentication。您可以再参考下[网页版的相关文档](https://www.taosdata.com/en/documentation/connector/#RESTful-Connector)，看看是否有帮助。

**Comment by guanshengliang** [comment]
我们修改了一下开源版网页版的说明文档，您可以参考

https://www.taosdata.com/cn/documentation/connector/#RESTful-Connector

修改内容为：

使用curl来发起一个HTTP Request, 语法如下：

```
curl -H 'Authorization: Basic <TOKEN>' -d '<SQL>' <ip>:<PORT>/rest/sql
```

或者

```
curl -u username:password -d '<SQL>' <ip>:<PORT>/rest/sql
```

其中，`TOKEN`为`{username}:{password}`经过Base64编码之后的字符串，例如`root:taosdata`编码后为`cm9vdDp0YW9zZGF0YQ==`
