### ISSUE TITLE
USE the importdata tool to import data and reports an error within two hours

### ISSUE THREAD

**Issue by gaosong1206** [taosdata/TDengine#1430]
**Bug Description**
客户端版本：1.6.5.6 系统：中标麒麟高级服务版7.0
服务端版本：1.6.5.6 系统：中标麒麟高级服务版7.0
服务端硬盘1T
**To Reproduce**
1. 建库语句：
create database gaosong tables 2000 cache 6144 ablocks 4 tblocks 50;
create database luomengmeng tables 2000 cache 6144 ablocks 4 tblocks 50;
create database shishaobo tables 2000 cache 6144 ablocks 4 tblocks 50;
create database wangzhilong tables 2000 cache 6144 ablocks 4 tblocks 50;
create database lilang tables 2000 cache 6144 ablocks 4 tblocks 50;
2. 分5台电脑，其中4台电脑4核心4线程，1台6核心6线程，向5个数据库中写入数据，每个数据库建立40000张表，命令如下：
./bin/taosimport -cfg config/cfg.toml -cases camera_detection -host 192.168.30.204 -hnum 4000 -vnum 0 -thread 4 -tick 60000 -batch 300 -start "2010-12-03 00:00:00.000" -db gaosong

./bin/taosimport -cfg config/cfg.toml -cases camera_detection -host 192.168.30.204 -hnum 4000 -vnum 0 -thread 4 -tick 60000 -batch 300 -start "2010-12-03 00:00:00.000" -db luomengmeng

./bin/taosimport -cfg config/cfg.toml -cases camera_detection -host 192.168.30.204 -hnum 4000 -vnum 0 -thread 4 -tick 60000 -batch 300 -start "2010-12-03 00:00:00.000" -db shishaobo

./bin/taosimport -cfg config/cfg.toml -cases camera_detection -host 192.168.30.204 -hnum 4000 -vnum 0 -thread 4 -tick 60000 -batch 300 -start "2010-12-03 00:00:00.000" -db wangzhilong

./bin/taosimport -cfg config/cfg.toml -cases camera_detection -host 192.168.30.204 -hnum 4000 -vnum 0 -thread 6 -tick 60000 -batch 300 -start "2010-12-03 00:00:00.000" -db lilang

3. See error
**Expected Behavior**
预期平稳运行12小时，每台客户端电脑终端显示速度为20万/s左右

error：
开始运行时间21:30，在23:20左右，其中负责写入gaosong数据库的电脑报错，execute insertSql insert into t_s100_camera_dectection_200 values（xxxxxxx）
error，failed to connect to server

此时10分钟以内，其余四台电脑的写入速度下降至3000-4000r/s，有两台电脑的速度变为0

**Screenshots**

**Environment (please complete the following information):**
 - OS: 中标麒麟
 - Memory：服务端16G，6核心6线程，i5-8500，硬盘转速7200rpm，正 常运行时CPU占比>%550,内存占比40%左右
 - TDengine Version [1.6.5.6]

**Additional Context**

**Comment by Shawshank-Smile** [comment]
we have disscussed this question in wechat.

**Comment by Shawshank-Smile** [comment]
Problems in parameter setting
