### ISSUE TITLE
After using helm setup, I cannot connect when started in LoadBalancer mode

### ISSUE THREAD

**Issue by damnwenxi** [taosdata/TDengine#14356]
**General Questions**
使用 helm 安装后，升级为loadBalancer模式，修改service.type = LoadBalancer, 启动后日志报错，无法连接
![Snipaste_2022-06-29_16-59-10](https://user-images.githubusercontent.com/33170776/176397129-034b6280-aef4-4d3e-a203-99cff4baa55c.png)

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
