### ISSUE TITLE
JDBC client executeUpdate report failed, but tdengine server acturally execute success

### ISSUE THREAD

**Issue by refactor** [taosdata/TDengine#14352]
**Bug Description**

When I use JDBC JNI do executeUpdate, it report failed and an SQLException throw up, and said ' TDengine ERROR (8000000b): Unable to establish connection', but the JDBC connection still alive (checked by "select server_status()"), and tdengine server acturally execute success.

BUT, sometimes JDBC do the right job, and NO SQLException throw out, not everytime!

**To Reproduce**
Test by JUnit

**Screenshots**
![2022-06-29 16-08-20屏幕截图](https://user-images.githubusercontent.com/115570/176385593-aba0c1a3-8f25-44d2-bdd8-5ced98f84564.png)

**Environment (please complete the following information):**
 - OS: ubuntu 22.04 intel
 - Memory 64G, CPU intel x86_64
 - TDengine Version: 2.6.0.6 docker run

>  docker run -d --hostname="tdengine-server" -v /etc/taos:/etc/taos -p 6030:6030 -p 6035:6035 -p 6041:6041 -p 6030-6040:6030-6040/udp tdengine/tdengine

 -  JDBC      group: 'com.taosdata.jdbc', name: 'taos-jdbcdriver', version: '2.0.39'
 - tdengine client driver: TDengine-client-2.6.0.6-Linux-x64.tar.gz, installed by install_client.sh

**Comment by yu285** [comment]
I guess maybe network reason ,you can add " rpcForceTcp    1 " this line in the taos.cfg in your client side .

Then rerun your program .
