### ISSUE TITLE
我经过克隆之后的虚拟机连接不上了，需要怎么配置

### ISSUE THREAD

**Issue by r0pzzz** [taosdata/TDengine#14400]
[root@hadoop02 ~]# taos -h 192.168.224.120 -u root -p
Welcome to the TDengine shell from Linux, Client Version:2.6.0.4
Copyright (c) 2022 by TAOS Data, Inc. All rights reserved.

Enter password:
taos connect failed, reason: Unable to establish connection.

[root@hadoop01 ~]# taos

Welcome to the TDengine shell from Linux, Client Version:2.6.0.4
Copyright (c) 2022 by TAOS Data, Inc. All rights reserved.

taos>

**Comment by fenghuazzm** [comment]
本 issue 同 #14419 
仅维护一个，这个先关闭
