### ISSUE TITLE
taos connect failed, reason: Unable to establish connection.

### ISSUE THREAD

**Issue by r0pzzz** [taosdata/TDengine#14419]
[root@hadoop01 ~]# taos -h hadoop01

Welcome to the TDengine shell from Linux, Client Version:2.6.0.4
Copyright (c) 2022 by TAOS Data, Inc. All rights reserved.

taos connect failed, reason: Unable to establish connection.
 
/etc/taos/taos.cfg里的FQDN我也配置了 我直接输入taos可以进入，但是用taos -h就显示上面这个 这是为什么

**Comment by fenghuazzm** [comment]
指定一下端口号：-P 6030
2.6.0.4 这个版本有这个限制，后续版本已重新放回了默认值

**Comment by r0pzzz** [comment]
我还想请问一下 我下载了TDengine-client-2.6.0.6-Linux-x64.tar.gz然后解压之后运行了install_client.sh 然后出现了这个是什么原因
[root@hadoop04 ~]# systemctl start taosd
Failed to start taosd.service: Unit not found.

**Comment by fenghuazzm** [comment]
client 是客户端了，下载错了。需要安装 TDengine-server 才能启动 taosd 服务
