### ISSUE TITLE
Offline is displayed after a DNode is added

### ISSUE THREAD

**Issue by r0pzzz** [taosdata/TDengine#14422]
taos> create dnode "hadoop02:6030";
Query OK, 0 of 0 row(s) in database (0.001095s)

taos> show dnodes;
   id   |           end_point            | vnodes | cores  |   status   | role  |       create_time       |      offline reason      |
======================================================================================================================================
      1 | hadoop01:6030                  |      1 |      1 | ready      | any   | 2022-07-01 10:23:42.916 |                          |
      2 | hadoop02:6030                  |      0 |      0 | offline    | any   | 2022-07-01 12:04:15.228 | status not received      |
Query OK, 2 row(s) in set (0.000687s)

**Comment by fenghuazzm** [comment]
You're giving me too little information.
Check whether firstEp is correctly configured in the configuration file of  hadoop02-dnode .

**Comment by r0pzzz** [comment]
# first fully qualified domain name (FQDN) for TDengine system
# firstEp                   hadoop01:6030

# local fully qualified domain name (FQDN)
# fqdn                      hadoop02

**Comment by fenghuazzm** [comment]
我写篇博客专门说这个问题：
https://www.taosdata.com/engineering/12205.html
第三个问题列举了节点 offline 的原因、排查办法。
第四个问题讲了删除节点的方法：
