### ISSUE TITLE
offline reason status not received

### ISSUE THREAD

**Issue by r0pzzz** [taosdata/TDengine#14455]
taos> show dnodes;
   id   |           end_point            | vnodes | cores  |   status   | role  |       create_time       |      offline reason      |
======================================================================================================================================
      1 | hadoop01:6030                  |      1 |      1 | ready      | any   | 2022-07-01 10:23:42.916 |                          |
      5 | hadoop02:6030                  |      0 |      0 | offline    | any   | 2022-07-02 11:03:14.466 | status not received      |
Query OK, 2 row(s) in set (0.001028s)

[root@hadoop02 ~]# netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:6035            0.0.0.0:*               LISTEN      1489/taosd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      947/sshd
tcp        0      0 0.0.0.0:6040            0.0.0.0:*               LISTEN      1489/taosd
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1174/master
tcp        0      0 0.0.0.0:6030            0.0.0.0:*               LISTEN      1489/taosd
tcp6       0      0 :::22                   :::*                    LISTEN      947/sshd
tcp6       0      0 :::6041                 :::*                    LISTEN      1559/taosadapter
tcp6       0      0 ::1:25                  :::*                    LISTEN      1174/master
tcp6       0      0 :::3306                 :::*                    LISTEN      1033/mysqld

[root@hadoop02 ~]# systemctl status taosd
● taosd.service - TDengine server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: disabled)
   Active: active (running) since 六 2022-07-02 11:02:47 CST; 8min ago
  Process: 1483 ExecStartPre=/usr/local/taos/bin/startPre.sh (code=exited, status=0/SUCCESS)
 Main PID: 1489 (taosd)
   CGroup: /system.slice/taosd.service
           └─1489 /usr/bin/taosd

7月 02 11:02:47 hadoop02 systemd[1]: Starting TDengine server service...
7月 02 11:02:47 hadoop02 systemd[1]: Started TDengine server service.
7月 02 11:02:47 hadoop02 TDengine:[1489]: Starting TDengine service...
7月 02 11:02:47 hadoop02 TDengine:[1489]: Started TDengine service successfully.

# first fully qualified domain name (FQDN) for TDengine system
# firstEp                   hadoop01:6030

# local fully qualified domain name (FQDN)
# fqdn                      hadoop02

# first port number for the connection (12 continuous UDP/TCP port number are used)
# serverPort                6030

**Comment by fenghuazzm** [comment]
https://www.taosdata.com/engineering/12205.html
请看其中第三个问题：集群扩容后，DNode 状态为 Offline 该如何排查？

**Comment by r0pzzz** [comment]
我都排查了一遍重新添加还是offline

**Comment by KevinRecovery** [comment]
> https://www.taosdata.com/engineering/12205.html 请看其中第三个问题：集群扩容后，DNode 状态为 Offline 该如何排查？

请问一下，新节点的data文件一定要删除吗？如果我已有的旧节点是修改过密码的，那么新节点删除data后，启动会报“Authentication failure”错误
