### ISSUE TITLE
When Taosdump is running, too many database connections occur, causing the connection failure

### ISSUE THREAD

**Issue by hufeng-tany** [taosdata/TDengine#14481]
**Bug Description**
执行taosdump时，出现连接数过多的问题
执行的dump命令：
taosdump -h127.0.0.1 -uroot -ptaosdata -P6030 -r /home/TDengine/databk/backup_result.txt -o/home/TDengine/databk/ -D hzinfo_data -T 16 -S ‘2022-03-01 00:00:00.000’ -E ‘2022-06-22 00:00:00.000’ -t 1000 -B 100

taosdump返回异常:
ERROR: Failed to connect to TDengine server 127.0.0.1 by specified database hzinfo_data

show connections;返回行数：27953 row(s) +
       28996 | root                     | taosdump                 |     1068037 | 127.0.0.1:56101        | 2022-07-04 09:49:45.804 | 2022-07-04 09:49:45.804 |
       28997 | root                     | taosdump                 |     1068037 | 127.0.0.1:51902        | 2022-07-04 09:49:45.804 | 2022-07-04 09:49:45.804 |
Query OK, 27953 row(s) in set (4.091677s)

如何解决链接数过多的问题！！！

taos版本2.2.0.5

**Comment by fenghuazzm** [comment]
maxShellConns、maxConnections 参数调大一些

**Comment by fenghuazzm** [comment]
这个 taosdump 是老版本 TDengine 自带的吗？
推荐 TDengine 升下级，并用新版 taos-tool 里面的 taosdump

**Comment by hufeng-tany** [comment]
你好！你的邮件我已经收到，我会尽快查看
胡峰

**Comment by hufeng-tany** [comment]
> 这个 taosdump 是老版本 TDengine 自带的吗？ 推荐 TDengine 升下级，并用新版 taos-tool 里面的 taosdump

是2.2.0.5版本带的taosdump，可以单独升级taosdump吗？现在已经部署在生产环境中，不方便升级涛思服务端；

链接过多的事情，主要出现在：taosdump时，dump这段时间内没数据时，就会疯狂占用链接数。
我也改大过，但是没效果，只要dump线程数，稍微多一点，链接数就是暴涨上千倍，很容易占满链接数。

**Comment by fenghuazzm** [comment]
可以安装 taos-tools，但这个版本好像只能导出不能导入了（导出还有带上参数 -L）。
因为导出导入的逻辑变化了，旧版本 taosdump 导入导出好像全部还是用的 sql，新版本都是 avro 格式了。实在不行只能 taosdump 的时候 -T 给少点儿线程数试试吧。

**Comment by hufeng-tany** [comment]
你好！你的邮件我已经收到，我会尽快查看
胡峰
