### ISSUE TITLE
A question about AGPL

### ISSUE THREAD

**Issue by shiritoshiro** [taosdata/TDengine#14480]
我注意到TDEngine使用的开源协议是AGPLV3,这是否意味着只要不修改TDEngine程序源码，只是给其他程序提供服务是不违反AGPLV3协议的？

**Comment by fenghuazzm** [comment]
这个挺复杂的，详情可找陈工交流下，他 Wechat：a15652223354

**Comment by jasongwq** [comment]
这个issues会决定我们是否能选用TDengine
如果选用TDengine会将AGPL传染整个通过网络交互的端到端解决方案的话这个是难以接受的

**Comment by yu285** [comment]
![image](https://github.com/taosdata/TDengine/assets/74105241/837ad6a4-9123-4484-8551-f801ad99f091)

**Comment by yu285** [comment]
自用可以，我们不支持商用项目
