### ISSUE TITLE
If multiple SQL statements are executed consecutively to delete multiple columns, only the first statement is executed.

### ISSUE THREAD

**Issue by SheaHong** [taosdata/TDengine#14484]
如：ALTER STABLE table.stable1 DROP COLUMN `column1` ; ALTER STABLE table.stable1 DROP COLUMN `column2` ; 只有column1被删除。我想要两列都删除或新增该如何处理

**Comment by fenghuazzm** [comment]
ALTER STABLE table.stable1 DROP COLUMN column;
我试着能多次删除、添加
删除的话是不是删的只剩时间戳字段了？最起码需要保留一个额外的普通字段

**Comment by SheaHong** [comment]
@fenghuazzm 如果没有额外列我记得会直接报错，我这种写法是只会执行第一条。用的是这种写法批量操作
    <insert id="insertColumnBatch" parameterType="base.pojo.vo.TDengineBatchVo">
        <foreach collection="list" item="tDengineBatchVo" separator=";" >
            ALTER STABLE  ${tDengineBatchVo.dbName}.${tDengineBatchVo.superTableName}
            <foreach collection="tDengineBatchVo.fields.entrySet()" index="key" item="value">
                ADD COLUMN `${key}` #{value}
            </foreach>
        </foreach>
    </insert>

**Comment by fenghuazzm** [comment]
![image](https://user-images.githubusercontent.com/70138133/177101295-82882a25-80ed-4f78-a2fe-88e9b246f249.png)
shell 上我试着可以呢，看看 foreach 拼出来的 sql 有没有问题吧

**Comment by SheaHong** [comment]
代码输出的sql放在shell上执行也是OK的。我再想想。
![image](https://user-images.githubusercontent.com/18188783/177107108-d8d6b52a-7032-4c25-8900-d477b0d0b266.png)
![image](https://user-images.githubusercontent.com/18188783/177107427-1567d59c-48fb-4051-a00c-cd8f91f612ca.png)

**Comment by SheaHong** [comment]
@fenghuazzm 请问一下TDEngine的连接有类似mysql allowMultiQueries功能的参数吗

**Comment by fenghuazzm** [comment]
好像是没有 allowMultiQueries 这类的参数去同时执行多条 SQL ，不过有 sql 语法支持批量（batch）写入

**Comment by fenghuazzm** [comment]
暂时还不支持同时增、删多个字段

**Comment by SheaHong** [comment]
好的谢谢。在代码中使用for循环删除多列。
