### ISSUE TITLE
When adding columns to the table, the TDengine.StmtExecute error says Need to reconfigure table

### ISSUE THREAD

**Issue by theflash1264** [taosdata/TDengine#14496]
问题描述
数据库表增加一列后 使用TDengine.StmtExecute(stmt)提示错误为Need to reconfigure table
添加列之前没有错误，命令写入数据没有错误
代码如下
stmt = TDengine.StmtInit(conn);
TDengine.StmtPrepare(stmt, "INSERT INTO ? USING sswater TAGS(?) (" + bvalues + ") VALUES (" + vvalues + ")");
                                                    
                                                    CheckStmtRes(res, "2、failed to prepare stmt", DC);
                                                    TAOS_BIND[] tags = new TAOS_BIND[1] { TaosBind.BindNchar(mn) };
                                                    res = TDengine.StmtSetTbnameTags(stmt, "sswater_" + mn.Trim() + "", tags);
                                                    DateTime timeStampStartTime = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);

                                                    TAOS_MULTI_BIND[] mBinds = new TAOS_MULTI_BIND[oldyzv.Count];
                                                    mBinds[0] = TaosMultiBind.MultiBindTimestamp(new long[1] { (long)(Convert.ToDateTime(AstrArray[0]).ToUniversalTime() - timeStampStartTime).TotalMilliseconds });

                                                    mBinds[1] = TaosMultiBind.MultiBindNchar(new string[1] { AstrArray[1] });

                                                    mBinds[2] = TaosMultiBind.MultiBindTimestamp(new long[1] { (long)(Convert.ToDateTime(AstrArray[2]).ToUniversalTime() - timeStampStartTime).TotalMilliseconds });
                                                    mBinds[3] = TaosMultiBind.MultiBindTimestamp(new long[1] { (long)(Convert.ToDateTime(AstrArray[3]).ToUniversalTime() - timeStampStartTime).TotalMilliseconds });
                                                    res = TDengine.StmtBindParamBatch(stmt, mBinds);
                                                    CheckStmtRes(res, "failed to bind params", DC);
                                                    res = TDengine.StmtAddBatch(stmt);
                                                    CheckStmtRes(res, "failed to add batch", DC);
                                                    res = TDengine.StmtExecute(stmt);
                                                    CheckStmtRes(res, "faild to execute", DC);
                                                    TDengine.StmtClose(stmt);

**Comment by fenghuazzm** [comment]
StmtPrepare 里面 sql 绑定的列最好是固定的。
stmt 这方面是有些限制，若表结构做了更改，可以试试先手动写入一条数据，再执行 StmtExecute 方法。

**Comment by fenghuazzm** [comment]
我和负责这块的同学交流了下，因为涉及参数绑定的实现，暂时确实没有更好的解决办法了。
后续重构会加以考虑的

**Comment by theflash1264** [comment]
> 



> 我和负责这块的同学交流了下，因为涉及参数绑定的实现，暂时确实没有更好的解决办法了。 后续重构会加以考虑的

好的，我先按这个方法尝试解决吧，谢谢。
