### ISSUE TITLE
RESTful 连接方式密码特殊字符转义问题

### ISSUE THREAD

**Issue by ouzujie** [taosdata/TDengine#14539]
**错误描述**
 REST 这种方式如果密码带有斜杠是导致连接不上

**复制**
重现行为的步骤：
## maven
```
       <dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>2.0.39</version>
        </dependency>
```
## java RESTful 方式连接代码
```
 public static void main(String[] args) throws SQLException {
        String jdbcUrl = "jdbc:TAOS-RS://localhost:6041/log?user=root&password=Abc123///";
        Connection conn = DriverManager.getConnection(jdbcUrl);
        System.out.println("Connected");
        conn.close();
    }
```

**环境：**
   - 操作系统：[CentOS 7.0]
   - TDengine 版本 2.4.0.5 以上

**Comment by ouzujie** [comment]
> **错误描述** REST 这种方式如果密码带有斜杠是导致连接不上
> 
> **复制** 重现行为的步骤：
> 
> ## maven
> ```
>        <dependency>
>             <groupId>com.taosdata.jdbc</groupId>
>             <artifactId>taos-jdbcdriver</artifactId>
>             <version>2.0.39</version>
>         </dependency>
> ```
> 
> ## java RESTful 方式连接代码
> ```
>  public static void main(String[] args) throws SQLException {
>         String jdbcUrl = "jdbc:TAOS-RS://localhost:6041/log?user=root&password=Abc123///";
>         Connection conn = DriverManager.getConnection(jdbcUrl);
>         System.out.println("Connected");
>         conn.close();
>     }
> ```
> 
> **环境：**
> 
> * 操作系统：[CentOS 7.0]
> * TDengine 版本 2.4.0.5 以上

# 看到官方文档了
https://docs.taosdata.com/taos-sql/escape

**Comment by fenghuazzm** [comment]
嗯嗯，/ 要转义
