### ISSUE TITLE
DB error: Out of DNodes, when insert

### ISSUE THREAD

**Issue by Sunrise6** [taosdata/TDengine#14544]
版本：2.4.0.18
安装默认，一个实例，非集群
INSERT INTO 
	d1544135900612411398 USING HisData TAGS('00392207013495') VALUES(1657014627000,'1544135900612411398',1656985829000,1657016196357,0.06)；
DB error: Out of DNodes (0.053000s)

taos> SHOW VARIABLES;
           name           |             value              |
============================================================
 walFlushSize             | 1024                           |
 smlTagNullName           | _tag_null                      |
 smlChildTableName        |                                |
 defaultJSONStrType       | nchar                          |
 clientMerge              | 0                              |
 deadLockKillQuery        | 1                              |
 version                  | 2.4.0.18                       |
 buildinfo                | Built at 2022-04-26 19:47      |
 gitinfoOfInternal        | NULL                           |
 gitinfo                  | e63e64a877526843859898d098f... |
 httpDbNameMandatory      | 0                              |
 telegrafUseFieldNum      | 0                              |
 topicBinaryLen           | 16000                          |
 stream                   | 1                              |
 monitor                  | 1                              |
 mqtt                     | 0                              |
 http                     | 1                              |
 adjustMaster             | 1                              |
 slaveQuery               | 1                              |
 flowctrl                 | 1                              |
 mnodeEqualVnodeNum       | 4                              |
 minimalDataDirGB         | 2.000000                       |
 minimalTmpDirGB          | 1.000000                       |
 minimalLogDirGB          | 1.000000                       |
 maxConnections           | 5000                           |
 maxShellConns            | 50000                          |
 charset                  | UTF-8                          |
 locale                   | zh_CN.UTF-8                    |
 timezone                 | Asia/Shanghai (CST, +0800)     |
 keepColumnName           | 1                              |
 retrieveBlockingModel    | 0                              |
 queryBufferSize          | -1                             |
 maxNumOfOrderedRes       | 1000000                        |
 maxRegexStringLen        | 128                            |
 maxWildCardsLength       | 100                            |
 maxSQLLength             | 1048576                        |
 compressColData          | -1                             |
 compressMsgSize          | 524288                         |
 cachelast                | 0                              |
 update                   | 0                              |
 quorum                   | 1                              |
 partitions               | 4                              |
 replica                  | 1                              |
 fsync                    | 3000                           |
 walLevel                 | 1                              |
 comp                     | 2                              |
 precision                | 0                              |
 maxRows                  | 4096                           |
 minRows                  | 100                            |
 keep                     | 3650                           |
 days                     | 10                             |
 blocks                   | 6                              |
 cache                    | 16                             |
 tableIncStepPerVnode     | 1000                           |
 minTablesPerVnode        | 1000                           |
 maxTablesPerVnode        | 1000000                        |
 maxVgroupsPerDb          | 0                              |
 streamCompDelayRatio     | 0.100000                       |
 retryStreamCompDelay     | 10000                          |
 maxFirstStreamCompDela   | 10000                          |
 maxStreamCompDelay       | 20000                          |
 minIntervalTime          | 1                              |
 minSlidingTime           | 10                             |
 statusInterval           | 1                              |
 offlineThreshold         | 864000                         |
 monitorReplica           | 1                              |
 maxTmrCtrl               | 512                            |
 keepTimeOffset           | 0                              |
 offlineInterval          | 3                              |
 balanceInterval          | 300                            |
 balance                  | 0                              |
 syncCheckInterval        | 1500                           |
 tcpConnTimeout           | 1000                           |
 telemetryReporting       | 1                              |
 vnodeBak                 | 1                              |
 numOfMnodes              | 1                              |
 maxNumOfDistinctRes      | 10000000                       |
 arbitrator               |                                |

**Comment by fenghuazzm** [comment]
Out of DNodes 这个错是指没有资源创建 vnode 了，需要添加节点。
目前是将数据都写在一个库里面、并且很多表吗？
maxVgroupsPerDb 设置为 0 默认是不允许产生超过 CPU 核数的 vnode，可以调为大于 CPU 核数试试。

**Comment by Sunrise6** [comment]
非常感谢，确实如此！
