### ISSUE TITLE
The taosadapter service is started, but cannot be accessed remotely

### ISSUE THREAD

**Issue by miaoyinjun** [taosdata/TDengine#14601]
版本：2.6.0.6
本地可以访问，远程不能访问，已排除防火墙和安全组问题

<img width="736" alt="image" src="https://user-images.githubusercontent.com/5077893/177503700-ba0c94db-408a-4d00-8660-a82568449854.png">

**Comment by fenghuazzm** [comment]
“远程不能访问”是指 curl 不了 localhost 吗？
从图看着 url 不对，并且没带账号密码、body。 
eg：
curl -L -u root:taosdata -d "show databases"  http://localhost:6041/rest/sql

**Comment by miaoyinjun** [comment]
没有问题了，是我参数的问题，谢谢
curl -L -u root:taosdata -d "show databases" http://外网IP:6041/rest/sql
