### ISSUE TITLE
Spark and TDengine perform statistical analysis, but the returned data is incomplete.

### ISSUE THREAD

**Issue by clcl2** [taosdata/TDengine#14638]
问题描述：
使用spark&tdengine对数据进行分析，为减少计算基数，使用嵌套查询先筛选数据，然后利用spark分区（900分区）计算。
<img width="929" alt="c7b32d037b3687d9431420906821f578_17108" src="https://user-images.githubusercontent.com/41424119/177690721-5cc9276a-db30-40f0-9fa8-8a60852b7edf.png">
如图，pos_time为首行时间戳，嵌套筛选条件为tag字段，单次查询耗时35s。共230546子表，每张表约6W数据。
且最终spark取出数据不完整，仅有总数据1/60的数据

**Comment by clcl2** [comment]
使用版本2.4.0.18
taosdata driver包为：taos-jdbcdriver-2.0.38.jar

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
