### ISSUE TITLE
Fastjson usage suggestions

### ISSUE THREAD

**Issue by melvin7** [taosdata/TDengine#14644]
fastjson 漏洞频发，其性能也不是最优，建议替换掉jdbcdriver中fastjson库的使用。
目前我们CI流程中遇到fastjson会直接打回，只能使用JNI模式来使用。

**Comment by fenghuazzm** [comment]
嗯嗯，后续会考虑替换掉 fastjson 依赖。目前可先不用 JDBC RESTful 。
