### ISSUE TITLE
parsing conflicts exist in sql.y in 3.0 branch

### ISSUE THREAD

**Issue by freemine** [taosdata/TDengine#14650]
**Bug Description**
There 2 parsing conflicts if we compile sql.y with `lemon`, which's believed to be the corresponding sql-parser-generator used internally by TDengine, though it's not included in the source base.

**To Reproduce**
1. lemon -d/tmp/ source/libs/parsers/inc/sql.y

**Expected Behavior**
A working-and-correct grammar (no matter it's SQL or any other `language`) shall not generate parsing conflict, otherwise,
it'll result in non-deterministic-or-correct result during run-time because of ambiguities therein.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Linux xxh-VirtualBox 5.13.0-51-generic #58~20.04.1-Ubuntu SMP Tue Jun 14 11:29:12 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux; Ubuntu 20.04 LTS]
 - Memory, CPU, current Disk Space
 - TDengine Version [3.0, git commit 886af82c57e481378ad8161ddd1e2fb73c44032b]
 - lemon: (lemon -x): Lemon version 1.0

**Additional Context**
If you check the detail in /tmp/sql.out, you'll probablly find something like this:
```
State 164:
    (133) specific_cols_opt ::= * 
          specific_cols_opt ::= * NK_LP col_name_list NK_RP 
          cmd ::= INSERT INTO full_table_name * specific_cols_opt query_expression

                         NK_LP shift        80     
                         NK_LP reduce       133     ** Parsing conflict **                                                             
             specific_cols_opt shift        53     
                     {default} reduce       133    specific_cols_opt ::=
```
and
```
State 564:
    (458) query_expression ::= query_expression_body order_by_clause_opt slimit_clause_opt limit_clause_opt *
          query_primary ::= NK_LP query_expression_body order_by_clause_opt slimit_clause_opt limit_clause_opt * NK_RP
          
                         NK_RP shift-reduce 463    query_primary ::= NK_LP query_expression_body order_by_clause_opt slimit_clause_opt limit_clause_opt NK_RP   
                         NK_RP reduce       458     ** Parsing conflict **                                                             
```

It's believed that the parsing conflicts root in `query_expression rule-set'.

**Comment by xiao-yu-wang** [comment]
The purpose of this rule is to hopefully implement the syntax:
**(SELECT * FROM foo ORDER BY c1 LIMIT 1) UNION ALL (SELECT * FROM foo ORDER BY c1 LIMIT 1)**
order_by_clause_opt/slimit_clause_opt/limit_clause_opt should be used, it was a bug before.
**query_primary ::= NK_LP query_expression NK_RP** or **query_primary ::= subquery** does not eliminate the conflict.
This problem has really been bothering me, hope to get your advice.

**Comment by freemine** [comment]
please check this attached syntax file where
1. redefine NK_COMMA related rules to left-recursion ones
2. remove subquery rule in expression and related. (please check thoroughly)
3. redefine query_primary rule to: query_primary ::= NL_LP query_expression NL_RP

after refactoring as above, ./lemon parser generator is satisifed with no warnings.

attentions:
action code related to above modified/created rules are either removed or meaningless, you'd better do some modification if you think the syntax is basically right.


BTW, which lemon version does this project use?
[sql.y.txt](https://github.com/taosdata/TDengine/files/9492787/sql.y.txt)

**Comment by xiao-yu-wang** [comment]
thank you very much! This modification does indeed eliminate the warning. But there is one more problem.
The rule expression ::= subquery is reserved because subqueries in expressions may be supported in the future. Is there any better way to modify it so that this rule can be preserved.

**Comment by freemine** [comment]
do you mean something like:
select (select 'a') as item, * from t

**Comment by freemine** [comment]
```
rule:  831 table_primary(A) ::= subquery(B) alias_opt(C).  
eg.: select * from (select * from b) as foo;
this is OK as usual
```
but
```
rule: 632 expression(A) ::= subquery(B). 
rule: 638 expression(A) ::= NK_MINUS(B) expression(C).
rule: 642 expression(A) ::= expression(B) NK_PLUS expression(C).
```
do you mean, users are encouraged to write a sql statement like:
```
select ((select 1) - (select 2)) as val from t
```
because according to the rule 632 ~ 642, this is valid syntax, but does it make sense?

**Comment by freemine** [comment]
https://docs.oracle.com/cd/B28359_01/server.111/b28286/expressions001.htm#SQLRF52045

how `expressions` are used in SQL, may it be helpful

**Comment by xiao-yu-wang** [comment]
Scalar subqueries do not make much sense when used directly in expressions, but if they are correlated subqueries, they make a lot of sense. Although we are still far from supporting correlated subqueries, I hope to cover the grammar rules first.

**Comment by xiao-yu-wang** [comment]
for the following statement:
SELECT c1, c2 FROM t1 UNION ALL SELECT c1, c2 FROM t1 ORDER BY c1
With your modification above, the ORDER BY clause will be recognized as part of the second SELECT statement. This is not what we want, it should be the clause after UNION ALL.

**Comment by xiao-yu-wang** [comment]
The version of lemon we are using is 1.0.

**Comment by freemine** [comment]
what about this:
```
query_expression ::= query_simple order_by_clause_opt slimit_clause_opt limit_clause_opt.
query_simple ::= query_specification. 
query_simple ::= union_query_expression.                                                                                                                                        
union_query_expression ::= query_simple_or_subquery UNION query_simple_or_subquery.
union_query_expression ::= query_simple_or_subquery UNION ALL query_simple_or_subquery.

query_simple_or_subquery ::= query_simple.
query_simple_or_subquery ::= subquery.

query_or_subquery ::= query_expression.
query_or_subquery ::= subquery.
```

**Comment by xiao-yu-wang** [comment]
query_or_subquery is not used, is there a typo?

**Comment by freemine** [comment]
cmd ::= query_or_subquery.

**Comment by freemine** [comment]
just submit another PR.
this seems all done, such as:
```
1. select * from t union all select * from t order by ...
2. select * from t union all (select * from t order by ...)
3. select * from t where v > (select avg(v) from t)
...
```
please check and review.

**Comment by xiao-yu-wang** [comment]
The conflict is indeed resolved! thank you very much! I submit a PR to see if it can pass the CI test.
https://github.com/taosdata/TDengine/pull/16891

**Comment by freemine** [comment]
happy to see it merged.

**Comment by xiao-yu-wang** [comment]
thank you very much!
