### ISSUE TITLE
taosAdapter cannot connect to TDengine directly

### ISSUE THREAD

**Issue by tcy110** [taosdata/TDengine#14669]
将adapter与tdengine拆分开独立在k8s中部署，adapter中配置的FQDN已经成功解析为tdengine的svc ip，其中tdengine启动也正常，网络策略也没有开启，但是adapter一直提示无法连接tdengine。

07/08 10:26:09.254096 00000001 TAOS_ADAPTER error "write to TDengine error" model=monitor error=[0xb] Unable to establish connection
07/08 10:26:39.249082 00000001 TAOS_ADAPTER error "write to TDengine error" model=monitor error=[0xb] Unable to establish connection
07/08 10:27:09.249030 00000001 TAOS_ADAPTER error "write to TDengine error" model=monitor error=[0xb] Unable to establish connection
07/08 10:27:39.214297 00000001 TAOS_ADAPTER error "write to TDengine error" model=monitor error=[0xb] Unable to establish connection
07/08 10:28:09.254049 00000001 TAOS_ADAPTER error "write to TDengine error" model=monitor error=[0xb] Unable to establish connection
07/08 10:28:39.254093 00000001 TAOS_ADAPTER error "write to TDengine error" error=[0xb] Unable to establish connection model=monitor
07/08 10:29:09.249041 00000001 TAOS_ADAPTER error "write to TDengine error" model=monitor error=[0xb] Unable to establish connection
07/08 10:29:39.249278 00000001 TAOS_ADAPTER error "write to TDengine error" model=monitor error=[0xb] Unable to establish connection
07/08 10:30:09.214050 00000001 TAOS_ADAPTER error "write to TDengine error" model=monitor error=[0xb] Unable to establish connection

**Comment by tcy110** [comment]
> 可以在 taosadapter 那个容器尝试使用 taos 连接 taosd，如果也是同样错误，请参考 FAQ 相关章节

taosadapter 容器可以使用taos连接taosd，我adapter容器是根据官方文档增加了变量

**Comment by tcy110** [comment]
> 可以在 taosadapter 那个容器尝试使用 taos 连接 taosd，如果也是同样错误，请参考 FAQ 相关章节

taosadapter 容器可以使用taos连接taosd，我adapter容器是根据官方文档增加了变量

**Comment by tcy110** [comment]
> 可以在 taosadapter 那个容器尝试使用 taos 连接 taosd，如果也是同样错误，请参考 FAQ 相关章节

这个是我的配置：     
      containers:
      - name: "adapter"
        image: tdengine/tdengine:2.6.0.6
        imagePullPolicy: "Always"
        args:
        - --debug=true
        - --logLevel=debug
        command: ["taosadapter"]
        env:
        - name: TAOS_FIRST_EP
          value: tdengine-0.taosd.monitoring.svc.cluster.local:6030
        - name: TZ
          value: "Asia/Shanghai"
        - name: TAOS_DEBUG_FLAG
          value: "135"

**Comment by tcy110** [comment]
> 可以在 taosadapter 那个容器尝试使用 taos 连接 taosd，如果也是同样错误，请参考 FAQ 相关章节

代码这块只指定了用户名和密码？默认连接本地？
![image](https://user-images.githubusercontent.com/67218828/177911523-71f852cd-48a8-4ebe-a893-4096f1c1e589.png)

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
