### ISSUE TITLE
openEuler 22.03 LTS Can not run taosd

### ISSUE THREAD

**Issue by waittingsummer** [taosdata/TDengine#14667]
测试版本
TDengine-server-2.4.0.7-MyLinux-x64.tar.gz
TDengine-server-2.4.0.12-MyLinux-x64.tar.gz
TDengine-server-2.6.0.6-Linux-x64.tar.gz

日志：
[root@openEulerA1 opt]# systemctl status   taosd
× taosd.service - TDengine server service
     Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Thu 2022-07-07 15:35:56 CST; 3s ago
    Process: 1345608 ExecStartPre=/usr/local/taos/bin/startPre.sh (code=exited, status=0/SUCCESS)
    Process: 1345614 ExecStart=/usr/bin/taosd (code=exited, status=255/EXCEPTION)
   Main PID: 1345614 (code=exited, status=255/EXCEPTION)

7月 07 15:35:56 openEulerA1 systemd[1]: taosd.service: Main process exited, code=exited, status=255/EXCEPTION
7月 07 15:35:56 openEulerA1 systemd[1]: taosd.service: Failed with result 'exit-code'.
7月 07 15:35:56 openEulerA1 systemd[1]: taosd.service: Scheduled restart job, restart counter is at 3.
7月 07 15:35:56 openEulerA1 systemd[1]: Stopped TDengine server service.
7月 07 15:35:56 openEulerA1 systemd[1]: taosd.service: Start request repeated too quickly.
7月 07 15:35:56 openEulerA1 systemd[1]: taosd.service: Failed with result 'exit-code'.
7月 07 15:35:56 openEulerA1 systemd[1]: Failed to start TDengine server service.

手动运行记录：
[root@openEulerA4 home]# cd /usr/local/taos/bin
[root@openEulerA4 bin]# ll
总用量 48M
-r-xr-xr-x. 1 root root 7.1K  7月  7 14:28 remove.sh
-r-xr-xr-x. 1 root root  939  7月  7 14:28 set_core.sh
-r-xr-xr-x. 1 root root 1.3K  7月  7 14:28 startPre.sh
-r-xr-xr-x. 1 root root 675K  7月  7 14:28 taos
-r-xr-xr-x. 1 root root  11M  7月  7 14:28 taosadapter
-r-xr-xr-x. 1 root root 1.6M  7月  7 14:28 taosBenchmark
-r-xr-xr-x. 1 root root 2.4M  7月  7 14:28 taosd
-r-xr-xr-x. 1 root root 2.9K  7月  7 14:28 taosd-dump-cfg.gdb
-r-xr-xr-x. 1 root root 1.5M  7月  7 14:28 taosdump
-r-xr-xr-x. 1 root root 1.7M  7月  7 14:28 tarbitrator
-r-xr-xr-x. 1 root root  30M  7月  7 14:28 tdengine-datasource-3.2.5.zip
-r-xr-xr-x. 1 root root 151K  7月  7 14:28 TDinsight-15167.json
-r-xr-xr-x. 1 root root  17K  7月  7 14:28 TDinsight.sh
[root@openEulerA4 bin]# 
[root@openEulerA4 bin]# 
[root@openEulerA4 bin]# 
[root@openEulerA4 bin]# ./taosd
07/08 10:35:59.329895 01364867 DND start to initialize TDengine
07/08 10:35:59.331233 01364867 DND step:dnode-tfile is initialized
07/08 10:35:59.331280 01364867 DND step:dnode-rpc is initialized
07/08 10:35:59.392008 01364867 UTL localEp is: openEulerA4:6030
07/08 10:35:59.393183 01364867 UTL WARN timezone not configured, set to system default: (CST, +0800)
07/08 10:35:59.393329 01364867 UTL WARN locale not configured, set to system default:zh_CN.UTF-8
07/08 10:35:59.393348 01364867 UTL WARN charset not configured, set to system default:UTF-8
07/08 10:35:59.393361 01364867 UTL    check global cfg completed
07/08 10:35:59.393366 01364867 UTL ==================================
07/08 10:35:59.393370 01364867 UTL    taos config & system info:
07/08 10:35:59.393375 01364867 UTL ==================================
07/08 10:35:59.393378 01364867 UTL  firstEp:                openEulerA4:6030 
07/08 10:35:59.393382 01364867 UTL  secondEp:               openEulerA4:6030 
07/08 10:35:59.393397 01364867 UTL  fqdn:                   openEulerA4 
07/08 10:35:59.393401 01364867 UTL  serverPort:             6030 
07/08 10:35:59.393404 01364867 UTL  configDir:              /etc/taos 
07/08 10:35:59.393408 01364867 UTL  logDir:                 /var/log/taos 
07/08 10:35:59.393412 01364867 UTL  scriptDir:              /etc/taos 
07/08 10:35:59.393415 01364867 UTL  arbitrator:              
07/08 10:35:59.393419 01364867 UTL  numOfThreadsPerCore:    1.000000 
07/08 10:35:59.393424 01364867 UTL  numOfCommitThreads:     4 
07/08 10:35:59.393428 01364867 UTL  ratioOfQueryCores:      1.000000 
07/08 10:35:59.393431 01364867 UTL  maxNumOfDistinctRes:    10000000 
07/08 10:35:59.393435 01364867 UTL  numOfMnodes:            1 
07/08 10:35:59.393438 01364867 UTL  vnodeBak:               1 
07/08 10:35:59.393442 01364867 UTL  telemetryReporting:     1 
07/08 10:35:59.393445 01364867 UTL  dnodeNopLoop:           0 
07/08 10:35:59.393448 01364867 UTL  tcpConnTimout:          1000(ms)
07/08 10:35:59.393452 01364867 UTL  syncCheckInterval:      1500(ms)
07/08 10:35:59.393455 01364867 UTL  balance:                1 
07/08 10:35:59.393458 01364867 UTL  balanceInterval:        300 
07/08 10:35:59.393462 01364867 UTL  offlineInterval:        3 
07/08 10:35:59.393466 01364867 UTL  keepTimeOffset:         0 
07/08 10:35:59.393469 01364867 UTL  role:                   0 
07/08 10:35:59.393472 01364867 UTL  maxTmrCtrl:             512 
07/08 10:35:59.393476 01364867 UTL  monitorInterval:        30(s)
07/08 10:35:59.393480 01364867 UTL  monitorReplica:         1 
07/08 10:35:59.393483 01364867 UTL  offlineThreshold:       864000(s)
07/08 10:35:59.393487 01364867 UTL  rpcTimer:               300(ms)
07/08 10:35:59.393491 01364867 UTL  rpcMaxTime:             600(s)
07/08 10:35:59.393494 01364867 UTL  rpcForceTcp:            0 
07/08 10:35:59.393497 01364867 UTL  statusInterval:         1(s)
07/08 10:35:59.393501 01364867 UTL  shellActivityTimer:     3(s)
07/08 10:35:59.393505 01364867 UTL  minSlidingTime:         10(ms)
07/08 10:35:59.393508 01364867 UTL  minIntervalTime:        1(ms)
07/08 10:35:59.393512 01364867 UTL  maxStreamCompDelay:     20000(ms)
07/08 10:35:59.393515 01364867 UTL  maxFirstStreamCompDelay:10000(ms)
07/08 10:35:59.393518 01364867 UTL  retryStreamCompDelay:   1800000(ms)
07/08 10:35:59.393522 01364867 UTL  streamCompDelayRatio:   0.100000 
07/08 10:35:59.393527 01364867 UTL  maxVgroupsPerDb:        0 
07/08 10:35:59.393530 01364867 UTL  maxTablesPerVnode:      1000000 
07/08 10:35:59.393533 01364867 UTL  minTablesPerVnode:      1000 
07/08 10:35:59.393537 01364867 UTL  tableIncStepPerVnode:   1000 
07/08 10:35:59.393542 01364867 UTL  cache:                  16(Mb)
07/08 10:35:59.393547 01364867 UTL  blocks:                 6 
07/08 10:35:59.393551 01364867 UTL  days:                   10 
07/08 10:35:59.393554 01364867 UTL  keep:                   3650 
07/08 10:35:59.393557 01364867 UTL  minRows:                100 
07/08 10:35:59.393561 01364867 UTL  maxRows:                4096 
07/08 10:35:59.393564 01364867 UTL  precision:              0 
07/08 10:35:59.393571 01364867 UTL  comp:                   2 
07/08 10:35:59.393575 01364867 UTL  walLevel:               1 
07/08 10:35:59.393578 01364867 UTL  fsync:                  3000 
07/08 10:35:59.393581 01364867 UTL  replica:                1 
07/08 10:35:59.393585 01364867 UTL  partitions:             4 
07/08 10:35:59.393588 01364867 UTL  quorum:                 1 
07/08 10:35:59.393591 01364867 UTL  update:                 0 
07/08 10:35:59.393595 01364867 UTL  cachelast:              0 
07/08 10:35:59.393598 01364867 UTL  compressMsgSize:        524288 
07/08 10:35:59.393602 01364867 UTL  compressColData:        -1 
07/08 10:35:59.393605 01364867 UTL  maxSQLLength:           1048576(byte)
07/08 10:35:59.393609 01364867 UTL  maxWildCardsLength:     100(byte)
07/08 10:35:59.393612 01364867 UTL  maxRegexStringLen:      128(byte)
07/08 10:35:59.393616 01364867 UTL  maxNumOfOrderedRes:     1000000 
07/08 10:35:59.393624 01364867 UTL  queryBufferSize:        -1(byte)
07/08 10:35:59.393628 01364867 UTL  retrieveBlockingModel:  0 
07/08 10:35:59.393631 01364867 UTL  keepColumnName:         1 
07/08 10:35:59.393635 01364867 UTL  timezone:                (CST, +0800) 
07/08 10:35:59.393639 01364867 UTL  locale:                 zh_CN.UTF-8 
07/08 10:35:59.393642 01364867 UTL  charset:                UTF-8 
07/08 10:35:59.393646 01364867 UTL  maxShellConns:          50000 
07/08 10:35:59.393649 01364867 UTL  maxConnections:         5000 
07/08 10:35:59.393653 01364867 UTL  minimalLogDirGB:        1.000000(GB)
07/08 10:35:59.393657 01364867 UTL  minimalTmpDirGB:        1.000000(GB)
07/08 10:35:59.393660 01364867 UTL  minimalDataDirGB:       2.000000(GB)
07/08 10:35:59.393664 01364867 UTL  mnodeEqualVnodeNum:     4 
07/08 10:35:59.393667 01364867 UTL  flowctrl:               1 
07/08 10:35:59.393671 01364867 UTL  slaveQuery:             1 
07/08 10:35:59.393675 01364867 UTL  adjustMaster:           1 
07/08 10:35:59.393678 01364867 UTL  http:                   1 
07/08 10:35:59.393682 01364867 UTL  monitor:                1 
07/08 10:35:59.393686 01364867 UTL  stream:                 1 
07/08 10:35:59.393689 01364867 UTL  topicBinaryLen:         16000 
07/08 10:35:59.393692 01364867 UTL  httpEnableRecordSql:    0 
07/08 10:35:59.393696 01364867 UTL  telegrafUseFieldNum:    0 
07/08 10:35:59.393734 01364867 UTL  httpMaxThreads:         2 
07/08 10:35:59.393740 01364867 UTL  restfulRowLimit:        10240 
07/08 10:35:59.393744 01364867 UTL  httpDbNameMandatory:    0 
07/08 10:35:59.393747 01364867 UTL  httpKeepAlive:          30000 
07/08 10:35:59.393751 01364867 UTL  numOfLogLines:          10000000 
07/08 10:35:59.393754 01364867 UTL  logKeepDays:            0 
07/08 10:35:59.393759 01364867 UTL  asyncLog:               1 
07/08 10:35:59.393763 01364867 UTL  debugFlag:              0 
07/08 10:35:59.393766 01364867 UTL  mDebugFlag:             131 
07/08 10:35:59.393769 01364867 UTL  dDebugFlag:             135 
07/08 10:35:59.393773 01364867 UTL  sDebugFlag:             135 
07/08 10:35:59.393776 01364867 UTL  wDebugFlag:             135 
07/08 10:35:59.393779 01364867 UTL  sdbDebugFlag:           131 
07/08 10:35:59.393783 01364867 UTL  rpcDebugFlag:           131 
07/08 10:35:59.393786 01364867 UTL  tmrDebugFlag:           131 
07/08 10:35:59.393789 01364867 UTL  cDebugFlag:             131 
07/08 10:35:59.393793 01364867 UTL  jniDebugFlag:           131 
07/08 10:35:59.393796 01364867 UTL  odbcDebugFlag:          131 
07/08 10:35:59.393824 01364867 UTL  uDebugFlag:             131 
07/08 10:35:59.393830 01364867 UTL  httpDebugFlag:          131 
07/08 10:35:59.393833 01364867 UTL  monDebugFlag:           131 
07/08 10:35:59.393837 01364867 UTL  qDebugFlag:             131 
07/08 10:35:59.393840 01364867 UTL  vDebugFlag:             135 
07/08 10:35:59.393845 01364867 UTL  tsdbDebugFlag:          131 
07/08 10:35:59.393860 01364867 UTL  cqDebugFlag:            131 
07/08 10:35:59.393865 01364867 UTL  enableRecordSql:        0 
07/08 10:35:59.393871 01364867 UTL  enableCoreFile:         0 
07/08 10:35:59.393886 01364867 UTL  gitinfo:                db5a04e113cf85c40a52489e558dbdfa4dbb11a4 
07/08 10:35:59.393908 01364867 UTL  gitinfoOfInternal:      NULL 
07/08 10:35:59.393913 01364867 UTL  buildinfo:              Built at 2022-06-25 15:01 
07/08 10:35:59.393918 01364867 UTL  version:                2.6.0.6 
07/08 10:35:59.393922 01364867 UTL  maxBinaryDisplayWidth:  30 
07/08 10:35:59.393925 01364867 UTL  tempDir:                /tmp/ 
07/08 10:35:59.393929 01364867 UTL  tsdbMetaCompactRatio:   0 
07/08 10:35:59.393932 01364867 UTL  deadLockKillQuery:      1 
07/08 10:35:59.393935 01364867 UTL  clientMerge:            0 
07/08 10:35:59.393939 01364867 UTL  defaultJSONStrType:     nchar 
07/08 10:35:59.393942 01364867 UTL  smlChildTableName:       
07/08 10:35:59.393945 01364867 UTL  smlTagNullName:         _tag_null 
07/08 10:35:59.393949 01364867 UTL  walFlushSize:           1024(Mb)
07/08 10:35:59.393952 01364867 UTL  shortcutFlag:           0 
07/08 10:35:59.393960 01364867 UTL  lossyColumns:            
07/08 10:35:59.393963 01364867 UTL  fPrecision:             0.000000 
07/08 10:35:59.393968 01364867 UTL  dPrecision:             0.000000 
07/08 10:35:59.393972 01364867 UTL  maxRange:               500 
07/08 10:35:59.393975 01364867 UTL  range:                  100 
07/08 10:35:59.393980 01364867 UTL  os pageSize:            4096(KB)
07/08 10:35:59.393988 01364867 UTL  os openMax:             1024
07/08 10:35:59.393991 01364867 UTL  os streamMax:           16
07/08 10:35:59.393994 01364867 UTL  os numOfCores:          2
07/08 10:35:59.393997 01364867 UTL  os totalMemory:         1431(MB)
07/08 10:35:59.394004 01364867 UTL  os sysname:             Linux
07/08 10:35:59.394007 01364867 UTL  os nodename:            openEulerA4
07/08 10:35:59.394011 01364867 UTL  os release:             5.10.0-60.18.0.50.oe2203.x86_64
07/08 10:35:59.394014 01364867 UTL  os version:             #1 SMP Wed Mar 30 03:12:24 UTC 2022
07/08 10:35:59.394017 01364867 UTL  os machine:             x86_64
07/08 10:35:59.394022 01364867 UTL  dataDir: /var/lib/taos
07/08 10:35:59.394025 01364867 UTL ==================================
07/08 10:35:59.394029 01364867 DND step:dnode-globalcfg is initialized
07/08 10:35:59.394184 01364867 TFS disk /var/lib/taos is mounted to tier level 0 id 0
07/08 10:35:59.403364 01364867 UTL ==================================
07/08 10:35:59.403453 01364867 UTL  os totalDisk:           55.804668(GB)
07/08 10:35:59.403469 01364867 UTL  os usedDisk:            9.358585(GB)
07/08 10:35:59.403473 01364867 UTL  os availDisk:           43.580460(GB)
07/08 10:35:59.403477 01364867 UTL ==================================
07/08 10:35:59.403481 01364867 DND dnode storage is initialized at /var/lib/taos/dnode
07/08 10:35:59.403487 01364867 DND step:dnode-storage is initialized
07/08 10:35:59.403529 01364867 DND dnode cfg is initialized
07/08 10:35:59.403537 01364867 DND step:dnode-cfg is initialized
07/08 10:35:59.403587 01364867 DND dnode eps is initialized
07/08 10:35:59.403592 01364867 DND step:dnode-eps is initialized
07/08 10:35:59.403615 01364867 DND dnode minfos is initialized
07/08 10:35:59.403619 01364867 DND step:dnode-minfos is initialized
07/08 10:35:59.406452 01364867 WAL wal module is initialized, rsetId:3
07/08 10:35:59.406501 01364867 DND step:dnode-wal is initialized
07/08 10:35:59.407001 01364867 DND step:dnode-sync is initialized
07/08 10:35:59.407074 01364867 DND ERROR free disk size: 0.698330 GB, too little, quit
07/08 10:35:59.407089 01364867 DND ERROR failed to check item:disk

**Comment by fenghuazzm** [comment]
看报错考虑是磁盘空间不够了，taosd 默认好像要 2 GB 才能启动

**Comment by waittingsummer** [comment]
![image](https://user-images.githubusercontent.com/32017265/177915862-291273d7-926d-4212-b176-1dbcfe34f2ca.png)

**Comment by waittingsummer** [comment]
已解决，修改/etc/taos/taos.cfg配置文件中log、tmp、data路径
![image](https://user-images.githubusercontent.com/32017265/177918727-3e66a276-d70b-4bc9-bf7b-020e09a3bae5.png)
