### ISSUE TITLE
call taos_query c api, result is failed

### ISSUE THREAD

**Issue by paopaol** [taosdata/TDengine#1466]
**Bug Description**
 ```sql
create database if not exists db
```
```c
taos_query("create database if not exists db"); 
```
result is failed. 
[error] DB already there.
but,i have Specify **if not exists**

**Expected Behavior**
result is success

**Environment (please complete the following information):**
 - OS: ubuntu
 - TDengine Version 1.6.6.1

**Comment by Shawshank-Smile** [comment]
I just want to have a try, but I can't find 1.6.6.1.   please give a correct one.

![image](https://user-images.githubusercontent.com/46439638/77917435-269e6b80-72cd-11ea-8bae-125ad085da9f.png)

**Comment by Shawshank-Smile** [comment]
Add my wechat 13720014098, Thank you.

**Comment by paopaol** [comment]
my version maybe a develop version from my colleagues.
[TDengine.zip](https://github.com/taosdata/TDengine/files/4412974/TDengine.zip)
this package is what i was used.

**Comment by Shawshank-Smile** [comment]
Try 1.6.5.6 on our webist please.  1.6.6.1 may not our original source code.

**Comment by paopaol** [comment]
ok
