### ISSUE TITLE
Using executeUpdate to execute ALTER statements via JNI，I found that the table structure had not changed in client

### ISSUE THREAD

**Issue by jiny28** [taosdata/TDengine#14663]
**Bug Description**
java原生连接方式使用executeUpdate()执行ALTER语句修改超级表结构后，在客户端执行describe stable命令发现并无变化，但是当我使用insert语句执行插入后（使用新表结构），再使用describe stable命令发现表结构已变化。

```
private void executeDDL(String ddlSql) throws SQLException {
        try (Connection connection = getConnection();
             Statement statement = connection.createStatement()) {
            // 输出0
            System.out.println(statement.executeUpdate("ALTER STABLE s ADD COLUMN field1 int;"));
           // connection.commit();
        }
 }
private static DataSource getDataSource(String host, int poolSize, String username, String password, String database) {
        String url = "jdbc:TAOS://" + host + ":6030/" + database;
        DruidDataSource dataSource = new DruidDataSource();
        // jdbc properties
        dataSource.setDriverClassName("com.taosdata.jdbc.TSDBDriver");
        dataSource.setUrl(url);
        dataSource.setUsername(username);
        dataSource.setPassword(password);
        Properties connProps = new Properties();
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_BATCH_LOAD, "true");
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_CHARSET, "utf-8");
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_LOCALE, "en_US.UTF-8");
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_TIME_ZONE, "UTC-8");
        connProps.setProperty("debugFlag", "135");
        connProps.setProperty("maxSQLLength", "1048576");
        dataSource.setConnectProperties(connProps);
        // pool configurations
        dataSource.setInitialSize(poolSize);
        dataSource.setMinIdle(poolSize);
        dataSource.setMaxActive(poolSize);
        dataSource.setMaxWait(30000);
        dataSource.setValidationQuery("select server_status()");
        log.info("taos pool url {}", dataSource.getUrl());
        return dataSource;
    }

**Comment by fenghuazzm** [comment]
目前机制确实是这样，可以改完表结构后在客户端执行 reset query cache; 刷下缓存

**Comment by jiny28** [comment]
> 目前机制确实是这样，可以改完表结构后在客户端执行 reset query cache; 刷下缓存

我尝试在java代码里面使用execute或executeUpdate方法执行该命令，并没有生效，但是我在windows客户端执行该命令后并生效。
请问有办法在java里面解决吗。

**Comment by fenghuazzm** [comment]
executeQuery 方法试试

**Comment by jiny28** [comment]
> executeQuery 方法试试

执行代码如下：
`
private void executeDDL(String ddlSql) throws SQLException {
        try (Connection connection = getConnection();
             Statement statement = connection.createStatement()) {
            statement.executeUpdate(ddlSql);
            resetCache();
        }
    }

    private void resetCache() throws SQLException {
        try (Connection connection = getConnection();
             Statement statement = connection.createStatement()) {
            statement.executeQuery("reset query cache;");
        }
    }
`
抛出异常如下：

`
java.sql.SQLException: ERROR (2307): Can not issue data manipulation statements with executeQuery()
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:72)
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:59)
	at com.taosdata.jdbc.TSDBStatement.executeQuery(TSDBStatement.java:51)
	at com.alibaba.druid.pool.DruidPooledStatement.executeQuery(DruidPooledStatement.java:296)
	at com.jiny.service.TaosImpl.resetCache(TaosImpl.java:165)
	at com.jiny.service.TaosImpl.executeDDL(TaosImpl.java:158)
	at com.jiny.service.TaosImpl.delFieldSTable(TaosImpl.java:79)
	at com.jiny.TaosApplicationTests.delFieldSTable(TaosApplicationTests.java:46)
`

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
