### ISSUE TITLE
Why does mybatis query ts increase precision？

### ISSUE THREAD

**Issue by homeless2010** [taosdata/TDengine#14678]
![image](https://user-images.githubusercontent.com/26829140/177936386-45a41601-b79a-481b-ba77-76da729510a9.png)
莫名其妙增大1000000倍
![image](https://user-images.githubusercontent.com/26829140/177936731-195c2a6e-ca93-46e2-a9a6-13bf365e82d1.png)

**Comment by fenghuazzm** [comment]
show create database XXX 看看所在数据库的 precision 配置是什么

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
