### ISSUE TITLE
Example StmtInsertExample is not worked in restful connection

### ISSUE THREAD

**Issue by xiegeng** [taosdata/TDengine#14673]
Example code StmtInsertExample is not worked when using Restful connection

I modify the code and it worked.

Could you please check the code and give me some suggestion.

If it's OK maybe you can added it to the example code for Restful connection.

Thanks.

[StmtInsertExample.zip](https://github.com/taosdata/TDengine/files/9068816/StmtInsertExample.zip)

**Comment by sangshuduo** [comment]
Right now RESTful does not support STMT.  Please see the official document.
