### ISSUE TITLE
How to invoke flush/commit manually by client/sql?

### ISSUE THREAD

**Issue by fangfcg** [taosdata/TDengine#14683]
**General Questions**
根据文档来看TDengine有时间驱动的落盘和数据驱动的落盘两种落盘方式，不知道除了这两种，在调试代码的时候有没有手动调用flush/commit进程的办法？
我尝试了COMPACT()的SQL语句，但是似乎并没有成功地调用起数据落盘，另外在调试时设置了taos.cfg的commitTime 30也没有起作用，不知道是否有一些其他办法，谢谢。

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
