### ISSUE TITLE
java.sql.SQLException: ERROR (2317): URI does not specify a valid host name: 

### ISSUE THREAD

**Issue by xt-simplism** [taosdata/TDengine#14705]
I have a question about  tdengine jdbc connection Exception: 
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: ERROR (2317): URI does not specify a valid host name: http://null:null/rest/login
so, what reason ?

**Comment by fenghuazzm** [comment]
You have given too little information to know the cause. I guess mapper.xml has configuration problems.
