### ISSUE TITLE
Use the "batch build sub table function " of the super table. The tag of the sub table is capitalized

### ISSUE THREAD

**Issue by colo1994** [taosdata/TDengine#1475]
既然是批量插入，我的SQL肯定是一样的。
之前都是数字，然后来了tag里面有字母的，发现变大写，然后查询失效了。
这两个不应该一致吗？
版本是1.6.5.5

**Comment by Shawshank-Smile** [comment]
I do not really unserstand what's your mean. Please add my wechat 13720014098.

**Comment by Shawshank-Smile** [comment]
solved by wechat.
