### ISSUE TITLE
 grafana：TDengine Data source is not working

### ISSUE THREAD

**Issue by r0pzzz** [taosdata/TDengine#14752]
TDengine Data source is not working

**Comment by r0pzzz** [comment]
我通过grafana进行TDengine connection 他提示TDengine Data source is not working

**Comment by fenghuazzm** [comment]
插件是什么版本？url是怎么写的？
多截些图

**Comment by r0pzzz** [comment]
grafana下载的是[grafana-enterprise-9.0.2-1.x86_64.rpm]
url是http://192.168.224.110:6041

**Comment by fenghuazzm** [comment]
grafana 和 TDengine 是在一个服务器或者内网里吗，taosadapter 开了吗？
grafana 9 太新了，我这边没试过，我抽空试试。grafana 8 我本地试着没问题

**Comment by r0pzzz** [comment]
开了 我现在用hadoop01:6041就可以运行 但是有192.168.224.110:6041不行 这个是正常的吗
我在etc/hosts里配置了192.168.224.110 hadoop01

**Comment by joekaapa** [comment]
Ditto, unable to achieve anything else than "TDengine Data source is not working" with Grafana 9.0.6 and TDEngine plugin 3.2.5. Taosadapter is running.

**Comment by sangshuduo** [comment]
> 

@joekaapa  are you running grafana/taosd/taosadapter on same machine? Or something else on a few different topologies? Did you try to access taosd via taos shell for natvie interface or curl for REST API?

**Comment by huolibo** [comment]
@joekaapa 

Currently，using grafana to monitor TDengine 3.x, you must start taosKeeper to write metrics to database. reference: [taosKeeper](https://docs.tdengine.com/reference/taosKeeper/)
and then select `TDengine for 3.x` dashboard in  `Dashboards tab` or import [the latest dashboard](https://github.com/taosdata/grafanaplugin/blob/master/dashboards/TDinsightV3.json)
finally, select the database taosKeeper write to in `Log from`. like [select database](https://docs.taosdata.com/assets/images/select_dashboard_db-b01fdf1ec0b0cc55e01063a035521c83.webp)

**Comment by lushi78778** [comment]
我遇到了相同的问题
version: 3.0.1.8
我的基础配置如下：https://ewlgc.gitee.io/tdengine-wiki/#/./docs/%E6%90%AD%E5%BB%BA%E9%9B%86%E7%BE%A4?id=%e9%9b%86%e7%be%a4%e6%89%8b%e5%8a%a8%e9%83%a8%e7%bd%b2
请打开查看，三个手动部署的集群
我在master上启动了TAOS_ADAPTER
输出如下
```text
12/01 11:45:53.037570 00001794 TAOS_ADAPTER info "server on : 6041" model=main
12/01 11:46:33.304978 00001794 TAOS_ADAPTER info "| 404 |     321.803µs |     192.168.3.1 | POST | /sql " model=web sessionID=1
12/01 11:48:31.016866 00001794 TAOS_ADAPTER info "| 404 |     385.191µs |     192.168.3.1 | POST | /sql " model=web sessionID=2
12/01 11:48:32.674758 00001794 TAOS_ADAPTER info "| 404 |     253.594µs |     192.168.3.1 | POST | /sql " sessionID=3 model=web
12/01 11:49:27.709592 00001794 TAOS_ADAPTER info "| 200 |   28.754457ms |     192.168.3.7 | POST | /rest/sql " sessionID=4 model=web
12/01 11:55:40.969385 00001794 TAOS_ADAPTER info "| 404 |     548.101µs |     192.168.3.1 | POST | /sql " model=web sessionID=5
```
200那次是我在Grafana主机上运行的请求，命令与返回值如下：
```text
[root@visualize-grafana ~]# curl -L -u root:taosdata \
>   -d "select name, ntables, status from information_schema.ins_databases;" \
>   192.168.3.2:6041/rest/sql
{"code":0,"column_meta":[["name","VARCHAR",64],["ntables","BIGINT",8],["status","VARCHAR",10]],"data":[["information_schema",22,"ready"],["performance_schema",5,"ready"],["test",10000,"ready"]],"rows":3}[root@visualize-grafana ~]#
```

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
