### ISSUE TITLE
DB error: Invalid Vgroup ID

### ISSUE THREAD

**Issue by xiejunyu** [taosdata/TDengine#14763]
服务器断电重新开机后就一直报错,用不了,请问如何恢复数据正常使用,恢复大部分数据也行
taos> select * from pcs limit 10;
DB error: Invalid Vgroup ID (3.180983s)
日志:
07/11 11:38:32.929446 00001785 RPC ERROR DND-S 0x7f4fa8ffeb68 (nil), connection is already released, rsp wont be sent
07/11 11:38:32.929472 00001785 VND vgId:3, not exist
07/11 11:38:32.929473 00001785 DND vgId:3, create vnode msg is received
07/11 11:38:32.929474 00001785 VND vgId:3, not exist
07/11 11:38:32.985080 00001785 VND vgId:3, successed to write /var/lib/taos/vnode/vnode3/config.json
07/11 11:38:32.985115 00001785 VND vgId:3, vnode dir is created, walLevel:1 fsyncPeriod:3000
07/11 11:38:32.985186 00001785 VND vgId:3, load vnode cfg successfully, replcia:1
07/11 11:38:32.985189 00001785 VND vgId:3, dnode:1, ubuntu:6040
07/11 11:38:32.985215 00001785 VND vgId:3, read /var/lib/taos/vnode/vnode3/version.json successfully, fver:3998135
07/11 11:38:32.985219 00001785 DND pVnode:0x7f4f585fdbd0, dnode vwrite queue:0x7f4f6f5aee90 is allocated
07/11 11:38:33.146309 00001785 TDB ERROR vgId:3 SBlockIdx part in file /var/lib/taos/vnode/vnode3/tsdb/data/v3f1918.head-ver639 is corrupted since wrong checksum, offset:80454972 len :1243120
07/11 11:38:33.146335 00001785 TDB ERROR vgId:3 failed to open TSDB repository while restore info since Data file(s) corrupted
07/11 11:38:33.169904 00001785 VND vgId:3, vnode will cleanup, refCount:1 pVnode:0x7f4f585fdbd0
07/11 11:38:33.169915 00001785 VND vgId:3, vnode is cleaned, refCount:1 pVnode:0x7f4f585fdbd0
07/11 11:38:33.169916 00001785 VND vgId:3, vnode will be destroyed, refCount:0 pVnode:0x7f4f585fdbd0
07/11 11:38:33.169933 00001785 VND vgId:3, vnode is destroyed, vnodes:1
07/11 11:38:33.169944 00001785 RPC ERROR DND-S 0x7f4fa8ffece0 (nil), connection is already released, rsp wont be sent
07/11 11:38:33.169957 00001785 VND vgId:4, not exist
07/11 11:38:33.169958 00001785 DND vgId:4, create vnode msg is received
07/11 11:38:33.169959 00001785 VND vgId:4, not exist
07/11 11:38:33.174824 00001785 VND vgId:4, successed to write /var/lib/taos/vnode/vnode4/config.json
07/11 11:38:33.174860 00001785 VND vgId:4, vnode dir is created, walLevel:1 fsyncPeriod:3000
07/11 11:38:33.174943 00001785 VND vgId:4, load vnode cfg successfully, replcia:1
07/11 11:38:33.174949 00001785 VND vgId:4, dnode:1, ubuntu:6040
07/11 11:38:33.174973 00001785 VND vgId:4, read /var/lib/taos/vnode/vnode4/version.json successfully, fver:4813952
07/11 11:38:33.174987 00001785 DND pVnode:0x7f4f585fdbd0, dnode vwrite queue:0x7f4f8a669b60 is allocated
07/11 11:38:33.342048 00001785 TDB ERROR vgId:4 SBlockIdx part in file /var/lib/taos/vnode/vnode4/tsdb/data/v4f1918.head-ver637 is corrupted since wrong checksum, offset:76839932 len :1234786
07/11 11:38:33.342073 00001785 TDB ERROR vgId:4 failed to open TSDB repository while restore info since Data file(s) corrupted
07/11 11:38:33.366138 00001785 VND vgId:4, vnode will cleanup, refCount:1 pVnode:0x7f4f585fdbd0
07/11 11:38:33.366152 00001785 VND vgId:4, vnode is cleaned, refCount:1 pVnode:0x7f4f585fdbd0
07/11 11:38:33.366153 00001785 VND vgId:4, vnode will be destroyed, refCount:0 pVnode:0x7f4f585fdbd0
07/11 11:38:33.366170 00001785 VND vgId:4, vnode is destroyed, vnodes:1
07/11 11:38:33.366180 00001785 RPC ERROR DND-S 0x7f4fa8ffee58 (nil), connection is already released, rsp wont be sent
07/11 11:38:33.366211 00001785 VND vgId:5, not exist
07/11 11:38:33.366211 00001785 DND vgId:5, create vnode msg is received
07/11 11:38:33.366212 00001785 VND vgId:5, not exist
07/11 11:38:33.403067 00001785 VND vgId:5, successed to write /var/lib/taos/vnode/vnode5/config.json
07/11 11:38:33.403102 00001785 VND vgId:5, vnode dir is created, walLevel:1 fsyncPeriod:3000
07/11 11:38:33.403152 00001785 VND vgId:5, load vnode cfg successfully, replcia:1
07/11 11:38:33.403154 00001785 VND vgId:5, dnode:1, ubuntu:6040
07/11 11:38:33.403161 00001785 VND vgId:5, read /var/lib/taos/vnode/vnode5/version.json successfully, fver:3676374
07/11 11:38:33.403166 00001785 DND pVnode:0x7f4f585fdbd0, dnode vwrite queue:0x7f4f6f5c88e0 is allocated
07/11 11:38:33.578164 00001785 TDB ERROR vgId:5 SBlockIdx part in file /var/lib/taos/vnode/vnode5/tsdb/data/v5f1918.head-ver643 is corrupted since wrong checksum, offset:79883636 len :1243544
07/11 11:38:33.578223 00001785 TDB ERROR vgId:5 failed to open TSDB repository while restore info since Data file(s) corrupted
07/11 11:38:33.605018 00001785 VND vgId:5, vnode will cleanup, refCount:1 pVnode:0x7f4f585fdbd0
07/11 11:38:33.605032 00001785 VND vgId:5, vnode is cleaned, refCount:1 pVnode:0x7f4f585fdbd0
07/11 11:38:33.605033 00001785 VND vgId:5, vnode will be destroyed, refCount:0 pVnode:0x7f4f585fdbd0
07/11 11:38:33.605050 00001785 VND vgId:5, vnode is destroyed, vnodes:1
07/11 11:38:33.605058 00001785 RPC ERROR DND-S 0x7f4fa8ffefd0 (nil), connection is already released, rsp wont be sent
07/11 11:38:33.605082 00001785 VND vgId:6, not exist
07/11 11:38:33.605083 00001785 DND vgId:6, create vnode msg is received
07/11 11:38:33.605084 00001785 VND vgId:6, not exist
07/11 11:38:33.666774 00001785 VND vgId:6, successed to write /var/lib/taos/vnode/vnode6/config.json
07/11 11:38:33.666844 00001785 VND vgId:6, vnode dir is created, walLevel:1 fsyncPeriod:3000
07/11 11:38:33.666929 00001785 VND vgId:6, load vnode cfg successfully, replcia:1
07/11 11:38:33.666933 00001785 VND vgId:6, dnode:1, ubuntu:6040
07/11 11:38:33.666951 00001785 VND vgId:6, read /var/lib/taos/vnode/vnode6/version.json successfully, fver:3309364
07/11 11:38:33.666955 00001785 DND pVnode:0x7f4f585fdbd0, dnode vwrite queue:0x7f4f585fe1a0 is allocated
07/11 11:38:33.844673 00001785 TDB ERROR vgId:6 SBlockIdx part in file /var/lib/taos/vnode/vnode6/tsdb/data/v6f1918.head-ver631 is corrupted since wrong checksum, offset:77609988 len :1234088
07/11 11:38:33.844705 00001785 TDB ERROR vgId:6 failed to open TSDB repository while restore info since Data file(s) corrupted
07/11 11:38:33.870231 00001785 VND vgId:6, vnode will cleanup, refCount:1 pVnode:0x7f4f585fdbd0
07/11 11:38:33.870243 00001785 VND vgId:6, vnode is cleaned, refCount:1 pVnode:0x7f4f585fdbd0
07/11 11:38:33.870244 00001785 VND vgId:6, vnode will be destroyed, refCount:0 pVnode:0x7f4f585fdbd0
07/11 11:38:33.870264 00001785 VND vgId:6, vnode is destroyed, vnodes:1
07/11 11:38:33.870275 00001785 RPC ERROR DND-S 0x7f4fa8fff148 (nil), connection is already released, rsp wont be sent
07/11 11:38:33.870298 00001785 VND vgId:7, not exist
07/11 11:38:33.870299 00001785 DND vgId:7, create vnode msg is received
07/11 11:38:33.870300 00001785 VND vgId:7, not exist
07/11 11:38:33.916128 00001785 VND vgId:7, successed to write /var/lib/taos/vnode/vnode7/config.json
07/11 11:38:33.916174 00001785 VND vgId:7, vnode dir is created, walLevel:1 fsyncPeriod:3000
07/11 11:38:33.916235 00001785 VND vgId:7, load vnode cfg successfully, replcia:1
07/11 11:38:33.916238 00001785 VND vgId:7, dnode:1, ubuntu:6040
07/11 11:38:33.916258 00001785 VND vgId:7, read /var/lib/taos/vnode/vnode7/version.json successfully, fver:2112825
07/11 11:38:33.916262 00001785 DND pVnode:0x7f4f585fdbd0, dnode vwrite queue:0x7f4f8a8b6c80 is allocated
07/11 11:38:34.458266 00001785 TDB ERROR vgId:7 SBlockIdx part in file /var/lib/taos/vnode/vnode7/tsdb/data/v7f1918.head-ver630 is corrupted since wrong checksum, offset:77657708 len :1226850
07/11 11:38:34.458311 00001785 TDB ERROR vgId:7 failed to open TSDB repository while restore info since Data file(s) corrupted
07/11 11:38:34.615866 00001785 VND vgId:7, vnode will cleanup, refCount:1 pVnode:0x7f4f585fdbd0
07/11 11:38:34.615878 00001785 VND vgId:7, vnode is cleaned, refCount:1 pVnode:0x7f4f585fdbd0
07/11 11:38:34.615886 00001785 VND vgId:7, vnode will be destroyed, refCount:0 pVnode:0x7f4f585fdbd0
07/11 11:38:34.615916 00001785 VND vgId:7, vnode is destroyed, vnodes:1
07/11 11:38:34.615927 00001785 RPC ERROR DND-S 0x7f4fa8fff2c0 (nil), connection is already released, rsp wont be sent
07/11 11:38:34.615943 00001785 VND vgId:8, not exist
07/11 11:38:34.615943 00001785 DND vgId:8, create vnode msg is received
07/11 11:38:34.615944 00001785 VND vgId:8, not exist
07/11 11:38:34.652746 00001785 VND vgId:8, successed to write /var/lib/taos/vnode/vnode8/config.json
07/11 11:38:34.652795 00001785 VND vgId:8, vnode dir is created, walLevel:1 fsyncPeriod:3000
07/11 11:38:34.652858 00001785 VND vgId:8, load vnode cfg successfully, replcia:1
07/11 11:38:34.652861 00001785 VND vgId:8, dnode:1, ubuntu:6040
07/11 11:38:34.652868 00001785 VND vgId:8, read /var/lib/taos/vnode/vnode8/version.json successfully, fver:1962000
07/11 11:38:34.652873 00001785 DND pVnode:0x7f4f585fdbd0, dnode vwrite queue:0x7f4f6f59fb10 is allocated
07/11 11:38:34.931550 00001785 TDB ERROR vgId:8 SBlockIdx part in file /var/lib/taos/vnode/vnode8/tsdb/data/v8f1918.head-ver620 is corrupted since wrong checksum, offset:75782716 len :1215082
07/11 11:38:34.931634 00001785 TDB ERROR vgId:8 failed to open TSDB repository while restore info since Data file(s) corrupted
07/11 11:38:34.969650 00001785 VND vgId:8, vnode will cleanup, refCount:1 pVnode:0x7f4f585fdbd0
07/11 11:38:34.969667 00001785 VND vgId:8, vnode is cleaned, refCount:1 pVnode:0x7f4f585fdbd0
07/11 11:38:34.969668 00001785 VND vgId:8, vnode will be destroyed, refCount:0 pVnode:0x7f4f585fdbd0
07/11 11:38:34.969700 00001785 VND vgId:8, vnode is destroyed, vnodes:1
07/11 11:38:34.969712 00001785 RPC ERROR DND-S 0x7f4fa8fff438 (nil), connection is already released, rsp wont be sent
07/11 11:38:34.969748 00001785 VND vgId:9, not exist
07/11 11:38:34.969749 00001785 DND vgId:9, create vnode msg is received
07/11 11:38:34.969750 00001785 VND vgId:9, not exist
07/11 11:38:34.974430 00001785 VND vgId:9, successed to write /var/lib/taos/vnode/vnode9/config.json
07/11 11:38:34.974503 00001785 VND vgId:9, vnode dir is created, walLevel:1 fsyncPeriod:3000
07/11 11:38:34.974613 00001785 VND vgId:9, load vnode cfg successfully, replcia:1
07/11 11:38:34.974618 00001785 VND vgId:9, dnode:1, ubuntu:6040
07/11 11:38:34.974626 00001785 VND vgId:9, read /var/lib/taos/vnode/vnode9/version.json successfully, fver:2369417
07/11 11:38:34.974629 00001785 DND pVnode:0x7f4f585fdbd0, dnode vwrite queue:0x7f4f880029d0 is allocated
07/11 11:38:35.370294 00001785 TDB ERROR vgId:9 SBlockIdx part in file /var/lib/taos/vnode/vnode9/tsdb/data/v9f1918.head-ver626 is corrupted since wrong checksum, offset:75696804 len :1219797
07/11 11:38:35.370333 00001785 TDB ERROR vgId:9 failed to open TSDB repository while restore info since Data file(s) corrupted
07/11 11:38:35.392118 00001785 VND vgId:9, vnode will cleanup, refCount:1 pVnode:0x7f4f585fdbd0
07/11 11:38:35.392128 00001785 VND vgId:9, vnode is cleaned, refCount:1 pVnode:0x7f4f585fdbd0
07/11 11:38:35.392129 00001785 VND vgId:9, vnode will be destroyed, refCount:0 pVnode:0x7f4f585fdbd0
07/11 11:38:35.392143 00001785 VND vgId:9, vnode is destroyed, vnodes:1
07/11 11:38:35.392152 00001785 RPC ERROR DND-S 0x7f4fa8fff5b0 (nil), connection is already released, rsp wont be sent
07/11 11:38:35.392171 00001785 VND vgId:10, not exist
07/11 11:38:35.392172 00001785 DND vgId:10, create vnode msg is received
07/11 11:38:35.392174 00001785 VND vgId:10, not exist
07/11 11:38:35.393199 00001785 VND vgId:10, successed to write /var/lib/taos/vnode/vnode10/config.json
07/11 11:38:35.393218 00001785 VND vgId:10, vnode dir is created, walLevel:1 fsyncPeriod:3000
07/11 11:38:35.393281 00001785 VND vgId:10, load vnode cfg successfully, replcia:1
07/11 11:38:35.393290 00001785 VND vgId:10, dnode:1, ubuntu:6040
07/11 11:38:35.393299 00001785 VND vgId:10, read /var/lib/taos/vnode/vnode10/version.json successfully, fver:2897380
07/11 11:38:35.393303 00001785 DND pVnode:0x7f4f585fdbd0, dnode vwrite queue:0x7f4f585fe1a0 is allocated
07/11 11:38:35.698906 00001785 TDB ERROR vgId:10 SBlockIdx part in file /var/lib/taos/vnode/vnode10/tsdb/data/v10f1918.head-ver629 is corrupted since wrong checksum, offset:77486748 len :1217667
07/11 11:38:35.698945 00001785 TDB ERROR vgId:10 failed to open TSDB repository while restore info since Data file(s) corrupted
07/11 11:38:35.718617 00001785 VND vgId:10, vnode will cleanup, refCount:1 pVnode:0x7f4f585fdbd0
07/11 11:38:35.718633 00001785 VND vgId:10, vnode is cleaned, refCount:1 pVnode:0x7f4f585fdbd0
07/11 11:38:35.718634 00001785 VND vgId:10, vnode will be destroyed, refCount:0 pVnode:0x7f4f585fdbd0
07/11 11:38:35.718653 00001785 VND vgId:10, vnode is destroyed, vnodes:1
07/11 11:38:35.718677 00001785 RPC ERROR DND-S 0x7f4fa8fff728 (nil), connection is already released, rsp wont be sent
07/11 11:38:35.718707 00001785 VND vgId:3, not exist
07/11 11:38:35.718707 00001785 DND vgId:3, create vnode msg is received
07/11 11:38:35.718708 00001785 VND vgId:3, not exist
07/11 11:38:35.730600 00001785 VND vgId:3, successed to write /var/lib/taos/vnode/vnode3/config.json
07/11 11:38:35.730655 00001785 VND vgId:3, vnode dir is created, walLevel:1 fsyncPeriod:3000
07/11 11:38:35.730782 00001785 VND vgId:3, load vnode cfg successfully, replcia:1
07/11 11:38:35.730803 00001785 VND vgId:3, dnode:1, ubuntu:6040
07/11 11:38:35.730817 00001785 VND vgId:3, read /var/lib/taos/vnode/vnode3/version.json successfully, fver:3998135
07/11 11:38:35.730824 00001785 DND pVnode:0x7f4f585fdbd0, dnode vwrite queue:0x7f4f6fc24a90 is allocated

 - OS: Ubuntu 20.04.4 LTS
 - Memory 6G, current Disk Space 700G
 - TDengine Version 2.4.0.30

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
