### ISSUE TITLE
what is it mean when a record "show type:show grants is not supported" appears in log file 

### ISSUE THREAD

**Issue by Autoloop** [taosdata/TDengine#14767]
I  am use taodump to backup data ,but I fund the result number I checked after the dump is completed , I fund the number is smaller than the recods in database,
the I search in the logfile ,find what I attach in the title;

**Describe your desired behavior**
the command what i used is like 
taodump -h 127.0.0.1 -p 6030 -o data databaseName stableName

the recods in the super table is about 35 million ,and will be larger in the future

but when I check the dump_result.txt ,the number always smaller than 35 million

I tried make the rpcMaxTime in taos.cfg larger , but it seems does not work, the current value after I adjust is 1800 

Additional:
is this config should be adjust both server and client?

**Comment by sangshuduo** [comment]
how many sub-tables are under the stable? are you running a cluster? could you please paste the dump_result.txt?

**Comment by Autoloop** [comment]
========== arguments config =========
taosdump version 1.4.4-6-g4d83d8c_4d83d8c
host: (null)
user: root
port: 0
outpath: data/
inpath:
resultFile: ./dump_result.txt
all_databases: false
databases: false
databasesSeq: (null)
schemaonly: false
with_property: true
answer_yes: false
avro codec: snappy
data_batch: 16383
thread_num: 8
allow_sys: false
escape_char: true
loose_mode: false
isDumpIn: false
arg_list_len: 2
arg_list[0]: daily_quotation
arg_list[1]: bond_daily_quotation
debug_print: 0
========== DUMP OUT ==========
# DumpOut start time:                   2022-07-11 18:11:43

============================== TOTAL STATISTICS ==============================
# total database count:     0
# total super table count:  0
# total child table count:  0
# total row count:          6603569



this is the dump_result.txt which I reproduce just now 

about 72666 sub-tables in bond_daily_quotation, I guess there are about 20000 sub-tables are empty

**Comment by Autoloop** [comment]
> how many sub-tables are under the stable? are you running a cluster? could you please paste the dump_result.txt?
I am not running in cluster ,but pretend to run in cluster where deploy in prod

**Comment by sangshuduo** [comment]
can you dump it again with same parameters but add one more '-g' and redirect the output to a text file.
for example: 
`taosdump -D <dbname> -o <output_dir> -g 2>&1 | tee out.txt`

then attach out.txt here.

**Comment by Autoloop** [comment]
[out1.zip](https://github.com/taosdata/TDengine/files/9084733/out1.zip)

**Comment by sangshuduo** [comment]
according to the log, the number of sub-tables is 69193. the number of total rows is 6060020

**Comment by Autoloop** [comment]
> according to the log, the number of sub-tables is 69193. the number of total rows is 6060020

actually ,the number of total rows in database,which I use the query "select count(*) from bond_daily_quotation", is greater then it,

the reason why the number of the sub-table is 69193 is I delete some empty sub-table;

After I delete some emptyTable ,the number of records which dumped out increased

**Comment by Autoloop** [comment]
I past some of log here 


07/12 13:04:06.964641 00000140 MND user:root login from 10.10.80.96, result:success
07/12 13:04:07.007306 00000138 MND user:root login from 10.10.80.96, result:success
07/12 13:04:07.042775 00000137 MND user:root login from 10.10.80.96, result:success
07/12 13:04:07.078506 00000139 MND user:root login from 10.10.80.96, result:success
07/12 13:04:07.113150 00000140 MND user:root login from 10.10.80.96, result:success
07/12 13:04:07.157778 00000137 MND user:root login from 10.10.80.96, result:success
07/12 13:04:07.185910 00000125 VND ERROR vgId:35, invalid qId in retrieving result, code:Invalid handle, QInfo:19174959026203848
07/12 13:04:19.332152 00000139 SDB vgId:1, update mnodes role, replica:1
07/12 13:04:19.332441 00000139 SDB vgId:1, mnode:1, role:master
07/12 13:04:19.332472 00000139 MND vgId:1, update mnodes epSet, numOfMnodes:1
07/12 13:04:19.332507 00000139 MND vgId:1, mnodes epSet is set, num:1 inUse:0
07/12 13:04:19.332528 00000139 MND vgId:1, mnode:1, fqdn:tdengine-node1 shell:6030 peer:6035
07/12 13:04:19.336515 00000138 SDB vgId:1, update mnodes role, replica:1
07/12 13:04:19.336629 00000138 SDB vgId:1, mnode:1, role:master
07/12 13:04:19.336650 00000138 MND vgId:1, update mnodes epSet, numOfMnodes:1
07/12 13:04:19.336671 00000138 MND vgId:1, mnodes epSet is set, num:1 inUse:0
07/12 13:04:19.336684 00000138 MND vgId:1, mnode:1, fqdn:tdengine-node1 shell:6030 peer:6035
07/12 13:04:19.338790 00000138 SDB vgId:1, update mnodes role, replica:1
07/12 13:04:19.338903 00000138 SDB vgId:1, mnode:1, role:master
07/12 13:04:19.338922 00000138 MND vgId:1, update mnodes epSet, numOfMnodes:1
07/12 13:04:19.338939 00000138 MND vgId:1, mnodes epSet is set, num:1 inUse:0
07/12 13:04:19.338951 00000138 MND vgId:1, mnode:1, fqdn:tdengine-node1 shell:6030 peer:6035
07/12 13:04:19.379356 00000138 MND WARN show type:show grants is not supported

**Comment by sangshuduo** [comment]
seems something happened and made the query timeout according to " invalid qId in retrieving result, code:Invalid handle," You can add "shellActivityTimer 120" to taos.cfg and try again.

**Comment by seven54** [comment]
我也遇到这样的问题，有没有好的解决方案

**Comment by Autoloop** [comment]
机器资源给大，部署数据库的物理节点和执行导出的物理节点分割开，调大参数


 
---Original---
From: ***@***.***&gt;
Date: 2022/7/18 14:49:34
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [taosdata/TDengine] what is it mean when a record "show type:showgrants is not supported" appears in log file  (Issue #14767)




 
我也遇到这样的问题，有没有好的解决方案
