### ISSUE TITLE
windows client error：failed to set up connection(Unable to establish connection)

### ISSUE THREAD

**Issue by myhzg** [taosdata/TDengine#14764]
服务器：社区版2.6.0.6版本，3台linux虚拟机部署的集群，配置了各自fqdn，时区Asia/Shanghai、本地化en_us.UTF-8、字符集UTF-8。群集运行正常。
windows客户端：win10，客户端2.6.0.6，配置了hosts文件fqdn相应配置，时区、本地化、字符集都与服务端匹配。
现象：show databases; show dnodes;show mnodes; 都能正常执行，但只要涉及insert与select之类的语句，执行超时。但insert与select在服务端的taosAdapter里可以执行，使用restful也可以执行。
客户端日志如下：
==================================================
                new log file                      
==================================================
07/11 15:36:35.059000 00008348 UTL localEp is: DESKTOP-F3NE697:6030
07/11 15:36:35.113000 00008348 UTL ERROR Invalid locale:en_US.UTF-8, please set the valid locale in config file
07/11 15:36:35.113000 00008348 UTL timezone is set to UTC-8 by config file
07/11 15:36:35.113000 00008348 UTL timezone format changed to (UTC, +0800)
07/11 15:36:35.113000 00008348 UTL    check global cfg completed
07/11 15:36:35.113000 00008348 UTL ==================================
07/11 15:36:35.113000 00008348 UTL    taos config & system info:
07/11 15:36:35.113000 00008348 UTL ==================================
07/11 15:36:35.113000 00008348 UTL  firstEp:                tdnode1.xxx.com:6030 
07/11 15:36:35.113000 00008348 UTL  secondEp:               DESKTOP-F3NE697:6030 
07/11 15:36:35.113000 00008348 UTL  fqdn:                   DESKTOP-F3NE697 
07/11 15:36:35.113000 00008348 UTL  serverPort:             6030 
07/11 15:36:35.113000 00008348 UTL  configDir:              C:\TDengine\cfg 
07/11 15:36:35.113000 00008348 UTL  logDir:                 C:\TDengine\log 
07/11 15:36:35.113000 00008348 UTL  scriptDir:              C:/TDengine/script 
07/11 15:36:35.113000 00008348 UTL  arbitrator:              
07/11 15:36:35.113000 00008348 UTL  numOfThreadsPerCore:    1.000000 
07/11 15:36:35.113000 00008348 UTL  maxNumOfDistinctRes:    10000000 
07/11 15:36:35.113000 00008348 UTL  rpcTimer:               300(ms)
07/11 15:36:35.113000 00008348 UTL  rpcMaxTime:             600(s)
07/11 15:36:35.113000 00008348 UTL  rpcForceTcp:            0 
07/11 15:36:35.113000 00008348 UTL  shellActivityTimer:     3(s)
07/11 15:36:35.113000 00008348 UTL  compressMsgSize:        524288 
07/11 15:36:35.113000 00008348 UTL  compressColData:        -1 
07/11 15:36:35.113000 00008348 UTL  maxSQLLength:           1048576(byte)
07/11 15:36:35.113000 00008348 UTL  maxWildCardsLength:     100(byte)
07/11 15:36:35.113000 00008348 UTL  maxRegexStringLen:      128(byte)
07/11 15:36:35.113000 00008348 UTL  maxNumOfOrderedRes:     1000000 
07/11 15:36:35.113000 00008348 UTL  keepColumnName:         1 
07/11 15:36:35.113000 00008348 UTL  timezone:               (UTC, +0800) 
07/11 15:36:35.113000 00008348 UTL  locale:                 en_US.UTF-8 
07/11 15:36:35.113000 00008348 UTL  charset:                UTF-8 
07/11 15:36:35.113000 00008348 UTL  numOfLogLines:          10000000 
07/11 15:36:35.113000 00008348 UTL  logKeepDays:            0 
07/11 15:36:35.113000 00008348 UTL  asyncLog:               1 
07/11 15:36:35.113000 00008348 UTL  debugFlag:              0 
07/11 15:36:35.113000 00008348 UTL  rpcDebugFlag:           131 
07/11 15:36:35.113000 00008348 UTL  tmrDebugFlag:           131 
07/11 15:36:35.113000 00008348 UTL  cDebugFlag:             131 
07/11 15:36:35.113000 00008348 UTL  jniDebugFlag:           131 
07/11 15:36:35.113000 00008348 UTL  odbcDebugFlag:          131 
07/11 15:36:35.113000 00008348 UTL  uDebugFlag:             131 
07/11 15:36:35.113000 00008348 UTL  qDebugFlag:             131 
07/11 15:36:35.113000 00008348 UTL  tsdbDebugFlag:          131 
07/11 15:36:35.113000 00008348 UTL  gitinfo:                db5a04e113cf85c40a52489e558dbdfa4dbb11a4 
07/11 15:36:35.113000 00008348 UTL  gitinfoOfInternal:      dbdbf33adbaa7a820dba86a07abb226480b1817d 
07/11 15:36:35.113000 00008348 UTL  buildinfo:              Built at 2022-06-25 15:01:37 
07/11 15:36:35.113000 00008348 UTL  version:                2.6.0.6 
07/11 15:36:35.113000 00008348 UTL  maxBinaryDisplayWidth:  30 
07/11 15:36:35.113000 00008348 UTL  tempDir:                C:\Users\admin\AppData\Local\Temp 
07/11 15:36:35.113000 00008348 UTL  defaultJSONStrType:     nchar 
07/11 15:36:35.114000 00008348 UTL  smlChildTableName:       
07/11 15:36:35.114000 00008348 UTL  smlTagNullName:         _tag_null 
07/11 15:36:35.114000 00008348 UTL  walFlushSize:           1024(Mb)
07/11 15:36:35.114000 00008348 UTL  shortcutFlag:           0 
07/11 15:36:35.114000 00008348 UTL  os numOfCores:          8
07/11 15:36:35.114000 00008348 UTL  os totalMemory:         8191(MB)
07/11 15:36:35.114000 00008348 UTL ==================================
07/11 15:36:35.114000 00008348 UTL  dataDir: C:/TDengine/data level:0 primary:1
07/11 15:36:35.114000 00008348 UTL ==================================
07/11 15:37:13.801000 00002956 UTL ERROR failed to connect socket, ip:0x9b507867, port:6030(Invalid argument)
07/11 15:37:13.801000 00002956 RPC ERROR failed to connect to:0x9b507867:6030
07/11 15:37:13.801000 00002956 RPC ERROR TSC 0000000000000004, failed to set up connection(Unable to establish connection)
07/11 15:37:13.805000 00007532 TSC WARN 0x4 it shall renew table meta, code:Unable to establish connection, retry:1
07/11 15:37:34.807000 00002956 UTL ERROR failed to connect socket, ip:0x9b507867, port:6030(Unknown error)
07/11 15:37:34.807000 00002956 RPC ERROR failed to connect to:0x9b507867:6030
07/11 15:37:34.807000 00002956 RPC ERROR TSC 0000000000000004, failed to set up connection(Unable to establish connection)
07/11 15:37:34.809000 00007532 TSC WARN 0x4 it shall renew table meta, code:Unable to establish connection, retry:2
07/11 15:37:55.811000 00002956 UTL ERROR failed to connect socket, ip:0x9b507867, port:6030(Unknown error)
07/11 15:37:55.811000 00002956 RPC ERROR failed to connect to:0x9b507867:6030
07/11 15:37:55.811000 00002956 RPC ERROR TSC 0000000000000004, failed to set up connection(Unable to establish connection)
07/11 15:37:55.814000 00007532 TSC WARN 0x4 it shall renew table meta, code:Unable to establish connection, retry:3
07/11 15:38:16.817000 00002956 UTL ERROR failed to connect socket, ip:0x9b507867, port:6030(Unknown error)
07/11 15:38:16.817000 00002956 RPC ERROR failed to connect to:0x9b507867:6030
07/11 15:38:16.817000 00002956 RPC ERROR TSC 0000000000000004, failed to set up connection(Unable to establish connection)
07/11 15:38:16.820000 00007532 TSC WARN 0x4 it shall renew table meta, code:Unable to establish connection, retry:4
07/11 15:38:37.823000 00002956 UTL ERROR failed to connect socket, ip:0x9b507867, port:6030(Unknown error)
07/11 15:38:37.823000 00002956 RPC ERROR failed to connect to:0x9b507867:6030
07/11 15:38:37.823000 00002956 RPC ERROR TSC 0000000000000004, failed to set up connection(Unable to establish connection)
07/11 15:38:37.825000 00007532 TSC WARN 0x4 it shall renew table meta, code:Unable to establish connection, retry:5
07/11 15:38:58.828000 00002956 UTL ERROR failed to connect socket, ip:0x9b507867, port:6030(Unknown error)
07/11 15:38:58.828000 00002956 RPC ERROR failed to connect to:0x9b507867:6030
07/11 15:38:58.828000 00002956 RPC ERROR TSC 0000000000000004, failed to set up connection(Unable to establish connection)
07/11 15:38:58.830000 00007532 TSC WARN 0x4 it shall renew table meta, code:Unable to establish connection, retry:6
07/11 15:38:58.830000 00007532 TSC ERROR 0x4 max retry 5 reached, give up

郁闷很久了，帮忙看一下

**Comment by xunzhimeng** [comment]
> 

这个问题最近看到挺多的，应该是这个版本的bug，试试老版本看看吧

**Comment by cidxie** [comment]
这个问题我也碰到了，在开启tdengine时出现。改完 rpcForceTcp 参数没生效，还是这样

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
