### ISSUE TITLE
Connection failure in case of too many remote query lines

### ISSUE THREAD

**Issue by wangfeng-szsh** [taosdata/TDengine#1484]
TDengine shell from linux, community client version:1.6.4.3 community server version:1.6.4.3

![OK](https://user-images.githubusercontent.com/62975847/78095201-f1973380-7408-11ea-9d2b-152a9c38ab02.jpg)
![error_linux](https://user-images.githubusercontent.com/62975847/78095210-f78d1480-7408-11ea-920c-2b4c67d5a4e6.jpg)
![error_windows](https://user-images.githubusercontent.com/62975847/78095219-fc51c880-7408-11ea-8678-2a928adce32e.jpg)

**Comment by Shawshank-Smile** [comment]
ZF vs GitHub, Can not see the picture. Add my wechat 13720014098, or show the errror directly. Thank you

**Comment by Shawshank-Smile** [comment]
Use TCP instead of UDP for transporting data, and this problem will not show again.

**Comment by wangfeng-szsh** [comment]
thanks, i will try that setting
