### ISSUE TITLE
How does the TDengine cluster master/slave node be determined？

### ISSUE THREAD

**Issue by r0pzzz** [taosdata/TDengine#14878]
TDengine集群配置replica和主从节点是怎么确定的
taos> create DATABASE a REPLICA 2;
Query OK, 0 of 0 row(s) in database (0.001598s)

taos> use a;
Database changed.

taos> show vgroups;
Query OK, 0 row(s) in set (0.002479s)

taos> create table tb1(ts timestamp,info binary(40));
Query OK, 0 of 0 row(s) in database (0.313873s)

taos> insert into tb1 values(now,"1111");
Query OK, 1 of 1 row(s) in database (0.000824s)

taos> select * from tb1;
           ts            |              info              |
===========================================================
 2022-07-13 22:39:07.073 | 1111                           |
Query OK, 1 row(s) in set (0.005416s)

taos> show vgroups;
    vgId     |   tables    |  status  |   onlines   | v1_dnode | v1_status | v2_dnode | v2_status | compacting  |
=================================================================================================================
           9 |           1 | ready    |           2 |        3 | leader    |        2 | follower  |           0 |
Query OK, 1 row(s) in set (0.001123s)
我有三个服务端，replica设置为2时，他使用的2和3 replica为默认1时则为3
我想知道这是通过什么原理决定的

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
