### ISSUE TITLE
Every time when100 entries are inserted only two entries will be success，Data lost!!!!

### ISSUE THREAD

**Issue by wzf55555** [taosdata/TDengine#1488]
IMPORT into devtagvalue_0d47383231343730009deb2e03a8f2fa  (createTime,Id,devID,tagName,sampleTime,updateTime,tagValue)  values (now,'3101','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_282_WLYeWei_1','2019-09-18 20:39:21','2019-09-18 20:39:22','0.676' )(now,'3102','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_197_ModbusH2S_2','2019-09-18 20:39:21','2019-09-18 20:39:23','0' )(now,'3103','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_143_NBCurrentDetection0_0','2019-09-18 20:42:08','2019-09-18 20:41:37','0.102' )(now,'3104','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_144_NBCurrentDetection1_1','2019-09-18 20:42:08','2019-09-18 20:41:37','0.139' )(now,'3105','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_151_NBLevelDetection0_0','2019-09-18 20:42:08','2019-09-18 20:41:37','0' )(now,'3106','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_152_NBLevelDetection1_1','2019-09-18 20:42:08','2019-09-18 20:41:37','1' )(now,'3107','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_153_NBLevelDetection2_2','2019-09-18 20:42:08','2019-09-18 20:41:37','1' )(now,'3108','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_154_NBLevelDetection3_3','2019-09-18 20:42:08','2019-09-18 20:41:37','1' )(now,'3109','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_159_NBLeveloutput0_0','2019-09-18 20:42:08','2019-09-18 20:41:37','0' )(now,'3110','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_160_NBLeveloutput1_1','2019-09-18 20:42:08','2019-09-18 20:41:37','0' )(now,'3111','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_141_NBBattery_0','2019-09-18 20:42:08','2019-09-18 20:41:37','242' )(now,'3112','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_224_WaterUpper_0','2019-09-18 20:42:09','2019-09-18 20:41:37','1' )(now,'3113','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_225_WaterLower_0','2019-09-18 20:42:09','2019-09-18 20:41:37','0.85' )(now,'3114','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_255_WLStopLower_0','2019-09-18 20:42:09','2019-09-18 20:41:37','0.5' )(now,'3115','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_235_ControlMode_0','2019-09-18 20:42:09','2019-09-18 20:41:37','1' )(now,'3116','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_261_WLAutomaticRemote_0','2019-09-18 20:42:09','2019-09-18 20:41:37','1' )(now,'3117','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_257_WLPump1Fault_0','2019-09-18 20:42:09','2019-09-18 20:41:37','0' )(now,'3118','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_258_WLPump2Fault_0','2019-09-18 20:42:09','2019-09-18 20:41:37','0' )(now,'3119','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_259_WLPump1Enable_0','2019-09-18 20:42:09','2019-09-18 20:41:37','0' )(now,'3120','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_260_WLPump2Enable_0','2019-09-18 20:42:09','2019-09-18 20:41:37','1' )(now,'3121','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_282_WLYeWei_1','2019-09-18 20:42:10','2019-09-18 20:41:38','0.677' )(now,'3122','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_197_ModbusH2S_2','2019-09-18 20:41:37','2019-09-18 20:41:39','0' )(now,'3123','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_143_NBCurrentDetection0_0','2019-09-18 20:44:24','2019-09-18 20:43:52','0.102' )(now,'3124','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_144_NBCurrentDetection1_1','2019-09-18 20:44:24','2019-09-18 20:43:52','0.139' )(now,'3125','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_151_NBLevelDetection0_0','2019-09-18 20:44:24','2019-09-18 20:43:53','0' )(now,'3126','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_152_NBLevelDetection1_1','2019-09-18 20:44:24','2019-09-18 20:43:53','1' )(now,'3127','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_153_NBLevelDetection2_2','2019-09-18 20:44:24','2019-09-18 20:43:53','1' )(now,'3128','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_154_NBLevelDetection3_3','2019-09-18 20:44:24','2019-09-18 20:43:53','1' )(now,'3129','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_159_NBLeveloutput0_0','2019-09-18 20:44:24','2019-09-18 20:43:53','0' )(now,'3130','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_160_NBLeveloutput1_1','2019-09-18 20:44:24','2019-09-18 20:43:53','0' )(now,'3131','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_141_NBBattery_0','2019-09-18 20:44:24','2019-09-18 20:43:53','242' )(now,'3132','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_224_WaterUpper_0','2019-09-18 20:44:25','2019-09-18 20:43:53','1' )(now,'3133','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_225_WaterLower_0','2019-09-18 20:44:25','2019-09-18 20:43:53','0.85' )(now,'3134','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_255_WLStopLower_0','2019-09-18 20:44:25','2019-09-18 20:43:53','0.5' )(now,'3135','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_235_ControlMode_0','2019-09-18 20:44:25','2019-09-18 20:43:53','1' )(now,'3136','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_261_WLAutomaticRemote_0','2019-09-18 20:44:25','2019-09-18 20:43:53','1' )(now,'3137','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_257_WLPump1Fault_0','2019-09-18 20:44:25','2019-09-18 20:43:53','0' )(now,'3138','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_258_WLPump2Fault_0','2019-09-18 20:44:25','2019-09-18 20:43:53','0' )(now,'3139','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_259_WLPump1Enable_0','2019-09-18 20:44:25','2019-09-18 20:43:53','0' )(now,'3140','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_260_WLPump2Enable_0','2019-09-18 20:44:25','2019-09-18 20:43:53','1' )(now,'3141','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_282_WLYeWei_1','2019-09-18 20:44:25','2019-09-18 20:43:53','0.677' )(now,'3142','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_197_ModbusH2S_2','2019-09-18 20:43:52','2019-09-18 20:43:54','0' )(now,'3143','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_143_NBCurrentDetection0_0','2019-09-18 20:48:15','2019-09-18 20:47:46','0.102' )(now,'3144','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_144_NBCurrentDetection1_1','2019-09-18 20:48:15','2019-09-18 20:47:46','0.140' )(now,'3145','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_151_NBLevelDetection0_0','2019-09-18 20:48:15','2019-09-18 20:47:46','0' )(now,'3146','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_152_NBLevelDetection1_1','2019-09-18 20:48:15','2019-09-18 20:47:46','1' )(now,'3147','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_153_NBLevelDetection2_2','2019-09-18 20:48:15','2019-09-18 20:47:46','1' )(now,'3148','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_154_NBLevelDetection3_3','2019-09-18 20:48:15','2019-09-18 20:47:46','1' )(now,'3149','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_159_NBLeveloutput0_0','2019-09-18 20:48:15','2019-09-18 20:47:46','0' )(now,'3150','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_160_NBLeveloutput1_1','2019-09-18 20:48:15','2019-09-18 20:47:46','0' )(now,'3151','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_141_NBBattery_0','2019-09-18 20:48:15','2019-09-18 20:47:46','242' )(now,'3152','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_224_WaterUpper_0','2019-09-18 20:48:16','2019-09-18 20:47:47','1' )(now,'3153','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_225_WaterLower_0','2019-09-18 20:48:16','2019-09-18 20:47:47','0.85' )(now,'3154','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_255_WLStopLower_0','2019-09-18 20:48:16','2019-09-18 20:47:47','0.5' )(now,'3155','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_235_ControlMode_0','2019-09-18 20:48:16','2019-09-18 20:47:47','1' )(now,'3156','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_261_WLAutomaticRemote_0','2019-09-18 20:48:16','2019-09-18 20:47:47','1' )(now,'3157','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_257_WLPump1Fault_0','2019-09-18 20:48:16','2019-09-18 20:47:47','0' )(now,'3158','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_258_WLPump2Fault_0','2019-09-18 20:48:16','2019-09-18 20:47:47','0' )(now,'3159','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_259_WLPump1Enable_0','2019-09-18 20:48:16','2019-09-18 20:47:47','0' )(now,'3160','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_260_WLPump2Enable_0','2019-09-18 20:48:16','2019-09-18 20:47:47','1' )(now,'3161','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_282_WLYeWei_1','2019-09-18 20:47:46','2019-09-18 20:47:47','0.678' )(now,'3162','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_197_ModbusH2S_2','2019-09-18 20:47:46','2019-09-18 20:47:48','0' )(now,'3163','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_143_NBCurrentDetection0_0','2019-09-18 20:50:33','2019-09-18 20:50:02','0.102' )(now,'3164','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_144_NBCurrentDetection1_1','2019-09-18 20:50:33','2019-09-18 20:50:02','0.140' )(now,'3165','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_151_NBLevelDetection0_0','2019-09-18 20:50:33','2019-09-18 20:50:02','0' )(now,'3166','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_152_NBLevelDetection1_1','2019-09-18 20:50:33','2019-09-18 20:50:02','1' )(now,'3167','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_153_NBLevelDetection2_2','2019-09-18 20:50:33','2019-09-18 20:50:02','1' )(now,'3168','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_154_NBLevelDetection3_3','2019-09-18 20:50:33','2019-09-18 20:50:02','1' )(now,'3169','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_159_NBLeveloutput0_0','2019-09-18 20:50:33','2019-09-18 20:50:02','0' )(now,'3170','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_160_NBLeveloutput1_1','2019-09-18 20:50:33','2019-09-18 20:50:02','0' )(now,'3171','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_141_NBBattery_0','2019-09-18 20:50:33','2019-09-18 20:50:02','242' )(now,'3172','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_224_WaterUpper_0','2019-09-18 20:50:34','2019-09-18 20:50:02','1' )(now,'3173','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_225_WaterLower_0','2019-09-18 20:50:34','2019-09-18 20:50:02','0.85' )(now,'3174','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_255_WLStopLower_0','2019-09-18 20:50:34','2019-09-18 20:50:02','0.5' )(now,'3175','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_235_ControlMode_0','2019-09-18 20:50:34','2019-09-18 20:50:02','1' )(now,'3176','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_261_WLAutomaticRemote_0','2019-09-18 20:50:34','2019-09-18 20:50:02','1' )(now,'3177','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_257_WLPump1Fault_0','2019-09-18 20:50:34','2019-09-18 20:50:02','0' )(now,'3178','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_258_WLPump2Fault_0','2019-09-18 20:50:34','2019-09-18 20:50:02','0' )(now,'3179','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_259_WLPump1Enable_0','2019-09-18 20:50:34','2019-09-18 20:50:02','0' )(now,'3180','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_260_WLPump2Enable_0','2019-09-18 20:50:34','2019-09-18 20:50:02','1' )(now,'3181','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_282_WLYeWei_1','2019-09-18 20:50:35','2019-09-18 20:50:03','0.678' )(now,'3182','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_197_ModbusH2S_2','2019-09-18 20:50:02','2019-09-18 20:50:04','0' )(now,'3183','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_143_NBCurrentDetection0_0','2019-09-18 20:52:49','2019-09-18 20:52:17','0.102' )(now,'3184','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_144_NBCurrentDetection1_1','2019-09-18 20:52:49','2019-09-18 20:52:17','0.139' )(now,'3185','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_151_NBLevelDetection0_0','2019-09-18 20:52:49','2019-09-18 20:52:17','0' )(now,'3186','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_152_NBLevelDetection1_1','2019-09-18 20:52:49','2019-09-18 20:52:17','1' )(now,'3187','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_153_NBLevelDetection2_2','2019-09-18 20:52:49','2019-09-18 20:52:17','1' )(now,'3188','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_154_NBLevelDetection3_3','2019-09-18 20:52:49','2019-09-18 20:52:17','1' )(now,'3189','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_159_NBLeveloutput0_0','2019-09-18 20:52:49','2019-09-18 20:52:17','0' )(now,'3190','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_160_NBLeveloutput1_1','2019-09-18 20:52:49','2019-09-18 20:52:17','0' )(now,'3191','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_141_NBBattery_0','2019-09-18 20:52:49','2019-09-18 20:52:17','242' )(now,'3192','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_224_WaterUpper_0','2019-09-18 20:52:50','2019-09-18 20:52:18','1' )(now,'3193','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_225_WaterLower_0','2019-09-18 20:52:50','2019-09-18 20:52:18','0.85' )(now,'3194','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_255_WLStopLower_0','2019-09-18 20:52:50','2019-09-18 20:52:18','0.5' )(now,'3195','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_235_ControlMode_0','2019-09-18 20:52:50','2019-09-18 20:52:18','1' )(now,'3196','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_261_WLAutomaticRemote_0','2019-09-18 20:52:50','2019-09-18 20:52:18','1' )(now,'3197','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_257_WLPump1Fault_0','2019-09-18 20:52:50','2019-09-18 20:52:18','0' )(now,'3198','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_258_WLPump2Fault_0','2019-09-18 20:52:50','2019-09-18 20:52:18','0' )(now,'3199','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_259_WLPump1Enable_0','2019-09-18 20:52:50','2019-09-18 20:52:18','0' )(now,'3200','0d47383231343730009deb2e03a8f2fa','0d47383231343730009deb2e03a8f2fa_2_260_WLPump2Enable_0','2019-09-18 20:52:50','2019-09-18 20:52:18','1' );
插入完成----2 第 3100条

**Comment by wzf55555** [comment]
时间戳那一列默认写0，一条都插入不进去

**Comment by Shawshank-Smile** [comment]
if all is "now"，It seams to be one row for TDengine.

**Comment by wzf55555** [comment]
目前的情况是，我需要把我们mysql库中的部分数据通过程序导入到td库中。第一列指定不同时间也插入不进去，指定now更插入不进去。


sql.append("('");
						sql.append(currentTime).append("','");//自己指定时间
						
//						sql.append("(");
//						sql.append(0).append(",'");//官方文档中：如果时间戳为0，系统将自动使用服务器当前时间作为该记录的时间戳
						
//						sql.append("(");
//						sql.append("now").append(",'");

第一列修改了3种方式。。。。。
始终不能把从mysql中的数据全部导入到tdengine中。

**Comment by Shawshank-Smile** [comment]
武总，刚刚微信语音您没有接到。import的功能是没有问题的。建议看看mysql查出来的数据是否完整，逐条插入不着急。可能有些sql出了问题，导致后面的插不进去。

**Comment by plum-lihui** [comment]
在一个import或insert语句中，同时插入多条记录，如果都使用now，表示取系统时间。由于处理很快，几乎所有记录都会取成系统的时间。这样在进行插入的时候，就会认为是相同时间戳的记录，从而丢弃后面同样时间戳的记录。
tdengine 是使用第一个时间戳字段做为关键索引的，是不能重复的。

**Comment by wzf55555** [comment]
确实是时间戳导致的问题。
解决方式：
创建库的时候指定时间戳列为“微妙”级别，插入的数据没有出现丢的问题。
create database demo precision'us';

**Comment by Shawshank-Smile** [comment]
时间戳重复很多。import函数非常稳定。
