### ISSUE TITLE
grafana v9: can't connect with tdengine plugin.      tdengine插件连接错误

### ISSUE THREAD

**Issue by ElseStudio** [taosdata/TDengine#14903]
i use tdengine plugin to connect taos and get error “Bad Gateway”，
![image](https://user-images.githubusercontent.com/27198507/178944323-d78e3edb-61eb-456b-8197-e9b2440fe295.png)

grafanna.log
![image](https://user-images.githubusercontent.com/27198507/178944235-e5a1d9fc-f052-4661-befd-d625e31bfc34.png)

but i access the db server with taos shell.
![image](https://user-images.githubusercontent.com/27198507/178943503-f4e38822-6cbf-4251-b929-565693da9bad.png)

使用的grafana9，和服务器在同一内网，tdengine插件连接无法通过，但是taos客户端工具可以访问操作，不知道问题在哪？

**Comment by fenghuazzm** [comment]
服务器上的 taosadapter 服务开了吗？

**Comment by ElseStudio** [comment]
> 服务器上的 taosadapter 服务开了吗？

谢谢您的回复，原来最近开发更新了tdengine版本，需要手动开启。开启后，正常了。
