### ISSUE TITLE
Error reported when starting my Java program：A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by shanlanCoding** [taosdata/TDengine#1503]
**Bug Description**
通过java -jar 启动jar包，windows正常。Linux会报错：
A fatal error has been detected by the Java Runtime Environment:
[查了相关的资料，和JDBC有关系，我怀疑是不是taosd是jdbc驱动导致的。](https://stackoverflow.com/questions/40638312/a-fatal-error-has-been-detected-by-the-java-runtime-environment-when-running-j)

**To Reproduce**
1. java -jar stream-data-storage-service-0.0.1-SNAPSHOT.jar

2.  报错如下：
```shell
java.library.path:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fe22eda7273, pid=1814, tid=0x00007fe1f09af700
#
# JRE version: OpenJDK Runtime Environment (8.0_242-b08) (build 1.8.0_242-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.242-b08 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [librt.so.1+0x4273]  timer_settime+0x3
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /root/hs_err_pid1814.log
2020-04-03 17:04:49.556  INFO 1814 --- [           main] c.t.i.s.TDengine.TDengineTool            : 00600001 ??TDengineTool????
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Aborted

```

**Expected Behavior**
windows能正常启动，同时希望Linux正常启动。

**Screenshots**
![image](https://user-images.githubusercontent.com/44717382/78343481-7a5ecc80-75cd-11ea-91e1-3d345cb455fb.png)

**Environment (please complete the following information):**
 - OS: [Debian 6.3.0]
 - Memory 2GB , CPU 2, current Disk Space 20GB
 - TDengine Version [ 1.6.5.6 ]

**Additional Context**

**Comment by Shawshank-Smile** [comment]
As we konw, I really think it's the problem of your evil VM system. Try on another machine please.

**Comment by shanlanCoding** [comment]
> As we konw, I really think it's the problem of your evil VM system. Try on another machine please.

Thank you. It is. I replaced the operating system and the problem was solved. I think as long as the jdbc driver of taosd is installed, it can be used normally. I didn't expect that the system also supports the installation of tdengine.😁
