### ISSUE TITLE
SQL query result is different from actual

### ISSUE THREAD

**Issue by qubbei** [taosdata/TDengine#15035]
**Bug Description**
sql： select * from s_point_status_22 where collect_day = 20220624 and business_sn in ('c0ev8tgo3u') and status in (1,2,3);
实际结果：把其他的business_sn、status  也查询出来了。
如果把最后的status条件去掉，可以正常查询

**To Reproduce**
1. taos shell 连接
2. 进入到指定的库，然后执行sql

**Expected Behavior**
数据库的基本功能、基本操作能正常使用

**Screenshots**
![image](https://user-images.githubusercontent.com/65695459/179437790-06df4875-9e50-413b-a648-5069d2fe52c2.png)
**Environment (please complete the following information):**
 - OS: [Linux version 3.10.0-1160.45.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Wed Oct 13 17:20:51 UTC 2021]
 - Memory, CPU, current Disk Space
 - TDengine Version [2.6.0.4]

**Additional Context**

**Comment by fenghuazzm** [comment]
我在 2.6.0.6 上没复现，可以升级到 2.6 最新版试试。
有用户在 2.6.0.x 最初的几个版本遇到过，升级后就没出现了。
