### ISSUE TITLE
Failed To Query Max() From Table

### ISSUE THREAD

**Issue by wangfeng-szsh** [taosdata/TDengine#1505]
![failed_udp](https://user-images.githubusercontent.com/62975847/78416373-f05d4500-765a-11ea-85b9-e84a23d4d809.jpg)
![failed_tcp](https://user-images.githubusercontent.com/62975847/78416376-f521f900-765a-11ea-86e3-4a645a4652c4.jpg)

**Comment by Shawshank-Smile** [comment]
Can't see the picture. we will solve this by Teamviewer.

**Comment by Shawshank-Smile** [comment]
my wechat is 13720014098

**Comment by Shawshank-Smile** [comment]
Try 1.6.5.7, Please.

**Comment by Shawshank-Smile** [comment]
According to your log， your data file has been broken。
