### ISSUE TITLE
Tag field merges rows

### ISSUE THREAD

**Issue by weiwxg** [taosdata/TDengine#15094]
表1：
| a | b | c |
|:--:|:--:|:--:|
| a1 | b1 | c1 |
| a1 | b1 | c2 |
| a2 | b2 | c3 |

表2：
| a | b | c |
|:--:|:--:|:--:|
| a1 | b1 | c1, c2 |
| a2 | b2 | c3 |

想从表1转换到表2的结果，其中`a`, `b`, `c`均为`tag`, 有什么sql方案吗？

**Comment by fenghuazzm** [comment]
TDengine 目前还不支持 group_concat 函数，并且 tag 列也不能做一些 concat 操作

**Comment by lxxsjia** [comment]
请问，TDengine 目前支持 group_concat 函数了吗？如未支持，可否有替代方案？
