### ISSUE TITLE
python调用taos, taos.connect（）里面的TDengine server IP address怎么设置，不用默认的？

### ISSUE THREAD

**Issue by Adhders** [taosdata/TDengine#151]
# @host     : TDengine server IP address 
    # @user     : Username used to connect to TDengine server
    # @password : Password 
这些参数怎么设置啊？
我用mysql的方法 update user set user="XXX" where user="root"; 行不通啊

**Comment by StoneT2000** [comment]
```python
conn = taos.connect(host = "your.server.ip", 
                    user= "your_user_name", 
                    password = "your_password", 
                    config ="config_location")
```
就可以了

**Comment by hzcheng** [comment]
@Adhders 您可以在python的shell中import taos，然后运行help(taos.connect)来查看关于connect的文档。假设您要连接在机器192.168.1.132机器上启动的TDengine服务端，可以用如下connect命令：
```
conn = taos.connect(host='192.168.1.132')
```

**Comment by Adhders** [comment]
> @Adhders 您可以在python的shell中import taos，然后运行help(taos.connect)来查看关于connect的文档。假设您要连接在机器192.168.1.132机器上启动的TDengine服务端，可以用如下connect命令：
> 
> ```
> conn = taos.connect(host='192.168.1.132')

> 谢谢您的回复，我昨天就试了，不行啊，返回taos.error.ProgrammingError: login disconnected, login again

我们服务器的地址是58.247.8.190，端口是30022。我密码，用户名无论设置的是否与我们服务器一样，都返回这个错误啊

**Comment by Adhders** [comment]
> ```python
> conn = taos.connect(host = "your.server.ip", 
>                     user = "your_user_name", 
>                     password = "your_password", 
>                     config = "config_location")
> ```
> 
> 就可以了

谢谢您的回复，我昨天就试了，不行啊，返回taos.error.ProgrammingError: login disconnected, login again
我们服务器的地址是58.247.8.190，端口是30022。我密码，用户名无论设置的是否与我们服务器一样，都返回这个错误啊

**Comment by hzcheng** [comment]
@Adhders 您修改的端口是那个端口，是怎么设置的呢？如果问题还无法解决，您可以直接通过邮件hzcheng@taosdata.com联系我，我帮您看一下。
