### ISSUE TITLE
The query result is inconsistent with the expected result

### ISSUE THREAD

**Issue by uunao** [taosdata/TDengine#15112]
如图,只查询status in(1,2,3)  会把status=4的查询出来
![image](https://user-images.githubusercontent.com/25587281/179683093-cdfe2fdb-894e-495b-a014-bc887265e4b9.png)

**Comment by fenghuazzm** [comment]
咱们是什么版本

**Comment by uunao** [comment]
2.4.0.7 和2.6.0.4 都这样

**Comment by fenghuazzm** [comment]
https://github.com/taosdata/TDengine/issues/15035

**Comment by uunao** [comment]
感谢
