### ISSUE TITLE
Order of super table queries

### ISSUE THREAD

**Issue by guanyiming** [taosdata/TDengine#15119]
请问，超级表查询顺序是什么样的？是把所有子表的数据都按时间正序排序，还是单纯的将子表的数据整合在一起了

**Comment by fenghuazzm** [comment]
查询超级表这个有随机性，随机 vnode(dnode) 返回的结果就是最终结果。
至于 vnode 是如何存储数据的，请看下文档技术内幕部分。

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
