### ISSUE TITLE
Failed to start TDengine server service.

### ISSUE THREAD

**Issue by defineconst** [taosdata/TDengine#15115]
**Bug Description**
Linux重启了一下，TDengine服务不能启动了。

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS:CentOS Linux release 7.6.1810 (Core)
 - Memory, CPU, current Disk Space
 - TDengine Version TDengine-server-2.6.0.8-Linux-x64

[root@h1 ~]# systemctl status taosd
● taosd.service - TDengine server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Tue 2022-07-19 14:46:04 CST; 4min 23s ago
  Process: 9491 ExecStart=/usr/bin/taosd (code=exited, status=1/FAILURE)
  Process: 9478 ExecStartPre=/usr/local/taos/bin/startPre.sh (code=exited, status=0/SUCCESS)
 Main PID: 9491 (code=exited, status=1/FAILURE)

Jul 19 14:46:04 h1 systemd[1]: Unit taosd.service entered failed state.
Jul 19 14:46:04 h1 systemd[1]: taosd.service failed.
Jul 19 14:46:04 h1 systemd[1]: taosd.service holdoff time over, scheduling restart.
Jul 19 14:46:04 h1 systemd[1]: Stopped TDengine server service.
Jul 19 14:46:04 h1 systemd[1]: start request repeated too quickly for taosd.service
Jul 19 14:46:04 h1 systemd[1]: Failed to start TDengine server service.
Jul 19 14:46:04 h1 systemd[1]: Unit taosd.service entered failed state.
Jul 19 14:46:04 h1 systemd[1]: taosd.service failed.

[root@h1 ~]# cat  /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
[root@h1 ~]# df -ah
Filesystem               Size  Used Avail Use% Mounted on
rootfs                      -     -     -    - /
sysfs                       0     0     0    - /sys
proc                        0     0     0    - /proc
devtmpfs                 3.8G     0  3.8G   0% /dev
securityfs                  0     0     0    - /sys/kernel/security
tmpfs                    3.9G     0  3.9G   0% /dev/shm
devpts                      0     0     0    - /dev/pts
tmpfs                    3.9G   12M  3.8G   1% /run
tmpfs                    3.9G     0  3.9G   0% /sys/fs/cgroup
cgroup                      0     0     0    - /sys/fs/cgroup/systemd
pstore                      0     0     0    - /sys/fs/pstore
cgroup                      0     0     0    - /sys/fs/cgroup/pids
cgroup                      0     0     0    - /sys/fs/cgroup/cpu,cpuacct
cgroup                      0     0     0    - /sys/fs/cgroup/net_cls,net_prio
cgroup                      0     0     0    - /sys/fs/cgroup/hugetlb
cgroup                      0     0     0    - /sys/fs/cgroup/devices
cgroup                      0     0     0    - /sys/fs/cgroup/cpuset
cgroup                      0     0     0    - /sys/fs/cgroup/blkio
cgroup                      0     0     0    - /sys/fs/cgroup/perf_event
cgroup                      0     0     0    - /sys/fs/cgroup/memory
cgroup                      0     0     0    - /sys/fs/cgroup/freezer
configfs                    0     0     0    - /sys/kernel/config
/dev/mapper/centos-root   35G  8.4G   27G  24% /
selinuxfs                   0     0     0    - /sys/fs/selinux
systemd-1                   0     0     0    - /proc/sys/fs/binfmt_misc
hugetlbfs                   0     0     0    - /dev/hugepages
debugfs                     0     0     0    - /sys/kernel/debug
mqueue                      0     0     0    - /dev/mqueue
/dev/sda1               1014M  146M  869M  15% /boot
tmpfs                    781M     0  781M   0% /run/user/0
[root@h1 ~]# free -m
              total        used        free      shared  buff/cache   available
Mem:           7803         140        7491          11         171        7416
Swap:          4095           0        4095
[root@h1 ~]# cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c
      4  Intel(R) Xeon(R) E-2224G CPU @ 3.50GHz
[root@h1 ~]#  cat /proc/cpuinfo | grep physical | uniq -c
      1 physical id     : 0
      1 address sizes   : 45 bits physical, 48 bits virtual
      1 physical id     : 0
      1 address sizes   : 45 bits physical, 48 bits virtual
      1 physical id     : 0
      1 address sizes   : 45 bits physical, 48 bits virtual
      1 physical id     : 0
      1 address sizes   : 45 bits physical, 48 bits virtual
[root@h1 ~]# ps aux
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          1  0.1  0.0 128040  6696 ?        Ss   14:45   0:01 /usr/lib/systemd/systemd --switched-root --system --deserialize 22
root          2  0.0  0.0      0     0 ?        S    14:45   0:00 [kthreadd]
root          3  0.0  0.0      0     0 ?        S    14:45   0:00 [ksoftirqd/0]
root          5  0.0  0.0      0     0 ?        S<   14:45   0:00 [kworker/0:0H]
root          6  0.0  0.0      0     0 ?        S    14:45   0:00 [kworker/u256:0]
root          7  0.0  0.0      0     0 ?        S    14:45   0:00 [migration/0]
root          8  0.0  0.0      0     0 ?        S    14:45   0:00 [rcu_bh]
root          9  0.0  0.0      0     0 ?        S    14:45   0:00 [rcu_sched]
root         10  0.0  0.0      0     0 ?        S<   14:45   0:00 [lru-add-drain]
root         11  0.0  0.0      0     0 ?        S    14:45   0:00 [watchdog/0]
root         12  0.0  0.0      0     0 ?        S    14:45   0:00 [watchdog/1]
root         13  0.0  0.0      0     0 ?        S    14:45   0:00 [migration/1]
root         14  0.0  0.0      0     0 ?        S    14:45   0:00 [ksoftirqd/1]
root         16  0.0  0.0      0     0 ?        S<   14:45   0:00 [kworker/1:0H]
root         17  0.0  0.0      0     0 ?        S    14:45   0:00 [watchdog/2]
root         18  0.0  0.0      0     0 ?        S    14:45   0:00 [migration/2]
root         19  0.0  0.0      0     0 ?        S    14:45   0:00 [ksoftirqd/2]
root         21  0.0  0.0      0     0 ?        S<   14:45   0:00 [kworker/2:0H]
root         22  0.0  0.0      0     0 ?        S    14:45   0:00 [watchdog/3]
root         23  0.0  0.0      0     0 ?        S    14:45   0:00 [migration/3]
root         24  0.0  0.0      0     0 ?        S    14:45   0:00 [ksoftirqd/3]
root         26  0.0  0.0      0     0 ?        S<   14:45   0:00 [kworker/3:0H]
root         28  0.0  0.0      0     0 ?        S    14:45   0:00 [kdevtmpfs]
root         29  0.0  0.0      0     0 ?        S<   14:45   0:00 [netns]
root         30  0.0  0.0      0     0 ?        S    14:45   0:00 [khungtaskd]
root         31  0.0  0.0      0     0 ?        S<   14:45   0:00 [writeback]
root         32  0.0  0.0      0     0 ?        S<   14:45   0:00 [kintegrityd]
root         33  0.0  0.0      0     0 ?        S<   14:45   0:00 [bioset]
root         34  0.0  0.0      0     0 ?        S<   14:45   0:00 [bioset]
root         35  0.0  0.0      0     0 ?        S<   14:45   0:00 [bioset]
root         36  0.0  0.0      0     0 ?        S<   14:45   0:00 [kblockd]
root         37  0.0  0.0      0     0 ?        S<   14:45   0:00 [md]
root         38  0.0  0.0      0     0 ?        S<   14:45   0:00 [edac-poller]
root         39  0.0  0.0      0     0 ?        S<   14:45   0:00 [watchdogd]
root         40  0.0  0.0      0     0 ?        S    14:45   0:00 [kworker/3:1]
root         41  0.0  0.0      0     0 ?        S    14:45   0:00 [kworker/2:1]
root         46  0.0  0.0      0     0 ?        S    14:45   0:00 [kswapd0]
root         47  0.0  0.0      0     0 ?        SN   14:45   0:00 [ksmd]
root         48  0.0  0.0      0     0 ?        SN   14:45   0:00 [khugepaged]
root         49  0.0  0.0      0     0 ?        S<   14:45   0:00 [crypto]
root         57  0.0  0.0      0     0 ?        S<   14:45   0:00 [kthrotld]
root         59  0.0  0.0      0     0 ?        S<   14:45   0:00 [kmpath_rdacd]
root         60  0.0  0.0      0     0 ?        S<   14:45   0:00 [kaluad]
root         61  0.0  0.0      0     0 ?        S    14:45   0:00 [kworker/1:1]
root         62  0.0  0.0      0     0 ?        S    14:45   0:00 [kworker/0:1]
root         63  0.0  0.0      0     0 ?        S<   14:45   0:00 [kpsmoused]
root         64  0.0  0.0      0     0 ?        S    14:45   0:00 [kworker/0:2]
root         65  0.0  0.0      0     0 ?        S<   14:45   0:00 [ipv6_addrconf]
root         78  0.0  0.0      0     0 ?        S<   14:45   0:00 [deferwq]
root        110  0.0  0.0      0     0 ?        S    14:45   0:00 [kauditd]
root        502  0.0  0.0      0     0 ?        S    14:45   0:00 [kworker/1:2]
root       2519  0.0  0.0      0     0 ?        S<   14:45   0:00 [nfit]
root       2945  0.0  0.0      0     0 ?        S<   14:45   0:00 [ata_sff]
root       2953  0.0  0.0      0     0 ?        S<   14:45   0:00 [mpt_poll_0]
root       2956  0.0  0.0      0     0 ?        S<   14:45   0:00 [mpt/0]
root       3270  0.0  0.0      0     0 ?        S    14:45   0:00 [scsi_eh_0]
root       3277  0.0  0.0      0     0 ?        S<   14:45   0:00 [scsi_tmf_0]
root       3372  0.0  0.0      0     0 ?        S    14:45   0:00 [kworker/u256:2]
root       3387  0.0  0.0      0     0 ?        S    14:45   0:00 [scsi_eh_1]
root       3393  0.0  0.0      0     0 ?        S<   14:45   0:00 [scsi_tmf_1]
root       3394  0.0  0.0      0     0 ?        S    14:45   0:00 [scsi_eh_2]
root       3395  0.0  0.0      0     0 ?        S<   14:45   0:00 [scsi_tmf_2]
root       3402  0.0  0.0      0     0 ?        S<   14:45   0:00 [ttm_swap]
root       3409  0.0  0.0      0     0 ?        S    14:45   0:00 [irq/16-vmwgfx]
root       3690  0.0  0.0      0     0 ?        S    14:45   0:00 [kworker/3:2]
root       4371  0.0  0.0      0     0 ?        S<   14:46   0:00 [kdmflush]
root       4374  0.0  0.0      0     0 ?        S<   14:46   0:00 [bioset]
root       4387  0.0  0.0      0     0 ?        S<   14:46   0:00 [kdmflush]
root       4389  0.0  0.0      0     0 ?        S<   14:46   0:00 [bioset]
root       4407  0.0  0.0      0     0 ?        S<   14:46   0:00 [bioset]
root       4412  0.0  0.0      0     0 ?        S<   14:46   0:00 [xfsalloc]
root       4421  0.0  0.0      0     0 ?        S<   14:46   0:00 [xfs_mru_cache]
root       4425  0.0  0.0      0     0 ?        S<   14:46   0:00 [xfs-buf/dm-0]
root       4427  0.0  0.0      0     0 ?        S<   14:46   0:00 [xfs-data/dm-0]
root       4428  0.0  0.0      0     0 ?        S<   14:46   0:00 [xfs-conv/dm-0]
root       4429  0.0  0.0      0     0 ?        S<   14:46   0:00 [xfs-cil/dm-0]
root       4430  0.0  0.0      0     0 ?        S<   14:46   0:00 [xfs-reclaim/dm-]
root       4431  0.0  0.0      0     0 ?        S<   14:46   0:00 [xfs-log/dm-0]
root       4432  0.0  0.0      0     0 ?        S<   14:46   0:00 [xfs-eofblocks/d]
root       4433  0.0  0.0      0     0 ?        S    14:46   0:00 [xfsaild/dm-0]
root       4434  0.0  0.0      0     0 ?        S<   14:46   0:00 [kworker/0:1H]
root       4503  0.0  0.0  39080  3564 ?        Ss   14:46   0:00 /usr/lib/systemd/systemd-journald
root       4519  0.0  0.0 192920  6208 ?        Ss   14:46   0:00 /usr/sbin/lvmetad -f
root       4526  0.0  0.0  49036  6456 ?        Ss   14:46   0:00 /usr/lib/systemd/systemd-udevd
root       7621  0.0  0.0      0     0 ?        S<   14:46   0:00 [xfs-buf/sda1]
root       7622  0.0  0.0      0     0 ?        S<   14:46   0:00 [xfs-data/sda1]
root       7631  0.0  0.0      0     0 ?        S<   14:46   0:00 [xfs-conv/sda1]
root       7647  0.0  0.0      0     0 ?        S<   14:46   0:00 [xfs-cil/sda1]
root       7656  0.0  0.0      0     0 ?        S<   14:46   0:00 [xfs-reclaim/sda]
root       7662  0.0  0.0      0     0 ?        S<   14:46   0:00 [xfs-log/sda1]
root       7678  0.0  0.0      0     0 ?        S<   14:46   0:00 [xfs-eofblocks/s]
root       7695  0.0  0.0      0     0 ?        S    14:46   0:00 [xfsaild/sda1]
root       8476  0.0  0.0  55532   860 ?        S<sl 14:46   0:00 /sbin/auditd
polkitd    8832  0.0  0.1 612240 12104 ?        Ssl  14:46   0:00 /usr/lib/polkit-1/polkitd --no-debug
root       8834  0.0  0.0  21680  1316 ?        Ss   14:46   0:00 /usr/sbin/irqbalance --foreground
dbus       8836  0.0  0.0  66468  2564 ?        Ssl  14:46   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
chrony     8840  0.0  0.0 117792  1740 ?        S    14:46   0:00 /usr/sbin/chronyd
root       8849  0.0  0.1 476028  8584 ?        Ssl  14:46   0:00 /usr/sbin/NetworkManager --no-daemon
root       8850  0.0  0.0  26380  1760 ?        Ss   14:46   0:00 /usr/lib/systemd/systemd-logind
root       8859  0.0  0.0 126384  1660 ?        Ss   14:46   0:00 /usr/sbin/crond -n
root       8923  0.0  0.0 110208   864 tty1     Ss+  14:46   0:00 /sbin/agetty --noclear tty1 linux
root       9155  0.0  0.2 574040 19304 ?        Ssl  14:46   0:00 /usr/bin/python2 -Es /usr/sbin/tuned -l -P
root       9156  0.0  0.0 112872  4320 ?        Ss   14:46   0:00 /usr/sbin/sshd -D
root       9159  0.0  0.0 216416  5604 ?        Ssl  14:46   0:00 /usr/sbin/rsyslogd -n
root       9470  0.0  0.0  89664  2128 ?        Ss   14:46   0:00 /usr/libexec/postfix/master -w
postfix    9476  0.0  0.0  89768  4072 ?        S    14:46   0:00 pickup -l -t unix -u
postfix    9477  0.0  0.0  89836  4100 ?        S    14:46   0:00 qmgr -l -t unix -u
root       9704  0.0  0.0      0     0 ?        S<   14:46   0:00 [kworker/1:1H]
root       9706  0.0  0.0      0     0 ?        S<   14:46   0:00 [kworker/3:1H]
root       9711  0.0  0.0      0     0 ?        S<   14:46   0:00 [kworker/2:1H]
root       9712  0.0  0.0 159208  5924 ?        Ds   14:48   0:00 sshd: root@pts/0
root       9716  0.0  0.0 158876  5500 ?        Ss   14:48   0:00 sshd: root@notty
root       9720  0.0  0.0  72208  2872 ?        Ss   14:48   0:00 /usr/libexec/openssh/sftp-server
root       9725  0.0  0.0 115544  2024 pts/0    Ss   14:48   0:00 -bash
root       9744  0.0  0.0      0     0 ?        S    14:50   0:00 [kworker/0:0]
root       9745  0.0  0.0      0     0 ?        S    14:51   0:00 [kworker/2:0]
root       9764  0.0  0.0      0     0 ?        R    15:01   0:00 [kworker/2:2]
root       9818  0.0  0.0 155468  1868 pts/0    R+   15:02   0:00 ps aux
[root@h1 ~]#

**Additional Context**

**Comment by fenghuazzm** [comment]
看下 taosdlog 日志下有什么 error
