### ISSUE TITLE
哪里可以找到《TDengine 2.0 查询模块设计》

### ISSUE THREAD

**Issue by jcwangxp** [taosdata/TDengine#15135]
https://docs.taosdata.com/tdinternal/taosd

Query 模块
该模块负责整体系统的查询处理。客户端调用该该模块进行 SQL 语法解析，并将查询或写入请求发送到 vnode ，同时负责针对超级表的查询进行二阶段的聚合操作。在 vnode 端，该模块调用 TSDB 模块读取系统中存储的数据进行查询处理。query 模块还定义了系统能够支持的全部查询函数，查询函数的实现机制与查询框架无耦合，可以在不修改查询流程的情况下动态增加查询函数。详细的设计请参见《TDengine 2.0 查询模块设计》。

《TDengine 2.0 查询模块设计》这个文档没有找到

**Comment by fenghuazzm** [comment]
感谢反馈，我们内部沟通了一下，因为一直以来这个模块变化较大，需要调整的地方较多，为防止误导用户，修改完之前暂时不对外公布了。
