### ISSUE TITLE
The Python client uses multi-process 

### ISSUE THREAD

**Issue by 0x55aa** [taosdata/TDengine#15166]
**Bug Description**

下方有测试代码，如果在多进程启动前不建立连接，多进程建立连接没问题。如果多进程启动前建立连接，多进程里就会hang住。不知道啥原因。

**To Reproduce**
1. 注释下面代码的，多进程前的连接代码，运行没问题。
2. 去掉注释，再运行有问题。
3. 加上注释，又没问题。

**Expected Behavior**

应该运行都没问题。

**code**

```
from multiprocessing import Process

import taos


def insert_process(p_num):
    print(11)
    conn = taos.connect(
        host="127.0.0.1",
        user="root",
        password="taosdata",
        database="db_benchmark",
        port=6030,
    )
    print(22)
    print(conn)
    return conn

# 需要打开和注释的代码
# conn = insert_process(1)
# conn.close()
conn = insert_process(1)
conn.close()

ps = []
for i in range(2):
    p = Process(target=insert_process, args=(i, ), daemon=True)
    ps.append(p)

for p in ps:
    p.start()
for p in ps:
    p.join()
```

**Environment (please complete the following information):**
 - OS: ubuntu 22.04 桌面版
 - Memory, CPU, current Disk Space
 - TDengine Version 2.6.0.8

**Additional Context**

**Comment by dingbo8128** [comment]
这是已知问题，建议每个子进程单独建立连接，不在父进程建立连接

**Comment by 0x55aa** [comment]
这个问题会修复吗？

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
