### ISSUE TITLE
springboot + tdengine，Rollback transaction using @transactional is not valid

### ISSUE THREAD

**Issue by wmjie666** [taosdata/TDengine#15200]
springboot + mybatis + tdengine，在service层的方法上使用@Transactional(rollbackFor = Exception.class)，当方法执行抛出异常后，方法中对tdengine的成功操作没有回滚。

部分代码如下：

    @Test
    public void modifySubTableTag(){
        LinkedHashMap<String, Object> tagsMap = new LinkedHashMap<>();
        tagsMap.put("location", "a1");     //
        tagsMap.put("groupId", "b");      //groupId是int类型，会报错

        tdEngineService.modifySubTableTag("t1_sub", tagsMap);
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public void modifySubTableTag(String tableName, LinkedHashMap<String, Object> tagsMap) {
        try {
            tagsMap.forEach((key, value) -> tdEngineDao.modifySubTableTag(tableName, key, value));
        }catch (Exception e){
            throw new RuntimeException("出错了");
        }
    }

<img width="700" alt="image" src="https://user-images.githubusercontent.com/9477969/179943704-05e87227-1e6d-4455-8a84-99715bf2c2e7.png">

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/9477969/179943755-72395618-5f54-4770-a5e0-a0c293ec0a5a.png">

<img width="676" alt="image" src="https://user-images.githubusercontent.com/9477969/179943584-520af0ed-9f67-4ad3-8953-61b28894cab1.png">

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/9477969/179943887-646074fc-3bc5-4834-b49d-65765268c476.png">

**Comment by fenghuazzm** [comment]
TDengine 的存储引擎目前不支持事务处理

**Comment by wmjie666** [comment]
> 

请问有计划什么时候推出事务支持吗

**Comment by fenghuazzm** [comment]
短期内应该不会推出的，目前是能保证最终一致性
