### ISSUE TITLE
TDengine ERROR (80000503): Invalid Vgroup ID

### ISSUE THREAD

**Issue by hubwu** [taosdata/TDengine#15229]
**Bug Description**
之前是单机安装，使用时没有问题，昨天整了个集群，当时就报 database is balancing，就无法插数据了，今天做插入能用了，但做查询时报这个错
org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [select tbname as vehicle_id,* from t_veh_data where company_id = ? and tbname = ? and create_time >= ? and create_time<= ?]; SQL state []; error code [-2147482365]; TDengine ERROR (80000503): Invalid Vgroup ID; nested exception is java.sql.SQLException: TDengine ERROR (80000503): Invalid Vgroup ID

在taos客户端查询又是OK的，这是什么个情况呢？

**Comment by hubwu** [comment]
集群是在原来的一个节点的基础上新增两个节点.
taos> show dnodes;
   id   |           end_point            | vnodes | cores  |   status   | role  |       create_time       |      offline reason      |
======================================================================================================================================
      1 | ubuntu-192:6030                |      0 |      4 | ready      | any   | 2022-07-04 19:51:54.251 |                          |
      2 | ubuntu-191:6030                |      1 |      2 | ready      | any   | 2022-07-20 16:36:59.904 |                          |
      3 | ubuntu-193:6030                |      2 |      4 | ready      | any   | 2022-07-20 16:37:08.194 |                          |
Query OK, 3 row(s) in set (0.003511s)

**Comment by fenghuazzm** [comment]
咱们 TDengine 是什么版本？是 docker 部署的吗
Invalid Vgroup ID 这个报错比较复杂

**Comment by hubwu** [comment]
版本是TDengine-server-2.6.0.8，一个节点是在linux服务器上，另两个是在两个虚拟机里面。
后面我修改了副本数，就不报这个错了。

现在我有个问题，查询3600条数据，估计十几M，查询时间有时需要7-8秒，有时需要20秒，三个结点的集群会慢成这样吗？还是我用错了？

DruidDataSource dataSource = new DruidDataSource();
dataSource.setDriverClassName("com.taosdata.jdbc.TSDBDriver");
dataSource.setUsername(taosUserName);
dataSource.setPassword(taosPassword);
dataSource.setUrl(taosUrl);
dataSource.setInitialSize(2);
dataSource.setMinIdle(30);
dataSource.setMaxActive(50);
dataSource.setMaxWait(60000);
dataSource.setValidationQuery("select server_status()");
Properties connProps = new Properties();
connProps.setProperty(TSDBDriver.PROPERTY_KEY_BATCH_LOAD, "true");
connProps.setProperty(TSDBDriver.PROPERTY_KEY_CHARSET, "UTF-8");
connProps.setProperty(TSDBDriver.PROPERTY_KEY_LOCALE, "en_US.UTF-8");
connProps.setProperty(TSDBDriver.PROPERTY_KEY_TIME_ZONE, "UTC-8");
dataSource.setConnectionProperties(connProps.toString());
return dataSource;
数据源，用JDBCTemplate执行查询return jdbcTemplate.query(sql, (rs, rowNum) -> {
            Long start2Time = System.currentTimeMillis();
            Map<String, Object> map = TaosRowUtil.resultSetToMap(rs);
            Long endTime = System.currentTimeMillis();
            return map;
        });



***@***.***
 
From: Zhengmao Zhu
Date: 2022-07-21 15:13
To: taosdata/TDengine
CC: hubwu; Author
Subject: Re: [taosdata/TDengine] TDengine ERROR (80000503): Invalid Vgroup ID (Issue #15229)
咱们 TDengine 是什么版本？是 docker 部署的吗
Invalid Vgroup ID 这个报错比较复杂

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
