### ISSUE TITLE
Old version taosdump failed to export data 

### ISSUE THREAD

**Issue by hufeng-tany** [taosdata/TDengine#15226]
异常描述：
1.taosdump多线程连接taos数据库是正常的；
2.但是写入导出文件的时候，是单线程操作，可以明显看到，建sql文件->写入数据->写入完成后->再重新新建sql文件；如此写入文件循环，并未见到-T多线程，多文件同时写入时的效果；
3.-D参数配置是，只备份全数据库，能检查到数据库名后的表名，但是不会根据此配置备份，需要按照表备份，不能加-D参数，taosdump文档中未明确注明！！！
复现时注意：单表数据量请多写一点，现象更佳明显
我测试时，单表的数据量是：7天*24小时*3600条（秒级数据）
涛思版本：2.2.0.5

taosdump的命令：
taosdump -h127.0.0.1 -uroot -ptaosdata -P6030 -r /data/bk/2022-07/2022-07-21-08-48-00/dump_reusult.txt -o/data/bk/2022-07/2022-07-21-08-48-00 hzinfo_data yc_1476186448519503874_37715 yx_1476186448519503874_89329 yx_1476186448519503874_89330 yx_1476186448519503874_89331 yx_1476186448519503874_89332 yx_1476186448519503874_89319 yx_1476186448519503874_89320 yx_1476186448519503874_89321 yx_1476186448519503874_89322 yx_1476186448519503874_89323 yx_1476186448519503874_89324 yx_1476186448519503874_89325 yx_1476186448519503874_89360 -T 8 -S 2022-07-20T00:00:00+0800 -E 2022-07-21T00:00:00+0800 -t 500 -B 100

**Comment by sangshuduo** [comment]
这是之前和 TDengine 附带的 taosdump 吧？请使用新的 taosTools 安装包附带的 taosdump

**Comment by hufeng-tany** [comment]
是 安装包里自带的，我升级试试

**Comment by sangshuduo** [comment]
建议 TDengine 也升级到最新版本。2.2 已经比较旧了

**Comment by hufeng-tany** [comment]
> 

TDengine，客户端和服务端，版本必须对应才能使用，升级其实不是很方便；
多出使用了涛思，当前升级版本，对于已有的环境影响很大，无法频繁更新版本。
我们计划3.0有稳定版本后，再计划更新

**Comment by hufeng-tany** [comment]
> 建议TDengine也升级到最新版本。2.2已经比较旧了

请教几个个小问题：
这是官网的一句话
#https://docs.taosdata.com/tdinternal/arch
Taosc taosc 是 TDengine 给应用提供的驱动程序（driver），负责处理应用与集群的接口交互，提供 C/C++ 语言原生接口，内嵌于 JDBC、C#、Python、Go、Node.js 语言连接库里。应用都是通过 taosc 而不是直接连接集群中的数据节点与整个集群进行交互的。
这个模块负责获取并
缓存元数据；
将插入、查询等请求转发到正确的数据节点；在把结果返回给应用时，还需要负责
最后一级的聚合、排序、过滤等操作。
对于 JDBC、C/C++、C#、Python、Go、Node.js 接口而言，这个模块是在应用所处的物理节点上运行。同时，为支持全分布式的 RESTful 接口，taosc 在 TDengine 集群的每个 dnode 上都有一运行实例。

#问题
1.此处：元数据是什么？--是表的全量数据吗？
2.元数据缓存遵循什么样的策略，对于下次查询是否有效；--保存多长时间，对于同表的查询都能共用吗？
3.最后一级的操作，是具体怎么判断最后一级？    
----是where后的所有条件，还是只包括最后一个条件呢？
----若是最后一个条件，之前的筛选过滤条件是在服务端完成后，才传给客户端的吗？
----此处传输的数据，和元数据是一个概念吗

**Comment by sangshuduo** [comment]
> > 
> 
> TDengine，客户端和服务端，版本必须对应才能使用，升级其实不是很方便； 多处使用了涛思，当前升级版本，对于已有的环境影响很大，无法频繁更新版本。 我们计划3.0有稳定版本后，再计划更新

如果只是备份数据可以单独安装 taosTools ，使用其中的 taosdump。但是 taosdump 目前默认使用了一个 2.4 的 escape char 功能，在 2.2 上不工作，需要使用 -n 参数强制不使用这个功能

**Comment by hufeng-tany** [comment]
> > > 
> > 
> > 
> > TDengine，客户端和服务端，版本必须对应才能使用，升级其实不是很方便； 多处使用了涛思，当前升级版本，对于已有的环境影响很大，无法频繁更新版本。 我们计划3.0有稳定版本后，再计划更新
> 
> 如果只是备份数据可以单独安装 taosTools ，使用其中的 taosdump。但是 taosdump 目前默认使用了一个 2.4 的 escape char 功能，在 2.2 上不工作，需要使用 -n 参数强制不使用这个功能

好的，谢谢，我这几天验证一下，看看是否可以丢现场使用。

最近遇到查询的一些问题，一遇到数据量比较大的表，查询效率就会很低，有什么办法分析sql和了解执行过程。类似于mysql的explain的功能的，优化没有思路。
是否有查询筛选，对于网络，硬盘，RAM等资源的占用原理性说明

**Comment by sangshuduo** [comment]
不建议把不同问题在一个 issue 里讨论。其他问题可以提交到一个新的 issue 里，如果是深入讨论，建议考虑企业支持服务。

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
