### ISSUE TITLE
Unable to establish connection

### ISSUE THREAD

**Issue by wujunchengman** [taosdata/TDengine#15291]
```shell
xnxv@debian:/etc/taos$ taos -n clients -h debian
07/22 14:32:33.129510 00018365 UTL check startup, host:debian port:6030

07/22 14:32:33.629768 00018365 UTL step:TDengine desc:initialized successfully
07/22 14:32:33.629813 00018365 UTL check startup finished
xnxv@debian:/etc/taos$ taos -n rpc -h debian
successed to test TCP port:6030
successed to test UDP port:6030
failed to test TCP port:6031
successed to test UDP port:6031
failed to test TCP port:6032
successed to test UDP port:6032
failed to test TCP port:6033
successed to test UDP port:6033
failed to test TCP port:6034
failed to test UDP port:6034
successed to test TCP port:6035
successed to test UDP port:6035
failed to test TCP port:6036
failed to test UDP port:6036
failed to test TCP port:6037
failed to test UDP port:6037
failed to test TCP port:6038
failed to test UDP port:6038
failed to test TCP port:6039
failed to test UDP port:6039
xnxv@debian:/etc/taos$ taos -h debian

Welcome to the TDengine shell from Linux, Client Version:2.6.0.8
Copyright (c) 2022 by TAOS Data, Inc. All rights reserved.

taos connect failed, reason: Unable to establish connection.

xnxv@debian:/etc/taos$

```
系统debian11.4，使用apt安装的最新版

**Comment by fenghuazzm** [comment]
这个网络检测瞅着没通过啊，还有些端口没通

**Comment by wujunchengman** [comment]
跟官网文档的检测结果一样啊

 二、环境中有运行的taosd服务

此时只需要在客户端环境运行 taos客户端测试功能， 通过参数 -n rpc：表示向正在运行的taosd服务发起检测。其他参数与上面完全相同。客户端运行的输出样例：

    plum@plum-VirtualBox ~/git/v20 $ taos -n clients
    host: 127.0.0.1	start port: 6030	end port: 6042	packet len: 1000
    TCP port:6030 test OK		UDP port:6030 test OK
    TCP port:6031 test fail.		udp port:6031 test fail.
    TCP port:6032 test fail.		udp port:6032 test fail.
    TCP port:6033 test fail.		udp port:6033 test fail.
    TCP port:6034 test fail.		udp port:6034 test fail.
    TCP port:6035 test OK		UDP port:6035 test OK
    TCP port:6036 test fail.		udp port:6036 test fail.
    TCP port:6037 test fail.		udp port:6037 test fail.
    TCP port:6038 test fail.		udp port:6038 test fail.
    TCP port:6039 test fail.		udp port:6039 test fail.
    TCP port:6040 test fail.		udp port:6040 test fail.
    TCP port:6041 test fail.		udp port:6041 test fail.
    TCP port:6042 test fail.		udp port:6042 test fail.

表示此时taosd只监听了6030/6035端口，其他端口暂时没有启用。

6041是HTTP模块使用的端口、6042是arbitrator使用的端口，此方法无法检测这两个端口。只能使用第一种方法进行检测。
