### ISSUE TITLE
DB error: invalid operation: group by/session/state_window not allowed on projection query 

### ISSUE THREAD

**Issue by DoubleCoffeeSweet** [taosdata/TDengine#15296]
在命令行中执行 select * from weather group by note;提示如下错误
 DB error: invalid operation: group by/session/state_window not allowed on projection query

**Comment by fenghuazzm** [comment]
要带上聚合函数

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
