### ISSUE TITLE
提议:中文文档支持

### ISSUE THREAD

**Issue by langxj** [taosdata/TDengine#153]
既然中国人要开发的，而且开源了，应当提供中文的文档的说明。阿里、百度等开源项目，基本都有提供中文文档的说明。个人建议，希望采纳。

**Comment by tidyjiang8** [comment]
官网有中文文档: https://www.taosdata.com/cn/documentation/

**Comment by a4651386** [comment]
建议中文位置显眼一点阿

**Comment by plum-lihui** [comment]
好的，我们重新考虑一下页面设计，多谢建议！

**Comment by geffzhang** [comment]
提供一个README.zh-CN.md

**Comment by hiei17** [comment]
config的能不能写详细一点 比如 什么样的情况 建议怎么配置 我看了这个文档 看了白皮书 还是不会配置
