### ISSUE TITLE
Go-taosql-sql

### ISSUE THREAD

**Issue by ZHOUAXING927** [taosdata/TDengine#15393]
**Bug Description**
测试taosql go的驱动 在使用占位符时 拼接时没有加上单引号。

正确拼接  create database if not exists ? precision 'us'  keep 365
实际拼接  create database if not exists ? precision us  keep 365

**Screenshots**
![image](https://user-images.githubusercontent.com/59408787/180740186-ed33fd49-7ff0-491a-81c4-75436ad173ec.png)

**Comment by ZHOUAXING927** [comment]
insert 时候 现在也是不加单引号的

**Comment by huskar-t** [comment]
@ZHOUAXING927 这个是为兼容之前设计，需要手动加上单引号

**Comment by ZHOUAXING927** [comment]
> @ZHOUAXING927这个是为了提前设计，需要手动加上单引号
那还有一个问题是 在插入的时候  insert  into tablename1 values( '10','20')  tablename2 values('20','30'); 
如果values里面不分数据类型 都加上引号 会对效率上有影响吗

**Comment by ZHOUAXING927** [comment]
> @ZHOUAXING927是为了提前设计，需要手动使用这个单引号

还有一个问题 insert into table1 values('10','100') table2 values('10','100') ;
在插入或者查询的时候,不分数据类型 都加上单引号会有什么效率或者其他的影响吗？

**Comment by huskar-t** [comment]
@ZHOUAXING927 只有字符类型需要加单引号，其他加单引号会语法错误

**Comment by ZHOUAXING927** [comment]
> @ZHOUAXING927 只有字符类型需要加单引号，其他加单引号会语法错误
之后你们的驱动应该也不会修改这个把  我们zorm最近在适配td

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
