### ISSUE TITLE
microsecond set cannot work

### ISSUE THREAD

**Issue by OlemEnDBUrEy** [taosdata/TDengine#154]
Q1:
I read the document and Add
enableMicrosecond  1
precision  us
To the /etc/taos/taos.cfg，but each of them can not work,There is no other document.
when I insert the value,I use '2019-07-02 00:00:00.000001',the data in db still  is '2019-07-02 00:00:00.000'
Q2:
If I use millisecond set,I can only insert table max 1000/sec speed? but I want insert about 10000 data in every second

**Comment by johnnyhou327** [comment]
Hi @OlemEnDBUrEy , try configuring the time precision when creating your database, e.g. <pre>create database mydb precision "us";</pre>.

**Comment by plum-lihui** [comment]
Sorry， This configuration parameter has been cancelled in taos.cfg， only can configure the time precision when creating database。
