### ISSUE TITLE
In a cluster environment, when the disk storage of the old node is nearly full, how can I control that data is saved only to the new node after a new node is added

### ISSUE THREAD

**Issue by loveworldlovesky** [taosdata/TDengine#15408]
请问社区版能否满足这种场景:
1.手动控制数据分配到各个节点的权重
2.添加新节点后,控制老节点不再继续保存数据仅对外提供查询功能

**Comment by fenghuazzm** [comment]
TDengine 2.x 有这个打分机制决定权重，可以 `show scores\G; `查看各个节点的分数（大概就是 cpu 核数、vnode 个数等），服务会优先在分数低的 dnode 节点上建立 vnode（vgroup），这个机制不能手动控制，但能手动迁移达到你想要的效果（balance 没开时），方法见[手动迁移数据节点](https://docs.taosdata.com/cluster/cluster-mgmt#%E6%89%8B%E5%8A%A8%E8%BF%81%E7%A7%BB%E6%95%B0%E6%8D%AE%E8%8A%82%E7%82%B9)，如果集群 balance 也打开的话，除了以上机制，在不均衡的情况下还会自动迁移 vnode。

**Comment by loveworldlovesky** [comment]
收到,非常感谢

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
