### ISSUE TITLE
hope the TDengine supports SUBSTRING_INDEX function

### ISSUE THREAD

**Issue by Conlin569** [taosdata/TDengine#15419]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the circumstance is and what the associated problem is. Ex. I'm using TDengine for this use case: [...]. But I'm always frustrated when [...]

**Describe your desired behavior**
A clear and concise description of what you want to happen. Ex. I want TDengine to be able to do [...] when I try to do [...] with it.

**Describe your solutions/suggestions if you've any**
A clear and concise description of any solutions/suggestions to this problem or features you've considered.

**Additional context**

**Comment by fenghuazzm** [comment]
暂不支持。大概是什么数据需要这样截取，能说一下需求吗？

**Comment by Colin678** [comment]
结合 grafana 变量的时
grafana变量: '$grafana_var' => '222,APP1,test'
sql 语句 : ${字段}  in ( substring_index('222,APP1,test',',',1) )
