### ISSUE TITLE
Super-table filters TBName is not as efficient as directly querying subtable

### ISSUE THREAD

**Issue by moonService** [taosdata/TDengine#15416]
tbname等于某个值的情况下效率应该和查询子表相同，但实际情况相反，数据量上亿后性能差距在10倍左右

**Comment by fenghuazzm** [comment]
子表数据量上亿吗？目前这超级表内有多少子表了

**Comment by moonService** [comment]
> 子表数据量上亿吗？目前这超级表内有多少子表
总数据量十几亿吧，450w左右的子表数量

**Comment by moonService** [comment]
总数据量十几亿，子表数量450w左右

**Comment by moonService** [comment]
@fenghuazzm 总数据量十几亿，子表数量450w左右

**Comment by moonService** [comment]
> @fenghuazzm 总数据量十几亿，子表数量450w左右

a

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
