### ISSUE TITLE
The TDengine service is down, and the getNumOfRowsInTimeWindow error is reported

### ISSUE THREAD

**Issue by ulike** [taosdata/TDengine#15487]
**Bug Description**
taosd: /home/ubuntu/workroom/jenkins/TDinternal/community/src/query/src/qExecutor.c:835: getNumOfRowsInTimeWindow: Assertion `startPos >= 0 && startPos < pDataBlockInfo->rows' failed.
07/27 21:10:30.661837 00027627 DND shut down signal is 6
07/27 21:10:30.662052 00027627 DND sender PID:27600 cmdline:./taosd

版本：TDengine-server-2.4.0.20-Linux-x64
操作系统：CentOS Linux release 7.2.1511 (Core

**Comment by watchpoints** [comment]
the core info？

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
