### ISSUE TITLE
Whether continuous query of all tables under the super table is supported  by  group by when sliding Windows are used for super table?

### ISSUE THREAD

**Issue by zhangheng0109** [taosdata/TDengine#15480]
**使用滑动窗口获取数据时，无法针对超级表下所有的表进行连续查询**
环境：
****2.4.0.16**版本
centos7.4**
文档中的SQL查询语法中：
SELECT select_expr [, select_expr ...]
    FROM {tb_name_list}
    [WHERE where_condition]
    [SESSION(ts_col, tol_val)]
    [STATE_WINDOW(col)]
    [INTERVAL(interval_val [, interval_offset]) [SLIDING sliding_val]]
    [FILL(fill_mod_and_val)]
    _**[GROUP BY col_list]**_
    [ORDER BY col_list { DESC | ASC }]
    [SLIMIT limit_val [SOFFSET offset_val]]
    [LIMIT limit_val [OFFSET offset_val]]
    [>> export_file];
在文档中的连续查询语法里面，没有在滑动窗口之后使用_**[GROUP BY col_list]**_语句：
[CREATE TABLE AS] SELECT select_expr [, select_expr ...]
    FROM {tb_name_list}
    [WHERE where_condition]
    [INTERVAL(interval_val [, interval_offset]) [SLIDING sliding_val]]
单独使用SQL语句：
select last(*) from meters where ts > now-5m and ts < now and wb>500 interval(15m) group by tbname;
时，5m内查询出的数据有350条，在语句中添加 sliding(5m)之后的SQL语句：
create table new_data as select last(*) from meters where ts > now and ts < now+1h and wb>500 interval(15m) sliding(5m) group by tbname;
25分钟后只有5条数据，并没有group by tbname的效果，目前在对超级表使用滑动窗口的时候，不支持针对超级表下所有表进行连续查询吗？

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
