### ISSUE TITLE
drop multiple data tables

### ISSUE THREAD

**Issue by double-7** [taosdata/TDengine#15488]
**question：** Whether to support drop multiple data tables？
**present situation：**
1. version：2.6.0.8
2. sql：`DROP TABLE IF EXISTS tablename1  ,tablename2;`
3. result：`DB error: syntax error near ", tablename2;" (0.000481s)`

**Comment by fenghuazzm** [comment]
暂时还不支持同时删多个

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
