### ISSUE TITLE
The taosAdapter fails to start

### ISSUE THREAD

**Issue by hz-chaohai** [taosdata/TDengine#15483]
taosadapter.service - TDengine taosAdapter service
     Loaded: loaded (/etc/systemd/system/taosadapter.service; disabled; vendor >
     Active: failed (Result: core-dump) since Wed 2022-07-27 19:40:18 CST; 1s a>
   Duration: 469ms
    Process: 3806 ExecStart=/usr/bin/taosadapter & (code=dumped, signal=SEGV)
   Main PID: 3806 (code=dumped, signal=SEGV)
        CPU: 9ms

7月 27 19:40:18 td1 systemd[1]: taosadapter.service: Scheduled restart job, res>
7月 27 19:40:18 td1 systemd[1]: Stopped TDengine taosAdapter service.
7月 27 19:40:18 td1 systemd[1]: taosadapter.service: Start request repeated too>
7月 27 19:40:18 td1 systemd[1]: taosadapter.service: Failed with result 'core-d>
7月 27 19:40:18 td1 systemd[1]: Failed to start TDengine taosAdapter service.
哪里设置问题

**Comment by fenghuazzm** [comment]
查看下 /var/log/taos/ 的 taosadapter...log 里面有没有 error

**Comment by hz-chaohai** [comment]
/var/log/taos/  下没有 taosadapter...log这个文件   我在Ubuntu 安装 2.4.0.30 可以正常启动  我在 centos-steam 安装2.4.0.30和2.6.0.10 都无法启动taosadapter 执行systemctl start taosadapter这个命令  没有生成 taosadapter这个的日志

**Comment by fenghuazzm** [comment]
在 /usr/local/taos/bin 目录手动启动 taosadapter 看看输出了什么错误

**Comment by hz-chaohai** [comment]
提示错误：段错误 (核心已转储)

**Comment by hz-chaohai** [comment]
![1659070851710](https://user-images.githubusercontent.com/88811115/181686229-e2a40411-0009-4137-80bf-abdb0f118b43.png)

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
