### ISSUE TITLE
Questions about the query

### ISSUE THREAD

**Issue by homeless2010** [taosdata/TDengine#15586]
通过超级表排序查子表数据并分页性能奇差，cpu 内存飙升
![image](https://user-images.githubusercontent.com/26829140/181877866-9c19f1fd-6c56-46ef-a906-fd9db578d0b1.png)

**Comment by fenghuazzm** [comment]
`desc meters;`
看一下表结构

**Comment by homeless2010** [comment]
![image](https://user-images.githubusercontent.com/26829140/182053734-a2496cfc-feec-407c-82a8-fec44609c1d3.png)

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
