### ISSUE TITLE
how to install  ibstdc++.a

### ISSUE THREAD

**Issue by watchpoints** [taosdata/TDengine#15593]
- rock 8.4

 **make[2]: *** No rule to make target 'libstdc++.a', needed by 'build/bin/taosdump'.** 
yum update
yum install epel-release
Package epel-release-8-16.el8.noarch is already installed.

yum install  libstdc++-static
Error: Unable to find a match: libstdc++-static

yum info libstdc++ is ok 
 yum info libstdc++
Last metadata expiration check: 0:10:26 ago on Sat 30 Jul 2022 04:50:14 PM CST.
Installed Packages
Name         : libstdc++
Version      : 8.5.0
Release      : 10.1.el8_6
Architecture : x86_64
Size         : 1.8 M
Source       : gcc-8.5.0-10.1.el8_6.src.rpm
Repository   : @System
From repo    : baseos
Summary      : GNU Standard C++ Library
URL          : http://gcc.gnu.org
License      : GPLv3+ and GPLv3+ with exceptions and GPLv2+ with exceptions and LGPLv2+ and BSD
Description  : The libstdc++ package contains a rewritten standard compliant GCC Standard
             : C++ Library.

**dnf info libstdc++-static**
Last metadata expiration check: 0:10:51 ago on Sat 30 Jul 2022 04:50:14 PM CST.
Error: No matching Packages to list

**Comment by sangshuduo** [comment]
sudo dnf -y install libstdc++-static

**Comment by watchpoints** [comment]
> sudo dnf -y install libstdc++-static

I try ,but failed 
dnf makecache --refresh
dnf -y install libstdc++-static
Error: Unable to find a match: libstdc++-static

**Comment by sangshuduo** [comment]
works to me

[root@rock /]# cat /etc/redhat-release
Rocky Linux release 8.5 (Green Obsidian)
[root@rock /]# dnf info libstdc++-static
Last metadata expiration check: 0:42:40 ago on Sat Jul 30 08:13:28 2022.
Installed Packages
Name         : libstdc++-static
Version      : 8.5.0
Release      : 10.1.el8_6
Architecture : x86_64
Size         : 5.1 M
Source       : gcc-8.5.0-10.1.el8_6.src.rpm
Repository   : @System
From repo    : powertools
Summary      : Static libraries for the GNU standard C++ library
URL          : http://gcc.gnu.org
License      : GPLv3+ and GPLv3+ with exceptions and GPLv2+ with exceptions and LGPLv2+ and BSD
Description  : Static libraries for the GNU standard C++ library.

Available Packages
Name         : libstdc++-static
Version      : 8.5.0
Release      : 10.1.el8_6
Architecture : i686
Size         : 650 k
Source       : gcc-8.5.0-10.1.el8_6.src.rpm
Repository   : powertools
Summary      : Static libraries for the GNU standard C++ library
URL          : http://gcc.gnu.org
License      : GPLv3+ and GPLv3+ with exceptions and GPLv2+ with exceptions and LGPLv2+ and BSD
Description  : Static libraries for the GNU standard C++ library.

**Comment by watchpoints** [comment]
do you change the yum ？

**Comment by sangshuduo** [comment]
yum config-manager --set-enabled powertools

**Comment by watchpoints** [comment]
fix
