### ISSUE TITLE
关于分页关键字的顺序建议

### ISSUE THREAD

**Issue by ewsq** [taosdata/TDengine#156]
分页查询语法就是limit N offset M，意思是取N条记录，从第一条向后偏移M条记录开始

MYSQL的查询语法是：
select * from orders_history where type=8 limit 10000,100;
前是起始号，后是取多少条

是否有必要改成理解顺序一致？

**Comment by WillWei1983** [comment]
Mysql查询写 select * from orders_history where type=8 limit 100 offset 10000有什么毛病吗？

**Comment by guanshengliang** [comment]
您好，问题已经修复，您pull代码即可l
