### ISSUE TITLE
The JDBC connector had 'read time out' after upgrade to 2.0.40

### ISSUE THREAD

**Issue by WangJingLoong** [taosdata/TDengine#15620]
之前maven版本：2.0.35
更新后版本：2.0.40
出现问题：
![image](https://user-images.githubusercontent.com/100544530/182060903-7e1fd360-de9e-4889-ab12-65bcf960be83.png)
当这种超过5S的sql，报出
`java.util.concurrent.CompletionException: org.springframework.jdbc.UncategorizedSQLException: 
### Error querying database.  Cause: java.sql.SQLException: ERROR (2318): Read timed out
Caused by: java.io.IOException: 你的主机中的软件中止了一个已建立的连接。`
怀疑新版本设置了默认的sql超时断开，请问新的版本，应该从哪里手动调整连接时长

**Comment by fenghuazzm** [comment]
是的，JDBC连接器在 2.0.39 开始增加了 http 连接和请求超时设置。Properties 中可以做如下设置：
<img width="871" alt="image" src="https://user-images.githubusercontent.com/70138133/182347793-cce791c0-dd9e-4019-a90a-050d95fcadff.png">

**Comment by WangJingLoong** [comment]
好的  现在好了  谢谢
