### ISSUE TITLE
TDengine failed to create a connect connection using the Python connector: Ref is not there

### ISSUE THREAD

**Issue by DesTinyOooooo** [taosdata/TDengine#15636]
linux版本：Linux version 3.10.0-1160.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Mon Oct 19 16:18:59 UTC 2020
TD版本: 2.4.0.16
测试代码：
`import datetime
import time

import taos

def test_connection():
    # all parameters are optional.
    # if database is specified,
    # then it must exist.
    conn = taos.connect(host="*******",
                        port=6030,
                        user="root",
                        password="*****",
                        database="*****")
    print('client info:', conn.client_info)
    print('server info:', conn.server_info)
    conn.close()

if __name__ == "__main__":
    i = 0
    while 1:
        test_connection()
        print("_____________________")
        i += 1
        print(i)
        print(datetime.datetime.now())
        time.sleep(1)

`
使用python创建connect连接时偶发性报错[0x010a]: Ref is not there

**Comment by DesTinyOooooo** [comment]
TD客户端和服务端均配置 rpcForceTCP 1

**Comment by weiwxg** [comment]
有解决方案吗，C#驱动创建连接也会出现这种偶发性报错，要崩溃了

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
