### ISSUE TITLE
Could TDengine support the date_format function?

### ISSUE THREAD

**Issue by ulike** [taosdata/TDengine#15631]
where条件带TIMETRUNCATE报错，希望增加日期转字符串函数，比如想要查询某月的数据，目前只能传入这个月第一天和最后一天进行where查询。如果有日期转字符串函数会很方便，例如：date_format(ts,'%Y-%m') = ‘2022-08’;

**Comment by yu285** [comment]
3.x 已经支持了

2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
