### ISSUE TITLE
cant connect to taosd on windows 10 with docker

### ISSUE THREAD

**Issue by devilsbibble** [taosdata/TDengine#1565]
Basic enviroment:

- system : windows 10
- tdengine server version :  community version: 1.6.5.5
- docker on windows : 
`docker pull tdengine/tdengine`
`docker run --name tdengine -p 6020-6050:6020-6050  -p 6020-6050:6020-6050/udp tdengine/tdengine`
- client : TDengine-client-1.6.5.5-Windows-x64.exe
- client  log : 
`C:\TDengine>taos
`
==================================================
                new log file                      
==================================================
04/09 13:45:09.304000 0x14816 UTL timezone not configured, use default
04/09 13:45:09.362000 0x14816 UTL locale not configured, set to default:Chinese_China.936
04/09 13:45:09.362000 0x14816 UTL charset not configured, set to default:cp936
04/09 13:45:09.362000 0x14816 UTL    taos config & system info:
04/09 13:45:09.362000 0x14816 UTL ==================================
04/09 13:45:09.362000 0x14816 UTL  localIp:                127.0.0.1 
04/09 13:45:09.362000 0x14816 UTL  mgmtShellPort:          6030 
04/09 13:45:09.362000 0x14816 UTL  vnodeShellPort:         6035 
04/09 13:45:09.362000 0x14816 UTL  configDir:              C:/TDengine/cfg 
04/09 13:45:09.362000 0x14816 UTL  logDir:                 C:/TDengine/log 
04/09 13:45:09.362000 0x14816 UTL  scriptDir:              C:/TDengine/script 
04/09 13:45:09.362000 0x14816 UTL  numOfThreadsPerCore:    1.000000 
04/09 13:45:09.363000 0x14816 UTL  affectedRowsMod:        0 
04/09 13:45:09.363000 0x14816 UTL  rpcTimer:               300(ms)
04/09 13:45:09.363000 0x14816 UTL  rpcMaxTime:             600(s)
04/09 13:45:09.363000 0x14816 UTL  shellActivityTimer:     3(s)
04/09 13:45:09.363000 0x14816 UTL  meterMetaKeepTimer:     7200(s)
04/09 13:45:09.363000 0x14816 UTL  metricMetaKeepTimer:    600(s)
04/09 13:45:09.363000 0x14816 UTL  defaultDB:               
04/09 13:45:09.363000 0x14816 UTL  defaultUser:            root 
04/09 13:45:09.363000 0x14816 UTL  sockettype:             tcp 
04/09 13:45:09.363000 0x14816 UTL  compressMsgSize:        -1 
04/09 13:45:09.363000 0x14816 UTL  maxSQLLength:           65380(byte)
04/09 13:45:09.363000 0x14816 UTL  timezone:               not configured 
04/09 13:45:09.363000 0x14816 UTL  locale:                 Chinese_China.936 
04/09 13:45:09.363000 0x14816 UTL  charset:                cp936 
04/09 13:45:09.363000 0x14816 UTL  numOfLogLines:          10000000 
04/09 13:45:09.363000 0x14816 UTL  asyncLog:               1 
04/09 13:45:09.363000 0x14816 UTL  debugFlag:              135 
04/09 13:45:09.363000 0x14816 UTL  rpcDebugFlag:           135 
04/09 13:45:09.363000 0x14816 UTL  tmrDebugFlag:           131 
04/09 13:45:09.363000 0x14816 UTL  cDebugFlag:             135 
04/09 13:45:09.363000 0x14816 UTL  jniDebugFlag:           135 
04/09 13:45:09.363000 0x14816 UTL  odbcDebugFlag:          135 
04/09 13:45:09.363000 0x14816 UTL  uDebugFlag:             135 
04/09 13:45:09.363000 0x14816 UTL  qDebugFlag:             131 
04/09 13:45:09.363000 0x14816 UTL  gitinfo:                918cb2220f6a1f71966f7e94e697885d50fc241f 
04/09 13:45:09.363000 0x14816 UTL  gitinfoOfInternal:      da88f4a2474737d1f9c76adcf0ff7fd0975e7342 
04/09 13:45:09.363000 0x14816 UTL  buildinfo:              Built by root at 2020-02-09 11:09 
04/09 13:45:09.363000 0x14816 UTL  version:                1.6.5.5 
04/09 13:45:09.363000 0x14816 UTL  dataDir:                C:/TDengine/data
04/09 13:45:09.363000 0x14816 UTL ==================================
04/09 13:45:09.363000 0x14816 TSC starting to initialize TAOS client ...
04/09 13:45:09.363000 0x14816 TSC Local IP address is:127.0.0.1
04/09 13:45:09.363000 0x14816 UTL tsc scheduler is initialized, numOfThreads:2
04/09 13:45:09.363000 0x14816 ERROR RPC InitTcpClient not support in windows
04/09 13:45:09.363000 0x14816 ERROR RPC TSC-vnode, failed to init network, 127.0.0.1:0
04/09 13:45:09.363000 0x14816 ERROR RPC SendTcpClientData not support in windows
04/09 13:45:09.363000 0x14816 RPC cid:0, handle:0000023F8A6431B0 close rpc chann

- python example test

C:\TDengine\examples\python>python read_example.py
04/09 13:41:32.511000 0x7240 TSC set config file directory:C:\TDengine\cfg
Traceback (most recent call last):
  File "read_example.py", line 25, in <module>
    conn = taos.connect(host="127.0.0.1",user="root", password="taosdata", config="C:\TDengine\cfg")
  File "D:\Program Files\Python37\lib\site-packages\taos\__init__.py", line 24, in connect
    return TDengineConnection(*args, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\taos\connection.py", line 19, in __init__
    self.config(**kwargs)
  File "D:\Program Files\Python37\lib\site-packages\taos\connection.py", line 46, in config
    self._chandle = CTaosInterface(self._config)
  File "D:\Program Files\Python37\lib\site-packages\taos\cinterface.py", line 170, in __init__
    CTaosInterface.libtaos.taos_init()
OSError: exception: access violation reading 0x0000000000000008

**Comment by devilsbibble** [comment]
Any one can help me ?
              
udp log file                      
==================================================
04/13 10:23:08.629000 0x1676 UTL timezone not configured, use default
04/13 10:23:08.684000 0x1676 UTL locale not configured, set to default:Chinese_China.936
04/13 10:23:08.684000 0x1676 UTL charset not configured, set to default:cp936
04/13 10:23:08.685000 0x1676 UTL    taos config & system info:
04/13 10:23:08.685000 0x1676 UTL ==================================
04/13 10:23:08.685000 0x1676 UTL  localIp:                127.0.0.1 
04/13 10:23:08.685000 0x1676 UTL  mgmtShellPort:          6030 
04/13 10:23:08.685000 0x1676 UTL  vnodeShellPort:         6035 
04/13 10:23:08.685000 0x1676 UTL  configDir:              C:/TDengine/cfg 
04/13 10:23:08.685000 0x1676 UTL  logDir:                 C:/TDengine/log 
04/13 10:23:08.685000 0x1676 UTL  scriptDir:              C:/TDengine/script 
04/13 10:23:08.685000 0x1676 UTL  numOfThreadsPerCore:    1.000000 
04/13 10:23:08.685000 0x1676 UTL  affectedRowsMod:        0 
04/13 10:23:08.685000 0x1676 UTL  rpcTimer:               300(ms)
04/13 10:23:08.685000 0x1676 UTL  rpcMaxTime:             600(s)
04/13 10:23:08.685000 0x1676 UTL  shellActivityTimer:     3(s)
04/13 10:23:08.685000 0x1676 UTL  meterMetaKeepTimer:     7200(s)
04/13 10:23:08.685000 0x1676 UTL  metricMetaKeepTimer:    600(s)
04/13 10:23:08.685000 0x1676 UTL  defaultDB:               
04/13 10:23:08.685000 0x1676 UTL  defaultUser:            root 
04/13 10:23:08.685000 0x1676 UTL  sockettype:             udp 
04/13 10:23:08.685000 0x1676 UTL  compressMsgSize:        -1 
04/13 10:23:08.685000 0x1676 UTL  maxSQLLength:           65380(byte)
04/13 10:23:08.685000 0x1676 UTL  timezone:               not configured 
04/13 10:23:08.685000 0x1676 UTL  locale:                 Chinese_China.936 
04/13 10:23:08.685000 0x1676 UTL  charset:                cp936 
04/13 10:23:08.685000 0x1676 UTL  numOfLogLines:          10000000 
04/13 10:23:08.685000 0x1676 UTL  asyncLog:               1 
04/13 10:23:08.685000 0x1676 UTL  debugFlag:              135 
04/13 10:23:08.685000 0x1676 UTL  rpcDebugFlag:           135 
04/13 10:23:08.685000 0x1676 UTL  tmrDebugFlag:           131 
04/13 10:23:08.685000 0x1676 UTL  cDebugFlag:             135 
04/13 10:23:08.685000 0x1676 UTL  jniDebugFlag:           135 
04/13 10:23:08.685000 0x1676 UTL  odbcDebugFlag:          135 
04/13 10:23:08.685000 0x1676 UTL  uDebugFlag:             135 
04/13 10:23:08.685000 0x1676 UTL  qDebugFlag:             131 
04/13 10:23:08.685000 0x1676 UTL  gitinfo:                918cb2220f6a1f71966f7e94e697885d50fc241f 
04/13 10:23:08.685000 0x1676 UTL  gitinfoOfInternal:      da88f4a2474737d1f9c76adcf0ff7fd0975e7342 
04/13 10:23:08.685000 0x1676 UTL  buildinfo:              Built by root at 2020-02-09 11:09 
04/13 10:23:08.685000 0x1676 UTL  version:                1.6.5.5 
04/13 10:23:08.685000 0x1676 UTL  dataDir:                C:/TDengine/data
04/13 10:23:08.685000 0x1676 UTL ==================================
04/13 10:23:08.685000 0x1676 TSC starting to initialize TAOS client ...
04/13 10:23:08.685000 0x1676 TSC Local IP address is:127.0.0.1
04/13 10:23:08.686000 0x1676 UTL tsc scheduler is initialized, numOfThreads:2
04/13 10:23:08.687000 0x1676 UTL tmr scheduler is initialized, numOfThreads:1
04/13 10:23:08.696000 0x1676 UTL open udp socket:127.0.0.1:0
04/13 10:23:08.696000 0x1676 ERROR UTL failed to open udp socket: 0 (No error)
04/13 10:23:08.701000 0x1676 ERROR RPC TSC-vnode failed to open UDP socket 127.0.0.1:0
04/13 10:23:08.701000 0x1676 ERROR RPC TSC-vnode, failed to init network, 127.0.0.1:0
04/13 10:23:08.701000 0x1676 RPC cid:0, handle:000002827F161EA0 close rpc chann

**Comment by Shawshank-Smile** [comment]
Add my wechat 13720014098 please, I need more info

**Comment by Shawshank-Smile** [comment]
I think windows is not working well, try Linux please.

**Comment by liu0x54** [comment]
You can try 
docker pull tdengine/tdengine:1.6.5.5
the client version and docker image version must clearly match

**Comment by liuyq-617** [comment]
1、docker network create --ip-range 172.15.1.255/24 --subnet 172.15.1.1/16 minidevops//创建一个虚拟网络
2、docker run -d --net minidevops --ip 172.15.1.6 -p 6030:6030 -p 6020:6020 -p 6031:6031 -p 6032:6032 -p 6033:6033 -p 6034:6034 -p 6035:6035 -p 6036:6036 -p 6037:6037 -p 6038:6038 -p 6039:6039 -p 6020-6050:6020-6050/udp tdengine/tdengine:1.6.5.5
//启动docker
3、taos.exe //windows端直接连接成功
