### ISSUE TITLE
mybatis+druid How to solve the Chinese disorder code when saving

### ISSUE THREAD

**Issue by Stone2016** [taosdata/TDengine#1566]
mybatis+druid 保存时中文乱码怎么解决

**Comment by Shawshank-Smile** [comment]
TDengine use the type “NCHAR”

Here may you find answer。
https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&rsv_idx=1&tn=baidu&wd=mybatis%2Bdruid%20%E4%BF%9D%E5%AD%98%E6%97%B6%E4%B8%AD%E6%96%87%E4%B9%B1%E7%A0%81%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3&rsv_t=d48bqrlTeTEJEky6%2FlzsHS1rk2F4dtAz4hPgTA%2FO6tjZzObtiIJb%2BEFZDBI&rsv_dl=tb&rsv_enter=1&rsv_n=2&rsv_sug3=1&rsv_sug2=0&inputT=390&rsv_sug4=391

**Comment by cuihanbing** [comment]
方案1
`jdbc-url: jdbc:TAOS://xxxx.xxxx.xxxx.xxxx:6030/xxxx?charset=UTF-8&locale=en_US.UTF-8&timezone=UTC-8`
方案2
```
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl(applicationConfig.getHostPort());
        config.setUsername("root");
        config.setPassword("taosdata");
        config.setMinimumIdle(3);
        config.setMaximumPoolSize(10);
        config.setConnectionTimeout(10000);
        config.setIdleTimeout(60000);
        config.setConnectionTestQuery("describe log.dn");
        config.setValidationTimeout(3000);
        **config.addDataSourceProperty(TSDBDriver.PROPERTY_KEY_CHARSET, "UTF-8");
        config.addDataSourceProperty(TSDBDriver.PROPERTY_KEY_LOCALE, "en_US.UTF-8");  
        config.addDataSourceProperty(TSDBDriver.PROPERTY_KEY_TIME_ZONE, "UTC-8");**
```

**Comment by sangshuduo** [comment]
请问问题解决了吗？

**Comment by Stone2016** [comment]
方案一试过不行，方案二没有去弄

方案1
jdbc-url: jdbc:TAOS://xxxx.xxxx.xxxx.xxxx:6030/xxxx?charset=UTF-8&amp;locale=en_US.UTF-8&amp;timezone=UTC-8
方案2
        HikariConfig config = new HikariConfig();         config.setJdbcUrl(applicationConfig.getHostPort());         config.setUsername("root");         config.setPassword("taosdata");         config.setMinimumIdle(3);         config.setMaximumPoolSize(10);         config.setConnectionTimeout(10000);         config.setIdleTimeout(60000);         config.setConnectionTestQuery("describe log.dn");         config.setValidationTimeout(3000);         **config.addDataSourceProperty(TSDBDriver.PROPERTY_KEY_CHARSET, "UTF-8");         config.addDataSourceProperty(TSDBDriver.PROPERTY_KEY_LOCALE, "en_US.UTF-8");           config.addDataSourceProperty(TSDBDriver.PROPERTY_KEY_TIME_ZONE, "UTC-8");**




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shuduo Sang"<notifications@github.com&gt;; 
发送时间: 2020年9月15日(星期二) 下午3:55
收件人: "taosdata/TDengine"<TDengine@noreply.github.com&gt;; 
抄送: "313室员"<394692958@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [taosdata/TDengine] mybatis+druid How to solve the Chinese disorder code when saving (#1566)





 
请问问题解决了吗？
