### ISSUE TITLE
Dose interval support unit of line?

### ISSUE THREAD

**Issue by wsf1990** [taosdata/TDengine#15670]
Dose INTERVAL func support some line when query table, like `select avg(column) from table interval(10l)', which 10l means interval 10 record.
INTERVAL 间隔采样支持以行为单位吗？比如间隔10行计算平均值？

**Comment by fenghuazzm** [comment]
暂时还不支持按照行来聚合。是因为采集数据的时间不是规律吗？

**Comment by wsf1990** [comment]
是的，每个传感器采样频率不一样

**Comment by yu285** [comment]
3.2.3.0 已经支持这个特性了

另外，2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
