### ISSUE TITLE
fix issues found by Coverity Scan in qFilter.c (branch: 2.6)

### ISSUE THREAD

**Issue by xiaopingcs** [taosdata/TDengine#15686]
Bug Description
fix issues found by Coverity Scan in TDengine/src/query/src/qFilter.c

To Reproduce
N/A

Expected Behavior
fix following issues:
| Type                          | Category                | Function                   | Line Number |
| ----------------------------- | ----------------------- | -------------------------- | ----------- |
| Logically dead code           | Control flow issues     | filterDumpInfoToString     | 1673        |
| Wrong sizeof argument         | Incorrect expression    | filterMergeGroupUnits      | 2157        |
| Logically dead code           | Control flow issues     | filterExecuteImplNotNull   | 3121        |
| Logically dead code           | Control flow issues     | filterExecuteImplIsNull    | 3074        |
| Missing break in switch       | Control flow issues     | filterConvertSetFromBinary | 1070        |
| Unsigned compared against 0   | Control flow issues     | filterDumpInfoToString     | 1604        |
| Uninitialized scalar variable | Uninitialized variables | filterExecuteImpl          | 3312        |
| Resource leak                 | Resource leaks          | createQueryPlanImpl        | Various     |

Screenshots
N/A

Environment (please complete the following information):
N/A

Additional Context
above issues found by https://scan.coverity.com/projects/tdengine?tab=overview

**Comment by HeZean** [comment]
Hi! May I work on it?

**Comment by kussshhhh** [comment]
Hi , can i work on it ?
