### ISSUE TITLE
希望分布式支持开源

### ISSUE THREAD

**Issue by ewsq** [taosdata/TDengine#157]
现在用到这种软件，基本都是解决大数据问题，而大数据就存在分布式存储问题，所以如果分布式不开源将极大限制此软件的扩散应用。希望也能将这部分开源。

**Comment by plum-lihui** [comment]
涛思数据将拥抱开源，而且坚决将核心代码开源。但基于多方面的考虑，暂时不开源集群版，今后会选择适当时机将集群版开源。集群版的设计已经公开，请看官网文档。如果你有意愿，我们可以给您提供集群版进行测试评估。

**Comment by sangshuduo** [comment]
2.0 集群已经开源
