### ISSUE TITLE
currentKey == ts' failed.

### ISSUE THREAD

**Issue by rexel-dev** [taosdata/TDengine#15709]
TDserver是2.1.0.0版本  client版本是2.1.0.0  pom依赖使用的是2.0.28，执行sql语句可以在td里面查到结果，但是使用java代码执行报这个错
java: /home/ubuntu/ver_release_workspace/TDinternal/community/src/query/src/qFill.c:207: fillResultImpl: Assertion `pFillInfo->currentKey == ts' failed.

sql语句如下

taos> select spread(value) as spread from XXXXXX_20220301155722.st_device_data_up  where ( productKey = "p2ed7b926ccdf" and  deviceName = "XXX" and ( pointId = "VR_TEST84")) and  time >= "2022-01-01 00:00:00" and  time < "2022-08-03 16:35:36"  interval(
1n)  fill(value,0)  group by productKey, deviceName, pointId ;

**Comment by fenghuazzm** [comment]
这应该是旧版本的 bug，2.1.0.0 很久远了，推荐升级到 2.6 最新版。
附：[升级步骤](https://www.taosdata.com/engineering/10222.html)

**Comment by rexel-dev** [comment]
好的
