### ISSUE TITLE
在同一张超级表的子表中插入标签值不同数据，后插入标签数据应该与之前标签值是不同的，但是显示插入的标签值是相同的这正常吗？

### ISSUE THREAD

**Issue by ZhangChengJi** [taosdata/TDengine#15724]
![image](https://user-images.githubusercontent.com/36288987/182620559-02a6d08d-74ed-4daf-b2c3-b6fdaee0fbf2.png)
![image](https://user-images.githubusercontent.com/36288987/182620715-afe84ead-745a-48d3-81b3-10e554be9d33.png)

**Comment by fenghuazzm** [comment]
正常的，同一子表需要有同样的标签值
