### ISSUE TITLE
Can I set the 'days to keep' according to different tables?

### ISSUE THREAD

**Issue by ivanzhc** [taosdata/TDengine#1573]
关于daysToKeep, 是否可以根据不同表或者不同数据库设置。
如果我一个数据库中，有两个表。一个表的数据想保留1年，一个表的数据想保留一个月。
是否有方法可以达成？
如果有方法，应该怎么做？
谢谢

**Comment by Shawshank-Smile** [comment]
Not supported yet, keep days works only to database. May be two databases is the only way for now.
