### ISSUE TITLE
Prompt for executing SQL statement，DB error: invalid table id

### ISSUE THREAD

**Issue by crzbee** [taosdata/TDengine#1574]
> aarch32系统、ubuntu(x86_64位)，两个系统都构建过TDengine-1.6.5.6。
1. 首先，在ubuntu(x86_64位)系统里，执行官方demo`taosdemo -h xxx.xxx.xx.xx`，向aarch32系统中的数据库，插入10亿条测试数据。
2. 成功插入之后，我分别在aarch32系统执行`taos`、ubuntu(x86_64)系统执行`taos -h xxx.xx.xx.xx`，进入终端执行sql，分别得到两个不同的结果。(x86_64)系统提示`DB error: invalid table id`。

#### 这是什么造成的呢？

截图如下:
![64位_ubuntu](https://user-images.githubusercontent.com/15994678/78958504-ca341b00-7b1a-11ea-93e9-876df2e395cc.png)
![32位_arm板](https://user-images.githubusercontent.com/15994678/78958517-cf916580-7b1a-11ea-864f-b4dc59972c91.png)

**Comment by Shawshank-Smile** [comment]
The client and the server must be the same version.

**Comment by huangheding** [comment]
> > aarch32系统、ubuntu(x86_64位)，两个系统都构建过TDengine-1.6.5.6。
> 
> 1. 首先，在ubuntu(x86_64位)系统里，执行官方demo`taosdemo -h xxx.xxx.xx.xx`，向aarch32系统中的数据库，插入10亿条测试数据。
> 2. 成功插入之后，我分别在aarch32系统执行`taos`、ubuntu(x86_64)系统执行`taos -h xxx.xx.xx.xx`，进入终端执行sql，分别得到两个不同的结果。(x86_64)系统提示`DB error: invalid table id`。
> 
> #### 这是什么造成的呢？
> 截图如下:
> ![64位_ubuntu](https://user-images.githubusercontent.com/15994678/78958504-ca341b00-7b1a-11ea-93e9-876df2e395cc.png)
> ![32位_arm板](https://user-images.githubusercontent.com/15994678/78958517-cf916580-7b1a-11ea-864f-b4dc59972c91.png)

问您一下 问题解决了吗？
