### ISSUE TITLE
The union all function should be described differently depending on the version.

### ISSUE THREAD

**Issue by jinghuijiang1993** [taosdata/TDengine#15761]
！[上传 image.png...]()  本人使用了两个版本 一个是2.1.0.0和2.4.0.4版本  因为最开始用的是2.1, 在使用union all进行相关数据查询时,并没有发现问题,但是后面还了2.4之后,发现有报错,仔细看了一下文档,确实说了最多只能100个,但是这个限制是在不同的版本下限制的,所以这块建议可以描述下什么版本下开始了数量限制

**Comment by fenghuazzm** [comment]
感谢反馈，union all 的数量可能因为某些原因限制过，文档上我们会及时更改

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
