### ISSUE TITLE
Why sometimes it can connect and sometimes not

### ISSUE THREAD

**Issue by BlueCestbon** [taosdata/TDengine#15822]
**Bug Description**
**Why sometimes it can connect and sometimes not ？**

**Screenshots**
![image](https://user-images.githubusercontent.com/65054570/183253737-d2e8ba3a-534f-44cb-be34-fabc2a8aeaad.png)

![image](https://user-images.githubusercontent.com/65054570/183253824-89c04ae1-68ff-49c7-bce2-f33ea6a7fcd5.png)

**Environment **

 - OS: [CentOS 7.6]
 - Client TDengine Version [2.6.0.10]
 - Server TDengine Version [2.6.0.10]
 - Kubernetes Version [1.20.9]

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
