### ISSUE TITLE
Create table problem

### ISSUE THREAD

**Issue by xieshengjie** [taosdata/TDengine#15849]
建表语句CREATE TABLE power.d1001.1 USING meters TAGS  ("d1001");
数据库是power,数据表名是d1001.1,表名带了“.”符号，建表不成功。报错

**Comment by xieshengjie** [comment]
加反引号也是报错

**Comment by fenghuazzm** [comment]
报了什么错？
加反引号后这个表名就没问题了，看看超级表 meters 的表结构，是不是少写了 tags 字段
