### ISSUE TITLE
Error：Could not initialize class com.taosdata.jdbc.TSDBJNIConnector 

### ISSUE THREAD

**Issue by greenhandH** [taosdata/TDengine#15878]
程序本地运行没有报错 线上运行报错，驱动版本2.0.39

java.lang.NoClassDefFoundError: Could not initialize class com.taosdata.jdbc.TSDBJNIConnector 	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:162) 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358) 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477) 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560) 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) 	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158) 	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116) 	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79) 	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:80) 	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:67)

**Comment by fenghuazzm** [comment]
线上环境有部署 TDengine 客户端吗？

**Comment by greenhandH** [comment]
> 线上环境有部署 TDengine 客户端吗？
有部署的，线上跑了五个微服务，用k8s进行部署管理的，其他俩个用到taos服务的微服务没有报错，目前只发现这个微服务线上执行语句时驱动启动报错了。

**Comment by greenhandH** [comment]
> 线上环境有部署 TDengine 客户端吗？

 有部署的，线上跑了五个微服务，用k8s进行部署管理的，其他俩个用到taos服务的微服务没有报错，目前只发现这个微服务线上执行语句时驱动启动报错了。

**Comment by 2110483505** [comment]
目前最新的Maven版本不是 2.0.38 吗?

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
