### ISSUE TITLE
Grafana adds Alert rule, but does not support Group by

### ISSUE THREAD

**Issue by ntucz** [taosdata/TDengine#15879]
![1](https://user-images.githubusercontent.com/22786757/183553633-1bbb6d1c-77ba-43d9-8a12-f3cda4406516.png)
![2](https://user-images.githubusercontent.com/22786757/183553646-41c6840e-10c0-4714-83c2-5d82842a24cb.png)
上图是postgres的alert rule添加后的展示，支持group by，并且group by的结果在label里面。
下图是TD的alert rule，不支持group by，增加group by导致查询结果多了一列sn，报错。
TD的alert rule的sql，即使不加group by，在select 里面增加一列，也报同样的错误。
但是实际使用中，没有这个group by或者id列，就不能得知alert属于哪个设备，这个就没有太大意义了。

**Comment by fenghuazzm** [comment]
group by 的字段放到 Group by column name 中试试

**Comment by ntucz** [comment]
> group by 的字段放到 Group by column name 中试试
![1](https://user-images.githubusercontent.com/22786757/183587025-d0eb3a20-2ef7-463e-b662-0b2f96934e60.png)
![2](https://user-images.githubusercontent.com/22786757/183587020-a08c7f41-528d-4564-beab-ce7d576b798f.png)
虽然没报错，但是告警预览里面得不到，不像postgres已经放到了labels里面。

**Comment by ntucz** [comment]
> group by 的字段放到 Group by column name 中试试

https://grafana.com/grafana/plugins/tdengine-datasource/
"In addition, only ALIAS BY and INPUT SQL are valid. So alert does not work if you requires the time-shift feature."
看来其他的都是摆设

**Comment by ntucz** [comment]
> group by 的字段放到 Group by column name 中试试

 Group by column name 这个配置不支持。
SQL里面group by 的语句支持仅限于字段为int或float，不能是字符串。
局限性太大，难堪大用。没有其他数据源实现的优雅，比如上面我测试的postgres。

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
