### ISSUE TITLE
only the first create table phase was executed when submit create table phase in bulk

### ISSUE THREAD

**Issue by valensc** [taosdata/TDengine#159]
![image](https://user-images.githubusercontent.com/2038501/61685916-bf4d1680-ad50-11e9-9018-2bd89f33d829.png)

**Comment by valensc** [comment]
taos> insert into t1 values (11, 1); insert into t2 values (22, 2);
TSDB error: invalid table

If multiple insert submission is not supportted, how can we improve the performance when facing millions of devices? Note that each time series may create one and only one new data point in every steps, so we need to flush all these data points belong to different time series in seconds. It's not possible without a cross table bulk write feature.

**Comment by plum-lihui** [comment]
1、Only one SQL statement can be supported at one time in the shell；
2、INSERT supports simultaneous insertion data into multiple tables， e.g.
`INSERT INTO <tb1_name> VALUES (field_value, …)(field_value, …)… <tb2_name> VALUES (field_value, …)(field_value, …)…;` 
`INSERT INTO <tb1_name> (field1_name,…) VALUES(field1_value,…) (field1_value,…) <tb2_name> (field2_name,…) VALUES (field2_value,…) (field2_value,…)`

**Comment by valensc** [comment]
@plum-lihui  Thanks for ur reply, I think a error msg for multiple create statement is better.

when I try this out, taosd crashed with log below, and cannot recover data again.

```
07/23 20:05:47.279194 7f5657ffe700 DND vid:0, committing is over
07/23 20:05:47.280005 7f575cee6700 MND user:root login from <ip>, code:0
07/23 20:05:47.280465 7f575bee4700 MND user:root login from <ip>, code:0
decomp_size:-1, Error decompress in LZ4 algorithm!
: Success
```

I wrote a test with go connector,  on a 32 cores machine, I can only reach 568,000 qps writing with 20 connections, and i found this in documents:

> taosSql驱动包内采用cgo模式，调用了TDengine的C/C++同步接口，与TDengine进行交互，因此，在数据库操作执行完成之前，客户端应用将处于阻塞状态。单个数据库连接，在同一时刻只能有一个线程调用API。

does it means only one goroutine can call cgo api at the same time? so it is not a parallel connector?

**Comment by plum-lihui** [comment]
This go connector is certainly parallelizable. Just a thread establishes a link, not another thread to use,  Each thread uses its own established links for accessing the database.
