### ISSUE TITLE
How does TD Docker cluster persist data and logs to the host directory?

### ISSUE THREAD

**Issue by AdonLuo** [taosdata/TDengine#15907]
环境: Centos7.9  docker 部署集群
配置文件：采用的是官方参考 /packaging/docker/docker-compose.yml
其中有关于目录映射的部分 采用了顶级卷 volumes，有点不明白如何指定宿主机上对应的目录？
volumes:
  taosdata-td1:
  taoslog-td1:
  taosdata-td2:
  taoslog-td2:
  
  这边要如何配置才可以试下数据、日志保存到宿主机指定的目录下呢？

**Comment by fenghuazzm** [comment]
docker-compose.yml 里面的 taosdata-td1、taoslog-td1 是需要自己  docker volume create 创建命名了的数据卷，也可以使用直接指定路径的方式。

**Comment by AdonLuo** [comment]
docker volume create 这个查了一圈下来好像都是默认docker 安装下的位置，无法指定自己的目录位置，除非不采用这种顶级卷方式是吧
