### ISSUE TITLE
Migrating mysql data to TDEngine using Datax，an error occurred：invalid column type  LONG

### ISSUE THREAD

**Issue by dev007-art** [taosdata/TDengine#15921]
mysql中bigint类型数据转到tdengine报错，tdengine这个也是bigint类型，
2022-08-09 21:55:54.385 [0-0-0-writer] ERROR StdoutPluginCollector - 脏数据:
{"exception":"invalid column type: LONG","record":[{"byteSize":8,"index":0,"rawData":1660042031000,"type":"DATE"},{"byteSize":1,"index":1,"rawData":4,"type":"LONG"},{"byteSize":6,"index":2,"rawData":"dasdsa","type":"STRING"}],"type":"writer"}
2022-08-09 21:55:54.387 [0-0-0-writer] ERROR DefaultDataHandler - invalid column type: LONG

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
