### ISSUE TITLE
How can I customize my installation path

### ISSUE THREAD

**Issue by paopaol** [taosdata/TDengine#1593]
**Bug Description**
I want to build an arm-based taosdb, and I specified CMAKE_INSTALL_PREFIX, but the default path is still installed to / usr. My cross compilation environment is ubuntu. But the default behavior is to install the taosdb of the arm architecture to the / usr directory of ubuntu. Is there any way for me to specify the installation path? So that I can copy the generated installation directory to the embedded system.

**Comment by Shawshank-Smile** [comment]
/etc/taos/taos.cfg  : All configuration are here .

**Comment by paopaol** [comment]
I am not referring to this. I am talking about the packaging of the entire Taos after compilation. This command is make install. I hope that after make install I can install taos to other directories, such as /opt/taos1.6.xx. But make install seems to be installed under / usr. On windows, it is forced to install to the c drive

**Comment by plum-lihui** [comment]
When on linux system，if you need appoint the install path, please modify packaging\tools\make_install.sh。 And on windows，please modify CMakelists.txt：SET(CMAKE_INSTALL_PREFIX C:/TDengine)
