### ISSUE TITLE
The taos_fetch_block function returns a maximum of 4096 data

### ISSUE THREAD

**Issue by yejinmo** [taosdata/TDengine#15953]
服务端： 2.6.0.12 / CentOS x86
客户端： 2.6.0.12 / Windows x86

目标测试集包含 30 万数据，通过 `taos_fetch_row` 函数可将全部数据获取到
但调用 `taos_fetch_block` 函数返回值最大为 4096 ，当测试集数量小于 4096 时返回值是正确的
查阅官网文档未发现这部分的说明，这里是有什么限制么？
感谢

**Comment by fenghuazzm** [comment]
taos_fetch_block 主要是通过查询 block 块提升了性能。请告知一下程序使用的语言、连接器版本，最好也能贴一下代码

**Comment by yejinmo** [comment]
感谢回复

> taos_fetch_block 主要是通过查询 block 块提升了性能。请告知一下程序使用的语言、连接器版本，最好也能贴一下代码

语言： C# / .Net Standard 2.0
连接器版本： 2.6.0.12

```cs
// 声明
[DllImport("taos", EntryPoint = "taos_fetch_block", CallingConvention = CallingConvention.Cdecl)]
static extern public int FetchBlock(IntPtr taos, ref IntPtr rows);

// 调用
// intPtr 为 taos_query 返回的指针
IntPtr rows = IntPtr.Zero;
var count = FetchBlock(intPtr, ref rows);
```

不知道是否是因为 `ref IntPtr rows` 这里调用不合规导致的问题

@fenghuazzm

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
