### ISSUE TITLE
macos /wrapper/asynccb.go:7:10: fatal error: 'taos.h' file not found

### ISSUE THREAD

**Issue by dengany** [taosdata/TDengine#15969]
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/45355892/184059481-0c9f6faa-f870-4030-83e7-f8cc9898c98d.png">
macos 

go get github.com/taosdata/driver-go/v2/taosSql
# github.com/taosdata/driver-go/v2/wrapper
../../../go/pkg/mod/github.com/taosdata/driver-go/v2@v2.0.4/wrapper/asynccb.go:7:10: fatal error: 'taos.h' file not found
#include <taos.h>

**Comment by fangyoukeji** [comment]
需要安装版本一致的客户端驱动 taosc

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
