### ISSUE TITLE
connect failed, reason: Unable to establish connection.

### ISSUE THREAD

**Issue by anybus** [taosdata/TDengine#15989]
服务器端是利用压缩包安装的，测试taos和python代码都能连接数据库，
安全组策略也没问题

现在问题是，windows客户端安装了2.4.0.30（与服务器版本一致），无法创建连接。。

FAQ里的都尝试了，6030端口ok，还有没有抢救的办法？？？

**Comment by fenghuazzm** [comment]
`python 代码能连接` 
是在 TDengine 服务端运行的吧
win 这边报错的截图贴一下

**Comment by 2110483505** [comment]
我昨天也遇到这个问题了, 我换了一种连接方式, 没有采用原生连接, 采用Rest连接就解决了.
具体文档  : https://docs.taosdata.com/reference/taosadapter/

以下时我的解决方案
1. 第一步 : 在服务器端开启 systemctl stop taosadapter
2. 第二步 : 换数据连接方式. 以下时java的解决方案. Python可以获取具体的代码
public static void main(String[] args) throws SQLException {
        String jdbcUrl = "jdbc:TAOS-RS://localhost:6041?user=root&password=taosdata";
        Properties connProps = new Properties();
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_BATCH_LOAD, "true");
        Connection conn = DriverManager.getConnection(jdbcUrl, connProps);
        System.out.println("Connected");
        conn.close();
    }
3. 第三步 : 进行测试
4. 可以下载一个TDengine的GUI工具进行测试 : https://gitee.com/skyebaobao/TDengineGUI

**Comment by godlovefei** [comment]
@anybus 
遇到类似的问题：
`conn = taos.connect(host="",
                    port=6041,
                    user="root",
                    password="taosdata",
                    database="log")`

错误：
`Traceback (most recent call last):
  File "D:\code\InspurProject\zhongan\test.py", line 16, in <module>
    conn = taos.connect(host="172.31.0.43",
  File "D:\software\Miniconda3\envs\paddle212\lib\site-packages\taos\__init__.py", line 65, in connect
    return TaosConnection(*args, **kwargs)
  File "D:\software\Miniconda3\envs\paddle212\lib\site-packages\taos\connection.py", line 25, in __init__
    self._conn = self._chandle.connect(self._host, self._user, self._password, self._database, self._port)
  File "D:\software\Miniconda3\envs\paddle212\lib\site-packages\taos\cinterface.py", line 1993, in connect
    return taos_connect(host, user, password, db, port)
  File "D:\software\Miniconda3\envs\paddle212\lib\site-packages\taos\cinterface.py", line 235, in taos_connect
    raise ConnectionError(errstr, errno)
taos.error.ConnectionError: [0x000b]: Unable to establish connection`

同@2110483505 ，通过使用Rest连接方式解决
