### ISSUE TITLE
K8S

### ISSUE THREAD

**Issue by r0pzzz** [taosdata/TDengine#15999]
k8s创建的集群可以用tdengine windows客户端连接吗 我tdengineGUI连接的上 但windows客户端连不上

**Comment by codering** [comment]
k8s集群对外一般只暴露了6041端口，可以用restful 方式访问。gui就是restful方式访问。windows安装的客户端用的其他端口，肯定访问不了。

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
