### ISSUE TITLE
能不能编译一份mac的库？

### ISSUE THREAD

**Issue by Konglingpeng** [taosdata/TDengine#160]
Mac下开发没有类库，没法连接taos，急需一份mac的类库

**Comment by plum-lihui** [comment]
已经有贡献者在开发了，敬请耐心等待！
多谢关注！

**Comment by xinqiyang** [comment]
强烈期待mac的库，开发很麻烦。 😄

**Comment by guanshengliang** [comment]
如果与我们联系的贡献者在8月15日仍然没有开发，我们会在8月15日启动，预计9月初可以完成。

**Comment by xmcxcoc** [comment]
请支持一下mac版本,谢谢.

**Comment by guanshengliang** [comment]
目前开源社区提出的需求很多
TDengine团队会根据自身的研发能力按照优先级进行排序

**Comment by ximinggao** [comment]
@guanshengliang thanks!

**Comment by boostbob** [comment]
有mac的动态库了吗?

**Comment by jmx580515** [comment]
请支持一下mac版本,谢谢.

**Comment by sintrb** [comment]
Mac很迫切。。

**Comment by guanshengliang** [comment]
如果春节期间没有研发计划，我可能会尝试做这件事情

**Comment by uax** [comment]
现在有 MacOS 的库吗？

**Comment by sudo168** [comment]
急需Mac client。。。

**Comment by ming201005** [comment]
现在有mac的库了吗？

**Comment by uax** [comment]
有 MacOS 库的进度了吗？

**Comment by ChinaShrimp** [comment]
Is there any progress? Thanks.

**Comment by armenpn** [comment]
期待！

**Comment by aszhou** [comment]
团队大部分均是 MAC 办公，没有 Mac client 太麻烦了，烦请提升优先级。

**Comment by guanshengliang** [comment]
On some macs, the udp package cannot exceed 64k, so although the 1.6 version of the mac can be compiled, it is not released
Version 2.0 will be included in the development plan.
If you need to develop on mac, you can consider using docker

**Comment by zsy-cn** [comment]
能更新一下Mac client的开发进度吗？谢谢！

**Comment by chuangtim** [comment]
Mac client能更新下开发进度吗？急需

**Comment by machine-w** [comment]
https://github.com/machine-w/crown

这个是我在使用TDengine开发应用的时候，自己写的一个python  orm库。我自己的项目也在用。可以直接在mac上连接Tdengine，出了目前暂时不支持jion查询以外，其他的功能都比较完备。大家如果有需要的可以试试。

**Comment by qinxiaoxiang** [comment]
现在有mac库了吗？

**Comment by sangshuduo** [comment]
@qinxiaoxiang 可以自己编译
