### ISSUE TITLE
3.0.0 windows client 安装后运行失败(TDengine-client-3.0.0.0-Windows-x64.exe)

### ISSUE THREAD

**Issue by BrianSpace** [taosdata/TDengine#16094]
**Bug Description**
3.0.0版本windows 64位 client安装后运行失败

**To Reproduce**
1. 运行安装程序(TDengine-client-3.0.0.0-Windows-x64.exe)
2. 完成后运行Taos Shell
3. 弹出两个对话框

**Expected Behavior**
可以正常运行taos

**Screenshots**
---------------------------
taos.exe - 系统错误
---------------------------
由于找不到 VCRUNTIME140D.dll，无法继续执行代码。重新安装程序可能会解决此问题。 
---------------------------
确定   
---------------------------

---------------------------
taos.exe - 系统错误
---------------------------
由于找不到 ucrtbased.dll，无法继续执行代码。重新安装程序可能会解决此问题。 
---------------------------
确定   
---------------------------

**Environment (please complete the following information):**
 - OS: Windows 11
 - TDengine Version 3.0.0

**Comment by BrianSpace** [comment]
这两个文件是Debug版本的吧？是不是把debug版本发出去了？

**Comment by xunzhimeng** [comment]
是的，找个32位的版本放进去，就可以用了，或者自己编译源码也可以。

**Comment by fenghuazzm** [comment]
运行库不全，可以从网上找一下给放到 system32 文件夹试试

**Comment by fenghuazzm** [comment]
目前已经修复，已经替换了官网 win 3.0.0.0 的下载源
