### ISSUE TITLE
document typo about SMALLINT UNSIGNED data range?

### ISSUE THREAD

**Issue by kerneltravel** [taosdata/TDengine#16090]
**Bug Description**
doc url:  https://docs.taosdata.com/taos-sql/data-type/ 
Type: SMALLINT UNSIGNED, 
Bytes :2 
说明：无符号短整型，范围 [0, 655357]

the  [0, 655357] should be  [0, 65535] ？

**Comment by sangshuduo** [comment]
谢谢指出，已修复
