### ISSUE TITLE
An Out of DNodes exception occurs in Windows server

### ISSUE THREAD

**Issue by ling-bin** [taosdata/TDengine#16116]
windows 版本使用 REST API 报异常  out  of dnodes
![73025a89593f2f7a2289131011f37be](https://user-images.githubusercontent.com/76943717/184609707-400047f8-c693-4e6f-9856-fc5b939d2fa8.jpg)

异常后其它的请求都会没有响应，一直到http超时，taosd 进程需要重启后才可以查询和插入操作，但依旧不能在超级表加新的子表；

**Comment by fenghuazzm** [comment]
TDengine 3.0.0.0 win server 是吗，目前大概有多少个表、数据库？

**Comment by ling-bin** [comment]
是的，几千个表、一个数据库就出问题了；

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。
