### ISSUE TITLE
How to realize dual machine hot standby？

### ISSUE THREAD

**Issue by GK0505** [taosdata/TDengine#16120]
行业标准中需要实现双机热备功能，tdengine中是如何实现的？文档中taosx章节没有相关内容，这部分功能是企业版，需要付费吗？

**Comment by fenghuazzm** [comment]
您所在的是什么行业呢？TDengine 采取分布式架构，使用多副本机制保障系统的高可用，目前社区版不支持双机热备的架构。
企业版有基于同步实现的方案，若想了解详细信息可以加本人微信：Deja_vu_4u，我协助对接企业版团队。

**Comment by yu285** [comment]
TDengine currently has support dual machine hot standby , if you want to know more about it , please add wechat a15652223354
