### ISSUE TITLE
Last (*),last_row (*) and other function return fields on 3.0.0.0 are different from those on 2.6.X

### ISSUE THREAD

**Issue by bluceyee** [taosdata/TDengine#16133]
**Bug Description**

之前使用的是2.6.0.12版本，其中的last, last_row 函数非常好用，其直接返回了列名，因为其作了缓存，我们直接使用作为传感器实时值，3.0.0.0版本发布后，我们尝试使用，发现影响比较多，其中最大的是上面两个函数，以及first 等函数返回的列表与2.6.x版本不一致了。

两个版本的测试结果如下：

Welcome to the TDengine Command Line Interface, Client Version:3.0.0.0
Copyright (c) 2022 by TDengine, all rights reserved.

Server is Community Edition.
taos> select last(*) from device_1;
    last(device_1.ts)    | last(device_1.bvalue) | last(device_1.temperature) | last(device_1.power) | last(device_1.avalue) |
==============================================================================================================================
 2022-08-15 10:14:07.071 |                  1050 |                   25.90000 |                   87 |                     0 |
Query OK, 1 rows in database (0.004906s)

Welcome to the TDengine shell from Linux, Client Version:2.6.0.12
Copyright (c) 2022 by TAOS Data, Inc. All rights reserved.

taos> select last(*) from device_1;
           ts            |   bvalue    |     temperature      |    power    |   avalue    |
===========================================================================================
 2022-08-14 20:51:56.171 |        1140 |             25.20000 |          87 |           0 |
Query OK, 1 row(s) in set (0.001900s)

**Expected Behavior**
保持与2.6.x版本上相同功能，返回列名。

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.6]
 - TDengine Version [3.0.0.0]

**Comment by fenghuazzm** [comment]
3.0  keepColumnName 参数没生效了，感谢反馈，我们研究下

**Comment by bluceyee** [comment]
the latest version is 3.0.1.8, has this problem been fixed？ tks

**Comment by imoxuan** [comment]
The problem of upgrading to the latest 3.0.2.1 version still exists.

**Comment by yu285** [comment]
3.0早期版本的bug 都已经全部修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。
