### ISSUE TITLE
3.0.0 INTERP、INTERVAL functions no longer return timestamp fields

### ISSUE THREAD

**Issue by wangshk** [taosdata/TDengine#16149]
文档中在使用聚合函数时会有时间字段返回：
taos> SELECT sum(current) FROM d1001 INTERVAL(10s);
           ts            |       sum(current)        |
 2018-10-03 14:38:00.000 |              10.300000191 |
 2018-10-03 14:38:10.000 |              24.900000572 |
Query OK, 2 row(s) in set (0.000883s)
但在3.0.0版本中无返回，且不支持添加时间字段
Welcome to the TDengine Command Line Interface, Client Version:3.0.0.0
Copyright (c) 2022 by TDengine, all rights reserved.
Server is Community Edition.
taos> use metric ;
Database changed.
taos> select avg(cpu) from metrics   WHERE  ts> now-1m INTERVAL(10s);
         avg(cpu)          |
               3.884500000 |
               3.766000000 |
               3.271000000 |
               3.531500000 |
               3.482000000 |
               3.681000000 |
Query OK, 6 rows in database (0.028810s)
taos> select ts,avg(cpu) from metrics  WHERE  ts> now-1m INTERVAL(10s);
DB error: No valid function in window query (0.007084s)

**Comment by yejinmo** [comment]
类似的问题，在 `2.6` 版本中使用命令 

```sql
select interp(`value`) from history.history_0 where time >= 1629043200000 and time <= 1629129600000 interval(3600000a) fill(linear) limit 10000;
```
即可查询等间隔插值，在 `3.0` 中此命令报错 `DB error: interp function is not supported in window query or group query (0.001200s)`，根据文档切换为下边命令后没有时间列

```sql
taos> select interp(`value`) from history.history_0 range(1629043200000, 1629129600000) every(3600000a) fill(linear) l
imit 10000;
      interp(`value`)      |
============================
              22.500589319 |
              75.502578269 |
              52.136298343 |
              17.714953959 |
              43.848674033 |
              66.855653775 |
              57.188674033 |
Query OK, 7 rows in database (4.519298s)
```

手动添加 `time` 报错：

```sql
taos> select time, interp(`value`) from history.history_0 range(1629043200000, 1629129600000) every(3600000a) fill(lin
ear) limit 10000;

DB error: Not a single-group group function (0.001386s)
```

根据 [伪列文档](https://docs.taosdata.com/taos-sql/select/#%E4%BC%AA%E5%88%97)

> _c0/_ROWTS
> TDengine 中，所有表的第一列都必须是时间戳类型，且为其主键，_rowts 伪列和_c0 伪列均代表了此列的值。相比实际的主键时间戳列，使用伪列更加灵活，语义也更加标准。例如，可以和 max\min 等函数一起使用。

手动添加伪列后报错：

```sql
taos> select _rowts, interp(`value`) from history.history_0 range(1629043200000, 1629129600000) every(3600000a) fill(l
inear) limit 10000;

DB error: Not a single-group group function (0.001397s)
```

**Comment by proxiti** [comment]
3.0 的特性，用伪列 _WSTART。select _WSTART, avg(v) from table1 INTERVAL(1m);

**Comment by yejinmo** [comment]
> 3.0 的特性，用伪列 _WSTART。select _WSTART, avg(v) from table1 INTERVAL(1m);

对于聚合函数可使用 `_wstart` ，对于插值函数 `interp` 此伪列报错：

```sql
taos> select _wstart, interp(`value`) as `value` from history.history_0 range(1658073600000, 1658160000000) every(3600
000a) fill(linear) limit 10000;

DB error: _WSTART, _WEND and _WDURATION can only be used in window query (0.001306s)
```

> https://docs.taosdata.com/taos-sql/function/#interp

**Comment by guilter** [comment]
大佬，这问题解决了么？我使用3.1.0.1版本依然出现这个问题，该如何解决？

**Comment by yu285** [comment]
官网搜索 “伪列”即可
