### ISSUE TITLE
Unable to load DLL 'taos' or one of its dependencies: 找不到指定的模块

### ISSUE THREAD

**Issue by jiangzhuangxiansheng** [taosdata/TDengine#16157]
**Bug Description**
使用TDengine.Connector 连接服务器，报错：Unable to load DLL 'taos' or one of its dependencies: 找不到指定的模块
![image](https://user-images.githubusercontent.com/33273148/184851844-b718daff-3db1-4d60-ac5c-f479b2881570.png)
已经按照示例解决方案 ： Linux 下建立如下软链接 ln -s /usr/local/taos/driver/libtaos.so.x.x.x.x /usr/lib/libtaos.so
依然无效

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.6]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 3.0.0.0]

**Additional Context**

**Comment by jiangzhuangxiansheng** [comment]
是client的原因

**Comment by ElevenFan** [comment]
怎么解决的？
