### ISSUE TITLE
Table name escape character error in Ver 3.0

### ISSUE THREAD

**Issue by zhangxuejian-a** [taosdata/TDengine#16158]
**Environment (please complete the following information):**
 - OS: Ubuntu
 - TDengine Version 3.0.0

文档中表名转义字符为“`”,在TDengine Version 2.x中使用正常
升级为3.0.0后，转义字符"`"无法正常使用，而“'”(英文单引号)作为转义字符可正常使用。

**Comment by oliver225** [comment]
<img width="469" alt="344ecd13f4adae39f9feee889d6e3c3" src="https://user-images.githubusercontent.com/16226897/185007588-964d51c6-fcb8-404d-ae00-9ee092052af6.png">
<img width="698" alt="b77a04ffda57c6a4e030b02e00411cb" src="https://user-images.githubusercontent.com/16226897/185007638-521077df-afab-4dac-9944-d0a0c7cf8574.png">
