### ISSUE TITLE
taosd.exe crash at first connection with taos.exe

### ISSUE THREAD

**Issue by trampeagle** [taosdata/TDengine#16167]
**Bug Description**
taosd.exe in windows version of 3.0.0.0 can't work, it crashes at first conection from taos.exe

**To Reproduce**
1. Download and install windows version of TDengine of 3.0.0.0 x64 version
2. change taos.cfg to set one node and log dir, data dir and tmp dir to another hard disk driver
3. starts taosd.exe in windows cmd
4. open another windows cmd to start taos.exe
5. taosd.exe crashes with pop windows dialog of "Debug Error!". detail in screenshots

**Expected Behavior**
taosd.exe should work 

**Screenshots**
![image](https://user-images.githubusercontent.com/15955461/184913325-bfdb0d8c-79ec-4349-bf38-b9385621f15f.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Home edition
 - Memory 16G , CPU i7, current Disk Space 1T
 - TDengine Version 3.0.0.0

**Additional Context**

**Comment by trampeagle** [comment]
stack status at the crash poinit
![image](https://user-images.githubusercontent.com/15955461/185060756-71dafa8e-ae25-49fc-97f3-d184f0d6b33f.png)

the function 
![image](https://user-images.githubusercontent.com/15955461/185060899-45833b44-9952-4f0e-ae04-79142a35ff99.png)

**Comment by yu285** [comment]
3.0早期版本的bug 都已经全部修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。
