### ISSUE TITLE
cannot connect server on windows client

### ISSUE THREAD

**Issue by BlazarS** [taosdata/TDengine#1616]
## 问题：windows无法连接server，Linux没有问题

server version:1.6.5.7

clinet version:1.6.5.7

-----------------------------------------------------------------------------------------
             new log file                      
==================================================
04/15 23:10:37.931000 0x23980 UTL timezone not configured, use default
04/15 23:10:37.946000 0x23980 UTL locale not configured, set to default:Chinese_China.936
04/15 23:10:37.946000 0x23980 UTL charset not configured, set to default:cp936
04/15 23:10:37.946000 0x23980 UTL    taos config & system info:
04/15 23:10:37.946000 0x23980 UTL ==================================
04/15 23:10:37.946000 0x23980 UTL  localIp:                0.0.0.0 
04/15 23:10:37.946000 0x23980 UTL  mgmtShellPort:          6030 
04/15 23:10:37.946000 0x23980 UTL  vnodeShellPort:         6035 
04/15 23:10:37.946000 0x23980 UTL  configDir:              C:/TDengine/cfg 
04/15 23:10:37.946000 0x23980 UTL  logDir:                 C:/TDengine/log 
04/15 23:10:37.946000 0x23980 UTL  scriptDir:              C:/TDengine/script 
04/15 23:10:37.946000 0x23980 UTL  numOfThreadsPerCore:    1.000000 
04/15 23:10:37.946000 0x23980 UTL  affectedRowsMod:        0 
04/15 23:10:37.946000 0x23980 UTL  rpcTimer:               300(ms)
04/15 23:10:37.946000 0x23980 UTL  rpcMaxTime:             600(s)
04/15 23:10:37.946000 0x23980 UTL  shellActivityTimer:     3(s)
04/15 23:10:37.946000 0x23980 UTL  meterMetaKeepTimer:     7200(s)
04/15 23:10:37.946000 0x23980 UTL  metricMetaKeepTimer:    600(s)
04/15 23:10:37.946000 0x23980 UTL  defaultDB:               
04/15 23:10:37.946000 0x23980 UTL  defaultUser:            root 
04/15 23:10:37.946000 0x23980 UTL  sockettype:             tcp 
04/15 23:10:37.946000 0x23980 UTL  compressMsgSize:        -1 
04/15 23:10:37.946000 0x23980 UTL  maxSQLLength:           65380(byte)
04/15 23:10:37.946000 0x23980 UTL  timezone:               not configured 
04/15 23:10:37.946000 0x23980 UTL  locale:                 Chinese_China.936 
04/15 23:10:37.946000 0x23980 UTL  charset:                cp936 
04/15 23:10:37.946000 0x23980 UTL  numOfLogLines:          10000000 
04/15 23:10:37.946000 0x23980 UTL  asyncLog:               1 
04/15 23:10:37.946000 0x23980 UTL  debugFlag:              131 
04/15 23:10:37.946000 0x23980 UTL  rpcDebugFlag:           131 
04/15 23:10:37.946000 0x23980 UTL  tmrDebugFlag:           131 
04/15 23:10:37.946000 0x23980 UTL  cDebugFlag:             131 
04/15 23:10:37.946000 0x23980 UTL  jniDebugFlag:           131 
04/15 23:10:37.946000 0x23980 UTL  odbcDebugFlag:          131 
04/15 23:10:37.946000 0x23980 UTL  uDebugFlag:             131 
04/15 23:10:37.946000 0x23980 UTL  qDebugFlag:             131 
04/15 23:10:37.946000 0x23980 UTL  gitinfo:                f83c59e8c4e1a51d33b4f3841e251e5fbf7f2319 
04/15 23:10:37.946000 0x23980 UTL  gitinfoOfInternal:      4cbf1f2c2cee44d99f6b78773e95ee40ce9ffdda 
04/15 23:10:37.946000 0x23980 UTL  buildinfo:              Built by root at 2020-04-04 15:11 
04/15 23:10:37.946000 0x23980 UTL  version:                1.6.5.7 
04/15 23:10:37.946000 0x23980 UTL  dataDir:                C:/TDengine/data
04/15 23:10:37.946000 0x23980 UTL ==================================
04/15 23:10:37.946000 0x23980 ERROR RPC InitTcpClient not support in windows
04/15 23:10:37.946000 0x23980 ERROR RPC TSC-vnode, failed to init network, 0.0.0.0:0
04/15 23:10:37.946000 0x23980 ERROR RPC SendTcpClientData not support in windows

**Comment by qz-c-source** [comment]
04/15 23:10:37.946000 0x23980 ERROR RPC InitTcpClient not support in windows

**Comment by liuyq-617** [comment]
https://www.taosdata.com/blog/2020/03/27/1366.html

**Comment by sangshuduo** [comment]
请试用 2.0 版本
