### ISSUE TITLE
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

### ISSUE THREAD

**Issue by weiwxg** [taosdata/TDengine#16168]
在使用C#驱动查询数据时经常报错，经观察在进行一个频繁耗时的查询时，发生该问题的概率非常高。比如在一个数据量比较大的超级表中，执行一个包含普通Field的Group By语句，就会抛出如上的错误

**Comment by fenghuazzm** [comment]
麻烦提供一下 TDengine 版本、C#驱动版本以及 SQL 语句
