### ISSUE TITLE
How to query the tags data corresponding to all sub-tables in the super table?

### ISSUE THREAD

**Issue by chenjie0927** [taosdata/TDengine#16176]
先前，采用超级表，赋值子表TAGS标签数据的方式，创建了子表。现在想通过超级表，把所有的子表的TAGS标签数据全部查出来，形成设备明细总表清单。
建议，提供便捷的SQL查询方法，方便获取子表的元数据信息。

![20220817111835](https://user-images.githubusercontent.com/13298514/185027774-5832079f-92cb-491f-834b-54a4d9e929a2.png)

**Comment by yejinmo** [comment]
针对3.0目前尝试出了两种方法：

### 1. 用新加的 `Information_Schema` 元数据数据库查询

> https://docs.taosdata.com/taos-sql/meta/#ins_stables

_ 目前测试这种方式查询速度没有第二种方法快_

### 2. 用 `distinct` 去重命令结合查询命令

```sql
select distinct tbname, [tag1, tag2, ...] from [stable];
````

> https://docs.taosdata.com/taos-sql/select/#%E7%BB%93%E6%9E%9C%E5%8E%BB%E9%87%8D

**Comment by chenjie0927** [comment]
谢谢。
________________________________
发件人: YeJinMo ***@***.***>
发送时间: 2022年8月17日 5:55
收件人: taosdata/TDengine ***@***.***>
抄送: chenjie0927 ***@***.***>; Author ***@***.***>
主题: Re: [taosdata/TDengine] 如何查询超级表下所有的子表对应的TAGS标签数据？ (Issue #16176)


针对3.0目前尝试出了两种方法：

1. 用新加的 Information_Schema 元数据数据库查询

https://docs.taosdata.com/taos-sql/meta/#ins_stables<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.taosdata.com%2Ftaos-sql%2Fmeta%2F%23ins_stables&data=05%7C01%7C%7Cd72bc47861784e71172008da80150dc4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637963125172413193%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ilH%2Be68CxnxqJWn%2FsqaOgDl6d2YxhNBPEoX9MzmXIYw%3D&reserved=0>

_ 目前测试这种方式查询速度没有第二种方法快_

2. 用 distinct 去重命令结合查询命令

select distinct tbname, [tag1, tag2, ...] from [stable];

https://docs.taosdata.com/taos-sql/select/#%E7%BB%93%E6%9E%9C%E5%8E%BB%E9%87%8D<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.taosdata.com%2Ftaos-sql%2Fselect%2F%23%25E7%25BB%2593%25E6%259E%259C%25E5%258E%25BB%25E9%2587%258D&data=05%7C01%7C%7Cd72bc47861784e71172008da80150dc4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637963125172413193%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KYnAMUE%2F%2FXQiByqi4UBZFxs6CjgAAeGRIpEbwZafixk%3D&reserved=0>

―
