### ISSUE TITLE
Give some suggestions about the default log level of TaosAdapter

### ISSUE THREAD

**Issue by cockroach888** [taosdata/TDengine#16171]
我查看了一下3.0中 /etc/taos/taosadapter.toml 里面的 logLevel = "info" 默认还是 info。
实测过高速入库时，日志太过频繁了，需要手动来改这个配置，而通常生产环境时，是不需要太过详细的日志，以免影响到生产。
建议默认改为warning或错误级别，然后把这个日志级别，放到醒目的地方。
例如，创建docker容器的时候，可以有哪些环境变量可以设置等。

另外，可以在Docker应用文档里，把一些常用的环境变量配置，做一个表格列举说明。

还有一点就是 RESTful API 在2.x和3.x的返回结果改变很大，但是对于返回的code编码，依然没有给出一个可以详细理解的列表，是否考虑？

**Comment by fenghuazzm** [comment]
您的需求是：
1. taosadapter 默认日志等级最好要比 info 低；
2. 文档罗列 Docker 部署常见环境变量；
3. 文档列出 RESTful 新 API 各种返回码。
感谢反馈！

**Comment by cockroach888** [comment]
对，是的。因为我目前在做业务的实践联合测试工作，而且数据是高速入库，对入库的完整性有要求。

**Comment by fenghuazzm** [comment]
> 对，是的。因为我目前在做业务的实践联合测试工作，而且数据是高速入库，对入库的完整性有要求。

相关建议都已收到，我们内部相关同学将开始对其做调整，欢迎持续关注

**Comment by cockroach888** [comment]
> 


会的，近期也正在研究3.0的应用。
