### ISSUE TITLE
Version 3.0 calls taos_init to pop up a flashing black console

### ISSUE THREAD

**Issue by xunzhimeng** [taosdata/TDengine#16172]
**Bug Description**
When I used library taos.dll 3.0, the program calls taos_init to pop up a flashing black console.
Debug to it,I found taos_init() calls winapi _popen function,then the console come out.

**To Reproduce**
1. taos_options(TSDB_OPTION_TIMEZONE, "GMT-8");
2. See Console

**Expected Behavior**
GUI progarm using taos.dll pop up a flashing black console

**Screenshots**
![05b7f8f39c8ca4d3aede0ceeeb96a35](https://user-images.githubusercontent.com/30234263/185020524-94a2d7ba-b202-41b8-9dae-978816e1f286.jpg)

**Environment (please complete the following information):**
 - OS: Win10
 - Memory, CPU, current Disk Space
 - TDengine Version 3.0.0.0

**Additional Context**
Stack:
taos.dll!taosOpenCmd(const char * cmd) line 245	C
taos.dll!cfgLoadFromEnvVar(SConfig * pConfig) line 634	C
taos.dll!taosLoadCfg(SConfig * pCfg, const char * * envCmd, const char * inputCfgDir, const char * envFile, char * apolloUrl) line  222	C
taos.dll!taosCreateLog(const char * logname, int logFileNum, const char * cfgDir, const char * * envCmd, const char * envFile, char * apolloUrl, SArray * pArgs, bool tsc) line  954	C
taos.dll!taos_init_imp() line 374	C
taos.dll!pthread_once(pthread_once_t_ * once_control, void(*)() init_routine) line  80	C
taos.dll!taos_init(...) line  415	C
taos.dll!taos_options_imp(TSDB_OPTION option, const char * str) line  421	C
taos.dll!taos_options(TSDB_OPTION option, const void * arg, ...) line  47	C

**Comment by fenghuazzm** [comment]
感谢反馈，已经转给相关的同学看了
