### ISSUE TITLE
some node works as offline 

### ISSUE THREAD

**Issue by 13612858893** [taosdata/TDengine#16184]
**Bug Description**
服务器重启后部分节点不能识别
启动后提示无法连接到服务器，提示如下
![224222005135f299586ed9a7f2d9488](https://user-images.githubusercontent.com/111417004/185056264-9dc5e35d-1ef0-4e46-973d-eb4bdaf27c50.png)
查看dnodes，发现节点2没有启动
![7c1e0c38cdba48a26f23fa249391826](https://user-images.githubusercontent.com/111417004/185056800-5fc30d6a-5602-4b06-a0df-d470e4c6fefa.png)
查节点对应的IP为10.0.40.182
![image](https://user-images.githubusercontent.com/111417004/185056983-ca875dd4-6ad6-425e-968c-2216f5bac462.png)
查看节点2的服务，发现是正常的
![de2fd70a66c6547f1ed61af50a589d0](https://user-images.githubusercontent.com/111417004/185057072-47a2ccd3-2a9f-4fc6-b460-5bc46b5aaff6.png)
依次重启节点3、2、1的服务后，发现节点2的服务还是离线状态。

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by plum-lihui** [comment]
能够让我们远程定位一下吗？

**Comment by 13612858893** [comment]
可以的，我微信手机号是：13612858893
















在 2022-08-17 14:35:46，"Hui Li" ***@***.***> 写道：

能够让我们远程定位一下吗？
