### ISSUE TITLE
taosd.service: Failed with result 'signal'.

### ISSUE THREAD

**Issue by Lao-Zhong** [taosdata/TDengine#16197]
root@bhiot3:~# systemctl status taosd
● taosd.service - TDengine server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Wed 2022-08-17 22:25:58 CST; 2min 40s ago
  Process: 18528 ExecStart=/usr/bin/taosd (code=killed, signal=ABRT)
  Process: 18513 ExecStartPre=/usr/local/taos/bin/startPre.sh (code=exited, status=0/SUCCESS)
 Main PID: 18528 (code=killed, signal=ABRT)

Aug 17 22:25:58 bhiot3 systemd[1]: taosd.service: Service hold-off time over, scheduling restart.
Aug 17 22:25:58 bhiot3 systemd[1]: taosd.service: Scheduled restart job, restart counter is at 3.
Aug 17 22:25:58 bhiot3 systemd[1]: Stopped TDengine server service.
Aug 17 22:25:58 bhiot3 systemd[1]: taosd.service: Start request repeated too quickly.
Aug 17 22:25:58 bhiot3 systemd[1]: taosd.service: Failed with result 'signal'.
Aug 17 22:25:58 bhiot3 systemd[1]: Failed to start TDengine server service.

root@bhiot3:/usr/local/taos/bin# ./taosd
08/17 22:33:40.544626 00027684 DND start to initialize TDengine
08/17 22:33:40.544695 00027684 DND step:dnode-tfile is initialized
08/17 22:33:40.544716 00027684 DND step:dnode-rpc is initialized
08/17 22:33:40.544725 00027684 UTL localEp is: bhiot.taos2:6030
08/17 22:33:40.545065 00027684 UTL timezone is set to Asia/Shanghai by config file
08/17 22:33:40.545094 00027684 UTL timezone format changed to (CST, +0800)
08/17 22:33:40.545112 00027684 UTL    check global cfg completed
08/17 22:33:40.545117 00027684 UTL ==================================
08/17 22:33:40.545124 00027684 UTL    taos config & system info:
08/17 22:33:40.545128 00027684 UTL ==================================
08/17 22:33:40.545137 00027684 UTL  firstEp:                bhiot.taos1:6030 
08/17 22:33:40.545146 00027684 UTL  secondEp:               bhiot.taos2:6030 
08/17 22:33:40.545153 00027684 UTL  fqdn:                   bhiot.taos2 
08/17 22:33:40.545160 00027684 UTL  serverPort:             6030 
08/17 22:33:40.545166 00027684 UTL  configDir:              /etc/taos 
08/17 22:33:40.545173 00027684 UTL  logDir:                 /data/taosdb/log 
08/17 22:33:40.545188 00027684 UTL  scriptDir:              /etc/taos 
08/17 22:33:40.545196 00027684 UTL  arbitrator:              
08/17 22:33:40.545202 00027684 UTL  numOfThreadsPerCore:    1.000000 
08/17 22:33:40.545212 00027684 UTL  numOfCommitThreads:     4 
08/17 22:33:40.545218 00027684 UTL  ratioOfQueryCores:      1.000000 
08/17 22:33:40.545224 00027684 UTL  numOfMnodes:            1 
08/17 22:33:40.545231 00027684 UTL  vnodeBak:               1 
08/17 22:33:40.545237 00027684 UTL  telemetryReporting:     1 
08/17 22:33:40.545243 00027684 UTL  balance:                1 
08/17 22:33:40.545249 00027684 UTL  balanceInterval:        300 
08/17 22:33:40.545255 00027684 UTL  role:                   0 
08/17 22:33:40.545261 00027684 UTL  maxTmrCtrl:             512 
08/17 22:33:40.545267 00027684 UTL  monitorInterval:        30(s)
08/17 22:33:40.545273 00027684 UTL  offlineThreshold:       864000(s)
08/17 22:33:40.545279 00027684 UTL  rpcTimer:               300(ms)
08/17 22:33:40.545285 00027684 UTL  rpcMaxTime:             600(s)
08/17 22:33:40.545291 00027684 UTL  statusInterval:         1(s)
08/17 22:33:40.545296 00027684 UTL  shellActivityTimer:     3(s)
08/17 22:33:40.545302 00027684 UTL  minSlidingTime:         10(ms)
08/17 22:33:40.545308 00027684 UTL  minIntervalTime:        10(ms)
08/17 22:33:40.545314 00027684 UTL  maxStreamCompDelay:     20000(ms)
08/17 22:33:40.545320 00027684 UTL  maxFirstStreamCompDelay:10000(ms)
08/17 22:33:40.545326 00027684 UTL  retryStreamCompDelay:   10000(ms)
08/17 22:33:40.545331 00027684 UTL  streamCompDelayRatio:   0.100000 
08/17 22:33:40.545338 00027684 UTL  maxVgroupsPerDb:        0 
08/17 22:33:40.545345 00027684 UTL  maxTablesPerVnode:      1000000 
08/17 22:33:40.545351 00027684 UTL  minTablesPerVnode:      1000 
08/17 22:33:40.545357 00027684 UTL  tableIncStepPerVnode:   1000 
08/17 22:33:40.545363 00027684 UTL  cache:                  16(Mb)
08/17 22:33:40.545369 00027684 UTL  blocks:                 6 
08/17 22:33:40.545373 00027684 UTL  days:                   10 
08/17 22:33:40.545379 00027684 UTL  keep:                   3650 
08/17 22:33:40.545384 00027684 UTL  minRows:                100 
08/17 22:33:40.545390 00027684 UTL  maxRows:                4096 
08/17 22:33:40.545396 00027684 UTL  precision:              0 
08/17 22:33:40.545402 00027684 UTL  comp:                   2 
08/17 22:33:40.545408 00027684 UTL  walLevel:               2 
08/17 22:33:40.545414 00027684 UTL  fsync:                  3000 
08/17 22:33:40.545420 00027684 UTL  replica:                1 
08/17 22:33:40.545426 00027684 UTL  partitions:             4 
08/17 22:33:40.545432 00027684 UTL  quorum:                 1 
08/17 22:33:40.545438 00027684 UTL  update:                 0 
08/17 22:33:40.545445 00027684 UTL  cachelast:              0 
08/17 22:33:40.545451 00027684 UTL  compressMsgSize:        -1 
08/17 22:33:40.545457 00027684 UTL  maxSQLLength:           1048576(byte)
08/17 22:33:40.545467 00027684 UTL  maxNumOfOrderedRes:     100000 
08/17 22:33:40.545473 00027684 UTL  queryBufferSize:        -1(byte)
08/17 22:33:40.545479 00027684 UTL  retrieveBlockingModel:  0 
08/17 22:33:40.545485 00027684 UTL  keepColumnName:         0 
08/17 22:33:40.545491 00027684 UTL  timezone:               (CST, +0800) 
08/17 22:33:40.545498 00027684 UTL  locale:                 en_US.UTF-8 
08/17 22:33:40.545504 00027684 UTL  charset:                UTF-8 
08/17 22:33:40.545510 00027684 UTL  maxShellConns:          5000 
08/17 22:33:40.545516 00027684 UTL  maxConnections:         5000 
08/17 22:33:40.545522 00027684 UTL  minimalLogDirGB:        1.000000(GB)
08/17 22:33:40.545529 00027684 UTL  minimalTmpDirGB:        1.000000(GB)
08/17 22:33:40.545535 00027684 UTL  minimalDataDirGB:       2.000000(GB)
08/17 22:33:40.545541 00027684 UTL  mnodeEqualVnodeNum:     4 
08/17 22:33:40.545547 00027684 UTL  flowctrl:               1 
08/17 22:33:40.545553 00027684 UTL  slaveQuery:             1 
08/17 22:33:40.545558 00027684 UTL  adjustMaster:           1 
08/17 22:33:40.545568 00027684 UTL  http:                   1 
08/17 22:33:40.545575 00027684 UTL  mqtt:                   0 
08/17 22:33:40.545581 00027684 UTL  monitor:                1 
08/17 22:33:40.545595 00027684 UTL  stream:                 1 
08/17 22:33:40.545602 00027684 UTL  httpEnableRecordSql:    0 
08/17 22:33:40.545608 00027684 UTL  telegrafUseFieldNum:    0 
08/17 22:33:40.545614 00027684 UTL  httpMaxThreads:         2000 
08/17 22:33:40.545621 00027684 UTL  restfulRowLimit:        10240 
08/17 22:33:40.545627 00027684 UTL  numOfLogLines:          10000000 
08/17 22:33:40.545633 00027684 UTL  logKeepDays:            0 
08/17 22:33:40.545639 00027684 UTL  asyncLog:               1 
08/17 22:33:40.545645 00027684 UTL  debugFlag:              0 
08/17 22:33:40.545651 00027684 UTL  mDebugFlag:             131 
08/17 22:33:40.545657 00027684 UTL  dDebugFlag:             135 
08/17 22:33:40.545663 00027684 UTL  sDebugFlag:             135 
08/17 22:33:40.545669 00027684 UTL  wDebugFlag:             135 
08/17 22:33:40.545675 00027684 UTL  sdbDebugFlag:           131 
08/17 22:33:40.545681 00027684 UTL  rpcDebugFlag:           131 
08/17 22:33:40.545687 00027684 UTL  tmrDebugFlag:           131 
08/17 22:33:40.545694 00027684 UTL  cDebugFlag:             131 
08/17 22:33:40.545700 00027684 UTL  jniDebugFlag:           131 
08/17 22:33:40.545706 00027684 UTL  odbcDebugFlag:          131 
08/17 22:33:40.545712 00027684 UTL  uDebugFlag:             131 
08/17 22:33:40.545718 00027684 UTL  httpDebugFlag:          131 
08/17 22:33:40.545724 00027684 UTL  mqttDebugFlag:          131 
08/17 22:33:40.545730 00027684 UTL  monDebugFlag:           131 
08/17 22:33:40.545736 00027684 UTL  qDebugFlag:             131 
08/17 22:33:40.545741 00027684 UTL  vDebugFlag:             135 
08/17 22:33:40.545747 00027684 UTL  tsdbDebugFlag:          143 
08/17 22:33:40.545753 00027684 UTL  cqDebugFlag:            131 
08/17 22:33:40.545759 00027684 UTL  enableRecordSql:        0 
08/17 22:33:40.545766 00027684 UTL  enableCoreFile:         0 
08/17 22:33:40.545770 00027684 UTL  gitinfo:                c763ec8c670b2886818afb4ff16c4a5377ba7b27 
08/17 22:33:40.545777 00027684 UTL  gitinfoOfInternal:      NULL 
08/17 22:33:40.545783 00027684 UTL  buildinfo:              Built at 2021-09-09 16:40 
08/17 22:33:40.545789 00027684 UTL  version:                2.0.20.17 
08/17 22:33:40.545795 00027684 UTL  maxBinaryDisplayWidth:  30 
08/17 22:33:40.545801 00027684 UTL  tempDir:                /tmp/ 
08/17 22:33:40.545808 00027684 UTL  os pageSize:            4096(KB)
08/17 22:33:40.545818 00027684 UTL  os openMax:             63868
08/17 22:33:40.545824 00027684 UTL  os streamMax:           16
08/17 22:33:40.545830 00027684 UTL  os numOfCores:          8
08/17 22:33:40.545836 00027684 UTL  os totalMemory:         16027(MB)
08/17 22:33:40.545843 00027684 UTL  os sysname:             Linux
08/17 22:33:40.545849 00027684 UTL  os nodename:            bhiot3
08/17 22:33:40.545855 00027684 UTL  os release:             4.15.0-191-generic
08/17 22:33:40.545866 00027684 UTL  os version:             #202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022
08/17 22:33:40.545872 00027684 UTL  os machine:             x86_64
08/17 22:33:40.545879 00027684 UTL  dataDir: /data/taosdb/datas
08/17 22:33:40.545885 00027684 UTL ==================================
08/17 22:33:40.545890 00027684 DND step:dnode-globalcfg is initialized
08/17 22:33:40.545917 00027684 TFS disk /data/taosdb/datas is mounted to tier level 0 id 0
08/17 22:33:40.546002 00027684 UTL ==================================
08/17 22:33:40.546018 00027684 UTL  os totalDisk:           491.957153(GB)
08/17 22:33:40.546029 00027684 UTL  os usedDisk:            52.044132(GB)
08/17 22:33:40.546036 00027684 UTL  os availDisk:           414.897400(GB)
08/17 22:33:40.546043 00027684 UTL ==================================
08/17 22:33:40.546052 00027684 DND dnode storage is initialized at /data/taosdb/datas/dnode
08/17 22:33:40.546058 00027684 DND step:dnode-storage is initialized
08/17 22:33:40.546099 00027684 DND read file /data/taosdb/datas/dnode/dnodeCfg.json successed
08/17 22:33:40.546117 00027684 DND dnodeId is set to 2, clusterId is set to 415943a7-a326-4c39-aec4-a8c239ce1b85
08/17 22:33:40.546868 00027684 DND successed to write /data/taosdb/datas/dnode/dnodeCfg.json
08/17 22:33:40.546887 00027684 DND dnode cfg is initialized
08/17 22:33:40.546893 00027684 DND step:dnode-cfg is initialized
08/17 22:33:40.546946 00027684 DND read file /data/taosdb/datas/dnode/dnodeEps.json successed
08/17 22:33:40.546988 00027684 DND dnode eps is initialized
08/17 22:33:40.546996 00027684 DND step:dnode-eps is initialized
08/17 22:33:40.547022 00027684 DND read file /data/taosdb/datas/dnode/mnodeEpSet.json successed
08/17 22:33:40.547030 00027684 DND print minfos, mnodeNum:3 inUse:0
08/17 22:33:40.547039 00027684 DND mnode index:1, bhiot.taos1:6030
08/17 22:33:40.547044 00027684 DND mnode index:2, bhiot.taos2:6030
08/17 22:33:40.547050 00027684 DND mnode index:4, bhiot.taos3:6030
08/17 22:33:40.547059 00027684 DND print minfos, mnodeNum:3 inUse:0
08/17 22:33:40.547065 00027684 DND mnode index:1, bhiot.taos1:6030
08/17 22:33:40.547072 00027684 DND mnode index:2, bhiot.taos2:6030
08/17 22:33:40.547078 00027684 DND mnode index:4, bhiot.taos3:6030
08/17 22:33:40.547084 00027684 DND dnode minfos is initialized
08/17 22:33:40.547090 00027684 DND step:dnode-minfos is initialized
08/17 22:33:40.547140 00027684 WAL wal module is initialized, rsetId:3
08/17 22:33:40.547148 00027684 DND step:dnode-wal is initialized
08/17 22:33:40.547235 00027684 DND step:dnode-sync is initialized
08/17 22:33:40.547256 00027684 DND dnode check is initialized
08/17 22:33:40.547264 00027684 DND step:dnode-check is initialized
08/17 22:33:40.547272 00027684 UTL worker:vquery is initialized, min:8 max:8
08/17 22:33:40.547282 00027684 UTL worker:vfetch is initialized, min:4 max:4
08/17 22:33:40.547289 00027684 DND step:dnode-vread is initialized
08/17 22:33:40.547297 00027684 DND dnode vwrite is initialized, max worker 8
08/17 22:33:40.547302 00027684 DND step:dnode-vwrite is initialized
08/17 22:33:40.547343 00027684 DND step:vnode-backup is initialized
08/17 22:33:40.547388 00027684 DND step:vnode-worker is initialized
08/17 22:33:40.547396 00027684 DND step:vnode-write is initialized
08/17 22:33:40.547405 00027684 DND step:vnode-read is initialized
08/17 22:33:40.547413 00027684 DND step:vnode-hash is initialized
08/17 22:33:40.547523 00027684 DND step:tsdb-queue is initialized
08/17 22:33:40.547533 00027684 UTL worker:vmgmt is initialized, min:1 max:1
08/17 22:33:40.547576 00027684 DND dnode vmgmt is initialized
08/17 22:33:40.547603 00027684 DND step:dnode-vmgmt is initialized
08/17 22:33:40.547618 00027684 DND step:dnode-mread is initialized
08/17 22:33:40.547630 00027684 DND step:dnode-mwrite is initialized
08/17 22:33:40.547640 00027684 DND step:dnode-mpeer is initialized
08/17 22:33:40.550892 00027684 DND dnode inter-dnodes rpc client is initialized
08/17 22:33:40.550915 00027684 DND step:dnode-client is initialized
08/17 22:33:40.551470 00027684 DND dnode inter-dnodes RPC server is initialized
08/17 22:33:40.551485 00027684 DND step:dnode-server is initialized
08/17 22:33:40.551516 00027684 DND start 8 threads to open 9 vnodes
08/17 22:33:40.551875 00027703 VND vgId:13, load vnode cfg successfully, replcia:3
08/17 22:33:40.551965 00027703 VND vgId:13, dnode:4, bhiot.taos3:6040
08/17 22:33:40.552062 00027703 VND vgId:13, dnode:2, bhiot.taos2:6040
08/17 22:33:40.552073 00027703 VND vgId:13, dnode:1, bhiot.taos1:6040
08/17 22:33:40.552095 00027703 VND vgId:13, read /data/taosdb/datas/vnode/vnode13/version.json successfully, fver:2259246
08/17 22:33:40.552187 00027702 VND vgId:11, load vnode cfg successfully, replcia:3
08/17 22:33:40.552358 00027704 VND vgId:16, load vnode cfg successfully, replcia:1
08/17 22:33:40.552431 00027704 VND vgId:16, dnode:2, bhiot.taos2:6040
08/17 22:33:40.552451 00027704 VND vgId:16, read /data/taosdb/datas/vnode/vnode16/version.json successfully, fver:4870817
08/17 22:33:40.552497 00027705 VND vgId:2, load vnode cfg successfully, replcia:1
08/17 22:33:40.552345 00027702 VND vgId:11, dnode:2, bhiot.taos2:6040
08/17 22:33:40.552699 00027705 VND vgId:2, dnode:2, bhiot.taos2:6040
08/17 22:33:40.552746 00027705 VND vgId:2, read /data/taosdb/datas/vnode/vnode2/version.json successfully, fver:6069521
08/17 22:33:40.552562 00027706 VND vgId:4, load vnode cfg successfully, replcia:1
08/17 22:33:40.552567 00027707 VND vgId:15, load vnode cfg successfully, replcia:3
08/17 22:33:40.552723 00027702 VND vgId:11, dnode:4, bhiot.taos3:6040
08/17 22:33:40.552773 00027706 VND vgId:4, dnode:2, bhiot.taos2:6040
08/17 22:33:40.552816 00027707 VND vgId:15, dnode:2, bhiot.taos2:6040
08/17 22:33:40.552820 00027702 VND vgId:11, dnode:1, bhiot.taos1:6040
08/17 22:33:40.552832 00027707 VND vgId:15, dnode:1, bhiot.taos1:6040
08/17 22:33:40.552839 00027706 VND vgId:4, read /data/taosdb/datas/vnode/vnode4/version.json successfully, fver:33839271
08/17 22:33:40.552841 00027707 VND vgId:15, dnode:4, bhiot.taos3:6040
08/17 22:33:40.552858 00027702 VND vgId:11, read /data/taosdb/datas/vnode/vnode11/version.json successfully, fver:4381113
08/17 22:33:40.552879 00027707 VND vgId:15, read /data/taosdb/datas/vnode/vnode15/version.json successfully, fver:25767
08/17 22:33:40.553008 00027711 VND vgId:10, load vnode cfg successfully, replcia:3
08/17 22:33:40.553016 00027709 VND vgId:9, load vnode cfg successfully, replcia:3
08/17 22:33:40.553059 00027711 VND vgId:10, dnode:4, bhiot.taos3:6040
08/17 22:33:40.553062 00027709 VND vgId:9, dnode:1, bhiot.taos1:6040
08/17 22:33:40.553077 00027711 VND vgId:10, dnode:2, bhiot.taos2:6040
08/17 22:33:40.553119 00027711 VND vgId:10, dnode:1, bhiot.taos1:6040
08/17 22:33:40.553082 00027709 VND vgId:9, dnode:4, bhiot.taos3:6040
08/17 22:33:40.553143 00027711 VND vgId:10, read /data/taosdb/datas/vnode/vnode10/version.json successfully, fver:3760308
08/17 22:33:40.553184 00027709 VND vgId:9, dnode:2, bhiot.taos2:6040
08/17 22:33:40.553309 00027709 VND vgId:9, read /data/taosdb/datas/vnode/vnode9/version.json successfully, fver:4666860
08/17 22:33:40.555481 00027705 WAL vgId:2, file:/data/taosdb/datas/vnode/vnode2/wal/wal1, will be restored
08/17 22:33:40.555636 00027705 WAL vgId:2, file:/data/taosdb/datas/vnode/vnode2/wal/wal1, restore success, wver:0
08/17 22:33:40.555788 00027705 WAL vgId:2, wal:0x7f741c02dc60 file:/data/taosdb/datas/vnode/vnode2/wal/wal1, it is removed
08/17 22:33:40.556114 00027705 VND vgId:2, sync role changed from offline to master
08/17 22:33:40.556138 00027705 QRY vgId:2, set querymgmt reopen
08/17 22:33:40.567657 00027707 WAL vgId:15, file:/data/taosdb/datas/vnode/vnode15/wal/wal1, will be restored
08/17 22:33:40.567747 00027707 WAL vgId:15, file:/data/taosdb/datas/vnode/vnode15/wal/wal1, restore success, wver:0
08/17 22:33:40.567797 00027707 WAL vgId:15, wal:0x7f7410039100 file:/data/taosdb/datas/vnode/vnode15/wal/wal1, it is removed
08/17 22:33:40.568088 00027707 VND vgId:15, sync role changed from offline to unsynced
08/17 22:33:40.568107 00027707 QRY vgId:15, set querymgmt reopen
08/17 22:33:40.570273 00027703 WAL vgId:13, file:/data/taosdb/datas/vnode/vnode13/wal/wal1, will be restored
08/17 22:33:40.570357 00027703 WAL vgId:13, file:/data/taosdb/datas/vnode/vnode13/wal/wal1, restore success, wver:0
08/17 22:33:40.570437 00027703 WAL vgId:13, wal:0x7f74240b9b00 file:/data/taosdb/datas/vnode/vnode13/wal/wal1, it is removed
08/17 22:33:40.570817 00027703 VND vgId:13, sync role changed from offline to unsynced
08/17 22:33:40.570851 00027703 QRY vgId:13, set querymgmt reopen
08/17 22:33:40.571286 00027702 WAL vgId:11, file:/data/taosdb/datas/vnode/vnode11/wal/wal1, will be restored
08/17 22:33:40.571337 00027702 WAL vgId:11, file:/data/taosdb/datas/vnode/vnode11/wal/wal1, restore success, wver:0
08/17 22:33:40.571453 00027702 WAL vgId:11, wal:0x7f742c0b9490 file:/data/taosdb/datas/vnode/vnode11/wal/wal1, it is removed
08/17 22:33:40.571777 00027702 VND vgId:11, sync role changed from offline to unsynced
08/17 22:33:40.571796 00027702 QRY vgId:11, set querymgmt reopen
08/17 22:33:40.571861 00027702 VND vgId:8, load vnode cfg successfully, replcia:3
08/17 22:33:40.571890 00027702 VND vgId:8, dnode:1, bhiot.taos1:6040
08/17 22:33:40.571898 00027702 VND vgId:8, dnode:4, bhiot.taos3:6040
08/17 22:33:40.571905 00027702 VND vgId:8, dnode:2, bhiot.taos2:6040
08/17 22:33:40.571923 00027702 VND vgId:8, read /data/taosdb/datas/vnode/vnode8/version.json successfully, fver:5043927
08/17 22:33:40.574876 00027709 WAL vgId:9, file:/data/taosdb/datas/vnode/vnode9/wal/wal1, will be restored
08/17 22:33:40.574969 00027709 WAL vgId:9, file:/data/taosdb/datas/vnode/vnode9/wal/wal1, restore success, wver:0
08/17 22:33:40.575085 00027709 WAL vgId:9, wal:0x7f74040c0d40 file:/data/taosdb/datas/vnode/vnode9/wal/wal1, it is removed
08/17 22:33:40.575097 00027711 WAL vgId:10, file:/data/taosdb/datas/vnode/vnode10/wal/wal1, will be restored
08/17 22:33:40.575177 00027711 WAL vgId:10, file:/data/taosdb/datas/vnode/vnode10/wal/wal1, restore success, wver:0
08/17 22:33:40.575256 00027711 WAL vgId:10, wal:0x7f74080c1230 file:/data/taosdb/datas/vnode/vnode10/wal/wal1, it is removed
08/17 22:33:40.575492 00027709 VND vgId:9, sync role changed from offline to unsynced
08/17 22:33:40.575533 00027709 QRY vgId:9, set querymgmt reopen
08/17 22:33:40.575619 00027711 VND vgId:10, sync role changed from offline to unsynced
08/17 22:33:40.575647 00027711 QRY vgId:10, set querymgmt reopen
08/17 22:33:40.580078 00027702 WAL vgId:8, file:/data/taosdb/datas/vnode/vnode8/wal/wal1, will be restored
08/17 22:33:40.580122 00027702 WAL vgId:8, file:/data/taosdb/datas/vnode/vnode8/wal/wal1, restore success, wver:0
08/17 22:33:40.580167 00027702 WAL vgId:8, wal:0x7f742c1a9a40 file:/data/taosdb/datas/vnode/vnode8/wal/wal1, it is removed
08/17 22:33:40.580425 00027702 VND vgId:8, sync role changed from offline to unsynced
08/17 22:33:40.580442 00027702 QRY vgId:8, set querymgmt reopen
08/17 22:33:40.614066 00027737 VND vgId:9, sync role changed from unsynced to slave
08/17 22:33:40.682307 00027737 VND vgId:8, sync role changed from unsynced to slave
08/17 22:33:40.716115 00027737 VND vgId:15, sync role changed from unsynced to slave
08/17 22:33:40.771009 00027737 VND vgId:11, sync role changed from unsynced to slave
08/17 22:33:40.807723 00027737 VND vgId:13, sync role changed from unsynced to slave
taosd: /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbFS.c:754: tsdbLoadMetaCache: Assertion `rInfo.offset > 0 && rInfo.size > 0' failed.
08/17 22:33:41.268105 00027706 DND shut down signal is 6
08/17 22:33:41.268176 00027706 DND sender PID:27684 cmdline:./taosd
Aborted (core dumped)

**Comment by yu285** [comment]
3.0早期版本的bug 都已经全部修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。
