### ISSUE TITLE
Currently 3.0 version lags behind 2.0 version in performance

### ISSUE THREAD

**Issue by z1017371914** [taosdata/TDengine#16199]
1.同样的环境下执行taosdemo 可以观察到每秒插入的数据量不一样。
2. select count(*) 时间太久。
3. 
![image](https://user-images.githubusercontent.com/10084923/185269465-d52d4dc5-0bd8-48c7-8cd4-2913e5256465.png)
4. 插入最新的数据也太久。

**Comment by z1017371914** [comment]
![image](https://user-images.githubusercontent.com/10084923/185271114-7b7c524c-29dc-4b49-a9a4-cd555f84ff57.png)
插入性能之前也就几百毫秒，现在都是秒级别了，是我配置的不对吗？

**Comment by yu285** [comment]
3.0早期版本的问题 都已经全部优化修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。
