### ISSUE TITLE
TDengine has  plugin for nginx?

### ISSUE THREAD

**Issue by zs-soft** [taosdata/TDengine#162]

**Comment by plum-lihui** [comment]
What plugins are needed？ TDengine can support restful interfaces。

**Comment by zs-soft** [comment]
The restful interfaces  could  support subscrib interfaces?

**Comment by zs-soft** [comment]
> What plugins are needed？ TDengine can support restful interfaces。

The restful interfaces could support subscrib interfaces?

**Comment by plum-lihui** [comment]
The resuful interfaces don't provide subscriptions yet.  What kind of subscription do you need? 
Please describe the specific subscription requirements, let's consider it.
Thanks！

**Comment by zs-soft** [comment]
> The resuful interfaces don't provide subscriptions yet. What kind of subscription do you need?
> Please describe the specific subscription requirements, let's consider it.
> Thanks！

En, like redis,kafka or zeromq for openresty(ngx-lua)

**Comment by guanshengliang** [comment]
sorry, we have no plans to support subscriptions on the rest interface for the time being
