### ISSUE TITLE
Shut down signal is 6

### ISSUE THREAD

**Issue by Lao-Zhong** [taosdata/TDengine#16202]
版本: v2.6.0.12
taos服务启动就显示shut down，而导致服务无法正常运行

root@bhiot3:/data/files# systemctl start taosd
root@bhiot3:/data/files# systemctl status taosd
● taosd.service - TDengine server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2022-08-18 11:51:57 CST; 2s ago
  Process: 18188 ExecStartPre=/usr/local/taos/bin/startPre.sh (code=exited, status=0/SUCCESS)
 Main PID: 18202 (taosd)
    Tasks: 43 (limit: 9830)
   CGroup: /system.slice/taosd.service
           └─18202 /usr/bin/taosd

Aug 18 11:51:57 bhiot3 systemd[1]: Starting TDengine server service...
Aug 18 11:51:57 bhiot3 systemd[1]: Started TDengine server service.
Aug 18 11:51:57 bhiot3 TDengine:[18202]: Starting TDengine service...
Aug 18 11:51:58 bhiot3 TDengine:[18202]: Shut down signal is 6
Aug 18 11:51:58 bhiot3 TDengine:[18202]: Shutting down TDengine service...

root@bhiot3:/data/files# systemctl status taosd
● taosd.service - TDengine server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Thu 2022-08-18 11:52:15 CST; 1min 10s ago
  Process: 18456 ExecStart=/usr/bin/taosd (code=killed, signal=ABRT)
  Process: 18443 ExecStartPre=/usr/local/taos/bin/startPre.sh (code=exited, status=0/SUCCESS)
 Main PID: 18456 (code=killed, signal=ABRT)

Aug 18 11:52:15 bhiot3 systemd[1]: taosd.service: Failed with result 'signal'.
Aug 18 11:52:15 bhiot3 systemd[1]: taosd.service: Service hold-off time over, scheduling restart.
Aug 18 11:52:15 bhiot3 systemd[1]: taosd.service: Scheduled restart job, restart counter is at 3.
Aug 18 11:52:15 bhiot3 systemd[1]: Stopped TDengine server service.
Aug 18 11:52:15 bhiot3 systemd[1]: taosd.service: Start request repeated too quickly.
Aug 18 11:52:15 bhiot3 systemd[1]: taosd.service: Failed with result 'signal'.
Aug 18 11:52:15 bhiot3 systemd[1]: Failed to start TDengine server service.

root@bhiot3:/data/files# taosd
08/18 11:50:29.651634 00016932 DND start to initialize TDengine
08/18 11:50:29.651761 00016932 DND step:dnode-tfile is initialized
08/18 11:50:29.651790 00016932 DND step:dnode-rpc is initialized
08/18 11:50:29.651806 00016932 UTL localEp is: bhiot.taos2:6030
08/18 11:50:29.652211 00016932 UTL timezone is set to Asia/Shanghai by config file
08/18 11:50:29.652245 00016932 UTL timezone format changed to (CST, +0800)
08/18 11:50:29.652253 00016932 UTL    check global cfg completed
08/18 11:50:29.652259 00016932 UTL ==================================
08/18 11:50:29.652276 00016932 UTL    taos config & system info:
08/18 11:50:29.652289 00016932 UTL ==================================
08/18 11:50:29.652297 00016932 UTL  firstEp:                bhiot.taos1:6030 
08/18 11:50:29.652308 00016932 UTL  secondEp:               bhiot.taos2:6030 
08/18 11:50:29.652318 00016932 UTL  fqdn:                   bhiot.taos2 
08/18 11:50:29.652334 00016932 UTL  serverPort:             6030 
08/18 11:50:29.652344 00016932 UTL  configDir:              /etc/taos 
08/18 11:50:29.652354 00016932 UTL  logDir:                 /data/taosdb/log 
08/18 11:50:29.652364 00016932 UTL  scriptDir:              /etc/taos 
08/18 11:50:29.652375 00016932 UTL  arbitrator:             bhiot.taos1:6042 
08/18 11:50:29.652385 00016932 UTL  numOfThreadsPerCore:    1.000000 
08/18 11:50:29.652397 00016932 UTL  numOfCommitThreads:     4 
08/18 11:50:29.652408 00016932 UTL  ratioOfQueryCores:      1.000000 
08/18 11:50:29.652418 00016932 UTL  maxNumOfDistinctRes:    10000000 
08/18 11:50:29.652429 00016932 UTL  numOfMnodes:            1 
08/18 11:50:29.652448 00016932 UTL  vnodeBak:               1 
08/18 11:50:29.652462 00016932 UTL  telemetryReporting:     1 
08/18 11:50:29.652473 00016932 UTL  dnodeNopLoop:           0 
08/18 11:50:29.652483 00016932 UTL  tcpConnTimeout:         1000(ms)
08/18 11:50:29.652493 00016932 UTL  syncCheckInterval:      1500(ms)
08/18 11:50:29.652510 00016932 UTL  balance:                1 
08/18 11:50:29.652520 00016932 UTL  balanceInterval:        300 
08/18 11:50:29.652530 00016932 UTL  offlineInterval:        3 
08/18 11:50:29.652541 00016932 UTL  keepTimeOffset:         0 
08/18 11:50:29.652562 00016932 UTL  role:                   0 
08/18 11:50:29.652572 00016932 UTL  maxTmrCtrl:             512 
08/18 11:50:29.652582 00016932 UTL  monitorInterval:        30(s)
08/18 11:50:29.652592 00016932 UTL  monitorReplica:         1 
08/18 11:50:29.652602 00016932 UTL  offlineThreshold:       864000(s)
08/18 11:50:29.652612 00016932 UTL  rpcTimer:               300(ms)
08/18 11:50:29.652622 00016932 UTL  rpcMaxTime:             600(s)
08/18 11:50:29.652631 00016932 UTL  rpcForceTcp:            0 
08/18 11:50:29.652641 00016932 UTL  statusInterval:         1(s)
08/18 11:50:29.652651 00016932 UTL  shellActivityTimer:     3(s)
08/18 11:50:29.652661 00016932 UTL  minSlidingTime:         10(ms)
08/18 11:50:29.652670 00016932 UTL  minIntervalTime:        1(ms)
08/18 11:50:29.652680 00016932 UTL  maxStreamCompDelay:     20000(ms)
08/18 11:50:29.652690 00016932 UTL  maxFirstStreamCompDelay:10000(ms)
08/18 11:50:29.652700 00016932 UTL  retryStreamCompDelay:   1800000(ms)
08/18 11:50:29.652710 00016932 UTL  streamCompDelayRatio:   0.100000 
08/18 11:50:29.652721 00016932 UTL  maxVgroupsPerDb:        0 
08/18 11:50:29.652731 00016932 UTL  maxTablesPerVnode:      1000000 
08/18 11:50:29.652740 00016932 UTL  minTablesPerVnode:      1000 
08/18 11:50:29.652750 00016932 UTL  tableIncStepPerVnode:   1000 
08/18 11:50:29.652760 00016932 UTL  cache:                  16(Mb)
08/18 11:50:29.652770 00016932 UTL  blocks:                 6 
08/18 11:50:29.652780 00016932 UTL  days:                   10 
08/18 11:50:29.652790 00016932 UTL  keep:                   3650 
08/18 11:50:29.652800 00016932 UTL  minRows:                100 
08/18 11:50:29.652810 00016932 UTL  maxRows:                4096 
08/18 11:50:29.652819 00016932 UTL  precision:              0 
08/18 11:50:29.652829 00016932 UTL  comp:                   2 
08/18 11:50:29.652839 00016932 UTL  walLevel:               2 
08/18 11:50:29.652853 00016932 UTL  fsync:                  3000 
08/18 11:50:29.652863 00016932 UTL  replica:                1 
08/18 11:50:29.652873 00016932 UTL  partitions:             4 
08/18 11:50:29.652882 00016932 UTL  quorum:                 1 
08/18 11:50:29.652892 00016932 UTL  update:                 0 
08/18 11:50:29.652902 00016932 UTL  cachelast:              0 
08/18 11:50:29.652912 00016932 UTL  compressMsgSize:        524288 
08/18 11:50:29.652922 00016932 UTL  compressColData:        -1 
08/18 11:50:29.652931 00016932 UTL  maxSQLLength:           1048576(byte)
08/18 11:50:29.652941 00016932 UTL  maxWildCardsLength:     100(byte)
08/18 11:50:29.652951 00016932 UTL  maxRegexStringLen:      128(byte)
08/18 11:50:29.652961 00016932 UTL  maxNumOfOrderedRes:     1000000 
08/18 11:50:29.652971 00016932 UTL  queryBufferSize:        -1(byte)
08/18 11:50:29.652981 00016932 UTL  retrieveBlockingModel:  0 
08/18 11:50:29.652991 00016932 UTL  keepColumnName:         0 
08/18 11:50:29.653000 00016932 UTL  timezone:               (CST, +0800) 
08/18 11:50:29.653010 00016932 UTL  locale:                 en_US.UTF-8 
08/18 11:50:29.653020 00016932 UTL  charset:                UTF-8 
08/18 11:50:29.653030 00016932 UTL  maxShellConns:          5000 
08/18 11:50:29.653039 00016932 UTL  maxConnections:         5000 
08/18 11:50:29.653049 00016932 UTL  minimalLogDirGB:        1.000000(GB)
08/18 11:50:29.653059 00016932 UTL  minimalTmpDirGB:        1.000000(GB)
08/18 11:50:29.653069 00016932 UTL  minimalDataDirGB:       2.000000(GB)
08/18 11:50:29.653079 00016932 UTL  mnodeEqualVnodeNum:     4 
08/18 11:50:29.653089 00016932 UTL  flowctrl:               1 
08/18 11:50:29.653099 00016932 UTL  slaveQuery:             1 
08/18 11:50:29.653109 00016932 UTL  adjustMaster:           1 
08/18 11:50:29.653119 00016932 UTL  http:                   1 
08/18 11:50:29.653128 00016932 UTL  monitor:                1 
08/18 11:50:29.653138 00016932 UTL  stream:                 1 
08/18 11:50:29.653148 00016932 UTL  topicBinaryLen:         16000 
08/18 11:50:29.653157 00016932 UTL  httpEnableRecordSql:    0 
08/18 11:50:29.653167 00016932 UTL  telegrafUseFieldNum:    0 
08/18 11:50:29.653182 00016932 UTL  httpMaxThreads:         2000 
08/18 11:50:29.653192 00016932 UTL  restfulRowLimit:        10240 
08/18 11:50:29.653202 00016932 UTL  httpDbNameMandatory:    0 
08/18 11:50:29.653212 00016932 UTL  httpKeepAlive:          30000 
08/18 11:50:29.653222 00016932 UTL  numOfLogLines:          10000000 
08/18 11:50:29.653232 00016932 UTL  logKeepDays:            0 
08/18 11:50:29.653241 00016932 UTL  asyncLog:               1 
08/18 11:50:29.653251 00016932 UTL  debugFlag:              0 
08/18 11:50:29.653261 00016932 UTL  mDebugFlag:             131 
08/18 11:50:29.653271 00016932 UTL  dDebugFlag:             135 
08/18 11:50:29.653281 00016932 UTL  sDebugFlag:             135 
08/18 11:50:29.653290 00016932 UTL  wDebugFlag:             135 
08/18 11:50:29.653300 00016932 UTL  sdbDebugFlag:           131 
08/18 11:50:29.653310 00016932 UTL  rpcDebugFlag:           131 
08/18 11:50:29.653320 00016932 UTL  tmrDebugFlag:           131 
08/18 11:50:29.653330 00016932 UTL  cDebugFlag:             131 
08/18 11:50:29.653339 00016932 UTL  jniDebugFlag:           131 
08/18 11:50:29.653349 00016932 UTL  odbcDebugFlag:          131 
08/18 11:50:29.653359 00016932 UTL  uDebugFlag:             131 
08/18 11:50:29.653368 00016932 UTL  httpDebugFlag:          131 
08/18 11:50:29.653378 00016932 UTL  monDebugFlag:           131 
08/18 11:50:29.653388 00016932 UTL  qDebugFlag:             131 
08/18 11:50:29.653398 00016932 UTL  vDebugFlag:             135 
08/18 11:50:29.653407 00016932 UTL  tsdbDebugFlag:          143 
08/18 11:50:29.653417 00016932 UTL  cqDebugFlag:            131 
08/18 11:50:29.653427 00016932 UTL  enableRecordSql:        0 
08/18 11:50:29.653442 00016932 UTL  enableCoreFile:         0 
08/18 11:50:29.653453 00016932 UTL  gitinfo:                79d52152dec05291cc1a5e8bb00c077b71cad6b4 
08/18 11:50:29.653463 00016932 UTL  gitinfoOfInternal:      NULL 
08/18 11:50:29.653476 00016932 UTL  buildinfo:              Built at 2022-08-06 00:07 
08/18 11:50:29.653486 00016932 UTL  version:                2.6.0.12 
08/18 11:50:29.653496 00016932 UTL  maxBinaryDisplayWidth:  30 
08/18 11:50:29.653506 00016932 UTL  tempDir:                /tmp/ 
08/18 11:50:29.653516 00016932 UTL  tsdbMetaCompactRatio:   0 
08/18 11:50:29.653526 00016932 UTL  deadLockKillQuery:      1 
08/18 11:50:29.653536 00016932 UTL  clientMerge:            0 
08/18 11:50:29.653546 00016932 UTL  defaultJSONStrType:     nchar 
08/18 11:50:29.653555 00016932 UTL  smlChildTableName:       
08/18 11:50:29.653565 00016932 UTL  smlTagNullName:         _tag_null 
08/18 11:50:29.653575 00016932 UTL  walFlushSize:           1024(Mb)
08/18 11:50:29.653589 00016932 UTL  shortcutFlag:           0 
08/18 11:50:29.653599 00016932 UTL  probeSeconds:           300 
08/18 11:50:29.653609 00016932 UTL  probeKillSeconds:       600 
08/18 11:50:29.653619 00016932 UTL  probeInterval:          40 
08/18 11:50:29.653628 00016932 UTL  lossyColumns:            
08/18 11:50:29.653638 00016932 UTL  fPrecision:             0.000000 
08/18 11:50:29.653649 00016932 UTL  dPrecision:             0.000000 
08/18 11:50:29.653660 00016932 UTL  maxRange:               500 
08/18 11:50:29.653669 00016932 UTL  range:                  100 
08/18 11:50:29.653680 00016932 UTL  os pageSize:            4096(KB)
08/18 11:50:29.653690 00016932 UTL  os openMax:             63868
08/18 11:50:29.653700 00016932 UTL  os streamMax:           16
08/18 11:50:29.653709 00016932 UTL  os numOfCores:          8
08/18 11:50:29.653719 00016932 UTL  os totalMemory:         16027(MB)
08/18 11:50:29.653730 00016932 UTL  os sysname:             Linux
08/18 11:50:29.653740 00016932 UTL  os nodename:            bhiot3
08/18 11:50:29.653750 00016932 UTL  os release:             4.15.0-191-generic
08/18 11:50:29.653759 00016932 UTL  os version:             #202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022
08/18 11:50:29.653769 00016932 UTL  os machine:             x86_64
08/18 11:50:29.653779 00016932 UTL  dataDir: /data/taosdb/datas
08/18 11:50:29.653789 00016932 UTL ==================================
08/18 11:50:29.653817 00016932 DND step:dnode-globalcfg is initialized
08/18 11:50:29.653870 00016932 TFS disk /data/taosdb/datas is mounted to tier level 0 id 0
08/18 11:50:29.653965 00016932 UTL ==================================
08/18 11:50:29.653983 00016932 UTL  os totalDisk:           491.957153(GB)
08/18 11:50:29.653996 00016932 UTL  os usedDisk:            62.536278(GB)
08/18 11:50:29.654006 00016932 UTL  os availDisk:           404.405273(GB)
08/18 11:50:29.654018 00016932 UTL ==================================
08/18 11:50:29.654027 00016932 DND dnode storage is initialized at /data/taosdb/datas/dnode
08/18 11:50:29.654037 00016932 DND step:dnode-storage is initialized
08/18 11:50:29.654085 00016932 DND read file /data/taosdb/datas/dnode/dnodeCfg.json successed
08/18 11:50:29.654103 00016932 DND dnodeId is set to 2, clusterId is set to 415943a7-a326-4c39-aec4-a8c239ce1b85
08/18 11:50:29.655222 00016932 DND successed to write /data/taosdb/datas/dnode/dnodeCfg.json
08/18 11:50:29.655254 00016932 DND dnode cfg is initialized
08/18 11:50:29.655266 00016932 DND step:dnode-cfg is initialized
08/18 11:50:29.655340 00016932 DND read file /data/taosdb/datas/dnode/dnodeEps.json successed
08/18 11:50:29.655383 00016932 DND dnode eps is initialized
08/18 11:50:29.655398 00016932 DND step:dnode-eps is initialized
08/18 11:50:29.655450 00016932 DND read file /data/taosdb/datas/dnode/mnodeEpSet.json successed
08/18 11:50:29.655463 00016932 DND print minfos, mnodeNum:3 inUse:0
08/18 11:50:29.655473 00016932 DND mnode index:1, bhiot.taos1:6030
08/18 11:50:29.655483 00016932 DND mnode index:2, bhiot.taos2:6030
08/18 11:50:29.655492 00016932 DND mnode index:4, bhiot.taos3:6030
08/18 11:50:29.655508 00016932 DND print minfos, mnodeNum:3 inUse:0
08/18 11:50:29.655518 00016932 DND mnode index:1, bhiot.taos1:6030
08/18 11:50:29.655528 00016932 DND mnode index:2, bhiot.taos2:6030
08/18 11:50:29.655537 00016932 DND mnode index:4, bhiot.taos3:6030
08/18 11:50:29.655547 00016932 DND dnode minfos is initialized
08/18 11:50:29.655571 00016932 DND step:dnode-minfos is initialized
08/18 11:50:29.655642 00016932 WAL wal module is initialized, rsetId:3
08/18 11:50:29.655659 00016932 DND step:dnode-wal is initialized
08/18 11:50:29.655792 00016932 DND step:dnode-sync is initialized
08/18 11:50:29.655838 00016932 DND dnode check is initialized
08/18 11:50:29.655858 00016932 DND step:dnode-check is initialized
08/18 11:50:29.655871 00016932 UTL worker:vquery is initialized, min:8 max:8
08/18 11:50:29.655887 00016932 UTL worker:vfetch is initialized, min:4 max:4
08/18 11:50:29.655897 00016932 DND step:dnode-vread is initialized
08/18 11:50:29.655907 00016932 DND dnode vwrite is initialized, max worker 8
08/18 11:50:29.655917 00016932 DND step:dnode-vwrite is initialized
08/18 11:50:29.655993 00016932 DND step:vnode-backup is initialized
08/18 11:50:29.656051 00016932 DND step:vnode-worker is initialized
08/18 11:50:29.656065 00016932 DND step:vnode-write is initialized
08/18 11:50:29.656080 00016932 DND step:vnode-read is initialized
08/18 11:50:29.656092 00016932 DND step:vnode-hash is initialized
08/18 11:50:29.656237 00016932 DND step:tsdb-queue is initialized
08/18 11:50:29.656252 00016932 UTL worker:vmgmt is initialized, min:1 max:1
08/18 11:50:29.656295 00016932 DND dnode vmgmt is initialized
08/18 11:50:29.656307 00016932 DND step:dnode-vmgmt is initialized
08/18 11:50:29.656326 00016932 DND step:dnode-mread is initialized
08/18 11:50:29.656340 00016932 DND step:dnode-mwrite is initialized
08/18 11:50:29.656353 00016932 DND step:dnode-mpeer is initialized
08/18 11:50:29.661046 00016932 DND dnode inter-dnodes rpc client is initialized
08/18 11:50:29.661077 00016932 DND step:dnode-client is initialized
08/18 11:50:29.661880 00016932 DND dnode inter-dnodes RPC server is initialized
08/18 11:50:29.661902 00016932 DND step:dnode-server is initialized
08/18 11:50:29.661968 00016932 DND start 8 threads to open 9 vnodes
08/18 11:50:29.662380 00016951 VND vgId:13, load vnode cfg successfully, replcia:3
08/18 11:50:29.662456 00016951 VND vgId:13, dnode:4, bhiot.taos3:6040
08/18 11:50:29.662474 00016950 VND vgId:11, load vnode cfg successfully, replcia:3
08/18 11:50:29.662483 00016951 VND vgId:13, dnode:2, bhiot.taos2:6040
08/18 11:50:29.662486 00016953 VND vgId:2, load vnode cfg successfully, replcia:1
08/18 11:50:29.662532 00016950 VND vgId:11, dnode:2, bhiot.taos2:6040
08/18 11:50:29.662543 00016951 VND vgId:13, dnode:1, bhiot.taos1:6040
08/18 11:50:29.662733 00016954 VND vgId:4, load vnode cfg successfully, replcia:1
08/18 11:50:29.662769 00016951 VND vgId:13, read /data/taosdb/datas/vnode/vnode13/version.json successfully, fver:2259246
08/18 11:50:29.662755 00016955 VND vgId:15, load vnode cfg successfully, replcia:3
08/18 11:50:29.662610 00016953 VND vgId:2, dnode:2, bhiot.taos2:6040
08/18 11:50:29.662793 00016954 VND vgId:4, dnode:2, bhiot.taos2:6040
08/18 11:50:29.662801 00016957 VND vgId:10, load vnode cfg successfully, replcia:3
08/18 11:50:29.662803 00016955 VND vgId:15, dnode:2, bhiot.taos2:6040
08/18 11:50:29.662828 00016957 VND vgId:10, dnode:4, bhiot.taos3:6040
08/18 11:50:29.662830 00016955 VND vgId:15, dnode:1, bhiot.taos1:6040
08/18 11:50:29.662840 00016953 VND vgId:2, read /data/taosdb/datas/vnode/vnode2/version.json successfully, fver:6069521
08/18 11:50:29.662845 00016955 VND vgId:15, dnode:4, bhiot.taos3:6040
08/18 11:50:29.662843 00016954 VND vgId:4, read /data/taosdb/datas/vnode/vnode4/version.json successfully, fver:33839271
08/18 11:50:29.662847 00016957 VND vgId:10, dnode:2, bhiot.taos2:6040
08/18 11:50:29.662881 00016955 VND vgId:15, read /data/taosdb/datas/vnode/vnode15/version.json successfully, fver:25767
08/18 11:50:29.662882 00016957 VND vgId:10, dnode:1, bhiot.taos1:6040
08/18 11:50:29.662913 00016957 VND vgId:10, read /data/taosdb/datas/vnode/vnode10/version.json successfully, fver:3760308
08/18 11:50:29.662697 00016950 VND vgId:11, dnode:4, bhiot.taos3:6040
08/18 11:50:29.662942 00016956 VND vgId:9, load vnode cfg successfully, replcia:3
08/18 11:50:29.662978 00016950 VND vgId:11, dnode:1, bhiot.taos1:6040
08/18 11:50:29.662993 00016956 VND vgId:9, dnode:1, bhiot.taos1:6040
08/18 11:50:29.663010 00016956 VND vgId:9, dnode:4, bhiot.taos3:6040
08/18 11:50:29.663018 00016950 VND vgId:11, read /data/taosdb/datas/vnode/vnode11/version.json successfully, fver:4381113
08/18 11:50:29.663023 00016956 VND vgId:9, dnode:2, bhiot.taos2:6040
08/18 11:50:29.663056 00016952 VND vgId:16, load vnode cfg successfully, replcia:1
08/18 11:50:29.663117 00016952 VND vgId:16, dnode:2, bhiot.taos2:6040
08/18 11:50:29.663132 00016956 VND vgId:9, read /data/taosdb/datas/vnode/vnode9/version.json successfully, fver:4666860
08/18 11:50:29.663190 00016952 VND vgId:16, read /data/taosdb/datas/vnode/vnode16/version.json successfully, fver:4870817
08/18 11:50:29.665392 00016953 WAL vgId:2, file:/data/taosdb/datas/vnode/vnode2/wal/wal1, will be restored
08/18 11:50:29.665560 00016953 WAL vgId:2, file:/data/taosdb/datas/vnode/vnode2/wal/wal1, restore success, wver:0
08/18 11:50:29.665641 00016953 WAL vgId:2, wal:0x7fe3f0030d10 file:/data/taosdb/datas/vnode/vnode2/wal/wal1, it is removed
08/18 11:50:29.665936 00016953 VND vgId:2, sync role changed from offline to leader
08/18 11:50:29.677750 00016957 WAL vgId:10, file:/data/taosdb/datas/vnode/vnode10/wal/wal1, will be restored
08/18 11:50:29.677819 00016957 WAL vgId:10, file:/data/taosdb/datas/vnode/vnode10/wal/wal1, restore success, wver:0
08/18 11:50:29.677875 00016957 WAL vgId:10, wal:0x7fe3d80b4c40 file:/data/taosdb/datas/vnode/vnode10/wal/wal1, it is removed
08/18 11:50:29.678137 00016957 VND vgId:10, sync role changed from offline to unsynced
08/18 11:50:29.678558 00016956 WAL vgId:9, file:/data/taosdb/datas/vnode/vnode9/wal/wal1, will be restored
08/18 11:50:29.678624 00016956 WAL vgId:9, file:/data/taosdb/datas/vnode/vnode9/wal/wal1, restore success, wver:0
08/18 11:50:29.678668 00016956 WAL vgId:9, wal:0x7fe3e00b4930 file:/data/taosdb/datas/vnode/vnode9/wal/wal1, it is removed
08/18 11:50:29.678907 00016956 VND vgId:9, sync role changed from offline to unsynced
08/18 11:50:29.679104 00016951 WAL vgId:13, file:/data/taosdb/datas/vnode/vnode13/wal/wal1, will be restored
08/18 11:50:29.679172 00016951 WAL vgId:13, file:/data/taosdb/datas/vnode/vnode13/wal/wal1, restore success, wver:0
08/18 11:50:29.679219 00016951 WAL vgId:13, wal:0x7fe3f80bd710 file:/data/taosdb/datas/vnode/vnode13/wal/wal1, it is removed
08/18 11:50:29.679504 00016951 VND vgId:13, sync role changed from offline to unsynced
08/18 11:50:29.685099 00016950 WAL vgId:11, file:/data/taosdb/datas/vnode/vnode11/wal/wal1, will be restored
08/18 11:50:29.685181 00016950 WAL vgId:11, file:/data/taosdb/datas/vnode/vnode11/wal/wal1, restore success, wver:0
08/18 11:50:29.685257 00016950 WAL vgId:11, wal:0x7fe4000acec0 file:/data/taosdb/datas/vnode/vnode11/wal/wal1, it is removed
08/18 11:50:29.685688 00016950 VND vgId:11, sync role changed from offline to unsynced
08/18 11:50:29.685809 00016950 VND vgId:8, load vnode cfg successfully, replcia:3
08/18 11:50:29.685829 00016950 VND vgId:8, dnode:1, bhiot.taos1:6040
08/18 11:50:29.685843 00016950 VND vgId:8, dnode:4, bhiot.taos3:6040
08/18 11:50:29.685855 00016950 VND vgId:8, dnode:2, bhiot.taos2:6040
08/18 11:50:29.685886 00016950 VND vgId:8, read /data/taosdb/datas/vnode/vnode8/version.json successfully, fver:5043927
08/18 11:50:29.697879 00016955 WAL vgId:15, file:/data/taosdb/datas/vnode/vnode15/wal/wal1, will be restored
08/18 11:50:29.697978 00016955 WAL vgId:15, file:/data/taosdb/datas/vnode/vnode15/wal/wal1, restore success, wver:0
08/18 11:50:29.698067 00016955 WAL vgId:15, wal:0x7fe3e403f310 file:/data/taosdb/datas/vnode/vnode15/wal/wal1, it is removed
08/18 11:50:29.698388 00016955 VND vgId:15, sync role changed from offline to unsynced
08/18 11:50:29.698842 00016950 WAL vgId:8, file:/data/taosdb/datas/vnode/vnode8/wal/wal1, will be restored
08/18 11:50:29.698907 00016950 WAL vgId:8, file:/data/taosdb/datas/vnode/vnode8/wal/wal1, restore success, wver:0
08/18 11:50:29.698990 00016950 WAL vgId:8, wal:0x7fe400191200 file:/data/taosdb/datas/vnode/vnode8/wal/wal1, it is removed
08/18 11:50:29.699286 00016950 VND vgId:8, sync role changed from offline to unsynced
08/18 11:50:29.889013 00016985 VND vgId:10, sync role changed from unsynced to follower
08/18 11:50:29.987152 00016985 VND vgId:11, sync role changed from unsynced to follower
taosd: /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbFS.c:836: tsdbLoadMetaCache: Assertion `rInfo.offset > 0 && rInfo.size > 0' failed.
08/18 11:50:30.681348 00016954 DND shut down signal is 6
08/18 11:50:30.681419 00016954 DND sender PID:16932 cmdline:taosd
Aborted (core dumped)

**Comment by JunTech** [comment]
me too

**Comment by JunTech** [comment]
系统: ubuntu
安装包:2.1.0.0 deb包
安装之后 edit 配置文件 并 systemctl start taosd,然后服务启动不起来，就算启动起来了，使用taos连接就会直接关闭掉，用status 命令查看状态，发现显示 signal is 6

**Comment by JunTech** [comment]
系统: ubuntu
安装包:2.1.0.0 deb包
安装之后 edit 配置文件 并 systemctl start taosd,然后服务启动不起来，就算启动起来了，使用taos连接就会直接关闭掉，用status 命令查看状态，发现显示 signal is 6，
2.6没有这个问题，可以正常启动

**Comment by Lao-Zhong** [comment]
> 系统: ubuntu 安装包:2.1.0.0 deb包 安装之后 edit 配置文件 并 systemctl start taosd,然后服务启动不起来，就算启动起来了，使用taos连接就会直接关闭掉，用status 命令查看状态，发现显示 signal is 6， 2.6没有这个问题，可以正常启动

当前系统: Ubuntu
当前版本: 2.6.0.12
集群中另两个节点可正常运行，但执行taos时显示操作【 taos connect failed, reason: Unable to establish connection. 】
当前节点执行 systemctl start taosd 运行不起来，报错误【 taosd.service: Failed with result 'signal'.】
执行taosd显示【sync role changed from offline to unsynced. DND shut down signal is 6】
不清楚signal 6是什么原因，是文件同步失败还是文件损坏了？

**Comment by 786442592** [comment]
老哥，有解决吗？

**Comment by sangshuduo** [comment]
> 老哥，有解决吗？

@786442592 这个 issue 时间已经很长了，很多信息不全。请重新提交一个 issue，包含版本和环境信息，如何复现问题，最好上传相应的 taosdlog 和 taoslog
