### ISSUE TITLE
3.0 docker performance issue compared with 2.0

### ISSUE THREAD

**Issue by AdonLuo** [taosdata/TDengine#16208]
# 环境：Centos7.9+docker 部署tdengine:3.0.0.0

1. 启动后出现一些错误提示，不知是否有影响？截图如下：
![image](https://user-images.githubusercontent.com/19642911/185337223-0c31cbc7-b811-4c13-bfe9-85cbd0b4cd56.png)
![image](https://user-images.githubusercontent.com/19642911/185337347-08a67dc8-b9ba-460c-bc35-062dd6713c94.png)

2. 创建数据库和创建表等方面耗时对比，3.0.0.0 在创建库表方面所体现的时间明细更久，大批量数据查询暂未验证
+ 3.0.0.0
```sql

taos> CREATE DATABASE IF NOT EXISTS db_iot REPLICA 1 COMP 2 PRECISION 'ns';
Query OK, 0 of 0 rows affected (1.075656s)

```
![image](https://user-images.githubusercontent.com/19642911/185338952-8f9ac3f8-3daa-4739-bcd8-3f64ca9331d7.png)

+2.4.0.30
```sql

taos> CREATE DATABASE IF NOT EXISTS db_iot REPLICA 1 QUORUM 1 DAYS 10 KEEP 3650 CACHE 16 BLOCKS 4 MINROWS 100 MAXROWS 4096 FSYNC 3000 CACHELAST 0 COMP 2 PRECISION 'ns' UPDATE 2;
Query OK, 0 of 0 row(s) in database (0.009056s)


```
![image](https://user-images.githubusercontent.com/19642911/185338446-a0eba895-7d13-4a88-aead-3bb0c36522a9.png)

**Comment by yu285** [comment]
报错无影响，3.0 正在持续优化中，潜力上限都远好于2.0 ， 烦请耐心

**Comment by yu285** [comment]
3.0早期版本问题都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。
