### ISSUE TITLE
3.0 windows connection issue

### ISSUE THREAD

**Issue by caiqiqqq** [taosdata/TDengine#16201]
![image](https://user-images.githubusercontent.com/102867723/185287184-43827466-9696-446b-87b4-e8362c112bcf.png)
![image](https://user-images.githubusercontent.com/102867723/185287205-02b00e60-98fc-4895-ac7f-e0a1a5e66030.png)
能够ping 通 服务器端

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

**Comment by yu285** [comment]
客户端服务端需要版本一致
