### ISSUE TITLE
After the Docker container modifies the port mapping, the client fails to connect

### ISSUE THREAD

**Issue by homeless2010** [taosdata/TDengine#16200]
3.0docker容器修改端口映射后客户端无法连接

以非6030-6049端口映射创建容器

![image](https://user-images.githubusercontent.com/26829140/185270346-d6192eb7-4ef8-440f-aa50-f235b6cd0a2e.png)
宿主机无法连接
![image](https://user-images.githubusercontent.com/26829140/185270391-3246f297-2634-4117-8c88-42318825a9c8.png)
远程windows客户端连接 查询报错
![image](https://user-images.githubusercontent.com/26829140/185272060-b9ed2934-4f21-4305-bc1e-2eba71ca1dfc.png)

**Comment by z1017371914** [comment]
你看看截图，建表语句，binary 你写成了 bnary

**Comment by yu285** [comment]
please use same port between docker image and host machine .
