### ISSUE TITLE
How do I change the REST port：6041

### ISSUE THREAD

**Issue by blackmaxer** [taosdata/TDengine#16212]
请问一下rest的端口去哪里配置，配置文件里面就只有tcp的6030,
rest的6041这个端口是固定偏移量产生的吗 

 serverPort            6030

这个arbitrator是配置rest？
arbitrator            arbitrator_hostname:6030

**Comment by fenghuazzm** [comment]
2.4 及之后的版本由 /etc/taos/taosadapter.toml 文件配置

**Comment by inprise1980** [comment]
@fenghuazzm 3.0的window版本，没有看到taosadapter.toml这个文件，默认是没安装taosAdapter吗

**Comment by sangshuduo** [comment]
@inprise1980 稍后发布
