### ISSUE TITLE
taos connect failed, reason: Unable to establish connection.

### ISSUE THREAD

**Issue by Lao-Zhong** [taosdata/TDengine#16211]
**Bug Description**
System: Ubuntu
Version: 2.6.0.12

集群中2个节点报错: taos connect failed, reason: Unable to establish connection.
1个节点服务运行不起来，如果是该节点的文件损坏，需要怎么操作才会使该节点恢复运行呢？有容错恢复机制么？急需协助
[taosd.log](https://github.com/taosdata/TDengine/files/9371869/taosd.log)

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
