### ISSUE TITLE
Regarding to TDengine CLI issue

### ISSUE THREAD

**Issue by yetao-study** [taosdata/TDengine#16220]
在Win10中下载[TDengine-client-3.0.0.0-Windows-x64.exe (5.5 M)](https://docs.taosdata.com/develop/connect/#!)
1、采用Edge浏览器下载，首先下载时，浏览器阻止了exe的下载，解除后下载成功
2、安装默认安装到C盘，创建桌面快捷方式打开，Win10提示病毒威胁，将taos.exe执行文件删除掉了
3、没了taos.exe文件不能使用了，只能卸载
建议：
1、别的数据库MySQL、InfluxDB等，服务端和客户端都可以绿色软件直接运行的，不知道TDengine为啥不提供
2、非要安装版也可以，但是程序打包的证书，不能在下载的时候浏览器就提示威胁，更不能在运行的时候直接被操作系统删除
3、作为开源软件，感觉很有必要提供绿色版的可执行程序

**Comment by yu285** [comment]
We are working on this, Thanks for your feedback

**Comment by H-TWINKLE** [comment]
同样，发现病毒

**Comment by sangshuduo** [comment]
> 同样，发现病毒

哪个版本？

**Comment by H-TWINKLE** [comment]
> > 同样，发现病毒
> 
> 哪个版本？

最新版本，病毒是  trojan.pe.ai

**Comment by yu285** [comment]
已经修复，建议使用最新版
