### ISSUE TITLE
when count=0 ,the result retrieve  is null 

### ISSUE THREAD

**Issue by zhuangQingGuang** [taosdata/TDengine#16230]
版本：2.6.0.8
连接方式：restful
疑问：如果count为0是否也应该返回0比较合理。
count为0的情况：
![count问题](https://user-images.githubusercontent.com/45782190/185524066-afd86ab7-0c9a-41c2-bb22-77e7e00f6385.png)

正常情况：
![count正常](https://user-images.githubusercontent.com/45782190/185524419-3312b9a3-9d92-4072-afc3-6c45c9da0d87.png)

**Comment by yu285** [comment]
我们参考了其它时序数据库做的设计，由于时序数据库有自己的逻辑，这个改动对于插值 （fill） 和 interval 插值有很大的影响。我们内部讨论过一次，决定暂时不修改。
在 3.x 或许可以提供一个新的结果返回模式，返回这个结果。

**Comment by zhuangQingGuang** [comment]
> 我们参考了其它时序数据库做的设计，由于时序数据库有自己的逻辑，这个改动对于插值 （fill） 和 interval 插值有很大的影响。我们内部讨论过一次，决定暂时不修改。 在 3.x 或许可以提供一个新的结果返回模式，返回这个结果。

收到 感谢回复
