### ISSUE TITLE
use taos dump 2.1.2 failed

### ISSUE THREAD

**Issue by wang233work** [taosdata/TDengine#16234]
![image](https://user-images.githubusercontent.com/57163477/185537204-fc9de20f-88f1-4682-b731-f9d1f5e745b7.png)
root@tsdb:~/dump# /root/taosTools-2.1.2/bin/taosdump -D data
/root/taosTools-2.1.2/bin/taosdump: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
![image](https://user-images.githubusercontent.com/57163477/185537245-725bd189-6922-4983-b88e-033359a8b4df.png)

**Comment by wang233work** [comment]
参考https://github.com/taosdata/TDengine/issues/3125#issue-680836338%EF%BC%8C%E6%88%91%E5%BA%94%E8%AF%A5%E5%8E%BB%E5%93%AA%E9%87%8C%E9%AA%8C%E8%AF%81%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%E6%98%AF%E5%90%A6%E8%AE%BE%E7%BD%AE%E6%AD%A3%E7%A1%AE

**Comment by wang233work** [comment]
如何验证环境变量是否设置正确

**Comment by yu285** [comment]
Try this : 

yum -y install  libatomic
