### ISSUE TITLE
Docker core dump where cli use " insert into table_02 select * from table_01"

### ISSUE THREAD

**Issue by msincenselee** [taosdata/TDengine#16245]
**Bug Description**

**To Reproduce**
1. Go to 'taos shell'
2. Type in 'use db01; insert into table_02 select * from table_01;'
3. See error : connection closed, docker core dump.

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [CentOS 7.0]
 - Memory, CPU, current Disk Space: fine
 - TDengine Version [e.g. 3.0.0]
 - Docker run TDengine.

**Additional Context**

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
