### ISSUE TITLE
3.0 LAST. FIRST  function not work as normal in java 

### ISSUE THREAD

**Issue by caiqiqqq** [taosdata/TDengine#16246]
![image](https://user-images.githubusercontent.com/102867723/185574259-7bc7f018-fee9-4bb6-a264-bf92f1c22dc7.png)
这样都没有办法解析，这放回的是个错误的东西
3.0版本

**Comment by yu285** [comment]
jdbc 驱动已经升级到 3.0.0 了吗

**Comment by caiqiqqq** [comment]
升级到了3.0

**Comment by caiqiqqq** [comment]
> 


升级到了3.0

**Comment by huolibo** [comment]
表结构是什么？执行的 SQL 是什么？
最好有一段代码可以复现。否则无法定位问题。

**Comment by caiqiqqq** [comment]
`    <select id="lastOne" resultType="java.util.Map">
        select
        <choose>
            <when test="attribute != null and attribute !=''">
                LAST(${attribute}) as ${attribute}
            </when>
            <otherwise>
                LAST(*)
            </otherwise>
        </choose>
        from #{tableName}
    </select>`

`    Map<String, Object> lastOne(@Param("tableName") String tableName,@Param("attribute") String attribute);
`

**Comment by caiqiqqq** [comment]
`{ "res": true, "count": 62, "data": [ { "Field": "ts", "Type": "TIMESTAMP", "Length": 8, "Note": "" }, { "Field": "city", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "cityid", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "citycode", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "week", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "weather", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "temp", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "temphigh", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "templow", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "img", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "humidity", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "pressure", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "windspeed", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "winddirect", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "windpower", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "updatetime", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "index", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "iname", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "ivalue", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "detail", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "so2", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "so224", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "no2", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "no224", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "co", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "co24", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "o3", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "o38", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "o324", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "pm10", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "pm1024", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "pm2_5", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "pm2_524", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "iso2", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "ino2", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "ico", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "io3", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "io38", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "ipm10", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "ipm2_5", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "aqi", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "primarypollutant", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "quality", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "timepoint", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "aqiinfo", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "level", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "color", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "affect", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "measure", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "daily", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "night", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "sunset", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "day", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "hourly", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "time", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "soncity", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "soncityid", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "soncitycode", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "sunrise", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "date", "Type": "BINARY", "Length": 64, "Note": "" }, { "Field": "deleted", "Type": "BOOL", "Length": 1, "Note": "" }, { "Field": "projectid", "Type": "BINARY", "Length": 64, "Note": "TAG" } ] }`

**Comment by huolibo** [comment]
表结构输出可以在 shell 中执行：
```shell
taos> show databases;
              name              |
=================================
 information_schema             |
 performance_schema             |
 driver                         |
 meters                         |
 log_test                       |
 power                          |
Query OK, 6 rows in database (0.021180s)

taos> use log_test;
Database changed.

taos> show stables;
          stable_name           |
=================================
 dn                             |
Query OK, 1 rows in database (0.016420s)

taos> desc dn;
             field              |         type         |   length    |   note   |
=================================================================================
 ts                             | TIMESTAMP            |           8 |          |
 cpu_taosd                      | FLOAT                |           4 |          |
 cpu_system                     | FLOAT                |           4 |          |
 cpu_cores                      | INT                  |           4 |          |
 mem_taosd                      | FLOAT                |           4 |          |
 mem_system                     | FLOAT                |           4 |          |
 mem_total                      | INT                  |           4 |          |
 disk_used                      | FLOAT                |           4 |          |
 disk_total                     | INT                  |           4 |          |
 band_speed                     | FLOAT                |           4 |          |
 io_read                        | FLOAT                |           4 |          |
 io_write                       | FLOAT                |           4 |          |
 req_http                       | INT                  |           4 |          |
 req_select                     | INT                  |           4 |          |
 req_insert                     | INT                  |           4 |          |
 dnodeid                        | INT                  |           4 | TAG      |
 fqdn                           | VARCHAR              |         128 | TAG      |
Query OK, 17 rows in database (0.008637s)

taos> show create table dn;
             Table              |          Create Table          |
==================================================================
 dn                             | CREATE STABLE `dn` (`ts` TI... |
Query OK, 1 rows in database (0.011423s)

taos> show create table dn\G;
*************************** 1.row ***************************
       Table: dn
Create Table: CREATE STABLE `dn` (`ts` TIMESTAMP, `cpu_taosd` FLOAT, `cpu_system` FLOAT, `cpu_cores` INT, `mem_taosd` FLOAT, `mem_system` FLOAT, `mem_total` INT, `disk_used` FLOAT, `disk_total` INT, `band_speed` FLOAT, `io_read` FLOAT, `io_write` FLOAT, `req_http` INT, `req_select` INT, `req_insert` INT) TAGS (`dnodeid` INT, `fqdn` VARCHAR(128))
Query OK, 1 rows in database (0.007346s)
```
sql 语句为正常可在shell 中执行的命令。比如 mybatis log中的 sql 语句。
可以方便些一个单元测试吗？

**Comment by caiqiqqq** [comment]
taos> desc suowei.s_weather_420104;
             Field              |         Type         |   Length    |   Note   |
=================================================================================
 ts                             | TIMESTAMP            |           8 |          |
 city                           | BINARY               |          64 |          |
 cityid                         | BINARY               |          64 |          |
 citycode                       | BINARY               |          64 |          |
 week                           | BINARY               |          64 |          |
 weather                        | BINARY               |          64 |          |
 temp                           | BINARY               |          64 |          |
 temphigh                       | BINARY               |          64 |          |
 templow                        | BINARY               |          64 |          |
 img                            | BINARY               |          64 |          |
 humidity                       | BINARY               |          64 |          |
 pressure                       | BINARY               |          64 |          |
 windspeed                      | BINARY               |          64 |          |
 winddirect                     | BINARY               |          64 |          |
 windpower                      | BINARY               |          64 |          |
 updatetime                     | BINARY               |          64 |          |
 index                          | BINARY               |          64 |          |
 iname                          | BINARY               |          64 |          |
 ivalue                         | BINARY               |          64 |          |
 detail                         | BINARY               |          64 |          |
 so2                            | BINARY               |          64 |          |
 so224                          | BINARY               |          64 |          |
 no2                            | BINARY               |          64 |          |
 no224                          | BINARY               |          64 |          |
 co                             | BINARY               |          64 |          |
 co24                           | BINARY               |          64 |          |
 o3                             | BINARY               |          64 |          |
 o38                            | BINARY               |          64 |          |
 o324                           | BINARY               |          64 |          |
 pm10                           | BINARY               |          64 |          |
 pm1024                         | BINARY               |          64 |          |
 pm2_5                          | BINARY               |          64 |          |
 pm2_524                        | BINARY               |          64 |          |
 iso2                           | BINARY               |          64 |          |
 ino2                           | BINARY               |          64 |          |
 ico                            | BINARY               |          64 |          |
 io3                            | BINARY               |          64 |          |
 io38                           | BINARY               |          64 |          |
 ipm10                          | BINARY               |          64 |          |
 ipm2_5                         | BINARY               |          64 |          |
 aqi                            | BINARY               |          64 |          |
 primarypollutant               | BINARY               |          64 |          |
 quality                        | BINARY               |          64 |          |
 timepoint                      | BINARY               |          64 |          |
 aqiinfo                        | BINARY               |          64 |          |
 level                          | BINARY               |          64 |          |
 color                          | BINARY               |          64 |          |
 affect                         | BINARY               |          64 |          |
 measure                        | BINARY               |          64 |          |
 daily                          | BINARY               |          64 |          |
 night                          | BINARY               |          64 |          |
 sunset                         | BINARY               |          64 |          |
 day                            | BINARY               |          64 |          |
 hourly                         | BINARY               |          64 |          |
 time                           | BINARY               |          64 |          |
 soncity                        | BINARY               |          64 |          |
 soncityid                      | BINARY               |          64 |          |
 soncitycode                    | BINARY               |          64 |          |
 sunrise                        | BINARY               |          64 |          |
 date                           | BINARY               |          64 |          |
 deleted                        | BOOL                 |           1 |          |
 projectid                      | BINARY               |          64 | TAG      |
Query OK, 62 row(s) in set (0.055824s)

taos> show create table suowei.s_weather_420104
   -> ;
             Table              |          Create Table          |
==================================================================
 s_weather_420104               | CREATE TABLE `s_weather_420... |
Query OK, 1 row(s) in set (0.448093s)

taos> show create table suowei.s_weather_420104\G
   -> ;
*************************** 1.row ***************************
       Table: s_weather_420104
Create Table: CREATE TABLE `s_weather_420104` USING `s_weather` TAGS ("1600768212670")
Query OK, 1 row(s) in set (0.184988s)

**Comment by caiqiqqq** [comment]
`taos> desc suowei.s_weather_420104;
             Field              |         Type         |   Length    |   Note   |
=================================================================================
 ts                             | TIMESTAMP            |           8 |          |
 city                           | BINARY               |          64 |          |
 cityid                         | BINARY               |          64 |          |
 citycode                       | BINARY               |          64 |          |
 week                           | BINARY               |          64 |          |
 weather                        | BINARY               |          64 |          |
 temp                           | BINARY               |          64 |          |
 temphigh                       | BINARY               |          64 |          |
 templow                        | BINARY               |          64 |          |
 img                            | BINARY               |          64 |          |
 humidity                       | BINARY               |          64 |          |
 pressure                       | BINARY               |          64 |          |
 windspeed                      | BINARY               |          64 |          |
 winddirect                     | BINARY               |          64 |          |
 windpower                      | BINARY               |          64 |          |
 updatetime                     | BINARY               |          64 |          |
 index                          | BINARY               |          64 |          |
 iname                          | BINARY               |          64 |          |
 ivalue                         | BINARY               |          64 |          |
 detail                         | BINARY               |          64 |          |
 so2                            | BINARY               |          64 |          |
 so224                          | BINARY               |          64 |          |
 no2                            | BINARY               |          64 |          |
 no224                          | BINARY               |          64 |          |
 co                             | BINARY               |          64 |          |
 co24                           | BINARY               |          64 |          |
 o3                             | BINARY               |          64 |          |
 o38                            | BINARY               |          64 |          |
 o324                           | BINARY               |          64 |          |
 pm10                           | BINARY               |          64 |          |
 pm1024                         | BINARY               |          64 |          |
 pm2_5                          | BINARY               |          64 |          |
 pm2_524                        | BINARY               |          64 |          |
 iso2                           | BINARY               |          64 |          |
 ino2                           | BINARY               |          64 |          |
 ico                            | BINARY               |          64 |          |
 io3                            | BINARY               |          64 |          |
 io38                           | BINARY               |          64 |          |
 ipm10                          | BINARY               |          64 |          |
 ipm2_5                         | BINARY               |          64 |          |
 aqi                            | BINARY               |          64 |          |
 primarypollutant               | BINARY               |          64 |          |
 quality                        | BINARY               |          64 |          |
 timepoint                      | BINARY               |          64 |          |
 aqiinfo                        | BINARY               |          64 |          |
 level                          | BINARY               |          64 |          |
 color                          | BINARY               |          64 |          |
 affect                         | BINARY               |          64 |          |
 measure                        | BINARY               |          64 |          |
 daily                          | BINARY               |          64 |          |
 night                          | BINARY               |          64 |          |
 sunset                         | BINARY               |          64 |          |
 day                            | BINARY               |          64 |          |
 hourly                         | BINARY               |          64 |          |
 time                           | BINARY               |          64 |          |
 soncity                        | BINARY               |          64 |          |
 soncityid                      | BINARY               |          64 |          |
 soncitycode                    | BINARY               |          64 |          |
 sunrise                        | BINARY               |          64 |          |
 date                           | BINARY               |          64 |          |
 deleted                        | BOOL                 |           1 |          |
 projectid                      | BINARY               |          64 | TAG      |
Query OK, 62 row(s) in set (0.055824s)

taos> show create table suowei.s_weather_420104
   -> ;
             Table              |          Create Table          |
==================================================================
 s_weather_420104               | CREATE TABLE `s_weather_420... |
Query OK, 1 row(s) in set (0.448093s)

taos> show create table suowei.s_weather_420104\G
   -> ;
*************************** 1.row ***************************
       Table: s_weather_420104
Create Table: CREATE TABLE `s_weather_420104` USING `s_weather` TAGS ("1600768212670")
Query OK, 1 row(s) in set (0.184988s)
`

**Comment by caiqiqqq** [comment]
之前的环境已经没有了，我看你门已经升级到了3.0.1 我打算升级到3.0.1 看看

**Comment by huolibo** [comment]
我通过此条创建语句不能本地复制此表。CREATE TABLE s_weather_420104 USING s_weather TAGS ("1600768212670") 
请提供 s_weather 的创建语句。
现在还没有发布 3.0.1。此版本是通过 github 源码编译的

**Comment by caiqiqqq** [comment]
Create Table: create table `s_weather` (`ts` TIMESTAMP,`city` BINARY(64),`cityid` BINARY(64),`citycode` BINARY(64),`week` BINARY(64),`weather` BINARY(64),`temp` BINARY(64),`temphigh` BINARY(64),`templow` BINARY(64),`img` BINARY(64),`humidity` BINARY(64),`pressure` BINARY(64),`windspeed` BINARY(64),`winddirect` BINARY(64),`windpower` BINARY(64),`updatetime` BINARY(64),`index` BINARY(64),`iname` BINARY(64),`ivalue` BINARY(64),`detail` BINARY(64),`so2` BINARY(64),`so224` BINARY(64),`no2` BINARY(64),`no224` BINARY(64),`co` BINARY(64),`co24` BINARY(64),`o3` BINARY(64),`o38` BINARY(64),`o324` BINARY(64),`pm10` BINARY(64),`pm1024` BINARY(64),`pm2_5` BINARY(64),`pm2_524` BINARY(64),`iso2` BINARY(64),`ino2` BINARY(64),`ico` BINARY(64),`io3` BINARY(64),`io38` BINARY(64),`ipm10` BINARY(64),`ipm2_5` BINARY(64),`aqi` BINARY(64),`primarypollutant` BINARY(64),`quality` BINARY(64),`timepoint` BINARY(64),`aqiinfo` BINARY(64),`level` BINARY(64),`color` BINARY(64),`affect` BINARY(64),`measure` BINARY(64),`daily` BINARY(64),`night` BINARY(64),`sunset` BINARY(64),`day` BINARY(64),`hourly` BINARY(64),`time` BINARY(64),`soncity` BINARY(64),`soncityid` BINARY(64),`soncitycode` BINARY(64),`sunrise` BINARY(64),`date` BINARY(64),`deleted` BOOL) TAGS (`projectid` BINARY(64))

**Comment by huolibo** [comment]
我看执行的 SQL 就是 select last(*) from s_weather;
我写一个简单的测试程序，看下能否正常运行
```java
import org.junit.*;
import java.sql.*;

public class BindTest {

    private static final String host = "127.0.0.1";
    private Connection conn;

    @Test
    public void mybatisTest() throws SQLException {
        String url = "jdbc:TAOS://" + host + ":6030/meters?user=root&password=taosdata";
        conn = DriverManager.getConnection(url);
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery("select last(*) from s_weather");
        rs.next();
        ResultSetMetaData metaData = rs.getMetaData();
        int c = metaData.getColumnCount();
        for (int i = 1; i <= c; i++) {
            System.out.println(metaData.getColumnLabel(i) + ":" + rs.getString(i));
        }
    }
}
```
