### ISSUE TITLE
"show create database test " output not complete 

### ISSUE THREAD

**Issue by CrossLee** [taosdata/TDengine#16241]
**Bug Description**
![image](https://user-images.githubusercontent.com/4584905/185556475-291450e0-9ffd-419e-8ff6-6bf5a3c43efe.png)
列 Create Database 的语句显示不全

**To Reproduce**
1. 创建一个数据库： create database test;
2. 显示创建语句：show create database test;

**Expected Behavior**
none
**Screenshots**

**Environment (please complete the following information):**
 - docker latest
 - TDengine Version 3.0

**Additional Context**
none

**Comment by yejinmo** [comment]
https://docs.taosdata.com/train-faq/faq/#9-%E8%A1%A8%E5%90%8D%E6%98%BE%E7%A4%BA%E4%B8%8D%E5%85%A8

**Comment by CrossLee** [comment]
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/4584905/185570545-73ed551a-9b68-44c9-b90d-63519efe7b87.png">
