### ISSUE TITLE
where is 3.0Window taosAdapter？

### ISSUE THREAD

**Issue by inprise1980** [taosdata/TDengine#16250]
3.0Window版本如何启动taosAdapter？目前在3.0版本没有看到相关介绍，使用TDengineGUI工具，无法连接成功，要如何设置？

**Comment by sangshuduo** [comment]
稍后会发布 Windows 版 taosAdapter

**Comment by yu285** [comment]
windows 早期问题较多，开源版维护不过来，回收到到企业版重做了。 所以windows版本到了 3.0.7.1 之后就没法再升级了，也没有维护团队支持。所以咱们还是换到 linux 版本再使用，目前最新版为 3.2.3.0。

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
