### ISSUE TITLE
对NCHAR型字段使用like查询时不准确 

### ISSUE THREAD

**Issue by xuejiazhi** [taosdata/TDengine#1625]
对NCHAR型字段使用like查询时不准确 ，两种情况分别全数字和全英文：
 like  '%xyz%' 英文的情况基本查不出来，
 like  '%123%' 用数字的时候就可以查出来，但是数据不准确。

**Comment by Shawshank-Smile** [comment]
This is a bug or a feature needs to be enhanced. Thank you a lot.

**Comment by plum-lihui** [comment]
多谢！
这确实是一个bug，我们会尽快修复。
