### ISSUE TITLE
TDengineGUI connect failed! but docker logs show status 200!

### ISSUE THREAD

**Issue by whoamixl** [taosdata/TDengine#16261]
![d6559a799514282e6a996ba27c74940](https://user-images.githubusercontent.com/49057722/185746446-79e0da3e-62cb-4ed8-9a4e-6bd65ff5da91.png)

I don’t know, Is not need to set other setting？

**Comment by liyl1996** [comment]
我的也是这样，官方文档写的根本就用不了各种版本都尝试了，按官方的来搞心态啊

**Comment by Yanxiaolong1998** [comment]
我自己用python写了一个gui




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月25日(星期四) 下午2:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [taosdata/TDengine] TDengineGUI connect failed! but docker logs show status 200! (Issue #16261)





 
我的也是这样，官方文档写的根本就用不了各种版本都尝试了，按官方的来搞心态啊

**Comment by liyl1996** [comment]
能连的上吗，我们公司部署的能连上，但自己按官方步骤搭建的数据库连不上。。。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月25日(星期四) 下午2:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [taosdata/TDengine] TDengineGUI connect failed! but docker logs show status 200! (Issue #16261)





 我自己用python写了一个gui 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2022年8月25日(星期四) 下午2:24 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [taosdata/TDengine] TDengineGUI connect failed! but docker logs show status 200! (Issue #16261) 
 
 
 
 
 
   
 我的也是这样，官方文档写的根本就用不了各种版本都尝试了，按官方的来搞心态啊

**Comment by Yanxiaolong1998** [comment]
我是3.0用gui连不上，然后我自己写了一个gui，和你的情况应该不一样




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月25日(星期四) 下午2:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [taosdata/TDengine] TDengineGUI connect failed! but docker logs show status 200! (Issue #16261)





 能连的上吗，我们公司部署的能连上，但自己按官方步骤搭建的数据库连不上。。。 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2022年8月25日(星期四) 下午2:26 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [taosdata/TDengine] TDengineGUI connect failed! but docker logs show status 200! (Issue #16261) 
 
 
 
 
 
  我自己用python写了一个gui  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: ***@***.***&amp;amp;gt;;   
  发送时间: 2022年8月25日(星期四) 下午2:24  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: ***@***.***&amp;amp;gt;; ***@***.***&amp;amp;gt;;   
  主题: Re: [taosdata/TDengine] TDengineGUI connect failed! but docker logs show status 200! (Issue #16261)  
   
   
   
   
   
     
  我的也是这样，官方文档写的根本就用不了各种版本都尝试了，按官方的来搞心态啊

**Comment by Doboo** [comment]
TDengineGUI 已经没法用在3.0版本上了。

**Comment by Yanxiaolong1998** [comment]
> TDengineGUI 已经没法用在3.0版本上了。

我自己写的gui

**Comment by Yanxiaolong1998** [comment]
没事，我自己写了一个3.0的gui



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月26日(星期五) 下午5:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [taosdata/TDengine] TDengineGUI connect failed! but docker logs show status 200! (Issue #16261)





 
TDengineGUI 已经没法用在3.0版本上了。

**Comment by arielyang** [comment]
> TDengineGUI 已经没法用在3.0版本上了。

可以用这个 Fork https://github.com/arielyang/TDengineGUI
