### ISSUE TITLE
why rest api /rest/sqlt/db_name is not supported in 3.0

### ISSUE THREAD

**Issue by jianqingdu** [taosdata/TDengine#16289]

**Comment by yu285** [comment]
we provide TO_UNIXTIMESTAMP function for same using .

**Comment by jianqingdu** [comment]
> TO_UNIXTIMESTAMP

 TO_UNIXTIMESTAMP can't apply to the main key (ts in v2.x or _ts in v3.x)

**Comment by rodvlopes** [comment]
`TO_UNIXTIMESTAMP` actually requires a string as an input not a timestamp.
`CAST(ts as BIGINT)` is the way to go.

`curl -u root:taosdata -d "SELECT CAST(ts as BIGINT),v FROM series;" 127.0.0.1:6041/rest/sql/mytable`
