### ISSUE TITLE
c++ 连接失败，版本不一致

### ISSUE THREAD

**Issue by xwangg** [taosdata/TDengine#163]
由于之前虚拟机 `make install` 因为软连接问题编译失败，所以从官网下再 deb 包安装，但是用 c++ connector 连接的时候报:
```
 version of client and server not match
```
补充：
编译的版本也是一样，调试发现  tscSql.c 文件里面的 taos_connect 函数里， version 变量是乱码
```
tscError("taos:%p, server version:%s not equal with client version:%s, close connection",
               taos, server_version, version);
```

**Comment by plum-lihui** [comment]
1、自己编译的版本和从官网下载的安装包，请不要同时使用。否则这两个版本就会出现不匹配的情况。所以在使用版本的时候，最好先将之前安装的版本清理干净。
2、您在编译的时候指定了新的版本号吗？没有指定的话，使用的是src/util/src/version.c中版本号。

**Comment by xwangg** [comment]
这个问题现在还没有解决，等我有时间再提供具体信息。现在我自己编译的时候把那段关于版本检查的注释掉了

**Comment by guanshengliang** [comment]
We modified the code logic for version checking
But you should try to use a compatible link library version
