### ISSUE TITLE
Unable to log in after password change

### ISSUE THREAD

**Issue by w858269620** [taosdata/TDengine#1632]
**Bug Description**
修改密码时，密码不加''，密码能修改成功，但是无法登陆

**To Reproduce**
1. 通过rpm方式安装TDEngine
2. 修改root密码（密码不加''）
   ALTER USER root PASS mypassword
3. 退出taos命令行
4.重新登陆（本机）
   taos -uroot -pmypassword
   无法登陆

**Environment:**
 - OS: CentOS 7.0
 - TDengine Version 1.6.5.5

**Comment by liuyq-617** [comment]
This bug will be fixed in the next version.

**Comment by sangshuduo** [comment]
new version already fix it. close it.
