### ISSUE TITLE
3.0.0 sql caculate is so slow.

### ISSUE THREAD

**Issue by RealForce1024** [taosdata/TDengine#16335]
on version 3.0.0 the sql is so slow. 
for example: `select avg(current), max(voltage), min(phase) from test.meters;` 
will execute more than 10-20s, 
but on version 2.6.0.14 so fast , less than 1s. 

**Screenshots**
on version 3.0.0 -> 19.269301s
<img width="808" alt="image" src="https://user-images.githubusercontent.com/5277544/186099317-c159bc19-197b-4f66-a2b0-e4a981db8ffe.png">

on version 2.6.0.14 -> 0.521119s
<img width="1516" alt="image" src="https://user-images.githubusercontent.com/5277544/186096869-1ab9d7df-ece1-47f4-aa1e-7f7ec08aef6b.png">

os info: ubuntu 20.04 LTS  8C 24G

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
