### ISSUE TITLE
TDEngine3.0 QRY ERROR failed to get tableIds from index

### ISSUE THREAD

**Issue by wendy512** [taosdata/TDengine#16331]
**Bug Description**
执行查询SQL：select avg(f_value) from device_data where metric_key = 'Tmp' and ts >= '2022-08-09 00:00:00' and ts < '2022-08-10 00:00:00'，查看taosdlog报错日志
08/29 15:54:00.015086 00009027 QRY ERROR failed to get tableIds from index, reason:success, suid:6293053938944299386
08/29 15:54:00.015751 00009024 QRY ERROR failed to get tableIds from index, reason:success, suid:6293053938944299386
08/29 15:54:34.953029 00008979 RPC WARN DND-S conn 0x7f0a0c0151b0 read error:EOF

**Environmen**
 - OS: CentOS 7.0
 - Memory, CPU, current Disk Space：16G,4c,800G
 - TDengine Version [3.0.0.1]
 - Kernel: 3.10.0-1160.el7.x86_64

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
