### ISSUE TITLE
3.0 stream's computing name is limited ,could it be unlimited ?

### ISSUE THREAD

**Issue by lixiaopenglidapeng** [taosdata/TDengine#16332]
![431cc9fa65ac740957cad77e4f1d138](https://user-images.githubusercontent.com/25788521/186081774-addad7d4-aa22-449d-b513-13ef299fe635.jpg)

**Comment by yu285** [comment]
3.0早期问题都已经都修复了，流计算已经做了重构。

但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
