### ISSUE TITLE
3.0 Version TDengine with Schemaless writing ，ordinary column‘s data would be deleted

### ISSUE THREAD

**Issue by gisakuya** [taosdata/TDengine#16340]
采用Schemaless模式写入，第一次写入列m1，第二次写入列m2。
2次写入的时间戳是一样的。
第二次写入后会将m1列删除。
2.6 版本不会这样。

下面是3.0版本
![image](https://user-images.githubusercontent.com/12749301/186120846-8b62ab7c-144f-4e8b-a8e7-0eeb954bfca2.png)

下面是2.6版本
![image](https://user-images.githubusercontent.com/12749301/186120792-aff2d693-4988-480a-b77b-f0f6de600146.png)

**Comment by yu285** [comment]
可以提供下 复现问题的 curl 语句不？

**Comment by gisakuya** [comment]
> 可以提供下 复现问题的 curl 语句不？

我是通过原生模式写入（C#）的。rest api好像不支持无架构写入？
我的操作步骤如下：
1、运行程序，插入如下数据：
"meters,id=1,prj=1 m1=1i32 1661233556",
"meters,id=1,prj=1 m1=2i32 1661233561",
"meters,id=1,prj=1 m1=3i32 1661233566",
"meters,id=1,prj=1 m1=4i32 1661233571",
"meters,id=1,prj=1 m1=5i32 1661233576",

2、关闭程序

3、再运行程序，插入如下数据：
"meters,id=2,prj=1 m2=1i32 1661233556",
"meters,id=2,prj=1 m2=2i32 1661233561",
"meters,id=2,prj=1 m2=3i32 1661233566",
"meters,id=2,prj=1 m2=4i32 1661233571",
"meters,id=2,prj=1 m2=5i32 1661233576",

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
