### ISSUE TITLE
Do we have the instruction about how TDengine3.0.0.1 installed in cdh

### ISSUE THREAD

**Issue by xieshengjie** [taosdata/TDengine#16343]
麻烦给一个TDengine3.0.0.1在cdh上安装的教程，及Parcel 包（附TDengine Parcel包 制作教程）

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
