### ISSUE TITLE
已经插入的数据，有什么办法修改吗

### ISSUE THREAD

**Issue by hexuejian** [taosdata/TDengine#1638]
已经插入的数据，有什么办法修改吗

**Comment by plum-lihui** [comment]
TDengine目前不支持插入数据的修改。

**Comment by hexuejian** [comment]
那如果插入错了，只能删除整个库重新插入么

**Comment by Shawshank-Smile** [comment]
生产环境中采集的真实数据，一般是不希望被修改的。

**Comment by eurake** [comment]
由于插入数据不再要求按时间顺序,可以用以下方法实现删除某条记录或更新某条记录
步骤1: 查询某个表的数据, 缓存
步骤2: 修改或删除某条件缓存数据
步骤3: 删除这个表
步骤4: 创建这个表
步骤5: 缓存数据存储

**Comment by zengjianfei** [comment]
> 由于插入数据不再要求按时间顺序,可以用以下方法实现删除某条记录或更新某条记录
> 步骤1: 查询某个表的数据, 缓存
> 步骤2: 修改或删除某条件缓存数据
> 步骤3: 删除这个表
> 步骤4: 创建这个表
> 步骤5: 缓存数据存储

一个几十亿的表这种方法成本是不是太高了
