### ISSUE TITLE
wget -c https://www.taosdata.com/assets-download/TDengine-client-3.0.0.0-Linux-x64.tar.gz

### ISSUE THREAD

**Issue by handsometong** [taosdata/TDengine#16381]
docker容器部署wget -c https://www.taosdata.com/assets-download/TDengine-client-3.0.0.0-Linux-x64.tar.gz
报404 Not Found，是文件没上传仓库吗

**Comment by immccn123** [comment]
请使用这个链接： https://www.taosdata.com/assets-download/3.0/TDengine-client-3.0.0.0-Linux-x64.tar.gz
