### ISSUE TITLE
Unauthorized user can delete any database on version 3

### ISSUE THREAD

**Issue by gisakuya** [taosdata/TDengine#16398]
3.0版本，没有授权的用户，能够随意删除其他数据库

下图是使用root账号创建一个test账号和一个otherdb数据库
![image](https://user-images.githubusercontent.com/12749301/186568882-0912d97c-f2a2-403a-9a2c-3b8a14f42166.png)

下图是使用test账号登录后，能够删除otherdb数据库
![image](https://user-images.githubusercontent.com/12749301/186568995-e7730235-e676-4649-9a10-980fc76a5ad4.png)

**Comment by lcy001001** [comment]
你好，这个问题有解决了吗，我也遇到这个问题
