### ISSUE TITLE
TDengine v3.0.0.1 start up slowly

### ISSUE THREAD

**Issue by Robinsir** [taosdata/TDengine#16394]
windows 版本下，TDengine v3.0.0.1 约插入10万条数据，启动速度非常慢，看了[一篇博客](https://www.cnblogs.com/taosdata/p/15908873.html) ，好像是跟wal有关，但是我没做大批量的DDL操作，windows下taosd --compact-mnode-wal 也用不了,目前只是单机模式。

TDengine配置都是默认配置，下面是建表信息

CREATE DATABASE test_data KEEP 365 DURATION 1 BUFFER 512  WAL_LEVEL 2;
CREATE STABLE st_test (ts timestamp, val binary(64)) TAGS (machine binary(32) ,name binary(32), shift int);

// 以下面的SQL循环插入10万条数据
INSERT INTO test01 USING st_test TAGS('machine01', 'test01',1) VALUES(now(),'1.222');
INSERT INTO test02 USING st_test TAGS('machine02', 'test02',1) VALUES(now(),'1.222');
INSERT INTO test03 USING st_test TAGS('machine03', 'test03',1) VALUES(now(),'1.222');
INSERT INTO test04 USING st_test TAGS('machine04', 'test04',1) VALUES(now(),'1.222');

重启Taosd，之后就需要等待六分钟的启动时间。日志:

08/25 07:01:11.998000 00020748 VND vgId:4, commit-cb is excuted, fsm:000001DB68B73460, index:1106, term:1, msg-index:1106, weak:0, code:0, state:102 leader, type:submit
08/25 07:01:12.002000 00020748 VND vgId:4, commit-cb is excuted, fsm:000001DB68B73460, index:1107, term:1, msg-index:1107, weak:0, code:0, state:102 leader, type:submit
08/25 07:01:12.007000 00020748 VND vgId:4, commit-cb is excuted, fsm:000001DB68B73460, index:1108, term:1, msg-index:1108, weak:0, code:0, state:102 leader, type:submit
08/25 07:01:12.011000 00020748 VND vgId:4, commit-cb is excuted, fsm:000001DB68B73460, index:1109, term:1, msg-index:1109, weak:0, code:0, state:102 leader, type:submit
08/25 07:01:12.015000 00020748 VND vgId:4, commit-cb is excuted, fsm:000001DB68B73460, index:1110, term:1, msg-index:1110, weak:0, code:0, state:102 leader, type:submit
08/25 07:01:12.019000 00020748 VND vgId:4, commit-cb is excuted, fsm:000001DB68B73460, index:1111, term:1, msg-index:1111, weak:0, code:0, state:102 leader, type:submit
。。。。

**Comment by yu285** [comment]
可以把 日志级别开到 143 ，然后删掉旧的日志，重启一下，把新生成的 taosdlog 发我们

**Comment by Robinsir** [comment]
> 可以把 日志级别开到 143 ，然后删掉旧的日志，重启一下，把新生成的 taosdlog 发我们

留个邮箱，太大了

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
