### ISSUE TITLE
Errors about file corruption

### ISSUE THREAD

**Issue by drinkdriver** [taosdata/TDengine#1639]
centos 7
tdengine-1.6.3.0-3
04/17 14:02:06.541360 7fbdeb7fe700 ERROR DND QInfo:0x7fbd6805d740 failed to map header file:/var/lib/taos/tsdb/vnode2/db/v2f1831.head, Invalid argument
1 记录head文件和last文件大小为0kb
2 由于记录head错误,读取某一个分片的head文件出错
3 出现错误的分片数据前后都有其他数据插入,使用默认查询不指定时间时,错误后的数据无法查询到,指定时间后,查询正常
4 taosdump默认导出无法导出出现错误后的数据,指定时间后,导出正常

**Comment by liuyq-617** [comment]
Thanks for your feedback. Inconvenience to your experience. It is recommended that you use a newer version, which solves many bugs

**Comment by sangshuduo** [comment]
请试用 2.0 版本
