### ISSUE TITLE
After adding tags through restful methods, inserting data will take more than an hour to take effect

### ISSUE THREAD

**Issue by xuejiazhi** [taosdata/TDengine#1640]
我一个表新增一个tag ,用restful方式插入数据就会出错，但是在命令行下就不会出错。过大概一个小时左右，restful就又可以了。

**Comment by liuyq-617** [comment]
我使用postman对1.6.5.6的restful进行测试，没有复现出您的问题。能否提供您的版本，并提供测试用例，谢谢

**Comment by sangshuduo** [comment]
请试用 2.0 版本
