### ISSUE TITLE
Double values Not Stored Correctly via TaosAdapter/TAO-RS in 3.0

### ISSUE THREAD

**Issue by ipaddicting** [taosdata/TDengine#16404]
**Bug Description**
When inserting double values into tables through TaosAdapter i.e. TAO-RS, the results were wrong.

**To Reproduce**
1. Create the stable: 
`CREATE STABLE vehicle_traces (ts timestamp, longitude double, latitude double) TAGS (plate BINARY(18), dispatch_center BINARY(64));`
2. Create a table:
`CREATE TABLE tbox001_traces USING vehicle_traces TAGS ("HC99999", "Minbei Dispatch Center");`
3. Insert rows via Restful API, the plain SQL as follows:
`INSERT INTO tbox001_traces VALUES (1661393141000, 12114.281311, 3112.485962)(1661393142000, 12114.281769, 3112.485962)(1661393143000, 12114.281769, 3112.485847);`

**Expected Behavior**
Correct values persisted.

**Screenshots**
Debugging program:
<img width="1230" alt="Screen Shot 2022-08-25 at 14 11 50" src="https://user-images.githubusercontent.com/244768/186591481-ea00534a-c3c0-4078-82e4-525b7e841aba.png">

After program execution, searching data from the console, all double values are messed: 
<img width="664" alt="Screen Shot 2022-08-25 at 14 12 39" src="https://user-images.githubusercontent.com/244768/186591592-e72506c3-0237-4ea1-80f1-669cf3f14691.png">

But no such issue if the same updates are applying directly from the console:
<img width="1346" alt="Screen Shot 2022-08-25 at 14 10 14" src="https://user-images.githubusercontent.com/244768/186591803-cb56593d-26fc-4d78-95d8-c9c4b94d17fe.png">

Table description:
<img width="659" alt="Screen Shot 2022-08-25 at 14 12 59" src="https://user-images.githubusercontent.com/244768/186592018-7848f045-b2da-46db-8ee6-ef1b3c2e70c2.png">

**Environment (please complete the following information):**
 - MBP M1 macOS Monterey 12.5.1 
 - Docker Desktop 4.11.1
 - TDengine Version 3.0.0.0

**Comment by sangshuduo** [comment]
@ipaddicting  may I know what language you use to access TDengine? The screenshot looks like Scala? Are you using Scala with JDBC connector? What version the connector is?

**Comment by ipaddicting** [comment]
> 

Kotlin 1.6.21 & JVM target Java 11, so it's the 3.0.0 Java connector.

**Comment by huolibo** [comment]
Here is a test case for Java. You can try it to see if it works:
```java
package com.taosdata.jdbc;

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

import java.sql.*;

public class TDengineTest {

    private static final String host = "127.0.0.1";
    private static final String stable = "vehicle_traces";
    private static final String table = "tbox001_traces";
    private static Connection conn = null;
    private static Statement stmt = null;

    @Test
    public void doubleTest() throws SQLException {
        stmt.execute("INSERT INTO " + table + " VALUES (1661393141000, 12114.281311, 3112.485962)(1661393142000, 12114.281769, 3112.485962)(1661393143000, 12114.281769, 3112.485847)");
        ResultSet resultSet = stmt.executeQuery("select * from " + table);
        while (resultSet.next()) {
            System.out.println("longitude:" + resultSet.getDouble("longitude")
                    + ", latitude:" + resultSet.getDouble("latitude"));
            Assert.assertNotEquals(0, resultSet.getDouble("latitude"), 0);
        }
    }

    @Before
    public void before() throws SQLException {
        String url = "jdbc:TAOS-RS://" + host + ":6041/?user=root&password=taosdata";
        conn = DriverManager.getConnection(url);
        stmt = conn.createStatement();
        stmt.execute("drop database if exists test_pd");
        stmt.execute("create database if not exists test_pd");
        stmt.execute("use test_pd");
        stmt.execute("create table " + stable
                + "(ts timestamp, longitude double, latitude double) TAGS (plate BINARY(18), dispatch_center BINARY(64))");
        stmt.execute("CREATE TABLE " + table + " USING " + stable + " TAGS ('HC99999', 'Minbei Dispatch Center')");
    }

    @After
    public void after() {
        try {
            if (stmt != null) {
                stmt.execute("drop database if exists test_pd");
                stmt.close();
            }
            if (conn != null)
                conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}

```
Run it like `mvn clean test -Dtest=com.taosdata.jdbc.TDengineTest#doubleTest`
Result in my compute: 
```shell
java version：11.0.16
longitude:12114.281311, latitude:3112.485962
longitude:12114.281769, latitude:3112.485962
longitude:12114.281769, latitude:3112.485847
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.12 s - in com.taosdata.jdbc.TDengineTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by ipaddicting** [comment]
It seems related to changes in table schema, at the beginning I created the table `tbox001_traces` with `float` type for both `longitude` and `latitude`, and then I changed them to `double`... 

After creating the database & table, everything is OK now.

I guess something wrong with cache since direct updates in console always behave as expected.
