### ISSUE TITLE
TDengine 3 最好能具备windows服务能力（TDengine 3 preferably with windows service capability）

### ISSUE THREAD

**Issue by cockroach888** [taosdata/TDengine#16411]
现在TDengine的Windows版本，需要进入到目录，手动执行启动，而且启动后会有一个常驻窗口，能否提供windows服务执行能力，最好能静默运行。谢谢。

The Windows version of TDengine now requires access to the directory and manual execution of startup, and there is a resident window after startup. Can it provide the ability to execute windows services, preferably running silently.

**Comment by yu285** [comment]
我们看下。

**Comment by cockroach888** [comment]
目前3.0在使用上确实存在着诸多挑战，但这也意味着，产品在越来越好，期待。

**Comment by Doboo** [comment]
可以自己使用工具安装为服务的，没有窗口。

**Comment by cockroach888** [comment]
> 可以自己使用工具安装为服务的，没有窗口。

是的，自己单独处理，方法可以有多种；但从一款产品角度来讲，还是应当多考虑一些定式，会更好一些。

**Comment by simple-phil** [comment]
> 可以自己使用工具安装为服务的，没有窗口。

请问下，您是通过什么工具安装成服务的，我通过sc命令安装的服务启动不成功
