### ISSUE TITLE
Running TDengine in docker with errorCode 9044

### ISSUE THREAD

**Issue by handsometong** [taosdata/TDengine#16410]
**Bug Description**
1、java -jar运行代码正常
2、tdengine版本3.0.0.0
3、docker容器中会报错，容器已启动tdengine客户端且taos不报错
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/12708876/186610123-b03635da-21ec-45b4-8d9f-c4053495d082.png">

**Comment by shenglian-zhou** [comment]
could you please attach logs to help identifying root cause? thanks a lot.

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
