### ISSUE TITLE
C# connector writing  to TDengine would cost cpu a lot

### ISSUE THREAD

**Issue by jiangzhuangxiansheng** [taosdata/TDengine#16422]
帖下测试代码，间隔1秒循环去写入，不太确定是否是我使用问题
![image](https://user-images.githubusercontent.com/33273148/186647711-4fb519f6-d319-4f86-93a5-e6af3cc3a0b3.png)

环境
系统:centos7
服务端:  3.0.0.1(非容器部署)，配置未做任何改动
client端：.net 6 跑在docker容器中

下图是写入时:cpu的情况，会慢慢累加
![image](https://user-images.githubusercontent.com/33273148/186648418-ab36d32b-cecd-40c9-bcb0-5a9178b0be2f.png)
下图是停止写入时
![image](https://user-images.githubusercontent.com/33273148/186648506-54fa2e0e-7f02-4139-91a7-1a6fd591dd2d.png)

**Comment by xleili** [comment]
在使用完TDengine.Query() 返回的res 后，需要手动的调用释放内存。应为这部分内存是C的内存，GC无法自动回收。
方法：
       ` static extern public void FreeResult(IntPtr res);`
方法连接：
https://github.com/taosdata/taos-connector-dotnet/blob/6dfeda25a67d3f04893729317e9ae72a9f88bd7a/src/TDengine.Driver/Impl/NativeMethod/TaoscNativeMethods.cs#L85

**Comment by jiangzhuangxiansheng** [comment]
按照回复手动调用了 TDengine.FreeResult(conn) 方法，依然会出现相同的问题，cpu缓慢增长
![image](https://user-images.githubusercontent.com/33273148/186806130-0a9e9e8c-e362-42d0-b153-821c75275860.png)

情况和上面一致，下图未写入时
![image](https://user-images.githubusercontent.com/33273148/186808619-4d7f5b7e-fbf0-4066-bef8-3279158b66cf.png)

写入是缓慢增加
![image](https://user-images.githubusercontent.com/33273148/186808699-99f58359-865b-4621-830d-d0dd3b656482.png)

和上图间隔2分钟左右
![image](https://user-images.githubusercontent.com/33273148/186809032-84139947-12a9-4934-843e-4652f64ca052.png)

**Comment by jiangzhuangxiansheng** [comment]
已解决！
