### ISSUE TITLE
wsl1 can't connect to 3.0 taosd service

### ISSUE THREAD

**Issue by Yurunsoft** [taosdata/TDengine#16425]
**Bug Description**

wsl1里连不上任何tdengine 3.0服务器，docker、windows安装都不行

![image](https://user-images.githubusercontent.com/20104656/186796749-0b08beb7-ece1-425a-adf2-f840c5ea3d3f.png)

但是从windows的taos可以连上

![image](https://user-images.githubusercontent.com/20104656/186796775-9e586678-789a-4df2-8be3-6afd31f27117.png)

wsl1 里 telnet是通的

![image](https://user-images.githubusercontent.com/20104656/186796816-1f0aefda-109a-4451-b1ae-e31049e67170.png)

看了下3.0的rpcForceTcp砍了，是因为这个所以连不上了吗，以前是配了rpcForceTcp 1才可以从wsl1连接

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: WSL1 + Ubuntu 20.04.4 LTS
 - Memory, CPU, current Disk Space
 - TDengine Version 3.0

**Additional Context**

**Comment by yu285** [comment]
服务端就在 windows 机器 是么

**Comment by Yurunsoft** [comment]
对，安装的 windows 版 server 和 docker 都不行

**Comment by Yurunsoft** [comment]
```log
root@LAPTOP-15IRLJ0T:/etc/taos# curl -L -H "Authorization: Basic cm9vdDp0YW9zZGF0YQ==" -d "show databases" 127.0.0.1:6041/rest/sql
{"code":0,"column_meta":[["name","VARCHAR",64]],"data":[["information_schema"],["performance_schema"]],"rows":2}

root@LAPTOP-15IRLJ0T:/etc/taos# taos -h 127.0.0.1 -P 6030
Welcome to the TDengine Command Line Interface, Client Version:3.0.1.5
Copyright (c) 2022 by TDengine, all rights reserved.

failed to connect to server, reason: Unable to establish connection
```

2个月过去了，还是没有解决

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
