### ISSUE TITLE
schemaless writing to TDengine with ERROR (2350): failed to insertLines

### ISSUE THREAD

**Issue by qingquaner** [taosdata/TDengine#16426]
TDengine版本：2.4.0.12

单条数据，如下
product_z9jk7sr6_data,tableName=device_data_062016221950014,tenant_id=1532176835246374914,tenant_code=1532176835227766784,model_code=default create_time=L"2022-08-26 09:47:01",device_bus_id=L"062016221950014",device_code=L"062016221950014",k01=L"138:45:14 true",k02=L"93:42:2 false",k03=L"147:36:30 true",k04=L"49:53:4 true",k05=L"51:59:4 false" 1661478352859

现象：
大多数情况下，能插入数据，偶尔出现TDengine ERROR (2350): failed to insertLines 异常

现无法定位原因。。。

**Comment by huolibo** [comment]
在此情况下需要查看 /var/log/taos 目录下的 taoslog，进行错误分析。
此版本在 jdbc 层没有获取 error 信息。建议使用 taosd 至 2.4.0.14 及以上版本，jdbc 升级至 2.0.38 版本。在此配置下 jdbc 可获取 schemaless 错误信息。

**Comment by qingquaner** [comment]
在taosinfo日志文件中找到的日志：
08/26 10:10:22.280424 00011095 VND ERROR vgId:40, failed to write into vwqueue since no diskspace, avail:1.982159GB

这是磁盘不足引起的吗？

**Comment by huolibo** [comment]
估计不是 其中应该包含 JNI ERROR。格式为"jobj:%p, conn:%p, code:%s, msg:%s".
版本升级后，可将 msg 信息反馈到 java 层。

**Comment by qingquaner** [comment]
ok
有机会升级后再定位一下
