### ISSUE TITLE
upgrade issue with 3.0.0.1 version 

### ISSUE THREAD

**Issue by skyformat99** [taosdata/TDengine#16449]
1） git clone  最新代码
2） 直接 build.sh
3）cd debug  ,   make install
4) systemctrl  start taosd

出现如下错误：
08/26 07:36:28.958692 00020343 UDF start to init udfd
08/26 07:36:28.959224 00020343 UDF ERROR can not spawn udfd. path: taosd/udfd, error: no such file or directory
08/26 07:36:28.959309 00020337 UDF udfd is cleaned up after spawn err
08/26 07:36:28.959320 00020337 DND ERROR failed to start udfd
08/26 07:36:28.959323 00020337 DND node:dnode, has been opened
08/26 07:36:28.959331 00020337 DND node:mnode, start to open
08/26 07:36:28.959362 00020337 WAL wal module is initialized, rsetId:3

TDengine/source/dnode/vnode/src/tsdb/tsdbFS.c:427: tsdbRecoverFS: Assertion `n + sizeof(TSCKSUM) == nData' failed.

备注： 之前的代码编译运行是OK的。
今天的最新的代码出现问题了。

**Comment by yu285** [comment]
3.0.0.1 和 3.0.0.0 底层做了调整，麻烦删除数据文件再启用。后续不会出现类似情况。

**Comment by skyformat99** [comment]
还真是啊；删除后ok了
搞定
