### ISSUE TITLE
taosBenchMark query test issue

### ISSUE THREAD

**Issue by sanliang125** [taosdata/TDengine#16442]
**Bug Description**
使用taosBenchMark进行大数据量查询测试时失败,导致服务器不可访问，并且后续服务器的内存居高不下。

**To Reproduce**
1. 使用 `taosBenchmark 	  -y 	-x` 命令进行查询效率检查。
2. 命令执行了数据插入操作后，执行了部分数据查询，然后我的服务器就卡住不可用了。
3. 一段时间后，我再次登陆上了服务器，发现内存居高不下。

**Expected Behavior**
我原本是想按照taosBenchmark来进行插入、查询的性能测试。其他功能基本上都测试过了，但是到了这个查询性能测试功能出现了异常情况。

**Screenshots**
服务器内存居高不下
![image](https://user-images.githubusercontent.com/29949952/186848466-3793b926-c49d-477e-9e7d-5146767d94a1.png)

**Environment ：**
 - OS: [ CentOS 7.6]
 - 4C8G
 - TDengine Version [3.0.0.1]

**Comment by yu285** [comment]
可以添加微信 15652223354 做具体排查

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
