### ISSUE TITLE
After updating ,The  query result value  comes and goes

### ISSUE THREAD

**Issue by DarkGodOne** [taosdata/TDengine#16457]
我用的2.4.0.5版本，今天发现一部分旧数据没有导入，所以写了程序从旧库里面读取数据存入新库中，数据量在680w条左右；超级表是支持更新插入的，因为出现这个问题，我又重新插入了好几次都没成功；
插入过程中没有任何报错，但是查询的时候出现数据时有时无的情况，这是啥情况？？？
![image](https://user-images.githubusercontent.com/12151282/187032158-fb577f46-4e8e-4fda-be5b-214ac1453844.png)
![image](https://user-images.githubusercontent.com/12151282/187032165-2f62153e-7cf4-4e87-87ec-1b3bfa813784.png)
使用的同一个查询语句，一会有一会就没了
麻烦给个答复

**Comment by DarkGodOne** [comment]
还有一些表数据中，原始库中是有值的，但是新库中就没有值了，真怪了，你们这个能保证数据准确和安全么？

**Comment by yu285** [comment]
生产环境还是测试环境，可以加下微信 做具体排查 15652223354

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
