### ISSUE TITLE
taosd  crashed : updateTableLatestColumn: Assertion `pTCol->bytes >= bytes' failed

### ISSUE THREAD

**Issue by soar4** [taosdata/TDengine#16462]
情景描述：
暂未找到重现方法。当天有多次手动修改表结构操作行为。操作完成后，未见崩溃。
业务程序只会往 tdengine 中插入数据，不会自动修改表结构。
晚上的时候 taosd 崩溃. 崩溃后，有尝试重新拉起，但每次拉起都会崩溃，崩溃在同一个地方。

期望行为：
期望程序崩溃后，再拉起能正常工作。数据丢失部分也可以接受。

环境信息
 - OS:  CentOS Linux release 7.9.2009 (Core)
 - Memory 32G, CPU 16Core, DiskSpace 1.8T
 - TDengine Version 2.6.0.12

gdb 反解core信息
[owdev@u0730004 bin]$ gdb taosd core.2441 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/taos/bin/taosd...done.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/local/taos/bin/taosd -c /usr/local/taos/conf'.
Program terminated with signal 6, Aborted.
#0  0x00007f8d134e6387 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-326.el7_9.x86_64
(gdb) bt
#0  0x00007f8d134e6387 in raise () from /lib64/libc.so.6
#1  0x00007f8d134e7bb8 in abort () from /lib64/libc.so.6
#2  0x00007f8d134df1a6 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007f8d134df252 in __assert_fail () from /lib64/libc.so.6
#4  0x00007f8d141a8e84 in updateTableLatestColumn (pRepo=0x7f8cc0001110, pTable=0x7f8cc1e895d0, row=0x7f8c772f1d36)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbMemTable.c:1068
#5  0x00007f8d141a9679 in tsdbUpdateTableLatestInfo (pRepo=0x7f8cc0001110, pTable=0x7f8cc1e895d0, row=0x7f8c772f1d36)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbMemTable.c:1117
#6  0x00007f8d141a7d78 in tsdbInsertDataToTable (pRepo=0x7f8cc0001110, pBlock=0x7f8bb04f9259, 
    pAffectedRows=0x7f8ce3ffe424) at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbMemTable.c:901
#7  0x00007f8d141a3c69 in tsdbInsertData (repo=0x7f8cc0001110, pMsg=0x7f8bb04f9248, pRsp=0x0, ppSem=0x0)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbMemTable.c:82
#8  0x000055817b96fbba in vnodeProcessSubmitMsg (pVnode=0x7f8cc00008c0, pCont=0x7f8bb04f9248, pRet=0x0)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/vnode/src/vnodeWrite.c:178
#9  0x000055817b96f892 in vnodeProcessWrite (vparam=0x7f8cc00008c0, wparam=0x7f8bb04f9230, qtype=2, rparam=0x0)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/vnode/src/vnodeWrite.c:123
#10 0x000055817b968703 in walRestoreWalFile (pWal=0x7f8cc29a7460, pVnode=0x7f8cc00008c0, 
    writeFp=0x55817b96f3fd <vnodeProcessWrite>, name=0x7f8ce3ffe5e0 "/mnt/sdb/taos/data/vnode/vnode12/wal/wal562", 
    fileId=562) at /home/ubuntu/workroom/jenkins/TDinternal/community/src/wal/src/walWrite.c:551
#11 0x000055817b96743a in walRestore (handle=0x7f8cc29a7460, pVnode=0x7f8cc00008c0, 
    writeFp=0x55817b96f3fd <vnodeProcessWrite>)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/wal/src/walWrite.c:203
#12 0x000055817b96a5d4 in vnodeOpen (vgId=12)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/vnode/src/vnodeMain.c:369
#13 0x000055817b92e2fd in dnodeOpenVnode (param=0x55817c578410)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/dnode/src/dnodeVnodes.c:101
#14 0x00007f8d13885ea5 in start_thread () from /lib64/libpthread.so.0
#15 0x00007f8d135aeb0d in clone () from /lib64/libc.so.6
(gdb) f 4
#4  0x00007f8d141a8e84 in updateTableLatestColumn (pRepo=0x7f8cc0001110, pTable=0x7f8cc1e895d0, row=0x7f8c772f1d36)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbMemTable.c:1068
1068	/home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbMemTable.c: No such file or directory.
(gdb) info locals 
idx = 7
value = 0x7f8c772f1dc8
pDataCol = 0x7f8b9fb27110
bytes = 34
pTCol = 0x7f8cc1e89f08
j = 7
pSchema = 0x7f8cc1e89ec0
pLatestCols = 0x7f8b9fb26fc0
kvIdx = 0
__PRETTY_FUNCTION__ = "updateTableLatestColumn"
(gdb) p *pTCol
$1 = {type = 8 '\b', colId = 7, bytes = 26, offset = 32}
(gdb)

可以看到 pTCol->bytes = 26; bytes=34 。触发断言崩溃。
正在寻找能重启 taosd 成功的方法。

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
