### ISSUE TITLE
restful connector support influxdb line protocol ?

### ISSUE THREAD

**Issue by zhou-hao** [taosdata/TDengine#16480]
顺便问一下：restful方式和使用动态链接库的方式性能差距有多大？ 是否提供更高效的tcp客户端协议？是否支持或者计划支持服务端sql预编译？

**Comment by sangshuduo** [comment]
请参考： https://docs.taosdata.com/reference/taosadapter/ 以及 https://docs.taosdata.com/connector/

**Comment by zhou-hao** [comment]
@sangshuduo 
restful方式和使用动态链接库的方式性能差距有多大？ 
是否提供更高效的tcp客户端协议？
是否支持或者计划支持服务端sql预编译？

**Comment by sangshuduo** [comment]
REST 接口性能和 client/server 间网络质量有很大关系。在相同机器测试证明排除网络质量性能损失并不大，10% 左右。
另外两个需求，暂时没有精力做。

**Comment by zhou-hao** [comment]
好的，感谢回复。

**Comment by marvel00000** [comment]
咨询下楼主，结论是现阶段不支持restful方式 使用influxdb 格式数据写入dengine 吧？

**Comment by arielyang** [comment]
> 咨询下楼主，结论是现阶段不支持restful方式 使用influxdb 格式数据写入dengine 吧？

Check these:
https://docs.taosdata.com/develop/insert-data/influxdb-line/
https://docs.taosdata.com/connector/schemaless-api/
