### ISSUE TITLE
query result not correct 

### ISSUE THREAD

**Issue by fawdlstty** [taosdata/TDengine#16493]
**Bug Description**
查询语句执行错了

**To Reproduce**
1. rest接口请求 `select count(*)+1 from INFORMATION_SCHEMA.INS_DATABASES where name = 'aaa';`
2. 返回`{"code":0,"column_meta":[["count(*)+1","DOUBLE",8]],"data":[],"rows":0}`

**Expected Behavior**
不管是否存在aaa这个数据库，理论上返回值只可能为1或2或报错,但实际json里没有1或2，也没报错

**Screenshots**

**Environment (please complete the following information):**
 - OS: Kubuntu 20.04
 - Memory, CPU, current Disk Space
 - TDengine Version 3.0.0.1

**Additional Context**

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
