### ISSUE TITLE
compile error in unbutu 16.04 and centos7.6

### ISSUE THREAD

**Issue by foxxnuaa** [taosdata/TDengine#165]
[root@ecs-2186-0001 build]# cmake .. && cmake --build
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Project source directory: /data/TDengine
-- Build Debug Version
-- Project binary output path: /data/TDengine/build
-- Executable files output path: /data/TDengine/build/build/bin
-- Project library output path: /data/TDengine/build/build/lib
-- Check targe platform x64, pass
-- Use the iconv functions in GLIBC
-- build version 
### CMake Error at src/client/CMakeLists.txt:30 (SET_TARGET_PROPERTIES):
  set_target_properties called with incorrect number of arguments.

**Comment by guanshengliang** [comment]
您先将这行代码注释掉，我们这几天会修改一下CMakeList脚本，同时修复这个问题

```
SET_TARGET_PROPERTIES(taos PROPERTIES VERSION ${VERSION_INFO} SOVERSION 1)
```

**Comment by foxxnuaa** [comment]
我自己先修改了makefile，编译通过了。
