### ISSUE TITLE
Last function have result after all data been delete.

### ISSUE THREAD

**Issue by wsf1990** [taosdata/TDengine#16517]
**Bug Description**
使用delete from table 删除所有数据之后，使用 select last(*) from table依旧能够查出内容。
**To Reproduce**
1. delete from table
2. select last(*) from table

**Screenshots**
![image](https://user-images.githubusercontent.com/8774884/187405565-6d3558de-4a1b-4bb5-b388-331176723ba0.png)

**Environment (please complete the following information):**
 - TDengine Version 3.0.0.0

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
