### ISSUE TITLE
bool type query

### ISSUE THREAD

**Issue by yagnzheng** [taosdata/TDengine#16528]
**Bug Description**
使用jdbc连接和 GUI界面查询 布尔类型字段时，查询为空，但是执行命令确可以查出来
**To Reproduce**
1. 存储一条布尔值数据
2. 使用java进行jdbc连接 或者打开GUI
3. 该条记录 对应的布尔类型 字段为空

**Expected Behavior**
希望可以查询出该字段

**Screenshots**
![image](https://user-images.githubusercontent.com/69229422/187612352-5a788bac-e137-44c5-9e1f-5dab5493904a.png)

![image](https://user-images.githubusercontent.com/69229422/187612555-42c9bfe2-4ce9-4153-8161-eab8874f911b.png)

**Environment (please complete the following information):**
 - 联想拯救者R9000
 - TDengine Version [e.g. 2.6.0.15]

**Additional Context**

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
