### ISSUE TITLE
C# 使用TDengine.Connector 3.0

### ISSUE THREAD

**Issue by Seven365** [taosdata/TDengine#16534]
**Bug Description**
示例代码中
public void InitTDengine()
{
    TDengine.Options((int)TDengineInitOption.TDDB_OPTION_CONFIGDIR, this.configDir);
    TDengine.Options((int)TDengineInitOption.TDDB_OPTION_SHELL_ACTIVITY_TIMER, "60");
    TDengine.Init();
    Console.WriteLine("TDengine Initialization finished");
}
无法找到
TDDB_OPTION_CONFIGDIR
TDDB_OPTION_SHELL_ACTIVITY_TIMER
修改为
TSDB_OPTION_CONFIGDIR
TSDB_OPTION_SHELL_ACTIVITY_TIMER

TDengine.Init();函数不存在，提供了一个新的
public static extern IntPtr StmtInit(IntPtr taos);
不知道如何使用

**Comment by xleili** [comment]
3.0 中移除了TDengine.Init();这个接口。
在应用中可以不调用TDengine.Init(); 这个接口。
此外：public static extern IntPtr StmtInit(IntPtr taos); 这是STMT（参数绑定）是初始化stmt用的。

可以提供示例代码的出处吗，方便我们把示例代码中的问题修改过来。

**Comment by Seven365** [comment]
https://github.com/taosdata/TDengine/blob/develop/examples/C%23/TDengineTest/TDengineTest.cs 182:188

**Comment by Seven365** [comment]
> 3.0 中移除了TDengine.Init();这个接口。 在应用中可以不调用TDengine.Init(); 这个接口。 此外：public static extern IntPtr StmtInit(IntPtr taos); 这是STMT（参数绑定）是初始化stmt用的。
> 
> 可以提供示例代码的出处吗，方便我们把示例代码中的问题修改过来。

https://github.com/taosdata/TDengine/blob/develop/examples/C%23/TDengineTest/TDengineTest.cs 182:188
