### ISSUE TITLE
 taosTools-2.1.2 taosdump导出失败

### ISSUE THREAD

**Issue by homeless2010** [taosdata/TDengine#16530]
![image](https://user-images.githubusercontent.com/26829140/187628988-2a381a5d-0ac6-4847-af20-e06452d82202.png)

**Comment by sangshuduo** [comment]
看看系统里是不是没有安装 zlib

**Comment by homeless2010** [comment]
tdengine server 为docker容器 在宿主机安装taostools使用taosdump失败，理论应该可以但最终没成功，只好在容器中导出

**Comment by sangshuduo** [comment]
> tdengine server 为docker容器 在宿主机安装taostools使用taosdump失败，理论应该可以但最终没成功，只好在容器中导出

taosdump 只是一个使用客户端接口的应用，taosdump 不行 taos shell 估计也不行，可以参考一下官网 FAQ 自查一下原因
