### ISSUE TITLE
Windows7 client can connect to the server, but can not insert data or query data

### ISSUE THREAD

**Issue by shaoyingfei** [taosdata/TDengine#1653]
**Bug Description**
win7的客户端可以连接服务端数据库，可以新建表，但是不能查询，插入数据

**Environment (please complete the following information):**
 -CentOS 7.7
 - TDengine Version 1.6.5.7

**Comment by liuyq-617** [comment]
可以提供一些日志吗？
把客户端和服务端的调试日志都调成135
debugFlag 135

**Comment by liuyq-617** [comment]
经过分析，是由于服务器的防火墙阻断了导致，请确保端口范围 6035 - 6039 的5个端口用于UDP通信
