### ISSUE TITLE
⚠️Alter user password issues!

### ISSUE THREAD

**Issue by jetadore** [taosdata/TDengine#16579]
**Bug Description**

When I change the user password, the old authentication remains valid until rebooting

**To Reproduce**
1.  `docker exec -it taos taos -s "SHOW users;"`
```
Welcome to the TDengine Command Line Interface, Client Version:3.0.0.1
Copyright (c) 2022 by TDengine, all rights reserved.

taos> SHOW users;
           name           | super | enable | sysinfo |       create_time       |
================================================================================
 root                     |     1 |      1 |       1 | 2022-09-01 17:32:14.707 |
Query OK, 1 rows in database (0.003443s)
```

2.  `curl -u root:taosdata -d 'show databases' xxx.xxx.xxx.xxx:6041/rest/sql`
```
{"code":0,"column_meta":[["name","VARCHAR",64]],"data":[["information_schema"],["performance_schema"]],"rows":2}%
```

3.  `docker exec -it taos taos -s "ALTER USER root PASS 'NoNews14GoodNews';"`

4.  `curl -u root:taosdata -d 'show databases' xxx.xxx.xxx.xxx:6041/rest/sql`
```
{"code":0,"column_meta":[["name","VARCHAR",64]],"data":[["information_schema"],["performance_schema"]],"rows":2}% 
```

5. `docker restart taos`

6.  `curl -u root:taosdata -d 'show databases' xxx.xxx.xxx.xxx:6041/rest/sql`
```
{"Code":855,"ErrStr":"Authentication failure"}%  
```

7.  `docker exec -it taos taos -pNoNews14GoodNews -s "SHOW users;"`
```
Welcome to the TDengine Command Line Interface, Client Version:3.0.0.1
Copyright (c) 2022 by TDengine, all rights reserved.

taos> SHOW users;
           name           | super | enable | sysinfo |       create_time       |
================================================================================
 root                     |     1 |      1 |       1 | 2022-09-01 17:32:14.707 |
Query OK, 1 rows in database (0.003443s)
```

**Expected Behavior**

*should #4 logs the same as #6?*

**Environment (please complete the following information):**
 - OS: [Docker@TetentYun#Debian ]
 - TDengine Version 3.0.0.1

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
