### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by whoamixl** [taosdata/TDengine#16578]
TDengine3.0!
execute sql  " select count(*) from yuwei_iot.water_info"   
TDengine service can lost connect and restart
Before that, I add some column and tags in water_info.
![image](https://user-images.githubusercontent.com/49057722/187864199-07d98009-9a3d-4bac-b383-b8e28309b6cd.png)

**Comment by yu285** [comment]
May I know your product version is 3.0.0.0 or 3.0.0.1 ?

if 3.0.0.0  , could you use the newest version ? like 3.0.0.1

if 3.0.0.1 , you could try "develop" branch or "main " branch to test it .

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
