### ISSUE TITLE
jdbc sql and shell SQL  result  are not same

### ISSUE THREAD

**Issue by daixyoung** [taosdata/TDengine#16577]
taos-jdbcdriver版本3.0.0
tdengine版本3.0

```shell
# 创建超级表
create stable stable_float (ts timestamp, value float) tags (device_id bigint, field_name nchar(32));

# 创建子表
create table t_20220831_temperature using stable_float tags (20220831,"temperature");
create table t_20220831_humidity using stable_float tags (20220831,"humidity");

# 插入数据
insert into t_20220831_temperature values (now,34.1);
insert into t_20220831_humidity values (now,50.2);
insert into t_20220831_temperature values (now,32.1);
insert into t_20220831_humidity values (now,52.2);

# 查询sql
select last(data) data, field_name from stable_float where device_id = 20220831 group by field_name;
```

#### 控制台
![image](https://user-images.githubusercontent.com/46256172/187863800-93f0b7d7-6498-4940-a6d4-61e3aa171793.png)
#### jdbc
![image](https://user-images.githubusercontent.com/46256172/187864007-e48058d7-490c-4fb9-84e1-c56eb3d7e5e3.png)

**Comment by daixyoung** [comment]
尝试使用field_name加上last()函数，查询就正常了
```sql
select last(data) data, last(field_name) from stable_float where device_id = 20220831 group by field_name;
```

**Comment by yu285** [comment]
> 尝试使用field_name加上last()函数，查询就正常了
> 
> ```sql
> select last(data) data, last(field_name) from stable_float where device_id = 20220831 group by field_name;
> ```
这个正常的定义是，与“控制台”保持了一致，对吗

**Comment by daixyoung** [comment]
> > 尝试使用field_name加上last()函数，查询就正常了
> > ```sql
> > select last(data) data, last(field_name) from stable_float where device_id = 20220831 group by field_name;
> > ```
> 
> 这个正常的定义是，与“控制台”保持了一致，对吗

是的

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
