### ISSUE TITLE
regarding to tdengine upgrading in docker 

### ISSUE THREAD

**Issue by homeless2010** [taosdata/TDengine#16599]
1. 容器部署升级有教程或方案吗；
2. taosdump跨版本导入导出如何兼容

**Comment by yu285** [comment]
https://www.taosdata.com/engineering/10222.html

结合这个，几个关键步骤替换成 docker 操作 即可。

**Comment by yu285** [comment]
跨版本需要指明是从哪个版本到哪个版本

**Comment by homeless2010** [comment]
ok! 迭代3.0.0.0至3.0.0.1
