### ISSUE TITLE
Java Connector handle leaked

### ISSUE THREAD

**Issue by maoxz89** [taosdata/TDengine#16594]
client采用2.4.0.30 TDengine-client-2.4.0.30-Windows-x64.exe
java driver采用compile "com.taosdata.jdbc:taos-jdbcdriver:2.0.40"
![image](https://user-images.githubusercontent.com/106085619/188037125-a874e840-7960-486b-968e-cab6a7664017.png)
使用原生方式时程序有严重的句柄泄露
![BJUX_ Z51(76G6E8SGO17SF](https://user-images.githubusercontent.com/106085619/188037310-6a39161c-aa28-43e8-9cf1-51f34f9da244.png)
使用restful的方式时句柄数正常
![image](https://user-images.githubusercontent.com/106085619/188037386-cdaff706-f45a-4494-ab2b-4a9080360772.png)
数据库建表语句
create database if not exists iot5 keep 3650  days 10 update 2 cachelast 3 precision 'us';

create stable if not exists iot5.event
(
    `ts` TIMESTAMP,
    `id` BINARY(32),
    `deviceName` NCHAR(128)
)
tags
(
    `deviceId` bigint
    
);

附件为测试代码

[td.zip](https://github.com/taosdata/TDengine/files/9474178/td.zip)

**Comment by huolibo** [comment]
已复现此问题，但 windows 的句柄数增加 表示什么含义以及解决方式需要进一步研究。

**Comment by maoxz89** [comment]
不只winodws 在linux上应该也存在，句柄泄露数过多会导致应用程序访问不了

**Comment by huolibo** [comment]
linux 上的表现是什么呢？
