### ISSUE TITLE
是否支持类似Mysql中的字符串函数？

### ISSUE THREAD

**Issue by wlilaifeng** [taosdata/TDengine#166]
1.请问TDengine的Sql是否支持类似Mysql中的字符串函数，如substr等
2.请问查询超表数据时如何显示数据来自哪个子表作为一个字段显示，如：
select *,tablename from stable;

**Comment by hjxilinx** [comment]
1. 短期没有支持的计划，因为还有其他优先级较高的功能需要开发
2. 您的SQL语句是正确的。现在是这样，但是选择函数(min/max/top/bottom....)现在还不能支持归属到tags和超级表，例如：
select top(column_name, 10),tags_1,tags_2,tbname from stable;
我们后面会提供这方面的功能增强。

**Comment by ewsq** [comment]
谢意是还不支持针对于tags的查询？
