### ISSUE TITLE
golang demo reports an error with influxDB row protocol writing 

### ISSUE THREAD

**Issue by 506688994** [taosdata/TDengine#16616]
**golang官方demo,influxDB行写入报错**
golang调用TD客户端执行写入操作报错fatal error: unexpected signal during runtime execution

**Screenshots**
![image](https://user-images.githubusercontent.com/45871200/188080711-f8e59028-876c-49ae-86d1-94bc8114fe66.png)

**Environment (please complete the following information):**
 - OS: CentOS 7.9(openstack-Nova)
 - Memory:8G, CPU:Intel Xeon Processor (Icelake), current Disk Space:10G
 - TDengine Version 2.6.0.14

**Additional Context**

[taosServerLog.tar.gz](https://github.com/taosdata/TDengine/files/9475828/taosServerLog.tar.gz)
[taosClientLog.tar.gz](https://github.com/taosdata/TDengine/files/9475835/taosClientLog.tar.gz)

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
