### ISSUE TITLE
TDengine3.0  TSC ERROR time diff: 1661936090s is too big can lead to collapse!

### ISSUE THREAD

**Issue by whoamixl** [taosdata/TDengine#16623]
![55e04a2de80d246236f321e87bb66a4](https://user-images.githubusercontent.com/49057722/188098629-4247d806-f1bf-4677-bcb4-6584d1d2689b.png)
when execute " select count(*) from water_info where review_type=0"

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
