### ISSUE TITLE
执行sql抛出异常close statement error

### ISSUE THREAD

**Issue by banyin-lx** [taosdata/TDengine#16622]
框架mybatisplus,数据库连接池:druid
执行一条sql时抛出异常close statement error,打断点到
TSDBPreparedStatement这个类下的
![image](https://user-images.githubusercontent.com/55781767/188096449-9a47e3f0-ae60-47d2-8cd5-94169c5234da.png)
这个方法的parameters参数为null,请问这个是没有设置什么参数的原因嘛?

**Comment by huolibo** [comment]
只是哪个版本的 jdbc? 可以升级到 2.0.40

**Comment by banyin-lx** [comment]
> 只是哪个版本的 jdbc? 可以升级到 2.0.40

谢谢,用这个版本的可以了
