### ISSUE TITLE
Use interval function the deleted result is obtained

### ISSUE THREAD

**Issue by tuotuopz01** [taosdata/TDengine#16626]
version:3.0.0.1

issue:
1、DELETE FROM d0 where ts < '2017-07-14 02:44:00.000' ;
     Query OK
2、select * from  d0 where ts < '2017-07-14 02:44:00.000' ;
      Query OK, 0 rows in database 
3、but 
      select first(ts),last(ts),count(*),avg(current) from d10 interval(1m);
      result have ts < '2017-07-14 02:44:00.000' data！

**Comment by yu285** [comment]
could you provide the below information to us :

1. show create table d0 \G;

2. select * from d0 >> /xxx/d0.csv;

and provide us create-table SQL, and the data of this table .

**Comment by tuotuopz01** [comment]
> could you provide the below information to us :
> 
> 1. show create table d0 \G;
> 2. select * from d0 >> /xxx/d0.csv;
> 
> and provide us create-table SQL, and the data of this table .

Data generated with  taosBenchmark command

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
