### ISSUE TITLE
can't connect to db after exporting data from database 

### ISSUE THREAD

**Issue by sytpb** [taosdata/TDengine#16639]
Ver 2.4. 

![image](https://user-images.githubusercontent.com/12178686/188253124-6f826454-8a29-4023-9f10-3ba5c135ae7a.png)

![image](https://user-images.githubusercontent.com/12178686/188253200-c0bc2eaf-1f9d-4f77-a1e3-0251d3504b50.png)

restart service still now work .

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
