### ISSUE TITLE
“Task context not exist ” during access the TDengine in docker with REST

### ISSUE THREAD

**Issue by happyhym** [taosdata/TDengine#16635]
**Bug Description**
通过http以REST方式访问docker容器中的tdengine时，执行类似如下语句：select last_row(ts,tension) from hwidb.hwidata where ts>=now-10d and ts<=now interval(1s) order by ts asc limit 7200，偶尔会出现如下错误：
Get/Release pages:0/0, flushToDisk:0.00 Kb (0 Pages), loadFromDisk:0.00 Kb (0 Pages), avgPageSize:-nan Kb
Paged buffer closed, total:0.00 Kb (0 Pages), inmem size:0.00 Kb (0 Pages), file size:0.00 Kb, page size:4.00 Kb, sortComparInit
Get/Release pages:0/0, flushToDisk:0.00 Kb (0 Pages), loadFromDisk:0.00 Kb (0 Pages), avgPageSize:-nan Kb
09/02 20:58:25.177166 00000063 **QRY ERROR QID:0xe6b01947b43c3e02,TID:0x14ea,EID:0 end to handle event at phase PRE_QUERY, code:Task context not exist
09/02 20:58:25.412523 00000069 QRY ERROR QID:0xe6b01947b04d3df7,TID:0x14db,EID:0 end to handle event at phase PRE_QUERY, code:Task context not exist
09/02 20:58:25.941496 00000065 QRY ERROR QID:0xe6b01947b04f3df9,TID:0x14de,EID:0 end to handle event at phase PRE_QUERY, code:Task context not exist**
出现上述错误后，查询无数据返回。

**Screenshots**
![image](https://user-images.githubusercontent.com/7564341/188157306-c38bdc2a-cd5a-4595-a525-55c0740ebb2d.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS
 - docker version: 20.10.12
 - Memory, CPU, current Disk Space
    Intel(R) Core(TM) i3-3227U CPU @ 1.90GHz
    MemTotal:        1847612 kB, MemFree:          106432 kB
 - Filesystem      Size  Used Avail Use% Mounted on
    /dev/sda4     98G   38G   56G   41%   /
 - TDengine Version: 3.0.0.1

**Comment by nasservb** [comment]
I have the same problem, when the server work for a day the CPU of the server is going to %200 in docker stats.
when I execute the query like : 
`sql 
show tables; `
or 
`sql 
select count(*) from aSuperTable; `
the server is not responded for a long time (10 min) and the query is timeout.
after restarting the server in docker-compose or deleting pod in k8s it's work fine, but it cause I restart server every day.
when that problem is ocured the light-weight query like insert and 
`sql 
show stables; ` or `sql show vgroups` or `sql show dnodes` are work fine;

**Comment by yu285** [comment]
The bugs in earlier versions of 3.0 have been fixed, but 3.0.2.5 May not be compatible with the current version (3.3.0.0), so it is not possible to upgrade directly. Therefore, it is recommended to redeploy the latest 3.3.0.0, the subsequent upgrade will be very convenient, directly install the latest version of the software.

Range of open source version of the operating system support: https://docs.taosdata.com/reference/support-platform/
The bugs from earlier versions of 3.0 have been fixed, but 3.0.2.5 May not be compatible with the current version (3.3.0.0), so it is not possible to upgrade directly. Therefore, it is recommended to redeploy the latest 3.3.0.0, the subsequent upgrade is very convenient, directly install the latest version of the software.

Range of open source version of the operating system support: https://docs.taosdata.com/reference/support-platform/
