### ISSUE TITLE
Super table couldn't be imported by  csv ?

### ISSUE THREAD

**Issue by sytpb** [taosdata/TDengine#16642]
备份数据把超级表的数据导出到了csv, 然后数据库删了，新建数据库后，导入提示

taos> insert into orders file '/root/qwx/trace-back/qwx-trace-back/taurus.orders.csv';

DB error: invalid operation: insert data into super table is not supported (0.000870s)

这才知道只能导出，不能导入，从超级表。

文档里也没有说明，本以为能导出，肯定能导入。

这情况，不知道这情况怎么弄

**Comment by yu285** [comment]
这个情况没有什么太好的办法。。除非对自己的 csv 梳理出逻辑，还原成每个子表的csv。
