### ISSUE TITLE
<`> supporting in INSERT INTO but not work in multipy insert into and select clause. 

### ISSUE THREAD

**Issue by sytpb** [taosdata/TDengine#16640]
![04064442fd96f79eac305f84c9073a2](https://user-images.githubusercontent.com/12178686/188253468-472b1320-f1fd-4eef-9754-4bd8a2dc4b05.png)

![28ec3caf6c3209747b74bd1182d86be](https://user-images.githubusercontent.com/12178686/188253470-d7215031-94a6-4013-98a7-462b4c15b57c.png)

虽然表创建支持了<`>,  但是在多表插入，还有查询等语义解释都没有支持，不知道3.0有没有支持，问题复现在 V2.4

**Comment by yu285** [comment]
已经优化完了。

另外 2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
