### ISSUE TITLE
3.0.0.1 restful query issue

### ISSUE THREAD

**Issue by cfjy** [taosdata/TDengine#16659]
**Bug Description**
相同语句使用restful查询在2.6.0版本正常，但是在3.0版本存在时区问题，和时间格式问题，数据库设置时区是Asia/Shanghai (CST, +0800)，在服务器本地查询正常，但是restful远程查询少了8个小时（restful无法指定时区），而且时间的毫秒数，存在缺少小数位的情况，比如如果是2022-09-09 10:31:28.600，就会略掉最后两位，成为这个样子"2022-09-09T10:31:28.6Z"，

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [3.0.0.1]

**Additional Context**

**Comment by sangshuduo** [comment]
@cfjy  后续版本会支持按数据库时间精度补齐

**Comment by yu285** [comment]
3.0早期问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
