### ISSUE TITLE
3.0 version startup failed

### ISSUE THREAD

**Issue by gisakuya** [taosdata/TDengine#16655]
windows版本，启动服务失败。
前端时间运行着，会突然崩溃退出程序，但重新运行就好了。
今天崩溃退出后，重启程序也打不开。报下图错误：

![image](https://user-images.githubusercontent.com/12749301/188346161-8e41dd0a-52ba-4c65-a525-4e1f7bae0890.png)

**Comment by gisakuya** [comment]
原来是进程里的程序没有退出。杀掉就好了。但运行一段时间就会崩溃退出这个问题，不知道是不是只在window上出现。

**Comment by yu285** [comment]
windows 早期问题较多，开源版维护不过来，回收到到企业版重做了。 所以windows版本到了 3.0.7.1 之后就没法再升级了，也没有维护团队支持。所以咱们还是换到 linux 版本再使用，目前最新版为 3.2.3.0。

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
