### ISSUE TITLE
super table query issue

### ISSUE THREAD

**Issue by XHXHXHX** [taosdata/TDengine#16657]
sql1:  查询不到数据
 SELECT * FROM device_running_status WHERE node_3rd_id in ('AAA')

sql2: 查询有数据
SELECT * FROM device_running_status_AAA 

目前只有AAA的数据有异常，换成BBB sql1也能正常查询

DESCRIBE device_running_status:
{ "res": true, "count": 3, "data": [ { "Field": "id", "Type": "TIMESTAMP", "Length": 8, "Note": "" }, { "Field": "value_int", "Type": "INT", "Length": 4, "Note": "" }, { "Field": "node_3rd_id", "Type": "BINARY", "Length": 64, "Note": "TAG" } ] }

**Comment by yu285** [comment]
版本号是
