### ISSUE TITLE
tdengine3.0.0.1 crashed in docker 

### ISSUE THREAD

**Issue by homeless2010** [taosdata/TDengine#16666]
tdengine3.0.0.1单节点容器运行中崩溃：

日志：
09/05 02:26:34.657700 00000047 VND vgId:2, commit-cb is excuted, fsm:0x7f189412d550, index:28122, term:3, msg-index:28122, weak:0, code:0, state:102 leader, type:submit
09/05 02:26:34.657704 00000047 WAL vgId:2, wal start to read index:28123
09/05 02:26:34.657707 00000102 VND vgId:2, submit success, index:28121
09/05 02:26:34.657709 00000102 VND vgId:2, start to process write request submit, index:28122
09/05 02:26:34.657721 00000102 VND vgId:2, submit success, index:28122
09/05 02:26:34.657722 00000047 WAL vgId:2, wal version reset from index:28123(invalid:1) to index:28123
09/05 02:26:34.657731 00000047 VND vgId:2, commit-cb is excuted, fsm:0x7f189412d550, index:28123, term:3, msg-index:28123, weak:0, code:0, state:102 leader, type:submit
09/05 02:26:34.657739 00000047 WAL vgId:2, wal start to read index:28124
09/05 02:26:34.657751 00000080 VND ERROR vgId:3, msg:0x7f184c005630 failed to process since not leader, gtid:0x0:0x43e02f788ea30007
09/05 02:26:34.657758 00000080 VND ERROR vgId:3, msg:0x7f184c005630 failed to propose since Database not ready, code:0x80000014, gtid:0x0:0x43e02f788ea30007
09/05 02:26:34.657758 00000047 WAL vgId:2, wal version reset from index:28124(invalid:1) to index:28124
09/05 02:26:34.657758 00000104 VND ERROR vgId:4, msg:0x7f18580051b0 failed to process since not leader, gtid:0x0:0x43e02f788ea30008
09/05 02:26:34.657768 00000047 VND vgId:2, commit-cb is excuted, fsm:0x7f189412d550, index:28124, term:3, msg-index:28124, weak:0, code:0, state:102 leader, type:submit
09/05 02:26:34.657770 00000104 VND ERROR vgId:4, msg:0x7f18580051b0 failed to propose since Database not ready, code:0x80000014, gtid:0x0:0x43e02f788ea30008
09/05 02:26:34.657773 00000102 VND vgId:2, start to process write request submit, index:28123
09/05 02:26:34.657773 00000047 WAL vgId:2, wal start to read index:28125
09/05 02:26:34.657785 00000100 VND ERROR vgId:2, msg:0x7f184c0056f0 failed to process since not leader, gtid:0x0:0x43e02f788ea30006
09/05 02:26:34.657789 00000100 VND ERROR vgId:2, msg:0x7f184c0056f0 failed to propose since Database not ready, code:0x80000014, gtid:0x0:0x43e02f788ea30006
09/05 02:26:34.657791 00000102 VND vgId:2, submit success, index:28123
09/05 02:26:34.657793 00000102 VND vgId:2, start to process write request submit, index:28124
09/05 02:26:34.657795 00000047 WAL vgId:2, wal version reset from index:28125(invalid:1) to index:28125
09/05 02:26:34.657804 00000047 VND vgId:2, commit-cb is excuted, fsm:0x7f189412d550, index:28125, term:3, msg-index:28125, weak:0, code:0, state:102 leader, type:submit
09/05 02:26:34.657805 00000102 VND vgId:2, submit success, index:28124
09/05 02:26:34.657811 00000102 VND vgId:2, start to process write request submit, index:28125
09/05 02:26:34.657812 00000047 WAL vgId:2, wal start to read index:28126
09/05 02:26:34.657823 00000102 VND vgId:2, submit success, index:28125
09/05 02:26:34.657830 00000047 WAL vgId:2, wal version reset from index:28126(invalid:1) to index:28126
09/05 02:26:34.657838 00000047 VND vgId:2, commit-cb is excuted, fsm:0x7f189412d550, index:28126, term:3, msg-index:28126, weak:0, code:0, state:102 leader, type:submit
09/05 02:26:34.657848 00000047 WAL vgId:2, wal start to read index:28127
09/05 02:26:34.657853 00000102 VND vgId:2, start to process write request submit, index:28126
09/05 02:26:34.657867 00000047 WAL vgId:2, wal version reset from index:28127(invalid:1) to index:28127

**Comment by yu285** [comment]
可以清掉数据后，重新部署下 3.0.1.0 ，底层有改动。
