### ISSUE TITLE
tdengine-alert start failed 

### ISSUE THREAD

**Issue by r0pzzz** [taosdata/TDengine#16661]
配置文件
{
        "port": 8100,
        "database": "file:alert.db",
        "tdengine": "root:taosdata@/tcp(127.0.0.1:0)/",
        "log": {
                "level": "production",
                "path": "alert.log"
        },
        "receivers": {
                "alertManager": "http://127.0.0.1:9093/api/v1/alerts",
                "console": true
        }
}
环境：centos7

**Comment by yu285** [comment]
tdengine-alert 已经不再维护了，可以参考下文档，或者在微信群和其他用户交流下吧。

可以加微信 15652223354 做具体沟通
