### ISSUE TITLE
 Client and server's time is not synchronized

### ISSUE THREAD

**Issue by wanjwsuper** [taosdata/TDengine#16679]
**Bug Description**

origin/3.0 源码编译，安装
单节点，服务端启动，taos可以进入，windows客户端taos启动连接时，提示
Welcome to the TDengine Command Line Interface, Client Version:3.0.0.1
Copyright (c) 2022 by TDengine, all rights reserved.

failed to connect to server, reason: Client and server's time is not synchronized

客户端和服务端时间不同步
服务端 centos7
timedatectl set-timezone "Asia/Shanghai"
ntpdate -u time.windows.com

windows 10 
"设置"--“日期与时间”--“(UTC+08:00) 北京，重庆，香港特别行政区，乌鲁木齐”--时钟与“time.windows.com”同步

设置之后，还是显示上面连不上，原因：客户端和服务端时间不同步

**Comment by wanjwsuper** [comment]
官网的文档里面下载的3.0.0.1和客户端3.0.0.1是可以连，但是源码编译的origin/3.0和官网下载的客户端3.0.0.1连不上

**Comment by RuiZhang-cn** [comment]
我也遇到了 ，我的问题是升级到3.0之后 JDBC连接数据库报错: JNI ERROR (2354): Client and server's time is not synchronized,
数据库服务器和本地都同步了windows的时间服务器,时区都是上海,配置文件也加了&timezone=UTC-8

**Comment by keychenn** [comment]
我也碰到了同样的问题。centos8.2 “timedatectl set-timezone "Asia/Shanghai" ntpdate -u time.windows.com”，win10连不上。

**Comment by yu285** [comment]
请确保客户端和服务端 版本一致

**Comment by jiyutr** [comment]
我的也是，win10的客户端连不上   提示Client and server's time is not synchronized   Linux 的客户端能连上    服务端是另一台Linux

**Comment by RuiZhang-cn** [comment]
> 3.0.0.1



> 请确保客户端和服务端 版本一致
版本如下：

Welcome to the TDengine Command Line Interface, Client Version:3.0.0.1

 <dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>3.0.0</version>
        </dependency>

**Comment by wanjwsuper** [comment]
下载新版本服务端taosd和新版本客户端taoc吧，客户端版本和服务端版本要求一致，如果是源码编译出来的，要是同一份源码编译出来的服务端和客户端

**Comment by jiyutr** [comment]
客户端Windows 安装包用的是[TDengine-client-3.0.1.0-Windows-x64.exe] 服务端Linux  安装包用的是[TDengine-server-3.0.1.0-Linux-x64.tar.gz]  版本都是3.0.1.0

**Comment by RuiZhang-cn** [comment]
windows本地和远程linux的版本必须一致

**Comment by JesseLivingston** [comment]
我在 mac 上用 k8s 部署集群， 转发 6030 端口后， 使用 taos 连接也是同样的错误， 看起来应该是 TDengine/source/libs/function/src/udfd.c 里 423 行附近抛出来的异常， mac 和一个 linux 容器里的时间差别超过 900 毫秒应该很正常， 估计只能使容器和宿主机的时间服务器保持一致了。

**Comment by JesseLivingston** [comment]
mac 上用 k8s 启个集群后， 在宿主机上连接 pod 里的服务也有同样的问题。
查了一下容器和宿主机的日期时间
`
(python3.9) ➜  TDEnginePlayground kubectl exec -i -t tdengine-0 -- date -R
Sun, 08 Jan 2023 17:45:29 +0800
(python3.9) ➜  TDEnginePlayground date -R
Mon, 09 Jan 2023 04:44:33 +0800
`
这结果就离谱， 容器中的时间滞后宿主机 11 个小时， 这似乎应该是容器 (ubuntu 18.04) 用的时间服务器就有问题。

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
