### ISSUE TITLE
V3.0  TIMETRUNCATE  with 1d return unexpected result

### ISSUE THREAD

**Issue by gisakuya** [taosdata/TDengine#16683]
3.0版本，TIMETRUNCATE 结合1d使用，返回的数据里多了8小时
![image](https://user-images.githubusercontent.com/12749301/188563490-d51c75cc-0fd5-4de3-92ed-bdf05d4533d9.png)

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
