### ISSUE TITLE
V3.0 timestamp add 1n return wrong time

### ISSUE THREAD

**Issue by gisakuya** [taosdata/TDengine#16691]
3.0版本，执行：select timestamp '2022-1-29 12:12:12'+1n ;  返回：1601-06-12 20:32:23.000
![image](https://user-images.githubusercontent.com/12749301/188597977-6ee542ec-435c-49c6-b368-430b604134e2.png)

**Comment by yu285** [comment]
we will check on this

**Comment by yu285** [comment]
taos> select timestamp '2022-1-29 12:12:12'+1n ; 
 timestamp '2022-1-29 12:12:12'+1n |
====================================
 2022-02-28 12:12:12.000 |
Query OK, 1 row(s) in set (0.053715s)

3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
