### ISSUE TITLE
c# influxdb行协议示例代码写入失败

### ISSUE THREAD

**Issue by jiangzhuangxiansheng** [taosdata/TDengine#16694]
**Bug Description**
服务器:centos7
客户端：windows10
版本:3.0.0.1
问题:influx行协议写入失败

超级表： CREATE STABLE meters (ts timestamp, current float, voltage int, phase float) TAGS (location binary(64), groupId int);
操作代码:
![image](https://user-images.githubusercontent.com/33273148/188601843-9d2c0f87-ea64-4875-9e21-3c7ddf489fea.png)

运行结果：
Invalid value in client

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by xleili** [comment]
我尝试复现你的问题，还没能复现。
请问，通过windows上的客户端，可以正常写入或者查询Linux server端吗。有尝试过别的schemaless 协议吗

**Comment by jiangzhuangxiansheng** [comment]
我用taos shell 使用sql是可以正常写入，其他schemaless 协议没有试过，那我后续在排查下是哪里的问题

**Comment by jvmx** [comment]
I can confirm this bug exists when I run the same test with the C# client (TDengine.Connector 3.0.1). OS: Windows 11 (both client and server). Throws a "Schemaless Insert failed since Invalid value in client" exception.

**Comment by xleili** [comment]
> I can confirm this bug still exists when I run the same test with the C# client (TDengine.Connector 3.0.1). OS: Windows 11 (both client and server). Throws a "Schemaless Insert failed since Invalid value in client" exception. Tried using .NET 6. This is a pretty show-stopper bug for my TDEngine use unfortunately (can't insert data, at all) - any fix would be greatly appreciated.\
> 
> Installs were:
> 
> * TDengine-server-3.0.1.4-Windows-x64
> * TDengine-client-3.0.1.4-Windows-x64
> 
> OS: Windows 11 (client and server) Library: TDengine.Connector 3.0.1 Language: C# Version: .NET 6

I haven't the test these on Windows 11, I will test and check. If this bug exists, we will fix this.
