### ISSUE TITLE
V2.6 rest api response missing 'code' attribute

### ISSUE THREAD

**Issue by littlered-zz** [taosdata/TDengine#16692]
server version: 2.6.0.14, 2.6.0.16

test case:
curl -u root:taosdata http://<ip_addr>:6041/rest/sql -d "select server_version()"                                 
{"status":"succ","head":["server_version()"],"column_meta":[["server_version()",8,8]],"data":[["2.6.0.16"]],"rows":1}

**python restclient expects code in resp, otherwise throw the "KeyError: 'code'"**

reference: restclient.py line 115
        resp = json.load(response)
        if resp["code"] != 0:
            raise ExecutionError(resp["desc"], resp["code"])

**Comment by sangshuduo** [comment]
2.6 和 3.0 REST API 是不兼容的

**Comment by littlered-zz** [comment]
那taospy兼容2.6版本api的应该是哪个版本？

> 2.6 和 3.0 REST API 是不兼容的

**Comment by sangshuduo** [comment]
> 那taospy兼容2.6版本api的应该是哪个版本？
> 
> > 2.6 和 3.0 REST API 是不兼容的

python3.7 之上最新版本就可以 pip3 install -U taospy

**Comment by littlered-zz** [comment]
pass in taospy 2.6.3
