### ISSUE TITLE
abort has been called

### ISSUE THREAD

**Issue by prefermall** [taosdata/TDengine#16702]
window10系统，TDEnige3.0.0.1
先建立超级表，然后建立1000个子表，用jdbc写入1000万数据，然后再删除1000万数据，关闭taosd.exe程序，再次打开taosd.exe，出现如下

![image](https://user-images.githubusercontent.com/12678289/188678331-b03984c4-d712-4a65-b2ff-69f648628fd2.png)

**Comment by yu285** [comment]
windows 早期问题较多，开源版维护不过来，回收到到企业版重做了。 所以windows版本到了 3.0.7.1 之后就没法再升级了，也没有维护团队支持。所以咱们还是换到 linux 版本再使用，目前最新版为 3.2.3.0。

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
