### ISSUE TITLE
2.X upgrade to 3.X start filed

### ISSUE THREAD

**Issue by Luokun2016** [taosdata/TDengine#16720]
**Fail log**
/07 15:00:18.634310 00025938 DND ERROR The default data directory /var/lib/taos contains old data of tdengine 2.x, please clear it before running! 
09/07 15:00:18.634348 00025938 DND ERROR failed to init dnode since Config not found

Is there any way to keep the 2.x version data?

**Comment by skyformat99** [comment]
哈哈，数据格式不同；2.x删了吧
参考这个#16449

**Comment by Luokun2016** [comment]
> 哈哈，数据格式不同；2.x删了吧 参考这个#16449

删了确实能起来，只能删除原来的了
