### ISSUE TITLE
TSDBPreparedStatement issue

### ISSUE THREAD

**Issue by pujian1984** [taosdata/TDengine#16731]
StringBuilder sb = new StringBuilder("SELECT utc, mbid, cbjd, cbwd, cbsd, course, csx, rot,fusion_type ");
	        sb.append("from ?");
	        sb.append(" where utc > ? and utc < ? order by utc desc");
	        TSDBPreparedStatement pstmt = (TSDBPreparedStatement) conn.prepareStatement(sb.toString()).unwrap(TSDBPreparedStatement.class);
	        pstmt.setTableName("t_0_" + mmsi);
	        pstmt.setTimestamp(1, new java.sql.Timestamp(startUtc));
	        pstmt.setTimestamp(2, new java.sql.Timestamp(endUtc));
	        ResultSet resultSet = pstmt.executeQuery();

以上代码会将第一个Timestamp参数放在表名的参数位置
另外你们的官方文档写的设置参数从0开始，但是实际是从1开始的
![微信截图_20220907221435](https://user-images.githubusercontent.com/35865181/188901247-e0ede6a3-f57f-494b-92ac-a21dcff6a1ca.png)

		<dependency>
		  <groupId>com.taosdata.jdbc</groupId>
		  <artifactId>taos-jdbcdriver</artifactId>
		  <version>3.0.0</version>
		</dependency>

**Comment by pujian1984** [comment]
另外我想咨询一下，预编译对动态表名是否有价值？

**Comment by huolibo** [comment]
丛 0 开始的，具体可参考：[TSDBPreparedStatementTest#executeTest](https://github.com/taosdata/taos-connector-jdbc/blob/b0009c310942d8db3710f3d05819e4f39296e055/src/test/java/com/taosdata/jdbc/TSDBPreparedStatementTest.java#L303)

预编译对 insert 可以批量做插入，加快插入速度。
