### ISSUE TITLE
docker container corrupted. container logs as below.

### ISSUE THREAD

**Issue by wxmeng04** [taosdata/TDengine#16742]
09/08 03:10:18.790889 00000053 VND vgId:4, commit-cb is excuted, fsm:0x7f5048127410, index:1297597, term:2, msg-index:1297597, weak:0, code:0, state:102 leader, type:submit

09/08 03:10:18.791058 00000053 VND vgId:4, commit-cb is excuted, fsm:0x7f5048127410, index:1297598, term:2, msg-index:1297598, weak:0, code:0, state:102 leader, type:submit

09/08 03:10:18.791177 00000053 VND vgId:4, commit-cb is excuted, fsm:0x7f5048127410, index:1297603, term:6, msg-index:1297603, weak:0, code:0, state:102 leader, type:submit

09/08 03:10:18.791243 00000053 VND vgId:4, commit-cb is excuted, fsm:0x7f5048127410, index:1297606, term:8, msg-index:1297606, weak:0, code:0, state:102 leader, type:submit

09/08 03:10:18.791291 00000053 VND vgId:4, commit-cb is excuted, fsm:0x7f5048127410, index:1297608, term:9, msg-index:1297608, weak:0, code:0, state:102 leader, type:submit

09/08 03:10:18.791319 00000053 VND vgId:4, commit-cb is excuted, fsm:0x7f5048127410, index:1297609, term:9, msg-index:1297609, weak:0, code:0, state:102 leader, type:submit

Segmentation fault (core dumped)

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
