### ISSUE TITLE
response of jdbc demo is different from curl

### ISSUE THREAD

**Issue by lhyundeadsoul** [taosdata/TDengine#16747]
**Bug Description**
branch 3.0

execute `com.taos.example.RestQueryExample` 

response:
```
avg(voltage)	location	
null	null	
null	null
```

**To Reproduce**

0. docker run -d -p 6030:6030 -p 6041:6041 -p 6043-6049:6043-6049 -p 6043-6049:6043-6049/udp tdengine/tdengine
1. check out branch 3.0
2. execute `com.taos.example.RestInsertExample`  to insert data
3. execute `com.taos.example.RestQueryExample`  

**Expected Behavior**
According to the doc:https://docs.tdengine.com/develop/query-data/
// possible output:
// avg(voltage) location
// 222.0    California.LosAngeles
// 219.0    California.SanFrancisco

**Screenshots**
Actually, I got
![image](https://user-images.githubusercontent.com/5850103/189059719-cd1ea737-440f-4136-8f8e-e57840cbcad8.png)

**Environment (please complete the following information):**
 - OS: MacBook Pro (16-inch, 2019)  macOS 10.15.7 (19H2
 - Memory, CPU, current Disk Space    16 GB 2667 MHz DDR4   2.6 GHz 六核Intel Core i7
 - TDengine Version [3.0]

**Additional Context**
when I execute
`curl -L -H "Authorization: Basic cm9vdDp0YW9zZGF0YQ==" \
  -d "SELECT AVG(voltage) FROM meters GROUP BY location;" \
  localhost:6041/rest/sql/power | jq`

I got 
``` json
{
  "status": "succ",
  "head": [
    "avg(voltage)",
    "location"
  ],
  "column_meta": [
    [
      "avg(voltage)",
      7,
      8
    ],
    [
      "location",
      8,
      64
    ]
  ],
  "data": [
    [
      222,
      "California.LosAngeles"
    ],
    [
      219,
      "California.SanFrancisco"
    ]
  ],
  "rows": 2
}
```

**Comment by sangshuduo** [comment]
the root cause is to use a 3.0 JDBC connector to access a Docker container runs TDengine 2.x
