### ISSUE TITLE
How to sort results in ascending or descending order in PARTITION BY clause

### ISSUE THREAD

**Issue by tocatss** [taosdata/TDengine#16745]
**General Questions**

经查文档已知 ORDER BY + LIMIT 输出的是对整个结果集排序后的结果，
请问有无将 ORDER BY 语句作用在分表的办法，比如每个分别获取最新的N条数据？

PS: influxdb应该是支持该类查询的

**Comment by tocatss** [comment]
## 期望每个host显示1个（符合预期）
<img width="364" alt="捕获9" src="https://user-images.githubusercontent.com/25919809/197674717-90e74a15-8c0f-49b0-b625-8b2ac62bff93.PNG">

## 期望每个host显示最新的1个（不符合预期）
<img width="448" alt="捕获10" src="https://user-images.githubusercontent.com/25919809/197675030-d541f269-ef31-450e-a3d8-24ca7d5a123f.PNG">

需要更多细节可以联系wx：spptbb

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/

**Comment by niufwshd** [comment]
3.3.0.3 依然不支持此功能
