### ISSUE TITLE
memory keep increasing during  querying operation 

### ISSUE THREAD

**Issue by sanliang125** [taosdata/TDengine#16762]
**Bug Description**
在集群环境下，我对tdengine进行查询操作，内存占用持续增加。
使用的sql语句如下：
`select * from meters where groupid = 1000  limit 1000`

**Expected Behavior**
我在数据库中插入了2亿条数据后，使用jmeter测试工具模拟用户调用JAVA api接口对数据进行查询，并发数为8，每秒进行一次select查询。
开始查询任务后，发现集群中的一个节点内存持续升高，每秒升高0.2%左右，并且无下降趋势。

**Screenshots**
![image](https://user-images.githubusercontent.com/29949952/189250773-840bffb6-7e65-409d-9e30-79ec6f32e11c.png)
![image](https://user-images.githubusercontent.com/29949952/189250788-a58598d9-667a-419a-a5ac-19dc059d63bd.png)

**Environment **
 - CentOS 7.0
 - 4H8G，50G ssd
 - TDengine Version：3.0.0.1

**Comment by yu285** [comment]
可以用 jemalloc 方式编译出来再看看是否有同样现象。

**Comment by johnnylc** [comment]
3.0.1.1问题仍然存在，内存持续增长

**Comment by 651016236** [comment]
> 这东西内存占用就离谱

确实，我打算用postgresql那个时序库了，这个东西太不稳定， 内存一直增长，我连查询都没查询   只是插入数据，3天从1G增长到11G。。。。只能重启解决

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
