### ISSUE TITLE
docker config path is empty?

### ISSUE THREAD

**Issue by qq1461607240** [taosdata/TDengine#16761]
**Bug Description**
使用docker安装 最新版 挂载配置文件路径时候 发现docker容器内的文件夹是空的 所以导致挂载的目录也是空的

**To Reproduce**
docker执行以下命令
docker pull tdengine/tdengine

docker run -d --name tdengine -e TAOS_FQDN=tdengine -v  /tdengine/taos/log:/var/log/taos -v  /tdengine/taos/config:/etc/taos/taos.cfg -v  /tdengine/taos/data:/var/lib/taos -p 6030-6049:6030-6049 -p 6030-6049:6030-6049/udp tdengine/tdengine

**Expected Behavior**
发现挂载的config目录文件夹内容为空，去容器查看依旧为空下面是截图
![0bdc14c6932cfa071c3eafe02fc2df7](https://user-images.githubusercontent.com/76995270/189250500-0f0015a3-97af-4060-9999-2632aa40b3ce.jpg)
![11fb905c2cc9ae2f2de005be3e353b0](https://user-images.githubusercontent.com/76995270/189250508-78e1ae4c-47c3-4e80-b49c-eefc6b39c3ae.jpg)
![9ca9ed603ff9fdf063e338fe35bd4ae](https://user-images.githubusercontent.com/76995270/189250518-91236024-e325-462c-ae79-707495ff38be.jpg)

![f69cce8da00eb477cc9dc823599e73a](https://user-images.githubusercontent.com/76995270/189250525-66aa1c0a-6c2d-4770-ade2-68191359fab8.jpg)

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by yu285** [comment]
![image](https://user-images.githubusercontent.com/74105241/189257438-a1265f00-d6e7-49ef-9345-3a35bae76cf0.png)

I can see it
