### ISSUE TITLE
Conn is broken and DB error: Database not ready.

### ISSUE THREAD

**Issue by alanchb** [taosdata/TDengine#16776]
Centos虚机安装了3.0.0.1，创建了超级表，在向子表插入数据的过程中，在另一进程发起子表查询（都是python接口操作），造成两边都异常退出。难道不支持写数据的时候发起查询？
之后再通过python接口发起子表查询，报Conn is broken。通过linux client发起子表查询，报Database not ready，在client端show tables能正常返回子表。重启taosd服务或重启虚机都不管用。

请问该如何解决？谢谢

**Comment by yu285** [comment]
show dnodes;
show mnodes;
show 库名.vgroups

截图发下
