### ISSUE TITLE
tdengine 3.0.1.0 select * from subtable not return tag field value

### ISSUE THREAD

**Issue by xukongyang** [taosdata/TDengine#16770]
**Bug Description**
tdengine 3.0.1.0 select * from subtable not return tag field value

**To Reproduce**
1. supertable have tag field
2. subtable create from supertable and set tag field value
3. select * from subtable not return tag field value
4. but select * from supertable return tag field value
5. test with example data meters supertable and my example supertable have same problem.

**Expected Behavior**
select * from subtable should return tag field value.

**Screenshots**

**Environment (please complete the following information):**
 - OS: ubuntu 20.04.5
 - Memory, CPU, current Disk Space
 - TDengine Version [3.0.1.0]

**Additional Context**
Add any other 
![微信图片_20220910093333-tdengine](https://user-images.githubusercontent.com/4610225/189463841-9be3698c-e545-4496-9822-f7cb2abfe515.jpg)
context about the problem here.

**Comment by xukongyang** [comment]
![微信图片_20220910094648-t2](https://user-images.githubusercontent.com/4610225/189464259-4470d4f8-653e-4bba-a3d8-c3e588080b37.jpg)

**Comment by yu285** [comment]
我们确认下

**Comment by yu285** [comment]
> ![微信图片_20220910094648-t2](https://user-images.githubusercontent.com/4610225/189464259-4470d4f8-653e-4bba-a3d8-c3e588080b37.jpg)

这里是文档有误，我们修改下

**Comment by xukongyang** [comment]
好的。
