### ISSUE TITLE
too many redirects, quit (2.4.0.14)

### ISSUE THREAD

**Issue by kevinwumg** [taosdata/TDengine#16786]
09/13 09:14:31.913473 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b265dc, too many redirects, quit
09/13 09:14:32.118598 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x2745b3b, too many redirects, quit
09/13 09:14:32.229401 00012261 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:32.403609 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae96f5, too many redirects, quit
09/13 09:14:32.688571 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x2743e16, too many redirects, quit
09/13 09:14:32.993568 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b144d5, too many redirects, quit
09/13 09:14:32.998467 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b26508, too many redirects, quit
09/13 09:14:33.255476 00124658 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:33.648692 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1af6ccd, too many redirects, quit
09/13 09:14:33.911710 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae983e, too many redirects, quit
09/13 09:14:33.968641 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae99f2, too many redirects, quit
09/13 09:14:34.218531 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x274581a, too many redirects, quit
09/13 09:14:34.229167 00124658 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:34.353588 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b15453, too many redirects, quit
09/13 09:14:34.558590 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x274734d, too many redirects, quit
09/13 09:14:35.259341 00012261 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:35.748541 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b25a76, too many redirects, quit
09/13 09:14:35.788685 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b24016, too many redirects, quit
09/13 09:14:36.093523 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae9e2d, too many redirects, quit
09/13 09:14:36.229267 00012261 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:36.269087 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b154c5, too many redirects, quit
09/13 09:14:36.813873 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x2745843, too many redirects, quit
09/13 09:14:36.948679 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b240d2, too many redirects, quit
09/13 09:14:37.249261 00012261 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:37.314141 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b14d67, too many redirects, quit
09/13 09:14:38.193515 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b154cc, too many redirects, quit
09/13 09:14:38.269452 00012261 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:38.448538 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x27473c0, too many redirects, quit
09/13 09:14:38.468509 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b13f84, too many redirects, quit
09/13 09:14:38.528554 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae983e, too many redirects, quit
09/13 09:14:38.829042 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1af6f9c, too many redirects, quit
09/13 09:14:39.103633 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x2745222, too many redirects, quit
09/13 09:14:39.118511 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b144e3, too many redirects, quit
09/13 09:14:39.239483 00012261 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:40.013636 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b13f7e, too many redirects, quit
09/13 09:14:40.264775 00014933 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:40.293452 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b144ca, too many redirects, quit
09/13 09:14:40.303495 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae5852, too many redirects, quit
09/13 09:14:40.363606 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b25a76, too many redirects, quit
09/13 09:14:40.648694 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1af6c1e, too many redirects, quit
09/13 09:14:40.673524 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1af6fca, too many redirects, quit
09/13 09:14:41.058552 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b14d6d, too many redirects, quit
09/13 09:14:41.234169 00124658 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:41.563496 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1af6dc7, too many redirects, quit
09/13 09:14:41.828591 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae8f95, too many redirects, quit
09/13 09:14:42.148614 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b25746, too many redirects, quit
09/13 09:14:42.218597 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b13ded, too many redirects, quit
09/13 09:14:42.259742 00014933 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:42.743579 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b1538c, too many redirects, quit
09/13 09:14:43.229274 00014933 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:43.819417 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b25767, too many redirects, quit
09/13 09:14:43.988945 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b240d2, too many redirects, quit
09/13 09:14:44.255523 00124367 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:44.558457 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1af6d23, too many redirects, quit
09/13 09:14:44.718693 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b2458a, too many redirects, quit
09/13 09:14:45.274411 00012274 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:45.757119 00124367 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:46.208604 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x2745b73, too many redirects, quit
09/13 09:14:46.529061 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae8fa1, too many redirects, quit
09/13 09:14:46.729156 00124367 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:47.749049 00124367 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:47.758851 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b145a5, too many redirects, quit
09/13 09:14:48.393877 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x2744a66, too many redirects, quit
09/13 09:14:48.538611 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae74cd, too many redirects, quit
09/13 09:14:48.543480 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b13db7, too many redirects, quit
09/13 09:14:48.588725 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b144e9, too many redirects, quit
09/13 09:14:48.593616 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b23fe2, too many redirects, quit
09/13 09:14:48.603595 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b240d2, too many redirects, quit
09/13 09:14:48.753598 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x2745da8, too many redirects, quit
09/13 09:14:48.774275 00124367 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:48.848473 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae80a9, too many redirects, quit
09/13 09:14:48.873512 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae8f95, too many redirects, quit
09/13 09:14:48.943553 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b155b1, too many redirects, quit
09/13 09:14:49.123743 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b1522a, too many redirects, quit
09/13 09:14:49.128706 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b154c5, too many redirects, quit
09/13 09:14:49.133604 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x27444b6, too many redirects, quit
09/13 09:14:49.143499 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x274739c, too many redirects, quit
09/13 09:14:49.148566 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b13d84, too many redirects, quit
09/13 09:14:49.153454 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b13ce5, too many redirects, quit
09/13 09:14:49.173566 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b13c0f, too many redirects, quit
09/13 09:14:49.178512 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x2743f7f, too many redirects, quit
09/13 09:14:49.203529 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x2744b90, too many redirects, quit
09/13 09:14:49.253643 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b13d6c, too many redirects, quit
09/13 09:14:49.303523 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae7da3, too many redirects, quit
09/13 09:14:49.428563 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae9e51, too many redirects, quit
09/13 09:14:49.453727 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b13a5f, too many redirects, quit
09/13 09:14:49.458499 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b23f8a, too many redirects, quit
09/13 09:14:49.463519 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b153a3, too many redirects, quit
09/13 09:14:49.473571 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b14bb6, too many redirects, quit
09/13 09:14:49.523559 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b25746, too many redirects, quit
09/13 09:14:49.683489 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b13bf3, too many redirects, quit
09/13 09:14:49.738615 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae86e7, too many redirects, quit
09/13 09:14:49.744034 00124367 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:49.763579 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x2743e75, too many redirects, quit
09/13 09:14:50.034609 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b13d19, too many redirects, quit
09/13 09:14:50.063889 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x27441d1, too many redirects, quit
09/13 09:14:50.073484 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x274548f, too many redirects, quit
09/13 09:14:50.769391 00124367 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:50.944350 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b153e8, too many redirects, quit
09/13 09:14:50.948573 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b14cc7, too many redirects, quit
09/13 09:14:51.048543 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b26508, too many redirects, quit
09/13 09:14:51.168899 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b257fe, too many redirects, quit
09/13 09:14:51.173884 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b25767, too many redirects, quit
09/13 09:14:51.183811 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae92aa, too many redirects, quit
09/13 09:14:51.248814 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1af6cdd, too many redirects, quit
09/13 09:14:51.659343 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b1534a, too many redirects, quit
09/13 09:14:51.739225 00124658 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:51.758631 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x274582c, too many redirects, quit
09/13 09:14:51.928615 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1af6d23, too many redirects, quit
09/13 09:14:52.123618 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x274412f, too many redirects, quit
09/13 09:14:52.193579 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b2589b, too many redirects, quit
09/13 09:14:52.764700 00124658 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:52.994102 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b14cdc, too many redirects, quit
09/13 09:14:53.003598 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b23d61, too many redirects, quit
09/13 09:14:53.088565 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b14ca5, too many redirects, quit
09/13 09:14:53.155891 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae74cd, too many redirects, quit
09/13 09:14:53.218594 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b240d2, too many redirects, quit
09/13 09:14:53.383479 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b13a81, too many redirects, quit
09/13 09:14:53.463519 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae80a9, too many redirects, quit
09/13 09:14:53.478486 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b153f3, too many redirects, quit
09/13 09:14:53.734100 00124658 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:53.738699 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b154c5, too many redirects, quit
09/13 09:14:53.758611 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b13d84, too many redirects, quit
09/13 09:14:53.793726 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x2743f7f, too many redirects, quit
09/13 09:14:54.038752 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x274737d, too many redirects, quit
09/13 09:14:54.044080 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae9e51, too many redirects, quit
09/13 09:14:54.293534 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b13bf3, too many redirects, quit
09/13 09:14:54.378520 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x2743e75, too many redirects, quit
09/13 09:14:54.578503 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae9307, too many redirects, quit
09/13 09:14:54.628512 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x27440f6, too many redirects, quit
09/13 09:14:54.638606 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x27440af, too many redirects, quit
09/13 09:14:54.688538 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x274548f, too many redirects, quit
09/13 09:14:54.754204 00124658 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:54.928468 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b2581e, too many redirects, quit
09/13 09:14:55.478850 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae8f9d, too many redirects, quit
09/13 09:14:55.578431 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x274573d, too many redirects, quit
09/13 09:14:55.588571 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b13ba1, too many redirects, quit
09/13 09:14:55.775209 00124658 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:55.858568 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b13f11, too many redirects, quit
09/13 09:14:56.273673 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b1534a, too many redirects, quit
09/13 09:14:56.453553 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x27457ee, too many redirects, quit
09/13 09:14:56.733579 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x274412f, too many redirects, quit
09/13 09:14:56.744490 00124658 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:56.808643 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b2589b, too many redirects, quit
09/13 09:14:56.853779 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b13c0f, too many redirects, quit
09/13 09:14:57.363511 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b15417, too many redirects, quit
09/13 09:14:57.393633 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x274625d, too many redirects, quit
09/13 09:14:57.633571 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b144bd, too many redirects, quit
09/13 09:14:57.713478 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae6559, too many redirects, quit
09/13 09:14:57.764243 00124658 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:58.088547 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b153f3, too many redirects, quit
09/13 09:14:58.303527 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b153e8, too many redirects, quit
09/13 09:14:58.358701 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b154c5, too many redirects, quit
09/13 09:14:58.623564 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b13bfc, too many redirects, quit
09/13 09:14:58.653598 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x274737d, too many redirects, quit
09/13 09:14:58.713539 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b144e9, too many redirects, quit
09/13 09:14:58.739603 00124658 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:58.993843 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x2743e75, too many redirects, quit
09/13 09:14:59.303605 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x274548f, too many redirects, quit
09/13 09:14:59.374739 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b26508, too many redirects, quit
09/13 09:14:59.439328 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae7a43, too many redirects, quit
09/13 09:14:59.443575 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b1529c, too many redirects, quit
09/13 09:14:59.483658 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1af6bf0, too many redirects, quit
09/13 09:14:59.533494 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x2745db8, too many redirects, quit
09/13 09:14:59.538559 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b2581e, too many redirects, quit
09/13 09:14:59.753700 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae78d1, too many redirects, quit
09/13 09:14:59.765092 00012437 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:14:59.783507 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x27473c5, too many redirects, quit
09/13 09:14:59.898694 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x2743d9e, too many redirects, quit
09/13 09:15:00.039779 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x274466a, too many redirects, quit
09/13 09:15:00.118965 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b15431, too many redirects, quit
09/13 09:15:00.188774 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x27472ed, too many redirects, quit
09/13 09:15:00.398547 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b13a79, too many redirects, quit
09/13 09:15:00.458796 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b14ca5, too many redirects, quit
09/13 09:15:00.734553 00012437 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:15:00.863663 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1af1464, too many redirects, quit
09/13 09:15:01.068512 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x2745da1, too many redirects, quit
09/13 09:15:01.098803 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae9e51, too many redirects, quit
09/13 09:15:01.113602 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x27444b6, too many redirects, quit
09/13 09:15:01.153868 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b23fe2, too many redirects, quit
09/13 09:15:01.653559 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x27473b0, too many redirects, quit
09/13 09:15:01.759850 00012437 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:15:01.933495 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae9307, too many redirects, quit
09/13 09:15:01.938773 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x2745573, too many redirects, quit
09/13 09:15:01.953670 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b268db, too many redirects, quit
09/13 09:15:02.008504 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x274625d, too many redirects, quit
09/13 09:15:02.253718 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b14c8e, too many redirects, quit
09/13 09:15:02.779298 00012437 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:15:02.858687 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b13d33, too many redirects, quit
09/13 09:15:03.089150 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1af6fc5, too many redirects, quit
09/13 09:15:03.285076 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1af6d23, too many redirects, quit
09/13 09:15:03.503769 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b23e1b, too many redirects, quit
09/13 09:15:03.608601 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x2743e75, too many redirects, quit
09/13 09:15:03.754159 00012437 UTL cache:stable-vgroup-list will be cleaned up
09/13 09:15:03.808757 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x27457ee, too many redirects, quit
09/13 09:15:03.913910 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x274548f, too many redirects, quit
09/13 09:15:04.038800 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b257fe, too many redirects, quit
09/13 09:15:04.050055 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1ae7a43, too many redirects, quit
09/13 09:15:04.053865 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b1529c, too many redirects, quit
09/13 09:15:04.158960 00120191 RPC WARN TSC 0x7f59a8ca99f0 0x1b2581e, too many redirects, quit

**Comment by yu285** [comment]
服务端可以连接使用么

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
