### ISSUE TITLE
How to upgrade TDengine  from 2.6 to  3.0 

### ISSUE THREAD

**Issue by wuyongx** [taosdata/TDengine#16794]
官方文档没有看到迁移步骤，如何进行数据迁移，谢谢支持。

**Comment by yu285** [comment]
当前还没有直升手段。测试的话，建议新部署一个环境 用 taosBenchmark 模拟数据生成也很便捷。

**Comment by wjehovah** [comment]
不是测试。
生产环境部署的是2.6 ，并且已经有数据 ，升级3.0的话数据需要迁移。

**Comment by wujunchengman** [comment]
同问，生产环境2.4版本，不知道该怎么升级

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
