### ISSUE TITLE
syncUtilnodeInfo2raftId: Assertion `ipv4 != 0xFFFFFFFF' failed.

### ISSUE THREAD

**Issue by sj-dev** [taosdata/TDengine#16799]
k8s中，删除全部pod后，再次启动时报：
taosd: /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/libs/sync/src/syncUtil.c:89: syncUtilnodeInfo2raftId: Assertion `ipv4 != 0xFFFFFFFF' failed.
Aborted (core dumped)

**Comment by sj-dev** [comment]
CREATE DATABASE if not exists test KEEP 36500d replica 3 CACHEMODEL 'both';  只有当replica=3 才会出现这一个问题

**Comment by yu285** [comment]
可以先使用 2.6 的 k8s .

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
