### ISSUE TITLE
Whether the business scenario is suitable for using TDengine

### ISSUE THREAD

**Issue by wzf55555** [taosdata/TDengine#1679]
目前又1000多个点，每个点有10个设备但是每个设备上传的数据种类大概有10种。这种应该怎么去创建父表？怎么去指定 tags。每个点每个种类建一张子表？
若是每个点每个种类创建一个子表那么需要创建的子表太多了。。
此种业务场景是否适合TDEngine。
例如：
       雨量计设备会上传：  1:累计雨量，2:昨日雨量，3:今日雨量。

**Comment by liuyq-617** [comment]
我们的首页：www.taosdata.com上有很多case study 供您参考，您也可以加我的微信进行咨询
wechat :13121752171
