### ISSUE TITLE
taosdump:  export float value inaccuracy

### ISSUE THREAD

**Issue by haides** [taosdata/TDengine#168]
I insert into table, set the float value (220.12).  query is right.
Then I run taosdump with this database, after check the  export file, the float value inaccuracy.

![Snipaste_2019-07-24_11-16-42](https://user-images.githubusercontent.com/451775/61762430-8cfcf100-ae04-11e9-9bf3-0ef501ed38cf.png)

**Comment by ewsq** [comment]
丢失了精度？

**Comment by guanshengliang** [comment]
浮点数能够表示6位有效数字，可以参考
https://blog.csdn.net/qq_16137569/article/details/79508091

TDengine按输入数值进行存储，未进行任何有损压缩或者降精度操作，但是Shell输出代码代码有一定的截断
![image](https://user-images.githubusercontent.com/28882257/61763141-dbab8a80-ae06-11e9-9e9f-82986f34869d.png)

若对精度有特殊要求，可以将浮点数乘以一定倍数，转换为int或者bigint进行存储，例如220.12可以存储为为2201200

**Comment by haides** [comment]
但是我输入的值是220.12. 所以在导出的时候丢失了精度。这个精度是系统自动补充回来的。
![Snipaste_2019-07-24_10-51-39](https://user-images.githubusercontent.com/451775/61763418-e9154480-ae07-11e9-9282-0cc8f45b79bd.png)

**Comment by guanshengliang** [comment]
没有补充精度，%*.5f是C库函数的标准写法，表示打印小数点后5位数字
