### ISSUE TITLE
taosdump export data：memory corruption (fast)

### ISSUE THREAD

**Issue by rocky-fan** [taosdata/TDengine#16828]
在导出数据时失败，错误提示：memory corruption (fast)。

数据库版本为：3.0.1.0
导出工具版本为：taosdump version 2.1.3

建表语句如下：
`Create Table: CREATE STABLE `electricity` (`ts` TIMESTAMP, `active_power_total` DOUBLE, `active_power_a` DOUBLE, `active_power_b` DOUBLE, `active_power_c` DOUBLE, `reactive_power_total` DOUBLE, `reactive_power_a` DOUBLE, `reactive_power_b` DOUBLE, `reactive_power_c` DOUBLE, `power_factor_total` DOUBLE, `power_factor_a` DOUBLE, `power_factor_b` DOUBLE, `power_factor_c` DOUBLE, `voltage_a` DOUBLE, `voltage_b` DOUBLE, `voltage_c` DOUBLE, `current_a` DOUBLE, `current_b` DOUBLE, `current_c` DOUBLE, `positive_active_power` DOUBLE, `reverse_active_power` DOUBLE, `positive_reactive_power` DOUBLE, `reverse_reactive_power` DOUBLE, `combination_active_power` DOUBLE, `consumption_positive` DOUBLE, `consumption_reverse` DOUBLE, `consumption` DOUBLE, `charge_positive` DOUBLE, `charge_reverse` DOUBLE, `pv_type` TINYINT, `price` DOUBLE, `szglz` DOUBLE, `szgla` DOUBLE, `szglb` DOUBLE, `szglc` DOUBLE, `zdxl` DOUBLE, `zdxlts` BIGINT, `zhygj` DOUBLE, `zhygf` DOUBLE, `zhygp` DOUBLE, `zhygg` DOUBLE, `djts` BIGINT, `djzxygz` DOUBLE, `djzxygj` DOUBLE, `djzxygf` DOUBLE, `djzxygp` DOUBLE, `djzxygg` DOUBLE, `djfxygz` DOUBLE, `djfxygj` DOUBLE, `djfxygf` DOUBLE, `djfxygp` DOUBLE, `djfxygg` DOUBLE, `charge` DOUBLE, `consumption_positive_reactive` DOUBLE, `consumption_reverse_reactive` DOUBLE, `charge_positive_reactive` DOUBLE, `charge_reverse_reactive` DOUBLE, `zhygjcz` DOUBLE, `zhygfcz` DOUBLE, `zhyggcz` DOUBLE, `zhygpcz` DOUBLE, `zhygjfy` DOUBLE, `zhygffy` DOUBLE, `zhygpfy` DOUBLE, `zhyggfy` DOUBLE, `djzxygzcz` DOUBLE, `djfxygzcz` DOUBLE, `djfxygfcz` DOUBLE, `djfxygjcz` DOUBLE, `djfxygpcz` DOUBLE, `djfxyggcz` DOUBLE, `djzxygfcz` DOUBLE, `djzxygjcz` DOUBLE, `djzxygpcz` DOUBLE, `djzxyggcz` DOUBLE, `active_power_total_act` DOUBLE, `active_power_a_act` DOUBLE, `active_power_b_act` DOUBLE, `active_power_c_act` DOUBLE, `reactive_power_total_act` DOUBLE, `reactive_power_a_act` DOUBLE, `reactive_power_b_act` DOUBLE, `reactive_power_c_act` DOUBLE, `voltage_a_act` DOUBLE, `voltage_b_act` DOUBLE, `voltage_c_act` DOUBLE, `current_a_act` DOUBLE, `current_b_act` DOUBLE, `current_c_act` DOUBLE, `positive_active_power_act` DOUBLE, `reverse_active_power_act` DOUBLE, `positive_reactive_power_act` DOUBLE, `reverse_reactive_power_act` DOUBLE, `combination_active_power_act` DOUBLE, `consumption_positive_act` DOUBLE, `consumption_reverse_act` DOUBLE, `consumption_act` DOUBLE, `charge_act` DOUBLE, `charge_positive_act` DOUBLE, `charge_reverse_act` DOUBLE, `szglz_act` DOUBLE, `szgla_act` DOUBLE, `szglb_act` DOUBLE, `szglc_act` DOUBLE, `zdxl_act` DOUBLE, `zhygj_act` DOUBLE, `zhygf_act` DOUBLE, `zhygp_act` DOUBLE, `zhygg_act` DOUBLE, `djzxygz_act` DOUBLE, `djzxygj_act` DOUBLE, `djzxygf_act` DOUBLE, `djzxygp_act` DOUBLE, `djzxygg_act` DOUBLE, `djfxygz_act` DOUBLE, `djfxygj_act` DOUBLE, `djfxygf_act` DOUBLE, `djfxygp_act` DOUBLE, `djfxygg_act` DOUBLE, `consumption_positive_reactive_act` DOUBLE, `consumption_reverse_reactive_act` DOUBLE, `charge_positive_reactive_act` DOUBLE, `charge_reverse_reactive_act` DOUBLE, `zhygjcz_act` DOUBLE, `zhygfcz_act` DOUBLE, `zhyggcz_act` DOUBLE, `zhygpcz_act` DOUBLE, `zhygjfy_act` DOUBLE, `zhygffy_act` DOUBLE, `zhygpfy_act` DOUBLE, `zhyggfy_act` DOUBLE, `djzxygzcz_act` DOUBLE, `djfxygzcz_act` DOUBLE, `djfxygfcz_act` DOUBLE, `djfxygjcz_act` DOUBLE, `djfxygpcz_act` DOUBLE, `djfxyggcz_act` DOUBLE, `djzxygfcz_act` DOUBLE, `djzxygjcz_act` DOUBLE, `djzxygpcz_act` DOUBLE, `djzxyggcz_act` DOUBLE, `bl_voltage` INT, `bl_current` INT, `bl` INT, `n1xxwgdnz` DOUBLE, `n2xxwgdnz` DOUBLE, `n3xxwgdnz` DOUBLE, `n4xxwgdnz` DOUBLE, `dwpl` DOUBLE, `lxdl` DOUBLE, `n1xxwgdnz_act` DOUBLE, `n2xxwgdnz_act` DOUBLE, `n3xxwgdnz_act` DOUBLE, `n4xxwgdnz_act` DOUBLE, `n1xxwgdnzcz` DOUBLE, `n2xxwgdnzcz` DOUBLE, `n3xxwgdnzcz` DOUBLE, `n4xxwgdnzcz` DOUBLE, `n1xxwgdnzcz_act` DOUBLE, `n2xxwgdnzcz_act` DOUBLE, `n3xxwgdnzcz_act` DOUBLE, `n4xxwgdnzcz_act` DOUBLE) TAGS (`no` NCHAR(50))`

报错截图：
![d89fc0ad3cdfce22ffe92f4d7e9ea86](https://user-images.githubusercontent.com/58651511/190068916-c94cdfac-6365-4962-bf4a-5ad955abfde7.jpg)

请问如何解决这个问题。

**Comment by sangshuduo** [comment]
使用 taosBenchmark 命令
taosBenchmark -b DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,TINYINT,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,BIGINT,DOUBLE,DOUBLE,DOUBLE,DOUBLE,BIGINT,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,INT,INT,INT,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE,DOUBLE -A nchar\(50\) -t 1000 -n 100 -y

建1000个表，每个表 100 条记录，taosdump 可以正常运行。

请提供 db 是否有其他超级表，是否有不属于任何超级表的普通表，各个超级表下有多少子表，每个子表大概有多少条记录，另外是否有 TAG 值为 NULL 的情况。谢谢

**Comment by rocky-fan** [comment]
1、数据库一共有3个超级表。
2、没有不属于任何超级表的普通表
3、以上提供表结构的超级表下有40个子表
4、每个子表做多的有1w多条数据，最少的有2k多条数据
5、没有TAG值为NULL的情况。

**Comment by sangshuduo** [comment]
已找到原因，争取尽快修复

**Comment by rocky-fan** [comment]
此问题已经在[taosTools-2.2.0-Linux-x64.deb (0.4 M)](https://docs.taosdata.com/get-started/package/#!)版本中解决，感谢
