### ISSUE TITLE
Turn on monitor=1 but not found log database

### ISSUE THREAD

**Issue by d4j-opensource** [taosdata/TDengine#16820]
Please help me!

/etc/taos/taos.cfg
`09/13 17:36:55.443491 01062176 UTL cfg_file     monitor                  1

09/13 17:36:55.443493 01062176 UTL default      monitorInterval          30

09/13 17:36:55.443496 01062176 UTL default      monitorFqdn              

09/13 17:36:55.443499 01062176 UTL default      monitorPort              6043

09/13 17:36:55.443502 01062176 UTL default      monitorMaxLogs           100

09/13 17:36:55.443504 01062176 UTL default      monitorComp              0
`

Log database not shown
![image](https://user-images.githubusercontent.com/104894975/189880345-b3b93ce0-34ac-4d60-a34f-f9a57239734a.png)

**Comment by yu285** [comment]
Hi 3.0 version TDengine ，there is no log database any more

**Comment by d4j-opensource** [comment]
How do I use TDinsight (https://docs.tdengine.com/operation/monitor/)?

**Comment by yu285** [comment]
check on this https://docs.tdengine.com/reference/taosKeeper/#
