### ISSUE TITLE
windows  taosc time not same as Linux taosd

### ISSUE THREAD

**Issue by wanjwsuper** [taosdata/TDengine#16837]
windows 客户端的时间戳（左边），本机客户端的ts时间戳（右边），显示的不一样

![d7a1cefc3d53baa4bd30a124058787a](https://user-images.githubusercontent.com/73144112/190113516-b93fb914-aa71-48b7-bbc9-f2565fec236d.jpg)

**Comment by yu285** [comment]
客户端和服务端机器的默认时区是多少？

有在客户段手动指定时区么

**Comment by wanjwsuper** [comment]
C:\TDengine\cfg
# system time zone
# timezone              Asia/Shanghai (CST, +0800)
# system time zone (for windows 10)
timezone                  UTC-8
linux的taos.cfg
![image](https://user-images.githubusercontent.com/73144112/190124343-54e330a9-22f0-467c-acc5-6ba7a3b2a184.png)

**Comment by wanjwsuper** [comment]
windows 10 的UTC-8改成UTC+8 OK了
