### ISSUE TITLE
last_row led to cluster  service restart 

### ISSUE THREAD

**Issue by qingquaner** [taosdata/TDengine#16838]
TDengine版本：2.4.0.30

![b96eb34595f3bb4c041fde46a93a76c](https://user-images.githubusercontent.com/20200473/190112565-b09745d4-4cae-4220-9777-68798abb469a.png)
![5c752f7d3d305098c78eaf449db9667](https://user-images.githubusercontent.com/20200473/190112786-55108d22-6c6d-449e-b598-21fc6bf4d671.png)

集群安装成功后，调整过numOfMnodes 参数，由初始值1变成3

执行last_row时，
![e53475908dd9108c2dc0eed88c8c783](https://user-images.githubusercontent.com/20200473/190112684-f1fa326c-498a-42fc-8d4a-d6869bc1001f.png)
下面是日志：
![fc4e3a99c0440d5cf23093e81b55309](https://user-images.githubusercontent.com/20200473/190113080-0b11482d-dafa-4ac9-8f5e-4832f0d99541.png)

现怀疑多个mnode元信息不一致导致，我该如何处理？重装集群？

**Comment by yu285** [comment]
现在服务可用吗？
