### ISSUE TITLE
client query deadlock

### ISSUE THREAD

**Issue by AxeXiey** [taosdata/TDengine#16844]
**Bug Description**

Occasionally ,when I execute a query there will be a deadlock。

**To Reproduce**
1. Create a super table t1 ;
```sql
create stable t1(ts timestamp,value doube) tags(device binary(8),point binary(8));
```
2. Create 100000 sub tables of the super table t1;
3. Initialize 2 billion records to the super table t1  according to the frequency of one record of data per minute for each device;
4.  Continue writing data;
5. Execute this query every 10 seconds through the program；
```sql
select sum(value) as data_value from t1 where device in('d1','d2','d3','d4','d5') and point in('point1')
and ts between '2022-09-01 00:00:00' and '2022-09-02 00:00:00';
```
7. Generally, the query returns results within 1 second, but occasionally it will be a deadlock。

**Expected Behavior**
1.This problem will happens with both udp and tcp protocols，even on the server client command line.
2.There is no error log when deadlock happened.

**Screenshots**

![p1](https://user-images.githubusercontent.com/26057707/190129982-87829e04-b1fb-441c-88b6-96e967134ff7.png)

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory 16G, CPU 8Core, current Disk Space 150G
 - TDengine Version [e.g. 2.4.0.30]
 - Deploy  single node

**Additional Context**
![p2](https://user-images.githubusercontent.com/26057707/190139612-8c0e511d-05a5-4a43-9336-0376efa159cc.png)

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
