### ISSUE TITLE
arm-linux-gnueabihf-gcc: error: unrecognized command line option '-msse4.2'

### ISSUE THREAD

**Issue by GeorgeWang12356** [taosdata/TDengine#16889]
#!/bin/bash

if [ ! -d debug ]; then
    mkdir debug || echo -e "failed to make directory for build"
fi

cd debug && cmake .. -DBUILD_TOOLS=true -DCMAKE_CXX_COMPILER=/home/my/env/rkarm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++ -DCMAKE_C_COMPILER=/home/my/env/rkarm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc && make

![image](https://user-images.githubusercontent.com/13636697/190553250-307615a4-462e-4454-b424-475aa800f8b3.png)

**Comment by skyformat99** [comment]
**提示：**在 ARM 环境下编译时，请将 makefile 中的 `-msse4.2` 去掉，这个选项只有在 x64/x86 硬件平台上才能支持。
