### ISSUE TITLE
failed to connect to server, reason: Database not ready

### ISSUE THREAD

**Issue by Mark916** [taosdata/TDengine#16883]
**Bug Description**
failed to connect to server, reason: Database not ready

**To Reproduce**
1. installed soft by tar.gz package 
2. systemctl start taosd     status:active (running)
3. systemctl start taosadapter  status:active (running)
4. connect to server by command:`taos -h 192.168.126.130 -P 6030`

**Expected Behavior**
Happen below error:
[root@server003 TDengine-server-3.0.1.1]# taos -h 192.168.126.130 -P 6030
Welcome to the TDengine Command Line Interface, Client Version:3.0.1.1
Copyright (c) 2022 by TDengine, all rights reserved.

failed to connect to server, reason: Database not ready

[root@server003 TDengine-server-3.0.1.1]# taos -h 192.168.126.130 -P 6030
Welcome to the TDengine Command Line Interface, Client Version:3.0.1.1
Copyright (c) 2022 by TDengine, all rights reserved.

failed to connect to server, reason: Database not ready

[root@server003 TDengine-server-3.0.1.1]# 

**Screenshots**
![error](https://user-images.githubusercontent.com/32362952/190544807-a25f4cd7-1612-442a-b483-791f0ab5041e.png)

**Environment :**
 - OS: [ CentOS 7.9]
 - Memory[2G], CPU[1H], current Disk Space [20G]
 - TDengine Version [3.0.1.1]

**Comment by skyformat99** [comment]
哈哈 老问题啊

哈哈，数据格式不同；删了吧
参考这个https://github.com/taosdata/TDengine/issues/16449

**Comment by 2215641174** [comment]
> 哈哈 老问题啊
> 
> 哈哈，数据格式不同；删了吧 参考这个#16449

没有升级重新部署也遇到了这个报错

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
