### ISSUE TITLE
请问如何删除超级表的子表?

### ISSUE THREAD

**Issue by pigwing** [taosdata/TDengine#169]
DROP TABLE 子表名称,然后会报语法错误.

**Comment by guanshengliang** [comment]
可以贴一个图吗

**Comment by pigwing** [comment]
![image](http://wx2.sinaimg.cn/large/6430c97bgy1g5atw5vanij20wc048wei.jpg)

**Comment by guanshengliang** [comment]
This is a bug, we will fix it as soon as possible

**Comment by fangpanpan** [comment]
you can try to change you table's name, which starts with letters instead.

**Comment by pigwing** [comment]
@guanshengliang 再请教个问题,为什么时间格式化方面,只有19年,而不是2019年的呢?

**Comment by guanshengliang** [comment]
显示格式的一种设置，并没什么特殊的设计或者更深层次的原因

**Comment by pigwing** [comment]
不能显示成yyyy-MM-dd 这种的吗?

**Comment by guanshengliang** [comment]
真正用的时候，一般都是通过程序进行控制，Shell只是一种后台管理工具。

现在没有配置项，将shell输出成这种方式

**Comment by pigwing** [comment]
谢谢,明白了.我以为程序输出也会这样.
