### ISSUE TITLE
complie with arm-linux-gnueabihf-gcc

### ISSUE THREAD

**Issue by GeorgeWang12356** [taosdata/TDengine#16903]
`vi CMakelist.txt`

add
![image](https://user-images.githubusercontent.com/13636697/190844690-e85bbdfd-7544-4e8f-a7cc-13906b0623b5.png)

modify the cmake/cmake.define
`vi cmake/cmake.define`
![image](https://user-images.githubusercontent.com/13636697/190844724-d6192eda-3a2e-4f79-9cb7-dcb058c4caf1.png)

then:
```
mkdir build
cd build/
sudo cmake .. -DARMVER=arm32
sudo make
```
the result:
![image](https://user-images.githubusercontent.com/13636697/190844639-9c1392d4-4a01-46a3-b776-1fc4d6170e1e.png)

**Comment by sangshuduo** [comment]
cmake 加 -DCPUTYPE=arm32 试试

**Comment by GeorgeWang12356** [comment]
> cmake 加 -DCPUTYPE=arm32 试试

![image](https://user-images.githubusercontent.com/13636697/190937402-4ea25400-5205-43b2-aafe-a34ce7de75ac.png)

**Comment by sangshuduo** [comment]
比较怀疑是 linaro gcc 6.3.1 的行为和标准 gcc 不一样，我们这里没有交叉编译的环境，你可以试试修改 source/client/com_taosdata_jdbc_tmq_TMQConnector.h 把参数名称加上看行不行

**Comment by GeorgeWang12356** [comment]
> -DCPUTYPE=arm32

统一函数定义后，编译通过，关于taosd和taos在目标机上运行有如下问题：
**1**.taosd运行磁盘空间不够，关于磁盘空间，目标机采用的是overlayfs，虽然rootfs不够2G，但用户实际使用的空间不止2G，这种情况是否通过相关配置解决，还是只能修改rootfs的固定大小至2G以上
![image](https://user-images.githubusercontent.com/13636697/190967137-2f487f6a-3217-46e9-8a39-a4fff1b660e7.png)

**2**.taos运行，Bus error (core dumped)
![image](https://user-images.githubusercontent.com/13636697/190967267-921a0721-9d7f-43c2-ae0f-a5803c96f874.png)

**Comment by sangshuduo** [comment]
了解。目前 arm32 平台还没有适配完成，如果有企业版用户需要也可以提高优先级

**Comment by GeorgeWang12356** [comment]
> 了解。目前 arm32 平台还没有适配完成，如果有企业版用户需要也可以提高优先级

OK,这个情况不是因为我这边编译操作，编译配置之类的导致的？ 而是arm32还没有适配完成导致的？

**Comment by sangshuduo** [comment]
> > 了解。目前 arm32 平台还没有适配完成，如果有企业版用户需要也可以提高优先级
> 
> OK,这个情况不是因为我这边编译操作，编译配置之类的导致的？ 而是arm32还没有适配完成导致的？

因素比较多，交叉编译之前也没有正式支持，所以很难说具体问题在哪。不过代码都是开源的，欢迎 bugfix 后 PR 回 TDengine

**Comment by sangshuduo** [comment]
> > > > 了解。目前 arm32 平台还没有适配完成，如果有企业版用户需要也可以提高优先级
> > > 
> > > 
> > > OK,这个情况不是因为我这边编译操作，编译配置之类的导致的？ 而是arm32还没有适配完成导致的？
> > 
> > 
> > 因素比较多，交叉编译之前也没有正式支持，所以很难说具体问题在哪。不过代码都是开源的，欢迎 bugfix 后 PR 回 TDengine
> 
> 好的好的，了解了 ，感谢解答。

统一函数定义的修改，欢迎 PR 回 TDengine，谢谢 :)

**Comment by GeorgeWang12356** [comment]
已PR

![image](https://user-images.githubusercontent.com/13636697/190989668-1ea3c030-149d-4f6d-b832-ff3258f08fc0.png)
