### ISSUE TITLE
over 100% CPU load for running the C example code from https://docs.tdengine.com/develop/tmq/

### ISSUE THREAD

**Issue by alec-liu** [taosdata/TDengine#16904]
I just copy and paste the C example code from https://docs.tdengine.com/develop/tmq/ to test the "Data Subscription".
Then build it with "gcc -o example example.c -ltaos", and run it.

And the example code just push the "taosd" process to 61.5% and "example" process to 149.5%.

I just want to know if it is normal. 

Thank you.

**Comment by yu285** [comment]
The bugs in earlier versions of 3.0 have been fixed, but 3.0.2.5 May not be compatible with the current version (3.3.0.0), so it is not possible to upgrade directly. Therefore, it is recommended to redeploy the latest 3.3.0.0, the subsequent upgrade is very convenient, directly install the latest version of the software.

Range of open source version of the operating system support: https://docs.taosdata.com/reference/support-platform/
The bugs from earlier versions of 3.0 have been fixed, but 3.0.2.5 May not be compatible with the current version (3.3.0.0), so it is not possible to upgrade directly. Therefore, it is recommended to redeploy the latest 3.3.0.0, the subsequent upgrade is very convenient, directly install the latest version of the software.

Range of open source version of the operating system support: https://docs.taosdata.com/reference/support-platform/
