### ISSUE TITLE
Data subscribtion

### ISSUE THREAD

**Issue by 6tJaCeF** [taosdata/TDengine#16917]
请问   数据订阅2.4版本
1.如果机器重启是否订阅也要重头开始
2.如何避免一开始数据量过大导致系统崩溃，然后重启又重头开始订阅数据的问题

**Comment by yu285** [comment]
文档有提，通过参数可以确定消费位置

**Comment by 6tJaCeF** [comment]
可否截图发一下，没有找不到，java的api，我尝试过订阅指定restart参数和close关闭订阅时候参数设置true，我机器重启后，还是从头拉了数据，所以不好意思咨询一下

**Comment by 6tJaCeF** [comment]
是这部分吗
![image](https://user-images.githubusercontent.com/34031268/192407629-8b46b704-be18-4880-af2e-36de492aabf2.png)
