### ISSUE TITLE
python connector query不返回

### ISSUE THREAD

**Issue by saiyn** [taosdata/TDengine#1691]
**Environment :**
 - TDEngine client: build source code from tag 1.6.5.5 on docker container(ubuntu 18.04 )
 - TDEngine  server: 1.6.5.5 image from docker hub
 -  Docker Host Disk Space: sometimes < 0.5GB

**To Reproduce**
1. insert some data( < 10 items) to the Server(TDEngine container)
2. restart the client which is a flask+uwsgi  web server container, the client connect to TDEngine server success
3. trigger query history data from web ui container
4. the client hang on the query and wont return anymore
5. check the log in client side, just an error msg:"ERROR RPC TSC-mgmt cid:0, sid:2 session is already released"

**debug**
1. verbose log level in client side 
2. restart the client container and reproduce and save the taoslog0.0
3. trigger the query by exec the python unitest which send the same query cmd, and the query return success, and the log save to taoslog1.0

**Comment by saiyn** [comment]
[taoslog0.txt](https://github.com/taosdata/TDengine/files/4519786/taoslog0.txt)
[taoslog1.txt](https://github.com/taosdata/TDengine/files/4519787/taoslog1.txt)

**Comment by saiyn** [comment]
多线程问题，已解决

**Comment by liujian016** [comment]
我也遇到了同样的问题，请问如何解决的？

> 多线程问题，已解决
