### ISSUE TITLE
exception: [0x000b]: Unable to establish connection 

### ISSUE THREAD

**Issue by Aismiler** [taosdata/TDengine#16943]
相关版本
TDEngine： 2.4.0.26
taospy: 2.3.1
使用python在docker中向td插入数据

执行的sql: 
insert into var_id_2321 file 'data.csv'

捕获到的异常：
exception: [0x000b]: Unable to establish connection

从后续的数据看，文件中的数据都成功插入到对应的表中了。

**Comment by sangshuduo** [comment]
怀疑是网络不稳定，可以用 taos shell 连一下试试。或者用 taosBenchmark 大批量写入或者查询看有没有 Unable to establish connection 出现
