### ISSUE TITLE
TDinsight DNodes Lifetime lost

### ISSUE THREAD

**Issue by noor-ho-tabbe** [taosdata/TDengine#16951]
TDinsight 在使用一段时间后 DNodes Lifetime节点少了一个。

 
![41b2cdc127ca4541b6c299f66a94572](https://user-images.githubusercontent.com/12782877/191203984-fdee49b9-c8a7-4a8a-a0f2-f22b502168b5.jpg)

1.  版本信息 :  Version:2.4.0.0
2.  3个节点的 taosd，taosAdapter 都正常运行
3.  数据写入也正常

**Comment by yu285** [comment]
你的意思是 节点1 看不到了，监控页面只剩下 2 和 3 了吗

**Comment by noor-ho-tabbe** [comment]
> 你的意思是 节点1 看不到了，监控页面只剩下 2 和 3 了吗

是的

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
