### ISSUE TITLE
example lua51 connector build with warning, run got error!

### ISSUE THREAD

**Issue by cdnplus** [taosdata/TDengine#16963]
**Bug Description**
pull the main branch code,  then build connector file "examples/lua/lua51/lua_connector51.c", got some warning message.
Detail:

> lua_connector51.c: In function ‘l_open_stream’:
lua_connector51.c:313:3: warning: implicit declaration of function ‘taos_open_stream’ [-Wimplicit-function-declaration]
   void* s = taos_open_stream(taos,sqlstr,stream_cb,stime,p,NULL);
   ^
lua_connector51.c:313:13: warning: initialization makes pointer from integer without a cast [enabled by default]
   void* s = taos_open_stream(taos,sqlstr,stream_cb,stime,p,NULL);
             ^
lua_connector51.c: In function ‘l_close_stream’:
lua_connector51.c:340:3: warning: implicit declaration of function ‘taos_close_stream’ [-Wimplicit-function-declaration]
   taos_close_stream(p->stream);
   ^

got file "luaconnector51.so". run command **lua test.lua** got error message.
Detail:

> lua: error loading module 'luaconnector51' from file './luaconnector51.so':
        ./luaconnector51.so: undefined symbol: taos_open_stream
stack traceback:
        [C]: ?
        [C]: in function 'require'
        test.lua:1: in main chunk
        [C]: ? 

**To Reproduce**
2. Type in '....'
3. See error

**Environment (please complete the following information):**
 - OS: CentOS Linux release 7.7.1908 (Core)
 - Memory, CPU, current Disk Space
 - TDengine Version 3.0.1.1

**Comment by sangshuduo** [comment]
Thanks for your reporting. The PR https://github.com/taosdata/TDengine/pull/16979 will fix it.

**Comment by cdnplus** [comment]
thanks your reply.But I pull the fix code, build it with no warning, running test.lua then got error.
Detail:

> lua: error loading module 'luaconnector51' from file './luaconnector51.so':
        ./luaconnector51.so: undefined symbol: luaL_setfuncs
stack traceback:
        [C]: ?
        [C]: in function 'require'
        test.lua:1: in main chunk
        [C]: ?

- Lua version: 5.1.4

**Comment by sangshuduo** [comment]
我用 Lua 5.3.3 (Ubuntu 20.04) 执行 build.sh 然后 lua test.lua 没问题

**Comment by cdnplus** [comment]
I want to use openresty with lua, openresty only support lua 5.1

**Comment by robotspace** [comment]
> I want to use openresty with lua, openresty only support lua 5.1

I've got that, prepare to fix it ASAP.

**Comment by cdnplus** [comment]
Thanks.

**Comment by robotspace** [comment]
> I want to use openresty with lua, openresty only support lua 5.1

Patch is accepted now. Please test it on branch 3.0. Main branch may get update some days layter.

**Comment by robotspace** [comment]
> I tried, but not succeed, got the same error messages. May the reason, the test.lua file have a function named "luaL_setfuncs" that only disappear in lua 5.2 and 5.3.
luaL_setfuncs is adopted from Lua5.2 by LuaJit. It's supported by OpenResty since LuaJit is essential. Do set Macro BUILD_LUA following steps in 
[build for lua](https://github.com/robotspace/TDengine/tree/develop/examples/lua)

**Comment by robotspace** [comment]
You may build tdengine as default configure, so a old version lua lib is wrappered. That's a delimma for now.

**Comment by cdnplus** [comment]
I test it on branch 3.0, run the lua script "test.lua" successfully with openresty luajit.
Copy test.lua to Openresty/resty/test_api.lua, luaconnector51.so to Openresty/so/luaconnector51.so
`curl http://127.0.0.1:7000/api/test_api`, got the error message

> 2022/10/17 21:17:32 [error] 17910#17910: *3 lua entry thread aborted: runtime error: error loading module 'luaconnector51' from file './/so/luaconnector51.so':
        .//so/luaconnector51.so: undefined symbol: luaopen_luaconnector51
stack traceback:
coroutine 0:
        [C]: in function 'require'
        ./rest/test_api.lua:1: in main chunk, client: 127.0.0.1, server: restapi, request: "GET /api/test_api HTTP/1.1", host: "127.0.0.1:7000"

Fix it with add the code to the end of "lua_connector51.c"

> 
extern int luaopen_luaconnector(lua_State* L)
{
  //  luaL_register(L, "luaconnector51", lib);
  lua_newtable(L);
  luaL_setfuncs(L,lib,0);
  return 1;
}

---

At the last, `curl http://127.0.0.1:7000/api/test`, got the error message

> 2022/10/17 21:47:30 [alert] 20007#20007: worker process 20044 exited on signal 11 (core dumped)

Remove the tdpool part of the code,  it can be fixed

**Comment by robotspace** [comment]
> 
It's not a good idea to do like that.
TDengine/examples/lua/test.lua is a demo for lua53 without luajit. Data type for Integer is supported in lua53.
TDengine/examples/lua/lua51 is for Openresty and Integer is not supported. If you create lib succsessfully just copy it into Openrsty's subdirectory so. For better performance, you can build with luajit.

**Comment by robotspace** [comment]
> I test it on branch 3.0, run the lua script "test.lua" successfully with openresty luajit. Copy test.lua to Openresty/resty/test_api.lua, luaconnector51.so to Openresty/so/luaconnector51.so `curl http://127.0.0.1:7000/api/test_api`, got the error message
> 
> > 2022/10/17 21:17:32 [error] 17910#17910: *3 lua entry thread aborted: runtime error: error loading module 'luaconnector51' from file './/so/luaconnector51.so':
> > .//so/luaconnector51.so: undefined symbol: luaopen_luaconnector51
> > stack traceback:
> > coroutine 0:
> > [C]: in function 'require'
> > ./rest/test_api.lua:1: in main chunk, client: 127.0.0.1, server: restapi, request: "GET /api/test_api HTTP/1.1", host: "127.0.0.1:7000"
> 
> Fix it with add the code to the end of "lua_connector51.c"
> 
> > 
> 
> extern int luaopen_luaconnector(lua_State* L) { // luaL_register(L, "luaconnector51", lib); lua_newtable(L); luaL_setfuncs(L,lib,0); return 1; }
> 
> At the last, `curl http://127.0.0.1:7000/api/test`, got the error message
> 
> > 2022/10/17 21:47:30 [alert] 20007#20007: worker process 20044 exited on signal 11 (core dumped)
> 
> Remove the tdpool part of the code, it can be fixed

It's not a good idea to do like that.
TDengine/examples/lua/test.lua is a demo for lua53 without luajit. Data type for Integer is supported in lua53.
TDengine/examples/lua/lua51 is for Openresty and Integer is not supported. If you create lib succsessfully just copy it into Openrsty's subdirectory so. For better performance, you can build with luajit.
