### ISSUE TITLE
Does not open 6041 port on windows server 2019

### ISSUE THREAD

**Issue by richwxd** [taosdata/TDengine#16968]
**Bug Description**
6041 port cannot be used on windows server 2019

**To Reproduce**
1. run taosd.exe

**Expected Behavior**
6041 port must be accessible

**Screenshots**

**Environment (please complete the following information):**
 - OS:  Windows server 2019
 - TDengine Version 3.0.1.1

**Comment by yu285** [comment]
please run taosadapter.exe to enable 6041
