### ISSUE TITLE
taosd crash after run sql query

### ISSUE THREAD

**Issue by rocky-fan** [taosdata/TDengine#16996]
数据库版本：community version: 3.0.1.2 compatible_version: 3.0.0.0
(gdb) bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:431
#1  0x00005555556e0bc8 in copyBlockDataToSDataBlock (pReader=0x7fff50074440, pBlockScanInfo=0x7fff50019a78)
    at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/tsdb/tsdbRead.c:901
#2  0x00005555556eb7d3 in doRetrieveDataBlock (pReader=0x7fff50074440)
    at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/tsdb/tsdbRead.c:3665
#3  0x00005555556eb854 in tsdbRetrieveDataBlock (pReader=0x7fff50074440, pIdList=0x0)
    at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/tsdb/tsdbRead.c:3678
#4  0x0000555555706f2c in loadDataBlock (pOperator=0x7fff50024e80, pTableScanInfo=0x7fff50015620, pBlock=0x7fff5002f2c0,
    status=0x7fffb6ffc7e0) at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/libs/executor/src/scanoperator.c:363
#5  0x0000555555707d43 in doTableScanImpl (pOperator=0x7fff50024e80)
    at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/libs/executor/src/scanoperator.c:523
#6  0x0000555555707f4a in doTableScanGroup (pOperator=0x7fff50024e80)
    at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/libs/executor/src/scanoperator.c:563
#7  0x00005555557084fd in doTableScan (pOperator=0x7fff50024e80)
    at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/libs/executor/src/scanoperator.c:667
#8  0x000055555570467a in doProjectOperation (pOperator=0x7fff50032010)
    at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/libs/executor/src/projectoperator.c:238
#9  0x00005555556ee2c9 in qExecTaskOpt (tinfo=0x7fff500420c0, pResList=0x7fff50042480, useconds=0x7fffb6ffcb38)
    at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/libs/executor/src/executor.c:514
#10 0x000055555574c6b0 in qwExecTask (mgmt=0x7fffd0127e80, sId=3472613070611690339, qId=7024609596509126740, tId=79, rId=67,
    eId=0, ctx=0x7fff9001bd68, queryStop=0x0

**Comment by sangshuduo** [comment]
will be fixed in next release
