### ISSUE TITLE
官网文档不通顺

### ISSUE THREAD

**Issue by will-Niu** [taosdata/TDengine#17]
**https://www.taosdata.com/cn/documentation/connector/#C/C++-Connector**
> 注意：对于单个数据库连接，在同一时刻只能有一个线程使用该链接调用API，否则可能会为定义的行为出现。客户端应用可以通过建立多个连接进行多线程的数据写入或查询处理。

> 否则可能会为定义的行为出现

否则可能会有未定义的行为出现？

**Comment by johnnyhou327** [comment]
谢谢指出，已改正。
