### ISSUE TITLE
Regarding to CQ of TDengine

### ISSUE THREAD

**Issue by kmijnuhb** [taosdata/TDengine#17015]
版本：TDengine-server-2.6.0.4-Linux-x64.tar.gz
  求一天内每小时的走值，但是报functions not compatible with interval，
  无效操作：函数与间隔不兼容
  有什么特色查询函数可以实现求时序数据的小时电量走了多少度电吗
     `SELECT DIFF(value) FROM chun_data.data_nenghao_lj 
   WHERE 
   ts>'2022-09-20' AND ts<'2022-09-21'  
   INTERVAL(60m)
   GROUP BY addr`

**Comment by yu285** [comment]
select sum(value) from (select diff(val)  value , tbname, tag1 from super_table) interval(1m)

try this one

**Comment by kmijnuhb** [comment]
select sum(value) from (select diff(val) value , tbname, tag1 from super_table) interval(1m)
有些问题，子句的执行不通过
select diff(value),tbname from chun_data.data_nenghao_lj
invalid operation: TWA/Diff/Derivative/Irate/CSUM/MAVG/SAMPLE/INTERP/Elapsed are not allowed to apply to super table directly


select sum(value) from (select diff(value), tbname,addr from chun_data.data_nenghao_lj where addr='691805310014') interval(1m)
invalid operation: TWA/Diff/Derivative/Irate/CSUM/MAVG/SAMPLE/INTERP/Elapsed are not allowed to apply to super table directly

和2.6的版本有关吗？
另外，先计算每条记录的之间的差值，再求和
比
先按小时分割数据，取出第一个数据，再求每个小时的窗口的数据差，
计算量更大

**Comment by kmijnuhb** [comment]
针对智能电表采集的数据，以 10 分钟为一个阶段，计算过去 24 小时的电流数据的平均值、最大值、电流的中位数。如果没有计算值，用前一个非 NULL 值填充。使用的查询语句如下：

SELECT AVG(current), MAX(current), APERCENTILE(current, 50) FROM meters
  WHERE ts>=NOW-1d and ts<=now
  INTERVAL(10m)
  FILL(PREV);
  这个文档示例怎末改造成计算过去 24 小时的电流数据的小时走值呢

**Comment by kmijnuhb** [comment]
![image](https://user-images.githubusercontent.com/9735193/192716904-80099a15-d916-4c6c-b515-26226476d2c2.png)
![image](https://user-images.githubusercontent.com/9735193/192716913-b6190eff-67ba-4ce5-9f33-d888beb00f79.png)

**Comment by kmijnuhb** [comment]
![image](https://user-images.githubusercontent.com/9735193/192717021-71aec677-9fc3-42fe-ad67-5433e44aaccb.png)

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
