### ISSUE TITLE
启动失败  ERROR DND vid:4, logfd:20, failed to alloc file size:1240465408, reason:No such file or directory

### ISSUE THREAD

**Issue by lovetaitai** [taosdata/TDengine#1701]
04/24 10:51:51.380745 7516 7f88fdc60740 UTL timezone not configured, set to system default: (CST, +0800)
04/24 10:51:51.380862 7516 7f88fdc60740 UTL locale not configured, set to system default:zh_CN.UTF-8
04/24 10:51:51.380886 7516 7f88fdc60740 UTL charset not configured, set to system default:UTF-8
04/24 10:51:51.380958 7516 7f88fdc60740 UTL    taos config & system info:
04/24 10:51:51.380969 7516 7f88fdc60740 UTL ==================================
04/24 10:51:51.380974 7516 7f88fdc60740 UTL  localIp:                10.20.178.206 
04/24 10:51:51.380981 7516 7f88fdc60740 UTL  httpIp:                 0.0.0.0 
04/24 10:51:51.380985 7516 7f88fdc60740 UTL  httpPort:               6020 
04/24 10:51:51.380994 7516 7f88fdc60740 UTL  mgmtShellPort:          6030 
04/24 10:51:51.380998 7516 7f88fdc60740 UTL  vnodeShellPort:         6035 
04/24 10:51:51.381003 7516 7f88fdc60740 UTL  configDir:              /etc/taos 
04/24 10:51:51.381010 7516 7f88fdc60740 UTL  logDir:                 /var/log/taos 
04/24 10:51:51.381014 7516 7f88fdc60740 UTL  scriptDir:              /etc/taos 
04/24 10:51:51.381019 7516 7f88fdc60740 UTL  dataDir:                /var/lib/taos 
04/24 10:51:51.381027 7516 7f88fdc60740 UTL  numOfThreadsPerCore:    1.000000 
04/24 10:51:51.381050 7516 7f88fdc60740 UTL  ratioOfQueryThreads:    0.500000 
04/24 10:51:51.381060 7516 7f88fdc60740 UTL  numOfVnodesPerCore:     8 
04/24 10:51:51.381064 7516 7f88fdc60740 UTL  numOfTotalVnodes:       256 
04/24 10:51:51.381072 7516 7f88fdc60740 UTL  tables:                 200000 
04/24 10:51:51.381076 7516 7f88fdc60740 UTL  cache:                  16384(byte)
04/24 10:51:51.381083 7516 7f88fdc60740 UTL  rows:                   4096 
04/24 10:51:51.381087 7516 7f88fdc60740 UTL  fileBlockMinPercent:    0.050000 
04/24 10:51:51.381095 7516 7f88fdc60740 UTL  ablocks:                4 
04/24 10:51:51.381099 7516 7f88fdc60740 UTL  tblocks:                100 
04/24 10:51:51.381103 7516 7f88fdc60740 UTL  affectedRowsMod:        0 
04/24 10:51:51.381106 7516 7f88fdc60740 UTL  monitorInterval:        30(s)
04/24 10:51:51.381111 7516 7f88fdc60740 UTL  rpcTimer:               300(ms)
04/24 10:51:51.381118 7516 7f88fdc60740 UTL  rpcMaxTime:             600(s)
04/24 10:51:51.381122 7516 7f88fdc60740 UTL  ctime:                  3600(s)
04/24 10:51:51.381130 7516 7f88fdc60740 UTL  statusInterval:         1(s)
04/24 10:51:51.381134 7516 7f88fdc60740 UTL  shellActivityTimer:     3(s)
04/24 10:51:51.381138 7516 7f88fdc60740 UTL  meterMetaKeepTimer:     7200(s)
04/24 10:51:51.381145 7516 7f88fdc60740 UTL  metricMetaKeepTimer:    600(s)
04/24 10:51:51.381149 7516 7f88fdc60740 UTL  maxUsers:               1000 
04/24 10:51:51.381153 7516 7f88fdc60740 UTL  maxDbs:                 1000 
04/24 10:51:51.381160 7516 7f88fdc60740 UTL  maxTables:              650000 
04/24 10:51:51.381164 7516 7f88fdc60740 UTL  maxVGroups:             10000 
04/24 10:51:51.381172 7516 7f88fdc60740 UTL  minSlidingTime:         10(ms)
04/24 10:51:51.381175 7516 7f88fdc60740 UTL  minIntervalTime:        10(ms)
04/24 10:51:51.381180 7516 7f88fdc60740 UTL  maxStreamCompDelay:     20000(ms)
04/24 10:51:51.381187 7516 7f88fdc60740 UTL  maxFirstStreamCompDelay:10000(ms)
04/24 10:51:51.381191 7516 7f88fdc60740 UTL  retryStreamCompDelay:   10(ms)
04/24 10:51:51.381196 7516 7f88fdc60740 UTL  clog:                   1 
04/24 10:51:51.381203 7516 7f88fdc60740 UTL  comp:                   2 
04/24 10:51:51.381207 7516 7f88fdc60740 UTL  days:                   10 
04/24 10:51:51.381212 7516 7f88fdc60740 UTL  keep:                   3650 
04/24 10:51:51.381219 7516 7f88fdc60740 UTL  defaultDB:               
04/24 10:51:51.381223 7516 7f88fdc60740 UTL  defaultUser:            root 
04/24 10:51:51.381228 7516 7f88fdc60740 UTL  sockettype:             udp 
04/24 10:51:51.381235 7516 7f88fdc60740 UTL  compressMsgSize:        -1 
04/24 10:51:51.381239 7516 7f88fdc60740 UTL  maxSQLLength:           65380(byte)
04/24 10:51:51.381245 7516 7f88fdc60740 UTL  timezone:                (CST, +0800) 
04/24 10:51:51.381251 7516 7f88fdc60740 UTL  locale:                 zh_CN.UTF-8 
04/24 10:51:51.381262 7516 7f88fdc60740 UTL  charset:                UTF-8 
04/24 10:51:51.381267 7516 7f88fdc60740 UTL  maxShellConns:          2000 
04/24 10:51:51.381274 7516 7f88fdc60740 UTL  maxMeterConnections:    10000 
04/24 10:51:51.381278 7516 7f88fdc60740 UTL  maxMgmtConnections:     2000 
04/24 10:51:51.381283 7516 7f88fdc60740 UTL  maxVnodeConnections:    10000 
04/24 10:51:51.381290 7516 7f88fdc60740 UTL  minimalLogDirGB:        0.100000(GB)
04/24 10:51:51.381294 7516 7f88fdc60740 UTL  minimalTmpDirGB:        0.100000(GB)
04/24 10:51:51.381302 7516 7f88fdc60740 UTL  minimalDataDirGB:       0.500000(GB)
04/24 10:51:51.381306 7516 7f88fdc60740 UTL  http:                   1 
04/24 10:51:51.381313 7516 7f88fdc60740 UTL  monitor:                1 
04/24 10:51:51.381317 7516 7f88fdc60740 UTL  monitorDbName:          log 
04/24 10:51:51.381322 7516 7f88fdc60740 UTL  httpCacheSessions:      100 
04/24 10:51:51.381329 7516 7f88fdc60740 UTL  httpEnableRecordSql:    0 
04/24 10:51:51.381333 7516 7f88fdc60740 UTL  telegrafUseFieldNum:    0 
04/24 10:51:51.381340 7516 7f88fdc60740 UTL  httpMaxThreads:         2 
04/24 10:51:51.381344 7516 7f88fdc60740 UTL  restfulRowLimit:        10240 
04/24 10:51:51.381348 7516 7f88fdc60740 UTL  httpEnableCompress:     0 
04/24 10:51:51.381355 7516 7f88fdc60740 UTL  numOfLogLines:          10000000 
04/24 10:51:51.381359 7516 7f88fdc60740 UTL  asyncLog:               1 
04/24 10:51:51.381364 7516 7f88fdc60740 UTL  debugFlag:              131 
04/24 10:51:51.381371 7516 7f88fdc60740 UTL  mDebugFlag:             135 
04/24 10:51:51.381375 7516 7f88fdc60740 UTL  dDebugFlag:             131 
04/24 10:51:51.381379 7516 7f88fdc60740 UTL  sdbDebugFlag:           135 
04/24 10:51:51.381386 7516 7f88fdc60740 UTL  rpcDebugFlag:           131 
04/24 10:51:51.381390 7516 7f88fdc60740 UTL  tmrDebugFlag:           131 
04/24 10:51:51.381394 7516 7f88fdc60740 UTL  cDebugFlag:             131 
04/24 10:51:51.381398 7516 7f88fdc60740 UTL  jniDebugFlag:           131 
04/24 10:51:51.381404 7516 7f88fdc60740 UTL  odbcDebugFlag:          131 
04/24 10:51:51.381408 7516 7f88fdc60740 UTL  uDebugFlag:             131 
04/24 10:51:51.381413 7516 7f88fdc60740 UTL  httpDebugFlag:          131 
04/24 10:51:51.381420 7516 7f88fdc60740 UTL  monitorDebugFlag:       131 
04/24 10:51:51.381424 7516 7f88fdc60740 UTL  qDebugFlag:             131 
04/24 10:51:51.381427 7516 7f88fdc60740 UTL  tscEnableRecordSql:     0 
04/24 10:51:51.381434 7516 7f88fdc60740 UTL  enableCoreFile:         0 
04/24 10:51:51.381438 7516 7f88fdc60740 UTL  gitinfo:                326a99b9e3e8e16198cea278cfefcc9f1a880185 
04/24 10:51:51.381446 7516 7f88fdc60740 UTL  gitinfoOfInternal:       
04/24 10:51:51.381450 7516 7f88fdc60740 UTL  buildinfo:              Built by root at 2020-03-03 15:34 
04/24 10:51:51.381515 7516 7f88fdc60740 UTL  version:                1.6.5.6 
04/24 10:51:51.381523 7516 7f88fdc60740 UTL  dataDir:                /var/lib/taos
04/24 10:51:51.381527 7516 7f88fdc60740 UTL  os pageSize:            4096(KB)
04/24 10:51:51.381532 7516 7f88fdc60740 UTL  os openMax:             1024
04/24 10:51:51.381535 7516 7f88fdc60740 UTL  os streamMax:           16
04/24 10:51:51.381539 7516 7f88fdc60740 UTL  os numOfCores:          2
04/24 10:51:51.381543 7516 7f88fdc60740 UTL  os totalDisk:           34.979008(GB)
04/24 10:51:51.381549 7516 7f88fdc60740 UTL  os totalMemory:         3770(MB)
04/24 10:51:51.381557 7516 7f88fdc60740 UTL  os sysname:             Linux
04/24 10:51:51.381563 7516 7f88fdc60740 UTL  os nodename:            CUT
04/24 10:51:51.381567 7516 7f88fdc60740 UTL  os release:             3.10.0-1062.12.1.el7.x86_64
04/24 10:51:51.381573 7516 7f88fdc60740 UTL  os version:             #1 SMP Tue Feb 4 23:02:59 UTC 2020
04/24 10:51:51.381577 7516 7f88fdc60740 UTL  os machine:             x86_64
04/24 10:51:51.381581 7516 7f88fdc60740 UTL ==================================
04/24 10:51:51.381585 7516 7f88fdc60740 DND Server IP address is:10.20.178.206
04/24 10:51:51.381596 7516 7f88fdc60740 DND starting to initialize TDengine ...
04/24 10:51:51.389549 7516 7f88fdc60740 MND starting to initialize TDengine mgmt ...
04/24 10:51:51.390522 7516 7f88fdc60740 MND dnode first access, set total vnodes:256
04/24 10:51:51.424926 7516 7f88fdc60740 MND TDengine mgmt is initialized successfully
04/24 10:51:51.478326 7516 7f88fdc60740 DND vid:0, cache pool is allocated:0x14dfd90
04/24 10:51:51.478566 7516 7f88fdc60740 DND vid:0, commit log is initialized
04/24 10:51:51.478582 7516 7f88fdc60740 DND vid:0, storage initialized, version:204 fileId:1837 numOfFiles:1
04/24 10:51:51.483752 7516 7f88fdc60740 DND vid:1, cache pool is allocated:0x14e0300
04/24 10:51:51.485630 7516 7f88fdc60740 DND vid:1, commit log is initialized
04/24 10:51:51.485655 7516 7f88fdc60740 DND vid:1, storage initialized, version:416 fileId:1837 numOfFiles:1
04/24 10:51:51.491777 7516 7f88fdc60740 DND vid:2, cache pool is allocated:0x14e2d20
04/24 10:51:51.493566 7516 7f88fdc60740 DND vid:2, commit log is initialized
04/24 10:51:51.493595 7516 7f88fdc60740 DND vid:2, storage initialized, version:416 fileId:1837 numOfFiles:1
04/24 10:51:51.498127 7516 7f88fdc60740 DND vid:3, cache pool is allocated:0x1508ae0
04/24 10:51:51.501003 7516 7f88fdc60740 DND vid:3, commit log is initialized
04/24 10:51:51.501029 7516 7f88fdc60740 DND vid:3, storage initialized, version:416 fileId:1837 numOfFiles:1
04/24 10:51:51.506801 7516 7f88fdc60740 DND vid:4, cache pool is allocated:0x1508b50
04/24 10:51:51.506911 7516 7f88fdc60740 ERROR DND vid:4, logfd:20, failed to alloc file size:1240465408, reason:No such file or directory
fallocate failed: No such file or directory
04/24 10:51:51.506995 7516 7f88fdc60740 ERROR DND vid:4, commit log init failed
04/24 10:51:51.507008 7516 7f88fdc60740 ERROR DND vid:4, commit init failed.
04/24 10:51:51.507013 7516 7f88fdc60740 ERROR DND failed to init vnode storage
04/24 10:51:51.507017 7516 7f88fdc60740 ERROR DND TDengine vnodes initialization failed
04/24 10:51:51.507052 7516 7f88fdc60740 HTP http service cleanup
04/24 10:51:51.507064 7516 7f88fdc60740 MON dnode:10.20.178.206 monitor module is stopped
04/24 10:51:51.507069 7516 7f88fdc60740 MON monitor service cleanup
04/24 10:51:51.507073 7516 7f88fdc60740 MON dnode:10.20.178.206 monitor module is stopped
04/24 10:51:51.507160 7516 7f7be7797700 DND vid:0, committing to file, firstKey:1587696711478319 lastKey:1587696288972384 ssid:0 esid:32
04/24 10:51:51.507658 7516 7f7be7797700 DND vid:0, data file:/var/lib/taos/tsdb/vnode0/db/v0f1837.data is opened to write
04/24 10:51:51.508007 7516 7f7be7797700 DND vid:0, committing is over
04/24 10:51:51.517328 7516 7f7be7797700 DND vid:1, committing to file, firstKey:1587696711480 lastKey:1587695587027 ssid:0 esid:100000
04/24 10:51:51.517451 7516 7f7be7797700 ERROR DND vid:1, logfd:3, failed to alloc file size:1240465408, reason:Success
fallocate failed: Success
04/24 10:51:51.544665 7516 7f7be7797700 DND vid:1, data file:/var/lib/taos/tsdb/vnode1/db/v1f1837.data is opened to write
04/24 10:51:51.553325 7516 7f7be7797700 DND vid:1, committing is over
04/24 10:51:51.557689 7516 7f7be7797700 DND vid:2, committing to file, firstKey:1587696711487 lastKey:1587695587027 ssid:0 esid:100000
04/24 10:51:51.582249 7516 7f7be7797700 DND vid:2, data file:/var/lib/taos/tsdb/vnode2/db/v2f1837.data is opened to write
04/24 10:51:51.590796 7516 7f7be7797700 DND vid:2, committing is over
04/24 10:51:51.598069 7516 7f7be7797700 DND vid:3, committing to file, firstKey:1587696711495 lastKey:1587695587027 ssid:0 esid:100000
04/24 10:51:51.624463 7516 7f7be7797700 DND vid:3, data file:/var/lib/taos/tsdb/vnode3/db/v3f1837.data is opened to write
04/24 10:51:51.633208 7516 7f7be7797700 DND vid:3, committing is over
04/24 10:51:51.638434 7516 7f7be7797700 DND vid:4, committing to file, firstKey:1587696711503 lastKey:0 ssid:0 esid:100000
04/24 10:51:51.638473 7516 7f7be7797700 DND vid:4, committing is over

**Comment by lovetaitai** [comment]
先前测试时插入超级表报错TDengine Error: vgroup init failed,后来找配置文件修改了 maxVGroups            10000 后就无法启动了

**Comment by Shawshank-Smile** [comment]
need more information about what did you do when this log arise. If still not work, and my wechat 13720014098 please.

**Comment by lovetaitai** [comment]
我把vnode4对应的数据文件夹整个删除后成功启动了

**Comment by lovetaitai** [comment]
不知道会不会有别的影响

**Comment by Shawshank-Smile** [comment]
This is caused by the damage of DB file.
