### ISSUE TITLE
shall we taosdump out a compressed file ?

### ISSUE THREAD

**Issue by kmijnuhb** [taosdata/TDengine#17014]
导出可以直接导出成压缩文件吗，不然还需要为大文件添加一个1T的硬盘
类似于mongobd的压缩导出，添加一个--gzip就可以实现，100G的数据导出10G

**Comment by kmijnuhb** [comment]
是的，可以导出直接带tag.gz的压缩文件，我现在从2.6升级到3.0，需要先导出2.6的数据，100G的数据库磁盘用量，已经导出了5天，配了200G的云硬盘，到今天显示硬盘用量不足，占了160G，扩容硬盘到300G,有数据平滑从2.6过度到3.0的方法吗

**Comment by sangshuduo** [comment]
taosdump 导出 avro 格式默认是压缩的

**Comment by kmijnuhb** [comment]
好的，谢了
