### ISSUE TITLE
Taosdump error after upgrade TDengine 3.0.1.2

### ISSUE THREAD

**Issue by hellpup** [taosdata/TDengine#17019]
**Bug Description**
Taosdump error after upgrade TDengine 3.0.1.2

**To Reproduce**
1. apt update && apt upgrade 
2. taosdump
3. See error" taosdump: symbol lookup error: taosdump: undefined symbol: inflateReset "

**Environment (please complete the following information):**
 - OS: Debian 11.5
 - 2vCPU 4G memory 18G disk free
 - TDengine Version3.0.1.2

**Comment by sangshuduo** [comment]
Please refer to https://github.com/taosdata/taos-tools/issues/367 see if they are same reason
