### ISSUE TITLE
cluster offline issue

### ISSUE THREAD

**Issue by jadedrip** [taosdata/TDengine#17034]
**Bug Description**
集群服务版本 2.4.0.20，3台
客户端配置的都是
firstEp                  zjiottd01:6030
secondEp                 zjiottd02:6030

做集群的容灾演练，使用 systemctl stop taosd 尝试停止1号服务器，但很长时间服务器无法停止，只能使用 kill -9 才能杀死服务。
这个阶段客户端正常，可以写入及查询。
然后重新启动 zjiottd01 的服务，尝试 systemctl stop taosd 2号服务
仍然长时间无法停止服务
并且客户端无法写入，无法查询，整个集群异常。

（分析是这个时间2号服务器停了一半，但仍然在监听端口，导致其他服务器的请求都没回应？）
PS: 3号机的日志：

09/22 22:12:56.514353 00220877 VND ERROR vgId:50, invalid qId in retrieving result, code:Invalid handle, QInfo:63027495544421277
09/22 22:12:56.514357 00220874 VND ERROR vgId:50, invalid qId in retrieving result, code:Invalid handle, QInfo:63027495544421277
09/22 22:12:56.514405 00220875 VND ERROR vgId:50, invalid qId in retrieving result, code:Invalid handle, QInfo:63027495544421277
09/22 22:12:57.167649 00220876 VND ERROR vgId:16, invalid qId in retrieving result, code:Invalid handle, QInfo:63027495545738173
09/22 22:13:00.448732 00221050 TSC ERROR 0x3, HB, total dnode:3, online dnode:2
09/22 22:13:01.958734 00221050 TSC ERROR 0x3, HB, total dnode:3, online dnode:2
09/22 22:13:03.463728 00221050 TSC ERROR 0x3, HB, total dnode:3, online dnode:2
09/22 22:13:04.968725 00221050 TSC ERROR 0x3, HB, total dnode:3, online dnode:2
09/22 22:13:06.478705 00221050 TSC ERROR 0x3, HB, total dnode:3, online dnode:2
09/22 22:13:07.988738 00221050 TSC ERROR 0x3, HB, total dnode:3, online dnode:2
09/22 22:13:09.493727 00221050 TSC ERROR 0x3, HB, total dnode:3, online dnode:2
09/22 22:13:11.003715 00221050 TSC ERROR 0x3, HB, total dnode:3, online dnode:2
09/22 22:13:12.513714 00221050 TSC ERROR 0x3, HB, total dnode:3, online dnode:2
09/22 22:13:14.018707 00221050 TSC ERROR 0x3, HB, total dnode:3, online dnode:2
09/22 22:13:15.523712 00221050 TSC ERROR 0x3, HB, total dnode:3, online dnode:2
09/22 22:13:17.033751 00221050 TSC ERROR 0x3, HB, total dnode:3, online dnode:2
09/22 22:13:18.543701 00221050 TSC ERROR 0x3, HB, total dnode:3, online dnode:2
09/22 22:13:20.048721 00221050 TSC ERROR 0x3, HB, total dnode:3, online dnode:2
09/22 22:13:20.268647 00220877 VND ERROR vgId:5, invalid qId in retrieving result, code:Invalid handle, QInfo:63027495593026585
09/22 22:13:20.268794 00220874 VND ERROR vgId:7, invalid qId in retrieving result, code:Invalid handle, QInfo:63027495593020435
09/22 22:13:20.269762 00220875 VND ERROR vgId:19, invalid qId in retrieving result, code:Invalid handle, QInfo:63027495593026586
09/22 22:13:20.269945 00220876 VND ERROR vgId:20, invalid qId in retrieving result, code:Invalid handle, QInfo:63027495593028636
09/22 22:13:20.270699 00220877 VND ERROR vgId:22, invalid qId in retrieving result, code:Invalid handle, QInfo:63027495593032735
09/22 22:13:20.271642 00220875 VND ERROR vgId:26, invalid qId in retrieving result, code:Invalid handle, QInfo:63027495593053234

**To Reproduce**
1. 见描述，由于是现网服务器，无法再次验证

**Expected Behavior**

systemctl stop taosd 后，taosd 应该第一时间停止监听端口，并且写完数据后正常停止服务。
某个服务异常不应该导致整个集群无法使用

**Screenshots**

**Environment (please complete the following information):**
 - OS: CentOS 7.6
 - TDengine Version 2.4.0.20

**Additional Context**

**Comment by yu285** [comment]
mnode 是几副本

**Comment by jadedrip** [comment]
mnode 是2副本
服务配置见附件
[taos.zip](https://github.com/taosdata/TDengine/files/9670158/taos.zip)
