### ISSUE TITLE
taosd memory leak

### ISSUE THREAD

**Issue by slylinux** [taosdata/TDengine#17054]
taosd version: 3.0.1.2
when insert data about 1000/s, system meory rise to 3.8G, when stopping data inserts ,about 12 hours later ,no memory release .

![image](https://user-images.githubusercontent.com/2696514/192126621-ea16052e-fe7f-4cdb-af23-793a56b3ba54.png)

**Comment by nibaozhu** [comment]
`echo 3 > /proc/sys/vm/drop_caches`

**Comment by slylinux** [comment]
jemalloc能解决吗

**Comment by yu285** [comment]
jemalloc 可以解决一些非程序泄漏级别的内存回收问题，请稍等一小段时间再尝试，我们正在调整

**Comment by slylinux** [comment]
最新的3.0.1.5还是存在这个问题

**Comment by yu285** [comment]
经过长期的迭代，3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
