### ISSUE TITLE
TAOS_FIELD taos_fetch_fields  returns TAOS_FIELD_E 

### ISSUE THREAD

**Issue by maikebing** [taosdata/TDengine#17057]
**Bug Description**
从 /include/client/taos.h  来看， taos_fetch_fields  返回的是 TAOS_FIELD 类型， 但实际上读取到的数据， 却是按照 TAOS_FIELD_E 返回的72字节。 

**To Reproduce**
 https://www.taosdata.com/assets-download/3.0/TDengine-client-3.0.1.2-Linux-x64.tar.gz
使用其中的动态库进行调用。  
 
 

**Environment (please complete the following information):**
 - OS: tdengine/tdengine:3.0.1.2

 - TDengine Version 3.0.1.2

**Comment by yu285** [comment]
we are checking on this

**Comment by maikebing** [comment]
4字节对齐问题
