### ISSUE TITLE
nmake compilation with error 

### ISSUE THREAD

**Issue by yyt6801** [taosdata/TDengine#17051]
操作系统win10 21H2 
VS2017 
cmake .. -G "NMake Makefiles"    这步正常
最后一步nmake时在进度44%时会出错，报错内容如下：

![image](https://user-images.githubusercontent.com/18433720/192082068-dab71e81-91bb-41f0-bf40-04ce2eb76370.png)

**Comment by yu285** [comment]
we will check it

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
