### ISSUE TITLE
fill use with partiton and interval return unexpected result

### ISSUE THREAD

**Issue by gisakuya** [taosdata/TDengine#17065]
语句1（不带fill）：
select last(val) a, dev, prj, _wstart ts from stest where ts >= '2022-9-26 14:00:00' and ts < '2022-9-26 16:00:00' partition by dev,prj interval(1h) 
返回如下：
![微信截图_20220926152833](https://user-images.githubusercontent.com/12749301/192217876-562253e3-b0da-4371-b4cf-1bd089dba9eb.png)

语句2（带fill）：
 select last(val) a, dev, prj, _wstart ts from stest where ts >= '2022-9-26 14:00:00' and ts < '2022-9-26 16:00:00' partition by dev,prj interval(1h) fill(null) 
返回如下：
![微信截图_20220926152854](https://user-images.githubusercontent.com/12749301/192218205-f34c68a2-fae0-4199-a6e8-0ea4a4a72c57.png)

**Comment by yu285** [comment]
The database  version please～
