### ISSUE TITLE
 invalid operation: column length too long

### ISSUE THREAD

**Issue by whwWu** [taosdata/TDengine#17061]
TDEngine version  2.6.0.4，安装时使用默认配置
现象：创建超级表的列达到601个列（包含tags的列）时，再新建新的列时会提示invalid operation: column length too long
官方文档上标识是可以最多创建4096个列，这边会出现这个问题是系统性能问题还是版本问题？需要怎么解决
![image](https://user-images.githubusercontent.com/28395754/192185388-b2584a83-2501-48f7-a190-e88171844ac6.png)
![image](https://user-images.githubusercontent.com/28395754/192185547-0d340275-7168-4a1d-b318-e33be779afec.png)

**Comment by yu285** [comment]
这是单行长度超过 48 k上限导致的报错
