### ISSUE TITLE
csv

### ISSUE THREAD

**Issue by taoplay** [taosdata/TDengine#1706]
**Performance Issue** 
Any questions related to TDengine's performance can be discussed here.

**Problem Description** 
A clear and concise description of what the problem is.

**To Reproduce**
1. Database parameters used: 
 ```show databases```
2. Verbs used: Insert/Import/Select?
3. Describe the total amount of data
4. Observed performance vs. expected performance

**Screenshots**

**Environment (please complete the following information):**

* OS: [e.g. CentOS 7.0]
* Memory, CPU, current Disk Space
* TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by taoplay** [comment]
问题都没解决，应该不是内存不够的原因。close啥哦


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liuyq-617"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 下午3:40
收件人:&nbsp;"taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送:&nbsp;"小丸子的大哥"<6492553@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [taosdata/TDengine] csv (#1706)





 
Closed #1706.

**Comment by liuyq-617** [comment]
你的关于报错的提问还在那里，我们也会持续关注解决的
