### ISSUE TITLE
TDEngine any log for recording drop database

### ISSUE THREAD

**Issue by SheaHong** [taosdata/TDengine#17079]
项目最近发现有些数据库莫名其妙消失，TDEngine是否有记录删库操作的日志文件供排查

**Comment by SheaHong** [comment]
> 项目最近发现有些数据库莫名其妙消失，TDEngine是否有记录删库操作的日志文件供排查

排查了logs表,如下图的库最后一条数据为创建的记录，但是实际上这个库已经不存在了，请问一下有哪些可能？
![image](https://user-images.githubusercontent.com/18188783/192446627-4777004d-b8c4-408e-b103-732612886d14.png)

**Comment by yu285** [comment]
哪个版本？ 2.x 的话，可以把 wal  文件发来，我们做下解析。

**Comment by SheaHong** [comment]
2.6.0.4的版本，谢谢
[wal0.zip](https://github.com/taosdata/TDengine/files/9661813/wal0.zip)

**Comment by yu285** [comment]
可以加下微信做具体排查 15652223354
