### ISSUE TITLE
grafana could not show data

### ISSUE THREAD

**Issue by pingod** [taosdata/TDengine#17080]
**Bug Description**
grafana 发部分数据无法展示

![image](https://user-images.githubusercontent.com/358093/192424931-aea210ad-ed72-42ca-b1b6-4e9bfd695b6a.png)

**To Reproduce**
1. tdendgine配置文件修改为开启monitor （默认是开启的）
2. 安装grafana tdengine插件
3. 导入grafana dashboard
4. 查看grafana 数据不全
5. 编译安装启动taoskeeper
6. 查看gafana 数据不全
7. 查询tdengine log数据库，发现log.dn这个表没有自动创建（怀疑其他的所有监控数据的表也都没有创建）

**Comment by pingod** [comment]
有点没有明白，通过curl http://localhost:6041/metrics 就可以获取到tdengine监控数据，为什么还需要部署一个taoskeeper,然后通过6043端口来获取tdengine监控数据？

**Comment by yu285** [comment]
https://docs.taosdata.com/reference/tdinsight/

麻烦参考这个在最新版TDengine 运行
