### ISSUE TITLE
Segmentation fault when importing csv data

### ISSUE THREAD

**Issue by taoplay** [taosdata/TDengine#1709]
问题：在import导入6000条数据时可以正常导入，导入13000条数据时出现Segmentation fault。

taos> import into glog7 file glog7000.csv;
Query OK, 6944 row(s) affected (0.014282s)
taos> import into glog7 file glog13000.csv;
Segmentation fault。
表结构如下：CREATE TABLE glog (create_time  timestamp, g_id int,m_id int ) 
TAGS(platformname  binary(20),platformid int );
CREATE TABLE  glog7 USING glog  TAGS ('g7',7);
服务器配置如下：阿里云的硬盘64G，内存2G的ecs服务器。
[root@izwz9heb2y4ywp2r9qze4jz bigdata]# uname -a
Linux izwz9heb2y4ywp2r9qze4jz 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 
15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@izwz9heb2y4ywp2r9qze4jz bigdata]# free -m
              total        used        free      shared  buff/cache   

available
Mem:           1839        1170         574           0          94         

541

[glog.zip](https://github.com/taosdata/TDengine/files/4527788/glog.zip)

**Comment by liuyq-617** [comment]
您对数据导入时的内存做一下监控，初步怀疑时您导入的时候内存不足导致的

**Comment by taoplay** [comment]
taos对内存有哪些具体要求呢，同一机器，mysql导入导出没有这个问题

**Comment by taoplay** [comment]
监视了内存，剩余850m。执行导入13000条记录的语句后，导入了4044条记录，然后出现Segmentation fault。再查内存，剩余846m。应该不是内存问题。而导入的数据文件只有493k。字段才3个，数据很少

**Comment by Aries-Lee1991** [comment]
当出现Segmentation fault时，会生成一个core文件，您需要把这个发到邮箱：yqliu@taosdata.com，注明一下使用的版本，题目备注GitHub-1709.

**Comment by taoplay** [comment]
core文件有80m，发您邮箱了。

**Comment by taoplay** [comment]
换了一台有4g内存的服务器，空闲内存3g，对导入13000条记录而言，应该足够。但还是同样错误

**Comment by taoplay** [comment]
以下是版本：
taos version：  TDengine shell from linux, community client version:1.6.5.7 community server version:1.6.5.7
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

linux version:
Linux izwz9heb2y4ywp2r9qze4jz 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by taoplay** [comment]
一个问题三天都没回复。看了下这上面也没提交多少问题啊。处理速度有点慢。

**Comment by liuyq-617** [comment]
定位出问题了，确实是个bug，在处理csv中重复行的时候会有些问题。您如果自己编译的话，可以拉最新的代码，已经修复了。我们也会在下个版本中修复这个bug。
