### ISSUE TITLE
no data returned while add a select column

### ISSUE THREAD

**Issue by dongtaiyuan** [taosdata/TDengine#17098]
**Bug Description**

here is the table definition of super table: "messagePushData"
             field              |         type         |   length    |   note   |
=================================================================================
 microtimestamp                 | TIMESTAMP            |           8 |          |
 id                             | BIGINT               |           8 |          |
 messagetime                    | VARCHAR              |         128 |          |
 messageid                      | BIGINT               |           8 |          |
 delay                          | BIGINT               |           8 |          |
 srcmessagecontent              | VARCHAR              |        4096 |          |
 translatemessagecontent        | VARCHAR              |        8192 |          |
 messagetypeid                  | BIGINT               |           8 | TAG      |
 appid                          | VARCHAR              |          50 | TAG      |
 channelid                      | BIGINT               |           8 | TAG      |
 messagedirection               | VARCHAR              |          10 | TAG      |
 status                         | VARCHAR              |          10 | TAG      |

when select columns have no column "translateMessageContent", there is one row returned.
taos> select delay, appId, channelId, status from messagePushData where messageId = 1574612208095736100 ;
         delay         |             appid              |       channelid       |   status   |
==============================================================================================
                     1 | c58399a5bd080e5641bd4fa0359... |                     7 | success    |
Query OK, 1 rows in database (0.753000s)

then I add this column to select columns，but no data returned
taos> select delay, translateMessageContent, appId, channelId, status from messagePushData where messageId = 1574612208095736100 ;
Query OK, 0 rows in database (1.198000s)
![image](https://user-images.githubusercontent.com/59045301/192496432-9793b663-ec62-45fb-8585-3d9b90466ccb.png)

**Expected Behavior**
both have data in two same query conditions.

**Screenshots**

**Environment (please complete the following information):**
 - OS: windows10
 - Memory: 16G，CPU：10, current Disk Space：299G total，242G available
 - TDengine Version: 3.0.1.2

**Additional Context**

**Comment by yu285** [comment]
this issue has been fixed in 3.0.1.4 , you could make a test ~
