### ISSUE TITLE
SQL with error in python

### ISSUE THREAD

**Issue by Aismiler** [taosdata/TDengine#17094]
TDengine 版本：2.4.0.26
taospy==2.3.1

执行的sql
```
DROP TABLE IF EXISTS var_id_12175;
CREATE TABLE IF NOT EXISTS `var_id_99` USING `s_vartype_flow` TAGS (12175,"flow");
insert into table_name file 'var_id_12175.csv'
```

报错
![lQLPJxa5mI2uSLzNAkvNBpuwOU_vacSocjoDMSWKrEBMAA_1691_587](https://user-images.githubusercontent.com/21995651/192486419-7728bf63-539f-4b07-8c8b-9617a7d0f183.png)

这个报错是执行第3条插入数据sql的时候报的错，之前还遇到执行第一条sql报错，抛出的异常是一样的，执行这3条sql的时候，对应的表依然有数据写入，数据写入时使用自动建表语法``` insert into var_id_12175 USING `s_vartype_flow` TAGS (12175,"flow") (ts,val) values (1664270533892,999.9) ```

请问这个报错和自动建表有关系吗？如果依然使用自动建表有其他方案解决这个问题吗？需要改成非自动建表吗？

**Comment by yu285** [comment]
insert into table_name file 'var_id_12175.csv'

这个是 taos shell 才有的功能，客户端应用不能用

**Comment by Aismiler** [comment]
insert into table_name file 'var_id_12175.csv'
这条sql语句，经验证，使用python连接器时是可以用不报错并且能够插入数据的，这条语句多次执行会导致这个0x000b: unable to establish connection错误吗？

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
