### ISSUE TITLE
从1.6.0.0版本升级到1.6.1.1后taos身份验证失败

### ISSUE THREAD

**Issue by limitimes** [taosdata/TDengine#171]
![image](https://user-images.githubusercontent.com/680991/61772160-28ea2500-ae24-11e9-9f76-1deca1b24518.png)
![image](https://user-images.githubusercontent.com/680991/61772213-47502080-ae24-11e9-83ca-1d77d95d6a92.png)
验证失败
日志一直显示错误 7f8f0ffd0700 ERROR MON monitor:0x7f8ef00008c0, connect to taosd failed, code:-10
![image](https://user-images.githubusercontent.com/680991/61772266-69e23980-ae24-11e9-9a19-601189e67396.png)

**Comment by limitimes** [comment]
请问是什么原因造成？

**Comment by guanshengliang** [comment]
1.6.1.0相对于1.6.0.0对用户密码进行了加密处理，数据结构发生了变化
您只能是卸载再重新装

**Comment by limitimes** [comment]
明白了

**Comment by uk0** [comment]
密码错误可以删除 user.db 重新启动 默认会是root权限 重新alert 即可
