### ISSUE TITLE
TSZ compression issue

### ISSUE THREAD

**Issue by zbsun-code** [taosdata/TDengine#17103]
您好，我对TDengine的有损压缩部分存在一些疑问：
  1. 为什么3.0版本中TSZ没有了
  2. 在2.6版本中开启TSZ，使用taosBenchmark运行官方插入测试用例insert.json时，为什么fPrecision为1e-5的时候数据文件大小反而大于精度更高的默认设置（1e-8）？

附图：

fPrecision=1e-5：
![2022-09-27_20-23](https://user-images.githubusercontent.com/50181645/192526173-a6985cb8-e675-4f11-bb88-b2c5ceb11c5e.png)

fPrecision=1e-8：
![2022-09-27_20-22](https://user-images.githubusercontent.com/50181645/192526040-b3e82684-782b-4b05-9837-72bfa647a3aa.png)

**Comment by yu285** [comment]
we are checking

**Comment by DuanKuanJun** [comment]
你好 @zbsun-code ，
      我们收到您的反馈后按您的步骤进行了实测验证，测试结果是符合我们设计的预期的，如下是测试结果：
![image](https://user-images.githubusercontent.com/51781608/203519918-31428951-4216-4a42-9af4-b8616ba7799c.png)
     没开TSZ大约在716M左右 ，开了TSZ 默认精度下有 10%以内的文件大小减小，精度设在 1e5 后有5%以内的文件大小减小，这个数据符合我们预期的。
     我们猜测可能是您测量库文件大小的时机可能有问题，准确测试库文件大小需要退出 taosd 后，退出和不退出 taosd 库文件的大小是不一样的，同时 taosBenchmark 每次生成的随机数据，大小也会有一些差别，这个影响因素也要注意。
     欢迎继续使用我们的产品。
