### ISSUE TITLE
spread and  last not compatible with state_window ?

### ISSUE THREAD

**Issue by zzpandaman** [taosdata/TDengine#17126]
taos> SELECT equipment_code, FIRST(utc),  equipment_state FROM tpm.statusevent STATE_WINDOW(equipment_state);
         equipment_code         |       first(utc)        |   equipment_state    |
==================================================================================
 M010-001-01-01-01              | 2022-09-20 10:18:09.000 | 2                    |
 M010-001-01-01-01              | 2022-09-21 10:28:27.000 | 1                    |
 M010-001-01-01-01              | 2022-09-27 02:52:57.000 | 2                    |
 M010-001-01-01-01              | 2022-09-27 02:53:02.000 | 1                    |
 M010-001-01-01-01              | 2022-09-27 16:34:14.160 | 2                    |
Query OK, 5 rows in database (0.025000s)

taos> SELECT equipment_code, FIRST(utc),spread(utc) , equipment_state FROM tpm.statusevent STATE_WINDOW(equipment_state);

DB error: No valid function in window query (0.001000s)

**Comment by zzpandaman** [comment]
![image](https://user-images.githubusercontent.com/38775011/192737666-431d67b1-8cf4-4ea8-8474-ed1028387813.png)
这里看到是能用spread的

**Comment by zzpandaman** [comment]
![image](https://user-images.githubusercontent.com/38775011/192737923-7444614e-1704-4681-9c7c-7471bfff275d.png)
我的用spread last 都不行

**Comment by yu285** [comment]
we will check on this

**Comment by yu285** [comment]
最新版本 3.3.0.0 已经支持 ，欢迎下载体验：
<img width="698" alt="image" src="https://github.com/taosdata/TDengine/assets/74105241/4d481f72-6595-4975-9fca-4593b5f1d7f0">
