### ISSUE TITLE
Segmentation fault while create a stream which already exists

### ISSUE THREAD

**Issue by zaghost** [taosdata/TDengine#17133]
**Bug Description**
I executed a create stream SQL statement in a docker container at the second time, then the container exited because Segmentation fault of taosd process.

**To Reproduce**
1. Start a tdengine  docker container
docker run -d -p 6030:6030 -p 6041:6041 -p 6043-6049:6043-6049 -p 6043-6049:6043-6049/udp tdengine/tdengine
2. Enter the container and follow the the steps in  'https://docs.taosdata.com/develop/stream/' to create db and super table and sub table
3. Execute 'create stream current_stream into current_stream_output_stb as select _wstart as start, _wend as wend, max(current) as max_current from meters where voltage <= 220 interval (5s);'
4. Execute above statement for the second time
5. CLI exit because the container exit.

**Expected Behavior**
Statement failed but container is normal.

**Screenshots**
![0b6edf9bacbb7d0327e6549b4a686f5](https://user-images.githubusercontent.com/8455736/192756492-5a8d0c6a-164b-4713-b302-04b2bf2326c7.png)

**Environment (please complete the following information):**
 - OS: CentOS 7.9
 - Docker Engine: Community 20.10.8,
 - Memory, CPU, current Disk Space
   754G 80C 
   
 - TDengine Version: 3.0.0.1

**Additional Context**

**Comment by yu285** [comment]
应该是已经修复的问题，麻烦清理下数据文件，换到 3.0.1.4 吧

**Comment by zaghost** [comment]
试了下使用3.0.1.4的镜像是正常的
