### ISSUE TITLE
TDengine3 issue: When using driver-go/v3/af to insert near 200,000 data, then client is blocked, no return

### ISSUE THREAD

**Issue by itgirltang** [taosdata/TDengine#17150]

**Comment by yu285** [comment]
the version and detail please

**Comment by itgirltang** [comment]
> the version and detail please
之前使用的是3.0.1.2，现在使用3.0.1.4没有问题了。
之前3.0.1.2插入数据使用func (*af.Connector).Exec(query string, args ...driver.Value) (driver.Result, error)函数，执行十多万条记录后这个函数就不返回了，此时尝试使用taos客户端，可以连接，但是SQL没有反应，一直阻塞。

**Comment by yu285** [comment]
好的，多谢反馈
