### ISSUE TITLE
drop table doesn't release space 

### ISSUE THREAD

**Issue by gaoj-git** [taosdata/TDengine#17166]
现在一个库下面有4张超级表，删除了其中一张超级表，其占用的磁盘空间没有释放，有什么方式可以清除掉这张表占用的磁盘空间

版本：2.6.0.8

**Comment by yu285** [comment]
可以尝试重组

https://docs.taosdata.com/2.6/operation/optimize/#%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96
