### ISSUE TITLE
drop table，The taos storage physical memory has not changed

### ISSUE THREAD

**Issue by Jiang4794** [taosdata/TDengine#17165]
版本：2.6.0.10

![image](https://user-images.githubusercontent.com/59756068/193169548-7840eba3-4381-4b0d-82b9-a9faef5e15be.png)
删除表（表中有一亿的数据）之后，taos存储所占用的物理内存没有变化；

**Comment by yu285** [comment]
需要等待keep 参数生效，或者企业版的在线数据重组功能（compact）
