### ISSUE TITLE
windows failed connect to server， v1.6.5.7

### ISSUE THREAD

**Issue by Alvin4567** [taosdata/TDengine#1716]
错误日志
==================================================
                new log file                      
==================================================
04/26 10:05:58.342000 0x13028 UTL timezone not configured, use default
04/26 10:05:58.357000 0x13028 UTL locale not configured, set to default:Chinese_China.936
04/26 10:05:58.357000 0x13028 UTL charset not configured, set to default:cp936
04/26 10:05:58.357000 0x13028 UTL    taos config & system info:
04/26 10:05:58.357000 0x13028 UTL ==================================
04/26 10:05:58.357000 0x13028 UTL  localIp:                0.0.0.0 
04/26 10:05:58.357000 0x13028 UTL  mgmtShellPort:          6030 
04/26 10:05:58.357000 0x13028 UTL  vnodeShellPort:         6035 
04/26 10:05:58.357000 0x13028 UTL  configDir:              C:/TDengine/cfg 
04/26 10:05:58.357000 0x13028 UTL  logDir:                 C:/TDengine/log 
04/26 10:05:58.357000 0x13028 UTL  scriptDir:              C:/TDengine/script 
04/26 10:05:58.357000 0x13028 UTL  numOfThreadsPerCore:    0.000000 
04/26 10:05:58.357000 0x13028 UTL  affectedRowsMod:        0 
04/26 10:05:58.357000 0x13028 UTL  rpcTimer:               300(ms)
04/26 10:05:58.357000 0x13028 UTL  rpcMaxTime:             600(s)
04/26 10:05:58.357000 0x13028 UTL  shellActivityTimer:     3(s)
04/26 10:05:58.357000 0x13028 UTL  meterMetaKeepTimer:     7200(s)
04/26 10:05:58.357000 0x13028 UTL  metricMetaKeepTimer:    600(s)
04/26 10:05:58.357000 0x13028 UTL  defaultDB:               
04/26 10:05:58.357000 0x13028 UTL  defaultUser:            root 
04/26 10:05:58.357000 0x13028 UTL  sockettype:             udp 
04/26 10:05:58.357000 0x13028 UTL  compressMsgSize:        -1 
04/26 10:05:58.357000 0x13028 UTL  maxSQLLength:           65380(byte)
04/26 10:05:58.357000 0x13028 UTL  timezone:               not configured 
04/26 10:05:58.357000 0x13028 UTL  locale:                 Chinese_China.936 
04/26 10:05:58.357000 0x13028 UTL  charset:                cp936 
04/26 10:05:58.357000 0x13028 UTL  numOfLogLines:          10000000 
04/26 10:05:58.357000 0x13028 UTL  asyncLog:               1 
04/26 10:05:58.357000 0x13028 UTL  debugFlag:              131 
04/26 10:05:58.357000 0x13028 UTL  rpcDebugFlag:           131 
04/26 10:05:58.357000 0x13028 UTL  tmrDebugFlag:           131 
04/26 10:05:58.357000 0x13028 UTL  cDebugFlag:             131 
04/26 10:05:58.357000 0x13028 UTL  jniDebugFlag:           131 
04/26 10:05:58.357000 0x13028 UTL  odbcDebugFlag:          131 
04/26 10:05:58.357000 0x13028 UTL  uDebugFlag:             131 
04/26 10:05:58.357000 0x13028 UTL  qDebugFlag:             131 
04/26 10:05:58.357000 0x13028 UTL  gitinfo:                f83c59e8c4e1a51d33b4f3841e251e5fbf7f2319 
04/26 10:05:58.357000 0x13028 UTL  gitinfoOfInternal:      4cbf1f2c2cee44d99f6b78773e95ee40ce9ffdda 
04/26 10:05:58.357000 0x13028 UTL  buildinfo:              Built by root at 2020-04-04 15:11 
04/26 10:05:58.357000 0x13028 UTL  version:                1.6.5.7 
04/26 10:05:58.357000 0x13028 UTL  dataDir:                C:/TDengine/data
04/26 10:05:58.357000 0x13028 UTL ==================================
04/26 10:06:07.363000 0x11320 ERROR TSC 0000000020863590 reach the max retry:2, code:29
04/26 10:06:07.364000 0x13028 ERROR JNI jobj:000000000312EE60, conn:0000000000000000, connect to database failed, host=39.100.41.195, user=root, dbname=test, port=6030
04/26 10:06:07.366000 0x13028 ERROR JNI jobj:000000000312EDF0, connection is closed

**Comment by Alvin4567** [comment]
linux客户端能访问，Restful API也能访问，就是java connect访问不了

**Comment by liuyq-617** [comment]
https://www.taosdata.com/cn/documentation/connector/#Java-Connector

**Comment by Alvin4567** [comment]
就是按照示例去做的，安装了和server版本一样的客户端
        Class.forName("com.taosdata.jdbc.TSDBDriver");
        String jdbcUrl = "jdbc:TAOS://**************:6030/log?user=root&password=taosdata";
        Connection conn = DriverManager.getConnection(jdbcUrl);

**Comment by Alvin4567** [comment]
> https://www.taosdata.com/cn/documentation/connector/#Java-Connector

就是按照示例去做的，安装了和server版本一样的客户端
Class.forName("com.taosdata.jdbc.TSDBDriver");
String jdbcUrl = "jdbc:TAOS://**************:6030/log?user=root&password=taosdata";
Connection conn = DriverManager.getConnection(jdbcUrl);

**Comment by liuyq-617** [comment]
您JDBC的客户端跑在linux还是Windows上？

**Comment by Alvin4567** [comment]
跑在windows，目前情况是内网ip能访问，外网就不行

**Comment by liuyq-617** [comment]
这还是您的网络问题，优先检查防火墙配置。如果云服务器，再检查安全配置组配置

**Comment by Alvin4567** [comment]
String jdbcUrl = "jdbc:TAOS://172.26.69.82:6030/log"这是我的云服务器的内网ip地址就可以访问，这里写云服务器的外网ip就不行，我的客户端不可能一直跑在内网环境中啊，而且外网使用http访问是没问题的

**Comment by liuyq-617** [comment]
Modify cloud server security configuration group settings
