### ISSUE TITLE
interval query speed issue 

### ISSUE THREAD

**Issue by LuckyHangMei** [taosdata/TDengine#17168]
每6秒存入一个点，查询语句：
select  avg(TagValue) as TagValue  from  TagDataSyncDt  where  time>='2022-08-30 15:24:55' And  time<='2022-09-29 15:24:55' And ( TagName='仪表code') INTERVAL(300s) fill(null)  Group by TagName

第一次查询耗时11336毫秒

之后相同的查询条件查询只要300毫秒，
其实查询出来的数据只有9000多条
为啥第一次这么慢？

**Comment by yu285** [comment]
拉取元数据需要时间。

**Comment by LuckyHangMei** [comment]
元数据在17w左右，同等数据量级。通过influxDb查询很快，Tdengines是否针对这种场景做一下优化，时序数据一个月查询跨度查询还是有的

**Comment by yu285** [comment]
3.0早期版本的问题已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
