### ISSUE TITLE
TDengine ERROR (80000115): Invalid message

### ISSUE THREAD

**Issue by xuqiangUP** [taosdata/TDengine#17187]
版本：3.0.1.3
描述：
本地测试没问题，发布到linux服务器出现该异常，没有使用docker，应用服务跟数据库没在同一台服务器，装了客户端。
![image](https://user-images.githubusercontent.com/45276899/193246277-6bb6dc06-bc86-4632-88e1-9781b635e6de.png)

拜托各位大佬

**Comment by sangshuduo** [comment]
客户端和服务端版本小版本确保严格一致
