### ISSUE TITLE
Restful connect to docker server, port 6041,  return 404 page not found

### ISSUE THREAD

**Issue by cocobase** [taosdata/TDengine#17193]
aws server, tdengine run in docker.
when access server in docker, it is working
docker ps:

2e3874ddab75   tdengine/tdengine   "/tini -- /usr/bin/e…"   44 hours ago   Up 9 minutes   0.0.0.0:6030->6030/tcp, :::6030->6030/tcp, 0.0.0.0:6041->6041/tcp, :::6041->6041/tcp, 0.0.0.0:6043-6049->6043-6049/tcp, :::6043-6049->6043-6049/tcp, 0.0.0.0:6043-6049->6043-6049/udp, :::6043-6049->6043-6049/udp   taoserver

curl http://localhost:6041/rest/root/password

return:
404 page not foun

**Comment by zeje** [comment]
http://<fqdn>:<port>/rest/sql/[db_name]
