### ISSUE TITLE
3.0.1.3 memory increase continuously when inserting data 

### ISSUE THREAD

**Issue by 651016236** [taosdata/TDengine#17192]
version: 3.0.1.3
CREATE DATABASE pos KEEP 180 DURATION 10 BUFFER 10 WAL_LEVEL 1;
涛思数据库貌似不会释放内存
使用golang restful写入数据

**Comment by yu285** [comment]
是 taosadapter 进程内存增长，还是taosd 内存增长呢

**Comment by zeje** [comment]
本地20核64G内存电脑，version: 3.0.1.4，docker部署，restful写入
CREATE DATABASE IF NOT EXISTS tb_test vgroups 20 DURATION 1d KEEP 10d, 10d, 10d
启动时内存：
taosd：126M
taosadapter：106M

应用程序启用压力测试后，模拟15w设备，每个设备每分钟写入几条数据，无查询：
内存：
taosd：1197M
taosadapter：549M

之后，数据量一直在增加，内存也一直在加，我这边压了半天，taosd涨到了2G+

不知道是内存泄露，还是合理的内存增长，这内存用在哪里？

**Comment by yu285** [comment]
vgroups 20 你有 20 个vgroups，这些都要开辟固定大小的缓存，2g是正常的。

**Comment by 651016236** [comment]
> 是 taosadapter 进程内存增长，还是taosd 内存增长呢

taosd一直增长16G内存很快就被占满

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
