### ISSUE TITLE
"Invalid value in client" error occurs while executing "describe" command in command line

### ISSUE THREAD

**Issue by dongtaiyuan** [taosdata/TDengine#17218]
**Bug Description**
"Invalid value in client" error occurs while executing "describe" command in command line

**To Reproduce**
1. execute "create table" statement in command line as below
`create stable if not exists test (
    primaryKey timestamp comment '主键时间戳',
    a nchar(4000),
    b nchar(4000),
    c nchar(4000),
    d nchar(4000)
) tags (
    tag1 varchar(50),
    tag2 bigint,
    tag3 varchar(50)
);`
2. execute "describe test;" statement in command line;
3. See error

**Expected Behavior**
display table structure correctly.

**Screenshots**
![describe error](https://user-images.githubusercontent.com/59045301/194699681-663910a8-d7d0-4fd9-bd71-367e9d9ee347.jpg)

**Environment (please complete the following information):**
 - OS: CentOS 7.0
 - Memory, CPU, current Disk Space
 - TDengine Version: 3.0.1.4

**Additional Context**

**Comment by yu285** [comment]
we will check on this

**Comment by yu285** [comment]
3.0早期版本的bug 都已经全部修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。
