### ISSUE TITLE
DB error: udf pipe connect error

### ISSUE THREAD

**Issue by AdamHouMX** [taosdata/TDengine#17217]
**Bug Description**

**To Reproduce**
1、CREATE FUNCTION l2norm AS "/data/sftp/libl2norm.so" OUTPUTTYPE DOUBLE bufsize 0;
2、select bit_and(voltage, voltage) from d1;
3、DB error: udf pipe connect error (0.006221s)

**Expected Behavior**
udf is not work

**Screenshots**
![图片](https://user-images.githubusercontent.com/23627917/194698651-5e051978-fe50-43c0-8e0f-74257bebb054.png)

**Environment (please complete the following information):**
 - OS: [CentOS 6.9]
 - TDengine Version [e.g. 3.0.1.2]

**Additional Context**

**Comment by yu285** [comment]
could you provide "/data/sftp/libl2norm.so"

**Comment by AdamHouMX** [comment]
GitHub dont support '.so' file type,I change the file 'libl2norm.so' to 'libl2norm.md', is it work?
[libl2norm.md](https://github.com/taosdata/TDengine/files/9744634/libl2norm.md)

**Comment by AdamHouMX** [comment]
> could you provide "/data/sftp/libl2norm.so"

thanks  ,I provide the file.Please see Previous reply,thanks!!!

**Comment by yu285** [comment]
libl2norm.c  also be needed , thank you~

**Comment by AdamHouMX** [comment]
> libl2norm.c also be needed , thank you~
I upload 'l2norm.log' file, GIT dont support '.c', change the file type ,it is the '.c' type file. thanks

**Comment by AdamHouMX** [comment]
原因1：UDFD 服务确保运行
原因2：load faild 确保在Linux 环境下编译
原因3：output type faild 确保在Linux 环境下编译
