### ISSUE TITLE
On dbeaver,  “show database ”or “show tables” shows hexadecimal garble

### ISSUE THREAD

**Issue by xie-jinfen** [taosdata/TDengine#17225]
驱动版本：taos-jdbcdriver-3.0.1-dist.jar
数据库版本：tdengine:3.0.1.0
连接url：jdbc:TAOS-RS://ip:6041
dbeaver连接，输入show tables显示的表名乱码，如performance_schema库显示的表名如下：
706572665F636F6E6E656374696F6E73
706572665F71756572696573
706572665F636F6E73756D657273
706572665F7472616E73
706572665F61707073
实际上应该是：
perf_apps
perf_connections
perf_consumers
perf_queries
perf_trans

![image](https://user-images.githubusercontent.com/15828611/194703801-0e05e7eb-ddbc-499a-a1e2-ef0a9a6b50fa.png)

**Comment by yu285** [comment]
通过 curl 测试下 6041 ，一样的 show databases 看看返回的结果是否正常。

**Comment by xie-jinfen** [comment]
![image](https://user-images.githubusercontent.com/15828611/194739435-c0c915e7-c9aa-4d0f-8943-6abd42e985e5.png)
curl查询表名显示是正常的

**Comment by boomion** [comment]
我也碰到这个问题，请问怎么解决的？

**Comment by yu285** [comment]
新版本的TDengine 和对应的驱动上已经没有这个问题了。
