### ISSUE TITLE
Whether to provide AS function in mysql, query the column not in the table

### ISSUE THREAD

**Issue by wzf55555** [taosdata/TDengine#1722]
查询语句中能否单独指定不存在的列，select '1.4' AS Num from  devtagvalue;
其中 devtagvalue数据库中有该表。指定一个字符串作为查询的列。

**Comment by Alvin4567** [comment]
hello，你的java connector能正常连接么

**Comment by wzf55555** [comment]
> hello，你的java connector能正常连接么

可以啊。

**Comment by liuyq-617** [comment]
We have not yet supported, thank you for your feedback

**Comment by sangshuduo** [comment]
请试用 2.0 版本
