### ISSUE TITLE
syntax of timestamp format 

### ISSUE THREAD

**Issue by zhangkanglei** [taosdata/TDengine#17232]
有没有时间戳格式化的语法,官方文档有timestamp format,但是没有介绍怎么用的,无语.....

**Comment by yu285** [comment]
我们看下，感谢反馈

**Comment by xiao-yu-wang** [comment]
https://docs.taosdata.com/taos-sql/data-type/
“官网文档->数据类型->常量”中有对于时间戳常量的介绍。

**Comment by zhangkanglei** [comment]
我说的格式化是比如我想取到天,2022-05-10这种格式的format

**Comment by zhangkanglei** [comment]
> 我们看下，感谢反馈

好的,多谢

**Comment by zhangkanglei** [comment]
> https://docs.taosdata.com/taos-sql/data-type/ “官网文档->数据类型->常量”中有对于时间戳常量的介绍。

我说的格式化是比如我想取到天,2022-05-10这种格式的format

**Comment by zhangkanglei** [comment]
> 我们看下，感谢反馈

请问有什么进展吗

**Comment by yu285** [comment]
暂时没有自定义的时间格式函数，可以在不同类型时间戳之间调整，受数据库精度设置影响。

**Comment by xiao-yu-wang** [comment]
https://docs.taosdata.com/taos-sql/function/#timetruncate
我们现在有个timetruncate函数，可以按照时间单位对时间戳进行处理。比如按天进行截断，timetruncate(ts, 1d)，结果是形如'2022-05-10 00:00:00.000'格式的时间戳。
