### ISSUE TITLE
The CPU usage exceeds 100% when using the select last (*) statement

### ISSUE THREAD

**Issue by xiao781433561** [taosdata/TDengine#17230]
**select last(*) 语句导致 CPU占用超过100%**
在V3.0.1.2版本，会出现内存泄漏导致进程被杀死的问题，查看升级日之后升级到V3.0.1.4版本:
1. 创建一个数据库 create database history；参数全部未设置采用默认值；
2. 执行语句 select last(*) from history.singledata; taosd CPU占用 140%， 执行时间6秒+；
3. 有个业务基于td，定时执行select last(*) from history.singledata partition by xx ，导致CPU占用390%，此时所有其他查询都极慢；
4. 查阅文档后认为是cachemodel需要设置默认值问题，执行 alter database history cachemodel 'both'之后重启taosd，没有效果
![image](https://user-images.githubusercontent.com/20273462/194735658-ef7aab7e-78fe-4ea6-aaf5-2885896f3878.png)
![image](https://user-images.githubusercontent.com/20273462/194735689-c4564ae7-3da7-4d8b-8776-b56a286814d2.png)
![image](https://user-images.githubusercontent.com/20273462/194735765-d3aba65c-1453-4962-8a08-533f08f41c17.png)
![image](https://user-images.githubusercontent.com/20273462/194735675-604454ac-e88c-49fb-9358-94ee3f33e994.png)

操作系统： CentOS7.9
taos版本：3.0.1.4
服务器硬件：	CPU: 4核 内存: 8GB

**Comment by yu285** [comment]
we will check on this

**Comment by yu285** [comment]
last version we will fix this
