### ISSUE TITLE
Assertion failed java    consumer.poll(Duration.ofMillis(100)) tdengine

### ISSUE THREAD

**Issue by njzhangfei** [taosdata/TDengine#17275]
**Problem Description** 

执行 
				consumer.subscribe(Collections.singletonList(topic));

弹窗报错
Assertion failed java    consumer.poll(Duration.ofMillis(100)) tdengine

![image](https://user-images.githubusercontent.com/42364159/194849985-d214ecfa-77ff-4c12-9388-20333ec6b29e.png)

**Environment (please complete the following information):**

* OS: window10
* Memory, CPU, current Disk Space
* TDengine Version 3.0.1.4

**Comment by yu285** [comment]
we will check on this

**Comment by yu285** [comment]
可以添加微信 15652223354 做具体排查

**Comment by yu285** [comment]
windows 早期问题较多，开源版维护不过来，回收到到企业版重做了。 所以windows版本到了 3.0.7.1 之后就没法再升级了，也没有维护团队支持。所以咱们还是换到 linux 版本再使用，目前最新版为 3.2.3.0。

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
