### ISSUE TITLE
linux connection issue

### ISSUE THREAD

**Issue by liu666-dev** [taosdata/TDengine#17287]
<img width="1711" alt="image" src="https://user-images.githubusercontent.com/59222662/195013174-e49d3a8c-d174-4984-81c2-9258486eeb45.png">

**Comment by yu285** [comment]
版本是？

**Comment by liu666-dev** [comment]
3.0.14版本

**Comment by yu285** [comment]
驱动版本是 3.0.0 么

**Comment by liu666-dev** [comment]
是这个版本

**Comment by yu285** [comment]
看下 url 吧。可以参考我们的 jdbcdemo 。
