### ISSUE TITLE
Database paging query bug

### ISSUE THREAD

**Issue by laihuibiao** [taosdata/TDengine#1728]
**Bug Description**
分页SQL中，包含LIMIT 10 OFFSET 120; OFFSET 为120的时候，报错  

**To Reproduce**
![image](https://user-images.githubusercontent.com/39431599/80330270-4cd90c00-8877-11ea-87ea-341029e2e786.png)
当我在taos命令行中，执行【select create_time,create_by,method,client_ip,class_name,method_name,request_url,params,exception_msg,exception_code,server_ip from log_api.t_log_api where server_ip = "0101040150827073" order by create_time desc LIMIT 10 OFFSET 120;】报错
**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by liuyq-617** [comment]
This is a very old version, please upgrade to the latest version and test again.
