### ISSUE TITLE
为什么超级表的tags个数不能超过6个？

### ISSUE THREAD

**Issue by xinyu7git** [taosdata/TDengine#173]
时序数据库竟然限制tag数量？为什么？

**Comment by guanshengliang** [comment]
TAG数据是常驻内存的，太多会对机器要求过高，所以设置为6

**Comment by pigwing** [comment]
tags其实6个已经非常够用了.1个tags我觉得可以理解成一个维度,2到3个维度对数据的切分已经足够了.目前6个我觉得非常充足了
