### ISSUE TITLE
3.0.0 version springboot error

### ISSUE THREAD

**Issue by ashuai5061** [taosdata/TDengine#17327]
如题

**Comment by yu285** [comment]
需要提供具体的服务端具体版本号，客户端具体版本号，驱动版本号 以及报错信息，连接配置

**Comment by ashuai5061** [comment]
[https://gitee.com/stud619/td-engine.git](url)

**Comment by ashuai5061** [comment]
3.0.0版本,作为springboot默认数据源时,报错:
Cannot determine a dialect for com.benchu.collector.dust.jdbc.MyJdbcTemplate@4052b19f. Please provide a Dialect.

大佬麻烦抽时间看一下.

**Comment by elf2017spring** [comment]
use spring-boot-starter-jdbc
```xml
<!--	<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jdbc</artifactId>
		</dependency>-->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jdbc</artifactId>
		</dependency>
```

**Comment by yu285** [comment]
3.0早期版本问题 都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
