### ISSUE TITLE
Alert 报警模块启动错误

### ISSUE THREAD

**Issue by Alvin4567** [taosdata/TDengine#1732]
启动报警模块报错
04/27 15:53:42.181581 2894086 7f3555c2d700 ERROR UTL can't get card name from ip:39.100.41.119

这是我的配置文件：
{
  "port": 8100,
  "database": "file:alert.db",
  "tdengine": "root:ikingtec@/tcp(127.0.0.1:0)/",
  "log": {
    "level": "production",
    "path": "./alert.log"
  },
  "receivers": {
    "alertManager": "http://127.0.0.1:9093/api/v1/alerts",
    "console": true
  }
}

**Comment by liuyq-617** [comment]
能描述一下您的网络环境吗

**Comment by Alvin4567** [comment]
和服务器在内网环境

**Comment by Alvin4567** [comment]
添加规则之后报这个错误：{"level":"error","ts":1587980256.466861,"caller":"log/log.go:69","msg":"[rule1]: result type is not bool","stacktrace":"github.com/taosdata/alert/utils/log.Errorf\n\t/home/zbm/project/td/community/alert/utils/log/log.go:69\ngithub.com/taosdata/alert/app.(*Alert).refresh\n\t/home/zbm/project/td/community/alert/app/rule.go:130\ngithub.com/taosdata/alert/app.(*Rule).run\n\t/home/zbm/project/td/community/alert/app/rule.go:370\ngithub.com/taosdata/alert/app.runRules.func1.1\n\t/home/zbm/project/td/community/alert/app/rule.go:483"}
