### ISSUE TITLE
 After restarting the Linux Server, some nodes in the cluster failed to start, and the investigation found that the meta-verX file in the /var/lib/taos/mnode/wal directory is empty

### ISSUE THREAD

**Issue by yunf17** [taosdata/TDengine#17337]
I created a cluster of three dnode. Restarted the server last night. But Today I found out that two of them are not working. 
TDengine version is: 3.0.1.4. The operating system version is: CentOS 7.9.2009.
The phenomenon is like this, when it is started, only the words "new log file" appear in the log taosdlog.0. The investigation found that the meta-verx file in /var/lib/taos/mnode/wal became empty.

The related errors and troubleshooting information are as follows：

![service start failed](https://user-images.githubusercontent.com/34063345/195537178-f050dfe5-f629-4d48-8a61-0038945bdf88.jpg)
![taosd_log](https://user-images.githubusercontent.com/34063345/195537207-fe568bf7-d67b-4af4-82d1-e38baeec70f8.jpg)
![meat-verX](https://user-images.githubusercontent.com/34063345/195537227-617fc5dd-59d9-4ca1-b6a9-4f2a446d6ccb.jpg)
![gdb info](https://user-images.githubusercontent.com/34063345/195537250-9928fe4a-e2dd-489f-afc7-62939534ab08.jpg)

**Comment by yu285** [comment]
The bugs in earlier versions of 3.0 have been fixed, but 3.0.2.5 May not be compatible with the current version (3.3.0.0), so it is not possible to upgrade directly. Therefore, it is recommended to redeploy the latest 3.3.0.0, the subsequent upgrade is very convenient, directly install the latest version of the software.

Range of open source version of the operating system support: https://docs.taosdata.com/reference/support-platform/
The bugs from earlier versions of 3.0 have been fixed, but 3.0.2.5 May not be compatible with the current version (3.3.0.0), so it is not possible to upgrade directly. Therefore, it is recommended to redeploy the latest 3.3.0.0, the subsequent upgrade is very convenient, directly install the latest version of the software.

Range of open source version of the operating system support: https://docs.taosdata.com/reference/support-platform/
