### ISSUE TITLE
After 3.0 in's official website to download channels found no ARM32 / for the ARMV7 architecture as well as tuning TDegine - Client. 

### ISSUE THREAD

**Issue by HuoYingCunCunZhang** [taosdata/TDengine#17347]
After 3.0 in's official website to download channels found no ARM32 / for the ARMV7 architecture as well as tuning TDegine - Client. Deb installation package in iot scenario ARM32 application scenario is still a lot of, please consider as soon as possible perfect ARM32 Client installation package download channel。

**Comment by yu285** [comment]
we will release it but not now , it is still in testing status  currently
