### ISSUE TITLE
failed to get fqdn, code:-11, reason:system error

### ISSUE THREAD

**Issue by Amethyst-w** [taosdata/TDengine#17360]
**Bug Description**
failed to get fqdn, code:-11, reason:system error.
单线程实时写入股票行情，出现上述报错，检查发现行情缺失。

**To Reproduce**
`int to_tick_db_async(const instr_price& data)
    {
        std::string tags_instr_id;
        std::string c_tab_sql;
        std::string ins_sql;

        get_tags_instr_id(data.instr_id, tags_instr_id);
        
        get_insert_sql(tags_instr_id, data, ins_sql);
        taos_query_a(db_conn_async_, ins_sql.c_str(), taos_insert_call_back, (void *)(common::date_util::get_nanosecs_since_epoch()));

        return 0;
    }

void taos_insert_call_back(void* param, TAOS_RES* tres, int code)
    {
        unsigned long long* insert_time = (unsigned long long *)param;
        struct timeval systemTime;
        char sql[128];

        if (code < 0) 
        {
        }
        else if (code == 0) 
        {
        }
        else
        {
        }
  
        taos_free_result(tres);
    }`

**Expected Behavior**
写入的行情，确保完整性。

**Screenshots**

**Environment (please complete the following information):**
 - OS : Ubuntu 22.04.1
 - Memory : 128G, CPU : 32, current Disk Space : 系统盘 1T，TDengine data存储是挂载的nas 49T
 - TDengine Version : 3.0.1.2

**Additional Context**

**Comment by yu285** [comment]
请问是单机还是集群

**Comment by Amethyst-w** [comment]
> 请问是单机还是集群

单机

**Comment by yu285** [comment]
可以在 服务端 ulimit -n 600000 ,然后再试下。

应该是异步API导致的，服务端打开句柄遭到瓶颈。
