### ISSUE TITLE
TDengine V3 has no resource limit ?

### ISSUE THREAD

**Issue by f1ynn-zhan9** [taosdata/TDengine#17397]
**Bug Description**

TDengine V3 执行全量查询导致服务器失去响应。
通过 TDengine Version 3.0.1.4 Docker 实例验证。

**To Reproduce**

1. Docker 运行 TDengine Version 3.0.1.4 实例，通过 taosBenchmark 创建测试数据
2. 通过命令行/其他工具连接数据库，然后执行 `SELECT * FROM test.meters;`
3. 服务器卡死、失去响应（SSH 命令行无法响应用户的命令，无法新建 SSH 连接；其他工具即使中断查询也无法让服务器恢复响应；服务器上的 NGINX、MySQL、Java 应用等均无法访问；阿里云监控显示极高的 CPU 使用率和硬盘 IO；腾讯云监控直接空白，无法采集监控数据）
4. 如果 TDengine 的 Docker 实例被自动 killed 掉，则服务器可恢复响应

**Expected Behavior**

即使直接 `SELECT * FROM test.meters;` 也不应该把服务器直接拖垮，导致服务器失去响应。

**Screenshots**

卡死之前最后的 top：
![卡死之前最后的 top](https://user-images.githubusercontent.com/80672942/196107197-f308a2f8-abef-4e05-8ab9-6efda75a8aec.png)
阿里云监控情况：
![阿里云监控情况](https://user-images.githubusercontent.com/80672942/196107171-b482e442-201a-4b99-b529-34f77050c6ce.png)
腾讯云监控情况：
![腾讯云监控情况](https://user-images.githubusercontent.com/80672942/196110113-b4885304-e409-4c56-ad3d-f2227c80b803.png)
docker logs 最后的部分：
![docker logs 最后的部分](https://user-images.githubusercontent.com/80672942/196111021-9a007bca-84d7-4ab1-bdf5-c112a7a0b0ab.png)

**Environment (please complete the following information):**

以下信息基于阿里云环境：
 - OS: CentOS  8.4 64位
 - 4核(vCPU) 16 GiB ESSD云盘 PL0 100GiB (3000 IOPS)
 - TDengine Version 3.0.1.4 Docker 实例

以下信息基于腾讯云环境：
- Debian 11.1 64bit
- CPU: 2核 内存: 2GB 30GB SSD云硬盘
- TDengine Version 3.0.1.4 Docker 实例

**Additional Context**

测试过 Version 2.6.0.18 的 Docker 实例，该版本不存在类似的问题。
在腾讯云轻量应用服务器测试 V3 时，Docker 实例被 killed 之后，服务器恢复响应。

**Comment by f1ynn-zhan9** [comment]
通过观察 htop 的数据，目测是 taosd 耗尽了可用内存导致服务器失去响应。而且在查询结束后，taosd 并未释放内存。
![htop 截图](https://user-images.githubusercontent.com/80672942/196639141-6c085fc5-ba39-4d35-9c8b-61c0a7c0eecf.png)

**Comment by yu285** [comment]
we will check on this
