### ISSUE TITLE
query performance issue 

### ISSUE THREAD

**Issue by hlb1012** [taosdata/TDengine#17405]
**性能问题** 
select * from dl.test001;
查询出100W条数据需要60秒，这个查询速度是不正常的吧。

**问题描述** 
一个超级表下面有大概3千个子表，每个子表200多个FLOAT(4)类型的列，加一个NCHAR(50)的TAG列。
请问是因为我的列过多，影响到了查询效率吗？

**环境、版本**
![cd352f169ddf4b487dc8c1cb1be850b](https://user-images.githubusercontent.com/33746311/196132976-385f4a1b-e136-4623-95cb-509eeb2faf7c.jpg)

![37ea1ca7ef927282241f3caeff74a86](https://user-images.githubusercontent.com/33746311/196134586-a69af801-0e68-442b-963b-055403cd9add.jpg)

**Comment by yu285** [comment]
这个版本已经快两年了，建议使用最新的 2.6.0.22 或者 3.0.1.4

**Comment by hlb1012** [comment]
好的，我升级版本看看效果

**Comment by bkcxiaop** [comment]
请问你升级解决了吗？我都升级到3.0.1.5了问题依旧存在

**Comment by yu285** [comment]
> 请问你升级解决了吗？我都升级到3.0.1.5了问题依旧存在

可以提一个新的issue吗，情况不一定相同

**Comment by hlb1012** [comment]
我还没有升级.

**Comment by hlb1012** [comment]
https://github.com/taosdata/TDengine/issues/17168

我发现一个问题，感觉跟我现在的有点类似，请问元数据拉取慢的这种情况下，我怎么加快查询效率呢？我尝试升级过服务器的cpu与硬盘，好像没有作用。

**Comment by bkcxiaop** [comment]
> > 你解决了吗？我都升级到3.1.5了升级问题依然存在。0.0
> 
> 可以提一个新的问题吗，特殊情况

我已经提了，相关截图再 [#17696](https://github.com/taosdata/TDengine/issues/17696)

**Comment by bkcxiaop** [comment]
> #17168
> 
> 我发现一个问题，感觉跟我现在的有点类似，请问元数据拉取慢的这种情况下，我怎么加快查询效率呢？我尝试升级过服务器的cpu与硬盘，好像没有作用。

我同一台服务器部署了两个docker的tdengine。分别时2.6.跟3.0.1.5.。2.6的数据量比3.X的数据量大很多。 我觉得跟服务器硬件没得关系

**Comment by bkcxiaop** [comment]
> > > 你解决了吗？我都升级到3.1.5了升级问题依然存在。0.0
> > 
> > 
> > 可以提一个新的问题吗，特殊情况
> 
> 我已经提了，相关截图再 [#17696](https://github.com/taosdata/TDengine/issues/17696)

哦，不好意思，我跟他的确实不一样。我的时2.X快。3.X慢。
