### ISSUE TITLE
mybatis-plus create table issue

### ISSUE THREAD

**Issue by ctrl1109** [taosdata/TDengine#17404]
![image](https://user-images.githubusercontent.com/101610374/196131505-d7cb8869-9004-4be3-9127-70e503c13e6c.png)

**Comment by yu285** [comment]
https://github.com/taosdata/TDengine/tree/main/examples/JDBC/mybatisplus-demo

**Comment by yu285** [comment]
您试过这个demo没

**Comment by ctrl1109** [comment]
测试了很久，好像是和mybatis-plus的多租户插件有冲突。
即使我用了@InterceptorIgnore(tenantLine = "true") 忽略多租户过滤，但是它刚启动后还是要我调用一次，报错一次过后 
就能正常使用。不太理解为什么非要我错一次才能正常用....

**Comment by ctrl1109** [comment]
> 您试过这个demo没

试了  demo里没问题，但是整合到一个我们的项目当中的时候，每次重新启动项目，mapper当中的每个建表建库的方法 第一次调用的时候会报截图这个错，错过一次以后， 后面就正常了调用了
