### ISSUE TITLE
same query return different result

### ISSUE THREAD

**Issue by 13612858893** [taosdata/TDengine#17429]
Version:2.2.2.11
相同条件下查询到的数据行数不一致
如图所示，查询条件为：select fcutterchangeprogramdebug,fproject,fcutterno,fmachineid from  t_cnc_lhoee  where _c0='2022-10-18 10:41:00';时数据为3826行
![b15f339bd33d4c1ebd8bef517a3256d](https://user-images.githubusercontent.com/111417004/196340546-186c3ddc-6377-40d4-ac7f-eb929c719887.png)
而显示的字段增加了factivatingtype后，发现数据只有7行，这里数据展示3826行的先查询，而数据展示7行的后查询，故不存在事后写入的现像
![6dd7d5980118d875ca82916edcf6369](https://user-images.githubusercontent.com/111417004/196340778-31075025-c671-4604-8ec2-b3ce75989c5b.png)
有空帮忙看一下，谢谢

**Comment by yu285** [comment]
https://www.taosdata.com/engineering/10222.html

可以按照这个先升级一下到2.6.0.22 您这个版本比较久了
