### ISSUE TITLE
同一个设备的两个属性值分成两个超级表后 想同时查出这个设备的两种历史数据

### ISSUE THREAD

**Issue by zhuangQingGuang** [taosdata/TDengine#1743]
需求：查出这个设备的两种历史属性值分页展示。
通过tag关联查询提示 timestamp join condition missing
` select * from stable1,stable2 where stable1.tag= stable1.tag`
目前这种join好象必须用ts作为条件。
` select * from stable1,stable2 where stable1.tag= stable1.tag and stable1.ts= stable1.ts`
上面这条sql不满足需求
想要得到不同时间的历史数据有什么好的办法吗。

**Comment by Shawshank-Smile** [comment]
This function will be enhanced very soon.

**Comment by korimas** [comment]
@Shawshank-Smile 这个问题关了，是已经支持了吗？
