### ISSUE TITLE
tag update issue

### ISSUE THREAD

**Issue by 13612858893** [taosdata/TDengine#17431]
Version:2.2.2.11
数据结构如图所示，针对fcutterchangeprogramdebug字段，写入的是2，读取到的是1
![1666070232859](https://user-images.githubusercontent.com/111417004/196341945-4a198943-f931-4440-a704-e6422807935a.png)
![1666070274157](https://user-images.githubusercontent.com/111417004/196341959-15fdab21-a84e-455d-89af-5c823f7f9b48.png)
![1666070288987](https://user-images.githubusercontent.com/111417004/196341982-30586aac-f361-4cf8-985d-319c2de0cc62.png)
![1666070303199](https://user-images.githubusercontent.com/111417004/196341999-3ffb1856-0176-4daa-bb08-53ccc2a4c2e6.png)
做了数据的写入，然后查询时发现fcutterchangeprogramdebug写入的是2，读取到的是1
![f22be10f6567efa1c683b6441ac4ead](https://user-images.githubusercontent.com/111417004/196342113-40896df3-039d-4d15-9626-e16515051606.png)
有空帮忙看一下，谢谢

**Comment by yu285** [comment]
建议直接升级到最新的 2.6.0.22 。这个版本太旧了

**Comment by yu285** [comment]
此外，你这个是正常现象。 

在 TDengine 中，tag的更新不是通过insert 来完成的。

**Comment by 13612858893** [comment]
明白了，这是表名不能重复的问题所致
















在 2022-10-18 13:37:22，"Yu Chen" ***@***.***> 写道：

此外，你这个是正常现象。

在 TDengine 中，tag的更新不是通过insert 来完成的。
