### ISSUE TITLE
TSC haven't acquire lock after spin xxx times.

### ISSUE THREAD

**Issue by yyiscoming** [taosdata/TDengine#1746]
问题描述：库中已创建好10w的测点表，模拟测点值每秒变化一次，故每秒会有10w个测点的值需要保存到各自的表中。为了达到秒级，我使用多线程，每2w个的测点数据为一个线程，故开启5个线程连接到数据库并存库。

出现问题：命令行一直出现“TSC haven't acquire lock after spin xxx times.”。

tdengine是否对客户端的连接方式有什么严格的要求，或者我在服务器端有什么需要配置，来解决这个问题。

注：客服端使用C#，使用一段时间后，xxx数值变的很大，数据无法插入。

**Comment by Shawshank-Smile** [comment]
Thoses threads should not use the same conn, and you'd better not use more than one thread to write the same table.

**Comment by yyiscoming** [comment]
> Thoses threads should not use the same conn, and you'd better not use more than one thread to write the same table.

Each thread uses one connection, but the above problems still occur.

**Comment by Shawshank-Smile** [comment]
and my wechat 13720014098
