### ISSUE TITLE
last row query issue

### ISSUE THREAD

**Issue by jokewwww** [taosdata/TDengine#17491]
![image](https://user-images.githubusercontent.com/49227858/196681751-a421c648-4002-4e38-9f9e-817a7f776b18.png)
![image](https://user-images.githubusercontent.com/49227858/196681831-15fff94a-045c-4066-ab16-4c2054b88bef.png)
![image](https://user-images.githubusercontent.com/49227858/196681901-c8d026af-7456-43a4-9b9d-e04197912d03.png)

**Comment by yu285** [comment]
数据库完整版本号是？

**Comment by jokewwww** [comment]
> 

3.0.0.1

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/

如果还有类似问题可以加微信 a15652223354
