### ISSUE TITLE
source <filename>报错Error in `taos': malloc(): memory corruption: 0x00007f2e08036500

### ISSUE THREAD

**Issue by Yuanmu93** [taosdata/TDengine#175]
SQL 脚本是MySQL里面导出来的，在taos里面创建了一个新数据库，然后source，报错：
---
`
*** Error in taos': malloc(): memory corruption: 0x00007f2e08036500 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f2e1a3737e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8213e)[0x7f2e1a37e13e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7f2e1a380184]
/lib/x86_64-linux-gnu/libc.so.6(regcomp+0x57)[0x7f2e1a3e41e7]
taos(regex_match+0x4d)[0x414159]
taos(shellRunCommand+0x29)[0x413af1]
taos(source_file+0x217)[0x415bda]
taos(shellRunCommand+0x354)[0x413e1c]
taos(shellLoopQuery+0x125)[0x4130db]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f2e1abde6ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f2e1a4033dd]
======= Memory map: ========
00400000-004c8000 r-xp 00000000 fd:01 324854                             /usr/local/taos/bin/taos
006c7000-006c8000 r--p 000c7000 fd:01 324854                             /usr/local/taos/bin/taos
006c8000-006cd000 rw-p 000c8000 fd:01 324854                             /usr/local/taos/bin/taos
006cd000-006df000 rw-p 00000000 00:00 0 
02061000-02120000 rw-p 00000000 00:00 0                                  [heap]
7f2df4000000-7f2df4021000 rw-p 00000000 00:00 0 
7f2df4021000-7f2df8000000 ---p 00000000 00:00 0 
7f2dfc000000-7f2dfc022000 rw-p 00000000 00:00 0 
7f2dfc022000-7f2e00000000 ---p 00000000 00:00 0 
7f2e00000000-7f2e00021000 rw-p 00000000 00:00 0 
7f2e00021000-7f2e04000000 ---p 00000000 00:00 0 
7f2e04000000-7f2e04021000 rw-p 00000000 00:00 0 
7f2e04021000-7f2e08000000 ---p 00000000 00:00 0 
7f2e08000000-7f2e08058000 rw-p 00000000 00:00 0 
7f2e08058000-7f2e0c000000 ---p 00000000 00:00 0 
7f2e0c000000-7f2e0c021000 rw-p 00000000 00:00 0 
7f2e0c021000-7f2e10000000 ---p 00000000 00:00 0 
7f2e108af000-7f2e108c5000 r-xp 00000000 fd:01 1180169                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f2e108c5000-7f2e10ac4000 ---p 00016000 fd:01 1180169                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f2e10ac4000-7f2e10ac5000 rw-p 00015000 fd:01 1180169                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f2e10ac5000-7f2e10af3000 rw-p 00000000 00:00 0 
7f2e10af3000-7f2e10af4000 ---p 00000000 00:00 0 
7f2e10af4000-7f2e112f4000 rw-p 00000000 00:00 0 
7f2e112f4000-7f2e112ff000 r-xp 00000000 fd:01 1185247                    /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f2e112ff000-7f2e114fe000 ---p 0000b000 fd:01 1185247                    /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f2e114fe000-7f2e114ff000 r--p 0000a000 fd:01 1185247                    /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f2e114ff000-7f2e11500000 rw-p 0000b000 fd:01 1185247                    /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f2e11500000-7f2e11506000 rw-p 00000000 00:00 0 
7f2e11506000-7f2e11511000 r-xp 00000000 fd:01 1185250                    /lib/x86_64-linux-gnu/libnss_nis-2.23.so
7f2e11511000-7f2e11710000 ---p 0000b000 fd:01 1185250                    /lib/x86_64-linux-gnu/libnss_nis-2.23.so
7f2e11710000-7f2e11711000 r--p 0000a000 fd:01 1185250                    /lib/x86_64-linux-gnu/libnss_nis-2.23.so
7f2e11711000-7f2e11712000 rw-p 0000b000 fd:01 1185250                    /lib/x86_64-linux-gnu/libnss_nis-2.23.so
7f2e11712000-7f2e11728000 r-xp 00000000 fd:01 1185243                    /lib/x86_64-linux-gnu/libnsl-2.23.so
7f2e11728000-7f2e11927000 ---p 00016000 fd:01 1185243                    /lib/x86_64-linux-gnu/libnsl-2.23.so
7f2e11927000-7f2e11928000 r--p 00015000 fd:01 1185243                    /lib/x86_64-linux-gnu/libnsl-2.23.so
7f2e11928000-7f2e11929000 rw-p 00016000 fd:01 1185243                    /lib/x86_64-linux-gnu/libnsl-2.23.so
7f2e11929000-7f2e1192b000 rw-p 00000000 00:00 0 
7f2e1192b000-7f2e11933000 r-xp 00000000 fd:01 1185256                    /lib/x86_64-linux-gnu/libnss_compat-2.23.so
7f2e11933000-7f2e11b32000 ---p 00008000 fd:01 1185256                    /lib/x86_64-linux-gnu/libnss_compat-2.23.so
7f2e11b32000-7f2e11b33000 r--p 00007000 fd:01 1185256                    /lib/x86_64-linux-gnu/libnss_compat-2.23.so
7f2e11b33000-7f2e11b34000 rw-p 00008000 fd:01 1185256                    /lib/x86_64-linux-gnu/libnss_compat-2.23.so
7f2e11b34000-7f2e11c9e000 rw-p 00000000 00:00 0 
7f2e11c9e000-7f2e11c9f000 ---p 00000000 00:00 0 
7f2e11c9f000-7f2e127fd000 rw-p 00000000 00:00 0 
7f2e127fd000-7f2e127fe000 ---p 00000000 00:00 0 
7f2e127fe000-7f2e12ffe000 rw-p 00000000 00:00 0 
7f2e12ffe000-7f2e12fff000 ---p 00000000 00:00 0 
7f2e12fff000-7f2e137ff000 rw-p 00000000 00:00 0 
7f2e137ff000-7f2e13800000 ---p 00000000 00:00 0 
7f2e13800000-7f2e14000000 rw-p 00000000 00:00 0 
7f2e14000000-7f2e14021000 rw-p 00000000 00:00 0 
7f2e14021000-7f2e18000000 ---p 00000000 00:00 0 
7f2e18020000-7f2e18021000 ---p 00000000 00:00 0 
7f2e18021000-7f2e18821000 rw-p 00000000 00:00 0 
7f2e18821000-7f2e18822000 ---p 00000000 00:00 0 
7f2e18822000-7f2e19022000 rw-p 00000000 00:00 0 
7f2e19022000-7f2e19023000 ---p 00000000 00:00 0 
7f2e19023000-7f2e19823000 rw-p 00000000 00:00 0 
7f2e19823000-7f2e19afb000 r--p 00000000 fd:01 273615                     /usr/lib/locale/locale-archive
7f2e19afb000-7f2e19afc000 ---p 00000000 00:00 0 
7f2e19afc000-7f2e1a2fc000 rw-p 00000000 00:00 0 
7f2e1a2fc000-7f2e1a4bc000 r-xp 00000000 fd:01 1185266                    /lib/x86_64-linux-gnu/libc-2.23.so
7f2e1a4bc000-7f2e1a6bc000 ---p 001c0000 fd:01 1185266                    /lib/x86_64-linux-gnu/libc-2.23.so
7f2e1a6bc000-7f2e1a6c0000 r--p 001c0000 fd:01 1185266                    /lib/x86_64-linux-gnu/libc-2.23.so
7f2e1a6c0000-7f2e1a6c2000 rw-p 001c4000 fd:01 1185266                    /lib/x86_64-linux-gnu/libc-2.23.so
7f2e1a6c2000-7f2e1a6c6000 rw-p 00000000 00:00 0 
7f2e1a6c6000-7f2e1a6cd000 r-xp 00000000 fd:01 1185252                    /lib/x86_64-linux-gnu/librt-2.23.so
7f2e1a6cd000-7f2e1a8cc000 ---p 00007000 fd:01 1185252                    /lib/x86_64-linux-gnu/librt-2.23.so
7f2e1a8cc000-7f2e1a8cd000 r--p 00006000 fd:01 1185252                    /lib/x86_64-linux-gnu/librt-2.23.so
7f2e1a8cd000-7f2e1a8ce000 rw-p 00007000 fd:01 1185252                    /lib/x86_64-linux-gnu/librt-2.23.so
7f2e1a8ce000-7f2e1a9d6000 r-xp 00000000 fd:01 1185261                    /lib/x86_64-linux-gnu/libm-2.23.so
7f2e1a9d6000-7f2e1abd5000 ---p 00108000 fd:01 1185261                    /lib/x86_64-linux-gnu/libm-2.23.so
7f2e1abd5000-7f2e1abd6000 r--p 00107000 fd:01 1185261                    /lib/x86_64-linux-gnu/libm-2.23.so
7f2e1abd6000-7f2e1abd7000 rw-p 00108000 fd:01 1185261                    /lib/x86_64-linux-gnu/libm-2.23.so
7f2e1abd7000-7f2e1abef000 r-xp 00000000 fd:01 1185249                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7f2e1abef000-7f2e1adee000 ---p 00018000 fd:01 1185249                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7f2e1adee000-7f2e1adef000 r--p 00017000 fd:01 1185249                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7f2e1adef000-7f2e1adf0000 rw-p 00018000 fd:01 1185249                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7f2e1adf0000-7f2e1adf4000 rw-p 00000000 00:00 0 
7f2e1adf4000-7f2e1ae1a000 r-xp 00000000 fd:01 1185244                    /lib/x86_64-linux-gnu/ld-2.23.so
7f2e1ae28000-7f2e1b008000 rw-p 00000000 00:00 0 
7f2e1b00f000-7f2e1b010000 rw-p 00000000 00:00 0 
7f2e1b010000-7f2e1b017000 r--s 00000000 fd:01 272890                     /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
7f2e1b017000-7f2e1b019000 rw-p 00000000 00:00 0 
7f2e1b019000-7f2e1b01a000 r--p 00025000 fd:01 1185244                    /lib/x86_64-linux-gnu/ld-2.23.so
7f2e1b01a000-7f2e1b01b000 rw-p 00026000 fd:01 1185244                    /lib/x86_64-linux-gnu/ld-2.23.so
7f2e1b01b000-7f2e1b01c000 rw-p 00000000 00:00 0 
7ffc9ab60000-7ffc9ab81000 rw-p 00000000 00:00 0                          [stack]
7ffc9abbd000-7ffc9abbf000 r--p 00000000 00:00 0                          [vvar]
7ffc9abbf000-7ffc9abc1000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Segmentation fault
`

## 是否是不支持其他数据库的 SQL 备份脚本的导入？

**Comment by guanshengliang** [comment]
TDengine和Mysql的语法近似，但是不能完全兼容
数据模型也完全不同，您需要自己写代码实现导入

**Comment by Yuanmu93** [comment]
嗯嗯，好的，谢谢
