### ISSUE TITLE
update the tag value error, report: 'Unable to establish connection' or 'Database not ready'.

### ISSUE THREAD

**Issue by Lao-Zhong** [taosdata/TDengine#17519]
**Bug Description**
Some tables failed to update the tag value content, report: 'Unable to establish connection' or 'Database not ready'.
Double check that the database is running properly and that the sub-tables created by the supertable are also running properly.

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/39207755/196874440-aad6c8f4-0ce6-4386-ad9c-74000c8214f4.png)
![image](https://user-images.githubusercontent.com/39207755/196874550-75735d26-1f53-4fbb-aab0-5811e5c9c260.png)

**Environment (please complete the following information):**
 - OS: [Windows10, Ubuntu18.04]
 - TDengine Version 2.6.0.14

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
