### ISSUE TITLE
The server bandwidth is used up in a short period of time (about 2 hours)

### ISSUE THREAD

**Issue by aricc** [taosdata/TDengine#17540]
**Performance Issue** 
短时间内（约2小时）会把服务器带宽占满

**Problem Description** 
一台应用服务器，一台TDengine服务器。程序运行在应用服务器，刚启动没问题，CPU占用，带宽占用都正常。但两者，特别是带宽，会在程序启动15分钟之后开始，在2个小时15分钟的时间内占满2M带宽。
检查过网络使用情况，带宽就是被这两台服务器之间的连接占用的。应用服务器和终端的连接流量很小。

**Screenshots**
![微信图片_20221021051954](https://user-images.githubusercontent.com/1269692/197060887-360681b3-75c8-43fe-8fb8-b48615b80632.jpg)

<img width="583" alt="Snipaste_2022-10-21_05-31-18" src="https://user-images.githubusercontent.com/1269692/197062754-174ac218-1f28-4ef2-bdd0-0bb06a118d55.png">

**Environment (please complete the following information):**

* 应用服务器Windows+.net 6。TDengine服务器 CentOS
* TDengine Version [3.0]

**Comment by yu285** [comment]
您已经知道了问题原因，建议把您的心得发现整理放在这里，让大家也了解一下。

**Comment by aricc** [comment]
问题确实已经解决了，原因如下：
问题解决前，我的做法是，用一个单例对象在程序启动时连接TDengine，并一直持有Connection，在需要写入数据时，直接从这个单例对象获取数据库连接，并写入数据。
后来实在没办法，我在服务器上安装了抓包工具，发现每次提交数据时，数据包中都包含了大量很早时间前的已经写入的数据。我就想到是不是因为没有一个“提交”动作，TDengine客户端认为之前发送的数据没有执行成功，导致其每次都是把累积的insert语句全部执行一遍，这才导致了带宽的迅速上升？同时也在看官方连接器相关文档中的示例代码，Insert之后有一个Close动作，还有一个CleanUp动作。
我就修改了代码，不再在程序启动时连接TDengine了，每次需要操作TDengine的时候创建数据库连接，写入或查询数据，然后立即关闭连接，并CleanUp。
但观察发现只能写入一次，后面就写入不了了。
我就把最后的CleanUp去掉，只保留Close。
然后就可以正常的写入数据了，随后跟踪观察了2个小时，带宽一直在几十Kb/s的正常水平，问题解决。

另外 ，上面的问题，不只是带宽被占满，还有以下的并发症：
1、CPU使用率也会在一定时间内（比带宽占满用的时间长一点，大约是3、4个小时）达到95%以上。
2、TDengine客户端安装目录下的log目录会以极高的速度打印在短时间内打印出超大的日志，每个日志文件可达800~900M左右。日志内容清一色的是“QRY WARN Acquire sch job failed,may be dropped jobid:0x0”
代码调整后，以上问题也都不存在了。

总结：
我觉得在数据库的使用说明上还不够详细。包括Connector的示例代码。不需要Commit就可以成功写入数据 ，就导致我认为TDengine是自动提交的。但没想到客户端并没有这么认为。
今天我对比了官网的示例代码与Github的示例代码，Github上的对CleanUp和FreeResult操作是有注释解释的，但官网没有。
如果像Github的示例代码一样，在每一步操作上作一个简短的说明，解释一下每一步这么做的目的、不做的后果，也就不会这样的事了。

疑问：
1、为什么一定要Close？或者是否有其它的操作可以替代Close，从而不用每次操作数据库都要创建连接，关闭连接？
2、如果确实就是要每次都Close，那这样高频的创建连接、关闭连接，不会影响性能和写入效率吗？

**Comment by aricc** [comment]
好的已经整理发布




 
发件人： Yu Chen
发送时间： 2022-10-23 18:59
收件人： taosdata/TDengine
抄送： Aricc Liu; Author
主题： Re: [taosdata/TDengine] 短时间内（约2小时）会把服务器带宽占满 (Issue #17540)
您已经知道了问题原因，建议把您的心得发现整理放在这里，让大家也了解一下。
