### ISSUE TITLE
taosd: /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/libs/executor/src/executil.c:464: getColInfoResult: Assertion `tag' failed.

### ISSUE THREAD

**Issue by fanhuafeng** [taosdata/TDengine#17578]
**Bug Description**
TDengine服务进程崩溃，docker后台报错如下：
(taosd: /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/libs/executor/src/executil.c:464: getColInfoResult: Assertion `tag' failed.)

**To Reproduce**
1. 建超级表
taos> CREATE TABLE meters (ts timestamp, current float, voltage int) TAGS (location binary(64), groupdId int);
Query OK, 0 of 0 rows affected (0.009227s)
taos>
taos> CREATE TABLE d1001 USING meters TAGS ("Beijing.Chaoyang", 2);
Query OK, 0 of 0 rows affected (0.006592s)
taos>
taos> desc d1001;
             field              |         type         |   length    |   note   |
=================================================================================
 ts                             | TIMESTAMP            |           8 |          |
 current                        | FLOAT                |           4 |          |
 voltage                        | INT                  |           4 |          |
 location                       | VARCHAR              |          64 | TAG      |
 groupdid                       | INT                  |           4 | TAG      |
Query OK, 5 rows in database (0.002096s)

taos>
taos> insert into d1001 values (now,1.0,210);
Query OK, 1 of 1 rows affected (0.003007s)

taos> insert into d1001 values (now,1.0,212);
Query OK, 1 of 1 rows affected (0.002282s)

taos> insert into d1001 values (now,1.0,213);
Query OK, 1 of 1 rows affected (0.002118s)

taos> insert into d1001 values (now,1.0,214);
Query OK, 1 of 1 rows affected (0.002799s)
taos> select * from d1001;
           ts            |       current        |   voltage   |
===============================================================
 2022-10-23 07:54:41.636 |              1.00000 |         220 |
 2022-10-23 07:54:53.425 |              1.00000 |         210 |
 2022-10-23 07:54:55.942 |              1.00000 |         212 |
 2022-10-23 07:54:57.978 |              1.00000 |         213 |
 2022-10-23 07:54:59.862 |              1.00000 |         214 |
 2022-10-23 07:55:02.173 |              1.00000 |         215 |
 2022-10-23 07:55:08.204 |              1.00000 |         216 |
 2022-10-23 07:55:10.435 |              1.00000 |         217 |
 2022-10-23 07:55:13.030 |              1.00000 |         218 |
 2022-10-23 07:55:15.093 |              1.00000 |         219 |
 2022-10-23 07:55:18.994 |              1.00000 |         220 |
 2022-10-23 07:55:20.815 |              1.00000 |         221 |
 2022-10-23 07:55:23.203 |              1.00000 |         222 |
 2022-10-23 07:55:25.156 |              1.00000 |         223 |
 2022-10-23 07:55:27.087 |              1.00000 |         224 |
 2022-10-23 07:55:28.900 |              1.00000 |         225 |
 2022-10-23 07:55:30.997 |              1.00000 |         226 |
 2022-10-23 07:55:33.066 |              1.00000 |         227 |
 2022-10-23 07:55:35.393 |              1.00000 |         228 |
 2022-10-23 07:55:37.965 |              1.00000 |         229 |
 2022-10-23 07:55:41.056 |              1.00000 |         230 |
Query OK, 21 rows in database (0.004878s)
taos> select avg(voltage) from  power.meters;
       avg(voltage)        |
============================
             225.290322581 |
Query OK, 1 rows in database (0.007296s)
taos> select avg(voltage) from  power.meters where location='Beijing.Chaoyang';
----此时涛思引擎崩溃
0/23 08:04:50.241980 00000069 MND information_schema table:information_schema.ins_grants, start to retrieve meta
10/23 08:04:54.510793 00000069 MND stb:1.power.meters, start to retrieve meta
taosd: /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/libs/executor/src/executil.c:464: getColInfoResult: Assertion `tag' failed.
Aborted (core dumped)

**Comment by fanhuafeng** [comment]
10/23 08:04:22.935018 00000048 UTL default      timezone                 Etc/UTC (UTC, +0000)
10/23 08:04:22.935132 00000048 UTL default      locale                   en_US.UTF-8
10/23 08:04:22.935148 00000048 UTL default      charset                  UTF-8
10/23 08:04:22.935158 00000048 UTL default      enableCoreFile           1
10/23 08:04:22.935192 00000048 UTL default      numOfCores               4.00
10/23 08:04:22.935206 00000048 UTL default      openMax                  1048576
10/23 08:04:22.935218 00000048 UTL default      streamMax                16
10/23 08:04:22.935229 00000048 UTL default      pageSizeKB               4
10/23 08:04:22.935237 00000048 UTL default      totalMemoryKB            8155424
10/23 08:04:22.935247 00000048 UTL default      os sysname               Linux
10/23 08:04:22.935285 00000048 UTL default      os nodename              68f3e6d72e81
10/23 08:04:22.935293 00000048 UTL default      os release               4.19.76-linuxkit
10/23 08:04:22.935303 00000048 UTL default      os version               #1 SMP Thu Oct 17 19:31:58 UTC 2019
10/23 08:04:22.935311 00000048 UTL default      os machine               x86_64
10/23 08:04:22.935321 00000048 UTL default      version                  3.0.1.5
10/23 08:04:22.935356 00000048 UTL default      compatible_version       3.0.0.0
10/23 08:04:22.935368 00000048 UTL default      gitinfo                  d58f7a62f72e95161068c2fa9c9cd22cbb018129
10/23 08:04:22.935376 00000048 UTL default      buildinfo                Built at 2022-10-19 17:06

**Comment by fanhuafeng** [comment]
docker info
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 45
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.778GiB
 Name: docker-desktop
 ID: 4HFV:2QWL:OMFC:HQO5:AMUF:DEEJ:46GP:KNFA:CVFZ:6EK4:CN57:X2DS
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 77
  Goroutines: 87
  System Time: 2022-10-23T09:16:50.4895269Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://pamm78gl.mirror.aliyuncs.com/
 Live Restore Enabled: false
 Product License: Community Engine

**Comment by fanhuafeng** [comment]
经测试，只要location的值为“**Beijing.Chaoyang**"，系统就会崩溃，其他的字符串都均正常使用。好像“Beijing.Chaoyang”是个不能用的关键字？

**Comment by fanhuafeng** [comment]
**Beijing.Chaoyan**

**Comment by fanhuafeng** [comment]
把数据库删除，重新建超级表和子表，居然就好了！

**Comment by yu285** [comment]
> 经测试，只要location的值为“**Beijing.Chaoyang**"，系统就会崩溃，其他的字符串都均正常使用。好像“Beijing.Chaoyang”是个不能用的关键字？

请问是稳定能复现这个crash 吗
