### ISSUE TITLE
TDengine 3.0.1.2，  subscribe topic. 

### ISSUE THREAD

**Issue by 15222883082** [taosdata/TDengine#17587]
环境 python 3.7  TDengine 3.0.1.2  taospy==2.6.4
目前订阅TDengine 数据存在几点问题：
1.创建超级表设置为ns，订阅得到的时间戳为None.  默认创建超级表就可以 订阅获取到，默认时间为毫秒
2.二种订阅方式，通过poll 订阅，订阅数据过多就会自动停止，报错 Process finished with exit code -1073740791 (0xC0000409)，在其它python环境电脑也是存在此问题。

import taos
from taos.tmq import *
import time

#
conn = taos.connect(host="192.168.1.114",
                    port=6030,
                    user="root",
                    password="taosdata")
#
print("init")
conn.execute("drop topic if exists topic_instr_ctb_column")
# 创建支持纳秒
conn.execute("create database if not exists py_tmq1 PRECISION 'ns'  vgroups 2")
conn.select_db("py_tmq1")

conn.execute("create stable if not exists meters (ts timestamp, c1 int, c2 float, c3 binary(10)) tags(t1 int)")

print("create topic")
conn.execute("drop topic if exists topic_instr_ctb_column")
conn.execute("create topic if not exists topic_instr_ctb_column as select *,tbname from meters")

print("create topic")
conn.execute("drop topic if exists topic_ctb_column")
conn.execute(
    "create topic if not exists topic_ctb_column as select *,tbname from meters"
)

print("build consumer")
conf = TaosTmqConf()
conf.set("group.id", "tg2")
conf.set("td.connect.user", "root")
conf.set("td.connect.pass", "taosdata")
conf.set("enable.auto.commit", "true")

def tmq_commit_cb_print(tmq, resp, offset, param=None):
    print(f"commit: {resp}, tmq: {tmq}, offset: {offset}, param: {param}")

conf.set_auto_commit_cb(tmq_commit_cb_print, None)
tmq = conf.new_consumer()

print("build topic list")

topic_list = TaosTmqList()
topic_list.append("topic_instr_ctb_column")

print("basic consume loop")
tmq.subscribe(topic_list)

sub_list = tmq.subscription()

print("subscribed topics: ", sub_list)

# 此方式消费消费数据多时，报错 Process finished with exit code -1073740791 (0xC0000409)
while True:
    res = tmq.poll(1000)
    if res:
        topic = res.get_topic_name()
        vg = res.get_vgroup_id()
        db = res.get_db_name()
        print(f"topic: {topic}\nvgroup id: {vg}\ndb: {db}")
        for row in res:
            # 在消费时,获取的时间为None，只有在设置ns时，才会有，创建database时，默认不会。
            print(row)

# 这种消费如何订阅多个topic？
# consumer = TaosConsumer('topic_instr_ctb_column', group_id='tg2')
# conf = TaosTmqConf()
# conf.set("group.id", "tg2")
# conf.set("td.connect.user", "root")
# conf.set("td.connect.pass", "taosdata")
# conf.set("enable.auto.commit", "true")
# conf.set("msg.with.table.name", "true")
# for res in consumer:
#     for row in res:
#         print(row)

**Comment by cosmic-jc** [comment]
ns精度问题已解决，将在3.0.1.6版本修复

**Comment by 15222883082** [comment]
请问订阅后，python消费多笔数据后，出现异常，这个问题有重现到吗？

**Comment by cosmic-jc** [comment]
异常是指？错误码是什么？
