### ISSUE TITLE
通过jdbc，插入数据，通过超级表形式创建表。会导致可以将数据表名设置为数字开头

### ISSUE THREAD

**Issue by yz4322gly** [taosdata/TDengine#176]
通过jdbc，插入数据，通过超级表形式创建表。会导致可以将数据表名设置为数字开头,例如  1 这样的表名。却不能通过drop table 1；进行删除，因为表名不合法。这样导致超级表也无法删除。

**Comment by plum-lihui** [comment]
不好意思，这是一个bug，我们正在处理中。修复后，再通知您更新。抱歉！

**Comment by pigwing** [comment]
@yz4322gly 用cli也存在这情况,估计不是jdbc问题,你可以尝试不用数字开头,是否可以drop,我昨天在shell也发现数字开头的问题

**Comment by plum-lihui** [comment]
这个bug已经修复，请下载更新源码，再编译测试。 多谢！

**Comment by hjxilinx** [comment]
> @yz4322gly 用cli也存在这情况,估计不是jdbc问题,你可以尝试不用数字开头,是否可以drop,我昨天在shell也发现数字开头的问题

抱歉，只能通过删库的方式来处理，我们现在已经修复了这个漏洞。
