### ISSUE TITLE
Solve JDBC error 'no taos in java.library.path '

### ISSUE THREAD

**Issue by RazorWang** [taosdata/TDengine#17600]
**Bug Description**

使用 mac 系统进行开发,虽然已经安装了 Mac 版 Client,但任然遇到'java.lang.UnsatisfiedLinkError : no taos in java.library.path'报错

官网文档给出了 不完整的 解决办法,
[常见问题](https://docs.taosdata.com/connector/java/#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Solution**
Java的Extensions目录添加软连接

` ln -s /usr/local/lib/libtaos.dylib /Library/Java/Extensions/libtaos.dylib`

**Environment (please complete the following information):**
 - OS: MacOS 
 - TDengine Version 3.0.1.5 

**Additional Context**
TDengine3.0 版本对Mac 支持自 3.0.1.5 开始

**Comment by kuainaiyang** [comment]
@yu285  希望官方文档更新一下。https://docs.taosdata.com/connector/java/#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by sangshuduo** [comment]
可以在命令行 java 后加 -Djava.library.path=/usr/local/lib 来指定寻找共享库的路径

**Comment by evenson419** [comment]
> 可以在命令行 java 后加 -Djava.library.path=/usr/local/lib 来指定寻找共享库的路径

<img width="545" alt="image" src="https://user-images.githubusercontent.com/35451163/212053584-3a2d173e-0fe8-4775-bc88-551ad673f43b.png">

**Comment by a1424132610** [comment]
希望官方可以更新一下文档,出现了问题就一脸懵逼的

**Comment by yu285** [comment]
FAQ 上有解决方案

**Comment by zosoftware** [comment]
添加了软链还是无效，启动指定 -Djava.library.path=/usr/local/lib 也是无效，啥原因啊

**Comment by zosoftware** [comment]
现在就windows是正常的，mac依旧报错
