### ISSUE TITLE
ERROR failed to execute redoActions since:Unable to establish connection, code:0x8000000b

### ISSUE THREAD

**Issue by YANGQINZ** [taosdata/TDengine#17608]
![b17c0b8ce1ef8dfd4ec4403c0648d97](https://user-images.githubusercontent.com/46222003/197495233-453bd675-9b89-4078-a14f-962b98cfe6b6.jpg)
使用docker-compose集群配置
版本：3.0.1.4
节点之间可以ping和telnet成功
![image](https://user-images.githubusercontent.com/46222003/197495457-b95f702a-b42c-423a-9a86-9e8c04c0e037.png)
两个节点之间的status也是ready
请问一下这个怎么解决，感谢

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/

如果还有类似问题可以加微信 a15652223354
