### ISSUE TITLE
DB error: Unable to establish connection While execute transaction

### ISSUE THREAD

**Issue by YANGQINZ** [taosdata/TDengine#17607]
![微信图片_20221024172704](https://user-images.githubusercontent.com/46222003/197494465-6dc43554-769d-4be2-a0cd-f97652f8c728.jpg)
![image](https://user-images.githubusercontent.com/46222003/197494582-0b236f00-6828-462a-8abb-20353935ec96.png)
![image](https://user-images.githubusercontent.com/46222003/197494709-1f0f4458-a211-4420-98db-a8396983f45f.png)
我想问一下我在创建库的时候报了一个这个问题，我show databases时又能看到这个库的存在，我使用use指定库的时候又报DB error: Database not exist这个错

**Comment by yu285** [comment]
hi ，可以加微信 15652223354 做下具体排查 。

**Comment by qianxitutu** [comment]
> hi ，可以加微信 15652223354 做下具体排查 。

解决了吗？也遇到类似问题
