### ISSUE TITLE
Unsupported stream query issue --3.0 version

### ISSUE THREAD

**Issue by huguirongcoco** [taosdata/TDengine#17633]
下面的情况是bug还是写法问题？
单独使用语句能查询
![微信图片_20221025164134](https://user-images.githubusercontent.com/54303908/197726746-e20841a2-c490-4b0d-8c5c-36c5c089058d.jpg)
创建流式计算却显示Unsupported stream query
![微信图片_20221025164251](https://user-images.githubusercontent.com/54303908/197727137-68d7624f-5d3c-4217-80a8-e1ad76fcd578.jpg)

**Comment by yu285** [comment]
3.0早期版本的问题已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
