### ISSUE TITLE
mac connection issue

### ISSUE THREAD

**Issue by xingcun** [taosdata/TDengine#17635]
**Bug Description**

failed to get fqdn, code:8, reason:nodename nor servname provided, or not known
Welcome to the TDengine Command Line Interface, Client Version:3.0.1.5
Copyright (c) 2022 by TDengine, all rights reserved.

**Comment by yu285** [comment]
I guess your hostname not configured in hosts file

you could run :   hostname 

then check if the result of hostname exist in /etc/hosts

**Comment by xingcun** [comment]
> 
host 配置
`192.168.0.62  0cd066e2a2d7`

taos配置
`firstEp                   0cd066e2a2d7:6030`
`fqdn                0cd066e2a2d7`

**Comment by yu285** [comment]
还是不行吗，可以加微信 15652223354 做具体排查

**Comment by kingylhq** [comment]
mac安装遇到同样的问题，链接不了，老铁，可否帮忙看看呢

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/

如果还有类似问题可以加微信 a15652223354
