### ISSUE TITLE
Upgrade and install 1.6.5.6 in linux system, suggesting that the version is not compatible

### ISSUE THREAD

**Issue by hexuejian** [taosdata/TDengine#1764]
this is centos system
./install.sh:行302: 10#compatible_version: 数值太大不可为算数进制的基 （错误符号是 "10#compatible_version"）
./install.sh:行306: 10#compatible_version: 数值太大不可为算数进制的基 （错误符号是 "10#compatible_version"）
Version incompatible

**Comment by liuyq-617** [comment]
For the time being, TDengine server only supports installation on Linux systems using systemd as the service manager. To check if your system has systemd, use the which command.
which systemd
If the systemd command is not found, please install from source code.
