### ISSUE TITLE
taosd: /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/tsdb/tsdbReaderWriter.c:1150: tsdbReadBlockDataImpl: Assertion `pBlockCol->type == pColData->type' failed. Aborted (core dumped)

### ISSUE THREAD

**Issue by zeje** [taosdata/TDengine#17652]
版本：3.0.1.5（docker）

测试压力测试后，查询单张子表的数据，taos进程直接停止。

taosd: /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/tsdb/tsdbReaderWriter.c:1150: tsdbReadBlockDataImpl: Assertion `pBlockCol->type == pColData->type' failed.
Aborted (core dumped)

create DATABASE `db` 
BUFFER 256 
CACHEMODEL 'last_row' 
COMP 2 
DURATION 1h 
WAL_FSYNC_PERIOD 30000 
MAXROWS 8192 
MINROWS 100 
KEEP 366d,366d,366d 
PAGES 512 
PAGESIZE 16 
precision 'ms' 
REPLICA 1 
STRICT 'off' 
WAL_LEVEL 1 
VGROUPS 20 
SINGLE_STABLE 0

**Comment by zeje** [comment]
查询语句：
![38a77a9f1ccf8b3435159851593248c](https://user-images.githubusercontent.com/10680634/197971626-5a96aeaa-be1c-45ec-8a5e-f50939119b19.png)

**Comment by zeje** [comment]
因为我这边的界面只有统计总数需求的并发，业务代码进行了调整，只查总数，不再查询第一条。若发现需要查询第一条，语句进行了更改：
select * from loctube.event_tdengine_status_999999100032361  order by _ts desc limit 1 offset 0
调整为：
select LAST_ROW from loctube.event_tdengine_status_999999100032361

减少了order by _ts desc limit 1 offset 0的查询，目前能够有效避免对问题的触发。

但是作为一个产品，建议优化以避免此问题的产生。

**Comment by yu285** [comment]
收到，我们处理下

**Comment by yu285** [comment]
您可以加我微信 15652223354 ，我们拉个群处理下。

**Comment by zeje** [comment]
感谢陈玉的指导，通过远程协助，目前问题确认为docker镜像中的问题，切换到宿主主机可以正常运行。
[eview202210271433.txt](https://github.com/taosdata/TDengine/files/9876556/eview202210271433.txt)
