### ISSUE TITLE
connection error: JNI ERROR (2354): Ref is not there

### ISSUE THREAD

**Issue by muyu1285** [taosdata/TDengine#17667]
![image](https://user-images.githubusercontent.com/24862395/197941492-d187d312-9727-4d60-8a9b-99f7f3adfbff.png)

[TDengine JNI问题.docx](https://github.com/taosdata/TDengine/files/9866396/TDengine.JNI.docx)

测试代码地址：https://jxtd-1306668909.cos.ap-shanghai.myqcloud.com/temp/tdengine-test.7z

**Comment by yu285** [comment]
please add rpcForceTCP 1 in taos.cfg both client and server side.

then try again
