### ISSUE TITLE
A consumer cannot unsubscribe after an abnormal consumption

### ISSUE THREAD

**Issue by q49105280** [taosdata/TDengine#17668]
**Bug Description**
版本：3.0.1.5
![cc5eddfb0e542577ed1ce035d3cd648](https://user-images.githubusercontent.com/23735234/197942382-f13c5445-b474-474a-88f9-c38a21451af5.png)

**To Reproduce**
[使用go3.0驱动里的示例](https://github.com/taosdata/driver-go/tree/3.0/examples/tmq)

![1666762289585](https://user-images.githubusercontent.com/23735234/197942768-e3f25824-3ff9-479e-b8a7-b534e37d199c.png)
消费异常后，查询到多个消费者。且无法删除。
![image](https://user-images.githubusercontent.com/23735234/197942880-91fa4658-e6d2-45a4-8d62-9ee0bd800d95.png)

这些消费者怎么删除呢？

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 -  CentOS 7.0
 - Memory 8G , CPU, 500G
 - TDengine Version 3.0.1.5

**Comment by cosmic-jc** [comment]
这里只是记录该consumer是异常退出，不影响后续功能

**Comment by q49105280** [comment]
我处理完异常，能删除consumer吗？

**Comment by cosmic-jc** [comment]
暂时没有删除的方法

**Comment by yu285** [comment]
3.0早期版本的问题已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
