### ISSUE TITLE
Failed to start TDengine server service.

### ISSUE THREAD

**Issue by keephunny** [taosdata/TDengine#17670]
**Bug Description**
[A clear and concise description of what the bug is.](taosd: /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/libs/tdb/src/db/tdbBtree.c:196: tdbBtreeInsert: Assertion `0' failed.)

10/26 14:47:35.820775 00003989 VND vgId:3, commit-cb is excuted, fsm:0x7fe8e8187cf0, index:473474, term:2, msg-index:473474, weak:0, code:0, state:102 leader, type:submit
10/26 14:47:35.820787 00003988 VND vgId:2, commit-cb is excuted, fsm:0x7fe8f018e520, index:8, term:2, msg-index:8, weak:0, code:0, state:102 leader, type:submit
10/26 14:47:35.820813 00003988 VND vgId:2, commit-cb is excuted, fsm:0x7fe8f018e520, index:9, term:2, msg-index:9, weak:0, code:0, state:102 leader, type:submit
10/26 14:47:35.820811 00003989 VND vgId:3, commit-cb is excuted, fsm:0x7fe8e8187cf0, index:473475, term:2, msg-index:473475, weak:0, code:0, state:102 leader, type:submit
10/26 14:47:35.820834 00003988 VND vgId:2, commit-cb is excuted, fsm:0x7fe8f018e520, index:10, term:2, msg-index:10, weak:0, code:0, state:102 leader, type:submit
10/26 14:47:35.820849 00003989 VND vgId:3, commit-cb is excuted, fsm:0x7fe8e8187cf0, index:473476, term:2, msg-index:473476, weak:0, code:0, state:102 leader, type:submit
10/26 14:47:35.820854 00003988 VND vgId:2, commit-cb is excuted, fsm:0x7fe8f018e520, index:11, term:2, msg-index:11, weak:0, code:0, state:102 leader, type:submit
10/26 14:47:35.820874 00003988 VND vgId:2, commit-cb is excuted, fsm:0x7fe8f018e520, index:12, term:2, msg-index:12, weak:0, code:0, state:102 leader, type:vnode-create-stb
10/26 14:47:35.820884 00003989 VND vgId:3, commit-cb is excuted, fsm:0x7fe8e8187cf0, index:473477, term:2, msg-index:473477, weak:0, code:0, state:102 leader, type:submit
10/26 14:47:35.820894 00003988 VND vgId:2, commit-cb is excuted, fsm:0x7fe8f018e520, index:13, term:2, msg-index:13, weak:0, code:0, state:102 leader, type:vnode-create-stb
10/26 14:47:35.820916 00003988 VND vgId:2, commit-cb is excuted, fsm:0x7fe8f018e520, index:14, term:2, msg-index:14, weak:0, code:0, state:102 leader, type:vnode-create-stb
10/26 14:47:35.820917 00003989 VND vgId:3, commit-cb is excuted, fsm:0x7fe8e8187cf0, index:473478, term:2, msg-index:473478, weak:0, code:0, state:102 leader, type:submit
10/26 14:47:35.820935 00003988 VND vgId:2, commit-cb is excuted, fsm:0x7fe8f018e520, index:15, term:2, msg-index:15, weak:0, code:0, state:102 leader, type:vnode-drop-stb
10/26 14:47:35.820949 00003989 VND vgId:3, commit-cb is excuted, fsm:0x7fe8e8187cf0, index:473479, term:2, msg-index:473479, weak:0, code:0, state:102 leader, type:submit
10/26 14:47:35.820957 00003988 VND vgId:2, commit-cb is excuted, fsm:0x7fe8f018e520, index:16, term:2, msg-index:16, weak:0, code:0, state:102 leader, type:vnode-create-stb
10/26 14:47:35.820979 00003988 VND vgId:2, commit-cb is excuted, fsm:0x7fe8f018e520, index:17, term:2, msg-index:17, weak:0, code:0, state:102 leader, type:vnode-alter-stb
10/26 14:47:35.820984 00003989 VND vgId:3, commit-cb is excuted, fsm:0x7fe8e8187cf0, index:473480, term:2, msg-index:473480, weak:0, code:0, state:102 leader, type:submit
10/26 14:47:35.821001 00003988 VND vgId:2, commit-cb is excuted, fsm:0x7fe8f018e520, index:18, term:2, msg-index:18, weak:0, code:0, state:102 leader, type:vnode-alter-stb
10/26 14:47:35.821033 00003989 VND vgId:3, commit-cb is excuted, fsm:0x7fe8e8187cf0, index:473481, term:2, msg-index:473481, weak:0, code:0, state:102 leader, type:submit
10/26 14:47:35.821047 00003988 VND vgId:2, commit-cb is excuted, fsm:0x7fe8f018e520, index:19, term:2, msg-index:19, weak:0, code:0, state:102 leader, type:vnode-alter-stb
10/26 14:47:35.821202 00003988 VND vgId:2, commit-cb is excuted, fsm:0x7fe8f018e520, index:20, term:2, msg-index:20, weak:0, code:0, state:102 leader, type:vnode-alter-stb
10/26 14:47:35.821205 00003989 VND vgId:3, commit-cb is excuted, fsm:0x7fe8e8187cf0, index:473482, term:2, msg-index:473482, weak:0, code:0, state:102 leader, type:submit
10/26 14:47:35.821228 00003988 VND vgId:2, commit-cb is excuted, fsm:0x7fe8f018e520, index:21, term:2, msg-index:21, weak:0, code:0, state:102 leader, type:vnode-alter-stb
10/26 14:47:35.821243 00003989 VND vgId:3, commit-cb is excuted, fsm:0x7fe8e8187cf0, index:473483, term:2, msg-index:473483, weak:0, code:0, state:102 leader, type:submit
10/26 14:47:35.821249 00003988 VND vgId:2, commit-cb is excuted, fsm:0x7fe8f018e520, index:22, term:2, msg-index:22, weak:0, code:0, state:102 leader, type:create-table
10/26 14:47:35.821268 00003988 VND vgId:2, commit-cb is excuted, fsm:0x7fe8f018e520, index:23, term:2, msg-index:23, weak:0, code:0, state:102 leader, type:drop-table
10/26 14:47:35.821278 00003989 VND vgId:3, commit-cb is excuted, fsm:0x7fe8e8187cf0, index:473484, term:2, msg-index:473484, weak:0, code:0, state:102 leader, type:submit
10/26 14:47:35.821285 00003988 VND vgId:2, commit-cb is excuted, fsm:0x7fe8f018e520, index:24, term:2, msg-index:24, weak:0, code:0, state:102 leader, type:create-table
10/26 14:47:35.821305 00003988 VND vgId:2, commit-cb is excuted, fsm:0x7fe8f018e520, index:25, term:2, msg-index:25, weak:0, code:0, state:102 leader, type:drop-table
10/26 14:47:35.821319 00003989 VND vgId:3, commit-cb is excuted, fsm:0x7fe8e8187cf0, index:473485, term:2, msg-index:473485, weak:0, code:0, state:102 leader, type:submit
10/26 14:47:35.821323 00003988 VND vgId:2, commit-cb is excuted, fsm:0x7fe8f018e520, index:26, term:2, msg-index:26, weak:0, code:0, state:102 leader, type:create-table
10/26 14:47:35.821343 00003988 VND vgId:2, commit-cb is excuted, fsm:0x7fe8f018e520, index:27, term:2, msg-index:27, weak:0, code:0, state:102 leader, type:create-table
10/26 14:47:35.821358 00003989 VND vgId:3, commit-cb is excuted, fsm:0x7fe8e8187cf0, index:473486, term:2, msg-index:473486, weak:0, code:0, state:102 leader, type:submit
10/26 14:47:35.821361 00003988 VND vgId:2, commit-cb is excuted, fsm:0x7fe8f018e520, index:28, term:2, msg-index:28, weak:0, code:0, state:102 leader, type:drop-table
taosd: /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/libs/tdb/src/db/tdbBtree.c:196: tdbBtreeInsert: Assertion `0' failed.
10/26 14:47:35.821400 00003989 VND vgId:3, commit-cb is excuted, fsm:0x7fe8e8187cf0, index:473487, term:2, msg-index:473487, weak:0, code:0, state:102 leader, type:submit
10/26 14:47:35.821439 00003989 VND vgId:3, commit-cb is excuted, fsm:0x7fe8e8187cf0, index:473488, term:2, msg-index:473488, weak:0, code:0, state:102 leader, type:submit

**Comment by yu285** [comment]
Hi the TDengine  version please ?
