### ISSUE TITLE
Query Stable‘s Table

### ISSUE THREAD

**Issue by wang182** [taosdata/TDengine#17682]
**Is your feature request related to a problem? Please describe.**
我现在使用去删除一个超级表的时候。会把超级表下的所有子表都删除

**Describe your desired behavior**
如果超级表下有子表，会删除超级表失败

**Describe your solutions/suggestions if you've any**
是否有语句可以查询超级表下的子表数量？

**Additional context**

**Comment by wang182** [comment]
2.6.0,之前也试过，可以删除

Yu Chen ***@***.***> 于2022年11月9日周三 16:11写道：

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
