### ISSUE TITLE
Test program source code link 404

### ISSUE THREAD

**Issue by leyi-bc** [taosdata/TDengine#17693]
**Performance Issue** 
Any questions related to TDengine's performance can be discussed here.

**Problem Description** 
Comparison test between TDengine and OpenTSDB
https://www.taosdata.com/engineering/621.html
Test program source code link 404,How do I get the latest links to test?

**Additional Context** 
The link cannot be accessed:  https://github.com/taosdata/tests/tree/master/comparisonTest/dataGenerator

**Comment by sangshuduo** [comment]
Please use https://github.com/taosdata/TDengine/tree/2.6/tests/comparisonTest
