### ISSUE TITLE
performance issue between 2.x and 3.x

### ISSUE THREAD

**Issue by bkcxiaop** [taosdata/TDengine#17696]
![6cb5cf7a1a921056819dda02fd74cd1](https://user-images.githubusercontent.com/116776928/198176848-70448929-b996-429f-83e0-1ac2ba81fabe.jpg)
相同得机器上，部署再docker上。查询性能相差10倍，3.X数据越多查询时间越长。

**Comment by bkcxiaop** [comment]
3.X再创建数据库时也增加了cachemodel ‘both’关键字。
![6f58c91a95261d82a95984a70b8a54a](https://user-images.githubusercontent.com/116776928/198177298-0ee2c36c-860c-42e7-9f66-c77bdca91188.jpg)

**Comment by yu285** [comment]
we are sorry to make u feel about this. TDengine 3.0 database is still in tuning performance stage.and it will be finished before Dec .

Thanks for your feedback

**Comment by yu285** [comment]
we can use 3.0.1.6 to do some test, we have done some tuning query on this version

**Comment by 759085503** [comment]
你好，感觉3.0.2.2的版本并没有处理好，可能是我的表结构跟你们的不一样导致的。我使用你们的测试工具写入1000个点（子表）10000W数据感觉你们的很性能效果正常。我的表结构写到这个量级1000个点（子表）10000W后明显的不如你们的。我的表结构如下：
create database if not exists database CACHEMODEL  'both'；
create table if not exists database.dataTable (ts timestamp, tagValue double) tags (tagName nchar(30),description nchar(50),unit nchar(50))；
我尝试把description 跟unit 拿掉后，性能跟你们的差不多。我想知道这个是啥原因（2.6的版本依然正常，3.0.2.2的这个表结构解释不行），希望你们使用我这种表结构试试。

**Comment by 759085503** [comment]
不好意思，好像账号登录的有点问题，我就是【[bkcxiaop](https://github.com/bkcxiaop)】博主。

**Comment by bkcxiaop** [comment]
![image](https://user-images.githubusercontent.com/116776928/210940398-3c0b6945-1cbd-48a6-a459-c80ad0d9fe19.png)
![image](https://user-images.githubusercontent.com/116776928/210940429-4efc1349-0e18-4bc6-80e4-c46cf4ec3b34.png)
![image](https://user-images.githubusercontent.com/116776928/210940505-20fa3be3-3b1a-4980-b2db-19597e504bb7.png)
![image](https://user-images.githubusercontent.com/116776928/210940839-3ec138f0-6461-4c53-bcef-2cc0bd9a3e97.png)

**Comment by bkcxiaop** [comment]
唯一的区别就是表结构不一样，在3.X下面我的表结构数据就不能存多。存多了就慢。而2.6跟3.X的表结构完全一样，2.6就不存咋这个性能问题

**Comment by bkcxiaop** [comment]
![image](https://user-images.githubusercontent.com/116776928/210941541-b2f987d9-27bf-48bc-9b68-687dca07585b.png)

**Comment by yu285** [comment]
如果数据以insert形式更新过多，就会导致这种情况。

**Comment by bkcxiaop** [comment]
是的，谢谢。已处理完毕
