### ISSUE TITLE
DataX writing report an  error 

### ISSUE THREAD

**Issue by hetonghao** [taosdata/TDengine#17707]
**Bug Description**
使用官方DataX TDengineWriter写入到taos3.x，报错

**To Reproduce**
1. 替换tdenginewriter/libs中的taos-jdbc驱动，使用3.0.0驱动
![image](https://user-images.githubusercontent.com/105187701/198205665-ee84d0b0-434c-4eda-bcd6-10d7f535059a.png)
2.配置DataX writer部分
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/105187701/198206101-11f0c7a0-1aa0-4580-9a59-25809ba30a0f.png">
3.运行，得到以下报错
<img width="1591" alt="image" src="https://user-images.githubusercontent.com/105187701/198206253-cb98ff7a-70f2-4300-bb47-cfbd9fa9b0a4.png">

**Expected Behavior**
期望正常写入数据

**Environment (please complete the following information):**
 - OS:  CentOS 7.0
 - Memory 16G, 4 core, current Disk Space Avail 12G
 - TDengine Version  3.0.1.4

**Additional Context**
反编译tdenginewriter-0.0.1-SNAPSHOT.jar，查看源码定位到这段代码
<img width="1840" alt="image" src="https://user-images.githubusercontent.com/105187701/198206467-e03e1c83-9a34-416e-9bcd-c7d54737234a.png">

**Comment by jjismomo** [comment]
3.0 目前还没有适配 dataX, 麻烦等一段时间吧，谢谢哈

**Comment by hetonghao** [comment]
@jjismomo 适配后可以回复一下吗

**Comment by yu285** [comment]
好的，可以加微信 15652223354 ，方便随时沟通

**Comment by zmlgirl** [comment]
目前在 https://github.com/taosdata/DataX/tree/dev/lispQin 这个分支为 DataX 做了 TDengine 3.0 的适配，你可以先试下 @hetonghao
