### ISSUE TITLE
TDengine is in the process of writing  data then suddenly lost power, now can't restart again

### ISSUE THREAD

**Issue by wu-dada-del** [taosdata/TDengine#17729]
此种情况，导致已经创建的数据库，写入的数据全部丢失
（可以排除本地服务器的问题，本地服务器其他的数据库应用全部可以重启）

![Snipaste_2022-10-28_11-21-45](https://user-images.githubusercontent.com/59598025/198495137-f589ccb6-c4e2-44ac-bffa-8bcea37fe898.png)

**Comment by yu285** [comment]
建议先升级到 3.0.1.5 再做启动。如果启动失败，手动执行 sudo taosd 把输出的最后一部分发给我们

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/

如果还有类似问题可以加微信 a15652223354
