### ISSUE TITLE
树莓派4B编译出错

### ISSUE THREAD

**Issue by AryaYinKun** [taosdata/TDengine#1773]
**Bug Description**
树莓派4B，sudo make失败

**To Reproduce**
1. git clone https://github.com/taosdata/TDengine.git成功；
2. sudo cmake .. -DCPUTYPE=aarch32
![image](https://user-images.githubusercontent.com/38499889/80804495-ebeb6400-8be7-11ea-9fcc-ad72bb28d9c3.png)

3. sudo make出错

![image](https://user-images.githubusercontent.com/38499889/80804576-2d7c0f00-8be8-11ea-99f0-f89cbb344261.png)

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
2G内存
cpu：
![image](https://user-images.githubusercontent.com/38499889/80804370-7c757480-8be7-11ea-81fb-dce210646c2a.png)
Disk Space
![image](https://user-images.githubusercontent.com/38499889/80804204-07a23a80-8be7-11ea-9d09-bc051c1a92e5.png)

 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by plum-lihui** [comment]
我们正计划在树莓派上编译，如果有兴趣的话，你可以先尝试自己修改解决一下。
多谢！

**Comment by plum-lihui** [comment]
最新的develop分支已经支持aarch32的编译了，请pull最新代码验证。
多谢！
