### ISSUE TITLE
query performance issue

### ISSUE THREAD

**Issue by xingcun** [taosdata/TDengine#17741]
**Bug Description**

![6921666927245_ pic](https://user-images.githubusercontent.com/14237778/198524311-4048bab3-1a7b-4aed-94a2-ae4148b4c751.jpg)

非超级表下的普通表，一千万条数据查询count(*)就要花费7秒

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory 16g, CPU 4核, 普通硬盘current Disk Space
 - TDengine Version [3.0]

**Comment by yu285** [comment]
这个表有没有做过大量更新操作？表结构describe table 发一下看看

**Comment by xingcun** [comment]
> 

![image](https://user-images.githubusercontent.com/14237778/199156950-a8e95093-ef01-4008-b821-061a825772e3.png)
