### ISSUE TITLE
.NET connector writing with 'Access violation' error

### ISSUE THREAD

**Issue by tjckkj** [taosdata/TDengine#17744]
IntPtr conn = TDengine.Connect("192.168.12.6","root","taosdata","env_data",6030); ;
IntPtr res = TDengine.Query(conn, sql);
 if (TDengine.ErrorNo(res) == 0 && TDengine.AffectRows(res) > 0)
 {
   Debug.WriteLine(sql);
  TDengine.FreeResult(res);
  TDengine.Close(conn);
  return true;
}
TDengine.FreeResult(res);
TDengine.Close(conn);

**Comment by tjckkj** [comment]
程序运行时，偶尔闪退，报错：返回值为 3221225477 (0xc0000005) 'Access violation'

**Comment by xleili** [comment]
就现在报的错来看是内存出问题了，你想要访问的内存地址不允许被访问。
请先提供一下：
TDengine version
.Net connector version

能简单描述一下插入的场景吗？插入频率，数据量等。可以知道程序报错报在那一段了吗

**Comment by sangshuduo** [comment]
Windows 还是 Linux？
跑出问题的 SQL 语句是什么？
