### ISSUE TITLE
C  [libtaos.so.2.6.0.6+0xd02b6]  doSendQueryReqs+0x88  crash

### ISSUE THREAD

**Issue by pyy2578006401** [taosdata/TDengine#17751]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fc5470b12b6, pid=19132, tid=0x00007fc544bdd700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_321-b07) (build 1.8.0_321-b07)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.321-b07 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libtaos.so.2.6.0.6+0xd02b6]  doSendQueryReqs+0x88
#
# Core dump written. Default location: /home/workspace/web/core or core.19132
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

---------------  T H R E A D  ---------------

Current thread is native thread

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000030

Registers:
RAX=0x0000000000000000, RBX=0x0000000000000000, RCX=0x0000000000000000, RDX=0x0000000000000118
RSP=0x00007fc544bdce50, RBP=0x00007fc544bdce90, RSI=0x0000000000000000, RDI=0x0000000000000000
R8 =0x0000000000000000, R9 =0x0000000000000048, R10=0x000000000000c127, R11=0x00007fc69febcd50
R12=0x0000000000000000, R13=0x0000000000801000, R14=0x0000000000000000, R15=0x00007fc544bdd700
RIP=0x00007fc5470b12b6, EFLAGS=0x0000000000010206, CSGSFS=0x0000000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007fc544bdce50)
0x00007fc544bdce50:   0000000000000003 00007fc544bdcec0
0x00007fc544bdce60:   0000000000000000 00000023472270b9
0x00007fc544bdce70:   00007fc5840e0030 00007fc4f86aa380
0x00007fc544bdce80:   0000000000000000 00007fc4f8531220
0x00007fc544bdce90:   00007fc544bdcf10 00007fc5471acbba
0x00007fc544bdcea0:   0000000000000000 00007fc5600d3450
0x00007fc544bdceb0:   0000000000000000 00007fc5600d3450
0x00007fc544bdcec0:   00007fc5470b122e 0000000000000000
0x00007fc544bdced0:   00007fc4f86aa380 00007fc5840e0030
0x00007fc544bdcee0:   0000000000000000 0000000000000000
0x00007fc544bdcef0:   6b7361742d637374 0000000000000051
0x00007fc544bdcf00:   0000000000000000 6a59952b1c10f400
0x00007fc544bdcf10:   0000000000000000 00007fc6a0520ea5
0x00007fc544bdcf20:   0000000000000000 00007fc544bdd700
0x00007fc544bdcf30:   00007fc544bdd700 81edd674e67ec840
0x00007fc544bdcf40:   0000000000000000 0000000000801000
0x00007fc544bdcf50:   0000000000000000 00007fc544bdd700
0x00007fc544bdcf60:   7e675f0f783ec840 7e6096d0faa4c840
0x00007fc544bdcf70:   0000000000000000 0000000000000000
0x00007fc544bdcf80:   0000000000000000 0000000000000000
0x00007fc544bdcf90:   0000000000000000 0000000000000000
0x00007fc544bdcfa0:   0000000000000000 0000000000000000
0x00007fc544bdcfb0:   00007fc544bdd700 00007fc69fe2db0d
0x00007fc544bdcfc0:   0000000000000000 0000000000000000
0x00007fc544bdcfd0:   0000000000000000 0000000000000000
0x00007fc544bdcfe0:   0000000000000000 0000000000000000
0x00007fc544bdcff0:   0000000000000000 0000000000000000
0x00007fc544bdd000:   0000000000000000 0000000000000000
0x00007fc544bdd010:   0000000000000000 0000000000000000
0x00007fc544bdd020:   0000000000000000 0000000000000000
0x00007fc544bdd030:   0000000000000000 0000000000000000
0x00007fc544bdd040:   0000000000000000 0000000000000000 

Instructions: (pc=0x00007fc5470b12b6)
0x00007fc5470b1296:   e0 48 8b 80 a0 07 00 00 8b 55 dc 48 63 d2 48 c1
0x00007fc5470b12a6:   e2 03 48 01 d0 48 8b 00 48 89 45 f0 48 8b 45 f0
0x00007fc5470b12b6:   48 8b 40 30 48 89 45 f8 48 8b 05 bb d6 4e 00 8b
0x00007fc5470b12c6:   00 83 e0 04 85 c0 74 4b 48 8b 45 f8 8b 70 10 48 

Register to memory mapping:

RAX=0x0000000000000000 is an unknown value
RBX=0x0000000000000000 is an unknown value
RCX=0x0000000000000000 is an unknown value
RDX=0x0000000000000118 is an unknown value
RSP=0x00007fc544bdce50 is an unknown value
RBP=0x00007fc544bdce90 is an unknown value
RSI=0x0000000000000000 is an unknown value
RDI=0x0000000000000000 is an unknown value
R8 =0x0000000000000000 is an unknown value
R9 =0x0000000000000048 is an unknown value
R10=0x000000000000c127 is an unknown value
R11=0x00007fc69febcd50: <offset 0x18dd50> in /lib64/libc.so.6 at 0x00007fc69fd2f000
R12=0x0000000000000000 is an unknown value
R13=0x0000000000801000 is an unknown value
R14=0x0000000000000000 is an unknown value
R15=0x00007fc544bdd700 is an unknown value

Stack: [0x00007fc5443de000,0x00007fc544bde000],  sp=0x00007fc544bdce50,  free space=8187k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libtaos.so.2.6.0.6+0xd02b6]  doSendQueryReqs+0x88
C  [libtaos.so.2.6.0.6+0x1cbbba]  taosProcessSchedQueue+0x357

请问这个是什么原因，请帮忙看下吗

**Comment by pyy2578006401** [comment]
版本是2.6.0.6

**Comment by pyy2578006401** [comment]
java: /home/ubuntu/workroom/jenkins/TDinternal/community/src/client/src/tscServer.c:499: tscProcessMsgFromServer: Assertion `rpcMsg->msgType == pCmd->msgType + 1' failed.

**Comment by pyy2578006401** [comment]
==================================================
10/27 17:48:31.970821 00032399 UTL localEp is: wulian01:6030
10/27 17:48:31.971398 00032399 UTL WARN timezone not configured, set to system default: (CST, +0800)
10/27 17:48:31.971407 00032399 UTL WARN locale not configured, set to system default:zh_CN.UTF-8
10/27 17:48:31.971413 00032399 UTL WARN charset not configured, set to system default:UTF-8
10/27 17:48:31.971427 00032399 UTL    check global cfg completed
10/27 17:48:31.971428 00032399 UTL ==================================
10/27 17:48:31.971430 00032399 UTL    taos config & system info:
10/27 17:48:31.971431 00032399 UTL ==================================
10/27 17:48:31.971433 00032399 UTL  firstEp:                datacol01:6030 
10/27 17:48:31.971435 00032399 UTL  secondEp:               wulian01:6030 
10/27 17:48:31.971436 00032399 UTL  fqdn:                   wulian01 
10/27 17:48:31.971437 00032399 UTL  serverPort:             6030 
10/27 17:48:31.971439 00032399 UTL  configDir:              /etc/taos 
10/27 17:48:31.971440 00032399 UTL  logDir:                 /var/log/taos 
10/27 17:48:31.971442 00032399 UTL  scriptDir:              /etc/taos 
10/27 17:48:31.971443 00032399 UTL  arbitrator:              
10/27 17:48:31.971445 00032399 UTL  numOfThreadsPerCore:    1.000000 
10/27 17:48:31.971455 00032399 UTL  maxNumOfDistinctRes:    10000000 
10/27 17:48:31.971456 00032399 UTL  rpcTimer:               300(ms)
10/27 17:48:31.971458 00032399 UTL  rpcMaxTime:             600(s)
10/27 17:48:31.971459 00032399 UTL  rpcForceTcp:            0 
10/27 17:48:31.971461 00032399 UTL  shellActivityTimer:     3(s)
10/27 17:48:31.971462 00032399 UTL  compressMsgSize:        524288 
10/27 17:48:31.971464 00032399 UTL  compressColData:        -1 
10/27 17:48:31.971465 00032399 UTL  maxSQLLength:           1048576(byte)
10/27 17:48:31.971466 00032399 UTL  maxWildCardsLength:     100(byte)
10/27 17:48:31.971474 00032399 UTL  maxRegexStringLen:      128(byte)
10/27 17:48:31.971476 00032399 UTL  maxNumOfOrderedRes:     1000000 
10/27 17:48:31.971477 00032399 UTL  keepColumnName:         1 
10/27 17:48:31.971479 00032399 UTL  timezone:                (CST, +0800) 
10/27 17:48:31.971480 00032399 UTL  locale:                 zh_CN.UTF-8 
10/27 17:48:31.971481 00032399 UTL  charset:                UTF-8 
10/27 17:48:31.971483 00032399 UTL  numOfLogLines:          10000000 
10/27 17:48:31.971484 00032399 UTL  logKeepDays:            0 
10/27 17:48:31.971485 00032399 UTL  asyncLog:               1 
10/27 17:48:31.971487 00032399 UTL  debugFlag:              0 
10/27 17:48:31.971488 00032399 UTL  rpcDebugFlag:           131 
10/27 17:48:31.971489 00032399 UTL  tmrDebugFlag:           131 
10/27 17:48:31.971491 00032399 UTL  cDebugFlag:             131 
10/27 17:48:31.971492 00032399 UTL  jniDebugFlag:           131 
10/27 17:48:31.971493 00032399 UTL  odbcDebugFlag:          131 
10/27 17:48:31.971494 00032399 UTL  uDebugFlag:             131 
10/27 17:48:31.971496 00032399 UTL  qDebugFlag:             131 
10/27 17:48:31.971497 00032399 UTL  tsdbDebugFlag:          131 
10/27 17:48:31.971498 00032399 UTL  gitinfo:                db5a04e113cf85c40a52489e558dbdfa4dbb11a4 
10/27 17:48:31.971499 00032399 UTL  gitinfoOfInternal:      NULL 
10/27 17:48:31.971501 00032399 UTL  buildinfo:              Built at 2022-06-25 15:01 
10/27 17:48:31.971502 00032399 UTL  version:                2.6.0.6 
10/27 17:48:31.971503 00032399 UTL  maxBinaryDisplayWidth:  30 
10/27 17:48:31.971505 00032399 UTL  tempDir:                /tmp/ 
10/27 17:48:31.971506 00032399 UTL  defaultJSONStrType:     nchar 
10/27 17:48:31.971507 00032399 UTL  smlChildTableName:       
10/27 17:48:31.971509 00032399 UTL  smlTagNullName:         _tag_null 
10/27 17:48:31.971510 00032399 UTL  walFlushSize:           1024(Mb)
10/27 17:48:31.971511 00032399 UTL  shortcutFlag:           0 
10/27 17:48:31.971514 00032399 UTL  os pageSize:            4096(KB)
10/27 17:48:31.971515 00032399 UTL  os openMax:             2048
10/27 17:48:31.971516 00032399 UTL  os streamMax:           16
10/27 17:48:31.971517 00032399 UTL  os numOfCores:          16
10/27 17:48:31.971520 00032399 UTL  os totalMemory:         32010(MB)
10/27 17:48:31.971524 00032399 UTL  os sysname:             Linux
10/27 17:48:31.971526 00032399 UTL  os nodename:            wulian01
10/27 17:48:31.971527 00032399 UTL  os release:             3.10.0-1062.el7.x86_64
10/27 17:48:31.971528 00032399 UTL  os version:             #1 SMP Wed Aug 7 18:08:02 UTC 2019
10/27 17:48:31.971529 00032399 UTL  os machine:             x86_64
10/27 17:48:31.971531 00032399 UTL  dataDir: /var/lib/taos
10/27 17:48:31.971533 00032399 UTL ==================================
10/27 17:48:33.046825 00000587 UTL ERROR failed to connect socket, ip:0xe700090a, port:6030(poll error/conn timeout)
10/27 17:48:33.046854 00000587 RPC ERROR failed to connect to:0xe700090a:6030
10/27 17:48:33.046900 00000587 RPC ERROR TSC 0x1f, failed to set up connection(Unable to establish connection)
10/27 17:48:33.047199 00000589 UTL ERROR failed to connect socket, ip:0xe700090a, port:6030(poll error/conn timeout)
10/27 17:48:33.047225 00000589 RPC ERROR failed to connect to:0xe700090a:6030
10/27 17:48:33.047230 00000589 RPC ERROR TSC 0x26, failed to set up connection(Unable to establish connection)
10/27 17:48:33.047421 00000588 UTL ERROR failed to connect socket, ip:0xe700090a, port:6030(poll error/conn timeout)
10/27 17:48:33.047442 00000588 RPC ERROR failed to connect to:0xe700090a:6030
10/27 17:48:33.047447 00000588 RPC ERROR TSC 0x22, failed to set up connection(Unable to establish connection)
10/27 17:48:33.048870 00000586 UTL ERROR failed to connect socket, ip:0xe700090a, port:6030(poll error/conn timeout)
10/27 17:48:33.048882 00000586 RPC ERROR failed to connect to:0xe700090a:6030
10/27 17:48:33.048885 00000586 RPC ERROR TSC 0x1b, failed to set up connection(Unable to establish connection)
10/27 17:48:33.051100 00000583 UTL ERROR failed to connect socket, ip:0xe700090a, port:6030(poll error/conn timeout)
10/27 17:48:33.051121 00000583 RPC ERROR failed to connect to:0xe700090a:6030
10/27 17:48:33.051125 00000583 RPC ERROR TSC 0x2e, failed to set up connection(Unable to establish connection)
10/27 17:48:33.051891 00000585 UTL ERROR failed to connect socket, ip:0xe700090a, port:6030(poll error/conn timeout)
10/27 17:48:33.051909 00000585 RPC ERROR failed to connect to:0xe700090a:6030
10/27 17:48:33.051913 00000585 RPC ERROR TSC 0x2a, failed to set up connection(Unable to establish connection)
10/27 17:48:33.053403 00000590 TSC WARN 0x1f it shall renew table meta, code:Unable to establish connection, retry:1
10/27 17:48:34.058092 00000586 UTL ERROR failed to connect socket, ip:0xe700090a, port:6030(poll error/conn timeout)
10/27 17:48:34.058142 00000586 RPC ERROR failed to connect to:0xe700090a:6030
10/27 17:48:34.058156 00000589 UTL ERROR failed to connect socket, ip:0xe700090a, port:6030(poll error/conn timeout)
10/27 17:48:34.058164 00000589 RPC ERROR failed to connect to:0xe700090a:6030
10/27 17:48:34.058166 00000589 RPC ERROR TSC 0x37, failed to set up connection(Unable to establish connection)
10/27 17:48:34.058145 00000583 UTL ERROR failed to connect socket, ip:0xe700090a, port:6030(poll error/conn timeout)
10/27 17:48:34.058186 00000583 RPC ERROR failed to connect to:0xe700090a:6030
10/27 17:48:34.058192 00000583 RPC ERROR TSC 0x51, failed to set up connection(Unable to establish connection)
10/27 17:48:34.058149 00000586 RPC ERROR TSC 0x45, failed to set up connection(Unable to establish connection)
10/27 17:48:34.058389 00000582 UTL ERROR failed to connect socket, ip:0xe700090a, port:6030(poll error/conn timeout)
10/27 17:48:34.058412 00000582 RPC ERROR failed to connect to:0xe700090a:6030
10/27 17:48:34.058416 00000582 RPC ERROR TSC 0x58, failed to set up connection(Unable to establish connection)
10/27 17:48:34.059884 00000585 UTL ERROR failed to connect socket, ip:0xe700090a, port:6030(poll error/conn timeout)
10/27 17:48:34.059904 00000585 RPC ERROR failed to connect to:0xe700090a:6030
10/27 17:48:34.059897 00000584 UTL ERROR failed to connect socket, ip:0xe700090a, port:6030(poll error/conn timeout)
10/27 17:48:34.059924 00000584 RPC ERROR failed to connect to:0xe700090a:6030
10/27 17:48:34.059929 00000584 RPC ERROR TSC 0x55, failed to set up connection(Unable to establish connection)
10/27 17:48:34.059908 00000585 RPC ERROR TSC 0x4d, failed to set up connection(Unable to establish connection)
10/27 17:48:34.062312 00000587 UTL ERROR failed to connect socket, ip:0xe700090a, port:6030(poll error/conn timeout)
10/27 17:48:34.062331 00000587 RPC ERROR failed to connect to:0xe700090a:6030
10/27 17:48:34.062335 00000587 RPC ERROR TSC 0x49, failed to set up connection(Unable to establish connection)
10/27 17:48:34.063388 00000590 TSC WARN 0x37 it shall renew table meta, code:Unable to establish connection, retry:1
10/27 17:53:02.959915 00000588 UTL ERROR failed to connect socket, ip:0xe700090a, port:6030(poll error/conn timeout)
10/27 17:53:02.959922 00000584 UTL ERROR failed to connect socket, ip:0xe700090a, port:6030(poll error/conn timeout)
10/27 17:53:02.959945 00000584 RPC ERROR failed to connect to:0xe700090a:6030
10/27 17:53:02.959939 00000586 UTL ERROR failed to connect socket, ip:0xe700090a, port:6030(poll error/conn timeout)
10/27 17:53:02.959939 00000588 RPC ERROR failed to connect to:0xe700090a:6030
10/27 17:53:02.959950 00000584 RPC ERROR TSC 0x1a0, failed to set up connection(Unable to establish connection)
10/27 17:53:02.959954 00000588 RPC ERROR TSC 0x18f, failed to set up connection(Unable to establish connection)
10/27 17:53:02.959961 00000586 RPC ERROR failed to connect to:0xe700090a:6030
10/27 17:53:02.959965 00000586 RPC ERROR TSC 0x1a9, failed to set up connection(Unable to establish connection)
10/27 17:53:02.968395 00000590 TSC WARN 0x1a0 it shall renew table meta, code:Unable to establish connection, retry:1
10/27 18:26:56.763103 00000588 UTL ERROR failed to connect socket, ip:0xe700090a, port:6030(poll error/conn timeout)
10/27 18:26:56.763128 00000588 RPC ERROR failed to connect to:0xe700090a:6030
10/27 18:26:56.763135 00000588 RPC ERROR TSC 0x3ce, failed to set up connection(Unable to establish connection)
10/27 18:26:56.768391 00000590 TSC WARN 0x3ce it shall renew table meta, code:Unable to establish connection, retry:1
10/27 18:26:57.779088 00000589 UTL ERROR failed to connect socket, ip:0xe700090a, port:6030(poll error/conn timeout)
10/27 18:26:57.779116 00000589 RPC ERROR failed to connect to:0xe700090a:6030
10/27 18:26:57.779122 00000589 RPC ERROR TSC 0x3da, failed to set up connection(Unable to establish connection)
10/27 18:26:57.779258 00000583 UTL ERROR failed to connect socket, ip:0xe700090a, port:6030(poll error/conn timeout)
10/27 18:26:57.779268 00000583 RPC ERROR failed to connect to:0xe700090a:6030
10/27 18:26:57.779271 00000583 RPC ERROR TSC 0x3f0, failed to set up connection(Unable to establish connection)
10/27 18:26:57.780975 00000588 UTL ERROR failed to connect socket, ip:0xe700090a, port:6030(poll error/conn timeout)
10/27 18:26:57.780995 00000588 RPC ERROR failed to connect to:0xe700090a:6030
10/27 18:26:57.780999 00000588 RPC ERROR TSC 0x3f4, failed to set up connection(Unable to establish connection)
10/27 18:26:57.783405 00000590 TSC WARN 0x3da it shall renew table meta, code:Unable to establish connection, retry:1

**Comment by yu285** [comment]
麻烦先升级到 2.6.0.28 再做尝试，修复了很多问题
