### ISSUE TITLE
password of TDengine user processed in MD5 Hash  and stored in sdb.data is not security enough 

### ISSUE THREAD

**Issue by xinwenwxw** [taosdata/TDengine#17773]
密码加密MD5 Hash，存在 sdb.data 中安全性不够高。参见代码https://github.com/taosdata/TDengine/blob/32e261f848d46b47e5ee04770ab59653d27bc026/include/util/tutil.h  

考虑金融机构引入安全性，md5属于弱算法不符合监管要求 建议修改为sm3或者sha256及以上的算法

**Comment by yu285** [comment]
感谢您的建议，我们会认真考虑。咱们当前的产品使用有遇到这方面因素的阻塞吗

**Comment by xinwenwxw** [comment]
现在这个问题就是阻塞点。必须修改掉才能使用

**Comment by xinwenwxw** [comment]
方便提供你的电话吗？和你单独沟通下

**Comment by yu285** [comment]
可以的 15652223354 ，也是微信。
