### ISSUE TITLE
jdbcTemplate query not return data

### ISSUE THREAD

**Issue by MelodyI** [taosdata/TDengine#17783]
**Bug Description**
jdbcTemplate query not return data

**To Reproduce**
List<Timestamp> list = jdbcTemplate.query("select ts from tableA", (rs, rowNum) -> {
    return rs.getTimestamp("ts");
});

list is empty while tableA is not empty!

**Environment (please complete the following information):**
 - OS: OSX 13
 - 8G, Apple M1, 512G
 - TDengine Version [3.0.1.5]
 - JDK[1.8]
 - Springboot[2.7.3]
 - Driver Version[3.0.2]

**Comment by huolibo** [comment]
It's ok in my test environment. ![image](https://user-images.githubusercontent.com/17586328/199863300-04e9f315-adf8-4912-86fb-21887aba1ae3.png)

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
