### ISSUE TITLE
Linux java.lang.UnsatisfiedLinkError: no taos in java.library.path

### ISSUE THREAD

**Issue by greenhandH** [taosdata/TDengine#17790]
本地运行没有报错 ，rancher部署后报错：
![1667218441991](https://user-images.githubusercontent.com/47620967/199005375-884afcbe-0497-4e40-8cbc-5f3c74fb219e.jpg)

服务运行的服务器上也配置了对应的软链接
![image](https://user-images.githubusercontent.com/47620967/199006003-5c81c8b2-8325-449c-b23f-804511f90c5a.png)

所以能请官方的技术看看是为什么嘛，谢谢。

刚刚试了下将另外一个多余的软链接删除，然后重新部署了一下项目，结果还是不行。
![image](https://user-images.githubusercontent.com/47620967/199008422-72fdfb8c-0993-4e8a-b32f-47729499fe60.png)
![image](https://user-images.githubusercontent.com/47620967/199008527-6e7aab0c-a671-4040-b6b2-71bd0a88c5f5.png)
麻烦看一下 谢谢

**Comment by yu285** [comment]
您好，加我微信一下吧 15652223354 我们看下

**Comment by yu285** [comment]
需要远程一下

**Comment by greenhandH** [comment]
> 需要远程一下

已经加您了

**Comment by sangshuduo** [comment]
https://docs.taosdata.com/connector/java/#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by sunpe** [comment]
和用户一起排查，最终定位是 rancher 配置问题

**Comment by JYHarvest** [comment]
我也遇到同样问题，请问最后如何解决的？
