### ISSUE TITLE
TDengine3.0.1.2 order by ts desc not work properly 

### ISSUE THREAD

**Issue by jinjerxu** [taosdata/TDengine#17814]
**Bug Description**
使用主键进行倒序查询时，不分页查询总数不对，分页查询到一定的页数，也查询不到数据，升序查询则正常，且使用非主键字段进行倒序查询也正常；试过其他超级表和字表，也发现同样的问题。

**Screenshots**
![image](https://user-images.githubusercontent.com/4001873/199217497-558718ee-b16e-438f-b4f0-d0eac4b5df6c.png)

**Environment (please complete the following information):**
 - OS: centos 7.9
 - Memory：32GB, CPU：8核, current Disk Space：250GB
 - TDengine Version [e.g. 3.0.1.2]

**Comment by yu285** [comment]
我们修复了很多查询方向的问题，可以升级到 3.0.1.5 再重新执行一下这个SQL吗

**Comment by yu285** [comment]
请问还有问题么
