### ISSUE TITLE
invalid SQL: sql too long

### ISSUE THREAD

**Issue by hexuejian** [taosdata/TDengine#1782]
使用python connecter的
按指定的列插入多条记录
IMPORT INTO tb_name (field1_name, ...) VALUES(field1_value1, ...) (field1_value2, ...)
当数据量过大时，大概16000条数据时，报出异常：invalid SQL: sql too long，想请问一下，IMPORT最大一次支持多少条数据向一个表中插入数据，还是说没有限制呢

**Comment by liuyq-617** [comment]
单条语句不能超过64K
