### ISSUE TITLE
springboot+tdengine

### ISSUE THREAD

**Issue by a995234891** [taosdata/TDengine#17828]
使用durid连接池在配置文件中加载，
我在内存中拼接好sql，通过SqlSessionTemplate获取Stament，去执行sql，报错
sql出错=sql injection violation, syntax error: syntax error, error in :'ints TAGS('1') VALUES('2018-10-03 1', expect IDENTIFIER, actual IDENTIFIER pos 31, line 1, column 32, token IDENTIFIER TAGS : insert into dev001 using points TAGS('1') VALUES('2018-10-03 14:38:05.000','1','1')
这是代码
![image](https://user-images.githubusercontent.com/58390364/199388410-08920ba2-59d5-4e8d-b069-dd254aea59d2.png)

**Comment by zclcs** [comment]
别用 using
