### ISSUE TITLE
database keep retrieving meta

### ISSUE THREAD

**Issue by AwayNOW** [taosdata/TDengine#17836]
版本：3.0.1.5

创建了两个库test和test1，test跑的是taosBenchmark示例，test1跑的是官方springbootdemo示例代码
问题是 数据库在win10电脑上，每次电脑待机后都需要重新启动，重启数据库后会搞20分钟左右的
![image](https://user-images.githubusercontent.com/17540853/199427247-1544f34a-af18-4897-b98b-07a49ff97073.png)
![image](https://user-images.githubusercontent.com/17540853/199438292-682e835c-cb7c-42ac-8a84-64550a90ef35.png)

在数据库主动搞retrieve meta时，TDengineGUI也无法链接上去了

想问数据库为什么会主动干这个操作，有什么意义，哪里可以关掉，官网上有没有这块的介绍链接

**Comment by yu285** [comment]
可以加微信 15652223354 做具体排查
