### ISSUE TITLE
cmake with error 

### ISSUE THREAD

**Issue by skyformat99** [taosdata/TDengine#17832]
最新版代码（2022/11/2日的代码）
使用  cmake ..   时候，出现如下错误：之前的版本是没有问题的。

简单看了一下，估计是CMakeFile.txt文件的问题啊

[ 68%] Performing update step for 'taosadapter'
fatal: ambiguous argument 'a11131c': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

**Comment by sangshuduo** [comment]
哪个分支？

**Comment by skyformat99** [comment]
> 哪个分支？

main

**Comment by sangshuduo** [comment]
你试试 git clean -fxd 然后再编译一次

> > 哪个分支？
> 
> main

**Comment by skyformat99** [comment]
> 

可以了。thx
