### ISSUE TITLE
TDengine 3.0.1.5:drop  stream ; result：DB error: Invalid Vgroup ID (11.187355s)

### ISSUE THREAD

**Issue by gx2529087850** [taosdata/TDengine#17845]
# 1.现象
第一次删除报错
![b62cbeb0c07368d9deae719be8200ee](https://user-images.githubusercontent.com/43409392/199458255-e54a4e2d-2b84-45bc-aedb-fa93ef167de5.jpg)
后面进行删除报错
![image](https://user-images.githubusercontent.com/43409392/199458596-f557f135-22ee-46da-931b-07f8088236bf.png)
在删不掉stream时候尝试删除db卡住，另一个客户端打开也看的到但是没法use如图
![image](https://user-images.githubusercontent.com/43409392/199459885-0dddd774-f153-4ee6-bdf1-c02f89332e92.png)

![image](https://user-images.githubusercontent.com/43409392/199459827-581b7084-9fad-49b2-ae9b-e9a6fa68672e.png)

show transactions
![ae8196873874af5ec64b62cce654080](https://user-images.githubusercontent.com/43409392/199460910-46a7484c-9525-48ce-8870-3b4d59fd6abc.jpg)

# 2.操作
## 2.1.环境
TD3.0.1.5集群 三个节点
![image](https://user-images.githubusercontent.com/43409392/199458732-792cbc1e-f38d-495e-8390-6f84bb8129fc.png)
## 2.2. 创建库、表、流

```sql
-- 库
create database chain_smart_log replica 3;
-- 表
create STABLE if not exists  device_property_25
        ( ts timestamp,
        createTime timestamp,
        property_value BINARY(100),
        number_value DOUBLE
        )
        TAGS(
        product_id BINARY(50),
        device_id BINARY(50),
        property BINARY(50)
        );
-- 流
create stream energy_stream into energy_stream_output_stb as select _wstart as start, _wend as wend,max(number_value)-min(number_value) energy ,device_id from  device_property_25 where property='energy' PARTITION BY device_id INTERVAL(1m);
-- 数据 示例
 INSERT INTO device_property_25_d2004p90jy927_energy        USING device_property_25 TAGS        (25,'D2004P90JY927','energy')        VALUES ('2022-10-15 00:00:02.483','2022-10-15 00:00:02.483', '2022-10-15 00:00:02.483',49.768);

```
在发现卡之前，是客户端程序无法进行数据插入，然后因为三个节点有几个节点被拿去做实验关闭掉了，所以统一去重启全部节点的操作，发现还是卡住，因为流后面加的，所以怀疑流有问题，试着删除，发现现在的问题；流在使用的时候是可以产生数据的，可以生成数据。

日志截图
![image](https://user-images.githubusercontent.com/43409392/199462759-3d8dd05e-51f0-42ab-b57e-acc444ca4738.png)

[taosdlog.zip](https://github.com/taosdata/TDengine/files/9919315/taosdlog.zip)

2022-11-03 10:46 更新
![image](https://user-images.githubusercontent.com/43409392/199639258-d33c377b-f74b-46f1-bbad-5da230068c78.png)
![image](https://user-images.githubusercontent.com/43409392/199639290-cc8b13d4-26b2-49b1-8b2b-63dfc24006f5.png)

在只运行一个节点的情况下，发现没法use具体的库或者删除数据，报错如截图，然后我启动了另外一个节点后，又变回上面的那个报错

**Comment by yu285** [comment]
您好抱歉刚看到我们的问题，可以加微信具体排查： 15652223354
