### ISSUE TITLE
TDengine3.0.1.5 couldn't get data through Grafana 

### ISSUE THREAD

**Issue by hecao100** [taosdata/TDengine#17854]
一、TDengine版本3.0.1.5（使用默认的用户root和密码taosdata）
已开启taosAdapter（端口6041）
已安装taosKeeper（端口6043）
启动taosAdapter和taosKeeper后，td数据库内log可以查看到数据
taos> use log;
Database changed.

taos> show stables;
          stable_name           |
=================================
 logs                           |
 taosadapter_restful_http_re... |
 log_dir                        |
 keeper_monitor                 |
 dnodes_info                    |
 data_dir                       |
 taosadapter_system_mem_percent |
 log_summary                    |
 m_info                         |
 vnodes_role                    |
 cluster_info                   |
 taosadapter_restful_http_re... |
 temp_dir                       |
 grants_info                    |
 taosadapter_system_cpu_percent |
 vgroups_info                   |
 d_info                         |
 taosadapter_restful_http_re... |
 taosadapter_restful_http_re... |
Query OK, 19 rows in database (0.001193s)

taos> show tables;
           table_name           |
=================================
 t_d031b47270c0ac8615a867ff2... |
 t_65141f8ce911d122226f473b0... |
 t_042603b9cac6b27e3a0524523... |
 t_5621784fb2013f7c45855f4b0... |
 t_47e34bbd7bd7492bda4705910... |
 t_ed51a8da0f672db14d4464bd2... |

taos> select * from cluster_info limit 1;
Query OK, 0 rows in database (0.002827s)  无数据

浏览器可以访问到metrics数据
[root@taos1 tsdb]# curl http://localhost:6041/metrics
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 3.3787e-05
go_gc_duration_seconds{quantile="0.25"} 4.1311e-05
go_gc_duration_seconds{quantile="0.5"} 4.4493e-05
go_gc_duration_seconds{quantile="0.75"} 5.6901e-05
go_gc_duration_seconds{quantile="1"} 0.000175442
go_gc_duration_seconds_sum 0.23867984
go_gc_duration_seconds_count 5538

二、分别安装Grafana7.* ，8.*，9.*，再Data source增加数据源测试成功TDengine Data source is working，导入[TDinsight for 3.x成功

三、在DashBoards里显示的所有数据都是NoData

**Comment by sunpe** [comment]
你的情况应该是TDengine的监控配置没打开，请检查 taos.cfg 文件（linux系统在 /etc/taos/taos.cfg）中 「monitor」配置，该配置默认是注释掉的，并添加 「monitorFqdn」配置。

更多信息请参考 [TDengine 文档](https://docs.taosdata.com/reference/config/#%E7%9B%91%E6%8E%A7%E7%9B%B8%E5%85%B3) 和 [taoskeeper 文档](https://docs.taosdata.com/reference/taosKeeper/)。

关于 TDengine 的任何问题，欢迎反馈给我们。

**Comment by hecao100** [comment]
这个是我们的配置参数，按照这个参数还是无法获得监控数据
numOfThreadsPerCore 2
numOfCommitThreads 40
ratioOfQueryCores  2
keepColumnName  1
numOfMnodes  3
balance  0
offlineThreshold  86400
maxVgroupsPerDb 30
blocks  60
quorum  2
wallevel  1
maxSQLLength  1048576
timezone  Asia/Shanghai(CST, +0800)
locale enUS.UTF-8
charset UTF-8
maxShellConns  50000
maxConnections  50000
monitor  1
monitorFqdn taos1



现在可以看到数据了，但是打开http://ip:3000/d/tdinsight-3x/tdinsight-for-3-x?orgId=1&refresh=30s&var-database=log&var-userdb=All&var-fqdn=All&var-version=&var-firstEp=&var-interval=$__auto_interval_interval

在这个页面在操作其他按钮是失灵的，就是无法退出这个监控页面了

**Comment by sunpe** [comment]
TDinsightV3 当前版本在高版本的grafana上有bug，我们已经修复了这个问题，但是还没发版。可以去代码仓库上下载最新的 [TDinsightV3](https://github.com/taosdata/grafanaplugin/blob/master/dashboards/TDinsightV3.json)

**Comment by sunpe** [comment]
grafana plugin v3.2.7 已经发布了，修复了dashboard的问题，欢迎体验 @hecao100
