### ISSUE TITLE
GoLang writing with error "Table does not exist"

### ISSUE THREAD

**Issue by rexel-cn** [taosdata/TDengine#17866]
**Bug Description**
模拟1秒写入10万测点的场景，每次写入1000个子表，写入过程中日志报错。

**Screenshots**
写入部分截图：
![image](https://user-images.githubusercontent.com/54128129/199653625-203c6ac0-8347-45f4-a7b3-73cd33965cfa.png)

客户端报错截图：
![image](https://user-images.githubusercontent.com/54128129/199653586-610bb21e-4e93-49fa-9454-f27434323343.png)

td后台日志截图：
![image](https://user-images.githubusercontent.com/54128129/199653766-52057ef7-ef43-477b-b402-cf7b0b58fb71.png)

**Environment (please complete the following information):**
linux：centos8.2 4cpu 16GB
tdengine： 2.6.0.12
client：github.com/taosdata/driver-go/v2 v2.0.5

**Comment by yu285** [comment]
自动建表在 2.x 是异步且单线程，容易出现瓶颈，建议先建好表。

**Comment by chenquan** [comment]
> 自动建表在 2.x 是异步且单线程，容易出现瓶颈，建议先建好表。

在3.x中 会存在这个问题吗?

**Comment by quchunhui** [comment]
同问，我需要判断一下是否有必要升级到3.x

**Comment by yu285** [comment]
3.x 不会在每秒千表级别的自动建表期间出现瓶颈，导致建表失败，元数据不同步等问题

**Comment by rexel-cn** [comment]
非常感谢
