### ISSUE TITLE
in-clause with parameter placehoder

### ISSUE THREAD

**Issue by freemine** [taosdata/TDengine#17872]
say:
select * from t where name in (?,?,?)

does this kind of parameterized-statement could be used via taos_stmt_xxxx APIs?

**Comment by xiao-yu-wang** [comment]
Yes, we support this usage.

**Comment by freemine** [comment]
but seems like the following fails with errmsg "Invalid column name: col_d" in `taos_stmt_bind_param_batch`
```
select * from (select col_d from t) x where col_d in (?,?)
```

please confirm if the problem exists.

btw, 
```
select * from t where col_d in (?, ?)
```
works just fine.
