### ISSUE TITLE
database not ready

### ISSUE THREAD

**Issue by nwsj2008** [taosdata/TDengine#17889]
centoros 7.9   tdengine 3.0above

**Comment by nwsj2008** [comment]
when i use taos local, showed "failed to connect server, database not ready" error then quit.

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
