### ISSUE TITLE
create stream by fill ,tdengine failed

### ISSUE THREAD

**Issue by Confuciussaids** [taosdata/TDengine#17892]
**Bug Description**
exec T-sql，select new stable，tdengine status failed

1. sql：
        create stream point_integration_stream trigger window_close into qz_shuixiang_jt.point_integration as
        select _wstart,_wend,_wduration,last(line) as line,last(devices) as devices, concat_ws(',',
        cast(last(wcs_sx_stop) as nchar(1)),
        cast(last(wcs_sx_allowaccess) as nchar(1)),
        cast(last(wcs_sx_allowcomplete) as nchar(1)),
        cast(last(wcs_sx_upcompletion) as nchar(1)),
        cast(last(wcs_sx_runing) as nchar(1))) as integrationvalue,
         last(ts) as last_time,count(*) as record_count
        from qz_shuixiang_jt.point
        where ts>=now-5m and ts<=now
        partition by tbname
        interval(10s) sliding(1s)
        fill(prev);
2. select * from qz_shuixiang_jt.point_integration
3. tdengine status failed
![1667527487451](https://user-images.githubusercontent.com/39848547/199869509-bfe81e58-95d7-4e34-8c19-2268c7baacd9.png)
4.gdb core
![4c92ce963b6e4305814608fc2e6ea2a](https://user-images.githubusercontent.com/39848547/199869577-6b0c78dd-ebb1-4836-89ea-bf30aa90466e.png)
![7c589fc68e4b1e323d154d6b224e7ac](https://user-images.githubusercontent.com/39848547/199869596-6e0c60e0-8f51-475b-accf-557660fa502b.png)

**Environment (please complete the following information):**
 - TDengine Version [3.0.1.4]

**Comment by cosmic-jc** [comment]
could you please provide the SQL that create table?

**Comment by Confuciussaids** [comment]
create source stable sql:
create stable qz_shuixiang_jt.point
(ts timestamp,kafkaoffset bigint,
wcs_sx_upcompletion tinyint,wcs_sx_allowaccess tinyint,wcs_sx_stop tinyint,wcs_sx_runing tinyint,wcs_sx_allowcomplete tinyint) 
tags (line nchar(20), devices nchar(50));

**Comment by cosmic-jc** [comment]
Some similar problems has been solved in ver 3.0.1.6, could you plz have a try? If it still appears, feel free to reopen it.
