### ISSUE TITLE
taos can't run   (required by /lib/libtaosws.so)

### ISSUE THREAD

**Issue by jiancaiHub** [taosdata/TDengine#17896]
os - CentOS Linux release 7.6.1810 (Core) 
* version
`TDengine-server-3.0.1.6-Linux-x64.rpm`
* step 1
`install - sudo rpm -ivh TDengine-server-3.0.1.6-Linux-x64.rpm`
* step 2
`start taosd - sudo systemctl start taosd`
* setp 3
`sudo taos`
* log 
`taos: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /lib/libtaosws.so)`

**Comment by yu285** [comment]
缺乏 2.25 的glibc, 建议做个更新或者新机器吧

**Comment by jiancaiHub** [comment]
install glibc
