### ISSUE TITLE
Initialization of tsDnodeRunStatus

### ISSUE THREAD

**Issue by haoyifan** [taosdata/TDengine#1790]
Inside dnodeInitSystem() where a bunch of initializations are done:

```
  if (dnodeInitStorage() != 0) return -1;
  if (dnodeInitRead() != 0) return -1;
  if (dnodeInitWrite() != 0) return -1;
  if (dnodeInitMClient() != 0) return -1;
  if (dnodeInitModules() != 0) return -1;
  if (dnodeInitMnode() != 0) return -1;
  if (dnodeInitMgmt() != 0) return -1;
  if (dnodeInitShell() != 0) return -1;

  dnodeStartModules();
  dnodeSetRunStatus(TSDB_DNODE_RUN_STATUS_RUNING);
```

A processor is free to reorder the instructions like the following:

```
  dnodeSetRunStatus(TSDB_DNODE_RUN_STATUS_RUNING); <-- processor reorders the instruction
  
  if (dnodeInitStorage() != 0) return -1;
  if (dnodeInitRead() != 0) return -1;
  if (dnodeInitWrite() != 0) return -1;
  if (dnodeInitMClient() != 0) return -1;
  if (dnodeInitModules() != 0) return -1;
  if (dnodeInitMnode() != 0) return -1;
  if (dnodeInitMgmt() != 0) return -1;
  if (dnodeInitShell() != 0) return -1;

  dnodeStartModules();
```

This is probably easier to reproduce on hardware with a more relaxed memory consistency model as well as deep pipeline and retire buffer. This means in theory outside world can see tsDnodeRunStatus being initialized to TSDB_DNODE_RUN_STATUS_RUNING before any components are properly initialized. Though this is theoretically possible, I didn't reproduce this problem (I'll probably know how once I get more familiar with the software).

This can be solved by either:
1. Use some synchronization primitive to protect tsDnodeRunStatus (atomic instruction or locking).
2. Add a memory barrier before dnodeSetRunStatus() to make sure it's not reordered by the hardware.

Please let me know if this is an issue. I might miss something here, but given that tsDnodeRunStatus is a shared variable I think it needs proper protection.

**Comment by liuyq-617** [comment]
Thanks for your feedback, we will process your request as soon as possible

**Comment by localvar** [comment]
functions like `dnodeStartModules` perform many syscall/atomic operations directly or indirectly, and memory fences of these operations will prevent other processors from seeing status change too earlier, so I don't think it will cause a real problem.

however, I agree with you that the status should be protected explicitly as the difficulty of concurrency issues.

**Comment by sangshuduo** [comment]
no update, close it.
