### ISSUE TITLE
TDEngine 3.x has broken update feature with 2.x

### ISSUE THREAD

**Issue by richwxd** [taosdata/TDengine#17903]
**Bug Description**
Same SQL can be run in 2.x successfully. But in 3.x, it failed and display "Syntax Error"

**To Reproduce**
1. Go to cmd
2. Type in SQL which successfully in 2.x version
3. "synctax error"

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: WIndows 10
 - 32GB, 8Core
 - TDengine Version 3.0.1.6

**Additional Context**

**Comment by yu285** [comment]
specific SQL statement please

**Comment by richwxd** [comment]
create table if not exists
mydb.properties_weldmqttdevicemodel
(_ts timestamp,
"pha1" double,
"iactual3" double,
"progno" int,
"currentreferencevalue" double,
"id" binary(256),
"timername" binary(256),
"poweractualvalue" double,
"resistanceactualvalue" double,
"pha2" double,
"iactual1" double,
"uiprefvalue" double,
"currnetactualvalue" double,
"datetime" binary(256),
"voltageactualvalue" double,
"stabilisationfactoractvalue" double,
"energyactualvalue" double,
"iactual2" double,
"createtime" bigint,
"uipactualvalue" double,
"spotname" binary(256),
"partidentstring" binary(256),
"weldtimeactualvalue" double,
"pha3" double)
TAGS
("deviceid" binary(256))

**Comment by richwxd** [comment]
So any update?

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
