### ISSUE TITLE
td-connector can't be installed with node V12..   

### ISSUE THREAD

**Issue by sytpb** [taosdata/TDengine#1791]
npm install td-connector got logs as below ...

../src/binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE {anonymous}::WriteObject(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/binding.cc:222:43: error: no matching function for call to ‘v8::Value::BooleanValue()’

......................

gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/root/sys/node-v12.16.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack at ChildProcess.emit (events.js:310:20)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 3.10.0-862.el7.x86_64
gyp ERR! command "/root/sys/node-v12.16.2-linux-x64/bin/node" "/root/sys/node-v12.16.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/tst/wework_server/node_modules/ref
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref@1.3.5 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ref@1.3.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

check the problem with others , thanks Stone to help me ,    td-connector dependency of node-gyp is v5.1 ,   the latest is V6.1.0 ,  it works well with Node V12 ,    hope solve this problem ...

**Comment by keel** [comment]
其实改下package.json，把node-gyp依赖升级到^6.1.0即可。

**Comment by keel** [comment]
好像td不怎么重视node驱动和client，目前mac 上也没办法跑起来

**Comment by StoneT2000** [comment]
Hi, just a note, node v12 is in fact not supported. You need node v10

**Comment by sangshuduo** [comment]
The nodejs connector already supports node v12.
