### ISSUE TITLE
the simple query , add tag for not exist sub table , just no exception

### ISSUE THREAD

**Issue by zeje** [taosdata/TDengine#17916]
version 3.0.1.6 taosadapter

创建了超级表，对应子表要插入数据才会有子表数据。
很多情况查询子表，是不确定子表是否产生的了。sql语句能不能加一个标记，让它不报错。
 select count(id) total from loctube.event_tdstore_weather_888888100016671

目前不定时报不同的错误
1. execute tdengine sql error [Fail to get table info, error: Database not ready
2. Fail to get table info, error: Unable to establish connection
3. Table does not exist
4. query no ready
5. Unable to establish connection

3.1.0.5的时候没问题，docker升级到3.1.0.6 crash之后（从docker启动改为host启动），
就经常报错上面的错误。重启taos、taosadapter还是报错（Fail to get table info），而且是固定的超级表对应的子表的count报错。自己到dbweaver（无论是rest还是jdbc）执行报错（Table does not exist），并没有其他错误。

**Comment by zeje** [comment]
经过沟通，可能是这种原因引发性能问题：
压力测试过程中，时间戳一样，引发数据更新，存在太多版本的数据。

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
