### ISSUE TITLE
computing the sum of the hourly electricity consumption of multiple meters

### ISSUE THREAD

**Issue by kmijnuhb** [taosdata/TDengine#17939]
td 2.6				
SELECT
	sum(Diff (VALUE)),
	addr
FROM
	chun_data.data_nenghao_lj
WHERE
	addr IN (
		'271906101025',
		'271906101119'
	)
AND ts > '2022-11-01 05:00:00'
AND ts < '2022-11-01 08:00:00' INTERVAL (1h, 10s)
GROUP BY
	tbname
求这两个设备的5，6，7点的电量走值和写sql,试了多次都失败，想得出结果  5点 2个设备总走值 10，6点2个设备总走值 30，7点2个设备总走值 50

下面这个语句可以直接得出5，6，7点的2个设备电量走值之和
SELECT
	sum(VALUE)
FROM
	(
		SELECT
			SPREAD (VALUE)
		FROM
			chun_data.data_nenghao_lj
		WHERE
			addr IN (
				'271906101025',
				'271906101119'
			)
		AND ts > '2022-11-01 05:00:00'
		AND ts < '2022-11-01 08:00:00' INTERVAL (1h, 10s)
		GROUP BY
			tbname
	) INTERVAL (1h, 10s)
	
	查询结果
	
	{
        "_status": "succ",
        "_head": [
                "ts",
                "sum(value)"
        ],
        "_rows": 3,
        "_column_meta": [
                {
                        "columnName": "ts",
                        "code": 9,
                        "size": 8,
                        "typeName": "timestamp"
                },
                {
                        "columnName": "sum(value)",
                        "code": 7,
                        "size": 8,
                        "typeName": "double"
                }
        ],
        "_data": [
                [
                        "2022-11-01 05:00:10.000",
                        6560.5
                ],
                [
                        "2022-11-01 06:00:10.000",
                        6.75
                ],
                [
                        "2022-11-01 07:00:10.000",
                        6
                ]
        ]
}

唯一的疑问时SPREAD函数得出的最大值最小值之差，和每个小时第一条的记录之差有时会不一样，原因在于
5：01  1
5：59  11
6：01  12
6：59  22
使用SPREAD函数  结果每小时最大值最小值之差都是10，
但是实际上 5点  12-1=11，走了11，忽略了5：59到6：01走的1，
这个问题有办法解决吗

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
