### ISSUE TITLE
how to get memory cost of TDengine

### ISSUE THREAD

**Issue by a1424132610** [taosdata/TDengine#17952]
我现在想测试 Tdengine插入数据大小跟mysql插入数据大小进行对比，Tdengine有相关的查询方法？

**Comment by yu285** [comment]
您的意思是磁盘占用？

**Comment by yu285** [comment]
还是内存

**Comment by yu285** [comment]
![img_v2_1c62a57c-f9ea-4b8c-8a2e-a8b8beda82eg](https://user-images.githubusercontent.com/74105241/202845194-c7484786-0ef0-4d3d-9ec3-36a14c461979.png)

关于log过大，可以参考：https://docs.taosdata.com/taos-sql/database/

查库的大小最直接的办法就是show dbname.vgroups,然后找到硬盘上vnode目录中对应编号的vnode目录，然后算出大小
