### ISSUE TITLE
taosd3.0.1.5 start failed

### ISSUE THREAD

**Issue by hecao100** [taosdata/TDengine#17978]
taosd3.0.1.5版本
systemctl restart taosd
无法启动，报错日志如下
DND ERROR vgId:6, msg:0x7f81cc005160 failed to put into vnode queue since Invalid Vgroup ID, type:submit qtype:4, gtid:0x0:0x0

这个环境是正常运行中，taos3节点突然掉线（offline），手动无法重启成功
<img width="1031" alt="ba887d42-94af-4f59-895f-4494de9d945d" src="https://user-images.githubusercontent.com/108709887/200707358-dec883c8-8ece-4fd4-8233-1723f8f8a22e.png">

**Comment by hecao100** [comment]
11/09 10:30:01.699822 00020987 VND ERROR vgId:8, msg:0x7fe8a80062f0 failed to process since restore not finished, gtid:0xdb7514391542fa4e:0x764405a3915db643
11/09 10:30:01.703617 00020987 VND ERROR vgId:8, msg:0x7fe8a80062f0 failed to propose since Database not ready, code:0x80000014, gtid:0xdb7514391542fa4e:0x764405a3915db643

**Comment by hecao100** [comment]
我升级了3.0.1.5版本到3.0.1.6版本，第三个节点（原启动失败的节点），还是无法启动，错误日志如下
11/10 14:02:24.629497 00010534 WAL ERROR vgId:6, WAL log entries incomplete in range [4105563, 4106043], aligned with snaphotVer:4105562
11/10 14:02:24.630383 00010534 WAL ERROR vgId:6, cannot open wal since repair meta file failed
11/10 14:02:24.631201 00010534 VND ERROR vgId:6, failed to open vnode wal since WAL log incomplete. wal:/data/tdengine/data/vnode/vnode6/wal
11/10 14:02:24.632303 00010534 DND ERROR vgId:6, failed to open vnode by thread:0
11/10 14:02:24.633627 00010535 WAL ERROR vgId:10, WAL log entries incomplete in range [34504439, 34509544], aligned with snaphotVer:34504438
11/10 14:02:24.634253 00010535 WAL ERROR vgId:10, cannot open wal since repair meta file failed
11/10 14:02:24.634768 00010535 VND ERROR vgId:10, failed to open vnode wal since WAL log incomplete. wal:/data/tdengine/data/vnode/vnode10/wal
11/10 14:02:24.635852 00010535 DND ERROR vgId:10, failed to open vnode by thread:1
11/10 14:02:24.646830 00010502 DND ERROR there are total vnodes:5, opened:3
11/10 14:02:24.647623 00010502 DND ERROR failed to open vnode since success
11/10 14:02:24.648149 00010502 DND ERROR failed to init vnodes-mgmt since success
11/10 14:02:24.648814 00010565 SYN ERROR vgId:7, sync propose not leader, follower, type:sync-leader-transfer
11/10 14:02:24.653697 00010565 SYN ERROR vgId:11, sync propose not leader, follower, type:sync-leader-transfer
11/10 14:02:24.617579 00010502 UTL apoll url not load
11/10 14:02:24.617628 00010502 UTL load from cfg file /etc/taos//taos.cfg success
11/10 14:02:24.617633 00010502 UTL failed to load env file: .env
11/10 14:02:24.617636 00010502 UTL load from env variables cfg success
11/10 14:02:24.617682 00010502 UTL timezone format changed from Asia/Shanghai (CST, +0800) to Asia/Shanghai (CST, +0800)

**Comment by yu285** [comment]
升级 3017后，问题解决，做关闭处理
