### ISSUE TITLE
执行JDBC查询返回ResultSet对象，获取的值全部为NULL

### ISSUE THREAD

**Issue by include0000** [taosdata/TDengine#17983]
String sql = "select * from gypaas.properties_weldmqttdevicemodel order by _ts desc limit 1";

            Class.forName("com.taosdata.jdbc.rs.RestfulDriver");
            String jdbcUrl = "jdbc:TAOS-RS://127.0.0.1:6041/gypaas?user=root&password=taosdata";
            Connection conn = DriverManager.getConnection(jdbcUrl);

            Statement stmt = conn.createStatement();
            ResultSet sett = stmt.executeQuery(sql);

            while (sett.next()){
                Timestamp tem = sett.getTimestamp(1);
                int ssett = sett.getInt(2);
                System.out.println(ssett);
            }

**Comment by include0000** [comment]
<dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>3.0.0</version>
        </dependency>

**Comment by include0000** [comment]
DB  Version  ：2.6.0.10

**Comment by yu285** [comment]
please use 2.0.40 JDBC , 3.0.0 is used for 3.x TDengine database
