### ISSUE TITLE
Macos TDengine-server-3.0.1.6-macOS-x64.pkg setup failure ？

### ISSUE THREAD

**Issue by sexbee** [taosdata/TDengine#17994]
**Bug Description**
Macos TDengine-server-3.0.1.6-macOS-x64.pkg setup failure ？

 

**Environment (please complete the following information):**
 - OS: [macos sierra 10.12.6]
 
 - TDengine Version [TDengine-server-3.0.1.6-macOS-x64.pkg ]

**Additional Context**
:$ taos
dyld: Library not loaded: /opt/taos/TDengine/debug/build/lib/libtaos.1.dylib
  Referenced from: /usr/local/bin/taos
  Reason: no suitable image found.  Did find:
	/usr/local/lib/libtaos.1.dylib: cannot load 'libtaos.1.dylib' (load command 0x80000034 is unknown)
	/usr/local/Cellar/tdengine/3.0.1.5/driver/libtaos.3.0.1.5.dylib: cannot load 'libtaos.3.0.1.5.dylib' (load command 0x80000034 is unknown)
Abort trap: 6

**Comment by xiaochuanliang** [comment]
请问解决了吗

**Comment by yu285** [comment]
我们检查下。

**Comment by yu285** [comment]
我试了 3017 的包，没有遇到这个问题。可以加我微信15652223354 做具体排查

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
