### ISSUE TITLE
请问能否提供文档的offline阅读的办法？

### ISSUE THREAD

**Issue by the-oaks** [taosdata/TDengine#180]
https://www.taosdata.com/en/documentation/

除了一页一页单独Chrome保存以外。谢谢

**Comment by StoneT2000** [comment]
Thanks for the suggestion, I will upload offline documentation files in HTML form and a equivalent PDF form soon.

**Comment by StoneT2000** [comment]
#181
@the-oaks 
offline文档放上去了，放到 *documentation/tdenginedocs-en* 和 *documentation/tdenginedocs-cn*

**Comment by the-oaks** [comment]
@StoneT2000 thanks!
