### ISSUE TITLE
 System out of disk space 

### ISSUE THREAD

**Issue by wang233work** [taosdata/TDengine#18018]
插库失败报错 System out of disk space，检查tmp文件夹
![image](https://user-images.githubusercontent.com/57163477/201012665-7c78a39e-f3c8-43a2-9916-aeaf19abfa87.png)
发现并没有什么大文件，随即重启了TDengine发现问题解决，TDengine版本2.6.0.6使用docker-compose拉起的。

**Comment by wang233work** [comment]
![image](https://user-images.githubusercontent.com/57163477/201013562-b532b81e-33e9-4df0-af4d-edb0ae43cef4.png)

**Comment by yu285** [comment]
logdir datadir tmpdir 都有自己的min value，在/etc/taos/taos.cfg指定

可以在报错的时候留意下
