### ISSUE TITLE
Usage of pthread_once

### ISSUE THREAD

**Issue by haoyifan** [taosdata/TDengine#1801]
I see the code use pthread_once extensively to run initialization code. Just curious what's the rationale behind using pthread_once (sorry this might be a dumb question but I don't know much about pthread_once). The only reason I can think of is to do lazy evaluation where you can push the initialization code as late as possible.

This complicates the code a bit because it's unclear how error should be handled in the initialization flow. For example, vnodeInit() is initiated by pthread_once, but if taosInitIntHash() fails the program never gets a chance to properly handle this error:

```
static void vnodeInit() {
  vnodeInitWriteFp();
  vnodeInitReadFp();

  tsDnodeVnodesHash = taosInitIntHash(TSDB_MAX_VNODES, sizeof(SVnodeObj *), taosHashInt);
  if (tsDnodeVnodesHash == NULL) {
    dError("failed to init vnode list"); <--- failure to initialize tsDnodeVnodesHash will cause subsequent calls that rely on it to fail.
  }
}

int32_t vnodeCreate(SMDCreateVnodeMsg *pVnodeCfg) {
  int32_t code;
  pthread_once(&vnodeModuleInit, vnodeInit); <--- called here
```

**Comment by liuyq-617** [comment]
Thanks for your feedback, we will process your request as soon as possible

**Comment by freemine** [comment]
@haoyifan no, pthread_once is not for lazy-load purpose, it's there for once-and-only-once initialization in the whole process life time. But the problem you mentioned exists, attention shall be taken to handle that init-failure problem.

http://man7.org/linux/man-pages/man3/pthread_once.3p.html

**Comment by haoyifan** [comment]
@freemine Thanks for the response. I took a look at the page you linked and found a use case:

> The use of pthread_once() not only supplies an implementation-guaranteed means of dynamic initialization, it provides an aid to the reliable construction of multi-threaded and realtime systems.

So pthread_once is useful if the following two requirements are needed:
1. The initialization needs to be dynamic and can not be made static. This is usually applicable to library functions where the library goes scaffolding the first time a library function is called (they cannot be made static unless the library requires a init call, which is ugly IMO).
2. If the initialization is dynamic, and has the potential to be called concurrently by multiple threads, pthread_once guarantees the init function is only called once.

Correct me if I'm wrong, but I feel like most of the initialization in the TDengine system can be made static. Why not put it somewhere in the initialization path? I find enclosing these initialization functions in pthread_once harder to reason about because now the initialization depends on when the query comes into the system.

As a side note, some of the pthread_once might execute multiple times. For example, vnodeRelease() would reinitialize **vnodeModuleInit** back to **PTHREAD_ONCE_INIT**. So vnodeInit() could be called multiple times even it is enclosed by pthread_once.

**Comment by freemine** [comment]
vnodeRelease, wow, that's interesting, I don't know if there's any other 'guarding' codes/logic to prevent from enterring data-race-condition. meanwhile, I am also curious about the phylosphy of `pthread_cancel` call.

**Comment by localvar** [comment]
@haoyifan this is a bug, it is not correct to reinitialize a pthread_once_t object, besides the issue you and @freemine mentioned, it may also cause resource leaks: the pthread library does not expose the details of pthread_once_t, if it has references to other dynamic allocated objects, theses objects leaks in a re-initialization.

**Comment by sangshuduo** [comment]
no update, close it.
