### ISSUE TITLE
LAST_ROW doesn't get last row 

### ISSUE THREAD

**Issue by chenquan** [taosdata/TDengine#18014]
**Bug Description**
LAST_ROW函数获取的值不是最后一条数据.
mqtt_connection_history是超级表, 查询语句如截图所示
**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**
![b2859f28beca72bfb6f7813d59af6b4](https://user-images.githubusercontent.com/20548053/200982608-968cc1a5-0319-40da-8cea-a35895e366b5.png)
![1900bf5a8331957155f36e92ef974a6](https://user-images.githubusercontent.com/20548053/200982748-1d67e569-e7b8-4a7c-a6f4-1b8b288e34d3.png)

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0] : CentOS 7.6
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7] : 3.0.1.6
 - TDengine Client: windows 3.0.1.6

**Additional Context**

**Comment by yu285** [comment]
可以加微信 15652223354 做具体排查。
