### ISSUE TITLE
taosadapter not running

### ISSUE THREAD

**Issue by whileW** [taosdata/TDengine#18023]
**Bug Description**
taosadapter在docker中没有运行，也没有办法手动执行，提示 Illegal instruction
![image](https://user-images.githubusercontent.com/31883707/201032763-9e70d6d5-e93b-4201-bced-f0cea789235e.png)
![image](https://user-images.githubusercontent.com/31883707/201033020-8ce9574d-5d7b-40c5-bbd6-4486856e1d5e.png)
我应该怎么开启taosadapter？

**Environment (please complete the following information):**
 - OS: [Mac M2]
 - TDengine Version [3.0.1.6]
 - docker image tdengine/tdengine:latest

**Additional Context**

**Comment by sangshuduo** [comment]
应该要 pull arm64 版本的镜像

**Comment by whileW** [comment]
打扰了，我的问题
