### ISSUE TITLE
desc: left.ts = right.ts is expected in join expression

### ISSUE THREAD

**Issue by chenna123456** [taosdata/TDengine#18028]
我需要对两个子查询进行联合查询，在2.4版本的时候实验通过的，但是升级到3的时候，就失败了。
我的sql:

select *
from
(SELECT first(time) as ts,first(data)as data FROM iot_cloud.da123_read_longitude_rtk
INTERVAL(1s)) lon,
(SELECT first(time) as ts,first(data)as data FROM iot_cloud.da123_read_latitude_rtk
INTERVAL(1s)) lat
where lon.ts = lat.ts

错误信息：
desc: left.ts = right.ts is expected in join expression

**Comment by chenna123456** [comment]
开始在2.4是对超级表进行查询，迁移到3.0后发现sql不可用，然后用子表进行查询也不行

**Comment by yu285** [comment]
这个问题在 3.0 分支上已经修复，可以编译尝试
![image](https://user-images.githubusercontent.com/74105241/201805149-50ccf01d-97d6-4aa6-9a5f-2a2f55d26c3a.png)

**Comment by chenna123456** [comment]
已收到，暂时我们已经在项目代码层面逻辑修复了该问题，等稍后版本更新以后，又尝试



---Original---
From: "Yu ***@***.***&gt;
Date: Tue, Nov 15, 2022 09:37 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [taosdata/TDengine] desc: left.ts = right.ts is expected in joinexpression (Issue #18028)




 
这个问题在 3.0 分支上已经修复，可以编译尝试
