### ISSUE TITLE
where clause lead to database crash

### ISSUE THREAD

**Issue by 123key** [taosdata/TDengine#18035]
环境说明：
WIN10中安装docker
使用docker-compose安装的数据，docker-compose见附件
TDengine: version: 3.0.1.5

复现步骤：
一：建立一个数据库
二：建立一个超表，对单子表进行数据多线程导入，1000万导入一次，然后删除子表，循环导入，N次
三：使用AVG聚合函数查询语句select AVG(long_v) from ts_kv where entity_id [='d1';例如该语句对超表查询，然后产生数据库宕机重启的问题。

添加到百度网盘中，表示tsingjet_cloud.ts_kv表。是docker容器，包含日志文件
链接：https://pan.baidu.com/s/1cspAn0kFwsxuuQvVTxUpeQ?pwd=knyt 
提取码：knyt

**Comment by yu285** [comment]
请问有设置 coredump 文件的生成吗。

如果没有，请：

1. 使用命令 ulimit -c unlimited (不限制core文件大小)来开启 core dump 功能
2. 指定内核转储的文件名和目录：sudo sysctl -w kernel.core_pattern='/corefile/core-%e-%p',  其中/corefile目录是可以自己指定的。
          永久化：echo '/corefile/core_%e-%p' | sudo tee /proc/sys/kernel/core_pattern
3.查询sysctl kernel.core_pattern，是否设置成功。

4. mkdir /corefile && chmod 777 /corefile

5.复现一下问题，在/corefile下就可以看到 core 文件了。

6.sudo gdb taosd corefile名字

7.输入bt，把输出信息发给我们。

如果有设置core文件的话，那就直接执行 6-7 步即可。如果没有安装gdb ，麻烦自行安装一下。

**Comment by 123key** [comment]
这个问题TDengine开发人员已经复现了
