### ISSUE TITLE
add a new way to insert data

### ISSUE THREAD

**Issue by zeje** [taosdata/TDengine#18045]
插入数据能否添加一种语法：
1. 字段顺序非默认
2. 库中有多个字段，实际上插入语句只需要指定的字段
3. 插入同一个超级表的多个子表的数据

假如：stable 有5个tag,10个value
现有的写法
insert into table1 (valName2,valName1) values (val2,val1)
insert into table2 (valName2,valName1) values (val2,val1)
insert into table3 (valName2,valName1) values (val2,val1)
新语法形式：
insert into stable stableName  values (valName2,valName1)
table1 values (val2,val1)
table2 values (val2,val1)
table3 values (val2,val1)
这样，每个子表无需再指定tag名称和val名称，可以节省字符

使用场景：
1. 程序使用的是物模型，经过前后对数据字段的变更，物模型中属性的顺序，可能无法保证与数据库中的字段的顺序一致。
2. 批量插入时，减少传输带宽，如下若有5000条
insert into tableName (tagName2,tagName1) tags (tag2,tag1) (valName2,valName1) values (val2,val1)
使用建议的新语法，可以节省 4999个如下的字符
 (tagName2,tagName1)  (valName2,valName1)
在大量插入情况下，可以减少很多字节，提高插入性能

**Comment by zeje** [comment]
同理：
InfluxDB 行协议
OpenTSDB 行协议
也存在浪费流量，浪费空间的问题

**Comment by zeje** [comment]
类似influx的csv插入
https://docs.influxdata.com/influxdb/v2.0/write-data/developer-tools/csv/

**Comment by yu285** [comment]
我们一直对外宣称的是 ，子表才是存储数据的实体。所以所有语法，insert into 的目标都是 子表，没有对超级表写入的，这涉及到语法层面的变动。

但我理解你这个行为对数据库实际执行的计划没有影响，性能基本是一样的。所以可以理解为一个特定场景的语法优化。但是实际执行上，我并不确认是否会对原有代码会造成比较大的改动风险，因此我觉得这个推动起来是有难度的。

INSERT INTO d1 (ts, current, phase) VALUES ('2021-07-13 14:06:33.196', 10
.27, 0.31) 

 d2 (ts, current, phase) VALUES ('2021-07-13 14:06:33.196', 10 ,1)

 d3 (ts, current, phase) VALUES ('2021-07-13 14:06:33.196', 10 ,1)

 d2 (ts, current, phase) VALUES ('2021-07-13 14:06:33.196', 10 ,1);


以当前语法为例，这里他省下的就是“ (ts, current, phase) VALUES ” 这一段字符串乘以行数，影响是有限的。
