### ISSUE TITLE
“High Performance Writing” DataBaseMonitor/SQLWriter  issue

### ISSUE THREAD

**Issue by 123key** [taosdata/TDengine#18040]
DataBaseMonitor该类在getTableCount方法中存在问题；
sql执行show test.stables时只能查询到name,但是代码中有long转化并且查询字段下标越界

SQLWriter该类中在判断sql长度的时候查询长度一直为0会导致代码一直执行flush操作

SQLWriter该类中Sql拼接逻辑存在问题，会导致insert into错误代码导入

![DataBaseMonitor](https://user-images.githubuserconten
![SQLWriter ](https://user-images.githubusercontent.com/44826214/201239414-a76a1e52-0c95-4b68-a039-4ded5bac4475.jpg)
t.com/44826214/201239224-1cc6a152-cfd6-4391-9547-798272d5c539.jpg)

![SQLWriterCode](https://user-images.githubusercontent.com/44826214/201239985-01d6e190-5637-44b3-b7b9-2e7342b1f32d.jpg)

**Comment by 123key** [comment]
[](url)
![DataBaseMonitor](https://user-images.githubusercontent.com/44826214/201240617-ce92d409-c75a-4a2e-85d2-6a9cd2b077a8.jpg)

**Comment by yu285** [comment]
您好，高效写入的代码和3.0还在适配中，我们正在处理

**Comment by yu285** [comment]
感谢您的反馈
