### ISSUE TITLE
 Database not ready

### ISSUE THREAD

**Issue by aispringli** [taosdata/TDengine#18055]
**Bug Description**
Database not ready .

**To Reproduce**
1. use k8s deploy 3 node  follow doc
2. config 3 Mnode, everyone is Mnode
3. sometimes node happen error and the taos-check is failed, so it always restart
4. in the time, first node sync failed,  because the second and three is failed to start
5. cannot but reomve taos-check and redeploy
6. finally, DND ERROR failed to send status msg since Database not ready, need retry, numOfEps:3 inUse:0

**Expected Behavior**
 DND ERROR failed to send status msg since Database not ready, need retry, numOfEps:3 inUse:0

**Screenshots**

**Environment (please complete the following information):**
 - OS: k8s
 - Memory, CPU, current Disk Space: 4C8G 
 - TDengine Version : 3.0.16

**Additional Context**

**Comment by yu285** [comment]
for the 3-mnode  module of TDengine ,we suggest test it until 3.0.1.7 .

**Comment by yu285** [comment]
3.0.1.7 would be released this week。

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
