### ISSUE TITLE
Too many core files causing the disk to be written full in version 3.0.1.6

### ISSUE THREAD

**Issue by xiao781433561** [taosdata/TDengine#18080]
**Bug Description**
升级V3.0.1.6之后，/根目录下每天会产生大量的core.XXX文件，导致磁盘被写满taosd进程崩溃。

**To Reproduce**
1. 安装V3.0.1.5，创建数据库和超级表（默认参数），使用taosadapter写入/读取物联网数据；
2. 停止、卸载V3.0.1.5，安装V3.0.1.6，保留历史数据，启动；
3. 根目录每天产生大量core.xxxx文件，直至磁盘写满，进程崩溃

**Expected Behavior**
不要产生太多core文件，如果是代码报错，能够修复代码。

**Screenshots**
gdb info：
![image](https://user-images.githubusercontent.com/20273462/201456597-b918bdcb-281e-40b4-9ad4-04d5ce20f420.png)

[root@node-data /]# sudo gdb taosd core.30068
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/taos/bin/taosd...done.
[New LWP 30119]
[New LWP 30116]
...
[New LWP 30083]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/bin/taosd'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000006d828f in tsdbRetrieveCacheRows (pReader=0x7ff6b50224e0, pResBlock=0x7ff734f6c6f0, slotIds=0x7

**Environment (please complete the following information):**
 - OS: [CentOS 7.9]
 - 16G内存，100G硬盘 
 - TDengine Version [3.0.1.6]

**Additional Context**
V3.0.1.5无此现象（或者有产生core文件但极少，所以没有注意）

**Comment by yu285** [comment]
麻烦在 gdb 中输入 bt，得到完整堆栈信息，发在这里，谢谢

**Comment by yu285** [comment]
sudo gdb taosd corefilename

**Comment by xiao781433561** [comment]
![image](https://user-images.githubusercontent.com/20273462/201627963-9a9c1fad-ab77-4c2b-a5bc-d3d34096e209.png)

**Comment by yu285** [comment]
f 6 

p sql

**Comment by xiao781433561** [comment]
![image](https://user-images.githubusercontent.com/20273462/201848779-99e45bc8-889d-4c60-bd1c-176498d2d123.png)

**Comment by yu285** [comment]
f 5

p sql

**Comment by yu285** [comment]
也可以加我微信 15652223354 做具体排查

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
