### ISSUE TITLE
CODE_OF_CONDUCT-CN.md

### ISSUE THREAD

**Issue by EchoHou2000** [taosdata/TDengine#18096]
Do you need Chinese translation of CODE_OF_CONDUCT.md? I can do this job.

**Comment by arielyang** [comment]
Very happy to see this, you can refer to the version in develop branch

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
