### ISSUE TITLE
Readability of feature-request.md

### ISSUE THREAD

**Issue by LookSin** [taosdata/TDengine#18102]
I think the readability of feature-request.md can be better. Can I improve it please?

**Comment by yu285** [comment]
could you provide the link here?

**Comment by 13917781779** [comment]
发的什么东西，你电话多少？













苏佳音


***@***.***







电子名片新出VIP模板啦，快来体验>>




扫一扫,


快速添加名片到手机




--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: Yu Chen  ***@***.***>
 

 
 发送时间: 2022-11-28 20:25:44
 

 
 收件人:taosdata/TDengine ***@***.***> 

 
 抄送:Subscribed ***@***.***> 

 
 主题: Re: [taosdata/TDengine] Readability of feature-request.md (Issue#18102)
 





 could you provide the link here?

**Comment by LookSin** [comment]
Sorry. I feel that my opinion is not necessary after my careful observation. I will close this issue.
