### ISSUE TITLE
query and write performance issue

### ISSUE THREAD

**Issue by 123key** [taosdata/TDengine#18105]
环境：
win10中安装docker
tdengine 3.0.1.5
异常触发：
1：使用高效写入代码
2：修改配置如下
int readTaskCount = 2;
int writeTaskCount = 16;
int tableCount = 1;
int maxBatchSize = 10000;
3：启动代码后一直查询，后期会越来越慢SQL:select count(*) from test.meters ;
![读写性能问题](https://user-images.githubusercontent.com/44826214/201554870-e2ee6d38-2dd1-4835-939b-1a22d9ae5df3.png)

**Comment by yu285** [comment]
taos_query_a 么

**Comment by 123key** [comment]
没看懂您的问题，taos代码是
https://docs.taosdata.com/develop/insert-data/high-volume/
这个链接中的代码

**Comment by yu285** [comment]
高效写入模块的代码还在适配 3.0 版本，目前可能不具备参考价值。

如果数据都写进侯，数据库通过shell查询都很慢，可以加我微信 15652223354 ，做具体排查。
