### ISSUE TITLE
taosdump import issue

### ISSUE THREAD

**Issue by kugua-bin** [taosdata/TDengine#18129]
使用taosdump将测试服务器上的数据导出，再导入到本地虚拟机上，然后用同一个sql查询时，两边数据不一致。
（如图所示，图左是导入后虚拟机上的数据，图右是服务器上原始数据）
![1668417794113](https://user-images.githubusercontent.com/57973357/201624175-a4a91823-6659-4ae2-b372-2ea04ed046e2.jpg)

**Comment by sangshuduo** [comment]
请提供一下导入前服务版本，导入后服务版本，taosdump 版本，表结构信息
导入前服务 taos.cfg 和 导入后服务的 taos.cfg 有没有什么区别？

**Comment by kugua-bin** [comment]
> 请提供一下导入前服务版本，导入后服务版本，taosdump 版本，表结构信息 导入前服务 taos.cfg 和 导入后服务的 taos.cfg 有没有什么区别？

导出和导入的版本都是3.0.1.5，taosdump版本都是2.2.6，taos.cfg没有区别。
表结构如下图
![1668649241598](https://user-images.githubusercontent.com/57973357/202333560-fc16f30c-b9e5-4c81-a975-b73d0daec626.jpg)

**Comment by sangshuduo** [comment]
![image](https://user-images.githubusercontent.com/825729/202336880-50cb231c-d70a-4fe4-b1b8-0c59b0790798.png)

请看我的验证过程，无法重现你说的问题
