### ISSUE TITLE
Maximum Database Size Support?

### ISSUE THREAD

**Issue by susu3621** [taosdata/TDengine#1813]
Do we support Maximum Database Size option similar as sqlite? 
https://www.sqlite.org/limits.html

Didn't find any hint in http://tdengine.net/cn/documentation/administrator/#%E6%9C%8D%E5%8A%A1%E7%AB%AF%E9%85%8D%E7%BD%AE
Which will be nice for arm device, and storage limited device.

**Comment by liuyq-617** [comment]
Indeed, as you can see, there are currently not too many control parameters. We will gradually open some parameter settings in the future
