### ISSUE TITLE
Wrong result of last_row() function in v3.0.1.6

### ISSUE THREAD

**Issue by xiao781433561** [taosdata/TDengine#18131]
**Bug Description**
select last_row(*) from stable partition by tagname; 返回了错误结果，且效率较低。

**To Reproduce**
1. 安装V3.0.1.5，创建数据库和超级表（默认参数），使用taosadapter写入/读取物联网数据（大约4000子表，每个子表有一个tag:点号：point_code）；
2. alter database xxx cahemodel 'both' 设置缓存
3. 执行查询语句 ：查询所有子表的最新数据快照： select last(*) from stable partition by point_code; 查出4000数据，但是耗时15秒；
4. last换成last_row再试：select last_row(*) from stable partition by point_code; 只有2条数据；
5. group  by 和partition by 表现一致；

**Expected Behavior**
last和last_row 至少一个正确且高效的查询超级表快照值。

**Screenshots**
![355f864c89c7be1183e94eb3cf32152](https://user-images.githubusercontent.com/20273462/201624796-b2d3ef66-67ae-407f-a41b-07aab8122be7.jpg)
![5e23cfd26f6164d3f14204a481fbe5c](https://user-images.githubusercontent.com/20273462/201624881-0e4f495f-fe6b-40e2-8fc0-72968b57282e.jpg)
![1236920e2ef29c58211f2906e661a71](https://user-images.githubusercontent.com/20273462/201624880-2c82050a-1da4-4e46-a506-02a76dab8f2f.jpg)

**Environment (please complete the following information):**
 - OS: [ CentOS 7.9]
 - Memory 16G
 - TDengine Version [3.0.1.6]

**Additional Context**
V3.0.15版本，设置cachemodel之后，last_row函数能正确查询所有数据，查询时间0.1秒左右，升级3.0.1.6之后结果不对。

**Comment by yu285** [comment]
taosdump -o 路径 库名 singledata 

麻烦导出一下数据，然后压缩发我们吧

**Comment by WankkoRee** [comment]
相同的问题，在最新的`3.0.2.3`仍然存在，将数据库和客户端都降级到`3.0.1.5`后确实解决了问题。

----

具体情况：

超级表`powers`中有 4000+ 条记录，每个记录对应一张表（因为数据是刚采集用来测试性能的，所以正好一条记录一张表）。

在`3.0.2.3`执行`select last_row(*) from powers partition by tbname;`，大约跑了一个小时（记得是 3500s+），期间CPU占用几乎一直是`100%`，所以差不多算是 1 条记录跑了快 1 秒钟？所以猜测`last_row`函数在某些情况下性能存在问题，于是找到了这个 issue。

根据提问者的建议换到`3.0.1.5`后，重新采集数据并测试（数据量一致，都是 4000+），同样的语句只需要 0.5 秒钟不到就完成了查询。

----

如需数据库测试样本请联系我邮箱`wkr@wkr.moe`。

**Comment by yu285** [comment]
> 在`3.0.2.4`上查询速度正常了，似乎是修复了？

可能是。可以再观察一段时间，如果又遇到可以加微信 a15652223354我们具体排查下
