### ISSUE TITLE
pyton连接包

### ISSUE THREAD

**Issue by wangjiancc** [taosdata/TDengine#18158]
服务端客户端均为 3.0.0.16，  Python 已经安装 pip3 install taos taospy ，前几天能正常操作数据库，插入查询数据，今天报 AttributeError: module 'taos' has no attribute 'TaosStmt' ，反复安装几次后，
报 ModuleNotFoundError: No module named 'taos'

**Comment by sangshuduo** [comment]
taos 不是 TDengine 连接器，只需要装 taospy

**Comment by wangjiancc** [comment]
现在 最新版是taospy-2.6.5 吗？    pip3 install  taospy -U  安装后，程序仍然报错，ModuleNotFoundError: No module named 'taos'  。 
               因为要使用   conn = taos.connect(
