### ISSUE TITLE
select * leads to a  crash

### ISSUE THREAD

**Issue by wangjiancc** [taosdata/TDengine#18155]
版本： TD 3.0.1.6
select count(*) from XXX,  如果是一张十几亿条数据的超级表，则查询不出数据，会报： DB error: Unable to establish connection，之类的错误。
<img width="898" alt="3b9afc5561798657bea324c36200074" src="https://user-images.githubusercontent.com/16346126/201838296-09a6576b-7202-4809-b598-a7444677f817.png">

**Comment by zeje** [comment]
1. 不建议用*，建议用count(时间戳)。
2. 一条数据存在多个版本，就是时间戳相同反复插入，这种会crash。避免此类数据。
3. 其他，也会crash

3.0.1.6 7千万数据，经纬度均为0的数据不会超过500条，但如下语句导致crash
select count(_ts) from loctube.event_gps where lat = 0 and lng = 0

**Comment by yu285** [comment]
可以加我微信远程看下：15652223354

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
