### ISSUE TITLE
TAOS_ADAPTER error "Error in plugin: read udp [::]:6044: use of closed network connection" model=statsd

### ISSUE THREAD

**Issue by chenjiaxing6** [taosdata/TDengine#18159]
My tdengine version is 2.4.3. There were two crashes yesterday and today. The following is the error log of/var/log/taos

11/15 09:58:41.706998 00001713 TAOS_ADAPTER error "Error in plugin: read udp [::]:6044: use of closed network connection" model=statsd

<img width="913" alt="image" src="https://user-images.githubusercontent.com/42378713/201842688-88cd173d-8089-4b21-9f2b-240873f66e03.png">

What may be the cause of this error message？

**Comment by yu285** [comment]
version is 2.4.0.3 ?

**Comment by chenjiaxing6** [comment]
yes

**Comment by lichehuo** [comment]
I had the same problem: this is my app's logs:

{"level":"error","time":"2023-04-21T17:26:48.670047296+08:00","msg":"insert td is failed==Post \"http://10.180.1.58:6041/rest/sql\": read tcp 10.254.3.141:43382->10.180.1.58:6041: read: connection reset by peer
{"level":"error","time":"2023-04-22T00:49:42.773945381+08:00","msg":"insert td is failed==Post \"http://10.180.1.58:6041/rest/sql\": read tcp 10.254.3.141:33912->10.180.1.58:6041: read: connection reset by peer,sql

{"level":"error","time":"2023-04-22T11:54:50.871181364+08:00","msg":"insert td is failed==Post \"http://10.180.1.58:6041/rest/sql\": write tcp 10.254.3.141:51062->10.180.1.58:6041: use of closed network connection

{"level":"error","time":"2023-04-22T13:50:50.679378043+08:00","msg":"insert td is failed==Post \"http://10.180.1.58:6041/rest/sql\": EOF
{"level":"error","time":"2023-04-22T13:50:52.369195002+08:00","msg":"insert td is failed==Post \"http://10.180.1.58:6041/rest/sql\": http: server closed idle connection
{"level":"error","time":"2023-04-22T13:50:52.369836751+08:00","msg":"insert td is failed==Post \"http://10.180.1.58:6041/rest/sql\": http: server closed idle connection
{"level":"error","time":"2023-04-22T13:50:52.371593224+08:00","msg":"insert td is failed==Post \"http://10.180.1.58:6041/rest/sql\": http: server closed idle connection

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
