### ISSUE TITLE
failed to connect tdengine by jdbc 3.0.2 driver on Mac

### ISSUE THREAD

**Issue by baikeh** [taosdata/TDengine#18164]
**Bug Description**
The following exception was throwed when using the JDBC3.0.2 driver:
```
java.lang.UnsatisfiedLinkError: 'com.taosdata.jdbc.TSDBException com.taosdata.jdbc.TSDBJNIConnector.setConfigImp(java.lang.String)'
	at com.taosdata.jdbc.TSDBJNIConnector.setConfigImp(Native Method)
	at com.taosdata.jdbc.TSDBJNIConnector.init(TSDBJNIConnector.java:42)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:157)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1682)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1774)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2835)
```

**Expected Behavior**
connect the tdengine and execute the sql command

**Screenshots**
![Screenshot 2022-11-15 at 15 30 54](https://user-images.githubusercontent.com/32256469/201858221-97c268dc-397e-4573-b856-e46363d7fb13.png)

**Environment (please complete the following information):**
 - OS: MacOS13 Ventura
 - CPU: Arm (Apple M1 Pro)
 - TDengine Version: 3.0.1.6
 - Client: TDengine-client-3.0.1.6-macOS-arm64
 - JDBC Version: 3.0.2
 - JDK: 11

**Additional Context**
It is only occurred when I used the native JDBC, works well against the TAOS-REST

**Comment by yu285** [comment]
收到我们处理下

**Comment by yu285** [comment]
我们的 mac shell 上，连接服务端以及查询写入都是正常的么

**Comment by luchangtx** [comment]
> 

shell是正常的，但是在java项目里用驱动原生连接 就会报这个错

**Comment by sunpe** [comment]
This problem occurs on ARM version macOS is because there are 2 architectures in `TDengine-client-macOS-arm64.pkg`. And the JNI of java11 or java8 cannot load the correct type architecture. The temporary solution is to change jdk and TDengine-client to x64 version.

**Comment by sunpe** [comment]
ARM 版的 mac 目前可以同时支持 X64 和 ARM64 类型的软件，TDengine client 需要依赖动态链接库，所以TDengine client 和JDK 类型需要相同，ARM版的JDK只能使用 ARM版的 TDengine client，x64版的 jdk 只能用 x64 版的 TDengine client，不能混着用。请检查本地的 JDK 和 TDengine client 版本类型 @luchangtx @baikeh 。

**Comment by evenson419** [comment]
> ARM 版的 mac 目前可以同时支持 X64 和 ARM64 类型的软件，TDengine client 需要依赖动态链接库，所以TDengine client 和JDK 类型需要相同，ARM版的JDK只能使用 ARM版的 TDengine client，x64版的 jdk 只能用 x64 版的 TDengine client，不能混着用。请检查本地的 JDK 和 TDengine client 版本类型 @luchangtx @baikeh 。

大佬，牛逼，我的可以了，但 REST方式还是连接不了。

**Comment by cesar-blog** [comment]
> ARM 版的 mac 目前可以同时支持 X64 和 ARM64 类型的软件，TDengine client 需要依赖动态链接库，所以TDengine client 和JDK 类型需要相同，ARM版的JDK只能使用 ARM版的 TDengine client，x64版的 jdk 只能用 x64 版的 TDengine client，不能混着用。请检查本地的 JDK 和 TDengine client 版本类型 @luchangtx @baikeh 。

解决了，顺带附上 ARM版mac的openjdk下载地址：
https://www.azul.com/downloads/?version=java-8-lts&os=macos&architecture=arm-64-bit&package=jdk
