### ISSUE TITLE
is null query return wrong values

### ISSUE THREAD

**Issue by 123key** [taosdata/TDengine#18185]
环境：
win10 docker安装
TDengine版本3.0.1.6

复现步骤：
创建超表，字段包含bigint类型
导入数据，有null和非null值
查询数据：
       select * from tsingjet_cloud.d1 ts where ts.long_v is not null ；
       select * from tsingjet_cloud.d1 ts where ts.long_v<>null;
两个值有问题

**Comment by 123key** [comment]
![3](https://user-images.githubusercontent.com/44826214/202057293-33aded74-518a-480e-928c-bfce859b299f.jpg)
![2](https://user-images.githubusercontent.com/44826214/202057301-2123b228-acaf-400c-b00e-9f48051f0572.jpg)
![1](https://user-images.githubusercontent.com/44826214/202057304-c24e224f-bc5a-4114-87f5-42fbab06fc92.jpg)

**Comment by 123key** [comment]
![37cad3732bf4ebaf6f1e86407e82677](https://user-images.githubusercontent.com/44826214/202058672-f7ef4403-73b7-4307-89d3-6475e268aa4c.png)
![6339bed68195922b44504d47d72dba0](https://user-images.githubusercontent.com/44826214/202058676-4df3b612-34e8-428f-ab1f-f9a17087e99e.png)

**Comment by freemine** [comment]
这个是sql标准.
null只能参与is / is not的比较. 其他诸如 =, <>, <, >， 你可以理解为，都是返回false.
你可以尝试select * from tsingjet_cloud.d1 ts where ts.long_v=null;
返回的应该也是0行数据。
