### ISSUE TITLE
taos_query doesn't return result occasionaly 

### ISSUE THREAD

**Issue by OrangeEffects** [taosdata/TDengine#18191]
TDengine Version 2.6.0.28   （与版本关系不大，多个版本都有这个问题）
windows 客户端，C API

多线程（10个）插入数据
批量插入，sql语句长度 65210 左右

taos_query 函数偶发卡死，不返回

//----------------

增加调试逻辑排查问题：
在 taos_query 前后写全局变量
```
m_td_insert_step=1;
m_td_result=taos_query(m_taos, sql);
m_td_insert_step=2;
```
开一个线程来检测 m_td_insert_step 来捕捉 taos_query 卡死的时刻，把当时执行的 sql 语句记录到日志
接着强制 taos_close(m_taos) ，发现 taos_query 还是卡住，并没有错误退出

单独写个测试程序执行上边记录的sql语句，正常，说明和sql语句没有关系。

。。。。。。。。。。。。。

所以 taos_query 在什么情况下可能卡住不返回？

你可以报错，你可以执行不成功，崩溃都行啊，现在是想救都救不回来！

**Comment by yu285** [comment]
可以添加下微信，做具体排查 ： 15652223354

**Comment by kdash19854** [comment]
我也是这种情况，同一个版本2.6.0.28 ，insert的时候会随机卡住不返回，兄弟解决了吗？

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
