### ISSUE TITLE
could not determine kind of name for C.taos_schemaless_insert_raw

### ISSUE THREAD

**Issue by pdlovedy** [taosdata/TDengine#18213]
进行生产消费的时候，创建topic时连接时

D:\xxxGO_WORKSPACE\pkg\mod\github.com\taosdata\driver-go\v3@v3.0.3\wrapper\schemaless.go:57:9: could not determine kind of name for C.taos_schemaless_insert_raw

**Comment by sangshuduo** [comment]
TDengine 需要 3.0.1.5 以上

**Comment by pdlovedy** [comment]
和demo校对了下，是driver-go的版本问题，镜像是最新的3.0.1.6，但是必须是这个driver
github.com/taosdata/driver-go/v3 v3.0.0

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
