### ISSUE TITLE
TDengine's version not match between the official website  sent and email  received 

### ISSUE THREAD

**Issue by laowengdiaodayu** [taosdata/TDengine#18280]
官方网站文件下载的版本和邮件发送的不一致

https://docs.taosdata.com/releases/tdengine/

![1f7d348751033ed7482769613b43079](https://user-images.githubusercontent.com/14109075/202857113-f2be7ce5-279b-4d74-86a5-5c2a649d958e.png)

![1faf476798b4e44704cb55cfc59d1a0](https://user-images.githubusercontent.com/14109075/202857128-7855258f-0fc4-4d97-ac19-742add7988e5.png)

**Comment by yu285** [comment]
感谢，我们正在处理，另，我们强烈建议优先使用 3.0.1.7 ，即版本号最大的版本。现阶段只做问题修复，所以版本号越大越稳定

**Comment by yu285** [comment]
问题已经修复，可以使用了。
