### ISSUE TITLE
Wrong SQL lead to taosadapter crash

### ISSUE THREAD

**Issue by aczael** [taosdata/TDengine#18288]
**Bug Description**
版本 3.0.1.7
通过Rest API 发送错误的SQL，会导致REST AP接口 挂掉需要重启才可以恢复

**To Reproduce**
1. 使用rest api 创建10000个表，分50条批量创建表命令
超级表格式
|ts                             | TIMESTAMP            |           8 |
|
 e                              | DOUBLE               |           8 |
|
 var                            | DOUBLE               |           8 |
|
 e1                             | DOUBLE               |           8 |
|
 e2                             | DOUBLE               |           8 |
|
 e3                             | DOUBLE               |           8 |
|
 e4                             | DOUBLE               |           8 |
|
 buildid                        | NCHAR                |          64 | TAG
|
 gatewayid                      | NCHAR                |          64 | TAG
|
 ct                             | INT                  |           4 | TAG
|
 remark                         | NCHAR                |          64 | TAG
|
 meterid                        | NCHAR                |          64 | TAG
|

开始输入错误的时候，remark和meterid，的value未加单引号；
create table if not exists parkems.D1904472885000183 USING parkems.ele_meters TAGS ('zhixiangdasha','zhixiangdasha001', 1,1904472885000183,1904472885000183) 
 if not exists parkems.D1904472885000188 USING parkems.ele_meters TAGS ('zhixiangdasha','zhixiangdasha001', 1,1904472885000188,1904472885000188)  
 if not exists parkems.D1904472885000185 USING parkems.ele_meters TAGS ('zhixiangdasha','zhixiangdasha001', 1,1904472885000185,1904472885000185)...

3. 批量发送指令后，rest API拒绝连接
4. 通过docker里面的命令行，taos进入，可以操作
5. 重启docker td实例后之后，rest API才可以恢复

**Expected Behavior**
希望输入错误SQL后，REST API不需要重启数据库才可以恢复

**Screenshots**

**Environment (please complete the following information):**
 - OS: [DOCKER] 
 - Memory, CPU, current Disk Space
 - TDengine Version [3.0.1.7]

**Additional Context**

**Comment by yu285** [comment]
麻烦直接提供下：
1. 超级表建表语句（show create table xxxx \G ）
2.可以直接导致服务失败的语句 curl -u root:taosdata -d  "select count(*) from log.log" 127.0.0.1:6041/rest/sql ,
其中“select count(*) from log.log” 替换为本issue中提及的“错误SQL”

**Comment by yu285** [comment]
可以微信沟通下: a15652223354

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
