### ISSUE TITLE
第一次connect 成功后， 第二次connect ，及时密码错误，也能连接成功。

### ISSUE THREAD

**Issue by azhuoinfogs** [taosdata/TDengine#1829]
master 分支：最新代码
commit c23053c749a35e0bb2204ec2fc070819596eab26 

测试代码： 修改c demo.c  
 taos = taos_connect(argv[1], "root", "taosdata", NULL, 0);
  if (taos == NULL) {
    printf("failed to connect to server, reason:%s\n", taos_errstr(taos));
    exit(1);
  }
  printf("success to connect to server\n");
  taos = taos_connect(argv[1], "root", "taosdatad", NULL, 0);
  if (taos == NULL) {
    printf("failed to connect to server, reason:%s\n", taos_errstr(taos));
    exit(1);
  }
  printf("success to connect to server 1\n");
结果：前后两次都能提示连接成功。

**Comment by plum-lihui** [comment]
我在最新的版本上验证了一下，第二次是失败的。请再测试看看，有问题请提交给我们。
多谢！
