### ISSUE TITLE
ODBC Driver can not build

### ISSUE THREAD

**Issue by DianaZhao** [taosdata/TDengine#18299]
I am trying to create a connector of Power BI for TDengine, it will depend on the TDengine ODBC driver. I noticed that there is an ODBC directory under /src/connector in the 'develop' branch. I tried to build it according to the Readme.md, no error occurs, but nothing appears, I can not find the 'todbc.dll' which should be built out. The following picture shows the process:
![1](https://user-images.githubusercontent.com/961024/202973238-214ed1a5-8ea0-4b13-a378-54a8f7d7328d.PNG)

I wish to know that, does that ODBC driver work now, or when it will work and be available to developers.

**Comment by freemine** [comment]
https://github.com/taosdata/TDengine/issues/17774
i am personally developing odbc driver for TDengine 3.0, which is totally re-designed.
but, currently no windows port yet.

**Comment by DianaZhao** [comment]
> 

I'd like to try that driver, when will the windows version available according to your plan?
