### ISSUE TITLE
3.0.1.7 drop dnode error

### ISSUE THREAD

**Issue by lvdoubaobao** [taosdata/TDengine#18304]
**Bug Description**
集群删除dnode时 数据未自动同步，执行完
DB error: Dnode does not exist
查询表:select count(*) from meters;
时DB error: Query not ready

**To Reproduce**
1.准备两台虚拟机部署集群
2.运行taosBenchmark填充数据
3.在主节点上执行"drop dnode 2;"显示"DB error: Dnode does not exist (310.542558s)"
4.执行"select count(*) from meters;"
5:显示“DB error: Query not ready (0.127872s)”
**Expected Behavior**

**Screenshots**
<img width="901" alt="image" src="https://user-images.githubusercontent.com/22880817/202985048-03db4d1e-27d6-405d-a258-7226982436ca.png">
<img width="432" alt="image" src="https://user-images.githubusercontent.com/22880817/202985098-b27a70af-4ba0-4d5e-8ccc-4a179f8ba04e.png">

**Environment (please complete the following information):**
-阿里云 2核8g
-腾讯云 2核8g

**Comment by yu285** [comment]
可以远程调试吗

**Comment by lvdoubaobao** [comment]
我卸载了 然后装上2.6版本没有遇到上述情况 ，3.0版本 集群删除节点这块儿感觉有很多问题 一删除就出问题

**Comment by yu285** [comment]
3.0 如果还有问题的话，我可以远程看下。微信：a15652223354

**Comment by 13917781779** [comment]
发的什么东西，你电话多少？













苏佳音


***@***.***







电子名片新出VIP模板啦，快来体验>>




扫一扫,


快速添加名片到手机




--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: Yu Chen  ***@***.***>
 

 
 发送时间: 2022-11-28 20:24:26
 

 
 收件人:taosdata/TDengine ***@***.***> 

 
 抄送:Subscribed ***@***.***> 

 
 主题: Re: [taosdata/TDengine] 3.0.1.7 drop dnode error (Issue #18304)
 





 Closed #18304 as completed.

**Comment by 13917781779** [comment]
发的什么东西，你电话多少？













苏佳音


***@***.***







电子名片新出VIP模板啦，快来体验>>




扫一扫,


快速添加名片到手机




--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: Yu Chen  ***@***.***>
 

 
 发送时间: 2022-11-28 20:24:26
 

 
 收件人:taosdata/TDengine ***@***.***> 

 
 抄送:Subscribed ***@***.***> 

 
 主题: Re: [taosdata/TDengine] 3.0.1.7 drop dnode error (Issue #18304)
 





 3.0 如果还有问题的话，我可以远程看下。微信：a15652223354
