### ISSUE TITLE
JDBC query result not consistent with taosd

### ISSUE THREAD

**Issue by heliuyi1994** [taosdata/TDengine#18314]
3.0.17版本，
ubuntu 20.04
查询语句
 
SELECT _wstart,max(energy) as energy,position FROM vib_61a173d7_1 WHERE 
ts BETWEEN "2022-11-21 16:10:27" AND "2022-11-21 17:09:27" INTERVAL(1m) FILL(V
ALUE,0,"NULL") limit 20000;

jdbc查询无结果
taos-cli可查询有效数据

我通过安装3.0.14版本解决了问题

**Comment by huolibo** [comment]
jdbc url 配置是什么？
根据配置不同 jdbc 下层可能使用 jni REST 或是 websocket 进行数据通信。

**Comment by heliuyi1994** [comment]
> jdbc url 配置是什么？ 根据配置不同 jdbc 下层可能使用 jni REST 或是 websocket 进行数据通信。
config=new HikariConfig();
config.setJdbcUrl("jdbc:TAOS://localhost:6030/wind_power");
config.setUsername("root");
config.setPassword("taosdata");

我在相同配置下更换tdengine版本就能解决bug 跟配置应该没有关系

**Comment by huolibo** [comment]
好的，我先做下本地问题复现。

**Comment by huolibo** [comment]
以下是一个 test demo 在本地 3.0.1.7 是可以正常运行的
```java
import org.junit.BeforeClass;
import org.junit.Test;

import java.sql.*;
import java.util.Properties;

public class QueryTest {

    public static final String HOST = "127.0.0.1";
    public static final String DB = "query_test";
    public static Connection connection;

    @Test
    public void QueryTest() throws SQLException {
        try (Statement statement = connection.createStatement()) {
            ResultSet resultSet = statement.executeQuery("SELECT _wstart, max(energy) as energy, position FROM t_table WHERE ts BETWEEN '2022-11-21 16:10:27' AND '2022-11-21 16:15:27' INTERVAL(1m) FILL(VALUE,0,'NULL') limit 20000");
            ResultSetMetaData metaData = resultSet.getMetaData();
            while (resultSet.next()) {
                System.out.println(metaData.getColumnName(1) + "---" + resultSet.getString(1));
                System.out.println(metaData.getColumnName(2) + "---" + resultSet.getString(2));
                System.out.println(metaData.getColumnName(3) + "---" + resultSet.getString(3));
            }
        }
    }

    @BeforeClass
    public static void beforeClass() throws SQLException {
        String url = "jdbc:TAOS://" + HOST + ":6030/?user=root&password=taosdata&timezone=UTC";
        Properties properties = new Properties();
        properties.setProperty(TSDBDriver.PROPERTY_KEY_LOCALE, "C");
        properties.setProperty(TSDBDriver.PROPERTY_KEY_CHARSET, "UTF-8");
        connection = DriverManager.getConnection(url, properties);
        try (Statement statement = connection.createStatement()){
            statement.executeUpdate("drop database if exists " + DB);
            statement.executeUpdate("create database " + DB);
            statement.executeUpdate("use " + DB);
            statement.executeUpdate("create table t_table (ts timestamp, energy int, position binary(10))");
            //2022-11-21 16:12:27
            statement.executeUpdate("insert into t_table values ('2022-11-21 16:12:27', 1, 'bj')");
        }
    }
}
```
result 中包含插入的数据:
```
_wstart---2022-11-21 16:10:00.0
energy---0
position---null
_wstart---2022-11-21 16:11:00.0
energy---0
position---null
_wstart---2022-11-21 16:12:00.0
energy---1
position---bj
_wstart---2022-11-21 16:13:00.0
energy---0
position---null
_wstart---2022-11-21 16:14:00.0
energy---0
position---null
_wstart---2022-11-21 16:15:00.0
energy---0
position---null
```

**Comment by heliuyi1994** [comment]
> 以下是一个 test demo 在本地 3.0.1.7 是可以正常运行的
> 
> ```java
> import org.junit.BeforeClass;
> import org.junit.Test;
> 
> import java.sql.*;
> import java.util.Properties;
> 
> public class QueryTest {
> 
>     public static final String HOST = "127.0.0.1";
>     public static final String DB = "query_test";
>     public static Connection connection;
> 
>     @Test
>     public void QueryTest() throws SQLException {
>         try (Statement statement = connection.createStatement()) {
>             ResultSet resultSet = statement.executeQuery("SELECT _wstart, max(energy) as energy, position FROM t_table WHERE ts BETWEEN '2022-11-21 16:10:27' AND '2022-11-21 16:15:27' INTERVAL(1m) FILL(VALUE,0,'NULL') limit 20000");
>             ResultSetMetaData metaData = resultSet.getMetaData();
>             while (resultSet.next()) {
>                 System.out.println(metaData.getColumnName(1) + "---" + resultSet.getString(1));
>                 System.out.println(metaData.getColumnName(2) + "---" + resultSet.getString(2));
>                 System.out.println(metaData.getColumnName(3) + "---" + resultSet.getString(3));
>             }
>         }
>     }
> 
>     @BeforeClass
>     public static void beforeClass() throws SQLException {
>         String url = "jdbc:TAOS://" + HOST + ":6030/?user=root&password=taosdata&timezone=UTC";
>         Properties properties = new Properties();
>         properties.setProperty(TSDBDriver.PROPERTY_KEY_LOCALE, "C");
>         properties.setProperty(TSDBDriver.PROPERTY_KEY_CHARSET, "UTF-8");
>         connection = DriverManager.getConnection(url, properties);
>         try (Statement statement = connection.createStatement()){
>             statement.executeUpdate("drop database if exists " + DB);
>             statement.executeUpdate("create database " + DB);
>             statement.executeUpdate("use " + DB);
>             statement.executeUpdate("create table t_table (ts timestamp, energy int, position binary(10))");
>             //2022-11-21 16:12:27
>             statement.executeUpdate("insert into t_table values ('2022-11-21 16:12:27', 1, 'bj')");
>         }
>     }
> }
> ```
> 
> result 中包含插入的数据:
> 
> ```
> _wstart---2022-11-21 16:10:00.0
> energy---0
> position---null
> _wstart---2022-11-21 16:11:00.0
> energy---0
> position---null
> _wstart---2022-11-21 16:12:00.0
> energy---1
> position---bj
> _wstart---2022-11-21 16:13:00.0
> energy---0
> position---null
> _wstart---2022-11-21 16:14:00.0
> energy---0
> position---null
> _wstart---2022-11-21 16:15:00.0
> energy---0
> position---null
> ```

执行你的程序后，我插入到t_table数据的时间戳为'2022-11-22 00:12:27.000'  而不是'2022-11-21 16:12:27'

查询结果为
```
_wstart---2022-11-22 00:10:00.0
energy---0
position---null
_wstart---2022-11-22 00:11:00.0
energy---0
position---null
_wstart---2022-11-22 00:12:00.0
energy---1
position---bj
_wstart---2022-11-22 00:13:00.0
energy---0
position---null
_wstart---2022-11-22 00:14:00.0
energy---0
position---null
_wstart---2022-11-22 00:15:00.0
energy---0
position---null
```

**Comment by huolibo** [comment]
这是由于时区导致的，但结果证明是可以获取到数据。

**Comment by heliuyi1994** [comment]
> 这是由于时区导致的，但结果证明是可以获取到数据。

1. 这个问题始终没有得到解决,我要如何设置时区来排除这个bug？
2. [由于老版本存在其他bug我不得已重新更新了新版本。仍然存在这个问题,在我们的开发环境下，就是无法从jdbc获取正确的数据，请在测试代码中插入更多的数据来复现。
