### ISSUE TITLE
TDengine-server-3.0.1.7-Windows-x64.exe   error

### ISSUE THREAD

**Issue by njzhangfei** [taosdata/TDengine#18310]
Program:C:\TDengine\taosd.exe

crt detected that application wrote to memory after end of heap buffer

**Comment by sangshuduo** [comment]
请问 Windows 什么版本？是第一个启动就出错吗？有没有安装过之前版本？有没有旧数据？

**Comment by njzhangfei** [comment]
我是卸载3.0.1.4版本后，再重新安装3.0.1.7版本的，有时运行几个小时就报错，有时运行两天才报错，弹出错误窗口后，把此窗口关闭，然后重启服务，就可以继续使用，过段时间又会报错，这已经出现好几次了

> 请问 Windows 什么版本？是第一个启动就出错吗？有没有安装过之前版本？有没有旧数据？

我是卸载3.0.1.4版本后，再重新安装3.0.1.7版本的，有时运行几个小时就报错，有时运行两天才报错，弹出错误窗口后，把此窗口关闭，然后重启服务，就可以继续使用，过段时间又会报错，这已经出现好几次了

**Comment by njzhangfei** [comment]
我是卸载3.0.1.4版本后，再重新安装3.0.1.7版本的，有时运行几个小时就报错，有时运行两天才报错，弹出错误窗口后，把此窗口关闭，然后重启服务，就可以继续使用，过段时间又会报错，这已经出现好几次了

**Comment by njzhangfei** [comment]
> 请问 Windows 什么版本？是第一个启动就出错吗？有没有安装过之前版本？有没有旧数据？

我是卸载3.0.1.4版本后，再重新安装3.0.1.7版本的，有时运行几个小时就报错，有时运行两天才报错，弹出错误窗口后，把此窗口关闭，然后重启服务，就可以继续使用，过段时间又会报错，这已经出现好几次了

**Comment by sangshuduo** [comment]
弹出错误窗口请截屏贴过来，上面应该有更详细的信息帮我们判断是哪里错了，谢谢

**Comment by njzhangfei** [comment]
> 



> 弹出错误窗口请截屏贴过来，上面应该有更详细的信息帮我们判断是哪里错了，谢谢

那我这边先将图片放到文件服务器上，然后贴出来，这边的问题提交不能直接上传图片，只能自己搞个在线图片，在将链接地址发出来了！

**Comment by njzhangfei** [comment]
> 弹出错误窗口请截屏贴过来，上面应该有更详细的信息帮我们判断是哪里错了，谢谢

[http://47.98.180.56:9000/pic](url)

**Comment by njzhangfei** [comment]
我要将版本改回3.0.1.4，先用着看看
