### ISSUE TITLE
after creating stream , meters disappeared

### ISSUE THREAD

**Issue by lvdoubaobao** [taosdata/TDengine#18313]
**Bug Description**
版本3.0.1.7 安装后，taosBenchmark测试后然后运行“CREATE STREAM avg_vol_s INTO avg_vol AS
SELECT _wstart, count(*), avg(voltage) FROM meters PARTITION BY tbname INTERVAL(1m) SLIDING(30s);”
超级表 meters 消失

**Comment by yu285** [comment]
收到，我们看下

**Comment by yu285** [comment]
您这边能稳定复现么，我这边看了没出现这个问题

**Comment by yu285** [comment]
> 我这边再测试下

如果复现，可以远程看下。

**Comment by yu285** [comment]
还有问题么
