### ISSUE TITLE
PYTHON3: login disconnected, login again

### ISSUE THREAD

**Issue by weilisikaili** [taosdata/TDengine#1832]
我将taos链接封装在我的接口中,  每次都会产生新的链接并查询;  在此之前查询没有任何问题,  现在我不管怎样,不管本地还是远程链接, 一直都是login disconnected, login again; 版本号1.6.4.4;  是否能给点建议,服务重启依旧不行,   不能解决我只能暂时将数据导出.

**Comment by weilisikaili** [comment]
刚刚我测试了一下,发现taos使用python链接,使用以下代码
import taos
cl = taos.connect(host="192.168.0.47", user="zh", password='a123456', config="/etc/taos")
conn_t = cl.cursor()
conn_t.execute("use jiau")
print(1)

当脚本在taos安装的本地服务器上运行时, connect success
当在taos安装所在服务器之外时, 会出现login disconnected, login again

在这些情况下有一个背景: 我在本地跑了一个脚本,我将taos链接对象创建和链接关闭放在了while True 里面, 执行每3秒插入一组数据的操作. 且使用的是一个独立的账户, 无论停掉脚本与否, 都会出现上述情况

**Comment by liuyq-617** [comment]
应该是你的网络环境问题，您先确认一下客户端连接正常吗

**Comment by weilisikaili** [comment]
你好,都是私有云内的云主机,我确认都能互相通讯(有没有可能TCP,UDP的端口的默认配置是否不行?),  且在我上述情况的基础下, 本地使用代码链接之后是可以正常操作的

**Comment by weilisikaili** [comment]
> 你好，都是私有云内的云主机，我确认是否互相通讯（有没有可能的TCP，UDP的端口的配置配置是否不行？），且在我上述情况的基础下，本地使用代码链接之后是可以正常操作的

 你好，都是私有云内的云主机，我确认能够互相通讯（有没有可能的TCP，UDP的端口的配置配置是否不行？），且在我上述情况的基础下，本地使用代码链接之后是可以正常操作的

**Comment by weilisikaili** [comment]
taos是否有类似于redis禁止外部访问的配置呢

**Comment by weilisikaili** [comment]
> taos是否有类似于redis禁止外部访问的配置呢

@liuyq-617

**Comment by liuyq-617** [comment]
我们私有云没有限制，很多都是在华为和阿里云上的。您参考这个服务端配置，看一下，得修改一下配置
https://www.taosdata.com/cn/documentation/administrator/#%E6%9C%8D%E5%8A%A1%E7%AB%AF%E9%85%8D%E7%BD%AE
