### ISSUE TITLE
3.0.14 Authentication failure

### ISSUE THREAD

**Issue by thomasgogo** [taosdata/TDengine#18337]
td 3.0.14
节点突然offline
日志信息提示:
11/22 14:47:46.681515 00013019 UDF start udfd event loop
11/22 14:47:46.882466 00013024 UDF ERROR udfd rpc error. code: Authentication failure
11/22 14:47:46.882486 00013026 UDF ERROR udfd can not connect to mnode, code: Authentication failure. retry
11/22 14:47:47.282831 00013024 UDF ERROR udfd rpc error. code: Authentication failure
11/22 14:47:47.282852 00013026 UDF ERROR udfd can not connect to mnode, code: Authentication failure. retry

请问下,如何解决

**Comment by yu285** [comment]
这应该不影响使用，至于为何离线，可以远程调试下，微信15652223354 。

**Comment by thomasgogo** [comment]
ERROR: getTableTagValueNativeV3() LN2720, failed to run command <SELEC FROM .WHERE = '' AND table_name = '>, taos: 0x558028881600, code: 0x800026ff, reason: Parser internal error
备份的时候报错,请帮忙看看

**Comment by thomasgogo** [comment]
msg:0x7f4474036a80, failed to check mnode state since Sync not leader, type:status, numOfMnodes:3 inUse:1
