### ISSUE TITLE
security issue :the  ~/.taos_history file permission is 666,which is readable by everyuser

### ISSUE THREAD

**Issue by kerneltravel** [taosdata/TDengine#18338]
**Bug Description**

**To Reproduce**
```
stat  ~/.taos_history
```

**Expected Behavior**
shoud not read by other people. or not record some sql in this file, e.g.: sql: alter user pass 'xxxx'; shoud not be recorded in .taos_hisrory file .

**Comment by yu285** [comment]
thanks for your advice, we are fixing it

**Comment by DuanKuanJun** [comment]
We adopted your second suggestion, and the product has been repaired.
The first suggestion was not adopted because we thought it was not necessary after evaluation.
Thank you for your advice.
