### ISSUE TITLE
How can I upgrade taosd online from 2.2.2.10 to 3.0.1.7

### ISSUE THREAD

**Issue by yinshan612** [taosdata/TDengine#18333]
The current version is 2.2.2.10. It is not feasible to upgrade directly. Data should be retained. How can I upgrade to 3. x

**Comment by yu285** [comment]
you can use taosdump ,if data size not too large .

**Comment by yinshan612** [comment]
> 你可以使用taosdump，如果数据大小不是太大。

The number is quite large. There are almost 2 billion pieces of data. I have tested the Taosdump. The exported files of the Taosdump corresponding to version 2.2.2.10 cannot be imported with the Taosdump corresponding to version 3. X

**Comment by pkarqi** [comment]
> The current version is 2.2.2.10. It is not feasible to upgrade directly. Data should be retained. How can I upgrade to 3. x

迁移完毕了吗？
