### ISSUE TITLE
tdbBtreeInsert: Assertion `0' failed.

### ISSUE THREAD

**Issue by chanvi** [taosdata/TDengine#18330]
11/22 11:10:39.560345 00011003 UTL fail to load apoll url
11/22 11:10:39.560378 00011003 UTL load from cfg file /etc/taos//taos.cfg success
11/22 11:10:39.560388 00011003 UTL failed to load env file: .env
11/22 11:10:39.560397 00011003 UTL load from env variables cfg success
11/22 11:10:39.560697 00011003 UTL fail to load apoll url
11/22 11:10:39.560731 00011003 UTL load from cfg file /etc/taos//taos.cfg success
11/22 11:10:39.560739 00011003 UTL failed to load env file: .env
11/22 11:10:39.560749 00011003 UTL load from env variables cfg success
11/22 11:10:39.560808 00011003 UTL                      global config
11/22 11:10:39.560815 00011003 UTL =================================================================
11/22 11:10:39.560818 00011003 UTL default      firstEp                  dx2.xrv.name:6030
11/22 11:10:39.560826 00011003 UTL default      secondEp                 dx2.xrv.name:6030
11/22 11:10:39.560834 00011003 UTL default      fqdn                     dx2.xrv.name
11/22 11:10:39.560837 00011003 UTL default      serverPort               6030
11/22 11:10:39.560844 00011003 UTL default      tempDir                  /tmp/
11/22 11:10:39.560847 00011003 UTL default      minimalTmpDirGB          1.00
11/22 11:10:39.560856 00011003 UTL default      shellActivityTimer       3
11/22 11:10:39.560858 00011003 UTL default      compressMsgSize          -1
11/22 11:10:39.560866 00011003 UTL default      compressColData          -1
11/22 11:10:39.560868 00011003 UTL default      queryPolicy              1
11/22 11:10:39.560876 00011003 UTL default      querySmaOptimize         0
11/22 11:10:39.560878 00011003 UTL default      queryPlannerTrace        0
11/22 11:10:39.560886 00011003 UTL default      queryNodeChunkSize       32768
11/22 11:10:39.560889 00011003 UTL default      queryUseNodeAllocator    1
11/22 11:10:39.560896 00011003 UTL default      keepColumnName           0
11/22 11:10:39.560899 00011003 UTL default      smlChildTableName
11/22 11:10:39.560906 00011003 UTL default      smlTagName               _tag_null
11/22 11:10:39.560909 00011003 UTL default      smlDataFormat            0
11/22 11:10:39.560913 00011003 UTL default      maxMemUsedByInsert       1024
11/22 11:10:39.560920 00011003 UTL default      numOfTaskQueueThreads    4
11/22 11:10:39.560922 00011003 UTL default      dataDir                  /var/lib/taos/
11/22 11:10:39.560929 00011003 UTL default      minimalDataDirGB         2.00
11/22 11:10:39.560932 00011003 UTL default      supportVnodes            8
11/22 11:10:39.560939 00011003 UTL default      maxShellConns            50000
11/22 11:10:39.560942 00011003 UTL default      statusInterval           1
11/22 11:10:39.560950 00011003 UTL default      minSlidingTime           10
11/22 11:10:39.560952 00011003 UTL default      minIntervalTime          1
11/22 11:10:39.560958 00011003 UTL default      maxNumOfDistinctRes      10000000
11/22 11:10:39.560964 00011003 UTL default      countAlwaysReturnValue   1
11/22 11:10:39.560967 00011003 UTL default      queryBufferSize          -1
11/22 11:10:39.560972 00011003 UTL default      printAuth                0
11/22 11:10:39.560978 00011003 UTL default      queryRspPolicy           0
11/22 11:10:39.560985 00011003 UTL default      multiProcess             0
11/22 11:10:39.560991 00011003 UTL default      mnodeShmSize             20972544
11/22 11:10:39.560997 00011003 UTL default      vnodeShmSize             104858624
11/22 11:10:39.561002 00011003 UTL default      qnodeShmSize             41944064
11/22 11:10:39.561009 00011003 UTL default      snodeShmSize             41944064
11/22 11:10:39.561015 00011003 UTL default      numOfShmThreads          1
11/22 11:10:39.561021 00011003 UTL default      numOfRpcThreads          2
11/22 11:10:39.561027 00011003 UTL default      numOfCommitThreads       2
11/22 11:10:39.561033 00011003 UTL default      numOfMnodeReadThreads    1
11/22 11:10:39.561039 00011003 UTL default      numOfVnodeQueryThreads   8
11/22 11:10:39.561046 00011003 UTL default      numOfVnodeStreamThreads  4
11/22 11:10:39.561056 00011003 UTL default      numOfVnodeWriteThreads   4
11/22 11:10:39.561059 00011003 UTL default      numOfVnodeSyncThreads    16
11/22 11:10:39.561067 00011003 UTL default      numOfVnodeRsmaThreads    4
11/22 11:10:39.561072 00011003 UTL default      numOfQnodeQueryThreads   8
11/22 11:10:39.561080 00011003 UTL default      numOfSnodeSharedThreads  2
11/22 11:10:39.561083 00011003 UTL default      numOfSnodeUniqueThreads  2
11/22 11:10:39.561087 00011003 UTL default      rpcQueueMemoryAllowed    808370995
11/22 11:10:39.561095 00011003 UTL default      monitor                  1
11/22 11:10:39.561098 00011003 UTL default      monitorInterval          30
11/22 11:10:39.561105 00011003 UTL default      monitorFqdn
11/22 11:10:39.561108 00011003 UTL default      monitorPort              6043
11/22 11:10:39.561115 00011003 UTL default      monitorMaxLogs           100
11/22 11:10:39.561118 00011003 UTL default      monitorComp              0
11/22 11:10:39.561123 00011003 UTL default      telemetryReporting       1
11/22 11:10:39.561130 00011003 UTL default      telemetryInterval        43200
11/22 11:10:39.561133 00011003 UTL default      telemetryServer          telemetry.taosdata.com
11/22 11:10:39.561143 00011003 UTL default      telemetryPort            80
11/22 11:10:39.561150 00011003 UTL default      transPullupInterval      2
11/22 11:10:39.561158 00011003 UTL default      mqRebalanceInterval      2
11/22 11:10:39.561167 00011003 UTL default      ttlUnit                  86400
11/22 11:10:39.561170 00011003 UTL default      ttlPushInterval          86400
11/22 11:10:39.561177 00011003 UTL default      uptimeInterval           300
11/22 11:10:39.561179 00011003 UTL default      queryRsmaTolerance       1000
11/22 11:10:39.561184 00011003 UTL default      udf                      1
11/22 11:10:39.561191 00011003 UTL default      udfdResFuncs
11/22 11:10:39.561194 00011003 UTL default      configDir                /etc/taos/
11/22 11:10:39.561201 00011003 UTL default      scriptDir                /etc/taos/
11/22 11:10:39.561203 00011003 UTL default      logDir                   /var/log/taos/
11/22 11:10:39.561206 00011003 UTL default      minimalLogDirGB          1.00
11/22 11:10:39.561213 00011003 UTL default      numOfLogLines            10000000
11/22 11:10:39.561216 00011003 UTL default      asyncLog                 1
11/22 11:10:39.561218 00011003 UTL default      logKeepDays              0
11/22 11:10:39.561226 00011003 UTL default      debugFlag                0
11/22 11:10:39.561229 00011003 UTL default      simDebugFlag             143
11/22 11:10:39.561231 00011003 UTL default      tmrDebugFlag             131
11/22 11:10:39.561238 00011003 UTL default      uDebugFlag               131
11/22 11:10:39.561240 00011003 UTL default      rpcDebugFlag             131
11/22 11:10:39.561248 00011003 UTL default      jniDebugFlag             131
11/22 11:10:39.561256 00011003 UTL default      qDebugFlag               131
11/22 11:10:39.561259 00011003 UTL default      cDebugFlag               131
11/22 11:10:39.561261 00011003 UTL default      dDebugFlag               135
11/22 11:10:39.561264 00011003 UTL default      vDebugFlag               135
11/22 11:10:39.561266 00011003 UTL default      mDebugFlag               135
11/22 11:10:39.561271 00011003 UTL default      wDebugFlag               135
11/22 11:10:39.561278 00011003 UTL default      sDebugFlag               135
11/22 11:10:39.561281 00011003 UTL default      tsdbDebugFlag            131
11/22 11:10:39.561289 00011003 UTL default      tqDebugFlag              135
11/22 11:10:39.561297 00011003 UTL default      fsDebugFlag              135
11/22 11:10:39.561300 00011003 UTL default      udfDebugFlag             135
11/22 11:10:39.561306 00011003 UTL default      smaDebugFlag             131
11/22 11:10:39.561313 00011003 UTL default      idxDebugFlag             135
11/22 11:10:39.561316 00011003 UTL default      tdbDebugFlag             131
11/22 11:10:39.561320 00011003 UTL default      metaDebugFlag            135
11/22 11:10:39.561327 00011003 UTL cfg_file     timezone                 Asia/Shanghai (CST, +0800)
11/22 11:10:39.561330 00011003 UTL default      locale                   en_US.UTF-8
11/22 11:10:39.561337 00011003 UTL default      charset                  UTF-8
11/22 11:10:39.561340 00011003 UTL default      enableCoreFile           1
11/22 11:10:39.561348 00011003 UTL default      numOfCores               4.00
11/22 11:10:39.561351 00011003 UTL default      openMax                  65535
11/22 11:10:39.561358 00011003 UTL default      streamMax                16
11/22 11:10:39.561360 00011003 UTL default      pageSizeKB               4
11/22 11:10:39.561368 00011003 UTL default      totalMemoryKB            7894248
11/22 11:10:39.561375 00011003 UTL default      os sysname               Linux
11/22 11:10:39.561378 00011003 UTL default      os nodename              dx2.xrv.name
11/22 11:10:39.561389 00011003 UTL default      os release               4.19.0-17-amd64
11/22 11:10:39.561395 00011003 UTL default      os version               #1 SMP Debian 4.19.194-3 (2021-07-18)
11/22 11:10:39.561401 00011003 UTL default      os machine               x86_64
11/22 11:10:39.561407 00011003 UTL default      version                  3.0.1.5
11/22 11:10:39.561415 00011003 UTL default      compatible_version       3.0.0.0
11/22 11:10:39.561421 00011003 UTL default      gitinfo                  d58f7a62f72e95161068c2fa9c9cd22cbb018129
11/22 11:10:39.561426 00011003 UTL default      buildinfo                Built at 2022-10-19 17:06
11/22 11:10:39.561434 00011003 UTL =================================================================
11/22 11:10:39.562893 00011003 DND start to init dnode env
11/22 11:10:39.562937 00011003 DND dnode will run in single-process mode
11/22 11:10:39.563756 00011003 DND dnode env is initialized
11/22 11:10:39.563766 00011003 DND start to init service
11/22 11:10:39.563776 00011003 DND node:dnode, start to open
11/22 11:10:39.563783 00011003 UTL worker:dnode-mgmt is initialized, min:1 max:1
11/22 11:10:39.563918 00011013 UDF start to init udfd
11/22 11:10:39.564766 00011013 UDF udfd is initialized
11/22 11:10:39.564814 00011003 DND node:dnode, has been opened
11/22 11:10:39.564830 00011003 DND node:mnode, start to open
11/22 11:10:39.564890 00011003 WAL wal module is initialized, rsetId:3
11/22 11:10:39.565146 00011003 DND mnode start to open
11/22 11:10:39.565162 00011003 MND start to open mnode in /var/lib/taos//mnode
11/22 11:10:39.565411 00011003 WAL WARN vgId:1, appliedVer:0 is less than snapshotVer:11873. align with it.
11/22 11:10:39.567075 00011003 MND mnode-wal is initialized
11/22 11:10:39.567098 00011003 MND start to init sdb in /var/lib/taos//mnode
11/22 11:10:39.567122 00011003 MND sdb init success
11/22 11:10:39.567130 00011003 MND mnode-sdb is initialized
11/22 11:10:39.567171 00011003 MND sdb table:trans is initialized
11/22 11:10:39.567177 00011003 MND mnode-trans is initialized
11/22 11:10:39.567186 00011003 MND sdb table:cluster is initialized
11/22 11:10:39.567192 00011003 MND mnode-cluster is initialized
11/22 11:10:39.567199 00011003 MND sdb table:mnode is initialized
11/22 11:10:39.567205 00011003 MND mnode-mnode is initialized
11/22 11:10:39.567210 00011003 MND sdb table:qnode is initialized
11/22 11:10:39.567217 00011003 MND mnode-qnode is initialized
11/22 11:10:39.567226 00011003 MND sdb table:snode is initialized
11/22 11:10:39.567234 00011003 MND mnode-snode is initialized
11/22 11:10:39.567245 00011003 MND sdb table:dnode is initialized
11/22 11:10:39.567252 00011003 MND mnode-dnode is initialized
11/22 11:10:39.567259 00011003 MND sdb table:user is initialized
11/22 11:10:39.567267 00011003 MND mnode-user is initialized
11/22 11:10:39.567271 00011003 MND mnode-grant is initialized
11/22 11:10:39.567278 00011003 MND mnode-privilege is initialized
11/22 11:10:39.567310 00011003 MND sdb table:acct is initialized
11/22 11:10:39.567317 00011003 MND mnode-acct is initialized
11/22 11:10:39.567326 00011003 MND sdb table:stream is initialized
11/22 11:10:39.567332 00011003 MND mnode-stream is initialized
11/22 11:10:39.567339 00011003 MND sdb table:topic is initialized
11/22 11:10:39.567344 00011003 MND mnode-topic is initialized
11/22 11:10:39.567349 00011003 MND sdb table:consumer is initialized
11/22 11:10:39.567354 00011003 MND mnode-consumer is initialized
11/22 11:10:39.567361 00011003 MND sdb table:subscribe is initialized
11/22 11:10:39.567367 00011003 MND mnode-subscribe is initialized
11/22 11:10:39.567371 00011003 MND sdb table:offset is initialized
11/22 11:10:39.567379 00011003 MND mnode-offset is initialized
11/22 11:10:39.567387 00011003 MND sdb table:vgroup is initialized
11/22 11:10:39.567393 00011003 MND mnode-vgroup is initialized
11/22 11:10:39.567398 00011003 MND sdb table:stb is initialized
11/22 11:10:39.567404 00011003 MND mnode-stb is initialized
11/22 11:10:39.567411 00011003 MND sdb table:sma is initialized
11/22 11:10:39.567416 00011003 MND mnode-sma is initialized
11/22 11:10:39.567450 00011003 MND mnode-infos is initialized
11/22 11:10:39.567466 00011003 MND mnode-perfs is initialized
11/22 11:10:39.567481 00011003 MND sdb table:db is initialized
11/22 11:10:39.567487 00011003 MND mnode-db is initialized
11/22 11:10:39.567491 00011003 MND sdb table:func is initialized
11/22 11:10:39.567499 00011003 MND mnode-func is initialized
11/22 11:10:39.567509 00011003 MND start to reset sdb
11/22 11:10:39.567579 00011003 MND sdb:trans is reset
11/22 11:10:39.567586 00011003 MND sdb:cluster is reset
11/22 11:10:39.567591 00011003 MND sdb:mnode is reset
11/22 11:10:39.567600 00011003 MND sdb:qnode is reset
11/22 11:10:39.567607 00011003 MND sdb:snode is reset
11/22 11:10:39.567610 00011003 MND sdb:dnode is reset
11/22 11:10:39.567615 00011003 MND sdb:user is reset
11/22 11:10:39.567671 00011003 MND sdb:acct is reset
11/22 11:10:39.567679 00011003 MND sdb:stream is reset
11/22 11:10:39.567683 00011003 MND sdb:offset is reset
11/22 11:10:39.567699 00011003 MND sdb:subscribe is reset
11/22 11:10:39.567710 00011003 MND sdb:consumer is reset
11/22 11:10:39.567718 00011003 MND sdb:topic is reset
11/22 11:10:39.567725 00011003 MND sdb:vgroup is reset
11/22 11:10:39.567732 00011003 MND sdb:sma is reset
11/22 11:10:39.567741 00011003 MND sdb:stb is reset
11/22 11:10:39.567749 00011003 MND sdb:db is reset
11/22 11:10:39.567751 00011003 MND sdb:func is reset
11/22 11:10:39.567759 00011003 MND sdb reset success
11/22 11:10:39.567764 00011003 MND start to read sdb file:/var/lib/taos//mnode/data/sdb.data
11/22 11:10:39.567865 00011003 MND vgId:1, has ready mnode:1, status:ready
11/22 11:10:39.567886 00011003 MND vgId:1, mnode sync not reconfig since readyMnodes:1 updatingMnodes:0
11/22 11:10:39.567900 00011003 MND read sdb file:/var/lib/taos//mnode/data/sdb.data success, commit index:11873 term:124 config:-1
11/22 11:10:39.567921 00011003 MND mnode-sdb is initialized
11/22 11:10:39.568461 00011003 MND mnode-profile is initialized
11/22 11:10:39.568479 00011003 MND mnode-show is initialized
11/22 11:10:39.568643 00011003 MND mnode-query is initialized
11/22 11:10:39.568653 00011003 MND vgId:1, start to open sync, selfIndex:0 replica:0
11/22 11:10:39.568804 00011003 SYN vgId:1, sync node use snapshot
11/22 11:10:39.568820 00011003 MND mnode-sync is opened, id:2
11/22 11:10:39.568828 00011003 MND mnode-sync is initialized
11/22 11:10:39.568842 00011003 MND mnode-telem is initialized
11/22 11:10:39.568855 00011003 MND mnode open successfully
11/22 11:10:39.568860 00011003 UTL worker:mnode-query is initialized, min:4 max:4
11/22 11:10:39.568995 00011003 UTL worker:mnode-fetch is initialized, min:1 max:1
11/22 11:10:39.569025 00011003 UTL worker:mnode-read is initialized, min:1 max:1
11/22 11:10:39.569058 00011003 UTL worker:mnode-write is initialized, min:1 max:1
11/22 11:10:39.569473 00011003 UTL worker:mnode-sync is initialized, min:1 max:1
11/22 11:10:39.569501 00011003 UTL worker:mnode-monitor is initialized, min:1 max:1
11/22 11:10:39.569532 00011003 DND node:mnode, has been opened
11/22 11:10:39.569541 00011003 DND node:vnode, start to open
11/22 11:10:39.569632 00011003 UTL worker:vnode-query is initialized, min:8 max:8
11/22 11:10:39.569635 00011003 UTL worker:vnode-stream is initialized, min:4 max:4
11/22 11:10:39.569638 00011003 UTL worker:vnode-mgmt is initialized, min:1 max:1
11/22 11:10:39.569661 00011003 UTL worker:vnode-monitor is initialized, min:1 max:1
11/22 11:10:39.569800 00011003 DND open 2 vnodes with 2 threads
11/22 11:10:39.574435 00011036 WAL WARN vgId:3, appliedVer:0 is less than snapshotVer:39. align with it.
11/22 11:10:39.574446 00011035 WAL WARN vgId:2, appliedVer:0 is less than snapshotVer:4. align with it.
11/22 11:10:39.596052 00011036 SYN vgId:3, sync node use snapshot
11/22 11:10:39.596044 00011035 SYN vgId:2, sync node use snapshot
11/22 11:10:39.596597 00011003 DND successfully opened 2 vnodes
11/22 11:10:39.596626 00011003 UDF get dnodeId:1 from env, pipe path:/var/lib/taos//.udfd.sock.1
11/22 11:10:39.596710 00011003 UDF udfc initialized
11/22 11:10:39.596720 00011003 DND node:vnode, has been opened
11/22 11:10:39.599157 00011003 MND vgId:1, become leader
11/22 11:10:39.599303 00011003 MND vgId:1, sync restore finished, and will handle outstanding transactions
11/22 11:10:39.599323 00011003 MND vgId:1, sync started, id:2
11/22 11:10:39.599399 00011003 DND restore 2 vnodes with 2 threads
11/22 11:10:39.599439 00011062 DND thread:0, start to restore 1 vnodes
11/22 11:10:39.599462 00011063 DND thread:1, start to restore 1 vnodes
11/22 11:10:39.601071 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:6, term:2, msg-index:6, weak:0, code:0, state:102 leader, type:vnode-drop-ttl-stb
11/22 11:10:39.601089 00011063 VND vgId:3, commit-cb is excuted, fsm:0x7f057012a6e0, index:41, term:2, msg-index:41, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601098 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:7, term:2, msg-index:7, weak:0, code:0, state:102 leader, type:vnode-drop-ttl-stb
11/22 11:10:39.601111 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:8, term:2, msg-index:8, weak:0, code:0, state:102 leader, type:vnode-drop-ttl-stb
11/22 11:10:39.601114 00011063 VND vgId:3, commit-cb is excuted, fsm:0x7f057012a6e0, index:42, term:2, msg-index:42, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601123 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:9, term:2, msg-index:9, weak:0, code:0, state:102 leader, type:vnode-drop-ttl-stb
11/22 11:10:39.601128 00011063 VND vgId:3, commit-cb is excuted, fsm:0x7f057012a6e0, index:43, term:2, msg-index:43, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601160 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:10, term:2, msg-index:10, weak:0, code:0, state:102 leader, type:vnode-drop-ttl-stb
11/22 11:10:39.601177 00011063 VND vgId:3, commit-cb is excuted, fsm:0x7f057012a6e0, index:44, term:2, msg-index:44, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601183 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:11, term:2, msg-index:11, weak:0, code:0, state:102 leader, type:vnode-drop-ttl-stb
11/22 11:10:39.601194 00011063 VND vgId:3, commit-cb is excuted, fsm:0x7f057012a6e0, index:45, term:2, msg-index:45, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601198 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:12, term:2, msg-index:12, weak:0, code:0, state:102 leader, type:vnode-drop-ttl-stb
11/22 11:10:39.601207 00011063 VND vgId:3, commit-cb is excuted, fsm:0x7f057012a6e0, index:46, term:2, msg-index:46, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601213 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:13, term:2, msg-index:13, weak:0, code:0, state:102 leader, type:vnode-drop-ttl-stb
11/22 11:10:39.601230 00011063 VND vgId:3, commit-cb is excuted, fsm:0x7f057012a6e0, index:47, term:2, msg-index:47, weak:0, code:0, state:102 leader, type:vnode-drop-ttl-stb
11/22 11:10:39.601245 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:14, term:2, msg-index:14, weak:0, code:0, state:102 leader, type:vnode-drop-ttl-stb
11/22 11:10:39.601246 00011063 VND vgId:3, commit-cb is excuted, fsm:0x7f057012a6e0, index:48, term:2, msg-index:48, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601262 00011063 VND vgId:3, commit-cb is excuted, fsm:0x7f057012a6e0, index:49, term:2, msg-index:49, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601262 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:15, term:2, msg-index:15, weak:0, code:0, state:102 leader, type:vnode-drop-ttl-stb
11/22 11:10:39.601273 00011063 VND vgId:3, commit-cb is excuted, fsm:0x7f057012a6e0, index:50, term:2, msg-index:50, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601281 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:16, term:2, msg-index:16, weak:0, code:0, state:102 leader, type:vnode-drop-ttl-stb
11/22 11:10:39.601288 00011063 VND vgId:3, commit-cb is excuted, fsm:0x7f057012a6e0, index:51, term:2, msg-index:51, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601299 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:17, term:2, msg-index:17, weak:0, code:0, state:102 leader, type:vnode-drop-ttl-stb
11/22 11:10:39.601313 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:18, term:2, msg-index:18, weak:0, code:0, state:102 leader, type:vnode-drop-ttl-stb
11/22 11:10:39.601302 00011063 VND vgId:3, commit-cb is excuted, fsm:0x7f057012a6e0, index:52, term:2, msg-index:52, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601325 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:19, term:2, msg-index:19, weak:0, code:0, state:102 leader, type:vnode-drop-ttl-stb
11/22 11:10:39.601337 00011063 VND vgId:3, commit-cb is excuted, fsm:0x7f057012a6e0, index:53, term:2, msg-index:53, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601338 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:20, term:2, msg-index:20, weak:0, code:0, state:102 leader, type:vnode-drop-ttl-stb
11/22 11:10:39.601353 00011063 VND vgId:3, commit-cb is excuted, fsm:0x7f057012a6e0, index:54, term:2, msg-index:54, weak:0, code:0, state:102 leader, type:vnode-drop-ttl-stb
11/22 11:10:39.601356 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:21, term:2, msg-index:21, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601366 00011063 VND vgId:3, commit-cb is excuted, fsm:0x7f057012a6e0, index:55, term:2, msg-index:55, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601369 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:22, term:2, msg-index:22, weak:0, code:0, state:102 leader, type:drop-table
11/22 11:10:39.601393 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:23, term:2, msg-index:23, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601394 00011063 VND vgId:3, commit-cb is excuted, fsm:0x7f057012a6e0, index:56, term:2, msg-index:56, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601405 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:24, term:2, msg-index:24, weak:0, code:0, state:102 leader, type:vnode-drop-ttl-stb
11/22 11:10:39.601424 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:25, term:2, msg-index:25, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601441 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:26, term:2, msg-index:26, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601458 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:27, term:2, msg-index:27, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601474 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:28, term:2, msg-index:28, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601490 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:29, term:2, msg-index:29, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601507 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:30, term:2, msg-index:30, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601524 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:31, term:2, msg-index:31, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601541 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:32, term:2, msg-index:32, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601557 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:33, term:2, msg-index:33, weak:0, code:0, state:102 leader, type:submit
taosd: /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/libs/tdb/src/db/tdbBtree.c:197: tdbBtreeInsert: Assertion `0' failed.
11/22 11:10:39.601574 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:34, term:2, msg-index:34, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601590 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:35, term:2, msg-index:35, weak:0, code:0, state:102 leader, type:submit
11/22 11:10:39.601607 00011062 VND vgId:2, commit-cb is excuted, fsm:0x7f057812cee0, index:36, term:2, msg-index:36, weak:0, code:0, state:102 leader, type:submit
Aborted

**Comment by yu285** [comment]
这个应该是已经修复过的问题，可以升级到 3.0.1.7 ，如果问题存在，我会reopen这个issue
