### ISSUE TITLE
The software insertion speed of version 3017 is much slower than that of version 3016

### ISSUE THREAD

**Issue by hecao100** [taosdata/TDengine#18347]
Taosd & Taos Client
 
version :3017
Insert into db, The speed:
[IOT-BikeRec]完成批量写入100条，耗时=33222 ms

version :3016
Insert into db, The speed:
[IOT-BikeRec]完成批量写入100条，耗时=551 ms

-----------------
The Code :  mybatis批量写入的代码
`<insert id="insertBatch" parameterType="com.test.entity.BikeRec">
        insert into ${tableName}
        USING bike_rec TAGS (#{list[0].a0})
        values
        <foreach collection="list" item="item" index="idx" separator=",">
            (
                #{item.ts},
                #{item.a1},
                #{item.a2},
                #{item.a3},
                #{item.a4},
                #{item.a5},
                #{item.a6},
                #{item.a7},
                #{item.a8},
                #{item.a9},
                #{item.a10},
                #{item.a11},
                #{item.a12},
                #{item.a13},
                #{item.a14},
                #{item.a15},
                #{item.a16},
                #{item.a17},
                #{item.a18},
                #{item.a19},
                #{item.a20},
                #{item.a21},
                #{item.a22},
                #{item.a23},
                #{item.a24},
                #{item.a25},
                #{item.a26},
                #{item.a27},
                #{item.a28},
                #{item.a29},
                #{item.a30},
                #{item.a31},
                #{item.a32},
                #{item.a33},
                #{item.a34},
                #{item.a35},
                #{item.a36},
                #{item.a37},
                #{item.a38},
                #{item.a39},
                #{item.a40},
                #{item.a41},
                #{item.a42},
                #{item.a43},
                #{item.a44},
                #{item.a45},
                #{item.a46},
                #{item.a47},
                #{item.a48},
                #{item.a49},
                #{item.a50},
                #{item.a51},
                #{item.a52},
                #{item.a53},
                #{item.a54},
                #{item.a55},
                #{item.a56},
                #{item.a57},
                #{item.a58},
                #{item.a59},
                #{item.a60},
                #{item.a61},
                #{item.a62}
            )
        </foreach>
    </insert>`

**Comment by hecao100** [comment]
`<insert id="insertBatch" parameterType="com.test.entity.BikeRec">
        insert into ${tableName}
        USING bike_rec TAGS (#{list[0].a0})
        values
        <foreach collection="list" item="item" index="idx" separator=",">
            (
                #{item.ts},
                #{item.a1},
                #{item.a2},
                #{item.a3},
                #{item.a4},
                #{item.a5},
                #{item.a6},
                #{item.a7},
                #{item.a8},
                #{item.a9},
                #{item.a10},
                #{item.a11},
                #{item.a12},
                #{item.a13},
                #{item.a14},
                #{item.a15},
                #{item.a16},
                #{item.a17},
                #{item.a18},
                #{item.a19},
                #{item.a20},
                #{item.a21},
                #{item.a22},
                #{item.a23},
                #{item.a24},
                #{item.a25},
                #{item.a26},
                #{item.a27},
                #{item.a28},
                #{item.a29},
                #{item.a30},
                #{item.a31},
                #{item.a32},
                #{item.a33},
                #{item.a34},
                #{item.a35},
                #{item.a36},
                #{item.a37},
                #{item.a38},
                #{item.a39},
                #{item.a40},
                #{item.a41},
                #{item.a42},
                #{item.a43},
                #{item.a44},
                #{item.a45},
                #{item.a46},
                #{item.a47},
                #{item.a48},
                #{item.a49},
                #{item.a50},
                #{item.a51},
                #{item.a52},
                #{item.a53},
                #{item.a54},
                #{item.a55},
                #{item.a56},
                #{item.a57},
                #{item.a58},
                #{item.a59},
                #{item.a60},
                #{item.a61},
                #{item.a62}
            )
        </foreach>
    </insert>`

**Comment by yu285** [comment]
hi，可以提供下具体代码吗

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
