### ISSUE TITLE
table XXX not found in submit rsp

### ISSUE THREAD

**Issue by aispringli** [taosdata/TDengine#18340]
**Bug Description**
`
11/22 14:17:59.305888 00013691 TSC ERROR table 1.test.gps_c3c9d984369946f9b77ba8bf89525d4e not found in submit rsp
11/22 14:18:00.878709 00013691 JNI ERROR excute batch jobj:0x7fe91d3f5118, conn:0x7fe96c011d80, code:Application error
11/22 14:18:00.878712 00013688 JNI ERROR excute batch jobj:0x7fe91d6f8118, conn:0x7fe968001ce0, code:Application error
11/22 14:18:00.879530 00013684 JNI ERROR excute batch jobj:0x7fe91dafbf98, conn:0x7fe95826e790, code:Application error
11/22 14:18:00.879521 00013686 JNI ERROR excute batch jobj:0x7fe91d8f9f98, conn:0x7fe96000cec0, code:Application error
11/22 14:18:00.879521 00013687 JNI ERROR excute batch jobj:0x7fe91d7f8f98, conn:0x7fe95c22f980, code:Application error
11/22 14:18:00.879529 00013690 JNI ERROR excute batch jobj:0x7fe91d4f61b8, conn:0x7fe970005b90, code:Application error
11/22 14:18:00.879521 00013685 JNI ERROR excute batch jobj:0x7fe91d9faf98, conn:0x7fe954007070, code:Application error
11/22 14:18:00.879536 00013689 JNI ERROR excute batch jobj:0x7fe91d5f72f8, conn:0x7fe964007f90, code:Application error

11/22 14:18:00.882967 00013687 TSC 0x12 connection is opening, connId:1140277035, dnodeConn:0x2, reqId:0xf35487fc7d32002a
11/22 14:18:00.882968 00013688 TSC 0x20 SQL: insert into  ? using gps tags(?,?) (xxx) values (?), reqId:0xf35487fc7d32
`

**Environment (please complete the following information):**
 - OS: CentOS 7.0
 - 8C32G 500G SSD
 - TDengine Version: 3.0.1.7

**Additional Context**

**Comment by yu285** [comment]
请提供下出现这段报错的代码吧

**Comment by aispringli** [comment]
> 请提供下出现这段报错的代码吧

就正常写入，一会就会出现这个问题，同样的程序在3.0.1.6上没有问题

**Comment by aispringli** [comment]
> 请提供下出现这段报错的代码吧

只不过我们单表列非常多，有有一百多列

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
