### ISSUE TITLE
TD 3.0.1.7 docker  start failed

### ISSUE THREAD

**Issue by AdonLuo** [taosdata/TDengine#18361]
部署环境:  Centos7.9、 docker compose 一键部署
  之前是docker 部署的单节点版本，想升级版本并且通过docker compose 进行一键部署，参考文档
https://github.com/taosdata/TDengine/tree/main/packaging/docker

部署配置依据：[docker-compose.yml](https://github.com/taosdata/TDengine/blob/main/packaging/docker/docker-compose.yml)

结果：3.0.1.7 版本 启动失败，2.4.0.30 版本成功。是否暂未适配呢？

部分查询记录和日志：
![企业微信截图_1669114346976](https://user-images.githubusercontent.com/19642911/203296251-f16dbdb9-3e8c-4032-acd0-4bed42d073eb.png)
![企业微信截图_16691125031457](https://user-images.githubusercontent.com/19642911/203296277-e090f4b0-f7ef-4290-bbe3-8c3a0e74fafe.png)

[start-log.txt](https://github.com/taosdata/TDengine/files/10066645/start-log.txt)

[log.txt](https://github.com/taosdata/TDengine/files/10066649/log.txt)

**Comment by yu285** [comment]
we will check on this

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
