### ISSUE TITLE
MacOS Big Sur 11.6.8 intall 3.0.1.7  failed

### ISSUE THREAD

**Issue by erickwang** [taosdata/TDengine#18372]
换了另外一台mac，系统版本 MacOS Big Sur 11.6.8 安装3.0.1.7 也失败了

启动不了

错误信息如下：

launchctl list | grep taosd
-	78	com.tdengine.taosd
MacBook-Pro ~ % taos
Welcome to the TDengine Command Line Interface, Client Version:3.0.1.7
Copyright (c) 2022 by TDengine, all rights reserved.

failed to connect to server, reason: Unable to establish connection

**Comment by yu285** [comment]
有我微信吗，远程看下吧。 15652223354

**Comment by 2XSXSXS** [comment]
> 有我微信吗，远程看下吧。 15652223354

您好，问题解决了吗？我使用的是3.0.2.0版本的服务端，也出现了这个情况。
系统版本macOS 13.0.1，tdengine版本为TDengine-server-3.0.2.0-macOS-arm64

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
