### ISSUE TITLE
MAC install 3.0.1.7 failed

### ISSUE THREAD

**Issue by erickwang** [taosdata/TDengine#18370]
MAC 系统安装版本3.0.1.7不成功。 报错信息如下：

$ taos
dyld: Library not loaded: /opt/taos/TDengine/debug/build/lib/libtaos.1.dylib
  Referenced from: /usr/local/bin/taos
  Reason: no suitable image found.  Did find:
	/usr/local/lib/libtaos.1.dylib: cannot load 'libtaos.1.dylib' (load command 0x80000034 is unknown)
	/usr/local/Cellar/tdengine/3.0.1.7/driver/libtaos.3.0.1.7.dylib: cannot load 'libtaos.3.0.1.7.dylib' (load command 0x80000034 is unknown)
Abort trap: 6

系统版本： macOS Mojave 10.14.6

**Comment by yu285** [comment]
使用的是安装包吗？

**Comment by erickwang** [comment]
是的

**Comment by yu285** [comment]
这个是 m1 还是 intel 呢

**Comment by bystart** [comment]
bystart@handsome:/usr/lib|
⇒  taos
dyld[72829]: Library not loaded: '/opt/taos/TDengine/debug/build/lib/libtaos.1.dylib'
  Referenced from: '/opt/homebrew/Cellar/tdengine/3.0.1.5/bin/taos'
  Reason: tried: '/opt/taos/TDengine/debug/build/lib/libtaos.1.dylib' (no such file), '/usr/local/lib/libtaos.1.dylib' (no such file), '/usr/lib/libtaos.1.dylib' (no such file)
[1]    72829 abort      taos

**Comment by bystart** [comment]
Mac M1 安装了server端和client端 版本都为3.0.1.5 出现了这个错误

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
