### ISSUE TITLE
数据不能成功导入

### ISSUE THREAD

**Issue by bananashake99** [taosdata/TDengine#184]
我从[TimescaleDB官网](https://docs.timescale.com/v1.1/tutorials/other-sample-datasets#in-depth-devices)下载了[工业数据集](https://timescaledata.blob.core.windows.net/datasets/devices_big.tar.gz)，然后在TDengine中建立了对应数据类型的表:
```
create table readings (time TIMESTAMP, device_id NCHAR(25), battery_level INT, battery_status NCHAR(25), battery_temperature FLOAT, bassid NCHAR(25), cpuavg1min FLOAT, cpuavg5min FLOAT, cpuavg15min FLOAT, mem_free BIGINT, mem_used BIGINT, rssi SMALLINT, ssid NCHAR(25));
```
为什么执行:
```
insert into readings file ～/devices_big_readings.csv;
```
的时候不能成功地将数据导入呢？

**Comment by bananashake99** [comment]
然后当我在导入时对文件加上双引号的时候：
```
insert into readings file "～/devices_big_readings.csv";
```
好像成功导入了数据，但是我这个文件devices_big_readings.csv有300万行，导入TDengine以后只有1万行，其次就是，当我执行：
```
select * from readings;
```
的时候，读出的数据大概是这样的，明显与原始数据不太一样：

 16-11-18 18:17:30.000|-11                                                                                                 |          -18|18:17:30                                                                                            |            -5.00000|demo000000                                                                                          |            29.00000|             0.00000|             0.00000|                    0|                   91|      0|7                                                                                                   |
 16-11-18 18:18:00.000|-11                                                                                                 |          -18|18:18:00                                                                                            |            -5.00000|demo000000                                                                                          |            29.00000|             0.00000|             0.00000|                    0|                   93|      0|4.33                                                                                                |
 16-11-18 18:18:30.000|-11                                                                                                 |          -18|18:18:30                                                                                            |            -5.00000|demo000000                                                                                          |            29.00000|             0.00000|             0.00000|                    0|                   88|      0|5.43                                                                                                |
 16-11-18 18:19:00.000|-11                                                                                                 |          -18|18:19:00                                                                                            |            -5.00000|demo000000                                                                                          |            29.00000|             0.00000|             0.00000|                    0|                   88|      0|7.58                                                                                                |
 16-11-18 18:19:30.000|-11                                                                                                 |          -18|18:19:30                                                                                            |            -5.00000|demo000000                                                                                          |            29.00000|             0.00000|             0.00000|                    0|                   88|      0|6.87                                                                                                |
Query OK, 10000 row(s) in set (0.428610s)

我感到非常奇怪，我想请教一下怎样才能让我的数据正常地导入并且读出，且不丢失呢？

**Comment by plum-lihui** [comment]
您能将csv文件发送过来我们分析一下吗？我的 email :   huili@taosdata.com
多谢！

**Comment by physercoe** [comment]
感觉和我之前提到的问题似乎类似，csv文件中的“YY-MM-DD”这种格式的时间要用引号括起来才行。
建议可以支持不带引号的形式，这也是大多数数据存储的形式，否则转换数据带来不必要的麻烦。

**Comment by plum-lihui** [comment]
不好意思，我下载了好几次，都没有能下载成功。估计是csv文件中数据格式不符合TDengine的要求。从之前提交的几个问题看，有这样几个地方需要注意：
1、第一列的时间戳格式，如果是整型，比如 1546300800000，需要是毫秒为单位的，不能是秒；
     如果是UTD格式，需要使用单引号引起来，比如:   '2019-06-23 10:08:09.010'
2、列的数据类型是 binary，或 nchar时，需要使用单引号引起来，比如： ‘beijing’

或者请从您下载用于测试的csv文件中拷贝几行给我看看。 多谢！
