### ISSUE TITLE
Alpine install 3.0.1.6 client failed

### ISSUE THREAD

**Issue by phil-guo** [taosdata/TDengine#18406]
我根据dockerfile生产docker镜像，基础镜像是Alpine系统，安装完成之后 执行taos命令会出现如下错误：
![image](https://user-images.githubusercontent.com/14214355/203562518-2cbde973-13b2-4807-9846-d0c62c57ef9f.png)
请问这个是现在客户端还不支持 Alpine 吗？

**Comment by yu285** [comment]
我们确认下

**Comment by simple-phil** [comment]
好的，如果方便的话也可以告诉我依赖库，需要安装哪些。
