### ISSUE TITLE
 taos_schemaless_insert datatype and precision

### ISSUE THREAD

**Issue by maikebing** [taosdata/TDengine#18413]
1. 数值类型  数字末尾 加入 u 代表 无符号整型， i 代表有符号整型 ， 浮点数则不需要加符号，因为大部分数据都是浮点数。 
`t1,devname=dev1 f_int=231i,f_uint=3u,temp=12.2 1669250841744368`

2. 时间精度， 建议 taos_schemaless_insert 中不需要指定 时间精度， 因为可以通过时间戳来判断每一行的精度。 这在 多个表写入时尤为重要。

**Comment by maikebing** [comment]
@sangshuduo   @guanshengliang  @hjxilinx  @dapan1121 @yihaoDeng  各位大佬，

**Comment by wangmm0220** [comment]
@maikebing  TDengine的line protocol兼容了influxdb的lint protocol https://docs.influxdata.com/influxdb/v2.0/reference/syntax/line-protocol/

所以，第一个问题，如果末尾没有指定的话，用64位浮点数也就是double来存储。
第二个问题，为了兼容influxdb的协议，如果没有指定精度，默认所有数据都是纳秒。也可以指定精度。但是不会根据每个数据时间长度来判断。opentsdb telnet的协议是根据时间长度来确认精度的。
![image](https://user-images.githubusercontent.com/6055324/209940680-c1ca2e45-82ee-4ef5-ac5b-680f70832d1a.png)
