### ISSUE TITLE
TDengine  startup failed

### ISSUE THREAD

**Issue by xiaochuanliang** [taosdata/TDengine#18420]
● taosd.service - TDengine server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2022-11-24 10:31:37 CST; 1min 59s ago
  Process: 802244 ExecStart=/usr/bin/taosd (code=exited, status=255/EXCEPTION)
  Process: 802237 ExecStartPre=/usr/local/taos/bin/startPre.sh (code=exited, status=0/SUCCESS)
 Main PID: 802244 (code=exited, status=255/EXCEPTION)

Nov 24 10:31:37 node1 systemd[1]: taosd.service: Service RestartSec=100ms expired, scheduling restart.
Nov 24 10:31:37 node1 systemd[1]: taosd.service: Scheduled restart job, restart counter is at 3.
Nov 24 10:31:37 node1 systemd[1]: Stopped TDengine server service.
Nov 24 10:31:37 node1 systemd[1]: taosd.service: Start request repeated too quickly.
Nov 24 10:31:37 node1 systemd[1]: taosd.service: Failed with result 'exit-code'.
Nov 24 10:31:37 node1 systemd[1]: Failed to start TDengine server service.

**Comment by yu285** [comment]
请提供数据库版本

**Comment by yu285** [comment]
请问还有问题么？ 可以加微信 a15652223354 做具体排查

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
