### ISSUE TITLE
交叉编译后在arm上运行taos会报Bus error (core dumped)错误

### ISSUE THREAD

**Issue by licj666** [taosdata/TDengine#18436]
1.设置编译工具链：
export CC=arm-linux-gnueabihf-gcc
export CXX=arm-linux-gnueabihf-g++

2.修改cmake/cmake.define(去除-Werror选项，为了解决把警告当成错误)
    ELSE ()
        SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Werror=return-type -fPIC -gdwarf-2 -g3 -Wformat=2 -Wno-format-nonliteral -Wno-format-y2k")
        SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror -Wno-literal-suffix -Werror=return-type -fPIC -gdwarf-2 -g3 -Wformat=2 -Wno-format-nonliteral -Wno-format-truncation -Wno-format-y2k")
    ENDIF ()

3.交叉编译TDengine
mkdir TDengine/debug && cd TDengine/debug && cmake .. -DCPUTYPE=arm32

4.编译成功后将build下的bin和lib拷贝到arm开发板上，添加lib的动态库环境变量
运行taosd: ./taosd -c cfg/taos.cfg

5.运行taos或者使用C语言写一个连接demo，运行：
出现Bus error (core dumped)

这个是编译方法不正确造成的，还是TDengine本身的Bug导致的啊？

**Comment by sangshuduo** [comment]
TDengine 没有正式支持交叉编译，在 arm32 上的验证也不充分。建议使用 native compile。

**Comment by licj666** [comment]
好的。以后有打算支持吗？大概多久可以支持啊？

**Comment by sangshuduo** [comment]
> 好的。以后有打算支持吗？大概多久可以支持啊？

优先级比较低，如果有付费用户需求可以提升优先级
