### ISSUE TITLE
failed to connect to server, reason: Database not ready

### ISSUE THREAD

**Issue by bs7729** [taosdata/TDengine#18430]
11/24 15:12:18.438563 00033693 RPC WARN DND-S conn 0x7f75cd8cc340 read error:EOF
11/24 15:12:18.482694 00033690 RPC WARN DND-S conn 0x7f75ac01cd90 read error:EOF
11/24 15:12:19.293678 00033691 RPC WARN DND-S conn 0x7f75e412c9e0 read error:EOF
11/24 15:12:20.409757 00033730 DND ERROR failed to send status req since Database not ready, need retry, numOfEps:3 inUse:0
11/24 15:12:20.547896 00033692 RPC WARN DND-S conn 0x7f75dc129bf0 read error:EOF
11/24 15:12:20.582893 00033693 RPC WARN DND-S conn 0x7f75cc008fb0 read error:EOF
11/24 15:12:21.427733 00033690 RPC WARN DND-S conn 0x7f75ac01cd90 read error:EOF
11/24 15:12:22.192783 00033730 DND ERROR failed to send status req since Database not ready, need retry, numOfEps:3 inUse:0
11/24 15:12:22.673843 00033691 RPC WARN DND-S conn 0x7f75e40faed0 read error:EOF
11/24 15:12:22.700492 00033692 RPC WARN DND-S conn 0x7f75dc129bf0 read error:EOF
11/24 15:12:22.840922 00033733 MND dnode:1, in offline state
11/24 15:12:22.841063 00033733 MND dnode:2, in offline state
11/24 15:12:22.841167 00033733 MND dnode:3, in offline state

**Comment by bs7729** [comment]
重启数据库后
![image](https://user-images.githubusercontent.com/64937539/203718188-e32f3750-49ee-4798-acb4-1b248073b135.png)

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
