### ISSUE TITLE
Grafana couldn‘t show multiple groups liner graph 

### ISSUE THREAD

**Issue by nwsj2008** [taosdata/TDengine#18445]
https://www.taosdata.com/user-cases/985.html
原先tdengine 可以group by之后分组展示不同的type
到3.0 之后 展示不出来

shell 里查询出来的是正确的，应该是plugin的问题

sql
select sum(agg_count),operate_type from sentinel_metric where ts>=today() partition by operate_type interval(1m)

![image](https://user-images.githubusercontent.com/6778725/203881404-ea9061b1-dd16-4f28-a216-e46dc6c9026a.png)

**Comment by yu285** [comment]
we will check on this

**Comment by yu285** [comment]
可以修改 display name，目前通过插件没办法直接改lenged的名字   计划下个版本加上该功能

**Comment by leidachui** [comment]
请问这个问题解决了吗

**Comment by leidachui** [comment]
怎么修改 display name，可以把 多个 operate_type  以不同曲线展示出来呢，
我也遇到同样的问题，还只展示两条曲线了

**Comment by endiw395927** [comment]
> 怎么修改 display name，可以把 多个 operate_type 以不同曲线展示出来呢， 我也遇到同样的问题，还只展示两条曲线了

加微信看下？a15652223354
