### ISSUE TITLE
after taosdump restore,some data miss

### ISSUE THREAD

**Issue by StringRock** [taosdata/TDengine#18443]
1.在A服务器用taosdump执行备份，备份后执行打包backups.tar.gz，日志输出备份数量为1.9E
2.传送到B服务器上，解压backups.tar.gz
3.在B服务器用taosdump执行数据恢复，途中没有报错信息， 日志输出恢复数量为1.9E
4.在B服务器的taosd查询对应数据数量，数量不一致，结果少了25%左右，实际在1.4E

备份数据大概在1.9E左右，最后恢复后，只有1.4E，结果少了近5000W

taosd : 2.6.08
taosdump " 2.2.6  

求助：该情况该如何排查原因？

**Comment by sangshuduo** [comment]
服务器 A B，是单机运行还是集群？是远程连接吗？taosdump 使用了多线程恢复吗？线程数是多少？

**Comment by StringRock** [comment]
> 服务器 A B，是单机运行还是集群？是远程连接吗？taosdump 使用了多线程恢复吗？线程数是多少？

都是单机，没有用远程连接，在A上面本地备份,把文件传输后B上面进行本地复原，多线程是默认选项。线程数也是默认的

**Comment by sangshuduo** [comment]
这些数据的时间范围在 db 的 keep 范围内吗？

**Comment by StringRock** [comment]
> 这些数据的时间范围在 db 的 keep 范围内吗？

对，是的，都在这个范围内，我用了时间筛选 -s -e 这两个命令

**Comment by sangshuduo** [comment]
这些数据的时间跨度是多大？db 的 Keep 配置参数值是什么？

**Comment by StringRock** [comment]
> 这些数据的时间跨度是多大？db 的 Keep 配置参数值是什么？

1天，keep= 1825

**Comment by sangshuduo** [comment]
请参考 https://github.com/taosdata/TDengine/issues/14767#issuecomment-1182899027 看  add the "shellActivityTimer 120" and the "rpcMaxTime 7200" to taos.cfg  能否解决问题
