### ISSUE TITLE
Filled values number mismatch

### ISSUE THREAD

**Issue by jiangzhuangxiansheng** [taosdata/TDengine#18457]
**Bug Description**

版本 3.0.1.7
使用fill 填充就报错，如图
![image](https://user-images.githubusercontent.com/33273148/203930298-3c924765-224e-4fca-9fb7-b08848d84e6f.png)

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by yu285** [comment]
应该是 last(val)吧？

3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
