### ISSUE TITLE
fatal error: 'taos.h' file not found

### ISSUE THREAD

**Issue by YanJa** [taosdata/TDengine#18477]
**Bug Description**

**To Reproduce**

```shell
import (
	...
	_ "github.com/taosdata/driver-go/v3/taosSql"
)
```

**Environment (please complete the following information):**
 - OS: `macOS 10.15.6`
 - Memory, CPU, current Disk Space
 - TDengine Version : `version: 3.0.1.7`
 - Go Version: `go version go1.15.2 darwin/amd64`

**Additional Context**
```shell
# github.com/taosdata/driver-go/v3/wrapper
../../../pkg/mod/github.com/taosdata/driver-go/v3@v3.0.3/wrapper/asynccb.go:7:10: fatal error: 'taos.h' file not found
#include <taos.h>
         ^~~~~~~~
1 error generated.
```

**Comment by sangshuduo** [comment]
我安装了 TDengine server 3.0.17 官方安装包，然后跑 TDengine/examples/go 下面的示例程序，没有问题。
请问你的安装过程和步骤是什么？

**Comment by YanJa** [comment]
> 我安装了 TDengine server 3.0.17 官方安装包，然后跑 TDengine/examples/go 下面的示例程序，没有问题。 请问你的安装过程和步骤是什么？

我好像还没装安装客户端驱动 taosc,我去壮壮看
