### ISSUE TITLE
windows11 Visual Studio 2019 build failed: after nmake 

### ISSUE THREAD

**Issue by xiaobage828** [taosdata/TDengine#18470]
[**Performance](url) Issue** 
Any questions related to TDengine's performance can be discussed here.

**Problem Description** 
A clear and concise description of what the problem is.

**To Reproduce**
1. Database parameters used: 
 ```show databases```
2. Verbs used: Insert/Import/Select?
3. Describe the total amount of data
4. Observed performance vs. expected performance

**Screenshots**

**Environment (please complete the following information):**

* OS: [e.g. CentOS 7.0]
* Memory, CPU, current Disk Space
* TDengine Version [e.g. 1.6.1.7]

**Additional Context** 

`
Microsoft (R) 程序维护实用工具 14.29.30147.0 版
版权所有 (C) Microsoft Corporation。  保留所有权利。

[  4%] Built target z
[  5%] Built target pthread
[  6%] Built target regex
[  6%] Built target iconv
[  6%] Built target lz4
[  7%] Built target cJson
[  8%] Built target wepoll
[ 18%] Built target MsvcLibXw
[ 18%] Built target rmonotonic
[ 26%] Built target lua
[ 38%] Built target TSZ
[ 41%] Built target oswindows
[ 45%] Built target os
[ 46%] Building C object src/util/CMakeFiles/tutil.dir/src/version.c.obj
cl: 命令行 warning D9025 :正在重写“/MDd”(用“/MT”)
version.c
[ 46%] Linking C static library ..\..\build\lib\tutil.lib
[ 54%] Built target tutil
[ 56%] Built target common
[ 57%] Built target tfs
[ 58%] Built target trpc
[ 62%] Built target tsdb
[ 66%] Built target query
[ 71%] Built target taos_static
[ 71%] Linking C shared library ..\..\build\lib\taos.dll
LINK Pass 1: command "D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx86\x86\link.exe /nologo @CMakeFiles\taos.dir\objects1 /out:..\..\build\lib\taos.dll /implib:..\..\build\lib\taos.lib /pdb:D:\OpenSource\github\TDengine\debug\build\lib\taos.pdb /dll /version:0.0 /DEF:D:/OpenSource/github/TDengine/src/client/src/taos.def /machine:X86 /debug /INCREMENTAL ..\..\build\lib\trpc.lib ..\..\build\lib\tutil.lib ..\..\build\lib\query.lib ..\..\build\lib\lua.lib ..\..\build\lib\cJson.lib ..\..\build\lib\tsdb.lib ..\..\build\lib\cJson.lib ..\..\build\lib\common.lib ..\..\build\lib\tfs.lib ..\..\build\lib\tutil.lib ..\..\build\lib\lz4.lib ..\..\build\lib\pthread.lib ..\..\build\lib\os.lib ..\..\build\lib\oswindows.lib ..\..\build\lib\z.lib ..\..\build\lib\rmonotonic.lib ..\..\build\lib\MsvcLibXw.lib ..\..\build\lib\TSZ.lib ..\..\build\lib\iconv.lib ..\..\build\lib\regex.lib winmm.lib IPHLPAPI.lib ws2_32.lib ..\..\build\lib\wepoll.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\taos.dir/intermediate.manifest CMakeFiles\taos.dir/manifest.res" failed (exit code 1120) with the following output:
TSDBJNIConnector.c.obj : 找到 MSIL .netmodule 或使用 /GL 编译的模块；正在使用 /LTCG 重新启动链接；将 /LTCG 添加到链接命令行以改进链接器性能
LINK : warning LNK4075: 忽略“/INCREMENTAL”(由于“/LTCG”规范)
  正在创建库 ..\..\build\lib\taos.lib 和对象 ..\..\build\lib\taos.exp
trpc.lib(rpcMain.c.obj) : error LNK2001: 无法解析的外部符号 _random
..\..\build\lib\taos.dll : fatal error LNK1120: 1 个无法解析的外部命令
NMAKE : fatal error U1077: “"D:\Program Files\CMake\bin\cmake.exe"”: 返回代码“0xffffffff”
Stop.
NMAKE : fatal error U1077: “"D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x86\nmake.exe"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x86\nmake.exe"”: 返回代码“0x2”
Stop.
`

**Comment by sangshuduo** [comment]
2010 太老了，请换新版本

**Comment by xiaobage828** [comment]
是Visual Studio 2019的，标题写错了

**Comment by sangshuduo** [comment]
请写一下完整的从 clone 代码到编译过程的命令行输入

**Comment by xiaobage828** [comment]
1. https://github.com/taosdata/TDengine.git
2. 在TDengine目录下面创建mkdir debug 然后 cd debug
3. 打开文件管理器，转到D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build，打开cmd，执行vcvarsall.bat x64
4. 回到TDengine目录下的debug目录执行 cmake .. -G "NMake Makefiles"，没有问题
5. 接着执行 nmake

**Comment by sangshuduo** [comment]
步骤3 执行完继续在这个 cmd 回话窗口里里执行 4、5

**Comment by xiaobage828** [comment]
按照你上面说的，如果不切换目录，在cmd中执行4就报错了。如果cd到debug下，就报我开始提的那个错了。

**Comment by xiaobage828** [comment]
我百度了一下开始提的那个错误，http://t.zoukankan.com/Crysaty-p-6611983.html 。说是要关掉/GL开关，但是我的vs2019找不到这个设置项

**Comment by sangshuduo** [comment]
> 按照你上面说的，如果不切换目录，在cmd中执行4就报错了。如果cd到debug下，就报我开始提的那个错了。

删除 debug 目录，重现完整执行上面步骤。我自己用 2022，公司其他人使用 2017 都没有问题，我觉得不太可能是 2019 恰好有 bug

**Comment by 13917781779** [comment]
发的什么东西，你电话多少？













苏佳音


***@***.***







电子名片新出VIP模板啦，快来体验>>




扫一扫,


快速添加名片到手机




--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: xiaobage828  ***@***.***>
 

 
 发送时间: 2022-11-28 01:11:05
 

 
 收件人:taosdata/TDengine ***@***.***> 

 
 抄送:Subscribed ***@***.***> 

 
 主题: Re: [taosdata/TDengine] windows11 Visual Studio 2019 build failed:after nmake  (Issue #18470)
 





 按照你上面说的，如果不切换目录，在cmd中执行4就报错了。如果cd到debug下，就报我开始提的那个错了。

**Comment by xiaobage828** [comment]
老师，我昨晚重新clone了一遍，然后执行以下1-5的步骤，build成功了，而且顺利启动。
1. git clone https://gitclone.com/github.com/taosdata/TDengine.git
2. TDengine目录下面创建debug文件夹，然后 cd debug
3. 打开文件管理器，转到D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build，打开cmd，执行vcvarsall.bat x64
4. 回到TDengine目录下的debug目录执行 cmake .. -G "NMake Makefiles"
5. 最后在debug目录下执行 nmake
我以前的操作中有两个地方可能会出问题：1.我是从gitee拉的代码 2. 我有阅读client部分的代码，而且添加了注释，注释中还有中文字符，后面才build的。

**Comment by xiaobage828** [comment]
老师，我主语言是java，TDengine是我阅读的第一个C语言开源项目，目前没找到入口文件，入口文件是哪个？类似java的main方法。

**Comment by sangshuduo** [comment]
grep “main(" -rn TDengine

> 老师，我主语言是java，TDengine是我阅读的第一个C语言开源项目，目前没找到入口文件，入口文件是哪个？类似java的main方法。

**Comment by xiaobage828** [comment]
总的入口是TDengine/source/dnode/mgmt/exe/dmMain.c吗?

**Comment by xiaobage828** [comment]
入口文件已找到，路径是src\dnode\src\dnodeSystem.c，函数是int32_t main(int32_t argc, char *argv[])
