### ISSUE TITLE
TDengine

### ISSUE THREAD

**Issue by MegaDzarek** [taosdata/TDengine#18483]
**Bug Description**

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by sangshuduo** [comment]
Please let's know the issue you reported in detailed. Thanks.
