### ISSUE TITLE
Tag values corrupt after batch insert

### ISSUE THREAD

**Issue by EricWice** [taosdata/TDengine#185]
Repro steps:
1. Create database:
create database test; use test;
2. Create super table:
create table sfs (ModifyTime timestamp, FileSize bigint, FileCreationTime timestamp, FileName binary(256)) tags(MachineName binary(20), LogType binary(80));
3. Do batch insert:
insert into n3248803077105136968_2378085273464124640_fs using sfs tags('A', 'VariantConfigurationLogsHourly') values ('2019-07-22 00:59:46.078', 151337, '2019-07-22 00:00:05.288', '1.LOG') n3248803077105136968_5732977098903791999_fs using sfs tags('A', 'WasclIpLoggerExecutionInfoLogging') values ('2019-07-22 00:08:33.405', 29318, '2019-07-22 00:08:33.405', '107912.txt')('2019-07-22 00:27:11.815', 10208, '2019-07-22 00:27:11.815', '10364.txt')('2019-07-22 00:59:18.048', 24079, '2019-07-22 00:08:31.854', '126808.txt')('2019-07-22 00:59:18.782', 158512, '2019-07-22 00:11:02.684', '32208.txt') n3248803077105136968_n546733905966760786_fs using sfs tags('A', 'RecipientReaderAgentLog') values ('2019-07-22 00:20:03.523', 438, '2019-07-22 00:19:36.334', '1.LOG') n3248803077105136968_647379012437868248_fs using sfs tags('A', 'UserConfigurationLog_TransformedApLogs') values ('2019-07-22 00:57:45.315', 3941, '2019-07-22 00:02:39.000', '2019-07-22-00_0.log') n3248803077105136968_n6583212252555004353_fs using sfs tags('A', 'WlmReportLog') values ('2019-07-22 00:02:32.994', 456940, '2019-07-21 23:02:35.027', '1.LOG')('2019-07-22 00:57:35.268', 450177, '2019-07-22 00:02:35.153', '1.LOG') n3248803077105136968_n5563859025000814349_fs using sfs tags('A', 'AttachmentProcessingLogs') values ('2019-07-22 00:03:12.481', 2912, '2019-07-22 00:03:08.653', '2.LOG')('2019-07-22 00:08:38.653', 33154, '2019-07-22 00:04:55.699', '3.LOG')('2019-07-22 00:59:22.735', 1242, '2019-07-22 00:59:00.021', '4.LOG');
4. Get row numbers grouped by logtype:
 select count(*) from sfs group by logtype;

Got result:
        count(*) | logtype
                    3|**AttachmentProcessingLogsnsformedApLogs**                                          |
                    1|**RecipientReaderAgentLognfoLogging**                                               |
                    1|UserConfigurationLog_TransformedApLogs                                          |
                    1|VariantConfigurationLogsHourly                                                  |
                    4|WasclIpLoggerExecutionInfoLogging                                               |
                    2|**WlmReportLogationLog_TransformedApLogs**                                          |

Note the **bold** values of "logtype" in the result, they don't exist in the original sql statement in step 3!

**Comment by hjxilinx** [comment]
This bug has been fixed, please pull the latest code and try again.

**Comment by EricWice** [comment]
Thanks for the quick response, it's fixed!
