### ISSUE TITLE
How to delete lost consumers？

### ISSUE THREAD

**Issue by 0703gaoxiaobo** [taosdata/TDengine#18532]
![image](https://user-images.githubusercontent.com/49136063/204413446-aaf54f43-c722-4779-b1f4-d08edbf705af.png)
一些未取消订阅的consumers应该如何删除呢，DROP CONSUMER GROUP [IF EXISTS] cgroup_name ON topic_name; 无法实现删除。

**Comment by yu285** [comment]
会在固定时间后，自动删除的

**Comment by yu285** [comment]
另，3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
