### ISSUE TITLE
"select last_row(*) from supper table  group by tbname "  result is not expected

### ISSUE THREAD

**Issue by imoxuan** [taosdata/TDengine#18541]
**Bug Description**
select last_row(*) from 超级表 group by tbname 并不是预想的结果。如下图：device_no为d003的数据，期望tv为11的，结果是tv为9的，不是所要的。device_no为d002的也一样。

启用了CACHEMODEL：'last_row'

![image](https://user-images.githubusercontent.com/11343073/204451512-67a70cd4-5249-4128-94d3-cd82352022ed.png)

**表结构及插入数据**

CREATE STABLE meters(
ts timestamp,
tv SMALLINT UNSIGNED,
cs TINYINT UNSIGNED,
th SMALLINT UNSIGNED
) TAGS(
  device_no BINARY(60)
);

INSERT INTO d001 USING meters TAGS('d001') VALUES(NOW,21,1,50);
INSERT INTO d001 USING meters TAGS('d001') VALUES(NOW,30,1,50);

INSERT INTO d002 USING meters TAGS('d002') VALUES(NOW,40,1,50);
INSERT INTO d002 USING meters TAGS('d002') VALUES(NOW,53,1,50);

INSERT INTO d003 USING meters TAGS('d003') VALUES(NOW,9,1,50);
INSERT INTO d003 USING meters TAGS('d003') VALUES(NOW,11,1,50);

**SQL 插入是一条一条分开执行的，所以ts中时间戳不会重复。**

**环境**
Centos 7.6
TDengine Version：3.0.1.6

**Comment by yu285** [comment]
可以加微信 15652223354 做下调试

**Comment by imoxuan** [comment]
创建数据库的时候，设置 CACHEMODEL 'last_row'会出现。

**Comment by tusky2015** [comment]
> 创建数据库的时候，设置 CACHEMODEL 'last_row'会出现。

你好，问题解决了吗？我这边也出现同样的问题。
taos版本 3.1.0.2
cachemodel设置为非none时，last_row()和last()函数返回的数据不正确

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
