### ISSUE TITLE
cluster couldn't be inserted after restart service

### ISSUE THREAD

**Issue by xtxz** [taosdata/TDengine#18573]
taos的版本是2.6.0.14，采用的是三个管理节点三份数据的模式
操作：
1、重启其中的一个备节点，重启期间显示offline
![image](https://user-images.githubusercontent.com/49859359/204732574-2b411c59-e274-41d3-8791-017796e8910e.png)
2、Java客户端报错：
java.sql.SQLException: TDengine ERROR (2350): failed to bind table name and corresponding tags, reason: Database unsynced

**Comment by yu285** [comment]
可以加微信 15652223354 做具体排查
