### ISSUE TITLE
JDBC queryForList column use "as" create alias invalid

### ISSUE THREAD

**Issue by tuine** [taosdata/TDengine#18575]
**Bug Description**
JAVA JdbcTemplate，function：queryForList or queryForMap
using `as` is invalid When querying the timestamp field, but there is no problem with other fields

**To Reproduce**
```java
String sql = "select LAST(ts) AS ts1,LAST(ts) AS ts2,max(key) as key1, max(key) as key2 from ts_kv interval(1s) limit 2;";
List<Map<String, Object>> maps = jdbcTemplate.queryForList(sql2);
```
list map result:
```json
{
  "key1" : 36,
  "key2" : 36,
  "ts" : 1669714246316
}
```

**Environment (please complete the following information):**
 - OS: centos7
 - Memory, CPU, current Disk Space
 - TDengine Version：3.0.1.6

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
