### ISSUE TITLE
show create table result not show correctly

### ISSUE THREAD

**Issue by xbkaishui** [taosdata/TDengine#18583]
**Bug Description**
show create table  sql result not show correctly,  ... 

**To Reproduce**
```
taos> show create table d6248;
             Table              |          Create Table          |
==================================================================
 d6248                          | CREATE TABLE `d6248` USING ... |
Query OK, 1 row(s) in set (0.004003s)
```
**Expected Behavior**
full create sql display

**Screenshots**

**Environment (please complete the following information):**
 - OS: docker 
 - Memory, CPU, current Disk Space
 - TDengine Version 3.0.1.8

**Comment by yu285** [comment]
add "\G" in the tail
