### ISSUE TITLE
05/09 18:50:15.514680 7f68169ce740 TSC set config file directory:/etc/taos

### ISSUE THREAD

**Issue by weilisikaili** [taosdata/TDengine#1859]
关于使用python链接的taos的问题:
1.05/09 18:50:15.514680 7f68169ce740 TSC set config file directory:/etc/taos  通常情况下这一行代表了连接器成功读取了链接对象的配置文件,是否能代表已经链接成功呢?
2. 如果代表了链接成功,我在代码的输出日志中看到了执行一次数据库操作,记录下了多个(类似于问题第一点)输出,也就是说我代码中写下一次链接代码 却读取了多次配置文件产生了多个链接对象? ,长期的脚本执行是否会导致链接对象(或会话)过多,而导致链接识别代码停止,数据库服务关闭呢?(在头两天,我是将链接对象和close写在while true里面的, 即一次循环包含一次链接和链接关闭, 结果是几个小时后,出现了两个错误: 1login disconnected, login again; 2.Session is too much; 到这里就像验证了我之前的想法, connection冗余了) 
3.我利用了时序数据库的一个特性: 不会重复插入数据; 把每间隔五分钟一条的数据,建立链接,执行sql,插入数据; 达到了不会插入重复数据的目的;  但是,执行重复数据插入时所建立的链接对象,应该是没有关闭的, 至少我在日志中没有看到过(这里我想到会不会有一种可能: 当执行sql插入数据时,无法close)
4.今天我改写了, 我将我的代码封装后, 我希望在局域网中的两个云主机都存一份数据, 相当于备份,我创建链接执行插入一个taos, 然后我将sql传给另一个链接对象, 链接会正常链接上,但是会报错:invalid submit message (且我验证过sql并没有变化, 两个云主机中的版本,数据库,以及表结构都完全相同)

**Comment by weilisikaili** [comment]
(这里我想到会不会有一种可能: 当执行sql插入数据时,无法close);  第三点最后一句话修改: 这里我想到会不会有一种可能: 当执行sql插入数据未成功插入时,无法close

**Comment by Shawshank-Smile** [comment]
Very useful information. What is the stage of your project by now?

**Comment by weilisikaili** [comment]
> Very useful information. What is the stage of your project by now?
mvp版已出,但由于以上提出的taos数据库链接的一些问题, 数据流转不通畅,不能让人放心的在后台执行脚本, 我将链接, 执行sql, 关闭链接放入了队列订阅中, 相当于借用了订阅的监听特性,但还是出现了我所提及的第四点问题.

**Comment by Shawshank-Smile** [comment]
please add my wechat 13720014098.

**Comment by weilisikaili** [comment]
> please add my wechat 13720014098.

已申请好友

**Comment by sangshuduo** [comment]
no update, close it.
