### ISSUE TITLE
REST API sql result not same as native API

### ISSUE THREAD

**Issue by WWTBNBWN** [taosdata/TDengine#18597]
![image](https://user-images.githubusercontent.com/53170533/204942238-ec35c606-5365-43d7-bc8f-8f2126897ecf.png)
![image](https://user-images.githubusercontent.com/53170533/204942271-4061c5b3-e61d-49cc-b8bb-855c54ed8c79.png)
两条sql一样的但是返回结果不一样

**Comment by yu285** [comment]
版本号是？

**Comment by WWTBNBWN** [comment]
![image](https://user-images.githubusercontent.com/53170533/205237698-d8a61150-1bc4-4e9f-9036-e29344941ca8.png)


> 版本号是？
