### ISSUE TITLE
创建STABLE报错：TDengine ERROR (80000200): invalid operation: row length exceeds max length

### ISSUE THREAD

**Issue by lowe00** [taosdata/TDengine#18598]
版本2.6.0.16
建表语句：
CREATE STABLE test
(
 ts TIMESTAMP,
 monitor_name NCHAR(32),
 group_ids NCHAR(500),
 group_names NCHAR(300),
 organization_id NCHAR(40),
 organization_name NCHAR(32),
 device_type INT,
 monitor_type INT,
 professional_ids NCHAR(500),
 professionals_name NCHAR(200),
 plate_color INT,
 sim_card NCHAR(30),
 reissue INT,
 create_time BIGINT,
 sys_time BIGINT,
 mile_sen_mileage DOUBLE,
 mile_sen_speed DOUBLE,
 mile_sen_unusual INT,
 gps_speed DOUBLE,
 grapher_speed DOUBLE,
 gps_mileage DOUBLE,
 gps_oil DOUBLE,
 direction DOUBLE,
 latitude DOUBLE,
 longitude DOUBLE,
 altitude DOUBLE,
 address NCHAR(100),
 city NCHAR(20),
 province NCHAR(20),
 status BIGINT,
 original_latitude DOUBLE,
 original_longitude DOUBLE,
 satellites_number INT,
 location_type INT,
 location_pattern INT,
 acc INT,
 location_status INT,
 operation_status INT,
 oil_way_status INT,
 circuitry_status INT,
 car_door_lock INT,
 travel_status INT,
 air_comp_status INT,
 alarm BIGINT,
 duration_time BIGINT,
 battery_elec INT,
 signal_type INT,
 signal_strength INT,
 wifi_signal_strength INT,
 battery_voltage DOUBLE,
 terminal_version NCHAR(20),
 device_message NCHAR(1000),
 attach_info NCHAR(1000),
 positive_negative NCHAR(1000),
 io_signal_data NCHAR(1000),
 lbs_data NCHAR(1000),
 wifis_data NCHAR(1000),
 drive_warn NCHAR(1000),
 unusual_drive_warn NCHAR(1000),
 elec_data NCHAR(1000),
 obd NCHAR(1000),
 monitor_status INT,
 tyre_infos NCHAR(1000)
)
TAGS (monitor_id BIGINT);

**Comment by sangshuduo** [comment]
https://docs.taosdata.com/2.6/taos-sql/limit/#%E4%B8%80%E8%88%AC%E9%99%90%E5%88%B6

**Comment by sangshuduo** [comment]
https://docs.taosdata.com/2.6/taos-sql/data-type/#%E6%94%AF%E6%8C%81%E7%9A%84%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B

每个 nchar 占 4 字节

**Comment by lowe00** [comment]
> https://docs.taosdata.com/2.6/taos-sql/data-type/#%E6%94%AF%E6%8C%81%E7%9A%84%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B
> 
> 每个 nchar 占 4 字节

这个限制可以通过配置取消吗？

**Comment by sangshuduo** [comment]
后面版本会提高一点，但肯定不是没有限制，暂时没有配置项

**Comment by lowe00** [comment]
> 

好的，谢谢
