### ISSUE TITLE
执行插入语句时报java.sql.SQLException: TDengine ERROR (8000000b): Unable to establish connection

### ISSUE THREAD

**Issue by ideazoom** [taosdata/TDengine#18600]
创建数据库语句正常，执行插入时报java.sql.SQLException: TDengine ERROR (8000000b): Unable to establish connection错误。
安装时填写的firstEp, 安装后将taos.cfg配置文件中的firstEp 注释掉了。
运行环境：
服务端：centos7 虚拟机；
客户端：windows 11 java 程序

**Comment by yu285** [comment]
https://www.taosdata.com/engineering/11076.html 看下问题1 排查一下即可
