### ISSUE TITLE
 row length exceeds max length

### ISSUE THREAD

**Issue by sytpb** [taosdata/TDengine#1863]
taos> CREATE TABLE  Acc (stamp TIMESTAMP,data1 nchar(512),data2 nchar(512)) TAGS(corpid nchar(32));

DB error: invalid SQL: row length exceeds max length

must less than  1024 ??       is it set to manually ?

**Comment by sytpb** [comment]
![image](https://user-images.githubusercontent.com/12178686/81491830-4a3dd400-92c5-11ea-87d9-4319d92a5840.png)
4096 bytes  , why 512 + 512  can't pass ?

**Comment by sangshuduo** [comment]
each nchar needs 4 bytes to store.
