### ISSUE TITLE
td 3.0.1.8 can't use taosdump

### ISSUE THREAD

**Issue by tanxon001** [taosdata/TDengine#18637]
td 3.0.1.8 can't use tcpdump
error:
taosdump: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory

**Comment by sangshuduo** [comment]
For CentOS 7/RHEL

sudo yum install -y zlib-devel xz-devel snappy-devel jansson jansson-devel pkgconfig libatomic libstdc++-static openssl-devel gawk

For CentOS 8/Rocky Linux

sudo yum install -y epel-release
sudo yum install -y dnf-plugins-core
sudo yum config-manager --set-enabled powertools
sudo yum install -y zlib-devel xz-devel snappy-devel jansson jansson-devel pkgconfig libatomic libstdc++-


稍后我们改成静态链接
