### ISSUE TITLE
failed to connect to server, reason: Database not ready

### ISSUE THREAD

**Issue by lihy8080** [taosdata/TDengine#18648]
**Bug Description**
install version3.0.1.8 on centos7，run comand taos，return "failed to connect to server, reason: Database not ready"。
 

**Environment (please complete the following information):**
 - OS: Centos7
 installed tdengine version 2.x before，but i have deleted /var/lib/taos and reinstall，the problem is still there。

**Comment by yu285** [comment]
经排查为firstEP配置问题
