### ISSUE TITLE
taosadapter 运行一段时间就会造成TAOS_ADAPTER error "write to TDengine error" model=monitor error=[0x3] Authentication failure

### ISSUE THREAD

**Issue by sunchunfeng** [taosdata/TDengine#18649]
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/30862573/205284149-13922e47-b76a-4a21-be76-0ad43bdfd462.png">

请问taosadapter运行一段时间就会出现TAOS_ADAPTER error "write to TDengine error" model=monitor error=[0x3] Authentication failure，程序在连接taosadapter 就调用不通了，这个怎么解决？是什么原因造成的呢？

**Comment by sunchunfeng** [comment]
**补充：**
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/30862573/205284673-90f45e20-a8ec-4413-9f86-381f7404450d.png">
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/30862573/205284952-96ab2f5c-b7dc-42c7-870d-33f4be30541b.png">
重启之前还是taosadapter 状态还是正常的，查看详细日志报TAOS_ADAPTER error "write to TDengine error" model=monitor error=[0x3] Authentication failure ；然后重启下taosadapter就又能访问了。有大神知道是什么原因导致身份认证失败的吗？

**Comment by huskar-t** [comment]
请给出 TDengine 的版本和系统环境

**Comment by sunchunfeng** [comment]
您好，TDengine 的版本2.6.0.16,系统版本：centos 7

**Comment by sunchunfeng** [comment]
<img width="1465" alt="image" src="https://user-images.githubusercontent.com/30862573/205535346-7665f260-8b72-413b-befa-5a71baa58e09.png">
TDengine 的版本2.6.0.16,系统版本：centos 7,TDengine运行看着像是内容运行没释放，重启一下内存就会释放掉一部分。配置文件没有做特殊的配置。这个怎么优化。

**Comment by szylmzs** [comment]
请问这个问题解决没 我也是一样的版本 shell里能连上 restfull方式连接报一样的错误

**Comment by huskar-t** [comment]
请升级到 2.6 最新版本

**Comment by Byrontoo** [comment]
2.6.0.32，运行一段时间后，也报这个错

**Comment by leimeng-ma** [comment]
这个问题现在有解决方案吗？当前使用的版本是taosadapter 2.6.0.10版本

**Comment by cqjxc** [comment]
我也遇到同样得问题， centos  7    2.6.0.12，我是修改了默认管理员得密码。修改后 TAOS 命令就无法进入 必需输入密码，同时这边也有出现报错得情况了。是不是没有同步 ，如何修改配置
