### ISSUE TITLE
2.4.0.5 TAOS-RS desc: Database not specified or available

### ISSUE THREAD

**Issue by psvirgo** [taosdata/TDengine#18644]
目前都是使用的 TAOS-RS 的方式链接的 。版本 2.4.0.5

测试环境 可以执行 没有问题 ，但是正式环境执行就报错了  
TDengine ERROR (380): sql: create stable if not exists dmp_test.meters (ts timestamp, current float, voltage int, phase float) TAGS (location binary(64), groupId int);, desc: Database not specified or available

**Comment by psvirgo** [comment]
已经解决

**Comment by Autoloop** [comment]
> 已经解决

这个是怎么解决的，是通过sql指定数据库名么
