### ISSUE TITLE
insert into Stable  happen DB error . 

### ISSUE THREAD

**Issue by sytpb** [taosdata/TDengine#1864]
Stable :

CREATE TABLE  AdminList(stamp TIMESTAMP,user_list nchar(512) ,type TINYINT)  TAGS(corpid nchar(32)) ;

Error happen as below , 

taos> INSERT INTO xtoken.ww2b7dbb2cbc418245 USING xtoken.AdminList TAGS (ww2b7dbb2cbc418245) VALUES(1589094946643,'xxxxxxx',1);

**DB error: invalid SQL: syntax error near ");" () expected)**

caused by the Tinyint field ? 
I don't know where is wrong ?

**Comment by sytpb** [comment]
I know the result , it is caused by  that there is another same name sub-table ,   so second 'insert into' failure .. 

such as the case : 
Stable   A   
insert into  aa using A ....    

Stable B 
insert into aa using B...    

same name sub-table created by two Stable  , that is not allowed in one DB ..  right ?

**Comment by sangshuduo** [comment]
It works well at my side.
Could you please list the full command sequence you inputted?

**Comment by sytpb** [comment]
ok later , I will list the command...

**Comment by sytpb** [comment]
`DB: xtoken

CREATE TABLE  AccToken (stamp TIMESTAMP, access_token nchar(512)) TAGS(corpid nchar(32));

CREATE TABLE   SuiteToken(stamp TIMESTAMP, access_token nchar(512)) TAGS(corpid nchar(32));

CREATE TABLE  AdminList(stamp TIMESTAMP,user_list nchar(512) ,type TINYINT)  TAGS(corpid nchar(32)) ;

--------------------------------------------------------------------------------------------------------------

DB: xdata

CREATE TABLE  BaseInfo (stamp TIMESTAMP, permanent_code nchar(512),agentid nchar(12),corp_name nchar(64),corp_user_max SMALLINT,corp_industry nchar(32),location nchar(64),dealer_corpid nchar(32),dealer_corp_name nchar(64),register_code nchar(32))  TAGS(corpid nchar(32)) ;

------------------------------------------------------------------------------------------------------------------
after Stable be created  then using insert into , such as below , 

INSERT INTO xdata.ww2b7dbb2cbc418245 USING xdata.BaseInfo TAGS (ww2b7dbb2cbc418245) VALUES (1589173798938,'CgHwxKCLg2m8eVaX7sIvxqwbU6QN6g0ThxOI0Q0TeYc','undefined','王技',200,'服务','xxx','','','') xtoken.ww2b7dbb2cbc418245 USING xtoken.AccToken TAGS (ww2b7dbb2cbc418245) VALUES (1589173798938,'WajwyaKp2WNK-UqiKDBFO94LkHjIgU-itiFeU3du0yalBbMNhI0CPsch0LepNGSm_M-9U2P8_hDo5nbYW-f1FAogHeBcLcR214k5FFP9-Ptn2Up8Rz8dF2uu4SXB_rkA8IJTB9CP0ij8SbGLAbgg7oXU4_o1SwoLZ5go2tKko7DT3W2JvcXDVMQbZ_NYUyUkOx1FU9TCb_RnfvzojlmtJw') xtoken.ww2b7dbb2cbc418245_sui USING xtoken.SuiteToken TAGS (ww2b7dbb2cbc418245) VALUES (1589173798938,'-ke2xn-p8x1IUy4fyPJXQHkO_F3kPnPeEge3hxR8hmETdCZnb5K-ZICLBVxNqo5uBPLEHxyklqxtfALal7nkf0HZb4kmDrjQlxBDhHvxkOZREjsTsUp_79BjPFKLZcGL') xtoken.ww2b7dbb2cbc418245_adm USING xtoken.AdminList TAGS (ww2b7dbb2cbc418245) VALUES (1589173798938,'[55555]',1);








The Insert SQL : 
INSERT INTO salary.ww2b7dbb2cbc418245 USING salary.BaseInfo TAGS (ww2b7dbb2cbc418245) VALUES (1589173798938,'CgHwxKCLg2m8eVaX7sIvxqwbU6QN6g0ThxOI0Q0TeYc','undefined','王',200,'IT','北京','','','') xtoken.ww2b7dbb2cbc418245 USING xtoken.AccToken TAGS (ww2b7dbb2cbc418245) VALUES (1589173798938,'WajwyaKp2WNK-UqiKDBFO94LkHjIgU-itiFeU3du0LepNGSm_M-9U2P8_hDo5nbYW-f1FAogHeBcLcR214k5FFP9-Ptn2Up8Rz8dF2uu4SXB_rkA8IJTB9CP0ij8SbGLAbgg7oXU4_o1SwoLZ5go2tKko7DT3W2JvcXDVMQbZ_NYUyUkOx1FU9TCb_RnfvzojlmtJw') xtoken.ww2b7dbb2cbc418245 USING xtoken.SuiteToken TAGS (ww2b7dbb2cbc418245) VALUES (1589173798938,'-ke2xn-p8x1IUy4fyPJXQHkUp_79BjPFKLZcGL') xtoken.ww2b7dbb2cbc418245 USING xtoken.AdminList TAGS (ww2b7dbb2cbc418245) VALUES (1589173798938,'[11111]',1);

`

**Comment by sytpb** [comment]
`DB: xtoken

CREATE TABLE  AccToken (stamp TIMESTAMP, access_token nchar(512)) TAGS(corpid nchar(32));

CREATE TABLE   SuiteToken(stamp TIMESTAMP, access_token nchar(512)) TAGS(corpid nchar(32));

--------------------------------------------------------------------------------------------------------

INSERT INTO xtoken.ww2b7dbb2cbc418245 USING xtoken.AccToken TAGS (ww2b7dbb2cbc418245) VALUES(1589173798949,'WtJw')  
xtoken.ww2b7dbb2cbc418245 USING xtoken.SuiteToken TAGS (ww2b7dbb2cbc418245) VALUES (1589173798949,'-kecGL');`

![image](https://user-images.githubusercontent.com/12178686/81528225-c8b27880-938e-11ea-859d-b7d65d03f829.png)
taos> INSERT INTO xtoken.ww2b7dbb2cbc418245 USING xtoken.AccToken TAGS (ww2b7dbb2cbc418245) VALUES(1589173798949,'WtJw')  
   -> xtoken.ww2b7dbb2cbc418245 USING xtoken.SuiteToken TAGS (ww2b7dbb2cbc418245) VALUES (1589173798949,'-kecGL');
Query OK, 1 row(s) affected (0.000336s)

same DB  , different Stable ,   inert into the same timestamp into Stables , it will happen error ,   

as the primary key limitation  don't be allowed ,    I thought sub-table from different Stable is different table,   but it is not.  the result show me this ...... 

@sangshuduo

**Comment by sytpb** [comment]
INSERT INTO xtoken.ww2b7dbb2cbc418245 USING xtoken.AccToken TAGS (ww2b7dbb2cbc418245) VALUES(1589173798950,'WtJw')   xtoken.ww2b7dbb2cbc418245 USING xtoken.SuiteToken TAGS (ww2b7dbb2cbc4182
45) VALUES (1589173798951,'-kecGL');
Query OK, 2 row(s) affected (0.000483s)



this works ok ,   1589173798951   and 1589173798950 different time stamp , 

I think same name sub-table created by two STABLEs should be different table, so i can insert data into the  two sub-table at the same time with same timestamp .

**Comment by sangshuduo** [comment]
Two sub-tables with the same name are not allowed by design. Please use a different name.
