### ISSUE TITLE
我该如何对ts进行年月日的group by查询

### ISSUE THREAD

**Issue by zhuangQingGuang** [taosdata/TDengine#18676]
没有找到类似DATE_FORMAT()函数，我该如何对ts进行年月日的group by查询

**Comment by kshenkshen** [comment]
有相同的疑问，没有DATE_FORMAT()函数，如何查询每天某一段时间内的数据，比如查询每天[12:30,13:30]的数据

**Comment by zhuangQingGuang** [comment]
推荐使用窗口切分查询
