### ISSUE TITLE
 Error creating bean with name 'webMvcMetricsFilter' defined in class path resource [org/springframework/boot/actuate/autoconfigure/metrics/web/servlet/WebMvcMetricsAutoConfiguration.class]: Unsatisfied dependency expressed through method 'webMvcMetricsFilter' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'prometheusMeterRegistry' defined in class path resource [org/springframework/boot/actuate/autoconfigure/metrics/export/prometheus/PrometheusMetricsExportAutoConfiguration.class]: Initialization of bean failed; nested exception is java.lang.UnsatisfiedLinkError: com.taosdata.jdbc.TSDBJNIConnector.setConfigImp(Ljava/lang/String;)Lcom/taosdata/jdbc/TSDBException;

### ISSUE THREAD

**Issue by yxwLearn** [taosdata/TDengine#18678]
TD版本：2.6.0.24 arm版本
java的连接器版本：2.0.38
启动报错如下
![image](https://user-images.githubusercontent.com/44970358/205480334-591a3403-2309-4c31-8073-569c7349b804.png)
![image](https://user-images.githubusercontent.com/44970358/205480338-fe6e0f9a-a37e-4640-bb7e-60b9ffc46473.png)

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/

如果还有具体的使用问题，可以加微信：a15652223354
