### ISSUE TITLE
 td-client and restapi query result not same

### ISSUE THREAD

**Issue by zgahxxwht** [taosdata/TDengine#18683]
_value字段为float类型
![image](https://user-images.githubusercontent.com/44645235/205531461-a45e5300-0c9e-4c07-9efc-ed117738e419.png)
![image](https://user-images.githubusercontent.com/44645235/205531499-d7987fce-698e-419f-a7d6-953a7ece37c1.png)

**Comment by yu285** [comment]
需要了解写入侧的SQL或者逻辑，麻烦提供下
