### ISSUE TITLE
TDengine ERROR (80000214): No write permission

### ISSUE THREAD

**Issue by sharkinocean** [taosdata/TDengine#18696]
复现步骤：
1.内网CentOS7.9上搭建单机版TDEngine Server，版本2.6.0.1，开放TCP+UDP的6030-6042端口
2.hostname设置为td-server
3.taoshll可以连接到td-server，可以建一个超级表。
4.向子表里插入一条数据
5.提示：TDengine ERROR (80000214): No write permission

**Comment by hb407033** [comment]
跟你一样的问题，不过我是在容器中出现的，到现在都没解决

**Comment by hb407033** [comment]
客户端驱动版本低于服务端版本导致的问题，更新客户端驱动版本后解决
