### ISSUE TITLE
DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable

### ISSUE THREAD

**Issue by wild-River2016** [taosdata/TDengine#18693]
**Bug Description**
启动TDengine（3.0.1.5）时报如下错误
12/05 10:58:57.314733 00016713 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:2
12/05 10:59:07.783313 00016713 DND ERROR failed to create dnode since Resource temporarily unavailable
12/05 10:59:07.842038 00016713 DND ERROR failed to init dnode since Resource temporarily unavailable

**To Reproduce**
之前好好的，刚才就是修改了一下数据库配置（内存中缓存子表的最近数据），
执行了一下alert database xx cachemodel 'last_row'这个sql。
然后执行重启的时候就报上面的错了。不知是不是和修改这个参数有关系。

**Expected Behavior**
希望能够启动成功。

**Screenshots**
![微信图片_20221205114610](https://user-images.githubusercontent.com/24984406/205545285-adadde44-bec4-4544-80c9-1d9db2ccd2fb.png)

**Environment (please complete the following information):**
 - OS: centos
 - Memory:16G
 -  CPU:4核
 -  current Disk Space： 1T
 - TDengine Version [3.0.1.5]

**Additional Context**

**Comment by yu285** [comment]
重启问题不见，应该是有僵尸进程
