### ISSUE TITLE
流式计算超级表默认tag groupid为空

### ISSUE THREAD

**Issue by logicfox-hu** [taosdata/TDengine#18711]
版本：3.0.1.7
测试创建流的sql：
create stream if not exists swStream trigger AT_ONCE into swjumpdata as select orgcode,node,point,first(ts) as ts,sw from iotswitch partition by tbname state_window(sw);

创建后原超级表数据录入后，流的超级表swjumpdata中tag groupid始终为空
![image](https://user-images.githubusercontent.com/80880139/205599218-1c40ff66-96b3-4dc3-8273-3470184886b4.png)

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
