### ISSUE TITLE
make TDengine storage usage visible 

### ISSUE THREAD

**Issue by cuteLittleDevil** [taosdata/TDengine#18713]
1 想直接查询磁盘占用情况 包括库 超级表 子表等
2 个人希望的方式参考du命令
如 test库 superTable表 T0001子表的情况

du test -h (显示test数据库所占用的磁盘大小 )
``` 
test 100mb
``` 
du test.superTable -h (显示test数据库superTable表所占用的磁盘大小)
``` 
test.superTable 70mb
``` 
增加多种辅助功能
du -hL=1(显示tdengine第一级数据库的情况)
``` 
├── tdengine
     ├── test             (100mb)
``` 
du -hL=2(显示tdengine第一级数据库和第二级超级表的情况)
``` 
├── tdengine
     ├── test             (100mb)
    │   └── supertable (70mb)
``` 
du history test -dh (显示test数据库每日新增加的磁盘大小)
``` 
2022-12-01 10mb
2022-12-02  15mb
2022-12-03 75mb
``` 
reset等连接方式查询返回对应的结构体 如
``` json lines
{
    "db_name": "test",
    "size": 100
    "remark": "使用mb为单位的查询"
}
```

**Comment by yu285** [comment]
感谢您的建议我们会仔细评估

**Comment by Sweetestheart** [comment]
好，支持
