### ISSUE TITLE
window10 access docker TDengine cluster withe error: "Unable to resolve FQDN"

### ISSUE THREAD

**Issue by lanyue52011** [taosdata/TDengine#18714]
数据库版本：TDengine2.0.18
window 客户端 TDengine-client-2.0.18.0
本地window10系统，访问远程linux（testHost1/192.168.28.222）系统中docker TDengine集群（db1,db2,db3）,都设置host，其中,db1  所有端口映射到testHost1；本地window系统配置hosts: 192.168.28.222 testHost1和 192.168.28.222 db1  ;客户端可以连接成功，可以执行show,use 操作；执行select操作提示：“DB error: Unable to resolve FQDN”； 这种情况不知道是我配置没有正确还是系统问题。

**Comment by lanyue52011** [comment]
docker 集群创建网段为127.18.0.0子网，分别是 127.18.0.100/db1   127.18.0.101/db2  127.18.0.102/db3

**Comment by yu285** [comment]
您好，可以加微信 : a15652223354 做具体排查

**Comment by yu285** [comment]
连接问题 https://www.taosdata.com/engineering/11076.html 看下问题1 排查一下
