### ISSUE TITLE
我是在本地windows系统，用的3.0.1.8版本，可以连接到服务端，但不能创建数据库

### ISSUE THREAD

**Issue by laogit** [taosdata/TDengine#18721]
![5ef52d8254f46b4e22adb01ff3d64f2](https://user-images.githubusercontent.com/119646767/205784996-2814b1b7-c399-47e1-a8ee-d66fdd04f376.png)

**Comment by laogit** [comment]
https://github.com/Yurunsoft/tdengine-restful-connector，用的这个连接器

**Comment by laogit** [comment]
前天连接还是好的，增删改查都可以

**Comment by sangshuduo** [comment]
应该在 https://github.com/Yurunsoft/tdengine-restful-connector 仓库提 issue，这个连接器是社区贡献，不是  涛思团队开发的

**Comment by laogit** [comment]
> 应该在 https://github.com/Yurunsoft/tdengine-restful-connector 仓库提 issue，这个连接器是社区贡献，不是 涛思团队开发的
你们对于php的连接器开发有计划吗？什么时候能看到官方的版的啊，尤其适用于windows客户的

**Comment by yu285** [comment]
windows 早期问题较多，开源版维护不过来，回收到到企业版重做了。 所以windows版本到了 3.0.7.1 之后就没法再升级了，也没有维护团队支持。所以咱们还是换到 linux 版本再使用，目前最新版为 3.2.3.0。

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
