### ISSUE TITLE
2.6.0.8 python can't insert

### ISSUE THREAD

**Issue by BenBenzzZ** [taosdata/TDengine#18734]
创建了一个表，表里有5个字段，有一个tag，在taosshell中insert可以插入新数据，但是同样的命令在python中不可以，报错“table does not exist”
conn_td = taos.connect(host="xx", port=6030, user="root", password="xx", database="xx")
cursor_td = conn_td.cursor()
sql_insert = “ insert into d0001 using forecast_anaylysis tags(d0001) values('2022-05-05 01:11:11', 'sx_cn001', 0, 0, 0); ”
cursor_td.execute(sql_insert)
conn_td.close()

**Comment by sangshuduo** [comment]
taos connector 什么版本？
使用 https://docs.taosdata.com/2.6/reference/connector/python/#%E5%BB%BA%E7%AB%8B%E8%BF%9E%E6%8E%A5 的示例代码可以吗？

**Comment by BenBenzzZ** [comment]
已解决，python里面的sql命令必须使用大写才可执行。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Shuduo ***@***.***>
发送时间: 2022年12月6日 17:35
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [taosdata/TDengine] 2.6.0.8版本采用python无法insert (Issue #18734)


taos connector 什么版本？
使用 https://docs.taosdata.com/2.6/reference/connector/python/#%E5%BB%BA%E7%AB%8B%E8%BF%9E%E6%8E%A5 的示例代码可以吗？

―

**Comment by BenBenzzZ** [comment]
> taos connector 什么版本？ 使用 https://docs.taosdata.com/2.6/reference/connector/python/#%E5%BB%BA%E7%AB%8B%E8%BF%9E%E6%8E%A5 的示例代码可以吗？

解决了，python里面sql语句命令要全部用大写才行，字段名表名之类为小写才能执行，taos shell里则没有这样的限制。

**Comment by BenBenzzZ** [comment]
> taos connector 什么版本？ 使用 https://docs.taosdata.com/2.6/reference/connector/python/#%E5%BB%BA%E7%AB%8B%E8%BF%9E%E6%8E%A5 的示例代码可以吗？

connector 是2.6.4

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/

如果还有具体的使用问题，可以加微信：a15652223354
