### ISSUE TITLE
3.0.1.7 query crash 

### ISSUE THREAD

**Issue by yerunqin** [taosdata/TDengine#18739]
错误信息：taosd: /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/tsdb/tsdbUtil.c:707: tRowMergerAdd: Assertion `0' failed.
场景复现：
![image](https://user-images.githubusercontent.com/38376164/205854627-1e8850f8-9242-470c-a317-44debe215413.png)
写入以上重复数据到对应的两张表中，查询时数据库直接奔溃

**Comment by yu285** [comment]
收到我们看下

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
