### ISSUE TITLE
TAOS_ADAPTER error "write to TDengine error" model=monitor error=[0x9] Bad file descriptor

### ISSUE THREAD

**Issue by zpf123zpf** [taosdata/TDengine#18756]
DB error: stale file handle (0.010670s)  错误   日志中报：12/07 11:03:00.774633 00000062 TAOS_ADAPTER error "write to TDengine error" model=monitor error=[0x9] Bad file descriptor
12/07 11:03:30.773983 00000062 TAOS_ADAPTER error "write to TDengine error" model=monitor error=[0x9] Bad file descriptor
12/07 11:04:00.774196 00000062 TAOS_ADAPTER error "write to TDengine error" model=monitor error=[0x9] Bad file descriptor
1                             涛思版本是：2.6.06

**Comment by yu285** [comment]
可以先升级到 2.6.0.32

**Comment by Byrontoo** [comment]
2.6.0.32运行一段时间后也报这个错
