### ISSUE TITLE
本地测试没问题，上服务器出现错误

### ISSUE THREAD

**Issue by 13116633458** [taosdata/TDengine#18759]
TDengine ERROR (80002662): Fail to get table info, error: Qnode not there

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
