### ISSUE TITLE
Query Error  when port 6030 map to external network

### ISSUE THREAD

**Issue by boboyunz** [taosdata/TDengine#18750]
**Bug Description**
Query error with C# Connector when port 6030 map to external network . while is run well within the local area network.

**To Reproduce**
1. Map port 6030 to  external network
2. Ttry to query data pass the external port
3. query error happen

**Screenshots**
![TDengine error](https://user-images.githubusercontent.com/45583988/205935996-387677aa-87b6-4f45-8b1c-4fad7f036aed.png)

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.9]
 - TDengine Version 3.0.16

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
