### ISSUE TITLE
3.XX 版本  last_value 缓存失效

### ISSUE THREAD

**Issue by boruishao** [taosdata/TDengine#18754]
版本号3.0.1.7
12W 数据量的表，表缓存信息如下
![image](https://user-images.githubusercontent.com/33225415/206072520-e47f4095-df6d-499a-b703-0d386c7d1182.png)
执行sql 查超级表很慢
![image](https://user-images.githubusercontent.com/33225415/206072891-6457ef11-5847-4803-bbec-f42c33d5f7bf.png)
单查子表也不快
![image](https://user-images.githubusercontent.com/33225415/206073053-8ec2508b-cb8b-4383-9aaf-7fb12d8e1797.png)
当缓存设置为last_row时，用last_row函数查，缓存是有效的
![image](https://user-images.githubusercontent.com/33225415/206073851-b98dd9b3-470b-4fb8-88a3-6d5c22365643.png)

**Comment by boruishao** [comment]
表删掉重建后，速度能快些，但是用了几天后，速度又变慢了

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
