### ISSUE TITLE
是否有详细的企业版和开源版的区别列表

### ISSUE THREAD

**Issue by 89333367** [taosdata/TDengine#18760]
我能在官网查到下面信息，但是查不到具体细节，例如，我在开源版中执行delete语句，就会出现请使用企业版的提示
![image](https://user-images.githubusercontent.com/20157752/206092310-d860ba63-928b-44d5-9a11-9a788ac8d87a.png)
![lQLPJwjdCZdjDS5DzQZEsDT5mEAB1NJFA4X8y5wAYAA_1604_67](https://user-images.githubusercontent.com/20157752/206092647-05a84eb4-15b9-4d93-9ec1-855716b71ba2.png)

**Comment by yu285** [comment]
删除只有在 2.x中社区版支持。估计你看的是 3.0 的对比

**Comment by 89333367** [comment]
> 删除只有在 2.x中社区版支持。估计你看的是 3.0 的对比

我的意思是想要一个开源版和企业版的详细区别。目前我已经知道了开源版不支持delete命令

![image](https://user-images.githubusercontent.com/20157752/206618774-6ce73ff9-c41f-453c-aa91-a53d88882180.png)

还有其他更详细的对比么？
