### ISSUE TITLE
Used other port not the default(6030) start tdengine docker, got "DB error: Unable to establish connection" when execute  "SHOW CREATE TABLE"

### ISSUE THREAD

**Issue by ningxiner0201** [taosdata/TDengine#18761]
1. 实验环境
   OS：Ubuntu 18.04.6 LTS
   TDengine: TDengine Docker，客户端驱动taosc均使用的最新版本 3.0.1.8
   配置文件：/etc/taos/taos.cfg 为默认配置

2. TDengine Docker部署
将默认6030端口映射到本地的46030端口
![图片](https://user-images.githubusercontent.com/24226706/206090872-cb11d03b-633e-404e-aa2a-1fd459ff0704.png)
容器成功启动，服务运行正常
![图片](https://user-images.githubusercontent.com/24226706/206091424-e5cb6679-85b8-4be3-ada4-16d470808dae.png)

3. 客户端连接数据库
taos -P 46030 指定服务端端口连接数据库；
执行建库、建表、显示建库语句时均正常，在执行 "SHOW CREATE TABLE" 时出现  "DB error: Unable to establish connection"错误，问题可复现。
![图片](https://user-images.githubusercontent.com/24226706/206092331-816752d3-8636-4a57-ac5f-364af40a74bd.png)

4. 对比实验
如果将容器映射端口恢复为6030，不会出现以上问题。

**Comment by yu285** [comment]
麻烦提供下咱们的docker-compose.yml 吧

**Comment by yu285** [comment]
请问您是单机吗

**Comment by craftslab** [comment]
> 麻烦提供下咱们的docker-compose.yml 吧

version: "3"

services:
  td:
    container_name: test-tdengine
    image: tdengine/tdengine:3.0.1.8
    restart: always
    ports:
      - 46030:6030
    volumes:
      - /path/to/tdengine/lib:/var/lib/taos/
      - /path/to/tdengine/log:/var/log/taos/

**Comment by craftslab** [comment]
> 请问您是单机吗

您好，是单机测试

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/

**Comment by yu285** [comment]
如果还有具体的使用问题，可以加微信：a15652223354
