### ISSUE TITLE
无法执行select server_status() 以及 select 1语句

### ISSUE THREAD

**Issue by zlqpzww** [taosdata/TDengine#18773]
**Bug Description**
执行语句select server_status() 和select 1出现错误提示：DB error: Unable to establish connection (0.000135s)，其他show、use、select语句都正常。

**To Reproduce**
未进行尝试

**Expected Behavior**
能正常执行上述语句

**Screenshots**
![image](https://user-images.githubusercontent.com/11763554/206129803-af5533be-844e-42f0-bf2f-85464922011e.png)

**Environment (please complete the following information):**
 - OS: CentOS 7.0
 - Memory:32GiB
 - CPU:Intel(R) Xeon(R) Gold 5218R CPU @ 2.10GHz x 16 cores
 - VM: VMware
 - current Disk Space: total 9.7T, used 2.1T
 - TDengine Version: 2.6.0.6

**Additional Context**
在生产环境突然出现，不知原因，没有尝试过如何复现

**Comment by zlqpzww** [comment]
![image](https://user-images.githubusercontent.com/11763554/206132339-a79d6b05-1950-4548-8a3b-08300b3e70c1.png)
# Additional Context
发现集群的一个dnode下线了，不知是否和这个原因有关？

**Comment by yu285** [comment]
可以加微信 a15652223354 做下具体排查
