### ISSUE TITLE
DB error: Table does not exist (0.000430s)

### ISSUE THREAD

**Issue by biao-lvwan** [taosdata/TDengine#18770]
New table ct_ type_ 6386f9e641c85a0045e5e570_ 1fn79fYnmw0_ dbiotworksGW_ 93 But query DB error: Table does not exist (0.000430s)
![image](https://user-images.githubusercontent.com/66588660/206123046-cba12a25-1f9c-4c5a-9c92-f604c84e58da.png)

**Comment by yu285** [comment]
表名两侧加上反引号
