### ISSUE TITLE
TDEngine continuous query not worked 

### ISSUE THREAD

**Issue by sausers** [taosdata/TDengine#18776]
TDEngine版本：2.6
创建一个连续查询：
 create table if not exists basic_data.avg2112_X3 as select avg(value) from basic_data.st2112_nc where template_tag='X3' interval(10m) sliding(10m);

![image](https://user-images.githubusercontent.com/94833110/206147909-5a444c62-ff6c-4df1-9188-26aa20ace143.png)
1）、查看此连续查询时 created time 显示错误
2）、第一次创建数据插入表中成功，之后不会按照时间的推移自动生成新数据

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/

如果还有具体的使用问题，可以加微信：a15652223354
