### ISSUE TITLE
how to resolve TDengine log oversize ?  

### ISSUE THREAD

**Issue by redgreat** [taosdata/TDengine#18785]
## 数据库版本3.0.13 三节点集群版

![图片](https://user-images.githubusercontent.com/1754926/206184469-f6b46b96-bf8d-4c74-968c-1334ef475a19.png)

## 操作系统
阿里云 CentOS7

![图片](https://user-images.githubusercontent.com/1754926/206183730-bff42397-71f2-40c5-86b2-d0f69243cc62.png)

## taos.cfg 参数配置

![图片](https://user-images.githubusercontent.com/1754926/206182505-c7689ffd-dd79-4f3d-b213-237b1beb9cb2.png)

![图片](https://user-images.githubusercontent.com/1754926/206182537-8d3af88b-c128-49ed-bc4f-b075bce71478.png)

__现在问题是设置了日志级别131，但是文件里带着大量的类似INFO的信息，如图：__

![图片](https://user-images.githubusercontent.com/1754926/206183293-571d0cb5-649a-48ca-b42d-3b3a46b11334.png)

![图片](https://user-images.githubusercontent.com/1754926/206183273-3703ce8a-2729-416d-a486-904a93b05d46.png)

正式环境疯狂写日志对数据库本身会有性能影响，还占用部分空间，望早日解决此问题。

**Comment by yu285** [comment]
在 logKeepdays = 0 的情况下,日志只有 0 和 1 两种flag，如 taosdlog.0 ,taosdlog.1 ,交替使用。

因此只需要降低numofLogLines 即可让每个日志大小变小，从而降低空间。

至于性能影响，131级别的日志写入造成性能问题的影响几乎可以忽略不计 。
