### ISSUE TITLE
查询时关于不同时区日期转换问题

### ISSUE THREAD

**Issue by yhy764** [taosdata/TDengine#18796]
![f4a84ae9a6b9b603db32e56fc8599d5](https://user-images.githubusercontent.com/36179694/206340695-07bef66e-d95d-44b4-a9cf-86a722b024d2.png)
您好：
服务器和客户端时区是上海，但是数据库存储的日期是UTC0的日期，我想查询昨天的数据，有什么高效的查询方法吗？

**Comment by yhy764** [comment]
我的思路是用数据库的日期+8小时，得到真实日期

**Comment by yhy764** [comment]
在不改变原数据和数据库配置的前提

**Comment by yhy764** [comment]
有点类似MYSQL中的CONVERT_TZ方法

**Comment by yu285** [comment]
可以使用select ts+8h , 这样的方法。
