### ISSUE TITLE
Write permissions issues after version upgrade

### ISSUE THREAD

**Issue by weifuwan007** [taosdata/TDengine#18797]
**Bug Description**
After upgrading TD from 2.4.0.40 to 2.6.0.32, the client prompts that it does not have the permission to insert data

**To Reproduce**
1. Upgrading TD from 2.4.0.40 to 2.6.0.32
2. Write a JAVA client program to connect to TDengine
3. Execute the insert data statement

**Screenshots**
1、Table creation statement
```
create database db keep 36500 days 7 blocks 6 update 2;
```
2、Table creation statement
```
create stable t_point(data_time timestamp, insert_time timestamp, point_value double) tags(device_id binary(8), point_name binary(16));
```
3、Error message
![image](https://user-images.githubusercontent.com/120071806/206342028-337aca4a-3b40-4293-a173-1080d58a093f.png)

4、The user used
```
root
```

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - 2C 4G
 - TDengine Version [e.g. 2.6.0.32]

**Comment by yu285** [comment]
驱动客户端版本需要保持正确
