### ISSUE TITLE
同一条统计查询语句多次执行统计数量不一致

### ISSUE THREAD

**Issue by wencyGit** [taosdata/TDengine#18792]
- 服务器系统 CentOS 7
- TDengine 单机版
- TDengine 版本 
![image](https://user-images.githubusercontent.com/21151964/206333146-855a3afe-9725-4e1d-aec1-d9c63d46cede.png)

- 查询结果

![image](https://user-images.githubusercontent.com/21151964/206333250-f8accf85-8ca0-4fd0-9e45-edfabf586fcc.png)

- 按理来说应该是有24条数据

**Comment by yu285** [comment]
经排查，不一致原因为，针对该表高频率清空再查询的中间状态。
