### ISSUE TITLE
Where can we download the TDengine client for windows(a .exe file)?

### ISSUE THREAD

**Issue by dingweihao** [taosdata/TDengine#188]
"在Windows 操作系统下 TDengine 提供 32 位和 64 位的 Windows 客户端，客户端 安装
应 用程序 为 exe 文件 运行 该文件 即可 安装， 默认 安装 路径 为 C: TDengine 。 Windows
的客户端可运行在主流的 32/64 位 Windows 平台之上"

**Comment by hjxilinx** [comment]
文档中说的是商业版本，开源版本的windows客户端如果顺利会在最近几天发布。

**Comment by plum-lihui** [comment]
The TDengine client for windows has been released, please download it from www.taosdata.com for trial. Thank you very much!
