### ISSUE TITLE
与 pandas 一起使用的例子跑不起来

### ISSUE THREAD

**Issue by dongdc21450** [taosdata/TDengine#18801]
**Bug Description**
与 pandas 一起使用的例子跑不起来

**To Reproduce**

**import pandas
from sqlalchemy import create_engine

engine = create_engine("taos://root:taosdata@192.168.1.31:6030/test")
df = pandas.read_sql("SELECT * FROM meters", engine)

# print index
print(df.index)
# print data type  of element in ts column
print(type(df.ts[0]))
print(df.head(3))**

**Expected Behavior**
正常打印出结果

**Screenshots**
![image](https://user-images.githubusercontent.com/27759317/206349143-12eac2f6-94e0-4191-8a86-b03909aed3cb.png)

**Environment (please complete the following information):**
版本信息如下
 - OS:  ubuntu22.04
SQLAlchemy      1.4.44
taospy          2.6.8
pandas          1.5.2
Client Version:3.0.1.8
community version: 3.0.1.8 compatible_version: 3.0.0.0

**Comment by sangshuduo** [comment]
taos shell 能连上吗？

**Comment by dongdc21450** [comment]
可以连上, 不用pandas能正常读写数据

**Comment by sunpe** [comment]
`df = pandas.read_sql("SELECT * FROM meters", engine)` 改成 `df = pandas.read_sql("SELECT * FROM test.meters", engine)` 再试一下，查询时需要指定 db name

![image](https://user-images.githubusercontent.com/8380506/206384786-de5eccb6-132d-4fc4-8e1b-c5607e5f7931.png)
