### ISSUE TITLE
query crash in taosd

### ISSUE THREAD

**Issue by Curtion** [taosdata/TDengine#18821]
**Bug Description**
执行```SELECT
    ts `time`,
    last(`00000000`) `data`
FROM iot_platform.st_product_10000
where
ts between now - 30d and now
INTERVAL(1d)
FILL(PREV)``` 后导致崩溃

**Expected Behavior**
SQL有问题不应该导致服务崩溃

**Screenshots**
![微信图片_20221208175403](https://user-images.githubusercontent.com/14846890/206416660-f2cf23e9-5da3-4628-a33e-5a9af5d47a63.png)

**Environment (please complete the following information):**
 - OS: CentOS8.2
 - TDengine Version 3.0.1.8

**Additional Context**
图片中的日志由core文件调试结果。

**Comment by yu285** [comment]
收到，我们处理下

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
