### ISSUE TITLE
Windows taos.exe cli show : Conn is broken

### ISSUE THREAD

**Issue by SaminZou** [taosdata/TDengine#18831]
![image](https://user-images.githubusercontent.com/18454078/206475485-153890ba-4bc9-495c-9499-18a29498c4af.png)

Already configured the file 'C:\TDengine\cfg\taos.cfg' , alert 'firstEp'  / 'fqdn' / 'serverPort'

**Comment by zmlgirl** [comment]
have you upgrade your server version, if is, you should upgrde client version too.

**Comment by SaminZou** [comment]
In the end, it is indeed about version problem. Backward compatibility can be described as a disaster. client / tools / servers **must be consistent!** **must be consistent!** **must be consistent!** Important things are said three times
