### ISSUE TITLE
TD:Version. 3.0.1.7 . We get nothing after executeing that SQL. [INSERT INTO d21001ASD USING meters TAGS 

### ISSUE THREAD

**Issue by zjwisedf** [taosdata/TDengine#18843]
Description:
 TD:Version. 3.0.1.7 . We get nothing after executeing that SQL. [INSERT INTO d21001ASD USING meters TAGS ('California.SanFrancisco', 2) VALUES ('2021-07-13 14:06:32.272', 10.2, 219, 0.32);] ,  condition: the d21001ASD  table is not exist before executing insert into.  but we get all data that have inserted into the table after restarted the TD database service.  Maybe that is bug. now we upgraded to TD version.3.0.1.8, We're watching all next.

**Environment (please complete the following information):**
 - OS: CentOS 7.7.1908 x86_64(Py3.7.9)　
 - Memory, CPU intel , Disk:1TB
 - TDengine Version  3.0.1.7

**Comment by yu285** [comment]
经排查，升级 3.0.1.8 可解决该问题。

做关闭处理
