### ISSUE TITLE
create database failed

### ISSUE THREAD

**Issue by luoluo2001108** [taosdata/TDengine#18840]
Hello:
when create database ,it run failed,
this is the detail information.

taos> create database pows;

DB error: Unable to establish connection While execute transaction (0.367577s)

taos> show transactions \G
   -> ;
*************************** 1.row ***************************
              id: 192
     create_time: 2022-12-09 10:37:16.632
           stage: redoAction
            oper: create-db
              db: pows2
          stable: 
    failed_times: 7
  last_exec_time: 2022-12-09 10:38:32.208
last_action_info: action:4 code:0x111(Action in progress) msgType:create-vnode numOfEps:1 inUse:0 ep:0-tdengine02.taosdata.com:6030 
*************************** 2.row ***************************
              id: 180
     create_time: 2022-12-09 09:45:58.732
           stage: redoAction
            oper: create-db
              db: power
          stable: 
    failed_times: 315
  last_exec_time: 2022-12-09 10:38:32.208
last_action_info: action:4 code:0x111(Action in progress) msgType:create-vnode numOfEps:1 inUse:0 ep:0-tdengine02.taosdata.com:6030 
*************************** 3.row ***************************
              id: 191
     create_time: 2022-12-09 10:35:32.594
           stage: redoAction
            oper: create-db
              db: pows
          stable: 
    failed_times: 18
  last_exec_time: 2022-12-09 10:38:32.208
last_action_info: action:4 code:0x111(Action in progress) msgType:create-vnode numOfEps:1 inUse:0 ep:0-tdengine02.taosdata.com:6030 
Query OK, 3 row(s) in set (0.002060s)

**Comment by yu285** [comment]
经排查，mnode所在节点不能ping通其他两个节点，但是反之可以ping通。

基于目前架构：只要管理节点能接收到heartbeat，就算其他节点收不到heartbeat-rsp ，也不影响 show dnodes的ready状态。

所以show dnodes 显示正常。

恢复网络后现象消失。
