### ISSUE TITLE
Dynamic SQL splicing after integrating Mybatis, no results can be found

### ISSUE THREAD

**Issue by yanwenjiang01** [taosdata/TDengine#1884]
1.使用#{}接收字符串参数，效果如下：Preparing: select *  from history_position_super WHERE xx= ? and xx= ? order by gpstime desc 
==> Parameters: 2(Integer), 565632132(String)
在终端中可以查询出结果，mybatis中查询结果为空。主要问题是String类型出错

**Comment by liuyq-617** [comment]
您把这个拼接的sql打印出来，直接到taos客户端中可以查询到数据吗？

**Comment by yanwenjiang01** [comment]
> 
> 
> 您把这个拼接的sql打印出来，直接到taos客户端中可以查询到数据吗？

可以的，语句在终端可以有结果

**Comment by yanwenjiang01** [comment]
> 
> 
> 您把这个拼接的sql打印出来，直接到taos客户端中可以查询到数据吗？

您好，这个String字符串我开始是以子表中字段查询，结果为空。但是以超级表标签字段进行查询就可以。在终端查询时，以子表字段也可以查出来。这个问题是怎么回事？看官网我没注意到这个问题。

**Comment by liuyq-617** [comment]
您版本号多少
方便把语句和数据贴出来吗？我复现一下看看

**Comment by yanwenjiang01** [comment]
> 
> 
> 您版本号多少
> 方便把语句和数据贴出来吗？我复现一下看看

1.6.5.7
您方便的话加我微信18686110784

**Comment by liuyq-617** [comment]
We have fixed this issue in the latest version and hope to update the latest version.
