### ISSUE TITLE
taosd DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:1

### ISSUE THREAD

**Issue by yzdzb** [taosdata/TDengine#18853]
![QQ截图20221209144538](https://user-images.githubusercontent.com/69287175/206641795-5b136d71-8c16-46ab-a662-4b7cd443397c.png)

taosd报错 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:1

**Comment by yu285** [comment]
经排查为基础配置问题。

**Comment by Syrea7** [comment]
我win10安装完server端. 执行taosd , 也是出现这个问题, 到底怎么解决呢?  一直找不到方法, 另外, 你说是配置问题, 那怎么改. . ?
