### ISSUE TITLE
使用taos-jdbcdriver3.0.0连接taos3.0.1.8错误 setByteArray

### ISSUE THREAD

**Issue by Anrushaoniantourumeng** [taosdata/TDengine#18859]
服务器taos正常启动
![image](https://user-images.githubusercontent.com/75239811/206673043-ce17bfc7-2ed1-4497-9d33-4d5eb2de67f2.png)
当我在本地根据官方文档进行连接测试时
![image](https://user-images.githubusercontent.com/75239811/206673329-edd8f3c7-205b-41d8-860d-26dbc7391856.png)
引入taos-jdbcdriver 3.0.0
执行连接操作异常
![image](https://user-images.githubusercontent.com/75239811/206673596-763ffdb4-718a-42dd-848a-ff3a57ca3fb3.png)
根据文档查询得知TDengine 3.0版本使用taos-jdbcdriver 3.*
![image](https://user-images.githubusercontent.com/75239811/206673723-7f072eba-7d67-4456-8cbf-43dc1c534644.png)
当我更换taos-jdbcdriver 3.0.2后问题依旧存在

**Comment by yu285** [comment]
应该是动态库文件问题，可以手动把 C:\TDengine\driver 下面的taos.dll ,复制到 C:\Windows\System32
