### ISSUE TITLE
taos_stmt_bind_param invoking with error 

### ISSUE THREAD

**Issue by QuYingzhao20200922** [taosdata/TDengine#18851]
**Bug Description**
在TDengine-3.0.1.6~8版本中, 基于Linux环境下, 对TDengine-server-3.0.1.6/examples/c/prepare.c,第266~390行代码进行复用,在此基础之上做二次开发,开发新功能参数绑定模式单行及多行插入行记录,taos_stmt_bind_param, taos_stmt_bind_param_batch, taos_stmt_errstr函数调用报错,/usr/bin/ld: .obj/mainwindow.o: undefined reference to symbol 'taos_stmt_bind_param' //usr/lib64/libtaos.so.1: error adding symbols: DSO missing from command line。这就是动态库报错。
    希望TDengine官方技术开发人员，对上述报错予以核验，尽快修复。另外，请给出在3.0.1.6版本基础之上如何进行参数绑定插入行记录的示例代码。即：更新TDengine-server-3.0.1.6/examples/c/prepare.c第266~390行代码。

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by QuYingzhao20200922** [comment]
恳请官方开发人员尽快解决，谢谢你们！

**Comment by yu285** [comment]
麻烦提供下ldd /usr/bin/taos
ls -l /usr/lib/libtaos.so.1
截图

**Comment by yu285** [comment]
![image](https://user-images.githubusercontent.com/74105241/206636717-eb8e3ad5-5248-46e1-8c2a-8a6b09ff2403.png)

**Comment by yu285** [comment]
可以在main分支测试验证了

**Comment by QuYingzhao20200922** [comment]
> 可以在main分支测试验证了
请问在哪个版本上进行测试？？？？？？？？？？？？

**Comment by gccgdb1234** [comment]
请基于最新的 3.0.2.4 进行验证。

**Comment by yu285** [comment]
暂无回复，做关闭处理
