### ISSUE TITLE
Error in executing taos command on mac m1

### ISSUE THREAD

**Issue by chenquan** [taosdata/TDengine#18889]
**Bug Description**

Error in executing taos command on mac m1.
**To Reproduce**
```
taos
```
output:
```shell
dyld[30005]: Library not loaded: /opt/taos/TDengine/debug/build/lib/libtaos.1.dylib
  Referenced from: <38C566C4-743F-369E-9043-FFA4AC610AC4> /usr/local/taos/bin/taos
  Reason: tried: '/opt/taos/TDengine/debug/build/lib/libtaos.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/taos/TDengine/debug/build/lib/libtaos.1.dylib' (no such file), '/opt/taos/TDengine/debug/build/lib/libtaos.1.dylib' (no such file), '/usr/local/lib/libtaos.1.dylib' (no such file), '/usr/lib/libtaos.1.dylib' (no such file, not in dyld cache)
zsh: abort      taos
```
**Expected Behavior**

**Screenshots**
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/20548053/206944026-be765862-67df-4100-a103-cddbfe44109e.png">

3.0.1.8:
<img width="989" alt="image" src="https://user-images.githubusercontent.com/20548053/207051048-6f3382f3-8819-4803-9326-e6d0f86a8a7c.png">
3.0.2.0:
<img width="953" alt="image" src="https://user-images.githubusercontent.com/20548053/207051326-e97e759c-03eb-47b5-a0c3-e77ffc205b89.png">

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0] mac 13.0.1
 - Memory, CPU, current Disk Space: 32G, m1 pro, 900G+
 - TDengine Version [e.g. 1.6.1.7] 3.0.2.0

**Additional Context**

**Comment by facetosea** [comment]
> **Bug Description**
> 
> Error in executing taos command on mac m1. **To Reproduce** Steps to reproduce the behavior:
> 
> ```
> taos
> ```
> 
> output:
> 
> ```shell
> dyld[30005]: Library not loaded: /opt/taos/TDengine/debug/build/lib/libtaos.1.dylib
>   Referenced from: <38C566C4-743F-369E-9043-FFA4AC610AC4> /usr/local/taos/bin/taos
>   Reason: tried: '/opt/taos/TDengine/debug/build/lib/libtaos.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/taos/TDengine/debug/build/lib/libtaos.1.dylib' (no such file), '/opt/taos/TDengine/debug/build/lib/libtaos.1.dylib' (no such file), '/usr/local/lib/libtaos.1.dylib' (no such file), '/usr/lib/libtaos.1.dylib' (no such file, not in dyld cache)
> zsh: abort      taos
> ```
> 
> **Expected Behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem. <img alt="image" width="1115" src="https://user-images.githubusercontent.com/20548053/206944026-be765862-67df-4100-a103-cddbfe44109e.png">
> 
> 3.0.1.8: <img alt="image" width="989" src="https://user-images.githubusercontent.com/20548053/207051048-6f3382f3-8819-4803-9326-e6d0f86a8a7c.png"> 3.0.2.0: <img alt="image" width="953" src="https://user-images.githubusercontent.com/20548053/207051326-e97e759c-03eb-47b5-a0c3-e77ffc205b89.png">
> 
> **Environment (please complete the following information):**
> 
> * OS: [e.g. CentOS 7.0] mac 13.0.1
> * Memory, CPU, current Disk Space: 32G, m1 pro, 900G+
> * TDengine Version [e.g. 1.6.1.7] 3.0.2.0
> 
> **Additional Context** Add any other context about the problem here.

I downloaded the installation package of mac 3.0.2.0 and reinstalled it once. (package name: TDengine-server-3.0.2.0-macOS-arm64.pkg)
In the "/usr/local/lib" directory, I found the "libtaos.dylib" file. 
After "taosd" starts, "taos" can start and work fine.

The libtaos.dylib file is like this:
```
lrwxr-xr-x   1 root  wheel       66 12 12 20:03 libtaos.1.dylib -> /opt/homebrew/Cellar/tdengine/3.0.2.0/driver/libtaos.3.0.2.0.dylib
lrwxr-xr-x   1 root  wheel       30 12 12 20:03 libtaos.dylib -> /usr/local/lib/libtaos.1.dylib
lrwxr-xr-x   1 root  wheel       60 12 12 20:03 libtaosws.dylib -> /opt/homebrew/Cellar/tdengine/3.0.2.0/driver/libtaosws.dylib
```

Can you try again, maybe it has something to do with permissions, but I'm not sure.
