### ISSUE TITLE
二进制部署3.0.2.0集群之后，dnode和mnode状态都正常，但是日志报错MND dnode:2, in offline state

### ISSUE THREAD

**Issue by wanghaibo-person** [taosdata/TDengine#18887]
部署方式：二进制部署，三节点集群
版本：3.0.2.0
目前状态：
leader节点和follower节点状态都显示正常
![image](https://user-images.githubusercontent.com/46038902/206909640-2fd62b0e-44b0-4a5e-8a12-65d9519671a1.png)
但是查看主节点middleware-prod-1日志/var/log/taosdlog.0 有报错如下：
![image](https://user-images.githubusercontent.com/46038902/206909732-cb0dbf4e-bd33-4258-bd75-d6e8be0968a7.png)
follower第一个节点middleware-prod-2日志/var/log/taosdlog.0 有报错如下：
![image](https://user-images.githubusercontent.com/46038902/206909807-2cc5b0e2-2157-4c8a-b5a8-6ac585c40eb7.png)
follower第二个节点middleware-prod-3日志/var/log/taosdlog.0 有报错如下：
![image](https://user-images.githubusercontent.com/46038902/206909860-355952ef-7738-45b5-97dd-2c85e89f3483.png)
目前是刚搭建完成的状态，求教一下这样的状态是否有问题~~~~

**Comment by yu285** [comment]
应该有点问题，可以加我微信 a15652223354 远程排查一下。

**Comment by wanghaibo-person** [comment]
> 应该有点问题，可以加我微信 a15652223354 远程排查一下。

好的 已添加您

**Comment by yu285** [comment]
这是一个不影响使用的问题，我们会在 3021 修复。

不应该在 follower 节点做这个检查。
