### ISSUE TITLE
One DNode offline, could not kill pid or shutdown

### ISSUE THREAD

**Issue by msincenselee** [taosdata/TDengine#18890]
taos> show dnodes;
   id   |           end_point            | vnodes | cores  |   status   | role  |       create_time       |      offline reason      |
======================================================================================================================================
      1 | hadoop206:6030                 |     13 |     24 | ready      | any   | 2022-09-01 15:34:21.959 |                          |
      2 | hadoop207:6030                 |     17 |     24 | offline    | any   | 2022-09-02 09:59:26.479 | status msg timeout       |
      3 | hadoop205:6030                 |     18 |     24 | ready      | any   | 2022-09-02 10:05:30.058 |                          |
      4 | hadoop211:6030                 |     13 |     24 | offline    | any   | 2022-09-02 10:19:36.139 | status msg timeout       |
Query OK, 4 row(s) in set (0.001850s)

one dnode (hadoop211) show offline, when we kill the pid, still exist.

[root@hadoop211 taos]# ps -ef|grep taosd
root     23889  5904  0 23:23 pts/1    00:00:00 grep --color=auto taosd
root     29936     1 30 11月16 ?      7-21:17:11 /usr/bin/taosd
[root@hadoop211 taos]# kill 29936
[root@hadoop211 taos]# ps -ef|grep taosd
root     24867  5904  0 23:24 pts/1    00:00:00 grep --color=auto taosd
root     29936     1 30 11月16 ?      7-21:17:54 /usr/bin/taosd

how can I make the hadoop211 from offline to ready ?

**Comment by yu285** [comment]
kill again the service reboot normally .
