### ISSUE TITLE
k8s部署tdengine失败

### ISSUE THREAD

**Issue by ingla9988** [taosdata/TDengine#18903]
参考这个文档：https://taosdata.github.io/TDengine-Operator/zh/index.html   在k8s部署tdengine  
k8s版本：1.13
tdengine版本：3.0.1.8

启动第一个pod就报错了

[root@k8stest new]$ kubectl get pod -owide -n test1212
NAME         READY   STATUS             RESTARTS   AGE   IP               NODE    NOMINATED NODE   READINESS GATES
tdengine-0   0/1     CrashLoopBackOff   13         44m   172.28.221.185   k8stest   <none>           <none>

通过命令查看日志  kubectl logs  tdengine-0  -n test1212
报错信息如下：

12/12 15:55:57.944727 00000056 UTL default      os version               #3 SMP Fri Dec 18 14:53:46 CST 2020
12/12 15:55:57.944734 00000056 UTL default      os machine               x86_64
12/12 15:55:57.944740 00000056 UTL default      version                  3.0.1.8
12/12 15:55:57.944746 00000056 UTL default      compatible_version       3.0.0.0
12/12 15:55:57.944752 00000056 UTL default      gitinfo                  9e47ea605620acab27e84e6280a91db79b744322
12/12 15:55:57.944759 00000056 UTL default      buildinfo                Built at 2022-11-24 18:16
12/12 15:55:57.944764 00000056 UTL =================================================================
12/12 15:55:57.948938 00000056 UTL ERROR failed to get ip from fqdn:tdengine-0.taosd.test1212.svc.cluster.local since Success, dnode can not be initialized
12/12 15:55:57.950765 00000056 DND ERROR failed to start since read config error

请问这个一般是什么原因呢？谢谢

**Comment by ingla9988** [comment]
镜像版本改成：tdengine:2.6.0.32  可以部署成功，是3.0的版本的yaml文件哪里需要修改吗？

**Comment by ingla9988** [comment]
镜像版本改成：tdengine:2.6.0.32 可以部署成功，
所以3.0的版本的yaml文件哪里需要修改吗？

**Comment by sangshuduo** [comment]
https://github.com/taosdata/TDengine-Operator/tree/3.0

**Comment by ingla9988** [comment]
> 

参考了你发的文档，我尝试用helm安装3.0的版本也是一样的报错

12/13 11:14:56.657864 00000074 UTL ERROR failed to get ip from fqdn:tdengine-0.tdengine.default.svc.cluster.local since Success, dnode can not be initialized
12/13 11:14:56.657887 00000074 DND ERROR failed to start since read config error

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
