### ISSUE TITLE
HOWTO restore v-group  status

### ISSUE THREAD

**Issue by msincenselee** [taosdata/TDengine#18919]
Our vnodes status:
taos> show dnodes;
   id   |           end_point            | vnodes | cores  |   status   | role  |       create_time       |      offline reason      |
======================================================================================================================================
      1 | hadoop206:6030                 |     13 |     24 | ready      | any   | 2022-09-01 15:34:21.959 |                          |
      2 | hadoop207:6030                 |     17 |     24 | offline    | any   | 2022-09-02 09:59:26.479 | status msg timeout       |
      3 | hadoop205:6030                 |     18 |     24 | ready      | any   | 2022-09-02 10:05:30.058 |                          |
      4 | hadoop211:6030                 |     13 |     24 | ready      | any   | 2022-09-02 10:19:36.139 |                          |

and the v-group status for one database:
taos> show vgroups;
    vgId     |   tables    |  status  |   onlines   | v1_dnode | v1_status | v2_dnode | v2_status | v3_dnode | v3_status | compacting  |
========================================================================================================================================
           3 |         893 | ready    |           0 |        3 | unsynced  |        4 | unsynced  |        2 | offline   |           0 |
           4 |         936 | ready    |           2 |        1 | leader    |        2 | offline   |        3 | follower  |           0 |
           5 |        1000 | ready    |           0 |        4 | unsynced  |        2 | offline   |        3 | unsynced  |           0 |
           6 |         977 | ready    |           2 |        3 | leader    |        2 | offline   |        1 | follower  |           0 |
           7 |         999 | ready    |           0 |        2 | offline   |        4 | unsynced  |        3 | unsynced  |           0 |
           8 |         620 | ready    |           2 |        1 | leader    |        2 | offline   |        3 | follower  |           0 |
           9 |         899 | ready    |           0 |        4 | unsynced  |        2 | offline   |        3 | unsynced  |           0 |
Query OK, 7 row(s) in set (0.000953s)

when insert data into current database, showed: database is not ready.
How to restore the vgroup status during the situation hadoop207 keep offline?

**Comment by yu285** [comment]
in 2.x version , you have to bring up all the dnode  to Ready states  to make sure your vnodes  can be chose as  new master/leader to provide service to users .
