### ISSUE TITLE
TDengineGUL

### ISSUE THREAD

**Issue by 1454850554** [taosdata/TDengine#18926]
TDengineGUL 端口和ip都对无法连接

![1670913651379](https://user-images.githubusercontent.com/104713222/207244859-c225fcb1-764c-4627-a298-44236b708850.jpg)

本地可以通
![2f286d5cc5e5c0dd581d8ec21f4f407](https://user-images.githubusercontent.com/104713222/207244892-1bdb8bf2-e7ff-47c8-b071-d1037a27862a.png)

**Comment by robinxie84** [comment]
server taosadapter running?
