### ISSUE TITLE
show stables with error with  python connector

### ISSUE THREAD

**Issue by SalYelBirch** [taosdata/TDengine#18924]
我现在在两台Linux 服务器（一台云端、一台本地）上部署了TDengine 3.0.1.8 版本的docker 并打开了对应的服务器端口
在一台windows 部署了相同版本的TDengine 3.0.1.8 客户端
现在借助 python 的tao连接库执行如下操作：
1、获取服务器客户端版本并校验一致性
2、清空已有的订阅topic 并 drop 已存在的测试数据库
3、新建测试数据库并初始化超级表
4、展示所有超级表（`show stables;`）
5、插入测试数据及测试订阅主题
6、查询表内容

带有公网IP的云服务器上，可以成功执行 命令4
但切换到本地的服务器之后，命令执行到 4 便报错退出

本地服务器移除命令4 的代码后后续操作也可以正常执行

**Comment by SalYelBirch** [comment]
![image](https://user-images.githubusercontent.com/60539707/207218932-d300ea44-35d2-4ae5-b43e-a3957a7d7e18.png)
此处为云服务器的执行结果

**Comment by SalYelBirch** [comment]
请问这种报错是如何产生的，该如何避免此类情况以确保程序稳定运行

**Comment by yu285** [comment]
既然是连接问题，可能需要远程调试一下，您加我微信吧。a15652223354
