### ISSUE TITLE
golang client  指针错误

### ISSUE THREAD

**Issue by lhwcd** [taosdata/TDengine#18937]
代码如下：
![截屏2022-12-13 22 37 22](https://user-images.githubusercontent.com/40284010/207364001-ccbef8fc-33a6-43a8-8517-1fa20b1fcbb4.png)
![截屏2022-12-13 22 37 51](https://user-images.githubusercontent.com/40284010/207364029-ae3c89a9-b9ce-488a-8759-18c4606b55fa.png)

**Environment (please complete the following information):**
 - OS: [Ubuntu 22.04 LTS]
 - Memory, CPU, current Disk Space
 - TDengine Version [version: 3.0.1.6]
运行结果如下：
![截屏2022-12-13 21 19 25](https://user-images.githubusercontent.com/40284010/207332869-86c59335-df6b-4373-a602-4a15fb5ce30d.png)
![截屏2022-12-13 21 19 12](https://user-images.githubusercontent.com/40284010/207332956-f8bfe73c-5dcb-4556-88dd-693e945a7a49.png)

**Additional Context**

**Comment by huskar-t** [comment]
@lhwcd 请提供 driver-go 版本

**Comment by lhwcd** [comment]
<img width="734" alt="截屏2022-12-14 14 08 44" src="https://user-images.githubusercontent.com/40284010/207519526-bd159567-6bda-48fc-b0c7-98a953a921d2.png">
是这个版本吗？

**Comment by lhwcd** [comment]
<img width="625" alt="截屏2022-12-14 14 37 22" src="https://user-images.githubusercontent.com/40284010/207524094-f78db31c-d4cc-4508-af98-062c50dbd40d.png">
这个版本

**Comment by lhwcd** [comment]
<img width="1308" alt="截屏2022-12-14 15 11 24" src="https://user-images.githubusercontent.com/40284010/207529601-0dec7e4a-4c52-403c-a3db-f0fdd132227a.png">
gh'c刚才又崩溃了，这个会不会有帮助

**Comment by sunpe** [comment]
@lhwcd go是什么版本

**Comment by lhwcd** [comment]
<img width="635" alt="截屏2022-12-14 17 19 51" src="https://user-images.githubusercontent.com/40284010/207556231-68ae0d63-8041-410f-912d-eced783740dd.png">

**Comment by sunpe** [comment]
问题还在排查中，af包是底层api，不建议使用af包执行sql查询，推荐使用taossql api

**Comment by huskar-t** [comment]
@lhwcd 
af.Open 返回的 conn 会在多个 goroutine 之间并发使用吗

**Comment by huskar-t** [comment]
@lhwcd 请使用 github.com/taosdata/driver-go/v3 v3.0.4 测试问题是否还存在

**Comment by yu285** [comment]
暂无回复，做关闭处理
