### ISSUE TITLE
从源码编译各种报错

### ISSUE THREAD

**Issue by zzboy** [taosdata/TDengine#1894]
拉的develop分支，cmake是3.12.1版本，gcc是4.9.2，报错如下：
/TDengine/src/common/inc/tdataformat.h:117:7: error: implicit declaration of function ‘POINTER_SHIFT’ [-Werror=implicit-function-declaration]
       return POINTER_SHIFT(row, *(VarDataOffsetT *)POINTER_SHIFT(row, offset));
       ^
/TDengine/src/common/inc/tdataformat.h:117:34: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
       return POINTER_SHIFT(row, *(VarDataOffsetT *)POINTER_SHIFT(row, offset));
                                  ^
/TDengine/src/common/inc/tdataformat.h:117:7: error: return makes pointer from integer without a cast [-Werror]
       return POINTER_SHIFT(row, *(VarDataOffsetT *)POINTER_SHIFT(row, offset));
       ^
/TDengine/src/common/inc/tdataformat.h:119:7: error: return makes pointer from integer without a cast [-Werror]
       return POINTER_SHIFT(row, offset);
       ^
/TDengine/src/common/inc/tdataformat.h: In function ‘tdGetColDataOfRow’:
/TDengine/src/common/inc/tdataformat.h:150:7: error: return makes pointer from integer without a cast [-Werror]
       return POINTER_SHIFT(pCol->pData, pCol->dataOff[row]);
       ^
/TDengine/src/common/inc/tdataformat.h:154:7: error: return makes pointer from integer without a cast [-Werror]
       return POINTER_SHIFT(pCol->pData, TYPE_BYTES[pCol->type] * row);
       ^
In file included from /TDengine/src/inc/tlog.h:26:0,
                 from /TDengine/src/common/inc/tulog.h:23,
                 from /TDengine/src/os/linux/src/linuxEnv.c:19:
/TDengine/src/inc/tglobalcfg.h: At top level:
/TDengine/src/inc/tglobalcfg.h:95:14: error: conflicting types for ‘tsAsyncLog’
 extern short tsAsyncLog;
              ^
In file included from /TDengine/src/os/linux/src/linuxEnv.c:18:0:
/TDengine/src/common/inc/tglobal.h:140:16: note: previous declaration of ‘tsAsyncLog’ was here
 extern int32_t tsAsyncLog;
                ^
In file included from /TDengine/src/inc/tlog.h:26:0,
                 from /TDengine/src/common/inc/tulog.h:23,
                 from /TDengine/src/os/linux/src/linuxEnv.c:19:
/TDengine/src/inc/tglobalcfg.h:168:17: error: conflicting types for ‘tmrDebugFlag’

请问怎么从源码编译？

**Comment by Aries-Lee1991** [comment]
您好，是编译器版本太低了，您这边是否可以升级到高一点的版本呢？

**Comment by zzboy** [comment]
> 您好，是编译器版本太低了，您这边是否可以升级到高一点的版本呢？

要升级到什么版本？

**Comment by Aries-Lee1991** [comment]
> > 您好，是编译器版本太低了，您这边是否可以升级到高一点的版本呢？
> 
> 要升级到什么版本？

建议使用7。

**Comment by zzboy** [comment]
> > > 您好，是编译器版本太低了，您这边是否可以升级到高一点的版本呢？
> > 
> > 
> > 要升级到什么版本？
> 
> 建议使用7。

-- The C compiler identification is GNU 7.1.0
-- The CXX compiler identification is GNU 7.1.0

TDengine/src/os/linux/src/linuxEnv.c:18:10: fatal error: tglobal.h: No such file or directory
 #include "tglobal.h"
          ^~~~~~~~~~~
compilation terminated.

还是同样的报错

**Comment by Aries-Lee1991** [comment]
能描述下你的编译步骤吗？

**Comment by zzboy** [comment]
mkdir build
cd build
cmake .. && cmake --build .

**Comment by zzboy** [comment]
> 能描述下你的编译步骤吗？

mkdir build
cd build
cmake .. && cmake --build .

**Comment by Aries-Lee1991** [comment]
你好，刚试了一下，我们用这个步骤，编译最新的 develop 分支，都没问题。

**Comment by zzboy** [comment]
> 你好，刚试了一下，我们用这个步骤，编译最新的 develop 分支，都没问题。

那就奇怪了啊 还可能是什么问题呢

**Comment by zzboy** [comment]
> > 你好，刚试了一下，我们用这个步骤，编译最新的 develop 分支，都没问题。
> 
> 那就奇怪了啊 还可能是什么问题呢

master 分支不编译tsdb、wal这些核心的模块吗？

**Comment by zzboy** [comment]
diff --git a/src/client/src/tscSQLParser.c b/src/client/src/tscSQLParser.c
index a81ad19..1e8ac92 100644
--- a/src/client/src/tscSQLParser.c
+++ b/src/client/src/tscSQLParser.c
@@ -13,7 +13,7 @@
  * along with this program. If not, see <http://www.gnu.org/licenses/>.
  */
 
-#define _XOPEN_SOURCE
+#define _XOPEN_SOURCE 500
 #define _DEFAULT_SOURCE
 
 #include "os.h"
diff --git a/src/kit/shell/src/shellEngine.c b/src/kit/shell/src/shellEngine.c
index 6947537..39e82f7 100644
--- a/src/kit/shell/src/shellEngine.c
+++ b/src/kit/shell/src/shellEngine.c
@@ -13,8 +13,9 @@
  * along with this program. If not, see <http://www.gnu.org/licenses/>.
  */
 
-#define _XOPEN_SOURCE
+#define _XOPEN_SOURCE 500
 #define _DEFAULT_SOURCE
+#define _POSIX_C_SOURCE 200809L
 
 #include "os.h"
 #include "shell.h"
@@ -49,7 +50,7 @@ TAOS *shellInit(struct arguments *args) {
   }
 
   if (args->is_use_passwd) {
-    if (args->password == NULL) args->password = getpass("Enter password: ");
+    //if (args->password == NULL) args->password = getpass("Enter password: ");
   } else {
     args->password = tsDefaultPass;
   }
diff --git a/src/kit/shell/src/shellImport.c b/src/kit/shell/src/shellImport.c
index b29b963..d789c18 100644
--- a/src/kit/shell/src/shellImport.c
+++ b/src/kit/shell/src/shellImport.c
@@ -15,6 +15,7 @@
 
 #define _XOPEN_SOURCE
 #define _DEFAULT_SOURCE
+#define _POSIX_C_SOURCE 200809L
 
 #include "os.h"
 #include "shell.h"
diff --git a/src/util/src/ttime.c b/src/util/src/ttime.c
index d34bf0e..20a3338 100644
--- a/src/util/src/ttime.c
+++ b/src/util/src/ttime.c
@@ -15,6 +15,8 @@
 
 #define _XOPEN_SOURCE
 #define _DEFAULT_SOURCE
+#define _SVID_SOURCE
+#define _BSD_SOURCE
 
 #include <errno.h>
 #include <stdio.h>
@@ -23,7 +25,6 @@
 #include "taosdef.h"
 #include "ttime.h"
 #include "tutil.h"
-
 /*
  * mktime64 - Converts date to seconds.
  * Converts Gregorian date to seconds since 1970-01-01 00:00:00.

**Comment by zzboy** [comment]
要改一些系统头文件的参数，diff在上面，看看是否需要merge到你们代码里面
