### ISSUE TITLE
Ubuntu20.04编译master 代码报错

### ISSUE THREAD

**Issue by freekingxx** [taosdata/TDengine#18945]
**Bug Description**
Ubuntu20.04 介绍编译TDEngine，最后出现libiconv undefine链接报错
![image](https://user-images.githubusercontent.com/21023693/207538776-c926bdb5-0ff2-478d-8355-17b957eb8f0a.png)

**To Reproduce**
1. sudo apt-get install -y gcc cmake build-essential git libssl-dev
2. sudo apt install build-essential libjansson-dev libsnappy-dev liblzma-dev libz-dev zlib1g pkg-config
3. 通过DownLoadZIP包的方法，下载unzip解压后，运行build.sh脚本

**Expected Behavior**

**Screenshots**
截图如上

**Environment (please complete the following information):**
 - 操作系统版本: 
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal

 - 8C8G, 磁盘充足
 - TDengine Version： download zip包， master分支当前最新

**Additional Context**

**Comment by sangshuduo** [comment]
稳定分支目前是 main，开发分支是 3.0，不要编 master

**Comment by freekingxx** [comment]
你好，使用稳定分支main编译，也是这样。 本机已经安装过libiconv了

**Comment by freekingxx** [comment]
![6a0e123e4b9f5691cf553043b43ecf7](https://user-images.githubusercontent.com/21023693/210314575-3d971419-257d-4445-9062-85075a96b07e.png)

**Comment by freekingxx** [comment]
@sangshuduo  上面的问题，麻烦有空再看下

**Comment by sangshuduo** [comment]
我试了没问题，应该也不需要自己装 libiconv

![image](https://user-images.githubusercontent.com/825729/210316180-f4ffcd89-e4d0-421e-bd26-240df43f09db.png)
