### ISSUE TITLE
在taos.cfg中配置smlChildTableName=tname后，尝试自带案例Schemaless功能性测试写入不生效

### ISSUE THREAD

**Issue by YiFlower** [taosdata/TDengine#18947]
我根据官网的案例，在Server端的配置文件中，新增了指定配置：
![2e993cc028e73c57180f0370bb97f27](https://user-images.githubusercontent.com/70850418/207539916-3170473c-c77f-4b6a-a62e-4a79272c60c7.png)
![cd63b1fd5c9de3c6886e31146e81f9e](https://user-images.githubusercontent.com/70850418/207540254-c3fc7e4e-ecc2-4c89-8a3d-30c00371ffa0.png)

随后，我根据官网的提示，将Java Schemaless写入代码copy到本地，并成功运行（无输出）
但数据库显示的表名和我的预期不一样，这是为什么呢？
![image](https://user-images.githubusercontent.com/70850418/207540365-737b64a3-79d1-423b-834a-bebeb52ad95c.png)

**Comment by zhou-hao** [comment]
请问咋解决的？ @YiFlower
