### ISSUE TITLE
win7环境，运行 Tdengine-server，Assertion failed,Expression:numOfFields > 0 后，异常关闭

### ISSUE THREAD

**Issue by zeweilin** [taosdata/TDengine#18946]
问题描述：
win7 分别运行 3.0.1.1 、3.0.1.8 Tdengine-Server，运行一段时间，都出现了一样的报错异常，然后直接关闭。

问题截图：
![image](https://user-images.githubusercontent.com/42395779/207539628-046d058e-d596-4049-81e6-17d0548b92ad.png)

运行环境：
 - win7
 - Tdengine-Server version 3.0.1.1/3.0.1.8

**Comment by anyucheng2568** [comment]
更新到 3020后问题解决。
