### ISSUE TITLE
TIMESTAMP 类型字段格式化

### ISSUE THREAD

**Issue by fangquan456** [taosdata/TDengine#18949]
Version:3.0.1.8，请问字段ts是TIMESTAMP 类型，有没有类似关系型数据库函数类似to_char(ts,'MM/DD') 来格式化日期，转成只带月/日的字符串，类似 12/14

**Comment by mojerro** [comment]
@fangquan456 你可以看看[函数文档](https://docs.taosdata.com/taos-sql/function/#to_iso8601)
估计只能转成标准ISO字符串，剩下的还是得自己处理

**Comment by xjy2010** [comment]
我查询出来的是 2022-12-16 14:36:21.673 这样，javaJDBC连接的方式

**Comment by mojerro** [comment]
那这就是正常格式了，而且这格式你完全可以在java里直接解析。或者可以用 `SUBSTR` 函数截取字符串这么处理

**Comment by xjy2010** [comment]
Mysql 里有一个DATE_FORMAT()函数，可以直接转换成指定的字符串格式，如果查询出来的结果是这样的格式，我还需要遍历出所有数据再进行截取，这是很耗性能的，有没有一个函数可以指定格式将日期输出

**Comment by yu285** [comment]
现在已经支持to_char
