### ISSUE TITLE
查询count SQL，提示TDengine ERROR (80000102): Out of Memory

### ISSUE THREAD

**Issue by zhangruijie-star** [taosdata/TDengine#18959]
**Bug Description**
截图-1 SQL，执行查询成功，并返回24行数据；
截图-2 SQL，在截图-1的SQL外层，查询count，SQL查询报错，提示TDengine ERROR (80000102): Out of Memory

**Environment**
 - OS: [macos Ventura 13.0.1]
 - CPU: [Apple M1 Pro]
 - TDengine Version [3.0.1.7]

**Screenshots**
![41671009821_ pic_hd](https://user-images.githubusercontent.com/57881345/207762909-f29b0f86-6dd5-44b6-bed7-757c3b7dfb2f.jpg)
![61671009821_ pic](https://user-images.githubusercontent.com/57881345/207762932-f87e8c7f-0d75-4f6b-87d2-9730f6143b73.jpg)

**Comment by xjy2010** [comment]
Out of Memory ，有点像内存溢出呀

**Comment by yu285** [comment]
3.0.2.1 已经修复
