### ISSUE TITLE
the data not exist is showed up

### ISSUE THREAD

**Issue by 295068421** [taosdata/TDengine#18956]
问题点：
![image](https://user-images.githubusercontent.com/13161609/207618003-195e3ef0-6dd4-4848-a3ae-ad16ff444d05.png)

数据库最后时间数据：
![image](https://user-images.githubusercontent.com/13161609/207618337-e57b00e7-d7ac-48e3-970b-cf0097a6cc7e.png)

操作系统：CenterOS

taos 信息：
![image](https://user-images.githubusercontent.com/13161609/207618638-962f369d-69ae-45f0-a354-944fabc99b4b.png)

**Comment by yu285** [comment]
可以加微信  a15652223354 远程看下吗
