### ISSUE TITLE
为什么TDengine-server-3.0.1.5版创建多个mnode出错？

### ISSUE THREAD

**Issue by kaiwong** [taosdata/TDengine#18961]
问题现象：
3台机3个节点，装好后运行正常，这时候只有一个mnode；此时在控制台执行CREATE MNODE ON DNODE dnode_id在第二个数据节点上创建多一个mnode集群时控制台立刻没反应，然后报错，重启后仍然报错，集群不能使用。
出错部分日志如下：
12/15 15:58:15.874121 03124669 MND mnode index:0, ep:testserver-s01:6030
12/15 15:58:15.875347 03124665 MND msg:0x7f7a2c007f30, type:status failed to process since Sync not leader, mnode restored:0 stopped:0, sync restored:0 role:candidate, redirect numOfEps:1 inUse:0
12/15 15:58:15.875358 03124665 MND mnode index:0, ep:testserver-s01:6030
12/15 15:58:15.888560 03124667 MND msg:0x7f7a6000a150, type:status failed to process since Sync not leader, mnode restored:0 stopped:0, sync restored:0 role:candidate, redirect numOfEps:1 inUse:0
12/15 15:58:15.888567 03124667 MND mnode index:0, ep:testserver-s01:6030
12/15 15:58:15.889482 03124666 MND msg:0x7f7a3c009eb0, type:status failed to process since Sync not leader, mnode restored:0 stopped:0, sync restored:0 role:candidate, redirect numOfEps:1 inUse:0
12/15 15:58:15.889489 03124666 MND mnode index:0, ep:testserver-s01:6030
12/15 15:58:15.890115 03124681 DND index:0, mnode ep:testserver-s01:6030
12/15 15:58:15.891036 03124669 MND msg:0x7f7a2c007f30, type:status failed to process since Sync not leader, mnode restored:0 stopped:0, sync restored:0 role:candidate, redirect numOfEps:1 inUse:0
12/15 15:58:15.891045 03124669 MND mnode index:0, ep:testserver-s01:6030
12/15 15:58:15.903859 03124665 MND msg:0x7f7a6000a150, type:status failed to process since Sync not leader, mnode restored:0 stopped:0, sync restored:0 role:candidate, redirect numOfEps:1 inUse:0
12/15 15:58:15.903865 03124665 MND mnode index:0, ep:testserver-s01:6030
12/15 15:58:15.907547 03124667 MND msg:0x7f7a2c007f30, type:status failed to process since Sync not leader, mnode restored:0 stopped:0, sync restored:0 role:candidate, redirect numOfEps:1 inUse:0
12/15 15:58:15.907552 03124667 MND mnode index:0, ep:testserver-s01:6030
12/15 15:58:15.919190 03124666 MND msg:0x7f7a6000a150, type:status failed to process since Sync not leader, mnode restored:0 stopped:0, sync restored:0 role:candidate, redirect numOfEps:1 inUse:0
12/15 15:58:15.919199 03124666 MND mnode index:0, ep:testserver-s01:6030
12/15 15:58:15.925288 03124669 MND msg:0x7f7a2c007f30, type:status failed to process since Sync not leader, mnode restored:0 stopped:0, sync restored:0 role:candidate, redirect numOfEps:1 inUse:0
12/15 15:58:15.925300 03124669 MND mnode index:0, ep:testserver-s01:6030
12/15 15:58:15.934485 03124665 MND msg:0x7f7a6000a150, type:status failed to process since Sync not leader, mnode restored:0 stopped:0, sync restored:0 role:candidate, redirect numOfEps:1 inUse:0
12/15 15:58:15.934496 03124665 MND mnode index:0, ep:testserver-s01:6030
12/15 15:58:15.940958 03124667 MND msg:0x7f7a2c007f30, type:status failed to process since Sync not leader, mnode restored:0 stopped:0, sync restored:0 role:candidate, redirect numOfEps:1 inUse:0
12/15 15:58:15.940964 03124667 MND mnode index:0, ep:testserver-s01:6030
12/15 15:58:15.949785 03124666 MND msg:0x7f7a6000a150, type:status failed to process since Sync not leader, mnode restored:0 stopped:0, sync restored:0 role:candidate, redirect numOfEps:1 inUse:0
12/15 15:58:15.949791 03124666 MND mnode index:0, ep:testserver-s01:6030
12/15 15:58:15.956554 03124669 MND msg:0x7f7a2c007f30, type:status failed to process since Sync not leader, mnode restored:0 stopped:0, sync restored:0 role:candidate, redirect numOfEps:1 inUse:0
12/15 15:58:15.956564 03124669 MND mnode index:0, ep:testserver-s01:6030
12/15 15:58:15.965047 03124665 MND msg:0x7f7a6000a150, type:status failed to process since Sync not leader, mnode restored:0 stopped:0, sync restored:0 role:candidate, redirect numOfEps:1 inUse:0
12/15 15:58:15.965052 03124665 MND mnode index:0, ep:testserver-s01:6030

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
