### ISSUE TITLE
3.0.2.0版本解决内存泄漏后，CPU占用大幅提升

### ISSUE THREAD

**Issue by mojerro** [taosdata/TDengine#18966]
![image](https://user-images.githubusercontent.com/15071824/207850463-b5d28b8c-0846-4121-b5c5-6677bb65ce6f.png)

如图，12月14日晚上我docker更新了3.0.2.0tdengine镜像，之后CPU占用稳定在60以上

**Comment by yu285** [comment]
可能需要远程排查一下，可以加微信 a15652223354

**Comment by mojerro** [comment]
聚合统计展示算法的问题，默认是max，只是峰值cpu高了一些，影响不大
