### ISSUE TITLE
In these two query result of TDengine, why is the number after the decimal point different?

### ISSUE THREAD

**Issue by like19891202** [taosdata/TDengine#18973]
As you see:

First SQL's result is 457445.014572144 

second one is 457445.000000000

taos>  select time, price, vol, price*vol*100  as amount from sh600096 where time > '2022-12-15' limit 1;
          time           |        price         |     vol     |          amount           |
===========================================================================================

 2022-12-15 09:30:24.000 |             23.95000 |         191 |          457445.014572144 |
Query OK, 10 row(s) in set (0.071000s)

taos> select 23.95*191*100  as amount;
          amount           |
============================
          457445.000000000 |
Query OK, 1 row(s) in set (0.008000s)

below is my create table statement :

CREATE STABLE `st_transaction_data` (`time` TIMESTAMP, `price` FLOAT, `vol` INT, `buyorsell` TINYINT) TAGS (`market` TINYINT)

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
