### ISSUE TITLE
want to know about performance of avg 

### ISSUE THREAD

**Issue by liangfutang** [taosdata/TDengine#18970]
场景：
大屏展示，需要统计设备坐标(表中的xyz字段)的平均值，现在上报的数据还不是很多，担心后面数据多了会查询慢，我们有的参数是每隔十秒上报的。
问题：
因为是大屏展示嘛，所以可能会用到union all同时查多张表,这种场景下会有效率的影响么

**Comment by yu285** [comment]
taosdemo -n 1000000 -t 10000

select avg()+avg()+avg() from test.meters partition by tbname

可以模拟一下
