### ISSUE TITLE
Taosdump Restore Error

### ISSUE THREAD

**Issue by sytuacmdyh** [taosdata/TDengine#18975]
**Bug Description**
使用Taosdump恢复数据（数据是我用Taosdump刚导出的）时，导入的数量是对的，但是部分值异常。
出现大量错误信息
`ERROR: dumpInAvroDataImpl() LN6783 mix type unknown with int array`

**Screenshots**
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/13233969/208035459-6277de7f-4172-45b6-85cf-a19c97b6cdc6.png">
[taosdump.log](https://github.com/taosdata/TDengine/files/10243149/taosdump.log)

**Environment (please complete the following information):**
 - OS: [docker]
 - TDengine Version [3.0.2.0]

**Comment by yu285** [comment]
taosdump 版本是？

**Comment by sytuacmdyh** [comment]
taosdump version 2.3.2, commit: d55a1f8

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/

如果还有具体的使用问题，可以加微信：a15652223354
