### ISSUE TITLE
DB error: Sync not leader

### ISSUE THREAD

**Issue by JH990624** [taosdata/TDengine#18971]
select count(1) from device;
服务器版本 3.0.2.0
创建数据库指定了Vgroup 就会报 sync not leader 错误   
创建数据库没有 指定 Vgroup 就会报 Unable to establish connection 错误

在 docker 容器内部执行命令 一切正常 
在windows 客户端3.0.2.0 版本 执行命令  会报错

**Comment by yu285** [comment]
您好，是微信群的用户吗？可以加微信 a15652223354 远程一下，做个具体排查

**Comment by yu285** [comment]
您好，有需要可随时联系我，暂做关闭处理。
