### ISSUE TITLE
TDengine超级表的不同子表是怎么分布存储在不同的Vnode/Vgroup下的?

### ISSUE THREAD

**Issue by wangpan-chance** [taosdata/TDengine#18974]
背景：我这边使用的是TDengine2.6版本，三个节点手动部署，创建了一个库默认无副本，创建了一张超级表，600+张子表，发现子表的vgId都相同，并且都是存在相同的Vnode下。

1.是否超级表的数据都存在同一个vnode下？
2.如果超级表不是存在同一vnode下，那么子表是按照什么逻辑分布在不同vnode下的？
3.如果单表(子表)列数多，数据量大，能使得数据均匀分布在不同的vnode/dnode下吗？还是建议拆分列数建表？

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/

如果还有具体的使用问题，可以加微信：a15652223354
