### ISSUE TITLE
写入WAL log异常，导致数据丢失

### ISSUE THREAD

**Issue by Dawnflying** [taosdata/TDengine#18986]
**Bug Description**
WAL log异常报错导致出现数据丢失，同时还出现了节点状态不一致的情况。

**To Reproduce**
批量写入SQL，单词最多400条记录。

**Expected Behavior**
数据正常写入。

**Screenshots**
![07591aa55b20ce7139e00f1138ba052](https://user-images.githubusercontent.com/5460921/208227632-281b7ba3-ce2d-46b8-9af4-fd3718dab47f.png)

![7807a8923d190e179e0da58cac35d64](https://user-images.githubusercontent.com/5460921/208227698-6030db93-eb88-4715-8c67-f58101a5c685.png)

**Environment (please complete the following information):**
 - CentOS 7.0
 - CPU 16c 32g,Disk Space 1.5T SSD
 - TDengine Version [e.g. 2.6.0.30]

**Additional Context**

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/

如果还有具体的使用问题，可以加微信：a15652223354
