### ISSUE TITLE
No errors are reported for continuous queries, and no data is generated in the result table

### ISSUE THREAD

**Issue by wowo404** [taosdata/TDengine#1899]
你好，我在使用连续查询时，碰到这样的情况，创建了一个连续查询，创建成功没有报错，show streams，没有任何问题，能查询到刚刚创建的连续查询记录，过一会再show streams，能看到cycles是有增加的，再查询结果表，结果表数据是0条，被统计的表是一直有实时数据插入的。
版本：community client version:1.6.5.7 community server version:1.6.5.7
下面是我创建相关表及连续查询的sql：
1.被统计的表结构
describe vibration;
                             Field                              |      Type      |  Length   |  Note  |
=======================================================================================================
ts                                                              |TIMESTAMP       |          8|        |
value                                                           |DOUBLE          |          8|        |
monitor_id                                                      |BIGINT          |          8|tag     |
direction                                                       |BINARY          |         10|tag     |
2.创建连续查询的sql
create table statistics_vibration as select avg(value) as avg, count(value) as count, sum(value) as sum from vibration interval(1m);
3.show streams;
          user          |          ip:port:id          |     created time     |      exec time       | time(us)  |              sql               |  cycles   |
===============================================================================================================================================================
_root                   |192.168.17.230:54634:6        | 20-05-13 14:05:12.610| 20-05-13 14:06:00.000|          0|select avg(value) as avg, count |          2|
4.查询结果表
select * from statistics_vibration;
Query OK, 0 row(s) in set (0.001676s)

**Comment by liuyq-617** [comment]
The query is always executed on a specified time window (window size is specified by parameter interval), and this window slides forward while time flows (the sliding period is specified by parameter sliding).

**Comment by wowo404** [comment]
Thank you for your response. what you answer is same as your official document ,could you provide more detail, or point at what's problem in my operation

**Comment by liuyq-617** [comment]
### Missing sliding parameter
create table statistics_vibration as select avg(value) as avg, count(value) as count, sum(value) as sum from vibration interval(1m) **sliding(1m)**

**Comment by wowo404** [comment]
according the document,missing sliding parameter is ok, the time window equals forward sliding time. and after your response, i test again with the slidiing parameter, it doesn't have any effect. and i upgrade the database version from 1.6.5.7 to 1.6.5.9

**Comment by liuyq-617** [comment]
wechat:msqdfx

**Comment by liuyq-617** [comment]
According to this issue [https://github.com/taosdata/TDengine/issues/1914](url) ,it seems that you already have a result on this issue.
Please continue to update on this issue [https://github.com/taosdata/TDengine/issues/1914](url)
