### ISSUE TITLE
tdengine has a granfana plugin?

### ISSUE THREAD

**Issue by strongit** [taosdata/TDengine#19]
https://grafana.com/plugins
can not found a plugin for tdengine?where can i get this, tks.

**Comment by isaac-ipl** [comment]
I believe it is in the repo here:
https://github.com/taosdata/TDengine/tree/master/src/connector/grafana/tdengine

**Comment by johnnyhou327** [comment]
Hi @strongit , the Grafana plugin for TDengine has not yet been published to Grafana's official plugins. You can find the plugin files provided by Taosdata Team in the directory as @isaac-ipl suggested.
