### ISSUE TITLE
option to flush the commit log 

### ISSUE THREAD

**Issue by jtao1735** [taosdata/TDengine#190]
In current TDengine implementation, mmap is used to save the commit log, but msync is not used, so there is a chance to lose small amount of data in the commit log if the computer is crashed. For current community edition, since no replication, the data may be lost. 

In typical IoT scenarios, a loss of small amount of data won't cause an issue, but for some scenarios, it is not acceptable. So we had better support msync in the implementation.

There is an option commitLog in system configuration file taos.cfg to turn on/off the commit log. To provide more options for the application, if commitLog is set to 2, msync shall be executed to prevent any data loss. To summarize, for option commitLog, it has 3 settings as below:
- 0: no commit log, if computer is crashed, the data not flushed to data file will be lost.
- 1: there is commit log, but msync is not called, small amount of data may be lost if computer is crashed
- 2: there is commit log, and mysnc is called. If computer is crashed, the data can be fully restored and won't be lost.

**Comment by hujiaming** [comment]
I changed clog to 2 in cfg file and restarted taosd,then i run test,but w"ERROR UTL config option:clog, input value:2, out of range[0.000000, 1.000000], use default value:1 " came up. why?

**Comment by hujiaming** [comment]
I changed clog to 2 in cfg file and restarted taosd,then i run test,but "ERROR UTL config option:clog, input value:2, out of range[0.000000, 1.000000], use default value:1 " came up. why?

**Comment by jtao1735** [comment]
> I changed clog to 2 in cfg file and restarted taosd,then i run test,but "ERROR UTL config option:clog, input value:2, out of range[0.000000, 1.000000], use default value:1 " came up. why?

not implemented yet

**Comment by tigerhu2008** [comment]
I notice that in version 1.6, mmap was used for wal Log, but in 2.x, mmap isn't used anymore, i am curious about why, could you shed some lights? Thanks.

**Comment by tigerhu2008** [comment]
> I notice that in version 1.6, mmap was used for wal Log, but in 2.x, mmap isn't used anymore, i am curious about why, could you shed some lights? Thanks.

@jtao1735  Jeff, could you please shed some lights? Thanks.
