### ISSUE TITLE
在数据库不明原因宕机之后，某个超级表的数据丢失

### ISSUE THREAD

**Issue by sytuacmdyh** [taosdata/TDengine#19013]
**Bug Description**
不明原因宕机之后，某个超级表的数据丢失，并且schemless 写入报错"[0x61b] Table schema is old"

**To Reproduce**
无法复现，可提供错误日志

**Screenshots**
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/13233969/208360361-5be8d176-399e-459a-b3cc-8043bf64fbf9.png">

**Environment (please complete the following information):**
 - OS: [docker]
 - TDengine Version [3.0.2.0]

**Comment by yu285** [comment]
我们看下

**Comment by yu285** [comment]
先切换到 3.0.2.6 版本

**Comment by sytuacmdyh** [comment]
> 先切换到 3.0.2.6 版本

在出现问题之后，持续运行到现在没有再次宕机（这么久了，数据已经无需恢复，我就先关掉这个issue了吧）
