### ISSUE TITLE
tdengine 2.1.2版本 keep设置，无法删除数据？

### ISSUE THREAD

**Issue by chenjie19940227** [taosdata/TDengine#19029]
具体操作如下：（版本2.1.4）
1、数据表 去年到至今都有数据（总库数据2-4亿，几十张超级表：1-3千张子表）
2、修改keep，设置为200
3、查询数据，条目未变。（设置已经1-2天）

能够满足的情况下
1、不升级的情况下，能够满足数据删除。（优选）
2、升级是否保障数据稳定性。最好有详细的具体方法（最好附带稳定版本和升级说明）
3、其他解决办法

**Comment by yu285** [comment]
修改keep，设置为200，但是查询数据，条目未变。 

在你设置为200后，会有大批量数据处于过期状态，但是触发删除过期数据操作的是的是数据落盘。

而数据落盘是需要写入累积到某个vnode写满 1/3 缓冲区，或者数据库停服才可以。如果你写入量小，他确实会长时间凑不满1/3。所以可以选择等待，或者选择手动重启一下服务再验证条目数。

结论是：不升级的话，当前也可以满足数据删除，只是触发条件如上。

对于这种快2年的版本建议速升级，2.0 离线升级手册：https://www.taosdata.com/engineering/10222.html

可以按照这个操作，做好数据文件备份的前提下来做升级。
