### ISSUE TITLE
结构中使用FLOAT存储数据，结合APERCENTILE函数后，数据精度多出数位小数

### ISSUE THREAD

**Issue by hubo0508** [taosdata/TDengine#19020]
![d4d98df37b087f5a0acf0afc0cbbc98](https://user-images.githubusercontent.com/2850109/208411216-01f52659-e611-463c-8b5c-4479d5e006d6.jpg)
![image](https://user-images.githubusercontent.com/2850109/208411270-880d4d12-e319-4dd6-bbf1-a906506052cf.png)

SELECT _WSTART pt, _WEND, APERCENTILE(press, 50) as press FROM meter_1559734076022521857_24995_10 WHERE ts >= '2022-12-19 00:00:00' and ts <= '2022-12-19 18:24:35' INTERVAL(60m) FILL(PREV)

**Comment by yu285** [comment]
> 漏了一条，原始数据存储前只有4位小数，到库后，查询出来全部默认加了一个0，如上图

由于浮点数存储有固定的方式，因此只能展示出固定的长度。这个是不可自定义的

**Comment by yu285** [comment]
这个返回double的问题，我们还在讨论。不过估计短期不会调整。
