### ISSUE TITLE
datax demo write to TDengine failed

### ISSUE THREAD

**Issue by kangrunze** [taosdata/TDengine#19036]
使用datax官方的tdenginewriter 写入td报错 connot find column in resultset
官方示例：https://github.com/alibaba/DataX/blob/master/tdenginewriter/doc/tdenginewriter-CN.md

![80BC538E-CBF0-4166-AC0F-8FCC29EA8090](https://user-images.githubusercontent.com/71558627/208592506-b75d7c01-e64c-409e-949f-fdabed73322b.png)

tdengine 3.0.2.0
taos-jdbcdriver 3.0.3
datax 3.0

**Comment by yu285** [comment]
收到，我们看下

**Comment by zmlgirl** [comment]
@kangrunze 可以使用 https://github.com/taosdata/DataX/tree/dev/lispQin 这个分支编译后执行对 TDengine 3.0 的写入。
