### ISSUE TITLE
使用taos连接出现错误消息, 貌似不影响使用, 源码编译, checkout tag >= ver-1.6.5.8

### ISSUE THREAD

**Issue by fangguangyang** [taosdata/TDengine#1904]
**Bug Description**
ERROR MND pShow:0x7efeac004f30, type:14 vpeers-rsp, failed to get Meta, code:76

**To Reproduce**
1. 源码编译之后启动taosd
2. 仅使用taos连接

**Screenshots**
![image](https://user-images.githubusercontent.com/14014903/81791389-40bca200-9539-11ea-8122-56c18df436d3.png)

**Environment (please complete the following information):**
 - OS: CentOS 7.7
 - 16GB, i5-8400, 50GB
 - TDengine Version 1.6.6.1

**Comment by liuyq-617** [comment]
Thank you for your feedback
You are also welcome to use the latest version of the system, the latest version number is 1.6.5.9

**Comment by fangguangyang** [comment]
ver-1.6.5.7没有这个错误消息, ver-1.6.5.8及以上有

**Comment by sangshuduo** [comment]
请使用新版本
