### ISSUE TITLE
将2.8版本的数据通过taosdump到迁入到windows版3.0.2数据库，一直不成功，但是也没看到报错信息

### ISSUE THREAD

**Issue by xiaoxiaoyangzhenxing** [taosdata/TDengine#19056]
========== arguments config =========
taosdump version 2.3.2, commit: d55a1f8
host: (null)
user: root
port: 0
outpath: 
inpath: E:\taos
resultFile: ./dump_result.txt
all_databases: false
databases: true
databasesSeq: test
schemaonly: false
with_property: true
answer_yes: false
avro codec: snappy
data_batch: 16383
thread_num: 8
allow_sys: false
escape_char: true
loose_mode: false
isDumpIn: true
arg_list_len: 0
debug_print: 0
========== DUMP IN ========== 
# DumpIn start time: 2022-12-21 10:21:52

**Comment by yu285** [comment]
请先更新到2.6.0.32 ，在此版本上导出数据，再导入 3.0

**Comment by sangshuduo** [comment]
taosdump 执行加上 -g 参数可以输出更多信息

**Comment by yu285** [comment]
windows版的taosdump 在进行 Linux 迁移到 windows 上的工作还有些问题，处理完后，会重新reopen这个问题。
