### ISSUE TITLE
invalid user with write authority 

### ISSUE THREAD

**Issue by hert525** [taosdata/TDengine#19066]
![image](https://user-images.githubusercontent.com/19421393/208854794-071b2abd-a8a1-4f03-ae9a-67fd8991fafd.png)

**Comment by yu285** [comment]
<img width="769" alt="image" src="https://user-images.githubusercontent.com/74105241/209066758-e4a6e6d1-0922-4763-96c3-922535ab3bf1.png">

**Comment by hert525** [comment]
现在新建的用户 test最简单的密码123456都不行了 查数据都会报invalid user



---原始邮件---
发件人: "Yu ***@***.***&gt;
发送时间: 2022年12月22日(周四) 中午1:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [taosdata/TDengine] 新建用户已经授权了write权限 查询数据时报invalid user (Issue #19066)

**Comment by hert525** [comment]
tdengine 2.6版本

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/

如果还有具体的使用问题，可以加微信：a15652223354
