### ISSUE TITLE
What is the maximum length supported by NCHAR, can this limit be removed in the code myself?

### ISSUE THREAD

**Issue by zzboy** [taosdata/TDengine#1906]
ATT

**Comment by Aries-Lee1991** [comment]
最大长度不能超过4KB，无法解除限制。

**Comment by zzboy** [comment]
> 最大长度不能超过4KB，无法解除限制。

那写法是NCHAR(4000)还是NCHAR(1000)？

**Comment by liuyq-617** [comment]
一个表必须有timestamp做主键，8bytes。
nchar单个是4bytes,所以您最多只能是nchar(1022)

如果您需要存那么多字符串的话，不要使用我们的数据库。我们不适合做字符串的处理
