### ISSUE TITLE
UDF ERROR Receive error EOF

### ISSUE THREAD

**Issue by bihuazhao** [taosdata/TDengine#19065]
使用udf函数报错
下面是代码，由于我们这边文件会被加密，所以将bit_and.c 命名成 bit_and.log
[bit_and.log](https://github.com/taosdata/TDengine/files/10275305/bit_and.log)

sql：
CREATE FUNCTION bit_and AS "/tmp/udf/libbitand.so" OUTPUTTYPE INT;
成功

SHOW FUNCTIONS;
查到自定义函数添加成功

SELECT bit_and(pos_state,acc_state) FROM track_info.track_1;
执行这个sql下面是报错日志
12/21 11:21:27.423152 00022746 UDF get dnodeId:0 from env, pipe path:/var/lib/taos//.udfd.sock.0
12/21 11:21:27.423174 00022746 UDF bind to pipe /var/lib/taos//.udfd.sock.0
12/21 11:21:27.423232 00022746 UDF start udfd event loop
12/21 14:07:42.146454 00022746 UDF ERROR Receive error EOF
12/21 14:07:42.133711 00012565 UDF setup request. seq num: 0, udf name: bit_and
12/21 14:07:42.146305 00012567 UDF teardown. seq number: 2, handle:7f342c001a70
12/21 14:11:59.502830 00022746 UDF ERROR Receive error EOF
12/21 14:11:59.489010 00012568 UDF setup request. seq num: 3, udf name: bit_and
12/21 14:11:59.502688 00012566 UDF teardown. seq number: 5, handle:7f3420001a70

动态库没发现问题
[root@test script]# ldd /tmp/udf/libbitand.so
        linux-vdso.so.1 =>  (0x00007ffc7647b000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f435d128000)
        /lib64/ld-linux-x86-64.so.2 (0x00005581d610d000)
[root@test script]#

**Comment by bihuazhao** [comment]
执行sql：
SELECT bit_and(pos_state,acc_state) FROM track_info.track_1;

SQL 错误 [10506]: TDengine ERROR (290a): sql: SELECT bit_and(pos_state,acc_state) FROM track_info.track_1, desc: udf invalid output type

**Comment by bihuazhao** [comment]
表结构：
pos_state,acc_state，这两个字段都是 TINYINT类型的
CREATE STABLE track_info.track 
(
dev_time TIMESTAMP COMMENT '设备时间',
pos_state TINYINT COMMENT '定位状态，0：未定位，1：定位',
acc_state TINYINT COMMENT 'Acc状态，0：开，1：关',
lon DOUBLE COMMENT '经度', 
lat DOUBLE COMMENT '纬度',
speed FLOAT COMMENT '速度（KM/H）',
run_state BOOL COMMENT '行停状态，true：行，false：停',
direct FLOAT COMMENT '方向',
mileage FLOAT COMMENT '里程（KM）',
driver NCHAR(32) COMMENT '驾驶员',
raw_data NCHAR(512) COMMENT '原始数据'
) 
tags (id BIGINT COMMENT '设备id');

**Comment by shenglian-zhou** [comment]
The EOF is logged with the wrong log level. In the latest code, it is changed to the info level.

from the udf code, the type must be INT. please modify the udf code to accept tinyint.

**Comment by shenglian-zhou** [comment]
for (int32_t i = 0; i < block->numOfCols; ++i) {
        SUdfColumn* col = block->udfCols[i];
        if (!(col->colMeta.type == _**TSDB_DATA_TYPE_INT**_)) {
            return TSDB_CODE_UDF_INVALID_INPUT;
        }
    }

**Comment by shenglian-zhou** [comment]
May I close this issue?

**Comment by bihuazhao** [comment]
sure，thanks
