### ISSUE TITLE
durid connection 、demo issue

### ISSUE THREAD

**Issue by GerryStydy** [taosdata/TDengine#19077]
由于没有墙，网慢的不行，固把一些问题一次提了，见谅！
问题2：druid 、JDBC-RESTful 配置druid连不上库？	就是下面两句配置连不上库
	#spring.datasource.driver-class-name=com.taosdata.jdbc.rs.RestfulDriver
	#spring.datasource.url=jdbc:TAOS-RS://127.0.0.1:6041/demo?timezone=UTC-8&charset=UTF-8&locale=en_US.UTF-8
问题3：单节点支持的访问量、连接量、存储量、库量、表量？	
问题4：在程序里的一个连接最大支持多长时间？
问题5：window上tdng server的6030、6041端口在那里开?
问题6：spring.datasource.url=jdbc:TAOS://127.0.0.1:6030/test  
	   如果这里不写test我发现也能连上但不写test时怎么理解？
问题7：Retrying request to {}->http://127.0.0.1:6041
	   init datasource error, url: jdbc:TAOS-RS://127.0.0.1:6041/test?timezone=UTC-8&charset=UTF-8&locale=en_US.UTF-8
	   这个问题怎么定位，搞不明白是哪儿的问题？
问题8：http://localhost:8087/weather/lastOne 时报(就这个方法报)
	   java.lang.NullPointerException
	   at com.taosdata.example.springbootdemo.service.WeatherService.lastOne(WeatherService.java:66)
问题9：数据点是指什么
问题10：表字段类型是用vchar还是vchar(20)

**Comment by huolibo** [comment]
问题2：需要配置 用户名与密码。druid 配置详见：[spring demo](https://github.com/taosdata/TDengine/blob/main/examples/JDBC/springbootdemo/src/main/resources/application.properties)
问题3：单点支持数量与机器性能相关，需要经过压力测试。
问题4：连接支持时间可以通过连接池配置。
问题5：在 windows 上启动 TDengine 与 taosAdapter 将占用 6030 与 6041 端口，可进行本机访问。
问题6：写上 /test 之后执行 SQL 时将在此数据库下进行，否则执行 SQL 时需要提前 `use test`。
问题7：没有提前创建 test 数据库。在使用此 url 创建连接时程序自动执行 `use test`报错
问题8：数据中需要先插入数据再查询，否则查询结果为 null 导致后续程序执行出错（此处需要改进）。
问题9：数据点大概指一条记录（具体没有指明出处不太确认）。
问题10：表字段类型为 varchar 但是创建表时需要指定变长字符可容纳的长度所以创建表时为 create table .. (ts timestamp, c1 varchar(10));

**Comment by GerryStydy** [comment]
问题2：需要配置 用户名与密码。druid 配置详见：[spring demo]
我的配置就是从你发的链接里来的，报的问题是Init DruidDataSource，Retrying request to {}->http://127.0.0.1:6041
我不知道缺什么东西还是要怎么设置下？您方便远程帮我看下吗？
问题4：连接支持时间可以通过连接池配置。比如我的项目跑的就是我们的springbootdemo,如果要让一次连接一直不断开要怎么设置？
问题5：在 windows 上启动 TDengine 与 taosAdapter 将占用 6030 与 6041 端口，可进行本机访问。
那么windows上在哪里启动TDengine和TaosAdapter？ 我刚接触就知道用taosd.exe启动，但这是否就启动了TDengine 与 taosAdapter我不知道如何确定。


问题8：数据中需要先插入数据再查询，否则查询结果为 null 导致后续程序执行出错（此处需要改进）。
我跑的是我们springbootdemo的项目数据有的，但是我们程序获取时取出来就成null了，您方便帮我远程下吗？
问题10：表字段类型为 varchar 但是创建表时需要指定变长字符可容纳的长度所以创建表时为 create table .. (ts timestamp, c1 varchar(10));   我看定义都是nchar(10) 哪varchar跟nchar啥区别啊？

**Comment by GerryStydy** [comment]
问题2：需要配置 用户名与密码。druid 配置详见：[spring demo]
我的配置就是从你发的链接里来的，报的问题是Init DruidDataSource，Retrying request to {}->http://127.0.0.1:6041
我不知道缺什么东西还是要怎么设置下？您方便远程帮我看下吗？
问题4：连接支持时间可以通过连接池配置。比如我的项目跑的就是我们的springbootdemo,如果要让一次连接一直不断开要怎么设置？
问题5：在 windows 上启动 TDengine 与 taosAdapter 将占用 6030 与 6041 端口，可进行本机访问。
那么windows上在哪里启动TDengine和TaosAdapter？ 我刚接触就知道用taosd.exe启动，但这是否就启动了TDengine 与 taosAdapter我不知道如何确定。


问题8：数据中需要先插入数据再查询，否则查询结果为 null 导致后续程序执行出错（此处需要改进）。
我跑的是我们springbootdemo的项目数据有的，但是我们程序获取时取出来就成null了，您方便帮我远程下吗？
问题10：表字段类型为 varchar 但是创建表时需要指定变长字符可容纳的长度所以创建表时为 create table .. (ts timestamp, c1 varchar(10));   我看定义都是nchar(10) 哪varchar跟nchar啥区别啊？

**Comment by GerryStydy** [comment]
问题2：需要配置 用户名与密码。druid 配置详见：[spring demo]
我的配置就是从你发的链接里来的，报的问题是Init DruidDataSource，Retrying request to {}->http://127.0.0.1:6041
我不知道缺什么东西还是要怎么设置下？您方便远程帮我看下吗？
问题4：连接支持时间可以通过连接池配置。比如我的项目跑的就是我们的springbootdemo,如果要让一次连接一直不断开要怎么设置？
问题5：在 windows 上启动 TDengine 与 taosAdapter 将占用 6030 与 6041 端口，可进行本机访问。
那么windows上在哪里启动TDengine和TaosAdapter？ 我刚接触就知道用taosd.exe启动，但这是否就启动了TDengine 与 taosAdapter我不知道如何确定。


问题8：数据中需要先插入数据再查询，否则查询结果为 null 导致后续程序执行出错（此处需要改进）。
我跑的是我们springbootdemo的项目数据有的，但是我们程序获取时取出来就成null了，您方便帮我远程下吗？
问题10：表字段类型为 varchar 但是创建表时需要指定变长字符可容纳的长度所以创建表时为 create table .. (ts timestamp, c1 varchar(10));   我看定义都是nchar(10) 哪varchar跟nchar啥区别啊？

**Comment by huolibo** [comment]
问题2：连接失败有两个原因：1. 提前创建 test 数据库。2. 启动 taosAdapter, 因为 taosd 不提供 http 服务，需要通过 taosAdapter 来提供。下载地址：[安装](https://docs.taosdata.com/get-started/package/#安装)
问题4：这个问题不需要担心，在使用时如果连接池没有连接会根据配置创建相应的连接。
问题5：如上下载 windows 对应的server版本后安装会附带 taosAdapter 启动程序。
问题8：先解决如上问题，在进行插入测试，查询就不会有空指针问题了。
问题10：varchar 与 nchar 类型的区别为是否为变长类型。nchar 为固定长度的。
