### ISSUE TITLE
repeated rows showed up in group by

### ISSUE THREAD

**Issue by yerunqin** [taosdata/TDengine#19088]
**Bug Description**
使用partitionby进行各子表相邻数据差值计算，在使用groupby 统计每个子表最大的差值和数据量后，出现同一个分组两条记录的情况，单独查询一个子表数据又是正常的。

**To Reproduce**
使用partitionby进行各子表相邻数据差值计算，在使用groupby 统计每个子表最大的差值和数据量后，出现同一个分组两条记录的情况，单独查询一个子表数据又是正常的。
![image](https://user-images.githubusercontent.com/38376164/209089175-6994aa5e-11bc-47c7-a129-91685a43859d.png)

**Expected Behavior**
分组后，每个子表一条记录

**Screenshots**
单个子表查询（正常）
![image](https://user-images.githubusercontent.com/38376164/209089385-414c3078-c3a7-4056-a24f-471565460990.png)
多个子表查询（异常）
![image](https://user-images.githubusercontent.com/38376164/209089175-6994aa5e-11bc-47c7-a129-91685a43859d.png)

**Environment (please complete the following information):**
 - OS: [CentOS 7.2]
 - TDengine Version [3.0.2.0]

**Comment by yerunqin** [comment]
复现SQL及数据:
select target_name,max(time_diff) AS time_diff,(count(1)+1) AS track_count from (
    select tbname as target_name,diff(pos_time) time_diff from test
    where tbname in ('_413254290_108_1001_','_413254000_108_1001_')
    partition by tbname
) a group by target_name;
[表结构和数据.txt](https://github.com/taosdata/TDengine/files/10285501/default.txt)

**Comment by yu285** [comment]
收到，我们处理下。

**Comment by yu285** [comment]
请在3.0.2.2 版本上做个验证吧，已经修复了。
