### ISSUE TITLE
create database error 

### ISSUE THREAD

**Issue by xujiesh0510** [taosdata/TDengine#1908]
root@test:/var/log/taos# taos --version
version: 1.6.5.8

server   returns  http status code 400   when i issue   command  'create database if not exists  db'  using http request

details:
 ERROR HTP context:0x7fafa3a58730, fd:68, ip:192.168.100.38:54534, code:400, error:33:DB already there

**Comment by liuyq-617** [comment]
Thank you for your feedback, we will deal with it as soon as possible
