### ISSUE TITLE
Database not ready

### ISSUE THREAD

**Issue by huashi1234** [taosdata/TDengine#19086]
查询和创建都报这个错误，“Database not ready” 当前数据不可用，常见原因是vnode正在同步数据。需要如何解决

![微信图片_20221222130531](https://user-images.githubusercontent.com/81249139/209061172-5fe384c7-607e-4abb-becb-ab012953eea0.png)

**Comment by yu285** [comment]
这个可以升级到 3.0.2.1 来解决
