### ISSUE TITLE
dump导出数据不全

### ISSUE THREAD

**Issue by xiaoxiaoyangzhenxing** [taosdata/TDengine#19081]
2.6版本数据库，数据库里面原有3000多超级表，但是使用dump导出的DBS.SQL文件里面才100个超级表建表语句，而且我把导出的数据恢复到一个新的数据库后，发现很多表都没有

**Comment by sangshuduo** [comment]
2.6的具体版本是什么？taosdump 的版本具体是什么？是在同一台机器上运行吗？

**Comment by xiaoxiaoyangzhenxing** [comment]
![image](https://user-images.githubusercontent.com/20468975/209041336-12d29495-767e-44a5-aed8-751c207fd36c.png)
是在同一个机器上

**Comment by xiaoxiaoyangzhenxing** [comment]
服务器版本也是2.6.0.32

**Comment by xiaoxiaoyangzhenxing** [comment]
&nbsp;


1219225947
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shuduo ***@***.***&gt;; 
发送时间: 2022年12月22日(星期四) 上午10:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [taosdata/TDengine] dump导出数据不全 (Issue #19081)





 
2.6的具体版本是什么？taosdump 的版本具体是什么？是在同一台机器上运行吗？

**Comment by sangshuduo** [comment]
在 /etc/taos/taos.cfg 里增加一行 shellActivityTimer  120，另外线程数不要设置太大

**Comment by yangsiting** [comment]
也遇到了同样的问题，给配置文件中增加了这个参数shellActivityTimer 120，线程数据设置为20,到处的超级表仍然为100个，请问是 有相关参数限制了吗？
