### ISSUE TITLE
TDengine crash with data lost

### ISSUE THREAD

**Issue by yxhpy** [taosdata/TDengine#19098]
你好，我在使用TDengine时，在较大并发的情况下，重复提交相同数据后，导致整个表数据丢失，重启无效。当我查询该表内容时主程序崩溃。

**Comment by yu285** [comment]
请问版本号是？ 可以加微信 a15652223354 做一下远程调试

**Comment by yu285** [comment]
未得到回复，暂做关闭处理，如有问题请联系我
