### ISSUE TITLE
物联网场景

### ISSUE THREAD

**Issue by pwudi922** [taosdata/TDengine#191]
物联网有一个很重要的指标就是实时状态，以下场景是很常见的且TDengine不具备的
1 实时状态筛选
建议增加功能：STABLE查询,条件语句中能支持LAST函数，比如：
1） 筛选离线设备(24小时未发过数据)
SELECT TBNAME,tb_tags FROM stable WHERE  LAST(ts) < now - 24h
2） 筛选实时状态为1的设备
SELECT TBNAME,tb_tag FROM stable WHERE  LAST(stat) =1

2 实时状态告警
建议在订阅中增加对STABLE的订阅,比如
STABLE 中任意表LAST(stat) >1     -> tbname
SELECT LAST(*) FROM tbname  -> publish

**Comment by hzcheng** [comment]
多谢提出建议，这些功能会在后续开发中慢慢加上的。
