### ISSUE TITLE
3.0.2 windows版本 运行期间 taosd.exe会经常自动关闭

### ISSUE THREAD

**Issue by chenjilai** [taosdata/TDengine#19113]
**Bug Description**
3.0.2 windows版本 运行期间 taosd.exe会经常自动关闭.
 五个超级表,每个超级表大概20万个表

**Environment (please complete the following information):**
 - OS: windows 2016 datacenter
 - 内存48G cpu12核
 - TDengine Version [3.0.2]免费版

**Additional Context**
运行期间 taosd.exe会经常自动关闭

**Comment by yu285** [comment]
请问有dmp文件生成吗

**Comment by chenjilai** [comment]
> 请问有dmp文件生成吗

已经在群里给出日志 有人帮我看了
