### ISSUE TITLE
taosadapter  established

### ISSUE THREAD

**Issue by yootou** [taosdata/TDengine#19132]
php     2878976  www   12u  IPv4           32873694      0t0      TCP 127.0.0.1:59752->127.0.0.1:6041 (ESTABLISHED)

运行一段时间后，就会出现类似的情况，卡在这个环节。

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
