### ISSUE TITLE
tdengine-demo连接报错

### ISSUE THREAD

**Issue by GerryStydy** [taosdata/TDengine#19136]
问题0 建库时对该数据库入会写 WAL 但不执行 FSYNC是什么意思？这是我们文档建库里的解释我没看明白
问题1 vgroup、vnode、vdata 这几个把人搞混了，能我说解释下么？
问题2 dnode的end point是啥，dnode是什么怎么理解？dnode用来干嘛的？数据点是不是就是dnode?
问题3 我们所说的end point是什么？如master的end point,dnode的point
问题4 我们所说的schema是什么？
问题5：使用	JDBC-JNI 和 JDBC-RESTful的区别是什么？
问题6：我跟的是我们3.0.2.0源码里的TDengine-ver-3.0.2.0\examples\JDBC\springbootdemo这个例子
	报了两个问题第一个是配置文件中使用：
		spring.datasource.driver-class-name=com.taosdata.jdbc.rs.RestfulDriver
		spring.datasource.url=jdbc:TAOS-RS://localhost:6041/test?timezone=UTC-8&charset=UTF-8&locale=en_US.UTF-8
		spring.datasource.username=root
		spring.datasource.password=taosdata
	项目在启动时报：
		：I/O exception (org.apache.http.conn.HttpHostConnectException) caught when processing request to {}->http://localhost:6041: Connect to localhost:6041 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
		: Retrying request to {}->http://localhost:6041
		: I/O exception (org.apache.http.conn.HttpHostConnectException) caught when processing request to {}->http://localhost:6041: Connect to localhost:6041 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
		: Retrying request to {}->http://localhost:6041
	请问下这是什么问题？
问题7：我问题7和问题8跑的都是我们3.0.2.0源码里的TDengine-ver-3.0.2.0\examples\JDBC\springbootdemo这个例子
	问题是在controller中的 saveWeather 这个方法产生的：
		post 方式 http://localhost:18087/weather/22.3/33.7  请求
		报：java.sql.SQLException: TDengine ERROR (80000216): syntax error near 'null, 22.3, 33.7, null)' (primary timestamp should not be null)
	我没改过我们的示例程序，请问这如果要改要怎么改可以解决这个问题?
如果方便请加我微信 15191845107 给我远程下，这问题我搞了好几天了郁闷

**Comment by yu285** [comment]
处理完毕
