### ISSUE TITLE
使用grafana 连接 tdengine 提示 TDengine Data source is not working, reason: Bad Gateway

### ISSUE THREAD

**Issue by huangjicong** [taosdata/TDengine#19146]
我用docker 的方式安装了 tdengine 和 grafana，grafana也装好了tdengine的插件，两个都能正常运行，但是grafana建立datasource时提示 连接不上tdengine

提示 TDengine Data source is not working, reason: Bad Gateway

在本机执行  curl -u root:taosdata -d 'show databases' 127.0.0.1:6041/rest/sql  是可以有结果的

**Comment by yu285** [comment]
taos --version
version: 3.0.2.1


插件版本 3.2.7

**Comment by kylinxue** [comment]
我也是，用了最新版本的tdengine3.0.4，grafna连不上tdengine datasource

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354

**Comment by zhangbo6248** [comment]
同样部署方式，使用的版本 taos 3.3.5 grafana 插件 3.3.5 无法连接
<img width="983" alt="image" src="https://github.com/user-attachments/assets/903a1d8c-25fa-47e0-80ab-e8c8e99c5eba" />
<img width="1422" alt="image" src="https://github.com/user-attachments/assets/dce9a5d6-d4eb-4068-b50e-301d64c390dc" />
