### ISSUE TITLE
使用3.0.3.0驱动，JNI连接3.0.2.0涛思数据库？ 出现连接上的问题

### ISSUE THREAD

**Issue by linser2015** [taosdata/TDengine#19148]
执行查询时，出现：
![image](https://user-images.githubusercontent.com/12657856/209514644-b780312a-86aa-43f0-a83a-3c2fd9ba80b5.png)

JNI ERROR     ,Conn  is Broken.

**Comment by yu285** [comment]
客户端的taos shell 能否正常查询表数据？

**Comment by linser2015** [comment]
> 客户端的taos shell 能否正常查询表数据？

客户端可以查到。

**Comment by little-coati** [comment]
我也遇到了相同的问题，后来发现是版本的问题。

**Comment by linser2015** [comment]
> 我也遇到了相同的问题，后来发现是版本的问题。客户端和服务端版本不一致。

是吗？？  我看网上他写的是一个范围 。。有最低要求  是个范围  所以就在可用范围内选了一个版本。。

**Comment by linser2015** [comment]
高版本中  已解决。
