### ISSUE TITLE
tdengine链接问题

### ISSUE THREAD

**Issue by zhouzhou98** [taosdata/TDengine#19144]
本地mac安装了tdengine3.0.1.8的server和client的pkg包，启动：launchctl start com.tdengine.taosd；
请求版本 taos --version 出现：invalid option --version，查看服务状态launchctl list | grep taosd 没有启动成功，显示-	255	com.tdengine.taosd

**Comment by yu285** [comment]
I guess it has been resolved

**Comment by 526326991** [comment]
· TDengine-client-3.0.7.1-macOS-x64.pkg
· TDengine-server-3.0.7.1-macOS-x64.pkg
刚装完，表示并没有解决！
OS:catalina10.15.7
