### ISSUE TITLE
execute continuous query error because sql grammar error,restart database, the database reload the error continuous

### ISSUE THREAD

**Issue by wowo404** [taosdata/TDengine#1914]
**Bug Description**
When I execute some continuous query, failed at sql grammar error, that's ok. I continue test continuous query, some problem happened, the database crashed(crash log A is below) , i spend some time try to find out the reason, but i failed, after that, i upgrade the version from 1.6.5.7 to 1.6.5.9, and the database is working, then i check the log, i found the database still reload the bad grammar continuous query sql(error log B is below).

**To Reproduce**
here is operate in version 1.6.5.7
1. before i got this bug，i execute some test with bad grammar continuous query sql in a long time ago
2.create a super table
3.create a continuous query
4.i found a tag with the wrong data type in the super table
5.drop that tag, this operation cost about 10 minutes
6.got the message 'can't connect the database server'
7.check the system progress, the database progress is gone
8.check the system memory and cpu load, the cpu is almost 100% because other progress
9.i don't know whether my operation caused crash or cpu load is too high

here is operate in version 1.6.5.9
1. restart the database
2. the database is working, then i check the log, i found the database still reload the bad grammar continuous query sql.

**Environment (please complete the following information):**
 - OS: [CentOS Linux release 7.2.1511]
 - Memory:32G, CPU:4 processor
 - TDengine Version [1.6.5.7]

**crash log A**
![E)IK)C97WB7$4~G@ 3_5B2R](https://user-images.githubusercontent.com/39786064/81922974-85b30800-960f-11ea-819d-5072d0fca007.png)
![DBRI2XD%B_)ZKJOC)NW{0AG](https://user-images.githubusercontent.com/39786064/81922986-8a77bc00-960f-11ea-907c-fc8fcadf814c.png)

**errorlog B**
![image](https://user-images.githubusercontent.com/39786064/81922726-19380900-960f-11ea-9e60-686dbec8e13d.png)

**Comment by wowo404** [comment]
i already upgrade the version to 1.6.5.9, execute continuous query without save result in the table, the sql run normally, when the continuous query with save result in the table, still doesn't have any effect.

**Comment by localvar** [comment]
as v2.0 is release last month with many changes, I will close this issue. please try the new version and feel free to raise a new issue if the problem still there.
