### ISSUE TITLE
3.0.1.5 python taos query issue

### ISSUE THREAD

**Issue by walle-zhao** [taosdata/TDengine#19159]
版本：3.0.1.5
问题：当我使用taos的库在连接执行sql的时候会报错(请求过快的时候，会偶发)：
python: /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/client/src/clientMain.c:574: taos_fetch_block_s: Assertion `0' failed

**Comment by yu285** [comment]
该问题在3021 应该已经修复，可以升级验证，如果仍有问题可再联系，暂做关闭处理
