### ISSUE TITLE
3.0.2.0集群搭建后，创建database后存在宕机问题，整个服务不可用状态

### ISSUE THREAD

**Issue by xinwenwxw** [taosdata/TDengine#19164]
supportVnodes 8
CREATE DATABASE ciot KEEP 365 DURATION 3 VGROUPS 12 REPLICA 3 BUFFER 256 CACHESIZE 64  CACHEMODEL 'last_row' PAGES 256 pagesize 8； 
创建database后，就存在宕机问题。创建超级表非常慢

**Comment by xinwenwxw** [comment]
确定是使用副本 3就存在问题，REPLICA 1就不会存在该问题

**Comment by xinwenwxw** [comment]
![Uploading df45e3bc220f48679e6b7a5db96ecf8.png…]()

**Comment by xinwenwxw** [comment]
![df45e3bc220f48679e6b7a5db96ecf8](https://user-images.githubusercontent.com/14171562/209628427-e8da2508-1b43-4f18-bb1f-6d3c186af5ee.png)

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
