### ISSUE TITLE
3.0.2.0集群搭建后，创建mnodes后存在报错 DB error: Unknown transaction error (111.321341s)

### ISSUE THREAD

**Issue by yesOldKing** [taosdata/TDengine#19165]
**Bug Description**
![106777343441ed692245f3d51ee8b4a](https://user-images.githubusercontent.com/64937574/209600506-7c889cae-df55-42d0-b401-15415c2f8a1a.png)

**Environment (please complete the following information):**
 - OS: [阿里云 ECS  CentOS 7.0]
 - Memory 24G , CPU  8核 , current Disk Space   500G
 - TDengine Version [3.0.2.0]

**Comment by endiw395927** [comment]
maybe check network first

**Comment by yesOldKing** [comment]
ok   Thank U
