### ISSUE TITLE
安装@tdengine/client问题

### ISSUE THREAD

**Issue by zhouzhou98** [taosdata/TDengine#19173]
使用mac m1，node版本为16.10.0安装@tdengine/client，执行yarn add @tdengine/client，报错 invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun，

**Comment by sangshuduo** [comment]
请参考 https://docs.taosdata.com/connector/node/#%E4%BD%BF%E7%94%A8%E9%99%90%E5%88%B6
