### ISSUE TITLE
partition by后在grafana展示的曲线有问题

### ISSUE THREAD

**Issue by leidachui** [taosdata/TDengine#19186]
我的查询语句如下：
 SELECT _wstart ,err_code,sum(total_count) FROM push_static.push_msg_done WHERE ts > '2022-12-27T06:45:45.000Z' and ts < '2022-12-27T06:46:25.000Z' and status = 2 partition by err_code INT
ERVAL (1000a) 

在命令行查，可以看到err_code有4种值，并且count是对的
![image](https://user-images.githubusercontent.com/33803494/209639774-0cd6dc8f-2eac-46c1-8022-369ec3d7ad14.png)

但在grafana上面只能显示两条曲线，并且无法用err_code命名
![image](https://user-images.githubusercontent.com/33803494/209639994-c3be51b3-cb31-4de9-b003-c0fc2c285423.png)

我看下面的issue也提了类似的问题：
https://github.com/taosdata/TDengine/issues/18445

请问现在已经修复了吗， 我用的grafana插件是 最新的 3.2.7版本；
如果没有修复，预计什么时候可以修复呢

**Comment by sunpe** [comment]
需要配置 「group by column name」。
<img width="939" alt="image" src="https://user-images.githubusercontent.com/8380506/209744376-61eecd28-fbb6-4dbc-a904-a11892bbc86f.png">

**Comment by leidachui** [comment]
sql中配置了不可以，必须 在 group by这里配置吗？ 我是配置了没有反应
