### ISSUE TITLE
TDengine ERROR (2350): unknown connection：jdbc:TAOS://127.0.0.1:6030

### ISSUE THREAD

**Issue by glCoding** [taosdata/TDengine#19184]
<img width="650" alt="de66877190f5774ff0b845d9b1e9266" src="https://user-images.githubusercontent.com/20293464/209638735-d65baf9c-bfca-4871-a447-d8c2e6c3c27e.png">

数据库连接池无模式写入，报TDengine ERROR (2350): unknown connection：jdbc:TAOS://127.0.0.1:6030/，
代码复制的官网的

**Comment by huolibo** [comment]
获取连接时使用  ds.getConnection().unwrap(TSDBConnection.class);
