### ISSUE TITLE
2.6.0.0版本 taosadapter 容器报错挂掉

### ISSUE THREAD

**Issue by qiaogli** [taosdata/TDengine#19195]
我这边做了一个docker smarm tdengine集群，然后程序运行一个sql的时候taosadapter 容器直接报错挂掉
tdengine版本是2.6.0.0
直接在tdengine里面是可以执行的，但是通过程序运行经过taosadapter 就报错
报错信息：
taosadapter: /home/ubuntu/workroom/jenkins/TDinternal/community/src/query/src/qFill.c:209: fillResultImpl: Assertion `pFillInfo->currentKey == ts' failed.
SIGABRT: abort
![image](https://user-images.githubusercontent.com/83851179/209741784-0a187fdc-11a1-407f-b23a-239581e2c8a6.png)
sql是：select sum(enter) as enter,sum(exit) as exit ,sum(attendance) as attendance from ai_peopleCount where project_code=('656') and upload_time>='2022-05-01 00:00:00' and upload_time<='2022-06-01 00:00:00' interval(1d) fill(value, 0) group by sn；

**Comment by sangshuduo** [comment]
2.6.0.0 版本太老了，换 3.0.2.x 或者 2.6.0.32 以上版本

**Comment by qiaogli** [comment]
升到2.6.0.34还是不行，生产环境用的是2.6的，现在有办法从2.x升到3.x了吗

**Comment by sangshuduo** [comment]
> 升到2.6.0.34还是不行，生产环境用的是2.6的，现在有办法从2.x升到3.x了吗

如果数据量不是特别大的情况可以用 taosdump 备份恢复

**Comment by qiaogli** [comment]
我之前也试过用taosdump从2.6备份还原数据到3.0 都是报错
![image](https://user-images.githubusercontent.com/83851179/209744770-4a2a3028-6382-4542-b39f-1660871bb2e4.png)

**Comment by sangshuduo** [comment]
3.0 的表的 column 有增删吗？

**Comment by qiaogli** [comment]
没有，只是把导数据，没做其他操作

**Comment by qiaogli** [comment]
这个bug 2.6版本还能解决下吗

**Comment by sangshuduo** [comment]
TDengine 2.x 和 3.x 的具体版本号是多少？ taosdump 具体版本是什么？

**Comment by qiaogli** [comment]
2.6.0.0  3.0.0.0

**Comment by sangshuduo** [comment]
3.0 系列建议用最新的 3.0.2.1 或者马上发布的 3.0.2.2
taosdump 建议用马上发布的 2.4.0

**Comment by yu285** [comment]
您好我们可能需要远程调试一下，可以加微信 a15652223354 做具体沟通。

**Comment by yu285** [comment]
使用taosadapter和服务端部署在一起的方式，问题没有出现。怀疑是时区配置问题。
