### ISSUE TITLE
2.6.0.0版本sql执行某sql查询服务挂掉

### ISSUE THREAD

**Issue by hairtail7** [taosdata/TDengine#19199]
2.6.0.0版本sql执行某sql查询服务挂掉
并非每次都会复现。
sql模板
select * from #{tableName} and ts >= #{startTime} and ts <=  #{endTime} order by ts desc limit #{pageNum},#{pageSize}
日志信息
![image](https://user-images.githubusercontent.com/61339505/209748560-9a9bc9cf-c481-41eb-887c-28042f2cbbd1.png)
![image](https://user-images.githubusercontent.com/61339505/209748635-1c8d804c-d012-49ea-acfa-1feb2efeb6e7.png)

**Comment by yu285** [comment]
可以加微信 a15652223354 远程调试一下
