### ISSUE TITLE
Out of dnodes

### ISSUE THREAD

**Issue by cfh763551832** [taosdata/TDengine#19201]
我在创建一个数据库的时候是成功的，当我再创建的时候就报错
![image](https://user-images.githubusercontent.com/21970995/209749561-0e9e27a9-1bdf-49fb-801b-64d25805f1aa.png)

**Comment by dlk557567** [comment]
需要增加改节点上 supportVnodes 参数的大小。通过/etc/taos.cfg 修改，修改完后重启服务。

**Comment by cfh763551832** [comment]
@dlk557567 感谢，可以了。我还想问下，这个值的设定与数据库创建个数比例是咋样的，我设定的是8，目前与系统自带的数据库一共是5个，再创建就失败。

![image](https://user-images.githubusercontent.com/21970995/209783435-91101453-d819-4417-8c5e-6041aa83f999.png)

**Comment by yu285** [comment]
建库默认消耗2个，通过vgroups 参数来指定

**Comment by yu285** [comment]
暂做关闭处理，如有其他需求，可以加微信 a15652223354

**Comment by cfh763551832** [comment]
@yu285 谢谢
