### ISSUE TITLE
USING FILE TO BATCH INSERT ERROR

### ISSUE THREAD

**Issue by jorgen-zhao** [taosdata/TDengine#19202]
**Bug Description**
我创建了一个普通表，建表语句如下：
`CREATE TABLE if not exists packet(ts timestamp, id int, imei nchar(64), protocol nchar(10),protocol_version int,battery_level int, temperature DOUBLE, info_length int, drop_alarm TINYINT UNSIGNED, lean_alarm TINYINT UNSIGNE
D, slope_move_alarm TINYINT UNSIGNED,  wake_alarm TINYINT UNSIGNED, swing_alarm TINYINT UNSIGNED,charging TINYINT UNSIGNED,stock_button TINYINT UNSIGNED, operate_status TINYINT UNSIGNED, hex_base_rep_type nchar(10),  base_rep_typ
e_desc nchar(255), dec_base_rep_type int, cpreshs_tilt DOUBLE, retain_str nchar(20),signal_value int, antenna_elevation int, latitude DOUBLE, longitude DOUBLE, roll DOUBLE, pitch DOUBLE, yaw DOUBLE,  ax int, ay int, az int, gx in
t, gy int, gz int, mx int, my int, mz int,  sx int, sy int, sz int, srx int, sry int, srz int, dx int, dy int, dz int, original_packet nchar(512), heading_degrees DOUBLE, lean_degrees DOUBLE, degree DOUBLE, azimuth nchar(10), slp
_wkp_times int, data_status int );`
我从MySQL中导出了150w条数据，通过FILE方式插入。过了一会后，提示DB error: Unable to establish connection (222.769505s) 。对这个表进行count查询也不行了。提示：DB error: Database not ready (12.060000s)

**Expected Behavior**
文件批量顺利插入，查询无异常

**Screenshots**
![image](https://user-images.githubusercontent.com/34176519/209753680-3227144e-d0d8-4068-859e-603918a05df6.png)

**Environment (please complete the following information):**
 - OS: CentOS 8.0 64bit
 - CPU: 4核 内存: 8GB 100GB SSD云硬盘
 - TDengine Version 3.0.1.8

**Comment by dlk557567** [comment]
微信：a15652223354, 我们远程看一下吧
