### ISSUE TITLE
3.0.1.2 client query crash

### ISSUE THREAD

**Issue by fanchunlei1983** [taosdata/TDengine#19200]
[hs_err_pid53772.log](https://github.com/taosdata/TDengine/files/10311744/hs_err_pid53772.log)

3.0.1.2 client query crash ， here is the log

**Comment by fanchunlei1983** [comment]
更新到 3021 ，驱动3.0.3 ，仍有crash 发生
[hs_err_pid55632.log](https://github.com/taosdata/TDengine/files/10311906/hs_err_pid55632.log)

**Comment by huolibo** [comment]
这个现象是过一会儿才会出现还是执行到特定代码后必现的？

**Comment by yu285** [comment]
您好，可以加下微信a15652223354 我们具体排查下

**Comment by gccgdb1234** [comment]
@yu285 此问题是12/28号，1个半月以前，我们问的问题使用都都不做回应，可以关闭处理，相应的内部JIRA关闭。
