### ISSUE TITLE
install tdengine by tdengine/tdengine:3.0.2.2 image on centos 7.9 VM got "Illegal instruction (core dumped)" Error

### ISSUE THREAD

**Issue by lzxking** [taosdata/TDengine#19216]
**Bug Description**

**To Reproduce**
1. docker run -d -p 6030:6030 -p 6041:6041 -p 6043-6049:6043-6049 -p 6043-6049:6043-6049/udp tdengine/tdengine:3.0.2.2
2. container star fail
3. See error：
[root@ivt bin]# docker logs -f k2a-tdengine
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
sysctl: setting key "kernel.core_pattern": Read-only file system
12/28 15:25:22.212969 00000030 TAOS_ADAPTER info "start server:00000030" model=main
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /debug/pprof/             --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/cmdline      --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/profile      --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)
[GIN-debug] POST   /debug/pprof/symbol       --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/symbol       --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/trace        --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/allocs       --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/block        --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/goroutine    --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/heap         --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/mutex        --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/threadcreate --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
[GIN-debug] GET    /metrics                  --> github.com/gin-gonic/gin.WrapH.func1 (5 handlers)
[GIN-debug] GET    /-/ping                   --> github.com/taosdata/taosadapter/v3/controller/ping.Controller.Init.func1 (5 handlers)
[GIN-debug] POST   /rest/sql                 --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).sql-fm (7 handlers)
[GIN-debug] POST   /rest/sql/:db             --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).sql-fm (7 handlers)
[GIN-debug] GET    /rest/login/:user/:password --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).des-fm (6 handlers)
[GIN-debug] GET    /rest/ws                  --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).ws-fm (6 handlers)
[GIN-debug] GET    /rest/stmt                --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).stmt-fm (6 handlers)
[GIN-debug] GET    /rest/tmq                 --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).tmq-fm (6 handlers)
[GIN-debug] POST   /rest/upload              --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).upload-fm (7 handlers)
[GIN-debug] GET    /rest/schemaless          --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).schemalessWs-fm (6 handlers)
[GIN-debug] GET    /rest/vgid                --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).tableVgID-fm (7 handlers)
[GIN-debug] GET    /genauth/:user/:password/:key --> github.com/taosdata/taosadapter/v3/plugin.RegisterGenerateAuth.func1 (5 handlers)
12/28 15:25:22.213675 00000030 TAOS_ADAPTER info "init plugin node_exporter/v1" model=plugin
12/28 15:25:22.215641 00000030 TAOS_ADAPTER info "node_exporter disabled" model=NodeExporter
12/28 15:25:22.215664 00000030 TAOS_ADAPTER info "init plugin opentsdb/v1" model=plugin
[GIN-debug] POST   /opentsdb/v1/put/json/:db --> github.com/taosdata/taosadapter/v3/plugin/opentsdb.(*Plugin).insertJson-fm (7 handlers)
[GIN-debug] POST   /opentsdb/v1/put/telnet/:db --> github.com/taosdata/taosadapter/v3/plugin/opentsdb.(*Plugin).insertTelnet-fm (7 handlers)
12/28 15:25:22.215878 00000030 TAOS_ADAPTER info "init plugin opentsdb_telnet/v1" model=plugin
12/28 15:25:22.217184 00000030 TAOS_ADAPTER info "opentsdb_telnet disabled" model=opentsdb_telnet
12/28 15:25:22.217204 00000030 TAOS_ADAPTER info "init plugin prometheus/v1" model=plugin
[GIN-debug] POST   /prometheus/v1/remote_read/:db --> github.com/taosdata/taosadapter/v3/plugin/prometheus.(*Plugin).Read-fm (7 handlers)
[GIN-debug] POST   /prometheus/v1/remote_write/:db --> github.com/taosdata/taosadapter/v3/plugin/prometheus.(*Plugin).Write-fm (7 handlers)
12/28 15:25:22.217434 00000030 TAOS_ADAPTER info "init plugin statsd/v1" model=plugin
12/28 15:25:22.219673 00000030 TAOS_ADAPTER info "statsd disabled" model=statsd
12/28 15:25:22.219694 00000030 TAOS_ADAPTER info "init plugin collectd/v1" model=plugin
12/28 15:25:22.220619 00000030 TAOS_ADAPTER info "collectd disabled" model=collectd
12/28 15:25:22.220638 00000030 TAOS_ADAPTER info "init plugin influxdb/v1" model=plugin
[GIN-debug] POST   /influxdb/v1/write        --> github.com/taosdata/taosadapter/v3/plugin/influxdb.(*Influxdb).write-fm (7 handlers)
12/28 15:25:22.221345 00000030 TAOS_ADAPTER info "all plugin init finish" model=plugin
12/28 15:25:22.221356 00000030 TAOS_ADAPTER info "all plugin start finish" model=plugin
12/28 15:25:22.221438 00000030 TAOS_ADAPTER info "Running in terminal." model=main
12/28 15:25:22.224164 00000030 TAOS_ADAPTER info "server on : 6041" model=main
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
sysctl: setting key "kernel.core_pattern": Read-only file system
12/28 15:25:27.775965 00000030 TAOS_ADAPTER info "start server:00000030" model=main
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /debug/pprof/             --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/cmdline      --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/profile      --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)
[GIN-debug] POST   /debug/pprof/symbol       --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/symbol       --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/trace        --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/allocs       --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/block        --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/goroutine    --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/heap         --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/mutex        --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/threadcreate --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
[GIN-debug] GET    /metrics                  --> github.com/gin-gonic/gin.WrapH.func1 (5 handlers)
[GIN-debug] GET    /-/ping                   --> github.com/taosdata/taosadapter/v3/controller/ping.Controller.Init.func1 (5 handlers)
[GIN-debug] POST   /rest/sql                 --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).sql-fm (7 handlers)
[GIN-debug] POST   /rest/sql/:db             --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).sql-fm (7 handlers)
[GIN-debug] GET    /rest/login/:user/:password --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).des-fm (6 handlers)
[GIN-debug] GET    /rest/ws                  --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).ws-fm (6 handlers)
[GIN-debug] GET    /rest/stmt                --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).stmt-fm (6 handlers)
[GIN-debug] GET    /rest/tmq                 --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).tmq-fm (6 handlers)
[GIN-debug] POST   /rest/upload              --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).upload-fm (7 handlers)
[GIN-debug] GET    /rest/schemaless          --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).schemalessWs-fm (6 handlers)
[GIN-debug] GET    /rest/vgid                --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).tableVgID-fm (7 handlers)
[GIN-debug] GET    /genauth/:user/:password/:key --> github.com/taosdata/taosadapter/v3/plugin.RegisterGenerateAuth.func1 (5 handlers)
12/28 15:25:27.776687 00000030 TAOS_ADAPTER info "init plugin opentsdb/v1" model=plugin
[GIN-debug] POST   /opentsdb/v1/put/json/:db --> github.com/taosdata/taosadapter/v3/plugin/opentsdb.(*Plugin).insertJson-fm (7 handlers)
[GIN-debug] POST   /opentsdb/v1/put/telnet/:db --> github.com/taosdata/taosadapter/v3/plugin/opentsdb.(*Plugin).insertTelnet-fm (7 handlers)
12/28 15:25:27.776995 00000030 TAOS_ADAPTER info "init plugin opentsdb_telnet/v1" model=plugin
12/28 15:25:27.778245 00000030 TAOS_ADAPTER info "opentsdb_telnet disabled" model=opentsdb_telnet
12/28 15:25:27.778265 00000030 TAOS_ADAPTER info "init plugin prometheus/v1" model=plugin
[GIN-debug] POST   /prometheus/v1/remote_read/:db --> github.com/taosdata/taosadapter/v3/plugin/prometheus.(*Plugin).Read-fm (7 handlers)
[GIN-debug] POST   /prometheus/v1/remote_write/:db --> github.com/taosdata/taosadapter/v3/plugin/prometheus.(*Plugin).Write-fm (7 handlers)
12/28 15:25:27.778505 00000030 TAOS_ADAPTER info "init plugin statsd/v1" model=plugin
12/28 15:25:27.780495 00000030 TAOS_ADAPTER info "statsd disabled" model=statsd
12/28 15:25:27.780531 00000030 TAOS_ADAPTER info "init plugin collectd/v1" model=plugin
12/28 15:25:27.781481 00000030 TAOS_ADAPTER info "collectd disabled" model=collectd
12/28 15:25:27.781500 00000030 TAOS_ADAPTER info "init plugin influxdb/v1" model=plugin
[GIN-debug] POST   /influxdb/v1/write        --> github.com/taosdata/taosadapter/v3/plugin/influxdb.(*Influxdb).write-fm (7 handlers)
12/28 15:25:27.781776 00000030 TAOS_ADAPTER info "init plugin node_exporter/v1" model=plugin
12/28 15:25:27.783714 00000030 TAOS_ADAPTER info "node_exporter disabled" model=NodeExporter
12/28 15:25:27.784076 00000030 TAOS_ADAPTER info "all plugin init finish" model=plugin
12/28 15:25:27.784090 00000030 TAOS_ADAPTER info "all plugin start finish" model=plugin
12/28 15:25:27.784179 00000030 TAOS_ADAPTER info "Running in terminal." model=main
12/28 15:25:27.786812 00000030 TAOS_ADAPTER info "server on : 6041" model=main
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
sysctl: setting key "kernel.core_pattern": Read-only file system
12/28 15:25:31.764307 00000035 TAOS_ADAPTER info "start server:00000035" model=main
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: CentOS 7.9  3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Memory, CPU, current Disk Space
 - TDengine Version 3.0.2.x

**Additional Context**

**Comment by sangshuduo** [comment]
Please re-pull same tag docker image. There is a mistake in the early publishing. Sorry for the inconvenience.
