### ISSUE TITLE
JDBC REST 连接目前不支持无模式写入

### ISSUE THREAD

**Issue by leidachui** [taosdata/TDengine#19227]
我看官方文档说，“JDBC REST 连接目前不支持无模式写入 ”

请问这个预计啥时候可以支持呢？ 在线等

![image](https://user-images.githubusercontent.com/33803494/209808125-dbd45670-45f0-404e-b920-9f4ba0789c4f.png)

因为我们的使用场景，不能事先创建好表，这样的话，用insert sql的方式就没法弄了；
只能用 无模式写入 方式，类似influxdb的那种；

但现在JDBC REST 不支持，只有 jdbc原生方式支持，
而 jdbc原生方式需要 安装libtao.so库，

我们的写入服务是部署在k8s上的，怎么安装 libtao.so库 呢？

所以最好的方式，还是 解决 “JDBC REST 连接目前不支持无模式写入 ” 的问题

**Comment by sangshuduo** [comment]
已在计划中

**Comment by leidachui** [comment]
有大概的时间点吗

**Comment by sangshuduo** [comment]
春节后吧

**Comment by leidachui** [comment]
我目前测试走通了如下流程：

应用以 influxdb v1行协议 写入数据到 kafka；telegraf从kafka读取数据，写入到taoadapter再到tdengine；
telegraf往taoadapter写数据走的是http协议，
为什么这种方式下支持 无模式写入 呢？

按我理解，telegraf是个通用方案，它里面的实现，应该是不会有 tdengine的jdbc的；

感觉很奇怪。

我往kafka写入的数据格式如下：
push_msg_static,reporter_name=push_service,reporter_ip=127.0.0.1,msg_type=1,status=0,err_code=0,push_channel=1 total_count=10,msg_id=10000 1672298536590000000
push_msg_static,reporter_name=push_service,reporter_ip=127.0.0.1,msg_type=1,status=2,err_code=1000,push_channel=1 total_count=0,msg_id=10000 1672298536590000000

**Comment by sangshuduo** [comment]
taosadapter 支持不等于连接器已经支持，各个语言需要做相应框架下的接口封装

**Comment by leidachui** [comment]
所以现在我的测试可以走通，就是因为 taosadapter 支持了 jdbc原生方式 。
如果是这样，那不就相当于 jdbc REST的方式也支持了吗？  因为 jdbc REST的方式本来就是要将数据发给 taosadapter ；

你看下面这个官方架构说明：
![image](https://user-images.githubusercontent.com/33803494/209927128-fc1c1b8d-2afd-4715-98d8-0214f65baa4f.png)

还是 不太理解，望帮忙说明下~

**Comment by sangshuduo** [comment]
taosadapter 是 go 开发的，通过 taosc 的方式支持了无模式写入。java 支持基于 REST/http 的无模式写入需要额外的开发工作

**Comment by leidachui** [comment]
“java 支持基于 REST/http 的无模式写入需要额外的开发工作”
--------
你说的这种，如果开发好了，效果是，

java app -- RestfulDriver -- 直接到 taosd 吗？  -- 效果就是  省去中间的 taosAdapter吗？

**Comment by leidachui** [comment]
刚才试了下，应用直接发 http请求，确实也是可以用 REST/http 的方式的：

![image](https://user-images.githubusercontent.com/33803494/209931687-59bb3f43-62cd-4702-9bb7-9d84208008a0.png)

**Comment by leidachui** [comment]
建议官方文档，能修改文档，重新说明下。。以免他人被误导，

**Comment by sangshuduo** [comment]
> ## “java 支持基于 REST/http 的无模式写入需要额外的开发工作”
> 
> 你说的这种，如果开发好了，效果是，
> 
> java app -- RestfulDriver -- 直接到 taosd 吗？ -- 效果就是 省去中间的 taosAdapter吗？
> 
> 看官网说明，REST/http 却是一定要经过 taosAdapter ![image](https://user-images.githubusercontent.com/33803494/209928407-618ce147-399b-4559-94c1-789bd1de7bbd.png)
> 
> 这样感觉就矛盾了哦
> 
> 再次理解下： 如果开发好了，效果是 taosAdapter 还是需要，但不需要安装 taosc 客户端驱动了，对吧？
> 
> 不过这样的话，我有另外一个问题： 既然要安装taosAdapter ，那再同时安装一个 taosc 客户端驱动，好像也没啥工作量，因为本身就可以一起安装。
> 
> 那感觉“java 支持基于 REST/http 的无模式写入”是不是意义就没那么大了？

不是安装 taosc 工作量的问题，是不同场景的模块部署耦合度
