### ISSUE TITLE
无模式写入指定子表tname时，数据会丢失

### ISSUE THREAD

**Issue by glCoding** [taosdata/TDengine#19229]
![image](https://user-images.githubusercontent.com/20293464/209823643-6dca2ae0-e8e1-466c-ba64-9ee858c07aa6.png)
为SYS_CPU指标准备了两条数据，指定tname=t1
![image](https://user-images.githubusercontent.com/20293464/209823843-5658f3bf-056c-4d56-87b6-fdec96c2a62d.png)
查询超级表只有一条数据
![image](https://user-images.githubusercontent.com/20293464/209823942-a7d39712-4892-49a4-81e0-2be1bfcc5a28.png)
查询子表也只有一条数据

去掉tname时，数据则有两条
![Uploading image.png…]()

**Comment by wangmm0220** [comment]
@glCoding 这是哪个版本？

**Comment by glCoding** [comment]
> @glCoding 这是哪个版本？
TDengine-server-3.0.2.1-Linux-x64.tar.gz

**Comment by wangmm0220** [comment]
@glCoding  这个没有问题，因为如果你指定了tname=t1，那么这两条数据就是一个子表的。这两条数据又是相同时间戳，所以只会保留最新的。   如果没有指定tname=t1，那么两条数据tag不同就是两个子表，相同时间戳没关系，就是两条数据

**Comment by glCoding** [comment]
> 么两条数据tag不同就是两个
我指定了tname, 但是tag不一样，不应该是两条数据数据么？

**Comment by wangmm0220** [comment]
@glCoding tname优先级高，如果你指定了tname的话，说明这两条数据子表名一样，那就是一个子表的数据，会忽略第二条的tag，认为第二条和第一条是一个子表，时间戳又一样，所以只有一条。
文档里也有说明：
![image](https://user-images.githubusercontent.com/6055324/210025800-bb646200-ed84-4194-aa81-34a67afca2d1.png)
