### ISSUE TITLE
TD的count(*)比MySql的count(*)慢10倍

### ISSUE THREAD

**Issue by Fred-fangts** [taosdata/TDengine#19234]
![e1d75f2ce8a4e1ddf5f74262637329c](https://user-images.githubusercontent.com/121590130/209893170-e724d054-ee8b-4fc9-9be1-5f16366113ce.png)

![d9d0d3f1b5b294a844e86daf46b6246](https://user-images.githubusercontent.com/121590130/209893175-577b5234-9126-46d3-a741-1e0ede5768b2.jpg)

具体看图片吧，怎么MYSQL用count（*）怎么比TD块了10来倍

**Comment by yu285** [comment]
我远程看下吧，加我微信 a15652223354

**Comment by yu285** [comment]
经排查：由于多线程产生了大量重复时间戳的数据，写入了相同子表，导致出现了很多更新操作。查询的时候需要加载到内存中很多数据块，导致查询变慢。

可以调整下数据生成的逻辑。
