### ISSUE TITLE
远程无法连接TDengine

### ISSUE THREAD

**Issue by KOM6177** [taosdata/TDengine#19233]
<img width="384" alt="微信图片_20221229094101" src="https://user-images.githubusercontent.com/59348943/209892563-93312113-9e24-42ca-a30c-b7768baee2b9.png">
<img width="611" alt="微信图片_202212290941011" src="https://user-images.githubusercontent.com/59348943/209892567-8dc61272-06dd-4d22-8cc1-ff113d7a3d5e.png">
<img width="438" alt="微信图片_202212290941012" src="https://user-images.githubusercontent.com/59348943/209892568-d57c5f35-43af-4f72-9493-1762aad6dad2.png">
服务端网络和客户端是通的，但是无法连接到服务

**Comment by yu285** [comment]
数据库和gui的版本是？

**Comment by KOM6177** [comment]
![image](https://user-images.githubusercontent.com/59348943/209892725-dd3c7e5f-8c9a-4de5-a112-e6ad8d48d8f3.png)
![image](https://user-images.githubusercontent.com/59348943/209892861-a7cd2552-4f4c-4155-84c5-c31c404a1365.png)
