### ISSUE TITLE
TDengine集群异常

### ISSUE THREAD

**Issue by zhuxiaomming** [taosdata/TDengine#19248]
您好，有个问题麻烦请教一下：
在生产环境下的集群模式，三个节点为hostname依次为 ：cdh-slave2,cdh-slave3,和cdh-slave4
fqdn 为cdh-slave4,   mnode节点和 dnode  节点均为 cdh-salve2,cdh-slave3,cdh-slave4,  qnode 为cdh-slave3;
目前情况是：cdh-slave2 启动正常，但无法对数据库进行操作；cdh-slave3，和cdh-slave4 刚启动后，就自动挂掉，导致集群启动失败；并且三个节点都产生了core文件；
现在问题是：
1.怎么能利用core文件对异常情况进行分析，或者说用什么方法，因为文件太大，无法正常打开，而且乱码；
2.两个异常节点，cdh-slave3,cdh-slave4，通过观察日志，均出现报错：msg:0x7f95a0001090 failed to process since restore not finished, gtid:0xbbc4ad8a7ae2aaf:0x667a15bd8a710374  ，请帮忙分析下是什么原因。
。

**Comment by qiks626** [comment]
我也遇到了类似问题，至今未找到处理办法
