### ISSUE TITLE
时间精度问题 

### ISSUE THREAD

**Issue by caiqiqqq** [taosdata/TDengine#19241]
我有两条数据，数据1 在这个时间点上 2022-12-27 16:16:36.244（1672128996000）  数据2 在这个时间点上 2022-12-27 16:16:36.455 （1672128996000）  用时间戳进行修改的时候，他只会修改第一个 数据   两个时间戳没有区别，导致修改 的时候只会修改第一个
<img width="958" alt="image" src="https://user-images.githubusercontent.com/102867723/209897730-7051f510-e4e6-42ae-934f-a0b6ee0a6e1c.png">

**Comment by caiqiqqq** [comment]
版本 2.6

**Comment by yu285** [comment]
2022-12-27 16:16:36.244（1672128996000）
 
 2022-12-27 16:16:36.455（1672128996000）
 
 这两时间戳都是一样的1672128996000，是不是有一个写错了
