### ISSUE TITLE
client connection issue

### ISSUE THREAD

**Issue by JackAuFull** [taosdata/TDengine#19259]
**Bug Description**
在centos7上安装TDengine Server 3.0.2.2后，防火墙也开启了6030端口；然后在自己win10电脑上安装了TDengine Client 3.0.2.2客户端后，在C:\Windows\system32\drivers\etc\hosts中添加了centos7的内网ip 192.168.1.x h1.tdengine.com，然后C:\TDengine\cfg\taos.cfg文件中配置了firstEp                     h1.tdengine.com:6030，最后打开Taos Shell使用taos命令连接不上。如图所示：
![image](https://user-images.githubusercontent.com/49433691/209925817-fed74cc2-1ff0-4c7f-882a-aff8359bcf40.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/49433691/209925817-fed74cc2-1ff0-4c7f-882a-aff8359bcf40.png)

**Environment (please complete the following information):**
 - OS: CentOS 7.0，win10
 - Memory, CPU, current Disk Space
 - TDengine Version 3.0.2.2

**Comment by yu285** [comment]
可以远程看 微信 a15652223354
