### ISSUE TITLE
schemless 写入报错"[0x61b] Table schema is old"

### ISSUE THREAD

**Issue by sytuacmdyh** [taosdata/TDengine#19254]
**Bug Description**
调用 `/influxdb/v1/write` schemless写入的时候，报错
request:
```
curl --location --request POST '{host}/influxdb/v1/write?db=device_log&precision=ms' \
--data-raw 'device_state_6389ae4a6c0635390e411568,device_id=639932f0f74b69e882aa8a82,sn=7cdfa1e5a398 online=true,p_2_1=T,p_2_2=0u8,p_4_1=44.56315994262695f32,p_2_3=19u8,p_2_4=T,p_4_2=37.733978271484375f32,p_2_5=F,p_4_3=32.09369659423828f32,p_2_6=37u16,p_1_8=0u32,v_1="0001",v_2="xxx" 1671428760835'
```
response:
```
{
    "code": "internal error",
    "message": "[0x61b] Table schema is old"
}
```

**Environment:**
 - OS: [docker]
 - TDengine Version [3.0.2.0]

**Additional Context**
除了无法写入之外，读取这个超级表的数据只有0条，其实应该是有数据的。读取超级表结构和子表结构都可正常返回。

**Comment by wangmm0220** [comment]
@sytuacmdyh  这个错误的意思是client端缓存的表schema和server端不一致了。在client端运行命令reset query cache 清理下client端的缓存再试试。

**Comment by sytuacmdyh** [comment]
我使用taosadapter提供的这个接口`/rest/sql`，执行了`reset query cache`，返回执行成功。

但是问题并没有解决，还是无法写入以及查询数据。

**Comment by yu285** [comment]
重启taosadapter 后还有这个问题么？

**Comment by YiFlower** [comment]
我在使用无模式(InfluxDB Line 协议)写入过程中，也遇到了这个问题。

我是使用SparkStreaming处理Kafka的数据，每个Spark分区建立一个JDBC连接。程序运行开始时，每个分区会报错：`TDengine ERROR (8000061b): Table schema is old`，然后后续的数据可以正常写入；运行过程中，每个分区会间歇性的再次报此错误。

查看taoslog1.0日志文件，里面有大量类似的报错内容：`03/07 10:48:25.912414 00057202 UTL ERROR SML:0xb98 smlInsertLines result, code:0,lineNum:150,stable num:1,ctable num:150,create stable num:0,alter stable tag num:0,alter stable col num:0         parse cost:61883,schema cost:976,bind cost:271335,rpc cost:10958,total cost:345152`

可以协助解决一下吗？

**Comment by sytuacmdyh** [comment]
> 重启taosadapter 后还有这个问题么？

我是用docker运行的，整个重启之后，问题并没有解决。（但是这个问题过去了这么久，更新数据库版本(3.0.2.0)之后，没有继续出现这个问题）
