### ISSUE TITLE
golang多对多的客户端连接服务端的方法

### ISSUE THREAD

**Issue by zhaopengtao-life** [taosdata/TDengine#19251]
1: 多个TD服务端，以集群nginxe配置，生成一个vip的公用ip和端口；
2: 在/etc/taos/taos.cfg，配置了firstEp和secondEp
<img width="497" alt="image" src="https://user-images.githubusercontent.com/44759950/209914685-7ef35a3a-6165-41b2-89d3-721213074ce3.png">

问题1 ：在go的代码实现中，怎么通过这个vip，进行原生链接执行插入和查询
问题2 ：如果存在三个或者四个服务端，是否只需要在配置文件中继续添加fqdn

**Comment by yu285** [comment]
1.在连接时不指定端口和fqdn即可默认使用firstEP和secondEP

2.是的，新客户端只要能确保可以解析fqdn值即可，但是firstEP和secondEP如果有需要也是要写上的，场景如上。
