### ISSUE TITLE
Data file(s) corrupted

### ISSUE THREAD

**Issue by Dawnflying** [taosdata/TDengine#19265]
**Bug Description**
Data file(s) corrupted

**To Reproduce**
do not know when and how it happend.

**Expected Behavior**
can query the specified ts duration.

**Screenshots**
cannot query the specified ts duration.

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version 2.6.0.30
![0ab912cae13ccf04288d28605c4667f](https://user-images.githubusercontent.com/5460921/209957071-0ab0dc2d-1394-4af4-916d-4762357a859d.png)

**Comment by yu285** [comment]
如果是多副本，可以尝试用其他正常的vnode目录做一个替换。
