### ISSUE TITLE
vs2019 安装TDengine.Connector报错

### ISSUE THREAD

**Issue by litong860105** [taosdata/TDengine#19267]
正在尝试收集与目标为“.NETFramework,Version=v4.7.2”的项目“MISSION.Code”有关的包“TDengine.Connector.3.0.1”的依赖项信息
收集依赖项信息花费时间 2.31 sec
正在尝试解析程序包“TDengine.Connector.3.0.1”的依赖项，DependencyBehavior 为“Lowest”
解析依赖项信息花费时间 0 ms
正在解析操作以安装程序包“TDengine.Connector.3.0.1”
已解析操作以安装程序包“TDengine.Connector.3.0.1”
安装失败。正在回滚...
程序包“TDengine.Connector.3.0.1”不存在于项目“MISSION.Code”中
程序包“TDengine.Connector.3.0.1”不存在于文件夹“C:\Users\......\MISSION_LOGS\IOTCloud_new_logs\packages”中
执行 nuget 操作花费时间 3.74 sec
无法安装程序包“TDengine.Connector 3.0.1”。你正在尝试将此程序包安装到目标为“.NETFramework,Version=v4.7.2”的项目中，但该程序包不包含任何与该框架兼容的程序集引用或内容文件。有关详细信息，请联系程序包作者。
已用时间: 00:00:09.9391675
========== 已完成 ==========

**Comment by xleili** [comment]
![image](https://user-images.githubusercontent.com/85657333/210027928-a8a561f8-bd99-4246-90bf-65e85bcd5143.png)
这个版本是不兼容 .Net Framework 的

下个版本会支持。
使用最新的3.0分支代码，已经支持的 .NET Framework.

**Comment by litong860105** [comment]
能提供一个3.0分支代码的下载链接吗？

**Comment by litong860105** [comment]
下一个支持.Net Framework的版本预计什么时间会发布呢？

**Comment by xleili** [comment]
> 下一个支持.Net Framework的版本预计什么时间会发布呢？

最近几天会发布。

**Comment by xleili** [comment]
> 能提供一个3.0分支代码的下载链接吗？

https://github.com/taosdata/taos-connector-dotnet
![image](https://user-images.githubusercontent.com/85657333/212034009-2bb99d1e-e8e2-48ce-aa2a-fc25e3f53c5b.png)
