### ISSUE TITLE
Update taostools 2.4.0 failed

### ISSUE THREAD

**Issue by darrenji** [taosdata/TDengine#19274]
**Bug Description**
When I check the latest version of taosdump(taostools 2.4.0).  It gives error: 

```
taosdump: error while loading shared libraries: libtaosws.so: cannot open shared object file: No such file or directory
```
**To Reproduce**

On Ubuntu 18.04. 

The reason why I want to  update the version of taostools to 2.4.0 is that I want to use the latest taosdump. 

Check the current version of taosdump: 
```
taosdump --version
2.2.6
```

Uninstall taostools. 
```
sudo dpkg -P taostools
```

Check if taostools has been uninstalled.
```
sudo dpkg -l taostools
```
![2](https://user-images.githubusercontent.com/2604576/210028955-e0579a5d-c3b5-425d-95bf-bd9c37414c1f.png)

Install the latest taostools.
```
sudo dpkg -i taosTools-2.4.0-Linux-x64.deb
```
It seems like the process is not fully completed.
![3](https://user-images.githubusercontent.com/2604576/210029033-cf758641-ee0e-4431-98e8-2ad1ef277dcf.png)

Check if taostools has been installed.
```
sudo dpkg -l taostools
```
![4](https://user-images.githubusercontent.com/2604576/210029098-b6177bb1-2c4d-4a73-a53b-90925abaa3ab.png)

Check the  version of taosdump.
```
taosdump --version
```
![5](https://user-images.githubusercontent.com/2604576/210029177-8a9fd806-9cc7-49b7-961a-9138f82e8759.png)

Maybe something is wrong with the dynamic linker. I use below command:
```
sudo /sbin/ldconfig -v
```
Check the version of taosdump again. Problem still exists. 

Try to find the `libtaosws.so`.
```
sudo find /usr/bin libtaosws.so
sudo find /usr/local/taos libtaosws.so
```

Can't find the `libtaosws.so`.

![6](https://user-images.githubusercontent.com/2604576/210029326-2bda9e3f-273c-437b-803a-1c1f5dd219dc.png)

![7](https://user-images.githubusercontent.com/2604576/210029338-95a1cdad-55c2-4686-9cda-45e6e2e3e36d.png)

**Comment by sangshuduo** [comment]
2.x TDengine 需要装对应页面的安装包，之前是可以兼容的，后来 3.0 支持了 websocket 就不兼容了，计划用 loadlibrary 的方式解决，暂时还只能装和 TDengine 对应的版本

**Comment by darrenji** [comment]
谢谢。对于3.0以后的版本，先装TDengine版本，再装与之对应的taostools版本，至少在启用 loadlibrary 的方式之前是这样。
