### ISSUE TITLE
通过csv文件写入后查询数据量跟写入的数据量不一致

### ISSUE THREAD

**Issue by hb407033** [taosdata/TDengine#19276]
TDEngine：  2.6
通过shell写入3个数据文件， 执行结果显示写入3千万行，但最终count查询只有100万行
![image](https://user-images.githubusercontent.com/10432196/210034529-8aaf06cd-47a2-4610-b89c-a3a0113b2367.png)

![image](https://user-images.githubusercontent.com/10432196/210034590-c3cfbbc8-7773-4f86-98cd-84b8bd00f59a.png)

**Comment by yu285** [comment]
请检查是否有相同时间戳的数据

**Comment by hb407033** [comment]
确实是时间戳有些没有ms，导致时间重复
