### ISSUE TITLE
创建流时，不想以_wstart为时间主键，自己构建时间索引不成功且报错

### ISSUE THREAD

**Issue by zhouzhou98** [taosdata/TDengine#19286]
创建流语句'create stream if not exists test_stream_12 into test_stream.stable_test_11 as select last(ts), id, parttime, last(current) from test_stream.meters_test where parttime = "2022-12-30" partition by id interval(1d)' 其中想以ts作为时间索引，ts为 test_stream.meters_test 时间主键timestamp，结果报错No valid function in window query

**Comment by cosmic-jc** [comment]
select 里面去掉parttime试试
