### ISSUE TITLE
taos-jdbcdriver2.0.34版本空指针异常问题

### ISSUE THREAD

**Issue by garrycode** [taosdata/TDengine#19283]
![ca0701e7e0ea768229b863a6aa2b658](https://user-images.githubusercontent.com/32251959/210042325-da2cc249-ed73-4145-b1ab-6495b8d862e9.png)
这里有可能报空指针，拿到的status为null。
http://localhost:6041/rest/login/root/taosdata
返回：{"code":0,"desc":"/KfeAzX/f9na8qdtNZmtONryp201ma04bEl8LcvLUd7a8qdtNZmtONryp201ma04"}

**Comment by huolibo** [comment]
在 jdbc 与 taosAdapter 之间增加了网关吗？返回的 JSON 信息与设计不符。

**Comment by garrycode** [comment]
> 在 jdbc 与 taosAdapter 之间增加了网关吗？返回的 JSON 信息与设计不符。
没有，大概情况是这样：1.使用docker安装的tdengine  2.本地使用数据库连接工具可以连接数据库  3.使用官网的springbootdemo本地启动（使用rest连接）起不来，因为这里报空指针。loginUrl为：http://localhost:6041/rest/login/root/taosdata
