### ISSUE TITLE
all streams stopped working for no reason

### ISSUE THREAD

**Issue by ak82091157** [taosdata/TDengine#19282]
all streams stop working at one time for no reason;

one of the stream create sql is:
`CREATE STREAM IF NOT EXISTS cq_action_info_1m_s TRIGGER WINDOW_CLOSE into cq_action_info_1m SUBTABLE(CONCAT('cai1_', tbname)) AS 
    SELECT 
        _wstart as _ts, avg(ave_time_top) as ave_time_top, avg(average_time) as average_time, max(handle_now_count) as handle_now_count,
        max(last_time) as last_time, max(max_time_top) as max_time_top, max(p_error_rate) as p_error_rate,
        max(profession_error) as profession_error, max(req_count) as req_count, max(req_second_count) as req_second_count,
        max(total_time) as total_time, max(unusual_count) as unusual_count, action, action_name, host, `port`, shelltype
    FROM zzdb.action_info PARTITION BY action, action_name, host, `port`, shelltype INTERVAL(1m);`

some system information is as follows:
TDengine version: 3.0.2.2
show dnodes:
![QQ截图20221230143047](https://user-images.githubusercontent.com/9837528/210041437-3119e4e4-948a-448b-b803-c4c29ce2e53d.png)
streams:
![QQ截图20221230143227](https://user-images.githubusercontent.com/9837528/210041549-04c800fe-5abd-4d85-9126-90496b6a2004.png)

**Comment by yu285** [comment]
您说的停止是指只能写入几条数据，后面即使新数据进来也不再写入了是吗

**Comment by ak82091157** [comment]
是的，但是我不确定最后一次写入的结果是否完整；
这是我最新的查询结果，其仍然停在30日，不知道是否有本地日志文件可供查询原因：
![QQ截图20230103110637](https://user-images.githubusercontent.com/9837528/210295510-1609d84a-09bf-4672-ba22-479c7b9b0f7a.png)

**Comment by onlyshow** [comment]
Client Version:3.0.2.1 也遇到了这个问题，重启后流式计算失效，无报错

**Comment by feiyangbeyond** [comment]
@yu285 我也遇到了这个问题，有什么最新的进展吗？

**Comment by yu285** [comment]
流计算经过几轮重构优化已经没什么问题了，而且3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
