### ISSUE TITLE
vgroups has no leader

### ISSUE THREAD

**Issue by a188** [taosdata/TDengine#19288]
**Bug Description**
在三台服务器上部署了 3 个 dnode 的集群，`show dnodes;`显示三个节点都已经是 `ready`状态，然后通过`create database test replica 3;`创建了一个数据库 `test`，但是 `show test.vgroups;`却显示节点都处于 `follower` 或者 `candidate`的状态，一直没有 `leader`。

**Screenshots**
![image](https://user-images.githubusercontent.com/52406068/210048309-06187acd-b4cf-4efd-a1db-69b379faaf77.png)

**Environment (please complete the following information):**
 - OS: Debian
 - TDengine Version: 3.0.2.2

**Comment by yu285** [comment]
we will check on this

**Comment by yu285** [comment]
hosts 配置问题。需要：

用这样的格式，写在所有节点的/etc/hosts里面

内网ip  mm02

内网ip  mm03

内网ip  mm04
