### ISSUE TITLE
Link error while build my own C source code which depends on taos windows lib v3.0 

### ISSUE THREAD

**Issue by DianaZhao** [taosdata/TDengine#19303]
While build my C code which calls taos lib, I got such a link error:
stmt.c.obj : error LNK2019: unresolved external symbol taos_data_type referenced in function stmt_describe_col

In my source  
#include <taos.h>

then some code calls taos_data_type which declared in taos.h
default: stmt_append_err_format(stmt, "HY000", 0,
                                        "General error:`%s[%d]` for Column `%s[#%d]` not implemented yet",
                                        taos_data_type(p->type), p->type, p->name, ColumnNumber);

I have added taos.lib in my cmake file
add_library(taos_odbc_driver SHARED
        "taos_odbc_driver.c"
        "core/env.c"
        "core/conn.c"
        "core/stmt.c"
        "core/enums.c"
        "core/errs.c"
        "core/desc.c"
        "core/utils.c"
        "core/strptime.c")
target_link_libraries(taos_odbc_driver
        pthread
        iconv
        ${TD_LIB_DIR}/taos.lib
        ${PLATFORM_DEPENDENCIES}
        ${ODBC_LIBS}
        ${ODBC_INSTLIBS})

other dependencies to taos lib looks good, but taos_data_type rises that error
Is that problem caused by my wrongly use of that lib, or by some bugs in that lib? I am not sure. who can help me?

**Comment by freemine** [comment]
please follow instructions detailed in README.md https://github.com/freemine/taos_odbc.
BTW, better build and install tdengine yourself before building taos-odbc.

**Comment by freemine** [comment]
And according to the linking problem stated in your issue, it seems you have to git clone the latest version of tdengine, better 3.0.2.1  or above. Because taos-data-type was not exported until recently uodate of tdengine.

**Comment by freemine** [comment]
Seems like you are 'branching' your own version of taos-odbc，but not the original https://github.com/freemine/taos_odbc?

**Comment by DianaZhao** [comment]
I am building a windows version of odbc driver, while mainly using your codes with some modifications. I noticed that taos.dll does not export taos_data_type, that maybe the cause. I will implement that function by mysqlf.

**Comment by DianaZhao** [comment]
It is done, thx
