### ISSUE TITLE
taosd crash during insert ,and can't be restarted

### ISSUE THREAD

**Issue by mark03** [taosdata/TDengine#19306]
**Bug Description**
写入数据（约不到100亿条）途中，taosd进程有概率挂掉，且使用
`systemctl restart taosd`
无法重启

**To Reproduce**
一直写入，不是稳定复现，有概率

**Expected Behavior**
可以重启服务，不要crash

**Screenshots**
![image](https://user-images.githubusercontent.com/14867856/210213695-81e77faf-063a-4d6e-8644-357115f65511.png)

**Environment (please complete the following information):**
 - OS: Ubuntu22.04 on WSL
 - Memory 24GB, CPU AMD 5800X, Disk 500GB
 - TDengine Version 
 ```
community version: 3.0.2.2 compatible_version: 3.0.0.0
gitinfo: c09602bcde83fbaba1d9bb29ab53f474ec0607b5
buildInfo: Built at 2022-12-28 15:31
```

手动运行taosd，输出如下内容
[taosd.log](https://github.com/taosdata/TDengine/files/10330814/taosd.log)

**Comment by yu285** [comment]
可以加微信 a15652223354 做具体排查
