### ISSUE TITLE
3.0.2.2 windows版本客户端登录异常问题

### ISSUE THREAD

**Issue by yantailong** [taosdata/TDengine#19315]
环境： windows , 服务器在节点tdnode1上，客户端在其它机器上。
通过终端登录失败，提示如下：
C:\Users\Administrator>taos -h tdnode1 -u root -p
Enter password: Welcome to the TDengine Command Line Interface, Client Version:3.0.2.2
Copyright (c) 2022 by TDengine, all rights reserved.

Failed to check Server Edition, Reason:0x80000020:some vnode/qnode/mnode(s) out of service

客户端taos.cfg修改如下：
firstEp                   tdnode1:6030
fqdn                      tdnode1
请帮忙看看哪儿还需要修改

**Comment by yantailong** [comment]
在服务器主机上的hosts中添加节点名 关联IP ，客户端就可以使用了。是自己配置的问题

**Comment by great-linux** [comment]
> 在服务器主机上的hosts中添加节点名 关联IP ，客户端就可以使用了。是自己配置的问题

求助求助，遇到了相同的问题一直没能解决，可以说的再详细一点么？服务端那边的设置。拜托了。
