### ISSUE TITLE
2.6  last(*)  query sometimes fast and sometimes slow

### ISSUE THREAD

**Issue by caiqiqqq** [taosdata/TDengine#19316]
select last(*) from s_1665200957429_1615173626308;

![image](https://user-images.githubusercontent.com/102867723/210294503-b8b30506-3158-4932-90d6-cf3b04d6299c.png)

帮忙看看一看，数据量有11w条

**Comment by yu285** [comment]
服务器资源有压力么

**Comment by caiqiqqq** [comment]
没有压力

**Comment by caiqiqqq** [comment]
> 服务器资源有压力么


没有压力

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/

如果还有具体的使用问题，可以加微信：a15652223354
