### ISSUE TITLE
数据库查询，字段值异常问题

### ISSUE THREAD

**Issue by lowe00** [taosdata/TDengine#19314]
环境：3台集群部署，平均秒级并发200，STABLE和TABLE结构存储
TD版本：3.0.2.0
---数据查询---
场景1：查询3点-3点40分数据，其中一条数据出现数据不完整情况
select ts,metrics,metrics_values from test where ts >= '2023-01-01 03:00:00' and ts < '2023-01-01 03:40:00';
![image](https://user-images.githubusercontent.com/33248806/210291564-b9abf402-1230-4611-b03f-2663e808c279.png)
场景2：查询3点-3点40分数据，加order by ts，该条数据同样异常
select ts,metrics,metrics_values from test where ts >= '2023-01-01 03:00:00' and ts < '2023-01-01 03:40:00' order by ts
![image](https://user-images.githubusercontent.com/33248806/210291647-e9937a74-dd5a-47c0-80b1-4e94bf5a4f1b.png)
场景3：查询3点-3点40分数据，加order by ts desc，该条数据正常
select ts,metrics,metrics_values from test where ts >= '2023-01-01 03:00:00' and ts < '2023-01-01 03:40:00' order by ts desc
![image](https://user-images.githubusercontent.com/33248806/210291757-0c8d4868-7576-4d14-ab95-142e65c14076.png)

该问题在TD 2.6版本中没有出现，近期升级到3.0.2.0才发现此问题

**Comment by yu285** [comment]
hello ，这个问题还在么，有我微信的话，我们可以跟进下。

a15652223354

**Comment by lowe00** [comment]
> hello ，这个问题还在么，有我微信的话，我们可以跟进下。
> 
> a15652223354

今天我在回归测试这个问题，版本时3.0.2.5，如果还存在我在微信里和你沟通
