### ISSUE TITLE
tdengine 集群环境异常

### ISSUE THREAD

**Issue by sanliang125** [taosdata/TDengine#19320]
**Bug Description**
 当我在基于tdengine 3.0.1.0社区版的集群服务上操作时，系统出现了以下异常日志,同时服务出现了使用异常的情况。tdengine的各项配置都使用的是默认值没有什么修改。
异常日志：
1. `RPC ERROR DND-S conn 0xfffd....  read invalid packet,received from xxx。`
![image](https://user-images.githubusercontent.com/29949952/210295846-d6ec53d3-48d4-47eb-9883-74ed839dd9fd.png)

2.  不断打印的`wal version reset from index`日志
![微信图片_20230103110928](https://user-images.githubusercontent.com/29949952/210295722-72fd6ae1-c723-4ca4-9d9d-4664a5b95279.jpg)

异常情况：
1. 日志不断的增加
2. 有多个超大的core.xxx文件
3. show tables 命令出现：`DB error: Unable to establish connection` 信息，且该指令操作使用失败。
4. 创建超级表命令出现: `DB error: Sync not ready for propose`。

**Expected Behavior**
期望能定位到是什么原因造成的这种服务不可用的异常情况，有什么方法可以避免这些异常出现。

**Environment (please complete the following information):**
 - OS: kylin
 - Memory : 4G, CPU: 4C, current Disk Space:50G
 - TDengine Version :  3.0.1.0

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
