### ISSUE TITLE
关于日志问题，请问如何限制日志文件大小或者关闭日志打印 版本3.0.2.0

### ISSUE THREAD

**Issue by dazzulay** [taosdata/TDengine#19328]
现在插入了2G多的数据，但是日志文件夹高达12G，发现一堆如下的信息

01/03 15:40:41.358932 00014830 UTL ERROR SML:0x1f88759 smlInsertLines result, code:0,lineNum:1,stable num:1,ctable num:1,create stable num:0,alter stable tag num:0,alter stable col num:0         parse cost:49,schema cost:32,bind cost:43,rpc cost:1126,total cost:1250
01/03 15:40:41.359436 00014831 UTL ERROR SML:0x1f8875a smlInsertLines result, code:0,lineNum:1,stable num:1,ctable num:1,create stable num:0,alter stable tag num:0,alter stable col num:0         parse cost:48,schema cost:40,bind cost:55,rpc cost:316,total cost:459
01/03 15:40:41.360779 00014834 UTL ERROR SML:0x1f8875b smlInsertLines result, code:0,lineNum:1,stable num:1,ctable num:1,create stable num:0,alter stable tag num:0,alter stable col num:0         parse cost:142,schema cost:49,bind cost:51,rpc cost:798,total cost:1040

我是使用go的InfluxDBInsertLines插入的，都是成功插入的，但是日志写了ERROR。
请问如何限制日志文件大小或者关闭日志打印？

**Comment by yu285** [comment]
具体是哪个日志大？ taosdlog 还是taoslog大，还是taosadapter的

可以加微信远程看下：a15652223354

**Comment by dazzulay** [comment]
> 具体是哪个日志大？ taosdlog 还是taoslog大，还是taosadapter的
> 
> 可以加微信远程看下：a15652223354

是taoslog

**Comment by yu285** [comment]
logKeepdays    0 

numofLogLines 调低
