### ISSUE TITLE
使用linux客户端3.0.2.0和数据库3.0.2.0，驱动使用taos-driver-3.0.3，jdk1.8的版本，执行sql查询时 造成jdk崩溃。 

### ISSUE THREAD

**Issue by linser2015** [taosdata/TDengine#19332]
**Bug Description**
使用linux客户端3.0.2.0和数据库3.0.2.0，驱动使用taos-driver-3.0.3，jdk1.8的版本

**To Reproduce**
使用客户端能够连接涛思数据库 并且能够正常查询。 但是在程序中使用会造成jdk崩溃。 

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

执行gdb tao   core文件后  

![664f13d4e6d7a7ff56418cd92044321](https://user-images.githubusercontent.com/12657856/210319050-bb305c69-64a3-4cc7-83e9-b7b8a2bd25cb.png)

**Comment by linser2015** [comment]
![fea1b35b35773ea81ef3a46987563f3](https://user-images.githubusercontent.com/12657856/210319309-c1a5ab93-2deb-41ef-a0b2-bbe2a5e5e4c8.png)
执行gdb tao core文件后  上半部分的日志。

**Comment by linser2015** [comment]
![image](https://user-images.githubusercontent.com/12657856/210498945-bd3b3553-8ad5-4e29-a857-1e3a0fce6d52.png)
这还是我们控制台给的日志。    

代码使用了prepareStatement
![image](https://user-images.githubusercontent.com/12657856/210499153-b1144cc1-8498-4931-8d3d-2a97c303c160.png)


一个简单的sql 。  select * from  table  limit 1 offset 5   类似这样

**Comment by sangshuduo** [comment]
> ![image](https://user-images.githubusercontent.com/12657856/210498945-bd3b3553-8ad5-4e29-a857-1e3a0fce6d52.png) 这还是我们控制台给的日志。
> 
> 代码使用了prepareStatement ![image](https://user-images.githubusercontent.com/12657856/210499153-b1144cc1-8498-4931-8d3d-2a97c303c160.png)
> 
> 一个简单的sql 。 select * from table limit 1 offset 5 类似这样

能否提供最少量完整可以重现问题的文本格式代码？这种截图我们没法验证调试

**Comment by sangshuduo** [comment]
建议基于官方示例代码介绍重现方法： https://github.com/taosdata/TDengine/tree/main/examples/JDBC

**Comment by linser2015** [comment]
> 建议基于官方示例代码介绍重现方法： https://github.com/taosdata/TDengine/tree/main/examples/JDBC


@sangshuduo    没找到有支持？ 占位符 。。动态传参的离职 。。是不是不支持呢？

**Comment by linser2015** [comment]
高版本的驱动 中 未出现此bug。 应该是已经解决了
