### ISSUE TITLE
taosadapter.toml中修改pool配置项maxconnect=30后未生效

### ISSUE THREAD

**Issue by aijingaiyi** [taosdata/TDengine#19331]
**Performance Issue** 
Any questions related to TDengine's performance can be discussed here.

**Problem Description** 
A clear and concise description of what the problem is.

**To Reproduce**
1. Database parameters used: 
 ```show databases```
2. Verbs used: Insert/Import/Select?
3. Describe the total amount of data
4. Observed performance vs. expected performance

**Screenshots**

**Environment (please complete the following information):**

* OS: [e.g. CentOS 7.0]
* Memory, CPU, current Disk Space
* TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by aijingaiyi** [comment]
java 使用restful 连接 taosdb 插入数据， 设置taosadapter.toml 中 pool配置项下的maxconnect=30，不生效，单个连接池最大连接数依然为20，且 maxIdle配置和idleTimeout配置需要与maxConnect配置同时打开，否则连接时会报错： error "connect taosd error" model=restful sessionID=6 error=invalid capacity settings

**Comment by ligai322** [comment]
问题解决了没有，我也遇到了同样的问题，怎么啥都没说就直接关闭了

**Comment by aijingaiyi** [comment]
那是很久之前的版本了，新版本还没解决？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年6月7日(周六) 下午4:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [taosdata/TDengine] taosadapter.toml中修改pool配置项maxconnect=30后未生效 (Issue #19331)


ligai322 left a comment (taosdata/TDengine#19331)
 
问题解决了没有，我也遇到了同样的问题，怎么啥都没说就直接关闭了
