### ISSUE TITLE
3.0.1.4版本使用“流式计算”清洗数据出现了一些语法问题

### ISSUE THREAD

**Issue by 13196789316** [taosdata/TDengine#19343]
1、建表语句
`-- 客户数据超级表
create stable db_data_tracking.t_user_data_report (ts timestamp, user_id nchar(64), user_name nchar(64), user_mobile nchar(16),
    user_age int, user_gender int, user_email nchar(64), user_wx_openid nchar(64), user_wx_unionid nchar(64))tags(app_id bigint)
    COMMENT '客户数据超级表';`

`alter table db_data_tracking.t_user_data_report  add column role nchar(64);
alter table db_data_tracking.t_user_data_report  add column degree_of_education nchar(64);
ALTER table db_data_tracking.t_user_data_report add column tenant_id bigint;`

2、最初想按角色group by，并按user_id去重，提示语法错误
`CREATE STREAM user_data_role_statistic_stream INTO user_data_role_statistic as
select  _wstart, count(*)as quantity, tenant_id, role from (select distinct user_id as user_id, tenant_id, role from t_user_data_report
where role is not null) group by tenant_id, role interval (1d);`

3、于是退而求其次，只按照用户id清洗一下数据：
`CREATE STREAM user_data_role_clean_stream INTO user_data_role_clean as
select distinct user_id, tenant_id, role, app_id from t_user_data_report
where role is not null interval(1m);`
提示错误：
`No valid function in window query`

**Comment by yu285** [comment]
select distinct user_id, tenant_id, role, app_id from t_user_data_report where role is not null interval(1m)

这个查询本身应该就会报错，你在数据库shell 里跑一下。
