### ISSUE TITLE
taosdump 3.0.1.4版本导出数据，导入新安装的3.0.2.2版本报错

### ISSUE THREAD

**Issue by zhouhongfei1988** [taosdata/TDengine#19352]
![图片](https://user-images.githubusercontent.com/121913330/210470793-faa11d4d-71e9-4f2f-b0d3-875f0266b3ed.png)
原来是3.0.1.4版本导出数据，导入新安装的3.0.2.2版本报错如图

**Comment by zhouhongfei1988** [comment]
都是CentOS Linux release 7.7.1908版本下的，就是原来3.0.1.4版本导出，后面把3.0.1.4卸载了，在原来服务器上装3.0.2.2版本，在导入

**Comment by yu285** [comment]
taosdump --version

**Comment by zhouhongfei1988** [comment]
taosdump version 2.4.0, commit: 1747390

**Comment by sangshuduo** [comment]
taosdump 导入命令后面加上 -g 2>&1 | tee out.txt ，然后把 out.txt 文件附在评论里我看一下

**Comment by zhouhongfei1988** [comment]
不好上传文件

**Comment by sangshuduo** [comment]
> ![图片](https://user-images.githubusercontent.com/121913330/210476858-7901fbd7-64e4-492b-abaf-f168dc5a33d0.png)

需要更早的出错信息，现在的信息对排查问题没有帮助

**Comment by sangshuduo** [comment]
上传文件拖放即可，out.txt 可以先 zip 压缩一下

**Comment by zhouhongfei1988** [comment]
[out.zip](https://github.com/taosdata/TDengine/files/10341260/out.zip)

**Comment by sangshuduo** [comment]
![image](https://user-images.githubusercontent.com/825729/210482461-3bb64509-5df2-4571-ad64-057988de723d.png)
从错误输出看是内存不够

**Comment by zhouhongfei1988** [comment]
怎么控制内存，一台就有20G内存，要设置什么参数

**Comment by sangshuduo** [comment]
> 怎么控制内存，一台就有20G内存，要设置什么参数

一共多少个db？多少个超级表？多少个子表？中间过程可以用 top 监控一下看是不是确实是内存不足，可以把 taoslog 打包上传我们分析一下
