### ISSUE TITLE
last 函数查询问题

### ISSUE THREAD

**Issue by caiqiqqq** [taosdata/TDengine#19351]
版本2.6
我这2023-01-03 18:44:24.000 已经全部有值了，为什么今天查last 的时候 又有空的情况呢

![image](https://user-images.githubusercontent.com/102867723/210468925-3b3e404a-b11e-4b1a-a94f-30cd0705b8e6.png)

**Comment by yu285** [comment]
请更新到2.6.0.34 ，如果有问题我来远程看下
