### ISSUE TITLE
3.0.2.2单机版部署运行1小时后无法提交insert语句

### ISSUE THREAD

**Issue by longshirong2019** [taosdata/TDengine#19367]
安装环境：centos7.9
TD版本：3.0.2.2
单机部署，taos.cfg配置参数如下
<img width="521" alt="a05f565e73dd15d7a78f36c7ec707a9" src="https://user-images.githubusercontent.com/48143825/210526558-72559aa2-3880-44b3-94a3-6ad9bd8969d2.png">

另外我参照2.6版本配了一个文件：{$TAOS_HOME}/dnode/dnodeEPs.json，不配这个文件客户端连接的时候会报错：unable to establish connection
<img width="243" alt="d2847687bf143ffdffdb029bf49679d" src="https://user-images.githubusercontent.com/48143825/210526701-699f750a-c898-4a35-911d-4654b399609b.png">

建库语句：
CREATE DATABASE digi_iot KEEP 36500 DURATION 10 BUFFER 16 WAL_LEVEL 1;

【故障描述】
运行1小时左右，系统就不能正常插入数据，提交的insert into语句会无限等待没有响应，重启taosd服务后运行1小时左右又会出现上述问题。查看日志文件：
<img width="639" alt="0dca8bb4304a461608566ccf4f7a82e" src="https://user-images.githubusercontent.com/48143825/210526861-b2b7b422-5263-4641-8973-dd72af95bbe7.png">

3.0.x几个版本我都试过，都会出现这种现象，但在2.6.x上没有遇到过

**Comment by yu285** [comment]
可以加微信 a15652223354 做具体的排查

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
