### ISSUE TITLE
/var/lib/taos/vnode/vnode2/wal/中的配置文件如何配置

### ISSUE THREAD

**Issue by hw1986232** [taosdata/TDengine#19374]
您好：
 我使用的3.0的TD。现在发现/var/lib/taos/vnode/vnode2/wal/下边生成了大量的0000000.log，非常占用空间。应该怎么配置该日志文件，并且如何清理该文件呢？请解答一下谢谢了。

**Comment by yu285** [comment]
![image](https://user-images.githubusercontent.com/74105241/210683395-1a7c4fc6-684e-434c-ac3c-65cfa6ee0357.png)

可以调整这几个参数的值，不过暂时不支持热更

<img width="733" alt="image" src="https://user-images.githubusercontent.com/74105241/210683377-eab87e0b-0071-4e16-b3df-5df52caae2cd.png">

**Comment by yu285** [comment]
初始版本，建议替换到 3.0.2.4。
