### ISSUE TITLE
K8s 环境中 tdengine 重启 dnode 节点名称发生改变导致无法正常启动

### ISSUE THREAD

**Issue by phil-guo** [taosdata/TDengine#19379]
我现在遇到在k8s 环境中 tdengien 由于某些原因导致 tdengine所在的pod重启，无法正常启动，报错误
![c44d91046752ac18c2a57311f4af584](https://user-images.githubusercontent.com/14214355/210693351-e32dc78d-1209-455b-b203-eebb52b12b02.png)
，这个只能手动物理删除dnode这个配置吗？可以配置的时候不用pod的名称吗？因为pod的名称只要重启了就会发生改变

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
