### ISSUE TITLE
To drop consumer with lost status is always failed

### ISSUE THREAD

**Issue by grandryxu** [taosdata/TDengine#19378]
**Bug Description**
删除状态是lost的consumer，提示Drop Ok，但是再查询的时候这些consumer数据还在，如果在执行删除，就提示”Subcribe not exist“，但查询数据依然没删除。

**To Reproduce**
1. 执行查询show consumers
![111](https://user-images.githubusercontent.com/12673210/210688878-9ea9e94d-39b0-46cd-beb5-4b92fa659ae5.png)
2,删除groupid是”group_1“的consumer
![222](https://user-images.githubusercontent.com/12673210/210689073-c1e79b96-9b68-433a-b485-86316483e9f0.png)
这个提示因为在提issue之前删除过，这里提示”Subcribe not exist“。
3. 再执行查询show consumers
![333](https://user-images.githubusercontent.com/12673210/210689268-d67c8940-64c0-4b58-8e84-c948b021479c.png)
这些数据依然还存在
4. 删除其他groupid 的数据执行结果一样，先提示”Drop Ok“，但是查询的时候数据没删除，再执行drop命令，就提示”Subcribe not exist“，其实对应的数据还存在。

**Expected Behavior**
能正常删除

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Debian]
 - Memory, CPU, current Disk Space
 - TDengine Version [3.0.2.2]

**Additional Context**

**Comment by yu285** [comment]
收到 我们看下

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
