### ISSUE TITLE
10万台设备压到10亿数据量服务就启不来了

### ISSUE THREAD

**Issue by keephunny** [taosdata/TDengine#19377]
**Bug Description**

**To Reproduce**
2. Type in '....'
3. See error
[root@platform-iot vnode]# du -h --max-dept=1
17G	./vnode2
17G	./vnode3
33G	.

**Expected Behavior**
[root@platform-iot vnode]# systemctl status taosd
● taosd.service - TDengine server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Thu 2023-01-05 10:27:49 CST; 6min ago
  Process: 4167 ExecStart=/usr/bin/taosd (code=killed, signal=ABRT)
  Process: 4158 ExecStartPre=/usr/local/taos/bin/startPre.sh (code=exited, status=0/SUCCESS)
 Main PID: 4167 (code=killed, signal=ABRT)

Jan 05 10:27:49 platform-iot systemd[1]: taosd.service: main process exited, code=killed, status=6/ABRT
Jan 05 10:27:49 platform-iot systemd[1]: Unit taosd.service entered failed state.
Jan 05 10:27:49 platform-iot systemd[1]: taosd.service failed.
Jan 05 10:27:49 platform-iot systemd[1]: taosd.service holdoff time over, scheduling restart.
Jan 05 10:27:49 platform-iot systemd[1]: Stopped TDengine server service.
Jan 05 10:27:49 platform-iot systemd[1]: start request repeated too quickly for taosd.service
Jan 05 10:27:49 platform-iot systemd[1]: Failed to start TDengine server service.
Jan 05 10:27:49 platform-iot systemd[1]: Unit taosd.service entered failed state.
Jan 05 10:27:49 platform-iot systemd[1]: taosd.service failed.

01/05 09:57:02.004677 00030039 SYN ERROR vgId:2, timer wal snapshot end error since:No space left on device, sync:leader, term:6, commit-index:324919355, first-ver:324906891, last-ver:324919355, min:-1, snap:324888758, snap-term:5, elect-times:0, as-leader-times:1, cfg-ch-times:0, hit:0, mis:0, hb-slow:0, hbr-slow:0, aq-items:0, snaping:324914889, replicas:1, last-cfg:-1, chging:0, restore:1, quorum:1, elect-lc-timer:1, hb:0, {0:-1 0}, {r-num:1, my:0, platform-iot:6030}, hb:{0:1672883659960}, hbr:{0:1672883659960}
01/05 09:57:02.069635 00030038 SYN ERROR vgId:3, timer wal snapshot end error since:No space left on device, sync:leader, term:6, commit-index:322428272, first-ver:322414682, last-ver:322428272, min:-1, snap:322396632, snap-term:5, elect-times:0, as-leader-times:1, cfg-ch-times:0, hit:0, mis:1, hb-slow:0, hbr-slow:0, aq-items:0, snaping:322422460, replicas:1, last-cfg:-1, chging:0, restore:1, quorum:1, elect-lc-timer:1, hb:0, {0:-1 0}, {r-num:1, my:0, platform-iot:6030}, hb:{0:1672883659956}, hbr:{0:1672883659956}
01/05 09:57:07.004634 00030039 SYN ERROR vgId:2, timer wal snapshot end error since:No space left on device, sync:leader, term:6, commit-index:324919355, first-ver:324906891, last-ver:324919355, min:-1, snap:324888758, snap-term:5, elect-times:0, as-leader-times:1, cfg-ch-times:0, hit:0,01/05 10:11:43.093219 00030026 MND start to write sdb file, apply index:1073 term:6 config:-1, commit index:1052 term:3 config:-1, file:/var/lib/taos//mnode/data/sdb.data
01/05 10:11:43.108327 00030026 MND ERROR failed to open sdb file:/var/lib/taos//mnode/tmp/sdb.data for write since No space left on device
01/05 10:11:43.108344 00030026 MND ERROR failed to write sdb file since No space left on device
01/05 10:11:43.572889 00030025 MND stb:1.iot.s_device, start to retrieve meta
01/05 10:11:45.095051 00030026 MND start to write sdb file, apply index:1073 term:6 config:-1, commit index:1052 term:3 config:-1, file:/var/lib/taos//mnode/data/sdb.data
01/05 10:11:45.097502 00030026 MND ERROR failed to open sdb file:/var/lib/taos//mnode/tmp/sdb.data for write since No space left on device
01/05 10:11:45.097525 00030026 MND ERROR failed to write sdb file since No space left on device
01/05 10:11:47.004973 00030039 SYN ERROR vgId:2, timer wal snapshot end error since:No space left on device, sync:leader, term:6, commit-index:324919355, first-ver:324906891, last-ver:324919355, min:-1, snap:324888758, snap-term:5, elect-times:0, as-leader-times:1, cfg-ch-times:0, hit:0, mis:0, hb-slow:0, hbr-slow:0, aq-items:0, snaping:324914889, replicas:1, last-cfg:-1, chging:0, restore:1, quorum:1, elect-lc-timer:1, hb:0, {0:-1 0}, {r-num:1, my:0, platform-iot:6030}, hb:{0:1672883659960}, hbr:{0:1672883659960}
01/05 10:11:47.074718 00030038 SYN ERROR vgId:3, timer wal snapshot end error since:No space left on device, sync:leader, term:6, commit-index:322428272, first-ver:322414682, last-ver:322428272, min:-1, snap:322396632, snap-term:5, elect-times:0, as-leader-times:1, cfg-ch-times:0, hit:0, mis:1, hb-slow:0, hbr-slow:0, aq-items:0, snaping:322422460, replicas:1, last-cfg:-1, chging:0, restore:1, quorum:1, elect-lc-timer:1, hb:0, {0:-1 0}, {r-num:1, my:0, platform-iot:6030}, hb:{0:1672883659956}, hbr:{0:1672883659956}
01/05 10:11:47.097868 00030026 MND start to write sdb file, apply index:1073 term:6 config:-1, commit index:1052 term:3 config:-1, file:/var/lib/taos//mnode/data/sdb.data
01/05 10:11:47.113315 00030026 MND ERROR failed to open sdb file:/var/lib/taos//mnode/tmp/sdb.data for write since No space left on device
01/05 10:11:47.113344 00030026 MND ERROR failed to write sdb file since No space left on device
01/05 10:11:49.104854 00030026 MND start to write sdb file, apply index:1073 term:6 config:-1, commit index:1052 term:3 config:-1, file:/var/lib/taos//mnode/data/sdb.data
01/05 10:11:49.109327 00030026 MND ERROR failed to open sdb file:/var/lib/taos//mnode/tmp/sdb.data for write since No space left on device
01/05 10:11:49.109345 00030026 MND ERROR failed to write sdb file since No space left on device
01/05 10:11:50.921413 00030025 MND stb:1.iot.s_device, start to retrieve meta
01/05 10:11:50.921710 00030025 MND stb:1.iot.s_device, start to retrieve meta
01/05 10:11:50.921768 00030025 MND stb:1.iot.s_device, start to retrieve meta
01/05 10:11:51.065657 00030036 WAL ERROR vgId:3, failed to write idx entry due to No space left on device. ver:322428273
01/05 10:11:51.065714 00030036 SYN ERROR vgId:3, wal write error, index:322428273, err:0x80ff001c, msg:No space left on device, syserr:28, sysmsg:No space left on device, sync:leader, term:6, commit-index:322428272, first-ver:322414682, last-ver:322428272, min:-1, snap:322396632, snap-term:5, elect-times:0, as-leader-times:1, cfg-ch-times:0, hit:0, mis:1, hb-slow:0, hbr-slow:0, aq-items:0, snaping:322422460, replicas:1, last-cfg:-1, chging:0, restore:1, quorum:1, elect-lc-timer:1, hb:0, {0:-1 0}, {r-num:1, my:0, platform-iot:6030}, hb:{0:1672883659956}, hbr:{0:1672883659956}
01/05 10:11:51.065724 00030036 SYN ERROR failed to append sync log entry since No space left on device. index:322428273, term:6
01/05 10:11:51.065728 00030036 SYN ERROR vgId:3, failed to persist sync log entry from buffer since No space left on device. index:322428273
01/05 10:11:51.065823 00030037 WAL ERROR vgId:2, failed to write idx entry due to No space left on device. ver:324919356

**Screenshots**

**Environment (please complete the following information):**
 - CentOS Linux release 7.9.2009 
 - 4C/8GB
 - TDengine-server-3.0.2.2-Linux-x64.tar.gz

**Additional Context**

**Comment by yu285** [comment]
经排查是存储空间问题。

**Comment by keephunny** [comment]
稳定了，问题没有出现。
