### ISSUE TITLE
SQL修改root的密码后客户端无法直接访问服务端

### ISSUE THREAD

**Issue by fwbcrazylang** [taosdata/TDengine#19375]
版本3.0.2.2
问题：通过SQL修改root密码后，远程客户端和服务端taos命令皆无法与服务建立连接，报错：failed to connect to server, reason: Authentication failure

**Comment by fwbcrazylang** [comment]
尝试1：修改远程客户端C:\TDengine\cfg\taosadapter.toml文件以及服务端/etc/taos/taosadapter.toml和/etc/taos/keeper.toml文件中password属性值，皆改为SQL修改后的密码，重启taosd.service和taosadapter.service服务，依旧无法直连。
尝试2：可能修改密码的时候密码没修改好，通过taos -u root -p的方式输入SQL修改后的密码可正常连接。
请问，通过SQL修改root密码后，还需要做什么操作，才可通过客户端命令进行直连？同时修改以上文件中password属性配置后是否影响其他功能使用？是否需要恢复默认密码？

**Comment by yu285** [comment]
密码在修改后只能手动指定，不能通过配置文件指定。
