### ISSUE TITLE
sql语句插入25万子表后，查询速度极慢

### ISSUE THREAD

**Issue by ybjtao** [taosdata/TDengine#19380]
**Bug Description**
使用windows版本3.0.2.2，sql语句插入25万子表后，查询速度极慢

**To Reproduce**
1. 下载安装TDengine-server-3.0.2.2-Windows-x64.exe 
2. 创建超级表，create stable  SmartWater.abc(
ts timestamp comment '记录时间',
aaa int comment '电池状态',
bbb varchar(20) comment '特征字') tags (
meterAddr nchar(50) comment '表地址') comment '测试'
;
3. 使用VS2022编写C#代码，循环插入子表，public void TDengineTest(int count = 1000000,int every = 2500)
        {
            var wsConn = TDengine.Connect("127.0.0.1", "root", "taosdata", "test", 6030);
            var group = count / every;
            try
            {
                for (int j = 0; j < group; j++)
                {
                    Stopwatch sw = new Stopwatch();
                    sw.Start();
                    var insert = new StringBuilder("INSERT INTO");
                    for (int i = 0; i < every; i++)
                    {
                        insert.Append($" d{1 + every * j + i} using abc tags('00000{100000001 + every * j + i}') VALUES");
                        insert.Append($" (NOW, {every * j + i}, '{every * j + i}')");
                        insert.AppendLine();
                    }
                    insert.Append(';');
                    var wsRes = TDengine.Query(wsConn, insert.ToString());
                    var msg = TDengine.Error(wsRes);
                    TDengine.FreeResult(wsRes);
                    sw.Stop();
                    Console.WriteLine($"结论{msg} 耗时组{j}:{sw.ElapsedTicks},{sw.ElapsedMilliseconds}ms");
                }
            }
            catch(Exception ex)
            {
                Console.WriteLine($"{ex}");
            }
        }
5. 当插入到25万多或者30万时，出现长时间无法插入的情况，例如几分钟，之后又能插入，但是在taosd中查询select * from test.abc limit 1;查询速度为180秒左右

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Windows 10
 - Memory 16G, CPU intel I5-8500, current Disk Space 100GB
 - TDengine Version [3.0.2.2]

**Additional Context**

**Comment by yu285** [comment]
可以加微信做下具体调试 a15652223354

**Comment by sundayong** [comment]
> 可以加微信做下具体调试 a15652223354

想问一下td最多支持一张超级表下建立多少张子表？

**Comment by yu285** [comment]
> > 可以加微信做下具体调试 a15652223354
> 
> 想问一下td最多支持一张超级表下建立多少张子表？

不作限制，上限可达10亿级别
