### ISSUE TITLE
springbootdemo的lastOne方法有bug

### ISSUE THREAD

**Issue by garrycode** [taosdata/TDengine#19393]
![b365c660ba4e2219a2d66efd99f67f4](https://user-images.githubusercontent.com/32251959/210738418-ce3f2815-2f09-451d-aeea-9adc3c9c403f.png)
springboot用的是2.7.7，驱动用的是3.0.0（或者3.0.2），本地启动调试该方法发现报空指针异常，如图。个人觉得还是last_row()函数问题，可能需要优化。

**Comment by sangshuduo** [comment]
taos shell 里执行相同 db 相同表的 last_row() 返回什么？

**Comment by huolibo** [comment]
结果集中是否存在 last_row()，可以通过修改 /etc/taos/taos.cfg 中 keepColumnName 参数控制。

**Comment by garrycode** [comment]
> 

![image](https://user-images.githubusercontent.com/32251959/210946186-357dd188-ffdf-4c1f-8863-6b34c0d50741.png)

**Comment by garrycode** [comment]
> 



> 结果集中是否存在 last_row()，可以通过修改 /etc/taos/taos.cfg 中 keepColumnName 参数控制。

============
结果集中存在last_now()，taos.cfg中没有找到keepColumnName这个参数

**Comment by sangshuduo** [comment]
https://docs.taosdata.com/reference/config/#%E7%9B%91%E6%8E%A7%E7%9B%B8%E5%85%B3

**Comment by garrycode** [comment]
> https://docs.taosdata.com/reference/config/#%E7%9B%91%E6%8E%A7%E7%9B%B8%E5%85%B3

=======================
通过客户端taos.cfg配置：
keepColumnName 1
已解决
