### ISSUE TITLE
[typo] typo error in documentation

### ISSUE THREAD

**Issue by Irving-cl** [taosdata/TDengine#194]
In `Getting Started` of documentation: https://github.com/StoneT2000/TDengine/blob/master/documentation/tdenginedocs-en/getting-started/index.html#L21

> If the service is running successfully, you can play around though TDengine shell taos,

It should be `play around through`?

**Comment by StoneT2000** [comment]
Thanks for pointing this out, woops 😅
Merging soon: #196
