### ISSUE TITLE
same SQL return different result 

### ISSUE THREAD

**Issue by matchmen** [taosdata/TDengine#19413]
**Bug Description**
部署情况：3个节点，1主2从。
多次执行select count(1) from nacos_user.play_record where user_id = 55508003 and resource_type = 'song';有时候有数据，有时候没有数据，出现没有数据频率较高，且没有规律，3个节点都会出现类似情况。
![SK7K3XEZB3C)0QRGH)`KFRL](https://user-images.githubusercontent.com/22736794/210940625-0e3dddfc-50d6-4454-a29e-42b6f8453d65.png)

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - TDengine Version [e.g. 2.4.0.12]

**Additional Context**

**Comment by checkForTD** [comment]
可以加微信远程调试一下 a15652223354

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
