### ISSUE TITLE
taoskeeper log database is not working normally

### ISSUE THREAD

**Issue by turbozhao** [taosdata/TDengine#19428]
环境： centos7
tdengine版本： 3.0.2.2
准备工作：
	1.准备三台机器，hostname分别为 hasaki  hasaki-2 hasaki-3
	2.taos.cfg firstEp均配置为hasaki:6030
	3.增加监控配置，三台配的monitorFQDN均为hasaki，分别启动taosd服务
	4.在hasaki leader节点开启taoskeeper服务。查看log库stable，如cluster_info,查看监控数据，一切正常。
	5.hasaki节点执行服务启停，将leader节点转移到其他节点，查看cluster_info表数据录入情况，
	  发现每隔15s录入三条数据，且除了leader节点录入的数据正常外，其他两个节点录入的数据均为空。

错误描述：
    公司采用Grafana监控Tdengine集群数据，但由于log库中数据录入异常，导致Grafana dashborder
	页面展示的数据时而展示，时而消失。请技术组分析原因，排查是否为tdengine本身的问题。感谢！

taos> show dnodes;
     id      |            endpoint            | vnodes | support_vnodes |   status   |       create_time       |              note              |
=================================================================================================================================================
           1 | hasaki:6030                    |      1 |              4 | ready      | 2023-01-06 10:05:27.203 |                                |
           2 | hasaki-2:6030                  |      0 |              4 | ready      | 2023-01-06 10:06:03.473 |                                |
           3 | hasaki-3:6030                  |      1 |              4 | ready      | 2023-01-06 10:06:07.441 |                                |
Query OK, 3 row(s) in set (0.004074s)

taos> show mnodes;
     id      |            endpoint            |     role     |  status   |       create_time       |
====================================================================================================
           1 | hasaki:6030                    | leader       | ready     | 2023-01-06 10:05:27.203 |
           2 | hasaki-2:6030                  | follower     | ready     | 2023-01-06 10:06:21.851 |
           3 | hasaki-3:6030                  | follower     | ready     | 2023-01-06 10:06:24.944 |
Query OK, 3 row(s) in set (0.003972s)

taos> select ts,version,first_ep  from cluster_info;
           ts            |   version    |            first_ep            |
==========================================================================
 2023-01-07 19:39:37.298 |              |                                |
 2023-01-07 19:39:44.325 |              |                                |
 2023-01-07 19:39:45.594 | 3.0.2.2      | hasaki:6030                    |
 2023-01-07 19:40:07.397 |              |                                |
 2023-01-07 19:40:14.413 |              |                                |
 2023-01-07 19:40:15.677 | 3.0.2.2      | hasaki:6030                    |
 2023-01-07 19:40:37.486 |              |                                |
 2023-01-07 19:40:44.510 |              |                                |
 2023-01-07 19:40:45.768 | 3.0.2.2      | hasaki:6030                    |
 2023-01-07 19:41:07.578 |              |                                |
Query OK, 10 row(s) in set (0.009670s)

**Comment by sunpe** [comment]
只有 mnode 节点会上报 cluster_info, vgroup_infos, grant_info 数据，其他的 dnode 节点不会上报这些数据。

**Comment by sangshuduo** [comment]
@turbozhao  https://github.com/taosdata/taoskeeper/releases/tag/1.0.3 已修复，在下次发版中包含
