### ISSUE TITLE
tdengine 3.0.2.2 query order by ts desc limit 10 very slow

### ISSUE THREAD

**Issue by xltxb** [taosdata/TDengine#19426]
**Performance Issue** 
Any questions related to TDengine's performance can be discussed here.

**Problem Description** 
query stable order by ts desc limit 10 very slow. that stable only 30K+ rows, but it's very slow

**To Reproduce**
1. Database parameters used: 
<img width="2456" alt="image" src="https://user-images.githubusercontent.com/5130103/211112943-b3ee4b36-6e3e-4c1b-a5f9-1846ad744953.png">
2. Verbs used: select
3. Describe the total amount of data
4. Observed performance vs. expected performance

**Screenshots**
<img width="458" alt="image" src="https://user-images.githubusercontent.com/5130103/211112350-c6efe758-6d26-4dc8-abd9-2c377bb7be11.png">
<img width="1879" alt="image" src="https://user-images.githubusercontent.com/5130103/211112479-17ea4553-474e-4c97-9536-73bb66bc6763.png">

**Environment (please complete the following information):**

* OS: Rocky linux 8
* 16G Memory, 8C CPU, 100G SSD
* TDengine Version [3.0.2.2]

**Additional Context**

**Comment by xltxb** [comment]
anyone can give me some help? or this is tdengine bug ?

**Comment by DuanKuanJun** [comment]
already created jira task to solve problem, Jira ID: TS-2414
Please wait patiently.

**Comment by xltxb** [comment]
Okay, I am waitting this solution.

**Comment by xltxb** [comment]
Any progress ?

**Comment by hjxilinx** [comment]
@xltxb 
Hi, there is the root cause why the global order by requires so many times to response.

> 超级表全局排序执行逻辑中，需要读取每个表的最早（order by ts asc）和 最晚 （order by ts desc）数据块，然后读取将每个表的 block，进行多路归并排序。如果有1000个表，就是1000路的多路归并排序。
> 
> 时间主要开销是每个表读取对应的数据block，更准确的说是，读取每个表的head 文件导致。
> 从执行流程上来说，由于采用了迭代的方式读取每个表的block，所以性能不会好。并且性能是随着查询涉及表的数量增加而恶化。
> 
> 优化策略：
> 1. 提供一个优化算子，提升多路归并排序过程中，首次排序初始化的性能。该优化算子提供一个特殊的加载模式，对于所有的表，只读取每个表的第一个block。后续block 的读取不做变更，仍然按照按需方式提供。同时，调整 table merge scan 算子，调用该优化算子来处理后续流程 。

We will apply this optimization policy to the future new released version of TDengine, and the expect elapsed time will be  reduced to less than 1 sec.

**Comment by xltxb** [comment]
Is it fix on version 3.0.2.4 ?

**Comment by xltxb** [comment]
Hell team, which version fix this problem ? I upgraded TDengine to 3.0.2.4 but it still not fix yet.

**Comment by hjxilinx** [comment]
暂时还没有 fix，还需要等待一段时间。

**Comment by Robinsir** [comment]
遇到一样的问题 3.0.3.1

**Comment by lazyz-zk** [comment]
二百万数据根据时间倒叙查，查10s。。。。。

**Comment by shenglian-zhou** [comment]
could you please share the table schema? thanks a lot. @xltxb @lazyz-zk ?
I am testing to see if this problem exists anymore after some improvements.

thanks a lot
