### ISSUE TITLE
Can TAOS_STMT run DDL? 

### ISSUE THREAD

**Issue by DianaZhao** [taosdata/TDengine#19427]
I am testing some C code using TAOS C API. There is a test running SQL, using TAOS_STMT related API. While I passed "create database testdb;" to that code, which calls taos_stmt_init, taos_stmt_prepare, taos_stmt_execute sequentially to execute it, taos_stmt_execute returns 2147484202, Stmt API usage error. I noticed that in taos c examples, TAOS_STMT only runs DML. Does that means  TAOS_STMT can not be used to run DDL?

**Comment by freemine** [comment]
currently, `taos-prepare` leaded API sequense will fail if the SQL statement is not parameterized one.

**Comment by freemine** [comment]
btw, don't know if it's bug or designed behavior by tdengine.
