### ISSUE TITLE
tdengine since WAL file is corrupted

### ISSUE THREAD

**Issue by weijiazhuo** [taosdata/TDengine#19431]
我们部署了tdengine3.0.1.1版本单机进行测试，测试是我们频繁写入导致服务器内存不存，taosd服务触发了omm机制被kill,之后taosd数据库无法启动，提示报错
 WAL ERROR vgId:3, unexpected wal log, index:585221, since WAL file is corrupted
每一次taosd数据库被异常停止，都会提示WAL文件损坏导致无法启动
我们尝试清空wal文件可以启动数据库，但是之前库表会访问异常，针对taosd被异常停止导致wal 文件损坏无法启动有什么恢复方案？

![image](https://user-images.githubusercontent.com/32673380/211191359-50754eb9-9b6c-4457-a14b-aa7efe92c565.png)

**Comment by yu285** [comment]
这种情况比较复杂，加微信沟通一下吧a15652223354

**Comment by weijiazhuo** [comment]
升级为3.0.2.2 版本问题解决，感谢支持
