### ISSUE TITLE
tdengine在使用过程中select没问题insert有问题

### ISSUE THREAD

**Issue by yufeioracle** [taosdata/TDengine#19439]
我在用tdengine大半年了，突然出现一个问题，select没问题insert有问题，不知道是什么原因，我就restart一下，发现一直卡住不动了，现在我想启动也是一直处于卡住状态，是什么原因呢？

**Comment by yu285** [comment]
我们对linux内核的操作系统没有特别的要求，应该是没问题

可以安装后执行：taosdemo 迅速做一下数据生成做下测试。

**Comment by yufeioracle** [comment]
自己的问题
