### ISSUE TITLE
tdengine数据库异常重启Cannot access memory at address

### ISSUE THREAD

**Issue by weijiazhuo** [taosdata/TDengine#19430]
**Bug Description**
tdengine 3.0.2.2 版本查询数据时异常重启

**To Reproduce**
select * from database.stable limit 10000,1000

**Expected Behavior**

RD [root@tdengine01 ~]# coredumpctl list
TIME                            PID   UID   GID SIG COREFILE  EXE
Sat 2023-01-07 21:02:43 CST  195171     0     0   6 present   /usr/local/taos/bin/taosd
Sun 2023-01-08 01:00:38 CST  251379     0     0   6 truncated /usr/local/taos/bin/taosd
Sun 2023-01-08 02:40:36 CST  503716     0     0   6 truncated /usr/local/taos/bin/taosd
Sun 2023-01-08 03:11:36 CST   88591     0     0   6 present   /usr/local/taos/bin/taosd
Sun 2023-01-08 06:57:07 CST  122152     0     0   6 truncated /usr/local/taos/bin/taosd
Sun 2023-01-08 10:10:07 CST  362836     0     0   6 truncated /usr/local/taos/bin/taosd
Sun 2023-01-08 10:39:07 CST   45410     0     0   6 truncated /usr/local/taos/bin/taosd
Sun 2023-01-08 11:08:07 CST   76783     0     0   6 truncated /usr/local/taos/bin/taosd
Sun 2023-01-08 12:38:06 CST  107478     0     0   6 truncated /usr/local/taos/bin/taosd
PRD [root@tdengine01 ~]#
**Cannot access memory at address 0x7f75ece70128
Cannot access memory at address 0x7f75ece70120
Failed to read a valid object file image from memory.
Core was generated by `/usr/bin/taosd'.
Program terminated with signal SIGABRT, Aborted.**

**Screenshots**
![image](https://user-images.githubusercontent.com/32673380/211190984-4c065928-e824-445a-bf66-de5ee06f97d7.png)

**Environment (please complete the following information):**
 - OS:CentOS Linux release 8.2.2004 (Core)
 - Memory, CPU, current Disk Space
PRD [root@tdengine01 ~]# free -g
              total        used        free      shared  buff/cache   available
Mem:             15           1           3           0          10          13
Swap:             9           0           9
PRD [root@tdengine01 ~]#
PRD [root@tdengine01 ~]# lscpu  |grep CPU
CPU op-mode(s):      32-bit, 64-bit
CPU(s):              8

 - TDengine Version [e.g. 3.0.2.2]
1/07 18:09:54.189952 00068047 UTL apoll url not load
01/07 18:09:54.190014 00068047 UTL load from cfg file /etc/taos//taos.cfg success
01/07 18:09:54.190019 00068047 UTL env file:.env not load
01/07 18:09:54.190024 00068047 UTL load from env variables cfg success
01/07 18:09:54.190058 00068047 UTL                      global config
01/07 18:09:54.190060 00068047 UTL =================================================================
01/07 18:09:54.190062 00068047 UTL cfg_file     firstEp                  tdengine01:6030
01/07 18:09:54.190064 00068047 UTL default      secondEp                 tdengine01:6030
01/07 18:09:54.190066 00068047 UTL cfg_file     fqdn                     tdengine01
01/07 18:09:54.190068 00068047 UTL default      serverPort               6030
01/07 18:09:54.190070 00068047 UTL default      tempDir                  /tmp/
01/07 18:09:54.190072 00068047 UTL default      minimalTmpDirGB          1.00
01/07 18:09:54.190076 00068047 UTL default      shellActivityTimer       3
01/07 18:09:54.190077 00068047 UTL default      compressMsgSize          -1
01/07 18:09:54.190079 00068047 UTL default      compressColData          -1
01/07 18:09:54.190080 00068047 UTL default      queryPolicy              1
01/07 18:09:54.190082 00068047 UTL default      querySmaOptimize         0
01/07 18:09:54.190084 00068047 UTL default      queryPlannerTrace        0
01/07 18:09:54.190085 00068047 UTL default      queryNodeChunkSize       32768
01/07 18:09:54.190087 00068047 UTL default      queryUseNodeAllocator    1
01/07 18:09:54.190088 00068047 UTL default      keepColumnName           0
01/07 18:09:54.190090 00068047 UTL default      smlChildTableName
01/07 18:09:54.190091 00068047 UTL default      smlTagName               _tag_null
01/07 18:09:54.190093 00068047 UTL default      smlDataFormat            0
01/07 18:09:54.190094 00068047 UTL default      smlBatchSize             10000
01/07 18:09:54.190096 00068047 UTL default      maxMemUsedByInsert       1024
01/07 18:09:54.190097 00068047 UTL default      useAdapter               0
01/07 18:09:54.190099 00068047 UTL default      configDir                /etc/taos/
01/07 18:09:54.190100 00068047 UTL default      scriptDir                /etc/taos/
01/07 18:09:54.190102 00068047 UTL cfg_file     logDir                   /app/log/taos
01/07 18:09:54.190103 00068047 UTL default      minimalLogDirGB          1.00
01/07 18:09:54.190105 00068047 UTL default      numOfLogLines            10000000
01/07 18:09:54.190107 00068047 UTL default      asyncLog                 1
01/07 18:09:54.190108 00068047 UTL default      logKeepDays              0
01/07 18:09:54.190110 00068047 UTL default      debugFlag                0
01/07 18:09:54.190111 00068047 UTL default      simDebugFlag             143
01/07 18:09:54.190112 00068047 UTL default      tmrDebugFlag             131
01/07 18:09:54.190114 00068047 UTL default      uDebugFlag               131
01/07 18:09:54.190115 00068047 UTL default      rpcDebugFlag             131
01/07 18:09:54.190116 00068047 UTL default      jniDebugFlag             131
01/07 18:09:54.190118 00068047 UTL default      qDebugFlag               131
01/07 18:09:54.190119 00068047 UTL default      cDebugFlag               131
01/07 18:09:54.190120 00068047 UTL default      timezone                 Asia/Shanghai (CST, +0800)
01/07 18:09:54.190122 00068047 UTL default      locale                   en_US.UTF-8
01/07 18:09:54.190123 00068047 UTL default      charset                  UTF-8
01/07 18:09:54.190125 00068047 UTL default      assert                   1
01/07 18:09:54.190126 00068047 UTL default      enableCoreFile           1
01/07 18:09:54.190128 00068047 UTL default      numOfCores               8.00
01/07 18:09:54.190130 00068047 UTL default      openMax                  524288
01/07 18:09:54.190132 00068047 UTL default      streamMax                16
01/07 18:09:54.190133 00068047 UTL default      pageSizeKB               4
01/07 18:09:54.190135 00068047 UTL default      totalMemoryKB            16267956
01/07 18:09:54.190136 00068047 UTL default      os sysname               Linux
01/07 18:09:54.190140 00068047 UTL default      os nodename              tdengine01
01/07 18:09:54.190141 00068047 UTL default      os release               4.18.0-193.el8.x86_64
01/07 18:09:54.190143 00068047 UTL default      os version               #1 SMP Fri May 8 10:59:10 UTC 2020
01/07 18:09:54.190144 00068047 UTL default      os machine               x86_64
01/07 18:09:54.190146 00068047 UTL default      version                  3.0.2.2
01/07 18:09:54.190147 00068047 UTL default      compatible_version       3.0.0.0
01/07 18:09:54.190149 00068047 UTL default      gitinfo                  c09602bcde83fbaba1d9bb29ab53f474ec0607b5
01/07 18:09:54.190150 00068047 UTL default      buildinfo                Built at 2022-12-28 15:17
**Additional Context**

RD [root@tdengine01 ~]# coredumpctl list
TIME                            PID   UID   GID SIG COREFILE  EXE
Sat 2023-01-07 21:02:43 CST  195171     0     0   6 present   /usr/local/taos/bin/taosd
Sun 2023-01-08 01:00:38 CST  251379     0     0   6 truncated /usr/local/taos/bin/taosd
Sun 2023-01-08 02:40:36 CST  503716     0     0   6 truncated /usr/local/taos/bin/taosd
Sun 2023-01-08 03:11:36 CST   88591     0     0   6 present   /usr/local/taos/bin/taosd
Sun 2023-01-08 06:57:07 CST  122152     0     0   6 truncated /usr/local/taos/bin/taosd
Sun 2023-01-08 10:10:07 CST  362836     0     0   6 truncated /usr/local/taos/bin/taosd
Sun 2023-01-08 10:39:07 CST   45410     0     0   6 truncated /usr/local/taos/bin/taosd
Sun 2023-01-08 11:08:07 CST   76783     0     0   6 truncated /usr/local/taos/bin/taosd
Sun 2023-01-08 12:38:06 CST  107478     0     0   6 truncated /usr/local/taos/bin/taosd
PRD [root@tdengine01 ~]#

RD [root@tdengine01 ~]# coredumpctl info 107478
           PID: 107478 (taosd)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 6 (ABRT)
     Timestamp: Sun 2023-01-08 12:38:00 CST (5h 35min ago)
  Command Line: /usr/bin/taosd
    Executable: /usr/local/taos/bin/taosd
 Control Group: /
         Slice: -.slice
       Boot ID: 2a2d62239b2e4d7782d4e82db53edc91
    Machine ID: fc7b99c55f466e3dbf411011f4695719
      Hostname: tdengine01
       Storage: /var/lib/systemd/coredump/core.taosd.0.2a2d62239b2e4d7782d4e82db53edc91.107478.1673152680000000.lz4 (truncated)
       Message: Process 107478 (taosd) of user 0 dumped core.

                Stack trace of thread 107542:
                #0  0x00007f75ebf0c70f n/a (n/a)
PRD [root@tdengine01 ~]#

RD [root@tdengine01 ~]# coredumpctl gdb 107478
           PID: 107478 (taosd)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 6 (ABRT)
     Timestamp: Sun 2023-01-08 12:38:00 CST (5h 35min ago)
  Command Line: /usr/bin/taosd
    Executable: /usr/local/taos/bin/taosd
 Control Group: /
         Slice: -.slice
       Boot ID: 2a2d62239b2e4d7782d4e82db53edc91
    Machine ID: fc7b99c55f466e3dbf411011f4695719
      Hostname: tdengine01
       Storage: /var/lib/systemd/coredump/core.taosd.0.2a2d62239b2e4d7782d4e82db53edc91.107478.1673152680000000.lz4 (truncated)
       Message: Process 107478 (taosd) of user 0 dumped core.

                Stack trace of thread 107542:
                #0  0x00007f75ebf0c70f n/a (n/a)

GNU gdb (GDB) Red Hat Enterprise Linux 8.2-11.el8
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/taos/bin/taosd...done.
BFD: warning: /var/tmp/coredump-ePvRzI is truncated: expected core file size >= 2273423360, found: 2147483648
[New LWP 107542]
[New LWP 107494]
[New LWP 107482]
[New LWP 107505]
[New LWP 107478]
[New LWP 107486]
[New LWP 107488]
[New LWP 107566]
[New LWP 107500]
[New LWP 107570]
[New LWP 107540]
[New LWP 107569]
[New LWP 107562]
[New LWP 107561]
[New LWP 107498]
[New LWP 107563]
[New LWP 107544]
[New LWP 107553]
[New LWP 107510]
[New LWP 107531]
[New LWP 107554]
[New LWP 107534]
[New LWP 107550]
[New LWP 107549]
[New LWP 107508]
[New LWP 107504]
[New LWP 107523]
[New LWP 107511]
[New LWP 107529]
[New LWP 107532]
[New LWP 107499]
[New LWP 107490]
[New LWP 107527]
[New LWP 107509]
[New LWP 107539]
[New LWP 107502]
[New LWP 107528]
[New LWP 107481]
[New LWP 107533]
[New LWP 107501]
[New LWP 107506]
[New LWP 107530]
[New LWP 107524]
[New LWP 107503]
[New LWP 107564]
[New LWP 107489]
[New LWP 107521]
[New LWP 107522]
[New LWP 107512]
[New LWP 107556]
[New LWP 107571]
[New LWP 107520]
[New LWP 107541]
[New LWP 107526]
[New LWP 107604]
[New LWP 107552]
[New LWP 107507]
[New LWP 107525]
[New LWP 107487]
[New LWP 107538]
[New LWP 107517]
[New LWP 107568]
[New LWP 107518]
[New LWP 107572]
[New LWP 107567]
[New LWP 107551]
[New LWP 107479]
[New LWP 107483]
[New LWP 107543]
[New LWP 107558]
[New LWP 107537]
[New LWP 107559]
[New LWP 107480]
[New LWP 107557]
[New LWP 107535]
[New LWP 108521]
[New LWP 107565]
[New LWP 107560]
[New LWP 107548]
[New LWP 107546]
[New LWP 107547]
[New LWP 107519]
[New LWP 107492]
[New LWP 107493]
[New LWP 107484]
[New LWP 107485]
[New LWP 107555]
[New LWP 107536]
[New LWP 107545]
Cannot access memory at address 0x7f75ece70128
Cannot access memory at address 0x7f75ece70120
Failed to read a valid object file image from memory.
Core was generated by `/usr/bin/taosd'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f75ebf0c70f in ?? ()
[Current thread is 1 (LWP 107542)]
(gdb)

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
