### ISSUE TITLE
tdengine 对于虚拟机操作系统openeuler 支持哪个版本 目前td 版本为2.6.10

### ISSUE THREAD

**Issue by Rio20001003** [taosdata/TDengine#19442]
tdengine 对于虚拟机操作系统openeuler 支持哪个版本 目前td 版本为2.6.10，支持openeuler 那个版本，请确认一下22.03和20.03两个版本，都支持吗

**Comment by yu285** [comment]
我们对linux内核的操作系统没有特别的要求，应该是没问题

可以安装后执行：taosdemo 迅速做一下数据生成做下测试。
