### ISSUE TITLE
数据库运行132天后突然连不上

### ISSUE THREAD

**Issue by 179107686** [taosdata/TDengine#19453]
数据库版本2.6.0.4
运行132天后数据库连不上：taos connect failed, reason: Unable to establish connection.，然后执行taosd,错误信息为：DND ERROR failed to lock file:/var/lib/taos/dnode/.running ret:-1[Resource temporarily unavailable], database may be running, quit。
已经重启过taosd 和linux系统，还是连不上。
进入文件夹:/var/lib/taos/dnode/查看，是没这个文件.running

**Comment by 179107686** [comment]
taosdlog日志为：
01/09 17:31:43.312688 00024419 VND vgId:596 :SDEL stop waiting thread count=0
01/09 17:31:43.813507 00024419 UTL cache:qhandle_596 will be cleaned up
01/09 17:31:43.813598 00024419 WAL vgId:596, stop write wal
01/09 17:31:43.813784 00024419 WAL vgId:596, file:/var/lib/taos/vnode/vnode596/wal/wal1, it is closed before remove all wals
01/09 17:31:43.813862 00024419 WAL vgId:596, wal:0x7fa5d6b59b30 file:/var/lib/taos/vnode/vnode596/wal/wal1, it is removed
01/09 17:31:43.813880 00024419 WAL vgId:596, wal:0x7fa5d6b59b30 is freed

**Comment by 179107686** [comment]
![5ddb5cc4d99bd4f9bd411f3ffd85871](https://user-images.githubusercontent.com/42930454/211456897-6df70e67-00a2-471d-b117-032cb97eab70.png)
wal大小

**Comment by yu285** [comment]
升级后问题解决
