### ISSUE TITLE
count(*)查询速度慢

### ISSUE THREAD

**Issue by viskeee** [taosdata/TDengine#19468]
**Bug Description**
数据量6亿+，执行Count(*) 耗时 6s左右。

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: ubuntu 18.04
 - Memory 16G, CPU 20C, current Disk Space 1TB
 - TDengine Version [3.0.2.0]

**Additional Context**

**Comment by gccgdb1234** [comment]
Is there out-of-order data or duplicate timestamp?

**Comment by viskeee** [comment]
> Is there out-of-order data or duplicate timestamp?

![image](https://user-images.githubusercontent.com/49233036/215686938-99589e7e-df43-4fae-99eb-e61b1570dd8f.png)

Duplicate timestamps in different Subtable distinguished by tag. 

No out-of-order timestamp.

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
