### ISSUE TITLE
RPC ERROR failed to malloc msg, size:-2085852611

### ISSUE THREAD

**Issue by caizhenboy** [taosdata/TDengine#19466]
**Bug Description**
tdengine单点部署（tdengine版本：：2.4.0.12），运行一段时间后挂了，看了一下taosdlog.0日志，日志如下：报错部分已经加粗，
01/10 10:11:51.249651 00000076 SDB vgId:1, update mnodes role, replica:1
01/10 10:11:51.249697 00000076 SDB vgId:1, mnode:1, role:master
01/10 10:11:51.249721 00000076 MND vgId:1, update mnodes epSet, numOfMnodes:1
01/10 10:11:51.249731 00000076 MND vgId:1, mnodes epSet is set, num:1 inUse:0
01/10 10:11:51.249738 00000076 MND vgId:1, mnode:1, fqdn:anysense1 shell:6030 peer:6035
01/10 10:11:51.250307 00000075 SDB vgId:1, update mnodes role, replica:1
01/10 10:11:51.250328 00000075 SDB vgId:1, mnode:1, role:master
01/10 10:11:51.250343 00000075 MND vgId:1, update mnodes epSet, numOfMnodes:1
01/10 10:11:51.250349 00000075 MND vgId:1, mnodes epSet is set, num:1 inUse:0
01/10 10:11:51.250354 00000075 MND vgId:1, mnode:1, fqdn:anysense1 shell:6030 peer:6035
01/10 10:11:51.250789 00000075 SDB vgId:1, update mnodes role, replica:1
01/10 10:11:51.250803 00000075 SDB vgId:1, mnode:1, role:master
01/10 10:11:51.250808 00000075 MND vgId:1, update mnodes epSet, numOfMnodes:1
01/10 10:11:51.250813 00000075 MND vgId:1, mnodes epSet is set, num:1 inUse:0
01/10 10:11:51.250817 00000075 MND vgId:1, mnode:1, fqdn:anysense1 shell:6030 peer:6035
01/10 10:11:51.256001 00000075 MND WARN show type:show grants is not support
01/10 10:11:56.587774 00000078 MND user:root login from 10.9.1.175, result:success
01/10 10:12:02.498988 00000078 MND user:root login from 10.9.1.175, result:success
**01/10 10:12:08.162219 00000035 RPC ERROR failed to malloc msg, size:-2085852611**
01/10 10:12:08.375871 00000078 MND user:root login from 10.9.1.175, result:success

**To Reproduce**
问题是偶发，据观察，服务宕机时，内存是充足的。系统近期要上线，麻烦大佬们帮忙看一下

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/

如果还有具体的使用问题，可以加微信：a15652223354
