### ISSUE TITLE
事务问题

### ISSUE THREAD

**Issue by w15135591069** [taosdata/TDengine#19471]
TDengine,关于事务，我看一些文档介绍说3.0才接入事务，2.0是没有事务，此事务是忠从ACID原则么？

**Comment by SunwenyiGIt** [comment]
这个事务是遵循ACID的，但是是这样，他只是用来管理元数据的。对于业务侧，我们使用的是无锁机制。所以你可以用show transcation 操作来检查自己 DDL 操作的进度。

https://www.taosdata.com/engineering/14534.html

可以参考这篇文章。

**Comment by w15135591069** [comment]
完美解决
