### ISSUE TITLE
使用systemctl重启taosd服务一直在等待

### ISSUE THREAD

**Issue by xjcbruce** [taosdata/TDengine#19475]
起始是因为今天上午所有程序突然连接不上taosadapter，于是我尝试重启taosadapter，发现还是连接不上。再尝试重启taosd：

`systemctl restart taosd`

就进入了漫长的等待。。大约半小时后ctrl+c退出，使用systemctl status taosd查看，状态如下：

`systemctl status taosd`
● taosd.service - TDengine server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: disabled)
   Active: deactivating (stop-sigterm) since 二 2023-01-10 12:12:03 CST; 51min ago
  Process: 1056 ExecStartPre=/usr/local/taos/bin/startPre.sh (code=exited, status=0/SUCCESS)
 Main PID: 1076 (taosd)
    Tasks: 41
   Memory: 3.9G
   CGroup: /system.slice/taosd.service
           ├─ 1076 /usr/bin/taosd
           └─24757 /usr/bin/udfd -c /etc/taos/

12月 08 08:04:12 home-server systemd[1]: Starting TDengine server service...
12月 08 08:04:12 home-server systemd[1]: Started TDengine server service.
1月 10 12:12:03 home-server systemd[1]: Stopping TDengine server service...

不知道是在落盘还是出错了。直接杀进程的话又怕出问题。

taosd和taosadapter运行1个月，数据1亿条左右。版本3.0.1.5。

请教该怎么处理？

**Comment by xjcbruce** [comment]
已在陈玉的协助下解决，非常感谢！

1. 备份数据文件（dataDir 参数的目录）
2. kill -9 taos相关进程
3. 升级到3.0.2.2（参考https://docs.taosdata.com/operation/pkg-install/）。先卸载旧版，再升级新版。卸载很方便，只需要命令rmtaos
4. 重启taos，配置和数据都在，正常运行。

**Comment by cmdares** [comment]
@xjcbruce 能帮助问下，什么原因导致的吗？是如何触发的？日常运维应该注意哪些事项？
