### ISSUE TITLE
官网给出的从mysql数据迁移到tdengine博客文档内容有误

### ISSUE THREAD

**Issue by LY83** [taosdata/TDengine#19470]
![image](https://user-images.githubusercontent.com/29663266/211455633-fe220884-f3fa-47bd-87e6-6cc0a5ea0dd0.png)

**Comment by LY83** [comment]
![image](https://user-images.githubusercontent.com/29663266/211469278-1dfbc494-131b-4289-8ea0-ebbb85316cf7.png)
![image](https://user-images.githubusercontent.com/29663266/211469306-63b98e7a-8ca2-4446-86cb-894960b2f5f3.png)

**Comment by LY83** [comment]
![image](https://user-images.githubusercontent.com/29663266/211469823-d0c39b2c-3152-465b-94af-61de26f3a0cf.png)
tdengine安装的最新版，datax也是官网最新的
![image](https://user-images.githubusercontent.com/29663266/211469936-2a82d637-691f-47ac-b9b7-940317e7d608.png)

**Comment by zmlgirl** [comment]
很抱歉现在才回复。
这个问题是由于目前实现的 DataX 的不兼容 TDengine 3.0 导致的。可以使用涛思 DataX 仓库的 https://github.com/taosdata/DataX/tree/dev/lispQin 这个分支尝试编译打包执行写入。
目前该分支还在 review 阶段之后会逐步同步到 DataX 里面。
