### ISSUE TITLE
this operation is NOT supported currently!

### ISSUE THREAD

**Issue by bingoGuo** [taosdata/TDengine#19480]
![9369726a90276e5939c115723143940](https://user-images.githubusercontent.com/18900448/211497059-c0818992-abe9-4a47-8689-5355d7c85623.png)

mybatis+druid多数据源
select的时候可以成功查询，但是insert会报错 java.sql.SQLFeatureNotSupportedException: this operation is NOT supported currently!

tdengine版本 3.0.1.7

**Comment by yu285** [comment]
不用动态数据源可以连接
