### ISSUE TITLE
更新语句无法成功

### ISSUE THREAD

**Issue by w15135591069** [taosdata/TDengine#19487]
taos>  select * from t1;
           ts            |    count    |
========================================
 2023-01-10 15:26:09.154 |          18 |
 2023-01-11 08:26:37.177 |           1 |
Query OK, 2 row(s) in set (0.055000s)

taos> insert into t1 values('2023-01-11 08:26:37.177',2);
Query OK, 1 of 1 row(s) in database (0.055000s)

taos> select * from t1;
           ts            |    count    |
========================================
 2023-01-10 15:26:09.154 |          18 |
 2023-01-11 08:26:37.177 |           1 |
Query OK, 2 row(s) in set (0.053000s)

**Comment by yu285** [comment]
信息不完整，请规范提问
