### ISSUE TITLE
多线程查询写入 突然停止的情况

### ISSUE THREAD

**Issue by chenjilai** [taosdata/TDengine#19492]
**Bug Description**
经过测试  经过2万多次查询后，有一次查询程序停在那， 也不报错。反复试了几次都有这种情况。c#调用的

测试过程是迁移数据到TDengine的超级表后，依次对这个超级表里面每10个子表进行查询这10个表的所有·数据，80万个子表10个表一组，查询8万次把所有表数据查出来。 查到20多万个表的时候，就停在那里了，也不报错

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 8.0]    centos 8.0版本
 - Memory, CPU, current Disk Space       内存48G  ;cpu i7-8700 12核心 虚拟机内存10G ,cpu分配6核
 - TDengine Version [e.g. 1.6.1.7]    TDengine-server-3.0.2.2-Linux-x64.tar.gz

业务逻辑代码如下:
 long dataNumber = 0;
                int takeNumber = 10;

                object curLocker1 = new object();
                int taskNum = 5;
                int loopNum = -1;//第几次循环 -1

                var tasks = new List<Task>();
                DateTime dataEndTime = DateTime.Now.AddDays(2);  //Convert.ToDateTime("2022-12-15 17:20:00");//这个理论上要大几天保险点. 是数据时间不是上传时间.
                allChannelLatestData = allChannelLatestData.Skip(0).Take(allChannelLatestData.Count - 0).ToList();
                int getedChannel = 0;
                for (int j = 0; j < taskNum; j++)
                {
                    tasks.Add(Task.Run(async () =>
                    {
                        while (loopNum * takeNumber < allChannelLatestData.Count)
                        {
                            List<LatestData> curTaskChannelLatestData = new List<LatestData>();
                            int curTakeNum = -1;
                            int curLoopLoopNum = 0;
                            lock (curLocker1)
                            {
                                curTakeNum = (++loopNum) * takeNumber;
                                curLoopLoopNum = loopNum;
                                //LabelHisData: 
                                curTaskChannelLatestData = allChannelLatestData.Skip(curTakeNum).Take(takeNumber).ToList();
                                //LogHelper.Info("同步hisdata:" + curTakeNum);
                                getedChannel += takeNumber;
                                LogHelper.Info("同步hisdata通道数量:" + getedChannel);
                            }
                            var carLatest = curTaskChannelLatestData.Select(it => it.ChannelId).ToList();
                            List<HisDataDto> curHisData = new List<HisDataDto>();
                            try
                            {

                                curHisData = dataBLL1Source.GetHisdata(channelIds: carLatest, endTime: dataEndTime).GetAwaiter().GetResult();

                            }
                            catch (Exception ex)
                            {
                                LogHelper.Error("SyncInfluxData1Xto2X-hisdata报错-拿数据" + ex.ToString() + ex.StackTrace.ToString());
                                //出错从出错的LoopNum开始执行
                                loopNum = curLoopLoopNum;
                                //throw ex; 
                            }
                            try
                            {
                                dataBLL2To.AddHisData(curHisData).GetAwaiter().GetResult();
                                dataNumber += curHisData.Count;
                            }
                            catch (Exception ex)
                            {
                                LogHelper.Error("SyncInfluxData1Xto2X-hisdata报错-插入数据" + ex.ToString() + ex.StackTrace.ToString());
                                lock (curLocker1)
                                {//出错从出错的LoopNum开始执行
                                    loopNum = curLoopLoopNum;
                                }
                            }
                        }
                    }));
                }
                Task.WhenAll(tasks).GetAwaiter().GetResult();
                tasks.Clear();

                LogHelper.Info("同步hisdata条数:" + dataNumber);
---=======================================================
写入数据代码如下
 public List<T> Query<T>(string sql, string tablename) where T : class, new()
        {
            try
            {
                IntPtr res = new IntPtr();
                //lock (ReadWriteLocker)
                //{//目前该控件多线程读写会报错,先加锁
                    LogHelper.Warn("GetHisdata记录咯咯End2222");
                    res = TDengine.Query(connDic[tablename], sql);
                    LogHelper.Warn("GetHisdata记录咯咯End3333");
                    if (TDengine.ErrorNo(res) != 0)
                    {
                        LogHelper.Error($"TDengine查询报错:{tablename} since: {TDengine.Error(res)}");
                        return new List<T>();
                    }
                    var fieldCount = TDengine.FieldCount(res);
                    var fieldInfos = TDengine.FetchFields(res);

                    var result = new List<T>();
                    IntPtr currentRow;
                    while ((currentRow = TDengine.FetchRows(res)) != IntPtr.Zero)
                    {
                        var source = TDengine.FetchLengths(res);
                        var target = new int[fieldCount];
                        Marshal.Copy(source, target, 0, fieldCount);
                        var properties = typeof(T).GetProperties();
                        var propertyMap = new Dictionary<string, PropertyInfo>(properties.Length, StringComparer.OrdinalIgnoreCase);
                        foreach (var property in properties)
                        {
                            var attribute = property.GetCustomAttribute(typeof(Column));
                            var attributeTDengine = property.GetCustomAttribute(typeof(TDColumn));

                            if (attribute != null && attribute is Column column)
                            {//利用之前influxdb的Column 属性继续判断
                                if (column.IsTimestamp)
                                {
                                    propertyMap.Add("time", property);
                                }
                                else
                                {
                                    if (attributeTDengine != null && attributeTDengine is TDColumn columnTD)
                                    {//TDengine 优先判断TDColumn 特性(TDColumn 的name 是数据库实际存的字段名)
                                        propertyMap.Add(!string.IsNullOrWhiteSpace(columnTD.Name) ? columnTD.Name : property.Name, property);
                                    }
                                    else
                                    {
                                        propertyMap.Add(!string.IsNullOrWhiteSpace(column.Name) ? column.Name : property.Name, property);
                                    }
                                }
                            }
                        }
                        var entity = new T();
                        for (int i = 0; i < fieldCount; i++)
                        {
                            var meta = fieldInfos[i];
                            var data = Marshal.ReadIntPtr(currentRow, IntPtr.Size * i);
                            if (data == IntPtr.Zero || !propertyMap.ContainsKey(meta.name))
                            {
                                continue;
                            }
                            switch ((TDengineDataType)meta.type)
                            {
                                case TDengineDataType.TSDB_DATA_TYPE_BOOL:
                                    var @bool = Marshal.ReadByte(data) != 0;
                                    propertyMap[meta.name].SetValue(entity, @bool);
                                    break;

                                case TDengineDataType.TSDB_DATA_TYPE_TINYINT:
                                    var @sbyte = (sbyte)Marshal.ReadByte(data);
                                    propertyMap[meta.name].SetValue(entity, @sbyte);
                                    break;

                                case TDengineDataType.TSDB_DATA_TYPE_SMALLINT:
                                    var @short = (short)Marshal.ReadByte(data);
                                    propertyMap[meta.name].SetValue(entity, @short);
                                    break;

                                case TDengineDataType.TSDB_DATA_TYPE_INT:
                                    var @int = (int)Marshal.ReadByte(data);
                                    propertyMap[meta.name].SetValue(entity, @int);
                                    break;

                                case TDengineDataType.TSDB_DATA_TYPE_BIGINT:
                                    var @long = (long)Marshal.ReadByte(data);
                                    propertyMap[meta.name].SetValue(entity, @long);
                                    break;

                                case TDengineDataType.TSDB_DATA_TYPE_FLOAT:
                                    var @float = (float)Marshal.ReadByte(data);
                                    propertyMap[meta.name].SetValue(entity, @float);
                                    break;

                                case TDengineDataType.TSDB_DATA_TYPE_DOUBLE:
                                    var @double = (double)Marshal.PtrToStructure(data, typeof(double));
                                    if (propertyMap[meta.name].PropertyType.FullName.Contains("System.Decimal"))
                                    {
                                        propertyMap[meta.name].SetValue(entity, Convert.ToDecimal(@double));
                                    }
                                    else
                                    {
                                        propertyMap[meta.name].SetValue(entity, @double);
                                    }
                                    break;

                                case TDengineDataType.TSDB_DATA_TYPE_BINARY:
                                case TDengineDataType.TSDB_DATA_TYPE_NCHAR:
                                    var @stringAnsi = Marshal.PtrToStringUTF8(data, target[i]);
                                    propertyMap[meta.name].SetValue(entity, @stringAnsi);
                                    break;

                                case TDengineDataType.TSDB_DATA_TYPE_TIMESTAMP:
                                    var @timepStamp = Marshal.ReadInt64(data);
                                    if (propertyMap[meta.name].PropertyType.FullName.Contains("System.DateTime"))
                                    {

                                        //var @time1 = timepStamp.ToDateTime();
                                        timepStamp = timepStamp / 1000; //微秒除以1000转换成毫秒来计算时间
                                        var @time = timepStamp.TimeStampToDateTime(inMilli: true);
                                        propertyMap[meta.name].SetValue(entity, @time);
                                    }
                                    else
                                    {
                                        propertyMap[meta.name].SetValue(entity, @timepStamp);
                                    }
                                    break;

                                case TDengineDataType.TSDB_DATA_TYPE_USMALLINT:
                                    var @ushort = (ushort)Marshal.ReadByte(data); ;
                                    propertyMap[meta.name].SetValue(entity, @ushort);
                                    break;

                                case TDengineDataType.TSDB_DATA_TYPE_UINT:
                                    var @uint = (uint)Marshal.ReadByte(data); ;
                                    propertyMap[meta.name].SetValue(entity, @uint);
                                    break;

                                case TDengineDataType.TSDB_DATA_TYPE_UBIGINT:
                                    var @ulong = (ulong)Marshal.ReadByte(data); ;
                                    propertyMap[meta.name].SetValue(entity, @ulong);
                                    break;
                            }
                        }
                        result.Add(entity);
                    }
                    LogHelper.Warn("GetHisdata记录咯咯End4444");
                    TDengine.FreeResult(res);
                    LogHelper.Warn("GetHisdata记录咯咯End5555");
                    return result;
                //}

            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                //Close();
            }
===========================================================
插入数据代码如下
  public bool InsertData<T>(IEnumerable<IGrouping<string, T>> infos, string tableName) where T : class
        {
            var propertySet = new List<PropertyInfo>();
            var filedString = TDengineSql.BuildFileds<T>(ref propertySet);

            var builder = new StringBuilder("INSERT INTO ");
            foreach (var item in infos)
            {
                var sb = new StringBuilder($"{tableName + item.Key} USING {tableName} TAGS('{item.Key}') ({filedString}) VALUES ");
                foreach (var it in item)
                {
                    sb.Append("(");
                    foreach (var property in propertySet)
                    {
                        //if (property.GetValue(it)!= null &&( property.Name.ToLower() == "not0clockoritime" || property.Name.Contains("OriTime")))
                        //{
                        //    string aaaa = "";
                        //}
                        sb.Append(TDengineSql.BuildFileValue(property, it));
                        sb.Append(",");

                        //if (sb.ToString().Contains('/'))
                        //{
                        //    var aaa = item.ToList();
                        //}
                    }

                    sb.Remove(sb.Length - 1, 1);
                    sb.Append(") ");
                }
                builder.Append(sb.ToString());
            }
            LogHelper.Warn("AddHisData记录咯咯End1111");
            return Insert(builder.ToString(), tableName); //true;// 
            LogHelper.Warn("AddHisData记录咯咯End2222");
        }

        /// <summary>
        /// 插入数据
        /// </summary>
        /// <param name="sql"></param>
        /// <returns></returns>
        public bool Insert(string sql, string tablename)
        {
            try
            {
                //lock (ReadWriteLocker)
                //{//目前该控件多线程读写会报错,先加锁
                var res = TDengine.Query(connDic[tablename], sql);

                if ((res == IntPtr.Zero) || (TDengine.ErrorNo(res) != 0))
                {
                    if (res != IntPtr.Zero)
                    {
                        LogHelper.Error(@$"TDengine插入{tablename}报错:" + TDengine.Error(res));
                        throw new ArgumentException("reason: " + TDengine.Error(res));
                    }
                }
                return TDengine.AffectRows(res) > 0;
                //}
            }
            catch
            {
                throw;
            }
            finally
            {
                //Close();
            }
        }
========================================================

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
