### ISSUE TITLE
TDengine 3.0.2.2 cluster, It's 6 second for a new database created.

### ISSUE THREAD

**Issue by xltxb** [taosdata/TDengine#19497]
**General Questions**
A general question should be related to TDengine's user's manual, user experience, milestones, business cooperations etc. 
Before you ask a question, please:
hello team, I found It was very long time during create new database, here is the picture and logfile
![image](https://user-images.githubusercontent.com/5130103/211722449-bd56e35d-27d2-4d0e-a603-75830b429689.png)

[taosdlog0.log](https://github.com/taosdata/TDengine/files/10389028/taosdlog0.log)

If all the ways above couldn't help, please clearly and concisely describe what the question is.

**Comment by yu285** [comment]
Is it at this speed everytime?

**Comment by xltxb** [comment]
> 
yes , I created database many times and it took about the same amount of time each time.

**Comment by gccgdb1234** [comment]
The performance of creating database is in our plan to improve.

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
