### ISSUE TITLE
I ran a SQL like below and taosd crashed 

### ISSUE THREAD

**Issue by TheHolyChan** [taosdata/TDengine#19496]
I ran a SQL like below and taosd crash

![image](https://user-images.githubusercontent.com/122420902/211711781-49af22f0-a07d-412d-9b98-025033d03917.png)

version：3.0.2.2

**Comment by gccgdb1234** [comment]
Please share below information:
1. the statement of create database
2. the statement of create stable
3. how many rows are in the stable? If the data can be exported by taosdump and uploaded, it would be very helpful.
4. the statement of the query SQL. Please don't use a screenshot of your client code to describe the issue.

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
