### ISSUE TITLE
search subtable count'  can't  support  group by tag.

### ISSUE THREAD

**Issue by march3008** [taosdata/TDengine#1950]
taos> SELECT COUNT(TBNAME) FROM arc_device_type_00f4 group by company_id;

DB error: invalid SQL: retrieve tags not compatible with group by or interval query

taos> SELECT TBNAME FROM arc_device_type_00f4 group by company_id;

DB error: invalid SQL: retrieve tags not compatible with group by or interval query

**Comment by liuyq-617** [comment]
[https://www.taosdata.com/cn/documentation/super-table/#STable%E5%A4%9A%E8%A1%A8%E8%81%9A%E5%90%88](url)
Only field_name can use GROUP BY
