### ISSUE TITLE
init db when docker container run for the first time. 

### ISSUE THREAD

**Issue by WankkoRee** [taosdata/TDengine#19519]
**Is your feature request related to a problem? Please describe.**
I'm using TDengine for this use case: run `tdengine` docker image as a service. But I can not initialize the database automatically when docker container run for the first time.

将`tdengine`docker镜像作为一个服务启动时，我无法在它首次启动时自动初始化数据库。

**Describe your desired behavior**
Just like `docker-entrypoint-initdb.d` folder in `postgres` or `mysql` docker image.

就像`postgres`或者`mysql`docker镜像里的`docker-entrypoint-initdb.d`文件夹一样，可以在其中放置一些`.sql`脚本用于初始化数据库。

**Describe your solutions/suggestions if you've any**
Ditto.

同上。

**Additional context**

**Comment by yu285** [comment]
后续会逐渐完善，感谢您的反馈
