### ISSUE TITLE
Slow query problem locating

### ISSUE THREAD

**Issue by wupeng1234** [taosdata/TDengine#19527]
**Performance Issue** 
Any questions related to TDengine's performance can be discussed here.

**Problem Description** 
I have a table with more than 5000 pieces of data, and it takes more than 1.2 seconds to query the full amount or limit each time. May I ask how to locate the problem?

**DDL**
CREATE STABLE daily_kline (time timestamp, open double, close double, high double, low double, vary double, vary_rate double, pre_open double, pre_close double, pre_high double, pre_low double, pre_vary double, pre_vary_rate double, suf_open double, suf_close double, suf_high double, suf_low double, suf_vary double, suf_vary_rate double, volume double, turnover double, after_volume double, after_turnover double) TAGS (market nchar(4), type nchar(8));

**Environment (please complete the following information):**
* OS: [CentOS 7.0]
* Memory, CPU, current Disk Space：4c, 16g, 46g
* TDengine Version [3.0.1.4]

**Additional Context**

**Comment by yu285** [comment]
first please update it to  3.0.2.4 version

then please make sure no many repeated timestamp wrote into the normal-table .

**Comment by gccgdb1234** [comment]
3.0.1.4 is too old, please upgrade to 3.0.2.4 to try gain. If the query performane is still not good, please let us know.
