### ISSUE TITLE
Query speed different between different STABLE

### ISSUE THREAD

**Issue by pgCanal** [taosdata/TDengine#19521]
**Performance Issue** 
I have two STABLEs, and all in the same database, but with different query speed

**Problem Description** 
The two STABLEs are
trade: stock historical trade information. Total records: 97680030, 135 tables;
quote: stock historical order book information. Total records: 1220955598, 76 tables;

When I count the records in these two table. (multiple time)
trade 26 seconds
quote 0.27 seconds

**To Reproduce**

```sql
SELECT COUNT(*) FROM trade;
SELECT COUNT(*) FROM quote;
```

**Screenshots**

![image](https://user-images.githubusercontent.com/80063654/211894885-1ecda6b8-572b-440b-a292-5297b7f1e0cd.png)

![image](https://user-images.githubusercontent.com/80063654/211895269-325cbad9-31da-4c65-9e57-dac9c1337432.png)

**Environment (please complete the following information):**

* OS: Ubuntu 20.04.2 LTS
* Memory: 480 G, CPU 80 core, current Disk Space, 8T
* TDengine Version: 3.0.2.2

**Additional Context** 
I have done one thing may caused this issue. In my trade STABLE, some of the name need to be rename, so I used following commends for around 5 tables. Then the taos cli become extremely slow and frozen there.

```sql
INSERT INTO new_table_name SELECT * FROM old_table_name;
DROP TABLE old_table_name;
```

Thanks for helping in advance!

**Comment by yu285** [comment]
I guess the reason is that the first trade table  be updated too many times by insert duplicated timestamp .

it would lead to  many read block operation.

If convenient, you can add my WeChat :a15652223354 to verify  it .

**Comment by gccgdb1234** [comment]
INSERT INTO new_table_name SELECT * FROM old_table_name;  
This operation may generate a lot of out-of-order data, then the query performance is pretty poor, we are working to resolve this issue, the ETA is end of Febuary, 2023.
