### ISSUE TITLE
failed to execute batch bind,stmt API usage error

### ISSUE THREAD

**Issue by lliaozhijin** [taosdata/TDengine#19528]
tdengine3.0.2.2集群版，在使用参数绑定写入的时候，有数据往里写入，但是会有一直报stmt api使用错误，参数绑定写入的方式是使用官网提供的方式。消费kafka数据写入td。目前有疑惑为什么会出现这个错误，想请教大大帮忙看看是什么原因。
![10561673491531_ pic](https://user-images.githubusercontent.com/44841530/211965956-e44e7349-0e94-45eb-af75-c1ed8e9ebe93.jpg)

**Comment by sangshuduo** [comment]
@lliaozhijin  “官网提供的方式”具体是指哪个文档或者博客吗？

**Comment by lliaozhijin** [comment]
> 文

<img width="822" alt="image" src="https://user-images.githubusercontent.com/44841530/215974770-045bd708-200f-4070-aacd-133dc5155d88.png">

按照官网的参数绑定形式写入数据

**Comment by lliaozhijin** [comment]
> @lliaozhijin “官网提供的方式”具体是指哪个文档或者博客吗？

<img width="822" alt="image" src="https://user-images.githubusercontent.com/44841530/215975006-c69a2b98-51f2-494e-a47f-0ac1287c0749.png">
这种写入方式

**Comment by sangshuduo** [comment]
官方示例代码 https://github.com/taosdata/TDengine/blob/main/docs/examples/java/src/main/java/com/taos/example/StmtInsertExample.java 也有相同的问题吗？

**Comment by lld1995** [comment]
[ERROR]2023-12-25 13:36:56:code:[0x22a],error:Stmt API usage error
[ERROR]2023-12-25 13:36:56:   at TDengine.Driver.Client.Native.NativeStmt.StmtCheckError(Int32 code)
   at TDengine.Driver.Client.Native.NativeStmt.SetTableName(String tableName)
   at EmptyStrategy.MyStrategy.InsertQ(SkQuote q, String tableName, ITDengineClient client) in D:\project\bian\bian\Program.cs:line 247
   at EmptyStrategy.MyStrategy.AddQ(SkQuote q, String tableName, ITDengineClient client, Unit u, Boolean isFinal) in D:\project\bian\bian\Program.cs:line 259


c# 也有同样的问题，又看不出具体是什么原因。这版本改动简直大得离谱，幸好项目还没上线

**Comment by lld1995** [comment]
SetTableName 我估计是和这个有关

**Comment by lld1995** [comment]
把 SetTableName 改成字符串拼接后又报error: column type mis-match with buffer type

**Comment by lld1995** [comment]
报的错完全让人不明所以

**Comment by lld1995** [comment]
找到原因了，timestamp不能为long了，必须是datetime，真的无语死了。。
