### ISSUE TITLE
macOS 13.1 使用TDengine CLI连接远程数据库无响应

### ISSUE THREAD

**Issue by itouxin** [taosdata/TDengine#19538]
**Bug Description**
macOS 13.1 使用TDengine CLI连接远程数据库无响应

**To Reproduce**
左侧窗口为通过macOS连接k8s上的tdengine数据库，一直无响应；
右侧窗口为通过centos连接k8s上的tdengine数据库，可以正常使用；
![image](https://user-images.githubusercontent.com/16275395/211998685-35a3af06-47fa-40a4-a4ba-e3bd7985aba7.png)

同时，Java开发报错，提示无法加载动态链接库
![image](https://user-images.githubusercontent.com/16275395/212006077-93b67573-cb13-4819-b806-36beffb47a1c.png)

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: macOS 13.1
 - TDengine Version 3.0.2.3

**Additional Context**

**Comment by evenson419** [comment]
安装mac版本的connect客户端没有？还要对动态库文件做下软连，假如安装过客户端，动态库文件在/usr/local/lib下面
<img width="719" alt="image" src="https://user-images.githubusercontent.com/35451163/212231617-a6b3a8d3-d955-4236-b1a7-1d31f061af43.png">

**Comment by CorlyDream** [comment]
同样的问题，链接上无响应
![image](https://github.com/taosdata/TDengine/assets/3351366/26d3b290-5c80-451a-bed0-b58d2453cd05)

![image](https://github.com/taosdata/TDengine/assets/3351366/21393917-e07e-45aa-860d-c4a68fa98c28)
