### ISSUE TITLE
windows 客户端 JDBC 订阅 restart 不起作用的解决方法

### ISSUE THREAD

**Issue by zhuangQingGuang** [taosdata/TDengine#1953]
描述：jdbc 订阅 参数正确的情况下 restart（断点续传） 不起作用
版本：1.6.5.9
环境：windows
`subscribId = subscribe.subscribe(topic, rawSql, false, 1000, new CallBack("first"));
subscribe.unsubscribe(subscribId, true);`
查阅官方文档怀疑是没有保存定位信息导致；
经过官方研发小哥哥排查是 配置文件缺少路径导致
**解决方法**：
**在客户端配置文件中加入**：`dataDir  C:\TDengine\data`
**配置文件默认路径**：`C:\TDengine\cfg\taos.cfg`
![111](https://user-images.githubusercontent.com/45782190/82204055-cd4ed200-9936-11ea-957b-4990074ea1e4.png)
**解决后订阅信息生成路径**：`C:\TDengine\data\subscribe`

**Comment by Kittoa** [comment]
How to modify the default path of the configuration file（taos.cfg）

**Comment by zhuangQingGuang** [comment]
> How to modify the default path of the configuration file（taos.cfg）

2.0.3解决办法：
配置文件默认路径：`C:\TDengine\cfg\taos.cfg`
新增`dataDir C:\TDengine\data`
但是一定要自己手动新建文件夹`C:\TDengine\data\subscribe`
