### ISSUE TITLE
last_row() return wrong data in 3.0.1.7

### ISSUE THREAD

**Issue by aaaaaadi** [taosdata/TDengine#19535]
Centos7
taos版本：3.0.1.7

![image](https://user-images.githubusercontent.com/26601868/211968725-87554e84-57da-48e8-a6e3-f3df8aa62ae5.png)
从超级表或者子表查询last_row()，数据都与order by desc 查询的不同；
设备信息为tag，查询超级表不同设备的最新数据时返回列包含tag，查询时间很久，10条数据6s左右。
语句为select last_row(val) ,last_row(tag_name) from stable
从子表查询，多个设备（超过100）不支持union all
语句为 select  last_row(val) ,last_row(tag_name) from table1 union all select  last_row(val) ,last_row(tag_name) from table2...

**Comment by yu285** [comment]
请更换到 3.0.2.4  3.0.2.x 版本做过大量优化

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/

如果还有具体的使用问题，可以加微信：a15652223354

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
