### ISSUE TITLE
the super table with 20 million rows query performance issue 

### ISSUE THREAD

**Issue by wubaiqing** [taosdata/TDengine#19539]
**Bug Description**
超级表，使用 ROUND 搭配百分位 APERCENTILE 以及 't-digest' 参数时会报错。

**To Reproduce**

1. 超级里面的表数量，大约 2000W 左右；
2. 执行 SQL
```sql
SELECT count(*) as count, APERCENTILE(api_response_time, 50, 't-digest') AS percent50, APERCENTILE(api_response_time, 80, 't-digest') AS percent80, APE
RCENTILE(api_response_time, 90, 't-digest') AS percent90, APERCENTILE(api_response_time, 95, 't-digest') AS percent95 FROM api WHERE app_id=1 AND api
_http_status IN ('200', '304') AND time_server >= TODAY() AND time_server <= NOW() INTERVAL(1m) FILL(VALUE, 0);
```
3. 看到结果
![image](https://user-images.githubusercontent.com/1062448/212001223-c962f3ff-64cf-47e3-b4c8-61ed3089d7ff.png)

**Environment (please complete the following information):**
 - Ubuntu：8C、32G、4T；
 - TDengine Version：2.6.0.32

**Comment by yu285** [comment]
请问服务端有中止么

**Comment by wubaiqing** [comment]
> 请问服务端有中止么

没有遇到中止的情况，只是 2000W 数据时 count(*) 比较慢。

**Comment by yu285** [comment]
count 是另一个问题？可以加微信 a15652223354 做具体排查
