### ISSUE TITLE
partition by + fill return wrong data

### ISSUE THREAD

**Issue by jedy** [taosdata/TDengine#19532]
**Bug Description**
正确的查询结果是这样的：
```
select pid, _wstart, sum(success) from task_stat 
where ts >= 1673420400000000000 and ts < 1673452800000000000 and pid in (13627, 9171)
partition by pid interval (1h) fill(value, 0);
```
<img width="574" alt="image" src="https://user-images.githubusercontent.com/1589263/211977117-5cf436e7-5c5c-4b07-980e-81af7df647a2.png">
 去掉pid的条件会返回错误的结果。

```
select pid, _wstart, sum(success) from task_stat
where ts >= 1673420400000000000 and ts < 1673452800000000000
partition by pid interval (1h) fill(value, 0);
```
<img width="557" alt="image" src="https://user-images.githubusercontent.com/1589263/211977280-df91bc21-4136-46b4-9d11-14f1c2b6d5ef.png">
上面pid返回了null，下面的pid应该是9171。

task_stat的表结构

```
CREATE STABLE task_stat (
  ts TIMESTAMP,
  client_type TINYINT,
  client_group BIGINT UNSIGNED,
  client_ip INT UNSIGNED,
  success INT,
  failed INT,
  spend FLOAT
  )
  TAGS (
    pid INT
  );
```

**To Reproduce**
在我的数据库上每次都是这样。

**Environment (please complete the following information):**
 - OS: mac
 - TDengine Version 3.0.2.2，最新的docker镜像。

**Comment by yu285** [comment]
我们看下

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
