### ISSUE TITLE
taosd crashed

### ISSUE THREAD

**Issue by yanggang98** [taosdata/TDengine#19545]
**Bug Description**
用taosdemo插的数据，在版本2.2.2.10和2.6.0.34测试，插入8亿条数据后，过几天后就会频繁崩溃，请问这个bug在其他版本修复了吗。

![1673522176576_D12A4DE4-B655-45fb-8241-655891A3049F](https://user-images.githubusercontent.com/62869086/212055095-ef8f9bff-acbe-44b9-84d1-05473f123ef4.png)
![image](https://user-images.githubusercontent.com/62869086/212055349-3418e0b0-1dd6-4bb2-b582-d64e9893c96b.png)

**Environment (please complete the following information):**
 - OS:
Linux version 4.9.0-8-linx-security-amd64 (linx-kernel@linx-info.com) (gcc version 4.9.2 (Debian 4.9.2-10) ) #1 SMP Linx 4.9.130-2linx5 (2020-10-13)
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 2.2.2.10]
 - TDengine Version [2.6.0.34]

**Comment by yu285** [comment]
我们看下

**Comment by yu285** [comment]
触发崩溃的时候是什么操作呢？

**Comment by yanggang98** [comment]
> 触发崩溃的时候是什么操作呢？

没有进行其他操作，之前使用2.2时候发现产生了core文件，我们把版本升级到了2.6进行测试，也同样会产生这个问题。
使用taosdemo 插入假数据 insert.json 内容如下，第一条记录起始时间2022-12-27 13:30:00.000，产生8亿条数据，库的数据将保留 10天，从2023-01-07 13:30:00.000开始 ，就有部分数据被清除，产生core文件的时间是2023-01-12。期间没有做其他的操作。

`{
    "filetype":"insert",
    "cfgdir": "/etc/taos",
    "host": "127.0.0.1",
    "port": 6030,
    "user": "root",
    "password": "taosdata",
    "thread_count": 32,
    "num_of_records_per_req": 10,
    "thread_count_create_tbl": 4,
    "databases": [{
        "dbinfo": {
            "name": "db05",
            "drop": "yes",
            "replica": 1,
            "days": 10,
            "cache": 16,
            "blocks": 8,
            "precision": "ms",
            "update": 0,
	    "keep": 10
        },
        "super_tables": [{
            "name": "stb05",
            "childtable_count": 10000,
            "childtable_prefix": "stb05_",
            "auto_create_table": "no",
            "data_source": "rand",
            "insert_mode": "taosc",
            "insert_rate": 0,
            "insert_rows": 100000,
            "timestamp_step": 10000,
            "start_timestamp": "2022-12-27 13:30:00.000",
            "sample_format": "csv",
            "sample_file": "/home/data/sample.csv",
            "tags_file": "",
            "columns": [{
                "type": "INT"
            }],
            "tags": [{
                "type": "INT"
            }]
        }]
    }]
}`

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/

如果还有具体的使用问题，可以加微信：a15652223354
