### ISSUE TITLE
Upgrade to 3.0.2.3 Client compilation run exception

### ISSUE THREAD

**Issue by zeje** [taosdata/TDengine#19548]
升级到3.0.2.3后，业务系统不能正常运行。

开发机环境：3.0.2.2
驱动依赖：
`
        <dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>3.0.2</version>
        </dependency>
`
服务器环境：centos8下，openjdk version "1.8.0_312"

升级过程：

`
#停止服务

#卸载
rpm -e tdengine

wget https://www.taosdata.com/assets-download/3.0/TDengine-server-3.0.2.3-Linux-x64.rpm

rpm -iv TDengine-server-3.0.2.3-Linux-x64.rpm
`

此时，业务系统不重新编译，可正常运行。

在开发机原有环境下，业务系统重新编译，放至服务器上，报错UTL FATAL crash signal is 11。

更新开发机环境：

开发机环境：3.0.2.3
驱动依赖：
`
        <dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>3.0.3</version>
        </dependency>
`
之后：

windows下使用java 1.8.0_231编译，jdbc方式，混合（jdbc+restful）方式，java程序不能正常运行，报no taos in java.library.path。restful方式，运行正常
把1.8.0_231编译的java程序放服务器centos8下，openjdk version "1.8.0_312"环境，jdbc方式运行，报UTL FATAL crash signal is 11。restful方式运行正常。

windows下使用java 1.8.0_239编译，jdbc方式，或者restful方式，或者混合方式，java程序正常运行。
但把1.8.0_239编译的java程序放服务器centos8下，openjdk version "1.8.0_312"环境，jdbc方式运行，报UTL FATAL crash signal is 11。restful方式运行正常。

**Comment by gccgdb1234** [comment]
请升级至 3.0.2.4 ，这是 3.0.2.3 中的一个已知问题，我们已经紧急修复在春节前发布了 3.0.2.4

**Comment by zeje** [comment]
好的，我现在是拿main分支自己编译了
