### ISSUE TITLE
interval query return the data out of  time range

### ISSUE THREAD

**Issue by zhangruijie-star** [taosdata/TDengine#19558]
**Bug Description**
使用interval函数和fill填充时，查询结果出现超出的where限定时间范围

**Screenshots**
![SQL](https://user-images.githubusercontent.com/57881345/212270312-020328fc-ef16-4a50-8ce2-e7e82a28b09f.jpg)

**Environment (please complete the following information):**
 - OS: [macos Ventura 13.0.1]
 - CPU: [Apple M1 Pro ARM64]
 - TDengine Version [3.0.2.2]

**Comment by yu285** [comment]
https://mp.weixin.qq.com/s/Kc7wzzRiK4XhAsL48rD6dg

应该是时间切割时候窗口出现了交集，原理如上，可以看下。
