### ISSUE TITLE
2.6 执行INTERVAL(1d) FILL(VALUE,0)查询报错

### ISSUE THREAD

**Issue by junyan-zg** [taosdata/TDengine#19565]
goroutine 1289 [IO wait]:
internal/poll.runtime_pollWait(0x7fbaf8b7e718, 0x72, 0xffffffffffffffff)
	/home/ubuntu/soft/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc001f8b518, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/home/ubuntu/soft/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/home/ubuntu/soft/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc001f8b500, 0xc00205c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/ubuntu/soft/go/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc001f8b500, 0xc00205c000, 0x1000, 0x1000, 0x0, 0x7fbaf8b7e720, 0x0)
	/home/ubuntu/soft/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0005e4148, 0xc00205c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/ubuntu/soft/go/src/net/net.go:183 +0x91
net/http.(*connReader).Read(0xc00218b2c0, 0xc00205c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/ubuntu/soft/go/src/net/http/server.go:780 +0x1b9
bufio.(*Reader).fill(0xc000798900)
	/home/ubuntu/soft/go/src/bufio/bufio.go:101 +0x108
bufio.(*Reader).Peek(0xc000798900, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/soft/go/src/bufio/bufio.go:139 +0x4f
net/http.(*conn).readRequest(0xc002042320, 0x1df1290, 0xc00208fd80, 0x0, 0x0, 0x0)
	/home/ubuntu/soft/go/src/net/http/server.go:963 +0xec5
net/http.(*conn).serve(0xc002042320, 0x1df1338, 0xc00208fd80)
	/home/ubuntu/soft/go/src/net/http/server.go:1858 +0x705
created by net/http.(*Server).Serve
	/home/ubuntu/soft/go/src/net/http/server.go:2993 +0x39b

版本：docker tdengine/tdengine:2.6.0.10
INTERVAL   h级别以下的正常，d级别以上的程序崩溃

**Comment by yu285** [comment]
可以先换到 2.6.0.34 ，再做验证。如果还有问题我们来看下。

https://www.taosdata.com/engineering/10222.html

升级可参考

**Comment by yu285** [comment]
请问还有问题吗，咱做关闭处理，如有问题可以再open

**Comment by junyan-zg** [comment]
已验证通过，感谢
