### ISSUE TITLE
新环境部署每天执行insert操作2个月后select count(*)经常超时

### ISSUE THREAD

**Issue by luchangtx** [taosdata/TDengine#19573]
k8s集群新部署tdengine，代码层面rs访问
每天执行车辆信号数据2个月之后，select count(*) 经常超时，
直接去服务器shell 执行taos 查询语句，select count(*)要5、6秒，数据量600多万而已
部署版本3.0.18，如果是频繁写入导致的表膨胀问题，如何在不更新重新部署的前提下解决这个问题，毕竟更新有成本，
需要手动补数据很麻烦，还有就是表膨胀问题每次遇到就重新部署是生产环境没办法接受的呀。

版本：3.0.18

**Comment by sanliang125** [comment]
同样碰到这个问题。

**Comment by cmdares** [comment]
同问，顶起！

**Comment by gccgdb1234** [comment]
是否有乱序时间戳的数据？

**Comment by luchangtx** [comment]
1.利用taosdump导出数据
2.重新部署最新版本 3.0.2.4 tdengine
3.利用taosdump导入备份的数据
4.select count(*) 依然要好几秒，一千万的表要5-6秒；3亿的表要18-20秒，有时候会超时

**Comment by longcf6666** [comment]
同样，现在超级表已经上亿的数据，count(*)直接提示超时，查不出来了

**Comment by tobyforever** [comment]
同样遇到这个问题，select和count都一直卡着

**Comment by donnasky** [comment]
同问，count()四五十秒才能查出来

**Comment by yu285** [comment]
一般查询慢主要这几个原因：

1.数据被大量相同时间戳的数据覆盖过，导致碎片多，开源版数据导出再导入就行了。（企业版支持在线重组）

2.乱序比较多。

3. 数据库建模优化不够，可以参考：https://www.taosdata.com/tdengine-engineering/21550.html

4.最好在最新版（当前为 3.3.0.0）上测试，确保数据库本身版本处于最优。

5.最好在服务端测试，确保没有网络等其他因素干扰。

**Comment by fredmuyu** [comment]
> 一般查询慢主要这几个原因：
> 
> 1.数据被大量相同时间戳的数据覆盖过，导致碎片多，开源版数据导出再导入就行了。（企业版支持在线重组）
> 
> 2.乱序比较多。
> 
> 3. 数据库建模优化不够，可以参考：https://www.taosdata.com/tdengine-engineering/21550.html
> 
> 4.最好在最新版（当前为 3.3.0.0）上测试，确保数据库本身版本处于最优。
> 
> 5.最好在服务端测试，确保没有网络等其他因素干扰。

看了一下issues的一些问题，开源版本 
1、无法逻辑删除，导致空间不能立即释放，
2、还有这个碎片问题，

其实就是 不要用开源版在生产环境使用，不然后面必然会有问题，
