### ISSUE TITLE
集群批量查询报错，TDengine ERROR (80000130): Database is starting up

### ISSUE THREAD

**Issue by lowe00** [taosdata/TDengine#19579]
环境：3台服务器集群
TD版本：3.0.2.0
实现步骤：
共36000个设备，每批1000开始查询，查询一会程序中报错如下图
![image](https://user-images.githubusercontent.com/33248806/212630017-90d724ce-4f88-4ca3-b8d7-8e8fd2cd5107.png)
服务器上主节点也随之挂掉，taos日志报错如下图：
![image](https://user-images.githubusercontent.com/33248806/212629941-1f740f82-f49b-4ec8-a8dd-b33a8c6438a1.png)
相同查询逻辑及处理代码，在TD单机部署版本没有问题
更新问题，在统一了各服务器的系统编码格式后，查询仍然报错，主节点挂掉，taos日志如下图：
![image](https://user-images.githubusercontent.com/33248806/212638826-c54427ed-9386-4fbe-a3cc-c451dbeec202.png)

**Comment by gccgdb1234** [comment]
从上面的错误信息看，非常明显，locale 配置不对。或者是某个节点上实际的 locale 和 taos.cfg 中不一致，或者是 各节点之间不统一。
问题中还提到“统一了各服务器的系统编码格式”后问题仍然报错，建议重建集群再试试。

**Comment by lowe00** [comment]
> Contributor

在统一了各项配置之后的测试，依旧报错，且已重启过多次集群依旧还是不行。经多次测试，不加入条件查询，只按时间范围进行查询会有较小概率报错，多加一个条件查询（例如设备的id）则大概率报错

**Comment by yu285** [comment]
下午远程看下吧，你应该有我微信 a15652223354
