### ISSUE TITLE
打包放服务器 启动失败报错：crash signal is 11 

### ISSUE THREAD

**Issue by fwbcrazylang** [taosdata/TDengine#19582]
TD版本：3.0.2.3
驱动版本：3.0.3
JDK版本：1.8-261
本地IDEA，windows环境可以正常启动
![1cb99b304ad29ae49501efe37bf2c47](https://user-images.githubusercontent.com/59505395/212633365-860d2488-6e63-409c-bc9c-7b7d2f1ca3e7.png)
打包后，在服务器系统CentOs 7.6环境中启动不起来：

01/16 16:00:23.712367 00023399 UTL FATAL crash signal is 11 
01/16 16:00:23.712407 00023399 UTL FATAL sender PID:-721623936 cmdline: 
01/16 16:00:23.712616 00023399 UTL FATAL obtained 11 stack frames 

01/16 16:00:23.712621 00023399 UTL FATAL frame:0, /usr/local/java/jdk1.8.0_261/jre/lib/amd64/server/libjvm.so(+0x3ee533) [0x7f48d37a3533] 
01/16 16:00:23.712636 00023399 UTL FATAL frame:1, /usr/local/java/jdk1.8.0_261/jre/lib/amd64/server/libjvm.so(+0x33108a) [0x7f48d36e608a] 
01/16 16:00:23.712639 00023399 UTL FATAL frame:2, /usr/local/java/jdk1.8.0_261/jre/lib/amd64/server/libjvm.so(+0x3313a0) [0x7f48d36e63a0] 
01/16 16:00:23.712643 00023399 UTL FATAL frame:3, /usr/local/java/jdk1.8.0_261/jre/lib/amd64/server/libjvm.so(+0x331b28) [0x7f48d36e6b28] 
01/16 16:00:23.712647 00023399 UTL FATAL frame:4, /usr/local/java/jdk1.8.0_261/jre/lib/amd64/server/libjvm.so(+0x48dc2c) [0x7f48d3842c2c] 
01/16 16:00:23.712650 00023399 UTL FATAL frame:5, /usr/local/java/jdk1.8.0_261/jre/lib/amd64/server/libjvm.so(+0x48f868) [0x7f48d3844868] 
01/16 16:00:23.712654 00023399 UTL FATAL frame:6, /usr/local/java/jdk1.8.0_261/jre/lib/amd64/server/libjvm.so(+0xa8614b) [0x7f48d3e3b14b] 
01/16 16:00:23.712658 00023399 UTL FATAL frame:7, /usr/local/java/jdk1.8.0_261/jre/lib/amd64/server/libjvm.so(+0xa86451) [0x7f48d3e3b451] 
01/16 16:00:23.712661 00023399 UTL FATAL frame:8, /usr/local/java/jdk1.8.0_261/jre/lib/amd64/server/libjvm.so(+0x914d12) [0x7f48d3cc9d12] 
01/16 16:00:23.712664 00023399 UTL FATAL frame:9, /lib64/libpthread.so.0(+0x7ea5) [0x7f48d4b9bea5] 
01/16 16:00:23.712667 00023399 UTL FATAL frame:10, /lib64/libc.so.6(clone+0x6d) [0x7f48d44a8b0d]

**Comment by huolibo** [comment]
为已知问题，需要将 TD 升级为 3.0.2.4 版本。

**Comment by wanlishiwunian** [comment]
兄弟，我也报同样的错误，但是我用另一个服务器安装td后，服务还是报错

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
