### ISSUE TITLE
超级表举例中的meters怎么翻译

### ISSUE THREAD

**Issue by chenqian1995** [taosdata/TDengine#19593]
![image](https://user-images.githubusercontent.com/50002319/212792352-56bf201d-39b9-4fcd-9428-6a5731d1f4c1.png)

**Comment by chenqian1995** [comment]
那个metrics  很好翻译，指标，容易懂。这个meters 实在不好理解

**Comment by sangshuduo** [comment]
> 那个metrics 很好翻译，指标，容易懂。这个meters 实在不好理解

电表。准确的说是智能电表
