### ISSUE TITLE
Stream Processing  use much memory

### ISSUE THREAD

**Issue by ttrrooorr** [taosdata/TDengine#19599]
**Performance Issue** 
Stream Processing (流式计算) , 使用太多的記憶體,是否合理,該如何限制 Stream Processing使用的 memory

**Problem Description** 
我建立16個 stream processing , memory 會使用到 2375 MB
如果建立 48 個 stream processing , memory會高達 8746 MB

**To Reproduce**
1. taos -f dbs.sql

**Screenshots**

**Environment (please complete the following information):**

* OS: windows 10
* Memory:8746MB
* CPU:0.1%
* current Disk Space : 152MB
* TDengine Version : 3.0.2.3

**Additional Context** 
![taosd](https://user-images.githubusercontent.com/104811441/212819160-3c7fab3f-0c7a-4e5d-9ab4-cd0cf63c82ba.png)

[tdengine.zip](https://github.com/taosdata/TDengine/files/10431826/tdengine.zip)

**Comment by yu285** [comment]
收到，我们看下

**Comment by yu285** [comment]
8746/48MB = 182MB。平均一个流占用182兆内存，这个是合理现象。

**Comment by ttrrooorr** [comment]
> 8746/48MB = 182MB。平均一个流占用182兆内存，这个是合理现象。

謝謝,能否調整每個流的內存?

**Comment by yu285** [comment]
这个暂时不能，后面版本会开启流数量的可配置，按需使用即可。
