### ISSUE TITLE
connection issue

### ISSUE THREAD

**Issue by 70kgcoding** [taosdata/TDengine#19642]
![image](https://user-images.githubusercontent.com/49628826/213137948-0e495921-b521-467d-a266-54275653ad54.png),

'Mnode not found' 这是什么意思，应该如何处理？

**Comment by sangshuduo** [comment]
systemctl status taosd 输出什么？

**Comment by yu285** [comment]
连接问题 https://www.taosdata.com/engineering/11076.html 看下问题1 排查一下

**Comment by 70kgcoding** [comment]
> systemctl status taosd 输出什么？

![image](https://user-images.githubusercontent.com/49628826/215300497-647ceae0-b3d0-4fec-b40e-6ae5255e1aaf.png)

**Comment by 70kgcoding** [comment]
> 连接问题 https://www.taosdata.com/engineering/11076.html 看下问题1 排查一下

参考了这个，现在可以连上了，感谢各位的帮助
