### ISSUE TITLE
A performance issue result from "limit 0"

### ISSUE THREAD

**Issue by 13612858893** [taosdata/TDengine#19678]
**Bug Description**
limit 0疑似造成全表查询BUG

**To Reproduce**
今天从2.6.0.32切换到3.0.2.1后，发现三个节点的CPU（每节点采用32核心的CPU）使用率均超过90%，而在原来的2.6.0.32环境下，CPU的占用率还没有超过10%，下图为其中一个节点。
![db808bfeebf74827bba43ce14441b2f](https://user-images.githubusercontent.com/111417004/215243273-eda91bce-855e-406a-a497-22fc0048ee34.png)

通过show queries查看，发现有两个select * from t XXX limit 0;
在两个环境分别执行发现用时相差3万多倍，3.0.2.1用时如下
![fcbca0a8812aceeb55daab51e278f88](https://user-images.githubusercontent.com/111417004/215243425-ca1523b0-4d85-4ebd-8b14-9684ea6cbbc7.png)
2.6.0.32用时如下
![image](https://user-images.githubusercontent.com/111417004/215243463-85e47425-c054-4b75-bbc3-6e1d8c44a4bb.png)

接下来在3.0.2.1环境中把语句改成select * from t XXX limit 1后，用时由74秒下降到0.03秒，回归正常，如下图所示。

最后把两个环境的对比图放出来（3.0的CPU使用率降下来后，查询速度有所提升）
![1674884446826](https://user-images.githubusercontent.com/111417004/215248381-edef5d19-1bb4-478e-a449-c61d3dbcc699.png)

![image](https://user-images.githubusercontent.com/111417004/215248373-b8b2c6d9-a553-4186-b239-4225ac94338a.png)

另外，这两个环境的配置、表结构都是一样的，从细节上来看，2.6.0.32的查询的18ms还是低于3.0.2.1的30ms。

**Comment by yu285** [comment]
收到我们看下

**Comment by hjxilinx** [comment]
@13612858893 
请问 
`select count(*) from t_qualityproductdetail`

执行时间多长？结果是什么？

**Comment by hjxilinx** [comment]
该问题已经修复，整合在下一个发布版本中。
