### ISSUE TITLE
python中异步查询与taos客户端查询结果不一致

### ISSUE THREAD

**Issue by timeobject** [taosdata/TDengine#19676]
**Bug Description**
python中异步查询与taos客户端查询的数据记录不一致

**To Reproduce**
操作系统：linux
TDengine：2.6.0.18
taospy：2.6.7
python：3.9.2
单机器，没有集群，查询的ticks是超级表，子表数千个。
异步代码采用python示例代码：https://docs.taosdata.com/2.6/develop/query-data/

taos查询结果如下：
```
taos> select count(*) from ticks;
       count(*)        |
========================
             497684728 |
Query OK, 1 row(s) in set (5.228109s)
```

python异步查询结果如下：
部分代码：
```
def test_query(conn):
    counter = Counter(count=0)
    conn.query_a("SELECT * FROM ticks;", query_callback, byref(counter))

    while not counter.done:
        print(counter)
        time.sleep(1)
    print(counter)
```
打印
```
...
{ count: 127223057, done: False }
fetching completed
{ count: 127293861, done: True }
```
**Expected Behavior**
python中返回的结构应该和taos客户端返回的结果一致。

**Comment by sunpe** [comment]
不建议直接 fetch 4亿数据，示例代码运行的时候应该伴随着 `taos.error.OperationalError: [0x020f]: Query terminated` 异常。

代码中的 Counter 仅仅是 fetch 出的数据条数，不代表数据库中数据的总条数，如果需要 count 数据条数，可以使用 `select count(*)` 语句。示例代码在（正常或异常） fetch 完之后，fetch 状态都会是 `done`。

**Comment by timeobject** [comment]
> 

如果需要在自己的应用中查询大量数据应该怎么查询？

**Comment by timeobject** [comment]
> 不建议直接 fetch 4亿数据，示例代码运行的时候应该伴随着 `taos.error.OperationalError: [0x020f]: Query terminated` 异常。
> 
> 代码中的 Counter 仅仅是 fetch 出的数据条数，不代表数据库中数据的总条数，如果需要 count 数据条数，可以使用 `select count(*)` 语句。示例代码在（正常或异常） fetch 完之后，fetch 状态都会是 `done`。

如果需要在自己的应用中查询大量数据应该怎么查询？

**Comment by sangshuduo** [comment]
> > 不建议直接 fetch 4亿数据，示例代码运行的时候应该伴随着 `taos.error.OperationalError: [0x020f]: Query terminated` 异常。
> > 代码中的 Counter 仅仅是 fetch 出的数据条数，不代表数据库中数据的总条数，如果需要 count 数据条数，可以使用 `select count(*)` 语句。示例代码在（正常或异常） fetch 完之后，fetch 状态都会是 `done`。
> 
> 如果需要在自己的应用中查询大量数据应该怎么查询？

时序数据通常更专注趋势。如果确实需要查询全量数据可以使用 offset 多次逐段查询。

**Comment by timeobject** [comment]
@sangshuduo 趋势也需要数据去计算的，就是不支持大量查询是吗，那么最大可以查询多少条数据好像文档并未说明，不查全量数据我查当天数据呢，但是我当天数据可能也很多，几千万条，是否可以一次查询千万级别？还是多少？谢谢。

**Comment by sangshuduo** [comment]
> @sangshuduo @sunpe 趋势也需要数据去计算的，就是不支持大量查询是吗，那么最大可以查询多少条数据好像文档并未说明，不查全量数据我查当天数据呢，但是我当天数据可能也很多，几千万条，是否可以一次查询千万级别？还是多少？谢谢。

查询条数没有现在，是查询执行时间不建议太长，会降低系统总的性能，所以希望尽量缩小每次查询范围，如果确实遇到查询超时，可以在 taos.cfg 里配置 shellActivityTimer 这个参数

**Comment by timeobject** [comment]
@sangshuduo shellActivityTimer文档说是shell 客户端向 mnode 发送心跳间隔，那么我用python或者C++库连接怎么设置这个参数呢？这个参数是心跳时间，似乎不能解决查询大量数据的问题。你的意思是查询大量数据，影响了系统性能，心跳时间过短的话，会引起查询超时而结束，所以导致查询的数据不完整？

**Comment by sangshuduo** [comment]
> @sangshuduo shellActivityTimer文档说是shell 客户端向 mnode 发送心跳间隔，那么我用python或者C++库连接怎么设置这个参数呢？这个参数是心跳时间，似乎不能解决查询大量数据的问题。你的意思是查询大量数据，影响了系统性能，心跳时间过短的话，会引起查询超时而结束，所以导致查询的数据不完整？

python 连接器或任何其他使用 taosc 驱动的都是适用这个参数的。
时序数据库的数据量非常大，通常不建议查询大量数据处理，TDengine 本身提供了聚合函数和各种条件查询可以满足绝大部分场景。默认心跳时间较短就是设计的行为。扩大心跳时间查询大量数据对系统内存压力也很大。

**Comment by timeobject** [comment]
@sangshuduo 好的，感谢解答。不能一次查询大量数据是吧，那只能在业务上想办法优化了。
