### ISSUE TITLE
taosadapter 使用中, 内存消耗越来越大, 是否为存在泄漏

### ISSUE THREAD

**Issue by htbig** [taosdata/TDengine#19677]
**Bug Description**
taosadapter 使用中, 内存消耗越来越大, 是否为存在泄漏

**To Reproduce**
1. 部署taosadapter
2. 使用influxdb client 写入数据
3. 查看taosadapter, 内存消耗变大

**Screenshots**
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
18226 root      20   0  107.2g  99.0g  16052 S   0.3 80.0 658:32.53 taosadapter

**Environment (please complete the following information):**
 - CentOS 7.0
 - TDengine Version 3.0.2.4, 0abd58a95e (HEAD, origin/main

trace libc 内存使用情况, 发现内存泄漏栈为
        taosMemoryMalloc+24
        taosHashInit+362
        smlInitHandle+78
        smlBuildSmlInfo+724
        taos_schemaless_insert_inner+771
        taos_schemaless_insert_raw_ttl_with_reqid+460
        taos_schemaless_insert_raw+71
        _cgo_c584c35eb21b_Cfunc_taos_schemaless_insert_raw+42
        github.com/taosdata/driver-go/v3/wrapper._Cfunc_taos_schemaless_insert_raw.abi0+77
        github.com/taosdata/driver-go/v3/wrapper.TaosSchemalessInsertRaw.func2+411
        github.com/taosdata/driver-go/v3/wrapper.TaosSchemalessInsertRaw+203
        github.com/taosdata/taosadapter/v3/schemaless/capi.InsertInfluxdb+329
        github.com/taosdata/taosadapter/v3/plugin/influxdb.(*Influxdb).write+3196
        github.com/taosdata/taosadapter/v3/plugin/influxdb.(*Influxdb).write-fm+44
        github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1+130
        github.com/taosdata/taosadapter/v3/log.GinRecoverLog.func1+398
        github.com/taosdata/taosadapter/v3/log.GinLog.func1+237
        github.com/gin-gonic/gin.(*Engine).handleHTTPRequest+1649
        github.com/gin-gonic/gin.(*Engine).ServeHTTP+477
        net/http.serverHandler.ServeHTTP+780
        net/http.(*conn).serve+1543
        net/http.(*Server).Serve.func3+46
        runtime.goexit.abi0+1

if (code != TSDB_CODE_SUCCESS) {
      info->pRequest->body.queryFp(info, req, code);
}
成功的请求, 不调用callback, 不destroy info
当然也存在其他内存泄漏的地方, 

请确定一下改问题

**Comment by wangmm0220** [comment]
看代码里smlInitHandle分配的内存，再调用结束时会释放，并且之前内存泄漏检测也没有发现这个地方有泄漏。
你是否调用了 taos_free_result 函数来释放每次调用schemaless的结果？ 这个结果每次都需要调用taos_free_result来释放
