### ISSUE TITLE
Can the data be written directly to the disk, not to the cache? 

### ISSUE THREAD

**Issue by zzboy** [taosdata/TDengine#1968]
**Bug Description**

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by Shawshank-Smile** [comment]
why you do that thing?

**Comment by zzboy** [comment]
> why you do that thing?

必须写透，不然会丢数据啊

**Comment by jtao1735** [comment]
> > why you do that thing?
> 
> 必须写透，不然会丢数据啊

2.0版会有选项，容许你写透、不写透或根本就不写WAL

**Comment by zzboy** [comment]
> > > why you do that thing?
> > 
> > 
> > 必须写透，不然会丢数据啊
> 
> 2.0版会有选项，容许你写透、不写透或根本就不写WAL

2.0什么时候发布，陶老师

**Comment by jtao1735** [comment]
> > > > why you do that thing?
> > > 
> > > 
> > > 必须写透，不然会丢数据啊
> > 
> > 
> > 2.0版会有选项，容许你写透、不写透或根本就不写WAL
> 
> 2.0什么时候发布，陶老师

估计还有一个月的时间。但你现在就可以看到我们代码，在develop分支上。

**Comment by zhuqiyun** [comment]
具体什么时候发布啊，准备直接用2.0

**Comment by sangshuduo** [comment]
2.0 已经发布，当前版本2.0.3.0
