### ISSUE TITLE
 ERROR DND QInfo:(nil), qhandle:0x7f29440213a0 is not matched with saved:(nil)

### ISSUE THREAD

**Issue by Eduardo95** [taosdata/TDengine#197]
你好，我通过csv导入了1千万条数据，导入以后通过命令行查询全量数据时会报如下错误
 ERROR DND QInfo:(nil), qhandle:0x7f29440213a0 is not matched with saved:(nil)

当我限制返回数量时，也会出现相同的错误，并且无法返回正确的结果。
请问这是什么原因呢？谢谢

**Comment by hzcheng** [comment]
您是在shell中通过select * 查询吗？结果全都打印到屏幕吗？

**Comment by Eduardo95** [comment]
是的，通过select *查询，结果全部打印

**Comment by Eduardo95** [comment]
并且每次会打印4096条，8192条或者12288条的时候中断

**Comment by hzcheng** [comment]
问题应该是这样的，服务端内部有一个计时器，对每个查询都会有计时，如果过了某个时间，客户端的这个查询没有来拉取数据，服务端会关闭这个连接，因为有可能客户端放弃这个查询了，服务端不可能永远等待。在用select *输出到屏幕时，由于输出到屏幕会消耗比较多的时间，导致客户端没有及时去服务端取下一段数据，因此服务端将查询关闭了。您可以用 select * from st >> t; 将所有数据导入到一个文件t中，看是否能全部导出来。
