### ISSUE TITLE
TDengine 3.x 中taosKeeper采集指标失败

### ISSUE THREAD

**Issue by 741406143wkf** [taosdata/TDengine#19704]
![image](https://user-images.githubusercontent.com/41145896/215379051-3dc1800b-6568-4556-a06e-333d5457eea9.png)
![image](https://user-images.githubusercontent.com/41145896/215379132-c899a98c-0696-4534-83a2-a02b93c74a82.png)

**Comment by sangshuduo** [comment]
https://github.com/taosdata/taoskeeper/blob/master/README.md

Cannot receive log from TDengine server.

**Answer**: Modify `/etc/taos/taos.cfg` file and add parameters like:

```
monitor                  1  // start monitor
monitorInterval          30  // send log interval (s)
monitorFqdn              localhost 
monitorPort              6043 // taosKeeper port
monitorMaxLogs           100
```

**Comment by 741406143wkf** [comment]
问题已解决 建议官网文档也添加相关信息
