### ISSUE TITLE
failed to search data, RPC ERROR SHELL | failed to send | Operation now in progress

### ISSUE THREAD

**Issue by yungchow** [taosdata/TDengine#19719]
**Bug Description**
使用taos-jdbcdriver连接tdengine，14个线程同时发起查询，其中一个线程获取到数据库连接后发生中断，没有任何返回，Java客户端未捕捉到异常

**To Reproduce**
偶发

**Expected Behavior**
期望正确返回查询结果

**Screenshots**
![taos_error](https://user-images.githubusercontent.com/15307067/215697753-20500ab2-7cb3-4d2b-8f09-69437ffa258c.png)

**Environment (please complete the following information):**
 - OS: Red Hat Enterprise Linux release 8.2 (Ootpa)
 - Memory, CPU, current Disk Space
 - TDengine Version 2.6.0.6

**Additional Context**

**Comment by yu285** [comment]
可以尝试 在客户端配置文件增加 rpcForceTcp    1

再做尝试

该参数用于强制使用 tcp 通信，不使用 udp

**Comment by yungchow** [comment]
由于之前出现过查询不到结果的问题,所以我们已经在客户端配置文件已经添加了 rpcForceTcp 1.
这次不同于查询不到结果,而是查询的线程一直卡在:
at com.taosdata.jdbc.TSDBJNIConnector.executeQueryImp(Native Method)
这里不动了
<img width="1234" alt="Screen Shot 2023-02-09 at 18 09 47" src="https://user-images.githubusercontent.com/15307067/217783019-28903df4-cabd-4f09-9a26-f215d162a2ae.png">

**Comment by yungchow** [comment]
> 可以尝试 在客户端配置文件增加 rpcForceTcp 1
> 
> 再做尝试
> 
> 该参数用于强制使用 tcp 通信，不使用 udp

由于之前出现过查询不到结果的问题,所以我们已经在客户端配置文件已经添加了 rpcForceTcp 1.
这次不同于查询不到结果,而是查询的线程一直卡在:
at com.taosdata.jdbc.TSDBJNIConnector.executeQueryImp(Native Method)
这里不动了
![Uploading Screen Shot 2023-02-09 at 18.09.47.png…]()

**Comment by yu285** [comment]
具体的 SQL 语句是什么样的呢，服务端的表结构也发一下吧

**Comment by yungchow** [comment]
> 

查询语句:
select * from pfactor._A_14_done_profit_loss_SM00202301280007_3 where date_time>'2023-01-30 09:57:07.000' and date_time<='2023-01-30 11:26:12.901'

超级表:
CREATE TABLE IF NOT EXISTS ims_factor_info(date_time timestamp,factor_name NCHAR(64),factor_value FLOAT) TAGS (factor_key NCHAR(200),model_id NCHAR(200),cus_number NCHAR(20), seq BINARY(30));

另:我们在插入的场景也遇到过类似问题(怀疑不是表结构的问题)

**Comment by yu285** [comment]
> > 
> 
> 查询语句: select * from pfactor._A_14_done_profit_loss_SM00202301280007_3 where date_time>'2023-01-30 09:57:07.000' and date_time<='2023-01-30 11:26:12.901'
> 
> 超级表: CREATE TABLE IF NOT EXISTS ims_factor_info(date_time timestamp,factor_name NCHAR(64),factor_value FLOAT) TAGS (factor_key NCHAR(200),model_id NCHAR(200),cus_number NCHAR(20), seq BINARY(30));
> 
> 另:我们在插入的场景也遇到过类似问题(怀疑不是表结构的问题)

也就是说，不论查询还是写入都会出现一样的 rpc 的报错对吗？

**Comment by yungchow** [comment]
> > > 
> > 
> > 
> > 查询语句: select * from pfactor._A_14_done_profit_loss_SM00202301280007_3 where date_time>'2023-01-30 09:57:07.000' and date_time<='2023-01-30 11:26:12.901'
> > 超级表: CREATE TABLE IF NOT EXISTS ims_factor_info(date_time timestamp,factor_name NCHAR(64),factor_value FLOAT) TAGS (factor_key NCHAR(200),model_id NCHAR(200),cus_number NCHAR(20), seq BINARY(30));
> > 另:我们在插入的场景也遇到过类似问题(怀疑不是表结构的问题)
> 
> 也就是说，不论查询还是写入都会出现一样的 rpc 的报错对吗？

是的,写入是不同的超级表,现象都是执行读/写的线程卡在at com.taosdata.jdbc.TSDBJNIConnector.executeQueryImp(Native Method)

**Comment by yu285** [comment]
连接使用的ip 是内网还是外网 ip 呢

**Comment by yungchow** [comment]
> 连接使用的ip 是内网还是外网 ip 呢

都是内网ip

**Comment by yu285** [comment]
两个思路吧 一是先换成2.6.0.34 和最新的 2.0.40 , 看看是否有同样问题。如果没有问题最好，有问题的话，则继续定位。

第二是，在现有版本继续调试，可以使用 taosdemo 使用 json 的方式模拟并发查询/写入 看是否有问题，如果有的话则是 TDengine 本身的问题，若没有可能是jdbc这一侧的问题。

**Comment by yungchow** [comment]
> 两个思路吧 一是先换成2.6.0.34 和最新的 2.0.40 , 看看是否有同样问题。如果没有问题最好，有问题的话，则继续定位。
> 
> 第二是，在现有版本继续调试，可以使用 taosdemo 使用 json 的方式模拟并发查询/写入 看是否有问题，如果有的话则是 TDengine 本身的问题，若没有可能是jdbc这一侧的问题。

一个小疑问,为什么不是建议直接升到3.0

**Comment by yu285** [comment]
> > 两个思路吧 一是先换成2.6.0.34 和最新的 2.0.40 , 看看是否有同样问题。如果没有问题最好，有问题的话，则继续定位。
> > 第二是，在现有版本继续调试，可以使用 taosdemo 使用 json 的方式模拟并发查询/写入 看是否有问题，如果有的话则是 TDengine 本身的问题，若没有可能是jdbc这一侧的问题。
> 
> 一个小疑问,为什么不是建议直接升到3.0

因为底层数据文件变化较大，不兼容，所以升级需要把数据导出再导入，比较麻烦。

如果可以在新环境完全使用 3.x 自然最好的了

**Comment by HeheYang** [comment]
> 
换成2.6.0.34 和最新的 2.0.40之后还是不行， rpcForceTcp 1 也加了，我们在进行批量插入过程中，就会出现以上问题，卡住不动了，at com.taosdata.jdbc.TSDBJNIConnector.executeQueryImp(Native Method)

**Comment by HeheYang** [comment]
> > > 两个思路吧 一是先换成2.6.0.34 和最新的 2.0.40 , 看看是否有同样问题。如果没有问题最好，有问题的话，则继续定位。
> > > 第二是，在现有版本继续调试，可以使用 taosdemo 使用 json 的方式模拟并发查询/写入 看是否有问题，如果有的话则是 TDengine 本身的问题，若没有可能是jdbc这一侧的问题。
> > 
> > 
> > 一个小疑问,为什么不是建议直接升到3.0
> 
> 因为底层数据文件变化较大，不兼容，所以升级需要把数据导出再导入，比较麻烦。
> 
> 如果可以在新环境完全使用 3.x 自然最好的了

换成2.6.0.34 和最新的 2.0.40之后还是不行， rpcForceTcp 1 也加了，我们在进行批量插入过程中，就会出现以上问题，卡住不动了，at com.taosdata.jdbc.TSDBJNIConnector.executeQueryImp(Native Method)

**Comment by thicktao** [comment]
我们也出现这个问题，版本是2.6.0.10，centos 7 容器部署 taos_query 就一直卡起，可以卡两天以上不断开，重启客户端，可以解决这个问题，但是数据丢失了，因为数据都在客户端堵着了 @yu285
ERROR SHELL 0x7fd930f10090 0x29c, failed to send, msgLen:2163 written:-1, reason:Operation now in progress

**Comment by yu285** [comment]
> 我们也出现这个问题，版本是2.6.0.10，centos 7 容器部署 taos_query 就一直卡起，可以卡两天以上不断开，重启客户端，可以解决这个问题，但是数据丢失了，因为数据都在客户端堵着了 @yu285 ERROR SHELL 0x7fd930f10090 0x29c, failed to send, msgLen:2163 written:-1, reason:Operation now in progress

请问也是多线程模式下遇到么？

**Comment by yu285** [comment]
> > > > 两个思路吧 一是先换成2.6.0.34 和最新的 2.0.40 , 看看是否有同样问题。如果没有问题最好，有问题的话，则继续定位。
> > > > 第二是，在现有版本继续调试，可以使用 taosdemo 使用 json 的方式模拟并发查询/写入 看是否有问题，如果有的话则是 TDengine 本身的问题，若没有可能是jdbc这一侧的问题。
> > > 
> > > 
> > > 一个小疑问,为什么不是建议直接升到3.0
> > 
> > 
> > 因为底层数据文件变化较大，不兼容，所以升级需要把数据导出再导入，比较麻烦。
> > 如果可以在新环境完全使用 3.x 自然最好的了
> 
> 换成2.6.0.34 和最新的 2.0.40之后还是不行， rpcForceTcp 1 也加了，我们在进行批量插入过程中，就会出现以上问题，卡住不动了，at com.taosdata.jdbc.TSDBJNIConnector.executeQueryImp(Native Method)

您这边也是多线程模式的时候遇到的么

**Comment by HeheYang** [comment]
> 

是的，是在多线程情况下进行查询或者写入出现了此类情况

**Comment by HeheYang** [comment]
> > > > > 两个思路吧 一是先换成2.6.0.34 和最新的 2.0.40 , 看看是否有同样问题。如果没有问题最好，有问题的话，则继续定位。
> > > > > 第二是，在现有版本继续调试，可以使用 taosdemo 使用 json 的方式模拟并发查询/写入 看是否有问题，如果有的话则是 TDengine 本身的问题，若没有可能是jdbc这一侧的问题。
> > > > 
> > > > 
> > > > 一个小疑问,为什么不是建议直接升到3.0
> > > 
> > > 
> > > 因为底层数据文件变化较大，不兼容，所以升级需要把数据导出再导入，比较麻烦。
> > > 如果可以在新环境完全使用 3.x 自然最好的了
> > 
> > 
> > 换成2.6.0.34 和最新的 2.0.40之后还是不行， rpcForceTcp 1 也加了，我们在进行批量插入过程中，就会出现以上问题，卡住不动了，at com.taosdata.jdbc.TSDBJNIConnector.executeQueryImp(Native Method)
> 
> 您这边也是多线程模式的时候遇到的么

是的，是在多线程情况下进行查询或者写入出现了此类情况

**Comment by yu285** [comment]
在查询/写入卡住期间，请执行一下 top -Hp `pidof taosd` 坚持是否有线程达到瓶颈状态。

**Comment by yu285** [comment]
pidof taosd 两侧加上反引号，github不显示

**Comment by HeheYang** [comment]
![image](https://user-images.githubusercontent.com/19985390/221502554-40ca6c5e-25b3-4e4e-8fa0-7f665a6b7de2.png)

**Comment by yungchow** [comment]
用100个线程同时通过同一个连接执行插入操作,插入到同一张表可以必现,如下是客户端和服务端的日志文件
[taoslog.zip](https://github.com/taosdata/TDengine/files/10848949/taoslog.zip)
@yu285

**Comment by yu285** [comment]
👌我们看下
