### ISSUE TITLE
查询按desc排序，查询结果排序不正确

### ISSUE THREAD

**Issue by longcf6666** [taosdata/TDengine#19724]
![企业微信截图_20230201095730](https://user-images.githubusercontent.com/98379149/215927448-dcac387b-e305-4d49-8025-e23ce2f86211.png)
![企业微信截图_20230201095840](https://user-images.githubusercontent.com/98379149/215927452-9f3071a3-3e11-4afa-8265-8fda1e9aae21.png)
查询按时间倒排序，如图1，03:42:23分的排在了最前，查询结果往下拉，如图2的09:56:34分才是应该排在最前的。
同样的查询sql，存在查询某些表排序正常，某些表不正常，这些子表都是同一个超级表。
涛思版本号：3.0.1.8

**Comment by yu285** [comment]
请更新到 3.0.2.5 ，问题已经解决过。

**Comment by GYFgaoyuefei** [comment]
3.0.3.2依旧遇到这个问题
