### ISSUE TITLE
TDengine-server-3.0.2.4-Windows-x64 中taosdump 导入报错

### ISSUE THREAD

**Issue by QIANGEGEGE** [taosdata/TDengine#19726]
win最新版本下，导入数据出现以下异常
`INFO: [2]:32%
.OK: [3] 4978 row(s) of file(iot_temp.3350455873297.1248.avro) be successfully dumped in!
.OK: [7] 4948 row(s) of file(iot_temp.3350455990292.286.avro) be successfully dumped in!
.OK: [6] 2187 row(s) of file(iot_temp.3350455967374.631.avro) be successfully dumped in!
.OK: [5] 5126 row(s) of file(iot_temp.3350455924922.37.avro) be successfully dumped in!
.OK: [6] 912 row(s) of file(iot_temp.3350455967422.464.avro) be successfully dumped in!
.OK: [4] 4582 row(s) of file(iot_temp.3350455896502.277.avro) be successfully dumped in!
.ERROR: dumpInAvroDataImpl() LN6999 taos_stmt_execute() failed! reason: Out of Memory, timestamp: 1667263801000
ERROR: dumpInAvroDataImpl() LN6999 taos_stmt_execute() failed! reason: Out of Memory, timestamp: 1668367920000
OK: [4] 1036 row(s) of file(iot_temp.3350455896525.2419.avro) be successfully dumped in!
OK: [3] 3145 row(s) of file(iot_temp.3350455873405.2675.avro) be successfully dumped in!
ERROR: dumpInAvroDataImpl() LN6999 taos_stmt_execute() failed! reason: Out of Memory, timestamp: 1668053400000
ERROR: dumpInAvroDataImpl() LN6999 taos_stmt_execute() failed! reason: Out of Memory, timestamp: 1668470400000
OK: [5] 1877 row(s) of file(iot_temp.3350455924926.13.avro) be successfully dumped in!
ERROR: dumpInAvroDataImpl() LN6999 taos_stmt_execute() failed! reason: Out of Memory, timestamp: 1673987400000
ERROR: dumpInAvroDataImpl() LN6999 taos_stmt_execute() failed! reason: Out of Memory, timestamp: 1668012600000
OK: [0] 4599 row(s) of file(iot_temp.3350455764363.224.avro) be successfully dumped in!
OK: [2] 3424 row(s) of file(iot_temp.3350455850159.2233.avro) be successfully dumped in!
OK: [6] 1389 row(s) of file(iot_temp.3350455967434.344.avro) be successfully dumped in!
ERROR: dumpInAvroDataImpl() LN6999 taos_stmt_execute() failed! reason: Out of Memory, timestamp: 1668342061000
ERROR: dumpInAvroDataImpl() LN6999 taos_stmt_execute() failed! reason: Out of Memory, timestamp: 1668456120000
OK: [7] 2749 row(s) of file(iot_temp.3350455990297.148.avro) be successfully dumped in!
OK: [1] 3705 row(s) of file(iot_temp.3350455828152.721.avro) be successfully dumped in!
.ERROR: dumpInAvroDataImpl() LN6999 taos_stmt_execute() failed! reason: Out of Memory, timestamp: 1666691100000
OK: [4] 0 row(s) of file(iot_temp.3350455896530.2059.avro) be successfully dumped in!`

**Comment by sangshuduo** [comment]
请修改 C:\\TDengine\\cfg\\taos.cfg 增加 debugFlag 135，重启 taosd后删除之前导入的 db 重新导入，在出错后把 C:\\TDengine\\log 下的日志文件打包上传到 github，我们分析一下

**Comment by sangshuduo** [comment]
请修改 C:\\TDengine\\cfg\\taos.cfg 增加 debugFlag 135，重启 taosd后删除之前导入的 db 重新导入，在出错后把 C:\\TDengine\\log 下的日志文件打包上传到 github，我们分析一下

**Comment by sangshuduo** [comment]
请修改 C:\\TDengine\\cfg\\taos.cfg 增加 debugFlag 135，重启 taosd后删除之前导入的 db 重新导入，在出错后把 C:\\TDengine\\log 下的日志文件打包上传到 github，我们分析一下

**Comment by QIANGEGEGE** [comment]
又出现了这个问题：
![image](https://user-images.githubusercontent.com/16687627/216534722-ac9beefe-bf53-4508-ab69-4b3a45670667.png)


日志文件超过25m了 ，我给它传到文叔叔上了：
复制这段话，打开文叔叔网站 https://www.wenshushu.cn/k/aew02fa1ddw 或 APP，钥匙串取文件 wss:2LDZewCSFBvum6JUFct8Nwf17nS
备注：log为日志文件
temp.7z为备份数据库文件，执行的还原命令是：.\taosdump.exe -i D:\temp
拜托了

**Comment by sangshuduo** [comment]
> 又出现了这个问题： ![image](https://user-images.githubusercontent.com/16687627/216534722-ac9beefe-bf53-4508-ab69-4b3a45670667.png)
> 
> 日志文件超过25m了 ，我给它传到文叔叔上了： 复制这段话，打开文叔叔网站 https://www.wenshushu.cn/k/aew02fa1ddw 或 APP，钥匙串取文件 wss:2LDZewCSFBvum6JUFct8Nwf17nS 备注：log为日志文件 temp.7z为备份数据库文件，执行的还原命令是：.\taosdump.exe -i D:\temp 拜托了

Unable to open avro file .... Cannot read 1 bytes from file，这种错误请看一下是不是那个文件的尺寸不对

**Comment by QIANGEGEGE** [comment]
一个一个超级表导入可以了。
