### ISSUE TITLE
taostool2.4.3下载不成功

### ISSUE THREAD

**Issue by Wusipeng030** [taosdata/TDengine#19729]
taostool2.4版本无法下载，使用2.3.3版本的，会报错“taosdump: symbol lookup error: taosdump: undefined symbol: inflateReset”

**Comment by sangshuduo** [comment]
TDengine 3.x 配合的 taosTools 需要从 https://docs.taosdata.com/releases/tools/ 下载 

TDengine 2.x （2.4-2.6） 配合的 taosTools 需要从 [https://www.taosdata.com/all-downloads](https://www.taosdata.com/all-downloads) 下载

**Comment by sangshuduo** [comment]
TDengine 3.x 配合的 taosTools 需要从 https://docs.taosdata.com/releases/tools/ 下载 

TDengine 2.x （2.4-2.6） 配合的 taosTools 需要从 [https://www.taosdata.com/all-downloads](https://www.taosdata.com/all-downloads) 下载
