### ISSUE TITLE
大批量数据写入句柄数量一直增加

### ISSUE THREAD

**Issue by Jiang4794** [taosdata/TDengine#19730]
TDengine.Connector版本：3.0.2

插入方式：
`IntPtr conn = DataBase.GetConnection();
                double[] doubles = ones.doubles;
                StringBuilder str3 = new StringBuilder();
                string tableName = "a_" + ones.AcquisitSerialNumber + "_" + ones.ChannelNumber + "_" + ones.SampleRate;
                long timestamp = GetTimestamp(dt);
                for (int j = 0; j < ((doubles.Length / 5000) + (doubles.Length % 5000 == 0 ? 0 : 1)); j++)
                {
                    for (int k = 0; k < doubles.Skip(j * 5000).Take(5000).Count(); k++)
                    {
                        double orginal = doubles[j * 5000 + k];
                        str3.Append("(" + timestamp + "," + orginal + ")");
                        timestamp++;
                    }
                    string sql="insert into " + tableName + " using acceleration TAGS ('" + ones.AcquisitSerialNumber + "','" + ones.ChannelNumber + "'," + ones.SampleRate + ") VALUES " + str3;
                    str3.Clear();
                    IntPtr res = TDengine.Query(conn, sql);
                    TDengine.FreeResult(res);
                }
                TDengine.Close(conn);`

**Comment by yu285** [comment]
麻烦使用 TDengine 3.0.2.5 做验证。另外需要补充其他必要信息，以及排版增加问题易读性。暂时做关闭处理
