### ISSUE TITLE
remote call Tdengine install script failed

### ISSUE THREAD

**Issue by lingshao9537** [taosdata/TDengine#19747]
**问题描述**
B服务器上写了一个install.sh脚本用于执行安装Tdengine(内容是无交互模式安装)。A服务器上写了一个installTD.sh脚本，内容是远程去执行B服务器上的install.sh脚本。
场景一： 在B服务器上执行install.sh，tdengine安装成功
场景二： 在A服务器执行installTD.sh，tdengine安装卡住
安装是否成功判断：在install.sh内容中，有一条语句执行tdengine自己的安装脚本，会输出到一个日志文件，日志文件内容来判断安装过程与结果

**Expected Behavior**
希望贵司可以去试试，通过远程调用安装脚本，是否能安装成功。

**Comment by lingshao9537** [comment]
A服务器的 installTD.sh代码
![](http://m.qpic.cn/psc?/V11pT01r0ckVxl/ruAMsa53pVQWN7FLK88i5vjSDBd31uyAQlEX472vL7GvhcafEeOuvBmBzJ35bHIitnMnkoGfeLBXrp4rCzvWktj1kfZ1Ua8Pm9L6KJwFTgk!/b&bo=oAU4BAAAAAABB7k!&rf=viewer_4)


B服务器的install.sh代码
![](http://m.qpic.cn/psc?/V11pT01r0ckVxl/ruAMsa53pVQWN7FLK88i5rNQc4MtaCiXqQDUcrmdrBTdwOyInTEkhlV*nltNAAaJJgROPw6*aoTJ5hyDkYEx5JBzSKodKuX5IzjS2juQrd0!/b&bo=oAU4BAAAAAABB7k!&rf=viewer_4)

B服务器执行install.sh 1.txt内容
![](http://m.qpic.cn/psc?/V11pT01r0ckVxl/ruAMsa53pVQWN7FLK88i5uAWfcs33Sc.AzHa9InGzJMWicJpyXS94Ca1fFCyr7qcrGUizIwEAmzRgGqO4dLJs7*sVgoLsZeD8XgWjOmri7w!/b&bo=oAU4BAAAAAABB7k!&rf=viewer_4)

A服务器执行installTD.sh 1.txt内容
![](http://m.qpic.cn/psc?/V11pT01r0ckVxl/ruAMsa53pVQWN7FLK88i5vojKeppPkypnfgS9RZs5Ti03Nj9qh2h5UtCh0bn5HdkSskUc*u136etUr0H*Ps6S*sSK*wbFi0gouCmRXp49p0!/b&bo=oAU4BAAAAAABB7k!&rf=viewer_4)

**Comment by tomchon** [comment]
说实话，没太看懂问题。是远程执行有什么报错吗。报错是什么，卡住自己分析了原因了吗
