### ISSUE TITLE
linux下安装后使用taos登录不了，Unable to establish connection

### ISSUE THREAD

**Issue by moco2022** [taosdata/TDengine#19754]
Welcome to the TDengine Command Line Interface from Linux, Client Version:2.6.0.34
Copyright (c) 2022 by TAOS Data, Inc. All rights reserved.

taos connect failed, reason: Unable to establish connection.

**Comment by yu285** [comment]
连接问题 https://www.taosdata.com/engineering/11076.html 看下问题1 排查一下
