### ISSUE TITLE
TDengine有办法实现双机热备吗?

### ISSUE THREAD

**Issue by MrThreeFire** [taosdata/TDengine#19755]
**软硬件环境** : 两台服务器, 各自运行一个TDengine实例.
**期望** : 两个TDengine实例互为主从, 其中一台服务器挂了后, 另一台接着运行. 故障的服务器故障恢复后, 能自动同步故障期间丢失掉的数据.(类似于mysql/mariadb的主主同步)
_把官网的文档大致都看了一下, 看到有高可用方案, 但是不知道是否要求物理节点达到3个或以上._

**Comment by zhonghuali** [comment]
https://docs.taosdata.com/2.4/cluster/ha-and-lb/#arbitrator-%E7%9A%84%E4%BD%BF%E7%94%A8

it dosen't need two metal machine if you uses Arbitrator

**Comment by yu285** [comment]
2.0 支持2副本，可以用两台机器，但原理上也并不是双机热备。可以参考。

3.0 只支持3副本了。
