### ISSUE TITLE
after rebooting server , launchctl can't operate TDengine in Mac

### ISSUE THREAD

**Issue by luoaaswd** [taosdata/TDengine#19762]
**Bug Description**
在安装TDengine-server-3.0.2.4后重启电脑，查询launchctl list | grep com.tdengine 显示无进程，应用程序TDengine.app也失效，需要重新执行launchctl load plist文件才可以使用launchctl启动程序，命令行直接启动无问题。

**Expected Behavior**
重启电脑后执行launchctl list | grep com.tdengine 结果会显示com.tdengine.taosadapter和com.tdengine.taosd任务进程，执行TDengine.app启动正常。

**solution**
把初始安装在/Library/LaunchDaemons中的com.taosdata.taosadapter.plist和com.taosdata.taosd.plist文件放到用户目录下的~/Library/LaunchAgents中，重启电脑后问题解决。暂不清楚问题具体原因

**Environment (please complete the following information):**
 - OS: [MacOS 13.2 (22D49)]
 - Apple M1 2020 pro
 - TDengine Version [TDengine-server-3.0.2.4]

**Comment by yu285** [comment]
您的意思是我们自动安装后，没有做 enable 的操作是吗

**Comment by luoaaswd** [comment]
准确的说是load操作。自动安装后会有加载plist文件，可以用launchctl命令管理taosd和taosadapter服务，TDengine.app自然也可以正常使用。但是重启电脑后，没有自动加载com.taosdata.taosadapter.plist和com.taosdata.taosd.plist这两个plist文件，需要手动launchctl load 才能继续用app和launchctl命令方便管理。后面发现只要把

**Comment by luoaaswd** [comment]
默认安装在/Library/LaunchDaemons的这两个plist文件放到~/Library/LaunchAgents或者/Library/LaunchAgents 目录下就可以解决了，重启电脑后就会加载到这两个plist文件。
