### ISSUE TITLE
docker hub don't have latest code image for release 2.4.X 

### ISSUE THREAD

**Issue by zhonghuali** [taosdata/TDengine#19767]
in hub.docker.io, the tdengine docker images only have 2.4.0.30 which is not latest. the latest release is 2.4.0.41 

expecting to have latest docker images for all release in time.

**Comment by sangshuduo** [comment]
https://hub.docker.com/r/tdengine/tdengine

**Comment by sangshuduo** [comment]
using latest 3.0 or 2.6 is recommended
