### ISSUE TITLE
 using lombok leads to deserialization   failed 

### ISSUE THREAD

**Issue by 13196789316** [taosdata/TDengine#19761]
![f49f2f88dc00b53756b2777125db4d3](https://user-images.githubusercontent.com/31721964/216271857-237d3606-213e-4dc7-85b1-93a1e9edc819.png)

readMethod是有的，ReferenceDeserializer的泛型上使用@Accessor(chain=true)以后无法获取到writeMethod

**Comment by yu285** [comment]
我们看下
