### ISSUE TITLE
show cluster bug

### ISSUE THREAD

**Issue by yaobo-lab** [taosdata/TDengine#19770]
**Bug Description**
when I created a 3 node tdengine cluster、
is show dnodes mnodes are ready；

When executing SQL： 
`show cluster;`
return：
`Query OK, 0 row(s) in set (0.003372s)`

**Screenshots**
![6f25b32e95e9012a5294917dad65f5e](https://user-images.githubusercontent.com/21329253/216490513-cc33d45f-c048-4fe3-b016-b456f8de7b1a.png)

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - TDengine Version [3.0.2.2]

**Additional Context**

**Comment by xiao-yu-wang** [comment]
Can you provide the specific version of the problem you found.

**Comment by yu285** [comment]
升级到 3.0.2.4 后问题解决
