### ISSUE TITLE
TDengine ERROR (200): sql: show null.tables like '%', desc: invalid operation: invalid name

### ISSUE THREAD

**Issue by zhengkaiGithub** [taosdata/TDengine#19773]
数据库启动后使用TDengine CLI可以连接到数据库，但是连接从6041端口连接数据库后提示次报错信息

**Comment by zhengkaiGithub** [comment]
只是使用dbeaver连接时出现次错误信息，使用Java能够正常连接并使用

**Comment by BradySuen** [comment]
什么原因？解决了吗

**Comment by zhengkaiGithub** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Joannzhou** [comment]
请问最后解决了吗？是什么问题

**Comment by zhengkaiGithub** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by zhengkaiGithub** [comment]
最后解决了，但是怎么解决的我忘记了

**Comment by zhengkaiGithub** [comment]
好像是因为密码太复杂，然后识别不了还是啥

**Comment by zhengkaiGithub** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
