### ISSUE TITLE
如何获取某个表的所有列的元数据？

### ISSUE THREAD

**Issue by yuanbing1010** [taosdata/TDengine#19783]
在mysql中我可以通过information_schema.COLUMNS这个表来获取某个表的所有列的元数据，在TDengine中我该怎么做？我看了官方文档，describe table貌似可以，但是只能看到列名、类型、长度这3种元数据，如果我还想看到列的注释信息该怎么做？

**Comment by yu285** [comment]
看看information_schema 的 ins_tables; 以 SQL 查询

**Comment by yuanbing1010** [comment]
ins_tables是表的元数据没错，这个貌似只返回这个表有几个列，我想要的是列的元数据



---原始邮件---
发件人: "Yu ***@***.***&gt;
发送时间: 2023年2月9日(周四) 晚上6:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [taosdata/TDengine] 如何获取某个表的所有列的元数据？ (Issue #19783)




 
看看information_schema 的 ins_tables; 以 SQL 查询

**Comment by yu285** [comment]
![image](https://user-images.githubusercontent.com/74105241/217799934-e55001f8-f26c-4f0f-9fd7-37212d5b9175.png)
这是当前最细化的可查询元信息了，更细的暂时还不支持

**Comment by yuanbing1010** [comment]
好的，感谢回复



---原始邮件---
发件人: "Yu ***@***.***&gt;
发送时间: 2023年2月9日(周四) 晚上7:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [taosdata/TDengine] 如何获取某个表的所有列的元数据？ (Issue #19783)




 

 这是当前最细化的可查询元信息了，更细的暂时还不支持
