### ISSUE TITLE
在C#中反复打开关闭连接，导致进程内句柄数量不断增加，是否存在句柄泄露问题？

### ISSUE THREAD

**Issue by LXX1029** [taosdata/TDengine#19784]
TDengine.Connector：3.0.2.0  服务器版本：3.0.2.0
` private async void btn1_Click(object sender, RoutedEventArgs e)
        {
            while (true)
            {
                this.TestConnection();
                await Task.Delay(TimeSpan.FromSeconds(0.5));
            }
        }
        private void TestConnection()
        {
            IntPtr connection = IntPtr.Zero;
            try
            {
                connection = TDengine.Connect("192.168.1.xxx", "root", "xxxx", "xxxxx", short.Parse("6333"));
            }
            catch (Exception ex)
            {}
            finally
            {
                if (connection != IntPtr.Zero)
                {
                    TDengine.Close(connection);
                }
            }
        连续运行大约30分钟后的句柄数量趋势：
![image](https://user-images.githubusercontent.com/51777355/216537430-42c24b5d-3f28-4fb7-b821-e71202d71373.png)

<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

Time | handles
-- | --
2023/2/3 14:51 | 562
2023/2/3 14:51 | 741
2023/2/3 14:52 | 782
2023/2/3 14:52 | 812
2023/2/3 14:52 | 841
2023/2/3 14:52 | 872
2023/2/3 14:53 | 904
2023/2/3 14:53 | 932
2023/2/3 14:53 | 961
2023/2/3 14:53 | 992
2023/2/3 14:54 | 1019
2023/2/3 14:54 | 1049
2023/2/3 14:54 | 1082
2023/2/3 14:54 | 1112
2023/2/3 14:55 | 1140
2023/2/3 14:55 | 1167
2023/2/3 14:55 | 1199
2023/2/3 14:55 | 1225
2023/2/3 14:56 | 1263
2023/2/3 14:56 | 1305
2023/2/3 14:56 | 1334
2023/2/3 14:56 | 1360
2023/2/3 14:57 | 1390
2023/2/3 14:57 | 1415
2023/2/3 14:57 | 1445
2023/2/3 14:57 | 1484
2023/2/3 14:58 | 1510
2023/2/3 14:58 | 1541
2023/2/3 14:58 | 1589
2023/2/3 14:58 | 1612
2023/2/3 14:59 | 1642
2023/2/3 14:59 | 1664
2023/2/3 14:59 | 1691
2023/2/3 14:59 | 1719
2023/2/3 15:00 | 1740
2023/2/3 15:00 | 1769
2023/2/3 15:00 | 1804
2023/2/3 15:00 | 1837
2023/2/3 15:01 | 1864
2023/2/3 15:01 | 1891
2023/2/3 15:01 | 1918
2023/2/3 15:01 | 1954
2023/2/3 15:02 | 1987
2023/2/3 15:02 | 2019
2023/2/3 15:02 | 2040
2023/2/3 15:02 | 2082
2023/2/3 15:03 | 2109
2023/2/3 15:03 | 2136
2023/2/3 15:03 | 2172
2023/2/3 15:03 | 2195
2023/2/3 15:04 | 2225
2023/2/3 15:04 | 2258
2023/2/3 15:04 | 2290
2023/2/3 15:04 | 2320
2023/2/3 15:05 | 2347
2023/2/3 15:05 | 2380
2023/2/3 15:05 | 2407
2023/2/3 15:05 | 2431
2023/2/3 15:06 | 2467
2023/2/3 15:06 | 2497
2023/2/3 15:06 | 2524
2023/2/3 15:06 | 2557
2023/2/3 15:07 | 2587
2023/2/3 15:07 | 2617
2023/2/3 15:07 | 2646
2023/2/3 15:07 | 2682
2023/2/3 15:08 | 2708
2023/2/3 15:08 | 2739
2023/2/3 15:08 | 2778
2023/2/3 15:08 | 2811
2023/2/3 15:09 | 2830
2023/2/3 15:09 | 2860
2023/2/3 15:09 | 2890
2023/2/3 15:09 | 2925
2023/2/3 15:10 | 2954
2023/2/3 15:10 | 2989
2023/2/3 15:10 | 3025
2023/2/3 15:10 | 3058
2023/2/3 15:11 | 3077
2023/2/3 15:11 | 3104
2023/2/3 15:11 | 3140
2023/2/3 15:11 | 3167
2023/2/3 15:12 | 3195
2023/2/3 15:12 | 3228
2023/2/3 15:12 | 3251
2023/2/3 15:12 | 3278
2023/2/3 15:13 | 3321
2023/2/3 15:13 | 3350
2023/2/3 15:13 | 3375
2023/2/3 15:13 | 3403
2023/2/3 15:14 | 3433
2023/2/3 15:14 | 3462
2023/2/3 15:14 | 3483
2023/2/3 15:14 | 3519
2023/2/3 15:15 | 3549
2023/2/3 15:15 | 3576
2023/2/3 15:15 | 3609
2023/2/3 15:15 | 3654
2023/2/3 15:16 | 3684
2023/2/3 15:16 | 3714
2023/2/3 15:16 | 3742
2023/2/3 15:16 | 3760
2023/2/3 15:17 | 3787
2023/2/3 15:17 | 3827
2023/2/3 15:17 | 3851
2023/2/3 15:17 | 3878
2023/2/3 15:18 | 3911
2023/2/3 15:18 | 3935
2023/2/3 15:18 | 3967
2023/2/3 15:18 | 4003
2023/2/3 15:19 | 4032
2023/2/3 15:19 | 4065
2023/2/3 15:19 | 4086
2023/2/3 15:19 | 4122
2023/2/3 15:20 | 4152
2023/2/3 15:20 | 4182
2023/2/3 15:20 | 4218
2023/2/3 15:20 | 4239
2023/2/3 15:21 | 4266
2023/2/3 15:21 | 4298
2023/2/3 15:21 | 4328
2023/2/3 15:21 | 4358
2023/2/3 15:22 | 4386
2023/2/3 15:22 | 4413
2023/2/3 15:22 | 4440
2023/2/3 15:22 | 4476
2023/2/3 15:23 | 4503
2023/2/3 15:23 | 4536

</body>

</html>

**Comment by yu285** [comment]
收到，我们在看了

**Comment by yu285** [comment]
更新到 3.0.2.5 即可，问题已经解决了。
