### ISSUE TITLE
json tag can't be compared with other tag

### ISSUE THREAD

**Issue by TangPe** [taosdata/TDengine#19793]
**Bug Description**
json tag不能作为比较值判断

**To Reproduce**
json tag为
![image](https://user-images.githubusercontent.com/27326690/216562873-62e992ad-7dbb-4989-850f-597c0dade27d.png)

![1675416445612](https://user-images.githubusercontent.com/27326690/216563319-cb545f8d-d643-4ffd-ba30-4d0affc679c3.jpg)

外层查询时json tag作为比较值判断，但是判断没有生效，猜测json tag取出来的值是字符串
<img width="842" alt="dbe4c072c61f894fdc8795592776778" src="https://user-images.githubusercontent.com/27326690/216563814-ee6c9d43-1b3b-4d1b-8ebf-1f8d205b827a.png">
![image](https://user-images.githubusercontent.com/27326690/216566430-5a902627-d1c6-4ebd-ae30-4040921da3d9.png)

**Expected Behavior**
json tag应该支持作为比较值判断

**Environment (please complete the following information):**
 - OS: [CentOS 7.9]
 - 4c16g 1t
 - TDengine Version [2.6.0.34]

**Comment by wangmm0220** [comment]
2.6的版本json tag支持值判断。
上面这个是 列和列比较。2.6不支持列和列比较，比较的两个中必须有一个是常量。
