### ISSUE TITLE
dnode 消失怎么定位

### ISSUE THREAD

**Issue by liufanfandev** [taosdata/TDengine#19847]
2.4.0.30 版本的 tdengine ，三个节点搭建的 k8s 集群，大概有不到两天的时间 k8s 网络集群有问题，后来网络恢复后，有一个节点 dnodeCfg.json 文件中 "dnodeDropped":  这个属性变成 1 了。
想请教一下，dnodeDropped  这个字段除了用命令删除会变外，还有什么情况下会变。

**Comment by yu285** [comment]
dnode 长时间 offline 会超出参数阈值，然后被踢出集群
