### ISSUE TITLE
issue about stream computing

### ISSUE THREAD

**Issue by zhouzhou98** [taosdata/TDengine#19841]
创建流语句:
create stream realtime_value_stream into t_realtime_value_stream SUBTABLE(CONCAT('real-', tname)) as select last(parttime) as parttime,last(close) as close, last(security_id) as security_id, max(high) as high, min(low) as low, last(pre_close) as pre_close, last(volume
) as volume, last(settle_price) as settle_price, last(pre_settle_price) as pre_settle_price, last(money) as money from t_realtime_value partition by tbname tname state_window(parttime);
创建出来的超级表，group_id无法自定义设置tag，当数量达到一两万的时候，查询流创建出来的超级表超级慢，因为tag即group_id为null,其次通过流创建的超级表含有_wstart，想通过_wstart筛选掉一部分数据，又会报 _WSTART, _WEND and _WDURATION can only be used in window query

**Comment by yu285** [comment]
流计算经历过很多次重构，3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
