### ISSUE TITLE
tdengine3.0.0.0重启后报错，并无法启动。报错信息如下：

### ISSUE THREAD

**Issue by lizenghui2141** [taosdata/TDengine#19843]
02/07 14:12:17.716349 00000074 WAL ERROR vgId:15, unexpected wal log, index:5662914, since body checksum not passed
taosd: /home/ubuntu/zqwang/TDinternal/community/source/libs/wal/src/walRead.c:528: walReadVer: Assertion `0' failed.
02/07 14:12:17.716359 00000074 WAL ERROR checksum written into log:1067182553, checksum calculated:908671181

**Comment by yu285** [comment]
3.0.0.0 是初始的第一个版本现在已经回收，建议用新部署一个到3.0.2.5 的环境

**Comment by yu285** [comment]
建议所有 3.0.2.x 之前的用户，都部署到最新版本，当前为 3.0.2.5
