### ISSUE TITLE
DB error: Fail to get table info, error: some vnode/qnode/mnode(s) out of service (10.284134s)

### ISSUE THREAD

**Issue by Roger-Fly** [taosdata/TDengine#19844]
k8s部署后通过NodePort暴露服务后，可以连接taos服务，可以执行show指令、create database，但是无法执行查询和插入操作

taos版本3.0.2.4，replicas为1

报错日志
DB error: Fail to get table info, error: some vnode/qnode/mnode(s) out of service (10.284134s)

taoslog如下：
UTL apoll url not load
UTL load from cfg file /etc/taos//taos.cfg success
UTL env file:.env not load
UTL load from env variables cfg success
UTL                      global config
UTL =================================================================
UTL env_var      firstEp                  tdengine-0.taosd.taos.svc.cluster.local:6030
UTL default      secondEp                 tdengine-0.taosd.taos.svc.cluster.local:6030
UTL env_var      fqdn                     tdengine-0.taosd.taos.svc.cluster.local
UTL env_var      serverPort               6030
UTL default      tempDir                  /tmp/
UTL default      minimalTmpDirGB          1.00
UTL default      shellActivityTimer       3
UTL default      compressMsgSize          -1
UTL default      compressColData          -1
UTL default      queryPolicy              1
UTL default      querySmaOptimize         0
UTL default      queryPlannerTrace        0
UTL default      queryNodeChunkSize       32768
UTL default      queryUseNodeAllocator    1
UTL default      keepColumnName           0
UTL default      smlChildTableName
UTL default      smlTagName               _tag_null
UTL default      smlDataFormat            0
UTL default      smlBatchSize             10000
UTL default      maxMemUsedByInsert       1024
UTL default      useAdapter               0
UTL default      crashReporting           1
UTL default      configDir                /etc/taos/
UTL default      scriptDir                /etc/taos/
UTL default      logDir                   /var/log/taos/
UTL default      minimalLogDirGB          1.00
UTL default      numOfLogLines            10000000
UTL default      asyncLog                 1
UTL default      logKeepDays              0
UTL default      debugFlag                0
UTL default      simDebugFlag             143
UTL default      tmrDebugFlag             131
UTL default      uDebugFlag               131
UTL default      rpcDebugFlag             131
UTL default      jniDebugFlag             131
UTL default      qDebugFlag               131
UTL default      cDebugFlag               131
UTL default      timezone                 Asia/Shanghai (CST, +0800)
UTL default      locale                   en_US.UTF-8
UTL default      charset                  UTF-8
UTL default      assert                   1
UTL default      enableCoreFile           1
UTL default      numOfCores               4.00
UTL default      openMax                  1048576
UTL default      streamMax                16
UTL default      pageSizeKB               4
UTL default      totalMemoryKB            16140728
UTL default      os sysname               Linux
UTL default      os nodename              tdengine-0
UTL default      os release               3.10.0-957.el7.x86_64
UTL default      os version               #1 SMP Thu Nov 8 23:39:32 UTC 2018
UTL default      os machine               x86_64
UTL default      version                  3.0.2.4
UTL default      compatible_version       3.0.0.0
UTL default      gitinfo                  03f21309e6594f9bb2d08d8739539f742f38e86d
UTL default      buildinfo                Built at 2023-01-17 17:40
UTL =================================================================
QRY catalog update thread started
QRY scheduler 0x6132343337363436 initizlized, maxJob:1000
TSC connecting to server, numOfEps:1 inUse:0 user:root db:(null) key:root:dcc5bed04851fec854c035b2e40263b6:***.18.1.***:30456
TSC ep:0, ***.18.1.***:30456
RPC ERROR TSC msg vnode-batch-meta failed to send, conn 0x7f229c009ca0 failed to connect to ***.18.1.***:6030, reason: connection refused
RPC ERROR TSC msg vnode-batch-meta failed to send, conn 0x7f229c009e60 failed to connect to ***.18.1.***:6030, reason: connection refused
RPC ERROR TSC msg vnode-batch-meta failed to send, conn 0x7f229c00a020 failed to connect to ***.18.1.***:6030, reason: connection refused
RPC ERROR TSC msg vnode-batch-meta failed to send, conn 0x7f229c00a190 failed to connect to ***.18.1.***:6030, reason: connection refused
RPC ERROR TSC msg vnode-batch-meta failed to send, conn 0x7f229c00a300 failed to connect to ***.18.1.***:6030, reason: connection refused
RPC ERROR TSC msg vnode-batch-meta failed to send, conn 0x7f229c00a470 failed to connect to ***.18.1.***:6030, reason: connection refused
RPC ERROR TSC msg vnode-batch-meta failed to send, conn 0x7f229c00a5e0 failed to connect to ***.18.1.***:6030, reason: connection refused
RPC ERROR TSC msg vnode-batch-meta failed to send, conn 0x7f229c00a5e0 failed to connect to ***.18.1.***:6030, reason: connection refused
RPC ERROR TSC msg vnode-batch-meta failed to send, conn 0x7f229c00a5e0 failed to connect to ***.18.1.***:6030, reason: connection refused
RPC ERROR TSC msg vnode-batch-meta failed to send, conn 0x7f229c00a5e0 failed to connect to ***.18.1.***:6030, reason: connection refused
RPC ERROR TSC msg vnode-batch-meta failed to send, conn 0x7f229c00a5e0 failed to connect to ***.18.1.***:6030, reason: connection refused
RPC ERROR TSC msg vnode-batch-meta failed to send, conn 0x7f229c00a5e0 failed to connect to ***.18.1.***:6030, reason: connection refused
RPC ERROR TSC msg vnode-batch-meta failed to send, conn 0x7f229c00a5e0 failed to connect to ***.18.1.***:6030, reason: connection refused
RPC ERROR TSC msg vnode-batch-meta failed to send, conn 0x7f229c00a5e0 failed to connect to ***.18.1.***:6030, reason: connection refused
RPC ERROR TSC msg vnode-batch-meta failed to send, conn 0x7f229c00a5e0 failed to connect to ***.18.1.***:6030, reason: connection refused
RPC ERROR TSC msg vnode-batch-meta failed to send, conn 0x7f229c00a5e0 failed to connect to ***.18.1.***:6030, reason: connection refused
RPC ERROR TSC msg vnode-batch-meta failed to send, conn 0x7f229c00a5e0 failed to connect to ***.18.1.***:6030, reason: connection refused
TSC ERROR 0x7 rsp msg:vnode-batch-meta-rsp, code:some vnode/qnode/mnode(s) out of service rspLen:0, elapsed time:10284 ms, reqId:0x15adb06888fc008a
QRY ERROR Got error rsp, error:some vnode/qnode/mnode(s) out of service
QRY ERROR QID:15adb06888fc008a CTG:0x33d4ef0 Get table 1.database_name.api_tps meta failed with error some vnode/qnode/mnode(s) out of service
QRY ERROR PARSER: 0x15adb06888fc008a catalogGetTableMeta error, code:some vnode/qnode/mnode(s) out of service, dbName:database_name, tbName:api_tps
TSC ERROR 0x7 error occurs, code:Fail to get table info, return to user app, reqId:0x15adb06888fc008a

**Comment by KingPLL** [comment]
同样的问题~~

**Comment by yaobo-lab** [comment]
同样的问题~~

**Comment by itouxin** [comment]
3.0.6.0也有该问题

**Comment by yu285** [comment]
连接问题 https://www.taosdata.com/engineering/11076.html 看下问题1 排查一下

**Comment by 1247776995** [comment]
> te thread started

您好，您发的那个是物理机部署的配置，K8s集群这种问题要怎么配置呢？怎么配置宿主机的hosts或者pod的host?远程客户端怎么配置？
