### ISSUE TITLE
TDengine-server-3.0.2.4-Windows-x64 taosadapter.exe crashed

### ISSUE THREAD

**Issue by Xnollis** [taosdata/TDengine#19865]
**Bug Description**
持续运行6~8个小时，taosadapter.exe即会发生进程崩溃并退出程序，服务终止。根据日志，初步看到有2种不同的原因导致进程崩溃。各种日志文件与运行时的配置文件，在下方附件中。

**To Reproduce**
1.建库建表
2.开启rest api服务程序：
    taosadapter.exe --logLevel warning
3.使用REST api进行数据的insert操作
4.持续运行6~8个小时，taosadapter.exe即会发生进程崩溃并退出程序，服务终止。

**Expected Behavior**
taosadapter.exe 应当可以长时间稳定运行

**Screenshots**

**Environment (please complete the following information):**
Windows 10 专业版 版本 10.0.19042.1466
CPU： intel 7700k
内存： 32G
主程序与数据库安装路径：C:\TDengine
TDengine版本：3.0.2.4

**Additional Context**
SQL:
`create database power;
use power;
CREATE STABLE tb_template_1 (ts timestamp,  voltage int, phase float) TAGS (location varchar (64), groupId int);
CREATE TABLE d1001 USING tb_template_1 TAGS ("车间1", 2); -- 根据超级表（表模板）来创建实际的数据表
CREATE TABLE d1002 USING tb_template_1 TAGS ("车间2", 3); -- 根据超级表（表模板）来创建实际的数据表
CREATE TABLE d1003 USING tb_template_1 TAGS ("车间3", 4); -- 根据超级表（表模板）来创建实际的数据表
CREATE TABLE d1004 USING tb_template_1 TAGS ("车间4", 5); -- 根据超级表（表模板）来创建实际的数据表
CREATE TABLE d1005 USING tb_template_1 TAGS ("车间5", 6); -- 根据超级表（表模板）来创建实际的数据表
CREATE TABLE d1006 USING tb_template_1 TAGS ("车间6", 7); -- 根据超级表（表模板）来创建实际的数据表

CREATE STABLE tb_template_2 (ts timestamp,  value1 int, value2 float,
value3 double,value4 bool,value5 nchar(32),value6 varchar(32) ) TAGS (location varchar (64), groupId int);
CREATE TABLE d2001 USING tb_template_2 TAGS ("车间10", 10); -- 根据超级表（表模板）来创建实际的数据表
CREATE TABLE d2002 USING tb_template_2 TAGS ("车间11", 11); -- 根据超级表（表模板）来创建实际的数据表`

**以下是各类日志文件**
[adapter-crash-Reproduce.txt](https://github.com/taosdata/TDengine/files/10681511/adapter-crash-Reproduce.txt)
[adapter-crash-log1.txt](https://github.com/taosdata/TDengine/files/10681512/adapter-crash-log1.txt)
[adapter-crash-log2.txt](https://github.com/taosdata/TDengine/files/10681513/adapter-crash-log2.txt)
[taos.cfg.txt](https://github.com/taosdata/TDengine/files/10681516/taos.cfg.txt)
[taosadapter.toml.txt](https://github.com/taosdata/TDengine/files/10681517/taosadapter.toml.txt)
[taosdlog.zip](https://github.com/taosdata/TDengine/files/10681523/taosdlog.zip)

**Comment by yu285** [comment]
收到 我们看下。

**Comment by Xnollis** [comment]
补充：运行了几个小时后的进程句柄与资源占用情况截图：
![101daf2d8620813cdd885deaf221289](https://user-images.githubusercontent.com/29424100/217463473-5cf1cf19-c931-4318-98b7-fbeb7501c133.png)
![75558718b96308783d416c4d575bf11](https://user-images.githubusercontent.com/29424100/217463501-4df12c5f-9a40-4870-b7b8-ba86a50f1e6c.png)
也许是资源泄漏导致的？ :)

**Comment by yu285** [comment]
您好，我们做了相关修复，麻烦使用最新的 3.0.2.5 做下验证吧？

**Comment by yu285** [comment]
请问还有这个问题吗

**Comment by Xnollis** [comment]
这几天详细测试了一下，通过观察taosadapter.exe在“任务管理器”里面的“句柄数”，发现句柄数量还是在缓慢增加，说明仍然有点资源泄漏。
复现条件与是：5个位于另外服务器上的线程，每个线程以每秒10次的 insert into语句执行频率，通过REST方式向数据库中并发地插入数据，可以发现：taosadapter.exe的句柄数大约每隔8秒自增1，且没有释放与减少的情况出现。

**Comment by Xnollis** [comment]
> 请问还有这个问题吗

这几天详细测试了一下，通过观察taosadapter.exe在“任务管理器”里面的“句柄数”，发现句柄数量还是在缓慢增加，说明仍然有点资源泄漏。
复现条件与是：5个位于另外服务器上的线程，每个线程以每秒10次的 insert into语句执行频率，通过REST方式向数据库中并发地插入数据，可以发现：taosadapter.exe的句柄数大约每隔8秒自增1，且没有释放与减少的情况出现。

**Comment by Xnollis** [comment]
> > 请问还有这个问题吗
> 
> 这几天详细测试了一下，通过观察taosadapter.exe在“任务管理器”里面的“句柄数”，发现句柄数量还是在缓慢增加，说明仍然有点资源泄漏。 复现条件与是：5个位于另外服务器上的线程，每个线程以每秒10次的 insert into语句执行频率，通过REST方式向数据库中并发地插入数据，可以发现：taosadapter.exe的句柄数大约每隔8秒自增1，且没有释放与减少的情况出现。

上述测试是在3.0.2.5版中进行的，但这两天似乎又正常了。  接下来可能还需要更长时间的运行和大量的并发验证。

**Comment by huskar-t** [comment]
我们高并发插入测试句柄未出现大的波动，请问现在还有这个问题吗 @Xnollis

**Comment by yu285** [comment]
> > > 请问还有这个问题吗
> > 
> > 
> > 这几天详细测试了一下，通过观察taosadapter.exe在“任务管理器”里面的“句柄数”，发现句柄数量还是在缓慢增加，说明仍然有点资源泄漏。 复现条件与是：5个位于另外服务器上的线程，每个线程以每秒10次的 insert into语句执行频率，通过REST方式向数据库中并发地插入数据，可以发现：taosadapter.exe的句柄数大约每隔8秒自增1，且没有释放与减少的情况出现。
> 
> 上述测试是在3.0.2.5版中进行的，但这两天似乎又正常了。 接下来可能还需要更长时间的运行和大量的并发验证。

请问现在还有问题吗

**Comment by Xnollis** [comment]
通过最近的观察，似乎是没有问题了。  这个issue我就先给它关闭了 :)
