### ISSUE TITLE
JNI ERROR (2354): JNI connection is NULL

### ISSUE THREAD

**Issue by ipaddicting** [taosdata/TDengine#19863]
**Bug Description**
TAOS 客户端连接查询时报错 - JNI ERROR (2354): JNI connection is NULL

Java 程序报错如下：
<img width="627" alt="Screenshot 2023-02-08 at 11 03 02" src="https://user-images.githubusercontent.com/244768/217418852-e3b40f96-5d42-49c6-9509-d8e6515bf1d1.png">

TAOS 客户端报错如下：
![WechatIMG2740](https://user-images.githubusercontent.com/244768/217419007-a2b4502b-b7e5-41a9-bc96-46718b6c1a3d.jpeg)

TAOSD 服务端报错如下：
<img width="894" alt="Screenshot 2023-02-08 at 10 07 40" src="https://user-images.githubusercontent.com/244768/217419074-39ac4b65-f274-48f9-a28c-dec60bfc59a3.png">

尝试在数据库连接 URL 中配置 TIMEZONE 信息，但错误同上。

**To Reproduce**
1. 安装 TAOS 原生客户端
2. 使用 JDBC 连接并查询数据

**Expected Behavior**
正确返回查询数据。

**Environment (please complete the following information):**
 - OS: macOS Ventura
 - M1 Pro, 32GB, 1TB 
 - TDengine Version 3.0.2.4

**Comment by sangshuduo** [comment]
taosd 起来了吗？ taos shell 能连吗？

**Comment by ipaddicting** [comment]
taosd，taos shell 和 restful 都是正常的，

> taosd 起来了吗？ taos shell 能连吗？

**Comment by ipaddicting** [comment]
能否提供更多诊断方法？目前我只知道查询日志，但信息不足以找到问题根源。
