### ISSUE TITLE
the filter = and <> doesn't work well for timestamp query

### ISSUE THREAD

**Issue by xiaopingcs** [taosdata/TDengine#1986]
**Bug Description**
The filter = and <> doesn't work well for timestamp query

**To Reproduce**
1. Create a table: create table if not exists st (ts timestamp, tagtype int)
2. Insert one record: insert into st(ts, tagtype) values('2020-05-13 10:00:00.002', 1)
3. Compare results for below queries:
    select * from st where ts = '2020-05-13 10:00:00.002';
    select * from st where ts <> '2020-05-13 10:00:00.002';

**Expected Behavior**
Not record should be found for the second query

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by liuyq-617** [comment]
We support <> for data, but not yet for timestamp
