### ISSUE TITLE
wrong result from  query consists of  first/last ,max ,inverval 

### ISSUE THREAD

**Issue by yuliyuanchn** [taosdata/TDengine#19889]
**Bug Description**
以下两个sql查询到的max(high)结果不同：
select first(high),max(high) from t interval(1d);
select last(high),max(high) from t interval(1d);

**To Reproduce**
1，建表 
CREATE TABLE `t` (`ts` TIMESTAMP, `open` DOUBLE, `close` DOUBLE, `high` DOUBLE, `low` DOUBLE, `vol` DOUBLE, `amount` DOUBLE, `preclose` DOUBLE)
2，下载并导入测试数据
[test.csv](https://github.com/taosdata/TDengine/files/10694650/test.csv)
3，查询结果
select first(high),max(high) from t interval(1d);
select last(high),max(high) from t interval(1d);

**Expected Behavior**
select first(high),max(high) from t interval(1d);
select last(high),max(high) from t interval(1d);
这两个的查询结果中max(high)列的数值应该一致

**Screenshots**
![yly_20230209](https://user-images.githubusercontent.com/7928411/217748758-08da7d47-ee3a-4b11-bdf5-5bbfa190b58f.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS
 - Memory, CPU, current Disk Space
 - TDengine Version 3.0.2.4

**Comment by yu285** [comment]
收到，已经在处理

**Comment by yuliyuanchn** [comment]
the bug is fixed
