### ISSUE TITLE
does install TDengine client is necessary for JNI connection ?

### ISSUE THREAD

**Issue by XW512** [taosdata/TDengine#19893]
我使用了官网的demo，跑了下restful形式的调用，可以访问的通，我现在有个疑问，因为原生连接是使用TSDBDriver 直接调用客户端驱动（libtaos.so 或 taos.dll）的 API 将写入和查询请求发送到位于物理节点 2（pnode2）上的 taosd 实例，那么是不是应用都需要安装TDengine-client客户端，如果没安装的话，就调用不了客户端的驱动了，我想的为啥不是Java应用连接TDengine-client的集群，然后通过这个集群进行调用，我没太明白这块的关系

**Comment by yu285** [comment]
直接调用客户端驱动（libtaos.so 或 taos.dll）是可以的。

**Comment by yu285** [comment]
只不过 libtaos.so 或 taos.dll  和服务端需要使用对应一致的版本，所以下载客户端比较方便。

**Comment by XW512** [comment]
> 直接调用客户端驱动（libtaos.so 或 taos.dll）是可以的。

我现在用windows的Java应用调用虚拟机上搭建的客户端，会报错java.lang.UnsatisfiedLinkError: no taos in java.library.path，这个是不是因为系统问题，需要我打包部署到Linux机器上去连接客户端

**Comment by XW512** [comment]
> 直接调用客户端驱动（libtaos.so 或 taos.dll）是可以的。

我部署到Linux系统，发现还是不行，报错 nested exception is java.lang.UnsatisfiedLinkError: no taos in java.library.path，是不是这个Linux系统也必须要安装TDengine-client才可以调用呀

**Comment by XW512** [comment]
> 直接调用客户端驱动（libtaos.so 或 taos.dll）是可以的。

我尝试了把Java应用包放到了安装了TDengine-client的那台虚拟机上启动，发现还是无法连上TDengine，报错java.sql.SQLException: JNI ERROR (2354): Unable to establish connection，这个应该与UDP端口没开没关系吧

**Comment by XW512** [comment]
> 直接调用客户端驱动（libtaos.so 或 taos.dll）是可以的。

我的想法是：搭建一个TDengine-client的集群，然后应用直接连接这个集群，但是我看到TDengine-client安装的机器只是新增了taos这个命令，没有端口相关的，所以没明白这个怎么通过TDengine-client去连接TDengine集群

**Comment by yu285** [comment]
客户端安装包自带 libtaos.so 或 taos.dll ，拿来使用就行
