### ISSUE TITLE
golang   使用taosql原生链接，TDengine2.4.0版本，linux环境，go版本1.17，gcc版本4.8.5

### ISSUE THREAD

**Issue by xm630814043** [taosdata/TDengine#19895]
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/44759950/217806244-d2ae8218-a4a7-4526-9ff5-a663839bbed4.png">

# github.com/taosdata/driver-go/v2/wrapper
../go/pkg/mod/github.com/taosdata/driver-go/v2@v2.0.6/wrapper/schemaless.go:57:9: could not determine kind of name for C.taos_schemaless_insert_raw

上图是在配置了客户端的服务器上

<img width="955" alt="image" src="https://user-images.githubusercontent.com/44759950/217806171-7c812c7a-7036-4355-b23a-a5b9b47fb497.png">

# github.com/taosdata/driver-go/v2/wrapper
/data/go/pkg/mod/github.com/taosdata/driver-go/v2@v2.0.6/wrapper/asynccb.go:7:18: fatal error: taos.h: No such file or directory
 #include <taos.h>
                  ^
compilation terminated.

上图是无配置客户端服务器
使用go build进行打包，抛出错误并打包失败。

**Comment by sangshuduo** [comment]
go get github.com/taosdata/driver-go/v2/taosSql@v2.0.5

**Comment by xm630814043** [comment]
<img width="939" alt="image" src="https://user-images.githubusercontent.com/44759950/218030228-f57c71c2-716e-42c3-94fb-ec6827fdd8df.png">
使用该命令抛出一样的错误

**Comment by sangshuduo** [comment]
> <img alt="image" width="939" src="https://user-images.githubusercontent.com/44759950/218030228-f57c71c2-716e-42c3-94fb-ec6827fdd8df.png">
> 使用该命令抛出一样的错误

要先装 TDengine 客户端安装包

**Comment by xm630814043** [comment]
已解决，谢谢
指定2.0.5，是因为版本问题吗？

**Comment by sangshuduo** [comment]
> 已解决，谢谢 指定2.0.5，是因为版本问题吗？

因为新版本增加了接口，需要使用早一点版本的 driver-go
