### ISSUE TITLE
strncpy broken

### ISSUE THREAD

**Issue by freemine** [taosdata/TDengine#1989]
in src file: src/mnode/src/mgmtTable.c
1307         strncpy(pVgroupInfo->vgroups[vgSize].ipAddr[vn].fqdn, pDnode->dnodeFqdn, tListLen(pDnode->dnodeFqdn));

size of dnodeFqdn is (TSDB_FQDN_LEN+1) while
size of fqdn is (TSDB_FQDN_LEN)

**Comment by guanshengliang** [comment]
Thanks for the suggestion, we will use macro tstrncpy to deal with similar problems, such as 
tstrncpy(pVgroupInfo->vgroups[vgSize].epAddr[vn].fqdn, pDnode->dnodeFqdn, TSDB_FQDN_LEN);

**Comment by guanshengliang** [comment]
This issue has been resolved, so we close it
