### ISSUE TITLE
关于建表字段数上限的问题

### ISSUE THREAD

**Issue by zhangchi0923** [taosdata/TDengine#199]
建表最多支持多少字段呢？我的表有近500个字段，source我的建表语句，只返回了TSDB error: invalid SQL: illegal number of columns，意味着字段数非法？

**Comment by hzcheng** [comment]
目前包含tag在内最多支持256列

**Comment by Ielool** [comment]
> 建表最多支持多少字段呢？我的表有近500个字段，source我的建表语句，只返回了TSDB error: invalid SQL: illegal number of columns，意味着字段数非法？

您在什么场景下用到500列的表？可以交流下吗？

**Comment by zhangchi0923** [comment]
@Ielool 车联网数据采集

**Comment by wanliofficial** [comment]
> @Ielool 车联网数据采集

牛逼，500个字段，分析起来也痛苦吧，一小时是要采集多少数据?

**Comment by guanshengliang** [comment]
From the code level, it can be easily extended, but it will cause performance degradation
I suggest you split into multiple tables
