### ISSUE TITLE
Order by 倒序查询bug

### ISSUE THREAD

**Issue by zhrmzr123** [taosdata/TDengine#19912]
![512ea96622eada68675b8498917642c](https://user-images.githubusercontent.com/81086395/218011046-61765384-536d-4045-ad1d-eb527afbc794.png)

**Comment by yu285** [comment]
请问版本号是？

**Comment by zhrmzr123** [comment]
使用的是3.0.1.6版本

**Comment by xvsefdbdty** [comment]
你好，后续解决了吗

**Comment by yu285** [comment]
> 你好，后续解决了吗

解决了，升级到最新版 3.3.8.1 即可
