### ISSUE TITLE
TDError.DatabaseError.ProgrammingError: invalid DB

### ISSUE THREAD

**Issue by sexbee** [taosdata/TDengine#1994]
TDError.DatabaseError.ProgrammingError: invalid DB
    at TDengineCursor.execute (/usr/local/kcu/node_modules/td-connector/nodetaos/cursor.js:143:11)
    at /usr/local/kcu/node_modules/td-connector/nodetaos/taosquery.js:40:25
    at new Promise (<anonymous>)

insert into db_mrnist.m5704198s4 using db_mrnist.st_mrnist tags("xf","2020") values('2020-05-22 14:09:12.211',570498,4,'C007','jERRY',56,'M','no','40xx','50A','no','no','333');

Taos shell: Insert   ===> Nomal   
query.execute()  =====>  invalid DB

**Comment by liuyq-617** [comment]
I tested it and did not reproduce your problem.
os:centos 7
version: 1.6.5.6
my code:
`var query = cursor.query('insert into test.test using test.meters tags(3,"aaa") values(now,1,2,3);');
query.execute();`

**Comment by sexbee** [comment]
我的推测是bug在于：如果新安装TAOS，然后从另一个数据库 taosdump过来的，此时如果新建一个db_newdatabase, query.excute()就会报错；然而如果是用 db_olddatabase 建的 st_newstable，query.excute()就不报错；换言之，如果是导入过taosdump，新建db就会报错 invalid db，用老db不报错。

My infer is that the bug lies in: if you install Taos newly, and then come from another database, taosdump, at this time, if you create a new DB_ newdatabase, query.excute () will report an error; however, if DB is used_ St built by olddatabase_ newstable， query.excute () no error is reported; in other words, if taosdump is imported, the new DB will report invalid dB, and the old DB will not.

**Comment by liuyq-617** [comment]
I am sorry, I have tested it again as you said, and your problem has not been reproduced.
Subject to the test conditions you put forward, I use V1.6.5.9 this time, I recommend you to update to the latest version and do another test
