### ISSUE TITLE
c++ connector memory leak？

### ISSUE THREAD

**Issue by kaifuGuy** [taosdata/TDengine#19959]
**Bug Description**
使用c++调用3.0.2.0或者3.0.2.5均有此问题，长期运行写入会逐渐吃掉所有内存。测试程序会比较明显。不知道是不是我调用方式有错误。

**To Reproduce**
测试代码如下:
[main.zip](https://github.com/taosdata/TDengine/files/10721001/main.zip)

**Expected Behavior**
测试代码比较极端，可以在5分钟内看到明显的增长.

**Screenshots**

**Environment (please complete the following information):**
 - OS: windows 2012 r2
 - TDengine Version 3.0.2.0 or 3.0.2.5

**Additional Context**
.

**Comment by yu285** [comment]
try this script

**Comment by yu285** [comment]
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <sys/time.h>
#include <pthread.h>
#include <unistd.h>
#include "taos.h"
#include <malloc.h>

TAOS* pTaos;

bool checkErrorCode(TAOS_STMT *stmt, int code, char *msg)
{
	if (code != 0) {
		taos_stmt_close(stmt);
		stmt = NULL;
		return false;
	}
	return true;
}


void insert(long int t)
{
	TAOS_RES *result;
	TAOS_STMT *stmt;

	struct {
		int64_t ts;
		float f0;
		float f1;
		float f2;
		float f3;
		float f4;
		float f5;
		float f6;
		float f7;
	} v = { 0 };

	int32_t bintLen = sizeof(int64_t);
	int32_t floatLen = sizeof(float);
	char is_null[2] = { 0 };

	v.ts = 1591060628106;
	for (int i = 0; i < 1; ++i) {
		v.ts += t;
		v.f0 = (float)i + 2;
		v.f1 = (float)i + 1;
		v.f2 = (float)(i + 2);
		v.f3 = (float)(i + 4);
		v.f4 = (float)(i + 8);
		v.f5 = (float)(i + 40);
		v.f6 = (float)(i + 80);
		v.f7 = (float)(i + 40);
	}

	stmt = taos_stmt_init(pTaos);
	TAOS_MULTI_BIND params[9];
	params[0].buffer_type = TSDB_DATA_TYPE_TIMESTAMP;
	params[0].buffer_length = sizeof(v.ts);
	params[0].buffer = &v.ts;
	params[0].length = &bintLen;
	params[0].is_null = NULL;
	params[0].num = 1;

	params[1].buffer_type = TSDB_DATA_TYPE_FLOAT;
	params[1].buffer_length = sizeof(v.f0);
	params[1].buffer = &v.f0;
	params[1].length = &floatLen;
	params[1].is_null = NULL;
	params[1].num = 1;

	params[2].buffer_type = TSDB_DATA_TYPE_FLOAT;
	params[2].buffer_length = sizeof(v.f1);
	params[2].buffer = &v.f1;
	params[2].length = &floatLen;
	params[2].is_null = NULL;
	params[2].num = 1;

	params[3].buffer_type = TSDB_DATA_TYPE_FLOAT;
	params[3].buffer_length = sizeof(v.f2);
	params[3].buffer = &v.f2;
	params[3].length = &floatLen;
	params[3].is_null = NULL;
	params[3].num = 1;

	params[4].buffer_type = TSDB_DATA_TYPE_FLOAT;
	params[4].buffer_length = sizeof(v.f3);
	params[4].buffer = &v.f3;
	params[4].length = &floatLen;
	params[4].is_null = NULL;
	params[4].num = 1;

	params[5].buffer_type = TSDB_DATA_TYPE_FLOAT;
	params[5].buffer_length = sizeof(v.f4);
	params[5].buffer = &v.f4;
	params[5].length = &floatLen;
	params[5].is_null = NULL;
	params[5].num = 1;

	params[6].buffer_type = TSDB_DATA_TYPE_FLOAT;
	params[6].buffer_length = sizeof(v.f5);
	params[6].buffer = &v.f5;
	params[6].length = &floatLen;
	params[6].is_null = NULL;
	params[6].num = 1;

	params[7].buffer_type = TSDB_DATA_TYPE_FLOAT;
	params[7].buffer_length = sizeof(v.f6);
	params[7].buffer = &v.f6;
	params[7].length = &floatLen;
	params[7].is_null = NULL;
	params[7].num = 1;

	params[8].buffer_type = TSDB_DATA_TYPE_FLOAT;
	params[8].buffer_length = sizeof(v.f7);
	params[8].buffer = &v.f7;
	params[8].length = &floatLen;
	params[8].is_null = NULL;
	params[8].num = 1;


	const char* sql = "INSERT INTO ?  USING meter TAGS(?, ?) VALUES(?,?,?,?,?,?,?,?,?)";
	int  code = taos_stmt_prepare(stmt, sql, 0);
	if (code != 0){
		printf("failed to execute taos_stmt_prepare. code:0x%x\n", code);
	}

	char* tablename = "t11112";
	char* devicecode = "111111";
	char* company = "2222";

	TAOS_MULTI_BIND tags[2];
	char* pname = malloc(strlen(tablename) + 1);
	memcpy(pname, tablename, strlen(tablename));
	pname[strlen(tablename)] = '\0';

	char     *location = malloc(strlen(devicecode) + 1);
	memcpy(location, devicecode, strlen(devicecode));
	location[strlen(devicecode)] = '\0';

	char     *clocation = malloc(strlen(company) + 1);
	memcpy(clocation, company, strlen(company));
	clocation[strlen(company)] = '\0';

	int32_t charlen = sizeof(char);

	tags[0].buffer_type = TSDB_DATA_TYPE_BINARY;
	tags[0].buffer_length = sizeof(location);
	tags[0].buffer = location;
	tags[0].length = &charlen;
	tags[0].is_null = NULL;
	tags[0].num = 1;

	tags[1].buffer_type = TSDB_DATA_TYPE_BINARY;
	tags[1].buffer_length = sizeof(clocation);
	tags[1].length = &charlen;
	tags[1].buffer = clocation;
	tags[1].is_null = NULL;
	tags[1].num = 1;

	code = taos_stmt_set_tbname_tags(stmt, pname, tags);
	char* msg2 = "failed to execute taos_stmt_set_tbname_tags:";
	if (!checkErrorCode(stmt, code, msg2))
	{
		taos_stmt_close(stmt);
		free(location);
		free(clocation);
		free(pname);
		return;
	}

	code = taos_stmt_bind_param(stmt, params);
	if (!checkErrorCode(stmt, code, "failed to execute taos_stmt_bind_param"))
	{
		taos_stmt_close(stmt);
		free(location);
		free(clocation);
		free(pname);
		return;
	}

	code = taos_stmt_add_batch(stmt);

	if (!checkErrorCode(stmt, code, "failed to execute taos_stmt_bind_param"))
	{
		taos_stmt_close(stmt);
		free(location);
		free(clocation);
		free(pname);
		return;
	}

	code = taos_stmt_execute(stmt);
	if (!checkErrorCode(stmt, code, "failed to execute taos_stmt_bind_param"))
	{
		taos_stmt_close(stmt);
		free(location);
		free(clocation);
		free(pname);
		return;
	}

		free(location);
		free(clocation);
		free(pname);
		
	int affectedRows = taos_stmt_affected_rows(stmt);
	printf("successfully inserted %d rows\n", affectedRows);

	taos_stmt_close(stmt);
}


bool connectServer()
{
	pTaos = taos_connect("localhost", "root", "taosdata",  NULL, 6030);
	if (pTaos == NULL)
	{
		int   errono = taos_errno(NULL);
		char* msg = taos_errstr(NULL);
		return false;
	}
	return true;
}


void testTD(int t)
{
	long int mark = time(0);
	insert(t);
}

void prepare() {
    TAOS_RES *result;  
  result = taos_query(pTaos, "drop database demo"); 
  taos_free_result(result);

  result = taos_query(pTaos, "create database demo");
  int code = taos_errno(result);
  if (code != 0) {
    printf("failed to create database, reason:%s\n", taos_errstr(result));
    taos_free_result(result);
    exit(1);
  }
  taos_free_result(result);

  result = taos_query(pTaos, "use demo");
  taos_free_result(result);

  // create table
  const char* sql = "create stable meter (ts timestamp, f1 float, f2 float, f3 float, f4 float, f5 float, f6 float, f7 float, f8 float) tags(t1 binary(11), t2 binary(11))";
  result = taos_query(pTaos, sql);
  code = taos_errno(result);
  if (code != 0) {
    printf("failed to create table, reason:%s\n", taos_errstr(result));
    taos_free_result(result);
    exit(1);
  }
  taos_free_result(result);

}

int main(int argc, char *argv[])
{
  int ret = mallopt(M_MMAP_THRESHOLD, 0);
  if (0 == ret) {
    return -1;
  }

	if (!connectServer())
		return 0;

	prepare();

	int t = 0;
	for (int i = 0;i < 1000000;++i)
	{
    	testTD(t++);
	}

        taos_close(pTaos);

	return 0;
}

**Comment by kaifuGuy** [comment]
你这个在只能在linux环境下，关键就是mallopt这个指定了内存调度模式。windows下我该用什么开关控制？

**Comment by dapan1121** [comment]
@kaifuGuy mallopt只是调试用的，你不需要的，我已经在上面的代码里去掉了，你可以直接编译运行

**Comment by kaifuGuy** [comment]
可是我试过了，windows下你这个代码也不行。

**Comment by kaifuGuy** [comment]
不知道问题在哪里。难道我们的lib不一致？

**Comment by kaifuGuy** [comment]
@dapan1121  能把你用的lib文件和头文件附件给我吗？

**Comment by dapan1121** [comment]
@kaifuGuy 我用的就是3.0.2.5的lib和头文件，不过我是在linux跑的，我试一下windows有没有问题

**Comment by dapan1121** [comment]
@kaifuGuy 使用3.0.2.5版本在windows 10跑了5分钟，内存没有任何增长。你要是测试还有问题你可以联系一下 @yu285 看看能不能远程看一下

**Comment by kaifuGuy** [comment]
@yu285 我该如何联系你？

**Comment by kaifuGuy** [comment]
抱歉，突然意识到我犯了一个愚蠢的错误。我在远程机器更新了3.0.2.5，但是我编译链接的一直是3.0.2.0版本的lib，这就导致了我始终出现内存泄漏。我刚才清理了本地的lib文件，替换成3.0.2.5版本之后，内存可以正确释放了。非常感谢 @dapan1121 的耐心配合处理。
