### ISSUE TITLE
cmake related

### ISSUE THREAD

**Issue by freemine** [taosdata/TDengine#1995]
it seems we failed to make a release build with -O3 option.
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build .
and cc options generated as followings:
cd <path_to>/TDengine/build/src/util && /usr/bin/cc  -DLINUX -DUSE_LIBICONV -D_LIBC_REENTRANT -D_M_X64 -D_REENTRANT -D__USE_POSIX -I<path_to>/TDengine/src/os/linux/inc -I<path_to>/TDengine/src/inc -I<path_to>/TDengine/src/util/inc -I<path_to>/TDengine/src/common/inc -I<path_to>/TDengine/deps/cJson/inc -I<path_to>/TDengine/deps/lz4/inc  -O3 -DNDEBUG -std=gnu99 -Wall -Werror -fPIC -malign-double -g3 -gdwarf-2 -malign-stringops -msse4.2 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILE -O0   -std=gnu11 -o CMakeFiles/tutil.dir/src/tcompression.c.o   -c <path_to>/TDengine/src/util/src/tcompression.c

because -O0 comes after -O3 in the command line.
when I check ../cmake/platform.inc, it states: SET(RELEASE_FLAGS "-O0")

I am wondering why optimization option is turned off even in a release build stage?

When I intently turn this option to -O3, gcc complains a lots of warnings (as error, cause -Werror). Although many of such warnings can be turned off by specifying -Wno-used-variable and so on, I found 'strict aliasing' warnings, which normally shall be turned off with -fno-strict-aliasing but failed to find in this project.

reference: https://lkml.org/lkml/2018/6/5/774
https://news.ycombinator.com/item?id=17262643

ps: because users might generate make-files by typing: CFLAGS='.....' cmake -D....
better place CMAKE_C/CXX_FLAGS_DEBUG/RLEASE after DEBUG/RELEASE_FLAGS
in ../cmake/env.inc

thx!

**Comment by sangshuduo** [comment]
@freemine expect #3535 can fix this issue.

**Comment by freemine** [comment]
seems like still -O0 for release build

**Comment by sangshuduo** [comment]
@freemine yes, since we are still busy on feature development and no enough bandwidth to focus on optimization. remove -O0 is a long-term plan.

**Comment by sangshuduo** [comment]
@freemine yes, since we are still busy on feature development and no enough bandwidth to focus on optimization. remove -O0 is a long-term plan.
