### ISSUE TITLE
When fetching the field with the environment win 10 and python 3, only the first character of the string can be fetched.

### ISSUE THREAD

**Issue by ccccxjin** [taosdata/TDengine#1996]
数据库在centos7
代码环境: win10 + python3

某字段定义为 nchar(1000), 给该字段存入 600个字符长度的字符串
取该字段时, 只能取出字符串的第一个字符.

代码:
![image](https://user-images.githubusercontent.com/40816135/82639943-4488ac80-9c3c-11ea-9fc9-03e7e3463aa1.png)
结果:
![image](https://user-images.githubusercontent.com/40816135/82640005-641fd500-9c3c-11ea-845f-614038e283b7.png)

在centos 命令行下执行
![image](https://user-images.githubusercontent.com/40816135/82640038-74d04b00-9c3c-11ea-9086-dc9bacf18201.png)

**Comment by liuyq-617** [comment]
Indeed a bug,fix it soon

**Comment by sanliang125** [comment]
请问这个bug解决了吗？JAVA好像也有这种现象。

**Comment by liu0x54** [comment]
> 请问这个bug解决了吗？JAVA好像也有这种现象。

什么现象？能否贴一下错误信息

**Comment by liu0x54** [comment]
The taos C connector interface will be modified in recent development. Please keep watch and try later
