### ISSUE TITLE
grafana connect tdengine issue

### ISSUE THREAD

**Issue by PPQiao** [taosdata/TDengine#19969]
Bug Description
tdengine正常运行, taos指令正常, 但是使用grafana连接本地的tdengine时出现如下图错误.
![image](https://user-images.githubusercontent.com/36836033/218627511-6950f38f-52cc-4862-a04b-1f5c8a56dd38.png)

Environment:

OS:centos7.6
TDengine Version 2.2.2.0
grafana v9.3.6
tdengine-plugin v2.3.8

**Comment by yu285** [comment]
已经启动 taosadapter 了么

**Comment by PPQiao** [comment]
> 

你好, 没有, 我的tdengine版本是2.2.2.0好像没有Adaptaer
, 请问是需要单独安装么?
![image](https://user-images.githubusercontent.com/36836033/218931080-23a6b4f6-cf00-4b7c-9403-7966ba6715b6.png)

**Comment by PPQiao** [comment]
> 已经启动 taosadapter 了么

你好, 没有, 我的tdengine版本是2.2.2.0好像没有Adaptaer
, 请问是需要单独安装么?
![image](https://user-images.githubusercontent.com/36836033/218931185-d8fe33af-8be2-46e5-9772-53dc93b05851.png)

**Comment by sangshuduo** [comment]
> > 已经启动 taosadapter 了么
> 
> 你好, 没有, 我的tdengine版本是2.2.2.0好像没有Adaptaer , 请问是需要单独安装么? ![image](https://user-images.githubusercontent.com/36836033/218931185-d8fe33af-8be2-46e5-9772-53dc93b05851.png)

taosadapter 是从 2.4 才开始有的

**Comment by PPQiao** [comment]
> > > 已经启动 taosadapter 了么
> > 
> > 
> > 你好, 没有, 我的tdengine版本是2.2.2.0好像没有Adaptaer , 请问是需要单独安装么? ![image](https://user-images.githubusercontent.com/36836033/218931185-d8fe33af-8be2-46e5-9772-53dc93b05851.png)
> 
> taosadapter 是从 2.4 才开始有的

那么tdengin v2.2要想连grafana, 是不是直接给grafana加上tdengine的插件就行了, 为什么我给grafana装了td的插件却连不上, 提示tdengine is not working reason: undefined, TDenging的服务是正常的, taos指令正常执行.
