### ISSUE TITLE
Excessive storage usage？

### ISSUE THREAD

**Issue by QIANGEGEGE** [taosdata/TDengine#19974]
**问题：tdengine存储每日新增大小与实际存储内容大小不符**
问题具体描述：
在一个小型项目中，使用了单机版TDengine2.6.0.34的数据库。测试使用 3个月，data目录占用370G，与实际数据大小严重不符。

认为不对的原因：
1.目前两个超级表，800子表，每个超级表下400子表，一个超级表数据是2715100条数据，单条数据应该占3000多字节，另外一个是448700条数据，单条数据应该200多字节。按照资源估算（https://www.taosdata.com/config/config.html）也不是占用300多G;
2.taosdump 备份全库导出数据只有60M左右。

**数据结构及频率等信息*
数据频率: 30分钟或1小时一条
建库语句：
`CREATE DATABASE `zghd_subheat` REPLICA 1 QUORUM 1 DAYS 10 KEEP 3650 CACHE 16 BLOCKS 6 MINROWS 100 MAXROWS 4096 WAL 1 FSYNC 3000 COMP 2 CACHELAST 0 PRECISION 'ms' UPDATE 1`
超级表1建表语句：
`CREATE TABLE `valve_his` (`ts` TIMESTAMP,`execitionopen` FLOAT,`supplytemp` FLOAT,`returntemp` FLOAT,`batterycapacity` FLOAT) TAGS (`devicecode` NCHAR(32),`company` NCHAR(64),`subcompany` NCHAR(64),`heat` NCHAR(64),`pipeline` NCHAR(64),`station` NCHAR(64),`stationunit` NCHAR(64),`community` NCHAR(64),`building` NCHAR(64),`unit` NCHAR(64),`region` NCHAR(64),`projectid` NCHAR(64))`
超级表2建表语句：
`CREATE TABLE `valve_config_his` (`activatedtime` TIMESTAMP,`mode` INT,`uploadfrequency` INT,`concurencelimit` INT,`collectfrequency` INT,`spansetup` INT,`minopen` INT,`targettemp` INT,`temptolerence` INT,`exedeadspam` INT,`sensordirection` INT,`controltimestep` INT,`percentpara` INT) TAGS (`devicecode` NCHAR(32))`

当前系统参数：
` [ "writeBatchTimeout", "10" ], [ "writeBatchSize", "0" ], [ "writeBatchThreadLocal", "0" ], [ "probeInterval", "40" ], [ "probeKillSeconds", "600" ], [ "probeSeconds", "300" ], [ "shortcutFlag", "0" ], [ "walFlushSize", "1024" ], [ "smlTagNullName", "_tag_null" ], [ "smlChildTableName", "" ], [ "defaultJSONStrType", "nchar" ], [ "aggAlways", "0" ], [ "clientMerge", "0" ], [ "deadLockKillQuery", "1" ], [ "version", "2.6.0.34" ], [ "buildinfo", "Built at 2022-12-23 14:14" ], [ "gitinfoOfInternal", "NULL" ], [ "gitinfo", "dc5dfa43996b7f540b98080ceed754cfa0c6d54" ], [ "httpDbNameMandatory", "0" ], [ "telegrafUseFieldNum", "0" ], [ "topicBinaryLen", "16000" ], [ "stream", "1" ], [ "audit", "0" ], [ "monitor", "1" ], [ "http", "1" ], [ "adjustMaster", "1" ], [ "slaveQuery", "1" ], [ "flowctrl", "1" ], [ "mnodeEqualVnodeNum", "4" ], [ "minimalDataDirGB", "2.000000" ], [ "minimalTmpDirGB", "1.000000" ], [ "minimalLogDirGB", "1.000000" ], [ "maxConnections", "5000" ], [ "maxShellConns", "50000" ], [ "charset", "UTF-8" ], [ "locale", "en_US.UTF-8" ], [ "timezone", "Asia/Shanghai (CST, +0800)" ], [ "keepColumnName", "1" ], [ "retrieveBlockingModel", "0" ], [ "queryBufferSize", "-1" ], [ "maxNumOfOrderedRes", "1000000" ], [ "maxRegexStringLen", "128" ], [ "maxWildCardsLength", "100" ], [ "maxSQLLength", "1048576" ], [ "compressColData", "-1" ], [ "compressMsgSize", "524288" ], [ "cachelast", "0" ], [ "update", "0" ], [ "quorum", "1" ], [ "partitions", "4" ], [ "replica", "1" ], [ "fsync", "3000" ], [ "walLevel", "1" ], [ "comp", "2" ], [ "precision", "0" ], [ "maxRows", "4096" ], [ "minRows", "100" ], [ "keep", "3650" ], [ "days", "10" ], [ "blocks", "6" ], [ "cache", "16" ], [ "tableIncStepPerVnode", "1000" ], [ "minTablesPerVnode", "1000" ], [ "maxTablesPerVnode", "1000000" ], [ "maxVgroupsPerDb", "0" ], [ "streamCompDelayRatio", "0.100000" ], [ "retryStreamCompDelay", "1800000" ], [ "maxFirstStreamCompDela", "10000" ], [ "maxStreamCompDelay", "20000" ], [ "minIntervalTime", "1" ], [ "minSlidingTime", "10" ], [ "statusInterval", "1" ], [ "offlineThreshold", "864000" ], [ "monitorReplica", "1" ], [ "maxTmrCtrl", "5120" ], [ "keepTimeOffset", "0" ], [ "offlineInterval", "3" ], [ "balanceInterval", "300" ], [ "balance", "1" ], [ "syncCheckInterval", "1500" ], [ "tcpConnTimeout", "1000" ], [ "telemetryReporting", "1" ], [ "vnodeBak", "1" ], [ "numOfMnodes", "1" ], [ "maxNumOfDistinctRes", "10000000" ], [ "arbitrator", "" ] ]`

**其它环境备注:**
 - OS: Ubuntu 20.04.4 
 - TDengine Version 2.6.0.34 单机版

**Additional Context**
希望能指导一个解决方案

**Comment by yu285** [comment]
data目录占用370G 里面包含了未压缩的wal（写前日志），可以停下服务，再测一下实际占用大小

**Comment by QIANGEGEGE** [comment]
@yu285  您好，给您解释下这边情况，因为磁盘快要满了，2023.2.12日这边将包含2个超级表的库导出，删除重新安装了一遍2.6.0.34版本，然后又导入这个库。导入后磁盘占用30M+，并且排查数据没有减少。  截至刚才，我停止了taos服务和taosadapter服务后，实际查看data目录占用大小为23G，实际每日新增大小为5G左右，还是有点不正常，是我这边的参数有设置错误么？ 
具体查看的信息：
`systemctl stop taosd;
`
`systemctl stop taosadapter`

`root@iZbd162lohhznvZ:~# du -sh /data/taos/vnode/vnode3
23G     /data/taos/vnode/vnode3
`

**Comment by yu285** [comment]
咱们总共有多少个表呢

**Comment by QIANGEGEGE** [comment]
好的，已经申请。

**Comment by QIANGEGEGE** [comment]
问题原因：
排查的原因为：每日频繁修改数据标签信息导致的  
因为2.0版本会把所有操作已日志形式记录在这里，所以会导致文件越来越大。
解决方案：
升级3.0版本
ps：升级备份都需要用taosdump来处理。
TDengine 3.x 导入时候的 taosTools 需要从 https://docs.taosdata.com/releases/tools/ 下载

最后再次感谢@yu285的鼎力支持！
