### ISSUE TITLE
stream computing doesn't return data on  time 

### ISSUE THREAD

**Issue by zhouzhou98** [taosdata/TDengine#19988]
流创建语句：
`create stream realtime_value_stream into t_realtime_value_stream SUBTABLE(CONCAT('real-', tname)) as select last(parttime) as parttime,last(close) as close, last(security_id) as security_id, max(high) as high, min(low) as low, last(pre_close) as pre_close, last(volume
) as volume, last(settle_price) as settle_price, last(pre_settle_price) as pre_settle_price, last(money) as money , last(open) as open from t_realtime_value partition by tbname tname state_window(parttime);`
它所依赖的超级表:
`CREATE STABLE `t_realtime_value` (`ts` TIMESTAMP, `parttime` VARCHAR(32), `open` FLOAT, `close` FLOAT, `high` FLOAT, `low` FLOAT, `pre_close` FLOAT, `volume` FLOAT, `money` FLOAT, `settle_price` FLOAT, `pre_settle_price` FLOAT) TAGS (`security_id` VARCHAR(32))`

t_realtime_value每隔几秒有1万的数据插入，但是 t_realtime_value_stream的数据前几天还算更新得快，后面更新就越来越慢
使用语句：
select * from t_realtime_value where security_id = 'AL.2303.XSGE.FC' and p
arttime = '2023-02-15' order by ts desc limit 10\G;
![1](https://user-images.githubusercontent.com/43700073/218920062-6fd1c006-675f-4538-b6fb-3892ea9089e6.png)
查询流创建的超级表的数据
select * from `real-t_realtime_value_al_2303_xsge_fc` where parttime = '2023-02-15'\G; 发现还停留在几十分钟之前的数据。
![2](https://user-images.githubusercontent.com/43700073/218920348-a4615817-824b-40a1-a84f-c49a231293e4.png)

**Comment by yu285** [comment]
1.投篮/突破姿势，尽可能在我现有基础上，做一些矫正。

2.运球投篮——被放一步如何投篮，如何调整脚步迅速稳定出手。

3.结合我的运球习惯制定一下：左右摆球的标准姿势，高度。适合我的突破节奏，适合我抬手直接投篮。总而言之——把之前的基本功训练的动作在身上结合起来，修正，然后用于实战。

4.脚步凌乱可能是没有用好基础的运球步。

5.希望您多观察，即时提出我的问题。

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
