### ISSUE TITLE
setByteArray error reported when using jdbc-jni to connect to TDengine 

### ISSUE THREAD

**Issue by linser2015** [taosdata/TDengine#19993]
**Bug Description**
业务系统中，使用jdbc连接 ，使用prepareStatement。 在进行connnect时 报noSuchMethod，第二次则直接jdk 宕掉。
**To Reproduce**

![image](https://user-images.githubusercontent.com/12657856/218974392-ad77e5ca-b2ed-413e-a5b1-3d09ec82b2d4.png)

部分代码：
![image](https://user-images.githubusercontent.com/12657856/218974612-6512a5e6-0936-4d5c-98d0-0deebe3f4969.png)
。
在此执行时：
在rs.getMetaData()处 直接宕jdk。
![image](https://user-images.githubusercontent.com/12657856/218975381-847e7185-285c-4eba-aaa3-5516836dc2d4.png)

**Comment by linser2015** [comment]
版本信息: tdengine :3.0.2.5   客户端：3.0.2.5   taos-jdbcDriver：3.0.4    。

**Comment by yu285** [comment]
可以手动把 C:\TDengine\driver 下面的taos.dll ,复制到 C:\Windows\System32

**Comment by linser2015** [comment]
怀疑是跟项目有关系：我在idea中  使用demo可以自行成功，并不会出现问题。但是在我们项目中 几乎类似的代码 就会出问题。
我们项目是java 的spring框架 ， 部署在tomcat上的。 可能与这有关系。  总结： 1。   windows td客户端 +tomcat项目 +java  出现问题。    2. windows td客户端 + java demo 不会出现问题。
