### ISSUE TITLE
tdengine v2.2.2.0 could connect to grafana？

### ISSUE THREAD

**Issue by PPQiao** [taosdata/TDengine#20005]
**General Questions**
tdengine v2.2.2.0是否可以连接grafana
文档中只说了v2.4以上的tdengine自带taosAdapter, 然后通过taosAdapter连接grafana, 但是v2.4之前的版本(例如v2.2.2.0)应该如何连接grafana呢?

**Comment by PPQiao** [comment]
v2.2.2.0的connector文件夹里没有tdengine官方文档中说的grafana插件
![image](https://user-images.githubusercontent.com/36836033/219251344-d79d84b9-4ac3-4650-ae68-2f1a494f52a7.png)

**Comment by yu285** [comment]
https://www.taosdata.com/docs/cn/v2.0/connections#grafana

**Comment by PPQiao** [comment]
> https://www.taosdata.com/docs/cn/v2.0/connections#grafana

按照官方文档, grafana在线安装tdengine的插件,也修改了签名配置, 然后还是不行, 版本是2.2.2.0, taos指令也是没问题的
![image](https://user-images.githubusercontent.com/36836033/234154211-a302081c-213a-4f98-885a-68160b9b81e0.png)
![image](https://user-images.githubusercontent.com/36836033/234154374-0e0427f3-1027-4239-a282-4848b2721665.png)

**Comment by sangshuduo** [comment]
换到 3.0.4.0 以上吧

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/

如果还有具体的使用问题，可以加微信：a15652223354
