### ISSUE TITLE
tdengine v3.0.2.3  turns to  offline after one min

### ISSUE THREAD

**Issue by arthur-jx** [taosdata/TDengine#20014]
tdengine v3.0.2.3 单节点部署，过1分钟后就 dnode offline ，   v3.0.2.5以一样
OS: ubuntu 20.04, 22.04  
==================================================
                new log file                      
==================================================
02/16 15:31:19.205326 00042539 DND startup path:/ args:/usr/bin/taosd
02/16 15:31:19.207354 00042539 UTL apoll url not load
02/16 15:31:19.207434 00042539 UTL load from cfg file /etc/taos//taos.cfg success
02/16 15:31:19.207446 00042539 UTL env file:.env not load
02/16 15:31:19.207452 00042539 UTL load from env variables cfg success
02/16 15:31:19.207660 00042539 UTL                      global config
02/16 15:31:19.207665 00042539 UTL =================================================================
02/16 15:31:19.207670 00042539 UTL default      firstEp                  TaosStorageServer:6030
02/16 15:31:19.207675 00042539 UTL default      secondEp                 TaosStorageServer:6030
02/16 15:31:19.207679 00042539 UTL default      fqdn                     TaosStorageServer
02/16 15:31:19.207683 00042539 UTL default      serverPort               6030
02/16 15:31:19.207688 00042539 UTL default      tempDir                  /tmp/
02/16 15:31:19.207692 00042539 UTL default      minimalTmpDirGB          1.00
02/16 15:31:19.207701 00042539 UTL default      shellActivityTimer       3
02/16 15:31:19.207705 00042539 UTL default      compressMsgSize          -1
02/16 15:31:19.207709 00042539 UTL default      compressColData          -1
02/16 15:31:19.207713 00042539 UTL default      queryPolicy              1
02/16 15:31:19.207716 00042539 UTL default      enableQueryHb            0
02/16 15:31:19.207720 00042539 UTL default      querySmaOptimize         0
02/16 15:31:19.207725 00042539 UTL default      queryPlannerTrace        0
02/16 15:31:19.207729 00042539 UTL default      queryNodeChunkSize       32768
02/16 15:31:19.207733 00042539 UTL default      queryUseNodeAllocator    1
02/16 15:31:19.207737 00042539 UTL default      keepColumnName           0
02/16 15:31:19.207741 00042539 UTL default      smlChildTableName        
02/16 15:31:19.207744 00042539 UTL default      smlTagName               _tag_null
02/16 15:31:19.207748 00042539 UTL default      smlDataFormat            0
02/16 15:31:19.207752 00042539 UTL default      smlBatchSize             10000
02/16 15:31:19.207756 00042539 UTL default      maxMemUsedByInsert       1024
02/16 15:31:19.207760 00042539 UTL default      maxRetryWaitTime         10000
02/16 15:31:19.207763 00042539 UTL default      useAdapter               0
02/16 15:31:19.207767 00042539 UTL default      crashReporting           1
02/16 15:31:19.207771 00042539 UTL default      numOfTaskQueueThreads    4
02/16 15:31:19.207775 00042539 UTL default      dataDir                  /var/lib/taos/
02/16 15:31:19.207779 00042539 UTL default      minimalDataDirGB         2.00
02/16 15:31:19.207783 00042539 UTL default      supportVnodes            12
02/16 15:31:19.207787 00042539 UTL default      maxShellConns            50000
02/16 15:31:19.207791 00042539 UTL default      statusInterval           1
02/16 15:31:19.207795 00042539 UTL default      minSlidingTime           10
02/16 15:31:19.207798 00042539 UTL default      minIntervalTime          1
02/16 15:31:19.207802 00042539 UTL default      maxNumOfDistinctRes      10000000
02/16 15:31:19.207806 00042539 UTL default      countAlwaysReturnValue   1
02/16 15:31:19.207810 00042539 UTL default      queryBufferSize          -1
02/16 15:31:19.207813 00042539 UTL default      printAuth                0
02/16 15:31:19.207817 00042539 UTL default      queryRspPolicy           0
02/16 15:31:19.207821 00042539 UTL default      numOfRpcThreads          3
02/16 15:31:19.207825 00042539 UTL default      numOfCommitThreads       3
02/16 15:31:19.207829 00042539 UTL default      numOfMnodeReadThreads    1
02/16 15:31:19.207832 00042539 UTL default      numOfVnodeQueryThreads   12
02/16 15:31:19.207836 00042539 UTL default      ratioOfVnodeStreamThrea  1.00
02/16 15:31:19.207840 00042539 UTL default      numOfVnodeFetchThreads   4
02/16 15:31:19.207844 00042539 UTL default      numOfVnodeRsmaThreads    6
02/16 15:31:19.207848 00042539 UTL default      numOfQnodeQueryThreads   12
02/16 15:31:19.207852 00042539 UTL default      numOfSnodeSharedThreads  2
02/16 15:31:19.207860 00042539 UTL default      numOfSnodeUniqueThreads  2
02/16 15:31:19.207864 00042539 UTL default      rpcQueueMemoryAllowed    834330214
02/16 15:31:19.207868 00042539 UTL default      syncElectInterval        25000
02/16 15:31:19.207872 00042539 UTL default      syncHeartbeatInterval    1000
02/16 15:31:19.207875 00042539 UTL default      syncHeartbeatTimeout     20000
02/16 15:31:19.207879 00042539 UTL default      vndCommitMaxInterval     60000
02/16 15:31:19.207883 00042539 UTL default      monitor                  1
02/16 15:31:19.207887 00042539 UTL default      monitorInterval          30
02/16 15:31:19.207891 00042539 UTL default      monitorFqdn              
02/16 15:31:19.207895 00042539 UTL default      monitorPort              6043
02/16 15:31:19.207898 00042539 UTL default      monitorMaxLogs           100
02/16 15:31:19.207902 00042539 UTL default      monitorComp              0
02/16 15:31:19.207906 00042539 UTL default      crashReporting           1
02/16 15:31:19.207910 00042539 UTL default      telemetryReporting       1
02/16 15:31:19.207913 00042539 UTL default      telemetryInterval        43200
02/16 15:31:19.207917 00042539 UTL default      telemetryServer          telemetry.taosdata.com
02/16 15:31:19.207921 00042539 UTL default      telemetryPort            80
02/16 15:31:19.207925 00042539 UTL default      transPullupInterval      2
02/16 15:31:19.207928 00042539 UTL default      mqRebalanceInterval      2
02/16 15:31:19.207932 00042539 UTL default      ttlUnit                  86400
02/16 15:31:19.207936 00042539 UTL default      ttlPushInterval          86400
02/16 15:31:19.207939 00042539 UTL default      uptimeInterval           300
02/16 15:31:19.207943 00042539 UTL default      queryRsmaTolerance       1000
02/16 15:31:19.207947 00042539 UTL default      walFsyncDataSizeLimit    104857600
02/16 15:31:19.207951 00042539 UTL default      udf                      1
02/16 15:31:19.207955 00042539 UTL default      udfdResFuncs             
02/16 15:31:19.207958 00042539 UTL default      udfdLdLibPath            
02/16 15:31:19.207962 00042539 UTL default      configDir                /etc/taos/
02/16 15:31:19.207966 00042539 UTL default      scriptDir                /etc/taos/
02/16 15:31:19.207970 00042539 UTL default      logDir                   /var/log/taos/
02/16 15:31:19.207974 00042539 UTL default      minimalLogDirGB          1.00
02/16 15:31:19.207978 00042539 UTL default      numOfLogLines            10000000
02/16 15:31:19.207982 00042539 UTL default      asyncLog                 1
02/16 15:31:19.207985 00042539 UTL default      logKeepDays              0
02/16 15:31:19.207989 00042539 UTL default      debugFlag                0
02/16 15:31:19.207993 00042539 UTL default      simDebugFlag             143
02/16 15:31:19.207996 00042539 UTL default      tmrDebugFlag             131
02/16 15:31:19.208000 00042539 UTL default      uDebugFlag               131
02/16 15:31:19.208004 00042539 UTL default      rpcDebugFlag             131
02/16 15:31:19.208007 00042539 UTL default      jniDebugFlag             131
02/16 15:31:19.208011 00042539 UTL default      qDebugFlag               131
02/16 15:31:19.208015 00042539 UTL default      cDebugFlag               131
02/16 15:31:19.208018 00042539 UTL default      dDebugFlag               131
02/16 15:31:19.208022 00042539 UTL default      vDebugFlag               131
02/16 15:31:19.208025 00042539 UTL default      mDebugFlag               131
02/16 15:31:19.208029 00042539 UTL default      wDebugFlag               131
02/16 15:31:19.208033 00042539 UTL default      sDebugFlag               131
02/16 15:31:19.208036 00042539 UTL default      tsdbDebugFlag            131
02/16 15:31:19.208040 00042539 UTL default      tqDebugFlag              131
02/16 15:31:19.208044 00042539 UTL default      fsDebugFlag              131
02/16 15:31:19.208047 00042539 UTL default      udfDebugFlag             131
02/16 15:31:19.208051 00042539 UTL default      smaDebugFlag             131
02/16 15:31:19.208054 00042539 UTL default      idxDebugFlag             131
02/16 15:31:19.208062 00042539 UTL default      tdbDebugFlag             131
02/16 15:31:19.208065 00042539 UTL default      metaDebugFlag            131
02/16 15:31:19.208069 00042539 UTL default      timezone                 Asia/Shanghai (CST, +0800)
02/16 15:31:19.208073 00042539 UTL default      locale                   en_US.UTF-8
02/16 15:31:19.208077 00042539 UTL default      charset                  UTF-8
02/16 15:31:19.208080 00042539 UTL default      assert                   1
02/16 15:31:19.208084 00042539 UTL default      enableCoreFile           1
02/16 15:31:19.208088 00042539 UTL default      numOfCores               6.00
02/16 15:31:19.208092 00042539 UTL default      SSE42                    0
02/16 15:31:19.208096 00042539 UTL default      AVX                      0
02/16 15:31:19.208100 00042539 UTL default      AVX2                     0
02/16 15:31:19.208104 00042539 UTL default      FMA                      0
02/16 15:31:19.208107 00042539 UTL default      SIMD-builtins            0
02/16 15:31:19.208111 00042539 UTL default      openMax                  1048576
02/16 15:31:19.208115 00042539 UTL default      streamMax                16
02/16 15:31:19.208119 00042539 UTL default      pageSizeKB               4
02/16 15:31:19.208123 00042539 UTL default      totalMemoryKB            8147756
02/16 15:31:19.208127 00042539 UTL default      os sysname               Linux
02/16 15:31:19.208130 00042539 UTL default      os nodename              TaosStorageServer
02/16 15:31:19.208134 00042539 UTL default      os release               5.4.0-139-generic
02/16 15:31:19.208138 00042539 UTL default      os version               #156-Ubuntu SMP Fri Jan 20 17:27:18 UTC 2023
02/16 15:31:19.208142 00042539 UTL default      os machine               x86_64
02/16 15:31:19.208145 00042539 UTL default      version                  3.0.2.5
02/16 15:31:19.208149 00042539 UTL default      compatible_version       3.0.0.0
02/16 15:31:19.208153 00042539 UTL default      gitinfo                  1c5390322bf2e5511e366cb25f4a9ab20e63bdad
02/16 15:31:19.208157 00042539 UTL default      buildinfo                Built at 2023-02-09 16:28
02/16 15:31:19.208160 00042539 UTL =================================================================
02/16 15:31:19.213162 00042539 DND start to init dnode env
02/16 15:31:19.213248 00042539 DND succceed to read mnode file /var/lib/taos//dnode/dnode.json
02/16 15:31:19.213279 00042539 DND succceed to read mnode file /var/lib/taos//mnode/mnode.json
02/16 15:31:19.213286 00042539 DND file:/var/lib/taos//qnode/qnode.json not exist
02/16 15:31:19.213290 00042539 DND file:/var/lib/taos//snode/snode.json not exist
02/16 15:31:19.214447 00042539 DND dnode env is initialized
02/16 15:31:19.214456 00042539 DND start to init service
02/16 15:31:19.214466 00042539 DND node:dnode, start to open
02/16 15:31:19.214470 00042539 UTL worker:dnode-mgmt is initialized, min:1 max:1
02/16 15:31:19.214507 00042539 UTL worker:dnode-mgmt:0 is launched, total:1
02/16 15:31:19.214510 00042539 UTL worker:dnode-mgmt, queue:0x564b12d15e20 is allocated, ahandle:0x564b12d15c50
02/16 15:31:19.214526 00042548 UTL worker:dnode-mgmt:0 is running, thread:00042548
02/16 15:31:19.214623 00042549 UDF start to init udfd
02/16 15:31:19.214656 00042549 UDF udfd LD_LIBRARY_PATH: :
02/16 15:31:19.215615 00042549 UDF udfd is initialized
02/16 15:31:19.215671 00042539 DND node:dnode, has been opened
02/16 15:31:19.215692 00042539 DND node:mnode, start to open
02/16 15:31:19.215739 00042539 WAL wal module is initialized, rsetId:3
02/16 15:31:19.215949 00042539 DND succceed to read mnode file /var/lib/taos//mnode/mnode.json
02/16 15:31:19.215960 00042539 DND mnode start to open
02/16 15:31:19.215964 00042539 MND start to open mnode in /var/lib/taos//mnode
02/16 15:31:19.216172 00042539 WAL vgId:1, reset commitVer to -1
02/16 15:31:19.216179 00042539 MND mnode-wal is initialized
02/16 15:31:19.216186 00042539 MND start to init sdb in /var/lib/taos//mnode
02/16 15:31:19.216293 00042539 MND sdb init success
02/16 15:31:19.216298 00042539 MND mnode-sdb is initialized
02/16 15:31:19.216315 00042539 MND sdb table:trans is initialized
02/16 15:31:19.216317 00042539 MND mnode-trans is initialized
02/16 15:31:19.216328 00042539 MND sdb table:cluster is initialized
02/16 15:31:19.216330 00042539 MND mnode-cluster is initialized
02/16 15:31:19.216334 00042539 MND sdb table:mnode is initialized
02/16 15:31:19.216336 00042539 MND mnode-mnode is initialized
02/16 15:31:19.216340 00042539 MND sdb table:qnode is initialized
02/16 15:31:19.216342 00042539 MND mnode-qnode is initialized
02/16 15:31:19.216376 00042539 MND sdb table:snode is initialized
02/16 15:31:19.216380 00042539 MND mnode-snode is initialized
02/16 15:31:19.216388 00042539 MND sdb table:dnode is initialized
02/16 15:31:19.216390 00042539 MND mnode-dnode is initialized
02/16 15:31:19.216394 00042539 MND sdb table:user is initialized
02/16 15:31:19.216398 00042539 MND mnode-user is initialized
02/16 15:31:19.216400 00042539 MND mnode-grant is initialized
02/16 15:31:19.216402 00042539 MND mnode-privilege is initialized
02/16 15:31:19.216408 00042539 MND sdb table:acct is initialized
02/16 15:31:19.216412 00042539 MND mnode-acct is initialized
02/16 15:31:19.216420 00042539 MND sdb table:stream is initialized
02/16 15:31:19.216422 00042539 MND mnode-stream is initialized
02/16 15:31:19.216428 00042539 MND sdb table:topic is initialized
02/16 15:31:19.216431 00042539 MND mnode-topic is initialized
02/16 15:31:19.216435 00042539 MND sdb table:consumer is initialized
02/16 15:31:19.216437 00042539 MND mnode-consumer is initialized
02/16 15:31:19.216441 00042539 MND sdb table:subscribe is initialized
02/16 15:31:19.216444 00042539 MND mnode-subscribe is initialized
02/16 15:31:19.216450 00042539 MND sdb table:vgroup is initialized
02/16 15:31:19.216452 00042539 MND mnode-vgroup is initialized
02/16 15:31:19.216455 00042539 MND sdb table:stb is initialized
02/16 15:31:19.216459 00042539 MND mnode-stb is initialized
02/16 15:31:19.216464 00042539 MND sdb table:sma is initialized
02/16 15:31:19.216466 00042539 MND mnode-sma is initialized
02/16 15:31:19.216502 00042539 MND mnode-infos is initialized
02/16 15:31:19.216515 00042539 MND mnode-perfs is initialized
02/16 15:31:19.216523 00042539 MND sdb table:db is initialized
02/16 15:31:19.216525 00042539 MND mnode-db is initialized
02/16 15:31:19.216528 00042539 MND sdb table:func is initialized
02/16 15:31:19.216530 00042539 MND mnode-func is initialized
02/16 15:31:19.216533 00042539 MND start to reset sdb
02/16 15:31:19.216536 00042539 MND sdb:trans is reset
02/16 15:31:19.216542 00042539 MND sdb:cluster is reset
02/16 15:31:19.216544 00042539 MND sdb:mnode is reset
02/16 15:31:19.216547 00042539 MND sdb:qnode is reset
02/16 15:31:19.216549 00042539 MND sdb:snode is reset
02/16 15:31:19.216553 00042539 MND sdb:dnode is reset
02/16 15:31:19.216556 00042539 MND sdb:user is reset
02/16 15:31:19.216558 00042539 MND sdb:acct is reset
02/16 15:31:19.216561 00042539 MND sdb:stream is reset
02/16 15:31:19.216565 00042539 MND sdb:subscribe is reset
02/16 15:31:19.216567 00042539 MND sdb:consumer is reset
02/16 15:31:19.216570 00042539 MND sdb:topic is reset
02/16 15:31:19.216572 00042539 MND sdb:vgroup is reset
02/16 15:31:19.216576 00042539 MND sdb:sma is reset
02/16 15:31:19.216579 00042539 MND sdb:stb is reset
02/16 15:31:19.216581 00042539 MND sdb:db is reset
02/16 15:31:19.216584 00042539 MND sdb:func is reset
02/16 15:31:19.216595 00042539 MND sdb reset success
02/16 15:31:19.216597 00042539 MND start to read sdb file:/var/lib/taos//mnode/data/sdb.data
02/16 15:31:19.216666 00042539 MND vgId:1, has ready mnode:1, status:ready
02/16 15:31:19.216670 00042539 MND vgId:1, ep:TaosStorageServer:6030 dnode:1
02/16 15:31:19.216679 00042539 MND vgId:1, mnode sync not reconfig since readyMnodes:1 updatingMnodes:0
02/16 15:31:19.216685 00042539 MND read sdb file:/var/lib/taos//mnode/data/sdb.data success, commit index:39 term:2 config:-1
02/16 15:31:19.216718 00042539 MND mnode-sdb is initialized
02/16 15:31:19.216830 00042539 MND mnode-profile is initialized
02/16 15:31:19.216869 00042539 MND mnode-show is initialized
02/16 15:31:19.217205 00042539 MND mnode-query is initialized
02/16 15:31:19.217210 00042539 MND vgId:1, start to open sync, replica:0 selfIndex:0
02/16 15:31:19.217257 00042539 SYN vgId:0, succceed to read sync cfg file /var/lib/taos//mnode/sync/raft_config.json
02/16 15:31:19.217266 00042539 SYN vgId:0, use sync config from sync cfg file
02/16 15:31:19.217268 00042539 SYN vgId:1, start to open sync node, replica:1 selfIndex:0
02/16 15:31:19.217272 00042539 SYN vgId:1, index:0 ep:TaosStorageServer:6030 dnode:1 cluster:3806869437114610393
02/16 15:31:19.217886 00042539 SYN vgId:1, sync addr:6449703155193085953, dnode:1 cluster:3806869437114610393 fqdn:TaosStorageServer ip:172.30.5.50 port:6030 ipv4:839196332
02/16 15:31:19.218389 00042539 SYN vgId:1, sync addr:6449703155193085953, dnode:1 cluster:3806869437114610393 fqdn:TaosStorageServer ip:172.30.5.50 port:6030 ipv4:839196332
02/16 15:31:19.218416 00042539 SYN vgId:1, succceed to read raft store file /var/lib/taos//mnode/sync/raft_store.json
02/16 15:31:19.218442 00042539 SYN vgId:1, sync node commitIndex initialized as 39
02/16 15:31:19.218637 00042539 SYN vgId:1, init sync log buffer. buffer: [39 39 39, 40)
02/16 15:31:19.218648 00042539 SYN vgId:1, sync open, node:0x564b12e060b0 electInterval:25000 heartbeatInterval:1000 heartbeatTimeout:20000, sync:follower, term:2, commit-index:39, first-ver:0, last-ver:39, min:-1, snap:39, snap-term:2, elect-times:0, as-leader-times:0, cfg-ch-times:0, hb-slow:0, hbr-slow:0, aq-items:-1, snaping:-1, replicas:1, last-cfg:-1, chging:0, restore:0, quorum:1, elect-lc-timer:0, hb:0, buffer:[39 39 39, 40), repl-mgrs:{0:0 [0 0, 0)}, members:{num:1, as:0, [TaosStorageServer:6030]}, hb:{0:1676532679218}, hb-reply:{0:1676532679218}
02/16 15:31:19.218654 00042539 MND mnode-sync is opened, id:2
02/16 15:31:19.218657 00042539 MND mnode-sync is initialized
02/16 15:31:19.218662 00042539 MND mnode-telem is initialized
02/16 15:31:19.218669 00042539 MND mnode open successfully
02/16 15:31:19.218672 00042539 UTL worker:mnode-query is initialized, min:4 max:4
02/16 15:31:19.218713 00042539 UTL worker:mnode-query:0 is launched, total:1
02/16 15:31:19.218734 00042539 UTL worker:mnode-query:1 is launched, total:2
02/16 15:31:19.218762 00042539 UTL worker:mnode-query:2 is launched, total:3
02/16 15:31:19.218781 00042539 UTL worker:mnode-query:3 is launched, total:4
02/16 15:31:19.218784 00042539 UTL worker:mnode-query, queue:0x564b12e98c20 is allocated, ahandle:0x564b12d447b0
02/16 15:31:19.218786 00042539 UTL worker:mnode-fetch is initialized, min:1 max:1
02/16 15:31:19.218814 00042539 UTL worker:mnode-fetch:0 is launched, total:1
02/16 15:31:19.218817 00042539 UTL worker:mnode-fetch, queue:0x564b12e991d0 is allocated, ahandle:0x564b12d447b0
02/16 15:31:19.218819 00042539 UTL worker:mnode-read is initialized, min:1 max:1
02/16 15:31:19.218834 00042560 UTL worker:mnode-fetch:0 is running, thread:00042560
02/16 15:31:19.218840 00042539 UTL worker:mnode-read:0 is launched, total:1
02/16 15:31:19.218865 00042539 UTL worker:mnode-read, queue:0x564b12e993f0 is allocated, ahandle:0x564b12d447b0
02/16 15:31:19.218867 00042539 UTL worker:mnode-write is initialized, min:1 max:1
02/16 15:31:19.218872 00042561 UTL worker:mnode-read:0 is running, thread:00042561
02/16 15:31:19.218904 00042539 UTL worker:mnode-write:0 is launched, total:1
02/16 15:31:19.218907 00042539 UTL worker:mnode-write, queue:0x564b12e99640 is allocated, ahandle:0x564b12d447b0
02/16 15:31:19.218849 00042559 UTL worker:mnode-query:3 is running, thread:00042559
02/16 15:31:19.218909 00042556 UTL worker:mnode-query:0 is running, thread:00042556
02/16 15:31:19.218909 00042539 UTL worker:mnode-sync is initialized, min:1 max:1
02/16 15:31:19.218945 00042557 UTL worker:mnode-query:1 is running, thread:00042557
02/16 15:31:19.218951 00042539 UTL worker:mnode-sync:0 is launched, total:1
02/16 15:31:19.218955 00042539 UTL worker:mnode-sync, queue:0x564b12e99890 is allocated, ahandle:0x564b12d447b0
02/16 15:31:19.218958 00042539 UTL worker:mnode-sync-ctrl is initialized, min:1 max:1
02/16 15:31:19.218972 00042562 UTL worker:mnode-write:0 is running, thread:00042562
02/16 15:31:19.218980 00042539 UTL worker:mnode-sync-ctrl:0 is launched, total:1
02/16 15:31:19.218983 00042539 UTL worker:mnode-sync-ctrl, queue:0x564b12e99ae0 is allocated, ahandle:0x564b12d447b0
02/16 15:31:19.218986 00042539 DND node:mnode, has been opened
02/16 15:31:19.218994 00042539 DND node:vnode, start to open
02/16 15:31:19.218999 00042563 UTL worker:mnode-sync:0 is running, thread:00042563
02/16 15:31:19.219024 00042564 UTL worker:mnode-sync-ctrl:0 is running, thread:00042564
02/16 15:31:19.219114 00042539 UTL worker:vnode-query is initialized, min:12 max:12
02/16 15:31:19.219119 00042539 UTL worker:vnode-stream is initialized as auto
02/16 15:31:19.219121 00042539 UTL worker:vnode-fetch is initialized, max:4
02/16 15:31:19.219123 00042539 UTL worker:vnode-mgmt is initialized, min:1 max:1
02/16 15:31:19.219145 00042539 UTL worker:vnode-mgmt:0 is launched, total:1
02/16 15:31:19.219148 00042539 UTL worker:vnode-mgmt, queue:0x564b12e9b610 is allocated, ahandle:0x564b12e99c90
02/16 15:31:19.219153 00042539 DND vnode file:/var/lib/taos//vnode/vnodes.json not exist
02/16 15:31:19.219161 00042539 DND open 0 vnodes with 3 threads
02/16 15:31:19.219163 00042539 DND successfully opened 0 vnodes
02/16 15:31:19.219167 00042539 UDF get dnodeId:1 from env, pipe path:/var/lib/taos//.udfd.sock.1
02/16 15:31:19.218917 00042558 UTL worker:mnode-query:2 is running, thread:00042558
02/16 15:31:19.219247 00042539 UDF udfc initialized
02/16 15:31:19.219250 00042539 DND node:vnode, has been opened
02/16 15:31:19.219320 00042539 SYN vgId:1, restore sync until commitIndex:39
02/16 15:31:19.219323 00042568 UTL worker:vnode-mgmt:0 is running, thread:00042568
02/16 15:31:19.228831 00042539 SYN vgId:1, succeed to write raft store file:/var/lib/taos//mnode/sync/raft_store.json, len:68
02/16 15:31:19.228848 00042539 MND vgId:1, become leader
02/16 15:31:19.228851 00042539 SYN vgId:1, reset sync log buffer. buffer: [39 39 39, 40)
02/16 15:31:19.228860 00042539 SYN vgId:1, become leader one replica start, sync:leader, term:3, commit-index:39, first-ver:0, last-ver:39, min:-1, snap:39, snap-term:2, elect-times:0, as-leader-times:1, cfg-ch-times:0, hb-slow:0, hbr-slow:0, aq-items:-1, snaping:-1, replicas:1, last-cfg:-1, chging:0, restore:0, quorum:1, elect-lc-timer:1, hb:0, buffer:[39 39 39, 40), repl-mgrs:{0:0 [0 0, 0)}, members:{num:1, as:0, [TaosStorageServer:6030]}, hb:{0:1676532679218}, hb-reply:{0:1676532679218}
02/16 15:31:19.235861 00042539 SYN vgId:1, commit sync barrier. index:40, term:3, type:sync-noop
02/16 15:31:19.235886 00042539 MND vgId:1, sync restore finished, and will handle outstanding transactions
02/16 15:31:19.235896 00042539 MND mnode set restored:1
02/16 15:31:19.235901 00042539 SYN vgId:1, restore finished. log buffer: [39 40 40, 41)
02/16 15:31:19.235910 00042539 MND vgId:1, sync started, id:2
02/16 15:31:19.236009 00042539 DND restore 0 vnodes with 3 threads
02/16 15:31:19.236082 00042539 DND TDengine initialized successfully
02/16 15:31:20.222089 00042561 MND dnode:1, mnode syncState from offline to leader, restoreState from 0 to 1
02/16 15:31:20.222111 00042561 MND dnode:1, from offline to online, memory avail:7492194714 total:8343302144 cores:6.00
02/16 15:31:23.609108 00042561 MND information_schema table:information_schema.ins_grants, start to retrieve meta
02/16 15:31:26.018462 00042561 MND information_schema table:information_schema.ins_configs, start to retrieve meta
02/16 15:31:32.628326 00042561 MND information_schema table:information_schema.ins_dnodes, start to retrieve meta
02/16 23:32:14.695419 00042561 MND dnode:1, from offline to online, memory avail:7492194714 total:8343302144 cores:6.00
02/16 15:32:19.340122 00042575 MND dnode:1, in offline state
02/16 15:32:19.340618 00042561 MND succeed to send telemetry report
02/16 15:32:24.348023 00042575 MND dnode:1, in offline state
02/16 15:32:29.356564 00042575 MND dnode:1, in offline state

taos> show dnodes;
     id      |            endpoint            | vnodes | support_vnodes |   status   |       create_time       |              note              |
=================================================================================================================================================
           1 | TaosStorageServer:6030         |      0 |             12 | offline    | 2023-02-16 14:18:45.247 | status msg timeout             |

**Comment by yu285** [comment]
可以把旧日志删除，然后把日志级别设置为 143 ，然后再启动一次。把新生成的taosdlog日志发给我们
