### ISSUE TITLE
Assertion `pBlockCol->type == pColData->type' failed.

### ISSUE THREAD

**Issue by 001466** [taosdata/TDengine#20022]
这个报错怎么解决？

/home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/tsdb/tsdbReaderWriter.c:1150: tsdbReadBlockDataImpl: Assertion `pBlockCol->type == pColData->type' failed.

**Comment by yu285** [comment]
请问版本号是？

**Comment by yu285** [comment]
麻烦提供版本号然后reopen这个问题，暂做关闭处理

**Comment by yu285** [comment]
另外，建议使用 3.0的最新版，目前为 3.0.2.5
