### ISSUE TITLE
The log is loaded after startup, and the database is unavailable

### ISSUE THREAD

**Issue by lbxing** [taosdata/TDengine#20036]
02/18 08:46:36.904000 00016528 VND vgId:5, commit-cb is excuted, fsm:00000298A9931AB0, index:68491, term:7, msg-index:68
491, weak:0, code:0, state:102 leader, type:submit
02/18 08:46:36.943000 00008044 VND vgId:2, commit-cb is excuted, fsm:00000298A9930A70, index:13482, term:4, msg-index:13
482, weak:0, code:0, state:102 leader, type:submit
02/18 08:46:36.966000 00087724 MND stb:1.collection_test.all_sensor, start to retrieve meta
02/18 08:46:36.997000 00066428 VND vgId:3, commit-cb is excuted, fsm:00000298A9931DF0, index:13476, term:4, msg-index:13
476, weak:0, code:0, state:102 leader, type:submit
02/18 08:46:37.014000 00088880 SYN vgId:5, sync get retry epset: index:0 SmartWater-srv:6030
02/18 08:46:37.052000 00016528 VND vgId:5, commit-cb is excuted, fsm:00000298A9931AB0, index:68492, term:7, msg-index:68
492, weak:0, code:0, state:102 leader, type:submit
02/18 08:46:37.096000 00008044 VND vgId:2, commit-cb is excuted, fsm:00000298A9930A70, index:13483, term:4, msg-index:13
483, weak:0, code:0, state:102 leader, type:submit

**Comment by yu285** [comment]
请补充版本信息

**Comment by lbxing** [comment]
> 请补充版本信息

3.0.1.5

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
