### ISSUE TITLE
Topic subscribed cannot be dropped

### ISSUE THREAD

**Issue by Lwc649792393** [taosdata/TDengine#20035]
**数据订阅，删除主题提示：Topic subscribed cannot be dropped**
如何删除无用主题？
![image](https://user-images.githubusercontent.com/16750651/219646203-36b6fd5c-c142-4aa0-9e17-21cc54a31ddd.png)

**Comment by Lwc649792393** [comment]
执行删除消费组命令
![image](https://user-images.githubusercontent.com/16750651/219653170-75f17787-e92e-460a-9322-609a8a802611.png)

**Comment by yu285** [comment]
请问版本号是？

**Comment by Lwc649792393** [comment]
> 请问版本号是？

3.0.2.4

**Comment by yu285** [comment]
需要unsubscribe ,或者等消费者自动离线一段时间后会自动unsubscribe，即可删除

**Comment by sky-03** [comment]
版本3.3.3.0 Community也有同样的问题
<img width="1201" alt="image" src="https://github.com/user-attachments/assets/09621e5b-41dd-4994-a1e5-d7335de67127">
<img width="1218" alt="image" src="https://github.com/user-attachments/assets/75d6c955-5136-4462-b8cc-3c0a3cb2aa0e">
<img width="1225" alt="image" src="https://github.com/user-attachments/assets/f2bc6977-fb27-4e39-866e-4211550025f9">
