### ISSUE TITLE
data subscription doesn't work in cluster environment 

### ISSUE THREAD

**Issue by Lwc649792393** [taosdata/TDengine#20041]
**数据订阅，集群环境消费者无推送，单机正常推送。**

集群(3.0.2.4)：
taos> show topics;
![image](https://user-images.githubusercontent.com/16750651/219847114-679a32bc-09fc-46a6-aacb-d9d19ede006a.png)

taos > show consumers;
![image](https://user-images.githubusercontent.com/16750651/219847556-ad7b9760-7797-49f1-92dc-41a3e3df930a.png)

` 
 func subTest() {

	host := "127.0.0.1" //切换成集群无法接收推送
	user := "root"
	pass := "taosdata"
	dbName := "aam_iot"
	prot := 6030
	db, err := af.Open(host, user, pass, dbName, prot)
	if err != nil {
		panic(err)
	}
	defer db.Close()

	tableName := "t8"
	topicName := "tp8"
	groupID := "groupID8"
	clientId := "test_tmq_client8"
	querySQL := fmt.Sprintf("SELECT * FROM %s.%s;", dbName, tableName)

	_, err = db.Exec(fmt.Sprintf("create database if not exists %s;", dbName))
	if err != nil {
		panic(err)
	}

	_, err = db.Exec(fmt.Sprintf("create table if not exists  %s.%s (ts timestamp,v int, name varchar(32));", dbName, tableName))
	if err != nil {
		panic(err)
	}

	_, err = db.Exec(fmt.Sprintf("create topic if not exists %s as %s;", topicName, querySQL))
	if err != nil {
		panic(err)
	}

	consumer, err := tmq.NewConsumer(&tmqcommon.ConfigMap{
		"group.id":                     groupID,
		"auto.offset.reset":            "earliest",
		"td.connect.ip":                host,
		"td.connect.user":              user,
		"td.connect.pass":              pass,
		"td.connect.port":              strconv.Itoa(prot),
		"client.id":                    clientId,
		"enable.auto.commit":           "false",
		"enable.heartbeat.background":  "true",
		"experimental.snapshot.enable": "true",
		"msg.with.table.name":          "true",
	})
	if err != nil {
		panic(err)
	}
	err = consumer.Subscribe(topicName, nil)
	if err != nil {
		panic(err)
	}
	defer consumer.Unsubscribe()
	defer consumer.Close()

	// 协程每隔1s插入数据
	go func() {
		for {
			_, err := db.Exec(fmt.Sprintf("insert into %s.%s values(now,1,'你好')", dbName, tableName))
			if err != nil {
				fmt.Print(err)
			}
			time.Sleep(1 * time.Second)
		}
	}()

	rows := make([]*tmqcommon.Data, 0)

	for {
		ev := consumer.Poll(0)
		if ev != nil {
			switch e := ev.(type) {
			case *tmqcommon.DataMessage:
				data, ok := e.Value().([]*tmqcommon.Data)
				if !ok {
					panic(e)
				}

				//解析接收消息
				for _, d := range data {
					fmt.Println(d.TableName)
					for _, c := range d.Data {
						for _, cc := range c {
							fmt.Println(cc)
						}
					}
				}
				rows = append(rows, data...)
			case tmqcommon.Error:
				fmt.Fprintf(os.Stderr, "%% Error: %v: %v\n", e.Code(), e)
				panic(e)
			}
			consumer.Commit()
		}
	}
}
`

**Comment by yu285** [comment]
我们看下

**Comment by hjxilinx** [comment]
@Lwc649792393 ， 3.0.3.0 中修复了集群环境下的订阅问题，请升级到 3.0.3.0在试一试。
特别提示：3.0.3.0 升级需要客户端和服务器同步升级。
