### ISSUE TITLE
last(*) sql return data mapping error

### ISSUE THREAD

**Issue by Ciser1104** [taosdata/TDengine#20051]
**Bug Description**
近期TDengine升级到3.0.2版本后，项目中select last(*) 查询的数据实体映射出现了问题
![image](https://user-images.githubusercontent.com/125844483/219998341-457e0040-a900-4151-be80-6e28cb74cbbf.png)
发现字段名称都加上了last(xx) ，导致实体类接收解析不出来，请问有什么解决办法吗？
![image](https://user-images.githubusercontent.com/125844483/219998762-2dcaf309-ce51-467b-b421-dea8755e3afb.png)

下图是之前2.x版本查询出的数据
![image](https://user-images.githubusercontent.com/125844483/219998500-d772dadd-5014-47f7-96c3-b1cf726cc6e5.png)

**Comment by yu285** [comment]
可以使用 KeepColomnName 参数控制返回结果为 “列名”或 “last（列名）”，详情可参考文档
