### ISSUE TITLE
TDengine start failed in docker

### ISSUE THREAD

**Issue by aaaaaadi** [taosdata/TDengine#20065]
![taos](https://user-images.githubusercontent.com/26601868/220522446-3403c8aa-a01d-45b3-9b49-99b4ff9d09bb.png)

linux服务器上,docker镜像版本是3.0.2.4.本来一直运行的好好的,今天突然无法启动,报错上面信息.共创建了5个数据库,superVnodes设置为512.服务器是16G8核心的阿里云.查看信息内存占用free 220M, buff/cache 8.1G,used7.2G.
这种错误信息容器还能恢复么,如果不能恢复,数据我挂载到系统盘的,数据可以恢复么,谢谢!

**Comment by yu285** [comment]
咱们创建了多少个流呢

**Comment by aaaaaadi** [comment]
> 咱们创建了多少个流呢

没有创建流吧,就是正常的查询,查询时间范围也不大,数据量总体在3GB左右.使用程序定时插入数据、查询数据.之前一直没问题,突然报错启动不来的

**Comment by yu285** [comment]
> > 咱们创建了多少个流呢
> 
> 没有创建流吧,就是正常的查询,查询时间范围也不大,数据量总体在3GB左右.使用程序定时插入数据、查询数据.之前一直没问题,突然报错启动不来的

建议先用 3025 启动一下，如果还是不行，可以加微信 a15652223354 做具体排查。
