### ISSUE TITLE
TDengine's configuration file would be truncated？

### ISSUE THREAD

**Issue by SpringLin97** [taosdata/TDengine#20071]
![1677048812862](https://user-images.githubusercontent.com/63085858/220545181-5086fe09-a665-4821-90b8-7853f0a39fc8.png)

**Comment by yu285** [comment]
请问是每次启动都会清空么

**Comment by SpringLin97** [comment]
> 请问是每次启动都会清空么

会概率清空，系统重启情况下

**Comment by yu285** [comment]
有影响整个库的读写使用吗？这个库的版本是？

**Comment by SpringLin97** [comment]
> 有影响整个库的读写使用吗？这个库的版本是？

会影响数据库读写，无法正常运行了，2.6.0.8

**Comment by yu285** [comment]
建议先升级到 2.6.0.34 观察下，不应该有这个现象
