### ISSUE TITLE
taosdump backup database ERROR: writeResultToAvroNative

### ISSUE THREAD

**Issue by zrenplus** [taosdata/TDengine#20075]
taosdump backup databases is slow  and we can see some errors.Error information as follow:
ERROR: writeResultToAvroNative() LN5035, actual dump out: 7206593, batch 7206595

**Comment by sangshuduo** [comment]
what TDengine version is?

**Comment by zrenplus** [comment]
3.0.2.28

**Comment by sangshuduo** [comment]
> 3.0.2.28

Interested in where you download this version? You can see all available releases at [https://docs.taosdata.com/releases/tdengine/.](https://docs.taosdata.com/releases/tdengine/.) We had not released 3.0.2.28.
