### ISSUE TITLE
Query the table created by the stream generates an error, and the service is immediately crashed

### ISSUE THREAD

**Issue by cmkcmk181** [taosdata/TDengine#20082]
**Bug Description**
查询stream创建的表后报错，服务直接挂掉。

**To Reproduce**
1.创建stream使用以下语句后：
create stream warn_pressure into warn_pressure SUBTABLE(CONCAT('warn_pressure_',tname))  as select equ_model,min(pressure) as pressure,case  when pressure<1 then '压力过低'  else '压力过高' end as remark from fire_extinguisher where pressure<1 or pressure>1.5 PARTITION BY tbname tname interval (5s); 

2.插入一条触发数据：
insert into SD1001 USING fire_extinguisher  TAGS("SD1001","KY001IJ01338444")  VALUES (NOW, 30.6,15.5,1.6);

3.查询语句报错：
select * from warn_pressure_sd1001;

**Screenshots**
![微信截图_20230221161912](https://user-images.githubusercontent.com/8915324/220287563-f741b205-646d-4474-ad64-9f934d5c244f.png)

**Environment (please complete the following information):**
 - OS: windows11
 - Memory, CPU, current Disk Space
 - TDengine Version 3.0.2.5

**Comment by huskar-t** [comment]
请提供建库建表语句

**Comment by cmkcmk181** [comment]
create stable fire_extinguisher(ts timestamp, temperature float, voltage float, pressure float) TAGS (equ_code varchar(64),equ_model varchar(64));

**Comment by huskar-t** [comment]
此问题已修复，将在 3.0.2.6 版本发布

**Comment by cmkcmk181** [comment]
ok
