### ISSUE TITLE
TDengine-client-3.0.2.5-macOS-x64.pkg (30.3 M) connect failed

### ISSUE THREAD

**Issue by fouthfire** [taosdata/TDengine#20081]
$ taos
dyld: Library not loaded: /opt/taos/TDengine/debug/build/lib/libtaos.1.dylib
  Referenced from: /usr/local/bin/taos
  Reason: no suitable image found.  Did find:
	/usr/local/lib/libtaos.1.dylib: cannot load 'libtaos.1.dylib' (load command 0x80000034 is unknown)
	/usr/local/Cellar/tdengine/3.0.2.5/driver/libtaos.3.0.2.5.dylib: cannot load 'libtaos.3.0.2.5.dylib' (load command 0x80000034 is unknown)
Abort trap: 6

**Comment by facetosea** [comment]
> $ taos dyld: Library not loaded: /opt/taos/TDengine/debug/build/lib/libtaos.1.dylib Referenced from: /usr/local/bin/taos Reason: no suitable image found. Did find: /usr/local/lib/libtaos.1.dylib: cannot load 'libtaos.1.dylib' (load command 0x80000034 is unknown) /usr/local/Cellar/tdengine/3.0.2.5/driver/libtaos.3.0.2.5.dylib: cannot load 'libtaos.3.0.2.5.dylib' (load command 0x80000034 is unknown) Abort trap: 6

/usr/local/lib 这个目录存在么？如果不存在的话尝试手动创建一下
ls -al /usr/local/lib | grep taos 查看一下有哪些文件

**Comment by fouthfire** [comment]
![image](https://user-images.githubusercontent.com/25971524/220319189-6e960f5b-6f0a-43cf-9276-c2be68d8ebf7.png)
目录之前不存在，通过terminal安装的，就都有了，但是还是不行

**Comment by facetosea** [comment]
看起来文件没有问题啊，您是docker安装的虚拟镜像mac系统么？看看这个有帮助么
https://stackoverflow.com/questions/32730312/reason-no-suitable-image-found
