### ISSUE TITLE
多次插入重复数据后，影响查询花费的时间

### ISSUE THREAD

**Issue by dongjialiang** [taosdata/TDengine#20087]
**Bug Description**
在Ubuntu系统，使用docker安装，版本为3.0.2.5，对同一张表，重复批量插入一批数据，一段时间后停止，再次查询发现花费时间变长，数据盘占用变大，但是计数值没变。
尝试在Windows系统测试，发现偶尔计数值出现的数值不正确，比正确的数据量要大。

**To Reproduce**
1. 在Ubuntu系统，插入一批数据
2. 使用count查询，速度不到1秒，数据盘占用空间不大
3. 开始每10分钟插入一次这批数据
4. 4个小时后停止插入
5. 使用count，查询花费时间超过2秒，数据盘占用空间变为原来的几倍
6. 在Windows重复上述过程，使用count命令查询，count值偶尔比正确的总数要大。

**Expected Behavior**
希望看下该问题是什么原因导致的。

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS、Windows 10
 - Memory, CPU, current Disk Space
 - TDengine Version 3.0.2.5

**Additional Context**

**Comment by yu285** [comment]
当前机制导致，可以等后面compact功能发出，可以做碎片整理。

**Comment by ZhangChengJie** [comment]
> 当前机制导致，可以等后面compact功能发出，可以做碎片整理。

请问目前最新版本3.2.0.0中是否包含了 compact？ 
或者计划哪个版本会推出？同样有这样的使用场景

**Comment by yu285** [comment]
> > 当前机制导致，可以等后面compact功能发出，可以做碎片整理。
> 
> 请问目前最新版本3.2.0.0中是否包含了 compact？ 或者计划哪个版本会推出？同样有这样的使用场景 @yu285

抱歉，compact 后续被作为企业版功能了。

开源用户可以用数据导出导入的方式清理碎片，或者insert into xxxx select * xxxx
