### ISSUE TITLE
插入16M条记录后Crash

### ISSUE THREAD

**Issue by EricWice** [taosdata/TDengine#201]
写了一个Python脚本插入数据，每条记录约600个字节，在连续插入15658948条后Crash了，返回error: commit log init failed

这时已经建立了3500000张表。之后重启数据库就没法用了，在超级表上运行count(*)之类的查询出现如下错误：
07/26 14:56:21.324695 7ef698a0b700 ERROR UTL sched is not ready, msg:0x7ef698a0abd0 is dropped
07/26 14:56:21.326018 7ef678d42700 ERROR UTL sched is not ready, msg:0x7ef678d41b80 is dropped
07/26 14:56:21.328514 7ef698a0b700 ERROR UTL sched is not ready, msg:0x7ef698a0abd0 is dropped
07/26 14:56:21.329032 7f80f4a93700 ERROR UTL sched is not ready, msg:0x7f80f4a92ba0 is dropped
07/26 14:56:21.329566 7ef66baf5700 ERROR UTL sched is not ready, msg:0x7ef66baf4b80 is dropped
07/26 14:56:21.338894 7f7ff8379700 ERROR DND QInfo:0x7ef65d43c870 error data file:v9f1810.head in vid:9, fid:1809, fid range:1809-118
07/26 14:56:21.376485 7f7ff8379700 ERROR DND QInfo:0x7ef65d9b5c60 error data file:v6f1810.head in vid:6, fid:1809, fid range:1809-118

是不是有些表里的数据已经Corrupt了？

**Comment by hzcheng** [comment]
您硬盘空间还有多少？

**Comment by EricWice** [comment]
2T的硬盘，现在用了不到30%:
Filesystem      Size  Used Avail Use% Mounted on
udev             16G     0   16G   0% /dev
tmpfs           3.2G  1.5M  3.2G   1% /run
/dev/sdb2       1.8T  464G  1.3T  27% /
