### ISSUE TITLE
超级表添加列报错，并且已经转义

### ISSUE THREAD

**Issue by zhgqiang** [taosdata/TDengine#20129]
3.0.2.5 版本
![image](https://user-images.githubusercontent.com/8361981/220873727-24fbd2b7-5479-476b-8171-23ac9b37c962.png)
之前文档有说加转义后区分大小写，但是报错
![image](https://user-images.githubusercontent.com/8361981/220873248-ef318ba0-a4c0-4a1f-b614-b155062d42a3.png)

**Comment by feici02** [comment]
如下图所示，我没有复现这个问题，请进一步确认或提供更多的信息。
![image](https://user-images.githubusercontent.com/5568663/221085457-901b96c1-44af-401c-a8fd-b2d21f014972.png)

**Comment by zhgqiang** [comment]
@feici02 是超级表，不是普通表
![image](https://user-images.githubusercontent.com/8361981/221086589-3817a95e-253b-4e23-957f-cfb77f742e10.png)

**Comment by feici02** [comment]
> @feici02 是超级表，不是普通表 ![image](https://user-images.githubusercontent.com/8361981/221086589-3817a95e-253b-4e23-957f-cfb77f742e10.png)

**Comment by feici02** [comment]
这是一个bug，我们会尽快修复，感谢您的反馈。
