### ISSUE TITLE
Task context not exist when using last function

### ISSUE THREAD

**Issue by shi0513** [taosdata/TDengine#20155]
最开始版本是3.0.2.0，升级到3.0.2.6，依然有如下图问题
![微信图片_20230224171117](https://user-images.githubusercontent.com/117802810/221138778-03fbe38f-2833-4328-9cb7-56e41f353ffd.png)
![客户端查询报错信息](https://user-images.githubusercontent.com/117802810/221131850-7f3f5ee4-548d-4b8a-86fe-d4c536d3e202.png)
![查询sq服务端l控制台信息](https://user-images.githubusercontent.com/117802810/221131974-dcecc4d2-6201-4796-992e-6219ca3bd937.png)
![服务器客户端查询报错信息](https://user-images.githubusercontent.com/117802810/221132293-91fd5e5f-1e8f-416c-9925-1655abd87c26.png)
![java代码执行sql报错信息](https://user-images.githubusercontent.com/117802810/221132580-7cea5aa8-d135-4775-8151-bd6f721f6f8a.jpg)

**Comment by feici02** [comment]
Hi, 如下图所示，我在执行taosBenchmark后生成的超级表test.meters上，使用了last()函数，并没有复现这个问题。
<img width="523" alt="image" src="https://user-images.githubusercontent.com/5568663/221404492-ed825e55-7cc6-4e0f-a3ec-d620bb9efdaf.png">

**Comment by shi0513** [comment]
> Hi, 如下图所示，我在执行taosBenchmark后生成的超级表test.meters上，使用了last()函数，并没有复现这个问题。 <img alt="image" width="523" src="https://user-images.githubusercontent.com/5568663/221404492-ed825e55-7cc6-4e0f-a3ec-d620bb9efdaf.png">
![image](https://user-images.githubusercontent.com/117802810/221468139-97d0c0d1-dc5e-4faf-8af3-5a94d0bd1de4.png)

**Comment by feici02** [comment]
taosd crashes when last() is called after a table schema change.
This issue has been fixed.
