### ISSUE TITLE
 unable to load taos C library：Could not find module 'taos' (or one of its dependencies). 

### ISSUE THREAD

**Issue by AlvinCage** [taosdata/TDengine#20168]
**Bug Description**
pip3 install taospy -i https://pypi.tuna.tsinghua.edu.cn/simple
成功安装 taospy-2.7.5，import taos报错如下：
taos.error.InterfaceError: [0xffff]: unable to load taos C library: Could not find module 'taos' (or one of its dependencies). Try using the full path with constructor syntax

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [3.0.2]

![image](https://user-images.githubusercontent.com/51590855/221367407-b4a53348-5dc1-45f0-ae97-341d885f2ef4.png)

**Comment by feici02** [comment]
使用Python连接器，除了要安装taospy，还要安装TDengine的客户端驱动；
具体可参考在线文档中的说明：[安装-准备](https://docs.taosdata.com/connector/python/#%E5%87%86%E5%A4%87)-第3项。

**Comment by feici02** [comment]
Hi, I will close this issue, if you have any further problems, please feel free to re-open it. Thanks.
