### ISSUE TITLE
RPC ERROR TSC 0x7f4fb8001720 0x3, failed to send

### ISSUE THREAD

**Issue by asdf2fzfvree3** [taosdata/TDengine#20176]
**版本：2.6.0.28
问题：安装非集群后，/var/log/taos/taosinfo.0日志提示以下内容，然后taosd进程自动退出了：**
02/26 18:03:52.921229 00127179 RPC ERROR TSC 0x7f4fb8001420 0x3, failed to send, msgLen:141 written:-1, reason:Operation not permitted
02/26 18:03:53.216228 00127179 RPC ERROR TSC 0x7f4fb80012a0 0x3, failed to send, msgLen:141 written:-1, reason:Operation not permitted
02/26 18:03:53.221227 00127179 RPC ERROR TSC 0x7f4fb8001420 0x3, failed to send, msgLen:141 written:-1, reason:Operation not permitted
02/26 18:03:53.826323 00127179 RPC ERROR TSC 0x7f4fb80015a0 0x3, failed to send, msgLen:141 written:-1, reason:Operation not permitted
02/26 18:03:53.831200 00127179 RPC WARN TSC 0x3, connection error. retry to send request again. numOfTry=1 msgType=103
02/26 18:03:53.831308 00127179 RPC ERROR TSC 0x7f4fb8001720 0x3, failed to send, msgLen:141 written:-1, reason:Operation not permitted
02/26 18:03:53.836202 00127179 RPC WARN TSC 0x3, connection error. notify client query over. numOfTry=2 msgType=103
02/26 18:03:54.126256 00127179 RPC ERROR TSC 0x7f4fb80015a0 0x3, failed to send, msgLen:141 written:-1, reason:Operation not permitted
02/26 18:03:54.131245 00127179 RPC ERROR TSC 0x7f4fb8001720 0x3, failed to send, msgLen:141 written:-1, reason:Operation not permitt

**Comment by asdf2fzfvree3** [comment]
![image](https://user-images.githubusercontent.com/126437351/221538945-7689c551-a967-4a4e-923b-25a089553eb5.png)

**Comment by yu285** [comment]
可以先升级到 2.6.0.34 我们观察下。
