### ISSUE TITLE
outdated pytest query/isNullTest.py

### ISSUE THREAD

**Issue by natsu1375** [taosdata/TDengine#20170]
The version of TDengine I built
```
./taos --version
version: 3.0.2.5
```

https://github.com/taosdata/TDengine/blob/main/tests/pytest/query/isNullTest.py
```
62 tdSql.error("select count(*) from st where t2 <> null")
63 tdSql.error("select count(*) from st where t2 = null")
```
 
`python test.py -f query/query/isNullTest.py`
After running the above command, I got the following error message
```
2023-02-26 15:33:27.500172 /z1/TDengine-main/tests/pytest/query/isNullTest.py(62) failed: sql:select count(*) from st where t2 <> null, expect error not occured
```

However I run the sql `select count(*) from st where t2 <> null` in the taos command line, it's ok, no error reported.
```
taos> select count(*) from st where t2 <> null;
Query OK, 0 row(s) in set (0.000669s)
```

**Comment by sangshuduo** [comment]
Yes, the test cases in the pytest directory are no more used in 3.0 but the source code is still kept.

**Comment by natsu1375** [comment]
The readme file under tests/ is obsolete. After exploring the tests/ directory, I have no idea about how the test proceeds, maybe it would be better to update the readme file.
There're plenty of .sim files under tests/script/tsim/ written in a ad hoc grammar, any docment about them?
Thanks.

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
