### ISSUE TITLE
tdengine v3.0.2.6 TIMETRUNCATE with 1d return unexpected result

### ISSUE THREAD

**Issue by Gerrit1999** [taosdata/TDengine#20198]
**Bug Description**
TIMETRUNCATE 结合1d使用，返回的结果错误

**Screenshots**
![image](https://user-images.githubusercontent.com/71630591/221733553-d28085d6-4559-4550-9313-a9b82f292e4d.png)

**Environment (please complete the following information):**
 - OS: Windows10-x64
 - Memory, CPU, current Disk Space
 - TDengine Version 3.0.2.6

**Comment by Gerrit1999** [comment]
使用TO_UNIXTIMESTAMP可以得到正确的结果
![image](https://user-images.githubusercontent.com/71630591/222058992-3c6f8a4b-43af-409f-bc02-b247d34894c5.png)

**Comment by yogaxu** [comment]
![微信截图_20230301161141](https://user-images.githubusercontent.com/20737702/222081580-193ff6b7-ec97-43cb-8eab-4fc0beea2e67.png)

**Comment by feici02** [comment]
This is a bug on Windows, we will fix it as soon as possible.
Thank you for the feedback.
