### ISSUE TITLE
if udf support multi argument ?

### ISSUE THREAD

**Issue by worker24h** [taosdata/TDengine#20239]
最近在统计成功率，发现需要进行两次查询，第一次计算成功数，第二次计算总数，最后进行两者相除，由于业务场景比较复杂，sql写的大，因此想开发一个UDF，举例说明：
**统计学校男生的比例**
例如：select percent(sex，'男') from students
返回：0.53

问题1： 是否支持多个参数？
通过查看官方文档以及demo l2norm发现，UDF接口貌似不能提供多个参数。
```
//列数据
typedef struct SUdfColumn {
  SUdfColumnMeta colMeta;
  bool           hasNull;
  SUdfColumnData colData;
} SUdfColumn;

//数据块
typedef struct SUdfDataBlock {
  int32_t numOfRows;
  int32_t numOfCols;
  SUdfColumn **udfCols;
} SUdfDataBlock;
``` 

问题2：官方提供 l2norm中的start函数中，buf内存是如何管理的？ 感觉这里应该交给用户进行malloc？ 如果原生框架负责申请内存，又如何保证内存长度足够满足用户需求？
```
DLL_EXPORT int32_t l2norm_start(SUdfInterBuf *buf) {
  *(int64_t*)(buf->buf) = 0; // 这里内存长度 是如何申请的？
  buf->bufLen = sizeof(double);
  buf->numOfResult = 0;
  return 0;
}
```

**Comment by shenglian-zhou** [comment]
1) udf interface can support multiple arguments, it can be seen that each of udfCols is an udfColumn
2) create function support has subclause bufSize. the framework is responsible for the memory allocation.

**Comment by worker24h** [comment]
> 1. udf interface can support multiple arguments, it can be seen that each of udfCols is an udfColumn
> 2. create function sql statement has subclause bufSize. the framework is responsible for the memory allocation.

Thank you for your answer, but I have another question. 
I understand `SUdfDataBlock` is a result set. Where are the udf parameters stored? Can you give a simple code，thanks

**Comment by worker24h** [comment]
I have solved the problem and I will close the issue.  
The udf code is:   https://github.com/worker24h/TDengine-udf
