### ISSUE TITLE
函数timetruncate结果与官方文档不一致

### ISSUE THREAD

**Issue by lemonschen** [taosdata/TDengine#20257]
```
Microsoft Windows [版本 10.0.22000.1641]
(c) Microsoft Corporation。保留所有权利。

C:\WINDOWS\system32>taos -V
version: 3.0.2.5

C:\WINDOWS\system32>taos
Welcome to the TDengine Command Line Interface, Client Version:3.0.2.5
Copyright (c) 2022 by TDengine, all rights reserved.

Server is Community Edition.

taos> select TIMETRUNCATE('2020-01-01 23:00:00', 1d, 1);
 timetruncate('2020-01-01 23:00:00', 1d, 1) |
=============================================
 2020-01-01 22:59:58.797 |
Query OK, 1 row(s) in set (0.010001s)

taos>
```

**Comment by lemonschen** [comment]
## 官方文档内容
TIMETRUNCATE
TIMETRUNCATE(expr, time_unit [, ignore_timezone])

ignore_timezone: {
    0
  | 1
}

功能说明：将时间戳按照指定时间单位 time_unit 进行截断。

返回结果数据类型：TIMESTAMP。

应用字段：表示 UNIX 时间戳的 BIGINT, TIMESTAMP 类型，或符合日期时间格式的 VARCHAR, NCHAR 类型。

适用于：表和超级表。

使用说明：

支持的时间单位 time_unit 如下： 1b(纳秒), 1u(微秒)，1a(毫秒)，1s(秒)，1m(分)，1h(小时)，1d(天), 1w(周)。
返回的时间戳精度与当前 DATABASE 设置的时间精度一致。
输入包含不符合时间日期格式的字符串则返回 NULL。
当使用 1d 作为时间单位对时间戳进行截断时， 可通过设置 ignore_timezone 参数指定返回结果的显示是否忽略客户端时区的影响。 例如客户端所配置时区为 UTC+0800, 则 TIMETRUNCATE('2020-01-01 23:00:00', 1d, 0) 返回结果为 '2020-01-01 08:00:00'。 而使用 TIMETRUNCATE('2020-01-01 23:00:00', 1d, 1) 设置忽略时区时，返回结果为 '2020-01-01 00:00:00' ignore_timezone 如果忽略的话，则默认值为 1 。

**Comment by lemonschen** [comment]
换了3.0.2.6也一样

**Comment by feici02** [comment]
与[20198](https://github.com/taosdata/TDengine/issues/20198)重复，这是Windows平台的bug，我们会尽快解决。
