### ISSUE TITLE
关于使用delete批量删除

### ISSUE THREAD

**Issue by zhengjieyuan** [taosdata/TDengine#20254]
使用版本：3.0.1.4
通过Taos Shell 连接数据库，执行  delete from wxalarm;        wxalarm是超级表。
显示信息： Query OK, 189778  of 189778  rows affected
而不是提示 Deleted 189778  row(s) from 1020 table(s) (0.421950s)

请问是哪里设置问题？

**Comment by feici02** [comment]
不是，没有这样的配置，不同版本可能会对TDengine CLI(taos)的输出进行调整。
