### ISSUE TITLE
Can TDengine add data expiration strategy

### ISSUE THREAD

**Issue by coloz** [taosdata/TDengine#2025]
例如让数据在指定时间自动清除。
在实际物联网大数据场景，一些远古数据，我们只想保留计算结果，没必要再保留原始数据。目前用redis、mongo等都有expire策略、InfluxDB\opentsdb也有duration持续策略，希望TDengine也能提供了一个方案。

**Comment by coloz** [comment]
InfluxDB\opentsdb也有duration持续策略

**Comment by coloz** [comment]
daysToKeep貌似是全局的，希望能有类似其他数据库一样的针对单一数据的设置

**Comment by liuyq-617** [comment]
[https://www.taosdata.com/en/documentation/taos-sql/#Database-Management](url)
`CREATE DATABASE [IF NOT EXISTS] db_name [KEEP keep]`
       KEEP is used for data retention policy.
Currently, the granularity is only at the database level

**Comment by coloz** [comment]
希望官网上个有搜索功能的文档系统

**Comment by hzcheng** [comment]
目前针对表的过期策略，短期内应该是不会考虑的。如果把不同过期策略的表放在不同的DB能否满足您的需求？

**Comment by coloz** [comment]
> 目前针对表的过期策略，短期内应该是不会考虑的。如果把不同过期策略的表放在不同的DB能否满足您的需求？

也是一个办法，谢谢
