### ISSUE TITLE
query throw exception in taos-jdbcdriver-3.1.0  with spark

### ISSUE THREAD

**Issue by lowe00** [taosdata/TDengine#20277]
TDengine版本：3.0.2.6
taos-jdbcdriver版本：3.1.0
问题现象：使用spark sql jdbc 进行查询，查询字段如果不带表的主键则会报错，经多次测试发现3.0必带主键作为查询字段查询，2.6则不需要，具体情况可看下面场景
场景1：不带主键查询（正常）
SELECT monitor_id FROM risk_event WHERE warn_time BETWEEN 1677686400000 AND 1677772800000;
场景2：带主键查询（异常）
SELECT warn_time,monitor_id FROM risk_event WHERE warn_time BETWEEN 1677686400000 AND 1677772800000;
报错如下
![image](https://user-images.githubusercontent.com/33248806/223054955-da879d38-0a5c-4617-a08b-8dc29e81a006.png)

**Comment by xiao-yu-wang** [comment]
能提供一下risk_event这个表的建表语句吗？

**Comment by lowe00** [comment]
> 能提供一下risk_event这个表的建表语句吗？

CREATE STABLE clbs.risk_event (
   warn_time timestamp,
   id NCHAR(40),
   number NCHAR(30),
   event_id NCHAR(40),
   brand NCHAR(20),
   time BIGINT,
   risk_id NCHAR(40),
   risk_number NCHAR(30),
   media_id NCHAR(40),
   media_name NCHAR(30),
   media_url NCHAR(100),
   warn_id INT
)
TAGS (monitor_id NCHAR(40));

**Comment by lowe00** [comment]
> 能提供一下risk_event这个表的建表语句吗？

可以看一下这两张图片的对比，都是taos-jdbcdriver中TSDBPreparedStatement的preprocessSql()，第一张是3.1.0，第二张是2.0.38，处理WHERE 1=0时，因为相同sql 2.0.38是没问题的，可能问题原因在这里
![a10b46c63e80a9d02018833f62d5b50](https://user-images.githubusercontent.com/33248806/223337349-cad4fd89-5f48-4020-b7c8-ade2c4da2eb5.png)

![32ab94b6f0465e55f7690bbfe4634fe](https://user-images.githubusercontent.com/33248806/223337406-f8971139-0370-468b-a1f8-68f12884f425.png)
