### ISSUE TITLE
invalid resultset pointer,failed to connect to server

### ISSUE THREAD

**Issue by wowo404** [taosdata/TDengine#2027]
**Bug Description**
使用mybatis+druid访问tdengine，发生了invalid resultset pointer，我照着github issue上#1477回答的将配置文件中的sockettype配置成tcp，然后重启数据库，在数据库服务器上用taos正常访问，java服务重启后无法连接数据库服务器，java服务的报错日志有create connection error, url: jdbc:TAOS://192.168.17.230:6020/manufacture, errorCode 79, state 及failed to connect to server.
并且，修改了配置文件中的sockettype成tcp后，在服务器上用taos命令访问，停留一会儿后，偶尔会在命令窗口产生这样一条错误输出日志  05/25 17:21:14.484141 8077 7f322c709700 ERROR UTL failed to connect socket, ip:192.168.17.230, port:6030, reason: Connection refused，这在我修改配置之前是没有出现过的。
java服务无法连接数据库后，数据库的日志输出如图
![WRVL$DFQHYOGG5% D%U)1PQ](https://user-images.githubusercontent.com/39786064/82799494-b7985a00-9eac-11ea-9049-c6ae1131e7a5.png)

**Comment by liuyq-617** [comment]
shellActivityTimer 20

Refer to this
[https://github.com/taosdata/TDengine/issues/1477#issuecomment-612301920](url)

**Comment by Shawshank-Smile** [comment]
vim /etc/taos/taos.cfg

shellActivityTimer 20  will work

**Comment by sangshuduo** [comment]
长时间没有回复，关闭此 issue
