### ISSUE TITLE
td v2.0.7.0, tables will be dropped from sdb

### ISSUE THREAD

**Issue by niaoWo36** [taosdata/TDengine#20283]
我想问下有部分超级表跟子表为啥会被删除，是不是什么配置导致的。部分日志如下：

03/06 07:45:05.000267 0x7fe749ffb700 VND vgId:5, sync role changed from offline to master
03/06 07:45:05.000283 0x7fe749ffb700 CQ  vgId:5, start all CQs
03/06 07:45:05.003027 0x7fe754c934c0 DND there are total vnodes:3, openned:3 failed:0
03/06 07:45:05.003057 0x7fe754c934c0 DND dnode mgmt is initialized
03/06 07:45:05.004266 0x7fe754c934c0 MND starting to initialize mnode ...
03/06 07:45:05.005208 0x7fe754c934c0 MND sdb write is opened
03/06 07:45:05.005232 0x7fe754c934c0 SDB open sdb wal for restore
03/06 07:45:05.012698 0x7fe754c934c0 MND dnode:1, fqdn:tdengine1 ep:tdengine1:6030 port:6030, do insert action
03/06 07:45:05.012720 0x7fe754c934c0 MND mnode:1, fqdn:tdengine1 ep:tdengine1:6030 port:6030, do insert action
03/06 07:45:05.064211 0x7fe754c934c0 MND db:0.iot_data, all child tables will be dropped from sdb
03/06 07:45:05.082404 0x7fe754c934c0 MND db:0.iot_data, all child tables:907 is dropped from sdb
03/06 07:45:05.082419 0x7fe754c934c0 MND db:0.iot_data, all super tables will be dropped from sdb
03/06 07:45:05.082438 0x7fe754c934c0 MND stable:0.iot_data.a12p8w0hpoc uid:15900201981713867036, all child tables:0 will be dropped from sdb
03/06 07:45:05.082650 0x7fe754c934c0 MND stable:0.iot_data.a12p8w0hpoc, all child tables:0 is dropped from sdb
03/06 07:45:05.082675 0x7fe754c934c0 MND stable:0.iot_data.a1v7ojrtazp uid:15900136999848524953, all child tables:0 will be dropped from sdb
03/06 07:45:05.082886 0x7fe754c934c0 MND stable:0.iot_data.a1v7ojrtazp, all child tables:0 is dropped from sdb
03/06 07:45:05.082897 0x7fe754c934c0 MND stable:0.iot_data.a1elmfcnhsb uid:15900079779240745279, all child tables:0 will be dropped from sdb
03/06 07:45:05.083107 0x7fe754c934c0 MND stable:0.iot_data.a1elmfcnhsb, all child tables:0 is dropped from sdb
03/06 07:45:05.083118 0x7fe754c934c0 MND stable:0.iot_data.a14enkcxpvv uid:621578253617900520, all child tables:0 will be dropped from sdb
03/06 07:45:05.083329 0x7fe754c934c0 MND stable:0.iot_data.a14enkcxpvv, all child tables:0 is dropped from sdb
03/06 07:45:05.083349 0x7fe754c934c0 MND stable:0.iot_data.a19guzksvig uid:15900217506980456683, all child tables:0 will be dropped from sdb
03/06 07:45:05.083563 0x7fe754c934c0 MND stable:0.iot_data.a19guzksvig, all child tables:0 is dropped from sdb
03/06 07:45:05.083574 0x7fe754c934c0 MND stable:0.iot_data.a1brhhgsox3 uid:621248383654335628, all child tables:0 will be dropped from sdb
03/06 07:45:05.083777 0x7fe754c934c0 MND stable:0.iot_data.a1brhhgsox3, all child tables:0 is dropped from sdb
03/06 07:45:05.083789 0x7fe754c934c0 MND stable:0.iot_data.a1npfjobziq uid:621044779521682839, all child tables:0 will be dropped from sdb
03/06 07:45:05.083991 0x7fe754c934c0 MND stable:0.iot_data.a1npfjobziq, all child tables:0 is dropped from sdb
03/06 07:45:05.084002 0x7fe754c934c0 MND stable:0.iot_data.a1leguuznky uid:621141137767292884, all child tables:0 will be dropped from sdb
03/06 07:45:05.084210 0x7fe754c934c0 MND stable:0.iot_data.a1leguuznky, all child tables:0 is dropped from sdb
03/06 07:45:05.084223 0x7fe754c934c0 MND stable:0.iot_data.a17yu1gefgd uid:621183603702789337, all child tables:0 will be dropped from sdb
03/06 07:45:05.084456 0x7fe754c934c0 MND stable:0.iot_data.a17yu1gefgd, all child tables:0 is dropped from sdb
03/06 07:45:05.084470 0x7fe754c934c0 MND stable:0.iot_data.a1owk85flkj uid:15900150932386890914, all child tables:0 will be dropped from sdb
03/06 07:45:05.092919 0x7fe754c934c0 MND stable:0.iot_data.a1owk85flkj, all child tables:0 is dropped from sdb
03/06 07:45:05.092952 0x7fe754c934c0 MND stable:0.iot_data.a1hkkch0lzr uid:621123546755651214, all child tables:0 will be dropped from sdb
03/06 07:45:05.093146 0x7fe754c934c0 MND stable:0.iot_data.a1hkkch0lzr, all child tables:0 is dropped from sdb
03/06 07:45:05.093165 0x7fe754c934c0 MND stable:0.iot_data.a1uzfcmcq3h uid:15900195391908633684, all child tables:0 will be dropped from sdb

03/06 07:45:05.165575 0x7fe754c934c0 MND stable:0.iot_data.a1eehj2kx6d uid:15900148282291405562, all child tables:0 will be dropped from sdb
03/06 07:45:05.165794 0x7fe754c934c0 MND stable:0.iot_data.a1eehj2kx6d, all child tables:0 is dropped from sdb
03/06 07:45:05.165815 0x7fe754c934c0 MND stable:0.iot_data.a1ihoh6u0vr uid:15900100203185972956, all child tables:0 will be dropped from sdb
03/06 07:45:05.166045 0x7fe754c934c0 MND stable:0.iot_data.a1ihoh6u0vr, all child tables:0 is dropped from sdb
03/06 07:45:05.166066 0x7fe754c934c0 MND stable:0.iot_data.a1va42yfjfy uid:621099099248151087, all child tables:0 will be dropped from sdb
03/06 07:45:05.166275 0x7fe754c934c0 MND stable:0.iot_data.a1va42yfjfy, all child tables:0 is dropped from sdb
03/06 07:45:05.166295 0x7fe754c934c0 MND db:0.iot_data, all super tables:243 is dropped from sdb
03/06 07:45:05.166300 0x7fe754c934c0 MND db:0.iot_data, all vgroups will be dropped from sdb
03/06 07:45:05.166330 0x7fe754c934c0 MND db:0.iot_data, all vgroups:1 is dropped from sdb
03/06 07:45:05.191355 0x7fe754c934c0 MND stable:0.iot_data.a1xvhme728p uid:15924110400434812512, all child tables:0 will be dropped from sdb
03/06 07:45:05.191854 0x7fe754c934c0 MND stable:0.iot_data.a1xvhme728p, all child tables:0 is dropped from sdb
03/06 07:45:05.196002 0x7fe754c934c0 MND stable:0.iot_data.a1e15hm9yes uid:15917394504760726910, all child tables:1 will be dropped from sdb
03/06 07:45:05.196502 0x7fe754c934c0 MND stable:0.iot_data.a1e15hm9yes, all child tables:1 is dropped from sdb
03/06 07:45:05.196574 0x7fe754c934c0 MND stable:0.iot_data.a1ymkdcrcz3 uid:15917407961396583857, all child tables:1 will be dropped from sdb
03/06 07:45:05.196961 0x7fe754c934c0 MND stable:0.iot_data.a1ymkdcrcz3, all child tables:1 is dropped from sdb

03/06 07:45:05.222778 0x7fe754c934c0 SDB ERROR table:ctables, failed to restore insert record:0.iot_data.a1hsrzazu85_zmq8czparaokl2ctzi7q000000 from source(2), ver:2951 too large, **sdb ver:2571**
03/06 07:45:05.222783 0x7fe754c934c0 SDB ERROR table:ctables, failed to restore insert record:0.iot_data.a12p8w0hpoc_mhcbjtp1n75apcjtmmqa000000 from source(2), ver:2952 too large, sdb ver:2571
03/06 07:45:05.222789 0x7fe754c934c0 SDB ERROR table:ctables, failed to restore insert record:0.iot_data.a1t67vuutsg_gumfhanvmpj5vlrztr5w000000 from source(2), ver:2953 too large, sdb ver:2571
03/06 07:45:05.222794 0x7fe754c934c0 SDB ERROR table:ctables, failed to restore insert record:0.iot_data.a1if5vuhbpl_ocfwpuqgwv7gyubrypdd000000 from source(2), ver:2954 too large, sdb ver:2571
03/06 07:45:05.222800 0x7fe754c934c0 SDB ERROR table:ctables, failed to restore insert record:0.iot_data.a1jl7axbhty_ojicxazjlb1cx5ork9h3000000 from source(2), ver:2955 too large, sdb ver:2571
03/06 07:45:05.222805 0x7fe754c934c0 SDB ERROR table:ctables, failed to restore insert record:0.iot_data.a1tkqpjadqo_lblakzqa1medanclwdcn000000 from source(2), ver:2956 too large, sdb ver:2571
03/06 07:45:05.222811 0x7fe754c934c0 SDB ERROR table:ctables, failed to restore insert record:0.iot_data.a1ckx9rzvft_jyfb0mhrfjnaxxvbxobp000000 from source(2), ver:2957 too large, sdb ver:2571
03/06 07:45:05.222817 0x7fe754c934c0 SDB ERROR table:ctables, failed to restore insert record:0.iot_data.a1a170armuk_ratrqguldo6epgbuy0nk000000 from source(2), ver:2958 too large, sdb ver:2571
03/06 07:45:05.222822 0x7fe754c934c0 SDB ERROR table:ctables, failed to restore insert record:0.iot_data.a1lrclfozvu_ujdtf1k3sioxszpzrxq4000000 from source(2), ver:2959 too large, sdb ver:2571
03/06 07:45:05.222828 0x7fe754c934c0 SDB ERROR table:ctables, failed to restore insert record:0.iot_data.a1bafkiee9o_sovnns6vqcpd8lora0yd000000 from source(2), ver:2960 too large, sdb ver:2571
03/06 07:45:05.222833 0x7fe754c934c0 SDB ERROR table:ctables, failed to restore insert record:0.iot_data.a1q9s7tr66h_kusddihkpvf7t1rf2xn3000000 from source(2), ver:2961 too large, sdb ver:2571
03/06 07:45:05.222901 0x7fe754c934c0 MND cluster id is set to a1f4070b-d082-4a40-8c18-5a60575f2c29
03/06 07:45:05.222918 0x7fe754c934c0 MND update mnodes epSet, numOfEps:1 
03/06 07:45:05.222936 0x7fe754c934c0 MND mnode:1, ep:tdengine1:6030 master
03/06 07:45:05.251482 0x7fe754c934c0 SDB sdb is restored, ver:2571 totalRows:1336 numOfTables:9
03/06 07:45:05.251513 0x7fe754c934c0 MND dnode:1 set access:0 to 0
03/06 07:45:05.251668 0x7fe754c934c0 MND mnode is initialized successfully
03/06 07:45:05.251688 0x7fe754c934c0 SDB work as mnode, replica:1
03/06 07:45:05.251692 0x7fe754c934c0 SDB mnode:1, tdengine1:6040
03/06 07:45:05.251765 0x7fe754c934c0 SDB mnode role changed from master to master
03/06 07:45:05.251771 0x7fe754c934c0 SDB update mnodes sync roles, total:1
03/06 07:45:05.251775 0x7fe754c934c0 SDB mnode:1, role:master
03/06 07:45:05.251781 0x7fe754c934c0 MND cluster id is set to a1f4070b-d082-4a40-8c18-5a60575f2c29
03/06 07:45:05.251785 0x7fe754c934c0 MND update mnodes epSet, numOfEps:1

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/

如果还有具体的使用问题，可以加微信：a15652223354
