### ISSUE TITLE
systemctl start taosd ERROR

### ISSUE THREAD

**Issue by andyli029** [taosdata/TDengine#20282]
**Bug Description**
Following [README.md](https://github.com/taosdata/TDengine#readme), do the cmd about
`https://github.com/taosdata/TDengine#on-linux-platform-1`

```
$ service taosd status
Redirecting to /bin/systemctl status taosd.service
● taosd.service
   Loaded: error (Reason: Invalid argument)
   Active: inactive (dead)
taosd.service lacks both ExecStart= and ExecStop= setting. Refusing.
```
**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.9]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. ver-3.0.2.6]

**Additional Context**

**Comment by yu285** [comment]
input "taosd" command directly . and show us the output ,please .
