### ISSUE TITLE
order by query not correct

### ISSUE THREAD

**Issue by jack2949560190** [taosdata/TDengine#20281]
预期输出一条，实际输出两条
<img width="949" alt="Snipaste_2023-03-06_17-35-03" src="https://user-images.githubusercontent.com/106313759/223071913-753cd80d-bacc-47af-8fd2-2a766860e1f2.png">

**Comment by yu285** [comment]
请问版本号是？

**Comment by feici02** [comment]
This issue has been fixed in the latest release [v3.0.3.0](https://github.com/taosdata/TDengine/releases/tag/ver-3.0.3.0).
