### ISSUE TITLE
stream's name issue 

### ISSUE THREAD

**Issue by xiahejun** [taosdata/TDengine#20289]
版本：3.0.2.5 

场景：因为存在冷热数据场景，初步设计为将最近一个月数据存入到实时库中，然后通过流计算实时将数据同步到历史库（历史库保存全部数据），现在同步后历史库的字表名称为自动生成，但是实时库中为测点名称，这个字表名称对我们来说具体意义。

问题：流计算过程中，能否支持字表名称自定义？如果支持应该怎么设置，目前配置了smlChildTableName 但是感觉不生效，盼回复。

**Comment by yu285** [comment]
需要配置在客户端，另外流计算经过多轮重构已经比较稳定了，建议使用最新的3.3.0.3
