### ISSUE TITLE
安装之后使用taos命令

### ISSUE THREAD

**Issue by wenguochen** [taosdata/TDengine#203]
提示：failed to get charset, please set the valid charset in config file

**Comment by wenguochen** [comment]
系统是：Linux chuangxin 4.4.0-117-generic #141-Ubuntu

**Comment by hzcheng** [comment]
您可以在/etc/taos/taos.cfg中加上选项
```
charset  UTF-8
```
来修复这个问题，或者修改您的LC_CTYPE。
export LC_CTYPE='en_US.UTF-8'

**Comment by wenguochen** [comment]
@hzcheng 
非常感谢，按照您的解决方案，问题已经解决
