### ISSUE TITLE
jdbcurl user info not work, it was always set to null

### ISSUE THREAD

**Issue by StardustXiaoT** [taosdata/TDengine#2030]
follow  with document 

Class.forName("com.taosdata.jdbc.TSDBDriver");
String jdbcUrl = "jdbc:TAOS://127.0.0.1:6030/log?user=root&password=taosdata";
Connection conn = DriverManager.getConnection(jdbcUrl);

It turns out that info fetched inside jdbcUrl , user was not interpreted correctly. It was always set to null.In this case, connection was still successful. However, when I use connProps.setProperty to set user info , it has no issue at all.

 - OS: server ubuntu18.04 
 - TDengine Version [1.6.5.9]  linux server and windows client

**Comment by Aries-Lee1991** [comment]
It's not a bug. The server and the client were not on the same host, you couldn't use this host_ip: 127.0.0.1.

**Comment by StardustXiaoT** [comment]
@Aries-Lee1991 Hi, my point is the “user=root ” in jdbc url was not  parsed  correctly. Whatever value I set, it was set to null. TDengine will use default root.

**Comment by sangshuduo** [comment]
Please try the latest official release 2.0.3.1 and JDBC driver 2.0.4. Thanks.
