### ISSUE TITLE
Can not create STable after create database

### ISSUE THREAD

**Issue by MikyChow** [taosdata/TDengine#20319]
**Bug Description**
根据官网文档创建数据库后无法创建超级表
1.  CREATE DATABASE power KEEP 365 DURATION 10 BUFFER 16 WAL_LEVEL 1;
2. USE power;
3. CREATE STABLE meters (ts timestamp, current float, voltage int, phase float) TAGS (location binary(64), groupId int);
![image](https://user-images.githubusercontent.com/5389478/223605119-8ce11c6a-3f82-4d2b-ba29-f37e539b86c4.png)
提示无效的消息
DB error: Invalid message (0.002353s)
**To Reproduce**
1. 查看服务器版本: 3.0.2.6
2. 服务端日志没有输出，无法知道具体问题

即使发生错误也希望能提示清晰，目前错误无法判断具体问题

**Comment by feici02** [comment]
Hi, 如截图所示，我并没有复现这个问题：
![image](https://user-images.githubusercontent.com/5568663/223610841-8a090bcf-43fd-431c-95d6-a78e1f9f6aa1.png)
[issue-20319.sql.txt](https://github.com/taosdata/TDengine/files/10916903/issue-20319.sql.txt)
可以提供平台信息吗？

**Comment by MikyChow** [comment]
使用的是docker版本的taosdata，完整命令如下:
![image](https://user-images.githubusercontent.com/5389478/223666247-56431335-c477-4668-9a68-db8be2b910fa.png)

1. docker run -d -p 6030:6030 -p 6041:6041 -p 6043-6049:6043-6049 -p 6043-6049:6043-6049/udp tdengine/tdengine
2. taos
3. CREATE DATABASE power KEEP 365 DURATION 10 BUFFER 16 WAL_LEVEL 1;
4. USE power;
5. CREATE STABLE meters (ts timestamp, current float, voltage int, phase float) TAGS (location binary(64), groupId int);

**Comment by MikyChow** [comment]
taso 版本： version: 3.0.3.0
server 版本: 3.0.2.6
操作系统: mac os 13.1 (22C65)

**Comment by feici02** [comment]
这是一个兼容性问题，我们只保证前3位版本号相同时，客户端与服务端的兼容性；
请将服务端升级至3.0.3.0.

**Comment by MikyChow** [comment]
好的，谢谢。 我再试试看
