### ISSUE TITLE
TDengine does not work with docker swarm mode

### ISSUE THREAD

**Issue by StardustXiaoT** [taosdata/TDengine#2031]
When I run TDengine with docker run, it has no issue. It somehow does not work  with  docker compose in docker swarm mode.

Here is  my docker compose file:

version: '3.2'
services:
  taos:
    image: tdengine/tdengine:1.6.5.9
    volumes:
      - ./data:/var/lib/taos
      - ./log:/var/log/taos
      - ./config:/etc/taos
    ports:
      - "26020:6020"
      - "26020:6020/udp"
      - "26030-26050:6030-6050"
      - "26030-26050:6030-6050/udp"
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

 - OS: ubuntu18.04 
 - docker: 19.03
 - TDengine Version [1.6.5.9] Linux Server and Windows Client.

When I exec into container, I cant connect to server with taos command. 
DB error: failed to connect to server

**Comment by Shawshank-Smile** [comment]
Is the problem solved?

**Comment by chinajuanbob** [comment]
For your reference, I tried with no ports exports, and connect taos using the container's IP, not the service's IP. It works.

However, ports exports are indeed needed in some cases.
