### ISSUE TITLE
DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:1

### ISSUE THREAD

**Issue by helloworldwyy** [taosdata/TDengine#20334]
输入taosd后提示 

**03/08 15:16:53.359678 03458135 DND file:/var/lib/taos//qnode/qnode.json not exist
03/08 15:16:53.359693 03458135 DND file:/var/lib/taos//snode/snode.json not exist
03/08 15:16:54.359982 03458135 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:1
03/08 15:16:55.360136 03458135 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:2
....**

qnode.json和snode.json是什么

**Comment by yu285** [comment]
并无影响，这代表你已经启动过数据库了。
