### ISSUE TITLE
client connected but got error "Unable to establish connection"

### ISSUE THREAD

**Issue by DianaZhao** [taosdata/TDengine#20356]
**Bug Description**

**To Reproduce**
1. I have run a piece of c code inserted some records, that code is modified from one of taos sample.
2. Then I open taos client, select that db, run select * from the table inserted. and got that error. but at the same time I can desc the structure of that table.

my insert code as follows:

#include <stdio.h>
#include <inttypes.h>
#include <string.h>
#include <time.h>
#include <taos.h>

typedef int16_t VarDataLenT;

#define TSDB_NCHAR_SIZE sizeof(int32_t)
#define VARSTR_HEADER_SIZE sizeof(VarDataLenT)

#define GET_FLOAT_VAL(x) (*(float *)(x))
#define GET_DOUBLE_VAL(x) (*(double *)(x))

#define varDataLen(v) ((VarDataLenT *)(v))[0]

int printRow(char *str, TAOS_ROW row, TAOS_FIELD *fields, int numFields) {
    int len = 0;
    char split = ' ';

    for (int i = 0; i < numFields; ++i) {
        if (i > 0) {
            str[len++] = split;
        }

        if (row[i] == NULL) {
            len += sprintf(str + len, "%s", "NULL");
            continue;
        }

        switch (fields[i].type) {
            case TSDB_DATA_TYPE_TINYINT:
                len += sprintf(str + len, "%d", *((int8_t *) row[i]));
                break;

            case TSDB_DATA_TYPE_UTINYINT:
                len += sprintf(str + len, "%u", *((uint8_t *) row[i]));
                break;

            case TSDB_DATA_TYPE_SMALLINT:
                len += sprintf(str + len, "%d", *((int16_t *) row[i]));
                break;

            case TSDB_DATA_TYPE_USMALLINT:
                len += sprintf(str + len, "%u", *((uint16_t *) row[i]));
                break;

            case TSDB_DATA_TYPE_INT:
                len += sprintf(str + len, "%d", *((int32_t *) row[i]));
                break;

            case TSDB_DATA_TYPE_UINT:
                len += sprintf(str + len, "%u", *((uint32_t *) row[i]));
                break;

            case TSDB_DATA_TYPE_BIGINT:
                len += sprintf(str + len, "%ld", *((int64_t *) row[i]));
                break;

            case TSDB_DATA_TYPE_UBIGINT:
                len += sprintf(str + len, "%llu", *((uint64_t *) row[i]));
                break;

            case TSDB_DATA_TYPE_FLOAT: {
                float fv = 0;
                fv = GET_FLOAT_VAL(row[i]);
                len += sprintf(str + len, "%f", fv);
            }
                break;

            case TSDB_DATA_TYPE_DOUBLE: {
                double dv = 0;
                dv = GET_DOUBLE_VAL(row[i]);
                len += sprintf(str + len, "%lf", dv);
            }
                break;

            case TSDB_DATA_TYPE_BINARY:
            case TSDB_DATA_TYPE_NCHAR: {
                int32_t charLen = varDataLen((char *) row[i] - VARSTR_HEADER_SIZE);
                memcpy(str + len, row[i], charLen);
                len += charLen;
            }
                break;

            case TSDB_DATA_TYPE_TIMESTAMP:
                len += sprintf(str + len, "%ld", *((int64_t *) row[i]));
                break;

            case TSDB_DATA_TYPE_BOOL:
                len += sprintf(str + len, "%d", *((int8_t *) row[i]));
            default:
                break;
        }
    }

    return len;
}

/**
 * @brief print column name and values of each row
 *
 * @param res
 * @return int
 */
static int printResult(TAOS_RES *res) {
    int numFields = taos_num_fields(res);
    TAOS_FIELD *fields = taos_fetch_fields(res);
    char header[256] = {0};
    int len = 0;
    for (int i = 0; i < numFields; ++i) {
        len += sprintf(header + len, "%s ", fields[i].name);
    }
    puts(header);

    TAOS_ROW row = NULL;
    while ((row = taos_fetch_row(res))) {
        char temp[256] = {0};
        printRow(temp, row, fields, numFields);
        puts(temp);
    }
}

int insertData(TAOS *taos) {
    struct {
        int64_t ts;
        int8_t ti;
        int16_t si;
        int32_t i;
        int64_t bi;
        float f;
        double d;
        char b[80];
    } v = {0};

    int32_t boolLen = sizeof(int8_t);
    int32_t sintLen = sizeof(int16_t);
    int32_t intLen = sizeof(int32_t);
    int32_t bintLen = sizeof(int64_t);
    int32_t floatLen = sizeof(float);
    int32_t doubleLen = sizeof(double);
    int32_t binLen = sizeof(v.b);
    int32_t ncharLen = 30;

    TAOS_STMT *stmt = taos_stmt_init(taos);
    TAOS_MULTI_BIND params[10];
    params[0].buffer_type = TSDB_DATA_TYPE_TIMESTAMP;
    params[0].buffer_length = sizeof(v.ts);
    params[0].buffer = &v.ts;
    params[0].length = &bintLen;
    params[0].is_null = NULL;
    params[0].num = 1;

    params[1].buffer_type = TSDB_DATA_TYPE_TINYINT;
    params[1].buffer_length = sizeof(v.ti);
    params[1].buffer = &v.ti;
    params[1].length = &boolLen;
    params[1].is_null = NULL;
    params[1].num = 1;

    params[2].buffer_type = TSDB_DATA_TYPE_SMALLINT;
    params[2].buffer_length = sizeof(v.si);
    params[2].buffer = &v.si;
    params[2].length = &sintLen;
    params[2].is_null = NULL;
    params[2].num = 1;

    params[3].buffer_type = TSDB_DATA_TYPE_INT;
    params[3].buffer_length = sizeof(v.i);
    params[3].buffer = &v.i;
    params[3].length = &intLen;
    params[3].is_null = NULL;
    params[3].num = 1;

    params[4].buffer_type = TSDB_DATA_TYPE_BIGINT;
    params[4].buffer_length = sizeof(v.bi);
    params[4].buffer = &v.bi;
    params[4].length = &bintLen;
    params[4].is_null = NULL;
    params[4].num = 1;

    params[5].buffer_type = TSDB_DATA_TYPE_FLOAT;
    params[5].buffer_length = sizeof(v.f);
    params[5].buffer = &v.f;
    params[5].length = &floatLen;
    params[5].is_null = NULL;
    params[5].num = 1;

    params[6].buffer_type = TSDB_DATA_TYPE_DOUBLE;
    params[6].buffer_length = sizeof(v.d);
    params[6].buffer = &v.d;
    params[6].length = &doubleLen;
    params[6].is_null = NULL;
    params[6].num = 1;

    params[7].buffer_type = TSDB_DATA_TYPE_BINARY;
    params[7].buffer_length = sizeof(v.b);
    params[7].buffer = &v.b;
    params[7].length = &binLen;
    params[7].is_null = NULL;
    params[7].num = 1;

    char is_null = 1;

    const char *sql = "insert into tbl_test values(?,?,?,?,?,?,?,?)";
    int code = taos_stmt_prepare(stmt, sql, 0);
    if (code != 0) {
        printf("failed to execute taos_stmt_prepare. code:0x%x\n", code);
    }
    int count;
    int ret;
    ret = taos_stmt_num_params(stmt, &count);
    printf("parameter count:  %d , ret: %d\n", count, ret);
    ret = taos_stmt_get_col_fields(stmt, &count, NULL);
    printf("field count:  %d , ret: %d\n", count, ret);
    time_t sec = time(NULL);
    v.ts = sec * 1000;
    printf("time:  %lld \n", v.ts);
    for (int i = 0; i < 10; ++i) {
        v.ts += 1;
        for (int j = 1; j < 10; ++j) {
            params[j].is_null = ((i == j) ? &is_null : 0);
        }
        v.ti = (int8_t) i % 2;
        v.si = (int16_t) (i * 2);
        v.i = (int32_t) (i * 4);
        v.bi = (int64_t) (i * 8);
        v.f = (float) (i * 40);
        v.d = (double) (i * 80);
        for (int j = 0; j < sizeof(v.b); ++j) {
            v.b[j] = (char) (i + '0');
        }

        taos_stmt_bind_param(stmt, params);
        taos_stmt_add_batch(stmt);
    }
    if (taos_stmt_execute(stmt) != 0) {
        printf("failed to execute insert statement.\n");
        return (-1);
    }
    ret = taos_stmt_num_params(stmt, &count);
    printf("parameter count:  %d , ret: %d\n", count, ret);
    ret = taos_stmt_get_col_fields(stmt, &count, NULL);
    printf("field count:  %d , ret: %d\n", count, ret);
    taos_stmt_close(stmt);

    // query the records
    stmt = taos_stmt_init(taos);
    taos_stmt_prepare(stmt, "SELECT * FROM tbl_test WHERE ti > ? AND si < ?", 0);
    v.ti = 5;
    v.si = 15;
    taos_stmt_bind_param(stmt, params + 2);
    if (taos_stmt_execute(stmt) != 0) {
        printf("failed to execute select statement.\n");
        return (-1);
    }

    TAOS_RES *result = taos_stmt_use_result(stmt);

    TAOS_ROW row;
    int rows = 0;
    int num_fields = taos_num_fields(result);
    TAOS_FIELD *fields = taos_fetch_fields(result);

    // fetch the records row by row
    while ((row = taos_fetch_row(result))) {
        char temp[256] = {0};
        rows++;
        taos_print_row(temp, row, fields, num_fields);
        printf("%s\n", temp);
    }
    if (rows == 2) {
        printf("two rows are fetched as expectation\n");
    } else {
        printf("expect two rows, but %d rows are fetched\n", rows);
    }

    taos_free_result(result);
    taos_stmt_close(stmt);
}

int main(int argc, char *argv[]) {
    //HMODULE m = LoadLibrary("D:\\workspaces\\VSProjects\\taos_odbc_driver\\debug\\taos_odbc_driver\\taos_odbc_driver.dll");
    //if (m != NULL) {

    //}
    const char *ip = "192.168.137.21";
    TAOS *taos = taos_connect(ip, NULL, NULL, "odbc_test", 6030);
    if (!taos) {
        printf("error connect to %s\n", ip);
        return -1;
    }
    printf("success connect to %s, %lld\n", ip, taos);
    insertData(taos);
    const char *qry = "show databases;";
    TAOS_RES *res = taos_query(taos, qry);
    if (taos_errno(res) == 0) {
        printResult(res);
    } else {
        printf("execute error number: %d\n", taos_errno(res));
    }
    taos_close(taos);
    taos_cleanup();
    return 0;
}

**Screenshots**
![dbe_uc](https://user-images.githubusercontent.com/961024/223862739-3dd092e7-fd33-4280-aa2f-085d6f826a3e.PNG)

**Environment (please complete the following information):**
 - OS: Debian 9
 - Memory, CPU, current Disk Space
 - TDengine Version 3.0

**Comment by yu285** [comment]
看起来是服务端crash 了，3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
