### ISSUE TITLE
求linux后台自动运行taosd服务的方法！

### ISSUE THREAD

**Issue by wogoshu** [taosdata/TDengine#2036]
linux系统版本 CentOS release 6.6 (Final)，源码安装TDengine，启动服务输入命令taosd，会提示服务启动成功，可以进行查询操作，但是如果关掉刚才输入taosd命令的窗口后就不能进行查询操作了，问下有后台启动服务的方法嘛，后台自动运行服务的方法？即使关掉taosd命令的对话框也不影响查询的那种，谢谢！

**Comment by POPIWEN0209** [comment]
这个问题怎么解决了呀，我也遇到这个问题

**Comment by POPIWEN0209** [comment]
Linux启动服务器怎么自动启动td数据库

**Comment by sangshuduo** [comment]
systemctl start taosd
