### ISSUE TITLE
2.6.x版本应该用哪个版本的taosdump

### ISSUE THREAD

**Issue by elysian-gc** [taosdata/TDengine#20369]
**Bug Description**
taosdump error

**To Reproduce**
1. run tdengine2.6 with docker
2. taosBenchmark
3. download taos-tools 2.2.6

**Expected Behavior**
dump sussessed

**Screenshots**
![image](https://user-images.githubusercontent.com/44466800/223976930-f63ccdcd-9dd6-4a93-a440-fa7644356f82.png)

**Environment (please complete the following information):**
 - OS: 5.10.167-147.601.amzn2.aarch64
 - Memory, CPU, current Disk Space
 - TDengine Version 2.6.0.34

**Additional Context**

**Comment by elysian-gc** [comment]
其他形式的包可以正常dump

**Comment by sangshuduo** [comment]
> 其他形式的包可以正常dump

https://www.taosdata.com/all-downloads 这里下载最新版 taos-tools
