### ISSUE TITLE
the issue regarding to taoskeeper

### ISSUE THREAD

**Issue by wupeng1234** [taosdata/TDengine#20370]
您好，关于集群监控，我看咱们的官网文档还是有些疑问：
1. 我目前是集群三台机器都开启了 monitor，同时运行了 taosAdapter，但只有主节点开启了 taosKeeper；
2. taosKeeper 更改的配置如下：
[taosAdapter]
address = ["node193.taos.com:6041", "node194.taos.com:6041", "node195.taos.com:6041"]
3. Grafana 也安装上了，但是在仪表 -> Dnode Usage[] 哪一项里面只有 node193.taos.com:6030 这一项可选。那其他两台怎么看资源使用情况呢？

**Comment by wupeng1234** [comment]
在仪表盘选择fqdn那里，只有“ALL”、“node193.taos.com:6030”两个可选

**Comment by wupeng1234** [comment]
我按照第一种方案操作不行
我查看以下咱们的 Grafana 的数据源插件，查询 fqdn 的语句是：select first_ep from $database.cluster_info group by cluster_id, first_ep;
其中 $database 对应的是 log 库，而 log.cluster_info 里面的 first_ep 都是 node193.taos.com，因为我启动进群的时候，指定另外两台的first_ep 就是  node193.taos.com，感觉设计好像就只能监控  node193.taos.com 的资源使用情况

**Comment by wupeng1234** [comment]
我确认了一下，log 库下面的 dnodes_info 表是有 node194、node195 的数据的，但就是 cluster_info 表下面查询不到 node194、node195，故而导致监控页面的 fqdn 变量取不到 node194、node195 这两个节点

**Comment by wupeng1234** [comment]
我确认了一下，log 库下面的 dnodes_info 表是有 node194、node195 的数据的，但就是 cluster_info 表下面查询不到 node194、node195，故而导致监控页面的 fqdn 变量取不到 node194、node195 这两个节点

**Comment by sunpe** [comment]
cluster_info 表只会记录 leader 节点。 您目前的问题时 dnodes dashboard 只展示了一个节点，和cluster_info 数据无关

**Comment by yu285** [comment]
hi 可以加微信a15652223354, 我们远程排查一下吧

**Comment by wupeng1234** [comment]
已经确定是 TDinsight.sh 脚本的版本问题，感谢大佬帮忙解答！
