### ISSUE TITLE
connection issue

### ISSUE THREAD

**Issue by qq876633655** [taosdata/TDengine#20380]
1. 使用容器安装完成后
2. 安装Linux版本的连接器
3. 执行bash install.sh全部回车
4. 重启电脑
5. 在linux中执行netstat anp | grep 6030发现端口已经被taosd监听占用，不能打开之前设置好端口的容器
6. 在上述容器未打开的情况下尝试执行了一下taos，发现可以直接连接到数据库
7. 产生疑问，不打开容器启动服务就可以使用taos连接数据库吗

**Comment by sangshuduo** [comment]
宿主机装过 taosd 吧？ ps ax|grep taosd 看看

**Comment by qq876633655** [comment]
ps ax | grep taosd
  1661 ?        Ssl    0:23 /usr/bin/taosd
  5702 pts/0    S+     0:00 grep --color=auto taosd

**Comment by qq876633655** [comment]
因为是个虚拟机Linux，我就先按照docker run -d -p 6030:6030 -p 6041:6041 -p 6043-6049:6043-6049 -p 6043-6049:6043-6049/udp tdengine/tdengine安装，然后解压TDengine-server-3.0.3.0-Linux-x64.tar.gz安装。然后重启了一下虚拟机之后，容器本身是没有开机自启的，所以想开启容器，然后在linux上执行taos。启动容器的时候发现被taosd占用了，就没起来。但是执行taos发现也能连到数据库。就想问问这个时候taos连接的是哪的数据库？（毕竟容器没起来）

**Comment by sangshuduo** [comment]
TDengine-server-3.0.3.0-Linux-x64.tar.gz 自带 taosd 在宿主机启动了。你可以 rmtaos 删除后装一个 TDengine-client 安装包宿主机就不会有 taosd

**Comment by qq876633655** [comment]
WARING: Create taoslog failed. configDir=/etc/taos/
Welcome to the TDengine Command Line Interface, Client Version:3.0.3.0
Copyright (c) 2022 by TDengine, all rights reserved.

   ******************************  Tab Completion  **********************************
   *   The TDengine CLI supports tab completion for a variety of items,             *
  *   including database names, table names, function names and keywords.              *
  *   The full list of shortcut keys is as follows:                                    *
  *    [ TAB ]        ......  complete the current word                                *
  *                   ......  if used on a blank line, display all supported commands  *
  *    [ Ctrl + A ]   ......  move cursor to the st[A]rt of the line                   *
  *    [ Ctrl + E ]   ......  move cursor to the [E]nd of the line                     *
  *    [ Ctrl + W ]   ......  move cursor to the middle of the line                    *
  *    [ Ctrl + L ]   ......  clear the entire screen                                  *
  *    [ Ctrl + K ]   ......  clear the screen after the cursor                        *
  *    [ Ctrl + U ]   ......  clear the screen before the cursor                       *
  **************************************************************************************


重装成client，然后现在有个新的问题，taos执行后卡在上述界面没有进入命令行，可能会是什么原因

**Comment by sangshuduo** [comment]
> WARING: Create taoslog failed. configDir=/etc/taos/ Welcome to the TDengine Command Line Interface, Client Version:3.0.3.0 Copyright (c) 2022 by TDengine, all rights reserved.
> 
> ****************************** Tab Completion **********************************
> 
>     * The TDengine CLI supports tab completion for a variety of items,             *
> 
>     * including database names, table names, function names and keywords.              *
> 
>     * The full list of shortcut keys is as follows:                                    *
> 
>     * [ TAB ]        ......  complete the current word                                *
> 
>     * ```
>                     ......  if used on a blank line, display all supported commands  *
>       ```
> 
>     * [ Ctrl + A ]   ......  move cursor to the st[A]rt of the line                   *
> 
>     * [ Ctrl + E ]   ......  move cursor to the [E]nd of the line                     *
> 
>     * [ Ctrl + W ]   ......  move cursor to the middle of the line                    *
> 
>     * [ Ctrl + L ]   ......  clear the entire screen                                  *
> 
>     * [ Ctrl + K ]   ......  clear the screen after the cursor                        *
> 
>     * [ Ctrl + U ]   ......  clear the screen before the cursor                       *
> 
> 
> 重装成client，然后现在有个新的问题，taos执行后卡在上述界面没有进入命令行，可能会是什么原因

按照官网文档 https://docs.taosdata.com/get-started/docker/ 方法也不行吗？

**Comment by qq876633655** [comment]
进入容器后执行taos是正常的，但是我理解client连接器不是为了支持不进入容器，在宿主机中连接容器端口用的吗。现在的情况是已经安装了client，然后在容器外执行taos没有出现命令行界面，我不确定卡在这种状态是什么原因，想咨询下
