### ISSUE TITLE
3.0.3.0 null value made client crash

### ISSUE THREAD

**Issue by qiks626** [taosdata/TDengine#20392]
1、stream 遇到null值时会导致taos崩溃且无法重新启动
2、where no in (null) 会导致客户端以及JVM崩溃
3、where no=null 会导致客户端以及JVM崩溃
taos version 3.0.3.0
taos client version 3.0.3.0
taos-jdbcdriver version 3.1.0
alibaba-druid version 1.2.16
springboot version 2.6.3

**Comment by yu285** [comment]
请问可以远程看下么，可以加微信 a15652223354

**Comment by jack2949560190** [comment]
什么原因？

**Comment by superzhengcn** [comment]
> 请问可以远程看下么，可以加微信 a15652223354

遇到了同样的问题，taos version 3.0.3.0 windows springboot +mybatisPlus查询不等于Null的值时，直接崩溃。还有就是如何查询字段值为NULL的数据，我在命令行使用select * from tabelA where age = null;select * from tabelA where age != null; select * from tabelA where age <> null;返回影响行数均为0

**Comment by jack2949560190** [comment]
null加个单引号试试


莫语
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taosdata/TDengine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月23日(星期四) 晚上8:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [taosdata/TDengine] 3.0.3.0 null value made client crash (Issue #20392)





  
请问可以远程看下么，可以加微信 a15652223354
  
遇到了同样的问题，taos version 3.0.3.0 windows springboot +mybatisPlus查询不等于Null的值时，直接崩溃。还有就是如何查询字段值为NULL的数据，我在命令行使用select * from tabelA where age = null;select * from tabelA where age != null; select * from tabelA where age <&gt; null;返回影响行数均为0
