### ISSUE TITLE
REST API 返回结果和官方文档不一致

### ISSUE THREAD

**Issue by longcf6666** [taosdata/TDengine#20393]
![image](https://user-images.githubusercontent.com/98379149/224251357-6f1c987e-8ca8-4dcc-bf90-8102ec454d75.png)
![image](https://user-images.githubusercontent.com/98379149/224251668-94416cee-92c4-4ecf-a5a8-af741c7b28cb.png)
返回结果没有status参数

**Comment by huskar-t** [comment]
@longcf6666 文档错误已修改
