### ISSUE TITLE
INSERT INTO ... USING ... TAGS, TDengine Error: failed to connect server.

### ISSUE THREAD

**Issue by cuihanbing** [taosdata/TDengine#2040]
测试写数据时自动建子表功能时，执行以下代码出现bug
` 

 
   statement = connection.createStatement();

            String SQL="INSERT INTO edb.edb_table USING edb.edb_stable TAGS ("+deviceId+" , "+parameterId+" ) VALUES ("+"now , "+data+")";
            String SQL1 = "INSERT INTO edb.edb_data VALUES (now , 6666)";

            System.out.println(SQL1);
            int count1 = statement.executeUpdate(SQL1);
            System.out.println("执行1.."+count1);

            String SQL3="INSERT INTO edb.edb_data USING edb.edb_stable TAGS ("+deviceId+" , "+parameterId+" ) VALUES ("+"now , "+data+") ";

            System.out.println(SQL3);
            int count3 = statement.executeUpdate(SQL3);
            System.out.println("执行2.."+count3);

            connection.close(); // put back to conneciton pool`

执行以上代码运行正常

`            
statement = connection.createStatement();
//
//            String SQL="INSERT INTO edb.edb_table USING edb.edb_stable TAGS ("+deviceId+" , "+parameterId+" ) VALUES ("+"now , "+data+")";
//            String SQL1 = "INSERT INTO edb.edb_data VALUES (now , 6666)";
//
//            System.out.println(SQL1);
//            int count1 = statement.executeUpdate(SQL1);
//            System.out.println("执行1.."+count1);

            String SQL3="INSERT INTO edb.edb_data USING edb.edb_stable TAGS ("+deviceId+" , "+parameterId+" ) VALUES ("+"now , "+data+") ";

            System.out.println(SQL3);
            int count3 = statement.executeUpdate(SQL3);
            System.out.println("执行2.."+count3);

            connection.close(); // put back to conneciton pool`

以上代码执行报错
`

INSERT INTO edb.edb_data USING edb.edb_stable TAGS (14 , 12 ) VALUES (now , 9556) 
java.sql.SQLException: TDengine Error: failed to connect to server
	at com.taosdata.jdbc.TSDBJNIConnector.executeQuery(TSDBJNIConnector.java:131)
	at com.taosdata.jdbc.TSDBStatement.executeUpdate(TSDBStatement.java:69)
	at com.alibaba.druid.pool.DruidPooledStatement.executeUpdate(DruidPooledStatement.java:325)
	at ClientTest.save(ClientTest.java:66)
	at ClientTest.main(ClientTest.java:15)
`

在shell执行
INSERT INTO edb.edb_data USING edb.edb_stable TAGS (14 , 12 ) VALUES (now , 9556) 
正常运行

**Comment by cuihanbing** [comment]
继续测试，在本地虚拟机搭建taosd服务正常使用；换一台电脑连接公有云也可以正常运行。

**Comment by Shawshank-Smile** [comment]
1.6.5.9 it is very stable, please feel free to enjoy it.
