### ISSUE TITLE
please give me a real mac client

### ISSUE THREAD

**Issue by limjiregister** [taosdata/TDengine#2041]
客户端安装
在Mac操作系统下，TDengine提供64位的Mac客户端(2月10日起提供下载)，客户端安装程序为.tar.gz文件，解压并运行其中的install_client.sh后即可完成安装，安装路径为/usr/loca/taos。客户端目录结构如下：

https://www.taosdata.com/cn/documentation/connector/#Go-Connector

明明说可以下载了。为何还是不能在mac进行go运行呢？

不是这里的么？
TDengine Linux Client
TDengine-client-1.6.5.9-Linux-x64.tar.gz
TDengine-client-1.6.5.8-Linux-x64.tar.gz
TDengine-client-1.6.5.7-Linux-x64.tar.gz
TDengine-client-1.6.5.6-Linux-x64.tar.gz
TDengine-client-1.6.5.5-Linux-x64.tar.gz
TDengine-client-edge-1.6.5.4-Linux-x64.tar.gz
TDengine-client-1.6.4.5.tar.gz
TDengine-client-1.6.4.4.tar.gz

# github.com/taosdata/driver-go/taosSql
ld: warning: ignoring file /usr/local/lib/libtaos.so, file was built for unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): /usr/local/lib/libtaos.so
Undefined symbols for architecture x86_64:

**Comment by Shawshank-Smile** [comment]
Do not use MAC client, there are bugs。
