### ISSUE TITLE
Hope TDengine can provide some environmental depency information for getting started

### ISSUE THREAD

**Issue by limjiregister** [taosdata/TDengine#2042]
玩了一天，在linux上瞎折腾还是okay的。

但是，如果要搞开发，着手去使用，各种环境依赖的缺失，开发成本不是一般的高。go语言的，在mac系统上不行。在window上还要编译一个什么dll。其他语言就懒得试了。略略吐槽一下，不好意思。

**Comment by Shawshank-Smile** [comment]
I don't think so...

**Comment by sangshuduo** [comment]
请参考官网文档
