### ISSUE TITLE
the issue when connecting to TDengine server  

### ISSUE THREAD

**Issue by luchaonan8** [taosdata/TDengine#20435]
**Bug Description**
本地无法通过vpn连接到tdengine3.0.3.0服务器，下载的taos client打不开

**To Reproduce**
1. 打开vpn
2. 下载[TDengine-client-3.0.3.0-Linux-x64.tar.gz (10.6 M)](https://docs.taosdata.com/get-started/package/#!)并安装
3. 使用taos打开taos客户端，提示：failed to connect to server, reason: Sync not leader

**Expected Behavior**
能打开客户端，能正常输入命令

**Screenshots**
![图片](https://user-images.githubusercontent.com/23694384/224602476-6f4f5003-fc93-4e93-b28e-41579bd18045.png)

**Environment (please complete the following information):**
 - OS:  Ubuntu 18.04
 - Memory, CPU, current Disk Space
 - TDengine Version 3.0.3.0

**Additional Context**
我使用windows的客户端也尝试了，还是不行。windows:[TDengine-client-3.0.3.0-Windows-x64.exe (22.2 M)](https://docs.taosdata.com/get-started/package/#!)

**Comment by yu285** [comment]
服务端能正常使用的话，就是连接问题

https://www.taosdata.com/engineering/11076.html 看下问题1 排查一下
