### ISSUE TITLE
C# x86环境下 :“无法加载 DLL“taos”: 找不到指定的模块。

### ISSUE THREAD

**Issue by xky-1** [taosdata/TDengine#20438]
![image](https://user-images.githubusercontent.com/30629714/224640035-5a822dff-2dd9-404e-b7c6-45bcf302267e.png)

在x64环境下调试正常

**Comment by sangshuduo** [comment]
x86 是32位，目前不支持

**Comment by sudrizzz** [comment]
> x86 是32位，目前不支持

建议在官方文档说写明不支持32位。

**Comment by sangshuduo** [comment]
有道理
