### ISSUE TITLE
Executing the SQL statement, DB error: failed to connect to server.

### ISSUE THREAD

**Issue by jackzuo2020** [taosdata/TDengine#2044]
在一张超级表s_vehicle_track_section上执行如下sql语句，td卡死，出现
DB error: failed to connect to server
SELECT
	COUNT (*)
FROM
	s_vehicle_track_section
WHERE
	client_code = 1001
AND (eid = 1 OR eid = 2)
AND (pid = 1 OR pid = 2)
AND (vid = 1 OR vid = 2)
AND ts >= '2020-3-4 17:00:00'
AND ts <= '2020-3-4 23:00:00'
AND admdivcode >= 130000
AND admdivcode < 140000;

**Comment by xiaopingcs** [comment]
你用的是哪个版本？还有你的表结构可以分享一下吗，我这边根据你的字段建了一张表，插入了几条数据试了一下是没有问题
<img width="1222" alt="截屏2020-05-27 上午10 22 24" src="https://user-images.githubusercontent.com/65699335/82970994-39e76200-a004-11ea-9de1-f63156291f68.png">

**Comment by jackzuo2020** [comment]
> 你用的是哪个版本？还有你的表结构可以分享一下吗，我这边根据你的字段建了一张表，插入了几条数据试了一下是没有问题
> <img alt="截屏2020-05-27 上午10 22 24" width="1222" src="https://user-images.githubusercontent.com/65699335/82970994-39e76200-a004-11ea-9de1-f63156291f68.png">

我的版本是Server is Community Edition, version is 1.6.5.9
表结构是：
                             Field                              |      Type      |  Length   |  Note  |
=======================================================================================================
ts                                                              |TIMESTAMP       |          8|        |
sim                                                             |BIGINT          |          8|        |
onlinestatus                                                    |INT             |          4|        |
start_time                                                      |TIMESTAMP       |          8|        |
start_lng                                                       |INT             |          4|        |
start_lat                                                       |INT             |          4|        |
start_altitude                                                  |INT             |          4|        |
start_rt_admdivcode                                             |INT             |          4|        |
end_time                                                        |TIMESTAMP       |          8|        |
end_lng                                                         |INT             |          4|        |
end_lat                                                         |INT             |          4|        |
end_altitude                                                    |INT             |          4|        |
end_rt_admdivcode                                               |INT             |          4|        |
duration                                                        |INT             |          4|        |
vid                                                             |INT             |          4|tag     |
pid                                                             |INT             |          4|tag     |
eid                                                             |INT             |          4|tag     |
oid                                                             |INT             |          4|tag     |
admdivcode                                                      |INT             |          4|tag     |
industry_id                                                     |INT             |          4|tag     |
client_code                                                     |INT             |          4|tag     |

**Comment by sangshuduo** [comment]
请使用新版本 TDengine 看是否还有这个问题
