### ISSUE TITLE
failed to process since restore not finished, type:submit 

### ISSUE THREAD

**Issue by qiks626** [taosdata/TDengine#20448]
ERROR vgId:21, msg:0x7f70f4298dc8 failed to process since restore not finished, type:submit, gtid:0x:0x

**Comment by qiks626** [comment]
failed to process since restore not finished, type:submit导致taos崩溃无法启动，请问有什么方法可用恢复taos吗

**Comment by yu285** [comment]
麻烦提供下版本号信息。直接输入taosd 命令把崩溃部分的截图麻烦发下，另外：有产生core文件吗？
