### ISSUE TITLE
3.0.3.0  crash after deleting data

### ISSUE THREAD

**Issue by qiks626** [taosdata/TDengine#20446]
03/13 19:15:25.245682 00000304 VND ERROR vgId:21, msg:0x7f70f41d6208 failed to process since restore not finished, type:submit, gtid:0x:0x
03/13 19:15:25.245683 00000306 SYN vgId:24, sync get retry epset numOfEps:1 inUse:0
03/13 19:15:25.245694 00000304 SYN vgId:21, sync get retry epset numOfEps:1 inUse:0
03/13 19:15:25.245700 00000304 VND ERROR vgId:21, msg:0x7f70f4298dc8 failed to process since restore not finished, type:submit, gtid:0x:0x
03/13 19:15:25.245679 00000298 SYN vgId:18, sync get retry epset numOfEps:1 inUse:0
03/13 19:15:25.245701 00000306 VND ERROR vgId:24, msg:0x7f70f8143b28 failed to process since restore not finished, type:submit, gtid:0x:0x
03/13 19:15:25.245707 00000304 SYN vgId:21, sync get retry epset numOfEps:1 inUse:0
03/13 19:15:25.245709 00000306 SYN vgId:24, sync get retry epset numOfEps:1 inUse:0
03/13 19:15:25.245711 00000298 VND ERROR vgId:18, msg:0x7f724c12f758 failed to process since restore not finished, type:submit, gtid:0x:0x
03/13 19:15:25.245718 00000298 SYN vgId:18, sync get retry epset numOfEps:1 inUse:0
03/13 19:15:25.245915 00000331 VND vgId:24, restore not finish since 1920 items in apply queue
03/13 19:15:25.246149 00000329 VND vgId:18, restore not finish since 4443 items in apply queue
03/13 19:15:25.246509 00000298 VND ERROR vgId:18, msg:0x7f70f0003db8 failed to process since restore not finished, type:submit, gtid:0x:0x
03/13 19:15:25.246518 00000306 VND ERROR vgId:24, msg:0x7f70e8060cc8 failed to process since restore not finished, type:submit, gtid:0x:0x
03/13 19:15:25.246522 00000298 SYN vgId:18, sync get retry epset numOfEps:1 inUse:0
03/13 19:15:25.246527 00000306 SYN vgId:24, sync get retry epset numOfEps:1 inUse:0
03/13 19:15:25.246531 00000298 VND ERROR vgId:18, msg:0x7f70f0085b78 failed to process since restore not finished, type:submit, gtid:0x:0x
03/13 19:15:25.246535 00000304 VND ERROR vgId:21, msg:0x7f70f41d5e68 failed to process since restore not finished, type:submit, gtid:0x:0x
03/13 19:15:25.246535 00000306 VND ERROR vgId:24, msg:0x7f70e8065ea8 failed to process since restore not finished, type:submit, gtid:0x:0x
03/13 19:15:25.246537 00000298 SYN vgId:18, sync get retry epset numOfEps:1 inUse:0
03/13 19:15:25.246542 00000304 SYN vgId:21, sync get retry epset numOfEps:1 inUse:0
03/13 19:15:25.246543 00000306 SYN vgId:24, sync get retry epset numOfEps:1 inUse:0
03/13 19:15:25.246563 00000298 VND ERROR vgId:18, msg:0x7f70f0003db8 failed to process since restore not finished, type:submit, gtid:0x:0x
03/13 19:15:25.246571 00000298 SYN vgId:18, sync get retry epset numOfEps:1 inUse:0
03/13 19:15:25.246696 00000304 VND ERROR vgId:21, msg:0x7f70e8060cc8 failed to process since restore not finished, type:submit, gtid:0x:0x
03/13 19:15:25.246705 00000304 SYN vgId:21, sync get retry epset numOfEps:1 inUse:0
03/13 19:15:25.246723 00000306 VND ERROR vgId:24, msg:0x7f70e8065ea8 failed to process since restore not finished, type:submit, gtid:0x:0x
03/13 19:15:25.246732 00000306 SYN vgId:24, sync get retry epset numOfEps:1 inUse:0
03/13 19:15:25.246740 00000298 VND ERROR vgId:18, msg:0x7f70f0085b78 failed to process since restore not finished, type:submit, gtid:0x:0x
03/13 19:15:25.246750 00000298 SYN vgId:18, sync get retry epset numOfEps:1 inUse:0
03/13 19:15:25.246758 00000298 VND ERROR vgId:18, msg:0x7f70f0003db8 failed to process since restore not finished, type:submit, gtid:0x:0x
03/13 19:15:25.246762 00000298 SYN vgId:18, sync get retry epset numOfEps:1 inUse:0
03/13 19:15:25.246769 00000298 VND ERROR vgId:18, msg:0x7f70f0085b78 failed to process since restore not finished, type:submit, gtid:0x:0x
03/13 19:15:25.246776 00000298 SYN vgId:18, sync get retry epset numOfEps:1 inUse:0
03/13 19:15:25.246917 00000298 VND ERROR vgId:18, msg:0x7f70e8060cc8 failed to process since restore not finished, type:submit, gtid:0x:0x
03/13 19:15:25.246935 00000298 SYN vgId:18, sync get retry epset numOfEps:1 inUse:0
03/13 19:15:25.247250 00000298 VND ERROR vgId:18, msg:0x7f70e8065ea8 failed to process since restore not finished, type:submit, gtid:0x:0x
03/13 19:15:25.247260 00000298 SYN vgId:18, sync get retry epset numOfEps:1 inUse:0
03/13 19:15:25.247740 00000306 VND ERROR vgId:24, msg:0x7f70f0085b78 failed to process since restore not finished, type:submit, gtid:0x:0x
03/13 19:15:25.247753 00000304 VND ERROR vgId:21, msg:0x7f70f41b7568 failed to process since restore not finished, type:submit, gtid:0x:0x
03/13 19:15:25.248025 00000306 SYN vgId:24, sync get retry epset numOfEps:1 inUse:0
03/13 19:15:25.247789 00000298 VND ERROR vgId:18, msg:0x7f70e8065ea8 failed to process since restore not finished, type:submit, gtid:0x:0x
03/13 19:15:25.248032 00000304 SYN vgId:21, sync get retry epset numOfEps:1 inUse:0
03/13 19:15:25.248040 00000298 SYN vgId:18, sync get retry epset numOfEps:1 inUse:0
03/13 19:15:25.248051 00000298 VND ERROR vgId:18, msg:0x7f70e8061168 failed to process since restore not finished, type:submit, gtid:0x:0x
03/13 19:15:25.248055 00000298 SYN vgId:18, sync get retry epset numOfEps:1 inUse:0
03/13 19:15:25.248599 00000304 VND ERROR vgId:21, msg:0x7f70dc1ed408 failed to process since restore not finished, type:submit, gtid:0x:0x
03/13 19:15:25.248612 00000304 SYN vgId:21, sync get retry epset numOfEps:1 inUse:0
03/13 19:15:25.250495 00000304 VND ERROR vgId:21, msg:0x7f70f80d21b8 failed to process since restore not finished, type:submit, gtid:0x:0x
03/13 19:15:25.250508 00000304 SYN vgId:21, sync get retry epset numOfEps:1 inUse:0
03/13 19:15:25.250513 00000330 VND vgId:21, apply queue is empty, restore finish

**Comment by yu285** [comment]
请问有生成core文件吗

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
