### ISSUE TITLE
taosdump 备份数据报错

### ISSUE THREAD

**Issue by qiaogli** [taosdata/TDengine#20452]
最近想从2.6升级到3.0 备份数据的时候报错了
涛思版本：2.6.0.34
taosTools版本：2.4.0
执行备份报错：
taosdump: error while loading shared libraries: libtaosws.so: cannot open shared object file: No such file or directory

**Comment by sangshuduo** [comment]
2.6 和 3.0 需要从官网各自版本页面对应的 taos-tools 安装包，请下载最新版本

**Comment by sangshuduo** [comment]
> libtaosws.so找不到

2.6 和 3.0 需要从官网各自版本页面对应的 taos-tools 安装包

**Comment by sui-mu** [comment]
注意：
TDengine 3.x 侧的 taosTools 需要从 https://docs.taosdata.com/releases/tools/ 下载 （最新版）
TDengine 2.x （2.4-2.6） 配合的 taosTools 需要从 https://www.taosdata.com/all-downloads 下载（最新版）
