### ISSUE TITLE
windows client create table failed 

### ISSUE THREAD

**Issue by Brian-su888** [taosdata/TDengine#20455]
**Bug Description**
版本：TDengine-client-3.0.3.0-Windows-x64.exe
在windows上使用taos命令远程连接：taos -h ip -u 用户名 -P 28888 -p，可以正常连接，可正常创建数据库，
在执行建表语句报错如下：
![image](https://user-images.githubusercontent.com/107903219/224915480-8b17917c-850d-4c9e-b0a3-ce6bd9927927.png)
排查到日志关键信息：
![image](https://user-images.githubusercontent.com/107903219/224916293-b2bd9d29-b6ce-4753-b04b-dcd2f5d401c0.png)

建议：执行建表语句请求端口改为连接参数时的指定端口

**Comment by yu285** [comment]
这是连docker映射 6030 出来的 28888 端口吗？

是的话，docker内的数据库的端口也要改成 28888

**Comment by Brian-su888** [comment]
是nginx4层代理映射的28888端口，后端数据库的端口改为28888，可以解决建表语句走6030端口的错误
