### ISSUE TITLE
tdengine 3.0 keep not work

### ISSUE THREAD

**Issue by weijiazhuo** [taosdata/TDengine#20469]
1.当前数据keep 为60天，数据大小为1T
2.duration为10天
将keep改为10天，修改后tdengine已删除50天的数据，只保留最近10天。
修改后观察磁盘空间没有释放,重启tdengine也无法解决，taos数据目录使用仍是1T
版本tdengine3.0,部署方式，集群部署3节点

**Comment by melojustme** [comment]
我也遇到这个问题，尝试使用TRIM DATABASE 命令 ，磁盘空间释放了
