### ISSUE TITLE
DB error: Fail to get table info, error: Invalid Vgroup ID

### ISSUE THREAD

**Issue by guyichuang** [taosdata/TDengine#20477]
k8s 环境部署的集群，3节点，因k8s集群node异常发生过重启，k8s node恢复后，td-engine 有两个node启动失败，后来按照运维文档重新扩容到3个node, 查询报错
这是node信息
taos> SHOW DNODES;
     id      |            endpoint            | vnodes | support_vnodes |   status   |       create_time       |              note              |
=================================================================================================================================================
           1 | tdengine-0.taosd.thingsboar... |      2 |              8 | ready      | 2022-09-27 09:33:18.364 |                                |
           2 | tdengine-1.taosd.thingsboar... |      2 |              8 | ready      | 2022-09-27 09:33:41.361 |                                |
           3 | tdengine-2.taosd.thingsboar... |      2 |              8 | ready      | 2022-09-27 09:34:31.551 |                                |
Query OK, 3 rows in database (0.001677s)

这是查询报错
taos> select * from currency_2c9f99c785fc7f230185fc81d98d0000;
DB error: Fail to get table info, error: Invalid Vgroup ID (0.000991s)

容器日志中有这些错误
03/15 16:52:38.315065 00000085 MND ERROR dnode:tdengine-2.taosd.thingsboard.svc.cluster.local:6030, failed to create since success
03/15 16:52:38.315069 00000085 MND ERROR msg:0x7fa1c8012860, failed to process since success, app:0x7fd0f8002650 type:create-dnode, gtid:0x5db04b78a9290002:0x5c304b78a9290003

03/15 16:58:57.508014 00000085 MND ERROR msg:0x7fa1d40157f0, failed to process since success, app:0x7fc9c4005af0 type:balance-vgroup, gtid:0x5e23057e72610168:0x1f23057e72610181

**Comment by yu285** [comment]
升级到最新版，检查下是不是有hostname的改变。开源版用户尽量不要用k8s，运维麻烦，不容易获得官方支持。
