### ISSUE TITLE
TDengine start failed

### ISSUE THREAD

**Issue by xuyinghao** [taosdata/TDengine#20478]
03/15 17:36:46.538012 00126565 UTL =================================================================
03/15 17:36:46.539309 00126565 DND start to init dnode env
03/15 17:36:46.539357 00126565 DND dnode will run in single-process mode
03/15 17:36:46.540014 00126565 DND dnode env is initialized
03/15 17:36:46.540022 00126565 DND start to init service
03/15 17:36:46.540032 00126565 DND node:dnode, start to open
03/15 17:36:46.540041 00126565 UTL worker:dnode-mgmt is initialized, min:1 max:1
03/15 17:36:46.540121 00126576 UDF start to init udfd
03/15 17:36:46.540728 00126576 UDF udfd is initialized
03/15 17:36:46.540759 00126565 DND node:dnode, has been opened
03/15 17:36:46.540779 00126565 DND node:vnode, start to open
03/15 17:36:46.540861 00126565 WAL wal module is initialized, rsetId:3
03/15 17:36:46.541127 00126565 UTL worker:vnode-query is initialized, min:16 max:16
03/15 17:36:46.541134 00126565 UTL worker:vnode-stream is initialized, min:4 max:4
03/15 17:36:46.541140 00126565 UTL worker:vnode-mgmt is initialized, min:1 max:1
03/15 17:36:46.541568 00126565 UTL worker:vnode-monitor is initialized, min:1 max:1
03/15 17:36:46.541693 00126565 DND open 4 vnodes with 4 threads
03/15 17:36:46.550431 00126587 TSD ERROR vgId:2, tsdb gnrt current failed since No such file or directory
03/15 17:36:46.550443 00126587 TSD ERROR vgId:2, tsdb fs open failed since No such file or directory
03/15 17:36:46.550459 00126587 VND ERROR vgId:2, failed to open vnode tsdb since No such file or directory
03/15 17:36:46.550505 00126587 DND ERROR vgId:2, failed to open vnode by thread:0
03/15 17:36:46.553567 00126590 TSD ERROR vgId:10, tsdb gnrt current failed since No such file or directory
03/15 17:36:46.553574 00126589 TSD ERROR vgId:8, tsdb gnrt current failed since No such file or directory
03/15 17:36:46.553576 00126590 TSD ERROR vgId:10, tsdb fs open failed since No such file or directory
03/15 17:36:46.553581 00126589 TSD ERROR vgId:8, tsdb fs open failed since No such file or directory
03/15 17:36:46.553584 00126590 VND ERROR vgId:10, failed to open vnode tsdb since No such file or directory
03/15 17:36:46.553585 00126589 VND ERROR vgId:8, failed to open vnode tsdb since No such file or directory
03/15 17:36:46.553634 00126590 DND ERROR vgId:10, failed to open vnode by thread:3
03/15 17:36:46.553636 00126589 DND ERROR vgId:8, failed to open vnode by thread:2
03/15 17:36:46.559635 00126588 TSD ERROR vgId:4, tsdb gnrt current failed since No such file or directory
03/15 17:36:46.559655 00126588 TSD ERROR vgId:4, tsdb fs open failed since No such file or directory
03/15 17:36:46.559658 00126588 VND ERROR vgId:4, failed to open vnode tsdb since No such file or directory
03/15 17:36:46.559709 00126588 DND ERROR vgId:4, failed to open vnode by thread:1
03/15 17:36:46.559740 00126565 DND ERROR there are total vnodes:4, opened:0
03/15 17:36:46.559755 00126565 DND ERROR failed to open vnode since success
03/15 17:36:46.559764 00126565 DND ERROR failed to init vnodes-mgmt since success
03/15 17:36:46.559769 00126565 DND start to close all vnodes
03/15 17:36:46.559775 00126565 DND total vnodes:0 are all closed
03/15 17:36:47.541035 00126565 WAL wal module is cleaned up
03/15 17:36:47.541057 00126565 DND ERROR node:vnode, failed to open since success
03/15 17:36:47.541065 00126565 DND ERROR node:vnode, failed to open since success
03/15 17:36:47.541068 00126565 DND ERROR failed to open nodes since success
03/15 17:36:47.541073 00126565 DND shutting down the service
03/15 17:36:47.946344 00126565 UDF udfd start to stop, need cleanup:1, spawn err:0
03/15 17:36:47.946447 00126565 UDF udfd is cleaned up
03/15 17:36:47.946454 00126565 DND dnode env is cleaned up

**Comment by yu285** [comment]
请问具体版本号是？

**Comment by xuyinghao** [comment]
> 

3.0.0

**Comment by xuyinghao** [comment]
> 请问具体版本号是？

3.0.0.0

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
