### ISSUE TITLE
Everytime when ?; entered in TDengine shell, a runtime assertion arises.

### ISSUE THREAD

**Issue by sunyikeji** [taosdata/TDengine#2047]
taos

Welcome to the TDengine shell from Linux, Client Version:1.6.5.9
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

Server is Community Edition, version is 1.6.5.9

taos> ?;
taos: /home/develop/opensource/taosdata/TDengine/src/client/src/sql.c:1496: yy_find_shift_action: Assertion `iLookAhead < 203' failed.
已放弃(吐核)

**Comment by freemine** [comment]
#1818 

this seems already fixed. please fetch the newest version and check.
