### ISSUE TITLE
rust client 

### ISSUE THREAD

**Issue by eurake** [taosdata/TDengine#205]
Can you provide the rust programming language client library?

**Comment by tidyjiang8** [comment]
I'm trying to support this, please refer to [tdengine-connector](https://github.com/tidyjiang8/tdengine-connector). It's working in process and, so far, can be used to connect to TDengine, create database, table, insert data.

**Comment by plum-lihui** [comment]
Good work！@tidyjiang8

**Comment by eurake** [comment]
Good Job! @tidyjiang8
