### ISSUE TITLE
process submit request failed since Table does not exist,

### ISSUE THREAD

**Issue by qiks626** [taosdata/TDengine#20503]
未删除超级表，允许一段时间后出现超级表不存在，SHOW STABLE显示表存在却无法查询

03/17 07:10:31.536955 00000124 VND ERROR vgId:3, process submit request failed since Table does not exist, version:1159243
03/17 07:10:31.536961 00000124 VND ERROR vgId:3, msg:0x7f83cf03dda8 failed to apply since Table does not exist, index:1159243, gtid:0x:0x
03/17 07:10:31.536968 00000124 VND ERROR vgId:3, process submit request failed since Table does not exist, version:1159244
03/17 07:10:31.536973 00000124 VND ERROR vgId:3, msg:0x7f83cf03e0d8 failed to apply since Table does not exist, index:1159244, gtid:0x:0x
03/17 07:10:31.536981 00000124 VND ERROR vgId:3, process submit request failed since Table does not exist, version:1159245
03/17 07:10:31.536985 00000124 VND ERROR vgId:3, msg:0x7f83cf03e408 failed to apply since Table does not exist, index:1159245, gtid:0x:0x
03/17 07:10:31.536993 00000124 VND ERROR vgId:3, process submit request failed since Table does not exist, version:1159246
03/17 07:10:31.536999 00000124 VND ERROR vgId:3, msg:0x7f83cf03e738 failed to apply since Table does not exist, index:1159246, gtid:0x:0x
03/17 07:10:31.536302 00000141 VND ERROR vgId:9, msg:0x7f835c2aeba8 failed to apply since Table does not exist, index:1197655, gtid:0x:0x
03/17 07:10:31.537022 00000141 VND ERROR vgId:9, process submit request failed since Table does not exist, version:1197656
03/17 07:10:31.537028 00000141 VND ERROR vgId:9, msg:0x7f835c2aeed8 failed to apply since Table does not exist, index:1197656, gtid:0x:0x
03/17 07:10:31.537035 00000141 VND ERROR vgId:9, process submit request failed since Table does not exist, version:1197657
03/17 07:10:31.537041 00000141 VND ERROR vgId:9, msg:0x7f835c2af208 failed to apply since Table does not exist, index:1197657, gtid:0x:0x
03/17 07:10:31.537048 00000141 VND ERROR vgId:9, process submit request failed since Table does not exist, version:1197658
03/17 07:10:31.537054 00000141 VND ERROR vgId:9, msg:0x7f835c2af538 failed to apply since Table does not exist, index:1197658, gtid:0x:0x
03/17 07:10:31.537062 00000141 VND ERROR vgId:9, process submit request failed since Table does not exist, version:1197659
03/17 07:10:31.537066 00000141 VND ERROR vgId:9, msg:0x7f835c2af868 failed to apply since Table does not exist, index:1197659, gtid:0x:0x
03/17 07:10:31.537075 00000141 VND ERROR vgId:9, process submit request failed since Table does not exist, version:1197660
03/17 07:10:31.537080 00000141 VND ERROR vgId:9, msg:0x7f835c2afb98 failed to apply since Table does not exist, index:1197660, gtid:0x:0x
03/17 07:10:31.537095 00000141 VND ERROR vgId:9, process submit request failed since Table does not exist, version:1197661
03/17 07:10:31.537006 00000124 VND ERROR vgId:3, process submit request failed since Table does not exist, version:1159247
03/17 07:10:31.537097 00000136 VND ERROR vgId:6, process submit request failed since Table already exists in other stables, version:1198300
03/17 07:10:31.537103 00000124 VND ERROR vgId:3, msg:0x7f83cf03ea68 failed to apply since Table does not exist, index:1159247, gtid:0x:0x
03/17 07:10:31.537107 00000136 VND ERROR vgId:6, msg:0x7f836428bdb8 failed to apply since Table already exists in other stables, index:1198300, gtid:0x:0x
03/17 07:10:31.537112 00000124 VND ERROR vgId:3, process submit request failed since Table does not exist, version:1159248
03/17 07:10:31.537118 00000124 VND ERROR vgId:3, msg:0x7f83cf03ed98 failed to apply since Table does not exist, index:1159248, gtid:0x:0x
03/17 07:10:31.537124 00000136 VND ERROR vgId:6, process submit request failed since Table already exists in other stables, version:1198301
03/17 07:10:31.537132 00000136 VND ERROR vgId:6, msg:0x7f836428c0e8 failed to apply since Table already exists in other stables, index:1198301, gtid:0x:0x
03/17 07:10:31.537155 00000124 VND ERROR vgId:3, process submit request failed since Table does not exist, version:1159250
03/17 07:10:31.537161 00000124 VND ERROR vgId:3, msg:0x7f83cf03f348 failed to apply since Table does not exist, index:1159250, gtid:0x:0x
03/17 07:10:31.537174 00000124 VND ERROR vgId:3, process submit request failed since Table does not exist, version:1159251
03/17 07:10:31.537177 00000124 VND ERROR vgId:3, msg:0x7f83cf03f678 failed to apply since Table does not exist, index:1159251, gtid:0x:0x
03/17 07:10:31.537184 00000124 VND ERROR vgId:3, process submit request failed since Table does not exist, version:1159252
03/17 07:10:31.537187 00000136 VND ERROR vgId:6, process submit request failed since Table already exists in other stables, version:1198303
03/17 07:10:31.537190 00000124 VND ERROR vgId:3, msg:0x7f83cf03f9a8 failed to apply since Table does not exist, index:1159252, gtid:0x:0x
03/17 07:10:31.537191 00000136 VND ERROR vgId:6, msg:0x7f836428c698 failed to apply since Table already exists in other stables, index:1198303, gtid:0x:0x
03/17 07:10:31.537098 00000141 VND ERROR vgId:9, msg:0x7f835c2afec8 failed to apply since Table does not exist, index:1197661, gtid:0x:0x
03/17 07:10:31.537209 00000141 VND ERROR vgId:9, process submit request failed since Table does not exist, version:1197662
03/17 07:10:31.537213 00000136 VND ERROR vgId:6, process submit request failed since Table already exists in other stables, version:1198304
03/17 07:10:31.537216 00000141 VND ERROR vgId:9, msg:0x7f835c2b01f8 failed to apply since Table does not exist, index:1197662, gtid:0x:0x
03/17 07:10:31.537217 00000136 VND ERROR vgId:6, msg:0x7f836428c9c8 failed to apply since Table already exists in other stables, index:1198304, gtid:0x:0x
03/17 07:10:31.537225 00000141 VND ERROR vgId:9, process submit request failed since Table does not exist, version:1197663
03/17 07:10:31.537229 00000141 VND ERROR vgId:9, msg:0x7f835c2b0528 failed to apply since Table does not exist, index:1197663, gtid:0x:0x
03/17 07:10:31.537233 00000136 VND ERROR vgId:6, process submit request failed since Table already exists in other stables, version:1198305
03/17 07:10:31.537237 00000136 VND ERROR vgId:6, msg:0x7f836428ccf8 failed to apply since Table already exists in other stables, index:1198305, gtid:0x:0x
03/17 07:10:31.537237 00000141 VND ERROR vgId:9, process submit request failed since Table does not exist, version:1197664
03/17 07:10:31.537241 00000141 VND ERROR vgId:9, msg:0x7f835c2b0858 failed to apply since Table does not exist, index:1197664, gtid:0x:0x
03/17 07:10:31.537198 00000124 VND ERROR vgId:3, process submit request failed since Table does not exist, version:1159253
03/17 07:10:31.537255 00000124 VND ERROR vgId:3, msg:0x7f83cf03fcd8 failed to apply since Table does not exist, index:1159253, gtid:0x:0x
03/17 07:10:31.537262 00000124 VND ERROR vgId:3, process submit request failed since Table does not exist, version:1159254
03/17 07:10:31.537268 00000124 VND ERROR vgId:3, msg:0x7f83cf040008 failed to apply since Table does not exist, index:1159254, gtid:0x:0x
03/17 07:10:31.537275 00000124 VND ERROR vgId:3, process submit request failed since Table does not exist, version:1159255
03/17 07:10:31.537279 00000124 VND ERROR vgId:3, msg:0x7f83cf040338 failed to apply since Table does not exist, index:1159255, gtid:0x:0x

**Comment by yu285** [comment]
请提供版本号和相关截图

**Comment by qiks626** [comment]
> 请提供版本号和相关截图

3.0.3.0

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
