### ISSUE TITLE
使用taosdump 导出数据，表结构tags中有两个单引号

### ISSUE THREAD

**Issue by jiang-007** [taosdata/TDengine#20517]
正在使用的数据库版本是 2.2.2.0，当升级taos 数据库到3.0版本时，使用taosdump 迁移数据，导出的表结构tags中有两个单引号，导致数据迁移只导入表结构，没有导入数据

taosdump 版本： 2.2.2.0-d1b0e06
数据库版本：2.2.2.0

导出命令如下
`taosdump -D ai_pig -o /var/java/ -u root -p `

导出建表语句如下
`CREATE TABLE IF NOT EXISTS ai_pig.t_robot_status_152446 USING ai_pig.super_robot_status TAGS (''1568133964860755970'', ''152446'');`
TAGS 中有两个单引号

导出的数据迁移到另一台机器，导入时提示 0 条数据被导入
![9182b9d533cfe23f7136e604387a242](https://user-images.githubusercontent.com/22881731/225856924-452b9b8a-e10b-4d2e-ba47-6adc2fabb076.png)

**Comment by sangshuduo** [comment]
请从官网文档 2.6 页面下载 taostools 最新版本并使用 loose mode 备份

再从官网文档 3.0 页面下载 taostools 后缀带 comp3 的最新版本恢复

**Comment by sangshuduo** [comment]
> > 
> 
> 从官网文档 3.0 页面下载 taostools 后缀带 comp3 的最新版本后 查看版本出现下面的错误信息 `./taosdump -V` ./taosdump: error while loading shared libraries: libtaosws.so: cannot open shared object file: No such file or directory

第一步下载 2.6 的 taosTools 最新版本，对 2.2 的 TDengine 数据做备份，使用 loose mode
第二步，安装 TDengine 3.0 最新版本
第三步，卸载 原来的 taosTools ，再下载 3.0 页面的 taosTools comp3 最新版本
第四步，taosump 恢复数据

**Comment by jiang-007** [comment]
> > > 
> > 
> > 
> > 从官网文档 3.0 页面下载 taostools 后缀带 comp3 的最新版本后 查看版本出现下面的错误信息 `./taosdump -V` ./taosdump: error while loading shared libraries: libtaosws.so: cannot open shared object file: No such file or directory
> 
> 第一步下载 2.6 的 taosTools 最新版本，对 2.2 的 TDengine 数据做备份，使用 loose mode 第二步，安装 TDengine 3.0 最新版本 第三步，卸载 原来的 taosTools ，再下载 3.0 页面的 taosTools comp3 最新版本 第四步，taosump 恢复数据

谢谢，我的问题已解决。

**Comment by ohhhyuan** [comment]
想问下你是如何使用taosdump命令将数据导入到容器的
