### ISSUE TITLE
too many results from vnode for sort

### ISSUE THREAD

**Issue by xujiesh0510** [taosdata/TDengine#2051]
version: 1.6.5.8

发了一个简单的sql

select ts, val from fcloudqa.variables where vkey='MTA2MTQzX+WNleeyvuW6pg=='  AND ts >= '2020-05-01 02:14:07' and ts <= '2020-05-27 02:14:07' order by ts desc limit 6000;

报了 too many results from vnode for sort 

请问如何解决？

**Comment by Shawshank-Smile** [comment]
No more than 10w rows can be sorted.

**Comment by xujiesh0510** [comment]
ok. duly noticed
