### ISSUE TITLE
java客户端查询云实例数据失败

### ISSUE THREAD

**Issue by W-Ping** [taosdata/TDengine#20532]
**java客户查询云实例数据连接超时**
下面是驱动依赖
`  <dependency>
      <groupId>com.taosdata.jdbc</groupId>
      <artifactId>taos-jdbcdriver</artifactId>
      <version>3.0.0</version>
    </dependency> `
测试用例
![1679132924381](https://user-images.githubusercontent.com/42802329/226098148-6549bcb8-131f-4c7f-b0e4-bff9ffd3a813.png)
执行结果
![1679132965664](https://user-images.githubusercontent.com/42802329/226098176-ac68b001-fe43-40ec-bc99-34666580e9f0.png)

**Comment by feici02** [comment]
这是云服务说明的问题，我们会尽快修复，请进行以下修改：
1. 将JDBC driver的版本升级至3.1.0
2. 将JDBC连接串中的`usessl=true`替换为`useSSL=true`
