### ISSUE TITLE
java 客户端连接setByteArray 异常

### ISSUE THREAD

**Issue by W-Ping** [taosdata/TDengine#20546]
版本：taos-jdbcdriver 版本 3+
下面为异常信息
![1679283040238](https://user-images.githubusercontent.com/42802329/226240127-c3347537-bab2-49fb-b42b-97025f7a200b.png)

**Comment by sangshuduo** [comment]
java.lang.NoSuchMethodError: setByteArray

原因：taos-jdbcdriver 3.* 版本仅支持 TDengine 3.0 及以上版本。

解决方法： 使用 taos-jdbcdriver 2. 版本连接 TDengine 2. 版本。

https://docs.taosdata.com/connector/java/#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
