### ISSUE TITLE
tdclient查询的数据正常，但使用jdbc、DBeaver查出的结果只有第一行是正确的，剩下的都是为空。

### ISSUE THREAD

**Issue by keephunny** [taosdata/TDengine#20544]
**Bug Description**
![image](https://user-images.githubusercontent.com/16333653/226231739-d50d3191-88b0-420a-8b6b-39c45a235860.png)

tdclient查询的数据正常，但使用jdbc、DBeaver查出的结果只有第一行是正确的，剩下的都是为空。

**Environment (please complete the following information):**
 - OS:  CentOS Linux release 7.9.2009 (Core)
 - Memory, CPU, current Disk Space
 - TDengine Version  3.0.2.2

**Comment by yu285** [comment]
JDBC 的版本是？

**Comment by keephunny** [comment]
C:\Users\Administrator\.m2\repository\com\taosdata\jdbc\taos-jdbcdriver\3.0.0\taos-jdbcdriver-3.0.0.jar
     <dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>3.0.0</version>
        </dependency>
![image](https://user-images.githubusercontent.com/16333653/226234662-d2710620-b92f-4970-8832-9c0017186f23.png)
![image](https://user-images.githubusercontent.com/16333653/226234679-2d717535-66c6-4775-bcd7-8a2d35891969.png)

**Comment by sangshuduo** [comment]
JDBC 换 3.1.0 试试

**Comment by keephunny** [comment]
JDBC 3.1.0 可以解决问题。
