### ISSUE TITLE
timezone issue

### ISSUE THREAD

**Issue by qaz1423078740** [taosdata/TDengine#20560]
我使用了官方例程中golang的sql := `INSERT INTO power.d1001 USING power.meters TAGS('California.SanFrancisco', 2) VALUES ('2018-10-03 14:38:05.000', 10.30000, 219, 0.31000)`插入语句
我在我自己的虚拟机centos7上能够正确查询到2018-10-03 14:38:05.000'这个时间，
但是在tdengine gui中时间却是2018-10-03T06:38:05.000Z，
并且我用go查询的时间也是2018-10-03 06:38:05 +0000 UTC
我想让我能够在gui中展示的是Asia/Shanghai时区的，且golang查询的也是

**Comment by yu285** [comment]
GUI 是三方工具，访问 6041 rest接口，目前只能返回UTC-0 。 

如果是6030端口，返回数据的时区取决于应用/客户端一侧的时区参数配置
