### ISSUE TITLE
taosd crashes and can't restart

### ISSUE THREAD

**Issue by davidjin11** [taosdata/TDengine#20563]
**Bug Description**
taosd crashes and can't restart

/usr/bin/taosd

03/20 23:34:57.626784 00024267 UTL FATAL frame:0, /usr/bin/taosd() [0x53ff6f]
03/20 23:34:57.626786 00024267 UTL FATAL frame:1, /usr/bin/taosd() [0x540d9c]
03/20 23:34:57.626788 00024267 UTL FATAL frame:2, /usr/bin/taosd() [0x541b32]
03/20 23:34:57.626790 00024267 UTL FATAL frame:3, /usr/bin/taosd(tsdbCacheGetLastH+0x106) [0x54231c]
03/20 23:34:57.626792 00024267 UTL FATAL frame:4, /usr/bin/taosd() [0x6ff9db]
03/20 23:34:57.626794 00024267 UTL FATAL frame:5, /usr/bin/taosd(tsdbRetrieveCacheRows+0x6dc) [0x70013e]
03/20 23:34:57.626796 00024267 UTL FATAL frame:6, /usr/bin/taosd() [0x5d2319]
03/20 23:34:57.626798 00024267 UTL FATAL frame:7, /usr/bin/taosd() [0x5883a6]
03/20 23:34:57.626800 00024267 UTL FATAL frame:8, /usr/bin/taosd() [0x588718]
03/20 23:34:57.626801 00024267 UTL FATAL frame:9, /usr/bin/taosd(qExecTaskOpt+0x45c) [0x5817f9]
03/20 23:34:57.626803 00024267 UTL FATAL frame:10, /usr/bin/taosd(qwExecTask+0x172) [0x5e9077]
03/20 23:34:57.626805 00024267 UTL FATAL frame:11, /usr/bin/taosd(qwProcessQuery+0x477) [0x5ec574]
03/20 23:34:57.626807 00024267 UTL FATAL frame:12, /usr/bin/taosd(qWorkerProcessQueryMsg+0x456) [0x5e2392]
03/20 23:34:57.626809 00024267 UTL FATAL frame:13, /usr/bin/taosd(vnodeProcessQueryMsg+0x15f) [0x50200b]
03/20 23:34:57.626811 00024267 UTL FATAL frame:14, /usr/bin/taosd() [0x46a20b]
03/20 23:34:57.626812 00024267 UTL FATAL frame:15, /usr/bin/taosd() [0x8a58be]
03/20 23:34:57.626814 00024267 UTL FATAL frame:16, /lib64/libpthread.so.0(+0x7dd5) [0x7fab213ffdd5]
03/20 23:34:57.626816 00024267 UTL FATAL frame:17, /lib64/libc.so.6(clone+0x6d) [0x7fab20d1d02d]

**Environment (please complete the following information):**
03/21 02:09:48.776176 00002273 UTL                      global config
03/21 02:09:48.776179 00002273 UTL =================================================================
03/21 02:09:48.776182 00002273 UTL default      firstEp                  li1742-188.members.linode.com:6030
03/21 02:09:48.776184 00002273 UTL default      secondEp                 li1742-188.members.linode.com:6030
03/21 02:09:48.776187 00002273 UTL default      fqdn                     li1742-188.members.linode.com
03/21 02:09:48.776189 00002273 UTL default      serverPort               6030
03/21 02:09:48.776191 00002273 UTL default      tempDir                  /tmp/
03/21 02:09:48.776193 00002273 UTL default      minimalTmpDirGB          1.00
03/21 02:09:48.776202 00002273 UTL default      shellActivityTimer       3
03/21 02:09:48.776204 00002273 UTL default      compressMsgSize          -1
03/21 02:09:48.776206 00002273 UTL default      compressColData          -1
03/21 02:09:48.776208 00002273 UTL default      queryPolicy              1
03/21 02:09:48.776210 00002273 UTL default      enableQueryHb            0
03/21 02:09:48.776212 00002273 UTL default      querySmaOptimize         0
03/21 02:09:48.776214 00002273 UTL default      queryPlannerTrace        0
03/21 02:09:48.776216 00002273 UTL default      queryNodeChunkSize       32768
03/21 02:09:48.776218 00002273 UTL default      queryUseNodeAllocator    1
03/21 02:09:48.776220 00002273 UTL default      keepColumnName           0
03/21 02:09:48.776223 00002273 UTL default      smlChildTableName
03/21 02:09:48.776225 00002273 UTL default      smlTagName               _tag_null
03/21 02:09:48.776227 00002273 UTL default      smlDataFormat            0
03/21 02:09:48.776229 00002273 UTL default      smlBatchSize             10000
03/21 02:09:48.776231 00002273 UTL default      maxMemUsedByInsert       1024
03/21 02:09:48.776233 00002273 UTL default      maxRetryWaitTime         10000
03/21 02:09:48.776235 00002273 UTL default      useAdapter               0
03/21 02:09:48.776237 00002273 UTL default      crashReporting           1
03/21 02:09:48.776239 00002273 UTL default      numOfTaskQueueThreads    8
03/21 02:09:48.776241 00002273 UTL default      dataDir                  /var/lib/taos/
03/21 02:09:48.776243 00002273 UTL default      minimalDataDirGB         2.00
03/21 02:09:48.776245 00002273 UTL default      supportVnodes            32
03/21 02:09:48.776247 00002273 UTL default      maxShellConns            50000
03/21 02:09:48.776249 00002273 UTL default      statusInterval           1
03/21 02:09:48.776251 00002273 UTL default      minSlidingTime           10
03/21 02:09:48.776253 00002273 UTL default      minIntervalTime          1
03/21 02:09:48.776255 00002273 UTL default      maxNumOfDistinctRes      10000000
03/21 02:09:48.776257 00002273 UTL default      countAlwaysReturnValue   1
03/21 02:09:48.776258 00002273 UTL default      queryBufferSize          -1
03/21 02:09:48.776260 00002273 UTL default      printAuth                0
03/21 02:09:48.776262 00002273 UTL default      queryRspPolicy           0
03/21 02:09:48.776264 00002273 UTL default      numOfRpcThreads          8
03/21 02:09:48.776266 00002273 UTL default      numOfRpcSessions         2000
03/21 02:09:48.776268 00002273 UTL default      numOfCommitThreads       4
03/21 02:09:48.776270 00002273 UTL default      numOfMnodeReadThreads    2
03/21 02:09:48.776272 00002273 UTL default      numOfVnodeQueryThreads   32
03/21 02:09:48.776274 00002273 UTL default      ratioOfVnodeStreamThrea  1.00
03/21 02:09:48.776276 00002273 UTL default      numOfVnodeFetchThreads   4
03/21 02:09:48.776280 00002273 UTL default      numOfVnodeRsmaThreads    16
03/21 02:09:48.776282 00002273 UTL default      numOfQnodeQueryThreads   32
03/21 02:09:48.776284 00002273 UTL default      numOfSnodeSharedThreads  4
03/21 02:09:48.776285 00002273 UTL default      numOfSnodeUniqueThreads  4
03/21 02:09:48.776287 00002273 UTL default      rpcQueueMemoryAllowed    6738604032
03/21 02:09:48.776289 00002273 UTL default      syncElectInterval        25000
03/21 02:09:48.776291 00002273 UTL default      syncHeartbeatInterval    1000
03/21 02:09:48.776293 00002273 UTL default      syncHeartbeatTimeout     20000
03/21 02:09:48.776295 00002273 UTL default      vndCommitMaxInterval     60000
03/21 02:09:48.776297 00002273 UTL default      monitor                  1
03/21 02:09:48.776299 00002273 UTL default      monitorInterval          30
03/21 02:09:48.776301 00002273 UTL default      monitorFqdn
03/21 02:09:48.776302 00002273 UTL default      monitorPort              6043
03/21 02:09:48.776304 00002273 UTL default      monitorMaxLogs           100
03/21 02:09:48.776306 00002273 UTL default      monitorComp              0
03/21 02:09:48.776308 00002273 UTL default      crashReporting           1
03/21 02:09:48.776310 00002273 UTL default      telemetryReporting       1
03/21 02:09:48.776312 00002273 UTL default      telemetryInterval        43200
03/21 02:09:48.776313 00002273 UTL default      telemetryServer          telemetry.taosdata.com
03/21 02:09:48.776315 00002273 UTL default      telemetryPort            80
03/21 02:09:48.776317 00002273 UTL default      transPullupInterval      2
03/21 02:09:48.776319 00002273 UTL default      mqRebalanceInterval      2
03/21 02:09:48.776321 00002273 UTL default      ttlUnit                  86400
03/21 02:09:48.776323 00002273 UTL default      ttlPushInterval          86400
03/21 02:09:48.776325 00002273 UTL default      uptimeInterval           300
03/21 02:09:48.776326 00002273 UTL default      queryRsmaTolerance       1000
03/21 02:09:48.776328 00002273 UTL default      walFsyncDataSizeLimit    104857600
03/21 02:09:48.776330 00002273 UTL default      udf                      1
03/21 02:09:48.776332 00002273 UTL default      udfdResFuncs
03/21 02:09:48.776334 00002273 UTL default      udfdLdLibPath
03/21 02:09:48.776336 00002273 UTL default      disableStream            0
03/21 02:09:48.776338 00002273 UTL default      configDir                /etc/taos/
03/21 02:09:48.776340 00002273 UTL default      scriptDir                /etc/taos/
03/21 02:09:48.776355 00002273 UTL default      logDir                   /var/log/taos/
03/21 02:09:48.776358 00002273 UTL default      minimalLogDirGB          1.00
03/21 02:09:48.776360 00002273 UTL default      numOfLogLines            10000000
03/21 02:09:48.776362 00002273 UTL default      asyncLog                 1
03/21 02:09:48.776381 00002273 UTL default      logKeepDays              0
03/21 02:09:48.776383 00002273 UTL default      debugFlag                0
03/21 02:09:48.776385 00002273 UTL default      simDebugFlag             143
03/21 02:09:48.776386 00002273 UTL default      tmrDebugFlag             131
03/21 02:09:48.776389 00002273 UTL default      uDebugFlag               131
03/21 02:09:48.776391 00002273 UTL default      rpcDebugFlag             131
03/21 02:09:48.776393 00002273 UTL default      jniDebugFlag             131
03/21 02:09:48.776395 00002273 UTL default      qDebugFlag               131
03/21 02:09:48.776397 00002273 UTL default      cDebugFlag               131
03/21 02:09:48.776399 00002273 UTL default      dDebugFlag               131
03/21 02:09:48.776400 00002273 UTL default      vDebugFlag               131
03/21 02:09:48.776402 00002273 UTL default      mDebugFlag               131
03/21 02:09:48.776404 00002273 UTL default      wDebugFlag               131
03/21 02:09:48.776406 00002273 UTL default      sDebugFlag               131
03/21 02:09:48.776407 00002273 UTL default      tsdbDebugFlag            131
03/21 02:09:48.776409 00002273 UTL default      tqDebugFlag              131
03/21 02:09:48.776419 00002273 UTL default      fsDebugFlag              131
03/21 02:09:48.776421 00002273 UTL default      udfDebugFlag             131
03/21 02:09:48.776423 00002273 UTL default      smaDebugFlag             131
03/21 02:09:48.776425 00002273 UTL default      idxDebugFlag             131
03/21 02:09:48.776426 00002273 UTL default      tdbDebugFlag             131
03/21 02:09:48.776428 00002273 UTL default      metaDebugFlag            131
03/21 02:09:48.776430 00002273 UTL default      timezone                 Etc/UTC (UTC, +0000)
03/21 02:09:48.776432 00002273 UTL default      locale                   en_US.UTF-8
03/21 02:09:48.776434 00002273 UTL default      charset                  UTF-8
03/21 02:09:48.776436 00002273 UTL default      assert                   1
03/21 02:09:48.776438 00002273 UTL default      enableCoreFile           1
03/21 02:09:48.776440 00002273 UTL default      numOfCores               16.00
03/21 02:09:48.776443 00002273 UTL default      SSE42                    0
03/21 02:09:48.776445 00002273 UTL default      AVX                      0
03/21 02:09:48.776446 00002273 UTL default      AVX2                     0
03/21 02:09:48.776448 00002273 UTL default      FMA                      0
03/21 02:09:48.776450 00002273 UTL default      SIMD-builtins            0
03/21 02:09:48.776452 00002273 UTL default      tagFilterCache           0
03/21 02:09:48.776454 00002273 UTL default      openMax                  1000000
03/21 02:09:48.776456 00002273 UTL default      streamMax                16
03/21 02:09:48.776457 00002273 UTL default      pageSizeKB               4
03/21 02:09:48.776459 00002273 UTL default      totalMemoryKB            65806680
03/21 02:09:48.776461 00002273 UTL default      os sysname               Linux
03/21 02:09:48.776463 00002273 UTL default      os nodename              li1742-188.members.linode.com
03/21 02:09:48.776465 00002273 UTL default      os release               3.10.0-957.21.3.el7.x86_64
03/21 02:09:48.776467 00002273 UTL default      os version               #1 SMP Tue Jun 18 16:35:19 UTC 2019
03/21 02:09:48.776469 00002273 UTL default      os machine               x86_64
03/21 02:09:48.776471 00002273 UTL default      version                  3.0.2.6
03/21 02:09:48.776473 00002273 UTL default      compatible_version       3.0.0.0
03/21 02:09:48.776475 00002273 UTL default      gitinfo                  0993813213efe3e18a0fcb5ab26538b811451798
03/21 02:09:48.776477 00002273 UTL default      buildinfo                Built at 2023-02-23 14:51
03/21 02:09:48.776478 00002273 UTL =================================================================

**Comment by yu285** [comment]
could you upgrade it to 3.0.3.0 then start it directly  , I guess it has been fixed , if not we can  check it by remote access tool .

**Comment by davidjin11** [comment]
Thanks for your quick reply. We will upgrade to 3.0.3.0.

**Comment by davidjin11** [comment]
The issue has been fixed on 3.0.3.0. Thanks.
