### ISSUE TITLE
regarding to performance issue 

### ISSUE THREAD

**Issue by lulg** [taosdata/TDengine#20586]
当有上万或几十万设备时，我如果开大量的流计算或者大量的数据订阅，会不会对TDengine的的性能差生明显的影响。

**Comment by yu285** [comment]
几十万设备并不多，整体性能不会有影响，可以参考过往 用户案例。

但是流计算需要一段时间迭代稳定，后续也不会有太大影响。

**Comment by lulg** [comment]
意思是流计算这块目前还不稳定吗？一些常规的数据聚合、过滤能用吧。

**Comment by yu285** [comment]
流计算现在已经很稳定了，3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
