### ISSUE TITLE
suggestion of document

### ISSUE THREAD

**Issue by lulg** [taosdata/TDengine#20583]
![image](https://user-images.githubusercontent.com/28698352/226775238-116e8a07-0644-4b4d-8b28-67863bf8ac61.png)
文档中用到的表名都是以dxxx开头的，建议改成txxx开头。dxxx容易给人一种心理暗示，以为是database而不是table。

**Comment by yu285** [comment]
感谢，我们会考虑。不过由于我们整个demo程序用的都是一套命名规则，可能该动起来规模会比较大

**Comment by sangshuduo** [comment]
d 代表 device
