### ISSUE TITLE
Test case compilation exception

### ISSUE THREAD

**Issue by yuao1112** [taosdata/TDengine#20597]
**Bug Description**
获取tdengine的源码，分支为2.6，编译【docs/examples/go/connect/cgoexample/main.go:10】的代码运行报错

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**
编译测试用例
![image](https://user-images.githubusercontent.com/24371179/226834065-f563fc33-b0e4-4114-bcb4-43586662a178.png)

**Screenshots**

**Environment (please complete the following information):**
 - OS: window11
 - TDengine Version [e.g. 2.6.0.34]

**Additional Context**

**Comment by wangmm0220** [comment]
这个问题的原因是windows导出的库里没有 这个接口taos_schemaless_insert_raw。
从2.6拉了个分支fix/20597，在这个分支上加上了导出这个接口的配置。可以用这个分支，编译安装一下，然后再运行这个例子。

建议可以直接用3.0的版本，3.0版本稳定的分支是main
