### ISSUE TITLE
raw data query enhancement

### ISSUE THREAD

**Issue by xujiesh0510** [taosdata/TDengine#2059]
针对超级表的一些查询：

1. 原始数据按时间降序查询 会有10万条结果集限制。 那么如果想要 一个时间段范围 数据按时间降序，并没有加上其他查询条件约束，取6000条，也有可能报错，因为数据在表里面本来是升序的，为什么不能倒过来直接取6000条？

2. 多线程查询原始数据,每次查询1000条，偶尔会出现时间范围外的数据。

**Comment by xujiesh0510** [comment]
关于第一点：
超级表的时间戳排序有数量要求，因为之前的order by ts是对结果集中的每个子表的数据排序。现在改成所有子表的记录混在一起排序，这个耗费计算资源高就加了个数量限制
可行的办法： 针对子表单独查询，没有限制。

**Comment by Shawshank-Smile** [comment]
This can be change, the  para is not in the tao.cfg yet. Thank you for your

**Comment by Shawshank-Smile** [comment]
This can be change, the  para is not in the tao.cfg yet. Thank you for your
