### ISSUE TITLE
3031 query issue

### ISSUE THREAD

**Issue by Stokoloshe** [taosdata/TDengine#20600]
**Bug Description**
3.0.1.6版卸载再安装3.0.3.1版本，超级表上使用where条件查询不到某些子表的数据，单独查询子表是可以查到的。卸载掉3.0.3.1版本，安装3.0.3.0版本，查询正常了

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by yu285** [comment]
可以远程看下 微信 a15652223354
