### ISSUE TITLE
[2.4.0.10][docker][show databases return slowly

### ISSUE THREAD

**Issue by relax-lee** [taosdata/TDengine#20614]
版本：2.4.0.10 docker 镜像
宿主机：CentOS Linux release 7.9.2009 
现象：show databases 等命令执行非常缓慢

查阅TDengine 相关issue ，建议动态调整日志级别，日志级别调整后，
发现日志如下：

03/24 00:23:20.871852 00000101 MND 0x7fbff4c838d0, show type:show databases index:67240, get meta finished, numOfRows:10 cols:19 result:success
03/24 00:23:20.871854 00000101 MND 0x7fbff4c838d0, show is released, force:false data:0x7fbff4072a40 index:67240
03/24 00:23:20.871856 00000101 UTL cache:show, data:0x7fbff4072a40 extend expire time: 1679617418871
03/24 00:23:20.871858 00000101 UTL cache:show, key:0x7fbff4072a48, 0x7fbff4072a40 released, refcnt:0, data in trashcan:0
03/24 00:23:20.871891 00000101 RPC SHELL 0x7fc003d50918 0x5, show-rsp is sent to 0x50011ac:48380, code:0x0 len:2592 sig:0xaf790000:0x02000000:63544
03/24 00:23:20.871897 00000101 RPC ERROR SHELL 0x7fc003d50918 0x5, failed to send, msgLen:2592 written:-1, reason:Success
03/24 00:23:20.871920 00000101 SDB vgId:1, sdb:users, dec ref to row:0x55d3772185c0:root:1
03/24 00:23:20.871922 00000101 UTL item:0x7fbfd0002350, node:0x7fbfd0002340 is freed
03/24 00:23:20.882589 00000054 UTL rsetId:4 p:0x7fc06c14b010 rid:12 is acquired

查询该版本源码，ERROR 定位到 rpcSendMsgToPeer 函数，
writtenLen = (*taosSendData[pConn->connType])(pConn->peerIp, pConn->peerPort, pHead, msgLen, pConn->chandle);
writtenLen 返回值 为 -1，暂无进一步分析手段，希望能提供建议或意见。

**Comment by yu285** [comment]
服务端执行也慢吗

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/

如果还有具体的使用问题，可以加微信：a15652223354
