### ISSUE TITLE
使用tdengine数据库3.0.2.0  ，restful连接该数据库，报空指针异常。

### ISSUE THREAD

**Issue by linser2015** [taosdata/TDengine#20624]
**Bug Description**
在业务系统中使用添加jar包驱动的方式 用restful来连接数据库，数据库3.0.2.0  ，驱动版本3.1.0.    java 。
连接信息正确  ，， 

然后采用driverManager ， 来连接涛思数据库，出现空指针。
报错信息是  restfulDriver中的111行 ，但是  没看到有代码。
![47375b63a7be92e52bd083aabe9023f](https://user-images.githubusercontent.com/12657856/227423937-56ebf097-49db-4834-968c-5a581bda8147.png)

见上图 。。

**Comment by linser2015** [comment]
另附部分连接代码： 主要就是 calss.forName  加载驱动类。。然后 执行连接。     配置均正确  。。REstFul方式 ，端口6041
![1679632381931](https://user-images.githubusercontent.com/12657856/227425393-8acb4216-78e1-4300-8413-1fe48d9451c6.png)

**Comment by huolibo** [comment]
你好，我看报错之后对应行是空行，是不是导入的 jar 包版本不对呢？
另外我写了一个 test case，请在本地运行一下看能否复现这个问题：
```
import org.junit.Assert;
import org.junit.Test;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Properties;

public class RestConnectionTest {

    private static final String HOST = "127.0.0.1";

    @Test
    public void test() throws SQLException {
        String url = "jdbc:TAOS-RS://"+ HOST + ":6041/";
        try{
            Class.forName("com.taosdata.jdbc.rs.RestfulDriver");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }

        Properties properties = new Properties();
        properties.setProperty(TSDBDriver.PROPERTY_KEY_TIME_ZONE, "UTC-8");
        properties.setProperty(TSDBDriver.PROPERTY_KEY_BATCH_LOAD, "true");
        properties.setProperty(TSDBDriver.PROPERTY_KEY_USER,"root");
        properties.setProperty(TSDBDriver.PROPERTY_KEY_PASSWORD,"taosdata");
        try(Connection connection = DriverManager.getConnection(url, properties)){
            DatabaseMetaData metaData = connection.getMetaData();
            Assert.assertEquals(url,metaData.getURL());
        }
    }
}
```

**Comment by linser2015** [comment]
备注：    jdbc 同样的场景   。。 普通的的方式能正常连接到涛思数据库。。但是restful方式就不行

**Comment by huolibo** [comment]
了解，请确认下引入的 jdbc 版本与上述 test 能否正常运行。

**Comment by linser2015** [comment]
> 了解，请确认下引入的 jdbc 版本与上述 test 能否正常运行。

还能继续告诉你  ，  这个代码能运行 。        。 我这样给你说吧  。   我在我写了restful的代码   不在我们项目中 还是能连的。并且能获取数据

**Comment by linser2015** [comment]
![image](https://user-images.githubusercontent.com/12657856/227459076-70d31b02-4aa0-466f-9c75-db59b64c5ef8.png)
示例代码能运行

**Comment by huolibo** [comment]
那在项目中 jdbc 代码与 TDengine 中间有网关或是 Nginx 等中间件吗？

**Comment by linser2015** [comment]
嗯  项目是 放在tomcat中运行的。  其他的没有额。      普通方式 已经可以    正常的。 但是  restful方式不行。

**Comment by huolibo** [comment]
我的意思是看下是否有网络中其他数据返回导致 jdbc 不能解析触发异常。
另外代码不对应也非常奇怪，可以通过断点进去看下 jdbc 运行的版本。

**Comment by linser2015** [comment]
![image](https://user-images.githubusercontent.com/12657856/227462108-d8509859-e87e-42ec-bd44-d94910808277.png)

**Comment by huolibo** [comment]
然后往下运行一行就报 npe？

**Comment by huolibo** [comment]
我想知道哪个对象为空导致了 npe。

**Comment by linser2015** [comment]
![image](https://user-images.githubusercontent.com/12657856/227466254-bd554dee-a0a1-47bb-a23e-d56e51861418.png)
这样报错111行 都没信息。  我在想是不是他前面那一行的问题

**Comment by linser2015** [comment]
![image](https://user-images.githubusercontent.com/12657856/227466935-22c32548-e241-4e97-8249-591382c36be1.png)
这是 运行到111行时  再进行下一步就报错。    我在想 代码不对应 。我也没看出来是 那一刚npe了

**Comment by linser2015** [comment]
> 我想知道哪个对象为空导致了 npe。
 
你可以把你的111行截个图看下嘛？？  我这感觉代码不对应   。 我这附近的值 都点不出来的。

**Comment by linser2015** [comment]
![image](https://user-images.githubusercontent.com/12657856/227467577-e655744e-c86e-4f64-ae77-3b97fdf3c5d6.png)
这一步 我看就只有这两个null。  其他的  我也没看懂。

**Comment by huolibo** [comment]
这两个为 null 应该不影响，batchLoad 仅判断是否执行 ws 连接，status 此文件中没有此对象。
建议将 home 目录下的 .m2/repository/com/taos/jdbc 清除然后让 maven 重新拉取代码。

**Comment by linser2015** [comment]
![image](https://user-images.githubusercontent.com/12657856/227469207-78bd9a78-aa74-478d-ba81-fdb11f89a72d.png)


> 这两个为 null 应该不影响，batchLoad 仅判断是否执行 ws 连接，status 此文件中没有此对象。 建议将 home 目录下的 .m2/repository/com/taos/jdbc 清除然后让 maven 重新拉取代码。
好的   我试一下

**Comment by linser2015** [comment]
![image](https://user-images.githubusercontent.com/12657856/227469286-cc2390f0-4c8e-47ae-9384-4b5fdf10d45e.png)

**Comment by linser2015** [comment]
> 这两个为 null 应该不影响，batchLoad 仅判断是否执行 ws 连接，status 此文件中没有此对象。 建议将 home 目录下的 .m2/repository/com/taos/jdbc 清除然后让 maven 重新拉取代码。

重新拉取代码后 正常没报错了 。。估计是我本地缓存了之前的版本驱动
