### ISSUE TITLE
tdengine cloud  streaming computing，how to configure concat_ws(".", location, tbname) as meter_location 

### ISSUE THREAD

**Issue by lulg** [taosdata/TDengine#20626]
我看一个字段只能配一个函数。
![image](https://user-images.githubusercontent.com/28698352/227442536-801af628-6dc6-4db1-97e7-2b9112e1ed6d.png)

**Comment by yu285** [comment]
页面的引导支持会有局限，可能无法实现某些复杂语句

建议复杂的流用sql形式来写

另外，流计算暂时处于优化阶段，可以等4月下旬左右再使用。
