### ISSUE TITLE
DB error: Unable to establish connection (0.081802s)

### ISSUE THREAD

**Issue by duhaoranc** [taosdata/TDengine#20629]
docker镜像版本3.0.1.5
在docker容器中进入taos  执行查询语句， 
Assertion `pBlockCol->type == pColData->type' failed.看日志会有这个问题
然后直接就自动退出tdengine的docker镜像 
请问这是什么问题呢   查询某几个字段不会报这个错误   个别字段会报这个错误

**Comment by linser2015** [comment]
> docker镜像版本3.0.1.5 在docker容器中进入taos 执行查询语句， Assertion `pBlockCol->type == pColData->type' failed.看日志会有这个问题 然后直接就自动退出tdengine的docker镜像 请问这是什么问题呢 查询某几个字段不会报这个错误 个别字段会报这个错误


你还应该附上    涛思数据库版本    驱动版本   客户端版本。  docker的话 建议重装一下 涛思数据库试一下

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
