### ISSUE TITLE
 TDengine  v2.6.0.18  docker  taosAdapter disappear

### ISSUE THREAD

**Issue by LuckyHangMei** [taosdata/TDengine#20648]
docker 部署TDengine 版本 v2.6.0.18，taosAdapter服务会停止运行，

![image](https://user-images.githubusercontent.com/64392435/227855239-466239f3-5831-4c58-8fef-ce91734f1255.png)

**Comment by yu285** [comment]
看下系统日志，taosadapter 的shutdown signal 是什么
