### ISSUE TITLE
event window in stream failed

### ISSUE THREAD

**Issue by xiahejun** [taosdata/TDengine#20651]
TDengine 版本：3.0.3.1
使用过程：
1 创建库和超级表，根据超级表插入子表数据，字表数据如下：
![image](https://user-images.githubusercontent.com/54968493/227864019-593fbc4f-f3d6-4a28-be11-8ad87e3a76b1.png)

2 使用事件窗函数，获取报警数据（阈值判断），结果如下：
![image](https://user-images.githubusercontent.com/54968493/227864113-86ee7e87-f5b5-4312-9879-ee939482192e.png)

3 **因为流计算不支持事件窗函数（此处生产环境一定要注意，如果使用了taos服务将停止）**，所以打算将窗函数的结果写到其他表里，然后订阅此表实现 实时动态获取报警数据。但是使用insert into xx的时候报错如下：
taos> insert into  AIC_ALARMS.alarm_point select  _wstart alarm_start, _wend alarm_end, 'd_alarm_point2' name,count(*) time_count,TIMEDIFF(_wstart,_wend,1s) time_diff from aic_real.d_alarm_point  event_window start with val >= 5 end with val < 5;

DB error: Planner internal error (0.000913s)
烦请各位大佬协助解决，或者给出其他好的方案，感谢。

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
