### ISSUE TITLE
3.0.3.1版本启动失败

### ISSUE THREAD

**Issue by duyingsoft** [taosdata/TDengine#20667]
版本：3.0.3.1
操作系统：CentOS Linux release 7.9.2009 (Core)

问题：用systemctl start taosd命令启动失败，没有看出是什么错误导致
          手动启动，提示动态加载有问题
![image](https://user-images.githubusercontent.com/13470619/228113766-d7353f98-845f-4156-ae00-c2cf8083b3fe.png)

但是查找动态库的话，本地是有的
![image](https://user-images.githubusercontent.com/13470619/228113906-83826bce-d479-4a28-8cad-3c693d51e038.png)

这个能帮忙看看是什么问题吗？

**Comment by sangshuduo** [comment]
已知问题，在修复中。试试 在 /etc/ld.so.conf.d/ 中增加一个 jemalloc.conf 文件，文件内容为 /usr/local/lib，执行 sudo ldconfig

**Comment by sangshuduo** [comment]
已知问题，在修复中。试试 在 /etc/ld.so.conf.d/ 中增加一个 jemalloc.conf 文件，文件内容为 /usr/local/lib，执行 sudo ldconfig

**Comment by sangshuduo** [comment]
已知问题，在修复中。试试 在 /etc/ld.so.conf.d/ 中增加一个 jemalloc.conf 文件，文件内容为 /usr/local/lib，执行 sudo ldconfig

**Comment by duyingsoft** [comment]
> 已知问题，在修复中。试试 在 /etc/ld.so.conf.d/ 中增加一个 jemalloc.conf 文件，文件内容为 /usr/local/lib，执行 sudo ldconfig

这个方法可以

**Comment by lulg** [comment]
请问下一版会解决这问题吗。上边的方案在docker中不生效，也不太方便。
下版预计什么时候发。
@sangshuduo

**Comment by sangshuduo** [comment]
> 请问下一版会解决这问题吗。上边的方案在docker中不生效，也不太方便。 下版预计什么时候发。 @sangshuduo

下一版中修复
