### ISSUE TITLE
TDengine crash when querying super table

### ISSUE THREAD

**Issue by Stokoloshe** [taosdata/TDengine#20692]
**Bug Description**
如下两条查询，在同一个页面调用，导致tdengine进程退出
第一条：select mcid, alarmno, count(*) as `count` from almlog WHERE starttime >= '2023-02-01' and starttime < '2023-04-01' partition by mcid, alarmno order by `count` desc, mcid, alarmno limit 10;
第二条：SELECT mcid, alarmno, alarmtext, _wstart AS MONTH, count(*) AS `count` FROM almlog WHERE starttime >= '2023-02-01' AND starttime < '2023-04-01' PARTITION BY mcid, alarmno, alarmtext INTERVAL(1n) ORDER BY `count` DESC, mcid, alarmno LIMIT 10;
（报错无法建立连接，进程已退出）

表结构如下：
CREATE STABLE almlog (starttime timestamp, endtime timestamp, durationtime int, alarmno int, alarmtext nchar(256), isactive nchar(64)) TAGS (mcid nchar(16));

报错截图：
![bc17cb1f3b2b6db6e3193a1f09630bc](https://user-images.githubusercontent.com/18400916/228476817-4c48dd0a-4672-4ce5-9d73-6d874346e35e.png)
![fb8e0384cb49143fc102041bc236daa](https://user-images.githubusercontent.com/18400916/228476898-603a1ba4-e0aa-4dc7-b55f-39afeb114e70.png)
![2730c856d2266e82d567a40cc0f9b70](https://user-images.githubusercontent.com/18400916/228476969-58caaabd-b4dd-402f-b103-92511af6ac16.png)

环境：
windows server2016
TDengine3.0.3.0

**Comment by yu285** [comment]
请问C：TDengine 有产生dmp文件吗
