### ISSUE TITLE
What is the difference between one-stage compression and two-stage compression? How does it affect the query?

### ISSUE THREAD

**Issue by hiwooNum1** [taosdata/TDengine#2069]
comp: 文件压缩标志位，0：关闭，1:一阶段压缩，2:两阶段压缩   
1、2两个压缩状态压缩后有什么不同效果， 对查询有什么影响

**Comment by Shawshank-Smile** [comment]
It is recommended to use the default mode, with small space occupation and unaffected query

**Comment by Shawshank-Smile** [comment]
1.6.5.9 it is very stable, please feel free to enjoy it.

**Comment by hiwooNum1** [comment]
> 1.6.5.9它非常稳定，请随时使用。

非常感谢
