### ISSUE TITLE
windows memory leak

### ISSUE THREAD

**Issue by 414501408** [taosdata/TDengine#20728]
用最新的 3.0.31 版本，  windows下运行简单的代码测试， 循环读取 benchmark 中写入过的数据

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TDengineDriver;
using TDengineDriver.Impl;

public class TestTDengine
{

    public static void Main()
    {
        Console.WriteLine("test");

        while(true)
        {

            string host = "localhost";
            short port = 6030;
            string username = "root";
            string password = "123456";
            string dbname = "test";

            var conn = TDengine.Connect(host, username, password, dbname, port);
            if (conn == IntPtr.Zero)
            {
                Console.WriteLine("Connect to TDengine failed");

            }
            else
            {

                // run query
                IntPtr res = TDengine.Query(conn, "SELECT * FROM d7546 LIMIT 2");
                if (TDengine.ErrorNo(res) != 0)
                {
                    throw new Exception("Failed to query since: " + TDengine.Error(res));
                }

                // get filed count
                int fieldCount = TDengine.FieldCount(res);
                Console.WriteLine("fieldCount=" + fieldCount);

                // print column names
                List<TDengineMeta> metas = LibTaos.GetMeta(res);
                for (int i = 0; i < metas.Count; i++)
                {
                    Console.Write(metas[i].name + "\t");
                }
                Console.WriteLine();

                // print values
                List<Object> resData = LibTaos.GetData(res);
                for (int i = 0; i < resData.Count; i++)
                {
                    Console.Write($"|{resData[i].ToString()} \t");
                    if (((i + 1) % metas.Count == 0))
                    {
                        Console.WriteLine("");
                    }
                }
                Console.WriteLine();

                // Free result after use
                TDengine.FreeResult(res);

                Console.WriteLine("Connect to TDengine success");
            }
            TDengine.Close(conn);

        }
    }
}

taosd 的句柄会一直快速增加， 1分钟就1万多的句柄了

**Comment by sangshuduo** [comment]
Close(conn)写在 while 循环外面了

**Comment by 414501408** [comment]
是在循环里面的， 那个括号是上面的 if

**Comment by 414501408** [comment]
因为写的正式的查询系统线上运行一直句柄增加导致运行不了多久 taosd 就会退出，  就写了这个简单的循环的测试代码运行， 果然一样的， 每次query都会 句柄增加， 这应该是一个bug

**Comment by sangshuduo** [comment]
好的，我们看一下，谢谢报 issue

**Comment by 414501408** [comment]
谢谢， 忘了说明清楚， 我用的是 windows server 的， 不是 client

**Comment by 414501408** [comment]
请问有进展吗？ 麻烦尽快能修一下谢谢

**Comment by facetosea** [comment]
> 请问有进展吗？ 麻烦尽快能修一下谢谢

谢谢反馈，已经处理，新版本会修复。

**Comment by 414501408** [comment]
太棒了

**Comment by 414501408** [comment]
这 bug 像个定时炸弹一样， 一直加， 加到后面数据库就挂了

**Comment by sangshuduo** [comment]
> 请问这个bug 现在版本修复了吗

已修复，请使用新版本 3.0.4.0
