### ISSUE TITLE
limit query issue

### ISSUE THREAD

**Issue by caizhongbing** [taosdata/TDengine#20723]
表中的某些列的值明明为NULL，但是有时候查询出来却是0.00000，经过排查发现其和limit有关，如果查询语句中不带limit，那么查询出来的都是正常的NULL，如果加上limit了，那么结果集有时候显示的对有时候不对，很奇怪。TDEngine版本是Linux 3.0.1.5
![1680249206088](https://user-images.githubusercontent.com/59197561/229059691-fc549f6b-df1b-402c-86d0-47ca65d5fc55.jpg)

**Comment by caizhongbing** [comment]
请问有没有人能帮助一下？

**Comment by yu285** [comment]
这个版本太旧了，麻烦先换到 3031 如果还有问题，我会远程看下：
微信：a15652223354

**Comment by caizhongbing** [comment]
已经升级到3031了，依然有问题，已经添加您微信了

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
