### ISSUE TITLE
How does the client version correspond to the JDBC version?

### ISSUE THREAD

**Issue by lulg** [taosdata/TDengine#20731]
请问客户端版本与驱动版本怎么对应的。
我客户端版本是3.0.3.1，驱动版本用3.1.0不可以吗

环境，docker linux
![image](https://user-images.githubusercontent.com/28698352/229389307-729ee51d-ed3a-44f5-893c-37267ced5585.png)

**Comment by yu285** [comment]
版本是可以的，再检查下配置吧
