### ISSUE TITLE
批量写入数据不稳定

### ISSUE THREAD

**Issue by zuodengchao** [taosdata/TDengine#20737]
我使用的tdengin版本是3.0.1.8，我的应用中大概有70张超级表，子表1229756张，批量向子表插入数据（写入数据的时候会自动创建表），有时候耗时十几秒，有时候几毫秒，很不稳定。

**Comment by yu285** [comment]
可以先换到 3.0.3.1 再做尝试，还有问题可以远程看下

a15652223354
