### ISSUE TITLE
windows 3.0.2.5 order by  query not return expected data

### ISSUE THREAD

**Issue by fanqang** [taosdata/TDengine#20734]
<img width="688" alt="1680493547404" src="https://user-images.githubusercontent.com/47728120/229406817-015b5340-cce3-4c38-a9b5-d2c09b7020c5.png">

<img width="697" alt="1680493519414" src="https://user-images.githubusercontent.com/47728120/229406754-231dffa5-d54c-4bcb-87a8-939831505f04.png">

**Comment by feici02** [comment]
从截图看，数据并没有重复，查询结果的lastts, nextts两个字段的值都不相同；
Param_Update应该是一个超级表，结果数据来自于不同的子表，并按ts字段排序，但该字段的值全部相同，结果是正常的。

**Comment by fanqang** [comment]
我这张表就是一张普通表，而且这张表就一条数据，然后升序是正常的，降序就出现了很多条重复的 我是按ts主键字段来排序的，这个字段不存在重复数据，这个字段的值是唯一的时间戳，麻烦看看是什么情况

**Comment by fanqang** [comment]
补充一下 我的系统环境是 windows server 2019版本

**Comment by feici02** [comment]
我在3.0.2.5版本进行了以下测试，但并没有复现该问题，请确认和你的场景是否一致？
创建一个普通表后，使用相同的时间戳多次写入，表中的数据被更新，只有1条记录；
然后查询该表，按照ts字段降序排列：
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/5568663/230700417-5a84ba18-d5c8-4c85-a87f-17117d232336.png">

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
