### ISSUE TITLE
taosd start failed    

### ISSUE THREAD

**Issue by lychmi** [taosdata/TDengine#20753]
服务器扩展内存以后   systemctl启动就报错了
taosd.service - TDengine server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Tue 2023-04-04 12:15:43 CST; 2s ago
  Process: 468727 ExecStart=/usr/bin/taosd (code=exited, status=255)
  Process: 468718 ExecStartPre=/usr/local/taos/bin/startPre.sh (code=exited, status=0/SUCCESS)
 Main PID: 468727 (code=exited, status=255)

Apr 04 12:15:43 iZpfmnydout3gpZ systemd[1]: Unit taosd.service entered failed state.
Apr 04 12:15:43 iZpfmnydout3gpZ systemd[1]: taosd.service failed.
Apr 04 12:15:43 iZpfmnydout3gpZ systemd[1]: taosd.service holdoff time over, scheduling restart.
Apr 04 12:15:43 iZpfmnydout3gpZ systemd[1]: Stopped TDengine server service.
Apr 04 12:15:43 iZpfmnydout3gpZ systemd[1]: start request repeated too quickly for taosd.service
Apr 04 12:15:43 iZpfmnydout3gpZ systemd[1]: Failed to start TDengine server service.
Apr 04 12:15:43 iZpfmnydout3gpZ systemd[1]: Unit taosd.service entered failed state.
Apr 04 12:15:43 iZpfmnydout3gpZ systemd[1]: taosd.service failed.

以为是关机前未关闭数据库导致数据错误。  删除数据文件后启动还是报错

启动 taosd报错
04/04 11:35:44.356889 00419487 DND ERROR failed to init dnode rpc server
04/04 11:35:44.356900 00419487 DND ERROR failed to init transport since Cannot assign requested address
04/04 11:35:44.356911 00419487 DND ERROR failed to create dnode since Cannot assign requested address
04/04 11:35:44.356916 00419487 DND ERROR failed to init dnode since Cannot assign requested ### address

**Comment by lychmi** [comment]
log里也没任何报错，只有new log file

**Comment by feiyangbeyond** [comment]
我也遇到了同样的问题，请问解决了吗

**Comment by yu285** [comment]
应该是权限/通讯配置之类的问题吧

**Comment by yu285** [comment]
检查下 fqdn 这些是否依然准确
