### ISSUE TITLE
failed to connect to server, reason: Version not compatible

### ISSUE THREAD

**Issue by yzdzb** [taosdata/TDengine#20757]
客户端版本3.0.3.0 服务端版本也是3.0.3.0但是提示 Version not compatible
客户端
![image](https://user-images.githubusercontent.com/69287175/229717201-be42d9aa-dcfb-4bc5-9521-54b9949f9225.png)
服务端
![image](https://user-images.githubusercontent.com/69287175/229717285-3f1164c9-9df4-4339-9b7a-9beb6dbeca52.png)
客户端配置文件和hosts
![image](https://user-images.githubusercontent.com/69287175/229717573-d1907ade-cbdc-4637-81de-347c33d30b82.png)
![image](https://user-images.githubusercontent.com/69287175/229717735-98ae0dfa-8cc5-4609-9df9-d933d9aea8be.png)
服务端配置文件和hosts
![image](https://user-images.githubusercontent.com/69287175/229717914-f1135e67-4ce4-4a51-82a7-ab288c59de0c.png)
![image](https://user-images.githubusercontent.com/69287175/229718034-41874615-90ae-4c2f-9398-d95707d61352.png)

**Comment by yzdzb** [comment]
之前一台服务器可以正常使用  第二台服务器就这样了

**Comment by AdamvvYau** [comment]
我也有同样的问题，请问解决了吗？是怎么解决的？
