### ISSUE TITLE
DB error: Unable to establish connection While execute transaction (62.328632s)

### ISSUE THREAD

**Issue by lcy001001** [taosdata/TDengine#20755]
![ff798f0aa4d7ccab94549b5b3acde74](https://user-images.githubusercontent.com/128111030/229702640-678e54ad-218f-456e-9e14-81bbeb7d133d.png)
TDEngine 集群（3.0.1.5）中删除库，删除不掉，节点都在线
![f65d893144b73a732efbb65187124bd](https://user-images.githubusercontent.com/128111030/229702959-48f47d05-e809-42c8-9d2c-879e2f6d6a4e.png)
有的能删除，有的就卡着不动了，这是什么原因

**Comment by lcy001001** [comment]
![482984695643a9b87c8b39468d6b828](https://user-images.githubusercontent.com/128111030/229703550-a2d6c09d-7603-4d8e-83f3-26ab91ed3fdb.png)
再次删除就提示这个库不存在，但我show databases;查看这些库都还存在

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
