### ISSUE TITLE
Unable to establish connection

### ISSUE THREAD

**Issue by codezn1997** [taosdata/TDengine#20760]
tdengine版本：3.0
驱动版本：3.1
zkcj_entrance_guard> SELECT count(0) FROM guard_record WHERE device_id = 4
[2023-04-04 15:46:20] [11] TDengine ERROR (b): sql: SELECT count(0) FROM guard_record WHERE device_id = 4, desc: Unable to establish connection

device_id是超级表中的一个标签字段，类型是bigint，当我执行这条sql语句的时候，就会报错，数据库链接不上，不执行这个语句就是正常的，查询，添加都没问题

**Comment by codezn1997** [comment]
如果sql后面的条件改成其他类型的就没有问题，只有bigint类型的会报错

**Comment by yu285** [comment]
需要知晓具体版本号，3.0.几？

**Comment by codezn1997** [comment]
version: 3.0.1.4
















在 2023-04-19 11:28:45，"Yu Chen" ***@***.***> 写道：

需要知晓具体版本号，3.0.几？

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
