### ISSUE TITLE
taosdump  dump out failed

### ISSUE THREAD

**Issue by chao** [taosdata/TDengine#20787]
**Bug Description**
用了几个月，突然通过REST的API查询某几张表的时候会导致整个容器重启。然后尝试使用taosdump导出数据也报错。错误内容：

```
ERROR: getTableTagValueNativeV3() LN2720, failed to run command <SELECT tag_name,tag_value FROM information_schema.ins_tags WHERE db_name = '***' AND table_name = 't_24e124707c481306'>, taos: 0x55dfd90f7290, code: 0x800026ff, reason: Parser internal error
```

**To Reproduce**
1、进入容器执行导出`taosdump -d z*** -s`
2、在导出某几张表的时候报错

**Expected Behavior**
希望能正常导出

**Screenshots**
<img width="1663" alt="image" src="https://user-images.githubusercontent.com/55872/230274401-dbcfff47-f126-4514-a37a-01507a4018a0.png">

**Environment (please complete the following information):**
- 系统Ubuntu 20.04
- 使用Docker, tdengine版本：3.0.1.4

**Comment by yu285** [comment]
建议先把数据库换到3031 ，然后看看数据能否正常查询。 备份下数据文件目录，直接覆盖安装新版本即可。

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
