### ISSUE TITLE
windows 安装TDEengine 编译报错

### ISSUE THREAD

**Issue by lookalook** [taosdata/TDengine#208]
根据最新的博客[如何编译TDengine的Windows客户端]
https://www.taosdata.com/blog/2019/07/26/%e5%a6%82%e4%bd%95%e7%bc%96%e8%af%91tdengine%e7%9a%84windows%e5%ae%a2%e6%88%b7%e7%ab%af/

在执行nmake install  报错
![image](https://user-images.githubusercontent.com/23193340/62002876-7675d300-b13f-11e9-9e88-48c0d0b7b137.png)

有编译通过的小伙伴没，能否发一哈taos.dll

**Comment by sto7** [comment]
1、若timespec重定义，定义宏 HAVE_STRUCT_TIMESPEC；
2、'inet_addr': Use inet_pton() or InetPton() instead，VC选项sdl检查去掉；
3、timezone，daylight未定义，则 int32_t timezone = 8*3600;  int32_t daylight = 0;
然后编译通过。

**Comment by Luozde** [comment]
求分享taos.dll，謝謝

**Comment by plum-lihui** [comment]
已经发布，请到涛思官网下载试用！

**Comment by Ring-k** [comment]
在使用VS编译的时候，遇到 未定义标识符“tzname”，请问该如何解决呢？

**Comment by langxj** [comment]
> 已经发布，请到涛思官网下载试用！

能否给个链接，官司网没找到taos.dll

**Comment by plum-lihui** [comment]
https://www.taosdata.com/cn/getting-started/#Quick Start

**Comment by zh672903** [comment]
在windows环境下我也碰到像你这种一模一样的问题！
