### ISSUE TITLE
how balance vgroups leader

### ISSUE THREAD

**Issue by haoweijia** [taosdata/TDengine#20807]
All the leaders of vgroups in a database in my cluster are on vnode 1. How to distribute the leaders evenly among all Vnodes?
I used the BALANCE VGROUP command to balance, but it didn't work

taos> show vgroups;
  vgroup_id  |            db_name             |   tables    | v1_dnode | v1_status | v2_dnode | v2_status | v3_dnode | v3_status | v4_dnode | v4_status |  cacheload  | tsma |
==============================================================================================================================================================================
           6 | tsp                            |           0 |        1 | leader    |        2 | follower  |        3 | follower  |     NULL | NULL      |           0 |    0 |
           7 | tsp                            |           2 |        1 | leader    |        2 | follower  |        3 | follower  |     NULL | NULL      |           0 |    0 |
           8 | tsp                            |           1 |        1 | leader    |        2 | follower  |        3 | follower  |     NULL | NULL      |           0 |    0 |
Query OK, 3 row(s) in set (0.001831s)

**Comment by yu285** [comment]
![image](https://github.com/taosdata/TDengine/assets/74105241/75732040-97da-4589-815c-db712c661f04)
