### ISSUE TITLE
使用客户端配置文件 taos.cfg 去连接集群 实际参数和文档不一致

### ISSUE THREAD

**Issue by yetaizuo** [taosdata/TDengine#20811]
**Bug Description**
使用客户端配置文件 taos.cfg 去连接集群 实际参数名称和文档不一致

**To Reproduce**
文档V3.0   https://docs.taosdata.com/connector/go/   使用连接器进行连接 DSN支持参数 configPath  指定 taos.cfg 目录
项目 driver-go V3.1.0 实际代码接受的参数名为cfg

**Comment by sangshuduo** [comment]
谢谢指出，已更新文档
