### ISSUE TITLE
TD start failed with core file

### ISSUE THREAD

**Issue by crikayuan** [taosdata/TDengine#20827]
systemclt start taos后过几分钟就断开导致数据采集后无法入库。然后主机内自动建立文件夹如下图所示。core是历史数据吗还是TD建立连接就自创的2.1G存储一千万条时序数据？导致时序数据占用容量太大，或者是生成的日志太多占用了30G的资源。
![73aa5fc3105ecb64278bba472abd19cf2eb4696ff0318caa904536838955a801 0](https://user-images.githubusercontent.com/62696005/230764565-e2e61e67-99d6-4694-9050-def2e8d5e909.PNG)

**Comment by yu285** [comment]
请问版本号是？

**Comment by crikayuan** [comment]
版本是3.0.3.2。然后我再问一下一个超级表最多能存多少条数据，因为数据存储量到100W左右显示无法存库。

**Comment by yu285** [comment]
可以加微信远程一下 a1565223354

**Comment by yu285** [comment]
> 版本是3.0.3.2。然后我再问一下一个超级表最多能存多少条数据，因为数据存储量到100W左右显示无法存库。

不应该出现这个情况，远程看看吧
