### ISSUE TITLE
Java连接器报错找不到本地方法commitCallbackHandler，3.0.3.2TdengineClient Linux版本客户端在Docker容器内无法连接TD服务端

### ISSUE THREAD

**Issue by ryub** [taosdata/TDengine#20826]
**Bug Description**
java.lang.NoSuchMethodError: commitCallbackHandler
 at com.taosdata.jdbc.TSDBJNIConnector.initImp(Native Method)
 at com.taosdata.jdbc.TSDBJNIConnector.init(TSDBJNIConnector.java:43)
 at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:130)

**To Reproduce**
1. 将linux客户端TDengine-client-3.0.3.2-Linux-x64.tar.gz与Springboot程序打包到镜像中启动
附基础镜像打包Dockfile指令如下：

FROM openjdk:8  
LABEL maintainer mingyang  
ADD TDengine-client-3.0.3.2-Linux-x64.tar.gz /opt/  
WORKDIR /opt/TDengine-client-3.0.3.2  
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \  
  echo 'Asia/Shanghai' >/etc/timezone && \  
  /bin/bash install_client.sh

容器内文件能看到驱动是有的
![image](https://user-images.githubusercontent.com/26146463/230752595-67858c85-1f5f-4403-a1b1-12a241f5496a.png)

3. See error
java.lang.NoSuchMethodError: commitCallbackHandler
 at com.taosdata.jdbc.TSDBJNIConnector.initImp(Native Method)
 at com.taosdata.jdbc.TSDBJNIConnector.init(TSDBJNIConnector.java:43)
 at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:130)

![6997990f59e623b3bf098bc188a2f16](https://user-images.githubusercontent.com/26146463/230751739-a25a7ec4-ce71-436f-862a-b6e5323b0052.png)

**Environment (please complete the following information):**
1. Tdengine客户端服务端版本3.0.3.2  
2. taos-jdbcdriver  版本3.1.0
3. 查看了libtaos.so.3.0.3.2文件中是有commitCallbackHandler这个方法的

**Additional Context**
同样的代码，IDEA在Windows本地启动是正常连接数据库使用的
我本人怀疑是taos-jdbcdriver Java连接驱动有问题 没能适配容器环境？

**Comment by huolibo** [comment]
请确认在 docker 环境中使用的 jdbc 版本。

**Comment by ryub** [comment]
> 请确认在 docker 环境中使用的 jdbc 版本。

3.1.0
![image](https://user-images.githubusercontent.com/26146463/230858686-66392508-92fd-453d-b143-022afde9be5c.png)

**Comment by ryub** [comment]
实际上3.0.2以上的版本我都试过了都是相同的报错

**Comment by huolibo** [comment]
我的测试用例：创建一个 maven 环境，pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>demo</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>3.1.0</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>demo</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>com.taos.Demo</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>


</project>
```
com.taos.Demo.java
```
package com.taos;

import java.sql.*;

public class Demo {
    public static void main(String[] args) throws SQLException {
        try (Connection connection = DriverManager.getConnection("jdbc:TAOS://localhost:6030?user=root&password=taosdata");
             Statement statement = connection.createStatement()) {
            ResultSet resultSet = statement.executeQuery("show databases");
            while (resultSet.next()){
                System.out.println(resultSet.getString(1));
            }
            resultSet.close();
        }
    }
}
```
使用 mvn package 打包后，存在 target/demo.jar
在相同路径下创建 Dockerfile:
```
FROM openjdk:8
ADD TDengine-server-3.0.3.2-Linux-x64.tar.gz /opt/
COPY demo/target/demo.jar /tmp/
WORKDIR /opt/TDengine-server-3.0.3.2
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo 'Asia/Shanghai' >/etc/timezone && \
    chmod 555 /tmp/demo.jar

COPY install_client.sh /opt/TDengine-server-3.0.3.2
CMD [ "/bin/bash" ,"/opt/TDengine-server-3.0.3.2/install_client.sh"]
```
在相同路径下创建 install_client.sh:
```
. /opt/TDengine-server-3.0.3.2/install.sh -e no
nohup taosd &
java -jar /tmp/demo.jar
sleep 2
```
创建镜像 docker build -t taos:v1.0.0 .
启动实例：docker run -itd --name=test taos:v1.0.0
查看结果 docker logs -f ***
result 包含:
```
information_schema
performance_schema
```

**Comment by ryub** [comment]
您好 我这个java应用也就是您打包的那个Jar包，连接的不是本地Tdengine服务，而是远程Tdengine服务。您这应该是把td服务端LInux包打到镜像并启动。

**Comment by ryub** [comment]
跟我使用的场景不同啊。我这按钮td服务端也是一个docker容器运行的。这也是我的打包Dockfile只用了Tdengine-client包的原因。
或者您的意思是，即使连接远程服务也是需要在springboot服务镜像中运行一个td服务器？这不太合适吧？ @huolibo
