### ISSUE TITLE
3.0.2.6 The original timestamp of the same SQL query database is inconsistent with the timestamp of the client connection query

### ISSUE THREAD

**Issue by leeleyi** [taosdata/TDengine#20837]
查询脚本：select * from d_1627913589434638338 order by ts desc limit 10;

数据库查询结果：
<img width="437" alt="1681098052962" src="https://user-images.githubusercontent.com/36921703/230821092-27c91b8b-87e2-4967-8cc3-39619704a635.png">

客户端查询结果：
<img width="455" alt="1681098238289" src="https://user-images.githubusercontent.com/36921703/230821456-5317f683-fc7e-403a-b48c-072da1813788.png">

客户端查询出的时间戳比数据库中查询出来的时间戳缺少8小时。

**Comment by yu285** [comment]
这个是时区配置问题，restful 默认返回utc-0 ，url 配置：

https://docs.taosdata.com/connector/rest-api/

<img width="835" alt="image" src="https://user-images.githubusercontent.com/74105241/231922929-92f629d6-dc7a-417a-979c-44e33ca7d270.png">
