### ISSUE TITLE
How can common server users create tables and write data?

### ISSUE THREAD

**Issue by chainder** [taosdata/TDengine#20833]
TDengine安装成功后，利用driver-go可以成功连接到时序库，但是在建表和写入数据的时候，必须要以root用户的身份执行go代码，才能在时序库中建表和写数据入库。请问，需要修改哪个文件的权限才能以普通用户身份执行go代码建表、写入数据？

**Comment by sangshuduo** [comment]
这里的 root 是指 TDengine 的用户不是 Linux 的用户吧？
TDengine 的用户权限管理参考 https://docs.taosdata.com/taos-sql/grant/
