### ISSUE TITLE
tdengine3.2.6 centos connection issue

### ISSUE THREAD

**Issue by ZhangChengJi** [taosdata/TDengine#20847]
![image](https://user-images.githubusercontent.com/36288987/230901777-acb267e1-b12a-44b3-9cb0-a46235327354.png)

**Comment by ZhangChengJi** [comment]
![image](https://user-images.githubusercontent.com/36288987/230902338-2dadf062-3ae1-4d74-b679-6355f93f2f1e.png)

**Comment by yu285** [comment]
连接问题 https://www.taosdata.com/engineering/11076.html 看下问题1 排查一下
