### ISSUE TITLE
windows server 2016 create database failed

### ISSUE THREAD

**Issue by a141178** [taosdata/TDengine#20851]
![image](https://user-images.githubusercontent.com/29970668/231037378-5e7b690f-4ca4-4048-81be-17a2825ff31a.png)
去掉 update 1时能成功创建 
**Environment (please complete the following information):**
 - OS: [windows server 2016]
 - 32GB, Intel(R) Xeon(R) Platinum 8163 CPU @ 2.5GHz 2.5GHz
 - TDengine Version [3.0.3.2]

**Additional Context**

**Comment by yu285** [comment]
3.0 不支持update 参数了，可以看下文档
