### ISSUE TITLE
condition query issue

### ISSUE THREAD

**Issue by wangjian6192** [taosdata/TDengine#20862]
**Bug Description**
条件查询时，用=参数带-无法返回正确结果，like是正常的

**To Reproduce**
1. select count(*) from location where ts > '2023-04-01 00:00:00' and plate_no = 'xx-xxx' and ts < '2023-04-02 00:00:00'
2. select count(*) from location where ts > '2023-04-01 00:00:00' and plate_no like 'xx-xxx' and ts < '2023-04-02 00:00:00'

**Comment by yu285** [comment]
请问版本号是

**Comment by wangjian6192** [comment]
3032

**Comment by yu285** [comment]
![image](https://github.com/taosdata/TDengine/assets/74105241/0e450054-b093-4787-bd61-3f3aa480aed8)

请升级到当前最新版本，3.3.0.3
