### ISSUE TITLE
UDF ERROR can not spawn udfd. path: taosd/udfd, error: no such file or directory

### ISSUE THREAD

**Issue by sanmv** [taosdata/TDengine#20871]
**Bug Description**
在K8s集群内部署了tdengine3.0.0.0版本，运行一段时间之后容器一直在尝试重启，容器内报错
` 04/11 16:27:31.812615 00000226 DND start to init dnode env

 04/11 16:27:31.812700 00000226 DND dnode will run in single-process mode
 04/11 16:27:31.813859 00000226 DND dnode env is initialized
 04/11 16:27:31.813868 00000226 DND start to init service
 04/11 16:27:31.813882 00000226 DND node:dnode, start to open
 04/11 16:27:31.813891 00000226 UTL worker:dnode-mgmt is initialized, min:1 max:1
 04/11 16:27:31.814112 00000237 UDF start to init udfd
 04/11 16:27:31.815644 00000237 UDF ERROR can not spawn udfd. path: taosd/udfd, error: no such file or directory
 04/11 16:27:31.815756 00000226 UDF udfd is cleaned up after spawn err
 04/11 16:27:31.815769 00000226 DND ERROR failed to start udfd
 04/11 16:27:31.815776 00000226 DND node:dnode, has been opened
 04/11 16:27:31.815789 00000226 DND node:vnode, start to open
 04/11 16:27:31.815927 00000226 WAL wal module is initialized, rsetId:3
 04/11 16:27:31.816396 00000226 UTL worker:vnode-query is initialized, min:256 max:256
 04/11 16:27:31.816408 00000226 UTL worker:vnode-stream is initialized, min:32 max:32
 04/11 16:27:31.816432 00000226 UTL worker:vnode-mgmt is initialized, min:1 max:1
 04/11 16:27:31.816517 00000226 UTL worker:vnode-monitor is initialized, min:1 max:1
 04/11 16:27:31.816762 00000226 DND open 1 vnodes with 64 threads
 Segmentation fault (core dumped)`
我看到帖子是说升级版本会出现这个问题，但是我的环境没有升级版本为什么产生这个报错呢？

**Comment by yu285** [comment]
3000 是初始版本，已经回收了，和如今版本不兼容。咱们直接切换到 3032 吧

**Comment by sanmv** [comment]
直接切换是不是还是需要清理一下数据？

**Comment by yu285** [comment]
是的。
