### ISSUE TITLE
delete operation leads to crash

### ISSUE THREAD

**Issue by trytowish** [taosdata/TDengine#20898]
taos> select * from yc_28634 2 where ts  2023-04-09 05:18:17.000
ts                                          |                val               |
=================================
2023-04-09 05:18:17.000     |            0.000000000   | 
OK,1 row(s) in set(0.027000s)

taos> delete from yc_28634 2 where ts =2023-04-09 05:18:17.000
Delete 0K，9 row(s) affected (0.008000s)

**Comment by trytowish** [comment]
04/13 08:57:29.308516 00000104 SYN ERROR vgId:3, sync leader failed to sync propose since not ready, type:submit, last:230193777, cmt:230193777, term:374, commit-index:230193777, first-ver:230067275, last-ver:230193777, min:-1, snap:230148554, snap-term:370, elect-times:0, as-leader-times:1, cfg-ch-times:0, hit:0, mis:0, hb-slow:0, hbr-slow:0, aq-items:20048, snaping:-1, replicas:1, last-cfg:-1, chging:0, restore:0, quorum:1, elect-lc-timer:1, hb:0, {0:-1 0}, {r-num:1, my:0, td1:6030}, hb:{0:1681347443507}, hbr:{0:1681347443507}
04/13 08:57:29.308468 00000103 SYN ERROR vgId:2, sync leader failed to sync propose since not ready, type:submit, last:234108658, cmt:234108658, term:374, commit-index:234108658, first-ver:233978317, last-ver:234108658, min:-1, snap:234055488, snap-term:370, elect-times:0, as-leader-times:1, cfg-ch-times:0, hit:0, mis:0, hb-slow:0, hbr-slow:0, aq-items:27962, snaping:-1, replicas:1, last-cfg:-1, chging:0, restore:0, quorum:1, elect-lc-timer:1, hb:0, {0:-1 0}, {r-num:1, my:0, td1:6030}, hb:{0:1681347443507}, hbr:{0:1681347443507}

**Comment by trytowish** [comment]
04/13 08:57:29.312081 00000104 VND ERROR vgId:3, msg:0x7fc64c000e78 failed to propose since Sync not ready for propose, code:0x80000911, gtid:0xb760011e11dbc3a8:0x6113781e1134882

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
