### ISSUE TITLE
请教一下,关于社区版的免费,开源是指哪方面呢

### ISSUE THREAD

**Issue by pigwing** [taosdata/TDengine#209]
请问,社区版的免费和开源是只哪方面呢?我看AGPL是一个非常严格的开源协议,连调用RPC都会被感染,需要把所有相关程序都开源.

**Comment by huijimuhe** [comment]
公关稿开源

**Comment by jtao1735** [comment]
采用AGPL的主要目的是为了防止云厂商利用开源代码提供服务，独占利润。另一方面，我们鼓励大家都开源。
