### ISSUE TITLE
data subscription issue

### ISSUE THREAD

**Issue by xiahejun** [taosdata/TDengine#20907]
版本：3.0.2.5
问题：使用如下语句订阅时无法获取tbname字段，所以无法反序列化。

"create topic " + TOPIC + " as select tbname ,ts,current,voltage,groupid,location from meters

跟踪源码发现rs的元数据如下图：
![1c9f490f3fb0ee6552254402484e9ab](https://user-images.githubusercontent.com/54968493/231667222-1e326e4f-79da-4b36-aca1-4273380d3ea7.png)

**Comment by ntucz** [comment]
你就用#expr_1忍受吧，ε=(´ο｀*)))唉
最反感的是1）不支持poll批量获取，2）poll不支持阻塞，什么数据都没有，还一个劲的返回

**Comment by xiahejun** [comment]
> 你就用#expr_1忍受吧，ε=（'ο'*）））唉 最反感的是1）不支持poll批量获取，2）poll不支持阻塞，什么数据都没有，还一个劲的返回

就感觉是一个假的数据订阅，还是需要一直查询数据。

**Comment by yu285** [comment]
现在已经支持了。

另外 3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
