### ISSUE TITLE
create connection failed in REST way

### ISSUE THREAD

**Issue by haoweijia** [taosdata/TDengine#20939]
Class.forName("com.taosdata.jdbc.rs.RestfulDriver");
        String jdbcUrl = "jdbc:TAOS-RS://xxxxxxx:6041/tsp?user=root&password=taosdata";
        Properties connProps = new Properties();
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_BATCH_LOAD, "true");
        Connection conn = DriverManager.getConnection(jdbcUrl, connProps);

使用 rest 创建连接，由于有网络的限制，开通了 6041的端口，但是创建连接报错。
Exception in thread "main" java.sql.SQLException: can't create connection with server
	at com.taosdata.jdbc.rs.RestfulDriver.connect(RestfulDriver.java:120)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at com.ifyou.optimize.flink.RestTest.main(RestTest.java:22)

检查 taosadapter 日志，提示如下错：

TAOS_ADAPTER info "| 200 |  9.621817648s |  10.246.155.177 | GET | /rest/ws " model=web sessionID=11
04/14 17:58:34.369885 00007822 TAOS_ADAPTER error "ws error" sessionID=12 wsType=query error=read tcp {taosadapterIP}:6041->{访问ip}:62382: read: connection reset by peer model=restful

是否因为taosadapter 又向 客户端创建了tcp 链接的请求，但是由于网络的限制，链接无法创建，导致rest jdbc 链接创建失败。

**Comment by sangshuduo** [comment]
taosadapter 是通过 taosc 6030 端口和 taosd 建立连接的

**Comment by NoFlyLonely** [comment]
mac M3上用docker安装tdengine后，容器里访问没有问题，宿主机器使用dbeaver连接报connection reset
