### ISSUE TITLE
why  mongodb use less storage space  than tdengine?

### ISSUE THREAD

**Issue by wuzhoushidao** [taosdata/TDengine#20930]
**Performance Issue** 
Any questions related to TDengine's performance can be discussed here.

**Problem Description** 
A clear and concise description of what the problem is.

**To Reproduce**
1. Database parameters used: 
 ```show databases```
2. Verbs used: Insert/Import/Select?
3. Describe the total amount of data
4. Observed performance vs. expected performance

**Screenshots**
![image](https://user-images.githubusercontent.com/30689840/231920923-1732f6e2-22d4-4c30-957c-7a9af44e1dff.png)
12小时占用24g，mongodb只占用了5g

**Environment (please complete the following information):**

* OS: [e.g. CentOS 7.0]
* Memory, CPU, current Disk Space
* TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by yu285** [comment]
版本号是？ 

cd 到 vnode下面 ，ls -ltR 看看

**Comment by wuzhoushidao** [comment]
版本号3.0.2.5 
![image](https://user-images.githubusercontent.com/30689840/231923005-1a3bf285-eb44-4732-b18a-245628da4f5b.png)
![image](https://user-images.githubusercontent.com/30689840/231923049-b14b657f-2c78-41df-9313-2141bbe7c7e1.png)
![image](https://user-images.githubusercontent.com/30689840/231923110-0f12eb2b-7b62-4715-a82a-4e57a87da6cb.png)

**Comment by yu285** [comment]
可以确认下，是不是每个 tsdb 目录下的 .data 文件占用最多？

**Comment by wuzhoushidao** [comment]
目前运行几天之后，存储空间比mongodb小了，第一天为什么占用24g不清楚，运行到今天只加了10g
