### ISSUE TITLE
out of sync node can't be started

### ISSUE THREAD

**Issue by dragon-ym** [taosdata/TDengine#20945]
环境：

3节点集群工作一段时间后，有一个节点故障长时间未发现，导致故障节点数据落后
节点        已写数据量
td0           400G
td1           400G
td2(故障)  50G

操作步骤：
1.重启故障节点td2

现象：
td2 节点 cpu 长期 400%
集群服务异常，读写间歇性失败(此时td2 dnode 状态 ready)
为保证集群服务正常，停掉了td2 节点，停掉之后集群读写正常

td2 日志报错
![image](https://user-images.githubusercontent.com/70568868/232266421-c5b38724-e7d8-4175-9258-e245bdbe62a9.png)

尝试调整 rpcQueueMemoryAllowed 参数
![image](https://user-images.githubusercontent.com/70568868/232266544-0c9a53ec-5efc-4924-9397-014de52b302e.png)
调整后 taosd 无法正常启动，报错参数 out of range
![image](https://user-images.githubusercontent.com/70568868/232266622-972868d5-50b4-4ec0-a8f3-8bbb5801166e.png)

尝试drop dnode td2，但是 td2 当前状态 offline ,无法drop

目前集群2个节点在正常提供服务，td2 不知道要如何恢复

**Comment by dragon-ym** [comment]
补充一下版本信息：3.0.2.6

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
