### ISSUE TITLE
Tdengine Server unexpectedly restarted

### ISSUE THREAD

**Issue by mathink-ma** [taosdata/TDengine#20957]
**Bug Description**
Server unexpectedly restarted  when order by data

**To Reproduce**
1. Create databases; 
```CREATE DATABASE IF NOT EXISTS test4 PRECISION 'us';```
2. Insert Data
(Influx Line Prtocol )``` "自控,param_name=iv53d8mwjs,sn=cigapi param_value="-276696288" 1681791979920" ```
Insert About 1milion
3. Select Data
``` select * from `自控` order by _ts desc limit 10; ```

**Expected Behavior**
Obtaining correct data

**Screenshots**
![image](https://user-images.githubusercontent.com/28838804/232671677-44c249b6-1342-4b65-b410-07d90617dcd5.png)
<img width="578" alt="1681792214358" src="https://user-images.githubusercontent.com/28838804/232671753-801a7bf1-615b-452a-87a3-899d351e4049.png">

**Environment (please complete the following information):**
OS:  CentOS 7.9
Memory 4GB,  4 vCPUs, 70GB current Disk Space
 - TDengine Version Lastest
 - 
**Additional Context**
None

**Comment by sangshuduo** [comment]
TDengine 什么版本？可以上传 taosdlog 吗？

**Comment by MaConch** [comment]
TDengine  Version： 3.0.4.0
[taosdlog.zip](https://github.com/taosdata/TDengine/files/11258228/taosdlog.zip)

**Comment by sangshuduo** [comment]
可以在同一台机器上用 top 监控一下 taosd 进程内存占用情况，并执行相同操作，看是不是内存耗尽 OOM 被系统 kill 掉了

**Comment by MaConch** [comment]
内存耗尽后系统kill了pid，这个问题应该如何处理

**Comment by MaConch** [comment]
这个只在排序 主键ts列时候出现，其它列都没问题

**Comment by sangshuduo** [comment]
> 这个只在排序 主键ts列时候出现，其它列都没问题

已知问题，在修复中，请暂时不要使用这个查询，或者增加内存
