### ISSUE TITLE
taosdump failed （ERROR: fillDbExtraInfoV3Native() LN11894  code: -2147483637, reason: Unable to establish connection）

### ISSUE THREAD

**Issue by wuzhoushidao** [taosdata/TDengine#20968]
**Bug Description**

taosdump 导出数据时，
ERROR: fillDbExtraInfoV3Native() LN11894, failed to run command <SELECT COUNT(table_name) FROM information_schema.ins_tables WHERE db_name='hitedmcp'>. code: -2147483637, reason: Unable to establish connection

**Screenshots**
![image](https://user-images.githubusercontent.com/30689840/232752750-4be4c88d-bde5-494d-a4be-2c7956e611ec.png)

**Environment (please complete the following information):**
 - OS: [ CentOS 7.0]
 - TDengine Version [3.0.2.5]
 - taosTools [2.4.9]

**Comment by sangshuduo** [comment]
Unable to establish connection 是连接问题，猜测用 taos shell 连接同样的 host 和端口也会失败

**Comment by wuzhoushidao** [comment]
taos连接没有问题，
![image](https://user-images.githubusercontent.com/30689840/232755304-b76bf27d-7b04-47bd-adec-c278361d8f15.png)

**Comment by wuzhoushidao** [comment]
执行这个sql确实不行
![image](https://user-images.githubusercontent.com/30689840/232755794-9fa5543a-773c-4960-b163-c76a2d56a0c1.png)

**Comment by wuzhoushidao** [comment]
那这是什么原因导致的，应该怎么处理

**Comment by sangshuduo** [comment]
> 那这是什么原因导致的，应该怎么处理

试试服务端不用 systemctl ，在 terminal 中用命令行 sudo taosd ，taos shell 再进行查询，看 taosd 是不是有什么问题

**Comment by wuzhoushidao** [comment]
服务端运行是可以的
![image](https://user-images.githubusercontent.com/30689840/232771837-39a5d4a0-c39e-44e6-97fc-5a572d4b2375.png)
而且我用6041端口也是没有问题，原生连接不行

**Comment by sangshuduo** [comment]
> 服务端运行是可以的 ![image](https://user-images.githubusercontent.com/30689840/232771837-39a5d4a0-c39e-44e6-97fc-5a572d4b2375.png) 而且我用6041端口也是没有问题，原生连接不行

我的意思是服务端机器 A 运行 taosd，但不用 systemctl，而是直接 sudo taosd，客户端机器 B 上使用 taos shell 执行这个 SQL，看 A 上的 taosd 输出什么？

**Comment by wuzhoushidao** [comment]
我是安装在docker里面，数据映射在外部，执行taosd后，
![image](https://user-images.githubusercontent.com/30689840/232945162-c6d6dfce-f9d6-43b1-8de2-328091871511.png)

**Comment by sangshuduo** [comment]
先解决连接问题吧，这个问题和 taosdump 无关
