### ISSUE TITLE
taos.error.SchemalessError: [0x0203]: Invalid value in client(affected rows: 0)

### ISSUE THREAD

**Issue by SalYelBirch** [taosdata/TDengine#20975]
在基于Schemaless 插入的场景下，间隔10秒插入一次，除时间戳外数据一致，周期性报错 Invalid value in client
version: 3.0.3.2
完整报错信息
```python
Traceback (most recent call last):
  File "C:\Users\Desktop\salyelbirch\git\stellar_edge_service\src\app\core\connector\connector.py", line 207, in _read_data
    _af_row = self.td_conn.schemaless_insert(schemaless_lines, SmlProtocol.LINE_PROTOCOL, SmlPrecision.SECONDS)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\taos\connection.py", line 174, in schemaless_insert
    return taos_schemaless_insert(self._conn, lines, protocol, precision)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\taos\cinterface.py", line 947, in taos_schemaless_insert
    raise SchemalessError(errstr, errno, affected_rows)
taos.error.SchemalessError: [0x0203]: Invalid value in client(affected rows: 0)
```

**Comment by SalYelBirch** [comment]
当报错后直接以相同数据重试，95%以上能在一次重试后插入成功
```python
        while schemaless_insert_cnt < 5:
            try:
                _af_row = self.td_conn.schemaless_insert(schemaless_lines, SmlProtocol.LINE_PROTOCOL, SmlPrecision.SECONDS)
            except SchemalessError as se:
                error(f"=======================Insert data failed!Reason: {se.args}")
                continue
            break
        info(f"Read data total insert rows: {len(schemaless_lines)}, affected: {_af_row}")
```

```shell
[ERROR][2023-04-19 14:34:12,002] - connector  - =======================Insert data failed!Reason: ('Invalid value in client', -2147483133, 0)
[INFO][2023-04-19 14:34:12,123] - connector  - Read data total insert rows: 4, affected: 4
```

**Comment by sangshuduo** [comment]
在 taos.cfg 中打开 debugFlag 135，清除日志，再执行一下，然后把 taoslog 日志上传到 GitHub issue 上

**Comment by SalYelBirch** [comment]
[log.tar.gz](https://github.com/taosdata/TDengine/files/11338780/log.tar.gz)
@sangshuduo

**Comment by wangmm0220** [comment]
> [log.tar.gz](https://github.com/taosdata/TDengine/files/11338780/log.tar.gz) @sangshuduo

需要的是client端的日志，发的是服务端taosd的日志。

**Comment by SalYelBirch** [comment]
[taoslog.0.log](https://github.com/taosdata/TDengine/files/11338947/taoslog.0.log)
@wangmm0220

**Comment by wangmm0220** [comment]
10:20:05.976918 00060232 UTL ERROR SML:0xe point type and db type mismatch. key: pcs_power=62891, 1682561999. point type: 12, db type: 7
04/27 10:20:05.976918 00090704 UTL ERROR SML:0xf point type and db type mismatch. key: pcs_power=10590, 1682561999. point type: 12, db type: 7

是不是手动建表了？  库里pcs_power这个字段是usigned small int，行协议自动解析是double，所以报错。 行协议不建议用户自己建表
![JYpUhDeC25](https://user-images.githubusercontent.com/6055324/234747157-441e7d9b-e916-48fa-a9e9-ff61a20fc1d5.jpg)

**Comment by SalYelBirch** [comment]
没有自动建表，就是在一开始插入的时候会有指定u16的数据写入一次
疑惑的是 写入 37203 这样不带小数点的数据也会被解析为double类型吗，还是所有未标明的数据全部按照double解析。

**Comment by wangmm0220** [comment]
> 没有自动建表，就是在一开始插入的时候会有指定u16的数据写入一次 疑惑的是 写入 37203 这样不带小数点的数据也会被解析为double类型吗，还是所有未标明的数据全部按照double解析。

没有指定的数据都是double类型，兼容linflux db的航协议
https://docs.taosdata.com/reference/schemaless/#%E6%97%A0%E6%A8%A1%E5%BC%8F%E5%86%99%E5%85%A5%E8%A1%8C%E5%8D%8F%E8%AE%AE
