### ISSUE TITLE
Data Subscription Problem in TD3.0

### ISSUE THREAD

**Issue by ntucz** [taosdata/TDengine#20974]
1. consumer.poll为何做不到阻塞，subQuery没有数据，也频繁返回，约0.1s一次的返回。
2. 使用期间发生错误（taosjdbc 3.1.0）：
java.sql.SQLException: java.util.concurrent.TimeoutException: websocket connection reached the max number of concurrent requests
        at com.taosdata.jdbc.ws.Transport.send(Transport.java:59)
        at com.taosdata.jdbc.ws.tmq.WSConsumer.poll(WSConsumer.java:91)
        at com.taosdata.jdbc.tmq.TaosConsumer.poll(TaosConsumer.java:93)

**Comment by ntucz** [comment]
针对问题2，难道我要把consumer经常关闭订阅，然后再开启？

**Comment by huolibo** [comment]
1. 目前 websocket 设计 poll 最长阻塞 1s。
以下为订阅空表，poll 前后打印的时间戳。
```
0 poll: 2023-04-20 14:16:55.039
0 end poll 2023-04-20 14:16:56.052
1 poll: 2023-04-20 14:16:56.052
1 end poll 2023-04-20 14:16:57.057
...
```
3. 可用过 properties.setProperty("httpPoolSize", "100"); 参数控制，默认 20 个并行请求。
