### ISSUE TITLE
insert issue in 3.0.4.0 

### ISSUE THREAD

**Issue by yh724** [taosdata/TDengine#20979]
**Bug Description**
在测试过程中，插入不同时间的数据会报不同的错误，我不是很明白为什么插入数据会报 Table already exists 错误，而且第1、4条插入语句一致为什么会产生不同的错误。

**Screenshots**
![image](https://user-images.githubusercontent.com/56058380/232993475-0eabe86c-2e90-40cd-9f19-b646cd837b7f.png)

**Environment (please complete the following information):**
 - OS:  服务端Ubuntu 18.04.1 LTS 客户端 win11
 - Memory, CPU, current Disk Space
 - TDengine Version 3.0.4.0

**Comment by yu285** [comment]
我远程看下吧，微信：a15652223354

**Comment by blingzr** [comment]
insert into xxx_38_0 (ts,uid,`balance`, currency,created_time,updated_time,version) USING xxx TAGS(38,0) values (1682617660683000000,123,'94.00533765', 'CNY',1682616787942000000,1682617660683000000,145);
这样也会提示 “Table already exists ”， 但不是必现！

**Comment by sangshuduo** [comment]
> insert into xxx_38_0 (ts,uid,`balance`, currency,created_time,updated_time,version) USING xxx TAGS(38,0) values (1682617660683000000,123,'94.00533765', 'CNY',1682616787942000000,1682617660683000000,145); 这样也会提示 “Table already exists ”， 但不是必现！

可以单独提一个 issue，附上版本信息，复现步骤，和日志

**Comment by zeje** [comment]
我在3.0.3.0上遇到这个问题，正好想着说升级版本会不会也这样。先升到3.0.4.1看看，
![00461A98](https://github.com/taosdata/TDengine/assets/10680634/a84c883c-b7c1-4edb-bb3c-68cc8e4b0f56)

**Comment by wb2712** [comment]
我也遇到了  TDClientInfo 3.0.5.0 TDServerInfo ver:3.0.5.0
SQL 错误 [1539]: TDengine ERROR (0x603): sql: INSERT into device_3011_9 (ts, float32_type) VALUES(1690442527573000, 13907.150391), desc: Table already exists

**Comment by wb2712** [comment]
> 我也遇到了 TDClientInfo 3.0.5.0 TDServerInfo ver:3.0.5.0 SQL 错误 [1539]: TDengine ERROR (0x603): sql: INSERT into device_3011_9 (t​​s, float32_type) VALUES(1690442527573000, 13907.150391), desc: 表已存在

多表批量插入时，参数错误了， （猜测 错误码不对）
