### ISSUE TITLE
2.4.20 query issue

### ISSUE THREAD

**Issue by MonkeyBrothers** [taosdata/TDengine#20987]
**问题**
我向已经存在的一张表 新增加一个BOOL 的字段类型 名字叫做 flag，后续查询的时候发现之前的历史数据都是 null。
我根据我插入的数据过滤 select * from table where flag = 1;  发现null的值并不能被过滤掉。
**版本**
2.4.20

**Comment by MonkeyBrothers** [comment]
使用的版本为 2.4.20

**Comment by yu285** [comment]
应该是当时版本的问题，我在3.0.4.0 没有这个问题：

![image](https://user-images.githubusercontent.com/74105241/233559352-ea48f77b-7333-49d3-a218-9a004d499c0e.png)

**Comment by MonkeyBrothers** [comment]
> 应该是当时版本的问题，我在3.0.4.0 没有这个问题：
> 
> ![image](https://user-images.githubusercontent.com/74105241/233559352-ea48f77b-7333-49d3-a218-9a004d499c0e.png)

非常感谢，已经和集团沟通确认过，后续会通过升级版本解决。
