### ISSUE TITLE
客户端连接查询问题

### ISSUE THREAD

**Issue by wupeng1234** [taosdata/TDengine#20986]
您好，TDengine 团队：

我这边用 Docker 构建了一个包含 taos 客户端的基础镜像，内容如下：
FROM centos:7

######## 指定进入容器的落脚点目录
ENV TDENGINE_VERSION=3.0.2.5
ENV MYPATH /usr/local
WORKDIR $MYPATH

######## 设置时区
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

####### 创建新目录
RUN mkdir /usr/local/java

######## 将压缩文件复制到镜像中，它将自动解压缩 tar 文件
ADD jdk-11_linux-x64_bin.tar.gz /usr/local/java/
ADD TDengine-client-${TDENGINE_VERSION}-Linux-x64.tar.gz /usr/local/

######### 安装 TDengine 客户端
RUN cd TDengine-client-${TDENGINE_VERSION} && ./install_client.sh

########### 设置环境变量
ENV JAVA_HOME /usr/local/java/jdk-11
ENV PATH $JAVA_HOME/bin:$PATH

EXPOSE 80

CMD echo $MYPATH
CMD echo "jdk11 success--------------ok"
CMD /bin/bash
###############################################
进入镜像后能连接服务端，就是在执行 select 的语句的时候会报错：
DB error: Fail to get table info, error: Sync not leader (10.955366s)

之后我又执行 show vgroups; show mnodes; 都是正常的，之前在技术群里咨询过，可也没有给到一个解决方案，现在确实要上线，有些急，麻烦帮忙解决一下吧，十分感谢

**Comment by sangshuduo** [comment]
可以参考一下 TDengine 官方 Dockerfile https://github.com/taosdata/TDengine/blob/main/packaging/docker/Dockerfile

**Comment by wupeng1234** [comment]
> 可以参考一下 TDengine 官方 Dockerfile https://github.com/taosdata/TDengine/blob/main/packaging/docker/Dockerfile

您好，问题已解决，是因为我配置 host 的问题，感谢！
