### ISSUE TITLE
Caused by: java.lang.UnsatisfiedLinkError: /usr/lib/libtaos.so.3.0.4.0: libjemalloc.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lazyz-zk** [taosdata/TDengine#20988]
**Bug Description**

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/106313759/233267266-6e726107-0bad-4de6-a390-7ba6970bd06c.png)

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by sangshuduo** [comment]
Could you please let me know what package format you installed? And where did you download it from? Thanks.

**Comment by lazyz-zk** [comment]
Docker安装的，代码本地测试可以连上数据库，部署到服务器就报错了

**Comment by sangshuduo** [comment]
> Docker安装的，代码本地测试可以连上数据库，部署到服务器就报错了

部署到服务器具体是怎么部署的？部署的是官方安装包吗？

**Comment by sangshuduo** [comment]
> 代码是把jar包用Dockerfile打成的镜像，部署在服务器的。数据库是拉的官方镜像，搭的3节点集群。 问题是：代码本地跑可以连上数据库，部署到服务器连数据库就报如上错误。

Docker 镜像里有没有装官方客户端安装包？

**Comment by lazyz-zk** [comment]
![image](https://user-images.githubusercontent.com/106313759/233306329-f58ab823-2d42-49ac-89a9-104e524fc65f.png)


> > 代码是把jar包用Dockerfile打成的镜像，部署在服务器的。数据库是拉的官方镜像，搭的3节点集群。 问题是：代码本地跑可以连上数据库，部署到服务器连数据库就报如上错误。
> 
> Docker 镜像里有没有装官方客户端安装包？
麻烦您看下这样是否可以？我把linux客户端的dirver复制到了镜像里
![image](https://user-images.githubusercontent.com/106313759/233306385-6fd8acf7-00f0-42aa-8df1-4f5bf8354a56.png)
![image](https://user-images.githubusercontent.com/106313759/233306770-15e10278-696f-4a51-a640-17a1a51744e0.png)

**Comment by sangshuduo** [comment]
> ![image](https://user-images.githubusercontent.com/106313759/233306329-f58ab823-2d42-49ac-89a9-104e524fc65f.png)
> 
> > > 代码是把jar包用Dockerfile打成的镜像，部署在服务器的。数据库是拉的官方镜像，搭的3节点集群。 问题是：代码本地跑可以连上数据库，部署到服务器连数据库就报如上错误。
> > 
> > 
> > Docker 镜像里有没有装官方客户端安装包？
> > 麻烦您看下这样是否可以？我把linux客户端的dirver复制到了镜像里
> > ![image](https://user-images.githubusercontent.com/106313759/233306385-6fd8acf7-00f0-42aa-8df1-4f5bf8354a56.png)
> > ![image](https://user-images.githubusercontent.com/106313759/233306770-15e10278-696f-4a51-a640-17a1a51744e0.png)

不能只复制 libtaos.so 还有 libjemalloc 的相关文件。建议在 Dockerfile 里使用官方客户端安装包解压后使用官方脚本安装

**Comment by lazyz-zk** [comment]
已解决

**Comment by shi0513** [comment]
> 已解决

能分享一下解决方式吗，我也遇到了 我java是用docker部署的 也挂载了libjemalloc  依然是这个错

**Comment by lazyz-zk** [comment]
> > 已解决
> 
> 能分享一下解决方式吗，我也遇到了 我java是用docker部署的 也挂载了libjemalloc 依然是这个错

不能只挂载libjemalloc，我直接在Dockfile里安装的taos客户端

**Comment by shi0513** [comment]
> > > 已解决
> > 
> > 
> > 能分享一下解决方法吗，我也遇到了我java是用docker部分包的也挂载了libjemalloc 仍然是这个错误
> 
> 不能只挂载libjemalloc，我直接在Dockfile里安装的taos客户端

能加一下微信么   客户端 安装不进去 我想看看你是怎么加进去的  这是我的微信13547843211

**Comment by wenfengSAT** [comment]
> > > 已解决
> > 
> > 
> > 能分享一下解决方式吗，我也遇到了 我java是用docker部署的 也挂载了libjemalloc 依然是这个错
> 
> 不能只挂载libjemalloc，我直接在Dockfile里安装的taos客户端

大佬，可以把解决后的Dockfile分享部分出来对比下吗？我也遇到同样的问题~

**Comment by WenshuaiXie** [comment]
![image](https://github.com/taosdata/TDengine/assets/77595766/95722073-07d6-4482-b839-cc1409119c29)
已解决
