### ISSUE TITLE
按聚合查询时，当聚合周期为多天时，起始时间不够准确

### ISSUE THREAD

**Issue by sto7** [taosdata/TDengine#210]
例如：select avg(a) from t  where ts >= '2018-01-01 0:0:0' interval(1n);
1n应该是一个月，实际上和30d效果等同；
统计周期不是按每月的1日开始，并且查询时间>2018.1.1，第一个数据则是从2017.12.20开始；
=================================================
 17-12-20 00:00:00.000|              5.501736111|
 18-01-19 00:00:00.000|              5.500514660|
 18-02-18 00:00:00.000|              5.497636960|
 18-03-20 00:00:00.000|              5.500069830|
 18-04-19 00:00:00.000|              5.501271991|
 18-05-19 00:00:00.000|              5.501008873|
 18-06-18 00:00:00.000|              5.502202932|
 18-07-18 00:00:00.000|              5.502309028|
 18-08-17 00:00:00.000|              5.499267747|
 18-09-16 00:00:00.000|              5.497895448|
 18-10-16 00:00:00.000|              5.498680941|
 18-11-15 00:00:00.000|              5.498341435|
 18-12-15 00:00:00.000|              5.498686683|
Query OK, 13 row(s) in set (0.094000s)
=================================================
另在笔记本联想x1 win10的centos7虚拟机中，写入速度每秒接近10w次，非常理想了已经；
聚合一年数据（每秒存一个）3150万数据，速度很快；
windows下使用python时，加载的libtaos.so，将taos.dll改名，即可用；
软件非常优秀，持续测试和关注中，感谢作者。

**Comment by hjxilinx** [comment]
是的，现在按照时间区间聚合还无法做到自然年、自然月的精确匹配，后面我们修复这个问题。

**Comment by nonamexz** [comment]
这个bug的修复有没有具体的时间计划呢？必竟按天以上的维度做数据聚合的场景还是蛮多的。

**Comment by guanshengliang** [comment]
争取在本周修复
