### ISSUE TITLE
smlChildTableName isnot working if i use client-3.0.4.0-Linux to write schemaless line

### ISSUE THREAD

**Issue by wangyongalfred** [taosdata/TDengine#21009]
server:
os-->CentOS Linux release 8.5.2111
tdengine server --> docker , image:tdengine/tdengine:3.0.4.0
taos.cfg --> smlChildTableName  group

=============test1 client===========
1.maven:
<dependency>
    <groupId>com.taosdata.jdbc</groupId>
    <artifactId>taos-jdbcdriver</artifactId>
    <version>3.0.4</version>
</dependency>

2.client:
TDengine-client-3.0.4.0-Windows-x64.exe

3. line:
m4,group=test s111=136i16 1682046003000000

result:success
stable:m4
table:test

//drop stable m4 if exist
=============test2 client===========
1.maven:
<dependency>
    <groupId>com.taosdata.jdbc</groupId>
    <artifactId>taos-jdbcdriver</artifactId>
    <version>3.0.4</version>
</dependency>

2.client:
TDengine-client-3.0.4.0-Linux-x64.tar.gz

3. line:
m4,group=test s111=136i16 1682046003000000

result:fail
stable:m4
table:t_(md5 value)  -->   should be 'test'

**Comment by yu285** [comment]
需要配置到客户端的taos.cfg
