### ISSUE TITLE
regarding to the license of TDengine 

### ISSUE THREAD

**Issue by temperta** [taosdata/TDengine#21003]
TDEngine使用AGPL3.0协议开源
对于其中的数据库驱动部分，是否也是AGPL3.0协议，还是其他的协议或者是AGPL3.0协议加上例外

**Comment by sangshuduo** [comment]
> TDEngine使用AGPL3.0协议开源 对于其中的数据库驱动部分，是否也是AGPL3.0协议，还是其他的协议或者是AGPL3.0协议加上例外

如果你说的驱动指  libtaos.so ，还是 AGPL 协议。如果需要例外处理，请联系商务团队。

**Comment by temperta** [comment]
> 

如果我的程序链接到了libtaos，那么按照AGPL3.0我的应用程序也是需要使用AGPL3.0协议进行开源。我这样理解有错误吗

**Comment by sangshuduo** [comment]
> 如果我的程序链接到了libtaos，那么按照AGPL3.0我的应用程序也是需要使用AGPL3.0协议进行开源。我这样理解有错误吗

是的，链接了动态库需要开源。你也可以选择使用 REST 或者 WebSocket 接口，就不需要开源了

**Comment by temperta** [comment]
> > 如果我的程序链接到了libtaos，那么按照AGPL3.0我的应用程序也是需要使用AGPL3.0协议进行开源。我这样理解有错误吗
> 
> 是的，链接了动态库需要开源。你也可以选择使用 REST 或者 WebSocket 接口，就不需要开源了

对于libtaos，是否有意向切换到类似于mysql的数据库客户端库类似的模式，如果仅仅只是作为库链接到应用程序，不涉及到代码的修改，可做为一个例外项，此种情况不需要开源应用程序的代码。

**Comment by sangshuduo** [comment]
> > > 如果我的程序链接到了libtaos，那么按照AGPL3.0我的应用程序也是需要使用AGPL3.0协议进行开源。我这样理解有错误吗
> > 
> > 是的，链接了动态库需要开源。你也可以选择使用 REST 或者 WebSocket 接口，就不需要开源了
> 
> 对于libtaos，是否有意向切换到类似于mysql的数据库客户端库类似的模式，如果仅仅只是作为库链接到应用程序，不涉及到代码的修改，可做为一个例外项，此种情况不需要开源应用程序的代码。

你说的是 LGPL 协议吧。我只能回答当前状态，公司管理层是否有其他决策，我回答不了

**Comment by temperta** [comment]
> > > > 如果我的程序链接到了libtaos，那么按照AGPL3.0我的应用程序也是需要使用AGPL3.0协议进行开源。我这样理解有错误吗
> > > 
> > > 
> > > 是的，链接了动态库需要开源。你也可以选择使用 REST 或者 WebSocket 接口，就不需要开源了
> > 
> > 
> > 对于libtaos，是否有意向切换到类似于mysql的数据库客户端库类似的模式，如果仅仅只是作为库链接到应用程序，不涉及到代码的修改，可做为一个例外项，此种情况不需要开源应用程序的代码。
> 
> 你说的是 LGPL 协议吧。我只能回答当前状态，公司管理层是否有其他决策，我回答不了，建议和公司商务团队沟通
我指的是这两个，MySQL的客户端链接库是GPL协议，但是有一些例外场景，很感谢你这边的回答
https://www.mysql.com/about/legal/licensing/foss-exception/
https://oss.oracle.com/licenses/universal-foss-exception/
