### ISSUE TITLE
query issue in 3.0.1.7

### ISSUE THREAD

**Issue by ctrl1109** [taosdata/TDengine#21010]
**Bug Description**
排序受到了要返回的字段的影响，导致排序错误

**To Reproduce**

**Expected Behavior**
正常数据应该是从15点左右开始倒叙，其他设备的数据也是正常的。
不知道是不是这个设备的 origin字段内容太长导致了什么bug
origin是设备上报的原子数据。

**Screenshots**
![image](https://user-images.githubusercontent.com/101610374/233578048-a23c41d0-735f-4188-8709-7146e154b7a1.png)

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]
 - 版本是3.0.1.7

**Additional Context**

**Comment by yu285** [comment]
建议直接升级到 3.0.4.1 ，问题应该是已经修复过了的。

备份下数据文件目录，覆盖安装即可。
