### ISSUE TITLE
使用asyncprofiler触发crash

### ISSUE THREAD

**Issue by XHao** [taosdata/TDengine#21016]
**Bug Description**
版本：3.0.3.2
现象：使用asyncprofiler就会导致jvm crash
但我发现，如果直接从jemalloc源码编译，并替换，就不会出现crash
请问一下你们提供的jemalloc和官方的有什么差别？是否有办法解决这个问题呢？

**To Reproduce**
使用async profiler性能诊断

**Expected Behavior**
预计不应该报错

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version 3.0.3.2

**Additional Context**
和这里看到的类似：https://github.com/async-profiler/async-profiler/issues/731

**Comment by sangshuduo** [comment]
@XHao 请问你用的 jemalloc commit id 是什么？如何重现 crash？谢谢

**Comment by XHao** [comment]
> @XHao 请问你用的 jemalloc commit id 是什么？如何重现 crash？谢谢

重现步骤比较简单，应用启动之后，使用asyncprofiler
> ./profiler.sh start -e cpu,file=/dev/null,alluser pid

进程就会crash。
我自己从jemalloc当前的dev分支编译了一下，发现没有这个问题，具体不清楚是哪个commit id和这个有关，还需要你们自己看一下

**Comment by sangshuduo** [comment]
> > @XHao 请问你用的 jemalloc commit id 是什么？如何重现 crash？谢谢
> 
> 重现步骤比较简单，应用启动之后，使用asyncprofiler
> 
> > ./profiler.sh start -e cpu,file=/dev/null,alluser pid
> 
> 进程就会crash。 我自己从jemalloc当前的dev分支编译了一下，发现没有这个问题，具体不清楚是哪个commit id和这个有关，还需要你们自己看一下

我们目前用的是 jemalloc 正式 release 版本，如果这确实是个 jemalloc dev 分支才能解决的问题，我们也只能等下次 jemalloc 正式 release 新版本才能更新了，谢谢你的 issue
