### ISSUE TITLE
3.0.4.0与emqx对接问题，订阅无法插入数据

### ISSUE THREAD

**Issue by lijunwei830** [taosdata/TDengine#21025]
1、创建数据库
create database if not exists db_monitor keep 7300 PRECISION 'ms' vgroups 20 buffer 100;
2、超级表如下：
create stable if not exists db_monitor.str_rsg_data_185(
            ts TIMESTAMP,
            pointid BIGINT,
            val DOUBLE,
            remarks NCHAR(64)
        ) tags (groupid NCHAR(64)) COMMENT 'A-21应变表';
3、子表如下：
create table if not exists db_monitor.str_rsg_data_185 using db_monitor.str_rsg_data_185 tags ('202304');
4、emqx中的Data Bridge中的body如下：
insert into db_monitor.str_rsg_data_${payload.deviceId}_${payload.yearmonth}(ts,pointid,val,remarks)values('${payload.time}',${payload.deviceId},${payload.val},'')
5、emqx中的Rules的SQL Editor如下：
SELECT
  payload
FROM
  "sensor/rsg"
6、订阅mqtt服务，主题sensor/rsg，数据如下：
{
  "yearmonth":202304,
  "time":"2023-04-21 11:41:20",
  "deviceId":185,
  "val":-155.55414
}
此时 会在日志log/taosdlog.o中出现00000967 RPC WARN DND-C conn 0x7f79d9212700 send cost:32202us, send exception，
在日志log/taoslog0.0中出现
04/23 10:08:13.936015 00001068 RPC WARN TSC conn 0x7f9494003010 send cost:33013us, send exception
04/23 10:08:16.156075 00000981 TSC connecting to server, numOfEps:2 inUse:0 user:root db:(null) key:root:dcc5bed04851fec854c035b2e40263b6:(null):0
04/23 10:08:16.156083 00000981 TSC ep:0, td1.simon.com:6030
04/23 10:08:16.156085 00000981 TSC ep:1, td2.simon.com:6030

但是直接执行语句是Ok，有数据
insert into db_monitor.str_rsg_data_185_202304(ts,pointid,val,remarks)values('2023-04-21 11:40:19.0',185,-155.55414,'');
请教一下怎么解决

**Comment by sangshuduo** [comment]
试过完全按照 [https://docs.taosdata.com/third-party/emq-broker/](https://docs.taosdata.com/third-party/emq-broker/) 设置吗？
