### ISSUE TITLE
java原生连接方式在url中设置时区无效

### ISSUE THREAD

**Issue by diaorunsheng** [taosdata/TDengine#21031]
我在java项目中使用jdbc原生连接方式连接数据库，驱动版本是3.1.0，操作系统是window11。
在使用now（）或者查询timestamp时时间少了八个小时，如下在url中添加timezone=UTC-8或者UTC+8没有任何效果。
_jdbc:TAOS://TD1:6030/heat_pipeline?charset=UTF-8&locale=en_US.UTF-8&timezone=UTC-8_
![image](https://user-images.githubusercontent.com/130733890/233823624-4fc9e19e-c8ae-419e-aabc-b4f821fe2fdb.png)
直接在服务端或者客户端上查询结果正常。
![image](https://user-images.githubusercontent.com/130733890/233823677-fd2701fc-2c6d-4011-847f-f3800da25031.png)

**Comment by Keene-Chen** [comment]
我也遇到这个问题了，请问有解决办法了嘛？我使用java调用jdbc驱动是正常的，但是使用datagrip连接的时候就显示出错，我怀疑是驱动的问题
