### ISSUE TITLE
TMR ERROR TSC too many timer controllers, failed to create timer controller

### ISSUE THREAD

**Issue by tbcandy** [taosdata/TDengine#21036]
==================================================
                new log file                      
==================================================
04/23 16:33:21.176424 00000001 DND start to initialize TDengine
04/23 16:33:21.176484 00000001 DND step:dnode-tfile is initialized
04/23 16:33:21.176494 00000001 DND step:dnode-rpc is initialized
04/23 16:33:21.176501 00000001 UTL localEp is: test_tdengine:6030
04/23 16:33:21.176761 00000001 UTL WARN locale not configured, set to system default:en_US.UTF-8
04/23 16:33:21.176773 00000001 UTL WARN charset not configured, set to system default:UTF-8
04/23 16:33:21.176814 00000001 UTL timezone is set to Asia/Shanghai by config file
04/23 16:33:21.176833 00000001 UTL timezone format changed to (CST, +0800)
04/23 16:33:21.176840 00000001 UTL    check global cfg completed
04/23 16:33:21.176848 00000001 UTL ==================================
04/23 16:33:21.176853 00000001 UTL    taos config & system info:
04/23 16:33:21.176858 00000001 UTL ==================================
04/23 16:33:21.176864 00000001 UTL  firstEp:                test_tdengine:6030 
04/23 16:33:21.176870 00000001 UTL  secondEp:               test_tdengine:6030 
04/23 16:33:21.176875 00000001 UTL  fqdn:                   test_tdengine 
04/23 16:33:21.176881 00000001 UTL  serverPort:             6030 
04/23 16:33:21.176888 00000001 UTL  configDir:              /etc/taos 
04/23 16:33:21.176892 00000001 UTL  logDir:                 /var/log/taos 
04/23 16:33:21.176899 00000001 UTL  scriptDir:              /etc/taos 
04/23 16:33:21.176904 00000001 UTL  arbitrator:              
04/23 16:33:21.176909 00000001 UTL  numOfThreadsPerCore:    1.000000 
04/23 16:33:21.176918 00000001 UTL  numOfCommitThreads:     4 
04/23 16:33:21.176921 00000001 UTL  ratioOfQueryCores:      1.000000 
04/23 16:33:21.176926 00000001 UTL  numOfMnodes:            1 
04/23 16:33:21.176932 00000001 UTL  vnodeBak:               1 
04/23 16:33:21.176938 00000001 UTL  telemetryReporting:     0 
04/23 16:33:21.176955 00000001 UTL  balance:                1 
04/23 16:33:21.176962 00000001 UTL  balanceInterval:        300 
04/23 16:33:21.176967 00000001 UTL  role:                   0 
04/23 16:33:21.176970 00000001 UTL  maxTmrCtrl:             512 
04/23 16:33:21.176975 00000001 UTL  monitorInterval:        30(s)
04/23 16:33:21.176980 00000001 UTL  offlineThreshold:       864000(s)
04/23 16:33:21.176985 00000001 UTL  rpcTimer:               300(ms)
04/23 16:33:21.176990 00000001 UTL  rpcMaxTime:             600(s)
04/23 16:33:21.176992 00000001 UTL  statusInterval:         1(s)
04/23 16:33:21.176995 00000001 UTL  shellActivityTimer:     3(s)
04/23 16:33:21.177000 00000001 UTL  minSlidingTime:         10(ms)
04/23 16:33:21.177002 00000001 UTL  minIntervalTime:        10(ms)
04/23 16:33:21.177005 00000001 UTL  maxStreamCompDelay:     20000(ms)
04/23 16:33:21.177010 00000001 UTL  maxFirstStreamCompDelay:10000(ms)
04/23 16:33:21.177014 00000001 UTL  retryStreamCompDelay:   10000(ms)
04/23 16:33:21.177020 00000001 UTL  streamCompDelayRatio:   0.100000 
04/23 16:33:21.177025 00000001 UTL  maxVgroupsPerDb:        0 
04/23 16:33:21.177030 00000001 UTL  maxTablesPerVnode:      1000000 
04/23 16:33:21.177036 00000001 UTL  minTablesPerVnode:      1000 
04/23 16:33:21.177040 00000001 UTL  tableIncStepPerVnode:   1000 
04/23 16:33:21.177044 00000001 UTL  cache:                  16(Mb)
04/23 16:33:21.177048 00000001 UTL  blocks:                 6 
04/23 16:33:21.177058 00000001 UTL  days:                   10 
04/23 16:33:21.177062 00000001 UTL  keep:                   3650 
04/23 16:33:21.177071 00000001 UTL  minRows:                100 
04/23 16:33:21.177074 00000001 UTL  maxRows:                4096 
04/23 16:33:21.177076 00000001 UTL  precision:              0 
04/23 16:33:21.177079 00000001 UTL  comp:                   2 
04/23 16:33:21.177083 00000001 UTL  walLevel:               1 
04/23 16:33:21.177087 00000001 UTL  fsync:                  3000 
04/23 16:33:21.177091 00000001 UTL  replica:                1 
04/23 16:33:21.177099 00000001 UTL  partitions:             4 
04/23 16:33:21.177103 00000001 UTL  quorum:                 1 
04/23 16:33:21.177107 00000001 UTL  update:                 0 
04/23 16:33:21.177113 00000001 UTL  cachelast:              0 
04/23 16:33:21.177122 00000001 UTL  compressMsgSize:        -1 
04/23 16:33:21.177126 00000001 UTL  maxSQLLength:           1048576(byte)
04/23 16:33:21.177129 00000001 UTL  maxNumOfOrderedRes:     100000 
04/23 16:33:21.177133 00000001 UTL  queryBufferSize:        -1(byte)
04/23 16:33:21.177143 00000001 UTL  retrieveBlockingModel:  0 
04/23 16:33:21.177146 00000001 UTL  keepColumnName:         0 
04/23 16:33:21.177150 00000001 UTL  timezone:               (CST, +0800) 
04/23 16:33:21.177160 00000001 UTL  locale:                 en_US.UTF-8 
04/23 16:33:21.177165 00000001 UTL  charset:                UTF-8 
04/23 16:33:21.177168 00000001 UTL  maxShellConns:          50000 
04/23 16:33:21.177174 00000001 UTL  maxConnections:         5000 
04/23 16:33:21.177187 00000001 UTL  minimalLogDirGB:        1.000000(GB)
04/23 16:33:21.177194 00000001 UTL  minimalTmpDirGB:        1.000000(GB)
04/23 16:33:21.177199 00000001 UTL  minimalDataDirGB:       2.000000(GB)
04/23 16:33:21.177204 00000001 UTL  mnodeEqualVnodeNum:     4 
04/23 16:33:21.177208 00000001 UTL  flowctrl:               1 
04/23 16:33:21.177214 00000001 UTL  slaveQuery:             1 
04/23 16:33:21.177226 00000001 UTL  adjustMaster:           1 
04/23 16:33:21.177234 00000001 UTL  http:                   1 
04/23 16:33:21.177241 00000001 UTL  mqtt:                   0 
04/23 16:33:21.177250 00000001 UTL  monitor:                1 
04/23 16:33:21.177254 00000001 UTL  stream:                 1 
04/23 16:33:21.177257 00000001 UTL  httpEnableRecordSql:    0 
04/23 16:33:21.177259 00000001 UTL  telegrafUseFieldNum:    0 
04/23 16:33:21.177263 00000001 UTL  httpMaxThreads:         12 
04/23 16:33:21.177274 00000001 UTL  restfulRowLimit:        10240 
04/23 16:33:21.177277 00000001 UTL  numOfLogLines:          10000000 
04/23 16:33:21.177283 00000001 UTL  logKeepDays:            7 
04/23 16:33:21.177293 00000001 UTL  asyncLog:               1 
04/23 16:33:21.177297 00000001 UTL  debugFlag:              131 
04/23 16:33:21.177302 00000001 UTL  mDebugFlag:             131 
04/23 16:33:21.177306 00000001 UTL  dDebugFlag:             131 
04/23 16:33:21.177309 00000001 UTL  sDebugFlag:             131 
04/23 16:33:21.177313 00000001 UTL  wDebugFlag:             131 
04/23 16:33:21.177319 00000001 UTL  sdbDebugFlag:           131 
04/23 16:33:21.177323 00000001 UTL  rpcDebugFlag:           131 
04/23 16:33:21.177328 00000001 UTL  tmrDebugFlag:           131 
04/23 16:33:21.177335 00000001 UTL  cDebugFlag:             131 
04/23 16:33:21.177338 00000001 UTL  jniDebugFlag:           131 
04/23 16:33:21.177344 00000001 UTL  odbcDebugFlag:          131 
04/23 16:33:21.177351 00000001 UTL  uDebugFlag:             131 
04/23 16:33:21.177355 00000001 UTL  httpDebugFlag:          131 
04/23 16:33:21.177361 00000001 UTL  mqttDebugFlag:          131 
04/23 16:33:21.177365 00000001 UTL  monDebugFlag:           131 
04/23 16:33:21.177371 00000001 UTL  qDebugFlag:             131 
04/23 16:33:21.177383 00000001 UTL  vDebugFlag:             131 
04/23 16:33:21.177389 00000001 UTL  tsdbDebugFlag:          131 
04/23 16:33:21.177394 00000001 UTL  cqDebugFlag:            131 
04/23 16:33:21.177405 00000001 UTL  enableRecordSql:        0 
04/23 16:33:21.177410 00000001 UTL  enableCoreFile:         0 
04/23 16:33:21.177415 00000001 UTL  gitinfo:                764074865eedb3b184ed6efb254912e3cce8efae 
04/23 16:33:21.177422 00000001 UTL  gitinfoOfInternal:      NULL 
04/23 16:33:21.177426 00000001 UTL  buildinfo:              Built at 2021-09-02 01:43 
04/23 16:33:21.177432 00000001 UTL  version:                2.0.20.16 
04/23 16:33:21.177435 00000001 UTL  maxBinaryDisplayWidth:  30 
04/23 16:33:21.177441 00000001 UTL  tempDir:                /tmp/ 
04/23 16:33:21.177446 00000001 UTL  os pageSize:            4096(KB)
04/23 16:33:21.177450 00000001 UTL  os openMax:             1048576
04/23 16:33:21.177453 00000001 UTL  os streamMax:           16
04/23 16:33:21.177455 00000001 UTL  os numOfCores:          24
04/23 16:33:21.177462 00000001 UTL  os totalMemory:         30377(MB)
04/23 16:33:21.177470 00000001 UTL  os sysname:             Linux
04/23 16:33:21.177475 00000001 UTL  os nodename:            16046db62346
04/23 16:33:21.177482 00000001 UTL  os release:             4.19.90-24.4.v2101.ky10.x86_64
04/23 16:33:21.177486 00000001 UTL  os version:             #1 SMP Mon May 24 12:14:55 CST 2021
04/23 16:33:21.177492 00000001 UTL  os machine:             x86_64
04/23 16:33:21.177496 00000001 UTL  dataDir: /var/lib/taos
04/23 16:33:21.177502 00000001 UTL ==================================
04/23 16:33:21.177507 00000001 DND step:dnode-globalcfg is initialized
04/23 16:33:21.177538 00000001 TFS disk /var/lib/taos is mounted to tier level 0 id 0
04/23 16:33:21.177588 00000001 UTL ==================================
04/23 16:33:21.177592 00000001 UTL  os totalDisk:           22285.488281(GB)
04/23 16:33:21.177597 00000001 UTL  os usedDisk:            211.101028(GB)
04/23 16:33:21.177600 00000001 UTL  os availDisk:           22074.386719(GB)
04/23 16:33:21.177605 00000001 UTL ==================================
04/23 16:33:21.177616 00000001 DND dnode storage is initialized at /var/lib/taos/dnode
04/23 16:33:21.177621 00000001 DND step:dnode-storage is initialized
04/23 16:33:21.177650 00000001 DND read file /var/lib/taos/dnode/dnodeCfg.json successed
04/23 16:33:21.177656 00000001 DND dnodeId is set to 1, clusterId is set to a2795f82-377d-4bbe-a373-07d67237c633
04/23 16:33:21.178347 00000001 DND successed to write /var/lib/taos/dnode/dnodeCfg.json
04/23 16:33:21.178354 00000001 DND dnode cfg is initialized
04/23 16:33:21.178357 00000001 DND step:dnode-cfg is initialized
04/23 16:33:21.178387 00000001 DND read file /var/lib/taos/dnode/dnodeEps.json successed
04/23 16:33:21.178400 00000001 DND dnode eps is initialized
04/23 16:33:21.178405 00000001 DND step:dnode-eps is initialized
04/23 16:33:21.178430 00000001 DND read file /var/lib/taos/dnode/mnodeEpSet.json successed
04/23 16:33:21.178435 00000001 DND print minfos, mnodeNum:1 inUse:0
04/23 16:33:21.178438 00000001 DND mnode index:1, test_tdengine:6030
04/23 16:33:21.178444 00000001 DND print minfos, mnodeNum:1 inUse:0
04/23 16:33:21.178450 00000001 DND mnode index:1, test_tdengine:6030
04/23 16:33:21.178456 00000001 DND dnode minfos is initialized
04/23 16:33:21.178460 00000001 DND step:dnode-minfos is initialized
04/23 16:33:21.178500 00000001 WAL wal module is initialized, rsetId:3
04/23 16:33:21.178505 00000001 DND step:dnode-wal is initialized
04/23 16:33:21.178556 00000001 SYN sync module initialized successfully
04/23 16:33:21.178557 00000001 DND step:dnode-sync is initialized
04/23 16:33:21.178572 00000001 DND dnode check is initialized
04/23 16:33:21.178575 00000001 DND step:dnode-check is initialized
04/23 16:33:21.178579 00000001 UTL worker:vquery is initialized, min:24 max:24
04/23 16:33:21.178588 00000001 UTL worker:vfetch is initialized, min:4 max:4
04/23 16:33:21.178594 00000001 DND step:dnode-vread is initialized
04/23 16:33:21.178597 00000001 DND dnode vwrite is initialized, max worker 24
04/23 16:33:21.178601 00000001 DND step:dnode-vwrite is initialized
04/23 16:33:21.178937 00000001 DND step:vnode-backup is initialized
04/23 16:33:21.178972 00000001 DND step:vnode-worker is initialized
04/23 16:33:21.178977 00000001 DND step:vnode-write is initialized
04/23 16:33:21.178980 00000001 DND step:vnode-read is initialized
04/23 16:33:21.178984 00000001 DND step:vnode-hash is initialized
04/23 16:33:21.179070 00000001 DND step:tsdb-queue is initialized
04/23 16:33:21.179077 00000001 UTL worker:vmgmt is initialized, min:1 max:1
04/23 16:33:21.179104 00000001 DND dnode vmgmt is initialized
04/23 16:33:21.179111 00000001 DND step:dnode-vmgmt is initialized
04/23 16:33:21.179116 00000001 DND step:dnode-mread is initialized
04/23 16:33:21.179122 00000001 DND step:dnode-mwrite is initialized
04/23 16:33:21.179130 00000001 DND step:dnode-mpeer is initialized
04/23 16:33:21.181003 00000001 DND dnode inter-dnodes rpc client is initialized
04/23 16:33:21.181020 00000001 DND step:dnode-client is initialized
04/23 16:33:21.181771 00000001 DND dnode inter-dnodes RPC server is initialized
04/23 16:33:21.181777 00000001 DND step:dnode-server is initialized
04/23 16:33:21.181889 00000001 DND start 24 threads to open 507 vnodes
04/23 16:33:21.182657 00000027 VND vgId:4, load vnode cfg successfully, replcia:1
04/23 16:33:21.182680 00000027 VND vgId:4, dnode:1, test_tdengine:6040
04/23 16:33:21.182658 00000025 VND vgId:2, load vnode cfg successfully, replcia:1
04/23 16:33:21.182673 00000026 VND vgId:3, load vnode cfg successfully, replcia:1
04/23 16:33:21.182692 00000027 VND vgId:4, read /var/lib/taos/vnode/vnode4/version.json successfully, fver:576330
04/23 16:33:21.182719 00000026 VND vgId:3, dnode:1, test_tdengine:6040
04/23 16:33:21.182693 00000025 VND vgId:2, dnode:1, test_tdengine:6040
04/23 16:33:21.182777 00000026 VND vgId:3, read /var/lib/taos/vnode/vnode3/version.json successfully, fver:576272
04/23 16:33:21.182777 00000025 VND vgId:2, read /var/lib/taos/vnode/vnode2/version.json successfully, fver:75047
04/23 16:33:21.182818 00000029 VND vgId:6, load vnode cfg successfully, replcia:1
04/23 16:33:21.182829 00000028 VND vgId:5, load vnode cfg successfully, replcia:1
04/23 16:33:21.182859 00000030 VND vgId:7, load vnode cfg successfully, replcia:1
......
04/23 16:33:21.825400 00000027 VND vgId:508, load vnode cfg successfully, replcia:1
04/23 16:33:21.825404 00000027 VND vgId:508, dnode:1, test_tdengine:6040
04/23 16:33:21.825415 00000027 VND vgId:508, read /var/lib/taos/vnode/vnode508/version.json successfully, fver:576223
04/23 16:33:21.828760 00000027 SYN vgId:508, nodeId:1, 0x7f0d2df9fec0 it is configured, ep:test_tdengine:6040 rid:508
04/23 16:33:21.828764 00000027 SYN vgId:508, 1 replicas are configured, quorum:1 role:master
04/23 16:33:21.828790 00000027 VND vgId:508, sync role changed from offline to master
04/23 16:33:21.828799 00000027 QRY vgId:508, set querymgmt reopen
04/23 16:33:21.828982 00000001 DND there are total vnodes:507, opened:507
04/23 16:33:21.828995 00000001 DND step:dnode-vnodes is initialized
04/23 16:33:21.829014 00000001 MND starting to initialize mnode ...
04/23 16:33:21.829101 00000001 DND step:sdbref is initialized
04/23 16:33:21.829189 00000001 DND step:profile is initialized
04/23 16:33:21.829196 00000001 DND step:cluster is initialized
04/23 16:33:21.829201 00000001 DND step:accts is initialized
04/23 16:33:21.829211 00000001 DND step:users is initialized
04/23 16:33:21.829217 00000001 DND step:dnodes is initialized
04/23 16:33:21.829222 00000001 DND step:dbs is initialized
04/23 16:33:21.829229 00000001 DND step:vgroups is initialized
04/23 16:33:21.829601 00000001 DND step:tables is initialized
04/23 16:33:21.829609 00000001 DND step:mnodes is initialized
04/23 16:33:21.829630 00000001 MND vgId:1, sdb write is opened
04/23 16:33:21.829638 00000001 SDB vgId:1, open sdb wal for restore
04/23 16:33:21.829655 00000001 WAL vgId:1, file:/var/lib/taos/mnode/wal/wal0, will be restored
04/23 16:33:21.829681 00000001 MND dnode:1, fqdn:test_tdengine ep:test_tdengine:6030 port:6030 is created
04/23 16:33:21.829688 00000001 MND mnode:1, fqdn:test_tdengine ep:test_tdengine:6030 port:6030 is created
04/23 16:33:21.829701 00000001 WAL vgId:1, file:/var/lib/taos/mnode/wal/wal0, restore success, wver:7
04/23 16:33:21.829713 00000001 SDB vgId:1, sdb wal load success
04/23 16:33:21.829717 00000001 SDB vgId:1, sdb start to check for integrity
04/23 16:33:21.829720 00000001 SDB vgId:1, sdb:cluster is checked, rows:1
04/23 16:33:21.829726 00000001 SDB vgId:1, sdb:dnodes is checked, rows:1
04/23 16:33:21.829730 00000001 MND vgId:1, update mnodes epSet, numOfMnodes:1
04/23 16:33:21.829736 00000001 MND vgId:1, mnodes epSet is set, num:1 inUse:0
04/23 16:33:21.829739 00000001 MND vgId:1, mnode:1, fqdn:test_tdengine shell:6030 peer:6035
04/23 16:33:21.829747 00000001 SDB vgId:1, sdb:mnodes is checked, rows:1
04/23 16:33:21.829761 00000001 SDB vgId:1, sdb:accounts is checked, rows:1
04/23 16:33:21.829766 00000001 SDB vgId:1, sdb:users is checked, rows:3
04/23 16:33:21.829775 00000001 SDB vgId:1, sdb:dbs is checked, rows:0
04/23 16:33:21.829778 00000001 SDB vgId:1, sdb:vgroups is checked, rows:0
04/23 16:33:21.829781 00000001 SDB vgId:1, sdb:stables is checked, rows:0
04/23 16:33:21.829784 00000001 SDB vgId:1, sdb:ctables is checked, rows:0
04/23 16:33:21.829789 00000001 SDB vgId:1, sdb is restored, mver:7 rows:7 tables:9
04/23 16:33:21.829792 00000001 DND step:sdb is initialized
04/23 16:33:21.829814 00000001 MND dnode:1 set access:0 to 0
04/23 16:33:21.829820 00000001 DND step:balance is initialized
04/23 16:33:21.829825 00000001 DND step:grant is initialized
04/23 16:33:21.830217 00000001 DND step:show is initialized
04/23 16:33:21.830229 00000001 MND mnode is initialized successfully
04/23 16:33:21.830246 00000001 SDB vgId:1, work as mnode, replica:1
04/23 16:33:21.830253 00000001 SDB vgId:1, mnode:1, test_tdengine:6040
04/23 16:33:21.830258 00000001 SYN vgId:1, nodeId:1, 0x557adb920450 it is configured, ep:test_tdengine:6040 rid:509
04/23 16:33:21.830260 00000001 SYN vgId:1, 1 replicas are configured, quorum:1 role:master
04/23 16:33:21.830316 00000001 SDB vgId:1, mnode role changed from master to master
04/23 16:33:21.830322 00000001 SDB vgId:1, update mnodes role, replica:1
04/23 16:33:21.830327 00000001 SDB vgId:1, mnode:1, role:master
04/23 16:33:21.830332 00000001 MND vgId:1, update mnodes epSet, numOfMnodes:1
04/23 16:33:21.830337 00000001 MND vgId:1, mnodes epSet is set, num:1 inUse:0
04/23 16:33:21.830342 00000001 MND vgId:1, mnode:1, fqdn:test_tdengine shell:6030 peer:6035
04/23 16:33:21.830391 00000001 DND dnode modules is initialized
04/23 16:33:21.830395 00000001 HTP start http server ...
04/23 16:33:21.831184 00000001 HTP http result queue is opened
04/23 16:33:21.831590 00000645 HTP http server init success at 6041
04/23 16:33:21.831830 00000001 TMR ERROR TSC too many timer controllers, failed to create timer controller.
04/23 16:33:21.832299 00000001 MON monitor module start
04/23 16:33:21.832312 00000001 DND step:dnode-modules is initialized
04/23 16:33:21.832330 00000001 TMR ERROR SHELL too many timer controllers, failed to create timer controller.
04/23 16:33:21.832334 00000001 RPC ERROR SHELL failed to init timers
04/23 16:33:21.833129 00000001 DND ERROR failed to init shell rpc server
04/23 16:33:21.833230 00000001 HTP http server cleanup
04/23 16:33:21.833512 00000001 HTP context cache is cleanuping, size:0
04/23 16:33:22.331390 00000001 UTL cache:restc will be cleaned up
04/23 16:33:22.331478 00000001 HTP session cache is cleanuping, size:0
04/23 16:33:22.830533 00000618 TMR ERROR TSC too many timer controllers, failed to create timer controller.
04/23 16:33:22.830568 00000618 RPC ERROR TSC failed to init timers
04/23 16:33:22.830863 00000618 TSC ERROR failed to init connection to TDengine
04/23 16:33:22.830898 00000618 MON ERROR failed to connect to database, reason:Unable to establish connection
04/23 16:33:22.831510 00000001 UTL cache:rests will be cleaned up
04/23 16:33:22.831770 00000001 HTP http result queue is closed
04/23 16:33:22.831776 00000001 MON monitor module stopped
04/23 16:33:22.831779 00000001 MON monitor module stopped
04/23 16:33:23.830961 00000618 MON monitor thread will quit, for taosd is quiting
04/23 16:33:23.830994 00000618 MON monitor thread is stopped
04/23 16:33:23.831064 00000001 MON monitor module is cleaned up
04/23 16:33:23.831086 00000001 MND starting to clean up mnode
04/23 16:33:23.831095 00000001 MND show cache is cleanup
04/23 16:33:24.330569 00000001 UTL cache:show will be cleaned up
04/23 16:33:24.330730 00000001 MND vgId:1, sdb write is closed
04/23 16:33:24.330738 00000001 SYN vgId:1, cleanup sync
04/23 16:33:24.330754 00000001 SYN vgId:1, nodeId:1, it is removed
04/23 16:33:24.829593 00000001 UTL cache:conn will be cleaned up
04/23 16:33:24.829672 00000001 MND mnode is cleaned up
04/23 16:33:24.829998 00000001 QRY vgId:2, set querymgmt closed, wait for all queries cancelled
04/23 16:33:24.830010 00000001 SYN vgId:2, cleanup sync
04/23 16:33:24.830014 00000001 SYN vgId:2, nodeId:1, it is removed
......
04/23 16:33:24.834920 00000001 QRY vgId:508, set querymgmt closed, wait for all queries cancelled
04/23 16:33:24.834925 00000001 SYN vgId:508, cleanup sync
04/23 16:33:24.834927 00000001 SYN vgId:508, nodeId:1, it is removed
04/23 16:33:24.834929 00000001 DND total vnodes:507 are all closed
04/23 16:33:25.186295 00000001 DND inter-dnodes RPC server is closed
04/23 16:33:25.199123 00000014 UTL cache:qhandle_2 will be cleaned up
04/23 16:33:25.199364 00000014 WAL vgId:2, wal:0x7f0ed802d750 file:/var/lib/taos/vnode/vnode2/wal/wal1, it is removed
04/23 16:33:25.259460 00000014 UTL cache:qhandle_3 will be cleaned up
04/23 16:33:25.260159 00000014 WAL vgId:3, wal:0x7f0ed00a3530 file:/var/lib/taos/vnode/vnode3/wal/wal1, it is removed
04/23 16:33:25.685834 00000001 DND dnode inter-dnodes rpc client is closed
04/23 16:33:25.685918 00000001 UTL worker:vmgmt is closed
......
04/23 16:35:42.795547 00000014 UTL cache:qhandle_506 will be cleaned up
04/23 16:35:42.796132 00000014 WAL vgId:506, wal:0x7f0d81f4f4c0 file:/var/lib/taos/vnode/vnode506/wal/wal1, it is removed
==================================================
                new log file                      
==================================================
04/23 16:35:44.592678 00000001 DND start to initialize TDengine
04/23 16:35:44.592733 00000001 DND step:dnode-tfile is initialized
04/23 16:35:44.592743 00000001 DND step:dnode-rpc is initialized
04/23 16:35:44.592747 00000001 UTL localEp is: test_tdengine:6030
......

modified maxTmrCtrl configuration, invalid

Does this mean that my data is corrupt?  Is there a way to recover data?

thanks.

**Comment by Mark33529** [comment]
我也遇到这个问题，如何解决？

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
