### ISSUE TITLE
v3.0.1.8 启动失败

### ISSUE THREAD

**Issue by 741406143wkf** [taosdata/TDengine#21048]
### 简介
重启服务器后，tdengine 服务无法正常启动
### 启动
[root@localhost TDengine-server-3.0.1.8]# systemctl start taosd
[root@localhost TDengine-server-3.0.1.8]#
[root@localhost TDengine-server-3.0.1.8]# systemctl status taosd
● taosd.service - TDengine server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since 一 2023-04-24 10:25:54 CST; 4s ago
  Process: 28563 ExecStart=/usr/bin/taosd (code=exited, status=255)
  Process: 28555 ExecStartPre=/usr/local/taos/bin/startPre.sh (code=exited, status=0/SUCCESS)
 Main PID: 28563 (code=exited, status=255)

4月 24 10:25:53 localhost.localdomain systemd[1]: Unit taosd.service entered failed state.
4月 24 10:25:53 localhost.localdomain systemd[1]: taosd.service failed.
4月 24 10:25:54 localhost.localdomain systemd[1]: taosd.service holdoff time over, scheduling restart.
4月 24 10:25:54 localhost.localdomain systemd[1]: Stopped TDengine server service.
4月 24 10:25:54 localhost.localdomain systemd[1]: start request repeated too quickly for taosd.service
4月 24 10:25:54 localhost.localdomain systemd[1]: Failed to start TDengine server service.
4月 24 10:25:54 localhost.localdomain systemd[1]: Unit taosd.service entered failed state.
4月 24 10:25:54 localhost.localdomain systemd[1]: taosd.service failed.
### taos log
new log file
04/24 10:33:32.185242 00001674 DND ERROR dnode:1, localEp localhost:6030 different from .:6030
04/24 10:33:32.238738 00001674 DND ERROR localEp localhost:6030 different with /home/taos/dataDir/dnode/dnode.json and need reconfigured
04/24 10:33:32.255374 00001674 DND ERROR failed to read file since Config not found
04/24 10:33:32.272045 00001674 DND ERROR failed to create dnode since Config not found
04/24 10:33:32.288720 00001674 DND ERROR failed to init dnode since Config not found
                new log file
04/24 10:33:32.629894 00001689 DND ERROR dnode:1, localEp localhost:6030 different from .:6030
04/24 10:33:32.672093 00001689 DND ERROR localEp localhost:6030 different with /home/taos/dataDir/dnode/dnode.json and need reconfigured
04/24 10:33:32.688873 00001689 DND ERROR failed to read file since Config not found
04/24 10:33:32.705469 00001689 DND ERROR failed to create dnode since Config not found
04/24 10:33:32.722142 00001689 DND ERROR failed to init dnode since Config not found
                new log file
04/24 10:33:32.884477 00001700 DND ERROR dnode:1, localEp localhost:6030 different from .:6030
04/24 10:33:32.922221 00001700 DND ERROR localEp localhost:6030 different with /home/taos/dataDir/dnode/dnode.json and need reconfigured
04/24 10:33:32.938991 00001700 DND ERROR failed to read file since Config not found
04/24 10:33:32.955493 00001700 DND ERROR failed to create dnode since Config not found
04/24 10:33:32.972242 00001700 DND ERROR failed to init dnode since Config not found

**Comment by 741406143wkf** [comment]
dnode.json文件
{
  "dnodeId": 1,
  "dnodeVer": "2",
  "clusterId": "2698389477574751145",
  "dropped": 0,
  "dnodes": [{
    "id": 1,
    "fqdn": ".",
    "port": 6030,
    "isMnode": 1
  }]
}

**Comment by sangshuduo** [comment]
ERROR localEp localhost:6030 different with /home/taos/dataDir/dnode/dnode.json and need reconfigured

看起来是 hostname 变了导致的

**Comment by 741406143wkf** [comment]
![image](https://user-images.githubusercontent.com/41145896/233892314-29f64611-ddc6-484a-8e38-d473e680ba80.png)
haost是本地的，我有试过把fqdn修改为 taos-conf启动，还是失败

**Comment by sangshuduo** [comment]
/home/taos/dataDir/dnode/dnode.json 这个文件的内容是什么？

**Comment by 741406143wkf** [comment]
dnode.json文件
{
"dnodeId": 1,
"dnodeVer": "2",
"clusterId": "2698389477574751145",
"dropped": 0,
"dnodes": [{
"id": 1,
"fqdn": ".",
"port": 6030,
"isMnode": 1
}]
}

**Comment by sangshuduo** [comment]
fqdn 有问题

**Comment by feiyangbeyond** [comment]
> 已解决,感谢

你好请教一下怎么解决的
