### ISSUE TITLE
How to alter multiple tag value?

### ISSUE THREAD

**Issue by sexbee** [taosdata/TDengine#2104]
**General Questions**
How to alter multiple tag value?
 ALTER TABLE <table_name> SET TAG <tag_name1>=<new_tag_value1> <tag_name2>=<new_tag_value2> <tag_name3>=<new_tag_value3>;

 DB error: invalid SQL: syntax error

**Comment by sexbee** [comment]
taos> alter table m25546s117 set tag onoff = 'off' adfrom='brly002';

DB error: invalid SQL: syntax error near "adfrom='brly002';"
taos>  alter table m25546s117 set tag onoff = 'off' adfrom='brly002';

DB error: invalid SQL: syntax error near "adfrom='brly002';"
taos> alter table m25546s117 set tag onoff = 'off' adfrom = 'brly002';

DB error: invalid SQL: syntax error near "adfrom = 'brly002';"
taos> alter table m25546s117 set tag onoff = 'off' and adfrom = 'brly002';

DB error: invalid SQL: syntax error near "and adfrom = 'brly002';"
taos> alter table m25546s117 set tag onoff = 'off' , adfrom = 'brly002';

DB error: invalid SQL: syntax error near ", adfrom = 'brly002';"
taos> alter table m25546s117 set tag onoff = 'off' set tag adfrom='brly002';

DB error: invalid SQL: syntax error near "set tag adfrom='brly002';"
taos> alter table m25546s117 set tag onoff = 'off'  tag adfrom='brly002';

DB error: invalid SQL: syntax error near "tag adfrom='brly002';"
taos>  alter table m25546s117 set tag onoff = 'off' and  set tag adfrom='brly002';

DB error: invalid SQL: syntax error near "and  set tag adfrom='brly002';"
taos>  alter table m25546s117 set tag onoff = 'off' , set tag adfrom='brly002';

DB error: invalid SQL: syntax error near ", set tag adfrom='brly002';"
taos>  alter table m25546s117 set tag onoff,adfrom = 'off','brly002';

DB error: invalid SQL: syntax error near ",adfrom = 'off','brly002';"
taos> alter table m25546s117 set tags onoff = 'off' , adfrom = 'brly002';

DB error: invalid SQL: syntax error near "tags onoff = 'off' , adfrom = 'brly002';"
taos> alter table m25546s117 set tags 'off' , 'brly002';

DB error: invalid SQL: syntax error near "tags 'off' , 'brly002';"
taos>  alter table m25546s117 set tag 'off' , 'brly002';

DB error: invalid SQL: syntax error near ", 'brly002';"
taos>  alter table m25546s117 set tag 'off' 'brly002';

DB error: invalid SQL: syntax error near "'brly002';"

taos> alter table m25546s117 set tag ( onoff = 'off' , adfrom = 'brly002');
DB error: invalid SQL: syntax error near "( onoff = 'off' , adfrom = 'brly002');"

**Comment by Aries-Lee1991** [comment]
It's invalid. If multiple tag value need to be altered,  please alter them one by one.

**Comment by sexbee** [comment]
Alter one tag  each times?

**Comment by Aries-Lee1991** [comment]
> Alter one tag each times?

Yes.
