### ISSUE TITLE
客户端连接  每次连接后都有 TDengine.Close()，但是会不停的生成线程占用6030端口。几个小时候不能连接和查询。 服务端连接数正常

### ISSUE THREAD

**Issue by chenjilai** [taosdata/TDengine#21041]
客户端连接  每次连接后都有 TDengine.Close()，但是会不停的生成线程占用6030端口。几个小时候不能连接和查询。 服务端连接数正常

**Comment by chenjilai** [comment]
服务端 linux服务器   客户端windows server2016服务器， iisc# 代码创建连接

**Comment by sangshuduo** [comment]
请提供可重现问题的代码

**Comment by chenjilai** [comment]
cs 程序没有问题， 布置在iis的有问题； 尤其外网ip来调用的接口最容易出问题。
代码我提供  连接， 插入，和查询。 查询操作更容易出问题
出问题的时候  代码停止在  TDengine.Connect(），不继续往下执行
1连接：
private IntPtr connect(string tablename)
        {
            LogHelper.Warn("TDengineconn11111111111111--------");
            try
            {
                IntPtr res = TDengine.Connect(
                SysOptions.TDengineOptionData.Host,
                SysOptions.TDengineOptionData.UserName,
                SysOptions.TDengineOptionData.Password,
                TableDic[tablename],
                SysOptions.TDengineOptionData.Port
                );
                LogHelper.Warn("TDengineconn222222222222222---");

                int errorTimes = 0;
                if (res == IntPtr.Zero)
                {
                    ++errorTimes;
                    while (errorTimes <= 3)
                    { //重连3次 
                        res = TDengine.Connect(
                    SysOptions.TDengineOptionData.Host,
                    SysOptions.TDengineOptionData.UserName,
                    SysOptions.TDengineOptionData.Password,
                    TableDic[tablename],
                    SysOptions.TDengineOptionData.Port
                    );
                        if (res != IntPtr.Zero)
                        {
                            break;
                        }
                    }
                    LogHelper.Error("TDengineconn 数据库连接失败，重连次数:" + (errorTimes));
                    LogHelper.Error("TDengineconn 数据库连接失败，请检查连接errno:" + TDengine.ErrorNo(res) + "tdErrorMsg:" + TDengine.Error(res));
                    if (errorTimes > 3)
                    {//重连三次连不上抛出异常
                        throw new ArgumentException("数据库连接失败，重连3次");
                    }
                }
                return res;

            }
            catch (Exception ex)
            {
                LogHelper.Error(@$"TDengine连接报错ex:" + ex.ToString());
                throw ex;
            }

        }

2查询：

 public async Task<List<HisDataDto>> GetHisdata(List<string> channelIds = null, DateTime? startTime = null, DateTime? endTime = null, int Interval = -1,
            string Unit = "", long Limit = 100000000, string order = "", List<StringDateTimeDto> channelIdAndTimes = null, DateTime? startTimeGreater = null, bool OrderDesc = true)
        {
            try
            {
         
                int takeNumber = 100; //不要太大,否则会查不出数据 停住,td连接越来越多,最后td奔溃

                var result = new List<HisDataDto>();
                string curSql = "";
                if (channelIds != null && channelIds.Count > 0)
                {
                    for (int i = 0; i < channelIds.Count; i += takeNumber)
                    {
                        var current = channelIds.Skip(i)
                                                .Take(takeNumber)
                                                .ToList();
          
                        var builder = TDengineSql.BuildConditionTDengine("HisData", current, null, startTime, endTime, startTimeGreater, order, Limit, OrderDesc);
                        var curResult = await Query<HisDataDto>(builder, "HisData");

                        result.AddRange(curResult);
                        curSql = builder.ToString();
                    }
                }
                if (channelIdAndTimes != null && channelIdAndTimes.Count > 0)
                {
                    //takeNumber = 300;
                    //DateTime startTimeCur = channelIdAndTimes.FirstOrDefault().TimeKey.Date;
                    //DateTime endTimeCur = startTimeCur.AddSeconds(1);
                    for (int i = 0; i < channelIdAndTimes.Count; i += takeNumber)
                    {
                        var current = channelIdAndTimes.Skip(i)
                                                       .Take(takeNumber)
                                                       .ToList();
     
                        var builder = TDengineSql.BuildConditionTDengine("HisData", null, current, startTime, endTime, startTimeGreater, order, Limit, OrderDesc);

                        var curResult = await Query<HisDataDto>(builder, "HisData");

                        result.AddRange(curResult);
                        curSql = builder.ToString();
                    }
                }
                bool ishaveNullId = false;
                foreach (var item in result)
                {
                    if (item.ChannelId == null)
                    {
                        ishaveNullId = true;
                    }
                }
                if (ishaveNullId)
                {
                    LogHelper.Error("DataBLLGetHisdata没有channelID SQL:" + curSql);
                    result = result.Where(it => it.ChannelId != null).ToList(); //出现channelid 是null的数据,不知道怎么来的 td 有bug
                }
                return result;
            }
            catch (Exception ex)
            {
                LogHelper.Error("DataBLL报错GetHisdata_20:" + ex.ToString() + "trace--" + ex.StackTrace);
                LogHelper.Error("channelIdsCount:" + channelIds.Count());
                throw ex;
            }
        }

2.1查询子方法
public static string BuildConditionTDengine(string tableName, List<string> channelIds, List<StringDateTimeDto> channelIdAndTimes, DateTime? startTime, DateTime? endTime, DateTime? startTimeGreater, string order, long? limit, bool OrderDesc = false)
        {

            var builder = new StringBuilder();

            if (channelIdAndTimes != null && channelIdAndTimes.Count > 0)
            {

                builder.Append($" select * from ( ");
                foreach (var item in channelIdAndTimes)
                {//这里time 都一样, 拿出来单独写
                    builder.Append($" select * from {tableName} where ChannelId = {item.StrKey} and time  = '{item.TimeKey:yyyy-MM-dd HH:mm:ss.ffffff}'  union all");
                }
                builder.Remove(builder.Length - 9, 9);
                builder.Append(" )");
 
            }
            else
            {

                builder.Append($" select * from ( ");
                foreach (var item in channelIds)
                {//这里time 都一样, 拿出来单独写
                    builder.Append($" select * from {tableName} where ChannelId = {item} ");
                    bool isFirst = false;

                    if (startTime.HasValue)
                    {
                        if (!isFirst)
                        {
                            builder.Append(" AND ");
                        }
                        builder.Append($"Time >= '{startTime:yyyy-MM-dd HH:mm:ss.ffffff}'");
                        isFirst = false;
                    }
                    if (startTimeGreater.HasValue)
                    {
                        if (!isFirst)
                        {
                            builder.Append(" AND ");
                        }
                        builder.Append($"Time > '{startTimeGreater:yyyy-MM-dd HH:mm:ss.ffffff}'");
                        isFirst = false;
                    }
                    if (endTime.HasValue)
                    {
                        if (!isFirst)
                        {
                            builder.Append(" AND ");
                        }
                        builder.Append($"Time < '{endTime:yyyy-MM-dd HH:mm:ss.ffffff}'");
                    }
                    builder.Append($"union all");
                }
                builder.Remove(builder.Length - 9, 9);
                //builder.Append($" limit {limit}"); //limit 写在最后一个union all 后面 可以达到所有union all  数据 limit的目的
                builder.Append(" )");

            }

            if (!string.IsNullOrWhiteSpace(order))
            {
                if (OrderDesc)
                {
                    builder.Append($" order by {order} desc");
                }
                else
                {
                    builder.Append($" order by {order} asc");
                }
            }
            if (limit.HasValue)
            {
                builder.Append($" limit {limit}");
            }
            return builder.ToString();
        }


2.2 查询子方法

public static ConcurrentDictionary<string, int> queryTaskNumTDEngine = new ConcurrentDictionary<string, int>();
        public static object queryTaskNumTaskLockerTDengine = new object();
        public int allowQueryTaskNum = 15;

        /// <summary>
        /// 查询数据
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="sql"></param>
        /// <returns></returns>
        public async Task<List<T>> Query<T>(string sql, string tablename) where T : class, new()
        {
            //if (DateTime.Now.Hour < 7)
            //{
            //    return new List<T>();
            //}
            IntPtr connCur = new IntPtr();
            bool isMltTryStillError = false;
            int reDealTimesToThrowEx = 2; //重新执行次数
            try
            {
                #region 限制访问数量
                if (!queryTaskNumTDEngine.ContainsKey("num"))
                {
                    queryTaskNumTDEngine.TryAdd("num", 0);
                }

                if (queryTaskNumTDEngine["num"] >= allowQueryTaskNum)
                {//本次达到任务数量,就类似加锁等待 ,
                    while (1 == 1)
                    {
                        lock (queryTaskNumTaskLockerTDengine)
                        {
                            if (queryTaskNumTDEngine["num"] <= allowQueryTaskNum - 1)
                            {
                                break;
                            }
                        }
                        await Task.Delay(50);
                    }
                }
                lock (queryTaskNumTaskLockerTDengine)
                {
                    //等到任务数减少到指定值, 继续执行,并增加tasknum
                    queryTaskNumTDEngine["num"] = (int)queryTaskNumTDEngine["num"] + 1;
                    LogHelper.Info("TDengine当前query线程数:" + queryTaskNumTDEngine["num"]);
                }
                #endregion

                connCur = connect(tablename);

                //lock (ReadWriteLocker)
                //{//目前该控件多线程读写会报错,先加锁
                //res = TDengine.Query(connDic[tablename], sql);

                //存在读取或者写入突然停止也不报错的情况,超时重新执行,执行三次还不行抛出异常

                //LogHelper.Info("TDengine读111111111111");

                IntPtr res = new IntPtr();

                Delegate_TDrun Delegate_run = new Delegate_TDrun(ExecuteSqlInDB);
                var workTask = Task.Run(() => Delegate_run.Invoke(connCur, sql));

                int delayMiniSecond = 10;//多少微妙循环判断一次执行结果
                var delay = TimeSpan.FromMilliseconds(delayMiniSecond);
                int secondsToStop = 100;//多少秒没返回结果 重新执行
                int whileLoopTime = 0; //while循环次数

                while (!workTask.IsCompleted)
                {
                    await Task.Delay(delay);//每隔0.01秒判断一下是否完成
                    //Thread.Sleep(100);
                    ++whileLoopTime;
                    if (whileLoopTime % (secondsToStop * 1000 / delayMiniSecond) == 0)
                    { //如果60秒还拿不出数据,重新获取,重新获取两次还拿不出数据 抛出异常
                        reDealTimesToThrowEx--;
                        TDengine.Close(connCur);
                        if (reDealTimesToThrowEx < 0)
                        {
                            isMltTryStillError = true;
                            throw new Exception(tablename + "时序库读取数据没有结果重新执行次数:" + reDealTimesToThrowEx + " sql:" + sql);
                        }
                        connCur = connect(tablename);
                        Delegate_run = new Delegate_TDrun(ExecuteSqlInDB);
                        workTask = Task.Run(() => Delegate_run.Invoke(connCur, sql));
                        LogHelper.Error("Get" + tablename + "重新获取reDealTimesToThrowEx:" + reDealTimesToThrowEx);
                    }
                }
                res = workTask.Result;
                workTask.Dispose();

                //LogHelper.Info("TDengine读2222222222");


                //var res = ExecuteSqlInDB(connCur, sql);



                if (TDengine.ErrorNo(res) != 0) //conn == IntPtr.Zero //新版本, TDengine.ErrorNo(res) = 0  TDengine.Error(res)是 success,  conn 也 == IntPtr.Zero 
                {
                    if (conn == IntPtr.Zero)
                    {
                        LogHelper.Error($"TDengine查询报错:{tablename} 连接情况:{conn.ToString()} ");
                    }
                    else
                    {
                        LogHelper.Error($"TDengine查询报错2:{tablename} 连接情况2:{conn.ToString()} ");
                    }
                    LogHelper.Error($"TDengine查询报错:{tablename} ,错误号:{TDengine.ErrorNo(res)} ,错误信息: {TDengine.Error(res)} ,sql语句:{sql} ");
                    return new List<T>();
                }

                var fieldCount = TDengine.FieldCount(res);
                var fieldInfos = TDengine.FetchFields(res);
                //LogHelper.Info("TDengine读333333333333");
                var result = new List<T>();
                IntPtr currentRow;
                while ((currentRow = TDengine.FetchRows(res)) != IntPtr.Zero)
                {
                    var source = TDengine.FetchLengths(res);
                    var target = new int[fieldCount];
                    Marshal.Copy(source, target, 0, fieldCount);
                    var properties = typeof(T).GetProperties();
                    var propertyMap = new Dictionary<string, PropertyInfo>(properties.Length, StringComparer.OrdinalIgnoreCase);
                    foreach (var property in properties)
                    {
                        var attribute = property.GetCustomAttribute(typeof(Column));
                        var attributeTDengine = property.GetCustomAttribute(typeof(TDColumn));

                        if (attribute != null && attribute is Column column)
                        {//利用之前influxdb的Column 属性继续判断
                            if (column.IsTimestamp)
                            {
                                propertyMap.Add("time", property);
                            }
                            else
                            {
                                if (attributeTDengine != null && attributeTDengine is TDColumn columnTD)
                                {//TDengine 优先判断TDColumn 特性(TDColumn 的name 是数据库实际存的字段名)
                                    propertyMap.Add(!string.IsNullOrWhiteSpace(columnTD.Name) ? columnTD.Name : property.Name, property);
                                }
                                else
                                {
                                    propertyMap.Add(!string.IsNullOrWhiteSpace(column.Name) ? column.Name : property.Name, property);
                                }
                            }
                        }
                    }
                    var entity = new T();
                    for (int i = 0; i < fieldCount; i++)
                    {
                        var meta = fieldInfos[i];
                        var data = Marshal.ReadIntPtr(currentRow, IntPtr.Size * i);
                        if (data == IntPtr.Zero || !propertyMap.ContainsKey(meta.name))
                        {
                            continue;
                        }
                        switch ((TDengineDataType)meta.type)
                        {
                            case TDengineDataType.TSDB_DATA_TYPE_BOOL:
                                var @bool = Marshal.ReadByte(data) != 0;
                                propertyMap[meta.name].SetValue(entity, @bool);
                                break;

                            case TDengineDataType.TSDB_DATA_TYPE_TINYINT:
                                var @sbyte = (sbyte)Marshal.ReadByte(data);
                                propertyMap[meta.name].SetValue(entity, @sbyte);
                                break;

                            case TDengineDataType.TSDB_DATA_TYPE_SMALLINT:
                                var @short = (short)Marshal.ReadByte(data);
                                propertyMap[meta.name].SetValue(entity, @short);
                                break;

                            case TDengineDataType.TSDB_DATA_TYPE_INT:
                                var @int = (int)Marshal.ReadByte(data);
                                propertyMap[meta.name].SetValue(entity, @int);
                                break;

                            case TDengineDataType.TSDB_DATA_TYPE_BIGINT:
                                long v5 = Marshal.ReadInt64(data);
                                if (meta.name == "channelid")
                                {//channelid 后台存的是bigint 获取后转成string使用
                                    propertyMap[meta.name].SetValue(entity, v5.ToString());
                                }
                                else
                                {
                                    propertyMap[meta.name].SetValue(entity, v5);
                                }
                                break;

                            case TDengineDataType.TSDB_DATA_TYPE_FLOAT:
                                var @float = (float)Marshal.ReadByte(data);
                                propertyMap[meta.name].SetValue(entity, @float);
                                break;

                            case TDengineDataType.TSDB_DATA_TYPE_DOUBLE:
                                var @double = (double)Marshal.PtrToStructure(data, typeof(double));
                                if (propertyMap[meta.name].PropertyType.FullName.Contains("System.Decimal"))
                                {
                                    propertyMap[meta.name].SetValue(entity, Convert.ToDecimal(@double));
                                }
                                else
                                {
                                    propertyMap[meta.name].SetValue(entity, @double);
                                }
                                break;

                            case TDengineDataType.TSDB_DATA_TYPE_BINARY:
                            case TDengineDataType.TSDB_DATA_TYPE_NCHAR:
                                var @stringAnsi = Marshal.PtrToStringUTF8(data, target[i]);
                                propertyMap[meta.name].SetValue(entity, @stringAnsi);
                                break;

                            case TDengineDataType.TSDB_DATA_TYPE_TIMESTAMP:
                                var @timepStamp = Marshal.ReadInt64(data);
                                if (propertyMap[meta.name].PropertyType.FullName.Contains("System.DateTime"))
                                {

                                    //var @time1 = timepStamp.ToDateTime();
                                    if (tablename == "Tmp2Data")
                                    {
                                        timepStamp = timepStamp / 1000; //微秒除以1000转换成毫秒来计算时间
                                    }
                                    var @time = timepStamp.TimeStampToDateTime(inMilli: true);
                                    propertyMap[meta.name].SetValue(entity, @time);
                                }
                                else
                                {
                                    propertyMap[meta.name].SetValue(entity, @timepStamp);
                                }
                                break;

                            case TDengineDataType.TSDB_DATA_TYPE_USMALLINT:
                                var @ushort = (ushort)Marshal.ReadByte(data);
                                propertyMap[meta.name].SetValue(entity, @ushort);
                                break;

                            case TDengineDataType.TSDB_DATA_TYPE_UINT:
                                var @uint = (uint)Marshal.ReadByte(data); ;
                                propertyMap[meta.name].SetValue(entity, @uint);
                                break;

                            case TDengineDataType.TSDB_DATA_TYPE_UBIGINT:
                                var @ulong = (ulong)Marshal.ReadByte(data);
                                propertyMap[meta.name].SetValue(entity, @ulong);
                                break;
                        }
                    }
                    result.Add(entity);
                }
                //LogHelper.Info("TDengine读444444444444");
                TDengine.FreeResult(res);
                //LogHelper.Info("TDengine读55555555555");
                return result;
                //}

            }
            catch (Exception ex)
            {
                LogHelper.Info("TDengine读报错:" + ex.ToString() + "_trace_" + ex.StackTrace.ToString()); ;
                throw ex;
            }
            finally
            {
                if (reDealTimesToThrowEx < 0)
                {
                    LogHelper.Error(tablename + "时序库读取数据读不出来关闭连接sql:" + sql);
                }
                lock (queryTaskNumTaskLockerTDengine)
                {
                    queryTaskNumTDEngine["num"] = (int)queryTaskNumTDEngine["num"] - 1;
                }
                //LogHelper.Info("TDengine读66666666666");

                TDengine.Close(connCur);

                //if (!isMltTryStillError)
                //{//多次失败这里close会卡住停止执行
                //    TDengine.Close(connCur);
                //}
                //else
                //{
                //    if (conn == IntPtr.Zero)
                //    {
                //        LogHelper.Error("TD插入close处:conn状态 IntPtr.Zero");
                //    }
                //    else
                //    {
                //        LogHelper.Error("TD插入close处:conn状态 非IntPtr.Zero");
                //    }
                //}


                //Close();
            }
        }

        private IntPtr ExecuteSqlInDB(IntPtr curConn, string sql)
        {
            IntPtr res = TDengine.Query(curConn, sql);
            LogHelper.Info("TD正在写入数据");
            return res;
        }

3插入：
 public async Task<string> AddHisData(List<HisDataDto> insertData, bool isResetTime = true)
        {

            if (insertData == null || insertData.Count == 0)
            {
                return "暂无数据";
            }

            try
            {

                var isSuccess = await InsertData(insertData, "HisData", 10000);
                if (isSuccess)
                {
                    return await Task.FromResult("插入成功");
                }
                return await Task.FromResult("插入失败");

            }
            catch (Exception ex)
            {
                LogHelper.Error("DataBLL报错AddHisData_Tdeint:" + ex.ToString() + "trace--" + ex.StackTrace);
                throw ex;
            }
        }

3.1插入子方法
public async Task<bool> InsertData<T>(IEnumerable<IGrouping<string, T>> infos, string tableName) where T : class
        {
            var propertySet = new List<PropertyInfo>();
            var filedString = TDengineSqlData.BuildFileds<T>(ref propertySet);

            var builder = new StringBuilder("INSERT INTO ");
            foreach (var item in infos)
            {
                var sb = new StringBuilder($"{tableName + item.Key} USING {tableName} TAGS('{item.Key}') ({filedString}) VALUES ");
                foreach (var it in item)
                {
                    sb.Append("(");
                    foreach (var property in propertySet)
                    {
     
                        sb.Append(TDengineSqlData.BuildFileValue(property, it));
                        sb.Append(",");
 
                    }

                    sb.Remove(sb.Length - 1, 1);
                    sb.Append(") ");
                }
                builder.Append(sb.ToString());
            }
            //LogHelper.Info("UploadHisData--Data-Data插入HisData:22222222+sql"+ builder.ToString());
            bool ret = await Insert(builder.ToString(), tableName); //true;// 
            if (!ret)
            {
                LogHelper.Error("插入数据失败tableName" + tableName + "SQL:" + builder.ToString().Substring(0, 5000));
            }

            return ret;
        }

3.1 插入子方法
public static string BuildFileValue<T>(PropertyInfo property, T t)
        {
            var value = property.GetValue(t);
            if (value == null)
            {
                return "NULL";
            }
            else if (property.PropertyType == typeof(string))
            {
                return $"'{value}'";
            }
            else if (property.PropertyType == typeof(DateTime))
            {
                var time = (DateTime)value;
                return $"'{time:yyyy-MM-dd HH:mm:ss.ffffff}'";
            }
            else if (property.PropertyType == typeof(DateTime?))
            {
                var time = (DateTime?)value;
                return $"'{time:yyyy-MM-dd HH:mm:ss.ffffff}'";
            }
            else if (property.PropertyType == typeof(TimeSpan))
            {
                var span = (TimeSpan)value;
                return $"'{span:yyyy-MM-dd HH:mm:ss.ffffff}'";
            }
            else
            {
                return $"{value}";
            }
        }

3.3 插入子方法
public async Task<bool> Insert(string sql, string tablename)
        {
            IntPtr conn = new IntPtr();
            int reDealTimesToThrowEx = 2; //重新执行次数
            bool isMltTryStillError = false;//重试多次后任然错误;
            try
            {
                #region 限制访问数量
                if (!insertTaskNumTDEngine.ContainsKey("num"))
                {
                    insertTaskNumTDEngine.TryAdd("num", 0);
                }

                if (insertTaskNumTDEngine["num"] >= allowinsertTaskNum)
                {//本次达到任务数量,就类似加锁等待 ,
                    while (1 == 1)
                    {
                        lock (insertTaskNumTaskLockerTDengine)
                        {
                            if (insertTaskNumTDEngine["num"] <= allowinsertTaskNum - 1)
                            {
                                break;
                            }
                        }
                        await Task.Delay(50);
                    }
                }
                lock (insertTaskNumTaskLockerTDengine)
                {
                    //等到任务数减少到指定值, 继续执行,并增加tasknum
                    insertTaskNumTDEngine["num"] = (int)insertTaskNumTDEngine["num"] + 1;
                    LogHelper.Info("TDengine当前insert线程数:" + insertTaskNumTDEngine["num"]);
                }
                #endregion

                conn = connect(tablename);

                ////存在读取或者写入突然停止也不报错的情况,超时重新执行,执行三次还不行抛出异常
                //IntPtr res = new IntPtr();
                //res = TDengine.Query(connDic[tablename], sql);


                Delegate_TDrun Delegate_run = new Delegate_TDrun(ExecuteSqlInDB);
                var workTask = Task.Run(() => Delegate_run.Invoke(conn, sql));

                int delayMiniSecond = 10;//多少微妙循环判断一次执行结果
                var delay = TimeSpan.FromMilliseconds(delayMiniSecond);
                int secondsToStop = 180;//多少秒没返回结果 重新执行
                int whileLoopTime = 0; //while循环次数
                while (!workTask.IsCompleted)
                {
                    await Task.Delay(delay);//每隔0.01秒判断一下是否完成
                    //Thread.Sleep(100);
                    ++whileLoopTime;
                    if (whileLoopTime % (secondsToStop * 1000 / delayMiniSecond) == 0)
                    { //如果secondsToStop秒还拿不出数据,重新获取,重新获取两次还拿不出数据 抛出异常
                        reDealTimesToThrowEx--;
                        TDengine.Close(conn);
                        if (reDealTimesToThrowEx < 0)
                        {
                            isMltTryStillError = true;
                            throw new Exception(tablename + "时序库插入数据没有结果重新执行次数:" + reDealTimesToThrowEx + " sql:" + sql);
                        }
                        conn = connect(tablename);

                        Delegate_run = new Delegate_TDrun(ExecuteSqlInDB);
                        workTask = Task.Run(() => Delegate_run.Invoke(conn, sql));
                        LogHelper.Error("Add" + tablename + "重新插入reDealTimesToThrowEx:" + reDealTimesToThrowEx);
                    }
                }

                IntPtr res = workTask.Result;

                if (TDengine.ErrorNo(res) != 0) //res == IntPtr.Zero) || 
                {
                    LogHelper.Error(@$"TDengine插入{tablename}报错:" + TDengine.Error(res));
                    throw new ArgumentException("reason: " + TDengine.Error(res));
                }
                var ret = TDengine.AffectRows(res) > 0;
                TDengine.FreeResult(res);
                return ret;

            }
            catch (Exception ex)
            {
                LogHelper.Error(@$"TDengine插入{tablename}报错ex:" + ex.ToString());
                throw ex;
            }
            finally
            {
                if (reDealTimesToThrowEx < 0)
                {
                    LogHelper.Error(tablename + "时序库插入数据插入失败3次关闭连接sql:" + sql);
                }
                lock (insertTaskNumTaskLockerTDengine)
                {
                    insertTaskNumTDEngine["num"] = (int)insertTaskNumTDEngine["num"] - 1;
                }
                TDengine.Close(conn);

            }
        }

3.4 插入子方法
      private IntPtr ExecuteSqlInDB(IntPtr curConn, string sql)
        {
            IntPtr res = TDengine.Query(curConn, sql);
            LogHelper.Info("TD正在写入数据");
            return res;
        }

**Comment by chenjilai** [comment]
外网调用iis 就是多线程调用的情况容易复现。

**Comment by sangshuduo** [comment]
如果 csharp 代码单独运行没问题，我认为和 TDengine 及连接器无关

**Comment by chenjilai** [comment]
连接都是用 官方.nuget\packages\tdengine.connector\3.0.2  插件 连接和查询的， 客户端释放端口都是插件托管的。 应该和tdengine.connector关系非常大。
