### ISSUE TITLE
请教关于REST API token的问题

### ISSUE THREAD

**Issue by hfhtsoft** [taosdata/TDengine#21054]
版本3.0
说明文档中的示例
curl -L -H "Authorization: Basic cm9vdDp0YW9zZGF0YQ==" -d "select * from demo.d1001" 192.168.0.1:6041/rest/sql

这里的token  cm9vdDp0YW9zZGF0YQ== 是固定么？
如果不是固定，怎么生成这个token？或者如何修改这个token，这个cm9vdDp0YW9zZGF0YQ==在我新装的服务器上也是可以通过认证的，这样不就是谁都可以访问了么？

另外，curl http://<fqnd>:<port>/rest/login/<username>/<password>
这样获取的token有过期时间么？

**Comment by sangshuduo** [comment]
可以在修改默认密码后使用自定义授权码，参考文档： https://docs.taosdata.com/connector/rest-api/#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8E%88%E6%9D%83%E7%A0%81

basic token 就是 base64 转的 "root:taosdata"

没有过期时间

**Comment by hfhtsoft** [comment]
好的。谢谢。
我修改了root的密码，但是这个cm9vdDp0YW9zZGF0YQ==仍然可以生效，
后来重启了taosadapter 才生效的。这个应该是个bug。
