### ISSUE TITLE
关于TDengine升级后，TDengine-client如何处理？

### ISSUE THREAD

**Issue by elysian-gc** [taosdata/TDengine#21089]
您好，我们现在使用的TDengine 3.0.3.1版本。
在未来使用中，会根据官方发布的版本升级，但是我们发现TDengine-client未向下兼容。
这就导致如果我们需要升级TDengine  server时，只能在升级它后再升级TDengine-client，造成更长的中断时间；
目前TDengine-client 编译在alpine镜像中，请问有更好的办法避免长时间的停机吗？

**Comment by sangshuduo** [comment]
可以考虑应用使用 WebSocket 或者 REST API

**Comment by elysian-gc** [comment]
> 可以考虑应用使用 WebSocket 或者 REST API

好的，后面会考虑向下兼容吗？

**Comment by sangshuduo** [comment]
> > 可以考虑应用使用 WebSocket 或者 REST API
> 
> 好的，后面会考虑向下兼容吗？

现在最末一位小版本是兼容的，次级版本还不兼容。完全向下兼容会有个过程
