### ISSUE TITLE
关于流式计算

### ISSUE THREAD

**Issue by yuao1112** [taosdata/TDengine#21080]
**General Questions**
问个场景，有个数据按小时存储（该数据只保留一个月，数据库配置keep一个月的时间，过期后会删除），通过流式计算，聚合成按天的数据（该数据长期），这种能实现麽？
1、尝试了下流计算，如果进行了数据删除，对应的聚合也会发生变化
2、通过什么参数可以配置，实现上述的场景呢？

**Comment by nieyuan1980** [comment]
创建流式计算时，增加一个fill_history 0选项
