### ISSUE TITLE
Issues related to stream processing

### ISSUE THREAD

**Issue by yuao1112** [taosdata/TDengine#21093]
Client Version:3.0.4.0
一、one question
**Bug Description**
![image](https://user-images.githubusercontent.com/24371179/234512088-ebc390ee-2dc8-4cac-b21d-37c2588a2976.png)

**To Reproduce**
1. cteate stable
CREATE STABLE electrichs (ts TIMESTAMP,valueh INT) TAGS (devicetype VARCHAR(16), subtype VARCHAR(16), mainversion INT UNSIGNED, region VARCHAR(16), batchnumber VARCHAR(10), uuid VARCHAR(32), uid BIGINT UNSIGNED);
2. create two stream

CREATE STREAM sum_electrich_s8 TRIGGER AT_ONCE WATERMARK 3d IGNORE EXPIRED 0 INTO sum_electrich8 SUBTABLE(CONCAT('test8_', tname)) AS SELECT _wstart, count(*), avg(valueh) FROM electrichs PARTITION BY tb
name tname INTERVAL(1d);

CREATE STREAM sum_electrich_s9 TRIGGER AT_ONCE WATERMARK 3d IGNORE EXPIRED 1 INTO sum_electrich9 SUBTABLE(CONCAT('test9_', tname)) AS SELECT _wstart, count(*), avg(valueh) FROM electrichs PARTITION BY tb
name tname INTERVAL(1d);
4. insert sql
INSERT INTO electrich_2212135375917160000134298f1f3701_0_10500351 USING electrichs (deviceType,subType,mainVersion,region,batchNumber,uuid,uid) TAGS('mts960','eu',4,'ap-dev','6000012212','221213537591716
0000134298f1f3701', 10500350) (ts,valueH) VALUES (1682459520000, 0)(1682463120000, 1)(1682466720000, 2)(1682470320000, 3)(1682473920000, 4)(1682477520000, 5);

二、second question
创建两个流，分别写入25、26号数据，都无聚合数据得产生
![image](https://user-images.githubusercontent.com/24371179/234513976-8272ee0d-f187-44da-8dcd-8acd33773ac9.png)
再次写入25号的数据，无聚合数据
![image](https://user-images.githubusercontent.com/24371179/234514326-9726d9d9-944f-4ca4-94c7-4c3afcd2ec21.png)
修改25号的数据，无聚合数据
![image](https://user-images.githubusercontent.com/24371179/234514468-021cc70a-21a3-41d1-a4b9-21c15d60eb2b.png)
写入26号的数据，获取到26号聚合数据
![image](https://user-images.githubusercontent.com/24371179/234514578-52a6c918-9f0a-4409-bd2a-405f9229250c.png)
将26号的后两条数据的值都改为6，【sum_electrich_s8 】流计算结果正确，【sum_electrich_s9 】流计算结果异常
![image](https://user-images.githubusercontent.com/24371179/234514758-cf97cb3f-cefc-46c5-93b0-f718ad735119.png)

**Comment by 54liuyao** [comment]
能连你的环境看下吗

**Comment by yuao1112** [comment]
> 能连你的环境看下吗

可以 我的微信：yu_ao1112

**Comment by yuao1112** [comment]
> 能连你的环境看下吗

可以 邮件回复您了
