### ISSUE TITLE
Grafana无法获取TDengine的信息该怎么解决

### ISSUE THREAD

**Issue by quzhen25** [taosdata/TDengine#21092]
参考案例：
EMQX+TDengine 搭建 MQTT 物联网可视化平台
https://www.emqx.com/zh/blog/emqx-tdengine-grafana
版本：
EMQ X Broker : 4.1.5
TDengine : 3.0.4.0
Grafana : 9.4.7

1.通过mock.js发送数据给EMQX
![mockjs](https://user-images.githubusercontent.com/131854845/234508048-2bc45908-80f4-4dfb-86e2-e563fb2089ce.png)

2.EMQX接收到信号并通过Web发送给TDengine
![QQ截图20230426155548](https://user-images.githubusercontent.com/131854845/234508417-c996ea63-af4f-47f5-8502-5d5203bb822a.png)

3.taos可以查看到数据量
![QQ截图20230426155658](https://user-images.githubusercontent.com/131854845/234508706-46b56a70-3cd9-4f57-8c81-2fd91016f77c.png)

4.添加Grafana数据源工作正常
![数据源](https://user-images.githubusercontent.com/131854845/234509042-4991cc87-2443-4c74-ac23-b0928f74f307.png)
这里我用的是IP:6041,账号密码为root/taosdata,令牌为空
=========================================
情况一:我通过默认import增加18180仪表
![QQ截图20230426160054](https://user-images.githubusercontent.com/131854845/234509781-e3332dc1-c1d0-4340-8362-23045095d29c.png)
![QQ截图20230426160212](https://user-images.githubusercontent.com/131854845/234510068-1d9010ac-2745-437e-9230-3b8452196fa1.png)

显示数据为空
![QQ截图20230426160235](https://user-images.githubusercontent.com/131854845/234510180-ed041c72-5fb9-4819-ad00-8baa4da930ea.png)

情况二：我通过增加新的仪表盘显示数据为空
![QQ截图20230426160647](https://user-images.githubusercontent.com/131854845/234511265-2459bd9b-2960-4939-a1ad-745246891672.png)

Input Sql : select avg(temperature), avg(humidity), avg(volume), avg(PM10), avg(pm25), avg(SO2), avg(NO2), avg(CO)  from test.sensor_data where coll_time >= $from and coll_time < $to interval($interval)

请问该排查什么地方解决这个问题？
 grafana 的query inspector我没找到在什么位置
@sangshuduo

**Comment by quzhen25** [comment]
我找到了query inspector
它的结果如下
![QQ截图20230426161059](https://user-images.githubusercontent.com/131854845/234512608-d615b19c-f4e6-40fe-bf2a-ed77570cd2b7.png)
`{
  "request": {
    "url": "api/datasources/proxy/uid/2XNSlqP4z/sql",
    "data": "select avg(temperature), avg(humidity), avg(volume), avg(PM10), avg(pm25), avg(SO2), avg(NO2), avg(CO)  from test.sensor_data where coll_time >= '2023-04-26T07:11:04.834Z' and coll_time < '2023-04-26T08:11:04.834Z' interval(2000a)",
    "method": "POST",
    "hideFromInspector": false
  },
  "response": {
    "code": 0,
    "column_meta": [
      [
        "avg(temperature)",
        "DOUBLE",
        8
      ],
      [
        "avg(humidity)",
        "DOUBLE",
        8
      ],
      [
        "avg(volume)",
        "DOUBLE",
        8
      ],
      [
        "avg(pm10)",
        "DOUBLE",
        8
      ],
      [
        "avg(pm25)",
        "DOUBLE",
        8
      ],
      [
        "avg(so2)",
        "DOUBLE",
        8
      ],
      [
        "avg(no2)",
        "DOUBLE",
        8
      ],
      [
        "avg(co)",
        "DOUBLE",
        8
      ]
    ],
    "data": [],
    "rows": 0
  }
}`

**Comment by sangshuduo** [comment]
没有时间戳

**Comment by quzhen25** [comment]
该如何设置？

**Comment by sangshuduo** [comment]
SQL 改成 select \_wstart as ts, avg(... 后面不变

**Comment by quzhen25** [comment]
![QQ截图20230426170141](https://user-images.githubusercontent.com/131854845/234525782-ee99f6b8-213a-4f89-b3c4-578a9983442f.png)
修改完后，出现了时间节点为今天早晨8:00-9:00
下面有一个令牌不识别的提示

**Comment by sangshuduo** [comment]
感觉是 SQL 写的有问题，你先写一个极短的 SQL 把通路打通，再写完整的，看看问题出在哪

**Comment by quzhen25** [comment]
通过了，非常感谢。
是SQL代码的问题
如题开头的案例代码为：
> select avg(temperature), avg(humidity), avg(volume), avg(PM10), avg(pm25), avg(SO2), avg(NO2), avg(CO)  from test.sensor_data where coll_time >= $from and coll_time < $to interval($interval)

后来修改了一下代码：
> select _wstart as ts, avg(temperature), avg(humidity), avg(volume), avg(PM10), avg(pm25), avg(SO2), avg(NO2), avg(CO)  from test.sensor_data where ts >= $from and ts < $to interval($interval)
然后就成功运行了
![image](https://user-images.githubusercontent.com/131854845/234558661-078eae60-9b94-4860-b3e4-71fdfcbea1d6.png)

**Comment by quzhen25** [comment]
桑哥我在taos里建立了mqtt数据库，并在下面增加了t_light表
![image](https://user-images.githubusercontent.com/131854845/235298822-0d8c7d23-1eeb-46a6-a451-c5642809c017.png)
t_light表中数据如下：
![image](https://user-images.githubusercontent.com/131854845/235298849-3283f789-30b8-4ca9-83f2-34af18f94cd5.png)
在grafana中，如何才能提取出这个数值加以引用 ？
input SQL报错：
select _wstart as ts, payload from mqtt.t_light where ts >= $from and ts < $to interval($interval)
![image](https://user-images.githubusercontent.com/131854845/235298948-3ce336c4-9f5a-4791-80bc-54c97c92dc05.png)
我不知道写它的语法，这条SQL该如何修改或者有没有相关的参考信息？
@sangshuduo

**Comment by sangshuduo** [comment]
https://docs.taosdata.com/develop/query-data/#%E9%99%8D%E9%87%87%E6%A0%B7%E6%9F%A5%E8%AF%A2%E3%80%81%E6%8F%92%E5%80%BC 用聚合函数和 interval 配合
