### ISSUE TITLE
TDengine-client-3.0.4.0-macOS-x64 在macOS 10.13.6上无法运行

### ISSUE THREAD

**Issue by maczh** [taosdata/TDengine#21099]
**Bug Description**
环境： macOS 10.13.6 High Sierra
CPU:  Intel i7-8700K
Mem: 16GB
安装客户端: TDengine-client-3.0.4.0-macOS-x64.pkg

运行taos报错:
dyld: Library not loaded: /opt/taos/workspace/3.0_releaseVersion/TDinternal/community/debug/build/lib/libtaos.1.dylib
  Referenced from: /usr/local/bin/taos
  Reason: no suitable image found.  Did find:
	/usr/local/lib/libtaos.1.dylib: cannot load 'libtaos.1.dylib' (load command 0x80000034 is unknown)
	/usr/local/Cellar/tdengine/3.0.4.0/driver/libtaos.3.0.4.0.dylib: cannot load 'libtaos.3.0.4.0.dylib' (load command 0x80000034 is unknown)
Abort trap: 6

/usr/local/lib目录列表
![image](https://user-images.githubusercontent.com/16284319/234572683-5c273603-7b4c-4438-a8c1-9a55bf431a18.png)
![image](https://user-images.githubusercontent.com/16284319/234572850-4411c672-86e3-4b9f-8e1b-2ea1ad75cc58.png)

我测试在我的macbook pro (2020,Intel, macOS 13)上安装使用正常，在另外一台macOS 12上安装也正常

**Comment by sangshuduo** [comment]
终端里执行 file /usr/local/lib/libtaos* 输出什么？

**Comment by siaron** [comment]
macos 系统12.6.1 安装 TDengine-client-3.0.5.1-macOS-x64.pkg  报
![image](https://github.com/taosdata/TDengine/assets/13701232/fc051806-744d-4c24-99fa-25a3fb56f926)
直接安装不了。

**Comment by sangshuduo** [comment]
@siaron 看一下 md5 值是不是 58658cfc3fb9b4cf0f6b1a6a3173fbc4

**Comment by siaron** [comment]
Desktop/ $ md5 TDengine-client-3.0.5.1-macOS-x64.pkg                                                                                                                                         [13:05:08]
MD5 (TDengine-client-3.0.5.1-macOS-x64.pkg) = 98920afa74a9ef3b8ad270380ec01ead

**Comment by sangshuduo** [comment]
> Desktop/ $ md5 TDengine-client-3.0.5.1-macOS-x64.pkg [13:05:08] MD5 (TDengine-client-3.0.5.1-macOS-x64.pkg) = 98920afa74a9ef3b8ad270380ec01ead

应该是没下完整或者正确的安装包
