### ISSUE TITLE
on windows，the taos.cfg is not work,

### ISSUE THREAD

**Issue by fushuangqiu** [taosdata/TDengine#21106]
**Bug Description**
on windows 11，3.0.3.1 the taos.cfg is not work,taosd.exe start the cfg file is c:\TDEngine\cfg\\\\taos.cfg, the" \\\\ "is right?

**Comment by fushuangqiu** [comment]
windows 集群功能没实现呢，不好意思

**Comment by sangshuduo** [comment]
试试最新版本， Windows 可以搭集群
