### ISSUE TITLE
相同的查询条件 使用== 和 in查询出来的结果返回的不一样 

### ISSUE THREAD

**Issue by hert525** [taosdata/TDengine#21115]
相同的查询条件 使用== 和 in查询出来的结果返回的不一样 版本为3.0.3.2 
[图片]

**Comment by hert525** [comment]
![image](https://user-images.githubusercontent.com/19421393/234846497-dfcbc47b-45bc-4b61-9044-7c43ff58867f.png)

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
