### ISSUE TITLE
C# connector not honoring multiple IP addresses in the config

### ISSUE THREAD

**Issue by sawo1337** [taosdata/TDengine#21117]
When using taos, you can specify ifdown IP address when using a cluster so if the primary IP is down, it can connect to another. This is done via the config and taos honors that. However, in the C# connector, even if you specify the config folder, it does not read the IPs apparently - if the primary host is down, it would not connect to the next one?

Sample config:

using TDengineDriver;
// ... do something ...
string host = "10.1.101.111";
string configDir = "C:/TDengine/cfg"; // For linux should it be /etc/taos.
string user = "root";
string password = "taosdata";
string db = ""; // Also can set it to the db name you want to connect.
short port = 0;

TDengine.Options((int)TDengineInitOption.TSDB_OPTION_CONFIGDIR,configDir);

Config:
 
firstEp                   10.1.101.111:6030
secondEp                    10.1.101.112:6030
secondEp                    10.1.101.113:6030

So even though configDir is populated, it would only connect to 10.1.101.111 and fail if it's not successful. Is there another way to specify multiple hosts in the C# connector?

**Comment by sangshuduo** [comment]
Please refer to https://docs.tdengine.com/deployment/deploy/#start-cluster for how to start a cluster

**Comment by sawo1337** [comment]
> Please refer to https://docs.tdengine.com/deployment/deploy/#start-cluster for how to start a cluster

We have a cluster with three nodes set up and it works fine when used via the CLI, but can't seem to get C# to honor the high availability settings:

![image](https://user-images.githubusercontent.com/31248804/235091108-22957ad9-e4e0-4b54-9cbb-0388abcd0c02.png)

**Comment by sangshuduo** [comment]
> > Please refer to https://docs.tdengine.com/deployment/deploy/#start-cluster for how to start a cluster
> 
> We have a cluster with three nodes set up and it works fine when used via the CLI, but can't seem to get C# to honor the high availability settings:
> 
> ![image](https://user-images.githubusercontent.com/31248804/235091108-22957ad9-e4e0-4b54-9cbb-0388abcd0c02.png)

C# or any connector is just a wrapper of the client library. The mechanism is the same. I do not quite understand what your problem is. Would you please explain how to reproduce?
