### ISSUE TITLE
build fail on Ubuntu20.04 and gcc-12.1

### ISSUE THREAD

**Issue by Absoler** [taosdata/TDengine#21129]
**Bug Description**
when I try to build 3.0.4.1 from source, I meet this problem report when `make`:

[ 98%] Linking C executable ../../../build/bin/taosdump
/usr/bin/ld: ../../../build/lib/libsnappy.a(snappy.cc.o): in function \`std::__new_allocator<snappy::SnappySinkAllocator::Datablock>::allocate(unsigned long, void const*)':
snappy.cc:(.text._ZNSt15__new_allocatorIN6snappy19SnappySinkAllocator9DatablockEE8allocateEmPKv[_ZNSt15__new_allocatorIN6snappy19SnappySinkAllocator9DatablockEE8allocateEmPKv]+0x45): undefined reference to \`std::__throw_bad_array_new_length()'
/usr/bin/ld: ../../../build/lib/libsnappy.a(snappy.cc.o): in function \`std::__new_allocator<char*>::allocate(unsigned long, void const*)':
snappy.cc:(.text._ZNSt15__new_allocatorIPcE8allocateEmPKv[_ZNSt15__new_allocatorIPcE8allocateEmPKv]+0x45): undefined reference to \`std::__throw_bad_array_new_length()'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/taos-tools/src/CMakeFiles/taosdump.dir/build.make:151: build/bin/taosdump] Error 1
make[1]: *** [CMakeFiles/Makefile2:4388: tools/taos-tools/src/CMakeFiles/taosdump.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 98%] Built target taosd
make: *** [Makefile:152: all] Error 2

the procedure I take is:
cd TDengine-ver-3.0.4.1
mkdir build && mkdir prefix
cd build
cmake -DBUILD_TOOLS=true -DCMAKE_INSTALL_PREFIX=/home/TDengine-ver-3.0.4.1/prefix/ ..
make -j 16

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - 64GB memory, 1T disk space
 - TDengine Version 3.0.4.1
 - C and CXX compiler gcc-12.1 and g++-12.1

**Comment by sangshuduo** [comment]
AFAIK, the official gcc package of 20.04 is not 12.1. I don't know what way like to build from source or binary package you install it. I use gcc 12.1 with Ubuntu 22.04 and gcc 12.2 with Arch Linux. I see taosdump can be built out with those "standard" environments. Could you try it with an official combo?
