### ISSUE TITLE
python集成TD，报错AttributeError: /usr/lib/libtaos.so: undefined symbol: taos_fetch_lengths

### ISSUE THREAD

**Issue by WangChao233** [taosdata/TDengine#2112]
**Bug Description**

**To Reproduce**

2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**
这是我dockerfile里关于TD的代码：
COPY . .
RUN pip install src/connector/python/linux/python3/

RUN tar -zxvf TDengine-client.tar.gz
WORKDIR /app/TDengine-client
RUN  /app/TDengine-client/install_client.sh
其中src文件夹为TD官网源码的src文件；TDengine-client.tar.gz为TD官网的TD-linux-client安装包，均放在本地运行代码同级目录。
容器启动时，导入不了taos包，于是将容器睡眠一小时，进去，输入python，然后import taos，报错AttributeError: /usr/lib/libtaos.so: undefined symbol: taos_fetch_lengths

**Comment by Aries-Lee1991** [comment]
您好，可以把日志发一下吗，我们这边看一下。

**Comment by liu0x54** [comment]
the version of python and TDengine not match, please pull the python connector from branch master
