### ISSUE TITLE
导入数据失败

### ISSUE THREAD

**Issue by luzheneaaa** [taosdata/TDengine#21124]
把备份的数据库导入新库时失败
源库版本：3.0.2.0 目标库版本3.0.4.0
提示：
ERROR: Failed to execute taos_stmt_set_tbname(`cp_kf-dev90_m59`).reason: db is not specified
ERROR: Failed to execute taos_stmt_set_tbname(`cp_kf-dev89_45`).reason: db is not specified
ERROR: Failed to execute taos_stmt_set_tbname(`cp_kf-dev90_m32`).reason: db is not specified
ERROR: Failed to execute taos_stmt_set_tbname(`cp_kf-dev_mp_1_3_b`).reason: db is not specified

**Comment by luzheneaaa** [comment]
xy

**Comment by sangshuduo** [comment]
taosdump 什么版本？备份和恢复的参数是什么？

**Comment by luzheneaaa** [comment]
taosdump -h 127.0.0.1 -u root -taosdata -i E:\tddb\gf\zhuz\tdzz20230424 -T 8

**Comment by luzheneaaa** [comment]
导入版本：
C:\TDengine>taosdump -V
version 2.4.9, commit: 0681d8b

**Comment by luzheneaaa** [comment]
导出数据库版本：
C:\TDengine>taosdump -V
taosdump version 2.3.2, commit: d55a1f8

**Comment by sangshuduo** [comment]
> 导出数据库版本： C:\TDengine>taosdump -V taosdump version 2.3.2, commit: d55a1f8

早期版本 taosdump for windows 有个bug，后来修复了，请使用最新版本导出再导入

**Comment by luzheneaaa** [comment]
只要安装最新版3.0.4.0的客户端就可以吗？

**Comment by luzheneaaa** [comment]
只要安装最新版3.0.4.0的客户端就可以吗？


> > 导出数据库版本： C:\TDengine>taosdump -V taosdump version 2.3.2, commit: d55a1f8
> 
> 早期版本 taosdump for windows 有个bug，后来修复了，请使用最新版本导出再导入

**Comment by sangshuduo** [comment]
> 只要安装最新版3.0.4.0的客户端就可以吗？
> 
> > > 导出数据库版本： C:\TDengine>taosdump -V taosdump version 2.3.2, commit: d55a1f8
> > 
> > 
> > 早期版本 taosdump for windows 有个bug，后来修复了，请使用最新版本导出再导入

是的，查了一下在 taosdump 2.4.0 修复的。但建议直接用 3.0.4.1 带的最新版 2.5.0

**Comment by luzheneaaa** [comment]
服务器是版本是3.0.2.0，编译程序采用的客户端是3.0.4.1，可以正常通讯吗？

**Comment by sangshuduo** [comment]
如果不升级 TDegnine 就需要把 taosdump 单独复制出来，和编译对应的 TDengine 版本无关
