### ISSUE TITLE
通过超级表在TAGS里面定义bigint类型的列，查询数据使用等号的时候查询不到数据，使用大于号可以查询出来数据

### ISSUE THREAD

**Issue by xiaobaxiang** [taosdata/TDengine#21121]
**Bug Description**
通过超级表在TAGS里面定义bigint类型的列，查询数据使用等号的时候查询不到数据，使用大于号可以查询出来数据
**To Reproduce**
1.通过jdbc:TAOS-RS连接服务端。输入数据
2.使用TDengineGUI.Setup.1.0.3客户端查询数据库中的数据

**Expected Behavior**
能按匹配的id筛选数据

**Screenshots**
![image](https://user-images.githubusercontent.com/11708019/235060098-48aa95b6-13a7-4e4a-9d31-6d5f5adbbe65.png)
![image](https://user-images.githubusercontent.com/11708019/235060150-ee4afb33-07b8-4c7e-8743-ccca5feedf78.png)

**Environment (please complete the following information):**
 - OS: 通过官网docker安装https://docs.taosdata.com/get-started/docker/
 - Memory, CPU, current Disk Space
 - TDengine Version 3.0.1.4

**Additional Context**

**Comment by xiaobaxiang** [comment]
是最新的3.0.4.1 ，上面写错了

**Comment by sangshuduo** [comment]
taos shell 执行相同 SQL 输出什么？
curl 执行相同 SQL 输出什么？

**Comment by xiaobaxiang** [comment]
输出是一样的
```shell

taos> select count(1) from iot_dev_collect.ddev01s1p1 where device_id = 1649021668195905500;
       count(1)        |
========================
                     0 |
Query OK, 1 row(s) in set (0.001129s)

taos> select count(1) from iot_dev_collect.ddev01s1p1 where device_id > 1649021668195905500;
       count(1)        |
========================
                    19 |
Query OK, 1 row(s) in set (0.001034s)
```

**Comment by xiaobaxiang** [comment]
数据库我删除重新建了，在shell里面执行也是一样的问题
```shell
taos> select count(1) from iot_dev_collect.ddev01s1p1 where device_id = 1649021668195905500;
       count(1)        |
========================
                     0 |
Query OK, 1 row(s) in set (0.001129s)

taos> select count(1) from iot_dev_collect.ddev01s1p1 where device_id > 1649021668195905500;
       count(1)        |
========================
                    19 |
Query OK, 1 row(s) in set (0.001034s)
```

**Comment by sangshuduo** [comment]
select * from information_schema.ins_tags where db_name = "iot_dev_collect" and stable_name = "ddev01s1p1" and tag_name = "device_id" and tag_value >= 1649021668195905500 ;

输出什么？

**Comment by xiaobaxiang** [comment]
taos> select * from information_schema.ins_tags where db_name = "iot_dev_collect" and stable_name = "ddev01s1p1" and tag_name = "device_id" and tag_value >= 1649021668195905500 ;
Query OK, 0 row(s) in set (0.072805s)

**Comment by xiaobaxiang** [comment]
```shell
taos> select * from information_schema.ins_tags where db_name = "iot_dev_collect" and stable_name = "ddev01s1p1" and tag_name = "device_id" and tag_value >= 1649021668195905500 ;
Query OK, 0 row(s) in set (0.072805s)
```

**Comment by xiaobaxiang** [comment]
找到问题了，是TDengineGUI这个软件显示的问题，实际的id不是1649021668195905500
