### ISSUE TITLE
date format in schemeless mode

### ISSUE THREAD

**Issue by wgreen2135** [taosdata/TDengine#21135]
**General Questions**
I am streaming data from telegraf to TDengine. I am having an issue with the date-time format. Within TDengine the timestamp is in the following format:_ts

_ts
2023-05-03T01:45:14.403Z

In other clients the timestamp is in the correct datetime format as opposed to character format.
Any assistance would be greatly appreciated

**Comment by sangshuduo** [comment]
I do not quite understand your question. What are the other clients? What format do you expect? How does this format impact your application?

**Comment by wgreen2135** [comment]
I am utilizing grafana for the charting and it does not recognize this as a proper timestamp and it sees this as character but not a timestamp. I am using dbeaver and it properly translates it into a timestamp. The question is how tdengine stores the timestamp and is there a method of hone to change the format.

**Comment by sunpe** [comment]
what the data type of the `_ts` field, show it use `desc` grammar

**Comment by sangshuduo** [comment]
@wgreen2135 Please let us know what version is the TDengine and Grafana plugin..
