### ISSUE TITLE
Is it possible to group data by calendar month/year?

### ISSUE THREAD

**Issue by crazyTweek** [taosdata/TDengine#21134]
Hi everyone!
We are currently using TDengine 3.0.2 and want to create reports of our database. 

One of those metrics shall be the count of tablerows, grouped by calendarmonth and year with a result similar to that:

| count(*) | device_id | year | month |
|----------|-----------|------|-------|
| 27387922 | 988       | 2023 | 2     |
| 9354295  | 988       | 2023 | 1     |
| 26770185 | 988       | 2022 | 12    |

Can this be done with TDengine? In SQL Server you could use the [DATEPART](https://www.w3schools.com/sql/func_sqlserver_datepart.asp) function.

Thanks in advance!

Best, Florian

**Comment by yu285** [comment]
you can use : count(*)+ interval(1y)
