### ISSUE TITLE
windows  3.0.4.0 taosd crash

### ISSUE THREAD

**Issue by huoliya** [taosdata/TDengine#21141]
**Bug Description**
版本：3.0.4.0
数据规模：8亿左右
现象：查询涉及order by valueTime limit 100 时，taosd服务瞬间崩溃（不存在cpu升高或者内存暴涨问题）。
OS： Windows 10 或者 Windows Server 2016.内存32GB

![6dce6c65ab85fbe7b0dd67d636fdef0](https://user-images.githubusercontent.com/40283390/236166368-2a61eb21-a843-479b-a8fa-9347d8891a4c.png)

![f25a7b36f50a7462bc16f0e0f850661](https://user-images.githubusercontent.com/40283390/236166444-cab2071d-5c6f-479c-a75f-8135268d84cb.png)

**Comment by sangshuduo** [comment]
在处理中

**Comment by sangshuduo** [comment]
已修复，请使用最新版本验证
