### ISSUE TITLE
python3.6版本安装taospyudf失败

### ISSUE THREAD

**Issue by AlphaJin95** [taosdata/TDengine#21149]
在windows和linux上使用python3.6安装 taos支持的新版本python开发udf 依赖 taospyudf，但是失败，麻烦看一下！！！！！！！！

============================================================================
Processing d:\python\python36\scripts\taospyudf-0.0.10.tar.gz
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: 'd:\python\python36\python.exe' 'd:\python\python36\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\lvjin\DOCUME~1\MOBAXT~1\slash\tmp\pip-build-env-b5eb04z6\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- scikit-build-core pybind11
       cwd: None
  Complete output (2 lines):
  ERROR: Could not find a version that satisfies the requirement scikit-build-core (from versions: none)
  ERROR: No matching distribution found for scikit-build-core
  ----------------------------------------
WARNING: Discarding file:///D:/Python/Python36/Scripts/taospyudf-0.0.10.tar.gz. Command errored out with exit status 1: 'd:\python\python36\python.exe' 'd:\python\python36\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\lvjin\DOCUME~1\MOBAXT~1\slash\tmp\pip-build-env-b5eb04z6\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- scikit-build-core pybind11 Check the logs for full command output.
ERROR: Command errored out with exit status 1: 'd:\python\python36\python.exe' 'd:\python\python36\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\lvjin\DOCUME~1\MOBAXT~1\slash\tmp\pip-build-env-b5eb04z6\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- scikit-build-core pybind11 Check the logs for full command output.

**Comment by sangshuduo** [comment]
Requires: Python >=3.7  https://pypi.org/project/scikit-build-core/

**Comment by AlphaJin95** [comment]
> 我用miniconda建了一个python3.8的环境，但是还是报错

(python_3.8) C:\Users\Admin>pip install taospyudf
Collecting taospyudf
  Downloading taospyudf-0.0.10.tar.gz (24 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: taospyudf
  Building wheel for taospyudf (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for taospyudf (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      2023-05-05 14:09:21,768 - scikit_build_core - WARNING - Can't find a Python library, got libdir=None, ldlibrary=None, multiarch=None, masd=None
      loading initial cache file C:\Users\Admin\AppData\Local\Temp\tmp7l305671\build\CMakeInit.txt
      CMake Error at C:/Users/Admin/AppData/Local/Temp/tmp7l305671/build/CMakeInit.txt:1:
        Parse error.  Expected a command name, got unquoted argument with text
        "b".


      CMake Error: Error processing file: C:/Users/Admin/AppData/Local/Temp/tmp7l305671/build/CMakeInit.txt
      -- Building for: Visual Studio 17 2022
      CMake Error at CMakeLists.txt:1:
        Parse error.  Expected a command name, got unquoted argument with text
        "b".


      -- Configuring incomplete, errors occurred!
      *** scikit-build-core 0.3.3 using CMake 3.21.4
      *** Configurating CMake...

      *** CMake configuration failed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for taospyudf
Failed to build taospyudf
ERROR: Could not build wheels for taospyudf, which is required to install pyproject.toml-based projects

**Comment by sangshuduo** [comment]
这是Python环境问题，和 TDengine 没什么关系吧，建议到 Python 技术社区问一下
