### ISSUE TITLE
create index issue

### ISSUE THREAD

**Issue by baseker** [taosdata/TDengine#21142]
**Bug Description**
3.0.4.1版本下，无法在超级表上建立标签索引

**To Reproduce**
1. 3.0.4.1版本下创建超级表
2. 为超级表添加标签索引
3. 报错信息为需指定数据库，指定后报错：索引已存在，实际并未存在索引

**Expected Behavior**
创建索引成功
**Screenshots**

**Environment (please complete the following information):**
 - CentOS 7.0
 - Memory, CPU, current Disk Space
 - TDengine Version [3.0.4.1]

**Additional Context**
添加标签索引时，指定超级表时已经附带库名，依然提示未指定库名

**Comment by sangshuduo** [comment]
![](https://user-images.githubusercontent.com/825729/236363312-36259cb7-8c36-4e28-83e5-837672265a4b.png)

我这里没问题，请提供输入命令和出错截图
