### ISSUE TITLE
域名连接失败

### ISSUE THREAD

**Issue by zhgqiang** [taosdata/TDengine#2114]
1. 客户端通过域名连接失败，DB error: failed to connect to server
2. 通过ip连接后，show tables 可以，但是执行 select * from thermometer 查询失败，DB error: failed to connect to server

**Comment by Aries-Lee1991** [comment]
请将客户端的配置文件中的日志开关打开，添加一行： debugflag 135，
然后重新连接，失败后，将日志文件发送给我们分析一下原因。

**Comment by zhgqiang** [comment]
Welcome to the TDengine shell from Linux, Client Version:1.6.5.9
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

06/03 13:40:57.402842 9131 7f211b597c00 ERROR UTL failed to connect socket, ip:xxx.xxx.top, port:6030, reason: Network is unreachable

DB error: failed to connect to server

06/03 13:40:01.046043 9113 7fb27d6dcc00 TSC starting to initialize TAOS client ...
06/03 13:40:01.046044 9113 7fb27d6dcc00 TSC Local IP address is:0.0.0.0
06/03 13:40:01.046495 9113 7fb27d6dcc00 UTL tsc scheduler is initialized, numOfThreads:2
06/03 13:40:01.046537 9113 7fb27d6dcc00 RPC TSC-vnode TCP client is initialized, ip:0.0.0.0 port:0
06/03 13:40:01.046540 9113 7fb27d6dcc00 RPC TSC-vnode RPC is openned, numOfThreads:2
06/03 13:40:01.046541 9113 7fb27d6dcc00 RPC cid:0, handle:0x1f37c40 open rpc chann
06/03 13:40:01.046557 9113 7fb27d6dcc00 UTL pool:0x1f38240 is setup, maxId:5000
06/03 13:40:01.046779 9113 7fb27d6dcc00 UTL tmr scheduler is initialized, numOfThreads:1
06/03 13:40:01.046817 9113 7fb27d6dcc00 RPC cid:1, handle:0x1f37c40 open rpc chann
06/03 13:40:01.046833 9113 7fb27d6dcc00 UTL pool:0x1f6d0a0 is setup, maxId:5000
06/03 13:40:01.046863 9113 7fb27d6dcc00 RPC TSC-mgmt TCP client is initialized, ip:0.0.0.0 port:0
06/03 13:40:01.046877 9113 7fb27d6dcc00 RPC cid:0, handle:0x1f7bbc0 open rpc chann
06/03 13:40:01.046890 9113 7fb27d6dcc00 UTL pool:0x1f7be70 is setup, maxId:2000
06/03 13:40:01.046910 9113 7fb27d6dcc00 RPC TSC-mgmt RPC is openned, numOfThreads:1
06/03 13:40:01.047280 9113 7fb27d6dcc00 TSC client is initialized successfully
06/03 13:40:01.047319 9113 7fb27d6dcc00 TSC try to create a connection to iot.tmis.top
06/03 13:40:01.047333 9113 7fb27d6dcc00 TSC 0x1fb9090 SQL cmd:29 will be processed, name:(null), type:0
06/03 13:40:01.047338 9113 7fb27d6dcc00 RPC TSC-mgmt cid:0 sid:1, ID allocated, used:1, old id:0
06/03 13:40:01.047341 9113 7fb27d6dcc00 RPC TSC-mgmt cid:0 sid:1 id:root, TAOS connection is allocated, localPort:0 pConn:0x7fb278c970f0
06/03 13:40:01.047342 9113 7fb27d6dcc00 UTL open tcp client socket:xxx.xxx.top:6030

**Comment by zhgqiang** [comment]
> 请将客户端的配置文件中的日志开关打开，添加一行： debugflag 135，
> 然后重新连接，失败后，将日志文件发送给我们分析一下原因。

Welcome to the TDengine shell from Linux, Client Version:1.6.5.9
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

06/03 13:40:57.402842 9131 7f211b597c00 ERROR UTL failed to connect socket, ip:xxx.xxx.top, port:6030, reason: Network is unreachable

DB error: failed to connect to server

06/03 13:40:01.046043 9113 7fb27d6dcc00 TSC starting to initialize TAOS client ...
06/03 13:40:01.046044 9113 7fb27d6dcc00 TSC Local IP address is:0.0.0.0
06/03 13:40:01.046495 9113 7fb27d6dcc00 UTL tsc scheduler is initialized, numOfThreads:2
06/03 13:40:01.046537 9113 7fb27d6dcc00 RPC TSC-vnode TCP client is initialized, ip:0.0.0.0 port:0
06/03 13:40:01.046540 9113 7fb27d6dcc00 RPC TSC-vnode RPC is openned, numOfThreads:2
06/03 13:40:01.046541 9113 7fb27d6dcc00 RPC cid:0, handle:0x1f37c40 open rpc chann
06/03 13:40:01.046557 9113 7fb27d6dcc00 UTL pool:0x1f38240 is setup, maxId:5000
06/03 13:40:01.046779 9113 7fb27d6dcc00 UTL tmr scheduler is initialized, numOfThreads:1
06/03 13:40:01.046817 9113 7fb27d6dcc00 RPC cid:1, handle:0x1f37c40 open rpc chann
06/03 13:40:01.046833 9113 7fb27d6dcc00 UTL pool:0x1f6d0a0 is setup, maxId:5000
06/03 13:40:01.046863 9113 7fb27d6dcc00 RPC TSC-mgmt TCP client is initialized, ip:0.0.0.0 port:0
06/03 13:40:01.046877 9113 7fb27d6dcc00 RPC cid:0, handle:0x1f7bbc0 open rpc chann
06/03 13:40:01.046890 9113 7fb27d6dcc00 UTL pool:0x1f7be70 is setup, maxId:2000
06/03 13:40:01.046910 9113 7fb27d6dcc00 RPC TSC-mgmt RPC is openned, numOfThreads:1
06/03 13:40:01.047280 9113 7fb27d6dcc00 TSC client is initialized successfully
06/03 13:40:01.047319 9113 7fb27d6dcc00 TSC try to create a connection to iot.tmis.top
06/03 13:40:01.047333 9113 7fb27d6dcc00 TSC 0x1fb9090 SQL cmd:29 will be processed, name:(null), type:0
06/03 13:40:01.047338 9113 7fb27d6dcc00 RPC TSC-mgmt cid:0 sid:1, ID allocated, used:1, old id:0
06/03 13:40:01.047341 9113 7fb27d6dcc00 RPC TSC-mgmt cid:0 sid:1 id:root, TAOS connection is allocated, localPort:0 pConn:0x7fb278c970f0
06/03 13:40:01.047342 9113 7fb27d6dcc00 UTL open tcp client socket:xxx.xxx.top:6030

**Comment by Aries-Lee1991** [comment]
wait, the relate R&D will check it.

**Comment by xiaopingcs** [comment]
Can you share your host name?

**Comment by zhgqiang** [comment]
> Can you share your host name?

可以给我个邮箱

**Comment by xiaopingcs** [comment]
> > Can you share your host name?
> 
> 可以给我个邮箱

xiaopingcs@outlook.com

**Comment by zhgqiang** [comment]
> > > Can you share your host name?
> > 
> > 
> > 可以给我个邮箱
> 
> [xiaopingcs@outlook.com](mailto:xiaopingcs@outlook.com)

已将hostname发送至邮箱

**Comment by xiaopingcs** [comment]
> > > > Can you share your host name?
> > > 
> > > 
> > > 可以给我个邮箱
> > 
> > 
> > [xiaopingcs@outlook.com](mailto:xiaopingcs@outlook.com)
> 
> 已将hostname发送至邮箱

Hi, I didn't receive the host name in my email, please double check. At the same time, I am raising an internal defect for you, once it's fixed, will let you know. Thanks very much for reporting.

**Comment by zhgqiang** [comment]
> > > > > Can you share your host name?
> > > > 
> > > > 
> > > > 可以给我个邮箱
> > > 
> > > 
> > > [xiaopingcs@outlook.com](mailto:xiaopingcs@outlook.com)
> > 
> > 
> > 已将hostname发送至邮箱
> 
> Hi, I didn't receive the host name in my email, please double check. At the same time, I am raising an internal defect for you, once it's fixed, will let you know. Thanks very much for reporting.

又发送了一遍

**Comment by xiaopingcs** [comment]
Hi, our 1.6 version only supports ip connection, host connection is not supported. In our 2.0 version, FQDN (Fully Qualified Domain Name) will be supported. 
Also, as I replied you in email, there is no issue with ip connection. Please check your client configuration.

**Comment by watchworld** [comment]
我部署后出现情况是这样的：
08/05 17:20:45.876822 0x7f3352cef700 UTL ERROR failed get the ip address, fqdn:, code:-2, reason:Name or service not known
08/05 17:20:45.876847 0x7f3352cef700 RPC ERROR DND-C, failed to resolve FQDN:
08/05 17:20:45.876855 0x7f3352cef700 RPC ERROR DND-C (nil), failed to set up connection(Unexpected generic error in RPC)
08/05 17:20:45.876862 0x7f3352cef700 RPC DND-C (nil), connection error happens
08/05 17:20:45.876864 0x7f3352cef700 DND ERROR status rsp is received, error:Unexpected generic error in RPC
08/05 17:20:46.876813 0x7f3352cef700 UTL ERROR failed get the ip address, fqdn:, code:-2, reason:Name or service not known
08/05 17:20:46.876837 0x7f3352cef700 RPC ERROR DND-C, failed to resolve FQDN:
08/05 17:20:46.876846 0x7f3352cef700 RPC ERROR DND-C (nil), failed to set up connection(Unexpected generic error in RPC)
08/05 17:20:46.876852 0x7f3352cef700 RPC DND-C (nil), connection error happens
08/05 17:20:46.876856 0x7f3352cef700 DND ERROR status rsp is received, error:Unexpected generic error in RPC
08/05 17:20:47.876805 0x7f3352cef700 UTL ERROR failed get the ip address, fqdn:, code:-2, reason:Name or service not known
08/05 17:20:47.876830 0x7f3352cef700 RPC ERROR DND-C, failed to resolve FQDN:
08/05 17:20:47.876838 0x7f3352cef700 RPC ERROR DND-C (nil), failed to set up connection(Unexpected generic error in RPC)
08/05 17:20:47.876844 0x7f3352cef700 RPC DND-C (nil), connection error happens
08/05 17:20:47.876847 0x7f3352cef700 DND ERROR status rsp is received, error:Unexpected generic error in RPC
