### ISSUE TITLE
ReadString: expects " or n, but found 4, error found in ........

### ISSUE THREAD

**Issue by zkbaba** [taosdata/TDengine#21147]
![image](https://user-images.githubusercontent.com/51184036/236365484-764eb214-1f8d-4096-bb2f-24615d4a2e3e.png)

大佬，您好：
      我在储存数据的时候，使用taos shell 可以正常存储数据，我按照官网上的教程在字符前加了‘\'’,使用go语言存储字节的时候就会报错，可以在tdengineGUI上查看到数据。在执行代码的时候就会报错。错误为：failed to insert, err: ReadString: expects " or n, but found 4, error found in #10 byte of ...|ed_rows",4,4]],"rows|..., bigger context ...|"affected_rows"],"column_meta":[["affected_rows",4,4]],"rows":1,"data":[[1]]}|.
![image](https://user-images.githubusercontent.com/51184036/236365602-22cc97bc-3777-4977-b4d5-97651f7cc56a.png)
麻烦大佬看一下是怎么回事。

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
