### ISSUE TITLE
Not the same tag value ？

### ISSUE THREAD

**Issue by sexbee** [taosdata/TDengine#2116]
**Bug Description**
遇到一个奇怪现象： 当 alter table m123 set tag  c1=111;后，
A) taoshell：describe m123; 
B) taoshell：select lastrow(*) ,c1..... 
C) query.excute()---->select lastrow(*) ,c1.....    
         
三种方式下查询 的tag值 不一致，大约10min 后一致了，难道有时间差？

**Comment by sexbee** [comment]
反复测试：
query.excute()- 下的--->describe table  tag value 比 taoshell 下的   tag value 更新晚5min左右。

**Comment by Aries-Lee1991** [comment]
OK, the related R&D will check it.

**Comment by Shawshank-Smile** [comment]
The client has a cache.Need to restart theclient to refresh the cache,Or the client executes： reset query cache

**Comment by sexbee** [comment]
this.$nextTick(function(){
                                 onCurrenticucolallfindChange(saveItem);
                   })
