### ISSUE TITLE
 support decimal datatype

### ISSUE THREAD

**Issue by JackAuFull** [taosdata/TDengine#21165]
希望增加decimal数据类型，这样就可以结合代码中的bigdecimal避免数据精度丢失的问题

**Comment by sangshuduo** [comment]
谢谢建议，已在计划中

**Comment by qin-jd** [comment]
> 谢谢建议，已在计划中

你好，这个decimal还要多久能在新版本体验到

**Comment by yu285** [comment]
后续 decimal 应该是企业版功能了。
