### ISSUE TITLE
No result is returned if the query condition contains Chinese characters

### ISSUE THREAD

**Issue by anyedilong** [taosdata/TDengine#21179]
<img width="522" alt="1683345234110" src="https://user-images.githubusercontent.com/31983335/236598353-f3db03e4-01d0-44c5-aa4f-3db223a6819a.png">
查询不到数据；需要什么特殊处理吗？

**Comment by sangshuduo** [comment]
这是在什么软件里执行的？在 taos shell 里执行什么结果？

**Comment by anyedilong** [comment]
用的DBeaver执行的sql;taos shell 一直连接不上
<img width="830" alt="1683361639032" src="https://user-images.githubusercontent.com/31983335/236612784-452d3bf3-4b8d-4bb9-af10-0835f7d1d59a.png">
<img width="603" alt="1683361679987" src="https://user-images.githubusercontent.com/31983335/236612830-d9d16983-2f2d-4fb4-8728-b9d7759cb5d0.png">

**Comment by sangshuduo** [comment]
试试 taos -p123456

**Comment by anyedilong** [comment]
可以了；谢谢；中文查询不到，可能是我这边编码设置问题




田振
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taosdata/TDengine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月7日(星期天) 上午10:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [taosdata/TDengine] 查询条件中含有中文问题 (Issue #21179)





 
试试 taos -p123456
