### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by qaz1423078740** [taosdata/TDengine#21175]
[root@master TDengine-server-3.0.4.1]# systemctl start taosd
[root@master TDengine-server-3.0.4.1]# systemctl status taosd
● taosd.service - server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Sat 2023-05-06 10:31:04 CST; 6s ago
  Process: 5991 ExecStart=/usr/bin/taosd (code=exited, status=255)
  Process: 5985 ExecStartPre=/usr/local/taos/bin/startPre.sh (code=exited, status=0/SUCCESS)
 Main PID: 5991 (code=exited, status=255)

May 06 10:31:03 master systemd[1]: taosd.service: main process exited, code=exited, status=255/n/a
May 06 10:31:03 master systemd[1]: Unit taosd.service entered failed state.
May 06 10:31:03 master systemd[1]: taosd.service failed.
May 06 10:31:04 master systemd[1]: taosd.service holdoff time over, scheduling restart.
May 06 10:31:04 master systemd[1]: Stopped server service.
May 06 10:31:04 master systemd[1]: start request repeated too quickly for taosd.service
May 06 10:31:04 master systemd[1]: Failed to start server service.
May 06 10:31:04 master systemd[1]: Unit taosd.service entered failed state.
May 06 10:31:04 master systemd[1]: taosd.service failed.

[root@master TDengine-server-3.0.4.1]# /usr/bin/taosd
locale not configured, set to system default:en_US.UTF-8
05/06 10:35:04.401604 00008956 UTL apoll url not load
05/06 10:35:04.401658 00008956 UTL load from cfg file /etc/taos//taos.cfg success
05/06 10:35:04.402080 00008956 UTL env file:.env not load
05/06 10:35:04.402115 00008956 UTL load from env variables cfg success
05/06 10:35:04.404833 00008956 DND startup path:/root/zhangweihang/TDengine-server-3.0.4.1 args:/usr/bin/taosd
05/06 10:35:04.405264 00008956 UTL apoll url not load
05/06 10:35:04.405320 00008956 UTL load from cfg file /etc/taos//taos.cfg success
05/06 10:35:04.405327 00008956 UTL env file:.env not load
05/06 10:35:04.405333 00008956 UTL load from env variables cfg success
05/06 10:35:04.405478 00008956 UTL                      global config
05/06 10:35:04.405484 00008956 UTL =================================================================
05/06 10:35:04.405487 00008956 UTL default      firstEp                  master:6030
05/06 10:35:04.405491 00008956 UTL default      secondEp                 master:6030
05/06 10:35:04.405494 00008956 UTL default      fqdn                     master
05/06 10:35:04.405497 00008956 UTL default      serverPort               6030
05/06 10:35:04.405500 00008956 UTL default      tempDir                  /tmp/
05/06 10:35:04.405503 00008956 UTL default      minimalTmpDirGB          1.00
05/06 10:35:04.405518 00008956 UTL default      shellActivityTimer       3
05/06 10:35:04.405522 00008956 UTL default      compressMsgSize          -1
05/06 10:35:04.405524 00008956 UTL default      compressColData          -1
05/06 10:35:04.405527 00008956 UTL default      queryPolicy              1
05/06 10:35:04.405530 00008956 UTL default      enableQueryHb            0
05/06 10:35:04.405533 00008956 UTL default      enableScience            0
05/06 10:35:04.405536 00008956 UTL default      querySmaOptimize         0
05/06 10:35:04.405539 00008956 UTL default      queryPlannerTrace        0
05/06 10:35:04.405542 00008956 UTL default      queryNodeChunkSize       32768
05/06 10:35:04.405545 00008956 UTL default      queryUseNodeAllocator    1
05/06 10:35:04.405548 00008956 UTL default      keepColumnName           0
05/06 10:35:04.405551 00008956 UTL default      smlChildTableName
05/06 10:35:04.405554 00008956 UTL default      smlTagName               _tag_null
05/06 10:35:04.405557 00008956 UTL default      maxMemUsedByInsert       1024
05/06 10:35:04.405560 00008956 UTL default      maxRetryWaitTime         10000
05/06 10:35:04.405563 00008956 UTL default      useAdapter               0
05/06 10:35:04.405566 00008956 UTL default      crashReporting           1
05/06 10:35:04.405569 00008956 UTL default      queryMaxConcurrentTable  200
05/06 10:35:04.405572 00008956 UTL default      numOfRpcThreads          2
05/06 10:35:04.405575 00008956 UTL default      numOfRpcSessions         10000
05/06 10:35:04.405577 00008956 UTL default      timeToGetAvailableConn   500000
05/06 10:35:04.405580 00008956 UTL default      numOfTaskQueueThreads    4
05/06 10:35:04.405583 00008956 UTL default      dataDir                  /var/lib/taos/
05/06 10:35:04.405586 00008956 UTL default      minimalDataDirGB         2.00
05/06 10:35:04.405589 00008956 UTL default      supportVnodes            4
05/06 10:35:04.405593 00008956 UTL default      maxShellConns            50000
05/06 10:35:04.405596 00008956 UTL default      statusInterval           1
05/06 10:35:04.405598 00008956 UTL default      minSlidingTime           10
05/06 10:35:04.405601 00008956 UTL default      minIntervalTime          1
05/06 10:35:04.405604 00008956 UTL default      maxNumOfDistinctRes      10000000
05/06 10:35:04.405607 00008956 UTL default      countAlwaysReturnValue   1
05/06 10:35:04.405610 00008956 UTL default      queryBufferSize          -1
05/06 10:35:04.405613 00008956 UTL default      printAuth                0
05/06 10:35:04.405616 00008956 UTL default      queryRspPolicy           0
05/06 10:35:04.405619 00008956 UTL default      numOfRpcThreads          2
05/06 10:35:04.405621 00008956 UTL default      numOfRpcSessions         10000
05/06 10:35:04.405624 00008956 UTL default      timeToGetAvailableConn   10000
05/06 10:35:04.405627 00008956 UTL default      numOfCommitThreads       2
05/06 10:35:04.405630 00008956 UTL default      numOfMnodeReadThreads    1
05/06 10:35:04.405633 00008956 UTL default      numOfVnodeQueryThreads   4
05/06 10:35:04.405636 00008956 UTL default      ratioOfVnodeStreamThrea  1.00
05/06 10:35:04.405642 00008956 UTL default      numOfVnodeFetchThreads   4
05/06 10:35:04.405645 00008956 UTL default      numOfVnodeRsmaThreads    4
05/06 10:35:04.405648 00008956 UTL default      numOfQnodeQueryThreads   4
05/06 10:35:04.405651 00008956 UTL default      numOfSnodeSharedThreads  2
05/06 10:35:04.405654 00008956 UTL default      numOfSnodeUniqueThreads  2
05/06 10:35:04.405656 00008956 UTL default      rpcQueueMemoryAllowed    377680281
05/06 10:35:04.405659 00008956 UTL default      syncElectInterval        25000
05/06 10:35:04.405662 00008956 UTL default      syncHeartbeatInterval    1000
05/06 10:35:04.405665 00008956 UTL default      syncHeartbeatTimeout     20000
05/06 10:35:04.405668 00008956 UTL default      vndCommitMaxInterval     600000
05/06 10:35:04.405671 00008956 UTL default      mndSdbWriteDelta         200
05/06 10:35:04.405674 00008956 UTL default      mndLogRetention          2000
05/06 10:35:04.405677 00008956 UTL default      monitor                  1
05/06 10:35:04.405680 00008956 UTL default      monitorInterval          30
05/06 10:35:04.405682 00008956 UTL default      monitorFqdn
05/06 10:35:04.405685 00008956 UTL default      monitorPort              6043
05/06 10:35:04.405688 00008956 UTL default      monitorMaxLogs           100
05/06 10:35:04.405691 00008956 UTL default      monitorComp              0
05/06 10:35:04.405694 00008956 UTL default      crashReporting           1
05/06 10:35:04.405697 00008956 UTL default      telemetryReporting       1
05/06 10:35:04.405700 00008956 UTL default      telemetryInterval        43200
05/06 10:35:04.405702 00008956 UTL default      telemetryServer          telemetry.taosdata.com
05/06 10:35:04.405705 00008956 UTL default      telemetryPort            80
05/06 10:35:04.405708 00008956 UTL default      transPullupInterval      2
05/06 10:35:04.405711 00008956 UTL default      mqRebalanceInterval      2
05/06 10:35:04.405714 00008956 UTL default      ttlUnit                  86400
05/06 10:35:04.405717 00008956 UTL default      ttlPushInterval          3600
05/06 10:35:04.405720 00008956 UTL default      uptimeInterval           300
05/06 10:35:04.405723 00008956 UTL default      queryRsmaTolerance       1000
05/06 10:35:04.405726 00008956 UTL default      walFsyncDataSizeLimit    104857600
05/06 10:35:04.405729 00008956 UTL default      udf                      1
05/06 10:35:04.405731 00008956 UTL default      udfdResFuncs
05/06 10:35:04.405734 00008956 UTL default      udfdLdLibPath
05/06 10:35:04.405737 00008956 UTL default      disableStream            0
05/06 10:35:04.405740 00008956 UTL default      cacheLazyLoadThreshold   500
05/06 10:35:04.405743 00008956 UTL default      configDir                /etc/taos/
05/06 10:35:04.405746 00008956 UTL default      scriptDir                /etc/taos/
05/06 10:35:04.405749 00008956 UTL default      logDir                   /var/log/taos/
05/06 10:35:04.405784 00008956 UTL default      minimalLogDirGB          1.00
05/06 10:35:04.405787 00008956 UTL default      numOfLogLines            10000000
05/06 10:35:04.405790 00008956 UTL default      asyncLog                 1
05/06 10:35:04.405793 00008956 UTL default      logKeepDays              0
05/06 10:35:04.405795 00008956 UTL default      debugFlag                0
05/06 10:35:04.405798 00008956 UTL default      simDebugFlag             143
05/06 10:35:04.405801 00008956 UTL default      tmrDebugFlag             131
05/06 10:35:04.405804 00008956 UTL default      uDebugFlag               131
05/06 10:35:04.405806 00008956 UTL default      rpcDebugFlag             131
05/06 10:35:04.405809 00008956 UTL default      jniDebugFlag             131
05/06 10:35:04.405812 00008956 UTL default      qDebugFlag               131
05/06 10:35:04.405815 00008956 UTL default      cDebugFlag               131
05/06 10:35:04.405817 00008956 UTL default      dDebugFlag               131
05/06 10:35:04.405820 00008956 UTL default      vDebugFlag               131
05/06 10:35:04.405823 00008956 UTL default      mDebugFlag               131
05/06 10:35:04.405829 00008956 UTL default      wDebugFlag               131
05/06 10:35:04.405832 00008956 UTL default      sDebugFlag               131
05/06 10:35:04.405834 00008956 UTL default      tsdbDebugFlag            131
05/06 10:35:04.405837 00008956 UTL default      tqDebugFlag              131
05/06 10:35:04.405840 00008956 UTL default      fsDebugFlag              131
05/06 10:35:04.405843 00008956 UTL default      udfDebugFlag             131
05/06 10:35:04.405846 00008956 UTL default      smaDebugFlag             131
05/06 10:35:04.405848 00008956 UTL default      idxDebugFlag             131
05/06 10:35:04.405851 00008956 UTL default      tdbDebugFlag             131
05/06 10:35:04.405854 00008956 UTL default      metaDebugFlag            131
05/06 10:35:04.405857 00008956 UTL default      timezone                 Asia/Shanghai (CST, +0800)
05/06 10:35:04.405859 00008956 UTL default      locale                   en_US.UTF-8
05/06 10:35:04.405862 00008956 UTL default      charset                  UTF-8
05/06 10:35:04.405865 00008956 UTL default      assert                   1
05/06 10:35:04.405868 00008956 UTL default      enableCoreFile           1
05/06 10:35:04.405871 00008956 UTL default      numOfCores               2.00
05/06 10:35:04.405874 00008956 UTL default      SSE42                    0
05/06 10:35:04.405876 00008956 UTL default      AVX                      0
05/06 10:35:04.405879 00008956 UTL default      AVX2                     0
05/06 10:35:04.405882 00008956 UTL default      FMA                      0
05/06 10:35:04.405885 00008956 UTL default      SIMD-builtins            0
05/06 10:35:04.405887 00008956 UTL default      tagFilterCache           0
05/06 10:35:04.405890 00008956 UTL default      openMax                  65535
05/06 10:35:04.405893 00008956 UTL default      streamMax                16
05/06 10:35:04.405896 00008956 UTL default      pageSizeKB               4
05/06 10:35:04.405899 00008956 UTL default      totalMemoryKB            3688284
05/06 10:35:04.405902 00008956 UTL default      os sysname               Linux
05/06 10:35:04.405904 00008956 UTL default      os nodename              master
05/06 10:35:04.405907 00008956 UTL default      os release               3.10.0-1160.83.1.el7.x86_64
05/06 10:35:04.405910 00008956 UTL default      os version               #1 SMP Wed Jan 25 16:41:43 UTC 2023
05/06 10:35:04.405913 00008956 UTL default      os machine               x86_64
05/06 10:35:04.405916 00008956 UTL default      version                  3.0.4.1
05/06 10:35:04.405919 00008956 UTL default      compatible_version       3.0.0.0
05/06 10:35:04.405922 00008956 UTL default      gitinfo                  14dc9eabc403e731ba1097eca0bcaa902c6d5b62
05/06 10:35:04.405924 00008956 UTL default      buildinfo                Built at 2023-04-27 11:08
05/06 10:35:04.405927 00008956 UTL =================================================================
05/06 10:35:04.407870 00008956 DND start to init dnode env
05/06 10:35:04.408094 00008956 DND succceed to read dnode file /var/lib/taos//dnode/dnode.json
05/06 10:35:04.408130 00008956 DND ERROR dnode:1, localEp master:6030 different from iZuf6iw5enua6fi1ra3cbcZ:6030
05/06 10:35:04.408135 00008956 DND ERROR localEp master:6030 different with /var/lib/taos//dnode/dnode.json and need reconfigured
05/06 10:35:04.408199 00008956 DND ERROR failed to read file since Invalid config option
05/06 10:35:04.408210 00008956 DND ERROR failed to create dnode since Invalid config option
05/06 10:35:04.408214 00008956 DND ERROR failed to init dnode since Invalid config option

dnode.json
{
	"dnodeId":	1,
	"dnodeVer":	"2",
	"clusterId":	"4916139791559277436",
	"dropped":	0,
	"dnodes":	[{
			"id":	1,
			"fqdn":	"iZuf6iw5enua6fi1ra3cbcZ",
			"port":	6030,
			"isMnode":	1
		}]
}
我该怎么修改才能运行

**Comment by sangshuduo** [comment]
05/06 10:35:04.405487 00008956 UTL default firstEp master:6030
05/06 10:35:04.405491 00008956 UTL default secondEp master:6030

/etc/taos/taos.cfg 里配置修改过？

**Comment by qaz1423078740** [comment]
我没动过任何配置文件，我修改/etc/taos/taos.cfg变成6031也并不可以运行。我甚至把/etc/taos目录下的全部删除，重新安装还是给我的配置文件是6030，我修改成6031

# The interval for CLI to send heartbeat to mnode
# shellActivityTimer        3


############### 1. Cluster End point ############################

# The end point of the first dnode in the cluster to be connected to when this dnode or the CLI utility is started
# firstEp                   hostname:6031

# The end point of the second dnode to be connected to if the firstEp is not available
# secondEp


############### 2. Configuration Parameters of current dnode #####

# The FQDN of the host on which this dnode will be started. It can be IP address
# fqdn                      hostname

# The port for external access after this dnode is started
# serverPort                6031

# The maximum number of connections a dnode can accept
# maxShellConns             5000

还是
05/06 14:18:46.282381 00007511 UTL default      firstEp                  master:6030
05/06 14:18:46.282384 00007511 UTL default      secondEp                 master:6030
05/06 14:18:46.282387 00007511 UTL default      fqdn                     master
05/06 14:18:46.282390 00007511 UTL default      serverPort               6030
05/06 14:18:46.282393 00007511 UTL default      tempDir                  /tmp/



05/06 14:16:00.262674 00005476 DND start to init dnode env
05/06 14:16:00.262819 00005476 DND succceed to read dnode file /var/lib/taos//dnode/dnode.json
05/06 14:16:00.262849 00005476 DND ERROR dnode:1, localEp master:6030 different from iZuf6iw5enua6fi1ra3cbcZ:6031
05/06 14:16:00.262858 00005476 DND ERROR localEp master:6030 different with /var/lib/taos//dnode/dnode.json and need reconfigured
05/06 14:16:00.262943 00005476 DND ERROR failed to read file since Invalid config option
05/06 14:16:00.262954 00005476 DND ERROR failed to create dnode since Invalid config option
05/06 14:16:00.262960 00005476 DND ERROR failed to init dnode since Invalid config option

**Comment by qaz1423078740** [comment]
> 05/06 10:35:04.405487 00008956 UTL default firstEp master:6030 05/06 10:35:04.405491 00008956 UTL default secondEp master:6030
> 
> /etc/taos/taos.cfg 里配置修改过？

我并没有动过任何东西全部是默认的，但确实里面的文件变了，之前我是运行成功的且是在6031端口，一段时间没有查看，今天发现它关闭了，然后重启一直失败。

**Comment by sangshuduo** [comment]
taos.cfg 和 dnode.json 里 fqdn 不一致

**Comment by qaz1423078740** [comment]
![9}54G0_Z YBLKC`GQ 5_MJ0](https://user-images.githubusercontent.com/92016538/236607456-d1f9fa3a-d901-46fa-b19a-8cba01c0d6a6.png)
![IDX{B5ULB20OSTK`RWPUVUS](https://user-images.githubusercontent.com/92016538/236607491-e95169e2-38fb-4fd1-a1e3-317724101f11.png)
05/06 14:33:50.583794 00018815 DND succceed to read dnode file /var/lib/taos//dnode/dnode.json
05/06 14:33:50.583874 00018815 DND ERROR dnode:1, localEp master:6030 different from hostname:6031
05/06 14:33:50.583881 00018815 DND ERROR localEp master:6030 different with /var/lib/taos//dnode/dnode.json and need reconfigured
05/06 14:33:50.583940 00018815 DND ERROR failed to read file since Invalid config option
05/06 14:33:50.583951 00018815 DND ERROR failed to create dnode since Invalid config option
05/06 14:33:50.583954 00018815 DND ERROR failed to init dnode since Invalid config option
好奇怪我明明改了是6031为什么会是6030

**Comment by qaz1423078740** [comment]
> taos.cfg 和 dnode.json 里 fqdn 不一致

修改了还是不行

**Comment by qaz1423078740** [comment]
> taos.cfg 和 dnode.json 里 fqdn 不一致

谢谢可以
