### ISSUE TITLE
write JSON data cause crash 

### ISSUE THREAD

**Issue by huienming** [taosdata/TDengine#21198]
**Bug Description**
When use schemaless writor，taosd server crashed if there is JSON data.

**To Reproduce**
1. use line protocal mode
2. only exist one column format with JSON array
3. JSON data may changed between [{},{},{}] or []
4. insert to database every 200ms ,200 rows total
5. run 30min or less,taos server crashed

**Expected Behavior**
do not crashed
**Screenshots**
![46f8a6ce15bcad6186fee9da76be832](https://user-images.githubusercontent.com/16663611/236654616-c4ff208a-60dd-4d4c-b520-4eaccb6bb181.png)

**Environment (please complete the following information):**
 - OS: [windows 10]
 - Memory, CPU, current Disk Space
 - TDengine Version [3.0.4.1]

**Additional Context**
Add any other context about the problem [here.]

**Comment by yu285** [comment]
windows 早期问题较多，开源版维护不过来，回收到到企业版重做了。 所以windows版本到了 3.0.7.1 之后就没法再升级了，也没有维护团队支持。所以咱们还是换到 linux 版本再使用，目前最新版为 3.2.3.0。

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
