### ISSUE TITLE
invalid commit head

### ISSUE THREAD

**Issue by xwangg** [taosdata/TDengine#212]
```
07/29 08:43:16.090942 7ff9f8d0e700 ERROR DND vid, invalid commit head, sid:1076399964 contLen:9458 action:-123
07/29 08:43:16.090963 7ff9f8d0e700 ERROR DND vid, invalid commit head, sid:1076389478 contLen:-515396076 action:3
07/29 08:43:16.090976 7ff9f8d0e700 ERROR DND vid, invalid commit head, sid:8100 contLen:-2061584302 action:122
07/29 08:43:16.090986 7ff9f8d0e700 ERROR DND vid, invalid commit head, sid:1076394721 contLen:1202590843 action:-21
```

**Comment by hjxilinx** [comment]
It seems the  header of submit.log is broken. Have you ever notice that the TAOSD service crashed before this error happened?

**Comment by xwangg** [comment]
yes, taosd was killed. any method to recovery from that?

**Comment by hjxilinx** [comment]
You can remove submit.log manually, then start TAOSD.

**Comment by xwangg** [comment]
> Remove submit.log manually, then start TAOSD.

where is submit.log?

**Comment by guanshengliang** [comment]
```
/var/lib/taos/data/tsdb/vnode`n`/db/submit`n`.log  
```

**Comment by vonlippmann** [comment]
我顺便在这问一句
1.请问这个submit.log日志和/var/log/taos/下的log分别是记录的什么日至，为什么分开放呢？
2.在配置文件taos.cfg中，把CLOG设置为0后重启taosd，我发现/var/log/taos下的日志还是产生了，这项配置是把submit.log日志禁用了吗？
3.我在插入百万级数据量的时候正常，千万级的时候遇到了invalid commit log错误，一般要怎么解决？

**Comment by hjxilinx** [comment]
submit.log是预写日志（write ahead log, WAL），无法关闭。
/var/log/taos目录下的是普通日志，用于系统运行追踪和分析。可以通过在/etc/taos/taos.cfg中增加设置信息：

>debugflag 131

的方式来关闭。
请给出更详细的错误信息，便于我们判断问题。

**Comment by vonlippmann** [comment]
> submit.log是预写日志（write ahead log, WAL），无法关闭。
> /var/log/taos目录下的是普通日志，用于系统运行追踪和分析。可以通过在/etc/taos/taos.cfg中增加设置信息：
> 
> > debugflag 131
> 
> 的方式来关闭。
> 请给出更详细的错误信息，便于我们判断问题。
我换了一台内存更高的机器，然后下载了你们最新的版本，现在这个问题没有出现了，但是我批量插入500行没有问题，批量插入1000行会报invalid sql 错误，批量插入时对sql语句的长度有限制吗？

**Comment by vonlippmann** [comment]
> submit.log是预写日志（write ahead log, WAL），无法关闭。
> /var/log/taos目录下的是普通日志，用于系统运行追踪和分析。可以通过在/etc/taos/taos.cfg中增加设置信息：
> 
> > debugflag 131
> 
> 的方式来关闭。
> 请给出更详细的错误信息，便于我们判断问题。


我换了一台内存更高的机器，然后下载了你们最新的版本，现在这个问题没有出现了，但是我批量插入500行没有问题，批量插入1000行会报invalid sql 错误，批量插入时对sql语句的长度有限制吗？

**Comment by sangshuduo** [comment]
参考 maxSQLLength 参数
