### ISSUE TITLE
tsdbPrepareCommit assert failed 

### ISSUE THREAD

**Issue by huienming** [taosdata/TDengine#21200]
**Bug Description**
在tsdbPrepareCommit函数里，ASSERT(pTsdb->imem == NULL)出现断言错误。
初步判断是因为tsdbFSCommit执行不成功，直接退到_exit。
int32_t tsdbFinishCommit(STsdb *pTsdb) {
  int32_t    code = 0;
  int32_t    lino = 0;
  SMemTable *pMemTable = pTsdb->imem;

  // lock
  taosThreadRwlockWrlock(&pTsdb->rwLock);

  code = tsdbFSCommit(pTsdb);
  
  if (code) {
    taosThreadRwlockUnlock(&pTsdb->rwLock);
    TSDB_CHECK_CODE(code, lino, _exit);
  }
  pTsdb->imem = NULL;

  

  // unlock
  taosThreadRwlockUnlock(&pTsdb->rwLock);
  if (pMemTable) {
    tsdbUnrefMemTable(pMemTable, NULL, true);
  }

_exit:
  if (code) {
    tsdbError("vgId:%d, %s failed at line %d since %s", TD_VID(pTsdb->pVnode), __func__, lino, tstrerror(code));
  } else {
    tsdbInfo("vgId:%d, tsdb finish commit", TD_VID(pTsdb->pVnode));
  }
  return code;
}
当code不为0的时候，直接退到了_exit,此时pTsdb->imem = NULL;没有执行

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. windows10]
 - TDengine Version [3.0.4.1]

**Additional Context**

**Comment by yu285** [comment]
请问可以远程吗？微信 a15652223354

**Comment by facetosea** [comment]
复现步骤没有看明白，麻烦问一下这个问题是在什么场景出现的？

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
