### ISSUE TITLE
same query works in the taos shell  but not springboot

### ISSUE THREAD

**Issue by anyedilong** [taosdata/TDengine#21209]
<img width="1083" alt="1683529868534" src="https://user-images.githubusercontent.com/31983335/236758942-632ea02a-2d06-4b31-a1df-5ffd75c32df9.png">
<img width="1198" alt="1683529885470" src="https://user-images.githubusercontent.com/31983335/236758973-16e62d37-c6aa-488b-9783-b26b6f15edba.png">
有什么特殊设置吗

**Comment by sangshuduo** [comment]
确定时区配置对了吗？

**Comment by anyedilong** [comment]
这个大概明白什么原因了；
再问个问题：一个表中如果存在主键时间戳不一样，但是code字段一样的数据；数据库有没有一种机制 根据code自动删除时间戳小的那一条数据或者说两条数据合并成一条数据

**Comment by sangshuduo** [comment]
> 这个大概明白什么原因了； 再问个问题：一个表中如果存在主键时间戳不一样，但是code字段一样的数据；数据库有没有一种机制 根据code自动删除时间戳小的那一条数据或者说两条数据合并成一条数据

没有

**Comment by qianxitutu** [comment]
> 确定时区配置对了吗？

我也遇到这样的问题，在springboot中配置时区不生效，如下
jdbc:TAOS-RS://tdengine-server:6041/sss?timezone=UTC+8

我应该怎么配置呢？

**Comment by sangshuduo** [comment]
> > 确定时区配置对了吗？
> 
> 我也遇到这样的问题，在springboot中配置时区不生效，如下 jdbc:TAOS-RS://tdengine-server:6041/sss?timezone=UTC+8
> 
> 我应该怎么配置呢？

注意中国时区在 Unix 标准中是 UTC-8

**Comment by anyedilong** [comment]
> > 确定时区配置对了吗？
> 
> 我也遇到这样的问题，在springboot中配置时区不生效，如下 jdbc:TAOS-RS://tdengine-server:6041/sss?timezone=UTC+8
> 
> 我应该怎么配置呢？

我这边springboot集成后；是把时间转换为时间戳，用时间戳进行查询的
