### ISSUE TITLE
limit  performance issue 

### ISSUE THREAD

**Issue by donnasky** [taosdata/TDengine#21201]
我是用的3.0.25版本的数据库，超级表：` CREATE STABLE `sensors_real_time_data` ( `time` timestamp,`code` VARCHAR(11) ,  `val` DOUBLE,  `x` DOUBLE,  `y` DOUBLE,  `z` DOUBLE,  `type` TINYINT  ) TAGS(`escalators_id` SMALLINT); `，建了100个子表，初始化了一亿多数据。当我直接执行 `select * from sensors_real_time_data where escalators_id=2 order by time desc;` 时，立刻返回了结果，但是同样的SQL加上limit时，查询了一分钟也没有返回结果。我想问是我表建的不对吗？还是用法有问题？
![image](https://user-images.githubusercontent.com/19203869/236717846-fe9552d1-f980-4e7a-8636-8286418308ec.png)

![image](https://user-images.githubusercontent.com/19203869/236717832-aa2b1f27-05b3-49c4-b48d-116c5cb3486c.png)

**Comment by yu285** [comment]
应该是已知问题，可以升级到 3.0.4.1 再验证一下
