### ISSUE TITLE
The Java client connects to TDengine and prompts two exceptions: "invalid user" and "Ref is not there".

### ISSUE THREAD

**Issue by ChanaLii** [taosdata/TDengine#21208]
**Bug Description**
We have encountered a problem in the production environment. When the TDengine cluster has not changed, the log prompts that the connection is abnormal when the Java client tries to connect to TDengine:
1. Factory method 'taosSqlSessionFactoryBean' threw exception; nested exception is com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: JNI ERROR (2354): Ref is not there
2、java.sql. SQLException:JNI ERROR (2354): Invalid user

In the issue list, I found relevant content: https://github.com/taosdata/TDengine/issues/12208

**To Reproduce**
1. A two-node cluster has been deployed and has been running stably for 1 year
2. deployed a Java client（SpringBoot application)  try to connect the TDengine
3. See error

**Expected Behavior**
Java client success to connect the TDeninge.

**Screenshots**
![iShot_2023-05-08_14 42 38](https://user-images.githubusercontent.com/20842481/236753038-aa81a9b2-5a6c-4335-bf96-fba7f18d67fa.png)
![image](https://user-images.githubusercontent.com/20842481/236753257-0b8ab9e4-087e-4107-a155-4c3165988ba3.png)

**Environment (please complete the following information):**
 - OS: [Alibaba Cloud Linux release 3 (Soaring Falcon)]
 - 4 G Memory,2 CPU, current Disk Space left 50G
 - TDengine Version [2.4.0.18]

**Additional Context**
none.

**Comment by sangshuduo** [comment]
Suggest upgrading TDengine to the latest version since 'Ref is not there' is fixed.

**Comment by ChanaLii** [comment]
> Suggest upgrading TDengine to the latest version since 'Ref is not there' is fixed.

Another problem is also solved by upgrading the latest version? As of now, our application still prompts the following exception:

```
[xxxxxxx/v1.0.1 - 192.168.0.43:8080] 2023-05-08 12:19:09.171  INFO 1 [] [main] com.zaxxer.hikari.HikariDataSource HikariPool-1 - Starting...
[xxxxxxx/v1.0.1 - 192.168.0.43:8080] 2023-05-08 12:19:10.472  ERROR 1 [] [main] com.zaxxer.hikari.pool.HikariPool HikariPool-1 - Exception during pool initialization.

java.sql.SQLException: JNI ERROR (2354): Invalid user
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:75)
	at com.taosdata.jdbc.TSDBJNIConnector.connect(TSDBJNIConnector.java:80)
	at com.taosdata.jdbc.TSDBConnection.connect(TSDBConnection.java:35)
	at com.taosdata.jdbc.TSDBConnection.<init>(TSDBConnection.java:21)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:131)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)

```
We have checked the user list of TDengine. Using the account and password of the Java client on the terminal can successfully connect to TDengine and perform a successful select operation, which can rule out the problems of non-existence of account and insufficient access rights.

**Comment by ChanaLii** [comment]
The problem was solved, it was because of taos-driver version mismatch. The TDengine version deployed in our production environment is v2.4.x, and the client uses the v3.x taos-driver
