### ISSUE TITLE
The failure of taosRenameFile leads to taosd hanging up.

### ISSUE THREAD

**Issue by huienming** [taosdata/TDengine#21214]
**Bug Description**
当taosRenameFile失败的时候，系统卡死再也连接不上

**To Reproduce**
运行大概1小时左右，会调用taosRenameFile去替换文件CURRENT.t为CURRENT。偶尔会失败，失败后系统再也连接不上了。

**Environment (please complete the following information):**
 - OS: [windows 10]
 - TDengine Version [3.0.4.1]

**Additional Context**

**Comment by sangshuduo** [comment]
如何复现？
