### ISSUE TITLE
taodump导入问题

### ISSUE THREAD

**Issue by elysian-gc** [taosdata/TDengine#21210]
例如我在tdengine有两个数据库，这两个数据库有一样的stable，我想把其中一个库(test)中的stable导入到另一个库（test1），我应该如何做？

从taosdump参数中没有发现相关参数。

**Comment by sangshuduo** [comment]
企业版有工具可以支持这个需求

**Comment by elysian-gc** [comment]
> 企业版有工具可以支持这个需求

ok谢谢，希望开源版也能支持
