### ISSUE TITLE
 The problem of using TDengineTest.cs under c#

### ISSUE THREAD

**Issue by wangfd83** [taosdata/TDengine#2122]
我通过客户端的taos.exe是可以连接数据库的。
C:\TDengine>taos.exe

Welcome to the TDengine shell from Windows, Client Version:1.6.5.9
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

Server is Community Edition, version is 1.6.5.9

taos> use db;
Query OK, 1 row(s) affected (0.001000s)

taos> select * from t;
          ts          |   speed   |
===================================
 19-07-15 13:00:00.000|         10|
 19-07-15 14:00:00.000|         20|
 19-08-15 13:00:00.000|         10|
 19-09-16 14:00:00.000|         20|
Query OK, 4 row(s) in set (0.020000s)
并且把C:\TDengine\cfg\taos这个配置文件copy到了bin目录下面。把taos.dll也拷贝到了bin目录下面。
在TDengineTest.cs的tester.InitTDengine();调用是成功的。
调用tester.ConnectTDengine();返回conn一直是0
public void ConnectTDengine()
        {
            try
            {
                string db = "";
                this.port = 0;
                this.host=“192.168.87.128”;
                this.user="root";
                this.password="123456";
                this.dbName="db";
                this.conn = TDengine.Connect(this.host, this.user, this.password, this.dbName, this.port);
                if (this.conn == 0)
                {
                    Console.WriteLine("Connect to TDengine failed");
                    ExitProgram();
                }
                else
                {
                    Console.WriteLine("Connect to TDengine success");
                }
            }
            catch (Exception ex)
            {
                
            }
        }

这里的conn一直是返回0；

**Comment by Aries-Lee1991** [comment]
麻烦您把日志发一下吧。
