### ISSUE TITLE
dnode节点的vnode数据同步异常

### ISSUE THREAD

**Issue by Lao-Zhong** [taosdata/TDengine#21238]
**Bug Description**
bug1:
vnode数据同步异常，meta文件同步完成后又自动移除；

bug2:
05/10 14:06:45.852798 00001282 TDB vgId:15 a row is updated in table s54190060472 tid 213 uid 4222128227360648 key 1683698803000
05/10 14:06:45.852801 00001282 TDB vgId:15 allocate 288 bytes from TSDB buffer block, nBlocks 2 offset 3173558 remain 13603658
05/10 14:06:46.027075 00001281 TDB vgId:13 allocate 0 bytes from TSDB buffer block, nBlocks 2 offset 11251568 remain 5525648
05/10 14:06:46.027097 00001281 TDB vgId:13 a row is updated in table s77430222131 tid 849 uid 3659188943898090 key 1683698804000
05/10 14:06:46.027100 00001281 TDB vgId:13 allocate 288 bytes from TSDB buffer block, nBlocks 2 offset 11251856 remain 5525360
05/10 14:06:46.048307 00001186 RPC WARN DND-C (nil), connection error. notify client query over. numOfTry=3 msgType=121
05/10 14:06:46.048407 00001596 DND ERROR user:bhgps, auth msg received from mnodes, error:Unable to establish connection
05/10 14:06:46.133308 00001186 RPC WARN DND-C (nil), connection error. notify client query over. numOfTry=3 msgType=121
05/10 14:06:46.133426 00001597 DND ERROR user:monitor, auth msg received from mnodes, error:Unable to establish connection

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 2.6.0.14]

**Additional Context**

**Comment by sangshuduo** [comment]
Unable to establish connection

网断了？还是 taosd core 了？建议升级到新版本

**Comment by ora-guo** [comment]
请问怎么处理的
