### ISSUE TITLE
时间字段排序出现混乱

### ISSUE THREAD

**Issue by qianxitutu** [taosdata/TDengine#21240]
我用时间倒序进行排序，10号的日期排在了3号的后面

数据库版本： 3.0 

![image](https://github.com/taosdata/TDengine/assets/22881731/4a58b6e0-73a9-488a-bd21-80d8066778ae)

**Comment by sangshuduo** [comment]
具体版本是什么？

**Comment by qianxitutu** [comment]
> 具体版本是什么？

3.0.1.4

**Comment by sangshuduo** [comment]
版本太老了，升级到 3.0.4.1 吧

**Comment by qianxitutu** [comment]
> 版本太老了，升级到 3.0.4.1 吧

好的，我试试

**Comment by veigara** [comment]
最新的版本也是一样，我用了时间倒序排序，最新的数据排到中间了，但正序是正常的

**Comment by iftrue-cn** [comment]
3.0.4.0版本使用时间戳和伪列_co倒序排序都出现乱序

**Comment by sangshuduo** [comment]
参考： https://github.com/taosdata/TDengine/issues/21604#issuecomment-1582069328
