### ISSUE TITLE
The 3-node taos cluster installed by docker-compose failed to restart

### ISSUE THREAD

**Issue by Byrontoo** [taosdata/TDengine#21246]
1、现象描述：
 使用docker-compose安装的3节点taos集群重启失败，报错：
2、软件版本：
    操作系统：centos7.9
    docker version: 23.0.4
    docker-compose version: v2.15.0
    tdengine: 2.6.0.34
    防火墙：3台服务器上面防火墙均已经关闭

3、docker-compose 配置：

`services:
 **taos1**:
   container_name: taos
   image: tdengine/tdengine:2.6.0.34
   environment:
     TZ: "Asia/Shanghai"
     TAOS_FQDN: "centos2"
     TAOS_SERVER_PORT: "6030"
     TAOS_FIRST_EP: "centos2"
     TAOS_NUM_OF_MNODES: "3"
     TAOS_REPLICA: "3"
   ports:
     - "6030-6042:6030-6042/tcp"
     - "6030-6042:6030-6042/udp"
   extra_hosts:
     - "centos3:192.168.21.50"
     - "centos4:192.168.23.14"
   volumes:
     - /etc/localtime:/etc/localtime:ro
     - ${DOCKER_WORK_PATH}/tdengine/taosdata:/var/lib/taos
     - ${DOCKER_WORK_PATH}/tdengine/log:/var/log/taos
   hostname: "centos2"
   networks:
     - custom_net

  **taos2**:
    container_name: taos
    image: tdengine/tdengine:2.6.0.34
    environment:
      TZ: "Asia/Shanghai"
      TAOS_FQDN: "centos3"
      TAOS_SERVER_PORT: "7030"
      TAOS_FIRST_EP: "centos2:6030"
      TAOS_NUM_OF_MNODES: "3"
      TAOS_REPLICA: "3"
    ports:
      - "7030-7042:7030-7042/tcp"
      - "7030-7042:7030-7042/udp"
    extra_hosts:
      - "centos2:192.168.20.10"
      - "centos4:192.168.23.14"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_WORK_PATH}/tdengine/taosdata:/var/lib/taos
      - ${DOCKER_WORK_PATH}/tdengine/log:/var/log/taos
    hostname: "centos3"
    networks:
      - custom_net

  **taos3**:
    container_name: taos
    image: tdengine/tdengine:2.6.0.34
    environment:
      TZ: "Asia/Shanghai"
      TAOS_FQDN: "centos4"
      TAOS_SERVER_PORT: "8030"
      TAOS_FIRST_EP: "centos2:6030"
      TAOS_NUM_OF_MNODES: "3"
      TAOS_REPLICA: "3"
    ports:
      - "8030-8042:8030-8042/tcp"
      - "8030-8042:8030-8042/udp"
    extra_hosts:
      - "centos2:192.168.20.10"
      - "centos3:192.168.21.50"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_WORK_PATH}/tdengine/taosdata:/var/lib/taos
      - ${DOCKER_WORK_PATH}/tdengine/log:/var/log/taos
    hostname: "centos4"
    networks:
      - custom_net

networks:
  custom_net:
    driver: bridge`
4、搭建成功后，3个节点能正常工作，但是依次停止taos1,taos2,taos3之后，再重启taos1，报错如下：

![image](https://github.com/taosdata/TDengine/assets/13880183/2a2daaa9-c64a-47c4-b91f-8011df8cc11f)

请问这个问题如何解决？

**Comment by yu285** [comment]
但是依次停止taos1,taos2,taos3之后，再重启taos1

这个时候只有一个taos1 在线吗？

**Comment by Byrontoo** [comment]
> 

taos1启动失败，不在线，反复报错taos2,taos3连接失败，taos2和taos3一启动就立即退出了，报错：taos connect failed, reason: Unable to establish connection.

**Comment by junyan-zg** [comment]
我这边也遇到这个问题，升级到3能解决吗

**Comment by Byrontoo** [comment]
> 我这边也遇到这个问题，升级到3能解决吗

还没有试过升级到3

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
