### ISSUE TITLE
1.6 TDengine can't be started 

### ISSUE THREAD

**Issue by bhgzhouchao** [taosdata/TDengine#21241]
服务正常启动，隔一段时间后会自动停止。
服务器：centos7 
tdengine版本：1.6.5.9
![image](https://github.com/taosdata/TDengine/assets/6915964/7914a77d-f5e8-497f-a9bb-48c06a463f9b)
[log.zip](https://github.com/taosdata/TDengine/files/11439060/log.zip)

**Comment by sangshuduo** [comment]
1.6 早就不维护了，请尽快升级到 3.0 最新版本
