### ISSUE TITLE
Streaming computation failed to write to the existing super table

### ISSUE THREAD

**Issue by 4yu** [taosdata/TDengine#21259]
问题描述：
1、创建stream，成功
create stream bat_stream trigger max_delay 600s into bat_com subtable(concat('s_', tbname))  as select _wstart as ts ,_wend as ets,count(*) as cnt from bat partition by tbname tbtag state_window(cast ((`u_value`*1000+`t_value`) as int)) ;
2、因为要修改stream，所以对已经存在的stream，删除后重新创建，删除成功。
drop stream bat_stream;
3、由于要保留原来的数据，需要写入原来已经存在的超级表【删除stream前创建的】，重新创建时报错：STable already exists (0.003414s)
create stream bat_stream trigger max_delay 600s into bat_com TAGS(tbtag2 varchar(200)) subtable(concat('s_', tbname))  as select _wstart as ts ,_wend as ets,count(*) as cnt from bat partition by tbname tbtag state_window(cast ((`u_value`*1000+`t_value`) as int)) ;
报错：
STable already exists (0.003414s)

版本：3.0.2.4

**Comment by yu285** [comment]
确认了下，该特性 3.0.3.0 发布，咱们更新到 3.0.4.1 吧
