### ISSUE TITLE
方便开放 TDengine 接入协议文档么？

### ISSUE THREAD

**Issue by ChunMengLu** [taosdata/TDengine#21257]
**Is your feature request related to a problem? Please describe.**
目前客户端在使用上依赖的 libtao.so 库，其实还是有些不方便，是否可以整理出接入协议，我们可以自行的扩展出各种语言的原生客户端。

**Describe your desired behavior**
开放出协议文档，方便大家编写各个语言原生的客户端。

**Describe your solutions/suggestions if you've any**
做过一些数据库协议的解析，mysql、pg 都有协议文档。

**Additional context**
看 td 源码和抓包的话工作量太大了。有文档会方便很多。

**Comment by sangshuduo** [comment]
暂时没有这样的文档
