### ISSUE TITLE
为什么不能使用like模糊匹配concat进行拼接通配符%

### ISSUE THREAD

**Issue by zlldouble** [taosdata/TDengine#21265]
![image](https://github.com/taosdata/TDengine/assets/121913285/e1490157-e87e-4afa-811a-de3701243e9b)
![image](https://github.com/taosdata/TDengine/assets/121913285/19487258-c306-49cc-8987-ed7beeb35d45)

**Comment by yu285** [comment]
暂时还不支持这种语法。
