### ISSUE TITLE
how to close the log in nodejs connector?

### ISSUE THREAD

**Issue by keel** [taosdata/TDengine#2130]
Thers's  too much logs when insert datas using td-connector, how to close that?

**Comment by Aries-Lee1991** [comment]
please set debugFlag to 131.

**Comment by keel** [comment]
how to set the debugFlag?

**Comment by Aries-Lee1991** [comment]
alter dnode ip_addr debugflag 135

**Comment by keel** [comment]
ok ,thanks.
