### ISSUE TITLE
SYN ERROR vgId:4, sync leader wal read error

### ISSUE THREAD

**Issue by qianxitutu** [taosdata/TDengine#21302]
版本：3.0.1.4 ，docker 部署方式

现象描述：
服务器断电关机，重启服务器后，tdengine 的容器无法重启，日志如下，请问这种情况改怎么修复？
05/15 06:39:55.268495 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752834, term:4, msg-index:8752834, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.268498 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068379, term:4, msg-index:14068379, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.268519 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068380, term:4, msg-index:14068380, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.268531 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752835, term:4, msg-index:8752835, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.268542 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068381, term:4, msg-index:14068381, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.268563 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068382, term:4, msg-index:14068382, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.268561 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752836, term:4, msg-index:8752836, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.268585 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068383, term:4, msg-index:14068383, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.268596 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752837, term:4, msg-index:8752837, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.268606 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068384, term:4, msg-index:14068384, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.268624 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068385, term:4, msg-index:14068385, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.268629 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752838, term:4, msg-index:8752838, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.268650 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068386, term:4, msg-index:14068386, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.268662 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752839, term:4, msg-index:8752839, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.268671 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068387, term:4, msg-index:14068387, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.268690 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068388, term:4, msg-index:14068388, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.268694 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752840, term:4, msg-index:8752840, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.268709 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068389, term:4, msg-index:14068389, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.268728 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752841, term:4, msg-index:8752841, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.268732 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068390, term:4, msg-index:14068390, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.268763 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068391, term:4, msg-index:14068391, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.268771 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752842, term:4, msg-index:8752842, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.268783 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068392, term:4, msg-index:14068392, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.268802 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068393, term:4, msg-index:14068393, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.268808 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752843, term:4, msg-index:8752843, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.268824 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068394, term:4, msg-index:14068394, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.268841 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752844, term:4, msg-index:8752844, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.268844 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068395, term:4, msg-index:14068395, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.268870 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752845, term:4, msg-index:8752845, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.268872 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068396, term:4, msg-index:14068396, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.268893 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068397, term:4, msg-index:14068397, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.268901 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752846, term:4, msg-index:8752846, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.268914 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068398, term:4, msg-index:14068398, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.268928 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752847, term:4, msg-index:8752847, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.268941 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068399, term:4, msg-index:14068399, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.268966 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752848, term:4, msg-index:8752848, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.268968 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068400, term:4, msg-index:14068400, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.268995 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068401, term:4, msg-index:14068401, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.268999 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752849, term:4, msg-index:8752849, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269031 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752850, term:4, msg-index:8752850, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269031 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068402, term:4, msg-index:14068402, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269061 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068403, term:4, msg-index:14068403, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269065 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752851, term:4, msg-index:8752851, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.269095 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752852, term:4, msg-index:8752852, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269103 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068404, term:4, msg-index:14068404, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269123 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752853, term:4, msg-index:8752853, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.269137 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068405, term:4, msg-index:14068405, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269153 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752854, term:4, msg-index:8752854, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269169 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068406, term:4, msg-index:14068406, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.269184 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752855, term:4, msg-index:8752855, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.269202 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068407, term:4, msg-index:14068407, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269215 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752856, term:4, msg-index:8752856, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269228 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068408, term:4, msg-index:14068408, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269243 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752857, term:4, msg-index:8752857, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.269249 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068409, term:4, msg-index:14068409, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269259 00000147 VND ERROR vgId:5, msg:0x7f1d08006580 failed to process since not leader, gtid:0xad90232312160019:0x3bf301e231200022
05/15 06:39:55.269271 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752858, term:4, msg-index:8752858, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269275 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068410, term:4, msg-index:14068410, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.269274 00000147 VND ERROR vgId:5, msg:0x7f1d08006580 failed to propose since Database not ready, code:0x80000014, gtid:0xad90232312160019:0x3bf301e231200022
05/15 06:39:55.269301 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068411, term:4, msg-index:14068411, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269308 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752859, term:4, msg-index:8752859, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269334 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068412, term:4, msg-index:14068412, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.269340 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752860, term:4, msg-index:8752860, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.269367 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752861, term:4, msg-index:8752861, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269368 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068413, term:4, msg-index:14068413, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269391 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068414, term:4, msg-index:14068414, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269400 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752862, term:4, msg-index:8752862, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.269414 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068415, term:4, msg-index:14068415, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269445 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068416, term:4, msg-index:14068416, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269446 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752863, term:4, msg-index:8752863, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269469 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068417, term:4, msg-index:14068417, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269480 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752864, term:4, msg-index:8752864, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269502 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068418, term:4, msg-index:14068418, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269512 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752865, term:4, msg-index:8752865, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269533 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068419, term:4, msg-index:14068419, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269540 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752866, term:4, msg-index:8752866, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.269574 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068420, term:4, msg-index:14068420, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269582 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752867, term:4, msg-index:8752867, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269595 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068421, term:4, msg-index:14068421, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.269610 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752868, term:4, msg-index:8752868, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.269620 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068422, term:4, msg-index:14068422, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269641 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752869, term:4, msg-index:8752869, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269648 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068423, term:4, msg-index:14068423, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269676 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752870, term:4, msg-index:8752870, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269679 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068424, term:4, msg-index:14068424, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.269708 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752871, term:4, msg-index:8752871, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.269710 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068425, term:4, msg-index:14068425, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269739 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068426, term:4, msg-index:14068426, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269741 00000220 VND vgId:4, commit-cb is excuted, fsm:0x7f1d7813c0c0, index:8752872, term:4, msg-index:8752872, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269764 00000220 WAL ERROR vgId:4, unexpected wal log, index:8752873, since head checksum not passed
05/15 06:39:55.269772 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068427, term:4, msg-index:14068427, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269783 00000220 SYN ERROR vgId:4, sync leader wal read error, index:8752873, err:-2147479551 80001001, msg:WAL file is corrupted, syserr:0, sysmsg:Success, tm:352, cmt:8753281, fst:8737352, lst:8753281, snap:8737351, snap-tm:4, sby:0, stgy:2, bch:1, r-num:1, lcfg:-1, chging:0, rsto:0, {r-num:1, my:0, tdengine-server:6030}
taosd: /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/libs/sync/src/syncMain.c:3069: syncNodeCommit: Assertion `code == 0' failed.
05/15 06:39:55.269815 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068428, term:4, msg-index:14068428, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269844 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068429, term:4, msg-index:14068429, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.269865 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068430, term:4, msg-index:14068430, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269893 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068431, term:4, msg-index:14068431, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269922 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068432, term:4, msg-index:14068432, weak:0, code:0, state:102 leader, type:create-table
05/15 06:39:55.269960 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068433, term:4, msg-index:14068433, weak:0, code:0, state:102 leader, type:submit
05/15 06:39:55.269988 00000221 VND vgId:5, commit-cb is excuted, fsm:0x7f1d6c12f080, index:14068434, term:4, msg-index:14068434, weak:0, code:0, state:102 leader, type:submit

**Comment by sangshuduo** [comment]
Sync leader is restoring 看看是不是 taosd crash 重启了

**Comment by qianxitutu** [comment]
> Sync leader is restoring 看看是不是 taosd crash 重启了
 按照官网说的步骤（https://www.taosdata.com/engineering/974.html），并没有生成任何文件,docker 容器一直重启
![image](https://github.com/taosdata/TDengine/assets/22881731/e07a45d9-0b56-47aa-8b08-feffade301a8)

**Comment by sangshuduo** [comment]
你的 docker Tag 还是 3.0.1.4

**Comment by qianxitutu** [comment]
> 你的 docker Tag 还是 3.0.1.4

3.0.4.1 可以启动，但是会报这个错误
taos_ADAPTER error "" error_code=2324 model=restful req_id=0x6e8201e4355009ba error_msg=**Sync leader is restoring sql=show tables**

**Comment by sangshuduo** [comment]
> > 你的 docker Tag 还是 3.0.1.4
> 
> 3.0.4.1 可以启动，但是会报这个错误 taos\_ADAPTER error "" error\_code=2324 model=restful req\_id=0x6e8201e4355009ba error\_msg=**Sync leader is restoring sql=show tables**

请监控一下 3.0.4.1 的 taosd 是否有重启，如果有，请上传相应的 taodlog
