### ISSUE TITLE
流式计算创建流含有子查询无法创建流

### ISSUE THREAD

**Issue by GiNiTM** [taosdata/TDengine#21304]
版本号3.0.4.1
table：
  test.power
    schema:CREATE STABLE `power` (`ts` TIMESTAMP, `power` FLOAT) TAGS (`location` NCHAR(64))
  test.t3
     schema:CREATE TABLE `t3` USING `power` (`location`) TAGS ("电量")
sql: create stream if not exists my_stream fill_history 1
into test.power  as
select NOW() AS ts,sum(sum_power) from (select sum(power) as sum_power from test.t3 where ts<= NOW() and ts >= NOW() -7d
    interval(1h));
 报错：[-2147473851] TDengine ERROR (80002645): Unsupported stream query

**Comment by sangshuduo** [comment]
流计算暂时不支持子查询，将来会支持
