### ISSUE TITLE
删除数据数据库会重启

### ISSUE THREAD

**Issue by trytowish** [taosdata/TDengine#21341]
[https://github.com/taosdata/TDengine/issues/20898](https://github.com/taosdata/TDengine/issues/20898)
继续还是此问题，删除数据库中数据库表，数据库会重启。
服务端是3.0.2.0
客户端是DBeaver 23.0.4.202305071722
taos的 jar包是taos-jdbcdriver-3.0.2-dist.jar
[截图是删除操作](https://cloud.mail.163.com/dfs/service/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20230517103731.png?op=thumbFile&uid=wishtotry@163.com&account=wishtotry@163.com&file=eyJzIjoiZnM6Y2xvdWRzdG9yYWdlLm1haWwuMTYzOjQ4NDQwNzM3ODIxMCIsInNmIjoiNDg1NzgxNzc2MDI4OjQ4NDQwNzM3ODIxMCIsImkiOjUwNzA5NDc2Mjc1MTEzMTcsImNzIjp7InQiOjEsInYiOiI5YjgxMzliNmNlNjFjN2Q4MDI3MTU1MmZmYWJlNDU2MiJ9LCJzeiI6MTE2MTAsImN0IjoxNjg0MjkxMTc2OTgwfQ&size=1000x1000)

然后数据库就访问不到，日志显示数据库服务重启了。

5/17 09:58:27.090731 00000079 MND stb:1.realtimedata.yc, start to retrieve meta
05/17 09:58:28.107702 00000100 TSD vgId:3, delete data from table suid:950466000756978635 uid:2383313999545694035 skey:1682407356000 eKey:1684288762000 at version 260076771 since success
05/17 09:58:28.590917 00000079 MND stb:1.realtimedata.electricity_generation, start to retrieve meta
05/17 09:58:28.590938 00000079 MND stb:1.realtimedata.charge_discharge_times, start to retrieve meta
05/17 09:58:33.091741 00000079 MND stb:1.realtimedata.charge_discharge, start to retrieve meta
==================================================
                new log file                      
==================================================
==================================================
                new log file                      
==================================================
==================================================
                new log file                      
==================================================
==================================================
                new log file                      
==================================================
==================================================
                new log file                      
==================================================
05/17 09:58:37.572946 00000126 SYN ERROR vgId:3, sync leader failed to sync propose since not ready, type:submit, last:260076838, cmt:260076838, term:411, commit-index:260076838, first-ver:259892100, last-ver:260076838, min:-1, snap:259997074, snap-term:410, elect-times:0, as-leader-times:1, cfg-ch-times:0, hit:0, mis:0, hb-slow:0, hbr-slow:0, aq-items:36871, snaping:-1, replicas:1, last-cfg:-1, chging:0, restore:0, quorum:1, elect-lc-timer:1, hb:0, {0:-1 0}, {r-num:1, my:0, td1:6030}, hb:{0:1684288717075}, hbr:{0:1684288717075}
05/17 09:58:37.574746 00000126 VND ERROR vgId:3, msg:0x7f89bc00b388 failed to propose since Sync not ready for propose, code:0x80000911, gtid:0xb760016e363230ed:0x6110276e36b26b0
05/17 09:58:37.583062 00000126 SYN ERROR vgId:3, sync leader failed to sync propose since not ready, type:submit, last:260076838, cmt:260076838, term:411, commit-index:260076838, first-ver:259892100, last-ver:260076838, min:-1, snap:259997074, snap-term:410, elect-times:0, as-leader-times:1, cfg-ch-times:0, hit:0, mis:0, hb-slow:0, hbr-slow:0, aq-items:38208, snaping:-1, replicas:1, last-cfg:-1, chging:0, restore:0, quorum:1, elect-lc-timer:1, hb:0, {0:-1 0}, {r-num:1, my:0, td1:6030}, hb:{0:1684288717075}, hbr:{0:1684288717075}
05/17 09:58:37.583402 00000127 SYN ERROR vgId:2, sync leader failed to sync propose since not ready, type:submit, last:262537244, cmt:262537244, term:411, commit-index:262537244, first-ver:262365036, last-ver:262537244, min:-1, snap:262461698, snap-term:410, elect-times:0, as-leader-times:1, cfg-ch-times:0, hit:0, mis:0, hb-slow:0, hbr-slow:0, aq-items:38006, snaping:-1, replicas:1, last-cfg:-1, chging:0, restore:0, quorum:1, elect-lc-timer:1, hb:0, {0:-1 0}, {r-num:1, my:0, td1:6030}, hb:{0:1684288717075}, hbr:{0:1684288717075}
05/17 09:58:37.584729 00000127 VND ERROR vgId:2, msg:0x7f89bc008e58 failed to propose since Sync not ready for propose, code:0x80000911, gtid:0xb760016e351430e9:0x6110276e35b26a8
05/17 09:58:37.584728 00000126 VND ERROR vgId:3, msg:0x7f89b80209c8 failed to propose since Sync not ready for propose, code:0x80000911, gtid:0xb760016e329c30de:0x6110276e32b2692
05/17 09:58:37.586171 00000127 SYN ERROR vgId:2, sync leader failed to sync propose since not ready, type:submit, last:262537244, cmt:262537244, term:411, commit-index:262537244, first-ver:262365036, last-ver:262537244, min:-1, snap:262461698, snap-term:410, elect-times:0, as-leader-times:1, cfg-ch-times:0, hit:0, mis:0, hb-slow:0, hbr-slow:0, aq-items:38126, snaping:-1, replicas:1, last-cfg:-1, chging:0, restore:0, quorum:1, elect-lc-timer:1, hb:0, {0:-1 0}, {r-num:1, my:0, td1:6030}, hb:{0:1684288717075}, hbr:{0:1684288717075}
05/17 09:58:37.586327 00000126 SYN ERROR vgId:3, sync leader failed to sync propose since not ready, type:submit, last:260076838, cmt:260076838, term:411, commit-index:260076838, first-ver:259892100, last-ver:260076838, min:-1, snap:259997074, snap-term:410, elect-times:0, as-leader-times:1, cfg-ch-times:0, hit:0, mis:0, hb-slow:0, hbr-slow:0, aq-items:38418, snaping:-1, replicas:1, last-cfg:-1, chging:0, restore:0, quorum:1, elect-lc-timer:1, hb:0, {0:-1 0}, {r-num:1, my:0, td1:6030}, hb:{0:1684288717075}, hbr:{0:1684288717075}
05/17 09:58:37.587532 00000126 VND ERROR vgId:3, msg:0x7f89bc00b4b8 failed to propose since Sync not ready for propose, code:0x80000911, gtid:0xb760016e33c830e4:0x6110276e33b269f
05/17 09:58:37.587532 00000127 VND ERROR vgId:2, msg:0x7f89b8022a28 failed to propose since Sync not ready for propose, code:0x80000911, gtid:0xb760016e357630eb:0x6110276e35b26ac
05/17 09:58:37.588911 00000127 SYN ERROR vgId:2, sync leader failed to sync propose since not ready, type:submit, last:262537244, cmt:262537244, term:411, commit-index:262537244, first-ver:262365036, last-ver:262537244, min:-1, snap:262461698, snap-term:410, elect-times:0, as-leader-times:1, cfg-ch-times:0, hit:0, mis:0, hb-slow:0, hbr-slow:0, aq-items:38364, snaping:-1, replicas:1, last-cfg:-1, chging:0, restore:0, quorum:1, elect-lc-timer:1, hb:0, {0:-1 0}, {r-num:1, my:0, td1:6030}, hb:{0:1684288717075}, hbr:{0:1684288717075}
05/17 09:58:37.589067 00000126 SYN ERROR vgId:3, sync leader failed to sync propose since not ready, type:submit, last:260076838, cmt:260076838, term:411, commit-index:260076838, first-ver:259892100, last-ver:260076838, min:-1, snap:259997074, snap-term:410, elect-times:0, as-leader-times:1, cfg-ch-times:0, hit:0, mis:0, hb-slow:0, hbr-slow:0, aq-items:38643, snaping:-1, replicas:1, last-cfg:-1, chging:0, restore:0, quorum:1, elect-lc-timer:1, hb:0, {0:-1 0}, {r-num:1, my:0, td1:6030}, hb:{0:1684288717075}, hbr:{0:1684288717075}
05/17 09:58:37.590730 00000126 VND ERROR vgId:3, msg:0x7f8a0812dc68 failed to propose since Sync not ready for propose, code:0x80000911, gtid:0xb760016e32bf30df:0x6110276e32b2694
05/17 09:58:37.590736 00000127 VND ERROR vgId:2, msg:0x7f8a0812ce18 failed to propose since Sync not ready for propose, code:0x80000911, gtid:0xb760016e342430e7:0x6110276e34b26a4
05/17 09:58:37.592378 00000127 SYN ERROR vgId:2, sync leader failed to sync propose since not ready, type:submit, last:262537244, cmt:262537244, term:411, commit-index:262537244, first-ver:262365036, last-ver:262537244, min:-1, snap:262461698, snap-term:410, elect-times:0, as-leader-times:1, cfg-ch-times:0, hit:0, mis:0, hb-slow:0, hbr-slow:0, aq-items:38711, snaping:-1, replicas:1, last-cfg:-1, chging:0, restore:0, quorum:1, elect-lc-timer:1, hb:0, {0:-1 0}, {r-num:1, my:0, td1:6030}, hb:{0:1684288717075}, hbr:{0:1684288717075}
05/17 09:58:37.592501 00000126 SYN ERROR vgId:3, sync leader failed to sync propose since not ready, type:submit, last:260076838, cmt:260076838, term:411, commit-index:260076838, first-ver:259892100, last-ver:260076838, min:-1, snap:259997074, snap-term:410, elect-times:0, as-leader-times:1, cfg-ch-times:0, hit:0, mis:0, hb-slow:0, hbr-slow:0, aq-items:39022, snaping:-1, replicas:1, last-cfg:-1, chging:0, restore:0, quorum:1, elect-lc-timer:1, hb:0, {0:-1 0}, {r-num:1, my:0, td1:6030}, hb:{0:1684288717075}, hbr:{0:1684288717075}
05/17 09:58:37.593573 00000127 VND ERROR vgId:2, msg:0x7f89bc00bec8 failed to propose since Sync not ready for propose, code:0x80000911, gtid:0xb760016e363230ed:0x6110276e36b26af
05/17 09:58:37.593632 00000126 VND ERROR vgId:3, msg:0x7f89bc00b998 failed to propose since Sync not ready for propose, code:0x80000911, gtid:0xb760016e33b730e3:0x6110276e33b269c
05/17 09:58:37.595079 00000127 SYN ERROR vgId:2, sync leader failed to sync propose since not ready, type:submit, last:262537244, cmt:262537244, term:411, commit-index:262537244, first-ver:262365036, last-ver:262537244, min:-1, snap:262461698, snap-term:410, elect-times:0, as-leader-times:1, cfg-ch-times:0, hit:0, mis:0, hb-slow:0, hbr-slow:0, aq-items:39083, snaping:-1, replicas:1, last-cfg:-1, chging:0, restore:0, quorum:1, elect-lc-timer:1, hb:0, {0:-1 0}, {r-num:1, my:0, td1:6030}, hb:{0:1684288717075}, hbr:{0:1684288717075}
05/17 09:58:37.595231 00000126 SYN ERROR vgId:3, sync leader failed to sync propose since not ready, type:submit, last:260076838, cmt:260076838, term:411, commit-index:260076838, first-ver:259892100, last-ver:260076838, min:-1, snap:259997074, snap-term:410, elect-times:0, as-leader-times:1, cfg-ch-times:0, hit:0, mis:0, hb-slow:0, hbr-slow:0, aq-items:39351, snaping:-1, replicas:1, last-cfg:-1, chging:0, restore:0, quorum:1, elect-lc-timer:1, hb:0, {0:-1 0}, {r-num:1, my:0, td1:6030}, hb:{0:1684288717075}, hbr:{0:1684288717075}
05/17 09:58:37.596839 00000127 VND ERROR vgId:2, msg:0x7f8a08122938 failed to propose since Sync not ready for propose, code:0x80000911, gtid:0xb760016e329830dd:0x6110276e32b2690
05/17 09:58:37.596885 00000126 VND ERROR vgId:3, msg:0x7f8a0c1333e8 failed to propose since Sync not ready for propose, code:0x80000911, gtid:0xb760016e33f530e5:0x6110276e33b26a0
05/17 09:58:37.598246 00000127 SYN ERROR vgId:2, sync leader failed to sync propose since not ready, type:submit, last:262537244, cmt:262537244, term:411, commit-index:262537244, first-ver:262365036, last-ver:262537244, min:-1, snap:262461698, snap-term:410, elect-times:0, as-leader-times:1, cfg-ch-times:0, hit:0, mis:0, hb-slow:0, hbr-slow:0, aq-items:39527, snaping:-1, replicas:1, last-cfg:-1, chging:0, restore:0, quorum:1, elect-lc-timer:1, hb:0, {0:-1 0}, {r-num:1, my:0, td1:6030}, hb:{0:1684288717075}, hbr:{0:1684288717075}
05/17 09:58:37.598388 00000126 SYN ERROR vgId:3, sync leader failed to sync propose since not ready, type:submit, last:260076838, cmt:260076838, term:411, commit-index:260076838, first-ver:259892100, last-ver:260076838, min:-1, snap:259997074, snap-term:410, elect-times:0, as-leader-times:1, cfg-ch-times:0, hit:0, mis:0, hb-slow:0, hbr-slow:0, aq-items:39758, snaping:-1, replicas:1, last-cfg:-1, chging:0, restore:0, quorum:1, elect-lc-timer:1, hb:0, {0:-1 0}, {r-num:1, my:0, td1:6030}, hb:{0:1684288717075}, hbr:{0:1684288717075}
05/17 09:58:37.599865 00000126 VND ERROR vgId:3, msg:0x7f89b8024e38 failed to propose since Sync not ready for propose, code:0x80000911, gtid:0xb760016e33a130e1:0x6110276e33b2698
05/17 09:58:37.600672 00000127 VND ERROR vgId:2, msg:0x7f8a081226d8 failed to propose since Sync not ready for propose, code:0x80000911, gtid:0xb760016e329c30de:0x6110276e32b2693

5/17 09:58:36.984841 00000053 DND startup path:/root args:taosd
05/17 09:58:36.985145 00000053 UTL apoll url not load
05/17 09:58:36.985177 00000053 UTL load from cfg file /etc/taos//taos.cfg success
05/17 09:58:36.985184 00000053 UTL env file:.env not load
05/17 09:58:36.985187 00000053 UTL load from env variables cfg success
05/17 09:58:36.985287 00000053 UTL                      global config
05/17 09:58:36.985294 00000053 UTL =================================================================
05/17 09:58:36.985296 00000053 UTL cfg_file     firstEp                  td1:6030
05/17 09:58:36.985298 00000053 UTL default      secondEp                 td1:6030
05/17 09:58:36.985300 00000053 UTL cfg_file     fqdn                     td1
05/17 09:58:36.985302 00000053 UTL default      serverPort               6030
05/17 09:58:36.985304 00000053 UTL default      tempDir                  /tmp/
05/17 09:58:36.985306 00000053 UTL default      minimalTmpDirGB          1.00
05/17 09:58:36.985327 00000053 UTL default      shellActivityTimer       3
05/17 09:58:36.985330 00000053 UTL default      compressMsgSize          -1
05/17 09:58:36.985332 00000053 UTL default      compressColData          -1
05/17 09:58:36.985335 00000053 UTL default      queryPolicy              1
05/17 09:58:36.985337 00000053 UTL default      enableQueryHb            0
05/17 09:58:36.985338 00000053 UTL default      querySmaOptimize         0

**Comment by sangshuduo** [comment]
先升级到最新版本再看看
