### ISSUE TITLE
WAL log incomplete 

### ISSUE THREAD

**Issue by longcf6666** [taosdata/TDengine#21360]
![image](https://github.com/taosdata/TDengine/assets/98379149/db44e954-dde7-40c5-a0d7-bb75e8e46245)

**Comment by yu285** [comment]
可以等 3.0.5.0 这个问题已经修复。

**Comment by nrwflqzr-zwhy** [comment]
> 可以等 3.0.5.0 这个问题已经修复。

我使用的版本是3.1.1.0-linux-x64 我也出现了这样的错误

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
