### ISSUE TITLE
Unexpected generic error with `LIKE` query

### ISSUE THREAD

**Issue by YuanchengJiang** [taosdata/TDengine#21368]
**Bug Description**
Unexpected generic error with `LIKE` query: 
```
select count(symbol) from test where symbol like 'INTC';   // OK
select count(symbol) from test where not symbol like 'INTC';   // Exception
select count(symbol) from test where not symbol not like 'INTC'  // OK
```

**To Reproduce**
```
create database test;
use test;
create table test(time TIMESTAMP, symbol VARCHAR(16), price DOUBLE, day_volume INT);
insert into test values ('2023-04-14 19:10:48.002','INTC',31.82,NULL);
select count(symbol) from test where not symbol like 'INTC';
```

**Expected Behavior**
The query `select count(symbol) from test where not symbol like 'INTC';` should return result.

**Environment (please complete the following information):**
 - OS: ubuntu 20.04
 - TDengine Version: 3.0.4.1

**Comment by yu285** [comment]
not like 是固定语法

**Comment by YuanchengJiang** [comment]
@yu285 `where not symbol like 'INTC'`的not不是`not like`的not. 就像`where not True`应该是`False`一样.

`select count(symbol) from test where not (symbol like 'INTC')`
