### ISSUE TITLE
abort stream

### ISSUE THREAD

**Issue by yuao1112** [taosdata/TDengine#21372]
**Bug Description**
大致步骤说明：
a、前提：
1、【test库】生成原数据【a】超级表
2、创建流【S】，将【test库】数据聚合到【sum_data】库【b】超级表
b、自测方向：
1、将【test库】数据，创建流【S1】转移到【5年库】
2、创建流【S2】，将【5年库】聚合到【sum_data】库【b】超级表
3、往原【test库】或者【5年库】写数据
c、问题：
删除原聚合流【S】，往【test库】写数据后，【5年库】能同步到数据，但聚合【sum_data库】中数据不再聚合。
删除新【S2】，再重新创建【S2】流，仍然不会进行数据的聚合

流程图如下：
![image](https://github.com/taosdata/TDengine/assets/24371179/4eec247d-ab07-47b9-bf9f-381391d927df)

**To Reproduce**
一、前提
环境：

tdEngine:
![image](https://github.com/taosdata/TDengine/assets/24371179/03ddef75-6963-449b-a43f-1b44837e1878)

window11：

使用docker部署tdEngine

模拟数据

通过【taosBenchmark】进行数据模拟，详见：https://docs.taosdata.com/reference/taosbenchmark/

数据内容：

创建【test】库，共5张表，每张表10条数据

关键参数：

【child_table_count 】：控制子表的数量，目前设置为5个

【insert_rows 】：控制子表内的数据量，目前设置为10条

模拟数据命令：

taosBenchmark -f /etc/taos/benchmarktest/insert.json

insert.json文件内容：

{"filetype":"insert","cfgdir":"/etc/taos","host":"127.0.0.1","port":6030,"user":"root","password":"taosdata","connection_pool_size":8,"thread_count":4,"create_table_thread_count":7,"result_file":"./insert_res.txt","confirm_parameter_prompt":"no","insert_interval":0,"interlace_rows":100,"num_of_records_per_req":100,"prepared_rand":10000,"chinese":"no","databases":[{"dbinfo":{"name":"test","drop":"yes","replica":1,"precision":"ms","keep":3650,"minRows":100,"maxRows":4096,"comp":2},"super_tables":[{"name":"st_temphumi","child_table_exists":"no","childtable_count":20,"childtable_prefix":"temphumi_","escape_character":"yes","auto_create_table":"yes","batch_create_tbl_num":10,"data_source":"rand","insert_mode":"taosc","non_stop_mode":"no","line_protocol":"line","child_table_count":5,"insert_rows":10,"childtable_limit":10,"childtable_offset":100,"interlace_rows":0,"insert_interval":0,"partial_col_num":0,"disorder_ratio":0,"disorder_range":1000,"timestamp_step":3600000,"start_timestamp":"2019-01-01 19:36:36.000","sample_format":"csv","sample_file":"./sample.csv","use_sample_ts":"no","tags_file":"","columns":[{"type":"INT","name":"temp","max":10000,"min":1000},{"type":"INT","name":"humi","max":30,"min":1}],"tags":[{"name":"devicetype","type":"VARCHAR","len":32,"values":["mss570x","mss620","mss620br","mss620hk","mss620r","mss630","mss710","mss710r","mss810","mss820","msxc0","msxh0","mts200","mts200b","mts960"]},{"name":"subtype","type":"VARCHAR","len":32,"values":["au","br","eu","fr","uk","us"]},{"type":"TINYINT","name":"mainversion","max":9,"min":1},{"name":"region","type":"VARCHAR","len":32,"values":["ap","eu","us"]},{"name":"batchnumber","type":"VARCHAR","len":20,"values":["0100002112","0100012112","0100022112","0100032112","0101012105","0200092112","02000A2112","1001112108","1515152108","2110292110","2111022111","2111032111","2111102111","2111112111","2111122111","2111132111","5100012303","5108012211","5108012212","5108012302"]}]}]}]}

模拟步骤：
1、创建【sum_data】库中的聚合超级表【st_aggr_temphumi】

CREATE database sum_data;

CREATE STABLE sum_data.st_aggr_temphumi (ts TIMESTAMP,temp INT,humi INT) TAGS (devicetype VARCHAR(32), subtype VARCHAR(32), mainversion TINYINT UNSIGNED, region VARCHAR(32), batchnumber VARCHAR(20));

2、创建流【aggr_temphumi】将【test】源数据聚合到【sum_data】库
CREATE STREAM aggr_temphumi TRIGGER AT_ONCE FILL_HISTORY 1 INTO sum_data.st_aggr_temphumi TAGS(devicetype,subType,mainVersion,region,batchNumber) SUBTABLE(concat("aggr_",tname)) AS SELECT _wstart ts,avg(temp) temp,sum(humi) humi FROM test.st_temphumi PARTITION BY tbname tname, devicetype,subType,mainVersion,region,batchNumber interval(1d);

3、创建【5年】库，同时创建与【test】源库相同的超级表
create database  telemetry_history_5year CACHEMODEL 'last_row' buffer 64  KEEP 1832d,1832d,1832d DURATION 30d;
CREATE STABLE telemetry_history_5year.st_temphumi (ts TIMESTAMP,temp INT,humi INT) TAGS (devicetype VARCHAR(32), subtype VARCHAR(32), mainversion TINYINT UNSIGNED, region VARCHAR(32), batchnumber VARCHAR(20));

4、创建流【migrate_temphumi】将【test】源数据转移到【telemetry_history_5year】库
CREATE STREAM migrate_temphumi TRIGGER AT_ONCE FILL_HISTORY 1 INTO telemetry_history_5year.st_temphumi TAGS(devicetype,subType,mainVersion,region,batchNumber) SUBTABLE(tname) AS SELECT ts,temp,humi FROM test.st_temphumi PARTITION BY tbname tname, devicetype,subType,mainVersion,region,batchNumber;

5、创建【新流】将转移后的【源数据】聚合到【sum_data】
CREATE STREAM aggr_temphumi_new TRIGGER AT_ONCE FILL_HISTORY 1 INTO sum_data.st_aggr_temphumi TAGS(devicetype,subType,mainVersion,region,batchNumber) SUBTABLE(concat("aggr_",tname)) AS SELECT _wstart ts,avg(temp) temp,sum(humi) humi FROM telemetry_history_5year.st_temphumi PARTITION BY tbname tname, devicetype,subType,mainVersion,region,batchNumber interval(1d);

6、删除原流

drop stream aggr_temphumi;

7、数据写入
#原库【test】
INSERT INTO temphumi_0 USING test.st_temphumi (devicetype, subtype, mainversion, region, batchnumber) TAGS ("mts200", "eu", 1, "ap", "02000A2112") (ts,temp,humi) VALUES (1547206599000, 2000,6);
#【telemetry_history_5year】库
INSERT INTO temphumi_0 USING telemetry_history_5year.st_temphumi (devicetype, subtype, mainversion, region, batchnumber) TAGS ("mts200", "eu", 1, "ap", "02000A2112") (ts,temp,humi) VALUES (1547379396000, 2000,2);

**Comment by yu285** [comment]
我们看下

**Comment by yu285** [comment]
版本补充： 3.0.4.0

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
