### ISSUE TITLE
Relation between vnode and table

### ISSUE THREAD

**Issue by c2002509** [taosdata/TDengine#2139]
tdengine的普通表和vnode的关系：
1.meta里保存着各个vnode对应的全量表？如果终端很多，meta量是否相当大
2.vnode和普通表是用算法映射的，还是一个个维护关系的？写入和查询时，怎么根据表找到vnode
3.根据tag查询时，怎么先过滤出vnode，再查询

**Comment by Aries-Lee1991** [comment]
先看一下官网文档：https://www.taosdata.com/cn/documentation/more-on-system-architecture/#%E9%9B%86%E7%BE%A4%E8%AE%BE%E8%AE%A1

**Comment by c2002509** [comment]
> 先看一下官网文档：https://www.taosdata.com/cn/documentation/more-on-system-architecture/#%E9%9B%86%E7%BE%A4%E8%AE%BE%E8%AE%A1

文档已经看了，没有找到答案，普通表和vnode之间的映射，具体怎么选择vnode的

**Comment by liuyq-617** [comment]
vnode对于您来说是透明的，是我们的一个虚拟化手段，做负载均衡用的。您写表和查询的时候，直接指定库名和表名就可以了

**Comment by c2002509** [comment]
> vnode对于您来说是透明的，是我们的一个虚拟化手段，做负载均衡用的。您写表和查询的时候，直接指定库名和表名就可以了

嗯，明白，有这个疑问，方便讲解下吗

**Comment by liuyq-617** [comment]
wechat:183030384
我们微信上说吧，方便点

**Comment by liuyq-617** [comment]
1.meta里保存着各个vnode对应的全量表？如果终端很多，meta量是否相当大
 当表的数量非常大（上亿级别）的时候确实会有这个问题，meta量会很大。
2.vnode和普通表是用算法映射的，还是一个个维护关系的？写入和查询时，怎么根据表找到vnode
 vnode是虚拟了一块空间出来，存放表的。都会在数据节点存储这些对应关系
3.根据tag查询时，怎么先过滤出vnode，再查询
 会根据meta信息去找出数据在哪些vnode里，然后再去vnode里检索数据

**Comment by c2002509** [comment]
> 1.meta里保存着各个vnode对应的全量表？如果终端很多，meta量是否相当大
> 当表的数量非常大（上亿级别）的时候确实会有这个问题，meta量会很大。
> 2.vnode和普通表是用算法映射的，还是一个个维护关系的？写入和查询时，怎么根据表找到vnode
> vnode是虚拟了一块空间出来，存放表的。都会在数据节点存储这些对应关系
> 3.根据tag查询时，怎么先过滤出vnode，再查询
> 会根据meta信息去找出数据在哪些vnode里，然后再去vnode里检索数据

感谢！
