### ISSUE TITLE
K8S  TDengine cluster can't be connected by CLI

### ISSUE THREAD

**Issue by yuchengao0721** [taosdata/TDengine#21418]
==================================================
                new log file                      
==================================================
05/22 18:03:17.492160 00032440 UTL apoll url not load
05/22 18:03:17.493163 00032440 UTL load from cfg file C:\TDengine\cfg\\taos.cfg success
05/22 18:03:17.493163 00032440 UTL env file:.env not load
05/22 18:03:17.493163 00032440 UTL load from env variables cfg success
05/22 18:03:17.493163 00032440 UTL                      global config
05/22 18:03:17.493163 00032440 UTL =================================================================
05/22 18:03:17.493163 00032440 UTL cfg_file     firstEp                  192.168.10.221:30050
05/22 18:03:17.493163 00032440 UTL default      secondEp                 DESKTOP-RI3P684:6030
05/22 18:03:17.493163 00032440 UTL default      fqdn                     DESKTOP-RI3P684
05/22 18:03:17.493163 00032440 UTL default      serverPort               6030
05/22 18:03:17.493163 00032440 UTL default      tempDir                  C:\Windows\Temp\
05/22 18:03:17.493163 00032440 UTL default      minimalTmpDirGB          1.00
05/22 18:03:17.493163 00032440 UTL default      shellActivityTimer       3
05/22 18:03:17.493163 00032440 UTL default      compressMsgSize          -1
05/22 18:03:17.493163 00032440 UTL default      compressColData          -1
05/22 18:03:17.493163 00032440 UTL default      queryPolicy              1
05/22 18:03:17.493163 00032440 UTL default      querySmaOptimize         0
05/22 18:03:17.493163 00032440 UTL default      queryPlannerTrace        0
05/22 18:03:17.493163 00032440 UTL default      queryNodeChunkSize       32768
05/22 18:03:17.493163 00032440 UTL default      queryUseNodeAllocator    1
05/22 18:03:17.493163 00032440 UTL default      keepColumnName           0
05/22 18:03:17.493163 00032440 UTL default      smlChildTableName        
05/22 18:03:17.493163 00032440 UTL default      smlTagName               _tag_null
05/22 18:03:17.493163 00032440 UTL default      smlDataFormat            0
05/22 18:03:17.493163 00032440 UTL default      smlBatchSize             10000
05/22 18:03:17.493163 00032440 UTL default      maxMemUsedByInsert       1024
05/22 18:03:17.493163 00032440 UTL default      useAdapter               0
05/22 18:03:17.493163 00032440 UTL default      crashReporting           1
05/22 18:03:17.493163 00032440 UTL default      configDir                C:\TDengine\cfg\
05/22 18:03:17.493163 00032440 UTL default      scriptDir                C:\TDengine\cfg\
05/22 18:03:17.493163 00032440 UTL default      logDir                   C:\TDengine\log\
05/22 18:03:17.493163 00032440 UTL default      minimalLogDirGB          1.00
05/22 18:03:17.493163 00032440 UTL default      numOfLogLines            10000000
05/22 18:03:17.493163 00032440 UTL default      asyncLog                 1
05/22 18:03:17.493163 00032440 UTL default      logKeepDays              0
05/22 18:03:17.493163 00032440 UTL default      debugFlag                0
05/22 18:03:17.493163 00032440 UTL default      simDebugFlag             143
05/22 18:03:17.493163 00032440 UTL default      tmrDebugFlag             131
05/22 18:03:17.493163 00032440 UTL default      uDebugFlag               131
05/22 18:03:17.493163 00032440 UTL default      rpcDebugFlag             131
05/22 18:03:17.493163 00032440 UTL default      jniDebugFlag             131
05/22 18:03:17.493163 00032440 UTL default      qDebugFlag               131
05/22 18:03:17.493163 00032440 UTL default      cDebugFlag               131
05/22 18:03:17.493163 00032440 UTL default      timezone                 Asia/Shanghai (UTC, +0800)
05/22 18:03:17.493163 00032440 UTL default      locale                   en_US.UTF-8
05/22 18:03:17.493163 00032440 UTL default      charset                  UTF-8
05/22 18:03:17.493163 00032440 UTL default      assert                   1
05/22 18:03:17.493163 00032440 UTL default      enableCoreFile           1
05/22 18:03:17.493163 00032440 UTL default      numOfCores               12.00
05/22 18:03:17.493163 00032440 UTL default      openMax                  0
05/22 18:03:17.493163 00032440 UTL default      streamMax                0
05/22 18:03:17.493163 00032440 UTL default      pageSizeKB               0
05/22 18:03:17.493163 00032440 UTL default      totalMemoryKB            33462080
05/22 18:03:17.493163 00032440 UTL default      os sysname               Windows_NT
05/22 18:03:17.493163 00032440 UTL default      os nodename              DESKTOP-RI3P684
05/22 18:03:17.493163 00032440 UTL default      os release               6
05/22 18:03:17.493163 00032440 UTL default      os version               2
05/22 18:03:17.493163 00032440 UTL default      os machine               AMD64
05/22 18:03:17.493163 00032440 UTL default      version                  3.0.2.6
05/22 18:03:17.493163 00032440 UTL default      compatible_version       3.0.0.0
05/22 18:03:17.493163 00032440 UTL default      gitinfo                  0993813213efe3e18a0fcb5ab26538b811451798
05/22 18:03:17.493163 00032440 UTL default      buildinfo                Built at 2023-02-23 11:34:10
05/22 18:03:17.493163 00032440 UTL =================================================================
05/22 18:03:17.498160 00033464 QRY catalog update thread started
05/22 18:03:17.498160 00032440 QRY scheduler 0x31373036374341 initizlized, maxJob:1000
05/22 18:03:17.502255 00032440 TSC connecting to server, numOfEps:2 inUse:0 user:root db:(null) key:root:dcc5bed04851fec854c035b2e40263b6:(null):0
05/22 18:03:17.502255 00032440 TSC ep:0, 192.168.10.221:30050
05/22 18:03:17.502255 00032440 TSC ep:1, DESKTOP-RI3P684:6030
05/22 18:03:19.537652 00026912 RPC ERROR TSC msg batch-meta failed to send, conn 000001A95661CE00 failed to connect to taosdata-tdengine-0.taosdata-tdengine.aims-dev.svc.cluster.local:6030, reason: connection refused, gtid:0xd99b6ce9c88200:0x660c042e9c800003
05/22 18:03:29.891189 00012592 QRY ERROR Got error rsp, error:some vnode/qnode/mnode(s) out of service
05/22 18:03:29.891189 00012592 QRY ERROR QID:d99b6ce9c8820003 CTG:000001A9532D68E0 Get table 1.information_schema.ins_grants meta failed with error some vnode/qnode/mnode(s) out of service
05/22 18:03:29.891189 00024488 QRY ERROR PARSER: 0xd99b6ce9c8820003 catalogGetTableMeta error, code:some vnode/qnode/mnode(s) out of service, dbName:information_schema, tbName:ins_grants
05/22 18:03:29.891189 00024488 TSC ERROR 0x4 error occurs, code:Fail to get table info, return to user app, reqId:0xd99b6ce9c8820003
05/22 18:03:29.907231 00026912 RPC ERROR TSC msg batch-meta failed to send, conn 000001A95661D1A0 failed to connect to taosdata-tdengine-0.taosdata-tdengine.aims-dev.svc.cluster.local:6030, reason: connection refused, gtid:0xd99b6ce9c88200:0x660c042e9c800003
05/22 18:03:29.907231 00012180 QRY ERROR Got error rsp, error:some vnode/qnode/mnode(s) out of service
05/22 18:03:29.907231 00012180 QRY ERROR QID:d99b6ce9c8820002 CTG:000001A9532D68E0 Get table 1.information_schema.ins_databases meta failed with error some vnode/qnode/mnode(s) out of service
05/22 18:03:29.907231 00025760 QRY ERROR PARSER: 0xd99b6ce9c8820002 catalogGetTableMeta error, code:some vnode/qnode/mnode(s) out of service, dbName:information_schema, tbName:ins_databases
05/22 18:03:29.907231 00025760 TSC ERROR 0x3 error occurs, code:Fail to get table info, return to user app, reqId:0xd99b6ce9c8820002
05/22 18:03:30.047392 00027060 RPC ERROR TSC msg heartbeat failed to send, conn 000001A95661CA60 failed to connect to taosdata-tdengine-0.taosdata-tdengine.aims-dev.svc.cluster.local:6030, reason: connection refused, gtid:0xd99b6ce9f18900:0x660c042e9f10000b

本地已经设置过host
192.168.10.221 taosdata-tdengine-0.taosdata-tdengine.aims-dev.svc.cluster.local

**Comment by sangshuduo** [comment]
Please use RESTful interface to access TDenigine inside the Kubernetes cluster.

**Comment by yuchengao0721** [comment]
> Please use RESTful interface to access TDenigine inside the Kubernetes cluster.

如果我要使用的话，是不是必须在k8s上暴露6030端口？或者采用websocket的连接方式走6041端口？

**Comment by sangshuduo** [comment]
> > Please use RESTful interface to access TDenigine inside the Kubernetes cluster.
> 
> 如果我要使用的话，是不是必须在k8s上暴露6030端口？或者采用websocket的连接方式走6041端口？

可以使用 6041 websocket 接口

**Comment by ohhhyuan** [comment]
想问一下，你K8S部署的TD集群，怎么将手动部署的数据迁移到容器里的啊
