### ISSUE TITLE
taosd crashing on armv5

### ISSUE THREAD

**Issue by mwo-ext-airmaster** [taosdata/TDengine#21412]
**Bug Description**
Configuring/building using:
-DBUILD_TOOLS=false -DCPUTYPE=aarch32
produces binary that segfaults on armv5.

The segfault happens when starting taosd. The core file was named "mnode-sync-11".

mwj-ext@mwjext-ThinkPad-T14-Gen-2a:~/remote-git/hp1/buildroot$ gdb-multiarch output/build/tdengine-3.0.4.1/build/bin/taosd mnode-sync.11.core 
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from output/build/tdengine-3.0.4.1/build/bin/taosd...

warning: Can't open file /usr/sbin/taosd during file-backed mapping note processing

warning: Can't open file /usr/lib/libgcc_s.so.1 during file-backed mapping note processing

warning: Can't open file /usr/lib/libresolv-2.31.so during file-backed mapping note processing

warning: Can't open file /usr/lib/libnss_dns-2.31.so during file-backed mapping note processing

warning: Can't open file /usr/lib/libnss_files-2.31.so during file-backed mapping note processing

warning: Can't open file /usr/lib/libc-2.31.so during file-backed mapping note processing

warning: Can't open file /usr/lib/librt-2.31.so during file-backed mapping note processing

warning: Can't open file /usr/lib/libdl-2.31.so during file-backed mapping note processing

warning: Can't open file /usr/lib/libpthread-2.31.so during file-backed mapping note processing

warning: Can't open file /usr/lib/libm-2.31.so during file-backed mapping note processing

warning: Can't open file /usr/lib/libatomic.so.1.2.0 during file-backed mapping note processing

warning: Can't open file /usr/lib/ld-2.31.so during file-backed mapping note processing

warning: exec file is newer than core file.
[New LWP 19633]
[New LWP 19612]
[New LWP 19613]
[New LWP 19614]
[New LWP 19615]
[New LWP 19616]
[New LWP 19617]
[New LWP 19618]
[New LWP 19619]
[New LWP 19622]
[New LWP 19623]
[New LWP 19625]
[New LWP 19626]
[New LWP 19627]
[New LWP 19628]
[New LWP 19629]
[New LWP 19630]
[New LWP 19631]
[New LWP 19632]
[New LWP 19634]
[New LWP 19635]
[New LWP 19636]
[New LWP 19637]
[New LWP 19638]
[New LWP 19639]
[New LWP 19640]
[New LWP 19624]
[New LWP 19642]
[New LWP 19641]

warning: Could not load shared library symbols for 11 libraries, e.g. /lib/libatomic.so.1.
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?
Core was generated by `taosd'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xb6d78070 in ?? ()
[Current thread is 1 (LWP 19633)]

I built the latest release using the GCC compiler provided by buildroot.
I had to remove "-Werror" from cmake.define to compile. I had to add "-latomic" to CFLAGS to be able to build without linker errors.

I also have some questions about the different flags used. For instanced why is "-fPIC" used?
Removing "-fPIC" for testing produces linker errors.

**To Reproduce**
Build taosd for embedded Linux.
Run taosd on Linux with data folder without any files.

**Expected Behavior**
I expect taosd to start up and not segfault.

**Environment (please complete the following information):**
 - OS: Linux built using buildroot.
 - TDengine Version 3.0.4.1

**Additional Context**

I will upload coredump/stack trace.

I tried removing "-fPIC" but I get this when building:

[ 87%] Linking C executable ../../build/bin/tsim
[ 87%] Linking C executable ../../build/bin/demo
[ 87%] Linking C executable ../../../build/bin/tmq_sim
[ 87%] Linking C executable ../../build/bin/asyncdemo
[ 88%] Linking C static library ../../../../build/lib/libmnode.a
[ 88%] Built target mnode
[ 88%] Building C object source/dnode/mgmt/node_util/CMakeFiles/node_util.dir/src/dmEps.c.o
[ 88%] Building C object source/dnode/mgmt/node_util/CMakeFiles/node_util.dir/src/dmFile.c.o
[ 89%] Building C object source/dnode/mgmt/node_util/CMakeFiles/node_util.dir/src/dmUtil.c.o
[ 89%] Linking C static library ../../../../build/lib/libnode_util.a
[ 89%] Built target node_util
[ 89%] Building C object source/dnode/mgmt/mgmt_mnode/CMakeFiles/mgmt_mnode.dir/src/mmFile.c.o
[ 89%] Building C object source/dnode/mgmt/mgmt_dnode/CMakeFiles/mgmt_dnode.dir/src/dmHandle.c.o
[ 89%] Building C object source/dnode/mgmt/mgmt_qnode/CMakeFiles/mgmt_qnode.dir/src/qmHandle.c.o
/home/mwj-ext/remote-git/hp1/buildroot/output/host/opt/ext-toolchain/bin/../lib/gcc/arm-buildroot-linux-gnueabi/10.2.0/../../../../arm-buildroot-linux-gnueabi/bin/ld: ../../build/lib/libos.a(osSemaphore.c.o)(.text+0x40): R_ARM_TLS_LE32 relocation not permitted in shared object
../../build/lib/libos.a(osSemaphore.c.o): in function `taosGetSelfPthreadId':
/home/mwj-ext/remote-git/hp1/buildroot/output/build/tdengine-3.0.4.1/source/os/src/osSemaphore.c:180:(.text+0x40): dangerous relocation: unsupported relocation
/home/mwj-ext/remote-git/hp1/buildroot/output/host/opt/ext-toolchain/bin/../lib/gcc/arm-buildroot-linux-gnueabi/10.2.0/../../../../arm-buildroot-linux-gnueabi/bin/ld: ../../build/lib/libutil.a(terror.c.o)(.text+0x74): R_ARM_TLS_LE32 relocation not permitted in shared object
../../build/lib/libutil.a(terror.c.o): in function `taosGetErrno':
/home/mwj-ext/remote-git/hp1/buildroot/output/build/tdengine-3.0.4.1/source/util/src/terror.c:31:(.text+0x74): dangerous relocation: unsupported relocation
/home/mwj-ext/remote-git/hp1/buildroot/output/host/opt/ext-toolchain/bin/../lib/gcc/arm-buildroot-linux-gnueabi/10.2.0/../../../../arm-buildroot-linux-gnueabi/bin/ld: ../../build/lib/libutil.a(terror.c.o)(.text+0x120): R_ARM_TLS_LE32 relocation not permitted in shared object
../../build/lib/libutil.a(terror.c.o): in function `terrstr':
/home/mwj-ext/remote-git/hp1/buildroot/output/build/tdengine-3.0.4.1/source/util/src/terror.c:696:(.text+0x120): dangerous relocation: unsupported relocation
/home/mwj-ext/remote-git/hp1/buildroot/output/host/opt/ext-toolchain/bin/../lib/gcc/arm-buildroot-linux-gnueabi/10.2.0/../../../../arm-buildroot-linux-gnueabi/bin/ld: ../../build/lib/libnodes.a(nodesUtilFuncs.c.o)(.text+0x2c0): R_ARM_TLS_LE32 relocation not permitted in shared object
../../build/lib/libnodes.a(nodesUtilFuncs.c.o): in function `nodesCalloc':
/home/mwj-ext/remote-git/hp1/buildroot/output/build/tdengine-3.0.4.1/source/libs/nodes/src/nodesUtilFuncs.c:84:(.text+0x2c0): dangerous relocation: unsupported relocation
/home/mwj-ext/remote-git/hp1/buildroot/output/host/opt/ext-toolchain/bin/../lib/gcc/arm-buildroot-linux-gnueabi/10.2.0/../../../../arm-buildroot-linux-gnueabi/bin/ld: ../../build/lib/libnodes.a(nodesUtilFuncs.c.o)(.text+0x4e0): R_ARM_TLS_LE32 relocation not permitted in shared object
../../build/lib/libnodes.a(nodesUtilFuncs.c.o): in function `nodesAcquireAllocator':
/home/mwj-ext/remote-git/hp1/buildroot/output/build/tdengine-3.0.4.1/source/libs/nodes/src/nodesUtilFuncs.c:186:(.text+0x4e0): dangerous relocation: unsupported relocation
/home/mwj-ext/remote-git/hp1/buildroot/output/host/opt/ext-toolchain/bin/../lib/gcc/arm-buildroot-linux-gnueabi/10.2.0/../../../../arm-buildroot-linux-gnueabi/bin/ld: ../../build/lib/libnodes.a(nodesUtilFuncs.c.o)(.text+0x578): R_ARM_TLS_LE32 relocation not permitted in shared object
../../build/lib/libnodes.a(nodesUtilFuncs.c.o): in function `nodesReleaseAllocator':
/home/mwj-ext/remote-git/hp1/buildroot/output/build/tdengine-3.0.4.1/source/libs/nodes/src/nodesUtilFuncs.c:204:(.text+0x578): dangerous relocation: unsupported relocation
[ 89%] Building C object source/dnode/mgmt/mgmt_mnode/CMakeFiles/mgmt_mnode.dir/src/mmHandle.c.o
[ 89%] Building C object source/dnode/mgmt/mgmt_qnode/CMakeFiles/mgmt_qnode.dir/src/qmInt.c.o
collect2: error: ld returned 1 exit status
make[4]: *** [source/client/CMakeFiles/taos.dir/build.make:350: build/lib/libtaos.so.3.0.4.1] Error 1
make[3]: *** [CMakeFiles/Makefile2:2412: source/client/CMakeFiles/taos.dir/all] Error 2
make[3]: *** Waiting for unfinished jobs....

**Comment by sangshuduo** [comment]
TDengine doesn't support cross-compile right now.

**Comment by mwo-ext-airmaster** [comment]
OK.

I wasn't aware that you need to support cross compiling software as such. There should be no difference.

The crash was this BTW:

Thread 3 "mnode-sync" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 14798.14828]
0xb6def07c in memcpy () from /home/mwj-ext/remote-git/hp1/buildroot/output/host/arm-buildroot-linux-gnueabi/sysroot/lib/libc.so.6
(gdb) bt
#0  0xb6def07c in memcpy () from /home/mwj-ext/remote-git/hp1/buildroot/output/host/arm-buildroot-linux-gnueabi/sysroot/lib/libc.so.6
#1  0x001b8d74 in syncEntryBuildFromClientRequest (pMsg=0x245b42b, term=<optimized out>, index=1) at /home/mwj-ext/remote-git/hp1/buildroot/output/build/tdengine-3.0.4.1/source/libs/sync/src/syncRaftEntry.c:46
#2  0x001af67c in syncNodeOnClientRequest (ths=ths@entry=0x2392ac8, pMsg=pMsg@entry=0x245b810, pRetIndex=pRetIndex@entry=0x0) at /home/mwj-ext/remote-git/hp1/buildroot/output/build/tdengine-3.0.4.1/source/libs/sync/src/syncMain.c:2469
#3  0x001b28a8 in syncProcessMsg (rid=<optimized out>, pMsg=pMsg@entry=0x245b810) at /home/mwj-ext/remote-git/hp1/buildroot/output/build/tdengine-3.0.4.1/source/libs/sync/src/syncMain.c:190
#4  0x0002fda0 in mndProcessSyncMsg (pMsg=pMsg@entry=0x245b810) at /home/mwj-ext/remote-git/hp1/buildroot/output/build/tdengine-3.0.4.1/source/dnode/mnode/impl/src/mndMain.c:594
#5  0x0001c62c in mmProcessSyncMsg (pInfo=<optimized out>, pMsg=0x245b810) at /home/mwj-ext/remote-git/hp1/buildroot/output/build/tdengine-3.0.4.1/source/dnode/mgmt/mgmt_mnode/src/mmWorker.c:84
#6  0x002b540c in tQWorkerThreadFp (worker=0x2383ad8) at /home/mwj-ext/remote-git/hp1/buildroot/output/build/tdengine-3.0.4.1/source/util/src/tworker.c:89
#7  0xb6eee434 in start_thread () from /home/mwj-ext/remote-git/hp1/buildroot/output/host/arm-buildroot-linux-gnueabi/sysroot/lib/libpthread.so.0
#8  0xb6e48ec8 in ?? () from /home/mwj-ext/remote-git/hp1/buildroot/output/host/arm-buildroot-linux-gnueabi/sysroot/lib/libc.so.6

**Comment by sangshuduo** [comment]
Close this issue as community edition support x64 and arm64 only. Please contact commercial support for non-official-support architecture.
