### ISSUE TITLE
Got "DB error: No enough memory in dnode"  when create mutiple databases in one dnode,this error cause the end user cannot create number of  db as expected. but 2.X work fine 

### ISSUE THREAD

**Issue by zhonghuali** [taosdata/TDengine#21414]
**Bug Description**
Always got "DB error: No enough memory in dnode"  when create mutiple databases in one dnode

**To Reproduce**
1. install tdengine with latest office docker images by this command:
docker run -d -p 6030:6030 -p 6041:6041 -p 6043-6049:6043-6049 -p 6043-6049:6043-6049/udp --name tdengine3 tdengine/tdengine:latest
2. changed config to support multiple databases in /etc/taos/taos.cfg ,then restart tdengine server
#tdengine 3  /etc/taos/taos.cfg
supportVnodes 1024
4. connect to server,then create many databases with different db name . or used the enclosed file create_dbs.sql
5. after created about 12 dbs , then got error: "DB error: No enough memory in dnode (0.001705s)" . please see error log

**Expected Behavior**
all databases should be created succesfully because the machine have enough memories

**Screenshots**

**Environment (please complete the following information):**
 - OS: Office Docker installation
 - Memory, CPU, current Disk Space
 - TDengine Version [3.0.4.1]

**Additional Context**
Even if I close other application ,then release memory ,the tdengine log still said same available memory , it not changed after release memory.

Are there any workaroud for this issue? where to config the max memory usage in one dnode?

**Comment by zhonghuali** [comment]
create_dbs.sql:
CREATE DATABASE IF NOT EXISTS zw9pblv5b0we_test_devices REPLICA 1    KEEP 18250  COMP 2 PRECISION 'ms'  ;

CREATE TABLE IF NOT EXISTS zw9pblv5b0we_test_devices.`meters`(`ts` timestamp,`current` float,`voltage` int,`phase` float) TAGS(`location` binary(64),`groupid` int);

CREATE DATABASE IF NOT EXISTS zyegqba7kvyh_test_devices REPLICA 1    KEEP 18250  COMP 2 PRECISION 'ms'  ;

CREATE TABLE IF NOT EXISTS zyegqba7kvyh_test_devices.`meters`(`ts` timestamp,`current` float,`voltage` int,`phase` float) TAGS(`location` binary(64),`groupid` int);

CREATE DATABASE IF NOT EXISTS uavj4stbnka1_test_devices REPLICA 1    KEEP 18250  COMP 2 PRECISION 'ms'  ;

CREATE TABLE IF NOT EXISTS uavj4stbnka1_test_devices.`meters`(`ts` timestamp,`current` float,`voltage` int,`phase` float) TAGS(`location` binary(64),`groupid` int);

CREATE DATABASE IF NOT EXISTS brs78kvznwrm_test_devices REPLICA 1    KEEP 18250  COMP 2 PRECISION 'ms'  ;

CREATE TABLE IF NOT EXISTS brs78kvznwrm_test_devices.`meters`(`ts` timestamp,`current` float,`voltage` int,`phase` float) TAGS(`location` binary(64),`groupid` int);

CREATE DATABASE IF NOT EXISTS g4o7dllvuo45_test_devices REPLICA 1    KEEP 18250  COMP 2 PRECISION 'ms'  ;

CREATE TABLE IF NOT EXISTS g4o7dllvuo45_test_devices.`meters`(`ts` timestamp,`current` float,`voltage` int,`phase` float) TAGS(`location` binary(64),`groupid` int);

CREATE DATABASE IF NOT EXISTS zusj3isdlzul_test_devices REPLICA 1    KEEP 18250  COMP 2 PRECISION 'ms'  ;

CREATE TABLE IF NOT EXISTS zusj3isdlzul_test_devices.`meters`(`ts` timestamp,`current` float,`voltage` int,`phase` float) TAGS(`location` binary(64),`groupid` int);

CREATE DATABASE IF NOT EXISTS r3ytwvbcdk3f_test_devices REPLICA 1    KEEP 18250  COMP 2 PRECISION 'ms'  ;

CREATE TABLE IF NOT EXISTS r3ytwvbcdk3f_test_devices.`meters`(`ts` timestamp,`current` float,`voltage` int,`phase` float) TAGS(`location` binary(64),`groupid` int);

CREATE DATABASE IF NOT EXISTS l50growsrh5v_test_devices REPLICA 1    KEEP 18250  COMP 2 PRECISION 'ms'  ;

CREATE TABLE IF NOT EXISTS l50growsrh5v_test_devices.`meters`(`ts` timestamp,`current` float,`voltage` int,`phase` float) TAGS(`location` binary(64),`groupid` int);

CREATE DATABASE IF NOT EXISTS kx8l5uvjs6xi_test_devices REPLICA 1    KEEP 18250  COMP 2 PRECISION 'ms'  ;

CREATE TABLE IF NOT EXISTS kx8l5uvjs6xi_test_devices.`meters`(`ts` timestamp,`current` float,`voltage` int,`phase` float) TAGS(`location` binary(64),`groupid` int);

CREATE DATABASE IF NOT EXISTS yqgvywb3ebqt_test_devices REPLICA 1    KEEP 18250  COMP 2 PRECISION 'ms'  ;

CREATE TABLE IF NOT EXISTS yqgvywb3ebqt_test_devices.`meters`(`ts` timestamp,`current` float,`voltage` int,`phase` float) TAGS(`location` binary(64),`groupid` int);

CREATE DATABASE IF NOT EXISTS zxmizvafsmxo_test_devices REPLICA 1    KEEP 18250  COMP 2 PRECISION 'ms'  ;

CREATE TABLE IF NOT EXISTS zxmizvafsmxo_test_devices.`meters`(`ts` timestamp,`current` float,`voltage` int,`phase` float) TAGS(`location` binary(64),`groupid` int);

CREATE DATABASE IF NOT EXISTS rj7teylss5j8_test_devices REPLICA 1    KEEP 18250  COMP 2 PRECISION 'ms'  ;

CREATE TABLE IF NOT EXISTS rj7teylss5j8_test_devices.`meters`(`ts` timestamp,`current` float,`voltage` int,`phase` float) TAGS(`location` binary(64),`groupid` int);

CREATE DATABASE IF NOT EXISTS fmw0ugc4zbmg_test_devices REPLICA 1    KEEP 18250  COMP 2 PRECISION 'ms'  ;

CREATE TABLE IF NOT EXISTS fmw0ugc4zbmg_test_devices.`meters`(`ts` timestamp,`current` float,`voltage` int,`phase` float) TAGS(`location` binary(64),`groupid` int);

CREATE DATABASE IF NOT EXISTS i5e5tjprvo58_test_devices REPLICA 1    KEEP 18250  COMP 2 PRECISION 'ms'  ;

CREATE TABLE IF NOT EXISTS i5e5tjprvo58_test_devices.`meters`(`ts` timestamp,`current` float,`voltage` int,`phase` float) TAGS(`location` binary(64),`groupid` int);

CREATE DATABASE IF NOT EXISTS idwd2kqvyzdk_test_devices REPLICA 1    KEEP 18250  COMP 2 PRECISION 'ms'  ;

CREATE TABLE IF NOT EXISTS idwd2kqvyzdk_test_devices.`meters`(`ts` timestamp,`current` float,`voltage` int,`phase` float) TAGS(`location` binary(64),`groupid` int);

CREATE DATABASE IF NOT EXISTS zoy1fdiljho0_test_devices REPLICA 1    KEEP 18250  COMP 2 PRECISION 'ms'  ;

CREATE TABLE IF NOT EXISTS zoy1fdiljho0_test_devices.`meters`(`ts` timestamp,`current` float,`voltage` int,`phase` float) TAGS(`location` binary(64),`groupid` int);

CREATE DATABASE IF NOT EXISTS rdc9rhpzuydm_test_devices REPLICA 1    KEEP 18250  COMP 2 PRECISION 'ms'  ;

CREATE TABLE IF NOT EXISTS rdc9rhpzuydm_test_devices.`meters`(`ts` timestamp,`current` float,`voltage` int,`phase` float) TAGS(`location` binary(64),`groupid` int);

CREATE DATABASE IF NOT EXISTS znhj0gtkimnc_test_devices REPLICA 1    KEEP 18250  COMP 2 PRECISION 'ms'  ;

CREATE TABLE IF NOT EXISTS znhj0gtkimnc_test_devices.`meters`(`ts` timestamp,`current` float,`voltage` int,`phase` float) TAGS(`location` binary(64),`groupid` int);

CREATE DATABASE IF NOT EXISTS tju1plk771j1_test_devices REPLICA 1    KEEP 18250  COMP 2 PRECISION 'ms'  ;

CREATE TABLE IF NOT EXISTS tju1plk771j1_test_devices.`meters`(`ts` timestamp,`current` float,`voltage` int,`phase` float) TAGS(`location` binary(64),`groupid` int);

CREATE DATABASE IF NOT EXISTS vtqtaeshqotg_test_devices REPLICA 1    KEEP 18250  COMP 2 PRECISION 'ms'  ;

CREATE TABLE IF NOT EXISTS vtqtaeshqotg_test_devices.`meters`(`ts` timestamp,`current` float,`voltage` int,`phase` float) TAGS(`location` binary(64),`groupid` int);

CREATE DATABASE IF NOT EXISTS aejiwuri02ef_test_devices REPLICA 1    KEEP 18250  COMP 2 PRECISION 'ms'  ;

CREATE TABLE IF NOT EXISTS aejiwuri02ef_test_devices.`meters`(`ts` timestamp,`current` float,`voltage` int,`phase` float) TAGS(`location` binary(64),`groupid` int);

CREATE DATABASE IF NOT EXISTS kttbxacn39to_test_devices REPLICA 1    KEEP 18250  COMP 2 PRECISION 'ms'  ;

CREATE TABLE IF NOT EXISTS kttbxacn39to_test_devices.`meters`(`ts` timestamp,`current` float,`voltage` int,`phase` float) TAGS(`location` binary(64),`groupid` int);

CREATE DATABASE IF NOT EXISTS mf0kt5l901fc_test_devices REPLICA 1    KEEP 18250  COMP 2 PRECISION 'ms'  ;

CREATE TABLE IF NOT EXISTS mf0kt5l901fc_test_devices.`meters`(`ts` timestamp,`current` float,`voltage` int,`phase` float) TAGS(`location` binary(64),`groupid` int);

CREATE DATABASE IF NOT EXISTS iiqdjmud0aiv_test_devices REPLICA 1    KEEP 18250  COMP 2 PRECISION 'ms'  ;

CREATE TABLE IF NOT EXISTS iiqdjmud0aiv_test_devices.`meters`(`ts` timestamp,`current` float,`voltage` int,`phase` float) TAGS(`location` binary(64),`groupid` int);

CREATE DATABASE IF NOT EXISTS z8zcctt9b08t_test_devices REPLICA 1    KEEP 18250  COMP 2 PRECISION 'ms'  ;

CREATE TABLE IF NOT EXISTS z8zcctt9b08t_test_devices.`meters`(`ts` timestamp,`current` float,`voltage` int,`phase` float) TAGS(`location` binary(64),`groupid` int);

**Comment by sangshuduo** [comment]
don't create too many database if you don't have enough memory

**Comment by zhonghuali** [comment]
I'm sure my machine have enough memory.  
more questions:
1.I just created many empty db, why the memory are used so many. it doesn't make sense.
2.I think you can easy to reproduce this issue in your laptop, is this issue only accur in docker . I guest the tdengine don't get right whole memory size  in docker vm. right?
3. Can I manully config the max memory size?
thanks

**Comment by zhonghuali** [comment]
In docker installation, the error said: 
05/22 07:39:06.538073 00000079 MND db:1.fmw0ugc4zbmg_test_devices, vgId:28, vn:0 is alloced, memory:269484032, dnode:1 avail:7493061018 used:7276068864
05/22 07:39:06.538081 00000079 MND ERROR db:1.fmw0ugc4zbmg_test_devices, vgId:29, no enough memory:269484032 in dnode:1, avail:7493061018 used:7276068864

the available memory is : dnode:1 avail:7493061018,about 749M memory, but actually my machine vm have about 7G available memory.

and I tested this case in bare linux machine, even thought I can create about 25 dbs, but the available memory in log is not right.  here is logs in bare machine:
05/23 10:11:26.227940 00757761 MND db:1.iiqdjmud0aiv_test_devices, start to create, vgroups:2
05/23 10:11:26.228193 00757761 MND dnode:1, vnodes:46 supportVnodes:1024 isMnode:1 online:1 memory avail:14837884928 used:12396265472
05/23 10:11:26.228220 00757761 MND db:1.iiqdjmud0aiv_test_devices, total 1 dnodes used to create 2 vgroups (2 vnodes)
05/23 10:11:26.228298 00757761 MND db:1.iiqdjmud0aiv_test_devices, vgId:48, vn:0 is alloced, memory:269484032, dnode:1 avail:14837884928 used:12665749504
05/23 10:11:26.228309 00757761 MND db:1.iiqdjmud0aiv_test_devices, vgId:49, vn:0 is alloced, memory:269484032, dnode:1 avail:14837884928 used:12935233536
......
10:11:26.451250 00757761 MND dnode:1, vnodes:48 supportVnodes:1024 isMnode:1 online:1 memory avail:14837884928 used:12935233536
05/23 10:11:26.451258 00757761 MND db:1.z8zcctt9b08t_test_devices, total 1 dnodes used to create 2 vgroups (2 vnodes)
05/23 10:11:26.451273 00757761 MND db:1.z8zcctt9b08t_test_devices, vgId:50, vn:0 is alloced, memory:269484032, dnode:1 avail:14837884928 used:13204717568
05/23 10:11:26.451276 00757761 MND db:1.z8zcctt9b08t_test_devices, vgId:51, vn:0 is alloced, memory:269484032, dnode:1 avail:14837884928 used:13474201600
05/23 10:11:26.451278 00757761 MND db:1.z8zcctt9b08t_test_devices, total 2 vgroups is alloced, replica:1

the machine memory with free command: 
v-znpd-dev-172 taos]$ free -h
               total        used        free      shared  buff/cache   available
Mem:            15Gi       7.9Gi       2.2Gi       375Mi       6.0Gi       7.5Gi
Swap:             0B          0B          0B

there two issue:
1. tdengine log said : "dnode:1 avail:14837884928 used:13204717568",  available memory is 14837884928 ,about 1.4G, but actually memory available is 7.5G as free command displaied.
2. in above logs, after first and second db created, the availalbe memory value: avail:14837884928  is not reduced.  it might be a wrong caculated available memory.

Thanks

**Comment by sangshuduo** [comment]
https://stackoverflow.com/questions/72185669/what-is-the-real-memory-available-in-docker-container

**Comment by zhonghuali** [comment]
Thanks your reply,

but I tested it in bare machine, Without in a docker, please see my commets.  I pasted here again.
---------------
and I tested this case in bare linux machine, even thought I can create about 25 dbs, but the available memory in log is not right. here is logs in bare machine:
05/23 10:11:26.227940 00757761 MND db:1.iiqdjmud0aiv_test_devices, start to create, vgroups:2
05/23 10:11:26.228193 00757761 MND dnode:1, vnodes:46 supportVnodes:1024 isMnode:1 online:1 memory avail:14837884928 used:12396265472
05/23 10:11:26.228220 00757761 MND db:1.iiqdjmud0aiv_test_devices, total 1 dnodes used to create 2 vgroups (2 vnodes)
05/23 10:11:26.228298 00757761 MND db:1.iiqdjmud0aiv_test_devices, vgId:48, vn:0 is alloced, memory:269484032, dnode:1 avail:14837884928 used:12665749504
05/23 10:11:26.228309 00757761 MND db:1.iiqdjmud0aiv_test_devices, vgId:49, vn:0 is alloced, memory:269484032, dnode:1 avail:14837884928 used:12935233536
......
10:11:26.451250 00757761 MND dnode:1, vnodes:48 supportVnodes:1024 isMnode:1 online:1 memory avail:14837884928 used:12935233536
05/23 10:11:26.451258 00757761 MND db:1.z8zcctt9b08t_test_devices, total 1 dnodes used to create 2 vgroups (2 vnodes)
05/23 10:11:26.451273 00757761 MND db:1.z8zcctt9b08t_test_devices, vgId:50, vn:0 is alloced, memory:269484032, dnode:1 avail:14837884928 used:13204717568
05/23 10:11:26.451276 00757761 MND db:1.z8zcctt9b08t_test_devices, vgId:51, vn:0 is alloced, memory:269484032, dnode:1 avail:14837884928 used:13474201600
05/23 10:11:26.451278 00757761 MND db:1.z8zcctt9b08t_test_devices, total 2 vgroups is alloced, replica:1

the machine memory with free command:
v-znpd-dev-172 taos]$ free -h
total used free shared buff/cache available
Mem: 15Gi 7.9Gi 2.2Gi 375Mi 6.0Gi 7.5Gi
Swap: 0B 0B 0B

there two issue:

tdengine log said : "dnode:1 avail:14837884928 used:13204717568", available memory is 14837884928 ,about 1.4G, but actually memory available is 7.5G as free command displaied.
in above logs, after first and second db created, the availalbe memory value: avail:14837884928 is not reduced,actually it's not changed after created all dbs. it might be a wrong caculated available memory.

**Comment by zhonghuali** [comment]
According to logs, the total availbe memory value is not reduced when keeping in creating db until the used memory is reached total available memory value,then got the no memory error.  I guess beacause the TDengine first to get available memory is part of all machine like 1/4, not dynamicly to acquire memory. so it easly to get no enough memory error.

**Comment by sangshuduo** [comment]
> According to logs, the total availbe memory value is not reduced when keeping in creating db until the used memory is reached total available memory value,then got the no memory error. I guess beacause the TDengine first to get available memory is part of all machine like 1/4, not dynamicly to acquire memory. so it easly to get no enough memory error.

I think it's a designed behavior.

**Comment by zhonghuali** [comment]
Hello, thanks for your reply. 
I undertood it's as designed behavior from yourdesign like dnode design. but my original concern is that can't create expected number of databases due to this errors.  
there are another simiar issue like https://github.com/taosdata/TDengine/issues/17372, as feedback ,TDengine doesn't have limiation to create mulitple databases. but in fact, because this errors,the end users cannot create number of db as thier expected. so most of end user are confused with this behavior.  
According to user guider, the supportVnode should match number of CPU, or can set bigger value.   I think  all of databases are not able to completely share same vnode in current design .  
For user experience , I realy hope this behavior can be improved ,and be able to create expected databases as TDengine 2.X done.

**Comment by sangshuduo** [comment]
Please keep in mind, use supportVnode to increase the allowed number for db creation for the development phase only rather than the best practice for the production environment. 

I recommend using multiple super tables instead of various databases to support different schema needs.

**Comment by zhonghuali** [comment]
Thanks your reply,
Using mulitple super tables is not good way in my scenario, cannot accept this workaround.

And I understood the supportVnode usage, but a little sad about it cannot be used to multiple databases in production.  let's forget the supportVnode ,and go back the original questions.
"Have the TDengine3 a limitation to create multiple databases?" or "Can the TDengine3 create multiple databases?"
so the answer is negative. although allow to create a few databases. 
I think it's best way to add this limitation into our documents.

**Comment by sangshuduo** [comment]
To use limited number of vgroup is on-purpose redesign. Each improvement has its cost. The FAQ section of the official document already explain it. Please refer to https://docs.taosdata.com/train-faq/faq/#20-%E5%BB%BA%E5%BA%93%E6%97%B6%E6%8F%90%E7%A4%BA-out-of-dnodes.
