### ISSUE TITLE
Once time , multiple 'Insert into' SQL with Rest API , uncertain error happen . 

### ISSUE THREAD

**Issue by sytpb** [taosdata/TDengine#2142]
![image](https://user-images.githubusercontent.com/12178686/83832214-b0c6de00-a71b-11ea-8705-a7f1bfd56203.png)

using Super table to create sub-table with 'Insert into' 

the uncertain error show as below , 
![image](https://user-images.githubusercontent.com/12178686/83832420-36e32480-a71c-11ea-8dad-6bbc8067d6ba.png)

and then I copy the SQL to command window to run , got ok  with it . 

![image](https://user-images.githubusercontent.com/12178686/83832669-c7ba0000-a71c-11ea-847e-220d7201c1f2.png)

another error case as below , 
![image](https://user-images.githubusercontent.com/12178686/83833885-93940e80-a71f-11ea-833d-d92193f462ce.png)

－－－－－－－－－－－－－－－－－－－－
additional i found a important point , 

the super table in two DB,   test result show me from now,    one DB's 'insert into' success, so another is wrong .   once only one DB's insert into is ok .

**Comment by Aries-Lee1991** [comment]
Please upload the logs

**Comment by sytpb** [comment]
> Please upload the logs
how to got it ?

**Comment by sytpb** [comment]
[Desktop.zip](https://github.com/taosdata/TDengine/files/4734157/Desktop.zip)

**Comment by sytpb** [comment]
![image](https://user-images.githubusercontent.com/12178686/83842038-ae24b280-a734-11ea-8905-e52f190a2673.png)

**Comment by Aries-Lee1991** [comment]
OK, we'll check it.

**Comment by liu0x54** [comment]
In which db are you creating tables?
the dot int the table name has its special meaning, TDengine SQL will parse it and take the left part as db name, the right part as the table name. so the xtoken.xxx may be parsed as table name xxx in the database xtoken.
Please check your database and table name, use the dot carefully or replace it with '_' to concat two part.

**Comment by sytpb** [comment]
yes ,    xtoken is my db ,  xxx is my table will create by this SQL .

**Comment by liu0x54** [comment]
Seems there is drop table cmd before the insert cmd? You can set the debugFlag to 135 in the /etc/taos/taos.cfg, and re-run the test, and upload the logs. It's better to delete logs before you run the test.

**Comment by plum-lihui** [comment]
We have released the v2.0 version of tdengine, please use the latest version to verify. thank you very much!
