### ISSUE TITLE
taos服务起不来了，启动时报 “Error in `taosd': malloc(): memory corruption: 0x00007fc6dc193740”。是什么问题，如何解决。

### ISSUE THREAD

**Issue by gubaoya123456** [taosdata/TDengine#21428]
[root]# taosd
05/23 11:21:17.559673 00009563 DND start to initialize TDengine
05/23 11:21:17.559791 00009563 DND step:dnode-tfile is initialized
05/23 11:21:17.559805 00009563 DND step:dnode-rpc is initialized
05/23 11:21:17.560124 00009563 UTL localEp is: hnjjtqlxty123.novalocal:6030
05/23 11:21:17.560540 00009563 UTL WARN timezone not configured, set to system default: (CST, +0800)
05/23 11:21:17.560620 00009563 UTL WARN locale not configured, set to system default:zh_CN.UTF-8
05/23 11:21:17.560632 00009563 UTL WARN charset not configured, set to system default:UTF-8
05/23 11:21:17.560678 00009563 UTL    check global cfg completed
05/23 11:21:17.560684 00009563 UTL ==================================
05/23 11:21:17.560690 00009563 UTL    taos config & system info:
05/23 11:21:17.560695 00009563 UTL ==================================
05/23 11:21:17.560702 00009563 UTL  firstEp:                hnjjtqlxty123.novalocal:6030 
05/23 11:21:17.560708 00009563 UTL  secondEp:               hnjjtqlxty123.novalocal:6030 
05/23 11:21:17.560725 00009563 UTL  fqdn:                   hnjjtqlxty123.novalocal 
05/23 11:21:17.560731 00009563 UTL  serverPort:             6030 
05/23 11:21:17.560737 00009563 UTL  configDir:              /etc/taos 
05/23 11:21:17.560743 00009563 UTL  logDir:                 /var/log/taos 
05/23 11:21:17.560748 00009563 UTL  scriptDir:              /etc/taos 
05/23 11:21:17.560753 00009563 UTL  arbitrator:              
05/23 11:21:17.560760 00009563 UTL  numOfThreadsPerCore:    1.000000 
05/23 11:21:17.560778 00009563 UTL  numOfCommitThreads:     4 
05/23 11:21:17.560784 00009563 UTL  ratioOfQueryCores:      1.000000 
05/23 11:21:17.560790 00009563 UTL  maxNumOfDistinctRes:    10000000 
05/23 11:21:17.560795 00009563 UTL  numOfMnodes:            1 
05/23 11:21:17.560800 00009563 UTL  vnodeBak:               1 
05/23 11:21:17.560806 00009563 UTL  telemetryReporting:     1 
05/23 11:21:17.560811 00009563 UTL  dnodeNopLoop:           0 
05/23 11:21:17.560816 00009563 UTL  tcpConnTimout:          1000(ms)
05/23 11:21:17.560822 00009563 UTL  syncCheckInterval:      1500(ms)
05/23 11:21:17.560828 00009563 UTL  balance:                1 
05/23 11:21:17.560833 00009563 UTL  balanceInterval:        300 
05/23 11:21:17.560839 00009563 UTL  offlineInterval:        3 
05/23 11:21:17.560844 00009563 UTL  keepTimeOffset:         0 
05/23 11:21:17.560850 00009563 UTL  role:                   0 
05/23 11:21:17.560864 00009563 UTL  maxTmrCtrl:             512 
05/23 11:21:17.560870 00009563 UTL  monitorInterval:        30(s)
05/23 11:21:17.560875 00009563 UTL  monitorReplica:         1 
05/23 11:21:17.560880 00009563 UTL  offlineThreshold:       864000(s)
05/23 11:21:17.560890 00009563 UTL  rpcTimer:               300(ms)
05/23 11:21:17.560896 00009563 UTL  rpcMaxTime:             600(s)
05/23 11:21:17.560901 00009563 UTL  rpcForceTcp:            0 
05/23 11:21:17.560907 00009563 UTL  statusInterval:         1(s)
05/23 11:21:17.560912 00009563 UTL  shellActivityTimer:     3(s)
05/23 11:21:17.560918 00009563 UTL  minSlidingTime:         10(ms)
05/23 11:21:17.560924 00009563 UTL  minIntervalTime:        1(ms)
05/23 11:21:17.560929 00009563 UTL  maxStreamCompDelay:     20000(ms)
05/23 11:21:17.560934 00009563 UTL  maxFirstStreamCompDelay:10000(ms)
05/23 11:21:17.560940 00009563 UTL  retryStreamCompDelay:   1800000(ms)
05/23 11:21:17.560946 00009563 UTL  streamCompDelayRatio:   0.100000 
05/23 11:21:17.560953 00009563 UTL  maxVgroupsPerDb:        0 
05/23 11:21:17.560958 00009563 UTL  maxTablesPerVnode:      1000000 
05/23 11:21:17.560964 00009563 UTL  minTablesPerVnode:      1000 
05/23 11:21:17.560969 00009563 UTL  tableIncStepPerVnode:   1000 
05/23 11:21:17.560982 00009563 UTL  cache:                  16(Mb)
05/23 11:21:17.560987 00009563 UTL  blocks:                 6 
05/23 11:21:17.560992 00009563 UTL  days:                   10 
05/23 11:21:17.561005 00009563 UTL  keep:                   3650 
05/23 11:21:17.561010 00009563 UTL  minRows:                100 
05/23 11:21:17.561015 00009563 UTL  maxRows:                4096 
05/23 11:21:17.561025 00009563 UTL  precision:              0 
05/23 11:21:17.561030 00009563 UTL  comp:                   2 
05/23 11:21:17.561035 00009563 UTL  walLevel:               1 
05/23 11:21:17.561041 00009563 UTL  fsync:                  3000 
05/23 11:21:17.561046 00009563 UTL  replica:                1 
05/23 11:21:17.561052 00009563 UTL  partitions:             4 
05/23 11:21:17.561057 00009563 UTL  quorum:                 1 
05/23 11:21:17.561063 00009563 UTL  update:                 0 
05/23 11:21:17.561068 00009563 UTL  cachelast:              0 
05/23 11:21:17.561073 00009563 UTL  compressMsgSize:        524288 
05/23 11:21:17.561084 00009563 UTL  compressColData:        -1 
05/23 11:21:17.561090 00009563 UTL  maxSQLLength:           1048576(byte)
05/23 11:21:17.561095 00009563 UTL  maxWildCardsLength:     100(byte)
05/23 11:21:17.561100 00009563 UTL  maxRegexStringLen:      128(byte)
05/23 11:21:17.561106 00009563 UTL  maxNumOfOrderedRes:     1000000 
05/23 11:21:17.561114 00009563 UTL  queryBufferSize:        -1(byte)
05/23 11:21:17.561119 00009563 UTL  retrieveBlockingModel:  0 
05/23 11:21:17.561125 00009563 UTL  keepColumnName:         1 
05/23 11:21:17.561130 00009563 UTL  timezone:                (CST, +0800) 
05/23 11:21:17.561136 00009563 UTL  locale:                 zh_CN.UTF-8 
05/23 11:21:17.561141 00009563 UTL  charset:                UTF-8 
05/23 11:21:17.561146 00009563 UTL  maxShellConns:          50000 
05/23 11:21:17.561152 00009563 UTL  maxConnections:         5000 
05/23 11:21:17.561157 00009563 UTL  minimalLogDirGB:        1.000000(GB)
05/23 11:21:17.561163 00009563 UTL  minimalTmpDirGB:        1.000000(GB)
05/23 11:21:17.561169 00009563 UTL  minimalDataDirGB:       2.000000(GB)
05/23 11:21:17.561175 00009563 UTL  mnodeEqualVnodeNum:     4 
05/23 11:21:17.561181 00009563 UTL  flowctrl:               1 
05/23 11:21:17.561187 00009563 UTL  slaveQuery:             1 
05/23 11:21:17.561192 00009563 UTL  adjustMaster:           1 
05/23 11:21:17.561197 00009563 UTL  http:                   1 
05/23 11:21:17.561202 00009563 UTL  monitor:                1 
05/23 11:21:17.561208 00009563 UTL  stream:                 1 
05/23 11:21:17.561213 00009563 UTL  topicBinaryLen:         16000 
05/23 11:21:17.561218 00009563 UTL  httpEnableRecordSql:    0 
05/23 11:21:17.561249 00009563 UTL  telegrafUseFieldNum:    0 
05/23 11:21:17.561256 00009563 UTL  httpMaxThreads:         4 
05/23 11:21:17.561261 00009563 UTL  restfulRowLimit:        10240 
05/23 11:21:17.561267 00009563 UTL  httpDbNameMandatory:    0 
05/23 11:21:17.561272 00009563 UTL  httpKeepAlive:          30000 
05/23 11:21:17.561277 00009563 UTL  numOfLogLines:          10000000 
05/23 11:21:17.561282 00009563 UTL  logKeepDays:            0 
05/23 11:21:17.561288 00009563 UTL  asyncLog:               1 
05/23 11:21:17.561293 00009563 UTL  debugFlag:              0 
05/23 11:21:17.561298 00009563 UTL  mDebugFlag:             131 
05/23 11:21:17.561304 00009563 UTL  dDebugFlag:             135 
05/23 11:21:17.561309 00009563 UTL  sDebugFlag:             135 
05/23 11:21:17.561314 00009563 UTL  wDebugFlag:             135 
05/23 11:21:17.561319 00009563 UTL  sdbDebugFlag:           131 
05/23 11:21:17.561324 00009563 UTL  rpcDebugFlag:           131 
05/23 11:21:17.561330 00009563 UTL  tmrDebugFlag:           131 
05/23 11:21:17.561335 00009563 UTL  cDebugFlag:             131 
05/23 11:21:17.561340 00009563 UTL  jniDebugFlag:           131 
05/23 11:21:17.561346 00009563 UTL  odbcDebugFlag:          131 
05/23 11:21:17.561366 00009563 UTL  uDebugFlag:             131 
05/23 11:21:17.561371 00009563 UTL  httpDebugFlag:          131 
05/23 11:21:17.561377 00009563 UTL  monDebugFlag:           131 
05/23 11:21:17.561382 00009563 UTL  qDebugFlag:             131 
05/23 11:21:17.561387 00009563 UTL  vDebugFlag:             135 
05/23 11:21:17.561392 00009563 UTL  tsdbDebugFlag:          131 
05/23 11:21:17.561397 00009563 UTL  cqDebugFlag:            131 
05/23 11:21:17.561403 00009563 UTL  enableRecordSql:        0 
05/23 11:21:17.561408 00009563 UTL  enableCoreFile:         0 
05/23 11:21:17.561417 00009563 UTL  gitinfo:                c4d6c3a24a0051acda88a56df515e5b18a10d6e1 
05/23 11:21:17.561422 00009563 UTL  gitinfoOfInternal:      NULL 
05/23 11:21:17.561428 00009563 UTL  buildinfo:              Built at 2022-05-31 11:33 
05/23 11:21:17.561433 00009563 UTL  version:                2.6.0.1 
05/23 11:21:17.561438 00009563 UTL  maxBinaryDisplayWidth:  30 
05/23 11:21:17.561444 00009563 UTL  tempDir:                /tmp/ 
05/23 11:21:17.561449 00009563 UTL  tsdbMetaCompactRatio:   0 
05/23 11:21:17.561455 00009563 UTL  deadLockKillQuery:      1 
05/23 11:21:17.561460 00009563 UTL  clientMerge:            0 
05/23 11:21:17.561465 00009563 UTL  defaultJSONStrType:     nchar 
05/23 11:21:17.561471 00009563 UTL  smlChildTableName:       
05/23 11:21:17.561476 00009563 UTL  smlTagNullName:         _tag_null 
05/23 11:21:17.561481 00009563 UTL  walFlushSize:           1024(Mb)
05/23 11:21:17.561486 00009563 UTL  shortcutFlag:           0 
05/23 11:21:17.561494 00009563 UTL  lossyColumns:            
05/23 11:21:17.561500 00009563 UTL  fPrecision:             0.000000 
05/23 11:21:17.561506 00009563 UTL  dPrecision:             0.000000 
05/23 11:21:17.561511 00009563 UTL  maxRange:               500 
05/23 11:21:17.561517 00009563 UTL  range:                  100 
05/23 11:21:17.561523 00009563 UTL  os pageSize:            4096(KB)
05/23 11:21:17.561536 00009563 UTL  os openMax:             1024
05/23 11:21:17.561541 00009563 UTL  os streamMax:           16
05/23 11:21:17.561546 00009563 UTL  os numOfCores:          8
05/23 11:21:17.561551 00009563 UTL  os totalMemory:         32002(MB)
05/23 11:21:17.561559 00009563 UTL  os sysname:             Linux
05/23 11:21:17.561564 00009563 UTL  os nodename:            hnjjtqlxty123.novalocal
05/23 11:21:17.561569 00009563 UTL  os release:             3.10.0-1160.66.1.el7.x86_64
05/23 11:21:17.561574 00009563 UTL  os version:             #1 SMP Wed May 18 16:02:34 UTC 2022
05/23 11:21:17.561580 00009563 UTL  os machine:             x86_64
05/23 11:21:17.561586 00009563 UTL  dataDir: /var/lib/taos
05/23 11:21:17.561591 00009563 UTL ==================================
05/23 11:21:17.561733 00009563 DND step:dnode-globalcfg is initialized
05/23 11:21:17.561804 00009563 TFS disk /var/lib/taos is mounted to tier level 0 id 0
05/23 11:21:17.561912 00009563 UTL ==================================
05/23 11:21:17.561920 00009563 UTL  os totalDisk:           45.488522(GB)
05/23 11:21:17.561926 00009563 UTL  os usedDisk:            24.063015(GB)
05/23 11:21:17.561932 00009563 UTL  os availDisk:           21.425507(GB)
05/23 11:21:17.561939 00009563 UTL ==================================
05/23 11:21:17.561944 00009563 DND dnode storage is initialized at /var/lib/taos/dnode
05/23 11:21:17.561949 00009563 DND step:dnode-storage is initialized
05/23 11:21:17.562037 00009563 DND read file /var/lib/taos/dnode/dnodeCfg.json successed
05/23 11:21:17.562055 00009563 DND dnodeId is set to 1, clusterId is set to 50b4d6f8-1ae3-47bf-9cb4-b99388f76487
05/23 11:21:17.563972 00009563 DND successed to write /var/lib/taos/dnode/dnodeCfg.json
05/23 11:21:17.563987 00009563 DND dnode cfg is initialized
05/23 11:21:17.563992 00009563 DND step:dnode-cfg is initialized
05/23 11:21:17.564059 00009563 DND read file /var/lib/taos/dnode/dnodeEps.json successed
05/23 11:21:17.564093 00009563 DND dnode eps is initialized
05/23 11:21:17.564099 00009563 DND step:dnode-eps is initialized
05/23 11:21:17.564142 00009563 DND read file /var/lib/taos/dnode/mnodeEpSet.json successed
05/23 11:21:17.564148 00009563 DND print minfos, mnodeNum:1 inUse:0
05/23 11:21:17.564154 00009563 DND mnode index:1, hnjjtqlxty123.novalocal:6030
05/23 11:21:17.564176 00009563 DND print minfos, mnodeNum:1 inUse:0
05/23 11:21:17.564186 00009563 DND mnode index:1, hnjjtqlxty123.novalocal:6030
05/23 11:21:17.564191 00009563 DND dnode minfos is initialized
05/23 11:21:17.564196 00009563 DND step:dnode-minfos is initialized
05/23 11:21:17.564263 00009563 WAL wal module is initialized, rsetId:3
05/23 11:21:17.564269 00009563 DND step:dnode-wal is initialized
05/23 11:21:17.564399 00009563 DND step:dnode-sync is initialized
05/23 11:21:17.564493 00009563 DND dnode check is initialized
05/23 11:21:17.564503 00009563 DND step:dnode-check is initialized
05/23 11:21:17.564518 00009563 UTL worker:vquery is initialized, min:8 max:8
05/23 11:21:17.564539 00009563 UTL worker:vfetch is initialized, min:4 max:4
05/23 11:21:17.564545 00009563 DND step:dnode-vread is initialized
05/23 11:21:17.564554 00009563 DND dnode vwrite is initialized, max worker 8
05/23 11:21:17.564559 00009563 DND step:dnode-vwrite is initialized
05/23 11:21:17.564630 00009563 DND step:vnode-backup is initialized
05/23 11:21:17.564681 00009563 DND step:vnode-worker is initialized
05/23 11:21:17.564695 00009563 DND step:vnode-write is initialized
05/23 11:21:17.564709 00009563 DND step:vnode-read is initialized
05/23 11:21:17.564716 00009563 DND step:vnode-hash is initialized
05/23 11:21:17.564842 00009563 DND step:tsdb-queue is initialized
05/23 11:21:17.564853 00009563 UTL worker:vmgmt is initialized, min:1 max:1
05/23 11:21:17.564886 00009563 DND dnode vmgmt is initialized
05/23 11:21:17.564892 00009563 DND step:dnode-vmgmt is initialized
05/23 11:21:17.564911 00009563 DND step:dnode-mread is initialized
05/23 11:21:17.564920 00009563 DND step:dnode-mwrite is initialized
05/23 11:21:17.564928 00009563 DND step:dnode-mpeer is initialized
05/23 11:21:17.568063 00009563 DND dnode inter-dnodes rpc client is initialized
05/23 11:21:17.568084 00009563 DND step:dnode-client is initialized
05/23 11:21:17.568880 00009563 DND dnode inter-dnodes RPC server is initialized
05/23 11:21:17.568890 00009563 DND step:dnode-server is initialized
05/23 11:21:17.568935 00009563 DND start 8 threads to open 3 vnodes
05/23 11:21:17.569312 00009583 VND vgId:12, load vnode cfg successfully, replcia:1
05/23 11:21:17.569372 00009583 VND vgId:12, dnode:1, hnjjtqlxty123.novalocal:6040
05/23 11:21:17.569336 00009581 VND vgId:2, load vnode cfg successfully, replcia:1
05/23 11:21:17.569375 00009582 VND vgId:5, load vnode cfg successfully, replcia:1
05/23 11:21:17.569397 00009581 VND vgId:2, dnode:1, hnjjtqlxty123.novalocal:6040
05/23 11:21:17.569401 00009582 VND vgId:5, dnode:1, hnjjtqlxty123.novalocal:6040
05/23 11:21:17.569417 00009583 VND vgId:12, read /var/lib/taos/vnode/vnode12/version.json successfully, fver:734725
05/23 11:21:17.569437 00009581 VND vgId:2, read /var/lib/taos/vnode/vnode2/version.json successfully, fver:6649161
05/23 11:21:17.569471 00009582 VND vgId:5, read /var/lib/taos/vnode/vnode5/version.json successfully, fver:496
05/23 11:21:17.576306 00009582 WAL vgId:5, file:/var/lib/taos/vnode/vnode5/wal/wal1, will be restored
05/23 11:21:17.576399 00009582 WAL vgId:5, file:/var/lib/taos/vnode/vnode5/wal/wal1, restore success, wver:0
05/23 11:21:17.576484 00009582 WAL vgId:5, wal:0x7fc6dc029620 file:/var/lib/taos/vnode/vnode5/wal/wal1, it is removed
05/23 11:21:17.576623 00009583 TDB vgId:12 file /var/lib/taos/vnode/vnode12/tsdb/data/v12f1949.data-ver5 is truncated from 2756087 to 1039092
05/23 11:21:17.576675 00009582 VND vgId:5, sync role changed from offline to master
05/23 11:21:17.576695 00009583 TDB vgId:12 file /var/lib/taos/vnode/vnode12/tsdb/data/v12f1949.smad-ver5 is truncated from 12616 to 5140
05/23 11:21:17.577374 00009583 WAL vgId:12, file:/var/lib/taos/vnode/vnode12/wal/wal7, will be restored
05/23 11:21:17.578584 00009581 WAL vgId:2, file:/var/lib/taos/vnode/vnode2/wal/wal1, will be restored
05/23 11:21:17.578626 00009581 WAL vgId:2, file:/var/lib/taos/vnode/vnode2/wal/wal1, restore success, wver:0
05/23 11:21:17.578687 00009581 WAL vgId:2, wal:0x7fc6e40547f0 file:/var/lib/taos/vnode/vnode2/wal/wal1, it is removed
05/23 11:21:17.578967 00009581 VND vgId:2, sync role changed from offline to master
05/23 11:21:17.961739 00009583 VND vgId:12, start commit, fver:734725 vver:832448
05/23 11:21:17.961817 00009583 WAL vgId:12, file:/var/lib/taos/vnode/vnode12/wal/wal7, restore success, wver:832448
05/23 11:21:17.961847 00009583 WAL vgId:12, file:/var/lib/taos/vnode/vnode12/wal/wal8, will be restored
05/23 11:21:17.961872 00009583 WAL vgId:12, file:/var/lib/taos/vnode/vnode12/wal/wal8, restore success, wver:832448
05/23 11:21:17.961851 00009571 TDB vgId:12 start to commit! keyFirst 1684144972000 keyLast 1684641624000 numOfRows 97722 meta rows: 0
*** Error in `taosd': malloc(): memory corruption: 0x00007fc6dc193740 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x82b36)[0x7fc70020cb36]
/lib64/libc.so.6(+0x83d72)[0x7fc70020dd72]
/lib64/libc.so.6(realloc+0x1d2)[0x7fc70020fe12]
/lib/libtaos.so.1(taosTRealloc+0x68)[0x7fc700ebc457]
/lib/libtaos.so.1(tsdbWriteBlockImpl+0x996)[0x7fc700ead8a2]
/lib/libtaos.so.1(+0x230779)[0x7fc700eae779]
/lib/libtaos.so.1(+0x230a15)[0x7fc700eaea15]
/lib/libtaos.so.1(+0x22ea68)[0x7fc700eaca68]
/lib/libtaos.so.1(+0x22d833)[0x7fc700eab833]
/lib/libtaos.so.1(+0x22d460)[0x7fc700eab460]
/lib/libtaos.so.1(tsdbCommitData+0xe3)[0x7fc700ea70b5]
/lib/libtaos.so.1(+0x21b104)[0x7fc700e99104]
/lib64/libpthread.so.0(+0x7ea5)[0x7fc70055fea5]
/lib64/libc.so.6(clone+0x6d)[0x7fc700288b0d]
======= Memory map: ========
55840d62a000-55840d6cb000 r-xp 00000000 fd:03 111441884                  /usr/local/taos/bin/taosd
55840d8ca000-55840d8cc000 r--p 000a0000 fd:03 111441884                  /usr/local/taos/bin/taosd
55840d8cc000-55840d8cd000 rw-p 000a2000 fd:03 111441884                  /usr/local/taos/bin/taosd
55840d8cd000-55840d8d3000 rw-p 00000000 00:00 0 
55840dcf8000-55840dd84000 rw-p 00000000 00:00 0                          [heap]
7fc6c4000000-7fc6c4021000 rw-p 00000000 00:00 0 
7fc6c4021000-7fc6c8000000 ---p 00000000 00:00 0 
7fc6cadd1000-7fc6cade6000 r-xp 00000000 fd:03 28996                      /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fc6cade6000-7fc6cafe5000 ---p 00015000 fd:03 28996                      /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fc6cafe5000-7fc6cafe6000 r--p 00014000 fd:03 28996                      /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fc6cafe6000-7fc6cafe7000 rw-p 00015000 fd:03 28996                      /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fc6cafe7000-7fc6cafe8000 ---p 00000000 00:00 0 
7fc6cafe8000-7fc6d47f1000 rw-p 00000000 00:00 0 
7fc6d47f1000-7fc6d47f2000 ---p 00000000 00:00 0 
7fc6d47f2000-7fc6d4ff2000 rw-p 00000000 00:00 0 
7fc6d4ff2000-7fc6d4ff3000 ---p 00000000 00:00 0 
7fc6d4ff3000-7fc6d57f3000 rw-p 00000000 00:00 0 
7fc6d57f3000-7fc6d57f4000 ---p 00000000 00:00 0 
7fc6d57f4000-7fc6d5ff4000 rw-p 00000000 00:00 0 
7fc6d5ff4000-7fc6d5ff5000 ---p 00000000 00:00 0 
7fc6d5ff5000-7fc6d67f5000 rw-p 00000000 00:00 0 
7fc6d67f5000-7fc6d67f6000 ---p 00000000 00:00 0 
7fc6d67f6000-7fc6d6ff6000 rw-p 00000000 00:00 0 
7fc6d6ff6000-7fc6d6ff7000 ---p 00000000 00:00 0 
7fc6d6ff7000-7fc6d77f7000 rw-p 00000000 00:00 0 
7fc6d77f7000-7fc6d77f8000 ---p 00000000 00:00 0 
7fc6d77f8000-7fc6d7ff8000 rw-p 00000000 00:00 0 
7fc6d7ff8000-7fc6d7ff9000 ---p 00000000 00:00 0 
7fc6d7ff9000-7fc6d87f9000 rw-p 00000000 00:00 0 
7fc6d87f9000-7fc6d87fa000 ---p 00000000 00:00 0 
7fc6d87fa000-7fc6d8ffa000 rw-p 00000000 00:00 0 
7fc6d8ffa000-7fc6d8ffb000 ---p 00000000 00:00 0 
7fc6d8ffb000-7fc6d97fb000 rw-p 00000000 00:00 0 
7fc6d97fb000-7fc6d97fc000 ---p 00000000 00:00 0 
7fc6d97fc000-7fc6d9ffc000 rw-p 00000000 00:00 0 
7fc6d9ffc000-7fc6d9ffd000 ---p 00000000 00:00 0 
7fc6d9ffd000-7fc6da7fd000 rw-p 00000000 00:00 0 
7fc6da7fd000-7fc6da7fe000 ---p 00000000 00:00 0 
7fc6da7fe000-7fc6daffe000 rw-p 00000000 00:00 0 
7fc6daffe000-7fc6dafff000 ---p 00000000 00:00 0 
7fc6dafff000-7fc6db7ff000 rw-p 00000000 00:00 0 
7fc6db7ff000-7fc6db800000 ---p 00000000 00:00 0 
7fc6db800000-7fc6dc000000 rw-p 00000000 00:00 0 
7fc6dc000000-7fc6dc304000 rw-p 00000000 00:00 0 
7fc6dc304000-7fc6e0000000 ---p 00000000 00:00 0 
7fc6e0000000-7fc6e0833000 rw-p 00000000 00:00 0 
7fc6e0833000-7fc6e4000000 ---p 00000000 00:00 0 
7fc6e4000000-7fc6e4355000 rw-p 00000000 00:00 0 
7fc6e4355000-7fc6e8000000 ---p 00000000 00:00 0 
7fc6e80a1000-7fc6e85ec000 rw-p 00000000 00:00 0 
7fc6e85ec000-7fc6e85ed000 ---p 00000000 00:00 0 
7fc6e85ed000-7fc6e8ded000 rw-p 00000000 00:00 0 
7fc6e8ded000-7fc6e8dee000 ---p 00000000 00:00 0 
7fc6e8dee000-7fc6e95ee000 rw-p 00000000 00:00 0 
7fc6e95ee000-7fc6e95ef000 ---p 00000000 00:00 0 
7fc6e95ef000-7fc6e9def000 rw-p 00000000 00:00 0 
7fc6e9def000-7fc6e9df0000 ---p 00000000 00:00 0 
7fc6e9df0000-7fc6ea5f0000 rw-p 00000000 00:00 0 
7fc6ea5f0000-7fc6ea5f1000 ---p 00000000 00:00 0 
7fc6ea5f1000-7fc6eadf1000 rw-p 00000000 00:00 0 
7fc6eadf1000-7fc6eadf2000 ---p 00000000 00:00 0 
7fc6eadf2000-7fc6ec1b3000 rw-p 00000000 00:00 0 
7fc6ec1b3000-7fc6ec1b4000 ---p 00000000 00:00 0 
7fc6ec1b4000-7fc6ec9b4000 rw-p 00000000 00:00 0 
7fc6ec9b4000-7fc6ec9b5000 ---p 00000000 00:00 0 
7fc6ec9b5000-7fc6ee2b7000 rw-p 00000000 00:00 0 
7fc6ee2b7000-7fc6ee2b8000 ---p 00000000 00:00 0 
7fc6ee2b8000-7fc6eeab8000 rw-p 00000000 00:00 0 
7fc6eeab8000-7fc6eeab9000 ---p 00000000 00:00 0 
7fc6eeab9000-7fc6ef2b9000 rw-p 00000000 00:00 0 
7fc6ef2b9000-7fc6ef2ba000 ---p 00000000 00:00 0 
7fc6ef2ba000-7fc6efaba000 rw-p 00000000 00:00 0 
7fc6efaba000-7fc6efabb000 ---p 00000000 00:00 0 
7fc6efabb000-7fc6f02bb000 rw-p 00000000 00:00 0 
7fc6f02bb000-7fc6f02bc000 ---p 00000000 00:00 0 
7fc6f02bc000-7fc6f0abc000 rw-p 00000000 00:00 0 
7fc6f0abc000-7fc6f0abd000 ---p 00000000 00:00 0 
7fc6f0abd000-7fc6f12bd000 rw-p 00000000 00:00 0 
7fc6f12bd000-7fc6f12be000 ---p 00000000 00:00 0 
7fc6f12be000-7fc6f1abe000 rw-p 00000000 00:00 0 
7fc6f1abe000-7fc6f8000000 r--p 00000000 fd:03 100664789                  /usr/lib/locale/locale-archive
7fc6f8000000-7fc6f8021000 rw-p 00000000 00:00 0 
7fc6f8021000-7fc6fc000000 ---p 00000000 00:00 0 
7fc6fc06c000-7fc6fc16d000 rw-p 00000000 00:00 0 
7fc6fc16d000-7fc6fc16e000 ---p 00000000 00:00 0 
7fc6fc16e000-7fc6fc96e000 rw-p 00000000 00:00 0 
7fc6fc96e000-7fc6fc96f000 ---p 00000000 00:00 0 
7fc6fc96f000-7fc6fd16f000 rw-p 00000000 00:00 0 
7fc6fd16f000-7fc6fd17b000 r-xp 00000000 fd:03 1547                       /usr/lib64/libnss_files-2.17.so
7fc6fd17b000-7fc6fd37a000 ---p 0000c000 fd:03 1547                       /usr/lib64/libnss_files-2.17.so
7fc6fd37a000-7fc6fd37b000 r--p 0000b000 fd:03 1547                       /usr/lib64/libnss_files-2.17.so
7fc6fd37b000-7fc6fd37c000 rw-p 0000c000 fd:03 1547                       /usr/lib64/libnss_files-2.17.so
7fc6fd37c000-7fc6fd382000 rw-p 00000000 00:00 0 
7fc6fd382000-7fc6fd383000 ---p 00000000 00:00 0 
7fc6fd383000-7fc6fef84000 rw-p 00000000 00:00 0 
7fc6fef84000-7fc6fef85000 ---p 00000000 00:00 0 
7fc6fef85000-7fc6ff785000 rw-p 00000000 00:00 0 
7fc6ff785000-7fc6ff786000 ---p 00000000 00:00 0 
7fc6ff786000-7fc6fff86000 rw-p 00000000 00:00 0 
7fc6fff86000-7fc6fff88000 r-xp 00000000 fd:03 1535                       /usr/lib64/libdl-2.17.so
7fc6fff88000-7fc700188000 ---p 00002000 fd:03 1535                       /usr/lib64/libdl-2.17.so
7fc700188000-7fc700189000 r--p 00002000 fd:03 1535                       /usr/lib64/libdl-2.17.so
7fc700189000-7fc70018a000 rw-p 00003000 fd:03 1535                       /usr/lib64/libdl-2.17.so
7fc70018a000-7fc70034e000 r-xp 00000000 fd:03 1529                       /usr/lib64/libc-2.17.so
7fc70034e000-7fc70054d000 ---p 001c4000 fd:03 1529                       /usr/lib64/libc-2.17.so
7fc70054d000-7fc700551000 r--p 001c3000 fd:03 1529                       /usr/lib64/libc-2.17.so05/23 11:21:18.034579 00009571 DND shut down signal is 6
05/23 11:21:18.034687 00009571 DND sender PID:9563 cmdline:taosd
已放弃

**Comment by sangshuduo** [comment]
什么版本？

**Comment by gubaoya123456** [comment]
[root]# taos --version
version: 2.6.0.1

**Comment by sangshuduo** [comment]
先升到 2.6 最新版本试试

**Comment by gubaoya123456** [comment]
数据怎么办，现在没办法备份啊。直接把数据文件和配置文件拷贝出来，然后升级版本，再把数据文件和配置文件拷贝到升级后的数据库中。这样可以吗？

**Comment by sangshuduo** [comment]
参考：https://www.taosdata.com/engineering/10222.html

**Comment by gubaoya123456** [comment]
升级后问题解决了。谢谢。
