### ISSUE TITLE
async_query_example.py

### ISSUE THREAD

**Issue by 8188** [taosdata/TDengine#21424]
?Why Run Demo: docs/examples/python/async_query_example.py 
Always Get { count: 0, done: False }

**Comment by sangshuduo** [comment]
先准备一下数据，可以用 taosBenchmark -d power -t 10 -n 10 -y 来生成。我验证了没问题

**Comment by 8188** [comment]
确实不行，windows10，tdengine3.0.1.8社区版跑在docker上，taospy2.7.7，用c语言的taos_query_a没问题

**Comment by sangshuduo** [comment]
先试试最新版本 3.0.4.2

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
