### ISSUE TITLE
invalid index

### ISSUE THREAD

**Issue by 4yu** [taosdata/TDengine#21431]
日志文件中有大量如下内容，请看是什么原因产生的，怎么解决？

05/23 14:33:10.063545 03632907 WAL vgId:5, invalid index:12784554, first index:24326518, last index:24327727
05/23 14:33:10.063538 03632895 WAL vgId:7, invalid index:13139544, first index:25000839, last index:25007801
05/23 14:33:10.063549 03632907 WAL vgId:5, invalid index:12790853, first index:24326518, last index:24327727
05/23 14:33:10.063551 03632895 WAL vgId:7, invalid index:13132194, first index:25000839, last index:25007801
05/23 14:33:10.063553 03632907 WAL vgId:5, invalid index:12786598, first index:24326518, last index:24327727
05/23 14:33:10.063556 03632895 WAL vgId:7, invalid index:13138539, first index:25000839, last index:25007801
05/23 14:33:10.063561 03632895 WAL vgId:7, invalid index:13134201, first index:25000839, last index:25007801
05/23 14:33:10.063570 03632907 WAL vgId:3, invalid index:12750184, first index:24408079, last index:24414620
05/23 14:33:10.063574 03632907 WAL vgId:3, invalid index:12742769, first index:24408079, last index:24414620
05/23 14:33:10.063578 03632907 WAL vgId:3, invalid index:12749185, first index:24408079, last index:24414620
05/23 14:33:10.063582 03632907 WAL vgId:3, invalid index:12744878, first index:24408079, last index:24414620
05/23 14:33:10.063659 03632908 WAL vgId:9, invalid index:13143625, first index:24875923, last index:24892314
05/23 14:33:10.063663 03632908 WAL vgId:9, invalid index:13136198, first index:24875923, last index:24892314
05/23 14:33:10.063666 03632908 WAL vgId:9, invalid index:13142656, first index:24875923, last index:24892314
05/23 14:33:10.063668 03632908 WAL vgId:9, invalid index:13138295, first index:24875923, last index:24892314
05/23 14:33:10.479055 03632883 WAL vgId:5, invalid index:12791835, first index:24326518, last index:24327728
05/23 14:33:10.479074 03632883 WAL vgId:5, invalid index:12784554, first index:24326518, last index:24327728
05/23 14:33:10.479078 03632883 WAL vgId:5, invalid index:12790853, first index:24326518, last index:24327728

版本是3.0.4.1

**Comment by sangshuduo** [comment]
有什么具体负面作用吗？
