### ISSUE TITLE
ERROR (2318): Read timed out every two or three days

### ISSUE THREAD

**Issue by veigara** [taosdata/TDengine#21433]
版本：3.0.4.1
我rest连接查SELECT LAST(*) from service_data_battery_cell_detail直接报Read timed out
报超时的时候内存会飙升到2个多g,一直不会降下来
但是进入服务器用shell taos是可以查询这个记录的
--------------------------taoslog-----------------------
05/23 14:52:08.991209 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:52:10.491587 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:52:16.493444 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:52:17.994672 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:52:17.994719 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:52:19.494304 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:52:25.496181 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:52:25.752580 00000080 MND start to process ttl timer
05/23 14:52:25.752647 00000080 MND vgId:2, send drop ttl table request to vnode, time:1684824745
05/23 14:52:25.752665 00000080 MND vgId:3, send drop ttl table request to vnode, time:1684824745
05/23 14:52:25.752676 00000080 MND vgId:4, send drop ttl table request to vnode, time:1684824745
05/23 14:52:25.752686 00000080 MND vgId:5, send drop ttl table request to vnode, time:1684824745
05/23 14:52:25.752712 00000080 MND update cluster uptime to 4066200
05/23 14:52:25.752744 00000080 MND trans:13572, prepare transaction
05/23 14:52:25.752758 00000080 MND trans:13572, sync to other mnodes, stage:prepare createTime:1684824745752
05/23 14:52:25.752763 00000080 MND trans:13572, will be proposed
05/23 14:52:25.752787 00000080 MND trans:13572, is proposing and wait sem, seq:695
05/23 14:52:25.767782 00000081 MND trans:13572, is proposed, saved:13572 code:0x0, apply index:27153 term:11 config:-1 role:leader raw:0x7ff39054984b sec:1684824745 seq:695
05/23 14:52:25.767825 00000081 MND trans:13572, perform insert action, row:0x7ff41fe1b40c stage:prepare, callfunc:1, startFunc:0
05/23 14:52:25.767833 00000081 MND trans:13572, is proposed and post sem, seq:695
05/23 14:52:25.767858 00000080 MND trans:13572, sync finished, createTime:1684824745752
05/23 14:52:25.767864 00000080 MND trans:13572, prepare finished
05/23 14:52:25.767869 00000080 MND trans:13572, continue to execute, stage:prepare createTime:1684824745752 leader:1
05/23 14:52:25.767874 00000080 MND trans:13572, stage from prepare to redoAction
05/23 14:52:25.767879 00000080 MND trans:13572, continue to execute, stage:redoAction createTime:1684824745752 leader:1
05/23 14:52:25.767890 00000080 MND trans:13572, stage from redoAction to commit
05/23 14:52:25.767894 00000080 MND trans:13572, continue to execute, stage:commit createTime:1684824745752 leader:1
05/23 14:52:25.767900 00000080 MND trans:13572, commit transaction
05/23 14:52:25.767906 00000080 MND trans:13572, sync to other mnodes, stage:commit createTime:1684824745752
05/23 14:52:25.767911 00000080 MND trans:13572, will be proposed
05/23 14:52:25.767928 00000080 MND trans:13572, is proposing and wait sem, seq:696
05/23 14:52:25.771567 00000081 MND trans:13572, is proposed, saved:13572 code:0x0, apply index:27154 term:11 config:-1 role:leader raw:0x7ff390549c4b sec:1684824745 seq:696
05/23 14:52:25.771595 00000081 MND trans:13572, perform update action, old row:0x7ff41fe1b40c stage:commit create:1684824745752, new row:0x7ff41fed280c stage:commit create:1684824745752
05/23 14:52:25.771602 00000081 MND trans:13572, perform delete action, row:0x7ff41fed280c stage:commit callfunc:0, stopFunc:0
05/23 14:52:25.771608 00000081 MND trans:13572, is proposed and post sem, seq:696
05/23 14:52:25.771641 00000080 MND trans:13572, sync finished, createTime:1684824745752
05/23 14:52:25.771648 00000080 MND trans:13572, commit finished
05/23 14:52:25.771651 00000080 MND trans:13572, stage from commit to commitAction
05/23 14:52:25.771656 00000080 MND trans:13572, continue to execute, stage:commitAction createTime:1684824745752 leader:1
05/23 14:52:25.771670 00000080 MND trans:13572, commitAction:0 write to sdb, type:cluster status:ready
05/23 14:52:25.771675 00000080 MND trans:13572, all 1 actions execute successfully
05/23 14:52:25.771679 00000080 MND trans:13572, stage from commitAction to finished
05/23 14:52:25.771683 00000080 MND trans:13572, continue to execute, stage:finished createTime:1684824745752 leader:1
05/23 14:52:25.771698 00000080 MND trans:13572, perform delete action, row:0x7ff41fe1ae0c stage:finished callfunc:0, stopFunc:0
05/23 14:52:25.771706 00000080 MND trans:13572, execute finished, code:0x0, failedTimes:0 createTime:1684824745752
05/23 14:52:25.771711 00000080 MND trans:13572, send rsp, stage:finished failedTimes:0 code:0x0
05/23 14:52:25.771716 00000080 MND trans:13572, perform delete action, row:0x7ff41fe1b40c stage:finished callfunc:1, stopFunc:0
05/23 14:52:26.996591 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:52:26.996648 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:52:28.497003 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:52:34.499063 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:52:35.999608 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:52:35.999670 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:52:37.500119 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:52:43.501970 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:52:45.002519 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:52:45.002566 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:52:46.502943 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:52:52.504808 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:52:54.005307 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:52:54.005355 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:52:55.505750 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:53:01.509596 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:53:03.009991 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:53:03.010039 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:53:04.510387 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:53:10.512279 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:53:12.012753 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:53:12.012805 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:53:13.513163 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:53:19.515555 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:53:21.016058 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:53:21.016112 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:53:22.516508 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:53:28.518447 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:53:30.018889 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:53:30.018945 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:53:31.519472 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:53:37.521225 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:53:39.021601 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:53:39.021659 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:53:40.522350 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:53:46.524016 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:53:48.024541 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:53:48.024590 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:53:49.525165 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:53:55.527012 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:53:57.027422 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:53:57.027485 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:53:58.527828 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:54:04.529633 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:54:06.030181 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:54:06.030237 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:54:07.530609 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:54:13.532312 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:54:15.032753 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:54:15.032806 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:54:16.533339 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:54:22.535115 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:54:24.035571 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:54:24.035619 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:54:25.536034 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:54:31.537925 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:54:33.038352 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:54:33.038407 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:54:34.538899 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:54:40.540792 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:54:42.041201 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:54:42.041248 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:54:43.541622 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:54:49.543959 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:54:51.044500 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:54:51.044552 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:54:52.545601 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:54:58.546733 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:55:00.047246 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:55:00.047294 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:55:01.551721 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:55:07.553777 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:55:09.052632 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:55:09.052689 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:55:10.553114 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:55:16.555070 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:55:18.055516 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:55:18.055564 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:55:19.556011 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:55:25.557977 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:55:27.058350 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:55:27.058404 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:55:28.558722 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:55:34.560438 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:55:36.060905 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:55:36.060952 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:55:37.561475 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:55:43.563111 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:55:45.063557 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:55:45.063605 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:55:46.565215 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:55:52.567154 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:55:54.067542 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:55:54.067586 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:55:55.568024 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:56:01.569850 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:56:03.070417 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:56:03.070484 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:56:04.570883 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:56:10.572582 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:56:12.073244 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:56:12.073298 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:56:13.573613 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:56:19.575336 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:56:21.075886 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:56:21.075936 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:56:22.576316 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:56:28.578196 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:56:30.079330 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:56:30.079379 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:56:31.579181 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:56:37.581114 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:56:39.081789 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:56:39.081842 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:56:40.582244 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:56:46.584123 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:56:48.084769 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:56:48.084821 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:56:49.585195 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:56:55.587041 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:56:57.088137 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:56:57.088187 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:56:58.588545 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:57:04.591024 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:57:06.091581 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:57:06.091627 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:57:07.591993 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:57:13.594048 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:57:15.094510 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:57:15.094562 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:57:16.595045 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:57:22.596942 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:57:24.097453 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:57:24.097518 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:57:25.597944 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:57:26.175042 00000080 MND update cluster uptime to 4066500
05/23 14:57:26.175082 00000080 MND trans:13573, prepare transaction
05/23 14:57:26.175092 00000080 MND trans:13573, sync to other mnodes, stage:prepare createTime:1684825046175
05/23 14:57:26.175099 00000080 MND trans:13573, will be proposed
05/23 14:57:26.175117 00000080 MND trans:13573, is proposing and wait sem, seq:697
05/23 14:57:26.176725 00000081 MND trans:13573, is proposed, saved:13573 code:0x0, apply index:27155 term:11 config:-1 role:leader raw:0x7ff39054a04b sec:1684825046 seq:697
05/23 14:57:26.176757 00000081 MND trans:13573, perform insert action, row:0x7ff41fed280c stage:prepare, callfunc:1, startFunc:0
05/23 14:57:26.176765 00000081 MND trans:13573, is proposed and post sem, seq:697
05/23 14:57:26.176800 00000080 MND trans:13573, sync finished, createTime:1684825046175
05/23 14:57:26.176808 00000080 MND trans:13573, prepare finished
05/23 14:57:26.176814 00000080 MND trans:13573, continue to execute, stage:prepare createTime:1684825046175 leader:1
05/23 14:57:26.176819 00000080 MND trans:13573, stage from prepare to redoAction
05/23 14:57:26.176824 00000080 MND trans:13573, continue to execute, stage:redoAction createTime:1684825046175 leader:1
05/23 14:57:26.176830 00000080 MND trans:13573, stage from redoAction to commit
05/23 14:57:26.176834 00000080 MND trans:13573, continue to execute, stage:commit createTime:1684825046175 leader:1
05/23 14:57:26.176839 00000080 MND trans:13573, commit transaction
05/23 14:57:26.176845 00000080 MND trans:13573, sync to other mnodes, stage:commit createTime:1684825046175
05/23 14:57:26.176850 00000080 MND trans:13573, will be proposed
05/23 14:57:26.176864 00000080 MND trans:13573, is proposing and wait sem, seq:698
05/23 14:57:26.178227 00000081 MND trans:13573, is proposed, saved:13573 code:0x0, apply index:27156 term:11 config:-1 role:leader raw:0x7ff39054a44b sec:1684825046 seq:698
05/23 14:57:26.178262 00000081 MND trans:13573, perform update action, old row:0x7ff41fed280c stage:commit create:1684825046175, new row:0x7ff41fed2e0c stage:commit create:1684825046175
05/23 14:57:26.178270 00000081 MND trans:13573, perform delete action, row:0x7ff41fed2e0c stage:commit callfunc:0, stopFunc:0
05/23 14:57:26.178279 00000081 MND trans:13573, is proposed and post sem, seq:698
05/23 14:57:26.178313 00000080 MND trans:13573, sync finished, createTime:1684825046175
05/23 14:57:26.178318 00000080 MND trans:13573, commit finished
05/23 14:57:26.178322 00000080 MND trans:13573, stage from commit to commitAction
05/23 14:57:26.178327 00000080 MND trans:13573, continue to execute, stage:commitAction createTime:1684825046175 leader:1
05/23 14:57:26.178336 00000080 MND trans:13573, commitAction:0 write to sdb, type:cluster status:ready
05/23 14:57:26.178345 00000080 MND trans:13573, all 1 actions execute successfully
05/23 14:57:26.178350 00000080 MND trans:13573, stage from commitAction to finished
05/23 14:57:26.178354 00000080 MND trans:13573, continue to execute, stage:finished createTime:1684825046175 leader:1
05/23 14:57:26.178369 00000080 MND trans:13573, perform delete action, row:0x7ff41fe1b40c stage:finished callfunc:0, stopFunc:0
05/23 14:57:26.178376 00000080 MND trans:13573, execute finished, code:0x0, failedTimes:0 createTime:1684825046175
05/23 14:57:26.178381 00000080 MND trans:13573, send rsp, stage:finished failedTimes:0 code:0x0
05/23 14:57:26.178387 00000080 MND trans:13573, perform delete action, row:0x7ff41fed280c stage:finished callfunc:1, stopFunc:0
05/23 14:57:31.599886 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:57:33.100330 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:57:33.100381 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:57:34.600851 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:57:40.602747 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta
05/23 14:57:42.103127 00000079 MND stb:1.db_hndk_station.service_data_battery_cell_detail, start to retrieve meta
05/23 14:57:42.103175 00000079 MND stb:1.db_hndk_station_relast.service_data_chargingpile, start to retrieve meta
05/23 14:57:43.603562 00000079 MND stb:1.db_hndk_station_relast.service_data_battery_cell_detail, start to retrieve meta
05/23 14:57:49.605525 00000079 MND stb:1.db_hndk_station.service_data_chargingpile, start to retrieve meta

**Comment by sangshuduo** [comment]
taos shell 查询耗时多久？内存飙升是指服务端？请截图。REST 超时请问是用什么连接器通过什么接口连接？设置的超时时间是多少？

**Comment by veigara** [comment]
已经找到问题了，前端没传时间过来，导致数据库拉取整个表的数据。
但是，断开请求后数据库飙升的内存也不会下降，外部rest连接也连不上，这也是一个问题。
查询sql:SELECT LAST(*) from service_data_battery_cell_detail
taos shelle 查询最后一条数据耗时 0.038048s 
用的java连接器，用rest连接6041端口，连接地址：jdbc:TAOS-RS://47.108.184.22:6041/db_hndk_station?timezone=UTC-8
超时时间是默认的，没有设置
![1](https://github.com/taosdata/TDengine/assets/36318745/305a0eb6-6eb9-49f0-a72c-ec10c4979a90)
![3](https://github.com/taosdata/TDengine/assets/36318745/41a2790a-d5a1-4cd2-9ce3-1e4de866f608)
![5](https://github.com/taosdata/TDengine/assets/36318745/f8439bdb-56d0-44c9-b9f9-74f8be0b7121)
![2](https://github.com/taosdata/TDengine/assets/36318745/0ae783a5-dc1f-4c59-ad40-d18f7f8d5188)

**Comment by sangshuduo** [comment]
前端没传时间过来，导致数据库拉取整个表的数据
--
为什么会拉整个表的数据？SQL命令是什么？是不是从应用侧避免产生这个场景可以解决问题？

**Comment by veigara** [comment]
由于前端的时间没传过，sql: select * from service_data_battery_cell_detail
现在限制了，是可以从应用解决
但是也不应该直接把rest连接口就堵死了啊，你这里面的taos shell里面能查询其他的sql，rest连接就不行了
mysql也没有这个啊，超时了查不到就查不到，但是也不能影响其他查询吧

**Comment by sangshuduo** [comment]
> 由于前端的时间没传过，sql: select * from service_data_battery_cell_detail 现在限制了，是可以从应用解决 但是也不应该直接把rest连接口就堵死了啊，你这里面的taos shell里面能查询其他的sql，rest连接就不行了 mysql也没有这个啊，超时了查不到就查不到，但是也不能影响其他查询吧

mysql 也是 REST 吗？

**Comment by veigara** [comment]
应该是，也是加载驱动就能查询

**Comment by sangshuduo** [comment]
> 应该是，也是加载驱动就能查询

麻烦确认一下。

之所以问是因为 REST 是通过 taosAdapter，会使用预分配固定数量连接的连接池，如果所有连接都忙，新的查询没有机会新建连接所以查不到。taos shell 可以是不使用连接池每次都会新建连接。

如果 mysql 也用 REST，说不定我们可以借鉴一下 mysql 怎么处理这种问题

**Comment by veigara** [comment]
刚确认了，mysql有rest这种，地址：https://www.modb.pro/db/621231

**Comment by veigara** [comment]
没用，我用的版本比较低的mysql5.7

**Comment by ctrl1109** [comment]
请问这个问题解决了吗，我也遇到差不多的，但是我是给了时间范围还是会这样。而且复现不了，隔段时间不知道那个操作下就Read timed out了....

**Comment by veigara** [comment]
没有，还没解决，现在我是发现查询的数据量少就没问题，一旦数据量大了他那个连接池的连接就用完了，连接不起。
现在只能后台应用控制尽量减少大数据的查询，搞分页，查询字段减少这些。
他那个用非主键时间戳排序也会出现这个问题

**Comment by veigara** [comment]
用原生的连接又是各种出问题,真尴尬

**Comment by ctrl1109** [comment]
你这么一说我就知道了，我排序用的不是主键时间戳，真的非常感谢

**Comment by ctrl1109** [comment]
因为就是最近改动才出现这个问题，最近刚好改了个排序的问题。

**Comment by blueiky** [comment]
类似的问题我这边也遇到过，用 rest 查询超级表数据总数的时候，直接会出现Read timed out，但直接使用 taos命令行查询的时候，7秒钟就查询出来了，目前都没解决

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
