### ISSUE TITLE
csv import issue

### ISSUE THREAD

**Issue by linglongQaQ** [taosdata/TDengine#21450]
1 使用客户端导入一个csv文件，大概有43万行的数据，只有一个节点的，导入报错:some vnode/qnode/mnode(s) out of service

taos> insert into t30000001 file '/root/t3000001_all_td.csv';

DB error: some vnode/qnode/mnode(s) out of service (46.175529s)

错误日志信息：

==================================================
                new log file                      
==================================================
05/24 10:32:11.092269 00021382 UTL apoll url not load
05/24 10:32:11.092616 00021382 UTL load from cfg file /etc/taos//taos.cfg success
05/24 10:32:11.092626 00021382 UTL env file:.env not load
05/24 10:32:11.092632 00021382 UTL load from env variables cfg success
05/24 10:32:11.092712 00021382 UTL                      global config
05/24 10:32:11.092714 00021382 UTL =================================================================
05/24 10:32:11.092717 00021382 UTL default      firstEp                  VM-0-3-centos:6030
05/24 10:32:11.092720 00021382 UTL default      secondEp                 VM-0-3-centos:6030
05/24 10:32:11.092722 00021382 UTL default      fqdn                     VM-0-3-centos
05/24 10:32:11.092724 00021382 UTL default      serverPort               6030
05/24 10:32:11.092725 00021382 UTL default      tempDir                  /tmp/
05/24 10:32:11.092727 00021382 UTL default      minimalTmpDirGB          1.00
05/24 10:32:11.092739 00021382 UTL default      shellActivityTimer       3
05/24 10:32:11.092741 00021382 UTL default      compressMsgSize          -1
05/24 10:32:11.092743 00021382 UTL default      compressColData          -1
05/24 10:32:11.092744 00021382 UTL default      queryPolicy              1
05/24 10:32:11.092746 00021382 UTL default      querySmaOptimize         0
05/24 10:32:11.092748 00021382 UTL default      queryPlannerTrace        0
05/24 10:32:11.092750 00021382 UTL default      queryNodeChunkSize       32768
05/24 10:32:11.092751 00021382 UTL default      queryUseNodeAllocator    1
05/24 10:32:11.092753 00021382 UTL default      keepColumnName           0
05/24 10:32:11.092755 00021382 UTL default      smlChildTableName        
05/24 10:32:11.092757 00021382 UTL default      smlTagName               _tag_null
05/24 10:32:11.092758 00021382 UTL default      maxMemUsedByInsert       1024
05/24 10:32:11.092760 00021382 UTL default      useAdapter               0
05/24 10:32:11.092761 00021382 UTL default      crashReporting           1
05/24 10:32:11.092763 00021382 UTL default      queryMaxConcurrentTable  200
05/24 10:32:11.092765 00021382 UTL default      configDir                /etc/taos/
05/24 10:32:11.092767 00021382 UTL default      scriptDir                /etc/taos/
05/24 10:32:11.092769 00021382 UTL default      logDir                   /var/log/taos/
05/24 10:32:11.092771 00021382 UTL default      minimalLogDirGB          1.00
05/24 10:32:11.092773 00021382 UTL default      numOfLogLines            10000000
05/24 10:32:11.092775 00021382 UTL default      asyncLog                 1
05/24 10:32:11.092777 00021382 UTL default      logKeepDays              0
05/24 10:32:11.092778 00021382 UTL default      debugFlag                0
05/24 10:32:11.092780 00021382 UTL default      simDebugFlag             143
05/24 10:32:11.092782 00021382 UTL default      tmrDebugFlag             131
05/24 10:32:11.092784 00021382 UTL default      uDebugFlag               131
05/24 10:32:11.092785 00021382 UTL default      rpcDebugFlag             131
05/24 10:32:11.092787 00021382 UTL default      jniDebugFlag             131
05/24 10:32:11.092789 00021382 UTL default      qDebugFlag               131
05/24 10:32:11.092790 00021382 UTL default      cDebugFlag               131
05/24 10:32:11.092792 00021382 UTL default      timezone                 Asia/Shanghai (CST, +0800)
05/24 10:32:11.092793 00021382 UTL default      locale                   en_US.utf8
05/24 10:32:11.092795 00021382 UTL default      charset                  UTF-8
05/24 10:32:11.092797 00021382 UTL default      assert                   1
05/24 10:32:11.092798 00021382 UTL default      enableCoreFile           1
05/24 10:32:11.092800 00021382 UTL default      numOfCores               2.00
05/24 10:32:11.092802 00021382 UTL default      openMax                  100001
05/24 10:32:11.092803 00021382 UTL default      streamMax                16
05/24 10:32:11.092805 00021382 UTL default      pageSizeKB               4
05/24 10:32:11.092807 00021382 UTL default      totalMemoryKB            7782616
05/24 10:32:11.092809 00021382 UTL default      os sysname               Linux
05/24 10:32:11.092810 00021382 UTL default      os nodename              VM-0-3-centos
05/24 10:32:11.092812 00021382 UTL default      os release               3.10.0-1160.71.1.el7.x86_64
05/24 10:32:11.092814 00021382 UTL default      os version               #1 SMP Tue Jun 28 15:37:28 UTC 2022
05/24 10:32:11.092815 00021382 UTL default      os machine               x86_64
05/24 10:32:11.092817 00021382 UTL default      version                  3.0.4.0
05/24 10:32:11.092819 00021382 UTL default      compatible_version       3.0.0.0
05/24 10:32:11.092820 00021382 UTL default      gitinfo                  b3acd9b1825567f9848f6f3717814efa439206ab
05/24 10:32:11.092822 00021382 UTL default      buildinfo                Built at 2023-04-15 08:53
05/24 10:32:11.092824 00021382 UTL =================================================================
05/24 10:32:11.095055 00021384 QRY catalog update thread started
05/24 10:32:11.095669 00021382 QRY scheduler 0x3363663037663238 initizlized, maxJob:1000
05/24 10:32:11.097047 00021382 TSC connecting to server, numOfEps:2 inUse:0 user:root db:(null) key:root:dcc5bed04851fec854c035b2e40263b6:(null):0
05/24 10:32:11.097052 00021382 TSC ep:0, VM-0-3-centos:6030
05/24 10:32:11.097053 00021382 TSC ep:1, VM-0-3-centos:6030
05/24 10:33:46.091099 00021397 TSC ERROR 0x5 error happens, code:-2147473920 - syntax error near, reqId:0x3ba3869af36a0043
05/24 10:34:02.626211 00021389 QRY ERROR QID:3ba3869b34010051 CTG:0x7f0aa4beb000 no tbmeta got, tbNmae:t3000000
05/24 10:34:02.626229 00021389 QRY ERROR QID:3ba3869b34010051 CTG:0x7f0aa4beb000 Get table 1.db30000.t3000000 meta failed with error Table does not exist
05/24 10:34:02.626263 00021389 TSC ERROR 0x8 error occurs, code:Fail to get table info, return to user app, reqId:0x3ba3869b34010051
05/24 10:35:54.153725 00021393 RPC WARN TSC conn 0x7f0a9ae06000 send cost:143810us, send exception
05/24 10:35:55.209609 00021397 TSC WARN slow query: insert into t30000001 file '/root/t3000001_all_td.csv';, duration:50361940
05/24 10:48:06.147273 00021397 TSC WARN slow query: select * from t30000001 where rece_time >='2022-04-01 00:00:00';, duration:6047480
05/24 11:19:27.246492 00021397 TSC ERROR 0x11 error happens, code:-2147473920 - syntax error near, reqId:0x3ba386c4c70e0772
05/24 11:20:06.760062 00021397 TSC ERROR 0x12 error happens, code:-2147473920 - syntax error near, reqId:0x3ba386c56166078d
05/24 11:20:40.610869 00021397 TSC ERROR 0x13 error happens, code:-2147473920 - syntax error near, reqId:0x3ba386c5e5a207a5
05/24 11:25:00.236386 00021397 TSC ERROR 0x14 error happens, code:-2147473920 - syntax error near, reqId:0x3ba386c9dbcc0853
05/24 11:30:28.911901 00021397 TSC ERROR 0x15 error happens, code:-2147473920 - syntax error near, reqId:0x3ba386cedfaf092f
05/24 11:31:18.972215 00021397 TSC ERROR 0x16 error happens, code:-2147473920 - syntax error near, reqId:0x3ba386cfa33c0952
05/24 11:33:14.026875 00021397 TSC WARN slow query: select * from t30000001 , duration:36033587
05/24 12:01:14.742972 00021397 TSC ERROR 0x18 error happens, code:-2147473920 - syntax error near, reqId:0x3ba386eb09f60e01
05/24 12:01:23.197573 00021397 TSC ERROR 0x19 error happens, code:-2147473920 - syntax error near, reqId:0x3ba386eb2afd0e07
05/24 13:38:20.648628 00021392 RPC WARN TSC conn 0x7f0a9cc06000 read error:ECONNRESET, ref:1
05/24 13:38:20.649997 00021392 RPC ERROR TSC conn 0x7f0a9cc06000 failed to write:ECANCELED
05/24 13:38:20.940847 00021392 RPC WARN TSC conn 0x7f0a9d05c380 read error:ECONNRESET, ref:1
05/24 13:38:20.945188 00021392 RPC ERROR TSC conn 0x7f0a9d05c380 failed to write:ECANCELED
05/24 13:38:21.218993 00021392 RPC WARN TSC conn 0x7f0a9d05c380 send cost:883287us, send exception
05/24 13:38:21.219007 00021392 RPC ERROR TSC conn 0x7f0a9d05c380 failed to write:ECONNRESET
05/24 13:38:21.497733 00021392 RPC WARN TSC conn 0x7f0a9d05c380 send cost:1162026us, send exception
05/24 13:38:21.497746 00021392 RPC ERROR TSC conn 0x7f0a9d05c380 failed to write:ECONNRESET
05/24 13:38:21.793467 00021392 RPC WARN TSC conn 0x7f0a9d05c380 send cost:1457761us, send exception
05/24 13:38:21.793481 00021392 RPC ERROR TSC conn 0x7f0a9d05c380 failed to write:ECONNRESET
05/24 13:38:22.130493 00021392 RPC WARN TSC conn 0x7f0a9d05c380 send cost:1794785us, send exception
05/24 13:38:22.130506 00021392 RPC ERROR TSC conn 0x7f0a9d05c380 failed to write:ECONNRESET
05/24 13:38:22.548920 00021392 RPC WARN TSC conn 0x7f0a9d05c380 send cost:2213213us, send exception
05/24 13:38:22.548934 00021392 RPC ERROR TSC conn 0x7f0a9d05c380 failed to write:ECONNRESET
05/24 13:38:23.122660 00021392 RPC WARN TSC conn 0x7f0a9d05c380 read error:ECONNRESET, ref:1
05/24 13:38:23.122732 00021392 RPC ERROR TSC conn 0x7f0a9d05c380 failed to write:ECANCELED
05/24 13:38:24.017995 00021392 RPC WARN TSC conn 0x7f0a9d05c380 send cost:3682288us, send exception
05/24 13:38:24.018008 00021392 RPC ERROR TSC conn 0x7f0a9d05c380 failed to write:ECONNRESET
05/24 13:38:25.273252 00021392 RPC WARN TSC conn 0x7f0a9d05c380 send cost:4937546us, send exception
05/24 13:38:25.273266 00021392 RPC ERROR TSC conn 0x7f0a9d05c380 failed to write:ECONNRESET
05/24 13:38:26.532756 00021392 RPC WARN TSC conn 0x7f0a9d05c380 read error:ECONNRESET, ref:1
05/24 13:38:26.532826 00021392 RPC ERROR TSC conn 0x7f0a9d05c380 failed to write:ECANCELED
05/24 13:38:27.787371 00021392 RPC WARN TSC conn 0x7f0a9d05c380 send cost:7451664us, send exception
05/24 13:38:27.787384 00021392 RPC ERROR TSC conn 0x7f0a9d05c380 failed to write:ECONNRESET
05/24 13:38:29.044760 00021392 RPC WARN TSC conn 0x7f0a9d05c380 read error:ECONNRESET, ref:1
05/24 13:38:29.044828 00021392 RPC ERROR TSC conn 0x7f0a9d05c380 failed to write:ECANCELED
05/24 13:38:30.300603 00021392 RPC WARN TSC conn 0x7f0a9d05c380 send cost:9964896us, send exception
05/24 13:38:30.300616 00021392 RPC ERROR TSC conn 0x7f0a9d05c380 failed to write:ECONNRESET
05/24 13:38:31.550994 00021392 RPC WARN TSC conn 0x7f0a9d05c380 send cost:11215287us, send exception
05/24 13:38:31.551007 00021392 RPC ERROR TSC conn 0x7f0a9d05c380 failed to write:ECONNRESET
05/24 13:38:31.560451 00021389 QRY ERROR QID:0x3ba3864365ac1d18,TID:0xe,EID:0 task failed and no more retry, code:some vnode/qnode/mnode(s) out of service
05/24 13:38:31.563732 00021397 TSC WARN slow query: insert into t30000001 file '/root/t3000001_all_td.csv';, duration:4617556

**Comment by yu285** [comment]
连接问题 https://www.taosdata.com/engineering/11076.html 看下问题1 排查一下

**Comment by linglongQaQ** [comment]
好的，我这边试下，主要是插入24万行数据文件可以，文件大小翻倍后就报这个错！！！！

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
