### ISSUE TITLE
page query return error result

### ISSUE THREAD

**Issue by wowo404** [taosdata/TDengine#2145]
total data amount is 17136, page query with limit and offset, where the offset set to 16473,no data returned.
here is my query procedure.
![1f4d49ce4829e8a4810a372c792e8eb](https://user-images.githubusercontent.com/39786064/83834249-6bf17600-a720-11ea-8aba-36773d79e470.png)

database version:1.6.5.9
system:CentOS Linux release 7.6.1810

**Comment by Aries-Lee1991** [comment]
wait a moment, the related R&D will check it.

**Comment by yihaoDeng** [comment]
@wowo404  please try newly released version 2.0.3.  the data vesion you used is obsoleted
