### ISSUE TITLE
RPC ERROR SHELL 0x7f66abb760e0 0xla2d failed to send, msgLen:109 written:-1, reason:Success

### ISSUE THREAD

**Issue by yupingsong-anylink-io** [taosdata/TDengine#21459]
Version: 2.6.0.10
![微信图片_20230525085744](https://github.com/taosdata/TDengine/assets/76909130/12759a4f-c811-4547-b5fe-41ce842a53e0)

tdengine日志会有不间断的error报错，这种情况是什么原因？数据是入库失败了，还是成功了？

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/

如果还有具体的使用问题，可以加微信：a15652223354
