### ISSUE TITLE
executeBatch多线程批量写入时卡死

### ISSUE THREAD

**Issue by yupingsong-anylink-io** [taosdata/TDengine#21463]
**Bug Description**
Java通过executeBatch方式多线程批量写入时卡住，不再往下执行，也没有报错

**Environment (please complete the following information):**
 - OS: CentOS 8
 - TDengine Version 2.6.0.8
 - jdbc驱动：2.0.38
```
<dependency>
    <groupId>com.taosdata.jdbc</groupId>
    <artifactId>taos-jdbcdriver</artifactId>
    <version>2.0.38</version>
</dependency>
```

Java代码如下：
```
private boolean doInsert(List<ItemDataPO> itemDataPOs) throws Exception
    {
        Connection connection = null;
        Statement stmt = null;
        List<String> sqlList = createSql(itemDataPOs);
        if(sqlList == null || sqlList.size() == 0){
            return true;
        }
        try {
            DruidDataSource druidDataSource = ApplicationContextHelper.getBean("dataSourceTDengine", DruidDataSource.class);
            connection = DataSourceUtils.getConnection(druidDataSource);
            stmt = connection.createStatement();

            for(String sql : sqlList) {
                stmt.addBatch(sql);
            }
            stmt.executeBatch();
            return true;
        }catch (Exception e){
            logger.error(e.getMessage(), e);
        } finally {
            try{
                if(stmt != null){
                    stmt.close();
                    stmt=null;
                }
                if(connection != null){
                    connection.close();
                    connection=null;
                }
            }catch (Exception e){
                logger.error(e.getMessage(), e);
            }
        }
        return false;
    }
```

**Comment by sangshuduo** [comment]
先把 TDengine 升级到最新版本

**Comment by yupingsong-anylink-io** [comment]
2.6.0.8 这个版本是否可能存在这种bug？另外还在使用的是2.6.0.10，倒是还没遇到这种问题。
生产环境直接升级不是首选的方案，还是希望先找到问题再考虑升级，谢谢

**Comment by HeheYang** [comment]
> 2.6.0.8 这个版本是否可能存在这种bug？另外还在使用的是2.6.0.10，倒是还没遇到这种问题。 生产环境直接升级不是首选的方案，还是希望先找到问题再考虑升级，谢谢

升级吧，，高并发情况下，增删改查都会出现卡死现象，我也反馈过很多遍，他们都没有处理过，现在升级到3.0.4，没有再出现过高并发情况下，连接卡住的问题了

**Comment by sangshuduo** [comment]
> > 2.6.0.8 这个版本是否可能存在这种bug？另外还在使用的是2.6.0.10，倒是还没遇到这种问题。 生产环境直接升级不是首选的方案，还是希望先找到问题再考虑升级，谢谢
> 
> 升级吧，，高并发情况下，增删改查都会出现卡死现象，我也反馈过很多遍，他们都没有处理过，现在升级到3.0.4，没有再出现过高并发情况下，连接卡住的问题了

bug 解决了在新版本里发布，旧版本需要升级到新版本来解决，不升级怎么解决旧版本的 bug？

**Comment by kdash19854** [comment]
> > > 2.6.0.8 这个版本是否可能存在这种bug？另外还在使用的是2.6.0.10，倒是还没遇到这种问题。 生产环境直接升级不是首选的方案，还是希望先找到问题再考虑升级，谢谢
> > 
> > 
> > 升级吧，，高并发情况下，增删改查都会出现卡死现象，我也反馈过很多遍，他们都没有处理过，现在升级到3.0.4，没有再出现过高并发情况下，连接卡住的问题了
> 
> bug 解决了在新版本里发布，旧版本需要升级到新版本来解决，不升级怎么解决旧版本的 bug？

已经从2.6.0.24一路升到了2.6.0.32版本，仍然会出现insert卡住没有返回情况，3.0没敢去升，卡住的时候kafka主题就被卡掉了

**Comment by yupingsong-anylink-io** [comment]
> > > > 2.6.0.8 这个版本是否可能存在这种bug？另外还在使用的是2.6.0.10，倒是还没遇到这种问题。 生产环境直接升级不是首选的方案，还是希望先找到问题再考虑升级，谢谢
> > > 
> > > 
> > > 升级吧，，高并发情况下，增删改查都会出现卡死现象，我也反馈过很多遍，他们都没有处理过，现在升级到3.0.4，没有再出现过高并发情况下，连接卡住的问题了
> > 
> > 
> > bug 解决了在新版本里发布，旧版本需要升级到新版本来解决，不升级怎么解决旧版本的 bug？
> 
> 已经从2.6.0.24一路升到了2.6.0.32版本，仍然会出现insert卡住没有返回情况，3.0没敢去升，卡住的时候kafka主题就被卡掉了

不知道你是不是你的tdengine是不是跑在docker容器里，我这两天测试了非docker容器版本的td2.6.0.8，暂时还没发现没问题（不过只跑了大概12个小时，docker容器版本只能坚持1个小时不到）

**Comment by kdash19854** [comment]
> > > > > 2.6.0.8 这个版本是否可能存在这种bug？另外还在使用的是2.6.0.10，倒是还没遇到这种问题。 生产环境直接升级不是首选的方案，还是希望先找到问题再考虑升级，谢谢
> > > > 
> > > > 
> > > > 升级吧，，高并发情况下，增删改查都会出现卡死现象，我也反馈过很多遍，他们都没有处理过，现在升级到3.0.4，没有再出现过高并发情况下，连接卡住的问题了
> > > 
> > > 
> > > bug 解决了在新版本里发布，旧版本需要升级到新版本来解决，不升级怎么解决旧版本的 bug？
> > 
> > 
> > 已经从2.6.0.24一路升到了2.6.0.32版本，仍然会出现insert卡住没有返回情况，3.0没敢去升，卡住的时候kafka主题就被卡掉了
> 
> 不知道你的tdengine是不是跑在docker容器里，我这两天测试了非docker容器版本的td2.6.0.8，暂时还没发现没问题（不过只跑了大概12个小时，docker容器版本只能坚持1个小时不到）

没有用docker，用3台云服务器搭得集群，12小时其实一般反应不出来问题的，一般都是跑一段时间后会出现这个问题，一般2周左右，出现了问题之后重启taos服务，现象就又消失了，疑似taos重启的时候会做某种数据或服务自平衡操作
