### ISSUE TITLE
fqdn  可以使用服务器ip么

### ISSUE THREAD

**Issue by w15135591069** [taosdata/TDengine#21466]
########################################################
#                                                      #
#                  Configuration                       #
#                                                      #
########################################################

######### 0. Client only configurations #############

# The interval for CLI to send heartbeat to mnode
# shellActivityTimer        3

############### 1. Cluster End point ############################

# The end point of the first dnode in the cluster to be connected to when this dnode or the CLI utility is started
#firstEp                   tdengine:6030

firstEp                    13.11.230.77:6030

# The end point of the second dnode to be connected to if the firstEp is not available
# secondEp

############### 2. Configuration Parameters of current dnode #####

# The FQDN of the host on which this dnode will be started. It can be IP address
#fqdn                      tdengine

fqdn                       13.11.230.77

**Comment by w15135591069** [comment]
1111

**Comment by yu285** [comment]
可以的。https://www.taosdata.com/tdengine-engineering/2741.html
