### ISSUE TITLE
TDengine 3.X  以insert形式更新过多，会导致查询慢；有没有其他的替代方式

### ISSUE THREAD

**Issue by anyedilong** [taosdata/TDengine#21474]
![image](https://github.com/taosdata/TDengine/assets/31983335/d0904712-6a2a-4bc7-9648-6f0f31e5d8f0)

**Comment by sangshuduo** [comment]
应用来保证不做更新操作

**Comment by longcf6666** [comment]
同样的，超级表3亿数据，10000+子表。我count（*）直接超时，查不出来了。应该也是有不少相同时间戳导致的更新操作。既然能够以insert形式更新，现在导致count（*）都没办法查询了，这个不能优化解决的吗？

**Comment by yu285** [comment]
企业版可以支持在线充足，开源版需要自己导出数据再导入。
