### ISSUE TITLE
原生连接时 提示  Exception in thread "main" java.sql.SQLException: TDengine ERROR (0x80000020): some vnode/qnode/mnode(s) out of service

### ISSUE THREAD

**Issue by shishi1yi** [taosdata/TDengine#21477]
![image](https://github.com/taosdata/TDengine/assets/50871933/48faeff5-e0b5-44ee-969b-854a1c2a4dc3)

**Comment by weisttl** [comment]
+1

**Comment by sangshuduo** [comment]
some vnode/qnode/mnode(s) out of service
--
这种问题通常是环境原因，例如 IP 地址变了

**Comment by weisttl** [comment]
我发现vnode的leader如果不在FirstEp上会出现这个问题

**Comment by shi0513** [comment]
> 我发现vnode的leader如果不在FirstEp上会出现这个问题

请教一下这个问题怎么处理喃

**Comment by sangshuduo** [comment]
检查一下 FQDN 端口 之类的配置吧，这种都是环境问题。先在一个物理机 Linux 安装验证，避免一开始就用复杂的环境配置

**Comment by xzydyp** [comment]
+1
