### ISSUE TITLE
query issue in 3.0.1.0

### ISSUE THREAD

**Issue by crazyhub** [taosdata/TDengine#21496]
**taos 版本：3.0.1.0**
问题：相同的查询语句查出不一样的结果，并且出现乱码

taos> select * from information_schema.ins_databases where name='xh_sz_log' \G;
*************************** 1.row ***************************
                name: xh_sz_log
         create_time: 2023-05-15 12:08:27.167
             vgroups: 2
             ntables: 186
             replica: 1
              strict: off
            duration: 14400m
                keep: 129600m,129600m,129600m
              buffer: 96
            pagesize: 4
               pages: 256
             minrows: 100
             maxrows: 4096
                comp: 2
           precision: ns
              status: ready
          retentions: NULL
       single_stable: false
          cachemodel: none
           cachesize: 1
           wal_level: 1
    wal_fsync_period: 3000
wal_retention_period: 0
  wal_retention_size: 0
     wal_roll_period: 0
    wal_segment_size: 0
         sst_trigger: 8
Query OK, 1 rows in database (0.005671s)

taos> select       * from     xh_sz_log.scv_record_play_log where search_request_id='14073502247049254070' \G;
*************************** 1.row ***************************
               ts: 2023-05-18 13:51:23.139739757
          user_id: .3344.35.33.3344.35.33.3344.35.3
        user_name: 陈文
           org_id: NULL
         org_code: NULL
         org_name: 
    terminal_type: 
               ip: 
        camera_id: 1920x10801920x10801920x10801920x
      camera_code: NULL
      camera_name: H264H264H26
        starttime: 2023-05-17 09:00:00.000000000
          endtime: 2023-05-17 18:00:00.000000000
 record_starttime: 2023-05-17 09:00:00.000000000
   record_endtime: 2023-05-17 18:00:00.000000000
        op_result: 1
       error_info: NULL
         play_sec: 0
 signalling_delay: 382
     iframe_delay: 0
     stream_delay: 0
   video_coderate: -842150451.000000000
     video_encode: NULL
       resolution: NULL
    framelossrate: 0.000000000
        framerate: -842150451.000000000
     audio_encode: NULL
   audio_coderate: -842150451.000000000
         media_ip: 10.10.35.25
search_request_id: 14073502247049254070
        user_code: chenwen
Query OK, 1 rows in database (0.019053s)

taos> select       * from     xh_sz_log.scv_record_play_log where search_request_id='14073502247049254070' \G;
*************************** 1.row ***************************
               ts: 2023-05-18 13:51:23.139739757
          user_id: .3344.35.33.3344.35.33.3344.35.3
        user_name: 陈文
           org_id: NULL
         org_code: NULL
         org_name: 
    terminal_type: 2
               ip: 
        camera_id: 1920x10801920x10801920x10801920x
      camera_code: NULL
      camera_name: 107新路天桥
        starttime: 2023-05-17 09:00:00.000000000
          endtime: 2023-05-17 18:00:00.000000000
 record_starttime: 2023-05-17 09:00:00.000000000
   record_endtime: 2023-05-17 18:00:00.000000000
        op_result: 1
       error_info: NULL
         play_sec: 0
 signalling_delay: 382
     iframe_delay: 0
     stream_delay: 0
   video_coderate: -842150451.000000000
     video_encode: NULL
       resolution: NULL
    framelossrate: 0.000000000
        framerate: -842150451.000000000
     audio_encode: NULL
   audio_coderate: -842150451.000000000
         media_ip: 10.10.35.25
search_request_id: 14073502247049254070
        user_code: chenwen
Query OK, 1 rows in database (0.023044s)

taos> select       * from     xh_sz_log.scv_record_play_log where search_request_id='14073502247049254070' \G;
*************************** 1.row ***************************
               ts: 2023-05-18 13:51:23.139739757
          user_id: 1920x10801920x10801920x10801920x
        user_name: 陈文
           org_id: NULL
         org_code: NULL
         org_name: 
    terminal_type: 2
               ip: 
        camera_id: 10.10.35.2510.10.35.25190.
      camera_code: NULL
      camera_name: H264H264H26
        starttime: 2023-05-17 09:00:00.000000000
          endtime: 2023-05-17 18:00:00.000000000
 record_starttime: 2023-05-17 09:00:00.000000000
   record_endtime: 2023-05-17 18:00:00.000000000
        op_result: 1
       error_info: NULL
         play_sec: 0
 signalling_delay: 382
     iframe_delay: 0
     stream_delay: 0
   video_coderate: -842150451.000000000
     video_encode: NULL
       resolution: NULL
    framelossrate: 0.000000000
        framerate: -842150451.000000000
     audio_encode: NULL
   audio_coderate: -842150451.000000000
         media_ip: 10.10.35.25
search_request_id: 14073502247049254070
        user_code: chenwen
Query OK, 1 rows in database (0.014771s)

taos> select       * from     xh_sz_log.scv_record_play_log where search_request_id='14073502247049254070' \G;
*************************** 1.row ***************************
               ts: 2023-05-18 13:51:23.139739757
          user_id: .3344.35.33.3344.35.33.3344.35.3
        user_name: 陈文
           org_id: NULL
         org_code: NULL
         org_name: 
    terminal_type: 
               ip: 
        camera_id: 1920x10801920x10801920x10801920x
      camera_code: NULL
      camera_name: H264H264H26
        starttime: 2023-05-17 09:00:00.000000000
          endtime: 2023-05-17 18:00:00.000000000
 record_starttime: 2023-05-17 09:00:00.000000000
   record_endtime: 2023-05-17 18:00:00.000000000
        op_result: 1
       error_info: NULL
         play_sec: 0
 signalling_delay: 382
     iframe_delay: 0
     stream_delay: 0
   video_coderate: -842150451.000000000
     video_encode: NULL
       resolution: NULL
    framelossrate: 0.000000000
        framerate: -842150451.000000000
     audio_encode: NULL
   audio_coderate: -842150451.000000000
         media_ip: 10.10.35.25
search_request_id: 14073502247049254070
        user_code: chenwen
Query OK, 1 rows in database (0.015286s)

taos> select       * from     xh_sz_log.scv_record_play_log where search_request_id='14073502247049254070' \G;
*************************** 1.row ***************************
               ts: 2023-05-18 13:51:23.139739757
          user_id: 深圳市
        user_name: 陈文
           org_id: NULL
         org_code: NULL
         org_name: 
    terminal_type: 
               ip: 
        camera_id: 10801920x10801920x10801920x10801
      camera_code: NULL
      camera_name: 107新路天桥
        starttime: 2023-05-17 09:00:00.000000000
          endtime: 2023-05-17 18:00:00.000000000
 record_starttime: 2023-05-17 09:00:00.000000000
   record_endtime: 2023-05-17 18:00:00.000000000
        op_result: 1
       error_info: NULL
         play_sec: 0
 signalling_delay: 382
     iframe_delay: 0
     stream_delay: 0
   video_coderate: -842150451.000000000
     video_encode: NULL
       resolution: NULL
    framelossrate: 0.000000000
        framerate: -842150451.000000000
     audio_encode: NULL
   audio_coderate: -842150451.000000000
         media_ip: 10.10.35.25
search_request_id: 14073502247049254070
        user_code: chenwen
Query OK, 1 rows in database (0.014052s)

taos> select       * from     xh_sz_log.scv_record_play_log where search_request_id='14073502247049254070' \G;
*************************** 1.row ***************************
               ts: 2023-05-18 13:51:23.139739757
          user_id: 1920x10801920x10801920x10801920x
        user_name: 陈文
           org_id: NULL
         org_code: NULL
         org_name: _request_id
    terminal_type: 2
               ip: 
        camera_id: 10.10.35.2510.10.35.25190.
      camera_code: NULL
      camera_name: H264H264H26
        starttime: 2023-05-17 09:00:00.000000000
          endtime: 2023-05-17 18:00:00.000000000
 record_starttime: 2023-05-17 09:00:00.000000000
   record_endtime: 2023-05-17 18:00:00.000000000
        op_result: 1
       error_info: NULL
         play_sec: 0
 signalling_delay: 382
     iframe_delay: 0
     stream_delay: 0
   video_coderate: -842150451.000000000
     video_encode: NULL
       resolution: NULL
    framelossrate: 0.000000000
        framerate: -842150451.000000000
     audio_encode: NULL
   audio_coderate: -842150451.000000000
         media_ip: 10.10.35.25
search_request_id: 14073502247049254070
        user_code: chenwen
Query OK, 1 rows in database (0.014068s)

taos> select       * from     xh_sz_log.scv_record_play_log where search_request_id='14073502247049254070' \G;
*************************** 1.row ***************************
               ts: 2023-05-18 13:51:23.139739757
          user_id: .3344.35.33.3344.35.33.3344.35.3
        user_name: 陈文
           org_id: NULL
         org_code: NULL
         org_name: 
    terminal_type: 
               ip: 
        camera_id: 1920x10801920x10801920x10801920x
      camera_code: NULL
      camera_name: H264H264H26
        starttime: 2023-05-17 09:00:00.000000000
          endtime: 2023-05-17 18:00:00.000000000
 record_starttime: 2023-05-17 09:00:00.000000000
   record_endtime: 2023-05-17 18:00:00.000000000
        op_result: 1
       error_info: NULL
         play_sec: 0
 signalling_delay: 382
     iframe_delay: 0
     stream_delay: 0
   video_coderate: -842150451.000000000
     video_encode: NULL
       resolution: NULL
    framelossrate: 0.000000000
        framerate: -842150451.000000000
     audio_encode: NULL
   audio_coderate: -842150451.000000000
         media_ip: 10.10.35.25
search_request_id: 14073502247049254070
        user_code: chenwen
Query OK, 1 rows in database (0.019418s)

taos> select       * from     xh_sz_log.scv_record_play_log where search_request_id='14073502247049254070' \G;
*************************** 1.row ***************************
               ts: 2023-05-18 13:51:23.139739757
          user_id: 深圳市
        user_name: 陈文
           org_id: NULL
         org_code: NULL
         org_name: 
    terminal_type: 2
               ip: 1
        camera_id: 10801920x10801920x10801920x10801
      camera_code: NULL
      camera_name: 107新路天桥
        starttime: 2023-05-17 09:00:00.000000000
          endtime: 2023-05-17 18:00:00.000000000
 record_starttime: 2023-05-17 09:00:00.000000000
   record_endtime: 2023-05-17 18:00:00.000000000
        op_result: 1
       error_info: NULL
         play_sec: 0
 signalling_delay: 382
     iframe_delay: 0
     stream_delay: 0
   video_coderate: -842150451.000000000
     video_encode: NULL
       resolution: NULL
    framelossrate: 0.000000000
        framerate: -842150451.000000000
     audio_encode: NULL
   audio_coderate: -842150451.000000000
         media_ip: 10.10.35.25
search_request_id: 14073502247049254070
        user_code: chenwen
Query OK, 1 rows in database (0.014861s)

taos> select       * from     xh_sz_log.scv_record_play_log where search_request_id='14073502247049254070' \G;
*************************** 1.row ***************************
               ts: 2023-05-18 13:51:23.139739757
          user_id: 1920x10801920x10801920x10801920x
        user_name: 陈文
           org_id: NULL
         org_code: NULL
         org_name: 
    terminal_type: 
               ip: 
        camera_id: 10.10.35.2510.10.35.25190.
      camera_code: NULL
      camera_name: H264H264H26
        starttime: 2023-05-17 09:00:00.000000000
          endtime: 2023-05-17 18:00:00.000000000
 record_starttime: 2023-05-17 09:00:00.000000000
   record_endtime: 2023-05-17 18:00:00.000000000
        op_result: 1
       error_info: NULL
         play_sec: 0
 signalling_delay: 382
     iframe_delay: 0
     stream_delay: 0
   video_coderate: -842150451.000000000
     video_encode: NULL
       resolution: NULL
    framelossrate: 0.000000000
        framerate: -842150451.000000000
     audio_encode: NULL
   audio_coderate: -842150451.000000000
         media_ip: 10.10.35.25
search_request_id: 14073502247049254070
        user_code: chenwen
Query OK, 1 rows in database (0.014821s)

taos> select       * from     xh_sz_log.scv_record_play_log where search_request_id='14073502247049254070' \G;
*************************** 1.row ***************************
               ts: 2023-05-18 13:51:23.139739757
          user_id: .3344.35.33.3344.35.33.3344.35.3
        user_name: 陈文
           org_id: NULL
         org_code: NULL
         org_name: d
    terminal_type: 
               ip: 
        camera_id: 1920x10801920x10801920x10801920x
      camera_code: NULL
      camera_name: H264H264H26
        starttime: 2023-05-17 09:00:00.000000000
          endtime: 2023-05-17 18:00:00.000000000
 record_starttime: 2023-05-17 09:00:00.000000000
   record_endtime: 2023-05-17 18:00:00.000000000
        op_result: 1
       error_info: NULL
         play_sec: 0
 signalling_delay: 382
     iframe_delay: 0
     stream_delay: 0
   video_coderate: -842150451.000000000
     video_encode: NULL
       resolution: NULL
    framelossrate: 0.000000000
        framerate: -842150451.000000000
     audio_encode: NULL
   audio_coderate: -842150451.000000000
         media_ip: 10.10.35.25
search_request_id: 14073502247049254070
        user_code: chenwen
Query OK, 1 rows in database (0.015575s)

taos> select       * from     xh_sz_log.scv_record_play_log where search_request_id='14073502247049254070' \G;
*************************** 1.row ***************************
               ts: 2023-05-18 13:51:23.139739757
          user_id: .3344.35.33.3344.35.33.3344.35.3
        user_name: 陈文
           org_id: NULL
         org_code: NULL
         org_name: ame
    terminal_type: 2
               ip: 
        camera_id: 1920x10801920x10801920x10801920x
      camera_code: NULL
      camera_name: H264H264H26
        starttime: 2023-05-17 09:00:00.000000000
          endtime: 2023-05-17 18:00:00.000000000
 record_starttime: 2023-05-17 09:00:00.000000000
   record_endtime: 2023-05-17 18:00:00.000000000
        op_result: 1
       error_info: NULL
         play_sec: 0
 signalling_delay: 382
     iframe_delay: 0
     stream_delay: 0
   video_coderate: -842150451.000000000
     video_encode: NULL
       resolution: NULL
    framelossrate: 0.000000000
        framerate: -842150451.000000000
     audio_encode: NULL
   audio_coderate: -842150451.000000000
         media_ip: 10.10.35.25
search_request_id: 14073502247049254070
        user_code: chenwen
Query OK, 1 rows in database (0.020255s)

taos> select       * from     xh_sz_log.scv_record_play_log where search_request_id='14073502247049254070' \G;
*************************** 1.row ***************************
               ts: 2023-05-18 13:51:23.139739757
          user_id: 1920x10801920x10801920x10801920x
        user_name: 陈文
           org_id: NULL
         org_code: NULL
         org_name: 
    terminal_type: 
               ip: 
        camera_id: 10.10.35.2510.10.35.25190.
      camera_code: NULL
      camera_name: H264H264H26
        starttime: 2023-05-17 09:00:00.000000000
          endtime: 2023-05-17 18:00:00.000000000
 record_starttime: 2023-05-17 09:00:00.000000000
   record_endtime: 2023-05-17 18:00:00.000000000
        op_result: 1
       error_info: NULL
         play_sec: 0
 signalling_delay: 382
     iframe_delay: 0
     stream_delay: 0
   video_coderate: -842150451.000000000
     video_encode: NULL
       resolution: NULL
    framelossrate: 0.000000000
        framerate: -842150451.000000000
     audio_encode: NULL
   audio_coderate: -842150451.000000000
         media_ip: 10.10.35.25
search_request_id: 14073502247049254070
        user_code: chenwen
Query OK, 1 rows in database (0.013991s)

taos> select       * from     xh_sz_log.scv_record_play_log where search_request_id='14073502247049254070' \G;
*************************** 1.row ***************************
               ts: 2023-05-18 13:51:23.139739757
          user_id: .3344.35.33.3344.35.33.3344.35.3
        user_name: 陈文
           org_id: NULL
         org_code: NULL
         org_name: 
    terminal_type: 
               ip: 
        camera_id: 0.168.24.11210.10.35.25190.16
      camera_code: NULL
      camera_name: 107新路天桥
        starttime: 2023-05-17 09:00:00.000000000
          endtime: 2023-05-17 18:00:00.000000000
 record_starttime: 2023-05-17 09:00:00.000000000
   record_endtime: 2023-05-17 18:00:00.000000000
        op_result: 1
       error_info: NULL
         play_sec: 0
 signalling_delay: 382
     iframe_delay: 0
     stream_delay: 0
   video_coderate: -842150451.000000000
     video_encode: NULL
       resolution: NULL
    framelossrate: 0.000000000
        framerate: -842150451.000000000
     audio_encode: NULL
   audio_coderate: -842150451.000000000
         media_ip: 10.10.35.25
search_request_id: 14073502247049254070
        user_code: chenwen
Query OK, 1 rows in database (0.017580s)

taos> select       * from     xh_sz_log.scv_record_play_log where search_request_id='14073502247049254070' \G;
*************************** 1.row ***************************
               ts: 2023-05-18 13:51:23.139739757
          user_id: .3344.35.33.3344.35.33.3344.35.3
        user_name: 陈文
           org_id: NULL
         org_code: NULL
         org_name: 
    terminal_type: 
               ip: 
        camera_id: 1de4a1f3331d11ec8563a08cf8a69225
      camera_code: NULL
      camera_name: H264H264H26
        starttime: 2023-05-17 09:00:00.000000000
          endtime: 2023-05-17 18:00:00.000000000
 record_starttime: 2023-05-17 09:00:00.000000000
   record_endtime: 2023-05-17 18:00:00.000000000
        op_result: 1
       error_info: NULL
         play_sec: 0
 signalling_delay: 382
     iframe_delay: 0
     stream_delay: 0
   video_coderate: -842150451.000000000
     video_encode: NULL
       resolution: NULL
    framelossrate: 0.000000000
        framerate: -842150451.000000000
     audio_encode: NULL
   audio_coderate: -842150451.000000000
         media_ip: 10.10.35.25
search_request_id: 14073502247049254070
        user_code: chenwen
Query OK, 1 rows in database (0.016883s)

taos> select       * from     xh_sz_log.scv_record_play_log where search_request_id='14073502247049254070' \G;
*************************** 1.row ***************************
               ts: 2023-05-18 13:51:23.139739757
          user_id: .3344.35.33.3344.35.33.3344.35.3
        user_name: 陈文
           org_id: NULL
         org_code: NULL
         org_name: 
    terminal_type: 
               ip: 
        camera_id: 10.10.35.2510.10.35.25190.
      camera_code: NULL
      camera_name: H264H264H26
        starttime: 2023-05-17 09:00:00.000000000
          endtime: 2023-05-17 18:00:00.000000000
 record_starttime: 2023-05-17 09:00:00.000000000
   record_endtime: 2023-05-17 18:00:00.000000000
        op_result: 1
       error_info: NULL
         play_sec: 0
 signalling_delay: 382
     iframe_delay: 0
     stream_delay: 0
   video_coderate: -842150451.000000000
     video_encode: NULL
       resolution: NULL
    framelossrate: 0.000000000
        framerate: -842150451.000000000
     audio_encode: NULL
   audio_coderate: -842150451.000000000
         media_ip: 10.10.35.25
search_request_id: 14073502247049254070
        user_code: chenwen
Query OK, 1 rows in database (0.016896s)

taos> select       * from     xh_sz_log.scv_record_play_log where search_request_id='14073502247049254070' \G;
*************************** 1.row ***************************
               ts: 2023-05-18 13:51:23.139739757
          user_id: .3344.35.33.3344.35.33.3344.35.3
        user_name: 陈文
           org_id: NULL
         org_code: NULL
         org_name: 
    terminal_type: 
               ip: 
        camera_id: 0.168.24.11210.10.35.25190.16
      camera_code: NULL
      camera_name: 107新路天桥
        starttime: 2023-05-17 09:00:00.000000000
          endtime: 2023-05-17 18:00:00.000000000
 record_starttime: 2023-05-17 09:00:00.000000000
   record_endtime: 2023-05-17 18:00:00.000000000
        op_result: 1
       error_info: NULL
         play_sec: 0
 signalling_delay: 382
     iframe_delay: 0
     stream_delay: 0
   video_coderate: -842150451.000000000
     video_encode: NULL
       resolution: NULL
    framelossrate: 0.000000000
        framerate: -842150451.000000000
     audio_encode: NULL
   audio_coderate: -842150451.000000000
         media_ip: 10.10.35.25
search_request_id: 14073502247049254070
        user_code: chenwen
Query OK, 1 rows in database (0.015436s)

taos> select       * from     xh_sz_log.scv_record_play_log where search_request_id='14073502247049254070' \G;
*************************** 1.row ***************************
               ts: 2023-05-18 13:51:23.139739757
          user_id: .3344.35.33.3344.35.33.3344.35.3
        user_name: 陈文
           org_id: NULL
         org_code: NULL
         org_name: 
    terminal_type: 2
               ip: 
        camera_id: 1de4a1f3331d11ec8563a08cf8a69225
      camera_code: NULL
      camera_name: H264H264H26
        starttime: 2023-05-17 09:00:00.000000000
          endtime: 2023-05-17 18:00:00.000000000
 record_starttime: 2023-05-17 09:00:00.000000000
   record_endtime: 2023-05-17 18:00:00.000000000
        op_result: 1
       error_info: NULL
         play_sec: 0
 signalling_delay: 382
     iframe_delay: 0
     stream_delay: 0
   video_coderate: -842150451.000000000
     video_encode: NULL
       resolution: NULL
    framelossrate: 0.000000000
        framerate: -842150451.000000000
     audio_encode: NULL
   audio_coderate: -842150451.000000000
         media_ip: 10.10.35.25
search_request_id: 14073502247049254070
        user_code: chenwen
Query OK, 1 rows in database (0.014477s)

**Comment by yu285** [comment]
3.0.1.0 版本比较旧，麻烦更新到 3.0.4.2 再尝试。另，我没看到乱码，如果还有问题麻烦标注下

**Comment by crazyhub** [comment]
1、user_id  查询出来都不一样；2、camera_name 通过本地taos命令不会乱码，但是其他客户端工具包括程序会乱码

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
