### ISSUE TITLE
database can not  be found

### ISSUE THREAD

**Issue by llfeng** [taosdata/TDengine#21494]
**Bug Description**
正常使用过程中，数据库丢失。提示nested exception is java.sql.SQLException: TDengine ERROR (80000388): Database not exist

**To Reproduce**
无法复现

**Expected Behavior**

**Screenshots**
![image](https://github.com/taosdata/TDengine/assets/9448904/0637fc1d-36e8-43a9-a7ad-7b6c81b44a48)
![image](https://github.com/taosdata/TDengine/assets/9448904/cd88db0d-eb2b-4ea6-bf43-03f9958fbc8a)

![image](https://github.com/taosdata/TDengine/assets/9448904/e77a8ae9-30fe-4874-aac1-12c47087045c)
![image](https://github.com/taosdata/TDengine/assets/9448904/b76c4b5a-d078-4a4e-9219-aeeb3bedd647)
![image](https://github.com/taosdata/TDengine/assets/9448904/dfd67617-a7ed-4edc-86ce-74a07cb1f9b9)
![image](https://github.com/taosdata/TDengine/assets/9448904/9b8a6140-e057-4dd0-b32c-00066c43a569)

![image](https://github.com/taosdata/TDengine/assets/9448904/dc47fb42-1803-4eed-ac3d-f7f003b3037f)
![image](https://github.com/taosdata/TDengine/assets/9448904/26d7647c-fc25-46c8-ac09-4bbf2f2acd2d)
![image](https://github.com/taosdata/TDengine/assets/9448904/50a73e1b-6206-4537-9f80-c100ba29f306)
![image](https://github.com/taosdata/TDengine/assets/9448904/42f0dfdf-c418-4ab9-acd3-e4e5987b6f5c)
![image](https://github.com/taosdata/TDengine/assets/9448904/b14fc277-745f-422b-b8a1-e5f9cc1c70ff)
![image](https://github.com/taosdata/TDengine/assets/9448904/af489aeb-a12e-44ca-9566-64d17d5a8311)

**Environment (please complete the following information):**
 - OS: CentOS Linux release 7.9.2009
 - Memory：8G
 -  CPU： Intel(R) Xeon(R) Platinum 8369B CPU @ 2.70GHz
 - current Disk Space：
![image](https://github.com/taosdata/TDengine/assets/9448904/eca90b1c-8d91-4853-84ac-e2620321772c)

 - TDengine Version version: 3.0.1.4

**Additional Context**

**Comment by yu285** [comment]
硬盘问题可能性比较大。
