### ISSUE TITLE
float precision  issue 

### ISSUE THREAD

**Issue by wqqlwxp** [taosdata/TDengine#21509]
**Bug Description**
sum函数求和时，精度无法正常计算，存在精度误差，本身插入的数据才只有最多2位小数，资源类型定义的是float

**Screenshots**
![image](https://github.com/taosdata/TDengine/assets/13158701/eab0e5e8-bb22-4113-be50-611084cc9627)
![image](https://github.com/taosdata/TDengine/assets/13158701/e93cb61a-1aa0-4b8f-8963-cc313194d1d9)

**Comment by sangshuduo** [comment]
float 遵从 IEEE 754 格式，就是有精度误差

**Comment by yu285** [comment]
后续 round 函数 有计划支持保留小数位

企业版会推出 Decimal 数据类型
