### ISSUE TITLE
连续压测1个小时，数据库无法查询，直接报 DB error: No available disk (0.008191s)，日志报 05/27 14:33:26.666852 00642698 QRY ERROR QID:0x879554e9751c0303,TID:0x257,EID:0 qExecTask failed, code:8000020f - Query terminated

### ISSUE THREAD

**Issue by AndyWebJava** [taosdata/TDengine#21502]
连续压测1个小时，数据库无法查询，直接报 DB error: No available disk (0.008191s)，日志报 05/27 14:33:26.666852 00642698 QRY ERROR QID:0x879554e9751c0303,TID:0x257,EID:0 qExecTask failed, code:8000020f - Query terminated

![image](https://github.com/taosdata/TDengine/assets/22862566/0549e56d-a792-4902-b965-361231c90a39)

![image](https://github.com/taosdata/TDengine/assets/22862566/d5563711-e0fb-4398-ad11-12a094385551)

数据库已经无法执行查询操作，我认为是非常严重的Bug。。。

**Comment by AndyWebJava** [comment]
我的 TDengine 服务端版本是：3.0.4.1

**Comment by AndyWebJava** [comment]
建议官方抓紧排查修复，数据库已经无法执行查询操作。

**Comment by AndyWebJava** [comment]
我的磁盘可用空间还剩238GB，和磁盘关系不大。

![image](https://github.com/taosdata/TDengine/assets/22862566/da548079-ab05-4cdc-9a0e-085f737c0b5a)

**Comment by AndyWebJava** [comment]
我把数据库删除了后，也不能使用了。。

**Comment by AndyWebJava** [comment]
绝对致命Bug

**Comment by AndyWebJava** [comment]
![image](https://github.com/taosdata/TDengine/assets/22862566/60c20847-aad4-4652-b8a0-841988730c48)
官方没人理我我擦。。。

**Comment by AndyWebJava** [comment]
问题已排查到，是TD集群中的 test1 节点的 /root 目录，被 jmeter.log 日志占满（32G），删除后功能恢复正常，所以大家在压测的时候，也要观察/root目录下的日志文件占用情况，3节点集群只要有1个节点 /root 磁盘满了整个集群就不可用了，压测日志很容易把没有挂硬盘的磁盘撑满，我 / 目录只有50GB，山承包户jmeter.log文件，调整位置后恢复正常。

误会官方了，这个问题我关闭了。

**Comment by likang105030** [comment]
666
