### ISSUE TITLE
What if I don't want to merge data with the same timestamp?

### ISSUE THREAD

**Issue by gypinsistcn** [taosdata/TDengine#21506]
请问如果时间戳相同时，里面有不少数据，不能直接的合并，我该怎么做啊？比如下图的股票数据，时间戳相同时，有买有卖，不能直接合并啊
![Snipaste_2023-05-29_06-10-26](https://github.com/taosdata/TDengine/assets/83859656/1b860a52-3511-4211-8666-a73917d38f17)

**Comment by yu285** [comment]
这是交易所提供的数据吗。是什么精度的？

**Comment by gypinsistcn** [comment]
是的，这是交易所提供的数据，时间戳是毫秒级的，大约最小20毫秒一批，一批数据中有不少是相同时间戳的
