### ISSUE TITLE
手动扩集群后streams不正常运行且 drop stream 失败

### ISSUE THREAD

**Issue by zhangzhijian2010** [taosdata/TDengine#21524]
**Bug Description**
如下图: drop stream 一直失败!
<img width="1013" alt="image" src="https://github.com/taosdata/TDengine/assets/4935488/06bbd8c8-028d-42bd-8ad3-8cff9247b467">

**To Reproduce**
1. 扩展3个集群. 
2. 执行:  BALANCE VGROUP 命令. 
3. 查看stream 是否正常执行. 即看stream入的超表数是否正常. 
4. 发现3.入数据异常. 则想直接删掉stream并重建stream.
5. 执行 drop stream xxx .  后执行 show transactions \G;  命令. 返回执行失败次数统计及原因:  code:0x503(Vnode is closed or removed) msgType:stream-task-drop numOfEps:1 inUse:0 ep:0-XXX 

**Expected Behavior**
1. 扩集群且均衡vgroup 后 stream 能正常执行. 
2. 即使不正常执行. 需提供强删除 stream 命令也成. 

**Environment (please complete the following information):**
 - OS: [CentOS 7.0]
 - 6台 32G,4C,2T
 - 3.0.4.1

**Comment by sangshuduo** [comment]
最近会发布新版本 3.0.5.0，流计算有大幅改进，请使用新版本验证。
