### ISSUE TITLE
event query window bug

### ISSUE THREAD

**Issue by yuao1112** [taosdata/TDengine#21532]
**Bug Description**
![image](https://github.com/taosdata/TDengine/assets/24371179/bd117a8a-71fa-49e0-8758-a386982c5731)

**To Reproduce**
1. 创建test库
2. #创建超级表
CREATE STABLE st_temphumi (ts TIMESTAMP,temp INT,humi INT,ignite INT) TAGS (devicetype VARCHAR(32), subtype VARCHAR(32), mainversion TINYINT UNSIGNED, region VARCHAR(32), batchnumber VARCHAR(20));
3. #测试数据写入
INSERT INTO temphumi_0 USING test.st_temphumi (devicetype, subtype, mainversion, region, batchnumber) TAGS ("mts200", "eu", 1, "ap", "02000A2112") (ts,temp,humi,ignite) VALUES (1546774596000, 1000,1,0),(1546688196000, 2000,2,1),(1547206599000, 3000,3,1),(1546918596000, 4000,4,1);
4、 #查询结果异常

SELECT COUNT(1), _WDURATION FROM temphumi_0 event_window start with ignite > 0 end with ignite < 1 ;

SELECT COUNT(1), _WDURATION FROM temphumi_0 event_window start with ignite > -1 end with ignite < 1 ;

SELECT COUNT(1), _WDURATION FROM temphumi_0 event_window start with ignite > -1 end with ignite < 2 ;

**Environment (please complete the following information):**
 - docker 部署 tdengine
 - TDengine Version [e.g. 3.0.4.0]

**Comment by shenglian-zhou** [comment]
It is expected. Can you detail the exception? thanks

**Comment by yuao1112** [comment]
> 

SELECT COUNT(1), _WDURATION FROM temphumi_0 event_window start with ignite > 0 end with ignite < 1 ;
这条语句，应该查不到数据才对

SELECT COUNT(1), _WDURATION FROM temphumi_0 event_window start with ignite > -1 end with ignite < 1 ;
这条语句，实际上只要2019-01-06那条数据满足条件才对，但是查询出来的结果count数量为2 ，_WDURATION 为何算出来的结果是86400000

**Comment by shenglian-zhou** [comment]
clause _start with cond_ indicates the start of window, clause _end with cond_ indicates the end of window.

**Comment by yuao1112** [comment]
![image](https://github.com/taosdata/TDengine/assets/24371179/ef05f2cf-c905-47ba-afda-45ee1cb080b3)
