### ISSUE TITLE
05/30 10:01:25.015139 00000066 DND ERROR failed to open nodes since Sync one replica

### ISSUE THREAD

**Issue by jingnengchuhui** [taosdata/TDengine#21537]
05/30 10:01:24.012272 00000066 DND start to init dnode env
05/30 10:01:24.012331 00000066 DND dnode will run in single-process mode
05/30 10:01:24.013164 00000066 DND dnode env is initialized
05/30 10:01:24.013170 00000066 DND start to init service
05/30 10:01:24.013189 00000066 DND node:dnode, start to open
05/30 10:01:24.013209 00000066 UTL worker:dnode-mgmt is initialized, min:1 max:1
05/30 10:01:24.013347 00000075 UDF start to init udfd
05/30 10:01:24.014627 00000075 UDF ERROR can not spawn udfd. path: taosd/udfd, error: no such file or directory
05/30 10:01:24.014845 00000066 UDF udfd is cleaned up after spawn err
05/30 10:01:24.014858 00000066 DND ERROR failed to start udfd
05/30 10:01:24.014865 00000066 DND node:dnode, has been opened
05/30 10:01:24.014888 00000066 DND node:mnode, start to open
05/30 10:01:24.014929 00000066 WAL wal module is initialized, rsetId:3
05/30 10:01:24.015153 00000066 DND mnode start to open
05/30 10:01:24.016507 00000066 MND start to open mnode sync, standby:0
05/30 10:01:24.016688 00000066 SYN vgId:1, sync node use snapshot
05/30 10:01:24.016736 00000066 UTL worker:mnode-query is initialized, min:4 max:4
05/30 10:01:24.016838 00000066 UTL worker:mnode-fetch is initialized, min:1 max:1
05/30 10:01:24.016896 00000066 UTL worker:mnode-read is initialized, min:4 max:4
05/30 10:01:24.016992 00000066 UTL worker:mnode-write is initialized, min:1 max:1
05/30 10:01:24.017021 00000066 UTL worker:mnode-sync is initialized, min:1 max:1
05/30 10:01:24.017053 00000066 UTL worker:mnode-monitor is initialized, min:1 max:1
05/30 10:01:24.017089 00000066 DND node:mnode, has been opened
05/30 10:01:24.017100 00000066 DND node:vnode, start to open
05/30 10:01:24.017260 00000066 UTL worker:vnode-query is initialized, min:128 max:128
05/30 10:01:24.017270 00000066 UTL worker:vnode-stream is initialized, min:16 max:16
05/30 10:01:24.017283 00000066 UTL worker:vnode-mgmt is initialized, min:1 max:1
05/30 10:01:24.017309 00000066 UTL worker:vnode-monitor is initialized, min:1 max:1
05/30 10:01:24.017470 00000066 DND open 2 vnodes with 32 threads
05/30 10:01:24.024121 00000099 TSD ERROR vgId:2, tsdb scan and try fix fs failed since Data file corrupted
05/30 10:01:24.024144 00000099 TSD ERROR vgId:2, tsdb fs open failed since Data file corrupted
05/30 10:01:24.024159 00000099 VND ERROR vgId:2, failed to open vnode tsdb since No such file or directory
05/30 10:01:24.024245 00000099 DND ERROR vgId:2, failed to open vnode by thread:0
05/30 10:01:24.026227 00000100 SYN vgId:3, sync node use snapshot
05/30 10:01:24.032798 00000066 DND ERROR there are total vnodes:2, opened:1
05/30 10:01:24.032823 00000066 DND ERROR failed to open vnode since success
05/30 10:01:24.032829 00000066 DND ERROR failed to init vnodes-mgmt since success
05/30 10:01:24.032834 00000066 DND start to close all vnodes
05/30 10:01:24.032856 00000066 VND vgId:3, start to commit, commit ID:318 version:5443971
05/30 10:01:24.033293 00000066 VND vgId:3, vnode info is saved, fname:/var/lib/taos/vnode/vnode3/vnode_tmp.json
05/30 10:01:24.033428 00000066 VND vgId:3, vnode info is committed
05/30 10:01:24.033627 00000066 VND vgId:3, commit end
05/30 10:01:24.037254 00000066 DND total vnodes:1 are all closed
05/30 10:01:25.015103 00000066 WAL wal module is cleaned up
05/30 10:01:25.015124 00000066 DND ERROR node:vnode, failed to open since Sync one replica
05/30 10:01:25.015135 00000066 DND ERROR node:vnode, failed to open since Sync one replica
05/30 10:01:25.015139 00000066 DND ERROR failed to open nodes since Sync one replica
05/30 10:01:25.015147 00000066 DND shutting down the service
05/30 10:01:25.217274 00000066 UDF udfd start to stop, need cleanup:0, spawn err:-2
05/30 10:01:25.516268 00000066 DND dnode env is cleaned up

**Comment by yu285** [comment]
应该是做过什么配置改动吧。

另外 3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
