### ISSUE TITLE
taosd start failed

### ISSUE THREAD

**Issue by sunyymq** [taosdata/TDengine#21533]
taosd -V
community version: 3.0.1.3 compatible_version: 3.0.0.0
gitinfo: b6563e4920d7e60b9735fb7fa2afff38f8dea8eb
buildInfo: Built at 2022-09-27 15:28

after systemctl start taosd,it's show failed

● taosd.service - TDengine server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: enabled)
   Active: failed (Result: core-dump) since Tue 2023-05-30 16:10:49 CST; 221ms ago
  Process: 1278348 ExecStart=/usr/bin/taosd (code=dumped, signal=ABRT)
  Process: 1278341 ExecStartPre=/usr/local/taos/bin/startPre.sh (code=exited, status=0/SUCCESS)
 Main PID: 1278348 (code=dumped, signal=ABRT)

5月 30 16:10:49 iZuf6aqb07dsf4vlur6z91Z systemd[1]: taosd.service: Service RestartSec=100ms expired, scheduling restart.
5月 30 16:10:49 iZuf6aqb07dsf4vlur6z91Z systemd[1]: taosd.service: Scheduled restart job, restart counter is at 3.
5月 30 16:10:49 iZuf6aqb07dsf4vlur6z91Z systemd[1]: Stopped TDengine server service.
5月 30 16:10:49 iZuf6aqb07dsf4vlur6z91Z systemd[1]: taosd.service: Start request repeated too quickly.
5月 30 16:10:49 iZuf6aqb07dsf4vlur6z91Z systemd[1]: taosd.service: Failed with result 'core-dump'.
5月 30 16:10:49 iZuf6aqb07dsf4vlur6z91Z systemd[1]: Failed to start TDengine server service.

manual start taosd

05/30 16:12:14.848394 01278576 UTL fail to load apoll url
05/30 16:12:14.848426 01278576 UTL load from cfg file /etc/taos/taos.cfg success
05/30 16:12:14.848432 01278576 UTL failed to load env file: .env
05/30 16:12:14.848438 01278576 UTL load from env variables cfg success
05/30 16:12:14.848666 01278576 UTL fail to load apoll url
05/30 16:12:14.848706 01278576 UTL load from cfg file /etc/taos/taos.cfg success
05/30 16:12:14.848714 01278576 UTL failed to load env file: .env
05/30 16:12:14.848721 01278576 UTL load from env variables cfg success
05/30 16:12:14.848804 01278576 UTL                      global config
05/30 16:12:14.848807 01278576 UTL =================================================================
05/30 16:12:14.848817 01278576 UTL default      firstEp                  iZuf6aqb07dsf4vlur6z91Z:6030
05/30 16:12:14.848822 01278576 UTL default      secondEp                 iZuf6aqb07dsf4vlur6z91Z:6030
05/30 16:12:14.848827 01278576 UTL default      fqdn                     iZuf6aqb07dsf4vlur6z91Z
05/30 16:12:14.848832 01278576 UTL default      serverPort               6030
05/30 16:12:14.848837 01278576 UTL default      tempDir                  /tmp
05/30 16:12:14.848842 01278576 UTL default      minimalTmpDirGB          1.00
05/30 16:12:14.848850 01278576 UTL default      shellActivityTimer       3
05/30 16:12:14.848855 01278576 UTL default      compressMsgSize          -1
05/30 16:12:14.848859 01278576 UTL default      compressColData          -1
05/30 16:12:14.848864 01278576 UTL default      queryPolicy              1
05/30 16:12:14.848869 01278576 UTL default      querySmaOptimize         0
05/30 16:12:14.848874 01278576 UTL default      queryPlannerTrace        0
05/30 16:12:14.848879 01278576 UTL default      queryNodeChunkSize       32768
05/30 16:12:14.848884 01278576 UTL default      queryUseNodeAllocator    1
05/30 16:12:14.848888 01278576 UTL default      smlChildTableName
05/30 16:12:14.848891 01278576 UTL default      smlTagName               _tag_null
05/30 16:12:14.848895 01278576 UTL default      smlDataFormat            1
05/30 16:12:14.848900 01278576 UTL default      numOfTaskQueueThreads    4
05/30 16:12:14.848904 01278576 UTL default      dataDir                  /var/lib/taos
05/30 16:12:14.848909 01278576 UTL default      minimalDataDirGB         2.00
05/30 16:12:14.848915 01278576 UTL cfg_file     supportVnodes            24
05/30 16:12:14.848920 01278576 UTL default      maxShellConns            50000
05/30 16:12:14.848925 01278576 UTL default      statusInterval           1
05/30 16:12:14.848929 01278576 UTL default      minSlidingTime           10
05/30 16:12:14.848934 01278576 UTL default      minIntervalTime          1
05/30 16:12:14.848939 01278576 UTL default      maxNumOfDistinctRes      10000000
05/30 16:12:14.848944 01278576 UTL default      countAlwaysReturnValue   1
05/30 16:12:14.848949 01278576 UTL default      queryBufferSize          -1
05/30 16:12:14.848955 01278576 UTL default      printAuth                0
05/30 16:12:14.848960 01278576 UTL default      multiProcess             0
05/30 16:12:14.848965 01278576 UTL default      mnodeShmSize             20972544
05/30 16:12:14.848970 01278576 UTL default      vnodeShmSize             104858624
05/30 16:12:14.848975 01278576 UTL default      qnodeShmSize             41944064
05/30 16:12:14.848980 01278576 UTL default      snodeShmSize             41944064
05/30 16:12:14.848985 01278576 UTL default      bnodeShmSize             41944064
05/30 16:12:14.848990 01278576 UTL default      numOfShmThreads          1
05/30 16:12:14.848995 01278576 UTL default      numOfRpcThreads          2
05/30 16:12:14.849000 01278576 UTL default      numOfCommitThreads       2
05/30 16:12:14.849005 01278576 UTL default      numOfMnodeReadThreads    1
05/30 16:12:14.849010 01278576 UTL default      numOfVnodeQueryThreads   8
05/30 16:12:14.849014 01278576 UTL default      numOfVnodeStreamThreads  4
05/30 16:12:14.849018 01278576 UTL default      numOfVnodeFetchThreads   4
05/30 16:12:14.849024 01278576 UTL default      numOfVnodeWriteThreads   4
05/30 16:12:14.849031 01278576 UTL default      numOfVnodeSyncThreads    16
05/30 16:12:14.849036 01278576 UTL default      numOfVnodeRsmaThreads    4
05/30 16:12:14.849043 01278576 UTL default      numOfQnodeQueryThreads   8
05/30 16:12:14.849056 01278576 UTL default      numOfSnodeSharedThreads  2
05/30 16:12:14.849066 01278576 UTL default      numOfSnodeUniqueThreads  2
05/30 16:12:14.849069 01278576 UTL default      rpcQueueMemoryAllowed    1622122905
05/30 16:12:14.849075 01278576 UTL default      monitor                  1
05/30 16:12:14.849079 01278576 UTL default      monitorInterval          30
05/30 16:12:14.849084 01278576 UTL default      monitorFqdn
05/30 16:12:14.849088 01278576 UTL default      monitorPort              6043
05/30 16:12:14.849092 01278576 UTL default      monitorMaxLogs           100
05/30 16:12:14.849096 01278576 UTL default      monitorComp              0
05/30 16:12:14.849100 01278576 UTL default      telemetryReporting       1
05/30 16:12:14.849105 01278576 UTL default      telemetryInterval        43200
05/30 16:12:14.849109 01278576 UTL default      telemetryServer          telemetry.taosdata.com
05/30 16:12:14.849113 01278576 UTL default      telemetryPort            80
05/30 16:12:14.849117 01278576 UTL default      transPullupInterval      2
05/30 16:12:14.849120 01278576 UTL default      mqRebalanceInterval      2
05/30 16:12:14.849124 01278576 UTL default      ttlUnit                  86400
05/30 16:12:14.849127 01278576 UTL default      ttlPushInterval          86400
05/30 16:12:14.849131 01278576 UTL default      uptimeInterval           300
05/30 16:12:14.849134 01278576 UTL default      queryRsmaTolerance       1000
05/30 16:12:14.849138 01278576 UTL default      udf                      1
05/30 16:12:14.849141 01278576 UTL default      udfdResFuncs
05/30 16:12:14.849145 01278576 UTL default      configDir                /etc/taos
05/30 16:12:14.849148 01278576 UTL default      scriptDir                /etc/taos
05/30 16:12:14.849152 01278576 UTL default      logDir                   /var/log/taos
05/30 16:12:14.849155 01278576 UTL default      minimalLogDirGB          1.00
05/30 16:12:14.849159 01278576 UTL default      numOfLogLines            10000000
05/30 16:12:14.849163 01278576 UTL default      asyncLog                 1
05/30 16:12:14.849167 01278576 UTL default      logKeepDays              0
05/30 16:12:14.849170 01278576 UTL default      debugFlag                0
05/30 16:12:14.849174 01278576 UTL default      simDebugFlag             143
05/30 16:12:14.849177 01278576 UTL default      tmrDebugFlag             131
05/30 16:12:14.849181 01278576 UTL default      uDebugFlag               131
05/30 16:12:14.849184 01278576 UTL default      rpcDebugFlag             131
05/30 16:12:14.849188 01278576 UTL default      jniDebugFlag             131
05/30 16:12:14.849191 01278576 UTL default      qDebugFlag               131
05/30 16:12:14.849195 01278576 UTL default      cDebugFlag               131
05/30 16:12:14.849198 01278576 UTL default      dDebugFlag               135
05/30 16:12:14.849202 01278576 UTL default      vDebugFlag               135
05/30 16:12:14.849205 01278576 UTL default      mDebugFlag               135
05/30 16:12:14.849209 01278576 UTL default      wDebugFlag               135
05/30 16:12:14.849212 01278576 UTL default      sDebugFlag               135
05/30 16:12:14.849216 01278576 UTL default      tsdbDebugFlag            131
05/30 16:12:14.849219 01278576 UTL default      tqDebugFlag              135
05/30 16:12:14.849223 01278576 UTL default      fsDebugFlag              135
05/30 16:12:14.849226 01278576 UTL default      udfDebugFlag             135
05/30 16:12:14.849230 01278576 UTL default      smaDebugFlag             131
05/30 16:12:14.849233 01278576 UTL default      idxDebugFlag             135
05/30 16:12:14.849237 01278576 UTL default      tdbDebugFlag             131
05/30 16:12:14.849240 01278576 UTL default      metaDebugFlag            135
05/30 16:12:14.849244 01278576 UTL default      timezone                 Asia/Shanghai (CST, +0800)
05/30 16:12:14.849248 01278576 UTL default      locale                   zh_CN.UTF-8
05/30 16:12:14.849251 01278576 UTL default      charset                  UTF-8
05/30 16:12:14.849254 01278576 UTL default      enableCoreFile           1
05/30 16:12:14.849261 01278576 UTL default      numOfCores               4.00
05/30 16:12:14.849264 01278576 UTL default      openMax                  65535
05/30 16:12:14.849268 01278576 UTL default      streamMax                16
05/30 16:12:14.849272 01278576 UTL default      pageSizeKB               4
05/30 16:12:14.849275 01278576 UTL default      totalMemoryKB            15841044
05/30 16:12:14.849279 01278576 UTL default      os sysname               Linux
05/30 16:12:14.849282 01278576 UTL default      os nodename              iZuf6aqb07dsf4vlur6z91Z
05/30 16:12:14.849286 01278576 UTL default      os release               5.10.134-12.2.al8.x86_64
05/30 16:12:14.849289 01278576 UTL default      os version               #1 SMP Thu Oct 27 10:07:15 CST 2022
05/30 16:12:14.849293 01278576 UTL default      os machine               x86_64
05/30 16:12:14.849297 01278576 UTL default      version                  3.0.1.3
05/30 16:12:14.849300 01278576 UTL default      compatible_version       3.0.0.0
05/30 16:12:14.849304 01278576 UTL default      gitinfo                  b6563e4920d7e60b9735fb7fa2afff38f8dea8eb
05/30 16:12:14.849307 01278576 UTL default      buildinfo                Built at 2022-09-27 15:28
05/30 16:12:14.849311 01278576 UTL =================================================================
05/30 16:12:14.850925 01278576 DND start to init dnode env
05/30 16:12:14.850969 01278576 DND dnode will run in single-process mode
05/30 16:12:14.851997 01278576 DND dnode env is initialized
05/30 16:12:14.852006 01278576 DND start to init service
05/30 16:12:14.852020 01278576 DND node:dnode, start to open
05/30 16:12:14.852026 01278576 UTL worker:dnode-mgmt is initialized, min:1 max:1
05/30 16:12:14.852159 01278586 UDF start to init udfd
05/30 16:12:14.852755 01278586 UDF udfd is initialized
05/30 16:12:14.852798 01278576 DND node:dnode, has been opened
05/30 16:12:14.852825 01278576 DND node:mnode, start to open
05/30 16:12:14.852892 01278576 WAL wal module is initialized, rsetId:3
05/30 16:12:14.853582 01278576 DND mnode start to open
05/30 16:12:14.853590 01278576 MND start to open mnode in /var/lib/taos/mnode
05/30 16:12:14.857487 01278576 MND mnode-wal is initialized
05/30 16:12:14.857502 01278576 MND start to init sdb in /var/lib/taos/mnode
05/30 16:12:14.857516 01278576 MND sdb init success
05/30 16:12:14.857520 01278576 MND mnode-sdb is initialized
05/30 16:12:14.857534 01278576 MND sdb table:trans is initialized
05/30 16:12:14.857543 01278576 MND mnode-trans is initialized
05/30 16:12:14.857554 01278576 MND sdb table:cluster is initialized
05/30 16:12:14.857557 01278576 MND mnode-cluster is initialized
05/30 16:12:14.857564 01278576 MND sdb table:mnode is initialized
05/30 16:12:14.857567 01278576 MND mnode-mnode is initialized
05/30 16:12:14.857575 01278576 MND sdb table:qnode is initialized
05/30 16:12:14.857578 01278576 MND mnode-qnode is initialized
05/30 16:12:14.857586 01278576 MND sdb table:snode is initialized
05/30 16:12:14.857589 01278576 MND mnode-snode is initialized
05/30 16:12:14.857598 01278576 MND sdb table:bnode is initialized
05/30 16:12:14.857602 01278576 MND mnode-bnode is initialized
05/30 16:12:14.857608 01278576 MND sdb table:dnode is initialized
05/30 16:12:14.857611 01278576 MND mnode-dnode is initialized
05/30 16:12:14.857620 01278576 MND sdb table:user is initialized
05/30 16:12:14.857623 01278576 MND mnode-user is initialized
05/30 16:12:14.857629 01278576 MND mnode-grant is initialized
05/30 16:12:14.857636 01278576 MND mnode-privilege is initialized
05/30 16:12:14.857643 01278576 MND sdb table:acct is initialized
05/30 16:12:14.857646 01278576 MND mnode-acct is initialized
05/30 16:12:14.857656 01278576 MND sdb table:stream is initialized
05/30 16:12:14.857659 01278576 MND mnode-stream is initialized
05/30 16:12:14.857667 01278576 MND sdb table:topic is initialized
05/30 16:12:14.857670 01278576 MND mnode-topic is initialized
05/30 16:12:14.857677 01278576 MND sdb table:consumer is initialized
05/30 16:12:14.857681 01278576 MND mnode-consumer is initialized
05/30 16:12:14.857688 01278576 MND sdb table:subscribe is initialized
05/30 16:12:14.857691 01278576 MND mnode-subscribe is initialized
05/30 16:12:14.857698 01278576 MND sdb table:offset is initialized
05/30 16:12:14.857701 01278576 MND mnode-offset is initialized
05/30 16:12:14.857708 01278576 MND sdb table:vgroup is initialized
05/30 16:12:14.857711 01278576 MND mnode-vgroup is initialized
05/30 16:12:14.857723 01278576 MND sdb table:stb is initialized
05/30 16:12:14.857726 01278576 MND mnode-stb is initialized
05/30 16:12:14.857734 01278576 MND sdb table:sma is initialized
05/30 16:12:14.857737 01278576 MND mnode-sma is initialized
05/30 16:12:14.857771 01278576 MND mnode-infos is initialized
05/30 16:12:14.857785 01278576 MND mnode-perfs is initialized
05/30 16:12:14.857794 01278576 MND sdb table:db is initialized
05/30 16:12:14.857799 01278576 MND mnode-db is initialized
05/30 16:12:14.857805 01278576 MND sdb table:func is initialized
05/30 16:12:14.857808 01278576 MND mnode-func is initialized
05/30 16:12:14.857816 01278576 MND start to reset sdb
05/30 16:12:14.857882 01278576 MND sdb:trans is reset
05/30 16:12:14.857885 01278576 MND sdb:cluster is reset
05/30 16:12:14.857889 01278576 MND sdb:mnode is reset
05/30 16:12:14.857892 01278576 MND sdb:qnode is reset
05/30 16:12:14.857896 01278576 MND sdb:snode is reset
05/30 16:12:14.857902 01278576 MND sdb:bnode is reset
05/30 16:12:14.857943 01278576 MND sdb:dnode is reset
05/30 16:12:14.857946 01278576 MND sdb:user is reset
05/30 16:12:14.857949 01278576 MND sdb:acct is reset
05/30 16:12:14.857952 01278576 MND sdb:stream is reset
05/30 16:12:14.857957 01278576 MND sdb:offset is reset
05/30 16:12:14.857960 01278576 MND sdb:subscribe is reset
05/30 16:12:14.857963 01278576 MND sdb:consumer is reset
05/30 16:12:14.857967 01278576 MND sdb:topic is reset
05/30 16:12:14.857971 01278576 MND sdb:vgroup is reset
05/30 16:12:14.857975 01278576 MND sdb:sma is reset
05/30 16:12:14.857980 01278576 MND sdb:stb is reset
05/30 16:12:14.857986 01278576 MND sdb:db is reset
05/30 16:12:14.857989 01278576 MND sdb:func is reset
05/30 16:12:14.857993 01278576 MND sdb reset success
05/30 16:12:14.857997 01278576 MND start to read sdb file:/var/lib/taos/mnode/data/sdb.data
05/30 16:12:14.860718 01278576 MND read sdb file:/var/lib/taos/mnode/data/sdb.data success, commit index:211899 term:14 config:-1
05/30 16:12:14.860749 01278576 MND mnode-sdb is initialized
05/30 16:12:14.860877 01278576 MND mnode-profile is initialized
05/30 16:12:14.860927 01278576 MND mnode-show is initialized
05/30 16:12:14.861160 01278576 MND mnode-query is initialized
05/30 16:12:14.861169 01278576 MND vgId:1, start to open sync, standby:0
05/30 16:12:14.861281 01278576 SYN vgId:1, sync node use snapshot
05/30 16:12:14.861292 01278576 MND mnode-sync is opened, id:2
05/30 16:12:14.861297 01278576 MND mnode-sync is initialized
05/30 16:12:14.861306 01278576 MND mnode-telem is initialized
05/30 16:12:14.861312 01278576 MND mnode open successfully
05/30 16:12:14.861317 01278576 UTL worker:mnode-query is initialized, min:4 max:4
05/30 16:12:14.861449 01278576 UTL worker:mnode-fetch is initialized, min:1 max:1
05/30 16:12:14.861888 01278576 UTL worker:mnode-read is initialized, min:1 max:1
05/30 16:12:14.861923 01278576 UTL worker:mnode-write is initialized, min:1 max:1
05/30 16:12:14.861956 01278576 UTL worker:mnode-sync is initialized, min:1 max:1
05/30 16:12:14.861998 01278576 UTL worker:mnode-monitor is initialized, min:1 max:1
05/30 16:12:14.862038 01278576 DND node:mnode, has been opened
05/30 16:12:14.862058 01278576 DND node:vnode, start to open
05/30 16:12:14.862166 01278576 UTL worker:vnode-query is initialized, min:8 max:8
05/30 16:12:14.862174 01278576 UTL worker:vnode-stream is initialized, min:4 max:4
05/30 16:12:14.862180 01278576 UTL worker:vnode-mgmt is initialized, min:1 max:1
05/30 16:12:14.862222 01278576 UTL worker:vnode-monitor is initialized, min:1 max:1
05/30 16:12:14.862415 01278576 DND open 14 vnodes with 2 threads
05/30 16:12:14.867458 01278608 SYN vgId:76, sync node use snapshot
05/30 16:12:14.868365 01278609 SYN vgId:77, sync node use snapshot
05/30 16:12:14.907361 01278609 SYN vgId:79, sync node use snapshot
05/30 16:12:14.908720 01278608 SYN vgId:78, sync node use snapshot
05/30 16:12:14.910463 01278609 SYN vgId:81, sync node use snapshot
05/30 16:12:14.911782 01278608 SYN vgId:80, sync node use snapshot
05/30 16:12:14.915151 01278609 SYN vgId:83, sync node use snapshot
05/30 16:12:14.916117 01278608 SYN vgId:82, sync node use snapshot
05/30 16:12:14.919226 01278609 SYN vgId:85, sync node use snapshot
05/30 16:12:14.920271 01278608 SYN vgId:84, sync node use snapshot
05/30 16:12:14.921368 01278609 SYN vgId:87, sync node use snapshot
05/30 16:12:14.922119 01278608 SYN vgId:86, sync node use snapshot
05/30 16:12:14.923269 01278609 SYN vgId:91, sync node use snapshot
05/30 16:12:14.924276 01278608 SYN vgId:90, sync node use snapshot
05/30 16:12:14.924400 01278576 DND successfully opened 14 vnodes
05/30 16:12:14.924419 01278576 UDF get dnodeId:1 from env, pipe path:/var/lib/taos/.udfd.sock.1
05/30 16:12:14.924476 01278576 UDF udfc initialized
05/30 16:12:14.924482 01278576 DND node:vnode, has been opened
05/30 16:12:14.926797 01278576 MND vgId:1, become leader
05/30 16:12:14.926923 01278576 MND trans:105944, is proposed, saved:0 code:0x0, apply index:211900 term:14 config:-1 role:leader raw:0x55987cf597a3
05/30 16:12:14.926979 01278576 MND trans:105944, execute in mnode which not leader
05/30 16:12:14.926983 01278576 MND trans:105944, continue to execute, stage:prepare
05/30 16:12:14.926987 01278576 MND trans:105944, stage from prepare to redoAction
05/30 16:12:14.926991 01278576 MND trans:105944, continue to execute, stage:redoAction
05/30 16:12:14.927031 01278576 MND ERROR failed to execute redoActions since:Database not ready, code:0x80000014
05/30 16:12:14.927102 01278576 MND trans:105944, is proposed, saved:0 code:0x0, apply index:211901 term:14 config:-1 role:leader raw:0x55987cf597a3
05/30 16:12:14.927145 01278576 MND trans:105944, execute in mnode which not leader
05/30 16:12:14.927148 01278576 MND trans:105944, continue to execute, stage:redoAction
05/30 16:12:14.927153 01278576 MND ERROR failed to execute redoActions since:Database not ready, code:0x80000014
05/30 16:12:14.927202 01278576 MND trans:105945, is proposed, saved:0 code:0x0, apply index:211902 term:14 config:-1 role:leader raw:0x55987cf597a3
05/30 16:12:14.927212 01278576 MND trans:105945, execute in mnode which not leader
05/30 16:12:14.927215 01278576 MND trans:105945, continue to execute, stage:prepare
05/30 16:12:14.927219 01278576 MND trans:105945, stage from prepare to redoAction
05/30 16:12:14.927225 01278576 MND trans:105945, continue to execute, stage:redoAction
05/30 16:12:14.927229 01278576 MND ERROR failed to execute redoActions since:Database not ready, code:0x80000014
05/30 16:12:14.927278 01278576 MND trans:105945, is proposed, saved:0 code:0x0, apply index:211903 term:14 config:-1 role:leader raw:0x55987cf597a3
05/30 16:12:14.927322 01278576 MND trans:105945, execute in mnode which not leader
05/30 16:12:14.927326 01278576 MND trans:105945, continue to execute, stage:redoAction
05/30 16:12:14.927331 01278576 MND ERROR failed to execute redoActions since:Database not ready, code:0x80000014
05/30 16:12:14.927399 01278576 MND trans:105946, is proposed, saved:0 code:0x0, apply index:211904 term:14 config:-1 role:leader raw:0x55987cf597a3
05/30 16:12:14.927409 01278576 MND trans:105946, execute in mnode which not leader
05/30 16:12:14.927412 01278576 MND trans:105946, continue to execute, stage:prepare
05/30 16:12:14.927416 01278576 MND trans:105946, stage from prepare to redoAction
05/30 16:12:14.927420 01278576 MND trans:105946, continue to execute, stage:redoAction
05/30 16:12:14.927424 01278576 MND ERROR failed to execute redoActions since:Database not ready, code:0x80000014
05/30 16:12:14.927478 01278576 MND trans:105946, is proposed, saved:0 code:0x0, apply index:211905 term:14 config:-1 role:leader raw:0x55987cf597a3
05/30 16:12:14.927526 01278576 MND trans:105946, execute in mnode which not leader
05/30 16:12:14.927529 01278576 MND trans:105946, continue to execute, stage:redoAction
05/30 16:12:14.927533 01278576 MND ERROR failed to execute redoActions since:Database not ready, code:0x80000014
05/30 16:12:14.927583 01278576 MND trans:105947, is proposed, saved:0 code:0x0, apply index:211906 term:14 config:-1 role:leader raw:0x55987cf4c1c3
05/30 16:12:14.927604 01278576 MND trans:105947, execute in mnode which not leader
05/30 16:12:14.927607 01278576 MND trans:105947, continue to execute, stage:prepare
05/30 16:12:14.927611 01278576 MND trans:105947, stage from prepare to redoAction
05/30 16:12:14.927615 01278576 MND trans:105947, continue to execute, stage:redoAction
05/30 16:12:14.927619 01278576 MND ERROR failed to execute redoActions since:Database not ready, code:0x80000014
05/30 16:12:14.927666 01278576 MND trans:105947, is proposed, saved:0 code:0x0, apply index:211907 term:14 config:-1 role:leader raw:0x55987cf9ab33
05/30 16:12:14.927710 01278576 MND trans:105947, execute in mnode which not leader
05/30 16:12:14.927713 01278576 MND trans:105947, continue to execute, stage:redoAction
05/30 16:12:14.927717 01278576 MND ERROR failed to execute redoActions since:Database not ready, code:0x80000014
05/30 16:12:14.927766 01278576 MND trans:105948, is proposed, saved:0 code:0x0, apply index:211908 term:14 config:-1 role:leader raw:0x55987cf4c1c3
05/30 16:12:14.927777 01278576 MND trans:105948, execute in mnode which not leader
05/30 16:12:14.927780 01278576 MND trans:105948, continue to execute, stage:prepare
05/30 16:12:14.927783 01278576 MND trans:105948, stage from prepare to redoAction
05/30 16:12:14.927787 01278576 MND trans:105948, continue to execute, stage:redoAction
05/30 16:12:14.927791 01278576 MND ERROR failed to execute redoActions since:Database not ready, code:0x80000014
05/30 16:12:14.927838 01278576 MND trans:105948, is proposed, saved:0 code:0x0, apply index:211909 term:14 config:-1 role:leader raw:0x55987cf9ab33
05/30 16:12:14.927879 01278576 MND trans:105948, execute in mnode which not leader
05/30 16:12:14.927882 01278576 MND trans:105948, continue to execute, stage:redoAction
05/30 16:12:14.927886 01278576 MND ERROR failed to execute redoActions since:Database not ready, code:0x80000014
05/30 16:12:14.927937 01278576 MND trans:105949, is proposed, saved:0 code:0x0, apply index:211910 term:14 config:-1 role:leader raw:0x55987cf4c1c3
05/30 16:12:14.927946 01278576 MND trans:105949, execute in mnode which not leader
05/30 16:12:14.927949 01278576 MND trans:105949, continue to execute, stage:prepare
05/30 16:12:14.927953 01278576 MND trans:105949, stage from prepare to redoAction
05/30 16:12:14.927957 01278576 MND trans:105949, continue to execute, stage:redoAction
05/30 16:12:14.927961 01278576 MND ERROR failed to execute redoActions since:Database not ready, code:0x80000014
05/30 16:12:14.928009 01278576 MND trans:105949, is proposed, saved:0 code:0x0, apply index:211911 term:14 config:-1 role:leader raw:0x55987cf9ab33
05/30 16:12:14.928065 01278576 MND trans:105949, execute in mnode which not leader
05/30 16:12:14.928071 01278576 MND trans:105949, continue to execute, stage:redoAction
05/30 16:12:14.928075 01278576 MND ERROR failed to execute redoActions since:Database not ready, code:0x80000014
05/30 16:12:14.928124 01278576 MND trans:105950, is proposed, saved:0 code:0x0, apply index:211912 term:14 config:-1 role:leader raw:0x55987cf4c1c3
05/30 16:12:14.928135 01278576 MND trans:105950, execute in mnode which not leader
05/30 16:12:14.928139 01278576 MND trans:105950, continue to execute, stage:prepare
05/30 16:12:14.928143 01278576 MND trans:105950, stage from prepare to redoAction
05/30 16:12:14.928147 01278576 MND trans:105950, continue to execute, stage:redoAction
05/30 16:12:14.928151 01278576 MND ERROR failed to execute redoActions since:Database not ready, code:0x80000014
05/30 16:12:14.928206 01278576 MND trans:105950, is proposed, saved:0 code:0x0, apply index:211913 term:14 config:-1 role:leader raw:0x55987cf9ab33
05/30 16:12:14.928257 01278576 MND trans:105950, execute in mnode which not leader
05/30 16:12:14.928260 01278576 MND trans:105950, continue to execute, stage:redoAction
05/30 16:12:14.928269 01278576 MND ERROR failed to execute redoActions since:Database not ready, code:0x80000014
05/30 16:12:14.928322 01278576 MND trans:105951, is proposed, saved:0 code:0x0, apply index:211914 term:14 config:-1 role:leader raw:0x55987cf4c1c3
05/30 16:12:14.928353 01278576 MND trans:105951, execute in mnode which not leader
05/30 16:12:14.928357 01278576 MND trans:105951, continue to execute, stage:prepare
05/30 16:12:14.928360 01278576 MND trans:105951, stage from prepare to redoAction
05/30 16:12:14.928365 01278576 MND trans:105951, continue to execute, stage:redoAction
05/30 16:12:14.928382 01278576 MND ERROR failed to execute redoActions since:Database not ready, code:0x80000014
05/30 16:12:14.928437 01278576 MND trans:105951, is proposed, saved:0 code:0x0, apply index:211915 term:14 config:-1 role:leader raw:0x55987cf9ab33
05/30 16:12:14.928480 01278576 MND trans:105951, execute in mnode which not leader
05/30 16:12:14.928483 01278576 MND trans:105951, continue to execute, stage:redoAction
05/30 16:12:14.928487 01278576 MND ERROR failed to execute redoActions since:Database not ready, code:0x80000014
05/30 16:12:14.928551 01278576 MND trans:105952, is proposed, saved:0 code:0x0, apply index:211916 term:14 config:-1 role:leader raw:0x55987cf4c1c3
05/30 16:12:14.928561 01278576 MND trans:105952, execute in mnode which not leader
05/30 16:12:14.928566 01278576 MND trans:105952, continue to execute, stage:prepare
05/30 16:12:14.928571 01278576 MND trans:105952, stage from prepare to redoAction
05/30 16:12:14.928583 01278576 MND trans:105952, continue to execute, stage:redoAction
05/30 16:12:14.928588 01278576 MND ERROR failed to execute redoActions since:Database not ready, code:0x80000014
05/30 16:12:14.928635 01278576 WAL ERROR vgId:1, unexpected wal log, index:211917, since body checksum not passed
05/30 16:12:14.928666 01278576 WAL ERROR checksum written into log:1798327341, checksum calculated:1451596864
taosd: /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/libs/wal/src/walRead.c:532: walReadVer: Assertion `0' failed.

**Comment by sangshuduo** [comment]
Please upgrade the TDengine to the latest version

**Comment by sunyymq** [comment]
after upgrade,start failed also

**Comment by sangshuduo** [comment]
Please paste the output
