### ISSUE TITLE
What if I don't want to merge data with the same timestamp?

### ISSUE THREAD

**Issue by gypinsistcn** [taosdata/TDengine#21534]
老师你好，请问如果时间戳相同时，里面有不少数据，不能直接的合并，我该怎么做啊？比如下图的股票数据，时间戳相同时，有买有卖，不能直接合并啊。这是交易所提供的数据，时间戳是毫秒级的，大约最小20毫秒一批，一批数据中有不少是相同时间戳的
![Snipaste_2023-05-29_06-10-26](https://github.com/taosdata/TDengine/assets/83859656/af400530-2a06-45fd-9fe6-11502f28afa8)

**Comment by xieyj-apple** [comment]
时间可以按微妙或者纳秒来，这样比毫秒多出3~6位可以自由设置值。

**Comment by yu285** [comment]
现在3.3.0.3 支持复合主键，可以完美解决这类场景。

可以加我微信：a15652223354
