### ISSUE TITLE
show table using like keyword and %, the result is not right

### ISSUE THREAD

**Issue by wowo404** [taosdata/TDengine#2154]
the sql and the query result is show below
show tables like 'trend_data__%'; #before the %, it has two underline(_)
![image](https://user-images.githubusercontent.com/39786064/83863493-fc967900-a755-11ea-9d1b-13c4e7b23e97.png)

**Comment by xiaopingcs** [comment]
_ matches any single char, so this is working as expected

**Comment by wowo404** [comment]
Please add this future to your documentation. I can't say any more.....

**Comment by xiaopingcs** [comment]
> Please add this future to your documentation. I can't say any more.....

It has been in our documentation, you can check it from this page: https://www.taosdata.com/cn/documentation/taos-sql/#%E6%95%B0%E6%8D%AE%E6%9F%A5%E8%AF%A2
