### ISSUE TITLE
TDengine: query the storage cost of an empty table

### ISSUE THREAD

**Issue by nrwflqzr-zwhy** [taosdata/TDengine#21540]
**Performance Issue** 
Any questions related to TDengine's performance can be discussed here.

**Problem Description** 
Hello taos team, I want to know how to query the storage cost of an empty table
We are currently considering whether to store all the data in one table or sub-table storage, so we want to know how much the storage overhead of the table itself is

**Environment (please complete the following information):**

 OS: [Ubuntu 20.04]
 TDengine Version [3.0.4.1]

**Comment by yu285** [comment]
compared with the actual data , you needn't to worry about the meta data (table size) . it is a small part .

how many tables you will have ? and how much storage do you have ?
