### ISSUE TITLE
请问如何在docker里面访问宿主机的taos服务？

### ISSUE THREAD

**Issue by yida2017** [taosdata/TDengine#21549]

**Comment by yida2017** [comment]
![1685517845288](https://github.com/taosdata/TDengine/assets/35675639/b4b56dda-c3b7-4743-a49a-6f7218c3e990)

**Comment by veigara** [comment]
在创建docker时加上-p 6030-6049:6030-6049 把端口映射到主机上，通过rest服务6041访问

**Comment by yida2017** [comment]
那再请问：在docker里面还需要安装taos客户端吗？

**Comment by veigara** [comment]
不需要啊，要在docker 容器内看数据的话，只要在进入容器后输入taos 就能用shell 查询数据
