### ISSUE TITLE
restful接口的时区设置没用?

### ISSUE THREAD

**Issue by denfils** [taosdata/TDengine#21548]
不指定时区
![image](https://github.com/taosdata/TDengine/assets/24760335/307ccd14-9b28-44ba-8ee5-d1bbf1aaad7a)
指定时区,查询出来的时间还是一样的
![image](https://github.com/taosdata/TDengine/assets/24760335/35e6f180-309a-43de-af23-c809b66ddfb6)
![image](https://github.com/taosdata/TDengine/assets/24760335/eefc5a2b-57d5-4ea1-b050-2c71ce16dcac)

**Comment by sangshuduo** [comment]
什么版本？

我这没问题
![image](https://github.com/taosdata/TDengine/assets/825729/9f6b1435-5fef-4eb6-9bb0-6c77c3714bd1)

**Comment by denfils** [comment]
3.0.0.0

**Comment by denfils** [comment]
> 

3.0.0.0

**Comment by sangshuduo** [comment]
升到最新 3.0.4.2 试试

**Comment by denfils** [comment]
> 升到最新 3.0.4.2 试试

![lQLPJwFT_9OaPDrNAqHNAvyw7Qu5MvEE_SYEcAaMJoAGAA_764_673](https://github.com/taosdata/TDengine/assets/24760335/04b4d4a0-34e7-4d02-b072-60557d080d77)
![f33341a50386eed9875aff6d439d4570](https://github.com/taosdata/TDengine/assets/24760335/d4bd73b5-ad0c-4a2f-9167-e67a68b5bdd4)
![25d186a45a7bdfb48996a2d5b3e0f9fa](https://github.com/taosdata/TDengine/assets/24760335/e761d225-849b-4604-a2c2-c408af424b40)
![a2ceff486519890945117de106d93fad](https://github.com/taosdata/TDengine/assets/24760335/9f17ce71-3b13-481d-8649-aa9077de3350)
升级了后还是有这个问题..请问是不是有什么额外的配置项?

**Comment by denfils** [comment]
> 升到最新 3.0.4.2 试试

找到原因了,使用curl可以使用时区参数.但是使用postman工具或者使用java代码,就无法使用时区参数.这个是使用有错吗?

**Comment by sangshuduo** [comment]
> > 升到最新 3.0.4.2 试试
> 
> 找到原因了,使用curl可以使用时区参数.但是使用postman工具或者使用java代码,就无法使用时区参数.这个是使用有错吗?

postman 不了解。java 如果使用官方连接器 REST 接口是可以设置时区的 https://docs.taosdata.com/connector/java/#%E6%8C%87%E5%AE%9A-url-%E5%92%8C-properties-%E8%8E%B7%E5%8F%96%E8%BF%9E%E6%8E%A5

**Comment by sangshuduo** [comment]
> > > 升到最新 3.0.4.2 试试
> > 
> > 找到原因了,使用curl可以使用时区参数.但是使用postman工具或者使用java代码,就无法使用时区参数.这个是使用有错吗?
> 
> postman 不了解。java 如果使用官方连接器 REST 接口是可以设置时区的 https://docs.taosdata.com/connector/java/#%E6%8C%87%E5%AE%9A-url-%E5%92%8C-properties-%E8%8E%B7%E5%8F%96%E8%BF%9E%E6%8E%A5

修正：Java 连接器不需要设置时区，会根据当前客户端机器系统时区自动取得正确的时间
