### ISSUE TITLE
tdengine cluster crash

### ISSUE THREAD

**Issue by xiaoshumiao6** [taosdata/TDengine#21543]
**Bug Description**
cluster crash; firstep consume 4 cpus full

**To Reproduce**
1.  build a tdengine cluster of 3 nodes , create  a database :
CREATE DATABASE `db_meter_read` CACHEMODEL 'both' DURATION 35 STT_TRIGGER 16 KEEP 3650d,3650d,3650d PAGES 256 PAGESIZE 4 PRECISION 'ms' REPLICA 3 WAL_LEVEL 1 VGROUPS 16 SINGLE_STABLE 0;

CREATE STABLE `meter_read_record` (`ts` TIMESTAMP,`amount` DOUBLE, `used` DOUBLE, `price` DOUBLE,`cost` DOUBLE,`contract_id` NCHAR(20),`year` INT,`pay_method` INT,`remark` NCHAR(200),`source` INT) TAGS (`device_id` NCHAR(32),`room_id` NCHAR(32),`tenant_id` NCHAR(10),`device_type` TINYINT,`house_id` NCHAR(32),`uuid` NCHAR(32),`platform` TINYINT,`platform_id` NCHAR(32));

CREATE INDEX idx_room_id ON meter_read_record (room_id);
CREATE INDEX idx_tenant_id ON meter_read_record (tenant_id);
CREATE INDEX idx_device_type ON meter_read_record (device_type);
CREATE INDEX idx_uuid ON meter_read_record (uuid);

2.  then insert some data ,  abount 1 millon +
3. then the cluster crash , every thing is broken.

**Expected Behavior**

**Screenshots**
[Tue May 30 00:27:10 2023] show_signal_msg: 6 callbacks suppressed
[Tue May 30 00:27:10 2023] vnode-apply[26148]: segfault at 4100000008 ip 000055cca3d3cf5a sp 00007f2e1a8ebe90 error 4 in taosd[55cca3800000+6a3000]
[Tue May 30 00:27:10 2023] Code: 00 0f 95 c0 0f b6 c0 48 8d 0d 8e 9b 0e 00 ba 91 00 00 00 48 8d 35 9e 9b 0e 00 89 c7 b8 00 00 00 00 e8 16 6d 00 00 48 8b 45 f8 <48> 8b 10 48 8b 45 e8 48 89 50 18 48 8b 45 f8 48 8b 50 08 48 8b 45
[Tue May 30 00:27:52 2023] vnode-apply[39881]: segfault at 48 ip 00007f70d90781e4 sp 00007f6f920da190 error 6 in libjemalloc.so.2[7f70d9000000+ae000]
[Tue May 30 00:27:52 2023] Code: e1 49 f7 d1 4f 21 0c fc 49 3b 9c 24 a0 25 00 00 4c 8b 53 40 0f 84 d4 00 00 00 4c 8b 5b 48 4d 8b 72 48 4d 89 73 40 48 8b 7b 40 <4c> 89 5f 48 48 8b 53 48 4c 8b 42 40 4c 89 43 48 48 8b 47 48 48 89
[Tue May 30 00:28:42 2023] vnode-apply[40038]: segfault at 7e9fde4168c0 ip 00007f9fe9a7801d sp 00007f9e9fbdbfe0 error 6 in libjemalloc.so.2[7f9fe9a00000+ae000]
[Tue May 30 00:28:42 2023] Code: 40 48 89 5b 48 4d 85 c9 74 28 4d 8b 41 48 4c 89 43 40 49 89 59 48 4c 8b 5b 48 49 8b 53 40 48 89 53 48 49 8b 79 48 4c 89 4f 40 <48> 89 5a 40 48 8b 5b 40 49 89 9c 24 a0 25 00 00 49 8b 84 24 a8 25
[Tue May 30 00:29:31 2023] vnode-apply[40184]: segfault at fffffff000000040 ip 00007f42c0e781fc sp 00007f4177bf28f0 error 7 in libjemalloc.so.2[7f42c0e00000+ae000]
[Tue May 30 00:29:31 2023] Code: 00 00 4c 8b 5b 48 4d 8b 72 48 4d 89 73 40 48 8b 7b 40 4c 89 5f 48 48 8b 53 48 4c 8b 42 40 4c 89 43 48 48 8b 47 48 48 89 78 40 <49> 89 58 40 49 8b 9c 24 a8 25 00 00 48 c1 ed 0c 48 29 eb 49 89 9c
[Tue May 30 00:30:57 2023] vnode-apply[40336]: segfault at fffffff000000040 ip 00007f219e0781fc sp 00007f205435cdc0 error 7 in libjemalloc.so.2[7f219e000000+ae000]
[Tue May 30 00:30:57 2023] Code: 00 00 4c 8b 5b 48 4d 8b 72 48 4d 89 73 40 48 8b 7b 40 4c 89 5f 48 48 8b 53 48 4c 8b 42 40 4c 89 43 48 48 8b 47 48 48 89 78 40 <49> 89 58 40 49 8b 9c 24 a8 25 00 00 48 c1 ed 0c 48 29 eb 49 89 9c
[Tue May 30 15:57:16 2023] trans-cli-work[87754]: segfault at 148d8 ip 00007ff82c866eed sp 00007ff8236f5e50 error 4 in libc.so.6[7ff82c7f6000+195000]
[Tue May 30 15:57:16 2023] Code: fa 48 89 f2 90 31 f6 e9 a1 f5 ff ff 90 f3 0f 1e fa 41 57 41 56 41 55 41 54 55 48 89 fd 53 48 83 ec 08 64 8b 1c 25 d0 02 00 00 <8b> 47 10 25 7f 01 00 00 83 f8 43 7f 66 77 14 48 8d 15 ed 9c 13 00
[Tue May 30 15:57:39 2023] vnode-apply[88029]: segfault at 7fdeec6bf6f0 ip 00007fdeec2289b6 sp 00007fdda2dd8770 error 4 in libjemalloc.so.2[7fdeec200000+ae000]
[Tue May 30 15:57:39 2023] Code: 1f 44 00 00 53 48 3b 91 c0 00 00 00 48 89 cb 74 43 48 8b 02 4c 8d 05 f9 48 49 00 48 c1 e8 14 0f b6 c8 48 8d 3c 89 4d 8d 0c f8 <41> 83 79 10 01 74 3b 48 8d bb c8 00 00 00 48 89 d6 e8 14 a2 04 00
[Tue May 30 15:58:27 2023] vnode-apply[88223]: segfault at fffffff000000040 ip 00007f29c1c781fc sp 00007f28775efdc0 error 7 in libjemalloc.so.2[7f29c1c00000+ae000]
[Tue May 30 15:58:27 2023] Code: 00 00 4c 8b 5b 48 4d 8b 72 48 4d 89 73 40 48 8b 7b 40 4c 89 5f 48 48 8b 53 48 4c 8b 42 40 4c 89 43 48 48 8b 47 48 48 89 78 40 <49> 89 58 40 49 8b 9c 24 a8 25 00 00 48 c1 ed 0c 48 29 eb 49 89 9c
[Tue May 30 15:59:14 2023] vnode-apply[88426]: segfault at 48 ip 00007f30394781e4 sp 00007f2ef08df190 error 6 in libjemalloc.so.2[7f3039400000+ae000]
[Tue May 30 15:59:14 2023] Code: e1 49 f7 d1 4f 21 0c fc 49 3b 9c 24 a0 25 00 00 4c 8b 53 40 0f 84 d4 00 00 00 4c 8b 5b 48 4d 8b 72 48 4d 89 73 40 48 8b 7b 40 <4c> 89 5f 48 48 8b 53 48 4c 8b 42 40 4c 89 43 48 48 8b 47 48 48 89
[Tue May 30 16:00:02 2023] vnode-apply[88641]: segfault at 7fc392abf6f0 ip 00007fc3926289b6 sp 00007fc2491d9770 error 4 in libjemalloc.so.2[7fc392600000+ae000]
[Tue May 30 16:00:02 2023] Code: 1f 44 00 00 53 48 3b 91 c0 00 00 00 48 89 cb 74 43 48 8b 02 4c 8d 05 f9 48 49 00 48 c1 e8 14 0f b6 c8 48 8d 3c 89 4d 8d 0c f8 <41> 83 79 10 01 74 3b 48 8d bb c8 00 00 00 48 89 d6 e8 14 a2 04 00
[Tue May 30 16:00:50 2023] vnode-apply[88841]: segfault at 48 ip 00007f9402c781e4 sp 00007f92b83f0190 error 6 in libjemalloc.so.2[7f9402c00000+ae000]
[Tue May 30 16:00:50 2023] Code: e1 49 f7 d1 4f 21 0c fc 49 3b 9c 24 a0 25 00 00 4c 8b 53 40 0f 84 d4 00 00 00 4c 8b 5b 48 4d 8b 72 48 4d 89 73 40 48 8b 7b 40 <4c> 89 5f 48 48 8b 53 48 4c 8b 42 40 4c 89 43 48 48 8b 47 48 48 89
[Tue May 30 16:01:38 2023] vnode-apply[89056]: segfault at 48 ip 00007ffb384781e4 sp 00007ff9ef7de190 error 6 in libjemalloc.so.2[7ffb38400000+ae000]
[Tue May 30 16:01:38 2023] Code: e1 49 f7 d1 4f 21 0c fc 49 3b 9c 24 a0 25 00 00 4c 8b 53 40 0f 84 d4 00 00 00 4c 8b 5b 48 4d 8b 72 48 4d 89 73 40 48 8b 7b 40 <4c> 89 5f 48 48 8b 53 48 4c 8b 42 40 4c 89 43 48 48 8b 47 48 48 89
[Tue May 30 16:02:26 2023] vnode-apply[89259]: segfault at 48 ip 00007fe2f36781e4 sp 00007fe1aa1d9190 error 6 in libjemalloc.so.2[7fe2f3600000+ae000]
[Tue May 30 16:02:26 2023] Code: e1 49 f7 d1 4f 21 0c fc 49 3b 9c 24 a0 25 00 00 4c 8b 53 40 0f 84 d4 00 00 00 4c 8b 5b 48 4d 8b 72 48 4d 89 73 40 48 8b 7b 40 <4c> 89 5f 48 48 8b 53 48 4c 8b 42 40 4c 89 43 48 48 8b 47 48 48 89
[Tue May 30 16:03:14 2023] vnode-apply[89443]: segfault at 48 ip 00007f0770a781e4 sp 00007f06274e8190 error 6 in libjemalloc.so.2[7f0770a00000+ae000]
[Tue May 30 16:03:14 2023] Code: e1 49 f7 d1 4f 21 0c fc 49 3b 9c 24 a0 25 00 00 4c 8b 53 40 0f 84 d4 00 00 00 4c 8b 5b 48 4d 8b 72 48 4d 89 73 40 48 8b 7b 40 <4c> 89 5f 48 48 8b 53 48 4c 8b 42 40 4c 89 43 48 48 8b 47 48 48 89
[Tue May 30 16:04:02 2023] vnode-apply[89646]: segfault at 7f9d35cbf6f0 ip 00007f9d358289b6 sp 00007f9beaff5770 error 4 in libjemalloc.so.2[7f9d35800000+ae000]
[Tue May 30 16:04:02 2023] Code: 1f 44 00 00 53 48 3b 91 c0 00 00 00 48 89 cb 74 43 48 8b 02 4c 8d 05 f9 48 49 00 48 c1 e8 14 0f b6 c8 48 8d 3c 89 4d 8d 0c f8 <41> 83 79 10 01 74 3b 48 8d bb c8 00 00 00 48 89 d6 e8 14 a2 04 00
[Tue May 30 16:04:50 2023] vnode-apply[89845]: segfault at 48 ip 00007f0be44781e4 sp 00007f0a9c7d9190 error 6 in libjemalloc.so.2[7f0be4400000+ae000]
[Tue May 30 16:04:50 2023] Code: e1 49 f7 d1 4f 21 0c fc 49 3b 9c 24 a0 25 00 00 4c 8b 53 40 0f 84 d4 00 00 00 4c 8b 5b 48 4d 8b 72 48 4d 89 73 40 48 8b 7b 40 <4c> 89 5f 48 48 8b 53 48 4c 8b 42 40 4c 89 43 48 48 8b 47 48 48 89
[Tue May 30 16:05:37 2023] vnode-apply[90047]: segfault at 7ff6cf0bf6f0 ip 00007ff6cec289b6 sp 00007ff5849ef770 error 4 in libjemalloc.so.2[7ff6cec00000+ae000]
[Tue May 30 16:05:37 2023] Code: 1f 44 00 00 53 48 3b 91 c0 00 00 00 48 89 cb 74 43 48 8b 02 4c 8d 05 f9 48 49 00 48 c1 e8 14 0f b6 c8 48 8d 3c 89 4d 8d 0c f8 <41> 83 79 10 01 74 3b 48 8d bb c8 00 00 00 48 89 d6 e8 14 a2 04 00
[Tue May 30 21:04:14 2023] vnode-apply[102289]: segfault at 7f4b1d0bf6f0 ip 00007f4b1cc289b6 sp 00007f495f1f1770 error 4 in libjemalloc.so.2[7f4b1cc00000+ae000]
[Tue May 30 21:04:14 2023] Code: 1f 44 00 00 53 48 3b 91 c0 00 00 00 48 89 cb 74 43 48 8b 02 4c 8d 05 f9 48 49 00 48 c1 e8 14 0f b6 c8 48 8d 3c 89 4d 8d 0c f8 <41> 83 79 10 01 74 3b 48 8d bb c8 00 00 00 48 89 d6 e8 14 a2 04 00
[Tue May 30 21:10:19 2023] trans-cli-work[120288]: segfault at 8 ip 000055b4e9c38974 sp 00007f23ed6f71a0 error 4 in taosd[55b4e9800000+6a3000]
[Tue May 30 21:10:19 2023] Code: 50 08 48 8b 45 c8 48 83 c0 08 48 8b 00 48 39 c2 0f 84 da 00 00 00 48 8b 45 c8 48 8b 40 08 48 89 45 e0 48 8b 45 e0 48 83 c0 08 <48> 8b 00 48 89 c2 48 8b 45 e0 48 8b 00 48 89 02 48 8b 45 e0 48 8b
[Tue May 30 21:11:07 2023] vnode-apply[121277]: segfault at 48 ip 00007fac326781e4 sp 00007fac22df3190 error 6 in libjemalloc.so.2[7fac32600000+ae000]
[Tue May 30 21:11:07 2023] Code: e1 49 f7 d1 4f 21 0c fc 49 3b 9c 24 a0 25 00 00 4c 8b 53 40 0f 84 d4 00 00 00 4c 8b 5b 48 4d 8b 72 48 4d 89 73 40 48 8b 7b 40 <4c> 89 5f 48 48 8b 53 48 4c 8b 42 40 4c 89 43 48 48 8b 47 48 48 89

**Environment (please complete the following information):**
 - OS: [Ubuntu 22.04.2 LTS]
 - Memory, CPU, current Disk Space [8C16G500G * 3]
 - TDengine Version [3.0.4.2]

**Additional Context**

**Comment by sangshuduo** [comment]
Please use gdb to launch it then show the stack info with the command 'bt'. Thanks.
