### ISSUE TITLE
/usr/local/taos/driver/libtaos.so.2.4.0.10 already loaded in another classloader

### ISSUE THREAD

**Issue by JiPengL** [taosdata/TDengine#21552]
**Bug Description**
flink在任务中加载taos数据源，当这个任务进行重启的时候会有这个异常，导致任务启动失败，只要fiink在本次生命周期内启动过这个任务，就无法重新启动，需要重启flink架构，才能重新启动这个任务。有什么办法能不重启flink集群，单独重启任务么

**Comment by sangshuduo** [comment]
这个问题应该问 flink 社区吧？
