### ISSUE TITLE
windows版本查询sql后，内存占用过高不释放

### ISSUE THREAD

**Issue by OLDDAI** [taosdata/TDengine#21560]
2亿多条数据查了一下sql，select avg(temperature), avg(humidity) from test.weather interval(1m)
内存占用5G左右，一直不释放，重启服务还是会立马占用，这是什么情况，
版本：3.0.4.2

![微信图片_20230601173958](https://github.com/taosdata/TDengine/assets/43257366/dc0b7ec8-2b53-4aa2-817a-44e1f028fc4b)

**Comment by yu285** [comment]
windows 早期问题较多，开源版维护不过来，回收到到企业版重做了。 所以windows版本到了 3.0.7.1 之后就没法再升级了，也没有维护团队支持。所以咱们还是换到 linux 版本再使用，目前最新版为 3.2.3.0。

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
