### ISSUE TITLE
Unable to establish connection

### ISSUE THREAD

**Issue by moco2022** [taosdata/TDengine#21571]
**Bug Description**

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**
![image](https://github.com/taosdata/TDengine/assets/110591589/77c0eafe-1535-47d0-ad7d-74aebbf4b314)
启动数据库cpu直接变成100%了，连接不上

**Comment by sangshuduo** [comment]
系统配置太低了？

**Comment by moco2022** [comment]
系统4核16G的 不是这个原因吧

**Comment by sangshuduo** [comment]
TDengine 什么版本？有旧版本数据吗？
