### ISSUE TITLE
The table name cannot contain '.'

### ISSUE THREAD

**Issue by hanjinglong** [taosdata/TDengine#21572]
**创建表报错**
SQL 错误 [9751]: TDengine ERROR (2617): sql: INSERT INTO  `TYMH.JQZQ.300_TI_10202` USING meters TAGS ('magus') values (1685646157000,28.606598), desc: The table name cannot contain '.'

**重现步骤**
1. 使用最新版本3.0.4.2
2. 创建表报错，提示表名不能包含“.”
3. 使用转义符"`"后依然报错

**Comment by yu285** [comment]
3.0 确实不支持 .
