### ISSUE TITLE
windows 版本的3.0.4.2 Server版 TDengine go的客户端SDK  使用 af 包建立原生连接 连接不上 请看看什么原因

### ISSUE THREAD

**Issue by fanqang** [taosdata/TDengine#21575]
![3061685689177](https://github.com/taosdata/TDengine/assets/47728120/799c7d79-4fb5-41b1-b9f9-0d781de6c9bd)

**Comment by sangshuduo** [comment]
Version not compatible. 客户端和服务端版本不匹配吧
