### ISSUE TITLE
磁盘占用过高

### ISSUE THREAD

**Issue by xiahejun** [taosdata/TDengine#21598]
版本：3.0.2.5
问题：
查看表磁盘占用不多，但是vnode占用特别大，使用了数据订阅功能。
![fa23d8182f4f4063f05706767abb4eb](https://github.com/taosdata/TDengine/assets/54968493/3b789f9e-fac3-43aa-b440-72768b128fee)
![b26d4fa85f3c2299cdf260f319b9c73](https://github.com/taosdata/TDengine/assets/54968493/99cce134-7c30-4653-99fe-330b14dfcf65)

**Comment by yu285** [comment]
wal 保留策略可以配置。
