### ISSUE TITLE
项目缺少个持续集成的服务

### ISSUE THREAD

**Issue by tidyjiang8** [taosdata/TDengine#216]
似乎目前还没有持续集成服务?

提交Pull Request时发现的问题：如果很多人都在向仓库提交PR，Reviewer不可能把每一行代码，每一个字符都看得清清楚楚，万一提交的代码有啥不对，编译不过，却被merge了，就。。

可能贵公司内部是有这个服务器的，但是希望开源版本也有一个对应的服务。

**Comment by plum-lihui** [comment]
非常感谢您的建议。确实需要一个测试服务，来保证版本更新的质量，后续我们整理发布一个测试集。

**Comment by ArgoZhang** [comment]
appveyor 这样类似的CI&CD很多，集成一个就可以了

**Comment by zimengpan** [comment]
GitHub最近更新GitHub Action，建议使用GitHub原生自带CI/CD服务

**Comment by ArgoZhang** [comment]
> GitHub最近更新GitHub Action，建议使用GitHub原生自带CI/CD服务

还不能用呢吧？注册都没有提供呢

**Comment by zimengpan** [comment]
现在是Beta版，个人很推荐尝试使用，主要这样可以集中管理，不需要东拼西凑地找其他资源：https://github.com/features/actions

**Comment by ArgoZhang** [comment]
@zimengpan 
这个页面仅仅是一个介绍。你能使用了？

**Comment by zimengpan** [comment]
> @zimengpan
> 这个页面仅仅是一个介绍。你能使用了？

GitHub Actions呀，一直可以用呀，只不过8月8号新发布的CI/CD服务，public repo是免费的，只需要点击页面里的Sign Up for Beta

**Comment by zimengpan** [comment]
当然如果不抢先试用beta版的话，今年11月13号beta测试结束，之后就可以直接使用了

**Comment by ArgoZhang** [comment]
不是所有人都能用。至少现在不能用的。

**Comment by sangshuduo** [comment]
Already integrated travis-CI.
