### ISSUE TITLE
taosc can not connect to server [taosc 不能连接到服务器]

### ISSUE THREAD

**Issue by jetgeng** [taosdata/TDengine#21605]
**Bug Description**
There are two pc, we call them S1 and C1. 
1. I have run a TDengine 3.0.4.1 server in docker container  on S1, and install TDengine-client-3.0.4.1-macos on C1. 
2. special firstEp to S1 in /etc/taos/taos.cfg on C1
3. run taos on C1, can not connect to S1

**To Reproduce**
In terminal i got this:

```
Welcome to the TDengine Command Line Interface, Client Version:3.0.4.1
Copyright (c) 2022 by TDengine, all rights reserved.

failed to connect to server, reason: Conn is broken
```

get log from client log as follow:

```
06/05 20:17:10.366554 123145377337344 QRY catalog update thread started
06/05 20:17:10.366619 140704453683392 QRY ERROR generate schdulerId failed, errno:2
06/05 20:17:10.367807 140704453683392 TSC connecting to server, numOfEps:2 inUse:0 user:root db:(null) key:root:dcc5bed04851fec854c035b2e40263b6:(null):0
06/05 20:17:10.367812 140704453683392 TSC ep:0, S1_ip:6030
06/05 20:17:10.367813 140704453683392 TSC ep:1, S1_ip:6030
06/05 20:17:10.499826 123145383776256 RPC WARN TSC conn 0x7fb8a8804680 send cost:130121us, send exception
06/05 20:17:11.544032 123145383776256 RPC WARN TSC conn 0x7fb8a8804680 read error:EOF, ref:1
06/05 20:17:12.513796 123145383776256 RPC WARN TSC conn 0x7fb8a8804680 send cost:2144093us, send exception
```

**Screenshots**
![image](https://github.com/taosdata/TDengine/assets/745096/b966657e-abed-4bf9-91ed-7c21f057a7a1)

**Environment (please complete the following information):**
 - OS: A is Mac OS X 10.15.7 and docker is Server Version: 20.10.11 
 - TDengine Version [3.0.4.1]  image id:   ad94f3c5dc66
 - C1: 
   - OS: MacOS 13.1 
   - TDengine Client: 3.0.4.1

**Comment by sangshuduo** [comment]
docker 使用 --network host 试试

**Comment by jetgeng** [comment]
@sangshuduo 谢谢,我测试了一下.发现还是没有用. 
我暂时先放弃使用docker 部署了. 用macos的原生版部署.可以顺利连接上.
