### ISSUE TITLE
Type DOUBLE variable in predicate produces unexpected results

### ISSUE THREAD

**Issue by YuanchengJiang** [taosdata/TDengine#21603]
**Bug Description**
`select count(1) from test where 1.0` returns normally as the predicate is True.
However, when it refers to a double variable, the predicate becomes False:
`select count(1) from test where test.price`

**To Reproduce**
```
create table test(time TIMESTAMP, symbol VARCHAR(16), price DOUBLE, day_volume INT);
insert into test values ('2023-04-14 19:10:48.002','INTC',31.82,NULL);
select count(1) from test where test.price; // it should return 1 while the result is 0
```

**Environment (please complete the following information):**
 - OS: ubuntu 20.04
 - TDengine Version: 3.0.4.1

**Comment by sangshuduo** [comment]
我用最新版本没有复现
