### ISSUE TITLE
时间主键倒序排序数据不准确

### ISSUE THREAD

**Issue by veigara** [taosdata/TDengine#21604]
taos 版本：3.0.4.1

时间主键倒序desc排序数据不准确，asc排序是准确的

-----------------------------------------------------------------
desc sql:
select create_time from db_hndk_station_relast.service_data_battery_cell_detail_LWLPWETU7NL003171
where   create_time >= TO_UNIXTIMESTAMP('2023-06-05 00:00:00') and create_time <= TO_UNIXTIMESTAMP('2023-06-05 23:38:59') 
and car_vin = 'LWLPWETU7NL003171' order by create_time desc

最新几条的结果：
![1](https://github.com/taosdata/TDengine/assets/36318745/a11c75ec-0654-42ff-95c3-7c432a524537)

asc sql:
select create_time from db_hndk_station_relast.service_data_battery_cell_detail_LWLPWETU7NL003171
where   create_time >= TO_UNIXTIMESTAMP('2023-06-05 00:00:00') and create_time <= TO_UNIXTIMESTAMP('2023-06-05 23:38:59') 
and car_vin = 'LWLPWETU7NL003171' order by create_time asc 

最新几条结果：
![2](https://github.com/taosdata/TDengine/assets/36318745/dbfbf552-befc-4c8f-bcf1-e27cd1d8f55f)

两者只是排序的不同字段都一样，最新的结果不一样，很影响前端用户体验

**Comment by sangshuduo** [comment]
没看懂，正序倒序截图上不是都对吗？

**Comment by veigara** [comment]
倒叙排列的时间是不准确的
![0](https://github.com/taosdata/TDengine/assets/36318745/ec3e7d5e-3ada-4797-8187-f9749d09da2c)

**Comment by veigara** [comment]
升级到2.0.5.0并重新导入数据就正常了

**Comment by yangshijing** [comment]
3.0.3.0版本也遇到了同样的问题，请问2.0.5.0不是降版本了吗

**Comment by sangshuduo** [comment]
> 3.0.3.0版本也遇到了同样的问题，请问2.0.5.0不是降版本了吗,目前最新的版本不是3.0.5.0吗 @sangshuduo

3.0.5.0 写错了
