### ISSUE TITLE
2.6.0.6版本,python连接器个版本都是报错unable to load taos client library: [WinError 126] 找不到指定的模块。

### ISSUE THREAD

**Issue by yangjiyue** [taosdata/TDengine#21610]
**Bug Description**
2.6.0.6版本,python连接器个版本都是报错unable to load taos client library: [WinError 126] 找不到指定的模块。
之前python连接器版本是2.6.0是可用的所以不是dll的问题

**To Reproduce**
只需要安装client.2.6.0.6 pip安装taospy 就是报这样的错误

**Expected Behavior**

**Screenshots**
![图片](https://github.com/taosdata/TDengine/assets/20500475/04e9ed82-54cf-4759-a888-8ec021114589)

**Environment (please complete the following information):**
 - win11
 - 
 - 2.6.0.6

**Additional Context**

**Comment by sangshuduo** [comment]
Windows\\system32 目录下有没有 taos.dll ？

**Comment by yangjiyue** [comment]
有的,不过我不清楚是不是我的环境问题.因为我又替换了一个3.0的taos.dll,仍然报相同的错误,但是我在代码里也用到了opcdaauto.dll是可以顺利加载的  .dll需要手动注册一下吗?

**Comment by yangjiyue** [comment]
![image](https://github.com/taosdata/TDengine/assets/20500475/c9462502-052a-4166-9daf-b68f312cc062)
我在电脑上装了3.0的tdserver   并替换了 taos.dll
重新安装的 taospy-2.7.7  报错的还是找不到指定的模块

**Comment by yangjiyue** [comment]
Python 3.6.8

**Comment by sangshuduo** [comment]
dll 不需要注册，客户端版本和服务端版本必须相同。2.6.0.6 比较老了，建议升级到 3.0 最新版本或者至少 2.6 最新版本。现象本身像是环境问题，建议在一个全新的环境安装调试验证一下。

我用 TDengine 3.0.4.2 Windows 11 Python 3.11.2 没有问题
