### ISSUE TITLE
JAVA获取到的时区错误。

### ISSUE THREAD

**Issue by donnasky** [taosdata/TDengine#21614]
如题，我在centos7系统上安装了一个3.0.4.1的数据库。centos设置的时区是CST。
![image](https://github.com/taosdata/TDengine/assets/19203869/6f1f62d0-92e9-46f9-9d63-b10606948082)
用JDBC做连接，
![image](https://github.com/taosdata/TDengine/assets/19203869/2fc20405-14eb-4771-9cf7-ff50f0527a7e)
我用java程序插入了一些数据，打印的日志的时间都是正确的。（CST），同时直接taos命令用SQL查出来的时区也是对的。
![image](https://github.com/taosdata/TDengine/assets/19203869/543c7efb-7c35-4699-8007-874e1ac9f800)
da
但是用JAVA查询数据的时候时间都是UTC的时区，在JDBC里设置了timezone也没用，客户端的taos.cfg里也设置了timezone。

**Comment by yu285** [comment]
需要确保应用一侧的服务器时区为东八区
