### ISSUE TITLE
Please improve white paper 

### ISSUE THREAD

**Issue by shengmx** [taosdata/TDengine#2162]
Doc typo.

open https://www.taosdata.com/downloads/TDengine%20White%20Paper.pdf
Page10

Step "4-1" should go to "Data Node 1" node instead of "Data Node 0".
Same as step 5-1.

Steps "4-0" and "5-0" vice versa.

Or move "Data Node 0" to clock 9 position and "Data Node 1" Up.

**Comment by Aries-Lee1991** [comment]
OK，Thank you. We'll check it.
