### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment with driver libtaos.so.3.0.4.2

### ISSUE THREAD

**Issue by zhonghuali** [taosdata/TDengine#21621]
**Bug Description**
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f481d84c2ec, pid=8, tid=54
#
# JRE version: OpenJDK Runtime Environment Corretto-17.0.7.7.1 (17.0.7+7) (build 17.0.7+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-17.0.7.7.1 (17.0.7+7-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, parallel gc, linux-amd64)
# Problematic frame:
# C  [libtaos.so.3.0.4.2+0xec2ec]  taosArrayDestroy+0x17
#
# Core dump will be written. Default location: /deployments/core
#
# An error report file with more information is saved as:
# /deployments/hs_err_pid8.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/corretto/corretto-17/issues/

**To Reproduce**
1. start your application in a container, you need to add the corresponding dependencies on TDengine to the image as well, e.g.
2. ENV TDENGINE_VERSION=3.0.4.2
RUN wget -c https://www.taosdata.com/assets-download/3.0/TDengine-client-${TDENGINE_VERSION}-Linux-x64.tar.gz \
   && tar xvf TDengine-client-${TDENGINE_VERSION}-Linux-x64.tar.gz \
   && cd TDengine-client-${TDENGINE_VERSION} \
   && ./install_client.sh \
   && cd ../ \
   && rm -rf TDengine-client-${TDENGINE_VERSION}-Linux-x64.tar.gz TDengine-client-${TDENGINE_VERSION}
3. call java driver to access tdengine3

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f481d84c2ec, pid=8, tid=54
#
# JRE version: OpenJDK Runtime Environment Corretto-17.0.7.7.1 (17.0.7+7) (build 17.0.7+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-17.0.7.7.1 (17.0.7+7-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, parallel gc, linux-amd64)
# Problematic frame:
# C  [libtaos.so.3.0.4.2+0xec2ec]  taosArrayDestroy+0x17
#
# Core dump will be written. Default location: /deployments/core
#
# An error report file with more information is saved as:
# /deployments/hs_err_pid8.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/corretto/corretto-17/issues/
**Expected Behavior**
not sure it libtaos.so.3.0.4.2 or jre error. 
it should not happen.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Amazon Linux release 2 (Karoo)]
 - Memory, CPU, current Disk Space
 - TDengine Version [3.0.4.2]

**Additional Context**

**Comment by sangshuduo** [comment]
Please post detail information such as hardware configuration, stable/table schema, how many records, etc and attach the source code you use then we can reproduce it on our side.
