### ISSUE TITLE
最新的代码编译错误了。。。

### ISSUE THREAD

**Issue by skyformat99** [taosdata/TDengine#21645]
操作过程如下：
1）20230607 获取最新的git代码   git clone  lastest
2) mkdir debug
3) cmake ..
4) make

error info：
In file included from /home/TDengine/source/libs/stream/src/stream.c:16:0:
/home/TDengine/source/libs/stream/inc/streamInc.h:19:22: 致命错误：executor.h：没有那个文件或目录
 #include "executor.h"
                      ^
编译中断。

多说一句，之前的代码都编译好好的。估计是加了什么新功能。。。

**Comment by sangshuduo** [comment]
哪个分支？我在 main 和 3.0 分支编译都没有问题

**Comment by sangshuduo** [comment]
> > 哪个分支？我在 main 和 3.0 分支编译都没有问题
> 
> main分支；
> 
> 用build.sh编译是这个错误了：
> 
> TDengine/contrib/rocksdb/include/rocksdb/slice.h:26:62: 致命错误：string\_view：没有那个文件或目录 #include // RocksDB now requires C++17 support 编译中断。 make\[2\]: \*\*\* \[contrib/rocksdb/CMakeFiles/rocksdb-shared.dir/cache/cache.cc.o\] 错误 1 make\[1\]: \*\*\* \[contrib/rocksdb/CMakeFiles/rocksdb-shared.dir/all\] 错误 2 make: \*\*\* \[all\] 错误 2

系统版本和 gcc/g++ 版本是什么？

**Comment by skyformat99** [comment]
> > > 哪个分支？我在 main 和 3.0 分支编译都没有问题
> > 
> > 
> > main分支；
> > 用build.sh编译是这个错误了：
> > TDengine/contrib/rocksdb/include/rocksdb/slice.h:26:62: 致命错误：string_view：没有那个文件或目录 #include // RocksDB now requires C++17 support 编译中断。 make[2]: *** [contrib/rocksdb/CMakeFiles/rocksdb-shared.dir/cache/cache.cc.o] 错误 1 make[1]: *** [contrib/rocksdb/CMakeFiles/rocksdb-shared.dir/all] 错误 2 make: *** [all] 错误 2
> 
> 系统版本和 gcc/g++ 版本是什么？

CentOS Linux release 7.3.1611 (Core)
gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

**Comment by lw-leo** [comment]
我也遇到了同样的问题
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-Av3uEd/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 
```

**Comment by skyformat99** [comment]
> 我也遇到了同样的问题
> 
> ```
> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
> OFFLOAD_TARGET_NAMES=nvptx-none:hsa
> OFFLOAD_TARGET_DEFAULT=1
> Target: x86_64-linux-gnu
> Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-Av3uEd/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
> Thread model: posix
> gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 
> ```

就是最近几天才出现的。
代码回退到一周之前的就OK

**Comment by sangshuduo** [comment]
> > > > 哪个分支？我在 main 和 3.0 分支编译都没有问题
> > > 
> > > 
> > > main分支；
> > > 用build.sh编译是这个错误了：
> > > TDengine/contrib/rocksdb/include/rocksdb/slice.h:26:62: 致命错误：string_view：没有那个文件或目录 #include // RocksDB now requires C++17 support 编译中断。 make[2]: *** [contrib/rocksdb/CMakeFiles/rocksdb-shared.dir/cache/cache.cc.o] 错误 1 make[1]: *** [contrib/rocksdb/CMakeFiles/rocksdb-shared.dir/all] 错误 2 make: *** [all] 错误 2
> > 
> > 
> > 系统版本和 gcc/g++ 版本是什么？
> 
> CentOS Linux release 7.3.1611 (Core) gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

验证了 CentOS 7.9 安装 devtoolset gcc 8 可以编译，我们改一下文档

**Comment by skyformat99** [comment]
> > > > > 哪个分支？我在 main 和 3.0 分支编译都没有问题
> > > > 
> > > > 
> > > > main分支；
> > > > 用build.sh编译是这个错误了：
> > > > TDengine/contrib/rocksdb/include/rocksdb/slice.h:26:62: 致命错误：string_view：没有那个文件或目录 #include // RocksDB now requires C++17 support 编译中断。 make[2]: *** [contrib/rocksdb/CMakeFiles/rocksdb-shared.dir/cache/cache.cc.o] 错误 1 make[1]: *** [contrib/rocksdb/CMakeFiles/rocksdb-shared.dir/all] 错误 2 make: *** [all] 错误 2
> > > 
> > > 
> > > 系统版本和 gcc/g++ 版本是什么？
> > 
> > 
> > CentOS Linux release 7.3.1611 (Core) gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)
> 
> 验证了 CentOS 7.9 安装 devtoolset gcc 8 可以编译，我们改一下文档


那老版本的centos有办法不？   还支持吗

**Comment by sangshuduo** [comment]
> > > > > > 哪个分支？我在 main 和 3.0 分支编译都没有问题
> > > > > 
> > > > > main分支；  
> > > > > 用build.sh编译是这个错误了：  
> > > > > TDengine/contrib/rocksdb/include/rocksdb/slice.h:26:62: 致命错误：string\_view：没有那个文件或目录 #include // RocksDB now requires C++17 support 编译中断。 make\[2\]: \*\*\* \[contrib/rocksdb/CMakeFiles/rocksdb-shared.dir/cache/cache.cc.o\] 错误 1 make\[1\]: \*\*\* \[contrib/rocksdb/CMakeFiles/rocksdb-shared.dir/all\] 错误 2 make: \*\*\* \[all\] 错误 2
> > > > 
> > > > 系统版本和 gcc/g++ 版本是什么？
> > > 
> > > CentOS Linux release 7.3.1611 (Core) gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)
> > 
> > 验证了 CentOS 7.9 安装 devtoolset gcc 8 可以编译，我们改一下文档
> 
> 那老版本的centos有办法不？ 还支持吗

主要是 gcc 要在 8 以上，和 CentOS 版本关系不大

**Comment by skyformat99** [comment]
> > > > > > > 哪个分支？我在 main 和 3.0 分支编译都没有问题
> > > > > > 
> > > > > > 
> > > > > > main分支；
> > > > > > 用build.sh编译是这个错误了：
> > > > > > TDengine/contrib/rocksdb/include/rocksdb/slice.h:26:62: 致命错误：string_view：没有那个文件或目录 #include // RocksDB now requires C++17 support 编译中断。 make[2]: *** [contrib/rocksdb/CMakeFiles/rocksdb-shared.dir/cache/cache.cc.o] 错误 1 make[1]: *** [contrib/rocksdb/CMakeFiles/rocksdb-shared.dir/all] 错误 2 make: *** [all] 错误 2
> > > > > 
> > > > > 
> > > > > 系统版本和 gcc/g++ 版本是什么？
> > > > 
> > > > 
> > > > CentOS Linux release 7.3.1611 (Core) gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)
> > > 
> > > 
> > > 验证了 CentOS 7.9 安装 devtoolset gcc 8 可以编译，我们改一下文档
> > 
> > 
> > 那老版本的centos有办法不？ 还支持吗
> 
> 主要是 gcc 要在 8 以上，和 CentOS 版本关系不大


哦。但很多老的设备，或者嵌入式设备，gcc版本都不高啊；
最好给个编译开关之类的，能忽略了。
RocksDB这破玩意，估计没有人用吧。

**Comment by sangshuduo** [comment]
> > > > > > > > 哪个分支？我在 main 和 3.0 分支编译都没有问题
> > > > > > > 
> > > > > > > 
> > > > > > > main分支；
> > > > > > > 用build.sh编译是这个错误了：
> > > > > > > TDengine/contrib/rocksdb/include/rocksdb/slice.h:26:62: 致命错误：string_view：没有那个文件或目录 #include // RocksDB now requires C++17 support 编译中断。 make[2]: *** [contrib/rocksdb/CMakeFiles/rocksdb-shared.dir/cache/cache.cc.o] 错误 1 make[1]: *** [contrib/rocksdb/CMakeFiles/rocksdb-shared.dir/all] 错误 2 make: *** [all] 错误 2
> > > > > > 
> > > > > > 
> > > > > > 系统版本和 gcc/g++ 版本是什么？
> > > > > 
> > > > > 
> > > > > CentOS Linux release 7.3.1611 (Core) gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)
> > > > 
> > > > 
> > > > 验证了 CentOS 7.9 安装 devtoolset gcc 8 可以编译，我们改一下文档
> > > 
> > > 
> > > 那老版本的centos有办法不？ 还支持吗
> > 
> > 
> > 主要是 gcc 要在 8 以上，和 CentOS 版本关系不大
> 
> 哦。但很多老的设备，或者嵌入式设备，gcc版本都不高啊； 最好给个编译开关之类的，能忽略了。 RocksDB这破玩意，估计没有人用吧。

欢迎 PR

**Comment by skyformat99** [comment]
> > > > > > > > > 哪个分支？我在 main 和 3.0 分支编译都没有问题
> > > > > > > > 
> > > > > > > > 
> > > > > > > > main分支；
> > > > > > > > 用build.sh编译是这个错误了：
> > > > > > > > TDengine/contrib/rocksdb/include/rocksdb/slice.h:26:62: 致命错误：string_view：没有那个文件或目录 #include // RocksDB now requires C++17 support 编译中断。 make[2]: *** [contrib/rocksdb/CMakeFiles/rocksdb-shared.dir/cache/cache.cc.o] 错误 1 make[1]: *** [contrib/rocksdb/CMakeFiles/rocksdb-shared.dir/all] 错误 2 make: *** [all] 错误 2
> > > > > > > 
> > > > > > > 
> > > > > > > 系统版本和 gcc/g++ 版本是什么？
> > > > > > 
> > > > > > 
> > > > > > CentOS Linux release 7.3.1611 (Core) gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)
> > > > > 
> > > > > 
> > > > > 验证了 CentOS 7.9 安装 devtoolset gcc 8 可以编译，我们改一下文档
> > > > 
> > > > 
> > > > 那老版本的centos有办法不？ 还支持吗
> > > 
> > > 
> > > 主要是 gcc 要在 8 以上，和 CentOS 版本关系不大
> > 
> > 
> > 哦。但很多老的设备，或者嵌入式设备，gcc版本都不高啊； 最好给个编译开关之类的，能忽略了。 RocksDB这破玩意，估计没有人用吧。
> 
> 欢迎 PR


最新版的好像解决了rocksdb的问题了。

但是出现另外一个一模一样的：
TDengine/source/libs/stream/src/stream.c:16:0:
TDengine/source/libs/stream/inc/streamInc.h:19:22: 致命错误：executor.h：没有那个文件或目录
 #include "executor.h"
                      ^
编译中断。
make[2]: *** [source/libs/stream/CMakeFiles/stream.dir/src/stream.c.o] 错误 1
make[1]: *** [source/libs/stream/CMakeFiles/stream.dir/all] 错误 2
make: *** [all] 错误 2
