### ISSUE TITLE
Failed to create an outputtype BINARY function

### ISSUE THREAD

**Issue by retanoj** [taosdata/TDengine#21649]
**Bug Description**
as title.

**To Reproduce**
`taos> create function foo as 'libfoo.so' outputtype binary;`

**Expected Behavior**
no error occur.

**Screenshots**
show as below:
```shell
taos> create function foo as 'libfoo.so' OUTPUTTYPE BINARY;

DB error: syntax error near ";" (2.478368s)
```

**Environment (please complete the following information):**
 - OS: macOS Monterrey 12.6.3
 - Docker: OrbStack - Docker version 23.0.6
 - TDengine Version: 3.0.4.2

**Comment by sangshuduo** [comment]
need to specify the binary length. For example OUTPUTTYPE BINARY(20).

**Comment by retanoj** [comment]
> need to specify the binary length. For example OUTPUTTYPE BINARY(20).

thx for the replying. But it not shows in document :(

And I found three vulnerbilities about tdengine. 
Could I report them on Github `Security -> Report a vulnerbility` ?
And Could I describe them on Chinese?

**Comment by sangshuduo** [comment]
> > need to specify the binary length. For example OUTPUTTYPE BINARY(20).
> 
> @sangshuduo thx for the replying. But it not shows in document :(

https://docs.tdengine.com/develop/udf/#udf-sample-code-in-c

> And I found three vulnerbilities about tdengine. Could I report them on Github `Security -> Report a vulnerbility` ? And Could I describe them on Chinese?
