### ISSUE TITLE
未知的架构Error: unknown architecture `native`

### ISSUE THREAD

**Issue by ningqingli** [taosdata/TDengine#21650]
ubuntu16下用arm交叉编译工具编译的，完整报错如下：
[ 45%] Built target planner
[ 45%] Building CXX object contrib/rocksdb/CMakeFiles/rocksdb-shared.dir/cache/cache.cc.o
Assembler messages:
Error: unknown architecture `native'

Error: unrecognized option -march=native
cc1plus: error: unrecognized argument in option '-march=native'
cc1plus: note: valid arguments to '-march=' are: armv2 armv2a armv3 armv3m armv4 armv4t armv5 armv5e armv5t armv5te armv6 armv6-m armv6j armv6k armv6s-m armv6t2 armv6z armv6zk armv7 armv7-a armv7-m armv7-r armv7e-m armv7ve armv8-a armv8-a+crc iwmmxt iwmmxt2 native
cc1plus: warning: unrecognized command line option "-Wno-errno=unused-private-field"
cc1plus: warning: unrecognized command line option "-Wno-format-truncation"
cc1plus: warning: unrecognized command line option "-Wno-reserved-user-defined-literal"
contrib/rocksdb/CMakeFiles/rocksdb-shared.dir/build.make:75: recipe for target 'contrib/rocksdb/CMakeFiles/rocksdb-shared.dir/cache/cache.cc.o' failed
make[2]: *** [contrib/rocksdb/CMakeFiles/rocksdb-shared.dir/cache/cache.cc.o] Error 1
CMakeFiles/Makefile2:1694: recipe for target 'contrib/rocksdb/CMakeFiles/rocksdb-shared.dir/all' failed
make[1]: *** [contrib/rocksdb/CMakeFiles/rocksdb-shared.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

这个是arm编译器不支持吗？

**Comment by sangshuduo** [comment]
不支持交叉编译
