### ISSUE TITLE
Sliding value can not less than 1% of interval value

### ISSUE THREAD

**Issue by snaseka** [taosdata/TDengine#21653]
I have statement to create an index with an expression `CREATE SMA INDEX my_db.my_index ON my_db.my_table FUNCTION(max(my_variable)) interval(60s) sliding(30s)`, but db response with an error `sliding value can not less than 1% of interval value`

**Comment by yu285** [comment]
May I know the version please?

And please provide output of the "show create table my_index;" to me .
