### ISSUE TITLE
 00003904 VND vgId:4 no free buffer pool on 635 try, wait 50 ms...

### ISSUE THREAD

**Issue by xutianyong** [taosdata/TDengine#21662]
**Bug Description**

**To Reproduce**
运行一段时间就会出现这个错误

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: windows server 2012
 - TDengine Version 3.0.2.6

**Additional Context**
06/06 14:16:48.738983 00004772 RPC WARN DND-S conn 000000D5C1535630 heartbeat received from 58.xxxx.xx.x.:43195, local info:172.16.5.89:6030, len:896, cost:51323983us, recv exception, gtid:0x145770590ae707:0x6ff008f590a0073f
06/06 14:16:48.787812 00003904 VND vgId:4 no free buffer pool on 631 try, wait 50 ms...
06/06 14:16:48.839569 00003904 VND vgId:4 no free buffer pool on 632 try, wait 50 ms...
06/06 14:16:48.891326 00003904 VND vgId:4 no free buffer pool on 633 try, wait 50 ms...
06/06 14:16:48.944060 00003904 VND vgId:4 no free buffer pool on 634 try, wait 50 ms...
06/06 14:16:48.995819 00003904 VND vgId:4 no free buffer pool on 635 try, wait 50 ms...
06/06 14:16:49.047576 00003904 VND vgId:4 no free buffer pool on 636 try, wait 50 ms...
06/06 14:16:49.099335 00003904 VND vgId:4 no free buffer pool on 637 try, wait 50 ms...
06/06 14:16:49.151092 00003904 VND vgId:4 no free buffer pool on 638 try, wait 50 ms...
06/06 14:16:49.202850 00003904 VND vgId:4 no free buffer pool on 639 try, wait 50 ms...
06/06 14:16:49.254607 00003904 VND vgId:4 no free buffer pool on 640 try, wait 50 ms...
06/06 14:16:49.306365 00003904 VND vgId:4 no free buffer pool on 641 try, wait 50 ms...
06/06 14:16:49.358123 00003904 VND vgId:4 no free buffer pool on 642 try, wait 50 ms...
06/06 14:16:49.409881 00003904 VND vgId:4 no free buffer pool on 643 try, wait 50 ms...
06/06 14:16:49.461638 00003904 VND vgId:4 no free buffer pool on 644 try, wait 50 ms...
06/06 14:16:49.513396 00003904 VND vgId:4 no free buffer pool on 645 try, wait 50 ms...
06/06 14:16:49.565154 00003904 VND vgId:4 no free buffer pool on 646 try, wait 50 ms...
06/06 14:16:49.616912 00003904 VND vgId:4 no free buffer pool on 647 try, wait 50 ms...
06/06 14:16:49.668669 00003904 VND vgId:4 no free buffer pool on 648 try, wait 50 ms...
06/06 14:16:49.721404 00003904 VND vgId:4 no free buffer pool on 649 try, wait 50 ms...
06/06 14:16:49.773161 00003904 VND vgId:4 no free buffer pool on 650 try, wait 50 ms...
06/06 14:16:49.824919 00003904 VND vgId:4 no free buffer pool on 651 try, wait 50 ms...
06/06 14:16:49.876677 00003904 VND vgId:4 no free buffer pool on 652 try, wait 50 ms...
06/06 14:16:49.928435 00003904 VND vgId:4 no free buffer pool on 653 try, wait 50 ms...
06/06 14:16:49.980193 00003904 VND vgId:4 no free buffer pool on 654 try, wait 50 ms...
06/06 14:16:50.031950 00003904 VND vgId:4 no free buffer pool on 655 try, wait 50 ms...
06/06 14:16:50.083708 00003904 VND vgId:4 no free buffer pool on 656 try, wait 50 ms...
06/06 14:16:50.135466 00003904 VND vgId:4 no free buffer pool on 657 try, wait 50 ms...
06/06 14:16:50.187224 00003904 VND vgId:4 no free buffer pool on 658 try, wait 50 ms...

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
