### ISSUE TITLE
3.0.4.1 windows10 TDengine crash

### ISSUE THREAD

**Issue by boomion** [taosdata/TDengine#21675]
运行过程中出现C++调试弹窗，日志文件内容如下：

06/08 18:58:49.026116 00054176 TSD vgId:3, tsdb finish commit
06/08 18:58:49.196963 00053108 VND vgId:2, commit end
06/08 18:58:49.214110 00054176 VND vgId:3, commit end
06/08 18:58:52.760845 00054168 VND vgId:2, propose vnode commit
06/08 18:58:52.760845 00027324 VND vgId:3, propose vnode commit
06/08 18:58:52.763559 00054168 VND vgId:2, commit at version 3722
06/08 18:58:52.764973 00027324 VND vgId:3, commit at version 3722
06/08 18:58:52.811038 00027324 VND vgId:3, vnode info is saved, fname:F:\data\tdengine\vnode\vnode3\vnode_tmp.json replica:1 selfIndex:0
06/08 18:58:52.811038 00054168 VND vgId:2, vnode info is saved, fname:F:\data\tdengine\vnode\vnode2\vnode_tmp.json replica:1 selfIndex:0
06/08 18:58:52.831148 00027324 VND vgId:3, vnode async commit done, commitId:122 term:2 applied:3722
06/08 18:58:52.831148 00054168 VND vgId:2, vnode async commit done, commitId:123 term:2 applied:3722
06/08 18:58:52.831148 00033044 VND vgId:3, start to commit, commitId:122 version:3722 term: 2
06/08 18:58:52.831148 00051584 VND vgId:2, start to commit, commitId:123 version:3722 term: 2
06/08 18:58:53.115107 00051584 TSD ERROR vgId:2, tsdbCommitFileDataImpl failed at line 1600 since Not found
06/08 18:58:53.118098 00051584 TSD ERROR vgId:2, tsdbCommitFileData failed at line 808 since Not found
06/08 18:58:53.190226 00051584 TSD ERROR vgId:2, tsdbCommitData failed at line 957 since Not found
06/08 18:58:53.191224 00051584 TSD ERROR vgId:2, tsdbEndCommit failed at line 1065 since Not found
06/08 18:58:53.193219 00051584 TSD ERROR vgId:2, tsdbCommit failed at line 188 since Not found
06/08 18:58:53.195214 00051584 VND ERROR vgId:2, vnodeCommitImpl failed at line 452 since Not found
06/08 18:58:54.646105 00033044 TSD vgId:3, tsdb end commit
06/08 18:58:54.648473 00033044 VND vnode info is committed, dir:F:\data\tdengine\vnode\vnode3
06/08 18:58:54.651548 00033044 TSD vgId:3, tsdb finish commit
06/08 18:58:54.799409 00033044 VND vgId:3, commit end
06/08 18:58:55.703138 00004000 MND stb:1.iot.original, start to retrieve meta
06/08 18:58:58.517032 00054168 VND vgId:2, propose vnode commit
06/08 18:58:58.517032 00027324 VND vgId:3, propose vnode commit
06/08 18:58:58.518051 00054168 VND vgId:2, commit at version 3754
06/08 18:58:58.520186 00027324 VND vgId:3, commit at version 3754
06/08 18:58:58.553405 00027324 VND vgId:3, vnode info is saved, fname:F:\data\tdengine\vnode\vnode3\vnode_tmp.json replica:1 selfIndex:0
06/08 18:58:58.553405 00054168 VND vgId:2, vnode info is saved, fname:F:\data\tdengine\vnode\vnode2\vnode_tmp.json replica:1 selfIndex:0
06/08 18:58:58.559844 00054168 UTL FATAL assert info not provided
06/08 18:58:58.560841 00054168 UTL FATAL tAssert at file C:\workroom\workspace\TDinternal\community\source\dnode\vnode\src\tsdb\tsdbCommit.c:156 exit:1
06/08 18:58:58.566825 00027324 VND vgId:3, vnode async commit done, commitId:123 term:2 applied:3754
06/08 18:58:58.566825 00053108 VND vgId:3, start to commit, commitId:123 version:3754 term: 2
06/08 18:58:58.605751 00054168 UTL FATAL obtained 14 stack frames

06/08 18:58:58.608836 00054168 UTL FATAL frame:0, cJSON_AddRawToObject - 0xC8E4CC93

06/08 18:58:58.609836 00054168 UTL FATAL frame:1, cJSON_AddRawToObject - 0xC8E4CC93

06/08 18:58:58.611830 00054168 UTL FATAL frame:2, cJSON_AddRawToObject - 0xC8E4CC93

06/08 18:58:58.613825 00054168 UTL FATAL frame:3, cJSON_AddRawToObject - 0xC8E4CC93

06/08 18:58:58.614822 00054168 UTL FATAL frame:4, cJSON_AddRawToObject - 0xC8E4CC93

06/08 18:58:58.616817 00054168 UTL FATAL frame:5, cJSON_AddRawToObject - 0xC8E4CC93

06/08 18:58:58.617814 00054168 UTL FATAL frame:6, cJSON_AddRawToObject - 0xC8E4CC93

06/08 18:58:58.618812 00054168 UTL FATAL frame:7, cJSON_AddRawToObject - 0xC8E4CC93

06/08 18:58:58.620806 00054168 UTL FATAL frame:8, cJSON_AddRawToObject - 0xC8E4CC93

06/08 18:58:58.624877 00054168 UTL FATAL frame:9, cJSON_AddRawToObject - 0xC8E4CC93

06/08 18:58:58.626872 00054168 UTL FATAL frame:10, cJSON_AddRawToObject - 0xC8E4CC93

06/08 18:58:58.628867 00054168 UTL FATAL frame:11, cJSON_AddRawToObject - 0xC8E4CC93

06/08 18:58:58.630861 00054168 UTL FATAL frame:12, BaseThreadInitThunk - 0x84E57600

06/08 18:58:58.631859 00054168 UTL FATAL frame:13, RtlUserThreadStart - 0x867E2680

06/08 18:59:00.175962 00053108 TSD vgId:3, tsdb end commit
06/08 18:59:00.177961 00053108 VND vnode info is committed, dir:F:\data\tdengine\vnode\vnode3
06/08 18:59:00.179962 00053108 TSD vgId:3, tsdb finish commit
06/08 18:59:00.277852 00053108 VND vgId:3, commit end
06/08 18:59:04.708395 00004000 MND stb:1.iot.original, start to retrieve meta
06/08 18:59:13.716797 00004000 MND stb:1.iot.original, start to retrieve meta
06/08 18:59:22.723343 00004000 MND stb:1.iot.original, start to retrieve meta

**Comment by yu285** [comment]
短期内，我们不建议使用 windows 版本，我们可以切换到 Linux或者在win上安装docker吗？

后续我们会抽出精力集中优化windows 版本的 TDengine。

如果在 Linux或者在win上安装docker的版本仍有这个问题，我可以远程排查下 ： 微信：a15652223354
