### ISSUE TITLE
Windows taosd start failed 

### ISSUE THREAD

**Issue by tusky2015** [taosdata/TDengine#21681]
操作系统：windows server 2016
TDengine版本：3.0.2.3
问题描述：电脑突然断电重启后taosd服务启动不起来，用客户端连接提示Database is starting up。升级到3.0.5.0也不行。

1.重启了好几次服务一直启动不起来
2.用命令行启动taosd.exe打印一段日志后卡住，然后taosd占用cpu直接拉到50%
3.打印日志如下：
==================================================
                new log file                      
==================================================
06/09 13:53:53.891478 00008564 DND startup path:not implemented on windows args:taosd.exe
06/09 13:53:53.906492 00008564 UTL apoll url not load
06/09 13:53:53.940282 00008564 UTL load from cfg file C:\TDengine\cfg\\taos.cfg success
06/09 13:53:53.948516 00008564 UTL env file:.env not load
06/09 13:53:53.957140 00008564 UTL load from env variables cfg success
06/09 13:53:53.974137 00008564 UTL                      global config
06/09 13:53:53.977139 00008564 UTL =================================================================
06/09 13:53:53.992155 00008564 UTL cfg_file     firstEp                  WIN-1C40VKHRESI:6030
06/09 13:53:54.022140 00008564 UTL default      secondEp                 WIN-1C40VKHRESI:6030
06/09 13:53:54.028139 00008564 UTL cfg_file     fqdn                     WIN-1C40VKHRESI
06/09 13:53:54.084632 00008564 UTL cfg_file     serverPort               6030
06/09 13:53:54.095631 00008564 UTL cfg_file     tempDir                  F:\TDengine\tmp
06/09 13:53:54.103636 00008564 UTL default      minimalTmpDirGB          1.00
06/09 13:53:54.111640 00008564 UTL default      shellActivityTimer       3
06/09 13:53:54.118633 00008564 UTL default      compressMsgSize          -1
06/09 13:53:54.156692 00008564 UTL default      compressColData          -1
06/09 13:53:54.164688 00008564 UTL default      queryPolicy              1
06/09 13:53:54.172688 00008564 UTL default      enableQueryHb            0
06/09 13:53:54.178690 00008564 UTL default      enableScience            0
06/09 13:53:54.187687 00008564 UTL default      querySmaOptimize         0
06/09 13:53:54.194695 00008564 UTL default      queryPlannerTrace        0
06/09 13:53:54.202698 00008564 UTL default      queryNodeChunkSize       32768
06/09 13:53:54.209694 00008564 UTL default      queryUseNodeAllocator    1
06/09 13:53:54.217690 00008564 UTL default      keepColumnName           0
06/09 13:53:54.226700 00008564 UTL default      smlChildTableName        
06/09 13:53:54.232694 00008564 UTL default      smlTagName               _tag_null
06/09 13:53:54.241229 00008564 UTL default      maxInsertBatchRows       1000000
06/09 13:53:54.250242 00008564 UTL default      maxRetryWaitTime         10000
06/09 13:53:54.258748 00008564 UTL default      useAdapter               0
06/09 13:53:54.263753 00008564 UTL default      crashReporting           1
06/09 13:53:54.271755 00008564 UTL default      queryMaxConcurrentTable  200
06/09 13:53:54.280760 00008564 UTL default      metaCacheMaxSize         -1
06/09 13:53:54.285751 00008564 UTL default      slowLogThreshold         3
06/09 13:53:54.294752 00008564 UTL default      slowLogScope             
06/09 13:53:54.301760 00008564 UTL default      numOfRpcThreads          2
06/09 13:53:54.307758 00008564 UTL default      numOfRpcSessions         10000
06/09 13:53:54.316758 00008564 UTL default      timeToGetAvailableConn   500000
06/09 13:53:54.324758 00008564 UTL default      numOfTaskQueueThreads    4
06/09 13:53:54.330759 00008564 UTL cfg_file     dataDir                  F:\TDengine\data
06/09 13:53:54.338792 00008564 UTL default      minimalDataDirGB         2.00
06/09 13:53:54.347786 00008564 UTL default      supportVnodes            8
06/09 13:53:54.355817 00008564 UTL default      maxShellConns            50000
06/09 13:53:54.360812 00008564 UTL default      statusInterval           1
06/09 13:53:54.369813 00008564 UTL default      minSlidingTime           1
06/09 13:53:54.377816 00008564 UTL default      minIntervalTime          1
06/09 13:53:54.382811 00008564 UTL default      maxNumOfDistinctRes      10000000
06/09 13:53:54.390821 00008564 UTL default      countAlwaysReturnValue   1
06/09 13:53:54.398817 00008564 UTL default      queryBufferSize          -1
06/09 13:53:54.404820 00008564 UTL default      printAuth                0
06/09 13:53:54.413819 00008564 UTL default      queryRspPolicy           0
06/09 13:53:54.420822 00008564 UTL default      numOfRpcThreads          2
06/09 13:53:54.426819 00008564 UTL default      numOfRpcSessions         10000
06/09 13:53:54.435820 00008564 UTL default      timeToGetAvailableConn   10000
06/09 13:53:54.442837 00008564 UTL default      numOfCommitThreads       2
06/09 13:53:54.452341 00008564 UTL default      numOfMnodeReadThreads    1
06/09 13:53:54.457404 00008564 UTL default      numOfVnodeQueryThreads   8
06/09 13:53:54.465404 00008564 UTL default      ratioOfVnodeStreamThrea  2.00
06/09 13:53:54.474408 00008564 UTL default      numOfVnodeFetchThreads   4
06/09 13:53:54.479399 00008564 UTL default      numOfVnodeRsmaThreads    4
06/09 13:53:54.487402 00008564 UTL default      numOfQnodeQueryThreads   8
06/09 13:53:54.496397 00008564 UTL default      numOfSnodeSharedThreads  2
06/09 13:53:54.502399 00008564 UTL default      numOfSnodeUniqueThreads  2
06/09 13:53:54.510401 00008564 UTL default      rpcQueueMemoryAllowed    1717939814
06/09 13:53:54.518410 00008564 UTL default      syncElectInterval        25000
06/09 13:53:54.524407 00008564 UTL default      syncHeartbeatInterval    1000
06/09 13:53:54.534408 00008564 UTL default      syncHeartbeatTimeout     20000
06/09 13:53:54.542931 00008564 UTL default      vndCommitMaxInterval     600000
06/09 13:53:54.548933 00008564 UTL default      mndSdbWriteDelta         200
06/09 13:53:54.558492 00008564 UTL default      mndLogRetention          2000
06/09 13:53:54.566491 00008564 UTL cfg_file     monitor                  1
06/09 13:53:54.573496 00008564 UTL default      monitorInterval          30
06/09 13:53:54.582494 00008564 UTL default      monitorFqdn              
06/09 13:53:54.588501 00008564 UTL default      monitorPort              6043
06/09 13:53:54.596494 00008564 UTL default      monitorMaxLogs           100
06/09 13:53:54.604498 00008564 UTL default      monitorComp              0
06/09 13:53:54.609512 00008564 UTL default      crashReporting           1
06/09 13:53:54.617495 00008564 UTL default      telemetryReporting       1
06/09 13:53:54.622496 00008564 UTL default      telemetryInterval        43200
06/09 13:53:54.630498 00008564 UTL default      telemetryServer          telemetry.tdengine.com
06/09 13:53:54.640036 00008564 UTL default      telemetryPort            80
06/09 13:53:54.648038 00008564 UTL default      transPullupInterval      2
06/09 13:53:54.654074 00008564 UTL default      mqRebalanceInterval      2
06/09 13:53:54.662073 00008564 UTL default      ttlUnit                  86400
06/09 13:53:54.669065 00008564 UTL default      ttlPushInterval          3600
06/09 13:53:54.675068 00008564 UTL default      uptimeInterval           300
06/09 13:53:54.684071 00008564 UTL default      queryRsmaTolerance       1000
06/09 13:53:54.692067 00008564 UTL default      walFsyncDataSizeLimit    104857600
06/09 13:53:54.697072 00008564 UTL default      udf                      1
06/09 13:53:54.705070 00008564 UTL default      udfdResFuncs             
06/09 13:53:54.713068 00008564 UTL default      udfdLdLibPath            
06/09 13:53:54.719088 00008564 UTL default      disableStream            0
06/09 13:53:54.726074 00008564 UTL default      streamBufferSize         134217728
06/09 13:53:54.733076 00008564 UTL default      checkpointInterval       10800000
06/09 13:53:54.742604 00008564 UTL default      cacheLazyLoadThreshold   500
06/09 13:53:54.751094 00008564 UTL default      filterScalarMode         0
06/09 13:53:54.758139 00008564 UTL default      maxStreamBackendCache    128
06/09 13:53:54.764140 00008564 UTL default      configDir                C:\TDengine\cfg\
06/09 13:53:54.773115 00008564 UTL default      scriptDir                C:\TDengine\cfg\
06/09 13:53:54.782148 00008564 UTL cfg_file     logDir                   F:\TDengine\log
06/09 13:53:54.790157 00008564 UTL default      minimalLogDirGB          1.00
06/09 13:53:54.795117 00008564 UTL default      numOfLogLines            10000000
06/09 13:53:54.805114 00008564 UTL default      asyncLog                 1
06/09 13:53:54.813136 00008564 UTL default      logKeepDays              0
06/09 13:53:54.818132 00008564 UTL default      debugFlag                0
06/09 13:53:54.826158 00008564 UTL default      simDebugFlag             143
06/09 13:53:54.834166 00008564 UTL default      tmrDebugFlag             131
06/09 13:53:54.840175 00008564 UTL default      uDebugFlag               131
06/09 13:53:54.848287 00008564 UTL default      rpcDebugFlag             131
06/09 13:53:54.855220 00008564 UTL default      jniDebugFlag             131
06/09 13:53:54.861212 00008564 UTL default      qDebugFlag               131
06/09 13:53:54.872216 00008564 UTL default      cDebugFlag               131
06/09 13:53:54.880206 00008564 UTL default      dDebugFlag               131
06/09 13:53:54.888211 00008564 UTL default      vDebugFlag               131
06/09 13:53:54.895217 00008564 UTL default      mDebugFlag               131
06/09 13:53:54.903217 00008564 UTL default      wDebugFlag               131
06/09 13:53:54.911210 00008564 UTL default      sDebugFlag               131
06/09 13:53:54.916207 00008564 UTL default      tsdbDebugFlag            131
06/09 13:53:54.924210 00008564 UTL default      tqDebugFlag              131
06/09 13:53:54.933210 00008564 UTL default      fsDebugFlag              131
06/09 13:53:54.939254 00008564 UTL default      udfDebugFlag             131
06/09 13:53:54.946744 00008564 UTL default      smaDebugFlag             131
06/09 13:53:54.953743 00008564 UTL default      idxDebugFlag             131
06/09 13:53:54.969937 00008564 UTL default      tdbDebugFlag             131
06/09 13:53:54.978943 00008564 UTL default      metaDebugFlag            131
06/09 13:53:54.983944 00008564 UTL default      timezone                 Asia/Shanghai (UTC, +0800)
06/09 13:53:54.992940 00008564 UTL default      locale                   en_US.UTF-8
06/09 13:53:55.000938 00008564 UTL default      charset                  UTF-8
06/09 13:53:55.008942 00008564 UTL default      assert                   1
06/09 13:53:55.014942 00008564 UTL default      enableCoreFile           1
06/09 13:53:55.020944 00008564 UTL default      numOfCores               4.00
06/09 13:53:55.028941 00008564 UTL default      SSE42                    0
06/09 13:53:55.034942 00008564 UTL default      AVX                      0
06/09 13:53:55.042973 00008564 UTL default      AVX2                     0
06/09 13:53:55.053980 00008564 UTL default      FMA                      0
06/09 13:53:55.059242 00008564 UTL default      SIMD-builtins            0
06/09 13:53:55.067259 00008564 UTL default      tagFilterCache           0
06/09 13:53:55.074248 00008564 UTL default      openMax                  0
06/09 13:53:55.081243 00008564 UTL default      streamMax                0
06/09 13:53:55.089251 00008564 UTL default      pageSizeKB               0
06/09 13:53:55.096255 00008564 UTL default      totalMemoryKB            16776756
06/09 13:53:55.102244 00008564 UTL default      os sysname               Windows_NT
06/09 13:53:55.110276 00008564 UTL default      os nodename              WIN-1C40VKHRESI
06/09 13:53:55.119249 00008564 UTL default      os release               6
06/09 13:53:55.127258 00008564 UTL default      os version               2
06/09 13:53:55.132248 00008564 UTL default      os machine               AMD64
06/09 13:53:55.142290 00008564 UTL default      version                  3.0.5.0
06/09 13:53:55.150796 00008564 UTL default      compatible_version       3.0.0.0
06/09 13:53:55.156813 00008564 UTL default      gitinfo                  e6ddaa7d4e7d0a7909ad16bf15f237bab25dd860
06/09 13:53:55.166813 00008564 UTL default      buildinfo                Built at 2023-06-08 01:35:20
06/09 13:53:55.176808 00008564 UTL =================================================================
06/09 13:53:55.197823 00008564 DND start to init dnode env
06/09 13:53:55.205814 00008564 DND succceed to read dnode file F:\TDengine\data\dnode\dnode.json
06/09 13:53:55.216825 00008564 DND succceed to read mnode file F:\TDengine\data\mnode\mnode.json
06/09 13:53:55.225824 00008564 DND file:F:\TDengine\data\qnode\qnode.json not exist
06/09 13:53:55.235829 00008564 DND file:F:\TDengine\data\snode\snode.json not exist
06/09 13:53:55.254872 00008564 DND dnode env is initialized
06/09 13:53:55.260865 00008564 DND start to init service
06/09 13:53:55.268866 00008564 DND node:dnode, start to open
06/09 13:53:55.274862 00008564 UTL worker:dnode-mgmt is initialized, min:1 max:1
06/09 13:53:55.283862 00008564 UTL worker:dnode-mgmt:0 is launched, total:1
06/09 13:53:55.283862 00007608 UTL worker:dnode-mgmt:0 is running, thread:00007608
06/09 13:53:55.291862 00008564 UTL worker:dnode-mgmt, queue:000002B7B18EEF50 is allocated, ahandle:000002B7B56F2D90
06/09 13:53:55.311874 00004644 UDF start to init udfd
06/09 13:53:55.316868 00004644 UDF udfd LD_LIBRARY_PATH: :
06/09 13:53:55.327867 00004644 UDF udfd is initialized
06/09 13:53:55.334864 00008564 DND node:dnode, has been opened
06/09 13:53:55.341390 00008564 DND node:mnode, start to open
06/09 13:53:55.349388 00008564 WAL wal module is initialized, rsetId:4
06/09 13:53:55.360445 00008564 DND succceed to read mnode file F:\TDengine\data\mnode\mnode.json
06/09 13:53:55.370444 00008564 DND mnode start to open
06/09 13:53:55.377441 00008564 MND start to open mnode in F:\TDengine\data\mnode
06/09 13:53:55.390446 00008564 WAL vgId:1, reset commitVer to 56123
06/09 13:53:55.399447 00008564 MND mnode-wal is initialized
06/09 13:53:55.404452 00008564 MND start to init sdb in F:\TDengine\data\mnode
06/09 13:53:55.414455 00008564 MND sdb init success
06/09 13:53:55.421446 00008564 MND mnode-sdb is initialized
06/09 13:53:55.431445 00008564 MND sdb table:trans is initialized
06/09 13:53:55.436445 00008564 MND mnode-trans is initialized
06/09 13:53:55.445985 00008564 MND sdb table:cluster is initialized
06/09 13:53:55.454490 00008564 MND mnode-cluster is initialized
06/09 13:53:55.459594 00008564 MND sdb table:mnode is initialized
06/09 13:53:55.468593 00008564 MND mnode-mnode is initialized
06/09 13:53:55.476595 00008564 MND sdb table:qnode is initialized
06/09 13:53:55.482596 00008564 MND mnode-qnode is initialized
06/09 13:53:55.490595 00008564 MND sdb table:snode is initialized
06/09 13:53:55.498599 00008564 MND mnode-snode is initialized
06/09 13:53:55.503597 00008564 MND sdb table:dnode is initialized
06/09 13:53:55.513599 00008564 MND mnode-dnode is initialized
06/09 13:53:55.520599 00008564 MND sdb table:user is initialized
06/09 13:53:55.526597 00008564 MND mnode-user is initialized
06/09 13:53:55.534596 00008564 MND mnode-grant is initialized
06/09 13:53:55.543132 00008564 MND mnode-privilege is initialized
06/09 13:53:55.549129 00008564 MND sdb table:acct is initialized
06/09 13:53:55.557194 00008564 MND mnode-acct is initialized
06/09 13:53:55.564198 00008564 MND sdb table:stream is initialized
06/09 13:53:55.570202 00008564 MND mnode-stream is initialized
06/09 13:53:55.580187 00008564 MND sdb table:topic is initialized
06/09 13:53:55.587199 00008564 MND mnode-topic is initialized
06/09 13:53:55.592192 00008564 MND sdb table:consumer is initialized
06/09 13:53:55.600208 00008564 MND mnode-consumer is initialized
06/09 13:53:55.607215 00008564 MND sdb table:subscribe is initialized
06/09 13:53:55.615248 00008564 MND mnode-subscribe is initialized
06/09 13:53:55.623222 00008564 MND sdb table:vgroup is initialized
06/09 13:53:55.629189 00008564 MND mnode-vgroup is initialized
06/09 13:53:55.637201 00008564 MND sdb table:stb is initialized
06/09 13:53:55.645236 00008564 MND mnode-stb is initialized
06/09 13:53:55.650222 00008564 MND sdb table:sma is initialized
06/09 13:53:55.657253 00008564 MND mnode-sma is initialized
06/09 13:53:55.665260 00008564 MND sdb table:idx is initialized
06/09 13:53:55.671255 00008564 MND mnode-idx is initialized
06/09 13:53:55.679256 00008564 MND mnode-infos is initialized
06/09 13:53:55.686256 00008564 MND mnode-perfs is initialized
06/09 13:53:55.692256 00008564 MND sdb table:db is initialized
06/09 13:53:55.702263 00008564 MND mnode-db is initialized
06/09 13:53:55.707248 00008564 MND sdb table:func is initialized
06/09 13:53:55.715264 00008564 MND mnode-func is initialized
06/09 13:53:55.722264 00008564 MND start to reset sdb
06/09 13:53:55.728250 00008564 MND sdb:trans is reset
06/09 13:53:55.736249 00008564 MND sdb:cluster is reset
06/09 13:53:55.743783 00008564 MND sdb:mnode is reset
06/09 13:53:55.749274 00008564 MND sdb:qnode is reset
06/09 13:53:55.757997 00008564 MND sdb:snode is reset
06/09 13:53:55.765993 00008564 MND sdb:dnode is reset
06/09 13:53:55.769988 00008564 MND sdb:user is reset
06/09 13:53:55.777999 00008564 MND sdb:acct is reset
06/09 13:53:55.781993 00008564 MND sdb:stream is reset
06/09 13:53:55.790988 00008564 MND sdb:subscribe is reset
06/09 13:53:55.797989 00008564 MND sdb:consumer is reset
06/09 13:53:55.802996 00008564 MND sdb:topic is reset
06/09 13:53:55.810998 00008564 MND sdb:vgroup is reset
06/09 13:53:55.815993 00008564 MND sdb:sma is reset
06/09 13:53:55.824991 00008564 MND sdb:stb is reset
06/09 13:53:55.829995 00008564 MND sdb:db is reset
06/09 13:53:55.835006 00008564 MND sdb:func is reset
06/09 13:53:55.843539 00008564 MND sdb:idx is reset
06/09 13:53:55.850025 00008564 MND sdb reset success
06/09 13:53:55.857117 00008564 MND start to read sdb file:F:\TDengine\data\mnode\data\sdb.data
06/09 13:53:55.880128 00008564 MND db:1.dlfw_data, tsdbPageSize set from 4 to default 4
06/09 13:53:55.889127 00008564 MND db:1.dlfw_data, sstTrigger set from 8 to default 1
06/09 13:53:55.898125 00008564 MND vgId:1, has ready mnode:1, status:ready
06/09 13:53:55.906128 00008564 MND vgId:1, ep:WIN-1C40VKHRESI:6030 dnode:1
06/09 13:53:55.914119 00008564 MND vgId:1, mnode:1, role:0, lastIndex:0
06/09 13:53:55.922133 00008564 MND read sdb file:F:\TDengine\data\mnode\data\sdb.data success, commit index:135876 term:251 config:-1
06/09 13:53:55.940123 00008564 MND mnode-sdb is initialized
06/09 13:53:55.948645 00008564 MND mnode-profile is initialized
06/09 13:53:55.966275 00008564 MND mnode-show is initialized
06/09 13:53:55.979277 00008564 MND mnode-query is initialized
06/09 13:53:55.989287 00008564 MND vgId:1, start to open sync, replica:0 selfIndex:0
06/09 13:53:56.005272 00008564 SYN vgId:0, succceed to read sync cfg file F:\TDengine\data\mnode\sync\raft_config.json
06/09 13:53:56.016276 00008564 SYN vgId:0, use sync config from sync cfg file
06/09 13:53:56.025287 00008564 SYN vgId:1, start to open sync node, totalReplicaNum:1 replicaNum:1 selfIndex:0
06/09 13:53:56.039290 00008564 DND dnode:WIN-1C40VKHRESI:6030, update dnodeId to dnode:1
06/09 13:53:56.049806 00008564 SYN vgId:1, index:0 ep:WIN-1C40VKHRESI:6030 dnode:1 cluster:7647536754175906909
06/09 13:53:56.061826 00008564 SYN vgId:1, sync addr:15521115555443507201, dnode:1 cluster:7647536754175906909 fqdn:WIN-1C40VKHRESI ip:172.17.1.55 port:6030 ipv4:922816940
06/09 13:53:56.081833 00008564 SYN vgId:1, sync addr:15521115555443507201, dnode:1 cluster:7647536754175906909 fqdn:WIN-1C40VKHRESI ip:172.17.1.55 port:6030 ipv4:922816940
06/09 13:53:56.098828 00008564 SYN vgId:1, succceed to read raft store file F:\TDengine\data\mnode\sync\raft_store.json
06/09 13:53:56.111826 00008564 SYN vgId:1, sync node commitIndex initialized as 135876
06/09 13:53:56.122833 00008564 SYN vgId:1, init sync log buffer. buffer: [135876 135876 135882, 135883)
06/09 13:53:56.132842 00008564 SYN vgId:1, sync open, node:000002B7B57B5C00 electInterval:25000 heartbeatInterval:1000 heartbeatTimeout:20000, sync:follower, term:251, commit-index:135876, applied-index:135876, first-ver:0, last-ver:135882, min:-1, snap:135876, snap-term:251, elect-times:0, as-leader-times:0, cfg-ch-times:0, hb-slow:0, hbr-slow:0, aq-items:-1, snaping:-1, replicas:1, last-cfg:-1, chging:0, restore:0, quorum:1, elect-lc-timer:0, hb:0, buffer:[135876 135876 135882, 135883), repl-mgrs:{0:0 [0 0, 0)}, members:{num:1, as:0, [WIN-1C40VKHRESI:6030]}, hb:{0:1686290036111}, hb-reply:{0:1686290036111}
06/09 13:53:56.191568 00008564 MND mnode-sync is opened, id:2
06/09 13:53:56.199571 00008564 MND mnode-sync is initialized
06/09 13:53:56.206571 00008564 MND mnode-telem is initialized
06/09 13:53:56.211570 00008564 MND mnode open successfully
06/09 13:53:56.220588 00008564 UTL worker:mnode-query is initialized, min:4 max:4
06/09 13:53:56.229571 00008564 UTL worker:mnode-query:0 is launched, total:1
06/09 13:53:56.230569 00006044 UTL worker:mnode-query:0 is running, thread:00006044
06/09 13:53:56.236572 00008564 UTL worker:mnode-query:1 is launched, total:2
06/09 13:53:56.238574 00008452 UTL worker:mnode-query:1 is running, thread:00008452
06/09 13:53:56.256096 00008564 UTL worker:mnode-query:2 is launched, total:3
06/09 13:53:56.256096 00006344 UTL worker:mnode-query:2 is running, thread:00006344
06/09 13:53:56.273121 00008564 UTL worker:mnode-query:3 is launched, total:4
06/09 13:53:56.273121 00000976 UTL worker:mnode-query:3 is running, thread:00000976
06/09 13:53:56.295124 00008564 UTL worker:mnode-query, queue:000002B7B18D4B90 is allocated, ahandle:000002B7B18C4DD0
06/09 13:53:56.311119 00008564 UTL worker:mnode-fetch is initialized, min:1 max:1
06/09 13:53:56.322134 00008564 UTL worker:mnode-fetch:0 is launched, total:1
06/09 13:53:56.322134 00007408 UTL worker:mnode-fetch:0 is running, thread:00007408
06/09 13:53:56.337126 00008564 UTL worker:mnode-fetch, queue:000002B7B18EEB40 is allocated, ahandle:000002B7B18C4DD0
06/09 13:53:56.358166 00008564 UTL worker:mnode-read is initialized, min:1 max:1
06/09 13:53:56.367163 00008564 UTL worker:mnode-read:0 is launched, total:1
06/09 13:53:56.367163 00007160 UTL worker:mnode-read:0 is running, thread:00007160
06/09 13:53:56.377160 00008564 UTL worker:mnode-read, queue:000002B7B58B7D30 is allocated, ahandle:000002B7B18C4DD0
06/09 13:53:56.398168 00008564 UTL worker:mnode-write is initialized, min:1 max:1
06/09 13:53:56.404175 00008564 UTL worker:mnode-write:0 is launched, total:1
06/09 13:53:56.406164 00008888 UTL worker:mnode-write:0 is running, thread:00008888
06/09 13:53:56.412163 00008564 UTL worker:mnode-write, queue:000002B7B58B7DE0 is allocated, ahandle:000002B7B18C4DD0
06/09 13:53:56.435171 00008564 UTL worker:mnode-sync is initialized, min:1 max:1
06/09 13:53:56.444762 00008564 UTL worker:mnode-sync:0 is launched, total:1
06/09 13:53:56.444762 00008976 UTL worker:mnode-sync:0 is running, thread:00008976
06/09 13:53:56.453199 00008564 UTL worker:mnode-sync, queue:000002B7B58B7E90 is allocated, ahandle:000002B7B18C4DD0
06/09 13:53:56.472787 00008564 UTL worker:mnode-sync-rd is initialized, min:1 max:1
06/09 13:53:56.479835 00008564 UTL worker:mnode-sync-rd:0 is launched, total:1
06/09 13:53:56.481803 00001672 UTL worker:mnode-sync-rd:0 is running, thread:00001672
06/09 13:53:56.488798 00008564 UTL worker:mnode-sync-rd, queue:000002B7B58B7F40 is allocated, ahandle:000002B7B18C4DD0
06/09 13:53:56.511811 00008564 DND node:mnode, has been opened
06/09 13:53:56.519521 00008564 DND node:vnode, start to open
06/09 13:53:56.528798 00008564 UTL worker:vnode-query is initialized, min:8 max:8
06/09 13:53:56.537794 00008564 UTL worker:vnode-stream is initialized as auto
06/09 13:53:56.548327 00008564 UTL worker:vnode-fetch is initialized, max:4
06/09 13:53:56.556318 00008564 UTL worker:vnode-mgmt is initialized, min:1 max:1
06/09 13:53:56.565338 00008564 UTL worker:vnode-mgmt:0 is launched, total:1
06/09 13:53:56.566338 00006788 UTL worker:vnode-mgmt:0 is running, thread:00006788
06/09 13:53:56.574339 00008564 UTL worker:vnode-mgmt, queue:000002B7B5A34920 is allocated, ahandle:000002B7B57C1660
06/09 13:53:56.596357 00008564 DND succceed to read vnode file F:\TDengine\data\vnode\vnodes.json
06/09 13:53:56.605341 00008564 DND open 2 vnodes with 2 threads
06/09 13:53:56.613342 00006960 DND thread:0, start to open 1 vnodes
06/09 13:53:56.613342 00001780 DND thread:1, start to open 1 vnodes
06/09 13:53:56.620356 00006960 DND dnode:WIN-1C40VKHRESI:6030, update dnodeId to dnode:1
06/09 13:53:56.629374 00001780 DND dnode:WIN-1C40VKHRESI:6030, update dnodeId to dnode:1
06/09 13:57:01.321186 00004776 DND shut down signal is 21

**Comment by yu285** [comment]
短期内，我们不建议使用 windows 版本，我们可以切换到 Linux或者在win上安装docker吗？

后续我们会抽出精力集中优化windows 版本的 TDengine。

如果在 Linux或者在win上安装docker的版本仍有这个问题，我可以远程排查下 ： 微信：a15652223354
