### ISSUE TITLE
two-stage cleanup

### ISSUE THREAD

**Issue by freemine** [taosdata/TDengine#2169]
tdengine seems to follow such design pattern in dynamic object ctor/dtor:
**taosInitXXXX:** as ctor
**taosCleanUpXXXX:** as dtor
for memory-only object, it's simple and clear. but for those with thread-wrapped objects, it gets complex. as now, we see two steps in **taosCleanUpXXXX:**
1. **notify thread to exit**
2. **wait thread to exit**
3. **release other resources**

if threads are designed to cooperate together to get the logic done. things get worse, especially when app is requested to exit. this is confirmed with valgrind, lots of leakage is recorded when **taosd**/**taos** exits.

digging into this, we found basically there are timer threads/schedule tasks threads are racing and cooperating during runtime. But when exiting, there is no specially step to tackle, which results in data-racing problem which is so hard to tackle. in order not to make process crash, we see codes surrending to this by leaving memory as is. for example:

`
void taosCloseLog() {

  taosStopLog();

  tsem_post(&(tsLogObj.logHandle->buffNotEmpty));

  if (taosCheckPthreadValid(tsLogObj.logHandle->asyncThread)) {

    pthread_join(tsLogObj.logHandle->asyncThread, NULL);

  }

  // In case that other threads still use log resources causing invalid write in valgrind

  // we comment two lines below.

  // taosLogBuffDestroy(tsLogObj.logHandle);

  // taosCloseLog();

}
`

i tried to use seperate-two-stage-exit to handle this when exiting app (for those statically-searchable threaded-objects)
1. **register atexit routine when exiting process**
1. **in atexit-ed routine, setting app exit cancelling flag**
3. **call statically-searchable object's __close/__cleanup routines**
4. **in atexit-ed routine, setting app exit destroying flag**
5. **call statically-searchable object's __close/__cleanup routines again**
note: it's __close/_cleanup's responsiblility to check whether it's now cancellable/destroyable stage

in such way, i simply checked with valgrind, taosd seems resolved in below situations:
1. **starting taosd, wait seconds, Ctrl-C**
2. **starting taosd, (starting taos, exit taos)..., Ctrl-C taosd to exit**

this seems aggressive, preliminary and problem-prone, i just push to **with-atexit** branch in my-forked repo
[https://github.com/freemine/TDengine.git](url)

please comments. thx!

**Comment by Aries-Lee1991** [comment]
wait a moment. the related R&D will check it.

**Comment by Aries-Lee1991** [comment]
@freemine The issue is no update for 19 days. Did you solute it?

**Comment by freemine** [comment]
@Aries-Lee1991 you means that i send a PR?

**Comment by sangshuduo** [comment]
@freemine PR is welcomed. :)

**Comment by freemine** [comment]
haven't spent time on tdengine for months.
seems like lots of changes have been made, and simply, there's only tlog leakage when taosd terminates.

it'll be solved simply by doing this at src/util/src/tlog.c now:

```
+
+static pthread_once_t        once = {0};
+
+static void exit_log(void) {
+  taosLogBuffDestroy(tsLogObj.logHandle);
+}
+
+static void init_exit(void) {
+  atexit(exit_log);
+}
+
+void taosCloseLog() {
+  taosStopLog();
+  tsem_post(&(tsLogObj.logHandle->buffNotEmpty));
+  if (taosCheckPthreadValid(tsLogObj.logHandle->asyncThread)) {
+    pthread_join(tsLogObj.logHandle->asyncThread, NULL);
+  }
+  // In case that other threads still use log resources causing invalid write in valgrind
+  // we comment two lines below.
+  if (0) taosLogBuffDestroy(tsLogObj.logHandle);
+  // taosCloseLog();
+
+  pthread_once(&once, init_exit);
+}

```

**Comment by sangshuduo** [comment]
@localvar could you please review freemine's suggestion?
