### ISSUE TITLE
select count(*) query timeout

### ISSUE THREAD

**Issue by longcf6666** [taosdata/TDengine#21703]
超级表上亿数据，10000+子表。count（*）直接超时，查不出来。
应该是有不少相同时间戳导致的更新操作。既然能够以insert形式更新，现在导致count（*）都没办法查询了，这个可以优化解决一下吗?
后面尝试一下where加时间条件，筛选只查询一天的数据，同样是查不出来。
taos版本已升级为最新的3.0.50

**Comment by jandison** [comment]
碰到同样的情况，有解决方案吗？

**Comment by longcf6666** [comment]
> 碰到同样的情况，有解决方案吗？

没有，很头痛，现在想统计一共有多少条数据，count(*)出不来

**Comment by sangshuduo** [comment]
解决乱序导致的查询超时，企业版可以使用 compact 功能，社区可以使用 taosdump 备份下数据后重新导入

**Comment by winnyrain** [comment]
> 超级表上亿数据，10000+子表。count（_）直接超时，查不出来。 应该是有不少相同时间戳导致的更新操作。既然能够以insert形式更新，现在导致count（_）都没办法查询了，这个可以优化解决一下吗? 后面尝试一下where加时间条件，筛选只查询一天的数据，同样是查不出来。 taos版本已升级为最新的3.0.50

社区版就是给你玩而已，根本用不了
