### ISSUE TITLE
taos与sqlalchemy结合查询数据有问题

### ISSUE THREAD

**Issue by zhouzhou98** [taosdata/TDengine#21700]
### 数据表t_trade_date
`CREATE STABLE `t_trade_date` (`parttime` TIMESTAMP, `trade_date` VARCHAR(16)) TAGS (`type` VARCHAR(16))`
### 结合代码
```
from sqlalchemy import create_engine, Column, String, DateTime
from sqlalchemy.orm import sessionmaker, declarative_base
# 创建连接URL
url = "taosrest://root:taosdata@127.0.0.1:6041/qt_data"
engine = create_engine(url)
Base = declarative_base()
class trade_date(Base):
    __tablename__ = 't_trade_date'
    parttime = Column(DateTime)
    trade_date = Column(String)
    type = Column(String, primary_key= True)
session = sessionmaker(bind=engine)()
results = session.query(trade_date).all()
print(len(results))
for res in results:
    print(res.type)
```
得出的结果长度是：1
<img width="1297" alt="1" src="https://github.com/taosdata/TDengine/assets/43700073/09a39acb-7706-4b94-8ee4-9c7dc4f28633">
但是实际长度有：
![2](https://github.com/taosdata/TDengine/assets/43700073/29e875bd-8cb1-4ff9-b1e4-95646f436dd4)

**Comment by sangshuduo** [comment]
目前 SQLAlchemy 支持 read\_sql() 接口
