### ISSUE TITLE
tdengine想建一个自动清除数据的普通表，使用ttl参数，但是一直报ttl的语法错误，看了文档也没看出来错误

### ISSUE THREAD

**Issue by clm123456** [taosdata/TDengine#21720]
CREATE TABLE normal_shear_wave2
    (   ts                   TIMESTAMP,
        value             double,
        packet_id BINARY(50) 
) TTL  6;

**Comment by clm123456** [comment]
![image](https://github.com/taosdata/TDengine/assets/58735160/96b33085-3830-4013-bda0-cddef7f89fbd)

**Comment by sangshuduo** [comment]
TDengine 什么版本？

**Comment by clm123456** [comment]
2.6.0.12

**Comment by luckeverda** [comment]
截图怎么看着像是 数字1 不是 字母l

**Comment by dfk-753** [comment]
我也是使用ttl参数一直提示语法错误
