### ISSUE TITLE
taos3.0.4.2占用内存居高不下，最终堵塞写入速度

### ISSUE THREAD

**Issue by HeheYang** [taosdata/TDengine#21724]
taos3.0.4.2
缓存内存一直增长，写入会因为内存变大而越来越慢，即时停掉写入，taosd所占内存也不会下降，请问是否存在内存泄漏问题呢或者有什么方式能阻止内存一直增长所带来的写入问题呢？
![image](https://github.com/taosdata/TDengine/assets/19985390/91289bfe-4bb1-4820-b5aa-adfaa0e806d0)
![image](https://github.com/taosdata/TDengine/assets/19985390/c584824d-7ae7-4586-977d-6f81a63ee972)

场景：
代码没法发，，场景可以告知，
写入方式：JDBC使用sql拼接 ：insert into t1 values() t2 values() ts values(),
8000条一个批次，最高600并发写入

数据库配置 500w个子表，3副本 *300vgroups，buffer 48M 

数据库建库：
CREATE DATABASE `pv_data` BUFFER 48 CACHESIZE 1 CACHEMODEL 'none' COMP 2 DURATION 14400m WAL_FSYNC_PERIOD 0 MAXROWS 4096 MINROWS 200 STT_TRIGGER 1 KEEP 525600m,525600m,525600m PAGES 512 PAGESIZE 128 PRECISION 'ms' REPLICA 3 WAL_LEVEL 1 VGROUPS 300 SINGLE_STABLE 0 TABLE_PREFIX 0 TABLE_SUFFIX 0 TSDB_PAGESIZE 4 WAL_RETENTION_PERIOD 0 WAL_RETENTION_SIZE 0 WAL_ROLL_PERIOD 0 WAL_SEGMENT_SIZE 0

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，因此建议直接安装最新版软件3.3.0.3即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
