### ISSUE TITLE
Sync leader is unreachable

### ISSUE THREAD

**Issue by xieyj-apple** [taosdata/TDengine#21745]
客户端程序在window上，执行循环insert数据，大概率出现“Sync leader is unreachable”错误，且耗时10s+  
var taosUri = "root:taosdata@tcp(10.60.01:6030)/test"
taos, err := sql.Open("taosSql", taosUri)
if err != nil {
		fmt.Println("failed to connect TDengine, err:", err)
		return
	}
defer taos.Close()
_sql := “insert into tableA using table values(...)”
_, err := taos.Exec(_sql)

**Comment by xieyj-apple** [comment]
when  i use rest to insert  ,it same

06/15 20:20:04.333041 00018688 taos_ADAPTER error "" model=restful req_id=0x29300beff6d00002 error_msg=Sync leader is unreachable sql=INSERT INTO testTable_1686831590733 USING testTable TAGS(1686831590733) VALUES (1686831590733843800, 1686831590733843800,null,null,'55ac5e4dc81d4ef196dcf0e951ca81ea',0,null,'content:55ac5e4dc81d4ef196dcf0e951ca81ea',1,null,null, 0,null,1686831590733843800) error_code=2316

**Comment by xieyj-apple** [comment]
问题出在 本地没有配置集群三台的host解析

**Comment by 1247776995** [comment]
> 问题出在 本地没有配置集群三台的host解析

请问怎么配置，我现在远程访问k8s tdengine集群就会报这个错
