### ISSUE TITLE
node connector install failed 

### ISSUE THREAD

**Issue by sytpb** [taosdata/TDengine#2175]
Env:

window 10 
nodejs v12 

-----------------------------------------------------------------------------------------------

gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:303:12)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\micro-express4(for weixin)\node_modules\ref
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by Aries-Lee1991** [comment]
@StoneT2000 When you are free, please check the issue.

**Comment by StoneT2000** [comment]
At the moment, nodejs v12 does not work, you will need nodejs v10

This is due to the node-ffi dependency needed to interact with the C API of the tdengine

**Comment by sytpb** [comment]
ok, got it ,thanks a lot .
