### ISSUE TITLE
create database error

### ISSUE THREAD

**Issue by pnpdb** [taosdata/TDengine#21765]
taos> CREATE DATABASE IF NOT EXISTS battery_params;
DB error: Invalid message

taos> drop database battery_params;
DB error: Database in creating status

**Comment by NephilimJaeger** [comment]
Im having the same problem

**Comment by sangshuduo** [comment]
If the taos cli client version is different with the taosd server version, sometime it may return such an error.

**Comment by Dut201892487** [comment]
+1，虽然重启taosd可以终止这个错误，一直没找到解决方法

**Comment by Dut201892487** [comment]
发现问题所在了，打开taosd的日志可以看到原因。我的是集群中有一个从节点的防火墙打开了，6030端口无法通信，导致创建的数据库没有在从数据库备份，一直是创建状态。

**Comment by reversemingyuc** [comment]
怎么解决的呢
