### ISSUE TITLE
taos-jdbcdriver memory revocation issue

### ISSUE THREAD

**Issue by bs7729** [taosdata/TDengine#21769]
**Performance Issue** 
taos-jdbcdriver 3.2.2 版本获取数据会导致内存一直回收不了,一晚上能到一两千次FGC, 还原到3.1.0后就没这问题了

**To Reproduce**
1. Database parameters used: 
 
taos> SELECT * FROM INFORMATION_SCHEMA.INS_DATABASES WHERE NAME='db_iot_bnclw' \G;
*************************** 1.row ***************************
                name: db_iot_bnclw
         create_time: 2023-06-15 12:44:33.209
             vgroups: 24
             ntables: 543024
             replica: 1
              strict: on
            duration: 14400m
                keep: 129600m,129600m,129600m
              buffer: 376
            pagesize: 4
               pages: 512
             minrows: 100
             maxrows: 4096
                comp: 2
           precision: ms
              status: ready
          retentions: NULL
       single_stable: false
          cachemodel: none
           cachesize: 1
           wal_level: 1
    wal_fsync_period: 3000
wal_retention_period: 0
  wal_retention_size: 0
     wal_roll_period: 0
    wal_segment_size: 0
         stt_trigger: 1
        table_prefix: 0
        table_suffix: 0
       tsdb_pagesize: 4

2. Verbs used:Select
大多sql是这样his_gps_warn 是超级表
SELECT count(1) counts,1 type from his_gps_warn WHERE ( ts > ? and dno in ( ? , ? , ? , ? , ? , ? , ? , ? , ? ) and type is not null and type <> ? ) and ( is_read = ? or is_read is null ) 
==> Parameters: 2023-06-14 00:00:00(String), 864200052656338(String), 862106025093106(String), 863844052485502(String), 864895036001905(String), 863844052370209(String), 862106025066103(String), 863844052596324(String), 868166051820991(String), 868683026467799(String), (String), 0(Integer)
或 dno_864200052656338 是子表
SELECT count(1) counts,1 type from dno_864200052656338 WHERE  ts > ?  and type is not null and type <> ? ) and ( is_read = ? or is_read is null ) 
==> Parameters: 2023-06-14 00:00:00(String), (String), 0(Integer)

* OS: [e.g. CentOS 7.0]
* TDengine Version 3.0.5.0

3.1.0 版本运行151867秒没问题
![39aad6d4d86858f580ffdd790addad1](https://github.com/taosdata/TDengine/assets/64937539/c25cad14-2933-4ca3-a8b4-f2086eac9b25)

3.2.2版本运行1000多少后就出问题了,  s1 一直是100%时间长后就一直在 FGC了
![image](https://github.com/taosdata/TDengine/assets/64937539/c40075c0-b3f3-4fb7-9639-d579b8bb26aa)

**Comment by huolibo** [comment]
创建连接的 URL 以及参数是什么？使用查询 SQL 的 resultSet 有没有 close 呢？

**Comment by bs7729** [comment]
> 创建链接的URL以及参数是什么？使用查询SQL的resultSet有没有关闭呢？

CREATE DATABASE db_iot_bnclw KEEP 90 BUFFER 96 vgroups 24 COMP 2;

查询都有关闭的, 代码没变,只要换驱动包就正常了

**Comment by huolibo** [comment]
在 3.2.2 版本下可以看下机器内存使用情况，有没有存在内存一直上涨的情况。
另外一个可以通过 jheap 等内存分析工具查看下哪些对象没有释放。

**Comment by huolibo** [comment]
java 创建连接的 URL 是什么？

**Comment by bs7729** [comment]
> java 创建连接的 URL 是什么？

![image](https://github.com/taosdata/TDengine/assets/64937539/eac3aa80-540b-4b6d-993b-c465569957ea)

**Comment by huolibo** [comment]
ORM  使用 mybatis？

**Comment by bs7729** [comment]
> 在3.2.2版本下面可以看下面的机器内存使用情况，有没有存在在内存一直上涌的情况。 另外一个可以通过jheap等内存分析工具查看下哪个一些对象没有释放。

![image](https://github.com/taosdata/TDengine/assets/64937539/9f2e77d1-b4c3-400d-93a1-4a7621c02c0a)

**Comment by bs7729** [comment]
> ORM 使用mybatis？

mybatis

**Comment by huolibo** [comment]
需要使用 mat 分析工具来查看内存对象之间的关系。concurrenthashMap 对象较多，是业务程序大量使用吗？通过 jstat 或是 jconsole 监控下有没有内存一直上涨的情况。

**Comment by bs7729** [comment]
> 需要使用 mat 分析工具来查看内存对象之间的关系。concurrenthashMap 对象较多，是业务程序大量使用吗？通过 jstat 或是 jconsole 监控下有没有内存一直上涨的情况。

**Comment by huolibo** [comment]
如果是仅查询就会出现类似情况，那直接使用
```
public static void main(String[] args) throws SQLException {
        Connection connection = DriverManager.getConnection("jdbc:TAOS://localhost:6030/log", "root", "taosdata");
        for (int i = 0; i < 10_000; i++) {
            try(Statement statement =connection.createStatement();
                ResultSet rs = statement.executeQuery("select * from log")){
                Timestamp ts = rs.getTimestamp(1);
            }
        }
    }
```
类似的程序也能模拟出来吧。

**Comment by bs7729** [comment]
> 如果是仅查询就会出现类似情况，那直接使用
> 
> ```
> public static void main(String[] args) throws SQLException {
>         Connection connection = DriverManager.getConnection("jdbc:TAOS://localhost:6030/log", "root", "taosdata");
>         for (int i = 0; i < 10_000; i++) {
>             try(Statement statement =connection.createStatement();
>                 ResultSet rs = statement.executeQuery("select * from log")){
>                 Timestamp ts = rs.getTimestamp(1);
>             }
>         }
>     }
> ```
> 
> 类似的程序也能模拟出来吧。

目前不知道,等内存出现一直回收问题时,要不你们看一下?现在还在运行着

**Comment by huolibo** [comment]
好，下午3点半怎么样？腾讯会议
会议时间：2023/06/19 15:30-16:15 (GMT+08:00) 中国标准时间 - 北京
https://meeting.tencent.com/dm/1n9icMzzSK4h

**Comment by bs7729** [comment]
> 好，下午3点半怎么样？腾讯会议 会议时间：2023/06/19 15:30-16:15 (GMT+08:00) 中国标准时间 - 北京 https://meeting.tencent.com/dm/1n9icMzzSK4h

好,看到时候3点出问题没先,现在我两个节点一个是3.1.0,一个是3.2.2在运行着
