### ISSUE TITLE
根据文档执行流式计算 结果缺失数据

### ISSUE THREAD

**Issue by zjfsdnu** [taosdata/TDengine#21779]
**Bug Description**
根据文档示例一执行流式计算 结果缺失数据

**To Reproduce**
1. Go to 'https://docs.taosdata.com/develop/stream/#%E7%A4%BA%E4%BE%8B%E4%B8%80'
2. Type in 'select wstart, wend, max_current from current_stream_output_stb;'
3. 结果只有1条数据

**Expected Behavior**
应该有2条数据

**Screenshots**
```
taos> select wstart, wend, max_current from current_stream_output_stb;
         wstart          |          wend           |     max_current      |
===========================================================================
 2018-10-03 14:38:15.000 | 2018-10-03 14:38:20.000 |             12.60000 |
Query OK, 1 row(s) in set (0.004374s)
```

**Environment (please complete the following information):**
 - OS: [win11+wsl +ubuntu 22.04+docker24.0.2]
 - Memory: 32G CPU: AMD Ryzen 7 7735HS, current Disk Space: 2T
 - TDengine Version [3.0.5.0]

**Comment by dyisdog** [comment]
看来不只是我们遇到了，我们拿3000W数据做聚合，几次下来，次次结果都不一样，文档没看到有这方面描述

create stream api_window_10s_stream_history fill_history 1 WATERMARK 30s trigger AT_ONCE into topology.api_window_10s_history TAGS(service binary(64),uri binary(256),source_app binary(256)) as
select 
_wstart as sts,
count(sts) as request_count,
sum(status) as success_count , 
max(use_time) as max_use,
min(use_time) as min_use  ,
avg(use_time) as avg_use
from topology.api where sts>='2023-06-20 00:00:00.000' and sts<='2023-06-20 23:59:59.999'
partition by service,uri,source_app
interval (10s)；

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，流计算也做过多次重构优化。因此建议直接安装最新版软件3.3.0.3即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
