### ISSUE TITLE
 TDengine ERROR (80ff0002): No such file or directory

### ISSUE THREAD

**Issue by maxin199056** [taosdata/TDengine#21777]
向表中可以插入数据 查询报错 另外 创建表一直卡顿不能创建成功  可以删除表

**Comment by sangshuduo** [comment]
什么版本？什么环境？硬件配置？CPU内存使用情况？

**Comment by maxin199056** [comment]
> 什么版本？什么环境？硬件配置？CPU内存使用情况？

3.0.22  
centos8  虚拟机
6核CPUIntel(R) Xeon(R) Platinum 8153 CPU @ 2.00GHz  33G内存  1T存储  
%Cpu(s):  1.7 us,  0.6 sy,  0.0 ni, 96.3 id,  1.1 wa,  0.2 hi,  0.1 si,  0.0 st
MiB Mem :  34514.6 total,   9544.7 free,  21478.5 used,   3491.4 buff/cache
MiB Swap:  61440.0 total,  57434.4 free,   4005.6 used.  12694.4 avail Mem

**Comment by maxin199056** [comment]
> 什么版本？什么环境？硬件配置？CPU内存使用情况？

3.0.2.2  
centos8  虚拟机
6核CPUIntel(R) Xeon(R) Platinum 8153 CPU @ 2.00GHz  33G内存  1T存储  
%Cpu(s):  1.7 us,  0.6 sy,  0.0 ni, 96.3 id,  1.1 wa,  0.2 hi,  0.1 si,  0.0 st
MiB Mem :  34514.6 total,   9544.7 free,  21478.5 used,   3491.4 buff/cache
MiB Swap:  61440.0 total,  57434.4 free,   4005.6 used.  12694.4 avail Mem

**Comment by sangshuduo** [comment]
先升到 3.0.5.1 看看

**Comment by sangshuduo** [comment]
> No enough disk space

检查一下磁盘空间？

**Comment by maxin199056** [comment]
磁盘空间没问题 用了dbeaver 重启解决了··

**Comment by sangshuduo** [comment]
> 磁盘空间没问题 用了dbeaver 重启解决了··

DBeaver 重启什么呢？之前有大量返回值的查询操作吗？

**Comment by maxin199056** [comment]
> > 磁盘空间没问题 用了dbeaver 重启解决了··
> 
> DBeaver 重启什么呢？之前有大量返回值的查询操作吗？

用dbeaver连着操作报的错 把dbeaver重启了 没有操作 就是建了表插入了几条数据 就放着了
