### ISSUE TITLE
.net core client

### ISSUE THREAD

**Issue by htrlq** [taosdata/TDengine#218]
Read Document so not find about .net core client，not support or remove support? 
now new lot add many .net core users,  Is there an official plan to support the. net core client?

**Comment by GameBelial** [comment]
+1

**Comment by guanshengliang** [comment]
Can you give some information about the .net core
similar to the driver like JDBC
we are not very familiar with it?

**Comment by CooperLiu** [comment]
@guanshengliang  
for all I know, [odbc](https://en.wikipedia.org/wiki/ODBC) stands for Open Database Connectivity which was created by Microsoft. it will be similar to JDBC, there is a bridge called `JDBC-ODBC` between JDBC and ODBC. just for your information.

**Comment by guanshengliang** [comment]
thanks, we will think about it

**Comment by zhangleixp** [comment]
+1

**Comment by guanshengliang** [comment]
关于C#的问题，请到 #51 继续提问
TDengine团队在研发计划中增加dapper框架的支持
