### ISSUE TITLE
TDengine fill data missed issue

### ISSUE THREAD

**Issue by donnasky** [taosdata/TDengine#21801]
1.数据库版本：3.0.50
2.建表语句：
``` 
CREATE STABLE `collect_data`
( `collect_time` timestamp,`cid` bigint,`field_type` tinyint,`task_id` bigint ,`value`  VARCHAR(256),`status` BOOL,`reason` VARCHAR(256))
TAGS(`device_id` bigint ,`point_id` bigint);
 ```
3.背景：目前我是按照设备id和点位id作为tag分的子表，按照规划是一个点一秒插入一条数据。
             现在我想统计出来一段时间内遗漏的数据（就是哪些秒缺失了数据）
            我的思路：用FILL方法，将数据补NULL 并进行统计
4.问题：FILL方法可以正确的补充遗漏的数据
![374592e8473c712324088be110b5d89](https://github.com/taosdata/TDengine/assets/19203869/ff8dad1b-5663-413c-a0ee-90a686770710)
             但是进行统计时用 time is null 并不能筛选出来遗漏的数据
![db53b5b63899f9afc3ae187335871af](https://github.com/taosdata/TDengine/assets/19203869/38e12383-d1e1-4ed5-97c4-796d1a4e7306)
           请问下这个是什么问题？怎么解决比较好。我如果想把缺失的数据全部都补到另外一张表里有什么好的办法吗？谢谢

**Comment by yu285** [comment]
试试interp函数？
