### ISSUE TITLE
Get error data using nodejs connector 

### ISSUE THREAD

**Issue by sytpb** [taosdata/TDengine#2182]
Linux Centos 

installed nodejs connector 

demo code as 

![image](https://user-images.githubusercontent.com/12178686/84003506-bb43da80-a99c-11ea-979d-33ad9554a975.png)

![image](https://user-images.githubusercontent.com/12178686/84003019-f7c30680-a99b-11ea-9084-fb8199b38cf7.png)

the results can't be understand. 

but using command in Shell as ,,, 

![image](https://user-images.githubusercontent.com/12178686/84003130-24771e00-a99c-11ea-95f4-f196a0359858.png)

**Comment by sytpb** [comment]
@StoneT2000

**Comment by StoneT2000** [comment]
What is the table schema? How did you create it?

The nodejs console output is indicating some of your fields are 0 bytes wide

**Comment by sytpb** [comment]
thanks for your reply . @StoneT2000 
**the simple description of this problem** 

table structure  : 
![image](https://user-images.githubusercontent.com/12178686/84097491-5a1d1500-aa37-11ea-9afc-308ca2c53383.png)



the data in this table with SQL query ; 
select last(stamp, permanent_code) from salary.baseinfo;

**The output ...**

![image](https://user-images.githubusercontent.com/12178686/84097764-0828bf00-aa38-11ea-88e3-378eea8c149d.png)


**Until now  every thing is correct . no problem .** 

But query with nodejs connector  some field show me is **undefined** .   , as below,

![image](https://user-images.githubusercontent.com/12178686/84097945-8ab17e80-aa38-11ea-9062-41320c60a75f.png)

![image](https://user-images.githubusercontent.com/12178686/84097995-a3219900-aa38-11ea-8994-0482bf033693.png)


why is undefined ???

**Comment by sytpb** [comment]
super table created by command in console .  and then using 'insert into table '  in  program code .

**Comment by StoneT2000** [comment]
Try recreating the tables and reinserting and let me know what happens.

**Comment by sytpb** [comment]
@StoneT2000  what did you mean?　　i have try many times .    the results were same . 

My steps are :

1 At the beginning i created the super table with command ,    then the initial work done . 

2  run my JS program ,  code like
 `  let sql1 = INSERT INTO db.xxx USING SUPER TABLE TAGS (something)....;`

3 query from the table , 

4 drop the table that have created ,and loop the step from 2 to 3 ..    

the results show me are same .

**Comment by StoneT2000** [comment]
Strange, Are you having this problem with other tables and other programs?

**Comment by sytpb** [comment]
yes you are right , i should check other table ... 

Now， insert to DB  use node-js connector , and query use REST api .  so it runs ok .

**Comment by StoneT2000** [comment]
Sorry, what rest api are you referring to? Nodejs connector doesn’t use a rest api

**Comment by sytpb** [comment]
sorry , i mean that my code connect with my DB using two connector ,   nodejs and  rest api.

**Comment by sytpb** [comment]
another table , same .. 
![image](https://user-images.githubusercontent.com/12178686/84353612-14f11280-abf2-11ea-9819-de38a0390c7b.png)

**Comment by StoneT2000** [comment]
Can you tell me the exact versions of your system, nodejs, taos client etc.

**Comment by sytpb** [comment]
td 1.5     
os: 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
nodejs 10.20

**Comment by Aries-Lee1991** [comment]
Is the issue solved?
@sytpb

**Comment by sytpb** [comment]
@Aries-Lee1991 　no , you met the same problem ?

**Comment by Aries-Lee1991** [comment]
> @Aries-Lee1991 　no , you met the same problem ?

No, just track the progress.

**Comment by StoneT2000** [comment]
Oh just realize you are on tdengine 1.5, try upgrading tdengine to 1.6.5.9 
Get it from here: https://www.taosdata.com/en/all-downloads/

There was a critical update to the td-connector recently

**Comment by Aries-Lee1991** [comment]
> Oh just realize you are on tdengine 1.5, try upgrading tdengine to 1.6.5.9
> Get it from here: https://www.taosdata.com/en/all-downloads/
> 
> There was a critical update to the td-connector recently

 @sytpb Stone is right. The old version like 1.5 is no longer maintained.

**Comment by sytpb** [comment]
ok,    Thanks a lot ,   I will try it on 1.6.5.9 .

**Comment by sytpb** [comment]
what 's the time for 2.0 ?   I will upgrade to 2.0

**Comment by StoneT2000** [comment]
what 2.0? for what

**Comment by sytpb** [comment]
release version 2. 0 .

**Comment by Aries-Lee1991** [comment]
> release version 2. 0 .

2.0 is in the release plan. Please wait patiently.
