### ISSUE TITLE
3.0.5.1 stream 窗口聚合数据不对

### ISSUE THREAD

**Issue by dyisdog** [taosdata/TDengine#21833]
<img width="837" alt="image" src="https://github.com/taosdata/TDengine/assets/46206183/cd32d7bd-8d90-4bc2-88d2-76218de45fab"> 历史数据查询

按下面1小时开一个窗口进行数据聚合
create stream api_window_1h_stream fill_history 1  watermark 30s trigger at_once into topology.api_window_1h TAGS(service binary(64),uri binary(256),source_app binary(256)) as
select 
_wstart as sts,
count(sts) as request_count,
sum(status) as success_count , 
max(use_time) as max_use,
min(use_time) as min_use  ,
avg(use_time) as avg_use
from topology.api where sts>now-7d
partition by service,uri,source_app
interval (1h);
查询结果
<img width="869" alt="image" src="https://github.com/taosdata/TDengine/assets/46206183/89f28d5e-d45c-45b4-b389-5e1ff28341cd">

按天创建 （结果看起来比较正常，但是也不知道对不对）

create stream api_window_1d_stream fill_history 1  watermark 30s trigger at_once into topology_agg.api_window_1d TAGS(service binary(64),uri binary(256),source_app binary(256)) as
select 
_wstart as sts,
count(sts) as request_count,
sum(status) as success_count , 
max(use_time) as max_use,
min(use_time) as min_use  ,
avg(use_time) as avg_use
from topology.api where sts>now-7d
partition by service,uri,source_app
interval (1d);
<img width="844" alt="image" src="https://github.com/taosdata/TDengine/assets/46206183/769788c2-960d-475a-abbe-72b54d633a8f">

**Comment by yu285** [comment]
流计算经过重构，3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
