### ISSUE TITLE
python taos 1.0.1 depends on Click==7.0  和其他开源库的依赖冲突

### ISSUE THREAD

**Issue by JunDon** [taosdata/TDengine#21839]
The conflict is caused by:
    The user requested click
    black 23.3.0 depends on click>=8.0.0
    flask 2.3.2 depends on click>=8.1.3
    taos 1.0.1 depends on Click==7.0

能否调整为 taos 1.0.1 depends on Click>=7.0

**Comment by yu285** [comment]
already resolved

**Comment by heaxo** [comment]
如何解决，我的也报这个错误

**Comment by LsQi647** [comment]
问问咋解决，我也报这个错
