### ISSUE TITLE
[INTERVAL 函数的使用]2.6.X版本与3.X版本差距有些大

### ISSUE THREAD

**Issue by LuckyHangMei** [taosdata/TDengine#21848]
INTERVAL 函数的使用：

在  2.6.x 版本，我使用如下sql；
 select  avg(字段1) as TagValue  from 超级表 where TagName ='code1' and  time >= '2023-06-20 07:40:00' and time < '2023-06-20 09:18:21' INTERVAL(6s) fill(null)  group by TagName
 
得到的查询结果有 tagValue，time  ，tagName  三列结果

但是在3.x版本，上表面的语句不支持，这样的场景：查询一系列仪表，通过指定间隔，返回，然后结果根据tag列分组，这样的场景INTERVAL函数应该支持的

**Comment by yu285** [comment]
使用partition by 和伪列，效果是一样的。
