### ISSUE TITLE
deleted data still is readable 

### ISSUE THREAD

**Issue by dongjialiang** [taosdata/TDengine#21853]
**Bug Description**
删除6点59分前的数据，提示删除成功，影响11条数据。但是还能通过倒序查询查到这些数据。

**To Reproduce**
1. 执行删除命令，删除了11条数据。delete from tag50134_d6s2_i60last where ts >= '2023-06-26 18:00:00' and ts < '2023-06-26 18:59:00' and mea = 98971 and dev = 1946363224 and prj = 541;
2. 执行正序查询命令，只查询到1条数据。select * from tag50134_d6s2_i60last where ts >= '2023-06-26 18:00:00' and ts < '2023-06-26 19:00:00' and mea = 98971 and dev = 1946363224 and prj = 541 order by ts asc limit 80;
3. 执行倒序查询命令，查询到12条数据。select * from tag50134_d6s2_i60last where ts >= '2023-06-26 18:00:00' and ts < '2023-06-26 19:00:00' and mea = 98971 and dev = 1946363224 and prj = 541 order by ts desc limit 80;

**Expected Behavior**
倒序查询能搜索到已被删除的数据。

**Screenshots**
![1687782391071](https://github.com/taosdata/TDengine/assets/35252376/aac271ed-db5e-4d18-8b97-78ff959655b0)

**Environment (please complete the following information):**
 - OS: Ubuntu18.04.5
 - Memory, CPU, current Disk Space
 - TDengine Version 3.0.5.

**Additional Context**

**Comment by yu285** [comment]
请问版本号是 3.0.5.几？

**Comment by dongjialiang** [comment]
> 请问版本号是 3.0.5.几？

版本是3.0.5.0

**Comment by yu285** [comment]
tag50134_d6s2_i60last 这个是超级表还是子表

**Comment by dongjialiang** [comment]
> tag50134_d6s2_i60last 这个是超级表还是子表

是超级表

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
