### ISSUE TITLE
查询响应慢问题

### ISSUE THREAD

**Issue by tangbao0002** [taosdata/TDengine#21869]
**查询速度慢** 

C#开发， var res = TDengine.Query(conn, sql)查询获取结果后， LibTaos.GetData(res)取结果还是要等待很久，时间和Query差不多，大概100个tag查询，LibTaos.GetData又查了一次数据库吗？

**Comment by yu285** [comment]
请提供版本信息，并且使用最新版3.3.0.3 测试。

如果还有问题可添加微信 a15652223354

**Comment by yu285** [comment]
请提供版本信息，并且使用最新版3.3.0.3 测试。

如果还有问题可添加微信 a15652223354
