### ISSUE TITLE
Failed to write core dump. Core dumps have been disabled

### ISSUE THREAD

**Issue by duabo** [taosdata/TDengine#21862]
Use Spring Boot, Mybatis, TDEngine Java Driver connect to TDEngine on the same machine，after running some time(about one or two day), JVM crash and left a crash report file

TDEngine  server version: 2.6.0.28
JAVA JDBC driver version: 2.0.40
JAVA jdk version: 1.8.0_351

Use Case:
write data per second ，the sql like this:
INSERT INTO eblock${info.type}_pack_t_v_${info.type} USING eblock${info.type}_pack_t_v
        TAGS (#{info.type})
        values (#{info.recordTime},#{info.receiveTime},#{info.packUUID}...

and search data per 30 second, the sql like this:
select * from emonitor.eblock${bmuType}_pack_t_v
        <where>
            <if test="lastSyncTime != null">
                record_time > #{lastSyncTime}
            </if>
        </where>
 order by record_time ASC limit #{pageSize}

JVM crash report:
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f29305bc093, pid=645245, tid=0x00007f291b7fe700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_351-b10) (build 1.8.0_351-b10)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.351-b10 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libtaos.so.2.6.0.28+0x1bc093]  rpcGetConnFromCache+0x10d
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

---------------  T H R E A D  ---------------

Current thread is native thread

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000150

Registers:
RAX=0x00000000000000b0, RBX=0x0000000000000000, RCX=0x000000000009d900, RDX=0x00007f27b4000550
RSP=0x00007f291b7fdbb0, RBP=0x00007f291b7fdc20, RSI=0x00007f27b4032a84, RDI=0x00007f29309c9fb0
R8 =0x00007fff8cba3080, R9 =0x00000000113e12d6, R10=0x0000000000000004, R11=0x00007f27b4032978
R12=0x00007f295b006aae, R13=0x00007f295b006aaf, R14=0x00007f295b006b90, R15=0x00007f291b7fdfc0
RIP=0x00007f29305bc093, EFLAGS=0x0000000000010202, CSGSFS=0x002b000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007f291b7fdbb0)
0x00007f291b7fdbb0:   00007f291b7fdfc0 0000178e305b2403
0x00007f291b7fdbc0:   00007f27b4032a84 00007f27b4000540
0x00007f291b7fdbd0:   0000000000003392 00001a6000000000
0x00007f291b7fdbe0:   00000000000000b0 0000000000000000
0x00007f291b7fdbf0:   00007f27b4000540 00000188f6a098ac
0x00007f291b7fdc00:   0000000064993fa4 0000000000003236
0x00007f291b7fdc10:   00007f291b7fdc40 1bf4c8fdc0ce1700
0x00007f291b7fdc20:   00007f291b7fdc60 00007f29305b3c64
0x00007f291b7fdc30:   000000005606a840 00007f27b4032970
0x00007f291b7fdc40:   00007f291b7fdcb0 00007f29305bbf5e
0x00007f291b7fdc50:   00007f27b40004c0 00007f27b4032978
0x00007f291b7fdc60:   00007f291b7fdcb0 00007f29305b61d9
0x00007f291b7fdc70:   00007f27b4032970 00007f2955610ab0
0x00007f291b7fdc80:   0000006f5557d270 00007f27b4032c78
0x00007f291b7fdc90:   00007f27b4032c78 0000000000003234
0x00007f291b7fdca0:   00007f287c00b76c 1bf4c8fdc0ce1700
0x00007f291b7fdcb0:   00007f291b7fdd60 00007f29305b5b54
0x00007f291b7fdcc0:   000000470000005e 00007f27b4032970
0x00007f291b7fdcd0:   00007f287c00b728 00007f2955e33cb0
0x00007f291b7fdce0:   000000037c00b728 00007f2955610ab0
0x00007f291b7fdcf0:   00007f2955610ab0 00007f287c00b76c
0x00007f291b7fdd00:   00007f291b7fdd58 00007f287c00b76c
0x00007f291b7fdd10:   800000040000028c 00007f27b4032970
0x00007f291b7fdd20:   0000000000003399 00007f2955610ab0
0x00007f291b7fdd30:   0000028c00000000 000003867c00b9f8
0x00007f291b7fdd40:   00007f2955e33cb0 00007f287c00b728
0x00007f291b7fdd50:   0000000000000000 1bf4c8fdc0ce1700
0x00007f291b7fdd60:   00007f291b7fdde0 00007f29305b5616
0x00007f291b7fdd70:   0000028c0000028c 00007f291b7fde20
0x00007f291b7fdd80:   000000007c00b420 00007f27b4032970
0x00007f291b7fdd90:   00007f287c00b728 00007f2955610ab0
0x00007f291b7fdda0:   00007f2955e33cb0 1bf4c8fdc0ce1700 

Instructions: (pc=0x00007f29305bc093)
0x00007f29305bc073:   e2 03 48 01 d0 48 8b 00 48 89 45 c0 e9 87 00 00
0x00007f29305bc083:   00 48 8b 45 d0 48 8b 40 20 48 89 c2 48 8b 45 c0
0x00007f29305bc093:   48 8b 80 a0 00 00 00 48 01 d0 48 39 45 d8 72 21
0x00007f29305bc0a3:   48 8b 4d d8 8b 55 bc 48 8b 75 c0 48 8b 45 d0 48 

Register to memory mapping:

RAX=0x00000000000000b0 is an unknown value
RBX=0x0000000000000000 is an unknown value
RCX=0x000000000009d900 is an unknown value
RDX=0x00007f27b4000550 is an unknown value
RSP=0x00007f291b7fdbb0 is an unknown value
RBP=0x00007f291b7fdc20 is an unknown value
RSI=0x00007f27b4032a84 is an unknown value
RDI=0x00007f29309c9fb0: <offset 0x5c9fb0> in /usr/local/taos/driver/libtaos.so.2.6.0.28 at 0x00007f2930400000
R8 =0x00007fff8cba3080 is an unknown value
R9 =0x00000000113e12d6 is an unknown value
R10=0x0000000000000004 is an unknown value
R11=0x00007f27b4032978 is an unknown value
R12=0x00007f295b006aae is pointing into the stack for thread: 0x00007f295400a800
R13=0x00007f295b006aaf is pointing into the stack for thread: 0x00007f295400a800
R14=0x00007f295b006b90 is pointing into the stack for thread: 0x00007f295400a800
R15=0x00007f291b7fdfc0 is an unknown value

Stack: [0x00007f291afff000,0x00007f291b7ff000],  sp=0x00007f291b7fdbb0,  free space=8186k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libtaos.so.2.6.0.28+0x1bc093]  rpcGetConnFromCache+0x10d
C  [libtaos.so.2.6.0.28+0x1b3c64]  rpcSetupConnToServer+0x7b
C  [libtaos.so.2.6.0.28+0x1b61d9]  rpcSendReqToServer+0x70
C  [libtaos.so.2.6.0.28+0x1b5b54]  rpcProcessIncomingMsg+0x3eb
C  [libtaos.so.2.6.0.28+0x1b5616]  rpcProcessMsgFromPeer+0x475
C  [libtaos.so.2.6.0.28+0x1ba702]  taosProcessTcpData+0x3d3

---------------  P R O C E S S  ---------------

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

heap address: 0x00000006cd800000, size: 3880 MB, Compressed Oops mode: Zero based, Oop shift amount: 3
Narrow klass base: 0x0000000000000000, Narrow klass shift: 3
Compressed class space size: 1073741824 Address: 0x00000007c0000000

Heap:
 PSYoungGen      total 229888K, used 15792K [0x000000076f300000, 0x0000000786480000, 0x00000007c0000000)
  eden space 224768K, 4% used [0x000000076f300000,0x000000076fdb5fc8,0x000000077ce80000)
  from space 5120K, 94% used [0x0000000784b80000,0x0000000785036050,0x0000000785080000)
  to   space 13824K, 0% used [0x0000000785700000,0x0000000785700000,0x0000000786480000)
 ParOldGen       total 312832K, used 65115K [0x00000006cd800000, 0x00000006e0980000, 0x000000076f300000)
  object space 312832K, 20% used [0x00000006cd800000,0x00000006d1796c08,0x00000006e0980000)
 Metaspace       used 116243K, capacity 123468K, committed 123800K, reserved 1159168K
  class space    used 13445K, capacity 14668K, committed 14760K, reserved 1048576K

Card table byte_map: [0x00007f29438ab000,0x00007f2944040000] byte_map_base: 0x00007f294023f000

Marking Bits: (ParMarkBitMap*) 0x00007f2959ddd1c0
 Begin Bits: [0x00007f28eb95c000, 0x00007f28ef5fc000)
 End Bits:   [0x00007f28ef5fc000, 0x00007f28f329c000)

Polling page: 0x00007f295b01b000

CodeCache: size=245760Kb used=52972Kb max_used=52985Kb free=192787Kb
 bounds [0x00007f2944400000, 0x00007f2947830000, 0x00007f2953400000]
 total_blobs=15956 nmethods=15181 adapters=683
 compilation: enabled

Compilation events (10 events):
Event: 78016.534 Thread 0x00007f2954253800 20429       4       javax.servlet.ServletResponseWrapper::flushBuffer (10 bytes)
Event: 78016.534 Thread 0x00007f2954253800 nmethod 20429 0x00007f294634b490 code [0x00007f294634b5e0, 0x00007f294634b678]
Event: 78025.534 Thread 0x00007f2954255800 20430       1       java.util.concurrent.atomic.AtomicLong::lazySet (12 bytes)
Event: 78025.534 Thread 0x00007f2954255800 nmethod 20430 0x00007f2944989410 code [0x00007f2944989560, 0x00007f2944989690]
Event: 78040.534 Thread 0x00007f2954251800 20431       4       io.netty.buffer.AbstractByteBuf::writeByte (23 bytes)
Event: 78040.535 Thread 0x00007f2954251800 nmethod 20431 0x00007f29462e2dd0 code [0x00007f29462e2f60, 0x00007f29462e31d0]
Event: 78073.534 Thread 0x00007f295424f000 20432       4       org.springframework.http.converter.AbstractHttpMessageConverter::canWrite (22 bytes)
Event: 78073.537 Thread 0x00007f295424f000 nmethod 20432 0x00007f294665df10 code [0x00007f294665e0c0, 0x00007f294665e538]
Event: 78112.534 Thread 0x00007f2954253800 20433       4       java.util.stream.FindOps$FindSink$OfRef::get (5 bytes)
Event: 78112.535 Thread 0x00007f2954253800 nmethod 20433 0x00007f2944c059d0 code [0x00007f2944c05b20, 0x00007f2944c05c18]

TDEngine log:
                new log file                      
==================================================
06/25 17:19:39.090024 00608415 UTL localEp is: localhost:6030
06/25 17:19:39.090626 00608415 UTL    check global cfg completed
06/25 17:19:39.090628 00608415 UTL ==================================
06/25 17:19:39.090629 00608415 UTL    taos config & system info:
06/25 17:19:39.090629 00608415 UTL ==================================
06/25 17:19:39.090630 00608415 UTL  firstEp:                localhost:6030 
06/25 17:19:39.090630 00608415 UTL  secondEp:               localhost:6030 
06/25 17:19:39.090631 00608415 UTL  fqdn:                   localhost 
06/25 17:19:39.090632 00608415 UTL  serverPort:             6030 
06/25 17:19:39.090632 00608415 UTL  configDir:              /etc/taos 
06/25 17:19:39.090633 00608415 UTL  logDir:                 /var/log/taos 
06/25 17:19:39.090633 00608415 UTL  scriptDir:              /etc/taos 
06/25 17:19:39.090634 00608415 UTL  arbitrator:              
06/25 17:19:39.090634 00608415 UTL  numOfThreadsPerCore:    1.000000 
06/25 17:19:39.090636 00608415 UTL  maxNumOfDistinctRes:    10000000 
06/25 17:19:39.090637 00608415 UTL  rpcTimer:               300(ms)
06/25 17:19:39.090638 00608415 UTL  rpcMaxTime:             600(s)
06/25 17:19:39.090638 00608415 UTL  rpcForceTcp:            0 
06/25 17:19:39.090639 00608415 UTL  shellActivityTimer:     3(s)
06/25 17:19:39.090639 00608415 UTL  compressMsgSize:        524288 
06/25 17:19:39.090640 00608415 UTL  compressColData:        -1 
06/25 17:19:39.090640 00608415 UTL  maxSQLLength:           1048576(byte)
06/25 17:19:39.090641 00608415 UTL  maxWildCardsLength:     100(byte)
06/25 17:19:39.090641 00608415 UTL  maxRegexStringLen:      128(byte)
06/25 17:19:39.090642 00608415 UTL  maxNumOfOrderedRes:     1000000 
06/25 17:19:39.090642 00608415 UTL  keepColumnName:         1 
06/25 17:19:39.090643 00608415 UTL  timezone:               (UTC, +0800) 
06/25 17:19:39.090643 00608415 UTL  locale:                 en_US.UTF-8 
06/25 17:19:39.090644 00608415 UTL  charset:                UTF-8 
06/25 17:19:39.090644 00608415 UTL  numOfLogLines:          10000000 
06/25 17:19:39.090645 00608415 UTL  logKeepDays:            0 
06/25 17:19:39.090645 00608415 UTL  asyncLog:               1 
06/25 17:19:39.090646 00608415 UTL  debugFlag:              0 
06/25 17:19:39.090646 00608415 UTL  rpcDebugFlag:           131 
06/25 17:19:39.090647 00608415 UTL  tmrDebugFlag:           131 
06/25 17:19:39.090647 00608415 UTL  cDebugFlag:             131 
06/25 17:19:39.090648 00608415 UTL  jniDebugFlag:           131 
06/25 17:19:39.090648 00608415 UTL  odbcDebugFlag:          131 
06/25 17:19:39.090649 00608415 UTL  uDebugFlag:             131 
06/25 17:19:39.090649 00608415 UTL  qDebugFlag:             131 
06/25 17:19:39.090649 00608415 UTL  tsdbDebugFlag:          131 
06/25 17:19:39.090650 00608415 UTL  gitinfo:                5f0a7ca587c1b00fcb0e04e9c214a814fc15db42 
06/25 17:19:39.090651 00608415 UTL  gitinfoOfInternal:      NULL 
06/25 17:19:39.090651 00608415 UTL  buildinfo:              Built at 2022-10-28 19:38 
06/25 17:19:39.090652 00608415 UTL  version:                2.6.0.28 
06/25 17:19:39.090652 00608415 UTL  maxBinaryDisplayWidth:  30 
06/25 17:19:39.090653 00608415 UTL  tempDir:                /tmp/ 
06/25 17:19:39.090653 00608415 UTL  aggAlways:              0 
06/25 17:19:39.090653 00608415 UTL  defaultJSONStrType:     nchar 
06/25 17:19:39.090654 00608415 UTL  smlChildTableName:       
06/25 17:19:39.090654 00608415 UTL  smlTagNullName:         _tag_null 
06/25 17:19:39.090655 00608415 UTL  walFlushSize:           1024(Mb)
06/25 17:19:39.090655 00608415 UTL  shortcutFlag:           0 
06/25 17:19:39.090656 00608415 UTL  probeSeconds:           300 
06/25 17:19:39.090656 00608415 UTL  probeKillSeconds:       600 
06/25 17:19:39.090657 00608415 UTL  probeInterval:          40 
06/25 17:19:39.090657 00608415 UTL  writeBatchThreadLocal:  0 
06/25 17:19:39.090658 00608415 UTL  writeBatchSize:         0 
06/25 17:19:39.090658 00608415 UTL  writeBatchTimeout:      10 
06/25 17:19:39.090659 00608415 UTL  os pageSize:            4096(KB)
06/25 17:19:39.090660 00608415 UTL  os openMax:             262144
06/25 17:19:39.090664 00608415 UTL  os streamMax:           16
06/25 17:19:39.090664 00608415 UTL  os numOfCores:          12
06/25 17:19:39.090665 00608415 UTL  os totalMemory:         15516(MB)
06/25 17:19:39.090666 00608415 UTL  os sysname:             Linux
06/25 17:19:39.090667 00608415 UTL  os nodename:            localhost.localdomain
06/25 17:19:39.090667 00608415 UTL  os release:             4.18.0-425.19.2.0.1.an8.x86_64
06/25 17:19:39.090668 00608415 UTL  os version:             #1 SMP Thu Apr 6 14:00:26 CST 2023
06/25 17:19:39.090668 00608415 UTL  os machine:             x86_64
06/25 17:19:39.090669 00608415 UTL  dataDir: /var/lib/taos
06/25 17:19:39.090669 00608415 UTL ==================================
==================================================
                new log file                      
==================================================
06/25 17:53:11.614158 00645247 UTL localEp is: localhost:6030
06/25 17:53:11.614303 00645247 UTL    check global cfg completed
06/25 17:53:11.614304 00645247 UTL ==================================
06/25 17:53:11.614305 00645247 UTL    taos config & system info:
06/25 17:53:11.614306 00645247 UTL ==================================
06/25 17:53:11.614306 00645247 UTL  firstEp:                localhost:6030 
06/25 17:53:11.614307 00645247 UTL  secondEp:               localhost:6030 
06/25 17:53:11.614307 00645247 UTL  fqdn:                   localhost 
06/25 17:53:11.614308 00645247 UTL  serverPort:             6030 
06/25 17:53:11.614309 00645247 UTL  configDir:              /etc/taos 
06/25 17:53:11.614309 00645247 UTL  logDir:                 /var/log/taos 
06/25 17:53:11.614310 00645247 UTL  scriptDir:              /etc/taos 
06/25 17:53:11.614310 00645247 UTL  arbitrator:              
06/25 17:53:11.614311 00645247 UTL  numOfThreadsPerCore:    1.000000 
06/25 17:53:11.614313 00645247 UTL  maxNumOfDistinctRes:    10000000 
06/25 17:53:11.614314 00645247 UTL  rpcTimer:               300(ms)
06/25 17:53:11.614314 00645247 UTL  rpcMaxTime:             600(s)
06/25 17:53:11.614315 00645247 UTL  rpcForceTcp:            0 
06/25 17:53:11.614315 00645247 UTL  shellActivityTimer:     3(s)
06/25 17:53:11.614316 00645247 UTL  compressMsgSize:        524288 
06/25 17:53:11.614316 00645247 UTL  compressColData:        -1 
06/25 17:53:11.614317 00645247 UTL  maxSQLLength:           1048576(byte)
06/25 17:53:11.614317 00645247 UTL  maxWildCardsLength:     100(byte)
06/25 17:53:11.614318 00645247 UTL  maxRegexStringLen:      128(byte)
06/25 17:53:11.614318 00645247 UTL  maxNumOfOrderedRes:     1000000 
06/25 17:53:11.614319 00645247 UTL  keepColumnName:         1 
06/25 17:53:11.614319 00645247 UTL  timezone:               (UTC, +0800) 
06/25 17:53:11.614320 00645247 UTL  locale:                 en_US.UTF-8 
06/25 17:53:11.614320 00645247 UTL  charset:                UTF-8 
06/25 17:53:11.614321 00645247 UTL  numOfLogLines:          10000000 
06/25 17:53:11.614321 00645247 UTL  logKeepDays:            0 
06/25 17:53:11.614322 00645247 UTL  asyncLog:               1 
06/25 17:53:11.614322 00645247 UTL  debugFlag:              0 
06/25 17:53:11.614323 00645247 UTL  rpcDebugFlag:           131 
06/25 17:53:11.614323 00645247 UTL  tmrDebugFlag:           131 
06/25 17:53:11.614324 00645247 UTL  cDebugFlag:             131 
06/25 17:53:11.614324 00645247 UTL  jniDebugFlag:           131 
06/25 17:53:11.614325 00645247 UTL  odbcDebugFlag:          131 
06/25 17:53:11.614325 00645247 UTL  uDebugFlag:             131 
06/25 17:53:11.614326 00645247 UTL  qDebugFlag:             131 
06/25 17:53:11.614326 00645247 UTL  tsdbDebugFlag:          131 
06/25 17:53:11.614327 00645247 UTL  gitinfo:                5f0a7ca587c1b00fcb0e04e9c214a814fc15db42 
06/25 17:53:11.614327 00645247 UTL  gitinfoOfInternal:      NULL 
06/25 17:53:11.614328 00645247 UTL  buildinfo:              Built at 2022-10-28 19:38 
06/25 17:53:11.614328 00645247 UTL  version:                2.6.0.28 
06/25 17:53:11.614329 00645247 UTL  maxBinaryDisplayWidth:  30 
06/25 17:53:11.614329 00645247 UTL  tempDir:                /tmp/ 
06/25 17:53:11.614330 00645247 UTL  aggAlways:              0 
06/25 17:53:11.614330 00645247 UTL  defaultJSONStrType:     nchar 
06/25 17:53:11.614331 00645247 UTL  smlChildTableName:       
06/25 17:53:11.614331 00645247 UTL  smlTagNullName:         _tag_null 
06/25 17:53:11.614332 00645247 UTL  walFlushSize:           1024(Mb)
06/25 17:53:11.614332 00645247 UTL  shortcutFlag:           0 
06/25 17:53:11.614333 00645247 UTL  probeSeconds:           300 
06/25 17:53:11.614333 00645247 UTL  probeKillSeconds:       600 
06/25 17:53:11.614334 00645247 UTL  probeInterval:          40 
06/25 17:53:11.614334 00645247 UTL  writeBatchThreadLocal:  0 
06/25 17:53:11.614335 00645247 UTL  writeBatchSize:         0 
06/25 17:53:11.614335 00645247 UTL  writeBatchTimeout:      10 
06/25 17:53:11.614336 00645247 UTL  os pageSize:            4096(KB)
06/25 17:53:11.614336 00645247 UTL  os openMax:             262144
06/25 17:53:11.614340 00645247 UTL  os streamMax:           16
06/25 17:53:11.614340 00645247 UTL  os numOfCores:          12
06/25 17:53:11.614341 00645247 UTL  os totalMemory:         15516(MB)
06/25 17:53:11.614342 00645247 UTL  os sysname:             Linux
06/25 17:53:11.614343 00645247 UTL  os nodename:            localhost.localdomain
06/25 17:53:11.614343 00645247 UTL  os release:             4.18.0-425.19.2.0.1.an8.x86_64
06/25 17:53:11.614343 00645247 UTL  os version:             #1 SMP Thu Apr 6 14:00:26 CST 2023
06/25 17:53:11.614344 00645247 UTL  os machine:             x86_64
06/25 17:53:11.614345 00645247 UTL  dataDir: /var/lib/taos
06/25 17:53:11.614345 00645247 UTL ==================================
06/26 09:30:15.052298 00645378 RPC WARN TSC 0x24ad, connection error. retry to send request again. numOfTry=1 msgType=1
06/26 15:23:00.003627 00645735 UTL ERROR DEEP write socket failed4. errno=32 fd=64 writeten=111 left=0
06/26 15:23:00.003631 00645735 RPC ERROR DEEP TSC 0x7f2955ddfb30 TCP data sent failed and try again, FD:0x7f27f427e190 fd:64 ctime=1687686810067 ret=-4 le=111 ip=0xe600a8c0 port=6030 threadid=0 numofFds=2
06/26 15:23:00.003634 00645735 UTL ERROR DEEP write socket failed4. errno=32 fd=64 writeten=111 left=0
06/26 15:23:00.003635 00645735 RPC ERROR DEEP TSC 0x7f2955ddfb30 Second TCP data sent failed, FD:0x7f27f427e190 fd:64 ctime=1687686810067 ret=-4 le=111 ip=0xe600a8c0 port=6030 threadid=0 numofFds=2
06/26 15:23:00.003640 00645735 RPC ERROR TSC 0x7f2955ddfb30 0x331e, failed to send, msgLen:111 written:-4, reason:断开的管道
06/26 15:23:00.006407 00645735 UTL ERROR DEEP write socket failed4. errno=32 fd=64 writeten=111 left=0
06/26 15:23:00.006410 00645735 RPC ERROR DEEP TSC 0x7f2955ddfb30 TCP data sent failed and try again, FD:0x7f27f427e190 fd:64 ctime=1687686810067 ret=-4 le=111 ip=0xe600a8c0 port=6030 threadid=0 numofFds=2
06/26 15:23:00.006412 00645735 UTL ERROR DEEP write socket failed4. errno=32 fd=64 writeten=111 left=0
06/26 15:23:00.006413 00645735 RPC ERROR DEEP TSC 0x7f2955ddfb30 Second TCP data sent failed, FD:0x7f27f427e190 fd:64 ctime=1687686810067 ret=-4 le=111 ip=0xe600a8c0 port=6030 threadid=0 numofFds=2
06/26 15:23:00.006414 00645735 RPC ERROR TSC 0x7f2955ddfb30 0x3321, failed to send, msgLen:111 written:-4, reason:断开的管道
==================================================

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/

如果还有具体的使用问题，可以加微信：a15652223354
