### ISSUE TITLE
desc能拿到某张表的数据，但是使用select语句报错Table does not exist

### ISSUE THREAD

**Issue by HikaRiwwww** [taosdata/TDengine#21879]
![9b83ab4ce2337477cb3728f464f85fa](https://github.com/taosdata/TDengine/assets/40284705/577b5b48-d756-4202-8629-168305f9d3b2)

**Comment by sangshuduo** [comment]
版本？

**Comment by HikaRiwwww** [comment]
> 版本？

3.0.5.0

**Comment by sangshuduo** [comment]
请先试试 3.0.5.1 ，如果还有同样问题，请提供 taoslog 和 taosdlog
