### ISSUE TITLE
按照官方文档进行多表查询时报错无法正确解析出列名

### ISSUE THREAD

**Issue by TheIllsionist** [taosdata/TDengine#21875]
**Bug Description**
数据库中有多张表, table1, table2, table3,....., tablen
如果查询 select * from table1 where time >= $x and time <= $y，能正常返回数据；
但是，如果查询select * from table1, table2 where time >= $x and time <= $y 会报错“Column ambiguously defined: time”
这种from子句中跟随多表名的形式在官方文档中是存在的，可见[官网链接](https://docs.taosdata.com/taos-sql/select/)页面中的from_clause语法，因此该情况反馈为bug 

**Environment:**
 - OS: [CentOS ]
 - TDengine Version [ 3.0.5.0 ]

**Additional Context**
希望尽快修复，感觉这应该属于非常简单基础的功能了

**Comment by yu285** [comment]
该特性已经优化，请升级最新版 3.3.0.3
