### ISSUE TITLE
ts范围查询+倒序查询，返回的数据不对

### ISSUE THREAD

**Issue by manmao** [taosdata/TDengine#21873]
使用 表的第一个ts字段 查询一天范围的数据，倒序排，理论上返回 当天23点最后一条数据，实际返回的是一个早上7点的数据
` select ts,ct from device_F0FE6BBFB708 where  ts between '2023-06-27 00:00:00' and '2023-06-27 23:59:59'  order by ts desc  limit 0,10;`
![image](https://github.com/taosdata/TDengine/assets/13160219/cfecf157-8928-4197-9e84-337324f4dbbc)

换成表中普通字段做范围搜索，数据又是正常的
`select ts,ct from device_F0FE6BBFB708 where  ct between '2023-06-27 00:00:00' and '2023-06-27 23:59:59'  order by ts desc  limit 0,10;`

![image](https://github.com/taosdata/TDengine/assets/13160219/dbbcb514-6ae3-4583-bc12-6c83f62db9e6)

版本：3.0.4.1

**Comment by sangshuduo** [comment]
试试 3.0.5.1

**Comment by manmao** [comment]
用了ts 主键 做范围搜索就会偶现这个问题，隔一天数据又正常了

**Comment by manmao** [comment]
> 试试 3.0.5.1


用了ts 主键 做范围搜索就会偶现这个问题，隔一天数据又正常了

**Comment by lichehuo** [comment]
td没个解释吗？这怎么敢用

**Comment by sangshuduo** [comment]
@manmao 先升级到最新的 3.0.6.0 ，如果有同样问题复现请添加 tdengine1 微信我们远程看一下

**Comment by manmao** [comment]
@sangshuduo 好的，我找个时间升级一下版本看看

**Comment by manmao** [comment]
升级到4.0.6.0版本后，这个问题没有再出现了，bug已解决
