### ISSUE TITLE
最新版代码编译错误哦

### ISSUE THREAD

**Issue by skyformat99** [taosdata/TDengine#21880]
最新的代码  2023 06 28  

1） git clone      main分支
2)   ./build.sh

错误如下：
/home/xxx/zz2/TDengine/deps/x86/rocksdb_static/librocksdb.a(c.cc.o)：在函数‘void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) [clone .constprop.0]’中：
c.cc:(.text+0x37a)：对‘std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)’未定义的引用
/usr/bin/ld: /home/xxx/zz2/TDengine/deps/x86/rocksdb_static/librocksdb.a(c.cc.o): unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: 错误的值
collect2: 错误：ld 返回 1
make[2]: *** [build/bin/taosd] 错误 1
make[1]: *** [source/dnode/mgmt/CMakeFiles/taosd.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by sangshuduo** [comment]
gcc 版本？

**Comment by skyformat99** [comment]
> gcc 版本？

gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

**Comment by sangshuduo** [comment]
> > gcc 版本？
> 
> gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

最近有一些新的代码要求 GCC 8 以上

**Comment by skyformat99** [comment]
> 

有编译开关嚒？

**Comment by sangshuduo** [comment]
必须默认使用的功能
