### ISSUE TITLE
Error in C's demo

### ISSUE THREAD

**Issue by duringyl** [taosdata/TDengine#2188]
**Bug Description**
编译运行项目中c语言的例子出错
Compile and run the C’s demo(tests/examples/c/demo.c) error

根据文档，demo.c中第30行taos_errno()的参数应该是taos

2020-06-08

**Comment by Aries-Lee1991** [comment]
我们这边运行没有问题，方便的话，请发日志上来。

**Comment by duringyl** [comment]
这是在使用vs的插件visualGDB，在windows下编写，然后上传到Ubuntu16.04编译和运行的截图，到doQuery()的时候就会提示段错误，访问到不该访问的内存了。


IDE提示是到if (taos_errno(res) != 0) 这一句引发异常，然后我们查了一下官网上的文档，发现taos_errno()传入的参数应该是TAOS*类型，而不是TAOS_RES*类型，改了之后就可以运行了。
文档对taos_errno()的描述：




On 6/9/2020 15:17，Xiaxin Li<notifications@github.com> wrote：

我们这边运行没有问题，方便的话，请发日志上来。

**Comment by Aries-Lee1991** [comment]
> 这是在使用vs的插件visualGDB，在windows下编写，然后上传到Ubuntu16.04编译和运行的截图，到doQuery()的时候就会提示段错误，访问到不该访问的内存了。 IDE提示是到if (taos_errno(res) != 0) 这一句引发异常，然后我们查了一下官网上的文档，发现taos_errno()传入的参数应该是TAOS*类型，而不是TAOS_RES*类型，改了之后就可以运行了。 文档对taos_errno()的描述： On 6/9/2020 15:17，Xiaxin Li<notifications@github.com> wrote： 我们这边运行没有问题，方便的话，请发日志上来。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，感谢，已反馈给相关同学。

**Comment by plum-lihui** [comment]
是的，使用错了。已经提交pr完成修改。
多谢！
