### ISSUE TITLE
data file corrupted

### ISSUE THREAD

**Issue by dansol88** [taosdata/TDengine#21885]
错误描述：
docker部署单个TD，每十秒写入60万条数据，运行一段时间后会出现崩溃，查询到的错误日志如下。
错误日志：
06/26 19:13:35.988994 00000082 TSD ERROR vId:3, read block failed since Data file corrupted
06/26 19:13:35.993053 00000082 TSD ERROR vId:3, tsdbMergeTableData failed at line 1375 since Data file corrupted
06/26 19:13:35.993061 00000082 TSD ERROR vgId:3, tsebCommitFileDataImpl failed at line 1610 since Data file corrupted
06/26 19:13:35.993065 00000082 TSD ERROR vId: 3
tsdbCommitFileData failed at Line 80g since Data file corrupted
06/26 19:13:35.993102 00000082 TSD ERROR vId:3, tsdbCommitData failed at line 957 since Data file corrupted
06/26 19:13:35.993109 00000082 TSD ERROR vId:3, tsdbEndCommit failed at line 1065 since Data file corrupted
06/26 19:13:35.993113 00000082 TSD ERROR vId:3, tsdbCommit failed at line 188 since Data file corrupted
06/26 19:13:35.993131 00000082 ND ERROR vId:3, vodeCommitImpl failed at line 336 since Data file corrupted
问题：
什么情况下会导致这个问题？内存不够或者CPU不够？还是这个频率写入的数据量太大导致的？

**Comment by yu285** [comment]
请问版本号是？

**Comment by dansol88** [comment]
版本号：3.0.2.3

**Comment by yu285** [comment]
已经修复的已知问题，如果不是正式环境建议重新用 3.0.7.1 部署一下，并且使用多副本确保高可用。
