### ISSUE TITLE
为什么默认情况下只能是CPU个数*2个库

### ISSUE THREAD

**Issue by Cricle** [taosdata/TDengine#21882]
一般电脑都是4核心，一个vnode只能创8个库，并且不能通过sql改过，只能是通过改配置文件解决，在边缘计算时候必须要引入运维才能解决这个问题。

有没有方式让一个vnode能创建更多的数据库

**Comment by sangshuduo** [comment]
这么设计的原因是性能最佳。可以用超级表来支持不同的schema，建多个 db 的场景是什么？

**Comment by Cricle** [comment]
类似saas那种方式多工程然后工程对应一个数据库
