### ISSUE TITLE
Unable to drop database due to "conflict transaction not completed"

### ISSUE THREAD

**Issue by sawo1337** [taosdata/TDengine#21889]
After attempting to drop a table, the cluster got stuck (possibly due to lack of free space), after that the database is not reachable and I can't even drop it:

```
taos> drop database db1;

DB error: Conflict transaction not completed (0.000426s)
```

I suspect the issue is because there is no leader vnode:
```
taos> show vnodes 1;
  vgroup_id  | replica |  status   |            db_name             |  dnode_id   |            dnode_ep            |
====================================================================================================================
          75 |       3 | follower  | db1                            |           1 | 10.10.10.167:6030              |
          76 |       3 | follower  | db1                            |           1 | 10.10.10.167:6030              |

taos> show vgroups;
  vgroup_id  |            db_name             |   tables    | v1_dnode | v1_status | v2_dnode | v2_status | v3_dnode | v3_status | v4_dnode | v4_status |  cacheload  | cacheelements | tsma |
==============================================================================================================================================================================================
          75 | db1                            |           0 |        1 | follower  |        2 | candidate |        3 | follower  | NULL     | NULL      |           0 |             0 |    0 |
          76 | db1                           |           0 |        1 | follower  |        2 | candidate |        3 | follower  | NULL     | NULL      |           0 |             0 |    0 |

```
```
taos> show dnodes;
     id      |            endpoint            | vnodes | support_vnodes |   status   |       create_time       |       reboot_time       |              note              |
===========================================================================================================================================================================
           1 | 10.10.10.167:6030              |      4 |             20 | ready      | 2023-04-26 19:18:39.740 | 2023-06-28 10:49:30.585 |                                |
           2 | 10.10.10.169:6030              |      2 |             20 | ready      | 2023-04-26 19:21:33.525 | 2023-06-28 10:54:48.814 |                                |
           3 | 10.10.10.168:6030              |      2 |             20 | ready      | 2023-04-26 19:22:08.132 | 2023-06-28 10:52:09.498 |                                |
Query OK, 3 row(s) in set (0.001442s)

```

```
taos> show mnodes;
     id      |            endpoint            |     role     |  status   |       create_time       |       reboot_time       |
==============================================================================================================================
           1 | 10.10.10.167:6030              | follower     | ready     | 2023-04-26 19:18:39.744 | 2023-06-28 10:54:45.672 |
           2 | 10.10.10.169:6030              | follower     | ready     | 2023-04-26 19:22:48.629 | 2023-06-28 10:54:50.069 |
           3 | 10.10.10.168:6030              | leader       | ready     | 2023-04-26 19:22:40.811 | 2023-06-28 10:54:45.842 |
Query OK, 3 row(s) in set (0.001266s)
```

I suspect the cluster is stuck in restoring state for the database:

```
06/28 12:08:21.538185 00005387 SYN ERROR vgId:75, sync send msg by id error, epset:(nil) dnode:2 addr:6352578276589830146 err:0x800009ff
06/28 12:08:21.900515 00005386 VND ERROR vgId:75, msg:0x7efd9427f4e8 failed to process since restore not finished, type:vnode-drop-stb, gtid:0x:0x219d101b08303def
06/28 12:08:21.900538 00005386 SYN vgId:75, sync get retry epset numOfEps:3 inUse:2
06/28 12:08:21.900926 00005341 VND ERROR vgId:76, msg:0x7efd977ea1e8 failed to process since restore not finished, type:vnode-drop-stb, gtid:0x:0x219d101b08303df0
06/28 12:08:21.900946 00005341 SYN vgId:76, sync get retry epset numOfEps:3 inUse:2

```
Any query against the database which actually reads data fails due to:

```
taos> show tables;

DB error: Sync leader is unreachable (10.005490s)
```

**Expected Behavior**
In my opinion this is a bug in the sense that I can't drop the database in any way and there is normal network communication between dnodes/mnodes and the cluster is functioning normally, there are other databases which are reachable without issues and I can drop them just fine.

**Environment (please complete the following information):**
 - OS: Ubuntu 20
 - TDengine 3.x

**Comment by monkiu-fish** [comment]
There are transaction running.You should find the transaction and kill it;
1.show transactions;
taos> SHOW TRANSACTIONS;
     id      |       create_time       |    stage     |      oper      |               db               |             stable             | failed_times |     last_exec_time      |        last_action_info        |
====================================================================================================================================================================================================================
       42484 | 2023-07-27 17:25:56.866 | undoAction   | create-stream  | ems                            | ems.ems_power_hour             |          836 | 2023-07-28 15:45:39.702 | action:2 
2.kill transactions;
taos> KILL TRANSACTION 42484;
3.drop database;
taos> drop database ems;
Drop OK, 0 row(s) affected (0.007213s)

**Comment by sawo1337** [comment]
>  There are transaction running.You should find the transaction and kill it;
> 1.show transactions;
> taos> SHOW TRANSACTIONS;
> id | create_time | stage | oper | db | stable | failed_times | last_exec_time | last_action_info |
> ```
>    42484 | 2023-07-27 17:25:56.866 | undoAction   | create-stream  | ems                            | ems.ems_power_hour             |          836 | 2023-07-28 15:45:39.702 | action:2 
> ```
> 
> 2.kill transactions; taos> KILL TRANSACTION 42484; 3.drop database; taos> drop database ems; Drop OK, 0 row(s) affected (0.007213s)
Thanks, I will try it if I see this error again, had to rebuild the cluster to get it going unfortunately.
