### ISSUE TITLE
该项目是否有计划支持.net 或.net core的计划了

### ISSUE THREAD

**Issue by winder9090** [taosdata/TDengine#219]
我使用.net或.net core进行项目开发，想问下该项目是否有计划支持.net 或.net core的计划了?

**Comment by guanshengliang** [comment]
不太清楚.net下应该使用哪种驱动，有没有类似JDBC这种标准的接口，我们可以考虑实现这个接口

**Comment by guhuajun** [comment]
微软传统上有ODBC

下面是现有的数据库驱动列表
https://docs.microsoft.com/en-us/ef/core/providers/

**Comment by winder9090** [comment]
> 不太清楚.net下应该使用哪种驱动，有没有类似JDBC这种标准的接口，我们可以考虑实现这个接口
现在用的是Ado.net

**Comment by guanshengliang** [comment]
非常感谢，近期公司内部会讨论何时开展这方面的工作

**Comment by ttgzs** [comment]
希望支持一下.net core

**Comment by guanshengliang** [comment]
windows的客户端提供了dll，并且提供了使用C#调用dll访问TDengine的例子，您可以先通过这种方式使用
更加完善的方法暂时不能排到工作计划中，要十一之后再考虑如何开展，见谅。

**Comment by zhangleixp** [comment]
.net 使用范围很广，市场占有率至少排到前5，强烈要求支持！

**Comment by ArgoZhang** [comment]
> windows的客户端提供了dll，并且提供了使用C#调用dll访问TDengine的例子，您可以先通过这种方式使用
> 更加完善的方法暂时不能排到工作计划中，要十一之后再考虑如何开展，见谅。

例子在哪里啊？

**Comment by guanshengliang** [comment]
@ArgoZhang 
C#的例子，可以参考这篇文档的最后部分
https://www.taosdata.com/blog/2019/07/26/如何编译tdengine的windows客户端/

**Comment by guanshengliang** [comment]
关于C#的问题，请到 #51 继续提问
TDengine团队在研发计划中增加dapper框架的支持
