### ISSUE TITLE
taosdump 数据导出问题

### ISSUE THREAD

**Issue by dachun639** [taosdata/TDengine#21903]
tdengine version: 3.0.3.0 
taosdump version 2.5.0    taosdump 导出来的数据是空的显示0行

导出命令如下：taosdump -D metric  -E "${date}T00:00:00.000+0800" -o ./metric/ 

![image](https://github.com/taosdata/TDengine/assets/62372823/371f7f56-27b0-41be-a17e-3539a4b7ff27)

**Comment by yu285** [comment]
用unix时间戳格式来导 试试
