### ISSUE TITLE
UTL FATAL   Aborted (core dumped)

### ISSUE THREAD

**Issue by z153114659** [taosdata/TDengine#21913]
06/30 12:29:04.703393 00000034 TAOS_ADAPTER info "| 200 |    4.730712ms |   10.20.250.105 | POST | /rest/sql/cssciotdata " model=web sessionID=54232
06/30 12:29:06.111791 00000089 MND stb:1.cssciotdata.plc1_meters, start to retrieve meta
06/30 12:29:06.813182 00000158 VND vgId:5, commit at version 474985
06/30 12:29:06.833763 00000158 VND vgId:5, vnode info is saved, fname:/var/lib/taos/vnode/vnode5/vnode_tmp.json replica:1 selfIndex:0
06/30 12:29:06.833806 00000158 UTL FATAL assert info not provided
06/30 12:29:06.833844 00000158 UTL FATAL tAssert at file /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/tsdb/tsdbCommit.c:156 exit:1
06/30 12:29:06.842912 00000158 UTL FATAL obtained 12 stack frames
06/30 12:29:06.842947 00000158 UTL FATAL frame:0, taosd(taosAssertDebug+0x1c6) [0x892cb1]
06/30 12:29:06.842957 00000158 UTL FATAL frame:1, taosd(tsdbPrepareCommit+0x4c) [0x52c783]
06/30 12:29:06.842966 00000158 UTL FATAL frame:2, taosd() [0x4f85d3]
06/30 12:29:06.842974 00000158 UTL FATAL frame:3, taosd(vnodeAsyncCommit+0x4a) [0x4f879b]
06/30 12:29:06.842982 00000158 UTL FATAL frame:4, taosd(vnodeProcessWriteMsg+0xae2) [0x4fe0fd]
06/30 12:29:06.842990 00000158 UTL FATAL frame:5, taosd() [0x502712]
06/30 12:29:06.842997 00000158 UTL FATAL frame:6, taosd() [0x502bf5]
06/30 12:29:06.843005 00000158 UTL FATAL frame:7, taosd(vnodeProposeCommitOnNeed+0xb7) [0x502d07]
06/30 12:29:06.843016 00000158 UTL FATAL frame:8, taosd(vnodeProposeWriteMsg+0x33d) [0x503116]
06/30 12:29:06.843028 00000158 UTL FATAL frame:9, taosd() [0x8a5237]
06/30 12:29:06.843040 00000158 UTL FATAL frame:10, /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f326588e6db]
06/30 12:29:06.843052 00000158 UTL FATAL frame:11, /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f32651ab61f]
taosd: /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/util/src/tlog.c:822: taosAssertDebug: Assertion `0' failed.
06/30 12:29:07.154224 00000158 UTL FATAL crash signal is 6
06/30 12:29:07.154311 00000158 UTL FATAL sender PID:63 cmdline:taosd
06/30 12:29:07.156930 00000158 UTL FATAL obtained 16 stack frames
06/30 12:29:07.156958 00000158 UTL FATAL frame:0, /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7) [0x7f32650c8e87]
06/30 12:29:07.156968 00000158 UTL FATAL frame:1, /lib/x86_64-linux-gnu/libc.so.6(abort+0x141) [0x7f32650ca7f1]
06/30 12:29:07.156976 00000158 UTL FATAL frame:2, /lib/x86_64-linux-gnu/libc.so.6(+0x303fa) [0x7f32650ba3fa]
06/30 12:29:07.156984 00000158 UTL FATAL frame:3, /lib/x86_64-linux-gnu/libc.so.6(+0x30472) [0x7f32650ba472]
06/30 12:29:07.156992 00000158 UTL FATAL frame:4, taosd(taosAssertDebug+0x2df) [0x892dca]
06/30 12:29:07.157000 00000158 UTL FATAL frame:5, taosd(tsdbPrepareCommit+0x4c) [0x52c783]
06/30 12:29:07.157007 00000158 UTL FATAL frame:6, taosd() [0x4f85d3]
06/30 12:29:07.157015 00000158 UTL FATAL frame:7, taosd(vnodeAsyncCommit+0x4a) [0x4f879b]
06/30 12:29:07.157023 00000158 UTL FATAL frame:8, taosd(vnodeProcessWriteMsg+0xae2) [0x4fe0fd]
06/30 12:29:07.157034 00000158 UTL FATAL frame:9, taosd() [0x502712]
06/30 12:29:07.157047 00000158 UTL FATAL frame:10, taosd() [0x502bf5]
06/30 12:29:07.157059 00000158 UTL FATAL frame:11, taosd(vnodeProposeCommitOnNeed+0xb7) [0x502d07]
06/30 12:29:07.157068 00000158 UTL FATAL frame:12, taosd(vnodeProposeWriteMsg+0x33d) [0x503116]
06/30 12:29:07.157077 00000158 UTL FATAL frame:13, taosd() [0x8a5237]
06/30 12:29:07.157086 00000158 UTL FATAL frame:14, /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f326588e6db]
06/30 12:29:07.157094 00000158 UTL FATAL frame:15, /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f32651ab61f]
Aborted (core dumped)

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
