### ISSUE TITLE
3.0.4 导出到文件时间显示有问题

### ISSUE THREAD

**Issue by qiaogli** [taosdata/TDengine#21950]
语句：
select * from real_time_record_85_null_202302240002_25173 >> 25173.csv;
导出文件
[25173.csv](https://github.com/taosdata/TDengine/files/11946513/25173.csv)
时间显示有问题

**Comment by qiaogli** [comment]
拿execl正常 拿wps打开异常

**Comment by yu285** [comment]
我们在3.0.7.0没有发现这个问题，建议做个升级吧。
