### ISSUE TITLE
schemaless c client 每次都要去服务端验证表、列存不存在？

### ISSUE THREAD

**Issue by ccwxl** [taosdata/TDengine#21956]
**Performance Issue** 
c client Schemaless 写入性能问题

**Problem Description** 
写入性能低
 
**Screenshots**
c client Schemaless 写入性能问题

**Environment (please complete the following information):**

* OS: [e.g. CentOS 7.0] macos
* Memory, CPU, current Disk Space 
* TDengine Version [e.g. 1.6.1.7] 3.0.6.0

**Additional Context** 
客户端下对表的元数据是否有缓存？我用golang 的driver 使用Schemaless influx 协议写入。每个线程每秒大概写800-900条数据。性能不至于这么低吧Schemaless下
服务器配置 8 core 16GB。
数据库配置 16 vgroup

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
