### ISSUE TITLE
窗口开始时间超出了设定的时间范围

### ISSUE THREAD

**Issue by murongfeng66** [taosdata/TDengine#21974]
服务端和客户端时区均为Asia/Shanghai，使用程序写入2023-07-01 00:00:00.000 ～ 2023-07-05 23:59:50.000的数据，
在taos中使用如下SQL查询：
```
select _wstart, _wend, count(*)  from data_history where '2023-07-03 00:00:00.000' <= time and time <= '2023-07-03 23:59:59.999' interval(5h);
``` 
发现第一个窗口开始时间超出了设定的时间范围
![image](https://github.com/taosdata/TDengine/assets/29116895/9c55ef14-9a49-4093-b7d2-bca827e53352)

**Comment by yu285** [comment]
https://mp.weixin.qq.com/s/Kc7wzzRiK4XhAsL48rD6dg

可以看下这个

**Comment by murongfeng66** [comment]
服务端和客户端的时区都是相同的，都是东八区

**Comment by twinkleeyes** [comment]
> 服务端和客户端的时区都是相同的，都是东八区

我也遇到了这个问题，后来怎么解决的呢
