### ISSUE TITLE
Invisible character insertion exception

### ISSUE THREAD

**Issue by zeje** [taosdata/TDengine#21993]
**Bug Description**

tdengine:3.0.4.1

<dependency>
      <groupId>com.taosdata.jdbc</groupId>
      <artifactId>taos-jdbcdriver</artifactId>
      <version>3.2.3</version>
</dependency>

restful插入方式

lang中en后面存在不可见字符\u0000，导致插入失败

syntax error near ''en' (invalid data or symbol)]: 
insert into loctube.device_log_katchu_353919025680130 
loctube.event_katchu_weather_353919025680130 using loctube.event_katchu_weather tags('null','353919025680130')
(_ts,`lng`,`createTime`,`lang`,`lat`)values(1688647335543,114.000635,1688647335552,'en',22.6536966)

**Comment by huolibo** [comment]
使用 prepareStatement 写入特殊字符
```java
Connection connection = DriverManager.getConnection("jdbc:TAOS-RS://localhost:6041/test_pstmt_ws?user=root&password=taosdata&batchfetch=true");
// f1 column type is varchar
PreparedStatement preparedStatement = connection.prepareStatement("insert into weather_test (ts, f1) values (?, ?)");
preparedStatement.setTimestamp(1, new Timestamp(System.currentTimeMillis()));
preparedStatement.setString(2, "var\u0000");
preparedStatement.executeUpdate();
preparedStatement.close();
connection.close();
```
