### ISSUE TITLE
vnodes masters分布不均

### ISSUE THREAD

**Issue by jandison** [taosdata/TDengine#21996]
version：3.0.6.0
集群 3 mnode，4 dnode，3副本
第一个dnode vnodes masters 22个
第二个dnode vnodes masters 2个
第三个dnode vnodes masters 2个
第四个dnode vnodes masters 76个

导致第四个dnode cpu使用率较高。有办法均衡下vnodes masters吗？

**Comment by yu285** [comment]
企业版可以在线重选，开源版只能充重启刷新结果。

因为raft 选leader 是随机的，可以参考这篇文章：

https://www.taosdata.com/engineering/18366.html
