### ISSUE TITLE
docker部署安装客户端shell报错！

### ISSUE THREAD

**Issue by zhuming19791109** [taosdata/TDengine#22047]
FROM openjdk:11
在此镜像下，安装lunix的客户端，版本2.4.0.10，
执行RUN sh ./TDengine-client-2.4.0.10/install_client.sh
报错如下：
#12 ERROR: executor failed running [/bin/sh -c sh ./TDengine-client-2.4.0.10/install_client.sh]: runc did not terminate sucessfully
 ------
  > [stage-1 6/7] RUN sh ./TDengine-client-2.4.0.10/install_client.sh:
 1.361 ./TDengine-client-2.4.0.10/install_client.sh: [73](http://gitlab.mango.com/mbp/mbp-mbasic-cloud/-/jobs/74228#L73): Syntax error: "(" unexpected
 ------

报错指出install_client.sh
 73 function kill_client() {
 74   pid=$(ps -ef | grep "${clientName}" | grep -v "grep" | awk '{print $2}')
 75   if [ -n "$pid" ]; then
 76     ${csudo}kill -9 $pid || :
 77   fi
 78 }

请问，如何解决？

**Comment by sangshuduo** [comment]
用 bash 不要用 sh
另外这个版本太老了，建议尽快切换到 3.0 最新版本
