### ISSUE TITLE
发布版本和文档对应问题

### ISSUE THREAD

**Issue by xieshiqi147258** [taosdata/TDengine#22044]
看到TDengine在3.0.6.0已经支持了geometry类型，官网文档目前还没更新，在#21454中看到删除了相关的材料，请问正式支持有计划具体时间吗
# #docs: remove geometry docs (https://github.com/taosdata/TDengine/pull/21454)
* docs: update readme with libgflags
* docs: update readme with geos
* docs: remove geometry docs

**Comment by sangshuduo** [comment]
还需要和 TDengine 其他功能进行集成和全面的测试，如果在使用中遇到什么问题欢迎报给我们

**Comment by xieshiqi147258** [comment]
> 还需要和TDengine其他功能进行集成和全面的测试，如果在使用中遇到什么问题欢迎报告给我们

OK，我们可以先使用看看 谢谢
