### ISSUE TITLE
3.0.7 集成grafana 时查询语法报错

### ISSUE THREAD

**Issue by liuguoshun** [taosdata/TDengine#22052]
参考了文档的语法.
https://docs.taosdata.com/third-party/grafana/
但是在taos 执行时报错.
请问这个sql 应该怎样写?

taos> desc  telegraf.cpu;   
             field              |         type         |   length    |   note   |
 _ts                            | TIMESTAMP            |           8 |          |
 usage_softirq                  | DOUBLE               |           8 |          |
 usage_steal                    | DOUBLE               |           8 |          |
 usage_guest_nice               | DOUBLE               |           8 |          |
 usage_user                     | DOUBLE               |           8 |          |
 usage_system                   | DOUBLE               |           8 |          |
 usage_iowait                   | DOUBLE               |           8 |          |
 usage_guest                    | DOUBLE               |           8 |          |
 usage_idle                     | DOUBLE               |           8 |          |
 usage_nice                     | DOUBLE               |           8 |          |
 usage_irq                      | DOUBLE               |           8 |          |
 cpu                            | NCHAR                |          16 | TAG      |
 host                           | NCHAR                |          32 | TAG      |
Query OK, 13 row(s) in set (0.001417s)

taos> select _ts,usage_idle from telegraf.cpu where _ts >= '2023-07-11T22:28:15.468Z' and _ts < '2023-07-12T10:28:15.468Z'  limit 2;  
           _ts           |        usage_idle         |
 2023-07-12 16:23:50.000 |        99.398797571552080 |
 2023-07-12 16:24:00.000 |        99.899598414491166 |
Query OK, 2 row(s) in set (0.002826s)

taos> select _ts,avg(usage_idle) from telegraf.cpu where _ts >= '2023-07-11T22:28:15.468Z' and _ts < '2023-07-12T10:28:15.468Z'  interval(2s);  

DB error: Invalid usage of expr: _ts (0.000420s)

**Comment by liuguoshun** [comment]
需要改下文档.
sql 要改成这样才可以
select first(_ts), avg(usage_idle),host from telegraf.cpu where _ts >= $from and _ts < $to partition by host interval($interval)

**Comment by sangshuduo** [comment]
> 需要改下文档. sql 要改成这样才可以 select first(\_ts), avg(usage\_idle),host from telegraf.cpu where \_ts >= fromandts\<from and \_ts \< to partition by host interval($interval)

具体哪个文档？能否提个 PR？谢谢

**Comment by liuguoshun** [comment]
https://docs.taosdata.com/third-party/grafana/

**Comment by sunpe** [comment]
TDengine 窗口查询中，SELECT 列表中的表达式只能包含：
- 常量
- _wstart伪列、_wend伪列和_wduration伪列
- 聚集函数（包括选择函数和可以由参数确定输出行数的时序特有函数）
- 包含上面表达式的表达式
- 且至少包含一个聚集函数

可以参考文档： https://docs.taosdata.com/taos-sql/distinguished/#%E7%AA%97%E5%8F%A3%E5%AD%90%E5%8F%A5%E7%9A%84%E8%A7%84%E5%88%99
