### ISSUE TITLE
taos connect failed, reason: Unable to establish connection.（2.6.0.14）

### ISSUE THREAD

**Issue by Lao-Zhong** [taosdata/TDengine#22068]
**Bug Description**
集群中的某个节点更换了IP后，就无法进入taos
![image](https://github.com/taosdata/TDengine/assets/39207755/718c121d-bd00-48a0-b5a0-f7b2d9cefd78)
![image](https://github.com/taosdata/TDengine/assets/39207755/f41a4ed2-8c57-440c-a15d-60c9e4e57673)

但是在集群可以看到该节点是正常的，数据也同步成功了，只是执行相关读取操作就不行了
![image](https://github.com/taosdata/TDengine/assets/39207755/7cbac0b8-a018-4bed-9b70-a50c567e844a)

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g.Ubuntu 18.04]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 2.6.0.14]

**Additional Context**

**Comment by yu285** [comment]
2.x 不支持了，迁移到 3.0 上吧

https://www.taosdata.com/tdengine-engineering/17753.html
