### ISSUE TITLE
关于最新版本3.0.7.0关于GEOMETRY类型的使用中存在的一些问题，需要解答

### ISSUE THREAD

**Issue by doucaomao** [taosdata/TDengine#22075]
一、安装创建部分
安装windows版3.0.7.0版本
//创建一个名为test的测试数据库
create database test 
//然后创建一个表track_info
create table test.track_info(pos_time TIMESTAMP,lon DOUBLE ,lat DOUBLE,point GEOMETRY(40)) tags(target_id BIGINT);

二、使用
使用jdbc进行链接，然后插入测试数据，代码大致如下
![image](https://github.com/taosdata/TDengine/assets/139204865/167ee51d-bd85-4551-bbf1-36260c454202)

三、问题
1.插入一定数量的数据后(大约1000w左右时)，会报错，错误信息为：“TDengine ERROR (80000020):some vnode/qnode/mnode(s) out of service”，如果创建数据库时，增加vgroups的数量（"create database test vgroups 64"），则可以可以坚持多插入一些数据，但是最后还是会发生一样的问题 

2.使用ST_Intersects函数进行范围查询时，增加其他字段的条件就会报错，感觉是一个bug，举例如下：

	可执行：
	SELECT
	count(1)
	FROM
	track_info
	WHERE
	ST_Intersects(ST_GeomFromText('POLYGON((118.22117788127919 23.733297259394583,119.30555943228148 23.733297259394583,119.30555943228148 24.722980767811308,118.22117788127919 24.722980767811308,118.22117788127919 23.733297259394583))'),point)
	
	不可执行
	SELECT
	count(1)
	FROM
	track_info
	WHERE
	pos_time BETWEEN '2021-09-01 00:00:00' AND '2021-09-05 00:00:00'
	and ST_Intersects(ST_GeomFromText('POLYGON((118.22117788127919 23.733297259394583,119.30555943228148 23.733297259394583,119.30555943228148 24.722980767811308,118.22117788127919 24.722980767811308,118.22117788127919 23.733297259394583))'),point)

**Comment by doucaomao** [comment]
配置使用的是默认配置，无修改

**Comment by sangshuduo** [comment]
some vnode/qnode/mnode(s) out of service 通常是环境因素导致，例如服务中 IP 变了。建议使用物理机 Linux 作为服务进行测试开发

**Comment by doucaomao** [comment]
> some vnode/qnode/mnode(s) out of service 通常是环境因素导致，例如服务中 IP 变了。建议使用物理机 Linux 作为服务进行测试开发

好的，我再试试，另外关于第二个问题，的确是存在的，应该是新版本的BUG，请后续更新过程中进行处理

**Comment by doucaomao** [comment]
> some vnode/qnode/mnode(s) out of service 通常是环境因素导致，例如服务中 IP 变了。建议使用物理机 Linux 作为服务进行测试开发

目前在linux服务器上，使用docker安装了最新3.0.7.0版本，插入依旧会出现该问题
![image](https://github.com/taosdata/TDengine/assets/139204865/77071510-6e08-4205-a275-0999dfa29dba)

另外第二点已经确认存在，应该是新版本的bug

**Comment by doucaomao** [comment]
jdbc使用参数替换的方式进行插入，如果一批次中，子表的时间有重复的话，会不会导致这个问题的发生？因为目前我使用的数据是到毫秒的

**Comment by sangshuduo** [comment]
谢谢。geometry 还在内部验证测试阶段。

**Comment by lsh2366254** [comment]
感觉bug多多啊

**Comment by sangshuduo** [comment]
> 感觉bug多多啊

geometry 还没有正式发布

**Comment by doucaomao** [comment]
> 

好像没有专门的类，我们是自己写的工具类，这个也得看你做什么用处了，如果只是POINT(x,x)这种的话，字符串感觉就行
