### ISSUE TITLE
使用时发生内存访问错误

### ISSUE THREAD

**Issue by isCoderHuang** [taosdata/TDengine#22082]
查询数据时发生了内存访问错误 数据量不多几千条

创库语句
CREATE DATABASE `xxxx14` BUFFER 256 CACHESIZE 1 CACHEMODEL 'none' COMP 2 DURATION 14400m WAL_FSYNC_PERIOD 3000 MAXROWS 4096 MINROWS 100 STT_TRIGGER 1 KEEP 5256000m,5256000m,5256000m PAGES 256 PAGESIZE 4 PRECISION 'ms' REPLICA 1 WAL_LEVEL 1 VGROUPS 2 SINGLE_STABLE 0 TABLE_PREFIX 0 TABLE_SUFFIX 0 TSDB_PAGESIZE 4 WAL_RETENTION_PERIOD 0 WAL_RETENTION_SIZE 0 WAL_ROLL_PERIOD 0 WAL_SEGMENT_SIZE 0

创表语句
CREATE STABLE `stb_mq_data` (`ts` TIMESTAMP, `big_type` INT, `sub_type` INT, `zone_code` NCHAR(10), `mqdata` DOUBLE, `model_code` NCHAR(4), `device_num` NCHAR(15),`ktkt_code` NCHAR(10), `device_name` NCHAR(25)) TAGS (`kt` VARCHAR(64))

查询语句
SELECT avg(mqdata) as avg_val FROM stb_mq_data WHERE ktkt='KTKT_0173' AND ts >= '2023-07-14 00:00:00' AND ts <= '2023-07-14 23:59:59' interval(60s) FILL(linear)
出错
以下是出错翻译
根据提供的错误日志，可以得出以下分析：

错误类型：EXCEPTION_ACCESS_VIOLATION (0xc0000005)

这是一个严重的错误类型，表示发生了内存访问违规（Memory Access Violation）。

错误位置：Problematic frame: C [taos.dll+0x593560]

错误发生在 taos.dll 的地址 0x00007ff8c2343560 处。

Java环境信息：
JRE版本：Java(TM) SE Runtime Environment (17.0.7+8) (build 17.0.7+8-LTS-224)
Java虚拟机：Java HotSpot(TM) 64-Bit Server VM (17.0.7+8-LTS-224, mixed mode, emulated-client, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)

崩溃发生在Java虚拟机之外的本地代码中：
The crash happened outside the Java Virtual Machine in native code.

根据以上信息，可以初步分析以下原因：
本地代码问题：错误发生在 taos.dll 中的本地代码，而不是Java虚拟机的代码。这可能是由于 taos.dll 的错误或问题导致的。taos.dll 可能是一个第三方库或自定义的本地库。

内存访问违规：EXCEPTION_ACCESS_VIOLATION 错误通常与内存访问错误相关。可能发生了非法的内存访问，例如访问了无效的内存地址或已释放的内存。

**Comment by isCoderHuang** [comment]
查询上面语句偶尔出错程序崩溃，使用的是
jdk17.0.7
springboot-2.7.13
com.taosdata.jdbc.taos-jdbcdrive:3.2.4
taos版本为3.0.4.1
version: 3.0.4.1 compatible_version: 3.0.0.0
gitinfo: 14dc9eabc403e731ba1097eca0bcaa902c6d5b62
buildInfo: Built at 2023-04-27 11:08

**Comment by isCoderHuang** [comment]
有解决方案麻烦踢我一下@isCoderHuang@gmail.com
感谢

**Comment by isCoderHuang** [comment]
已完美解决

**Comment by ggmyfand** [comment]
你好，请问是如何解决的？
