### ISSUE TITLE
DROP DNODE "fqdn:port" 的方式始终失败

### ISSUE THREAD

**Issue by yangbocheng** [taosdata/TDengine#22083]
tdegine版本为`Welcome to the TDengine Command Line Interface, Client Version:3.0.7.1`
如下 启动3个节点
```
docker run -itd --name td1 --network test -e TAOS_FQDN=td1 -e TAOS_FIRST_EP=td1 -p 6030:6030 -p 6041:6041 tdengine/tdengine
docker run -itd --name td2 --network test -e TAOS_FQDN=td2 -e TAOS_FIRST_EP=td1 -p 6031:6030 -p 6042:6041 tdengine/tdengine
docker run -itd --name td3 --network test -e TAOS_FQDN=td3 -e TAOS_FIRST_EP=td1 -p 6032:6030 -p 6043:6041 tdengine/tdengine
```

然后进入td1 中，使用drop dnode, 请问为什么`drop dnode "td3:6030"`的方式始终失败，但是`drop dnode 3`就正常运行
![image](https://github.com/taosdata/TDengine/assets/32633109/d5bb04aa-9df8-4fa7-bdb0-b37cd07e7eb7)

**Comment by sangshuduo** [comment]
[https://docs.taosdata.com/taos-sql/node/#%E5%88%A0%E9%99%A4%E7%AE%A1%E7%90%86%E8%8A%82%E7%82%B9](https://docs.taosdata.com/taos-sql/node/#%E5%88%A0%E9%99%A4%E7%AE%A1%E7%90%86%E8%8A%82%E7%82%B9) 设计如此

**Comment by yangbocheng** [comment]
谢谢回复。 但是几处文档都有这种说明。 是否文档有误？
![image](https://github.com/taosdata/TDengine/assets/32633109/9967ebba-3f43-44a6-b333-eb60fdf6d1be)
