### ISSUE TITLE
流计算一定时间后不更新

### ISSUE THREAD

**Issue by techzhou** [taosdata/TDengine#22088]
3.0.4.1

使用SQL创建流
create stream `stream_XXX` trigger at_once fill_history 1 into `new_table_XXX` as select `time`, `number`*0.2 as `number`, `data_idx` from table_XXX;

从new_table_XXX中可以取到数据 但是一段时间后 不再更新 table_XXX内数据正常 删除重建流和new_table_XXX后又可以了

是创建语句有问题？

**Comment by sangshuduo** [comment]
什么版本？

**Comment by techzhou** [comment]
> 什么版本？

3.0.4.1

**Comment by sangshuduo** [comment]
先升到最新版本吧，流计算改进比较大

**Comment by techzhou** [comment]
> 先升到最新版本吧，流计算改进比较大

OK

**Comment by feiyangbeyond** [comment]
解决了么
