### ISSUE TITLE
taosdump

### ISSUE THREAD

**Issue by isCoderHuang** [taosdata/TDengine#22093]
![image](https://github.com/taosdata/TDengine/assets/115392891/5288f580-2f3f-45be-b718-75f7df299127)

taosdump命令提示未找到这个Debug版本的VC++库140d.dll
windows10系统
taos版本3.0.4.1

**Comment by sangshuduo** [comment]
[https://aka.ms/vs/16/release/vc_redist.x64.exe](https://aka.ms/vs/16/release/vc_redist.x64.exe)

https://answers.microsoft.com/en-us/windows/forum/all/vcruntime140dll-was-not-found/f43d5afd-9239-4913-8f32-20e44a959e13
