### ISSUE TITLE
连接方式从restful改为原生，sql报错

### ISSUE THREAD

**Issue by zhuming19791109** [taosdata/TDengine#22105]
**Bug Description**
相同的代码，只是切换从restful连接改为原生连接，有些sql就会报错

**To Reproduce**
1. 原先连接信息
    driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
    url: jdbc:TAOS-RS://192.168.1.242:6041/mbasic?timezone=UTC-8&charset=UTF-8&locale=zh_CN.UTF-8&user=admin&password=mango252
2. 修改后连接信息
    driver-class-name: com.taosdata.jdbc.TSDBDriver
    url: jdbc:TAOS://192.168.1.242:6030/mbasic?timezone=UTC-8&charset=UTF-8&locale=zh_CN.UTF-8&user=admin&password=mango252
3. 报错信息
![image](https://github.com/taosdata/TDengine/assets/23214094/ca1878cd-24f3-469d-9dcc-676159bdea60)

**Comment by sangshuduo** [comment]
建议先升级 java 连接器到 2.0.42 试试。如果方便的话 TDengine 建议升级到 3.0 最新版本，社区版 2.x 不再继续更新了
