### ISSUE TITLE
集群启动时报错

### ISSUE THREAD

**Issue by StevenSwinyoung** [taosdata/TDengine#22113]
**Bug Description**

**To Reproduce**
启动TDengine

**Expected Behavior**
报如下错误：
07/18 19:27:21.673973 00054249 DND start to init dnode env
07/18 19:27:21.674023 00054249 DND dnode will run in single-process mode
07/18 19:27:21.674903 00054249 DND dnode env is initialized
07/18 19:27:21.674911 00054249 DND start to init service
07/18 19:27:21.674923 00054249 DND node:dnode, start to open
07/18 19:27:21.674931 00054249 UTL worker:dnode-mgmt is initialized, min:1 max:1
07/18 19:27:21.675062 00054259 UDF start to init udfd
07/18 19:27:21.675749 00054259 UDF ERROR can not spawn udfd. path: taosd/udfd, error: no such file or directory
07/18 19:27:21.675885 00054249 UDF udfd is cleaned up after spawn err
07/18 19:27:21.675897 00054249 DND ERROR failed to start udfd
07/18 19:27:21.675904 00054249 DND node:dnode, has been opened
07/18 19:27:21.675917 00054249 DND node:mnode, start to open
07/18 19:27:21.675979 00054249 WAL wal module is initialized, rsetId:3
07/18 19:27:21.676138 00054249 DND mnode start to open
07/18 19:27:21.677214 00054249 MND start to open mnode sync, standby:0
07/18 19:27:21.677342 00054249 SYN vgId:1, sync node use snapshot
07/18 19:27:21.677373 00054249 UTL worker:mnode-query is initialized, min:4 max:4
07/18 19:27:21.677486 00054249 UTL worker:mnode-fetch is initialized, min:1 max:1
07/18 19:27:21.677534 00054249 UTL worker:mnode-read is initialized, min:1 max:1
07/18 19:27:21.677570 00054249 UTL worker:mnode-write is initialized, min:1 max:1
07/18 19:27:21.677602 00054249 UTL worker:mnode-sync is initialized, min:1 max:1
07/18 19:27:21.677634 00054249 UTL worker:mnode-monitor is initialized, min:1 max:1
07/18 19:27:21.677669 00054249 DND node:mnode, has been opened
07/18 19:27:21.677682 00054249 DND node:vnode, start to open
07/18 19:27:21.677793 00054249 UTL worker:vnode-query is initialized, min:8 max:8
07/18 19:27:21.677798 00054249 UTL worker:vnode-stream is initialized, min:4 max:4
07/18 19:27:21.677807 00054249 UTL worker:vnode-mgmt is initialized, min:1 max:1
07/18 19:27:21.677840 00054249 UTL worker:vnode-monitor is initialized, min:1 max:1
07/18 19:27:21.678005 00054249 DND open 11 vnodes with 2 threads
07/18 19:27:21.682015 00054279 SYN vgId:20, sync node use snapshot
07/18 19:27:21.682327 00054278 SYN vgId:18, sync node use snapshot
07/18 19:27:21.686617 00054279 SYN vgId:22, sync node use snapshot
07/18 19:27:21.686688 00054278 SYN vgId:53, sync node use snapshot
07/18 19:27:21.690151 00054278 TSD ERROR vgId:55, tsdb scan and try fix fs failed since Data file corrupted
07/18 19:27:21.690228 00054278 TSD ERROR vgId:55, tsdb fs open failed since Data file corrupted
07/18 19:27:21.690275 00054278 VND ERROR vgId:55, failed to open vnode tsdb since No such file or directory
07/18 19:27:21.690381 00054278 DND ERROR vgId:55, failed to open vnode by thread:0
07/18 19:27:21.690795 00054279 SYN vgId:57, sync node use snapshot
07/18 19:27:21.693281 00054278 SYN vgId:27, sync node use snapshot
07/18 19:27:21.694521 00054279 SYN vgId:13, sync node use snapshot
07/18 19:27:21.697196 00054278 SYN vgId:29, sync node use snapshot
07/18 19:27:21.698288 00054279 SYN vgId:62, sync node use snapshot
07/18 19:27:21.700920 00054278 SYN vgId:31, sync node use snapshot
07/18 19:27:21.701085 00054249 DND ERROR there are total vnodes:11, opened:10
07/18 19:27:21.701108 00054249 DND ERROR failed to open vnode since success
07/18 19:27:21.701117 00054249 DND ERROR failed to init vnodes-mgmt since success
07/18 19:27:21.701126 00054249 DND start to close all vnodes
07/18 19:27:21.701143 00054249 VND vgId:18, start to commit, commit ID:62 version:102681
07/18 19:27:21.707229 00054249 VND vgId:18, vnode info is saved, fname:/data/taos/data/vnode/vnode18/vnode_tmp.json
07/18 19:27:21.707421 00054249 VND vgId:18, vnode info is committed
07/18 19:27:21.707548 00054249 VND vgId:18, commit end
07/18 19:27:21.709911 00054249 VND vgId:20, start to commit, commit ID:62 version:101018
07/18 19:27:21.713349 00054249 VND vgId:20, vnode info is saved, fname:/data/taos/data/vnode/vnode20/vnode_tmp.json
07/18 19:27:21.713505 00054249 VND vgId:20, vnode info is committed
07/18 19:27:21.713614 00054249 VND vgId:20, commit end
07/18 19:27:21.715973 00054249 VND vgId:53, start to commit, commit ID:77 version:609448
07/18 19:27:21.719125 00054249 VND vgId:53, vnode info is saved, fname:/data/taos/data/vnode/vnode53/vnode_tmp.json
07/18 19:27:21.719273 00054249 VND vgId:53, vnode info is committed
07/18 19:27:21.719378 00054249 VND vgId:53, commit end
07/18 19:27:21.721765 00054249 VND vgId:22, start to commit, commit ID:62 version:107172
07/18 19:27:21.724873 00054249 VND vgId:22, vnode info is saved, fname:/data/taos/data/vnode/vnode22/vnode_tmp.json
07/18 19:27:21.725032 00054249 VND vgId:22, vnode info is committed
07/18 19:27:21.725136 00054249 VND vgId:22, commit end
07/18 19:27:21.727567 00054249 VND vgId:57, start to commit, commit ID:76 version:432740
07/18 19:27:21.731767 00054249 VND vgId:57, vnode info is saved, fname:/data/taos/data/vnode/vnode57/vnode_tmp.json
07/18 19:27:21.731912 00054249 VND vgId:57, vnode info is committed
07/18 19:27:21.732047 00054249 VND vgId:57, commit end
07/18 19:27:21.734432 00054249 VND vgId:27, start to commit, commit ID:62 version:104743
07/18 19:27:21.737959 00054249 VND vgId:27, vnode info is saved, fname:/data/taos/data/vnode/vnode27/vnode_tmp.json
07/18 19:27:21.738113 00054249 VND vgId:27, vnode info is committed
07/18 19:27:21.738220 00054249 VND vgId:27, commit end
07/18 19:27:21.740570 00054249 VND vgId:29, start to commit, commit ID:62 version:99910
07/18 19:27:21.744457 00054249 VND vgId:29, vnode info is saved, fname:/data/taos/data/vnode/vnode29/vnode_tmp.json
07/18 19:27:21.744630 00054249 VND vgId:29, vnode info is committed
07/18 19:27:21.744735 00054249 VND vgId:29, commit end
07/18 19:27:21.747099 00054249 VND vgId:13, start to commit, commit ID:62 version:103531
07/18 19:27:21.750561 00054249 VND vgId:13, vnode info is saved, fname:/data/taos/data/vnode/vnode13/vnode_tmp.json
07/18 19:27:21.750706 00054249 VND vgId:13, vnode info is committed
07/18 19:27:21.750807 00054249 VND vgId:13, commit end
07/18 19:27:21.753175 00054249 VND vgId:62, start to commit, commit ID:79 version:807385
07/18 19:27:21.756691 00054249 VND vgId:62, vnode info is saved, fname:/data/taos/data/vnode/vnode62/vnode_tmp.json
07/18 19:27:21.756847 00054249 VND vgId:62, vnode info is committed
07/18 19:27:21.756959 00054249 VND vgId:62, commit end
07/18 19:27:21.759366 00054249 VND vgId:31, start to commit, commit ID:62 version:99475
07/18 19:27:21.762828 00054249 VND vgId:31, vnode info is saved, fname:/data/taos/data/vnode/vnode31/vnode_tmp.json
07/18 19:27:21.762988 00054249 VND vgId:31, vnode info is committed
07/18 19:27:21.763089 00054249 VND vgId:31, commit end
07/18 19:27:21.765436 00054249 DND total vnodes:10 are all closed
07/18 19:27:22.676129 00054249 WAL wal module is cleaned up
07/18 19:27:22.676158 00054249 DND ERROR node:vnode, failed to open since Sync one replica
07/18 19:27:22.676165 00054249 DND ERROR node:vnode, failed to open since Sync one replica
07/18 19:27:22.676170 00054249 DND ERROR failed to open nodes since Sync one replica
07/18 19:27:22.676179 00054249 DND shutting down the service
07/18 19:27:22.878414 00054249 UDF udfd start to stop, need cleanup:0, spawn err:-2
07/18 19:27:23.177104 00054249 DND dnode env is cleaned up

**Environment (please complete the following information):**
 - OS: ubuntu
 - Memory 16G, CPU 4c, current Disk Space 2000G
 - TDengine Version  3.0.1.2

**Additional Context**

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
