### ISSUE TITLE
Questions about query cache

### ISSUE THREAD

**Issue by sudo168** [taosdata/TDengine#2211]
**Case**
TD版本：1.6.2.2
场景：通过超级表查询当天数据，limit 可变
step1: 不用tag作为条件查询，查到最新数据，ID为 6
step2: 插入一条， ID为7
step3: 不用tag作为条件查询，查到的最新数据还是ID为6
step4: 使用tag1作为条件，能查到ID为7的最新数据
step5: 插入一条， ID为8
step6: 使用tag1作为条件，查到的最新数据还是ID为7的数据
step7: 再换成tag2作为条件，又能查到ID为8的数据
step8: 继续 不用tag作为条件查询（查出ID6），继续 使用tag1作为条件（查出ID7）
**Questions**
1、缓存一般都有maxAge ，idleAge吧，两个分别是多久？
2、JDBC，或者其他客户端怎么使用 reset query cache？
3、是否有last_row除外的其他相关函数可以跳过缓存？

**Comment by Aries-Lee1991** [comment]
好，安排相关同事看一下。 @changxiaoqiang

**Comment by hjxilinx** [comment]
这个是libtaos在本地的metricmeta的缓存引起的。可以修改metricmetakeeptimer来缓解该问题。
在配置文件 /etc/taos/taos.cfg 中添加如下的配置项：
`metricmetakeeptimer 3` 
意思是只保留3秒。
