### ISSUE TITLE
希望官方出一款针对TDengine的数据库界面软件

### ISSUE THREAD

**Issue by Intgrp** [taosdata/TDengine#22122]
有官方肯定使用官方的数据库管理客户端，但目前历史的其他管理工具类似navicat之类的并不是针对TDengine，没那么好用，超表和普通表都不方便关联查看，已知开源的TDengineGUI又赶不上官方版本特性更新步伐，经常报异常。

本来程序测试了下TDengine感觉运行非常快速，但一到界面工具，**工具难用，反过来劝退了使用TDengine，配套的生态不够，很难留住用户**。现在也一直在纠结到底要不要项目中使用TDengine。

**Comment by Vijay629** [comment]
DBeaver支持TD，官网推荐的那个GUI工具时间戳显示都不对，而且long类型会溢出难用的一批，DBeaver则没有这些问题，推荐

**Comment by peterchenhdu** [comment]
https://gitee.com/dbquery/td-genie
