### ISSUE TITLE
最新版本3.0.7.1 查询速度很慢

### ISSUE THREAD

**Issue by KiDddder** [taosdata/TDengine#22124]
**Bug Description**
查询超级表的count 要超过1分钟，部署的是集群，不知道有没有关系
![image](https://github.com/taosdata/TDengine/assets/19902899/b56786fe-da15-4ee7-8abe-55d7e7846cf2)

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by ETLGRN** [comment]
遇到同样的问题 该怎么解决

**Comment by sangshuduo** [comment]
估计有乱序数据写入，社区版可以通过数据备份重写解决，企业版通过 compact 命令可以解决

**Comment by ETLGRN** [comment]
> 估计有乱序数据写入，社区版可以通过数据备份重写解决，企业版通过 compact 命令可以解决

您好，麻烦问下乱序是针对超级表说的还是针对子表。子表ts不重复，超级表ts会重复，这种会导致查询变慢吗？

**Comment by sangshuduo** [comment]
只针对子表，数据写入的时候尽量保证写入数据的时间戳递增，否则就是乱序数据，乱序数据超过一定比例会对性能有很大的影响

**Comment by ETLGRN** [comment]
问题解决了，两方面问题：
1.存在少量乱序数据
2.批量插入时，数据没有清理，重复ts，一直覆盖之前的数据

**Comment by DavidChild** [comment]
那怎么查询确认表中是否存在乱序问题呢？
