### ISSUE TITLE
DBeaver连接错误

### ISSUE THREAD

**Issue by xiaojigugu** [taosdata/TDengine#22125]
使用docker在本地部署了TDEngine,version: 3.0.7.1 compatible_version: 3.0.0.0
在代码中使用restful驱动连接成功并且可以正常插入数据
但DBeaver无法连接，报错如下：
![image](https://github.com/taosdata/TDengine/assets/39613470/ee0e846b-15be-452c-bc5d-e25c7d3bde99)
驱动配置如下：
![image](https://github.com/taosdata/TDengine/assets/39613470/496781b4-d558-4b1d-86f7-566757c9689d)

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
