### ISSUE TITLE
ubuntu22 编译出错，不编译tools

### ISSUE THREAD

**Issue by lld1995** [taosdata/TDengine#22140]
**Bug Description**
![image](https://github.com/taosdata/TDengine/assets/17978390/41e056df-78e5-43fd-bb78-1f58e71f266c)

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by sangshuduo** [comment]
什么分支？commit id 是什么？cmake 的完整命令行是什么？

**Comment by lld1995** [comment]
> 什么分支？commit id 是什么？cmake 的完整命令行是什么？

master ,cmake version 3.22.1 ,gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04.1)
commit 0c0acd931f1ed94c45d2248a48b15b7d1226e644

adminadmin@adminadmin-virtual-machine:~/disk2/TDengine/debug$ uname -r
5.19.0-46-generic
adminadmin@adminadmin-virtual-machine:~/disk2/TDengine/debug$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

连编译都有问题，实在是离谱，没人用么，apt install readme上面写的全都装了

**Comment by lld1995** [comment]
> 什么分支？commit id 是什么？cmake 的完整命令行是什么？

cmake .. -DBUILD_TOOLS=false
因为你们那个tao-tools我也编译不过

**Comment by sangshuduo** [comment]
为啥我新拉一个全新的 Docker 能编出来？

docker run -dit ubuntu:22.04

![image](https://github.com/taosdata/TDengine/assets/825729/f3446078-0685-4d02-918d-e14ca4ee013e)

**Comment by sangshuduo** [comment]
root@e8d608fd7d24:/# gcc --version
gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@e8d608fd7d24:/# cmake --version
cmake version 3.22.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
root@e8d608fd7d24:/# cat /etc/issue
Ubuntu 22.04.2 LTS \n \l
