### ISSUE TITLE
根据超级表无法查询，提示表不存在 版本V3.0.5.1

### ISSUE THREAD

**Issue by lsh2366254** [taosdata/TDengine#22146]
加入新节点，重新平衡后，无法根据超级表查询

taos> select count(1) from jt_service_host_track.location_info where   pos_time   > '2023-07-15 07:58:51.183' ;
DB error: Table does not exist (0.136984s)

通过子表查询正常

taos> select origin_latitude  from location_info_013305560545 limit 1;
      origin_latitude      |
============================
              37.286152000 |
Query OK, 1 row(s) in set (0.004822s)

重大bug，请帮忙定位问题。

**Comment by lsh2366254** [comment]
查询超级表标签也正常
taos> SELECT DISTINCT TBNAME, terminal_id FROM location_info;
             tbname             |          terminal_id           |
==================================================================
 location_info_001580366560     | 001580366560                   |
 location_info_001580366553     | 001580366553                   |
 location_info_040835412476     | 040835412476                   |
 location_info_1550000000000... | 15500000000000000009           |
 location_info_1550000000000... | 15500000000000000007           |
 location_info_001580366506     | 001580366506                   |
 location_info_001580366548     | 001580366548                   |
 location_info_013782206099     | 013782206099                   |
 location_info_013305560555     | 013305560555                   |

**Comment by yu285** [comment]
版本号是？之前的具体操作麻烦提供一下截图，或者步骤。

**Comment by lsh2366254** [comment]
> 

版本号：3.0.5.1
步骤：1.新加入DNODE进入集群
           2.执行BALANCE VGROUP
现象：自动平衡完之后，主表无法进行查询

**Comment by zuodengchao** [comment]
> > 
> 
> 版本号：3.0.5.1 步骤：1.新加入DNODE进入集群 2.执行BALANCE VGROUP 现象：自动平衡完之后，主表无法进行查询

这个问题有解决吗，我也遇到了相同的问题，苦恼中

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
