### ISSUE TITLE
After the server restarts, TDengine.Connector  cannot connect to the server

### ISSUE THREAD

**Issue by zhonghuali** [taosdata/TDengine#22141]
**Bug Description**
After the server restarts, TDengine.Connector  cannot connect to the server

**To Reproduce**
Follow the guider: https://docs.tdengine.com/reference/connector/csharp/

客户端启动后，可以正常和taos服务端交互，
这时服务端重启：systemctl restart taosd

原来已经启动的.net connector 中的接口，无法和taos连接
客户端报错: some vnode/qnode/mnode(s) out of service

客户端重新启动,才能够访问
**Expected Behavior**
无需重启客户端应用,可以正常访问服务器

**Screenshots**

**Environment (please complete the following information):**
 - OS: [ CentOS 9]
 - Memory, CPU, current Disk Space
 - TDengine Version [3.0.7.1]

**Additional Context**

**Comment by sangshuduo** [comment]
out of service 通常是环境问题，比如 IP 变了

**Comment by zhonghuali** [comment]
沒有通過IP访问,是通过机器名(服务名)访问,重启后IP会变,但机器名是固定的

**Comment by zhonghuali** [comment]
安装方式是官方推荐的k8s方式.

    spec:
│       containers:
│       - env:
│         - name: POD_NAME
│           valueFrom:
│             fieldRef:
│               apiVersion: v1
│               fieldPath: metadata.name
│         - name: SERVICE_NAME
│           value: tdengine3
│         - name: STS_NAME
│           value: tdengine3
│         - name: STS_NAMESPACE
│           valueFrom:
│             fieldRef:
│               apiVersion: v1
│               fieldPath: metadata.namespace

还需要指定host name 吗?

**Comment by sangshuduo** [comment]
下一个版本 3.1.0.0 解决了这个问题
