### ISSUE TITLE
3.7.0.1 实时查询会出现数据丢失

### ISSUE THREAD

**Issue by KiDddder** [taosdata/TDengine#22157]
**Bug Description**
![image](https://github.com/taosdata/TDengine/assets/19902899/21381ed7-fe29-4f99-81af-3518084efce2)
我会提供一个接口给第三调用，让他来查询数据，比较实时。如图（04:28:06查询）
select * from ipc_super where 1690144024292911644<ts and ts<= 1690144084787242962 查询出来5条数据。
然后9点同样的sql查询出来有7条数据。这个是为什么，怎么解决

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by KiDddder** [comment]
之前3.0.2.0概率很高，现在升级到了3.0.7.1 概率是60万条有2条遗漏

**Comment by sangshuduo** [comment]
什么平台？

**Comment by KiDddder** [comment]
> 什么平台？

公司搭的采集平台，这个应该没什么关系吧

**Comment by KiDddder** [comment]
> > 什么平台？
> 
> 公司搭的采集平台，这个应该没什么关系吧

linux

**Comment by KiDddder** [comment]
> 从来没听说用户报告过这样的问题，确定查询的同时没有其他应用在写入数据吗？

查询的时候 是有插入操作的。插入的ts 是用了tdengine自带的now()函数
类似insert into ipc_aaa(ts,countdone) values(now,'1')
是因为落盘是乱序导致的？查询的时候 落盘没有落完整
