### ISSUE TITLE
文档的一处错误吗？

### ISSUE THREAD

**Issue by ly0928** [taosdata/TDengine#22187]
[OpenTSDB 迁移到 TDengine 中 sum](https://github.com/taosdata/TDengine/blob/main/docs/zh/25-application/03-immigrate.md#sum) 等效函数 书写为：Select max(value) from (select first(val) value from table_name interval(10s) fill(linear)) interval(10s) 这样是正确的吗 是否应为sum(value)

**Comment by sangshuduo** [comment]
欢迎提 PR 修复，谢谢

**Comment by gccgdb1234** [comment]
已经修改上线
