### ISSUE TITLE
有两百多列查询超慢

### ISSUE THREAD

**Issue by keephunny** [taosdata/TDengine#22208]
CentOS Linux release 7.9.2009 (Core)
TDengine Version:3.0.2.2

# 有两百多列查询超慢
select *  from s_79076200093  order by ts desc  limit 0,100;
Query OK, 100 row(s) in set (18.252778s)

select device_sn,ts from s_79076200093  order by ts desc  limit 0,100;
Query OK, 100 row(s) in set (0.474423s)

可有什么查询优化方法，不能减少列。

**Comment by crazy-airhead** [comment]
在测试的时候，分页查询碰到类似的问题，应用层面的处理办法，是做两次查询
1.查询所有的ts列数据
2.用1获取的ts做条件，做union查询

**Comment by yu285** [comment]
这个版本太旧了，直接部署 3.3.2.0 吧，各方面都有大幅提升
