### ISSUE TITLE
java REST连接与客户端直接查询，返回结果不同

### ISSUE THREAD

**Issue by 18518758363** [taosdata/TDengine#22204]
![image](https://github.com/taosdata/TDengine/assets/20415246/41c982ce-1b76-490a-85ae-379b64551dba)
<img width="1210" alt="image" src="https://github.com/taosdata/TDengine/assets/20415246/ad667c8d-593c-4fe7-8570-9fe089e74acb">
![image](https://github.com/taosdata/TDengine/assets/20415246/c4ed1d63-e3ef-4b90-b562-dd46fd4ba917)

**Comment by yu285** [comment]
版本号是？

另图片不够清晰，无法判断
