### ISSUE TITLE
invalid table id

### ISSUE THREAD

**Issue by huangheding** [taosdata/TDengine#2220]
持续不间断往超级表内插入数据并且建立子表，偶尔会抛出error： invalid table id

![Uploading image.png…]()

**Comment by Aries-Lee1991** [comment]
好的， @xiaopingcs 请验证一下是否是Bug～

**Comment by xiaopingcs** [comment]
> 持续不间断往超级表内插入数据并且建立子表，偶尔会抛出error： invalid table id

Hi, can you share your code used to created tables?

**Comment by huangheding** [comment]
> > 持续不间断往超级表内插入数据并且建立子表，偶尔会抛出error： invalid table id
> 
> Hi, can you share your code used to created tables?

OK,
golang connector
//init conn
func InitDB() {
	var err error
	db, err = sql.Open(conf.GetConf().TAOS.Driver,
		fmt.Sprintf("%s:%s@/tcp(%v)/xiaojin", conf.GetConf().TAOS.DBUser, conf.GetConf().TAOS.DBPwd, conf.GetConf().TAOS.DBUrl))
	if err != nil {
		panic(err)
	}

	//defer db.Close()
}

//handle data 
for {
		select {
		case res := <-batchChan:
			go func() {
				if err := handleData(res); err != nil {
					b = false
				}
			}()
		case err := <-errChan:
			time.Sleep(2 * time.Second)
			glog.FPrint("WaitSeconds Overtime", err)
		}
		//time.Sleep(1 * time.Second)
	}



//insert(stable)
func InsertAliPoint(m map[string]interface{}) error {
	
	sql := `insert into ? using xj_ali_point2 tags(?) values(?,?,?,?,?,?,?,?,?)`
	stmt, err := db.GetConn().Prepare(sql)
	if err != nil {
		log.Errorf("insert stmt error:%s", err.Error())
		return err
	}

	s := []interface{}{"t" + m["deviceName"].(string), m["deviceName"], 0}
	for _, v := range strings.Split(m["record"].(string), ",") {
		s = append(s, v)
	}

	_, err = stmt.Exec(s...)
	if err != nil {
		log.Errorf("sql:%s\n param:%v\n", sql, s)
		return err
	}
	return nil
}

**Comment by xiaopingcs** [comment]
Hi, @huangheding sorry for late response. I am trying to reproduce your issue. can you answer following questions.
1. how many STABLEs (super table) did you create?
2. how many normal tables did you create for each STABLE?
3. how many records did you insert into each table?

**Comment by Aries-Lee1991** [comment]
@huangheding The issue is no update for 16 days. Did you solute it？

**Comment by xiaopingcs** [comment]
用户长时间没有回应，先关闭这个问题，如果还有相同问题，请重新创建一个issue或重新把这个问题reopen
