### ISSUE TITLE
taosdb crash and fail to restart after execute a create stream

### ISSUE THREAD

**Issue by monkiu-fish** [taosdata/TDengine#22222]
**Bug Description**
3台服务器组成了一个数据库集群，创建的测试库ems分别在vnode1和vnode2上，在测试库ems创建一个超级表ems_data，在这个空的超级表上创建stream，导致数据库crash

**To Reproduce**
1. 创建一个流，创建语句如下：
create stream ems_power_stream trigger at_once into ems_power_hour 
tags(obj_id int, mete_id int, module_id int, province_area bigint,city_area bigint,district_area bigint,station_id bigint) 
as select _wstart report_time,(last(fval)-first(fval)) eval from ems_data where mete_id=116001001 
partition by obj_id,mete_id,module_id,province_area,city_area,district_area,station_id interval(1h) sliding(1h)
2. 等待数十秒后，提示：DB error: Database is starting up (36.549606s)
3. 查看数据库进程，vnode1和vnode2的数据库进程都crash了。
4. 重启数据库进程失败，日志如下：
vnode1日志如下:
07/28 09:01:59.015011 00028859 TQ  expand stream task on vg 66, task id 1247806800, child id 0, level 2
07/28 09:01:59.015247 00028844 MND trans:42484, redoAction:5 response is received, code:0x0, accept:0x0 retry:0x0
07/28 09:01:59.015295 00028844 MND trans:42484, continue to execute, stage:redoAction createTime:1690449956866 leader:1
07/28 09:01:59.015317 00028844 MND trans:42484, 6 of 8 actions executed
07/28 09:01:59.015333 00028844 MND trans:42484, stage keep on redoAction since Action in progress
07/28 09:01:59.021017 00028859 UTL FATAL crash signal is 11
07/28 09:01:59.021069 00028859 UTL FATAL sender PID:0 cmdline:
07/28 09:01:59.022615 00028859 UTL FATAL obtained 19 stack frames
07/28 09:01:59.022629 00028859 UTL FATAL frame:0, taosd(createExprFromOneNode+0x68) [0x5da238]
07/28 09:01:59.022638 00028859 UTL FATAL frame:1, taosd(createExprFromTargetNode+0x32) [0x5dac0f]
07/28 09:01:59.022655 00028859 UTL FATAL frame:2, taosd(createExprInfo+0x10a) [0x5dad1c]
07/28 09:01:59.022662 00028859 UTL FATAL frame:3, taosd(createStreamScanOperatorInfo+0x292) [0x5a6537]
07/28 09:01:59.022669 00028859 UTL FATAL frame:4, taosd(createOperatorTree+0x669) [0x58a78b]
07/28 09:01:59.022676 00028859 UTL FATAL frame:5, taosd(createOperatorTree+0xb87) [0x58aca9]
07/28 09:01:59.022684 00028859 UTL FATAL frame:6, taosd(createExecTaskInfoImpl+0xfe) [0x58b6f2]
07/28 09:01:59.022690 00028859 UTL FATAL frame:7, taosd(qCreateExecTask+0xcd) [0x58114a]
07/28 09:01:59.022697 00028859 UTL FATAL frame:8, taosd(qCreateStreamExecTaskInfo+0x91) [0x58090b]
07/28 09:01:59.022704 00028859 UTL FATAL frame:9, taosd(tqExpandTask+0x210) [0x56b41e]
07/28 09:01:59.022710 00028859 UTL FATAL frame:10, taosd(streamMetaAddTask+0x35) [0x5fc376]
07/28 09:01:59.022717 00028859 UTL FATAL frame:11, taosd(tqProcessTaskDeployReq+0xb3) [0x56bd31]
07/28 09:01:59.022725 00028859 UTL FATAL frame:12, taosd(vnodeProcessWriteMsg+0x73a) [0x5018e7]
07/28 09:01:59.022732 00028859 UTL FATAL frame:13, taosd() [0x506447]
07/28 09:01:59.022739 00028859 UTL FATAL frame:14, taosd() [0x5069da]
07/28 09:01:59.022747 00028859 UTL FATAL frame:15, taosd(vnodeProposeWriteMsg+0x61d) [0x5071db]
07/28 09:01:59.022760 00028859 UTL FATAL frame:16, taosd() [0x8a6a85]
07/28 09:01:59.022767 00028859 UTL FATAL frame:17, /lib64/libpthread.so.0(+0x7ea5) [0x7f69172a1ea5]
07/28 09:01:59.022774 00028859 UTL FATAL frame:18, /lib64/libc.so.6(clone+0x6d) [0x7f6916bbeb0d]
段错误(吐核)
vnode2日志如下：
07/28 09:01:59.018077 00006244 TQ  expand stream task on vg 67, task id 1247806799, child id 1, level 3
07/28 09:01:59.048210 00006244 UTL FATAL crash signal is 11
07/28 09:01:59.048259 00006244 UTL FATAL sender PID:0 cmdline:
07/28 09:01:59.049577 00006244 UTL FATAL obtained 19 stack frames
07/28 09:01:59.049585 00006244 UTL FATAL frame:0, taosd(createExprFromOneNode+0x68) [0x5da238]
07/28 09:01:59.049590 00006244 UTL FATAL frame:1, taosd(createExprFromTargetNode+0x32) [0x5dac0f]
07/28 09:01:59.049594 00006244 UTL FATAL frame:2, taosd(createExprInfo+0x10a) [0x5dad1c]
07/28 09:01:59.049601 00006244 UTL FATAL frame:3, taosd(createStreamScanOperatorInfo+0x292) [0x5a6537]
07/28 09:01:59.049605 00006244 UTL FATAL frame:4, taosd(createOperatorTree+0x669) [0x58a78b]
07/28 09:01:59.049609 00006244 UTL FATAL frame:5, taosd(createOperatorTree+0xb87) [0x58aca9]
07/28 09:01:59.049613 00006244 UTL FATAL frame:6, taosd(createExecTaskInfoImpl+0xfe) [0x58b6f2]
07/28 09:01:59.049617 00006244 UTL FATAL frame:7, taosd(qCreateExecTask+0xcd) [0x58114a]
07/28 09:01:59.049620 00006244 UTL FATAL frame:8, taosd(qCreateStreamExecTaskInfo+0x91) [0x58090b]
07/28 09:01:59.049624 00006244 UTL FATAL frame:9, taosd(tqExpandTask+0x210) [0x56b41e]
07/28 09:01:59.049628 00006244 UTL FATAL frame:10, taosd(streamMetaAddTask+0x35) [0x5fc376]
07/28 09:01:59.049632 00006244 UTL FATAL frame:11, taosd(tqProcessTaskDeployReq+0xb3) [0x56bd31]
07/28 09:01:59.049636 00006244 UTL FATAL frame:12, taosd(vnodeProcessWriteMsg+0x73a) [0x5018e7]
07/28 09:01:59.049640 00006244 UTL FATAL frame:13, taosd() [0x506447]
07/28 09:01:59.049649 00006244 UTL FATAL frame:14, taosd() [0x5069da]
07/28 09:01:59.049654 00006244 UTL FATAL frame:15, taosd(vnodeProposeWriteMsg+0x61d) [0x5071db]
07/28 09:01:59.049657 00006244 UTL FATAL frame:16, taosd() [0x8a6a85]
07/28 09:01:59.049661 00006244 UTL FATAL frame:17, /lib64/libpthread.so.0(+0x7ea5) [0x7f5e52ac7ea5]
07/28 09:01:59.049665 00006244 UTL FATAL frame:18, /lib64/libc.so.6(clone+0x6d) [0x7f5e523e4b0d]
段错误(吐核)
5.查看core文件内容如下：
vnode1的core文件如下：
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `taosd'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000005da238 in createExprFromOneNode (pExp=0x7f684c262870, pNode=0x5f6a626f00000004, slotId=0)
    at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/libs/executor/src/executil.c:1313
1313    /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/libs/executor/src/executil.c: 没有那个文件或目录.
vnode2的core文件如下：
[New LWP 6216]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `taosd'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000005da238 in createExprFromOneNode (pExp=0x7f5dcc129e70, pNode=0x5f6a626f00000004, slotId=0)
    at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/libs/executor/src/executil.c:1313
1313    /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/libs/executor/src/executil.c: 没有那个文件或目录.
Missing separate debuginfos, use: debuginfo-install glibc-2.17-326.el7_9.x86_64 libgcc-4.8.5-44.el7.x86_64

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [CentOS Linux release 7.9.2009]
 - Memory, CPU, current Disk Space
 - TDengine Version [3.0.2.6]

**Additional Context**

在尝试启动服务的过程中，将/data/vnode/vnode66/wal，/data/vnode/vnode67/wal目录下的文件删除，启动服务错误依旧存在。盼回复，希望能够尽快解决问题。

经过一天的折腾，大概知道是什么引起服务crash了。在重建服务后，使用新的创建stream语句就没有问题，新语句如下：
create stream ems_power_stream trigger at_once into ems_power_hour  
as select _wstart,(last(fval)-first(fval)) as eval from ems_data where mete_id=116001001 
partition by obj_id,mete_id,module_id,province_area,city_area,district_area,station_id interval(1h) sliding(1h)
与之前最大的区别就是把tags(obj_id int, mete_id int, module_id int, province_area bigint,city_area bigint,district_area bigint,station_id bigint) 去掉了。
加上自定义的tags，就肯定会导致服务crash。通过上述现象，说明创建stream在这个版本是有局限性的。
建议针对这个BUG进行修复，否则在生产系统上非法创建stream，会直接导致服务crash掉，这是致命的BUG。
还有就是建议加强自定义TAGS的支持，否则会造成大量的冗余数据。

**Comment by yu285** [comment]
流计算已经重构了，麻烦使用最新版吧，这些问题都修复了。
