### ISSUE TITLE
Windows环境运行taosdump.exe报找不到MSVCP140D.dll

### ISSUE THREAD

**Issue by dazzulay** [taosdata/TDengine#22253]
![EVABMX8KRG B$@ZNU(HLJ N](https://github.com/taosdata/TDengine/assets/21986054/0e34e511-4f4a-4b74-8aa1-d144bff53d8a)
版本[TDengine-server-3.0.7.1-Windows-x64.exe (21.6 M)](https://docs.taosdata.com/releases/tdengine/#!)

**Comment by ZLey373** [comment]
安装一个vs2019可能解决，它里面可能含有MSVCP140D.dll

**Comment by dazzulay** [comment]
> 安装一个vs2019可能解决，它里面可能含有MSVCP140D.dll

是不是编译的使用了debug模式，正常发布不应该用release模式吗，总不可能生成环境还装个VS2019吧

**Comment by ZLey373** [comment]
你电脑里少这个MSVCP140D.dll文件, 网上下载一个放进去呗。
