### ISSUE TITLE
 failed to change the password using the taos command with -s

### ISSUE THREAD

**Issue by elysian-gc** [taosdata/TDengine#22300]
**Bug Description**
taos -s 修改root密码，不能登录

**To Reproduce**
1. install taosd
2. taos -s "ALTER USER root pass 'lNSOA91tcFNLcqfzpHOTELT2opYY8EjS'"
3. taos -uroot -p

**Expected Behavior**
can login in 

**Screenshots**

![image](https://github.com/taosdata/TDengine/assets/44466800/edc1c574-286f-4270-b67a-bf09ac74fc00)

**Environment (please complete the following information):**
 - OS: 5.10.184-175.749.amzn2.aarch64
 - Memory, CPU, current Disk Space
 - TDengine Version  3.0.5.1

**Additional Context**
None

**Comment by elysian-gc** [comment]
测试下来是长度限制。希望能优化提示。

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
