### ISSUE TITLE
官网docker swarm 部署后连接报错

### ISSUE THREAD

**Issue by lwjlucky** [taosdata/TDengine#22341]
按照官网 docker swarm 部署方式部署之后服务正常启动但是在连接的时候出现报错。
![image](https://github.com/taosdata/TDengine/assets/45527588/4cba0221-8f7e-4ea8-b48f-d85a2a166fed)
![image](https://github.com/taosdata/TDengine/assets/45527588/54ee0914-1bc2-4140-990b-8fd0c823089f)

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
