### ISSUE TITLE
3.0  start failed

### ISSUE THREAD

**Issue by Diend-7** [taosdata/TDengine#22361]
![image](https://github.com/taosdata/TDengine/assets/52726737/3f859eda-b34c-41e0-8dfd-4b4948f86007)

7月底重启服务器之后重启失败

**Comment by sangshuduo** [comment]
具体什么版本？

**Comment by Diend-7** [comment]
> 

3.0.2.4

**Comment by sangshuduo** [comment]
先升到 3.0.7.1 看看还有没有问题

**Comment by Diend-7** [comment]
> 

<img width="775" alt="image" src="https://github.com/taosdata/TDengine/assets/52726737/078762e6-3905-43df-963c-921b397490b1">
升级过后报这个错误
