### ISSUE TITLE
v1.6.5.9 insert, DB error: invalid DB

### ISSUE THREAD

**Issue by sudo168** [taosdata/TDengine#2236]
**Bug Description**
insert into test.t_1(ts, price) values(1591847933452, 0.00);  //执行 OK
insert into 'test.t_1'(ts, price) values(1591847933452, 0.00); //执行 DB error: invalid DB

**Comment by Aries-Lee1991** [comment]
OK, we'll check it.

**Comment by plum-lihui** [comment]
1、确实对于加引号后，处理有点问题，没有正确去掉引号再查找DB或table；
2、使用的时候，请先不要对 数据库名 和 表名加引号吧。

**Comment by plum-lihui** [comment]
我会在下个版本解决。
