### ISSUE TITLE
docker启动服务修改映射端口,服务异常

### ISSUE THREAD

**Issue by LarryXp123** [taosdata/TDengine#22381]
**Bug Description**
docker启动服务，如果宿主机不用6030映射，服务就不能完全正常的运行

`docker run -d --restart=always --name tdengine1 -p 6030:6030 tdengine/tdengine:3.1.0.0`

`docker run -d --restart=always --name tdengine2 -p 50580:6030 -p 50581:6041 tdengine/tdengine:3.1.0.0`

`docker run -d --restart=always --name tdengine3 -p 50585:6030 -p 50586:6041 -p 50587-50593:6043-6049 -p 50587-50593:6043-6049/udp tdengine/tdengine:3.1.0.0`

启动3个容器，分别tdengine1 用6030端口映射，tdengine2 用50580端口映射，tdengine3映射出全部端口 

taos -h ip:6030
taos -h ip:50580
taos -h ip:50585
都能连接上

执行基本语句，tdengine1 没什么问题。tdengine2 、tdengine3，执行语句很容易报错，服务应该有问题。

CREATE STABLE IF NOT EXISTS meters (ts TIMESTAMP, current FLOAT, voltage INT, phase FLOAT) TAGS (location BINARY(64), groupId INT);

taos> show tables;
DB error: Unable to establish connection (10.231504s)

taos> CREATE TABLE IF NOT EXISTS m3 USING `meters` TAGS ('m4', 4);
DB error: Table does not exist (0.522312s)

**Screenshots**
![image](https://github.com/taosdata/TDengine/assets/141024800/64672ed7-4ec2-4452-ba58-9254e9a7a56a)
![image](https://github.com/taosdata/TDengine/assets/141024800/873fc820-b833-470e-8aff-eb7fad0e6f5f)

**Environment (please complete the following information):**
 - CentOS Linux release 7.5.1804
 - TDengine Version [3.1.0.0]，2.4也有这个问题，应该和版本无关

**Additional Context**

**Comment by yu285** [comment]
需要确保内外的端口配置保持一致。
