### ISSUE TITLE
建议提供按版本下载？

### ISSUE THREAD

**Issue by mingciong** [taosdata/TDengine#224]

**Comment by guanshengliang** [comment]
感谢您的建议，近期会讨论是否在网站上增加此项功能

**Comment by yiluohan1234** [comment]
能否提供windows的版本？每次都是自己编译，有些麻烦

**Comment by StoneT2000** [comment]
@mingciong 昨天加了安版本下载方式，请访问 https://www.taosdata.com/cn/all-downloads/
