### ISSUE TITLE
连接报错 java.sql.SQLException: ERROR (2318): Read timed out

### ISSUE THREAD

**Issue by feythin** [taosdata/TDengine#22409]
Bug Description
当连接数突增的时候，客户端出现java.sql.SQLException: ERROR (2318): Read timed out
监控如下，再11:50的时候出现，服务器端没有相关报错日志。
![image](https://github.com/taosdata/TDengine/assets/1758752/e6f8e04a-747f-445c-ab42-493b3519a745)

Environment
物理机部署，sata盘，三副本
TDengine Version 3.0.2.5

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
