### ISSUE TITLE
Windows Docker挂载/var/lib/taos和/var/log/taos到D盘后，无法启动容器

### ISSUE THREAD

**Issue by houluy** [taosdata/TDengine#22412]
在Windows Docker上通过如下命令启动容器后，会反复重复后续错误消息，`udfd`进程状态码251，请问是什么问题？

镜像版本：

**tdengine/tdengine:latest**

启动容器命令：

```powershell
docker run -d --name tdengine -v /d/DB/Taos/data:/var/lib/taos -v /d/DB/Taos/log:/var/log/taos -p 6041:6041 tdengine/tdengine
```

错误消息：
```
2023-08-13 15:29:18 08/13 07:29:18.985560 00000118 UDF udfd process exited with status 251, signal 0
2023-08-13 15:29:18 08/13 07:29:18.985581 00000118 UDF udfd process restart
2023-08-13 15:29:18 08/13 07:29:18.985584 00000118 UDF start to init udfd
2023-08-13 15:29:18 08/13 07:29:18.985591 00000118 UDF udfd LD_LIBRARY_PATH: ::/usr/lib
2023-08-13 15:29:18 08/13 07:29:18.990507 00000118 UDF udfd is initialized
```

**Comment by sangshuduo** [comment]
![](https://github.com/taosdata/TDengine/assets/825729/17c524de-535d-4918-941e-fc3a2a7b9f61)

无法复现

**Comment by Gerrit1999** [comment]
请问解决了吗? 我也遇到了这个问题, 版本3.0.7.1

**Comment by oneya999** [comment]
同样的问题我也遇到了。
电脑系统：windows2019
docker版本为Docker Desktop 4.23.0 (120376) 
TDEngine容器： 3.0.7.1

启动容器的命令：
`docker run --network xxx -v //d/FJY/FJY_docker/db/taos:/var/lib/taos -d -e TAOS_FQDN=tdengine -e TZ=Asia/Shanghai --name tdengine -p 6030:6030 -p 6041-6049:6041-6049 -p 6041-6049:6041-6049/udp --restart on-failure tdengine/tdengine:3.0.7.1`

错误消息：
![WechatIMG176](https://github.com/taosdata/TDengine/assets/67720922/82e40744-2b53-40a0-9bab-4dd91e6ba87f)
![WechatIMG175](https://github.com/taosdata/TDengine/assets/67720922/d2b52a36-549c-4c78-8ec5-0c73d7baf088)

但是在windows11运行相同的启动命令就没有问题，请问这是什么问题？

**Comment by gccgdb1234** [comment]
请从容器和操作系统差异找原因，综合现象描述，不是 TDengine 的问题

**Comment by johnnylc** [comment]
操作系统：Windows Server 2019使用docker-desktop部署同样遇到该问题，启动命令为：
docker run -d --name tdengine --restart=always --net rz_network --ip 172.172.0.10 -p 6030:6030 -p 6041:6041 -p 6043-6049:6043-6049 -p 6043-6049:6043-6049/udp --hostname="td_local" -v /d/docker/volumes/taos/conf/taos.cfg:/etc/taos/taos.cfg -v /d/docker/volumes/taos/log:/var/log/taos -v /d/docker/volumes/taos/data:/var/lib/taos tdengine/tdengine:3.1.1.0

**Comment by johnnylc** [comment]
> 同样的问题我也遇到了。 电脑系统：Windows Server 2019 docker版本为Docker Desktop 4.23.0 (120376) TDEngine容器： 3.0.7.1
> 
> 启动容器的命令： `docker run --network xxx -v //d/FJY/FJY_docker/db/taos:/var/lib/taos -d -e TAOS_FQDN=tdengine -e TZ=Asia/Shanghai --name tdengine -p 6030:6030 -p 6041-6049:6041-6049 -p 6041-6049:6041-6049/udp --restart on-failure tdengine/tdengine:3.0.7.1`
> 
> 错误消息： ![WechatIMG176](https://user-images.githubusercontent.com/67720922/268991558-82e40744-2b53-40a0-9bab-4dd91e6ba87f.jpg) ![WechatIMG175](https://user-images.githubusercontent.com/67720922/268991594-d2b52a36-549c-4c78-8ec5-0c73d7baf088.jpg)
> 
> 但是在windows11运行相同的启动命令就没有问题，请问这是什么问题？

您好 我使用windows server 2019遇到一样的问题了，请问您这边问题解决了吗？
