### ISSUE TITLE
httpServer segment fault in poor network environment or heavy load

### ISSUE THREAD

**Issue by freemine** [taosdata/TDengine#2244]
**Bug Description**
implementation httpProcessData is `block-mode`, which will break if request is received piece by piece.
with help of **curl/socat,** it can be reproduced as follows.

**To Reproduce**
1. start taosd
2. open another terminal, and run 
**curl -H 'Host: 127.0.0.1' -H 'Damn: foooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooobarrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr' 127.0.0.1:6020/rest/login/root/taosdata**
3. this reports ok, 
4. run:
**socat -b16 TCP-LISTEN:2060,fork,reuseaddr TCP:localhost:6020**
5. open another terminal, and run:
**curl -D - -H 'Host: 127.0.0.1' -H 'Damn: foooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooobarrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr' 127.0.0.1:2060/rest/login/root/taosdata**
6. random output as follows, from time to time:
**{"status":"error","code":1005,"desc":"http head parse error"}**
or
**curl: (52) Empty reply from server**
and we also see core dump at taosd very much offen
**06/11 16:07:25.137039 0x140030321870592 ERROR HTP context:0x7f5b5999e3f0, fd:20, ip:127.0.0.1:50412, code:406, error:http head parse error
Segmentation fault (core dumped)**

we also use such commands to make sure it's not **curl/socat** problem.
**socat -b16 TCP-LISTEN:2060,fork,reuseaddr TCP:www.baidu.com:80**
**curl -D - -H 'Host: www.baidu.com' -H 'Damn: foooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooobarrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr' 127.0.0.1:2060**
output is **HTTP/1.1 200 OK**

bypass socat:
**curl -D - -H 'Host: 127.0.0.1' -H 'Damn: foooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooobarrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr' 127.0.0.1:6020/rest/login/root/taosdata**
output is **HTTP/1.1 200 OK**

**Expected Behavior**
httpServer does not provide different behaviour in case of poor network.

**Environment (please complete the following information):**
 - OS: Linux xxxxx-VirtualBox 5.4.0-33-generic #37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - MemTotal:        8153508 kB
 - TDengine Version latest version in github

**Comment by Aries-Lee1991** [comment]
OK, we'll check it.

**Comment by sangshuduo** [comment]
@freemine thanks for your brilliant report. We will fix it ASAP.

**Comment by freemine** [comment]
@Aries-Lee1991 , the bug still exists. y u close it?

**Comment by guanshengliang** [comment]
This problem can be reproduced steadily
Let's reopen this question

**Comment by guanshengliang** [comment]
sorry, I press the wrong button and caused the issue closed
I wrote a loop and sent 300 requests, and no problems was found

**Comment by freemine** [comment]
so sorry to mention again, this bug is still there, i just tested with curl/socat. sometime error message received, sometime http 200 is received as expected, but core dump will be there after about 7~8 times of failure.

and i recheck your code and found this:

```
143 bool httpGetHttpMethod(HttpContext* pContext) {
144   HttpParser* pParser = &pContext->parser;
145 
146   char*       pSeek = strchr(pParser->pLast, ' ');
147   if (pSeek == NULL) {
148     httpSendErrorResp(pContext, HTTP_PARSE_HTTP_METHOD_ERROR);
149     return false;
150   }
```

in poor network, **strchr** won't be satisfied with correct answer, and **httpGetHttpMethod** will return **false** back in the calling-stack until http_process callback is finished. but leaving the http parser in the state that's not re-continued.

i believe this is the root-cause of this bug, not ref-count.

**Comment by freemine** [comment]
have u tried curl/socat?

**Comment by guanshengliang** [comment]
The above modification makes the server not to crash
and when this happens, there are two treatments in server sid

1. wait for the end of reading
2. close server connection

**Comment by guanshengliang** [comment]
whil head parse failed, we notify fd to close it self

**Comment by freemine** [comment]
same request, but different response as follows:
```
xxx@xxx-VirtualBox:~$ curl -D - -H 'Host: 127.0.0.1' -H 'Damn: foooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooobarrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr' 127.0.0.1:2060/rest/login/root/taosdata
HTTP/1.1 406 Not Acceptable
Access-Control-Allow-Origin:*
Content-Type: application/json;charset=utf-8
Content-Length: 61

{"status":"error","code":1005,"desc":"http head parse error"}xxh@xxh-VirtualBox:~$ 
xxx@xxx-VirtualBox:~$ curl -D - -H 'Host: 127.0.0.1' -H 'Damn: foooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooobarrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr' 127.0.0.1:2060/rest/login/root/taosdata
HTTP/1.1 200 OK
Access-Control-Allow-Origin:*
Content-Type: application/json;charset=utf-8
Content-Length: 100

{"status":"succ","code":0,"desc":"/KfeAzX/f9na8qdtNZmtONryp201ma04bEl8LcvLUd7a8qdtNZmtONryp201ma04"}xxx@xxx-VirtualBox:~$ 
```

good part is: app seems not crash with correct ref-count now.
:)
