### ISSUE TITLE
/usr/include/taos.h: No such file or directory

### ISSUE THREAD

**Issue by tony358** [taosdata/TDengine#22444]
使用Dockerfile安装官方完整客户端包（TDengine-client-3.1.0.0-Linux-x64.tar.gz）时出错，如下图：
![AC7D4666-4D6B-4161-822E-86E9192DFEE5](https://github.com/taosdata/TDengine/assets/26424684/b87ff7b5-8943-4048-b0e6-52c1bdb48a0c)

**Comment by sangshuduo** [comment]
用 bash install_client.sh 试试

**Comment by tony358** [comment]
> 用 bash install_client.sh 试试

试过了，还是会报错。
![image](https://github.com/taosdata/TDengine/assets/26424684/3fcbe1ba-0d5a-45e2-8e30-c9c7eafc7f49)

**Comment by sangshuduo** [comment]
![](https://github.com/taosdata/TDengine/assets/825729/bd24b798-8080-4223-8999-21346245e6cd)

**Comment by tony358** [comment]
> ![](https://user-images.githubusercontent.com/825729/262207979-bd24b798-8080-4223-8999-21346245e6cd.png)

问题已解决，Dockerfile由于使用了精简版jdk alpine，导致缺少部分文件安装不成功。现已替换jdk版本安装成功。
