### ISSUE TITLE
超级表删不掉 Invalid value in client

### ISSUE THREAD

**Issue by hjy30312** [taosdata/TDengine#22466]
版本  3.0.2.6
有一个超级表，我把字段扩展到 nchar(5000)然后报错， DB error: Fail to get table info, error: Invalid value in client 

想删也删不掉，应该怎么办呢？
taos> drop table zzj_assembly_agv;

DB error: Invalid value in client (0.000718s)

**Comment by yu285** [comment]
这个是旧版本的问题，后面已经修复了。

咱们是测试环境吗，方便的话重建一下环境吧,使用最新版本 3.1.0.2。

微信：a15652223354
