### ISSUE TITLE
Win11安装没有释放taosd.exe

### ISSUE THREAD

**Issue by Cyaim** [taosdata/TDengine#22494]
**Bug Description**
windows 11 安装后没有释放taosd.exe

**To Reproduce**
1.双击安装
![image](https://github.com/taosdata/TDengine/assets/28213262/243f63c9-3f4b-4e82-85f9-610b01633cf7)
![image](https://github.com/taosdata/TDengine/assets/28213262/80513872-94a8-45ad-b9ff-c1071b24a158)

2. 进入C:\TDengine文件夹
![image](https://github.com/taosdata/TDengine/assets/28213262/bf10a8b2-0db8-4372-b81e-41f341da4f67)

4. 没有发现有taosd.exe文件，并且taos命令无法连接到服务

**Screenshots**
系统环境
![image](https://github.com/taosdata/TDengine/assets/28213262/aaf07386-e573-4cc1-ad36-bce639e691a7)

**Environment (please complete the following information):**
 - OS:Win11
 - Memory, CPU, current Disk Space
 - TDengine Version 3.1.0.0

**Comment by sangshuduo** [comment]
3.1.0.0 开始社区版 Windows 版不再包含 taosd 服务端程序，请联系取得企业版
