### ISSUE TITLE
流式计算中按自然月月聚合应该怎么写？

### ISSUE THREAD

**Issue by lulg** [taosdata/TDengine#22505]
我想再流式计算中实现一个按月聚合的语句，比如实时统计当月的平均值，写入另一个超表，但是不知道怎么写。
我看留的事件窗口都是时间长度，怎么能保证它是从月初开始聚合统计呢呢。

1d、1n是不是就代表自然日和自然月？

**Comment by yu285** [comment]
你说的对。是这样的
