### ISSUE TITLE
在使用group by 的情况下，使用udf的聚合函数异常

### ISSUE THREAD

**Issue by PapaOfFantuan** [taosdata/TDengine#22503]
**Bug Description**
pycumsum为聚合函数的例子程序

对于
select security_id,pycumsum(AR) from t_factors where parttime >= '2023-08-17' and security_id in ('000001.XSHE.ESA','000012.XSHE.E
SA') group by security_id ;
只返回了 000001.XSHE.ESA 的聚合值

对于
select security_id,sum(AR) from t_factors where parttime >= '2023-08-17' and security_id in ('000001.XSHE.ESA','000012.XSHE.ESA') 
group by security_id ;
同时返回了000001.XSHE.ESA与000012.XSHE.E
SA的聚合值

通过在udf中增加日志，发现pycumsum.py中的reduce函数的data中的数据只有security_id='000001.XSHE.ESA'相关的数据

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**
<img width="415" alt="image" src="https://github.com/taosdata/TDengine/assets/1526039/0e060f70-0bde-4dab-b160-f21d2a45a553">
![image](https://github.com/taosdata/TDengine/assets/1526039/a96fb40b-ead6-4dd7-8d06-8ad3f610454d)
![image](https://github.com/taosdata/TDengine/assets/1526039/984f3be5-d61e-4673-b4b6-97f95090fec5)
![image](https://github.com/taosdata/TDengine/assets/1526039/4dc57e85-2e79-49b5-adbb-515ff52c4c1e)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - TDengine Version 3.0.7.1

**Additional Context**

**Comment by PapaOfFantuan** [comment]
附加pycumsum.py代码

def log(o):
    LOG_FILE.write(str(o) + '\n')

def destroy():
    log("close log file: spread.log")
    LOG_FILE.close()

def start():
    return pickle.dumps(0.0)

def finish(buf):
    return pickle.loads(buf)

def reduce(datablock, buf):
    log(dir(datablock))
    log(datablock.meta(0))
    (rows, cols) = datablock.shape()
    if buf is None:
        state = 0.0
    else:
        state = pickle.loads(buf)
    row = []
    for i in range(rows):
        for j in range(cols):
            cell = datablock.data(i, j)
            if cell is not None:
                log("value:%f" % (cell,))
                row.append(datablock.data(i, j))
    if len(row) > 1:
        new_state = np.cumsum(row)[-1]
    else:
        new_state = state
    log("new_state:%f" % (new_state,))
    return pickle.dumps(new_state)

**Comment by shenglian-zhou** [comment]
Could you please write the whole python program with indent? thanks a lot.

**Comment by shenglian-zhou** [comment]
I have run the sample pycumsum program with group by and no problems are found. Could you please check it again?

**Comment by PapaOfFantuan** [comment]
> I have run the sample pycumsum program with group by and no problems are found. Could you please check it again?

**Comment by PapaOfFantuan** [comment]
> I have run the sample pycumsum program with group by and no problems are found. Could you please check it again?

可以跑，但是返回的结果有问题，应该返回的至少两条记录，但是只返回了一条，另外日志方面，只执行了一次函数，我的理解，应该会为每一次的group by 聚合 执行一次函数
