### ISSUE TITLE
taosd异常停止前在服务器写入大量的core.pid文件

### ISSUE THREAD

**Issue by w15135591069** [taosdata/TDengine#22528]
版本:3.0.5.0
程序:jdk1.8,springboot,使用HikariDataSource连接池,jdbc:TAOS-RS,进行连接
未找到异常信息
怀疑执行 range('2023-08-03 00:00:00', '2023-08-03 23:59:59') every(10m) fill(value,0) 这类型的SQL语句失败后数据源服务器会写入大量的
image
core.pid文件,改文件大小4到4G左右

**Comment by yu285** [comment]
3.0.5.0 的话建议升级到 3.1.0.2 再做验证

如果还有问题我可以远程排查

微信：a15652223354
