### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by yangzilong1986** [taosdata/TDengine#22523]
**Bug Description**

tdengine 版本3.1.0
在执行docker容器里执行一条sql出现错误，导致容器异常退出。

select * from table_abc a where a.ts > '2021-04-27' and a.ts< '2021-12-30' order by a.ts desc;

08/22 11:32:38.887686 00000462 UTL FATAL assert info not provided
08/22 11:32:38.888137 00000462 UTL FATAL tAssert at file /data/release/TDinternal/community/source/dnode/vnode/src/tsdb/tsdbRead2.c:2675 exit:1
08/22 11:32:38.892940 00000462 UTL FATAL obtained 17 stack frames
08/22 11:32:38.892951 00000462 UTL FATAL frame:0, taosd(taosAssertDebug+0x1c6) [0x1106186]
08/22 11:32:38.892954 00000462 UTL FATAL frame:1, taosd() [0x85d218]
08/22 11:32:38.892956 00000462 UTL FATAL frame:2, taosd() [0x85e027]
08/22 11:32:38.892958 00000462 UTL FATAL frame:3, taosd() [0x86392b]
08/22 11:32:38.892960 00000462 UTL FATAL frame:4, taosd(tsdbNextDataBlock2+0x268) [0x863bf9]
08/22 11:32:38.892962 00000462 UTL FATAL frame:5, taosd() [0xe1b97f]
08/22 11:32:38.892965 00000462 UTL FATAL frame:6, taosd() [0xe1be85]
08/22 11:32:38.892967 00000462 UTL FATAL frame:7, taosd() [0xe1c3b6]
08/22 11:32:38.892969 00000462 UTL FATAL frame:8, taosd(qExecTaskOpt+0x476) [0xe059bd]
08/22 11:32:38.892971 00000462 UTL FATAL frame:9, taosd(qwExecTask+0x172) [0xdf1860]
08/22 11:32:38.892973 00000462 UTL FATAL frame:10, taosd(qwProcessCQuery+0x19d) [0xdf5396]
08/22 11:32:38.892975 00000462 UTL FATAL frame:11, taosd(qWorkerProcessCQueryMsg+0x2cd) [0xdeaa08]
08/22 11:32:38.892977 00000462 UTL FATAL frame:12, taosd(vnodeProcessQueryMsg+0x22c) [0x7ad6e0]
08/22 11:32:38.892979 00000462 UTL FATAL frame:13, taosd() [0x700f0d]
08/22 11:32:38.892980 00000462 UTL FATAL frame:14, taosd() [0x1118fb4]
08/22 11:32:38.892982 00000462 UTL FATAL frame:15, /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f673201a6db]
08/22 11:32:38.892984 00000462 UTL FATAL frame:16, /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f6730ff861f]
taosd: /data/release/TDinternal/community/source/util/src/tlog.c:830: taosAssertDebug: Assertion `0' failed.
08/22 11:32:39.206564 00000462 UTL FATAL crash signal is 6
08/22 11:32:39.206598 00000462 UTL FATAL sender PID:93 cmdline:taosd
08/22 11:32:39.212130 00000462 UTL FATAL obtained 21 stack frames
08/22 11:32:39.212140 00000462 UTL FATAL frame:0, /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7) [0x7f6730f15e87]
08/22 11:32:39.212143 00000462 UTL FATAL frame:1, /lib/x86_64-linux-gnu/libc.so.6(abort+0x141) [0x7f6730f177f1]
08/22 11:32:39.212146 00000462 UTL FATAL frame:2, /lib/x86_64-linux-gnu/libc.so.6(+0x303fa) [0x7f6730f073fa]
08/22 11:32:39.212149 00000462 UTL FATAL frame:3, /lib/x86_64-linux-gnu/libc.so.6(+0x30472) [0x7f6730f07472]
08/22 11:32:39.212152 00000462 UTL FATAL frame:4, taosd(taosAssertDebug+0x2df) [0x110629f]
08/22 11:32:39.212155 00000462 UTL FATAL frame:5, taosd() [0x85d218]
08/22 11:32:39.212164 00000462 UTL FATAL frame:6, taosd() [0x85e027]
08/22 11:32:39.212167 00000462 UTL FATAL frame:7, taosd() [0x86392b]
08/22 11:32:39.212170 00000462 UTL FATAL frame:8, taosd(tsdbNextDataBlock2+0x268) [0x863bf9]
08/22 11:32:39.212173 00000462 UTL FATAL frame:9, taosd() [0xe1b97f]
08/22 11:32:39.212176 00000462 UTL FATAL frame:10, taosd() [0xe1be85]
08/22 11:32:39.212179 00000462 UTL FATAL frame:11, taosd() [0xe1c3b6]
08/22 11:32:39.212182 00000462 UTL FATAL frame:12, taosd(qExecTaskOpt+0x476) [0xe059bd]
08/22 11:32:39.212185 00000462 UTL FATAL frame:13, taosd(qwExecTask+0x172) [0xdf1860]
08/22 11:32:39.212188 00000462 UTL FATAL frame:14, taosd(qwProcessCQuery+0x19d) [0xdf5396]
08/22 11:32:39.212190 00000462 UTL FATAL frame:15, taosd(qWorkerProcessCQueryMsg+0x2cd) [0xdeaa08]
08/22 11:32:39.212193 00000462 UTL FATAL frame:16, taosd(vnodeProcessQueryMsg+0x22c) [0x7ad6e0]
08/22 11:32:39.212196 00000462 UTL FATAL frame:17, taosd() [0x700f0d]
08/22 11:32:39.212199 00000462 UTL FATAL frame:18, taosd() [0x1118fb4]
08/22 11:32:39.212203 00000462 UTL FATAL frame:19, /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f673201a6db]
08/22 11:32:39.212206 00000462 UTL FATAL frame:20, /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f6730ff861f]

**Screenshots**
![image](https://github.com/taosdata/TDengine/assets/1464795/ec9285c6-a88d-4b5d-a94d-2d0b24823582)

![image](https://github.com/taosdata/TDengine/assets/1464795/760ce5d3-479d-489b-bd0c-2f2fb9ea8479)

**Comment by yu285** [comment]
您好，可以加我微信吗a15652223354 

我们具体排查下堆栈信息
