### ISSUE TITLE
telemetry.tdengine.com

### ISSUE THREAD

**Issue by feiyangbeyond** [taosdata/TDengine#22525]
`telemetry.tdengine.com`

发现tdengine server会请求这个域名，如何关闭？

 版本 3.0.7.1

**Comment by sangshuduo** [comment]
https://docs.taosdata.com/reference/config/#telemetryreporting

**Comment by feiyangbeyond** [comment]
> https://docs.taosdata.com/reference/config/#telemetryreporting

谢谢
