### ISSUE TITLE
普通表6000W数据查询慢的问题

### ISSUE THREAD

**Issue by zhuangQingGuang** [taosdata/TDengine#22543]
在server端执行查询普通表6000W数据查询慢
环境：版本3.0.2.4，阿里云4VCPU 30G内存
SQL1：`select count(*) `count` from ghlflog.wy_log where ts >= '2023-08-01 00:00:00' and ts < '2023-08-24 00:00:00' and data_package like '%01 00 00 0E 0B 72 D0 50%' ;`
SQL2：`select count(*) `count` from ghlflog.wy_log;`
查询时间
![涛思count慢](https://github.com/taosdata/TDengine/assets/45782190/af000142-357a-40d5-9f0b-b77deed630fd)
表结构
![表结构](https://github.com/taosdata/TDengine/assets/45782190/df519892-4ce2-4246-8a80-4f8d85e39dd6)

**Comment by laisanshan** [comment]
我是在超级表下建的普通表，达到500W就很卡，执行SQL会经常连接超时。不得已只能再拆解数据，它只能在tag上加索引

**Comment by yu285** [comment]
一般查询慢主要这三个原因：

1.数据被大量相同时间戳的数据覆盖过，导致碎片多，开源版数据导出再导入就行了。（企业版支持在线重组）

2.乱序比较多。

3. 数据库建模优化不够，可以参考：https://www.taosdata.com/tdengine-engineering/21550.html

4.最好在最新版（当前为 3.2.1.0）上测试，确保数据库本身版本处于最优。

**Comment by laisanshan** [comment]
谢谢，稍后我会测试
