### ISSUE TITLE
Schemaless 无模式写入同时向带.和_的表名插入同样的数据，会存在相同时间戳的两条数据

### ISSUE THREAD

**Issue by yuolvv** [taosdata/TDengine#22556]
![image](https://github.com/taosdata/TDengine/assets/5761395/550968e6-2ba3-4e37-a945-ed1308cfb8e0)
无模式写入，插入这两条记录，会存在相同时间戳的两条数据
![image](https://github.com/taosdata/TDengine/assets/5761395/35d7622f-5909-4aaf-baa5-d20aa56ad282)

**Comment by sangshuduo** [comment]
什么版本？

**Comment by yuolvv** [comment]
![image](https://github.com/taosdata/TDengine/assets/5761395/fd8c05ac-b9a6-47bd-b876-0d204a282228)


Version:3.1.0.0

**Comment by yuolvv** [comment]
> 什么版本？

Version:3.1.0.0

![image](https://github.com/taosdata/TDengine/assets/5761395/03c8e51c-a6b1-4213-baa8-bb7549875004)

**Comment by sangshuduo** [comment]
好的，这个问题在修复中，下个版本包含
