### ISSUE TITLE
Crash ! v1.6.5.9 ! While using 'count(*)' query for more than 1000+ sub tables

### ISSUE THREAD

**Issue by sudo168** [taosdata/TDengine#2258]
**Bug Description**
库是2020年6月3号建的。
一个业务，有4种数据表，每种按小时建子表，一小时10张，一天就是 240 * 4，跑了近9天。数据量6w+（仅内部测试）。

count是统计超级表，大概1-2千个子表。

执行：
select count(*) from order_info where ts>='2020-06-01 00:00:00.000000'; // OK

select count(*) from order_info; // taosd服务直接挂掉

**Comment by sudo168** [comment]
是每小时10张子表

**Comment by Aries-Lee1991** [comment]
OK, we'll check it.
