### ISSUE TITLE
vnode-query 写入IO突然增高

### ISSUE THREAD

**Issue by haoshengcai** [taosdata/TDengine#22585]
![image](https://github.com/taosdata/TDengine/assets/49974715/4d13c7b2-cfa2-4134-8a65-47dedd8431f7)

一直正常运行，最近vnode_query突然增高，会把磁盘沾满，但是找不到具体的文件，满了以后磁盘占用会降下来重新写，请问要怎么排查问题？

**Comment by yu285** [comment]
版本号是？

**Comment by haoshengcai** [comment]
版本号为：TDengine-server-3.0.2.6-Linux-x64
