### ISSUE TITLE
时间戳乱序问题

### ISSUE THREAD

**Issue by xxl19792003** [taosdata/TDengine#22587]
**Bug Description**
建立了超表meters，建了3个子表d1001，d1002，d1003。对子表d1001模拟数据，如下：
1 先模拟1000条数据，起始时间为2020-1-1 00:00:00，时间每次递增1分钟，查询数据正常；
2 模拟10万条数据，起始时间还是2020-1-1 00:00:00，时间每次递增1分钟，查询数据异常，时间乱序。

下面给出测试代码：

void insertData(TAOS *taos)
{
    //rows values
    Meters_Row row_val;

    //对应的采集量（指标）列
    TAOS_MULTI_BIND colValues[4];
    //memset(colValues, 0, sizeof(colValues));

   //列属性基本初始化
    initSampleColAttr(TSDB_DATA_TYPE_TIMESTAMP,&colValues[0]);
    initSampleColAttr(TSDB_DATA_TYPE_FLOAT, &colValues[1]);
    initSampleColAttr(TSDB_DATA_TYPE_INT, &colValues[2]);
    initSampleColAttr(TSDB_DATA_TYPE_FLOAT, &colValues[3]);

    //绑定struct的值域
    colValues[0].buffer = &row_val.ts;
    colValues[1].buffer = &row_val.current;
    colValues[2].buffer = &row_val.voltage;
    colValues[3].buffer = &row_val.phase;

    //测试数据
    time_t t_now = String2Time("2020-1-1 00:00:00");
    int cout = 0;
    int k    = 1 /*1000*/;  //k=1000的时候，数据的时间戳有问题了。

    while(k--)
    {
        TAOS_STMT *stmt = taos_stmt_init(taos);

        const char *sql = "INSERT INTO d1001 (ts, current, voltage, phase) VALUES (?, ?, ?, ?)";

        //prepare
        int code = taos_stmt_prepare(stmt, sql, 0);
        checkStmtErrorCode(stmt, code, "failed to execute taos_stmt_prepare");

        for (int i = 0; i < 1000; ++i)
        {
            row_val.ts = t_now + (cout*60*1000);//+1分钟
            row_val.current = RandNumInRange(0.0, 20.0); //随机数
            row_val.voltage = RandNumInRange(210, 380, true);
            row_val.phase = RandNumInRange(0.0, 2.0);

            //bind param
            code = taos_stmt_bind_param(stmt, colValues);
            checkStmtErrorCode(stmt, code, "failed to execute taos_stmt_bind_param");

            //add batch
            if (code == 0)
            {
                cout++;

                code = taos_stmt_add_batch(stmt);
                checkStmtErrorCode(stmt, code, "failed to execute taos_stmt_add_batch");
            }
        }

        //execute
        code = taos_stmt_execute(stmt);
        checkStmtErrorCode(stmt, code, "failed to execute taos_stmt_execute");

        //get affect row num
        int affectedRows = taos_stmt_affected_rows(stmt);
        printf("successfully inserted %d rows\n", affectedRows);

        //close
        taos_stmt_close(stmt);
    }
}

**Environment (please complete the following information):**
 处理器  Intel(R) Core(TM) i5-4210U CPU  2.40 GHz 2内核
RAM     8.00 GB 
硬盘    500G（SSD）
win10+虚拟机
![ok](https://github.com/taosdata/TDengine/assets/10609067/a28ad501-2c9b-45d8-b139-591e7e46f249)
![error](https://github.com/taosdata/TDengine/assets/10609067/a7604101-60ab-49e9-beeb-379591bb1584)

**Comment by sangshuduo** [comment]
TDengine 什么版本？

**Comment by xxl19792003** [comment]
企业版：TDengine-enterprise-server-3.0.7.1-Linux-x64.tar

**Comment by sangshuduo** [comment]
企业版可以和专属支持团队联系解决

**Comment by kobe6666** [comment]
您好 不知道您是否解决这个问题。我比较好奇就复现了一下问题 发现不是程序本身的问题 是测试用例里面  row_val.ts = t_now + (cout*60*1000);//+1分钟 这个表达式当count很大时（大概是39572左右会产生临时右值的溢出） ，会变成一个负数，引起时间戳变小，用一个够大的类型（如unsigned int）先保存好 (cout*60*1000)，然后求和，问题会得到解决

**Comment by kobe6666** [comment]
> 企业版：TDengine-enterprise-server-3.0.7.1-Linux-x64.tar

您好 不知道您是否解决这个问题。我比较好奇就复现了一下问题 发现不是程序本身的问题 是测试用例里面 row_val.ts = t_now + (cout601000);//+1分钟 这个表达式当count很大时（大概是35792左右会产生临时右值的溢出） ，会变成一个负数，引起时间戳变小，用一个够大的类型（如unsigned int）先保存好 (coutX60X1000)，然后求和，问题会得到解决
