### ISSUE TITLE
3.1.0.3 taos.dll resouce leak

### ISSUE THREAD

**Issue by Xnollis** [taosdata/TDengine#22599]
**Bug Description**
在使用taos.dll去操作数据库，当在子线程中调用taos_query()函数时，会造成资源泄漏。进程的句柄数量一直在增加，所占内存也在增加。

**To Reproduce**
1. 编译附件中的test.cpp（需要先重命名为cpp文件，构建时需自行配置lib路径）
2. 在编译好的程序所在的目录创建/编辑一个write_sql.txt文件。在里面写上需要在tdengine执行的sql语句。测试程序会读取此文件。
3. 在程序运行的控制台界面上，不断按下Enter键，即可不断启动新的子线程去调用taos_query().
4. 注意观察任务管理器中本进程的句柄数量
5. 会发现本进程的句柄数量一直在增加，内存也会增加。

**Expected Behavior**
应当在各种线程环境中正常运行，无任何形式的资源泄漏

**Screenshots**
[ScreenShot](https://user-images.githubusercontent.com/29424100/263617184-7f8a4a11-d034-4898-9b5f-ea052862a2da.png)

**Environment (please complete the following information):**
 - OS: Windows 10 x64
 - Memory, CPU, current Disk Space
 - TDengine Version 3.1.0.3

**Additional Context**
1.当taos_query在主线程中被调用时，无资源泄漏问题
2.发生泄漏后，让进程空闲下来，等待很久的时间，泄漏的资源也不会被释放。
[test.txt](https://github.com/taosdata/TDengine/files/12451158/test.txt)

**Comment by Xnollis** [comment]
![image](https://github.com/taosdata/TDengine/assets/29424100/7f8a4a11-d034-4898-9b5f-ea052862a2da)
任务管理器中本进程的句柄数量在不断增加

**Comment by sangshuduo** [comment]
为什么 taos_close() 注释掉了？
另外好奇 3.1.0.0 之后的 Windows 版不再提供服务端，现在这段程序还是连的 127.0.0.1，是说服务端是 3.0 版本？

**Comment by Xnollis** [comment]
> 
因为是要模拟真实的场景，建立好的连接是要复用的。

另外，当前这个bug和这一句也关系不大。可以把`taos`这个变量改成局部变量。 但问题依然存在。

**Comment by sangshuduo** [comment]
客户端和服务端版本需要严格一致。另外不建议在生产环境中使用 Windows 版本。

**Comment by Xnollis** [comment]
>客户端和服务端版本需要严格一致。另外不建议在生产环境中使用 Windows 版本。

从3.0.7.1版本开始就一直有这个问题。
另外我只是在windows上使用客户端taos.dll，无论服务端的是在那个平台上的，版本号都严格的与服务端保持一致。 但是这个问题一直都能复现和存在着。

**Comment by snk8828912** [comment]
也遇到了类似问题
系统：centos linux release 7.9.2009
容器：docker 20.10.17
客户端：TDengine-client-3.1.0.0-Windows-x64.exe
服务端:docker pull tdengine/tdengine:3.1.0.0
驱动： taos-connector-dotnet-3.0 .net 6
调用方式：stmt
业务使用持有conn，压测调用query，内存会一直增长

**Comment by facetosea** [comment]
除了前边说到的 run_test_sql  中 taos_connect 多次执行没有释放会有句柄泄露之外（如果为了效率，connect 想要只进行一次放在循环外面会比较好）
另外， manage_run_test_sql 中每 500 ms 的频率在创建新线程，但线程任务 run_test_sql 在 500ms 内应该完不成，所以线程会越来越多。
write_sql.txt  的内容我不知道，修改上面两个问题，我尝试了简单的查询 sql，没有句柄增加。
@Xnollis  您再试试

**Comment by facetosea** [comment]
> ![image](https://user-images.githubusercontent.com/29424100/263617184-7f8a4a11-d034-4898-9b5f-ea052862a2da.png) 任务管理器中本进程的句柄数量在不断增加

谢谢您的反馈，按照 case 测试发现确实有句柄泄露，而且和子线程调用相关，原因已经确定，我们会尽快修复。
但是目前查看到的泄露点不在query（也许我使用的query 比较简单）, 而在connect ，所以您如果把 connect 放在循环外全局使用的话，也许能解决您碰到的问题。
 
 linux 暂时没有发现 connect  的句柄泄露，句柄初始会增加，少量增加之后就会达到稳定状态。
 
 如果您修改之后， query 依然有句柄泄露，麻烦您提供一下case 中的 sql 语句，我们会继续跟踪。
 
 感谢您的反馈。

**Comment by Xnollis** [comment]
感谢回复！

对于你所提到的，我简单做一下说明：
1."如果把 connect 放在循环外全局使用的话，也许能解决您碰到的问题。" ，在测试代码中我其实已经是这样做了。因为：

`void run_test_sql(int cnt) {
    static TAOS* taos = NULL; // 这里是个static类型的变量，它等价于"connect 放在循环外全局使用"，因为连接只会建立一次
	printf("[%d]run_test_sql thread id is %d..........\n", cnt, GetCurrentThreadId());
	if (taos == NULL) // 对static变量的值做了判断
		taos = taos_connect("127.0.0.1", "root", "taosdata", NULL, 6030); // 连接只会建立一次
        // ..............................
`

2.“麻烦您提供一下case 中的 sql 语句”，在这里用到的语句(即测试代码中用到的write_sql.txt文件的内容)，只有一句：
`insert into db1.tb_test_1 values (now,2.3,5,"ff""ff",3,-3);`

对应的建库建表语句：
`
create  database db1 PRECISION 'ns';
use db1;
CREATE STABLE stb_test_1 ( ts TIMESTAMP,volt1 float,flag int,msg nchar(30),si1 smallint unsigned ,si2 smallint ) tags(idx int);
create table tb_test_1 using stb_test_1 tags(1);
`

3. “query 每执行一次，result 都要释放一次”。 每次query之后，我都已经有调用：taos_free_result()
参考上面的附件“test.txt”里面的源代码

**Comment by yu285** [comment]
请问最新版 3.3.0.3 还有这个情况吗
