### ISSUE TITLE
3.0.7.1 case when issue

### ISSUE THREAD

**Issue by zhyj** [taosdata/TDengine#22598]
**Bug Description**
查询语句： select `value`, case `value` when `value` > 10  then `value` else 0 end from scada_6  
结果集中的数值都大于10，但是case when 语句返回的都是0；
select  unit is not null,  case unit when (unit is not null) then 1  when (unit is null) then 2 else 0 end   from p_0;
这个语句也是一样，第一个字段都是true，case when 语句返回的都是2；

**Screenshots**
![微信图片_20230824155511](https://github.com/taosdata/TDengine/assets/3094307/1f6647e9-371a-423b-a904-e489cdfa4596)

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version 3.0.7.1 

**Additional Context**

**Comment by yu285** [comment]
请问最新版3.3.1.0有这个问题吗，有的话可以加微信a15652223354具体排查
