### ISSUE TITLE
DB error: too many results from vnodes for sort

### ISSUE THREAD

**Issue by tylr2017** [taosdata/TDengine#2260]
**Bug Description**
When the number of records in the table exceeds 100,000, the following statement will report an error：
![image](https://user-images.githubusercontent.com/33024821/84485925-3e33a080-accf-11ea-8ae1-a598cd03b902.png)

**Environment (please complete the following information):**
 - OS: CentOS 7.0
 - TDengine Version 1.6.5.9

**Comment by Aries-Lee1991** [comment]
OK, we'll check it.

**Comment by yihaoDeng** [comment]
> **Bug Description**
> When the number of records in the table exceeds 100,000, the following statement will report an error：
> ![image](https://user-images.githubusercontent.com/33024821/84485925-3e33a080-accf-11ea-8ae1-a598cd03b902.png)
> 
> **Environment (please complete the following information):**
> 
> * OS: CentOS 7.0
> * TDengine Version 1.6.5.9
 
please configure maxNumOfOrderedRes(default is 100000) in the taos.cfg

**Comment by tylr2017** [comment]
> > **Bug Description**
> > When the number of records in the table exceeds 100,000, the following statement will report an error：
> > ![image](https://user-images.githubusercontent.com/33024821/84485925-3e33a080-accf-11ea-8ae1-a598cd03b902.png)
> > **Environment (please complete the following information):**
> > 
> > * OS: CentOS 7.0
> > * TDengine Version 1.6.5.9
> 
> please configure maxNumOfOrderedRes(default is 100000) in the taos.cfg

--------------------------------------------------------------------------------------
That doesn't seem to work, my configuration is as follows:
![image](https://user-images.githubusercontent.com/33024821/84617277-02801d00-af01-11ea-95d5-6143a5e44d27.png)
Also, Taos has been rebooted using command "systemctl restart taosd"

Looking forward to your reply，thanks!

**Comment by Shawshank-Smile** [comment]
Support sorting no more than 10W。

**Comment by Aries-Lee1991** [comment]
@tylr2017 Please attach the log. thanks.

**Comment by tylr2017** [comment]
> @tylr2017 Please attach the log. thanks.

Logs is as follows:
![image](https://user-images.githubusercontent.com/33024821/84640341-20af4280-af2c-11ea-8001-4adcf1198e90.png)

**Comment by Aries-Lee1991** [comment]
> > @tylr2017 Please attach the log. thanks.
> 
> Logs is as follows:
> ![image](https://user-images.githubusercontent.com/33024821/84640341-20af4280-af2c-11ea-8001-4adcf1198e90.png)

As  @Shawshank-Smile  said, support sorting no more than 10W.
