### ISSUE TITLE
upgrade version 1.6.6.0  from version 1.6.5.6  start time  create the following  bug.    

### ISSUE THREAD

**Issue by march3008** [taosdata/TDengine#2261]
[New Thread 0x7ffe932fd700 (LWP 107243)]
06/12 17:36:02.131935 107178 7ffff7fdd740 DND TDengine is initialized successfully
06/12 17:36:02.132358 107178 7ffe932fd700 HTP http service init success at ip:0.0.0.0:6020
06/12 17:36:02.145661 107178 7fffe65a7700 MON starting to initialize monitor service ..
06/12 17:36:02.146267 107178 7fffe75a9700 MND user:monitor login from 192.168.1.234, code:0
06/12 17:36:02.147104 107178 7ffff05bb700 ERROR DND qmsg:0x7ffe700008f4 illegal value of aggTimeInterval -72034504293744640

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff05bb700 (LWP 107183)]
__GI___libc_free (mem=0xcc7a000000000000) at malloc.c:2941
2941   if (chunk_is_mmapped(p))                       /* release mmapped memory. */
(gdb) bt
#0  __GI___libc_free (mem=0xcc7a000000000000) at malloc.c:2941
#1  0x000000000042da2d in vnodeProcessQueryRequest (pMsg=0x7ffe700008f4 "\027", msgLen=31436, pObj=0x40ffb30) at /home/ubuntu/version_release_workroom/release_workspace/TDinternal/community/src/system/detail/src/vnodeShell.c:393
#2  0x000000000042c787 in vnodeProcessMsgFromShell (msg=0x7ffe700008cc "\001", ahandle=0x0, thandle=0x7ffe94ba40f0)
    at /home/ubuntu/version_release_workroom/release_workspace/TDinternal/community/src/system/detail/src/vnodeShell.c:105
#3  0x000000000050cd0a in taosProcessSchedMsg (pMsg=0x7ffff05baed0) at /home/ubuntu/version_release_workroom/release_workspace/TDinternal/community/src/rpc/src/trpc.c:1469
#4  0x0000000000540d21 in taosProcessSchedQueue (param=0x7e4100) at /home/ubuntu/version_release_workroom/release_workspace/TDinternal/community/src/util/src/tsched.c:144
#5  0x00007ffff7bc6e65 in start_thread (arg=0x7ffff05bb700) at pthread_create.c:307
#6  0x00007ffff73e588d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) quit
A debugging session is active.

**Comment by Aries-Lee1991** [comment]
OK, we'll check it.

**Comment by plum-lihui** [comment]
hello！
Please  send the core file to us for analysis。
huili@taosdata.com

Thanks

**Comment by march3008** [comment]
sorry&nbsp; i&nbsp; have del it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"huili"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月15日(星期一) 中午1:15
收件人:&nbsp;"taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送:&nbsp;"起点/love"<271646801@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [taosdata/TDengine] upgrade version 1.6.6.0  from version 1.6.5.6  start time  create the following  bug.     (#2261)





 
hello！
 Please  send the core file to us for analysis。
 huili@taosdata.com
 
Thanks

**Comment by plum-lihui** [comment]
If the same problem occurs again, please send this information to us for analysis. 
Thank you very much！

**Comment by Aries-Lee1991** [comment]
The is issue is closed.
If the same problem occurrs again, please reopen the issue.
