### ISSUE TITLE
Schemaless 无模式写入 指定的字表名称 不能包含大写字母

### ISSUE THREAD

**Issue by yuolvv** [taosdata/TDengine#22612]
版本：3.1.0.3

 无模式写入 指定的子表名称 不能包含大写字母

![image](https://github.com/taosdata/TDengine/assets/5761395/d31187dd-d77a-49ef-b8a1-ea9e1294667b)
子表名称包含大写字母，插入数据，查询不出来
![image](https://github.com/taosdata/TDengine/assets/5761395/e74c4ec1-cdcd-4d97-baaa-db9cdb8dc276)

![image](https://github.com/taosdata/TDengine/assets/5761395/beb48648-a040-4ae8-87b4-e779aef203d7)
子表名称不包含大写字母，插入数据，正常查询
![image](https://github.com/taosdata/TDengine/assets/5761395/cf29e673-7bb9-42c9-a872-85707a0cd882)

**Comment by sangshuduo** [comment]
表名加 \`\`

**Comment by yuolvv** [comment]
> 表名加 ``


加 ``
![image](https://github.com/taosdata/TDengine/assets/5761395/cfdcc9a4-7ea0-4ae8-83ec-7f31c509b48e)

结果：
![image](https://github.com/taosdata/TDengine/assets/5761395/676f37d3-16f8-4d69-bf5a-d794f266f204)

**Comment by sangshuduo** [comment]
这是什么软件？

**Comment by yuolvv** [comment]
> 这是什么软件？

TDengineGUI

用命令taos查询，如下图：
![image](https://github.com/taosdata/TDengine/assets/5761395/a1eff6ef-79a1-4ffe-9bd9-4048a1be1d69)

**Comment by wangmm0220** [comment]
tbname=aBcd

然后 shell里查询  select * from `aBcd`就可以。

TDengineGUI  工具里应该是没有加反引号的原因

**Comment by hehepeng** [comment]
你这个无模式写入，表名是拼接sql的时候按规则创建的，还是tdengine默认的无模式写入自动生成的子表名。我遇到一个问题，使用InfluxDB 协议，配置taos.cfg的smlAutoChildTableNameDelimiter,无法生成自定义表名

**Comment by Witten1997** [comment]
> 你这个无模式写入，表名是拼接sql的时候按规则创建的，还是tdengine默认的无模式写入自动生成的子表名。我遇到一个问题，使用InfluxDB 协议，配置taos.cfg的smlAutoChildTableNameDelimiter,无法生成自定义表名

你解决了吗，我也遇到这个问题
