### ISSUE TITLE
Using "order by" returns only one piece of data

### ISSUE THREAD

**Issue by AidenZhang-cn** [taosdata/TDengine#22624]
**Bug Description**
Using "order by" returns only one piece of data.

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by sangshuduo** [comment]
什么版本？什么平台？如何复现？
