### ISSUE TITLE
服务器重启后，docker 重启失败

### ISSUE THREAD

**Issue by A95monster** [taosdata/TDengine#22636]
日志：
08/29 11:51:16.774225 00000061 DND start to init dnode env
08/29 11:51:16.774287 00000061 DND succceed to read dnode file /var/lib/taos//dnode/dnode.json
08/29 11:51:16.774300 00000061 DND ERROR dnode:1, localEp 943a0e861c2e:6030 different from 6f87c4c52f08:6030
08/29 11:51:16.774304 00000061 DND ERROR localEp 943a0e861c2e:6030 different with /var/lib/taos//dnode/dnode.json and need reconfigured
08/29 11:51:16.774347 00000061 DND ERROR failed to read file since Invalid config option
08/29 11:51:16.774355 00000061 DND ERROR failed to create dnode since Invalid config option
08/29 11:51:16.774357 00000061 DND ERROR failed to init dnode since Invalid config option
sysctl: setting key "kernel.core_pattern": Read-only file system
08/29 11:51:23.681437 00000038 taos_ADAPTER info "start server:00000038" model=main
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /debug/pprof/             --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/cmdline      --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/profile      --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)
[GIN-debug] POST   /debug/pprof/symbol       --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/symbol       --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/trace        --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/allocs       --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/block        --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/goroutine    --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/heap         --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/mutex        --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/threadcreate --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
[GIN-debug] GET    /metrics                  --> github.com/gin-gonic/gin.WrapH.func1 (5 handlers)
[GIN-debug] GET    /-/ping                   --> github.com/taosdata/taosadapter/v3/controller/ping.Controller.Init.func1 (5 handlers)
[GIN-debug] POST   /rest/sql                 --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).sql-fm (7 handlers)
[GIN-debug] POST   /rest/sql/:db             --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).sql-fm (7 handlers)
[GIN-debug] POST   /rest/sql/:db/vgid        --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).tableVgID-fm (7 handlers)
[GIN-debug] GET    /rest/login/:user/:password --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).des-fm (6 handlers)
[GIN-debug] GET    /rest/ws                  --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).ws-fm (6 handlers)
[GIN-debug] GET    /rest/stmt                --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).stmt-fm (6 handlers)
[GIN-debug] GET    /rest/tmq                 --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).tmq-fm (6 handlers)
[GIN-debug] POST   /rest/upload              --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).upload-fm (7 handlers)
[GIN-debug] GET    /rest/schemaless          --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).schemalessWs-fm (6 handlers)
[GIN-debug] GET    /genauth/:user/:password/:key --> github.com/taosdata/taosadapter/v3/plugin.RegisterGenerateAuth.func1 (5 handlers)
08/29 11:51:23.681659 00000038 taos_ADAPTER info "init plugin opentsdb_telnet/v1" model=plugin
08/29 11:51:23.682516 00000038 taos_ADAPTER info "opentsdb_telnet disabled" model=opentsdb_telnet
08/29 11:51:23.682523 00000038 taos_ADAPTER info "init plugin prometheus/v1" model=plugin
[GIN-debug] POST   /prometheus/v1/remote_read/:db --> github.com/taosdata/taosadapter/v3/plugin/prometheus.(*Plugin).Read-fm (7 handlers)
[GIN-debug] POST   /prometheus/v1/remote_write/:db --> github.com/taosdata/taosadapter/v3/plugin/prometheus.(*Plugin).Write-fm (7 handlers)
08/29 11:51:23.682633 00000038 taos_ADAPTER info "init plugin statsd/v1" model=plugin
08/29 11:51:23.683870 00000038 taos_ADAPTER info "statsd disabled" model=statsd
08/29 11:51:23.683878 00000038 taos_ADAPTER info "init plugin collectd/v1" model=plugin
08/29 11:51:23.684413 00000038 taos_ADAPTER info "collectd disabled" model=collectd
08/29 11:51:23.684419 00000038 taos_ADAPTER info "init plugin influxdb/v1" model=plugin
[GIN-debug] POST   /influxdb/v1/write        --> github.com/taosdata/taosadapter/v3/plugin/influxdb.(*Influxdb).write-fm (7 handlers)
08/29 11:51:23.684520 00000038 taos_ADAPTER info "init plugin node_exporter/v1" model=plugin
08/29 11:51:23.685635 00000038 taos_ADAPTER info "node_exporter disabled" model=NodeExporter
08/29 11:51:23.685641 00000038 taos_ADAPTER info "init plugin opentsdb/v1" model=plugin
[GIN-debug] POST   /opentsdb/v1/put/json/:db --> github.com/taosdata/taosadapter/v3/plugin/opentsdb.(*Plugin).insertJson-fm (7 handlers)
[GIN-debug] POST   /opentsdb/v1/put/telnet/:db --> github.com/taosdata/taosadapter/v3/plugin/opentsdb.(*Plugin).insertTelnet-fm (7 handlers)
08/29 11:51:23.686079 00000038 taos_ADAPTER info "all plugin init finish" model=plugin
08/29 11:51:23.686090 00000038 taos_ADAPTER info "all plugin start finish" model=plugin
08/29 11:51:23.686136 00000038 taos_ADAPTER info "Running in terminal." model=main
08/29 11:51:23.686587 00000038 taos_ADAPTER info "server on : 6041" model=main
run TDengine with single node.
08/29 11:51:24.131265 00000061 UTL apoll url not load
08/29 11:51:24.131292 00000061 UTL load from cfg file /etc/taos//taos.cfg success
08/29 11:51:24.131300 00000061 UTL env file:.env not load
08/29 11:51:24.131308 00000061 UTL load from env variables cfg success
08/29 11:51:24.131437 00000061 UTL open new log file ......
08/29 11:51:24.131431 00000061 DND startup path:/root args:taosd
08/29 11:51:24.131675 00000061 UTL apoll url not load
08/29 11:51:24.131705 00000061 UTL load from cfg file /etc/taos//taos.cfg success
08/29 11:51:24.131711 00000061 UTL env file:.env not load
08/29 11:51:24.131715 00000061 UTL load from env variables cfg success
08/29 11:51:24.131803 00000061 UTL                      global config
08/29 11:51:24.131806 00000061 UTL =================================================================
08/29 11:51:24.131808 00000061 UTL default      firstEp                  943a0e861c2e:6030
08/29 11:51:24.131810 00000061 UTL default      secondEp                 943a0e861c2e:6030
08/29 11:51:24.131812 00000061 UTL default      fqdn                     943a0e861c2e
08/29 11:51:24.131814 00000061 UTL default      serverPort               6030
08/29 11:51:24.131815 00000061 UTL default      tempDir                  /tmp/
08/29 11:51:24.131817 00000061 UTL default      minimalTmpDirGB          1.00
08/29 11:51:24.131824 00000061 UTL default      shellActivityTimer       3
08/29 11:51:24.131841 00000061 UTL default      compressMsgSize          -1
08/29 11:51:24.131844 00000061 UTL default      compressColData          -1
08/29 11:51:24.131846 00000061 UTL default      queryPolicy              1
08/29 11:51:24.131848 00000061 UTL default      enableQueryHb            0
08/29 11:51:24.131851 00000061 UTL default      enableScience            0
08/29 11:51:24.131853 00000061 UTL default      querySmaOptimize         0
08/29 11:51:24.131855 00000061 UTL default      queryPlannerTrace        0
08/29 11:51:24.131858 00000061 UTL default      queryNodeChunkSize       32768
08/29 11:51:24.131860 00000061 UTL default      queryUseNodeAllocator    1
08/29 11:51:24.131863 00000061 UTL default      keepColumnName           0
08/29 11:51:24.131865 00000061 UTL default      smlChildTableName        
08/29 11:51:24.131868 00000061 UTL default      smlTagName               _tag_null
08/29 11:51:24.131874 00000061 UTL default      maxMemUsedByInsert       1024
08/29 11:51:24.131876 00000061 UTL default      maxRetryWaitTime         10000
08/29 11:51:24.131878 00000061 UTL default      useAdapter               0
08/29 11:51:24.131880 00000061 UTL default      crashReporting           1
08/29 11:51:24.131882 00000061 UTL default      queryMaxConcurrentTable  200
08/29 11:51:24.131885 00000061 UTL default      numOfRpcThreads          2
08/29 11:51:24.131887 00000061 UTL default      numOfRpcSessions         10000
08/29 11:51:24.131889 00000061 UTL default      timeToGetAvailableConn   500000
08/29 11:51:24.131892 00000061 UTL default      numOfTaskQueueThreads    4
08/29 11:51:24.131894 00000061 UTL default      dataDir                  /var/lib/taos/
08/29 11:51:24.131897 00000061 UTL default      minimalDataDirGB         2.00
08/29 11:51:24.131899 00000061 UTL default      supportVnodes            8
08/29 11:51:24.131902 00000061 UTL default      maxShellConns            50000
08/29 11:51:24.131905 00000061 UTL default      statusInterval           1
08/29 11:51:24.131907 00000061 UTL default      minSlidingTime           10
08/29 11:51:24.131915 00000061 UTL default      minIntervalTime          1
08/29 11:51:24.131918 00000061 UTL default      maxNumOfDistinctRes      10000000
08/29 11:51:24.131920 00000061 UTL default      countAlwaysReturnValue   1
08/29 11:51:24.131926 00000061 UTL default      queryBufferSize          -1
08/29 11:51:24.131928 00000061 UTL default      printAuth                0
08/29 11:51:24.131930 00000061 UTL default      queryRspPolicy           0
08/29 11:51:24.131932 00000061 UTL default      numOfRpcThreads          2
08/29 11:51:24.131934 00000061 UTL default      numOfRpcSessions         10000
08/29 11:51:24.131937 00000061 UTL default      timeToGetAvailableConn   10000
08/29 11:51:24.131939 00000061 UTL default      numOfCommitThreads       2
08/29 11:51:24.131941 00000061 UTL default      numOfMnodeReadThreads    1
08/29 11:51:24.131944 00000061 UTL default      numOfVnodeQueryThreads   8
08/29 11:51:24.131946 00000061 UTL default      ratioOfVnodeStreamThrea  1.00
08/29 11:51:24.131949 00000061 UTL default      numOfVnodeFetchThreads   4
08/29 11:51:24.131951 00000061 UTL default      numOfVnodeRsmaThreads    4
08/29 11:51:24.131953 00000061 UTL default      numOfQnodeQueryThreads   8
08/29 11:51:24.131956 00000061 UTL default      numOfSnodeSharedThreads  2
08/29 11:51:24.131958 00000061 UTL default      numOfSnodeUniqueThreads  2
08/29 11:51:24.131960 00000061 UTL default      rpcQueueMemoryAllowed    1650466406
08/29 11:51:24.131963 00000061 UTL default      syncElectInterval        25000
08/29 11:51:24.131965 00000061 UTL default      syncHeartbeatInterval    1000
08/29 11:51:24.131968 00000061 UTL default      syncHeartbeatTimeout     20000
08/29 11:51:24.131970 00000061 UTL default      vndCommitMaxInterval     600000
08/29 11:51:24.131972 00000061 UTL default      mndSdbWriteDelta         200
08/29 11:51:24.131975 00000061 UTL default      mndLogRetention          2000
08/29 11:51:24.131977 00000061 UTL default      monitor                  1
08/29 11:51:24.131979 00000061 UTL default      monitorInterval          30
08/29 11:51:24.131981 00000061 UTL default      monitorFqdn              
08/29 11:51:24.131984 00000061 UTL default      monitorPort              6043
08/29 11:51:24.131986 00000061 UTL default      monitorMaxLogs           100
08/29 11:51:24.131992 00000061 UTL default      monitorComp              0
08/29 11:51:24.131995 00000061 UTL default      crashReporting           1
08/29 11:51:24.131997 00000061 UTL default      telemetryReporting       1
08/29 11:51:24.131999 00000061 UTL default      telemetryInterval        43200
08/29 11:51:24.132001 00000061 UTL default      telemetryServer          telemetry.taosdata.com
08/29 11:51:24.132004 00000061 UTL default      telemetryPort            80
08/29 11:51:24.132006 00000061 UTL default      transPullupInterval      2
08/29 11:51:24.132009 00000061 UTL default      mqRebalanceInterval      2
08/29 11:51:24.132012 00000061 UTL default      ttlUnit                  86400
08/29 11:51:24.132015 00000061 UTL default      ttlPushInterval          86400
08/29 11:51:24.132017 00000061 UTL default      uptimeInterval           300
08/29 11:51:24.132019 00000061 UTL default      queryRsmaTolerance       1000
08/29 11:51:24.132021 00000061 UTL default      walFsyncDataSizeLimit    104857600
08/29 11:51:24.132024 00000061 UTL default      udf                      1
08/29 11:51:24.132026 00000061 UTL default      udfdResFuncs             
08/29 11:51:24.132029 00000061 UTL default      udfdLdLibPath            
08/29 11:51:24.132031 00000061 UTL default      disableStream            0
08/29 11:51:24.132033 00000061 UTL default      cacheLazyLoadThreshold   500
08/29 11:51:24.132036 00000061 UTL default      configDir                /etc/taos/
08/29 11:51:24.132038 00000061 UTL default      scriptDir                /etc/taos/
08/29 11:51:24.132040 00000061 UTL default      logDir                   /var/log/taos/
08/29 11:51:24.132042 00000061 UTL default      minimalLogDirGB          1.00
08/29 11:51:24.132045 00000061 UTL default      numOfLogLines            10000000
08/29 11:51:24.132047 00000061 UTL default      asyncLog                 1
08/29 11:51:24.132049 00000061 UTL default      logKeepDays              0
08/29 11:51:24.132052 00000061 UTL default      debugFlag                0
08/29 11:51:24.132054 00000061 UTL default      simDebugFlag             143
08/29 11:51:24.132056 00000061 UTL default      tmrDebugFlag             131
08/29 11:51:24.132058 00000061 UTL default      uDebugFlag               131
08/29 11:51:24.132061 00000061 UTL default      rpcDebugFlag             131
08/29 11:51:24.132063 00000061 UTL default      jniDebugFlag             131
08/29 11:51:24.132065 00000061 UTL default      qDebugFlag               131
08/29 11:51:24.132067 00000061 UTL default      cDebugFlag               131
08/29 11:51:24.132070 00000061 UTL default      dDebugFlag               131
08/29 11:51:24.132072 00000061 UTL default      vDebugFlag               131
08/29 11:51:24.132074 00000061 UTL default      mDebugFlag               131
08/29 11:51:24.132076 00000061 UTL default      wDebugFlag               131
08/29 11:51:24.132079 00000061 UTL default      sDebugFlag               131
08/29 11:51:24.132081 00000061 UTL default      tsdbDebugFlag            131
08/29 11:51:24.132083 00000061 UTL default      tqDebugFlag              131
08/29 11:51:24.132086 00000061 UTL default      fsDebugFlag              131
08/29 11:51:24.132088 00000061 UTL default      udfDebugFlag             131
08/29 11:51:24.132090 00000061 UTL default      smaDebugFlag             131
08/29 11:51:24.132092 00000061 UTL default      idxDebugFlag             131
08/29 11:51:24.132095 00000061 UTL default      tdbDebugFlag             131
08/29 11:51:24.132097 00000061 UTL default      metaDebugFlag            131
08/29 11:51:24.132099 00000061 UTL default      timezone                 Etc/UTC (UTC, +0000)
08/29 11:51:24.132102 00000061 UTL default      locale                   en_US.UTF-8
08/29 11:51:24.132104 00000061 UTL default      charset                  UTF-8
08/29 11:51:24.132107 00000061 UTL default      assert                   1
08/29 11:51:24.132109 00000061 UTL default      enableCoreFile           1
08/29 11:51:24.132111 00000061 UTL default      numOfCores               4.00
08/29 11:51:24.132114 00000061 UTL default      SSE42                    0
08/29 11:51:24.132116 00000061 UTL default      AVX                      0
08/29 11:51:24.132119 00000061 UTL default      AVX2                     0
08/29 11:51:24.132121 00000061 UTL default      FMA                      0
08/29 11:51:24.132123 00000061 UTL default      SIMD-builtins            0
08/29 11:51:24.132125 00000061 UTL default      tagFilterCache           0
08/29 11:51:24.132128 00000061 UTL default      openMax                  1048576
08/29 11:51:24.132130 00000061 UTL default      streamMax                16
08/29 11:51:24.132133 00000061 UTL default      pageSizeKB               4
08/29 11:51:24.132139 00000061 UTL default      totalMemoryKB            16117836
08/29 11:51:24.132142 00000061 UTL default      os sysname               Linux
08/29 11:51:24.132144 00000061 UTL default      os nodename              943a0e861c2e
08/29 11:51:24.132146 00000061 UTL default      os release               5.4.0-132-generic
08/29 11:51:24.132148 00000061 UTL default      os version               #148-Ubuntu SMP Mon Oct 17 16:02:06 UTC 2022
08/29 11:51:24.132151 00000061 UTL default      os machine               x86_64
08/29 11:51:24.132156 00000061 UTL default      version                  3.0.4.0
08/29 11:51:24.132159 00000061 UTL default      compatible_version       3.0.0.0
08/29 11:51:24.132161 00000061 UTL default      gitinfo                  b186e0bc1bc20df034a1a071491a6558e9c028fd
08/29 11:51:24.132163 00000061 UTL default      buildinfo                Built at 2023-04-14 16:39
08/29 11:51:24.132171 00000061 UTL =================================================================
08/29 11:51:24.133325 00000061 DND start to init dnode env
08/29 11:51:24.133393 00000061 DND succceed to read dnode file /var/lib/taos//dnode/dnode.json
08/29 11:51:24.133405 00000061 DND ERROR dnode:1, localEp 943a0e861c2e:6030 different from 6f87c4c52f08:6030
08/29 11:51:24.133410 00000061 DND ERROR localEp 943a0e861c2e:6030 different with /var/lib/taos//dnode/dnode.json and need reconfigured
08/29 11:51:24.133455 00000061 DND ERROR failed to read file since Invalid config option
08/29 11:51:24.133462 00000061 DND ERROR failed to create dnode since Invalid config option
08/29 11:51:24.133464 00000061 DND ERROR failed to init dnode since Invalid config option

dnode.json：
{
  "dnodeId": 1,
  "dnodeVer": "2",
  "clusterId": "7699029899745775489",
  "dropped": 0,
  "dnodes": [{
    "id": 1,
    "fqdn": "172.22.xxx.xx",
    "port": 6030,
    "isMnode": 1
  }]
}
可以ping通 172.22.xxx.xx
  
docker run -d --name tdengine --restart=always -p 6030:6030 -p 6041:6041 -p 6043-6049:6043-6049 -p 6043-6049:6043-6049/udp -v /wahle/v-TDengine/taos/log:/var/log/taos -v /whale/v-TDengine/taos/data:/var/lib/taos tdengine/tdengine

这个我改怎么处理，我的数据还能恢复么？

**Comment by sangshuduo** [comment]
docker 命令行启动时指定 hostname 和原来的一样试试
--hostname 943a0e861c2e

**Comment by jianchengwang** [comment]
这个算bug吗，后续会修复吗，还是只能指定hostname解决，
