### ISSUE TITLE
TDengine是否支持旧数据重排

### ISSUE THREAD

**Issue by cabinary** [taosdata/TDengine#22671]
这边的有个业务是按时间戳顺序的，但是上游的服务会有不确定性的网络波动导致数据丢失，为了保证时效性，其他数据不能等待这批因为网络波动丢失的数据补全，所以可能会有一段时间缺失数据。而后面肯定会补全，所以涉及到有一定比率的乱序插入问题（这边的检测情况是约占总数据的5%）。
而数据均是时间顺序的，补全的情况不会超过1小时，也就是说一小时之后，历史的数据已经可以确定是完全的了，可以重排了。
但是在未来，由于这样的数据错位数量越来越多，是否会产生可观的性能损失？

**Comment by sangshuduo** [comment]
会影响性能，可以考虑选用企业版，支持 compact 数据功能

**Comment by zuodengchao** [comment]
> 会影响性能，可以考虑选用企业版，支持 compact 数据功能

compact 有计划进行开源吗？

**Comment by sangshuduo** [comment]
> > 会影响性能，可以考虑选用企业版，支持 compact 数据功能
> 
> compact 有计划进行开源吗？

目前没有计划开源

**Comment by zuodengchao** [comment]
> > > 会影响性能，可以考虑选用企业版，支持 compact 数据功能
> > 
> > 
> > compact 有计划进行开源吗？
> 
> 目前没有计划开源

有没有可以缓解的方案呢？以及如何检测有乱序的数据呢？
