### ISSUE TITLE
build TDEngine3.0 error

### ISSUE THREAD

**Issue by changshun-shi** [taosdata/TDengine#22679]
**Bug Description**
Compile Failed in the latest MacOS version with clang 16.0.0.
It's shown as `a function declaration without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]`
I find solution in this issue(https://github.com/madler/zlib/issues/633), it has been resolved in newer version(Maybe update your fork one is perfectly right). And then I update the `zlib_CMakeLists.txt.in`, set `GIT_REPOSITORY=https://github.com/madler/zlib.git` and `GIT_TAG=v1.3`, the zlib can be compiled successfully. 
However, when I fix it, I find a new one, which is as follows: 
```
TDengine/source/libs/executor/src/aggregateoperator.c:482:84: error: passing arguments to 'terrstr' without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
    qError("Init stream agg supporter failed since %s, key:%s, tempDir:%s", terrstr(code), pKey, tsTempDir);
                                                                                   ^
```
emmm, Maybe it's a bug. Please fix.
thank you

**To Reproduce**
Just build it with followed Environment

**Screenshots**
![image](https://github.com/taosdata/TDengine/assets/41324444/4726e5d7-c2af-44b1-a369-65ccba911bc1)
![image](https://github.com/taosdata/TDengine/assets/41324444/ecc2e44b-9086-49c0-bd2a-41a83ea08c19)

**Environment (please complete the following information):**
 - OS: MacOS Ventura (13.5) M2
 - TDengine Version [e.g.  3.0]
 - clang: Homebrew clang version 16.0.0 Target: x86_64-apple-darwin22.6.0

**Additional Context**
no

**Comment by zyyang-taosdata** [comment]
![image](https://github.com/taosdata/TDengine/assets/69311263/da40fb31-0ac9-410a-83b1-3c10bf567b41)

**Comment by changshun-shi** [comment]
Maybe a patch for code fix is better.
