### ISSUE TITLE
集群主节点offline,重启失败

### ISSUE THREAD

**Issue by zxloading** [taosdata/TDengine#22670]
日常使用中，发现主节点：Unable to establish connection
可以ping fqdn，查看taosd状态，发现未运行，systemctl restart taosd失败
日志信息：
 taosd.service - TDengine server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Thu 2023-08-31 14:18:36 CST; 44min ago
  Process: 10649 ExecStart=/usr/bin/taosd (code=exited, status=255)
  Process: 10642 ExecStartPre=/usr/local/taos/bin/startPre.sh (code=exited, status=0/SUCCESS)
 Main PID: 10649 (code=exited, status=255)

systemd[1]: Unit taosd.service entered failed state.
systemd[1]: taosd.service failed.
systemd[1]: taosd.service holdoff time over, scheduling restart.
systemd[1]: Stopped TDengine server service.
systemd[1]: start request repeated too quickly for taosd.service
systemd[1]: Failed to start TDengine server service.
systemd[1]: Unit taosd.service entered failed state.
systemd[1]: taosd.service failed.
这个是什么原因导致失败，需要修改什么配置

**Comment by sangshuduo** [comment]
执行 sudo taosd 看看输出什么？

**Comment by zxloading** [comment]
显示磁盘5.2G不够用，至少需要10G，但是数据和日志存储位置都已修改到其他路径，对应路径的磁盘大小是够用的
![image](https://github.com/taosdata/TDengine/assets/32754990/824a2527-0d39-4c27-b45d-d70e890d8991)
![image](https://github.com/taosdata/TDengine/assets/32754990/08b1b9cc-aedc-4c83-8660-dce7d095ef6d)
![image](https://github.com/taosdata/TDengine/assets/32754990/f08fcc60-049e-4117-b55e-966aa93380e6)

**Comment by zxloading** [comment]
重启为什么需要至少10G，这个是配置里面设置的，还是tdengine根据实际情况统计的

**Comment by zxloading** [comment]
![image](https://github.com/taosdata/TDengine/assets/32754990/dea4b75a-fb51-4adf-993d-31bfb3b5c656)
![image](https://github.com/taosdata/TDengine/assets/32754990/aeb8a2ef-edb8-4a11-9dd0-ac364fed99b9)
![image](https://github.com/taosdata/TDengine/assets/32754990/74fe80ec-f420-4900-94ef-345cd23f8855)
![image](https://github.com/taosdata/TDengine/assets/32754990/d868dd81-ae30-451c-bc08-aada5564b08b)
显示资源不足，但是data和log存放路径已修改，对应路径磁盘够用，那重启为什么还是必须10G，这个是配置设置的，还是服务重启时，实际计算而来的

**Comment by sangshuduo** [comment]
minimalLogDirGB   10.00 这个配置要求最小存储 log 空间为 10G

**Comment by zxloading** [comment]
log存储在/mnt路径下，存储空间还剩900G，为什么会显示不够呢

**Comment by sangshuduo** [comment]
什么版本？

**Comment by zxloading** [comment]
3.0.1.4

**Comment by zxloading** [comment]
日志路径修改，在对应存储空间够用的情况下，修改minimalLogDirGB<5G，这样会有问题嘛

**Comment by zxloading** [comment]
修改配置后，重启taosd成功，sudo taosd,最终显示 DND ERROR failed to lock file:/mnt/data/taos/.running since Resource temporarily unavailable, retryTimes:1，这个又是什么原因，内存够，文件只有tdengine在使用，为什么会报这个错误，但是时序库可以正常连接，这个错误会导致什么问题，怎么处理呢

**Comment by yu285** [comment]
> 修改配置后，重启taosd成功，sudo taosd,最终显示 DND ERROR failed to lock file:/mnt/data/taos/.running since Resource temporarily unavailable, retryTimes:1，这个又是什么原因，内存够，文件只有tdengine在使用，为什么会报这个错误，但是时序库可以正常连接，这个错误会导致什么问题，怎么处理呢

这说明你的数据库已经跑起来了，这是重复启动的正常报错。

如果还有疑问可以添加微信：a15652223354 做具体排查
