### ISSUE TITLE
Initialize user, password and database with docker run

### ISSUE THREAD

**Issue by houluy** [taosdata/TDengine#22694]
How to initialize user, password and database when running TDEngine with docker, like in MySQL, we can set environment variables to create user, password and database:

MYSQL_USER, MYSQL_PASS, MYSQL_DATABASE.

Are there similary variables in TDEngine? Or we need to create user manually after starting the container.

**Comment by yu285** [comment]
sorry ,  It can't be configured , we need to create user manually after starting the container.
