### ISSUE TITLE
systemctl start taosd 时启动不了

### ISSUE THREAD

**Issue by ymk1933230135** [taosdata/TDengine#22703]
ERROR:systemctl:Unit taosd.service not found.

**Comment by ymk1933230135** [comment]
使用的是wsl安装的ubuntu20.04;
1.通过apt安装，安装失败；
2.通过DEB安装，安装后出现上述无法启动的现象；
3.卸载后通过tar.gz安装，可以正常启动

**Comment by ymk1933230135** [comment]
使用的是wsl安装的ubuntu20.04;
1.通过apt安装，安装失败；（通过apt方式安装提示：Warning: apt-key output should not be parsed (stdout is not a terminal)）
2.通过DEB安装，安装后出现上述无法启动的现象；（ERROR:systemctl:Unit taosd.service not found.）
3.卸载后通过tar.gz安装，可以正常启动（ok）

**Comment by yu285** [comment]
具体版本号是？可以加微信 a15652223354 做具体排查。
