### ISSUE TITLE
taosdump 导入错误

### ISSUE THREAD

**Issue by ly0928** [taosdata/TDengine#22709]
ERROR: getTableDesNative() LN2859, failed to run command <DESCRIBE xx23015h.`s_tvoc`>. code: 0x80000020, reason: some vnode/qnode/mnode(s) out of service
ERROR: getTableDesNative() LN2859, failed to run command <DESCRIBE xx23015h.`s_ms_308`>. code: 0x80000020, reason: some vnode/qnode/mnode(s) out of service
ERROR: getTableDesNative() LN2859, failed to run command <DESCRIBE xx23015h.`s_tsp`>. code: 0x80000020, reason: some vnode/qnode/mnode(s) out of service
ERROR: dumpInAvroTbTagsImpl() LN5863 Unknown type: 8
ERROR: getTableDesNative() LN2859, failed to run command <DESCRIBE xx23015h.`s_ms_2001`>. code: 0x80000020, reason: some vnode/qnode/mnode(s) out of service
ERROR: dumpInAvroTbTagsImpl() LN5863 Unknown type: 8
ERROR: dumpInAvroTbTagsImpl() LN5863 Unknown type: 8
ERROR: dumpInAvroTbTagsImpl() LN5863 Unknown type: 8
ERROR: dumpInAvroTbTagsImpl() LN5863 Unknown type: 8
ERROR: dumpInAvroTbTagsImpl() LN5863 Unknown type: 8
WARN: dumpInAvroTbTagsImpl() LN5895 taos_query() failed! sqlstr: CREATE TABLE xx23015h.`z001` USING xx23015h.`s_tvoc` TAGS), reason: syntax error near ")"
ERROR: dumpInAvroTbTagsImpl() LN5863 Unknown type: 8
ERROR: dumpInAvroTbTagsImpl() LN5863 Unknown type: 8
WARN: dumpInAvroTbTagsImpl() LN5895 taos_query() failed! sqlstr: CREATE TABLE xx23015h.`t003` USING xx23015h.`s_tsp` TAGS), reason: syntax error near ")"
ERROR: getTableDesNative() LN2859, failed to run command <DESCRIBE xx23015h.`s_ms`>. code: 0x80000020, reason: some vnode/qnode/mnode(s) out of service
ERROR: dumpInAvroTbTagsImpl() LN5863 Unknown type: 8
ERROR: getTableDesNative() LN2859, failed to run command <DESCRIBE xx23015h.`s_cems`>. code: 0x80000020, reason: some vnode/qnode/mnode(s) out of service
ERROR: dumpInAvroTbTagsImpl() LN5863 Unknown type: 8
ERROR: dumpInAvroTbTagsImpl() LN5863 Unknown type: 8
ERROR: dumpInAvroTbTagsImpl() LN5863 Unknown type: 8
ERROR: dumpInAvroTbTagsImpl() LN5863 Unknown type: 8
ERROR: dumpInAvroTbTagsImpl() LN5863 Unknown type: 8
ERROR: dumpInAvroTbTagsImpl() LN5863 Unknown type: 8
WARN: dumpInAvroTbTagsImpl() LN5895 taos_query() failed! sqlstr: CREATE TABLE xx23015h.`w204` USING xx23015h.`s_ms_308` TAGS), reason: syntax error near ")"
ERROR: dumpInAvroTbTagsImpl() LN5863 Unknown type: 8
WARN: dumpInAvroTbTagsImpl() LN5895 taos_query() failed! sqlstr: CREATE TABLE xx23015h.`w102` USING xx23015h.`s_ms_2001` TAGS), reason: syntax error near ")"
ERROR: dumpInAvroTbTagsImpl() LN5863 Unknown type: 8
ERROR: dumpInAvroTbTagsImpl() LN5863 Unknown type: 8
ERROR: getTableDesNative() LN2859, failed to run command <DESCRIBE xx23015h.`s_gps`>. code: 0x80000020, reason: some vnode/qnode/mnode(s) out of service
WARN: dumpInAvroTbTagsImpl() LN5895 taos_query() failed! sqlstr: CREATE TABLE xx23015h.`cems2` USING xx23015h.`s_cems` TAGS), reason: syntax error near ")"
WARN: dumpInAvroTbTagsImpl() LN5895 taos_query() failed! sqlstr: CREATE TABLE xx23015h.`w001` USING xx23015h.`s_ms` TAGS), reason: syntax error near ")"
ERROR: dumpInAvroTbTagsImpl() LN5863 Unknown type: 10
ERROR: dumpInAvroTbTagsImpl() LN5863 Unknown type: 10
WARN: dumpInAvroTbTagsImpl() LN5895 taos_query() failed! sqlstr: CREATE TABLE xx23015h.`g002` USING xx23015h.`s_gps` TAGS), reason: syntax error near ")"

**Comment by ly0928** [comment]
正常导出文件 执行导入 出现错误

**Comment by sangshuduo** [comment]
TDengine 和 taosdump 什么版本？要从什么版本往什么版本迁移？

reason: some vnode/qnode/mnode(s) out of service  错误需要根据 taosdlog 排查

**Comment by ly0928** [comment]
TDengine 是3.0.7.0 taosdump 是2.5.2 版本都是3.0.7.0

**Comment by ly0928** [comment]
超级表导入成功 其子表全部失败

**Comment by sangshuduo** [comment]
请提供一下 xx23015h.s\_tvoc 表的 schema

另外上传发生 Out of service 时间的 taosd 所在机器的 taosdlog 文件

**Comment by ly0928** [comment]
CREATE TABLE IF NOT EXISTS xx23015h.`s_tvoc`(`ts` timestamp,`tvoc` float) TAGS(`devicetype` binary(64),`devicename` binary(64),`deviceid` binary(64));
这是表的语句
我的场景是使用docker-compose 生成多个运行的容器 通过nginx做端口映射,可能TDengine配置中的问题 不知道taos.cfg中fqdn我应怎么写

**Comment by ly0928** [comment]
日志文件中能看到的错误信息为
RPC ERROR http-report failed to conn to server, reason:connection refused, dst:localhost:6043

**Comment by ly0928** [comment]
6043端口是什么程序的端口呢 导入会用到吗

**Comment by sangshuduo** [comment]
> 6043端口是什么程序的端口呢 导入会用到吗

taoskeeper 用的，和备份导入没关系。估计还是容器 FQDN 相关的配置引起的问题，和 taosdump 关系不大。你用 taos 命令行估计也会有一样的错误

**Comment by ly0928** [comment]
但是正常的超级表导入成功 就只有子表失败 正确的配置应该是如何

**Comment by ly0928** [comment]
正常登录可行 涉及到导入的这个数据库会报错
DB error: Unable to establish connection

**Comment by sangshuduo** [comment]
> 正常登录可行 涉及到导入的这个数据库会报错 DB error: Unable to establish connection

所以和 taosdump 没关系，就是环境问题

**Comment by ly0928** [comment]
已找到问题已解决

**Comment by ohhhyuan** [comment]
想问下，你怎么把手动搭建的TD集群数据迁移到容器里的

**Comment by pkarqi** [comment]
> 想问下，你怎么把手动搭建的TD集群数据迁移到容器里的

+1

**Comment by wkgitacct** [comment]
请问下，taosdump导入报错reason: some vnode/qnode/mnode(s) out of service，这个问题最后怎么解决的？

**Comment by wkgitacct** [comment]
> 已找到问题已解决
请问下，taosdump导入报错reason: some vnode/qnode/mnode(s) out of service，这个问题最后怎么解决的？
