### ISSUE TITLE
写入后读取最新的数据时有时能读到有时读不到

### ISSUE THREAD

**Issue by beimyy** [taosdata/TDengine#22746]
**Bug Description**
通过java jdbc读写, 先写入一条数据, 然后读最后的数据的ts写入的进行对比, 有可能对比相同, 也可能对比不同, 实际是有时能读到数据, 有时读不到数据.

**To Reproduce**
见下面 test1 和 test2

**Expected Behavior**
写入后马上读能读到最新的数据

**Screenshots**
test1:
index: 1	time: 1693905548234	lastTime: 1693905548234	equals
index: 2	time: 1693905648234	lastTime: 1693905648234	equals
index: 3	time: 1693905748234	lastTime: 1693905748234	equals
index: 4	time: 1693905848234	lastTime: 1693905848234	equals

test2:
on start: 0
index: 1	time: 1693904889766	lastTime: 0	 not equals
index: 2	time: 1693904989766	lastTime: 0	 not equals
index: 3	time: 1693905089766	lastTime: 0	 not equals
index: 4	time: 1693905189766	lastTime: 0	 not equals

**Environment:**
 - OS: ubuntu20.04 
 - Memory 64G, CPU 32核心, current Disk Space 4T
 - TDengine Version [2.4.0.30]
 - JDK 1.8

**Additional Context**

    private Connection getConnection() throws SQLException {
        String jdbcUrl = "";
        jdbcUrl = "jdbc:TAOS://taosnode1:6030/test?user=root&password=taosdata";
        Properties connProps = new Properties();
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_CHARSET, "UTF-8");
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_LOCALE, "en_US.UTF-8");
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_TIME_ZONE, "UTC-8");
        Connection conn = DriverManager.getConnection(jdbcUrl, connProps);
        return conn;
    }

    private void createTable(Connection conn) throws SQLException {
        String dropSql = "DROP STABLE IF EXISTS meter";
        Statement statement = conn.createStatement();
        statement.execute(dropSql);
        statement.close();

        String createSql = "create stable meter (ts TIMESTAMP,val DOUBLE) TAGS (code NCHAR(20))";
        statement = conn.createStatement();
        statement.execute(createSql);
        statement.close();
    }

    private void insert(Connection conn, Long time, Double val) throws SQLException {
        String sql = "insert into meter_1001 using meter tags ('1001') values (" + time + ", " + val + ")";
        Statement statement = conn.createStatement();
        statement.executeUpdate(sql);
        statement.close();
    }

    public Long last(Connection conn) throws SQLException {
        String sql = "select last(*) from meter";
        Statement statement = conn.createStatement();
        try {
            ResultSet resultSet = statement.executeQuery(sql);
            if (resultSet.next()) {
                return resultSet.getLong("ts");
            } else {
                return 0L;
            }
        } catch (Exception e) {
            e.printStackTrace();
            return -1L;
        } finally {
            statement.close();
        }
    }

    @Test
    public void test1() throws SQLException {
        Connection conn = getConnection();
        createTable(conn);
        Date now = new Date();
        for (int i = 1; i < 5; i++) {
            long time = now.getTime();
            double val = time * Math.random();
            insert(conn, time, val);
            Long lastTime = last(conn);
            if (time != lastTime) {
                System.out.println("index: " + i + "\ttime: " + time + "\tlastTime: " + lastTime + "\t not equals");
            } else {
                System.out.println("index: " + i + "\ttime: " + time + "\tlastTime: " + lastTime + "\tequals");
            }
            now = new Date(time + 100000);
        }
    }

    @Test
    public void test2() throws SQLException {
        Connection conn = getConnection();
        createTable(conn);
        System.out.println("on start: " + last(conn)); // 相比test1多了此行, 后续对比全部失败
        Date now = new Date();
        for (int i = 1; i < 5; i++) {
            long time = now.getTime();
            double val = time * Math.random();
            insert(conn, time, val);
            Long lastTime = last(conn);
            if (time != lastTime) {
                System.out.println("index: " + i + "\ttime: " + time + "\tlastTime: " + lastTime + "\t not equals");
            } else {
                System.out.println("index: " + i + "\ttime: " + time + "\tlastTime: " + lastTime + "\tequals");
            }
            now = new Date(time + 100000);
        }
    }

**Comment by sangshuduo** [comment]
建议升级到 3.1 最新版本
