### ISSUE TITLE
为什么至少要有一个TAG，能否去掉这个限制？

### ISSUE THREAD

**Issue by lzxoy** [taosdata/TDengine#22781]

**Comment by sangshuduo** [comment]
普通表可以没有 tag

**Comment by lzxoy** [comment]
什么场景适合用超级表？什么情况下用普通标就行？

**Comment by sangshuduo** [comment]
建议通读一下官方文档

**Comment by lzxoy** [comment]
> 由于一个数据采集点一张表，导致表的数量巨增，难以管理，而且应用经常需要做采集点之间的聚合操作，聚合的操作也变得复杂起来。为解决这个问题，TDengine 引入超级表（Super Table，简称为 STable）的概念。 

[官方文档](https://docs.taosdata.com/concept)看到这段话，解答了我的疑惑，写的清楚 👍

---

接下来，我们继续讨论原来的主题 😂

是否考虑过在超级表中去掉至少一个TAG的限制？

**Comment by enix223** [comment]
你既然要用超级表，肯定是需要基于超级表创建子表，如果你的超级表没有TAG，又基于什么来区分子表呢？

还是建议你直接用普通表吧

**Comment by lzxoy** [comment]
> 你既然要用超级表，肯定是需要基于超级表创建子表，如果你的超级表没有TAG，又基于什么来区分子表呢？
> 
> 还是建议你直接用普通表吧

不太理解，为什么没有TAG就不能区分子表呢？
