### ISSUE TITLE
3.1.0.3 插入数据本地运行正常，发到服务器上插入报错，jdk 版本8 ，操作系统 centos

### ISSUE THREAD

**Issue by yuanThink** [taosdata/TDengine#22785]
*** Error in `java': double free or corruption (out): 0x00007fc2200b10a0 ***
![image](https://github.com/taosdata/TDengine/assets/13092348/b25e3eac-29a3-44bf-8ca3-1c4f61609260)
![image](https://github.com/taosdata/TDengine/assets/13092348/397833e7-bef2-4cc2-a1a8-9515be7aee0a)
![image](https://github.com/taosdata/TDengine/assets/13092348/2860c3bf-cc48-4a32-a7b5-79fa7caa648d)

**Comment by yu285** [comment]
我们看一下。可以加我微信远程排查一下

a15652223354
