### ISSUE TITLE
3.1.1.0 repeated data came up 

### ISSUE THREAD

**Issue by bwcx-jzy** [taosdata/TDengine#22798]
**Bug Description**
3.1.1.0 版本数据主键出现重复，数据大批量异常

**To Reproduce**

今天发现数据库中同一个表中出现主键相同的数据，现在数据库版本为 3.1.1.0 之前版本是 3.0.4.1 今天升级

**Expected Behavior**
主键唯一

**Screenshots**
查询重复记录

![image](https://github.com/taosdata/TDengine/assets/16408873/5a7a0dcc-043d-48db-8042-4cfb9494369a)

建表，建库语句

![image](https://github.com/taosdata/TDengine/assets/16408873/37b4f487-507b-4772-b0fd-42f05a95f6e7)

![image](https://github.com/taosdata/TDengine/assets/16408873/44da30c0-de96-4ae7-9aa1-51b9b3312b0c)

主键重复具体记录

![image](https://github.com/taosdata/TDengine/assets/16408873/5c40e1ae-99f5-4ec9-9245-67be292a80ed)

**Environment (please complete the following information):**
 - OS: docker
 - TDengine Version 3.0.4.1 -> 3.1.1.0

**Comment by jandison** [comment]
3.1.1.0版本，我们测试了一段时间，发现不太稳定，运行大概半天后，客户端报连接服务端超时，然后taosdlog日志的归档和配置不符合，而且归档日志解压报错。同样在3.0.6.0上是正常的。

**Comment by sangshuduo** [comment]
> 3.1.1.0版本，我们测试了一段时间，发现不太稳定，运行大概半天后，客户端报连接服务端超时，然后taosdlog日志的归档和配置不符合，而且归档日志解压报错。同样在3.0.6.0上是正常的。

如果是另外的问题请新开一个 issue，提供详细的描述和日志

**Comment by yu285** [comment]
我们已经在跟进调查了

**Comment by yu285** [comment]
问题已经修复了，麻烦升级解决吧——最新版3.2.2.0
