### ISSUE TITLE
taosd takes too much single-core CPU and writes slowly

### ISSUE THREAD

**Issue by ll10020163** [taosdata/TDengine#2279]
我的服务器环境是4核CPU，但是taos 只是占用了单核心全程保持100%占用率，如果在做持续取数据甚至会达到107%的占用，这将导致kafka消费产生堆积现象。

Tasks: 133 total,   2 running, 131 sleeping,   0 stopped,   0 zombie
%Cpu(s): 25.3 us,  2.2 sy,  0.0 ni, 72.3 id,  0.0 wa,  0.0 hi,  0.2 si,  0.0 st
KiB Mem : 16266248 total,  8225056 free,  6132792 used,  1908400 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  9794472 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     
 1319 root      20   0 2202084 334036   2176 S 102.0  2.1   2089:48 taosd

线程详情：
Threads:  23 total,   2 running,  21 sleeping,   0 stopped,   0 zombie
%Cpu(s): 26.6 us,  2.1 sy,  0.0 ni, 71.0 id,  0.0 wa,  0.0 hi,  0.2 si,  0.0 st
KiB Mem : 16266248 total,  8225696 free,  6131556 used,  1908996 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  9795708 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND      
 1413 root      20   0 2136548 329492   2192 R 96.7  2.0   1020:26 taosd        
 1414 root      20   0 2136548 329492   2192 S  9.7  2.0   1053:50 taosd        
 1349 root      20   0 2136548 329492   2192 R  0.7  2.0   4:56.82 taosd        
 1401 root      20   0 2136548 329492   2192 S  0.3  2.0   0:16.09 taosd        
 1611 root      20   0 2136548 329492   2192 S  0.3  2.0   4:49.68 taosd        
 1319 root      20   0 2136548 329492   2192 S  0.0  2.0   0:00.05 taosd        
 1348 root      20   0 2136548 329492   2192 S  0.0  2.0   0:00.10 taosd        
 1350 root      20   0 2136548 329492   2192 S  0.0  2.0   0:00.00 taosd        
 1351 root      20   0 2136548 329492   2192 S  0.0  2.0   0:06.26 taosd        
 1352 root      20   0 2136548 329492   2192 S  0.0  2.0   0:06.20 taosd        
 1353 root      20   0 2136548 329492   2192 S  0.0  2.0   0:16.00 taosd        
 1354 root      20   0 2136548 329492   2192 S  0.0  2.0   1:31.27 taosd        
 1355 root      20   0 2136548 329492   2192 S  0.0  2.0   5:37.62 taosd        
 1402 root      20   0 2136548 329492   2192 S  0.0  2.0   0:00.00 taosd        
 1406 root      20   0 2136548 329492   2192 S  0.0  2.0   0:02.05 taosd        
 1408 root      20   0 2136548 329492   2192 S  0.0  2.0   0:02.04 taosd        
 1409 root      20   0 2136548 329492   2192 S  0.0  2.0   0:00.13 taosd        
 1410 root      20   0 2136548 329492   2192 S  0.0  2.0   0:00.13 taosd        
 1411 root      20   0 2136548 329492   2192 S  0.0  2.0   0:05.26 taosd        
 1612 root      20   0 2136548 329492   2192 S  0.0  2.0   0:00.28 taosd        
 1615 root      20   0 2136548 329492   2192 S  0.0  2.0   0:00.09 taosd        
 1616 root      20   0 2136548 329492   2192 S  0.0  2.0   0:00.23 taosd        
 1617 root      20   0 2136548 329492   2192 S  0.0  2.0   0:00.00 taosd 

使用过程：
1、每次插入数据前，先查询1分钟内的TD数据，处理后，再写入数据到TD。高峰期每5分钟写入125条数据。这种处理程度单核CPU就占用了100%。
2、如果每秒获取1天内的数据，CPU占用率将达到108%，同时影响数据写入。
请尽快处理。

**Comment by Aries-Lee1991** [comment]
好的，收到。

**Comment by Aries-Lee1991** [comment]
您用的是哪个版本？ @ll10020163

**Comment by ll10020163** [comment]
> 您用的是哪个版本？ @ll10020163

TDengine-server-1.6.5.5-Linux-x64.tar

**Comment by Aries-Lee1991** [comment]
@liu0x54 麻烦看一下这个问题。

**Comment by liu0x54** [comment]
请尝试在taos.cfg中修改一下这个配置：
numOfThreadsPerCore  2
如果以上修改有一点效果，可以尝试修改成
numOfThreadsPerCore 4
看看有没有改善

**Comment by ll10020163** [comment]
> 请尝试在taos.cfg中修改一下这个配置：
> numOfThreadsPerCore 2
> 如果以上修改有一点效果，可以尝试修改成
> numOfThreadsPerCore 4
> 看看有没有改善

配置好后是否需要重启TD数据库服务 ？

**Comment by ll10020163** [comment]
![image](https://user-images.githubusercontent.com/64181672/85101146-5312b580-b234-11ea-9396-7e3292f04dd7.png)
观察了一段时间后反馈下，设置后好用！ 查询效率变快很多，我设置的是三核。CPU瞬时占用率可以达到整体（4核心）75%

**Comment by ll10020163** [comment]
![image](https://user-images.githubusercontent.com/64181672/85101078-26f73480-b234-11ea-9371-38866537bc5c.png)
![image](https://user-images.githubusercontent.com/64181672/85101620-5c505200-b235-11ea-83fe-ce78590a3583.png)


改进下使用方式，taosd占用率降低到2%，看来taosd不适合频繁取数据操作。
原先：1、每次插入数据前，先查询1分钟内的TD数据，处理后，再写入数据到TD。高峰期每5分钟写入125条数据。这种处理程度单核CPU就占用了100%。
现在：1、每次插入数据前先保存到Redis里，处理后，再写入数据到TD。CPU占用率就很低了。

**Comment by liu0x54** [comment]
你查询1分钟的数据是什么查询？是查询原始数据还是聚合计算后的结果？然后做什么样的处理？
能否详细说说，我们看看你这场景怎么优化

**Comment by liu0x54** [comment]
另外你的schema是什么样的，能否贴一下？

**Comment by ll10020163** [comment]
![image](https://user-images.githubusercontent.com/64181672/85105227-b1dc2d00-b23c-11ea-8bfe-412d7b00f845.png)

场景，设备数据汇总到服务器后进行处理保存。

操作方式： 
获得数据后，根据设备上报时间（ts的时间是有延迟的不准），设备MAC，查询1分钟内的数据。使用如下语句。
select  * from dataname.dataname
        where mac_up_date &gt; '1990-01-01 00:00:00.000'
            AND mac_up_date &gt; #{startTime}
            AND mac_up_date &lt;= #{endTime}
            AND mac = #{mac}
        order by ts desc;

如果与返回 1分钟内的 number 重复 ，就不插入这条数据。否则插入到TD数据库。

或者有什么更高效的去重建议？

**Comment by liu0x54** [comment]
是否可以直接用mac_up_data作为主键，不要ts这个字段？如果只保留mac_up_data作为timestamp，那么性能会提高很多。
另外，number为啥是个NCHAR？是中文字符吗？如果都是英文字符，建议NCHAR都改成binary
如果mac_up_date是唯一的timestamp，我们是可以支持mac_up_data的排序的。
以上，才是时序数据库的正确使用方式，否则，不如采用关系型数据库

**Comment by ll10020163** [comment]
mac_up_data 不是毫秒级，如果用的话必须要毫秒级是么？
number 确实有中文情况。

**Comment by liu0x54** [comment]
没关系的，你这个时间戳是unix timestamp还是字符？只要能保证唯一，都可以添加位数来达到相应精度；如果秒的精度上有重复，可以在写入程序中根据先来后到关系在毫秒位上做出区别

**Comment by Aries-Lee1991** [comment]
It seems the problem has been solved. I closed the issue. If there are other problems, please reopen the issue again, or submit a new issue.
