### ISSUE TITLE
软件安装提问

### ISSUE THREAD

**Issue by zpy853787428** [taosdata/TDengine#228]
在windows平台上启动程序，程序启动异常，错误信息:
07/30 09:32:30.854000 0x1880536507568 ERROR RPC TSC-mgmt cid:0 sid:1 id:root, dataLen:185 writtenLen:-1, not good, reason:No error

**Comment by zpy853787428** [comment]
从官网上提供的数据信息得知，TDengine的开发背景是针对于物联网，物联网的数据每时每刻都在产生，每个时间点都会产生相应的数据，对于传统的行业数据问题，比如:银行历史数据清洗 计算等，是否支持。

**Comment by zimengpan** [comment]
关于第二个问题，根据TDengine的开发初衷，其中有以下三点：
1、写多读少
2、注重趋势，而非某一特定时间点的准确值
3、数据有保留期限
银行历史数据清洗计算等场景至少在这三点上与TDengine相悖。建议使用Hadoop等作为首要处理平台

**Comment by guanshengliang** [comment]
windows的问题通常不好定位
1.修改配置文件，即C:/TDengine/cfg/taos.cfg文件，增加一行debugFlag 135 
2.清空日志，即删除C:/TDengine/log/文件夹的所有日志文件
3.通过cmd.exe，在C:/TDengine目录下执行taos.exe -h ip地址
4.将日志文件夹下的日志文件，压缩后发给slgaun@taosdata.com，并在邮箱中留下微信号联系方式，我会和你沟通解决
