### ISSUE TITLE
3.1.1.0. tag 插入的bug

### ISSUE THREAD

**Issue by 414501408** [taosdata/TDengine#22815]
<img width="1291" alt="image" src="https://github.com/taosdata/TDengine/assets/24967627/fbeaa3ab-d812-420f-8918-206067b49bf8">

表结构如上

<img width="1641" alt="image" src="https://github.com/taosdata/TDengine/assets/24967627/65f0cd5f-35c3-4282-85e4-f226076f3620">

插入数据后， tag 查询出来跟插入的不一样

**Comment by sangshuduo** [comment]
这是之前用 NULL, k7 最为 tag 值建过表吧？tag 值是第一次写入即生效，后面写入的不会覆盖之前的值

**Comment by 414501408** [comment]
是的， tag 难道是整个子表里面都不会变的吗

**Comment by sangshuduo** [comment]
TAG 是设备的静态数据，通常是不变或者很少变。修改标签值的方法参见 https://docs.taosdata.com/taos-sql/table/#%E4%BF%AE%E6%94%B9%E5%AD%90%E8%A1%A8%E6%A0%87%E7%AD%BE%E5%80%BC
