### ISSUE TITLE
taosdump导出报错ERROR: writeResultToAvroNative() LN5077, actual dump out: 5131750, batch 5344733

### ISSUE THREAD

**Issue by zhaodianyi** [taosdata/TDengine#22827]
**Bug Description**

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by sangshuduo** [comment]
TDengine 什么版本？taosdump 什么版本？完整的输出是什么？

**Comment by zhaodianyi** [comment]
[root@localhost home]# taos --version
version: 2.6.0.30

[root@localhost home]# taosdump --version
taosdump version 2.4.2, commit: 40632cb

上边是版本，下边是导出日志，最后没有导出完，一直停在那个位置两三个小时没动，不知是何原因

[root@localhost home]# taosdump -o /data/zdy/ -uroot -proot.123456 -D xdiot_witpark2_db
==============================
========== arguments config =========
taosdump version 2.4.2, commit: 40632cb
host: (null)
user: root
port: 0
outpath: /data/zdy//
inpath: 
resultFile: ./dump_result.txt
all_databases: false
databases: true
databasesSeq: xdiot_witpark2_db
schemaonly: false
with_property: true
answer_yes: false
avro codec: snappy
data_batch: 16383
thread_num: 8
allow_sys: false
escape_char: true
loose_mode: false
isDumpIn: false
arg_list_len: 0
OK: Database: xdiot_witpark2_db exists
INFO: Start to dump out database: xdiot_witpark2_db
INFO: Getting tables' number of super table (mapping_product21) ...
INFO: dumpNtbOfStbByThreads() LN10551, xdiot_witpark2_db's mapping_product21's total normal table count: 5
INFO: connection: 0x556b5943f110 is dumping out schema of sub-table(s) of mapping_product21 
INFO: Getting tables' number of super table (mapping_product21) ...
INFO: The number of tables of mapping_product21 is 5!
INFO: connection 0x556b5943f110 fetched 20% of mapping_product21' tbname
INFO: connection 0x556b5943f110 fetched 40% of mapping_product21' tbname
INFO: connection 0x556b5943f110 fetched 60% of mapping_product21' tbname
INFO: connection 0x556b5943f110 fetched 80% of mapping_product21' tbname
INFO: connection 0x556b5943f110 fetched 100% of mapping_product21' tbname
OK: total 5 sub-table's name of stable: mapping_product21 fetched
INFO: The number of tables of mapping_product21 be filled is 5!
INFO: connection 0x556b5943f110 is dumping out schema:0% of mapping_product21
INFO: connection 0x556b5943f110 is dumping out schema:20% of mapping_product21
INFO: connection 0x556b5943f110 is dumping out schema:40% of mapping_product21
INFO: connection 0x556b5943f110 is dumping out schema:60% of mapping_product21
INFO: connection 0x556b5943f110 is dumping out schema:80% of mapping_product21
INFO: connection 0x556b5943f110 is dumping out schema:100% of mapping_product21
OK: total 5 sub table(s) of stable: mapping_product21 dumped
.INFO: 100% of data_product21_eqp004
.INFO: 100% of data_product21_eqp003
ERROR: getTableTagValueNativeV2() LN2805, failed to run command <SELECT `equipment_id`,`dept_code`,`project_code`,`space0`,`space1`,`space2`,`space3`,`space4`,`space5`,`space6`,`space7`,`space8`,`space9` FROM xdiot_witpark2_db.`data_product21_eqp005` LIMIT 1>, taos: 0x556b59737ea0, code: 0x8000020f, reason: Query terminated
ERROR: dumpNormalTable() LN8426 columns/tags count is -1
INFO: Getting tables' number of super table (mapping_product7) ...
INFO: dumpNtbOfStbByThreads() LN10551, xdiot_witpark2_db's mapping_product7's total normal table count: 2
INFO: connection: 0x556b5943f110 is dumping out schema of sub-table(s) of mapping_product7 
INFO: Getting tables' number of super table (mapping_product7) ...
INFO: The number of tables of mapping_product7 is 2!
INFO: connection 0x556b5943f110 fetched 50% of mapping_product7' tbname
INFO: connection 0x556b5943f110 fetched 100% of mapping_product7' tbname
OK: total 2 sub-table's name of stable: mapping_product7 fetched
INFO: The number of tables of mapping_product7 be filled is 2!
INFO: connection 0x556b5943f110 is dumping out schema:0% of mapping_product7
INFO: connection 0x556b5943f110 is dumping out schema:50% of mapping_product7
INFO: connection 0x556b5943f110 is dumping out schema:100% of mapping_product7
OK: total 2 sub table(s) of stable: mapping_product7 dumped
.INFO: 100% of data_product7_eqp001
.INFO: 100% of data_product7_eqp002
INFO: Getting tables' number of super table (mapping_product14) ...
INFO: dumpNtbOfStbByThreads() LN10551, xdiot_witpark2_db's mapping_product14's total normal table count: 6
INFO: connection: 0x556b5943f110 is dumping out schema of sub-table(s) of mapping_product14 
INFO: Getting tables' number of super table (mapping_product14) ...
INFO: The number of tables of mapping_product14 is 6!
INFO: connection 0x556b5943f110 fetched 16% of mapping_product14' tbname
INFO: connection 0x556b5943f110 fetched 33% of mapping_product14' tbname
INFO: connection 0x556b5943f110 fetched 50% of mapping_product14' tbname
INFO: connection 0x556b5943f110 fetched 66% of mapping_product14' tbname
INFO: connection 0x556b5943f110 fetched 83% of mapping_product14' tbname
INFO: connection 0x556b5943f110 fetched 100% of mapping_product14' tbname
OK: total 6 sub-table's name of stable: mapping_product14 fetched
INFO: The number of tables of mapping_product14 be filled is 6!
INFO: connection 0x556b5943f110 is dumping out schema:0% of mapping_product14
INFO: connection 0x556b5943f110 is dumping out schema:16% of mapping_product14
INFO: connection 0x556b5943f110 is dumping out schema:33% of mapping_product14
INFO: connection 0x556b5943f110 is dumping out schema:50% of mapping_product14
INFO: connection 0x556b5943f110 is dumping out schema:66% of mapping_product14
INFO: connection 0x556b5943f110 is dumping out schema:83% of mapping_product14
INFO: connection 0x556b5943f110 is dumping out schema:100% of mapping_product14
OK: total 6 sub table(s) of stable: mapping_product14 dumped
.INFO: 100% of data_product14_eqp008
.INFO: 100% of data_product14_eqp006
.INFO: 100% of data_product14_eqp009
.INFO: 100% of data_product14_eqp007
INFO: Getting tables' number of super table (tj2) ...
INFO: dumpNtbOfStbByThreads() LN10551, xdiot_witpark2_db's tj2's total normal table count: 0
INFO: Getting tables' number of super table (mapping_chuanbo) ...
INFO: dumpNtbOfStbByThreads() LN10551, xdiot_witpark2_db's mapping_chuanbo's total normal table count: 1
INFO: connection: 0x556b5943f110 is dumping out schema of sub-table(s) of mapping_chuanbo 
INFO: Getting tables' number of super table (mapping_chuanbo) ...
INFO: The number of tables of mapping_chuanbo is 1!
INFO: connection 0x556b5943f110 fetched 100% of mapping_chuanbo' tbname
OK: total 1 sub-table's name of stable: mapping_chuanbo fetched
INFO: The number of tables of mapping_chuanbo be filled is 1!
INFO: connection 0x556b5943f110 is dumping out schema:0% of mapping_chuanbo
INFO: connection 0x556b5943f110 is dumping out schema:100% of mapping_chuanbo
OK: total 1 sub table(s) of stable: mapping_chuanbo dumped
ERROR: writeResultToAvroNative() LN5077, actual dump out: 6510337, batch 12479401
.INFO: 100% of data_356828000
INFO: Getting tables' number of super table (mapping_product15) ...
INFO: dumpNtbOfStbByThreads() LN10551, xdiot_witpark2_db's mapping_product15's total normal table count: 3
INFO: connection: 0x556b5943f110 is dumping out schema of sub-table(s) of mapping_product15 
INFO: Getting tables' number of super table (mapping_product15) ...
INFO: The number of tables of mapping_product15 is 3!
INFO: connection 0x556b5943f110 fetched 33% of mapping_product15' tbname
INFO: connection 0x556b5943f110 fetched 66% of mapping_product15' tbname
INFO: connection 0x556b5943f110 fetched 100% of mapping_product15' tbname
OK: total 3 sub-table's name of stable: mapping_product15 fetched
INFO: The number of tables of mapping_product15 be filled is 3!
INFO: connection 0x556b5943f110 is dumping out schema:0% of mapping_product15
INFO: connection 0x556b5943f110 is dumping out schema:33% of mapping_product15
INFO: connection 0x556b5943f110 is dumping out schema:66% of mapping_product15
INFO: connection 0x556b5943f110 is dumping out schema:100% of mapping_product15
OK: total 3 sub table(s) of stable: mapping_product15 dumped
.INFO: 100% of data_product15_eqp004
.INFO: 100% of data_product15_eqp005
.INFO: 100% of data_product15_eqp003
INFO: Getting tables' number of super table (mapping_product2) ...
INFO: dumpNtbOfStbByThreads() LN10551, xdiot_witpark2_db's mapping_product2's total normal table count: 1
INFO: connection: 0x556b5943f110 is dumping out schema of sub-table(s) of mapping_product2 
INFO: Getting tables' number of super table (mapping_product2) ...
INFO: The number of tables of mapping_product2 is 1!
INFO: connection 0x556b5943f110 fetched 100% of mapping_product2' tbname
OK: total 1 sub-table's name of stable: mapping_product2 fetched
INFO: The number of tables of mapping_product2 be filled is 1!
INFO: connection 0x556b5943f110 is dumping out schema:0% of mapping_product2
INFO: connection 0x556b5943f110 is dumping out schema:100% of mapping_product2
OK: total 1 sub table(s) of stable: mapping_product2 dumped
.INFO: 100% of data_product2_eqp001
INFO: Getting tables' number of super table (mapping_product3) ...
INFO: dumpNtbOfStbByThreads() LN10551, xdiot_witpark2_db's mapping_product3's total normal table count: 2
INFO: connection: 0x556b5943f110 is dumping out schema of sub-table(s) of mapping_product3 
INFO: Getting tables' number of super table (mapping_product3) ...
INFO: The number of tables of mapping_product3 is 2!
INFO: connection 0x556b5943f110 fetched 50% of mapping_product3' tbname
INFO: connection 0x556b5943f110 fetched 100% of mapping_product3' tbname
OK: total 2 sub-table's name of stable: mapping_product3 fetched
INFO: The number of tables of mapping_product3 be filled is 2!
INFO: connection 0x556b5943f110 is dumping out schema:0% of mapping_product3
INFO: connection 0x556b5943f110 is dumping out schema:50% of mapping_product3
INFO: connection 0x556b5943f110 is dumping out schema:100% of mapping_product3
OK: total 2 sub table(s) of stable: mapping_product3 dumped
.INFO: 100% of data_product3_eqp002
INFO: Getting tables' number of super table (mapping_product16) ...
INFO: dumpNtbOfStbByThreads() LN10551, xdiot_witpark2_db's mapping_product16's total normal table count: 6
INFO: connection: 0x556b5943f110 is dumping out schema of sub-table(s) of mapping_product16 
INFO: Getting tables' number of super table (mapping_product16) ...
INFO: The number of tables of mapping_product16 is 6!
INFO: connection 0x556b5943f110 fetched 16% of mapping_product16' tbname
INFO: connection 0x556b5943f110 fetched 33% of mapping_product16' tbname
INFO: connection 0x556b5943f110 fetched 50% of mapping_product16' tbname
INFO: connection 0x556b5943f110 fetched 66% of mapping_product16' tbname
INFO: connection 0x556b5943f110 fetched 83% of mapping_product16' tbname
INFO: connection 0x556b5943f110 fetched 100% of mapping_product16' tbname
OK: total 6 sub-table's name of stable: mapping_product16 fetched
INFO: The number of tables of mapping_product16 be filled is 6!
INFO: connection 0x556b5943f110 is dumping out schema:0% of mapping_product16
INFO: connection 0x556b5943f110 is dumping out schema:16% of mapping_product16
INFO: connection 0x556b5943f110 is dumping out schema:33% of mapping_product16
INFO: connection 0x556b5943f110 is dumping out schema:50% of mapping_product16
INFO: connection 0x556b5943f110 is dumping out schema:66% of mapping_product16
INFO: connection 0x556b5943f110 is dumping out schema:83% of mapping_product16
INFO: connection 0x556b5943f110 is dumping out schema:100% of mapping_product16
OK: total 6 sub table(s) of stable: mapping_product16 dumped
.INFO: 100% of data_product16_eqp002
.INFO: 100% of data_product16_eqp007
.INFO: 100% of data_product16_eqp006
.INFO: 100% of data_product16_eqp008
.INFO: 100% of data_product16_eqp004
.INFO: 100% of data_product16_eqp005
INFO: Getting tables' number of super table (mapping_product10) ...
INFO: dumpNtbOfStbByThreads() LN10551, xdiot_witpark2_db's mapping_product10's total normal table count: 1
INFO: connection: 0x556b5943f110 is dumping out schema of sub-table(s) of mapping_product10 
INFO: Getting tables' number of super table (mapping_product10) ...
INFO: The number of tables of mapping_product10 is 1!
INFO: connection 0x556b5943f110 fetched 100% of mapping_product10' tbname
OK: total 1 sub-table's name of stable: mapping_product10 fetched
INFO: The number of tables of mapping_product10 be filled is 1!
INFO: connection 0x556b5943f110 is dumping out schema:0% of mapping_product10
INFO: connection 0x556b5943f110 is dumping out schema:100% of mapping_product10
OK: total 1 sub table(s) of stable: mapping_product10 dumped
INFO: Getting tables' number of super table (mapping_product1) ...
INFO: dumpNtbOfStbByThreads() LN10551, xdiot_witpark2_db's mapping_product1's total normal table count: 1
INFO: connection: 0x556b5943f110 is dumping out schema of sub-table(s) of mapping_product1 
INFO: Getting tables' number of super table (mapping_product1) ...
INFO: The number of tables of mapping_product1 is 1!
INFO: connection 0x556b5943f110 fetched 100% of mapping_product1' tbname
OK: total 1 sub-table's name of stable: mapping_product1 fetched
INFO: The number of tables of mapping_product1 be filled is 1!
INFO: connection 0x556b5943f110 is dumping out schema:0% of mapping_product1
INFO: connection 0x556b5943f110 is dumping out schema:100% of mapping_product1
OK: total 1 sub table(s) of stable: mapping_product1 dumped
.INFO: 100% of data_product1_eqp001
INFO: Getting tables' number of super table (mapping_product11) ...
INFO: dumpNtbOfStbByThreads() LN10551, xdiot_witpark2_db's mapping_product11's total normal table count: 3
INFO: connection: 0x556b5943f110 is dumping out schema of sub-table(s) of mapping_product11 
INFO: Getting tables' number of super table (mapping_product11) ...
INFO: The number of tables of mapping_product11 is 3!
INFO: connection 0x556b5943f110 fetched 33% of mapping_product11' tbname
INFO: connection 0x556b5943f110 fetched 66% of mapping_product11' tbname
INFO: connection 0x556b5943f110 fetched 100% of mapping_product11' tbname
OK: total 3 sub-table's name of stable: mapping_product11 fetched
INFO: The number of tables of mapping_product11 be filled is 3!
INFO: connection 0x556b5943f110 is dumping out schema:0% of mapping_product11
INFO: connection 0x556b5943f110 is dumping out schema:33% of mapping_product11
INFO: connection 0x556b5943f110 is dumping out schema:66% of mapping_product11
INFO: connection 0x556b5943f110 is dumping out schema:100% of mapping_product11
OK: total 3 sub table(s) of stable: mapping_product11 dumped
.INFO: 100% of data_product11_eqp006
.INFO: 100% of data_product11_eqp008
INFO: Getting tables' number of super table (mapping_product28) ...
INFO: dumpNtbOfStbByThreads() LN10551, xdiot_witpark2_db's mapping_product28's total normal table count: 2
INFO: connection: 0x556b5943f110 is dumping out schema of sub-table(s) of mapping_product28 
INFO: Getting tables' number of super table (mapping_product28) ...
INFO: The number of tables of mapping_product28 is 2!
INFO: connection 0x556b5943f110 fetched 50% of mapping_product28' tbname
INFO: connection 0x556b5943f110 fetched 100% of mapping_product28' tbname
OK: total 2 sub-table's name of stable: mapping_product28 fetched
INFO: The number of tables of mapping_product28 be filled is 2!
INFO: connection 0x556b5943f110 is dumping out schema:0% of mapping_product28
INFO: connection 0x556b5943f110 is dumping out schema:50% of mapping_product28
INFO: connection 0x556b5943f110 is dumping out schema:100% of mapping_product28
OK: total 2 sub table(s) of stable: mapping_product28 dumped
INFO: Getting tables' number of super table (mapping_product27) ...
INFO: dumpNtbOfStbByThreads() LN10551, xdiot_witpark2_db's mapping_product27's total normal table count: 1
INFO: connection: 0x556b5943f110 is dumping out schema of sub-table(s) of mapping_product27 
INFO: Getting tables' number of super table (mapping_product27) ...
INFO: The number of tables of mapping_product27 is 1!
INFO: connection 0x556b5943f110 fetched 100% of mapping_product27' tbname
OK: total 1 sub-table's name of stable: mapping_product27 fetched
INFO: The number of tables of mapping_product27 be filled is 1!
INFO: connection 0x556b5943f110 is dumping out schema:0% of mapping_product27
INFO: connection 0x556b5943f110 is dumping out schema:100% of mapping_product27
OK: total 1 sub table(s) of stable: mapping_product27 dumped
ERROR: writeResultToAvroNative() LN5077, actual dump out: 5131750, batch 5344733
.INFO: 100% of data_product27_eqp003

**Comment by sangshuduo** [comment]
ERROR: getTableTagValueNativeV2() LN2805, failed to run command \<SELECT `equipment_id`,`dept_code`,`project_code`,`space0`,`space1`,`space2`,`space3`,`space4`,`space5`,`space6`,`space7`,`space8`,`space9` FROM xdiot\_witpark2\_db.`data_product21_eqp005` LIMIT 1>, taos: 0x556b59737ea0, code: 0x8000020f, reason: Query terminated

估计系统有其他问题导致 Query terminated

**Comment by zhaodianyi** [comment]
ERROR: writeResultToAvroNative() LN5077, actual dump out: 5131750, batch 5344733

倒数第二行，像这种错误是何原因

**Comment by sangshuduo** [comment]
会先统计应该导出多少，最后统计实际导出多少。不一致报错。

**Comment by zhaodianyi** [comment]
ERROR: getTableTagValueNativeV2() LN2805, failed to run command <SELECT equipment_id,dept_code,project_code,space0,space1,space2,space3,space4,space5,space6,space7,space8,space9 FROM xdiot_witpark2_db.data_product21_eqp005 LIMIT 1>, taos: 0x556b59737ea0, code: 0x8000020f, reason: Query terminated

这个错误加了一个 -T 8 的参数就没有出现了
taosdump -c /etc/tao/ -o /data/taosbak -uroot  -proot.123456 -D xdiot_witpark2_db   -T 8
