### ISSUE TITLE
Error querying database.  Cause: java.nio.BufferUnderflowException

### ISSUE THREAD

**Issue by Zy-X25** [taosdata/TDengine#22836]
**Bug Description**
springboot+mybatis:使用查询语句select进行查询时添加条件会抛出 Error querying database.  Cause: java.nio.BufferUnderflowException

**To Reproduce**
1. 一个普通表，建表语句如下：create table if not exists m_data_transfer_record( ts TIMESTAMP, device_ts TIMESTAMP, m_id int,m_equip_id nchar(64), lon double, lat double, alt double, batch_id int,send_lon double, send_lat double, send_alt double, platform_id nchar(64), platform_lon double, platform_lat double,platform_alt double, detection_radius double, distance double);表数据量20w。
2. 一个简单查询，通过mybatis查询，sql如下：select * from m_data_transfer_record WHERE m_id = 1 order by ts asc limit 20 offset 0。在taos-shell中不报错。
3.当taos-jdbcdriver版本为3.2.2时报错：Cause: java.lang.IllegalArgumentException: newPosition > limit: (17320 > 3826)
4.当taos-jdbcdriver版本为3.2.4时报错：Error querying database.  Cause: java.nio.BufferUnderflowException

**Environment (please complete the following information):**
 - OS: win10
 - Memory, CPU, current Disk Space:8核16G
 - TDengine Version 3.0.5.1

**Comment by sangshuduo** [comment]
java.nio.BufferUnderflowException 不是 TDengine Java 报的错
