### ISSUE TITLE
Optimization suggestions for:  [ DB Error: too many results from vnodes for sort ]

### ISSUE THREAD

**Issue by sudo168** [taosdata/TDengine#2284]
**Bug Description**
执行：select * from table where tag='xxx' order by ts desc limit 1;
结果：DB Error: too many results from vnodes for sort

经查看Issue #2260 并咨询过官方，给的建议是：
1、增加配置 maxNumOfOrderedRes（默认10w），Issue #2260也有配，但是不生效
2、使用last_row（这在JDBC与mybatis映射上存在BUG）

**但是，我的问题是：**
1、做为高性能数据库，order by ts desc limit 1这种语句居然没有优化，居然还要判断maxNumOfOrderedRes，居然还要排序。。。看似需要优化，其实这更像是一个BUG。
2、10w的order by limit真的太小了。不用管用户内存，以及执行效率，实在太慢的话，用户会去解决（不会觉得是taos的问题），但是你用maxNumOfOrderedRes限制住了，这就呵呵了......这个也绝不是使用‘企业版’的充分理由，企业版采用这么low的功能做卖点，绝对是砸牌子。

**Environment (please complete the following information):**
 - OS:  Ubuntu
 - TDengine Version 1.6.5.9

**Comment by Aries-Lee1991** [comment]
在TDengine的设计中，本来是不提供针对跨表全局排序的支持，之所以增加这个功能，是因为有企业版用户提出来的需求。当然，源代码在github上，你有兴趣可以提交patch优化性能。欢迎！我们在企业版本中开发的出来的功能，本着共享的原则，同步推送到社区版本中。这个不是企业版的卖点，社区版本和企业版本的区别在网站上直接就能看到。

**Comment by sudo168** [comment]
我是指定tag的，不存在你说的跨表全局排序。

**Comment by sudo168** [comment]
select * from table where tag='xxx' order by ts desc limit 1;   
确认一下，使用tag了，也会触发排序，这个是不是可以优化？

**Comment by Aries-Lee1991** [comment]
问题私下应该已经沟通了，这里暂时关闭，如果还有其他问题，可以reopen或者新建。
