### ISSUE TITLE
通过insert更新

### ISSUE THREAD

**Issue by zuodengchao** [taosdata/TDengine#22842]
服务器版本3.0.1.8，以下场景是否有性能影响呢？

场景1 ：
insert 更新 null 字段，是否会影响插入性能和查询性能？

场景2 ：
insert 频繁更新某个字段为相同的值，是否会影响插入和查询性能？

**Comment by yu285** [comment]
3018 是去年的版本，和现在差很多，建议切换到 3110 版本，然后再进行测试。少走弯路
