### ISSUE TITLE
windows10 无法启动

### ISSUE THREAD

**Issue by dontls** [taosdata/TDengine#22851]
C:\TDengine>taosd.exe
09/12 10:09:57.818746 00019860 UTL apoll url not load
09/12 10:09:57.819776 00019860 UTL load from cfg file C:\TDengine\cfg\\taos.cfg success
09/12 10:09:57.820776 00019860 UTL env file:.env not load
09/12 10:09:57.822776 00019860 UTL load from env variables cfg success
09/12 10:09:57.827776 00019860 DND startup path:not implemented on windows args:taosd.exe
09/12 10:09:57.833746 00019860 UTL apoll url not load
09/12 10:09:57.835769 00019860 UTL load from cfg file C:\TDengine\cfg\\taos.cfg success
09/12 10:09:57.836771 00019860 UTL env file:.env not load
09/12 10:09:57.837774 00019860 UTL load from env variables cfg success
09/12 10:09:57.840770 00019860 UTL                      global config
09/12 10:09:57.842775 00019860 UTL =================================================================
09/12 10:09:57.844776 00019860 UTL default      firstEp                  DESKTOP-DMDB3AR:6030
09/12 10:09:57.845776 00019860 UTL default      secondEp                 DESKTOP-DMDB3AR:6030
09/12 10:09:57.848471 00019860 UTL default      fqdn                     DESKTOP-DMDB3AR
09/12 10:09:57.850473 00019860 UTL default      serverPort               6030
09/12 10:09:57.851474 00019860 UTL default      tempDir                  C:\Windows\Temp\
09/12 10:09:57.853468 00019860 UTL default      minimalTmpDirGB          1.00
09/12 10:09:57.854470 00019860 UTL default      shellActivityTimer       3
09/12 10:09:57.856471 00019860 UTL default      compressMsgSize          -1
09/12 10:09:57.857470 00019860 UTL default      compressColData          -1
09/12 10:09:57.859470 00019860 UTL default      queryPolicy              1
09/12 10:09:57.860471 00019860 UTL default      enableQueryHb            1
09/12 10:09:57.862441 00019860 UTL default      enableScience            0
09/12 10:09:57.864474 00019860 UTL default      querySmaOptimize         0
09/12 10:09:57.865470 00019860 UTL default      queryPlannerTrace        0
09/12 10:09:57.867474 00019860 UTL default      queryNodeChunkSize       32768
09/12 10:09:57.868470 00019860 UTL default      queryUseNodeAllocator    1
09/12 10:09:57.870471 00019860 UTL default      keepColumnName           0
09/12 10:09:57.871471 00019860 UTL default      smlChildTableName
09/12 10:09:57.873475 00019860 UTL default      smlTagName               _tag_null
09/12 10:09:57.874471 00019860 UTL default      smlTsDefaultName         _ts
09/12 10:09:57.876476 00019860 UTL default      smlDot2Underline         1
09/12 10:09:57.877470 00019860 UTL default      maxInsertBatchRows       1000000
09/12 10:09:57.879440 00019860 UTL default      maxRetryWaitTime         10000
09/12 10:09:57.881475 00019860 UTL default      useAdapter               0
09/12 10:09:57.883475 00019860 UTL default      crashReporting           1
09/12 10:09:57.884470 00019860 UTL default      queryMaxConcurrentTable  200
09/12 10:09:57.885471 00019860 UTL default      metaCacheMaxSize         -1
09/12 10:09:57.887470 00019860 UTL default      slowLogThreshold         3
09/12 10:09:57.888470 00019860 UTL default      slowLogScope
09/12 10:09:57.890471 00019860 UTL default      numOfRpcThreads          4
09/12 10:09:57.891471 00019860 UTL default      numOfRpcSessions         10000
09/12 10:09:57.893470 00019860 UTL default      timeToGetAvailableConn   500000
09/12 10:09:57.895440 00019860 UTL default      keepAliveIdle            60
09/12 10:09:57.897441 00019860 UTL default      numOfTaskQueueThreads    5
09/12 10:09:57.898471 00019860 UTL cfg_file     dataDir                  F:\tdata
09/12 10:09:57.900472 00019860 UTL default      minimalDataDirGB         2.00
09/12 10:09:57.902816 00019860 UTL default      supportVnodes            20
09/12 10:09:57.903819 00019860 UTL default      maxShellConns            50000
09/12 10:09:57.904816 00019860 UTL default      statusInterval           1
09/12 10:09:57.905816 00019860 UTL default      minSlidingTime           1
09/12 10:09:57.906816 00019860 UTL default      minIntervalTime          1
09/12 10:09:57.907815 00019860 UTL default      maxNumOfDistinctRes      10000000
09/12 10:09:57.908816 00019860 UTL default      countAlwaysReturnValue   1
09/12 10:09:57.910834 00019860 UTL default      queryBufferSize          -1
09/12 10:09:57.911815 00019860 UTL default      printAuth                0
09/12 10:09:57.912817 00019860 UTL default      queryRspPolicy           0
09/12 10:09:57.913816 00019860 UTL default      numOfRpcThreads          4
09/12 10:09:57.914815 00019860 UTL default      numOfRpcSessions         10000
09/12 10:09:57.916817 00019860 UTL default      timeToGetAvailableConn   10000
09/12 10:09:57.918053 00019860 UTL default      keepAliveIdle            60
09/12 10:09:57.918053 00019860 UTL default      numOfCommitThreads       4
09/12 10:09:57.919062 00019860 UTL default      numOfMnodeReadThreads    1
09/12 10:09:57.920061 00019860 UTL default      numOfVnodeQueryThreads   20
09/12 10:09:57.921061 00019860 UTL default      ratioOfVnodeStreamThrea  4.00
09/12 10:09:57.922060 00019860 UTL default      numOfVnodeFetchThreads   4
09/12 10:09:57.923092 00019860 UTL default      numOfVnodeRsmaThreads    10
09/12 10:09:57.924098 00019860 UTL default      numOfQnodeQueryThreads   20
09/12 10:09:57.925092 00019860 UTL default      numOfSnodeSharedThreads  2
09/12 10:09:57.926066 00019860 UTL default      numOfSnodeUniqueThreads  2
09/12 10:09:57.927093 00019860 UTL default      rpcQueueMemoryAllowed    1701904793
09/12 10:09:57.928093 00019860 UTL default      syncElectInterval        25000
09/12 10:09:57.929094 00019860 UTL default      syncHeartbeatInterval    1000
09/12 10:09:57.930062 00019860 UTL default      syncHeartbeatTimeout     20000
09/12 10:09:57.931062 00019860 UTL default      vndCommitMaxInterval     600000
09/12 10:09:57.932093 00019860 UTL default      mndSdbWriteDelta         200
09/12 10:09:57.933092 00019860 UTL default      mndLogRetention          2000
09/12 10:09:57.934095 00019860 UTL default      grantMode                0
09/12 10:09:57.935092 00019860 UTL default      skipGrant                0
09/12 10:09:57.936099 00019860 UTL default      monitor                  1
09/12 10:09:57.937094 00019860 UTL default      monitorInterval          30
09/12 10:09:57.938092 00019860 UTL default      monitorFqdn
09/12 10:09:57.939092 00019860 UTL default      monitorPort              6043
09/12 10:09:57.940093 00019860 UTL default      monitorMaxLogs           100
09/12 10:09:57.941092 00019860 UTL default      monitorComp              0
09/12 10:09:57.942092 00019860 UTL default      audit                    0
09/12 10:09:57.943093 00019860 UTL default      auditFqdn
09/12 10:09:57.944081 00019860 UTL default      auditPort                6043
09/12 10:09:57.944081 00019860 UTL default      crashReporting           1
09/12 10:09:57.945062 00019860 UTL default      telemetryReporting       1
09/12 10:09:57.946060 00019860 UTL default      telemetryInterval        43200
09/12 10:09:57.947062 00019860 UTL default      telemetryServer          telemetry.tdengine.com
09/12 10:09:57.949092 00019860 UTL default      telemetryPort            80
09/12 10:09:57.950092 00019860 UTL default      tmqMaxTopicNum           20
09/12 10:09:57.951090 00019860 UTL default      transPullupInterval      2
09/12 10:09:57.951090 00019860 UTL default      mqRebalanceInterval      2
09/12 10:09:57.952062 00019860 UTL default      ttlUnit                  86400
09/12 10:09:57.953062 00019860 UTL default      ttlPushInterval          10
09/12 10:09:57.954062 00019860 UTL default      ttlBatchDropNum          10000
09/12 10:09:57.956092 00019860 UTL default      ttlChangeOnWrite         0
09/12 10:09:57.957092 00019860 UTL default      ttlFlushThreshold        100
09/12 10:09:57.958098 00019860 UTL default      trimVDbIntervalSec       3600
09/12 10:09:57.959064 00019860 UTL default      uptimeInterval           300
09/12 10:09:57.959064 00019860 UTL default      queryRsmaTolerance       1000
09/12 10:09:57.960062 00019860 UTL default      walFsyncDataSizeLimit    104857600
09/12 10:09:57.961062 00019860 UTL default      udf                      0
09/12 10:09:57.963705 00019860 UTL default      udfdResFuncs
09/12 10:09:57.964729 00019860 UTL default      udfdLdLibPath
09/12 10:09:57.965704 00019860 UTL default      disableStream            0
09/12 10:09:57.966728 00019860 UTL default      streamBufferSize         134217728
09/12 10:09:57.967729 00019860 UTL default      checkpointInterval       20
09/12 10:09:57.968728 00019860 UTL default      cacheLazyLoadThreshold   500
09/12 10:09:57.969717 00019860 UTL default      filterScalarMode         0
09/12 10:09:57.969717 00019860 UTL default      keepTimeOffset           0
09/12 10:09:57.971704 00019860 UTL default      maxStreamBackendCache    128
09/12 10:09:57.972729 00019860 UTL default      pqSortMemThreshold       16
09/12 10:09:57.973730 00019860 UTL default      resolveFQDNRetryTime     100
09/12 10:09:57.974729 00019860 UTL default      s3Accesskey              <accesskey>
09/12 10:09:57.975730 00019860 UTL default      s3Endpoint               <endpoint>
09/12 10:09:57.976187 00019860 UTL default      s3BucketName             <bucketname>
09/12 10:09:57.977192 00019860 UTL default      minDiskFreeSize          52428800
09/12 10:09:57.978192 00019860 UTL default      configDir                C:\TDengine\cfg\
09/12 10:09:57.980192 00019860 UTL default      scriptDir                C:\TDengine\cfg\
09/12 10:09:57.981217 00019860 UTL default      logDir                   C:\TDengine\log\
09/12 10:09:57.982192 00019860 UTL default      minimalLogDirGB          1.00
09/12 10:09:57.983192 00019860 UTL default      numOfLogLines            10000000
09/12 10:09:57.984192 00019860 UTL default      asyncLog                 1
09/12 10:09:57.985192 00019860 UTL default      logKeepDays              0
09/12 10:09:57.987226 00019860 UTL default      debugFlag                0
09/12 10:09:57.988257 00019860 UTL default      simDebugFlag             143
09/12 10:09:57.989257 00019860 UTL default      tmrDebugFlag             131
09/12 10:09:57.990257 00019860 UTL default      uDebugFlag               131
09/12 10:09:57.991258 00019860 UTL default      rpcDebugFlag             131
09/12 10:09:57.992257 00019860 UTL default      jniDebugFlag             131
09/12 10:09:57.993258 00019860 UTL default      qDebugFlag               131
09/12 10:09:57.994260 00019860 UTL default      cDebugFlag               131
09/12 10:09:57.995258 00019860 UTL default      dDebugFlag               131
09/12 10:09:57.996259 00019860 UTL default      vDebugFlag               131
09/12 10:09:57.997258 00019860 UTL default      mDebugFlag               131
09/12 10:09:57.998259 00019860 UTL default      wDebugFlag               131
09/12 10:09:57.999257 00019860 UTL default      sDebugFlag               131
09/12 10:09:58.000258 00019860 UTL default      tsdbDebugFlag            131
09/12 10:09:58.001259 00019860 UTL default      tqDebugFlag              131
09/12 10:09:58.002264 00019860 UTL default      fsDebugFlag              131
09/12 10:09:58.004257 00019860 UTL default      udfDebugFlag             131
09/12 10:09:58.005232 00019860 UTL default      smaDebugFlag             131
09/12 10:09:58.006231 00019860 UTL default      idxDebugFlag             131
09/12 10:09:58.007258 00019860 UTL default      tdbDebugFlag             131
09/12 10:09:58.008245 00019860 UTL default      metaDebugFlag            131
09/12 10:09:58.008245 00019860 UTL default      timezone                 Asia/Shanghai (UTC, +0800)
09/12 10:09:58.010257 00019860 UTL default      locale                   en_US.UTF-8
09/12 10:09:58.011257 00019860 UTL default      charset                  UTF-8
09/12 10:09:58.012257 00019860 UTL default      assert                   1
09/12 10:09:58.013236 00019860 UTL default      enableCoreFile           1
09/12 10:09:58.014263 00019860 UTL default      numOfCores               10.00
09/12 10:09:58.015266 00019860 UTL default      SSE42                    0
09/12 10:09:58.016263 00019860 UTL default      AVX                      0
09/12 10:09:58.017265 00019860 UTL default      AVX2                     0
09/12 10:09:58.018815 00019860 UTL default      FMA                      0
09/12 10:09:58.019852 00019860 UTL default      SIMD-builtins            0
09/12 10:09:58.020850 00019860 UTL default      tagFilterCache           0
09/12 10:09:58.021852 00019860 UTL default      openMax                  0
09/12 10:09:58.021852 00019860 UTL default      streamMax                0
09/12 10:09:58.022821 00019860 UTL default      pageSizeKB               0
09/12 10:09:58.023822 00019860 UTL default      totalMemoryKB            16620164
09/12 10:09:58.024822 00019860 UTL default      os sysname               Windows_NT
09/12 10:09:58.025822 00019860 UTL default      os nodename              DESKTOP-DMDB3AR
09/12 10:09:58.026822 00019860 UTL default      os release               6
09/12 10:09:58.027821 00019860 UTL default      os version               2
09/12 10:09:58.029822 00019860 UTL default      os machine               AMD64
09/12 10:09:58.030821 00019860 UTL default      version                  3.1.1.0
09/12 10:09:58.031852 00019860 UTL default      compatible_version       3.0.0.0
09/12 10:09:58.032853 00019860 UTL default      gitinfo                  1bce2b7d0e2d6b82658c8d237473e52a763593fc
09/12 10:09:58.034846 00019860 UTL default      buildinfo                Built at 2023-09-01 17:01:30
09/12 10:09:58.035852 00019860 UTL =================================================================
09/12 10:09:58.040851 00019860 DND start to init dnode env
09/12 10:09:58.042852 00019860 DND ERROR failed to init dnode since unsupported platform, please visit https://www.taosdata.com for support

**Comment by yu285** [comment]
3.1.0.0 后 windows 属于企业版范畴了，如果非要在windows 使用：

建议在win上装docker

最好还是使用 linux
