### ISSUE TITLE
insert data into super table is not supported

### ISSUE THREAD

**Issue by zhuyanlao** [taosdata/TDengine#22865]
为什么批量新增数据，不能直接inset into test.meters插入超级表，自己动态去创建或插入子表，查询select test.meters可以，插入只能insert into test.d0插入子表，感觉很不方便

**Comment by yu285** [comment]
这个你看下文档吧。有提供自动建表的功能。

**Comment by zhuyanlao** [comment]
库test,超级表meters，子表d0
目前不能直接根据test.meters插入数据，是还需要什么配置吗







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taosdata/TDengine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月12日(星期二) 下午5:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [taosdata/TDengine] insert data into super table is not supported (Issue #22865)





 
这个你看下文档吧。有提供自动建表的功能。

**Comment by zhuyanlao** [comment]
![1694512413816](https://github.com/taosdata/TDengine/assets/38239956/e6032bed-aa17-491b-a2a1-708b7b4b47d3)

**Comment by zhuyanlao** [comment]
![1694512413816](https://github.com/taosdata/TDengine/assets/38239956/6eaa0ece-67c4-4c1a-8eb1-54a52790565f)

**Comment by zyk492322922** [comment]
我也遇到这个问题了，   用的  3.0.7.1的windows版本，     3.3.2.0 linux版本  却没有这个问题，      还有，  windows版在3.0.7.1后在怎么没了

**Comment by zyk492322922** [comment]
> ![1694512413816](https://private-user-images.githubusercontent.com/38239956/267290199-6eaa0ece-67c4-4c1a-8eb1-54a52790565f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDg3MTIsIm5iZiI6MTcyNjA0ODQxMiwicGF0aCI6Ii8zODIzOTk1Ni8yNjcyOTAxOTktNmVhYTBlY2UtNjdjNC00YzFhLThlYjEtNTRhNTI3OTA1NjVmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA5NTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzZGM1OTE2ZTE2OTQ5OGJmMmQ3ZjFkMDM2ZWVkZmFmYmI3ZDc2OTM5MmFjODI1NWRjY2Q2NTllOGE1YzBkMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4mWsKPkCMo1GKWeKJXMMtxoRFVYVv4v7S0srjc1bkbI)

大佬，   问题解决了没有
