### ISSUE TITLE
upgrade version 1.6.6.0 from version 1.6.5.6：result of taoshell query is different from tdconnetor query?

### ISSUE THREAD

**Issue by sexbee** [taosdata/TDengine#2287]
**Bug Description**
upgrade version 1.6.6.0 from version 1.6.5.6：result of taoshell query is different from tdconnetor query?
~~~~~~~~~~~~~~~~~~~~~~~~~
result of taoshell query :

112|23|3|4
~~~~~~~~~~~~~~~~~~~~~~~
result of tdconnector query 
1.334444555555456467e+25
6.978653786439856332e+24
...

**Comment by Aries-Lee1991** [comment]
Ok, we'll check it.

**Comment by sexbee** [comment]
降级到1.6.5.9就nomal了。

**Comment by plum-lihui** [comment]
是对原有插入的数据查询出现这个问题吗？
如果升级到V1.6.6.0后，再插入一条新的数据后，使用两种方式查询出来的结果相同吗？

**Comment by sexbee** [comment]
插入没问题，升级到1660后，查询结果不一样，我的推测，可能是1660版的某些数据格式或路径改变，而nodejs的tdconnector里面没有相应调整。

**Comment by plum-lihui** [comment]
我的意思是升级到V1.6.6.0版本后，新插入一些数据，再在连接器中查询 和 shell中查询 这些新插入的数据，两种方式查询出来的结果相同，还是也是不同？

**Comment by sexbee** [comment]
Sorry 耽搁了几天，是这样的，之前发现不一样，就是升级1.6.6.0后最新插入的数据。

**Comment by sexbee** [comment]
而且不仅数据变了，甚至有跨列错乱现象，所以推测nodejs的tdconnector的查询规则 是不是没有随版本改变而调整。

**Comment by localvar** [comment]
由于2.0已于上月发布，我们对1.6的支持将会减少，所以现在关闭这个问题。请您试试2.0版是否仍存在这个问题，是的话，请新建一个问题，谢谢。
