### ISSUE TITLE
QRY ERROR taosHashGet hb connection failed

### ISSUE THREAD

**Issue by jandison** [taosdata/TDengine#22896]
OS: CentOS 7.6
Memory 385G, CPU 64C, current Disk Space 132G used
TDengine Version 3.1.0.3

运行一段时间后会出现 QRY ERROR taosHashGet hb connection failed, nodeId:2, fqdn:taos.node1, port:6030 报错
报错时会出现写入流量下降。

**Comment by sangshuduo** [comment]
建议升级到最新版本，新版本已经不作为错误处理，对功能没有影响
