### ISSUE TITLE
支持与Grafana集成吗？

### ISSUE THREAD

**Issue by dingrui37** [taosdata/TDengine#229]
支持与Grafana集成吗？

**Comment by nonamexz** [comment]
支持，使用方法你可以参考官方这个文档：
https://www.taosdata.com/blog/2019/07/10/%e4%bd%bf%e7%94%a8tdengine%e5%bf%ab%e9%80%9f%e6%90%ad%e5%bb%ba%e8%bf%90%e7%bb%b4%e7%9b%91%e6%b5%8b%e7%b3%bb%e7%bb%9f/

**Comment by dingrui37** [comment]
多谢
