### ISSUE TITLE
 stream computing "trigger max_delay" time not work

### ISSUE THREAD

**Issue by yogaxu** [taosdata/TDengine#22917]
**Bug Description**
创建流式计算时 state_window 的参数字段出现在 partition by 后面，会导致 trigger max_delay time 到时间不触发

**To Reproduce**
```sql
CREATE STABLE IF NOT EXISTS test(create_time timestamp, record_time timestamp, s1 int) TAGS (t1 nchar(50));

CREATE STREAM IF NOT EXISTS test_s 
FILL_HISTORY 1 IGNORE EXPIRED 0 TRIGGER MAX_DELAY 10s 
INTO test_s1 SUBTABLE(CONCAT(tbname, '_s1')) AS
SELECT _wstart AS                   alarm_begin_time,
       _wend AS                     alarm_end_time,
       _wduration AS                alarm_duration,
    count(*) AS record_count,
    t1, s1
FROM test PARTITION BY tbname, t1, s1 STATE_WINDOW(s1);

INSERT INTO test_001 USING test TAGS('001') VALUES('2023-09-15 09:00:00','2023-09-15 09:00:00',1) ('2023-09-15 09:00:01','2023-09-15 09:00:01',2);

SELECT * FROM test_001;
-- 这里查询出来只有一条数据，正常10秒触发是两条
SELECT * FROM test_001_s1;

INSERT INTO test_001 USING test tags('001') VALUES('2023-09-15 09:00:03','2023-09-15 09:00:03',3);

SELECT * FROM test_001;
-- 再次查询依旧是一条
SELECT * FROM test_001_s1;
```

**Expected Behavior**
-- partition by 后面不带 s1 就可以触发
CREATE STREAM IF NOT EXISTS test_s
FILL_HISTORY 1 IGNORE EXPIRED 0 TRIGGER MAX_DELAY 10s
INTO test_s1 SUBTABLE(CONCAT(tbname, '_s1')) AS
SELECT _wstart AS                   alarm_begin_time,
       _wend AS                     alarm_end_time,
       _wduration AS                alarm_duration,
    count(*) AS record_count,
    t1, s1
FROM test PARTITION BY tbname, t1 STATE_WINDOW(s1);

**Environment (please complete the following information):**
 - OS: Win10客户端 + CentOS7服务端/Docker服务端
 - Memory, CPU, current Disk Space
 - TDengine Version: 3.0.6.0/3.1.0.1

**Additional Context**
这块需要在创建时报语法异常

**Comment by sangshuduo** [comment]
谢谢报告，在修复中

**Comment by yu285** [comment]
问题已修复，烦请验证。咱做关闭处理，如果问题仍在请联系微信a15652223354
