### ISSUE TITLE
在golang中编译报错

### ISSUE THREAD

**Issue by Sunziqi1028** [taosdata/TDengine#22921]
**Bug Description**
在golang中编译报错

**To Reproduce**
1. 执行 CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o opc_test main.go
2. See github.com/taosdata/driver-go/v3/wrapper: build constraints exclude all Go files in /Users/Sun/go/pkg/mod/github.com/taosdata/driver-go/v3@v3.5.0/wrapper

**Expected Behavior**
正常编译

**Screenshots**
<img width="1362" alt="image" src="https://github.com/taosdata/TDengine/assets/58042498/454d1019-f4fa-447e-9f51-4b3673cb6acf">

**Environment (please complete the following information):**
 - OS: mac M1 13.5.1
 - golang version: go1.21.0 darwin/arm64
 - TDengine driverVersion: github.com/taosdata/driver-go/v3/taosSql

**Additional Context**

**Comment by sangshuduo** [comment]
go mod init
go mod tidy
go build

**Comment by nieqiangnote** [comment]
现在还是存在这个问题, FROM golang:1.21-alpine as builder 作为基础镜像，还是出现楼主一样的问题

**Comment by nieqiangnote** [comment]
> 必须启用 CGO，启用了 CGO 不能跨平台.可以使用 WebSocket 或者 REST

哥，最后是怎么解决的呢
