### ISSUE TITLE
磁盘空间满后，系统异常后再也无法启动。是否可以绕过损坏文件启动。

### ISSUE THREAD

**Issue by trytowish** [taosdata/TDengine#22930]
server版本是3.0.2.0版本，单机运行，一个数据库分配2个vnode节点。
运行期间发现磁盘空间满后，服务异常，不断重启。经过清理磁盘空间后，服务仍然不断重启，启动不了。通过日志发现数据库的一个Vnode节点报异常。

09/15 16:19:13.027999 00000083 TSD ERROR vgId:3, tsdbScanAndTryFixFS failed at line 199 since No such file or directory, fid:1099
09/15 16:19:13.028211 00000083 TSD ERROR vgId:3, tsdbFSOpen failed at line 791 since No such file or directory

后面经过替换或者增加1099的文件都无法正常启动。

想请问下是否可以修改扫描DB的文件，跳过扫描文件ID 1099的head和data。 这样是否可以就能启动服务？
如果能，需要修改什么地方？

**Comment by yu285** [comment]
应该是不可以的。
