### ISSUE TITLE
使用官网提供的arm架构的安装包在arm架构服务器上安装，启动失败，提示unsupported platform

### ISSUE THREAD

**Issue by guojihong** [taosdata/TDengine#22951]
**Bug Description**
使用官网提供的arm架构的安装包在arm架构服务器上安装，启动失败，提示unsupported platform

**To Reproduce**
官网下载的3.1.0.3的arm架构的安装包
安装后启动提示unsupported platform

安装的服务器信息：麒麟系统，arm64架构

是否目前不支持麒麟系统 arm64架构的平台

**Comment by sangshuduo** [comment]
https://docs.taosdata.com/reference/support-platform/

**Comment by hualaihu** [comment]
@guojihong，后来你是怎么解决的？买的企业版本嘛？
