### ISSUE TITLE
使用命令可以删除stream, 使用rest客户端就不能，事务总是未完成状态。

### ISSUE THREAD

**Issue by lulg** [taosdata/TDengine#22952]
我们用的版本是3.0.4.0
使用命令可以删除stream, 使用rest客户端就不能，事务总是未完成状态。得手动杀掉事务才算完成删除。
![image](https://github.com/taosdata/TDengine/assets/28698352/85c74e26-9bfc-4a3e-a666-541d0de90c31)

**Comment by lulg** [comment]
很奇怪，后来又复现不出来了

**Comment by yu285** [comment]
请使用最新版本的流计算 ： 3.2.1.0
