### ISSUE TITLE
td 3.1.0.3 order by之后无法获取正确的值

### ISSUE THREAD

**Issue by Chenzhiling** [taosdata/TDengine#22966]
我想获取一段时间内的最后一条数据，使用order by ts desc limit 1去实现。
输入不同时间区段，结果不同。
ts在2023-09-18 07:00:00到2023-09-19 03:00:00时间段内可以获得正确的数据，如下图
![1](https://github.com/taosdata/TDengine/assets/45333368/4c25185a-ced1-4666-968a-02448d5bb2f7)
ain/bug/1.png)
ts在2023-09-18 17:00:00到2023-09-19 03:00:00时间段内无法获得正确的数据，如下图
![2](https://github.com/taosdata/TDengine/assets/45333368/4d94c95d-e992-4755-956d-484926c1640b)
如果按照quantity字段去order by，数据是正常的，不知道是什么原因导致，希望可以帮忙解决。
这是表中导出的数据
[data.csv](https://github.com/taosdata/TDengine/files/12655274/data.csv)

**Comment by yu285** [comment]
我们来验证一下

**Comment by yu285** [comment]
这个环境是从旧版本升级上来的吗？还是直接部署的新的3.1.0.3

**Comment by Chenzhiling** [comment]
直接部署的3.1.0.3

**Comment by yu285** [comment]
可以升级到 3.2.1.0 ，如果还有问题直接联系我即可：微信 a15652223354
