### ISSUE TITLE
 An exception of Taos.dll in .net, Windows caused the application to quit

### ISSUE THREAD

**Issue by wb4ufox** [taosdata/TDengine#2297]
**Bug Description**
Taos.dll使用异常

**To Reproduce**
1、应用程序中有线程专门执行写入TDengine
2、任务不重，1秒大约执行300条左右写入左右
3、通过日志发现异常前插入SQL失败
4、将日志中的出错SQL在终端中写入可以正常写入
5、异常时间一般在半小时左右，也有特殊情况，5分钟就异常了
6、SQL语句
insert into Y41_66_T2002 (TS,P01,P02,P03,P04,P05,P06,P07,P08,P09,P10,P11,P12,P13,P14) values ('2020-06-16 09:45:22.252',238.90,238.90,239.90,29.39,30.39,29.89,2.76,21.26,21.44,0.00,49.95,0.00,0.12,0.00)
7、SQL出错原因
reason: not active table(not created yet or dropped already)

**Environment (please complete the following information):**
数据库服务器 
- OS:  CentOS 7.7
 - 128G, xeon 2.4, 1T
 - TDengine Version  1.6.1.9

应用服务器
- OS:  windows 2012 server
- 16G, xeon 2.13, 100G
- Taos.dll
-.NET Core 3.1

**Comment by wb4ufox** [comment]
笔误，应该是TDengine Version 1.6.5.9

**Comment by wb4ufox** [comment]
有的SQL出现failure, reason: invalid table id错误，把SQL语句单独拷贝到终端运行可以插入成功，这个错误没有触发异常退出。

**Comment by Aries-Lee1991** [comment]
多谢反馈，我们这边看一下。

**Comment by wb4ufox** [comment]
![错误信息](https://user-images.githubusercontent.com/64847191/84760159-3854fc80-affa-11ea-98cd-0958dc948d3e.png)
![错误信息1](https://user-images.githubusercontent.com/64847191/84760287-633f5080-affa-11ea-8b65-ecaa8ba68236.png)

**Comment by wb4ufox** [comment]
![错误信息](https://user-images.githubusercontent.com/64847191/84760583-d5179a00-affa-11ea-9803-65917a17eeda.jpg)

**Comment by wb4ufox** [comment]
![错误信息1](https://user-images.githubusercontent.com/64847191/84760821-2889e800-affb-11ea-8a38-d421b785ac62.jpg)
