### ISSUE TITLE
insert with jdbc,cache not updated

### ISSUE THREAD

**Issue by hb0902** [taosdata/TDengine#22982]
超级表：
CREATE STABLE `testtable` (`_ts` TIMESTAMP, `col1` FLOAT, `col2` FLOAT) TAGS (`tag1` NCHAR(32))
子表：
CREATE TABLE `testsubtable1` USING `testtable` (`tag1`) TAGS ("1234")
 
用jdbc的pstmt写入的数据后，
 
![image](https://github.com/taosdata/TDengine/assets/20200057/e0c38287-dff1-4a9c-b1d5-200e5a807ff5)

用select last(_ts),last(col1),last(col2) from `testTable` group by tag1查询，
last(col1)的值不更新，
taos客户端写入的数据查询没有问题

写入代码：
	 private static Connection conn=null;
	 private static Statement stmt=null;
	 private static PreparedStatement pstmt=null;
	 
	 public static void  insert(){
		 if(conn==null){
			 try {
				conn=getConnection();
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		 }
		 String psql="INSERT INTO ? VALUES(?,?,?)";
		 TSDBPreparedStatement pst;
		try {
			pst = (TSDBPreparedStatement)conn.prepareStatement(psql);
			pst.setTableName("testsubtable1");
			pst.setTimestamp(0, tsToLongArray("2023-01-03 00:00:00.000"));
			pst.setFloat(1, toArray(Float.valueOf("3.2")));
			pst.setFloat(2, toArray(Float.valueOf("3.2")));
			pst.columnDataAddBatch();
			pst.columnDataExecuteBatch();
			pst.close();
		} catch (SQLException e) {
			System.out.println(e.getMessage());
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	 }
	 public static ArrayList<Long> tsToLongArray(String ts) {
		    ArrayList<Long> result = new ArrayList<>();
		    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.SSS");
		    LocalDateTime localDateTime = LocalDateTime.parse(ts, formatter);
		    result.add(Long.valueOf(localDateTime.toInstant(ZoneOffset.of("+8")).toEpochMilli()));
		    return result;
		  }
	 public static <T> ArrayList<T> toArray(T v) {
		    ArrayList<T> result = new ArrayList<>();
		    result.add(v);
		    return result;
		  }

**Comment by gccgdb1234** [comment]
不要用 last 查询，直接查询用 JDBC (STMT) 写入的数据能查询到吗？

**Comment by hb0902** [comment]
> 不要用 last 查询，直接查询用 JDBC (STMT) 写入的数据能查询到吗？

可以的，数据是可以查的到的，只有第一列有问题，

**Comment by yu285** [comment]
麻烦升级新版本吧，3.3.2.0，问题都解决了
