### ISSUE TITLE
关于tdengine备份的问题

### ISSUE THREAD

**Issue by elysian-gc** [taosdata/TDengine#22984]
问题1： 备份速度慢

3副本集群，2c4g，一个超级表有13w子表，采用THREAD_NUM=8备份需要1.5h左右。

问题2： 备份时cpu明显增高；

平常使用中，cpu一般在5%左右，但是备份时，cpu在90%~100%，为了备份而扩容机器不是一个好的方法。

请问有无好的备份方案，既能保证速度，又能保证cpu的消耗不徒增。

**Comment by gccgdb1234** [comment]
明确回复：没有
既想要备份速度还想省资源，那是不可能的事情
2核4G的配置本身也太差了。
