### ISSUE TITLE
java JNI使用last函数返回字段名不对

### ISSUE THREAD

**Issue by zhuyanlao** [taosdata/TDengine#22985]
![image](https://github.com/taosdata/TDengine/assets/38239956/4b73fdef-4659-4924-ae01-bd5521988df4)
使用java JNI的方式查询，last函数最后返回的字段名是一个id值，而不是想要的字段名
sever版本3.1.1.0-Linux
taos-jdbcdriver 3.2.5

**Comment by sheyanjie-qq** [comment]
这个不是java连接器的bug，是TDengine的bug，使用taos shell也会有这个问题
TDengine会在3.2.0.0修复，需要的话请及时关注并升级TDengine版本
