### ISSUE TITLE
网络是wifi状态时，启动不起来

### ISSUE THREAD

**Issue by fivetrees** [taosdata/TDengine#230]
root@wj:/mnt/c/senlin/work/yunwei/TDengine/build# ./build/bin/taosd -c test/cfg/taos.cfg
option file:test/cfg/taos.cfg/taos.cfg not found, all options are set to system default
07/30 14:59:26.927823 7fd5b6700b80 ERROR UTL open file:/proc/2268/io failed
07/30 14:59:26.928707 7fd5b6700b80 UTL timezone not configured, set to system default:Asia/Shanghai (CST, +0800)
07/30 14:59:26.930170 7fd5b6700b80 UTL locale not configured, set to system default:C.UTF-8
07/30 14:59:26.930524 7fd5b6700b80 UTL charset not configured, set to system default:UTF-8
07/30 14:59:26.930852 7fd5b6700b80 UTL    taos config & system info:
07/30 14:59:26.931135 7fd5b6700b80 UTL ==================================
07/30 14:59:26.931394 7fd5b6700b80 UTL  internalIp:             169.254.45.28
07/30 14:59:26.931757 7fd5b6700b80 UTL  serverIp:               0.0.0.0
07/30 14:59:26.932026 7fd5b6700b80 UTL  localIp:                0.0.0.0
07/30 14:59:26.932319 7fd5b6700b80 UTL  httpIp:                 0.0.0.0
07/30 14:59:26.932576 7fd5b6700b80 UTL  httpPort:               6020
07/30 14:59:26.932827 7fd5b6700b80 UTL  mgmtShellPort:          6030
07/30 14:59:26.933086 7fd5b6700b80 UTL  vnodeShellPort:         6035
07/30 14:59:26.933389 7fd5b6700b80 UTL  configDir:              test/cfg/taos.cfg
07/30 14:59:26.933725 7fd5b6700b80 UTL  dataDir:                /var/lib/taos
07/30 14:59:26.933948 7fd5b6700b80 UTL  logDir:                 /var/log/taos
07/30 14:59:26.934230 7fd5b6700b80 UTL  scriptDir:              /etc/taos
07/30 14:59:26.934586 7fd5b6700b80 UTL  numOfThreadsPerCore:    1.000000
07/30 14:59:26.934877 7fd5b6700b80 UTL  ratioOfQueryThreads:    0.500000
07/30 14:59:26.935131 7fd5b6700b80 UTL  numOfVnodesPerCore:     8
07/30 14:59:26.935404 7fd5b6700b80 UTL  numOfTotalVnodes:       0
07/30 14:59:26.935783 7fd5b6700b80 UTL  tables:                 1000
07/30 14:59:26.936124 7fd5b6700b80 UTL  cache:                  16384(byte)
07/30 14:59:26.936463 7fd5b6700b80 UTL  rows:                   4096
07/30 14:59:26.936774 7fd5b6700b80 UTL  fileBlockMinPercent:    0.050000
07/30 14:59:26.937027 7fd5b6700b80 UTL  ablocks:                4
07/30 14:59:26.937332 7fd5b6700b80 UTL  tblocks:                100
07/30 14:59:26.937624 7fd5b6700b80 UTL  monitorInterval:        30(s)
07/30 14:59:26.937920 7fd5b6700b80 UTL  rpcTimer:               300(ms)
07/30 14:59:26.938200 7fd5b6700b80 UTL  rpcMaxTime:             600(s)
07/30 14:59:26.938474 7fd5b6700b80 UTL  ctime:                  3600(s)
07/30 14:59:26.938740 7fd5b6700b80 UTL  statusInterval:         1(s)
07/30 14:59:26.938963 7fd5b6700b80 UTL  shellActivityTimer:     3(s)
07/30 14:59:26.939237 7fd5b6700b80 UTL  meterMetaKeepTimer:     7200(s)
07/30 14:59:26.939463 7fd5b6700b80 UTL  metricMetaKeepTimer:    600(s)
07/30 14:59:26.939671 7fd5b6700b80 UTL  maxUsers:               1000
07/30 14:59:26.939924 7fd5b6700b80 UTL  maxDbs:                 1000
07/30 14:59:26.940148 7fd5b6700b80 UTL  maxTables:              650000
07/30 14:59:26.940458 7fd5b6700b80 UTL  maxVGroups:             1000
07/30 14:59:26.940749 7fd5b6700b80 UTL  minSlidingTime:         10(ms)
07/30 14:59:26.940903 7fd5b6700b80 UTL  minIntervalTime:        10(ms)
07/30 14:59:26.941102 7fd5b6700b80 UTL  maxStreamCompDelay:     20000(ms)
07/30 14:59:26.941285 7fd5b6700b80 UTL  maxFirstStreamCompDelay:10000(ms)
07/30 14:59:26.941502 7fd5b6700b80 UTL  retryStreamCompDelay:   10(ms)
07/30 14:59:26.941769 7fd5b6700b80 UTL  clog:                   1
07/30 14:59:26.942007 7fd5b6700b80 UTL  comp:                   2
07/30 14:59:26.942293 7fd5b6700b80 UTL  days:                   10
07/30 14:59:26.942634 7fd5b6700b80 UTL  keep:                   3650
07/30 14:59:26.942838 7fd5b6700b80 UTL  defaultDB:
07/30 14:59:26.943101 7fd5b6700b80 UTL  defaultUser:            root
07/30 14:59:26.943300 7fd5b6700b80 UTL  defaultPass:            taosdata
07/30 14:59:26.943535 7fd5b6700b80 UTL  timezone:               Asia/Shanghai (CST, +0800)
07/30 14:59:26.943863 7fd5b6700b80 UTL  locale:                 C.UTF-8
07/30 14:59:26.944162 7fd5b6700b80 UTL  charset:                UTF-8
07/30 14:59:26.944368 7fd5b6700b80 UTL  maxShellConns:          2000
07/30 14:59:26.944550 7fd5b6700b80 UTL  maxMeterConnections:    10000
07/30 14:59:26.944731 7fd5b6700b80 UTL  maxMgmtConnections:     2000
07/30 14:59:26.944882 7fd5b6700b80 UTL  maxVnodeConnections:    10000
07/30 14:59:26.945097 7fd5b6700b80 UTL  enableHttp:             1
07/30 14:59:26.945364 7fd5b6700b80 UTL  enableMonitor:          1
07/30 14:59:26.945577 7fd5b6700b80 UTL  httpCacheSessions:      2000
07/30 14:59:26.945917 7fd5b6700b80 UTL  httpMaxThreads:         2
07/30 14:59:26.946254 7fd5b6700b80 UTL  numOfLogLines:          10000000
07/30 14:59:26.946533 7fd5b6700b80 UTL  asyncLog:               1
07/30 14:59:26.946808 7fd5b6700b80 UTL  debugFlag:              131
07/30 14:59:26.947069 7fd5b6700b80 UTL  mDebugFlag:             135
07/30 14:59:26.947355 7fd5b6700b80 UTL  dDebugFlag:             131
07/30 14:59:26.947692 7fd5b6700b80 UTL  sdbDebugFlag:           135
07/30 14:59:26.947963 7fd5b6700b80 UTL  taosDebugFlag:          131
07/30 14:59:26.948202 7fd5b6700b80 UTL  tmrDebugFlag:           131
07/30 14:59:26.948432 7fd5b6700b80 UTL  cDebugFlag:             131
07/30 14:59:26.948617 7fd5b6700b80 UTL  jniDebugFlag:           131
07/30 14:59:26.948844 7fd5b6700b80 UTL  odbcDebugFlag:          131
07/30 14:59:26.949159 7fd5b6700b80 UTL  uDebugFlag:             131
07/30 14:59:26.949462 7fd5b6700b80 UTL  httpDebugFlag:          131
07/30 14:59:26.949877 7fd5b6700b80 UTL  monitorDebugFlag:       131
07/30 14:59:26.950214 7fd5b6700b80 UTL  qDebugFlag:             131
07/30 14:59:26.950504 7fd5b6700b80 UTL  gitinfo:                ddcb2519e895c2e2101089aedaf529cee5cefe04
07/30 14:59:26.950801 7fd5b6700b80 UTL  buildinfo:              Built by plum at 2019-07-29 10:41
07/30 14:59:26.951065 7fd5b6700b80 UTL  version:                1.6.1.2
07/30 14:59:26.951488 7fd5b6700b80 UTL  dataDir:                /var/lib/taos
07/30 14:59:26.951777 7fd5b6700b80 UTL  os pageSize:            4096(KB)
07/30 14:59:26.952022 7fd5b6700b80 UTL  os openMax:             1024
07/30 14:59:26.952275 7fd5b6700b80 UTL  os streamMax:           16
07/30 14:59:26.952566 7fd5b6700b80 UTL  os numOfCores:          8
07/30 14:59:26.952877 7fd5b6700b80 UTL  os totalDisk:           238(GB)
07/30 14:59:26.953146 7fd5b6700b80 UTL  os totalMemory:         16268(MB)
07/30 14:59:26.953362 7fd5b6700b80 UTL  os sysname:             Linux
07/30 14:59:26.953616 7fd5b6700b80 UTL  os nodename:            wj
07/30 14:59:26.953828 7fd5b6700b80 UTL  os release:             4.4.0-18362-Microsoft
07/30 14:59:26.954080 7fd5b6700b80 UTL  os version:             #1-Microsoft Mon Mar 18 12:02:00 PST 2019
07/30 14:59:26.954341 7fd5b6700b80 UTL  os machine:             x86_64
07/30 14:59:26.954528 7fd5b6700b80 UTL ==================================
07/30 14:59:26.954725 7fd5b6700b80 DND Server IP address is:169.254.45.28
07/30 14:59:26.954897 7fd5b6700b80 DND starting to initialize TDengine engine ...
07/30 14:59:26.956905 7fd5b6700b80 ERROR UTL setsockopt SO_NO_CHECK failed: 92 (Protocol not available)
07/30 14:59:26.964227 7fd5b6700b80 ERROR UTL setsockopt SO_NO_CHECK failed: 92 (Protocol not available)
07/30 14:59:26.964571 7fd5b6700b80 ERROR DND failed to init connection to shell
07/30 14:59:26.964953 7fd5b6700b80 ERROR DND failed to init communication to shell
07/30 14:59:26.965167 7fd5b6700b80 ERROR DND TDengine vnodes initialization failed
07/30 14:59:26.965419 7fd5b6700b80 HTP http service cleanup
07/30 14:59:26.965631 7fd5b6700b80 MON dnode:169.254.45.28 is stopped
07/30 14:59:26.965856 7fd5b6700b80 MON monitor service cleanup
07/30 14:59:26.966092 7fd5b6700b80 MON dnode:169.254.45.28 is stopped
root@wj:/mnt/c/senlin/work/yunwei/TDengine/build#

**Comment by guanshengliang** [comment]
可能这个网卡不支持SO_NO_CHECK选项，尝试将tsocket.c中的代码行注释掉
```
 if (taosSetSockOpt(sockFd, SOL_SOCKET, SO_NO_CHECK, (void *)&nocheck, sizeof(nocheck)) < 0) {
    pError("setsockopt SO_NO_CHECK failed: %d (%s)", errno, strerror(errno));
    close(sockFd);
    return -1;
  }
```
