### ISSUE TITLE
Taosd service failed to start

### ISSUE THREAD

**Issue by nieyuan1980** [taosdata/TDengine#23029]
**Bug Description**
Taosd service failed to start

**To Reproduce**
1.execute command：systemctl start taosd

2.Active: failed

3.execute command：taosd

4.failed to create table:t metxjjszxnsb1 481 cd636655847d6a074df8cf0ef4fc type: child table since 0ut of Memory

I think streaming computing caused this problem

**Screenshots**
 
![01](https://github.com/taosdata/TDengine/assets/25432482/8599e87b-4739-4bcb-9b51-166d80f745ea)

![02](https://github.com/taosdata/TDengine/assets/25432482/6824b743-53f3-4de9-8a59-ea23476bb22a)

**Environment (please complete the following information):**
 - OS: CentOS 7.0
 - Memory: 6G
 - CPU: 2cores\2.5G 
 - Disk space available：24G
 - TDengine Version: 3.1.1.0

**Comment by yu285** [comment]
does this taosd upgraded from a previous version?

**Comment by yu285** [comment]
如果还需要处理：可以加我微信远程排查一下

a15652223354
