### ISSUE TITLE
关于wal清理机制的问题

### ISSUE THREAD

**Issue by chengkm** [taosdata/TDengine#23034]
不管是在这篇博客https://www.taosdata.com/tdengine-engineering/6062.html 还是官方文档中都有提到“vnode通过WAL记录了数据和表的元数据，并且会在落盘触发后清零”.
但在实际测试中(3.1.1.0版本),在停止数据写入且查询到的数据数量和插入数量相等的情况下(也就证明数据落盘到了tsdb下),不管是重启taosd进程还是手动执行flush database后vnode目录下的wal依旧没有清零,文件大小和实际未压缩前的大小差不多.请问下vnode下的wal到底在什么情况下会触发删除操作?因为wal是未压缩前的数据,数据量大的时候如果不能及时清理会非常占用空间.

**Comment by yu285** [comment]
3.0引入了额外的保留策略：在文档的建库章节可以看到
