### ISSUE TITLE
关于多线程并发访问数据库的问题

### ISSUE THREAD

**Issue by cixiancong01** [taosdata/TDengine#23044]
**关于多线程并发访问数据库的问题**
您好，我刚开始接触TDengine，在使用开源版本进行使用测试的过程中（java调用），遇到几次下面的问题：
1.大概有50到100个左右线程在并发查询数据库时，偶发的会出现其中某个线程执行过程中，不返回结果了，像是锁死了一样；
2. 上述现像发生后，后续的线程也同样的发生卡死；
3.  在这个过程中，我通过命令窗口中访问数据库，发现在输入任意查询语句时，同样也是无反馈；
4. 出现上述问题后，在系统服务中，taos的服务也无法手动完成重启或是停止；

这个问题，不是每次都出现，偶尔会发生；所以我想咨询下可能的原因；

我的使用环境是：
系统平台：Windows Server 2016
开发语言：java
数据库版本：3.0.4

**Comment by yu285** [comment]
3.1.0.0 开始，只有企业版有win 服务端了，建议：

1.在windows 上部署docker，使用linux版本

2.切换到linux版本

3.0.4.0 和现在有一定的性能差距，建议先切换平台，然后再做测试——我的微信 a15652223354
