### ISSUE TITLE
 CentOS Stream release 8 ERROR failed to init dnode since unsupported platform

### ISSUE THREAD

**Issue by watchpoints** [taosdata/TDengine#23056]
code: master
git clone TDengine.git

centos：

 cat /etc/redhat-release
 CentOS Stream release 8

![image](https://github.com/taosdata/TDengine/assets/5937331/a0eb43b6-8c83-4bdf-90d1-b74072488981)

**Comment by watchpoints** [comment]
9/26 11:15:24.369921 00002082 UTL apoll url not load
09/26 11:15:24.370032 00002082 UTL load from cfg file /etc/taos//taos.cfg success
09/26 11:15:24.370052 00002082 UTL env file:.env not load
09/26 11:15:24.370058 00002082 UTL load from env variables cfg success
09/26 11:15:24.370338 00002082 DND startup path:/usr/bin args:./taosd
09/26 11:15:24.371211 00002082 UTL apoll url not load
09/26 11:15:24.371272 00002082 UTL load from cfg file /etc/taos//taos.cfg success
09/26 11:15:24.371280 00002082 UTL env file:.env not load
09/26 11:15:24.371284 00002082 UTL load from env variables cfg success
09/26 11:15:24.371411 00002082 UTL                      global config
09/26 11:15:24.371428 00002082 UTL =================================================================
09/26 11:15:24.371432 00002082 UTL default      firstEp                  localhost:6030
09/26 11:15:24.371434 00002082 UTL default      secondEp                 localhost:6030
09/26 11:15:24.371436 00002082 UTL default      fqdn                     localhost
09/26 11:15:24.371439 00002082 UTL default      serverPort               6030
09/26 11:15:24.371449 00002082 UTL default      tempDir                  /tmp/
09/26 11:15:24.371454 00002082 UTL default      minimalTmpDirGB          1.00
09/26 11:15:24.371460 00002082 UTL default      shellActivityTimer       3
09/26 11:15:24.371462 00002082 UTL default      compressMsgSize          -1
09/26 11:15:24.371464 00002082 UTL default      compressColData          -1
09/26 11:15:24.371466 00002082 UTL default      queryPolicy              1
09/26 11:15:24.371468 00002082 UTL default      enableQueryHb            1
09/26 11:15:24.371470 00002082 UTL default      enableScience            0
09/26 11:15:24.371472 00002082 UTL default      querySmaOptimize         0
09/26 11:15:24.371475 00002082 UTL default      queryPlannerTrace        0
09/26 11:15:24.371477 00002082 UTL default      queryNodeChunkSize       32768
09/26 11:15:24.371479 00002082 UTL default      queryUseNodeAllocator    1
09/26 11:15:24.371481 00002082 UTL default      keepColumnName           0
09/26 11:15:24.371485 00002082 UTL default      smlChildTableName
09/26 11:15:24.371488 00002082 UTL default      smlTagName               _tag_null
09/26 11:15:24.371490 00002082 UTL default      smlTsDefaultName         _ts
09/26 11:15:24.371492 00002082 UTL default      smlDot2Underline         1
09/26 11:15:24.371495 00002082 UTL default      maxInsertBatchRows       1000000
09/26 11:15:24.371498 00002082 UTL default      maxRetryWaitTime         10000
09/26 11:15:24.371500 00002082 UTL default      useAdapter               0
09/26 11:15:24.371502 00002082 UTL default      crashReporting           1
09/26 11:15:24.371504 00002082 UTL default      queryMaxConcurrentTable  200
09/26 11:15:24.371507 00002082 UTL default      metaCacheMaxSize         -1
09/26 11:15:24.371511 00002082 UTL default      slowLogThreshold         3
09/26 11:15:24.371515 00002082 UTL default      slowLogScope
09/26 11:15:24.371529 00002082 UTL default      numOfRpcThreads          2
09/26 11:15:24.371533 00002082 UTL default      numOfRpcSessions         10000
09/26 11:15:24.371535 00002082 UTL default      timeToGetAvailableConn   500000
09/26 11:15:24.371538 00002082 UTL default      keepAliveIdle            60
09/26 11:15:24.371541 00002082 UTL default      numOfTaskQueueThreads    4
09/26 11:15:24.371544 00002082 UTL cfg_file     dataDir                  /mnt/tgnine/taos
09/26 11:15:24.371557 00002082 UTL default      minimalDataDirGB         2.00
09/26 11:15:24.371562 00002082 UTL default      supportVnodes            8
09/26 11:15:24.371565 00002082 UTL default      maxShellConns            50000
09/26 11:15:24.371578 00002082 UTL default      statusInterval           1
09/26 11:15:24.371582 00002082 UTL default      minSlidingTime           1
09/26 11:15:24.371584 00002082 UTL default      minIntervalTime          1
09/26 11:15:24.371587 00002082 UTL default      maxNumOfDistinctRes      10000000
09/26 11:15:24.371589 00002082 UTL default      countAlwaysReturnValue   1
09/26 11:15:24.371593 00002082 UTL default      queryBufferSize          -1
09/26 11:15:24.371595 00002082 UTL default      printAuth                0
09/26 11:15:24.371597 00002082 UTL default      queryRspPolicy           0
09/26 11:15:24.371599 00002082 UTL default      numOfRpcThreads          2
09/26 11:15:24.371605 00002082 UTL default      numOfRpcSessions         10000
09/26 11:15:24.371607 00002082 UTL default      timeToGetAvailableConn   10000
09/26 11:15:24.371609 00002082 UTL default      keepAliveIdle            60
09/26 11:15:24.371641 00002082 UTL default      numOfCommitThreads       2
09/26 11:15:24.371645 00002082 UTL default      numOfMnodeReadThreads    1
09/26 11:15:24.371659 00002082 UTL default      numOfVnodeQueryThreads   8
09/26 11:15:24.371662 00002082 UTL default      ratioOfVnodeStreamThrea  4.00
09/26 11:15:24.371676 00002082 UTL default      numOfVnodeFetchThreads   4
09/26 11:15:24.371680 00002082 UTL default      numOfVnodeRsmaThreads    4
09/26 11:15:24.371684 00002082 UTL default      numOfQnodeQueryThreads   8
09/26 11:15:24.371686 00002082 UTL default      numOfSnodeSharedThreads  2
09/26 11:15:24.371688 00002082 UTL default      numOfSnodeUniqueThreads  2
09/26 11:15:24.371690 00002082 UTL default      rpcQueueMemoryAllowed    381731635
09/26 11:15:24.371693 00002082 UTL default      syncElectInterval        25000
09/26 11:15:24.371707 00002082 UTL default      syncHeartbeatInterval    1000
09/26 11:15:24.371710 00002082 UTL default      syncHeartbeatTimeout     20000
09/26 11:15:24.371713 00002082 UTL default      vndCommitMaxInterval     600000
09/26 11:15:24.371716 00002082 UTL default      mndSdbWriteDelta         200
09/26 11:15:24.371729 00002082 UTL default      mndLogRetention          2000
09/26 11:15:24.371733 00002082 UTL default      grantMode                0
09/26 11:15:24.371737 00002082 UTL default      skipGrant                0
09/26 11:15:24.371739 00002082 UTL default      monitor                  1
09/26 11:15:24.371741 00002082 UTL default      monitorInterval          30
09/26 11:15:24.371743 00002082 UTL default      monitorFqdn
09/26 11:15:24.371757 00002082 UTL default      monitorPort              6043
09/26 11:15:24.371761 00002082 UTL default      monitorMaxLogs           100
09/26 11:15:24.371775 00002082 UTL default      monitorComp              0
09/26 11:15:24.371778 00002082 UTL default      audit                    0
09/26 11:15:24.371782 00002082 UTL default      auditFqdn
09/26 11:15:24.371785 00002082 UTL default      auditPort                6043
09/26 11:15:24.371787 00002082 UTL default      crashReporting           1
09/26 11:15:24.371789 00002082 UTL default      telemetryReporting       1
09/26 11:15:24.371802 00002082 UTL default      telemetryInterval        43200
09/26 11:15:24.371806 00002082 UTL default      telemetryServer          telemetry.tdengine.com
09/26 11:15:24.371820 00002082 UTL default      telemetryPort            80
09/26 11:15:24.371824 00002082 UTL default      tmqMaxTopicNum           20
09/26 11:15:24.371827 00002082 UTL default      transPullupInterval      2
09/26 11:15:24.371840 00002082 UTL default      mqRebalanceInterval      2
09/26 11:15:24.371844 00002082 UTL default      ttlUnit                  86400
09/26 11:15:24.371858 00002082 UTL default      ttlPushInterval          10
09/26 11:15:24.371861 00002082 UTL default      ttlBatchDropNum          10000
09/26 11:15:24.371864 00002082 UTL default      ttlChangeOnWrite         0
09/26 11:15:24.371877 00002082 UTL default      ttlFlushThreshold        100
09/26 11:15:24.371882 00002082 UTL default      trimVDbIntervalSec       3600
09/26 11:15:24.371886 00002082 UTL default      uptimeInterval           300
09/26 11:15:24.371900 00002082 UTL default      queryRsmaTolerance       1000
09/26 11:15:24.371904 00002082 UTL default      walFsyncDataSizeLimit    104857600
09/26 11:15:24.371918 00002082 UTL default      udf                      1
09/26 11:15:24.371921 00002082 UTL default      udfdResFuncs
09/26 11:15:24.371924 00002082 UTL default      udfdLdLibPath
09/26 11:15:24.371926 00002082 UTL default      disableStream            0
09/26 11:15:24.371930 00002082 UTL default      streamBufferSize         134217728
09/26 11:15:24.371932 00002082 UTL default      checkpointInterval       20
09/26 11:15:24.371936 00002082 UTL default      cacheLazyLoadThreshold   500
09/26 11:15:24.371939 00002082 UTL default      filterScalarMode         0
09/26 11:15:24.371952 00002082 UTL default      keepTimeOffset           0
09/26 11:15:24.371956 00002082 UTL default      maxStreamBackendCache    128
09/26 11:15:24.371959 00002082 UTL default      pqSortMemThreshold       16
09/26 11:15:24.371972 00002082 UTL default      resolveFQDNRetryTime     100
09/26 11:15:24.371976 00002082 UTL default      s3Accesskey              <accesskey>
09/26 11:15:24.371990 00002082 UTL default      s3Endpoint               <endpoint>
09/26 11:15:24.371993 00002082 UTL default      s3BucketName             <bucketname>
09/26 11:15:24.371997 00002082 UTL default      minDiskFreeSize          52428800
09/26 11:15:24.372000 00002082 UTL default      configDir                /etc/taos/
09/26 11:15:24.372013 00002082 UTL default      scriptDir                /etc/taos/
09/26 11:15:24.372016 00002082 UTL cfg_file     logDir                   /mnt/tgnine/log/taos
09/26 11:15:24.372021 00002082 UTL default      minimalLogDirGB          1.00
09/26 11:15:24.372024 00002082 UTL default      numOfLogLines            10000000
09/26 11:15:24.372026 00002082 UTL default      asyncLog                 1
09/26 11:15:24.372028 00002082 UTL default      logKeepDays              0
09/26 11:15:24.372042 00002082 UTL default      debugFlag                0
09/26 11:15:24.372046 00002082 UTL default      simDebugFlag             143
09/26 11:15:24.372048 00002082 UTL default      tmrDebugFlag             131
09/26 11:15:24.372062 00002082 UTL default      uDebugFlag               131
09/26 11:15:24.372065 00002082 UTL default      rpcDebugFlag             131
09/26 11:15:24.372068 00002082 UTL default      jniDebugFlag             131
09/26 11:15:24.372081 00002082 UTL default      qDebugFlag               131
09/26 11:15:24.372085 00002082 UTL default      cDebugFlag               131
09/26 11:15:24.372088 00002082 UTL default      dDebugFlag               131
09/26 11:15:24.372101 00002082 UTL default      vDebugFlag               131
09/26 11:15:24.372105 00002082 UTL default      mDebugFlag               131
09/26 11:15:24.372108 00002082 UTL default      wDebugFlag               131
09/26 11:15:24.372121 00002082 UTL default      sDebugFlag               131
09/26 11:15:24.372125 00002082 UTL default      tsdbDebugFlag            131
09/26 11:15:24.372139 00002082 UTL default      tqDebugFlag              131
09/26 11:15:24.372142 00002082 UTL default      fsDebugFlag              131
09/26 11:15:24.372145 00002082 UTL default      udfDebugFlag             131
09/26 11:15:24.372158 00002082 UTL default      smaDebugFlag             131
09/26 11:15:24.372162 00002082 UTL default      idxDebugFlag             131
09/26 11:15:24.372176 00002082 UTL default      tdbDebugFlag             131
09/26 11:15:24.372180 00002082 UTL default      metaDebugFlag            131
09/26 11:15:24.372182 00002082 UTL default      timezone                 Asia/Shanghai (CST, +0800)
09/26 11:15:24.372196 00002082 UTL default      locale                   zh_CN.UTF-8
09/26 11:15:24.372200 00002082 UTL default      charset                  UTF-8
09/26 11:15:24.372214 00002082 UTL default      assert                   1
09/26 11:15:24.372229 00002082 UTL default      enableCoreFile           1
09/26 11:15:24.372244 00002082 UTL default      numOfCores               4.00
09/26 11:15:24.372259 00002082 UTL default      SSE42                    1
09/26 11:15:24.372274 00002082 UTL default      AVX                      1
09/26 11:15:24.372289 00002082 UTL default      AVX2                     1
09/26 11:15:24.372304 00002082 UTL default      FMA                      1
09/26 11:15:24.372319 00002082 UTL default      SIMD-builtins            0
09/26 11:15:24.372323 00002082 UTL default      tagFilterCache           0
09/26 11:15:24.372325 00002082 UTL default      openMax                  655350
09/26 11:15:24.372327 00002082 UTL default      streamMax                16
09/26 11:15:24.372342 00002082 UTL default      pageSizeKB               4
09/26 11:15:24.372357 00002082 UTL default      totalMemoryKB            3727848
09/26 11:15:24.372372 00002082 UTL default      os sysname               Linux
09/26 11:15:24.372387 00002082 UTL default      os nodename              localhost.localdomain
09/26 11:15:24.372402 00002082 UTL default      os release               4.18.0-448.el8.x86_64
09/26 11:15:24.372417 00002082 UTL default      os version               #1 SMP Wed Jan 18 15:02:46 UTC 2023
09/26 11:15:24.372432 00002082 UTL default      os machine               x86_64
09/26 11:15:24.372447 00002082 UTL default      version                  3.1.2.0.alpha
09/26 11:15:24.372462 00002082 UTL default      compatible_version       3.0.0.0
09/26 11:15:24.372476 00002082 UTL default      gitinfo                  253001165ae8564cf3268881264fd72a3480eeae
09/26 11:15:24.372491 00002082 UTL default      buildinfo                Built at 2023-09-25 19:25:01
09/26 11:15:24.372506 00002082 UTL =================================================================
09/26 11:15:24.375354 00002082 DND start to init dnode env
09/26 11:15:24.375521 00002082 DND ERROR failed to init dnode since unsupported platform, please visit https://www.taosdata.com for support

**Comment by watchpoints** [comment]
why taosdlog.0 have no error msg

**Comment by yu285** [comment]
https://docs.taosdata.com/reference/support-platform/
当前支持平台列表

**Comment by watchpoints** [comment]
CentOS Stream release 8

**Comment by watchpoints** [comment]
不是衍生版本的
