### ISSUE TITLE
REST API不支持VARBINARY类型的查询

### ISSUE THREAD

**Issue by 759085503** [taosdata/TDengine#23063]
taos 版本3.1.1.0
使用的是[REST API]查询，我可以将VARBINARY类型（二进制）插入到表中，如下图：
![image](https://github.com/taosdata/TDengine/assets/26373061/6eb7b5cd-a479-4acb-8197-dd2bb68e7d04)
但是我查询的时候直接超时，然后使用REST API所有的查询都失败。应该是taosadapter停了，我重启docker 一切恢复正常。
请问
REST API
是不是不支持VARBINARY这种类型的查询？

**Comment by yu285** [comment]
可以提供下复现命令吗？我们试下

**Comment by 759085503** [comment]
这个你们模拟写一个二进制进去，然后再使用REST API读一下就可以了。我也是这样做的测试

**Comment by yu285** [comment]
> 这个你们模拟写一个二进制进去，然后再使用REST API读一下就可以了。我也是这样做的测试

感谢反馈，我们已经在处理，可以加我微信a15652223354，会随时同步修复信息。

**Comment by yu285** [comment]
taosadapter 正在做geometry 和 varbinary 的两种数据类型的适配

**Comment by yu285** [comment]
适配已经完毕，可以直接更新到 3.2.1.0 体验。
