### ISSUE TITLE
3.0.4.1和3.1.1.0版本安装之后，均出现了DB error: some vnode/qnode/mnode(s) out of service  ，不知原因是为什么

### ISSUE THREAD

**Issue by summer-lixt** [taosdata/TDengine#23064]
![image](https://github.com/taosdata/TDengine/assets/62743371/75041a02-7cca-4401-a71a-0cf3a199def2)
 rest方式没有问题，但是client连接无法操作table,查询和新增都会报错，希望帮忙解决一下

**Comment by summer-lixt** [comment]
和端口映射有关吗 做了端口映射

**Comment by yu285** [comment]
检查下 hosts 文件和fqdn 相关的基础配置即可
