### ISSUE TITLE
taodump导出数据报错

### ISSUE THREAD

**Issue by SillageDylan** [taosdata/TDengine#23088]
使用taodump导出数据时，提示错误，请问这个需要怎么解决呢 ？

ERROR: getTableDesNative() LN2884, failed to run command <DESCRIBE iotcloud.`md_1381448949184806913`>, taos: 0x55d2265b8040, code: 0x80000216, reason: syntax error near 'unrecognized token: "`md_1381448949184806913`"'
ERROR: dumpStableClasuse() LN3412, failed to get stable[md_1381448949184806913] schema

![69439e0a-6a80-4a53-8585-895042706311](https://github.com/taosdata/TDengine/assets/146165819/16383cb9-5e7a-492b-9486-5909a5c436c4)

**Comment by yu285** [comment]
请问数据库/taosdump 版本号分别是？
