### ISSUE TITLE
容器环境下，客户端连接异常

### ISSUE THREAD

**Issue by duyingsoft** [taosdata/TDengine#23099]
客户端和服务端版本：3.0.3.2
部署方式：容器
访问方式：应用是一个go语言的服务，使用原生的方式连接tdengine，该应用也是容器部署
![image](https://github.com/taosdata/TDengine/assets/13470619/13849a74-7bd6-4695-b8c0-144e5dd92890)

现象：最开始连接是正常的，但是如果tdengine容器的IP变化了，则应用会连不上tdengine的，除非重启应用。
           在应用所在的容器内部，用taos cli 连接又是正常的，ping访问的tdengine的域名也是解析到正确的IP上了。
           通过在应用的容器内抓包看的话，发现应用连tdengine的IP是旧的，如下图所示，172.18.0.3是旧的IP，因为应用是通过域名去访问的，怀疑是不是有dns缓存，但是机器上解析又是正常的，因为C语言没有怎么接触过，所以想确认一下是否底层客户端底层实现，是否会做域名解析的缓存？
![image](https://github.com/taosdata/TDengine/assets/13470619/1991ae45-9031-4573-83b9-44ff49fac432)

**Comment by yu285** [comment]
可以了解下 FQDN 机制：https://www.taosdata.com/tdengine-engineering/2741.html
