### ISSUE TITLE
When is the windows version available？

### ISSUE THREAD

**Issue by yangskyfly** [taosdata/TDengine#2309]
我目前想试用一下，由于我们的开发平台都是基于windows平台，其实目前国内的工业控制现场大多数也是运行在windows平台下，所以有几个问题想咨询一下：
1.什么时候出windows平台版本?
2.我看这边是没有C#的connector，能不能释放出基于.net 4.0的C#外包连接器，最好能与sqlserver或oracle的连接器类兼容。

谢谢!
小李
2020-6-17

**Comment by Aries-Lee1991** [comment]
您好，Windows客户端一直都有，服务器版本正在开发中，也许马上就有好消息。
我们这边是有C# Connector的：https://www.taosdata.com/cn/documentation/connector/#CSharp-Connector

**Comment by yangskyfly** [comment]
好的，谢谢！
