### ISSUE TITLE
syntax error near "tags(? ,

### ISSUE THREAD

**Issue by Linzhiyu1993** [taosdata/TDengine#231]
taos> create table v1 using tags(28436,'BMW');
TSDB error: invalid SQL: syntax error near "tags(28436,'BMW');"
taos>

**Comment by guanshengliang** [comment]
语法不对，没有创建超级表，您可以参考一下用户手册，例如
```
create table st (ts timestamp, f int) tags(t1 int, t2 binary(10));
create table t1 using st tags(28436,'BMW');
```

**Comment by Linzhiyu1993** [comment]
OK

**Comment by kakopappa** [comment]
I think article needs to be fixed. I was scratching my head when i saw this too

https://www.taosdata.com/blog/2019/07/10/using-tdengine-to-build-the-backend-of-a-connected-vehicle-platform/

**Comment by guanshengliang** [comment]
ok, we will check it

**Comment by johnnyhou327** [comment]
@Linzhiyu1993 @kakopappa Thanks for pointing out. It's now fixed.
