### ISSUE TITLE
普通表查询巨慢 表格只有49条数据 查询时接近5秒

### ISSUE THREAD

**Issue by fanqang** [taosdata/TDengine#23166]
<img width="893" alt="image" src="https://github.com/taosdata/TDengine/assets/47728120/1f06a4ce-52dd-4a19-abf4-5f998961bd55">
这张表有大量的更新操作，但是为什么查询速度会这么慢呢？
运行环境是 windows server 2019
数据库版本是 TDengine-server-3.0.7.0-Windows-x64 
这个问题是系统运行了一段时间才暴露的，刚开始查询的速度并不慢，麻烦帮忙看一下

**Comment by fanqang** [comment]
当我把运行的程序关闭后 在这个客户端进行查询 耗时还是接近5秒，帮忙看看是什么原因

**Comment by fanqang** [comment]
补充两张运行环境图片
<img width="557" alt="image" src="https://github.com/taosdata/TDengine/assets/47728120/1d638a92-1fa2-4fea-88d9-50db4239496a">
<img width="592" alt="image" src="https://github.com/taosdata/TDengine/assets/47728120/8b95e549-79ac-4840-8843-b58eed806088">

**Comment by fanqang** [comment]
补充建表语句 CREATE TABLE IF NOT EXISTS Data_Collect (Ts TIMESTAMP,VariableName NCHAR(128),PointName NCHAR(128),PointNameCn NCHAR(128),PointType NCHAR(128),PointExplain NCHAR(128),IsWrite BOOL,IsRead BOOL,WriteTs TIMESTAMP,DecimalPlaces INT,Device NCHAR(128),PlcType NCHAR(128),Slot NCHAR(128),IsShow BOOL,FunType NCHAR(128));

**Comment by yu285** [comment]
更新过多确实会导致查询降速，请从业务端尽量避免这种情况。或者定时导出导入重建表即可。

**Comment by fanqang** [comment]
超级表能否避免这种情况？

**Comment by fanqang** [comment]
但是超级表 也会有类似的更新操作

**Comment by bailuxia** [comment]
大佬还在嘛

**Comment by fanqang** [comment]
> 大佬还在嘛

你是遇到和我一样的问题了吗

**Comment by fanqang** [comment]
完整的代码仓库里有，可以直接拉，sql没有了 这是好多年之前没毕业弄的了哈&nbsp;


范强
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月11日(星期三) 下午4:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [taosdata/TDengine] 普通表查询巨慢 表格只有49条数据 查询时接近5秒 (Issue #23166)





   
大佬还在嘛
  
你是遇到和我一样的问题了吗
  
想问一下要下sql和完整的代码

**Comment by fanqang** [comment]
> > > 大佬还在嘛
> > 
> > 
> > 你是遇到和我一样的问题了吗
> 
> 想问一下要下sql和完整的代码

完整的代码仓库里有，可以直接拉，sql没有了 这是好多年之前没毕业弄的了哈
