### ISSUE TITLE
TDengine stream led to taosd CPU 198%

### ISSUE THREAD

**Issue by nieyuan1980** [taosdata/TDengine#23172]
**Bug描述**
自创建9个流式计算以后, TDengine崩溃, CPU占用率 198%

**复制**
1.创建流式计算(降采样, 每小时写入一次最大值)
create stream water_meter_hs trigger at_once fill_history 1
into water_meter_h
    tags(meter_code varchar(32), location varchar(512), working_on varchar(32), is_calc varchar(8))
    subtable(cast(concat('h_', lower(meter_code)) as varchar(32))) as
select _wstart recode_time, max (dqljlcc) max_value
from water_meters1
partition by meter_code, location, working_on, is_calc interval (1h);

2.检查 water_meter_h 表
创建完成后表中有历史数据, 创建后没有按照规则写入新数据

3.检查 入库程序
产生有崩溃日志
正在执行的线程信息：
Current thread (0x00007f5834009800):  JavaThread "main" [_thread_in_native, id=26038, stack(0x00007f583d028000,0x00007f583d128000)]

-------------------------------------------------------
对应的堆栈信息：
Stack: [0x00007f583d028000,0x00007f583d128000],  sp=0x00007f583d125e80,  free space=1015k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libtaos.so.3.1.1.0+0x37e00f]  ctgCloneDbVg+0x20
C  [libtaos.so.3.1.1.0+0x377a7a]  ctgCallSubCb+0x277
C  [libtaos.so.3.1.1.0+0x377f34]  ctgHandleTaskEnd+0xc0
C  [libtaos.so.3.1.1.0+0x37bf49]  ctgLaunchGetDbVgTask+0x184
C  [libtaos.so.3.1.1.0+0x37eccc]  ctgLaunchSubTask+0x22d
C  [libtaos.so.3.1.1.0+0x37ce5d]  ctgLaunchGetTbTagTask+0x165
C  [libtaos.so.3.1.1.0+0x37edc2]  ctgLaunchJob+0xc7
C  [libtaos.so.3.1.1.0+0x36ac4c]  catalogAsyncGetAllMeta+0x6b3
C  [libtaos.so.3.1.1.0+0x1a08de]  getAllMetaAsync+0x114
C  [libtaos.so.3.1.1.0+0x1a0936]  phaseAsyncQuery+0x4e
C  [libtaos.so.3.1.1.0+0x1a1312]  doAsyncQuery+0x12b
C  [libtaos.so.3.1.1.0+0x196ec3]  taosAsyncQueryImpl+0x18e
C  [libtaos.so.3.1.1.0+0x197129]  taosQueryImpl+0xc9
C  [libtaos.so.3.1.1.0+0x19e496]  taos_query+0x28
C  [libtaos.so.3.1.1.0+0x198d0b]  Java_com_taosdata_jdbc_TSDBJNIConnector_executeQueryImp+0x1b5
j  com.taosdata.jdbc.TSDBJNIConnector.executeQueryImp([BJ)J+0
j  com.taosdata.jdbc.TSDBJNIConnector.executeQuery(Ljava/lang/String;)J+14
j  com.taosdata.jdbc.TSDBStatement.executeUpdate(Ljava/lang/String;)I+50
j  com.antai.database.TaosDBUtil.driverInsert(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;+153
j  com.antai.TaosTool.insertSQLWriteDatabase(Ljava/lang/String;Ljava/lang/String;)Lcom/antai/utils/Rest;+111
j  com.antai.TaosTool.main([Ljava/lang/String;)V+183
v  ~StubRoutines::call_stub
V  [libjvm.so+0x68842b]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0xddb
V  [libjvm.so+0x6d33e1]  jni_invoke_static(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, Thread*) [clone .isra.96] [clone .constprop.117]+0x1e1
V  [libjvm.so+0x6d56ab]  jni_CallStaticVoidMethod+0x15b
C  [libjli.so+0x889c]  JavaMain+0xa3c
C  [libpthread.so.0+0x7ea5]  start_thread+0xc5

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.taosdata.jdbc.TSDBJNIConnector.executeQueryImp([BJ)J+0
j  com.taosdata.jdbc.TSDBJNIConnector.executeQuery(Ljava/lang/String;)J+14
j  com.taosdata.jdbc.TSDBStatement.executeUpdate(Ljava/lang/String;)I+50
j  com.antai.database.TaosDBUtil.driverInsert(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;+153
j  com.antai.TaosTool.insertSQLWriteDatabase(Ljava/lang/String;Ljava/lang/String;)Lcom/antai/utils/Rest;+111
j  com.antai.TaosTool.main([Ljava/lang/String;)V+183
v  ~StubRoutines::call_stub
-------------------------------------------------------

4. 停止流式计算 
失败

5. 删除流式计算 
卡死

6. 停止数据库 
systemctl stop taosd 卡死
systemctl status taosd 数据库已停止
top命令, taosd进程依然高占用CPU
  
**屏幕截图**
![捕获02](https://github.com/taosdata/TDengine/assets/25432482/8c8cc042-bd83-4d54-b94b-94c63debe5ed)

![捕获03](https://github.com/taosdata/TDengine/assets/25432482/8415c762-d188-426f-9981-2a35e69a7336)

**环境（请填写以下信息）：**
-操作系统：
CentOS 7.0

-内存、CPU、当前磁盘空间
2G、2394.454MHz、25G

-TDengine版本 
3.1.1.0

**Comment by yu285** [comment]
cpu几核？

**Comment by nieyuan1980** [comment]
CPU是两核
-------------------------------------------------------------------------------------
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-26xx v4
Stepping:              1
CPU MHz:               2394.454
BogoMIPS:              4788.90
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
NUMA node0 CPU(s):     0,1

**Comment by nieyuan1980** [comment]
> cpu几核？

CPU是两核

Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Byte Order: Little Endian
CPU(s): 2
On-line CPU(s) list: 0,1
Thread(s) per core: 1
Core(s) per socket: 2
Socket(s): 1
NUMA node(s): 1
Vendor ID: GenuineIntel
CPU family: 6
Model: 79
Model name: Intel(R) Xeon(R) CPU E5-26xx v4
Stepping: 1
CPU MHz: 2394.454
BogoMIPS: 4788.90
Hypervisor vendor: KVM
Virtualization type: full
L1d cache: 32K
L1i cache: 32K
L2 cache: 4096K
NUMA node0 CPU(s): 0,1

**Comment by yu285** [comment]
你这个看起来更像资源不足。可以适当增加服务器资源再做测试吗

**Comment by yu285** [comment]
如果后续有问题可以联系我，微信：a15652223354

**Comment by nieyuan1980** [comment]
后继内存增加到6G，服务器正常。
但是流式计算一直无法停止或删除（无论是重启数据库还是重启服务器），报错：Conflict transaction not completed。
使用命令：show transactions\G

![微信图片_20231030160345](https://github.com/taosdata/TDengine/assets/25432482/78b11cb3-ad64-490e-8ead-84fc3764e062)

**Comment by yu285** [comment]
加我微信我们远程一下吧
