### ISSUE TITLE
3.0.3.0 服务器异常重启之后，启动服务失败，报错failed to open wal since WAL log incomplete

### ISSUE THREAD

**Issue by danlalu** [taosdata/TDengine#23175]
![9091696729379_ pic](https://github.com/taosdata/TDengine/assets/39449811/91b51b17-5d5b-4ea4-82f0-29613722f595)

**Comment by nrwflqzr-zwhy** [comment]
请问你这个问题是如何解决的

**Comment by yu285** [comment]
这种问题一般由于断电，服务异常终止等原因导致的wal数据丢失。

日常使用最好使用三副本规避此类意外。

**Comment by leijianhang** [comment]
请问下是怎么解决的，我也遇到了
