### ISSUE TITLE
数据订阅为何限制20个

### ISSUE THREAD

**Issue by lulg** [taosdata/TDengine#23205]
![image](https://github.com/taosdata/TDengine/assets/28698352/f8e6cea6-edef-48b0-970b-77da5192a70e)
数据订阅为何限制20个呢，并且最大值职能是10000?

假设我有几十万个设备，每个数值超了都要告警，我要订阅这些数据，那最佳实践是什么呢？

**Comment by imborntowin** [comment]
我感觉这不算问题，感觉可以优化结构，或者订阅高层级，比如stb，db。但是我发现订阅功能，好像获取不了tag？即获取不到完整的一条数据，又限制了订阅数量，就有点问题了感觉

**Comment by yu285** [comment]
> 我感觉这不算问题，感觉可以优化结构，或者订阅高层级，比如stb，db。但是我发现订阅功能，好像获取不了tag？即获取不到完整的一条数据，又限制了订阅数量，就有点问题了感觉

订阅的时候，select *,tagname from xxxx  这样试过吗

**Comment by yu285** [comment]
咱做关闭处理，如有问题请添加微信 a15652223354
