### ISSUE TITLE
查询太慢

### ISSUE THREAD

**Issue by tjthink** [taosdata/TDengine#23204]
安装的 3.1.1.0 版本
服务器：16c 16g
使用 taosBenchmark 插入数据，然后通过时间或 groupid、location 字段查询超级表，查询很慢，需要10s左右了
![}U)K{H882B0CJZR)HZ850XX](https://github.com/taosdata/TDengine/assets/5283107/bf24d39a-5d7d-4d0e-a1ea-b509f9cc20b2)

**Comment by yu285** [comment]
在服务端执行，你这个应该是网络问题。
