### ISSUE TITLE
failed to connect to server, reason: Sync leader is unreachable

### ISSUE THREAD

**Issue by java-fei** [taosdata/TDengine#23211]
k8s 部署三节点集群，版本为tdengine/tdengine:3.0.7.1。
扩容磁盘后异常。
kubectl exec -it tdengine-0 -n tdengine -- taos
Welcome to the TDengine Command Line Interface, Client Version:3.0.7.1
Copyright (c) 2022 by TDengine, all rights reserved.
failed to connect to server, reason: Sync leader is unreachable
command terminated with exit code 255

查看容器日志:

10/10 16:21:47.424337 00001128 SYN vgId:10, succeed to write raft store file:/var/lib/taos/vnode/vnode10/sync/raft_store.json, term:17733
10/10 16:21:47.425626 00001128 SYN vgId:10, succeed to write raft store file:/var/lib/taos/vnode/vnode10/sync/raft_store.json, term:17733
10/10 16:21:47.426806 00001128 SYN vgId:10, succeed to write raft store file:/var/lib/taos/vnode/vnode10/sync/raft_store.json, term:17733
10/10 16:21:48.078048 00001009 SYN vgId:11, begin election, sync:candidate, term:17754, commit-index:-1, applied-index:-1, first-ver:0, last-ver:452, min:-1, snap:-1, snap-term:0, elect-times:3580, as-leader-times:0, cfg-ch-times:0, hb-slow:0, hbr-slow:0, aq-items:0, snaping:-1, replicas:3, last-cfg:0, chging:0, restore:0, quorum:2, elect-lc-timer:3767, hb:0, buffer:[-1 -1 452, 453), repl-mgrs:{0:0 [0 0, 0), 1:0 [0 0, 0), 2:0 [0 0, 0)}, members:{num:3, as:0, [tdengine-0.taosd.tdengine.svc.cluster.local:6030, tdengine-1.taosd.tdengine.svc.cluster.local:6030, tdengine-2.taosd.tdengine.svc.cluster.local:6030]}, hb:{0:1696904102459,1:1696904102459,2:1696904102459}, hb-reply:{0:1696904102459,1:1696904102459,2:1696904102459}
10/10 16:21:48.079549 00001009 SYN vgId:11, succeed to write raft store file:/var/lib/taos/vnode/vnode11/sync/raft_store.json, term:17755
10/10 16:21:48.081125 00001009 SYN vgId:11, succeed to write raft store file:/var/lib/taos/vnode/vnode11/sync/raft_store.json, term:17755
10/10 16:21:48.082343 00001009 SYN vgId:11, succeed to write raft store file:/var/lib/taos/vnode/vnode11/sync/raft_store.json, term:17755
10/10 16:21:48.110323 00000096 SYN vgId:1, recv sync-request-vote from dnode:2, {term:23624, last-index:12039, last-term:15}, granted:0, sync:candidate, term:23636, commit-index:12010, applied-index:12010, first-ver:9811, last-ver:12032, min:-1, snap:12010, snap-term:1, elect-times:4822, as-leader-times:0, cfg-ch-times:0, hb-slow:0, hbr-slow:0, aq-items:-1, snaping:-1, replicas:3, last-cfg:20, chging:0, restore:0, quorum:2, elect-lc-timer:4943, hb:0, buffer:[12010 12010 12032, 12033), repl-mgrs:{0:0 [0 0, 0), 1:0 [0 0, 0), 2:0 [0 0, 0)}, members:{num:3, as:0, [tdengine-0.taosd.tdengine.svc.cluster.local:6030, tdengine-1.taosd.tdengine.svc.cluster.local:6030, tdengine-2.taosd.tdengine.svc.cluster.local:6030]}, hb:{0:1696904102422,1:1696904102422,2:1696904102422}, hb-reply:{0:1696904102422,1:1696904102422,2:1696904102422}
10/10 16:21:48.110346 00000096 SYN vgId:1, send sync-request-vote-reply to dnode:2 {term:23636, grant:0}, , sync:candidate, term:23636, commit-index:12010, applied-index:12010, first-ver:9811, last-ver:12032, min:-1, snap:12010, snap-term:1, elect-times:4822, as-leader-times:0, cfg-ch-times:0, hb-slow:0, hbr-slow:0, aq-items:-1, snaping:-1, replicas:3, last-cfg:20, chging:0, restore:0, quorum:2, elect-lc-timer:4943, hb:0, buffer:[12010 12010 12032, 12033), repl-mgrs:{0:0 [0 0, 0), 1:0 [0 0, 0), 2:0 [0 0, 0)}, members:{num:3, as:0, [tdengine-0.taosd.tdengine.svc.cluster.local:6030, tdengine-1.taosd.tdengine.svc.cluster.local:6030, tdengine-2.taosd.tdengine.svc.cluster.local:6030]}, hb:{0:1696904102422,1:1696904102422,2:1696904102422}, hb-reply:{0:1696904102422,1:1696904102422,2:1696904102422}
10/10 16:21:48.503044 00000096 SYN vgId:1, begin election, sync:candidate, term:23636, commit-index:12010, applied-index:12010, first-ver:9811, last-ver:12032, min:-1, snap:12010, snap-term:1, elect-times:4822, as-leader-times:0, cfg-ch-times:0, hb-slow:0, hbr-slow:0, aq-items:-1, snaping:-1, replicas:3, last-cfg:20, chging:0, restore:0, quorum:2, elect-lc-timer:4943, hb:0, buffer:[12010 12010 12032, 12033), repl-mgrs:{0:0 [0 0, 0), 1:0 [0 0, 0), 2:0 [0 0, 0)}, members:{num:3, as:0, [tdengine-0.taosd.tdengine.svc.cluster.local:6030, tdengine-1.taosd.tdengine.svc.cluster.local:6030, tdengine-2.taosd.tdengine.svc.cluster.local:6030]}, hb:{0:1696904102422,1:1696904102422,2:1696904102422}, hb-reply:{0:1696904102422,1:1696904102422,2:1696904102422}
10/10 16:21:48.504616 00000096 SYN vgId:1, succeed to write raft store file:/var/lib/taos//mnode/sync/raft_store.json, term:23637
10/10 16:21:48.505529 00000096 SYN vgId:1, succeed to write raft store file:/var/lib/taos//mnode/sync/raft_store.json, term:23637
10/10 16:21:48.506620 00000096 SYN vgId:1, succeed to write raft store file:/var/lib/taos//mnode/sync/raft_store.json, term:23637
10/10 16:21:49.120269 00001128 SYN vgId:10, recv sync-request-vote from dnode:2, {term:17726, last-index:456, last-term:11}, granted:0, sync:candidate, term:17733, commit-index:-1, applied-index:-1, first-ver:0, last-ver:452, min:-1, snap:-1, snap-term:0, elect-times:3617, as-leader-times:0, cfg-ch-times:0, hb-slow:0, hbr-slow:0, aq-items:0, snaping:-1, replicas:3, last-cfg:0, chging:0, restore:0, quorum:2, elect-lc-timer:3716, hb:0, buffer:[-1 -1 452, 453), repl-mgrs:{0:0 [0 0, 0), 1:0 [0 0, 0), 2:0 [0 0, 0)}, members:{num:3, as:0, [tdengine-0.taosd.tdengine.svc.cluster.local:6030, tdengine-1.taosd.tdengine.svc.cluster.local:6030, tdengine-2.taosd.tdengine.svc.cluster.local:6030]}, hb:{0:1696904102464,1:1696904102464,2:1696904102464}, hb-reply:{0:1696904102464,1:1696904102464,2:1696904102464}
10/10 16:21:49.120293 00001128 SYN vgId:10, send sync-request-vote-reply to dnode:2 {term:17733, grant:0}, , sync:candidate, term:17733, commit-index:-1, applied-index:-1, first-ver:0, last-ver:452, min:-1, snap:-1, snap-term:0, elect-times:3617, as-leader-times:0, cfg-ch-times:0, hb-slow:0, hbr-slow:0, aq-items:0, snaping:-1, replicas:3, last-cfg:0, chging:0, restore:0, quorum:2, elect-lc-timer:3716, hb:0, buffer:[-1 -1 452, 453), repl-mgrs:{0:0 [0 0, 0), 1:0 [0 0, 0), 2:0 [0 0, 0)}, members:{num:3, as:0, [tdengine-0.taosd.tdengine.svc.cluster.local:6030, tdengine-1.taosd.tdengine.svc.cluster.local:6030, tdengine-2.taosd.tdengine.svc.cluster.local:6030]}, hb:{0:1696904102464,1:1696904102464,2:1696904102464}, hb-reply:{0:1696904102464,1:1696904102464,2:1696904102464}
10/10 16:21:49.462500 00001128 SYN vgId:10, recv sync-request-vote from dnode:3, {term:17680, last-index:456, last-term:11}, granted:0, sync:candidate, term:17733, commit-index:-1, applied-index:-1, first-ver:0, last-ver:452, min:-1, snap:-1, snap-term:0, elect-times:3617, as-leader-times:0, cfg-ch-times:0, hb-slow:0, hbr-slow:0, aq-items:0, snaping:-1, replicas:3, last-cfg:0, chging:0, restore:0, quorum:2, elect-lc-timer:3716, hb:0, buffer:[-1 -1 452, 453), repl-mgrs:{0:0 [0 0, 0), 1:0 [0 0, 0), 2:0 [0 0, 0)}, members:{num:3, as:0, [tdengine-0.taosd.tdengine.svc.cluster.local:6030, tdengine-1.taosd.tdengine.svc.cluster.local:6030, tdengine-2.taosd.tdengine.svc.cluster.local:6030]}, hb:{0:1696904102464,1:1696904102464,2:1696904102464}, hb-reply:{0:1696904102464,1:1696904102464,2:1696904102464}
10/10 16:21:49.462523 00001128 SYN vgId:10, send sync-request-vote-reply to dnode:3 {term:17733, grant:0}, , sync:candidate, term:17733, commit-index:-1, applied-index:-1, first-ver:0, last-ver:452, min:-1, snap:-1, snap-term:0, elect-times:3617, as-leader-times:0, cfg-ch-times:0, hb-slow:0, hbr-slow:0, aq-items:0, snaping:-1, replicas:3, last-cfg:0, chging:0, restore:0, quorum:2, elect-lc-timer:3716, hb:0, buffer:[-1 -1 452, 453), repl-mgrs:{0:0 [0 0, 0), 1:0 [0 0, 0), 2:0 [0 0, 0)}, members:{num:3, as:0, [tdengine-0.taosd.tdengine.svc.cluster.local:6030, tdengine-1.taosd.tdengine.svc.cluster.local:6030, tdengine-2.taosd.tdengine.svc.cluster.local:6030]}, hb:{0:1696904102464,1:1696904102464,2:1696904102464}, hb-reply:{0:1696904102464,1:1696904102464,2:1696904102464}
10/10 16:21:50.145700 00001009 SYN vgId:11, recv sync-request-vote from dnode:2, {term:17746, last-index:457, last-term:14}, granted:0, sync:candidate, term:17755, commit-index:-1, applied-index:-1, first-ver:0, last-ver:452, min:-1, snap:-1, snap-term:0, elect-times:3581, as-leader-times:0, cfg-ch-times:0, hb-slow:0, hbr-slow:0, aq-items:0, snaping:-1, replicas:3, last-cfg:0, chging:0, restore:0, quorum:2, elect-lc-timer:3768, hb:0, buffer:[-1 -1 452, 453), repl-mgrs:{0:0 [0 0, 0), 1:0 [0 0, 0), 2:0 [0 0, 0)}, members:{num:3, as:0, [tdengine-0.taosd.tdengine.svc.cluster.local:6030, tdengine-1.taosd.tdengine.svc.cluster.local:6030, tdengine-2.taosd.tdengine.svc.cluster.local:6030]}, hb:{0:1696904102459,1:1696904102459,2:1696904102459}, hb-reply:{0:1696904102459,1:1696904102459,2:1696904102459}
10/10 16:21:50.145721 00001009 SYN vgId:11, send sync-request-vote-reply to dnode:2 {term:17755, grant:0}, , sync:candidate, term:17755, commit-index:-1, applied-index:-1, first-ver:0, last-ver:452, min:-1, snap:-1, snap-term:0, elect-times:3581, as-leader-times:0, cfg-ch-times:0, hb-slow:0, hbr-slow:0, aq-items:0, snaping:-1, replicas:3, last-cfg:0, chging:0, restore:0, quorum:2, elect-lc-timer:3768, hb:0, buffer:[-1 -1 452, 453), repl-mgrs:{0:0 [0 0, 0), 1:0 [0 0, 0), 2:0 [0 0, 0)}, members:{num:3, as:0, [tdengine-0.taosd.tdengine.svc.cluster.local:6030, tdengine-1.taosd.tdengine.svc.cluster.local:6030, tdengine-2.taosd.tdengine.svc.cluster.local:6030]}, hb:{0:1696904102459,1:1696904102459,2:1696904102459}, hb-reply:{0:1696904102459,1:1696904102459,2:1696904102459}
10/10 16:21:50.297050 00001009 SYN vgId:11, recv sync-request-vote from dnode:3, {term:17695, last-index:457, last-term:14}, granted:0, sync:candidate, term:17755, commit-index:-1, applied-index:-1, first-ver:0, last-ver:452, min:-1, snap:-1, snap-term:0, elect-times:3581, as-leader-times:0, cfg-ch-times:0, hb-slow:0, hbr-slow:0, aq-items:0, snaping:-1, replicas:3, last-cfg:0, chging:0, restore:0, quorum:2, elect-lc-timer:3768, hb:0, buffer:[-1 -1 452, 453), repl-mgrs:{0:0 [0 0, 0), 1:0 [0 0, 0), 2:0 [0 0, 0)}, members:{num:3, as:0, [tdengine-0.taosd.tdengine.svc.cluster.local:6030, tdengine-1.taosd.tdengine.svc.cluster.local:6030, tdengine-2.taosd.tdengine.svc.cluster.local:6030]}, hb:{0:1696904102459,1:1696904102459,2:1696904102459}, hb-reply:{0:1696904102459,1:1696904102459,2:1696904102459}
10/10 16:21:50.297073 00001009 SYN vgId:11, send sync-request-vote-reply to dnode:3 {term:17755, grant:0}, , sync:candidate, term:17755, commit-index:-1, applied-index:-1, first-ver:0, last-ver:452, min:-1, snap:-1, snap-term:0, elect-times:3581, as-leader-times:0, cfg-ch-times:0, hb-slow:0, hbr-slow:0, aq-items:0, snaping:-1, replicas:3, last-cfg:0, chging:0, restore:0, quorum:2, elect-lc-timer:3768, hb:0, buffer:[-1 -1 452, 453), repl-mgrs:{0:0 [0 0, 0), 1:0 [0 0, 0), 2:0 [0 0, 0)}, members:{num:3, as:0, [tdengine-0.taosd.tdengine.svc.cluster.local:6030, tdengine-1.taosd.tdengine.svc.cluster.local:6030, tdengine-2.taosd.tdengine.svc.cluster.local:6030]}, hb:{0:1696904102459,1:1696904102459,2:1696904102459}, hb-reply:{0:1696904102459,1:1696904102459,2:1696904102459}
10/10 16:21:52.402467 00000096 SYN vgId:1, recv sync-request-vote from dnode:3, {term:23571, last-index:12039, last-term:15}, granted:0, sync:candidate, term:23637, commit-index:12010, applied-index:12010, first-ver:9811, last-ver:12032, min:-1, snap:12010, snap-term:1, elect-times:4823, as-leader-times:0, cfg-ch-times:0, hb-slow:0, hbr-slow:0, aq-items:-1, snaping:-1, replicas:3, last-cfg:20, chging:0, restore:0, quorum:2, elect-lc-timer:4944, hb:0, buffer:[12010 12010 12032, 12033), repl-mgrs:{0:0 [0 0, 0), 1:0 [0 0, 0), 2:0 [0 0, 0)}, members:{num:3, as:0, [tdengine-0.taosd.tdengine.svc.cluster.local:6030, tdengine-1.taosd.tdengine.svc.cluster.local:6030, tdengine-2.taosd.tdengine.svc.cluster.local:6030]}, hb:{0:1696904102422,1:1696904102422,2:1696904102422}, hb-reply:{0:1696904102422,1:1696904102422,2:1696904102422}
10/10 16:21:52.402491 00000096 SYN vgId:1, send sync-request-vote-reply to dnode:3 {term:23637, grant:0}, , sync:candidate, term:23637, commit-index:12010, applied-index:12010, first-ver:9811, last-ver:12032, min:-1, snap:12010, snap-term:1, elect-times:4823, as-leader-times:0, cfg-ch-times:0, hb-slow:0, hbr-slow:0, aq-items:-1, snaping:-1, replicas:3, last-cfg:20, chging:0, restore:0, quorum:2, elect-lc-timer:4944, hb:0, buffer:[12010 12010 12032, 12033), repl-mgrs:{0:0 [0 0, 0), 1:0 [0 0, 0), 2:0 [0 0, 0)}, members:{num:3, as:0, [tdengine-0.taosd.tdengine.svc.cluster.local:6030, tdengine-1.taosd.tdengine.svc.cluster.local:6030, tdengine-2.taosd.tdengine.svc.cluster.local:6030]}, hb:{0:1696904102422,1:1696904102422,2:1696904102422}, hb-reply:{0:1696904102422,1:1696904102422,2:1696904102422}
10/10 16:21:52.488036 00000096 SYN vgId:1, begin election, sync:candidate, term:23637, commit-index:12010, applied-index:12010, first-ver:9811, last-ver:12032, min:-1, snap:12010, snap-term:1, elect-times:4823, as-leader-times:0, cfg-ch-times:0, hb-slow:0, hbr-slow:0, aq-items:-1, snaping:-1, replicas:3, last-cfg:20, chging:0, restore:0, quorum:2, elect-lc-timer:4944, hb:0, buffer:[12010 12010 12032, 12033), repl-mgrs:{0:0 [0 0, 0), 1:0 [0 0, 0), 2:0 [0 0, 0)}, members:{num:3, as:0, [tdengine-0.taosd.tdengine.svc.cluster.local:6030, tdengine-1.taosd.tdengine.svc.cluster.local:6030, tdengine-2.taosd.tdengine.svc.cluster.local:6030]}, hb:{0:1696904102422,1:1696904102422,2:1696904102422}, hb-reply:{0:1696904102422,1:1696904102422,2:1696904102422}

**Comment by yu285** [comment]
https://www.taosdata.com/tdengine-engineering/18366.html 有相关错误原理
