### ISSUE TITLE
超级表插入不同类型字段(float、double)值有很大差别，为什么float会补全随机值？

### ISSUE THREAD

**Issue by gubinjie** [taosdata/TDengine#23235]
版本：3.0
描述：
相同的值插入float和double类型的字段中，为什么float会补全随机值？
比如插入974.15，float类型的出现974.15002 ，这002是怎么出来的？

![image](https://github.com/taosdata/TDengine/assets/37869445/c9677906-0b71-441d-83df-ed61307d660a)

**Comment by hoilung** [comment]
这个不算bug，数值类小数精度问题，对于你实际存取没啥影响，你存的是974.15，取出来的也是 974.15
