### ISSUE TITLE
same SQL encountered an error in native connection  but worked fine in restful

### ISSUE THREAD

**Issue by zhuming19791109** [taosdata/TDengine#23238]
**Bug Description**
之前用restful连接的sql，现在用原生连接后会报错

**Additional Context**
之前用restful连接：
select             INTERP(`value`) as `value`         from pressMGFF2F26263B38_0_2_0         
range('2023-10-12 14:33:08','2023-10-12 14:42:08')         every(2m) FILL(prev)
现在用原生连接：
select             INTERP(`value`) as `value`         from pressMGFF2F26263B38_0_2_0         
range('2023-10-12 14:33:08','2023-10-12 14:42:08')         every(‘2m’) FILL(prev)

报错信息如下：
### Cause: java.sql.SQLException: TDengine ERROR (80000216): syntax error near "'10m') fill(prev)"

也就是多了个单引号，程序是通过String类型传进来：2m，这个字符串的，如何修正这个错误？

**Comment by yu285** [comment]
这种是语法限制，应用侧不能去掉单引号对吗。

**Comment by zhuming19791109** [comment]
是的，应用侧是10m（十分钟）这个字符串，解释到sql自动加上了单引号。

**Comment by yu285** [comment]
咱们的版本是？

**Comment by zhuming19791109** [comment]
我的版本是2.4.0.10，已经通过固定间隔时间写死来解决了，传变量有问题。

**Comment by yu285** [comment]
> 我的版本是2.4.0.10，已经通过固定间隔时间写死来解决了，传变量有问题。

尽早迁移到 3.x 上吧（当前最新版 3.2.1.0），迁移方法：https://www.taosdata.com/tdengine-engineering/17753.html

有疑问可加我微信：a15652223354
