### ISSUE TITLE
WINDOWS版本无法正常使用

### ISSUE THREAD

**Issue by c56625079** [taosdata/TDengine#23270]
由于环境限制，我需要在WINDOWS SERVER2019下面安装TDengine进行开发。   我先后尝试安装了3.1.1.0，3.1.0.3 两个版本，在C:\TDengine  目录下，均未发现taosd.exe 文件，导至无法启动TDengine。

**Comment by yu285** [comment]
3100 开始windows是企业版范畴了

建议：

1.使用 linux 

2. 在windows 上使用docker

**Comment by c56625079** [comment]
3.0.7.1版本有同样情况
