### ISSUE TITLE
TDengine ERROR (0x80000020): some vnode/qnode/mnode(s) out of service

### ISSUE THREAD

**Issue by FlowerBirds** [taosdata/TDengine#23287]
日志里面只有这个，具体什么情况么，taos版本是3.0.x。

错误信息不明确

**Comment by Andhros** [comment]
I have the same error.

Currently running TDEngine 3.2.0.0 in both client and server. The message does not help at all.
![image](https://github.com/taosdata/TDengine/assets/29643878/01a04173-627f-4c18-8b52-81e7ec29d8f9)


Also my taos.cfg file in the firstEP config:

########################################################
#                                                      #
#                  Configuration                       #
#                                                      #
########################################################

######### 0. Client only configurations #############

# The interval for CLI to send heartbeat to mnode
# shellActivityTimer        3


############### 1. Cluster End point ############################

# The end point of the first dnode in the cluster to be connected to when this dnode or the CLI utility is started
firstEp                   docker-desktop:6030

# The end point of the second dnode to be connected to if the firstEp is not available
# secondEp


############### 2. Configuration Parameters of current dnode #####

# The FQDN of the host on which this dnode will be started. It can be IP address
# fqdn                      hostname

# The port for external access after this dnode is started
# serverPort                6030

**Comment by FlowerBirds** [comment]
最后在/etc/hosts里面配置了taos server的主机名和ip映射，可以正常连接了

**Comment by Andhros** [comment]
Can you explain it better please? I don't understand how to solve this. I'm running tdengine on docker by the way.

**Comment by GXISH** [comment]
You need to configure the hostname in the /etc/hosts file. You can use the ping command to verify if your configuration is successful. TDengine relies on the hostname as a contact identifier, rather than solely relying on the internal IP address. Do you understand?

**Comment by GXISH** [comment]
> 你能解释得更好吗？我不明白如何解决这个问题。顺便说一下，我正在码头工人上运行 tdengine。

You need to configure the hostname in the /etc/hosts file. You can use the ping command to verify if your configuration is successful. TDengine relies on the hostname as a contact identifier, rather than solely relying on the internal IP address.

**Comment by GXISH** [comment]
> Can you explain it better please? I don't understand how to solve this. I'm running tdengine on docker by the way.

You need to configure the hostname in the /etc/hosts file. You can use the ping command to verify if your configuration is successful. TDengine relies on the hostname as a contact identifier, rather than solely relying on the internal IP address.

**Comment by FlowerBirds** [comment]
@Andhros you can add hostname in YAML：
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: tdengine-client
spec:
  containers:
    - name: mycontainer
      image: myimage
  hostAliases:
    - ip: "192.168.0.10"
      hostnames:
        - "tdengine-server.com"

```
Try it.

**Comment by FlowerBirds** [comment]
Or use add-host in docker command:
```bash
Aliases:
  docker container run, docker run

Options:
      --add-host list                  Add a custom host-to-IP mapping (host:ip)

```
`docker run --add-host example.com:192.168.0.10 myimage`

It's important to add host at client side.

**Comment by smingflying** [comment]
![屏幕截图 2023-11-10 125049](https://github.com/taosdata/TDengine/assets/53905802/e6431ea0-fa13-4931-8c15-421437ec17c4) ERROR (0x80000020): some vnode/qnode/mnode(s) out of service

**Comment by yu285** [comment]
please make sure your client server‘s /etc/hosts file record correct FQDN value and corresponding IP

**Comment by ohhhyuan** [comment]
想问一下，你是如何将手动部署的TD数据映射到容器里的
