### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by liu666-dev** [taosdata/TDengine#23282]
linux服务器部署tdengine 3.0.1.0版本报错：
![57C8285F-1B80-4c9a-BC77-940D4163B724](https://github.com/taosdata/TDengine/assets/59222662/e3a46673-a027-45a6-93e3-1b690ca8cbad)
![4ACD04D5-F127-42d3-98C9-E2181176B848](https://github.com/taosdata/TDengine/assets/59222662/31935063-8177-4a46-8516-7fc1dfd243d8)
链接报错
![58F1A557-521F-4555-AD74-17107F0E50E6](https://github.com/taosdata/TDengine/assets/59222662/99ecb37e-211b-4598-92ba-547d1dc33471)

**Comment by liu666-dev** [comment]
目前的解决方案是删除数据
![CC56F445-C5AB-4834-AAD1-555E79EDB1B7](https://github.com/taosdata/TDengine/assets/59222662/4aab8590-1481-400e-9b18-bd59edc2da55)
能告知是什么原因造成的吗

**Comment by yu285** [comment]
这个版本已经回收了，是一年前 3.0刚发布的初始版本，这个错误码也不存在于现在代码中。建议清空环境，直接部署3.2.0.0 使用体验会大幅提升。
