### ISSUE TITLE
数据库连接断开无法访问

### ISSUE THREAD

**Issue by ytw1ytw** [taosdata/TDengine#23297]
![图片](https://github.com/taosdata/TDengine/assets/114635488/8fce4828-8d39-4f48-8511-c3694f69eb0f)
报错日志如上，目前需要建立40张超级表，1400张子表，运行几个小时后就会出现此类情况，数据库无法连接
版本：3.0.1.0

**Comment by yu285** [comment]
这个是初始版本，已经回收了。

重新部署一下 3.2.0.0 再使用吧，没有这些问题了。

如果还有疑问可以加我微信：

a15652223354
