### ISSUE TITLE
出现周期性性能抖动

### ISSUE THREAD

**Issue by jandison** [taosdata/TDengine#23307]
3.1.0.3版本
运行一段时候后发现会出现周期性的抖动，排查taosdlog日志发现每次抖动之前都会出现大量类似日志
10/16 20:00:05.619941 00021165 MND vgId:96, send drop ttl table request to vnode, time:1697457605
10/16 20:00:05.619807 00021165 MND vgId:85, send drop ttl table request to vnode, time:1697457605
10/16 20:00:05.619821 00021165 MND vgId:86, send drop ttl table request to vnode, time:1697457605
10/16 20:00:05.619834 00021165 MND vgId:87, send drop ttl table request to vnode, time:1697457605
10/16 20:00:05.619841 00021165 MND vgId:88, send drop ttl table request to vnode, time:1697457605
10/16 20:00:05.619857 00021165 MND vgId:89, send drop ttl table request to vnode, time:1697457605
10/16 20:00:05.619867 00021165 MND vgId:90, send drop ttl table request to vnode, time:1697457605
10/16 20:00:05.619883 00021165 MND vgId:91, send drop ttl table request to vnode, time:1697457605
10/16 20:00:05.619894 00021165 MND vgId:92, send drop ttl table request to vnode, time:1697457605
10/16 20:00:05.619908 00021165 MND vgId:93, send drop ttl table request to vnode, time:1697457605
10/16 20:00:05.619920 00021165 MND vgId:94, send drop ttl table request to vnode, time:1697457605
10/16 20:00:05.619930 00021165 MND vgId:95, send drop ttl table request to vnode, time:1697457605
10/16 20:00:05.619941 00021165 MND vgId:96, send drop ttl table request to vnode, time:1697457605
10/16 20:00:05.619950 00021165 MND vgId:97, send drop ttl table request to vnode, time:1697457605
10/16 20:00:05.619965 00021165 MND vgId:98, send drop ttl table request to vnode, time:1697457605
10/16 20:00:05.619975 00021165 MND vgId:99, send drop ttl table request to vnode, time:1697457605
10/16 20:00:05.619990 00021165 MND vgId:100, send drop ttl table request to vnode, time:1697457605
10/16 20:00:05.619997 00021165 MND vgId:101, send drop ttl table request to vnode, time:1697457605
10/16 20:00:05.620012 00021165 MND vgId:102, send drop ttl table request to vnode, time:1697457605
10/16 20:00:05.620020 00021165 MND vgId:103, send drop ttl table request to vnode, time:1697457605
随后会集中触发大量的head，data，sma文件物理删除，日志如下
10/16 20:00:05.630547 00021173 TSD file:/data/taos/data/vnode/vnode18/tsdb/v18f157051ver3060.head is removed
10/16 20:00:05.630616 00021174 TSD file:/data/taos/data/vnode/vnode26/tsdb/v26f157051ver3056.head is removed
10/16 20:00:05.630715 00021172 TSD file:/data/taos/data/vnode/vnode39/tsdb/v39f157051ver3053.head is removed
10/16 20:00:05.630728 00021175 TSD file:/data/taos/data/vnode/vnode8/tsdb/v8f157051ver3058.head is removed
10/16 20:00:05.632703 00021173 TSD file:/data/taos/data/vnode/vnode18/tsdb/v18f157051ver3035.data is removed
10/16 20:00:05.632797 00021172 TSD file:/data/taos/data/vnode/vnode39/tsdb/v39f157051ver3027.data is removed
10/16 20:00:05.632910 00021174 TSD file:/data/taos/data/vnode/vnode26/tsdb/v26f157051ver3033.data is removed
10/16 20:00:05.633092 00021175 TSD file:/data/taos/data/vnode/vnode8/tsdb/v8f157051ver3032.data is removed
10/16 20:00:05.633328 00021173 TSD file:/data/taos/data/vnode/vnode18/tsdb/v18f157051ver3035.sma is removed
10/16 20:00:05.633409 00021172 TSD file:/data/taos/data/vnode/vnode39/tsdb/v39f157051ver3027.sma is removed
10/16 20:00:05.633503 00021174 TSD file:/data/taos/data/vnode/vnode26/tsdb/v26f157051ver3033.sma is removed
10/16 20:00:05.633703 00021175 TSD file:/data/taos/data/vnode/vnode8/tsdb/v8f157051ver3032.sma is removed
实际业务中并没有配置表的ttl，请问是否有参数控制该机制？

**Comment by yu285** [comment]
可以加我微信远程排查一下

a15652223354
