### ISSUE TITLE
springboot连接集群，关闭集群中配置为firstEp的节点，会报无法建立连接

### ISSUE THREAD

**Issue by TomZhiYu** [taosdata/TDengine#23311]
org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [select * from meters limit 20;]; SQL state []; error code [-2147483637]; TDengine ERROR (0x8000000b): Unable to establish connection; nested exception is java.sql.SQLException: TDengine ERROR (0x8000000b): Unable to establish connection

**Comment by hoilung** [comment]
你这是主节点挂了。肯定就访问不了了，
最近测试也发现类似问题，3个节点（1个mnode，2个dnode），想添加其中一个为mnode，直接服务挂了。添加都添加不上，
找官网文档说只能添加1或3个mnode，站内文章又说最多不能超过3个，如果只能1或者3个，想添加第三个就的先加第二个，就是加上，还是说最小dnode和mnode之间又啥最小限制？

**Comment by yu285** [comment]
> 你这是主节点挂了。肯定就访问不了了， 最近测试也发现类似问题，3个节点（1个mnode，2个dnode），想添加其中一个为mnode变成2个mnode，直接服务挂了。添加都添加不上， 找官网文档说只能添加1或3个mnode，站内文章又说最多不能超过3个，如果只能1或者3个，想添加第三个就的先加第二个，就是加不上，还是说最小dnode和mnode之间又啥最小限制？

使用新版本3210，建mnode不会导致服务挂，除非是bug，使用新版本不会有这种问题。
