### ISSUE TITLE
在使用的集群中drop mnode之后重新create mnode不成功

### ISSUE THREAD

**Issue by lb112218** [taosdata/TDengine#23323]
**Bug Description**
在使用的集群中，drop mnode后, 再重新 create mnode，log显示一直是redoAction，如下图一。
经过20多分钟的等待后，kill 了 这个transaction，之后显示mnode的role变成了learner如图二，
再之后想要create 或者 drop mnode 都会失败如图二中显示：DB error: Sync timeout。
请问如何解决？

**To Reproduce**
1. 有3个节点的已配置集群（01，02，03），3个dnode，3个mnode
2. 已有数据导入
3. drop 除主节点外的2个mnode（02，03）
4. 重新create mnode用原来的dnode（02）
5. 得到很久的等待与图一的log
6. kill transaction
7. should reproduce the error

**Expected Behavior**
希望能删除learner这个role的mnode然后重新 成功加回2原来2个mnode

**Screenshots**
图一：
![20231018-182909](https://github.com/taosdata/TDengine/assets/124237245/201928e5-e283-4b33-af0c-852c43cf1e97)
图二：
![20231018-182921](https://github.com/taosdata/TDengine/assets/124237245/0b4e1e6e-1227-4c6d-8171-e1a002a109c9)

**Environment (please complete the following information):**
 - OS: Debian 10.0
 - Memory 32g, CPU 8 vCPUs, current Disk Space 500g  
 - TDengine Version 3.1.1
 - x3 个ecs

**Additional Context**

**Comment by yu285** [comment]
请问问题还存在吗？可以加我微信 a15652223354 做具体排查。
