### ISSUE TITLE
使用druid 1.2.4进行插入数据异常

### ISSUE THREAD

**Issue by Jiaxinbbbbbb** [taosdata/TDengine#23339]
插入记录时自动建表
在xml文件中写的sql
   <insert id="insertInformationDO">
        INSERT INTO s${po.clientId} USING sun TAGS (#{po.clientId},#{po.ICCID}) (
           ts,
           warn_bit,
           status_bit,
           latitude,
           longitude,
           altitude,
           speed,
           direction,
           date_time,
           mileage,
           signal_strength,
           gnss_count,
           batty_value,
           battery_remaining_capacity
           solar_panel_charging_voltage,
           charging_state,
           version,
           client_id,
           iccid
        ) VALUES
            (NOW,
            ${po.warnBit},
            ${po.statusBit},
            ${po.latitude},
            ${po.longitude},
            ${po.altitude},
            ${po.speed},
            ${po.direction},
            ${po.dateTime},
            ${po.mileage},
            ${po.signalStrength},
            ${po.gnssCount},
            ${po.battyValue},
            ${po.batteryRemainingCapacity},
            ${po.solarPanelChargingVoltage},
            ${po.chargingState},
            ${po.version},
            #{po.clientId},
            #{po.ICCID}
            )
    </insert>
    但是执行之后会报 syntax error, error in :'USING sun TAGS (?,?) (
           ts, pos 34, line 1, column 32, token IDENTIFIER sun，（但是我同样的sql，我在demo中使用的是HikariDataSource，它就不会有这个问题）虽然它抛异常了但是它能执行成功，数据库里面有数据，请问有解决的办法吗？

**Comment by Kiki513H** [comment]
解决了没有？

**Comment by Jiaxinbbbbbb** [comment]
> 解决了没有？

USING sun TAGS (#{po.clientId},#{po.ICCID}) 我把这个删了就不会报异常了
