### ISSUE TITLE
double free or corruption (!prev)

### ISSUE THREAD

**Issue by zy405677275** [taosdata/TDengine#2333]
**Bug Description**
执行数据查询时，报出 double free or corruption (!prev) ，并且导致web容器终止运行

**Comment by Aries-Lee1991** [comment]
we'll check it.

**Comment by Aries-Lee1991** [comment]
请报一下版本号，和环境，谢谢。

**Comment by zy405677275** [comment]
版本：1.6.5.8
系统：Centos8.5
![image](https://user-images.githubusercontent.com/8521982/85387868-f1c24d80-b577-11ea-9029-06681b5b468e.png)

**Comment by Aries-Lee1991** [comment]
您好，可以先升级一下1.6.6.0，看看是否还有这个问题的存在。
