### ISSUE TITLE
TDengine3，how to setup a Arbitrator Node or how to set one node only as management node which will not be involved in data store and computation.

### ISSUE THREAD

**Issue by zhanzhen-sh** [taosdata/TDengine#23357]
TDengine3，how to setup an Arbitrator Node or how to set one node only as management node which will not be involved in data store and computation.

On TDengine2.x, an Arbitrator Node can be setup, but no document mentions this point in TDengine3 document.

**Comment by yu285** [comment]
There is no arbitrator in TDengine 3.0 .

please read our official document to get new features in TDengine 3.0

**Comment by yu285** [comment]
TDengine use standard raft  to achieve consistency
