### ISSUE TITLE
使用 last_row(*) 方法，返回列名 附带last_row

### ISSUE THREAD

**Issue by jiangchengshi** [taosdata/TDengine#23351]
已升级最新版本 3.2.0.0，新插入数据后，执行 ` SELECT last_row(*) FROM data_record_1712990094586122241;` ，返回列名附带了last_row，如下：
![image](https://github.com/taosdata/TDengine/assets/21210629/0707f9fe-1ba9-467f-a313-f8c900584b7d)

**Comment by laiyongtao** [comment]
keepColumnName 配置项。https://docs.taosdata.com/reference/config/
