### ISSUE TITLE
Java进行数据订阅报错：consumer reference is null or has been destroyed

### ISSUE THREAD

**Issue by meichuannenku** [taosdata/TDengine#23365]
连接本地服务时没有问题，但是连接线上服务报错。
在TMQConnector的createTopic方法中抛出异常，执行：
        if (topic < TMQ_SUCCESS) {
            throw TSDBError.createSQLException(ERROR_TMQ_CONSUMER_NULL);
        }
其中变量topic为-120，变量taos为0

**Comment by meichuannenku** [comment]
超级表建表语句：CREATE STABLE `stdevice` (`ts` TIMESTAMP, `rotation` INT, `magnification` INT, `stress` INT, `feed` INT, `load` INT, `status` TINYINT UNSIGNED) TAGS (`group_id` VARCHAR(20), `type` VARCHAR(10)) SMA(`ts`,`rotation`,`magnification`,`stress`,`feed`,`load`)
创建主题语句：create topic topic_test as select * from yst.stdevice 
线上服务使用docker部署

**Comment by meichuannenku** [comment]
JAVA代码：
消费者：
@Component
public class ConsumerHandler implements Consumer{

    private static String GROUP_ID;
    private static String TOPICNAME;

    private TaosConsumer<StDeviceEntity> consumer;
    private ExecutorService executors;

    //消息队列消息拉取是否开启
    private volatile boolean active = true;

    private AtomicInteger count = new AtomicInteger();

    public static Properties initConfig() {
        GROUP_ID = "test";
        TOPICNAME = "topic_test";

        Properties properties = new Properties();
        properties.setProperty(TMQConstants.BOOTSTRAP_SERVERS, HOST_NAME);
        properties.setProperty(TMQConstants.MSG_WITH_TABLE_NAME, "true");
        properties.setProperty(TMQConstants.ENABLE_AUTO_COMMIT, "true");
        properties.setProperty(TMQConstants.CONNECT_USER, USERNAME);
        properties.setProperty(TMQConstants.CONNECT_PASS, PASSWORD);
        properties.setProperty(TMQConstants.GROUP_ID, GROUP_ID);
        properties.setProperty(TMQConstants.VALUE_DESERIALIZER,
                "com.uniorange.dcs.deserializer.StdeviceDeserializer");
        return properties;
    }

    /**
     * 项目启动时完成初始化配置
     */
    @PostConstruct
    public void initTaosConfig() {
        Properties properties = initConfig();
        try {
            //创建消费者实例
            consumer = new TaosConsumer<>(properties);
            List<String> topics = new ArrayList<>();
            topics.add(TOPICNAME);
            //订阅主题
            consumer.subscribe(topics);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

    }

    /**
     * 多线程批量消费(执行这个方法即可循环拉取消息)
     *
     * @param workerNum
     */
    public void execute(int workerNum) {
        active = true;
        executors = new ThreadPoolExecutor(workerNum, 20, 10,
                TimeUnit.SECONDS, new ArrayBlockingQueue<>(2000), new ThreadPoolExecutor.CallerRunsPolicy());
        while (active) {
            try {
                ConsumerRecords<StDeviceEntity> records = consumer.poll(Duration.ofMillis(100));
                if (!records.isEmpty()) {
                    //将消息交给线程池认领
                    executors.submit(new TaskWorker(records,this));
                }
            } catch (SQLException e) {
                throw new RuntimeException(e);
            }
        }
        System.out.println("ConsumerHandler: "+count.get());
    }

    /**
     * 停止拉取消息
     */
    public void stopTaosPoll() {
        this.active = false;
    }

    @Override
    public void addCount(int sum) {
        this.count.addAndGet(sum);
    }
}

public interface Consumer {

//    public static final String HOST_NAME = "localhost:6030";
    public static final String HOST_NAME = "服务器ip:6030";
    public static final String USERNAME = "root";
    public static final String PASSWORD = "taosdata";

    void addCount(int sum);

}

**Comment by yu285** [comment]
麻烦提供一下版本信息

**Comment by meichuannenku** [comment]
> 麻烦提供一下版本信息

服务器上的是3.1.1.1（docker），本地的是windows版本的3.0.7.1。java客户端使用的maven依赖是taos-jdbcdriver 3.2.2

**Comment by yu285** [comment]
客户端和服务端版本要保持一致先

**Comment by meichuannenku** [comment]
> 客户端和服务端版本要保持一致先

我已经按照官网将客户端依赖改为3.2.5版本，但是还是报错

**Comment by yu285** [comment]
taos.dll 要属于3.1.1.0 客户端的。你要安装 3.1.1.0 的 windows 客户端。
