### ISSUE TITLE
centos虚拟机空间良好，却上报存储信息空间不足问题

### ISSUE THREAD

**Issue by Alexyang90** [taosdata/TDengine#23388]
1.磁盘空间如下
![1698132462667](https://github.com/taosdata/TDengine/assets/13196233/75647808-38d4-41f8-ac6e-24361d6d885d)
2.数据日志空间如下
![1698132550252](https://github.com/taosdata/TDengine/assets/13196233/a33327d5-16a7-484d-ad28-41904dfe8db8)
但是后台插入数据时报TDengine ERROR (0x8000012e): No enough disk space
麻烦工作人员给看看，谢谢啦

**Comment by yu285** [comment]
检查下客户端的tmpDir

**Comment by liudainyong** [comment]
No enough disk space 有可能不是硬盘满了,而是Inode使用率满了
