### ISSUE TITLE
how to optimize the reading of data?

### ISSUE THREAD

**Issue by zzboy** [taosdata/TDengine#2339]
使用TDengine的过程中，发现一个非常严重的问题，我的数据很有特点，一个memfile中70%的设备都只有一两条数据，绝大部分数据都来自很少量的设备，但是这些设备又不好做分割。
我有一个读的场景是读一个设备最近的1000条数据，当有这种查询的时候，我发现磁盘的随机读IO特别严重。
last文件的我设置的比较小，主要是为了避免写放大。
我这种场景有什么办法能优化吗？

**Comment by liuyq-617** [comment]
根绝您的描述，还是推荐您把设备分到两个库里，分别优化
