### ISSUE TITLE
Java Rest timezone issue

### ISSUE THREAD

**Issue by changzhihua** [taosdata/TDengine#23394]
服务端版本：3.1.1.0
taos-jdbcdriver: 3.2.5
使用Java REST方式连接，用API查询出来的数据比命令行SQL查询出来的数据时区多8，
在REST连接中，指定tz(TSDBDriver.HTTP_TIME_ZONE) 参数无效。

**Comment by yu285** [comment]
jdbc-rest 将结果转为“当前应用所在服务器的时区”
