### ISSUE TITLE
官网的文档中的java客户端连接测试类有错误

### ISSUE THREAD

**Issue by riyun1989** [taosdata/TDengine#234]
https://www.taosdata.com/cn/documentation/connector/#Java-Connector，测试类中的这行有错误`connProps.setProperty(TSDBDriver.PROPERTY_KEY_TIMEZONE, "UTC-8");`，应该是：`connProps.setProperty(TSDBDriver.PROPERTY_KEY_TIME_ZONE, "UTC-8");`

**Comment by johnnyhou327** [comment]
@riyun1989 多谢指出，已经修改！
