### ISSUE TITLE
 I use EMQX with  TDengine   to achieve  MQTT information visualization

### ISSUE THREAD

**Issue by CJT1111** [taosdata/TDengine#23425]
您好，我使用EMQX配合咱得TD做MQTT信息可视化，首先我得EMQX的配置如下
<img width="93" alt="wps_doc_0" src="https://github.com/taosdata/TDengine/assets/111559992/09c9a1e0-d0db-44c7-8f2f-10ebdb883eeb">
部署的IP地址为
![wps_doc_2](https://github.com/taosdata/TDengine/assets/111559992/05bb3366-ae07-4f99-8876-0ab05fe22067)
我想知道该界面如何填写
![wps_doc_1](https://github.com/taosdata/TDengine/assets/111559992/2026aa83-e093-4110-94d7-915c282a8680)

**Comment by feici02** [comment]
这里假设从EMQX消费的数据已写入TDengine
Grafana是通过taosadapter访问TDengine的，应填写taosadapter的IP地址和端口号(6041), 如下图所示：
![image](https://github.com/taosdata/TDengine/assets/5568663/8479572c-4857-4385-8347-ac7f8c0d1887)
