### ISSUE TITLE
window环境下taos插入数据异常

### ISSUE THREAD

**Issue by graceZxy** [taosdata/TDengine#23473]
**Bug Description**
window环境下taos插入数据异常

**To Reproduce**
版本：3.0.3.1
环境：Linux 、Windows
描述：
每秒插入2W条数据，Linux正常；
情况1：windows环境下几小时后即卡住，查询超级表提示表不存在“table doesnot is exits”；
情况2：报错弹框

报错弹框图片：

![image](https://github.com/taosdata/TDengine/assets/64307322/16eebbfe-7d67-43b9-936d-90f6b1adfe78)

**Comment by yu285** [comment]
3100 开始windows是企业版范畴了，为了方便使用和后续的升级，开源版用户请使用：

1.使用 linux 

2. 在windows 上使用docker

**Comment by graceZxy** [comment]
我是3.0.3.1，大版本应该是3.0版本。我可以理解为windows下，taos此版本不支持每秒2W这个量级的插入吗 ？这属于性能问题
