### ISSUE TITLE
tableName is null

### ISSUE THREAD

**Issue by qingsenmeng** [taosdata/TDengine#23489]
环境如下

tdengine版本：3.2.0.0
操作系统：linux
tdengine客户端版本：3.2.7
语言：java

<img width="413" alt="企业微信截图_16987563427826" src="https://github.com/taosdata/TDengine/assets/29728755/eb5e1b85-94cc-4b27-870e-4bf20008e922">

**Comment by yu285** [comment]
这个tablename 预期值是？

**Comment by qingsenmeng** [comment]
> 这个tablename 预期值是？

具体 子表名

**Comment by yu285** [comment]
可以加微信 a15652223354 做具体排查

**Comment by yu285** [comment]
<img width="548" alt="image" src="https://github.com/taosdata/TDengine/assets/74105241/11359d83-a4a0-48ec-84c0-7025c850ad3c">
<img width="499" alt="image" src="https://github.com/taosdata/TDengine/assets/74105241/678ad782-3af1-43d0-9622-9277fb0b5a7f">
<img width="605" alt="image" src="https://github.com/taosdata/TDengine/assets/74105241/eeeeedfa-62cf-4636-a07a-fff326f6710c">

**Comment by qingsenmeng** [comment]
经沟通，开源版本在 超级表及数据库订阅下，jdbc返回元数据不包含表名

**Comment by qingsenmeng** [comment]
经沟通，开源版本在 超级表及数据库订阅下，jdbc返回元数据不包含表名
