### ISSUE TITLE
tsdbScanAndTryFixFS failed at line 200 since No such file or directory, fid:9581

### ISSUE THREAD

**Issue by wuzhoushidao** [taosdata/TDengine#23492]
重启之后，数据库启动不了。
TSD ERROR vgId:3, tsdbScanAndTryFixFS failed at line 200 since No such file or directory, fid:9581
 TSD ERROR vgId:3, tsdbFSOpen failed at line 793 since No such file or directory
TSD ERROR vgId:3 tsdbUpgradeFileSystem failed at line 601 since No such file or directory
TSD ERROR vgId:3 tsdbOpenFS failed at line 736 since No such file or directory
 VND ERROR vgId:3, failed to open vnode tsdb since success
 DND ERROR vgId:3, failed to open vnode by thread:1 since success
是否有解决办法
版本：3.0.2.5 与 3.2.0.0
系统：centos7

**Comment by yu285** [comment]
数据文件损坏/丢失，需要依靠多副本或日常备份解决。

友情提示：开源版要尽量确保版本同步更新，防止旧版本bug影响。

**Comment by wuzhoushidao** [comment]
已解决，数据恢复了，此类问题可留言

**Comment by xiaohanbh** [comment]
@wuzhoushidao 请问是怎么解决的？

**Comment by wuzhoushidao** [comment]
> @wuzhoushidao 请问是怎么解决的？

简单来说就是先读取tsdb下CURRENT的文件内容，然后去掉没有fid数据（报错没有的fid数据是已经删除，这个恢复不了），反写CURRENT，怎么读取、反写、格式什么的开源代码里面都有

**Comment by xiaohanbh** [comment]
> > @wuzhoushidao 请问是怎么解决的？
> 
> 简单来说就是先读取tsdb下CURRENT的文件内容，然后去掉没有fid数据（报错没有的fid数据是已经删除，这个恢复不了），反写CURRENT，怎么读取、反写、格式什么的开源代码里面都有

大神，具体文件格式再源码哪里？

**Comment by wuzhoushidao** [comment]
> > > @wuzhoushidao 请问是怎么解决的？
> > 
> > 
> > 简单来说就是先读取tsdb下CURRENT的文件内容，然后去掉没有fid数据（报错没有的fid数据是已经删除，这个恢复不了），反写CURRENT，怎么读取、反写、格式什么的开源代码里面都有
> 
> 大神，具体文件格式再源码哪里？

根据你报错信息来找，不同版本位置可能不一样，类似我这个就在调用tsdbScanAndTryFixFS 这个方法的上面，有个函数读取tsdbLoadFSFromFile

**Comment by xiaohanbh** [comment]
> > > > @wuzhoushidao 请问是怎么解决的？
> > > 
> > > 
> > > 简单来说就是先读取tsdb下CURRENT的文件内容，然后去掉没有fid数据（报错没有的fid数据是已经删除，这个恢复不了），反写CURRENT，怎么读取、反写、格式什么的开源代码里面都有
> > 
> > 
> > 大神，具体文件格式再源码哪里？
> 
> 根据你报错信息来找，不同版本位置可能不一样，类似我这个就在调用tsdbScanAndTryFixFS 这个方法的上面，有个函数读取tsdbLoadFSFromFile

我这边是3.0.1.6版本；tsdbScanAndTryFixFS这个方法在哪个文件里面呀？我对源码不是很熟悉，没找到这个方法在哪个文件里？

**Comment by xiaohanbh** [comment]
> > > > > > @wuzhoushidao 请问是怎么解决的？
> > > > > 
> > > > > 
> > > > > 简单来说就是先读取tsdb下CURRENT的文件内容，然后去掉没有fid数据（报错没有的fid数据是已经删除，这个恢复不了），反写CURRENT，怎么读取、反写、格式什么的开源代码里面都有
> > > > 
> > > > 
> > > > 大神，具体文件格式再源码哪里？
> > > 
> > > 
> > > 根据你报错信息来找，不同版本位置可能不一样，类似我这个就在调用tsdbScanAndTryFixFS 这个方法的上面，有个函数读取tsdbLoadFSFromFile
> > 
> > 
> > 我这边是3.0.1.6版本；tsdbScanAndTryFixFS这个方法在哪个文件里面呀？我对源码不是很熟悉，没找到这个方法在哪个文件里？
> 
> 大哥，下载代码，ide打开搜索，vscode搜索代码不就好了

方便电话或微信沟通一下吗？我的手机号/微信：15010691339

**Comment by wuzhoushidao** [comment]
> ![image](https://private-user-images.githubusercontent.com/47447609/287605414-c99d4455-b933-4096-85cb-0c7e133bb096.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NzA2NjIsIm5iZiI6MTcwMTY3MDM2MiwicGF0aCI6Ii80NzQ0NzYwOS8yODc2MDU0MTQtYzk5ZDQ0NTUtYjkzMy00MDk2LTg1Y2ItMGM3ZTEzM2JiMDk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDA2MTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwY2M5MTgxMmFjOTM4MTM1NzkyMjViODljYTVhMWIzNGY2NWI2YmZhMDk3ZmYwNWEzNjFkNjFkMTJmNDc0MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n9BOhK5A-qqw7SBHXbDhpBnmd0Now0zGnHp5h3ihKLk) 我的也是这个错，有什么解决办法吗

简单来说就是先读取tsdb下CURRENT的文件内容，然后去掉没有fid数据（报错没有的fid数据是已经删除，这个恢复不了），反写CURRENT，怎么读取、反写、格式什么的开源代码里面都有
上面已经说了，需要读取，去掉没有的fid，反写就可以了。

**Comment by lion-brave** [comment]
@wuzhoushidao 具体应该怎么操作呢？不是很明白。非常感谢
