### ISSUE TITLE
想用TDengine与Matlab连接，碰到安装的问题

### ISSUE THREAD

**Issue by luoyueyue** [taosdata/TDengine#235]
TDengine 技术大牛：
感谢开源TDengine，我这两天刚接触，想用TDengine与Matlab连接，碰到安装的问题：按照文档的说明步骤中taos.lib在TDengine安装包内找不到，是漏放在安装 TDengine安装包内里了还是需另外在哪里下载？

将TDengine安装包内的taos.lib文件拷贝至${matlab_ root _dir}\MATLAB\R2017a\lib\win64

**Comment by guanshengliang** [comment]
windows的安装包里面有taos.dll，但是没有与这个taos.dll匹配的taos.lib，下次打包的时候会加上，请稍待

**Comment by luoyueyue** [comment]
TDengine 技术大牛：
       下次打包大概什么时候？如果时间较长的话能否先私发给我尝试学习一下？


--


顺祝：




                                                        罗岳




 

电话:15889558647

传真：

邮箱:19971949@163.com

网址:


在 2019-07-30 18:15:45，"slguan" <notifications@github.com> 写道：


windows的安装包里面有taos.dll，但是没有与这个taos.dll匹配的taos.lib，下次打包的时候会加上，请稍待

**Comment by luoyueyue** [comment]
TDengine 技术大牛：
       下次打包大概什么时候？如果时间较长的话能否先私发给我尝试学习一下？

**Comment by guanshengliang** [comment]
今天晚上会会更新，您明天早晨下载即可。

**Comment by luoyueyue** [comment]
刚下载TDengine Windows (1.8M)等都没找到taos.lib文件，传到哪个安装包啦？

**Comment by guanshengliang** [comment]
不好意思，昨天有个bug没有解决。
今天上传之后会再给您回消息，见谅。

**Comment by luoyueyue** [comment]
收到，客气啦，感谢及时回复！

**Comment by luoyueyue** [comment]
已经帮忙解决了吗？

**Comment by guanshengliang** [comment]
不好意思，忘记了
马上修改编译选项，以后的Windows包都会包含这个taos.lib文件。

**Comment by luoyueyue** [comment]
福音啊！感谢！！！

**Comment by luoyueyue** [comment]
新发布的tdengine-windows-client-x64-1.6.1.5已经包括了吗？还没找到呢？

**Comment by guanshengliang** [comment]
sorry,已记录到备忘录中,这次不会忘了

**Comment by guanshengliang** [comment]
这次发布的1.6.1.7版本包含了taos.lib
