### ISSUE TITLE
tdengine 客户端模式6030 可以通过nginx反向代理吗

### ISSUE THREAD

**Issue by flyrun9527** [taosdata/TDengine#23519]
tdengine 客户端模式6030 可以通过nginx反向代理吗
我配置反向代理无效

nginx中端口映射配置如下

proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_redirect off;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
client_max_body_size 10m;
client_body_buffer_size 128k;
proxy_connect_timeout 90;
proxy_send_timeout 90;
proxy_read_timeout 90;
proxy_buffers 32 4k;

如果不可以代理那么docker集群应该怎么使用客户端模式

**Comment by yu285** [comment]
可以配置，但是nginx具体配置方式我们没办法提供帮助。

另外客户端高可用可以参考：
https://www.taosdata.com/tdengine-engineering/2287.html

**Comment by haojiawei111** [comment]
解决了吗？ 我也一样的问题，代理端口84，客户端连接不上，日志显示客户端去连接6030端口了。

**Comment by flyrun9527** [comment]
改用 6041 jdbc连接，6030 客户端还要装东西太麻烦了
