### ISSUE TITLE
存储占用空间很大

### ISSUE THREAD

**Issue by random1919** [taosdata/TDengine#23527]
使用版本
linux 
docker安装 3.0.3.0
创建两张超级表后创建子表，只加了15W数据硬盘占用就达到了39G

创建的语句如下

create stable if not exists DATABASE_3M.TABLE_NUMERICAL (ts timestamp,pointvalue float,pointstatus nchar(32)) tags(eqpId nchar(32),tenantid nchar(32),pointid varchar(32));

create stable if not exists DATABASE_3M.TABLE_STRING (ts timestamp,pointvalue nchar(100),pointstatus nchar(32)) tags(eqpId nchar(32),tenantid nchar(32),pointid varchar(32))

同时创建四个流计算
CREATE STREAM IF NOT EXISTS STREAM_6h INTO DATABASE_6M.TABLE_NUMERICAL_6h SUBTABLE(CONCAT('p_6h_',pid)) AS  SELECT _WSTART AS TS, MAX(POINTVALUE) AS MAX_VALUE ,MIN(POINTVALUE) AS MIN_VALUE, AVG(POINTVALUE) AS AVG_VALUE, FIRST(POINTVALUE) AS FIRST_VALUE, LAST(POINTVALUE) AS LAST_VALUE, APERCENTILE(POINTVALUE,50) AS APERCENTILE_VALUE, COUNT(POINTVALUE) AS COUNT_VALUE FROM DATABASE_3M.TABLE_NUMERICAL PARTITION BY POINTID PID  INTERVAL(6h) 

CREATE STREAM IF NOT EXISTS STREAM_1d INTO DATABASE_6M.TABLE_NUMERICAL_1d SUBTABLE(CONCAT('p_1d_',pid)) AS  SELECT _WSTART AS TS, MAX(POINTVALUE) AS MAX_VALUE ,MIN(POINTVALUE) AS MIN_VALUE, AVG(POINTVALUE) AS AVG_VALUE, FIRST(POINTVALUE) AS FIRST_VALUE, LAST(POINTVALUE) AS LAST_VALUE, APERCENTILE(POINTVALUE,50) AS APERCENTILE_VALUE, COUNT(POINTVALUE) AS COUNT_VALUE FROM DATABASE_3M.TABLE_NUMERICAL PARTITION BY POINTID PID  INTERVAL(1d) 

CREATE STREAM IF NOT EXISTS STREAM_7d INTO DATABASE_6M.TABLE_NUMERICAL_7d SUBTABLE(CONCAT('p_7d_',pid)) AS  SELECT _WSTART AS TS, MAX(POINTVALUE) AS MAX_VALUE ,MIN(POINTVALUE) AS MIN_VALUE, AVG(POINTVALUE) AS AVG_VALUE, FIRST(POINTVALUE) AS FIRST_VALUE, LAST(POINTVALUE) AS LAST_VALUE, APERCENTILE(POINTVALUE,50) AS APERCENTILE_VALUE, COUNT(POINTVALUE) AS COUNT_VALUE FROM DATABASE_3M.TABLE_NUMERICAL PARTITION BY POINTID PID  INTERVAL(7d) 

CREATE STREAM IF NOT EXISTS STREAM_1n INTO DATABASE_1Y.TABLE_NUMERICAL_1n SUBTABLE(CONCAT('p_1n_',pid)) AS  SELECT _WSTART AS TS, MAX(POINTVALUE) AS MAX_VALUE ,MIN(POINTVALUE) AS MIN_VALUE, AVG(POINTVALUE) AS AVG_VALUE, FIRST(POINTVALUE) AS FIRST_VALUE, LAST(POINTVALUE) AS LAST_VALUE, APERCENTILE(POINTVALUE,50) AS APERCENTILE_VALUE, COUNT(POINTVALUE) AS COUNT_VALUE FROM DATABASE_3M.TABLE_NUMERICAL PARTITION BY POINTID PID  INTERVAL(1n) 
流式计算的表中数据很少，因为添加的数据时间间隔很短，只是存储普通数据的表就占用了很大的空间。

![image](https://github.com/taosdata/TDengine/assets/63285451/1baedfed-c480-4ba1-b703-92ff813ef475)

请问为何占用空间很大，其中并没有存储null数据，同时观察到使用内存也在提高，将流删除后内存比较稳定。
有解决的办法吗，谢谢

![image](https://github.com/taosdata/TDengine/assets/63285451/dcc930e9-146c-4473-aaf6-e5b6a5f04c05)

**Comment by random1919** [comment]
今天查看占用空间，发现vnode中的tq文件中的stream占用非常大，是流导致的原因吗，另一个服务服务中没有启用流的存储占用很小。
![image](https://github.com/taosdata/TDengine/assets/63285451/6ba45f92-29c5-46a6-9946-4246a689502d)

**Comment by yu285** [comment]
流计算早就重构过，麻烦升级到 3.2.0.0 ，还有问题可以加我微信远程排查：

a15652223354
