### ISSUE TITLE
version: 3.2.0.0 ，The result is not correct when two stream computings are used synchronously

### ISSUE THREAD

**Issue by RSongR** [taosdata/TDengine#23537]
version: 3.2.0.0 版，当一个表有两个流计算时，有数据插入，其中一个流计算的数据不全，两个流计算的合计不一致，有什么解决办法

**Comment by yu285** [comment]
麻烦提供一下具体的截图，多谢

**Comment by RSongR** [comment]
就是对两个表进行两种流计算，算出来的合计不一致，需要合计不同的截图吗？
使用的是  trigger at_once 模式，trigger MAX_DELAY time 模式没有使用明白

**Comment by RSongR** [comment]
create stream stream_billsale_day trigger at_once IGNORE EXPIRED 0 into streambillsaleday as 
select _wstart as date,tenantid,shopid,devicecode,productid,sum(case when IsReturn=0 then qty else 0 end) as saleqty,sum(case when IsReturn=0 then money else 0 end) as salemoney,sum(case when IsReturn=1 then 0-qty else 0 end) as refundqty,sum(case when IsReturn=1 then 0-money else 0 end) as refundmoney from billsale PARTITION BY tenantid,shopid,devicecode,productid interval (1d);


create stream stream_billsale_category trigger at_once IGNORE EXPIRED 0 into streambillsalecategory as 
select _wstart as date,tenantid,shopid,devicecode,sum(case when IsReturn=0 then qty else 0 end) as saleqty,sum(case when IsReturn=0 then money else 0 end) as salemoney,sum(case when IsReturn=1 then 0-qty else 0 end) as refundqty,sum(case when IsReturn=1 then 0-money else 0 end) as refundmoney from billsale PARTITION BY tenantid,shopid,devicecode interval (1d);
![image](https://github.com/taosdata/TDengine/assets/134750976/c532c56f-e108-44e4-93af-06a7fcf86c22)

**Comment by RSongR** [comment]
TRIGGER&nbsp;&nbsp;AT_ONCE 模式


另外 麻烦给&nbsp;TRIGGER&nbsp;MAX_DELAY time 模式举个例子

宋~
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taosdata/TDengine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月7日(星期二) 上午10:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [taosdata/TDengine] version: 3.2.0.0 版，当一个表有两个流计算时，有数据插入，其中一个流计算的数据不全，两个流计算的合计不一致，有什么解决办法 (Issue #23537)





 
麻烦提供一下具体的截图，多谢

**Comment by RSongR** [comment]
参数设置的问题，修改参数后，问题解决
