### ISSUE TITLE
插入数据时，当子表数量达到百万级别时，性能下降很严重，程序会阻塞几分钟再次执行插入，持续循环

### ISSUE THREAD

**Issue by qiuminkai** [taosdata/TDengine#23538]
**Performance Issue** 
Any questions related to TDengine's performance can be discussed here.

**Problem Description** 
3.1.1.0使用脚本单线程循环往数据库里插入数据，子表到达百万级别以后，会出现卡顿，大概几分钟之后又会继续插入，服务器配置也远没有达到限制，截图是服务器信息，分别进行了单条循环插入，多条循环插入。

**To Reproduce**
1. Database parameters used: 
 ```show databases```
![image](https://github.com/taosdata/TDengine/assets/149778629/f89e1052-d378-4e23-8801-3d96851a437e)

2. Verbs used: Insert/Import/Select?
insert
4. Describe the total amount of data
![image](https://github.com/taosdata/TDengine/assets/149778629/8729e06e-cdf9-4410-a1fe-829536f7e1cd)
6. Observed performance vs. expected performance

**Screenshots**
<img width="1014" alt="b2290afbf38ee445326f5c3feb585c8" src="https://github.com/taosdata/TDengine/assets/149778629/52ae9e4b-d46a-4840-b11c-6b60cd48a3e0">
<img width="1020" alt="71ff1fe3a223b4f9142006ffdfecf29" src="https://github.com/taosdata/TDengine/assets/149778629/63ab1915-7f9c-4acd-85b9-578af80a8517">
<img width="1014" alt="31fd074937ebd2581bd066d43d7aa8b" src="https://github.com/taosdata/TDengine/assets/149778629/fbc1916d-3d92-4adb-854a-4e5ed7e7f25c">
<img width="510" alt="7e457b1d087304a9d3230312d4abdce" src="https://github.com/taosdata/TDengine/assets/149778629/96d3a504-93f7-4fd6-8e6b-55a6a6816439">
<img width="255" alt="d9b14cc758b82e98cfdf7fd39d3e78d" src="https://github.com/taosdata/TDengine/assets/149778629/88565c88-789c-4a7a-bff8-ad6225e02e50">
<img width="1033" alt="a011faf5d8f69fa26b7ad7f2b543842" src="https://github.com/taosdata/TDengine/assets/149778629/73c234ef-e036-466b-ad0c-ff1ab92f2cac">
<img width="1021" alt="05680c9b0d09261f8cec6cc6266c234" src="https://github.com/taosdata/TDengine/assets/149778629/e9bdce2f-3daa-4b05-b770-dce0c2e9ac03">

**Environment (please complete the following information):**

* OS: [e.g. CentOS 7.0]
* CentOS 7.9
* Memory, CPU, current Disk Space
* 32核64g500g
* TDengine Version [e.g. 1.6.1.7]
* 3.1.1.0

**Additional Context**

**Comment by Dawnflying** [comment]
2.6版本也遇到了同样的问题

**Comment by qiuminkai** [comment]
已解决

**Comment by Dawnflying** [comment]
> 已解决

能说下如何解决的吗？
