### ISSUE TITLE
select count  generate  coredump 

### ISSUE THREAD

**Issue by march3008** [taosdata/TDengine#2354]
taos> select count(*) from arc_device_type_00f4;

DB error: failed to connect to server

# #

**Comment by Aries-Lee1991** [comment]
OK, the related R&D will contact u.

**Comment by Aries-Lee1991** [comment]
Please attach the version info. .

**Comment by Aries-Lee1991** [comment]
Long time no reply. I closed the issue. If any question is existed, you can reopen it at any time.
