### ISSUE TITLE
TDengine启动状态错误 Active: failed (Result: exit-code)

### ISSUE THREAD

**Issue by liyubo-debug** [taosdata/TDengine#23558]
**启动后状态错误**
[root@td1 TDengine-server-3.2.0.0]# systemctl start taosd
[root@td1 TDengine-server-3.2.0.0]# systemctl status taosd
● taosd.service - server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2023-11-06 13:56:00 CST; 7s ago
  Process: 226482 ExecStartPre=/usr/local/taos/bin/startPre.sh (code=exited, status=0/SUCCESS)
  Process: 226489 ExecStart=/usr/bin/taosd (code=exited, status=255/EXCEPTION)
 Main PID: 226489 (code=exited, status=255/EXCEPTION)

11月 06 13:56:00 td1 systemd[1]: taosd.service: Service RestartSec=100ms expired, scheduling restart.
11月 06 13:56:00 td1 systemd[1]: taosd.service: Scheduled restart job, restart counter is at 3.
11月 06 13:56:00 td1 systemd[1]: Stopped server service.
11月 06 13:56:00 td1 systemd[1]: taosd.service: Start request repeated too quickly.
11月 06 13:56:00 td1 systemd[1]: taosd.service: Failed with result 'exit-code'.
11月 06 13:56:00 td1 systemd[1]: Failed to start server service.

**配置文件为：**
############### 1. Cluster End point ############################

# The end point of the first dnode in the cluster to be connected to when this dnode or the CLI utility is started
firstEp                   td1:6030

# The end point of the second dnode to be connected to if the firstEp is not available
 secondEp                td2:6030

############### 2. Configuration Parameters of current dnode #####

# The FQDN of the host on which this dnode will be started. It can be IP address
fqdn                      td1

# The port for external access after this dnode is started
 serverPort                6030

# The maximum number of connections a dnode can accept
# maxShellConns             5000

# The directory for writing log files, if you are using Windows platform please change to Windows path
 logDir                    /home/tdengine/taos3.2.0.0/server/log

# All data files are stored in this directory, if you are using Windows platform please change to Windows path
 dataDir                   /home/tdengine/taos3.2.0.0/server/data

# temporary file's directory, if you are using Windows platform please change to Windows path
tempDir                   /home/tdengine/taos3.2.0.0/server/tmp/

“报错”
[root@td1 bin]# ./taosd
11/06 14:01:01.363187 00226612 UTL apoll url not load
11/06 14:01:01.363265 00226612 UTL load from cfg file /etc/taos//taos.cfg success
11/06 14:01:01.363285 00226612 UTL env file:.env not load
11/06 14:01:01.363312 00226612 UTL load from env variables cfg success
11/06 14:01:01.363448 00226612 DND startup path:/usr/local/taos/bin args:./taosd
11/06 14:01:01.363730 00226612 UTL apoll url not load
11/06 14:01:01.363776 00226612 UTL load from cfg file /etc/taos//taos.cfg success
11/06 14:01:01.363789 00226612 UTL env file:.env not load
11/06 14:01:01.363799 00226612 UTL load from env variables cfg success
11/06 14:01:01.363951 00226612 UTL                      global config
11/06 14:01:01.363962 00226612 UTL =================================================================
11/06 14:01:01.363969 00226612 UTL cfg_file     firstEp                  td1:6030
11/06 14:01:01.363976 00226612 UTL cfg_file     secondEp                 td2:6030
11/06 14:01:01.363983 00226612 UTL cfg_file     fqdn                     td1
11/06 14:01:01.364009 00226612 UTL cfg_file     serverPort               6030
11/06 14:01:01.364016 00226612 UTL cfg_file     tempDir                  /home/tdengine/taos3.2.0.0/server/tmp/
11/06 14:01:01.364041 00226612 UTL default      minimalTmpDirGB          1.00
11/06 14:01:01.364051 00226612 UTL default      shellActivityTimer       3
11/06 14:01:01.364058 00226612 UTL default      compressMsgSize          -1
11/06 14:01:01.364066 00226612 UTL default      compressColData          -1
11/06 14:01:01.364072 00226612 UTL default      queryPolicy              1
11/06 14:01:01.364079 00226612 UTL default      enableQueryHb            1
11/06 14:01:01.364085 00226612 UTL default      enableScience            0
11/06 14:01:01.364092 00226612 UTL default      querySmaOptimize         0
11/06 14:01:01.364098 00226612 UTL default      queryPlannerTrace        0
11/06 14:01:01.364123 00226612 UTL default      queryNodeChunkSize       32768
11/06 14:01:01.364131 00226612 UTL default      queryUseNodeAllocator    1
11/06 14:01:01.364155 00226612 UTL default      keepColumnName           0
11/06 14:01:01.364162 00226612 UTL default      smlChildTableName        
11/06 14:01:01.364186 00226612 UTL default      smlTagName               _tag_null
11/06 14:01:01.364194 00226612 UTL default      smlTsDefaultName         _ts
11/06 14:01:01.364201 00226612 UTL default      smlDot2Underline         1
11/06 14:01:01.364208 00226612 UTL default      maxInsertBatchRows       1000000
11/06 14:01:01.364215 00226612 UTL default      maxRetryWaitTime         10000
11/06 14:01:01.364239 00226612 UTL default      useAdapter               0
11/06 14:01:01.364246 00226612 UTL default      crashReporting           1
11/06 14:01:01.364253 00226612 UTL default      queryMaxConcurrentTable  200
11/06 14:01:01.364260 00226612 UTL default      metaCacheMaxSize         -1
11/06 14:01:01.364267 00226612 UTL default      slowLogThreshold         3
11/06 14:01:01.364273 00226612 UTL default      slowLogScope             
11/06 14:01:01.364280 00226612 UTL default      numOfRpcThreads          2
11/06 14:01:01.364324 00226612 UTL default      numOfRpcSessions         10000
11/06 14:01:01.364333 00226612 UTL default      timeToGetAvailableConn   500000
11/06 14:01:01.364341 00226612 UTL default      keepAliveIdle            60
11/06 14:01:01.364382 00226612 UTL default      numOfTaskQueueThreads    4
11/06 14:01:01.364390 00226612 UTL cfg_file     dataDir                  /home/tdengine/taos3.2.0.0/server/data
11/06 14:01:01.364396 00226612 UTL default      minimalDataDirGB         2.00
11/06 14:01:01.364403 00226612 UTL default      supportVnodes            4
11/06 14:01:01.364409 00226612 UTL default      maxShellConns            50000
11/06 14:01:01.364417 00226612 UTL default      statusInterval           1
11/06 14:01:01.364423 00226612 UTL default      minSlidingTime           1
11/06 14:01:01.364430 00226612 UTL default      minIntervalTime          1
11/06 14:01:01.364436 00226612 UTL default      maxNumOfDistinctRes      10000000
11/06 14:01:01.364443 00226612 UTL default      countAlwaysReturnValue   1
11/06 14:01:01.364449 00226612 UTL default      queryBufferSize          -1
11/06 14:01:01.364455 00226612 UTL default      printAuth                0
11/06 14:01:01.364461 00226612 UTL default      queryRspPolicy           0
11/06 14:01:01.364470 00226612 UTL default      numOfRpcThreads          2
11/06 14:01:01.364476 00226612 UTL default      numOfRpcSessions         10000
11/06 14:01:01.364492 00226612 UTL default      timeToGetAvailableConn   10000
11/06 14:01:01.364499 00226612 UTL default      keepAliveIdle            60
11/06 14:01:01.364505 00226612 UTL default      numOfCommitThreads       2
11/06 14:01:01.364511 00226612 UTL default      numOfMnodeReadThreads    1
11/06 14:01:01.364517 00226612 UTL default      numOfVnodeQueryThreads   4
11/06 14:01:01.364523 00226612 UTL default      ratioOfVnodeStreamThrea  4.00
11/06 14:01:01.364529 00226612 UTL default      numOfVnodeFetchThreads   4
11/06 14:01:01.364535 00226612 UTL default      numOfVnodeRsmaThreads    4
11/06 14:01:01.364541 00226612 UTL default      numOfQnodeQueryThreads   4
11/06 14:01:01.364550 00226612 UTL default      numOfSnodeSharedThreads  2
11/06 14:01:01.364558 00226612 UTL default      numOfSnodeUniqueThreads  2
11/06 14:01:01.364567 00226612 UTL default      rpcQueueMemoryAllowed    1542975078
11/06 14:01:01.364575 00226612 UTL default      syncElectInterval        25000
11/06 14:01:01.364582 00226612 UTL default      syncHeartbeatInterval    1000
11/06 14:01:01.364587 00226612 UTL default      syncHeartbeatTimeout     20000
11/06 14:01:01.364593 00226612 UTL default      vndCommitMaxInterval     600000
11/06 14:01:01.364599 00226612 UTL default      mndSdbWriteDelta         200
11/06 14:01:01.364605 00226612 UTL default      mndLogRetention          2000
11/06 14:01:01.364611 00226612 UTL default      grantMode                0
11/06 14:01:01.364617 00226612 UTL default      skipGrant                0
11/06 14:01:01.364623 00226612 UTL default      monitor                  1
11/06 14:01:01.364628 00226612 UTL default      monitorInterval          30
11/06 14:01:01.364634 00226612 UTL default      monitorFqdn              
11/06 14:01:01.364640 00226612 UTL default      monitorPort              6043
11/06 14:01:01.364646 00226612 UTL default      monitorMaxLogs           100
11/06 14:01:01.364652 00226612 UTL default      monitorComp              0
11/06 14:01:01.364658 00226612 UTL default      audit                    0
11/06 14:01:01.364663 00226612 UTL default      auditFqdn                
11/06 14:01:01.364669 00226612 UTL default      auditPort                6043
11/06 14:01:01.364675 00226612 UTL default      crashReporting           1
11/06 14:01:01.364681 00226612 UTL default      telemetryReporting       1
11/06 14:01:01.364687 00226612 UTL default      telemetryInterval        43200
11/06 14:01:01.364692 00226612 UTL default      telemetryServer          telemetry.tdengine.com
11/06 14:01:01.364698 00226612 UTL default      telemetryPort            80
11/06 14:01:01.364704 00226612 UTL default      tmqMaxTopicNum           20
11/06 14:01:01.364710 00226612 UTL default      transPullupInterval      2
11/06 14:01:01.364715 00226612 UTL default      mqRebalanceInterval      2
11/06 14:01:01.364721 00226612 UTL default      ttlUnit                  86400
11/06 14:01:01.364727 00226612 UTL default      ttlPushInterval          10
11/06 14:01:01.364733 00226612 UTL default      ttlBatchDropNum          10000
11/06 14:01:01.364739 00226612 UTL default      ttlChangeOnWrite         0
11/06 14:01:01.364745 00226612 UTL default      ttlFlushThreshold        100
11/06 14:01:01.364750 00226612 UTL default      trimVDbIntervalSec       3600
11/06 14:01:01.364756 00226612 UTL default      uptimeInterval           300
11/06 14:01:01.364762 00226612 UTL default      queryRsmaTolerance       1000
11/06 14:01:01.364768 00226612 UTL default      timeseriesThreshold      50
11/06 14:01:01.364774 00226612 UTL default      walFsyncDataSizeLimit    104857600
11/06 14:01:01.364780 00226612 UTL default      udf                      1
11/06 14:01:01.364785 00226612 UTL default      udfdResFuncs             
11/06 14:01:01.364791 00226612 UTL default      udfdLdLibPath            
11/06 14:01:01.364796 00226612 UTL default      disableStream            0
11/06 14:01:01.364804 00226612 UTL default      streamBufferSize         134217728
11/06 14:01:01.364810 00226612 UTL default      checkpointInterval       300
11/06 14:01:01.364816 00226612 UTL default      streamSinkDataRate       2.00
11/06 14:01:01.364821 00226612 UTL default      cacheLazyLoadThreshold   500
11/06 14:01:01.364827 00226612 UTL default      lossyColumns             
11/06 14:01:01.364833 00226612 UTL default      fPrecision               0.00
11/06 14:01:01.364839 00226612 UTL default      dPrecision               0.00
11/06 14:01:01.364845 00226612 UTL default      maxRange                 500
11/06 14:01:01.364851 00226612 UTL default      curRange                 100
11/06 14:01:01.364856 00226612 UTL default      ifAdtFse                 0
11/06 14:01:01.364862 00226612 UTL default      compressor               ZSTD_COMPRESSOR
11/06 14:01:01.364868 00226612 UTL default      filterScalarMode         0
11/06 14:01:01.364873 00226612 UTL default      maxStreamBackendCache    128
11/06 14:01:01.364879 00226612 UTL default      pqSortMemThreshold       16
11/06 14:01:01.364884 00226612 UTL default      resolveFQDNRetryTime     100
11/06 14:01:01.364890 00226612 UTL default      s3Accesskey              <accesskey>
11/06 14:01:01.364896 00226612 UTL default      s3Endpoint               <endpoint>
11/06 14:01:01.364902 00226612 UTL default      s3BucketName             <bucketname>
11/06 14:01:01.364907 00226612 UTL default      s3BlockSize              4096
11/06 14:01:01.364913 00226612 UTL default      s3BlockCacheSize         16
11/06 14:01:01.364918 00226612 UTL default      minDiskFreeSize          52428800
11/06 14:01:01.364924 00226612 UTL default      enableWhiteList          0
11/06 14:01:01.364930 00226612 UTL default      configDir                /etc/taos/
11/06 14:01:01.364935 00226612 UTL default      scriptDir                /etc/taos/
11/06 14:01:01.364941 00226612 UTL cfg_file     logDir                   /home/tdengine/taos3.2.0.0/server/log
11/06 14:01:01.364947 00226612 UTL default      minimalLogDirGB          1.00
11/06 14:01:01.364953 00226612 UTL default      numOfLogLines            10000000
11/06 14:01:01.364959 00226612 UTL default      asyncLog                 1
11/06 14:01:01.364964 00226612 UTL default      logKeepDays              0
11/06 14:01:01.364970 00226612 UTL default      debugFlag                0
11/06 14:01:01.364976 00226612 UTL default      simDebugFlag             143
11/06 14:01:01.364981 00226612 UTL default      tmrDebugFlag             131
11/06 14:01:01.364987 00226612 UTL default      uDebugFlag               131
11/06 14:01:01.364992 00226612 UTL default      rpcDebugFlag             131
11/06 14:01:01.364998 00226612 UTL default      jniDebugFlag             131
11/06 14:01:01.365004 00226612 UTL default      qDebugFlag               131
11/06 14:01:01.365009 00226612 UTL default      cDebugFlag               131
11/06 14:01:01.365015 00226612 UTL default      dDebugFlag               131
11/06 14:01:01.365021 00226612 UTL default      vDebugFlag               131
11/06 14:01:01.365026 00226612 UTL default      mDebugFlag               131
11/06 14:01:01.365032 00226612 UTL default      wDebugFlag               131
11/06 14:01:01.365038 00226612 UTL default      sDebugFlag               131
11/06 14:01:01.365043 00226612 UTL default      tsdbDebugFlag            131
11/06 14:01:01.365049 00226612 UTL default      tqDebugFlag              131
11/06 14:01:01.365054 00226612 UTL default      fsDebugFlag              131
11/06 14:01:01.365060 00226612 UTL default      udfDebugFlag             131
11/06 14:01:01.365066 00226612 UTL default      smaDebugFlag             131
11/06 14:01:01.365071 00226612 UTL default      idxDebugFlag             131
11/06 14:01:01.365077 00226612 UTL default      tdbDebugFlag             131
11/06 14:01:01.365083 00226612 UTL default      metaDebugFlag            131
11/06 14:01:01.365088 00226612 UTL default      stDebugFlag              131
11/06 14:01:01.365094 00226612 UTL default      timezone                 Asia/Shanghai (CST, +0800)
11/06 14:01:01.365101 00226612 UTL default      locale                   zh_CN.UTF-8
11/06 14:01:01.365107 00226612 UTL default      charset                  UTF-8
11/06 14:01:01.365112 00226612 UTL default      assert                   1
11/06 14:01:01.365118 00226612 UTL default      enableCoreFile           1
11/06 14:01:01.365123 00226612 UTL default      numOfCores               2.00
11/06 14:01:01.365129 00226612 UTL default      ssd42                    0
11/06 14:01:01.365135 00226612 UTL default      avx                      0
11/06 14:01:01.365141 00226612 UTL default      avx2                     0
11/06 14:01:01.365146 00226612 UTL default      fma                      0
11/06 14:01:01.365152 00226612 UTL default      simdEnable               0
11/06 14:01:01.365157 00226612 UTL default      tagFilterCache           0
11/06 14:01:01.365163 00226612 UTL default      openMax                  1024
11/06 14:01:01.365169 00226612 UTL default      streamMax                16
11/06 14:01:01.365174 00226612 UTL default      pageSizeKB               4
11/06 14:01:01.365180 00226612 UTL default      totalMemoryKB            15068116
11/06 14:01:01.365185 00226612 UTL default      os sysname               Linux
11/06 14:01:01.365191 00226612 UTL default      os nodename              td1
11/06 14:01:01.365197 00226612 UTL default      os release               4.19.90-52.15.v2207.ky10.x86_64
11/06 14:01:01.365202 00226612 UTL default      os version               #1 SMP Thu Nov 24 21:50:03 CST 2022
11/06 14:01:01.365208 00226612 UTL default      os machine               x86_64
11/06 14:01:01.365214 00226612 UTL default      version                  3.2.0.0
11/06 14:01:01.365219 00226612 UTL default      compatible_version       3.0.0.0
11/06 14:01:01.365225 00226612 UTL default      gitinfo                  0d8276ba747cc7bff8af0ac1e2f5ba153fad928c
11/06 14:01:01.365231 00226612 UTL default      buildinfo                Built at 2023-10-19 19:36
11/06 14:01:01.365236 00226612 UTL =================================================================
11/06 14:01:01.367122 00226612 DND start to init dnode env
11/06 14:01:01.367217 00226612 DND dnode file:/home/tdengine/taos3.2.0.0/server/data/dnode/dnode.json not exist
11/06 14:01:01.367247 00226612 DND mnode file:/home/tdengine/taos3.2.0.0/server/data/mnode/mnode.json not exist
11/06 14:01:01.367256 00226612 DND file:/home/tdengine/taos3.2.0.0/server/data/qnode/qnode.json not exist
11/06 14:01:01.367263 00226612 DND file:/home/tdengine/taos3.2.0.0/server/data/snode/snode.json not exist
11/06 14:01:01.367344 00226612 DND ERROR failed to create dnode since Not found
11/06 14:01:01.367352 00226612 DND ERROR failed to init dnode since unsupported platform, please visit https://www.taosdata.com for support

安装的版本是目前最新版3.2.0.0

**Comment by gccgdb1234** [comment]
查看日志看看为什么启动失败。日志在 /var/log/taos

**Comment by gccgdb1234** [comment]
什么平台？从日志最后一行看这是不支持的平台

**Comment by liyubo-debug** [comment]
你好，我在配置文件中将日志地址设置在了/home/tdengine/taos3.2.0.0/server/log，很奇怪日志文件中没有什么内容，命令行中直接输入./taosd出现的日志信息在上面，看到是dnode.json not exit，我的配置文件更改情况也在正文中有。
平台是VM VirtualBox虚拟机下的kylinV10

**Comment by liyubo-debug** [comment]
在ubuntu上可以成功安装
