### ISSUE TITLE
Aparemnt JSON parsing error causing SIGSEGV

### ISSUE THREAD

**Issue by mikhailtchernychev** [taosdata/TDengine#23585]
**Bug Description**
JSON parsing causing SIGSEGV and abnormal termination.

**To Reproduce**
1. Compile ver-3.2.0.0, using default settings. Ubuntu 22.04, gcc 11.4.0
2.  Compile file json_protocol_example.c
3. I had a docker image of TDengine running.
2. Run the program, you get exit code -1
3. Using GDB under eclipse I got:

```
Thread 1 "taos_demo" received signal SIGSEGV, Segmentation fault.
smlParseJSONString (info=0x555557618610, start=0x7fffffffdaa0, elements=0x7fffffffdab0) at /home/misha/Downloads/TDengine/source/client/src/clientSmlJson.c:1158
1158        *(elements->tags + elements->tagsLen) = 0;
```

**Expected Behavior**
Should insert lines into database, this does not happen

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - 64GB, 100GB
 - TDengine Version ver-3.2.0.0
-  running TDengine via docker tdengine/tdengine

**Comment by yu285** [comment]
hi ,could you provide the complete steps to reproduce this bug ?

at least provide us "json_protocol_example.c" file .

Thanks
