### ISSUE TITLE
3.2 TDengine cluster problem in use

### ISSUE THREAD

**Issue by ivercher** [taosdata/TDengine#23589]
3.2版本，集群有三个节点，我把其中一个节点/var/lib/taos的文件都删除了，如果重新同步其他节点数据到这个节点

**Comment by yu285** [comment]
重启一下这个节点试试

**Comment by ivercher** [comment]
进不了命令行，有什么办法管理集群？

**Comment by ivercher** [comment]
> 重启一下这个节点试试

不行_

**Comment by yu285** [comment]
可以加微信a15652223354做一下具体排查

**Comment by yu285** [comment]
暂无反馈，暂做关闭处理，如果还有疑问可添加微信：a15652223354
