### ISSUE TITLE
uos 安装问题

### ISSUE THREAD

**Issue by ly0928** [taosdata/TDengine#23594]
uos安装tdengine的deb时出现该错误
dpkg: 处理归档 TDengine-server-3.0.7.0-Linux-x64.deb (--install)时出错：
 执行钩子 if test -x /usr/sbin/deepin-pkg-install-hook;then /usr/sbin/deepin-pkg-install-hook -e hc-verifysign;fi 出错，退出状态为 65280
并且apt方式没有3.0.7.0版本 我应该如何指定版本安装呢

**Comment by yu285** [comment]
3100 后，企业版/开源版支持范畴有调整，参考：

https://docs.taosdata.com/reference/support-platform/
