### ISSUE TITLE
NodeJs连接器问题

### ISSUE THREAD

**Issue by real2019** [taosdata/TDengine#236]
运行nodejs连接器中的test.js，centos 7.0环境，具体报错信息如下：
/usr/local/TDengine/src/connector/nodejs/nodetaos/cinterface.js:98
  return ((BigInt(val) << 32n) + BigInt(first + buffer[++offset] * 2 ** 8 + buffer[++offset] * 2 ** 16 + buffer[++offset] * 2 ** 24));

**Comment by StoneT2000** [comment]
Please update your td-connector to the latest version, 1.2.1, it fixes this bug.
