### ISSUE TITLE
3.*版本的tdengine不支持OpenEuler22.03 LTS SP2

### ISSUE THREAD

**Issue by TensyAndKiya** [taosdata/TDengine#23603]
**Bug Description**
安装3.*版本的tdengine启动后都显示 DND ERROR failed to init dnode since unsupported platform
但是安装2.*版本的tdengine就可以成功启动

系统版本是OpenEuler22.03 LTS SP2
安装方式是tar.gz/rpm

**Comment by winnyrain** [comment]
社区版不支持了，要用商业版，开始收割社区开源版了，请参见https://docs.taosdata.com/reference/support-platform
