### ISSUE TITLE
How to Specify Time Interval for Query Results in table

### ISSUE THREAD

**Issue by mackjie** [taosdata/TDengine#23604]
**How to Specify Time Interval for Query Results in table**

"2023-10-11 18:00:00",2
"2023-10-11 18:05:00",5
"2023-10-11 18:10:00",10
"2023-10-11 18:15:00",15
"2023-10-11 18:20:00",15
"2023-10-11 18:25:00",10
"2023-10-11 18:30:00",15
"2023-10-11 18:35:00",20
"2023-10-11 18:40:00",17
"2023-10-11 18:45:00",10
"2023-10-11 18:50:00",3
In TDengine,  table ces_st   i have Two fields （ts、value），there is the above data. How to specify the time interval of the query result。
for example：
1、to return all data if specified as 5 minutes, 

2、half data if specified as 10 minutes
"2023-10-11 18:00:00",2
"2023-10-11 18:10:00",10
"2023-10-11 18:20:00",15
...
3、 two data if specified as 30 minutes? 
"2023-10-11 18:00:00",2
"2023-10-11 18:30:00",15

**Comment by yu285** [comment]
for 10 mins case:

select count(*)  from ces_st interval(10m)
