### ISSUE TITLE
使用原生链接报版本不兼容

### ISSUE THREAD

**Issue by xwh1108** [taosdata/TDengine#23633]
1.已安装客户端驱动 并且客户端驱动可以正常链接服务器
![微信截图_20231110115955](https://github.com/taosdata/TDengine/assets/35356435/4a266aec-cf3e-4b13-8f35-23429aaaf8d4)
2.jdbc pom 版本
```xml
<dependency>
        <groupId>com.taosdata.jdbc</groupId>
        <artifactId>taos-jdbcdriver</artifactId>
        <version>3.2.7</version>
 </dependency>
```
3.服务端 docker方式安装 镜像为`tdengine/tdengine:latest`

4.报错`JNI ERROR (0x2354): Version not compatible`

**Comment by yu285** [comment]
请排查应用是否使用了旧版本的动态库文件libtaos.so / taos.dll

**Comment by xwh1108** [comment]
> 请排查应用是否使用了旧版本的动态库文件libtaos.so / taos.dll

驱动程序和应用程序均在一台电脑上,不存在驱动程序和应用程序调用的dll不一致

驱动程序版本:TDengine-client-3.2.0.0-Windows-x64.exe
Java版本:
```
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```
![微信图片_20231110141747](https://github.com/taosdata/TDengine/assets/35356435/e044d5e8-3e87-4731-8fd0-a9ac56c34eca)
dll均来自安装包 无人为复制或下载

**Comment by xwh1108** [comment]
破案了:可能存在dll缓存? 因为我一致在不停变换服务端版本?

**Comment by yu285** [comment]
> 破案了:可能存在dll缓存? 因为我一致在不停变换服务端版本?

破案就好
