### ISSUE TITLE
使用taosdump备份数据库时报错：ERROR: Invalid time precision: .

### ISSUE THREAD

**Issue by CrannyCast** [taosdata/TDengine#23637]
操作系统是CentOS7.6，server版本是3.1.1.0，taosdump版本是2.4.5
建库语句是 “create database if not exists history_trend keep 3650 precision 'ms';”
建超表语句是“ create stable history_trend_data (ts timestamp, val double, quality bigint) TAGS(deviceid_ binary(128),state_ binary(128));”
在这个超表下建立了一些普通表，并且向普通表中写入了一些数据，然后使用taosdump工具备份数据库，语句是“taosdump  -L -o /home/lu/td_bk/ -D history_trend”，最后报错

OK: total 166 sub table(s) of stable: history_trend_data dumped
ERROR: Invalid time precision: .
ERROR: dumpNtbOfStbByThreads() LN10688, get precision error

生成的taosdump.XXX文件夹中dbs.sql中的建库语句是“CREATE DATABASE IF NOT EXISTS history_trend    KEEP      PRECISION ''  ;”
请问是怎么回事，同时文件夹中显示的taosdump版本是2.4.2？
完整的文件放在了附录中的压缩包中。

[td_bk.zip](https://github.com/taosdata/TDengine/files/13316849/td_bk.zip)

**Comment by CrannyCast** [comment]
一周了没人看这个问题吗

**Comment by yu285** [comment]
2.4.5 是2.x版本的taostool, 请先使用 3.x  自带的taosdump
