### ISSUE TITLE
3.2版本，一个集群，有三个节点，我把其中节点 /var/lib/taos/下的文件直接删了，怎样操作可以让这个节点数据重新同步

### ISSUE THREAD

**Issue by ivercher** [taosdata/TDengine#23632]
删除文件节点不停报如下警告

11/10 10:30:40.034952 00066502 DND WARN vgId:2, msg:0x7fce68003228 failed to put into vnode queue since Vnode is closed or removed, type:sync-heartbeat qtype:6 contLen:96, gtid:0x0:0x62793b7113401829
11/10 10:30:40.234962 00066502 DND WARN vgId:3, msg:0x7fce68003228 failed to put into vnode queue since Vnode is closed or removed, type:sync-heartbeat qtype:6 contLen:96, gtid:0x0:0x62793b711350182b
11/10 10:30:41.024940 00066501 DND WARN vgId:2, msg:0x7fce6c003008 failed to put into vnode queue since Vnode is closed or removed, type:sync-heartbeat qtype:6 contLen:96, gtid:0x0:0x62793b711380182e
11/10 10:30:41.224945 00066501 DND WARN vgId:3, msg:0x7fce6c003008 failed to put into vnode queue since Vnode is closed or removed, type:sync-heartbeat qtype:6 contLen:96, gtid:0x0:0x62793b7113901830
11/10 10:30:41.590947 00066502 DND WARN vgId:2, msg:0x7fce68003278 failed to put into vnode queue since Vnode is closed or removed, type:sync-append-entries qtype:5 contLen:184, gtid:0x0:0x62793b7113a01837
11/10 10:30:41.590947 00066501 DND WARN vgId:3, msg:0x7fce6c003058 failed to put into vnode queue since Vnode is closed or removed, type:sync-append-entries qtype:5 contLen:184, gtid:0x0:0x62793b7113a01836
11/10 10:30:42.016128 00066502 DND WARN vgId:2, msg:0x7fce68003228 failed to put into vnode queue since Vnode is closed or removed, type:sync-heartbeat qtype:6 contLen:96, gtid:0x0:0x62793b7113c01839

**Comment by yu285** [comment]
重新启动该节点就可以了。
