### ISSUE TITLE
DOUBLE类型精度丢失

### ISSUE THREAD

**Issue by 1797899698** [taosdata/TDengine#23638]
操作系统是CentOS7.6
建库语句是create database energy_carbon_emissions;
create table dev_history(date_time TIMESTAMP, val DOUBLE,pkey NCHAR(20),ver NCHAR(10),sn NCHAR(50),dq INT ) TAGS(client_id NCHAR(50),dev NCHAR(50),item NCHAR(50));
插入数据发现部分数据精度丢失
![image](https://github.com/taosdata/TDengine/assets/40411650/f3950c37-b113-4be7-94f3-c4624938263c)

**Comment by 1797899698** [comment]
原本的数据应该是103.31

**Comment by 1797899698** [comment]
目前版本是3.2.0

**Comment by 1797899698** [comment]
2.4版本就没有这个问题

**Comment by yu285** [comment]
计算机本身就是无法精准保存全部的小数的，与数据库没有关系。
