### ISSUE TITLE
尝试添加集群失败后，重启td发现单节点无法正常登录

### ISSUE THREAD

**Issue by buyaoxiaxue** [taosdata/TDengine#23648]
目前我这边在使用过程中出现问题，之前尝试加入其他设备到集群后，暂时出现无法使用的情况，因生产环境使用需求，又drop掉其他的节点，单机恢复正常，但是其余节点一直处于drop状态，昨晚又尝试加入集群，加入集群失败，重启服务后，单机无法正常登陆了

**Expected Behavior**

![image](https://github.com/taosdata/TDengine/assets/99472146/ad2716d4-cb4f-4fd2-b2bb-2185a896e226)

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.9]

**Additional Context**

**Comment by yu285** [comment]
如果问题仍存在 可添加微信 a15652223354
