### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by tianbo-0319** [taosdata/TDengine#2365]
[hs_err_pid26620.log](https://github.com/taosdata/TDengine/files/4803992/hs_err_pid26620.log)

**Comment by tianbo-0319** [comment]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f2bcc59dd33, pid=28427, tid=0x00007f2b4c3e4700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_161-b12) (build 1.8.0_161-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.161-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libtaos.so.1.6.5.9+0x9ad33]  tscProcessSql+0x1a8
#
# Core dump written. Default location: /home/work/levelhqpush/level-task/core or core.28427
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x00007f2c83656000):  JavaThread "disruptor-thread-8" [_thread_in_native, id=28506, stack(0x00007f2b4c2e4000,0x00007f2b4c3e5000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000001

Registers:
RAX=0x0000000000000000, RBX=0x00007f2bcd8a5de0, RCX=0x00007f2b7c005670, RDX=0x0000000000000000
RSP=0x00007f2b4c3e3020, RBP=0x00007f2b4c3e3090, RSI=0x0000000000000000, RDI=0x00007f2b4803a3b0
R8 =0x00000007b2baa730, R9 =0x0000000000000035, R10=0x00007f2bcc54df87, R11=0x00007f2c72228c58
R12=0x0000000000000000, R13=0x00007f2b4c3e31a8, R14=0x00007f2b4c3e3238, R15=0x00007f2c83656000
RIP=0x00007f2bcc59dd33, EFLAGS=0x0000000000010246, CSGSFS=0x002b000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007f2b4c3e3020)
0x00007f2b4c3e3020:   9000000000000000 00007f2b7c005670
0x00007f2b4c3e3030:   e5585fd151001191 0000000000014000
0x00007f2b4c3e3040:   0000000000000000 00007f2b48006cc4
0x00007f2b4c3e3050:   00007f2b48006cb0 00007f2b7c005760
0x00007f2b4c3e3060:   00007f2b7c005718 00007f2b4803a3b0
0x00007f2b4c3e3070:   742e6c6576656c2e 2e626f6a2e6b7361
0x00007f2b4c3e3080:   0000000030323032 00007f2b4803a3b0
0x00007f2b4c3e3090:   00007f2b4c3e30e0 00007f2bcc542b67
0x00007f2b4c3e30a0:   0000000020373234 00007f2b7c005670
0x00007f2b4c3e30b0:   00007f2b7c005670 00007f2b7c005760
0x00007f2b4c3e30c0:   00007f2b7c005718 00007f2b4803a3b0
0x00007f2b4c3e30d0:   00007f2b48006cb0 0000000000000000
0x00007f2b4c3e30e0:   00007f2b4c3e3100 00007f2bcc542d81
0x00007f2b4c3e30f0:   00000007b22a03a8 00007f2b7c005670
0x00007f2b4c3e3100:   00007f2b4c3e3140 00007f2bcc54e04f
0x00007f2b4c3e3110:   00007f2b7c005670 00007f2b7c005520
0x00007f2b4c3e3120:   00007f2b4c3e3150 00007f2c836561f8
0x00007f2b4c3e3130:   000000079ddbf9a8 00007f2b7c005520
0x00007f2b4c3e3140:   00007f2b4c3e3190 00007f2c72228cf2
0x00007f2b4c3e3150:   000000051b52bdf0 00007f2c882b7c4c
0x00007f2b4c3e3160:   00007f2c09870668 00007f2c83656000
0x00007f2b4c3e3170:   0000000000000000 00007f2c83656000
0x00007f2b4c3e3180:   0000000000000000 00007f2c09870668
0x00007f2b4c3e3190:   00007f2b4c3e3210 00007f2c71007d00
0x00007f2b4c3e31a0:   00007f2c71007d00 00007f2b7c005670
0x00007f2b4c3e31b0:   00000007b2baa7e0 00007f2b7c005520
0x00007f2b4c3e31c0:   00007f2b7c005670 000000051b52bdf0
0x00007f2b4c3e31d0:   00007f2b4c3e31d0 00007f2bcd8a5c0d
0x00007f2b4c3e31e0:   00007f2b4c3e3238 00007f2bcd8a6a70
0x00007f2b4c3e31f0:   00007f2b3dec94c0 00007f2bcd8a5c58
0x00007f2b4c3e3200:   00007f2b4c3e31a8 00007f2b4c3e3240
0x00007f2b4c3e3210:   00000007b2baa890 00007f2c72321d64 

Instructions: (pc=0x00007f2bcc59dd33)
0x00007f2bcc59dd13:   8b 00 48 85 c0 74 12 48 8b 45 c0 48 8b 00 0f b6
0x00007f2bcc59dd23:   40 01 83 e0 0f 84 c0 74 1c 48 8b 45 c0 48 8b 00
0x00007f2bcc59dd33:   0f b6 40 01 c0 e8 04 89 c2 48 8b 45 98 88 50 62
0x00007f2bcc59dd43:   e9 ad 00 00 00 48 8b 45 d8 0f b7 40 02 0f b7 c0 

Register to memory mapping:

RAX=0x0000000000000000 is an unknown value
RBX={method} {0x00007f2bcd8a5de0} 'freeResultSetImp' '(JJ)I' in 'com/taosdata/jdbc/TSDBJNIConnector'
RCX=0x00007f2b7c005670 is an unknown value
RDX=0x0000000000000000 is an unknown value
RSP=0x00007f2b4c3e3020 is pointing into the stack for thread: 0x00007f2c83656000
RBP=0x00007f2b4c3e3090 is pointing into the stack for thread: 0x00007f2c83656000
RSI=0x0000000000000000 is an unknown value
RDI=0x00007f2b4803a3b0 is an unknown value
R8 =0x00000007b2baa730 is pointing into object: 0x00000007b2912178

[error occurred during error reporting (printing register info), id 0xb]

Stack: [0x00007f2b4c2e4000,0x00007f2b4c3e5000],  sp=0x00007f2b4c3e3020,  free space=1020k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libtaos.so.1.6.5.9+0x9ad33]  tscProcessSql+0x1a8
C  [libtaos.so.1.6.5.9+0x3fb67]  taos_free_result_imp+0x2eb
C  [libtaos.so.1.6.5.9+0x3fd81]  taos_free_result+0x1d
C  [libtaos.so.1.6.5.9+0x4b04f]  Java_com_taosdata_jdbc_TSDBJNIConnector_freeResultSetImp+0xc8
J 6551  com.taosdata.jdbc.TSDBJNIConnector.freeResultSetImp(JJ)I (0 bytes) @ 0x00007f2c72228cf2 [0x00007f2c72228c40+0xb2]
j  com.taosdata.jdbc.TSDBJNIConnector.freeResultSet(J)I+45
J 6700 C1 com.taosdata.jdbc.TSDBJNIConnector.executeQuery(Ljava/lang/String;)I (139 bytes) @ 0x00007f2c72321d64 [0x00007f2c72321c80+0xe4]
J 6657 C1 com.taosdata.jdbc.TSDBStatement.executeQuery(Ljava/lang/String;)Ljava/sql/ResultSet; (76 bytes) @ 0x00007f2c722d603c [0x00007f2c722d5f60+0xdc]
J 6655 C1 com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(Ljava/lang/String;)Ljava/sql/ResultSet; (13 bytes) @ 0x00007f2c722d3b5c [0x00007f2c722d3800+0x35c]
J 5727 C2 com.level.task.service.impl.TaosServiceImpl.selectList(Ljava/lang/String;Ljava/lang/String;)Ljava/util/List; (331 bytes) @ 0x00007f2c7188075c [0x00007f2c71880440+0x31c]
J 5740 C2 com.level.task.job.StockFundWorkHandler.process(Ljava/lang/String;Lcom/level/task/model/StockFundThreshold;)V (297 bytes) @ 0x00007f2c71b42ba0 [0x00007f2c71b42b00+0xa0]
J 6540 C1 com.level.task.job.StockFundWorkHandler.onEvent(Lcom/level/task/job/HandlerEvent;)V (47 bytes) @ 0x00007f2c7222c694 [0x00007f2c7222c580+0x114]
J 6539 C1 com.level.task.job.StockFundWorkHandler.onEvent(Ljava/lang/Object;)V (9 bytes) @ 0x00007f2c72227fec [0x00007f2c72227e80+0x16c]
j  com.lmax.disruptor.WorkProcessor.run()V+121
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub
V  [libjvm.so+0x695ae6]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x1056
V  [libjvm.so+0x695ff1]  JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*)+0x321
V  [libjvm.so+0x696497]  JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*)+0x47
V  [libjvm.so+0x731cb0]  thread_entry(JavaThread*, Thread*)+0xa0
V  [libjvm.so+0xa7eaa3]  JavaThread::thread_main_inner()+0x103
V  [libjvm.so+0xa7ebec]  JavaThread::run()+0x11c
V  [libjvm.so+0x92da28]  java_start(Thread*)+0x108
C  [libpthread.so.0+0x82de]  start_thread+0xfe

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 6551  com.taosdata.jdbc.TSDBJNIConnector.freeResultSetImp(JJ)I (0 bytes) @ 0x00007f2c72228c78 [0x00007f2c72228c40+0x38]
j  com.taosdata.jdbc.TSDBJNIConnector.freeResultSet(J)I+45
J 6700 C1 com.taosdata.jdbc.TSDBJNIConnector.executeQuery(Ljava/lang/String;)I (139 bytes) @ 0x00007f2c72321d64 [0x00007f2c72321c80+0xe4]
J 6657 C1 com.taosdata.jdbc.TSDBStatement.executeQuery(Ljava/lang/String;)Ljava/sql/ResultSet; (76 bytes) @ 0x00007f2c722d603c [0x00007f2c722d5f60+0xdc]
J 6655 C1 com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(Ljava/lang/String;)Ljava/sql/ResultSet; (13 bytes) @ 0x00007f2c722d3b5c [0x00007f2c722d3800+0x35c]
J 5727 C2 com.level.task.service.impl.TaosServiceImpl.selectList(Ljava/lang/String;Ljava/lang/String;)Ljava/util/List; (331 bytes) @ 0x00007f2c7188075c [0x00007f2c71880440+0x31c]
J 5740 C2 com.level.task.job.StockFundWorkHandler.process(Ljava/lang/String;Lcom/level/task/model/StockFundThreshold;)V (297 bytes) @ 0x00007f2c71b42ba0 [0x00007f2c71b42b00+0xa0]
J 6540 C1 com.level.task.job.StockFundWorkHandler.onEvent(Lcom/level/task/job/HandlerEvent;)V (47 bytes) @ 0x00007f2c7222c694 [0x00007f2c7222c580+0x114]
J 6539 C1 com.level.task.job.StockFundWorkHandler.onEvent(Ljava/lang/Object;)V (9 bytes) @ 0x00007f2c72227fec [0x00007f2c72227e80+0x16c]
j  com.lmax.disruptor.WorkProcessor.run()V+121
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
  0x00000000006e6000 JavaThread "HikariPool-1 connection closer" daemon [_thread_blocked, id=28567, stack(0x00007f2bce23b000,0x00007f2bce33c000)]
  0x00007f2bc80e7000 JavaThread "pool-1-thread-1" [_thread_blocked, id=28533, stack(0x00007f2b3dfe8000,0x00007f2b3e0e9000)]
  0x00007f2bb8011000 JavaThread "flow_save-2-thread-8" daemon [_thread_blocked, id=28532, stack(0x00007f2b3e0e9000,0x00007f2b3e1ea000)]
  0x00007f2bb800f000 JavaThread "flow_save-2-thread-7" daemon [_thread_blocked, id=28531, stack(0x00007f2b3e1ea000,0x00007f2b3e2eb000)]
  0x00007f2bb800d800 JavaThread "flow_save-2-thread-6" daemon [_thread_blocked, id=28530, stack(0x00007f2b3e2eb000,0x00007f2b3e3ec000)]
  0x00007f2bb800c000 JavaThread "flow_save-2-thread-5" daemon [_thread_blocked, id=28529, stack(0x00007f2b3e3ec000,0x00007f2b3e4ed000)]
  0x00007f2bb800a000 JavaThread "flow_save-2-thread-4" daemon [_thread_blocked, id=28528, stack(0x00007f2b3e4ed000,0x00007f2b3e5ee000)]
  0x00007f2bb8008800 JavaThread "flow_save-2-thread-3" daemon [_thread_blocked, id=28527, stack(0x00007f2b3e5ee000,0x00007f2b3e6ef000)]
  0x00007f2bb8006800 JavaThread "flow_save-2-thread-2" daemon [_thread_blocked, id=28526, stack(0x00007f2b3e6ef000,0x00007f2b3e7f0000)]
  0x00007f2bb8005800 JavaThread "flow_save-2-thread-1" daemon [_thread_blocked, id=28525, stack(0x00007f2b3e7f0000,0x00007f2b3e8f1000)]
  0x00007f2c8000b000 JavaThread "DestroyJavaVM" [_thread_blocked, id=28428, stack(0x00007f2c893fc000,0x00007f2c894fc000)]
  0x00007f2c81629800 JavaThread "stock-fund-data-scheduler" daemon [_thread_blocked, id=28524, stack(0x00007f2b3e8f1000,0x00007f2b3e9f2000)]
  0x00007f2c8215a000 JavaThread "flow-cache-scheduler" daemon [_thread_blocked, id=28523, stack(0x00007f2bce33c000,0x00007f2bce43d000)]
  0x00007f2c82020800 JavaThread "XNIO-1 Accept" [_thread_in_native, id=28522, stack(0x00007f2b3e9f2000,0x00007f2b3eaf3000)]
  0x00007f2c8201e800 JavaThread "XNIO-1 I/O-8" [_thread_in_native, id=28521, stack(0x00007f2b3eaf3000,0x00007f2b3ebf4000)]
  0x00007f2c8201c800 JavaThread "XNIO-1 I/O-7" [_thread_in_native, id=28520, stack(0x00007f2b3ebf4000,0x00007f2b3ecf5000)]
  0x00007f2c8201a800 JavaThread "XNIO-1 I/O-6" [_thread_in_native, id=28519, stack(0x00007f2b3ecf5000,0x00007f2b3edf6000)]
  0x00007f2c81f58800 JavaThread "XNIO-1 I/O-5" [_thread_in_native, id=28518, stack(0x00007f2b3edf6000,0x00007f2b3eef7000)]
  0x00007f2c81f56800 JavaThread "XNIO-1 I/O-4" [_thread_in_native, id=28517, stack(0x00007f2b3eef7000,0x00007f2b3eff8000)]
  0x00007f2c81f55000 JavaThread "XNIO-1 I/O-3" [_thread_in_native, id=28516, stack(0x00007f2b3eff8000,0x00007f2b3f0f9000)]
  0x00007f2c82b63000 JavaThread "XNIO-1 I/O-2" [_thread_in_native, id=28515, stack(0x00007f2b3f0f9000,0x00007f2b3f1fa000)]
  0x00007f2c82b62800 JavaThread "XNIO-1 I/O-1" [_thread_in_native, id=28514, stack(0x00007f2b3f1fa000,0x00007f2b3f2fb000)]
  0x00007f2c81cce000 JavaThread "scheduling-1" [_thread_blocked, id=28513, stack(0x00007f2b3f4fb000,0x00007f2b3f5fc000)]
  0x00007f2c837e9800 JavaThread "nats:3" [_thread_blocked, id=28512, stack(0x00007f2b3f9fc000,0x00007f2b3fafd000)]
  0x00007f2c836ad800 JavaThread "Nats Connection Timer" [_thread_blocked, id=28511, stack(0x00007f2b3fafd000,0x00007f2b3fbfe000)]
  0x00007f2c836a9800 JavaThread "nats:2" [_thread_blocked, id=28510, stack(0x00007f2b3fbfe000,0x00007f2b3fcff000)]
  0x00007f2c836a7800 JavaThread "nats:1" [_thread_in_native, id=28509, stack(0x00007f2b3fcff000,0x00007f2b3fe00000)]
  0x00007f2c836a2000 JavaThread "pool-3-thread-1" [_thread_blocked, id=28508, stack(0x00007f2b4c0e2000,0x00007f2b4c1e3000)]
=>0x00007f2c83656000 JavaThread "disruptor-thread-8" [_thread_in_native, id=28506, stack(0x00007f2b4c2e4000,0x00007f2b4c3e5000)]
  0x00007f2c83654800 JavaThread "disruptor-thread-7" [_thread_in_native, id=28505, stack(0x00007f2b4c3e5000,0x00007f2b4c4e6000)]
  0x00007f2c83652800 JavaThread "disruptor-thread-6" [_thread_in_native, id=28504, stack(0x00007f2b4c4e6000,0x00007f2b4c5e7000)]
  0x00007f2c83651000 JavaThread "disruptor-thread-5" [_thread_in_native, id=28503, stack(0x00007f2b4c5e7000,0x00007f2b4c6e8000)]
  0x00007f2c8364f000 JavaThread "disruptor-thread-4" [_thread_in_native, id=28502, stack(0x00007f2b4c6e8000,0x00007f2b4c7e9000)]
  0x00007f2c8364d800 JavaThread "disruptor-thread-3" [_thread_blocked, id=28501, stack(0x00007f2bcc0ff000,0x00007f2bcc200000)]
  0x00007f2c8364c000 JavaThread "disruptor-thread-2" [_thread_in_native, id=28500, stack(0x00007f2bcc200000,0x00007f2bcc301000)]
  0x00007f2c8364a800 JavaThread "disruptor-thread-1" [_thread_in_native, id=28499, stack(0x00007f2bcc301000,0x00007f2bcc402000)]
  0x00007f2c83009000 JavaThread "HikariPool-1 housekeeper" daemon [_thread_blocked, id=28498, stack(0x00007f2bcc402000,0x00007f2bcc503000)]
  0x00007f2c82f97800 JavaThread "redisson-netty-1-16" [_thread_in_native, id=28490, stack(0x00007f2bcc827000,0x00007f2bcc928000)]
  0x00007f2c82f95000 JavaThread "redisson-netty-1-15" [_thread_in_native, id=28489, stack(0x00007f2bcc928000,0x00007f2bcca29000)]
  0x00007f2c82f93000 JavaThread "redisson-netty-1-14" [_thread_in_native, id=28488, stack(0x00007f2bcca29000,0x00007f2bccb2a000)]
  0x00007f2c82f91000 JavaThread "redisson-netty-1-13" [_thread_in_native, id=28487, stack(0x00007f2bccb2a000,0x00007f2bccc2b000)]
  0x00007f2c82f8f000 JavaThread "redisson-netty-1-12" [_thread_in_native, id=28486, stack(0x00007f2bccc2b000,0x00007f2bccd2c000)]
  0x00007f2c82f8d000 JavaThread "redisson-netty-1-11" [_thread_in_native, id=28485, stack(0x00007f2bccd2c000,0x00007f2bcce2d000)]
  0x00007f2c82f8b000 JavaThread "redisson-netty-1-10" [_thread_in_native, id=28484, stack(0x00007f2bcce2d000,0x00007f2bccf2e000)]
  0x00007f2c82f89000 JavaThread "redisson-netty-1-9" [_thread_in_native, id=28483, stack(0x00007f2bccf2e000,0x00007f2bcd02f000)]
  0x00007f2c82f87800 JavaThread "redisson-netty-1-8" [_thread_in_native, id=28482, stack(0x00007f2bcd02f000,0x00007f2bcd130000)]
  0x00007f2c82f86000 JavaThread "redisson-netty-1-7" [_thread_in_native, id=28481, stack(0x00007f2bcd130000,0x00007f2bcd231000)]
  0x00007f2c82f84000 JavaThread "redisson-netty-1-6" [_thread_in_native, id=28480, stack(0x00007f2bcd231000,0x00007f2bcd332000)]
  0x00007f2c82f82800 JavaThread "redisson-netty-1-5" [_thread_in_native, id=28479, stack(0x00007f2bcd332000,0x00007f2bcd433000)]
  0x00007f2c82f80800 JavaThread "redisson-netty-1-4" [_thread_in_native, id=28478, stack(0x00007f2bcd433000,0x00007f2bcd534000)]
  0x00007f2c82f7f800 JavaThread "redisson-netty-1-3" [_thread_in_native, id=28477, stack(0x00007f2bcd534000,0x00007f2bcd635000)]
  0x00007f2c82f75800 JavaThread "redisson-netty-1-2" [_thread_in_native, id=28476, stack(0x00007f2bcd635000,0x00007f2bcd736000)]
  0x00007f2c819ef000 JavaThread "redisson-netty-1-1" [_thread_in_native, id=28475, stack(0x00007f2bcd936000,0x00007f2bcda37000)]
  0x00007f2c81f29800 JavaThread "mybatis-plus MapperRefresh" [_thread_blocked, id=28466, stack(0x00007f2bcea3f000,0x00007f2bceb40000)]
  0x00007f2c82353000 JavaThread "System Clock" daemon [_thread_blocked, id=28465, stack(0x00007f2bceb40000,0x00007f2bcec41000)]
  0x00007f2c81a33800 JavaThread "master housekeeper" daemon [_thread_blocked, id=28464, stack(0x00007f2bcec41000,0x00007f2bced42000)]
  0x00007f2c8223c000 JavaThread "mysql-cj-abandoned-connection-cleanup" daemon [_thread_blocked, id=28463, stack(0x00007f2c08d80000,0x00007f2c08e81000)]
  0x00007f2c811ff000 JavaThread "Service Thread" daemon [_thread_blocked, id=28458, stack(0x00007f2c08f82000,0x00007f2c09083000)]
  0x00007f2c811ec000 JavaThread "C1 CompilerThread3" daemon [_thread_in_vm, id=28457, stack(0x00007f2c09084000,0x00007f2c09184000)]
  0x00007f2c811e9800 JavaThread "C2 CompilerThread2" daemon [_thread_in_native, id=28456, stack(0x00007f2c09185000,0x00007f2c09285000)]
  0x00007f2c811e7800 JavaThread "C2 CompilerThread1" daemon [_thread_in_native, id=28455, stack(0x00007f2c09286000,0x00007f2c09386000)]
  0x00007f2c811e5800 JavaThread "C2 CompilerThread0" daemon [_thread_in_native, id=28454, stack(0x00007f2c09387000,0x00007f2c09487000)]
  0x00007f2c811e3800 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=28453, stack(0x00007f2c09487000,0x00007f2c09588000)]
  0x00007f2c811e2000 JavaThread "Surrogate Locker Thread (Concurrent GC)" daemon [_thread_blocked, id=28452, stack(0x00007f2c100d3000,0x00007f2c101d4000)]
  0x00007f2c811ab000 JavaThread "Finalizer" daemon [_thread_blocked, id=28451, stack(0x00007f2c101d4000,0x00007f2c102d5000)]
  0x00007f2c811a6800 JavaThread "Reference Handler" daemon [_thread_blocked, id=28450, stack(0x00007f2c102d5000,0x00007f2c103d6000)]

Other Threads:
  0x00007f2c8119f000 VMThread [stack: 0x00007f2c103d7000,0x00007f2c104d7000] [id=28449]
  0x00007f2c81204800 WatcherThread [stack: 0x00007f2c08e82000,0x00007f2c08f82000] [id=28459]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

Heap:
 garbage-first heap   total 11141120K, used 8943616K [0x0000000518000000, 0x0000000518405500, 0x00000007c0000000)
  region size 4096K, 101 young (413696K), 17 survivors (69632K)
 Metaspace       used 55483K, capacity 57432K, committed 57600K, reserved 1099776K
  class space    used 6973K, capacity 7323K, committed 7424K, reserved 1048576K

**Comment by Aries-Lee1991** [comment]
你用的是哪个版本？

**Comment by tianbo-0319** [comment]
1.0.3




在2020年06月21日 16:37，Xiaxin Li 写道：

你用的是哪个版本？

**Comment by tianbo-0319** [comment]
数据库 1.6.5.9  jar包1.0.3

**Comment by Aries-Lee1991** [comment]
> 数据库 1.6.5.9 jar包1.0.3

好的，我们这边看一下您这个问题。

**Comment by plum-lihui** [comment]
1、# Core dump written. Default location: /home/work/levelhqpush/level-task/core or core.26620
您能将这个core文件发送给我们分析一下吗？多谢！

2、我们已经发布了最新的v1.6.6.0版本了，建议您下载这个版本使用。

**Comment by tianbo-0319** [comment]
core文件很大，kan看这个能看出么
![image](https://user-images.githubusercontent.com/40235929/85356622-f9ff9600-b541-11ea-89ad-f106b3af0ca8.png)

**Comment by tianbo-0319** [comment]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /usr/java/jdk/jre/lib/amd64/server/libjvm.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/13/bda266af1f869687977cd6f2a46bf1c3511321.debug
Missing separate debuginfo for /usr/java/jdk/jre/lib/amd64/libverify.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/b3/de2701fa3aef182d8e7b2db8d294a91af1eb7c.debug

warning: Loadable section ".note.gnu.property" outside of ELF segments
Missing separate debuginfo for /usr/java/jdk/jre/lib/amd64/libmanagement.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/ee/7e746ef83f2c2fbe8ea0cb42706b63cd74de3f.debug
Core was generated by `java -Xmx8192M -Xms8192M -XX:MaxMetaspaceSize=128M -XX:MetaspaceSize=128M -XX:+'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fcfed8b48df in raise () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7fcebafed700 (LWP 12982))]
Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-72.el8_1.1.x86_64 sssd-client-2.2.0-19.el8_1.1.x86_64
(gdb) bt
#0  0x00007fcfed8b48df in raise () from /lib64/libc.so.6
#1  0x00007fcfed89ecf5 in abort () from /lib64/libc.so.6
#2  0x00007fcfed89ebc9 in __assert_fail_base.cold.0 () from /lib64/libc.so.6
#3  0x00007fcfed8ace96 in __assert_fail () from /lib64/libc.so.6
#4  0x00007fcf3854af2e in tscProcessMsgFromServer (msg=0x7fcf300066cc "<", ahandle=0x7fcee8006bb0, thandle=0x7fcfead139c0)
    at /home/ubuntu/version_release_workroom/release_workspace/TDinternal/community/src/client/src/tscServer.c:527
#5  0x00007fcf3855b44b in taosProcessSchedMsg (pMsg=0x7fcebafeceb0) at /home/ubuntu/version_release_workroom/release_workspace/TDinternal/community/src/rpc/src/trpc.c:1469
#6  0x00007fcf3858f3fd in taosProcessSchedQueue (param=0x7fcfe93dace0) at /home/ubuntu/version_release_workroom/release_workspace/TDinternal/community/src/util/src/tsched.c:144
#7  0x00007fcfee0622de in start_thread () from /lib64/libpthread.so.0
#8  0x00007fcfed979133 in clone () from /lib64/libc.so.6
(gdb)

**Comment by plum-lihui** [comment]
这样无法分析，请压缩一下发送到我的邮箱吧：huili@taosdata.com
多谢！

**Comment by tianbo-0319** [comment]
core实在是太大了，可以到我服务器上分析，可以加微信13958000294

**Comment by plum-lihui** [comment]
加你微信了。多谢！

**Comment by Aries-Lee1991** [comment]
@tianbo-0319 @plum-lihui 这个问题是否已经解决了呢？

**Comment by plum-lihui** [comment]
We have released the v2.0 version of TDengine, please use the latest version to verify. thank you very much!
