### ISSUE TITLE
create mnode失败

### ISSUE THREAD

**Issue by ly0928** [taosdata/TDengine#23651]
三台3.0.7.0 create mnode on dnode 之后 some vnode/qnode/mnode(s) out of service
firstEq直接挂掉 且启动不来 是为何 该版本不可使用集群吗

**Comment by yu285** [comment]
这个是配置问题，检查下hosts 文件，fqdn等内容即可。

**Comment by ly0928** [comment]
我的配置就做了基本配置firstEq和fqdn 各自的主机host配置了hostname dnode都可以加入且是ready状态 在windonws 执行create mnode直接会taosd启动不起来（3台win） 在linux 添加mnode第一个成功了 但在第二次的时候又失败 taosd也启动不起来(3台linux)&nbsp;&nbsp;


八九
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yu ***@***.***&gt;; 
发送时间: 2023年11月13日(星期一) 下午2:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [taosdata/TDengine] create mnode失败 (Issue #23651)





 
这个是配置问题，检查下hosts 文件，fqdn等内容即可。

**Comment by ly0928** [comment]
高版本对于我们来说有不好用的地方 没办法升级到高版本 只能以3.0.7.0测试
