### ISSUE TITLE
3.1.1.0 和 3.2.0.0 版本测试，集群重启，需要等待半个小时才能使用

### ISSUE THREAD

**Issue by liufanfandev** [taosdata/TDengine#23662]
用 3.1.1.0 和 3.2.0.0 版本 分别搭建两个集群，正常插入数据，然后重启集群。
服务端报错：
![image](https://github.com/taosdata/TDengine/assets/23279206/4b062928-14d2-49d1-b9ac-e3bc77dbbfb1)
客户端请求 adapter 报错：
{"code":2316,"desc":"Sync leader is unreachable"}
{"code":2324,"desc":"Sync leader is restoring"}
然后等待半个小时，就能正常插入数据

**Comment by yu285** [comment]
https://www.taosdata.com/tdengine-engineering/18366.html

正常现象，参考本文。
