### ISSUE TITLE
firstEq挂掉后不可查询表的内容

### ISSUE THREAD

**Issue by ly0928** [taosdata/TDengine#23678]
三台unbuntu TDengine3.2.0.0 三个mnode firstEq 宕机后 其他两个mnode节点不可查询表的内容 该如何解决 且这样的集群怎么实现高可用
mnode 必须是一台或者三台及以上吗 为何不可为两台

**Comment by yu285** [comment]
需要数据库三副本才可以高可用。mnode里不包含数据。
