### ISSUE TITLE
Duplicated data in a stable

### ISSUE THREAD

**Issue by NephilimJaeger** [taosdata/TDengine#23671]
**Bug Description**
I'm having an issue with duplicated data. 

**To Reproduce**

The data comes from Event Hubs, being inserted using a K8s pod and SQL. The table has the column 'tag' as its TAG, and the first timestamp is the sensor reading timestamp. The TDEngine is duplicating the data for a few timestamps and tags; I have records with the same timestamp for a given TAG.

**Expected Behavior**
The expectation is that the data is not duplicated, only updated

**Screenshots**
![image](https://github.com/taosdata/TDengine/assets/79484746/9eed2718-3993-4769-a146-18dab06cd007)

Table schema 
![image](https://github.com/taosdata/TDengine/assets/79484746/b2dd9a06-076c-4264-bdb2-58d3d1d1c7fc)

**Environment (please complete the following information):**
 - TDengine Version 3.1.1.0

**Additional Context**
At first we think that was timestamp precision but after we changed, the problem persists

**Comment by yu285** [comment]
please upgrade it to 3.2.1.0 ,we've already fixed this kind of issue .

**Comment by yu285** [comment]
by the way ,we allow the same-timestamped data existed in the scope of super table .

we don't allow the same-timestamped  data existed in the normal/child table .

**Comment by NephilimJaeger** [comment]
@yu285 in our case, the database is modeled to have one child table per tag, so it was a real issue. We updated to version 3.2.0 and the duplicities are now resolved. Thanks
