### ISSUE TITLE
offline节点如何删除

### ISSUE THREAD

**Issue by xiaopangemail** [taosdata/TDengine#23698]
taos> show transactions \G;
*************************** 1.row ***************************
              id: 8079
     create_time: 2023-11-14 18:40:24.884
           stage: redoAction
            oper: balance-vgroup
              db: 
          stable: 
    failed_times: 0
  last_exec_time: 2023-11-15 09:52:44.590
last_action_info: action:11 code:0x111(Action in progress) msgType:alter-confirm numOfEps:2 inUse:0 ep:0-people-tdengine02:6030 ep:1-uat-test:6030 

taos> show dnodes;
     id      |            endpoint            | vnodes | support_vnodes |    status    |       create_time       |       reboot_time       |              note              |
=============================================================================================================================================================================
           1 | people-tdengine01... |      7 |              8 | ready        | 2023-10-17 19:44:50.828 | 2023-11-15 08:43:49.274 |                                |
           2 |people-tdengine02... |      7 |              8 | ready        | 2023-10-19 20:15:22.487 | 2023-11-15 08:47:40.262 |                                |
           3 |people-tdengine03... |      6 |              8 | ready        | 2023-10-19 20:24:36.416 | 2023-11-15 09:47:57.456 |                                |
           4 |uat-test:6030         |      6 |                 0 | offline      | 2023-11-14 10:45:40.310 | 1970-01-01 08:00:00.000 | status not received            |

taos> drop dnode 4;

DB error: Dnode is offline (0.000991s)

节点没办法删除

**Comment by xiaopangemail** [comment]
群集执行balance-vgroup，失败后就处于当前状态

**Comment by xiaopangemail** [comment]
新增一个不存在的节点，然后删除，提示DB error: Dnode is offline，这样如何清理

**Comment by yu285** [comment]
drop dnode x force

**Comment by wubaiqing** [comment]
现在的命令叫 unsafe 了；
`drop dnode x unsafe;`
