### ISSUE TITLE
taos3.2.0.0和3.1.0.0在Centos8下不能运行，3.0.7.1可以

### ISSUE THREAD

**Issue by fatzhang** [taosdata/TDengine#23706]
之前系统安装版本为3.0.7.1，系统可以正常运行，systemctl status正常，今天升级到3.2.0.0，systemctl status失败，255错误
然后运行/usr/bin/taod，输出错误DND ERROR failed to init dnode since unsupported platform
然后安装3.1.0.0版本，依然报此错误，重新安装3.0.7.1恢复正常。

部分输入如下：
11/15 16:07:30.493954 00016873 UTL default      totalMemoryKB            32574712
11/15 16:07:30.493957 00016873 UTL default      os sysname               Linux
11/15 16:07:30.493962 00016873 UTL default      os nodename              dbserver.aerotop.net
11/15 16:07:30.493965 00016873 UTL default      os release               5.10.134-13.an8.x86_64
11/15 16:07:30.493970 00016873 UTL default      os version               #1 SMP Mon Jan 9 10:39:46 CST 2023
11/15 16:07:30.493974 00016873 UTL default      os machine               x86_64
11/15 16:07:30.493982 00016873 UTL default      version                  3.2.0.0
11/15 16:07:30.493986 00016873 UTL default      compatible_version       3.0.0.0
11/15 16:07:30.493994 00016873 UTL default      gitinfo                  0d8276ba747cc7bff8af0ac1e2f5ba153fad928c
11/15 16:07:30.493997 00016873 UTL default      buildinfo                Built at 2023-10-19 19:36
11/15 16:07:30.494002 00016873 UTL =================================================================
11/15 16:07:30.497876 00016873 DND start to init dnode env
11/15 16:07:30.498055 00016873 DND succceed to read dnode file /var/lib/taos//dnode/dnode.json
11/15 16:07:30.498113 00016873 DND succceed to read mnode file /var/lib/taos//mnode/mnode.json
11/15 16:07:30.498129 00016873 DND file:/var/lib/taos//qnode/qnode.json not exist
11/15 16:07:30.498145 00016873 DND file:/var/lib/taos//snode/snode.json not exist
11/15 16:07:30.498254 00016873 DND ERROR failed to create dnode since Not found
11/15 16:07:30.498267 00016873 DND ERROR failed to init dnode since unsupported platform, please visit https://www.taosdata.com for support

**Comment by yu285** [comment]
3100 后，企业版/开源版支持范畴有调整，参考：

https://docs.taosdata.com/reference/support-platform/
