### ISSUE TITLE
使用官网提供的高效写入insert语句长度超限报错

### ISSUE THREAD

**Issue by Apophisdeity** [taosdata/TDengine#23720]
使用官网提供的高效写入api写td,报错desc: SQL statement too long Query,请问insert into的长度不能超过多少?
[官网给的示例](https://docs.taosdata.com/develop/insert-data/high-volume/#sample-code)
`sb.length() + q.length() > maxSQLLength`

**Comment by Apophisdeity** [comment]
驱动版本:3.2.2,insert sql中存在中文

**Comment by feiyangbeyond** [comment]
官网写了最长1MB

[https://docs.taosdata.com/develop/insert-data/sql-writing/](https://docs.taosdata.com/develop/insert-data/sql-writing/)
> 要提高写入效率，需要批量写入。一般来说一批写入的记录条数越多，插入效率就越高。但一条记录不能超过 48KB，一条 SQL 语句总长度不能超过 1MB。

[https://docs.taosdata.com/develop/insert-data/high-volume/](https://docs.taosdata.com/develop/insert-data/high-volume/)
> 单次写入的数据量。一般来讲，每批次写入的数据量越大越高效（但超过一定阈值其优势会消失）。使用 SQL 写入 TDengine 时，尽量在一条 SQL 中拼接更多数据。目前，TDengine 支持的一条 SQL 的最大长度为 1,048,576（1MB）个字符
