### ISSUE TITLE
taosd cpu usage issue .

### ISSUE THREAD

**Issue by SpringLin97** [taosdata/TDengine#23721]
**如何配置taos使用CPU的限制？？**
![image](https://github.com/taosdata/TDengine/assets/63085858/0efad05c-6a14-41ce-8c69-5d84a3b48d0f)

**Comment by yu285** [comment]
top -Hp `pidof taosd` ,检查一下具体在做什么工作。

**Comment by SpringLin97** [comment]
> top -Hp `pidof taosd` ,检查一下具体在做什么工作。

现场环境，就是查询，入库操作，有没有优化建议，比如限制TAOS的CPU使用核数等等。？？？

**Comment by yu285** [comment]
如果是正常的大量业务使用。导致cpu高为正常现象。

TDengine 本身没有对 cpu 限制的方法。
