### ISSUE TITLE
show vnodes

### ISSUE THREAD

**Issue by ly0928** [taosdata/TDengine#23741]
https://docs.taosdata.com/taos-sql/show/#show-vnodes
show vnode;会出错
SHOW VNODES [ON DNODE dnode_id];
show vnodes on dnode 1;也会出错
应为show vondes 1;是合并没同步过来吗？

**Comment by yu285** [comment]
版本号是？以及报错截图麻烦提供

**Comment by ly0928** [comment]
版本号3.0.7.0
![Uploading bandicam 2023-11-23 11-35-31-921.jpg…]()

**Comment by ly0928** [comment]
![Uploading bandicam 2023-11-23 11-35-31-921.jpg…]()

**Comment by ly0928** [comment]
执行
show vnodes on dnode 1;
DB error: syntax error near "on dnode 1;"(0.000082s)

**Comment by ly0928** [comment]
![bandicam 2023-11-23 11-35-31-921](https://github.com/taosdata/TDengine/assets/44955589/4c4a993d-0280-4150-9d8e-ca17171df83a)

**Comment by yu285** [comment]
应该是语法近期做过调整，升级到 3.2.1.0 最新版本吧
![image](https://github.com/taosdata/TDengine/assets/74105241/3c07ed67-16cd-484e-86bc-242571e5678a)
