### ISSUE TITLE
taosdump export db

### ISSUE THREAD

**Issue by slonbalon** [taosdata/TDengine#23745]
ERROR: Invalid AVRO codec inputted. Exit program!.

**To Reproduce**
 taosdump -d log -o /var/db/
See error 
ERROR: Invalid AVRO codec inputted. Exit program!.
Expected : dump db on /var/db/taos_XXXXX

**Environment (please complete the following information):**
 - OS: [Ubuntu 22]
 - 8G  X64, 100GB
 - TDengine Version [current 3.2.1]
taosTools 2.5.2
Before update to last tdengine Taosdump is work is expect.

**Comment by yu285** [comment]
TDengine 3.2.1 use 2.5.4 taostool,could you use 2.5.4 and try again?

**Comment by slonbalon** [comment]
;)
After restart  host, and try again. Everything is fine.
Thank you for your time. P.S. 
2.5.4.works as expected.
Best regards.

⁣Get BlueMail for Android ​

**Comment by yu285** [comment]
you are welcome ~

**Comment by njuptlzz** [comment]
I use 2.5.4 taostool, but it also show this error
