### ISSUE TITLE
消费者consumer占用的资源无法释放, 请问怎么清理消费者consumer

### ISSUE THREAD

**Issue by logicong** [taosdata/TDengine#23757]
消费者已经卡了3天
重启数据库 kill connection 都没用
导致对应的 topic 和 stream 都无法删除
并且这几个消费者一直在不停的起事务
请问怎么清理消费者
消费者查询结果
![微信图片_20231120171728](https://github.com/taosdata/TDengine/assets/35619149/5f17830f-3466-4113-ac90-009f30a5d0e3)
事务查询结果
![微信图片_20231120171733](https://github.com/taosdata/TDengine/assets/35619149/81d2afbe-4f24-4208-8da3-aa5a53aa7fc5)
日志
[taosdlog.1700466984.gz](https://github.com/taosdata/TDengine/files/13411862/taosdlog.1700466984.gz)

**Comment by yu285** [comment]
问题原因：在节点重启过程，因为rpc消息因为内存不足而入队失败，进而导致vnode恢复失败。

增大rpcQueueMemoryAllowed 重启服务即可。

**Comment by logicong** [comment]
问题已解决, 非常感谢.
