### ISSUE TITLE
涛思数据库，内部查询报错，同样语句，有些条件正常查询，条件不一样报错，把涛思数据库查挂，版本：2.6.0.8

### ISSUE THREAD

**Issue by SpringLin97** [taosdata/TDengine#23783]
![image](https://github.com/taosdata/TDengine/assets/63085858/bf2efa3b-6f3e-43cc-b422-4340702ad26a)

**Comment by SpringLin97** [comment]
版本版本：2.6.0.8

**Comment by yu285** [comment]
https://www.taosdata.com/tdengine-engineering/17753.html

我们已经不再提供 2.x 版本的支持服务，可以先升级到 2.6.0.34 ，然后迁移到最新的3.0 版本（当前为：3.2.1.0）
