### ISSUE TITLE
to_timestamp/to_char 函数无法使用

### ISSUE THREAD

**Issue by flyrun9527** [taosdata/TDengine#23793]
to_timestamp/to_char 函数无法使用  提示desc: Func not exists

**Comment by flyrun9527** [comment]
使用3.2.0.0版本

**Comment by flyrun9527** [comment]
什么时候实装该函数  官网文档那些函数可以说明对应支持版本吗  这样很不友好

**Comment by gccgdb1234** [comment]
请使用 3.2.1.0

**Comment by tcxkb** [comment]
> 请使用 3.2.1.0

3.2.1.0也不对呀！
![image](https://github.com/taosdata/TDengine/assets/44721348/6ca34229-0e56-4de0-a0b4-4bdaed780567)
![image](https://github.com/taosdata/TDengine/assets/44721348/c1e1f8de-a178-49e0-88f9-cf47dfcbd207)
