### ISSUE TITLE
TS

### ISSUE THREAD

**Issue by LXX1029** [taosdata/TDengine#23813]
**Bug Description**
11/24 06:41:48.317881 00131032 RPC ERROR TSC msg heartbeat failed to send, conn 000002B6A0A0CCF0 failed to connect to WIN-RUJ8LHVNLED:6030, reason: connection refused
11/24 06:41:48.317881 00131032 RPC ERROR TSC msg heartbeat failed to send, conn 000002B6A0B4C1F0 failed to connect to WIN-RUJ8LHVNLED:6030, reason: connection refused
11/24 06:41:48.317881 00249328 RPC ERROR TSC msg heartbeat failed to send, conn 000002B6A0A0AFF0 failed to connect to WIN-RUJ8LHVNLED:6030, reason: connection refused
11/24 06:41:48.317881 00131032 RPC ERROR TSC msg heartbeat failed to send, conn 000002B6A0A0C3E0 failed to connect to WIN-RUJ8LHVNLED:6030, reason: connection refused
11/24 06:41:48.317881 00249328 RPC ERROR TSC msg heartbeat failed to send, conn 000002B6A0A08640 failed to connect to WIN-RUJ8LHVNLED:6030, reason: connection refused
11/24 06:41:48.317881 00249328 RPC ERROR TSC msg heartbeat failed to send, conn 000002B6A0B508A0 failed to connect to WIN-RUJ8LHVNLED:6030, reason: connection refused
11/24 06:41:48.317881 00131032 RPC ERROR TSC msg heartbeat failed to send, conn 000002B6A0A0A170 failed to connect to WIN-RUJ8LHVNLED:6030, reason: connection refused
11/24 06:41:48.317881 00516756 RPC ERROR TSC msg heartbeat failed to send, conn 000002B6A0B4D5E0 failed to connect to WIN-RUJ8LHVNLED:6030, reason: connection refused
11/24 06:41:48.317881 00398748 RPC ERROR TSC msg heartbeat failed to send, conn 000002B6A0AC95A0 failed to connect to WIN-RUJ8LHVNLED:6030, reason: connection refused
11/24 06:41:48.317881 00249328 RPC ERROR TSC msg heartbeat failed to send, conn 000002B6A0A09DD0 failed to connect to WIN-RUJ8LHVNLED:6030, reason: connection refused
11/24 06:41:48.317881 00516756 RPC ERROR TSC msg heartbeat failed to send, conn 000002B6A0B4BC80 failed to connect to WIN-RUJ8LHVNLED:6030, reason: connection refused
11/24 06:41:48.317881 00398748 RPC ERROR TSC msg heartbeat failed to send, conn 000002B6A0AC7500 failed to connect to WIN-RUJ8LHVNLED:6030, reason: connection refused
11/24 06:41:48.317881 00249328 RPC ERROR TSC msg heartbeat failed to send, conn 000002B6A0B4B370 failed to connect to WIN-RUJ8LHVNLED:6030, reason: connection refused
11/24 06:41:48.317881 00516756 RPC ERROR TSC msg heartbeat failed to send, conn 000002B6A0A077C0 failed to connect to WIN-RUJ8LHVNLED:6030, reason: connection refused
11/24 06:41:48.317881 00398748 RPC ERROR TSC msg heartbeat failed to send, conn 000002B6A0AC6F90 failed to connect to WIN-RUJ8LHVNLED:6030, reason: connection refused
11/24 06:41:48.317881 00249328 RPC ERROR TSC msg heartbeat failed to send, conn 000002B6A0AC9CE0 failed to connect to WIN-RUJ8LHVNLED:6030, reason: connection refused
11/24 06:41:48.317881 00516756 RPC ERROR TSC msg heartbeat failed to send, conn 000002B6A0A09FA0 failed to connect to WIN-RUJ8LHVNLED:6030, reason: connection refused
11/24 06:41:48.317881 00398748 RPC ERROR TSC msg heartbeat failed to send, conn 000002B6A0B49F80 failed to connect to WIN-RUJ8LHVNLED:6030, reason: connection refused
11/24 06:41:48.317881 00516756 RPC ERROR TSC msg heartbeat failed to send, conn 000002B6A0A094C0 failed to connect to WIN-RUJ8LHVNLED:6030, reason: connection refused
11/24 06:41:48.317881 00398748 RPC ERROR TSC msg heartbeat failed to send, conn 000002B6A0A0C5B0 failed to connect to WIN-RUJ8LHVNLED:6030, reason: connection refused

**Environment (please complete the following information):**
 - OS:windows server 2019 Datacenter
 - 256G, Inter Xeon(R) Silver 4310, 8T
 - TDengine Version 3.0.2.5

**Additional Context**
It runs for about 15 hours and writes about 200*65536 pieces of data every 15 minutes

**Comment by yu285** [comment]
please upgrade it to 3.2.1.0 then check if error occur .
