### ISSUE TITLE
space issue

### ISSUE THREAD

**Issue by zifeiYv** [taosdata/TDengine#23817]
我的场景是存储天气预报数据，单次预报数据包括未来15天的逐15分钟数据，每天预报一次，因此存在数据的滚动更新。

我的做法是：每次都将预报数据直接写入子表，因为数据库会根据时间戳来[覆盖掉旧的数据，从而只保留最新的数据](https://docs.taosdata.com/develop/insert-data/sql-writing/)。

我的问题是：按照上述方式存储数据后，空间占用非常大，严重超出了原始文件的大小。此外，我还做了进一步的验证，简述如下：

- 假设有两个数据文件，file1和file2
- 初始化数据库、超级表和子表后，先写入file1，再写入file2，这是监测到的空间变化是：写入file1后空间占用为167M，再写入file2后空间占用增加至500M。
- 将数据库删除后，重复上一步的初始化操作，先写入file2，在写入file1，监测到的空间变化与上一步相同。

根据上述试验，我怀疑时间戳重复的数据也被重复存储了，只是在子表中查不到而已。

我的诉求是：由于file2相较于file1只增量更新了一小部分数据（按照15天-15分钟的例子，其实只更新了96行数据），其余的数据都是在原始时间戳上修改的，但为什么所占空间的增量这么大？该如何解决？

**Comment by rmokerone** [comment]
同样遇到这样的问题，用户数据已经删除了，taos还是占用了800多G。
<img width="303" alt="image" src="https://github.com/taosdata/TDengine/assets/3683271/c912d8ac-7a52-4307-9254-0d3f3c32b401">
<img width="378" alt="image" src="https://github.com/taosdata/TDengine/assets/3683271/b488d914-a7e5-4e68-8970-facb32fc52f5">
<img width="499" alt="image" src="https://github.com/taosdata/TDengine/assets/3683271/c31bc03f-c943-4615-b10d-e4f0157b6279">

主机硬盘只有1TB，严重影响使用。

**Comment by zifeiYv** [comment]
@rmokerone 我验证过，只删除表（无论是子表还是超级表），空间是不会释放的；但删除所属数据库是可以的。我觉得应该有对应的解决方案，可是我没找到。

**Comment by rmokerone** [comment]
2.0的版本没有这个问题，应该是3.0版本新引入的问题

**Comment by zifeiYv** [comment]
这...

**Comment by yu285** [comment]
空间的清理只能通过keep参数生效，重复时间戳确实会被存储，在查询的时候过滤。

如果数据覆盖过多，会影响查询性能。

如果想随时释放空间，降低性能影响，只能企业版的在线数据重组可以解决。

开源版尽量避免数据的频繁更新，乱序。

**Comment by zifeiYv** [comment]
了解了

**Comment by rmokerone** [comment]
> 空间的清理只能通过keep参数生效，重复时间戳确实会被存储，在查询的时候过滤。
> 
> 如果数据覆盖过多，会影响查询性能。
> 
> 如果想随时释放空间，降低性能影响，只能企业版的在线数据重组可以解决。
> 
> 开源版尽量避免数据的频繁更新，乱序。

我们数据库只用来存储最近两天的数据，之前的数据都会删除掉，即使这样数据库占用的空间也会越来越大，请问也是keep参数的问题吗？

**Comment by CraxGrix** [comment]
> > 空间的清理只能通过keep参数生效，重复时间戳确实会被存储，在查询的时候过滤。
> > 如果数据覆盖过多，会影响查询性能。
> > 如果想随时释放空间，降低性能影响，只能企业版的在线数据重组可以解决。
> > 开源版尽量避免数据的频繁更新，乱序。
> 
> 我们数据库只用来存储最近两天的数据，之前的数据都会删除掉，即使这样数据库占用的空间也会越来越大，请问也是keep参数的issue吗？ @yu285

请问这个问题你最后解决了吗？

**Comment by CraxGrix** [comment]
> @rmokerone 我验证过，只删除表（无论是子表还是超级表），空间是不会释放的；但删除所属数据库是可以的。我觉得应该有对应的解决方案，可是我没找到。

试了一下，删除数据库好像也是不能释放空间的。。。

**Comment by yu285** [comment]
> > @rmokerone 我验证过，只删除表（无论是子表还是超级表），空间是不会释放的；但删除所属数据库是可以的。我觉得应该有对应的解决方案，可是我没找到。
> 
> 试了一下，删除数据库好像也是不能释放空间的。。。

删库后需要清理vnode_bak 目录，就可以了。 另外2.x 我们已经不维护了，请迁移至最新的3.3.1.0版本。

**Comment by boomion** [comment]
> 空间的清理只能通过keep参数生效，重复时间戳确实会被存储，在查询的时候过滤。
> 
> 如果数据覆盖过多，会影响查询性能。
> 
> 如果想随时释放空间，降低性能影响，只能企业版的在线数据重组可以解决。
> 
> 开源版尽量避免数据的频繁更新，乱序。

请问在线数据重组在最新的开源版也不支持么？遇到数据重复覆盖磁盘占用大的问题

**Comment by xiaohu89** [comment]
2.x同样遇到了数据重复覆盖数据文件增长快的问题，没啥解决办法

**Comment by CraxGrix** [comment]
> 2.x同样遇到了数据重复覆盖数据文件增长快的问题，没啥解决办法

暂时没发现好的解决方法，删除vnode_bak也是不行的，因为数据重复覆盖之后并没有被删掉而是跟正常的数据混在一起了
