### ISSUE TITLE
V2.2.2.0  RPC WARN DND-C 0×7fc397ec0cc0(nil),too many redirects,quit

### ISSUE THREAD

**Issue by lh12826** [taosdata/TDengine#23821]
1.版本：V2.2.2.0
2.部署方式：linux服务器 3节点集群
3.问题：最近俩月每周不定时的宕机，重启即可恢复。
4.请求：怎么提高稳定性，根本性解决这个偶尔宕机问题。
5.以下为错误时间日志：
1.日志分析=================================
node1：（宕机之前日志 宕机之后没有任何日志，节点数据异常）
11/24 21:41:28 UTL ERROR pNode:(nil) data:0×7f16183476a0 is not ther!!!
11/24 21:41:28 UTL ERROR pNode:(nil) data:0×7f16183476a0 is not ther!!!
11/24 21:41:28 UTL ERROR pNode:(nil) data:0×7f16183476a0 is not ther!!! （宕机前最后一条日志）
11/24 22:56:41 new log file （恢复后第一条日志）

node2：（宕机之前日志正常 宕机之后异常日志，1重定向过多退出  2异常用户无法建立连接）
11/24 21:41:26 DND user:root,send anth msg to mnodes （宕机前最后一条日志）
11/24 21:41:29 RPC WARN DND-C 0×7fc397ec0cc0(nil),too many redirects,quit（宕机后第一条日志）
11/24 21:41:29 DND ERROR user:root, auth msg received from mnodes,error:Unable to establish connections
11/24 21:41:29 RPC WARN DND-C 0×7fc0b9fbb908 0×3,too many redirects,quit

node3：（宕机之前日志正常 宕机之后异常日志，1重定向过多退出 2异常用户无法建立连接）
11/24 21:41:23 DND user:root,send anth msg to mnodes （宕机前最后一条日志）
11/24 21:41:27 RPC WARN DND-C 0×7fc397ec0cc0(nil),too many redirects,quit（宕机后第一条日志）
11/24 21:41:27 DND ERROR user:root, auth msg received from mnodes,error:Unable to establish connections
11/24 21:41:30 TSC ERROR 0×8c98 Async insertion completed,total inserted:0 rows,numOfFailed:1,numOfTotal:1
![node1日志](https://github.com/taosdata/TDengine/assets/50856394/f0bde892-b59f-4747-ac28-34bc85f31805)
![node2 node3日志](https://github.com/taosdata/TDengine/assets/50856394/632b7efb-fcdd-4c3e-8b25-6e3520149f3e)

**Comment by yu285** [comment]
2.x 我们已经不维护了，请迁移到3.x版本 ：https://www.taosdata.com/tdengine-engineering/17753.html
