### ISSUE TITLE
使用INTERVAL(1w)函数以一周为时间周期时，开始统计的时间和结束统计的时间不符合条件

### ISSUE THREAD

**Issue by WsProgrammer** [taosdata/TDengine#23896]
![image](https://github.com/taosdata/TDengine/assets/34298947/37b2682f-9697-4526-a446-8cda66332b85)

这个窗口函数的两个时间位列的范围无法
准确限制，貌似只要有一个满足这个时间范围条件就能查出来，显然这并不符合实际要求

**Comment by yu285** [comment]
https://www.taosdata.com/tdengine-engineering/3278.html

可以通过控制偏移量规避
