### ISSUE TITLE
V3.2.6.0无法在kylin上启动和安装

### ISSUE THREAD

**Issue by heoo2016** [taosdata/TDengine#23914]
12/02 14:41:20.736765 02872782 UTL =================================================================
12/02 14:41:20.736772 02872782 UTL default      firstEp                  iZ2zedzrlre1gj3gc765gbZ:6030
12/02 14:41:20.736778 02872782 UTL default      secondEp                 iZ2zedzrlre1gj3gc765gbZ:6030
12/02 14:41:20.736781 02872782 UTL default      fqdn                     iZ2zedzrlre1gj3gc765gbZ
12/02 14:41:20.736784 02872782 UTL default      serverPort               6030
12/02 14:41:20.736788 02872782 UTL default      tempDir                  /tmp/
12/02 14:41:20.736791 02872782 UTL default      minimalTmpDirGB          1.00
12/02 14:41:20.736797 02872782 UTL default      shellActivityTimer       3
12/02 14:41:20.736801 02872782 UTL default      compressMsgSize          -1
12/02 14:41:20.736805 02872782 UTL default      queryPolicy              1
12/02 14:41:20.736809 02872782 UTL default      enableQueryHb            1
12/02 14:41:20.736814 02872782 UTL default      enableScience            0
12/02 14:41:20.736817 02872782 UTL default      querySmaOptimize         0
12/02 14:41:20.736820 02872782 UTL default      queryPlannerTrace        0
12/02 14:41:20.736824 02872782 UTL default      queryNodeChunkSize       32768
12/02 14:41:20.736828 02872782 UTL default      queryUseNodeAllocator    1
12/02 14:41:20.736831 02872782 UTL default      keepColumnName           0
12/02 14:41:20.736834 02872782 UTL default      smlChildTableName        
12/02 14:41:20.736837 02872782 UTL default      smlAutoChildTableNameDe  
12/02 14:41:20.736840 02872782 UTL default      smlTagName               _tag_null
12/02 14:41:20.736844 02872782 UTL default      smlTsDefaultName         _ts
12/02 14:41:20.736847 02872782 UTL default      smlDot2Underline         1
12/02 14:41:20.736850 02872782 UTL default      maxShellConns            50000
12/02 14:41:20.736853 02872782 UTL default      maxInsertBatchRows       1000000
12/02 14:41:20.736856 02872782 UTL default      maxRetryWaitTime         10000
12/02 14:41:20.736859 02872782 UTL default      useAdapter               0
12/02 14:41:20.736862 02872782 UTL default      crashReporting           1
12/02 14:41:20.736866 02872782 UTL default      queryMaxConcurrentTable  200
12/02 14:41:20.736869 02872782 UTL default      metaCacheMaxSize         -1
12/02 14:41:20.736872 02872782 UTL default      slowLogThreshold         3
12/02 14:41:20.736875 02872782 UTL default      slowLogScope             
12/02 14:41:20.736879 02872782 UTL default      numOfRpcThreads          2
12/02 14:41:20.736882 02872782 UTL default      numOfRpcSessions         10000
12/02 14:41:20.736885 02872782 UTL default      timeToGetAvailableConn   500000
12/02 14:41:20.736889 02872782 UTL default      keepAliveIdle            60
12/02 14:41:20.736892 02872782 UTL default      numOfTaskQueueThreads    4
12/02 14:41:20.736896 02872782 UTL default      dataDir                  /var/lib/taos/
12/02 14:41:20.736900 02872782 UTL default      minimalDataDirGB         2.00
12/02 14:41:20.736905 02872782 UTL default      supportVnodes            4
12/02 14:41:20.736909 02872782 UTL default      statusInterval           1
12/02 14:41:20.736912 02872782 UTL default      minSlidingTime           1
12/02 14:41:20.736915 02872782 UTL default      minIntervalTime          1
12/02 14:41:20.736918 02872782 UTL default      countAlwaysReturnValue   1
12/02 14:41:20.736921 02872782 UTL default      queryBufferSize          -1
12/02 14:41:20.736925 02872782 UTL default      queryRspPolicy           0
12/02 14:41:20.736928 02872782 UTL default      numOfRpcThreads          2
12/02 14:41:20.736932 02872782 UTL default      numOfRpcSessions         10000
12/02 14:41:20.736939 02872782 UTL default      timeToGetAvailableConn   10000
12/02 14:41:20.736942 02872782 UTL default      numOfCommitThreads       2
12/02 14:41:20.736946 02872782 UTL default      numOfMnodeReadThreads    1
12/02 14:41:20.736949 02872782 UTL default      numOfVnodeQueryThreads   4
12/02 14:41:20.736952 02872782 UTL default      ratioOfVnodeStreamThrea  4.00
12/02 14:41:20.736955 02872782 UTL default      numOfVnodeFetchThreads   4
12/02 14:41:20.736959 02872782 UTL default      numOfVnodeRsmaThreads    4
12/02 14:41:20.736962 02872782 UTL default      numOfQnodeQueryThreads   4
12/02 14:41:20.736965 02872782 UTL default      numOfSnodeSharedThreads  2
12/02 14:41:20.736968 02872782 UTL default      numOfSnodeUniqueThreads  2
12/02 14:41:20.736971 02872782 UTL default      rpcQueueMemoryAllowed    797747609
12/02 14:41:20.736975 02872782 UTL default      syncElectInterval        25000
12/02 14:41:20.736978 02872782 UTL default      syncHeartbeatInterval    1000
12/02 14:41:20.736981 02872782 UTL default      syncHeartbeatTimeout     20000
12/02 14:41:20.736985 02872782 UTL default      mndSdbWriteDelta         200
12/02 14:41:20.736988 02872782 UTL default      mndLogRetention          2000
12/02 14:41:20.736991 02872782 UTL default      grantMode                0
12/02 14:41:20.736995 02872782 UTL default      skipGrant                0
12/02 14:41:20.736998 02872782 UTL cfg_file     monitor                  1
12/02 14:41:20.737001 02872782 UTL default      monitorInterval          30
12/02 14:41:20.737005 02872782 UTL cfg_file     monitorFqdn              iZ2zedzrlre1gj3gc765gbZ
12/02 14:41:20.737009 02872782 UTL default      monitorPort              6043
12/02 14:41:20.737012 02872782 UTL default      monitorMaxLogs           100
12/02 14:41:20.737016 02872782 UTL default      monitorComp              0
12/02 14:41:20.737019 02872782 UTL cfg_file     audit                    1
12/02 14:41:20.737022 02872782 UTL default      auditCreateTable         1
12/02 14:41:20.737025 02872782 UTL default      crashReporting           1
12/02 14:41:20.737029 02872782 UTL default      telemetryReporting       1
12/02 14:41:20.737033 02872782 UTL default      telemetryInterval        43200
12/02 14:41:20.737036 02872782 UTL default      telemetryServer          telemetry.tdengine.com
12/02 14:41:20.737040 02872782 UTL default      telemetryPort            80
12/02 14:41:20.737044 02872782 UTL default      rsyncPort                873
12/02 14:41:20.737049 02872782 UTL default      snodeAddress             
12/02 14:41:20.737052 02872782 UTL default      checkpointBackupDir      /var/lib/taos/backup/checkpoint/
12/02 14:41:20.737056 02872782 UTL default      tmqMaxTopicNum           20
12/02 14:41:20.737059 02872782 UTL default      transPullupInterval      2
12/02 14:41:20.737063 02872782 UTL default      mqRebalanceInterval      2
12/02 14:41:20.737066 02872782 UTL default      ttlUnit                  86400
12/02 14:41:20.737069 02872782 UTL default      ttlPushInterval          10
12/02 14:41:20.737073 02872782 UTL default      ttlBatchDropNum          10000
12/02 14:41:20.737076 02872782 UTL default      ttlChangeOnWrite         0
12/02 14:41:20.737079 02872782 UTL default      ttlFlushThreshold        100
12/02 14:41:20.737083 02872782 UTL default      trimVDbIntervalSec       3600
12/02 14:41:20.737086 02872782 UTL default      uptimeInterval           300
12/02 14:41:20.737089 02872782 UTL default      queryRsmaTolerance       1000
12/02 14:41:20.737092 02872782 UTL default      timeseriesThreshold      50
12/02 14:41:20.737096 02872782 UTL default      walFsyncDataSizeLimit    104857600
12/02 14:41:20.737099 02872782 UTL default      udf                      1
12/02 14:41:20.737102 02872782 UTL default      udfdResFuncs             
12/02 14:41:20.737106 02872782 UTL default      udfdLdLibPath            
12/02 14:41:20.737109 02872782 UTL default      disableStream            0
12/02 14:41:20.737112 02872782 UTL default      streamBufferSize         134217728
12/02 14:41:20.737115 02872782 UTL default      checkpointInterval       60
12/02 14:41:20.737122 02872782 UTL default      streamSinkDataRate       2.00
12/02 14:41:20.737125 02872782 UTL default      cacheLazyLoadThreshold   500
12/02 14:41:20.737129 02872782 UTL default      lossyColumns             
12/02 14:41:20.737132 02872782 UTL default      fPrecision               0.00
12/02 14:41:20.737136 02872782 UTL default      dPrecision               0.00
12/02 14:41:20.737140 02872782 UTL default      maxRange                 500
12/02 14:41:20.737143 02872782 UTL default      curRange                 100
12/02 14:41:20.737147 02872782 UTL default      ifAdtFse                 0
12/02 14:41:20.737150 02872782 UTL default      compressor               ZSTD_COMPRESSOR
12/02 14:41:20.737163 02872782 UTL default      filterScalarMode         0
12/02 14:41:20.737167 02872782 UTL default      maxStreamBackendCache    128
12/02 14:41:20.737170 02872782 UTL default      pqSortMemThreshold       16
12/02 14:41:20.737174 02872782 UTL default      resolveFQDNRetryTime     100
12/02 14:41:20.737177 02872782 UTL default      s3Accesskey              <accesskey>
12/02 14:41:20.737180 02872782 UTL default      s3Endpoint               <endpoint>
12/02 14:41:20.737183 02872782 UTL default      s3BucketName             <bucketname>
12/02 14:41:20.737187 02872782 UTL default      s3BlockSize              -1
12/02 14:41:20.737190 02872782 UTL default      s3BlockCacheSize         16
12/02 14:41:20.737194 02872782 UTL default      s3PageCacheSize          4096
12/02 14:41:20.737197 02872782 UTL default      s3UploadDelaySec         3600
12/02 14:41:20.737200 02872782 UTL default      minDiskFreeSize          52428800
12/02 14:41:20.737204 02872782 UTL default      enableWhiteList          0
12/02 14:41:20.737208 02872782 UTL default      configDir                /etc/taos/
12/02 14:41:20.737213 02872782 UTL default      scriptDir                /etc/taos/
12/02 14:41:20.737217 02872782 UTL default      logDir                   /var/log/taos/
12/02 14:41:20.737220 02872782 UTL default      minimalLogDirGB          1.00
12/02 14:41:20.737224 02872782 UTL default      numOfLogLines            10000000
12/02 14:41:20.737227 02872782 UTL default      asyncLog                 1
12/02 14:41:20.737231 02872782 UTL default      logKeepDays              0
12/02 14:41:20.737235 02872782 UTL default      debugFlag                0
12/02 14:41:20.737238 02872782 UTL default      simDebugFlag             143
12/02 14:41:20.737241 02872782 UTL default      tmrDebugFlag             131
12/02 14:41:20.737244 02872782 UTL default      uDebugFlag               131
12/02 14:41:20.737248 02872782 UTL default      rpcDebugFlag             131
12/02 14:41:20.737251 02872782 UTL default      jniDebugFlag             131
12/02 14:41:20.737254 02872782 UTL default      qDebugFlag               131
12/02 14:41:20.737258 02872782 UTL default      cDebugFlag               131
12/02 14:41:20.737261 02872782 UTL default      dDebugFlag               131
12/02 14:41:20.737264 02872782 UTL default      vDebugFlag               131
12/02 14:41:20.737267 02872782 UTL default      mDebugFlag               131
12/02 14:41:20.737271 02872782 UTL default      wDebugFlag               131
12/02 14:41:20.737274 02872782 UTL default      sDebugFlag               131
12/02 14:41:20.737277 02872782 UTL default      tsdbDebugFlag            131
12/02 14:41:20.737280 02872782 UTL default      tqDebugFlag              131
12/02 14:41:20.737284 02872782 UTL default      fsDebugFlag              131
12/02 14:41:20.737287 02872782 UTL default      udfDebugFlag             131
12/02 14:41:20.737290 02872782 UTL default      smaDebugFlag             131
12/02 14:41:20.737293 02872782 UTL default      idxDebugFlag             131
12/02 14:41:20.737297 02872782 UTL default      tdbDebugFlag             131
12/02 14:41:20.737300 02872782 UTL default      metaDebugFlag            131
12/02 14:41:20.737303 02872782 UTL default      stDebugFlag              131
12/02 14:41:20.737306 02872782 UTL default      timezone                 Asia/Shanghai (CST, +0800)
12/02 14:41:20.737313 02872782 UTL default      locale                   zh_CN.UTF-8
12/02 14:41:20.737316 02872782 UTL default      charset                  UTF-8
12/02 14:41:20.737320 02872782 UTL default      assert                   1
12/02 14:41:20.737323 02872782 UTL default      enableCoreFile           1
12/02 14:41:20.737326 02872782 UTL default      numOfCores               2.00
12/02 14:41:20.737330 02872782 UTL default      ssd42                    0
12/02 14:41:20.737333 02872782 UTL default      avx                      0
12/02 14:41:20.737337 02872782 UTL default      avx2                     0
12/02 14:41:20.737340 02872782 UTL default      fma                      0
12/02 14:41:20.737343 02872782 UTL default      avx512                   0
12/02 14:41:20.737346 02872782 UTL default      simdEnable               0
12/02 14:41:20.737350 02872782 UTL default      tagFilterCache           0
12/02 14:41:20.737353 02872782 UTL default      openMax                  65535
12/02 14:41:20.737357 02872782 UTL default      streamMax                16
12/02 14:41:20.737360 02872782 UTL default      pageSizeKB               4
12/02 14:41:20.737363 02872782 UTL default      totalMemoryKB            7790504
12/02 14:41:20.737367 02872782 UTL default      os sysname               Linux
12/02 14:41:20.737370 02872782 UTL default      os nodename              iZ2zedzrlre1gj3gc765gbZ
12/02 14:41:20.737374 02872782 UTL default      os release               5.10.134-15.al8.x86_64
12/02 14:41:20.737378 02872782 UTL default      os version               #1 SMP Thu Jul 20 00:44:04 CST 2023
12/02 14:41:20.737381 02872782 UTL default      os machine               x86_64
12/02 14:41:20.737385 02872782 UTL default      version                  3.2.1.0
12/02 14:41:20.737389 02872782 UTL default      compatible_version       3.0.0.0
12/02 14:41:20.737392 02872782 UTL default      gitinfo                  234463fcca65f3f1d08a1f245570e4e5d5d272e2
12/02 14:41:20.737395 02872782 UTL default      buildinfo                Built Linux-x64 at 2023-11-20 17:29:01 +0800
12/02 14:41:20.737399 02872782 UTL =================================================================
12/02 14:41:20.740622 02872782 DND start to init dnode env
12/02 14:41:20.740728 02872782 DND dnode file:/var/lib/taos//dnode/dnode.json not exist
12/02 14:41:20.740768 02872782 DND mnode file:/var/lib/taos//mnode/mnode.json not exist
12/02 14:41:20.740775 02872782 DND deploy mnode required. dnodeId:0<=0, clusterId:0<=0, localEp:iZ2zedzrlre1gj3gc765gbZ:6030==firstEp
12/02 14:41:20.740784 02872782 DND file:/var/lib/taos//qnode/qnode.json not exist
12/02 14:41:20.740791 02872782 DND file:/var/lib/taos//snode/snode.json not exist
12/02 14:41:20.740894 02872782 DND ERROR failed to create dnode since Not found
12/02 14:41:20.740900 02872782 DND ERROR failed to init dnode since unsupported platform, please visit https://www.taosdata.com for support

**Comment by yu285** [comment]
3100 版本后，企业版/开源版支持范畴有调整，参考：

https://docs.taosdata.com/reference/support-platform/
