### ISSUE TITLE
docker运行时宿主机与容器时区不一致

### ISSUE THREAD

**Issue by lidayed** [taosdata/TDengine#23925]
宿主机上时区是正确的。
![image](https://github.com/taosdata/TDengine/assets/60281421/dc7f6f70-7f1a-4d94-b991-cb5bd8a0fd9c)

容器上里的时区少8小时
![image](https://github.com/taosdata/TDengine/assets/60281421/c6c1fc10-7d92-4bcd-afec-f0cc2d5b0f5f)

导致用TO_CHAR函数转换的时候会少8小时。
![image](https://github.com/taosdata/TDengine/assets/60281421/21efa14c-3590-43ca-a755-1e0d1f4e4c31)

**Comment by yu285** [comment]
调整容器时间即可。
