### ISSUE TITLE
failed to connect to server, reason: Unable to establish connection

### ISSUE THREAD

**Issue by qiang436** [taosdata/TDengine#23933]
**General Questions**
New installation on Ubuntu 22.04 (Windows Subsystem for Linux(WSL) on Win10)
Unable to logon taosd, can you give some advice how to fix it. Thanks.

root@ubuntu:~# taos
Welcome to the TDengine Command Line Interface, Client Version:3.2.1.0
Copyright (c) 2023 by TDengine, all rights reserved.

failed to connect to server, reason: Unable to establish connection
root@ubuntu:~# service --status-all
 [ - ]  apparmor
 [ ? ]  apport
 [ - ]  console-setup.sh
 [ - ]  cron
 [ - ]  dbus
 [ ? ]  hwclock.sh
 [ + ]  irqbalance
 [ - ]  keyboard-setup.sh
 [ - ]  kmod
 [ ? ]  plymouth
 [ ? ]  plymouth-log
 [ - ]  procps
 [ - ]  rsync
 [ - ]  screen-cleanup
 [ + ]  ssh
 [ + ]  taosd
 [ - ]  udev
 [ - ]  ufw
 [ - ]  unattended-upgrades
 [ - ]  uuidd

root@ubuntu:/var/log/taos# tail -n 50 taosdlog.0*
12/05 09:25:49.694043 00000539 RPC ERROR DND-C conn 0x7f895c001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794d300291
12/05 09:25:49.715681 00000539 RPC ERROR DND-C conn 0x7f895c001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794d300291
12/05 09:25:49.753451 00000538 RPC ERROR DND-C conn 0x7f8970001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794bf00290
12/05 09:25:49.756391 00000539 RPC ERROR DND-C conn 0x7f895c001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794d300291
12/05 09:25:49.837113 00000539 RPC ERROR DND-C conn 0x7f895c001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794d300291
12/05 09:25:49.998846 00000539 RPC ERROR DND-C conn 0x7f895c001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794d300291
12/05 09:25:50.318443 00000539 RPC ERROR DND-C conn 0x7f895c001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794d300291
12/05 09:25:50.754101 00000538 RPC ERROR DND-C conn 0x7f8970001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794bf00290
12/05 09:25:50.959120 00000539 RPC ERROR DND-C conn 0x7f895c001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794d300291
12/05 09:25:51.756028 00000538 RPC ERROR DND-C conn 0x7f8970001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794bf00290
12/05 09:25:51.960790 00000539 RPC ERROR DND-C conn 0x7f895c001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794d300291
12/05 09:25:52.697677 00000579 MND dnode:1, in offline state
12/05 09:25:52.757492 00000538 RPC ERROR DND-C conn 0x7f8970001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794bf00290
12/05 09:25:52.960618 00000539 RPC ERROR DND-C conn 0x7f895c001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794d300291
12/05 09:25:53.758110 00000538 RPC ERROR DND-C conn 0x7f8970001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794bf00290
12/05 09:25:53.961690 00000539 RPC ERROR DND-C conn 0x7f895c001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794d300291
12/05 09:25:54.694807 00000572 DND ERROR failed to send status req since Operation timeout, epSet:{ubuntu:6030}, inUse:0
12/05 09:25:54.759557 00000538 RPC ERROR DND-C conn 0x7f8970001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794bf00290
12/05 09:25:54.895564 00000540 RPC ERROR DND-C conn 0x7f8950001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794e800292
12/05 09:25:54.895660 00000540 RPC ERROR DND-C conn 0x7f8950001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794e800292
12/05 09:25:54.905924 00000540 RPC ERROR DND-C conn 0x7f8950001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794e800292
12/05 09:25:54.926426 00000540 RPC ERROR DND-C conn 0x7f8950001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794e800292
12/05 09:25:54.961377 00000539 RPC ERROR DND-C conn 0x7f895c001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794d300291
12/05 09:25:54.966811 00000540 RPC ERROR DND-C conn 0x7f8950001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794e800292
12/05 09:25:55.046248 00000540 RPC ERROR DND-C conn 0x7f8950001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794e800292
12/05 09:25:55.206768 00000540 RPC ERROR DND-C conn 0x7f8950001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794e800292
12/05 09:25:55.526500 00000540 RPC ERROR DND-C conn 0x7f8950001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794e800292
12/05 09:25:55.962298 00000539 RPC ERROR DND-C conn 0x7f895c001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794d300291
12/05 09:25:56.167194 00000540 RPC ERROR DND-C conn 0x7f8950001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794e800292
12/05 09:25:56.962930 00000539 RPC ERROR DND-C conn 0x7f895c001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794d300291
12/05 09:25:57.168785 00000540 RPC ERROR DND-C conn 0x7f8950001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794e800292
12/05 09:25:57.720229 00000579 MND dnode:1, in offline state
12/05 09:25:57.963579 00000539 RPC ERROR DND-C conn 0x7f895c001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794d300291
12/05 09:25:58.168690 00000540 RPC ERROR DND-C conn 0x7f8950001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794e800292
12/05 09:25:58.964301 00000539 RPC ERROR DND-C conn 0x7f895c001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794d300291
12/05 09:25:59.168379 00000540 RPC ERROR DND-C conn 0x7f8950001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794e800292
12/05 09:25:59.900693 00000572 DND ERROR failed to send status req since Operation timeout, epSet:{ubuntu:6030}, inUse:0
12/05 09:25:59.965047 00000539 RPC ERROR DND-C conn 0x7f895c001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794d300291
12/05 09:26:00.101613 00000541 RPC ERROR DND-C conn 0x7f8954001a40 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794fc00293
12/05 09:26:00.101731 00000541 RPC ERROR DND-C conn 0x7f8954001a40 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794fc00293
12/05 09:26:00.111214 00000541 RPC ERROR DND-C conn 0x7f8954001a40 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794fc00293
12/05 09:26:00.131650 00000541 RPC ERROR DND-C conn 0x7f8954001a40 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794fc00293
12/05 09:26:00.169049 00000540 RPC ERROR DND-C conn 0x7f8950001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794e800292
12/05 09:26:00.172145 00000541 RPC ERROR DND-C conn 0x7f8954001a40 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794fc00293
12/05 09:26:00.252906 00000541 RPC ERROR DND-C conn 0x7f8954001a40 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794fc00293
12/05 09:26:00.412551 00000541 RPC ERROR DND-C conn 0x7f8954001a40 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794fc00293
12/05 09:26:00.733158 00000541 RPC ERROR DND-C conn 0x7f8954001a40 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794fc00293
12/05 09:26:01.170637 00000540 RPC ERROR DND-C conn 0x7f8950001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794e800292
12/05 09:26:01.374021 00000541 RPC ERROR DND-C conn 0x7f8954001a40 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794fc00293
12/05 09:26:02.171141 00000540 RPC ERROR DND-C conn 0x7f8950001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794e800292
root@ubuntu:/var/log/taos#

**Comment by yu285** [comment]
https://www.taosdata.com/engineering/11076.html 看下问题1 排查一下

还有问题可以加微信：a15652223354 做具体排查

**Comment by aptxhb** [comment]
我也遇到这个问题，可以把排查思路贴一下吗？

**Comment by qiang436** [comment]
文档上的步骤都排查过了，未能解决。

应该是OS的环境原因，重点我觉得需要研发解释下 “Protocol not available” 是怎么造成的。

root@ubuntu:/var/log/taos# tail -n 50 taosdlog.0*
12/05 09:25:49.694043 00000539 RPC ERROR DND-C conn 0x7f895c001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794d300291
12/05 09:25:49.715681 00000539 RPC ERROR DND-C conn 0x7f895c001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794d300291
12/05 09:25:49.753451 00000538 RPC ERROR DND-C conn 0x7f8970001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794bf00290
12/05 09:25:49.756391 00000539 RPC ERROR DND-C conn 0x7f895c001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794d300291
12/05 09:25:49.837113 00000539 RPC ERROR DND-C conn 0x7f895c001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794d300291
12/05 09:25:49.998846 00000539 RPC ERROR DND-C conn 0x7f895c001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794d300291
12/05 09:25:50.318443 00000539 RPC ERROR DND-C conn 0x7f895c001a70 failed to create socket, reason:Protocol not available, gtid:0x0:0x476f03794d300291
