### ISSUE TITLE
mybatis query ins_streams with wrong result

### ISSUE THREAD

**Issue by wang2421850881** [taosdata/TDengine#23941]
SpringBoot + Mybatis + Taos 连接，在使用mybatis条件查询ins_streams，无论什么条件，一直是第一条数据。
表数据
![image](https://github.com/taosdata/TDengine/assets/152954244/e63aad85-50a3-4218-8f34-1c65371ac5d8)

linux查询正常。
![image](https://github.com/taosdata/TDengine/assets/152954244/a5c16f12-855f-4289-b1b4-fcda4ecacc47)

TDengineGUI查询正常。
![image](https://github.com/taosdata/TDengine/assets/152954244/76b6a1e7-978e-485f-8255-68291016c097)

mybatis查询异常
![image](https://github.com/taosdata/TDengine/assets/152954244/d8302d91-06a0-40f1-960c-d169c37e1fe8)
![image](https://github.com/taosdata/TDengine/assets/152954244/29316a1f-159f-4336-a9e0-6b360dc7be2c)

**Comment by yu285** [comment]
可以把客户端的taos.cfg  的debugFlag 设置为 135，然后检查日志中记录mybatis 传入的sql 和服务端正常查询的SQL 是否一致。

如果有具体操作问题可以加我们微信 a1565223354
