### ISSUE TITLE
TDengine Version 3.2.1.0 cannot run partition by

### ISSUE THREAD

**Issue by lihy8080** [taosdata/TDengine#23959]
- TDengine Version 3.2.1.0

run : SELECT SUM(val),usage FROM super_emeter WHERE keys = 'costEnergyDif' partition by usage;  
error: DB error: Database not specified (0.000098s)
create table sql: 
CREATE STABLE super_emeter(ts TIMESTAMP, val FLOAT, keys BINARY(30)) TAGS(path BINARY(255),area BINARY(50),park BINARY(50),building BINARY(50),areatype BINARY(50),usage BINARY(50),level BINARY(50));
同样sql在其他版本不存在问题。如下图：

![image](https://github.com/taosdata/TDengine/assets/63838972/75dc8f03-911c-444e-a375-91d9a9bece6b)

**Comment by yu285** [comment]
'use DatabaseName' first

**Comment by yu285** [comment]
暂做关闭处理，如果还有疑问可添加微信：a15652223354
