### ISSUE TITLE
TDengine Connector doesn't support C# framework

### ISSUE THREAD

**Issue by wzq321183** [taosdata/TDengine#23951]
.net framework4.6.1的程序 nuget安装TDengine Connector，使用连接代码如下：
 string DSN = "ws://root:taosdata@127.0.0.1:6041";
 wsConn = LibTaosWS.WSConnectWithDSN(DSN);

报错，提示"无法加载 DLL“taosws”: 找不到指定的模块。

**Comment by wzq321183** [comment]
安装的Connector版本是3.0.2

**Comment by yu285** [comment]
c#连接器处于重构状态，可以等我们正式发布
