### ISSUE TITLE
Out of Memory ， When using ORDER BY.

### ISSUE THREAD

**Issue by Dream95** [taosdata/TDengine#23961]
**Bug Description**
When using ORDER BY, an Out of Memory (OOM) error occurred. 

**To Reproduce**
 CREATE STABLE `wireMeter` (`_ts` TIMESTAMP, `sensorValue` DOUBLE, `sensorValueUnit` NCHAR(10)) TAGS (`deviceNo` NCHAR(30), `serial` NCHAR(10), `bridgeId` BIGINT)；
insert 600 million data;
SELECT *  FROM `wireMeter` where `bridgeId` = 41 ORDER BY _ts DESC ;
**Expected Behavior**

**Screenshots**
![image](https://github.com/taosdata/TDengine/assets/17948602/fe0abf53-a38e-4003-8f42-46697a476b20)

<img width="595" alt="截图_17018493813685" src="https://github.com/taosdata/TDengine/assets/17948602/cdeda96d-c157-4d78-beff-304905aa301c">

**Environment (please complete the following information):**
 - OS: centos 7
 - Memory, CPU, current Disk Space  16G,4C
 - TDengine Version [e.g. 1.6.1.7]   3.2.0  ,docker group

**Additional Context**

**Comment by yu285** [comment]
we don't control memory usage during query , please try to use normal SQL .
