### ISSUE TITLE
3.2.1.0 start up failed

### ISSUE THREAD

**Issue by Yahoofly** [taosdata/TDengine#23984]
Active: failed (Result: exit-code) since Fri 2023-12-08 10:56:34 CST; 10s ago
    Process: 498252 ExecStartPre=/usr/local/taos/bin/startPre.sh (code=exited, status=0/SUCCESS)
    Process: 498258 ExecStart=/usr/bin/taosd (code=exited, status=255/EXCEPTION)
   Main PID: 498258 (code=exited, status=255/EXCEPTION)

Dec 08 10:56:34 LSS-pc systemd[1]: taosd.service: Scheduled restart job, restart counter is at 3.
Dec 08 10:56:34 LSS-pc systemd[1]: Stopped server service.
Dec 08 10:56:34 LSS-pc systemd[1]: taosd.service: Start request repeated too quickly.
Dec 08 10:56:34 LSS-pc systemd[1]: taosd.service: Failed with result 'exit-code'.
Dec 08 10:56:34 LSS-pc systemd[1]: Failed to start server service.

**Comment by yu285** [comment]
sudo taosd

**Comment by Yahoofly** [comment]
这个是什么意思

**Comment by Yahoofly** [comment]
我去查了一下日志，好像是平台的问题12/08 10:56:34.154396 00498258 DND startup path:/ args:/usr/bin/taosd
12/08 10:56:34.154852 00498258 UTL apoll url not load
12/08 10:56:34.154904 00498258 UTL load from cfg file /etc/taos//taos.cfg success
12/08 10:56:34.154910 00498258 UTL env file:.env not load
12/08 10:56:34.154912 00498258 UTL load from env variables cfg success
12/08 10:56:34.155027 00498258 UTL                      global config
12/08 10:56:34.155030 00498258 UTL =================================================================
12/08 10:56:34.155031 00498258 UTL default      firstEp                  LSS-pc:6030
12/08 10:56:34.155033 00498258 UTL default      secondEp                 LSS-pc:6030
12/08 10:56:34.155034 00498258 UTL cfg_file     fqdn                     LSS-pc
12/08 10:56:34.155035 00498258 UTL default      serverPort               6030
12/08 10:56:34.155036 00498258 UTL default      tempDir                  /tmp/
12/08 10:56:34.155037 00498258 UTL default      minimalTmpDirGB          1.00
12/08 10:56:34.155041 00498258 UTL default      shellActivityTimer       3
12/08 10:56:34.155042 00498258 UTL default      compressMsgSize          -1
12/08 10:56:34.155043 00498258 UTL default      queryPolicy              1
12/08 10:56:34.155044 00498258 UTL default      enableQueryHb            1
12/08 10:56:34.155045 00498258 UTL default      enableScience            0
12/08 10:56:34.155047 00498258 UTL default      querySmaOptimize         0
12/08 10:56:34.155048 00498258 UTL default      queryPlannerTrace        0
12/08 10:56:34.155049 00498258 UTL default      queryNodeChunkSize       32768
12/08 10:56:34.155050 00498258 UTL default      queryUseNodeAllocator    1
12/08 10:56:34.155051 00498258 UTL cfg_file     keepColumnName           1
12/08 10:56:34.155052 00498258 UTL default      smlChildTableName        
12/08 10:56:34.155053 00498258 UTL default      smlAutoChildTableNameDe  
12/08 10:56:34.155054 00498258 UTL default      smlTagName               _tag_null
12/08 10:56:34.155055 00498258 UTL default      smlTsDefaultName         _ts
12/08 10:56:34.155057 00498258 UTL default      smlDot2Underline         1
12/08 10:56:34.155058 00498258 UTL default      maxShellConns            50000
12/08 10:56:34.155059 00498258 UTL default      maxInsertBatchRows       1000000
12/08 10:56:34.155060 00498258 UTL default      maxRetryWaitTime         10000
12/08 10:56:34.155061 00498258 UTL default      useAdapter               0
12/08 10:56:34.155062 00498258 UTL default      crashReporting           1
12/08 10:56:34.155063 00498258 UTL default      queryMaxConcurrentTable  200
12/08 10:56:34.155064 00498258 UTL default      metaCacheMaxSize         -1
12/08 10:56:34.155065 00498258 UTL default      slowLogThreshold         3
12/08 10:56:34.155066 00498258 UTL default      slowLogScope             
12/08 10:56:34.155067 00498258 UTL default      numOfRpcThreads          8
12/08 10:56:34.155068 00498258 UTL default      numOfRpcSessions         10000
12/08 10:56:34.155069 00498258 UTL default      timeToGetAvailableConn   500000
12/08 10:56:34.155071 00498258 UTL default      keepAliveIdle            60
12/08 10:56:34.155072 00498258 UTL default      numOfTaskQueueThreads    8
12/08 10:56:34.155073 00498258 UTL default      dataDir                  /var/lib/taos/
12/08 10:56:34.155074 00498258 UTL default      minimalDataDirGB         2.00
12/08 10:56:34.155075 00498258 UTL default      supportVnodes            32
12/08 10:56:34.155076 00498258 UTL default      statusInterval           1
12/08 10:56:34.155077 00498258 UTL default      minSlidingTime           1
12/08 10:56:34.155078 00498258 UTL default      minIntervalTime          1
12/08 10:56:34.155079 00498258 UTL default      countAlwaysReturnValue   1
12/08 10:56:34.155080 00498258 UTL default      queryBufferSize          -1
12/08 10:56:34.155081 00498258 UTL default      queryRspPolicy           0
12/08 10:56:34.155082 00498258 UTL default      numOfRpcThreads          8
12/08 10:56:34.155083 00498258 UTL default      numOfRpcSessions         10000
12/08 10:56:34.155085 00498258 UTL default      timeToGetAvailableConn   10000
12/08 10:56:34.155100 00498258 UTL default      numOfCommitThreads       4
12/08 10:56:34.155101 00498258 UTL default      numOfMnodeReadThreads    2
12/08 10:56:34.155102 00498258 UTL default      numOfVnodeQueryThreads   32
12/08 10:56:34.155104 00498258 UTL default      ratioOfVnodeStreamThrea  4.00
12/08 10:56:34.155105 00498258 UTL default      numOfVnodeFetchThreads   4
12/08 10:56:34.155106 00498258 UTL default      numOfVnodeRsmaThreads    16
12/08 10:56:34.155107 00498258 UTL default      numOfQnodeQueryThreads   32
12/08 10:56:34.155108 00498258 UTL default      numOfSnodeSharedThreads  4
12/08 10:56:34.155109 00498258 UTL default      numOfSnodeUniqueThreads  4
12/08 10:56:34.155110 00498258 UTL default      rpcQueueMemoryAllowed    1621082112
12/08 10:56:34.155111 00498258 UTL default      syncElectInterval        25000
12/08 10:56:34.155112 00498258 UTL default      syncHeartbeatInterval    1000
12/08 10:56:34.155113 00498258 UTL default      syncHeartbeatTimeout     20000
12/08 10:56:34.155114 00498258 UTL default      mndSdbWriteDelta         200
12/08 10:56:34.155115 00498258 UTL default      mndLogRetention          2000
12/08 10:56:34.155117 00498258 UTL default      grantMode                0
12/08 10:56:34.155118 00498258 UTL default      skipGrant                0
12/08 10:56:34.155119 00498258 UTL default      monitor                  1
12/08 10:56:34.155120 00498258 UTL default      monitorInterval          30
12/08 10:56:34.155121 00498258 UTL default      monitorFqdn              
12/08 10:56:34.155122 00498258 UTL default      monitorPort              6043
12/08 10:56:34.155123 00498258 UTL default      monitorMaxLogs           100
12/08 10:56:34.155124 00498258 UTL default      monitorComp              0
12/08 10:56:34.155125 00498258 UTL default      audit                    1
12/08 10:56:34.155126 00498258 UTL default      auditCreateTable         1
12/08 10:56:34.155127 00498258 UTL default      crashReporting           1
12/08 10:56:34.155128 00498258 UTL default      telemetryReporting       1
12/08 10:56:34.155129 00498258 UTL default      telemetryInterval        43200
12/08 10:56:34.155130 00498258 UTL default      telemetryServer          telemetry.tdengine.com
12/08 10:56:34.155132 00498258 UTL default      telemetryPort            80
12/08 10:56:34.155133 00498258 UTL default      rsyncPort                873
12/08 10:56:34.155134 00498258 UTL default      snodeAddress             
12/08 10:56:34.155135 00498258 UTL default      checkpointBackupDir      /var/lib/taos/backup/checkpoint/
12/08 10:56:34.155136 00498258 UTL default      tmqMaxTopicNum           20
12/08 10:56:34.155137 00498258 UTL default      transPullupInterval      2
12/08 10:56:34.155138 00498258 UTL default      mqRebalanceInterval      2
12/08 10:56:34.155139 00498258 UTL default      ttlUnit                  86400
12/08 10:56:34.155140 00498258 UTL default      ttlPushInterval          10
12/08 10:56:34.155141 00498258 UTL default      ttlBatchDropNum          10000
12/08 10:56:34.155142 00498258 UTL default      ttlChangeOnWrite         0
12/08 10:56:34.155143 00498258 UTL default      ttlFlushThreshold        100
12/08 10:56:34.155144 00498258 UTL default      trimVDbIntervalSec       3600
12/08 10:56:34.155145 00498258 UTL default      uptimeInterval           300
12/08 10:56:34.155146 00498258 UTL default      queryRsmaTolerance       1000
12/08 10:56:34.155147 00498258 UTL default      timeseriesThreshold      50
12/08 10:56:34.155148 00498258 UTL default      walFsyncDataSizeLimit    104857600
12/08 10:56:34.155150 00498258 UTL default      udf                      1
12/08 10:56:34.155151 00498258 UTL default      udfdResFuncs             
12/08 10:56:34.155152 00498258 UTL default      udfdLdLibPath            
12/08 10:56:34.155153 00498258 UTL default      disableStream            0
12/08 10:56:34.155154 00498258 UTL default      streamBufferSize         134217728
12/08 10:56:34.155155 00498258 UTL default      checkpointInterval       60
12/08 10:56:34.155156 00498258 UTL default      streamSinkDataRate       2.00
12/08 10:56:34.155159 00498258 UTL default      cacheLazyLoadThreshold   500
12/08 10:56:34.155160 00498258 UTL default      lossyColumns             
12/08 10:56:34.155161 00498258 UTL default      fPrecision               0.00
12/08 10:56:34.155163 00498258 UTL default      dPrecision               0.00
12/08 10:56:34.155164 00498258 UTL default      maxRange                 500
12/08 10:56:34.155165 00498258 UTL default      curRange                 100
12/08 10:56:34.155167 00498258 UTL default      ifAdtFse                 0
12/08 10:56:34.155168 00498258 UTL default      compressor               ZSTD_COMPRESSOR
12/08 10:56:34.155169 00498258 UTL default      filterScalarMode         0
12/08 10:56:34.155170 00498258 UTL default      maxStreamBackendCache    128
12/08 10:56:34.155171 00498258 UTL default      pqSortMemThreshold       16
12/08 10:56:34.155172 00498258 UTL default      resolveFQDNRetryTime     100
12/08 10:56:34.155173 00498258 UTL default      s3Accesskey              <accesskey>
12/08 10:56:34.155174 00498258 UTL default      s3Endpoint               <endpoint>
12/08 10:56:34.155175 00498258 UTL default      s3BucketName             <bucketname>
12/08 10:56:34.155176 00498258 UTL default      s3BlockSize              -1
12/08 10:56:34.155177 00498258 UTL default      s3BlockCacheSize         16
12/08 10:56:34.155178 00498258 UTL default      s3PageCacheSize          4096
12/08 10:56:34.155179 00498258 UTL default      s3UploadDelaySec         3600
12/08 10:56:34.155180 00498258 UTL default      minDiskFreeSize          52428800
12/08 10:56:34.155181 00498258 UTL default      enableWhiteList          0
12/08 10:56:34.155183 00498258 UTL default      configDir                /etc/taos/
12/08 10:56:34.155184 00498258 UTL default      scriptDir                /etc/taos/
12/08 10:56:34.155185 00498258 UTL default      logDir                   /var/log/taos/
12/08 10:56:34.155186 00498258 UTL default      minimalLogDirGB          1.00
12/08 10:56:34.155187 00498258 UTL default      numOfLogLines            10000000
12/08 10:56:34.155188 00498258 UTL default      asyncLog                 1
12/08 10:56:34.155189 00498258 UTL default      logKeepDays              0
12/08 10:56:34.155190 00498258 UTL default      debugFlag                0
12/08 10:56:34.155191 00498258 UTL default      simDebugFlag             143
12/08 10:56:34.155192 00498258 UTL default      tmrDebugFlag             131
12/08 10:56:34.155193 00498258 UTL default      uDebugFlag               131
12/08 10:56:34.155194 00498258 UTL default      rpcDebugFlag             131
12/08 10:56:34.155195 00498258 UTL default      jniDebugFlag             131
12/08 10:56:34.155196 00498258 UTL default      qDebugFlag               131
12/08 10:56:34.155197 00498258 UTL default      cDebugFlag               131
12/08 10:56:34.155198 00498258 UTL default      dDebugFlag               131
12/08 10:56:34.155200 00498258 UTL default      vDebugFlag               131
12/08 10:56:34.155201 00498258 UTL default      mDebugFlag               131
12/08 10:56:34.155202 00498258 UTL default      wDebugFlag               131
12/08 10:56:34.155203 00498258 UTL default      sDebugFlag               131
12/08 10:56:34.155204 00498258 UTL default      tsdbDebugFlag            131
12/08 10:56:34.155205 00498258 UTL default      tqDebugFlag              131
12/08 10:56:34.155206 00498258 UTL default      fsDebugFlag              131
12/08 10:56:34.155207 00498258 UTL default      udfDebugFlag             131
12/08 10:56:34.155208 00498258 UTL default      smaDebugFlag             131
12/08 10:56:34.155209 00498258 UTL default      idxDebugFlag             131
12/08 10:56:34.155210 00498258 UTL default      tdbDebugFlag             131
12/08 10:56:34.155211 00498258 UTL default      metaDebugFlag            131
12/08 10:56:34.155212 00498258 UTL default      stDebugFlag              131
12/08 10:56:34.155213 00498258 UTL default      timezone                 Asia/Shanghai (CST, +0800)
12/08 10:56:34.155214 00498258 UTL default      locale                   zh_CN.UTF-8
12/08 10:56:34.155217 00498258 UTL default      charset                  UTF-8
12/08 10:56:34.155218 00498258 UTL default      assert                   1
12/08 10:56:34.155219 00498258 UTL default      enableCoreFile           1
12/08 10:56:34.155220 00498258 UTL default      numOfCores               16.00
12/08 10:56:34.155222 00498258 UTL default      ssd42                    0
12/08 10:56:34.155223 00498258 UTL default      avx                      0
12/08 10:56:34.155224 00498258 UTL default      avx2                     0
12/08 10:56:34.155225 00498258 UTL default      fma                      0
12/08 10:56:34.155226 00498258 UTL default      avx512                   0
12/08 10:56:34.155227 00498258 UTL default      simdEnable               0
12/08 10:56:34.155228 00498258 UTL default      tagFilterCache           0
12/08 10:56:34.155229 00498258 UTL default      openMax                  1048576
12/08 10:56:34.155230 00498258 UTL default      streamMax                16
12/08 10:56:34.155232 00498258 UTL default      pageSizeKB               4
12/08 10:56:34.155233 00498258 UTL default      totalMemoryKB            15830880
12/08 10:56:34.155234 00498258 UTL default      os sysname               Linux
12/08 10:56:34.155235 00498258 UTL default      os nodename              LSS-pc
12/08 10:56:34.155236 00498258 UTL default      os release               5.10.0-8-generic
12/08 10:56:34.155237 00498258 UTL default      os version               #33~v10pro-KYLINOS SMP Wed Mar 22 07:21:49 UTC 2023
12/08 10:56:34.155238 00498258 UTL default      os machine               x86_64
12/08 10:56:34.155239 00498258 UTL default      version                  3.2.1.0
12/08 10:56:34.155240 00498258 UTL default      compatible_version       3.0.0.0
12/08 10:56:34.155241 00498258 UTL default      gitinfo                  234463fcca65f3f1d08a1f245570e4e5d5d272e2
12/08 10:56:34.155242 00498258 UTL default      buildinfo                Built Linux-x64 at 2023-11-20 17:29:01 +0800
12/08 10:56:34.155243 00498258 UTL =================================================================
12/08 10:56:34.157079 00498258 DND start to init dnode env
12/08 10:56:34.157253 00498258 DND dnode file:/var/lib/taos//dnode/dnode.json not exist
12/08 10:56:34.157277 00498258 DND mnode file:/var/lib/taos//mnode/mnode.json not exist
12/08 10:56:34.157280 00498258 DND deploy mnode required. dnodeId:0<=0, clusterId:0<=0, localEp:LSS-pc:6030==firstEp
12/08 10:56:34.157284 00498258 DND file:/var/lib/taos//qnode/qnode.json not exist
12/08 10:56:34.157286 00498258 DND file:/var/lib/taos//snode/snode.json not exist
12/08 10:56:34.157392 00498258 DND ERROR failed to create dnode since Not found
12/08 10:56:34.157396 00498258 DND ERROR failed to init dnode since unsupported platform, please visit https://www.taosdata.com for support

**Comment by yu285** [comment]
3100 后，企业版/开源版支持范畴有调整，参考：

https://docs.taosdata.com/reference/support-platform/
