### ISSUE TITLE
Document needs to be rich

### ISSUE THREAD

**Issue by yzpnet** [taosdata/TDengine#24]
Document needs to be rich

**Comment by StoneT2000** [comment]
Can you elaborate on which documents? What do you mean by rich?

**Comment by akzi** [comment]
> Can you elaborate on which documents? What do you mean by rich?

how to setup cluster and how to manager cluser ?
how to replicate data between cluster nodes ?
it use raft or paxos ?
it will auto recovery when nodes go failed?

**Comment by guanshengliang** [comment]
sorry, the cluster has no open source yet
