### ISSUE TITLE
请教：降采查询INTERVAL时，怎么限制到只统计某个时间段内的数据

### ISSUE THREAD

**Issue by 379386901** [taosdata/TDengine#24047]
**降采查询INTERVAL(1d)时，怎么限制到只统计某个时间段内的数据。**

例如：
降采样查询每天的谷电量（谷电量是指每天晚上23点至第二天早上7点之间的用电量总和），
即：想要只统计1年中每天23点~7点的电量。

以下sql只是降采查询1整天的：
`SELECT _wstart, sum(current) FROM d1001 INTERVAL(1d);`

**Comment by 379386901** [comment]
目前考虑到一种比字符串匹配更好的办法：
时间戳求差值函数TIMEDIFF+时间戳截断函数TIMETRUNCATE，组成查询条件，`TIMEDIFF(ts,TIMETRUNCATE(ts, 1d))>xxxx`

例如：
`select _wstart,count(*)  from table_xxxx  where  TIMEDIFF(ts,TIMETRUNCATE(ts, 1d)) between xxxxx and yyyy  interval(1h);`

**Comment by 379386901** [comment]
用函数性能不好，还是改用字符串匹配了

**Comment by random1919** [comment]
老哥怎么解决的
