### ISSUE TITLE
tdengine3.0.7.1三节点集群，不定期的出现重启，产生core文件

### ISSUE THREAD

**Issue by boomion** [taosdata/TDengine#24077]
tdengine3.0.7.1构建的三个节点集群，不定期的会出现各个节点自动重启，这是12-14两个节点产生的core文件
![image](https://github.com/taosdata/TDengine/assets/9972202/5a20b572-a50a-45d8-923d-b2c729960b7e)
![image](https://github.com/taosdata/TDengine/assets/9972202/611b22f5-d0ea-452e-8cea-c585642f3ad1)

请问，tdengine在什么情况下会自动重启，具体原因该如何定位

**Comment by yu285** [comment]
升级到3210即可，如果升级后还有问题，可reopen 该问题。

**Comment by boomion** [comment]
能帮忙分析一下么，生产环境不大敢升级，也没经验

**Comment by ranchunfu** [comment]
请问该问题解决了么？如何升级的？有指导文档么？感谢感谢

**Comment by boomion** [comment]
> 请问该问题解决了么？如何升级的？有指导文档么？感谢感谢

没有额
