### ISSUE TITLE
TDengine-server-3.0.7.1-Windows-x64 no respond during concurrent query

### ISSUE THREAD

**Issue by lves2014** [taosdata/TDengine#24087]
我用.Net 写了一个webapi接口调试并发，numThreads频繁调用几次，有较大概率出现连接成功，线程卡死的情况。

`
public class TDengineWS2Controller : ControllerBase
{
    [HttpGet("api/ws-test")]
    public async Task<string> TestConcurrent(int numThreads)
    {
        var rd = new Random();

        Task[] tasks = new Task[numThreads];

        for (int i = 0; i < numThreads; i++)
        {
            tasks[i] = Task.Run(() => GetData($"select * from smart_water.meters where siteId = {rd.Next(1, 3000)} limit 10"));
        }
        await Task.WhenAll(tasks);

        return "并发测试完成";
    }

    public void GetData(string select)
    {
        string DSN = "ws://root:taosdata@127.0.0.1:6041/smart_water";
        IntPtr wsConn = LibTaosWS.WSConnectWithDSN(DSN);
        if (wsConn == IntPtr.Zero)
        {
            Console.WriteLine("get WS connection failed");                
        }
        else
        {
            Console.WriteLine("Establish connect success.");
        }
        //卡死在这行
        IntPtr wsRes = LibTaosWS.WSQueryTimeout(wsConn, select, 1);

        int code = LibTaosWS.WSErrorNo(wsRes);
        if (code != 0)
        {
            Console.WriteLine($"execute SQL failed: reason: {LibTaosWS.WSErrorStr(wsRes)}, code:{code}");
            LibTaosWS.WSFreeResult(wsRes);
        }

        //......

        LibTaosWS.WSFreeResult(wsRes);

        LibTaosWS.WSClose(wsConn);
    }
}`

`卡死后控制台taos> show dnodes;
status   |   note                            |
=====================
offline  |   status msg timeout     |`

**Comment by yu285** [comment]
3.1.0.0 开始windows是企业版范畴了，为了方便使用和后续的升级，开源版用户请使用 linux  版本的最新版（目前是 3.2.1.0） ，不会有类似问题。
