### ISSUE TITLE
3.2.0.0

### ISSUE THREAD

**Issue by yusir1st** [taosdata/TDengine#24086]
**Bug Description**
3.2.0.0 版本建库时报内存不足，但是真实物理内存还有。详情见附件
<img width="784" alt="taosbug" src="https://github.com/taosdata/TDengine/assets/100739557/14fd9b9c-964b-4c4b-9bb9-fa82ada02ac9">

**Comment by yu285** [comment]
可以加我微信，a15652223354 做具体排查

**Comment by yusir1st** [comment]
经沟通，初步定位是内存不足的问题，初步判断是 “建库阶段，只会检查当前剩余量 即 free，并不会将cache 也计算在内“；具体问题还要工程师分析代码逻辑，感谢！
