### ISSUE TITLE
golang连接问题

### ISSUE THREAD

**Issue by hsnxiaoning** [taosdata/TDengine#241]
用golang连接tdengine，ping时报错
taos_connect() fail!
操作系统：ubuntu18.04
版本：1.6.1.2
golang版本：1.10
golang代码：
`package main

import (
	"database/sql"
	_ "taosSql"
)

func main(){
	//db, err := sql.Open("taosSql", "root:taosdata@tcp(127.0.0.1:6035)/test_db")
	db, err := sql.Open("taosSql", "root:taosdata@tcp(127.0.0.1:6035)/test_db")

	defer db.Close()
	if err != nil {
		panic(err)
	}

	err = db.Ping()
	if err != nil {
		panic(err)
	}
	
}
`

**Comment by plum-lihui** [comment]
不好意思，TDengine的driver目前不支持go sql的ping接口。

**Comment by hsnxiaoning** [comment]
> 不好意思，TDengine的driver目前不支持go sql的ping接口。

测试了一下query，报了一样的错
代码如下：
package main

import (
	"database/sql"
	"fmt"
	_ "taosSql"
)

func main() {
	db, err := sql.Open("taosSql", "root:taosdata@tcp(127.0.0.1:6035)/flow_db")
	if err != nil {
		panic(err)
	}

	defer db.Close()
	r, err := db.Query("select * from flow_db.flow")
	if err != nil {
		panic(err)
	}

	fmt.Println(r)
}

**Comment by plum-lihui** [comment]
今天上午修复了一个dsn的解析bug，请取一下最新的代码。
另外，db, err := sql.Open("taosSql", "root:taosdata@tcp(127.0.0.1:6035)/flow_db")： 这里的ip地址应该填写环境中taosd 实际使用的ip地址，port 可以填写0，内部就会使用缺省的端口值。

**Comment by hsnxiaoning** [comment]
> 今天上午修复了一个dsn的解析bug，请取一下最新的代码。
> 另外，db, err := sql.Open("taosSql", "root:taosdata@tcp(127.0.0.1:6035)/flow_db")： 这里的ip地址应该填写环境中taosd 实际使用的ip地址，port 可以填写0，内部就会使用缺省的端口值。

测试已经可以使用了

**Comment by zhuqiyun** [comment]
> > 今天上午修复了一个dsn的解析bug，请取一下最新的代码。
> > 另外，db, err := sql.Open("taosSql", "root:taosdata@tcp(127.0.0.1:6035)/flow_db")： 这里的ip地址应该填写环境中taosd 实际使用的ip地址，port 可以填写0，内部就会使用缺省的端口值。
> 
> 测试已经可以使用了
我这边出出现了同样的问题，ubuntu20.04，版本1.6.6.1，一直解决不了
