### ISSUE TITLE
连接6030端口时，报错

### ISSUE THREAD

**Issue by xufh2016** [taosdata/TDengine#24103]
**Bug Description**
12/18 08:43:48.691242 00023562 RPC ERROR TSC msg heartbeat failed to send, conn 0x7fada4001ee0 failed to connect to VM-4-11-centos:6030, reason: connection refused, gtid:0xfc8bc86108525323:0x10807a61083baff
12/18 08:43:48.701467 00023562 RPC ERROR TSC msg heartbeat failed to send, conn 0x7fada4000ae0 failed to connect to VM-4-11-centos:6030, reason: connection refused, gtid:0xfc8bc86108525323:0x10807a61083baff
12/18 08:43:48.722781 00023562 RPC ERROR TSC msg heartbeat failed to send, conn 0x7fada4000ae0 failed to connect to VM-4-11-centos:6030, reason: connection refused, gtid:0xfc8bc86108525323:0x10807a61083baff
12/18 08:43:48.763085 00023562 RPC ERROR TSC msg heartbeat failed to send, conn 0x7fada4000ae0 failed to connect to VM-4-11-centos:6030, reason: connection refused, gtid:0xfc8bc86108525323:0x10807a61083baff
12/18 08:43:48.843443 00023562 RPC ERROR TSC msg heartbeat failed to send, conn 0x7fada4000ae0 failed to connect to VM-4-11-centos:6030, reason: connection refused, gtid:0xfc8bc86108525323:0x10807a61083baff
12/18 08:43:49.003964 00023562 RPC ERROR TSC msg heartbeat failed to send, conn 0x7fada4000ae0 failed to connect to VM-4-11-centos:6030, reason: connection refused, gtid:0xfc8bc86108525323:0x10807a61083baff
12/18 08:43:49.324534 00023562 RPC WARN TSC conn 0x7fada4000ae0 send cost:633652us, send exception
12/18 08:43:49.465320 00023563 RPC WARN TSC conn 0x7fad9c000940 send cost:2274618us, send exception
12/18 08:43:49.965759 00023562 RPC WARN TSC conn 0x7fada4000ae0 send cost:1274876us, send exception
12/18 08:43:50.466680 00023563 RPC WARN TSC conn 0x7fad9c000940 send cost:3275978us, send exception

**Comment by yu285** [comment]
是连接问题 https://www.taosdata.com/engineering/11076.html 看下问题1 排查一下
