### ISSUE TITLE
taosdump data dumped in  failed

### ISSUE THREAD

**Issue by aggaadfr** [taosdata/TDengine#24140]
**问题**
使用taosdump导入数据，查看taosdump导入日志文件，有ERROR报错信息：[31mERROR: getSchemaAndReaderFromFile() LN7149, Unable to open avro file /opt/data/backdata/wlcb/taosdump.3401096796155/data0/: Cannot read 4 bytes from file  

**命令**
导出：nohup taosdump  -o /data/dataBack/wlcb --databases wlcb-c /etc/taos -h tdengine1 -P 6030 -T 8 > insetData.log &
导入：nohup taosdump  -i /opt/data/backdata/wlcb --databases wlcb  -c /etc/taos -h bigdata1 -P 6030 -T 16 > insetData.log &

**现象**
查看导入数据时发现有数据丢失

**错误日志**
4398 ^[[0m^[[31mERROR: dumpInAvroWorkThreadFp() LN7370, failed to dump file:
4399 ^[[0m^[[33mWARN: [10] -1 row(s) of file() failed to dumped in!
4400 ^[[0m^[[31mERROR: getSchemaAndReaderFromFile() LN7149, Unable to open avro file /opt/data/backdata/wlcb/taosdump.3401096796155/data0/: Cannot read 4 bytes from file
4401 ^[[0m^[[31mERROR: dumpInOneAvroFile() LN7255, failed to get schema
4402 ^[[0m^[[31mERROR: dumpInAvroWorkThreadFp() LN7370, failed to dump file:
4403 ^[[0m^[[33mWARN: [10] -1 row(s) of file() failed to dumped in!
4404 ^[[0m^[[31mERROR: getSchemaAndReaderFromFile() LN7149, Unable to open avro file /opt/data/backdata/wlcb/taosdump.3401096796155/data0/: Cannot read 4 bytes from file
4405 ^[[0m^[[31mERROR: dumpInOneAvroFile() LN7255, failed to get schema
4406 ^[[0m^[[31mERROR: dumpInAvroWorkThreadFp() LN7370, failed to dump file:
4407 INFO: [10]:84%
4408 INFO: [10]:85%
4409 INFO: [10]:86%
4410 INFO: [10]:87%
4411 INFO: [10]:88%
4412 INFO: [10]:89%
4413 INFO: [10]:90%
4414 ^[[0m^[[33mWARN: [10] -1 row(s) of file() failed to dumped in!
4415 ^[[0m^[[31mERROR: getSchemaAndReaderFromFile() LN7149, Unable to open avro file /opt/data/backdata/wlcb/taosdump.3401096796155/data0/: Cannot read 4 bytes from file
4416 ^[[0m^[[31mERROR: dumpInOneAvroFile() LN7255, failed to get schema
4417 ^[[0m^[[31mERROR: dumpInAvroWorkThreadFp() LN7370, failed to dump file:
4418 ^[[0m^[[33mWARN: [10] -1 row(s) of file() failed to dumped in!
4419 ^[[0m^[[31mERROR: getSchemaAndReaderFromFile() LN7149, Unable to open avro file /opt/data/backdata/wlcb/taosdump.3401096796155/data0/: Cannot read 4 bytes from file
4420 ^[[0m^[[31mERROR: dumpInOneAvroFile() LN7255, failed to get schema
4421 ^[[0m^[[31mERROR: dumpInAvroWorkThreadFp() LN7370, failed to dump file:
4422 ^[[0m^[[33mWARN: [10] -1 row(s) of file() failed to dumped in!
******
4598 ^[[0mINFO: [5]:34%
4599 ....xxx.x^[[32mOK: [12] 682146 row(s) of file(wlcb.3401097880896.1157.avro) be successfully dumped in!
4600 ^[[0m.x.xxx...x....x.xx.xx.x..x.x.xx.xx.xx^[[32mOK: [9] 684176 row(s) of file(wlcb.3401112963947.1786.avro) be successfully dumped in!
4601 ^[[0m.x.x.x....xxxx.xx..x^[[32mOK: [6] 682347 row(s) of file(wlcb.3401101979766.10.avro) be successfully dumped in!
4602 ^[[0m...xx...xx.xxx...x...xx.xxxx..x.xxx.x.....xxxx.x..^[[32mOK: [1] 685225 row(s) of file(wlcb.3401119994356.1232.avro) be successfully dumped in!
4603 ^[[0m..x...xxxx.xx.x.x....xx.x.xxxx.x...x.^[[32mOK: [15] 690249 row(s) of file(wlcb.3401143174733.1015.avro) be successfully dumped in!
4604 ^[[0m.xxxx.x...x..xx.....xx..xxx..xxxxx.xx..xx.xx.x.....^[[32mOK: [4] 684649 row(s) of file(wlcb.3401114681599.1791.avro) be successfully dumped in!
4605 ^[[0mINFO: [4]:36%
4606 .xxxx...x..x.xx.x.x.x....xx.xx.x^[[32mOK: [12] 684598 row(s) of file(wlcb.3401115045045.1503.avro) be successfully dumped in!
4607 ^[[0mINFO: [12]:38%
4608 .xxx..xxxxxx.^[[32mOK: [11] 682403 row(s) of file(wlcb.3401126679410.1824.avro) be successfully dumped in!
4609 ^[[0m^[[31mERROR: getSchemaAndReaderFromFile() LN7149, Unable to open avro file /opt/data/backdata/wlcb/taosdump.3401096796155/data0/: Cannot read 4 bytes from file
4610 ^[[0m^[[31mERROR: dumpInOneAvroFile() LN7255, failed to get schema
4611 ^[[0m^[[31mERROR: dumpInAvroWorkThreadFp() LN7370, failed to dump file:
4612 ^[[0m^[[33mWARN: [11] -1 row(s) of file() failed to dumped in!
4613 ^[[0m^[[31mERROR: getSchemaAndReaderFromFile() LN7149, Unable to open avro file /opt/data/backdata/wlcb/taosdump.3401096796155/data0/: Cannot read 4 bytes from file
4614 ^[[0m^[[31mERROR: dumpInOneAvroFile() LN7255, failed to get schema
4615 ^[[0m^[[31mERROR: dumpInAvroWorkThreadFp() LN7370, failed to dump file:
4616 ^[[0m^[[33mWARN: [11] -1 row(s) of file() failed to dumped in!
4617 ^[[0m^[[31mERROR: getSchemaAndReaderFromFile() LN7149, Unable to open avro file /opt/data/backdata/wlcb/taosdump.3401096796155/data0/: Cannot read 4 bytes from file
4618 ^[[0m^[[31mERROR: dumpInOneAvroFile() LN7255, failed to get schema
4619 ^[[0m^[[31mERROR: dumpInAvroWorkThreadFp() LN7370, failed to dump file:
4620 ^[[0m^[[33mWARN: [11] -1 row(s) of file() failed to dumped in!
4621 ^[[0m^[[31mERROR: getSchemaAndReaderFromFile() LN7149, Unable to open avro file /opt/data/backdata/wlcb/taosdump.3401096796155/data0/: Cannot read 4 bytes from file
4622 ^[[0m^[[31mERROR: dumpInOneAvroFile() LN7255, failed to get schema
4623 ^[[0m^[[31mERROR: dumpInAvroWorkThreadFp() LN7370, failed to dump file:
******
4650 ^[[0m^[[31mERROR: dumpInOneAvroFile() LN7255, failed to get schema
4651 ^[[0m^[[31mERROR: dumpInAvroWorkThreadFp() LN7370, failed to dump file:
4652 ^[[0m^[[33mWARN: [11] -1 row(s) of file() failed to dumped in!
4653 ^[[0m^[[31mERROR: getSchemaAndReaderFromFile() LN7149, Unable to open avro file /opt/data/backdata/wlcb/taosdump.3401096796155/data0/: Cannot read 4 bytes from file
4654 ^[[0m^[[31mERROR: dumpInOneAvroFile() LN7255, failed to get schema
4655 ^[[0m^[[31mERROR: dumpInAvroWorkThreadFp() LN7370, failed to dump file:
4656 ^[[0m^[[33mWARN: [11] -1 row(s) of file() failed to dumped in!
4657 ^[[0m^[[31mERROR: getSchemaAndReaderFromFile() LN7149, Unable to open avro file /opt/data/backdata/wlcb/taosdump.3401096796155/data0/: Cannot read 4 bytes from file
4658 ^[[0m^[[31mERROR: dumpInOneAvroFile() LN7255, failed to get schema
4659 ^[[0m^[[31mERROR: dumpInAvroWorkThreadFp() LN7370, failed to dump file:
4660 ^[[0m^[[33mWARN: [11] -1 row(s) of file() failed to dumped in!
4661 ^[[0m^[[31mERROR: getSchemaAndReaderFromFile() LN7149, Unable to open avro file /opt/data/backdata/wlcb/taosdump.3401096796155/data0/: Cannot read 4 bytes from file
4662 ^[[0m^[[31mERROR: dumpInOneAvroFile() LN7255, failed to get schema
4663 ^[[0m^[[31mERROR: dumpInAvroWorkThreadFp() LN7370, failed to dump file:
4664 ^[[0m^[[33mWARN: [11] -1 row(s) of file() failed to dumped in!
4665 ^[[0m^[[31mERROR: getSchemaAndReaderFromFile() LN7149, Unable to open avro file /opt/data/backdata/wlcb/taosdump.3401096796155/data0/: Cannot read 4 bytes from file
4666 ^[[0m^[[31mERROR: dumpInOneAvroFile() LN7255, failed to get schema
4667 ^[[0m^[[31mERROR: dumpInAvroWorkThreadFp() LN7370, failed to dump file:
4668 ^[[0m^[[33mWARN: [11] -1 row(s) of file() failed to dumped in!
4669 ^[[0mINFO: [11]:38%
4670 INFO: [11]:39%
4671 INFO: [11]:40%
4672 INFO: [11]:41%
4673 INFO: [11]:42%
4674 INFO: [11]:43%
4675 INFO: [11]:44%
4676 INFO: [11]:45%
4677 INFO: [11]:46%
4678 INFO: [11]:47%
4679 INFO: [11]:48%
4680 .....xx.x.xx..x..x.xx..x...xxx...x.x.xxxxx.xxx...xx....x.xx.xxx.x...x..^[[32mOK: [5] 682823 row(s) of file(wlcb.3401130474441.393.avro) be successfully dumped in!
4681 ^[[0m..xx.x...xxx.x^[[32mOK: [13] 695111 row(s) of file(wlcb.3401168021749.1383.avro) be successfully dumped in!
4682 ^[[0mINFO: [13]:32%
4683 ..x.xxx..xx..x.x.xxxx..^[[32mOK: [14] 689547 row(s) of file(wlcb.3401139948432.133.avro) be successfully dumped in!
4684 ^[[0m..xxx.x......xx.xx..xxxx.....xx..xxxx.xxx...xx....xxxx.x^[[32mOK: [4] 678567 row(s) of file(wlcb.3401097537215.1444.avro) be successfully dumped in!
4685 ^[[0m.x....x...xxxxx....xx.xx^[[32mOK: [7] 694871 row(s) of file(wlcb.3401166591181.1959.avro) be successfully dumped in!
4686 ^[[0m.xx.xx.x....xxx..x..x..x...xxxxx...xx..xxxx.xxx.....x.xx.xx..x.....xxxxx.x..x..xx.xxxxx....x..xx.xx..x.....xxxx.xx..x..xx.xxxxx....x...xxx..xx....^[[32mOK: [12] 683675 row(s) of f     ile(wlcb.3401109146641.39.avro) be successfully dumped in!

**版本情况**
 - Ubuntu22.04
 - cpu、内存、磁盘：4C  24G  2T   共7台
 - 导出的TDengine版本为：3.0.4.1  
 - 导入的TDengine版本为： 3.2.0.0   
 - taosdump Version [2.5.2]  导出和导入都是同一个版本

**Comment by yu285** [comment]
导入方使用 3.2.2.0 自带的2.5.4 再做尝试

**Comment by aggaadfr** [comment]
> 导入方使用 3.2.2.0 自带的2.5.4 再做尝试

好的，正在使用最新版的TDengine-3.2.2.0自带的taosdump导入数据。截止到现在，导入数据没有出现上述的报错，我会持续更近返回进展和结果。

**Comment by aggaadfr** [comment]
升级到最新版本的TDengine-3.2.2.0自带的taosdump后，问题以解决。

**Comment by timelessRecall** [comment]
您好 我从3.2.2.0导入到3.3.4.3后，再从3.3.4.3导入到另一台3.3.4.3的服务器时 报了上述错误
