### ISSUE TITLE
differ from current cluster:2966319457849330870

### ISSUE THREAD

**Issue by veigue** [taosdata/TDengine#24143]
集群重启后，节点间提示集群ID不一致怎么处理呢？
![image](https://github.com/taosdata/TDengine/assets/16631277/14a26c8a-c53e-495f-8a9a-772e07eb4a52)

**Comment by yu285** [comment]
应该是是搭测试环境，集群搞乱了吧。应该是数据文件目录被清空或者重置和之前的集群id不匹配。

重新搭一下吧

**Comment by veigue** [comment]
好的，我这边清除重置一下。
