### ISSUE TITLE
New installation with error: "DB error: version of client and server not match"

### ISSUE THREAD

**Issue by gozhhu** [taosdata/TDengine#2415]
**Bug Description**
I just downloaded TDengine-server-1.6.6.0-Linux-x64.tar.gz, and install it with: ./install.sh, after that I ran: systemctl start taosd, then "taos", but the error is occured.

**To Reproduce**
1. Download tar.gz
2. Run ./install.sh
3. run taos

**Expected Behavior**
connect to the taosd.

**Screenshots**
<img width="809" alt="WX20200622-224309@2x" src="https://user-images.githubusercontent.com/152880/85301121-03551800-b4da-11ea-9aa0-8f92d0b8b23e.png">

**Environment (please complete the following information):**
 - OS: CentOS 7.5
 - 4C, 8G, 50G
 - TDengine Version 1.6.6.0

**Comment by Aries-Lee1991** [comment]
OK，we'll check it.

**Comment by plum-lihui** [comment]
After installation, you need to start taosd。I guess it's running taosd or the old version。

**Comment by gozhhu** [comment]
It is a new server, and I ran :systemctl start taosd already.
It failed again.

**Comment by gozhhu** [comment]
I setup a new server, and it works fine.

**Comment by Aries-Lee1991** [comment]
It seems the issue could be closed.  If you have any other question, please submit a new issue.
