### ISSUE TITLE
sql 查询 ts between  xx and  xx order by ts desc  结果偶现顺序乱掉

### ISSUE THREAD

**Issue by PuzePuze** [taosdata/TDengine#24152]
版本3.2.1.0 就是这种简单的sql 查询，SELECT * FROM C_1734841174823374849_copy1 WHERE ts BETWEEN '2023-12-20 07:06:30.0' and '2023-12-20 07:11:30.0'  ORDER BY ts desc limit 20;结果会偶现顺序乱掉

**Comment by yu285** [comment]
问题已经修复 麻烦更新到 3.2.2.0 验证
