### ISSUE TITLE
return null but not 0 when executing sum to  column without data

### ISSUE THREAD

**Issue by 516562160** [taosdata/TDengine#24169]
**Bug Description**
聚合函数无符合条件纪录时聚合结果不给默认值而是直接空啥都查询不出来。比如sum，count等，无符合条件纪录应该0

**To Reproduce**
1.建立一张新表
2.不插入数据直接查询
select sum(medium_small_bus_flow) mediumSmallBus,sum(large_bus_flow) largeBus
from dcac.dcac_traffic_survey 
where ts >= '2023-12-22 00:00:00. '
3.
![1703146639148](https://github.com/taosdata/TDengine/assets/46312969/5d594ce5-d649-474f-9047-b53fb470eb1a)

**Expected Behavior**
sum(medium_small_bus_flow) mediumSmallBus 应该聚合为0

**Environment (please complete the following information):**

 - TDengine Version [e.g. 3.0]

**Comment by yu285** [comment]
<img width="634" alt="image" src="https://github.com/taosdata/TDengine/assets/74105241/07f326a0-0b49-46c7-b64d-f48e2b3638e4">
参考 mySQL 返回结果。
