### ISSUE TITLE
Sync leader is unreachable

### ISSUE THREAD

**Issue by SCY-ICT** [taosdata/TDengine#24161]
**Bug Description**

tdengine version：3.2.0.0
三节点集群
部署环境：centos7
taos-jdbcdriver version：3.0.2
jdk8

使用taosshell执行
select distinct tbname from xxstable;
正常返回，

使用jdbc执行，会报错：
Tdengine ERROR(80002662):Fail to get table info,error: Sync leader is unreachable

show dnodes 三个节点都是ready状态
show mnodes 只有一个管理节点，显示为ready状态
集群状态正常

**Comment by yu285** [comment]
需要具体排查，可以添加微信 a15652223354

**Comment by SCY-ICT** [comment]
感谢taos技术人员的支持，本地配置的问题，由于本地环境hosts文件中只添加了一台管理节点的fqdn，没有添加集群中另外两台的

**Comment by ghost8publisment** [comment]
怎么添加

**Comment by SCY-ICT** [comment]
https://docs.taosdata.com/deployment/deploy/


https://www.taosdata.com/tdengine-engineering/1824.html




孙成圆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taosdata/TDengine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月13日(星期三) 下午3:29
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [taosdata/TDengine] Sync leader is unreachable (Issue #24161)





 
怎么添加
