### ISSUE TITLE
DB file corrupted

### ISSUE THREAD

**Issue by gaosong1206** [taosdata/TDengine#2417]
**Bug Description**
1、新建1个数据库，新建一个超级表，新建100000张子表，每个子表写入900000条数据，客户端输入命令，select count(*) from chaojibiao，客户端报错DB file orrupted，重启数据库服务也会报错

2、新建1个数据库，新建一个超级表，新建100000张子表，每个子表写入80000条数据，将/var/lib/taos拷贝到其他目录下，修改taos.cfg中数据文件的路径，重启服务，数据库信息回复，表信息恢复，但是select count(*) from chaojibiao，提示DB file orrupted；

但是如果每个子表写入1条数据，执行select count(*) from chaojibiao就不会提示错误，数据库和数据表信息都可以恢复。

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: 中标麒麟高级服务版v7.4
 - Memory, CPU, 900亿数据占约250G内存，存储在1T机械硬盘上；
 - TDengine Version 1.6.5.6

**Additional Context**

**Comment by Aries-Lee1991** [comment]
您先升级下TDengine的版本可以吗，也许新的版本已经修复了。

**Comment by Aries-Lee1991** [comment]
您好，升级完版本后，问题解决了吗？ @gaosong1206

**Comment by gaosong1206** [comment]
你好:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; DB file corrupted 报错信息不会出现，但是数据仍旧无法恢复

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 共计10w张表，40亿数据，每张表4000条数据，只能恢复表的信息，但是表中的数据无法恢复






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xiaxin Li"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月28日(星期天) 上午10:51
收件人:&nbsp;"taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送:&nbsp;"松仔"<865380824@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [taosdata/TDengine] DB file corrupted (#2417)





 
您好，升级完版本后，问题解决了吗？ @gaosong1206

**Comment by Aries-Lee1991** [comment]
好的，我们看一下。

**Comment by Alpha365** [comment]
我的就是一个database , 里面就两张表 , 一张表300万数据, 另一个2条数据 , 今天查看两条哪个 , 也出现了
![image](https://user-images.githubusercontent.com/50922702/86736880-71ffad00-c066-11ea-871f-057b64b3c278.png)

这个问题会导致以后存入的数据损坏 , 是因为压缩的问题吗 ?放着放着就坏了

**Comment by Aries-Lee1991** [comment]
> 我的就是一个database , 里面就两张表 , 一张表300万数据, 另一个2条数据 , 今天查看两条哪个 , 也出现了
> ![image](https://user-images.githubusercontent.com/50922702/86736880-71ffad00-c066-11ea-871f-057b64b3c278.png)
> 
> 这个问题会导致以后存入的数据损坏 , 是因为压缩的问题吗 ?放着放着就坏了
> 
> 其实我希望你们后续版本能加入数据保护模块 . . 或者数据校验恢复机制 . . . . 稳定性提高 , 那么用它的人会更多 . . .

您这个可以描述的详细些吗，版本号，日志，请附上，方便我们进行分析。

**Comment by xiao781433561** [comment]
我也是同样的问题，切换数据文件路径后，过了几天报错数据文件损坏（重启服务不报错，但是只能查询重启之后的数据，而且过段时间又会出现。。。），之前的数据都查不到了，请问有没有大佬解决了的（解决报错&恢复数据）烦请指导下

**Comment by Aries-Lee1991** [comment]
> 我也是同样的问题，切换数据文件路径后，过了几天报错数据文件损坏（重启服务不报错，但是只能查询重启之后的数据，而且过段时间又会出现。。。），之前的数据都查不到了，请问有没有大佬解决了的（解决报错&恢复数据）烦请指导下

如果你是在2.0遇到的问题，麻烦重启一个Issue吧，他这个问题是基于1.6版本的。
