### ISSUE TITLE
Go connector query string data length

### ISSUE THREAD

**Issue by zhgqiang** [taosdata/TDengine#2418]
go connector `遇到个字符串问题：定义的列长度50，存的值为1X16，通过go读取数据后返回的数据长度是为50，实际应该是4
`
=== RUN   TestQuery1
    TestQuery1: tdegine_test.go:72: 1X16
    TestQuery1: tdegine_test.go:73: [49 88 49 54 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
    TestQuery1: tdegine_test.go:74: 50
--- PASS: TestQuery1 (0.20s)
PASS
ok      command-line-arguments  0.201s
`

**Comment by Aries-Lee1991** [comment]
@liuyq-617 麻烦看一下这个问题哈。

**Comment by liuyq-617** [comment]
TDengine会自动将字符串填充至定义长度，因此len返回一定是50。
可以迭代数组中的字节，跳过为0的字节；或者调用rest接口

**Comment by zhgqiang** [comment]
> TDengine会自动将字符串填充至定义长度，因此len返回一定是50。
> 可以迭代数组中的字节，跳过为0的字节；或者调用rest接口

驱动中不可以处理吗

**Comment by liuyq-617** [comment]
你可以测试一下，提交个pr

**Comment by zhgqiang** [comment]
> 你可以测试一下，提交个pr
已经提交

**Comment by Aries-Lee1991** [comment]
这个问题是否已经解决了呢？ @zhgqiang @liuyq-617

**Comment by Aries-Lee1991** [comment]
看样子已经没有后续，暂时关闭，如果有其他问题，麻烦递交一个新的Issue。
