### ISSUE TITLE
the issue regarding 3.0.4.0 timestamp from future 

### ISSUE THREAD

**Issue by haoguangsu** [taosdata/TDengine#24190]
发现背景：
  告警业务需要大批量频繁插入数据，因为服务器存在系统时间变化的可能性，如果每次插入数据时，都通过获取系统当前时间来批量生成时间戳，则会出现已存在数据被新插入数据覆盖的问题。所以当前业务里，是根据业务来生成的时间戳，类似于7315302343200215041。
  在测试环节，发现同时插入2000条数据时，显示插入成功的数量，大概率会小于2000条，出现数据丢失的情况。
![image](https://github.com/taosdata/TDengine/assets/30803642/f3443a4a-0bff-4510-9ac0-d14fa58d7382)

定位中发现的问题：

![image](https://github.com/taosdata/TDengine/assets/30803642/aefddef7-2e40-45b1-b783-77d74b55d7e5)

![image](https://github.com/taosdata/TDengine/assets/30803642/78adeec8-49b6-42c9-8e3a-06008646dfc7)

往表中插入一条数据，插入成功：
![image](https://github.com/taosdata/TDengine/assets/30803642/4fabbe9a-75b3-49eb-926a-2aa804d88dd3)

再次查询时，显示的主键时间戳不一致：
![image](https://github.com/taosdata/TDengine/assets/30803642/0192db4f-1d34-45e1-9d77-b82889730e90)

将两个oid同时插入，插入成功，但是只显示成功插入一条：
![image](https://github.com/taosdata/TDengine/assets/30803642/ce6a4a04-665d-4258-976c-33aa0f0d984c)

**Comment by haoguangsu** [comment]
补充案例：
1.创建一张表：
 CREATE TABLE `t_event_alarm_eventinfo_yxeventlog` (`oid` TIMESTAMP, `actingtime` TIMESTAMP, `confirmtime` TIMESTAMP) 

2.往其中插入100条数据：
insert into t_event_alarm_eventinfo_yxeventlog(oid) values(7316349513446600449),(7316349513446600705),(7316349513446600961),(7316349513446601217),(7316349513446601473),(7316349513446601729),(7
316349513446601985),(7316349513446602241),(7316349513446602497),(7316349513446602753),(7316349513446603009),(7316349513446603265),(7316349513446603521),(7316349513446603777),(7316349513446604033),(7
316349513446604289),(7316349513446604545),(7316349513446604801),(7316349513446605057),(7316349513446605313),(7316349513446605569),(7316349513446605825),(7316349513446606081),(7316349513446606337),(7
316349513446606593),(7316349513446601729),(7316349513446601985),(7316349513446602241),(7316349513446602497),(7316349513446602753),(7316349513446603009),(7316349513446603265),(7316349513446603521),(7
316349513446603777),(7316349513446604033),(7316349513446604289),(7316349513446604545),(7316349513446604801),(7316349513446605057),(7316349513446605313),(7316349513446605569),(7316349513446605825),(7
316349513446606081),(7316349513446606337),(7316349513446606593),(7316349513446606849),(7316349513446607105),(7316349513446607361),(7316349513446607617),(7316349513446607873),(7316349513446608129),(7
316349513446608385),(7316349513446608641),(7316349513446608897),(7316349513446609153),(7316349513446609409),(7316349513446609665),(7316349513446609921),(7316349513446610177),(7316349513446610433),(7
316349513446610689),(7316349513446610945),(7316349513446611201),(7316349513446611457),(7316349513446611713),(7316349513446611969),(7316349513446612225),(7316349513446612481),(7316349513446612737),(7
316349513446612993),(7316349513446613249),(7316349513446613505),(7316349513446613761),(7316349513446614017),(7316349513446614273),(7316349513446614529),(7316349513446614785),(7316349513446615041),(7
316349513446615297),(7316349513446615553),(7316349513446615809),(7316349513446616065),(7316349513446616321),(7316349513446616577),(7316349513446616833),(7316349513446617089),(7316349513446617345),(7
316349513446617601),(7316349513446617857),(7316349513446618113),(7316349513446618369),(7316349513446618625),(7316349513446618881),(7316349513446619137),(7316349513446619393),(7316349513446619649),(7
316349513446619905),(7316349513446620161),(7316349513446620417),(7316349513446620673);


3.实际入库是80条：
![image](https://github.com/taosdata/TDengine/assets/30803642/7cd87476-0525-42b3-8125-74fd59f98d97)

**Comment by yu285** [comment]
麻烦在新版本3220验证，应该均是修复过的。如果还有问题可以加我微信 a15652223354远程排查

**Comment by haoguangsu** [comment]
> 麻烦在新版本3220验证，应该均是修复过的。如果还有问题可以加我微信 a15652223354远程排查

![image](https://github.com/taosdata/TDengine/assets/30803642/bf1dfbbc-0e27-4571-acae-70a9dab07588)
3.2.2.0版本安装手册有吗？同样的操作安装3.0.4.0，就可以访问。3.2.2.0就报这个错

**Comment by yu285** [comment]
> [haoguangsu](/haoguangsu)

这个报错和版本无关的，你加我微信一下吧。我给你远程看看
