### ISSUE TITLE
【版本号3.0.3.0】【重大bug】select出来的数据在加上limit分页后，同一条数据的值变了

### ISSUE THREAD

**Issue by dudan57** [taosdata/TDengine#24194]
1、数据库有某一条数据，在加上limit分页查询后，本应为null的字段，竟然被赋了值（为0），如下图
<img width="521" alt="企业微信20231222-155450@2x" src="https://github.com/taosdata/TDengine/assets/20554714/05e81535-c734-447e-b78f-56ecac9aafbb">

2、实际上这条数据，这个字段的值为null，如下图
<img width="512" alt="image" src="https://github.com/taosdata/TDengine/assets/20554714/2e02504d-26fa-4a9b-82af-cf46ea506477">

3、奇怪的是，如果把分页数据稍微改下，查出来的数据又正常了，如下图
<img width="534" alt="image" src="https://github.com/taosdata/TDengine/assets/20554714/932490e1-1079-4e55-91e7-4fb7c52d8b5d">

这是什么原因造成的，数据库里存储的某条数据，部分值查出来竟然不对？

**Comment by yu285** [comment]
这是初期版本，升级一下新版 3.2.2.0 就可以了，问题都是修复过的。

**Comment by dudan57** [comment]
OK
