### ISSUE TITLE
对于一个被测设备（比如断路器）采集其电流、电压、功率，但数据不是同一时刻上送，建模时应该采用多列模型还是单列模型？如果采用单列模型，是不是可以不用超级表，使用普通表即可？

### ISSUE THREAD

**Issue by lupon11** [taosdata/TDengine#24209]

**Comment by jiguorui** [comment]
如果一个设备的结构很清晰，并且不太会变化，可以用多列模型。

**Comment by lupon11** [comment]
> 如果一个设备的结构很清晰，并且不太会变化，可以用多列模型。
多列的情况下，在同一时刻下，很可能只会往其中一列插入数据，那么其他列就是空值，这样会对存储及查询有什么影响吗？

**Comment by yafwang** [comment]
> > 如果一个设备的结构很清晰，并且不太会变化，可以用多列模型。
> > 多列的情况下，在同一时刻下，很可能只会往其中一列插入数据，那么其他列就是空值，这样会对存储及查询有什么影响吗？

存储没影响，指定相关列插入即可，查询要看你的应用逻辑，可以使用last取出最新的全部数据

**Comment by lupon11** [comment]
> > > 如果一个设备的结构很清晰，并且不太会变化，可以用多列模型。
> > > 多列的情况下，在同一时刻下，很可能只会往其中一列插入数据，那么其他列就是空值，这样会对存储及查询有什么影响吗？
> 
> 存储没影响，指定相关列插入即可，查询要看你的应用逻辑，可以使用last取出最新的全部数据

对于TSengine来说，空值的列是不会被存储的是吧？

**Comment by yafwang** [comment]
> > > > 如果一个设备的结构很清晰，并且不太会变化，可以用多列模型。
> > > > 多列的情况下，在同一时刻下，很可能只会往其中一列插入数据，那么其他列就是空值，这样会对存储及查询有什么影响吗？
> > 
> > 
> > 存储没影响，指定相关列插入即可，查询要看你的应用逻辑，可以使用last取出最新的全部数据
> 
> 对于TSengine来说，空值的列是不会被存储的是吧？
未指定的列，在查询时为NULL，不会占用空间

**Comment by lupon11** [comment]
> > > > > 如果一个设备的结构很清晰，并且不太会变化，可以用多列模型。
> > > > > 多列的情况下，在同一时刻下，很可能只会往其中一列插入数据，那么其他列就是空值，这样会对存储及查询有什么影响吗？
> > > 
> > > 
> > > 存储没影响，指定相关列插入即可，查询要看你的应用逻辑，可以使用last取出最新的全部数据
> > 
> > 
> > 对于TSengine来说，空值的列是不会被存储的是吧？
> > 未指定的列，在查询时为NULL，不会占用空间

好的，十分感谢您的回答
