### ISSUE TITLE
td突然挂了，然后启动一会，突然又再次挂了

### ISSUE THREAD

**Issue by 821361335** [taosdata/TDengine#2420]
06/23 10:57:57.724034 10570 7fee82ffd700 MON monitor service init success
06/23 10:57:58.362003 10570 7fee8cb00700 MND pConn:0x100d6d0 is rebuild, destIp:0xf900a8c0:192.168.0.249 publicIp:0xf900a8c0:192.168.0.249 usePublicIp:1
06/23 10:57:58.362021 10570 7fee8cb00700 MND login from:fa00a8c0:10692
06/23 10:57:58.377576 10570 7fee8c2ff700 MND pConn:0x100d750 is rebuild, destIp:0xf900a8c0:192.168.0.249 publicIp:0xf900a8c0:192.168.0.249 usePublicIp:1
06/23 10:57:58.377587 10570 7fee8c2ff700 MND login from:fa00a8c0:10692
06/23 10:58:00.830258 10570 7fee8db02700 MND pConn:0x100d7d0 is rebuild, destIp:0x100007f:127.0.0.1 publicIp:0xf900a8c0:192.168.0.249 usePublicIp:0
06/23 10:58:00.830272 10570 7fee8db02700 MND login from:100007f:57768
06/23 10:58:28.317566 10570 7fee8d301700 MND pConn:0x100d850 is rebuild, destIp:0x100007f:127.0.0.1 publicIp:0xf900a8c0:192.168.0.249 usePublicIp:0
06/23 10:58:28.317580 10570 7fee8d301700 MND login from:f900a8c0:46558
06/23 10:58:28.317590 10570 7fee8d301700 MND 0.log.dn_192_168_0_249, uid:1099511758856 meter meta is retrieved
06/23 10:58:34.322286 10570 7fee8cb00700 MND connection from monitor is closed

**Comment by Aries-Lee1991** [comment]
您提了两个重复问题，这个我就给您关闭了，我们在 #2422 上回答。
