### ISSUE TITLE
stream computing performance issue

### ISSUE THREAD

**Issue by lihongguang-lhg** [taosdata/TDengine#24211]
版本: 3.0.5.1
流式计算 计算数据按天汇总, 列有点多 100多列, 只查询当天数据, 需要10几秒, 和查询全部用的时间基本上一致,
请问如何优化?
![image](https://github.com/taosdata/TDengine/assets/66587661/e1f7448f-acae-495b-9ada-f8d4dd2c86ea)

**Comment by yu285** [comment]
我们重构了流计算，麻烦升级到最新版本的 3.2.2.0 吧 ，如果还有问题可以加我微信 a15652223354
