### ISSUE TITLE
"Invalid Vgroup ID",服务器重启后,某个表curd出错

### ISSUE THREAD

**Issue by binshuilong** [taosdata/TDengine#24216]
版本: v2.6.0.16
集群

1.执行 show vgroup;
<img width="1306" alt="image" src="https://github.com/taosdata/TDengine/assets/39979820/98f0437e-3e87-4de7-98f1-bed2c18d52dd">
2.taosd.log
<img width="984" alt="image" src="https://github.com/taosdata/TDengine/assets/39979820/5768acab-bbf2-4000-a6c2-98d00f46417a">

**Comment by yu285** [comment]
开源版已经不提供官方社区支持，请尽早迁移https://www.taosdata.com/tdengine-engineering/17753.html
