### ISSUE TITLE
Failed to connect to server.

### ISSUE THREAD

**Issue by 821361335** [taosdata/TDengine#2422]
06/23 11:14:29.308546 10921 7f4801ae2700 ERROR TSC 0x14e3530 reach the max retry:2, code:29
06/23 11:14:29.308600 10921 7f4807098700 ERROR TSC 0x1302dc0 SQL result:29, failed to connect to server pObj:0x1204ff0
06/23 11:14:29.803549 10921 7f48022e3700 ERROR TSC 0x7f47e8000910 reach the max retry:2, code:16
06/23 11:14:38.323540 10921 7f4801ae2700 ERROR TSC 0x15123f0 reach the max retry:2, code:29
06/23 11:14:38.323584 10921 7f4807098700 ERROR TSC 0x1302dc0 SQL result:29, failed to connect to server pObj:0x1204ff0
06/23 11:14:40.303535 10921 7f48022e3700 ERROR TSC 0x7f47e8000910 reach the max retry:2, code:16
06/23 11:14:47.328550 10921 7f4801ae2700 ERROR TSC 0x15123f0 reach the max retry:2, code:29
06/23 11:14:47.328606 10921 7f4807098700 ERROR TSC 0x1302dc0 SQL result:29, failed to connect to server pObj:0x1204ff0
06/23 11:14:50.803539 10921 7f48022e3700 ERROR TSC 0x7f47e8000910 reach the max retry:2, code:16
06/23 11:14:56.333551 10921 7f48032e5700 ERROR TSC 0x15123f0 reach the max retry:2, code:29
06/23 11:14:56.333598 10921 7f4807098700 ERROR TSC 0x1302dc0 SQL result:29, failed to connect to server pObj:0x1204ff0
06/23 11:15:01.303544 10921 7f4802ae4700 ERROR TSC 0x7f47e8000910 reach the max retry:2, code:16
06/23 11:15:05.338544 10921 7f48032e5700 ERROR TSC 0x15123f0 reach the max retry:2, code:29
06/23 11:15:05.338587 10921 7f4807098700 ERROR TSC 0x1302dc0 SQL result:29, failed to connect to server pObj:0x1204ff0

**Comment by Aries-Lee1991** [comment]
报一下你的版本号，谢谢。

**Comment by 821361335** [comment]
> 报一下你的版本号，谢谢。
版本号是：1.6.5.6

**Comment by Aries-Lee1991** [comment]
好的，我们这边来看一下。

**Comment by Aries-Lee1991** [comment]
> > 报一下你的版本号，谢谢。
> > 版本号是：1.6.5.6

建议您这边先升级成1.6.6.0，再看，正式版本已经更新到1.6.6.0了，有一些问题已经解决，您试试，如果还有问题，再联系我。

**Comment by Aries-Lee1991** [comment]
您好，这个问题暂时关闭了，如果您还有其他问题，可以随时打开，也可以新建一个Issue。
