### ISSUE TITLE
 Unable to establish connection

### ISSUE THREAD

**Issue by lzh123** [taosdata/TDengine#24238]
docker部署 taos
docker 镜像版本是 tdengine/tdengine:2.6.0.1 . 因为第三方程序go采用的的驱动是V2版本，所以taos服务端安装的是2.6版本，
用tdengineGui客户端连接是正常的
![image](https://github.com/taosdata/TDengine/assets/21017205/df4d0129-7f8d-419d-b68b-d40846e75fe1)
但是docker中跑的服务 连不上 taos服务，报了 Unable to establish connection这个错误

**Comment by lzh123** [comment]
执行taosd 
![image](https://github.com/taosdata/TDengine/assets/21017205/61638143-68c7-49f5-82a2-344dbee82727)

**Comment by lzh123** [comment]
dnodeEps.json z中数据截图：
![image](https://github.com/taosdata/TDengine/assets/21017205/e956d447-53d7-4b6c-9189-1fdf29a1f775)

**Comment by luojiyin1987** [comment]
docker 的网络运行模式？ 开放的端口？ 具体的 docker run 命令？ 或者docker-compose 文件 ？

**Comment by lzh123** [comment]
docker  network is NAT

sudo docker run -d --name tdengine --restart=always  \
-h tdengine                        \
-p 6041:6041                       \
-p 6030-6035:6030-6035             \
-p 6030-6035:6030-6035/udp         \
-v /etc/localtime:/etc/localtime   \
-v /usr/local/tdengine/log:/var/log/taos \
-v /usr/local/tdengine/data:/var/lib/taos \
tdengine/tdengine:2.6.0.1

**Comment by lzh123** [comment]
用客户端连接一切操作都是正常的，但是docker容器中插入数据就报错
![image](https://github.com/taosdata/TDengine/assets/21017205/6af56b97-6616-47a6-b0fe-d4de9569d8f8)

**Comment by luojiyin1987** [comment]
unable to establish connection  报错信息， 大概率是网络方面的问题

**Comment by lzh123** [comment]
没查出来啥原因，连redis、连mysql都没有问题，连tdengine就出了这个问题。有没有可供排查的建议

**Comment by yu285** [comment]
如果只是连接问题 https://www.taosdata.com/engineering/11076.html 看下问题1 排查一下

另外2.x 已经不提供官方支持了，请迁移到最新的 3.x 版本：https://www.taosdata.com/tdengine-engineering/17753.html
