### ISSUE TITLE
修改端口后启动不了是什么原因?

### ISSUE THREAD

**Issue by wolfcome110** [taosdata/TDengine#24249]
在cfg/taos.cfg文件中如下配置：
firstEp                   192.168.0.115:60301
serverPort              60301
修改了端口后启动不了,运行环境 win10，目前版本是3.0.4

**Comment by yu285** [comment]
3100 开始windows是企业版范畴了，为了方便使用和后续的升级，开源版用户请使用：

1.使用 linux 

2. 在windows 上使用docker


至于启动问题可以看下启动日志有提示，不过建议还是直接个更换版本，该版本不建议长期使用。
