### ISSUE TITLE
DB error: Vnodes exhausted

### ISSUE THREAD

**Issue by xiaonannet** [taosdata/TDengine#24240]
**Bug Description**
执行创建数据库指令出现以下异常错误，其他库数据写入查询正常，容器重启后无效；
Client Version:3.2.1.0

taos> create database if not exists thinglinks_extend_4;

DB error: Vnodes exhausted (0.000466s)

<img width="616" alt="image" src="https://github.com/taosdata/TDengine/assets/57425893/c549775a-d1dd-490a-a395-3de640df9af1">

**Comment by yu285** [comment]
经调查，这个应该是近期版本新增的错误提示，解决方法依然保持文章中的描述，增加supportVnodes：https://mp.weixin.qq.com/s/QQNkiHSo0nV2TnaH1s5ktg

**Comment by xiasf** [comment]
最新版本 docker 也是这样，无法解决

**Comment by trdmm** [comment]
> 最新版本 docker 也是这样，无法解决

我也是, 只能去`/etc/taos/taos.cfg`中设置`supportVnodes 8`调大*supportVnodes*才好使.
