### ISSUE TITLE
docker deployed TDengine 3.2.2.0  failed

### ISSUE THREAD

**Issue by 2017zhm** [taosdata/TDengine#24299]
**docker 部署 Tdengine 3.2.2.0 版本失败问题**
docker部署命令操作如下
1. docker pull tdengine/tdengine:3.2.2.0
2. docker run -e TAOS_FQDN=tdengine -d -v /app/tdengine/data:/var/lib/taos -v /app/tdengine/logs:/var/log/taos -p 6030:6030 -p 6041:6041 -p 6043-6049:6043-6049 -p 6043-6049:6043-6049/udp tdengine/tdengine:3.2.2.0

在 docker run 命令执行之后报错，docker日志报错信息显示如下：
run TDengine with single node.
12/28 09:19:50.744622 00000073 UTL apoll url not load
12/28 09:19:50.744759 00000073 UTL load from cfg file /etc/taos/taos.cfg success
12/28 09:19:50.744785 00000073 UTL env file:.env not load
12/28 09:19:50.744799 00000073 UTL load from env variables cfg success
failed to init log file since Config not foundfailed to start since init log error
无法启动，但是同样的命令部署 3.0.1.4 版本是能正常启动运行，请求帮助，需要怎么样才能解决这个问题。

**Comment by dongshd** [comment]
![11](https://github.com/taosdata/TDengine/assets/12226358/0386557f-1586-47ee-b7d8-8427bbc48a4b)

**Comment by 2017zhm** [comment]
过一段时间在看是否正常？docker run之后 直接运行 docker ps 也是正常的，但是过一段时间之后就会出现问题，或者是关闭之后再运行是否会出现问题?

**Comment by 2017zhm** [comment]
主要是 报错提示“failed to init log file since Config not foundfailed to start since init log error” 这个是原因导致的？

**Comment by dongshd** [comment]
[root@localhost ~]# docker stop  2981c0f70474              
2981c0f70474
[root@localhost ~]# docker start  2981c0f70474    
2981c0f70474
[root@localhost ~]# docker logs -n 20  2981c0f70474     
01/02 05:51:03.957043 00000054 MND trans:18, continue to execute, stage:commitAction createTime:1704174470857 topHalf:0
01/02 05:51:03.957044 00000054 MND trans:18, commitAction:0 write to sdb, type:cluster status:ready
01/02 05:51:03.957046 00000054 MND trans:18, all 1 actions execute successfully
01/02 05:51:03.957047 00000054 MND trans:18, stage from commitAction to finished
01/02 05:51:03.957048 00000054 MND trans:18, continue to execute, stage:finished createTime:1704174470857 topHalf:0
01/02 05:51:03.957051 00000054 MND trans:18, perform delete action, row:0x47ec9dc stage:finished callfunc:0, stopFunc:0
01/02 05:51:03.957052 00000054 MND trans:18, execute finished, code:0x0, failedTimes:0 createTime:1704174470857
01/02 05:51:03.957054 00000054 MND trans:18, send rsp, stage:finished failedTimes:0 code:0x0
01/02 05:51:03.957055 00000054 MND trans:18, perform delete action, row:0x47ed8fc stage:finished callfunc:1, stopFunc:0
01/02 05:51:03.957058 00000054 SYN vgId:1, commit sync barrier. index:37, term:2, type:sync-noop
01/02 05:51:03.957061 00000054 MND vgId:1, sync restore finished, and will handle outstanding transactions
01/02 05:51:03.957064 00000054 MND mnode set restored:1
01/02 05:51:03.957103 00000054 SYN vgId:1, restore finished. term:2, log buffer: [10 37 37, 38)
01/02 05:51:03.957106 00000054 MND vgId:1, sync started, id:2
01/02 05:51:03.957136 00000054 DND restore 0 vnodes with 1 threads
01/02 05:51:03.957158 00000054 DND The daemon initialized successfully
01/02 05:51:04.956818 00000076 MND dnode:1, mnode syncState from offline to leader, restoreState from 0 to 1, syncTerm from 0 to 2
01/02 05:51:04.956837 00000076 MND dnode:1, from offline to online, memory avail:4493035520 total:5010903040 cores:2.00
01/02 05:51:04.956913 00000082 DND status rsp received from mnode, statusSeq:1:1 dnodeVer:0:2, gtid:0x0:0x38460c8b9bc00002
01/02 05:51:04.957865 00000082 DND succeed to write dnode file:/var/lib/taos//dnode/dnode.json, num:1 ver:2



重启也没问题
确定下启动的命令，使用的目录下面是空的， 本地的data, logs目录

**Comment by xiewjsir** [comment]
遇到了相同的问题。无解吗？

**Comment by WeiduWedo** [comment]
3.2.3也存在这个问题

**Comment by WeiduWedo** [comment]
> 主要是 报错提示“failed to init log file since Config not foundfailed to start since init log error” 这个是原因导致的？

解决了么？

**Comment by gaoyf-china** [comment]
3.2.2.0版本的docker在ubuntu上部署就会有这个问题，在centos上就没事

**Comment by NineTimes** [comment]
版本：3.3.0.0 centos7 docker部署，遇到了同样的问题，请问这个问题解决了吗？
报错信息如下：
sysctl: setting key "kernel.core_pattern", ignoring: Read-only file system
05/31 07:09:17.545787 00000030 C UTL apoll url not load
05/31 07:09:17.545847 00000030 C UTL load from cfg file /etc/taos/taos.cfg success
05/31 07:09:17.545865 00000030 C UTL env file:.env not load
05/31 07:09:17.545875 00000030 C UTL load from env variables cfg success
failed to init log file since Config not foundfailed to start since init log error
runtime/cgo: pthread_create failed: Operation not permitted

**Comment by yu285** [comment]
加上 --privileged

**Comment by buruguichen** [comment]
我也遇到同样的问题，把镜像版本换成3.1.1.0正常启动了

**Comment by ajf12f** [comment]
在 ubuntu 上使用最新的镜像启动遇到了同样的问题，使用  @yu285   提供的参数，解决。非常感谢🙏
```yaml
version: '3.8'

services:
  tdengine:
    image: tdengine/tdengine:latest
    container_name: tdengine
    user: root
    privileged: true   # ✅ 加上这个后可以正常启动，这个破问题浪费我几个小时时间
    ports:
      - "6030:6030"
      - "6041-6047:6041-6047"
    volumes:
      - ./data:/var/lib/taos
      - ./conf/taos.cfg:/etc/taos/taos.cfg:ro
    restart: always

```
