### ISSUE TITLE
count(*) leads to TDengine restart

### ISSUE THREAD

**Issue by systemChina** [taosdata/TDengine#24302]
**Bug Description**
select count(*) from tsp_by_data.tsp_by_data02_la9cj9a49lwjjm329   --执行OK
select count(*) from tsp_by_data.tsp_by_data02 --执行报错
SQL错误[304]: TDengine ERROR(0x130): sgl: select count(*) from tsp_by_data.tsp_by_data_02, desc:Database is starting up

**To Reproduce**
一开始好的，好像是运行了几天数据量大了就不行了。但有些超级表如select count(*) from tsp_by_data.tsp_by_data_01是正常的，执行结果是三千多万

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.9.2009]
 - Memory 62G, CPU 32, current Disk Space 2T
 - TDengine Version [e.g. 3.2.2.0]

**Comment by Yordroid** [comment]
换吧，我这里也是，入库了700w,然后select count(1) from table 就重启了，唉，心累

**Comment by yu285** [comment]
抱歉，为近期的优化导致，已经在3.0 分支修复，可以等发版，也可以自己编译。
