### ISSUE TITLE
请问普通表不能创建tag吗

### ISSUE THREAD

**Issue by lupon11** [taosdata/TDengine#24304]
请问普通表不能创建tag吗

**Comment by yu285** [comment]
不可以的。超级表和tag是一体的，建议先多看下文档了解一下数据模型。

**Comment by yu285** [comment]
如果还有疑问可以添加微信 a15652223354

**Comment by lupon11** [comment]
> 不可以的。超级表和tag是一体的，建议先多看下文档了解一下数据模型。

好的，感谢
