### ISSUE TITLE
streaming computing issue

### ISSUE THREAD

**Issue by shenxiaokou** [taosdata/TDengine#24341]
CLIENT VERSION：3.0.3.0
SERVER VERSION：3.0.3.0
流式计算语句如下：
create stream if not exists stream_meters_hourly fill_history 1 into stream_meters_hourly_stb  
as select _wstart,consumer_id,sum(total_act_power) as total_power 
from meter  partition by consumer_id interval(1h);
源表数据从8点到23点都有数据，预期结果应该是8点-9点、9点-10点数据等每隔1小时进行数据汇总，但是结果间隔非常大

<img width="441" alt="19001a84f6eac36cbc4464f558c8d55" src="https://github.com/taosdata/TDengine/assets/22739570/96dd5d76-6796-4ebd-b6f5-8f2ee34b9335">

问题：
1、为什么查询结果不是按照预期的根据consumer_id每隔1小时进行数据汇总；
2、 interval(1h)这个时间是以哪个时间计算的?难道不是ts吗？

**Comment by yu285** [comment]
流计算经过多次重构，请使用最新版 3220 ，如果还有问题可以reopen该问题。

微信a15652223354 。
