### ISSUE TITLE
Tdengine：3.0.0.1，stable增加tag，子表数据插入异常

### ISSUE THREAD

**Issue by zxloading** [taosdata/TDengine#24345]
Tdengine：3.0.0.1，stable增加tag，已存在的子表，插入数据后，stable中没有插入新增的tag值；新增的子表，插入同样的数据，stable中数据正常

**Comment by yu285** [comment]
这个版本是初始版本。早就被回收了，都没有下载途径。

使用 3.2.1.0 吧。
