### ISSUE TITLE
3.0.0.1 版本 case表达式使用报错

### ISSUE THREAD

**Issue by shancongcong1990** [taosdata/TDengine#24387]
语句:
select case when super = 1 then 'a' else 'b' end from ins_users;

报错:
DB error: syntax error near "super = 1 then 'a' else 'b' end from ins_users;"

**Comment by yu285** [comment]
请使用 3.2.2.0 3.0.0.1 是初始第一个版本，官方已经回收不在再提供。

**Comment by yu285** [comment]
如果新版本还有疑问，可以reopen这个问题
