### ISSUE TITLE
count performance issue

### ISSUE THREAD

**Issue by wsyummy** [taosdata/TDengine#24384]
**Bug Description**
机器配置：16核CPU 2.4*2 内存32GB，磁盘占用率17%
目前数据库实际使用1个PS_COLLECTION,超级表3个， 
ps_data_history_stable   
 energy_data_history_stable   
 sta_data_history_stable     
执行其中一个count(*)
select count(*) from sta_data_history_stable;
等待时间非常长，最终提示DB error: Database is starting up(457.778132s);
重新执行结果一样只是括号内时间长短不一样
如图：

![企业微信截图_17047638004501](https://github.com/taosdata/TDengine/assets/90503267/845da249-28de-4212-9bf0-4ca512a4d2b0)
其他超级表也一样情况

执行过程CPU100%

**Comment by yu285** [comment]
当前没有 3.2.7 版本的数据库，麻烦再确认一下
