### ISSUE TITLE
tdengine:2.4.0.16报很多这种错误“Unable to establish connection”，有时又能正常连接，这是怎么回事啊！

### ISSUE THREAD

**Issue by zhoujinlong** [taosdata/TDengine#24388]
tdengine:2.4.0.16报很多这种错误“Unable to establish connection”，有时又能正常连接，这是怎么回事啊！

**Comment by yu285** [comment]
我们已经不提供 2.4 的支持服务了，麻烦尽早迁移到3.x 上吧https://www.taosdata.com/tdengine-engineering/17753.html
