### ISSUE TITLE
3.2.2.0 taosd  crash

### ISSUE THREAD

**Issue by cancelpj** [taosdata/TDengine#24386]
**Bug Description**
docker 容器在后台运行过程中突然退出，然后查看到有崩溃日志，再启动容器也还是会马上退出。

**To Reproduce**
1. 创建容器的命令是 
docker run -d --name tdengine \
-v ~/data/taos/dnode/data:/var/lib/taos \
-v ~/data/taos/dnode/log:/var/log/taos \
--network host tdengine/tdengine

2. 先停止容器，再解压附件并恢复到 ~/data/taos 文件夹下，然后启动容器。
[taos.tar.gz](https://github.com/taosdata/TDengine/files/13868265/taos.tar.gz)

**.taosdCrashLog**
?      {
	"reportVersion":	1,
	"clusterId":	"4350243688540646131",
	"startTime":	"1703403121736",
	"fqdn":	"localhost",
	"pid":	"56",
	"appName":	"taosd",
	"os":	"Ubuntu 22.04.3 LTS",
	"cpuModel":	"Intel(R) Xeon(R) Gold 5220R CPU @ 2.20GHz",
	"numOfCpu":	1,
	"memory":	"32780332 kB",
	"version":	"3.2.2.0",
	"buildInfo":	"Built Linux-x64 at 2023-12-20 00:20:30 +0800",
	"gitInfo":	"e38f1a2473c648d5254c33f89ba67f6bc3278c5c",
	"crashSig":	"6",
	"crashTs":	"1704659167775034",
	"stackInfo":	"obtained 17 stack frames\nframe:0, /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c) [0x7f40a21019fc]\nframe:1, /lib/x86_64-linux-gnu/libc.so.6(raise+0x16) [0x7f40a20ad476]\nframe:2, /lib/x86_64-linux-gnu/libc.so.6(abort+0xd3) [0x7f40a20937f3]\nframe:3, /lib/x86_64-linux-gnu/libc.so.6(+0x2871b) [0x7f40a209371b]\nframe:4, /lib/x86_64-linux-gnu/libc.so.6(+0x39e96) [0x7f40a20a4e96]\nframe:5, taosd(taosAssertDebug+0x2e9) [0x124b1d0]\nframe:6, taosd() [0x9500a3]\nframe:7, taosd(streamProcessCheckpointBlock+0x170) [0x95027f]\nframe:8, taosd(doStreamExecTask+0x173) [0x95c6c8]\nframe:9, taosd(streamExecTask+0x3d) [0x95cc47]\nframe:10, taosd(tqStreamTaskProcessRunReq+0x124) [0x94d0a2]\nframe:11, taosd(tqProcessTaskRunReq+0x68) [0x7f871b]\nframe:12, taosd(vnodeProcessStreamMsg+0x182) [0x7b803a]\nframe:13, taosd() [0x79b8fd]\nframe:14, taosd() [0x125f0ac]\nframe:15, /lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7f40a20ffac3]\nframe:16, /lib/x86_64-linux-gnu/libc.so.6(clone+0x44) [0x7f40a2190814]\n"
}

**Environment (please complete the following information):**
 - OS: CentOS Linux release 7.9.2009 (Core) + docker 24.0.7
 - Memory, CPU, current Disk Space
 - TDengine Version 3.2.2.0

**Additional Context**
当服务无法启动时，有什么可以保留数据恢复服务的临时性解决措施吗？

**Comment by yu285** [comment]
我们看下

**Comment by yu285** [comment]
![image](https://github.com/taosdata/TDengine/assets/74105241/0e57e7c7-3c09-413f-ad9d-d45f2e3b0ccf)
我用 3.0 分支最新的代码编译后是可以启动的，说明这是一个已知问题。咱们可以尝试一下，如果有问题可以联系我们 
微信 a15652223354
