### ISSUE TITLE
DB error : not active session

### ISSUE THREAD

**Issue by eltonchaw7** [taosdata/TDengine#2442]
我在命令行客户端里执行以下操作：
删除一个超级表>重新创建超级表>往子表写入数据，报错DB error : not active session，然后重新进入，写入成功。

但是在python客户端：
删除一个超级表>重新创建超级表>往子表写入数据，报错DB error : not active session，然后重新建立连接，还是会报DB error : not active session 错误。

**Comment by eltonchaw7** [comment]
1.6.5.5版本

**Comment by Aries-Lee1991** [comment]
收到，我们这边看一下。不过建议您先升级下版本，现在正式版已经是1.6.6.0了。

**Comment by eltonchaw7** [comment]
> 收到，我们这边看一下。不过建议您先升级下版本，现在正式版已经是1.6.6.0了。

1.6.6.0现在会有这个问题吗？

**Comment by Aries-Lee1991** [comment]
> > 收到，我们这边看一下。不过建议您先升级下版本，现在正式版已经是1.6.6.0了。
> 
> 1.6.6.0现在会有这个问题吗？

没听到谁报过这个问题。我们这边也再看一下，您也试试升级，因为有一些版本，可能已经不维护了。

**Comment by eltonchaw7** [comment]
好的，谢谢！我升级下试试

**Comment by Aries-Lee1991** [comment]
升级新版本之后，这个问题解决了吗？ @eltonchaw7

**Comment by Aries-Lee1991** [comment]
已经很久没有新的反馈了，这个问题暂时关闭了，如果遇到新的问题，麻烦重新递交Issue。
