### ISSUE TITLE
taosd -c cfg error on euler20 and euler22 :ERROR failed to init dnode since unsupported platform

### ISSUE THREAD

**Issue by fubingting** [taosdata/TDengine#24431]
taosd -c cfg  can be executed normally on both centos and ubuntu systems.
Error report in euler system: ”ERROR failed to init dnode since unsupported platform”.
Whether the community considers supporting euler system,Thank you

**Comment by yu285** [comment]
3100 后，企业版/开源版支持范畴有调整，参考：

https://docs.taosdata.com/reference/support-platform/

暂做关闭处理，如果还有疑问可添加微信：a15652223354
