### ISSUE TITLE
docker 版本 3.2.2.0 创建表提示表不存在， 查询表server直接退出

### ISSUE THREAD

**Issue by sdvdxl** [taosdata/TDengine#24437]
**Bug Description**
docker 版本 3.2.2.0 创建表提示表不存在， 查询表server直接退出

**To Reproduce**

1. ```bash
    docker run -d --name tdengine \
    -v ~/data/taos/dnode/data:/var/lib/taos \
    -v ~/data/taos/dnode/log:/var/log/taos \
    -p 6041:6041 tdengine/tdengine:3.2.2.0
    ```
2. ```bash
    create database test;
    use test;
    
    CREATE TABLE stb_d (
        ts TIMESTAMP,
        did VARCHAR(64)
    )  ;
    
    insert into s1_stb_d using stb_d tags() VALUES(now(), '1');
```

提示表不存在（一定要是test库）。

1. ```bash
    create database db3;
    use db3;
    
    CREATE TABLE stb_d (
        ts TIMESTAMP,
        did VARCHAR(64)
    )  ;
    
    insert into s1_stb_d using stb_d tags() VALUES(now(), '1');
    select * from stb_d;
```

server 直接退出。

**Environment (please complete the following information):**
![image](https://github.com/taosdata/TDengine/assets/3821540/79d0e0a9-1bf8-4535-8f5f-fcd3a83a815f)

docker 错误日志
![image](https://github.com/taosdata/TDengine/assets/3821540/fa6556a0-1138-491e-9102-a00e71035a01)

**Comment by yu285** [comment]
我在 3.0 最新分支没有遇到这个crash ，应该是已经修复了。

另外 ，    create database db3;
    use db3;
    
    CREATE TABLE stb_d (
        ts TIMESTAMP,
        did VARCHAR(64)
    )  ;
    
    insert into s1_stb_d using stb_d tags() VALUES(now(), '1');
    select * from stb_d;
    
    这个 stb_d 是个普通表，不能这么用。
    
    如果还有疑问可以加微信 a15652223354
