### ISSUE TITLE
3.2.2.0 Multi-table join query  issue

### ISSUE THREAD

**Issue by haoguangsu** [taosdata/TDengine#24470]
问题版本：3.2.2.0

问题表现：
数据库中新增一张表，create table t_test(sdbkey timestamp, name nchar(10));
插入多条数据： insert into t_test values(1705031520000000000, 'name1'),(1705031520000000001, 'name2'),(1705031520000000002, 'name3'),(1705031580000000000, 'name4'),(1705031580000000001, 'name5'),(1705031580000000002, 'name6');

![image](https://github.com/taosdata/TDengine/assets/30803642/83bc5fd4-8ac7-496c-abae-8f3471994eb7)

当执行下面两条sql时，发现了问题：
sql1:
taos>  select * from t_test t1, (select * from t_test order by sdbkey limit 5) t2 where t1.sdbkey  = t2.sdbkey;
![image](https://github.com/taosdata/TDengine/assets/30803642/25ad4bd2-bc2b-4797-8cc7-28eec63930c6)

能够返回结果；

sql2:
taos> select * from t_test t1, (select * from t_test order by sdbkey desc limit 5) t2 where t1.sdbkey  = t2.sdbkey;
![image](https://github.com/taosdata/TDengine/assets/30803642/9388d1e9-9266-43d3-bafb-20f083279dbe)

查询为空。

而sql2也就比sql1，多了一个desc。
![image](https://github.com/taosdata/TDengine/assets/30803642/1d9d20d6-894f-42f0-9b90-06a5830be2a4)

**Comment by yu285** [comment]
我们看下

**Comment by yu285** [comment]
我们会处理，可以加微信 a15652223354 ，有修复进展会随时沟通。

**Comment by yu285** [comment]
该问题已经修复，麻烦验证。

**Comment by yu285** [comment]
可以用最新版本 3.3.2.0
