### ISSUE TITLE
 failed to open vnode  since WAL log incomplete

### ISSUE THREAD

**Issue by NanamiZY** [taosdata/TDengine#24497]
taosd.service - server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2024-01-17 10:31:52 CST; 5min ago
  Process: 8152 ExecStart=/usr/bin/taosd (code=exited, status=255)
  Process: 8146 ExecStartPre=/usr/local/taos/bin/startPre.sh (code=exited, status=0/SUCCESS)
  Process: 8125 ExecStartPre=/bin/sleep 8 (code=exited, status=0/SUCCESS)
 Main PID: 8152 (code=exited, status=255)

**Comment by NanamiZY** [comment]
01/17 10:44:22.507822 00009508 WAL vgId:3, reset commitVer to 77878
01/17 10:44:22.507822 00009507 WAL WARN vgId:2, firstVer:257 is larger than snapshotVer:-1 + 1. align with it.
01/17 10:44:22.507901 00009507 WAL vgId:2, reset commitVer to -1
01/17 10:44:22.507947 00009507 WAL ERROR vgId:2, WAL log entries incomplete in range [0, 58847], index:0, snaphotVer:-1
01/17 10:44:22.507971 00009507 WAL ERROR vgId:2, cannot open wal since repair meta file failed
01/17 10:44:22.508151 00009507 VND ERROR vgId:2, failed to open vnode wal since WAL log incomplete. wal:/tinycs/taos/data/vnode/vnode2/wal
01/17 10:44:22.510295 00009507 DND ERROR vgId:2, failed to open vnode by thread:0 since WAL log incomplete
01/17 10:44:22.512876 00009507 MTA vgId:7, ttl mgr open end, hash size: 0, time consumed: 654801 ns


01/17 10:44:23.429961 00009477 WAL wal module is cleaned up
01/17 10:44:23.430159 00009477 DND ERROR node:vnode, failed to open since Vnode init failure
01/17 10:44:23.430195 00009477 DND ERROR node:vnode, failed to open since Vnode init failure
01/17 10:44:23.430216 00009477 DND ERROR failed to open nodes since Vnode init failure
01/17 10:44:23.430235 00009477 DND node:dnode, start to close
01/17 10:44:23.430284 00009477 UTL worker:dnode-mgmt:0 is stopping

**Comment by NanamiZY** [comment]
断电后重启

**Comment by yu285** [comment]
> 断电后重启
版本号是？ 加我下微信 具体排查一下吧 a15652223354

**Comment by yu285** [comment]
加我微信 a1565223354 具体排查一下吧

**Comment by zc2422** [comment]
请问一下怎么解决的呢？遇到同样的情况了

**Comment by lixuzhen2019** [comment]
请问一下怎么解决的呢？断电后 tdengine就起不来了

**Comment by yu285** [comment]
这个是硬件断电带来的概率性问题，单机一定要做日常备份。而且版本越新越健壮。

所以用新版本，做备份。

**Comment by leijianhang** [comment]
请问一下怎么解决的呢？遇到同样的情况了，断电后 tdengine就起不来了

**Comment by dachun639** [comment]
请问这个怎么恢复的呢 怎么恢复的呢
