### ISSUE TITLE
TDengine 3.2.2.0 count query led to taosd crash

### ISSUE THREAD

**Issue by akailee** [taosdata/TDengine#24506]
**Bug Description**
使用tdengine 3.2.2.0 刚开始一切正常,几天后数据多了后,出现查询,某张超表
 SELECT COUNT(*) AS total FROM xxx WHERE (created_time BETWEEN ? AND ?)
直接报错

### Cause: java.sql.SQLException: ERROR (0x2318): Connect to 192.168.9.235:16041 [/192.168.9.235] failed: 拒绝连接 (Connection refused)
; uncategorized SQLException; SQL state []; error code [8984]; ERROR (0x2318): Connect to 192.168.9.235:16041 [/192.168.9.235] failed: 拒绝连接 (Connection refused); nested exception is java.sql.SQLException: ERROR (0x2318): Connect to 192.168.9.235:16041 [/192.168.9.235] failed: 拒绝连接 (Connection refused)

被踢掉了.另外一张表查询又正常.
使用 TDengineGUI 连接后执行上面的sql也报错.但是自己双击gui里的这张超表查询,又能查询出数据.请问这个怎么解决.

**Comment by yu285** [comment]
抱歉该问题为新近版本的优化导致的bug ,仅针对这个问题，已经解决，大家可以编译 3.0 分支最新使用。

如果不方便编译，也可以备份一下数据文件目录 ，然后尝试降级到3.2.1.1 。

另外注意一下：降级操作一定要在特殊情况（比如bug），在官方指导下，才可以进行。

严格意义上 TDengine 不支持降级。
