### ISSUE TITLE
3.2.2.0 docker  select count(*)  crash

### ISSUE THREAD

**Issue by pppploi8** [taosdata/TDengine#24507]
不太好复现，有的时候在有问题的表里继续写入一些新的历史数据，又会莫名其妙的恢复
查询的是当日数据，sql如下
select count(*) from tablename where ts >= 1705420800000 and ts < 1705507200000

Docker崩溃日志

01/17 09:02:18.937261 00000153 UTL FATAL crash signal is 11
01/17 09:02:18.937284 00000153 UTL FATAL sender PID:80 cmdline:taosd
01/17 09:02:18.946603 00000153 UTL FATAL obtained 29 stack frames
01/17 09:02:18.946609 00000153 UTL FATAL frame:0, taosd(tsdbRowMergerAdd+0x2f) [0x8950f7]
01/17 09:02:18.946611 00000153 UTL FATAL frame:1, taosd() [0x85d65b]
01/17 09:02:18.946613 00000153 UTL FATAL frame:2, taosd() [0x861060]
01/17 09:02:18.946614 00000153 UTL FATAL frame:3, taosd() [0x8616dc]
01/17 09:02:18.946616 00000153 UTL FATAL frame:4, taosd() [0x862b73]
01/17 09:02:18.946617 00000153 UTL FATAL frame:5, taosd() [0x863a41]
01/17 09:02:18.946619 00000153 UTL FATAL frame:6, taosd() [0x8694e5]
01/17 09:02:18.946620 00000153 UTL FATAL frame:7, taosd() [0x86961a]
01/17 09:02:18.946621 00000153 UTL FATAL frame:8, taosd(tsdbNextDataBlock2+0x268) [0x8698af]
01/17 09:02:18.946627 00000153 UTL FATAL frame:9, taosd() [0xef977e]
01/17 09:02:18.946628 00000153 UTL FATAL frame:10, taosd() [0xef9aa9]
01/17 09:02:18.946630 00000153 UTL FATAL frame:11, taosd() [0xefa41f]
01/17 09:02:18.946631 00000153 UTL FATAL frame:12, taosd() [0xefa7d1]
01/17 09:02:18.946632 00000153 UTL FATAL frame:13, taosd(getNextBlockFromDownstreamImpl+0x1aa) [0xeef56a]
01/17 09:02:18.946634 00000153 UTL FATAL frame:14, taosd(getNextBlockFromDownstream+0x25) [0xef1f0e]
01/17 09:02:18.946636 00000153 UTL FATAL frame:15, taosd() [0xf40086]
01/17 09:02:18.946637 00000153 UTL FATAL frame:16, taosd() [0xf403b4]
01/17 09:02:18.946639 00000153 UTL FATAL frame:17, taosd(getNextBlockFromDownstreamImpl+0x1aa) [0xeef56a]
01/17 09:02:18.946640 00000153 UTL FATAL frame:18, taosd(getNextBlockFromDownstream+0x25) [0xef1f0e]
01/17 09:02:18.946642 00000153 UTL FATAL frame:19, taosd() [0xef2fba]
01/17 09:02:18.946643 00000153 UTL FATAL frame:20, taosd(qExecTaskOpt+0x38a) [0xee7dd2]
01/17 09:02:18.946645 00000153 UTL FATAL frame:21, taosd(qwExecTask+0x172) [0xed229b]
01/17 09:02:18.946646 00000153 UTL FATAL frame:22, taosd(qwProcessQuery+0x3cd) [0xed5ef2]
01/17 09:02:18.946647 00000153 UTL FATAL frame:23, taosd(qWorkerProcessQueryMsg+0x3d7) [0xecaa23]
01/17 09:02:18.946649 00000153 UTL FATAL frame:24, taosd(vnodeProcessQueryMsg+0x1ec) [0x7b7ac0]
01/17 09:02:18.946650 00000153 UTL FATAL frame:25, taosd() [0x79b45b]
01/17 09:02:18.946652 00000153 UTL FATAL frame:26, taosd() [0x125e8ef]
01/17 09:02:18.946653 00000153 UTL FATAL frame:27, /lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7ff06a933ac3]
01/17 09:02:18.946655 00000153 UTL FATAL frame:28, /lib/x86_64-linux-gnu/libc.so.6(clone+0x44) [0x7ff06a9c4814]
Segmentation fault (core dumped)

**Comment by yu285** [comment]
可以加微信 a15652223354 具体排查

**Comment by mumuwithw** [comment]
方便透露一下这个问题的原因不

> 可以加微信 a15652223354 具体排查

**Comment by pppploi8** [comment]
> 方便透露一下这个问题的原因不
> 
> > 可以加微信 a15652223354 具体排查

我忘记关闭issue了，当时作者和我说的是3.2.2.0的bug，让我自己编译github最新代码或者降级到3.2.1.0，我后来降级到3.2.1.0没问题后就没管这个issue了，没想到现在还开着

如果你也是相同版本，可以考虑升级或者降级测试，如果依然有问题，可以考虑单独开个issue或者直接加作者微信试试

**Comment by mumuwithw** [comment]
> > 方便透露一下这个问题的原因不
> > > 可以加微信 a15652223354 具体排查
> 
> 我忘记关闭issue了，当时作者和我说的是3.2.2.0的bug，让我自己编译github最新代码或者降级到3.2.1.0，我后来降级到3.2.1.0没问题后就没管这个issue了，没想到现在还开着
> 
> 如果你也是相同版本，可以考虑升级或者降级测试，如果依然有问题，可以考虑单独开个issue或者直接加作者微信试试

感谢！
