### ISSUE TITLE
docker TDengine start up failed

### ISSUE THREAD

**Issue by lhb66666666** [taosdata/TDengine#24544]
1、用docker 运行 启动 TDEngine
2、过了一会儿 TDEngine 自动停止
3、日志信息如下：
01/19 06:04:44.445033 00000096 MND stb:1.beny.pcs, start to retrieve meta
01/19 06:04:44.469575 00000150 UTL FATAL crash signal is 11
01/19 06:04:44.469604 00000150 UTL FATAL sender PID:80 cmdline:taosd
01/19 06:04:44.478416 00000150 UTL FATAL obtained 26 stack frames
01/19 06:04:44.478421 00000150 UTL FATAL frame:0, taosd(tsdbRowMergerAdd+0x2f) [0x8950f7]
01/19 06:04:44.478423 00000150 UTL FATAL frame:1, taosd() [0x85d65b]
01/19 06:04:44.478425 00000150 UTL FATAL frame:2, taosd() [0x861060]
01/19 06:04:44.478427 00000150 UTL FATAL frame:3, taosd() [0x8616dc]
01/19 06:04:44.478428 00000150 UTL FATAL frame:4, taosd() [0x862b73]
01/19 06:04:44.478430 00000150 UTL FATAL frame:5, taosd() [0x863a41]
01/19 06:04:44.478431 00000150 UTL FATAL frame:6, taosd() [0x8694e5]
01/19 06:04:44.478433 00000150 UTL FATAL frame:7, taosd() [0x86961a]
01/19 06:04:44.478434 00000150 UTL FATAL frame:8, taosd(tsdbNextDataBlock2+0x268) [0x8698af]
01/19 06:04:44.478436 00000150 UTL FATAL frame:9, taosd() [0xef977e]
01/19 06:04:44.478438 00000150 UTL FATAL frame:10, taosd() [0xef9aa9]
01/19 06:04:44.478439 00000150 UTL FATAL frame:11, taosd() [0xefa41f]
01/19 06:04:44.478441 00000150 UTL FATAL frame:12, taosd() [0xefa7d1]
01/19 06:04:44.478443 00000150 UTL FATAL frame:13, taosd(getNextBlockFromDownstreamImpl+0x1aa) [0xeef56a]
01/19 06:04:44.478445 00000150 UTL FATAL frame:14, taosd(getNextBlockFromDownstream+0x25) [0xef1f0e]
01/19 06:04:44.478447 00000150 UTL FATAL frame:15, taosd() [0xf40086]
01/19 06:04:44.478449 00000150 UTL FATAL frame:16, taosd() [0xf403b4]
01/19 06:04:44.478451 00000150 UTL FATAL frame:17, taosd(qExecTaskOpt+0x38a) [0xee7dd2]
01/19 06:04:44.478453 00000150 UTL FATAL frame:18, taosd(qwExecTask+0x172) [0xed229b]
01/19 06:04:44.478455 00000150 UTL FATAL frame:19, taosd(qwProcessQuery+0x3cd) [0xed5ef2]
01/19 06:04:44.478456 00000150 UTL FATAL frame:20, taosd(qWorkerProcessQueryMsg+0x3d7) [0xecaa23]
01/19 06:04:44.478458 00000150 UTL FATAL frame:21, taosd(vnodeProcessQueryMsg+0x1ec) [0x7b7ac0]
01/19 06:04:44.478460 00000150 UTL FATAL frame:22, taosd() [0x79b45b]
01/19 06:04:44.478462 00000150 UTL FATAL frame:23, taosd() [0x125e8ef]
01/19 06:04:44.478463 00000150 UTL FATAL frame:24, /lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7fd2c1e2bac3]
01/19 06:04:44.478465 00000150 UTL FATAL frame:25, /lib/x86_64-linux-gnu/libc.so.6(clone+0x44) [0x7fd2c1ebc814]
Segmentation fault (core dumped)
![3857b9aafba8a8ad02c168ee58b5c72](https://github.com/taosdata/TDengine/assets/34294241/34962796-ebbb-4de7-865d-257b2dbedb86)
![tdengine](https://github.com/taosdata/TDengine/assets/34294241/c9646165-6046-4fc5-959b-17e16037c850)

**Comment by yu285** [comment]
请问版本号是？

**Comment by yu285** [comment]
好的，如果还有其他疑问可以添加 a15652223354 。
