### ISSUE TITLE
table already exists in other stables

### ISSUE THREAD

**Issue by zhaopengtao-life** [taosdata/TDengine#24549]
![image](https://github.com/taosdata/TDengine/assets/44759950/680e65e1-d382-4422-8bef-8069b74b0872)
子表和数据部分数据可以正常插入，部分数据又无法插入
![image](https://github.com/taosdata/TDengine/assets/44759950/3091b057-2029-497e-9b68-08b7b6ac1311)
相同的数据库和子表，插入结果却不相同

**Comment by yu285** [comment]
可以提供下完整的语句吗？我们复现一下

**Comment by zhaopengtao-life** [comment]
insert into  _emhvbmdqaWFu._agent_alive_fc1a6c74dea141fe84d3983b13b432cf USING _emhvbmdqaWFu._fc1a6c74dea141fe84d3983b13b432cf TAGS ('')  values( 1716805653000, 'agent.alive', 'fc1a6c74dea141fe84d3983b13b432cf', 60, 1.000000, 'GAUGE') _emhvbmdqaWFu._avg_rtt_fc1a6c74dea141fe84d3983b13b432cf USING _emhvbmdqaWFu._fc1a6c74dea141fe84d3983b13b432cf TAGS ('')  values( 1716805653000, 'avg.rtt', 'fc1a6c74dea141fe84d3983b13b432cf', 60, 0.444000, 'GAUGE') _emhvbmdqaWFu._loss_packet_fc1a6c74dea141fe84d3983b13b432cf USING _emhvbmdqaWFu._fc1a6c74dea141fe84d3983b13b432cf TAGS ('')  values( 1716805653000, 'loss.packet', 'fc1a6c74dea141fe84d3983b13b432cf', 60, 0.000000, 'GAUGE') _emhvbmdqaWFu._stddev_rtt_fc1a6c74dea141fe84d3983b13b432cf USING _emhvbmdqaWFu._fc1a6c74dea141fe84d3983b13b432cf TAGS ('')  values( 1716805653000, 'stddev.rtt', 'fc1a6c74dea141fe84d3983b13b432cf', 60, 0.089000, 'GAUGE') _emhvbmdqaWFu._agent_alive_8378a5b1d6c248cd959e1eb8f05cbdf9 USING _emhvbmdqaWFu._8378a5b1d6c248cd959e1eb8f05cbdf9 TAGS ('')  values( 1716805653000, 'agent.alive', '8378a5b1d6c248cd959e1eb8f05cbdf9', 60, 1.000000, 'GAUGE') _emhvbmdqaWFu._avg_rtt_8378a5b1d6c248cd959e1eb8f05cbdf9 USING _emhvbmdqaWFu._8378a5b1d6c248cd959e1eb8f05cbdf9 TAGS ('')  values( 1716805653000, 'avg.rtt', '8378a5b1d6c248cd959e1eb8f05cbdf9', 60, 0.384000, 'GAUGE') _emhvbmdqaWFu._loss_packet_8378a5b1d6c248cd959e1eb8f05cbdf9 USING _emhvbmdqaWFu._8378a5b1d6c248cd959e1eb8f05cbdf9 TAGS ('')  values( 1716805653000, 'loss.packet', '8378a5b1d6c248cd959e1eb8f05cbdf9', 60, 0.000000, 'GAUGE') _emhvbmdqaWFu._stddev_rtt_8378a5b1d6c248cd959e1eb8f05cbdf9 USING _emhvbmdqaWFu._8378a5b1d6c248cd959e1eb8f05cbdf9 TAGS ('')  values( 1716805653000, 'stddev.rtt', '8378a5b1d6c248cd959e1eb8f05cbdf9', 60, 0.044000, 'GAUGE') _emhvbmdqaWFu._agent_alive_37199424f9994901ad433ad6b9ee375c USING _emhvbmdqaWFu._37199424f9994901ad433ad6b9ee375c TAGS ('')  values( 1716805653000, 'agent.alive', '37199424f9994901ad433ad6b9ee375c', 60, 1.000000, 'GAUGE') _emhvbmdqaWFu._avg_rtt_37199424f9994901ad433ad6b9ee375c USING _emhvbmdqaWFu._37199424f9994901ad433ad6b9ee375c TAGS ('')  values( 1716805653000, 'avg.rtt', '37199424f9994901ad433ad6b9ee375c', 60, 0.516000, 'GAUGE') _emhvbmdqaWFu._loss_packet_37199424f9994901ad433ad6b9ee375c USING _emhvbmdqaWFu._37199424f9994901ad433ad6b9ee375c TAGS ('')  values( 1716805653000, 'loss.packet', '37199424f9994901ad433ad6b9ee375c', 60, 0.000000, 'GAUGE') _emhvbmdqaWFu._stddev_rtt_37199424f9994901ad433ad6b9ee375c USING _emhvbmdqaWFu._37199424f9994901ad433ad6b9ee375c TAGS ('')  values( 1716805653000, 'stddev.rtt', '37199424f9994901ad433ad6b9ee375c', 60, 0.094000, 'GAUGE') _emhvbmdqaWFu._agent_alive_4b6bbe103afd4434946d4b65a013f768 USING _emhvbmdqaWFu._4b6bbe103afd4434946d4b65a013f768 TAGS ('')  values( 1716805653000, 'agent.alive', '4b6bbe103afd4434946d4b65a013f768', 60, 1.000000, 'GAUGE') _emhvbmdqaWFu._avg_rtt_4b6bbe103afd4434946d4b65a013f768 USING _emhvbmdqaWFu._4b6bbe103afd4434946d4b65a013f768 TAGS ('')  values( 1716805653000, 'avg.rtt', '4b6bbe103afd4434946d4b65a013f768', 60, 0.339000, 'GAUGE') _emhvbmdqaWFu._loss_packet_4b6bbe103afd4434946d4b65a013f768 USING _emhvbmdqaWFu._4b6bbe103afd4434946d4b65a013f768 TAGS ('')  values( 1716805653000, 'loss.packet', '4b6bbe103afd4434946d4b65a013f768', 60, 0.000000, 'GAUGE') _emhvbmdqaWFu._stddev_rtt_4b6bbe103afd4434946d4b65a013f768 USING _emhvbmdqaWFu._4b6bbe103afd4434946d4b65a013f768 TAGS ('')  values( 1716805653000, 'stddev.rtt', '4b6bbe103afd4434946d4b65a013f768', 60, 0.084000, 'GAUGE') _emhvbmdqaWFu._agent_alive_4e7499135dda4441ae393d5c6d3e68a3 USING _emhvbmdqaWFu._4e7499135dda4441ae393d5c6d3e68a3 TAGS ('')  values( 1716805653000, 'agent.alive', '4e7499135dda4441ae393d5c6d3e68a3', 60, 1.000000, 'GAUGE') _emhvbmdqaWFu._avg_rtt_4e7499135dda4441ae393d5c6d3e68a3 USING _emhvbmdqaWFu._4e7499135dda4441ae393d5c6d3e68a3 TAGS ('')  values( 1716805653000, 'avg.rtt', '4e7499135dda4441ae393d5c6d3e68a3', 60, 0.441000, 'GAUGE') _emhvbmdqaWFu._loss_packet_4e7499135dda4441ae393d5c6d3e68a3 USING _emhvbmdqaWFu._4e7499135dda4441ae393d5c6d3e68a3 TAGS ('')  values( 1716805653000, 'loss.packet', '4e7499135dda4441ae393d5c6d3e68a3', 60, 0.000000, 'GAUGE') _emhvbmdqaWFu._stddev_rtt_4e7499135dda4441ae393d5c6d3e68a3 USING _emhvbmdqaWFu._4e7499135dda4441ae393d5c6d3e68a3 TAGS ('')  values( 1716805653000, 'stddev.rtt', '4e7499135dda4441ae393d5c6d3e68a3', 60, 0.081000, 'GAUGE') 
2024-05-27 18:28:07.859 [GOID:0] ERROR :0 - TdengineHttpPost Failed To Exec Error [0x61d] Table already exists in other stables: sqlStr: insert into  _Z3VzaGVuZ3Rhbmc._agent_alive_36e129d2e3654e0bb94376098f97238b USING _Z3VzaGVuZ3Rhbmc._36e129d2e3654e0bb94376098f97238b TAGS ('')  values( 1716805686000, 'agent.alive', '36e129d2e3654e0bb94376098f97238b', 60, 1.000000, 'GAUGE')

**Comment by yu285** [comment]
已知问题，升级到本周末发版的 3.3.3.0 吧，如果还遇到可以加微信 a15652223354
