### ISSUE TITLE
deleted data can be showed in 3.0.1.6

### ISSUE THREAD

**Issue by ChianaCat** [taosdata/TDengine#24568]
使用delete删除数据后，使用last和first函数还能查出数据

**Comment by yu285** [comment]
麻烦提供版本号和问题截图

**Comment by ChianaCat** [comment]
![11818d6da38fbaa2f81929c7005be0a](https://github.com/taosdata/TDengine/assets/129477168/a8cb5018-ea39-4773-b46d-00a8d0dad2b4)
TDengine-server-3.0.1.6-Linux-x64

**Comment by yu285** [comment]
哦哦这个版本的问题早就修复了，这个是初始版本。和现在不兼容。如果是测试环境的话，咱们直接重建一下吧。

建议使用 3.2.1.0 版本，或者自己编译 3.0 分支最新代码，建议后者

**Comment by ChianaCat** [comment]
现在是线上环境在使用，只有更新版本这个解决方法了吗

**Comment by ChianaCat** [comment]
/var/lib/taos 这下面数据文件不动，直接升级版本可以解决这个问题吗

**Comment by yu285** [comment]
3.0.1.6 不行，但是 3.0.2.5 以后的都可以。 这个版本太早了。和现在不兼容。
