### ISSUE TITLE
使用delete语句后普通查询语句查不出数据来，语句中包含 last first 函数的时候还是可以查出数据

### ISSUE THREAD

**Issue by ChianaCat** [taosdata/TDengine#24561]
**Bug Description**

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by yu285** [comment]
1.6 版本已好多年前的版本了，已经不再维护了。 建议部署较新的 3.2.1.0 版本。如果有具体问题可以添加微信：a15652223354
