### ISSUE TITLE
some vnode/qnode/mnode(s) out of service

### ISSUE THREAD

**Issue by qxh711805** [taosdata/TDengine#24597]
报错 DB error: Fail to get table info, error: some vnode/qnode/mnode(s) out of service 
还有容器里映射出来的端口必须是 6030端口吗？

**Comment by yu285** [comment]
内外映射端口需要保持一致：
6030:6030

**Comment by swallretu** [comment]
有更新吗，同样的版本遇到同样的问题

**Comment by qxh711805** [comment]
> 有更新吗，同样的版本遇到同样的问题

没有哟，哎，不知道是不是服务端集群问题哟。照这样弄，用docker只有在那台服务器部署服务，要么就用单机版的tar包

**Comment by PilgrimWang** [comment]
我排查到的原因是 容器hosts 和 宿主机hosts 不一致导致的问题：
```
docker run -d --name tdengine --hostname <宿主机hostname> --add-host <宿主机hostname>:<宿主机IP> \
  -v /opt/app/tdengine/data/taos/dnode/data:/var/lib/taos \
  -v /opt/app/tdengine/data/taos/dnode/log:/var/log/taos \
  -p 6030:6030 -p 6041:6041 -p 6043-6049:6043-6049 -p 6043-6049:6043-6049/udp tdengine/tdengine
```
将容器hosts 和 宿主机hosts 保持一致后，应该能够正常连接了

**Comment by PilgrimWang** [comment]
> 我排查到的原因是 容器hosts 和 宿主机hosts 不一致导致的问题：
> 
> ```
> docker run -d --name tdengine --hostname <宿主机hostname> --add-host <宿主机hostname>:<宿主机IP> \
>   -v /opt/app/tdengine/data/taos/dnode/data:/var/lib/taos \
>   -v /opt/app/tdengine/data/taos/dnode/log:/var/log/taos \
>   -p 6030:6030 -p 6041:6041 -p 6043-6049:6043-6049 -p 6043-6049:6043-6049/udp tdengine/tdengine
> ```
> 
> 将容器hosts 和 宿主机hosts 保持一致后，应该能够正常连接了

![image](https://github.com/taosdata/TDengine/assets/125627305/826af8ab-af15-425d-a75f-d37210be23f0)

**Comment by Fxskyzz** [comment]
> 我排查到的原因是 容器hosts 和 宿主机hosts 不一致导致的问题：
> 
> ```
> docker run -d --name tdengine --hostname <宿主机hostname> --add-host <宿主机hostname>:<宿主机IP> \
>   -v /opt/app/tdengine/data/taos/dnode/data:/var/lib/taos \
>   -v /opt/app/tdengine/data/taos/dnode/log:/var/log/taos \
>   -p 6030:6030 -p 6041:6041 -p 6043-6049:6043-6049 -p 6043-6049:6043-6049/udp tdengine/tdengine
> ```
> 
> 将容器hosts 和 宿主机hosts 保持一致后，应该能够正常连接了

这样做确实可以，但是前提是客户端和服务端都必须在同一台服务器上吧

**Comment by PilgrimWang** [comment]
> > 我排查到的原因是 容器hosts 和 宿主机hosts 不一致导致的问题：
> > ```
> > docker run -d --name tdengine --hostname <宿主机hostname> --add-host <宿主机hostname>:<宿主机IP> \
> >   -v /opt/app/tdengine/data/taos/dnode/data:/var/lib/taos \
> >   -v /opt/app/tdengine/data/taos/dnode/log:/var/log/taos \
> >   -p 6030:6030 -p 6041:6041 -p 6043-6049:6043-6049 -p 6043-6049:6043-6049/udp tdengine/tdengine
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 将容器hosts 和 宿主机hosts 保持一致后，应该能够正常连接了
> 
> 这样做确实可以，但是前提是客户端和服务端都必须在同一台服务器上吧

不需要吧，我当时测试时客户端和服务端并没有在一台机器上，客户端配置文件里加上服务端地址就可以了
![image](https://github.com/taosdata/TDengine/assets/125627305/f9e13e3c-77a1-4090-93aa-83f3d84eae6d)

**Comment by Fxskyzz** [comment]
> > > 我排查到的原因是 容器hosts 和 宿主机hosts 不一致导致的问题：
> > > ```
> > > docker run -d --name tdengine --hostname <宿主机hostname> --add-host <宿主机hostname>:<宿主机IP> \
> > >   -v /opt/app/tdengine/data/taos/dnode/data:/var/lib/taos \
> > >   -v /opt/app/tdengine/data/taos/dnode/log:/var/log/taos \
> > >   -p 6030:6030 -p 6041:6041 -p 6043-6049:6043-6049 -p 6043-6049:6043-6049/udp tdengine/tdengine
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 将容器hosts 和 宿主机hosts 保持一致后，应该能够正常连接了
> > 
> > 
> > 这样做确实可以，但是前提是客户端和服务端都必须在同一台服务器上吧
> 
> 不需要吧，我当时测试时客户端和服务端并没有在一台机器上，客户端配置文件里加上服务端地址就可以了 ![image](https://private-user-images.githubusercontent.com/125627305/334615639-f9e13e3c-77a1-4090-93aa-83f3d84eae6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5OTM3NjcsIm5iZiI6MTcxNjk5MzQ2NywicGF0aCI6Ii8xMjU2MjczMDUvMzM0NjE1NjM5LWY5ZTEzZTNjLTc3YTEtNDA5MC05M2FhLTgzZjNkODRlYWU2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQxNDM3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMWRhZjUwODllMTJkNTg1MDc1YTQ0ODA0ODBmMWJhNDdmNWRjMzA4NjdmZDc0YWJmOWJhMzM2YzVkYTJjZjU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5nbymbYKn4c3XjFCV6jz79f7JkjkA0EcldmRwxpOfMI)

唉，有时候可以，有时候又不行。都是一样的环境命令。。

**Comment by Fxskyzz** [comment]
> > > 我排查到的原因是 容器hosts 和 宿主机hosts 不一致导致的问题：
> > > ```
> > > docker run -d --name tdengine --hostname <宿主机hostname> --add-host <宿主机hostname>:<宿主机IP> \
> > >   -v /opt/app/tdengine/data/taos/dnode/data:/var/lib/taos \
> > >   -v /opt/app/tdengine/data/taos/dnode/log:/var/log/taos \
> > >   -p 6030:6030 -p 6041:6041 -p 6043-6049:6043-6049 -p 6043-6049:6043-6049/udp tdengine/tdengine
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 将容器hosts 和 宿主机hosts 保持一致后，应该能够正常连接了
> > 
> > 
> > 这样做确实可以，但是前提是客户端和服务端都必须在同一台服务器上吧
> 
> 不需要吧，我当时测试时客户端和服务端并没有在一台机器上，客户端配置文件里加上服务端地址就可以了 ![image](https://private-user-images.githubusercontent.com/125627305/334615639-f9e13e3c-77a1-4090-93aa-83f3d84eae6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5OTQwOTgsIm5iZiI6MTcxNjk5Mzc5OCwicGF0aCI6Ii8xMjU2MjczMDUvMzM0NjE1NjM5LWY5ZTEzZTNjLTc3YTEtNDA5MC05M2FhLTgzZjNkODRlYWU2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQxNDQzMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDcxODIwYTZmZTQyZjAwZGI4YjI2YzM1OTA2NzFlZmIwNWRiMmM0OTkyZTNmY2M1NGM2OGI2MDM4OWU0NWI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vUW9M5fP1Ma8tvesgHYGbaiIbdQeIy6WVzX2I21krRY)

<img width="1179" alt="image" src="https://github.com/taosdata/TDengine/assets/51671651/207c930e-1903-4f3a-bc73-4e3934659262">
唉，有时候可以，有时候又不行。都是一样的版本。。。

**Comment by sharooque7** [comment]
I recently encountered the same issue while working with the TDengine Kafka Connector, where the packets were being blocked by the firewall. After diagnosing the problem, I found that adjusting the firewall settings resolved the connectivity issue.

**Comment by myhubo** [comment]
我不是通过docker部署的，也有这个问题，连接正常，执行sql就报这个错误

**Comment by setruth** [comment]
> > 我排查到的原因是 容器hosts 和 宿主机hosts 不一致导致的问题：
> > ```
> > docker run -d --name tdengine --hostname <宿主机hostname> --add-host <宿主机hostname>:<宿主机IP> \
> >   -v /opt/app/tdengine/data/taos/dnode/data:/var/lib/taos \
> >   -v /opt/app/tdengine/data/taos/dnode/log:/var/log/taos \
> >   -p 6030:6030 -p 6041:6041 -p 6043-6049:6043-6049 -p 6043-6049:6043-6049/udp tdengine/tdengine
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 将容器hosts 和 宿主机hosts 保持一致后，应该能够正常连接了
> 
> ![image](https://github.com/taosdata/TDengine/assets/125627305/826af8ab-af15-425d-a75f-d37210be23f0)

但是如果自己测试得环境下做IP绑定得话岂不是每次ip变化都要改 有办法一次性解决嘛
