### ISSUE TITLE
python package install was failed

### ISSUE THREAD

**Issue by Laurel-rao** [taosdata/TDengine#246]
**I found two error when i was installed connector of python.**
### Error 1:
- The error show installation path `pip install src/connector/python/python3/` with documentation from link `https://www.taosdata.com/en/documentation/connector/#Python-Connector` .
- But the actually path is `pip install src/connector/python/windows/python3/` from github project.
![image](https://user-images.githubusercontent.com/42195541/62207407-9c60d900-b3c6-11e9-9508-ed1563130cca.png)
### Error 2:
- The installation with python was failedwhen i use `pip install ` that shows successfully installed.
- But i use the command `import taos`, it shows error below.

![image](https://user-images.githubusercontent.com/42195541/62207780-9a4b4a00-b3c7-11e9-80d9-65bfae54b189.png)

**Comment by langxj** [comment]
我也是这个问题，python3 pip能安装成功，但import taos说找不到模块。python2.7能安装成功，但有个报错，错误如下：
![image](https://user-images.githubusercontent.com/7477494/62216717-df797700-b3db-11e9-93db-924145e451fd.png)
![image](https://user-images.githubusercontent.com/7477494/62216796-08017100-b3dc-11e9-83a9-5eaca544ee6c.png)

**Comment by langxj** [comment]
linux no error!

**Comment by fangpanpan** [comment]
For error 1, the installation path to be chosen depends on what system under which your client will be installed. If you want to install the python client under windows, then the installation path is "src/connector/python/windows/python3/". Otherwise, the you will install the python client under linux. 

For error2, can you find the taos.dll under "C:\TDengine\driver"?

**Comment by ZSCLM** [comment]
> For error 1, the installation path to be chosen depends on what system under which your client will be installed. If you want to install the python client under windows, then the installation path is "src/connector/python/windows/python3/". Otherwise, the you will install the python client under linux.
> 
> For error2, can you find the taos.dll under "C:\TDengine\driver"?

我有这个文件，还是报错：
![image](https://user-images.githubusercontent.com/5078654/62275705-18b1f580-b475-11e9-91ee-04608af7d834.png)
![image](https://user-images.githubusercontent.com/5078654/62275728-27001180-b475-11e9-8fcc-534c94e6e20e.png)

**Comment by fangpanpan** [comment]
Have you also copied the tao.dll to "C:\windows\system32"?

**Comment by ZSCLM** [comment]
After I copied the "taos.dll" to "C:\Windows\System32", I tried again and the error still exists, and I also restarted my "cmd"..
![image](https://user-images.githubusercontent.com/5078654/62277223-49475e80-b478-11e9-92f1-634af5750c4d.png)
![image](https://user-images.githubusercontent.com/5078654/62277324-83186500-b478-11e9-8547-45d8b2b37f4e.png)

**Comment by fangpanpan** [comment]
Your windows is 32bit and our tao.dll is compiled on 64bit system.

**Comment by ZSCLM** [comment]
> Your windows is 32bit and our tao.dll is compiled on 64bit system.

Great ! That's the problem..

**Comment by langxj** [comment]
> Your windows is 32bit and our tao.dll is compiled on 64bit system.

My windows is 64bit, the error still exists.
![image](https://user-images.githubusercontent.com/7477494/62337425-2912b080-b507-11e9-8ebe-5ba7a0d1e28b.png)
![image](https://user-images.githubusercontent.com/7477494/62337435-33cd4580-b507-11e9-99ca-ce55215499fa.png)
![image](https://user-images.githubusercontent.com/7477494/62337450-434c8e80-b507-11e9-9273-9a256d1792f8.png)

**Comment by fangpanpan** [comment]
I'm confused about your statement "The installation with python was failed" in error 2. Have you succeed after entering "pip install python3\"? 

Another question, have you copied "tao.dll" to  "C:\Windows\System32\" and "C:\TDengine\driver\"?

**Comment by fangpanpan** [comment]
> > Your windows is 32bit and our tao.dll is compiled on 64bit system.
> 
> My windows is 64bit, the error still exists.
> ![image](https://user-images.githubusercontent.com/7477494/62337425-2912b080-b507-11e9-8ebe-5ba7a0d1e28b.png)
> ![image](https://user-images.githubusercontent.com/7477494/62337435-33cd4580-b507-11e9-99ca-ce55215499fa.png)
> ![image](https://user-images.githubusercontent.com/7477494/62337450-434c8e80-b507-11e9-9273-9a256d1792f8.png)

I'm confused about your statement "The installation with python was failed" in error 2. Have you succeed after entering "pip install python3"?

Another question, have you copied "tao.dll" to "C:\Windows\System32" and "C:\TDengine\driver"?

**Comment by ZSCLM** [comment]
> > Your windows is 32bit and our tao.dll is compiled on 64bit system.
> 
> My windows is 64bit, the error still exists.
> ![image](https://user-images.githubusercontent.com/7477494/62337425-2912b080-b507-11e9-8ebe-5ba7a0d1e28b.png)
> ![image](https://user-images.githubusercontent.com/7477494/62337435-33cd4580-b507-11e9-99ca-ce55215499fa.png)
> ![image](https://user-images.githubusercontent.com/7477494/62337450-434c8e80-b507-11e9-9273-9a256d1792f8.png)

I think there may be two possibilities：
> * First：Your source code is not update to date, I updated my code yesterday and reinstalld the lib, and then the problem was solved. 
> * Second：You've installed the wrong lib. You should use the command "pip install /src/connector/python/windows/python3" to install the lib used under windows system. Now your code is trying to load the lib "libtaos.so" which seems to be used under Linux system..

**Comment by langxj** [comment]
> > > Your windows is 32bit and our tao.dll is compiled on 64bit system.
> > 
> > 
> > My windows is 64bit, the error still exists.
> > ![image](https://user-images.githubusercontent.com/7477494/62337425-2912b080-b507-11e9-8ebe-5ba7a0d1e28b.png)
> > ![image](https://user-images.githubusercontent.com/7477494/62337435-33cd4580-b507-11e9-99ca-ce55215499fa.png)
> > ![image](https://user-images.githubusercontent.com/7477494/62337450-434c8e80-b507-11e9-9273-9a256d1792f8.png)
> 
> I think there may be two possibilities：
> 
> > * First：Your source code is not update to date, I updated my code yesterday and reinstalld the lib, and then the problem was solved.
> > * Second：You've installed the wrong lib. You should use the command "pip install /src/connector/python/windows/python3" to install the lib used under windows system. Now your code is trying to load the lib "libtaos.so" which seems to be used under Linux system..

github lastest code is ok!
![image](https://user-images.githubusercontent.com/7477494/62372119-32cd0000-b569-11e9-86f0-d5e7fb544302.png)

**Comment by langxj** [comment]
> **I found two error when i was installed connector of python.**
> 
> ### Error 1:
> * The error show installation path `pip install src/connector/python/python3/` with documentation from link `https://www.taosdata.com/en/documentation/connector/#Python-Connector` .
> * But the actually path is `pip install src/connector/python/windows/python3/` from github project.
>   ![image](https://user-images.githubusercontent.com/42195541/62207407-9c60d900-b3c6-11e9-9508-ed1563130cca.png)
> 
> ### Error 2:
> * The installation with python was failedwhen i use `pip install ` that shows successfully installed.
> * But i use the command `import taos`, it shows error below.
> 
> ![image](https://user-images.githubusercontent.com/42195541/62207780-9a4b4a00-b3c7-11e9-80d9-65bfae54b189.png)

update github lastest code, run "pip install src\connector\python\windows\python3"

**Comment by hong6914** [comment]
From the screenshot seems that it's a bug in \taos\cinterface.py, that it tries to load a Linux ELF file (libtaos.so) instead of a Windows PE (libtaos.dll --- unless ctypes.CDLL() does the name-conversion job properly).
https://user-images.githubusercontent.com/7477494/62337425-2912b080-b507-11e9-8ebe-5ba7a0d1e28b.png

**Comment by hong6914** [comment]
Besides, you guys better install the packages and debug your stuff in a python's virtual environment, and avoid the pollution of the packages over time. There are a few virtual environments and I'd prefer virtualenv :-)

(sudo --- Linux) pip install virtualenv
cd <your src dir>
virtualenv <your_vent_name>
cd <your_vent_name>
source bin/activate   (---Linux)  or    bin\activate (---Windows)
pip install <whatever packages you want>
mkdir src
then put your code in it and play with it

Also are you using PyCharm? The community edition is free even in office. The best Python IDE on this planet. Try it :-)

Side note: from the screenshot above --- C:\python36\lib\site-packages\ is the global place to store the packages on your machine. Be careful installing stuff to here

**Comment by treemp3** [comment]
我在Windows10上也pip成功了，报同样的错误，只好把代码放到Linux上去运行。
taos.dll不是在开发么？https://github.com/taosdata/TDengine/issues/89

**Comment by Lao-Zhong** [comment]
我在Windows10上也pip成功了，报同样的错误
![1](https://user-images.githubusercontent.com/39207755/84628268-e4271b00-af1a-11ea-820d-fc56ab8562c8.png)
![2](https://user-images.githubusercontent.com/39207755/84628274-e5f0de80-af1a-11ea-9866-7e181c5d8bb9.png)
![3](https://user-images.githubusercontent.com/39207755/84628277-e8ebcf00-af1a-11ea-846c-b67f9b036069.png)

**Comment by Lao-Zhong** [comment]
> > **我在安装python连接器时发现了两个错误。**
> > ### 错误1：
> > 
> > * 错误显示安装路径`pip install src/connector/python/python3/`以及link中的文档`https://www.taosdata.com/en/documentation/connector/#Python-Connector`。
> > * 但是实际路径`pip install src/connector/python/windows/python3/`来自github项目。
> >   ![图片](https://user-images.githubusercontent.com/42195541/62207407-9c60d900-b3c6-11e9-9508-ed1563130cca.png)
> > 
> > ### 错误2：
> > 
> > * 当我使用python进行安装时失败`pip install `，表明安装成功。
> > * 但是我使用命令`import taos`，它显示下面的错误。
> > 
> > ![图片](https://user-images.githubusercontent.com/42195541/62207780-9a4b4a00-b3c7-11e9-80d9-65bfae54b189.png)
> 
> 更新github最新代码，运行“ pip install src \ connector \ python \ windows \ python3”

同样的错误，请问您解决这个问题了么

**Comment by Laurel-rao** [comment]
> > > **我在安装python连接器时发现了两个错误。**
> > > ### 错误1：
> > > 
> > > * 错误显示安装路径`pip install src/connector/python/python3/`以及link中的文档`https://www.taosdata.com/en/documentation/connector/#Python-Connector`。
> > > * 但是实际路径`pip install src/connector/python/windows/python3/`来自github项目。
> > >   ![图片](https://user-images.githubusercontent.com/42195541/62207407-9c60d900-b3c6-11e9-9508-ed1563130cca.png)
> > > 
> > > ### 错误2：
> > > 
> > > * 当我使用python进行安装时失败`pip install `，表明安装成功。
> > > * 但是我使用命令`import taos`，它显示下面的错误。
> > > 
> > > ![图片](https://user-images.githubusercontent.com/42195541/62207780-9a4b4a00-b3c7-11e9-80d9-65bfae54b189.png)
> > 
> > 
> > 更新github最新代码，运行“ pip install src \ connector \ python \ windows \ python3”
> 
> 同样的错误，请问您解决这个问题了么

It shows the same error.
```
>>> import taos
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\15627\AppData\Local\Programs\Python\Python36\lib\site-packages\taos\__init__.py", line 2, in <module>
    from .connection import TDengineConnection
  File "C:\Users\15627\AppData\Local\Programs\Python\Python36\lib\site-packages\taos\connection.py", line 1, in <module>
    from .cursor import TDengineCursor
  File "C:\Users\15627\AppData\Local\Programs\Python\Python36\lib\site-packages\taos\cursor.py", line 1, in <module>
    from .cinterface import CTaosInterface
  File "C:\Users\15627\AppData\Local\Programs\Python\Python36\lib\site-packages\taos\cinterface.py", line 138, in <module>
    class CTaosInterface(object):
  File "C:\Users\15627\AppData\Local\Programs\Python\Python36\lib\site-packages\taos\cinterface.py", line 140, in CTaosInterface
    libtaos = ctypes.windll.LoadLibrary('taos')
  File "C:\Users\15627\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\15627\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。
```

**Comment by treemp3** [comment]
这个解决方法很简单啊，如果是Windows的话，把taos.dll文件复制一下，在system32和SysWOW64都放一份。
Linux上面也是一样的，在/usr/lib和/usr/lib64下面都放一份taos.so，大概是这样的，时间久了记不太清了。

**Comment by Lao-Zhong** [comment]
> 这个解决方法很简单啊，如果是Windows的话，把taos.dll文件复制一下，在system32和SysWOW64都放一份。
> Linux上面也是一样的，在/usr/lib和/usr/lib64下面都放一份taos.so，大概是这样的，时间久了记不太清了。

非常感谢，可以了

**Comment by hong6914** [comment]
1。把自己的DLL随意放到系统目录下，不是解决问题的正确姿势。
2。软件以后升级，这种方式最容易忘了更新，调试起来够你喝一壶的 :-)
3。尽量把软件包(DLL或者.so)放在一起

**Comment by hong6914** [comment]
To the author: 
Do you wanna do this?

import platform

TAO_LIB = 'taos.dll' if platform.system() == 'Windows' else 'taos.so'
tao_dll_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), TAO_LIB)

# continue call the exported functions you want to expose

**Comment by hong6914** [comment]
github does not handle it right --- the file( ) above should be
_ _ file ( ) _ _
