### ISSUE TITLE
TDengine ERROR (80000014): Database not ready

### ISSUE THREAD

**Issue by daodol** [taosdata/TDengine#24631]
系统正常运行突然宕机，日志报错TDengine ERROR (80000014): Database not ready
期间无任何人工操作。
版本2.4.7
<img width="704" alt="企业微信截图_17062262782642" src="https://github.com/taosdata/TDengine/assets/16305190/e5794e59-4c8e-4652-aa30-1f1c10473520">
![image](https://github.com/taosdata/TDengine/assets/16305190/dc56a5bd-ecc6-443c-94a4-50d98ff842d0)
![image](https://github.com/taosdata/TDengine/assets/16305190/d95a6b77-e06f-472e-a2f7-56777ef3ffe4)

**Comment by yu285** [comment]
2.4 我们已经不维护了，可参考 https://www.taosdata.com/tdengine-engineering/17753.html 做下数据迁移

**Comment by yu285** [comment]
迁移后：https://www.taosdata.com/tdengine-engineering/21550.html 可以参考此文更好入门。
