### ISSUE TITLE
执行 show tables可以看到表，但是执行 select 语句会报DB error: Fail to get table info, error: Table does not exist

### ISSUE THREAD

**Issue by ych-szh** [taosdata/TDengine#24649]
**Bug Description**
在命令行中使用向超级表插入数据的方式，对一个全新的数据库（定义了超级表）插入数据，命令行显示插入成功，同时 show tables 可以看到子表，但是执行 select * from 子表会报 DB error: Fail to get table info, error: Table does not exist。

**To Reproduce**
1. create database test precision 'ms' cachemodel 'last_value' duration 10d keep 36500;
2. CREATE STABLE s_sensor (ts TIMESTAMP, sensor_value DOUBLE, value_state INT) TAGS (sensor_name VARCHAR(64));
3.  INSERT INTO s_sensor(tbname, ts, sensor_value, value_state) 
    > VALUES ('c1_DDD_CX_IED_JV888', '2023-05-03 18:23:48', 0.6074005494502546, 1) 
    > ('c1_CCC_AC_BIR_IM123', '2021-09-20 19:36:35', 0.06996487399278939, 1);
4. show tables;
5. select * from c1_CCC_AC_BIR_IM123;

**Screenshots**
<img width="796" alt="image" src="https://github.com/taosdata/TDengine/assets/8725490/3d1d647e-9ea9-4786-b60b-96942f2f4596">

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS (GNU/Linux 5.15.0-91-generic x86_64)
 - Memory, CPU, current Disk Space  16g AMD Ryzen 7 5800H 1TB
 - TDengine Version 3.2.2.0(DOCKER)

**Comment by NephilimJaeger** [comment]
I'm having the same issue. The table name appears when I make a SELECT TBNAME from stable but when I query directly at one subtable, it show the "Table does not exist" error. 

<img width="765" alt="Captura de Tela 2024-01-31 às 12 40 44" src="https://github.com/taosdata/TDengine/assets/79484746/dbb4a864-abb8-48c1-a983-0dd54877ef94">

<img width="769" alt="image" src="https://github.com/taosdata/TDengine/assets/79484746/b17c2cc0-df9a-4960-9df9-62ba9558f9ea">

**Comment by jiurenm** [comment]
> I'm having the same issue. The table name appears when I make a SELECT TBNAME from stable but when I query directly at one subtable, it show the "Table does not exist" error.
> 
> <img alt="Captura de Tela 2024-01-31 às 12 40 44" width="765" src="https://private-user-images.githubusercontent.com/79484746/301219440-dbb4a864-abb8-48c1-a983-0dd54877ef94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzcxODgsIm5iZiI6MTcwNjc3Njg4OCwicGF0aCI6Ii83OTQ4NDc0Ni8zMDEyMTk0NDAtZGJiNGE4NjQtYWJiOC00OGMxLWE5ODMtMGRkNTQ4NzdlZjk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA4NDEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3OTI2NzU2ZDA4YTJjZjU5M2QyNzNkMmE1YzcyODVlYjRlM2NmMmI4MWQxNGE5ODgzMDJhZGI2MWM3YWExZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bs6mThQuebsIF62pr3B2qQvRUHaHP19l8djkNnrg9NY"> <img alt="image" width="769" src="https://private-user-images.githubusercontent.com/79484746/301219617-b17c2cc0-df9a-4960-9df9-62ba9558f9ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzcxODgsIm5iZiI6MTcwNjc3Njg4OCwicGF0aCI6Ii83OTQ4NDc0Ni8zMDEyMTk2MTctYjE3YzJjYzAtZGY5YS00OTYwLTlkZjktNjJiYTk1NThmOWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA4NDEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMDc1YTllYjllOThkYTU0YzUxODhmOWYxMzhiYmYwYTAyYWQzN2QyZDZiN2JlZTFlNjQyMWU4ZDE5MjczNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PX6SbFcj4AyrGEMw5Q0_-BeZihZ9wD7g6AVGsnGUt-0">
> VERSION: 3.2.0.0(Kubernetes)

Use backticks to enclose the table name, such as ```select * from `your_subtable_name`;```

**Comment by zhujiaxin** [comment]
> > I'm having the same issue. The table name appears when I make a SELECT TBNAME from stable but when I query directly at one subtable, it show the "Table does not exist" error.
> > <img alt="Captura de Tela 2024-01-31 às 12 40 44" width="765" src="https://private-user-images.githubusercontent.com/79484746/301219440-dbb4a864-abb8-48c1-a983-0dd54877ef94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzcxODgsIm5iZiI6MTcwNjc3Njg4OCwicGF0aCI6Ii83OTQ4NDc0Ni8zMDEyMTk0NDAtZGJiNGE4NjQtYWJiOC00OGMxLWE5ODMtMGRkNTQ4NzdlZjk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA4NDEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3OTI2NzU2ZDA4YTJjZjU5M2QyNzNkMmE1YzcyODVlYjRlM2NmMmI4MWQxNGE5ODgzMDJhZGI2MWM3YWExZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bs6mThQuebsIF62pr3B2qQvRUHaHP19l8djkNnrg9NY"> <img alt="image" width="769" src="https://private-user-images.githubusercontent.com/79484746/301219617-b17c2cc0-df9a-4960-9df9-62ba9558f9ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzcxODgsIm5iZiI6MTcwNjc3Njg4OCwicGF0aCI6Ii83OTQ4NDc0Ni8zMDEyMTk2MTctYjE3YzJjYzAtZGY5YS00OTYwLTlkZjktNjJiYTk1NThmOWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA4NDEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMDc1YTllYjllOThkYTU0YzUxODhmOWYxMzhiYmYwYTAyYWQzN2QyZDZiN2JlZTFlNjQyMWU4ZDE5MjczNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PX6SbFcj4AyrGEMw5Q0_-BeZihZ9wD7g6AVGsnGUt-0">
> > VERSION: 3.2.0.0(Kubernetes)
> 
> Use backticks to enclose the table name, such as `` select * from `your_subtable_name`; ``

当表名为大写的时候直接使用原生查询的确是会出错的，如果使用taos客户端创建的表会自动转为小写，推荐使用这个方法。可以使用超级表过滤表名的方式进行查询。`select * from stable_name where tbname = 'your_subtable_name';`
