### ISSUE TITLE
Java Mybatis 原生连接 Insert value 内使用 NOW()函数问题

### ISSUE THREAD

**Issue by unlock-lee** [taosdata/TDengine#24672]
Java 原生连接 Insert 操作VALUE内支持函数吗？

#手动执行正常SQL
INSERT INTO log_t26507_1 USING log TAGS (26507, 1) VALUES (NOW(), NOW(), "日志");
#无法执行注解语句  TDengine ERROR (0x80000216): syntax error near '测试)' (invalid data or symbol)
@Insert("INSERT INTO log_t${tid}_${groupId} USING log TAGS (${tid}, ${groupId}) VALUES (NOW(), #{logTime}, #{logContent})")

#手动执行正常SQL
SELECT NOW();
#正常执行注解
@Select("SELECT NOW()")

使用的版本
mybatis-spring 3.0.3
tdegine 3.2.2.0
jdbcdriver 3.2.7

**Comment by unlock-lee** [comment]
![image](https://github.com/taosdata/TDengine/assets/14037032/e8a4a5f0-8a06-46f0-b55f-eef976c2880b)
我也无法在官网docs检索到0x80000216相关的信息

**Comment by junmowen** [comment]
怎么解决的你这边

**Comment by unlock-lee** [comment]
> 怎么解决的你这边

业务代码上赋值时间戳。放弃jdbc直接使用函数。
