### ISSUE TITLE
the "system" collected by telegraf  can be used in TDengine

### ISSUE THREAD

**Issue by Joe-DoubleV** [taosdata/TDengine#24673]
system字段报错
用sql 查询 telegraf 插件上传的数据，所有关于“system”这个单词的语句都会报错，比如 describe system; 但是其他的比如"cpu"等都是OK的。

taos> describe system;
DB error: syntax error near "system;" (0.000169s)

使用版本
tdegine 3.2.2.0

**Comment by Joe-DoubleV** [comment]
还有 host 这个单词

**Comment by yu285** [comment]
please use `system` and `host` to avoid this .

**Comment by yu285** [comment]
请使用反引号包裹system
