### ISSUE TITLE
DB error: failed to connect to server

### ISSUE THREAD

**Issue by liujinsheng** [taosdata/TDengine#2469]
select count(*) from s_gps;

DB error: failed to connect to server

数据量大的时候，数据库会崩掉

**Comment by Aries-Lee1991** [comment]
现在的信息太少，无法判断问题。
请补充版本信息、具体场景描述以及日志信息，以便于我们这边排查复现，谢谢。

**Comment by liujinsheng** [comment]
版本1.6.5.9 。数据库存入设备位置点  ，里边有千万测试数据。select count（*）位置超级表 ，数据库直接挂掉。

**Comment by Aries-Lee1991** [comment]
@liuyq-617 麻烦刘工跟踪下这个问题。

**Comment by Aries-Lee1991** [comment]
追加：s_gps超级表存千万的设备位置数据。
warning是报警类型，一共32种报警，长度为32字符串，报警为1不报警为0。
业务需求会根据vid、pid等tag，groupby统计数量。
for循环以下sql语句，like会从第一位到32位赋1。
select count(ts) as count from db.s_gps where warning like '1___________________' and ts>'2020-06-23 00:00:00' and ts < '2020-06-23 23:59:59' group by vid ,client_code , pid ,eid ,oid ,admdivcode ,industry_id
请求频繁，数据库响应失败或者数据库直接崩掉。

**Comment by liuyq-617** [comment]
把服务端和客户端的debugFlag 改为135，然后把日志贴出来吧

**Comment by liujinsheng** [comment]
07/06 16:02:52.734850 22854 7f3881406700 ERROR MND vgroup:50 is not there, but associated with vnode 47
07/06 16:02:52.734856 22854 7f3881406700 ERROR MND vgroup:59 is not there, but associated with vnode 54
07/06 16:02:52.734862 22854 7f3881406700 ERROR MND vgroup:69 is not there, but associated with vnode 63
07/06 16:02:53.739970 22854 7f3881406700 ERROR MND vgroup:47 is not there, but associated with vnode 43
07/06 16:02:53.740008 22854 7f3881406700 ERROR MND vgroup:49 is not there, but associated with vnode 46
07/06 16:02:53.740015 22854 7f3881406700 ERROR MND vgroup:50 is not there, but associated with vnode 47
07/06 16:02:53.740021 22854 7f3881406700 ERROR MND vgroup:59 is not there, but associated with vnode 54
07/06 16:02:53.740027 22854 7f3881406700 ERROR MND vgroup:69 is not there, but associated with vnode 63
07/06 16:02:54.745029 22854 7f3881406700 ERROR MND vgroup:47 is not there, but associated with vnode 43
07/06 16:02:54.745068 22854 7f3881406700 ERROR MND vgroup:49 is not there, but associated with vnode 46
07/06 16:02:54.745075 22854 7f3881406700 ERROR MND vgroup:50 is not there, but associated with vnode 47


这是taosdlog的日志，在没有存入和查询的时候，自己一直再刷这个日志，我们的问题会不会和这个有关系

**Comment by liuyq-617** [comment]
您之前做了什么操作啊？这个肯定是有问题啊

**Comment by liujinsheng** [comment]
什么操作引起的，具体也不清楚。删过子表或者更新了下子表的名称。这个问题大体什么引起的？怎么解决呢？

**Comment by liuyq-617** [comment]
是不是升级过版本啊？之前的版本里有这个bug

**Comment by liujinsheng** [comment]
之前是1.6.4.3，后来使用1.6.5.9，现在是1.6.6.0。旧版本有这个问题，新版本应该没事了吧。还是说直接升级有问题啊，需要把数据清空。

**Comment by liuyq-617** [comment]
应该是您在旧版本的时候就有问题了，然后只是升级版本，之前数据的bug就遗留了下来。推荐您把原数据导出，然后清空数据，重新安装。
