### ISSUE TITLE
卸载tdengine-1.6.0.0版本，重装tdengine-1.6.1.2版本 taos身份验证失败

### ISSUE THREAD

**Issue by limitimes** [taosdata/TDengine#247]
卸载旧的1.6.0.0版本
![image](https://user-images.githubusercontent.com/680991/62211903-472ac480-b3d2-11e9-9c07-989aa3e40fa8.png)
安装新的1.6.1.2版本
![image](https://user-images.githubusercontent.com/680991/62211962-6aee0a80-b3d2-11e9-920e-1832a53d4187.png)
![image](https://user-images.githubusercontent.com/680991/62212019-80633480-b3d2-11e9-9fdd-27a024beb1e3.png)
身份验证失败?

**Comment by limitimes** [comment]
> 卸载旧的1.6.0.0版本
> ![image](https://user-images.githubusercontent.com/680991/62211903-472ac480-b3d2-11e9-9c07-989aa3e40fa8.png)
> 安装新的1.6.1.2版本
> ![image](https://user-images.githubusercontent.com/680991/62211962-6aee0a80-b3d2-11e9-920e-1832a53d4187.png)
> ![image](https://user-images.githubusercontent.com/680991/62212019-80633480-b3d2-11e9-9fdd-27a024beb1e3.png)
> 身份验证失败?

旧的数据也已经删除。

**Comment by guanshengliang** [comment]
需要把/var/lib/taos文件夹的内容全部删除

**Comment by guanshengliang** [comment]
停止服务，删除掉，再启动服务

**Comment by limitimes** [comment]
> 停止服务，删除掉，再启动服务

原来是在taos.cfg中配置的密码无效，还是默认的密码？

**Comment by guanshengliang** [comment]
删除之后，系统恢复为默认密码taosdata。

**Comment by limitimes** [comment]
> 删除之后，系统恢复为默认密码taosdata。

已经重新配置taos.cfg，并且已经重启服务，但配置的密码不生效。

**Comment by guanshengliang** [comment]
不知道配置的密码是什么意思
把配置文件恢复成原样或者直接删除，试试

**Comment by limitimes** [comment]
另外1.6.0.0版本时用taosdump导出的数据有问题，不能导入到1.6.1.2版本，显示SQL语法有误
![image](https://user-images.githubusercontent.com/680991/62213098-be615800-b3d4-11e9-96bf-bfcbb57e0c41.png)

**Comment by limitimes** [comment]
> 不知道配置的密码是什么意思 把配置文件恢复成原样或者直接删除，试试

![image](https://user-images.githubusercontent.com/680991/62213113-cb7e4700-b3d4-11e9-8744-0cdbe69b8842.png)

**Comment by guanshengliang** [comment]
已经把数据库文件都删除，等于全新的数据库，用您配置文件的密码自然登录失败。
配置文件中的密码信息，只是指定登录数据库时使用哪个密码，并不是修改了数据库的密码

**Comment by plum-lihui** [comment]
@limitimes   您能将导出的数据文件发给我看看吗？ 我的邮箱：huili@taosdata.com， 我来分析一下。
多谢！

**Comment by plum-lihui** [comment]
是taosdump的bug，导出的那个建子表的语句有点问题：CREATE TABLE IF NOT EXISTS k30192610001 USING device TAGS ('K3019261account', 709394, 15645644brand, 2, 480, 0)
其中第三个tag的值多了brand，所以导入的时候就出错了。
这个我们解决一下。
