### ISSUE TITLE
taosOpenTcpServerSocket listen失败没有关闭socket

### ISSUE THREAD

**Issue by Remainfox** [taosdata/TDengine#2470]
int taosOpenTcpServerSocket(uint32_t ip, uint16_t port) {
  struct sockaddr_in serverAdd;
  int                sockFd;
  int                reuse;

  uTrace("open tcp server socket:0x%x:%hu", ip, port);

  bzero((char *)&serverAdd, sizeof(serverAdd));
  serverAdd.sin_family = AF_INET;
  serverAdd.sin_addr.s_addr = ip;
  serverAdd.sin_port = (uint16_t)htons(port);

  if ((sockFd = (int)socket(AF_INET, SOCK_STREAM, IPPROTO_TCP)) < 0) {
    uError("failed to open TCP socket: %d (%s)", errno, strerror(errno));
    return -1;
  }

  /* set REUSEADDR option, so the portnumber can be re-used */
  reuse = 1;
  if (taosSetSockOpt(sockFd, SOL_SOCKET, SO_REUSEADDR, (void *)&reuse, sizeof(reuse)) < 0) {
    uError("setsockopt SO_REUSEADDR failed: %d (%s)", errno, strerror(errno));
    close(sockFd);
    return -1;
  };

  /* bind socket to server address */
  if (bind(sockFd, (struct sockaddr *)&serverAdd, sizeof(serverAdd)) < 0) {
    uError("bind tcp server socket failed, 0x%x:%hu(%s)", ip, port, strerror(errno));
    close(sockFd);
    return -1;
  }

  if (taosKeepTcpAlive(sockFd) < 0) return -1;

  if (listen(sockFd, 10) < 0) {
    uError("listen tcp server socket failed, 0x%x:%hu(%s)", ip, port, strerror(errno));
    return -1;
  }

  return sockFd;
}

注意：listen异常没有close socket
  if (listen(sockFd, 10) < 0) {
    uError("listen tcp server socket failed, 0x%x:%hu(%s)", ip, port, strerror(errno));
    return -1;
  }

**Comment by Aries-Lee1991** [comment]
@jtao1735 让我们boss亲自看一下这个bug~

**Comment by Aries-Lee1991** [comment]
@Remainfox 这个错误你这边是否可以更正过来递交个PR呢~这样也能成为我们的Contributor呢~

**Comment by Aries-Lee1991** [comment]
@Remainfox 先加一下微信吧：tdengine

**Comment by guanshengliang** [comment]
The error handling code is incomplete, and the scanning tool did not find it
We have fixed and merged into the develop branch
thank a lot
