### ISSUE TITLE
data is not consistent 

### ISSUE THREAD

**Issue by xiaopangemail** [taosdata/TDengine#24705]
1、同一个应用，同时向群集A、B写同样的数据，群集A、B为主备的情况
2、查询相同时间的数据总量，存在群集A、B数据一致、群集A比群集B数据量多、群集A比群集B数据量少的情况
3、不同的应用(对应不同的群集)都出现这个问题

**Comment by yu285** [comment]
版本号是？可以停一下应用看看是中途不一致，还是最终不一致

**Comment by xiaopangemail** [comment]
2.6.0.32 和3.2.0.0  都存在这个问题。数据最终不一致，查询几天前的数据是不一致的。不同的应用批量写和单条写都存在这样的情况

**Comment by yu285** [comment]
相同时间戳的数据会发生覆盖，你们能完全避免这种情况发生吗

**Comment by xiaopangemail** [comment]
这个确认过数据，不同的时间戳，我们是间隔写入的

**Comment by yu285** [comment]
3.0 不会存在这个情况

可以加我微信远程排查一下

a15652223354
