### ISSUE TITLE
普通用户可以随意删除库中的表

### ISSUE THREAD

**Issue by lcy001001** [taosdata/TDengine#24729]
使用root用户创建了一个wxkj普通用户，登录上这个用户，为什么他具有删除表的权限。TDengine3.0.3.0版本
![Uploading 4df41ff2f49a94126f86a43aa6a03e0.png…]()

**Comment by lcy001001** [comment]
![Uploading 4df41ff2f49a94126f86a43aa6a03e0.png…]()

**Comment by lcy001001** [comment]
![4df41ff2f49a94126f86a43aa6a03e0](https://github.com/taosdata/TDengine/assets/128111030/94116805-4928-4f34-8268-73b954fbefe7)

**Comment by lcy001001** [comment]
![d548e01fdc15c91f24cb29e54ee7e1f](https://github.com/taosdata/TDengine/assets/128111030/2dd10c10-4e2f-424e-9985-c9f9c09f94ae)

**Comment by yu285** [comment]
用户权限控制只有企业版支持。
