### ISSUE TITLE
taos client got failed to get fqdn

### ISSUE THREAD

**Issue by fbird** [taosdata/TDengine#24724]
**Bug Description**
hello, i got "failed to get fqdn, code:-3, reason:Temporary failure in name resolution " in my taos client, the client taos.cfg was configged success, and the query also worked properly, but the error happened like a warn. btw, is there have any solution for the slow deep page query, thans

**Expected Behavior**
client works well 

**Screenshots**
the client login with a error as follow
![image](https://github.com/taosdata/TDengine/assets/25980768/6032fcc1-2280-4eb7-a428-4ad2fd9159e0)

also happend for slow query
![image](https://github.com/taosdata/TDengine/assets/25980768/8165d8ae-4339-46e8-a336-e4fcb5267ac4)

work fine for quick query
![image](https://github.com/taosdata/TDengine/assets/25980768/1b255e96-41ea-4264-bcc4-79c08936c6e8)

**Environment (please complete the following information):**
 - TDengine Version [3.2.1.0]

**Additional Context**

**Comment by yu285** [comment]
连接问题 https://www.taosdata.com/engineering/11076.html 看下问题1 排查一下
