### ISSUE TITLE
centos7.7下taosd进程占用的内存不会释放

### ISSUE THREAD

**Issue by lovetaitai** [taosdata/TDengine#2473]
使用jdbc连接taos数据库，循环创建表进行测试，当taosd内存占用100%后，数据库就异常关闭了，这个策略是不是不太合适，会严重影响到业务流程。

**Comment by lovetaitai** [comment]
版本为1.6.5.6

**Comment by Aries-Lee1991** [comment]
> 版本为1.6.5.6

这边建议您试着先升级一下，因为现在稳定版本已经更新到1.6.6.0了。

**Comment by lovetaitai** [comment]
我升级到了1.6.6.0了，原先内存使用100%了taosd异常停止问题不存在了，但是发现另一个问题，循环创建表运行一段时间后，进程taosd内存占用60%后，停止创建和连接，发现内存不会释放，占用一直这么多

**Comment by Aries-Lee1991** [comment]
> 我升级到了1.6.6.0了，原先内存使用100%了taosd异常停止问题不存在了，但是发现另一个问题，循环创建表运行一段时间后，进程taosd内存占用60%后，停止创建和连接，发现内存不会释放，占用一直这么多

好的，我们这边看一下这个问题。

**Comment by guanshengliang** [comment]
在TDengine的设计中，分成两类数据
- 元数据：数据库、数据表，mnode模块负责处理，存储在管理节点
- 时序数据：数据表中的每条记录，dnode/vnode模块中处理，存储在数据节点

元数据全内存，只要启动就会占用资源。
您的这个测试场景：循环建表；其实是在测试管理节点的性能和容量，资源不释放是正常的。

这种设计会占用较多内存，在2.0版本中有所缓解，但是比较重要的数据全内存是TDengine的一个比较特定的设计
通常默认情况下，一个数据表大概占用100K左右内存，您可以据此合力分配资源，或者扩充服务器

**Comment by lovetaitai** [comment]
我们实际场景中会有20w设备的超级表下单表创建需求，这样的话按照目前版本解决方案还是需要适当扩大内存了

**Comment by lovetaitai** [comment]
内存占用60%的情况下，我重启taosd以后内存占用降到了20%，这一部分也不会自动释放的吗

**Comment by guanshengliang** [comment]
TDengine适当的占用了一些内存，以便提升性能。在极限配置的情况下，每张表也可降低到10K左右的内存需求，但是性能影响很明显。目前内存已经很便宜，在有20W设备数据规模的企业中，这点成本更是不算什么。

如果您还有使用上的需求和问题，请联系我们的技术支持团队 @johnnyhou327

**Comment by dullduck** [comment]
按照每张表占用100k的内存, 实际使用的内存也比计算值大很多
