### ISSUE TITLE
jdbc自动创建子表语句绑定表名如果是大写，子表名会变成大写，引起后续一系列后续问题

### ISSUE THREAD

**Issue by zhujiaxin** [taosdata/TDengine#24748]
**Bug Description**
如果使用客户端模式连接tdengine，如果插入数据使用自动建表语句后会出现子表名变成大写的问题

**To Reproduce**
1. 使用官方jdbcdemo在ParameterBindingDemo.java的74行吧小写t_改成大写T_后就会出现此问题。

**Expected Behavior**
如果使用参数绑定的方式创建的自动建表，如果tbname设置为了大写，在tdengine中的子表名也为大写了。

**Screenshots**
![image](https://github.com/taosdata/TDengine/assets/30893925/e51af374-eba5-4349-ba49-27d46012e2e6)
![image](https://github.com/taosdata/TDengine/assets/30893925/2cfadcf3-d4eb-4051-843d-467d7b02fea8)

**Environment (please complete the following information):**
 - OS: windows11
 - Memory 32G, CPU I9-12900H, DISK 500G
 - TDengine Version 3.2.2.0 (in docker)

**Additional Context**
使用官方镜像 tdengine/tdengine:3.2.2.0
taos-jdbcdriver:3.2.8
使用原生的拼接sql的方式进行拼接。

**Comment by zhujiaxin** [comment]
当前测试在修改子表相关的操作、子表直接查询两部分操作会出现找不到表的错误

**Comment by yu285** [comment]
在有大写的表名两侧增加反引号即可，可以看下文档。
