### ISSUE TITLE
how to drop a empty subtable?

### ISSUE THREAD

**Issue by jandison** [taosdata/TDengine#24762]
业务特点导致存在大量的空子表（用户退订套餐，存量数据过期被删除后，就一直是空表），约达到所有子表的40%，子表量目前约5千万级别，还一直在缓慢上升，该如何判断子表是否为空，并删除（除了逐表select count还有其他途径吗）？

**Comment by yu285** [comment]
可以看下文档的 TTL  功能能否满足。

**Comment by jandison** [comment]
@yu285 好像不太行，设置ttl后，表存在时间到了ttl设置时间后就会被删除，并不关心这个表有没有数据，即使是一个正常写入的表也会被删掉。

**Comment by yu285** [comment]
如果设置一个业务允许的最大值呢，比如1年，就没有任何表会再写入了，这样即便是用 TTL 删除也没有问题。

**Comment by jandison** [comment]
还是有业务风险，可能会把续订套餐的用户数据误删掉。要是能增加一个空表自动删除的功能就好了。

**Comment by dfk-753** [comment]
我的库也是每天会生成大量空的子表，怎么设置ttl呢，我在3.1.0.0版本里面设置不了，麻烦给提供下设置样例呢

**Comment by yu285** [comment]
> 还是有业务风险，可能会把续订套餐的用户数据误删掉。要是能增加一个空表自动删除的功能就好了。

可以加微信具体沟通一下，功能有价值，我们可以考虑开发。

**Comment by yu285** [comment]
> 我的库也是每天会生成大量空的子表，怎么设置ttl呢，我在3.1.0.0版本里面设置不了，麻烦给提供下设置样例呢

https://docs.taosdata.com/reference/taos-sql/table/#%E4%BF%AE%E6%94%B9%E8%A1%A8%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F
