### ISSUE TITLE
TDengine 是否支持数据保留策略？

### ISSUE THREAD

**Issue by LiuShiYa-github** [taosdata/TDengine#24776]
### 应用场景:
使用TDengine作为Prometheus的后端存储，监控数据一般保留近三个月也就可以了，所以对于三个月之前的数据应该怎么清理？

### 查看官方文档：
虽然我看官方文档中https://docs.taosdata.com/taos-sql/delete-data/  有删除数据的内容，但是还需要写定时任务脚本来执行，并且我个人认为额外写脚本进行删除历史数据的方式并没有使用数据保留策略自动清理的方式优秀。

请问TDengine 是否支持数据保留策略？

**Comment by yu285** [comment]
数据库的 keep 参数可以看下

**Comment by LiuShiYa-github** [comment]
是的,这正是我想要的，经过验证是否满足我的需求，感谢支持~
