### ISSUE TITLE
TDengine数据库3.0以上开源版本使用问题

### ISSUE THREAD

**Issue by xyxfy** [taosdata/TDengine#24789]
**Bug Description**

3.0.1.1的版本在ubuntu16的系统上安装成功，但是使用java驱动无法连接，提示某个类不存在。
3.0.1.1以上的其他版本，均无法在ubuntu16/CentOS7系统上安装成功。

**Comment by yu285** [comment]
这些版本都是初始版本，与现在不兼容。建议使用较新的 3.2.1.0

**Comment by xyxfy** [comment]
3.1.1.2是什么版本，怎么获取

**Comment by yu285** [comment]
> 3.1.1.2是什么版本，怎么获取

通过官网下载即可，不过这两天在发布3.2.3.0 是更好的版本，可以稍等：https://docs.taosdata.com/get-started/package/

**Comment by xyxfy** [comment]
![TD时间不同步](https://github.com/taosdata/TDengine/assets/52305431/3f39a65f-3859-4ae1-9e1e-e456d61f034b)
这个问题是什么原因，实际上客户端和服务端的系统时间是一样的，还有其他的情况会导致这个问题吗？
