### ISSUE TITLE
不同服务器写入数据失败

### ISSUE THREAD

**Issue by moco2022** [taosdata/TDengine#24795]
我两台设备，一台设备运行了数据库，另一台设备想插入和读取当前设备的数据，为啥不生效？需要设置哪个属性才会生效
版本是V2.4.0.4版本

![企业微信截图_2](https://github.com/taosdata/TDengine/assets/110591589/1b763e42-9c8b-4d49-990f-a9bad717a0ee)
![企业微信截图_50](https://github.com/taosdata/TDengine/assets/110591589/78b68838-1718-41fd-8bf7-44203010fcc2)

**Comment by moco2022** [comment]
版本是V2.4.0.4版本

**Comment by yu285** [comment]
不好意思 2.4 已经不提供官方支持维护了，建议尽早迁移：https://www.taosdata.com/tdengine-engineering/17753.html

**Comment by yu285** [comment]
如果迁移有问题 可以添加微信 a15652223354

**Comment by moco2022** [comment]
好的
