### ISSUE TITLE
在 Kubernetes 上部署 TDengine 集群，显示错误dnode file:/var/lib/taos//dnode/dnode.json not exist，无法建立连接

### ISSUE THREAD

**Issue by juaqiang** [taosdata/TDengine#24822]
在 Kubernetes 上部署 TDengine 集群，根据官网文档采用Kubectl工具部署，一共3个节点，第一个POD启动时出现以下错误：
02/22 19:30:11.998670 00000064 UTL default      metaDebugFlag            131
02/22 19:30:11.998672 00000064 UTL default      timezone                 Asia/Shanghai (CST, +0800)
02/22 19:30:11.998673 00000064 UTL default      locale                   en_US.UTF-8
02/22 19:30:11.998674 00000064 UTL default      charset                  UTF-8
02/22 19:30:11.998675 00000064 UTL default      assert                   1
02/22 19:30:11.998677 00000064 UTL default      enableCoreFile           1
02/22 19:30:11.998678 00000064 UTL default      numOfCores               8.00
02/22 19:30:11.998680 00000064 UTL default      SSE42                    0
02/22 19:30:11.998681 00000064 UTL default      AVX                      0
02/22 19:30:11.998682 00000064 UTL default      AVX2                     0
02/22 19:30:11.998684 00000064 UTL default      FMA                      0
02/22 19:30:11.998685 00000064 UTL default      SIMD-builtins            0
02/22 19:30:11.998686 00000064 UTL default      tagFilterCache           0
02/22 19:30:11.998688 00000064 UTL default      openMax                  1073741816
02/22 19:30:11.998689 00000064 UTL default      streamMax                16
02/22 19:30:11.998690 00000064 UTL default      pageSizeKB               4
02/22 19:30:11.998692 00000064 UTL default      totalMemoryKB            8159328
02/22 19:30:11.998693 00000064 UTL default      os sysname               Linux
02/22 19:30:11.998694 00000064 UTL default      os nodename              tdengine-0
02/22 19:30:11.998695 00000064 UTL default      os release               5.10.0-182.0.0.95.oe2203sp3.x86_64
02/22 19:30:11.998697 00000064 UTL default      os version               #1 SMP Sat Dec 30 13:10:36 CST 2023
02/22 19:30:11.998698 00000064 UTL default      os machine               x86_64
02/22 19:30:11.998699 00000064 UTL default      version                  3.0.7.1
02/22 19:30:11.998701 00000064 UTL default      compatible_version       3.0.0.0
02/22 19:30:11.998702 00000064 UTL default      gitinfo                  56679a7b20ba3635dd3e08116b604afc474b1ecb
02/22 19:30:11.998703 00000064 UTL default      buildinfo                Built at 2023-07-13 19:03
02/22 19:30:11.998705 00000064 UTL ====================
=============================================
02/22 19:30:12.000613 00000064 DND start to init dnode env
02/22 19:30:12.001272 00000064 DND dnode file:/var/lib/taos//dnode/dnode.json not exist
02/22 19:30:12.002099 00000064 DND mnode file:/var/lib/taos//mnode/mnode.json not exist
02/22 19:30:12.002543 00000064 DND file:/var/lib/taos//qnode/qnode.json not exist
02/22 19:30:12.002959 00000064 DND file:/var/lib/taos//snode/snode.json not exist
系统为openEuler 22.03容器无法启动，部署失败，请问是什么原因呢

**Comment by juaqiang** [comment]
已解决，是存储的事，使用的windows NFS服务器无法获取root权限写文件就卡那了，换LInux系统NFS服务器就好了

**Comment by ohhhyuan** [comment]
想问下，手动部署的TD集群数据，你是如何迁移到容器里的

**Comment by juaqiang** [comment]
他不是有taosdump工具吗，先把数据从集群里导出来，再在容器里设置持久化存储，把数据目录用nfs挂载，把数据导进去



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月01日 09:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [taosdata/TDengine] 在 Kubernetes 上部署 TDengine 集群，显示错误dnode file:/var/lib/taos//dnode/dnode.json not exist，无法建立连接 (Issue #24822) |

想问下，手动部署的TD集群数据，你是如何迁移到容器里的

**Comment by ohhhyuan** [comment]
> 他没有taosdump工具吗，先把数据从资源里导出来，再在容器里设置持久化存储，把数据目录用nfs挂载，把数据导入口
> [……](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年03月01日 09:55 | | 营养 | ***@***.***> | | 抄送至| ***@***.***>***@***.***> | | 主题 | Re: [taosdata/TDengine] 在 Kubernetes 上部署 TDengine 集群，显示错误 dnode file:/var/lib/taos//dnode/dnode.json not exit，无法建立连接 (Issue #24822 ) | 想问下，手动部署的 TD 集群数据，你是如何迁移到容器里的 — 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您创作了该主题。消息 ID：***@***.***>

试过taosdump工具，但是显示导入数据为空
