### ISSUE TITLE
rpc open too many session

### ISSUE THREAD

**Issue by qanshangi** [taosdata/TDengine#24821]
当连接数超110时，运行几分钟后，客户端抛code:[0x22],error:rpc open too many session异常，后面一直连接不上 ，使用的C# TDengine.Connector3.1.0包

日志：
02/19 15:24:29.039465 00018478 TSC ep:0, 119.45.133.39:6030
02/19 15:24:29.984530 00018841 TSC ERROR failed to connect to server, reason: rpc open too many session

配置：
cfg_file     firstEp                  localhost.localdomain:6030
default      secondEp                 localhost.localdomain:6030
cfg_file     tempDir                  /tmp/
default      minimalTmpDirGB          1.00
default      shellActivityTimer       3
default      compressMsgSize          -1
default      queryPolicy              1
default      enableQueryHb            1
default      enableScience            0
default      querySmaOptimize         0
default      queryPlannerTrace        0
default      queryNodeChunkSize       32768
default      queryUseNodeAllocator    1
default      keepColumnName           0
default      smlChildTableName
default      smlAutoChildTableNameDe
default      smlTagName               _tag_null
default      smlTsDefaultName         _ts
default      smlDot2Underline         1
cfg_file     maxShellConns            5000
default      maxInsertBatchRows       1000000
default      maxRetryWaitTime         10000
default      useAdapter               0
default      queryMaxConcurrentTable  200
default      metaCacheMaxSize         -1
default      slowLogThreshold         3
default      slowLogScope
default      numOfRpcThreads          2
default      numOfRpcSessions         30000
cfg_file     timeToGetAvailableConn   10000
default      keepAliveIdle            60
default      numOfTaskQueueThreads    4
default      experimental             1
default      configDir                /etc/taos/
cfg_file     logDir                   /var/log/taos
default      minimalLogDirGB          1.00
cfg_file     numOfLogLines            10000000
cfg_file     asyncLog                 1
default      logKeepDays              0
default      debugFlag                0
default      tmrDebugFlag             131
default      uDebugFlag               131
default      rpcDebugFlag             131
default      jniDebugFlag             131
default      qDebugFlag               131
default      cDebugFlag               131
default      timezone                 Asia/Shanghai (CST, +0800)
default      locale                   en_US.utf8
default      charset                  UTF-8
default      assert                   1
default      enableCoreFile           1
default      numOfCores               4.00
default      ssd42                    0
default      avx                      0
default      avx2                     0
default      fma                      0
default      avx512                   0
default      simdEnable               0
default      tagFilterCache           0
default      openMax                  1024
default      streamMax                16
default      pageSizeKB               4
default      totalMemoryKB            15642620
default      os sysname               Linux
default      os nodename              VM-0-10-ubuntu
default      os release               4.15.0-180-generic
default      os version               #189-Ubuntu SMP Wed May 18 14:13:57 UTC 2022
default      os machine               x86_64
default      version                  3.2.2.0
default      compatible_version       3.0.0.0

**Comment by diao1ue** [comment]
同问题，请问解决了吗

**Comment by ldc10241** [comment]
同问题，请问解决了吗

**Comment by yu285** [comment]
这个是早起版本的问题，升级到最新版3.3.3.0 就可以了
