### ISSUE TITLE
tdengine一直插入相同数据之后会导致查询速度变慢

### ISSUE THREAD

**Issue by qiaogli** [taosdata/TDengine#24830]
刚开始查询的速度是0.005s
![image](https://github.com/taosdata/TDengine/assets/83851179/14f94fe0-9bbe-466f-9a91-21e1ad4f9dc7)
经过一天的重复插入相同的数据之后，查询速度变成3s多
![image](https://github.com/taosdata/TDengine/assets/83851179/84f5e05c-30ab-4084-ab4d-b909e9e82e58)
等于一天一直在对同一条数据做更新操作 之后查询速度变慢了，如果我后面接着插入数据，查询速度还会进一步变慢，这个有什么处理办法吗

**Comment by yu285** [comment]
数据被大量相同时间戳的数据覆盖过，导致碎片多，开源版数据导出再导入就行了。（企业版支持在线重组）
