### ISSUE TITLE
想问windows服务端还继续维护吗?已经很久没有发布了

### ISSUE THREAD

**Issue by TRUSS-ME** [taosdata/TDengine#24848]
想问windows服务端还继续维护吗?已经很久没有发布了

**Comment by yu285** [comment]
windows 早期问题较多，开源版维护不过来，回收到到企业版重做了，调整了半年多，最近刚发版出来。 所以用 windows 版本的话，到了 3.0.7.1 之后就没法再升级了。也没有维护团队支持。所以咱们还是换到 linux 版本再使用。
