### ISSUE TITLE
taosd crash led by query

### ISSUE THREAD

**Issue by sancaichuangke** [taosdata/TDengine#24860]
**Bug Description**
超級表5000張子表，每個子表目前平均400000行，本來正常寫入、查詢，突然一查超級表就崩潰，單獨查詢子表還正常。

log：
02/23 19:21:22.675268 00000924 taos_ADAPTER error "" req_id=0x5dfc1d5b2c2000ef sql=SHOW base_data.TABLES error_code=1827 error_msg=Task context not exist model=restful
02/23 19:21:29.679603 00000924 taos_ADAPTER error "" error_code=304 error_msg=Database is starting up model=restful req_id=0x5dfc1d5b2bf000ee sql=SELECT count(*) FROM base_data.base_data_1m
02/23 19:21:36.057791 00000924 taos_ADAPTER error "" error_code=9728 error_msg=syntax error near ".600699" model=restful req_id=0x5dfc1d5b306000f1 sql=DESCRIBE base_data.600699
02/23 19:21:43.273322 00000924 taos_ADAPTER error "" req_id=0x5dfc1d5b322000f2 sql=DESCRIBE base_data.600699 error_code=9728 error_msg=syntax error near ".600699" model=restful
02/23 19:21:59.894737 00000924 taos_ADAPTER error "" error_msg=Unable to establish connection model=restful req_id=0x5dfc1d5b33c000f3 sql=SHOW base_data.STABLES error_code=11
02/23 19:22:33.764811 00000924 taos_ADAPTER error "" error_code=11 req_id=0x5dfc1d5b3c0000f4 model=restful error_msg=Unable to establish connection sql=SHOW base_data.TABLES
02/23 19:22:36.834593 00000924 taos_ADAPTER error "" model=restful sql=SHOW base_data.STABLES error_code=11 error_msg=Unable to establish connection req_id=0x5dfc1d5b3cc000f5
02/23 19:27:15.140171 00000924 taos_ADAPTER error "" sql=SHOW base_data.STABLES error_code=11 error_msg=Unable to establish connection model=restful req_id=0x5dfc1d5b80b000f6

![微信图片_20240223222757](https://github.com/taosdata/TDengine/assets/96162408/f8df3dc3-86c9-4240-9bcf-2534a272aaa0)
![微信图片_20240223222810](https://github.com/taosdata/TDengine/assets/96162408/fabaa05e-073a-49b9-aa7c-a5fd847fa245)

 - OS: wsl ubuntu
 - 宿主機128G，wsl64G, e5-2680v4, 致鈦4t*2 raid0
 - TDengine Version [3.2.2]

**Comment by yu285** [comment]
这是 3.2.2.0 新特性带来的一个问题，抱歉。可以等我们下周发版，或者自己编译 3.0 分支。
