### ISSUE TITLE
是否可以在调用taos_cleanup后再调用taos_init?

### ISSUE THREAD

**Issue by zhengzxdgis** [taosdata/TDengine#24877]
想要将taos封装成C++的一个类，在构造函数中调用了taos_init，析构函数中调用了taos_cleanup，发现第二次init无法正确初始化taos环境，想请问cleanup之后是否不能再调用init，如果析构中不调用cleanup，那会不会有内存未释放，这个问题如何处理？

**Comment by zhengzxdgis** [comment]
想要将taos封装成C++的一个类，再构造函数中调用了taos_init，析构函数中调用了taos_cleanup，发现第二次init无法正确初始化taos环境，想请问cleanup之后是否不能再调用init，如果析构中不调用cleanup，那会不会有内存未释放，这个问题如何处理？

**Comment by zhengzxdgis** [comment]
taos_cleanup只能是在程序结束之前调用吗？不调用taos_cleanup会有什么影响呢？

**Comment by zhengzxdgis** [comment]
@yu285

**Comment by yu285** [comment]
我们确认下

**Comment by dapan1121** [comment]
@zhengzxdgis 目前不支持二次初始化，最简单的用法就是不需要额外封装调用init和cleanup，taos内部会自行调用Init和cleanup接口。应用即使不调用taos_cleanup，进程退出时也会调用taos_cleanup，可以提前调用，但是调用之后就不能再用taos了。

**Comment by zhengzxdgis** [comment]
收到
