### ISSUE TITLE
TDengineException: Version not compatible

### ISSUE THREAD

**Issue by huhuaihang** [taosdata/TDengine#24881]
TDengineException: Version not compatible
linux 服务器 安装了3.2.2.0
php 用命令行模式   查询写入 都没问题
放在不同的控制器里面路由访问  报错 TDengineException: Version not compatible

**Comment by yu285** [comment]
客户端驱动和服务端版本要保持一致。

**Comment by huhuaihang** [comment]
都是在服务器上操作  taos客户端是能查询  
php 写的 写入和查询也都没问题  但是放到相同项目  下面访问 就报错
https://dev.gofish.ren/h5/device-v2/t-list
![微信图片_20240226153721](https://github.com/taosdata/TDengine/assets/16285213/619a272a-434b-4d17-8718-56ea0d9bd96e)

**Comment by huhuaihang** [comment]
![Uploading 微信图片_20240226154407.png…]()

**Comment by huhuaihang** [comment]
问题解决  如果是升级了  tdengine  php-tdengine需要重新编译一下 然后 php-fpm重新载入配置
