### ISSUE TITLE
failed to connect to server

### ISSUE THREAD

**Issue by huangheding** [taosdata/TDengine#2489]
docker镜像里taos客户端连接服务端

taos server版本 1.6.6.0 
测试docker镜像ubuntu18.04 taos client 版本1.6.6.0

问题：可以连接 可以use database 可以describe table，但是不能select insert

会直接阻塞在那持续一段时间抛出异常   failed to connect to server

因为项目打包在docker镜像上运行 ，所以也存在该问题

**Comment by huangheding** [comment]
taos server log：
06/29 17:33:01.130896 8998 7fe859aae700 MND connection from root is closed
06/29 17:35:13.525639 8998 7fe8592ad700 MND pConn:0x7fe85c2ff190 is rebuild, destIp:0xa901a8c0:192.168.1.169 publicIp:0xa901a8c0:192.168.1.169 usePublicIp:1
06/29 17:35:13.525948 8998 7fe8592ad700 MND user:root login from 192.168.1.144, code:0
06/29 17:35:13.527735 8998 7fe859aae700 MND pShow:0x7fe7e00018d0 is allocated
06/29 17:35:13.527761 8998 7fe859aae700 ERROR MND pShow:0x7fe7e00018d0, type:14 vpeers-rsp, failed to get Meta, code:76
06/29 17:35:17.130491 8998 7fe859aae700 MND pConn:0x7fe85c2ff210 is rebuild, destIp:0xa901a8c0:192.168.1.169 publicIp:0xa901a8c0:192.168.1.169 usePublicIp:1
06/29 17:35:17.130532 8998 7fe859aae700 MND login from:9001a8c0:45779
06/29 17:35:17.130610 8998 7fe858aac700 MND DB is change to:0.xiaojin by root
06/29 17:35:23.135896 8998 7fe8592ad700 MND connection from root is closed
06/29 17:35:28.985824 8998 7fe8592ad700 MND pConn:0x7fe85c2ff290 is rebuild, destIp:0xa901a8c0:192.168.1.169 publicIp:0xa901a8c0:192.168.1.169 usePublicIp:1
06/29 17:35:28.985859 8998 7fe8592ad700 MND login from:9001a8c0:45779
06/29 17:35:28.985895 8998 7fe8592ad700 MND 0.xiaojin.xj_ali_point, uid:104363790266625593 meter meta is retrieved
06/29 17:35:28.988807 8998 7fe859aae700 MND metric:0.xiaojin.xj_ali_point retrieve all meter, no query condition
06/29 17:35:28.990539 8998 7fe859aae700 MND metric:0.xiaojin.xj_ali_point numOfRes:9693
06/29 17:35:28.996290 8998 7fe859aae700 MND metric:0.xiaojin.xj_ali_point metric-meta tables:9693, vnode:10
06/29 17:35:28.996309 8998 7fe859aae700 MND metric-meta msg size 194414
06/29 17:35:34.990866 8998 7fe859aae700 MND connection from root is closed
06/29 17:36:14.215894 8998 7fe859aae700 MND connection from root is closed

**Comment by Aries-Lee1991** [comment]
OK, we'll check it.

**Comment by liu0x54** [comment]
你这个是自己制作的镜像文件吗？docker container启动的时候是否做了端口绑定以及绑定了哪些端口？

**Comment by huangheding** [comment]
> 你这个是自己制作的镜像文件吗？docker container启动的时候是否做了端口绑定以及绑定了哪些端口？

taos server没用docker，server跑在一台本地服务器上面，为了测试 我构建了一个docker ubuntu 18.04的镜像  然后把taos 客户端1660 copy过去 然后在容器中安装客户端，然后taos -h 服务器这样连接的，执行查询或者插入就会阻塞

**Comment by liu0x54** [comment]
192.168.1.144是什么ip地址？是不是你的docker的宿主机的地址？这个问题可能是你客户端在docker里，访问taos server时docker网络 的问题。
建议客户端不要放在docker里运行；我们有对应的windows，linux的客户端软件，可以安装个客户端软件后再试试

**Comment by huangheding** [comment]
> 192.168.1.144是什么ip地址？是不是你的docker的宿主机的地址？这个问题可能是你客户端在docker里，访问taos server时docker网络 的问题。
> 建议客户端不要放在docker里运行；我们有对应的windows，linux的客户端软件，可以安装个客户端软件后再试试

对的 144是我docker宿主机地址 169是taos server服务器所在地址，不用docker是可以的 这只是我测试来着，但是项目要打包在docker镜像中跑啊，现在的问题就是项目跑着跑着就阻塞了 我才排查测试出这个问题所在，，网络的话 这个taos客户端是可以连接服务端的啊  这代表网络就是通的不是嘛

**Comment by liu0x54** [comment]
你的安装软件包文件名贴一下，服务端和客户端端的文件名都贴一下

**Comment by huangheding** [comment]
> 你的安装软件包文件名贴一下，服务端和客户端端的文件名都贴一下

TDengine-server-1.6.6.0-Linux-x64.tar.gz  TDengine-client-1.6.6.0-Linux-x64.tar.gz

**Comment by liu0x54** [comment]
1.你在客户端和server端的/etc/taos/taos.cfg文件中都加上一句：debugFlag 135
2.然后，把两边的/var/log/taos/下面的文件都删掉
3.再跑一遍，重现故障
4.再吧两边的/var/log/taos/下的文件打包后上传上来

**Comment by huangheding** [comment]
> 1.你在客户端和server端的/etc/taos/taos.cfg文件中都加上一句：debugFlag 135
> 2.然后，把两边的/var/log/taos/下面的文件都删掉
> 3.重启taosd和客户端，再跑一遍，重现故障
> 4.再吧两边的/var/log/taos/下的文件打包后上传上来

不好意思才回复您，因为一直在测试问题，，
现在把项目(golang)跑在跟taos服务端同一个服务器上面的docker容器内，运行大约几十秒后就会阻塞
阻塞位置是对taos的select max()操作
go连接taos尝试使用连接池、单连接每次执行open close、单连接open一次永远不close 运行结果都是跟上述问题一致

下面是服务端log ，麻烦了~


[taosd0.log](https://github.com/taosdata/TDengine/files/4856657/taosd0.log)
[taos0.0.log](https://github.com/taosdata/TDengine/files/4856658/taos0.0.log)

**Comment by huangheding** [comment]
抱歉 之前的log修改debugflag没有成功 ，我又重新复现了一下问题 这次是135的log
这次阻塞在 taos insert 执行
[taoslog0.0.log](https://github.com/taosdata/TDengine/files/4861882/taoslog0.0.log)

**Comment by liu0x54** [comment]
从日志里看不出阻塞在insert的现象，要不你留个联系方式，我们同事远程给你看看

**Comment by huangheding** [comment]
> 从日志里看不出阻塞在insert的现象，要不你把你的写入程序在这里贴一下，我们看看有没有使用上的问题

**Comment by huangheding** [comment]
> > 从日志里看不出阻塞在insert的现象，要不你把你的写入程序在这里贴一下，我们看看有没有使用上的问题

阻塞问题解决了， 我这面把 sockettype 从udp改成了tcp之后不存在阻塞问题了 ，
有一个新问题 现在项目(golang)跑一段时间后就会停掉 抛出的是segmentation fault (core dumped)

应该是C的指针问题 或者是堆栈溢出等等 ， 怀疑是taos的golang sdk cgo部分代码有内存指针问题，
咱这面golang负责的这块关注一下~
