### ISSUE TITLE
请问何时可支持windows下直接连接localhost？

### ISSUE THREAD

**Issue by dbsxdbsx** [taosdata/TDengine#249]
首先感谢下tdengine终于可以用windows下的客户端了。 期待能够只能在windows本地启动服务。

**Comment by zuozhiwen** [comment]
linux server + windows client已经可以了

**Comment by zend** [comment]
WSL在Windows下运行server也无压力，不过要是win10

**Comment by zuozhiwen** [comment]
@zend 我上次用WSL试发现缺少很多组件，磕磕碰碰，Ubuntu和Debian都挺坑，你用的哪个？

**Comment by dbsxdbsx** [comment]
感谢各位回复，确实，目前win10下只能再去开个linux服务端了。

**Comment by zimengpan** [comment]
> #339 已经为WSL提供了暂时的支持，请再尝试一下 

> #339 has provided with a temporary workaround, please pull and try again
