### ISSUE TITLE
Clent and server's time is not synchronized

### ISSUE THREAD

**Issue by xyxfy** [taosdata/TDengine#24915]
![TD时间不同步](https://github.com/taosdata/TDengine/assets/52305431/1ceb15d8-301f-4ecf-bd8a-19296c3422e2)
服务端和客户端的时间时区是一致的，通过Windows客户端查询数据时，时而报错，时而不报错，这个问题可能有哪些原因导致。

**Comment by yu285** [comment]
这个还是要排查机器自身配置为主。数据库也是采集操作系统信息的，不会自己处理。

如果还有问题可以加微信：a15652223354
