### ISSUE TITLE
对时间排序错误

### ISSUE THREAD

**Issue by xinsendi** [taosdata/TDengine#24957]
**Bug Description**
使用order by [time] desc 返回的结果排序出现问题

**To Reproduce**
![1](https://github.com/taosdata/TDengine/assets/130046179/c19232a2-084c-409b-8e34-f02a0fb5b7e6)
![2](https://github.com/taosdata/TDengine/assets/130046179/743f6abf-3026-4e3c-a63f-08ccf973da62)

**Environment (please complete the following information):**
 - OS: [CentOS 7.5]
 - TDengine Version [3.1.1.0]

**Comment by yupingsong-anylink-io** [comment]
请问这个问题你解决了吗？我也遇到了相同的问题

**Comment by xinsendi** [comment]
升级版本就行，升到最新版本
 
发件人： yuping.song
发送时间： 2024-06-21 00:11
收件人： taosdata/TDengine
抄送： yujianxin; State change
主题： Re: [taosdata/TDengine]对时间排序错误 (Issue #24957)
请问这个问题你解决了吗？我也遇到了相同的问题
