### ISSUE TITLE
Error in windows Server 2012 R2 by c# connector

### ISSUE THREAD

**Issue by shaoyingfei** [taosdata/TDengine#2499]
经常弹出错误
![image](https://user-images.githubusercontent.com/40617207/86069724-5700cc00-baad-11ea-87f6-209585ba459e.png)

**Comment by Aries-Lee1991** [comment]
能否详细描述一下？

**Comment by shaoyingfei** [comment]
我现在用的是c#连接TDEngine，版本是1.6.5.7，项目发布到windows server 2012 R2上时，调用TDengine数据库的时候会提示错误，但是新增，查询是可以的，不定时的IIS上的使用TDEngine的服务会挂掉。
报错图片：

系统日志：









------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xiaxin Li"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月30日(星期二) 下午2:01
收件人:&nbsp;"taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送:&nbsp;"跟你吃遍大江南北"<1746723639@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [taosdata/TDengine] c#连接TDEngine，发布到windows Server 2012 R2 上提示错误 (#2499)





 
能否详细描述一下？

**Comment by Aries-Lee1991** [comment]
> 我现在用的是c#连接TDEngine，版本是1.6.5.7，项目发布到windows server 2012 R2上时，调用TDengine数据库的时候会提示错误，但是新增，查询是可以的，不定时的IIS上的使用TDEngine的服务会挂掉。 报错图片： 系统日志：

您好，图片看不到，您加一下tdengine的微信吧。

**Comment by Aries-Lee1991** [comment]
这是你自己编译的windows server吗？

**Comment by plum-lihui** [comment]
TDengine已经更新到v2.0版本，请使用最新的v2.0版本测试吧。如仍然有问题，请联系我们来解决。
多谢！
