### ISSUE TITLE
TDengine-client-1.6.5.9-Windows-x86.exe failed to connect to server

### ISSUE THREAD

**Issue by wangfd83** [taosdata/TDengine#2500]
日志文件如下:

==================================================
                new log file                      
==================================================
06/30 09:12:36.421000 0x29756 UTL timezone not configured, use default
06/30 09:12:36.455000 0x29756 UTL locale not configured, set to default:Chinese_China.936
06/30 09:12:36.455000 0x29756 UTL charset not configured, set to default:cp936
06/30 09:12:36.455000 0x29756 UTL    taos config & system info:
06/30 09:12:36.455000 0x29756 UTL ==================================
06/30 09:12:36.455000 0x29756 UTL  masterIp:               192.168.87.1 
06/30 09:12:36.455000 0x29756 UTL  localIp:                0.0.0.0 
06/30 09:12:36.455000 0x29756 UTL  mgmtShellPort:          6030 
06/30 09:12:36.455000 0x29756 UTL  vnodeShellPort:         6035 
06/30 09:12:36.455000 0x29756 UTL  configDir:              C:/TDengine/cfg 
06/30 09:12:36.455000 0x29756 UTL  logDir:                 C:/TDengine/log 
06/30 09:12:36.455000 0x29756 UTL  scriptDir:              C:/TDengine/script 
06/30 09:12:36.455000 0x29756 UTL  numOfThreadsPerCore:    1.000000 
06/30 09:12:36.455000 0x29756 UTL  affectedRowsMod:        0 
06/30 09:12:36.455000 0x29756 UTL  rpcTimer:               300(ms)
06/30 09:12:36.455000 0x29756 UTL  rpcMaxTime:             600(s)
06/30 09:12:36.455000 0x29756 UTL  shellActivityTimer:     3(s)
06/30 09:12:36.455000 0x29756 UTL  meterMetaKeepTimer:     7200(s)
06/30 09:12:36.455000 0x29756 UTL  metricMetaKeepTimer:    600(s)
06/30 09:12:36.455000 0x29756 UTL  defaultDB:               
06/30 09:12:36.455000 0x29756 UTL  defaultUser:            root 
06/30 09:12:36.455000 0x29756 UTL  sockettype:             udp 
06/30 09:12:36.455000 0x29756 UTL  compressMsgSize:        -1 
06/30 09:12:36.455000 0x29756 UTL  maxSQLLength:           65380(byte)
06/30 09:12:36.455000 0x29756 UTL  maxNumOfOrderedRes:     100000 
06/30 09:12:36.455000 0x29756 UTL  timezone:               not configured 
06/30 09:12:36.455000 0x29756 UTL  locale:                 Chinese_China.936 
06/30 09:12:36.455000 0x29756 UTL  charset:                cp936 
06/30 09:12:36.455000 0x29756 UTL  numOfLogLines:          10000000 
06/30 09:12:36.455000 0x29756 UTL  asyncLog:               1 
06/30 09:12:36.455000 0x29756 UTL  debugFlag:              131 
06/30 09:12:36.455000 0x29756 UTL  rpcDebugFlag:           131 
06/30 09:12:36.455000 0x29756 UTL  tmrDebugFlag:           131 
06/30 09:12:36.455000 0x29756 UTL  cDebugFlag:             131 
06/30 09:12:36.455000 0x29756 UTL  jniDebugFlag:           131 
06/30 09:12:36.455000 0x29756 UTL  odbcDebugFlag:          131 
06/30 09:12:36.455000 0x29756 UTL  uDebugFlag:             131 
06/30 09:12:36.455000 0x29756 UTL  qDebugFlag:             131 
06/30 09:12:36.455000 0x29756 UTL  gitinfo:                cfdd50d2404338577744e8af0def471535586856 
06/30 09:12:36.455000 0x29756 UTL  gitinfoOfInternal:      9e6b936fad2be7cce6b2810cd9bb264f4d4dff01 
06/30 09:12:36.455000 0x29756 UTL  buildinfo:              Built by root at 2020-04-27 09:40 
06/30 09:12:36.455000 0x29756 UTL  version:                1.6.5.9 
06/30 09:12:36.455000 0x29756 UTL  dataDir:                C:/TDengine/data
06/30 09:12:36.455000 0x29756 UTL ==================================
06/30 09:13:12.486000 0x19320 ERROR TSC 014BE728 reach the max retry:8, code:29

![image](https://user-images.githubusercontent.com/66345837/86071614-499a1080-bab2-11ea-9da9-7b2cf9ccba74.png)

**Comment by Aries-Lee1991** [comment]
收到，我们这边看一下。

**Comment by wangfd83** [comment]
taos.exe可以连接成功，但是c#调用的时候，init失败
![image](https://user-images.githubusercontent.com/66345837/86197189-6fddb000-bb87-11ea-8f48-6b1695eccc25.png)
![image](https://user-images.githubusercontent.com/66345837/86197218-83891680-bb87-11ea-8664-69230c5827d2.png)
![image](https://user-images.githubusercontent.com/66345837/86197315-b6cba580-bb87-11ea-888e-f925d4ff96ee.png)

**Comment by wangfd83** [comment]
![image](https://user-images.githubusercontent.com/66345837/86197433-f1cdd900-bb87-11ea-928b-f9ec04d71098.png)

**Comment by Aries-Lee1991** [comment]
@plum-lihui 麻烦看一下这个问题。

**Comment by plum-lihui** [comment]
这个是windows  32位的客户端程序吗？

**Comment by wangfd83** [comment]
@plum-lihui ，是32位客户端程序的。我调用的也是1.6.5.9版本的32位taos.DLL.example用的是64的TDengineDriver.cs

**Comment by plum-lihui** [comment]
你好！TDengine已经升级到了V2.0版本，请使用最新的c#驱动吧。
多谢！
