### ISSUE TITLE
WAL不释放

### ISSUE THREAD

**Issue by WMSen** [taosdata/TDengine#25014]
一套td集群包含多个库，其中一个库4个vnode，vnode目录下数据量不大，但是wal占用特别大，看日期有一个多月前的还在，其他库的wal都正常，请问是什么原因？如何释放？

**Comment by WMSen** [comment]
version:3.0.4.1

**Comment by yu285** [comment]
升级到 3.2.3.0 ，然后控制一下wal 保留策略（官网文档建库参数），如果还有什么问题可以加我微信 a15652223354
