### ISSUE TITLE
数据库直接暴露到公网安全吗？

### ISSUE THREAD

**Issue by bxjg1987** [taosdata/TDengine#25023]
官方文档没有找到详细的关于安全方面的内容。

是否可以考虑服务端默认使用自签名证书，做TLS/SSL
或者使用原生连接时，支持参数，确定是否需要加密通信

总之希望能提供一种既简单又安全的通信方式，或者已经有的话方便发个官方文档链接吗？

感谢！

**Comment by yu285** [comment]
我们确认下。

**Comment by yu285** [comment]
开源版不支持加密通信。

**Comment by wingwing2005** [comment]
@bxjg1987 多谢您对 TDengine Cloud 的关注，目前云服务对外暴露的访问网关都是 https 的，目前只支持通过 websocket 连接，对于用户权限采用 query 参数 token 的方式，不同用户使用不同的token，token可以用户自己定期刷新。可以参考下面文档建立云服务的连接 https://docs.taosdata.com/cloud/programming/connect/。
