### ISSUE TITLE
Can I dynamically adjust the retention time of database data files？

### ISSUE THREAD

**Issue by crazy11586** [taosdata/TDengine#2503]
-- create database sql
"create database %s precision \"us\" keep 30;", tdengine_db_name

-- problems
I want to adjust the retention time of database data files to keep 20;

Can you Give me some advice? please

**Comment by liuyq-617** [comment]
For some data security reasons, we prohibit dynamic modification of this parameter.

**Comment by crazy11586** [comment]
> For some data security reasons, we prohibit dynamic modification of this parameter.

How should I modify it？

**Comment by crazy11586** [comment]
> For some data security reasons, we prohibit dynamic modification of this parameter.

can't modify it after the database is specified ?

**Comment by liuyq-617** [comment]
yes

**Comment by Aries-Lee1991** [comment]
It seems the issue is already solved. I closed it.
