### ISSUE TITLE
如何分时间段的统计某个状态的时长

### ISSUE THREAD

**Issue by imborntowin** [taosdata/TDengine#25062]
比如某个设备的状态有0、1，0代表关闭，1代表运行

统计运行的时长，第一时间想到的是状态窗口。

但是如果需求是统计过去一周每天的运行时长，如果单纯利用td来实现，该怎么查询呢，有没有比较好的方法。

毕竟有时候运行时长是横跨两天的。

感觉有点像时间窗口嵌套状态窗口的概念，但是写不出来。

有没有大佬指教一下

**Comment by yu285** [comment]
elapsed + state_window 试试可以不?

**Comment by imborntowin** [comment]
> elapsed + state_window 试试可以不？

有试过，感觉就是存在我描述的问题，一个state窗口，可能跨越两天，或者更多天。可能还是得业务代码，通过_wstart, _wend计算一下每天的时长？

**Comment by imborntowin** [comment]
> elapsed + state_window 试试可以不?

感觉比较贴合的功能是partition by 支持函数，能根据日期分组，不知道partition by 后面支不支持to_char函数，实现类似的功能，可惜现在用的版本是3.1.1的，有时间私下试试

**Comment by chudingkun** [comment]
> > elapsed + state_window 试试可以不?
> 
> 感觉比较贴合的功能是partition by 支持函数，能根据日期分组，不知道partition by 后面支不支持to_char函数，实现类似的功能，可惜现在用的版本是3.1.1的，有时间私下试试

有找到方式方法吗？
