### ISSUE TITLE
TDengine installed successfully on CentOS but won't start, logs shown below

### ISSUE THREAD

**Issue by eesliukn** [taosdata/TDengine#25077]
03/13 12:49:22.918789 02688248 DND start to init dnode env
03/13 12:49:22.919024 02688248 DND dnode file:/var/lib/taos//dnode/dnode.json not exist
03/13 12:49:22.919042 02688248 DND mnode file:/var/lib/taos//mnode/mnode.json not exist
03/13 12:49:22.919046 02688248 DND file:/var/lib/taos//qnode/qnode.json not exist
03/13 12:49:22.919048 02688248 DND file:/var/lib/taos//snode/snode.json not exist
03/13 12:49:22.919118 02688248 DND ERROR failed to create dnode since Not found
03/13 12:49:22.919121 02688248 DND ERROR failed to init dnode since unsupported platform, please visit https://www.taosdata.com for support

**Comment by eesliukn** [comment]
<img width="564" alt="3141824" src="https://github.com/taosdata/TDengine/assets/163239463/ff8ade4d-d70c-4080-b949-cab880c0f091">

**Comment by unlock-lee** [comment]
I tried building TDengine (both tar.gz and rpm) on CentOS Stream el9, but it failed. After that, I switched to CentOS 7.9 el7 and successfully built it. for your reference.

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
