### ISSUE TITLE
3.2.3.0建库时设置STT_TRIGGER报错 DB error: Invalid option sstTrigger: 8 valid range: [1, 1] (0.000307s)

### ISSUE THREAD

**Issue by sanhe11** [taosdata/TDengine#25087]
![企业微信截图_17103938872110](https://github.com/taosdata/TDengine/assets/75357740/7be2fb02-237c-4992-a321-c7b2040d1915)

**Comment by yu285** [comment]
stt_trigger 经过重做优化后，3.1.0.0 后在企业版中生效了。
