### ISSUE TITLE
高基数问题：查询时间随基数线性增长如何优化

### ISSUE THREAD

**Issue by ZhangZhen-Naoc** [taosdata/TDengine#25086]
**Performance Issue** 

**Problem Description** 
我使用的单机部署的TDEngine 3.0.5.1 ，基于业务需求的上千万基数进行了查询时间测试，发现查询时间随基数线性增长。
（我直观感觉如果表名或tag有索引应当是log增长？）希望能得到一些高基数场景的优化建议

**To Reproduce**
1. 创建一个超表
2. 插入n个表（n分别取1k,10k, 20k……5M），因主要测试高基数场景，每个表只插入了1000左右
3. 随机取100张表`SELECT`，计算查询平均时间

**Screenshots**
![image](https://github.com/taosdata/TDengine/assets/156745898/02ead597-8b8f-4fb8-ba00-fb85b742f9a8)

**Environment (please complete the following information):**

* OS: [ Ubuntu 20.04]
* CPU: Intel(R) Xeon(R) Platinum 8369HB CPU @ 3.30GHz , 8核
* 内存：64G
* 硬盘：2T
* TDengine Version [3.0.5.1]

**Comment by yu285** [comment]
需要排查很多方面，可以加微信 a15652223354 具体看下
