### ISSUE TITLE
select last_row(*) return null but actually it shouldn't be null

### ISSUE THREAD

**Issue by liujiangithub** [taosdata/TDengine#25092]
**Bug Description**
last_row返回数据为空(实际非空),select * 和select last(*)没有问题，数据库开启了cache_model为'last_row‘，关闭该选项暂未复现

**To Reproduce**
自动测试程序执行以下步骤(手动操作或者关闭cache_model缓存未能复现)
1. 删除并新建数据库，create database xxx KEEP 24h DURATION 1h CACHEMODEL 'last_row'
2. 新建超级表,field(ts timestamp, v double) tag(t varchar(200));
3. 插入语句自动建表10000个，每个表1条数据。
4. 直接从子表查询select last_row(*) from 子表名， 返回的时间字段正确，但数据字段为null,。用select * 和select last(*)查询没有问题。
5. select last_row(*) from 超级表也是这个现象。

**Expected Behavior**
last_row返回正确数据

**Screenshots**
![企业微信截图_17104072179790](https://github.com/taosdata/TDengine/assets/44750857/9ed09b9c-bbbc-4152-a146-57901f33fba0)

**Environment (please complete the following information):**
 - OS: ubuntu18.04
 - Memory, CPU, current Disk Space, 均足够
 - TDengine Version 3.2.3.0

**Comment by yu285** [comment]
收到我们看下

**Comment by yu285** [comment]
可以加我微信，可能需要远程处理一下：a15652223354

**Comment by liujiangithub** [comment]
好的，我复现了现场了，微信已加

**Comment by yu285** [comment]
升级到3.3.0.0 问题已经解决
