### ISSUE TITLE
使用swarm创建集群，挂掉其中一个非主节点，整个集群不可用

### ISSUE THREAD

**Issue by flyzht** [taosdata/TDengine#25098]
使用swarm创建集群，4个主机节点创建4个dnode，td-01 ~ td-04，创建数据库6分片，3个副本，集群正常插入和查询数据
手工删除其中一个非主节点服务，例如：docker service rm taos_td-03
整个集群不可用
[taosdlog.zip](https://github.com/taosdata/TDengine/files/14609721/taosdlog.zip)

![image](https://github.com/taosdata/TDengine/assets/5363822/2180f48f-ff48-49d9-8fb2-eb519fdf88e4)

version: '3.7'

services:
  td-01:
    environment:
      TZ: Asia/Shanghai
      TAOS_FQDN: "td-01"
      TAOS_FIRST_EP: "td-01:6030"
      TAOS_SUPPORT_VNODES: "32"
    image: tdengine/tdengine:3.2.1.0
    ports: 
      - "6030:6030"
    volumes:
      - /data/TDengine/lib/td-01:/var/lib/taos
      - /data/TDengine/logs/td-01:/var/log/taos 
    deploy:
      placement:
        constraints: [node.hostname == tdengine1]
        
  td-02:
    environment:
      TZ: Asia/Shanghai
      TAOS_FQDN: "td-02"
      TAOS_FIRST_EP: "td-01:6030"
      TAOS_SUPPORT_VNODES: "32"
      TAOS_SERVER_PORT: "6130"
    image: tdengine/tdengine:3.2.1.0
    ports: 
      - "6130:6130"
    volumes:
      - /data/TDengine/lib/td-02:/var/lib/taos
      - /data/TDengine/logs/td-02:/var/log/taos
    depends_on:
      - td-01   
    deploy:
      placement:
        constraints: [node.hostname == tdengine2]

  td-03:
    environment:
      TZ: Asia/Shanghai
      TAOS_FQDN: "td-03"
      TAOS_FIRST_EP: "td-01:6030"
      TAOS_SUPPORT_VNODES: "32"
      TAOS_SERVER_PORT: "6230"
    image: tdengine/tdengine:3.2.1.0
    ports: 
      - 6230:6230
    volumes:
      - /data/TDengine/lib/td-03:/var/lib/taos
      - /data/TDengine/logs/td-03:/var/log/taos
    depends_on:
      - td-01
    deploy:
      placement:
        constraints: [node.hostname == tdengine3]

  td-04:
    environment:
      TZ: Asia/Shanghai
      TAOS_FQDN: "td-04"
      TAOS_FIRST_EP: "td-01:6030"
      TAOS_SUPPORT_VNODES: "32"
      TAOS_SERVER_PORT: "6330"
    image: tdengine/tdengine:3.2.1.0
    ports: 
      - 6330:6330
    volumes:
      - /data/TDengine/lib/td-04:/var/lib/taos
      - /data/TDengine/logs/td-04:/var/log/taos
    depends_on:
      - td-01
    deploy:
      placement:
        constraints: [node.hostname == tdengine4]

**Comment by yu285** [comment]
我们可以在非容器的环境给你检查这类问题，容器类的排查较为复杂，社区人力不足以支撑，望理解。
