### ISSUE TITLE
SHOW CREATE TABLE DB error: Unexpected generic error

### ISSUE THREAD

**Issue by TensyAndKiya** [taosdata/TDengine#25119]
**Bug Description**

show create table device_aa;
正常输出建表语句
show create table device_bb;
报错 DB error: Unexpected generic error

**To Reproduce**
1. 使用create table的方式创建表aa
2. show show create table device_aa正常输出
3. 使用insert into ... using的方式创建表bb
4. show create table device_bb报错

**Expected Behavior**
对于任意超级表或子表，show create table均应正常输出建表语句

**Screenshots**
![image](https://github.com/taosdata/TDengine/assets/30516647/c8ec8953-9b33-4778-b32d-4f03d4473ef7)

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - TDengine Version [3.1.1.0] docker

**Additional Context**

**Comment by yu285** [comment]
这个问题升级到 3.2.3.0 可以解决

**Comment by zhuangQingGuang** [comment]
> 这个问题升级到 3.2.3.0 可以解决

升级后 之前建好的表 查询建表语句还是报错 怎么修复
