### ISSUE TITLE
td3.2.3 taosdump "sync leader is unreachable"

### ISSUE THREAD

**Issue by lsh2366254** [taosdata/TDengine#25110]
导出命令
taosdump -h ***  -Dgwc_host_track   -u root -p **  > /data/taos/backgwc.log 2>&1&
5个节点，3副本，每次导出最终都会因为Sync leader is unreachable失败
INFO: create 8 thread(s) to export data ...
.INFO: gwc_host_track.terminal_event_alarm_info_1 [1/3546] write avro 100% of terminal_event_alarm_info_1_012630154183
.INFO: gwc_host_track.terminal_event_alarm_info_1 [2/3546] write avro 100% of terminal_event_alarm_info_1_018930410961
.INFO: gwc_host_track.terminal_event_alarm_info_1 [3/3546] write avro 100% of terminal_event_alarm_info_1_019171482021
.INFO: gwc_host_track.terminal_event_alarm_info_1 [4/3546] write avro 100% of terminal_event_alarm_info_1_019171676232
.INFO: gwc_host_track.terminal_event_alarm_info_1 [5/3546] write avro 100% of terminal_event_alarm_info_1_018930410935
.ERROR: queryDbForDumpOutCountNative() LN4575, failed to run command <SELECT COUNT(*) FROM gwc_host_track.`terminal_event_alarm_info_1_019171678336` WHERE _c0 >= -9223372036854775806 AND _c0 <= 9223372036854775807>. code: 0x8000090c, reason: Sync leader is unreachable
ERROR: queryDbForDumpOutCountNative() LN4575, failed to run command <SELECT COUNT(*) FROM gwc_host_track.`terminal_event_alarm_info_1_018940736520` WHERE _c0 >= -9223372036854775806 AND _c0 <= 9223372036854775807>. code: 0x8000090c, reason: Sync leader is unreachable
ERROR: queryDbForDumpOutOffsetNative() LN4659, failed to run command <SELECT * FROM gwc_host_track.`terminal_event_alarm_info_1_018940736601` WHERE _c0 >= -9223372036854775806 AND _c0 <= 9223372036854775807 ORDER BY _c0 ASC LIMIT 972 OFFSET 0;>. code: 0x8000090c, reason: Sync leader is unreachable
ERROR: 0% of terminal_event_alarm_info_1_018940736601
ERROR: writeResultToAvroNative() LN5245, table rows is zero. actual dump out: 45101, batch 85940 dbName=gwc_host_track tbName=terminal_event_alarm_info_1_019171675359
INFO: gwc_host_track.terminal_event_alarm_info_1 [6/3546] write avro 100% of terminal_event_alarm_info_1_073093300632
.ERROR: queryDbForDumpOutCountNative() LN4575, failed to run command <SELECT COUNT(*) FROM gwc_host_track.`terminal_event_alarm_info_1_018940736159` WHERE _c0 >= -9223372036854775806 AND _c0 <= 9223372036854775807>. code: 0x8000090c, reason: Sync leader is unreachable
ERROR: queryDbForDumpOutCountNative() LN4575, failed to run command <SELECT COUNT(*) FROM gwc_host_track.`terminal_event_alarm_info_1_018930412059` WHERE _c0 >= -9223372036854775806 AND _c0 <= 9223372036854775807>. code: 0x8000090c, reason: Sync leader is unreachable
ERROR: queryDbForDumpOutCountNative() LN4575, failed to run command <SELECT COUNT(*) FROM gwc_host_track.`terminal_event_alarm_info_1_019171677187` WHERE _c0 >= -9223372036854775806 AND _c0 <= 9223372036854775807>. code: 0x8000090c, reason: Sync leader is unreachable
ERROR: getTableTagValueNativeV2() LN2956, failed to run command <SELECT `terminal_id` FROM gwc_host_track.`terminal_event_alarm_info_1_012630154414` LIMIT 1>. code: 0x8000090c, reason: Sync leader is unreachable
ERROR: getTableTagValueNativeV2() LN2956, failed to run command <SELECT `terminal_id` FROM gwc_host_track.`terminal_event_alarm_info_1_019171676057` LIMIT 1>. code: 0x8000090c, reason: Sync leader is unreachable
ERROR: getTableTagValueNativeV2() LN2956, failed to run command <SELECT `terminal_id` FROM gwc_host_track.`terminal_event_alarm_info_1_018940736029` LIMIT 1>. code: 0x8000090c, reason: Sync leader is unreachable
ERROR: getTableTagValueNativeV2() LN2956, failed to run command <SELECT `terminal_id` FROM gwc_host_track.`terminal_event_alarm_info_1_018940736005` LIMIT 1>. code: 0x8000090c, reason: Sync leader is unreachable
ERROR: getTableTagValueNativeV2() LN2956, failed to run command <SELECT `terminal_id` FROM gwc_host_track.`terminal_event_alarm_info_1_019171675433` LIMIT 1>. code: 0x80000130, reason: Database is starting up
ERROR: queryDbForDumpOutCountNative() LN4575, failed to run command <SELECT COUNT(*) FROM gwc_host_track.`terminal_event_alarm_info_1_018940736348` WHERE _c0 >= -9223372036854775806 AND _c0 <= 9223372036854775807>. code: 0x8000090c, reason: Sync leader is unreachable
ERROR: getTableTagValueNativeV2() LN2956, failed to run command <SELECT `terminal_id` FROM gwc_host_track.`terminal_event_alarm_info_1_018940737663` LIMIT 1>. code: 0x8000090c, reason: Sync leader is unreachable
ERROR: getTableTagValueNativeV2() LN2956, failed to run command <SELECT `terminal_id` FROM gwc_host_track.`terminal_event_alarm_info_1_012630154396` LIMIT 1>. code: 0x8000090c, reason: Sync leader is unreachable

**Comment by yu285** [comment]
需要远程排查一下，可以加我们微信 a15652223354
