### ISSUE TITLE
td 3.1.0.2 版本启动出现crash，启动失败，操作系统生成core.xxxx文件

### ISSUE THREAD

**Issue by gitzhuyongfu** [taosdata/TDengine#25113]
td版本信息，以及出现的异常如下(.taosdCrashLog文件)：
s{
        "reportVersion":        1,
        "clusterId":    "8124648695086385513",
        "startTime":    "1710557642190",
        "fqdn": "cdh-3",
        "pid":  "2303",
        "appName":      "taosd",
        "os":   "CentOS Linux 7 (Core)",
        "cpuModel":     "Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz",
        "numOfCpu":     2,
        "memory":       "15991756 kB",
        "version":      "3.1.0.2",
        "buildInfo":    "Built at 2023-08-21 12:38",
        "gitInfo":      "cdc84032dc622c02d1d2e0448c85472eea0c0307",
        "crashSig":     "6",
        "crashTs":      "1710557647926108",
        "stackInfo":    "obtained 19 stack frames\nframe:0, /lib64/libc.so.6(gsignal+0x37) [0x7f220212f387]\nframe:1, /lib64/libc.so.6(abort+0x148) [0x7f2202130a78]\nframe:2, /lib64/libc.so.6(+0x2f1a6) [0x7f22021281a6]\nframe:3, /lib64/libc.so.6(+0x2f252) [0x7f2202128252]\nframe:4, taosd(taosAssertDebug+0x2df) [0x11070a7]\nframe:5, taosd() [0xe80c96]\nframe:6, taosd() [0xe84e36]\nframe:7, taosd() [0xe8558f]\nframe:8, taosd(tdbBtcGet+0xc2) [0xe86b93]\nframe:9, taosd(tdbBtcMoveTo+0x2f7) [0xe8783f]\nframe:10, taosd(tdbTbcMoveTo+0x2e) [0xe7b469]\nframe:11, taosd(ttlMgrFindExpired+0x92) [0x7d7491]\nframe:12, taosd(metaTtlDropTable+0x99) [0x7bf29c]\nframe:13, taosd() [0x7ae00a]\nframe:14, taosd(vnodeProcessWriteMsg+0x4d5) [0x7acca9]\nframe:15, taosd(vnodeApplyWriteMsg+0x682) [0x7b4986]\nframe:16, taosd() [0x111af8d]\nframe:17, /lib64/libpthread.so.0(+0x7ea5) [0x7f22030faea5]\nframe:18, /lib64/libc.so.6(clone+0x6d) [0x7f22021f7b0d]\n"

操作系统的core文件异常如下：
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/bin/taosd'.
Program terminated with signal 6, Aborted.
#0  0x00007f3067f3a387 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
55        return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);
(gdb) where
#0  0x00007f3067f3a387 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007f3067f3bbb8 in __GI_abort () at abort.c:119
#2  0x00007f3067f331a6 in __assert_fail_base (fmt=0x7f306808ef60 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x13a7b72 "0", 
    file=file@entry=0x13a7b38 "/data/release/TDinternal/community/source/util/src/tlog.c", line=line@entry=830, 
    function=function@entry=0x13a7d10 <__PRETTY_FUNCTION__.11877> "taosAssertDebug") at assert.c:92
#3  0x00007f3067f33252 in __GI___assert_fail (assertion=0x13a7b72 "0", file=0x13a7b38 "/data/release/TDinternal/community/source/util/src/tlog.c", line=830, 
    function=0x13a7d10 <__PRETTY_FUNCTION__.11877> "taosAssertDebug") at assert.c:101
#4  0x00000000011070a7 in taosAssertDebug (condition=false, file=0x13718d8 "/data/release/TDinternal/community/source/libs/tdb/src/inc/tdbInt.h", line=355, 
    format=0x1371874 "assert info not provided") at /data/release/TDinternal/community/source/util/src/tlog.c:830
#5  0x0000000000e80c96 in tdbPageGetCell (pPage=0x7f2daa42e400, idx=0) at /data/release/TDinternal/community/source/libs/tdb/src/inc/tdbInt.h:355
#6  0x0000000000e84e36 in tdbBtreeDecodePayload (pPage=0x7f2daa4af000, pCell=0x7f2daa4ae221 "@\345u\373\333u\205\037m\035\020\353\b\307>\347\033", nHeader=3, 
    pDecoder=0x7f3056498b98, pTxn=0x7f3014855b40, pBt=0x7f2da9a16e90) at /data/release/TDinternal/community/source/libs/tdb/src/db/tdbBtree.c:1363
#7  0x0000000000e8558f in tdbBtreeDecodeCell (pPage=0x7f2daa4af000, pCell=0x7f2daa4ae221 "@\345u\373\333u\205\037m\035\020\353\b\307>\347\033", pDecoder=0x7f3056498b98, 
    pTxn=0x7f3014855b40, pBt=0x7f2da9a16e90) at /data/release/TDinternal/community/source/libs/tdb/src/db/tdbBtree.c:1549
#8  0x0000000000e86b93 in tdbBtcGet (pBtc=0x7f3056498a80, ppKey=0x7f2d9cbe4a70, kLen=0x7f2d9cbe4a6c, ppVal=0x0, vLen=0x0)
    at /data/release/TDinternal/community/source/libs/tdb/src/db/tdbBtree.c:2109
#9  0x0000000000e8783f in tdbBtcMoveTo (pBtc=0x7f3056498a80, pKey=0x7f2d9cbe4b40, kLen=16, pCRst=0x7f2d9cbe4b3c)
    at /data/release/TDinternal/community/source/libs/tdb/src/db/tdbBtree.c:2410
#10 0x0000000000e7b469 in tdbTbcMoveTo (pTbc=0x7f3056498a80, pKey=0x7f2d9cbe4b40, kLen=16, c=0x7f2d9cbe4b3c)
    at /data/release/TDinternal/community/source/libs/tdb/src/db/tdbTable.c:264
#11 0x00000000007d7491 in ttlMgrFindExpired (pTtlMgr=0x7f2e77535520, timePointMs=1710476901000, pTbUids=0x7f2d94f2f9e0)
    at /data/release/TDinternal/community/source/dnode/vnode/src/meta/metaTtl.c:353
#12 0x00000000007bf29c in metaTtlDropTable (pMeta=0x7f2f43cbaf00, timePointMs=1710476901000, tbUids=0x7f2d94f2f9e0)
    at /data/release/TDinternal/community/source/dnode/vnode/src/meta/metaTable.c:936
#13 0x00000000007ae00a in vnodeProcessDropTtlTbReq (pVnode=0x7f2daa086000, ver=65663226, pReq=0x7f30564a3057, len=8, pRsp=0x7f2d9cbe4cc0)
    at /data/release/TDinternal/community/source/dnode/vnode/src/vnd/vnodeSvr.c:721
#14 0x00000000007acca9 in vnodeProcessWriteMsg (pVnode=0x7f2daa086000, pMsg=0x7f30564a0928, ver=65663226, pRsp=0x7f2d9cbe4cc0)
    at /data/release/TDinternal/community/source/dnode/vnode/src/vnd/vnodeSvr.c:431
#15 0x00000000007b4986 in vnodeApplyWriteMsg (pInfo=0x7f2d9cbe4e10, qall=0x7f2da951dd00, numOfMsgs=324)
    at /data/release/TDinternal/community/source/dnode/vnode/src/vnd/vnodeSync.c:334
#16 0x000000000111af8d in tWWorkerThreadFp (worker=0x7f2e77687d40) at /data/release/TDinternal/community/source/util/src/tworker.c:344
#17 0x00007f3068f05ea5 in start_thread (arg=0x7f2d9cbe6700) at pthread_create.c:307
#18 0x00007f3068002b0d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

**Comment by yu285** [comment]
咱们升级一下到 3.2.3.0 吧，crash 问题都是在旧版本解决过的。如果还有问题可以微信联系我们 a15652223354
