### ISSUE TITLE
restful query issue

### ISSUE THREAD

**Issue by ws719547997** [taosdata/TDengine#25114]
我分别在本地和云服务器上部署了3.2.0.0和3.2.2.0版本的tdengine，
我使用原生查询时，语句`select * from trade_cal where ts = '2024-12-01';`都能正常返回结果
但是当使用restful连接时，云服务器3.2.2.0版本的返回结果为空。本地的3.2.0.0能正常返回。
请问这是版本差异还是我有哪些配置没有做好呢？

原生查询
```
taos> select * from trade_cal where ts = '2024-12-01';
           ts            | is_trade |
=====================================
 2024-12-01 00:00:00.000 | false    |
Query OK, 1 row(s) in set (0.006377s)
```

**Comment by yu285** [comment]
应该是时区配置的原因，可以观察下是不是相差整数的小时范围

**Comment by ws719547997** [comment]
> 应该是时区配置的原因，可以观察下是不是相差整数的小时范围

感谢帮助！ 
我在参考了这一篇文章后正确的设置了时区信息后，访问能返回预期的结果了！
