### ISSUE TITLE
table join - left.ts = right.ts is expected in join expression

### ISSUE THREAD

**Issue by gujinzhi** [taosdata/TDengine#25117]
1、建立普通表；
2、插入数据；
3、进行表关联查询的时候 ，返回异常 left.ts = right.ts is expected in join expression；
![捕获](https://github.com/taosdata/TDengine/assets/12582544/ecfadb0b-dbb8-491f-ba95-38252b2065c9)
 为何无法进行关联查询呢？

**Comment by gujinzhi** [comment]
版本为 3.2.3.0

**Comment by yu285** [comment]
这个是针对时序数据场景的join ,所以必须要有ts作为连接条件。后续会支持其他列的连接
