### ISSUE TITLE
建库参数STT_TRIGGER是弃用了吗？

### ISSUE THREAD

**Issue by iftrue-cn** [taosdata/TDengine#25115]
![image](https://github.com/taosdata/TDengine/assets/23302166/7e895022-8022-43da-9fa3-06a936261d1b)
从这个版本开始弃用参数STT_TRIGGER了吗？最近的几个版本建库时参数STT_TRIGGER无法超过1

**Comment by yu285** [comment]
stt_trigger 经过重做优化后，3.1.0.0 后在企业版中生效了。

**Comment by iftrue-cn** [comment]
开源版是没有这个功能了吗？这个参数只能是1是吗？
