### ISSUE TITLE
TDengine v3.0 文档缺失用户管理相关说明

### ISSUE THREAD

**Issue by craftslab** [taosdata/TDengine#25129]
**Bug Description**
相比 TDengine v2.6 文档，TDengine v3.0 文档缺失用户管理相关说明

**To Reproduce**
点击 https://docs.taosdata.com/operation/
查看运维指南，缺失用户管理页面

**Expected Behavior**
点击 https://docs.taosdata.com/operation/
查看运维指南，可查看用户管理页面

**Screenshots**
![1](https://github.com/taosdata/TDengine/assets/49358172/aeb854ae-edc8-4b85-88e1-465d0e7fc2af)
![2](https://github.com/taosdata/TDengine/assets/49358172/2317d30b-79aa-4a9e-8a5b-031ed84e6423)

**Environment (please complete the following information):**

**Additional Context**

**Comment by yu285** [comment]
3.0 的用户管理是企业版范畴所以没有出现在开源版文档中，敬请谅解
