### ISSUE TITLE
DBeaver and API calls time out after my TDengine deployed in Docker has been running for a period of time

### ISSUE THREAD

**Issue by imborntowin** [taosdata/TDengine#25144]
**Bug Description**
在测试环境里，用docker部署了有两个月了，今天发现系统异常，定位是tdengine有问题，dbeaver、调用接口都超时。但是好像一段时间又恢复了，很不稳定，不知道是什么问题？如何排查？
docker日志截取一段如下
`
03/21 11:13:40.521899 00000091 TSD vid:4, cid:3252, tsdbDoRetentionBegin done
03/21 11:13:40.521908 00000091 TSD vid:4, cid:3252, tsdbDoRetentionEnd done
03/21 11:13:40.532787 00000085 MND stb:1.sensor_center_st_v2.st_stream_count_for_factor_value, start to retrieve meta
03/21 11:13:40.547820 00000253 VND vgId:4, trim vnode request will be processed, time:1709171835
03/21 11:13:40.547912 00000092 TSD vid:4, cid:3253, tsdbDoRetentionBegin done
03/21 11:13:40.547920 00000092 TSD vid:4, cid:3253, tsdbDoRetentionEnd done
03/21 11:13:40.581468 00000253 VND vgId:4, trim vnode request will be processed, time:1709175439
03/21 11:13:40.581514 00000091 TSD vid:4, cid:3254, tsdbDoRetentionBegin done
03/21 11:13:40.586419 00000091 TSD vid:4, cid:3254, tsdbDoRetentionEnd done
03/21 11:13:40.617245 00000253 VND vgId:4, trim vnode request will be processed, time:1709179044
03/21 11:13:40.617291 00000092 TSD vid:4, cid:3255, tsdbDoRetentionBegin done
03/21 11:13:40.617297 00000092 TSD vid:4, cid:3255, tsdbDoRetentionEnd done
03/21 11:13:40.653051 00000253 VND vgId:4, trim vnode request will be processed, time:1709182649
03/21 11:13:40.653108 00000091 TSD vid:4, cid:3256, tsdbDoRetentionBegin done
03/21 11:13:40.653114 00000091 TSD vid:4, cid:3256, tsdbDoRetentionEnd done
03/21 11:13:40.688360 00000521 VND ERROR vgId:7, msg:0x7f3d57e672e8 failed to process since restore not finished, type:vnode-drop-ttl-stb, gtid:0x0:0x5dc25f00020009a
03/21 11:13:40.688371 00000521 SYN vgId:7, sync get retry epset numOfEps:1 inUse:0
03/21 11:13:40.690698 00000253 VND vgId:4, trim vnode request will be processed, time:1709186253
03/21 11:13:40.690776 00000092 TSD vid:4, cid:3257, tsdbDoRetentionBegin done
03/21 11:13:40.690785 00000092 TSD vid:4, cid:3257, tsdbDoRetentionEnd done
03/21 11:13:40.690953 00000353 VND ERROR vgId:5, msg:0x7f3d57e51628 failed to process since restore not finished, type:vnode-drop-ttl-stb, gtid:0x0:0x5dc25f000200098
03/21 11:13:40.690967 00000353 SYN vgId:5, sync get retry epset numOfEps:1 inUse:0
03/21 11:13:40.693114 00000452 VND ERROR vgId:6, msg:0x7f3d57e666e8 failed to process since restore not finished, type:vnode-drop-ttl-stb, gtid:0x0:0x5dc25f000200099
03/21 11:13:40.693126 00000452 SYN vgId:6, sync get retry epset numOfEps:1 inUse:0
03/21 11:13:40.696266 00000250 VND ERROR vgId:4, msg:0x7f3d57e669e8 failed to process since restore not finished, type:vnode-drop-ttl-stb, gtid:0x0:0x5dc25f000200097
03/21 11:13:40.696280 00000250 SYN vgId:4, sync get retry epset numOfEps:1 inUse:0
03/21 11:13:40.724876 00000253 VND vgId:4, trim vnode request will be processed, time:1709189858
03/21 11:13:40.724961 00000091 TSD vid:4, cid:3258, tsdbDoRetentionBegin done
03/21 11:13:40.724970 00000091 TSD vid:4, cid:3258, tsdbDoRetentionEnd done
03/21 11:13:40.750575 00000253 VND vgId:4, trim vnode request will be processed, time:1709193463
03/21 11:13:40.750660 00000092 TSD vid:4, cid:3259, tsdbDoRetentionBegin done
03/21 11:13:40.750670 00000092 TSD vid:4, cid:3259, tsdbDoRetentionEnd done
03/21 11:13:40.777989 00000253 VND vgId:4, trim vnode request will be processed, time:1709197067
03/21 11:13:40.778077 00000091 TSD vid:4, cid:3260, tsdbDoRetentionBegin done
03/21 11:13:40.778087 00000091 TSD vid:4, cid:3260, tsdbDoRetentionEnd done
03/21 11:13:40.801918 00000253 VND vgId:4, trim vnode request will be processed, time:1709200672

`

 - TDengine Version 3.1.1

**Comment by yu285** [comment]
直接拉 3.2.3.0 镜像可以解决这类问题
