### ISSUE TITLE
客户端连接服务器异常

### ISSUE THREAD

**Issue by potato0934** [taosdata/TDengine#25152]
Client Version:3.0.1.4
输入密码后提示错误如下：Assertion failed: (rows == numOfRows && cols == numOfCols), function setResultDataPtr, file /opt/taos/TDengine/source/client/src/clientImpl.c, line 1877.

**Comment by yu285** [comment]
这个版本比较久了，是初始版本，咱们做个升级，直接使用 3.2.3.0 吧，问题都修过了。如果还有疑问可以加微信 a15652223354。
