### ISSUE TITLE
tdengine 3.0.3.0 core dumped , version 3.2.3.0 worked neither

### ISSUE THREAD

**Issue by zhixingdo** [taosdata/TDengine#25154]
开始遇到的主要问题是集群中的一台服务器持续不断的产生core.xx文件，产生core.xx文件的时候导致服务异常。3副本的数据，其中一台服务器产生core文件后导致整个集群不可用。升级到tdengine3.2.3.0后服务仍然不可用。主要问题如下：

1、偶尔整个集群的所有机器都会产生core.xx文件

2、查询时报错，错误日志如下：
`DB error: Fail to get table info, error: Sync leader is unreachable (10.288967s)`

3、整个集群的所有服务器显示一直在同步数据，IO被占满
<img width="858" alt="image" src="https://github.com/taosdata/TDengine/assets/141227336/dbfa9d88-ee63-4333-aaa2-f4ee63aa0555">

4、整个集群所有服务器都在报相同的错误，错误日志如下：
<img width="1535" alt="image" src="https://github.com/taosdata/TDengine/assets/141227336/f1b53f61-f5d2-4115-bd5d-ca085b32a56c">

`
03/22 10:31:01.965577 00002783 VND ERROR vgId:120 vnodeProcessSubmitReq failed since success, version:602267215
03/22 10:31:01.965580 00002783 VND ERROR vgId:120, process submit request failed since Invalid message, ver:602267215
03/22 10:31:01.965582 00002783 VND ERROR vgId:120, msg:0x7f08a00076b8 failed to apply since Invalid message, index:602267215, gtid:0x0:0x0
03/22 10:31:01.965897 00002783 VND ERROR vgId:120 vnodeProcessSubmitReq failed since success, version:602267216
03/22 10:31:01.965900 00002783 VND ERROR vgId:120, process submit request failed since Invalid message, ver:602267216
03/22 10:31:01.965902 00002783 VND ERROR vgId:120, msg:0x7f08a0008938 failed to apply since Invalid message, index:602267216, gtid:0x0:0x0
`

麻烦社区的大佬们帮忙看下是嘛问题，是否可以解决，谢谢了🙏

**Comment by yu285** [comment]
可以加微信 a15652223354 我们远程看下

**Comment by yu285** [comment]
该问题已经在下一个版本修复，我们直接使用最新版 3.2.3.0 即可
