### ISSUE TITLE
3.1.1.8版本删除子表后磁盘空间未释放

### ISSUE THREAD

**Issue by kaixiangShi** [taosdata/TDengine#25167]
您好，我这边使用的是3.1.1.8版本，再删除大量taos子表后，磁盘空间未释放，这个该如何处理

**Comment by yu285** [comment]
数据的物理删除需要依靠keep 参数的生效。想要在线删除需要企业版/云服务的数据重组支持。

**Comment by fredmuyu** [comment]
> 业务逻辑删除依赖于保持生效。 业务逻辑删除企业版/云服务。

这个有点坑吧，业务逻辑删除不是应该属于基本功能吗？也需要企业版，那开源了个寂寞

**Comment by boomion** [comment]
整个子表drop重新导入也不行么，只能升级企业版？

**Comment by yongweizhao** [comment]
开源版删除数据却不释放磁盘空间，确实开源了个寂寞

**Comment by feifanwsh** [comment]
无语

**Comment by yu285** [comment]
首先，空间的释放是可以通过 keep 参数控制，可以看下文档。

其次在我们产品设计最初，就是设定物联网场景，删除场景很少，主要为写入。
https://www.taosdata.com/jeffsthoughts/105.html

删除都是后期新增的功能。

**Comment by fredmuyu** [comment]
那你觉得mysql 有DELETE、TRUNCATE 等删除数据的语句 为什么还要设计一个 “OPTIMIZE TABLE”  ？

服务资源不足了，keep来生效？

**Comment by yu285** [comment]
> 那你觉得mysql 有DELETE、TRUNCATE 等删除数据的语句 为什么还要设计一个 “OPTIMIZE TABLE” ？
> 
> 服务资源现在就不足了，还要继续等keep来生效？

我们已经尽可能的开源了核心功能，比如集群，三副本，可以确保绝大多数用户的免费使用。

服务资源不足，可以想办法添置，请不要对数据库产生绝对依赖

**Comment by boomion** [comment]
真实场景就是产生了大量垃圾数据，可能是底层上传数据问题，也可能是程序逻辑问题，生产环境白白占用了好几个T，我就只能干瞪眼。

**Comment by boomion** [comment]
整个库导出要1天，你相信么？Data Only size(MB): 3331125

**Comment by yu285** [comment]
导出就是执行查询，快慢与否取决于数据量和建模优化。

如果连时间也不能投入的话，只能考虑企业版本了。

**Comment by boomion** [comment]
没碰到哪个开源项目有这种限制的，不说了

**Comment by yu285** [comment]
> 没碰到哪个开源项目有这种限制的，不说了

别人集群都不让你用。
