### ISSUE TITLE
ProgrammingError: failed to connect to server

### ISSUE THREAD

**Issue by hexinglin** [taosdata/TDengine#2516]
**Bug Description**
我能链接上数据库,查询数据，能添加和删除超级表。但是无法给超级表创建字表。

![image](https://user-images.githubusercontent.com/25925485/86200490-68baa000-bb8f-11ea-92af-dcba701bfbf4.png)
---------------------------------------------------------------------------
ProgrammingError                          Traceback (most recent call last)
<ipython-input-78-d31499dacc54> in <module>
----> 1 cursor.execute("CREATE TABLE a00a090dfb USING th TAGS (1)")

/usr/local/lib/python3.6/dist-packages/taos/cursor.py in execute(self, operation, params)
    119                 return self._handle_result()
    120         else:
--> 121             raise ProgrammingError(CTaosInterface.errStr(self._connection._conn))
    122 
    123     def executemany(self, operation, seq_of_parameters):

ProgrammingError: failed to connect to server

**Environment (please complete the following information):**
 - OS: [e.g. ubuntu18.04]
 - python3.6
 - TDengine Version [e.g. 1.6.5.9]

**Comment by hexinglin** [comment]
这是添加的时候，输出的日志。
07/01 06:02:42.784648 1 7f4442958700 MND pConn:0x7f4445094c10 is rebuild, destIp:0x4e6f2479:121.36.111.78 publicIp:0x40014ac:172.20.0.4 usePublicIp:0
07/01 06:02:42.784661 1 7f4442958700 MND login from:10014ac:31460
07/01 06:02:42.784671 1 7f4442958700 MND 0.tais_test.th, uid:104435888258547727 meter meta is retrieved
07/01 06:02:48.790899 1 7f4442958700 MND connection from root is closed

**Comment by Aries-Lee1991** [comment]
OK, we'll check it.

**Comment by liuyq-617** [comment]
从日志来看，是断开了连接。如果可以，修改运行日志开关，提供更详细的服务端和客户端日志

**Comment by hexinglin** [comment]
> 从日志来看，是断开了连接。如果可以，修改运行日志开关，提供更详细的服务端和客户端日志

怎么修改呀

**Comment by liuyq-617** [comment]
修改客户端和服务端配置文件
# debugFlag 131   修改为   debugFlag   135
然后重启服务端和客户端

**Comment by hexinglin** [comment]
问题解决了。
问题原因是:由于使用udp协议通信(默认)且客户端是在docker中运行。执行添加字表的操作时，无法给客户端返回数据。所以客户端报failed to connect to server（推测）。
解决办法：修改服务端和客服端的配置文件。把taos.cfg 中 ‘sockettype            udp’改为‘sockettype            tcp’
               使用tcp长链接通信。
