### ISSUE TITLE
用python测试插入数据速度较慢

### ISSUE THREAD

**Issue by zzs1978** [taosdata/TDengine#252]
测试了一下使用python接口样例程序插入100万数据，采用默认参数，12核的主机上花了将近一分钟，性能达不到理想值，请问如何优化？
alpr-e2e) hyz@bjworkstation:~/td$ python insert.py
08/01 15:44:20.341892 7fa00ef6f600 TSC set config file directory:/etc/taos
connect to TDengine success
2019-08-01 15:44:20.348595
2019-08-01 15:45:17.917563
两个时间点打印，一个是开始插入前，一个是插入后

**Comment by hzcheng** [comment]
一方面python语言本身就是比较慢的，另一方面，python客户端使用的C的libtaos.so的动态库，python调用c接口也会耗费一些时间。如果想加快速度，有几点建议：
1. 一条insert语句中追加多条记录
```
insert into t1 values (1564650601000, 1) (1564650602000, 2)...... t2 values (1564650601000, 10) (1564650602000, 11)
```
拼装SQL语句字符串时建议使用list的append函数最后用str的join函数连接。

2. 使用多连接，多线程
每个线程负责写一定的表，每个线程使用自己的连接。
注：目前请不要用多线程操纵同一个连接

**Comment by zzs1978** [comment]
我试试用C接口吧
