### ISSUE TITLE
我在四台服务器上部署了涛思集群，只有两个服务器存储了数据，发现创建数据库默认是2个vgroup，是这个原因导致的吗，怎么解决呢？

### ISSUE THREAD

**Issue by LastNever** [taosdata/TDengine#25204]
我在四台服务器上部署了涛思集群，只有两个服务器存储了数据，发现创建数据库默认是2个vgroup，是这个原因导致的吗，怎么解决呢？
1、官网文档中数据库可修改参数似乎没有vgroups，用alter命令试了确实也不行，请问有其他方法可以修改吗？
2、如果不能直接修改vgroups，请问应该怎么解决，我想让数据分布存储在四个服务器上。
![image](https://github.com/taosdata/TDengine/assets/59238906/3b03bbed-1783-4af3-a3a1-c5b88d8632c4)
![image](https://github.com/taosdata/TDengine/assets/59238906/a01ad9c2-6136-4e58-bf3f-df9bf6c71530)

**Comment by enix223** [comment]
我也遇到过这个问题，vgroup只能在创建数据库时指定，后期貌似不能改。就算后期扩充服务器，对于现有的数据库貌似没有什么帮助。

**Comment by yu285** [comment]
开源版不能动态分裂，企业版云服务才能修改。

**Comment by LastNever** [comment]
> 开源版不能动态分裂，企业版云服务才能修改。

谢谢，那现在怎么处理呢，只能新建数据库再导出来吗

**Comment by yu285** [comment]
是的

**Comment by LastNever** [comment]
> 是的

好的，谢谢
