### ISSUE TITLE
failed to execute batch bind, reason: invalid input

### ISSUE THREAD

**Issue by fish-cai** [taosdata/TDengine#25218]
java.sql.SQLException: TDengine ERROR (0x8000070f): failed to execute batch bind, reason: invalid input

	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:95)
	at com.taosdata.jdbc.TSDBJNIConnector.executeBatch(TSDBJNIConnector.java:375)
	at com.taosdata.jdbc.TSDBPreparedStatement.columnDataExecuteBatch(TSDBPreparedStatement.java:943)

代码如下：
        try (TSDBPreparedStatement pstmt = conn.prepareStatement(sql).unwrap(TSDBPreparedStatement.class)) {
            ArrayList<byte[]> list = new ArrayList<>();
            list.add(bytes);
            pstmt.setVarbinary(1, list, 60000);
            pstmt.columnDataAddBatch();
            pstmt.columnDataExecuteBatch();
        }
如果用 pstmt.execute(sql)，报错就是syntax error near '?)' (? only used in stmt)，
场景：时序数据内容是byte[]，长度为 60000

**Comment by yu285** [comment]
麻烦提供一下数据库、驱动版本信息
