### ISSUE TITLE
taosdump throws error "Invalid AVRO codec inputted. Exit program!"

### ISSUE THREAD

**Issue by njuptlzz** [taosdata/TDengine#25243]
![image](https://github.com/taosdata/TDengine/assets/20552955/524a516d-e853-43fd-8dae-501b1a5006fd)

taos版本3.2.3

**Comment by AaronC59** [comment]
Try:

**Comment by AaronC59** [comment]
Try this:

```
taosdump -D data_traffic -o /home/dump
```

The parameter name is `-D`, not `-d`.
