### ISSUE TITLE
Upgrading existing cluster to 3.2.3.0 causes slow queries, but new cluster is not affected

### ISSUE THREAD

**Issue by hert525** [taosdata/TDengine#25241]
从3.0.4.1升级上来的taos集群 相同的查询语句经常需要1-4s
![image](https://github.com/taosdata/TDengine/assets/19421393/a9a9fa87-4273-4da6-a71c-735d0984549f)
新搭建的taos集群 数据量一样 查询是在ms级的
![image](https://github.com/taosdata/TDengine/assets/19421393/5831708b-8568-4eb5-84b8-0115c310c723)

建库语句如下

**Comment by hert525** [comment]
![image](https://github.com/taosdata/TDengine/assets/19421393/aa041827-3c04-4c65-ab85-cde908db91e0)

**Comment by yu285** [comment]
可以尝试把数据做一下重新导入，贴出性能对比截图，如果还是不行，我们可以远程看下。
