### ISSUE TITLE
regarding 3.2.0.0 monitoring

### ISSUE THREAD

**Issue by xiaopangemail** [taosdata/TDengine#25247]
**General Questions**
2.6.0.32 request监控界面会显示各个节点的select/insert量，3.2.0.0监控界面已不显示各个节点的select/insert数量了，这个有没有方法显示各个节点的select/insert量

3.2.0.0 监控采用：grafana + TDinsight for 3.x

**Comment by yu285** [comment]
Requests Rate(Inserts per Second)：平均每秒插入次数。
3.x 有这类指标的
