### ISSUE TITLE
TDengine 2.0 - Coming Activities and Benefits

### ISSUE THREAD

**Issue by xiaopingcs** [taosdata/TDengine#2525]
Hi everyone,
Thanks very much for joining our TDengine community, we are opening this special issue for activities and benefits for our users.  The first activity will be the celebration of coming TDengine 2.0 release.

Please follow us, more activities and benefits are on the way.

**Comment by xiaopingcs** [comment]
![WechatIMG5](https://user-images.githubusercontent.com/65699335/86236002-e7cdc980-bbcb-11ea-9ced-dda2df303ee1.jpeg)

**Comment by lgh-dev** [comment]
发现两个问题。
1. win10客户端2.0没找到下载地址。
2.java jdbc2.0包没有。

去年到今年，折腾了好几次，没有一次能成功用起来。唉~~

**Comment by xiaopingcs** [comment]
> 发现两个问题。
> 
> 1. win10客户端2.0没找到下载地址。
>    2.java jdbc2.0包没有。
> 
> jdbc还可以自己编译，win10客户端真是没法找。
> 
> 去年到今年，折腾了好几次，没有一次能成功用起来。唉~~

不好意思，给你使用带来不便。我们的暂时没有2.0版的客户端， 正在开发中，估计需要2到3周完成。 JDBC 2.0 jar包我们已经上传，可能需要一些时间更新到maven 仓库。

**Comment by sunsnowswift** [comment]
![Uploading image.png…]()

springboot demo 在window10 上运行，连接 2.0 的服务器版本，因为没有找到2.0对应的客户端，安装了最新版版本的1.6.6.1版本的，运行提示   Caused by: java.sql.SQLException: TDengine Error: failed to connect to server
win10 telnet连接ip端口 成功，手动建立了 log数据库。请问原因可能是什么？是否是因为如上图第一条所说的 客户端与服务端版本不一致。

**Comment by xiaopingcs** [comment]
> springboot demo 在window10 上运行，连接 2.0 的服务器版本，因为没有找到2.0对应的客户端，安装了最新版版本的1.6.6.1版本的，运行提示
> `Caused by: java.sql.SQLException: TDengine Error: failed to connect to server`
> win10 telnet连接ip端口 成功，手动建立了 log数据库。请问原因可能是什么？是否是如下第一条所说的 客户端与服务端版本不一致。
> `5. 遇到错误"failed to connect to server", 我怎么办？ 客户端遇到链接故障，请按照下面的步骤进行检查： 确保客户端与服务端版本号是完全一致的，开源社区版和企业版也不能混用`

我们没有做过客户端和服务端版本不一致这方面的测试，所以没有办法回答你的问题。建议你等windows客户端2.0发布之后再使用。

**Comment by sunsnowswift** [comment]
> > springboot demo 在window10 上运行，连接 2.0 的服务器版本，因为没有找到2.0对应的客户端，安装了最新版版本的1.6.6.1版本的，运行提示
> > `Caused by: java.sql.SQLException: TDengine Error: failed to connect to server`
> > win10 telnet连接ip端口 成功，手动建立了 log数据库。请问原因可能是什么？是否是如下第一条所说的 客户端与服务端版本不一致。
> > `5. 遇到错误"failed to connect to server", 我怎么办？ 客户端遇到链接故障，请按照下面的步骤进行检查： 确保客户端与服务端版本号是完全一致的，开源社区版和企业版也不能混用`
> 
> 我们没有做过客户端和服务端版本不一致这方面的测试，所以没有办法回答你的问题。建议你等windows客户端2.0发布之后再使用。

2.0客户端版本发布还需要多久

**Comment by xiaopingcs** [comment]
> > > springboot demo 在window10 上运行，连接 2.0 的服务器版本，因为没有找到2.0对应的客户端，安装了最新版版本的1.6.6.1版本的，运行提示
> > > `Caused by: java.sql.SQLException: TDengine Error: failed to connect to server`
> > > win10 telnet连接ip端口 成功，手动建立了 log数据库。请问原因可能是什么？是否是如下第一条所说的 客户端与服务端版本不一致。
> > > `5. 遇到错误"failed to connect to server", 我怎么办？ 客户端遇到链接故障，请按照下面的步骤进行检查： 确保客户端与服务端版本号是完全一致的，开源社区版和企业版也不能混用`
> > 
> > 
> > 我们没有做过客户端和服务端版本不一致这方面的测试，所以没有办法回答你的问题。建议你等windows客户端2.0发布之后再使用。
> 
> 2.0客户端版本发布还需要多久

最多三周时间

**Comment by arielyang** [comment]
This issue was closed because it has been inactive for too many days.
