### ISSUE TITLE
when we insert data in batches  , TDengine got stuck every single period of time

### ISSUE THREAD

**Issue by ffxin** [taosdata/TDengine#25266]
## 1、数据库环境

- docker环境，宿主机配置内存：125G，cpu：24核心
- TDengine版本 3.0.4.2

## 2、问题描述
在springboot，通过线程池每隔1秒向数据库插入3000条数据（共10组，每一组有300条数据），在运行8～10分钟左右的时间，会出现卡顿现象，在经过10s～30s左右的时间，继续执行，循环如此。。。调整过参数：numOfCommitThreads 改为8、以及48，任然会出现这种情况。。

**Comment by yu285** [comment]
3.0.4.2 版本比较久了，麻烦更新一下到3.2.3.0 吧。

**Comment by yu285** [comment]
另外也需要确认咱们的具体数据库环境，可以加微信a15652223354 做具体排查

**Comment by ffxin** [comment]
> 3.0.4.2 版本比较久了，麻烦更新一下到3.2.3.0 吧。

好的，我这边升级下，试试。
