### ISSUE TITLE
Unsupported stream query

### ISSUE THREAD

**Issue by bdwanga** [taosdata/TDengine#25276]
**Bug Description**
创建流式计算，一直报Unsupported stream query，

**To Reproduce**

CREATE STREAM open_time_s trigger WINDOW_CLOSE INTO open_time AS
SELECT _wstart as `start`, _wend as `end`,_wduration as `time`,last(ts) from tlink_sensor_log where type_id = 2 and (name like '%展开' or name like '%收起')
PARTITION BY tbname
EVENT_WINDOW START WITH `current` >= 1.0 END WITH `current` < 1.0;

**Comment by yu285** [comment]
版本太旧了吧？版本号是？

**Comment by bdwanga** [comment]
> 版本太旧了吧？版本号是？

3.0.5.0
