### ISSUE TITLE
超级表查询总数都查不了

### ISSUE THREAD

**Issue by wangzhiguoengineer** [taosdata/TDengine#25271]
![image](https://github.com/taosdata/TDengine/assets/16033868/a8bbb2aa-a800-4eeb-9524-4a75139f7ef6)

![image](https://github.com/taosdata/TDengine/assets/16033868/cbc3d17f-0642-41c0-8678-fb3239d238f2)

**Comment by yu285** [comment]
这是 3220 一个新优化带来的问题抱歉，已经在3230修复了，您升级一下就好
