### ISSUE TITLE
DB error: Object is creating (0.000329s) - can't create supertable

### ISSUE THREAD

**Issue by NGC2264** [taosdata/TDengine#25290]
taos> CREATE STABLE pvarry_meters (ts TIMESTAMP, P float,Q FLOAT ,U FLOAT, I FLOAT,SUM_U FLOAT,POS_U FLOAT,NEG_U FLOAT,PN_DIFF FLOAT,BAT_I FLOAT,BAT_U 
FLOAT,LSV_P FLOAT,UNIT_HEAT FLOAT,LIMIT_P FLOAT,CE FLOAT,DE FLOAT,BAT_C_U FLOAT,MAXP FLOAT ,MAXI FLOAT ) TAGS (id BIGINT, of_microgrid BIGINT, name VAR
CHAR(60)) ;

DB error: Object is creating (0.000329s)

**Comment by NGC2264** [comment]
taos --version
version: 3.2.1.0 compatible_version: 3.0.0.0
gitinfo: 234463fcca65f3f1d08a1f245570e4e5d5d272e2
buildInfo: Built Linux-x64 at 2023-11-20 17:29:01 +0800

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
3.0早期版本的错误都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
