### ISSUE TITLE
Performance differences between WebSocket and REST API

### ISSUE THREAD

**Issue by zhuangQingGuang** [taosdata/TDengine#25294]
当查询报错的时候 websocket返回时间比restful长很多
TD版本：3.2.0
JDBC版本：3.2.9
链接区别：?batchfetch=true
============websocket=========基本耗时在1S以上
![wesocket-1](https://github.com/taosdata/TDengine/assets/45782190/2a8afea6-bb53-47c1-bc98-29ab6c5da86f)
![websocket-2](https://github.com/taosdata/TDengine/assets/45782190/f80b6ef9-4339-4d62-9e0b-6c8384b50848)
============restful=========基本耗时在1S以内
![restful-1](https://github.com/taosdata/TDengine/assets/45782190/f2949733-917c-40ac-87df-522146291f67)
![restful-2](https://github.com/taosdata/TDengine/assets/45782190/853e3218-685f-4701-82d0-83203b4158d3)

**Comment by yu285** [comment]
查询不报错的时候，性能比对情况如何？
