### ISSUE TITLE
3.2.3.0 docker start up failed 

### ISSUE THREAD

**Issue by WeiduWedo** [taosdata/TDengine#25304]
docker-compose -f docker-compose.yaml up
Starting td-1 ... done
Attaching to td-1
td-1    | sysctl: setting key "kernel.core_pattern", ignoring: Read-only file system
td-1    | 04/09 10:49:45.741707 00000073 UTL apoll url not load
td-1    | 04/09 10:49:45.741826 00000073 UTL load from cfg file /etc/taos/taos.cfg success
td-1    | 04/09 10:49:45.741841 00000073 UTL env file:.env not load
td-1    | 04/09 10:49:45.741848 00000073 UTL load from env variables cfg success
td-1    | failed to init log file since Config not foundfailed to start since init log error
启动会报这些错误，其中taos.cfg是从镜像中拷贝出来的，data和log是镜像自己创建的

**Comment by yu285** [comment]
请提供一下  docker-compose.yaml

**Comment by yu285** [comment]
docker run 后面加上 --privileged 试试

**Comment by buruguichen** [comment]
我也遇到同样的问题，把镜像版本换成3.1.1.0正常启动了
