### ISSUE TITLE
Where is the client for Mac

### ISSUE THREAD

**Issue by RockyNiu** [taosdata/TDengine#2530]
On your document: https://www.taosdata.com/cn/documentation/connector/

"在Mac操作系统下，TDengine提供64位的Mac客户端([2月10日起提供下载](https://www.taosdata.com/cn/all-downloads/#tdengine_mac-list))，客户端安装程序为.tar.gz文件，解压并运行其中的install_client.sh后即可完成安装，安装路径为/usr/loca/taos。客户端目录结构如下："

However, there is no any link to the client for Mac.

Would you help with this issue?

**Comment by Aries-Lee1991** [comment]
Sorry, Mac client is not stable yet. We didn't officially release it. Please follow the official news.
