### ISSUE TITLE
Vulnerability identified in TDengine - information disclosure from pprof

### ISSUE THREAD

**Issue by zzzzhhhhuuuu** [taosdata/TDengine#25325]
![Uploadin
![Snipaste_2024-04-10_15-23-17](https://github.com/taosdata/TDengine/assets/67354980/29ed97f4-316d-4f1f-8381-26e52e10f14d)
g image.png…]()

**Comment by zzzzhhhhuuuu** [comment]
被扫描到的是6041端口

**Comment by yu285** [comment]
我们看下，请等待答复

**Comment by huskar-t** [comment]
@zzzzhhhhuuuu 在配置文件 /etc/taos/taosadapter.toml 中修改 debug = false 将关闭 pprof
