### ISSUE TITLE
TDengine upgrade help wanted

### ISSUE THREAD

**Issue by liuguoshun** [taosdata/TDengine#25336]
3.1.0.0 版本的集群, 升级了一个节点到 3.2.0.0 报如下错误: 版本不一致.
集群小版本升级可以做到在线滚动升级吗？ 

04/11 14:48:28.959376 00026472 RPC DND-C conn 0x7f82a40010a0 status-rsp received from 10.198.193.10:6030, local info:10.198.193.12:14134, len:79, code str:Version not compatible, gtid:0x0:0x6cc12cbea3a00034
04/11 14:48:28.959533 00026498 DND ERROR failed to send status req since Version not compatible, epSet:{10.198.193.12:6030, 10.198.193.10:6030, 10.198.193.11:6030}, inUse:0
04/11 14:48:29.234716 00026469 RPC DND-S conn 0x7f8284001d60 sync-heartbeat received from 10.198.193.10:11770, local info:10.198.193.12:6030, len:175, noResp:1, code:0, cost:14098867us, recv exception, gtid:0x0:0x1b802cbea040004c
04/11 14:48:29.234750 00026469 DND ERROR Version not compatible, cli ver: 3010000, svr ver: 3020000
04/11 14:48:29.234760 00026469 RPC handle 0x7f8284003070 failed to send resp
04/11 14:48:29.960396 00026498 RPC DND-C send request at thread:00026473, dst:10.198.193.10:6030, app:0x9527, gtid:0x0:0x6cc12cbea3e00035
04/11 14:48:29.960575 00026473 RPC DND-C conn 0x7f82900011a0 status is sent to 10.198.193.10:6030, local info 10.198.193.12:14138, len:363, gtid:0x0:0x6cc12cbea3e00035
04/11 14:48:29.960683 00026473 RPC DND-C conn 0x7f82900011a0 data already was written out
04/11 14:48:29.961529 00026473 RPC DND-C conn 0x7f82900011a0 get ahandle 0x9527, persist: 0
04/11 14:48:29.961553 00026473 RPC DND-C conn 0x7f82900011a0 status-rsp received from 10.198.193.10:6030, local info:10.198.193.12:14138, len:79, code str:Version not compatible, gtid:0x0:0x6cc12cbea3e00035
04/11 14:48:29.961698 00026498 DND ERROR failed to send status req since Version not compatible, epSet:{10.198.193.10:6030, 10.198.193.11:6030, 10.198.193.12:6030}, inUse:0
04/11 14:48:30.225024 00026469 RPC DND-S conn 0x7f82840031e0 sync-heartbeat received from 10.198.193.10:11790, local info:10.198.193.12:6030, len:175, noResp:1, code:0, cost:14099045us, recv exception, gtid:0x0:0x1b802cbea070004f
04/11 14:48:30.225057 00026469 DND ERROR Version not compatible, cli ver: 3010000, svr ver: 3020000
04/11 14:48:30.225072 00026469 RPC handle 0x7f82840044f0 failed to send resp
04/11 14:48:30.317795 00026501 MND vgId:1, mnode not leader, state:candidate

**Comment by yu285** [comment]
滚动升级建议在企业版团队跟进的情况下执行，开源用户建议使用离线升级

**Comment by liuguoshun** [comment]
好的
