### ISSUE TITLE
About the .a file in /deps/dm_static

### ISSUE THREAD

**Issue by yangecool** [taosdata/TDengine#25339]
hi, we are currently porting your tdengine to risc-v platform, unfortunatly we found that the last step of compiling didnt pass by the reason of you dm_static file, after throughly searching, we still cant find the source code of libdmodule.a and we cant find the work, do you have any idea or where can we find the code? Thanks

**Comment by yu285** [comment]
we will check on this

**Comment by yu285** [comment]
could you provide the capture about specific error .

**Comment by misyange9** [comment]
<img width="803" alt="Snipaste_2024-05-07_14-06-08" src="https://github.com/taosdata/TDengine/assets/97574583/fea243d8-9291-4f02-941d-799c4eec4ce2">
<img width="499" alt="Snipaste_2024-05-07_14-08-29" src="https://github.com/taosdata/TDengine/assets/97574583/0b828b92-1a38-4caf-8de0-d644c0c9d62a">
The Error was exactly as i described in the issue, your .a file didnt have the matched architecture for my platform so ld cannot find -ldmoudle for compiling.
Please offer some information for the source code of libdmoudle.a
Thanks

**Comment by yu285** [comment]
We need to compile TDengine Enterprise  to obtain the .a file for your use., but we don't have RISC-V server . really sorry for we couldn't help on this .

**Comment by vincentfenet** [comment]
requirement for a binary without its source code prevents this project from being open source

**Comment by yangecool** [comment]
Exactly
