### ISSUE TITLE
(v2.6.0.1) restarting tdengine throws "too many timer controllers, failed to create timer controller"

### ISSUE THREAD

**Issue by Mark33529** [taosdata/TDengine#25349]
我的tdengine部署在阿里云服务器，tdengine开启了自启动，重启阿里云后，tdengine报错，如下所示。

tdengine有1280个vnode，maxTmrCtrl也设置到2048了，还是报以下错误。

04/11 14:44:48.015282 00025740 DND dnode modules is initialized
04/11 14:44:48.016553 00025740 TMR ERROR TSC too many timer controllers, failed to create timer controller.
04/11 14:44:48.016931 00025740 MON monitor module start
04/11 14:44:48.016941 00025740 DND step:dnode-modules is initialized
04/11 14:44:48.016987 00025740 TMR ERROR SHELL too many timer controllers, failed to create timer controller.
04/11 14:44:48.016997 00025740 RPC ERROR SHELL failed to init timers
04/11 14:44:48.028430 00025740 DND ERROR failed to init shell rpc server

**Comment by yu285** [comment]
2.x 我们已经不支持维护了，烦请迁移到 3.x 版本吧。
