### ISSUE TITLE
sql handle increase  内存溢出

### ISSUE THREAD

**Issue by link-wanglei** [taosdata/TDengine#25353]
**Bug Description**
运行系统 windows sever 2016 64位，写数据库操作会导致内存溢出，查看进程，句柄一直增加。
同样的程序运行于win10 ，运行正常，无溢出。

数据库版本，3.0.16

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by yu285** [comment]
windows 早期问题较多，开源版维护不过来，回收到到企业版重做了，调整了大半年，最近刚发版出来。 所以windows版本到了 3.0.7.1 之后就没法再升级了，也没有维护团队支持。所以咱们还是换到 linux 版本再使用，目前最新版为 3.2.3.0。
