### ISSUE TITLE
sockettype tcp core dumped

### ISSUE THREAD

**Issue by huangheding** [taosdata/TDengine#2535]
> 从日志里看不出阻塞在insert的现象，要不你把你的写入程序在这里贴一下，我们看看有没有使用上的问题

_Originally posted by @huangheding in https://github.com/taosdata/TDengine/issues/2489#issuecomment-652955738_

阻塞问题解决了，  我这面把 sockettype 从udp改成了tcp之后不存在阻塞问题了 ，
有一个新问题 现在项目(golang)跑一段时间后就会停掉 抛出的是**segmentation fault (core dumped)**

应该是C的指针内存问题 或者是堆栈溢出等等 ，咱们这边关注一下

**Comment by huangheding** [comment]
今天复现问题时 taos golang的sdk  cgo代码块taosSqlCgo.go这个文件执行query的时候抛出了error：

fatal: morestack on g0
SIGTRAP: trace trap
PC=0x4682a2 m=5 sigcode=128

goroutine 0 [idle]:
runtime.abort()
	/usr/local/go/src/runtime/asm_amd64.s:859 +0x2
runtime.morestack()
	/usr/local/go/src/runtime/asm_amd64.s:416 +0x25

goroutine 7786 [syscall]:
runtime.cgocall(0x945cd0, 0xc00060f738, 0x40f358)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc00060f708 sp=0xc00060f6d0 pc=0x40570b
go_ali_record/common/taos/taosSql._Cfunc_taos_query(0x170c2e0, 0x17ada00, 0x0)
	_cgo_gotypes.go:245 +0x4d fp=0xc00060f738 sp=0xc00060f708 pc=0x75589d
go_ali_record/common/taos/taosSql.(*taosConn).taosQuery.func2(0xc0003266c0, 0x17ada00, 0x17ada00)
	/usr/app/common/taos/taosSql/taosSqlCgo.go:53 +0x5f fp=0xc00060f770 sp=0xc00060f738 pc=0x75b9cf
go_ali_record/common/taos/taosSql.(*taosConn).taosQuery(0xc0003266c0, 0xc0000b0c60, 0x5a, 0x0, 0x0, 0x0)
	/usr/app/common/taos/taosSql/taosSqlCgo.go:53 +0x95 fp=0xc00060f7c8 sp=0xc00060f770 pc=0x759d55
go_ali_record/common/taos/taosSql.(*taosSqlStmt).query(0xc0003d4090, 0xc00020bc80, 0x2, 0x2, 0x2, 0x2, 0x0)
	/usr/app/common/taos/taosSql/statement.go:72 +0xcf fp=0xc00060f840 sp=0xc00060f7c8 pc=0x7544bf
go_ali_record/common/taos/taosSql.(*taosSqlStmt).QueryContext(0xc0003d4090, 0xb37b20, 0xc000128020, 0xc000071c70, 0x2, 0x2, 0x40f358, 0x10, 0x9d8bc0, 0xc0000ea601)
	/usr/app/common/taos/taosSql/connection.go:335 +0x91 fp=0xc00060f890 sp=0xc00060f840 pc=0x757d91
database/sql.ctxDriverStmtQuery(0xb37b20, 0xc000128020, 0xb37e20, 0xc0003d4090, 0xc000071c70, 0x2, 0x2, 0x2, 0x2, 0x0, ...)
	/usr/local/go/src/database/sql/ctxutil.go:82 +0x210 fp=0xc00060f908 sp=0xc00060f890 pc=0x671360
database/sql.rowsiFromStatement(0xb37b20, 0xc000128020, 0xb36060, 0xc0003266c0, 0xc000330dc0, 0xc00060fc20, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/go/src/database/sql/sql.go:2604 +0x16a fp=0xc00060f988 sp=0xc00060f908 pc=0x67d5ba
database/sql.(*Stmt).QueryContext(0xc000332a20, 0xb37b20, 0xc000128020, 0xc00060fc20, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:2556 +0x210 fp=0xc00060fa50 sp=0xc00060f988 pc=0x67d030
database/sql.(*Stmt).Query(...)

@liu0x54 麻烦关注一下 谢谢了~

**Comment by huangheding** [comment]
[taosdlog.1.log](https://github.com/taosdata/TDengine/files/4867654/taosdlog.1.log)
这是server log，我的项目服务是在2020-07-03 11:44:56异常终止的 
异常信息：**Segmentation fault (core dumped)**

**Comment by liu0x54** [comment]
你把这部分操作的代码贴一下？我看看是不是操作上有啥问题

**Comment by huangheding** [comment]
> 你把这部分操作的代码贴一下？我看看是不是操作上有啥问题

连接池：
```
var dbConn *SQLConnPool

// SQLConnPool is DB pool struct
type SQLConnPool struct {
	DriverName     string
	DataSourceName string
	MaxOpenConns   int
	MaxIdleConns   int
	SQLDB          *sql.DB
}

func InitTDB() {

	dbConn = NewPool(conf.GetConf().TAOS.Host, conf.GetConf().TAOS.Port, conf.GetConf().TAOS.User,
		conf.GetConf().TAOS.Pass, conf.GetConf().TAOS.Schema)
	glog.FPrint("Connect to tdegine", conf.GetConf().TAOS.Schema)
}

// InitPool func base DB pool
func NewPool(address, port, user, password, schema string) *SQLConnPool {
	dataSourceName := fmt.Sprintf("%s:%s@/tcp(%s:%v)/%s", user, password, address, port, schema)

	db := &SQLConnPool{
		DriverName:     "taosSql",
		DataSourceName: dataSourceName,
		MaxIdleConns:   100,
		MaxOpenConns:   1000,
	}
	if err := db.Open(); err != nil {
		panic(err)
	}
	return db
}

func (p *SQLConnPool) Open() error {
	var err error
	p.SQLDB, err = sql.Open(p.DriverName, p.DataSourceName)
	if err != nil {
		return err
	}
	if err = p.SQLDB.Ping(); err != nil {
		return err
	}
	p.SQLDB.SetMaxOpenConns(p.MaxOpenConns)
	p.SQLDB.SetMaxIdleConns(p.MaxIdleConns)
	p.SQLDB.SetConnMaxLifetime(time.Hour * 4)
	return nil
}

func GetConn() *SQLConnPool {
	return dbConn
}

// Close pool
func (p *SQLConnPool) Close() error {
	return p.SQLDB.Close()
}

// Insert via pool
func (p *SQLConnPool) Insert(insertStr string, args ...interface{}) (int64, error) {
	stmt, err := p.SQLDB.Prepare(insertStr)
	if err != nil {
		return 0, err
	}
	defer stmt.Close()

	result, err := stmt.Exec(args...)
	if err != nil {
		return 0, err
	}
	affect, err := result.RowsAffected()
	return affect, err
}

func (p *SQLConnPool) Get(queryStr string, args ...interface{}) (map[string]interface{}, error) {
	stmt, err := p.SQLDB.Prepare(queryStr)
	if err != nil {
		return map[string]interface{}{}, err
	}
	defer stmt.Close()

	rows, err := stmt.Query(args...)
	if err != nil {
		if err == sql.ErrNoRows {
			return map[string]interface{}{}, nil
		}
		return map[string]interface{}{}, err
	}
	defer rows.Close()

	//将查询结果集Scan到map
	result := make([]map[string]interface{}, 0, 10)
	columns, _ := rows.Columns()
	for rows.Next() {
		value := make([]interface{}, len(columns))
		columnPointers := make([]interface{}, len(columns))
		for i := 0; i < len(columns); i++ {
			columnPointers[i] = &value[i]
		}

		rows.Scan(columnPointers...)
		data := make(map[string]interface{})
		for i := 0; i < len(columns); i++ {
			columnName := columns[i]
			columnValue := columnPointers[i].(*interface{})
			data[columnName] = *columnValue
		}
		result = append(result, data)
	}
	if len(result) > 0 {
		return result[0], nil
	}
	return nil, nil
}

// Query via pool
func (p *SQLConnPool) Query(queryStr string, args ...interface{}) ([]map[string]interface{}, error) {
	stmt, err := p.SQLDB.Prepare(queryStr)
	if err != nil {
		return []map[string]interface{}{}, err
	}
	defer stmt.Close()
	rows, err := stmt.Query(args...)
	if err != nil {
		if err == sql.ErrNoRows {
			return []map[string]interface{}{}, nil
		}
		return []map[string]interface{}{}, err
	}
	defer rows.Close()

	//将查询结果集Scan到map
	result := make([]map[string]interface{}, 0, 10)
	columns, _ := rows.Columns()
	for rows.Next() {
		value := make([]interface{}, len(columns))
		columnPointers := make([]interface{}, len(columns))
		for i := 0; i < len(columns); i++ {
			columnPointers[i] = &value[i]
		}

		rows.Scan(columnPointers...)
		data := make(map[string]interface{})
		for i := 0; i < len(columns); i++ {
			columnName := columns[i]
			columnValue := columnPointers[i].(*interface{})
			data[columnName] = *columnValue
		}
		result = append(result, data)
	}
	return result, nil
}
```

简单查询：
```
sql := `select max(time) time,did from xj_ali_point where did = ? and run_id = ?`
	mp, err := db.GetConn().Get(sql, did, runId)

	if err != nil {
		return nil, err
	}

	resultSql := `select * from xj_ali_point where did = ? and run_id = ? and time = ?`
	res, err := db.GetConn().Get(resultSql, did, runId, mp["time"])
```

taos默认udp连接运行是没有问题的， 但是项目打包在docker内，就有之前提过的阻塞问题
然后我这面把udp改成tcp连接后，阻塞问题解决了
现在项目跑5分钟左右 就会自动终止 异常信息就是**Segmentation fault (core dumped)**，大概插入十万条数据 执行select语句大概 每执行一次insert 语句大概会伴随执行四次select 去处理一些逻辑

**Comment by liu0x54** [comment]
代码不全，看不太出来；不过你这dbconn是不是多个线程共享？试着每个goroutine获取一个连接去操作，不要多goroutine共享dbconn

**Comment by huangheding** [comment]
> 代码不全，看不太出来；不过你这dbconn是不是多个线程共享？试着每个goroutine获取一个连接去操作，不要多goroutine共享dbconn

每个goroutine获取一个新连接，每执行一次db操作都open conn - close conn 是这样吗？

**Comment by liu0x54** [comment]
> > 代码不全，看不太出来；不过你这dbconn是不是多个线程共享？试着每个goroutine获取一个连接去操作，不要多goroutine共享dbconn
> 
> 每个goroutine获取一个新连接，每执行一次db操作都open conn - close conn 是这样吗？

是的

**Comment by liu0x54** [comment]
另外，你之前的问题docker里阻塞，可能是docker启动时端口映射的问题，你显式的把6030-6039端口用UDP、TCP都映射一遍试试

**Comment by huangheding** [comment]
> 另外，你之前的问题docker里阻塞，可能是docker启动时端口映射的问题，你显式的把6030-6039端口用UDP、TCP都映射一遍试试

docker阻塞  是项目跑在docker中也就是客户端在docker中访问宿主机的server， 客户端还要映射端口吗？

**Comment by huangheding** [comment]
> 另外，你之前的问题docker里阻塞，可能是docker启动时端口映射的问题，你显式的把6030-6039端口用UDP、TCP都映射一遍试试

我加一下您微信吧 方便不方便

**Comment by liu0x54** [comment]
你有我们同事的微信吗？找他要一下我的微信号吧

**Comment by huangheding** [comment]
> 你有我们同事的微信吗？找他要一下我的微信号吧

OK

**Comment by huangheding** [comment]
> 另外，你之前的问题docker里阻塞，可能是docker启动时端口映射的问题，你显式的把6030-6039端口用UDP、TCP都映射一遍试试

连接方式换成您说的单次open close了 ，还是同样的问题
贴一下简单的查询代码
```
sql := `select max(time) time,did from xj_ali_point where did = ? and run_id = ?`
	mp, err := db.GetConn().Get(sql, did, runId)

	if err != nil {
		return nil, err
	}

	resultSql := `select * from xj_ali_point where did = ? and run_id = ? and time = ?`
	res, err := db.GetConn().Get(resultSql, did, runId, mp["time"])
	if err != nil {
		return nil, err
	}
	return parsePointCase(res), nil
```

**Comment by huangheding** [comment]
将taosd版本降回1659解决了问题
