### ISSUE TITLE
(v3.0.3.0) 3-node cluster, 2 dnodes and 1 mnode+dnode - mnode went down and won't come back up

### ISSUE THREAD

**Issue by wzm20191010** [taosdata/TDengine#25351]
**Bug Description**

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**
![Uploading 1712904894380.jpg…]()
[
![11115](https://github.com/taosdata/TDengine/assets/54854351/8a27e2ac-5c78-467f-a82a-510fcb82057e)
](url)

**Environment (please complete the following information):**
%Cpu(s):  0.2 us,  0.3 sy,  0.0 ni, 99.5 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 16265908 total,   568052 free,   786204 used, 14911652 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 15132308 avail Mem 
[root@Tdengine-1 taos]# df -h
Filesystem                      Size  Used Avail Use% Mounted on
devtmpfs                        7.8G     0  7.8G   0% /dev
tmpfs                           7.8G     0  7.8G   0% /dev/shm
tmpfs                           7.8G  9.0M  7.8G   1% /run
tmpfs                           7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/mapper/centos_centos-root   96G   93G  3.6G  97% /
/dev/sda2                       4.0G  150M  3.9G   4% /boot
/dev/mapper/data--vg-data--lv   6.0T  1.9T  4.2T  32% /data
tmpfs                           1.6G     0  1.6G   0% /run/user/0
[root@Tdengine-1 taos]# 

 - TDengine Version  3.0.3.0

**Additional Context**

**Comment by yu285** [comment]
mnode needs to be three to assure high-availability
