### ISSUE TITLE
Error 113: TDengine.Query(conn, sql)

### ISSUE THREAD

**Issue by wangfd83** [taosdata/TDengine#2536]
我做了这个测试
create database db tables 4000;
![image](https://user-images.githubusercontent.com/66345837/86359577-be806c80-bca3-11ea-9e87-a914df76c8e4.png)
 当i=4000的时候，TDengine.Query(conn, sql)就返回113错误，会持续一段时间，一直报113

重新删除database,create database db tables 3000;
 当i=3000的时候，TDengine.Query(conn, sql)就返回113错误，继续持续一段时间，一直报113

**Comment by Aries-Lee1991** [comment]
OK, we'll check it.

**Comment by liuyq-617** [comment]
接口，版本？

**Comment by wangfd83** [comment]
1.6.5.9, 32位taos.dll, C#demo

**Comment by liuyq-617** [comment]
这个是你自己封装的代码吧，113错误码是无效的提交信息，可以在shell中查询一下测试

**Comment by wangfd83** [comment]
我没有做过封装的，就是创建连接后，我循环的执行插入操作



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yiqing Liu"<notifications@github.com&gt;; 
发送时间: 2020年7月6日(星期一) 中午11:33
收件人: "taosdata/TDengine"<TDengine@noreply.github.com&gt;; 
抄送: "枫"<3120297937@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [taosdata/TDengine] Error 113: TDengine.Query(conn, sql) (#2536)





 
这个是你自己封装的代码吧，113错误码是无效的提交信息，可以在shell中查询一下测试

**Comment by wangfd83** [comment]
这个是TDengine的bug哦


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yiqing Liu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月6日(星期一) 中午11:33
收件人:&nbsp;"taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送:&nbsp;"枫"<3120297937@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [taosdata/TDengine] Error 113: TDengine.Query(conn, sql) (#2536)





 
这个是你自己封装的代码吧，113错误码是无效的提交信息，可以在shell中查询一下测试
