### ISSUE TITLE
windows下用java远程连接linux上数据库要怎么操作？

### ISSUE THREAD

**Issue by fanrong1993** [taosdata/TDengine#254]

**Comment by hechaotudou** [comment]
<dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>1.0.0</version>
        </dependency>
请问Java的连接mysql的jdbc这个在哪里可以下载到，

**Comment by guanshengliang** [comment]
请到www.mysql.com下载mysql的jdbcdriver

**Comment by guanshengliang** [comment]
TDengine的jdbcdriver，在windows平台和linux平台并没有不同，差别仅在于windows需要使用taos.dll，而linux需要使用libtaos.so.

**Comment by hechaotudou** [comment]
> TDengine的jdbcdriver，在窗口平台和Linux的平台并没有不同，差别仅在于窗户需要使用taos.dll，而在linux需要使用libtaos.so。

TDengine taos-jdbcdriver-x.x.x.jar为Enterprise Java开发人员提供JDBC驱动程序。TDengine的JDBC驱动程序是作为标准JDBC 3.0规范的子集实现的，并支持最常见的Java开发框架。驱动程序当前未发布到在线依赖性存储库（如Maven Center Repository），用户应手动将.jar文件添加到其本地依赖性存储库。
TDengine taos-jdbcdriver-x.x.x.jar这个哪里有 或者哪里可以下载，？

**Comment by fanrong1993** [comment]
@hechaotudou 在安装目录下/connector/jdbc/下或者安装包里面也有/connector/

**Comment by hechaotudou** [comment]
@fanrong1993 我只看到个这个  taos-jdbcdriver-1.0.0-dist.jar， 你们可以单独发我邮件吗  太难找了

**Comment by fanrong1993** [comment]
@hechaotudou 就是这个啊taos -jdbcdriver-1.0.0-dist.jar，你不是找到了么

**Comment by Luozde** [comment]
您好，我在windows下的Java连接远程的Linux数据库遇到下面这个错误 Error: invalid time stamp
在windows cmd上连接远程数据库也同样遇到这个错误Error: invalid time stamp，请问该怎么处理？

---------------windows10 cmd命令行下连接远程Linux数据库错误----------------------------
c:\TDengine>taos -h 192.168.182.128
TSDB error: invalid time stamp

---------------windows10 Java连接远程Linux数据库错误--------------------------------------
java.sql.SQLException: TDengine Error: invalid time stamp
	at com.taosdata.jdbc.TSDBJNIConnector.connect(TSDBJNIConnector.java:96)
	at com.taosdata.jdbc.TSDBConnection.connect(TSDBConnection.java:64)
	at com.taosdata.jdbc.TSDBConnection.<init>(TSDBConnection.java:56)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:135)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at TestTDengine.App.getConn(App.java:39)
	at TestTDengine.App.main(App.java:20)
option file:/etc/taos/taos.cfg not found, all options are set to system default

**Comment by kingLi88** [comment]
我也遇到这个问题。windows上java代码连不上linux的数据库。 jar已经放到工程了。

**Comment by guanshengliang** [comment]
1. 在windows上调试TDengine的Java客户端程序，需要下载安装TDengine的Windows客户端，TDengine的JDBCDriver通过taos.dll完成与TDengine服务端的通信
2. 先确保通过taos.exe能够连接到linux服务端，然后再调试java程序
3. 调试前，可以先将防火墙全部关闭，包括windows的防火墙和linux防火墙，以确定是防火墙问题还是网络本身不通

**Comment by rainmaple** [comment]
低版本如1.0.1的jdbcdriver在安装目录下的确有，但是开发时会遇上版本不匹配的错误，有高版本的driver提供么
