### ISSUE TITLE
When replace the default data directory, error in querying STable

### ISSUE THREAD

**Issue by 18268889381** [taosdata/TDengine#2540]
**Bug Description**
过程
1、rpm方式安装TDengine
版本1.6.5.5和版本1.6.6.5都尝试过
2、修改/etc/taos/taos.cfg
dataDir修改为 /home/data/taos
3、启动taosd
systemctl start taosd

错误
超级表中数据只有几千条
查询超级表根据ts倒叙（正序是正常），会报下面的错
![ff10d5537fffd8f22fa0866e0bb6246](https://user-images.githubusercontent.com/28639191/86423877-844eb380-bd13-11ea-861e-baab82968e44.png)

安装后数据目录与默认安装不同点
1、原来默认安装tsdb会建立到data的软链接
2、跟换数据目录后tsdb没有建立到data的软链接

**Environment (please complete the following information):**
 - OS:  CentOS 7.0
 - Memory：128, CPU:40, current Disk Space:1.4T
 - TDengine Version 1.6.5.5及1.6.6.0

**Additional Context**

**Comment by Aries-Lee1991** [comment]
您好，这需要涉及数据迁移，刚好也是我们最近搞的一个活动。您可以看看，报名一下：http://taosdata.mikecrm.com/gwzXF7x
