### ISSUE TITLE
(v3.0.5.1) Max row length is only 16000+, not 65531 as documented

### ISSUE THREAD

**Issue by hufeng-tany** [taosdata/TDengine#25431]
执行的sql：
taos> CREATE STABLE IF NOT EXISTS testdbname.testlength3 (datatime TIMESTAMP,data_model1 NCHAR(16302),data_mode21 NCHAR(1111)) TAGS (keynchar(64),vernchar(64));
错误返回：
DB error: Row length exceeds max length 65531 (0.000000s)
可以计算出，上面的一行数据，只有1.7万个字符；就提示超过了65531了？？
去掉第二个字段，可以建表成功：
 CREATE STABLE IF NOT EXISTS testdbname.testlength3 (datatime TIMESTAMP,data_model1 NCHAR(16302)) TAGS (keynchar(64),vernchar(64));
 所以涛思此版本，实际的行数只有1.63W+。
具体值没有细测。
未达到说明你的64KB

**Comment by yu285** [comment]
varchar/binary 是65531， nchar 用于存储中文等非ascii 自负，需要除以4 ，所以大概是1.63w+
