### ISSUE TITLE
taosdump -A freezes

### ISSUE THREAD

**Issue by systemChina** [taosdata/TDengine#25464]
**Bug Description**
![image](https://github.com/taosdata/TDengine/assets/18650479/fead213b-e09e-4a4e-ab81-69c75066fc59)
一直卡在这个地方了。

**To Reproduce**
1. 第一次导出正常
2. 删除大部分超级表中的一半数据 delete from xx where ts < xx
3. 导出异常，卡住了

**Screenshots**
![06bd447f1e9df4a131012771b3cb6d4](https://github.com/taosdata/TDengine/assets/18650479/e2a2a216-c4da-4027-a4b4-88b6beaba7d8)

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory 32G , CPU 16核, current Disk Space 1T
 - TDengine Version [3.2.0.0]

**Comment by yu285** [comment]
这个是不是从 3.0.x 版本导出来的数据？是的话，需要先升级一下。再导出。

我先关闭此问题，有问题可以加微信 a15652223354
