### ISSUE TITLE
Delete the table under the STable, the disk resource is not released.

### ISSUE THREAD

**Issue by crazy11586** [taosdata/TDengine#2546]
-- sql
drop table sub_16621588895186587733;

目前, 机器上的磁盘空间已经严重不足了, 想删除表里面的部分数据，但是删除子表后发现磁盘资源的不到释放, 有几个问题：
现象是否正常？
删除子表之后，需要通过其他的命令来释放资源吗？
有没有其他的方式删除表里面的部分数据？

谢谢

**Comment by Aries-Lee1991** [comment]
您好，这个现象是正常的，超级表下面的子表数据都在一起，资源回收的时候，也是一起回收的，单个回收的话，代价太大了。

**Comment by crazy11586** [comment]
有什么办法能让taosd主动回收资源吗？比如修改数据保留时间 “keep”, 从30天改成20天

**Comment by Aries-Lee1991** [comment]
请参考一下这个Issue：https://github.com/taosdata/TDengine/issues/2565
