### ISSUE TITLE
How can I aggregate data in different time zones on an hourly basis?

### ISSUE THREAD

**Issue by chessplay** [taosdata/TDengine#25485]
我的明细表字段如下:gather_time,total_users,utc_code,我想要根据不同的utc_code来判断当前时区是否到达0点，如果到达0点，则对total_user进行天聚合，如果不区分utc_code每个小时聚合会造成计算资源上的浪费。这种情况下sql要怎么写，select sum(total_users) from table where utc_code=getCurrentUtcCode(NOW) interval(1d) sliding(1h),getCurrentUtcCode()是我的udf，这样好像不行，这样某个utc_code的数据每个小时都会有一份，我只需要天级别的数据，如果把不同时间的数据分开到不同的表又很麻烦，请问有没有什么简介高效的方法

**Comment by GaN601** [comment]
> 我的明细表字段如下：gather_time，total_users，utc_code，我想要根据不同的utc_code来判断当前时区是否到达0点，如果到达0点，则对total_user进行天聚合，如果不区分utc_code每个小时聚合会造成计算资源上的浪费。这种情况下sql要怎么写，select sum（total_users） from table where utc_code=getCurrentUtcCode（NOW） interval（1d） sliding（1h），getCurrentUtcCode（）是我的udf，这样好像不行，这样某个utc_code的数据每个小时都会有一份，我只需要天级别的数据，如果把不同时间的数据分开到不同的表又很麻烦，请问有没有什么简介高效的方法

每个小时激活一次, 每小时整不是意味着必定有一个时区是0点么. 然后将服务器当前小时计算成对应的时区code
