### ISSUE TITLE
Are temporary result sets supported for nested queries?

### ISSUE THREAD

**Issue by foow123** [taosdata/TDengine#25482]
例如如下SQL语法：
SELECT * FROM ( VALUES ( 1 ), ( 2 ) ) AS temp(col1) ........
TDEngine中似乎找不到对应的语法，请问TDEngine中是否有对应构建临时结果集的方法，或者以后有没有计划添加？

**Comment by yu285** [comment]
可以看下嵌套查询是否满足。

**Comment by foow123** [comment]
是，嵌套查询可以完成，我现在就是这么处理的，但这需要先创建一个临时表，然后将数据写入，再进行嵌套查询，最后再将临时表删除，而我仅仅只需要生成一个结果集进行数据处理而已，现在这种处理方式感觉太麻烦了

**Comment by yu285** [comment]
不好意思，没有太理解哈。嵌套查询不会创建临时表，再删除呢。不可以直接用select xxx from (select xxx ) 直接返回最终结果集吗？

**Comment by foow123** [comment]
中间查询的那部分临时数据并不保存在TDEngine中，只是其它模块请求时使用的参数，查询语句是从postgresql移植过来的，所以向问下是否有相应的查询方法

**Comment by yu285** [comment]
这个确实没有
