### ISSUE TITLE
请教关于TDengine预计算的设计

### ISSUE THREAD

**Issue by Irene1007** [taosdata/TDengine#255]
我想问一下TDengine预计算的设计。
1.比如说，一共100天数据，你们是不是预先对每个可能的一个或多个tag的组合，对每一个非tag的列都进行了所有聚合函数的预计算？
2.这些预计算是在什么时间区间的？
3.如果还有其他一些过滤条件，是不是预计算就无效了？
4.预计算是在什么时间进行的？数据写入的时候进行的吗？
如果能够在文档上仔细地说明这些，其实我们在使用的时候能够更加明确、合理地设计表结构、设定相关tag，感谢！

**Comment by guanshengliang** [comment]
1.预计算只和单一的数据字段有关，与tag及其组合无关
2.预计算只对落盘数据块生效
3.有些过滤条件的情况下，预计算确实不起作用，但要视具体的SQL语句来分析
4.预计算是在写数据的同时进行的
总结：在设计数据模型的时候，无需考虑预计算，两者之前没有直接关联；即便在完全没有可能使用预计算的场景，例如拉取某设备的全部数据，TD的速度依然很快。

**Comment by TS668** [comment]
所以TDengine是对每一数据字段每一个时间区间在写入时进行预计算吗？这个预计算的时间区间是多长？

**Comment by hjxilinx** [comment]
是针对每个落盘以后的data block，不是一个固定的时间区间。

**Comment by Irene1007** [comment]
请问data block指的是一张表就是一个data block吗？落盘是一个什么概念？隔多少时间进行一次落盘？是每次我新追加了一条数据就进行一次落盘吗？还是到了数据每增加到一定程度就进行一次落盘？初学者，不是很了解底层设计，望指教，谢谢！

**Comment by hjxilinx** [comment]
一张表包含了若干个data block。落盘就是在内存的缓存中的数据flush 到disk中，形成了 data block。默认落盘间隔时间是1个小时。

落盘受到写入记录和时间的双重影响。
缓存的中数据达到一定的程度就开始落盘，即使没有到1个小时。同时，即使只写了一条记录，到了一个小时也会触发落盘操作。
