### ISSUE TITLE
(v3.0.5.1) show tables statement includes duplicate tables - of 2000 subtables, 2122 were returned, making 122 duplicates

### ISSUE THREAD

**Issue by hufeng-tany** [taosdata/TDengine#25519]
问题情景：
我建立了1个超表和超表的2000个子表；
持续写入测试中，发送show tables返回表数量为2122个
查看超表的tag的sqlSHOW TABLE TAGS FROm stb_mode1 549861283852189696>>E:\TIG.CSV;返回的也是重复2122条
![595324e9d2d227c41a3fe8027b7207c](https://github.com/taosdata/TDengine/assets/59222444/a6b40826-325e-4248-9397-dfdf7203ee45)
[
[TIG.CSV](https://github.com/taosdata/TDengine/files/15126068/TIG.CSV)
](url)

**Comment by yu285** [comment]
可以升级到 3.2.3.0 再查看一下，如果还有问题可以加微信 a15652223354 具体沟通
