### ISSUE TITLE
响应失败

### ISSUE THREAD

**Issue by liujinsheng** [taosdata/TDengine#2552]
s_gps超级表存千万的设备位置数据。
warning是报警类型，一共32种报警，长度为32字符串，报警为1不报警为0。
业务需求会根据vid、pid等tag，groupby统计数量。
for循环以下sql语句，like会从第一位到32位赋1。
select count(ts) as count from db.s_gps  where warning like '______1_________________________'  and ts>'2020-06-23 00:00:00' and ts < '2020-06-23 23:59:59' group by vid ,client_code , pid ,eid ,oid ,admdivcode ,industry_id 
请求频繁，数据库响应失败或者数据库直接崩掉。

**Comment by Aries-Lee1991** [comment]
@liujinsheng 你之前提过一个关于这个的问题，可以直接在下面追加，我们已经有工程师跟踪那个问题了。

**Comment by Aries-Lee1991** [comment]
帮您追加到另外一个问题下面了，这个问题就给您关掉了。
