### ISSUE TITLE
connection reset

### ISSUE THREAD

**Issue by NoFlyLonely** [taosdata/TDengine#25537]
mac m3 docker部署tdenginge后，docker容器访问taos没有问题，宿主机器用dbeaver访问显示connection reset
![image](https://github.com/taosdata/TDengine/assets/50352490/2c192737-e06c-44d0-be3c-bd11327ddd1c)
![image](https://github.com/taosdata/TDengine/assets/50352490/2129ad79-4809-464d-8dcf-754ec0a61144)

**Comment by maxy19** [comment]
我也遇到这个问题 有人帮忙看下吗 我是m1 mac 连不上 报同样错误

**Comment by yu285** [comment]
确保taosadapter 启动，使用 6041端口，使用dist 包 https://repo1.maven.org/maven2/com/taosdata/jdbc/taos-jdbcdriver/3.2.11/
