### ISSUE TITLE
c++ sdk can't insert data

### ISSUE THREAD

**Issue by dearbird** [taosdata/TDengine#25533]
@yu285 
c++客户端连接，连接成功，打印双方版本好正常：
I0427 18:07:48.374 719 taos_conn.cc:27] Connected to TDengine, client: 3.2.3.0
I0427 18:07:48.374 719 taos_conn.cc:28] Connected to TDengine, server: ver:3.2.3.0
build:Built Linux-x64 at 2024-02-29 18:01:09 +0800
gitinfo:e27fdcff254b7bd0e0ad2f825e0414da4c0f37dc

但是无法插入数据时，中间卡住20s以上
I0427 18:07:48.374 719 taos_db.cc:46] ==> start insert, SQL: INSERT INTO device100000001 USING device TAGS(1) VALUES (1713707448959, 0.0, 0.0, 0.0, 8, 0.0, 0.0, 0.0, 0.0,0.0, 0.0, 0, 0, 0, 0, 0,0.0,0.0, 0, 0, 0)
W0427 18:08:05.297 719 taos_conn.cc:49] Failed to exec TDengine: some vnode/qnode/mnode(s) out of service
I0427 18:08:05.297 719 taos_db.cc:49] Failed to insert data into database: INSERT INTO device100000001 USING device TAGS(1) VALUES (1713707448959, 0.0, 0.0, 0.0, 8, 0.0, 0.0, 0.0, 0.0,0.0, 0.0, 0, 0, 0, 0, 0,0.0,0.0, 0, 0, 0)

检测 taos 日志输出
04/27 18:08:38.137279 00000740 RPC ERROR TSC msg heartbeat failed to send, conn 0x7fbacfd65c50 failed to connect to LAPTOP-AK5M6V5M:6030, reason: address not available, gtid:0xf422cb06fd3d550d:0x23eb31f06fda5507
04/27 18:08:38.137284 00000740 UTL ERROR sched is already stopped, msg:0x7fbaed7eff80 is dropped
04/27 18:08:38.137285 00000740 TSC ERROR failed to sched msg to tsc, tsc ready to quit

直接 taos 连接， 插入数是正常，但是c++连接无法插入数据。

**Comment by yu285** [comment]
请问数据库的版本号是？

**Comment by yu285** [comment]
加微信具体排查吧 a15652223354
