### ISSUE TITLE
Server 3.2.3.0 JDBC returns syntax error when a comment is added

### ISSUE THREAD

**Issue by richwxd** [taosdata/TDengine#25540]
```
ALTER STABLE device_property MODIFY COLUMN event_time timestamp COMMENT '上报时间';
```
报错 DB error: syntax error near "comment '上报时间';" (0.001009s)

原始表例子
···
CREATE STABLE IF NOT EXISTS device_property ( event_time timestamp, motdcvoltage2 FLOAT, motdccurrent2 FLOAT) TAGS (device_id NCHAR(50));
···

**Comment by yu285** [comment]
暂时还不支持字段级别的comment
