### ISSUE TITLE
TDengine 3.2.0.0/3.1.0.0 can't  support Ningsi80.2020 version

### ISSUE THREAD

**Issue by Zander-W** [taosdata/TDengine#25573]
TDengine 3.2.0.0/3.1.0.0 can't  support Ningsi80.2020 version
show that:
start to init dnode  env
succeed to read dnode /home/taos/data/dnode/dnode.json
succeed to read mnode /home/taos/data/mnode/mnode.json
deploy mnode required. option deploy:1
file:/home/taos/data/qnode/qnode.json not exist
file:/home/taos/data/snode/snode.json not exist
ERROR failed to create dnode since Not found
ERROR failed to init dnode since unsupported platform, please visit https://www.taosdata.com for support
<img width="641" alt="1714373630305" src="https://github.com/taosdata/TDengine/assets/57083268/9287bb4a-7f35-45f7-b4f1-0e4c4d5bb094">
<img width="1244" alt="d1382121b1ad9a4021b5bf49e4c6f8c" src="https://github.com/taosdata/TDengine/assets/57083268/2977872f-9b38-4e19-903d-1ffd61201e12">
![1714373730762](https://github.com/taosdata/TDengine/assets/57083268/45429c69-62d4-4492-bedb-b5e896d6087f)

**Comment by Zander-W** [comment]
<img width="713" alt="7a777796a89f367c0458ee207ca8569" src="https://github.com/taosdata/TDengine/assets/57083268/37c49e60-57a7-433c-a001-d4e5b6920020">
<img width="723" alt="1b6e6a668605de949ee8c439c0add67" src="https://github.com/taosdata/TDengine/assets/57083268/378bf307-5854-4c7a-970c-7ecbd17b5e64">
新版凝思系统也是不支持了

**Comment by yu285** [comment]
开源版确实不支持了，可以考虑换操作系统。确实换不了可以考虑docker
