### ISSUE TITLE
show users; allowed_host 127.0.0.1 - how can I modify to enable remote connections?

### ISSUE THREAD

**Issue by southfly** [taosdata/TDengine#25622]
**客户端远程连接问题**
我在Linux服务器上使用apt安装了服务，并添加用户，想使用远程连接，这个需要怎么配置、修改？
![image](https://github.com/taosdata/TDengine/assets/28092819/dc429e2f-a4fc-433e-acce-1f11f96f75b8)
本地windows客户端连接，本地配置了firstEP IP地址:端口(服务端防火墙已允许)
![image](https://github.com/taosdata/TDengine/assets/28092819/6e483a4c-8935-4dbb-a0ea-4e8f865d5c90)
3.0版本的文档，这块描述不是很清楚，建议完善一下。关于用户管理、用户权限这块。

**Comment by yu285** [comment]
连接问题 https://www.taosdata.com/engineering/11076.html 看下问题1 排查一下即可确保使用。

更多的用户管理和权限属于企业版范畴。
