### ISSUE TITLE
typo in keyword on table description doc

### ISSUE THREAD

**Issue by GaN601** [taosdata/TDengine#25621]
https://docs.taosdata.com/taos-sql/table/
![image](https://github.com/taosdata/TDengine/assets/80253667/0c93e169-3e25-4e54-a081-7025ba93a8ec)
PRIAMRY KEY?  primary key?

**Comment by jtao1735** [comment]
Thanks for pointing out this typo. At the end of the each document page, there is a link "edit this page", please click this link and submit the changes. We would like to accept your pull request. Thanks.
