### ISSUE TITLE
TDengine运行一年左右，一直频繁重启

### ISSUE THREAD

**Issue by elysian-gc** [taosdata/TDengine#25624]
**Bug Description**
TDengine运行一年左右，一直频繁重启

**To Reproduce**
1. none

**Expected Behavior**
不发生重启现象

**Screenshots**

core 文件显示：
![image](https://github.com/taosdata/TDengine/assets/44466800/ff6c4236-1df4-404f-b0bd-4775c7566063)

**Environment (please complete the following information):**
 - OS: 5.10.179-171.711.amzn2.aarch64
 - Memory, CPU, current Disk Space: 正常
 - TDengine Version : 3.0.5.1

**Additional Context**
none

**Comment by jtao1735** [comment]
Since 3.0.5, TDengine has many bugs fixed, please upgrade into the latest version

**Comment by jtao1735** [comment]
If you still encounter crashes in the latest release, please post it on GitHub, we would like to help you out
