### ISSUE TITLE
Does C# client use connection pooling?

### ISSUE THREAD

**Issue by moaazassali** [taosdata/TDengine#25623]
I have looked through the source code here: https://github.com/taosdata/taos-connector-dotnet, and I don't see anything about connection pooling in the constructors or Open() method for TDEngineConnection, DbDriver or NativeClient.

What is the best strategy to use TDEngine client in c# then? Should I implement my own connection pooling class?

In case I missed/misunderstood something in the C# adapter code, I also implemented my own connection pool queue and the performance gains are obvious. Opening a connection before would take around 1.5ms but now its like 0.005ms with my connection pool.

**Comment by huskar-t** [comment]
C# connector does not use a connection pool and creates a connection every time `Open` is called.
