### ISSUE TITLE
TDengine 3.2.3.0 not reporting metrics to Taoskeeper, 404 on /general-metric

### ISSUE THREAD

**Issue by hasland** [taosdata/TDengine#25625]
**Bug Description**
Using TDengine 3.2.3.0 and TaosKeeper 1.0.17 results in tdengine sending data to `/general-metric` endpoint and taoskeeper returns a 404.

Taoskeeper log with TDengine 3.2.3.0:
```
[GIN] 2024/05/03 - 17:32:31 | 404 |         3.1µs |     10.244.7.74 | POST     "/general-metric"
[GIN] 2024/05/03 - 17:32:32 | 404 |         1.7µs |     10.244.7.74 | POST     "/general-metric"
[GIN] 2024/05/03 - 17:32:32 | 404 |         1.2µs |     10.244.7.74 | POST     "/general-metric"
[GIN] 2024/05/03 - 17:32:33 | 404 |         1.1µs |     10.244.7.73 | POST     "/general-metric"
[GIN] 2024/05/03 - 17:32:37 | 404 |           1µs |     10.244.7.74 | POST     "/general-metric"
```

**To Reproduce**
Install TDEngine 3.2.3.0 and Taoskeeper 1.0.17 and configure monitoring.

**Expected Behavior**
Taoskeeper returns 200 status code on /report (as it was in 3.2.0.0 and 3.2.2.0).

**Environment (please complete the following information):**
 - TDengine Version: 3.2.3.0
 - Taoskeeper version: 1.0.17

On TDengine 3.2.0.0 and 3.2.2.0 with the same Taoskeeper (1.0.17) it's working as expected:
Taoskeeper log with TDengine 3.2.0.0 (same with 3.2.2.0):
```
[GIN] 2024/05/03 - 17:35:13 | 200 |   53.462018ms |     10.244.0.52 | POST     "/report"
[GIN] 2024/05/03 - 17:35:15 | 200 |  1.109326389s |     10.244.0.53 | POST     "/report"
[GIN] 2024/05/03 - 17:35:39 | 200 |   62.352042ms |     10.244.0.51 | POST     "/report"
[GIN] 2024/05/03 - 17:35:43 | 200 |   52.433205ms |     10.244.0.52 | POST     "/report"
[GIN] 2024/05/03 - 17:35:45 | 200 |  679.043129ms |     10.244.0.53 | POST     "/report"
```

**Comment by yu285** [comment]
TDengine 3.2.3.0 use same version taoskeeper as 3.2.2.0 ? both 1.0.17?

**Comment by hasland** [comment]
Looks like [Taoskeeper](https://github.com/taosdata/taoskeeper) repo doesn´t always add a release, they just create a tag. So I've downloaded the tag [3.3.2.0](https://github.com/taosdata/taoskeeper/tree/ver-3.3.2.0), built it, and deployed this updated version. It worked as expected.

I think they should update the README to include clear instructions about new versions.
