### ISSUE TITLE
3.2.2.0升级到3.2.3.0，grafana 18180（tdinsight-for-3-x）模板无法使用

### ISSUE THREAD

**Issue by tonyfeel** [taosdata/TDengine#25643]
3.2.2.0升级到3.2.3.0，grafana 18180 模板无法使用，log库表结构及表名均有变更。

插件Version 3.5.0

![aaa](https://github.com/taosdata/TDengine/assets/99962401/08be7af7-078d-496d-8b34-2e564a2d6013)

**Comment by yu285** [comment]
我们看下

**Comment by yu285** [comment]
使用问题：

“我是直接在grafana里面import的18180模板，这个模板还是老版本的。另外可以从td数据源的页面导入，这个模板是新的，从这里导入就好了。”
