### ISSUE TITLE
Can‘t query data from table after databases config change

### ISSUE THREAD

**Issue by kakaroy123** [taosdata/TDengine#25648]
**General Questions**

After change some config of a exist database and reboot tdengine,  i can not query any data from table in this database through my python file. Why??

**Comment by yu285** [comment]
you need more specific error code or capture here

**Comment by kakaroy123** [comment]
> you need more specific error code or capture here

this file can run succussfully before database config change.

**Comment by yu285** [comment]
you need let us know what you changed
