### ISSUE TITLE
recommend unifying placeholder names in docs

### ISSUE THREAD

**Issue by haroldyong** [taosdata/TDengine#25647]
既然已经定义了超级表的概念，那么就应该全部文档中的超级表应该统一，比如

比如创建索引，原文档（https://docs.taosdata.com/taos-sql/tag-index/）是这样写的“ CREATE INDEX index_name ON tbl_name (tagColName）”

建议

CREATE INDEX index_name ON stbl_name (tagColName）

使用stbl代替 tbl

**Comment by yu285** [comment]
Thanks for your advice! we will consider about this
