### ISSUE TITLE
关于总量查询

### ISSUE THREAD

**Issue by Carson-yy** [taosdata/TDengine#25652]
数据量很大的时候，如何统计总共多少条数据了？count(*)执行不出来了！

**Comment by yu285** [comment]
一般查询慢主要这几个原因：

1.数据被大量相同时间戳的数据覆盖过，导致碎片多，开源版数据导出再导入就行了。（企业版支持在线重组）

2.乱序比较多。

3. 数据库建模优化不够，可以参考：https://www.taosdata.com/tdengine-engineering/21550.html

4.最好在最新版（当前为 3.3.0.0）上测试，确保数据库本身版本处于最优。

5.最好在服务端测试，确保没有网络等其他因素干扰。

**Comment by Carson-yy** [comment]
> 一般查询慢主要这几个原因：
> 
> 1.数据被大量相同时间戳的数据覆盖过，导致碎片多，开源版数据导出再导入就行了。（企业版支持在线重组）
> 
> 2.乱序比较多。
> 
> 3. 数据库建模优化不够，可以参考：https://www.taosdata.com/tdengine-engineering/21550.html
> 
> 4.最好在最新版（当前为 3.3.0.0）上测试，确保数据库本身版本处于最优。
> 
> 5.最好在服务端测试，确保没有网络等其他因素干扰。

社区版有什么办法可以检测是不是有时间戳覆盖问题？？？

**Comment by accoool** [comment]
> 一般查询慢主要这几个原因：
> 
> 1.数据被大量相同时间戳的数据覆盖过，导致碎片多，开源版数据导出再导入就行了。（企业版支持在线重组）
> 
> 2.乱序比较多。
> 
> 3. 数据库建模优化不够，可以参考：https://www.taosdata.com/tdengine-engineering/21550.html
> 
> 4.最好在最新版（当前为 3.3.0.0）上测试，确保数据库本身版本处于最优。
> 
> 5.最好在服务端测试，确保没有网络等其他因素干扰。
我有一个问题，第一列的时间戳是默认意义上的主键id（不重复的那种）吗？

**Comment by accoool** [comment]
> 一般查询慢主要这几个原因：
> 
> 1.数据被大量相同时间戳的数据覆盖过，导致碎片多，开源版数据导出再导入就行了。（企业版支持在线重组）
> 
> 2.乱序比较多。
> 
> 3. 数据库建模优化不够，可以参考：https://www.taosdata.com/tdengine-engineering/21550.html
> 
> 4.最好在最新版（当前为 3.3.0.0）上测试，确保数据库本身版本处于最优。
> 
> 5.最好在服务端测试，确保没有网络等其他因素干扰。

第一列的timestamp是主键id（不重复的那种）吗？还是说担任了分时分区的一个职责？我现在一个表3000w，用 ts in （）查询耗时1分钟

**Comment by Carson-yy** [comment]
> > 一般查询慢主要这几个原因：
> > 1.数据被大量相同时间戳的数据覆盖过，导致碎片多，开源版数据导出再导入就行了。（企业版支持在线重组）
> > 2.乱序比较多。
> > 
> > 3. 数据库建模优化不够，可以参考：https://www.taosdata.com/tdengine-engineering/21550.html
> > 
> > 4.最好在最新版（当前为 3.3.0.0）上测试，确保数据库本身版本处于最优。
> > 5.最好在服务端测试，确保没有网络等其他因素干扰。
> 
> 第一列的timestamp是主键id（不重复的那种）吗？还是说担任了分时分区的一个职责？我现在一个表3000w，用 ts in （）查询耗时1分钟

ts我设定的纳秒级，重复基本可能性不大，ts完全对我就是时序列
