### ISSUE TITLE
cannot sync data after expanding single-node deployment to multi-node cluster

### ISSUE THREAD

**Issue by liqilong2017** [taosdata/TDengine#25678]
版本：V3.0.2.0
单节点到集群扩容，数据无法同步
执行完：create dnode 'xxx:6030';
执行完：alter database saas replica 3 ;
就一直在 transactions，其他的命令也执行不了，报错 DB error: Conflict transaction not completed (0.006464s)

![image](https://github.com/taosdata/TDengine/assets/36256621/e351d28e-9293-4689-a1f1-916eb7330d7a)

05/08 18:36:57.039257 00028826 VND ERROR vgId:3, msg:0x7fcc5400bf08 failed to propose since Sync not ready for propose, code:0x80000911, gtid:0x0:0x6387357c71901154
05/08 18:36:57.040120 00028815 MND ERROR trans:144805, stage keep on redoAction since success, failedTimes:583
05/08 18:36:59.181123 00028826 SYN ERROR vgId:3, sync leader failed to sync propose since not ready, type:alter-confirm, last:130276628, cmt:130276626, term:13, commit-index:130276626, first-ver:130193872, last-ver:130276628, min:-1, snap:130276626, snap-term:9, elect-times:1, as-leader-times:1, cfg-ch-times:0, hit:0, mis:1191, hb-slow:0, hbr-slow:0, aq-items:0, snaping:-1, replicas:2, last-cfg:-1, chging:0, restore:0, quorum:2, elect-lc-timer:5, hb:0, {0:-1 0, 1:-1 0}, {r-num:2, my:0, k8s-master.test.ali.dc:6030, k8s-node02.dev.ali.dc:6030}, hb:{0:1715163379279,1:1715163379279}, hbr:{0:1715163379279,1:1715164104804}

![image](https://github.com/taosdata/TDengine/assets/36256621/f9a051aa-5c8e-4e3f-8e7a-b3f27ffc4206)
![image](https://github.com/taosdata/TDengine/assets/36256621/e97ea7cb-fb69-422b-bd95-a65a1b1c7dc1)
![image](https://github.com/taosdata/TDengine/assets/36256621/3b1bd369-753f-4ced-b4dc-c6167b58969b)

**Comment by yu285** [comment]
kill 事务的语法： kill transaction id

**Comment by yu285** [comment]
另外 3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/

仍有问题请微信联系 a15652223354
