### ISSUE TITLE
Caused by: java.lang.UnsatisfiedLinkError: no taos in java.library.path

### ISSUE THREAD

**Issue by holypost** [taosdata/TDengine#25688]
docker 安装的镜像，运行正常，
docker run -d --name tdengine --network service_network \
	--hostname="tdengine-server" \
	-v /docker-data/taos/dnode/data:/var/lib/taos \
	-v /docker-data/taos/dnode/log:/var/log/taos \
	-v /usr/share/zoneinfo:/usr/share/zoneinfo \
	-e TZ=Asia/Shanghai \
	-p 6030:6030 -p 6041:6041 -p 6043-6049:6043-6049 -p 6043-6049:6043-6049/udp \
	tdengine/tdengine
![image](https://github.com/taosdata/TDengine/assets/154062060/abb8ed54-d5b5-4583-a309-ccb7d32bb940)

项目的驱动：
```
<dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>3.2.11</version>
        </dependency>
```

启动报错：
Caused by: java.lang.UnsatisfiedLinkError: no taos in java.library.path: /usr/lib/jvm/java-17-amazon-corretto/lib/server:/usr/lib/jvm/java-17-amazon-corretto/lib:/usr/lib/jvm/java-17-amazon-corretto/../lib:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2434)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1993)
	at com.taosdata.jdbc.TSDBJNIConnector.<clinit>(TSDBJNIConnector.java:35)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:164)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
.....

![image](https://github.com/taosdata/TDengine/assets/154062060/47455c28-ba87-4713-9dd7-417dfd5b4a8b)

**Comment by yu285** [comment]
参考 https://docs.taosdata.com/train-faq/faq/

**Comment by holypost** [comment]
> 参考 https://docs.taosdata.com/train-faq/faq/

thx.  文档并没有说清楚。

不过我已经解决了，是要 docker构建的镜像内要有这个 .so，或者挂载宿主机里有这个.so的目录，并将其设置到环境变量里，如我的Dockerfile里是这样的：

`
# 配置JAVA_HOME环境变量
ENV JAVA_HOME="/usr/lib/jvm/${JDK}"
ENV LD_LIBRARY_PATH="/usr/local/taos/driver"
ENV PATH="${PATH}:${JAVA_HOME}/bin:${JAVA_HOME}/sbin:$LD_LIBRARY_PATH"
`
/usr/local/taos/driver  是宿主机的目录，该目录有.so文件，构建镜像的时候，挂载这个目录

**Comment by holypost** [comment]
> > > 参考 https://docs.taosdata.com/train-faq/faq/
> > 
> > 
> > thx. 文档并没有说清楚。
> > 不过我已经解决了，是要 docker构建的镜像内要有这个 .so，或者挂载宿主机里有这个.so的目录，并将其设置到环境变量里，如我的Dockerfile里是这样的：
> > # 配置JAVA_HOME环境变量
> > ENV JAVA_HOME="/usr/lib/jvm/${JDK}" ENV LD_LIBRARY_PATH="/usr/local/taos/driver" ENV PATH="${PATH}:${JAVA_HOME}/bin:${JAVA_HOME}/sbin:$LD_LIBRARY_PATH" /usr/local/taos/driver 是宿主机的目录，该目录有.so文件，构建镜像的时候，挂载这个目录
> 
> 请问，最后一句话，构建镜像的时候挂载这个目录是什么意思，我按照你这边配置，在dockerfile里也指定了.so文件存放的路径，连接数据库的时候，提示我指定的宿主机路径里还是no taos in java.library.path，是要把存放.so文件的宿主机路径挂载到java程序容器服务里的某个地方吗

宿主机有就行了，因为会扫描这个目录，Dockerfile里在环境变量设置了这个路径，

**Comment by Nicky213Zhang** [comment]
> > > > 参考 https://docs.taosdata.com/train-faq/faq/
> > > 
> > > 
> > > thx. 文档并没有说清楚。
> > > 不过我已经解决了，是要 docker构建的镜像内要有这个 .so，或者挂载宿主机里有这个.so的目录，并将其设置到环境变量里，如我的Dockerfile里是这样的：
> > > # 配置JAVA_HOME环境变量
> > > ENV JAVA_HOME="/usr/lib/jvm/${JDK}" ENV LD_LIBRARY_PATH="/usr/local/taos/driver" ENV PATH="${PATH}:${JAVA_HOME}/bin:${JAVA_HOME}/sbin:$LD_LIBRARY_PATH" /usr/local/taos/driver 是宿主机的目录，该目录有.so文件，构建镜像的时候，挂载这个目录
> > 
> > 
> > 请问，最后一句话，构建镜像的时候挂载这个目录是什么意思，我按照你这边配置，在dockerfile里也指定了.so文件存放的路径，连接数据库的时候，提示我指定的宿主机路径里还是no taos in java.library.path，是要把存放.so文件的宿主机路径挂载到java程序容器服务里的某个地方吗
> 
> 宿主机有就行了，因为会扫描这个目录，Dockerfile里在环境变量设置了这个路径，

你这个/usr/local/taos/driver路径下的文件是跟tdengine容器内的对应的路径下的吗，因为它那个.so文件是一层一层递进的，我的tdengine容器内的/usr/local/taos/driver下只有这三个
![image](https://github.com/taosdata/TDengine/assets/25654842/55d13eb9-c0ce-4bb0-88bd-b31cddcc529a)

**Comment by holypost** [comment]
> > > > > 参考 https://docs.taosdata.com/train-faq/faq/
> > > > 
> > > > 
> > > > thx. 文档并没有说清楚。
> > > > 不过我已经解决了，是要 docker构建的镜像内要有这个 .so，或者挂载宿主机里有这个.so的目录，并将其设置到环境变量里，如我的Dockerfile里是这样的：
> > > > # 配置JAVA_HOME环境变量
> > > > ENV JAVA_HOME="/usr/lib/jvm/${JDK}" ENV LD_LIBRARY_PATH="/usr/local/taos/driver" ENV PATH="${PATH}:${JAVA_HOME}/bin:${JAVA_HOME}/sbin:$LD_LIBRARY_PATH" /usr/local/taos/driver 是宿主机的目录，该目录有.so文件，构建镜像的时候，挂载这个目录
> > > 
> > > 
> > > 请问，最后一句话，构建镜像的时候挂载这个目录是什么意思，我按照你这边配置，在dockerfile里也指定了.so文件存放的路径，连接数据库的时候，提示我指定的宿主机路径里还是no taos in java.library.path，是要把存放.so文件的宿主机路径挂载到java程序容器服务里的某个地方吗
> > 
> > 
> > 宿主机有就行了，因为会扫描这个目录，Dockerfile里在环境变量设置了这个路径，
> 
> 你这个/usr/local/taos/driver路径下的文件是跟tdengine容器内的对应的路径下的吗，因为它那个.so文件是一层一层递进的，我的tdengine容器内的/usr/local/taos/driver下只有这三个 ![image](https://private-user-images.githubusercontent.com/25654842/338519776-55d13eb9-c0ce-4bb0-88bd-b31cddcc529a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTc4MDEsIm5iZiI6MTcxODA5NzUwMSwicGF0aCI6Ii8yNTY1NDg0Mi8zMzg1MTk3NzYtNTVkMTNlYjktYzBjZS00YmIwLTg4YmQtYjMxY2RkY2M1MjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA5MTgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0Mjk4NGI2MzUwM2I4OWQyZjg5ODYzYzJmMDllY2NmODlkZmQ2ZjYzZGNhNzFhMGZhM2ZkODkzODc0MzNkNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l3an5dmk0NGh1ihRriap9SUDrAsatPylFr0m4DHzrH8)

好像是默认的taos目录把，我这里是：
![image](https://github.com/taosdata/TDengine/assets/154062060/a352ba0b-92e3-4663-a165-42778f41c9f5)

**Comment by Nicky213Zhang** [comment]
> > > > > > 参考 https://docs.taosdata.com/train-faq/faq/
> > > > > 
> > > > > 
> > > > > thx. 文档并没有说清楚。
> > > > > 不过我已经解决了，是要 docker构建的镜像内要有这个 .so，或者挂载宿主机里有这个.so的目录，并将其设置到环境变量里，如我的Dockerfile里是这样的：
> > > > > # 配置JAVA_HOME环境变量
> > > > > ENV JAVA_HOME="/usr/lib/jvm/${JDK}" ENV LD_LIBRARY_PATH="/usr/local/taos/driver" ENV PATH="${PATH}:${JAVA_HOME}/bin:${JAVA_HOME}/sbin:$LD_LIBRARY_PATH" /usr/local/taos/driver 是宿主机的目录，该目录有.so文件，构建镜像的时候，挂载这个目录
> > > > 
> > > > 
> > > > 请问，最后一句话，构建镜像的时候挂载这个目录是什么意思，我按照你这边配置，在dockerfile里也指定了.so文件存放的路径，连接数据库的时候，提示我指定的宿主机路径里还是no taos in java.library.path，是要把存放.so文件的宿主机路径挂载到java程序容器服务里的某个地方吗
> > > 
> > > 
> > > 宿主机有就行了，因为会扫描这个目录，Dockerfile里在环境变量设置了这个路径，
> > 
> > 
> > 你这个/usr/local/taos/driver路径下的文件是跟tdengine容器内的对应的路径下的吗，因为它那个.so文件是一层一层递进的，我的tdengine容器内的/usr/local/taos/driver下只有这三个 ![image](https://private-user-images.githubusercontent.com/25654842/338519776-55d13eb9-c0ce-4bb0-88bd-b31cddcc529a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTc4MDEsIm5iZiI6MTcxODA5NzUwMSwicGF0aCI6Ii8yNTY1NDg0Mi8zMzg1MTk3NzYtNTVkMTNlYjktYzBjZS00YmIwLTg4YmQtYjMxY2RkY2M1MjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA5MTgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0Mjk4NGI2MzUwM2I4OWQyZjg5ODYzYzJmMDllY2NmODlkZmQ2ZjYzZGNhNzFhMGZhM2ZkODkzODc0MzNkNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l3an5dmk0NGh1ihRriap9SUDrAsatPylFr0m4DHzrH8)
> 
> 好像是默认的taos目录把，我这里是： ![image](https://private-user-images.githubusercontent.com/154062060/338520562-a352ba0b-92e3-4663-a165-42778f41c9f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTc4ODksIm5iZiI6MTcxODA5NzU4OSwicGF0aCI6Ii8xNTQwNjIwNjAvMzM4NTIwNTYyLWEzNTJiYTBiLTkyZTMtNDY2My1hMTY1LTQyNzc4ZjQxYzlmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQwOTE5NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZGIzM2M1YTE4MGYwNGQyNTBiZjlkNzA2MjFiNWZhOTEyMTQ2ZmZiMjRhNTJiZjdiNTExMDEwNWFmMjcxYTdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MTKOFYRytuREC640VRMgEKZo3p5KDKvWSVNczaiDJss)

![image](https://github.com/taosdata/TDengine/assets/25654842/06c40f58-f8a7-4edf-9104-efe700d12a07)
人麻了

**Comment by holypost** [comment]
> > > > > > > 参考 https://docs.taosdata.com/train-faq/faq/
> > > > > > 
> > > > > > 
> > > > > > thx. 文档并没有说清楚。
> > > > > > 不过我已经解决了，是要 docker构建的镜像内要有这个 .so，或者挂载宿主机里有这个.so的目录，并将其设置到环境变量里，如我的Dockerfile里是这样的：
> > > > > > # 配置JAVA_HOME环境变量
> > > > > > ENV JAVA_HOME="/usr/lib/jvm/${JDK}" ENV LD_LIBRARY_PATH="/usr/local/taos/driver" ENV PATH="${PATH}:${JAVA_HOME}/bin:${JAVA_HOME}/sbin:$LD_LIBRARY_PATH" /usr/local/taos/driver 是宿主机的目录，该目录有.so文件，构建镜像的时候，挂载这个目录
> > > > > 
> > > > > 
> > > > > 请问，最后一句话，构建镜像的时候挂载这个目录是什么意思，我按照你这边配置，在dockerfile里也指定了.so文件存放的路径，连接数据库的时候，提示我指定的宿主机路径里还是no taos in java.library.path，是要把存放.so文件的宿主机路径挂载到java程序容器服务里的某个地方吗
> > > > 
> > > > 
> > > > 宿主机有就行了，因为会扫描这个目录，Dockerfile里在环境变量设置了这个路径，
> > > 
> > > 
> > > 你这个/usr/local/taos/driver路径下的文件是跟tdengine容器内的对应的路径下的吗，因为它那个.so文件是一层一层递进的，我的tdengine容器内的/usr/local/taos/driver下只有这三个 ![image](https://private-user-images.githubusercontent.com/25654842/338519776-55d13eb9-c0ce-4bb0-88bd-b31cddcc529a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTc4MDEsIm5iZiI6MTcxODA5NzUwMSwicGF0aCI6Ii8yNTY1NDg0Mi8zMzg1MTk3NzYtNTVkMTNlYjktYzBjZS00YmIwLTg4YmQtYjMxY2RkY2M1MjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA5MTgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0Mjk4NGI2MzUwM2I4OWQyZjg5ODYzYzJmMDllY2NmODlkZmQ2ZjYzZGNhNzFhMGZhM2ZkODkzODc0MzNkNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l3an5dmk0NGh1ihRriap9SUDrAsatPylFr0m4DHzrH8)
> > 
> > 
> > 好像是默认的taos目录把，我这里是： ![image](https://private-user-images.githubusercontent.com/154062060/338520562-a352ba0b-92e3-4663-a165-42778f41c9f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTc4ODksIm5iZiI6MTcxODA5NzU4OSwicGF0aCI6Ii8xNTQwNjIwNjAvMzM4NTIwNTYyLWEzNTJiYTBiLTkyZTMtNDY2My1hMTY1LTQyNzc4ZjQxYzlmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQwOTE5NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZGIzM2M1YTE4MGYwNGQyNTBiZjlkNzA2MjFiNWZhOTEyMTQ2ZmZiMjRhNTJiZjdiNTExMDEwNWFmMjcxYTdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MTKOFYRytuREC640VRMgEKZo3p5KDKvWSVNczaiDJss)
> 
> ![image](https://private-user-images.githubusercontent.com/25654842/338521796-06c40f58-f8a7-4edf-9104-efe700d12a07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTgxNDUsIm5iZiI6MTcxODA5Nzg0NSwicGF0aCI6Ii8yNTY1NDg0Mi8zMzg1MjE3OTYtMDZjNDBmNTgtZjhhNy00ZWRmLTkxMDQtZWZlNzAwZDEyYTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA5MjQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3ZjU2ZjdmMzRiOWMxOWYyMTA4N2FmMWIyNmI5YTkyNDQ1MGZjMjNlNzEwNWZmN2U2NjEwNjRmODAwNzljZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vChcWFVsaRON29WKu-se_any4lqMt6vnwxotE_Zea0U) 人麻了


你 cp libtaos.so.3.3.0.0  libtaos.so 试试，你好像没用这个名字

**Comment by Nicky213Zhang** [comment]
> > 参考 https://docs.taosdata.com/train-faq/faq/
> 
> thx. 文档并没有说清楚。
> 
> 不过我已经解决了，是要 docker构建的镜像内要有这个 .so，或者挂载宿主机里有这个.so的目录，并将其设置到环境变量里，如我的Dockerfile里是这样的：
> 
> # 配置JAVA_HOME环境变量
> ENV JAVA_HOME="/usr/lib/jvm/${JDK}" ENV LD_LIBRARY_PATH="/usr/local/taos/driver" ENV PATH="${PATH}:${JAVA_HOME}/bin:${JAVA_HOME}/sbin:$LD_LIBRARY_PATH" /usr/local/taos/driver 是宿主机的目录，该目录有.so文件，构建镜像的时候，挂载这个目录

我最后的处理方式是这样的：一、/usr/local/taos/driver是容器内的路径，环境变量最后还是要在容器内启动应用时生效。二、docker脚本挂载宿主机路径到容器内的/usr/local/taos/driver路径下。你是不是容器内外都是这个路径，我是不一样的路径，所以可以清晰的看出来
