### ISSUE TITLE
Cannot write the same stable as other stream 

### ISSUE THREAD

**Issue by zhuangQingGuang** [taosdata/TDengine#25692]
版本：3.2.0.0
创建流计算时，使用同一个超级表时报：Cannot write the same stable as other stream 
我看文档说是只要表结构一样是可以使用同一张超级表 是我的语句有问题吗

`create stream hr_stream1 into s_t_4 subtable(concat('new_', tname)) as select _wstart, _wend, avg(`value`) energy from d_1 partition by tbname tname interval(10m);`
`create stream hr_stream2 into s_t_4 subtable(concat('new_', tname)) as select _wstart, _wend, avg(`value`) energy from d_2 partition by tbname tname interval(10m);`

**Comment by yu285** [comment]
应该是版本问题，可以等明后天，升级到最新的 3.3.0.0 。

**Comment by zhuangQingGuang** [comment]
> 应该是版本问题，可以等明后天，升级到最新的 3.3.0.0 。

升级到最新版本之后还是不能同用一个超级表

**Comment by zhenjun115** [comment]
版本: 3.3.5.2 Community
报错：Internal error: `Cannot write the same stable as other stream`

**Comment by yu285** [comment]
![Image](https://github.com/user-attachments/assets/df401d25-12ad-4140-9c60-b9ed209dd9e4)
