### ISSUE TITLE
关于查询问题

### ISSUE THREAD

**Issue by Carson-yy** [taosdata/TDengine#25712]
语句如下：

st_point_data_commerce 这个是超表，device_sn是TAG列，data_no 是一个普通列，查询要长达5秒，当日超表的子表和数据量挺大！

select
	last_row(*)
from
	st_point_data_commerce
where
	device_sn = 'xxxxxxx'
	and ts <= '2024-05-09 13:25:00'
	and data_no = '04'

条件带普通列都查询很慢，配置上4核8G三台集群

**Comment by yinheli** [comment]
补充 explain 信息看看？

**Comment by Carson-yy** [comment]
> explain

![image](https://github.com/taosdata/TDengine/assets/12856549/f9acde9a-4fdf-46f3-966e-cc558c8cd1f2)
