### ISSUE TITLE
interval()函数 +  SPREAD()函数查询差值时，interval()参数不一样，计算策略不一致！该问题已经在微信群跟你们官方人员解释确认过！

### ISSUE THREAD

**Issue by qihaofei001** [taosdata/TDengine#25714]
**Bug Description**
interval()函数 +  SPREAD()函数查询差值时，interval()参数不一样，计算策略不一致！
注！该问题已经在微信群跟你们官方人员解释确认过

**To Reproduce**
1. 按1分钟频率采集递增数据（如电表，每个数据值必须不一致，且是递增的）
2. --INTERVAL(30m)，实际结果是00:30:00值-00:00:00值，01:00:00值-00:30:00值，符合预期
select SPREAD(`current`) from taosiot.table
where ts>='2024-05-07 00:00:00' and ts<='2024-05-07 01:00:00'
INTERVAL(30m)
3.--INTERVAL(1h)，实际结果是00:59:00值-00:00:00值，不符合预期
select SPREAD(`current`) from taosiot.table
where ts>='2024-05-07 00:00:00' and ts<='2024-05-07 01:00:00'
INTERVAL(1h)

**Expected Behavior**
在INTERVAL（）使用不同的参数时，行为应该是一致的，通常情况我们更希望能像INTERVAL(30m)，实际结果是00:30:00值-00:00:00值，01:00:00值-00:30:00值，而不是像INTERVAL(1h)使用00:59:00值-00:00:00值。

**Screenshots**
测试数据：
![image](https://github.com/taosdata/TDengine/assets/15154223/22de74b0-9fba-49aa-826d-12feeaeb1f4f)
INTERVAL(30m)时，SPREAD实际结果是00:30:00值-00:00:00值，01:00:00值-00:30:00值，符合预期。
![image](https://github.com/taosdata/TDengine/assets/15154223/fb90c707-2db3-415b-bac3-ac0b27ee9154)
INTERVAL(1h)，SPREAD实际结果是00:59:00值-00:00:00值，不符合预期
![image](https://github.com/taosdata/TDengine/assets/15154223/668e153b-b5cd-4af9-83fd-e5fb74aa1af7)

**Environment (please complete the following information):**
 - OS:  CentOS 7.9
 - Memory, CPU, 都没问题
 - TDengine Version [3.0.6，3.2.3均已经测试过，都存在该问题]

**Additional Context**

**Comment by xiaopingcs** [comment]
@54liuyao TD-30000

**Comment by qihaofei001** [comment]
此问题是我测试数据问题，造成的，interval（）函数在参数不同的情况下，每个时间段都是左闭右开，策略是一致的！没问题！
