### ISSUE TITLE
PERCENTILE function causes abnormal memory usage

### ISSUE THREAD

**Issue by MochenSata** [taosdata/TDengine#25767]
**Bug Description**
PERCENTILE函数导致内存异常增加

**To Reproduce**
1. select PERCENTILE (p01_0022,50) value from test.p1006_051012_sec where ts >= '2024-05-10 11:21:05.000' and ts <= '2024-05-14 11:26:24.000'
2. 表中一秒钟一条数据，5天大约40w条多数据
3. 执行sql后没反应，内存一直在增加
4. windows docker上尝试后内存增加到3g左右自己被杀掉，centos docker 内存一直增加直至爆内存

**Environment (please complete the following information):**
 - OS: CentOS 7.9，windows
 - TDengine Version [e.g. 2.2.2.10]

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/

如果还有具体的使用问题，可以加微信：a15652223354
