### ISSUE TITLE
order by ts desc returns incorrect results

### ISSUE THREAD

**Issue by denzellin** [taosdata/TDengine#25780]
1. 创建表：CREATE STABLE if not exists vital_surface (ts timestamp, user_id bigint unsigned, body_temperature binary(20), step_count int, gateway binary(64)) TAGS (mac binary(64))

3. 插入数据：INSERT INTO vital_surface_#{mac} USING vital_surface TAGS(#{mac})
        VALUES(#{timestamp}, #{userId}, #{bodyTemperature}, #{stepCount}, #{gatewayMac})

4. 结果集按降序排序时, 结果集没有记录，查询语句：
select ts from vital_inner where ts >= 1715232974000 and  ts <= 1715234460000 and user_id = 1051 order by ts desc;
5. 结果集升序或默认排序时, 结果集正常，查询语句：
select ts from vital_inner where ts >= 1715232974000 and  ts <= 1715234460000 and user_id = 1051 order by ts asc;

![WechatIMG403](https://github.com/taosdata/TDengine/assets/13179422/778618a9-61bf-4620-aaa7-f9d45004ba70)

数据库版本号信息：

Welcome to the TDengine Command Line Interface, Client Version:3.0.1.4
Copyright (c) 2022 by TDengine, all rights reserved.

Server is Community Edition.

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
