### ISSUE TITLE
请问Java的连接的jdbc这个在哪里可以下载到？

### ISSUE THREAD

**Issue by hechaotudou** [taosdata/TDengine#258]
<dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>1.0.0</version>
        </dependency>

请问Java的连接的jdbc驱动程序这个在哪里可以下载到，

**Comment by guanshengliang** [comment]
deb或者rpm包安装之后
在/usr/local/taos/connector目录下
