### ISSUE TITLE
Question: how to create a stream to load data into super table with tags

### ISSUE THREAD

**Issue by enix223** [taosdata/TDengine#25806]
## Question

I have a summary table (with two tags: **location** and **device_id**), the source table `device_history` also have these two tags, I need to summarized the `power` value for each location + device_id combination, and load it into the dest table.

```sql
CREATE STABLE device_total_power (ts TIMESTAMP, total_power BIGINT) TAGS (location INT, device_id INT);
```

create stream
```sql
CREATE STREAM stream_device_total_power
TRIGGER WINDOW_CLOSE
INTO device_total_power SUBTABLE(CONCAT('device_, CAST(device_id AS VARCHAR(12)), '_total_power'))
AS SELECT _wend AS ts, SUM(power) AS total_power
FROM device_history PARTITION BY location, device_id INTERVAL(1d);
```

When I run the sql above, I got error: 

```
DB error: Illegal number of columns (0.012870s)
```

## Environment

TDEngine version: 3.1.0.3
Server: Ubuntu 22.04

**Comment by yu285** [comment]
![image](https://github.com/taosdata/TDengine/assets/74105241/ae494b94-84d8-46cf-a46e-b5c2abb69716)

 CREATE STABLE device_history (ts TIMESTAMP, power BIGINT) TAGS (location INT, device_id INT);
 
CREATE STREAM stream_device_total_power TRIGGER WINDOW_CLOSE INTO device_total_power   SUBTABLE(CONCAT('device_', CAST(device_id AS VARCHAR(12)), '_total_power')) AS SELECT _wen
d AS ts, SUM(power) AS total_power FROM device_history PARTITION BY location, device_id INTERVAL(1d);


it seems fine ,can you try new version? 3.3.0.3
