### ISSUE TITLE
文档流式计算部分有个单词错误

### ISSUE THREAD

**Issue by damoasis** [taosdata/TDengine#25813]
**文档单词错误，文档链接如下：**
https://docs.taosdata.com/taos-sql/stream/#%E6%B5%81%E5%BC%8F%E8%AE%A1%E7%AE%97%E7%9A%84-partition
部分内容如下：
PARTITION 子句中，为 tbname 定义了一个别名 tname, 在PARTITION 子句中的别名可以用于 SUBTABLE 子句中的表达式计算，在上述示例中，流新创建的子表将以前缀 'new-' 连接原表名作为表名(从3.2.3.0开始，为了避免 sutable 中的表达式无法区分各个子表，即误将多个相同时间线写入一个子表，在指定的子表名后面加上 _groupId)。

其中sutable应为subtable

**Comment by yu285** [comment]
收到我们改一下。
