### ISSUE TITLE
mqtt通过restful保存数据, 部分数据丢失

### ISSUE THREAD

**Issue by sanmuTHINK** [taosdata/TDengine#25820]
**Bug Description**

流程是这样的
1. 生产端 循环300条记录publish 给MQTT
2. MQTT 通过restful post给tdengine 做备份
3. 消费端消费MQTT ,存入数据库

出现问题:
查询tdengine 丢失部分数据.  
![tdengine截图](https://github.com/taosdata/TDengine/assets/21034776/782ab1da-f848-4de0-bccf-ff19945d3d6b)

消费端查询数据完整.
![消费端截图](https://github.com/taosdata/TDengine/assets/21034776/d4c82fb8-e24b-4ee2-b6ac-becf738aff83)

**Environment (please complete the following information):**
 - OS: [window server 2019]
 - TDengine Version [3.0.7.1]

**Additional Context**

**Comment by sanmuTHINK** [comment]
做过以下排查
1. Emqx 的数据桥接到tdengine , 没有发送失败记录,全部成功
2. 开启enableRecordHttpSql日志, 是有insert 语句的.

**Comment by yu285** [comment]
有没有时间戳相同导致被覆盖更新的隐患？
