### ISSUE TITLE
what does REDISTRIBUTE actually do?

### ISSUE THREAD

**Issue by Zeroive** [taosdata/TDengine#25847]
官方文档如下:
调整VGROUP中VNODE的分布
REDISTRIBUTE VGROUP vgroup_no DNODE dnode_id1 [DNODE dnode_id2] [DNODE dnode_id3]

按照给定的dnode列表，调整vgroup中的vnode分布。因为副本数目最大为3，所以最多输入3个dnode。

- 是调整 vgroup_no 放在 第几个 dnode 中的意思嘛？

**Comment by yu285** [comment]
是这样的
