### ISSUE TITLE
java.sql.SQLException: JNI ERROR (0x2354): Conn is broken

### ISSUE THREAD

**Issue by fulin-peng-ydxs** [taosdata/TDengine#25851]
使用java客户端：3.2.3
	<dependency>
			<groupId>com.taosdata.jdbc</groupId>
			<artifactId>taos-jdbcdriver</artifactId>
			<version>**3.2.3**</version>
	</dependency>
连接相同版本的数据库报错：JNI ERROR (0x2354): Conn is broken

        String jdbcUrl = "jdbc:TAOS://xxxx:6030?user=root&password=taosdata";
        Properties connProps = new Properties();
        Connection conn = DriverManager.getConnection(jdbcUrl, connProps);
        System.out.println("Connected");
        conn.close();

值得注意的是我使用相同版本linux客户端却可以正常连接！！！！
Welcome to the TDengine Command Line Interface, Client Version:3.2.3.0
Copyright (c) 2023 by TDengine, all rights reserved.

  ********************************  Tab Completion  ************************************
  *   The TDengine CLI supports tab completion for a variety of items,                 *
  *   including database names, table names, function names and keywords.              *
  *   The full list of shortcut keys is as follows:                                    *
  *    [ TAB ]        ......  complete the current word                                *
  *                   ......  if used on a blank line, display all supported commands  *
  *    [ Ctrl + A ]   ......  move cursor to the st[A]rt of the line                   *
  *    [ Ctrl + E ]   ......  move cursor to the [E]nd of the line                     *
  *    [ Ctrl + W ]   ......  move cursor to the middle of the line                    *
  *    [ Ctrl + L ]   ......  clear the entire screen                                  *
  *    [ Ctrl + K ]   ......  clear the screen after the cursor                        *
  *    [ Ctrl + U ]   ......  clear the screen before the cursor                       *
  **************************************************************************************

Server is Community Edition.

taos>

**Comment by yu285** [comment]
![image](https://github.com/taosdata/TDengine/assets/74105241/12269a4d-142e-4e1e-a204-61d6ae3813b5)
按照这个对应关系
