### ISSUE TITLE
数据订阅

### ISSUE THREAD

**Issue by gavin1001** [taosdata/TDengine#25885]
当应用程序处理不过来，出现大量的数据积压时，想抛弃积压的所有数据，此时应该使用什么命令情况管道里的积压数据？

**Comment by wangmm0220** [comment]
可以通过tmq_get_topic_assignment 接口获取每个vnode（即partition）的 end offset，然后把 end offset  通过tmq_offset_seek 接口将消费进度设置到end，继续消费就跳到了最后。
