### ISSUE TITLE
order by ts desc 结果乱序

### ISSUE THREAD

**Issue by zhuangQingGuang** [taosdata/TDengine#25906]
版本：3.2.0
SQL：select * from d_3121_liquid_level where ts>"2024-05-22 14:56:39" and ts < "2024-05-23 14:56:39" order by ts desc;
![微信截图_20240523163111](https://github.com/taosdata/TDengine/assets/45782190/c2d1385d-415f-44f4-82ad-14bd646f751a)

**Comment by yu285** [comment]
排序问题已经优化修复，请统一升级到最新版3.3.0.3
