### ISSUE TITLE
JAVA采用原生连接的方式连接tdengine，刚启动一会就退出，java进程关闭

### ISSUE THREAD

**Issue by 474873060** [taosdata/TDengine#25903]
报错日志：
05/23 11:16:24.841987 00004910 UTL FATAL assert info not provided
05/23 11:16:24.842006 00004910 UTL FATAL tAssert at file /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/common/src/tdataformat.c:2354 exit:1
05/23 11:16:24.842834 00004910 UTL FATAL obtained 13 stack frames
05/23 11:16:24.842840 00004910 UTL FATAL frame:0, /usr/local/taos/driver/libtaos.so.3.0.3.0(taosAssertDebug+0x1c6) [0x7c58e828396a]
05/23 11:16:24.842843 00004910 UTL FATAL frame:1, /usr/local/taos/driver/libtaos.so.3.0.3.0(tColDataGetValue+0x80) [0x7c58e82bfb4b]
05/23 11:16:24.842846 00004910 UTL FATAL frame:2, /usr/local/taos/driver/libtaos.so.3.0.3.0(+0x12c5e8) [0x7c58e82c15e8]
05/23 11:16:24.842848 00004910 UTL FATAL frame:3, /usr/local/taos/driver/libtaos.so.3.0.3.0(+0x12c7da) [0x7c58e82c17da]
05/23 11:16:24.842852 00004910 UTL FATAL frame:4, /usr/local/taos/driver/libtaos.so.3.0.3.0(+0x12c967) [0x7c58e82c1967]
05/23 11:16:24.842854 00004910 UTL FATAL frame:5, /usr/local/taos/driver/libtaos.so.3.0.3.0(+0x12c9ad) [0x7c58e82c19ad]
05/23 11:16:24.842860 00004910 UTL FATAL frame:6, /usr/local/taos/driver/libtaos.so.3.0.3.0(tColDataSortMerge+0x1a0) [0x7c58e82c310a]
05/23 11:16:24.842863 00004910 UTL FATAL frame:7, /usr/local/taos/driver/libtaos.so.3.0.3.0(insMergeTableDataCxt+0x17b) [0x7c58e8380631]
05/23 11:16:24.842867 00004910 UTL FATAL frame:8, /usr/local/taos/driver/libtaos.so.3.0.3.0(qBuildStmtOutput+0x52) [0x7c58e837d6d9]
05/23 11:16:24.842870 00004910 UTL FATAL frame:9, /usr/local/taos/driver/libtaos.so.3.0.3.0(stmtExec+0x17d) [0x7c58e8263fe1]
05/23 11:16:24.842874 00004910 UTL FATAL frame:10, /usr/local/taos/driver/libtaos.so.3.0.3.0(taos_stmt_execute+0x7c) [0x7c58e8246b9f]
05/23 11:16:24.842878 00004910 UTL FATAL frame:11, /usr/local/taos/driver/libtaos.so.3.0.3.0(Java_com_taosdata_jdbc_TSDBJNIConnector_executeBatchImp+0xdb) [0x7c58e823fff0]
05/23 11:16:24.842882 00004910 UTL FATAL frame:12, [0x7c5909018427]

这种问题应该怎么处理？能够避免异常关闭进程？

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
