### ISSUE TITLE
UTL FATAL assert info not provided

### ISSUE THREAD

**Issue by svalensu** [taosdata/TDengine#25928]
**Bug Description**
启动taosd失败，报错：UTL FATAL assert info not provided

**To Reproduce**
意外掉电后重启，服务一直起不来，手动启动服务时一直报这个错。

Environment (please complete the following information):
TDengine Version [3.0.2.4]

**Screenshots**
05/24 15:06:41.971115 00001523 UTL apoll url not load
05/24 15:06:41.971371 00001523 UTL failed to load from cfg file /etc/taos/ since No such file or directory, use default parameters
05/24 15:06:41.971438 00001523 UTL env file:.env not load
05/24 15:06:41.971472 00001523 UTL load from env variables cfg success
05/24 15:06:41.972093 00001523 DND startup path:/var/lib/taos/vnode args:taosd
05/24 15:06:41.973274 00001523 UTL apoll url not load
05/24 15:06:41.973354 00001523 UTL failed to load from cfg file /etc/taos/ since No such file or directory, use default parameters
05/24 15:06:41.973394 00001523 UTL env file:.env not load
05/24 15:06:41.973422 00001523 UTL load from env variables cfg success
05/24 15:06:41.973964 00001523 UTL                      global config
05/24 15:06:41.974005 00001523 UTL =================================================================
05/24 15:06:41.974023 00001523 UTL default      firstEp                  YYCUBE:6030
05/24 15:06:41.974041 00001523 UTL default      secondEp                 YYCUBE:6030
05/24 15:06:41.974069 00001523 UTL default      fqdn                     YYCUBE
05/24 15:06:41.974086 00001523 UTL default      serverPort               6030
05/24 15:06:41.974102 00001523 UTL default      tempDir                  /tmp/
05/24 15:06:41.974118 00001523 UTL default      minimalTmpDirGB          1.00
05/24 15:06:41.974142 00001523 UTL default      shellActivityTimer       3
05/24 15:06:41.974159 00001523 UTL default      compressMsgSize          -1
05/24 15:06:41.974174 00001523 UTL default      compressColData          -1
05/24 15:06:41.974199 00001523 UTL default      queryPolicy              1
05/24 15:06:41.974215 00001523 UTL default      enableQueryHb            0
05/24 15:06:41.974231 00001523 UTL default      querySmaOptimize         0
05/24 15:06:41.974247 00001523 UTL default      queryPlannerTrace        0
05/24 15:06:41.974262 00001523 UTL default      queryNodeChunkSize       32768
05/24 15:06:41.974277 00001523 UTL default      queryUseNodeAllocator    1
05/24 15:06:41.974293 00001523 UTL default      keepColumnName           0
05/24 15:06:41.974318 00001523 UTL default      smlChildTableName
05/24 15:06:41.974334 00001523 UTL default      smlTagName               _tag_null
05/24 15:06:41.974349 00001523 UTL default      smlDataFormat            0
05/24 15:06:41.974365 00001523 UTL default      smlBatchSize             10000
05/24 15:06:41.974381 00001523 UTL default      maxMemUsedByInsert       1024
05/24 15:06:41.974397 00001523 UTL default      maxRetryWaitTime         10000
05/24 15:06:41.974412 00001523 UTL default      useAdapter               0
05/24 15:06:41.974435 00001523 UTL default      crashReporting           1
05/24 15:06:41.974452 00001523 UTL default      numOfTaskQueueThreads    4
05/24 15:06:41.974468 00001523 UTL default      dataDir                  /var/lib/taos/
05/24 15:06:41.974483 00001523 UTL default      minimalDataDirGB         2.00
05/24 15:06:41.974503 00001523 UTL default      supportVnodes            8
05/24 15:06:41.974519 00001523 UTL default      maxShellConns            50000
05/24 15:06:41.974534 00001523 UTL default      statusInterval           1
05/24 15:06:41.974558 00001523 UTL default      minSlidingTime           10
05/24 15:06:41.974574 00001523 UTL default      minIntervalTime          1
05/24 15:06:41.974590 00001523 UTL default      maxNumOfDistinctRes      10000000
05/24 15:06:41.974605 00001523 UTL default      countAlwaysReturnValue   1
05/24 15:06:41.974620 00001523 UTL default      queryBufferSize          -1
05/24 15:06:41.974639 00001523 UTL default      printAuth                0
05/24 15:06:41.974659 00001523 UTL default      queryRspPolicy           0
05/24 15:06:41.974675 00001523 UTL default      numOfRpcThreads          2
05/24 15:06:41.974689 00001523 UTL default      numOfCommitThreads       2
05/24 15:06:41.974704 00001523 UTL default      numOfMnodeReadThreads    1
05/24 15:06:41.974719 00001523 UTL default      numOfVnodeQueryThreads   8
05/24 15:06:41.974734 00001523 UTL default      ratioOfVnodeStreamThrea  1.00
05/24 15:06:41.974751 00001523 UTL default      numOfVnodeFetchThreads   4
05/24 15:06:41.974766 00001523 UTL default      numOfVnodeRsmaThreads    4
05/24 15:06:41.974782 00001523 UTL default      numOfQnodeQueryThreads   8
05/24 15:06:41.974797 00001523 UTL default      numOfSnodeSharedThreads  2
05/24 15:06:41.974834 00001523 UTL default      numOfSnodeUniqueThreads  2
05/24 15:06:41.974851 00001523 UTL default      rpcQueueMemoryAllowed    409154764
05/24 15:06:41.974867 00001523 UTL default      syncElectInterval        25000
05/24 15:06:41.974882 00001523 UTL default      syncHeartbeatInterval    1000
05/24 15:06:41.974897 00001523 UTL default      syncHeartbeatTimeout     20000
05/24 15:06:41.974912 00001523 UTL default      vndCommitMaxInterval     60000
05/24 15:06:41.974927 00001523 UTL default      monitor                  1
05/24 15:06:41.974940 00001523 UTL default      monitorInterval          30
05/24 15:06:41.974954 00001523 UTL default      monitorFqdn
05/24 15:06:41.974969 00001523 UTL default      monitorPort              6043
05/24 15:06:41.974984 00001523 UTL default      monitorMaxLogs           100
05/24 15:06:41.974999 00001523 UTL default      monitorComp              0
05/24 15:06:41.975014 00001523 UTL default      crashReporting           1
05/24 15:06:41.975029 00001523 UTL default      telemetryReporting       1
05/24 15:06:41.975044 00001523 UTL default      telemetryInterval        43200
05/24 15:06:41.975060 00001523 UTL default      telemetryServer          telemetry.taosdata.com
05/24 15:06:41.975075 00001523 UTL default      telemetryPort            80
05/24 15:06:41.975090 00001523 UTL default      transPullupInterval      2
05/24 15:06:41.975105 00001523 UTL default      mqRebalanceInterval      2
05/24 15:06:41.975119 00001523 UTL default      ttlUnit                  86400
05/24 15:06:41.975135 00001523 UTL default      ttlPushInterval          86400
05/24 15:06:41.975150 00001523 UTL default      uptimeInterval           300
05/24 15:06:41.975164 00001523 UTL default      queryRsmaTolerance       1000
05/24 15:06:41.975179 00001523 UTL default      walFsyncDataSizeLimit    104857600
05/24 15:06:41.975195 00001523 UTL default      udf                      1
05/24 15:06:41.975209 00001523 UTL default      udfdResFuncs
05/24 15:06:41.975224 00001523 UTL default      udfdLdLibPath
05/24 15:06:41.975239 00001523 UTL default      configDir                /etc/taos/
05/24 15:06:41.975254 00001523 UTL default      scriptDir                /etc/taos/
05/24 15:06:41.975270 00001523 UTL default      logDir                   /var/log/taos/
05/24 15:06:41.975285 00001523 UTL default      minimalLogDirGB          1.00
05/24 15:06:41.975303 00001523 UTL default      numOfLogLines            10000000
05/24 15:06:41.975319 00001523 UTL default      asyncLog                 1
05/24 15:06:41.975334 00001523 UTL default      logKeepDays              0
05/24 15:06:41.975349 00001523 UTL default      debugFlag                0
05/24 15:06:41.975364 00001523 UTL default      simDebugFlag             143
05/24 15:06:41.975379 00001523 UTL default      tmrDebugFlag             131
05/24 15:06:41.975393 00001523 UTL default      uDebugFlag               131
05/24 15:06:41.975408 00001523 UTL default      rpcDebugFlag             131
05/24 15:06:41.975423 00001523 UTL default      jniDebugFlag             131
05/24 15:06:41.975439 00001523 UTL default      qDebugFlag               131
05/24 15:06:41.975453 00001523 UTL default      cDebugFlag               131
05/24 15:06:41.975469 00001523 UTL default      dDebugFlag               131
05/24 15:06:41.975484 00001523 UTL default      vDebugFlag               131
05/24 15:06:41.975499 00001523 UTL default      mDebugFlag               131
05/24 15:06:41.975515 00001523 UTL default      wDebugFlag               131
05/24 15:06:41.975531 00001523 UTL default      sDebugFlag               131
05/24 15:06:41.975545 00001523 UTL default      tsdbDebugFlag            131
05/24 15:06:41.975560 00001523 UTL default      tqDebugFlag              131
05/24 15:06:41.975575 00001523 UTL default      fsDebugFlag              131
05/24 15:06:41.975591 00001523 UTL default      udfDebugFlag             131
05/24 15:06:41.975607 00001523 UTL default      smaDebugFlag             131
05/24 15:06:41.975622 00001523 UTL default      idxDebugFlag             131
05/24 15:06:41.975647 00001523 UTL default      tdbDebugFlag             131
05/24 15:06:41.975663 00001523 UTL default      metaDebugFlag            131
05/24 15:06:41.975678 00001523 UTL default      timezone                 Asia/Shanghai (CST, +0800)
05/24 15:06:41.975693 00001523 UTL default      locale                   C
05/24 15:06:41.975708 00001523 UTL default      charset                  UTF-8
05/24 15:06:41.975723 00001523 UTL default      assert                   1
05/24 15:06:41.975739 00001523 UTL default      enableCoreFile           1
05/24 15:06:41.975754 00001523 UTL default      numOfCores               4.00
05/24 15:06:41.975771 00001523 UTL default      SSE42                    0
05/24 15:06:41.975786 00001523 UTL default      AVX                      0
05/24 15:06:41.975802 00001523 UTL default      AVX2                     0
05/24 15:06:41.975817 00001523 UTL default      FMA                      0
05/24 15:06:41.975832 00001523 UTL default      SIMD-builtins            0
05/24 15:06:41.975847 00001523 UTL default      openMax                  1024
05/24 15:06:41.975864 00001523 UTL default      streamMax                16
05/24 15:06:41.975879 00001523 UTL default      pageSizeKB               4
05/24 15:06:41.975895 00001523 UTL default      totalMemoryKB            3995652
05/24 15:06:41.975910 00001523 UTL default      os sysname               Linux
05/24 15:06:41.975925 00001523 UTL default      os nodename              YYCUBE
05/24 15:06:41.975941 00001523 UTL default      os release               6.1.25
05/24 15:06:41.975955 00001523 UTL default      os version               #78 SMP Wed Nov  8 18:47:36 CST 2023
05/24 15:06:41.975972 00001523 UTL default      os machine               aarch64
05/24 15:06:41.975987 00001523 UTL default      version                  3.0.2.4
05/24 15:06:41.976002 00001523 UTL default      compatible_version       3.0.0.0
05/24 15:06:41.976017 00001523 UTL default      gitinfo                  c534b3c755fad3b63e840bf3ac74e4677408ca80
05/24 15:06:41.976033 00001523 UTL default      buildinfo                Built at 2024-05-09 14:28:35
05/24 15:06:41.976047 00001523 UTL =================================================================
05/24 15:06:41.984430 00001523 DND start to init dnode env
05/24 15:06:41.984877 00001523 DND succceed to read mnode file /var/lib/taos//dnode/dnode.json
05/24 15:06:41.985079 00001523 DND succceed to read mnode file /var/lib/taos//mnode/mnode.json
05/24 15:06:41.985130 00001523 DND file:/var/lib/taos//qnode/qnode.json not exist
05/24 15:06:41.985159 00001523 DND file:/var/lib/taos//snode/snode.json not exist
05/24 15:06:41.986972 00001523 DND dnode env is initialized
05/24 15:06:41.987046 00001523 DND start to init service
05/24 15:06:41.987123 00001523 DND node:dnode, start to open
05/24 15:06:41.987178 00001523 UTL worker:dnode-mgmt is initialized, min:1 max:1
05/24 15:06:41.987397 00001530 UTL worker:dnode-mgmt:0 is running, thread:00001530
05/24 15:06:41.987373 00001523 UTL worker:dnode-mgmt:0 is launched, total:1
05/24 15:06:41.987442 00001523 UTL worker:dnode-mgmt, queue:0x225a1790 is allocated, ahandle:0x225a15c0
05/24 15:06:41.987872 00001531 UDF start to init udfd
05/24 15:06:41.987986 00001531 UDF udfd LD_LIBRARY_PATH: :
05/24 15:06:41.990640 00001531 UDF ERROR can not spawn udfd. path: /usr/bin/udfd, error: no such file or directory
05/24 15:06:41.990996 00001523 UDF udfd is cleaned up after spawn err
05/24 15:06:41.991043 00001523 DND ERROR failed to start udfd
05/24 15:06:41.991062 00001523 DND node:dnode, has been opened
05/24 15:06:41.991164 00001523 DND node:mnode, start to open
05/24 15:06:41.991324 00001523 WAL wal module is initialized, rsetId:3
05/24 15:06:41.992076 00001523 DND succceed to read mnode file /var/lib/taos//mnode/mnode.json
05/24 15:06:41.992151 00001523 DND mnode start to open
05/24 15:06:41.992178 00001523 MND start to open mnode in /var/lib/taos//mnode
05/24 15:06:41.992851 00001523 WAL vgId:1, reset commitVer to -1
05/24 15:06:41.992910 00001523 MND mnode-wal is initialized
05/24 15:06:41.992971 00001523 MND start to init sdb in /var/lib/taos//mnode
05/24 15:06:41.993042 00001523 MND sdb init success
05/24 15:06:41.993063 00001523 MND mnode-sdb is initialized
05/24 15:06:41.993125 00001523 MND sdb table:trans is initialized
05/24 15:06:41.993144 00001523 MND mnode-trans is initialized
05/24 15:06:41.993176 00001523 MND sdb table:cluster is initialized
05/24 15:06:41.993195 00001523 MND mnode-cluster is initialized
05/24 15:06:41.993217 00001523 MND sdb table:mnode is initialized
05/24 15:06:41.993234 00001523 MND mnode-mnode is initialized
05/24 15:06:41.993298 00001523 MND sdb table:qnode is initialized
05/24 15:06:41.993323 00001523 MND mnode-qnode is initialized
05/24 15:06:41.993358 00001523 MND sdb table:snode is initialized
05/24 15:06:41.993376 00001523 MND mnode-snode is initialized
05/24 15:06:41.993399 00001523 MND sdb table:dnode is initialized
05/24 15:06:41.993422 00001523 MND mnode-dnode is initialized
05/24 15:06:41.993446 00001523 MND sdb table:user is initialized
05/24 15:06:41.993463 00001523 MND mnode-user is initialized
05/24 15:06:41.993479 00001523 MND mnode-grant is initialized
05/24 15:06:41.993500 00001523 MND mnode-privilege is initialized
05/24 15:06:41.993524 00001523 MND sdb table:acct is initialized
05/24 15:06:41.993541 00001523 MND mnode-acct is initialized
05/24 15:06:41.993577 00001523 MND sdb table:stream is initialized
05/24 15:06:41.993601 00001523 MND mnode-stream is initialized
05/24 15:06:41.993625 00001523 MND sdb table:topic is initialized
05/24 15:06:41.993643 00001523 MND mnode-topic is initialized
05/24 15:06:41.993665 00001523 MND sdb table:consumer is initialized
05/24 15:06:41.993687 00001523 MND mnode-consumer is initialized
05/24 15:06:41.993716 00001523 MND sdb table:subscribe is initialized
05/24 15:06:41.993734 00001523 MND mnode-subscribe is initialized
05/24 15:06:41.993756 00001523 MND sdb table:vgroup is initialized
05/24 15:06:41.993778 00001523 MND mnode-vgroup is initialized
05/24 15:06:41.993889 00001523 MND sdb table:stb is initialized
05/24 15:06:41.993910 00001523 MND mnode-stb is initialized
05/24 15:06:41.993935 00001523 MND sdb table:sma is initialized
05/24 15:06:41.993958 00001523 MND mnode-sma is initialized
05/24 15:06:41.994259 00001523 MND mnode-infos is initialized
05/24 15:06:41.994309 00001523 MND mnode-perfs is initialized
05/24 15:06:41.994349 00001523 MND sdb table:db is initialized
05/24 15:06:41.994367 00001523 MND mnode-db is initialized
05/24 15:06:41.994390 00001523 MND sdb table:func is initialized
05/24 15:06:41.994406 00001523 MND mnode-func is initialized
05/24 15:06:41.994587 00001523 MND start to reset sdb
05/24 15:06:41.994619 00001523 MND sdb:trans is reset
05/24 15:06:41.994648 00001523 MND sdb:cluster is reset
05/24 15:06:41.994669 00001523 MND sdb:mnode is reset
05/24 15:06:41.994690 00001523 MND sdb:qnode is reset
05/24 15:06:41.994708 00001523 MND sdb:snode is reset
05/24 15:06:41.994729 00001523 MND sdb:dnode is reset
05/24 15:06:41.994752 00001523 MND sdb:user is reset
05/24 15:06:41.994810 00001523 MND sdb:acct is reset
05/24 15:06:41.994848 00001523 MND sdb:stream is reset
05/24 15:06:41.994892 00001523 MND sdb:subscribe is reset
05/24 15:06:41.994951 00001523 MND sdb:consumer is reset
05/24 15:06:41.994987 00001523 MND sdb:topic is reset
05/24 15:06:41.995026 00001523 MND sdb:vgroup is reset
05/24 15:06:41.995089 00001523 MND sdb:sma is reset
05/24 15:06:41.995128 00001523 MND sdb:stb is reset
05/24 15:06:41.995167 00001523 MND sdb:db is reset
05/24 15:06:41.995219 00001523 MND sdb:func is reset
05/24 15:06:41.995260 00001523 MND sdb reset success
05/24 15:06:41.995297 00001523 MND start to read sdb file:/var/lib/taos//mnode/data/sdb.data
05/24 15:06:41.995608 00001523 MND db:1.db_yunce, tsdbPageSize set from 4 to default 4
05/24 15:06:41.995813 00001523 MND vgId:1, has ready mnode:1, status:ready
05/24 15:06:41.995870 00001523 MND vgId:1, ep:INTOGOAL:6030 dnode:1
05/24 15:06:41.995919 00001523 MND vgId:1, mnode sync not reconfig since readyMnodes:1 updatingMnodes:0
05/24 15:06:41.995989 00001523 MND read sdb file:/var/lib/taos//mnode/data/sdb.data success, commit index:490 term:7 config:-1
05/24 15:06:41.996131 00001523 MND mnode-sdb is initialized
05/24 15:06:41.996520 00001523 MND mnode-profile is initialized
05/24 15:06:41.996642 00001523 MND mnode-show is initialized
05/24 15:06:41.997690 00001523 MND mnode-query is initialized
05/24 15:06:41.997821 00001523 MND vgId:1, start to open sync, replica:0 selfIndex:0
05/24 15:06:41.998121 00001523 SYN vgId:0, succceed to read sync cfg file /var/lib/taos//mnode/sync/raft_config.json
05/24 15:06:41.998205 00001523 SYN vgId:0, use sync config from sync cfg file
05/24 15:06:41.998247 00001523 SYN vgId:1, start to open sync node, replica:1 selfIndex:0
05/24 15:06:41.998291 00001523 SYN vgId:1, index:0 ep:INTOGOAL:6030 dnode:1 cluster:2057381601087199488
05/24 15:06:41.998594 00001523 SYN vgId:1, sync addr:7798573192536129537, dnode:1 cluster:2057381601087199488 fqdn:INTOGOAL ip:127.0.1.1 port:6030 ipv4:16842879
05/24 15:06:41.998723 00001523 SYN vgId:1, sync addr:7798573192536129537, dnode:1 cluster:2057381601087199488 fqdn:INTOGOAL ip:127.0.1.1 port:6030 ipv4:16842879
05/24 15:06:41.998829 00001523 SYN vgId:1, succceed to read raft store file /var/lib/taos//mnode/sync/raft_store.json
05/24 15:06:41.998976 00001523 SYN vgId:1, sync node commitIndex initialized as 490
05/24 15:06:41.999468 00001523 UTL FATAL assert info not provided
05/24 15:06:41.999524 00001523 UTL FATAL tAssert at file /home/yzt/taos/TDengine/source/libs/wal/src/walRead.c:135 exit:1
05/24 15:06:42.000313 00001523 UTL FATAL obtained 1 stack frames
05/24 15:06:42.000407 00001523 UTL FATAL frame:0, taosd(taosAssertDebug+0x1b4) [0x8c5744]
taosd: /home/yzt/taos/TDengine/source/util/src/tlog.c:822: taosAssertDebug: Assertion `0' failed.
05/24 15:06:42.304531 00001523 UTL FATAL crash signal is 6
05/24 15:06:42.304888 00001523 UTL FATAL sender PID:1523 cmdline:taosd
05/24 15:06:42.305797 00001523 UTL FATAL obtained -2 stack frames
Aborted (core dumped)

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
