### ISSUE TITLE
表中出现相同时间戳的数据

### ISSUE THREAD

**Issue by anyedilong** [taosdata/TDengine#25927]
<img width="770" alt="1716530772698" src="https://github.com/taosdata/TDengine/assets/31983335/63bb3667-7907-4f75-9de1-8b85b1f49509">

版本：3.1.1.0
描述：taosdump工具导入；第一个导入文件中有一条时间戳为“2024-05-24 12:00:00.000”的数据，第二个导入文件中也有一条时间戳为“2024-05-24 12:00:00.000”的数据；结果表中出现两条相同时间戳的数据，不应该自动覆盖吗？

**Comment by yu285** [comment]
如果确认所查询目标为子表的话，是已知问题，直接使用最新的3.3.0.3 即可
