### ISSUE TITLE
After data was migrated with taosdump, the tags are not consistent with pre-migration

### ISSUE THREAD

**Issue by fetaoily** [taosdata/TDengine#25982]
**Bug Description**
通过taosdump迁移数据, 新库TAG值与源库不一致

**To Reproduce**
1. 导出命令: `taosdump huak room_temp_t_90886aa4`
2. 导入命令: `taosdump -i .`

**Expected Behavior**
| 源库TAG值  | 新库TAG值-预期 | 新库TAG值-实际 |
|---------|-----------|-----------|
| room_temp_t    | room_temp_t      | room_temp_t6  |
| flow    | flow      | flowress  |
| go_temp | go_temp   | go_temps  |
| hot     | hot       | hotpress  |

**Screenshots**
![2bb1429326d2dad4fdddfc15b4d6e5f](https://github.com/taosdata/TDengine/assets/501984/b69ab290-71e5-4ca6-aab1-b0e3fdca1c79)
![image](https://github.com/taosdata/TDengine/assets/501984/077dc40c-f177-4550-accb-ef483dc85d86)

**Environment (please complete the following information):**

**源库**
taos --version 
version: 2.6.0.24
taosdump --version 
taosdump version 2.2.3

**新库(2.6)**
taos --version 
version: 2.6.0.34
taosdump --version 
taosdump version 2.4.2, commit: 40632cb

**新库(3.0)**
taos --version 
version: 3.3.0.3 compatible_version: 3.0.0.0
gitinfo: 3c12b0f1695c8a47c1bd34cfe22d33843c7ac524
buildInfo: Built Linux-x64 at 2024-05-21 18:08:56 +0800
taosdump --version 
version: 3.3.0.3
gitinfo: e754cc6
buildInfo: Built Linux-x64 at 2024-05-21 18:08:56 +0800

**Additional Context**
源库taosdump升级到2.4.2导出的文件再次导入2.6和3.0版本问题依然存在

**Comment by DuanKuanJun** [comment]
能留个联系方式吗，我们远程上去看下

**Comment by yu285** [comment]
咱做关闭处理，如果用户反馈再做reopen
