### ISSUE TITLE
taosdump还原数据的时候，能否恢复到新的数据库，不是备份的数据库的名字，修改dbs.sql无效

### ISSUE THREAD

**Issue by vjeson** [taosdata/TDengine#26003]
taosdump还原数据的时候，能否恢复到新的数据库，不是备份的数据库的名字，修改dbs.sql无效

查了文档，搜遍网络，没有看到解决办法

修改dbs.sql替换了数据库名字，还原的时候还是恢复到了备份的时候的数据库名字

我需要还原到新的一个数据库和原来不同的名字

**Comment by yu285** [comment]
这个做不到，只能用原名。

**Comment by vjeson** [comment]
为什么呢？这应该是个常见的需求

**Comment by yu285** [comment]
因为工具底层改动会比较大，暂时还不能支持。
