### ISSUE TITLE
failed to init dnode since unsupported platform

### ISSUE THREAD

**Issue by haogghao** [taosdata/TDengine#26009]
TDengine-server-3.3.0.3-Linux-x64 不支持Amazon Linux 2 么？

**Screenshots**

**Environment (please complete the following information):**
 - OS: 
 - NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"

 - TDengine-server-3.3.0.3-Linux-x64

**Additional Context**
06/01 03:56:40.106565 00032360 C DND startup path:/ args:/usr/bin/taosd
06/01 03:56:40.109586 00032360 C UTL apoll url not load
06/01 03:56:40.109710 00032360 C UTL load from cfg file /etc/taos/taos.cfg success
06/01 03:56:40.109722 00032360 C UTL env file:.env not load
06/01 03:56:40.109729 00032360 C UTL load from env variables cfg success
06/01 03:56:40.110047 00032360 C UTL                      global config
06/01 03:56:40.110054 00032360 C UTL =================================================================
06/01 03:56:40.110060 00032360 C UTL default      firstEp                  node01:6030
06/01 03:56:40.110065 00032360 C UTL default      secondEp                 node01:6030
06/01 03:56:40.110068 00032360 C UTL cfg_file     fqdn                     node01
06/01 03:56:40.110073 00032360 C UTL default      serverPort               6030
06/01 03:56:40.110076 00032360 C UTL default      tempDir                  /tmp/
06/01 03:56:40.110080 00032360 C UTL default      minimalTmpDirGB          1.00
06/01 03:56:40.110089 00032360 C UTL default      shellActivityTimer       3
06/01 03:56:40.110093 00032360 C UTL default      compressMsgSize          -1
06/01 03:56:40.110096 00032360 C UTL default      queryPolicy              1
06/01 03:56:40.110100 00032360 C UTL default      enableQueryHb            1
06/01 03:56:40.110104 00032360 C UTL default      enableScience            0
06/01 03:56:40.110108 00032360 C UTL default      querySmaOptimize         0
06/01 03:56:40.110112 00032360 C UTL default      queryPlannerTrace        0
06/01 03:56:40.110116 00032360 C UTL default      queryNodeChunkSize       32768
06/01 03:56:40.110120 00032360 C UTL default      queryUseNodeAllocator    1
06/01 03:56:40.110124 00032360 C UTL default      keepColumnName           0
06/01 03:56:40.110128 00032360 C UTL default      smlChildTableName
06/01 03:56:40.110132 00032360 C UTL default      smlAutoChildTableNameDe
06/01 03:56:40.110136 00032360 C UTL default      smlTagName               _tag_null
06/01 03:56:40.110139 00032360 C UTL default      smlTsDefaultName         _ts
06/01 03:56:40.110143 00032360 C UTL default      smlDot2Underline         1
06/01 03:56:40.110147 00032360 C UTL default      maxShellConns            50000
06/01 03:56:40.110151 00032360 C UTL default      maxInsertBatchRows       1000000
06/01 03:56:40.110154 00032360 C UTL default      maxRetryWaitTime         10000
06/01 03:56:40.110158 00032360 C UTL default      useAdapter               0
06/01 03:56:40.110162 00032360 C UTL default      crashReporting           1
06/01 03:56:40.110166 00032360 C UTL default      queryMaxConcurrentTable  200
06/01 03:56:40.110170 00032360 C UTL default      metaCacheMaxSize         -1
06/01 03:56:40.110174 00032360 C UTL default      slowLogThreshold         3
06/01 03:56:40.110178 00032360 C UTL default      slowLogScope
06/01 03:56:40.110182 00032360 C UTL default      numOfRpcThreads          2
06/01 03:56:40.110185 00032360 C UTL default      numOfRpcSessions         10000
06/01 03:56:40.110189 00032360 C UTL default      timeToGetAvailableConn   500000
06/01 03:56:40.110193 00032360 C UTL default      keepAliveIdle            60
06/01 03:56:40.110196 00032360 C UTL default      numOfTaskQueueThreads    16
06/01 03:56:40.110200 00032360 C UTL default      experimental             1
06/01 03:56:40.110204 00032360 C UTL cfg_file     monitor                  1
06/01 03:56:40.110208 00032360 C UTL default      monitorInterval          30
06/01 03:56:40.110212 00032360 C UTL default      multiResultFunctionStar  0
06/01 03:56:40.110216 00032360 C UTL default      countAlwaysReturnValue   1
06/01 03:56:40.110219 00032360 C UTL default      maxTsmaCalcDelay         600
06/01 03:56:40.110223 00032360 C UTL default      tsmaDataDeleteMark       86400000
06/01 03:56:40.110226 00032360 C UTL default      dataDir                  /var/lib/taos/
06/01 03:56:40.110230 00032360 C UTL default      minimalDataDirGB         2.00
06/01 03:56:40.110235 00032360 C UTL default      supportVnodes            9
06/01 03:56:40.110242 00032360 C UTL default      encryptAlgorithm
06/01 03:56:40.110245 00032360 C UTL default      encryptScope
06/01 03:56:40.110249 00032360 C UTL default      statusInterval           1
06/01 03:56:40.110253 00032360 C UTL default      minSlidingTime           1
06/01 03:56:40.110257 00032360 C UTL default      minIntervalTime          1
06/01 03:56:40.110261 00032360 C UTL default      queryBufferSize          -1
06/01 03:56:40.110265 00032360 C UTL default      queryRspPolicy           0
06/01 03:56:40.110269 00032360 C UTL default      numOfCommitThreads       2
06/01 03:56:40.110272 00032360 C UTL default      numOfMnodeReadThreads    1
06/01 03:56:40.110276 00032360 C UTL default      numOfVnodeQueryThreads   16
06/01 03:56:40.110280 00032360 C UTL default      ratioOfVnodeStreamThrea  0.50
06/01 03:56:40.110285 00032360 C UTL default      numOfVnodeFetchThreads   4
06/01 03:56:40.110288 00032360 C UTL default      numOfVnodeRsmaThreads    4
06/01 03:56:40.110292 00032360 C UTL default      numOfQnodeQueryThreads   16
06/01 03:56:40.110296 00032360 C UTL default      numOfSnodeSharedThreads  2
06/01 03:56:40.110300 00032360 C UTL default      numOfSnodeUniqueThreads  2
06/01 03:56:40.110303 00032360 C UTL default      rpcQueueMemoryAllowed    203120640
06/01 03:56:40.110307 00032360 C UTL default      syncElectInterval        25000
06/01 03:56:40.110311 00032360 C UTL default      syncHeartbeatInterval    1000
06/01 03:56:40.110315 00032360 C UTL default      syncHeartbeatTimeout     20000
06/01 03:56:40.110318 00032360 C UTL default      syncSnapReplMaxWaitN     128
06/01 03:56:40.110322 00032360 C UTL default      arbHeartBeatIntervalSec  5
06/01 03:56:40.110326 00032360 C UTL default      arbCheckSyncIntervalSec  10
06/01 03:56:40.110330 00032360 C UTL default      arbSetAssignedTimeoutSe  30
06/01 03:56:40.110334 00032360 C UTL default      mndSdbWriteDelta         200
06/01 03:56:40.110338 00032360 C UTL default      mndLogRetention          2000
06/01 03:56:40.110342 00032360 C UTL default      skipGrant                0
06/01 03:56:40.110346 00032360 C UTL cfg_file     monitorFqdn              node01
06/01 03:56:40.110349 00032360 C UTL default      monitorPort              6043
06/01 03:56:40.110353 00032360 C UTL default      monitorMaxLogs           100
06/01 03:56:40.110357 00032360 C UTL default      monitorComp              0
06/01 03:56:40.110361 00032360 C UTL default      monitorLogProtocol       0
06/01 03:56:40.110365 00032360 C UTL default      monitorIntervalForBasic  30
06/01 03:56:40.110369 00032360 C UTL default      monitorForceV2           1
06/01 03:56:40.110373 00032360 C UTL cfg_file     audit                    1
06/01 03:56:40.110377 00032360 C UTL default      auditCreateTable         1
06/01 03:56:40.110380 00032360 C UTL default      auditInterval            5000
06/01 03:56:40.110384 00032360 C UTL default      telemetryReporting       1
06/01 03:56:40.110388 00032360 C UTL default      telemetryInterval        43200
06/01 03:56:40.110392 00032360 C UTL default      telemetryServer          telemetry.tdengine.com
06/01 03:56:40.110396 00032360 C UTL default      telemetryPort            80
06/01 03:56:40.110400 00032360 C UTL default      rsyncPort                873
06/01 03:56:40.110404 00032360 C UTL default      snodeAddress
06/01 03:56:40.110407 00032360 C UTL default      checkpointBackupDir      /var/lib/taos/backup/checkpoint/
06/01 03:56:40.110411 00032360 C UTL default      tmqMaxTopicNum           20
06/01 03:56:40.110415 00032360 C UTL default      tmqRowSize               4096
06/01 03:56:40.110418 00032360 C UTL default      maxTsmaNum               3
06/01 03:56:40.110423 00032360 C UTL default      transPullupInterval      2
06/01 03:56:40.110427 00032360 C UTL default      compactPullupInterval    10
06/01 03:56:40.110430 00032360 C UTL default      mqRebalanceInterval      2
06/01 03:56:40.110434 00032360 C UTL default      ttlUnit                  86400
06/01 03:56:40.110437 00032360 C UTL default      ttlPushInterval          10
06/01 03:56:40.110444 00032360 C UTL default      ttlBatchDropNum          10000
06/01 03:56:40.110448 00032360 C UTL default      ttlChangeOnWrite         0
06/01 03:56:40.110452 00032360 C UTL default      ttlFlushThreshold        100
06/01 03:56:40.110456 00032360 C UTL default      trimVDbIntervalSec       3600
06/01 03:56:40.110460 00032360 C UTL default      s3MigrateIntervalSec     3600
06/01 03:56:40.110464 00032360 C UTL default      s3MigrateEnabled         1
06/01 03:56:40.110467 00032360 C UTL default      uptimeInterval           300
06/01 03:56:40.110471 00032360 C UTL default      queryRsmaTolerance       1000
06/01 03:56:40.110475 00032360 C UTL default      timeseriesThreshold      50
06/01 03:56:40.110479 00032360 C UTL default      walFsyncDataSizeLimit    104857600
06/01 03:56:40.110483 00032360 C UTL default      udf                      1
06/01 03:56:40.110487 00032360 C UTL default      udfdResFuncs
06/01 03:56:40.110491 00032360 C UTL default      udfdLdLibPath
06/01 03:56:40.110495 00032360 C UTL default      disableStream            0
06/01 03:56:40.110498 00032360 C UTL default      streamBufferSize         134217728
06/01 03:56:40.110502 00032360 C UTL default      streamAggCnt             100000
06/01 03:56:40.110505 00032360 C UTL default      checkpointInterval       300
06/01 03:56:40.110509 00032360 C UTL default      streamSinkDataRate       2.00
06/01 03:56:40.110514 00032360 C UTL default      cacheLazyLoadThreshold   500
06/01 03:56:40.110518 00032360 C UTL default      fPrecision               0.00
06/01 03:56:40.110523 00032360 C UTL default      dPrecision               0.00
06/01 03:56:40.110527 00032360 C UTL default      maxRange                 500
06/01 03:56:40.110530 00032360 C UTL default      curRange                 100
06/01 03:56:40.110534 00032360 C UTL default      ifAdtFse                 0
06/01 03:56:40.110538 00032360 C UTL default      compressor               ZSTD_COMPRESSOR
06/01 03:56:40.110542 00032360 C UTL default      filterScalarMode         0
06/01 03:56:40.110545 00032360 C UTL default      maxStreamBackendCache    128
06/01 03:56:40.110549 00032360 C UTL default      pqSortMemThreshold       16
06/01 03:56:40.110552 00032360 C UTL default      resolveFQDNRetryTime     100
06/01 03:56:40.110556 00032360 C UTL default      s3Accesskey              <accesskey>
06/01 03:56:40.110560 00032360 C UTL default      s3Endpoint               <endpoint>
06/01 03:56:40.110563 00032360 C UTL default      s3BucketName             <bucketname>
06/01 03:56:40.110567 00032360 C UTL default      s3PageCacheSize          4096
06/01 03:56:40.110570 00032360 C UTL default      s3UploadDelaySec         60
06/01 03:56:40.110574 00032360 C UTL default      minDiskFreeSize          52428800
06/01 03:56:40.110578 00032360 C UTL default      enableWhiteList          0
06/01 03:56:40.110582 00032360 C UTL default      configDir                /etc/taos/
06/01 03:56:40.110586 00032360 C UTL default      scriptDir                /etc/taos/
06/01 03:56:40.110590 00032360 C UTL default      logDir                   /var/log/taos/
06/01 03:56:40.110597 00032360 C UTL default      minimalLogDirGB          1.00
06/01 03:56:40.110601 00032360 C UTL default      numOfLogLines            10000000
06/01 03:56:40.110605 00032360 C UTL default      asyncLog                 1
06/01 03:56:40.110609 00032360 C UTL default      logKeepDays              0
06/01 03:56:40.110613 00032360 C UTL default      debugFlag                0
06/01 03:56:40.110616 00032360 C UTL default      simDebugFlag             131
06/01 03:56:40.110621 00032360 C UTL default      tmrDebugFlag             131
06/01 03:56:40.110625 00032360 C UTL default      uDebugFlag               131
06/01 03:56:40.110628 00032360 C UTL default      rpcDebugFlag             131
06/01 03:56:40.110633 00032360 C UTL default      jniDebugFlag             131
06/01 03:56:40.110636 00032360 C UTL default      qDebugFlag               131
06/01 03:56:40.110640 00032360 C UTL default      cDebugFlag               131
06/01 03:56:40.110647 00032360 C UTL default      dDebugFlag               131
06/01 03:56:40.110651 00032360 C UTL default      vDebugFlag               131
06/01 03:56:40.110655 00032360 C UTL default      mDebugFlag               131
06/01 03:56:40.110659 00032360 C UTL default      wDebugFlag               131
06/01 03:56:40.110663 00032360 C UTL default      sDebugFlag               131
06/01 03:56:40.110666 00032360 C UTL default      tsdbDebugFlag            131
06/01 03:56:40.110670 00032360 C UTL default      tqDebugFlag              131
06/01 03:56:40.110674 00032360 C UTL default      fsDebugFlag              131
06/01 03:56:40.110677 00032360 C UTL default      udfDebugFlag             131
06/01 03:56:40.110681 00032360 C UTL default      smaDebugFlag             131
06/01 03:56:40.110685 00032360 C UTL default      idxDebugFlag             131
06/01 03:56:40.110689 00032360 C UTL default      tdbDebugFlag             131
06/01 03:56:40.110693 00032360 C UTL default      metaDebugFlag            131
06/01 03:56:40.110697 00032360 C UTL default      stDebugFlag              131
06/01 03:56:40.110701 00032360 C UTL default      sndDebugFlag             131
06/01 03:56:40.110704 00032360 C UTL default      timezone                 UTC (UTC, +0000)
06/01 03:56:40.110707 00032360 C UTL default      locale                   en_US.UTF-8
06/01 03:56:40.110711 00032360 C UTL default      charset                  UTF-8
06/01 03:56:40.110715 00032360 C UTL default      assert                   1
06/01 03:56:40.110719 00032360 C UTL default      enableCoreFile           1
06/01 03:56:40.110722 00032360 C UTL default      numOfCores               2.00
06/01 03:56:40.110727 00032360 C UTL default      ssd42                    0
06/01 03:56:40.110731 00032360 C UTL default      avx                      0
06/01 03:56:40.110734 00032360 C UTL default      avx2                     0
06/01 03:56:40.110738 00032360 C UTL default      fma                      0
06/01 03:56:40.110742 00032360 C UTL default      avx512                   0
06/01 03:56:40.110745 00032360 C UTL default      simdEnable               0
06/01 03:56:40.110749 00032360 C UTL default      tagFilterCache           0
06/01 03:56:40.110753 00032360 C UTL default      openMax                  1048576
06/01 03:56:40.110756 00032360 C UTL default      streamMax                16
06/01 03:56:40.110761 00032360 C UTL default      pageSizeKB               4
06/01 03:56:40.110765 00032360 C UTL default      totalMemoryKB            1983600
06/01 03:56:40.110768 00032360 C UTL default      os sysname               Linux
06/01 03:56:40.110772 00032360 C UTL default      os nodename              ip.ap-northeast-1.compute.internal
06/01 03:56:40.110776 00032360 C UTL default      os release               5.10.106-102.504.amzn2.x86_64
06/01 03:56:40.110779 00032360 C UTL default      os version               #1 SMP Tue Mar 29 23:15:13 UTC 2022
06/01 03:56:40.110783 00032360 C UTL default      os machine               x86_64
06/01 03:56:40.110787 00032360 C UTL default      version                  3.3.0.3
06/01 03:56:40.110791 00032360 C UTL default      compatible_version       3.0.0.0
06/01 03:56:40.110795 00032360 C UTL default      gitinfo                  3c12b0f1695c8a47c1bd34cfe22d33843c7ac524
06/01 03:56:40.110798 00032360 C UTL default      buildinfo                Built Linux-x64 at 2024-05-21 18:08:56 +0800
06/01 03:56:40.110802 00032360 C UTL =================================================================
06/01 03:56:40.116739 00032360 C DND start to init dnode env
06/01 03:56:40.117143 00032360 C DND dnode file:/var/lib/taos//dnode/dnode.json not exist
06/01 03:56:40.117184 00032360 C DND mnode file:/var/lib/taos//mnode/mnode.json not exist
06/01 03:56:40.117189 00032360 C DND deploy mnode required. dnodeId:0<=0, clusterId:0<=0, localEp:node01:6030==firstEp
06/01 03:56:40.117197 00032360 C DND file:/var/lib/taos//qnode/qnode.json not exist
06/01 03:56:40.117202 00032360 C DND file:/var/lib/taos//snode/snode.json not exist
06/01 03:56:40.117376 00032360 C DND ERROR failed to create dnode since Not found
06/01 03:56:40.117384 00032360 C DND ERROR failed to init dnode since unsupported platform, please visit https://www.taosdata.com for support

**Comment by yu285** [comment]
https://docs.taosdata.com/reference/support-platform/

支持平台范围参考

**Comment by dim-sniffier** [comment]
同样，阿里云CentOS8变种也不支持。”Alibaba Cloud Linux 3.2104 LTS 64位“07/25 10:56:40.331188 03257975 C DND file:/var/lib/taos//snode/snode.json not exist
07/25 10:56:40.331311 03257975 C DND ERROR failed to create dnode since Not found
07/25 10:56:40.331319 03257975 C DND ERROR failed to init dnode since unsupported platform, please visit https://www.taosdata.com for support

**Comment by bookgh** [comment]
rockylinux 9.4 也不支持

08/08 15:16:47.638670 00044267 DND ERROR failed to create dnode since Not found
08/08 15:16:47.638687 00044267 DND ERROR failed to init dnode since unsupported platform, please visit https://www.taosdata.com for support

# cat /etc/os-release
NAME="Rocky Linux"
VERSION="9.4 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.4 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.4"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"

**Comment by Justme0** [comment]
> 抱歉，不太理解。 我理解 Amazon Linux 2 跟 CentOS 7+ 是兼容的。 意思是说目前TDengine-server-3.3.0.3-Linux-x64 不支持Amazon Linux 2 么？

与支持平台兼容的话可以这样改下源码

![image](https://github.com/user-attachments/assets/d3641ea0-f285-4238-9253-655e7757cfc1)


```
  if (sName) tstrncpy(sName, "CentOS Linux", maxLen);
  if (releaseName) tstrncpy(releaseName, "CentOS Linux 7 (Core)", maxLen);
  if (ver) tstrncpy(ver, "7", maxLen);
```
