### ISSUE TITLE
csv文件导入失败

### ISSUE THREAD

**Issue by BearTian** [taosdata/TDengine#2600]
**Bug Description**
如图
![image](https://user-images.githubusercontent.com/20335105/86900769-57990280-c13e-11ea-9ca0-6fa1c0649352.png)

**To Reproduce**
1. sql写入数据
2. 导出cheng成csv
3. 去除csv的表头，修改为新的时间戳（修改后的csv列数一致，内如如图）
![image](https://user-images.githubusercontent.com/20335105/86900806-6384c480-c13e-11ea-9916-3742f3c524c7.png)

4. 导入失败

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by Aries-Lee1991** [comment]
你这个版本太老了，先升级一下吧，看看是否还有问题。1.6.1.7，应该已经不维护了。

**Comment by BearTian** [comment]
升级到 下面的版本还是有问题
community version: 1.6.6.0 compatible_version: 1.6.0.0
gitinfo: 1e638278130f3901f547f5b4d11614edc924a6f1
gitinfoI:
buildinfo: Built by root at 2020-06-11 14:28

**Comment by BearTian** [comment]
问题已找到，带路径导入失败，不带路径导入成功

**Comment by Shawshank-Smile** [comment]
路径需要加上“”

**Comment by BearTian** [comment]
辛苦补充下文档： https://www.taosdata.com/cn/documentation/administrator/#%E6%95%B0%E6%8D%AE%E5%AF%BC%E5%85%A5
