### ISSUE TITLE
Ambiguity in official documentation

### ISSUE THREAD

**Issue by YeatsLiao** [taosdata/TDengine#26076]
**General Questions**

In the data writing - data source of the Cloud Chinese document, Influexdb seems to be a wrong statement, should it all refer to InfluxDB and its data source and database?
https://docs.taosdata.com/cloud/data-in/ds/
![image](https://github.com/taosdata/TDengine/assets/68049064/275f026f-53e0-41d9-9a81-40f05520772b)

But this is not the case in the English documentation.
https://docs.tdengine.com/cloud/data-in/ds/influx/
![image](https://github.com/taosdata/TDengine/assets/68049064/e3a4c1e1-5494-4982-aa02-12afba33fcf8)

Perhaps the wording should be uniform :)

**Comment by yu285** [comment]
thanks for your feedback

**Comment by yu285** [comment]
we will fix these

**Comment by yu285** [comment]
we already fixed these ,
thanks for your feedback
