### ISSUE TITLE
2.6.0.34版本内存占用过高，无法释放

### ISSUE THREAD

**Issue by IAseven** [taosdata/TDengine#26098]
**Performance Issue** 
taosd 内存占用过高，一直无法释放

**Problem Description** 
三个节点集群，副本数为1，总数据库的数量大概是100个，总表数大概是6000万张表，
每台物理机的内存大概是190G，现在每台机器的内存一直占用很高，无法释放

**Screenshots**
![图片](https://github.com/taosdata/TDengine/assets/38178039/a5545605-361e-4434-8de1-d7bd9c20f083)

**Environment (please complete the following information):**
配置全部是安装时的默认配置，

* OS: [BigCloud Enterprise Linux For Euler release 21.10 (LTS-SP2)]
* Memory, CPU, current Disk Space
* TDengine Version [2.6.0.34]

请问如何处理来降低物理内存的使用

**Comment by yu285** [comment]
2.6官方已经不维护了，您这个体量还比较大，加我微信一下吧。
a15652223354

**Comment by IAseven** [comment]
已加您微信
