### ISSUE TITLE
taos-jdbcdriver 版本问题（tdengine：3.3.1.0）

### ISSUE THREAD

**Issue by xghjbvvg** [taosdata/TDengine#26141]
tdengine：3.3.1.0
taos-jdbcdriver：3.2.11、3.2.10、3.2.09、3.2.08

以上taos-jdbcdriver都不兼容tdengine3.3版本，请问一下对应的taos-jdbcdriver是多少呢
java.sql.SQLException: JNI ERROR (0x2354): Version not compatible
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:90)

**Comment by imborntowin** [comment]
3.3.0吧
