### ISSUE TITLE
docker 国内镜像被封后，有其他方法可以拉取镜像吗

### ISSUE THREAD

**Issue by veigara** [taosdata/TDengine#26156]
docker 国内镜像被封后，有其他方法可以拉取镜像吗，比如：开放docke镜像得本地下载地址或者公布docker镜像构建得源代码,自己构建

**Comment by yu285** [comment]
这个只能自己想一下办法了，或者看其他用户能不能给出一些建议

**Comment by veigara** [comment]
没翻墙啊，直接就能访问的

**Comment by dengbin40** [comment]
> 没翻墙啊，就能访问的

https://mp.weixin.qq.com/s/HAvENKkcjJn8PjNp8whBTw

**Comment by hoilung** [comment]
网上那么多反代的加速镜像，找上一个就能解决，或者自建一个

**Comment by quanlu45** [comment]
docker pull dockerproxy.cn/tdengine/tdengine:latest
