### ISSUE TITLE
AlmaLinux9.3 安装TDengine3.3.1.0后，taosd启动不了

### ISSUE THREAD

**Issue by tnucat** [taosdata/TDengine#26184]
操作系统版本：AlmaLinux9.3
TDengine版本：3.3.1.0

安装完成
![image](https://github.com/taosdata/TDengine/assets/153151457/4697dff2-6253-4ee3-baf6-ce3c9e3875ab)

查看状态
![image](https://github.com/taosdata/TDengine/assets/153151457/b3c3d3f8-959f-4dcb-8cc8-fd742b5ee2b3)

**Comment by yu285** [comment]
https://docs.taosdata.com/reference/support-platform/

3.1.0.0 以及之后的版本，支持范围参考：
