### ISSUE TITLE
将旧库数据库备份导入新库，发现旧库储存空间占用异常

### ISSUE THREAD

**Issue by zhuangQingGuang** [taosdata/TDengine#26203]
现象：
将数据库全量备份出来后 导入新库 磁盘空间占用减少90%
版本：旧库3.2.0，新库3.3.0
旧库
![1](https://github.com/taosdata/TDengine/assets/45782190/e043c24e-622f-43a9-9e03-3838a0684823)
新库
![2](https://github.com/taosdata/TDengine/assets/45782190/b7c62d16-0a77-408c-bbff-a8c7385bb0f6)
是否新库运行时间长了也会出现这个情况，该如何清理异常的存储

**Comment by boomion** [comment]
我的旧库都快3个T了，导入新库也才100多G，也不知道怎么处理，只能换企业版？

**Comment by yu285** [comment]
将数据库全量备份出来后 导入新库 磁盘空间占用减少90%

可能是旧库建模有问题，压缩率没上去。建议检查数据优先，不要看磁盘大小

**Comment by zhuangQingGuang** [comment]
> 将数据库全量备份出来后 导入新库 磁盘空间占用减少90%
> 
> 可能是旧库建模有问题，压缩率没上去。建议检查数据优先，不要看磁盘大小

现在旧库还在用 但是想优化释放一些空间有什么办法吗 能否帮忙看下是什么原因造成的

**Comment by xiaohu89** [comment]
> > 将数据库全量备份出来后 导入新库 磁盘空间占用减少90%
> > 可能是旧库建模有问题，压缩率没上去。建议检查数据优先，不要看磁盘大小
> 
> 现在旧库还在用 但是想优化释放一些空间有什么办法吗 能否帮忙看下是什么原因造成的

问下这个问题解决了么？2.x版本也有数据文件增长过快的问题，update设置为0就好很多，还以为3.0有改善，这样升级的意义不大呀

**Comment by zhuangQingGuang** [comment]
> > > 将数据库全量备份出来后 导入新库 磁盘空间占用减少90%
> > > 可能是旧库建模有问题，压缩率没上去。建议检查数据优先，不要看磁盘大小
> > 
> > 
> > 现在旧库还在用 但是想优化释放一些空间有什么办法吗 能否帮忙看下是什么原因造成的
> 
> 问下这个问题解决了么？2.x版本也有数据文件增长过快的问题，update设置为0就好很多，还以为3.0有改善，这样升级的意义不大呀

我这边初步排查是流计算引起的 几条简单的流计算  一个VNODE下就有100G

**Comment by xiaohu89** [comment]
> > > > 将数据库全量备份出来后 导入新库 磁盘空间占用减少90%
> > > > 可能是旧库建模有问题，压缩率没上去。建议检查数据优先，不要看磁盘大小
> > > 
> > > 
> > > 现在旧库还在用 但是想优化释放一些空间有什么办法吗 能否帮忙看下是什么原因造成的
> > 
> > 
> > 问下这个问题解决了么？2.x版本也有数据文件增长过快的问题，update设置为0就好很多，还以为3.0有改善，这样升级的意义不大呀
> 
> 我这边初步排查是流计算引起的 几条简单的流计算 一个VNODE下就有100G

嗯嗯，不做流计算每日的数据文件增长快么？我是2.0版本，将update设置为1后，每天数据文件增长5G左右，不知道3.0版本有没有这个问题？

**Comment by zhuangQingGuang** [comment]
> > > > > 将数据库全量备份出来后 导入新库 磁盘空间占用减少90%
> > > > > 可能是旧库建模有问题，压缩率没上去。建议检查数据优先，不要看磁盘大小
> > > > 
> > > > 
> > > > 现在旧库还在用 但是想优化释放一些空间有什么办法吗 能否帮忙看下是什么原因造成的
> > > 
> > > 
> > > 问下这个问题解决了么？2.x版本也有数据文件增长过快的问题，update设置为0就好很多，还以为3.0有改善，这样升级的意义不大呀
> > 
> > 
> > 我这边初步排查是流计算引起的 几条简单的流计算 一个VNODE下就有100G
> 
> 嗯嗯，不做流计算每日的数据文件增长快么？我是2.0版本，将update设置为1后，每天数据文件增长5G左右，不知道3.0版本有没有这个问题？

我这边没有修改update  除去流计算应该是正常的

**Comment by xiaohu89** [comment]
> > > > > > 将数据库全量备份出来后 导入新库 磁盘空间占用减少90%
> > > > > > 可能是旧库建模有问题，压缩率没上去。建议检查数据优先，不要看磁盘大小
> > > > > 
> > > > > 
> > > > > 现在旧库还在用 但是想优化释放一些空间有什么办法吗 能否帮忙看下是什么原因造成的
> > > > 
> > > > 
> > > > 问下这个问题解决了么？2.x版本也有数据文件增长过快的问题，update设置为0就好很多，还以为3.0有改善，这样升级的意义不大呀
> > > 
> > > 
> > > 我这边初步排查是流计算引起的 几条简单的流计算 一个VNODE下就有100G
> > 
> > 
> > 嗯嗯，不做流计算每日的数据文件增长快么？我是2.0版本，将update设置为1后，每天数据文件增长5G左右，不知道3.0版本有没有这个问题？
> 
> 我这边没有修改update 除去流计算应该是正常的

平时更新覆盖相同时间戳数据的场景多么？

**Comment by zhuangQingGuang** [comment]
> > > > > > > 将数据库全量备份出来后 导入新库 磁盘空间占用减少90%
> > > > > > > 可能是旧库建模有问题，压缩率没上去。建议检查数据优先，不要看磁盘大小
> > > > > > 
> > > > > > 
> > > > > > 现在旧库还在用 但是想优化释放一些空间有什么办法吗 能否帮忙看下是什么原因造成的
> > > > > 
> > > > > 
> > > > > 问下这个问题解决了么？2.x版本也有数据文件增长过快的问题，update设置为0就好很多，还以为3.0有改善，这样升级的意义不大呀
> > > > 
> > > > 
> > > > 我这边初步排查是流计算引起的 几条简单的流计算 一个VNODE下就有100G
> > > 
> > > 
> > > 嗯嗯，不做流计算每日的数据文件增长快么？我是2.0版本，将update设置为1后，每天数据文件增长5G左右，不知道3.0版本有没有这个问题？
> > 
> > 
> > 我这边没有修改update 除去流计算应该是正常的
> 
> 平时更新覆盖相同时间戳数据的场景多么？

很少
