### ISSUE TITLE
如何查看topic是基于哪张表创建的？

### ISSUE THREAD

**Issue by Wuyiz** [taosdata/TDengine#26215]
有没有命令或语句可以查看指定topic的建立语句呢？

我从官方文档里并没有看到如何查询topic详情的相关内容，导致很多时候想要查看一个topic就只能建立消费者消费数据后，再反向分析出来（有些topic是其他开发者建立的时候，就只能问他们或者自己分析）

**Comment by yu285** [comment]
可查看information_schema库下的  ins_topics 表获取相关信息。

**Comment by Wuyiz** [comment]
> 可查看information_schema库下的 ins_topics 表获取相关信息。

感谢！
