### ISSUE TITLE
按照官方文档上的部署。报错。

### ISSUE THREAD

**Issue by wo494945137** [taosdata/TDengine#26249]
![image](https://github.com/taosdata/TDengine/assets/24561267/c97e5955-d959-48ae-9ddc-2d07e2dfc338)
![0104c4f28961ccf927d7b69bf993062](https://github.com/taosdata/TDengine/assets/24561267/6c0edb67-ddec-42d1-9935-61bbaf914777)

![84fe83f71d3857102dee756633463a6](https://github.com/taosdata/TDengine/assets/24561267/8840d6da-8339-459c-8402-cf6c1ecd605f)
我按照官方文档的步骤部署，报错呀。请问怎么解决。

**Comment by yu285** [comment]
我们正在修改entrypoint，优化后会通知大家

**Comment by Fiuck** [comment]
我今天在k8s上部署也出现了这个问题，tdengine-0启动成功后，tdengine-1一直起不来，这是tdengine-1的容器日志
 sysctl: setting key "kernel.core_pattern", ignoring: Read-only file system

 2: service ok

 execute create dnode

 Welcome to the TDengine Command Line Interface, Client Version:3.3.0.0

 Copyright (c) 2023 by TDengine, all rights reserved.

 

 

 DB error: Dnode already exists (0.001681s)

 taos> create dnode "tdengine-1.taosd.sdhn.svc.cluster.local:6030";

 TDengine is running

 07/27 18:33:35.494675 00000089 taos_ADAPTER info "start server:00000089" model=main

 [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.

  - using env:	export GIN_MODE=release

  - using code:	gin.SetMode(gin.ReleaseMode)

 

 [GIN-debug] GET    /debug/pprof/             --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)

 [GIN-debug] GET    /debug/pprof/cmdline      --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)

 [GIN-debug] GET    /debug/pprof/profile      --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)

 [GIN-debug] POST   /debug/pprof/symbol       --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)

 [GIN-debug] GET    /debug/pprof/symbol       --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)

 [GIN-debug] GET    /debug/pprof/trace        --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)

 [GIN-debug] GET    /debug/pprof/allocs       --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)

 [GIN-debug] GET    /debug/pprof/block        --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)

 [GIN-debug] GET    /debug/pprof/goroutine    --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)

 [GIN-debug] GET    /debug/pprof/heap         --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)

 [GIN-debug] GET    /debug/pprof/mutex        --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)

 [GIN-debug] GET    /debug/pprof/threadcreate --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)

 [GIN-debug] GET    /metrics                  --> github.com/gin-gonic/gin.WrapH.func1 (5 handlers)

 [GIN-debug] GET    /-/ping                   --> github.com/taosdata/taosadapter/v3/controller/ping.Controller.Init.func1 (5 handlers)

 [GIN-debug] POST   /rest/sql                 --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).sql-fm (8 handlers)

 [GIN-debug] POST   /rest/sql/:db             --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).sql-fm (8 handlers)

 [GIN-debug] POST   /rest/sql/:db/vgid        --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).tableVgID-fm (7 handlers)

 [GIN-debug] GET    /rest/login/:user/:password --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).des-fm (6 handlers)

 [GIN-debug] POST   /rest/upload              --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).upload-fm (7 handlers)

 [GIN-debug] GET    /rest/ws                  --> github.com/taosdata/taosadapter/v3/controller/ws/query.(*QueryController).Init.func1 (5 handlers)

 [GIN-debug] GET    /rest/schemaless          --> github.com/taosdata/taosadapter/v3/controller/ws/schemaless.(*SchemalessController).Init.func1 (5 handlers)

 [GIN-debug] GET    /rest/stmt                --> github.com/taosdata/taosadapter/v3/controller/ws/stmt.(*STMTController).Init.func1 (5 handlers)

 [GIN-debug] GET    /rest/tmq                 --> github.com/taosdata/taosadapter/v3/controller/ws/tmq.(*TMQController).Init.func1 (5 handlers)

 [GIN-debug] GET    /ws                       --> github.com/taosdata/taosadapter/v3/controller/ws/ws.(*webSocketCtl).Init.func1 (5 handlers)

 [GIN-debug] GET    /genauth/:user/:password/:key --> github.com/taosdata/taosadapter/v3/plugin.RegisterGenerateAuth.func1 (5 handlers)

 07/27 18:33:35.494984 00000089 taos_ADAPTER info "init plugin opentsdb_telnet/v1" model=plugin

 07/27 18:33:35.496002 00000089 taos_ADAPTER info "opentsdb_telnet disabled" model=opentsdb_telnet

 07/27 18:33:35.496014 00000089 taos_ADAPTER info "init plugin prometheus/v1" model=plugin

 [GIN-debug] POST   /prometheus/v1/remote_read/:db --> github.com/taosdata/taosadapter/v3/plugin/prometheus.(*Plugin).Read-fm (7 handlers)

 [GIN-debug] POST   /prometheus/v1/remote_write/:db --> github.com/taosdata/taosadapter/v3/plugin/prometheus.(*Plugin).Write-fm (7 handlers)

 07/27 18:33:35.496153 00000089 taos_ADAPTER info "init plugin statsd/v1" model=plugin

 07/27 18:33:35.497673 00000089 taos_ADAPTER info "statsd disabled" model=statsd

 07/27 18:33:35.497694 00000089 taos_ADAPTER info "init plugin collectd/v1" model=plugin

 07/27 18:33:35.498362 00000089 taos_ADAPTER info "collectd disabled" model=collectd

 07/27 18:33:35.498368 00000089 taos_ADAPTER info "init plugin influxdb/v1" model=plugin

 [GIN-debug] POST   /influxdb/v1/write        --> github.com/taosdata/taosadapter/v3/plugin/influxdb.(*Influxdb).write-fm (7 handlers)

 07/27 18:33:35.498526 00000089 taos_ADAPTER info "init plugin node_exporter/v1" model=plugin

 07/27 18:33:35.500022 00000089 taos_ADAPTER info "node_exporter disabled" model=NodeExporter

 07/27 18:33:35.500032 00000089 taos_ADAPTER info "init plugin opentsdb/v1" model=plugin

 [GIN-debug] POST   /opentsdb/v1/put/json/:db --> github.com/taosdata/taosadapter/v3/plugin/opentsdb.(*Plugin).insertJson-fm (7 handlers)

 [GIN-debug] POST   /opentsdb/v1/put/telnet/:db --> github.com/taosdata/taosadapter/v3/plugin/opentsdb.(*Plugin).insertTelnet-fm (7 handlers)

 07/27 18:33:35.500413 00000089 taos_ADAPTER info "all plugin init finish" model=plugin

 07/27 18:33:35.500425 00000089 taos_ADAPTER info "all plugin start finish" model=plugin

 07/27 18:33:35.500506 00000089 taos_ADAPTER info "Running in terminal." model=main

 07/27 18:33:35.501177 00000089 taos_ADAPTER info "server on : 6041" model=main

 07/27 18:33:38.826162 00000125 warning "create database sql: create database if not exists log cachemodel 'none' " model=report

 07/27 18:33:38.831416 00000125 error "create database log error Post "http://buildkitsandbox:6041/rest/sql": dial tcp: lookup buildkitsandbox on 169.254.25.10:53: no such host" error=Post "http://buildkitsandbox:6041/rest/sql": dial tcp: lookup buildkitsandbox on 169.254.25.10:53: no such host model=report

 panic: Post "http://buildkitsandbox:6041/rest/sql": dial tcp: lookup buildkitsandbox on 169.254.25.10:53: no such host

 

 goroutine 1 [running]:

 github.com/taosdata/taoskeeper/api.(*Reporter).createDatabase(0xc00010ea20)

 	/data/release/main/taoskeeper/api/report.go:261 +0x316

 github.com/taosdata/taoskeeper/api.(*Reporter).Init(0xc000003080?, {0xe73338, 0xc0001031e0})

 	/data/release/main/taoskeeper/api/report.go:60 +0x8e

 github.com/taosdata/taoskeeper/system.Init()

 	/data/release/main/taoskeeper/system/program.go:39 +0xae

 main.main()

 	/data/release/main/taoskeeper/main.go:8 +0x19

 Use configuration file path: /etc/taos/explorer.toml

 2024-07-27T10:33:48.786489Z  INFO main ThreadId(01) taos_explorer: Starting server at 0.0.0.0:6060

 2024-07-27T10:33:48.786534Z  INFO main ThreadId(01) actix_server::builder: starting 4 workers

 2024-07-27T10:33:48.786540Z  INFO main ThreadId(01) actix_server::server: Actix runtime found; starting in Actix runtime
 
然后tdengine-0容器一直在刷新这个日志

 07/27 18:53:27.631002 00000051 C UDF start to init udfd

 07/27 18:53:27.631048 00000051 C UDF udfd LD_LIBRARY_PATH: ::/usr/lib

 07/27 18:53:27.655625 00000051 C UDF udfd is initialized

 07/27 18:53:27.660673 00000051 C UDF udfd process exited with status 254, signal 0

 07/27 18:53:27.660694 00000051 C UDF udfd process restart

 07/27 18:53:27.660697 00000051 C UDF start to init udfd

 07/27 18:53:27.660744 00000051 C UDF udfd LD_LIBRARY_PATH: ::/usr/lib

 07/27 18:53:27.684818 00000051 C UDF udfd is initialized

 07/27 18:53:27.689873 00000051 C UDF udfd process exited with status 254, signal 0

 07/27 18:53:27.689886 00000051 C UDF udfd process restart

 07/27 18:53:27.689889 00000051 C UDF start to init udfd

 07/27 18:53:27.689936 00000051 C UDF udfd LD_LIBRARY_PATH: ::/usr/lib

 07/27 18:53:27.716497 00000051 C UDF udfd is initialized

 07/27 18:53:27.722626 00000051 C UDF udfd process exited with status 254, signal 0

 07/27 18:53:27.722640 00000051 C UDF udfd process restart

 07/27 18:53:27.722642 00000051 C UDF start to init udfd

 07/27 18:53:27.722716 00000051 C UDF udfd LD_LIBRARY_PATH: ::/usr/lib

 07/27 18:53:27.747696 00000051 C UDF udfd is initialized

 07/27 18:53:27.752705 00000051 C UDF udfd process exited with status 254, signal 0

 07/27 18:53:27.752722 00000051 C UDF udfd process restart

 07/27 18:53:27.752725 00000051 C UDF start to init udfd

 07/27 18:53:27.752778 00000051 C UDF udfd LD_LIBRARY_PATH: ::/usr/lib

**Comment by zkd1998** [comment]
我也是这个问题，现在这个问题解决了吗

**Comment by qtsunk** [comment]
官方的dockerfile和docker-entrypoint.sh写的跟屎一样，官方镜像根本不能正常使用。要自己重新改造下docker-entrypoint.sh才行。

**Comment by yu285** [comment]
更新到3.3.3.0 ，此问题已经解决。
