### ISSUE TITLE
docker-compose 部署集群报错

### ISSUE THREAD

**Issue by cuihaodong0919** [taosdata/TDengine#26243]
**hosts配置**
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.x.x td.master
192.168.x.x td.slave1
192.168.x.x td.slave2
**docker-compose启动的yml文件**
![image](https://github.com/taosdata/TDengine/assets/172091362/3ab9b7a6-f9dc-4915-86c3-60882e9204d0)
**taos.cfg配置文件**
![image](https://github.com/taosdata/TDengine/assets/172091362/c3626579-1c7a-4cb6-b566-e8d179132396)
**主节点启动报错**
06/21 16:16:19.182452 00000061 DND start to init dnode env
06/21 16:16:19.182884 00000061 DND dnode file:/var/lib/taos//dnode/dnode.json not exist
06/21 16:16:19.182927 00000061 DND mnode file:/var/lib/taos//mnode/mnode.json not exist
06/21 16:16:19.182931 00000061 DND deploy mnode required. dnodeId:0<=0, clusterId:0<=0, localEp:td.master:6030==firstEp
06/21 16:16:19.182937 00000061 DND file:/var/lib/taos//qnode/qnode.json not exist
06/21 16:16:19.182943 00000061 DND file:/var/lib/taos//snode/snode.json not exist
06/21 16:16:19.183264 00000061 DND ERROR failed to init dnode rpc server
06/21 16:16:19.183277 00000061 DND ERROR failed to init transport since Cannot assign requested address
06/21 16:16:19.183286 00000061 DND ERROR failed to create dnode since Cannot assign requested address
06/21 16:16:19.183289 00000061 DND ERROR failed to init dnode since Cannot assign requested address

**Comment by luojiyin1987** [comment]
目录挂载是  
```shell
/data/docker/tdengine/logs:/var/log/taos
``` 
还是 
```shell
./data/docker/tdengine/logs:/var/log/taos   
```
?
