### ISSUE TITLE
OpenEuler安装3.1.0.0及以上版本可以安装成功，但运行失败

### ISSUE THREAD

**Issue by chaoyuepure** [taosdata/TDengine#26266]
**Bug Description**
OpenEuler安装3.1.0.0及以上版本可以安装成功，但运行失败

**Environment (please complete the following information):**
 - OS: [e.g. OpenEuler 22.03]
 - TDengine Version [e.g. 3.1.0.0]+

**Comment by yu285** [comment]
https://docs.taosdata.com/reference/support-platform/

3.1.0.0 以及之后的版本，支持范围参考：
