### ISSUE TITLE
插入时间2014年以前的数据插入不进去。

### ISSUE THREAD

**Issue by Shmaur** [taosdata/TDengine#26276]
**Bug Description**
![image](https://github.com/taosdata/TDengine/assets/23330527/40836e62-d136-4ccb-ac6f-b13c50b64287)

如图

版本：
Client **Version:3.3.0.0**
TDengine-server-3.3.0.0

服务器时区：
![image](https://github.com/taosdata/TDengine/assets/23330527/724d8103-8de8-4e69-af69-38a2efc2a80c)

**Comment by yu285** [comment]
https://mp.weixin.qq.com/s/uJEQwN0NnmSTBAMOecAtoA

可以看下，如果还有问题请加微信a15652223354
