### ISSUE TITLE
插入几千条数据之后，命令行查询会死锁，golang查询会出现乱码

### ISSUE THREAD

**Issue by hsnxiaoning** [taosdata/TDengine#263]

**Comment by plum-lihui** [comment]
您能将测试步骤详细描述一下吗？我们试试来复现问题，这样比较好定位。多谢！

**Comment by hsnxiaoning** [comment]
> 您能将测试步骤详细描述一下吗？我们试试来复现问题，这样比较好定位。多谢！

具体代码我没有保存，步骤是通过golang的sql连接到数据库，批量插入数据，数据插入后通过sql接口查询，有乱码，通过命令行查询会卡住死锁，猜测是cgo和c类型问题或指针问题，问题应该是在插入时

**Comment by plum-lihui** [comment]
批量插入时，使用了单连接，还是多连接？

**Comment by hsnxiaoning** [comment]
> 批量插入时，使用了单连接，还是多连接？

单连接，非并发

**Comment by genelet** [comment]
GOLANG：
单链接测试 db.Exec，偶尔出现如下系统报错：
TDengine/src/client/src/tscParseInsert.c:1313: tscProcessMultiVnodesInsert: Assertion `pCmd->isInsertFromFile != -1 && pMeterMetaInfo->vnodeIndex >= 1 && pCmd->pDataBlocks != NULL' failed.
SIGABRT: abort

**Comment by sangshuduo** [comment]
请使用新的正式发布版验证一下
