### ISSUE TITLE
How tdengine know the field type from telegraf

### ISSUE THREAD

**Issue by tonycheng518** [taosdata/TDengine#2635]
I tested using telegraf to collect metrics of my host machine and send them to tdengine，configs in /etc/telegraf/telegraf.conf is like this:
###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################
# Read metrics about cpu usage
[[inputs.cpu]]
  ## Whether to report per-cpu stats or not
  percpu = true
  ## Whether to report total system cpu stats or not
  totalcpu = true
  ## If true, collect raw CPU time metrics.
  collect_cpu_time = false
  ## If true, compute and report the sum of all non-idle CPU states.
  report_active = false
# Read metrics about disk usage by mount point
[[inputs.disk]]
# Read metrics about disk IO by device
[[inputs.diskio]]
# Get kernel statistics from /proc/stat
[[inputs.kernel]]
# Read metrics about memory usage
[[inputs.mem]]
# Get the number of processes and group them by status
[[inputs.processes]]
# Read metrics about system load & uptime
[[inputs.system]]

[[outputs.http]]
#   ## URL is the address to send metrics to
    url = "http://127.0.0.1:6020/telegraf/udb"

#   ## HTTP method, one of: "POST" or "PUT"
    method = "POST"
#
#   ## HTTP Basic Auth credentials
    username = "root"
    password = "taosdata"

#   ## Data format to output.
#   ## Each data format has it's own unique set of configuration options, read
    data_format = "json"
    json_timestamp_units = "1ms"

after boot telegraf and tdengine taosd, i use taos to connect taosd and see the supertable that telegraf created. I wonder that how tdengine know the type of fields, I guess telegraf maybe use standard sql to create table then tdengine know the fields type,  or the data_format = "json" and telegraf use something like { "field1_type": "int", "field2_type":"double"} to tell tdengine.
Why i ask this is that i want to use kafka as the input of telegraf, and i don't know how i send data to kafka. my telegraf kafka config is like this:
# # Read metrics from Kafka topics
[[inputs.kafka_consumer]]
#   ## Kafka brokers.
   brokers = ["localhost:9092"]

#
#   ## Topics to consume.
   topics = ["telegraf"]

#
#   ## Name of the consumer group.
    consumer_group = "telegraf_metrics_consumers"
#
#   ## Initial offset position; one of "oldest" or "newest".
  offset = "oldest"
# Data format to consume
data_format = "json"

**Comment by Aries-Lee1991** [comment]
we'll check it.

**Comment by tonycheng518** [comment]
from this url: http://167.114.231.105/telegraf/v1.7/concepts/data_formats_input/#json-data-format
I know that only numerical values are converted to fields, and they are converted into a float. strings are ignored unless specified as a tag_key. With the configuration in last post, after booted, telegraf itself creates the topic "telegraf" in kafka, I use kafka-console-producer.sh to produce a message in json format:
{ "temperature":26.0, "humidity":75.0, "air_pressure":1000, "pm25":80.0, "pm10":70.0 }
After sending this message, i find udb database created:
taos> show databases;
              name              |     created time     |  ntables  |  vgroups  |replica| days  |  keep1,keep2,keep(D)   |  tables   |   rows    | cache(b)  |      ablocks       |tblocks| ctime(s)  | clog | comp |time precision|  status  |
==============================================================================================================================================================================================================================================
udb                             | 20-07-14 15:07:30.427|          1|          1|      1|     10|3650,3650,3650          |       1000|       4096|      16384|             4.00000|     50|       3600|     1|     2|ms            |ready     |
log                             | 20-06-30 18:11:34.264|          5|          1|      1|     10|30,30,30                |         32|       1024|       2048|             2.00000|     32|       3600|     1|     2|us            |ready     |
Query OK, 2 row(s) in set (0.063066s)
taos> use udb;
Database changed.

taos> show stables;
                              name                              |     created_time     |columns| tags  |  tables   |
====================================================================================================================
kafka_consumer                                                  | 20-07-14 15:07:30.449|      6|      1|          1|
Query OK, 1 row(s) in set (0.016740s)

taos> show tables;
                           table_name                           |     created_time     |columns|                             stable                             |
=================================================================================================================================================================
kafka_consumer_zqs_virtual_machine_worker_node1                 | 20-07-14 15:07:30.520|      6|kafka_consumer                                                  |
Query OK, 1 row(s) in set (1.656348s)

taos> describe kafka_consumer_zqs_virtual_machine_worker_node1;
                             Field                              |      Type      |  Length   |              Note              |
===============================================================================================================================
ts                                                              |TIMESTAMP       |          8|                                |
f_air_pressure                                                  |DOUBLE          |          8|                                |
f_humidity                                                      |DOUBLE          |          8|                                |
f_pm10                                                          |DOUBLE          |          8|                                |
f_pm25                                                          |DOUBLE          |          8|                                |
f_temperature                                                   |DOUBLE          |          8|                                |
t_host                                                          |BINARY          |         32|zqs-virtual-machine-worker-node1|
Query OK, 7 row(s) in set (0.007117s)

taos> select count(*) from kafka_consumer_zqs_virtual_machine_worker_node1;
      count(*)       |
======================
                    1|
Query OK, 1 row(s) in set (0.063379s)

taos> select * from kafka_consumer_zqs_virtual_machine_worker_node1;
          ts          |     f_air_pressure      |       f_humidity        |         f_pm10          |         f_pm25          |      f_temperature      |
=========================================================================================================================================================
 20-07-14 15:07:24.106|           1000.000000000|             75.000000000|             70.000000000|             80.000000000|             26.000000000|
Query OK, 1 row(s) in set (0.035641s)
now, we confirm that it's true.
something bother me: the f_  field prefix and t_host field is added by tdengine?
