### ISSUE TITLE
启动taosd问题

### ISSUE THREAD

**Issue by handsomeSong** [taosdata/TDengine#26382]
systemctl start taosd 启动后  会出现两个tcp端口 6035 和 6040  而且没有6030端口  导致无法连接终端

**Comment by yu285** [comment]
应该是启动还没有完成，没有激活 6030 。 所以需要具体日志分析。

但您没有提供版本信息，日志信息等。所以暂作关闭处理，可以微信联系a15652223354做具体沟通
