### ISSUE TITLE
drop and create table then it cause server crash

### ISSUE THREAD

**Issue by robotspace** [taosdata/TDengine#264]
**### server log:**
08/02 15:10:55.710465 7f62e74ddb80 UTL timezone not configured, set to system default: (CST, +0800)
08/02 15:10:55.710548 7f62e74ddb80 UTL locale not configured, set to system default:en_US.UTF-8
08/02 15:10:55.710584 7f62e74ddb80 UTL charset not configured, set to system default:UTF-8
08/02 15:10:55.710737 7f62e74ddb80 UTL    taos config & system info:
08/02 15:10:55.710745 7f62e74ddb80 UTL ==================================
08/02 15:10:55.710752 7f62e74ddb80 UTL  internalIp:             10.136.198.240 
08/02 15:10:55.710759 7f62e74ddb80 UTL  serverIp:               0.0.0.0 
08/02 15:10:55.710767 7f62e74ddb80 UTL  localIp:                0.0.0.0 
08/02 15:10:55.710783 7f62e74ddb80 UTL  httpIp:                 0.0.0.0 
08/02 15:10:55.710797 7f62e74ddb80 UTL  httpPort:               6020 
08/02 15:10:55.710813 7f62e74ddb80 UTL  mgmtShellPort:          6030 
08/02 15:10:55.710827 7f62e74ddb80 UTL  vnodeShellPort:         6035 
08/02 15:10:55.710843 7f62e74ddb80 UTL  configDir:              ../cfg 
08/02 15:10:55.710852 7f62e74ddb80 UTL  dataDir:                /var/lib/taos 
08/02 15:10:55.710858 7f62e74ddb80 UTL  logDir:                 /var/log/taos 
08/02 15:10:55.710868 7f62e74ddb80 UTL  scriptDir:              /etc/taos 
08/02 15:10:55.710873 7f62e74ddb80 UTL  numOfThreadsPerCore:    1.000000 
08/02 15:10:55.710883 7f62e74ddb80 UTL  ratioOfQueryThreads:    0.500000 
08/02 15:10:55.710892 7f62e74ddb80 UTL  numOfVnodesPerCore:     8 
08/02 15:10:55.710897 7f62e74ddb80 UTL  numOfTotalVnodes:       0 
08/02 15:10:55.710904 7f62e74ddb80 UTL  tables:                 1000 
08/02 15:10:55.710910 7f62e74ddb80 UTL  cache:                  16384(byte)
08/02 15:10:55.710917 7f62e74ddb80 UTL  rows:                   4096 
08/02 15:10:55.710922 7f62e74ddb80 UTL  fileBlockMinPercent:    0.050000 
08/02 15:10:55.710930 7f62e74ddb80 UTL  ablocks:                4 
08/02 15:10:55.710938 7f62e74ddb80 UTL  tblocks:                100 
08/02 15:10:55.710947 7f62e74ddb80 UTL  monitorInterval:        30(s)
08/02 15:10:55.710957 7f62e74ddb80 UTL  rpcTimer:               300(ms)
08/02 15:10:55.710965 7f62e74ddb80 UTL  rpcMaxTime:             600(s)
08/02 15:10:55.710970 7f62e74ddb80 UTL  ctime:                  3600(s)
08/02 15:10:55.710974 7f62e74ddb80 UTL  statusInterval:         1(s)
08/02 15:10:55.710978 7f62e74ddb80 UTL  shellActivityTimer:     3(s)
08/02 15:10:55.710985 7f62e74ddb80 UTL  meterMetaKeepTimer:     7200(s)
08/02 15:10:55.710992 7f62e74ddb80 UTL  metricMetaKeepTimer:    600(s)
08/02 15:10:55.711000 7f62e74ddb80 UTL  maxUsers:               1000 
08/02 15:10:55.711005 7f62e74ddb80 UTL  maxDbs:                 1000 
08/02 15:10:55.711010 7f62e74ddb80 UTL  maxTables:              650000 
08/02 15:10:55.711016 7f62e74ddb80 UTL  maxVGroups:             1000 
08/02 15:10:55.711021 7f62e74ddb80 UTL  minSlidingTime:         10(ms)
08/02 15:10:55.711027 7f62e74ddb80 UTL  minIntervalTime:        10(ms)
08/02 15:10:55.711031 7f62e74ddb80 UTL  maxStreamCompDelay:     20000(ms)
08/02 15:10:55.711037 7f62e74ddb80 UTL  maxFirstStreamCompDelay:10000(ms)
08/02 15:10:55.711042 7f62e74ddb80 UTL  retryStreamCompDelay:   10(ms)
08/02 15:10:55.711045 7f62e74ddb80 UTL  clog:                   1 
08/02 15:10:55.711048 7f62e74ddb80 UTL  comp:                   2 
08/02 15:10:55.711056 7f62e74ddb80 UTL  days:                   10 
08/02 15:10:55.711061 7f62e74ddb80 UTL  keep:                   3650 
08/02 15:10:55.711068 7f62e74ddb80 UTL  defaultDB:               
08/02 15:10:55.711077 7f62e74ddb80 UTL  defaultUser:            root 
08/02 15:10:55.711083 7f62e74ddb80 UTL  defaultPass:            taosdata 
08/02 15:10:55.711089 7f62e74ddb80 UTL  timezone:                (CST, +0800) 
08/02 15:10:55.711097 7f62e74ddb80 UTL  locale:                 en_US.UTF-8 
08/02 15:10:55.711105 7f62e74ddb80 UTL  charset:                UTF-8 
08/02 15:10:55.711110 7f62e74ddb80 UTL  maxShellConns:          2000 
08/02 15:10:55.711115 7f62e74ddb80 UTL  maxMeterConnections:    10000 
08/02 15:10:55.711121 7f62e74ddb80 UTL  maxMgmtConnections:     2000 
08/02 15:10:55.711126 7f62e74ddb80 UTL  maxVnodeConnections:    10000 
08/02 15:10:55.711132 7f62e74ddb80 UTL  enableHttp:             1 
08/02 15:10:55.711137 7f62e74ddb80 UTL  enableMonitor:          1 
08/02 15:10:55.711140 7f62e74ddb80 UTL  httpCacheSessions:      2000 
08/02 15:10:55.711145 7f62e74ddb80 UTL  httpMaxThreads:         2 
08/02 15:10:55.711150 7f62e74ddb80 UTL  numOfLogLines:          10000000 
08/02 15:10:55.711158 7f62e74ddb80 UTL  asyncLog:               1 
08/02 15:10:55.711164 7f62e74ddb80 UTL  debugFlag:              131 
08/02 15:10:55.711169 7f62e74ddb80 UTL  mDebugFlag:             135 
08/02 15:10:55.711178 7f62e74ddb80 UTL  dDebugFlag:             131 
08/02 15:10:55.711184 7f62e74ddb80 UTL  sdbDebugFlag:           135 
08/02 15:10:55.711191 7f62e74ddb80 UTL  taosDebugFlag:          131 
08/02 15:10:55.711198 7f62e74ddb80 UTL  tmrDebugFlag:           131 
08/02 15:10:55.711205 7f62e74ddb80 UTL  cDebugFlag:             131 
08/02 15:10:55.711212 7f62e74ddb80 UTL  jniDebugFlag:           131 
08/02 15:10:55.711219 7f62e74ddb80 UTL  odbcDebugFlag:          131 
08/02 15:10:55.711224 7f62e74ddb80 UTL  uDebugFlag:             131 
08/02 15:10:55.711231 7f62e74ddb80 UTL  httpDebugFlag:          131 
08/02 15:10:55.711238 7f62e74ddb80 UTL  monitorDebugFlag:       131 
08/02 15:10:55.711245 7f62e74ddb80 UTL  qDebugFlag:             131 
08/02 15:10:55.711252 7f62e74ddb80 UTL  gitinfo:                ddcb2519e895c2e2101089aedaf529cee5cefe04 
08/02 15:10:55.711258 7f62e74ddb80 UTL  buildinfo:              Built by plum at 2019-07-29 10:41 
08/02 15:10:55.711264 7f62e74ddb80 UTL  version:                1.6.1.2 
08/02 15:10:55.711269 7f62e74ddb80 UTL  dataDir:                /var/lib/taos
08/02 15:10:55.711278 7f62e74ddb80 UTL  os pageSize:            4096(KB)
08/02 15:10:55.711287 7f62e74ddb80 UTL  os openMax:             1024
08/02 15:10:55.711296 7f62e74ddb80 UTL  os streamMax:           16
08/02 15:10:55.711304 7f62e74ddb80 UTL  os numOfCores:          4
08/02 15:10:55.711313 7f62e74ddb80 UTL  os totalDisk:           48(GB)
08/02 15:10:55.711320 7f62e74ddb80 UTL  os totalMemory:         7737(MB)
08/02 15:10:55.711331 7f62e74ddb80 UTL  os sysname:             Linux
08/02 15:10:55.711338 7f62e74ddb80 UTL  os nodename:            localhost.localdomain
08/02 15:10:55.711345 7f62e74ddb80 UTL  os release:             4.19.6-300.fc29.x86_64
08/02 15:10:55.711352 7f62e74ddb80 UTL  os version:             #1 SMP Sun Dec 2 17:33:14 UTC 2018
08/02 15:10:55.711359 7f62e74ddb80 UTL  os machine:             x86_64
08/02 15:10:55.711366 7f62e74ddb80 UTL ==================================
08/02 15:10:55.711373 7f62e74ddb80 DND Server IP address is:10.136.198.240
08/02 15:10:55.711381 7f62e74ddb80 DND starting to initialize TDengine engine ...
08/02 15:10:55.719068 7f62e74ddb80 ERROR DND vid, invalid commit head, sid:-1397227520 contLen:3162488 action:1
08/02 15:10:55.719098 7f62e74ddb80 ERROR DND vid, invalid commit head, sid:16461 contLen:0 action:0
08/02 15:10:55.719121 7f62e74ddb80 ERROR DND vid, invalid commit head, sid:-872415232 contLen:54015 action:0
08/02 15:10:55.719130 7f62e74ddb80 ERROR DND vid, invalid commit head, sid:16777216 contLen:-567456912 action:0
08/02 15:10:55.719139 7f62e74ddb80 ERROR DND vid, invalid commit head, sid:1082726359 contLen:4 action:28
08/02 15:10:55.719147 7f62e74ddb80 ERROR DND vid, invalid commit head, sid:7737 contLen:1098427576 action:0
08/02 15:10:55.719155 7f62e74ddb80 ERROR DND vid, invalid commit head, sid:1078808577 contLen:0 action:48
08/02 15:10:55.721328 7f62e74ddb80 DND vnode is initialized successfully
08/02 15:10:55.721360 7f62e74ddb80 MND starting to initialize TDengine mgmt ...
08/02 15:10:55.722115 7f62e74ddb80 MND first access, set total vnodes:50
08/02 15:10:55.785588 7f62e74ddb80 MND TDengine mgmt is initialized successfully
08/02 15:10:55.785601 7f62e74ddb80 HTP starting to initialize http service ...
08/02 15:10:55.785940 7f62e74ddb80 DND TDengine is initialized successfully
08/02 15:10:55.786006 7f62c0d19700 HTP http service init success at ip:0.0.0.0:6020
08/02 15:10:55.922183 7f62d3fff700 MON starting to initialize monitor service ..
08/02 15:10:55.922430 7f62c56c1700 MND user:monitor login from 127.0.0.1, code:0
08/02 15:10:55.922964 7f62d9c46700 MON dnode:10.136.198.240 is started
08/02 15:10:55.923546 7f62d9c46700 MON monitor service init success
08/02 15:10:56.327178 7f62d3fff700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 15:10:57.527188 7f62d3fff700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 15:10:58.727199 7f62d3fff700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 15:10:59.927207 7f62d3fff700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 15:11:01.127209 7f62d3fff700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 15:11:01.520372 7f62c56c1700 MND user:root login from 127.0.0.1, code:0
08/02 15:11:01.520656 7f62c46bf700 MND db:0.demo all vnodes drop finished
08/02 15:11:01.520708 7f62c46bf700 MND db:0.demo all meters drop finished
08/02 15:11:01.520734 7f62c46bf700 MND db:0.demo database drop finished
Segmentation fault (core dumped)

**### client log**
./demo 127.0.0.1
success to connect to server
failed to create database, reason:failed to connect to server

In fact  I was testing my lua connector. While I followed demo instructions in C demo I got some error, then tried to restore db by C demo. Finally db is out of control.

**Comment by hzcheng** [comment]
Please pull new github code to test again. There is a bug when dropping table. It will be fixed soon. Thanks for reporting.

**Comment by robotspace** [comment]
thanks for your concern. @hzcheng

**Comment by guanshengliang** [comment]
we have already fixed, please pull the code and try again

**Comment by robotspace** [comment]
Sorry, there is still something wrong.

**### server log**

./taosd -c ../cfg
08/02 23:12:53.018836 7ff52eef6b80 UTL timezone not configured, set to system default: (CST, +0800)
08/02 23:12:53.018919 7ff52eef6b80 UTL locale not configured, set to system default:en_US.UTF-8
08/02 23:12:53.018939 7ff52eef6b80 UTL charset not configured, set to system default:UTF-8
08/02 23:12:53.019106 7ff52eef6b80 UTL    taos config & system info:
08/02 23:12:53.019116 7ff52eef6b80 UTL ==================================
08/02 23:12:53.019120 7ff52eef6b80 UTL  internalIp:             192.168.50.215 
08/02 23:12:53.019124 7ff52eef6b80 UTL  serverIp:               0.0.0.0 
08/02 23:12:53.019128 7ff52eef6b80 UTL  localIp:                0.0.0.0 
08/02 23:12:53.019131 7ff52eef6b80 UTL  httpIp:                 0.0.0.0 
08/02 23:12:53.019135 7ff52eef6b80 UTL  httpPort:               6020 
08/02 23:12:53.019139 7ff52eef6b80 UTL  mgmtShellPort:          6030 
08/02 23:12:53.019142 7ff52eef6b80 UTL  vnodeShellPort:         6035 
08/02 23:12:53.019149 7ff52eef6b80 UTL  configDir:              ../cfg 
08/02 23:12:53.019156 7ff52eef6b80 UTL  dataDir:                /var/lib/taos 
08/02 23:12:53.019162 7ff52eef6b80 UTL  logDir:                 /var/log/taos 
08/02 23:12:53.019171 7ff52eef6b80 UTL  scriptDir:              /etc/taos 
08/02 23:12:53.019184 7ff52eef6b80 UTL  numOfThreadsPerCore:    1.000000 
08/02 23:12:53.019196 7ff52eef6b80 UTL  ratioOfQueryThreads:    0.500000 
08/02 23:12:53.019205 7ff52eef6b80 UTL  numOfVnodesPerCore:     8 
08/02 23:12:53.019212 7ff52eef6b80 UTL  numOfTotalVnodes:       0 
08/02 23:12:53.019217 7ff52eef6b80 UTL  tables:                 1000 
08/02 23:12:53.019224 7ff52eef6b80 UTL  cache:                  16384(byte)
08/02 23:12:53.019228 7ff52eef6b80 UTL  rows:                   4096 
08/02 23:12:53.019235 7ff52eef6b80 UTL  fileBlockMinPercent:    0.050000 
08/02 23:12:53.019241 7ff52eef6b80 UTL  ablocks:                4 
08/02 23:12:53.019247 7ff52eef6b80 UTL  tblocks:                100 
08/02 23:12:53.019256 7ff52eef6b80 UTL  monitorInterval:        30(s)
08/02 23:12:53.019261 7ff52eef6b80 UTL  rpcTimer:               300(ms)
08/02 23:12:53.019267 7ff52eef6b80 UTL  rpcMaxTime:             600(s)
08/02 23:12:53.019271 7ff52eef6b80 UTL  ctime:                  3600(s)
08/02 23:12:53.019279 7ff52eef6b80 UTL  statusInterval:         1(s)
08/02 23:12:53.019283 7ff52eef6b80 UTL  shellActivityTimer:     3(s)
08/02 23:12:53.019288 7ff52eef6b80 UTL  meterMetaKeepTimer:     7200(s)
08/02 23:12:53.019294 7ff52eef6b80 UTL  metricMetaKeepTimer:    600(s)
08/02 23:12:53.019298 7ff52eef6b80 UTL  maxUsers:               1000 
08/02 23:12:53.019302 7ff52eef6b80 UTL  maxDbs:                 1000 
08/02 23:12:53.019309 7ff52eef6b80 UTL  maxTables:              650000 
08/02 23:12:53.019313 7ff52eef6b80 UTL  maxVGroups:             1000 
08/02 23:12:53.019318 7ff52eef6b80 UTL  minSlidingTime:         10(ms)
08/02 23:12:53.019324 7ff52eef6b80 UTL  minIntervalTime:        10(ms)
08/02 23:12:53.019328 7ff52eef6b80 UTL  maxStreamCompDelay:     20000(ms)
08/02 23:12:53.019335 7ff52eef6b80 UTL  maxFirstStreamCompDelay:10000(ms)
08/02 23:12:53.019339 7ff52eef6b80 UTL  retryStreamCompDelay:   10(ms)
08/02 23:12:53.019345 7ff52eef6b80 UTL  clog:                   1 
08/02 23:12:53.019349 7ff52eef6b80 UTL  comp:                   2 
08/02 23:12:53.019353 7ff52eef6b80 UTL  days:                   10 
08/02 23:12:53.019359 7ff52eef6b80 UTL  keep:                   3650 
08/02 23:12:53.019363 7ff52eef6b80 UTL  defaultDB:               
08/02 23:12:53.019370 7ff52eef6b80 UTL  defaultUser:            root 
08/02 23:12:53.019375 7ff52eef6b80 UTL  defaultPass:            taosdata 
08/02 23:12:53.019381 7ff52eef6b80 UTL  timezone:                (CST, +0800) 
08/02 23:12:53.019385 7ff52eef6b80 UTL  locale:                 en_US.UTF-8 
08/02 23:12:53.019390 7ff52eef6b80 UTL  charset:                UTF-8 
08/02 23:12:53.019396 7ff52eef6b80 UTL  maxShellConns:          2000 
08/02 23:12:53.019400 7ff52eef6b80 UTL  maxMeterConnections:    10000 
08/02 23:12:53.019405 7ff52eef6b80 UTL  maxMgmtConnections:     2000 
08/02 23:12:53.019409 7ff52eef6b80 UTL  maxVnodeConnections:    10000 
08/02 23:12:53.019413 7ff52eef6b80 UTL  enableHttp:             1 
08/02 23:12:53.019417 7ff52eef6b80 UTL  enableMonitor:          1 
08/02 23:12:53.019421 7ff52eef6b80 UTL  httpCacheSessions:      30 
08/02 23:12:53.019427 7ff52eef6b80 UTL  httpMaxThreads:         2 
08/02 23:12:53.019432 7ff52eef6b80 UTL  numOfLogLines:          10000000 
08/02 23:12:53.019437 7ff52eef6b80 UTL  asyncLog:               1 
08/02 23:12:53.019442 7ff52eef6b80 UTL  debugFlag:              131 
08/02 23:12:53.019446 7ff52eef6b80 UTL  mDebugFlag:             135 
08/02 23:12:53.019451 7ff52eef6b80 UTL  dDebugFlag:             131 
08/02 23:12:53.019457 7ff52eef6b80 UTL  sdbDebugFlag:           135 
08/02 23:12:53.019461 7ff52eef6b80 UTL  taosDebugFlag:          131 
08/02 23:12:53.019466 7ff52eef6b80 UTL  tmrDebugFlag:           131 
08/02 23:12:53.019471 7ff52eef6b80 UTL  cDebugFlag:             131 
08/02 23:12:53.019476 7ff52eef6b80 UTL  jniDebugFlag:           131 
08/02 23:12:53.019480 7ff52eef6b80 UTL  odbcDebugFlag:          131 
08/02 23:12:53.019486 7ff52eef6b80 UTL  uDebugFlag:             131 
08/02 23:12:53.019490 7ff52eef6b80 UTL  httpDebugFlag:          131 
08/02 23:12:53.019508 7ff52eef6b80 UTL  monitorDebugFlag:       131 
08/02 23:12:53.019513 7ff52eef6b80 UTL  qDebugFlag:             131 
08/02 23:12:53.019517 7ff52eef6b80 UTL  gitinfo:                ddcb2519e895c2e2101089aedaf529cee5cefe04 
08/02 23:12:53.019522 7ff52eef6b80 UTL  buildinfo:              Built by plum at 2019-07-29 10:41 
08/02 23:12:53.019527 7ff52eef6b80 UTL  version:                1.6.1.3 
08/02 23:12:53.019531 7ff52eef6b80 UTL  dataDir:                /var/lib/taos
08/02 23:12:53.019535 7ff52eef6b80 UTL  os pageSize:            4096(KB)
08/02 23:12:53.019541 7ff52eef6b80 UTL  os openMax:             1024
08/02 23:12:53.019545 7ff52eef6b80 UTL  os streamMax:           16
08/02 23:12:53.019549 7ff52eef6b80 UTL  os numOfCores:          4
08/02 23:12:53.019556 7ff52eef6b80 UTL  os totalDisk:           48(GB)
08/02 23:12:53.019560 7ff52eef6b80 UTL  os totalMemory:         7737(MB)
08/02 23:12:53.019577 7ff52eef6b80 UTL  os sysname:             Linux
08/02 23:12:53.019584 7ff52eef6b80 UTL  os nodename:            localhost.localdomain
08/02 23:12:53.019588 7ff52eef6b80 UTL  os release:             4.19.6-300.fc29.x86_64
08/02 23:12:53.019594 7ff52eef6b80 UTL  os version:             #1 SMP Sun Dec 2 17:33:14 UTC 2018
08/02 23:12:53.019598 7ff52eef6b80 UTL  os machine:             x86_64
08/02 23:12:53.019602 7ff52eef6b80 UTL ==================================
08/02 23:12:53.019608 7ff52eef6b80 DND Server IP address is:192.168.50.215
08/02 23:12:53.019614 7ff52eef6b80 DND starting to initialize TDengine engine ...
08/02 23:12:53.033449 7ff52eef6b80 DND vnode is initialized successfully
08/02 23:12:53.033475 7ff52eef6b80 MND starting to initialize TDengine mgmt ...
08/02 23:12:53.034197 7ff52eef6b80 MND first access, set total vnodes:50
08/02 23:12:53.048805 7ff52eef6b80 MND TDengine mgmt is initialized successfully
08/02 23:12:53.048818 7ff52eef6b80 HTP starting to initialize http service ...
08/02 23:12:53.048925 7ff52eef6b80 DND TDengine is initialized successfully
08/02 23:12:53.048965 7ff4f58ce700 HTP http service init success at ip:0.0.0.0:6020
08/02 23:12:53.225590 7ff51fdd9700 MON starting to initialize monitor service ..
08/02 23:12:53.226358 7ff50cbbb700 MND user:monitor login from 127.0.0.1, code:0
08/02 23:12:53.227923 7ff52165f700 MON dnode:192.168.50.215 is started
08/02 23:12:53.230315 7ff52165f700 MON monitor service init success
08/02 23:12:53.635634 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:12:54.835604 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:12:56.035671 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:12:57.235621 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:12:58.435679 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:12:59.635662 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:00.835681 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:02.035645 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:03.235650 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:04.435652 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:05.635647 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:06.835621 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:08.035584 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:09.235639 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:10.435646 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:11.635631 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:12.835651 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:14.035631 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:14.463681 7ff50cbbb700 MND user:root login from 127.0.0.1, code:0
08/02 23:13:14.464447 7ff50bbb9700 MND DB:0.demo is dropped by root
08/02 23:13:14.466464 7ff50bbb9700 MND DB:0.demo is created by root
08/02 23:13:14.467655 7ff517fff700 ERROR DND failed to create vnode:1 file:/var/lib/taos/tsdb/vnode1/meterObj.v1
08/02 23:13:14.467755 7ff50c3ba700 ERROR MND db:0.demo vgroup create failed, code:74
08/02 23:13:15.235650 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:16.435651 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:17.635651 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:18.835644 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:20.035645 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:21.235648 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:22.435637 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:23.635640 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:24.835673 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:26.035649 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:27.235630 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:28.435646 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:29.635647 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:30.835648 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:32.035647 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:33.235628 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:34.435652 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:35.635656 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:36.835670 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:38.035677 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:39.235674 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:40.435645 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:41.635678 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:42.835657 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:44.035657 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:45.235684 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:46.435631 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:47.635631 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:48.835649 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:50.035678 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:51.235621 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:52.435667 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:53.635668 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:54.835671 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:56.035670 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:57.235611 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:58.435671 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:13:59.635621 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:14:00.835671 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:14:02.035673 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:14:03.235672 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:14:04.435674 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:14:05.635675 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:14:06.835672 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:14:08.035642 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:14:09.235650 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:14:10.435648 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:14:11.635673 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:14:12.835672 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
08/02 23:14:14.035670 7ff51fdd9700 ERROR MND vgroup:3 is not there, but associated with vnode 2
^C08/02 23:14:14.172237 7ff52eef6b80 DND shut down signal is 2, sender PID:0
08/02 23:14:14.172303 7ff52eef6b80 HTP http service cleanup
08/02 23:14:14.172798 7ff52eef6b80 MON dnode:192.168.50.215 is stopped
08/02 23:14:14.172839 7ff52eef6b80 MON monitor service cleanup
08/02 23:14:14.172854 7ff52eef6b80 MON dnode:192.168.50.215 is stopped
08/02 23:14:14.189129 7ff50bbb9700 DND vid:0, committing to file, firstKey:1564758773031720 lastKey:1564758854172325 ssid:0 esid:32
08/02 23:14:14.190047 7ff50bbb9700 ERROR DND failed to create head data file, vnode: 0, fileId: 1811
08/02 23:14:14.190101 7ff50bbb9700 DND vid:0, committing is over
08/02 23:14:14.199215 7ff52eef6b80 ERROR DND vid:0, failed to remove:/var/lib/taos/tsdb/vnode0/db/submit0.log
08/02 23:14:14.199413 7ff50bbb9700 DND vid:2, committing to file, firstKey:1564758773032 lastKey:1592222222223 ssid:0 esid:1000
08/02 23:14:14.200762 7ff50bbb9700 ERROR DND vid:2, failed to open new head file:/var/lib/taos/tsdb/vnode2/db/v2f1811.t, reason:Permission denied
08/02 23:14:14.200816 7ff50bbb9700 DND vid:2, committing is over
08/02 23:14:14.209515 7ff52eef6b80 ERROR DND vid:2, failed to remove:/var/lib/taos/tsdb/vnode2/db/submit2.log
08/02 23:14:14.209802 7ff52eef6b80 DND TDengine is shut down!


**### client log**

lua test.lua 
success to connect to server
receive command:drop database demo
receive command:create database demo
receive command:use demo
receive command:create table m1 (ts timestamp, speed int)
failed, reason:vgroup init failed
vgroup init failed

**Comment by robotspace** [comment]
I delete all data and reinstall packages to run lua connector. Anyway server doesn't crash any more. Issue is closed for the moment.
