### ISSUE TITLE
RESTAPI偶现"http head parse error"

### ISSUE THREAD

**Issue by zhuangQingGuang** [taosdata/TDengine#2646]
{"status":"error","code":1005,"desc":"http head parse error"}

版本：1.6.6.0

**Comment by Aries-Lee1991** [comment]
收到，我们看一下。

**Comment by guanshengliang** [comment]
This debugging information is not enough, there is no way to locate the error
However, the upcoming 2.0 version optimizes this issue, please wait a few more days

**Comment by zhuangQingGuang** [comment]
> This debugging information is not enough, there is no way to locate the error
> However, the upcoming 2.0 version optimizes this issue, please wait a few more days

OK thank you
