### ISSUE TITLE
在集群已经创建，并且修改了root密码和新增了其他用户后，如何新增节点并加入这个集群？

### ISSUE THREAD

**Issue by JackHuang90** [taosdata/TDengine#26488]
**General Questions**
在查看过用户手册和搜索后，没有找到在集群已经创建，并且修改了root密码和新增了其他用户后，进行新增节点并加入这个集群的相关说明和操作。
想咨询一下，如果是这种情况，如何加入现有集群呢？因为直接配置firstEp secondEp 会直接报错 Authentication failure，而无法启动Tdengine。

版本：tdengine:3.3.2.0
环境：Docker

**Comment by yu285** [comment]
不会影响的，有执行create dnode 吗？ 要不你加微信a15652223354 具体沟通下

**Comment by JackHuang90** [comment]
> 不会影响的，有执行create dnode 吗？ 要不你加微信a15652223354 具体沟通下

好的，谢谢，我加你。我是先写好firstEp secondEp的配置文件，然后启动的时候启动不了。
