### ISSUE TITLE
STDDEV 函数计算结果随机出现结果为0

### ISSUE THREAD

**Issue by chenkline** [taosdata/TDengine#26484]
**Bug Description**
STDDEV 函数计算结果随机出现结果为0 

**To Reproduce**
数据库&表结构:
CREATE DATABASE IF NOT EXISTS ue_ping KEEP 365 DURATION 3d BUFFER 96 VGROUPS 12 WAL_LEVEL 1;
CREATE STABLE IF NOT EXISTS ue_ping.s_ue_ping (ts timestamp, delay bigint) TAGS (imsi binary(36)); 
子表预创建，以001010000000084为例，子表建表语句：
CREATE TABLE IF NOT EXISTS ue_ping.t_ue_ping_001010000000084 USING ue_ping.s_ue_ping TAGS ("001010000000084");

SQL 查询语句:
 SELECT
 MAX(CASE WHEN delay != 0 THEN delay ELSE NULL END) AS maxDelay,
 MIN(CASE WHEN delay != 0 THEN delay ELSE NULL END) AS minDelay,
 AVG(CASE WHEN delay != 0 THEN delay ELSE NULL END) AS avgDelay,
 STDDEV(CASE WHEN delay != 0 THEN delay ELSE NULL END) AS jitter,
 COUNT(CASE WHEN delay = 0 THEN 1 ELSE NULL END) AS timeoutCount,
 COUNT(*) AS totalCount
 FROM ue_ping.s_ue_ping
 WHERE ts between '2024-07-08 11:0:35' and '2024-07-09 11:0:35';

**Expected Behavior**
查询结果的jitter值每次查询都相同

**Screenshots**
<img width="943" alt="3320" src="https://github.com/taosdata/TDengine/assets/5063693/1aa607d7-69ba-45e9-80f1-04ce7c9a8649">

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - 16C32GB, 剩余磁盘空间709GB
 - TDengine Version 3.3.0.0 / 3.3.2.0

**Additional Context**
 - 容器化单节点部署环境说明, Docker version 20.10.13, Docker Compose version v2.3.3
 - Docker Compose 配置文件
version: "3.7"
name: ailink-aiums
services:
    ailink-tdengine:
        image: tdengine/tdengine:3.3.2.0
        build:
            #容器构建相对路径/绝对路径
            context: /opt/OMC/aiums/dockfile
            #指定构建的Dockerfile
            dockerfile: Dockerfile_tdengine
        network_mode: "host"
        environment:
            AIUMS_TAOS_USER_NAME: root
            AIUMS_TAOS_PASSWORD: AIUMSDB@123456
        volumes:
            - /opt/OMC/var/lib/taos:/var/lib/taos
            - /opt/OMC/var/log/taos:/var/log/taos
            - /opt/OMC/aiums/tdengine/initdb:/var/initdb
            - /opt/OMC/aiums/tdengine/config/taos.cfg:/etc/taos/taos.cfg
        container_name: ailink-tdengine
        restart: always

/opt/OMC/aiums/tdengine/config/taos.cfg 配置内容：

fqdn                      buildkitsandbox
supportVnodes             80
monitor 1
monitorFQDN buildkitsandbox
audit 1
timezone Hongkong

**Comment by yu285** [comment]
收到我们处理一下

**Comment by yu285** [comment]
下个版本会修复，请到时候升级验证

**Comment by chenkline** [comment]
tag ver-3.3.2.9 验证OK，没有再出现结果为0的情况
