### ISSUE TITLE
Ghost Data

### ISSUE THREAD

**Issue by Zeroive** [taosdata/TDengine#26496]
**Bug Description**
同一个时间点的数据会有两种值，并且查出来的数据没有按照时间戳排序(图中8月30号的数据被插到了8月16号的数据中返回)。

**Screenshots**
![c22e5ef0d391cf1c9daab742104fb26](https://github.com/taosdata/TDengine/assets/48762249/b31c6026-fd69-4de2-aaba-2544d082f2a9)
![b1716b6d1bbc86cc28ddeb476c6844d](https://github.com/taosdata/TDengine/assets/48762249/0cdc4cc9-5d2f-47bb-88ee-4ddf2f56001a)

TDengine Version:3.0.4.1

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，直接安装最新版软件（3.3.2.0）即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
