### ISSUE TITLE
集群环境TDengine ERROR (0x80000020)

### ISSUE THREAD

**Issue by Carson-yy** [taosdata/TDengine#26523]
集群环境一直报TDengine ERROR (0x80000020): some vnode/qnode/mnode(s) out of service

 - 3台4核8G，磁盘余量无限很大
 - TDengine Version 3.2.2.0

集群环境出现错误 TDengine ERROR (0x80000020): some vnode/qnode/mnode(s) out of service 无论是新建集群还是单机切换到集群，这个错误一直在。

通过官方TDEngine Client的C库连接的，没有使用REST的taosAdapter

**Comment by Carson-yy** [comment]
解决了，服务是容器部署的，每个服务需要都能够访问集群的每个TD，不然就出现上面的问题，我们给Pod加了hosts解析，这个问题就没了

**Comment by 1247776995** [comment]
> 解决了，服务是容器部署的，每个服务需要都能够访问集群的每个TD，不然就出现上面的问题，我们给Pod加了hosts解析，这个问题就没了

您好，请问一下具体如何给pods加hosts解析
