### ISSUE TITLE
fatal error: taos.h: No such file or directory

### ISSUE THREAD

**Issue by hell0w0orld** [taosdata/TDengine#26544]
**Bug Description**
项目编译失败
fatal error: taos.h: No such file or directory  #include <taos.h>           ^~~~~~~~ compilation terminated.

**Screenshots**
![image](https://github.com/user-attachments/assets/874518c4-300e-42b1-bf76-8df4662086a9)

**Environment (please complete the following information):**
系统：windows11
go 1.21
github.com/taosdata/driver-go/v3/taosSql v3.5.6
未安装服务端

**Comment by mesquita** [comment]
You have to install the taosc driver.
