### ISSUE TITLE
通过C# taosconnector查询个别点报错，系统直接崩掉

### ISSUE THREAD

**Issue by yuyong4992** [taosdata/TDengine#26557]
**General Questions**
通过C# taosconnector查询个别点报错，系统直接崩掉
用taos进行describe 该表也会报错。
07/13 12:04:44.087575 00114368 UTL FATAL frame:1, cJSON_AddRawToObject - 0x40AFC92D

07/13 12:04:44.093983 00114368 UTL FATAL frame:2, cJSON_AddRawToObject - 0x40AFC92D

07/13 12:04:44.098265 00114368 UTL FATAL frame:3, cJSON_AddRawToObject - 0x40AFC92D

07/13 12:04:44.102509 00114368 UTL FATAL frame:4, cJSON_AddRawToObject - 0x40AFC92D

07/13 12:04:44.106760 00114368 UTL FATAL frame:5, cJSON_AddRawToObject - 0x40AFC92D

07/13 12:04:44.110967 00114368 UTL FATAL frame:6, cJSON_AddRawToObject - 0x40AFC92D

07/13 12:04:44.114169 00114368 UTL FATAL frame:7, cJSON_AddRawToObject - 0x40AFC92D

07/13 12:04:44.118459 00114368 UTL FATAL frame:8, cJSON_AddRawToObject - 0x40AFC92D

07/13 12:04:44.124937 00114368 UTL FATAL frame:9, cJSON_AddRawToObject - 0x40AFC92D

07/13 12:04:44.129233 00114368 UTL FATAL frame:10, cJSON_AddRawToObject - 0x40AFC92D

07/13 12:04:44.133406 00114368 UTL FATAL frame:11, cJSON_AddRawToObject - 0x40AFC92D

07/13 12:04:44.137585 00114368 UTL FATAL frame:12, cJSON_AddRawToObject - 0x40AFC92D

07/13 12:04:44.142839 00114368 UTL FATAL frame:13, BaseThreadInitThunk - 0xA21F7960

07/13 12:04:44.147028 00114368 UTL FATAL frame:14, RtlUserThreadStart - 0xA3A6A250

Assertion failed: 0, file C:\workroom\workspace\3.0_releaseVersion\TDinternal\community\source\util\src\tlog.c, line 777
![d19621b0dbcdc01135180019bf1563a](https://github.com/user-attachments/assets/6b0da203-0dc1-4892-9bcd-00dccc5aa997)

版本 OSS 3.0.7.0

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，直接升级到最新版3.3.2.0即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
