### ISSUE TITLE
limit 加了offset后，数据值都变了，是什么原因

### ISSUE THREAD

**Issue by shixiayu13** [taosdata/TDengine#26561]
如果只是limit 1，数据格式返回正常。
![image](https://github.com/user-attachments/assets/2df57ae3-1cd8-49ae-ad86-bf1d26a2846f)
但是加了 limit 1, 1 数据格式返回就不对了
![image](https://github.com/user-attachments/assets/6b47ac3d-5512-458c-9102-c790ebd148b4)
这个是什么原因导致的

**Comment by yu285** [comment]
信息不完整，请提供一下版本号，和具体sql
