### ISSUE TITLE
从3.2.3.0升级到3.3.2.0，报错

### ISSUE THREAD

**Issue by veigara** [taosdata/TDengine#26571]
5 11:24:42.617158 00000073 warning "create database sql: create database if not exists log buffer 64  cachemodel 'both'  vgroups 1  keep 90 " model=report
Use configuration file path: /etc/taos/explorer.toml
2024-07-15T03:24:52.727966Z  INFO main ThreadId(01) taos_explorer: Starting server at 0.0.0.0:6060
2024-07-15T03:24:52.728386Z  INFO main ThreadId(01) actix_server::builder: starting 2 workers
2024-07-15T03:24:52.728410Z  INFO main ThreadId(01) actix_server::server: Actix runtime found; starting in Actix runtime
07/15 11:24:52.921336 00000036 taos_ADAPTER error "connect server error" sql=create database if not exists log buffer 64  cachemodel 'both'  vgroups 1  keep 90 error=[0xb] Unable to establish connection model=restful req_id=0x10840b46bce00001
07/15 11:24:52.921727 00000036 taos_ADAPTER info "| 200 |  10.30351647s |       127.0.0.1 | POST | %2Frest%2Fsql " req_id=0x10840b46bce00001 model=web
07/15 11:24:52.922159 00000073 error "create database log error [0xb] Unable to establish connection" model=report error=[0xb] Unable to establish connection
panic: [0xb] Unable to establish connection

goroutine 1 [running]:
github.com/taosdata/taoskeeper/api.(*Reporter).createDatabase(0xc0004e5340)
        /data/release/main/taoskeeper/api/report.go:263 +0x316
github.com/taosdata/taoskeeper/api.(*Reporter).Init(0xc000002f00?, {0xe71df8, 0xc000102b60})
        /data/release/main/taoskeeper/api/report.go:62 +0x8e
github.com/taosdata/taoskeeper/system.Init()
        /data/release/main/taoskeeper/system/program.go:39 +0x9b
main.main()
        /data/release/main/taoskeeper/main.go:8 +0x19
07/15 11:25:00.006168 00000036 taos_ADAPTER error "write to server error" model=monitor error=Post "http://127.0.0.1:6043/adapter_report": dial tcp 127.0.0.1:6043: connect: connection refused
07/15 11:25:15.004272 00000036 taos_ADAPTER error "write to server error" model=monitor error=Post "http://127.0.0.1:6043/adapter_report": dial tcp 127.0.0.1:6043: connect: connection refused
07/15 11:25:30.008087 00000036 taos_ADAPTER error "write to server error" model=monitor error=Post "http://127.0.0.1:6043/adapter_report": dial tcp 127.0.0.1:6043: connect: connection refused
07/15 11:25:45.006869 00000036 taos_ADAPTER error "write to server error" model=monitor error=Post "http://127.0.0.1:6043/adapter_report": dial tcp 127.0.0.1:6043: connect: connection refused
07/15 11:26:00.006631 00000036 taos_ADAPTER error "write to server error" model=monitor error=Post "http://127.0.0.1:6043/adapter_report": dial tcp 127.0.0.1:6043: connect: connection refused
07/15 11:26:15.006836 00000036 taos_ADAPTER error "write to server error" error=Post "http://127.0.0.1:6043/adapter_report": dial tcp 127.0.0.1:6043: connect: connection refused model=monitor
07/15 11:26:30.010096 00000036 taos_ADAPTER error "write to server error" model=monitor error=Post "http://127.0.0.1:6043/adapter_report": dial tcp 127.0.0.1:6043: connect: connection refused

**Comment by yu285** [comment]
服务端进程在正常工作吗？

**Comment by veigara** [comment]
没有启动起来，adapter不能连接

**Comment by yu285** [comment]
是无法启动吗？

是的话 sudo taosd ,看一下底下的报错。

**Comment by NephilimJaeger** [comment]
> Can't start?
> 
> If yes, run sudo taosd and check the error below.


I'm getting a similar error with version 3.3.2.0 but started when I tried to bump my cluster to 4 replicas.
I'd run sudo taosd in the pod and get this error

`DND ERROR failed to init dnode since Config not found`

**Comment by Gallium70** [comment]
疑似原因是 3.3.x 版本的容器镜像中 adapter 和 keeper 等组件都没有理会 `TAOS_FQDN` 环境变量或是 `taos.cfg` 中的 `fqdn` 参数，都用了各自配置文件 (`/etc/taos` 路径下的 `taos.cfg`, `explorer.toml`, `taosadapter.toml`, `taoskeeper.toml`) 中的配置 (`buildkitsandbox`) 。一种解决方案是把它们的配置文件全部拖出来，批量替换 `buildkitsandbox` 为真正的主机名，映射回容器中覆盖 (`-v "./tdengine-config:/etc/taos"`) 。

可能相关的问题：
#26363 #23613 #26765 #25354
