### ISSUE TITLE
查询导出csv文件数据失败

### ISSUE THREAD

**Issue by moco2022** [taosdata/TDengine#26581]
在终端使用SQL语句可以查询导出csv文件数据，在代码中却导出失败了。
![image](https://github.com/user-attachments/assets/bd781b88-9902-470e-8592-86d13f1f190f)
![image](https://github.com/user-attachments/assets/2a20da44-64f7-4f8e-82ec-5102f5a832ba)
![image](https://github.com/user-attachments/assets/bb0c0f2d-2d39-4027-9646-e740759bd451)

**Comment by yu285** [comment]
csv 导出是taos shell 专属的工具。
