### ISSUE TITLE
查询时间窗口范围内的聚合数据，时间窗口被分成了两个

### ISSUE THREAD

**Issue by jragray** [taosdata/TDengine#26611]
![image](https://github.com/user-attachments/assets/e4c3ce9e-efe4-4989-b9bb-404c444fcaa3)

查询的时间范围刚好16小时，但返回结果被拆分成两条数据，且_wstart也和我设置的起始时间不一样，有人遇到过同样问题或有解决方法吗？

**Comment by Wuyiz** [comment]
td的窗口就是这样，你传的只是查询范围，圈定了数据有哪些，但划分时间窗口是按照每天的0点来算的，然后再按照你圈定的数据填入对应的窗口范围

**Comment by jragray** [comment]
> td的窗口就是这样，你传的只是查询范围，圈定了数据有哪些，但划分时间窗口是按照每天的0点来算的，然后再按照你圈定的数据填入对应的窗口范围

感谢，我已经找到办法解决了这个问题
