### ISSUE TITLE
taosws.QueryError: [0x0018] Internal error: `Too many open files`

### ISSUE THREAD

**Issue by mesquita** [taosdata/TDengine#26613]
**Bug Description**
I'm having a problem when trying make a query using the websocket connection. 
The problem that I get:
```
taosws.QueryError: [0x0018] Internal error: `Too many open files`
```

**To Reproduce**
1. Use the websocket connection
2. Make a query to TDEngine

**Expected Behavior**
The query should work.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Linux
 - TDengine Version 3.3.2.0

Is this some configuration problem? I did not find anything on your code/doc about it.

**Comment by yu285** [comment]
please change the amount of open file in docker .

**Comment by yu285** [comment]
google can provide the specific  steps.

**Comment by fofoni** [comment]
Hello @yu285

One thing I can't understand is: which process is opening too many fds? Is it the taosws implementation in my client app opening too many sockets, or is it the database itself?

I suspect it must be TDengine itself opening too many actual files on the filesystem, but the traceback I get is not very helpful:
```
  ...
  File "/path/to/my_application.py", line 241, in _query_tdengine
    result = conn.query(query)
             ^^^^^^^^^^^^^^^^^
taosws.QueryError: [0x0018] Internal error: `Too many open files`
```

Assuming it's the database process that's opening too many files, is there a guideline anywhere for how many open fds should be allowed in the ulimit? Based on the number of tables and amount of data in each table, or something like this?

If there is no such guideline, would it be ok to simply keep doubling the current ulimit until we don't get the error anymore? Or could this lead to other issues?

**Comment by yu285** [comment]
yes！ you are correct ,  this error is from database server side . but it is difficult to calculate , it depends on the amount of data files under $DataDir  that your query touched. it depends on how many query you are running simultaneously,  it is heavily related to your configuration of TDengine . 

hence it is hard to provide your a specific ,precisely  formula

**Comment by fofoni** [comment]
I understand, thanks!
