### ISSUE TITLE
JDBC 批量插入，会丢失大量数据

### ISSUE THREAD

**Issue by f987002856** [taosdata/TDengine#2661]
**Bug Description**
1、使用 JDBC batch 插入 5000 条数据，最终到达数据库的只有 2046 条。
2、不使用 batch 插入，每一条数据单独使用 statement.executeUpdate(); 也会出现数据丢失的情况
（注：低性能服务器不会出现这问题，高性能服务器会出现，服务器配置在下方）

**代码如下**
```
package com.example.tdengine;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;

import java.sql.Connection;
import java.sql.Statement;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class Test5 {
    private static HikariDataSource ds;
    //拼接字段值
    static volatile int ddf = 819;
    // 字段值
    static String tagname = "t" + ddf;
    // 固定 sql 语句
    static String sb11 = "";
    public static void main(String[] args) {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl("jdbc:TAOS://localhost:6030/ctest");
        config.setUsername("root");
        config.setPassword("taosdata");
        config.setMinimumIdle(3);
        config.setMaximumPoolSize(51);
        config.setConnectionTimeout(10000);
        config.setIdleTimeout(60000);
        config.setConnectionTestQuery("describe log.dn");
        config.setValidationTimeout(10000);
        ds = new HikariDataSource(config);
        ExecutorService executorService = Executors.newFixedThreadPool(21);
        //组织固定sql语句
        StringBuilder sb1 = new StringBuilder();
        for (int i = 0; i < 250; i++) {
            sb1.append((10 * Math.random()));
            if (i == 249) {
                sb1.append(")");
            } else {
                sb1.append(",");
            }
        }
        sb11 = sb1.toString();
        while(true) {
            System.out.println("run ---> " + tagname);
            for (int i = 0; i < 20; i++) {
                final int j = i;
                executorService.execute(new Runnable() {
                    @Override
                    public void run() {
                        Connection connection = null; // get connection
                        try {
                            connection = ds.getConnection();
                            connection.setAutoCommit(false);
                            long startTime = System.currentTimeMillis();
                            Statement statement = connection.createStatement(); // get statement
                            for (int ts = 1; ts <= 5000; ts++) {
                                StringBuilder sb = new StringBuilder();
                                sb.append("INSERT INTO tbz");
                                sb.append(j);
                                sb.append(" VALUES (0, '");
                                sb.append(tagname);
                                sb.append("',");
                                sb.append(ts);
                                sb.append(",");
                                sb.append(sb11);
                                statement.addBatch(sb.toString());
                            }
                            //批量插入
                            statement.executeBatch();
                            connection.commit();
                            System.out.println("耗时 ---> " + (System.currentTimeMillis() - startTime));
                            statement.close();
                            connection.close();
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }

                });
            }
            try {
                Thread.sleep(20000);
                tagname = "t" + (++ddf);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }

    }
}
```

**截图**
![1594720307(1)](https://user-images.githubusercontent.com/12999173/87411782-c670d280-c5fa-11ea-8390-81a349c1c595.jpg)
![1594720404(1)](https://user-images.githubusercontent.com/12999173/87411898-f324ea00-c5fa-11ea-8c85-3c14f2c46ac5.jpg)

**服务器配置如下:**
 - OS: [CentOS 7.0]
 - Memory  1T, CPU 128 核, current Disk Space：1.6T
 - TDengine Version [1.6.6.1]

**Comment by Aries-Lee1991** [comment]
好的，我们看一下。

**Comment by xiaopingcs** [comment]
Hello, can you share you table schema? at least schema for first 5 columns. Please make sure the first column is timestamp and every record should have a different timestamp. please try again and let us know.

**Comment by f987002856** [comment]
> Hello, can you share you table schema? at least schema for first 5 columns. Please make sure the first column is timestamp and every record should have a different timestamp. please try again and let us know.

这是使用 describe table 打印的表结构信息，表共有 253 列，前几列如下图，其他的部分都是 double 类型。
![1594785462(1)](https://user-images.githubusercontent.com/12999173/87501838-abea3800-c692-11ea-9d16-a54ee2cb8e43.jpg)
插入数据的时候，ts 传入的值是 0，TDengine 会默认转为 timestamp 存储。我不知道会不会在转换过程中不同的数据出现相同的 timestamp。
请问一张表里的不同数据，不可以出现相同的 timestamp 时间吗？如果一张表被不同的客户端同时大量插入，肯定会出现相同的 timestamp

**Comment by f987002856** [comment]
![1594785462(1)](https://user-images.githubusercontent.com/12999173/87502097-4d718980-c693-11ea-9dfb-640500beefdc.jpg)

**Comment by xiaopingcs** [comment]
> > Hello, can you share you table schema? at least schema for first 5 columns. Please make sure the first column is timestamp and every record should have a different timestamp. please try again and let us know.
> 
> 这是使用 describe table 打印的表结构信息，表共有 253 列，前几列如下图，其他的部分都是 double 类型。
> ![1594785462(1)](https://user-images.githubusercontent.com/12999173/87501838-abea3800-c692-11ea-9d16-a54ee2cb8e43.jpg)
> 插入数据的时候，ts 传入的值是 0，TDengine 会默认转为 timestamp 存储。我不知道会不会在转换过程中不同的数据出现相同的 timestamp。
> 请问一张表里的不同数据，不可以出现相同的 timestamp 时间吗？如果一张表被不同的客户端同时大量插入，肯定会出现相同的 timestamp

Thanks for quick response. You are correct, duplicate timestamps are not allowed in the same table for following reasons:
1. Our database supports timestamp from microseconds, in future it should support milliseconds. 
2. The data of our database comes from devices, like cars. Each device has a table, one device is not likely to send data every microsecond.
If you are interested, you are very welcome to read below documentation from our website: https://www.taosdata.com/downloads/TDengine%20White%20Paper.pdf

Also, can you try to run your code again with different timestamps and let us know if you still have this issue? If yes, we will fix it ASAP.

Again, thanks very much for reporting issues.

**Comment by f987002856** [comment]
> > > Hello, can you share you table schema? at least schema for first 5 columns. Please make sure the first column is timestamp and every record should have a different timestamp. please try again and let us know.
> > 
> > 
> > 这是使用 describe table 打印的表结构信息，表共有 253 列，前几列如下图，其他的部分都是 double 类型。
> > ![1594785462(1)](https://user-images.githubusercontent.com/12999173/87501838-abea3800-c692-11ea-9d16-a54ee2cb8e43.jpg)
> > 插入数据的时候，ts 传入的值是 0，TDengine 会默认转为 timestamp 存储。我不知道会不会在转换过程中不同的数据出现相同的 timestamp。
> > 请问一张表里的不同数据，不可以出现相同的 timestamp 时间吗？如果一张表被不同的客户端同时大量插入，肯定会出现相同的 timestamp
> 
> Thanks for quick response. You are correct, duplicate timestamps are not allowed in the same table for following reasons:
> 
> 1. Our database supports timestamp from microseconds, in future it should support milliseconds.
> 2. The data of our database comes from devices, like cars. Each device has a table, one device is not likely to send data every microsecond.
>    If you are interested, you are very welcome to read below documentation from our website: https://www.taosdata.com/downloads/TDengine%20White%20Paper.pdf
> 
> Also, can you try to run your code again with different timestamps and let us know if you still have this issue? If yes, we will fix it ASAP.
> 
> Again, thanks very much for reporting issues.

**Comment by f987002856** [comment]
> > > > Hello, can you share you table schema? at least schema for first 5 columns. Please make sure the first column is timestamp and every record should have a different timestamp. please try again and let us know.
> > > 
> > > 
> > > 这是使用 describe table 打印的表结构信息，表共有 253 列，前几列如下图，其他的部分都是 double 类型。
> > > ![1594785462(1)](https://user-images.githubusercontent.com/12999173/87501838-abea3800-c692-11ea-9d16-a54ee2cb8e43.jpg)
> > > 插入数据的时候，ts 传入的值是 0，TDengine 会默认转为 timestamp 存储。我不知道会不会在转换过程中不同的数据出现相同的 timestamp。
> > > 请问一张表里的不同数据，不可以出现相同的 timestamp 时间吗？如果一张表被不同的客户端同时大量插入，肯定会出现相同的 timestamp
> > 
> > 
> > Thanks for quick response. You are correct, duplicate timestamps are not allowed in the same table for following reasons:
> > 
> > 1. Our database supports timestamp from microseconds, in future it should support milliseconds.
> > 2. The data of our database comes from devices, like cars. Each device has a table, one device is not likely to send data every microsecond.
> >    If you are interested, you are very welcome to read below documentation from our website: https://www.taosdata.com/downloads/TDengine%20White%20Paper.pdf
> > 
> > Also, can you try to run your code again with different timestamps and let us know if you still have this issue? If yes, we will fix it ASAP.
> > Again, thanks very much for reporting issues.

你好，我这面使用了不同的时间戳进行了测试，5000 条数据可以完整的插入，不会丢失。但是插入的时间要至少增加（插入的总总条数 / 1000）秒

**Comment by xiaopingcs** [comment]
> > > > > Hello, can you share you table schema? at least schema for first 5 columns. Please make sure the first column is timestamp and every record should have a different timestamp. please try again and let us know.
> > > > 
> > > > 
> > > > 这是使用 describe table 打印的表结构信息，表共有 253 列，前几列如下图，其他的部分都是 double 类型。
> > > > ![1594785462(1)](https://user-images.githubusercontent.com/12999173/87501838-abea3800-c692-11ea-9d16-a54ee2cb8e43.jpg)
> > > > 插入数据的时候，ts 传入的值是 0，TDengine 会默认转为 timestamp 存储。我不知道会不会在转换过程中不同的数据出现相同的 timestamp。
> > > > 请问一张表里的不同数据，不可以出现相同的 timestamp 时间吗？如果一张表被不同的客户端同时大量插入，肯定会出现相同的 timestamp
> > > 
> > > 
> > > Thanks for quick response. You are correct, duplicate timestamps are not allowed in the same table for following reasons:
> > > 
> > > 1. Our database supports timestamp from microseconds, in future it should support milliseconds.
> > > 2. The data of our database comes from devices, like cars. Each device has a table, one device is not likely to send data every microsecond.
> > >    If you are interested, you are very welcome to read below documentation from our website: https://www.taosdata.com/downloads/TDengine%20White%20Paper.pdf
> > > 
> > > Also, can you try to run your code again with different timestamps and let us know if you still have this issue? If yes, we will fix it ASAP.
> > > Again, thanks very much for reporting issues.
> 
> 你好，我这面使用了不同的时间戳进行了测试，5000 条数据可以完整的插入，不会丢失。但是插入的时间要至少增加（插入的总总条数 / 1000）秒 ，希望在以后的版本中，可以增加时间戳相同的数据行，拓展使用场景。
> 谢谢你们的开源，辛苦了。

Thanks for confirming, we are improving the performance. Closing this issue.
