### ISSUE TITLE
TDengine ERROR (0x8000090c): Sync leader is unreachable

### ISSUE THREAD

**Issue by chenhuan3012** [taosdata/TDengine#26632]
TDengine版本：3.1.0.0
5个节点，3副本部署。

单表查询，同一个表，使用LAST_ROW函数时会出现错误，但直接查询正常：
TDengine ERROR (0x8000090c): Sync leader is unreachable; uncategorized SQLException; SQL state []; error code [-2147481332];

出现错误的查询SQL: SELECT LAST_ROW(*)  FROM ?
正常查询的SQL：SELECT *  FROM ?

**Comment by yu285** [comment]
该问题已经修复，麻烦升级到 3.3.2.0。
