### ISSUE TITLE
容器内tdengine数据库不能正确读取系统时区信息

### ISSUE THREAD

**Issue by chenkline** [taosdata/TDengine#26651]
**Bug Description**
容器内不能正确读取系统时区信息，期望数据库时区自动跟随宿主机系统时区

**To Reproduce**
目标预期是容器内tdengine数据库时区自动跟随宿主机系统时区

1. 生成 Dockerfile_tdengine 文件内容
cat << EOF > ./Dockerfile_tdengine
FROM tdengine/tdengine:3.3.0.0
RUN rm -f /etc/localtime
EOF

2. 建立镜像
docker build --network host -t tdengine:3.3.0.0 -f Dockerfile_tdengine ./

3. 启动镜像
docker run -d -v /opt/app/var/lib/taos:/var/lib/taos    -v /opt/app/var/log/taos:/var/log/taos    -v /etc/localtime:/etc/localtime     -v /usr/share/zoneinfo:/usr/share/zoneinfo:ro    --name ailink-tdengine -h tdengine --network host    tdengine:3.3.0.0

4. 查看和比对宿主机系统时区和容器内系统时区(结果为容器内外系统时区相同，符合预期)
date
2024年 07月 18日 星期四 10:37:31 HKT

docker exec -it ailink-tdengine date
Thu Jul 18 10:36:38 AM HKT 2024

5. 查看容器内tdengine数据库时区（输出结果为UTC时区，与容器系统时区不同，不符合预期）
docker exec -it ailink-tdengine taos -s 'SELECT TIMEZONE();'

failed to get fqdn, code:-2, reason:Name or service not known
read /etc/localtime error, reason:Invalid argumentWelcome to the TDengine Command Line Interface, Client Version:3.3.0.0
Copyright (c) 2023 by TDengine, all rights reserved.

taos> SELECT TIMEZONE();
           timezone()           |
=================================
 Etc/UTC (UTC, +0000)           |
Query OK, 1 row(s) in set (0.000941s)

**Expected Behavior**
SELECT TIMEZONE(); 查询结果为系统时区 HKT

**Screenshots**

**Environment (please complete the following information):**
 - OS: [CentOS 6.9] (宿主机)
 - Memory, CPU, current Disk Space
 - TDengine Version [3.3.0.0]

**Additional Context**
由于业务场景期望自动跟随宿主机系统时区，容器未设置TZ环境变量
推测原因是，tdengine数据强制认定  /etc/localtime 必须是符号文件，只分析符号文件指向文件的名称，而没有读取文件指向的最终文件内容。

**Comment by chenkline** [comment]
补充信息:  由于业务场景期望自动跟随宿主机系统时区，容器未设置TZ环境变量

**Comment by yu285** [comment]
yuchen@JadeChenMBP three_node % cat docker-compose.yml 
version: "3"
services:
  taosnode1:
      #开机自启
      restart: always
      #指定镜像
      image: tdengine/tdengine:3.3.2.0
      #指定容器hostname
      hostname: taosnode1
      #容器名称
      container_name: taosnode1
      #创建容器后默认执行的命令
      privileged: true
      #容器的映射端口
      ports:
        - 6020:6020
        - 6030-6042:6030-6042/tcp
        - 6030-6042:6030-6042/udp
        - 6060:6060/tcp

      #定义挂载点
      volumes:
        - /etc/localtime:/etc/localtime:ro #同步主机时区到容器
        - ./data/node1data:/var/lib/taos
        - ./etc/node1etc:/etc/taos
        - ./log/node1log:/var/log/taos
  
  taosnode2:
      restart: always
      image: tdengine/tdengine:latest
      hostname: taosnode2
      container_name: taosnode2
      privileged: true
      ports:
        - 7020:7020
        - 7030-7042:7030-7042/tcp
        - 7030-7042:7030-7042/udp
      volumes:
        - /etc/localtime:/etc/localtime:ro #同步主机时区到容器
        - ./data/node2data:/var/lib/taos
        - ./etc/node2etc:/etc/taos
        - ./log/node2log:/var/log/taos

  taosnode3:
      restart: always
      image: tdengine/tdengine:latest
      hostname: taosnode3
      container_name: taosnode3
      privileged: true
      ports:
        - 8020:8020
        - 8030-8042:8030-8042/tcp
        - 8030-8042:8030-8042/udp
      volumes:
        - /etc/localtime:/etc/localtime:ro #同步主机时区到容器
        - ./data/node3data:/var/lib/taos
        - ./etc/node3etc:/etc/taos
        - ./log/node3log:/var/log/taos


这个docker-compose 能否有帮助。

**Comment by chenkline** [comment]
/etc/localtime:/etc/localtime:ro 和 /etc/localtime:/etc/localtime 是一样的，而且目前出现的问题不是容器的系统时区没有跟随宿主机系统时区，而是tdegine数据库的时区没有跟随容器的系统时区

**Comment by yu285** [comment]
> /etc/localtime:/etc/localtime:ro 和 /etc/localtime:/etc/localtime 是一样的，而且目前出现的问题不是容器的系统时区没有跟随宿主机系统时区，而是tdegine数据库的时区没有跟随容器的系统时区 即：第4步的检查结果是正确符合预期的，第5步的检查结果不符合预期

![image](https://github.com/user-attachments/assets/2b8f4cce-cad8-4e57-bb82-82e890e58acf)
我使用这个docker-compose 是没问题的，数据库的时区正常同步，要不您那边仔细对比排查一下？
