### ISSUE TITLE
Alternative install directory

### ISSUE THREAD

**Issue by dakhnod** [taosdata/TDengine#26667]
I am trying to automate the TDEngine installation in order to build a nix package.
I download the prebuild zip and run install.sh.
The issue is that the install script attempts to create /usr, which is not allowed in the nix build process.

Is there any way to change the installation directory?
If not, could you implement env variables or arguments to the install.sh script?

**Comment by yu285** [comment]
please provide the version you are using please.

**Comment by yu285** [comment]
you can backup install.sh then  try to edit install.sh  to change it
