### ISSUE TITLE
Mybatis query float data error

### ISSUE THREAD

**Issue by mooska7** [taosdata/TDengine#2669]
**Bug Description**
SrpingBoot服务集成mybatis，查询时发现float的数据在程序中（实体对应属性是bigdecinal）变成了整数

**Comment by Aries-Lee1991** [comment]
版本号、日志等详细信息麻烦发一下。

**Comment by piziZhang2017** [comment]
SrpingBoot服务集成mybatis，能够连接tdegine吗

**Comment by sangshuduo** [comment]
长时间没有更新，暂时关闭。 @m
