### ISSUE TITLE
How to config telegraf to create multiple supertable and it's tables under one input plugin item

### ISSUE THREAD

**Issue by tonycheng518** [taosdata/TDengine#2674]
Hi, guys at taosdata, i use the default configuration like this:
###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################

# Read metrics about cpu usage
[[inputs.cpu]]
  ## Whether to report per-cpu stats or not
  percpu = true
  ## Whether to report total system cpu stats or not
  totalcpu = true
  ## If true, collect raw CPU time metrics.
  collect_cpu_time = false
  ## If true, compute and report the sum of all non-idle CPU states.
  report_active = false
# Read metrics about disk usage by mount point
[[inputs.disk]]
# Read metrics about disk IO by device
[[inputs.diskio]]
# Get kernel statistics from /proc/stat
[[inputs.kernel]]
# Read metrics about memory usage
[[inputs.mem]]
# Get the number of processes and group them by status
[[inputs.processes]]
# Read metrics about system load & uptime
[[inputs.system]]

[[outputs.http]]
#   ## URL is the address to send metrics to
    url = "http://127.0.0.1:6020/telegraf/udb"
#   ## HTTP method, one of: "POST" or "PUT"
    method = "POST"
#   ## HTTP Basic Auth credentials
    username = "root"
    password = "taosdata"
#   # data format to output
    data_format = "json"
    json_timestamp_units = "1ms"
after booting telegraf and taosd, i use taos to connect, then i get:
taos> show databases;
              name              |     created time     |  ntables  |  vgroups  |replica| days  |  keep1,keep2,keep(D)   |  tables   |   rows    | cache(b)  |      ablocks       |tblocks| ctime(s)  | clog | comp |time precision|  status  |
==============================================================================================================================================================================================================================================
udb                             | 20-07-15 11:36:30.597|         40|          1|      1|     10|3650,3650,3650          |       1000|       4096|      16384|             4.00000|     50|       3600|     1|     2|ms            |ready     |
log                             | 20-06-30 18:11:34.264|          6|          1|      1|     10|30,30,30                |         32|       1024|       2048|             2.00000|     32|       3600|     1|     2|us            |ready     |
Query OK, 2 row(s) in set (0.021036s)

taos> use udb;
Database changed.

taos> show stables;
                              name                              |     created_time     |columns| tags  |  tables   |
====================================================================================================================
cpu_usage                                                       | 20-07-15 11:36:50.019|     11|      2|          3|
system_uptime                                                   | 20-07-15 11:36:40.067|      2|      1|          1|
kernel                                                          | 20-07-15 11:36:40.066|      6|      1|          1|
system_uptime_format                                            | 20-07-15 11:36:40.063|      2|      1|          1|
processes                                                       | 20-07-15 11:36:40.062|     12|      1|          1|
mem                                                             | 20-07-15 11:36:30.658|     36|      1|          1|
swap                                                            | 20-07-15 11:36:30.657|      5|      1|          1|
swap_in                                                         | 20-07-15 11:36:30.656|      3|      1|          1|
disk                                                            | 20-07-15 11:36:30.654|      8|      5|          3|
system                                                          | 20-07-15 11:36:30.653|      6|      1|          1|
diskio                                                          | 20-07-15 11:36:30.597|     12|      2|         26|
Query OK, 11 row(s) in set (0.013983s)

taos> show tables;
                           table_name                           |     created_time     |columns|                             stable                             |
=================================================================================================================================================================
diskio_zqs_virtual_machine_worker_node1_loop0                   | 20-07-15 11:36:30.645|     12|diskio                                                          |
diskio_zqs_virtual_machine_worker_node1_loop1                   | 20-07-15 11:36:30.650|     12|diskio                                                          |
diskio_zqs_virtual_machine_worker_node1_loop2                   | 20-07-15 11:36:30.650|     12|diskio                                                          |
diskio_zqs_virtual_machine_worker_node1_loop3                   | 20-07-15 11:36:30.641|     12|diskio                                                          |
diskio_zqs_virtual_machine_worker_node1_loop4                   | 20-07-15 11:36:30.640|     12|diskio                                                          |
diskio_zqs_virtual_machine_worker_node1_loop5                   | 20-07-15 11:36:30.647|     12|diskio                                                          |
diskio_zqs_virtual_machine_worker_node1_loop6                   | 20-07-15 11:36:30.644|     12|diskio                                                          |
diskio_zqs_virtual_machine_worker_node1_loop7                   | 20-07-15 11:36:30.645|     12|diskio                                                          |
diskio_zqs_virtual_machine_worker_node1_loop8                   | 20-07-15 11:36:30.647|     12|diskio                                                          |
diskio_zqs_virtual_machine_worker_node1_loop9                   | 20-07-15 11:36:30.651|     12|diskio                                                          |
diskio_zqs_virtual_machine_worker_node1_loop11                  | 20-07-15 11:36:30.642|     12|diskio                                                          |
diskio_zqs_virtual_machine_worker_node1_loop16                  | 20-07-15 11:36:40.059|     12|diskio                                                          |
cpu_usage_zqs_virtual_machine_worker_node1_cpu0                 | 20-07-15 11:36:50.021|     11|cpu_usage                                                       |
cpu_usage_zqs_virtual_machine_worker_node1_cpu1                 | 20-07-15 11:36:50.019|     11|cpu_usage                                                       |
diskio_zqs_virtual_machine_worker_node1_loop10                  | 20-07-15 11:36:30.642|     12|diskio                                                          |
diskio_zqs_virtual_machine_worker_node1_loop15                  | 20-07-15 11:36:30.646|     12|diskio                                                          |
disk_zqs_virtual_machine_worker_node1_sda5_ext4_rw__home        | 20-07-15 11:36:30.654|      8|disk                                                            |
processes_zqs_virtual_machine_worker_node1                      | 20-07-15 11:36:40.062|     12|processes                                                       |
system_uptime_format_zqs_virtual_machine_worker_node1           | 20-07-15 11:36:40.064|      2|system_uptime_format                                            |
disk_zqs_virtual_machine_worker_node1_sda1_ext4_rw__boot        | 20-07-15 11:36:30.655|      8|disk                                                            |
system_zqs_virtual_machine_worker_node1                         | 20-07-15 11:36:30.653|      6|system                                                          |
diskio_zqs_virtual_machine_worker_node1_loop14                  | 20-07-15 11:36:40.057|     12|diskio                                                          |
swap_in_zqs_virtual_machine_worker_node1                        | 20-07-15 11:36:30.656|      3|swap_in                                                         |
mem_zqs_virtual_machine_worker_node1                            | 20-07-15 11:36:30.660|     36|mem                                                             |
diskio_zqs_virtual_machine_worker_node1_loop19                  | 20-07-15 11:36:40.005|     12|diskio                                                          |
cpu_usage_zqs_virtual_machine_worker_node1_cpu_total            | 20-07-15 11:36:50.019|     11|cpu_usage                                                       |
kernel_zqs_virtual_machine_worker_node1                         | 20-07-15 11:36:40.066|      6|kernel                                                          |
diskio_zqs_virtual_machine_worker_node1_loop13                  | 20-07-15 11:36:30.649|     12|diskio                                                          |
diskio_zqs_virtual_machine_worker_node1_loop18                  | 20-07-15 11:36:30.640|     12|diskio                                                          |
diskio_zqs_virtual_machine_worker_node1_sda                     | 20-07-15 11:36:30.644|     12|diskio                                                          |
diskio_zqs_virtual_machine_worker_node1_sda1                    | 20-07-15 11:36:30.643|     12|diskio                                                          |
diskio_zqs_virtual_machine_worker_node1_sda2                    | 20-07-15 11:36:30.647|     12|diskio                                                          |
diskio_zqs_virtual_machine_worker_node1_sda3                    | 20-07-15 11:36:30.652|     12|diskio                                                          |
diskio_zqs_virtual_machine_worker_node1_sda4                    | 20-07-15 11:36:30.643|     12|diskio                                                          |
diskio_zqs_virtual_machine_worker_node1_sda5                    | 20-07-15 11:36:30.651|     12|diskio                                                          |
disk_zqs_virtual_machine_worker_node1_sda3_ext4_rw__            | 20-07-15 11:36:30.655|      8|disk                                                            |
swap_zqs_virtual_machine_worker_node1                           | 20-07-15 11:36:30.657|      5|swap                                                            |
diskio_zqs_virtual_machine_worker_node1_loop12                  | 20-07-15 11:36:30.646|     12|diskio                                                          |
system_uptime_zqs_virtual_machine_worker_node1                  | 20-07-15 11:36:40.067|      2|system_uptime                                                   |
diskio_zqs_virtual_machine_worker_node1_loop17                  | 20-07-15 11:36:30.648|     12|diskio                                                          |
Query OK, 40 row(s) in set (0.041782s)
we can see that 11 supertable created, each of them have several tables in it.
now i want to create several supertables and each of which has many tables in it under one input plugin like input.kafka_consumr, how can i do it?

**Comment by liuyq-617** [comment]
我们目前还不支持telegraf的其他监控信息及消费服务
如果有这方面的需要，可以看下白龙马模块https://www.taosdata.com/blog/2020/02/03/1189.html
