### ISSUE TITLE
Can not start 3.3.0.0 on Amazon Linux 2023, but 2.6 works fine

### ISSUE THREAD

**Issue by eric-yq** [taosdata/TDengine#26758]
Hi all,

I am user of AWS cloud, my instance type is c7g.4xlarge(Graviton3 CPU, aarch64) with OS Amazon Linux 2023.

I can build 2.6.0.34 version successfully , taosBenchmark runs well.
![image](https://github.com/user-attachments/assets/522875af-24c6-4643-bbf0-ce1181b2a9a1)

When I build 3.3.0.0 on the same instance type and OS, it shows successfully.
But failed to start taosd:
![image](https://github.com/user-attachments/assets/6b04dce0-5342-46d3-a3b4-894dc66bd3ad)

I check logs, it show:
......
![image](https://github.com/user-attachments/assets/2ed0b660-72ce-4937-b90c-00d7c4470727)

Can you check what should I do ?

Thanks.

**Comment by yu285** [comment]
https://docs.tdengine.com/reference/support-platform/

sorry 3.x doesn't support this 

please change OS or use docker is fine
