### ISSUE TITLE
alter supportVnodes error

### ISSUE THREAD

**Issue by wyzzzl** [taosdata/TDengine#26753]
Ubuntu 18.04 ，版本 3.3.2 ，执行以下命令报错：

```
taos> alter dnode 2 'supportvnodes 60';

DB error: Invalid config option (0.000213s)
taos>
```

我参考了  https://github.com/taosdata/TDengine/releases ， 里面提及该版本已支持动态调整 supportvnodes，这是哪里有问题？

**Comment by yu285** [comment]
抱歉，这个是企业版功能。我们已经修改了文档
