### ISSUE TITLE
Whether 2.6 support Arm Neon for SIMD operations？

### ISSUE THREAD

**Issue by eric-yq** [taosdata/TDengine#26761]
I am using ver 2.6, plan to migrating to aarch64-based server.
Whether ver 2.6 can support Arm Neon for SIMD?
Or which version is suggested on aarch64-based server?

Thanks.

**Comment by yu285** [comment]
we haven't  supported 2.6  version any more, we suggest you use newest version (currently 3.3.2.0)

https://docs.tdengine.com/reference/support-platform/

above is support-platform, please check .
