### ISSUE TITLE
taos-explorer 使用docker-compose 伪集群方式怎么配置

### ISSUE THREAD

**Issue by flyrun9527** [taosdata/TDengine#26769]
**Bug Description**

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

taos-explorer 使用docker-compose 伪集群方式怎么配置

**Comment by flyrun9527** [comment]
https://docs.taosdata.com/deployment/docker/#taosadapter  这种方式

**Comment by yu285** [comment]
https://docs.taosdata.com/operation/deployment/
