### ISSUE TITLE
Taoskeeper Metric: exist 'unknown' labels

### ISSUE THREAD

**Issue by quinniup** [taosdata/TDengine#26778]
**Bug Description**
- The 'sql_req_count' metric exist 'unknown' labels when 'sql_type' is 'select', 'insert' and 'delete'.

**To Reproduce**
1. request taoskeeper 'metrics' RESTful API.

**Expected Behavior**
taos_sql_req_count{cluster_id="2146726896535871438",dnode_ep="tdengine-test03:6030",dnode_id="1",result="Success",sql_type="inserted_rows",username="root",vgroup_id="3"} 0
taos_sql_req_count{cluster_id="2146726896535871438",dnode_ep="tdengine-test03:6030",dnode_id="1",result="Success",sql_type="inserted_rows",username="root",vgroup_id="34"} 0
taos_sql_req_count{cluster_id="2146726896535871438",dnode_ep="tdengine-test03:6030",dnode_id="1",result="Success",sql_type="inserted_rows",username="root",vgroup_id="35"} 0
taos_sql_req_count{cluster_id="2146726896535871438",dnode_ep="tdengine-test03:6030",dnode_id="3",result="Success",sql_type="inserted_rows",username="root",vgroup_id="23"} 67
taos_sql_req_count{cluster_id="2146726896535871438",dnode_ep="unknown",dnode_id="unknown",result="Failed",sql_type="delete",username="root",vgroup_id="unknown"} 0
taos_sql_req_count{cluster_id="2146726896535871438",dnode_ep="unknown",dnode_id="unknown",result="Failed",sql_type="insert",username="root",vgroup_id="unknown"} 0
taos_sql_req_count{cluster_id="2146726896535871438",dnode_ep="unknown",dnode_id="unknown",result="Failed",sql_type="select",username="root",vgroup_id="unknown"} 0
taos_sql_req_count{cluster_id="2146726896535871438",dnode_ep="unknown",dnode_id="unknown",result="Success",sql_type="delete",username="root",vgroup_id="unknown"} 0
taos_sql_req_count{cluster_id="2146726896535871438",dnode_ep="unknown",dnode_id="unknown",result="Success",sql_type="insert",username="root",vgroup_id="unknown"} 37
taos_sql_req_count{cluster_id="2146726896535871438",dnode_ep="unknown",dnode_id="unknown",result="Success",sql_type="select",username="root",vgroup_id="unknown"} 6
**Screenshots**
![image](https://github.com/user-attachments/assets/2542c2e4-ddcb-4eba-9fed-b7f857bdf70a)

**Environment (please complete the following information):**
 - TDengine Version [v3.2.3.0]

**Additional Context**

**Comment by yu285** [comment]
请问taoskeeper log 里有没有错误信息
