### ISSUE TITLE
WebSocket连接 插入数据报错

### ISSUE THREAD

**Issue by Zurant** [taosdata/TDengine#26785]
**Bug Description**
使用WebSocket连接，当插入的数据比较大时，会报错。主要是repBody这个字段长度比较长，我也打印到日志了。在报错后我使用mybatis去插入数据，是正常插入的！

**Screenshots**
代码：
![image](https://github.com/user-attachments/assets/83304051-c105-4fac-bb1c-f4e45701bca0)
报错信息：
![image](https://github.com/user-attachments/assets/d0815272-c0e1-4d88-8530-ab7d49b6106f)
mybatis正常插入打印的日志：
![image](https://github.com/user-attachments/assets/7055087c-f976-47e6-b4cf-fe95efc6b45c)
mapper xml插入语句
![image](https://github.com/user-attachments/assets/52b1db4d-bcb3-4911-bc0a-77fde0d453f1)

**Environment (please complete the following information):**
 - TDengine Version [3.3.0]

**Comment by yu285** [comment]
请问jdbc 驱动版本是多少。https://docs.taosdata.com/connector/java/

请确保jdbc 驱动版本和数据库版本对应关系正确。

**Comment by Zurant** [comment]
> 请问jdbc 驱动版本是多少。https://docs.taosdata.com/connector/java/
> 
> 请确保jdbc 驱动版本和数据库版本对应关系正确。

**Comment by Zurant** [comment]
> 请问jdbc 驱动版本是多少。https://docs.taosdata.com/connector/java/
> 
> 请确保jdbc 驱动版本和数据库版本对应关系正确。

jdbc驱动 3.3.0   Tdengine最新版本

**Comment by yu285** [comment]
加微信具体排查一下吧 ： a15652223354
