### ISSUE TITLE
Window10启动taos.exe一闪而过？

### ISSUE THREAD

**Issue by hechaotudou** [taosdata/TDengine#268]
Window10启动taos.exe一闪而过？

**Comment by hong6914** [comment]
1. Did you run it from a DOS prompt, or from Windows Explorer?
2. Better run it from a DOS prompt, and any error messages? If not, type this command to get the exit code:
echo %errorlevel%

If you get zero "0", file a bug as it does report the proper error code :-)

**Comment by hechaotudou** [comment]
从DOS提示符运行它,解决了我的问题。
