### ISSUE TITLE
大量子表查询超级表卡住问题

### ISSUE THREAD

**Issue by chaohz1** [taosdata/TDengine#26809]
**Bug Description**
查询超级表卡住问题
**To Reproduce**
1 一个空的ubuntu机器，只运行docker 版本的tdengine 3.3.2 
2 建库 create database platform
2 超级表建表 CREATE STABLE if not exists s_0915 (ts timestamp, val float) TAGS (deviceId binary(30), meteId binary(20),meteKind binary(2),modelId binary(20),regionId binary(20))
创建大约42个超级表
3 子表建表语句 create table if not exists `t_deviceId_meteId` using `s_0915` tags('0915..','0101..','1','0111...','01231...');
创建子表数量 44647351个子表
4 未插入数据 直接查询某个超级表
select * from s_0701 limit 10; 
基本就会卡住，而且taos命令连不上了

**Expected Behavior**

**Screenshots**
![WechatIMG522](https://github.com/user-attachments/assets/080aa54b-aa1b-444c-9660-fc39cff78e23)
![WechatIMG524](https://github.com/user-attachments/assets/6d5fcbb2-a0e5-4d27-94c7-9a0d659fd7a4)
![WechatIMG532](https://github.com/user-attachments/assets/722d3910-9bf9-4597-ab11-843be518bc7b)

**Environment (please complete the following information):**
 - OS: ubuntu 18.04
 - Memory 32G, CPU 8核,  Disk 500GB 
 - TDengine Version 3.3.2

**Additional Context**

**Comment by chaohz1** [comment]
建库 create database platform

**Comment by chaohz1** [comment]
由于库是默认建立 ，未进行调优配置，我仔细观察了下数据，发现子表越多查询越有问题，合适的范围是子表数量大约是50W ，超过这个就会超过1秒返回，上述问题s_0701 正好存在子表数量达到三千万，导致空库情况下查询卡死
<img width="947" alt="image" src="https://github.com/user-attachments/assets/34c6da59-3e5a-4319-b6f5-a3120de2d988">
<img width="349" alt="image" src="https://github.com/user-attachments/assets/b877029e-d48d-4b90-a1dd-f636a7ee2664">
<img width="1409" alt="image" src="https://github.com/user-attachments/assets/b8b247f3-5287-4e34-9fc3-6faed3b73d76">

**Comment by yu285** [comment]
4000+万子表太多了，建议不使用容器，然后多增加vgroup

**Comment by tomchon** [comment]
建议一个 vgroup 中的表数控制在 100 万以内。在硬件资源足够的情况下，控制在 1 万以内是最好的

**Comment by yu285** [comment]
暂作关闭处理，如果还有问题可以加微信：a15652223354
