### ISSUE TITLE
SQL 批量创建子表时是否可以使用不同的超级表？

### ISSUE THREAD

**Issue by Gallium70** [taosdata/TDengine#26808]
文档中对 [批量创建子表](https://docs.taosdata.com/taos-sql/table/#%E6%89%B9%E9%87%8F%E5%88%9B%E5%BB%BA%E5%AD%90%E8%A1%A8) 的语句定义是

```sql
CREATE TABLE [IF NOT EXISTS] tb_name1 USING stb_name TAGS (tag_value1, ...) [IF NOT EXISTS] tb_name2 USING stb_name TAGS (tag_value2, ...) ...;
```

此处 `tb_name1` 和 `tb_name2` 可以使用不同的超级表模板，还是必须使用同一个超级表？望解答，非常感谢。

**Comment by yu285** [comment]
应该是可以的，不过建议实测一下。比较好验证

**Comment by Gallium70** [comment]
试了下应该可以，谢谢

**Comment by Gallium70** [comment]
试了下应该可以，谢谢
