### ISSUE TITLE
tdengine3.0.2.2与tdengine3.0.0.0的group by的问题

### ISSUE THREAD

**Issue by LyneDefense** [taosdata/TDengine#26828]
**General Questions**
我原来的tdengine的版本是3.0.2.2，我里面有一个sql写的是select * from xxx having count(*) > 1。 但是我降级成3.0.0.0之后，这个sql报错了，显示的是我需要加上group by才能正常运行。 我在官方文档上也没找到相关的说明，想问一下这个是为什么？是做了什么优化吗？

**Comment by LyneDefense** [comment]
我上面的版本号写错了。请参照我这个版本号的问题。我原来的tdengine的版本是3.2.2.0，我里面有一个sql写的是select * from xxx having count(*) > 1。 但是我降级成3.0.2.2之后，这个sql报错了，显示的是我需要加上group by才能正常运行。 我在官方文档上也没找到相关的说明，想问一下这个是为什么？是做了什么优化吗？

**Comment by yu285** [comment]
新版本语法更灵活，另外不要降级，早期版本可能会遇到bug，新版本不论是功能还是稳定性都会更好。

**Comment by yu285** [comment]
如果有问题，可以随时联系我。暂作关闭处理 ,微信：a15652223354
