### ISSUE TITLE
error in golang connector with version 1.6.6.1

### ISSUE THREAD

**Issue by zhuqiyun** [taosdata/TDengine#2683]
07/15 21:47:54.973116 118265 7f98ec18fc00 ERROR TSC 0x18b4cd0 SQL result:76, not supported operation pObj:0x18b4b80

**Comment by Aries-Lee1991** [comment]
我们这边看一下。

**Comment by Aries-Lee1991** [comment]
请附上日志。

**Comment by zhuqiyun** [comment]
> 请附上日志。

==================================================
                new log file                      
==================================================
07/16 22:12:05.813934 5739 7f3f06ffd700 UTL timezone not configured, set to system default:Asia/Shanghai (CST, +0800)
07/16 22:12:05.813975 5739 7f3f06ffd700 UTL locale not configured, set to system default:en_US.UTF-8
07/16 22:12:05.813981 5739 7f3f06ffd700 UTL charset not configured, set to system default:UTF-8
07/16 22:12:05.813997 5739 7f3f06ffd700 UTL    taos config & system info:
07/16 22:12:05.814000 5739 7f3f06ffd700 UTL ==================================
07/16 22:12:05.814001 5739 7f3f06ffd700 UTL  masterIp:               192.168.1.194 
07/16 22:12:05.814002 5739 7f3f06ffd700 UTL  localIp:                0.0.0.0 
07/16 22:12:05.814003 5739 7f3f06ffd700 UTL  mgmtShellPort:          6030 
07/16 22:12:05.814004 5739 7f3f06ffd700 UTL  vnodeShellPort:         6035 
07/16 22:12:05.814005 5739 7f3f06ffd700 UTL  configDir:              /etc/taos 
07/16 22:12:05.814006 5739 7f3f06ffd700 UTL  logDir:                 /var/log/taos 
07/16 22:12:05.814008 5739 7f3f06ffd700 UTL  scriptDir:              /etc/taos 
07/16 22:12:05.814009 5739 7f3f06ffd700 UTL  numOfThreadsPerCore:    1.000000 
07/16 22:12:05.814012 5739 7f3f06ffd700 UTL  affectedRowsMod:        0 
07/16 22:12:05.814014 5739 7f3f06ffd700 UTL  rpcTimer:               300(ms)
07/16 22:12:05.814015 5739 7f3f06ffd700 UTL  rpcMaxTime:             600(s)
07/16 22:12:05.814016 5739 7f3f06ffd700 UTL  shellActivityTimer:     3(s)
07/16 22:12:05.814017 5739 7f3f06ffd700 UTL  meterMetaKeepTimer:     7200(s)
07/16 22:12:05.814018 5739 7f3f06ffd700 UTL  metricMetaKeepTimer:    600(s)
07/16 22:12:05.814019 5739 7f3f06ffd700 UTL  defaultDB:               
07/16 22:12:05.814020 5739 7f3f06ffd700 UTL  defaultUser:            root 
07/16 22:12:05.814021 5739 7f3f06ffd700 UTL  sockettype:             udp 
07/16 22:12:05.814022 5739 7f3f06ffd700 UTL  compressMsgSize:        -1 
07/16 22:12:05.814022 5739 7f3f06ffd700 UTL  maxSQLLength:           65380(byte)
07/16 22:12:05.814023 5739 7f3f06ffd700 UTL  maxAuthRetryTime:       5(byte)
07/16 22:12:05.814024 5739 7f3f06ffd700 UTL  maxNumOfOrderedRes:     100000 
07/16 22:12:05.814025 5739 7f3f06ffd700 UTL  timezone:               Asia/Shanghai (CST, +0800) 
07/16 22:12:05.814026 5739 7f3f06ffd700 UTL  locale:                 en_US.UTF-8 
07/16 22:12:05.814027 5739 7f3f06ffd700 UTL  charset:                UTF-8 
07/16 22:12:05.814028 5739 7f3f06ffd700 UTL  numOfLogLines:          10000000 
07/16 22:12:05.814029 5739 7f3f06ffd700 UTL  asyncLog:               1 
07/16 22:12:05.814030 5739 7f3f06ffd700 UTL  debugFlag:              131 
07/16 22:12:05.814031 5739 7f3f06ffd700 UTL  rpcDebugFlag:           131 
07/16 22:12:05.814032 5739 7f3f06ffd700 UTL  tmrDebugFlag:           131 
07/16 22:12:05.814033 5739 7f3f06ffd700 UTL  cDebugFlag:             131 
07/16 22:12:05.814034 5739 7f3f06ffd700 UTL  jniDebugFlag:           131 
07/16 22:12:05.814035 5739 7f3f06ffd700 UTL  odbcDebugFlag:          131 
07/16 22:12:05.814036 5739 7f3f06ffd700 UTL  uDebugFlag:             131 
07/16 22:12:05.814036 5739 7f3f06ffd700 UTL  qDebugFlag:             131 
07/16 22:12:05.814037 5739 7f3f06ffd700 UTL  gitinfo:                a1304e54b705890ecb82eb7766610c421b38bd77 
07/16 22:12:05.814038 5739 7f3f06ffd700 UTL  gitinfoOfInternal:       
07/16 22:12:05.814039 5739 7f3f06ffd700 UTL  buildinfo:              Built by root at 2020-07-08 09:41 
07/16 22:12:05.814040 5739 7f3f06ffd700 UTL  version:                1.6.6.1 
07/16 22:12:05.814042 5739 7f3f06ffd700 UTL  dataDir:                /var/lib/taos
07/16 22:12:05.814043 5739 7f3f06ffd700 UTL  os pageSize:            4096(KB)
07/16 22:12:05.814044 5739 7f3f06ffd700 UTL  os openMax:             1048576
07/16 22:12:05.814045 5739 7f3f06ffd700 UTL  os streamMax:           16
07/16 22:12:05.814046 5739 7f3f06ffd700 UTL  os numOfCores:          12
07/16 22:12:05.814046 5739 7f3f06ffd700 UTL  os totalDisk:           0.000000(GB)
07/16 22:12:05.814047 5739 7f3f06ffd700 UTL  os totalMemory:         15840(MB)
07/16 22:12:05.814049 5739 7f3f06ffd700 UTL  os sysname:             Linux
07/16 22:12:05.814050 5739 7f3f06ffd700 UTL  os nodename:            zhu-Lenovo-XiaoXinPro-13IML-2020
07/16 22:12:05.814052 5739 7f3f06ffd700 UTL  os release:             5.4.0-40-generic
07/16 22:12:05.814053 5739 7f3f06ffd700 UTL  os version:             #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020
07/16 22:12:05.814054 5739 7f3f06ffd700 UTL  os machine:             x86_64
07/16 22:12:05.814055 5739 7f3f06ffd700 UTL ==================================

**Comment by zhuqiyun** [comment]
> 请附上日志。

请帮忙看下  现在是想在项目中应用   使用golang连接本地ubuntu20.04的数据库

**Comment by Aries-Lee1991** [comment]
> > 请附上日志。
> 
> 请帮忙看下 现在是想在项目中应用 使用golang连接本地ubuntu20.04的数据库

好的，我们这边看一下。

**Comment by Aries-Lee1991** [comment]
> > 请附上日志。
> 
> 请帮忙看下 现在是想在项目中应用 使用golang连接本地ubuntu20.04的数据库

方便的话，你可以添加一下微信：tdengine，保持沟通。

**Comment by zhuqiyun** [comment]
> > > 请附上日志。
> > 
> > 
> > 请帮忙看下 现在是想在项目中应用 使用golang连接本地ubuntu20.04的数据库
> 
> 方便的话，你可以添加一下微信：tdengine，保持沟通。

这个是什么问题？怎么解决啊？

**Comment by zhuqiyun** [comment]
已解决，谢谢
