### ISSUE TITLE
python 或者 java 程序中可以实现 import 文件进行入库吗

### ISSUE THREAD

**Issue by wangzhanchi8** [taosdata/TDengine#2687]
conn = taos.connect(host="127.0.0.1", user="root", password="taosdata", config="/etc/taos")
c1 = conn.cursor()
 c1.execute("import into zhangji.test file '//TDengine//data//test.csv';")

sql语句，命令执行可以正常导入数据。在程序中执行，不报错，但数据也没导入进去

**Comment by Aries-Lee1991** [comment]
暂时不可以用这种方式。
