### ISSUE TITLE
when window query,  the returned time exceeds the specified query time range.

### ISSUE THREAD

**Issue by 14985745** [taosdata/TDengine#26897]
**Bug Description**
I am also experiencing the same issue. When the interval is greater than 2 hours, the returned time exceeds the specified query time range.

**Expected Behavior**
window query
When the interval is greater than 2 hours

**Screenshots**
<img width="1482" alt="image" src="https://github.com/user-attachments/assets/f56e2e84-574b-4e66-8997-f04c65819103">
<img width="1488" alt="image" src="https://github.com/user-attachments/assets/8f6b9171-58f7-4acb-a25a-a25b8f96e5fc">
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/12dc0613-cf13-45f8-913b-32eb10aa7603">

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - TDengine Version: 3.2.0.0

**Additional Context**

**Comment by yu285** [comment]
the window of interval  is not depended on your 'where ts' clause , but start from '1970-1-1 00:00:000 UTC '， that is why you can see '2024-07-29 15:00 xxxx'
