### ISSUE TITLE
数据库订阅无法获取tableName

### ISSUE THREAD

**Issue by TongleiSun** [taosdata/TDengine#26898]
<img width="841" alt="d558f4e1561a0e9710608ff135ea7f9" src="https://github.com/user-attachments/assets/85298dea-aaf9-494e-a101-198d6597067e">

**Comment by TongleiSun** [comment]
![image](https://github.com/user-attachments/assets/8d3b4c9b-c464-4593-b308-2bfea1609f56)

**Comment by TongleiSun** [comment]
![image](https://github.com/user-attachments/assets/06cce551-9aab-4a9f-873d-5eb0fd6f4885)

**Comment by yu285** [comment]
与https://github.com/taosdata/TDengine/issues/24297同，暂作关闭。

**Comment by wangmm0220** [comment]
![36ab9b6c-0c37-43a9-a07c-a6f0e93b3cfa](https://github.com/user-attachments/assets/c57144ff-4c3c-4548-9b76-8776286ed693)

**Comment by wangmm0220** [comment]
> ![image](https://private-user-images.githubusercontent.com/48509267/353711756-8d3b4c9b-c464-4593-b308-2bfea1609f56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjMzNTEsIm5iZiI6MTcyMjQyMzA1MSwicGF0aCI6Ii80ODUwOTI2Ny8zNTM3MTE3NTYtOGQzYjRjOWItYzQ2NC00NTkzLWIzMDgtMmJmZWExNjA5ZjU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEwNTA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwODk4OGIxNjRmZDZmZGMwNWZmYjMwMzllMDg2YzFiNzY1Mjk0OGQzZjc4ZDA2ZTA0ZmYzODNjN2JkMjRiMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pb4Emm96ZfzNC6-q07XbsoTkjT4cA1j3Lv7_bMj_cEc)

需要获取一条数据然后再获取表名，一次poll的结果可能包含很多表的数据，所以需要先fetch 数据，才能获取到表名

**Comment by TongleiSun** [comment]
![image](https://github.com/user-attachments/assets/561d87e0-fa3c-4f5b-ad91-4e470cdba89d)

我看连接器里已经fetchBlock了，还是没有获取到tableName

**Comment by TongleiSun** [comment]
用的java连接器 应该怎么去获取tableName呢？ 没找到方法

**Comment by sheyanjie-qq** [comment]
连接器目前不支持订阅数据库 with meta，请按照超级表 select 的方式订阅。
![image](https://github.com/user-attachments/assets/eadff9f8-6c7a-48e9-8d94-4461f604aea9)

**Comment by TongleiSun** [comment]
java连接器  数据库类型订阅会将元数据丢弃，只能订阅到数据，无法获取到tableName
