### ISSUE TITLE
集群版本申请试用

### ISSUE THREAD

**Issue by AlexForMRD** [taosdata/TDengine#269]
请问集群版本什么时候会推出, 我看到说是可以先申请, 不知道如何申请? 谢谢

**Comment by jtao1735** [comment]
请加微信tdengine，涛思数据会安排人对接

**Comment by gysan** [comment]
集群版都没有，还给我讲大数据

**Comment by hzcheng** [comment]
首先，不知道您从哪知道我们没有集群。我们有集群，只是没有开源而已。如果您指的是集群没开源，那么请参考问题#84。其次，我们从来没有跟**您**讲过大数据，谢谢！

**Comment by gysan** [comment]
既然不讲大数据，那还给Hadoop做什么对比啊，比Hadoop快10倍
