### ISSUE TITLE
如何编写涉及阶梯计价的sql语句

### ISSUE THREAD

**Issue by stormbirds** [taosdata/TDengine#26944]
我有一个电表，有字段ts和对应时间段内的电量kwh，现在有阶梯计价规则例如第一阶梯少于1000度为0.5元/度，大于1000少于3000为0.8元/度，大于3000以上为1元/度，使用tdengine怎么编写计算这种阶梯电价的sql语句

**Comment by stormbirds** [comment]
> SELECT ts, CASE WHEN kwh < 1000 THEN kwh * 0.5 WHEN kwh < 3000 THEN kwh*0.8 ELSE kwh END FROM meters
> 
> 随手写的，没验证

我可能没说清楚，电表的数据是每行一个时间戳列和电量，我需要计算的是电量累计总和在1000度以内的行使用0.5元每度计算成本，累计电量超过1000度少于3000度时的数据行使用0.8元每度计算成本，累计电量超过3000度以上为1元每度计算成本，其中电量列存储的当前时间戳与上一行数据时间戳时间范围内的电量
![image](https://github.com/user-attachments/assets/f1466012-30e6-4e9c-acab-4194aa6b5a5f)

**Comment by yu285** [comment]
select sum(value) from (select diff(val)  value  from super_table group by tbname) interval(1m) 试试这种
