### ISSUE TITLE
connect failed, reason: Invalid app version.

### ISSUE THREAD

**Issue by Songgexnl** [taosdata/TDengine#26967]
const taos = require("td2.0-connector");
var conn = taos.connect({
  host: "192.168.1.122",
  user: "root",
  password: "taosdata",
  db:"test",
  port: 6041,
});
var cursor = conn.cursor();
![image](https://github.com/user-attachments/assets/2b913481-4a93-467b-8364-b8914a3709d6)

**Comment by yu285** [comment]
应用所使用的动态库文件/客户端需要和服务端版本需要保持一致。
