### ISSUE TITLE
ERROR: Found data file(s) exists in .! Please use other place to dump out!

### ISSUE THREAD

**Issue by sexbee** [taosdata/TDengine#27053]
3.2.3.0 dump out  ---- > 3.3.2.0 dump in

========== arguments config =========
taosdump version: 3.3.2.0
git: 6d748239c188db3d2293ae31196ed7ed76a40f38
build: Linux-x64 2024-06-28 10:22:45 +0800
host: (null)
user: root
port: 0
outpath: 
inpath: 
resultFile: ./dump_result.txt
all_databases: false
databases: false
databasesSeq: (null)
schemaonly: false
with_property: true
avro codec: snappy
data_batch: 16383
thread_num: 8
allow_sys: false
escape_char: true
loose_mode: false
isDumpIn: false
arg_list_len: 8
arg_list[0]: –c
arg_list[1]: /etc/taos
arg_list[2]: –u
arg_list[3]: root
arg_list[4]: –p
arg_list[5]: taosdata
arg_list[6]: –i
arg_list[7]: /tmp/taos/taosdump.3445128444783
build: Linux-x64 2024-06-28 10:22:45 +0800
start time: 2024-08-07 08:40:05
**ERROR: 0 database(s) valid to dump**

==============and====================
========== arguments config =========
taosdump version: 3.3.2.0
git: 6d748239c188db3d2293ae31196ed7ed76a40f38
build: Linux-x64 2024-06-28 10:22:45 +0800
host: (null)
user: root
port: 6041
outpath: 
inpath: 
resultFile: ./dump_result.txt
all_databases: false
databases: false
databasesSeq: (null)
schemaonly: false
with_property: true
avro codec: snappy
data_batch: 16383
thread_num: 8
allow_sys: false
escape_char: true
loose_mode: false
isDumpIn: false
arg_list_len: 8
arg_list[0]: –c
arg_list[1]: /etc/taos
arg_list[2]: –u
arg_list[3]: root
arg_list[4]: –p
arg_list[5]: taosdata
arg_list[6]: –i
arg_list[7]: /tmp/taos/taosdump.3445128444783
build: Linux-x64 2024-06-28 10:22:45 +0800
start time: 2024-08-07 08:46:21
**ERROR: Found data file(s) exists in .! Please use other place to dump out!**
end time: 2024-08-07 08:46:21

**Comment by yu285** [comment]
更换或者清空该目录重新执行即可
