### ISSUE TITLE
issue when fetching data by Spark

### ISSUE THREAD

**Issue by Fantaseacheng** [taosdata/TDengine#27067]
通过Spark读取taos中的数据时，实际数据值被替换为列名。
```
            Dataset<Row> load = spark.read()
                    .format("jdbc")
                    .option("url", "jdbc:TAOS://")
                    .option("driver", "com.taosdata.jdbc.TSDBDriver")
                    .option("user", "root")
                    .option("password", "taosdata")
                    .option("query", "select device_id FROM db_history_data.t_freeze_data")
                    .load();

            load.show(false);
```
taos表中数据
![image](https://github.com/user-attachments/assets/be7717d7-382c-4221-b7d4-330cdd7e0cc5)

执行结果
![image](https://github.com/user-attachments/assets/3f28501a-25fa-4827-977f-e487b6c3b102)

taos jdbc版本：3.2.9
Spark版本：3.5.1
已参考技术文档：https://www.taosdata.com/tdengine-engineering/9165.html

**Comment by Fantaseacheng** [comment]
Spark读取mysql中的数据时正常，DataSource读取taos中的数据也正常，但Spark读取taos数据时出现上述问题

**Comment by yu285** [comment]
TDengine版本是？

**Comment by Fantaseacheng** [comment]
> TDengine版本是？

抱歉，切换到客户端对应的jdbc版本后解决了
