### ISSUE TITLE
 Business Consulting

### ISSUE THREAD

**Issue by zhuqiyun** [taosdata/TDengine#2712]
1、设备频繁上报数据，物联网平台，上报可能会高并发。
2、服务器收到数据后按照“数据模型”解析，完成后存入tdengine
3、“数据模型”开始存储在mysql中，但是mysql频繁读取效率低，不可取。
4、解决方案：1、将数据模型提前缓存到redis中，解析程序从redis中获取解析模板，2、数据模型直接在tdengine中建一个表，解析程序实时从tdengine中读取模型。
5、现在偏向于在tdengine中建模型表，这个业务场景适合吗？

**Comment by zhuqiyun** [comment]
能帮忙回答一下嘛

**Comment by Aries-Lee1991** [comment]
> 能帮忙回答一下嘛

您好，业务类问题，请发邮件到support@taosdata.com
