### ISSUE TITLE
CACHESIZE如何优化

### ISSUE THREAD

**Issue by zhuangQingGuang** [taosdata/TDengine#27138]
官网描述
如果 cacheload 非常接近 cachesize，则 cachesize 可能过小。 如果 cacheload 明显小于 cachesize 则 cachesize 是够用的。可以根据这个原则判断是否需要修改 cachesize 。具体修改值可以根据系统可用内存情况来决定是加倍或者是提高几倍。
然后我查询的我的参数  发现差距甚大
cachesize: 1
cacheload: 1048563

服务器配置4C 16G
我应该如何配置我的cachesize

**Comment by yu285** [comment]
有开缓存吗？ 需要开启缓存 cachemodel

**Comment by zhuangQingGuang** [comment]
> 有开缓存吗？ 需要开启缓存 cachemodel

有的  CACHEMODEL 'last_row'

**Comment by yu285** [comment]
可能需要具体看看你的环境了，加个微信 a15652223354 看一下吧。

**Comment by yu285** [comment]
cacheload的单位是字节，所以是视觉差异，我们也调整一下文档
