### ISSUE TITLE
failure, reason: invalid submit message

### ISSUE THREAD

**Issue by qq421379648** [taosdata/TDengine#2714]
**Bug Description**
使用API插入数据时,另一台机器 ptuuy 远程taosdata数据库机器，使用查询语句，若查询语句有错误，则有很大几率导致插入出错

 ,插入数据 ，每次199个数值

插入语句
insert into yxsj1(t,v,s) values(1537487903000,96.791,1),(1537487905000,94.341,1),(1537487909000,94.695,1),.....,(1537488503000,91.329,1); 

错误信息如下：
failure, reason: invalid submit message

putty 输入查询语句为

select max(t) as m from ysxj1;

**Screenshots**
![image](https://user-images.githubusercontent.com/34973636/87874256-ed644580-c9fa-11ea-8dea-d7f6eb4ee0e2.png)

**Environment (please complete the following information):**
 - OS: 插入数据服务器为  win2008 服务器 32G内存，使用c#+ taos.dll
taosdata为 ubuntu 18.04 64G 内存

 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by Aries-Lee1991** [comment]
您好，这个版本太老了，现在已经不维护了，麻烦您先升级一下，看是否还有这种问题。

**Comment by wxlevel** [comment]
> 您好，这个版本太老了，现在已经不维护了，麻烦您先升级一下，看是否还有这种问题。

你好，我安装的是1.6.6.2 的版本，然后安装了对应的window客户端，用里面的例子c#代码跑的， 也遇到这个问题

![image](https://user-images.githubusercontent.com/38063110/90471407-c2cbf080-e150-11ea-92d1-ccb33f64f21a.png)
![image](https://user-images.githubusercontent.com/38063110/90471435-d9724780-e150-11ea-8f60-9a466070f671.png)

**Comment by Aries-Lee1991** [comment]
> > 您好，这个版本太老了，现在已经不维护了，麻烦您先升级一下，看是否还有这种问题。
> 
> 你好，我安装的是1.6.6.2 的版本，然后安装了对应的window客户端，用里面的例子c#代码跑的， 也遇到这个问题
> 
> ![image](https://user-images.githubusercontent.com/38063110/90471407-c2cbf080-e150-11ea-92d1-ccb33f64f21a.png)
> ![image](https://user-images.githubusercontent.com/38063110/90471435-d9724780-e150-11ea-8f60-9a466070f671.png)

麻烦您升级成2.0吧，1.6版本已经逐渐不维护了~

**Comment by Aries-Lee1991** [comment]
问一下，您升级成2.0还存在这个问题吗？
