### ISSUE TITLE
无模式插入，表名有大写字母，会有问题

### ISSUE THREAD

**Issue by zhangtaozt3601** [taosdata/TDengine#27154]
涛思数据库版本：3.3.2.0。
我的无模式插入测试代码：
#include "taos.h"
#include <stdio.h>
#include <stdlib.h>
#include <sys/time.h>
#include <time.h>
#include <unistd.h>
#include <inttypes.h>
#include <string.h>

int main(int argc, char *argv[])
{
    TAOS_RES *result;
    const char *host = "127.0.0.1";
    const char *user = "root";
    const char *passwd = "taosdata";

    taos_options(TSDB_OPTION_TIMEZONE, "GMT-8");
    TAOS *taos = taos_connect(host, user, passwd, "ztdb", 0);
    if (taos == NULL)
    {
        printf("\033[31mfailed to connect to db, reason:%s\033[0m\n", taos_errstr(taos));
        exit(1);
    }

    time_t ct = time(NULL);
    int64_t ts = ct * 1000;

    char *lineFormat = "testdata,tname=%s,name=%s val=%ff32 %" PRId64;

    int lineNum = 10;
    char **lines = (char **)calloc(lineNum, sizeof(char *));

    int l = 0;
    for (int i = 0; i < lineNum; i++)
    {
        char *line = (char *)calloc(512, 1);
        char tname[512];
        sprintf(tname, "TEST_%d", i);
        snprintf(line, 512, lineFormat, tname, tname, 33.66, ts);
        lines[l] = line;
        ++l;
    }

    TAOS_RES *res = taos_schemaless_insert(taos, lines, lineNum, TSDB_SML_LINE_PROTOCOL, TSDB_SML_TIMESTAMP_MILLI_SECONDS);
    taos_free_result(res);

    return 0;
}
程序执行后，查询：
taos> show tables;
           table_name           |
=================================
 TEST_0                         |
 TEST_1                         |
 TEST_5                         |
 TEST_6                         |
 TEST_9                         |
 TEST_2                         |
 TEST_3                         |
 TEST_4                         |
 TEST_7                         |
 TEST_8                         |
Query OK, 10 row(s) in set (0.002933s)

taos> select * from TEST_0;

DB error: Fail to get table info, error: Table does not exist (0.000761s)
taos>

问题：为什么会报错？

**Comment by yu285** [comment]
select * from `TEST_0`;

即可，具体转义相关，请参考：

https://docs.taosdata.com/taos-sql/escape/

**Comment by zhangtaozt3601** [comment]
select * from TEST_0;这句报错，拜托仔细看。为什么会报错啊？

**Comment by anyedilong** [comment]
select * from TEST_0; 这样写的话实际执行的是select * from test_0;
