### ISSUE TITLE
增加字段报错: Row length exceeds max length 49151

### ISSUE THREAD

**Issue by LoveScotty** [taosdata/TDengine#27166]
我加了一个超级表，然后我新增field的时候，增加到327后，再加就提示Row length exceeds max length 49151，我的表结构如下：
desc product_D3rxrtnTrY_telemetry;
             field              |         type         |   length    |   note   |
=================================================================================
 ts                             | TIMESTAMP            |           8 |          |
 rowdata                        | NCHAR                |         255 |          |
 dspb1chpnpa                    | FLOAT                |           4 |          |
 dspb2chpnpa                    | FLOAT                |           4 |          |
 dspa1chpnpa                    | FLOAT                |           4 |          |
 dspa21chpnpa                   | FLOAT                |           4 |          |
 dspb4chpnpa                    | FLOAT                |           4 |          |
 dspa4chpnpa                    | FLOAT                |           4 |          |
 dspa22chpnpa                   | FLOAT                |           4 |          |
 b1nowtemp17                    | FLOAT                |           4 |          |
 b2nowtemp18                    | FLOAT                |           4 |          |
 a1nowtemp19                    | FLOAT                |           4 |          |
 a21nowtemp110                  | FLOAT                |           4 |          |
 b4nowtemp111                   | FLOAT                |           4 |          |
 a22nowtemp113                  | FLOAT                |           4 |          |
 de                             | FLOAT                |           4 |          |
 dw                             | FLOAT                |           4 |          |
 dp                             | FLOAT                |           4 |          |
 averchrt                       | FLOAT                |           4 |          |
 dspflow                        | FLOAT                |           4 |          |
 cwp1250ia                      | FLOAT                |           4 |          |
 cwp1250ib                      | FLOAT                |           4 |          |
 cwp1250ic                      | FLOAT                |           4 |          |
 cwp1250uab                     | FLOAT                |           4 |          |
 cwp1250ubc                     | FLOAT                |           4 |          |
 cwp1250uca                     | FLOAT                |           4 |          |
 cwp1250pt                      | FLOAT                |           4 |          |
 cwp1250xskwh                   | FLOAT                |           4 |          |
 chp1250ia                      | FLOAT                |           4 |          |
 chp1250ib                      | FLOAT                |           4 |          |
 chp1250ic                      | FLOAT                |           4 |          |
 chp1250uab                     | FLOAT                |           4 |          |
 chp1250ubc                     | FLOAT                |           4 |          |
 chp1250uca                     | FLOAT                |           4 |          |
 chp1250pt                      | FLOAT                |           4 |          |
 chp1250xskwh                   | FLOAT                |           4 |          |
 ct11ia                         | FLOAT                |           4 |          |
 ct11ib                         | FLOAT                |           4 |          |
 ct11ic                         | FLOAT                |           4 |          |
 ct11uab                        | FLOAT                |           4 |          |
 ct11ubc                        | FLOAT                |           4 |          |
 ct11uca                        | FLOAT                |           4 |          |
 ct11pt                         | FLOAT                |           4 |          |
 ct11xskwh                      | FLOAT                |           4 |          |
 ct12ia                         | FLOAT                |           4 |          |
 ct12ib                         | FLOAT                |           4 |          |
 ct12ic                         | FLOAT                |           4 |          |
 ct12uab                        | FLOAT                |           4 |          |
 ct12ubc                        | FLOAT                |           4 |          |
 ct12uca                        | FLOAT                |           4 |          |
 ct12pt                         | FLOAT                |           4 |          |
 ct12xskwh                      | FLOAT                |           4 |          |
 ct13ia                         | FLOAT                |           4 |          |
 ct13ib                         | FLOAT                |           4 |          |
 ct13ic                         | FLOAT                |           4 |          |
 ct13uab                        | FLOAT                |           4 |          |
 ct13ubc                        | FLOAT                |           4 |          |
 ct13uca                        | FLOAT                |           4 |          |
 ct13pt                         | FLOAT                |           4 |          |
 ct13xskwh                      | FLOAT                |           4 |          |
 ct14ia                         | FLOAT                |           4 |          |
 ct14ib                         | FLOAT                |           4 |          |
 ct14ic                         | FLOAT                |           4 |          |
 ct14uab                        | FLOAT                |           4 |          |
 ct14ubc                        | FLOAT                |           4 |          |
 ct14uca                        | FLOAT                |           4 |          |
 ct14pt                         | FLOAT                |           4 |          |
 ct14xskwh                      | FLOAT                |           4 |          |
 a27chpia                       | FLOAT                |           4 |          |
 a27chpib                       | FLOAT                |           4 |          |
 a27chpic                       | FLOAT                |           4 |          |
 a27chpuab                      | FLOAT                |           4 |          |
 a27chpubc                      | FLOAT                |           4 |          |
 a27chpuca                      | FLOAT                |           4 |          |
 a27chppt                       | FLOAT                |           4 |          |
 a27chpxskwh                    | FLOAT                |           4 |          |
 a24chpia                       | FLOAT                |           4 |          |
 a24chpib                       | FLOAT                |           4 |          |
 a24chpic                       | FLOAT                |           4 |          |
 a24chpuab                      | FLOAT                |           4 |          |
 a24chpubc                      | FLOAT                |           4 |          |
 a24chpuca                      | FLOAT                |           4 |          |
 a24chppt                       | FLOAT                |           4 |          |
 a24chpxskwh                    | FLOAT                |           4 |          |
 cwp1100ia                      | FLOAT                |           4 |          |
 cwp1100ib                      | FLOAT                |           4 |          |
 cwp1100ic                      | FLOAT                |           4 |          |
 cwp1100uab                     | FLOAT                |           4 |          |
 cwp1100ubc                     | FLOAT                |           4 |          |
 cwp1100uca                     | FLOAT                |           4 |          |
 cwp1100pt                      | FLOAT                |           4 |          |
 cwp1100xskwh                   | FLOAT                |           4 |          |
 chp1100ia                      | FLOAT                |           4 |          |
 chp1100ib                      | FLOAT                |           4 |          |
 chp1100ic                      | FLOAT                |           4 |          |
 chp1100uab                     | FLOAT                |           4 |          |
 chp1100ubc                     | FLOAT                |           4 |          |
 chp1100uca                     | FLOAT                |           4 |          |
 chp1100pt                      | FLOAT                |           4 |          |
 chp1100xskwh                   | FLOAT                |           4 |          |

 Notice: The result shows only the first 100 rows.
         You can use the `LIMIT` clause to get fewer result to show.
           Or use '>>' to redirect the whole set of the result to a specified file.

         You can use Ctrl+C to stop the underway fetching.

Query OK, 329 row(s) in set (0.003062s)

**Comment by LoveScotty** [comment]
版本为：3.0.4.2

**Comment by yu285** [comment]
麻烦提供一下具体的sql语句。我们在新版本验证无误的话，麻烦您那边也做一下升级。

**Comment by yu285** [comment]
提供后 再做reopen处理
