### ISSUE TITLE
 Is it possible to modify the table column name

### ISSUE THREAD

**Issue by lei-q** [taosdata/TDengine#2717]
Dear taos，
   我们正在使用taosdb动态建立超级表的功能，在我们项目中，创建的表，随着业务的迭代，表中字段会发生变更，能否提供修改表列名的功能，类似于mysql中的 
             修改列名：alter table 表名 change 原列名 新列名 int;
             修改列属性：alter table 表名 modify 原列名 varchar(22);

这个功能对我们很重要，希望能评估一下。或者告知一下其他替代方案，多谢！
        
祝taosdb越来越强大！！！

**Comment by Aries-Lee1991** [comment]
您好，功能的评估，请联系 support@taosdata.com。

**Comment by lei-q** [comment]
> 
> 
> 您好，功能的评估，请联系 [support@taosdata.com](mailto:support@taosdata.com)。

好的
