### ISSUE TITLE
No response from last_row(*)

### ISSUE THREAD

**Issue by kinghtdom** [taosdata/TDengine#2719]
**Bug Description**
用last_row查询最近的一条记录时，没有数据返回
taos> select last_row(*) from tab_jf1;
Query OK, 0 row(s) in set (0.001926s)

主要用taos存储传感器的数据，存储频率是5条/秒。每5秒读取一次数据库中的最新数据。当数据库重启后，last_row()可以读取到最新数据，但是过了几天后，实时数据又无法读取。但是，用select * from tab_jf1 where dt>=NOW-1m and dt<now;依然可以读到最近1分钟的数据。

**Screenshots**
![image](https://user-images.githubusercontent.com/8519670/87902621-b3dc1a80-ca8c-11ea-8408-7e32fe3320b2.png)

**Environment (please complete the following information):**
 - OS: UOS 20SP1
 - Memory: 64G, CPU: 龙芯, current Disk Space: 800G
 - TDengine Version 2.0

**Comment by Aries-Lee1991** [comment]
您好，2.0还没有官方发布，正在修复bug中，您的bug我会反馈给研发，什么时候能上线使用，还请多关注我们官方通知。

**Comment by yihaoDeng** [comment]
> **Bug Description**
> 用last_row查询最近的一条记录时，没有数据返回
> taos> select last_row(*) from tab_jf1;
> Query OK, 0 row(s) in set (0.001926s)
> 
> 主要用taos存储传感器的数据，存储频率是5条/秒。每5秒读取一次数据库中的最新数据。当数据库重启后，last_row()可以读取到最新数据，但是过了几天后，实时数据又无法读取。但是，用select * from tab_jf1 where dt>=NOW-1m and dt<now;依然可以读到最近1分钟的数据。
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/8519670/87902621-b3dc1a80-ca8c-11ea-8408-7e32fe3320b2.png)
> 
> **Environment (please complete the following information):**
> 
> * OS: UOS 20SP1
> * Memory: 64G, CPU: 龙芯, current Disk Space: 800G
> * TDengine Version 2.0

1.

**Comment by yihaoDeng** [comment]
> **Bug Description**
> 用last_row查询最近的一条记录时，没有数据返回
> taos> select last_row(*) from tab_jf1;
> Query OK, 0 row(s) in set (0.001926s)
> 
> 主要用taos存储传感器的数据，存储频率是5条/秒。每5秒读取一次数据库中的最新数据。当数据库重启后，last_row()可以读取到最新数据，但是过了几天后，实时数据又无法读取。但是，用select * from tab_jf1 where dt>=NOW-1m and dt<now;依然可以读到最近1分钟的数据。
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/8519670/87902621-b3dc1a80-ca8c-11ea-8408-7e32fe3320b2.png)
> 
> **Environment (please complete the following information):**
> 
> * OS: UOS 20SP1
> * Memory: 64G, CPU: 龙芯, current Disk Space: 800G
> * TDengine Version 2.0

你可以试试我们最新的版本，我在当前这个版本上并没有模拟出这个问题,  不管是超级表还是普通表， 之后你有问题的话， 可以描述的稍微详细一些， 比如是针对超级表的查询还是普通表， 还有代码的commit id, 这样也方便我们快速定位， 谢谢
