### ISSUE TITLE
ERROR UTL can't get locale from system Invalid locale

### ISSUE THREAD

**Issue by ArgoZhang** [taosdata/TDengine#272]
```log
[root@VM_34_63_centos ~]# taos
08/04 11:11:40.586769 7f34ffc16740 ERROR UTL can't get locale from system
Invalid locale:, please set the valid locale in config file[root@VM_34_63_centos ~]#
```
这个问题怎么解决呢？

**Comment by lhyfree** [comment]
centos7 和 Ubuntu16 同样的报错

**Comment by hzcheng** [comment]
Please add the following line in your config file: /etc/taos/taos.cfg

```
charset utf-8
```

**Comment by lhyfree** [comment]
加 charset utf-8  无效。

而且我看默认配置有相关配置:
# system locale
# locale                en_US.UTF-8

# default system charset
# charset               UTF-8

**Comment by hzcheng** [comment]
这些选项前面的注释符号’#’都去了是吗？可不可以将您的配置文件贴一份

**Comment by lhyfree** [comment]
我只加了一行：
charset utf-8

其他都是默认带#的配置。

**Comment by hzcheng** [comment]
您可以在您的机器的shell中运行下
```
locale
```
然后发下输出

**Comment by lhyfree** [comment]
root@taos:/etc/taos# locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=zh_CN.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by hzcheng** [comment]
您可以尝试在/etc/taos/taos.cfg中加上
locale en_US.UTF-8
charset UTF-8
再尝试下

**Comment by lhyfree** [comment]
可以了。
