### ISSUE TITLE
下载最新版本3.3.2.0安装后taosd启动不了

### ISSUE THREAD

**Issue by xiaobaxiang** [taosdata/TDengine#27215]
**Bug Description**

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

查看 /var/log/taos/taosdlog.0 日志中报这几个文件找不到。
08/14 14:13:26.270878 01014576 C DND dnode file:/var/lib/taos//dnode/dnode.json not exist
08/14 14:13:26.270906 01014576 C DND mnode file:/var/lib/taos//mnode/mnode.json not exist
08/14 14:13:26.270912 01014576 C DND file:/var/lib/taos//qnode/qnode.json not exist
08/14 14:13:26.270915 01014576 C DND file:/var/lib/taos//snode/snode.json not exist

查看/var/lib/taos/目录下面是空的

**Comment by xiaobaxiang** [comment]
Alibaba Cloud Linux 3.2104 LTS 64位 操作系统

**Comment by niufwshd** [comment]
我是用docker安装的，借助daocloud镜像源
doctor pull m.daocloud.com/docker.io/tdengine:tdengine
