### ISSUE TITLE
taosd crash

### ISSUE THREAD

**Issue by elysian-gc** [taosdata/TDengine#27287]
**Bug Description**
taosd crash 

**To Reproduce**
don't know

**Expected Behavior**
no crash

**Screenshots**
![image](https://github.com/user-attachments/assets/825bb6fb-fc55-4693-a484-3e8d19d20a78)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.4 LTS
 - Memory, CPU, current Disk Space: 2c8g * 6
 - TDengine Version：
 ```
root@ip-10-2-4-244:/var/lib/apport/coredump# taosd -V
community version: 3.3.0.0 compatible_version: 3.0.0.0
gitinfo: eb6094f92fd73395a286d294f5aaa316c6a0c91e
buildInfo: Built Linux-arm64 at 2024-05-15 17:36:07 +0800
```

**Additional Context**

**Comment by yu285** [comment]
we will check this ,thanks for your feedback

**Comment by yu285** [comment]
this is my wechat : a15652223354 , we can check this issue together .

**Comment by yu285** [comment]
or you can compile TDengine  main branch to get newest code to see whether this issue resolved .

since no respond ,close it temporary
