### ISSUE TITLE
too many authentication failed,try 10 minutes later

### ISSUE THREAD

**Issue by gaosong1206** [taosdata/TDengine#2730]
**Bug Description**
使用函数 TAOS *taos_connect(char *ip, char *user, char *pass, char *db, int port)与数据库进行连接，分别进行如下设置测试：
仅IP地址错误
仅用户名错误
仅密码错误
仅数据库名称错误
仅端口号错误
连接信息全部正确

连续六次taos_connect 函数，分别对应上述信息，执行完成后在终端输入taos，终端报错：
too many authentication failed,try 10 minutes later

**Comment by Aries-Lee1991** [comment]
这种问题属于认证类的问题，请联系 support@taosdata.com
