### ISSUE TITLE
The return value of taos_connect is error.

### ISSUE THREAD

**Issue by gaosong1206** [taosdata/TDengine#2731]
使用taos_connect函数进行数据库连接，调用方法如下：

taos = taos_connect(“192.168.4.555”, "root", "taosdata", NULL, 0);
  if (taos == NULL) {
    printf("failed to connect to server, reason:%s\n", taos_errstr(taos));
    exit(1);
  }
  printf("success to connect to server\n");

int code = taos_errno(taos)// code的值为0

string errorMsg = taos_errstr(taos) // errorMsg的内容为success
其中192.168.4.555是一个根本不存在的ip地址，连接应该失败，返回空指针才对

**Comment by Aries-Lee1991** [comment]
建议还是正常操作。
