### ISSUE TITLE
taos-jdbcdriver在用HikariCP和Druid连接池导致内存和本地端口占用暴增

### ISSUE THREAD

**Issue by jlchengithub** [taosdata/TDengine#27336]
**问题描述** 
程序中用HikariCP和Druid连接池通过taos-jdbcdriver驱动链接TDengine服务，如客户端与服务端网络长时间（几分钟）断开，导致应用程序内存暴涨（短时间内就能达到上百G），在网络恢复后，应用程序本地端口占用也暴涨。

**测试环境** 
jdk：17/21
taos-jdbcdriver：3.3.0
HikariCP：5.0.1
Druid：1.2.23
操作系统：macOS/Windows11

**截图-正常情况**
![image](https://github.com/user-attachments/assets/4c737713-00a2-40a9-ab6b-76417f0704af)
<img width="317" alt="image" src="https://github.com/user-attachments/assets/6a407ee7-b1ce-45bd-b874-8a99daf662d8">

**截图-异常情况**
![image](https://github.com/user-attachments/assets/be2500df-4d7d-4776-8bdd-0af05eafbcc8)
<img width="318" alt="image" src="https://github.com/user-attachments/assets/ff770ede-3455-4b8d-b25b-8ab376a03d56">
恢复网络后执行 netstat -nat|grep -i "6030"|wc -l 本地端口占用了好几千
![image](https://github.com/user-attachments/assets/8eecaf31-e1e4-499c-8ff5-f689f773900a)

**测试代码**
测试代码就是用的官网代码，注释了关闭连接池。
<img width="977" alt="image" src="https://github.com/user-attachments/assets/d1c2367b-083a-43a1-9a76-0ad334535f78">

**Comment by yu285** [comment]
同 #26680  目前正在处理，修复后会通知大家

**Comment by yu285** [comment]
可以升级到 3.3.3.0 ，问题已经解决。
