### ISSUE TITLE
batch size too big

### ISSUE THREAD

**Issue by gaosong1206** [taosdata/TDengine#2734]
调用涛思的taos_errstr接口，返回值为batch size too big

建库语句为：create database if not exists db tables 20000 cache 1024 ablocks 4 tblocks 50

超级表语句：create table devices (ts timestamp,testbinary binary(255), testNchar nchar(255), temperature int, humidity float) tags(devid int, devname binary(20),devgroup int)

普通表语句：create table dev1 if not exists using devices tags(1,'dev_1',1)

sql语句：insert into dev1 (ts,temperature, humidity) values ('2019-05-13 00:21:50.000',1,2.3000)

执行完后报错：batch size too big

超级表更改为语句：create table devices (ts timestamp,testbinary binary(20), testNchar nchar(20), temperature int, humidity float) tags(devid int, devname binary(20),devgroup int)
sql语句可以正常执行

please tell me the reason

server version:1.6.6.0

**Comment by Aries-Lee1991** [comment]
请先升级版本吧，1.6.1.7，官方已经不再维护了。

**Comment by Aries-Lee1991** [comment]
您要做这种测试的话，还是直接测2.0吧，develop分支下载。

**Comment by gaosong1206** [comment]
我提交issue忘记删除下面的示例了，我用的版本是1.6.6.0

**Comment by gaosong1206** [comment]
> 您要做这种测试的话，还是直接测2.0吧，develop分支下载。

我试试吧

**Comment by gaosong1206** [comment]
> 请先升级版本吧，1.6.1.7，官方已经不再维护了。

我提交issue忘记删除下面的示例了，我用的版本是1.6.6.0

**Comment by Aries-Lee1991** [comment]
> > 请先升级版本吧，1.6.1.7，官方已经不再维护了。
> 
> 我提交issue忘记删除下面的示例了，我用的版本是1.6.6.0

1.6.6.1版本我们这边进行了复现，不存在您这个问题。您还是测2.0吧。
