### ISSUE TITLE
数据删除失败，delete data failed

### ISSUE THREAD

**Issue by Fugitive844** [taosdata/TDengine#27346]
执行类似delte from tablename where ts<'2024-08-20 00:00:00'之后，数据无法删除成功，刚刚删除完成的时候查询的确没了，过一会被删除的数据自动恢复。
数据库一直在高频写入数据中，TDengine版本3.3.2.0稳定复现，docker部署。
现象同另一个[delete data failed](https://github.com/taosdata/TDengine/issues/26046)

![1724205044760](https://github.com/user-attachments/assets/baa9204b-03de-483e-b26b-afc746267e11)
![51fc4b5bb4fcf5709ff97832345e2bb](https://github.com/user-attachments/assets/0b83d431-1fa8-4c14-939b-d29abfb61446)

**Comment by yu285** [comment]
这个问题已经在处理，感谢反馈

**Comment by yu285** [comment]
该问题已经修复，可以拉取main分支最新代码验证此问题。

**Comment by wyzzzl** [comment]
在不升级的情况下，是否有办法解决这个问题？

**Comment by wyzzzl** [comment]
发现不升级的情况下，删两次就可以删成功了。

**Comment by zpnvliba** [comment]
> 发现不升级的情况下，删两次就可以删成功了。

大佬用的那个版本，你说的删除两次是指，第一次删除以后，第二次出现再删除，还是一次删除两次啊

**Comment by wyzzzl** [comment]
我用的是 TDengine-server-3.3.2.0-Linux-x64，
我说删除两次是指：第一次删除以后，隔了2天，发现被删的数据又出来了，然后进行第二次删除，就再没出现了。
