### ISSUE TITLE
 Query the STable in reverse order based on time, without specifying the time range, some data cannot be queried

### ISSUE THREAD

**Issue by w858269620** [taosdata/TDengine#2736]
**Bug Description**
查询超级表根据时间倒序，不指定时间范围，无法查询到数据

**To Reproduce**
1. 直接查询超级表，不指定时间范围，只查到了2016年和2020、2019年的数据
![image](https://user-images.githubusercontent.com/28639191/88130114-4fe06000-cc0c-11ea-8af3-249b00d27bc3.png)

2. 直接查询超级表，指定时间范围，查到了2017年的数据
![image](https://user-images.githubusercontent.com/28639191/88130175-6d152e80-cc0c-11ea-9fbd-63d4b4fdbe33.png)

3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS:  CentOS 7.0
 - Memory：40, CPU：128, current Disk Space：1.8T
 - TDengine Version 1.6.5.5

**Additional Context**

**Comment by Aries-Lee1991** [comment]
版本先升级一下吧，1.6.5.5已经不维护了。

**Comment by Aries-Lee1991** [comment]
您好，看样子已经过去了一个多月，想问下，您升级版本后，还会有这个问题吗？
