### ISSUE TITLE
最新3.3.2.0版本子查询窗口查询报错（3.x旧版本没报错）

### ISSUE THREAD

**Issue by peterchenhdu** [taosdata/TDengine#27362]
**Bug Description**
最新3.3.2.0版本子查询窗口查询报错（3.x旧版本没报错）

**To Reproduce**
执行以下语句报错：DB error: Window query not supported, since not valid primary timestamp column as input (0.000552s)

SELECT MIN( tag_value ) AS min_tag_value, tag_name  FROM (SELECT _rowts, * FROM `ptest4`.`ptbtest4` WHERE time > 1716520258085 AND time < 1717171199000 UNION ALL SELECT _rowts,* FROM ptest4_his.ptbtest4_his WHERE time > 1716048000000 AND time < 1716520258085 ) PARTITION BY tag_name INTERVAL ( 36000000a );

**Expected Behavior**
正确执行

**Screenshots**
![image](https://github.com/user-attachments/assets/2ba0f802-57e8-4ea5-8f90-02d7688efad0)

**Environment (please complete the following information):**
 - TDengine Version [3.3.2.0]

**Comment by yu285** [comment]
请问旧版本指的是哪个版本？

**Comment by yu285** [comment]
更新到3.3.3.0版本，如果还有问题可以微信联系a15652223354
