### ISSUE TITLE
请问如何备份topic ,用dump备份数据库还原时候发现topic都不存在

### ISSUE THREAD

**Issue by niufwshd** [taosdata/TDengine#27366]
**General Questions**
1. tdengine 3.3.0  使用taosdump -D wristbrand -o  ./tdengine 执行备份
2. 在另外一台服务器上执行 taosdump -D wristbrand -i ./tdengine 还原 ，查询数据是存在的，但是原来的topic都不存在了。
3 请问是不是我taosdump命令使用的问题还是taosdump不支持，有什么解决方式么，谢谢大侠。

**Comment by yu285** [comment]
taos> select * from information_schema.ins_topics\G;


可以通过这样在原库把 topic复制出来
