### ISSUE TITLE
Failed to establish a new connection

### ISSUE THREAD

**Issue by 1638896469** [taosdata/TDengine#2738]
server: 1.6.6.0
client:  1.6.6.0
互相能ping通，且端口已打开

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /taosdevops/dev-ops-now-bios/tree/master/team-members (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001B1A2020240>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有 正确答复或连接的主机没有反应，连接尝试失败。',))

log：
                new log file                      
==================================================
07/22 11:19:12.534000 0x7416 UTL timezone not configured, use default
07/22 11:19:12.545000 0x7416 UTL locale not configured, set to default:Chinese_China.936
07/22 11:19:12.545000 0x7416 UTL charset not configured, set to default:cp936
07/22 11:19:12.545000 0x7416 UTL    taos config & system info:
07/22 11:19:12.545000 0x7416 UTL ==================================
07/22 11:19:12.545000 0x7416 UTL  masterIp:               192.168.79.1 
07/22 11:19:12.545000 0x7416 UTL  localIp:                0.0.0.0 
07/22 11:19:12.545000 0x7416 UTL  mgmtShellPort:          6030 
07/22 11:19:12.545000 0x7416 UTL  vnodeShellPort:         6035 
07/22 11:19:12.545000 0x7416 UTL  configDir:              C:/TDengine/cfg 
07/22 11:19:12.545000 0x7416 UTL  logDir:                 C:/TDengine/log 
07/22 11:19:12.545000 0x7416 UTL  scriptDir:              C:/TDengine/script 
07/22 11:19:12.545000 0x7416 UTL  numOfThreadsPerCore:    1.000000 
07/22 11:19:12.545000 0x7416 UTL  affectedRowsMod:        0 
07/22 11:19:12.545000 0x7416 UTL  rpcTimer:               300(ms)
07/22 11:19:12.545000 0x7416 UTL  rpcMaxTime:             600(s)
07/22 11:19:12.545000 0x7416 UTL  shellActivityTimer:     3(s)
07/22 11:19:12.545000 0x7416 UTL  meterMetaKeepTimer:     7200(s)
07/22 11:19:12.545000 0x7416 UTL  metricMetaKeepTimer:    600(s)
07/22 11:19:12.545000 0x7416 UTL  defaultDB:               
07/22 11:19:12.545000 0x7416 UTL  defaultUser:            root 
07/22 11:19:12.545000 0x7416 UTL  sockettype:             udp 
07/22 11:19:12.545000 0x7416 UTL  compressMsgSize:        -1 
07/22 11:19:12.545000 0x7416 UTL  maxSQLLength:           65380(byte)
07/22 11:19:12.545000 0x7416 UTL  maxAuthRetryTime:       5(byte)
07/22 11:19:12.545000 0x7416 UTL  maxNumOfOrderedRes:     100000 
07/22 11:19:12.545000 0x7416 UTL  timezone:               not configured 
07/22 11:19:12.545000 0x7416 UTL  locale:                 Chinese_China.936 
07/22 11:19:12.545000 0x7416 UTL  charset:                cp936 
07/22 11:19:12.545000 0x7416 UTL  numOfLogLines:          10000000 
07/22 11:19:12.545000 0x7416 UTL  asyncLog:               1 
07/22 11:19:12.545000 0x7416 UTL  debugFlag:              131 
07/22 11:19:12.545000 0x7416 UTL  rpcDebugFlag:           131 
07/22 11:19:12.545000 0x7416 UTL  tmrDebugFlag:           131 
07/22 11:19:12.545000 0x7416 UTL  cDebugFlag:             131 
07/22 11:19:12.545000 0x7416 UTL  jniDebugFlag:           131 
07/22 11:19:12.545000 0x7416 UTL  odbcDebugFlag:          131 
07/22 11:19:12.545000 0x7416 UTL  uDebugFlag:             131 
07/22 11:19:12.545000 0x7416 UTL  qDebugFlag:             131 
07/22 11:19:12.545000 0x7416 UTL  gitinfo:                e69e95a4a9c771140bff568217874e66bf1f6c57 
07/22 11:19:12.545000 0x7416 UTL  gitinfoOfInternal:      a0339e1311c1f626de8c7d8efa51ef026c98ce86 
07/22 11:19:12.545000 0x7416 UTL  buildinfo:              Built by root at 2020-06-11 10:38 
07/22 11:19:12.545000 0x7416 UTL  version:                1.6.6.0 
07/22 11:19:12.545000 0x7416 UTL  dataDir:                C:/TDengine/data
07/22 11:19:12.545000 0x7416 UTL ==================================
07/22 11:19:48.642000 0x224 ERROR TSC 000001EABF404CA0 reach the max retry:8, code:29

**Comment by liuyq-617** [comment]
检查一下，TCP/UDP:6030-6039的端口是否正常

**Comment by liuyq-617** [comment]
服务端IP不能发生变化，如果修改，需要重新安装或者使用我们的迁移服务
