### ISSUE TITLE
TaosKeeper Prometheus Dashboard for 3.x监控模版部分显示异常

### ISSUE THREAD

**Issue by jandison** [taosdata/TDengine#27388]
tdengine server 3.3.2.0
采用官网推荐的18587模版，以及grafana上的TaosKeeper Prometheus Dashboard for 3.x模版均存在显示异常或无显示的情况

uptime，current cpu usage of taosd 和实际情况不符。
![image](https://github.com/user-attachments/assets/f573a4b4-9151-45bc-ae77-f57356c4b0b4)
无数据
![image](https://github.com/user-attachments/assets/b105301c-5513-4980-a482-a8f19215f4db)
![image](https://github.com/user-attachments/assets/b8b25c34-19f7-4fef-9002-ffdc9055d63e)

**Comment by yu285** [comment]
重新导入一下看看，不应该出现这样的情况
