### ISSUE TITLE
 Taos crashes when java application inserts data

### ISSUE THREAD

**Issue by easykoala** [taosdata/TDengine#2742]
**Bug Description**
java: /home/ubuntu/version_release_workroom/release_workspace/TDinternal/community/src/client/src/tscParseInsert.c:1494: tscProcessMultiVnodesInsert: Assertion `pMeterMetaInfo->vnodeIndex >= 1 && pCmd->pDataBlocks != NULL' failed.

/home/ubuntu目录根本不存在

**Environment (please complete the following information):**
 - OS: ubuntu 18
 - Memory, CPU, current Disk Space
 - TDengine Version 1.6.6.1

**Comment by Aries-Lee1991** [comment]
@easykoala 请描述详细一点，麻烦把你的操作步骤复现一下。

**Comment by easykoala** [comment]
create table if not exists logtbl (ts timestamp, level BINARY(10), loggerName BINARY(100), message NCHAR(255), thrown  BINARY(255));

这是java代码
            String sql = String.format("insert into %s values(now, ?, ?, ?, ?)", table);
            PreparedStatement statement = connection.prepareStatement(sql);
            Object[] params = new Object[]{body.getString("level"), body.getString("loggerName"), body.getString("message"), thrown == null ? "" : thrown.encode()};
            for (int i = 0; i < params.length; i++) {
                statement.setObject(i + 1, params[i]);
            }
            statement.executeUpdate(sql);
开始插入5条数据是ok的，查询也ok。后面在插入3条同样的数据就报错了：
java: /home/ubuntu/version_release_workroom/release_workspace/TDinternal/community/src/client/src/tscParseInsert.c:1494: tscProcessMultiVnodesInsert: Assertion `pMeterMetaInfo->vnodeIndex >= 1 && pCmd->pDataBlocks != NULL' failed.

taos崩溃了，java应用也奔溃了，重新启动taos可以查询，就是不能插入
尝试删除数据库和表还是不能插入

**Comment by easykoala** [comment]
补充：
原来java代码：
            Statement statement = connection.createStatement();
            String sql = String.format("insert into %s values(now, \"%s\", \"%s\", \"%s\", \"%s\")", table, body.getString("level"), body.getString("loggerName"), body.getString("message"), thrown == null ? "" : thrown.encode());
            statement.executeUpdate(sql);
这个可以正常执行，换成prepareStatement报错了，估计是jdbc的问题，用的是1.0.3版本

**Comment by zyyang-taosdata** [comment]
use taos-jdbcdriver-2.0.4 and try again.

**Comment by zyyang-taosdata** [comment]
this issue is closed by the assignees
