### ISSUE TITLE
使用docker部署好后使用java端连接提示版本不对

### ISSUE THREAD

**Issue by ixiami1314** [taosdata/TDengine#2743]
maven配置使用的是以下官网最新配置
            <dependency>
                <groupId>com.taosdata.jdbc</groupId>
                <artifactId>taos-jdbcdriver</artifactId>
                <version>1.0.3</version>
            </dependency>
            <dependency>
                <groupId>com.zaxxer</groupId>
                <artifactId>HikariCP</artifactId>
                <version>3.4.1</version>
            </dependency>

docker 使用的就是指定版本 1.6.5.9

**Comment by easykoala** [comment]
尝试不要在docker下运行，试试看

**Comment by ixiami1314** [comment]
不用docker，直接安装在本地是可以连上的。
