### ISSUE TITLE
jdbc  method nullsAreSortedAtStart and nullsAreSortedAtEnd both return false

### ISSUE THREAD

**Issue by taojin0505** [taosdata/TDengine#2746]
**Bug Description**
When we used apache calcite  JdbcSchema query on TDengine,it could not get metadata ,because of TDengine jdbc  driver method nullsAreSortedAtStart and nullsAreSortedAtEnd  in ``TDengine/src/connector/jdbc/src/main/java/com/taosdata/jdbc/TSDBDatabaseMetaData.java`` both return false.
**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]
 master branch
**Additional Context**

**Comment by Aries-Lee1991** [comment]
@taojin0505 版本是1.6.1.7？您目前告诉的信息不完整，不利于我们重现。请附上环境信息、操作步骤。我们再看。

**Comment by taojin0505** [comment]
@Aries-Lee1991  jdbc version：taos-jdbcdriver：1.0.3

**Comment by Aries-Lee1991** [comment]
> @Aries-Lee1991 jdbc version：taos-jdbcdriver：1.0.3

请列出具体操作步骤，您这么说，我们研发这边是无法复现出来的。

**Comment by Aries-Lee1991** [comment]
> @Aries-Lee1991 jdbc version：taos-jdbcdriver：1.0.3

TDengine版本也没写，是1.6.1.7吗？

**Comment by taojin0505** [comment]
@Aries-Lee1991 你看一下这两个函数的逻辑就知道了，不可能同时为false的，应该是所有版本jdbc都有这个问题

**Comment by zyyang-taosdata** [comment]
这个问题在下个jdbc版本中已经修复，请等待测试后的发布
