### ISSUE TITLE
Create Database

### ISSUE THREAD

**Issue by freedom0822** [taosdata/TDengine#2747]
create database xx keep 7 precision 'us';
报invalid option错误； 删除keep 7就没问题，根据文档可以加keep，不知道是哪里有问题？

谢谢

**Comment by freedom0822** [comment]
加引号就可以了。。。

**Comment by freedom0822** [comment]
create database xx keep '7' precision 'us';

**Comment by Aries-Lee1991** [comment]
默认days是10天，你Keep 7肯定是失败的。你所说的加引号就可以？？？应该不行吧。你要想保存7天的话，要把day默认为1天。

**Comment by freedom0822** [comment]
create database xx keep '7' precision 'us';  这样能够创建成功，但show databases; 显示还是3650天，我的taosdb版本是1.6.6.1

**Comment by Aries-Lee1991** [comment]
> create database xx keep '7' precision 'us'; 这样能够创建成功，但show databases; 显示还是3650天，我的taosdb版本是1.6.6.1

操作肯定是有问题的，建议还是多看看我们的文档吧。我们研发说了，绝对不存在，没有keep'7'这种写法。

**Comment by Aries-Lee1991** [comment]
> create database xx keep '7' precision 'us'; 这样能够创建成功，但show databases; 显示还是3650天，我的taosdb版本是1.6.6.1

那就说明，你这个keep '7'并没有生效。

**Comment by freedom0822** [comment]
create database xx keep 7 precision 'us';  那这个命令有问题吗？

**Comment by freedom0822** [comment]
只输入 CREATE DATABASE strat KEEP 7;   也是报invalid option， 还是说keep天数有限制？

**Comment by freedom0822** [comment]
可以设置最小keep 天数吗, 我们的需求不需要保留太长数据

**Comment by easykoala** [comment]
奇怪了，我提的issue还会被删除掉？？？

**Comment by freedom0822** [comment]
知道了， create database strat days 1 keep 7; 这样就好了，  keep必须是days的整数倍

**Comment by Aries-Lee1991** [comment]
> 知道了， create database strat days 1 keep 7; 这样就好了， keep必须是days的整数倍

是的。

**Comment by Aries-Lee1991** [comment]
> 奇怪了，我提的issue还会被删除掉？？？

没有被删除吧，我这里没有看到被删除
