### ISSUE TITLE
3.2.3.0版本 按时间窗口interval按1w和7d分组返回数据不符合预期

### ISSUE THREAD

**Issue by lihy8080** [taosdata/TDengine#27491]
开始时间和结束时间差6天，理论上1w和7d都返回一条数据，但是实际都返回了2条数据
![微信图片_20240827151659](https://github.com/user-attachments/assets/30632516-0625-42f0-8f6c-ff480f330386)

**Comment by tom055** [comment]
+1

**Comment by yu285** [comment]
https://www.taosdata.com/tdengine-engineering/3278.html

窗口划分规则请参考上问
