### ISSUE TITLE
taosd服务启动不了

### ISSUE THREAD

**Issue by qingqicangyu** [taosdata/TDengine#27494]
执行startall.sh命令后弹出四个successfully，输入taos后弹出报错未能连接服务（failed to connect to server, reason: Unable to establish connection）。systemctl查看四个服务状态，taosd和taoskeeper两个是failed（另外两个actived的我就没截进来）。
![屏幕截图 2024-08-27 164353](https://github.com/user-attachments/assets/dfd8cc4c-0216-4fff-89c6-66c61e4f9aa7)
查看日志(/var/log/taos/taosdlog.0)
![屏幕截图 2024-08-27 164814](https://github.com/user-attachments/assets/d914338e-24f6-46ce-8ad2-50177d15fc5e)
提示缺少的两个Json文件在官方文档里面没找到

**Comment by yefeng2016** [comment]
这个是解决了？

**Comment by qingqicangyu** [comment]
> 这个是解决了？

unsupported platform,操作系统不支持。社区版不支持部分国产操作系统，我用的是统信UOSV20-1050A（龙蜥8.9）是不行的。但是不是不能用，docker部署的话能用，我这边是要用到插件弄监控，所以是安装包安装的
