### ISSUE TITLE
redhat7.9启动taosd失败

### ISSUE THREAD

**Issue by Witten1997** [taosdata/TDengine#27508]
在redhat7.9系统中启动taosd失败，查询systemctl status taosd信息如下
● taosd.service - server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since 三 2024-08-28 11:00:27 CST; 22min ago
  Process: 75199 ExecStart=/usr/bin/taosd (code=exited, status=255)
  Process: 75192 ExecStartPre=/usr/local/taos/bin/startPre.sh (code=exited, status=0/SUCCESS)
 Main PID: 75199 (code=exited, status=255)

8月 28 11:00:27 redhat1 systemd[1]: Unit taosd.service entered failed state.
8月 28 11:00:27 redhat1 systemd[1]: taosd.service failed.
8月 28 11:00:27 redhat1 systemd[1]: taosd.service holdoff time over, scheduling restart.
8月 28 11:00:27 redhat1 systemd[1]: Stopped server service.
8月 28 11:00:27 redhat1 systemd[1]: start request repeated too quickly for taosd.service
8月 28 11:00:27 redhat1 systemd[1]: Failed to start server service.
8月 28 11:00:27 redhat1 systemd[1]: Unit taosd.service entered failed state.
8月 28 11:00:27 redhat1 systemd[1]: taosd.service failed.

查询了日志，错误信息如下
![image](https://github.com/user-attachments/assets/58da7f65-af6f-40fb-ab01-cf07e8c420b8)

查询了/var/lib/taos目录中只有.running文件，尝试了prm安装跟tar.gz安装都是这个情况，安装的是3.3.2版本，在centos7的版本中安装没有问题，可以正常启动连接，但是在redhat7.9中就不行

**Comment by aerochenj** [comment]
rockylinux8.9rpm和tar.gz两种方式也是同样问题

**Comment by yu285** [comment]
麻烦提供一下 uname -a 输出结果

**Comment by Witten1997** [comment]
> 麻烦提供一下 uname -a 输出结果

![image](https://github.com/user-attachments/assets/23a5a1b4-6a69-41b9-a364-02a59636f6e7)

**Comment by yu285** [comment]
下个版本应该就可以了，应该是3320的版本检查做了改动。

**Comment by yu285** [comment]
本月底发版。

**Comment by yu285** [comment]
版本已经发布 麻烦升级验证

**Comment by yu285** [comment]
暂作关闭处理，如有问题可联系 a15652223354
