### ISSUE TITLE
JDBC 数据订阅实现失败

### ISSUE THREAD

**Issue by Flyerison** [taosdata/TDengine#2751]
TDengine版本：1.6.5.9
JDBC：1.0.3
Q：java版本数据订阅实现失败

JDBC的API subscribe(String host, String user, String password, String database, String table, long time, int period) 与 文档中介绍的C/C++ API不一致，是版本未同步吗？

消费端主要代码如下：
jniConnector = new TSDBJNIConnector();
long subscribe = jniConnector.subscribe("jdbc:TAOS://172.16.11.241:6030", "root", "taosdata", "iot", "mq_iot_device", new Date().getTime(), 10);
while(true) {
      TSDBResultSetRowData consume = jniConnector.consume(subscribe);
}

生产者代码就是向一张表插入数据，这个是成功的，可以看到表中新加了数据
create table mq_iot_device (ts timestamp, data BINARY(2048));

subscribe  返回值是0 可能是连接失败的返回码，  consume也并未阻塞

不知道问题出现在什么地方，希望大佬能给看下是什么原因

**Comment by Flyerison** [comment]
我在 JDBCDemo  项目中看到了数据订阅的代码，但是部分类没有找到，估计是版本较为落后的原因~~
taos-jdbcdriver.jar  V1.0.1/2/3都找过，都没有TSDBSubscribe这个类
![image](https://user-images.githubusercontent.com/28044926/88352601-e3409f00-cd8c-11ea-8f79-93f659146493.png)

**Comment by Flyerison** [comment]
已找到问题
develop分支  源码中找到 TDengine/src/connector/jdbc  项目，当中含有缺失的数据订阅部分代码，pom文件也是显示是1.0.3版本，但是从maven源下载的 V1.0.3 jar中缺失部分代码~~
<groupId>com.taosdata.jdbc</groupId>
<artifactId>taos-jdbcdriver</artifactId>
<version>1.0.3</version>
<packaging>jar</packaging>
已通过手动重新打包 taos-jdbcdriver-1.0.3.jar 替换maven源下载的jar包，并且已通过测试，订阅到数据
请检查下  推maven源  当中环节是否存在问题

**Comment by xiaopingcs** [comment]
好的，谢谢，我们1.6版本的订阅确实有问题，在develop分支修复没有合并到1.6版本里面。现在都在忙最新版本，1.6版本暂时不提供支持。我先关闭这个问题， 如果有其他问题麻烦再新建一个issue。谢谢帮我们指出问题。
