### ISSUE TITLE
3.0.1.4版本  根据主键时间戳排序 结果集未正确排序

### ISSUE THREAD

**Issue by dian78js** [taosdata/TDengine#27523]
3.0.1.4版本  根据主键时间戳排序 结果集未正确排序

select xxx from monitor.kickstand_863218075378251 T1 WHERE T1.connect_type = 'ctwing' and report_device_time > '2024-08-28 05:00:00.000' ORDER BY T1.report_device_time DESC

结果集 404 和 405行 排序开始不对
<img width="740" alt="image" src="https://github.com/user-attachments/assets/e54803c6-0537-4eb6-b66e-934225353b44">

**Comment by dian78js** [comment]
请问这个问题是bug还是有其他注意点

**Comment by yu285** [comment]
这个版本是有这个问题的，另外这个版本太旧了和现在不兼容。重新部署使用最新版的 3.3.2.0 吧，排序问题已经修复了。

**Comment by dian78js** [comment]
好，已经用最新的了
