### ISSUE TITLE
TDengine集群3.3.2是否支持基于数据文件还原数据？

### ISSUE THREAD

**Issue by wyzzzl** [taosdata/TDengine#27522]
请教一下  ，TDengine集群3.3.2是否支持基于数据文件还原数据？谢谢！

举例：
我建了一个3.3.2版本的集群含A，B，C三个机器，
我把A机器的数据目录dataDir数据拷贝到机器D，
机器A和D的taos.cfg配置相同， 
在机器D是否可以还原出节点A的数据？如果可以，具体怎么实现？

**Comment by yu285** [comment]
支持。只要确保fqdn解析出的ip 正确即可。

如果不了解fqdn ,可以先看文档或者：https://www.taosdata.com/tdengine-engineering/2741.html
