### ISSUE TITLE
tdengine 3.3.2.6 

### ISSUE THREAD

**Issue by hchw** [taosdata/TDengine#27547]
tdengine 里面总是报一些奇怪的日志
我用influxdb 的模式插入数据 
怎么数据库总是报一些这样的错误
C UTL SML data(name:Ii1 type:FLOAT) is not same like the db data(name:OnlineStatus type:BIGINT)
SML data(name:Ui1 type:FLOAT) is not same like the db data(name:OnlineStatus type:BIGINT)
这个错误的含义是什么？

**Comment by yu285** [comment]
您这个是企业版吗？

**Comment by hchw** [comment]
不是
