### ISSUE TITLE
python connector problem

### ISSUE THREAD

**Issue by freedom0822** [taosdata/TDengine#2761]
``` python
import taos
taos.connect(host='192.168.200.4',user='root',password='taosdata')

07/24 18:02:56.305209 30454 7f158e1b2700 ERROR UTL failed to connect socket, ip:192.168.200.1, port:6030, reason: Connection refused
```

指定host地址，为什么显示连接192.168.200.1:6030，是否本地配置需要修改? 
谢谢

ps: 192.168.200.1是本地ip地址
server version: 1.6.6.1
connector version: 1.4.15

**Comment by liuyq-617** [comment]
我使用了两台linux服务器，没有复现出您的情况。
麻烦将客户端的debugFlag 日志开关调整为135，然后把完整的日志，发送到yqliu@taosdata.com
