### ISSUE TITLE
Python UDF 函数无法调用

### ISSUE THREAD

**Issue by booleriot** [taosdata/TDengine#27674]
问题描述：
使用Python UDF函数的时候无法调用，参考的Demo是[示例一](https://docs.taosdata.com/develop/udf/)，目前出现的结果：
![image](https://github.com/user-attachments/assets/8ed00246-a5b9-41db-a6e7-2b90f3f18679)
环境以及相关上下文描述：
1、TD服务端使用Docker进行启动的，最新的版本，启动的代码如下：
2、版本是 Client Version:3.3.2.0 跟服务端一个机器。
3、操作系统版本：
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

4、
![image](https://github.com/user-attachments/assets/9419e98c-3150-4c5d-b35f-562ed4a5a749)
这个文件没有。
5、
![image](https://github.com/user-attachments/assets/df28706f-75c3-4707-b1af-803f390c03d2)
这个是对应的日志,taoslog0.0,这个文件有错误日志：
![image](https://github.com/user-attachments/assets/42c38d04-3a03-4b73-a7b6-07a5e664f38f)
6、具体的代码
![image](https://github.com/user-attachments/assets/44bbe9f9-18bd-4e09-9022-3677bbc2879b)
7、
![image](https://github.com/user-attachments/assets/f33a5800-74c3-41fe-9373-2e6405bb9a5a)

以上是我的问题描述。

**Comment by yu285** [comment]
需要去服务端看到 udf的日志，你这个应该是客户端的日志目录

**Comment by booleriot** [comment]
![image](https://github.com/user-attachments/assets/3a11fed3-414a-4459-b20d-498dc53d133a)
谢谢你的回复，这些命令是再客户端的执行，还是需要再服务端执行（目前我的服务端是Docker进行启动的）

**Comment by booleriot** [comment]
> 需要去服务端看到 udf的日志，你这个应该是客户端的日志目录

![image](https://github.com/user-attachments/assets/dfb919cd-17e5-448c-902e-0af319cd69e4)
谢谢你的回复，这些命令是再客户端的执行，还是需要再服务端执行（目前我的服务端是Docker进行启动的）

**Comment by yu285** [comment]
在服务端操作

**Comment by yu285** [comment]
any update?
