### ISSUE TITLE
taosdump恢复数据失败

### ISSUE THREAD

**Issue by bahuzh** [taosdata/TDengine#27683]
dbs.sql

#!server_ver: ver:3.3.2.0
#!taosdump_ver: 3.3.2.0_6d748239c188db3d2293ae31196ed7ed76a40f38
#!os_id: LINUX
#!escape_char: true
#!loose_mode: false
#!charset: UTF-8
CREATE DATABASE IF NOT EXISTS stk_minute1_us REPLICA 1   DURATION 14400m KEEP 5256000m,5256000m,5256000m     PRECISION 'ms'   MINROWS 100 MAXROWS 4096 COMP 2 ;

CREATE TABLE IF NOT EXISTS stk_minute1_us.`stock_minute_line`(`time` timestamp) TAGS(`asset_id` binary(100),`mkt_day` binary(100),`min` int,`mins` binary(100),`open_price` float,`high_price` float,`low_price` float,`close_price` float,`prev_close` float,`adj_factor` float,`volume` bigint,`turnover` bigint,`m_interval` binary(10));

------
taosdump
ERROR: getTableDesNative() LN3092, failed to run command <DESCRIBE stk_minute1_us.`stock_minute_line`>. code: 0x80002603, reason: Table does not exist
ERROR: dumpInAvroTbTagsImpl() LN6121 Unknown type: 8
WARN: dumpInAvroTbTagsImpl() LN6153 taos_query() failed! sqlstr: CREATE TABLE stk_minute1_us.`usgsl` USING stk_minute1_us.`stock_minute_line` TAGS), reason: syntax error near ")"

----
taos cli
Server is TDengine Community Edition, ver:3.3.2.0 and will never expire.

taos> CREATE DATABASE IF NOT EXISTS stk_minute1_us REPLICA 1   DURATION 14400m KEEP 5256000m,5256000m,5256000m     PRECISION 'ms'   MINROWS 100 M
AXROWS 4096 COMP 2 ;
Create OK, 0 row(s) affected (0.000782s)

taos> CREATE TABLE IF NOT EXISTS stk_minute1_us.`stock_minute_line`(`time` timestamp) TAGS(`asset_id` binary(100),`mkt_day` binary(100),`min` int
,`mins` binary(100),`open_price` float,`high_price` float,`low_price` float,`close_price` float,`prev_close` float,`adj_factor` float,`volume` bi
gint,`turnover` bigint,`m_interval` binary(10));

DB error: Illegal number of columns (0.000614s)
taos>

**Comment by yu285** [comment]
你需要额外设置一列时间戳数据，不能只存一列时间戳。

至少需要两列，格式为 timestamp + other type(include timestamp)
