### ISSUE TITLE
涛思连接没有断，按时不返回数据

### ISSUE THREAD

**Issue by zlcm20** [taosdata/TDengine#27681]
java插入涛思数据或者查询刚开始都没有问题，但是过一段时间，涛思不返回数据，请求一直在响应，导致接口超时，这个连接不能释放，什么场景可能出现此状况？

**Comment by yu285** [comment]
信息太少完全不够判断，版本号，日志，硬件资源截图，麻烦提供一下，暂作close 处理，提供后再reopen。
