### ISSUE TITLE
通过 rest/sql 操作时出现 {"status":"error","code":32,"desc":"invalid table"} 问题。

### ISSUE THREAD

**Issue by bevin1984** [taosdata/TDengine#277]
1. 先创建了一张超级表 A
2. 通过 rest/sql 执行 INSERT INTO dbname.table001 USING dbname.stable TAGS (001) VALUES (1542544024000, 0, 0) 插入并创建表。
3. 通过命令行下执行 drop table table001;
4. 再执行第2步时，报 {"status":"error","code":32,"desc":"invalid table"} 的错。

当前版本：1.6.1.2

**Comment by hzcheng** [comment]
问题是这样的，TDengine的服务端内嵌了一个客户端，用来处理HTTP的发来的SQL语句。客户端内有cache，是表的schema等信息。在shell中drop表后，shell中客户端的cache会被更新。但是TDengine服务端内嵌的
cache没有更新。目前这是一个问题。最近会修复这个问题。非常感谢报告！
