### ISSUE TITLE
About TDengine Alert：failed to query TDengine: taos_connect() fail!

### ISSUE THREAD

**Issue by hb990208** [taosdata/TDengine#2774]
错误提示：
2020-07-27T14:15:40.491+0800	ERROR	log/log.go:69	[CarTooFast]: failed to query TDengine: taos_connect() fail!
github.com/taosdata/alert/utils/log.Errorf
	/home/zbm/project/td/community/alert/utils/log/log.go:69
github.com/taosdata/alert/app.(*Rule).run
	/home/zbm/project/td/community/alert/app/rule.go:345
github.com/taosdata/alert/app.runRules.func1.1
	/home/zbm/project/td/community/alert/app/rule.go:483

告警配置文件
[alert.zip](https://github.com/taosdata/TDengine/files/4980450/alert.zip)

告警规则文件
[rule.zip](https://github.com/taosdata/TDengine/files/4980451/rule.zip)

**Comment by d8txc** [comment]
me too

**Comment by hb990208** [comment]
22天了......怎么还要等,求教一下怎么解决呀...

**Comment by zskylark** [comment]
对go的支持很差，go的驱动也只能支持linux下编译，win下编译不出来与之cgo配合的库。
我在centos7下跑个driver_test.go报错： taos_connect() fail!
db, err := sql.Open(DRIVER_NAME, dataSourceName)
if err != nil {
	t.Fatalf("error on:  sql.open %s", err.Error())
	return
}
defer db.Close()
dbt := &DBTest{t, db}
// prepare data
dbt.db.Exec("DROP TABLE IF EXISTS test")  <-- 执行到此处必报错：taos_connect() fail!
另外，直接用taos连数据库没问题，说明地址和端口没错，服务器也没问题。

**Comment by sangshuduo** [comment]
可以跑一下 TDengine/tests/examples/go 试一下吗？
