### ISSUE TITLE
Last函数返回查询时间范围外的数据

### ISSUE THREAD

**Issue by centychen** [taosdata/TDengine#27789]
**Bug Description**
3.3.1版本使用Last函数查询某个时间范围内最后一个非null数据时，返回了时间范围外的数据。

**To Reproduce**
如下图查询语句：
![image](https://github.com/user-attachments/assets/73bd6f24-5b11-473e-9134-c5a0ac75adc2)

**Environment (please complete the following information):**
 - TDengine Version [3.3.1]

**Comment by yu285** [comment]
在服务端的taos shell 麻烦执行一下一样的sql , 然后截图发我们一下

**Comment by centychen** [comment]
taos执行也是一样的结果：
![image](https://github.com/user-attachments/assets/84f96b38-ed75-47f0-9944-36378ed7c344)

**Comment by yu285** [comment]
应该是已知问题，麻烦升级到 3.3.3.0 ，再验证一下吧。

如果还有问题可以添加微信 a15652223354
