### ISSUE TITLE
java win10 连接Demo运行失败

### ISSUE THREAD

**Issue by lpeng-git** [taosdata/TDengine#278]
语言：java；开发环境：win10，服务器：本机上安装的虚拟机，系统为centOS7，防火墙已经关闭

在linux上可以操作数据库，在win上做java开发，不能成功，一直创建连接失败
ps：taos-jdbcdriver-1.0.0-dist.jar已经在maven中安装
安装命令：mvn install:install-file -Dfile=D:\repository\com\taosdata\jdbc\taos-jdbcdriver\1.0.0\taos-jdbcdriver-1.0.0-dist.jar -DgroupId=com.taosdata.jdbc -DartifactId=taos-jdbcdriver -Dversion=1.0.0 -Dpackaging=jar

pom文件中 dependency如下：

`<dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>1.0.0</version>
        </dependency>`

demo运行结果如下：
Arguments format: host tables loop batchs
---------------------------------------------------------------
Start testing...
---------------------------------------------------------------

JDBC URL to use:
jdbc:TAOS://192.168.40.128:0/?user=root&password=taosdata

---------------------------------------------------------------
Start creating databases and tables...
java.sql.SQLException: TDengine Error: failed to connect to server
	at com.taosdata.jdbc.TSDBJNIConnector.connect(TSDBJNIConnector.java:96)
	at com.taosdata.jdbc.TSDBConnection.connect(TSDBConnection.java:64)
	at com.taosdata.jdbc.TSDBConnection.<init>(TSDBConnection.java:56)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:135)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at com.lp.tdtest.Demo.doCreateDbAndTable(Demo.java:100)
	at com.lp.tdtest.Demo.main(Demo.java:56)
Failed to execute SQL: 

Process finished with exit code 4

是否是因为不支持win10导致的？还是有什么需要做的设置没做？

**Comment by padin** [comment]
大哥，taos-jdbcdriver-1.0.0-dist.jar在哪里下载的？

**Comment by xiaohaiany** [comment]
你可以安装一个windows版本的taos，里面有对应的jar,dll包

**Comment by johnnyhou327** [comment]
@lpeng-git 您试试在cmd中用taos客户端连接服务能否连上呢？可以对照[FAQ](https://www.taosdata.com/cn/faq/)中列出的一些点对照尝试解决一下，如果排除那些可能仍不能连接，就要看看客户端日志，windows上客户端日志在C:/TDengine/log

**Comment by linzhenyao** [comment]
我也是这样在 linux上可以操作数据库，在win上做java开发，一直连接不上

**Comment by sangshuduo** [comment]
请使用新的 TDengine 2.0.3.1 和 JDBC driver 2.0.4
