### ISSUE TITLE
使用last查询缓存不一致

### ISSUE THREAD

**Issue by leonhu2016** [taosdata/TDengine#27828]
步骤：
1、cachemodel设为both
2、表中插入一条时间戳为A的数据，且列不为空
3、表中重新插入一条时间戳为A的数据，并把列置为空
现象：
1、表中时间戳A的数据列均被置为了null
2、使用last查询值为null的列返回了未覆盖前的非空数据

**Comment by yu285** [comment]
需要提供版本号和操作截图，暂作关闭处理，补充完后再reopen
