### ISSUE TITLE
关于 interval 时间分割问题

### ISSUE THREAD

**Issue by jinghuijiang1993** [taosdata/TDengine#27855]
**Bug Description**
我对一个相同查询时间段进行 4h 和 3h 间隔，但是查询出来的时间间隔没有理解

**To Reproduce**
![WechatIMG311](https://github.com/user-attachments/assets/468b5cbe-2338-4146-88ca-a132049bf10a)
![WechatIMG312](https://github.com/user-attachments/assets/04ab977a-25d9-4851-af23-d17589241584)
为什么3h 的是 23点 2 点 而 4h 的就是 0 点 4 点呢
 我之前看过你们对 interval 的介绍 但是 还是没有得到这个问题的答案 麻烦解答一下

**Comment by yu285** [comment]
想看窗口的时间戳。需要使用_wstart 、 _wend 伪列，具体用法可以看下文档

**Comment by jinghuijiang1993** [comment]
我的 sql 使用了_wstart 伪列了  ts 是我用的别名  你发的这个文档我看过多次了


On September 13, 2024 at 2:28:43 PM, Yu Chen ***@***.***) wrote:

想看窗口的时间戳。需要使用_wstart 、 _wend 伪列，具体用法可以看下文档

**Comment by jinghuijiang1993** [comment]
还有就是 这个问题 我们沟通 都没有结论  然后这边就主动关闭这个问题 不明白你这边是这样处理和解答别人的疑问的吗
