### ISSUE TITLE
Springboot Druid connect TDengine problem!

### ISSUE THREAD

**Issue by coffeenan** [taosdata/TDengine#2785]
- X86服务器，Centos7版本，使用spring boot + druid连接TDengine, 使用100个线程每10ms间隔往同一张表写入数据，中途服务器断电，重启后登录数据区，发现表损坏，并且重新启动数据写入程序后，正常运行1分钟后数据库无法通过JDBC访问，求解决和修复方法

![微信截图_20200728151116](https://user-images.githubusercontent.com/6970189/88631917-807d3980-d0e5-11ea-99a5-6349d418d752.png)

![微信图片_20200728151758](https://user-images.githubusercontent.com/6970189/88631952-8c68fb80-d0e5-11ea-801c-191df8f6b547.png)

**Comment by liuyq-617** [comment]
如果数据重要，可以联系商务咨询我们的数据恢复服务。否则，推荐删除数据重装

**Comment by ZhangJiaLei123** [comment]
我也尝试通过druid连接TDengine,但是提示错误:
```
java.sql.SQLException: connect error, url jdbc:TAOS://192.168.0.11:6030, driverClass com.taosdata.jdbc.TSDBDriver
```
请问您是怎么解决的?

**Comment by coffeenan** [comment]
你好，我自己实验了下，在涛思1.6版本的jdbc驱动中，druid中的有些配置项，有些功能是完全没有实现的，导致我们如果按照晚上mysql的配置方法，会导致错误

例如下面两项：
#spring.datasource.druid.taos.poolPreparedStatements=true
#spring.datasource.druid.taos.maxPoolPreparedStatementPerConnectionSize=20
一旦配置springboot就会无法启动，所以一定要注释掉

我这里有个可运行的配置内容，请参照
#======= Druid Taos database connection pool ========
spring.datasource.druid.taos.url=jdbc:TAOS://xxx.xxx.xxx.xxxx:6030/log?test=test&charset=UTF-8
spring.datasource.druid.taos.username=root
spring.datasource.druid.taos.password=taosdata
spring.datasource.druid.taos.driver-class-name=com.taosdata.jdbc.TSDBDriver
spring.datasource.druid.taos.type=com.alibaba.druid.pool.DruidDataSource

spring.datasource.druid.taos.initialSize=20
spring.datasource.druid.taos.minIdle=5
spring.datasource.druid.taos.maxActive=40
spring.datasource.druid.taos.maxWait=6000
spring.datasource.druid.taos.timeBetweenEvictionRunsMillis=60000
spring.datasource.druid.taos.minEvictableIdleTimeMillis=300000
spring.datasource.druid.taos.validationQuery=select server_status()
spring.datasource.druid.taos.testWhileIdle=true
spring.datasource.druid.taos.testOnBorrow=false
spring.datasource.druid.taos.testOnReturn=false
#spring.datasource.druid.taos.poolPreparedStatements=true
#spring.datasource.druid.taos.maxPoolPreparedStatementPerConnectionSize=20
spring.datasource.druid.taos.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

最近一直没上邮件，回复与点慢，抱歉，希望能解决你的问题


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: libai<mailto:notifications@github.com>
发送时间: 2020年9月22日 18:02
收件人: taosdata/TDengine<mailto:TDengine@noreply.github.com>
抄送: ChenNan<mailto:xuehu001@hotmail.com>; State change<mailto:state_change@noreply.github.com>
主题: Re: [taosdata/TDengine] Springboot Druid connect TDengine problem! (#2785)


我也尝试通过druid连接TDengine,但是提示错误:

java.sql.SQLException: connect error, url jdbc:TAOS://192.168.0.11:6030, driverClass com.taosdata.jdbc.TSDBDriver



请问您是怎么解决的?

―
