### ISSUE TITLE
taos数据导入

### ISSUE THREAD

**Issue by helloworld-zhangxc** [taosdata/TDengine#27858]
taos导入csv文件，文件20g，2亿条数据，导入时报错system out of memory，如何解决，有大佬遇到过吗？小的文件可以正常导入，在不分割文件的情况下是否有解决方案？？？

**Comment by helloworld-zhangxc** [comment]
> 版本号是？

3.0.1.4的版本

**Comment by yu285** [comment]
这个版本是两年前的初始版本，太旧了，和现在版本不兼容。麻烦部署一下最新版3320 或者等月底官方发版，3330，不会有类似问题。

建议等最后者发版。

**Comment by helloworld-zhangxc** [comment]
> 这个版本是两年前的初始版本，太旧了，和现在版本不兼容。麻烦部署一下最新版3320 或者等月底官方发版，3330，不会有类似问题。
> 
> 建议等最后者发版。

好的，感谢
