### ISSUE TITLE
合法的子表名，查询子表如果表名不用``包括，则报错表不存在

### ISSUE THREAD

**Issue by liangdd2** [taosdata/TDengine#27867]
合法的子表名，查询子表如果表名不用``包括，则报错表不存在
<img width="552" alt="tdbug图片" src="https://github.com/user-attachments/assets/6e70e418-60d2-499c-b1a0-611222c49abe">

服务器版本3.3.2.0 Community

**Comment by yu285** [comment]
不用`` 会被转化为小写，这是正常用法，可以看下文档。
