### ISSUE TITLE
JNI ERROR (2354):success

### ISSUE THREAD

**Issue by 001wangwei** [taosdata/TDengine#27872]
![5f4fa53b969bdb773c459c3a779d525](https://github.com/user-attachments/assets/cc2d8821-219d-4881-b34c-7a88f13edd75)

同一台服务器部署的java和tdengine，采用yml文件部署，本地测试正常访问

**Comment by 001wangwei** [comment]
使用的是连接池方式连接

**Comment by yu285** [comment]
本地测试正常访问——指的是taos shell 可以正常读写吗

**Comment by 001wangwei** [comment]
对，可以正常去读写。但是在linux环境就不行
&nbsp;


1255324804
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yu ***@***.***&gt;; 
发送时间: 2024年9月13日(星期五) 下午5:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [taosdata/TDengine] JNI ERROR (2354):success (Issue #27872)














 
本地测试正常访问——指的是taos shell 可以正常读写吗

**Comment by 001wangwei** [comment]
![image](https://github.com/user-attachments/assets/7b433816-7f5b-458c-90f5-acc7e2b831fe)
目前我的配置

**Comment by 001wangwei** [comment]
![image](https://github.com/user-attachments/assets/8b965c34-bec9-4792-a979-cc2236e7f4e5)
这是我的配置

**Comment by yu285** [comment]
数据库和驱动的版本是？

**Comment by 001wangwei** [comment]
数据库版本是

 驱动版本是
<dependency&gt;
    <groupId&gt;com.taosdata.jdbc</groupId&gt;
    <artifactId&gt;taos-jdbcdriver</artifactId&gt;
    <version&gt;3.3.2</version&gt;
</dependency&gt;
&nbsp;


1255324804
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yu ***@***.***&gt;; 
发送时间: 2024年9月18日(星期三) 上午9:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [taosdata/TDengine] JNI ERROR (2354):success (Issue #27872)














 
数据库和驱动的版本是？

**Comment by yu285** [comment]
数据版本没写：
![Uploading image.png…]()

**Comment by 001wangwei** [comment]
数据库版本是3.3.2.0 



125532480发送
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taosdata/TDengine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月18日(星期三) 上午10:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [taosdata/TDengine] JNI ERROR (2354):success (Issue #27872)





 
数据版本没写：
 image.png (view on web)

**Comment by babyo0o** [comment]
请问这个问题解决了吗？遇到了同样的问题

**Comment by 001wangwei** [comment]
没有，换了个服务器就好了
&nbsp;


1255324804
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月8日(星期二) 中午11:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [taosdata/TDengine] JNI ERROR (2354):success (Issue #27872)














 
请问这个问题解决了吗？遇到了同样的问题
