### ISSUE TITLE
taosdump 3.3.2 还原数据报错 FATAL obtained 9 stack frames

### ISSUE THREAD

**Issue by wyzzzl** [taosdata/TDengine#27880]
ubuntu 18.04
tdengine 3.3.2 集群 --> tdengine 3.3.2 单节点
taosdump 3.3.2 out --> taosdump 3.3.2 in

**taosdump安装方法如下：**
wget https://www.taosdata.com/assets-download/3.0/TDengine-server-3.3.2.0-Linux-x64.deb
sudo dpkg -i TDengine-server-3.3.2.0-Linux-x64.deb

**还原命令如下：**
taosdump --host=10.10.1.12 --inpath=/data/backup/backup_08_13 --databases=test --thread-num=1 -B 500

**数据总量 869MB，查看 /var/log/taos/taosdlog.0 并未发现报错信息，执行多次还原命令有时可以成功，有时报错，
stop-all.sh && start-all.sh 后也无效果，报错信息如下：**
x.OK: [0] 1440 row(s) of file(test.3452418814259.1914.avro) be successfully dumped in!
.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.OK: [0] 24262 row(s) of file(test.3452418814267.1915.avro) be successfully dumped in!
.x.OK: [0] 1440 row(s) of file(test.3452418814349.1916.avro) be successfully dumped in!
09/13 10:12:58.720541 00022416 C UTL FATAL tAssert called in release mode, exit:1
09/13 10:12:58.721273 00022416 C UTL FATAL obtained 9 stack frames
09/13 10:12:58.721280 00022416 C UTL FATAL frame:0, /usr/lib/libtaos.so.1(taosAssertRelease+0x58) [0x7f4695842de8]
09/13 10:12:58.721282 00022416 C UTL FATAL frame:1, /usr/lib/libtaos.so.1(setResultDataPtr+0xb9) [0x7f46957fbe79]
09/13 10:12:58.721287 00022416 C UTL FATAL frame:2, /usr/lib/libtaos.so.1(asyncExecLocalCmd+0xbc) [0x7f46957fe8ac]
09/13 10:12:58.721292 00022416 C UTL FATAL frame:3, /usr/lib/libtaos.so.1(+0x1c16c3) [0x7f46958066c3]
09/13 10:12:58.721295 00022416 C UTL FATAL frame:4, /usr/lib/libtaos.so.1(ctgCallUserCb+0x2d) [0x7f469594d43d]
09/13 10:12:58.721301 00022416 C UTL FATAL frame:5, /usr/lib/libtaos.so.1(+0x365a1b) [0x7f46959aaa1b]
09/13 10:12:58.721303 00022416 C UTL FATAL frame:6, /usr/lib/libtaos.so.1(+0x207b45) [0x7f469584cb45]
09/13 10:12:58.721304 00022416 C UTL FATAL frame:7, /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f46952076db]
09/13 10:12:58.721308 00022416 C UTL FATAL frame:8, /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f46945fb61f]
Aborted (core dumped)

**ll -h /usr/lib/libtaos.so && ll -h /usr/lib/libtaos.so.1 结果：**

user@10:/data/backup$ ll -h /usr/lib/libtaos.so
lrwxrwxrwx 1 root root 21 Sep 12 10:38 /usr/lib/libtaos.so -> /usr/lib/libtaos.so.1*

user@10:/data/backup$ ll -h /usr/lib/libtaos.so.1
lrwxrwxrwx 1 root root 41 Sep 12 10:18 /usr/lib/libtaos.so.1 -> /usr/local/taos/driver/libtaos.so.3.3.2.0*

**Comment by yu285** [comment]
这个是已知问题被修复过，急用的话麻烦自己编译到main分支，或者等月底官方发版。

**Comment by wyzzzl** [comment]
好的，谢谢！
