### ISSUE TITLE
interval 时间划分有问题

### ISSUE THREAD

**Issue by jinghuijiang1993** [taosdata/TDengine#27897]
一个 3h 和 4h 间隔   为啥时间起始不一样呢  不是都从 0 点开始   我使用了伪劣  请仔细看下我的结果  时间间隔的规则是什么 
![WechatIMG311](https://github.com/user-attachments/assets/2739829d-cc81-4065-a06f-0a1196e794ba)
![WechatIMG312](https://github.com/user-attachments/assets/95e6d58d-4062-493d-a8d6-0756d577e682)
**Bug Description**

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by yu285** [comment]
SQL 不完整，请补充一下

**Comment by jinghuijiang1993** [comment]
select _WSTART AS ts,17581 AS id,19 as station,11 as unit,6 as db,0 AS ord, LAST(result) AS result  from mydb_unit6.normal_point_17581_19_11_6 where ts >= '2024-09-12 00:00:00.000' and ts <= '2024-09-12 09:39:01.999'  interval(3h)  fill(PREV)  limit 0 ,300000 ;    这个是我的 sql  仅用了_start 伪劣  分别进行了 3h 和 4h 间隔   然后间隔得到的 ts  没有理解 为啥不是都是从 0 点开始间隔 而有一个是从 23 点开始的  麻烦了 主要想知道这个时间间隔的规律是怎样的  方便我们这边处理数据


On September 18, 2024 at 9:27:41 AM, Yu Chen ***@***.***) wrote:

SQL 不完整，请补充一下

**Comment by yu285** [comment]
规律是从UTC-0时区，1970年1月1日 0点0分开始切分窗口，所以不是从你指定的时间开始切分的，如果想自定义，需要自己控制偏移量：参考文章https://mp.weixin.qq.com/s/Kc7wzzRiK4XhAsL48rD6dg

**Comment by jinghuijiang1993** [comment]
我想说明的是，不管是哪个时区进行 我的两个 sql 分别是 3h 和 4h 去进行时间间隔  这两个时间间隔都是可以被 24h 整除的  也就是说即使是 1970年1月1日 0点0分 0 秒开始进行切分  不应该每次都有 0 点 0 分 0 秒吗


On September 24, 2024 at 2:35:04 PM, Yu Chen ***@***.***) wrote:

规律是从UTC-0时区，1970年1月1日 0点0分开始切分窗口，所以不是从你指定的时间开始切分的，如果想自定义，需要自己控制偏移量：参考文章https://mp.weixin.qq.com/s/Kc7wzzRiK4XhAsL48rD6dg

**Comment by yu285** [comment]
> 我想说明的是，不管是哪个时区进行 我的两个 sql 分别是 3h 和 4h 去进行时间间隔  这两个时间间隔都是可以被 24h 整除的  也就是说即使是 1970年1月1日 0点0分 0 秒开始进行切分  不应该每次都有 0 点 0 分 0 秒吗 On September 24, 2024 at 2:35:04 PM, Yu Chen ***@***.***) wrote: 规律是从UTC-0时区，1970年1月1日 0点0分开始切分窗口，所以不是从你指定的时间开始切分的，如果想自定义，需要自己控制偏移量：参考文章https://mp.weixin.qq.com/s/Kc7wzzRiK4XhAsL48rD6dg — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

对呀，你没发现你两个查询都有8吗，这就是对齐时候的时间点 0 加上东八区的 8 小时。
