### ISSUE TITLE
Springboot demo  connect TDengine server problem!

### ISSUE THREAD

**Issue by amen943** [taosdata/TDengine#2793]
阿里云服务器：1.6.6.1，防火墙关闭，6030端口也对外开放，telnet成功。
客户端windows也装了对应的客户端，死活连接不上：Caused by: java.sql.SQLException: TDengine Error: failed to connect to server。
以下是日志：
==================================================
                new log file                      
==================================================
07/29 12:35:37.511000 0x9944 UTL timezone not configured, use default
07/29 12:35:37.522000 0x9944 UTL locale not configured, set to default:Chinese_China.936
07/29 12:35:37.522000 0x9944 UTL charset not configured, set to default:cp936
07/29 12:35:37.522000 0x9944 UTL    taos config & system info:
07/29 12:35:37.522000 0x9944 UTL ==================================
07/29 12:35:37.522000 0x9944 UTL  masterIp:               192.168.100.119 
07/29 12:35:37.522000 0x9944 UTL  localIp:                0.0.0.0 
07/29 12:35:37.522000 0x9944 UTL  mgmtShellPort:          6030 
07/29 12:35:37.522000 0x9944 UTL  vnodeShellPort:         6035 
07/29 12:35:37.522000 0x9944 UTL  configDir:              C:/TDengine/cfg 
07/29 12:35:37.522000 0x9944 UTL  logDir:                 C:/TDengine/log 
07/29 12:35:37.522000 0x9944 UTL  scriptDir:              C:/TDengine/script 
07/29 12:35:37.522000 0x9944 UTL  numOfThreadsPerCore:    0.000000 
07/29 12:35:37.522000 0x9944 UTL  affectedRowsMod:        0 
07/29 12:35:37.522000 0x9944 UTL  rpcTimer:               300(ms)
07/29 12:35:37.522000 0x9944 UTL  rpcMaxTime:             600(s)
07/29 12:35:37.522000 0x9944 UTL  shellActivityTimer:     3(s)
07/29 12:35:37.522000 0x9944 UTL  meterMetaKeepTimer:     7200(s)
07/29 12:35:37.522000 0x9944 UTL  metricMetaKeepTimer:    600(s)
07/29 12:35:37.522000 0x9944 UTL  defaultDB:               
07/29 12:35:37.522000 0x9944 UTL  defaultUser:            root 
07/29 12:35:37.522000 0x9944 UTL  sockettype:             udp 
07/29 12:35:37.522000 0x9944 UTL  compressMsgSize:        -1 
07/29 12:35:37.522000 0x9944 UTL  maxSQLLength:           65380(byte)
07/29 12:35:37.522000 0x9944 UTL  maxNumOfOrderedRes:     100000 
07/29 12:35:37.522000 0x9944 UTL  timezone:               not configured 
07/29 12:35:37.522000 0x9944 UTL  locale:                 Chinese_China.936 
07/29 12:35:37.522000 0x9944 UTL  charset:                cp936 
07/29 12:35:37.522000 0x9944 UTL  numOfLogLines:          10000000 
07/29 12:35:37.522000 0x9944 UTL  asyncLog:               1 
07/29 12:35:37.522000 0x9944 UTL  debugFlag:              131 
07/29 12:35:37.522000 0x9944 UTL  rpcDebugFlag:           131 
07/29 12:35:37.522000 0x9944 UTL  tmrDebugFlag:           131 
07/29 12:35:37.522000 0x9944 UTL  cDebugFlag:             131 
07/29 12:35:37.522000 0x9944 UTL  jniDebugFlag:           131 
07/29 12:35:37.522000 0x9944 UTL  odbcDebugFlag:          131 
07/29 12:35:37.522000 0x9944 UTL  uDebugFlag:             131 
07/29 12:35:37.522000 0x9944 UTL  qDebugFlag:             131 
07/29 12:35:37.522000 0x9944 UTL  gitinfo:                f40d01b9ae72f37c6701b5ef1d7e9192de28cb8b 
07/29 12:35:37.522000 0x9944 UTL  gitinfoOfInternal:      37d94d45a2026760c10c91d743166b418178567e 
07/29 12:35:37.522000 0x9944 UTL  buildinfo:              Built by root at 2020-04-02 13:35 
07/29 12:35:37.522000 0x9944 UTL  version:                1.6.6.2 
07/29 12:35:37.522000 0x9944 UTL  dataDir:                C:/TDengine/data
07/29 12:35:37.522000 0x9944 UTL ==================================
07/29 12:36:13.624000 0x13360 ERROR TSC 0000000001026090 reach the max retry:8, code:29
07/29 12:36:13.624000 0x9944 ERROR JNI jobj:000000000316B9A8, conn:0000000000000000, connect to database failed, host=隐去, user=root, dbname=test, port=6030

**Comment by Shawshank-Smile** [comment]
Should be an application problem, refer to the sample code in the installation package。
