### ISSUE TITLE
多子表查询数会出现已删除的数据

### ISSUE THREAD

**Issue by Miracle1003** [taosdata/TDengine#27937]
执行完删除操作后，进行单子表查询的时候不会出现已删除数据，但是当通过超级表查询多子表的时候会出现已经删除过的数据。
超级表vibration_ts,标签列为:data_type、sensor_id。

**Comment by Miracle1003** [comment]
无问题sql:  select * from vibration_ts where sensor_id in (821);
有问题sql:  select * from vibration_ts where sensor_id in (821,839);

**Comment by yu285** [comment]
该问题已经在最新版3.3.3.0修复，麻烦升级验证，如果验证遇到问题，请联系a1565223354
