### ISSUE TITLE
相同结果集 子表查询和超级表查询效率有明显差距

### ISSUE THREAD

**Issue by Miracle1003** [taosdata/TDengine#27938]
通过子表查询：
select * from temp_12408 where ts > '2024-09-01 00:00:00' order by ts desc;
执行时间在0.2s左右

通过超级表查询：
select * from vibration_ts  where sensor_id = 12408 and data_type = 'temp' and ts > '2024-09-01 00:00:00' order by ts desc;
执行时间在0.5s左右

如果有数据碎片，超级表查询的执行时间还会被无限拉长。
这种现象是语句问题还是本身设计如此？

**Comment by yu285** [comment]
子表才是存储数据的实体，如果通过超级表查询，需要检索到子表然后返回数据。因此本来就多出一层筛选，有性能损耗是正常的。

**Comment by Miracle1003** [comment]
如果超级表或者子表数据量增加，是否会导致执行时间差距变大
