### ISSUE TITLE
jndiconnector timezone

### ISSUE THREAD

**Issue by pope12389** [taosdata/TDengine#27942]
使用jndi连接，设置timezone GMT+8,但发现系统时区被设置成了GMT-8调试发现是 连接 器修改了系统默认时间，导致 获取当时时间与设置GMT+8不符合。这设计 上有什么考虑么？

使用的java，目前只能通过设置GMT-8。

感觉时区设置确实有点乱。

**Comment by yu285** [comment]
![image](https://github.com/user-attachments/assets/a625305e-3ecb-4311-9c2b-aaeefcbbf138)
参考文档。
