### ISSUE TITLE
rpc open too many session

### ISSUE THREAD

**Issue by ntucz** [taosdata/TDengine#27950]
tdengine版本3.0.3.2
使用rest连接方式：com.taosdata.jdbc.rs.RestfulDriver
某天突然adapter连接不上了，这个是需要做什么配置吗？
![微信图片_20240919095403](https://github.com/user-attachments/assets/970c626b-7a36-430d-8a3e-b2eb05f7d7b5)
taosadapter日志：
09/17 14:12:12.940838 03187995 TAOS_ADAPTER info "| 200 |   28.559061ms |     172.17.0.12 | POST | /rest/sql/iot " model=web req_id=0x1c7b1fe9c293aaa4
09/17 14:12:12.993625 03187995 TAOS_ADAPTER info "| 200 |   23.901715ms |     172.17.0.12 | POST | /rest/sql/iot " model=web req_id=0x1c7b1fe9c2a3aaa5
09/17 14:12:44.889810 03187995 TAOS_ADAPTER info "| 200 | 14.162578772s |     172.17.0.12 | GET | /rest/tmq " req_id=0x%!x(<nil>) model=web
09/17 14:16:41.199705 03187995 TAOS_ADAPTER info "| 200 | 12.669901532s |     172.17.0.12 | GET | /rest/tmq " req_id=0x%!x(<nil>) model=web
09/17 14:16:43.269349 03187995 TAOS_ADAPTER info "| 200 | 14.680000691s |     172.17.0.12 | GET | /rest/tmq " model=web req_id=0x%!x(<nil>)
09/17 14:16:59.085772 03187995 TAOS_ADAPTER info "| 200 | 13.640980733s |     172.17.0.12 | GET | /rest/tmq " model=web req_id=0x%!x(<nil>)
09/17 14:18:17.356959 03187995 TAOS_ADAPTER info "| 200 | 13.666776795s |     172.17.0.12 | GET | /rest/tmq " req_id=0x%!x(<nil>) model=web
09/17 14:19:41.409562 03187995 TAOS_ADAPTER error "ws error" model=restful wsType=tmq error=read tcp 11.86.15.121:6041->172.17.0.12:51084: i/o timeout
09/17 14:19:41.409633 03187995 TAOS_ADAPTER error "ws error" model=restful wsType=tmq error=write tcp 11.86.15.121:6041->172.17.0.12:51084: write: broken pipe
09/17 14:19:41.914131 03187995 TAOS_ADAPTER info "| 200 | 8m53.043379535s |     172.17.0.12 | GET | /rest/tmq " model=web req_id=0x%!x(<nil>)
09/17 14:19:43.912334 03187995 TAOS_ADAPTER error "ws error" model=restful wsType=tmq error=read tcp 11.86.15.121:6041->172.17.0.12:49262: i/o timeout
09/17 14:19:43.912423 03187995 TAOS_ADAPTER error "ws error" model=restful wsType=tmq error=write tcp 11.86.15.121:6041->172.17.0.12:49262: write: broken pipe
09/17 14:19:44.413292 03187995 TAOS_ADAPTER error "ws error" wsType=tmq model=restful error=read tcp 11.86.15.121:6041->172.17.0.12:37814: i/o timeout
09/17 14:19:44.413370 03187995 TAOS_ADAPTER error "ws error" model=restful wsType=tmq error=write tcp 11.86.15.121:6041->172.17.0.12:37814: write: broken pipe
09/17 14:19:45.418594 03187995 TAOS_ADAPTER info "| 200 | 8m56.555998258s |     172.17.0.12 | GET | /rest/tmq " model=web req_id=0x%!x(<nil>)
09/17 14:19:48.522833 03187995 TAOS_ADAPTER error "ws error" model=restful wsType=tmq error=read tcp 11.86.15.121:6041->172.17.0.12:44392: i/o timeout
09/17 14:19:48.522797 03187995 TAOS_ADAPTER error "ws error" error=write tcp 11.86.15.121:6041->172.17.0.12:44392: write: broken pipe model=restful wsType=tmq
09/17 14:19:49.529692 03187995 TAOS_ADAPTER info "| 200 | 8m21.022497265s |     172.17.0.12 | GET | /rest/tmq " req_id=0x%!x(<nil>) model=web
09/17 14:20:05.825035 03187995 TAOS_ADAPTER error "ws error" model=restful wsType=tmq error=read tcp 11.86.15.121:6041->172.17.0.12:39612: i/o timeout
09/17 14:20:05.825100 03187995 TAOS_ADAPTER error "ws error" error=write tcp 11.86.15.121:6041->172.17.0.12:39612: write: broken pipe model=restful wsType=tmq
09/17 14:20:22.855478 03187995 TAOS_ADAPTER error "" error_msg=rpc open too many session model=restful req_id=0x1c7b1fe9c023aaa1 sql=select last_row(ts) ts,

**Comment by yu285** [comment]
这个是旧版本的问题, 升级一下就可以了。

**Comment by yu285** [comment]
建议等待月底发布最新版 ，或者自己编译main 分支，参考：https://github.com/taosdata/TDengine
