### ISSUE TITLE
关于写入CPU 100%的问题

### ISSUE THREAD

**Issue by Carson-yy** [taosdata/TDengine#27989]
服务写入数据量较大，且目前是单条写入
![image](https://github.com/user-attachments/assets/00fcf61e-fcc2-47e2-8c04-95ca360ee336)

用的C库连接，版本是3.2.2.0

目前CPU很有规律的瞬时100%

集群部署，3台4核8G

有什么优化思路？

**Comment by yu285** [comment]
100%是指的单c 100% 还是4c 总共100%

**Comment by Carson-yy** [comment]
> 100%是指的单c 100% 还是4c 总共100%

4C总共100%

**Comment by Carson-yy** [comment]
> 100%是指的单c 100% 还是4c 总共100%

三个机器,集群环境总有两个在ECS云监控看,taosd进程的CPU使用可以到700-800%

**Comment by Carson-yy** [comment]
已解决
