### ISSUE TITLE
python client的connector下载链接有误

### ISSUE THREAD

**Issue by anna-mo** [taosdata/TDengine#28]
![image](https://user-images.githubusercontent.com/26948980/61194370-90e98e80-a6f3-11e9-86d6-89224db56787.png)
跳过去是这个链接：
![image](https://user-images.githubusercontent.com/26948980/61194382-a52d8b80-a6f3-11e9-9144-2123cf798a16.png)

**Comment by ohmyheartbeat** [comment]
下载链接是这个：https://www.taosdata.com/en/documentation/connector/www.taosdata.com  一个错误页面

**Comment by hzcheng** [comment]
@anna-mo 文档错误已经更正，非常感谢！ @ohmyheartbeat 感谢解答！
