### ISSUE TITLE
ERROR UTL failed to connect socket, reason: No error

### ISSUE THREAD

**Issue by jiny28** [taosdata/TDengine#2807]
问题描述：
java jdbc实现查询 select * from hlhz_3 limit 100 无问题。
但当 select * from hlhz_3 limit 1000 查询时抛错误：
07/30 08:56:43.731000 0x16856 ERROR UTL failed to connect socket, ip:192.168.113.129, port:6035, reason: No error。

taos是使用本地docker跑的， 连接时使用ip ： 127.0.0.1 .  本地内网ip 为 ： 192.168.31.28

**Comment by Aries-Lee1991** [comment]
请问版本号是？

**Comment by zyyang-taosdata** [comment]
this issue is closed by the assingnees.
