### ISSUE TITLE
python  conn.close方法没有关闭连接，程序持续运行连接数会不断上涨

### ISSUE THREAD

**Issue by sakuray** [taosdata/TDengine#28099]
**Bug Description**

**To Reproduce**
![image](https://github.com/user-attachments/assets/edc2a81a-e62c-49e3-9197-d3727e7e40e8)

**Expected Behavior**
close会清除连接

**Screenshots**
代码比较简单，就是：
获取连接数 -> connect -> 获取连接数 -> 等待3秒 -> close -> 获取连接数 -> 等待3秒 -> 再创建连接 -> 获取连接数
![image](https://github.com/user-attachments/assets/2b3ec11e-a449-482e-a223-b1eb69970b18)
上图可以看见：
connect时仅建立了一个连接
等待3秒后关闭，出现了3个连接，连接没有关掉，排查日志发现了2次心跳数据，心跳产生了新连接
再次connect创建连接，出现了4个连接

close并没有释放底层的连接，心跳等还可能产生额外连接。导致程序持续运行，客户端到服务端的连接数不断上涨

**Environment (please complete the following information):**
- client 3.0.4.1

**Additional Context**

**Comment by yu285** [comment]
请升级到最新版本的数据库 3.3.3.0 再做验证，3041是2年前的版本比较旧，和现在变化比较大。

如果新版本还有类似问题请联系微信：a15652223354
