### ISSUE TITLE
java 客户端连接setByteArray 异常

### ISSUE THREAD

**Issue by wangshiping32** [taosdata/TDengine#28105]
aarch64架构安装的taos-2.6.0.34 Java程序连接启动报错
![image](https://github.com/user-attachments/assets/b7043cfd-4b60-409a-972b-4d37297c916d)
nacos配置如下
![image](https://github.com/user-attachments/assets/f85aef30-9f2c-45f1-b63c-f5de2e303fca)

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
