### ISSUE TITLE
服务器端支持平台是否能增加国产操作系统？

### ISSUE THREAD

**Issue by foow123** [taosdata/TDengine#28103]
经测试，TDEngine在国产平台上无法运行，包括中标/银河麒麟、统信、欧拉等，请问未来是否由支持国产平台的计划？

**Comment by it512** [comment]
没理由啊， 都是linux啊

**Comment by yu285** [comment]
企业版/云服务支持，开源版目前只支持通用的linux 操作系统。https://docs.taosdata.com/reference/supported/

**Comment by yu285** [comment]
企业版/云服务支持，开源版目前只支持通用的linux 操作系统。https://docs.taosdata.com/reference/supported/

**Comment by pope12389** [comment]
国家要求要部分系统必须国产化，产品最好能计划上支持国产
