### ISSUE TITLE
RESTful连接器HTTP无响应

### ISSUE THREAD

**Issue by effun** [taosdata/TDengine#282]
我用的是.net core，因为没有合适的客户端，只能用RESTful连接器。应用程序前台通过人工交互查询数据时没有发现问题，但如果在后台运行时，数据交换的数据量会变得比较大，就偶尔会出现无响应的情况。
我用的是System.Net.Http.HttpClient，用SendAsync方法提交查询，在出现无响应时，SendAsync长时间不返回，大约10秒左右后抛出TaskCanceledException，根据其内部异常信息分析，基本可判断是超时引起的。这时再用netstate命令，可以看到有一条到服务器6020端口的连接处于TIME_WAIT状态，如果查询的频率再高点，可以看到大量的TIME_WAIT连接。
出现无响应的情况并没有什么规律，但在出现后重新调用一次就没有问题了，这种情况对于一般的读取操作并没有大影响，但对于大量实时数据的写入（最高2000+条/秒）就会是一种考验。

另外，.net core专用的连接器什么时候会有，希望这个专用的连接器会有更好的表现。

**Comment by guanshengliang** [comment]
1.C#的专有连接器暂时不会开发，但是C#通过调用taos.dll完全可连接到数据库，可以参考
```
https://www.taosdata.com/blog/2019/07/26/如何编译tdengine的windows客户端/
```
2.HTTP这几天有更新，解决了一部分连接超时的问题，github上已经提交
3.不太清楚C#中SendAsync方法的机制，但通过Go的HttpRequest没有发现问题，你可以将C#的代码贴上来或者发到slguan@taosdata.com

**Comment by effun** [comment]
我会试一下taos.dll，谢谢。

另外，整个RestfulClient我给传上来了，因为不让传CS文件，我把扩展名改成TXT了。
[RestfulClient.txt](https://github.com/taosdata/TDengine/files/3470784/RestfulClient.txt)

**Comment by effun** [comment]
抱歉我是个C++白痴，从来没接触过CMake，折腾了一天都没能编译成功。

E:\Projects\Repos\Taos\TDengine\sln>cmake .. -A x64
-- Building for: NMake Makefiles
CMake Error at CMakeLists.txt:2 (PROJECT):
  Generator

    NMake Makefiles

  does not support platform specification, but platform

    x64

  was specified.


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "E:/Projects/Repos/Taos/TDengine/sln/CMakeFiles/CMakeOutput.log".

我用的VS是2019 Community版。

不奢望大神从零指导，但求可以给个编译好的下载地址，拜谢！

**Comment by guanshengliang** [comment]
@effun 
到www.taosdata.com就可以下载windows客户端
但注意windows客户端需要与linux的服务端版本号一致
