### ISSUE TITLE
删除子表后没有释放磁盘空间

### ISSUE THREAD

**Issue by flyrun9527** [taosdata/TDengine#28225]
应该怎么才能释放磁盘空间

**Comment by flyrun9527** [comment]
COMPACT VNODES IN (vg_id1, vg_id2, ...)

 这个命令已经不给使用了吗 为什么删除 compact vnodes这个命令

**Comment by flyrun9527** [comment]
后续后开放企业版中的资源回收功能吗

**Comment by flyrun9527** [comment]
我看文件中说明| 7 | COMPACT VNODES | 暂不支持 | 整理指定VNODE的数据。3.0.0版本暂不支持。

**Comment by flyrun9527** [comment]
compact database 数据重整功能会下放到社区版本吗

**Comment by yu285** [comment]
这个暂时应该不会

**Comment by yu285** [comment]
目前只能通过keep参数释放空间。
