### ISSUE TITLE
如何在 k8s集群外部通过taosc访问tdengine集群，3节点

### ISSUE THREAD

**Issue by 1247776995** [taosdata/TDengine#28244]
Description：
   我在windows客户端使用 taos -h  <k8s宿主机 host IP> -P <nodePort> -u root -ptaosdata 无法登录tdengine,报错: Sync leader is 
   unreachable;官方的文档，其他issue里官方人员的回复都是关于fqdn解析未配置，给点参考文档都是基于宿主机部署的集群，没看到有 
   关于k8s集群的配置方法。
env： 
   3台linux宿主机，分别运行了tdengine-0,tdengine-1,tdengine-2三个POD，客户端是windows 安装了同版本的taosc。
want to know: 
   如何配置FQDN, windows，3台宿主机分别怎么配置, 以及POD内部是否需要配置什么?

**Comment by yu285** [comment]
对于K8s用户，请统一使用 restful/websocket 方式连接。
