### ISSUE TITLE
Unkown error 65535

### ISSUE THREAD

**Issue by hombooo** [taosdata/TDengine#28275]
**Bug Description**
执行业务SQL报错“Unkown error 65535”，目前只出现过一次这种情况

**To Reproduce**
客户端日志：
![cc915f148982319bde31ab68abf3c6f](https://github.com/user-attachments/assets/6b1ca75d-6ba7-4626-9482-48dd3c8419bd)

**Environment (please complete the following information):**
TDengine Version [3.2.0.0]
taos-jdbcdriver [3.2.7]

**Comment by yu285** [comment]
建议升级到最新版 3.3.3.0 ，然后再观察，过于偶发的问题，我们也很难排查。

**Comment by yu285** [comment]
如果在3330又遇到，可联系微信 a15652223354
