### ISSUE TITLE
使用 dbeaver 连接提示：failed to respond

### ISSUE THREAD

**Issue by LookFor1231** [taosdata/TDengine#28321]
本地和远程桌面版本都为 3.0.2.2. dbeaver 版本为 24.2.2. 驱动版本为今天刚下的最新的
本地创建了个数据库，可以直接连上并打开。
连接其他电脑点开表之后，提示 error,0x2318 ,failed to respond
telnet 能打开

**Comment by yu285** [comment]
驱动版本和数据库版本不匹配。

3.0.2.2 是最早起的版本，已经2年多了，和现在不兼容，请更换一下最新的3.3.3.0 版本，各方面都要好很多的版本。然后再使用最新的驱动去连接。

**Comment by yu285** [comment]
情况如何了
