### ISSUE TITLE
The combination of the NOT (NOT) operation triggers a logical bug.

### ISSUE THREAD

**Issue by LingweiKuang** [taosdata/TDengine#28335]
#### Bug Description

The combination of the **NOT (NOT)** operation triggers a logical bug.

#### To Reproduce

Assume that we execute the following statement under a database named **testdb**.

```
DROP TABLE IF EXISTS t1;

CREATE TABLE t1( time TIMESTAMP, c0 BIGINT);
INSERT INTO t1(time, c0) VALUES (1641024000000, 1);

# query statement
SELECT time, c0 FROM t1 WHERE NOT (NOT (1 == 1));
```

#### Expected Behavior

The above query statement should be able to retrieve all the data.

#### Actual behaviour

The above query did not return any data and did not report any errors.

#### Environment

- OS：Ubuntu Server 22.04 LTS 64bit
- TDengine Version：3.3.3.0

#### Additional Context

Hello, TDengine team. I'd like to confirm with you whether this is a **logical bug**?

**Comment by yu285** [comment]
let me check on this .

**Comment by yu285** [comment]
<img width="1008" alt="image" src="https://github.com/user-attachments/assets/bba9fd95-d15c-42a6-b673-16f12e325b38">
it seems okay  in the new version .

**Comment by LingweiKuang** [comment]
Thanks for fixing this! Good Job!
