### ISSUE TITLE
2.6.0.34版本 查询语句where条件使用按位与查询，内存一直增加不降

### ISSUE THREAD

**Issue by myloveanddog** [taosdata/TDengine#28364]
比如sql语句select * from test_table where (test_col & 128) = 128 order by ts desc limit 1; 这中带& 的会一直增加内存且不降
这种问题有什么解决办法吗？

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
