### ISSUE TITLE
使用DROP TABLE IF EXISTS 指定子表语句删除大量子表时效率极低

### ISSUE THREAD

**Issue by stormbirds** [taosdata/TDengine#28384]
TDengine 版本为 
TDengine Community Edition
taos version: 3.3.2.0
参数配置如下
| name | create_time | vgroups | ntables | replica | strict | duration | keep | buffer | pagesize | pages | minrows | maxrows | comp | precision | status | retentions | single_stable | cachemodel | cachesize | wal_level | wal_fsync_period | wal_retention_period | wal_retention_size | stt_trigger | table_prefix | table_suffix | tsdb_pagesize | keep_time_offset | s3_chunksize | s3_keeplocal | s3_compact | with_arbitrator | encrypt_algorithm |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| XXX | 2024-07-24 17:10:42.734 | 2 | 73660 | 3 | on | 14400m | 5256000m,5256000m,5256000m | 32 | 4 | 256 | 100 | 4096 | 2 | ms | ready | NULL | false | both | 1 | 1 | 3000 | 3600 | 0 | 1 | 0 | 0 | 4 | 0 | 262144 | 5256000m | 0 | 0 | none |

机器配置为 3台 4核 4G内存 主机组成的集群，系统为 Ubuntu 24.04 LTS
有14个超级表，7w左右子表，数据量大约两亿条，当使用DROP TABLE IF EXISTS语句删除大量表时，效率特别慢，删除7W张表大约跑了30分钟左右仍然没有执行完成，后来只能通过删除超级表整个清空来实现（删除超级表相对反应比较快），但是需求是需要保留部分仍然需要的表的数据，只删除不需要的表，因此不能直接使用删除超级表的方法。在此集群上尝试使用taosBenchmark 压测写入性能正常。
所以TDengine删除表的性能本身就是这么慢还是配置问题？

**Comment by yu285** [comment]
大批量删表多出自测试场景，并非用户常见场景。目前并没有参数控制。

可以使用多vgroups 增加并行度，这样删表的速度会有显著增长。

除此之外，没有性能优化空间，可以理解为性能大概如此。
