### ISSUE TITLE
阅读官方帮助文档时，发现一处文档sql语法错误

### ISSUE THREAD

**Issue by zudajun** [taosdata/TDengine#28381]
![下载](https://github.com/user-attachments/assets/c36c24f0-0b0a-4fb0-8804-af0febd302b5)

https://docs.taosdata.com/basic/insert
v3.0文档
基础功能-数据写入-通过超级表写入，sql样例：
insert into meters (tbname, ts, current, voltage, phase, location, group_id)
values( "d1001v, "2018-10-03 14:38:05", 10.2, 220, 0.23, "California.SanFrancisco", 2)

上面这段sql样例存在语法错误，正确的应该是：
insert into meters (tbname, ts, current, voltage, phase, location, group_id)
values( "d1001", "2018-10-03 14:38:05", 10.2, 220, 0.23, "California.SanFrancisco", 2)

"d1001v 应该是  "d1001"

**Comment by yu285** [comment]
收到，我们修改一下。感谢反馈
