### ISSUE TITLE
can taos only connect to the mnode

### ISSUE THREAD

**Issue by iwanlebron** [taosdata/TDengine#28420]
![image](https://github.com/user-attachments/assets/f6ad7645-6a63-4d91-851f-e1f19f423b3c)
As shown in the figure, when using other servers to connect to the TDEngine cluster, if the connected node is not mnode, an error will be reported

**Comment by iwanlebron** [comment]
ny-wlw-0009.novalocal  mnode
ny-wlw-0010.novalocal  dnode
ny-wlw-0011.novalocal  dnode
the client of taos is ny-wlw-0016.novalocal

**Comment by yu285** [comment]
can you show us the hosts file in your client server?

**Comment by iwanlebron** [comment]
sure 
![image](https://github.com/user-attachments/assets/b5115217-abbd-4634-9bb9-4d0065ca665f)

**Comment by yu285** [comment]
all the taosd process has been stared ,right ?

and you can connect to TDengine from  these three servers?

ny-wlw-0009.novalocal mnode
ny-wlw-0010.novalocal dnode
ny-wlw-0011.novalocal dnode

**Comment by iwanlebron** [comment]
yes

**Comment by iwanlebron** [comment]
no
![image](https://github.com/user-attachments/assets/7ba431e7-7c42-4126-9440-d8228c4562bd)

**Comment by iwanlebron** [comment]
Can only connect to ny-wlw-0009.novalocal mnode

**Comment by yu285** [comment]
can you make sure all the hosts information recorded uniformly  in all  servers ? 

like:

ip1  ny-wlw-0009.novalocal
ip2  ny-wlw-0010.novalocal
ip3  ny-wlw-0011.novalocal 

you should put them in all the database server.

**Comment by iwanlebron** [comment]
yes, sure

**Comment by iwanlebron** [comment]
yes, sure

**Comment by iwanlebron** [comment]
Yes, confirm, otherwise the cluster cannot be built
