### ISSUE TITLE
错误连接数据库 [test] : org.pentaho.di.core.exception.KettleDatabaseException:  Error occured while trying to connect to the database  Error connecting to database: (using class com.taosdata.jdbc.TSDBDriver) Could not initialize class com.taosdata.jdbc.TSDBJNIConnector

### ISSUE THREAD

**Issue by hhhyb** [taosdata/TDengine#285]
抱这个错是什么原因

**Comment by hhhyb** [comment]
taos-jdbcdriver-1.0.0-dist.jar这个驱动类我导了，我看文档是因为没有taos.dll文件吗，如果是因为这个从哪里找这个文件，因为我是用另一个工具配置连接数据库，能否给一个下载taos.dll文件的地址

**Comment by hzcheng** [comment]
dll可在官网[快速上手](https://www.taosdata.com/cn/getting-started/)下载

**Comment by hhhyb** [comment]
好的。谢谢


------------------ 原始邮件 ------------------
发件人: "hzcheng"<notifications@github.com>;
发送时间: 2019年8月7日(星期三) 中午11:47
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
抄送: "拥抱."<1396988252@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [taosdata/TDengine] 错误连接数据库 [test] : org.pentaho.di.core.exception.KettleDatabaseException:  Error occured while trying to connect to the database  Error connecting to database: (using class com.taosdata.jdbc.TSDBDriver) Could not initialize class com.taosdata.jdbc.TSDBJNIConnector (#285)




dll可在官网快速上手下载

**Comment by hhhyb** [comment]
我测试连接使用的是Kittle工具，在配置的地方配置url，jdbc:TAOS://192.168.14.86:10665/dm，然后配置驱动类com.taosdata.jdbc.TSDBDriver，然后用户名root，密码taosdata。其中ip地址是我在Linux上安装的TDengine的show connections；出来的ip地址。
然后我在我的这个工具里面导入了taos-jdbcdriver-1.0.0-dist.jar包。就一直报下面这个错，能看看是什么原因吗？

错误连接数据库 [TEST] : org.pentaho.di.core.exception.KettleDatabaseException: 
Error occured while trying to connect to the database

Error connecting to database: (using class com.taosdata.jdbc.TSDBDriver)
Could not initialize class com.taosdata.jdbc.TSDBJNIConnector


org.pentaho.di.core.exception.KettleDatabaseException: 
Error occured while trying to connect to the database

Error connecting to database: (using class com.taosdata.jdbc.TSDBDriver)
Could not initialize class com.taosdata.jdbc.TSDBJNIConnector

**Comment by hzcheng** [comment]
我们目前没有跟该工具适配过，具体什么原因我们会查看下，不过需要一些时间。您可以先将/var/log/taos目录打包发我们：hzcheng@taosdata.com. 我们可以先看一下日志

**Comment by hhhyb** [comment]
好的，您先看看




------------------ 原始邮件 ------------------
发件人: "hzcheng"<notifications@github.com>;
发送时间: 2019年8月7日(星期三) 晚上6:09
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
抄送: "拥抱."<1396988252@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [taosdata/TDengine] 错误连接数据库 [test] : org.pentaho.di.core.exception.KettleDatabaseException:  Error occured while trying to connect to the database  Error connecting to database: (using class com.taosdata.jdbc.TSDBDriver) Could not initialize class com.taosdata.jdbc.TSDBJNIConnector (#285)




我们目前没有跟该工具适配过，具体什么原因我们会查看下，不过需要一些时间。您可以先将/var/log/taos目录打包发我们：hzcheng@taosdata.com. 我们可以先看一下日志
