### ISSUE TITLE
PL/SQL support by TDengine

### ISSUE THREAD

**Issue by wgong** [taosdata/TDengine#28520]
As someone with extensive Oracle background, I believe PL/SQL support would be a significant enhancement to TDengine's capabilities, particularly due to its superior performance compared to language-specific UDFs. I'd like to present a specific use case from financial services to illustrate the value:

Currently, we use the [Python TA-Lib library](https://github.com/TA-Lib/ta-lib-python) for End-of-Day stock analysis. While this works well for daily data, we see an opportunity to leverage TDengine for high-performance intraday trading analysis across hundreds or thousands of stocks in near real-time. The [C implementation of TA-Lib](https://github.com/TA-Lib) would be ideal for this purpose.

I have two specific questions:

1) In the absence of full PL/SQL support, what would be the recommended approach to integrate C-library functions (like TA-Lib) as custom SQL functions in TDengine?
2) Has similar integration work been done before? If so, could you share the architectural approach and implementation examples?

As TDengine is open-source, the community could potentially contribute to this implementation, given proper technical guidance from your team.

**Comment by yu285** [comment]
hi sorry for delay response . May I know this first :

what is the relationship between PL/SQL and  TA-Lib ?

can you share the most typical business application scenario that they work together?

**Comment by yu285** [comment]
close this issue  temporarily ， until get response from you.
