### ISSUE TITLE
3.3.0版本订阅数据库主题的topic的时候没有返回表和标签等信息

### ISSUE THREAD

**Issue by xiaobao16** [taosdata/TDengine#28564]
如题所示，这边创建了一个数据库主题的TOPIC，使用原生的方式进行数据订阅，在数据插入后返回的订阅的内容中只有基础的值的信息，缺少我插入数据的表信息以及标签信息（该表是基于某超级表创建的）
topic_power（数据库主题）：create topic if not exists topic_power as database power
![image](https://github.com/user-attachments/assets/3c199e55-d36f-48c1-86a5-96de6b59245e)
![image](https://github.com/user-attachments/assets/c9310440-06ad-4a92-ae69-f392fa5d39e1)
insert语句如下
![image](https://github.com/user-attachments/assets/3267d8e0-021f-47f8-85f7-3d6b6b976373)

**Comment by yu285** [comment]
JDBC目前还不能完整支持使用库订阅，后续我们会调整一下这里的行为。
![img_v3_02gc_8cdf6679-7987-4f81-9288-89ef79d2d44g](https://github.com/user-attachments/assets/20e1b5c3-f033-4f02-ad65-cd6a94888600)
