### ISSUE TITLE
3.0.1.0 集群出现数据文件损坏

### ISSUE THREAD

**Issue by c1105590204** [taosdata/TDengine#28676]
**Bug Description**
使用3.0.1.0部署的3节点集群，其中一个节点挂掉，目前无法启动

**To Reproduce**

**Expected Behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/b100af9f-6dbf-4e5a-8e04-e9e1b762a742)

**Environment (please complete the following information):**
 - OS: Kylin-Server-V10-SP3-AARCH64
 - Memory 64G, CPU  16C
 - TDengine Version 3.0.1.0

**Additional Context**
这个节点挂掉之后，systemctl启动失败，而且日志文件没有日志（只有new log file，没有其他输出），然后直接使用taosd启动，就可以看到控制台上如图的错误

**Comment by yu285** [comment]
是多副本还是单副本。

**Comment by c1105590204** [comment]
> 是多副本还是单副本。

单副本

**Comment by yu285** [comment]
3.0.1.0 是3.x 系列2年多前的最早的版本，和现在区别较大，单副本如果有备份的话，可以恢复一下，然后把数据尽早迁移出来导入 3.3.3.0。

3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.3.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.3.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/

**Comment by yu285** [comment]
仍有疑问可以添加微信 a15652223354 做具体沟通
