### ISSUE TITLE
stream目录磁盘空间占用高

### ISSUE THREAD

**Issue by zhuangQingGuang** [taosdata/TDengine#28741]
版本3.3.3
一共24条流计算，SQL都差不多，如下
` create stream hr_stream24 into s_t_1669_compressor_current_2 subtable(concat('new_', tname)) as select _wstart, _wend, (avg(`value`) * 220 * 600) energy from d_1669_compressor_current_2 partition by tbname tname interval(10m);`
才运行了4个月不到，vnode下stream目录已经生成100G的文件，是否正常，如何优化

**Comment by yu285** [comment]
麻烦截图一下该目录下的明细：

**Comment by zhuangQingGuang** [comment]
> 麻烦截图一下该目录下的明细：

![微信截图_20241126142510](https://github.com/user-attachments/assets/12cf3d0e-394f-4c53-8755-71d6bfcc01c4)
![微信截图_20241126142212](https://github.com/user-attachments/assets/99c1db63-e3ae-4ace-9657-f9f969f39909)

**Comment by yu285** [comment]
收到。

**Comment by yu285** [comment]
本身由于你的流计算比较多，任务也多，所以计算量比较大，在中间状态中可能会有这么大的空间占用。
 目前的空间是什么情况了？有释放吗？

**Comment by zhuangQingGuang** [comment]
> 本身由于你的流计算比较多，任务也多，所以计算量比较大，在中间状态中可能会有这么大的空间占用。 目前的空间是什么情况了？有释放吗？

最近升级版本 我把流计算删掉了 删了好像也没有释放空间   意思是用DELETE_MARK释放空间吗

**Comment by yu285** [comment]
https://docs.taosdata.com/advanced/stream/#%E6%B5%81%E8%AE%A1%E7%AE%97%E5%8D%87%E7%BA%A7%E6%95%85%E9%9A%9C%E6%81%A2%E5%A4%8D

请按照这个操作来清理流。

这个流文件的删除是流自己控制的。


请在最新版本再观察

**Comment by yu285** [comment]
请问有变化吗

**Comment by zhuangQingGuang** [comment]
> 请问有变化吗

评估换成代码实现计算逻辑了 暂时没法观察了
