### ISSUE TITLE
taosd数据库后台，连接了一个公网服务器的80端口

### ISSUE THREAD

**Issue by liujiangithub** [taosdata/TDengine#28821]
运行中的某台服务器，查看tcp连接的时候，发现自动连接了一个公网ip20.124.239.6的80端口

**Screenshots**
![企业微信截图_17319998481390](https://github.com/user-attachments/assets/ef437863-9405-4bdb-843b-78f5128fdc26)

**Environment (please complete the following information):**
 - OS:  ubuntu18.04
 - Memory, CPU, current Disk Space(无关紧要)
 - TDengine Version 3.3.1.0

网站上查询该IP是美国tdengine官网 请问为什么要连，是否存在安全隐患？是否有办法关闭

**Comment by yu285** [comment]
您好, 这个连接只会上报不涉及任何用户数据的最基本信息，用于官方了解产品在世界范围内的分布情况，进而优化产品，提升用户体验，具体采集项目为：集群名、操作系统版本、cpu信息。

该特性为可选配置项，在开源版中默认开启，具体参数为 telemetryReporting , 在官方文档中有做说明，具体链接如下：

https://docs.taosdata.com/reference/components/taosd/#%E7%9B%91%E6%8E%A7%E7%9B%B8%E5%85%B3

您可以随时关闭该参数，只需要在taos.cfg 中修改telemetryReporting为 0，然后重启数据库服务即可。

代码位于:https://github.com/taosdata/TDengine/blob/62e609c558deb764a37d1a01ba84bc35115a85a4/source/dnode/mnode/impl/src/mndTelem.c#L137

此外，对于安全性要求极高的企业版 TDengine Enterprise 来说，此参数不会工作。

**Comment by yu285** [comment]
另外咱们是初次安装 TDengine 吗？还有遇到其他的任何使用问题吗？

**Comment by liujiangithub** [comment]
> 另外咱们是初次安装 TDengine 吗？还有遇到其他的任何使用问题吗？

不是初次安装，只是以前没有注意到这个问题。

**Comment by yu285** [comment]
好的，我们已经在官网FAQ 上补充了您的这个问题的答复，感谢使用。
