### ISSUE TITLE
V3.3.0.3 DB error: Func not exists

### ISSUE THREAD

**Issue by springbootyp** [taosdata/TDengine#28820]
**Bug Description**
无法使用SUBSTRING_INDEX函数、CAST函数
使用TDengine版本为：3.3.0.3

![image](https://github.com/user-attachments/assets/96ce28df-fd7f-479b-ba9f-acf17fc6996a)

**Comment by yu285** [comment]
这个是版本问题，升级到最新的 3.3.4.3 即可。
