### ISSUE TITLE
Timestamp out of range

### ISSUE THREAD

**Issue by 1ess** [taosdata/TDengine#2884]
8月16日可以插入，8月17日就不能插入了
![image](https://user-images.githubusercontent.com/36092926/89139901-c2d5c900-d572-11ea-99b2-921b1b62564f.png)

 - OS: CentOS 7.0
 - TDengine Version 1.6.6.0

**Comment by Aries-Lee1991** [comment]
版本已经更新到2.0.0.0了，请升级到最新版本在使用。
