### ISSUE TITLE
Rocky 9 安装 版本 3.3.4.3 ，taosd 启动不成功

### ISSUE THREAD

**Issue by qwretee** [taosdata/TDengine#28888]
11/22 10:47:32.818320 00002030 C DND dnode file:/var/lib/taos//dnode/dnode.json not exist
11/22 10:47:32.818701 00002030 C DND mnode file:/var/lib/taos//mnode/mnode.json not exist, reason:No such file or directory
11/22 10:47:32.818749 00002030 C DND deploy mnode required. dnodeId:0<=0, clusterId:0<=0, localEp:rockyhost1:6030==firstEp
11/22 10:47:32.818797 00002030 C DND file:/var/lib/taos//qnode/qnode.json not exist
11/22 10:47:32.818846 00002030 C DND file:/var/lib/taos//snode/snode.json not exist
11/22 10:47:32.819250 00002030 C DND ERROR failed to init module at line 566 since Not found
11/22 10:47:32.819339 00002030 C DND ERROR failed to create dnode since Not found
11/22 10:47:32.819393 00002030 C DND ERROR failed to init dnode since unsupported platform, please visit https://www.taosdata.com for support

我的 配置  [root@rockyhost1 TDengine-server-3.3.4.3]# uname -a
Linux rockyhost1 5.14.0-427.22.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jun 19 17:35:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
无论是 rmp还是 tar 都是一样的

**Comment by yu285** [comment]
3.x 开源版操作系统支持范围参考：https://docs.taosdata.com/reference/supported/

最好更换一下服务器，如果不方便可以使用docker ，具体安装/使用方式可以参考官方文档。
