### ISSUE TITLE
c++连接，聚合函数（avg，sum）查询得到结果为0或接近0的值

### ISSUE THREAD

**Issue by panicwq** [taosdata/TDengine#28882]
版本3.0.5.1社区版本 win
在taos shell中一样的查询语句能查到对的平均值。
用C++连接taos，得到为0，但是其他普通查询可以得到正确数值，max()和min()也正确，只有avg()【聚合函数，测试sum（）也为0，或者时很接近0的数】提取数值总是0。

关键代码：
` 	
QString data = QString("SELECT avg(fyfkqxz_yc02) as fyfkqxz_yc02_avg FROM tsdb.ycmain WHERE TIMEDIFF(ts,NOW)<120000 and ts<=NOW");

	TAOS_RES* result = taos_query(taosCon, data.toUtf8().data());
	
	TAOS_ROW    row = NULL;
	
	int         num_fields = taos_field_count(result);
	TAOS_FIELD* fields = taos_fetch_fields(result);

	fprintf(stdout, "query successfully, got %d fields, the sql is: %s.\n", num_fields, data.toUtf8().data());

	while ((row = taos_fetch_row(result)))
	{
		if (num_fields > 0)
		{
			auto colname = fields[0].name;
			QString colN = colname;
			float statdata = *(float*)(row[0]);//0
			qDebug() << colN << statdata;
		}
	}
	taos_free_result(result);
`

taos shell中同样的语句查询正确
![image](https://github.com/user-attachments/assets/79fc18a4-2651-4486-b2d5-547710b911e0)

**Comment by yu285** [comment]
3071 后没有windows版本也没有官方支持，所以windows版本没办法长期使用，建议先切换到linux版本 或者docker（当前最新版为 3.3.4.3 ） 再做后续调试。

**Comment by yu285** [comment]
如果在新版本有任何问题可以随时联系我们，微信：a15652223354
