### ISSUE TITLE
Error in packaging/tools/get_version.sh make build fail

### ISSUE THREAD

**Issue by DianaZhao** [taosdata/TDengine#2888]
**Bug Description**
There are chars ^M at every line end in the file packaging/tools/get_version.sh to make it fail to run, while build TDengine using cmake. I remove these chars manually then can build mormally. 
**To Reproduce**
1. follow the readme to build TDengine, while run cmake .. && cmake --build .

**Expected Behavior**
build success

**Environment (please complete the following information):**
 - OS: [Debian 10.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [develop head]

make_install.sh also has that problem. there may be other files has the same problem.

![image](https://user-images.githubusercontent.com/961024/89145695-2caa9e80-d584-11ea-9206-2099e1dc2438.png)

**Comment by Aries-Lee1991** [comment]
Please attach the environment information.

**Comment by Aries-Lee1991** [comment]
您好，这个问题已经过去20天了，想问下还存在这个问题吗？如果有的话，请附上具体信息：版本、环境、操作步骤。谢谢。
