### ISSUE TITLE
RESTful 的 “metric meta expired”

### ISSUE THREAD

**Issue by godatabus** [taosdata/TDengine#289]
由于 cgo在 windows需要配置编译环境，所以用了RESTful  API。
今天遇到了{"status":"error","code":63,"desc":"metric meta expired"}的问题。像语句“SELECT COUNT(*)   FROM test.IPCHistoryInfo WHERE ClassID < 1200”，在 taos命令行下能正常返回（服务器为ubuntu），在RESTful  API下，包括命令行 curl 里，都出同样的问题。如果是先插入了100多条数据然后执行，则百分百出现。

**Comment by hzcheng** [comment]
您好，这是由于server端内嵌的客户端内的元数据暂时没有更新。这是一个bug，我们正在解决它。为了避开这个问题，您可以暂时先重启下服务端。
