### ISSUE TITLE
The logic of assigning BOOL values is inconsistent between the IN operation and equality comparisons.

### ISSUE THREAD

**Issue by LingweiKuang** [taosdata/TDengine#28901]
#### Bug Description

The logic of assigning BOOL values is inconsistent between the **IN** operation and equality comparisons.

#### To Reproduce

Assume that we execute the following statement under a database named **testdb**.

```
DROP TABLE IF EXISTS t1;
CREATE TABLE t1(time TIMESTAMP, c1 BIGINT);
INSERT INTO t1(time, c1) VALUES (1641024000000, 1);

# query 1
SELECT c1 FROM t1 WHERE TRUE = 2;

# query 2
SELECT c1 FROM t1 WHERE TRUE in (2);
```

#### Expected Behavior

Query 1 returned result set: **empty set**

Query 2 returned result set: **empty set**

#### Actual behaviour

Query 1 returned result set: **empty set**

Query 2 returned result set: **1**

#### Environment

- OS：Ubuntu Server 22.04 LTS 64bit
- TDengine Version：**3.3.4.3**

#### Additional Context

Hello, TDengine team. In Query 1, **TRUE** is implicitly converted to the numeric value **1** and compared with the numeric value **2**. However, in Query 2, **TRUE** is implicitly converted to any non-zero numeric value. Theoretically, there should be no difference between the two in a database management system, as this could lead to user confusion.

**Comment by LingweiKuang** [comment]
![The logic of assigning BOOL values is inconsistent between the IN operation and equality comparisons](https://github.com/user-attachments/assets/b38ecb3b-870f-4bfa-bb03-09ec5c18a5e1)

**Comment by yu285** [comment]
![image](https://github.com/user-attachments/assets/978e31f9-82df-4e50-9d9e-0b6c8d8674ef)
