### ISSUE TITLE
创建表名为大写时，创建成功，但是后续操作会出错

### ISSUE THREAD

**Issue by gfxm301** [taosdata/TDengine#28905]
taos> show tables;
           table_name           |
=================================
 event                          |
 Receiver3                      |
 log                            |
 Receiver1                      |
 Receiver2                      |
Query OK, 5 row(s) in set (0.002211s)

taos> drop table Receiver1;

DB error: Table does not exist (0.001239s)
taos> drop table 'Receiver1';

DB error: syntax error near "'Receiver1';" (0.000148s)
taos> drop table receiver1;

DB error: Table does not exist (0.001066s)
taos> drop table "receiver1";

DB error: syntax error near ""receiver1";" (0.000054s)
taos> drop table "Receiver1";

DB error: syntax error near ""Receiver1";" (0.000067s)
taos> show stables;
          stable_name           |
=================================
 Receiver                       |
Query OK, 1 row(s) in set (0.001048s)

taos> drop stable Receiver;

DB error: STable not exist (0.000392s)
taos> drop stable 'Receiver';

DB error: syntax error near "'Receiver';" (0.000056s)
taos> drop stable receiver;

DB error: STable not exist (0.000370s)
taos> show stables;
          stable_name           |
=================================
 Receiver                       |
Query OK, 1 row(s) in set (0.001179s)

taos> DROP STABLE Receiver;

DB error: STable not exist (0.000393s)
taos> DROP STABLE Receiver;

DB error: STable not exist (0.000368s)
taos> DROP STABLE "Receiver";

DB error: syntax error near ""Receiver";" (0.000053s)
taos> SELECT * FROM Receiver LIMIT 1;

DB error: Fail to get table info, error: Table does not exist (0.001301s)
taos> CREATE STABLE IF NOT EXISTS ops.`Receiver`  (ts timestamp,attitude VARCHAR(32),tempetature1 VARCHAR(32),tempetature2 VARCHAR(32),tempetature3 VARCHAR(32)) TAGS (location nchar(32),`user` nchar(32))
;
Create OK, 0 row(s) affected (0.000552s)

taos> show stables;
          stable_name           |
=================================
 Receiver                       |
Query OK, 1 row(s) in set (0.001061s)

taos> drop stable 'Receiver';

DB error: syntax error near "'Receiver';" (0.000062s)
taos> DROP STABLE Receiver;

DB error: STable not exist (0.000487s)
taos> show tables;
           table_name           |
=================================
 event                          |
 Receiver3                      |
 log                            |
 Receiver1                      |
 Receiver2                      |
Query OK, 5 row(s) in set (0.001730s)

taos> CREATE TABLE IF NOT EXISTS ops.`Receiver4` USING ops.`Receiver` TAGS ('jw','hdu');
Create OK, 0 row(s) affected (0.001243s)

taos> show tables;
           table_name           |
=================================
 Receiver4                      |
 event                          |
 Receiver3                      |
 log                            |
 Receiver1                      |
 Receiver2                      |
Query OK, 6 row(s) in set (0.001849s)

taos> drop table Receiver;

DB error: Table does not exist (0.001108s)
taos> drop table Receiver1;

DB error: Table does not exist (0.001267s)
taos> drop table Receiver4;

DB error: Table does not exist (0.001402s)
taos> drop table 'Receiver4';

DB error: syntax error near "'Receiver4';" (0.000066s)
taos> drop table ops.'Receiver4';

DB error: syntax error near "'Receiver4';" (0.000056s)
taos> drop table ops.Receiver4;

DB error: Table does not exist (0.001274s)
taos> INSERT INTO ops.'Receiver1' VALUES (NOW, 1.88,37,38,39);
Insert OK, 1 row(s) affected (0.000947s)

taos> select * from ops.'Receiver1';

DB error: syntax error near "'Receiver1';" (0.000074s)
taos> 
![Uploading image.png…]()
![Uploading image (1).png…]()

**Comment by yu285** [comment]
使用反引号转役 `Receiver4 `

https://docs.taosdata.com/reference/taos-sql/escape/#%E8%BD%AC%E4%B9%89%E5%AD%97%E7%AC%A6%E8%A1%A8
