### ISSUE TITLE
Tdengine V3.3.0.3 创建好超级表后，无法保存部分Tag数据

### ISSUE THREAD

**Issue by springbootyp** [taosdata/TDengine#28914]
status和battery_level  为什么没有值？ 还请问下如何查询超级表下的子表数量和数据总量？
![1cc849bf6ca74fe2000da5260fd1c66](https://github.com/user-attachments/assets/cb56c295-7848-4bd1-ad47-1a9f6ad784e6)
![ea48a7e267a9bea8e9ece481e1aa893](https://github.com/user-attachments/assets/1304171c-9750-4d26-a216-afa4297f2216)

**Comment by springbootyp** [comment]
升级V3.3.4.3 版本还是一样的结果，如图
![Uploading image.png…]()

**Comment by yu285** [comment]
tag 值修改方式：

![image](https://github.com/user-attachments/assets/28f915a0-d78e-4e0b-9cc3-3d9bd1d93fe8)

**Comment by springbootyp** [comment]
> tag 值修改方式：
> 
> ![image](https://private-user-images.githubusercontent.com/74105241/389409749-28f915a0-d78e-4e0b-9cc3-3d9bd1d93fe8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MTgwODgsIm5iZiI6MTczMjUxNzc4OCwicGF0aCI6Ii83NDEwNTI0MS8zODk0MDk3NDktMjhmOTE1YTAtZDc4ZS00ZTBiLTljYzMtM2Q5YmQxZDkzZmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA2NTYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZGU2MzcwMmI1NDVkYjUzNWNhMDdlOGE1YzIzYWYyNmE0MmZhZDQzM2QzNWFiNzIzOTliNDQxNDA3ZGI4NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AlaHfJ0FgTGz_NNDBbsdYzWw63EiTfcmzchAmvyLTm0)

我通过超级表进行插入，是无法获取到值，我创建超级表结构是有Tag字段？我如何通过插入的方式
