### ISSUE TITLE
使用字符串函数 REPLACE 时提示语法错误

### ISSUE THREAD

**Issue by gonvee** [taosdata/TDengine#28930]
**Bug Description**

按照[官方文档](https://docs.taosdata.com/reference/taos-sql/function/#replace)示例使用`REPLACE`函数时提示语法错误。

```sh
taos> select replace('aabbccAABBCC', 'AA', 'DD');

DB error: syntax error near "replace('aabbccAABBCC', 'AA', 'DD');" (0.000269s)
```
**Environment (please complete the following information):**
 - OS: Ubuntu22.04
 - TDengine Version: 3.3.2.0

**Comment by yu285** [comment]
这是 3.3.3.0 支持的函数，直接升级到最新版 3.3.4.3 吧，各方面体验都更好
