### ISSUE TITLE
tdenigne创建超级表或子表命名是否支持点号"."

### ISSUE THREAD

**Issue by yongweizhao** [taosdata/TDengine#28938]
用的版本是3.0.2，测试了下，使用转义字符 ` 时，字段名可以带点号，如`a.b.c`，能够创建成功，
![image](https://github.com/user-attachments/assets/4bd47327-17c1-45c9-9b74-b78c3135856b)
；但是超级表和子表创建时不能带点号，报错：DB error: The table name cannot contain '.'。请问哪个版本的td支持点号，该需求在电力行业较为普遍，希望后续版本能够支持。

**Comment by yu285** [comment]
这个确实不支持，也不好支持，我们之前内部有过沟通讨论。

如果需求特别强，只能通过企业版定制进行商务沟通，看看能不能有开发可行性。
