### ISSUE TITLE
a question about left join and group by

### ISSUE THREAD

**Issue by stonesummer** [taosdata/TDengine#28954]
i write  this sql 

![image](https://github.com/user-attachments/assets/e2e79ebc-0ea9-42e3-b74d-36678fe45a79)

but the result is error : **Join requires valid time series input**

what should i do ?please ,thank you

**Comment by yu285** [comment]
time series input must be in  the "on" clause , like :        "on t3.ts= t1.ts and t3.sensorno = t1.sensorno ."
