### ISSUE TITLE
C# TDengine.FetchRows no data return

### ISSUE THREAD

**Issue by zhijun0451** [taosdata/TDengine#2897]
1.6.6.0 用官方提供的DLL C#引用读取数据在第二次调用TDengine.FetchRows函数的时候没有返回数据，返回值是0并且Error报的是成功，这个函数是有什么机制吗？

**Comment by liuyq-617** [comment]
嗯，目前是不支持执行两次这个函数的。这个执行的时候，是从服务器的内存空间读取一块数据，执行完成之后，这段内存就可以被其他查询复写了，所以不能这样来使用
