### ISSUE TITLE
升级3.3.4.3后，节点一直重启（每3分钟一次）

### ISSUE THREAD

**Issue by Yuecz** [taosdata/TDengine#28995]
问题：升级3.3.4.3后，节点每三分钟重启一次
重启前日志报错截图：
![image](https://github.com/user-attachments/assets/6585e8bd-c5c1-481e-a943-88585d1fce18)
相关消费者都已offline，对应主题也已删除
期望：解决该问题

**Comment by yu285** [comment]
麻烦提供一下完整日志吧

**Comment by yu285** [comment]
taosdlog

**Comment by Yuecz** [comment]
@yu285 日志如下，周期三分钟会进行重启
[taosdlog.0.gz](https://github.com/user-attachments/files/17971825/taosdlog.0.gz)
