### ISSUE TITLE
I got an error in make install

### ISSUE THREAD

**Issue by wty9391** [taosdata/TDengine#29]
I have built successfully.
I can run the TDengine server and client via
`./build/bin/taosd -c test/cfg` 
and 
`./build/bin/taos -c test/cfg`.
But when I try to `make install` or `sudo make install`, it told me 
```bash
bala bala......
Start to update TDEngine...
Removing any system startup links for /etc/init.d/taosd ...
cp: cannot stat ‘/home/wty/sda2/TDengine/packaging/tools/../rpm/init.d/taosd’: No such file or directory
update-rc.d: /etc/init.d/taosd: file does not exist
```
and failed.

I try to launch the TDengine in a vmware virual machine (Ubuntu 14.04), so I do not have much free space for it.
I have 10GB free space for the system root directory and I try to install the TDengine in another disk which has 5GB free space.

I can start up server via `sudo taosd`. But I don't known whether the fialling `make install ` makes difference.

**Comment by hzcheng** [comment]
The problem is solved. Thanks for reporting.
