### ISSUE TITLE
Data loss prevention mechanism

### ISSUE THREAD

**Issue by techengines** [taosdata/TDengine#290]
Hi there, thanks for the open-sourced project. A few questions below for further understanding your system:

1. what mechanism does tdengine implement to prevent data loss? 
2. is data redundancy reinforced anyhow?
3. in case which entity is responsible for data replication/synchronization and load balancing among data copies holders?
4. Any failure recovery strategy other than log-ahead and backup?

Look forward to your kind replies. 
Thanks

**Comment by kakopappa** [comment]
I am also interested in how to take backups

**Comment by sangshuduo** [comment]
We use WAL to provent data loss.
