### ISSUE TITLE
grafana can't get data from taosd

### ISSUE THREAD

**Issue by tonycheng518** [taosdata/TDengine#2900]
Hi, guys at taosdata, i have configured grafana by steps here: https://www.taosdata.com/cn/documentation/connections-with-other-tools/, but grafana gets no data from taosd.
In taos shell, we can get data:
taos> select * from weather1;
          ts          |    temperature     |      humidity      |    air_pressure    |        pm25        |        pm10        |
================================================================================================================================
 20-07-28 17:06:40.196|            26.00000|            75.00000|          1000.00000|            80.00000|            70.00000|
 20-07-28 17:09:44.895|            26.50000|            75.50000|          1005.00000|            80.50000|            70.50000|
 20-07-28 17:11:12.129|            27.00000|            76.00000|          1010.00000|            81.00000|            71.00000|
 20-07-28 17:40:55.793|            27.50000|            76.50000|          1015.00000|            81.50000|            71.50000|
 20-07-28 17:44:37.600|            28.00000|            77.00000|          1020.00000|            82.00000|            72.00000|
 20-07-28 17:47:16.841|            28.50000|            77.50000|          1025.00000|            82.50000|            72.50000|
 20-07-29 11:26:53.588|            29.00000|            78.00000|          1030.00000|            83.00000|            73.00000|
 20-07-29 11:40:05.395|            29.50000|            78.50000|          1035.00000|            83.50000|            73.50000|
 20-07-29 11:42:29.823|            30.00000|            79.00000|          1040.00000|            84.00000|            74.00000|
 20-07-29 11:42:41.253|            30.50000|            79.50000|          1045.00000|            84.50000|            74.50000|
 20-07-29 16:59:10.497|            31.00000|            80.00000|          1050.00000|            85.00000|            75.00000|
 20-07-29 17:01:06.741|            31.50000|            80.50000|          1055.00000|            85.50000|            75.50000|
 20-08-03 10:20:34.984|            32.00000|            81.00000|          1060.00000|            86.00000|            76.00000|
 20-08-03 10:21:29.941|            32.50000|            81.50000|          1065.00000|            86.50000|            76.50000|
Query OK, 14 row(s) in set (0.031665s)
taos> select temperature from weather1 where ts >= '2020-07-28 17:00:000' and ts < '2020-07-29 18:00:000';
    temperature     |
=====================
            26.00000|
            26.50000|
            27.00000|
            27.50000|
            28.00000|
            28.50000|
            29.00000|
            29.50000|
            30.00000|
            30.50000|
            31.00000|
            31.50000|
Query OK, 12 row(s) in set (0.021813s)
but when we create a dashboard and use the sql above(select temperature from weather1 where ts >= '2020-07-28 17:00:000' and ts < '2020-07-29 18:00:000';) as it's input sql, no data displayed. what's the matter?

**Comment by Aries-Lee1991** [comment]
Please add the detail infomation, like the environment info., the version info. ...

**Comment by tonycheng518** [comment]
tdengine version: 1.6.6.0
os verison: 4.18.0-15-generic #16~18.04.1-Ubuntu SMP Thu Feb 7 14:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
grafana version: 7.1.1
I use tcpdump to monitor the tcp port 6020, nothing happened. it seems that the grafana process doen't fetch data from taosd.
the json model of the dashboard created is as blow:
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 2,
  "links": [],
  "panels": [
    {
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "TDengine",
      "fieldConfig": {
        "defaults": {
          "custom": {}
        },
        "overrides": []
      },
      "fill": 1,
      "fillGradient": 0,
      "gridPos": {
        "h": 15,
        "w": 16,
        "x": 0,
        "y": 0
      },
      "hiddenSeries": false,
      "id": 2,
      "legend": {
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 1,
      "nullPointMode": "null",
      "percentage": false,
      "pluginVersion": "7.1.1",
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "alias": "temperature_weather1",
          "refId": "A",
          "sql": "select temperature from demo.weather1 where ts >= '2020-07-28 17:00:000';",
          "target": "select metric",
          "type": "timeserie"
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Panel Title",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    }
  ],
  "refresh": "10s",
  "schemaVersion": 26,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ]
  },
  "timezone": "",
  "title": "temperature_weather1_10m",
  "uid": "Geto6f4Gz",
  "version": 5
}

**Comment by tonycheng518** [comment]
this is log from /var/log/grafana/grafana.log:
t=2020-08-10T17:29:13+0800 lvl=info msg="Starting Grafana" logger=server version=7.1.1 commit=3039f9c3bd branch=HEAD compiled=2020-07-24T18:08:01+0800
t=2020-08-10T17:29:13+0800 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2020-08-10T17:29:13+0800 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2020-08-10T17:29:13+0800 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2020-08-10T17:29:13+0800 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2020-08-10T17:29:13+0800 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2020-08-10T17:29:13+0800 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
t=2020-08-10T17:29:13+0800 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2020-08-10T17:29:13+0800 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2020-08-10T17:29:13+0800 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2020-08-10T17:29:13+0800 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2020-08-10T17:29:13+0800 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
t=2020-08-10T17:29:13+0800 lvl=info msg="App mode production" logger=settings
t=2020-08-10T17:29:13+0800 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana/grafana-server.pid pid=111296
t=2020-08-10T17:29:13+0800 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2020-08-10T17:29:13+0800 lvl=info msg="Starting DB migration" logger=migrator
t=2020-08-10T17:29:13+0800 lvl=info msg="Starting plugin search" logger=plugins
t=2020-08-10T17:29:13+0800 lvl=info msg="Registering plugin" logger=plugins name="Direct Input"
t=2020-08-10T17:29:13+0800 lvl=info msg="Registering plugin" logger=plugins name=TDengine
t=2020-08-10T17:29:13+0800 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
t=2020-08-10T18:19:29+0800 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1/grafana/query remote_addr=192.168.20.142 referer="http://192.168.20.209:3000/d/Geto6f4Gz/temperature_weather1_10m?editview=dashboard_json&orgId=1&refresh=10s" error="httputil: ReverseProxy read error during body copy: read tcp 192.168.20.209:50250->192.168.20.209:6020: use of closed network connection"
t=2020-08-10T18:19:29+0800 lvl=eror msg="Request error" logger=context userId=1 orgId=1 uname=admin error="net/http: abort Handler"
t=2020-08-10T18:21:49+0800 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1/grafana/query remote_addr=192.168.20.142 referer="http://192.168.20.209:3000/d/Geto6f4Gz/temperature_weather1_10m?editPanel=2&orgId=1&refresh=10s" error="httputil: ReverseProxy read error during body copy: read tcp 192.168.20.209:50266->192.168.20.209:6020: use of closed network connection"
t=2020-08-10T18:21:49+0800 lvl=eror msg="Request error" logger=context userId=1 orgId=1 uname=admin error="net/http: abort Handler"

**Comment by Aries-Lee1991** [comment]
麻烦先升级一下，我们软件的正式版本已经到2.0了。
