### ISSUE TITLE
Sync leader is restoring

### ISSUE THREAD

**Issue by neil-mao** [taosdata/TDengine#29024]
导入数据后，重启了机器，再开机，一直报 “Sync leader is restoring”

查看日志：
总是这个循环报错

 00000220 C SYN vgId:4, sync get retry epset numOfEps:1 inUse:0
 00000180 C MND vgId:4 not restored, not ready for checkpoint or other operations
 00000180 C MND WARN not all vnodes are ready, end to process the consensus-checkpointId in tmr process
 00000220 C VND WARN vgId:4, msg:0x7f7b5c01ed58 failed to process since restore not finished, type:vnode-fetch-ttl-expired-tbs,QID:0x0:0x256338bbd570035f

环境是：3个节点
show vnodes;
dnode_id   |  vgroup_id  |            db_name             |   status    |        role_time        |       start_time        | restored |
           2 |           2 | track                          | leader      | 2024-12-03 16:47:58.734 | 2024-12-03 16:47:58.641 | true     |
           3 |           3 | track                          | leader      | 2024-12-03 16:47:58.940 | 2024-12-03 16:47:58.560 | true     |
           1 |           4 | track                          | leader      | 2024-12-03 16:48:01.522 | 2024-12-03 16:47:57.269 | false    | <--- 出错节点
           3 |           5 | track                          | leader      | 2024-12-03 16:47:58.940 | 2024-12-03 16:47:58.769 | true     |

这种该如何恢复？

**Comment by neil-mao** [comment]
补充：
 删除了 vnode4 目录下的WAL目录， 就可以正常启动了
不知道这种方法是否正确

**Comment by yu285** [comment]
恢复需要时间，可以通过高等级日志可以判断是否恢复卡住。

你这种处理方式会导致丢失这部分数据，但是可以迅速恢复服务。
