### ISSUE TITLE
select last_row(*) from jktest.tfloat where tbname in ('tag_99998') partition by tbname；执行结果错误

### ISSUE THREAD

**Issue by ZhangcyX** [taosdata/TDengine#29039]
tdnegine 版本：3.3.2.0
超表tfloat tbool
子表 tag_99998 是 tbool 的子表
![image](https://github.com/user-attachments/assets/82ba7f33-0b84-46c1-beb4-9e69ad92708a)

我在使用这条sql语句的时候遇到这样一个问题，我根据超表tfloat查询子表tag_99998的值，但是tag_99998并不是tfloat的子表，是tbool的子表，依然能够查出结果？为什么？
select last_row(*) from jktest.tfloat where tbname in ('tag_99998') partition by tbname；
![image](https://github.com/user-attachments/assets/06e070ed-9293-4bee-beed-f2a7d2f4e96e)
实际上tag_99998值应该是布尔类型，最后返回的结果也不对。

**Comment by yu285** [comment]
这是半年前的版本，应该是该版本的bug ，可以升级一下到最新的 3.3.4.8。 如果还有问题可以加微信 a15652223354 远程排查。

**Comment by ZhangcyX** [comment]
我在3.3.4.8的版本上试过啦，使用的docker部署的tdengine，同样的问题还是会存在，能够查到不是当前超表的子表的最新一条数据，数据值还会存在异常。

**Comment by yu285** [comment]
您加我一下吧。
