### ISSUE TITLE
无模式写入，每秒一次，运行一段时间后，写入开始变慢

### ISSUE THREAD

**Issue by charlist8324** [taosdata/TDengine#29044]
**Bug Description**
无模式写入，每秒一次，共10个线程并发写入。
运行一段时间后，写入开始变慢，程序日志显示，停留在写库阶段，如下图

![无模式写库缓慢](https://github.com/user-attachments/assets/2fb676ed-9c93-43af-8514-d34b1cc538a7)

查看jstack发现，线程也阻塞在com.taosdata.jdbc.TSDBJNIConnector.connectImp(Native Method) 位置，如下图：
![image](https://github.com/user-attachments/assets/dee9a5e4-7298-4fb4-b970-6b4e81671c7d)

重启程序可以恢复写入速度，运行一段时间依旧

**Environment (please complete the following information):**
 - OS: [CentOS 7.9]
 - Memory：32GB, CPU：32, 
 - TDengine Version [3.3.4.8]
 - 使用taos原生连接，无模式写入

**Additional Context**
写入代码示例：
![image](https://github.com/user-attachments/assets/175ecbfc-387e-4563-afdc-b4ad38b89fca)
![image](https://github.com/user-attachments/assets/80e434f1-1c0d-41b4-8099-3b10c31fb860)

[jstack2.log](https://github.com/user-attachments/files/18016910/jstack2.log)

**Comment by yu285** [comment]
好的，我们看下

**Comment by yu285** [comment]
应用组排查结束， 需要引擎组分析日志，taosc 获取连接时间较长，看 top -Hp，发现 hb 线程cpu 打满。

**Comment by charlist8324** [comment]
已解决，写库需要池化，避免频繁写入

**Comment by duoheshei** [comment]
> 已解决，写库需要池化，避免频繁写入

10个线程还需要避免频繁写入啊
