### ISSUE TITLE
There is a logical error when combining DISTINCT, CAST, and ORDER BY expressions.

### ISSUE THREAD

**Issue by LingweiKuang** [taosdata/TDengine#29048]
#### Bug Description

The abstract expression sequence is: `SELECT DISTINCT CAST(column AS type) FROM table ORDER BY column `

#### To Reproduce

Assume that we execute the following statement under a database named **testdb**.

```
DROP TABLE IF EXISTS t1;
CREATE TABLE t1(time TIMESTAMP, c1 INT);
INSERT INTO t1(time, c1) VALUES (1641024000000, 1);

# query 1
SELECT DISTINCT c1, CAST(time as BIGINT) FROM t1 ORDER BY time;

# query 2
SELECT c1, CAST(time as BIGINT) FROM t1 ORDER BY time;
SELECT DISTINCT c1, time FROM t1 ORDER BY time;
SELECT DISTINCT c1, CAST(time as BIGINT) FROM t1;
```

#### Expected Behavior

Query 1 returned result set: **1**

Query 2 returned result set: 1

#### Actual behaviour

Query 1 returned result set: **DB error: Not SELECTed expression**

Query 2 returned result set: 1

#### Environment

- OS：Ubuntu Server 22.04 LTS 64bit
- TDengine Version：**[3.3.4.8](https://github.com/taosdata/TDengine/commit/51750787269b137c8f6e4b2099ce61b14fd05a46)**

#### Additional Context

In Query 1, we apply the `DISTINCT` and `CAST` expressions in the SELECT FETCH COLUMN and use the `ORDER BY` expression to sort the filtered result set. However, the query returns an error: "Not SELECTed expression." This type of query combination cannot retrieve any data.

**Comment by LingweiKuang** [comment]
![There is a logical error when combining DISTINCT, CAST, and ORDER BY expressions](https://github.com/user-attachments/assets/45a8b5e8-84d7-44a2-8cf6-5fc1bc3e72a5)

**Comment by yu285** [comment]
![image](https://github.com/user-attachments/assets/b8352b25-6337-4840-8edd-43d647c77400)
