### ISSUE TITLE
failed to start taosd, v1f1847.head corrupted

### ISSUE THREAD

**Issue by xiwang1314** [taosdata/TDengine#2905]
08/03 17:20:20.355240 7f9f3357e740 DND Server IP address is:172.17.0.8
08/03 17:20:20.355259 7f9f3357e740 DND starting to initialize TDengine engine ...
08/03 17:20:20.412584 7f9f3357e740 DND vid:1, committing to file, firstKey:1596392367337 lastKey:1596392408189 ssid:0 esid:1000
08/03 17:20:20.424354 7f9f3357e740 ERROR DND vid:1, last file:/var/lib/taos/tsdb/vnode1/db/v1f1847.head corrupted

**Comment by xiwang1314** [comment]
-rwxrwxrwx 1 root root 1041186816 Jul 29 09:51 v1f1847.data
-rwxrwxrwx 1 root root        512 Aug  3 17:34 v1f1847.head0
-rwxrwxrwx 1 root root          0 Jul 29 09:51 v1f1847.head1
-rwxrwxrwx 1 root root          0 Jul 29 09:51 v1f1847.last1
文件大小为0，估计是文件损坏了

**Comment by xiwang1314** [comment]
现在要如何修复数据

**Comment by xiaopingcs** [comment]
你用的什么版本，有没有升级过?
