### ISSUE TITLE
The CAST operator violates the transitivity of equality comparisons.

### ISSUE THREAD

**Issue by LingweiKuang** [taosdata/TDengine#29064]
#### Bug Description

The abstract expression sequence is: `CAST(column0 AS BINARY) == column1 `

#### To Reproduce

Assume that we execute the following statement under a database named **testdb**.

```
DROP TABLE IF EXISTS t1;
CREATE TABLE t1(time TIMESTAMP, c0 DOUBLE, c1 BIGINT);
INSERT INTO t1(time, c0, c1) VALUES (1641024000000, 1.0, 1);

# query 1
SELECT * FROM t1 WHERE CAST(c0 as BINARY) == CAST(c1 as BINARY);

# query 2
SELECT * FROM t1 WHERE CAST(c0 as BINARY) == c1 AND c1 == CAST(c1 as BINARY);
```

#### Expected Behavior

Query 1 returned result set: **empty set**

Query 2 returned result set: **empty set**

#### Actual behaviour

Query 1 returned result set: **empty set**

Query 2 returned result set: **1**

#### Environment

- OS：Ubuntu Server 22.04 LTS 64bit
- TDengine Version：**[3.3.4.8](https://github.com/taosdata/TDengine/commit/51750787269b137c8f6e4b2099ce61b14fd05a46)**

#### Additional Context

Hello, TDengine team. In Query 1, we convert column `c0` (DOUBLE) and column `c1` (BIGINT) to strings for comparison, and the predicate expression evaluates to FALSE. In Query 2, the predicate expression satisfies the relationship: `a = b` & `b = c`. Since equality comparisons are transitive, we should be able to conclude that `a = c`, which is the same as the predicate expression in Query 1. However, Query 1 evaluates to FALSE, while Query 2 evaluates to TRUE, resulting in a contradiction between the two.

**Comment by LingweiKuang** [comment]
![The CAST operator violates the transitivity of equality comparisons](https://github.com/user-attachments/assets/19a4b515-1269-41e8-bccc-236e215122af)

**Comment by yu285** [comment]
您好 这个并非bug：

原因：CAST(c0 as BINARY) == CAST(c1 as BINARY);  是字符串比较,  '1.0' == '1' 为 false
           (c0 as BINARY) == c1   是字符串和数字比较，最终会按照数值比较逻辑， 1.0 == 1 为 true
