### ISSUE TITLE
stable子表过多时，查询性能特别差，而且taosc会狂增内存

### ISSUE THREAD

**Issue by zjpChina** [taosdata/TDengine#29074]
|              name              |      created_time       | columns |  tags  |   tables    |
|--------------------------------|-------------------------|---------|--------|-------------|
| xyz123                         | 2023-10-14 00:13:12.881 |      65 |      3 |      414614 |
| abc456                         | 2024-02-02 10:18:06.683 |       6 |      4 |          28 |
| def789                         | 2023-10-14 00:13:12.889 |     133 |      2 |       72215 |
| ghi012                         | 2023-12-29 15:15:59.381 |      39 |      3 |           0 |
| jkl345                         | 2023-10-14 00:13:12.910 |       7 |      1 |       18377 |
| mno678                         | 2024-08-28 19:02:27.576 |     200 |      1 |           0 |
| pqr901                         | 2024-07-24 15:50:45.290 |      22 |      2 |           0 |
| stu234                         | 2024-04-03 17:22:51.542 |       4 |      2 |          40 |
| vwx567                         | 2023-10-14 00:13:12.885 |      26 |      3 |        1620 |
| yza890                         | 2023-10-14 00:13:12.892 |      13 |      1 |        1217 |
| bcd123                         | 2023-10-14 00:13:12.896 |      12 |      1 |          32 |
| efg456                         | 2023-10-14 00:13:12.900 |      16 |      1 |         506 |
| hij789                         | 2024-08-28 19:02:27.549 |     178 |      1 |           1 |
| klm012                         | 2024-08-28 19:02:27.562 |      66 |      1 |           0 |
| nop345                         | 2024-08-28 19:02:27.535 |      79 |      1 |           5 |
| qrs678                         | 2023-10-14 00:13:12.903 |       9 |      1 |          17 |
| tuv901                         | 2024-02-04 17:12:49.126 |       4 |      3 |           1 |

查询子表多的stable,性能特别差，然后 taosc内存会狂增。而且通过nload发现会有大量的up流量。
怎么优化性能？

**Comment by xuyinghao** [comment]
你好，请问如何解决的
