### ISSUE TITLE
INTERVAL-使用bug

### ISSUE THREAD

**Issue by k6i6n6g** [taosdata/TDengine#29084]
INTERVAL使用的时候相同时间格式不同查询出来的数据不同。
![image](https://github.com/user-attachments/assets/a2b95279-9eab-495a-a0f7-1d8cde80dbfa)
查询出来的结果不同：
![image](https://github.com/user-attachments/assets/c0459b3f-e08c-450d-ad48-1e05ddb64824)

![image](https://github.com/user-attachments/assets/f3b7f9c1-a346-42d2-af68-f4ec6b7e8e4d)

**Comment by yu285** [comment]
1d 是自然日，1440 m 是分钟，逻辑不一样，可以看下

https://mp.weixin.qq.com/s/Kc7wzzRiK4XhAsL48rD6dg
