### ISSUE TITLE
failed to start taosd after upgrade from tdengine 1.6 to tdengine 2.0

### ISSUE THREAD

**Issue by dpy615** [taosdata/TDengine#2911]
**Bug Description**
之前安装1.6单机版本
后来卸载1.6版本，尝试安装2.0版本
安装后启动失败。 两次安装卸载均为rpm方式安装。报错是 /var/log/taos 下没有新的日志

操作系统：CentOS7

● taosd.service - TDengine server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Mon 2020-08-03 21:03:08 CST; 6min ago
  Process: 320475 ExecStart=/usr/bin/taosd (code=exited, status=127)
 Main PID: 320475 (code=exited, status=127)

Aug 03 21:03:08 hbase systemd[1]: Unit taosd.service entered failed state.
Aug 03 21:03:08 hbase systemd[1]: taosd.service failed.
Aug 03 21:03:08 hbase systemd[1]: taosd.service holdoff time over, scheduling restart.
Aug 03 21:03:08 hbase systemd[1]: Stopped TDengine server service.
Aug 03 21:03:08 hbase systemd[1]: start request repeated too quickly for taosd.service
Aug 03 21:03:08 hbase systemd[1]: Failed to start TDengine server service.
Aug 03 21:03:08 hbase systemd[1]: Unit taosd.service entered failed state.
Aug 03 21:03:08 hbase systemd[1]: taosd.service failed.

**Comment by JKeyZ** [comment]
我是新装机器装了taos，也遇到相同问题
原因可能是没有libtaos.so.1动态库导致的，尝试着执行/usr/bin/taos或者/usr/bin/taosd，可以看到异常。
解决方法是，把client包里libtaos.so.2.0.0.0软链到/usr/lib64下

**Comment by dpy615** [comment]
> 我是新装机器装了taos，也遇到相同问题
> 原因可能是没有libtaos.so.1动态库导致的，尝试着执行/usr/bin/taos或者/usr/bin/taosd，可以看到异常。
> 解决方法是，把client包里libtaos.so.2.0.0.0软链到/usr/lib64下
> 
> 但确实是BUG，rpm包安装连相关库都没安装。而且这种方式目前还没验证对整体功能是否会造成影响

确实如此，做了软链后好了。。。。。。

**Comment by dpy615** [comment]
换了好几台测试发现，用上面说的这种方法，虽然安装成功，但是jdbc远程无法连接，不知道是什么原因，难道2.0版本不支持单机版？
@JKeyZ 你这种方式安装完成后，远程连接正常么？

**Comment by piziZhang2017** [comment]
docker容器启动最新版本， springBoot尝试连接失败，这是通病吗

**Comment by dpy615** [comment]
我觉得新版本对jdbc的应该是适配有问题。我用完全相同的方法1.6就完全没有问题

喜欢随大流
