### ISSUE TITLE
Using Chaos Engineering to enhance TDengine's stabilty

### ISSUE THREAD

**Issue by zhouqiang-cl** [taosdata/TDengine#2912]
Hello, I am Chaos Mesh Maintainer. From the [WeChat official account article](https://mp.weixin.qq.com/s?__biz=MzUyMjEwNDQyMA==&mid=2247484194&idx=1&sn=82a6c3deb32b808685022e741b018cec&chksm=f9d1b829cea6313f4ead19729f49fcb04b2c6849baf02c9e63a76a31f086b7b841b9eb18457a&mpshare=1&scene=1&srcid=0803luRkyhEXgIHXR6SOHHDB&sharer_sharetime=1596447327354&sharer_shareid=9184fc45aa1c0b4ed99e3e9482e03214&version=3.0.24.2278&platform=mac&rd2werd=1#wechat_redirect), I saw that TDengine released version 2.0, which open sourced the cluster function. Congratulations. And I can see from the article that your company attaches great importance to testing and stability

In the database field, the stability of the cluster and the correctness of the data are very important. I believe you will also feel deeply. Chaos engineering is a test method that can guarantee the stability of the system to a large extent. Within PingCAP, we continue to practice chaos engineering and find many bugs (such as data consistency, such as excessive recovery time). Some of the issue records at https://github.com/orgs/chaos-mesh/projects/1

On December 31, 2019, we open sourced our chaos engineering platform [Chaos Mesh](https://github.com/chaos-mesh/chaos-mesh) and entered the CNCF Sandbox on July 15 this year. It is currently the industry’s leading cloud-native chaos engineering platform. In addition to general k8s operations, it also includes a simplified dashboard that can easily perform chaos operations on the front-end page. It also includes an observable datasource that integrates chaos events and services. metric combination.

At present, in addition to our own use of Chaos Mesh to enhance the stability of our TiDB, some other companies such as Xiaopeng Motors, Meituan, Youzan, Dailymotion, NetEase Fuxi Lab, JuiceFS, Apache pulsar, etc. are using Chaos Mesh to enhance system stability. In addition, we can also see some open source projects integrating Chaos Mesh as part of the test system, such as [datastax/fallout](https://github.com/datastax/fallout/pull/1)  [ethersphere/beekeeper](https://github.com/ethersphere/beekeeper/pull/22) [cncf/cnf-conformance](https://github.com/cncf/cnf-conformance/commit/b9227dd4b2262d05eb80b435d931216b084c6a42) [Experiment-catalog](https://github.com/open-chaos/experiment-catalog/tree/master/local/choas-mesh-turbulence) [RCNIT](https://github.com/ungurflorin/RCNIT) [Shortlink](https://github.com/batazor/shortlink) [Fdb-k8s-chaos](https://github.com/PierreZ/fdb-k8s-chaos/)

In Chaos Mesh, we have many injection functions, such as pod/container kill, network partition, network interruption, CPU/memory usage, time rollback, disk failure, etc.

In addition, you can see from the front page of the issue list that recently there are several issues that may be detected by chaos engineering, such as #2905 #2884 #2808

Welcome to use Chaos Mesh to enhance the stability of TDengine. If you have any questions, you can add to my WeChat flicket or submit an issue at https://github.com/chaos-mesh/chaos-mesh, or send me an email zhouqiang@pingcap. com

Sorry for disturb

----------

你们好，我是 Chaos Mesh Maintainer. 从[微信公众号文章](https://mp.weixin.qq.com/s?__biz=MzUyMjEwNDQyMA==&mid=2247484194&idx=1&sn=82a6c3deb32b808685022e741b018cec&chksm=f9d1b829cea6313f4ead19729f49fcb04b2c6849baf02c9e63a76a31f086b7b841b9eb18457a&mpshare=1&scene=1&srcid=0803luRkyhEXgIHXR6SOHHDB&sharer_sharetime=1596447327354&sharer_shareid=9184fc45aa1c0b4ed99e3e9482e03214&version=3.0.24.2278&platform=mac&rd2werd=1#wechat_redirect)里看到 TDengine 发布 2.0 版本，该版本开源了集群功能，恭喜你们。并且从文章中看到贵司对测试和稳定性非常重视

在数据库领域，集群的稳定性和数据的正确性非常重要，相信你们也有很深的感触。混沌工程是一个能在很大程度上保障系统稳定性的测试方法，在 PingCAP 内部，我们持续实践混沌工程，并且发现很多 bug(比如数据一致性的,比如恢复时间过长的) 其中部分 issue 记录在https://github.com/orgs/chaos-mesh/projects/1

在 2019 年 12 月 31 号我们开源了我们混沌工程平台 Chaos Mesh(https://github.com/chaos-mesh/chaos-mesh) 并于今年 7 月 15 日进入 CNCF Sandbox。目前是业界领先的云原生混沌工程平台，除了包含一般的 k8s 操作，也含有简化操作的 dashboard，可以很方便的在前端页面上进行 chaos 操作，  还包含可观测性的 datasource， 将 chaos 事件和业务 metric 结合。

目前除了我们自己在使用 Chaos Mesh 增强我们 TiDB 的稳定性以外，也有一些其他公司比如小鹏汽车、美团、有赞、dailymotion、网易伏羲实验室、JuiceFS、Apache pulsar 等在使用 Chaos Mesh 增强系统稳定性和节省维护窗口时间等，另外我们也可以看到一些开源项目集成 Chaos Mesh 作为测试系统的一部分，如 [datastax/fallout](https://github.com/datastax/fallout/pull/1)  [ethersphere/beekeeper](https://github.com/ethersphere/beekeeper/pull/22) [cncf/cnf-conformance](https://github.com/cncf/cnf-conformance/commit/b9227dd4b2262d05eb80b435d931216b084c6a42) [Experiment-catalog](https://github.com/open-chaos/experiment-catalog/tree/master/local/choas-mesh-turbulence) [RCNIT](https://github.com/ungurflorin/RCNIT) [Shortlink](https://github.com/batazor/shortlink) [Fdb-k8s-chaos](https://github.com/PierreZ/fdb-k8s-chaos/)

在 Chaos Mesh 中，我们有诸多的注入功能，比如 pod/container 的 kill、 网络分区、网络延时、CPU/Memory 占用、时间回退、磁盘故障等等

另外从 issue 列表首页中也可以看到，最近有几个 issue 有可能通过混沌工程来测出其中的问题，如 #2905 #2884 #2808

欢迎来使用 Chaos Mesh 来增强 TDengine 的稳定性，有任何问题可以加我微信 flicket 或者在 https://github.com/chaos-mesh/chaos-mesh 提 issue, 也可以给我发邮件 zhouqiang@pingcap.com

打扰了

**Comment by Aries-Lee1991** [comment]
Please contact the tech email：support@taosdata.com
