### ISSUE TITLE
复合主键且没有时间戳列的普通表能否创建？

### ISSUE THREAD

**Issue by snake3342** [taosdata/TDengine#29139]
我就想创建一个普通表，记录IP地址和端口，不常改动，所以不会有时间戳列，又想把ip和端口作为复合主键(这样可以有主键约束防止重复写入)

create table if not exists ADMIN_DB.ip_address (
host_address VARCHAR(30) PRIMARY KEY,
port INT PRIMARY KEY,
ISP VARCHAR(20),
counter_version VARCHAR(20)
);

说我在port那列syntax error

**Comment by yu285** [comment]
你可以通过超级表，把ip 和 端口 作为两个静态标签，而不用单独存储这样的元数据表。

这是TDengine 的核心设计，具体可以参考官方文档：https://docs.taosdata.com/basic/model/
