### ISSUE TITLE
希望社区版本也能考虑国产操作系统支持

### ISSUE THREAD

**Issue by pope12389** [taosdata/TDengine#29141]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the circumstance is and what the associated problem is. Ex. I'm using TDengine for this use case: [...]. But I'm always frustrated when [...]

**Describe your desired behavior**
A clear and concise description of what you want to happen. Ex. I want TDengine to be able to do [...] when I try to do [...] with it.

**Describe your solutions/suggestions if you've any**
A clear and concise description of any solutions/suggestions to this problem or features you've considered.

**Additional context**

**Comment by yu285** [comment]
这个短期内应该不会，后续会纳入讨论，感谢您的反馈
