### ISSUE TITLE
order by ts desc error

### ISSUE THREAD

**Issue by mm2321** [taosdata/TDengine#29157]
**Bug Description**
根据时间戳逆序查询结果不符合预期，先按日期升序后按时间降序

**To Reproduce**
跨天查询

**Screenshots**
![mmexport1734320255237](https://github.com/user-attachments/assets/101194be-b4a5-4f61-abc5-4a3f10ddb51b)

**Environment (please complete the following information):**
 - OS: Red Hat 7.9
 - TDengine Version 3.0.2.0

**Comment by yu285** [comment]
3.0早期版本的bug 都已经都修复了，但是3.0.2.5 之前可能与现在的最新版（3.3.4.8）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/
