### ISSUE TITLE
The third node cannot be added, and taos lacks library after installation

### ISSUE THREAD

**Issue by liqilong2017** [taosdata/TDengine#2916]
1、集群第二个节点、可以正常添加；第三个报错， end port 一直用第一个节点的还是？？？
第二个节点 配置了：arbitrator            node002.taosd.pub.test:6130
DND ERROR status rsp is received, error:Cluster cfg inconsistent

2、tar.gz 安装包、执行install.sh 以后，直接运行 taos 提醒：
taos: error while loading shared libraries: libtaos.so.1: cannot open shared object file: No such file or directory

**Comment by liuyq-617** [comment]
1. 3台服务器的情况下是不用配置arbitrator的，如果配置，那么所有节点的arbitrator必须指向同一个节点
2. 第二个问题会在下个版本中彻底解决centos的问题，目前请您执行:
   > ln -s /usr/lib64/libtaos.so.1 /usr/lib64/libtaos.so
ln -s /usr/local/taos/driver/libtaos.so.2.0.0.0 /usr/lib64/libtaos.so.1

**Comment by liqilong2017** [comment]
不配置arbitrator，其他的配置跟第二个节点一样？EndPort 还是用第一个节点的？

**Comment by liuyq-617** [comment]
3台服务器的FQDN分别为A,B,C
那么三台的配置文件中:
firstEp都配置为A，secondEp都配置为B

**Comment by liqilong2017** [comment]
如果是 执行 tar.gz里的 install 安装，留空，然后修改配置文件？

**Comment by liuyq-617** [comment]
可以
