### ISSUE TITLE
历史数据和增量数据同步云端问题

### ISSUE THREAD

**Issue by yongweizhao** [taosdata/TDengine#29197]
请教一个数据同步方案，需求是：tdengine已运行了几个月，现在想把历史数据和增量数据同步到云端，tdenigne有无相关实现方案。如数据订阅或TDengine Source Connector 能够满足上述场景。使用的是3.0.2版本。

**Comment by yu285** [comment]
这是企业版/云服务功能，开源版暂时没有数据实时同步工具。如果需要了解可以加微信 a15652223354 具体沟通
