### ISSUE TITLE
消息订阅 表名包含大写报错 

### ISSUE THREAD

**Issue by gfxm301** [taosdata/TDengine#29215]
pull数据 同样的表结构 一个表名大写 一个表名小写  小写的能成功 大写poll数据失败 报错 consumer poll error,code: (0xffff) message: tmg not init
创建订阅语句为
create topic if not exists topic_mic as select * from ops.`Mic`  
create topic if not exists topic_mic7 as select * from ops.`mic7`

**Comment by yu285** [comment]
Mic 变成`Mic` 再试试

仍有疑问可以加微信 a15652223354 做具体排查
