### ISSUE TITLE
联表查询，条件使用函数或非主键,查询异常错误 ：TDengine ERROR (0x2701) 

### ISSUE THREAD

**Issue by hoilung** [taosdata/TDengine#29257]
>OS:windows
>version:3.0.7.0

**联表查询，不支持函数或非主键时间戳作为条件内容** 
1. 联表条件使用函数,查询异常
2. 联表条件使用非主键，查询异常

**数据结构内容如下**
```sql
select * from data_event;
```
 |            ts             |          device_name           |         attribute_name         |           data_type            |      data_value      |
|---|---|---|---|---|
| 2021-07-13 14:06:32.272356 | d8408                          | jk                             | bool                           |            1.0 |
| 2021-07-13 14:06:32.272357 | d8408                          | dl_a                           | float                          |            6.6 |
| 2021-07-13 14:06:32.272358 | d8409                          | jk                             | bool                           |            0.0 |
| 2021-07-13 14:06:32.272359 | d8409                          | dl_a                           | float                          |            8.8 |

>在不确定设备结构的情况下，使用一张表存储数据

不想使用多个列,在不传参数时间戳的情况下获取d8408的在1s内的数据
想通过t2表查询last_row获取最后一行数据的时间戳，再结合联表查询获取所有符合条件的内容

```sql
select t1.* from 
data_event as t1,
(select ts,device_name from data_event where device_name='d8408' order by ts desc limit 1) as t2 
where timediff(t1.ts,t2.ts,1s)==0 and t1.device_name=t2.device_name
```
> 或者
```sql
select t1.* from 
data_event as t1,
(select last_row(ts) as ts from data_event where device_name='d8408') as t2 
where timediff(t1.ts,t2.ts,1s)==0 and t1.device_name='d8408'
```
想通过以上SQL得到如下结果
> select * from data_event where timediff('2021-07-13 14:06:32.272',ts,1s)==0 and device_name='d8408'

|ts                     |device_name|attribute_name|data_type|data_value|
|-----------------------|-----------|--------------|---------|----------|
|2021-07-13 14:06:32.272|d8408      |jk            |bool     |       1.0|
|2021-07-13 14:06:32.272|d8408      |dl_a          |float    |       6.6|

### 测试如下：
***查询正常***
>条件使用主键时间戳的正常
```sql
select t1.* from 
data_event t1,
(select last_row(ts) as ts from data_event where device_name='d8408') t2
where t1.ts=t2.ts
```
***查询异常***
>条件是非主键的查询异常
```sql
select t1.* from 
data_event t1,
(select last_row(device_name) as device_name from data_event where device_name='d8408') t2
where t1.device_name=t2.device_name
```
>条件使用函数的查询异常
```sql
select t1.* from 
data_event as t1,
(select last_row(ts) as ts from data_event where device_name='d8408') as t2 
where timediff(t1.ts,t2.ts,1s)==0
```

**Comment by yu285** [comment]
windows 早期问题较多，开源版维护不过来，回收到到企业版重做了。 所以windows版本到了 3.0.7.1 之后就没法再升级了，也没有维护团队支持。所以咱们还是换到 linux 版本再使用，目前最新版为 3.3.4.8

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/

如果迁移后还有问题，可以加微信 a15652223354 做具体排查

**Comment by hoilung** [comment]
应该不是版本问题，是功能问题，使用最新版本linux的也存在类似问题，应该是不支持内存或虚拟表来进行联表查询
