### ISSUE TITLE
希望删除/覆盖数据时可以清理掉磁盘空间

### ISSUE THREAD

**Issue by LFDCC** [taosdata/TDengine#29281]
相关问题已经在issues上看过了，删除数据包括表都不会清理磁盘空间，希望开发大大把这个功能加上。。。
还有插入重复的时间戳实现变相的更新数据，但原始数据的磁盘空间也不会被释放（。。这就很奇怪了）。希望也可以清理掉磁盘空间

**Comment by yu285** [comment]
这个是逻辑删除，需要重组碎片的功能，目前开源版还不支持，只能通过 keep 参数来物理释放空间，或者taosdump 导出再导入重建。

**Comment by LFDCC** [comment]
我们现在遇到一点覆盖数据的问题，因为总会冗余一些数据，例如设备规格，因为规格字典修改了，所以想在特定的时间把所以冗余数据刷一遍，但是后来看issue上的回复，原始数据空间不会被释放，例如现在有500G的原始数据，那把所以数据覆盖一遍岂不是占用空间翻倍了，所以我们现在打算就把冗余字段废弃掉了，查询数据的时候在内存中把最新的规格型号查出来



---原始邮件---
发件人: "Yu ***@***.***&gt;
发送时间: 2024年12月24日(周二) 下午2:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [taosdata/TDengine] 希望删除/覆盖数据时可以清理掉磁盘空间 (Issue #29281)




 
这个是逻辑删除，需要重组碎片的功能，目前开源版还不支持，只能通过 keep 参数来物理释放空间，或者taosdump 导出再导入重建。

**Comment by jettzhan** [comment]
> 这个是逻辑删除，需要重组碎片的功能，目前开源版还不支持，只能通过 keep 参数来物理释放空间，或者taosdump 导出再导入重建。

麻烦问下，通过keep参数来释放空间，如果 当时覆盖数据或者delete的时间，在keep参数 范围之内，那么这个修改 keep 参数否可行？我看文档keep 是数据文件保存的时间。 @yu285
