### ISSUE TITLE
如果查询超级表下所有子表的最后一条数据？

### ISSUE THREAD

**Issue by vkqiang** [taosdata/TDengine#293]
定义一个超级表，然后一个设备一个子表，如果有一千个设备，想获取这一千个设备的最后一条记录，怎么获取呢
循环获取1000次？应该有更简单的方法吧，一条sql就能出来么？

**Comment by hzcheng** [comment]
可以的，假设超级表是st：

```
select last_row(*) from st group by tbname;
```
tbname是关键词，表示表名。

**Comment by vkqiang** [comment]
> 可以的，假设超级表是st：
> 
> ```
> select last_row(*) from st group by tbname;
> ```
> 
> tbname是关键词，表示表名。

正解

**Comment by andyz168** [comment]
`select last_row(*), device_identification
from common_sfser t
group by device_identification;`
为什么用mybatis读取出来device_identification是空字符
![image](https://github.com/taosdata/TDengine/assets/22382971/fa5bb998-1581-4b91-8e7b-4369ef953214)
![image](https://github.com/taosdata/TDengine/assets/22382971/3836ed7f-05da-44f4-aef1-be60db52580a)
