### ISSUE TITLE
数据表列的问题

### ISSUE THREAD

**Issue by dpy615** [taosdata/TDengine#2930]
目前每个数据表，最大能存放255列。这个列的宽度是固定的么？有什么地方可以配置么？

**Comment by yilezhu** [comment]
看官方文档说：TDengine支持最大的列数为1024列。 
![image](https://user-images.githubusercontent.com/18655233/89377077-a88f1d00-d723-11ea-84c6-a803856f9ddd.png)

**Comment by dpy615** [comment]
> 看官方文档说：TDengine支持最大的列数为1024列。
> ![image](https://user-images.githubusercontent.com/18655233/89377077-a88f1d00-d723-11ea-84c6-a803856f9ddd.png)
> 这是链接：https://www.taosdata.com/cn/documentation20/model/#%E5%88%9B%E5%BB%BA%E8%A1%A8
> 在文章最下面有写

哦哦，看到了，在代码里也找到了定义列最大值的地方。

**Comment by dpy615** [comment]
@yilezhu  2.0版本你有波状或单机版么？远程连接是否正常？
