### ISSUE TITLE
When can we provide C# connector?

### ISSUE THREAD

**Issue by yilezhu** [taosdata/TDengine#2931]
At present, many connectors have been provided, but there is no C# Standard Version connector. Is there any plan to support it？
Looking forward to your answers。

**Comment by Aries-Lee1991** [comment]
C# connector is comming. Wait for a few weeks.

**Comment by leegkon** [comment]
In the field of industrial Internet, especially the traditional chemical industry, machinery, electricity, steel and other industries, there are a large number of applications based on. Net technology stack, they have urgent needs for the collection and storage of industrial data, hope taosData official can meet the needs of this part of users, which will also promote the progress of the industrial field.

**Comment by geffzhang** [comment]
https://github.com/maikebing/Maikebing.EntityFrameworkCore.Taos
