### ISSUE TITLE
Alert error: failed to query TDengine: Unexpected generic error in RPC

### ISSUE THREAD

**Issue by lovetaitai** [taosdata/TDengine#2932]
目前使用2.0.0.0版本的taos数据库和最新版本的Alert告警模块，然后按照文档配置了cfg文件如下：
![image](https://user-images.githubusercontent.com/53462360/89381981-92398f00-d72c-11ea-890a-b68c5d1a2380.png)
然后推送了规则rule1：
{
  "name": "rule1",
  "sql": "select sum(cpu_used) as cpu from iot.computing_resource_info where ts > now - 1m group by machine_id;",
  "expr": "cpu > 43",
  "for": "0",
  "period": "1m",
  "labels": {
    "ruleName": "rule1"
  },
  "annotations": {
    "summary": "sum of rule {{$labels.ruleName}} of machine_id {{$values.machine_id}} is {{$values.cpu}}"
  }
}
但是alert日志一直在报错：
taosdata/alert/app.runRules.func1.1\n\t/home/zbm/td/community/alert/app/rule.go:483"}
{"level":"error","ts":1596610740.6265388,"caller":"log/log.go:69","msg":"[rule1]: failed to query TDengine: Unexpected generic error in RPC","stacktrace":"github.com/taosdata/alert/utils/log.Errorf\n\t/home/zbm/td/community/alert/utils/log/log.go:69\ngithub.com/taosdata/alert/app.(*Rule).run\n\t/home/zbm/td/community/alert/app/rule.go:345\ngithub.com/taosdata/alert/app.runRules.func1.1\n\t/home/zbm/td/community/alert/app/rule.go:483"}
{"level":"error","ts":1596610800.6263335,"caller":"log/log.go:69","msg":"[rule1]: failed to query TDengine: Unexpected generic error in RPC","stacktrace":"github.com/taosdata/alert/utils/log.Errorf\n\t/home/zbm/td/community/alert/utils/log/log.go:69\ngithub.com/taosdata/alert/app.(*Rule).run\n\t/home/zbm/td/community/alert/app/rule.go:345\ngithub.com/taosdata/alert/app.runRules.func1.1\n\t/home/zbm/td/community/alert/app/rule.go:483"}
{"level":"error","ts":1596610860.6265104,"caller":"log/log.go:69","msg":"[rule1]: failed to query TDengine: Unexpected generic error in RPC","stacktrace":"github.com/taosdata/alert/utils/log.Errorf\n\t/home/zbm/td/community/alert/utils/log/log.go:69\ngithub.com/taosdata/alert/app.(*Rule).run\n\t/home/zbm/td/community/alert/app/rule.go:345\ngithub.com/taosdata/alert/app.runRules.func1.1\n\t/home/zbm/td/community/alert/app/rule.go:483"}
^C

规则中的sql实际数据库汇总运行有结果无误的。

**Comment by lovetaitai** [comment]
实际我用一台服务器上的taos2.0.0客户端去连接另一个服务器的taos2.0.0，可以连接上，但是运行命令报错：
DB error: Unexpected generic error in RPC

**Comment by localvar** [comment]
这个问题的原因是将FQDN（截图中挡住的部分）转换为ip地址时出错，请确认下dns配置是否有问题，或者用其他程序测试下这个转换是否会出错。

**Comment by lovetaitai** [comment]
> 这个问题的原因是将FQDN（截图中挡住的部分）转换为ip地址时出错，请确认下dns配置是否有问题，或者用其他程序测试下这个转换是否会出错。

遮住的地方就是写的ip地址

**Comment by localvar** [comment]
这里的意思是 “taos2.0 的客户端与服务器不在一台机器上时，也会报 'Unexpected generic error in RPC'” 吗？

> 实际我用一台服务器上的taos2.0.0客户端去连接另一个服务器的taos2.0.0，可以连接上，但是运行命令报错：
> DB error: Unexpected generic error in RPC

**Comment by amen943** [comment]
服务端运行在docker，springboot+mybatis与服务端是同一台主机，能正常连接，但是插入报错：
org.springframework.jdbc.UncategorizedSQLException: 
### Error updating database.  Cause: java.sql.SQLException: TDengine Error: Unexpected generic error in RPC
### The error may exist in class path resource [mapper/TestMapper.xml]
### The error may involve com.wangguofa.taosdatainsertservice.dao.TestDao.insertTest-Inline
### The error occurred while setting parameters
### SQL: insert into wgf.test(ts, speed) values (?, ?)
### Cause: java.sql.SQLException: TDengine Error: Unexpected generic error in RPC
; uncategorized SQLException; SQL state []; error code [-2147483636]; TDengine Error: Unexpected generic error in RPC; nested exception is java.sql.SQLException: TDengine Error: Unexpected generic error in RPC
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89) ~[spring-jdbc-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81) ~[spring-jdbc-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81) ~[spring-jdbc-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]

**Comment by localvar** [comment]
您好，这个问题我们已经通过更新文档、修改代码等方式进行了处理，请您更新到最新版本验证一下问题是否仍然存在。
