### ISSUE TITLE
nodejs connector is not available in window for 2.0

### ISSUE THREAD

**Issue by theday112** [taosdata/TDengine#2935]
安装完，找不到libtaos.dll文件，windows/system32 windows/system 目录下都没有！

D:\MyWork\tdengine>npm install td2.0-connector --save
npm WARN deprecated har-validator@5.1.5: this

> ref@1.3.5 install D:\MyWork\tdengine\node_modules\ref
> node-gyp rebuild

D:\MyWork\tdengine\node_modules\ref>if not defined npm_config_node_gyp (node "D:\MyWork\node-v10.22.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\MyWork\node-v10.22.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  binding.cc
  win_delay_load_hook.cc
d:\mywork\tdengine\node_modules\ref\src\binding.cc(253): warning C4996: 'v8::Value::Uint32Value': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ref\build\binding.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\10.22.0\include\node\v8.h(2477): note: 参见“v8::Value::Uint32Value”的声明
d:\mywork\tdengine\node_modules\ref\src\binding.cc(360): warning C4996: 'v8::String::Utf8Value::Utf8Value': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ref\build\binding.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\10.22.0\include\node\v8.h(2891): note: 参见“v8::String::Utf8Value::Utf8Value”的声明
d:\mywork\tdengine\node_modules\ref\src\binding.cc(447): warning C4996: 'v8::String::Utf8Value::Utf8Value': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ref\build\binding.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\10.22.0\include\node\v8.h(2891): note: 参见“v8::String::Utf8Value::Utf8Value”的声明
d:\mywork\tdengine\node_modules\ref\src\binding.cc(521): warning C4996: 'v8::Value::Uint32Value': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ref\build\binding.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\10.22.0\include\node\v8.h(2477): note: 参见“v8::Value::Uint32Value”的声明
d:\mywork\tdengine\node_modules\ref\src\binding.cc(550): warning C4996: 'v8::Value::Uint32Value': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ref\build\binding.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\10.22.0\include\node\v8.h(2477): note: 参见“v8::Value::Uint32Value”的声明
d:\mywork\tdengine\node_modules\ref\src\binding.cc(643): warning C4996: 'Nan::ForceSet': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ref\build\binding.vcxproj]
  d:\mywork\tdengine\node_modules\nan\nan_maybe_43_inl.h(117): note: 参见“Nan::ForceSet”的声明
d:\mywork\tdengine\node_modules\ref\src\binding.cc(644): warning C4996: 'Nan::ForceSet': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ref\build\binding.vcxproj]
  d:\mywork\tdengine\node_modules\nan\nan_maybe_43_inl.h(117): note: 参见“Nan::ForceSet”的声明
    正在创建库 D:\MyWork\tdengine\node_modules\ref\build\Release\binding.lib 和对象 D:\MyWork\tdengine\node_modules\ref\build\Release\binding.exp
  正在生成代码
  All 206 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  已完成代码的生成
  binding.vcxproj -> D:\MyWork\tdengine\node_modules\ref\build\Release\\binding.node

> ffi@2.3.0 install D:\MyWork\tdengine\node_modules\ffi
> node-gyp rebuild

D:\MyWork\tdengine\node_modules\ffi>if not defined npm_config_node_gyp (node "D:\MyWork\node-v10.22.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\MyWork\node-v10.22.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  Building assembly file ..\..\..\deps\libffi\src\x86\win64.asm
   Assembling: ..\..\..\deps\libffi\src\x86\win64.asm
  prep_cif.c
  types.c
  raw_api.c
  java_raw_api.c
  closures.c
  ffi.c
  win_delay_load_hook.cc
  ffi.vcxproj -> D:\MyWork\tdengine\node_modules\ffi\build\Release\\libffi.lib
  ffi.cc
  callback_info.cc
  threaded_callback_invokation.cc
  win32-dlfcn.cc
  win_delay_load_hook.cc
d:\mywork\tdengine\node_modules\ffi\src\callback_info.cc(63): warning C4996: 'Nan::Callback::Call': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  d:\mywork\tdengine\node_modules\nan\nan.h(1742): note: 参见“Nan::Callback::Call”的声明
d:\mywork\tdengine\node_modules\ffi\src\callback_info.cc(73): warning C4996: 'Nan::Callback::Call': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  d:\mywork\tdengine\node_modules\nan\nan.h(1742): note: 参见“Nan::Callback::Call”的声明
d:\mywork\tdengine\node_modules\ffi\src\callback_info.cc(78): warning C4996: 'Nan::Callback::Call': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(58): warning C4996: 'Nan::ForceSet': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  d:\mywork\tdengine\node_modules\nan\nan.h(1742): note: 参见“Nan::Callback::Call”的声明
  d:\mywork\tdengine\node_modules\nan\nan_maybe_43_inl.h(117): note: 参见“Nan::ForceSet”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(59): warning C4996: 'Nan::ForceSet': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  d:\mywork\tdengine\node_modules\nan\nan_maybe_43_inl.h(117): note: 参见“Nan::ForceSet”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(60): warning C4996: 'Nan::ForceSet': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  d:\mywork\tdengine\node_modules\nan\nan_maybe_43_inl.h(117): note: 参见“Nan::ForceSet”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(63): warning C4996: 'Nan::ForceSet': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  d:\mywork\tdengine\node_modules\nan\nan_maybe_43_inl.h(117): note: 参见“Nan::ForceSet”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(64): warning C4996: 'Nan::ForceSet': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  d:\mywork\tdengine\node_modules\nan\nan_maybe_43_inl.h(117): note: 参见“Nan::ForceSet”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(65): warning C4996: 'Nan::ForceSet': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  d:\mywork\tdengine\node_modules\nan\nan_maybe_43_inl.h(117): note: 参见“Nan::ForceSet”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(78): warning C4996: 'Nan::ForceSet': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
d:\mywork\tdengine\node_modules\ffi\src\callback_info.cc(112): warning C4996: 'v8::Value::ToObject': 被声明为已否决d:\mywork\tdengine\node_modules\nan\nan_maybe_43_inl.h(117): note: 参见“Nan::ForceSet”的声明 [D:\MyWork\tdengine\node_modules\ffi\bui
ld\ffi_bindings.vcxproj]

  c:\users\administrator\appdata\local\node-gyp\cache\10.22.0\include\node\v8.h(10046): note: 参见“v8::Value::ToObject”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(88): warning C4996: 'Nan::ForceSet': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
d:\mywork\tdengine\node_modules\ffi\src\callback_info.cc(113): warning C4996: 'v8::Value::Int32Value': 被声明为已否决d:\mywork\tdengine\node_modules\nan\nan_maybe_43_inl.h(117): note: 参见“Nan::ForceSet”的声明 [D:\MyWork\tdengine\node_modules\ffi\b
uild\ffi_bindings.vcxproj]

  c:\users\administrator\appdata\local\node-gyp\cache\10.22.0\include\node\v8.h(2478): note: 参见“v8::Value::Int32Value”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(91): warning C4996: 'Nan::ForceSet': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
d:\mywork\tdengine\node_modules\ffi\src\callback_info.cc(114): warning C4996: 'v8::Value::Int32Value': 被声明为已否决d:\mywork\tdengine\node_modules\nan\nan_maybe_43_inl.h(117): note: 参见“Nan::ForceSet”的声明 [D:\MyWork\tdengine\node_modules\ffi\b
uild\ffi_bindings.vcxproj]

  c:\users\administrator\appdata\local\node-gyp\cache\10.22.0\include\node\v8.h(2478): note: 参见“v8::Value::Int32Value”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(94): warning C4996: 'Nan::ForceSet': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  d:\mywork\tdengine\node_modules\nan\nan_maybe_43_inl.h(117): note: 参见“Nan::ForceSet”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(97): warning C4996: 'Nan::ForceSet': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  d:\mywork\tdengine\node_modules\nan\nan_maybe_43_inl.h(117): note: 参见“Nan::ForceSet”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(111): warning C4996: 'Nan::ForceSet': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  d:\mywork\tdengine\node_modules\nan\nan_maybe_43_inl.h(117): note: 参见“Nan::ForceSet”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(114): warning C4996: 'Nan::ForceSet': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  d:\mywork\tdengine\node_modules\nan\nan_maybe_43_inl.h(117): note: 参见“Nan::ForceSet”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(123): warning C4996: 'Nan::ForceSet': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  d:\mywork\tdengine\node_modules\nan\nan_maybe_43_inl.h(117): note: 参见“Nan::ForceSet”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(124): warning C4996: 'Nan::ForceSet': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  d:\mywork\tdengine\node_modules\nan\nan_maybe_43_inl.h(117): note: 参见“Nan::ForceSet”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(125): warning C4996: 'Nan::ForceSet': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  d:\mywork\tdengine\node_modules\nan\nan_maybe_43_inl.h(117): note: 参见“Nan::ForceSet”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(126): warning C4996: 'Nan::ForceSet': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  d:\mywork\tdengine\node_modules\nan\nan_maybe_43_inl.h(117): note: 参见“Nan::ForceSet”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(132): warning C4996: 'Nan::ForceSet': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  d:\mywork\tdengine\node_modules\nan\nan_maybe_43_inl.h(117): note: 参见“Nan::ForceSet”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(190): warning C4996: 'v8::Value::Uint32Value': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\10.22.0\include\node\v8.h(2477): note: 参见“v8::Value::Uint32Value”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(191): warning C4996: 'v8::Value::ToObject': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\10.22.0\include\node\v8.h(10046): note: 参见“v8::Value::ToObject”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(192): warning C4996: 'v8::Value::ToObject': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\10.22.0\include\node\v8.h(10046): note: 参见“v8::Value::ToObject”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(193): warning C4996: 'v8::Value::Uint32Value': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\10.22.0\include\node\v8.h(2477): note: 参见“v8::Value::Uint32Value”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(234): warning C4996: 'v8::Value::Uint32Value': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\10.22.0\include\node\v8.h(2477): note: 参见“v8::Value::Uint32Value”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(235): warning C4996: 'v8::Value::Uint32Value': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\10.22.0\include\node\v8.h(2477): note: 参见“v8::Value::Uint32Value”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(236): warning C4996: 'v8::Value::ToObject': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\10.22.0\include\node\v8.h(10046): note: 参见“v8::Value::ToObject”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(237): warning C4996: 'v8::Value::ToObject': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\10.22.0\include\node\v8.h(10046): note: 参见“v8::Value::ToObject”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(238): warning C4996: 'v8::Value::Uint32Value': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\10.22.0\include\node\v8.h(2477): note: 参见“v8::Value::Uint32Value”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(265): warning C4996: 'v8::Value::ToObject': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\10.22.0\include\node\v8.h(10046): note: 参见“v8::Value::ToObject”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(266): warning C4996: 'v8::Value::ToObject': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\10.22.0\include\node\v8.h(10046): note: 参见“v8::Value::ToObject”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(267): warning C4996: 'v8::Value::ToObject': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\10.22.0\include\node\v8.h(10046): note: 参见“v8::Value::ToObject”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(268): warning C4996: 'v8::Value::ToObject': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\10.22.0\include\node\v8.h(10046): note: 参见“v8::Value::ToObject”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(307): warning C4996: 'v8::Value::ToObject': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\10.22.0\include\node\v8.h(10046): note: 参见“v8::Value::ToObject”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(308): warning C4996: 'v8::Value::ToObject': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\10.22.0\include\node\v8.h(10046): note: 参见“v8::Value::ToObject”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(309): warning C4996: 'v8::Value::ToObject': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\10.22.0\include\node\v8.h(10046): note: 参见“v8::Value::ToObject”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(310): warning C4996: 'v8::Value::ToObject': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\10.22.0\include\node\v8.h(10046): note: 参见“v8::Value::ToObject”的声明
d:\mywork\tdengine\node_modules\ffi\src\ffi.cc(367): warning C4996: 'Nan::Callback::Call': 被声明为已否决 [D:\MyWork\tdengine\node_modules\ffi\build\ffi_bindings.vcxproj]
  d:\mywork\tdengine\node_modules\nan\nan.h(1742): note: 参见“Nan::Callback::Call”的声明
    正在创建库 D:\MyWork\tdengine\node_modules\ffi\build\Release\ffi_bindings.lib 和对象 D:\MyWork\tdengine\node_modules\ffi\build\Release\ffi_bindings.exp
  正在生成代码
  All 343 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  已完成代码的生成
  ffi_bindings.vcxproj -> D:\MyWork\tdengine\node_modules\ffi\build\Release\\ffi_bindings.node
npm WARN tdengine@1.0.0 No description
npm WARN tdengine@1.0.0 No repository field.

+ td2.0-connector@2.0.1
added 118 packages from 79 contributors in 22.309s

2 packages are looking for funding
  run `npm fund` for details

D:\MyWork\tdengine>node tdengine.js
D:\MyWork\tdengine\node_modules\ffi\lib\dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err)
    ^

Error: Dynamic Linking Error: Win32 error 126
    at new DynamicLibrary (D:\MyWork\tdengine\node_modules\ffi\lib\dynamic_library.js:74:11)
    at Object.Library (D:\MyWork\tdengine\node_modules\ffi\lib\library.js:45:12)
    at new CTaosInterface (D:\MyWork\tdengine\node_modules\td2.0-connector\nodetaos\cinterface.js:200:22)
    at TDengineConnection._configConn (D:\MyWork\tdengine\node_modules\td2.0-connector\nodetaos\connection.js:52:19)
    at new TDengineConnection (D:\MyWork\tdengine\node_modules\td2.0-connector\nodetaos\connection.js:25:8)
    at Object.module.exports.connect (D:\MyWork\tdengine\node_modules\td2.0-connector\tdengine.js:3:10)
    at Object.<anonymous> (D:\MyWork\tdengine\tdengine.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

**Comment by xiaopingcs** [comment]
你好，我们windows 2.0客户端还没有发版，所有2.0的connector在windows下都无法使用。windows 2.0客户端正在开发中，发版需要等3周。
