### ISSUE TITLE
tdengine 3.2.1 last函数失效问题

### ISSUE THREAD

**Issue by liuchenn** [taosdata/TDengine#29356]
tdengine版本：3.2.1

问题描述：
last函数获取的值是半小时之前的最新值
![cdb226f26f220db0c3222f83568c4e1a](https://github.com/user-attachments/assets/3223ce29-080b-4148-915a-c8b0733c7af7)
![618854c3afbc7fe9cf052f2086df96d3](https://github.com/user-attachments/assets/f02ec6fc-7aa9-47c3-aafe-bbfa324630d5)

**Comment by liuchenn** [comment]
我排查了缓存，
![image](https://github.com/user-attachments/assets/36df14bf-1c50-4b9e-8918-c8cb5cc4d90c)
![image](https://github.com/user-attachments/assets/ba476d37-fe58-4504-8029-62558f86d65a)
目前缓存还没有用完

**Comment by yu285** [comment]
升级到最新版本吧 3.3.4.8，或者下周升级到马上发版的 3.3.5.0 吧，这类问题已经解决了。
