### ISSUE TITLE
SpringBoot+MybatisPlus+TDengine使用超级表插入数据报错this operation is NOT supported currently!

### ISSUE THREAD

**Issue by Jerveen** [taosdata/TDengine#29370]
Windows环境下
Tdengine ：3.3.0.0
Tdengine Client：3.3.0.0
mybatis-plus：3.5.3.1
druid：1.2.16
dynamic-datasource：3.6.1

MybatisPlus批量插入代码：
![image](https://github.com/user-attachments/assets/a94eb4c5-ce08-4b10-92c3-e604e442d7c3)
报错信息：
![image](https://github.com/user-attachments/assets/5c075422-4201-41a0-a59a-17202ad07620)
TDengine使用Java的Jdbc原生方式连接，RS方式也试过，同样的报错！

**Comment by xionghaizhi** [comment]
怎么解决的？怎么关闭了？

**Comment by xionghaizhi** [comment]
怎么解决的大佬？
