### ISSUE TITLE
2000w条数据，大约占了400M的磁盘空间

### ISSUE THREAD

**Issue by Anbingsong** [taosdata/TDengine#29402]
我测试了influx数据库的磁盘占用是150M,每条数据为单列float的数据量，建表也为单列float，可否优化一下这个磁盘占用量？

**Comment by yu285** [comment]
是不是wal 占用比较多？

实际需要对比的是tsdb 目录下的文件

WAL 可以设置保留策略，https://docs.taosdata.com/reference/taos-sql/database/

如果还有疑问可以添加微信 a15652223354
