### ISSUE TITLE
taos connect failed, reason: Unable to establish connection.

### ISSUE THREAD

**Issue by watchworld** [taosdata/TDengine#2940]
install tdengine , enter taos,happen taos connect failed, reason: Unable to establish connection.
log description

08/05 17:20:45.876822 0x7f3352cef700 UTL ERROR failed get the ip address, fqdn:, code:-2, reason:Name or service not known
08/05 17:20:45.876847 0x7f3352cef700 RPC ERROR DND-C, failed to resolve FQDN:
08/05 17:20:45.876855 0x7f3352cef700 RPC ERROR DND-C (nil), failed to set up connection(Unexpected generic error in RPC)
08/05 17:20:45.876862 0x7f3352cef700 RPC DND-C (nil), connection error happens
08/05 17:20:45.876864 0x7f3352cef700 DND ERROR status rsp is received, error:Unexpected generic error in RPC
08/05 17:20:46.876813 0x7f3352cef700 UTL ERROR failed get the ip address, fqdn:, code:-2, reason:Name or service not known
08/05 17:20:46.876837 0x7f3352cef700 RPC ERROR DND-C, failed to resolve FQDN:
08/05 17:20:46.876846 0x7f3352cef700 RPC ERROR DND-C (nil), failed to set up connection(Unexpected generic error in RPC)
08/05 17:20:46.876852 0x7f3352cef700 RPC DND-C (nil), connection error happens
08/05 17:20:46.876856 0x7f3352cef700 DND ERROR status rsp is received, error:Unexpected generic error in RPC
08/05 17:20:47.876805 0x7f3352cef700 UTL ERROR failed get the ip address, fqdn:, code:-2, reason:Name or service not known
08/05 17:20:47.876830 0x7f3352cef700 RPC ERROR DND-C, failed to resolve FQDN:
08/05 17:20:47.876838 0x7f3352cef700 RPC ERROR DND-C (nil), failed to set up connection(Unexpected generic error in RPC)
08/05 17:20:47.876844 0x7f3352cef700 RPC DND-C (nil), connection error happens
08/05 17:20:47.876847 0x7f3352cef700 DND ERROR status rsp is received, error:Unexpected generic error in RPC

**Comment by Aries-Lee1991** [comment]
Please add the environment and version info.

**Comment by watchworld** [comment]
CentOS Linux release 7.8.2003 (Core) 
kernel-3.10.0-1127.18.2.el7.x86_64

**Comment by watchworld** [comment]
tdengine 2.0.0.1

**Comment by watchworld** [comment]
TDEngine2.0.0.1 OK
