### ISSUE TITLE
might overwrite ->next field

### ISSUE THREAD

**Issue by freemine** [taosdata/TDengine#2942]
https://github.com/taosdata/TDengine/blob/61935939a6604fef7ba6cab051ba1dffd9b1e1e7/src/util/src/ttimer.c#L549
```
tstrncpy(ctrl->label, label, sizeof(ctrl->label)); 
```
if label is too long, say greater than 8 in this case, the `next` field would be corrupted.

shall be corrected to:
```
tstrncpy(ctrl->label, label, sizeof(ctrl->padding));
```

**Comment by localvar** [comment]
hi freemine, `time_ctrl_t` is a union, which means `label` and `next` would never be used at a same time, so this is not a bug.

**Comment by freemine** [comment]
OK,  it's union,and next means it's next node in free list. There is no working list maintained.
