### ISSUE TITLE
error message taos.error.ProgrammingError: Unexpected generic error in RPC when using python connector

### ISSUE THREAD

**Issue by jerryuhoo** [taosdata/TDengine#2944]
如果从本地电脑访问服务器的话能成功连接到数据库，但是执行c1.execute('use db')会返回......local/lib/python3.7/site-packages/taos/cursor.py", line 150, in execute
    self._result), errno)
taos.error.ProgrammingError: Unexpected generic error in RPC。

用的是release2.0.0.0版本，连接到数据库的端口是6030

**Comment by Shawshank-Smile** [comment]
I need your log file

**Comment by jerryuhoo** [comment]
==================================================
                new log file                      
==================================================
08/06 10:00:41.598852 0xfff72c5fc0 UTL localEp is: srv01:6030
08/06 10:00:41.599580 0xfff72c5fc0 UTL timezone not configured, set to system default:Asia/Shanghai (CST, +0800)
08/06 10:00:41.599664 0xfff72c5fc0 UTL ERROR locale not configured, set to system default:zh_CN.UTF-8
08/06 10:00:41.599678 0xfff72c5fc0 UTL WARN charset not configured, set to system default:UTF-8
08/06 10:00:41.599732 0xfff72c5fc0 UTL    taos config & system info:
08/06 10:00:41.599739 0xfff72c5fc0 UTL ==================================
08/06 10:00:41.599744 0xfff72c5fc0 UTL  firstEp:                srv01:6030 
08/06 10:00:41.599748 0xfff72c5fc0 UTL  secondEp:               srv01:6030 
08/06 10:00:41.599752 0xfff72c5fc0 UTL  fqdn:                   srv01 
08/06 10:00:41.599756 0xfff72c5fc0 UTL  serverPort:             6030 
08/06 10:00:41.599759 0xfff72c5fc0 UTL  configDir:              /etc/taos 
08/06 10:00:41.599763 0xfff72c5fc0 UTL  logDir:                 /var/log/taos 
08/06 10:00:41.599766 0xfff72c5fc0 UTL  scriptDir:              /etc/taos 
08/06 10:00:41.599769 0xfff72c5fc0 UTL  arbitrator:              
08/06 10:00:41.599773 0xfff72c5fc0 UTL  numOfThreadsPerCore:    1.000000 
08/06 10:00:41.599783 0xfff72c5fc0 UTL  rpcTimer:               1000(ms)
08/06 10:00:41.599787 0xfff72c5fc0 UTL  rpcMaxTime:             600(s)
08/06 10:00:41.599790 0xfff72c5fc0 UTL  shellActivityTimer:     3(s)
08/06 10:00:41.599794 0xfff72c5fc0 UTL  tableMetaKeepTimer:     7200(s)
08/06 10:00:41.599797 0xfff72c5fc0 UTL  compressMsgSize:        -1 
08/06 10:00:41.599801 0xfff72c5fc0 UTL  maxSQLLength:           65480(byte)
08/06 10:00:41.599805 0xfff72c5fc0 UTL  maxNumOfOrderedRes:     100000 
08/06 10:00:41.599808 0xfff72c5fc0 UTL  timezone:               Asia/Shanghai (CST, +0800) 
08/06 10:00:41.599812 0xfff72c5fc0 UTL  locale:                 zh_CN.UTF-8 
08/06 10:00:41.599815 0xfff72c5fc0 UTL  charset:                UTF-8 
08/06 10:00:41.599819 0xfff72c5fc0 UTL  numOfLogLines:          10000000 
08/06 10:00:41.599822 0xfff72c5fc0 UTL  asyncLog:               1 
08/06 10:00:41.599825 0xfff72c5fc0 UTL  debugFlag:              0 
08/06 10:00:41.599829 0xfff72c5fc0 UTL  rpcDebugFlag:           131 
08/06 10:00:41.599832 0xfff72c5fc0 UTL  tmrDebugFlag:           131 
08/06 10:00:41.599835 0xfff72c5fc0 UTL  cDebugFlag:             131 
08/06 10:00:41.599839 0xfff72c5fc0 UTL  jniDebugFlag:           131 
08/06 10:00:41.599842 0xfff72c5fc0 UTL  odbcDebugFlag:          131 
08/06 10:00:41.599845 0xfff72c5fc0 UTL  uDebugFlag:             131 
08/06 10:00:41.599849 0xfff72c5fc0 UTL  qDebugFlag:             131 
08/06 10:00:41.599852 0xfff72c5fc0 UTL  tsdbDebugFlag:          131 
08/06 10:00:41.599855 0xfff72c5fc0 UTL  gitinfo:                3264067e97300c84caa61ac909d548c9ca56de6b 
08/06 10:00:41.599859 0xfff72c5fc0 UTL  gitinfoOfInternal:      da88f4a2474737d1f9c76adcf0ff7fd0975e7342 
08/06 10:00:41.599862 0xfff72c5fc0 UTL  buildinfo:              Built by root at 2020-04-01 14:38 
08/06 10:00:41.599865 0xfff72c5fc0 UTL  version:                2.0.0.0 
08/06 10:00:41.599869 0xfff72c5fc0 UTL  maxBinaryDisplayWidth:  30 
08/06 10:00:41.599872 0xfff72c5fc0 UTL  os pageSize:            16384(KB)
08/06 10:00:41.599875 0xfff72c5fc0 UTL  os openMax:             1024
08/06 10:00:41.599878 0xfff72c5fc0 UTL  os streamMax:           16
08/06 10:00:41.599882 0xfff72c5fc0 UTL  os numOfCores:          8
08/06 10:00:41.599885 0xfff72c5fc0 UTL  os totalDisk:           0.000000(GB)
08/06 10:00:41.599889 0xfff72c5fc0 UTL  os totalMemory:         64651(MB)
08/06 10:00:41.599895 0xfff72c5fc0 UTL  os sysname:             Linux
08/06 10:00:41.599899 0xfff72c5fc0 UTL  os nodename:            srv01
08/06 10:00:41.599902 0xfff72c5fc0 UTL  os release:             4.19.0-loongson-3-server
08/06 10:00:41.599906 0xfff72c5fc0 UTL  os version:             #1187 SMP PREEMPT Wed Mar 25 22:36:49 CST 2020
08/06 10:00:41.599909 0xfff72c5fc0 UTL  os machine:             mips64
08/06 10:00:41.599912 0xfff72c5fc0 UTL ==================================

**Comment by localvar** [comment]
您可以查看一下服务器是否配置了 hostname 吗？谢谢
```shell
$ hostname
```

**Comment by jerryuhoo** [comment]
> 您可以查看一下服务器是否配置了 hostname 吗？谢谢
> 
> ```shell
> $ hostname
> ```

srv01

**Comment by sangshuduo** [comment]
@jerryuhoo 这个问题解决了吗？

**Comment by jerryuhoo** [comment]
> @jerryuhoo 这个问题解决了吗？

后来没有试，换了restful协议了
