### ISSUE TITLE
适用于这种场景日志存储吗？

### ISSUE THREAD

**Issue by elyshow** [taosdata/TDengine#2945]
场景：
单条日志有30+的字段，大小平均50K，一秒大概会有10w条日志入库
使用微秒作为时间粒度存储，可以保证时间戳不会重复

日志写入的话，应该会采用import csv的方式，而不是insert的形式（因为sql单条不大于16K）
顺便，全部用csv来导入的话，会不会影响查询性能？

**Comment by elyshow** [comment]
因为时间戳能保证不一致，所以用不到超级表，单表必然会超10亿条的存储

**Comment by superbool** [comment]
日志的话用ELk更合适吧，索引，搜索啥的应该会更方便。

**Comment by elyshow** [comment]
> 日志的话用ELk更合适吧，索引，搜索啥的应该会更方便。

是的，clickhouse也不错，但是tdengine是国货之光呀~

**Comment by jtao1735** [comment]
> > 日志的话用ELk更合适吧，索引，搜索啥的应该会更方便。
> 
> 是的，clickhouse也不错，但是tdengine是国货之光呀~

如果是机器、传感器采集的数据，是相当的合适。但如果是我们开发人员平常的日志文件，TDengine目前不是好的选择，因为它没有强大的文本搜索功能

**Comment by elyshow** [comment]
> > > 日志的话用ELk更合适吧，索引，搜索啥的应该会更方便。
> > 
> > 
> > 是的，clickhouse也不错，但是tdengine是国货之光呀~
> 
> 如果是机器、传感器采集的数据，是相当的合适。但如果是我们开发人员平常的日志文件，TDengine目前不是好的选择，因为它没有强大的文本搜索功能

OK。感谢回复~
