### ISSUE TITLE
jdbc failed to connect to server 

### ISSUE THREAD

**Issue by vannewang** [taosdata/TDengine#2947]
我使用docker在ubuntu里面部署了服务端，然后用java JDBC 2.0进行连接，报错com/taosdata/jdbc/TSDBDriver has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

1. docker部署状态
![52bc9969c324ae33af90df1bfb22d6c](https://user-images.githubusercontent.com/46670766/89487311-af776780-d7d7-11ea-8878-2b409d2c3625.png)
2. maven 版本  阿里云仓库
![7c9c6a129aba747e30002ff73812465](https://user-images.githubusercontent.com/46670766/89487369-d3d34400-d7d7-11ea-84da-157c651e8658.png)
3. yml配置
![add73e40bdf1d4e31decfda6b4f4449](https://user-images.githubusercontent.com/46670766/89487404-ec435e80-d7d7-11ea-91b2-8ed7045299ce.png)

4.启动报的错误

![36354dbcad59f26ae68d7839293fff7](https://user-images.githubusercontent.com/46670766/89487436-01b88880-d7d8-11ea-80bb-d145dcaf629c.png)

**Comment by vannewang** [comment]
taos-jdbcdriver-2.0.1.jar 里面的MANIFEST.MF文件  build-jdk 是11.0.8 ,我的错误和这个有关系吗,图片如下：

![image](https://user-images.githubusercontent.com/46670766/89496751-882b9500-d7ed-11ea-9e2e-aa32e556751c.png)

**Comment by xiaopingcs** [comment]
图片看不见，我记得2.0.1使用java 1.8编译的，如果是11.0.8的话，你可能需要升级一下Java。不过这个版本还有一个小问题，我们已经修复，麻烦你稍等，今天晚点的时候我会发布一个修复之后的版本，到时我会使用java 1.8进行编译。

**Comment by vannewang** [comment]
目前我已升级至 jdk11.0.8 ,连接时显示无法连接服务器，
 init datasource error, url: jdbc:TAOS://192.168.35.55:7030/log

java.sql.SQLException: TDengine Error: failed to connect to server

**Comment by xiaopingcs** [comment]
2.0移除了log库，所以连不上，而且建议加上用户名，密码。
示例： jdbc:TSDB://127.0.0.1:0/db?user=root&password=your_password
