### ISSUE TITLE
taos客户端 -p 参数无效

### ISSUE THREAD

**Issue by BearTian** [taosdata/TDengine#2950]
### 修改root密码后， shell 中直接输入taos 登陆失败，如图：
![image](https://user-images.githubusercontent.com/20335105/89501080-561e3100-d7f5-11ea-9348-6c78d2099a6f.png)

### 修改taos.cfg 密码后扔登陆失败，如图
![image](https://user-images.githubusercontent.com/20335105/89501167-75b55980-d7f5-11ea-8031-be4af7d8bccb.png)

### shell中使用 -p 参数直接指定命令扔登陆失败
![image](https://user-images.githubusercontent.com/20335105/89501271-a1d0da80-d7f5-11ea-9764-08918a30f05b.png)

### Version:2.0.0.0

**Comment by Shawshank-Smile** [comment]
![image](https://user-images.githubusercontent.com/46439638/89501453-f3796500-d7f5-11ea-9663-cbeb41b125a8.png)

[root@192 TDengine-server]# taos

Welcome to the TDengine shell from Linux, Client Version:2.0.0.0
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

taos> alter user root pass '123asd';
Query OK, 0 row(s) affected (0.013033s)

taos> q
[root@192 TDengine-server]# taos -u root -p

Welcome to the TDengine shell from Linux, Client Version:2.0.0.0
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

Enter password: 
taos> q
[root@192 TDengine-server]# taos -u root -p 123asd
taos: Too many arguments
Try `taos --help' or `taos --usage' for more information.
