### ISSUE TITLE
cannot import data after upgrade TDengine in Centos 7

### ISSUE THREAD

**Issue by ElephantPretty** [taosdata/TDengine#2953]
**Bug Description**
source data.sql 导入命令无法执行成功（1.6.5.6）
taosdump -N 1000 --all-databases -o test1.sql 导出命令无法执行成功 （1.6.5.6）

**To Reproduce**
1.使用taosdump导出数据，taosdump -N 1000 --all-databases -o testzhang.sql
2.卸载原有版本的TDengine1.6.5.6(rpm -e TDengine)
3.安装新版本的TDengine1.6.5.9（rpm -iv TDengine-server-1.6.5.9-Linux-x64.rpm 
）
4. 我在数据库中写了一个数据来测试导出（准备导出的数据库为db1）
![1](https://user-images.githubusercontent.com/49465384/89505674-9208c480-d7fc-11ea-9e42-1a24804ada18.png)
执行导出所有数据库命令后报第一个错
![2](https://user-images.githubusercontent.com/49465384/89505938-eca22080-d7fc-11ea-97cc-de015069529e.png)
我在尝试导入此前旧版本数据库导出的文件testzhang.sql时，也发生了错误
![3](https://user-images.githubusercontent.com/49465384/89506170-4efb2100-d7fd-11ea-860f-56d3e3889cb9.png)
![4](https://user-images.githubusercontent.com/49465384/89506185-54f10200-d7fd-11ea-9a63-4b2526a51a8e.png)
![5](https://user-images.githubusercontent.com/49465384/89506251-6cc88600-d7fd-11ea-8bc1-26d8f36e6728.png)
**Expected Behavior**
公司交代我连接远程服务器，把数据备份的同时卸载掉TDengine，安装新版本后导入旧版本数据

**Screenshots**

**Environment (please complete the following information):**
 - OS: CentOS 7.6.1810
 - TDengine Version [1.6.5.6、1.6.5.9]

**Additional Context**
我后面发现，我在第一次卸载掉旧版本，查看新版本数据库时会存在除了log数据库外另一个数据库db2,不过我当时以为是安装自带的，后面发现安装只会自带一个库，也就是log，我删除的db2数据库其实是旧版本的生产数据。。。

**Comment by Aries-Lee1991** [comment]
您好，现在已经更新2.0版本了，大家都已经逐步迁移过来了，请先升级，谢谢。

**Comment by jixinggaozhao9** [comment]
> 您好，现在已经更新2.0版本了，大家都已经逐步迁移过来了，请先升级，谢谢。

不升级版本的话会有什么问题吗

**Comment by ElephantPretty** [comment]
> 您好，现在已经更新2.0版本了，大家都已经逐步迁移过来了，请先升级，谢谢。

你好，实际情况下升级不了，这不是个人测试，属于实际应用，我这边假如单方面升级。。。另外一边也需要2.0对接。所以暂时无法升级。

**Comment by Aries-Lee1991** [comment]
> > 您好，现在已经更新2.0版本了，大家都已经逐步迁移过来了，请先升级，谢谢。
> 
> 你好，实际情况下升级不了，这不是个人测试，属于实际应用，我这边假如单方面升级。。。另外一边也需要2.0对接。所以暂时无法升级。

请联系 support@taosdata.com，具体咨询，目前就是1.6的bug，我们逐步不再维护了。

**Comment by jixinggaozhao9** [comment]
> > > 您好，现在已经更新2.0版本了，大家都已经逐步迁移过来了，请先升级，谢谢。
> > 
> > 
> > 你好，实际情况下升级不了，这不是个人测试，属于实际应用，我这边假如单方面升级。。。另外一边也需要2.0对接。所以暂时无法升级。
> 
> 请联系[support@taosdata.com](mailto:support@taosdata.com)，具体咨询，目前就是1.6的bug，我们逐步不再维护了。

我现在换成2.0版本，安装成功之后，查看启动状态，是启动成功的，但是我执行taos命令进不去taos数据库，你知道怎么回事吗，这个问题我在1.6.5.9里面也存在这样的情况

**Comment by jixinggaozhao9** [comment]
> > > 您好，现在已经更新2.0版本了，大家都已经逐步迁移过来了，请先升级，谢谢。
> > 
> > 
> > 你好，实际情况下升级不了，这不是个人测试，属于实际应用，我这边假如单方面升级。。。另外一边也需要2.0对接。所以暂时无法升级。
> 
> 请联系[support@taosdata.com](mailto:support@taosdata.com)，具体咨询，目前就是1.6的bug，我们逐步不再维护了。

我现在升级的是2.0版本，为什么我导出数据的时候会多出那么多sql文件呢，不是应该是一个吗
![image](https://user-images.githubusercontent.com/42602339/90002123-d4327a00-dcc4-11ea-8404-c63e60ef41da.png)

**Comment by xiaopingcs** [comment]
不好意思，忘记回复了，这个看你的文件应该是按表导出的。如果你还有连接数据库的问题，麻烦你再提新的issue，实在抱歉。我们github现在每天有专人值班，肯定会及时回复的。我先把这个问题关闭掉。
