### ISSUE TITLE
Ver 2.0.0 cluster try add dnode failed

### ISSUE THREAD

**Issue by Janus-Xu** [taosdata/TDengine#2954]
**Bug Description**
尝试2.0.0.0版本集群配置失败。
两台机器内网配置hostname后，分别rpm安装tdengine；
按要求在01添加自己的hostname到taos.cfg启动作为第一个节点；
在02添加01hostname，加入集群，
再在01里面添加节点，但02始终报错DND ERROR status rsp is received, error:Unable to establish connection。
无法正常启动。

telnet确认双方端口是可以访问的；
内网通讯且防火墙关闭状态；

**Expected Behavior**

集群配置成功。两个节点在线。

**Screenshots**
01日志配置：
![image](https://user-images.githubusercontent.com/6883877/89511549-a5b82900-d804-11ea-92eb-e2ef7a4c76c7.png)

01启动成功：
![image](https://user-images.githubusercontent.com/6883877/89511612-bcf71680-d804-11ea-943d-76cf31dd924a.png)

02日志配置：
![image](https://user-images.githubusercontent.com/6883877/89511644-c7b1ab80-d804-11ea-9e72-60508d2c9cc6.png)

02启动失败：
![image](https://user-images.githubusercontent.com/6883877/89511675-d0a27d00-d804-11ea-86c3-bed498e27c6b.png)

01里面查看节点信息，02始终离线

![image](https://user-images.githubusercontent.com/6883877/89511771-ec0d8800-d804-11ea-9efa-f4ee9ccea363.png)

互相telnet正常
![image](https://user-images.githubusercontent.com/6883877/89511862-047da280-d805-11ea-86df-8c9d176b3618.png)
![image](https://user-images.githubusercontent.com/6883877/89511885-0a738380-d805-11ea-9d98-7f968e5bc21a.png)

**Environment (please complete the following information):**
 - OS: [CentOS Linux release 7.8.2003 (Core)]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 2.0.0.0]

**Additional Context**

**Comment by guanshengliang** [comment]
不好意思，看不到图片。
您将/var/lib/taos /var/log/taos的内容都清空之后，在配置文件中增加一行debugFlag 135 ，然后重复之前的配置步骤。
将/var/log/taos/taosd*打成压缩包，上传到github或者其他网盘，以便我进行分析。

**Comment by guanshengliang** [comment]
这个已经很明显是网络问题02与01之间无法建立连接，要确保6030-6040的TCP和UDP端口是互通的。
请  @plum-lihui  继续协助处理此问题

**Comment by plum-lihui** [comment]
我们有一个工具，验证客户端和服务端之间是否满足tdengine的通讯。主要就是测试端口是否可达。先停止taosd，然后在服务端启动taosServer ，然后再在客户端启动taosClient。结果会显示需要的端口是否ok。
[networkTools.zip](https://github.com/taosdata/TDengine/files/5044548/networkTools.zip)
