### ISSUE TITLE
taos client cannot connect to taosd

### ISSUE THREAD

**Issue by jixinggaozhao9** [taosdata/TDengine#2956]
[root@localhost ~]# rpm -iv TDengine-server-2.0.0.0-Linux-x64.rpm
软件包准备中...
TDengine-2.0.0.0-3.x86_64
Start to install TDEngine...
Created symlink from /etc/systemd/system/multi-user.target.wants/taosd.service to /etc/systemd/system/taosd.service.

Enter FQDN:port (like h1.taosdata.com:6030) of an existing TDengine cluster node to join
OR leave it blank to build one:
To configure TDengine : edit /etc/taos/taos.cfg
To start TDengine     : sudo systemctl start taosd
To access TDengine    : use taos in shell

TDengine is installed successfully!
[root@localhost ~]# systemctl start taosd
[root@localhost ~]# systemctl status taosd
● taosd.service - TDengine server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: disabled)
   Active: active (running) since 四 2020-08-06 17:47:30 CST; 11s ago
 Main PID: 21510 (taosd)
   CGroup: /system.slice/taosd.service
           └─21510 /usr/bin/taosd

8月 06 17:47:30 localhost.localdomain systemd[1]: Started TDengine server service.
8月 06 17:47:30 localhost.localdomain TDengine:[21510]: Starting TDengine service...
8月 06 17:47:30 localhost.localdomain TDengine:[21510]: Started TDengine service successfully.
[root@localhost ~]# taos
Usage: taos [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  about      Print information about Taos
  bio        Lookup Taos personell bio information.
  contact    Send a contact request to taos
  subscribe  Send a service subscription request to taos
[root@localhost ~]# 

上面是我执行的的安装代码和查询，不知道为什么一直进不去taos数据库呢

**Comment by linye123456** [comment]
同问!
linux CentOS Linux release 7.6.1810 (Core) 
version TDengine-server-2.0.0.0-Linux-x64.tar.gz

就一台centos 安装 
 Enter FQDN:port (like h1.taosdata.com:6030) of an existing TDengine cluster node to join
OR leave it blank to build one:
这个 什么也没输入

**Comment by linye123456** [comment]
问题解决了，由于第一次  安装时  leave it blank to build one:  输入了    hostname:6030 ;启动后报这个错；
没有解决就直接卸载 后又直接安装，还报这个问题；
解决方案：
rmtaos 
rm -rf /etc/taos/ 
rm -rf /var/log/taos/
然后 
重新安装  即成功！

**Comment by jixinggaozhao9** [comment]
> 问题解决了，由于第一次安装时留空建立一个：输入了主机名：6030;启动后报这个错，
> 没有解决就直接卸载后又直接安装，还报这个问题;
> 解决方案：
> rmtaos
> RM - rf / etc / taos /
> rm -rf / var / log / taos /
> 然后
> 重新安装即成功！

我通过这种方法还是实现不成功的

**Comment by plum-lihui** [comment]
您能够将taos的log文件发上来我们分析一下么？缺省应该在/var/log/taos/目录下。

**Comment by plum-lihui** [comment]
Enter FQDN:port (like h1.taosdata.com:6030) of an existing TDengine cluster node to join
OR leave it blank to build one:
对于这个提示，在第一个节点安装的时候，不需要输入任何东西，直接回撤就好。后续新增节点，需要加入集群时，才可以输入已有集群中的一个可用节点的fqdn，或者也可以不输入，而是在启动前，在配置文件里面配置集群中可用节点的fqdn。

**Comment by jixinggaozhao9** [comment]
> 输入FQDN：现有TDengine群集节点的端口（如h1.taosdata.com:6030）加入
> 或留空建立一个：
> 对于这个提示，在第一个节点安装的时候，不需要输入任何东西，直接回撤就好。后续补充例程，需要加入合并时，才可以输入已有的中的一个可用例程的fqdn，或者也可以不输入，而是在启动前，在配置文件中配置可用的中可用例程的fqdn。

这个我在开始第一部的时候没有输入什么节点，我不知道怎么把log日志文件传递上来，我给你复制一部分日志上的内容
log内容：
==================================================
                new log file                      
==================================================
08/07 09:27:23.608200 0x7f8bbfe2a740 UTL localEp is: localhost:6030
08/07 09:27:23.609346 0x7f8bbfe2a740 UTL timezone not configured, set to system default: (CST, +0800)
08/07 09:27:23.609510 0x7f8bbfe2a740 UTL ERROR locale not configured, set to system default:zh_CN.UTF-8
08/07 09:27:23.609549 0x7f8bbfe2a740 UTL WARN charset not configured, set to system default:UTF-8
08/07 09:27:23.609672 0x7f8bbfe2a740 UTL    taos config & system info:
08/07 09:27:23.609689 0x7f8bbfe2a740 UTL ==================================
08/07 09:27:23.609704 0x7f8bbfe2a740 UTL  firstEp:                localhost:6030 
08/07 09:27:23.609719 0x7f8bbfe2a740 UTL  secondEp:               localhost:6030 
08/07 09:27:23.609734 0x7f8bbfe2a740 UTL  fqdn:                   localhost 
08/07 09:27:23.609750 0x7f8bbfe2a740 UTL  serverPort:             6030 
08/07 09:27:23.609765 0x7f8bbfe2a740 UTL  configDir:              /etc/taos 
08/07 09:27:23.609780 0x7f8bbfe2a740 UTL  logDir:                 /var/log/taos 
08/07 09:27:23.609795 0x7f8bbfe2a740 UTL  scriptDir:              /etc/taos 
08/07 09:27:23.609809 0x7f8bbfe2a740 UTL  dataDir:                /var/lib/taos 
08/07 09:27:23.609824 0x7f8bbfe2a740 UTL  arbitrator:              
08/07 09:27:23.609839 0x7f8bbfe2a740 UTL  numOfThreadsPerCore:    1.000000 
08/07 09:27:23.609885 0x7f8bbfe2a740 UTL  ratioOfQueryThreads:    0.500000 
08/07 09:27:23.609902 0x7f8bbfe2a740 UTL  numOfMnodes:            3 
08/07 09:27:23.609917 0x7f8bbfe2a740 UTL  vnodeBak:               1 
08/07 09:27:23.609932 0x7f8bbfe2a740 UTL  telemetryReporting:     1 
08/07 09:27:23.609947 0x7f8bbfe2a740 UTL  balance:                1 
08/07 09:27:23.609961 0x7f8bbfe2a740 UTL  balanceInterval:        300 
08/07 09:27:23.609976 0x7f8bbfe2a740 UTL  role:                   0 
08/07 09:27:23.609991 0x7f8bbfe2a740 UTL  maxTmrCtrl:             512 
08/07 09:27:23.610005 0x7f8bbfe2a740 UTL  monitorInterval:        30(s)
08/07 09:27:23.610020 0x7f8bbfe2a740 UTL  offlineThreshold:       8640000(s)
08/07 09:27:23.610035 0x7f8bbfe2a740 UTL  rpcTimer:               1000(ms)
08/07 09:27:23.610049 0x7f8bbfe2a740 UTL  rpcMaxTime:             600(s)
08/07 09:27:23.610064 0x7f8bbfe2a740 UTL  statusInterval:         1(s)
08/07 09:27:23.610079 0x7f8bbfe2a740 UTL  shellActivityTimer:     3(s)
08/07 09:27:23.610094 0x7f8bbfe2a740 UTL  tableMetaKeepTimer:     7200(s)
08/07 09:27:23.610108 0x7f8bbfe2a740 UTL  minSlidingTime:         10(ms)
08/07 09:27:23.610124 0x7f8bbfe2a740 UTL  minIntervalTime:        10(ms)
08/07 09:27:23.610139 0x7f8bbfe2a740 UTL  maxStreamCompDelay:     20000(ms)
08/07 09:27:23.610154 0x7f8bbfe2a740 UTL  maxFirstStreamCompDelay:10000(ms)
08/07 09:27:23.610169 0x7f8bbfe2a740 UTL  retryStreamCompDelay:   10(ms)
08/07 09:27:23.610183 0x7f8bbfe2a740 UTL  streamCompDelayRatio:   0.100000 
08/07 09:27:23.610200 0x7f8bbfe2a740 UTL  maxVgroupsPerDb:        0 
08/07 09:27:23.610214 0x7f8bbfe2a740 UTL  maxTablesPerVnode:      1000000 
08/07 09:27:23.610256 0x7f8bbfe2a740 UTL  minTablesPerVnode:      1000 
08/07 09:27:23.610272 0x7f8bbfe2a740 UTL  tableIncStepPerVnode:   1000 
08/07 09:27:23.610287 0x7f8bbfe2a740 UTL  cache:                  16(Mb)
08/07 09:27:23.610302 0x7f8bbfe2a740 UTL  blocks:                 6 
08/07 09:27:23.610317 0x7f8bbfe2a740 UTL  days:                   10 
08/07 09:27:23.610331 0x7f8bbfe2a740 UTL  keep:                   3650 
08/07 09:27:23.610345 0x7f8bbfe2a740 UTL  minRows:                100 
08/07 09:27:23.610360 0x7f8bbfe2a740 UTL  maxRows:                4096 
08/07 09:27:23.610368 0x7f8bbfe2a740 UTL  comp:                   2 
08/07 09:27:23.610383 0x7f8bbfe2a740 UTL  walLevel:               1 
08/07 09:27:23.610397 0x7f8bbfe2a740 UTL  fsync:                  3000 
08/07 09:27:23.610411 0x7f8bbfe2a740 UTL  replica:                1 
08/07 09:27:23.610426 0x7f8bbfe2a740 UTL  quorum:                 1 
08/07 09:27:23.610441 0x7f8bbfe2a740 UTL  compressMsgSize:        -1 
08/07 09:27:23.610455 0x7f8bbfe2a740 UTL  maxSQLLength:           65480(byte)
08/07 09:27:23.610462 0x7f8bbfe2a740 UTL  maxNumOfOrderedRes:     100000 
08/07 09:27:23.610484 0x7f8bbfe2a740 UTL  timezone:                (CST, +0800) 
08/07 09:27:23.610499 0x7f8bbfe2a740 UTL  locale:                 zh_CN.UTF-8 
08/07 09:27:23.610514 0x7f8bbfe2a740 UTL  charset:                UTF-8 
08/07 09:27:23.610529 0x7f8bbfe2a740 UTL  maxShellConns:          5000 
08/07 09:27:23.610537 0x7f8bbfe2a740 UTL  maxConnections:         5000 
08/07 09:27:23.610552 0x7f8bbfe2a740 UTL  minimalLogDirGB:        0.100000(GB)
08/07 09:27:23.610568 0x7f8bbfe2a740 UTL  minimalTmpDirGB:        0.100000(GB)
08/07 09:27:23.610583 0x7f8bbfe2a740 UTL  minimalDataDirGB:       0.500000(GB)
08/07 09:27:23.610598 0x7f8bbfe2a740 UTL  mnodeEqualVnodeNum:     4 
08/07 09:27:23.610613 0x7f8bbfe2a740 UTL  http:                   1 
08/07 09:27:23.610627 0x7f8bbfe2a740 UTL  mqtt:                   0 
08/07 09:27:23.610636 0x7f8bbfe2a740 UTL  monitor:                0 
08/07 09:27:23.610650 0x7f8bbfe2a740 UTL  httpCacheSessions:      1000 
08/07 09:27:23.610665 0x7f8bbfe2a740 UTL  httpEnableRecordSql:    0 
08/07 09:27:23.610679 0x7f8bbfe2a740 UTL  telegrafUseFieldNum:    0 
08/07 09:27:23.610688 0x7f8bbfe2a740 UTL  httpMaxThreads:         2 
08/07 09:27:23.610702 0x7f8bbfe2a740 UTL  restfulRowLimit:        10240 
08/07 09:27:23.610716 0x7f8bbfe2a740 UTL  numOfLogLines:          10000000 
08/07 09:27:23.610743 0x7f8bbfe2a740 UTL  asyncLog:               1 
08/07 09:27:23.610748 0x7f8bbfe2a740 UTL  debugFlag:              0 
08/07 09:27:23.610758 0x7f8bbfe2a740 UTL  mDebugFlag:             135 
08/07 09:27:23.610763 0x7f8bbfe2a740 UTL  dDebugFlag:             135 
08/07 09:27:23.610773 0x7f8bbfe2a740 UTL  sDebugFlag:             135 
08/07 09:27:23.610778 0x7f8bbfe2a740 UTL  wDebugFlag:             135 
08/07 09:27:23.610787 0x7f8bbfe2a740 UTL  sdbDebugFlag:           135 
08/07 09:27:23.610792 0x7f8bbfe2a740 UTL  rpcDebugFlag:           131 
08/07 09:27:23.610802 0x7f8bbfe2a740 UTL  tmrDebugFlag:           131 
08/07 09:27:23.610806 0x7f8bbfe2a740 UTL  cDebugFlag:             131 
08/07 09:27:23.610816 0x7f8bbfe2a740 UTL  jniDebugFlag:           131 
08/07 09:27:23.610821 0x7f8bbfe2a740 UTL  odbcDebugFlag:          131 
08/07 09:27:23.610830 0x7f8bbfe2a740 UTL  uDebugFlag:             131 
08/07 09:27:23.610835 0x7f8bbfe2a740 UTL  httpDebugFlag:          131 
08/07 09:27:23.610844 0x7f8bbfe2a740 UTL  mqttDebugFlag:          131 
08/07 09:27:23.610849 0x7f8bbfe2a740 UTL  monitorDebugFlag:       131 
08/07 09:27:23.610859 0x7f8bbfe2a740 UTL  qDebugFlag:             131 
08/07 09:27:23.610864 0x7f8bbfe2a740 UTL  vDebugFlag:             131 
08/07 09:27:23.610873 0x7f8bbfe2a740 UTL  tsdbDebugFlag:          131 
08/07 09:27:23.610878 0x7f8bbfe2a740 UTL  tscEnableRecordSql:     0 
08/07 09:27:23.610888 0x7f8bbfe2a740 UTL  enableCoreFile:         0 
08/07 09:27:23.610893 0x7f8bbfe2a740 UTL  gitinfo:                8df8b7d9930342dd34ba13df160a7d538fad7bc7 
08/07 09:27:23.610903 0x7f8bbfe2a740 UTL  gitinfoOfInternal:       
08/07 09:27:23.610909 0x7f8bbfe2a740 UTL  buildinfo:              Built by root at 2020-08-03 17:21 
08/07 09:27:23.610913 0x7f8bbfe2a740 UTL  version:                2.0.0.0 
08/07 09:27:23.610923 0x7f8bbfe2a740 UTL  maxBinaryDisplayWidth:  30 
08/07 09:27:23.610930 0x7f8bbfe2a740 UTL  os pageSize:            4096(KB)
08/07 09:27:23.610939 0x7f8bbfe2a740 UTL  os openMax:             65536
08/07 09:27:23.610944 0x7f8bbfe2a740 UTL  os streamMax:           16
08/07 09:27:23.610954 0x7f8bbfe2a740 UTL  os numOfCores:          8
08/07 09:27:23.610958 0x7f8bbfe2a740 UTL  os totalDisk:           43.974613(GB)
08/07 09:27:23.610971 0x7f8bbfe2a740 UTL  os totalMemory:         7820(MB)
08/07 09:27:23.610979 0x7f8bbfe2a740 UTL  os sysname:             Linux
08/07 09:27:23.610988 0x7f8bbfe2a740 UTL  os nodename:            localhost.localdomain
08/07 09:27:23.610992 0x7f8bbfe2a740 UTL  os release:             3.10.0-957.27.2.el7.x86_64
08/07 09:27:23.611002 0x7f8bbfe2a740 UTL  os version:             #1 SMP Mon Jul 29 17:46:05 UTC 2019
08/07 09:27:23.611007 0x7f8bbfe2a740 UTL  os machine:             x86_64
08/07 09:27:23.611015 0x7f8bbfe2a740 UTL ==================================
08/07 09:27:23.611020 0x7f8bbfe2a740 DND start to initialize TDengine on localhost:6030
08/07 09:27:23.611074 0x7f8bbfe2a740 DND storage directory is initialized
08/07 09:27:23.611098 0x7f8bbfe2a740 DND dnode read is opened, min worker:8 max worker:16
08/07 09:27:23.611114 0x7f8bbfe2a740 DND dnode write is opened, max worker 8
08/07 09:27:23.611132 0x7f8bbfe2a740 DND dnode mread is opened
08/07 09:27:23.611147 0x7f8bbfe2a740 DND dnode mwrite is opened
08/07 09:27:23.611158 0x7f8bbfe2a740 DND dnode mpeer is opened
08/07 09:27:23.612093 0x7f8bbfe2a740 DND inter-dnodes rpc client is opened
08/07 09:27:23.612424 0x7f8bbfe2a740 DND inter-dnodes RPC server is opened
08/07 09:27:23.612524 0x7f8bbfe2a740 DND read numOfVnodes successed, dnodeId:1
08/07 09:27:23.612611 0x7f8bbfe2a740 DND read mnode epSet successed, numOfEps:1 inUse:0
08/07 09:27:23.612624 0x7f8bbfe2a740 DND mnode:1, localhost:6030
08/07 09:27:23.612760 0x7f8bbfe2a740 DND start 8 threads to open 0 vnodes
08/07 09:27:23.612776 0x7f8bbfe2a740 DND there are total vnodes:0, openned:0 failed:0
08/07 09:27:23.612782 0x7f8bbfe2a740 DND dnode mgmt is initialized
08/07 09:27:23.612819 0x7f8bbfe2a740 MND starting to initialize mnode ...
08/07 09:27:23.612867 0x7f8bbfe2a740 DND dnode mwrite worker:0 is launched, total:1
08/07 09:27:23.612875 0x7f8bbfe2a740 DND dnode mwrite queue:0x1539660 is allocated
08/07 09:27:23.612907 0x7f8bbfe2a740 DND dnode mread worker:0 is launched, total:4
08/07 09:27:23.612955 0x7f8bbfe2a740 DND dnode mread worker:1 is launched, total:4
08/07 09:27:23.612988 0x7f8bbfe2a740 DND dnode mread worker:2 is launched, total:4
08/07 09:27:23.613027 0x7f8bbfe2a740 DND dnode mread worker:3 is launched, total:4
08/07 09:27:23.613034 0x7f8bbfe2a740 DND dnode mread queue:0x1539ac0 is allocated
08/07 09:27:23.613071 0x7f8bbfe2a740 DND dnode mpeer worker:0 is launched, total:1
08/07 09:27:23.613078 0x7f8bbfe2a740 DND dnode mpeer queue:0x15396c0 is allocated
08/07 09:27:23.613148 0x7f8bbfe2a740 MND table:cluster, hash is created
08/07 09:27:23.613169 0x7f8bbfe2a740 MND table:accounts, hash is created
08/07 09:27:23.613184 0x7f8bbfe2a740 MND table:users, hash is created
08/07 09:27:23.613204 0x7f8bbfe2a740 MND table:dnodes table is created
08/07 09:27:23.613218 0x7f8bbfe2a740 MND table:dbs table is created
08/07 09:27:23.613261 0x7f8bbfe2a740 MND table:vgroups is created
08/07 09:27:23.613277 0x7f8bbfe2a740 MND table:stables is created
08/07 09:27:23.613297 0x7f8bbfe2a740 MND table:ctables is created
08/07 09:27:23.613310 0x7f8bbfe2a740 MND table:mnodes table is created
08/07 09:27:23.613357 0x7f8bbfe2a740 MND sdb write worker:0 is launched, total:1
08/07 09:27:23.613369 0x7f8bbfe2a740 MND sdb write queue:0x153c550 is allocated
08/07 09:27:23.613372 0x7f8bbfe2a740 MND sdb write is opened
08/07 09:27:23.613386 0x7f8bbfe2a740 WAL WAL module is initialized
08/07 09:27:23.613405 0x7f8bbfe2a740 SDB open sdb wal for restore
08/07 09:27:23.613445 0x7f8bbfe2a740 WAL wal:/var/lib/taos/mnode/wal, 1 files will be restored
08/07 09:27:23.613470 0x7f8bbfe2a740 WAL wal:/var/lib/taos/mnode/wal/wal0, start to restore
08/07 09:27:23.613498 0x7f8bbfe2a740 SDB table:cluster, record from wal/fwd is disposed, action:insert record:8b9d5d69-8515-4b82-be5b-af87f07b115b ver:1
08/07 09:27:23.613527 0x7f8bbfe2a740 SDB table:cluster, insert record:8b9d5d69-8515-4b82-be5b-af87f07b115b to hash, rowSize:60 numOfRows:1, msg:(nil)
08/07 09:27:23.613543 0x7f8bbfe2a740 SDB table:dnodes, record from wal/fwd is disposed, action:insert record:1 ver:2
08/07 09:27:23.613549 0x7f8bbfe2a740 SDB table:dnodes, insert record:1 to hash, rowSize:308 numOfRows:1, msg:(nil)
08/07 09:27:23.613562 0x7f8bbfe2a740 SDB table:mnodes, record from wal/fwd is disposed, action:insert record:1 ver:3
08/07 09:27:23.613566 0x7f8bbfe2a740 SDB table:mnodes, insert record:1 to hash, rowSize:20 numOfRows:1, msg:(nil)
08/07 09:27:23.613582 0x7f8bbfe2a740 SDB table:accounts, record from wal/fwd is disposed, action:insert record:root ver:4
08/07 09:27:23.613596 0x7f8bbfe2a740 SDB table:accounts, insert record:root to hash, rowSize:124 numOfRows:1, msg:(nil)
08/07 09:27:23.613613 0x7f8bbfe2a740 SDB table:users, record from wal/fwd is disposed, action:insert record:root ver:5
08/07 09:27:23.613621 0x7f8bbfe2a740 SDB table:users, insert record:root to hash, rowSize:84 numOfRows:1, msg:(nil)
08/07 09:27:23.613635 0x7f8bbfe2a740 SDB table:users, record from wal/fwd is disposed, action:insert record:monitor ver:6
08/07 09:27:23.613639 0x7f8bbfe2a740 SDB table:users, insert record:monitor to hash, rowSize:84 numOfRows:2, msg:(nil)
08/07 09:27:23.613648 0x7f8bbfe2a740 SDB table:users, record from wal/fwd is disposed, action:insert record:_root ver:7
08/07 09:27:23.613658 0x7f8bbfe2a740 SDB table:users, insert record:_root to hash, rowSize:84 numOfRows:3, msg:(nil)
08/07 09:27:23.613712 0x7f8bbfe2a740 MND cluster id is set to 8b9d5d69-8515-4b82-be5b-af87f07b115b
08/07 09:27:23.613727 0x7f8bbfe2a740 SDB table:cluster, is restored, numOfRows:1
08/07 09:27:23.613732 0x7f8bbfe2a740 SDB table:dnodes, is restored, numOfRows:1
08/07 09:27:23.613736 0x7f8bbfe2a740 MND update mnodes epSet, numOfEps:1 
08/07 09:27:23.613746 0x7f8bbfe2a740 MND mnode:1, for shell fqdn:localhost 6030
08/07 09:27:23.613755 0x7f8bbfe2a740 MND mnode:1, for peer fqdn:localhost 6035
08/07 09:27:23.613760 0x7f8bbfe2a740 MND mnode:1, ep:localhost:6030 master
08/07 09:27:23.613767 0x7f8bbfe2a740 SDB table:mnodes, is restored, numOfRows:1
08/07 09:27:23.613776 0x7f8bbfe2a740 SDB table:accounts, is restored, numOfRows:1
08/07 09:27:23.613780 0x7f8bbfe2a740 SDB table:users, is restored, numOfRows:3
08/07 09:27:23.613783 0x7f8bbfe2a740 SDB table:dbs, is restored, numOfRows:0
08/07 09:27:23.613786 0x7f8bbfe2a740 SDB table:vgroups, is restored, numOfRows:0
08/07 09:27:23.613789 0x7f8bbfe2a740 SDB table:stables, is restored, numOfRows:0
08/07 09:27:23.613793 0x7f8bbfe2a740 SDB table:ctables, is restored, numOfRows:0
08/07 09:27:23.613802 0x7f8bbfe2a740 SDB sdb is restored, ver:7 totalRows:7 numOfTables:9
08/07 09:27:23.613814 0x7f8bbfe2a740 SDB work as mnode, replica:1
08/07 09:27:23.613824 0x7f8bbfe2a740 SDB mnode:1, localhost:6040
08/07 09:27:23.614083 0x7f8bbfe2a740 SYN vgId:1 peer:localhost:6040, it is configured
08/07 09:27:23.614097 0x7f8bbfe2a740 SYN vgId:1, 1 replicas are configured, quorum:1 role:master
08/07 09:27:23.614115 0x7f8bbfe2a740 SDB mnode role changed from master to master
08/07 09:27:23.614128 0x7f8bbfe2a740 SDB update mnodes sync roles, total:1
08/07 09:27:23.614134 0x7f8bbfe2a740 SDB mnode:1, role:master
08/07 09:27:23.614145 0x7f8bbfe2a740 MND cluster id is set to 8b9d5d69-8515-4b82-be5b-af87f07b115b
08/07 09:27:23.614150 0x7f8bbfe2a740 MND update mnodes epSet, numOfEps:1 
08/07 09:27:23.614157 0x7f8bbfe2a740 MND mnode:1, for shell fqdn:localhost 6030
08/07 09:27:23.614162 0x7f8bbfe2a740 MND mnode:1, for peer fqdn:localhost 6035
08/07 09:27:23.614171 0x7f8bbfe2a740 MND mnode:1, ep:localhost:6030 master
08/07 09:27:23.614187 0x7f8bbfe2a740 MND balance start fp:0x461ac6 initialized
08/07 09:27:23.614197 0x7f8bbfe2a740 MND dnode:1 set access:0 to 0
08/07 09:27:23.614258 0x7f8bbfe2a740 MND mnode is initialized successfully
08/07 09:27:23.614545 0x7f8bbfe2a740 DND dnode mgmt timer is initialized
08/07 09:27:23.614883 0x7f8bbfe2a740 DND shell rpc server is opened
08/07 09:27:23.614928 0x7f8bbfe2a740 HTP start http server ...
08/07 09:27:23.615457 0x7f8bbfe2a740 DND TDengine is initialized successfully
08/07 09:27:23.615596 0x7f8b9ffff700 HTP http server init success at 6041
08/07 09:27:24.117463 0x7f8bacff9700 DND msg:status will be processed in mpeer queue
08/07 09:27:24.117552 0x7f8bacff9700 MND dnode:1, from offline to online
08/07 09:27:24.117672 0x7f8bb65e5700 DND module status:2 is received, start mnode module
08/07 09:27:24.117691 0x7f8bb65e5700 MND mnode module already started...
08/07 09:27:24.621714 0x7f8bb7e3d700 MND balance function is scheduled by event for 500 mseconds arrived
08/07 09:27:25.121787 0x7f8bacff9700 DND msg:status will be processed in mpeer queue
08/07 09:27:26.121893 0x7f8bacff9700 DND msg:status will be processed in mpeer queue
08/07 09:27:27.126840 0x7f8bacff9700 DND msg:status will be processed in mpeer queue
08/07 09:27:28.126772 0x7f8bacff9700 DND msg:status will be processed in mpeer queue
08/07 09:27:29.126788 0x7f8bacff9700 DND msg:status will be processed in mpeer queue
08/07 09:27:30.126832 0x7f8bacff9700 DND msg:status will be processed in mpeer queue
08/07 09:27:31.126839 0x7f8bacff9700 DND msg:status will be processed in mpeer queue
08/07 09:27:32.126824 0x7f8bacff9700 DND msg:status will be processed in mpeer queue
08/07 09:27:33.126807 0x7f8bacff9700 DND msg:status will be processed in mpeer queue
08/07 09:27:34.126785 0x7f8bacff9700 DND msg:status will be processed in mpeer queue
08/07 09:27:35.126776 0x7f8bacff9700 DND msg:status will be processed in mpeer queue
08/07 09:27:36.126862 0x7f8bacff9700 DND msg:status will be processed in mpeer queue
08/07 09:27:37.126836 0x7f8bacff9700 DND msg:status will be processed in mpeer queue
08/07 09:27:38.126850 0x7f8bacff9700 DND msg:status will be processed in mpeer queue

**Comment by jixinggaozhao9** [comment]
我这个情况在1.6.5.9和1.6.5.7都出现过，当时用的rpm版本，后来改成2.0版本rpm还是这样，然后我又安装了2.0tar版本试试，还是这样的问题

**Comment by plum-lihui** [comment]
不对，这个日志是taosd服务端的日志，我需要看taos客户端的日志。
taosdlog.x是服务端的，  taoslogx.x是客户端的日志。

**Comment by jixinggaozhao9** [comment]
> 不对，这个日志是taosd服务端的日志，我需要看taos客户端的日志
> 。taosdlog.x是服务端的，taoslogx.x是客户端的日志。

这个/var/log/taos路径下就只有这一个log日志，就是taosdlog.0这个日志，我把日志内容就传过去了

**Comment by jixinggaozhao9** [comment]
[taosdlog.0.txt](https://github.com/taosdata/TDengine/files/5039684/taosdlog.0.txt)
就只有这个日志，我把后缀加了txt，你可以看看，没有你说的客户端日志

**Comment by plum-lihui** [comment]
那你执行taos是在哪里执行的？是与taosd服务在同一台机器上么，还是在另外一台机器上？

**Comment by jixinggaozhao9** [comment]
> 那你执行taos是在哪里执行的？是与taosd服务在同一台机器上么，还是在另外一台机器上？

同一台机器上，taos不是直接装了服务器默认就有客户端了吗，我直接在运行taos就不行了，安装过程和展示过程标题粘贴的有执行代码，你可以看一下

**Comment by plum-lihui** [comment]
[root@localhost ~]# taos
Usage: taos [OPTIONS] COMMAND [ARGS]...

Options:
--help Show this message and exit.

Commands:
about Print information about Taos
bio Lookup Taos personell bio information.
contact Send a contact request to taos
subscribe Send a service subscription request to taos


从你提供的这个信息看，好像另外有一个执行文件也是taos，因为这个输出不是我们的taos输出的信息。两个程序重名了。
这样吧，你可以到/usr/local/taos/bin/taos 执行。看看能不能连上taosd服务。

**Comment by jixinggaozhao9** [comment]
> [root @ localhost〜]＃taos
> 用法：taos [OPTIONS] COMMAND [ARGS] ...
> 
> 选项：--
> help显示此消息并退出。
> 
> 命令：
> about打印有关
> Taos biolookup信息的信息。
> 联系人向taos发送联系请求
> 订阅向taos 发送服务订阅
> 
> 从你提供的这个信息看，好像另外有一个执行文件也是taos，因为这个输出不是我们的taos输出的信息。两个程序重名了。
> 这样吧，你可以到/ usr / local / taos / bin / taos执行。看看能不能连上taosd服务。

![image](https://user-images.githubusercontent.com/42602339/89618184-3737a180-d8be-11ea-8c3b-6ddfb6d92f60.png)
根据你说的，我去路径里面执行，还是和之前是一样的

**Comment by plum-lihui** [comment]
能加微信么，让我远程看一下。

**Comment by plum-lihui** [comment]
到/ usr / local / taos / bin /下，然后  ./taos   怎么执行。    如果直接taos的话，还是执行那个另外的taso程序

**Comment by plum-lihui** [comment]
安装、执行都没有了。估计就是其他安装的taos  与  tdengine的taos冲突了。导致无法直接执行taos。
重新将第三方的taos卸载干净后，应该就没有问题。
