### ISSUE TITLE
does table support tag as a filter?

### ISSUE THREAD

**Issue by theday112** [taosdata/TDengine#2959]
我想对单个普通表中做group by,group by的条件列在tags中，但用select在普通表中无法添加tags中的列作为查询条件，我是以设备唯一id作为普通表名，tags中没有添加设备唯一id，这样我上诉需求就实现不了了吗？

**Comment by johnnyhou327** [comment]
group by tbname

**Comment by sangshuduo** [comment]
no update, close it.
