### ISSUE TITLE
go语言demo中，指定端口无效

### ISSUE THREAD

**Issue by mxyue** [taosdata/TDengine#296]
tests/examples/go/src/taosapp/taosapp.go

db, err := sql.Open(taosDriverName, "root:taosdata@/tcp(127.0.0.1:230)/demodb") 
设置成任意正整数的端口都能正常运行，应该是端口未生效。都取了默认端口

**Comment by plum-lihui** [comment]
您用的是什么时候的版本？这个问题已经在8月1号修复过了，请取最新的版本测试。
多谢!

**Comment by mxyue** [comment]
请问你说的是 tdengine的版本还是， go的版本呢。 go驱动拉取的是最新的。

**Comment by plum-lihui** [comment]
tdengine的版本，其中connector/go中有修复。

**Comment by mxyue** [comment]
任然有问题哈。 tdengine用的1.6.1.6，connector今天拉取的master最新的代码，用的是你们的test里面的demo。我只把里面写的0那个端口设置为了12或者其他的值，任然可以把测试跑通。
