### ISSUE TITLE
update v2.0, Chinese unicode display for nchar field

### ISSUE THREAD

**Issue by sexbee** [taosdata/TDengine#2963]
**Bug Description**
deepin19  tdengine 2.0 

直接taos client  query 中文 nchar 字段，显示 正常；but td-connector query   则显示乱码。

for example ： name : "駩螋“

**Comment by sexbee** [comment]
推测是不是和 td2.0-connector 模块的文字代码转换有关。

**Comment by Shawshank-Smile** [comment]
![image](https://user-images.githubusercontent.com/46439638/89700576-d06bc400-d961-11ea-84e1-39cc2082f678.png)
https://www.taosdata.com/cn/documentation20/administrator/#服务端配置

**Comment by sexbee** [comment]
谢谢，直接用 taos client  来query 显示中文是正常的；但是从td2.0-connector 连接query 则显示为乱码，所以是否应该和client字符集无关？而且之前1.6版本的时候完全正常。

**Comment by sexbee** [comment]
这个无法解决吗？

**Comment by hjxilinx** [comment]
Problem solved?
