### ISSUE TITLE
taosdemo run failed 

### ISSUE THREAD

**Issue by xuyujie1991** [taosdata/TDengine#2964]
[root@hdfs1 TDengine-server]# taosdemo 
###################################################################
# Server IP:                         localhost:0
# User:                              root
# Password:                          taosdata
# Use metric:                        true
# Datatype of Columns:               int        
# Binary Length(If applicable):      -1
# Number of Columns per record:      3
# Number of Threads:                 10
# Number of Tables:                  10000
# Number of Data per Table:          100000
# Records/Request:                   1000
# Database name:                     test
# Table prefix:                      t
# Delete method:                     0
# Test time:                         2020-08-06 18:38:21
###################################################################

Press enter key to continue
Creating meters super table...
Failed to run create table if not exists test.meters (ts timestamp,f1 int,f2 ,f3 ) tags (areaid int, loc binary(10)), reason: invalid SQL: syntax error near ",f3 ) tags (areaid int, loc binary(10))"

**Comment by plum-lihui** [comment]
create table if not exists test.meters (ts timestamp,f1 int,f2 ,f3 ) tags (areaid int, loc binary(10)), reason: invalid SQL:

f3 前面少了一个数据类型。我们修改一下。

**Comment by sukkamehu** [comment]
+1 for this issue. I'm on MacOS Catalina w/ Docker. `taosdemo -b 'INT','FLOAT','BIGINT'` seems to work.

**Comment by shadow-shadow** [comment]
taosdemo -b 'INT','FLOAT','BIGINT'   
---------------------------------------------
  Centos 7亲测有效

**Comment by plum-lihui** [comment]
Good！
