### ISSUE TITLE
can not start taosd service

### ISSUE THREAD

**Issue by kinghtdom** [taosdata/TDengine#2965]
**General Questions**
无法启动taosd服务。
报错内容是：
`08/07 09:49:30.358821 0xfff64ee020 DND ERROR failed to read dnodeCfg.json, clusterId not found
段错误`
但是查看过dnodeCfg.json文件，是有内容的:
`{
  "dnodeId": 1,
  "clusterId": "591ff002-198c-4e6a-9494-92583e2e0ba2"
}`

这台服务器的配置是龙芯CPU，uos操作系统，安装的是taos v2.0版本，详细配置参数见下文
具体报错内容：
08/07 09:49:30.353268 0xfff64ee020 UTL localEp is: srv01:6030
08/07 09:49:30.354272 0xfff64ee020 UTL timezone not configured, set to system default:Asia/Shanghai (CST, +0800)
08/07 09:49:30.354486 0xfff64ee020 UTL ERROR locale not configured, set to system default:zh_CN.UTF-8
08/07 09:49:30.354577 0xfff64ee020 UTL WARN charset not configured, set to system default:UTF-8
08/07 09:49:30.354702 0xfff64ee020 UTL    taos config & system info:
08/07 09:49:30.354743 0xfff64ee020 UTL ==================================
08/07 09:49:30.354774 0xfff64ee020 UTL  firstEp:                srv01:6030 
08/07 09:49:30.354798 0xfff64ee020 UTL  secondEp:               srv01:6030 
08/07 09:49:30.354822 0xfff64ee020 UTL  fqdn:                   srv01 
08/07 09:49:30.354846 0xfff64ee020 UTL  serverPort:             6030 
08/07 09:49:30.354870 0xfff64ee020 UTL  configDir:              /etc/taos 
08/07 09:49:30.354896 0xfff64ee020 UTL  logDir:                 /var/log/taos 
08/07 09:49:30.354919 0xfff64ee020 UTL  scriptDir:              /etc/taos 
08/07 09:49:30.354947 0xfff64ee020 UTL  dataDir:                /var/lib/taos 
08/07 09:49:30.354993 0xfff64ee020 UTL  arbitrator:              
08/07 09:49:30.355022 0xfff64ee020 UTL  numOfThreadsPerCore:    1.000000 
08/07 09:49:30.355071 0xfff64ee020 UTL  ratioOfQueryThreads:    0.500000 
08/07 09:49:30.355107 0xfff64ee020 UTL  numOfMnodes:            3 
08/07 09:49:30.355136 0xfff64ee020 UTL  vnodeBak:               1 
08/07 09:49:30.355178 0xfff64ee020 UTL  telemetryReporting:     1 
08/07 09:49:30.355206 0xfff64ee020 UTL  balance:                1 
08/07 09:49:30.355234 0xfff64ee020 UTL  balanceInterval:        300 
08/07 09:49:30.355254 0xfff64ee020 UTL  role:                   0 
08/07 09:49:30.355277 0xfff64ee020 UTL  maxTmrCtrl:             512 
08/07 09:49:30.355301 0xfff64ee020 UTL  monitorInterval:        30(s)
08/07 09:49:30.355338 0xfff64ee020 UTL  offlineThreshold:       8640000(s)
08/07 09:49:30.355367 0xfff64ee020 UTL  rpcTimer:               1000(ms)
08/07 09:49:30.355400 0xfff64ee020 UTL  rpcMaxTime:             600(s)
08/07 09:49:30.355427 0xfff64ee020 UTL  statusInterval:         1(s)
08/07 09:49:30.355454 0xfff64ee020 UTL  shellActivityTimer:     3(s)
08/07 09:49:30.355474 0xfff64ee020 UTL  tableMetaKeepTimer:     7200(s)
08/07 09:49:30.355606 0xfff64ee020 UTL  minSlidingTime:         10(ms)
08/07 09:49:30.355655 0xfff64ee020 UTL  minIntervalTime:        10(ms)
08/07 09:49:30.355673 0xfff64ee020 UTL  maxStreamCompDelay:     20000(ms)
08/07 09:49:30.355687 0xfff64ee020 UTL  maxFirstStreamCompDelay:10000(ms)
08/07 09:49:30.355709 0xfff64ee020 UTL  retryStreamCompDelay:   10(ms)
08/07 09:49:30.355723 0xfff64ee020 UTL  streamCompDelayRatio:   0.100000 
08/07 09:49:30.355742 0xfff64ee020 UTL  maxVgroupsPerDb:        0 
08/07 09:49:30.355763 0xfff64ee020 UTL  maxTablesPerVnode:      1000000 
08/07 09:49:30.355777 0xfff64ee020 UTL  minTablesPerVnode:      1000 
08/07 09:49:30.355790 0xfff64ee020 UTL  tableIncStepPerVnode:   1000 
08/07 09:49:30.355803 0xfff64ee020 UTL  cache:                  16(Mb)
08/07 09:49:30.355816 0xfff64ee020 UTL  blocks:                 6 
08/07 09:49:30.355830 0xfff64ee020 UTL  days:                   10 
08/07 09:49:30.355844 0xfff64ee020 UTL  keep:                   3650 
08/07 09:49:30.355858 0xfff64ee020 UTL  minRows:                100 
08/07 09:49:30.355872 0xfff64ee020 UTL  maxRows:                4096 
08/07 09:49:30.355885 0xfff64ee020 UTL  comp:                   2 
08/07 09:49:30.355895 0xfff64ee020 UTL  walLevel:               1 
08/07 09:49:30.355909 0xfff64ee020 UTL  fsync:                  3000 
08/07 09:49:30.355922 0xfff64ee020 UTL  replica:                1 
08/07 09:49:30.355935 0xfff64ee020 UTL  quorum:                 1 
08/07 09:49:30.355948 0xfff64ee020 UTL  compressMsgSize:        -1 
08/07 09:49:30.355963 0xfff64ee020 UTL  maxSQLLength:           65480(byte)
08/07 09:49:30.355977 0xfff64ee020 UTL  maxNumOfOrderedRes:     100000 
08/07 09:49:30.355990 0xfff64ee020 UTL  timezone:               Asia/Shanghai (CST, +0800) 
08/07 09:49:30.356001 0xfff64ee020 UTL  locale:                 zh_CN.UTF-8 
08/07 09:49:30.356011 0xfff64ee020 UTL  charset:                UTF-8 
08/07 09:49:30.356024 0xfff64ee020 UTL  maxShellConns:          5000 
08/07 09:49:30.356038 0xfff64ee020 UTL  maxConnections:         5000 
08/07 09:49:30.356050 0xfff64ee020 UTL  minimalLogDirGB:        0.100000(GB)
08/07 09:49:30.356064 0xfff64ee020 UTL  minimalTmpDirGB:        0.100000(GB)
08/07 09:49:30.356078 0xfff64ee020 UTL  minimalDataDirGB:       0.500000(GB)
08/07 09:49:30.356092 0xfff64ee020 UTL  mnodeEqualVnodeNum:     4 
08/07 09:49:30.356105 0xfff64ee020 UTL  http:                   1 
08/07 09:49:30.356118 0xfff64ee020 UTL  mqtt:                   0 
08/07 09:49:30.356133 0xfff64ee020 UTL  monitor:                0 
08/07 09:49:30.356146 0xfff64ee020 UTL  httpCacheSessions:      1000 
08/07 09:49:30.356160 0xfff64ee020 UTL  httpEnableRecordSql:    0 
08/07 09:49:30.356172 0xfff64ee020 UTL  telegrafUseFieldNum:    0 
08/07 09:49:30.356185 0xfff64ee020 UTL  httpMaxThreads:         2 
08/07 09:49:30.356198 0xfff64ee020 UTL  restfulRowLimit:        102400 
08/07 09:49:30.356211 0xfff64ee020 UTL  numOfLogLines:          10000000 
08/07 09:49:30.356226 0xfff64ee020 UTL  asyncLog:               1 
08/07 09:49:30.356239 0xfff64ee020 UTL  debugFlag:              0 
08/07 09:49:30.356252 0xfff64ee020 UTL  mDebugFlag:             135 
08/07 09:49:30.356265 0xfff64ee020 UTL  dDebugFlag:             135 
08/07 09:49:30.356278 0xfff64ee020 UTL  sDebugFlag:             135 
08/07 09:49:30.356291 0xfff64ee020 UTL  wDebugFlag:             135 
08/07 09:49:30.356304 0xfff64ee020 UTL  sdbDebugFlag:           135 
08/07 09:49:30.356319 0xfff64ee020 UTL  rpcDebugFlag:           131 
08/07 09:49:30.356332 0xfff64ee020 UTL  tmrDebugFlag:           131 
08/07 09:49:30.356344 0xfff64ee020 UTL  cDebugFlag:             131 
08/07 09:49:30.356355 0xfff64ee020 UTL  jniDebugFlag:           131 
08/07 09:49:30.356367 0xfff64ee020 UTL  odbcDebugFlag:          131 
08/07 09:49:30.356379 0xfff64ee020 UTL  uDebugFlag:             131 
08/07 09:49:30.356390 0xfff64ee020 UTL  httpDebugFlag:          131 
08/07 09:49:30.356403 0xfff64ee020 UTL  mqttDebugFlag:          131 
08/07 09:49:30.356417 0xfff64ee020 UTL  monitorDebugFlag:       131 
08/07 09:49:30.356429 0xfff64ee020 UTL  qDebugFlag:             131 
08/07 09:49:30.356442 0xfff64ee020 UTL  vDebugFlag:             131 
08/07 09:49:30.356453 0xfff64ee020 UTL  tsdbDebugFlag:          131 
08/07 09:49:30.356465 0xfff64ee020 UTL  tscEnableRecordSql:     0 
08/07 09:49:30.356477 0xfff64ee020 UTL  enableCoreFile:         0 
08/07 09:49:30.356491 0xfff64ee020 UTL  gitinfo:                3264067e97300c84caa61ac909d548c9ca56de6b 
08/07 09:49:30.356505 0xfff64ee020 UTL  gitinfoOfInternal:      da88f4a2474737d1f9c76adcf0ff7fd0975e7342 
08/07 09:49:30.356518 0xfff64ee020 UTL  buildinfo:              Built by root at 2020-04-01 14:38 
08/07 09:49:30.356531 0xfff64ee020 UTL  version:                2.0.0.0 
08/07 09:49:30.356544 0xfff64ee020 UTL  maxBinaryDisplayWidth:  30 
08/07 09:49:30.356558 0xfff64ee020 UTL  os pageSize:            16384(KB)
08/07 09:49:30.356571 0xfff64ee020 UTL  os openMax:             1024
08/07 09:49:30.356584 0xfff64ee020 UTL  os streamMax:           16
08/07 09:49:30.356597 0xfff64ee020 UTL  os numOfCores:          8
08/07 09:49:30.356610 0xfff64ee020 UTL  os totalDisk:           648.692139(GB)
08/07 09:49:30.356633 0xfff64ee020 UTL  os totalMemory:         64651(MB)
08/07 09:49:30.356655 0xfff64ee020 UTL  os sysname:             Linux
08/07 09:49:30.356669 0xfff64ee020 UTL  os nodename:            srv01
08/07 09:49:30.356681 0xfff64ee020 UTL  os release:             4.19.0-loongson-3-server
08/07 09:49:30.356694 0xfff64ee020 UTL  os version:             #1187 SMP PREEMPT Wed Mar 25 22:36:49 CST 2020
08/07 09:49:30.356708 0xfff64ee020 UTL  os machine:             mips64
08/07 09:49:30.356721 0xfff64ee020 UTL ==================================
08/07 09:49:30.356735 0xfff64ee020 DND start to initialize TDengine on srv01:6030
08/07 09:49:30.356932 0xfff64ee020 DND storage directory is initialized
08/07 09:49:30.356992 0xfff64ee020 DND dnode read is opened, min worker:8 max worker:16
08/07 09:49:30.357009 0xfff64ee020 DND dnode write is opened, max worker 8
08/07 09:49:30.357048 0xfff64ee020 DND dnode mread is opened
08/07 09:49:30.357078 0xfff64ee020 DND dnode mwrite is opened
08/07 09:49:30.357113 0xfff64ee020 DND dnode mpeer is opened
08/07 09:49:30.357996 0xfff64ee020 DND inter-dnodes rpc client is opened
08/07 09:49:30.358514 0xfff64ee020 DND inter-dnodes RPC server is opened
08/07 09:49:30.358821 0xfff64ee020 DND ERROR failed to read dnodeCfg.json, clusterId not found
段错误

**Comment by plum-lihui** [comment]
龙芯的系统？是自己使用源码编译的版本么？

**Comment by kinghtdom** [comment]
是龙芯的UOS系统，也是自己用源码编译的，版本是v2.0的。

**Comment by kinghtdom** [comment]
找到解决方法了。要将debug/test/cfg/taos.cfg中的dataDir和logDir的路径放到/etc/taos/taos.cfg文件中。再启动taosd就不会报错了。
