### ISSUE TITLE
Unit test failed

### ISSUE THREAD

**Issue by boyxiaolong** [taosdata/TDengine#2968]
按照How-To-Run-Test-And-How-To-Add-New-Test-Case允许到第三步cmake ..时，报错：
-- Community directory: /root/code/TDengine
-- input cpuType unknown 
-- The current os is 
-- The current platform is Linux 64-bit
-- CMAKE_CXX_COMPILER_ID: GNU
-- COMMON_FLAGS: -std=gnu99 -Wall -Werror -fPIC -g3 -gdwarf-2 -msse4.2 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILE
-- Project source directory: /root/code/TDengine
-- Project binary files output path: /root/code/TDengine/debug
-- Project executable files output path: /root/code/TDengine/debug/build/bin
-- Project library files output path: /root/code/TDengine/debug/build/lib
-- MVN is not installed and JDBC is not compiled
-- Build Debug Version as default
-- Use the iconv functions in GLIBC
-- build version 
CMake Error at src/client/CMakeLists.txt:36 (SET_TARGET_PROPERTIES):
  set_target_properties called with incorrect number of arguments.

-- Configuring incomplete, errors occurred!
See also "/root/code/TDengine/debug/CMakeFiles/CMakeOutput.log".
See also "/root/code/TDengine/debug/CMakeFiles/CMakeError.log".

**Comment by plum-lihui** [comment]
请将这两个log文件发上来，我们分析一下。多谢！
See also "/root/code/TDengine/debug/CMakeFiles/CMakeOutput.log".
See also "/root/code/TDengine/debug/CMakeFiles/CMakeError.log".

**Comment by boyxiaolong** [comment]
[CMakeError.log](https://github.com/taosdata/TDengine/files/5044213/CMakeError.log)
[CMakeOutput.log](https://github.com/taosdata/TDengine/files/5044215/CMakeOutput.log)

**Comment by plum-lihui** [comment]
环境中cmake、gcc的版本分别是多少呢？
