### ISSUE TITLE
potential dead-lock in tcache.c

### ISSUE THREAD

**Issue by freemine** [taosdata/TDengine#2969]
in the working thread of tcache, when time expires and ref of node is zero, the registered callback will be called.
but, the code implemented is somewhat like this:
```
__cache_wr_lock(pCacheObj);
...
pCacheObj->freeFp(pNode->data);
...
__cache_unlock(pCacheObj);
```
that means one senario lock series might be: cache locker , callback , user locker

but user code might using other senario like, holding it's own locker before calling the cache api.
thus, the lock series might be: user locker, call cache api, cache locker.

dead lock might occur in above situation.

**Comment by sangshuduo** [comment]
@freemine would you please to submit a PR to fix it?

**Comment by sangshuduo** [comment]
@freemine would you please to submit a PR to fix it?

**Comment by freemine** [comment]
@sangshuduo 
#3695
