### ISSUE TITLE
tdengine 用逆序的输入测试集的发现的性能和设计上的问题

### ISSUE THREAD

**Issue by whuyinpeng** [taosdata/TDengine#297]
说明： 逆序数据可以参考官方文档：**数据写入**一节(“注意” 部分)
https://www.taosdata.com/cn/documentation/taos-sql/#%E6%95%B0%E6%8D%AE%E5%86%99%E5%85%A5

你好，我在根据https://www.taosdata.com/blog/2019/07/19/tdengine%e4%b8%8einfluxdb%e5%af%b9%e6%af%94%e6%b5%8b%e8%af%95/
复现测试数据遇到了一些问题，想咨询下作者。

我的测试环境是 Centos 7.2.1511（内核版本3.10.0），用 gcc 8.3.0编译TDengine，机器配置是Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz * 2 (共24逻辑核)，内存 64GB。

我用dataGenerator工具生成了 100 个文件，共100000000条数据。命令如下：
java com/taosdata/generator/DataGenerator -dataDir ~/testdata -numOfDevices 10000 -numOfFiles 100 -rowsPerDevice 10000

用 tdengine 的测试工具测试，命令是：
./tdengineTest -dataDir DATA_DIR_PREFIX/testdata/ -numOfFiles 10 -writeClients 1 -rowsPerRequest 1000
tdengine的速度能到32万条记录每秒，但是用influxdb只能到6万条记录每秒。同时 tdengine的cpu占用率最高约20%，但是influxdb 最高到90%，确实速度非常快。

但是后来看数据格式的文档，对tdengine怎么仅用3个文件就能保证数据块按时间排序的技术很感兴趣，就尝试把测试数据集逆序排列( tac 命令)，然后我用命令：
./tdengineTest -dataDir DATA_DIR_PREFIX/testdata_tac/ -numOfFiles 10 -writeClients 1 -rowsPerRequest 1000
测试，就发现了很奇怪的现象：
1. tdengine扔掉了每个表除第一个请求的所有数据（就是说每个表只有1000条数据），原因是因为逆序的，所以后面的时间戳都比前面的小。
2. 如果tdengine扔掉数据不处理，按理说cpu应该会降低，但是我观察到 tdengine cpu 占用率飚高到了 80%，但反而客户端的cpu使用率略微降低。我以为是服务器排序的问题，但是后来看代码发现tdengine在处理insert的时候，批量数据是客户端排序的。
3. 测试最终结果发现速度降低到了 17万每秒。

所以我的问题有：
1. 如果我们假设输入是有序的，确实能避免掉很多问题，简化设计，譬如对于一些不严格有序的数据至少可以避免merge，但是这种假设在现实情况中很难遇到。譬如：两个不同的服务器因为时间同步的问题有略微的不一致，如果我想把若干台服务器的数据存在一个表，在这个模型上可能就不可行。再比如即使tdengine客户端用了tcp协议，如果有重连或者多连接的话，两个tcp链接之间的顺序也不能保证，除非为每个tcp链接单独建立一个表。这种简化设计我不知道tdengine是怎么考虑的？（我不了解物联网，但是如果每个物联网设备都建立一个tcp连接可能服务器也会扛不住吧，所以我猜想很多场景可能都会使用udp，但是tdengine对客户端输入的要求好像很难满足这些场景）
2. 按理说扔掉数据cpu使用率应该会降低，但是为什么逆序数据相比正序输入cpu使用率竟然增加了4倍？
3. 扔掉数据后服务器负载也应该降低，但是为什么最终处理速度会降低一倍？
4. tdengine的schema的定长问题会不会在实际使用中有什么局限？(提出这个问题的原因是我翻代码的时候发现 schema 好像只支持定长数据，这样也会简化很多设计问题）
5. 其他的数据库也是在客户端排序的吗？即使tdengine的客户端代码做了有序验证，但是如果有乱序数据的话，客户端排序会对客户端的服务造成多大的影响呢？

**Comment by guanshengliang** [comment]
1. TDengine的基本假设是物联网数据按照时间有序，大多场景下，这个假设是没有问题的。但也确实存在一些场景需要导入历史数据，甚至可能存在乱序数据。对于这种情况，TDengine也进行了针对处理，但乱序数据写入速度会和顺序写入速度差别较大，这个性能差异只能尽量缩小。对于完全乱序的场景，并且也无法通过一些预处理方法使其在某一时间窗口内有序，那这种场景TDengine没有很好的处理方法。
2. CPU使用率增加，可能是TDengine在这种情况下的一个BUG，这个我们会争取复现并解决。
3. “扔掉”这个词并不是很准确，当数据写入失败时，TDengine会返回一个错误，或者APP端也可以通过AffectRows获取实际写入的数据条数。这种情况下，APP端应该需要进行相应的错误处理，因为TDengine已经明确告知了数据存在问题。
4.  TDengine是用结构化方法去处理物联网的问题，这也基于其对物联网数据的假设，TDengine并不是一个通用的数据库，甚至不能处理所有类型的时序数据，当数据本身不是结构化时，您需要根据数据模型进行合理设计和选型。定长Schema主要问题在于字符串数据的处理，但是字符串在物联网中也不是很多。
5. 客户端排序本身没问题，因为TDengine每一批次允许写入的数据量最长为64K的SQL语句，如此小体量的排序对客户端产生的性能压力可以忽略不计。

**Comment by whuyinpeng** [comment]
针对第一个问题，我还是很难理解。
1. 时序数据本身虽然是大体有序的，但是始终会因为各种问题，譬如我问题里面提到的服务器时间之类的问题变的无序。即使数据在产生的终端是有序的，但也不能假设数据产生是有序的那么在处理侧也是有序的，如果强行这么对等我觉得没有很大的说服力。
2. 现在没有办法处理乱序的错误码，我测试的过程中只是在服务端日志中有WARNING而已，如果有这种情况，我只能通过新建表来解决，但是这又会影响到查询。

**Comment by whuyinpeng** [comment]
这里再补充下我的测试版本，我的代码测试版本是master分支，最后一次提交的tag是：d0e5e817a24ece4636957b820294a2943df4d10a

**Comment by guanshengliang** [comment]
1. 一个小范围内无序的数据，例如从kfaka消费过来的数据，这种情况TDengine会缓存其中一部分数据，在落盘的时候再进行排序。这种情况下，写入速度虽然略有下降，但是应该不会成为该场景的瓶颈。
2. 可以通过taos_affected_rows获取上次insert语句实际写入的条数，但写入条数和预期不同时，可以将该批数据拆分，一条一条写入。

**Comment by guanshengliang** [comment]
不需要过分强调排序的问题，github的版本已经自动做了排序。

**Comment by whuyinpeng** [comment]
我从代码上看 vnodeMeter.c 593 到 597 的这个逻辑
```
    if (*((TSKEY *)pData) <= pObj->lastKey) {
      dWarn("vid:%d sid:%d id:%s, received key:%ld not larger than lastKey:%ld", pObj->vnode, pObj->sid, pObj->meterId,
            *((TSKEY *)pData), pObj->lastKey);
      pData += pObj->bytesPerPoint;
      continue;
    }
```
我不分表好像是写不进去的吧。
后面 vnodeFile.c 的刷盘代码也有数据有序的假设，否则很难不通过merge来保证数据块有序啊。

**Comment by guanshengliang** [comment]
1. 不太清楚您说的分表是什么意思，TDengine的用法就是一个设备一张表，如果您现在不是这种用法，要进行响应的修改
2. 代码的逻辑您自己研究吧，确实没有时间在这里进行解析

**Comment by whuyinpeng** [comment]
不是啊，我目前是单设备两个批量直接的写入顺序和时间戳不一致我数据就没办法写进去啊。

**Comment by hzcheng** [comment]
@whuyinpeng 最近比较忙，我同事不是说您没事找事，抱歉啊。是这样的，TDengine的insert语句有较强的假设，是对于一张表，后插入的数据要严格时间戳有序的，不过我们同时也提供了import语句，这个语句没有那么强的假设。import时，如果直接写入的时间戳是最新的，那么它和insert是一样的。如果不是，则出发单独的import过程。不过import语句如果写入，有可能会直接写文件，这样的话，牵扯到拆块合并等问题，因此，一旦直接import文件，效率肯定没有insert效率高。不过考虑到物联网数据基本有序，import到文件的数据应该是一小部分。您如果有兴趣，可以看下vnodeImport.c文件。 另外，我们的import还有很大的优化空间，我们后续工作会慢慢将优化完成的。

**Comment by whuyinpeng** [comment]
Ok，用 import 代替 insert 就可以搞定了是吧，我明白了。
就是insert没有办法处理序不一致的数据，但是 import 可以。
谢谢。

**Comment by guanshengliang** [comment]
好的，我没理解你的问题，发言太过官方，见谅

**Comment by whuyinpeng** [comment]
还有一个问题，就是后面能不能再客户端封装import过程呢？

**Comment by hzcheng** [comment]
不是很明白您客户端封装的意思。是指将import和insert合并还是说还有其他的含义？

**Comment by whuyinpeng** [comment]
就是我插入数据的时候我不用处理affect_rows这样的错误问题，我觉得在官方的客户端代码做可以避免很多客户写同样的代码。

**Comment by hzcheng** [comment]
我们会考虑的。建议您新开个issue，提这个功能需求，这样我们也好统计备案，按需安排开发和支持任务。

**Comment by whuyinpeng** [comment]
嗷，好的，多谢。

**Comment by whuyinpeng** [comment]
那个cpu使用率的问题，如果你们复现解决了也麻烦回复下issue，我拉下来再看看。昨天也困扰了我好久，这个问题。

**Comment by hzcheng** [comment]
正在看

**Comment by hzcheng** [comment]
CPU使用率的问题应该是大量打印报警信息引起的, 集体代码应该是这行：https://github.com/taosdata/TDengine/blob/34efa468ad413ccfac8baab40e339c73b29f3ba9/src/system/src/vnodeMeter.c#L595

**Comment by whuyinpeng** [comment]
已验证，日志猛如虎，正常情况下应该不是问题。多谢。
