### ISSUE TITLE
DB error: too many sessions on server

### ISSUE THREAD

**Issue by Lao-Zhong** [taosdata/TDengine#2974]
**Bug Description**
DB error: too many sessions on server
![1596781229(1)](https://user-images.githubusercontent.com/39207755/89615502-54b63c80-d8b9-11ea-853e-8219cee12592.jpg)

**Comment by localvar** [comment]
as v2.0 is released, we will put more resource on the new version, and the response time of v1.6 issues may be very long.
could you please upgrade to the new version and try again? thanks for your understanding.
