### ISSUE TITLE
2.0 TDengine connection error in docker

### ISSUE THREAD

**Issue by liqilong2017** [taosdata/TDengine#2976]
taos -h 192.168.10.154 -uroot -ptaosdata -s "show databases;" 执行报错
在宿主机上能正常执行

`[root@2a0393fb6149 TDengine-server]# taos -h 192.168.10.154 -uroot -ptaosdata -s "show databases;"

Welcome to the TDengine shell from Linux, Client Version:2.0.0.0
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

taos> show databases;

DB error: Unexpected generic error in RPC

taos -h 192.168.10.154 -uroot -ptaosdata -s "show databases;"

Welcome to the TDengine shell from Linux, Client Version:2.0.0.0
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

taos> show databases;
              name              |      created_time       |   ntables   |   vgroups   | replica | quorum |  days  |    keep1,keep2,keep(D)     |  cache(MB)  |   blocks    |   minrows   |   maxrows   | wallevel |    fsync    | comp | precision |    status    |
===================================================================================================================================================================================================================================================================
 test                           | 2020-08-07 13:48:26.515 |           0 |           0 |       1 |      1 |     10 | 3650,3650,3650             |          16 |           6 |         100 |        4096 |        1 |        3000 |    2 | ms        | ready        |
Query OK, 1 row(s) in set (0.001345s)`

**Comment by liqilong2017** [comment]
去掉： "status will be processed in mpeer queue" 然后显示的日志 
08/07 15:22:45.796746 0x7ff379e84700 MND connId:16, is created, user:root ip:192.168.10.223:53479
08/07 15:22:45.796750 0x7ff379e84700 MND user:root login from 192.168.10.223, result:success
08/07 15:22:59.617258 0x7ff378681700 MND connId:16, is destroyed

**Comment by hzcheng** [comment]
可否用nc测试下访问192.168.10.154是否有问题？

**Comment by plum-lihui** [comment]
这个问题估计是网络不通造成的。我们有一个工具，验证客户端和服务端之间是否满足tdengine的通讯。主要就是测试端口是否可达。先停止taosd，然后在服务端启动taosServer ，然后再在客户端启动taosClient。结果会显示需要的端口是否ok。

[networkTools.zip](https://github.com/taosdata/TDengine/files/5044514/networkTools.zip)

**Comment by liqilong2017** [comment]
应该是  FQDN ,现在非容器的问题解决了、、容器里的tdengine 无法连接，容器里的自己连自己也有问题

**Comment by liqilong2017** [comment]
[root@tdengine taos]# grep -r "ae22addf58c3"  |grep firstEp
taosdlog.1:08/07 02:14:30.522955 0x7fc1ea87f740 UTL  firstEp:                ae22addf58c3:6030 
docker 容器里 的这个 firstEp  参数 是 如何获取的啊？？上面命令是在 /var/log/taos 目录下执行的

**Comment by plum-lihui** [comment]
docker的话，请参考： [TDengine官方Docker镜像的发布、下载和使用](https://www.taosdata.com/blog/2020/08/03/1509.html )
