### ISSUE TITLE
query result from rest interface is different from taos console

### ISSUE THREAD

**Issue by jonathanwx** [taosdata/TDengine#2977]
SQL如下
``` sql
select min(value),max(value),avg(value) from test.iot_equip_data 
    where (field_id='000048f6-e10b-43a3-af0e-e49e16d2efd6' or field_id='00021b1e-6e91-4846-b08d-9b6b15d5a9b1') 
    interval(15m) group by field_id;
```
rest接口运行结果
![QQ截图20200807170457](https://user-images.githubusercontent.com/6824364/89629300-2c860800-d8d0-11ea-8a39-c62a5c2113f4.png)

控制台运行结果
![QQ截图20200807170608](https://user-images.githubusercontent.com/6824364/89629377-4e7f8a80-d8d0-11ea-8859-c856b82c7ac9.png)

控制台得到了预期的结果，而rest接口没有
tdengine版本2.0.0.1
![QQ截图20200807170845](https://user-images.githubusercontent.com/6824364/89629599-ab7b4080-d8d0-11ea-88d2-4933644c723d.png)

**Comment by guanshengliang** [comment]
您可以建表、insert的SQL语句，导一份出来发送给我们，以便我们能够复现这个问题。
这些信息，还不够判断。

**Comment by jonathanwx** [comment]
建表以及insert语句在附件的压缩包中，还请帮忙复现下

[create-table-and-data.zip](https://github.com/taosdata/TDengine/files/5049389/create-table-and-data.zip)

**Comment by guanshengliang** [comment]
好的，问题已经复现。
我们会尽快解决这个问题。

**Comment by guanshengliang** [comment]
已经处理并提交到master分支，您可以拉master分支代码编译。
或者等待几天后的2.0.1.1版本

**Comment by jonathanwx** [comment]
好的 感谢大佬 过几天版本出来了我验证下

**Comment by guanshengliang** [comment]
There is no response to this issue for a long time, and this issue has been fixed in 2.0 version, so close it
If there are still any questions, you can reopen or create a new issue
