### ISSUE TITLE
执行taosdemo的时候 报SQL错

### ISSUE THREAD

**Issue by chenlinsoft** [taosdata/TDengine#2978]
![image](https://user-images.githubusercontent.com/9483193/89633835-fa2bd900-d8d6-11ea-9609-5e3fe556fd3c.png)

Creating meters super table...
Failed to run create table if not exists test.meters (ts timestamp,f1 int,f2 ,f3 ) tags (areaid int, loc binary(10)), reason: invalid SQL: syntax error near ",f3 ) tags (areaid int, loc binary(10))"

**Comment by Shawshank-Smile** [comment]
请根据提示仔细检查一下，f2 和 f3 的类型没有给。

**Comment by eurake** [comment]
the same problem
