### ISSUE TITLE
cluster with 3 dnodes

### ISSUE THREAD

**Issue by eleleme** [taosdata/TDengine#2979]
v2.0.1版本下，想建一个集群。
taosdnode1.pse.sjtu:6030 主机云行taos（已经建好为taosdnode2.pse.sjtu:6030 ，taosdnode3.pse.sjtu:6030 建了dnode)，提示另外两个vnodes是offline，这是正常的吗？
taos> show dnodes;
   id   |           end_point            | vnodes | cores  |     status     |   role   |       create_time       |
==================================================================================================================
      1 | localhost:6030                 |      1 |      2 | ready          | any      | 2020-08-07 05:02:19.527 |
      4 | taosdnode2.pse.sjtu:6030       |      0 |      0 | offline        | any      | 2020-08-07 07:25:46.896 |
      5 | taosdnode3.pse.sjtu:6030       |      0 |      0 | offline        | any      | 2020-08-07 07:37:16.419 |

**Comment by eleleme** [comment]
create table testtb2 (ts timestamp, c1 int, c2 binary(20), c3 nchar(50));
===================
DB error: Out of DNodes

**Comment by Shawshank-Smile** [comment]
offline是不正常的，需要具体检查原因。如果重启还是不能解决的话，需要按照官方文档检查FQDN和hostname的配置。
