### ISSUE TITLE
vs2019 client compile error

### ISSUE THREAD

**Issue by ximenjiangjun** [taosdata/TDengine#2980]
1>D:\TDegine\TDengine-ver-2.0.0.1\src\inc\taosmsg.h(209,22): error C2233: “blocks”: 包含大小为零的数组的对象数组是非法的
1>D:\TDegine\TDengine-ver-2.0.0.1\src\inc\taosmsg.h(683,24): error C2233: “metas”: 包含大小为零的数组的对象数组是非法的

// Submit message for this TSDB
typedef struct SSubmitMsg {
  SMsgHead   header;
  int32_t    length;
  int32_t    numOfBlocks;
  SSubmitBlk blocks[];
} SSubmitMsg;

**Comment by guanshengliang** [comment]
2.0的windows客户端还没有发布，请再等等

**Comment by ximenjiangjun** [comment]
ok
