### ISSUE TITLE
how to dump taosd/taosc's stdout/stderr output when hacking with crash_gen.py/crash_gen.sh

### ISSUE THREAD

**Issue by freemine** [taosdata/TDengine#2981]
as subject

crash_gen.py is great, but how to dump more info when it reports crash? that'll help greater.

thx!

**Comment by stevel032** [comment]
Not sure if I fully understand the question. When a crash happens, a core file will be generated with all the necessary information. I wonder what information might be missing that might be valuable?

**Comment by stevel032** [comment]
Right now, the tool is still in active development. The output handling isn't completely unified yet. We use Python logging, which goes to STDERR, but we still sprinkle some print() statements, which goes to STDOUT. For now, to capture all output, one can do:

```
$ ./crash_gen.sh -p -t 3 -s 5 > dummy.txt 2>&1
$ wc dummy.txt
20  123 1052 dummy.txt
```

If there is a strong case to be made to analyze the output, we can definitely adjust the output arrangements.

**Comment by freemine** [comment]
thx. That helps.

**Comment by stevel032** [comment]
Sounds great, feel free to reopen this issue or create a new one if you encounter additional issues down the road.
