### ISSUE TITLE
tier storage support

### ISSUE THREAD

**Issue by foobar** [taosdata/TDengine#299]
The cfg file below has items for tiered storage. But it doesn't seem to be implemented from the source code.  Is this really supported?

https://github.com/taosdata/TDengine/blob/1b00a4a8d63b8b9fe228d772072a65aa8423aba6/packaging/cfg/taos.cfg#L173-L181

**Comment by hzcheng** [comment]
Not implemented in the open source code.

**Comment by jtao1735** [comment]
Only enterprise solution supports this feature
