### ISSUE TITLE
about tag null

### ISSUE THREAD

**Issue by yangzj208** [taosdata/TDengine#3006]
taos> select name,tag1,tag2,tag3 from test.node where tag1='dfe';
Query OK, 0 row(s) in set (0.001198s)
taos> select name,tag1,tag2,tag3 from test.node where tag1=null;
DB error: invalid SQL: illegal column name
taos> select name,tag1,tag2,tag3 from test.node where tag1 is null;
DB error: invalid SQL: syntax error near "is null;"

如上，字符串查询没问题，后两种都出错。想查tag1为null的子表信息该如何查，谢谢

**Comment by xiaopingcs** [comment]
'is null' is not supported for now
