### ISSUE TITLE
TDengine cluster building slave node has been offline and cannot register

### ISSUE THREAD

**Issue by chengjiabaocjb** [taosdata/TDengine#3007]
**Bug Description**

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by plum-lihui** [comment]
这个问题估计是网络不通造成的。我们有一个工具，验证客户端和服务端之间是否满足tdengine的通讯。主要就是测试端口是否可达。先停止taosd，然后在服务端启动taosServer ，然后再在客户端启动taosClient。结果会显示需要的端口是否ok。
[networkTools.zip](https://github.com/taosdata/TDengine/files/5054688/networkTools.zip)

**Comment by sangshuduo** [comment]
@chengjiabaocjb 问题解决了吗？

**Comment by plum-lihui** [comment]
已经发布了最新的v2.0.4.0版本，如果还有问题，请使用最新版本试试。
