### ISSUE TITLE
UTL ERROR failed get the ip address, fqdn:telemetry.taosdata.com, code:-2, reason:Name or service not known

### ISSUE THREAD

**Issue by chengjiabaocjb** [taosdata/TDengine#3008]
**Bug Description**

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by Aries-Lee1991** [comment]
Please attach the log、version and operation info..

**Comment by AlvinCage** [comment]
**the same issues!**
08/24 17:54:29.725833 0x7f1b01adc700 UTL **ERROR failed get the ip address, fqdn:f0f2bdf9ffbc, code:-2, reason:Name or service not known**
08/24 17:54:29.725886 0x7f1b01adc700 RPC ERROR DND-C, failed to resolve FQDN:f0f2bdf9ffbc
08/24 17:54:29.725895 0x7f1b01adc700 RPC ERROR DND-C (nil), failed to set up connection(Unexpected generic error in RPC)
08/24 17:54:29.725909 0x7f1b01adc700 DND ERROR status rsp is received, error:Unexpected generic error in RPC
08/24 17:54:30.444602 0x7f1b01adc700 UTL ERROR failed get the ip address, fqdn:f0f2bdf9ffbc, code:-2, reason:Name or service not known
08/24 17:54:30.444652 0x7f1b01adc700 RPC ERROR TSC, failed to resolve FQDN:f0f2bdf9ffbc
08/24 17:54:30.444669 0x7f1b01adc700 RPC ERROR TSC 0x7f1adc001170, failed to set up connection(Unexpected generic error in RPC)
08/24 17:54:30.733487 0x7f1b01adc700 UTL ERROR failed get the ip address, fqdn:f0f2bdf9ffbc, code:-2, reason:Name or service not known

**Comment by zyyang-taosdata** [comment]
对于TAOS Shell或客户端应用，请做如下检查：

请检查连接的服务器的FQDN是否正确
1.如果网络配置有DNS server, 请检查是否正常工作
2.如果网络没有配置DNS server, 请检查客户端所在机器的hosts文件，查看该FQDN是否配置，并是否有正确的IP地址。
3.如果网络配置OK，从客户端所在机器，你需要能Ping该连接的FQDN，否则客户端是无法链接服务器的
