### ISSUE TITLE
查询 stable 条数不匹配

### ISSUE THREAD

**Issue by wsf1990** [taosdata/TDengine#301]
场景：一个超级表，多个子表。
执行：
```
select * from stable_name  limit 10 offset 0;
```
在客户端中执行能得到10条结果，但是使用python客户端却得到了80条结果。
执行：
```
for item in cursor:
      print(item)
```
打印了80次，共打印了8个子表中的数据，每个子表10条。

**Comment by hzcheng** [comment]
您用的版本是最新的吗？前面已经有人报过这个问题，应该是已经修复了，如果不是最新的，您可以重新拉取代码编译，替换，最重要的是要替换libtaos.so(linux下)或者taos.dll(windows下)。

**Comment by hzcheng** [comment]
#244

**Comment by wsf1990** [comment]
好的，我试一下

**Comment by wsf1990** [comment]
我更新了系统，但是发现修改配置文件中的keep配置项不起作用了，这个地方是做了修改吗？

**Comment by hzcheng** [comment]
现在修改了retention的策略，不再是锚定vnode最新数据了，而是和服务器的时间挂钩了，服务器时间一个月（keep 30)的数据保留。因为以前的策略比较危险，实际场景中有可能有垃圾数据来，比如2049年，会将现在有用的数据删除。

**Comment by wsf1990** [comment]
意思是现在只能保留一个月的数据吗？

**Comment by hzcheng** [comment]
不是，我只是举个例子，假设keep 设置成30，就是只保留30天的数据，指的是当前服务器时间向前的一个月的数据

**Comment by wsf1990** [comment]
明白，可是我将keep 设置成了 36500，结果启动taosd的时候，发现打印出来的还是3650，并且超过10年的数据都没了。

**Comment by wsf1990** [comment]
我的失误，是正常的

**Comment by wsf1990** [comment]
从 stable 查询 10 条，得到的是某个子表的前 10 条（根据时间戳字段排序），而不是所有子表的前 10 条，这个是正常的吗？

**Comment by wsf1990** [comment]
stable不能整体上按照时间进行order吗？

**Comment by hzcheng** [comment]
从stable中查询每个子表的10条记录的功能目前不支持，后续会加，stable的查询结果目前也不支持按照时间排序。

**Comment by wsf1990** [comment]
我可能没有表达清楚，对 stable 执行 select 操作的时候，返回的结果是根据什么排序的呢？tag？

**Comment by hjxilinx** [comment]
排序的结果是每个子表内部的顺序。简单的说，select * from super_table的返回结果等效于：
```
select * from sub_table_1
```
```
select * from sub_table_2
```
对于sub_table的排序，现在不提供指定的排序（不保证顺序），但是对于跨vnode的查询，按照vnode的创建的顺序进行输出。
