### ISSUE TITLE
error：taos connect failed, reason: Unexpected generic error in RPC.

### ISSUE THREAD

**Issue by whwqs** [taosdata/TDengine#3010]
**Bug Description**
运行服务后，在linux控制台，运行taos报错：
taos connect failed, reason: Unexpected generic error in RPC.

**To Reproduce**
1. linux版本：Linux version 3.10.0-229.el7.x86_64
2. TDengine版本：TDengine-server-2.0.0.1-Linux-x64.rpm
3. 运行taos报错：taos connect failed, reason: Unexpected generic error in RPC.

**Expected Behavior**
正常运行

**Screenshots**

**Environment (please complete the following information):**
 - OS: Linux version 3.10.0-229.el7.x86_64
 - Memory, CPU, current Disk Space
 - TDengine Version [TDengine-server-2.0.0.1-Linux-x64.rpm]

**Additional Context**
上传日志给你们
[log.zip](https://github.com/taosdata/TDengine/files/5054527/log.zip)

**Comment by localvar** [comment]
您可以查看一下服务器是否配置了 hostname 吗？谢谢
```shell
hostname
```

**Comment by whwqs** [comment]
配置文件在zip文件里有，看了一下，配置好像都是用#号注释了，应该是没有配置hostname

**Comment by whwqs** [comment]
![image](https://user-images.githubusercontent.com/24094/90112823-13bf9b80-dd83-11ea-9d0c-12d2f51cd436.png)

**Comment by whwqs** [comment]
下午到现在用dev版本源码安装成功，运行taosd，不断重复报错如下：
08/13 00:57:58.803247 0x7f11b4709700 DND ERROR status rsp is received, error:Unexpected generic error in RPC
08/13 00:57:59.808175 0x7f11b4709700 UTL ERROR failed get the ip address, fqdn:, code:-2, reason:Name or service not known
08/13 00:57:59.808206 0x7f11b4709700 RPC ERROR DND-C, failed to resolve FQDN:
08/13 00:57:59.808214 0x7f11b4709700 RPC ERROR DND-C (nil), failed to set up connection(Unexpected generic error in RPC)
08/13 00:57:59.808224 0x7f11b4709700 DND ERROR status rsp is received, error:Unexpected generic error in RPC
08/13 00:58:00.813162 0x7f11b4709700 UTL ERROR failed get the ip address, fqdn:, code:-2, reason:Name or service not known
08/13 00:58:00.813194 0x7f11b4709700 RPC ERROR DND-C, failed to resolve FQDN:
08/13 00:58:00.813201 0x7f11b4709700 RPC ERROR DND-C (nil), failed to set up connection(Unexpected generic error in RPC)
08/13 00:58:00.813211 0x7f11b4709700 DND ERROR status rsp is received, error:Unexpected generic error in RPC
08/13 00:58:01.818174 0x7f11b4709700 UTL ERROR failed get the ip address, fqdn:, code:-2, reason:Name or service not known
08/13 00:58:01.818206 0x7f11b4709700 RPC ERROR DND-C, failed to resolve FQDN:
08/13 00:58:01.818214 0x7f11b4709700 RPC ERROR DND-C (nil), failed to set up connection(Unexpected generic error in RPC)
08/13 00:58:01.818226 0x7f11b4709700 DND ERROR status rsp is received, error:Unexpected generic error in RPC
08/13 00:58:02.823206 0x7f11b4709700 UTL ERROR failed get the ip address, fqdn:, code:-2, reason:Name or service not known
08/13 00:58:02.823238 0x7f11b4709700 RPC ERROR DND-C, failed to resolve FQDN:
08/13 00:58:02.823246 0x7f11b4709700 RPC ERROR DND-C (nil), failed to set up connection(Unexpected generic error in RPC)
08/13 00:58:02.823257 0x7f11b4709700 DND ERROR status rsp is received, error:Unexpected generic error in RPC
08/13 00:58:03.828167 0x7f11b4709700 UTL ERROR failed get the ip address, fqdn:, code:-2, reason:Name or service not known

**Comment by localvar** [comment]
请在系统 shell 中执行下
```shell
$hostname
```
看是否能取到正确的机器名。

**Comment by whwqs** [comment]
能取到机器名：redis

**Comment by whwqs** [comment]
刚才用 taos -h localhost 试了下，报错变成了：
taos connect failed, reason: Unable to establish connection.

**Comment by whwqs** [comment]
今天早上用taos -h localhost ，先是这样：
[root@redis ~]# taos -h localhost

Welcome to the TDengine shell from Linux, Client Version:2.0.0.6
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

Failed to open file /root/.taos_history 报这个错
taos> 

quit后再 taos -h localhost 正常了：
[root@redis ~]# taos -h localhost

Welcome to the TDengine shell from Linux, Client Version:2.0.0.6
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

taos>

直接taos还是一样的错：
Welcome to the TDengine shell from Linux, Client Version:2.0.0.6
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

taos connect failed, reason: Unexpected generic error in RPC.

**Comment by whwqs** [comment]
基本查明原因了，是因为该虚拟机主机名起名为redis，但在 /etc/hosts 文件中未把redis配置进去，导致直接运行taos时不能把redis解析为127.0.0.1
解决方案就是：在 /etc/hosts文件中把redis配置进去，例如：
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 redis

bug的线索其实也挺明显，就在 /var/log/taos/taosdlog.0文件中：
08/14 14:22:07.465621 0x7f3d4c09d740 UTL ERROR failed to get fqdn, code:-2, reason:Name or service not known
08/14 14:22:07.465661 0x7f3d4c09d740 UTL localEp is: :6030
08/14 14:22:07.466083 0x7f3d4c09d740 UTL timezone not configured, set to system default: (ADT, -0300)
08/14 14:22:07.466123 0x7f3d4c09d740 UTL ERROR locale not configured, set to system default:en_US.UTF-8
08/14 14:22:07.466133 0x7f3d4c09d740 UTL WARN charset not configured, set to system default:UTF-8
08/14 14:22:07.466166 0x7f3d4c09d740 UTL    taos config & system info:
08/14 14:22:07.466170 0x7f3d4c09d740 UTL ==================================
08/14 14:22:07.466173 0x7f3d4c09d740 UTL  firstEp:                :6030 
08/14 14:22:07.466175 0x7f3d4c09d740 UTL  secondEp:               :6030 
08/14 14:22:07.466178 0x7f3d4c09d740 UTL  fqdn:                    
08/14 14:22:07.466180 0x7f3d4c09d740 UTL  serverPort:             6030 
fqdn读取出错
大家以后碰到这个问题：直接运行taos，报错：taos connect failed, reason: Unexpected generic error in RPC.
可以尝试如下步骤解决：
1、运行hostname查看主机名
2、看 /etc/hosts文件中是否配置了上面的主机名
3、没有配置，配置好，一般就解决了

**Comment by whwqs** [comment]
基本查明原因了，是因为该虚拟机主机名起名为redis，但在 /etc/hosts 文件中未把redis配置进去，导致直接运行taos时不能把redis解析为127.0.0.1
解决方案就是：在 /etc/hosts文件中把redis配置进去，例如：
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 redis

bug的线索其实也挺明显，就在 /var/log/taos/taosdlog.0文件中：
08/14 14:22:07.465621 0x7f3d4c09d740 UTL ERROR failed to get fqdn, code:-2, reason:Name or service not known
08/14 14:22:07.465661 0x7f3d4c09d740 UTL localEp is: :6030
08/14 14:22:07.466083 0x7f3d4c09d740 UTL timezone not configured, set to system default: (ADT, -0300)
08/14 14:22:07.466123 0x7f3d4c09d740 UTL ERROR locale not configured, set to system default:en_US.UTF-8
08/14 14:22:07.466133 0x7f3d4c09d740 UTL WARN charset not configured, set to system default:UTF-8
08/14 14:22:07.466166 0x7f3d4c09d740 UTL    taos config & system info:
08/14 14:22:07.466170 0x7f3d4c09d740 UTL ==================================
08/14 14:22:07.466173 0x7f3d4c09d740 UTL  firstEp:                :6030 
08/14 14:22:07.466175 0x7f3d4c09d740 UTL  secondEp:               :6030 
08/14 14:22:07.466178 0x7f3d4c09d740 UTL  fqdn:                    
08/14 14:22:07.466180 0x7f3d4c09d740 UTL  serverPort:             6030 
fqdn读取出错
大家以后碰到这个问题：直接运行taos，报错：taos connect failed, reason: Unexpected generic error in RPC.
可以尝试如下步骤解决：
1、运行hostname查看主机名
2、看 /etc/hosts文件中是否配置了上面的主机名
3、没有配置，配置好，一般就解决了

**Comment by whwqs** [comment]
基本查明原因了，是因为该虚拟机主机名起名为redis，但在 /etc/hosts 文件中未把redis配置进去，导致直接运行taos时不能把redis解析为127.0.0.1
解决方案就是：在 /etc/hosts文件中把redis配置进去，例如：
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 redis

bug的线索其实也挺明显，就在 /var/log/taos/taosdlog.0文件中：
08/14 14:22:07.465621 0x7f3d4c09d740 UTL ERROR failed to get fqdn, code:-2, reason:Name or service not known
08/14 14:22:07.465661 0x7f3d4c09d740 UTL localEp is: :6030
08/14 14:22:07.466083 0x7f3d4c09d740 UTL timezone not configured, set to system default: (ADT, -0300)
08/14 14:22:07.466123 0x7f3d4c09d740 UTL ERROR locale not configured, set to system default:en_US.UTF-8
08/14 14:22:07.466133 0x7f3d4c09d740 UTL WARN charset not configured, set to system default:UTF-8
08/14 14:22:07.466166 0x7f3d4c09d740 UTL    taos config & system info:
08/14 14:22:07.466170 0x7f3d4c09d740 UTL ==================================
08/14 14:22:07.466173 0x7f3d4c09d740 UTL  firstEp:                :6030 
08/14 14:22:07.466175 0x7f3d4c09d740 UTL  secondEp:               :6030 
08/14 14:22:07.466178 0x7f3d4c09d740 UTL  fqdn:                    
08/14 14:22:07.466180 0x7f3d4c09d740 UTL  serverPort:             6030 
fqdn读取出错
大家以后碰到这个问题：直接运行taos，报错：taos connect failed, reason: Unexpected generic error in RPC.
可以尝试如下步骤解决：
1、运行hostname查看主机名
2、看 /etc/hosts文件中是否配置了上面的主机名
3、没有配置，配置好，一般就解决了

**Comment by AlvinCage** [comment]
**我遇到了同样的问题：**
[root@f614b2808614 TDengine-server]# taos
Welcome to the TDengine shell from Linux, Client Version:2.0.1.1
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.
taos>
taos> create database demo;

**DB error: Unexpected generic error in RPC**

操作如下:
[root@f614b2808614 TDengine-server]# hostname
**f614b2808614**
[root@f614b2808614 TDengine-server]#
[root@f614b2808614 TDengine-server]#
[root@f614b2808614 TDengine-server]# cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
**172.17.0.3      f614b2808614**
[root@f614b2808614 TDengine-server]#
