### ISSUE TITLE
floor、round、bucket Function

### ISSUE THREAD

**Issue by trj832000** [taosdata/TDengine#3017]
从告警模块看有floor、round函数，但是TDengine2.0里没有。请问能加上这几个函数吗？像postgresql的bucket分桶统计函数也是很常用的函数，希望能提供。谢谢

**Comment by hjxilinx** [comment]
我们会在接下来的未来的1~2个 月内提供这几个函数。

**Comment by hjxilinx** [comment]
您说的bucket分桶统计函数具体是什么？

**Comment by trj832000** [comment]
比如温度按0-10，10-20，20-30区间统计分别有多少条记录，
postgresql有分桶函数width_bucket，elasticsearch有直方图函数histogram

**Comment by hjxilinx** [comment]
OK, we will see to it. Thanks!
