### ISSUE TITLE
客户端封装INSERT的强制条件的错误处理逻辑

### ISSUE THREAD

**Issue by whuyinpeng** [taosdata/TDengine#302]
> 注意：对同一张表，插入的新记录的时间戳必须递增，否则会跳过插入该条记录。如果时间戳为0，系统将自动使用服务器当前时间作为该记录的时间戳。

>IMPORT：如果需要将时间戳小于最后一条记录时间的记录写入到数据库中，可使用IMPORT替代INSERT命令，IMPORT的语法与INSERT完全一样。如果同时IMPORT多条记录，需要保证一批记录是按时间戳排序好的。

TDengine 对insert的数据有顺序要求，不满足要求的数据可以按照作者的建议处理（用 IMPORT 命令处理），如下：

>可以通过taos_affected_rows获取上次insert语句实际写入的条数，但写入条数和预期不同时，可以将该批数据拆分，一条一条写入。

但是几乎每个客户都不可避免地遇到这个问题，为了避免代码重复，希望官方可以封装这个错误处理过程，方便客户的同时也避免潜在的bug。

谢谢 ^_^

**Comment by guanshengliang** [comment]
近期会内部讨论是否进行修改

**Comment by zuozhiwen** [comment]
确实我也发现INSERT和IMPORT在使用场景上面过于冗余。现在物联网的场景中乱序的场景不可避免，比如：1.并发和网络问题导致的数据延后。2.有些场景有意而为之。
按照现阶段的操作，我要先确定表的TIMESTAMP最大值，然后与要插入的数据对比，确定使用INSERT还是IMPORT。集群情况下这几步本身也是有并发的问题的。还有就是怎么维护TIMESTAMP，放在Redis又背离了TDEngine的初衷，查数据也有性能问题并发问题。
想来想去，怎么做也是在数据库层面内部区分INSERT和IMPORT好点。

**Comment by guanshengliang** [comment]
生产环境中，使用import是可以的
如果是导数据的场景，可以先排好序再使用insert
TDengine团队会逐步提升Import的写入效率
