### ISSUE TITLE
taos connect failed, reason: Unable to establish connection.

### ISSUE THREAD

**Issue by issac-demon** [taosdata/TDengine#3021]
TDengine服务正常运行，但是建立连接时提示不能建立连接，请问这是因为什么原因？

systemctl status taosd
● taosd.service - TDengine server service
     Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset:>
     Active: active (running) since Tue 2020-08-11 02:55:19 PDT; 59min ago
   Main PID: 5831 (taosd)
      Tasks: 29 (limit: 2285)
     Memory: 5.1M
     CGroup: /system.slice/taosd.service
             └─5831 /usr/bin/taosd

Aug 11 02:55:19 ubuntu systemd[1]: Started TDengine server service.
Aug 11 02:55:19 ubuntu TDengine:[5831]: Starting TDengine service...
Aug 11 02:55:19 ubuntu TDengine:[5831]: Started TDengine service successfully.

**Comment by plum-lihui** [comment]
不好意思，提供信息有点少，无法直接判断是哪里的问题。请参考 [5. 遇到错误"Unable to establish connection", 我怎么办？](https://www.taosdata.com/cn/documentation20/faq/) 排查一下。
