### ISSUE TITLE
connection to Grafana get "HTTP Error Bad Gateway"

### ISSUE THREAD

**Issue by dongdan39** [taosdata/TDengine#3025]
Hi,  Expert,
  I started the tdengine with:
docker run -d --name tdengine -p 6020-6041:6020-6041 tdengine/tdengine:latest

And when I try to connect to it as data source with grafana, I got:
"HTTP Error Bad Gateway"

I'm trying with:
Host: localhost:6020
￼User: root
￼Password: taosdata

Can you help me? Thanks!
Cheers,
Dan

**Comment by sangshuduo** [comment]
Please use 6041 instead of 6020 if you are using 2.0.

**Comment by dongdan39** [comment]
> Please use 6041 instead of 6020 if you are using 2.0.

Thanks! But I got the same error. I think I'm using version 2.0:
[root@1c8040d9139b driver]# ll
total 4408
-rwxr-xr-x 1 root root 4513224 Aug  6 09:02 libtaos.so.2.0.0.1

**Comment by sangshuduo** [comment]
Can you try using an IP address instead of localhost?

**Comment by dongdan39** [comment]
> Can you try using an IP address instead of localhost?

Yes, actually I tried with:
http://127.0.0.1:6041
but the result is the same.

**Comment by dongdan39** [comment]
Sorry when I tried with the real IP of 192.168.*.*, it works! What's the problem? Thanks a lot!

**Comment by sangshuduo** [comment]
I think it's a networking setting issue. Neither TDengine nor Grafana.
