### ISSUE TITLE
Use http connect to server,notice :parse basic auth token error

### ISSUE THREAD

**Issue by phpliao** [taosdata/TDengine#3030]
Use postman request local server http://192.16.8.138:6041/rest/login/root/taosdata,header Authorization is return error

{
    "status": "error",
    "code": 5052,
    "desc": "parse basic auth token error"
}

**Comment by guanshengliang** [comment]
没有复现成功

- 采用postman发送请求

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/28882257/90361286-61dce380-e090-11ea-81bc-2a0bdbc49eb7.png">

- 采用curl发送请求
<img width="605" alt="image" src="https://user-images.githubusercontent.com/28882257/90361326-80db7580-e090-11ea-9ef3-984233fd2071.png">

两者均没有问题，如果还不能解决。请将httpDebugFlag设置为143，并将taosdlog.*日志打包上传来分析

**Comment by Aries-Lee1991** [comment]
@phpliao 是否有后续？

**Comment by guanshengliang** [comment]
There is no response to this issue for a long time, and this issue has been fixed in 2.0.1.1 version, so close it
