### ISSUE TITLE
 TDengine version number is 2.0.0.1, the query takes long time

### ISSUE THREAD

**Issue by manbushen** [taosdata/TDengine#3032]
版本号2.0.0.1  随便一个查询语句，耗时很长
linux 版本   CentOS Linux release 7.5.1804 (Core)
![123](https://user-images.githubusercontent.com/52345913/89983090-865c4880-dca9-11ea-8835-be9f858c74af.png)
[taos.zip](https://github.com/taosdata/TDengine/files/5061083/taos.zip)

**Comment by Aries-Lee1991** [comment]
建议先升级版本试试，现在已经更新到2.0.0.4

**Comment by manbushen** [comment]
> 建议先升级版本试试，现在已经更新到2.0.0.4

官网最新版本是2.0.0.1

**Comment by Aries-Lee1991** [comment]
> > 建议先升级版本试试，现在已经更新到2.0.0.4
> 
> 官网最新版本是2.0.0.1

请看GitHub的release
