### ISSUE TITLE
A memory consumption exception occurred in a multiprocess performance test

### ISSUE THREAD

**Issue by jin522** [taosdata/TDengine#3038]
**Performance Issue** 
write data into taos(20000records/s * 16 processes on a node)by taos-jdbc,after running a period of time,The physical memory will be used up and the JVM will be killed

**Problem Description** 
when i write data into taos by jdbc,Used physical Memory continues to increase along with time going.finally,when all physical mem has been used,part of 16 process will be killed,then release some mem can continue to run other process，always like this，until all processes are killed

* OS: CentOS 7.0
* 96GB*6nodes,40core*6nodes,3T disk *6nodes
* TDengine Version 2.0.1
*jdbcdriver version 2.0.0

**Comment by jin522** [comment]
or say,when jdbc call JNI function library, Is there a memory recovery mechanism?

**Comment by 18378333917** [comment]
Which version of  taos-jdbc driver do you use with this problem?I have this problem in taos-jdbcdriver 2.0.2 to connect tdengine 2.0.1,when I use taos-jdbcdriver 1.0.3 to connect tdengine 1.6.5.9 is normal.

**Comment by jin522** [comment]
@18378333917 taos-jdbcdriver 2.0.0 which I used in this test，and instead of get jdbc from maven lib，I compile the jdbc-driver 2.0.0 by myself from tdengine2.0.1 source

**Comment by sangshuduo** [comment]
please use latest TDengine and JDBC driver to try. We did fix a memory leak bug recently.

**Comment by zyyang-taosdata** [comment]
check your code and use jdbc like this:
```
Statement stat = connection.createStatement();
ResultSet result = stat.execute(sql);
while(result.next()){
...
}
result.close();
stat.close();
```
the statement should be closed every time

**Comment by zyyang-taosdata** [comment]
this issue is closed by the assignees
