### ISSUE TITLE
docker TDengine.2.0.0.1 image, Golang db exec failed: Unexpected generic error in RPC

### ISSUE THREAD

**Issue by Kittoa** [taosdata/TDengine#3040]
For TDengine.2.0.0.1 docker image, i use golang drive  to connect  taos, but i meet a error :Unexpected generic error in RPC.
example:
![image](https://user-images.githubusercontent.com/17596488/90016577-c983df00-dcdc-11ea-9f4b-c578d227f8b0.png)
running result:
![image](https://user-images.githubusercontent.com/17596488/90016748-0fd93e00-dcdd-11ea-8140-a368d1f7edc6.png)
docker info:
![image](https://user-images.githubusercontent.com/17596488/90016829-339c8400-dcdd-11ea-82ae-0702305506c9.png)

**Comment by localvar** [comment]
could you please help check if `hostname` is correctly configured or not? thanks.

```shell
hostname
```

**Comment by Kittoa** [comment]
![image](https://user-images.githubusercontent.com/17596488/90091184-5a4bd080-dd58-11ea-9d1a-fcec4bede1d0.png)

**Comment by Kittoa** [comment]
modify fqdn hostname to 127.0.0.1
