### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by hiddenscroll** [taosdata/TDengine#3046]
**Bug Description**

 Trying to CREATE DATABASE demo DAYS 10 CACHE 16000 ROWS 2000  throws an sql error. Removing cache and rows executes
**To Reproduce**
1. Go to taos 
2. Type in CREATE DATABASE demo DAYS 10 CACHE 16000 ROWS 2000 
3. See error

**Expected Behavior**

No error

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0] Ubuntu 18.04
 - Memory, CPU, current Disk Space 30GB disk
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by Aries-Lee1991** [comment]
Please attach the details. about version, optional steps, and the log.

**Comment by hjxilinx** [comment]
CREATE DATABASE demo DAYS 10 CACHE 16000 ROWS 2000
创建 DB 的时候，CACHE 的单位是 MB， 16000就是16GB 每个 VNODE。不可能分配出来。
