### ISSUE TITLE
The prepare query return empty data.

### ISSUE THREAD

**Issue by amuluowin** [taosdata/TDengine#3054]
**Bug Description**
The prepare query return empty data.

**To Reproduce**
1. Go to tests/examples/c'
2. gcc -o prepare prepare.c -ltaos
3. run prepare localhost

**Expected Behavior**
Prepare can return data in query, but insert success

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.8 & WSL2 Ubuntu 20.04]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 2.0.0.1~2.0.0.6]

**Additional Context**

**Comment by xiaopingcs** [comment]
prepare 应该是顺利执行了，只是没有任何输出。因为最后一行是return getchar(), 是在等待一个用户输入才能返回，所以看起来像一直在运行无法结束。你可以用taos客户端确认一下数据是否已经写入。

**Comment by amuluowin** [comment]
196行有打印查询结果，控制台没有输出，debug跟踪后taos_fetch_row返回了null，没有进while

**Comment by amuluowin** [comment]
写入是成功的，只是通过prepare的方式查询不到数据，返回null

**Comment by xiaopingcs** [comment]
> 写入是成功的，只是通过prepare的方式查询不到数据，返回null

这个问题我们正在看，今天应该会有结果

**Comment by xiaopingcs** [comment]
> 写入是成功的，只是通过prepare的方式查询不到数据，返回null

问题已经修复. 需要重新编译运行taosd, 然后再执行prepare localhost。谢谢反馈，如果确认没有问题，麻烦你把这个issue关闭掉。

**Comment by amuluowin** [comment]
已验证，关闭
