### ISSUE TITLE
taosdump is error

### ISSUE THREAD

**Issue by liqilong2017** [taosdata/TDengine#3062]
执行：taosdump -uroot -o /root/taos_bak/ --databases saas -ptaosdata
ERROR: thread:510 failed connect to TDengine, error:Unable to establish connection
taosdump 执行报错、、但是目录里有各个表

**Comment by plum-lihui** [comment]
taosdump报错，应该是与taosd之间连接不上。你收的目录里有各个表，是什么意思？是表以及表中的数据已经都导出来了吗？

**Comment by liqilong2017** [comment]
导出了部分表、可能有600 个但是只导出了 500个左右，然后报错了

**Comment by plum-lihui** [comment]
有没有出现taosd奔溃的问题？

**Comment by liqilong2017** [comment]
崩溃倒是没有

**Comment by plum-lihui** [comment]
已经发布了最新的v2.0.4.0，试试最新的版本试试吧，解决了不少bug。
