### ISSUE TITLE
超级表中添加49000个子表后提示need more dnode 

### ISSUE THREAD

**Issue by kidari** [taosdata/TDengine#307]
需要修改配置文件哪个字段？磁盘使用10%

**Comment by guanshengliang** [comment]
通过执行
```
show databases
```
可以看到数据库的配置，猜测tables参数为1000，表示每个vnode最多能创建1000张表

按照你的机器配置，应该最多能够创建50个Vnode，而log数据库已经占用了1个vnode，那么剩下可用的vnode为49个，所以只能创建49000张表。

需要删除该数据库，再重新创建数据库，并指定tables参数，例如
```
create database db tables 5000
```
目前不支持对数据库的tables参数进行修改
