### ISSUE TITLE
raspberry上怎样安装connector呀？

### ISSUE THREAD

**Issue by txeagle** [taosdata/TDengine#308]
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:49 (MESSAGE):
  The current platform is Linux 32-bit, not supported yet

-- Configuring incomplete, errors occurred!
See also "/home/pi/TDengine/build/CMakeFiles/CMakeOutput.log".

**Comment by hzcheng** [comment]
目前不支持在32位机器上编译运行。32位版本的会在年底前发布。
