### ISSUE TITLE
TSDB error: failed to connect to server

### ISSUE THREAD

**Issue by tianqidongwu** [taosdata/TDengine#309]
启动服务 输入taos后，出现
Welcome to the TDengine shell, client version:1.6.1.5  
TSDB error: failed to connect to server
然后我查看服务状态
● taosd.service - TDengine server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since 六 2019-08-10 10:37:35 CST; 30s ago
  Process: 76491 ExecStart=/usr/bin/taosd (code=dumped, signal=SEGV)
 Main PID: 76491 (code=dumped, signal=SEGV)

**Comment by hzcheng** [comment]
您这是干净的环境还是升级服务？如果方便的话，您可以尝试用GDB启动
```
sudo gdb taosd
```
然后运行
```
r
```
如果它出问题，会暂停，您运行
```
bt
```
将截图发下看下吧。

**Comment by tianqidongwu** [comment]
你好，我是在我的虚拟机centOS上做的。

这个问题在我关闭taosd服务后，过一会儿再重新启动的时候就会发生。


 


------------------ 原始邮件 ------------------
发件人: "hzcheng"<notifications@github.com>;
发送时间: 2019年8月9日(星期五) 中午12:05
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
抄送: "Smitten"<972226220@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [taosdata/TDengine] TSDB error: failed to connect to server(#309)




您这是干净的环境还是升级服务？如果方便的话，您可以尝试用GDB启动
 sudo gdb taosd  
然后运行
 r  
如果它出问题，会暂停，您运行
 bt  
将截图发下看下吧。
