### ISSUE TITLE
AttributeError: module 'taos' has no attribute 'connect'

### ISSUE THREAD

**Issue by wujiops** [taosdata/TDengine#3092]
AttributeError: module 'taos' has no attribute 'connect'
![0](https://user-images.githubusercontent.com/58058753/90350739-9b055b80-e070-11ea-9a50-a8fa3ee4d6e4.jpg)

**Comment by xiaopingcs** [comment]
python使用的是哪一个版本？请在driver里找到Python connector并安装
python2: pip install src/connector/python/linux/python2/
python3: pip3 install src/connector/python/linux/python3/

**Comment by wujiops** [comment]
[root@emqx TDengine-client]# pip3 install connector/python/linux/python3/
Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Processing ./connector/python/linux/python3
Using legacy 'setup.py install' for taos, since package 'wheel' is not installed.
Installing collected packages: taos
  Attempting uninstall: taos
    Found existing installation: taos 2.0.0
    Uninstalling taos-2.0.0:
      Successfully uninstalled taos-2.0.0
    Running setup.py install for taos ... done
Successfully installed taos-2.0.0
[root@emqx TDengine-client]# python3 taos.py 
Traceback (most recent call last):
  File "taos.py", line 1, in <module>
    import taos
  File "/mnt/TDengine-client/taos.py", line 3, in <module>
    conn = taos.connect(host="192.168.1.115", user="root", password="taosdata", config="/etc/taos")
AttributeError: module 'taos' has no attribute 'connect'
并不行  这个一开始就是按照文档来装的，两台机器都是同样的错误。module 'taos' has no attribute 'connect'

**Comment by xiaopingcs** [comment]
<img width="1075" alt="Screen Shot 2020-08-17 at 2 26 34 PM" src="https://user-images.githubusercontent.com/65699335/90363778-d7977e00-e095-11ea-8f8a-60cd8fe34fb4.png">
你要不装一下wheel试试，我这边用官网的安装包安装的，没有问题

**Comment by sangshuduo** [comment]
操作系统是什么发行版？什么版本？

**Comment by wujiops** [comment]
centos 7.7.1908
centos 7.8.2003

**Comment by wujiops** [comment]
你好  我做的是3台集群  我在master主机是可以用Python Connector的。在其它机器都是出现module 'taos' has no attribute 'connect'。
即使我在第四台主机安装了单机的taos-server，也不能使用Python Connector，加载taos模块报错。
使用的rpm包安装。版本是taos-server-2.0.0.1  和 taos-server-2.0.1.0，还有在taos-client-linux的tar包里面找不到taosdump。

**Comment by sangshuduo** [comment]
我在一台 CentOS 7.8 上没发现有什么问题，如果您有一台是可以的，能否看一下另外几台不行的机器在系统上有什么区别？是否没有执行完整步骤？

**Comment by wujiops** [comment]
系统版本：`centos 7.8.2003`，`AttributeError: module 'taos' has no attribute 'connect'`已解决。（`重启`服务器🥱）

具体步骤：4台新装服务器，关闭`selinux`、`firewalld`

`node1`、`node2`、`node3`安装`TDengine-server`，步骤参考集群[文档](https://www.taosdata.com/cn/documentation/cluster/#%E5%AE%89%E8%A3%85%E3%80%81%E5%88%9B%E5%BB%BA%E5%90%8E%E7%BB%AD%E8%8A%82%E7%82%B9)

`node4`安装`python3`，`yum -y install python3 python3-devel python3-pip`，安装`TDengine-client`，下载`TDengine-client-2.0.1.0-Linux-x64.tar.gz`包解压，`bash TDengine-client/install_client.sh`

新建`py`文件，测试`Python-Connector`，`pip3 install TDengine-client/connector/python/linux/python3/`参考[文档](https://www.taosdata.com/cn/documentation/connector/#Python-Connector)

遇到的问题1，`py`文件名字不要是`taos.py`，否则报错：`AttributeError: module 'taos' has no attribute 'connect'`（此错误是`python`的规则，`.py`文件即模块）。

遇到的问题2，`taos.error.ProgrammingError: Disconnected from service`，重启了`node1-4`。此错误在集群宕机数量达到`vnode`的一半时也会出现，数据库也会报错：
```sql
taos> SHOW DNODES;

DB error: Unable to establish connection
```

其它对服务器的操作：做了`时间同步`。`hostnamectl set-hostname xxx`对四台机器设置了主机名。

感谢@sangshuduo

**Comment by sangshuduo** [comment]
Good to know :)

**Comment by Visterainer** [comment]
`pip install taospy`
