### ISSUE TITLE
group by tagId was failed to connect socket, ip:172.168.1.248, port:6035, reason: Connection refused  DB error: invalid table id

### ISSUE THREAD

**Issue by hl3482477** [taosdata/TDengine#3094]
我新建了80万张表，每张表大约插入一万条数据，做group by查询的时候报错，求大佬帮忙
表结构如下：
stmt.executeUpdate("create table tag_history(createTime timestamp,temperature double) " +
                "tags (tagId nchar(15))");
sql如下：
select avg(temperature) from tag_history where createTime > now -1d group by tagId ;

报错如下：

08/17 10:56:49.398149 18283 7f826431a700 ERROR UTL failed to connect socket, ip:172.168.1.248, port:6035, reason: Connection refused
08/17 10:56:49.398218 18283 7f826431a700 ERROR UTL failed to connect socket, ip:172.168.1.248, port:6035, reason: Connection refused
08/17 10:56:49.401953 18283 7f826431a700 ERROR UTL failed to connect socket, ip:172.168.1.248, port:6035, reason: Connection refused
08/17 10:56:49.402057 18283 7f826431a700 ERROR UTL failed to connect socket, ip:172.168.1.248, port:6035, reason: Connection refused
08/17 10:56:49.402134 18283 7f826431a700 ERROR UTL failed to connect socket, ip:172.168.1.248, port:6035, reason: Connection refused
08/17 10:56:49.402183 18283 7f826431a700 ERROR UTL failed to connect socket, ip:172.168.1.248, port:6035, reason: Connection refused
08/17 10:56:49.402221 18283 7f826431a700 ERROR UTL failed to connect socket, ip:172.168.1.248, port:6035, reason: Connection refused
08/17 10:56:49.402264 18283 7f826431a700 ERROR UTL failed to connect socket, ip:172.168.1.248, port:6035, reason: Connection refused
08/17 10:56:49.402293 18283 7f826431a700 ERROR UTL failed to connect socket, ip:172.168.1.248, port:6035, reason: Connection refused
08/17 10:56:49.402328 18283 7f826431a700 ERROR UTL failed to connect socket, ip:172.168.1.248, port:6035, reason: Connection refused
08/17 10:56:49.402371 18283 7f826431a700 ERROR UTL failed to connect socket, ip:172.168.1.248, port:6035, reason: Connection refused
08/17 10:56:49.402408 18283 7f826431a700 ERROR UTL failed to connect socket, ip:172.168.1.248, port:6035, reason: Connection refused
08/17 10:56:49.402446 18283 7f826431a700 ERROR UTL failed to connect socket, ip:172.168.1.248, port:6035, reason: Connection refused
08/17 10:56:49.402484 18283 7f826431a700 ERROR UTL failed to connect socket, ip:172.168.1.248, port:6035, reason: Connection refused
08/17 10:56:49.402526 18283 7f826431a700 ERROR UTL failed to connect socket, ip:172.168.1.248, port:6035, reason: Connection refused
08/17 10:56:49.402564 18283 7f826431a700 ERROR UTL failed to connect socket, ip:172.168.1.248, port:6035, reason: Connection refused
08/17 10:56:49.402602 18283 7f826431a700 ERROR UTL failed to connect socket, ip:172.168.1.248, port:6035, reason: Connection refused
08/17 10:56:49.402642 18283 7f826431a700 ERROR UTL failed to connect socket, ip:172.168.1.248, port:6035, reason: Connection refused
08/17 10:56:49.402694 18283 7f826431a700 ERROR UTL failed to connect socket, ip:172.168.1.248, port:6035, reason: Connection refused
08/17 10:56:49.402755 18283 7f826431a700 ERROR UTL failed to connect socket, ip:172.168.1.248, port:6035, reason: Connection refused
08/17 10:56:49.402795 18283 7f826431a700 ERROR UTL failed to connect socket, ip:172.168.1.248, port:6035, reason: Connection refused
08/17 10:56:49.402832 18283 7f826431a700 ERROR UTL failed to connect socket, ip:172.168.1.248, port:6035, reason: Connection refused

DB error: invalid table id

**Comment by hjxilinx** [comment]
您好，您有更详细的日志 提供吗？
