### ISSUE TITLE
Can't receive  e-mail with gmail when download deb pk

### ISSUE THREAD

**Issue by JackyYangPassion** [taosdata/TDengine#31]
https://www.taosdata.com/cn/getting-started/#%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B

**Comment by StoneT2000** [comment]
Thanks for letting us know! Just made an update to the website, try downloading it again.

**Comment by JackyYangPassion** [comment]
3Q! try again ,it works!
