### ISSUE TITLE
change the datadir 

### ISSUE THREAD

**Issue by liqilong2017** [taosdata/TDengine#3103]
想把 数据目录更换一下，步骤如下：
1、停止服务，并修改配置文件
2、原数据文件迁移
3、重新启动服务

不知道这个过程是否有问题

**Comment by Shawshank-Smile** [comment]
and between ‘2’ and ‘3’，you need a tool to modify some files. However, this tool and service is only for the enterprise customers.
If your is very important, please add my wechat: 13720014098.
