### ISSUE TITLE
not activated for submit

### ISSUE THREAD

**Issue by thingio** [taosdata/TDengine#311]
TaosData兄弟们好,

碰到一个问题, 我在根据链接
https://www.taosdata.com/cn/documentation/super-table/
熟悉你们的SQL,

建立完STable以后, 建立Table, 在插入的时候碰到: fail to connect to server
![image (1)](https://user-images.githubusercontent.com/45798691/62757012-5b468400-baac-11e9-9005-4e120638840a.png)

当时服务器日志是: DND vid:2 is not  activated for submit
![image](https://user-images.githubusercontent.com/45798691/62756999-4ec22b80-baac-11e9-8902-b1be1b9d5f09.png)

系统版本是:
char version[64] = "1.6.1.4";
char compatible_version[64] = "1.6.1.0";
char gitinfo[128] = "36936e19eb26b5e45107bca95394133e3ac7c3a1";
char buildinfo[512] = "Built by slguan at 2019-08-05 09:24";

请不吝赐教

**Comment by guanshengliang** [comment]
1.6.1.5版本已经可以下载了，您可以使用这个版本实验问题是否还存在。

在1.6.1.5版本上，按照您的步骤，无法复现。因此，请按照以下步骤操作，以便于我们定位问题

1.停止服务
```
sudo systemctl stop taosd
```

2.清空数据和日志
```
rm -rf /var/lib/taos/*
rm -rf /var/log/taos/*
```

3.开启全量日志，即修改/etc/taos/taos.cfg，增加一行
```
debugFlag 135
```

4.启动服务
```
sudo systemctl start taosd
```

5.重新开始您的测试

6.将文件夹/var/log/taos/*下的日志文件打包
```
cd /var/log/taos
sudo tar -czvf log.tar.gz *
```

7.将压缩文件发给我的信箱
```
slguan@taosdata.com
```
