### ISSUE TITLE
java.sql.SQLException: TDengine Error: invalid SQL: 

### ISSUE THREAD

**Issue by SciHan** [taosdata/TDengine#3115]
**Bug Description**
在使用jdbc的时候，如果使用conn.prepareStatement(String sql)方法拼接sql的时候，如果调用prepareStatement的setString(int parameterIndex, String x)方法的时候，如果拼接的字符串x有问号的话，下一个拼接的属性值就会拼接到前一个字符串中的问号中，而不是sql中预编译的问号位置造成sql乱序插入失败，具体的类应该是SavedPreparedStatement中的replaceTemplateParam方法，里面调用的是string的replaceFirst方法可能不够严谨。

**Comment by zyyang-taosdata** [comment]
感谢您的提醒，为我们开发提供了宝贵意见，我们会跟踪这个问题，谢谢。
