### ISSUE TITLE
TDengine DB error: invalid vgroup id

### ISSUE THREAD

**Issue by tangshilin520** [taosdata/TDengine#3116]
1. TDengine 集群部署成功后，通过taosdemo  插入测试数据；
2. 通过taos  sql能正常访问数据；
3. 重启所有的集群设备，再次通过taos  sql不能正常访问数据； 

taos> show databases;
              name              |      created_time       |   ntables   |   vgroups   | replica | quorum |  days  |    keep1,keep2,keep(D)     |  cache(MB)  |   blocks    |   minrows   |  | comp | precision |    status    |
===============================================================================================================================================================================================================================
 test                           | 2020-08-17 16:36:09.608 |       10000 |          10 |       1 |      1 |      2 | 3650,3650,3650             |          16 |           6 |         100 |  |    2 | ms        | ready        |
 log                            | 2020-08-17 15:26:50.634 |           6 |           1 |       1 |      1 |     10 | 30,30,30                   |           1 |           3 |         100 |  |    2 | us        | ready        |
Query OK, 2 row(s) in set (0.002565s)

taos> show dnodes;
   id   |           end_point            | vnodes | cores  |     status     |   role   |       create_time       |
==================================================================================================================
      1 | 192.168.1.185:6030             |      1 |      8 | ready          | any      | 2020-08-17 15:26:47.620 |
      2 | 192.168.1.202:6030             |      9 |     24 | ready          | any      | 2020-08-17 15:27:53.539 |
      3 | 192.168.1.227:6030             |      1 |      8 | ready          | any      | 2020-08-17 16:06:42.973 |
Query OK, 3 row(s) in set (0.002107s)

taos> show mnodes;
   id   |           end_point            |      role      |       create_time       |
=====================================================================================
      1 | 192.168.1.185:6030             | master         | 2020-08-17 15:26:47.620 |
      2 | 192.168.1.202:6030             | slave          | 2020-08-17 16:09:33.894 |
      3 | 192.168.1.227:6030             | slave          | 2020-08-17 16:07:04.292 |
Query OK, 3 row(s) in set (0.002734s)

taos> select count(*) from test.meters;

DB error: Invalid Vgroup ID
taos>

**Comment by guanshengliang** [comment]
show databases; show mnodes; show dnodes; 这三个命令是在重启设备之前执行的，还是在重启之后执行的
重启设备，是指重启数据库，还是重启虚拟机/物理机
以上三个机器，重启之后IP是否有发生变化
可将所有机器的日志清空后，在配置文件设置debugFlag 135，然后将三个机器的taosdlog文件提交，我来分析

**Comment by tangshilin520** [comment]
重启设备之前，功能是正常的；重启设备指设备断电；设备为静态IP；
[log.zip](https://github.com/taosdata/TDengine/files/5093751/log.zip)

**Comment by guanshengliang** [comment]
这个问题之前出现过，是在负载均衡过程的一个BUG导致，2.0.1.1已经发布，并且修复了您的这问题。
从日志上看，数据库中还都是测试数据，因此建议将数据库重置（删除/var/lib/taos中的数据），然后再重新开始相同的步骤，如果还有问题，咱们继续分析解决。
