### ISSUE TITLE
taos connect failed, reason: Unable to establish connection.

### ISSUE THREAD

**Issue by botao-git** [taosdata/TDengine#3123]
version: 2.0.1.0
安装单节点成功后,执行 taos 无法建立连接
[root@i-uxksyhss taos]# taos

Welcome to the TDengine shell from Linux, Client Version:2.0.1.0
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

taos connect failed, reason: Unable to establish connection.

检查安装目录下的日志信息：
==================================================
                new log file                      
==================================================
08/18 15:37:31.733131 0x7fc2557db740 UTL localEp is: i-uxksyhss:6030
08/18 15:37:31.733447 0x7fc2557db740 UTL timezone not configured, set to system default: (CST, +0800)
08/18 15:37:31.733521 0x7fc2557db740 UTL ERROR locale not configured, set to system default:en_US.UTF-8
08/18 15:37:31.733531 0x7fc2557db740 UTL WARN charset not configured, set to system default:UTF-8
08/18 15:37:31.733581 0x7fc2557db740 UTL    taos config & system info:
08/18 15:37:31.733587 0x7fc2557db740 UTL ==================================
08/18 15:37:31.733590 0x7fc2557db740 UTL  firstEp:                i-uxksyhss:6030 
08/18 15:37:31.733592 0x7fc2557db740 UTL  secondEp:               i-uxksyhss:6030 
08/18 15:37:31.733609 0x7fc2557db740 UTL  fqdn:                   i-uxksyhss 
08/18 15:37:31.733611 0x7fc2557db740 UTL  serverPort:             6030 
08/18 15:37:31.733613 0x7fc2557db740 UTL  configDir:              /etc/taos 
08/18 15:37:31.733614 0x7fc2557db740 UTL  logDir:                 /var/log/taos 
08/18 15:37:31.733632 0x7fc2557db740 UTL  scriptDir:              /etc/taos 
08/18 15:37:31.733634 0x7fc2557db740 UTL  arbitrator:              
08/18 15:37:31.733635 0x7fc2557db740 UTL  numOfThreadsPerCore:    1.000000 
08/18 15:37:31.733659 0x7fc2557db740 UTL  rpcTimer:               1000(ms)
08/18 15:37:31.733661 0x7fc2557db740 UTL  rpcMaxTime:             600(s)
08/18 15:37:31.733663 0x7fc2557db740 UTL  shellActivityTimer:     3(s)
08/18 15:37:31.733664 0x7fc2557db740 UTL  tableMetaKeepTimer:     7200(s)
08/18 15:37:31.733681 0x7fc2557db740 UTL  compressMsgSize:        -1 
08/18 15:37:31.733682 0x7fc2557db740 UTL  maxSQLLength:           65480(byte)
08/18 15:37:31.733684 0x7fc2557db740 UTL  maxNumOfOrderedRes:     100000 
08/18 15:37:31.733685 0x7fc2557db740 UTL  timezone:                (CST, +0800) 
08/18 15:37:31.733702 0x7fc2557db740 UTL  locale:                 en_US.UTF-8 
08/18 15:37:31.733704 0x7fc2557db740 UTL  charset:                UTF-8 
08/18 15:37:31.733706 0x7fc2557db740 UTL  numOfLogLines:          10000000 
08/18 15:37:31.733707 0x7fc2557db740 UTL  asyncLog:               1 
08/18 15:37:31.733723 0x7fc2557db740 UTL  debugFlag:              0 
08/18 15:37:31.733726 0x7fc2557db740 UTL  rpcDebugFlag:           131 
08/18 15:37:31.733727 0x7fc2557db740 UTL  tmrDebugFlag:           131 
08/18 15:37:31.733728 0x7fc2557db740 UTL  cDebugFlag:             131 
08/18 15:37:31.733743 0x7fc2557db740 UTL  jniDebugFlag:           131 
08/18 15:37:31.733745 0x7fc2557db740 UTL  odbcDebugFlag:          131 
08/18 15:37:31.733777 0x7fc2557db740 UTL  uDebugFlag:             131 
08/18 15:37:31.733780 0x7fc2557db740 UTL  qDebugFlag:             131 
08/18 15:37:31.733782 0x7fc2557db740 UTL  tsdbDebugFlag:          131 
08/18 15:37:31.733783 0x7fc2557db740 UTL  gitinfo:                7ac6c2b8de3cd66e180132fc1cf77715237308a1 
08/18 15:37:31.733799 0x7fc2557db740 UTL  gitinfoOfInternal:       
08/18 15:37:31.733801 0x7fc2557db740 UTL  buildinfo:              Built by root at 2020-08-17 11:12 
08/18 15:37:31.733802 0x7fc2557db740 UTL  version:                2.0.1.0 
08/18 15:37:31.733804 0x7fc2557db740 UTL  maxBinaryDisplayWidth:  30 
08/18 15:37:31.733821 0x7fc2557db740 UTL  os pageSize:            4096(KB)
08/18 15:37:31.733823 0x7fc2557db740 UTL  os openMax:             1024
08/18 15:37:31.733824 0x7fc2557db740 UTL  os streamMax:           16
08/18 15:37:31.733826 0x7fc2557db740 UTL  os numOfCores:          4
08/18 15:37:31.733827 0x7fc2557db740 UTL  os totalDisk:           0.000000(GB)
08/18 15:37:31.733829 0x7fc2557db740 UTL  os totalMemory:         15887(MB)
08/18 15:37:31.733831 0x7fc2557db740 UTL  os sysname:             Linux
08/18 15:37:31.733833 0x7fc2557db740 UTL  os nodename:            i-uxksyhss
08/18 15:37:31.733834 0x7fc2557db740 UTL  os release:             3.10.0-327.4.5.el7.x86_64
08/18 15:37:31.733835 0x7fc2557db740 UTL  os version:             #1 SMP Mon Jan 25 22:07:14 UTC 2016
08/18 15:37:31.733869 0x7fc2557db740 UTL  os machine:             x86_64
08/18 15:37:31.733872 0x7fc2557db740 UTL ==================================
08/18 15:37:31.733890 0x7fc2557db740 UTL the old unlimited para: rlim_cur=0, rlim_max=18446744073709551615
08/18 15:37:31.733903 0x7fc2557db740 UTL the new unlimited para: rlim_cur=18446744073709551615, rlim_max=18446744073709551615
08/18 15:37:31.733914 0x7fc2557db740 UTL _sysctl(kern_core_uses_pid) set fail: Function not implemented
08/18 15:37:31.733916 0x7fc2557db740 UTL The old core_uses_pid[4]: 0
08/18 15:37:31.733918 0x7fc2557db740 UTL _sysctl(kern_core_uses_pid) get fail: Function not implemented
08/18 15:37:31.733919 0x7fc2557db740 UTL The new core_uses_pid[4]: 0

**Comment by shiweiY** [comment]
请问是什么原因呢，我也遇到了这个问题

**Comment by chijey** [comment]
why  closed?

**Comment by jiaozg22** [comment]
taos -h 主机名（不是域名，或者ip）

**Comment by liushaowenliushaowen** [comment]
您好，解决了没，我是rpm安装，也是报这个错

**Comment by TomThread** [comment]
我也抱着个错误，解决没有

**Comment by amumuku** [comment]
taos -h  内网 ip(看下本机 /etc/hosts)

**Comment by qiuxuelaici** [comment]
这个没看到怎么解决的呀

**Comment by yu285** [comment]
https://www.taosdata.com/engineering/11076.html 看下问题1 排查一下
