### ISSUE TITLE
taosdump error

### ISSUE THREAD

**Issue by wangyalong0401** [taosdata/TDengine#3125]
Error using taosdump：
taosdump: error while loading shared libraries: libtaos.so.1: cannot open shared object file: No such file or directory

How to solve this problem？

**Comment by plum-lihui** [comment]
确认正确安装了tdengine安装包后，ll 一下/usr/lib下面是否有 libtaos.so， libtaos.so.1。如果不存在，说明安装不正确。如果存在，看看环境变量中是否设置正确。

**Comment by darrenji** [comment]
When I installed taosTools-2.1.2-Linux-x64.deb on Ubuntu 18.04, It failed.
![无法安装](https://user-images.githubusercontent.com/2604576/186380496-6acb4ad5-39ed-4b52-b8e8-99ae97a396d0.png)
![系统版本](https://user-images.githubusercontent.com/2604576/186380574-3a548844-0b08-4645-b4d8-f66c8ac16227.png)
Under /usr/bin like this:
![lib](https://user-images.githubusercontent.com/2604576/186380665-67fd5fc0-ab7a-45be-8cf4-345146792b93.png)
Environment related like this:
![env1](https://user-images.githubusercontent.com/2604576/186380808-bc925091-e00b-4ad1-83ea-724621447793.png)
![env2](https://user-images.githubusercontent.com/2604576/186380850-e4e762f1-6d97-48b1-b706-8f7d5c4670bb.png)

**Comment by darrenji** [comment]
> When I installed taosTools-2.1.2-Linux-x64.deb on Ubuntu 18.04, It failed. ![无法安装](https://user-images.githubusercontent.com/2604576/186380496-6acb4ad5-39ed-4b52-b8e8-99ae97a396d0.png) ![系统版本](https://user-images.githubusercontent.com/2604576/186380574-3a548844-0b08-4645-b4d8-f66c8ac16227.png) Under /usr/bin like this: ![lib](https://user-images.githubusercontent.com/2604576/186380665-67fd5fc0-ab7a-45be-8cf4-345146792b93.png) Environment related like this: ![env1](https://user-images.githubusercontent.com/2604576/186380808-bc925091-e00b-4ad1-83ea-724621447793.png) ![env2](https://user-images.githubusercontent.com/2604576/186380850-e4e762f1-6d97-48b1-b706-8f7d5c4670bb.png)

I have solved this problem after I turned to Shuduo@涛思. He helped me a lot. Thanks. The reason is that the deb file I got perhaps was a broken one.

**Comment by WenYuan1010** [comment]
检查tdengine-client 版本和tdengine-server是否一致；更换taostools版本，多试几个taostools版本,一般是因为tools的版本不对。
