### ISSUE TITLE
taos client 2.0.1.0 can't connect to remote server!

### ISSUE THREAD

**Issue by yokewang** [taosdata/TDengine#3129]
Server: 2.0.1.0  IP: 192.168.99.241 OS: CentOS 7.4 64bit
Client: 2.0.1.0  IP: 192.168.99.240 OS: CentOS 7.4 64bit
From Client Side, using "taos -h 192.168.99.241 " can't connect to remote server.
It seems taos can only connect to localhost.
The firewall is disabled.

**Comment by zyyang-taosdata** [comment]
请提供更多的client端的报错信息，please provide more error information of the client

**Comment by yokewang** [comment]
It seems that cmd "taos" only uses the host defined in taos.cfg and ignore  "-h" parameters.
So, when I run "taos" with "-c" and specify a specified config file, it works.
BTW，TDengine server is also running on client(just another standalone server, not cluster).

**Comment by zyyang-taosdata** [comment]
please show me the /var/log/taos/taoslog0.0
