### ISSUE TITLE
TDError.DatabaseError.OperationalError: Invalid use of fetchall,

### ISSUE THREAD

**Issue by sexbee** [taosdata/TDengine#3130]
**Bug Description**
deepin19
taosdta 2.0.1.0
 let query =  cursor.query('insert into' + ' ' .....
            ... query.execute().then(function (result)
Alert :
{ TDError.DatabaseError.OperationalError: Invalid use of fetchall, either result or fields from query are null. First execute a query first
    at TDengineCursor.fetchall (/usr/local/k/node_modules/td2.0-connector/nodetaos/cursor.js:176:11)
    at /usr/local/k/node_modules/td2.0-connector/nodetaos/taosquery.js:42:71
    at new Promise (<anonymous>)
    at TaosQuery.execute (/usr/local/k/node_modules/td2.0-connector/nodetaos/taosquery.js:35:26)

**Comment by sangshuduo** [comment]
Please provide all steps to reproduce. Thanks.

**Comment by sangshuduo** [comment]
close this issue if no new information.
