### ISSUE TITLE
有对时间操作的函数吗

### ISSUE THREAD

**Issue by BearTian** [taosdata/TDengine#3131]
### 表里面定义的时间格式为 timestamp，现有需求需要对时间进行平移一段时间，是否有对应的操作函数；

**伪代码：**
```
select linux_time + 10000 from log_p_3003;
```

![image](https://user-images.githubusercontent.com/20335105/90583325-70e3a300-e202-11ea-8180-ef773f433d3e.png)

**Comment by hjxilinx** [comment]
普通数值可以四则运算，时间戳暂不支持。
