### ISSUE TITLE
cannot connect server without network

### ISSUE THREAD

**Issue by liu18831337077** [taosdata/TDengine#3133]
1.在一个没有网的linux服务器上使用tar包部署时，安装后使用本机的客户端都无法连接，同样的步骤在一个有网的服务器上就可以。
2.使用java的demo远程连接服务器，只提示出“failed to connect to server”，并不会说明具体原因，难以排查错误。

**Comment by sangshuduo** [comment]
请提供版本信息和复现步骤

**Comment by hjxilinx** [comment]
您可以尝试设置一下本机的 IP 地址，然后重试。
第二个问题，您需要打开日志输出的配置项, 
```
debugflag 135
```
然后再次执行操作，检查日志会有详细的信息输出。日志路径：
```
/var/log/taos
```

**Comment by sangshuduo** [comment]
no update, close it.
