### ISSUE TITLE
在centos上安装windows不能访问

### ISSUE THREAD

**Issue by kingLi88** [taosdata/TDengine#314]
在centos上安装后，本地能正常访问，端口已开放6020，在局域网windows上用java连接失败。windows上已经安装客户端程序。提示服务器无法连接

**Comment by guanshengliang** [comment]
1. TCP`6020`端口是HTTP访问的端口，java通过jdbc访问TDengine，不走HTTP协议
2.在windows上开发程序，先确保通过taos.exe能够连接到linux服务端，然后再调试java
3.调试前，可以先将防火墙全部关闭，包括windows的防火墙和linux防火墙，以确定是防火墙问题还是网络本身不通
4.具体端口配置，可以参考
https://www.taosdata.com/cn/documentation/administrator/#服务端配置
```
mgmtShellPort：管理节点与客户端通信使用的TCP/UDP端口号（默认值是6030）。此端口号在内向后连续的5个端口都会被UDP通信占用，即UDP占用[6030-6034]，同时TCP通信也会使用端口[6030]。
vnodeShellPort：数据节点与客户端通信使用的TCP/UDP端口号（默认值是6035）。此端口号在内向后连续的5个端口都会被UDP通信占用，即UDP占用[6035-6039]，同时TCP通信也会使用端口[6035]
```

**Comment by 59471032** [comment]
把6020改成其他端口，用http接口可以访问到，用jdbc无法连接，这个是什么情况？

**Comment by guanshengliang** [comment]
jdbc访问不是通过http端口，而是通过mgmtShellPort和vnodeShellPort系列端口

**Comment by lst789** [comment]
关闭linux上的防火墙试试
