### ISSUE TITLE
python3 "import taos" report error

### ISSUE THREAD

**Issue by wobaa** [taosdata/TDengine#3140]
我按照官网上写明的安装方法执行后，
![Python Connector](https://user-images.githubusercontent.com/30998643/90611497-65f83500-e239-11ea-9330-b7fc3227d30a.png)    

运行项目，报错：
![import_eroor](https://user-images.githubusercontent.com/30998643/90611686-a22b9580-e239-11ea-8bbc-e98602171eb4.png)

想请教一下是为啥？

**Comment by xiaopingcs** [comment]
如果你用的是python3， 需要安装pip3, 然后用pip3 install src/connector/python/linux/python3试试

**Comment by wobaa** [comment]
我已经做过此操作，如下图
![3](https://user-images.githubusercontent.com/30998643/90612583-d5225900-e23a-11ea-9fff-3e76a1788a1d.png)

提示我成功了，我才运行项目，但最开始的import就报错了

**Comment by xiaopingcs** [comment]
你的taosd是怎么安装的，是直接用命令编译出来的还是下载我们官网安装包安装的？在python3的目录下面有一个test.py，你可以不可以运行python3 test.py看看是不是一样的结果

**Comment by wobaa** [comment]
python3运行test.py是一样的结果，我是下载下图qu圈出来的安装包之后
![1](https://user-images.githubusercontent.com/30998643/90617349-27ff0f00-e241-11ea-8a98-8760b19a97a2.png)

找到对应connector，就执行了pip命令，没进行其他操作

**Comment by xiaopingcs** [comment]
> python3运行test.py是一样的结果，我是下载下图圈出来的安装包之后
> ![1](https://user-images.githubusercontent.com/30998643/90617349-27ff0f00-e241-11ea-8a98-8760b19a97a2.png)
> 
> 找到对应connector，就执行了pip命令，没进行其他操作

你的错误是缺少libtaos.so, 这个文件是安装taosd才会有的。 你下载完安装包解压，需要先运行install.sh，这样就不会缺少libtaos.so这个文件了。
如果这样还不行， 就使用sudo systemctl start taosd 命令启动taosd，然后进入/usr/local/taos/bin, 运行taos 命令，看看是否能够正常连接。如果可以正常连接，再运行pip3 install python3/， 成功之后应该就没有问题了

如果出现taos客户端报错Unexpected generic error in RPC, 你需要在hosts文件中添加域名和IP的对应关系: 127.0.0.1 localhost (win10默认配置路径在:c:/windows/System32/drivers/etc目录下， Linux路径在/etc/hosts）
