### ISSUE TITLE
客户端和服务的版本必须一致吗？

### ISSUE THREAD

**Issue by liu18831337077** [taosdata/TDengine#3141]
我在服务器安装了一个2.0版本的TDengine，windows端安装了1.6的客户端，请问我的java程序一直无法连接到服务器，是因为版本问题吗？,但是我又没找到2.0的客户端

**Comment by yihaoDeng** [comment]
是的， 1.6用1.6的客户端， 2.x用2.x的客户端， 目前2.x的windows client还没发布，不过代码已经开发完成， 正在紧张测试中， 马山会官方发布

**Comment by liu18831337077** [comment]
> 是的，1.6用1.6的客户端，2.x用2.x的客户端，目前2.x的windows client还没发布，不过代码已经开发完成，正在紧张测试中，马山会官方发布
那如何在windows下开发程序呢？
