### ISSUE TITLE
win64 client(2.0.1.0) can't work until commenting some codes related to KeepTcpAlive

### ISSUE THREAD

**Issue by yokewang** [taosdata/TDengine#3149]
see below comments.

`
int taosKeepTcpAlive(SOCKET sockFd) {
  uDebug("keep alive checking "); 
  int alive = 1;
  if (taosSetSockOpt(sockFd, SOL_SOCKET, SO_KEEPALIVE, (void *)&alive, sizeof(alive)) < 0) {
    uError("fd:%d setsockopt SO_KEEPALIVE failed: %d (%s)", sockFd, errno, strerror(errno));
    taosCloseSocket(sockFd);
    return -1;
  }

  int probes = 3;
  //if (taosSetSockOpt(sockFd, SOL_TCP, TCP_KEEPCNT, (void *)&probes, sizeof(probes)) < 0) {
  //  uError("fd:%d setsockopt SO_KEEPCNT failed: %d (%s)", sockFd, errno, strerror(errno));
  //  taosCloseSocket(sockFd);
  //  return -1;
  //}

  int alivetime = 10;
  if (taosSetSockOpt(sockFd, SOL_TCP, TCP_KEEPIDLE, (void *)&alivetime, sizeof(alivetime)) < 0) {
    uError("fd:%d setsockopt SO_KEEPIDLE failed: %d (%s)", sockFd, errno, strerror(errno));
    taosCloseSocket(sockFd);
    return -1;
  }
...

`

**Comment by guanshengliang** [comment]
windows客户端还未正式发布，但是代码已经合并到master，预计明天发布2.0.1.1版本时，同时发布windows 64位客户端。

windows系统的不同编译环境下，各种系统函数有些差别，官方仅保证在vs2013环境上可以编译运行；其他编译环境，您可以自己调整少量代码，但这类问题不能算是bug的。

建议你使用官方发布的客户端，以免出现很多不易定位的问题。

**Comment by guanshengliang** [comment]
2.0.1.1版本已经发布，同时windows 64位客户端也能够下载了

**Comment by guanshengliang** [comment]
There is no response to this issue for a long time, and this issue has been fixed in 2.0.1.1 version, so close it
