### ISSUE TITLE
日志模块单独使用

### ISSUE THREAD

**Issue by jnxyatmjx** [taosdata/TDengine#315]
你们的日志模块写日志的吞吐量大约是多少，是否能用于短时间大量信息写入呢。

**Comment by guanshengliang** [comment]
没有对日志模块进行吞吐量的测试
TDengine的日志模块以AppendOnly方式写文本类型日志，从原理上可以做到磁盘写入速度的一半
日志模块有同步写和异步写两种策略，但并没有机制保证日志完整保存到日志文件中
