### ISSUE TITLE
请问支持.NET Core的客户端吗？

### ISSUE THREAD

**Issue by zfeihong** [taosdata/TDengine#3150]
目前只有java,c,c++的客户端，请问未来会支持.NET Core的客户端吗？

**Comment by maikebing** [comment]
.Net  的ADO.net 提供程序和  和  EF Core   在这里，  
https://github.com/maikebing/Maikebing.EntityFrameworkCore.Taos

**Comment by ttgzs** [comment]
> .Net 的ADO.net 提供程序和 和 EF Core 在这里，
> https://github.com/maikebing/Maikebing.EntityFrameworkCore.Taos

这个不是官方的，用起来有些担心。
之前项目中用过1.6x的，我们td2.0发布后，刚刚看了一些现在已经支持2.0了。

建议把这个开源项目纳入td的开源组织中。

**Comment by Aries-Lee1991** [comment]
> > .Net 的ADO.net 提供程序和 和 EF Core 在这里，
> > https://github.com/maikebing/Maikebing.EntityFrameworkCore.Taos
> 
> 这个不是官方的，用起来有些担心。
> 之前项目中用过1.6x的，我们td2.0发布后，刚刚看了一些现在已经支持2.0了。
> 
> 建议把这个开源项目纳入td的开源组织中。

@maikebing 是我们TDengine的Contributor

**Comment by maikebing** [comment]
@ttgzs  如果纳入到td的开源组织， 命名空间估计待改一下。 这个命名空间太个人色彩了。

**Comment by maikebing** [comment]
@ttgzs   虽然不是官方， 但是 目前唯一的 asp.net 提供程序和ef core 提供程序。 啧啧， 别无二选。

**Comment by maikebing** [comment]
Maikebing.Data.Taos  2.0.123 版本已经发布
