### ISSUE TITLE
docker如何部署集群？能否将集群命令参数配置化？可以不用手动运行命令?

### ISSUE THREAD

**Issue by Rebellioncry** [taosdata/TDengine#3151]
**Is your feature request related to a problem? Please describe.**
想在docker swarm模式下部署集群，但是看了集群的部署方式，要进入容器且进入taos cli才能执行命令，这对使用docker来说简直太麻烦

**Describe your desired behavior**
希望能出集群可配置化参数，可以使用docker compose file 一键启动

**Describe your solutions/suggestions if you've any**
类似EMQX等支持docker环境配置化启动集群

**Additional context**

**Comment by zfeihong** [comment]
同问，如何在k8s下运行集群？

**Comment by sangshuduo** [comment]
我们以后会通过 Blog 方式分享集群配置方法
