### ISSUE TITLE
Cause: java.sql.SQLException: TDengine Error: Unexpected generic error in RPC

### ISSUE THREAD

**Issue by kindomcat** [taosdata/TDengine#3155]
TDengine 版本使用的 2.0.1.0
driver版本使用的 2.0.3

TDengine 使用的官方docker镜像
客户端使用java编写的demo。
客户端程序能启动起来，但是客户端程序一执行sql就报错，报错如下：
Cause: java.sql.SQLException: TDengine Error: Unexpected generic error in RPC

**Comment by amen943** [comment]
如果你不是在docker中安装的server端，是能跑起来的，我实践过了。
如果是docker，好像还得在docker中装个客户端。

**Comment by kindomcat** [comment]
> 如果你不是在docker中安装的服务器端，是能跑起来的，我实践过了。
> 如果是docker，好像还得在docker中装个客户端。

java demo也是在docker中，我在docker中也装了客户端，java能链接上数据库链接，但是一进行查询操作就报错。我在1.6的版本中就不会发生这种问题。

**Comment by jtao1735** [comment]
> > 如果你不是在docker中安装的服务器端，是能跑起来的，我实践过了。
> > 如果是docker，好像还得在docker中装个客户端。
> 
> java demo也是在docker中，我在docker中也装了客户端，java能链接上数据库链接，但是一进行查询操作就报错。我在1.6的版本中就不会发生这种问题。

能否提供一下日志，一般在/var/log/taos这个目录

**Comment by kindomcat** [comment]
> > > 如果你不是在docker中安装的服务器端，是能跑起来的，我实践过了。
> > > 如果是docker，好像还得在docker中装个客户端。
> > 
> > 
> > java demo也是在docker中，我在docker中也装了客户端，java能链接上数据库链接，但是一进行查询操作就报错。我在1.6的版本中就不会发生这种问题。
> 
> 能否提供一下日志，一般在/ var / log / taos这个目录
这是taoslog0.0的日志
08/20 06:03:18.166916 0x7f8e73d8e740 UTL localEp is: b824a472b87c:6030
08/20 06:03:18.167566 0x7f8e73d8e740 UTL timezone not configured, set to system default: (UTC, +0000)
08/20 06:03:18.167610 0x7f8e73d8e740 UTL ERROR locale not configured, set to system default:en_US.UTF-8
08/20 06:03:18.167616 0x7f8e73d8e740 UTL WARN charset not configured, set to system default:UTF-8
08/20 06:03:18.167639 0x7f8e73d8e740 UTL    taos config & system info:
08/20 06:03:18.167650 0x7f8e73d8e740 UTL ==================================
08/20 06:03:18.167653 0x7f8e73d8e740 UTL  firstEp:                b824a472b87c:6030 
08/20 06:03:18.167654 0x7f8e73d8e740 UTL  secondEp:               b824a472b87c:6030 
08/20 06:03:18.167656 0x7f8e73d8e740 UTL  fqdn:                   b824a472b87c 
08/20 06:03:18.167657 0x7f8e73d8e740 UTL  serverPort:             6030 
08/20 06:03:18.167658 0x7f8e73d8e740 UTL  configDir:              /etc/taos 
08/20 06:03:18.167659 0x7f8e73d8e740 UTL  logDir:                 /var/log/taos 
08/20 06:03:18.167660 0x7f8e73d8e740 UTL  scriptDir:              /etc/taos 
08/20 06:03:18.167661 0x7f8e73d8e740 UTL  arbitrator:              
08/20 06:03:18.167662 0x7f8e73d8e740 UTL  numOfThreadsPerCore:    1.000000 
08/20 06:03:18.167678 0x7f8e73d8e740 UTL  rpcTimer:               1000(ms)
08/20 06:03:18.167681 0x7f8e73d8e740 UTL  rpcMaxTime:             600(s)
08/20 06:03:18.167682 0x7f8e73d8e740 UTL  shellActivityTimer:     3(s)
08/20 06:03:18.167683 0x7f8e73d8e740 UTL  tableMetaKeepTimer:     7200(s)
08/20 06:03:18.167685 0x7f8e73d8e740 UTL  compressMsgSize:        -1 
08/20 06:03:18.167686 0x7f8e73d8e740 UTL  maxSQLLength:           65480(byte)
08/20 06:03:18.167686 0x7f8e73d8e740 UTL  maxNumOfOrderedRes:     100000 
08/20 06:03:18.167687 0x7f8e73d8e740 UTL  timezone:                (UTC, +0000) 
08/20 06:03:18.167688 0x7f8e73d8e740 UTL  locale:                 en_US.UTF-8 
08/20 06:03:18.167689 0x7f8e73d8e740 UTL  charset:                UTF-8 
08/20 06:03:18.167689 0x7f8e73d8e740 UTL  numOfLogLines:          10000000 
08/20 06:03:18.167690 0x7f8e73d8e740 UTL  asyncLog:               1 
08/20 06:03:18.167691 0x7f8e73d8e740 UTL  debugFlag:              0 
08/20 06:03:18.167692 0x7f8e73d8e740 UTL  rpcDebugFlag:           131 
08/20 06:03:18.167693 0x7f8e73d8e740 UTL  tmrDebugFlag:           131 
08/20 06:03:18.167694 0x7f8e73d8e740 UTL  cDebugFlag:             131 
08/20 06:03:18.167695 0x7f8e73d8e740 UTL  jniDebugFlag:           131 
08/20 06:03:18.167696 0x7f8e73d8e740 UTL  odbcDebugFlag:          131 
08/20 06:03:18.167697 0x7f8e73d8e740 UTL  uDebugFlag:             131 
08/20 06:03:18.167698 0x7f8e73d8e740 UTL  qDebugFlag:             131 
08/20 06:03:18.167699 0x7f8e73d8e740 UTL  tsdbDebugFlag:          131 
08/20 06:03:18.167701 0x7f8e73d8e740 UTL  gitinfo:                8df8b7d9930342dd34ba13df160a7d538fad7bc7 
08/20 06:03:18.167702 0x7f8e73d8e740 UTL  gitinfoOfInternal:       
08/20 06:03:18.167704 0x7f8e73d8e740 UTL  buildinfo:              Built by root at 2020-08-03 17:21 
08/20 06:03:18.167705 0x7f8e73d8e740 UTL  version:                2.0.0.0 
08/20 06:03:18.167707 0x7f8e73d8e740 UTL  maxBinaryDisplayWidth:  30 
08/20 06:03:18.167709 0x7f8e73d8e740 UTL  os pageSize:            4096(KB)
08/20 06:03:18.167711 0x7f8e73d8e740 UTL  os openMax:             1048576
08/20 06:03:18.167713 0x7f8e73d8e740 UTL  os streamMax:           16
08/20 06:03:18.167713 0x7f8e73d8e740 UTL  os numOfCores:          2
08/20 06:03:18.167714 0x7f8e73d8e740 UTL  os totalDisk:           0.000000(GB)
08/20 06:03:18.167715 0x7f8e73d8e740 UTL  os totalMemory:         1824(MB)
08/20 06:03:18.167717 0x7f8e73d8e740 UTL  os sysname:             Linux
08/20 06:03:18.167718 0x7f8e73d8e740 UTL  os nodename:            b824a472b87c
08/20 06:03:18.167718 0x7f8e73d8e740 UTL  os release:             3.10.0-327.el7.x86_64
08/20 06:03:18.167719 0x7f8e73d8e740 UTL  os version:             #1 SMP Thu Nov 19 22:10:57 UTC 2015
08/20 06:03:18.167719 0x7f8e73d8e740 UTL  os machine:             x86_64
08/20 06:03:18.167720 0x7f8e73d8e740 UTL ==================================
08/20 06:04:08.245562 0x7f8e6e4ce700 UTL cache:tableMeta will be cleaned up

------------------------------------------------------
这是taosdlog.0的日志
08/21 01:41:12.547703 0x7f86e7ff7700 DND msg:status will be processed in mpeer queue
08/21 01:41:13.552578 0x7f86e7ff7700 DND msg:status will be processed in mpeer queue
08/21 01:41:14.557412 0x7f86e7ff7700 DND msg:status will be processed in mpeer queue
08/21 01:41:15.561972 0x7f86e7ff7700 DND msg:status will be processed in mpeer queue
08/21 01:41:16.566917 0x7f86e7ff7700 DND msg:status will be processed in mpeer queue

我发起了一起请求，但是发现这两个日志文件都没有增加。

**Comment by 379547990** [comment]
> driver版本使用的 2.0.4时，Client在服务器上跑正常，在Windows下报同样错误。
> 不该Server端，只改Windows的C:\Windows\System32\drivers\etc\hosts，增加一行
> XX.XX.XX.XX RemoteServerName
> XX.XX.XX.XX --服务器地址
> RemoteServerName --服务器名称，可以在服务器上执行hostnamectl获取
> 不要改Server端。估计是引入集群功能没完善有关。集群建议不要用名称，一般考虑用IP组

解决了我的问题！
