### ISSUE TITLE
通过RESTful Connector查询数据时，数据过大时仅返回一个子表的数据

### ISSUE THREAD

**Issue by wobaa** [taosdata/TDengine#3163]
同样的sql语句
在服务端的命令行执行，返回行数为137275条，是包含了多个子表的数据；

通过RESTful Connector查询数据时，仅返回第一个子表的数据条数，8747条；

想知道这是为什么？查阅文档，RESTful Connector的查询返回集条数默认是10240条，那也应该返回10240条吧？是TDengine内部做了处理吗？

**Comment by Shawshank-Smile** [comment]
请把软件版本，所进行的操作和日志贴一下。

**Comment by sangshuduo** [comment]
No more information, close it.
