### ISSUE TITLE
count() result is different to query result

### ISSUE THREAD

**Issue by wobaa** [taosdata/TDengine#3165]
先查询的count数量，结果为16，如下图：

![1](https://user-images.githubusercontent.com/30998643/90750715-c9509880-e307-11ea-9635-1291e7c81d4f.png)

然后查询数据，结果却仅有5条返回，如下图：

![2](https://user-images.githubusercontent.com/30998643/90750834-f604b000-e307-11ea-87f1-72aff9bdf375.png)

想请问这为什么？？

**Comment by frankhepeng** [comment]
在cli界面用select count(*) 查询也遇到同样的问题。count()多次数据越来越少。

**Comment by Shawshank-Smile** [comment]
请问软件版本？

**Comment by wobaa** [comment]
服务器上装的TDengine版本是2.0.0

**Comment by yihaoDeng** [comment]
> 服务器taos版本如下图，不知道是否是您所指的：
> ![taos_version](https://user-images.githubusercontent.com/30998643/90952077-304e8880-e493-11ea-871d-3eeb6cdbe172.png)
> 
> 客户端就是http访问的；insert语句也很长，我只能展示如下代码来说明insert语句的拼接逻辑。
> ![query_sql](https://user-images.githubusercontent.com/30998643/90952243-9daee900-e494-11ea-8ad2-11f7c8810756.png)

我在目前的最新上构造了和你非常类似的一个场景， 没有遇到你说的说这个问题。

**Comment by wobaa** [comment]
但在我部署的版本上就是出现了这个现象，所以我需要更新到最新的2.0.1.1版本再进行尝试吗？

**Comment by jin522** [comment]
count（*） 和 count(某一字段名)的结果也不一样，所以count的逻辑是什么？是统计行数吗？包括副本数吗？

**Comment by frankhepeng** [comment]
count(*)统计行数。
发送


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taosdata/TDengine"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月25日(星期二) 中午1:58
收件人:&nbsp;"taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送:&nbsp;"大浪淘沙!"<1733945@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [taosdata/TDengine] 查询count得到的数据条数后，单独查询数据获得的条数不一致 (#3165)





 
count（*） 和 count(某一字段名)的结果也不一样，所以count的逻辑是什么？是统计行数吗？包括副本数吗？

**Comment by hjxilinx** [comment]
> count（*） 和 count(某一字段名)的结果也不一样，所以count的逻辑是什么？是统计行数吗？包括副本数吗？

count(*)统计该表行数，count(column)统计某一列的数量（忽略 NULL），所以如果您的表中该列有 NULL 值，那么结果可能会不一样，但是如果没有 NULL 值，结果应该是一样的。

**Comment by hjxilinx** [comment]
如果需要，我们可以远程协助的方式到您的环境下检查一下。

**Comment by jin522** [comment]
taos> select * from train_signal limit 5;
           ts            |    p_id     |           value           |   train_id   |    v_id     |
=================================================================================================
 2020-09-01 09:10:21.685 |         109 |               0.000000000 | NLCJ_T2      |        4999 |
 2020-09-01 09:10:23.256 |         109 |               0.000000000 | NLCJ_T2      |        4999 |
 2020-09-01 09:10:23.376 |         109 |               0.000000000 | NLCJ_T2      |        4999 |
 2020-09-01 09:10:23.492 |         109 |               0.000000000 | NLCJ_T2      |        4999 |
 2020-09-01 09:10:23.609 |         109 |               0.000000000 | NLCJ_T2      |        4999 |
Query OK, 5 row(s) in set (0.011095s)

taos> select count(*) from train_signal;
       count(*)        |
========================
              20000000 |
Query OK, 1 row(s) in set (0.421876s)

taos> select count(ts) from train_signal;
       count(ts)       |
========================
              20000000 |
Query OK, 1 row(s) in set (0.340223s)

taos> select count(p_id) from train_signal;
      count(p_id)      |
========================
              20000000 |
Query OK, 1 row(s) in set (0.389337s)

taos> select count(value) from train_signal;
     count(value)      |
========================
              20000000 |
Query OK, 1 row(s) in set (0.396967s)

taos> select count(train_id) from train_signal;
    count(train_id)    |
========================
                 20000 |
Query OK, 1 row(s) in set (0.023901s)

taos> select count(v_id) from train_signal;
      count(v_id)      |
========================
                 20000 |
Query OK, 1 row(s) in set (0.022883s)

**Comment by jin522** [comment]
如上，总共20000000条数据，count（v_id），count(train_id)统计的数字为20000，数据中也没有null值

**Comment by wobaa** [comment]
> 如上，总共20000000条数据，count（v_id），count(train_id)统计的数字为20000，数据中也没有null值

他们底层实现应该是自动去重了，你看一下你的数据是否v_id和train_id是不唯一的

**Comment by jin522** [comment]
> > 如上，总共20000000条数据，count（v_id），count(train_id)统计的数字为20000，数据中也没有null值
> 
> 他们底层实现应该是自动去重了，你看一下你的数据是否v_id和train_id是不唯一的

应该没有distinct，v_id是0到9999连续不重复，去重后应该是10000，train_id去重后应该为2

**Comment by wobaa** [comment]
那我也不知道了，用下来就感觉SQL语句的实现不对劲，数据获取结果不稳定，同样的语句可能得出不同的结果

**Comment by yihaoDeng** [comment]
应该是稳定的， 我们这里做了大量持续的测试 @wobaa

**Comment by yihaoDeng** [comment]
新版本有这个问题吗， @jin522
