### ISSUE TITLE
Nodejs 试了试没有成功, 不知道问题在哪.

### ISSUE THREAD

**Issue by Jimmysh** [taosdata/TDengine#3167]
**Bug Description**

数据库是在 docker 里跑的. 本机执行 node 代码. 提示错误. node 版本 8, 10 都不行.
RESTful API 跟 node connector 性能差的多吗?

**To Reproduce**
node a.js
```js
// a.js
const taos = require("td2.0-connector");
var conn = taos.connect({
  host: "127.0.0.1",
  user: "root",
  password: "taosdata",
  config: "/etc/taos",
  port: 0,
});
var cursor = conn.cursor();
var query = cursor.query("show databases;");
var promise = query.execute();
promise.then(function(result) {
  result.pretty(); 
});

```

**Screenshots**
![截屏2020-08-20 下午5 37 16](https://user-images.githubusercontent.com/230652/90754159-23ebf380-e30c-11ea-8fcf-eece005453f7.png)
![截屏2020-08-20 下午5 37 29](https://user-images.githubusercontent.com/230652/90754168-28181100-e30c-11ea-9278-cdc95bac79a6.png)

**Environment (please complete the following information):**
 - OS: MacOS 10.15.6
 - TDengine Version 2.0.0.4

**Comment by sangshuduo** [comment]
libtaos.dylib image not found

暂时不支持 MacOS
