### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by Mrgongm** [taosdata/TDengine#3169]
**开发环境：**
①、TDengine-server-2.0.1.1    位于 “1号ubuntu主机”  Ubuntu18.04系统。
②、TDengine-client-1.6.6.1     位于 “2号windows主机”  Windows系统。
③、java开发项目，maven工程,使用taos-jdbcdriver-**2.0.3**.jar

**过程：**
1、在Windows系统，在连接TDengine时出现以下错误：

`A fatal error has been detected by the Java Runtime Environment:`
 `SIGSEGV (0xb) at pc=0x00007f2b779e78a4, pid=13088, tid=0x00007f2b763eb700`
 `JRE version: Java(TM) SE Runtime Environment (8.0_251-b08) (build 1.8.0_251-b08)`
 `Java VM: Java HotSpot(TM) 64-Bit Server VM (25.251-b08 mixed mode linux-amd64 compressed oops)`
 `Problematic frame:`
 `C  [libbsd.so.0+0x68a4]  MD5Pad+0x24`
` Core dump written. Default location: /home/beiyang/NetbeansProjects/SVN_HELAN_2.0/core or core.13088`
 `An error report file with more information is saved as:`
`/home/beiyang/NetbeansProjects/SVN_HELAN_2.0/hs_err_pid13088.log`
 `If you would like to submit a bug report, please visit:`
` http://bugreport.java.com/bugreport/crash.jsp`
 `The crash happened outside the Java Virtual Machine in native code.`
 `See problematic frame for where to report the bug.`
![20200820183033](https://user-images.githubusercontent.com/42021493/90759622-446b7c00-e313-11ea-9ebe-b8c9182c6859.png)
将工程代码拷贝至“1号ubuntu主机”，连接TDengine出现同样错误。

**出现转机：**
1、2020年8月20日发布TDengine-client-2.0.1.1后，更换了“2号windows主机”的客户端版本由1.6.6.1换成2.0.1.1，然后运行项目，发现连接成功了。
2、将工程代码拷贝至“1号ubutnu主机”，连接TDengine问题又出现了。

生成日志文件：
[hs_err_pid13088.log](https://github.com/taosdata/TDengine/files/5102298/hs_err_pid13088.log)

请问 是否是因为安装TDengine-server-2.0.1.1时 自带的libtaos.so文件版本问题导致？

**Comment by sangshuduo** [comment]
请确保旧版本删除后重现安装新版本

**Comment by hjxilinx** [comment]
您升级后1号机器的 libtaos.so 的版本和 client 的 libtaos.so 的版本是一致的对吧？

**Comment by Mrgongm** [comment]
> 您升级后1号机器的libtaos.so的版本和客户端的libtaos.so的版本是一致的对吧？

使用taos-jdbcdriver- 2.0.3 .jar连接1号机器，libtaos.so不是安装TDengine-server时自带的吗。
