### ISSUE TITLE
与Grafana集成后添加Variables无法使用的问题

### ISSUE THREAD

**Issue by skcai** [taosdata/TDengine#317]
我在Grafana上添加了Variables，但是在Query里无法使用，如：
Variables：$short_id
Query: select ts, op from device.tb_[[short_id]] where ts >= $from and ts <= $to
GENERATE SQL: select ts, op from device.tb_[[short_id]] where ts >= '2019-08-09T03:35:48.857Z' and ts <= '2019-08-09T09:35:48.857Z'

请问要如何给Query添加Variable呢？

**Comment by guanshengliang** [comment]
目前TDengine的Grafana插件还不支持变量
TDengine团队会将此问题添加到研发计划中

**Comment by guanshengliang** [comment]
此问题已经解决，代码在develop分支上，您可以下载使用

**Comment by skcai** [comment]
谢谢！已经用上。TDengine 真的很快，极大的提高了我们设备统计图表的显示速度。
