### ISSUE TITLE
how to use mutiple group by fileds? 

### ISSUE THREAD

**Issue by frankhepeng** [taosdata/TDengine#3172]
如何使用多字段分组？goup by filed1,filed2  ?
![image](https://user-images.githubusercontent.com/3974652/90846380-93102900-e39a-11ea-82f7-56847694cb2d.png)

**Comment by yihaoDeng** [comment]
tag 列可以支持

**Comment by korimas** [comment]
@yihaoDeng 有计划支持吗？
