### ISSUE TITLE
JDBC 2.0.3 error: java.sql.SQLException: TDengine Error: Unable to establish connection

### ISSUE THREAD

**Issue by PascalMing** [taosdata/TDengine#3176]
服务端Centos7 + TDengine-server-2.0.1.1-Linux-x64.rpm
Cient TDengine-client-2.0.1.1-Windows-x64.exe，Win10
使用缺省安装和配置
采用Rest API接口，从Windows访问Server的6041端口，操作正常
从Windows Telnet Server的6030端口，可以连接，排除防火墙问题。没有使用代理
使用JAVA的2.0.3 JDBC操作，执行“CREATE DATABASE IF NOT EXISTS DevTest”等失败。
使用代码：
    public void jdbcDemoUpdate(Connection con, String sql) throws Exception
    {
        Statement stmt = null;
        try
        {
            stmt = con.createStatement(); //执行后，connecter的taos值正常
            stmt.executeUpdate(sql); //执行后报错，java.sql.SQLException: TDengine Error: Unable to establish connection
        }catch(Exception ex)
        {
            System.out.println(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()) + " jdbcDemoUpdate sql=" + sql+" Ex="+ex.getMessage());
        }finally {
            try {
                    if (stmt != null){
                    stmt.close();
                }
            }catch (Exception e){
                e.printStackTrace();
            }
        }
    }
Windows下出错信息如下，过程见代码注释说明：
java.sql.SQLException: TDengine Error: Unable to establish connection

打包到服务器直接执行，报错：
2020-08-21 13:58:19 jdbcDemoUpdate sql=CREATE DATABASE IF NOT EXISTS DevTest Ex=The executed SQL is not a DML or a DDL

**Comment by liujianguo122** [comment]
遇到这错的还不少啊

**Comment by liu18831337077** [comment]
我连不上服务器的问题解决了，我理解的原因是taos请求到mnode，mnode返回了它存储的dnode信息，然后taos得到了这个节点信息，但是很不幸里面的是存储的IP为hostname（即End Point）然后客户端的taos会再次发起请求，由于客户端并不知道服务器的hostname，于是乎就会出现连接错误问题，特征就是服务器的本机可以taos通，跨服务器就不可以，可以将hostname设置为ip（但是我只使用了yum安装包可以，tar包并不会识别出来，使用show dnodes命令查看的），或者配置客户端host的映射。

**Comment by maikebing** [comment]
参考 #3155

**Comment by liujianguo122** [comment]
java.sql.SQLException: The executed SQL is not a DML or a DDL
Failed to execute query: 
	at com.taosdata.jdbc.TSDBStatement.executeUpdate(TSDBStatement.java:82)
	at TSDBSyncSample.doExecuteQuery(TSDBSyncSample.java:158)
	at TSDBSyncSample.main(TSDBSyncSample.java:46)

修改hosts之后执行sql
![6e4f8a5c0ec04ca3baee6a7a9bf4af7a](https://user-images.githubusercontent.com/67721622/91114470-90734380-e6ba-11ea-8433-eddedbc36bc9.jpg)
出现新的错误：The executed SQL is not a DML or a DDL

**Comment by liujianguo122** [comment]
java.sql.SQLException: The executed SQL is not a DML or a DDL
Failed to execute query: 
	at com.taosdata.jdbc.TSDBStatement.executeUpdate(TSDBStatement.java:82)
	at TSDBSyncSample.doExecuteQuery(TSDBSyncSample.java:158)
	at TSDBSyncSample.main(TSDBSyncSample.java:46)

修改hosts之后执行sql
![6e4f8a5c0ec04ca3baee6a7a9bf4af7a](https://user-images.githubusercontent.com/67721622/91114470-90734380-e6ba-11ea-8433-eddedbc36bc9.jpg)
出现新的错误：The executed SQL is not a DML or a DDL

**Comment by liujianguo122** [comment]
修改客户端hosts之后，执行sql出现新的错误：The executed SQL is not a DML or a DDL
java.sql.SQLException: The executed SQL is not a DML or a DDL
Failed to execute query: 
	at com.taosdata.jdbc.TSDBStatement.executeUpdate(TSDBStatement.java:82)
	at TSDBSyncSample.doExecuteQuery(TSDBSyncSample.java:158)
	at TSDBSyncSample.main(TSDBSyncSample.java:46)

**Comment by liu18831337077** [comment]
这个问题还没有遇到。

**Comment by zyyang-taosdata** [comment]
用taos-jdbcdriver-2.0.4
