### ISSUE TITLE
TDengine 的时间精度只能精确到ms？

### ISSUE THREAD

**Issue by wxlevel** [taosdata/TDengine#3178]
TDengine 的时间精度只能精确到ms，对于同一ms内的数据 是直接丢弃掉的吗？
我通过测试往tdengine插入1w条数据，使用TDengine默认的时间戳，结果发现只插入了6000多条左右的数据，丢掉了将近4000条数据。我是用多线程来跑的。

TDengine 能做到不丢数据吗？

**Comment by sangshuduo** [comment]
可以配置成微秒的，参见官方文档：

https://www.taosdata.com/cn/documentation/administrator/#%E6%9C%8D%E5%8A%A1%E7%AB%AF%E9%85%8D%E7%BD%AE
