### ISSUE TITLE
float类型精度问题

### ISSUE THREAD

**Issue by wsf1990** [taosdata/TDengine#318]
定义了两个float类型的字段，insert 的时候值分别为：`1678.258423,10.1948`，但是取出来却变成了 `1678.2584228515625,10.19480037689209`。这是什么原因呢？

两个字段定义如下：
```
value2                                                          |FLOAT           |          4|        |
value1                                                          |FLOAT           |          4|        |
```

**Comment by guanshengliang** [comment]
基本类型的浮点数精度在任何编程语言中均相同
1. `float`用`4`字节存储，有效数字位为`6–7`位
2. `double`用`8`字节存储，有效数字位为`15–16`位

TDengine未对浮点数据做特殊处理，所以同样无法保证有效数字之后的精度

如需要确保浮点数据精度，可将浮点数放大，存储成int或者bigint类型，例如
`1678.258423`放大`10^6`倍，表示为`1678258423`
`10.1948`放大`10^6`倍，表示为`10194800`
