### ISSUE TITLE
cannot insert data to database

### ISSUE THREAD

**Issue by frankhepeng** [taosdata/TDengine#3187]
程序运气一段时间后，发现数据不能插入到数据库。
![无标题1](https://user-images.githubusercontent.com/3974652/90884593-a1823300-e3e2-11ea-83c0-e943c71193f1.png)

**Comment by sangshuduo** [comment]
请提供版本信息和重现步骤

**Comment by frankhepeng** [comment]
就是taos2.0.步骤开始已经发了



---原始邮件---
发件人: "Shuduo Sang"<notifications@github.com&gt;
发送时间: 2020年8月25日(周二) 中午12:31
收件人: "taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"frankhepeng"<1733945@qq.com&gt;;
主题: Re: [taosdata/TDengine] 数据不能插入到数据库。 (#3187)




 
请提供版本信息和重现步骤

**Comment by frankhepeng** [comment]
![捕获](https://user-images.githubusercontent.com/3974652/91268418-e245c780-e7a7-11ea-8f2d-7d4fe1d34c74.PNG)
插入数据显示成功，但是查询有异常。
![捕获1](https://user-images.githubusercontent.com/3974652/91268467-fb4e7880-e7a7-11ea-8291-b3bfe812446b.PNG)
