### ISSUE TITLE
开发机Mac下JDBC无法连接到服务器

### ISSUE THREAD

**Issue by javamonkey** [taosdata/TDengine#3191]
报错是
Exception in thread "main" java.lang.UnsatisfiedLinkError: no taos in java.library.path

因为我是mac，我尝试copy到/usr/lib, 但mac有限制，无法完成，我就copy到 /usr/local/libm 但依然报错

有什么办法能让mac通过jdbc下连接到taos 服务器？

**Comment by zyyang-taosdata** [comment]
[目前，jdbc去连接TDengine实例，需要依赖本地动态库（libtaos.so）的，你把linux上编译出来的动态库（.so文件）拷贝到mac上，当然是没用的。在文档：[快速上手](https://www.taosdata.com/cn/getting-started/#%E5%BF%AB%E6%8D%B7%E5%AE%89%E8%A3%85)
中，有描述：”如果应用需要在Windows或Mac上运行，目前只能使用TDengine的RESTful接口连接服务器。“
您也可以考虑下载TDengine的源码，自己在mac上编译。或者，将java程序打成jar包，在linux或docker环境下运行。

**Comment by sangshuduo** [comment]
暂时官方还不支持 MAC 环境下编译

**Comment by MelodyI** [comment]
问题已关闭，什么时候能解决

**Comment by mushanzi1216** [comment]
所以还是没解决？

**Comment by sangshuduo** [comment]
@mushanzi1216 如果有付费客户我们可以提高优先级
