### ISSUE TITLE
JDBC_windows

### ISSUE THREAD

**Issue by cavern1628** [taosdata/TDengine#32]
windows JDBC 不能用，没有依赖驱动

**Comment by johnnyhou327** [comment]
@cavern1628 Windows的客户端目前还暂时没有支持，请先试用Linux上的客户端。后面我们会更新windows客户端支持。

**Comment by niezl** [comment]
依赖包没法下载呀

**Comment by guanshengliang** [comment]
我们会在7月27日提交windows客户端代码

**Comment by zouchengli** [comment]
> @cavern1628 Windows的客户端目前还暂时没有支持，请先试用Linux上的客户端。后面我们会更新windows客户端支持。


> 我们会在7月27日提交windows客户端代码

今天在csdn博客上看到文章果断跑来试试这个数据库引擎。linux上面随便跑了跑，感觉还不错。期待windows客户端和mac客户端来进行开发调试。

**Comment by guanshengliang** [comment]
Windows的dll已经可以在官网下载
