### ISSUE TITLE
在taosdata官网上，下载了最新的TDengine RPM package (1.5M)安装包，安装时提示没有/usr/local/taos/connector/taos-jdbcdriver-1.0.1-dist.jar。为什么没有jdbc的驱动包了？不支持Java连接了？

### ISSUE THREAD

**Issue by xiaoLaia** [taosdata/TDengine#320]

**Comment by plum-lihui** [comment]
![image](https://user-images.githubusercontent.com/52318143/62815929-6e139400-bb52-11e9-93b1-57b9827fcf37.png)

**Comment by plum-lihui** [comment]
![rpm](https://user-images.githubusercontent.com/52318143/62815970-fdb94280-bb52-11e9-9260-36c36c687070.png)

**Comment by plum-lihui** [comment]
@xiaoLaia   上图是我在环境中安装的截图，安装后，是有jdbc的驱动包的。您能把安装时的情况，以及安装后目录/usr/local/taos/connector内容的截图发送上来看看吗？

**Comment by xiaoLaia** [comment]
@plum-lihui 
![PK3LP5`J}_701H4BGF0_R58](https://user-images.githubusercontent.com/35595939/62816058-3f96b880-bb54-11e9-943a-27fe18016746.png)

**Comment by xiaoLaia** [comment]
@plum-lihui 
![9%VMDMG0}(F0HW` @N45HZF](https://user-images.githubusercontent.com/35595939/62816071-7d93dc80-bb54-11e9-9599-cdd81fc1e509.png)

**Comment by plum-lihui** [comment]
您先用这个命令： rpm -e --noscripts tdengine  卸载了，再重新安装1.6.1.5版本。@xiaoLaia

**Comment by xiaoLaia** [comment]
@plum-lihui 是的，我再安装新版本前，已经rpm -e tdengine-1.6.1.2-3.el7.x86_64.rpm，再安装tdengine-1.6.1.5-3.el7.x86_64.rpm得。
![aea45136264f864c6055e806fffc2a6](https://user-images.githubusercontent.com/35595939/62816190-03645780-bb56-11e9-8c25-86f3126c3e84.png)

**Comment by plum-lihui** [comment]
看起来像这个下载的安装包有问题，从大小来看就不对，应该有1.7M多点，您的才1.3M多，请重新下载一下吧。
![无标题](https://user-images.githubusercontent.com/52318143/62816186-f5163b80-bb55-11e9-95c1-7e4f7359d411.png)

**Comment by xiaoLaia** [comment]
@plum-lihui 好了安装成功了，谢谢解答，非常感谢，我没注意到安装包的完整性。
