### ISSUE TITLE
http返回结果和服务器返回结果不同

### ISSUE THREAD

**Issue by liujinsheng** [taosdata/TDengine#3203]
select count(ts) as total_count , max(total_mileage) as total_max , min(total_mileage) as total_min  , max(continue_mileage) as continue_max, min(continue_mileage) as continue_min , first(ts)  from db.s_gps  where  ts>'1598112000000' and ts < '1598198399999' group by vid ,client_code , pid ,eid ,oid ,admdivcode ,industry_id;

linux 返回结果：Query OK, 11154 row(s) in set (5.928493s)
http返回结果："rows": 10240

**Comment by lengmao** [comment]
我也遇到了同样的问题，直接查库有10W条数据，jdbc请求返回10240条
