### ISSUE TITLE
java.sql.SQLException: TDengine Error: Unexpected generic error in RPC

### ISSUE THREAD

**Issue by t1567954** [taosdata/TDengine#3205]
配置为：driver-class-name: com.taosdata.jdbc.TSDBDriver
    url: jdbc:TAOS://192.168.8.244:6030/
    data-username: root
    data-password: taosdata
错误为
### SQL: create database if not exists test;

**Comment by maikebing** [comment]
需要使用 域名或者主机名登录  不能用IP

**Comment by maikebing** [comment]
参考 3155
