### ISSUE TITLE
python版cursor.executemany 插入数据失败

### ISSUE THREAD

**Issue by byronsong** [taosdata/TDengine#321]
部分代码如下：

    execute_params = []
    # stmt = "insert into get_item_log_08_18 values (%s, %d, %d, %d, %s, %d, %d, %d, %d, %s, %d, %d, %d, %s, %d, %d, %d, %s, %d, %d, %d)"
    stmt = "insert into get_item_log_08_18 values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"

    for i in range(count):
        try:
           player = player_list[random.randint(0, player_len - 1)]
           item = item_list[random.randint(0, item_len - 1)]
           param = param_list[random.randint(0, param_len - 1)]
           num = random.randint(1, 9999)

           values = (start_time, i, log_type, start_ms + i, server_name, server_id, platform_id, player.account_id, player.role_id, player.role_name, player.level, player.vip, random.randint(1, 99), param,
                item.type, item.item_id, item.item_def_id, item.item_name, num, item.curr_number - num, start_ms + i)
           execute_params.append(values)
        except Exception as err:
            conn.close()
            raise(err)
        start_time += time_interval
    print("len ", len(execute_params))
    c1.executemany(stmt, execute_params)
    conn.commit()

之前用官网的execute入库成功，没有问题。
我想测试下executemany。结果发现插入失败。

taos> select count(*) from db.get_item_log_08_18;
Query OK, 0 row(s) in set (0.000753s)

麻烦帮忙看下，哪里调用不对。
谢谢。

**Comment by guanshengliang** [comment]
产可以把执行的SQL语句贴出来，如果语法正确，那么可能原因
1. 单条语句要小于64K
2. 在使用insert语句情况下，时间戳需要单调增长
3. 如果不能保证单调增长，需要使用import

**Comment by byronsong** [comment]
2,3 肯定是没有问题
因为我单条入库，走c1.execute(sqlString)，100W条记录都是成功的。

1. 单条语句要小于64K，这一条不是很理解？是指我insert数据过多吗？那我把for循环数据量降低了。也还是不行。

真正执行的sql，是这样的：
insert into get_item_log_08_08 values ('2019-07-01 00:00:00', 0, 1, 1561939200000, '宝可萌1服', 1, 1, 26765, 10918964953090, '浮夸', 103, 8, 63, '{"defId":8,"paramName":"探索副本采集奖励1"}', 13, 10910401167365, 10034, '幸运宝箱', 2501, 97498, 15619392000
00);
之前是走c1.execute(sqlString)，没有问题。100W条，都正常入库。

刚刚我把for i in range(count):的count改为1，也还是没有任何数据入库。

**Comment by byronsong** [comment]
sql语法我觉得应该也没有问题。
同样的sql，我同样是executemany
mysql入库成功。100条准确插入。
mysql> use db;
Database changed
mysql> select count(*) from get_item_log_08_18;
+----------+
| count(*) |
+----------+
|      100 |
+----------+
1 row in set (0.01 sec)

**Comment by guanshengliang** [comment]
周一再仔细分析，请稍等

**Comment by byronsong** [comment]
好的。谢谢。
如果你们测试没有重现的话。麻烦把你们的example贴一下。
operation command sql 中，values后面，我测试过mysql example的 %s，以及 sqllite example的 ？

**Comment by fangpanpan** [comment]
我发现executemany的代码里有bug，我们周一会去解决这个bug，等解决好了以后我会再告诉您。

现在如果您想进行批量插入的话，execute也是可以的。用法和通常的execute(sql_command)相似，里面sql_command 是“insert into table_name values (...)(...)(...)”这种形式。如您的例子，

stmt = "insert into get_item_log_08_18 values ”
for i in range(count):
    try:
       player = player_list[random.randint(0, player_len - 1)]
       item = item_list[random.randint(0, item_len - 1)]
       param = param_list[random.randint(0, param_len - 1)]
       num = random.randint(1, 9999)

       values = (start_time, i, log_type, start_ms + i, server_name, server_id, platform_id, player.account_id, player.role_id, player.role_name, player.level, player.vip, random.randint(1, 99), param, item.type, item.item_id, item.item_def_id, item.item_name, num, item.curr_number - num, start_ms + i)
       rtmt_append =  "( %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)" % (values)
       rtmt += rtmt_append
    except Exception as err:
        conn.close()
        raise(err)
    start_time += time_interval
c1.execute(stmt)
conn.commit()

**Comment by byronsong** [comment]
收到。
谢谢。
我按照你们提供的方法改一下测试代码看看。

**Comment by byronsong** [comment]
测试结果OK。 @fangpanpan 推荐的方法是可行的。
我在做与mysql批量插入对比测试。

测试发现：
TDengine引擎，一共10W条insert。
1条value，execute一次，耗时19.361秒。
100条value，execute一次，耗时41.85秒。
（测试语言：Python2.7）

TDengine不推荐批量insert吗？

**Comment by fangpanpan** [comment]
TDengine推荐批量insert, 这样可以节省网络传输时间。您可以参考这篇博文[https://www.taosdata.com/blog/2019/07/19/tdengine%e4%b8%8einfluxdb%e5%af%b9%e6%af%94%e6%b5%8b%e8%af%95/](url) 图一。 
Python的insert速度确实会慢一些，一方面python语言本身就是比较慢的，另一方面，python客户端使用的C的libtaos.so的动态库，python调用c接口也会耗费一些时间。

**Comment by byronsong** [comment]
@fangpanpan 你推荐的博文我之前看过了。
只可惜我C不熟，只能读懂C语言，没法用来测试。
所以用的Python写测试代码。
我记得issue里也有人提过因为跟c语言相比，Python的fetchall慢得多的多，因为Python创建对象比较耗时。所以我也担心因为Python语言，影响到测试结果的准确性。但是，我做的是insert测试，不是fetch测试，应该还好吧？

在跟mysql对比之前，我确实也认为就是Python的问题。
但是跟MysqlDb对比了之后，我不太确认如此了。
mysql的execute测试结果（也是一共10W条记录）
1条value，execute一次，耗时超过12分钟（没有等待完成就强制中断了）。
100条value，execute一次，耗时15.91秒。
1000条value，execute一次，耗时5.944秒。
TDengine受限于64k，没法做1000条1次execute的测试。
对于mysql的这个测试结果，我该怎么去看？

另外，请问你们修复了executemany的bug之后，最大支持多少kb的数据一次提交？

**Comment by fangpanpan** [comment]
目前如果修复了executemany，批量插入还是会受限于64k。tdengine 里python的sql命令是拼接的，写法也会有影响。您能将“insert into table_name values ()()()"这种拼接语句的写法改成list.append() 和list.join() 这用方法吗再试试？

**Comment by byronsong** [comment]
好的。我下午试试。
