### ISSUE TITLE
Unexpected generic error in RPC

### ISSUE THREAD

**Issue by bilujun** [taosdata/TDengine#3210]
**Bug Description**
安装的window客户端连接成功后，执行任意命令报Unexpected generic error in RPC

**To Reproduce**
win10 客户端操作
![image](https://user-images.githubusercontent.com/68941962/91041395-8d3c7100-e642-11ea-9c90-f86a0bf8e33c.png)
安装TDEngine本机的机器没问题
![image](https://user-images.githubusercontent.com/68941962/91041641-f91ed980-e642-11ea-9924-937b818f7bb6.png)

6030-6039 tcp,udp防火墙端口都已开放

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: WIN10
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 2.0.1.1]

**Additional Context**

**Comment by maikebing** [comment]
要用 机器名 或者 dns来连接， 不能用ip 连接

**Comment by maikebing** [comment]
参考 #3205

**Comment by bilujun** [comment]
不能用Ip这个要求很奇怪，我觉得应该遵循大多数的数据连接访问方式才对。

**Comment by maikebing** [comment]
我也觉得很奇怪。  你可以问问  @jtao1735

**Comment by bilujun** [comment]
maikebing，您好，由于这个原因，我使用您的连接器测试，在执行ExecuteReader读取数据卡顿好几秒，但抛出Exception,然后调用reader.Read()返回false，这个可能存在问题。

**Comment by bilujun** [comment]
未抛出Exception

**Comment by maikebing** [comment]
尝试一下 Maikebing.Data.Taos   2.0.123

**Comment by bilujun** [comment]
非常感谢您的回答
