### ISSUE TITLE
The data returns incomplete by restful

### ISSUE THREAD

**Issue by liujinsheng** [taosdata/TDengine#3218]
**Bug Description**
返回数据大约有2条左右，返回数据不全  restfulRowLimit有最大限制吗，默认是10240，修改到50240

这是最后返回结果的结尾 ：[103,20242110,20200820],[104,20242112,20200820。应该有rows才对啊

**Comment by sangshuduo** [comment]
请提供版本信息和重现方法步骤，谢谢

**Comment by guanshengliang** [comment]
This problem has been fixed in 2.0.3.0, and there is no response to this problem for a long time, we temporarily close it
