### ISSUE TITLE
启动服务后，使用taos命令连接终端报错:taos connect failed,reason:Unexpected generic error in RPC

### ISSUE THREAD

**Issue by lan52lan** [taosdata/TDengine#3219]
1、安装好TDengine后，使用systemctl start taosd
2、然后使用命令taos连接终端报错:taos connect failed,reason:Unexpected generic error in RPC
具体报错详情及日志报错信息见截图
![1](https://user-images.githubusercontent.com/70185936/91119222-4a6fad00-e6c5-11ea-829d-052c74bdb309.jpg)
![2](https://user-images.githubusercontent.com/70185936/91119230-4fccf780-e6c5-11ea-8b0f-f25923e67d75.jpg)
![3](https://user-images.githubusercontent.com/70185936/91119241-565b6f00-e6c5-11ea-96d6-17e3d00b3bdb.jpg)

**Comment by sangshuduo** [comment]
麻烦贴一下 /etc/taos/taos.cfg

**Comment by Aries-Lee1991** [comment]
刚才在群里已经跟您回复了，请参考：https://github.com/taosdata/TDengine/issues/3210

**Comment by lan52lan** [comment]
taos.cfg没有做更改，连不上是因为需要手动修改配置项吗？

**Comment by hjxilinx** [comment]
是的，手动修改配置文件/etc/taos/taos.cfg。 设置正确的 hostsname. 
要用 机器名 或者 dns来连接， 不能用ip 连接

**Comment by lan52lan** [comment]
是该fqdn的hostname？

**Comment by lan52lan** [comment]
是改fqdn的hostname？

**Comment by xiaopingcs** [comment]
在客户端和服务器都要通过修改hosts文件，添加一行 “host-ip fqdn”就可以了
fqdn 可以通过hostname -f得到

**Comment by lan52lan** [comment]
我通过hostname -f获取到：colasoft.localdomain
然后我hosts文件中添加一行：127.0.0.1   colasoft.localdomain
然后修改taos.cfg中fqdn hostname为fqdn colasoft.localdomain
然后重启taosd服务，执行taos命令，仍然报错：DB error:Unexpected generic error in RPC
查看日志，日志报错信息为：
faild get the ip address,fqdn:hostname,code:-3,reason:Tenporary failure in name resolution
TSC,faild to resolve FQDN:hostname
faild to set up connection
再帮忙看看是哪里的问题呢？

**Comment by xiaopingcs** [comment]
> 我通过hostname -f获取到：colasoft.localdomain
> 然后我hosts文件中添加一行：127.0.0.1 colasoft.localdomain
> 然后修改taos.cfg中fqdn hostname为fqdn colasoft.localdomain
> 然后重启taosd服务，执行taos命令，仍然报错：DB error:Unexpected generic error in RPC
> 查看日志，日志报错信息为：
> faild get the ip address,fqdn:hostname,code:-3,reason:Tenporary failure in name resolution
> TSC,faild to resolve FQDN:hostname
> faild to set up connection
> 再帮忙看看是哪里的问题呢？

那再试试下面的步骤:
1. taos.cfg 再修改一下firstEp 为 colasoft.localdomain:6030. 
2. rm -rf /var/lib/taos/* (这个是删除数据文件，谨慎操作)
3. rm -rf /var/log/taos/*
4. systemctl restart taosd

**Comment by lan52lan** [comment]
谢谢，按照您上面的操作可以了
