### ISSUE TITLE
document "Each DB has one or mode vnodes" maybe typo 

### ISSUE THREAD

**Issue by rickyzhou2017** [taosdata/TDengine#322]
Each DB has one or mode vnodes  -> Each DB has one or more vnodes

**Comment by guanshengliang** [comment]
Can you provide a URL?

**Comment by StoneT2000** [comment]
Hi @rickyzhou2017 you can make a pull request. Just click the edit button (a small pen button at each header) at where the typo is, and then edit what’s wrong and submit a pull request
