### ISSUE TITLE
TDengine的BINARY和NCHAR字段长度定义的问题

### ISSUE THREAD

**Issue by tangtang666** [taosdata/TDengine#323]
很长的数据好像存不了，我想要存类似下面ee这样长的数据有办法存吗？关系数据库我试了可以存，时序数据库influxdb我也试了可以存，TDengine的BINARY和NCHAR字段我都试了存不下，自动截取掉了，是我存的方式不对吗
{'time': '2019-08-10T19:32:26.726000128Z', 'ee': '[-0.03528048098087311, 0.027286896482110023, -0.0007418438326567411, 0.025416137650609016, 0.053813252598047256, -0.022233212366700172, -0.0040390691719949245, -0.08520957082509995, 0.010252443142235279, 0.018108868971467018, -0.0899757593870163, 0.02550979144871235, 0.003966170363128185, 0.05169397220015526, 0.020950965583324432, -0.03801539167761803, 0.04234521836042404, 0.041709307581186295, 0.011453807353973389, 0.043608054518699646, 0.001368837314657867, 0.004873236175626516, -0.06286998093128204, 0.04789498820900917, 0.033981047570705414, 0.06695793569087982, 0.06169306859374046, 0.05145832523703575, 0.009090677835047245, -0.013937442563474178, 0.020188983529806137, 0.039276301860809326, 0.045330386608839035, -0.01749137043952942, 0.021052999421954155, -0.02121269889175892, 0.04118354991078377, 0.0011114162625744939, 0.015809061005711555, 0.07680308073759079, -0.05731161683797836, 0.007630623877048492, 0.012018470093607903, 0.020156653597950935, -0.04576245695352554, 0.00302212149836123, 0.003857575822621584, 0.04108242318034172, -0.008116103708744049, -0.004665590822696686, 0.022642988711595535, -0.014812147244811058, 0.052408117800951004, 0.06084765866398811, 0.04966391623020172, -0.022079048678278923, 0.015564962290227413, -0.018733510747551918, 0.009273740462958813, 0.004851832985877991, 0.08779537677764893, 0.001946570468135178, 0.027383767068386078, 0.10449965298175812, -0.014019538648426533, 0.03441563993692398, 0.046674273908138275, 0.0004506238619796932, -0.006833740510046482, 0.011791313998401165, 0.0607965812087059, 0.06450719386339188, 0.035025738179683685, -0.005790261086076498, -0.01691628061234951, 0.0601595900952816, -0.006578200496733189, 0.02513687126338482, 0.06294408440589905, -0.025020798668265343, 0.013644073158502579, 0.056213781237602234, 0.0007981129456311464, 0.016108524054288864, 0.05471637845039368, 0.0012995123397558928, 0.016845520585775375, -0.016752880066633224, 0.043014347553253174, 0.04425985366106033, 0.05840873718261719, 0.08013138175010681, 0.008619766682386398, -0.0027399903628975153, 0.07383548468351364, 0.024592746049165726, -0.021057378500699997, 0.009900719858705997, 0.005471620708703995, 0.04526306316256523, -0.005952890962362289, 0.05773773416876793, 0.023456500843167305, 0.008080728352069855, 0.058517035096883774, -0.024503124877810478, 0.005944359581917524, 0.00507886428385973, 0.01318674348294735, 0.0603465810418129, -0.06611733883619308, -0.011644145473837852, -0.01192433387041092, 0.03546788543462753, 0.09713675081729889, -0.021836599335074425, 0.10526321828365326, -0.009932866320014, 0.0035930462181568146, 0.054383210837841034, 0.02368127927184105, 0.026380708441138268, 0.0042810142040252686, 0.021515272557735443, 0.03533995524048805, -0.012441177852451801, -0.0790901780128479, 0.051035262644290924, 0.07921769469976425, 0.07250519096851349, -0.0609503909945488, 0.020941350609064102, 0.04431222006678581, -0.08292869478464127, 0.05683254823088646, 0.05777277797460556, 0.032624464482069016, 0.01597195491194725, 0.02574462816119194, 0.06784772127866745, -0.048757001757621765, -0.00514857517555356, 0.05055033788084984, 0.043155837804079056, 0.06700105220079422, 0.03636126220226288, -0.021919498220086098, 0.019295519217848778, 0.017454132437705994, -0.03310017287731171, 0.03181186690926552, -0.016067931428551674, -0.0011181653244420886, -0.014110313728451729, -0.019312160089612007, 0.052069392055273056, 0.057713061571121216, 0.012760455720126629, 0.024927163496613503, 0.04285895451903343, -0.05217071250081062, -0.019355662167072296, -0.025166628882288933, 0.016875319182872772, 0.04603835940361023, 0.038711387664079666, 0.017304981127381325, 0.003174789482727647, 0.0767933577299118, 0.011517930775880814, 0.031441133469343185, 0.03157695755362511, 0.03226739913225174, 0.02219456434249878, 0.017886118963360786, 0.04537057504057884, 0.028190165758132935, 0.01350626815110445, -0.028700053691864014, -0.013370933942496777, 0.07451407611370087, 0.03276396542787552, 0.0815202072262764, -0.03256774693727493, 0.10923678427934647, -0.0014378518098965287, -0.052928946912288666, 0.06117980182170868, -0.014873397536575794, 0.025727281346917152, -0.013074330985546112, -0.01631264016032219, 0.042352695018053055, -0.04771636053919792, 0.04806462302803993, 0.019166365265846252, 0.08585917949676514, -0.007730942219495773, -0.015653615817427635, 0.029796581715345383, -0.010134628973901272, 0.10979466885328293, 0.046182066202163696, 0.015672652050852776, -0.0022465584333986044, 0.030292777344584465, 0.01952970214188099, 0.031203944236040115, 0.0042068082839250565, -0.014200083911418915, 0.05739163979887962, 0.0093471584841609, 0.09385041892528534, 0.049308422952890396, 0.02124612033367157, 0.06256658583879471, -0.015288256108760834, 0.039212916046381, 0.037055689841508865, 0.028287962079048157, 0.0447474904358387, 0.05071225017309189, 0.034886009991168976, -0.05470210313796997, 0.04884803667664528, 0.013996291905641556, 0.020351428538560867, 0.05862155556678772, 0.016110414639115334, 0.02116318792104721, 0.10455203801393509, -0.006819712929427624, -0.0069349054247140884, 0.09657078981399536, 0.018588317558169365, 0.011656573973596096, 0.011508935131132603, 0.06108852103352547, 0.016935044899582863, 0.0914025828242302, 0.012097015976905823, -0.052945829927921295, 0.0028517150785773993, -0.01752985455095768, 0.05749532952904701, 0.042121853679418564, 0.012575631029903889, 0.01605500467121601, 0.037701766937971115, -0.0014550958294421434, -0.013324590399861336, -0.01364989671856165, 0.012629847973585129, 0.030297385528683662, 0.04977068677544594, 0.02472853846848011, 0.0644693374633789, 0.05561832711100578, -0.030514506623148918, 0.08027905970811844, 0.1238122433423996, 0.015363410115242004, -0.014271407388150692, 0.026094410568475723, 0.006495703011751175, 0.03138825297355652, 0.026711178943514824, 0.04987286776304245, 0.04391945153474808, 0.006514473352581263, -0.00906029250472784, 0.048182759433984756, 0.023428302258253098, 0.019303197041153908, 0.052569203078746796, 0.03795529156923294, 0.02427290566265583, 0.050613418221473694, 0.03362646698951721, 0.0009266910492442548, 0.03415771201252937, 0.015345653519034386, 0.025752704590559006, 0.017919158563017845, -0.013580171391367912, 0.009267590939998627, 0.04058182239532471, 0.05178622156381607, 0.06320615857839584, -0.053471099585294724, -0.007718692068010569, 0.047991540282964706, 0.01063609030097723, 0.0411376953125, -0.013924571685492992, 0.061335500329732895, 0.046150751411914825, 0.05198035389184952, 0.010749723762273788, -0.006863475777208805, -0.0068272012285888195, -0.0069999233819544315, -0.03748319670557976, 0.03984181955456734, 0.00823902152478695, 0.021453814581036568, -0.018619142472743988, 0.02836775593459606, 0.05087888240814209, 0.06865610927343369, 0.01623431034386158, 0.010903758928179741, 0.04341181367635727, 0.04435510188341141, 0.07862314581871033, -0.01237401831895113, 0.0806085467338562, 0.10171294957399368, 0.06491485238075256, 0.08131401985883713, 0.04766295105218887, -0.01890331506729126, 0.052040647715330124, -0.02311735227704048, -0.0288002360612154, -0.0036841314285993576, 0.022563863545656204, 0.0037481973413378, 0.07187555730342865, 0.06432658433914185, 0.10318039357662201, 0.041159436106681824, -0.009357712231576443, 0.05959300324320793, 0.11253755539655685, -0.03100850246846676, 0.051510125398635864, -0.020389903336763382, -0.0008627715287730098, 0.023985503241419792, 0.039926107972860336, 0.04144696518778801, 0.004108974244445562, 0.02409999445080757, 0.024560391902923584, 0.050532083958387375, 0.03777850419282913, 0.021004894748330116, 0.0823291763663292, 0.05264456942677498, 0.030299128964543343, -0.03660288825631142, 0.022447003051638603, 0.01542443223297596, 0.0036907889880239964, 0.10378424823284149, 0.04697248712182045, 0.012564241886138916, 0.01864309050142765, 0.039938636124134064, -0.017461637035012245, 0.04897197335958481, 0.042380113154649734, 0.001685027265921235, -0.002950357273221016, 0.03624323010444641, 0.023852668702602386, 0.05202299728989601, 0.05385676398873329, 0.021072661504149437, 0.002564289141446352, 0.03979102894663811, 0.04526710510253906, -0.03796622157096863, 0.02210802026093006, 0.04362870752811432, 0.027046097442507744, 0.0017034783959388733, 0.011486922390758991, 0.02881265990436077, 0.12013228982686996, 0.025733614340424538, 0.056535400450229645, -0.004181671887636185, -0.021445507183670998, 0.04019249230623245, 0.0022454678546637297, -0.04100075364112854, 0.059015486389398575, 0.007327910512685776, 0.007121168076992035, 0.06125783175230026, 0.04489095136523247, 0.02005450800061226, 0.0322340652346611, 0.0804351344704628, 0.03548420965671539, 0.02788640186190605, -0.017493823543190956, 0.008650349453091621, -0.053777020424604416, 0.020550141111016273, 0.06164352968335152, 0.07536986470222473, 0.05100899562239647, 0.07091144472360611, 0.04933900386095047, 0.0325232669711113, -0.002461418742313981, 0.10563243925571442, 0.0038903788663446903, -0.008036285638809204, 0.0038204328157007694, 0.06632925570011139, 0.02646239474415779, -0.0006310850149020553, 0.03301088511943817, 0.06961867213249207, -0.03892794996500015, 0.07546146214008331, 0.08248545974493027, 0.036143962293863297, 0.09354231506586075, 0.020373625680804253, 0.004718051757663488, -0.012706603854894638, -0.008821072056889534, 0.03625411167740822, -0.044127456843853, 0.00029583057039417326, 0.016500132158398628, 0.007349945604801178, 0.07963239401578903, 0.058053649961948395, 0.03708314895629883, -0.007256914395838976, 0.01783856563270092, 0.052607063204050064, 0.0473337322473526, 0.02438228391110897, -0.01343026664108038, 0.04518360644578934, 0.027171887457370758, 0.016977226361632347, 0.029000405222177505, 0.030663693323731422, 0.024795347824692726, 0.024250684306025505, 0.03808470815420151, 0.05660172551870346, 0.004140366334468126, 0.013265503570437431, 0.06636007875204086, 0.05365976318717003, 0.04473036155104637, 0.1185273677110672, -0.06118713319301605, 0.08291284739971161, 0.04604828357696533, 0.07668870687484741, 0.030003629624843597, -0.01539669744670391, 0.03379720821976662, 0.032235037535429, 0.09830735623836517, 0.048663247376680374, 0.08606226742267609, 0.06048988550901413, -0.05766700580716133, 0.02445685677230358, -0.004865641705691814, 0.024515969678759575, 0.021147863939404488, 0.01609421707689762, 0.022485636174678802, 0.031349800527095795, 0.04720797389745712, 0.04487118870019913, 0.11194270104169846, 0.08623869717121124, 0.02179536037147045, 0.031766247004270554, 0.017546823248267174, 0.028297362849116325, 0.005315390881150961, 0.010469942353665829, -0.044585343450307846, -0.038805704563856125, 0.04087424278259277, 0.06716595590114594, 0.056665290147066116, 0.05549325793981552, 0.07282999157905579, -0.012849449180066586, 0.04563773795962334, -0.03263067826628685, 0.09636127203702927, 0.04657026007771492, 0.016711171716451645, 0.06394228339195251, 0.05444280058145523, 0.02956090308725834, 0.041354890912771225, -0.04355296865105629, -0.014669748023152351, 0.05995794013142586, 0.06337333470582962, 0.06985370069742203, 0.041475825011730194, 0.036839138716459274, 0.08854091912508011, 0.04024093225598335]'}

**Comment by guanshengliang** [comment]
TDengine是结构化的时序数据库，每行数据最长长度为4096字节。
您需要重新设计数据模型，将非结构化的数据转化为结构化数据而不是以字符串形式存储。
如果确实是非结构化的数据，那么TDengine并不适合这种场景
