### ISSUE TITLE
'select count(*) from xx' returns an empty result set if 'xx' has no data, should return an one column result set with value zero

### ISSUE THREAD

**Issue by zwllxs** [taosdata/TDengine#3240]
如果有表d1002，没有一条结果时，查询count结果如下，正常应该返回1条结果集，有1个列，列值为0，而不应该是空结果集
![图片](https://user-images.githubusercontent.com/5228810/91255577-b0c50000-e797-11ea-9d98-77f37c440ef4.png)

**Comment by hjxilinx** [comment]
在 count 的行为上，TDengine对于没有记录的数据不会返回任何结果。与 InfluxDB 等库的行为保持了一致。

**Comment by hjxilinx** [comment]
后续的版本会调整这个行为，允许用户配置该行为，关闭该 issue。
