### ISSUE TITLE
The actual result is different to the exception status on IDEA with java driver

### ISSUE THREAD

**Issue by zwllxs** [taosdata/TDengine#3241]
在idea中配置了java驱动，对TdEngine进行操作，每次都会返回一个异常信息,
但是实际情况，有时是执行成功的，比如select, insert等语句，有时却真没成功
![图片](https://user-images.githubusercontent.com/5228810/91255708-0dc0b600-e798-11ea-8a81-42bbaec24f39.png)
![图片](https://user-images.githubusercontent.com/5228810/91255780-495b8000-e798-11ea-9033-c3856ee5b43e.png)

![图片](https://user-images.githubusercontent.com/5228810/91255684-f84b8c00-e797-11ea-8fce-1914ca3f0894.png)

**Comment by Aries-Lee1991** [comment]
可以参考一下这个教程：https://www.taosdata.com/blog/2020/08/27/1767.html

**Comment by zyyang-taosdata** [comment]
参考一下这篇文章吧，[如何通过IDEA Database管理工具连接TDengine](https://mp.weixin.qq.com/s/i-ivWiCP9YJ3HdihPxeXRg)

**Comment by zwllxs** [comment]
> 
> 
> 参考一下这篇文章吧，[如何通过IDEA Database管理工具连接TDengine](https://mp.weixin.qq.com/s/i-ivWiCP9YJ3HdihPxeXRg)

用的就是指定链接里的方法

**Comment by zyyang-taosdata** [comment]
this issue is closed by the assignees
