### ISSUE TITLE
底层查询基于什么算法呢？

### ISSUE THREAD

**Issue by hitits** [taosdata/TDengine#3243]
不懂C，所以没法看源码。
想知道底层是基于什么算法查询的；对压缩处理后的数据查询，如何做到高效查找？
(这些有助于使用者进行技术选型和表设计)

**Comment by Aries-Lee1991** [comment]
https://www.taosdata.com/cn/documentation/，不用看源码，请多研究一下我们的文档，所有思路都公开了。
