### ISSUE TITLE
float,double类型会丢失精度

### ISSUE THREAD

**Issue by zwllxs** [taosdata/TDengine#3247]
float,double类型会丢失精度, 
![图片](https://user-images.githubusercontent.com/5228810/91295972-72970300-e7ce-11ea-9175-67e891ca0d6e.png)

 一般数据库都有decimal类型，不知道以后有没有可能考虑增加

**Comment by Aries-Lee1991** [comment]
这是浮点数本身的设计标准，请参考IEEE 754。
