### ISSUE TITLE
 Can log name support customization?

### ISSUE THREAD

**Issue by hitits** [taosdata/TDengine#3249]
![image](https://user-images.githubusercontent.com/69614127/91371104-b3306400-e842-11ea-96d6-250a0dea8e3e.png)

![image](https://user-images.githubusercontent.com/69614127/91371111-b592be00-e842-11ea-8ab8-c07d16052878.png)
这个日志的名称能支持自定义么，想根据日期去命名。单个文件时间久了有点大，不好定位

**Comment by hjxilinx** [comment]
这日志是两个文件的滚动记录。当初我们考虑到如果按照每天生成一个日志可能日志量非常大。所以为了控制日志总量，只用两个文件轮转。要定位里边的错误，我们一般都是 grep “ERROR”来确定日志中的错误。
