### ISSUE TITLE
求助一下，数据库表部分的源代码解读？

### ISSUE THREAD

**Issue by zhangzhongshuai** [taosdata/TDengine#325]
`typedef struct {
  SSdbHeader header;
  int        maxRows;
  int        dbId;
  int32_t    maxRowSize;
  char       name[TSDB_DB_NAME_LEN];
  char       fn[128];
  int        keyType;
  uint32_t   autoIndex;
  int64_t    numOfRows;
  int64_t    id;
  int64_t    size;
  void *     iHandle;
  int        fd;
  void *(*appTool)(char, void *, char *, int, int *);
  pthread_mutex_t mutex;
  SSdbUpdate *    update;
  int             numOfUpdates;
  int             updatePos;
} SSdbTable;`
该结构体中，各变量分别是什么意思？
表缺省支持的列数为256，跟该结构体中的变量有关系吗？

**Comment by guanshengliang** [comment]
列数256的定义不在这里，而且，不是修改一个定义就可以将列数目增大的，可能会引发性能的下降。

**Comment by guanshengliang** [comment]
目前研发任务较多，社区内的一些需求需要处理，一些BUG需要尽快FIX
因此，该结构体各个列的含义，还请您自己钻研，代码解读工作我们以后会在合适的时间开展
