### ISSUE TITLE
Unable to establish connection by Windows Client to Linux Server

### ISSUE THREAD

**Issue by zhangzl0119** [taosdata/TDengine#3250]
linux和windows都是用的最新版本2.0.2.1版本，Java客户使用的jar包版本2.0.4. 发布到linux服务器是没有问题的，但是在windows本地运行就是出现错误：TDengine Error: Unable to establish connection。

客户端本地日志：
[客户端日志.txt](https://github.com/taosdata/TDengine/files/5133454/default.txt)

服务端日志：
[服务端日志.txt](https://github.com/taosdata/TDengine/files/5133461/default.txt)

**Comment by guanshengliang** [comment]
这个问题和jdbc没有关系，就是两者之间网络通信不正常。
在windows环境下，在C:\TDengine\cfg\taos.cfg中，将debugFlag设置为143，然后把C:\TDengine\log文件夹的文件都清掉，使用taos.exe -h <serverip或fqdn>，然后将log文件再上传一次。

您也需要检查一下，pre-hbase-04这台机器是否开了防火墙，6030-6042的udp/tcp端口是否开放，检查方法最简答的是telnet

**Comment by guanshengliang** [comment]
您提供的客户端日志，并没有任何调试信息，还只有ERROR输出，根据这个ERROR输出，不能完全定位

**Comment by zhangzl0119** [comment]
![image](https://user-images.githubusercontent.com/32055976/91375703-f80dc800-e84d-11ea-8626-ee4ec2d5bef4.png)
设置不了调试信息。
pre-hbase-04防火墙并没有开

**Comment by guanshengliang** [comment]
那就打开防火墙啊

**Comment by zhangzl0119** [comment]
![image](https://user-images.githubusercontent.com/32055976/91376523-cd247380-e84f-11ea-95f8-510148f5df8c.png)
没有防火墙呀

**Comment by guanshengliang** [comment]
telnet 172.16.16.220 6030
另外，日志也贴一下

**Comment by zhangzl0119** [comment]
是可以telnet通的，什么日志？

**Comment by guanshengliang** [comment]
在windows环境下，在C:\TDengine\cfg\taos.cfg中，将debugFlag设置为143，然后把C:\TDengine\log文件夹的文件都清掉，使用taos.exe -h <serverip或fqdn>，然后将log文件再上传一次。

**Comment by zhangzl0119** [comment]
==================================================
                new log file                      
==================================================
08/27 10:11:28.269000 0x00005b80 UTL localEp is: zzl-pc:6030
08/27 10:11:28.269000 0x00005b80 UTL timezone not configured, use default
08/27 10:11:28.293000 0x00005b80 UTL locale not configured, set to default:Chinese_China.936
08/27 10:11:28.293000 0x00005b80 UTL charset not configured, set to default:cp936
08/27 10:11:28.293000 0x00005b80 UTL    taos config & system info:
08/27 10:11:28.293000 0x00005b80 UTL ==================================
08/27 10:11:28.293000 0x00005b80 UTL  firstEp:                zzl-pc:6030 
08/27 10:11:28.293000 0x00005b80 UTL  secondEp:               zzl-pc:6030 
08/27 10:11:28.293000 0x00005b80 UTL  fqdn:                   zzl-pc 
08/27 10:11:28.293000 0x00005b80 UTL  serverPort:             6030 
08/27 10:11:28.293000 0x00005b80 UTL  configDir:              C:/TDengine/cfg 
08/27 10:11:28.293000 0x00005b80 UTL  logDir:                 C:/TDengine/log 
08/27 10:11:28.293000 0x00005b80 UTL  scriptDir:              C:/TDengine/script 
08/27 10:11:28.293000 0x00005b80 UTL  arbitrator:              
08/27 10:11:28.293000 0x00005b80 UTL  numOfThreadsPerCore:    0.000000 
08/27 10:11:28.293000 0x00005b80 UTL  rpcTimer:               1000(ms)
08/27 10:11:28.293000 0x00005b80 UTL  rpcMaxTime:             600(s)
08/27 10:11:28.293000 0x00005b80 UTL  shellActivityTimer:     3(s)
08/27 10:11:28.293000 0x00005b80 UTL  tableMetaKeepTimer:     7200(s)
08/27 10:11:28.293000 0x00005b80 UTL  compressMsgSize:        -1 
08/27 10:11:28.293000 0x00005b80 UTL  maxSQLLength:           65480(byte)
08/27 10:11:28.293000 0x00005b80 UTL  maxNumOfOrderedRes:     100000 
08/27 10:11:28.293000 0x00005b80 UTL  timezone:               not configured 
08/27 10:11:28.293000 0x00005b80 UTL  locale:                 Chinese_China.936 
08/27 10:11:28.293000 0x00005b80 UTL  charset:                cp936 
08/27 10:11:28.293000 0x00005b80 UTL  numOfLogLines:          10000000 
08/27 10:11:28.293000 0x00005b80 UTL  asyncLog:               1 
08/27 10:11:28.293000 0x00005b80 UTL  debugFlag:              0 
08/27 10:11:28.293000 0x00005b80 UTL  rpcDebugFlag:           131 
08/27 10:11:28.293000 0x00005b80 UTL  tmrDebugFlag:           131 
08/27 10:11:28.293000 0x00005b80 UTL  cDebugFlag:             131 
08/27 10:11:28.293000 0x00005b80 UTL  jniDebugFlag:           131 
08/27 10:11:28.293000 0x00005b80 UTL  odbcDebugFlag:          131 
08/27 10:11:28.293000 0x00005b80 UTL  uDebugFlag:             131 
08/27 10:11:28.293000 0x00005b80 UTL  qDebugFlag:             131 
08/27 10:11:28.293000 0x00005b80 UTL  tsdbDebugFlag:          131 
08/27 10:11:28.293000 0x00005b80 UTL  gitinfo:                1527828603722a0ed8ea706439e8c172a13b7eb1 
08/27 10:11:28.293000 0x00005b80 UTL  gitinfoOfInternal:      490a983428d02b00d06b2a067b3f6e74f4b8d1a8 
08/27 10:11:28.293000 0x00005b80 UTL  buildinfo:              Built by root at 2020-08-26 12:00 
08/27 10:11:28.293000 0x00005b80 UTL  version:                2.0.2.1 
08/27 10:11:28.293000 0x00005b80 UTL  maxBinaryDisplayWidth:  30 
08/27 10:11:32.314000 0x00005b80 RPC ERROR TSC, failed to create eventfd(No such file or directory)
08/27 10:11:32.317000 0x00005b80 JNI ERROR jobj:000000000261F018, conn:0000000000000000, connect to database failed, host=pre-hbase-04, user=root, dbname=log, port=6030
08/27 10:11:32.319000 0x00005b80 JNI ERROR jobj:000000000261EF98, connection is closed

**Comment by guanshengliang** [comment]
设置成143

**Comment by zhangzl0119** [comment]
![image](https://user-images.githubusercontent.com/32055976/91376882-c0544f80-e850-11ea-98ba-556940a1b261.png)

已经设置成143了，但是没法生效

**Comment by guanshengliang** [comment]
在配置文件的最上面，增加一行debugFlag 143
#号表示注释的意思

**Comment by zhangzl0119** [comment]
==================================================
                new log file                      
==================================================
08/27 10:38:24.666000 0x000043f4 UTL all debug flag are set to 143
08/27 10:38:24.676000 0x000043f4 UTL localEp is: zzl-pc:6030
08/27 10:38:24.676000 0x000043f4 UTL timezone not configured, use default
08/27 10:38:24.700000 0x000043f4 UTL locale not configured, set to default:Chinese_China.936
08/27 10:38:24.700000 0x000043f4 UTL charset not configured, set to default:cp936
08/27 10:38:24.700000 0x000043f4 UTL    taos config & system info:
08/27 10:38:24.700000 0x000043f4 UTL ==================================
08/27 10:38:24.700000 0x000043f4 UTL  firstEp:                zzl-pc:6030 
08/27 10:38:24.700000 0x000043f4 UTL  secondEp:               zzl-pc:6030 
08/27 10:38:24.700000 0x000043f4 UTL  fqdn:                   zzl-pc 
08/27 10:38:24.700000 0x000043f4 UTL  serverPort:             6030 
08/27 10:38:24.700000 0x000043f4 UTL  configDir:              C:/TDengine/cfg 
08/27 10:38:24.700000 0x000043f4 UTL  logDir:                 C:/TDengine/log 
08/27 10:38:24.700000 0x000043f4 UTL  scriptDir:              C:/TDengine/script 
08/27 10:38:24.700000 0x000043f4 UTL  arbitrator:              
08/27 10:38:24.700000 0x000043f4 UTL  numOfThreadsPerCore:    0.000000 
08/27 10:38:24.700000 0x000043f4 UTL  rpcTimer:               1000(ms)
08/27 10:38:24.700000 0x000043f4 UTL  rpcMaxTime:             600(s)
08/27 10:38:24.700000 0x000043f4 UTL  shellActivityTimer:     3(s)
08/27 10:38:24.700000 0x000043f4 UTL  tableMetaKeepTimer:     7200(s)
08/27 10:38:24.700000 0x000043f4 UTL  compressMsgSize:        -1 
08/27 10:38:24.700000 0x000043f4 UTL  maxSQLLength:           65480(byte)
08/27 10:38:24.700000 0x000043f4 UTL  maxNumOfOrderedRes:     100000 
08/27 10:38:24.700000 0x000043f4 UTL  timezone:               not configured 
08/27 10:38:24.700000 0x000043f4 UTL  locale:                 Chinese_China.936 
08/27 10:38:24.700000 0x000043f4 UTL  charset:                cp936 
08/27 10:38:24.700000 0x000043f4 UTL  numOfLogLines:          10000000 
08/27 10:38:24.700000 0x000043f4 UTL  asyncLog:               1 
08/27 10:38:24.700000 0x000043f4 UTL  debugFlag:              143 
08/27 10:38:24.700000 0x000043f4 UTL  rpcDebugFlag:           143 
08/27 10:38:24.700000 0x000043f4 UTL  tmrDebugFlag:           143 
08/27 10:38:24.700000 0x000043f4 UTL  cDebugFlag:             143 
08/27 10:38:24.700000 0x000043f4 UTL  jniDebugFlag:           143 
08/27 10:38:24.700000 0x000043f4 UTL  odbcDebugFlag:          143 
08/27 10:38:24.700000 0x000043f4 UTL  uDebugFlag:             143 
08/27 10:38:24.700000 0x000043f4 UTL  qDebugFlag:             143 
08/27 10:38:24.700000 0x000043f4 UTL  tsdbDebugFlag:          143 
08/27 10:38:24.700000 0x000043f4 UTL  gitinfo:                1527828603722a0ed8ea706439e8c172a13b7eb1 
08/27 10:38:24.700000 0x000043f4 UTL  gitinfoOfInternal:      490a983428d02b00d06b2a067b3f6e74f4b8d1a8 
08/27 10:38:24.700000 0x000043f4 UTL  buildinfo:              Built by root at 2020-08-26 12:00 
08/27 10:38:24.700000 0x000043f4 UTL  version:                2.0.2.1 
08/27 10:38:24.700000 0x000043f4 UTL  maxBinaryDisplayWidth:  30 
08/27 10:38:24.700000 0x000043f4 TSC starting to initialize TAOS client ...
08/27 10:38:24.700000 0x000043f4 TSC Local End Point is:zzl-pc:6030
08/27 10:38:24.700000 0x000043f4 UTL tsc scheduler is initialized, numOfThreads:2
08/27 10:38:24.701000 0x000043f4 UTL tmr scheduler is initialized, numOfThreads:1
08/27 10:38:24.701000 0x000043f4 TMR timer module is initialized, number of threads: 1
08/27 10:38:24.701000 0x000043f4 TMR TSC timer controller is initialized, number of timer controllers: 1.
08/27 10:38:24.701000 0x000043f4 TMR TSC timer[id=0] does not exist
08/27 10:38:24.701000 0x000043f4 TMR TSC timer[id=1, fp=00007FFA8B7F9BA0, param=0000000000000000] started
08/27 10:38:24.701000 0x000043f4 TSC client is initialized successfully
08/27 10:38:24.701000 0x000043f4 UTL pool:0000000001426640 is setup, maxId:5000
08/27 10:38:24.701000 0x000043f4 TMR TSC timer controller is initialized, number of timer controllers: 2.
08/27 10:38:24.701000 0x000043f4 TMR TSC timer[id=0] does not exist
08/27 10:38:24.701000 0x000043f4 TMR TSC timer[id=2, fp=00007FFA8B80BF50, param=000000000142D860] started
08/27 10:38:24.701000 0x000043f4 RPC TSC TCP client is initialized, ip:0:0
08/27 10:38:24.701000 0x000043f4 UTL open udp socket:0x0:0
08/27 10:38:24.702000 0x000043f4 RPC TSC UDP connection is initialized, ip:0:0 threads:1
08/27 10:38:24.702000 0x000043f4 RPC TSC rpc is openned, threads:1 sessions:5000
08/27 10:38:24.702000 0x000043f4 TSC dnodeConn:000000000143C390 is created, user:root
08/27 10:38:24.702000 0x000043f4 TSC 000000002567D480 SQL cmd:connect will be processed, name:(null), type:0
08/27 10:38:24.702000 0x000043f4 RPC malloc mem: 0000000025996CD0
08/27 10:38:24.702000 0x00008e48 RPC TSC UDP thread is created, index:0
08/27 10:38:24.703000 0x000043f4 RPC TSC 0000000025D8E1B8 client connection is allocated, uid:0x25d975eb
08/27 10:38:24.703000 0x000043f4 RPC TSC UDP connection is setup, ip:dc1010ac:6030 localPort:55695
08/27 10:38:24.703000 0x000043f4 RPC TSC 0000000025D8E1B8 000000002567D480, connect is sent to pre-hbase-04:6030, len:345 sig:0x01000000:0x00000000:7116
08/27 10:38:24.704000 0x000043f4 TMR TSC timer[id=0] does not exist
08/27 10:38:24.704000 0x000043f4 TMR TSC timer[id=3, fp=00007FFA8B807570, param=0000000025D8E1B8] started
08/27 10:38:24.717000 0x000091c4 TMR TSC adding expired timer[id=1, fp=00007FFA8B7F9BA0, param=0000000000000000] to queue.
08/27 10:38:24.717000 0x000091c4 TMR timer[id=1] has been added to queue.
08/27 10:38:24.717000 0x00005d98 TMR TSC timer[id=1, fp=00007FFA8B7F9BA0, param=0000000000000000] execution start.
08/27 10:38:24.717000 0x00005d98 TMR TSC timer[id=4, fp=00007FFA8B7F9BA0, param=0000000000000000] started
08/27 10:38:24.717000 0x00005d98 TMR TSC timer[id=1, fp=00007FFA8B7F9BA0, param=0000000000000000] execution end.
08/27 10:38:25.707000 0x000091c4 TMR TSC adding expired timer[id=3, fp=00007FFA8B807570, param=0000000025D8E1B8] to queue.
08/27 10:38:25.707000 0x000091c4 TMR timer[id=3] has been added to queue.
08/27 10:38:25.707000 0x00005d98 TMR TSC timer[id=3, fp=00007FFA8B807570, param=0000000025D8E1B8] execution start.
08/27 10:38:25.707000 0x00005d98 RPC TSC 0000000025D8E1B8 000000002567D480, expected connect-rsp is not received
08/27 10:38:25.707000 0x00005d98 RPC TSC 0000000025D8E1B8 000000002567D480, re-send msg:connect to pre-hbase-04:6030
08/27 10:38:25.707000 0x00005d98 RPC TSC 0000000025D8E1B8 000000002567D480, connect is sent to pre-hbase-04:6030, len:345 sig:0x01000000:0x00000000:7116
08/27 10:38:25.707000 0x00005d98 TMR TSC timer[id=5, fp=00007FFA8B807570, param=0000000025D8E1B8] started
08/27 10:38:25.707000 0x00005d98 TMR TSC timer[id=3, fp=00007FFA8B807570, param=0000000025D8E1B8] execution end.
08/27 10:38:25.722000 0x000091c4 TMR TSC adding expired timer[id=4, fp=00007FFA8B7F9BA0, param=0000000000000000] to queue.
08/27 10:38:25.722000 0x000091c4 TMR timer[id=4] has been added to queue.
08/27 10:38:25.722000 0x00005d98 TMR TSC timer[id=4, fp=00007FFA8B7F9BA0, param=0000000000000000] execution start.
08/27 10:38:25.722000 0x00005d98 TMR TSC timer[id=6, fp=00007FFA8B7F9BA0, param=0000000000000000] started
08/27 10:38:25.722000 0x00005d98 TMR TSC timer[id=4, fp=00007FFA8B7F9BA0, param=0000000000000000] execution end.
08/27 10:38:26.712000 0x000091c4 TMR TSC adding expired timer[id=5, fp=00007FFA8B807570, param=0000000025D8E1B8] to queue.
08/27 10:38:26.712000 0x000091c4 TMR timer[id=5] has been added to queue.
08/27 10:38:26.712000 0x00005d98 TMR TSC timer[id=5, fp=00007FFA8B807570, param=0000000025D8E1B8] execution start.
08/27 10:38:26.712000 0x00005d98 RPC TSC 0000000025D8E1B8 000000002567D480, expected connect-rsp is not received
08/27 10:38:26.712000 0x00005d98 RPC TSC 0000000025D8E1B8 000000002567D480, re-send msg:connect to pre-hbase-04:6030
08/27 10:38:26.712000 0x00005d98 RPC TSC 0000000025D8E1B8 000000002567D480, connect is sent to pre-hbase-04:6030, len:345 sig:0x01000000:0x00000000:7116
08/27 10:38:26.712000 0x00005d98 TMR TSC timer[id=7, fp=00007FFA8B807570, param=0000000025D8E1B8] started
08/27 10:38:26.712000 0x00005d98 TMR TSC timer[id=5, fp=00007FFA8B807570, param=0000000025D8E1B8] execution end.
08/27 10:38:26.726000 0x000091c4 TMR TSC adding expired timer[id=6, fp=00007FFA8B7F9BA0, param=0000000000000000] to queue.
08/27 10:38:26.726000 0x000091c4 TMR timer[id=6] has been added to queue.
08/27 10:38:26.726000 0x00005d98 TMR TSC timer[id=6, fp=00007FFA8B7F9BA0, param=0000000000000000] execution start.
08/27 10:38:26.726000 0x00005d98 TMR TSC timer[id=8, fp=00007FFA8B7F9BA0, param=0000000000000000] started
08/27 10:38:26.726000 0x00005d98 TMR TSC timer[id=6, fp=00007FFA8B7F9BA0, param=0000000000000000] execution end.
08/27 10:38:27.717000 0x000091c4 TMR TSC adding expired timer[id=7, fp=00007FFA8B807570, param=0000000025D8E1B8] to queue.
08/27 10:38:27.717000 0x000091c4 TMR timer[id=7] has been added to queue.
08/27 10:38:27.717000 0x00005d98 TMR TSC timer[id=7, fp=00007FFA8B807570, param=0000000025D8E1B8] execution start.
08/27 10:38:27.717000 0x00005d98 RPC TSC 0000000025D8E1B8 000000002567D480, expected connect-rsp is not received
08/27 10:38:27.717000 0x00005d98 RPC TSC 0000000025D8E1B8 000000002567D480, re-send msg:connect to pre-hbase-04:6030
08/27 10:38:27.717000 0x00005d98 RPC TSC 0000000025D8E1B8 000000002567D480, connect is sent to pre-hbase-04:6030, len:345 sig:0x01000000:0x00000000:7116
08/27 10:38:27.717000 0x00005d98 TMR TSC timer[id=9, fp=00007FFA8B807570, param=0000000025D8E1B8] started
08/27 10:38:27.717000 0x00005d98 TMR TSC timer[id=7, fp=00007FFA8B807570, param=0000000025D8E1B8] execution end.
08/27 10:38:27.732000 0x000091c4 TMR TSC adding expired timer[id=8, fp=00007FFA8B7F9BA0, param=0000000000000000] to queue.
08/27 10:38:27.732000 0x000091c4 TMR timer[id=8] has been added to queue.
08/27 10:38:27.732000 0x00005d98 TMR TSC timer[id=8, fp=00007FFA8B7F9BA0, param=0000000000000000] execution start.
08/27 10:38:27.732000 0x00005d98 TMR TSC timer[id=10, fp=00007FFA8B7F9BA0, param=0000000000000000] started
08/27 10:38:27.732000 0x00005d98 TMR TSC timer[id=8, fp=00007FFA8B7F9BA0, param=0000000000000000] execution end.
08/27 10:38:28.707000 0x000091c4 TMR TSC adding expired timer[id=2, fp=00007FFA8B80BF50, param=000000000142D860] to queue.
08/27 10:38:28.707000 0x000091c4 TMR timer[id=2] has been added to queue.
08/27 10:38:28.707000 0x00005d98 TMR TSC timer[id=2, fp=00007FFA8B80BF50, param=000000000142D860] execution start.
08/27 10:38:28.708000 0x00005d98 TMR TSC timer[id=11, fp=00007FFA8B80BF50, param=000000000142D860] started
08/27 10:38:28.708000 0x00005d98 TMR TSC timer[id=2, fp=00007FFA8B80BF50, param=000000000142D860] execution end.
08/27 10:38:28.722000 0x000091c4 TMR TSC adding expired timer[id=9, fp=00007FFA8B807570, param=0000000025D8E1B8] to queue.
08/27 10:38:28.722000 0x000091c4 TMR timer[id=9] has been added to queue.
08/27 10:38:28.722000 0x00005d98 TMR TSC timer[id=9, fp=00007FFA8B807570, param=0000000025D8E1B8] execution start.
08/27 10:38:28.722000 0x00005d98 RPC TSC 0000000025D8E1B8 000000002567D480, expected connect-rsp is not received
08/27 10:38:28.722000 0x00005d98 RPC TSC 0000000025D8E1B8 000000002567D480, failed to send msg:connect to pre-hbase-04:6030
08/27 10:38:28.722000 0x00005d98 TMR TSC timer[id=12, fp=00007FFA8B807410, param=0000000025996CD0] started
08/27 10:38:28.722000 0x00005d98 TMR TSC adding expired timer[id=12, fp=00007FFA8B807410, param=0000000025996CD0] to queue.
08/27 10:38:28.722000 0x00005d98 TMR timer[id=12] has been added to queue.
08/27 10:38:28.722000 0x00005d98 TMR timer[id=0] does not exist
08/27 10:38:28.722000 0x00005d98 TMR timer[id=0] does not exist
08/27 10:38:28.722000 0x00005d98 RPC TSC 0000000025D8E1B8 000000002567D480, rpc connection is released
08/27 10:38:28.722000 0x00005d98 TMR TSC timer[id=9, fp=00007FFA8B807570, param=0000000025D8E1B8] execution end.
08/27 10:38:28.722000 0x00005d98 TMR TSC timer[id=12, fp=00007FFA8B807410, param=0000000025996CD0] execution start.
08/27 10:38:28.722000 0x00005d98 RPC TSC 000000002567D480, connection error happens
08/27 10:38:28.722000 0x00005d98 TSC 000000002567D480 SQL cmd:connect, code:Unable to establish connection rspLen:0
08/27 10:38:28.722000 0x00005d98 RPC free mem: 0000000025996CD0
08/27 10:38:28.722000 0x00005d98 TMR TSC timer[id=12, fp=00007FFA8B807410, param=0000000025996CD0] execution end.
08/27 10:38:28.722000 0x000043f4 TSC 000000002567D480 start to free sql object
08/27 10:38:28.722000 0x000043f4 TSC 000000002567D480 start to free local reducer
08/27 10:38:28.722000 0x000043f4 TSC 000000002567D480 local reducer has been freed, abort
08/27 10:38:28.722000 0x000043f4 TSC 000000002567D480 SqlObj is freed by app, qhandle is null
08/27 10:38:28.722000 0x000043f4 TMR timer[id=0] does not exist
08/27 10:38:28.722000 0x000043f4 RPC TSC TCP client is stopped
08/27 10:38:28.722000 0x00008e48 RPC TSC UDP socket was closed, exiting(No error)
08/27 10:38:28.722000 0x000043f4 RPC TSC UDP is stopped
08/27 10:38:28.723000 0x000043f4 RPC ERROR TSC, failed to create eventfd(File exists)
08/27 10:38:28.726000 0x00007878 RPC TSC TCP thread get stop event, exiting...
08/27 10:38:28.726000 0x000043f4 RPC TSC TCP client is cleaned up
08/27 10:38:28.726000 0x000043f4 RPC TSC UDP is cleaned up
08/27 10:38:28.726000 0x000043f4 RPC TSC rpc is closed
08/27 10:38:28.726000 0x000043f4 TMR TSC timer[id=11, fp=00007FFA8B80BF50, param=000000000142D860] is cancelled.
08/27 10:38:28.726000 0x000043f4 TMR TSC timer controller is cleaned up.
08/27 10:38:28.726000 0x000043f4 UTL pool:0000000001426640 is cleaned
08/27 10:38:28.726000 0x000043f4 RPC TSC rpc resources are released
08/27 10:38:28.726000 0x000043f4 TSC 000000000144DE30 DB connection is closed, dnodeConn:000000000143C390
08/27 10:38:28.726000 0x000043f4 JNI ERROR jobj:000000000351EFE8, conn:0000000000000000, connect to database failed, host=pre-hbase-04, user=root, dbname=log, port=6030
08/27 10:38:28.728000 0x000043f4 JNI ERROR jobj:000000000351EF68, connection is closed
08/27 10:38:28.737000 0x000091c4 TMR TSC adding expired timer[id=10, fp=00007FFA8B7F9BA0, param=0000000000000000] to queue.
08/27 10:38:28.737000 0x000091c4 TMR timer[id=10] has been added to queue.
08/27 10:38:28.737000 0x00005d98 TMR TSC timer[id=10, fp=00007FFA8B7F9BA0, param=0000000000000000] execution start.
08/27 10:38:28.737000 0x00005d98 TMR TSC timer[id=13, fp=00007FFA8B7F9BA0, param=0000000000000000] started
08/27 10:38:28.737000 0x00005d98 TMR TSC timer[id=10, fp=00007FFA8B7F9BA0, param=0000000000000000] execution end.

**Comment by guanshengliang** [comment]
telnet 一下 pre-hbase-04 可能是 fqdn没有配置

**Comment by zhangzl0119** [comment]
![image](https://user-images.githubusercontent.com/32055976/91378108-39a07200-e852-11ea-8073-b14cf6eb7e90.png)
是可以的

**Comment by guanshengliang** [comment]
没指定端口吧

**Comment by zhangzl0119** [comment]
![image](https://user-images.githubusercontent.com/32055976/91378325-ba5f6e00-e852-11ea-9f35-994bf12098a7.png)
指定了6030端口

**Comment by guanshengliang** [comment]
你指定端口和未指定端口的telnet截图并不相同，我也不懂telnet的具体使用。但从日志上看，就是服务端没有收到客户端的响应。您可以自己想其他办法，看看两者为何通过fqdn连接时网络不通。

另外，为了确认这个问题。您可以重置数据库，使用ip而不是fqdn来启动TDengine。方法是
1. systemctl stop taosd
2. rm -rf /var/lib/taos
3. vi /etc/taos/taos.cfg，在其中增加一行
firstEp 172.16.16.220:6030
fqdn 172.16.16.220
4. systemctl restart taosd
5. linux机器上，taos连接后，show dnodes，看看fqdn是不是变为了172.16.16.220
6. windows机器上，用taos -h 172.16.16.220 试一下

**Comment by zhangzl0119** [comment]
![image](https://user-images.githubusercontent.com/32055976/91381811-d6ffa400-e85a-11ea-9954-e71aed65753a.png)
![image](https://user-images.githubusercontent.com/32055976/91381831-e1ba3900-e85a-11ea-8d9a-0a13cbdf214b.png)

**Comment by liuyq-617** [comment]
加一下我微信吧，13121752171。我远程连接检查一下吧

**Comment by zhangzl0119** [comment]
现在解决了这个问题，是云服务安全组的限制，没开放udp端口。

**Comment by guanshengliang** [comment]
好的，那这边就关闭issue了
