### ISSUE TITLE
 Can Boolean data achieve aggregate analysis?

### ISSUE THREAD

**Issue by jin522** [taosdata/TDengine#3252]
在建表时，有一个value字段定义为bool型，往表里写入数据时，value字段默认存储true或false，TDengine支持设置存储0或1吗？或者说，TDengine sql中有没有关键字可以实现支持对bool型字段做avg，sum等聚合分析？

**Comment by jin522** [comment]
我尝试对bool类型字段求平均：
select avg(value) from train_signal where v_id=7500 and ts>1598313600000 and ts <1598486400000;
sql执行报错：
invalid SQL: not support column types

**Comment by hjxilinx** [comment]
bool 类型为何要计算平均数呢？

**Comment by hjxilinx** [comment]
This issue was closed because it has been inactive for too many days.
