### ISSUE TITLE
 Recommendations on JDBC

### ISSUE THREAD

**Issue by zwllxs** [taosdata/TDengine#3264]
jdbc驱动，
1: 建议时间返回格式化后的，如2020-08-20 17:22:50.000，和命令终端一样。
目前jdbc驱动返回的是毫秒数，时间列，无法和众多java框架无缝整合
2:建议TSDBConnection.java中，将如下方法也实现一下:

	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
		throw new SQLException(TSDBConstants.UNSUPPORT_METHOD_EXCEPTIONZ_MSG);
	}
因为大多数人的实际项目，在执行语句时，都会执行到这方法里。否则需要显示关闭返回主键，然而这个重要信息，官网并未标明，导致会有很多人容易踩坑。

**Comment by hjxilinx** [comment]
谢谢您的建议。JDBC的问题修复您提到的问题。

命令行终端中的日期输出也是将unix timestamp 转换为字符串，后台数据库并没有处理这个问题。我们在后续的版本中会提供原生的自定义日期格式输出的定义。例如：
```
select toData(data_format, ts) from table_name;
```
