### ISSUE TITLE
make install 时如何只保留最简的二进制文件

### ISSUE THREAD

**Issue by anjia0532** [taosdata/TDengine#3268]
我尝试基于ubuntu构建docker，ubuntu 20.04基础镜像27M左右，但是令人沮丧的是，构建出来的，镜像经过各种优化最终大于 58M

![image](https://user-images.githubusercontent.com/15098916/91436063-f669f180-e899-11ea-8325-ae4c1d6aa85a.png)

经过排查发现主要是执行 `make install` 将一些用不到二进制打到了 `/usr/local/taos/bin`下，大约30多M，而官方镜像只保留了5个文件  `remove.sh,set_core.sh,taos,taosd,taosdemo,tarbitrator` （大约4-5M）。

虽然可以使用 `rm -rf /usr/local/taos/bin/{cqtest,demo,reconnect_subscriber,rsclient,simple_subscriber,syncServer,taosClient,tsim,createNormalTable,rclient,rserver,simple_publisher,syncClient,taosServer,tdengineTest,waltest}` 进行瘦身但是无疑是很笨重的方式。

按照二进制名字搜索得到，大多是通过 `TD_LINUX` 变量控制的

https://github.com/taosdata/TDengine/blob/6554a5356d54e6963c8b9883412819ce7010db2b/src/rpc/test/CMakeLists.txt#L6

而 `TD_LINUX` 是在构建平台是LINUX就会自动设置为true

https://github.com/taosdata/TDengine/blob/6c95affeea6430e2b30585bdf60d22eabf60500b/cmake/platform.inc#L34

所以，是有文档中 (例如 `make install`) 没提到的隐藏参数控制的么？

或者构建的时候可以关闭 `test` 么？(因为大多是在 `/src/*/test/CMakeLists.txt` 路径下)

**Comment by sangshuduo** [comment]
请参考网上 Docker 镜像瘦身方法

**Comment by anjia0532** [comment]
明显不是docker镜像瘦身问题，基础镜像27M，make build 和make install后的 `/usr/local/taos/bin/` 目录占用31M ,官方的镜像 `/usr/local/taos/bin/` 4-5M ，我提的issues上这些都说了啊  [捂脸]

**Comment by sangshuduo** [comment]
官方dockerfile也开源了，您可以参考一下

**Comment by anjia0532** [comment]
你们官方dockerfile，你有看过么？这个压缩包根本不是github releases 的tar.gz ,谁也不知道从哪弄的，很可能是自己本地 make build . 后，手动裁剪完，然后再自己搞的一个包。

https://github.com/taosdata/TDengine/blob/4cdcaba9246efac1e18d9b4e37789537c1c168c3/packaging/docker/Dockerfile#L5

但是我想知道如何设置make 的构建参数，生成 tao.tar.gz（最小化的二进制包），也就是你们开源的dockerfile的 `COPY tdengine.tar.gz /root/` 中的 `tdengine.tar.gz`

最终是通过 下面这个脚本进行安装的。
https://github.com/taosdata/TDengine/blob/4cdcaba9246efac1e18d9b4e37789537c1c168c3/packaging/tools/install.sh#L545-L550

**Comment by anjia0532** [comment]
找到办法了，用 `release.sh`

**Comment by anjia0532** [comment]
真费劲
