### ISSUE TITLE
aarch64平台-cent7.5 数据库无法创建问题

### ISSUE THREAD

**Issue by dvt0551** [taosdata/TDengine#327]
修改CMakeList.txt 因为arrch64无法支持mse42和-m align-double -m align-string的选择
SET(COMMON_FLAGS "-std=gnu99 -Wall -fPIC -mstrict-align -Wno-char-subscripts   -D_FILE_OFFSET_BITS=64 -D_LARGE_FILE")
编译通过：发现日志
08/12 10:02:38.564999 ffffb34cf200 MON starting to initialize monitor service ..
08/12 10:02:38.565184 ffffa776f200 MND login from:d7190a0a:42914
08/12 10:02:38.565225 ffffa674f200 MND invalid db option commitLog: 255
08/12 10:02:38.565337 ffffb458f200 ERROR MON monitor:0xffff9c0008c0, sql failed, code:-45, create database if not exists log replica 1 days 10 keep 30 rows 1024 cache 2048 ablocks 2 tblocks 32 tables 32 precision 'us'
无法建立数据库 包括create db 都不行，我使用GBK字符集，locale也是zh_CN.GBK
编译有很多警告。

**Comment by hzcheng** [comment]
目前我们不支持这个平台的编译和运行。后面我们会支持的。

**Comment by dvt0551** [comment]
计划什么时候发行aarch64版本

**Comment by hzcheng** [comment]
估计在年底之前

**Comment by dvt0551** [comment]
谢谢
