### ISSUE TITLE
在log 表中的 dn1 中  TSDB_DATA_TYPE_TIMESTAMP类型返回数据跟其他表返回的不一致的问题

### ISSUE THREAD

**Issue by maikebing** [taosdata/TDengine#3270]
服务端版本: docker 版本 v2.0.1.1 
客户端版本 v2.0.1.1 

```
use log 
 SELECT * FROM dn1; 
```
![image](https://user-images.githubusercontent.com/3445167/91442535-93318c80-e8a4-11ea-9a45-c91838ab224a.png)
时间戳: 1598527937775901

但是 在其他表中：
![image](https://user-images.githubusercontent.com/3445167/91442623-b5c3a580-e8a4-11ea-8cfe-b60860759500.png)

也就是时间戳 1598527937775  实际上除以了 1000  

类型都是  TSDB_DATA_TYPE_TIMESTAMP

**Comment by maikebing** [comment]
fix  https://github.com/maikebing/Maikebing.EntityFrameworkCore.Taos/commit/ec345be628273b6a2e015012c6ca52d4c3815076

**Comment by hjxilinx** [comment]
您执行 show databases。能够看到数据库的时间精度。Log 库的时间精度是 微秒。普通的库如果不指定时间精度默认是毫秒。

API 中有一个 API 让用户判断当前结果集时间戳是毫秒还是微秒。
```
taos_result_precision
```

**Comment by maikebing** [comment]
我看的taos_result_precision 返回的结果都是 0

**Comment by hjxilinx** [comment]
#define TSDB_TIME_PRECISION_MILLI 0
#define TSDB_TIME_PRECISION_MICRO 1
#define TSDB_TIME_PRECISION_NANO  2

定义在 taosdef.h 文件中，后面要挪到 taos.h 中。

**Comment by hjxilinx** [comment]
您可以看一下 ```shellEngine.c`` 535行的函数： printField。控制 taos 打印输出的，对于不同的时间分辨率将时间戳列解析为字符串并打印到屏幕输出。
