### ISSUE TITLE
taosd cannot start

### ISSUE THREAD

**Issue by eltonchaw7** [taosdata/TDengine#3272]
08/27 21:39:19.552671 0x7fab7fe1d0 TDB ERROR vgId:3 table stock_600261 tid 219 uid 3298549235957 timestamp is out of range! now 1598535559552 minKey 1283175559552 maxKey 1598708359552
08/27 21:39:19.573512 0x7fab7fe1d0 TDB ERROR vgId:3 table stock_600276 tid 230 uid 3298549956864 timestamp is out of range! now 1598535559573 minKey 1283175559573 maxKey 1598708359573
08/27 21:39:19.577966 0x7fab7fe1d0 TDB ERROR vgId:3 table stock_600281 tid 235 uid 3298550284549 timestamp is out of range! now 1598535559577 minKey 1283175559577 maxKey 1598708359577
08/27 21:39:19.594353 0x7fab7fe1d0 TDB ERROR vgId:3 table stock_600293 tid 246 uid 3298551005456 timestamp is out of range! now 1598535559594 minKey 1283175559594 maxKey 1598708359594
08/27 21:39:19.603143 0x7fab7fe1d0 TDB ERROR vgId:3 table stock_600298 tid 249 uid 3298551202067 timestamp is out of range! now 1598535559603 minKey 1283175559603 maxKey 1598708359603
08/27 21:39:19.616165 0x7fab7fe1d0 TDB ERROR vgId:3 table stock_600306 tid 256 uid 3298551660826 timestamp is out of range! now 1598535559616 minKey 1283175559616 maxKey 1598708359616
08/27 21:39:19.623183 0x7fab7fe1d0 TDB ERROR vgId:3 table stock_600309 tid 259 uid 3298551857437 timestamp is out of range! now 1598535559623 minKey 1283175559623 maxKey 1598708359623
08/27 21:39:19.634549 0x7fab7fe1d0 TDB ERROR vgId:3 table stock_600315 tid 264 uid 3298552185122 timestamp is out of range! now 1598535559634 minKey 1283175559634 maxKey 1598708359634
08/27 21:39:19.644009 0x7f7f7ee1d0 TDB vgId:3 start to commit! keyFirst 1598405100000 keyLast 1598511622000 numOfRows 837636

**Comment by sangshuduo** [comment]
请提供版本信息和重现步骤

**Comment by hjxilinx** [comment]
您好，
日志显示，您写入的数据时间跨度超过了保存的时间周期。数据库默认保存10年。报错的时间戳是：
minKey 1283175559594 maxKey 1598708359594
时间范围是：2010/8/30 21:39:19 - 2020/8/29 21:39:19。

解决这个问题，你需要修改一下数据库的最大保留时间长度。 @eltonchaw7 

DB 的数据保存周期，您可以通过 SHOW DATABASE 查看到。
