### ISSUE TITLE
please help on windows compile error

### ISSUE THREAD

**Issue by x1234521** [taosdata/TDengine#3274]
https://www.taosdata.com/blog/2020/01/06/1093.html
按照此博客操作，最后一步make时报错，不知道是缺少什么依赖组件，还是什么问题。

![image](https://user-images.githubusercontent.com/34298043/91511708-efcb9080-e912-11ea-94a3-f8b7b09a854c.png)

**Comment by plum-lihui** [comment]
不好意思，您贴的图片我们无法正常显示，看不到问题。请拷贝文字贴上吧。@x1234521

**Comment by x1234521** [comment]
https://user-images.githubusercontent.com/34298043/91511708-efcb9080-e912-11ea-94a3-f8b7b09a854c.png

=========================================
PS D:\TDengine\debug> make
"C:/Program Files/CMake/bin/cmake.exe" -SD:/TDengine -BD:/TDengine/debug --check-build-system CMakeFiles/Makefile.cmake 0
"C:/Program Files/CMake/bin/cmake.exe" -E cmake_progress_start D:/TDengine/debug/CMakeFiles D:/TDengine/debug//CMakeFiles/progress.marks
/usr/bin/make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/d/TDengine/debug'
/usr/bin/make  -f deps/pthread/CMakeFiles/pthread.dir/build.make deps/pthread/CMakeFiles/pthread.dir/depend
make[2]: Entering directory '/d/TDengine/debug'
"C:/Program Files/CMake/bin/cmake.exe" -E cmake_depends "Unix Makefiles" D:/TDengine D:/TDengine/deps/pthread D:/TDengine/debug D:/TDengine/debug/deps/pthread D:/TDengine/debug/deps/pthread/CMakeFiles/pthread.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/d/TDengine/debug'
/usr/bin/make  -f deps/pthread/CMakeFiles/pthread.dir/build.make deps/pthread/CMakeFiles/pthread.dir/build
make[2]: Entering directory '/d/TDengine/debug'
[  1%] Building C object deps/pthread/CMakeFiles/pthread.dir/pthread.c.obj
cd D:/TDengine/debug/deps/pthread && C:/msys64/mingw64/bin/cc.exe -DPTW32_BUILD -DPTW32_STATIC_LIB -DUSE_LIBICONV -DWINDOWS -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_MBCS -D_M_X64 -D_TD_GO_DLL_ -D_TD_WINDOWS_64 -D__CLEANUP_C @CMakeFiles/pthread.dir/includes_C.rsp -O3 -DNDEBUG   -std=gnu11 -o CMakeFiles/pthread.dir/pthread.c.obj -c D:/TDengine/deps/pthread/pthread.c
In file included from D:/TDengine/deps/MsvcLibX/include/msvcTime.h:20,
                 from D:/TDengine/deps/pthread/pthread.h:231,
                 from D:/TDengine/deps/pthread/pthread.c:39:
**D:/TDengine/deps/MsvcLibX/include/msvclibx.h:28:2: error: #error The msvclibx library is designed for use with the Microsoft Visual C/C++ tools only.**
   28 | #error The msvclibx library is designed for use with the Microsoft Visual C/C++ tools only.
      |  ^~~~~
In file included from D:/TDengine/deps/MsvcLibX/include/msvcTime.h:22,
                 from D:/TDengine/deps/pthread/pthread.h:231,
                 from D:/TDengine/deps/pthread/pthread.c:39:
C:/msys64/mingw64/x86_64-w64-mingw32/include/winsock2.h:15:2: warning: #warning Please include winsock2.h before windows.h [-Wcpp]
   15 | #warning Please include winsock2.h before windows.h
      |  ^~~~~~~
In file included from D:/TDengine/deps/MsvcLibX/include/msvcTime.h:36,
                 from D:/TDengine/deps/pthread/pthread.h:231,
                 from D:/TDengine/deps/pthread/pthread.c:39:
D:/TDengine/deps/MsvcLibX/include/sys\msvcTime.h:69:8: error: redefinition of 'struct timespec'
   69 | struct timespec {
      |        ^~~~~~~~
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/time.h:300,
                 from D:/TDengine/deps/MsvcLibX/include/msvcTime.h:23,
                 from D:/TDengine/deps/pthread/pthread.h:231,
                 from D:/TDengine/deps/pthread/pthread.c:39:
C:/msys64/mingw64/x86_64-w64-mingw32/include/sys/timeb.h:91:8: note: originally defined here
   91 | struct timespec {
      |        ^~~~~~~~
In file included from D:/TDengine/deps/pthread/pthread.h:231,
                 from D:/TDengine/deps/pthread/pthread.c:39:
D:/TDengine/deps/MsvcLibX/include/msvcTime.h:42:5: error: conflicting types for 'clock_gettime'
   42 | int clock_gettime(clockid_t clock_id, struct timespec *tp);
      |     ^~~~~~~~~~~~~
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/time.h:308,
                 from D:/TDengine/deps/MsvcLibX/include/msvcTime.h:23,
                 from D:/TDengine/deps/pthread/pthread.h:231,
                 from D:/TDengine/deps/pthread/pthread.c:39:
C:/msys64/mingw64/x86_64-w64-mingw32/include/pthread_time.h:88:28: note: previous declaration of 'clock_gettime' was here
   88 | int __cdecl WINPTHREAD_API clock_gettime(clockid_t clock_id, struct timespec *tp);
      |                            ^~~~~~~~~~~~~
In file included from D:/TDengine/deps/pthread/sched.h:115,
                 from D:/TDengine/deps/pthread/pthread.h:314,
                 from D:/TDengine/deps/pthread/pthread.c:39:
D:/TDengine/deps/MsvcLibX/include/sys/msvcTypes.h:55:15: error: conflicting types for 'pid_t'
   55 | typedef DWORD pid_t;        /* Windows defines it as a DWORD */
      |               ^~~~~
In file included from D:/TDengine/deps/MsvcLibX/include/sys/msvcTypes.h:23,
                 from D:/TDengine/deps/pthread/sched.h:115,
                 from D:/TDengine/deps/pthread/pthread.h:314,
                 from D:/TDengine/deps/pthread/pthread.c:39:
C:/msys64/mingw64/x86_64-w64-mingw32/include/sys/types.h:68:16: note: previous declaration of 'pid_t' was here
   68 | typedef _pid_t pid_t;
      |                ^~~~~
In file included from D:/TDengine/deps/pthread/sched.h:115,
                 from D:/TDengine/deps/pthread/pthread.h:314,
                 from D:/TDengine/deps/pthread/pthread.c:39:
D:/TDengine/deps/MsvcLibX/include/sys/msvcTypes.h:92:13: error: conflicting types for 'mode_t'
   92 | typedef int mode_t;
      |             ^~~~~~
In file included from D:/TDengine/deps/MsvcLibX/include/sys/msvcTypes.h:23,
                 from D:/TDengine/deps/pthread/sched.h:115,
                 from D:/TDengine/deps/pthread/pthread.h:314,
                 from D:/TDengine/deps/pthread/pthread.c:39:
C:/msys64/mingw64/x86_64-w64-mingw32/include/sys/types.h:77:17: note: previous declaration of 'mode_t' was here
   77 | typedef _mode_t mode_t;
      |                 ^~~~~~
make[2]: *** [deps/pthread/CMakeFiles/pthread.dir/build.make:86: deps/pthread/CMakeFiles/pthread.dir/pthread.c.obj] Error 1
make[2]: Leaving directory '/d/TDengine/debug'
make[1]: *** [CMakeFiles/Makefile2:939: deps/pthread/CMakeFiles/pthread.dir/all] Error 2
make[1]: Leaving directory '/d/TDengine/debug'
make: *** [Makefile:174: all] Error 2

**Comment by x1234521** [comment]
麻烦您帮忙看一下，挺着急的，感谢！@plum-lihui

**Comment by x1234521** [comment]
@plum-lihui 麻烦帮忙看一下呗？
@sangshuduo

**Comment by plum-lihui** [comment]
我们的指导文档中，是使用nmake，不是make。
你再试试。

**Comment by x1234521** [comment]
![image](https://user-images.githubusercontent.com/34298043/91787632-e9a02180-ec3c-11ea-95ff-71edc3a01cdb.png)

https://www.taosdata.com/blog/2020/01/06/1093.html
是我看错了文档？

**Comment by x1234521** [comment]
你说的指导文档，是哪个文件，方便发个链接给我么，我是通过你们官方博客的文章操作的。

**Comment by plum-lihui** [comment]
哦，你是编译go的windows驱动？那是我理解错了，以为是编译TDengine的taos客户端。

**Comment by x1234521** [comment]
好的，感谢。
