### ISSUE TITLE
if data type affect insert time？

### ISSUE THREAD

**Issue by jin522** [taosdata/TDengine#3276]
**Performance Issue** 
I create a super-table A include 10000 sub-tables,and this super-table have one column which called value is defined as double. also, i create another super-table B have the same columns ,but colume value is defined as int. 
then, i insert the same data into A and B by jdbc and calculate the time.  finally, I find B spend less time than A, is it related to data type?

TDengine version 2.0.0.1
taos-jdbc version 2.0.0.0

**Comment by sangshuduo** [comment]
I believe it is.
