### ISSUE TITLE
BI工具连接数据库报错TDengine Error: failed to connect to server

### ISSUE THREAD

**Issue by hhhyb** [taosdata/TDengine#328]
![报错](https://user-images.githubusercontent.com/42267833/62849857-d2ca1c80-bd13-11e9-9123-612e3a754a2a.png)

**Comment by johnnyhou327** [comment]
@hhhyb 有没有具体的BI连接日志？taos客户端日志？

**Comment by hhhyb** [comment]
稍等啊，我这边好像是连上了



------------------ 原始邮件 ------------------
发件人: "johnnyhou327"<notifications@github.com>; 
发送时间: 2019年8月12日(星期一) 下午3:17
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>; 
抄送: "拥抱."<1396988252@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [taosdata/TDengine] BI工具连接数据库报错TDengine Error: failed to connect to server (#328)




@hhhyb 有没有具体的BI连接日志？taos客户端日志？

**Comment by hhhyb** [comment]
您好，我现在是连接成功了，但是那个taosdemo中每张表的数据量还是太少了，然后我想把t1表的数据往t0表里面多加几次让他数据量在大一点，我在taos里面执行insert into t0 values(select * from t1);这样的执行不了吗


------------------ 原始邮件 ------------------
发件人: "johnnyhou327"<notifications@github.com>;
发送时间: 2019年8月12日(星期一) 下午3:17
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
抄送: "拥抱."<1396988252@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [taosdata/TDengine] BI工具连接数据库报错TDengine Error: failed to connect to server (#328)




@hhhyb 有没有具体的BI连接日志？taos客户端日志？

**Comment by fangpanpan** [comment]
目前tdengine不支持nesty query，如果您想增加每张表的数据量，可以使用参数-n, -n 后面接的就是每张表里记录的行数. 比如taosdemo -n 100000

**Comment by hhhyb** [comment]
![log](https://user-images.githubusercontent.com/42267833/62920933-bb556700-bdd9-11e9-96f3-dd4fed87cd68.png)
这是我的日志，我的csv文件就在指定目录下，但是数据就是导不进数据表里面

**Comment by linzhenyao** [comment]
failed to connect to server  同问这个是怎么解决的，我一直卡在这里连不上

**Comment by hhhyb** [comment]
如果是windows版本连接Linux的话，在windows上安装一个windows版本的客户端。如果是服务器连接服务器，在连接的服务器上面也装一个taos数据库，就能连接上了，我的就是这样就解决的。




------------------ 原始邮件 ------------------
发件人: "linzhenyao"<notifications@github.com>; 
发送时间: 2019年9月26日(星期四) 下午4:52
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>; 
抄送: "拥抱."<1396988252@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [taosdata/TDengine] BI工具连接数据库报错TDengine Error: failed to connect to server (#328)




failed to connect to server  同问这个是怎么解决的，我一直卡在这里连不上
