### ISSUE TITLE
ailed to parse rule: invalid character 'r' looking for beginning of value

### ISSUE THREAD

**Issue by hb990208** [taosdata/TDengine#3286]
![image](https://user-images.githubusercontent.com/59379060/91547929-3511b180-e957-11ea-9c48-097824ce0790.png)

在使用TDengine告警模块中，按照博客中的alert.cfg设定配置，以及rule告警规则设定，最后提示这个错误，找半天无从下手
https://www.taosdata.com/blog/2020/04/14/1438.html

**Comment by localvar** [comment]
应该是您的规则中有拼写错误，方便的话请贴一下规则。

**Comment by hb990208** [comment]
解决了
