### ISSUE TITLE
客户端只能连接到集群(三个dnode)的一个节点的服务器（网络原因)，需要能能够操作库  如果配置或好的解决方案

### ISSUE THREAD

**Issue by wuyupengcool** [taosdata/TDengine#3294]
08/29 18:55:11.461000 0x00005b84 UTL ERROR failed get the ip address, fqdn:xxx-0003, code:11001, reason:不知道这样的主机。 
08/29 18:55:11.461000 0x00005b84 RPC ERROR TSC, failed to resolve FQDN:xxx-0003
08/29 18:55:11.461000 0x00005b84 RPC ERROR TSC 000001586B598EC0, failed to set up connection(Unexpected generic error in RPC)
08/29 18:55:11.484000 0x00005b84 RPC WARN TSC 000001586B5A1910 000001586B598EC0, too many redirects, quit
08/29 18:55:11.486000 0x00000984 RPC ERROR TSC, failed to create eventfd(No such file or directory)

**Comment by jtao1735** [comment]
这个错误消息来看，报错的这台机器无法解析 xxx-0003, 因此你可以配置一下hosts文件，将xxx-0003以及相应的IP地址添加进去

**Comment by wuyupengcool** [comment]
陶老师 这个场景是当前客户端机器只能访问到001节点 ，002 003 不让连接   集群在内网  网闸只允许客户端访问其中一台机器
