### ISSUE TITLE
Bailongma编译报错问题

### ISSUE THREAD

**Issue by aybthebest** [taosdata/TDengine#3298]
go version
go version go1.15 linux/amd64
# 安装依赖
go get github.com/gogo/protobuf/proto
go get github.com/golang/snappy
go get github.com/prometheus/common/model
go get github.com/taosdata/driver-go/taosSql
go get github.com/prometheus/prometheus/prompb
# 开始编译
go build
cd /home/stefan/myapp/linux/Bailongma-master/blm_prometheus
# _/home/stefan/myapp/linux/Bailongma-master/blm_prometheus
./server.go:300:21: cannot use ts (type prompb.TimeSeries) as type *prompb.TimeSeries in argument to HandleStable
./server.go:752:15: cannot use lbs (type []*prompb.Label) as type []prompb.Label in assignment
./server.go:754:19: cannot use ts (type []*prompb.TimeSeries) as type []prompb.TimeSeries in assignment

Bailongma编译报错，请问如何解决？

**Comment by liu0x54** [comment]
是取的哪个路径的源码？
git clone  https://www.github.com/taosdata/Bailongma.git
用这个项目试试

**Comment by liu0x54** [comment]
此外，可以在Bailongma的路径下执行go mod init bailongam/m/v2 ，用go mod 来管理依赖关系

**Comment by aybthebest** [comment]
用新的go mod命令已解决，谢谢🙏
