### ISSUE TITLE
关于数据的原子性

### ISSUE THREAD

**Issue by augustus0725** [taosdata/TDengine#33]
简单过了下代码,  库在做insert update之类的操作好像都没有日志相关的操作, 这个是怎么保证原子性的?

**Comment by jtao1735** [comment]
我们有commit log, 请看vnodeCommit.c. 原子性操作是保证的，因为利用了物联网数据的特点，一个设备一张表，而数据源是唯一的，因此至多一个写的操作。

**Comment by herocsl** [comment]
顺便对”对一个设备一张表“有点疑问？请问表的第一个字段是timestamp类型，且系统默认是主键。也是说业务上用的时候。一个设备对应一张表对吗？那如果一毫秒产生2条数据。该如何怎么区分呢？

**Comment by herocsl** [comment]
”首个字段“等同于”关系数据库中的自增主键“吗？如果要存eventTime，单独加一个时间列作为存储？

**Comment by zhouyihaocc** [comment]
另外请问如何保证在远程传输数据时服务器接收到的数据是严格按照时间顺序来的呢？如果服务器收到的数据是乱序的，那么有什么机制可以恢复吗？

**Comment by yyrdl** [comment]
> 另外请问如何保证在远程传输数据时服务器接收到的数据是严格按照时间顺序来的呢？如果服务器收到的数据是乱序的，那么有什么机制可以恢复吗？

不知道有没有全局时钟同步，或者是设计时就没有设计严格的时序保证，还是先点star为敬　!

**Comment by willove** [comment]
> 另外请问如何保证在远程传输数据时服务器接收到的数据是严格按照时间顺序来的呢？如果服务器收到的数据是乱序的，那么有什么机制可以恢复吗？

时序数据库写入数据的时候需要提供一个时间戳作为主键，所以理论上写入数据库的时间先后并不会影响数据的先后顺序，因为数据已经自己贴上了时间的标签，谁先谁后已经定好了。这也是时序数据库的特色。

**Comment by willove** [comment]
> 顺便对”对一个设备一张表“有点疑问？请问表的第一个字段是timestamp类型，且系统默认是主键。也是说业务上用的时候。一个设备对应一张表对吗？那如果一毫秒产生2条数据。该如何怎么区分呢？

我看官网文档说可以支持微秒级的时间戳，还有引入超级表能够解决多表数据的问题。多看看文档，不难。

**Comment by herocsl** [comment]
> > 顺便对”对一个设备一张表“有点疑问？请问表的第一个字段是timestamp类型，且系统默认是主键。也是说业务上用的时候。一个设备对应一张表对吗？那如果一毫秒产生2条数据。该如何怎么区分呢？
> 
> 我看官网文档说可以支持微秒级的时间戳，还有引入超级表能够解决多表数据的问题。多看看文档，不难。

>嗯，是可以通过别的方式解决。但是如果用一张表,insert into ..的时候，首个字段就不该有客户端传入。客户端传入就会导致插入失败(毫秒内产生2个字段，主键冲突)，所以我的意思是使用过程中，该字段由服务端操作(如使用now()函数，因为该列是自增类型列)。客户端要插入的eventTime，自己定义新的列进行存储。

**Comment by willove** [comment]
> > > 顺便对”对一个设备一张表“有点疑问？请问表的第一个字段是timestamp类型，且系统默认是主键。也是说业务上用的时候。一个设备对应一张表对吗？那如果一毫秒产生2条数据。该如何怎么区分呢？
> > 
> > 
> > 我看官网文档说可以支持微秒级的时间戳，还有引入超级表能够解决多表数据的问题。多看看文档，不难。
> 
> > 嗯，是可以通过别的方式解决。但是如果用一张表,insert into ..的时候，首个字段就不该有客户端传入。客户端传入就会导致插入失败(毫秒内产生2个字段，主键冲突)，所以我的意思是使用过程中，该字段由服务端操作(如使用now()函数，因为该列是自增类型列)。客户端要插入的eventTime，自己定义新的列进行存储。

可能你对时序数据库还有一些误解，和关系型数据库还是有些差别的。时序数据库主要分时序列、维度列和数值列三块。从关系型数据库的角度看，时序列和维度列可以看做这条数据的联合主键。那个服务端取得的时间应该丢弃掉或者存入数值列中，主要需要提高事件发生的时间精度。

**Comment by zhangchi0923** [comment]
> 我们有commit log, 请看vnodeCommit.c. 原子性操作是保证的，因为利用了物联网数据的特点，一个设备一张表，而数据源是唯一的，因此至多一个写的操作。

关于文档中“无锁写入”我有一点疑问，例如，对于v0f1804.*文件组，它存储了10天（默认）的属于该vnode的所有表的数据块，而且数据块是按时间主键排列的，那么不同表的数据块是穿插排列的。如果我上面的理解正确的话，那么虽然每张表只有一个写入源，但是属于同一个vnode的多张表并发写入的时候相当于并发修改v0f1804.data文件，这样的话还能够“无锁写入”吗？

**Comment by dingziyang** [comment]
@zhangchi0923 文档里说了，对于如果vnode1里面存储的数据最大时序是M, 则之后的vnode2里面的最小时序一定大于M，所以在vnode与vnode之间也不存在 “同一条数据并发写”

**Comment by zhangchi0923** [comment]
> @zhangchi0923 文档里说了，对于如果vnode1里面存储的数据最大时序是M, 则之后的vnode2里面的最小时序一定大于M，所以在vnode与vnode之间也不存在 “同一条数据并发写”

我的问题是同一个vnode中不同的表可能同时都有数据写入，他们的数据块落盘后是穿插的，所以我以为data文件存在并发写入的情况，但作者在另一个issue里提醒我了，数据是先放在缓存里的，然后再落盘。可以在缓存里排序再落盘，这样就不是并发写入data文件了。

**Comment by c-atom** [comment]
大致可以这样理解
tdengine必须采用timestamp作为主键，默认为毫秒精度，所以一张表每秒最多存1000条记录。
如果配置为微秒精度（需要修改tdengine配置），一张表每秒最多存100w条记录。

如果业务对10毫秒或者微秒级别的时间精度要求不高，则可以自己在这个时间精度范围内，自己控制一个小范围的自增序列（如毫秒+seq）作为主键。

如果业务存在时间一样且不可避免的情况，只能采用“超级表STable” 😄
