### ISSUE TITLE
taosMsleep的精确度

### ISSUE THREAD

**Issue by 375C** [taosdata/TDengine#330]
有个地方比较疑惑，就是taosMsleep这个函数的实现。
在linux 4.4.0版本上8CPU机器上测试，对长延时（低精度，50000us以上）的睡眠，nanosleep的表现要明显好于select,对短延迟（高精度，50000us以下）两者差别基本一致，都是60us左右的误差。请问采用select方案主要是考虑了哪些方面？是考虑系统中断问题还是多平台的兼容性问题？

**Comment by guanshengliang** [comment]
Sleep函数在TDengine的应用很少，对睡眠的精度没有特别要求，考虑到Select的性能更好，采用Select代替Sleep。
参考这篇文章
```
https://blog.csdn.net/dongyu_1989/article/details/78968261
```

**Comment by 375C** [comment]
谢谢，了解了。这个文章以前读到过， 文中提到的nanosleep的两个问题，时间片丢失和优先级问题导致的不准问题，感觉在现在的内核主频和调度策略下，影响会比较小；中断问题，确实是一个需要单独考虑的地方。
您提到的性能好，有具体的测试数据吗？个人感觉select方案只是对中断友好。
