### ISSUE TITLE
客户端连接报错

### ISSUE THREAD

**Issue by hitits** [taosdata/TDengine#3300]
08/31 11:12:27.304937 0x7fc35b7f1700 MND user:monitor, failed to auth user, reason:System not ready
08/31 11:12:27.304948 0x7fc35b7f1700 DND user:monitor, send auth msg to mnode
08/31 11:12:27.305085 0x7fc35b7f1700 DND user:monitor, auth msg received from mnode
08/31 11:12:27.305104 0x7fc3737fe700 DND 0x7fc330001cd0, rpc msg:submit will be processed in vwrite queue
08/31 11:12:29.724100 0x7fc35b7f1700 MND user:monitor, failed to auth user, reason:System not ready
08/31 11:12:29.724116 0x7fc35b7f1700 DND user:monitor, send auth msg to mnode
08/31 11:12:29.724336 0x7fc35b7f1700 DND user:monitor, auth msg received from mnode
08/31 11:12:29.724360 0x7fc3737fe700 DND 0xe41490, rpc msg:submit will be processed in vwrite queue
08/31 11:12:30.298508 0x7fc35b7f1700 MND user:monitor, failed to auth user, reason:System not ready
08/31 11:12:30.298527 0x7fc35b7f1700 DND user:monitor, send auth msg to mnode
08/31 11:12:30.298776 0x7fc35b7f1700 DND user:monitor, auth msg received from mnode
08/31 11:12:30.298798 0x7fc3737fe700 DND 0x7f28cc001cd0, rpc msg:submit will be processed in vwrite queue
08/31 11:12:58.305204 0x7fc35b7f1700 MND user:monitor, failed to auth user, reason:System not ready
08/31 11:12:58.305215 0x7fc35b7f1700 DND user:monitor, send auth msg to mnode
08/31 11:12:58.305365 0x7fc35b7f1700 DND user:monitor, auth msg received from mnode
08/31 11:12:58.305385 0x7fc3737fe700 DND 0x7fc330001cd0, rpc msg:submit will be processed in vwrite queue
08/31 11:13:00.724959 0x7fc35b7f1700 MND user:monitor, failed to auth user, reason:System not ready
08/31 11:13:00.724985 0x7fc35b7f1700 DND user:monitor, send auth msg to mnode
08/31 11:13:00.725291 0x7fc35b7f1700 DND user:monitor, auth msg received from mnode
08/31 11:13:00.725337 0x7fc3737fe700 DND 0xe41490, rpc msg:submit will be processed in vwrite queue
08/31 11:13:01.298543 0x7fc35b7f1700 MND user:monitor, failed to auth user, reason:System not ready
08/31 11:13:01.298568 0x7fc35b7f1700 DND user:monitor, send auth msg to mnode
08/31 11:13:01.298770 0x7fc35b7f1700 DND user:monitor, auth msg received from mnode
08/31 11:13:01.298793 0x7fc3737fe700 DND 0x7f28cc001cd0, rpc msg:submit will be processed in vwrite queue
08/31 11:13:29.305095 0x7fc35b7f1700 MND user:monitor, failed to auth user, reason:System not ready
08/31 11:13:29.305108 0x7fc35b7f1700 DND user:monitor, send auth msg to mnode
08/31 11:13:29.305245 0x7fc35b7f1700 DND user:monitor, auth msg received from mnode
08/31 11:13:29.305281 0x7fc3737fe700 DND 0x7fc330001cd0, rpc msg:submit will be processed in vwrite queue
08/31 11:13:31.724594 0x7fc35b7f1700 MND user:monitor, failed to auth user, reason:System not ready
08/31 11:13:31.724618 0x7fc35b7f1700 DND user:monitor, send auth msg to mnode
08/31 11:13:31.724871 0x7fc35b7f1700 DND user:monitor, auth msg received from mnode
08/31 11:13:31.724892 0x7fc3737fe700 DND 0xe41490, rpc msg:submit will be processed in vwrite queue
08/31 11:13:32.298360 0x7fc35b7f1700 MND user:monitor, failed to auth user, reason:System not ready
08/31 11:13:32.298371 0x7fc35b7f1700 DND user:monitor, send auth msg to mnode
08/31 11:13:32.298488 0x7fc35b7f1700 DND user:monitor, auth msg received from mnode
08/31 11:13:32.298508 0x7fc3737fe700 DND 0x7f28cc001cd0, rpc msg:submit will be processed in vwrite queue
08/31 11:13:55.595844 0x7fc35b7f1700 MND user:monitor, failed to auth user, reason:System not ready
08/31 11:13:55.595860 0x7fc35b7f1700 DND user:monitor, send auth msg to mnode
08/31 11:13:55.596020 0x7fc35b7f1700 DND user:monitor, auth msg received from mnode
08/31 11:13:55.596042 0x7fc3737fe700 DND 0xe40830, rpc msg:submit will be processed in vwrite queue
08/31 11:14:00.305229 0x7fc35b7f1700 MND user:monitor, failed to auth user, reason:System not ready
08/31 11:14:00.305241 0x7fc35b7f1700 DND user:monitor, send auth msg to mnode
08/31 11:14:00.306352 0x7fc35b7f1700 DND user:monitor, auth msg received from mnode
08/31 11:14:00.306378 0x7fc3737fe700 DND 0x7fc330001cd0, rpc msg:submit will be processed in vwrite queue
08/31 11:14:02.724084 0x7fc35b7f1700 MND user:monitor, failed to auth user, reason:System not ready
08/31 11:14:02.724099 0x7fc35b7f1700 DND user:monitor, send auth msg to mnode
08/31 11:14:02.724269 0x7fc35b7f1700 DND user:monitor, auth msg received from mnode
08/31 11:14:02.724290 0x7fc3737fe700 DND 0xe403c0, rpc msg:submit will be processed in vwrite queue
08/31 11:14:03.298733 0x7fc35b7f1700 MND user:monitor, failed to auth user, reason:System not ready
08/31 11:14:03.298750 0x7fc35b7f1700 DND user:monitor, send auth msg to mnode
08/31 11:14:03.298948 0x7fc35b7f1700 DND user:monitor, auth msg received from mnode
08/31 11:14:03.298972 0x7fc3737fe700 DND 0x7f28cc001cd0, rpc msg:submit will be processed in vwrite queue
08/31 11:14:31.304907 0x7fc35b7f1700 MND user:monitor, failed to auth user, reason:System not ready
08/31 11:14:31.304918 0x7fc35b7f1700 DND user:monitor, send auth msg to mnode
08/31 11:14:31.305049 0x7fc35b7f1700 DND user:monitor, auth msg received from mnode
08/31 11:14:31.305068 0x7fc3737fe700 DND 0x7fc330001cd0, rpc msg:submit will be processed in vwrite queue
08/31 11:14:33.724072 0x7fc35b7f1700 MND user:monitor, failed to auth user, reason:System not ready
08/31 11:14:33.724088 0x7fc35b7f1700 DND user:monitor, send auth msg to mnode
08/31 11:14:33.724268 0x7fc35b7f1700 DND user:monitor, auth msg received from mnode
08/31 11:14:33.724292 0x7fc3737fe700 DND 0xe41490, rpc msg:submit will be processed in vwrite queue
08/31 11:14:34.299223 0x7fc35b7f1700 MND user:monitor, failed to auth user, reason:System not ready
08/31 11:14:34.299239 0x7fc35b7f1700 DND user:monitor, send auth msg to mnode
08/31 11:14:34.299438 0x7fc35b7f1700 DND user:monitor, auth msg received from mnode
08/31 11:14:34.299468 0x7fc3737fe700 DND 0x7f28cc001cd0, rpc msg:submit will be processed in vwrite queue
08/31 11:15:02.305048 0x7fc35b7f1700 MND user:monitor, failed to auth user, reason:System not ready
08/31 11:15:02.305061 0x7fc35b7f1700 DND user:monitor, send auth msg to mnode
08/31 11:15:02.305215 0x7fc35b7f1700 DND user:monitor, auth msg received from mnode
08/31 11:15:02.305242 0x7fc3737fe700 DND 0x7fc330001cd0, rpc msg:submit will be processed in vwrite queue
08/31 11:15:04.724647 0x7fc35b7f1700 MND user:monitor, failed to auth user, reason:System not ready
08/31 11:15:04.724678 0x7fc35b7f1700 DND user:monitor, send auth msg to mnode
08/31 11:15:04.725006 0x7fc35b7f1700 DND user:monitor, auth msg received from mnode
08/31 11:15:04.725067 0x7fc3737fe700 DND 0xe41490, rpc msg:submit will be processed in vwrite queue
08/31 11:15:05.298555 0x7fc35b7f1700 MND user:monitor, failed to auth user, reason:System not ready
08/31 11:15:05.298573 0x7fc35b7f1700 DND user:monitor, send auth msg to mnode
08/31 11:15:05.298915 0x7fc35b7f1700 DND user:monitor, auth msg received from mnode
08/31 11:15:05.298981 0x7fc3737fe700 DND 0x7f28cc001cd0, rpc msg:submit will be processed in vwrite queue

**Comment by sangshuduo** [comment]
请列出版本、环境和重现步骤

**Comment by sangshuduo** [comment]
same issue #3303
