### ISSUE TITLE
windows客户端执行出现Invalid Ugroup ID

### ISSUE THREAD

**Issue by hitits** [taosdata/TDengine#3303]
集群版本 2.0.2.1
3节点、2核、8G内存
客户端版本同集群版本
在windows2012 客户端查询出现以下问题(在windows10版本下正常)
![image](https://user-images.githubusercontent.com/69614127/91686165-27467100-eb8f-11ea-958e-1c513afde5c4.png)

**Comment by hitits** [comment]
这些日志可能与报错有关：
![image](https://user-images.githubusercontent.com/69614127/91686420-d420ee00-eb8f-11ea-9145-08ab4bb2914c.png)

**Comment by guanshengliang** [comment]
加一下我的微信吧 geiseil

**Comment by hitits** [comment]
是hosts问题
