### ISSUE TITLE
failed to sync data from prometheus to TDengine by blm_prometheus

### ISSUE THREAD

**Issue by aybthebest** [taosdata/TDengine#3307]
启动blm_prometheus并prometheus配置完成后，prometheus的报错如下：
ts=2020-08-31T08:31:50.584Z caller=dedupe.go:112 component=remote level=warn remote_name=6f5db8 url=http://XXX.XX.149.210:8088/receive msg="Failed to send batch, retrying" err="Post \"http://XXX.XX.149.210:8088/receive\": dial tcp XXX.XX.149.210:8088: connect: connection refused"
ts=2020-08-31T08:32:50.621Z caller=dedupe.go:112 component=remote level=warn remote_name=6f5db8 url=http://XXX.XX.149.210:8088/receive msg="Failed to send batch, retrying" err="Post \"http://XXX.XX.149.210:8088/receive\": dial tcp XXX.XX.149.210:8088: connect: connection refused"
查询TD已成功建库，但是库下没有表。可见，prometheus到blm_prometheus这段链路没通。请帮忙看一下什么问题，谢谢。

版本信息：
prometheus-2.20.1.linux-amd64
TDengine version: 2.0.0.1

1-启动blm_prometheus命令如下:
./blm_prometheus -tdengine-ip XXX.XX.46.141 -tdengine-api-port 6030 --dbname mydb --dbuser 'root' --dbpassword 'taosdata' --port '8088'
2-prometheus参数如下:
remote_write:
- url: "http://XXX.XX.149.210:8088/receive"
3-TD三个节点

**Comment by stevel032** [comment]
Thank you very much for reporting the problem, let us look into this and report back soon.

**Comment by stevel032** [comment]
Hi... I wonder if you can quickly verify if the target machine is reachable from the Prometheus host? with the following command from it?

```
$ ping XXX.XX.149.210
```

and then confirm if the port is reachalble?

```
$ telnet XXX.XX.149.210 8088
```

and finally confirm if the blm_prometheus process is serving content:

```
$ curl http://XXX.XX.149.210:8088/receive
```

Thank you...

**Comment by aybthebest** [comment]
blm_prometheus和prometheus是部署在同一台机器上的

在blm_prometheus部署机器执行
#curl http://XXX.XX.149.210:8088/receive
snappy: corrupt input

prometheus的日志如下：
ts=2020-09-01T06:00:43.207Z caller=dedupe.go:112 component=remote level=warn remote_name=6f5db8 url=http://XXX.XX.149.210:8088/receive msg="Failed to send batch, retrying" err="Post \"http://XXX.XX.149.210:8088/receive\": context deadline exceeded"
ts=2020-09-01T06:01:17.766Z caller=dedupe.go:112 component=remote level=warn remote_name=6f5db8 url=http://XXX.XX.149.210:8088/receive msg="Failed to send batch, retrying" err="Post \"http://XXX.XX.149.210:8088/receive\": context canceled"
ts=2020-09-01T06:01:17.866Z caller=dedupe.go:112 component=remote level=error remote_name=6f5db8 url=http://XXX.XX.149.210:8088/receive msg="non-recoverable error" count=100 err="context canceled"
ts=2020-09-01T06:01:17.866Z caller=dedupe.go:112 component=remote level=error remote_name=6f5db8 url=http://XXX.XX.149.210:8088/receive msg="Failed to flush all samples on shutdown" count=500
ts=2020-09-01T06:01:48.117Z caller=dedupe.go:112 component=remote level=warn remote_name=6f5db8 url=http://XXX.XX.149.210:8088/receive msg="Failed to send batch, retrying" err="Post \"http://XXX.XX.149.210:8088/receive\": context deadline exceeded"
ts=2020-09-01T06:01:48.117Z caller=dedupe.go:112 component=remote level=warn remote_name=6f5db8 url=http://XXX.XX.149.210:8088/receive msg="Failed to send batch, retrying" err="Post \"http://XXX.XX.149.210:8088/receive\": context deadline exceeded"

**Comment by liu0x54** [comment]
在/var/log/taos/路径下有个blm_log和taoslogx.x，可以清空了再执行一下，把日志作为附件贴上来看看

**Comment by aybthebest** [comment]
这是日志文件
[blm_prometheus.log](https://github.com/taosdata/TDengine/files/5160673/blm_prometheus.log)
[taoslog0.0.log](https://github.com/taosdata/TDengine/files/5160675/taoslog0.0.log)

**Comment by liu0x54** [comment]
XXX.XX.46.141这个XXX.XX原来是什么？XXX是你把数字替换掉的吗？如果prometheus和blm_prometheus在一台机器上，你可以在prometheus的conf里把remote_write部分配置改成http://localhost:8088或者http://127.0.0.1:8088试试。
从blm的日志里看，感觉没有收到数据。
还是不行的话
在/etc/taos/taos.cfg中，最后加上一行 
debugFlag 135
然后清空日志再跑一遍，把日志贴上来

**Comment by liu0x54** [comment]
/blm_prometheus -tdengine-ip XXX.XX.46.141 -tdengine-api-port 6030 --dbname mydb --dbuser 'root' --dbpassword 'taosdata' --port '8088'
这里 -tdengine-api-port 是TDengine的restFul 接口的端口，不是6030，应该是6020

**Comment by aybthebest** [comment]
restful默认端口是6041，已经测通了，感谢🙏
