### ISSUE TITLE
client crash

### ISSUE THREAD

**Issue by q1002142102** [taosdata/TDengine#3309]
程序版本:2.0.2.1
错误的语句:insert into xcxday.d1000004_145(user_id,path,scene,ts) using xcxday.xcxlog(appid,adzone_id,session_id,ip) tags(1000004,145,97160,1717171445) values (97160,'pagex/goods/taoke',1086,now);

详细错误信息: /home/ubuntu/lihui/v2.0/TDinternal/community/src/common/inc/tdataformat.h:328: tdAddColToKVRow: Assertion `pBuilder->nCols == 0 || colId > pBuilder->pColIdx[pBuilder->nCols - 1].colId' failed.
Aborted

**Comment by localvar** [comment]
语法错误的语句会在客户端检查出来，不会发送到服务端，所以这个问题不是语法错误引起的。

您可以提供下建表语句吗？

**Comment by q1002142102** [comment]
表结构:create table xcxlog (ts timestamp, user_id int, path BINARY(40),scene int) tags(appid bigint, adzone_id int,ip bigint,session_id bigint);

**Comment by localvar** [comment]
谢谢您的反馈，这时一个bug，我们会修复。
