### ISSUE TITLE
时间戳递增问题

### ISSUE THREAD

**Issue by Luozde** [taosdata/TDengine#331]
您好，通过文档中说有所有的数据都是按时间戳递增，但我们有数据补传的场景，也就是说数据不一定是按递增的顺序过来？这样的场景需要怎样处理？

**Comment by fangpanpan** [comment]
insert命令要求时间戳递增，补传数据时，插入这部分数据可以用import命令。

**Comment by TS668** [comment]
补传以后的数据，是不是就不是按时间戳递增了？这样的话会不会严重影响查询计算性能？

**Comment by fangpanpan** [comment]
补传后的数据还是按时间戳递增的，并不会严重影响查询性能。

**Comment by TS668** [comment]
补传以后还是按时间戳递增？你的意思是整个数据块重写了吗？那补传的速度岂不是非常慢？

**Comment by fangpanpan** [comment]
一个小范围内无序的数据，这种情况TDengine会缓存其中一部分数据，影响不会很大。不过有时候import语句写入，可能会直接写文件，这样的话，会牵扯到拆块合并等问题。我们的import还有很大的优化空间，后续工作会慢慢将优化完成的。

**Comment by willove** [comment]
为什么不能把 insert 和 import 合成一个命令呢，有时候也不清楚后续的数据是不是需要 import 而不是 insert

**Comment by hzcheng** [comment]
两个api的合并工作正在进行中



---原始邮件---
发件人: "乐悠族"<notifications@github.com>
发送时间: 2019年8月17日(星期六) 晚上6:08
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [taosdata/TDengine] 时间戳递增问题 (#331)



为什么不能把 insert 和 import 合成一个命令呢，有时候也不清楚后续的数据是不是需要 import 而不是 insert

**Comment by SMD12138** [comment]
传感器是每5分钟采集一次，如果用采集时间作为时间戳的话，可以吗？但是不是递增的

**Comment by hzcheng** [comment]
同一个传感器采集的时间为什么不是递增的呢？
