### ISSUE TITLE
cannot find pthread when compile on Loongson

### ISSUE THREAD

**Issue by tankwei** [taosdata/TDengine#3313]
CMake Error at src/client/CMakeLists.txt:31 (SET_TARGET_PROPERTIES):
  SET_TARGET_PROPERTIES called with incorrect number of arguments.

是要安装什么依赖库吗？

Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/loongson/source/TDengine/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_81f3d/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_81f3d.dir/build.make CMakeFiles/cmTC_81f3d.dir/build
gmake[1]: Entering directory '/home/loongson/source/TDengine/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_81f3d.dir/src.c.o
/usr/lib64/ccache/cc   -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_81f3d.dir/src.c.o   -c /home/loongson/source/TDengine/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_81f3d
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_81f3d.dir/link.txt --verbose=1
/usr/lib64/ccache/cc  -DCMAKE_HAVE_LIBC_PTHREAD    CMakeFiles/cmTC_81f3d.dir/src.c.o  -o cmTC_81f3d 
CMakeFiles/cmTC_81f3d.dir/src.c.o：在函数‘main’中：
src.c:(.text+0x54)：对‘pthread_create’未定义的引用
src.c:(.text+0x5c)：对‘pthread_create’未定义的引用
src.c:(.text+0x6c)：对‘pthread_detach’未定义的引用
src.c:(.text+0x74)：对‘pthread_detach’未定义的引用
src.c:(.text+0x84)：对‘pthread_cancel’未定义的引用
src.c:(.text+0x8c)：对‘pthread_cancel’未定义的引用
src.c:(.text+0xa0)：对‘pthread_join’未定义的引用
src.c:(.text+0xa8)：对‘pthread_join’未定义的引用
collect2: 错误：ld 返回 1
CMakeFiles/cmTC_81f3d.dir/build.make:106: recipe for target 'cmTC_81f3d' failed
gmake[1]: *** [cmTC_81f3d] Error 1
gmake[1]: Leaving directory '/home/loongson/source/TDengine/build/CMakeFiles/CMakeTmp'
Makefile:141: recipe for target 'cmTC_81f3d/fast' failed
gmake: *** [cmTC_81f3d/fast] Error 2

Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/loongson/source/TDengine/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_3b125/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_3b125.dir/build.make CMakeFiles/cmTC_3b125.dir/build
gmake[1]: Entering directory '/home/loongson/source/TDengine/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_3b125.dir/CheckFunctionExists.c.o
/usr/lib64/ccache/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_3b125.dir/CheckFunctionExists.c.o   -c /usr/local/share/cmake-3.17/Modules/CheckFunctionExists.c
Linking C executable cmTC_3b125
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_3b125.dir/link.txt --verbose=1
/usr/lib64/ccache/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_3b125.dir/CheckFunctionExists.c.o  -o cmTC_3b125  -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: 错误：ld 返回 1
CMakeFiles/cmTC_3b125.dir/build.make:106: recipe for target 'cmTC_3b125' failed
gmake[1]: *** [cmTC_3b125] Error 1
gmake[1]: Leaving directory '/home/loongson/source/TDengine/build/CMakeFiles/CMakeTmp'
Makefile:141: recipe for target 'cmTC_3b125/fast' failed
gmake: *** [cmTC_3b125/fast] Error 2

**Comment by localvar** [comment]
抱歉，我们目前还不支持在龙芯上编译。
