### ISSUE TITLE
Does TDengine capable for log storage?

### ISSUE THREAD

**Issue by oslet** [taosdata/TDengine#3320]
1. tdegnine 是否适合日志类型的数据存储?
2. 是否支持类似于 filebeat等工具采集导入
3.周边工具是否支持,如一键按管mysql数据,有无提供http接口,类似于clickhouse,方便数据导入

**Comment by localvar** [comment]
存储日志的化，需要看日志是结构化的还是非结构化的，TDengine适合存储结构化数据。
可以使用 `taos -D` 从文件夹中批量导入准备好的数据。
我们提供了 http接口，请参考 https://www.taosdata.com/cn/documentation/connector/#RESTful-Connector

**Comment by oslet** [comment]
好,非常感谢
