### ISSUE TITLE
/usr/bin/ld: cannot find -lpthreads when get building . 

### ISSUE THREAD

**Issue by sytpb** [taosdata/TDengine#3322]
7 /usr/bin/cc   -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_be870.dir/src.c.o   -c /root/sys/TDengine/debug/CMakeFiles/CMakeTmp/src.c
  8 Linking C executable cmTC_be870
  9 /usr/bin/cmake3 -E cmake_link_script CMakeFiles/cmTC_be870.dir/link.txt --verbose=1
 10 /usr/bin/cc  -DCMAKE_HAVE_LIBC_PTHREAD    CMakeFiles/cmTC_be870.dir/src.c.o  -o cmTC_be870
 11 CMakeFiles/cmTC_be870.dir/src.c.o: In function `main':
 12 src.c:(.text+0x2d): undefined reference to `pthread_create'
 13 src.c:(.text+0x39): undefined reference to `pthread_detach'
 14 src.c:(.text+0x45): undefined reference to `pthread_cancel'
 15 src.c:(.text+0x56): undefined reference to `pthread_join'
 16 src.c:(.text+0x6a): undefined reference to `pthread_atfork'
 17 collect2: error: ld returned 1 exit status
 18 gmake[1]: *** [cmTC_be870] Error 1
 19 gmake[1]: Leaving directory `/root/sys/TDengine/debug/CMakeFiles/CMakeTmp'
 20 gmake: *** [cmTC_be870/fast] Error 2
 21 
 22 
 23 Source file was:
 24 #include <pthread.h>
 25 
 26 void* test_func(void* data)
 27 {
 28   return data;
 29 }
 30 
 31 int main(void)
 32 {
 33   pthread_t thread;
 34   pthread_create(&thread, NULL, test_func, NULL);
 35   pthread_detach(thread);
 36   pthread_cancel(thread);
 37   pthread_join(thread, NULL);
 38   pthread_atfork(NULL, NULL, NULL);
 39   pthread_exit(NULL);
 40 
 41   return 0;
 42 }
 43 
 44 Determining if the function pthread_create exists in the pthreads failed with the following output:
 45 Change Dir: /root/sys/TDengine/debug/CMakeFiles/CMakeTmp
 46 
 47 Run Build Command(s):/usr/bin/gmake cmTC_94d73/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_94d73.dir/build.make CMakeFiles/cmTC_94d73.dir/build
 48 gmake[1]: Entering directory `/root/sys/TDengine/debug/CMakeFiles/CMakeTmp'
 49 Building C object CMakeFiles/cmTC_94d73.dir/CheckFunctionExists.c.o
 50 /usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_94d73.dir/CheckFunctionExists.c.o   -c /usr/share/cmake3/Modules/CheckFunctionExists.c
 51 Linking C executable cmTC_94d73
 52 /usr/bin/cmake3 -E cmake_link_script CMakeFiles/cmTC_94d73.dir/link.txt --verbose=1
 53 /usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_94d73.dir/CheckFunctionExists.c.o  -o cmTC_94d73  -lpthreads
 **54 /usr/bin/ld: cannot find -lpthreads**
 55 collect2: error: ld returned 1 exit status
 56 gmake[1]: *** [cmTC_94d73] Error 1
 57 gmake[1]: Leaving directory `/root/sys/TDengine/debug/CMakeFiles/CMakeTmp'
 58 gmake: *** [cmTC_94d73/fast] Error 2

**Comment by sytpb** [comment]
lpthreads  or  lpthread (without s ) ?


### ld -lpthreads --verbose

attempt to open //usr/x86_64-redhat-linux/lib64/libpthreads.so failed
attempt to open //usr/x86_64-redhat-linux/lib64/libpthreads.a failed
attempt to open //usr/lib64/libpthreads.so failed
attempt to open //usr/lib64/libpthreads.a failed
attempt to open //usr/local/lib64/libpthreads.so failed
attempt to open //usr/local/lib64/libpthreads.a failed
attempt to open //lib64/libpthreads.so failed
attempt to open //lib64/libpthreads.a failed
attempt to open //usr/x86_64-redhat-linux/lib/libpthreads.so failed
attempt to open //usr/x86_64-redhat-linux/lib/libpthreads.a failed
attempt to open //usr/local/lib/libpthreads.so failed
attempt to open //usr/local/lib/libpthreads.a failed
attempt to open //lib/libpthreads.so failed
attempt to open //lib/libpthreads.a failed
attempt to open //usr/lib/libpthreads.so failed
attempt to open //usr/lib/libpthreads.a failed
ld: cannot find -lpthreads



### ld -lpthread --verbose
==================================================
attempt to open //usr/x86_64-redhat-linux/lib64/libpthread.so failed
attempt to open //usr/x86_64-redhat-linux/lib64/libpthread.a failed
attempt to open //usr/lib64/libpthread.so succeeded
opened script file //usr/lib64/libpthread.so
opened script file //usr/lib64/libpthread.so
**attempt to open /lib64/libpthread.so.0 succeeded**
/lib64/libpthread.so.0
attempt to open /usr/lib64/libpthread_nonshared.a succeeded
libc.so.6 needed by /lib64/libpthread.so.0
found libc.so.6 at //usr/lib64/libc.so.6
ld-linux-x86-64.so.2 needed by /lib64/libpthread.so.0
found ld-linux-x86-64.so.2 at //usr/lib64/ld-linux-x86-64.so.2
ld: warning: cannot find entry symbol _start; not setting start address


[root@VM_0_16_centos debug]# uname -a 
Linux VM_0_16_centos 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hjxilinx** [comment]
新版本已经修复这个问题。
