### ISSUE TITLE
在树莓派上安装TDEngine失败

### ISSUE THREAD

**Issue by feverwind** [taosdata/TDengine#333]
### system
pi@longsm-rasp:~ $ uname -a
Linux longsm-rasp 4.19.50-v7+ #896 SMP Thu Jun 20 16:11:44 BST 2019 armv7l GNU/Linux

### log

root@longsm-rasp:/home/pi# dpkg -i tdengine-1.6.1.5.deb 

dpkg: 处理归档 tdengine-1.6.1.5.deb (--install)时出错：

 软件包体系结构(amd64)与本机系统体系结构(armhf)不符

在处理时有错误发生：

 tdengine-1.6.1.5.deb

**Comment by plum-lihui** [comment]
不好意思！
当前版本还不支持arm平台，还在移植开发中。欢迎加入社区参与arm版本的推进。
多谢！

**Comment by feverwind** [comment]
arm版本的适配你在负责？pi3的CPU虽然是64bit的，但操作系统raspbian还是32bit的。

**Comment by plum-lihui** [comment]
是的。我们首先会提供32位的arm版本。

**Comment by congweitao** [comment]
arm版本移植如何参与？有参与链接吗

**Comment by congweitao** [comment]
arm版本移植有哪些思路？有项目参与链接吗？

**Comment by plum-lihui** [comment]
tdengine for aarch64 移植 #357
请看一下这个issue，已经说移植成功了。你可以试试看。

**Comment by ohmyheartbeat** [comment]
![图片](https://user-images.githubusercontent.com/31534021/64156150-ce9ea400-ce66-11e9-8f0b-0c64d8ff948d.png)
好像还是不行。。按照上述提到的方式改了文件

**Comment by sangshuduo** [comment]
To compile on an ARM processor (aarch64 or aarch32), please add option CPUTYPE as below:

aarch64:

cmake .. -DCPUTYPE=aarch64 && cmake --build .

aarch32:

cmake .. -DCPUTYPE=aarch32 && cmake --build .
