### ISSUE TITLE
Could the alert application push messages to my own receivers?

### ISSUE THREAD

**Issue by hb990208** [taosdata/TDengine#3330]
alert.cfg中 receivers 怎么写自己的api接口？

**Comment by localvar** [comment]
报警模块目前还不支持自定义的 receiver。
但它发送的数据是按 AlertManager 的格式组织的，所以您可以让自己的 receiver 支持这个格式，然后把报警模块的推送地址改成您自己的 receiver 即可。

参考：https://github.com/prometheus/alertmanager/blob/master/examples/ha/send_alerts.sh

**Comment by hb990208** [comment]
> 报警模块目前还不支持自定义的接收器。
> 但它发送的数据是按AlertManager的格式组织的，所以您可以让自己的接收器支持这个格式，然后把报警模块的推送地址改成您自己的接收器即可。
> 
> 参考：[https](https://github.com/prometheus/alertmanager/blob/master/examples/ha/send_alerts.sh) : [//github.com/prometheus/alertmanager/blob/master/examples/ha/send_alerts.sh](https://github.com/prometheus/alertmanager/blob/master/examples/ha/send_alerts.sh)

**Comment by hb990208** [comment]
那请问一下receivers中
    "alertManager": "http://127.0.0.1/api/v1/alerts"

如果换成自己的api，这个 “alertManager” 是有要求的吗？是否可以随意填写？

**Comment by localvar** [comment]
不可以随意写，只能是`alertManager`。

**Comment by hb990208** [comment]
您的意思是我在alertManager 配置中写自己的接收地址吗，由alertManager接收到数据再转发到我自己的api中？
