### ISSUE TITLE
select count(*) ... return wrong row numbers

### ISSUE THREAD

**Issue by XiaoChenUser** [taosdata/TDengine#3334]
**Bug Description**
insert 1千万条数据，select count(*)... 总是返回 1千多万条数据，有时 1010 多万，有时 1020 多万。

**To Reproduce**
1. 服务端：Ubuntu 16.04.2，3 个节点，taosd 版本 2.0.1.0
![server-version](https://user-images.githubusercontent.com/26337902/91828738-15d69500-ec73-11ea-8336-90783c511f0f.PNG)
客户端（windows）：java taosc 版本：2.0.1.1
2.操作
表设计：
![describe-table](https://user-images.githubusercontent.com/26337902/91833139-e32f9b00-ec78-11ea-81e0-3ad13a3f2f3a.PNG)
插入 id 为 [0, 9999999) 的 1千万条数据，起始 id = 0，起始 ts 选择 2020-01-01 00:00:00 对应的时间戳 1577808000000，后续每条数据 id 和 ts 都 “+1”；
数据插入时，每次先 drop 后 create 表，50 个 thread 批量插入 1000W 条数据，每批 1000 条，“thread-1” 插入 [0, 200000)，“thread-2” 插入 [200000, 400000)，以此类推。
查询：select count(*) from 'college_stus';
3.错误排查
发现 select count 返回的数据不对，多次 drop 表重新插入，再查询，还是不对。
a. 清空 /var/log/taos，重新插入，发现日志较多的 taosdlog.1 有很多 ERROR，“ERROR vgId:22 failed to get table to insert data, uid 0 tid 16777216”，“ERROR vgId:22 failed to insert data since Invalid table ID”。
![server-error](https://user-images.githubusercontent.com/26337902/91830801-d3628780-ec75-11ea-911e-5ecd5c988887.PNG)

b. select * from college_stus limit [offset], [rows];   select * from college_stus limit 0,100000;
通过上面的查询语句，逐步增大 offset，配合减小 rows，逐步定位到下面的问题：
select * from college_stus limit 394000,1000;
![data-error](https://user-images.githubusercontent.com/26337902/91832140-9b5c4400-ec77-11ea-91e3-5af05b3d43a2.PNG)
经过多次测试，每次出现错误的 offset 都不一样。查询得知，错误附近的数据 id 唯一，使用函数 min(id) 和 max(id) 查询，分别为 0 和 9,999,999，数据插入没错。
4.排查遗留问题
1）select count(*) 返回的数据行数是否有问题，若正确如何校验？
2）select * ... limit... 出现的时序数据乱序问题是什么原因？

**Comment by localvar** [comment]
您有几个子表？1个？

**Comment by XiaoChenUser** [comment]
> 您有几个子表？1个？

对，就一个，我插入 1百万数据 select count 没问题，1千万就有问题了

**Comment by localvar** [comment]
这个问题我们已经重现，正在处理。

**Comment by hjxilinx** [comment]
简单回避该 bug 的方法是重启一下 taosd 服务。
该 bug 已经修复，会整合到两周后的发布版本中。
谢谢！
