### ISSUE TITLE
The query failed, and the number of connections exceeded

### ISSUE THREAD

**Issue by kujasama** [taosdata/TDengine#3339]
运行了一段时间的TDengine数据库，这几天查询时会卡住，最后抛出：DB error: query cancelled的报错。
日志中存在如下报错：
09/01 12:18:35.937471 8395 7f4c87613700 ERROR RPC MND-shell cid:0, maximum number of sessions:2000 is reached

09/02 08:46:03.756540 4005 7fd490e97700 ERROR RPC DND-shell cid:0, maximum number of sessions:300 is reached

重启taosd服务可以解决，但是问题已复现多次，请问如何解决？

**Comment by yihaoDeng** [comment]
请问用的什么接口访问的, http 还是java client 或者其他

**Comment by kujasama** [comment]
java client访问TDengine

**Comment by kujasama** [comment]
> 请问用的什么接口访问的, http 还是java client 或者其他

java client访问TDengine

**Comment by kujasama** [comment]
> 请问用的什么接口访问的, http 还是java client 或者其他

请教一下，TDengine是否可以通过配置文件修改最大session连接数，或者限制空闲session的连接时间？

**Comment by yihaoDeng** [comment]
> > 请问用的什么接口访问的, http 还是java client 或者其他
> 
> 请教一下，TDengine是否可以通过配置文件修改最大session连接数，或者限制空闲session的连接时间？
可以修改， taos.cfg里有个maxConnection， 你可以修改下
