### ISSUE TITLE
可否提供C#的数据订阅(Publisher/Subscriber)例子？

### ISSUE THREAD

**Issue by leigoCQ** [taosdata/TDengine#334]
可否提供C#的数据订阅(Publisher/Subscriber)例子？
谢谢！

**Comment by guanshengliang** [comment]
新版订阅功能正在重构，预计11月初可以发布到Github上。

**Comment by leigoCQ** [comment]
> 新版订阅功能正在重构，预计11月初可以发布到Github上。

功能很吻合，就差订阅功能，若能9月份推出就好了，正准备用在项目上。

**Comment by bluesky4485** [comment]
java版本订阅是不是也还没有示例的？
@guanshengliang

**Comment by guanshengliang** [comment]
我的同事 @localvar  正在开展这方面的研发工作
等C语言版本稳定之后，会陆续支持C#和Java语言

**Comment by lishuaia** [comment]
@guanshengliang ,您好，我想问下C#订阅的示例现在有吗？

**Comment by anybt** [comment]
@guanshengliang 您好，现在有c#数据订阅相关的示例吗？
