### ISSUE TITLE
After the server restarts, springboot jdbc cannot connect to the server

### ISSUE THREAD

**Issue by weicz1221** [taosdata/TDengine#3341]
springbootdemo启动后，可以正常和taos服务端交互，
这时服务端重启：systemctl restart taosd

原来已经启动的springbootdemo中的接口，无法和taos连接
### Cause: java.sql.SQLException: TDengine Error: Unable to establish connection
; uncategorized SQLException; SQL state []; error code [-2147483637]; TDengine Error: Unable to establish connection; nested exception is java.sql.SQLException: TDengine Error: Unable to establish connection] with root cause

重启springboot可以正常访问

**Comment by zyyang-taosdata** [comment]
the connection which client hold is invalid after taosd restart, please restart the springboot demo and retry.

**Comment by zyyang-taosdata** [comment]
this issue is closed by the assignees
