### ISSUE TITLE
关于压缩方法

### ISSUE THREAD

**Issue by withgakki** [taosdata/TDengine#335]
![15656648514724](https://user-images.githubusercontent.com/39128271/62911990-fa26f500-bdb8-11e9-9917-7ee423a26c96.png)
请问下，各个数据类型具体的压缩方法是什么

**Comment by hzcheng** [comment]
您可以参考/src/util/src/tcompression.c文件的开头注释了解具体的压缩算法。

**Comment by hzcheng** [comment]
https://github.com/taosdata/TDengine/blob/747e93260c9ede7a9f9a2eef10b6c636c6da98ad/src/util/src/tcompression.c#L18
