### ISSUE TITLE
can not query data after restart part of  tdengine nodes

### ISSUE THREAD

**Issue by jin522** [taosdata/TDengine#3352]
i have a cluster with 6 nodes, 
first, i start all 6 nodes, and create one database, use database, create 480000pcs table which 3 replica, and write data into all tables, and query data(select count(*) from train_signal), all operation is ok;
then, i stop 3 nodes of this cluster, and query data from stables(select count(*) from train_signal), however , TDengine report error→DB error: System not ready
last，i start the 3 nodes which stoped before, and query data(select count(*) from train_signal), TDengine still report error→DB error: System not ready

is it a bug or who can tell me how to repair this question?

TDengine version :2.0.0.1

show dnodes:
id   |           end_point            | vnodes | cores  |     status     |   role   |       create_time       |
==================================================================================================================
      1 | master01:6030                  |    118 |     40 | ready          | any      | 2020-08-17 10:44:09.419 |
      2 | slave02:6030                   |    122 |     40 | ready          | any      | 2020-08-17 11:10:02.308 |
      3 | slave04:6030                   |    122 |     40 | ready          | any      | 2020-08-17 11:10:06.308 |
      4 | slave05:6030                   |    122 |     40 | ready          | any      | 2020-08-17 11:10:08.690 |
      5 | slave06:6030                   |    118 |     40 | ready          | any      | 2020-08-17 11:10:10.899 |
      6 | slave07:6030                   |    119 |     40 | ready          | any      | 2020-08-17 11:10:14.004 |

**Comment by xiaopingcs** [comment]
Please add "debugFlag 135" into /etc/taos/taos.cfg for each node and restart taosd. run the same query agian, if you see any error, please share us your logs for each node. we will investigate.

**Comment by guanshengliang** [comment]
Take a look at the results of show vgroups, are there many vgroups that have not selected a master?
When there are too many vgroups, there may be a bug in the synchronization strategy, and we are trying to fix it

**Comment by guanshengliang** [comment]
When there are too many vgroups, synchronization may cause problems
We will solve this problem and it is expected to take 1-2 months

You can reduce the number of vgroups by setting the maxVgroupsPerDb parameter. Refer to the document
https://www.taosdata.com/cn/documentation/administrator/#Capacity planning

**Comment by guanshengliang** [comment]
The new version may solve this problem, you can download it for verification
If there is still a problem, we will continue to deal with it
