### ISSUE TITLE
Loop create super table causing program crash by Java

### ISSUE THREAD

**Issue by yishierniao36** [taosdata/TDengine#3355]
错误如下：
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff977ddb79a, pid=18728, tid=0x0000000000000708
#
# JRE version: Java(TM) SE Runtime Environment (8.0_151-b12) (build 1.8.0_151-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.151-b12 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [taos.dll+0x4b79a]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# D:\bos\arcplus-bos-cloud\hs_err_pid18728.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Disconnected from the target VM, address: '127.0.0.1:62581', transport: 'socket'

建表语句在taos studio中能运行
代码如下：
![图片](https://user-images.githubusercontent.com/10684150/91973382-bea5f280-ed4e-11ea-9fc7-72a735a984da.png)
![图片](https://user-images.githubusercontent.com/10684150/91973420-d3828600-ed4e-11ea-9bbe-208789d72e92.png)

**Comment by zyyang-taosdata** [comment]
connection.createStatement().execute(sql)这样的使用方法是不正确的，参考：
```java
Statement stat = connection.createStatement();
stat.execute("create table(ts timestamp, f1 int) tags(loc binary(64))");
stat.close();
```
每次创建完statement后要关闭，否则会有内存泄露的问题。

**Comment by zyyang-taosdata** [comment]
this issue is closed by assignees
