### ISSUE TITLE
When using TDengine to query the label data of the sub-table, the label value is incomplete

### ISSUE THREAD

**Issue by sanliang125** [taosdata/TDengine#3357]
**Bug Description**
当我在使用JDBC对子表进行查询的时候，出现标签值缺失一个字符的情况。我怀疑是JDBC的原因，然后我又把相同的查询sql放到taos客户端上进行查询，还是出现一样的结果，截图如下。

![微信图片_20200903100235](https://user-images.githubusercontent.com/29949952/92063091-dae87480-edcc-11ea-8620-95e024c527d4.png)

一样的查询语句，有时候查询出来结果是正确的，有时候不不正确，出现不正确情况的概率为40%以上。

**Environment ：**
 - OS: ubuntu 20.04
 - Memory :8G  , CPU:4 Core, current Disk Space:20G
 - TDengine Version : 2.0.1.1
 - JDBC Version: 2.0.4

**Comment by hjxilinx** [comment]
有可能与 wcsncpy 的有关，方便远程过去看一下吗？

**Comment by hjxilinx** [comment]
有可能与 wcsncpy 的有关，方便远程过去看一下吗？

**Comment by hjxilinx** [comment]
有可能与 wcsncpy 的有关，方便远程过去看一下吗？

**Comment by sanliang125** [comment]
> 
> 
> 有可能与 wcsncpy 的有关，方便远程过去看一下吗？
我这边方便的。我的微信号是  sanliang125

**Comment by Aries-Lee1991** [comment]
@sanliang125 这个问题是否已经解决了？

**Comment by hjxilinx** [comment]
这个问题已经解决了。就是 wcsncpy 的原因。
