### ISSUE TITLE
 When querying sub-table data in super table, using Ctrl + C to interrupt the query will cause a segmentation fault.

### ISSUE THREAD

**Issue by sanliang125** [taosdata/TDengine#3358]
**Bug Description**
当进行超级表查询子表数据时，使用Ctrl+C中断查询会出现segmentation fault。
查询语句类似于：  select   *  from temperature;  
其中temperature是超级表表名，该超级表下含有几十个子表，数据量有几十万。
当我查询出了部分结果之后，我使用Ctrl+C中断查询，会出现段错误。

![微信图片_20200903102918](https://user-images.githubusercontent.com/29949952/92064598-5c8dd180-edd0-11ea-9c45-787b2c945afe.png)

** Environment **

- OS: ubuntu 20.04
- Memory :8G , CPU:4 Core, current Disk Space:20G
- TDengine Version : 2.0.1.1

**Comment by hjxilinx** [comment]
这个问题我们知道了，后续我们会修复这个问题。谢谢！

**Comment by sanliang125** [comment]
> 
> 
> 这个问题我们知道了，后续我们会修复这个问题。谢谢！

ok。
