### ISSUE TITLE
failed to evaluate: only integers is allowed || result type is not bool

### ISSUE THREAD

**Issue by hb990208** [taosdata/TDengine#3364]
想请教下为什么在执行告警规则时，明明没有问题的sql和expr会出现报错

**Comment by hb990208** [comment]
![image](https://user-images.githubusercontent.com/59379060/92088432-71ce2480-edff-11ea-8a66-4df99f3e4933.png)


![image](https://user-images.githubusercontent.com/59379060/92088466-7f83aa00-edff-11ea-853e-8991568a4920.png)

**Comment by hb990208** [comment]
2020-09-03T15:21:15.851+0800	ERROR	log/log.go:69	[test1]: result type is not bool
github.com/taosdata/alert/utils/log.Errorf
	/home/zbm/project/td/community/alert/utils/log/log.go:69
github.com/taosdata/alert/app.(*Alert).refresh
	/home/zbm/project/td/community/alert/app/rule.go:130
github.com/taosdata/alert/app.(*Rule).run
	/home/zbm/project/td/community/alert/app/rule.go:370
github.com/taosdata/alert/app.runRules.func1.1
	/home/zbm/project/td/community/alert/app/rule.go:483

**Comment by hb990208** [comment]
我的表结构是这样的：
taos> select * from alllink.inttest1_w4_c2;
          ts          | intnumber |
===================================
 20-09-03 10:58:34.000|         14|
 20-09-03 15:16:59.017|         14|
 20-09-03 15:24:54.813|         14|
 20-09-03 15:33:29.502|         14|
 20-09-03 15:34:30.822|         14|
Query OK, 5 row(s) in set (0.081000s)

**Comment by localvar** [comment]
这是一个已知的问题，预计下周可以修复，请关注。

**Comment by hb990208** [comment]
> 这是一个已知的问题，预计下周可以修复，请关注。

好的

**Comment by hb990208** [comment]
> > 这是一个已知的问题，预计下周可以修复，请关注。
> 
> 好的



> 这是一个已知的问题，预计下周可以修复，请关注。

**Comment by hb990208** [comment]
> 这是一个已知的问题，预计下周可以修复，请关注。


您好，请问修复了吗？已经两周了
