### ISSUE TITLE
i can't connect to taosdata server on windows

### ISSUE THREAD

**Issue by z197915** [taosdata/TDengine#3367]
i don't know which port is need to open on my server
i opened tcp 6030 and 6035 port
udp port 6030-6040
but my python program not work

conn = taos.connect(host="gps.linktrip.com", user="root", password="taosdata",database='gpsrecord')
c1 = conn.cursor()
c1.execute('select * from t')
data = c1.fetchall()
print(data)

but this code work  ok on linux

conn = taos.connect(host="127.0.0.1", user="root", password="taosdata",database='gpsrecord')
c1 = conn.cursor()
c1.execute('select * from t')

data = c1.fetchall()
print(data)

**Comment by z197915** [comment]
and i used these code to test,no problem
import socket
sk=socket.socket()
addr=("gps.linktrip.com",6030)
sk.connect(addr)
sk.close()
addr=("gps.linktrip.com",6035)
sk=socket.socket()
sk.connect(addr)
sk.close()
addr=("gps.linktrip.com",6020)
sk=socket.socket()
sk.connect(addr)
sk.close()

**Comment by plum-lihui** [comment]
What version is used? Is it the version downloaded from tdengine's official website or the version compiled by your own source code?

**Comment by z197915** [comment]
version is same
taos server version:1.6.6.1
client version 1.6.6.1

**Comment by plum-lihui** [comment]
We have released tdengine version 2.0, please test it with the latest version. thank you very much!

**Comment by z197915** [comment]
version 2.x can not find python connector

**Comment by z197915** [comment]
the connect test python code run on linux is OK
but if change code  like this
conn = taos.connect(host="gps.linktrip.com", user="root", password="taosdata",database='gpsrecord')
not work

**Comment by plum-lihui** [comment]
The python driver for windows has not been officially released。
Can the “gps.linktrip.com” be resolved normally on linux？

**Comment by Aries-Lee1991** [comment]
> The python driver for windows has not been officially released。
> Can the “gps.linktrip.com” be resolved normally on linux？

Have you tried the method suggested？Can the “gps.linktrip.com” be resolved normally on linux？

**Comment by plum-lihui** [comment]
The python driver for windows has been released in version 2.0.4.0。
