### ISSUE TITLE
 TDengine 2.0.2.1 data table is duplicate

### ISSUE THREAD

**Issue by PascalMing** [taosdata/TDengine#3372]
Centos 7，TDengine-server-2.0.2.1-Linux-x64.tar.gz 解压安装

Welcome to the TDengine shell from Linux, Client Version:2.0.2.1
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

taos> use mydb;
Database changed.

taos> show tables;
           table_name           |      created_time       | columns |          stable_name           |
======================================================================================================
 f22921864f82f72f69c75a59fd216d | 2020-09-04 09:09:10.042 |       2 |                                |
 tabledef                       | 2020-09-04 08:48:36.232 |       5 |                                |
 faeae9c82d233cb63c79d1c700cd0a | 2020-09-04 09:09:08.830 |       2 |                                |
 tae7ba5aaf4bf895700604db9e9810 | 2020-09-04 08:48:37.457 |       2 |                                |
 fae7ba5aaf4bf895700604db9e9810 | 2020-09-04 08:59:13.116 |       2 |                                |
 f5e9d203a37426e93bed554b42c7bf | 2020-09-04 09:11:39.763 |       2 |                                |
 f4375ff275fd9eb1e07f7486aeee55 | 2020-09-04 09:08:45.656 |       2 |                                |
 fe1cd033e1ff856279e8a97e92b0f1 | 2020-09-04 09:09:00.864 |       2 |                                |
 fbb32cf25d8779cf4bd75aea15d43b | 2020-09-04 09:11:38.012 |       2 |                                |
Query OK, 9 row(s) in set (0.002449s)

taos> select * from f22921864f82f72f69c75a59fd216d;

DB error: Table does not exist
taos> DESCRIBE f22921864f82f72f69c75a59fd216d;

DB error: Table does not exist
taos> DESCRIBE  tabledef ;
             Field              |        Type        |   Length    |    Note    |
=================================================================================
 ts                             | TIMESTAMP          |           8 |            |
 md5                            | BINARY             |          35 |            |
 tagname                        | BINARY             |         128 |            |
 clientid                       | BINARY             |          63 |            |
 remark                         | BINARY             |         128 |            |
Query OK, 5 row(s) in set (0.001252s)

taos> DESCRIBE  tae7ba5aaf4bf895700604db9e9810;

DB error: Table does not exist
taos> select count(*) from f22921864f82f72f69c75a59fd216d;

DB error: Table does not exist
taos> select count(*) from  tabledef;
       count(*)        |
========================
                     9 |
Query OK, 1 row(s) in set (0.101474s)

taos> select count(*) from tae7ba5aaf4bf895700604db9e9810;

DB error: Table does not exist
taos> DROP TABLE f22921864f82f72f69c75a59fd216d;

DB error: Table does not exist
taos> DROP TABLE  tae7ba5aaf4bf895700604db9e9810;

DB error: Table does not exist
taos>

**Comment by PascalMing** [comment]
换成1.6.6的版本后，正常

**Comment by yihaoDeng** [comment]
您好， 可以附带一份日志吗

**Comment by yihaoDeng** [comment]
对了， 你这里的是1.6和2.x用的同一份数据吗， 这两者是不兼容。

**Comment by PascalMing** [comment]
更新版本后，以下数据都是全部删除的
/var/lib/taos
/var/log/taos

**Comment by yihaoDeng** [comment]
> 更新版本后，以下数据都是全部删除的
> /var/lib/taos
> /var/log/taos1

也就是你用2.x的客户端灌了一批数据到2.x的服务上， 仍然出现了上述的问题？如果是，麻烦你你把你的构造语句，以及日志贴一下， 如果我们不能分析浮现，或者不能分析出问题，我们会后续远程帮你继续分析

**Comment by Aries-Lee1991** [comment]
> > 更新版本后，以下数据都是全部删除的
> > /var/lib/taos
> > /var/log/taos1
> 
> 也就是你用2.x的客户端灌了一批数据到2.x的服务上， 仍然出现了上述的问题？如果是，麻烦你你把你的构造语句，以及日志贴一下， 如果我们不能分析浮现，或者不能分析出问题，我们会后续远程帮你继续分析

@PascalMing

**Comment by PascalMing** [comment]
原来的环境已经重置，1.6的正常。
我用2.0.3再试试，看看是否可以。
日志需要哪些位置的？

**Comment by yihaoDeng** [comment]
> 原来的环境已经重置，1.6的正常。
> 我用2.0.3再试试，看看是否可以。
> 日志需要哪些位置的？

客户端即可， 记得设置为各个query/rpc或者更多模块级别设置为135

**Comment by PascalMing** [comment]
重置系统后，安装2.0.3还是有问题。
发个邮件给我：183832091@qq.com，我把账号发你

**Comment by PascalMing** [comment]
表名过长，在Taos命令下从Select中看到的名称不全，可以用 >>XX.cvs看完整的。
