### ISSUE TITLE
Performance tool taosimport crash 

### ISSUE THREAD

**Issue by lgh-dev** [taosdata/TDengine#3380]
官方提供的go性能测试工具导入时候出现DB error: Unable to establish connection，go程序挂掉了。
没留下截图：
执行命令：
`bin/taosimport -cfg config/cfg.toml -cases sensor_info -db test_20200903 -hnum 1 -vnum 360 -start "2020-07-01 00:00:00.000" -auto=1 -interval 60000 -save 1 -dropdb 1`

貌似是第一次导入的时候，加上` -dropdb 1`出现的问题。
具体是前面8个线程顺利建立连接，第9个线程出现DB error: Unable to establish connection错误。go程序就挂掉了。
查看数据量的时候，发现导入了小部分数据。

环境：
 - OS: [ubuntu 18.0.4 Docker安装]
 - 8CPU 32G内存
 - TDengine Version [2.0.2.1]

**Comment by xiaopingcs** [comment]
我们这边没有问题
<img width="1136" alt="Screen Shot 2020-09-04 at 5 11 21 PM" src="https://user-images.githubusercontent.com/65699335/92222589-d3f75a00-eed1-11ea-8aa6-34e7f1306385.png">

**Comment by Aries-Lee1991** [comment]
@lgh-dev 我们这边复现没有问题，你这边还有问题吗？如果依然存在，麻烦把log附上。

**Comment by cpvmrd** [comment]
长期没有回复，先关闭了。
