### ISSUE TITLE
TDengine Alert  info 

### ISSUE THREAD

**Issue by hb990208** [taosdata/TDengine#3381]
在添加告警规则中：
  "sql"：”select avg(numbers) as avgnumber from all.test1“;
  "annotations": {
    "summary": "{{$values}}"
  }

告警信息{{$values}}中就只有一个 avgnumber ？
在sql中把时间参数加上提示出错：failed to query TDengine: invalid SQL: only one selectivity function allowed in presence of tags function

请问怎样把告警的那条数据其他字段给显示出来？

**Comment by yihaoDeng** [comment]
这里已经提示了， only one selectivity function allowed in presence of tags function

**Comment by hb990208** [comment]
> 这里已经提示了， only one selectivity function allowed in presence of tags function

那怎么取出那条数据的其他字段？{{$values}} 输出里面只有一个avgnumber
