### ISSUE TITLE
使用命令通过csv文件导入数据一直不成功

### ISSUE THREAD

**Issue by hhhyb** [taosdata/TDengine#340]
![log](https://user-images.githubusercontent.com/42267833/62922406-e0e46f80-bddd-11e9-8bed-c4d7f500245c.png)
![log1](https://user-images.githubusercontent.com/42267833/62922492-0d988700-bdde-11e9-9e9a-82b2387ba01b.png)
这是打印的日志，着怎么解决

**Comment by fangpanpan** [comment]
您可以将debugflag改成135,然后看看完整的日志吗？

**Comment by fangpanpan** [comment]
您可以将”11.csv“复制到当前目录，或者将“11.csv" 写成完整的绝对的路径。

**Comment by hhhyb** [comment]
当前目录是指那个目录，我的11.csv是放在/usr/local/taos/bin这个下面的。
如果是写成完整的路径insert into dm_test file /usr/local/taos/bin/11.csv;是这样吗？




------------------ 原始邮件 ------------------
发件人: "fangpanpan"<notifications@github.com>; 
发送时间: 2019年8月13日(星期二) 下午5:04
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>; 
抄送: "拥抱."<1396988252@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [taosdata/TDengine] 使用命令通过csv文件导入数据一直不成功 (#340)




您可以将”11.csv“复制到当前目录，或者将“11.csv" 写成完整的绝对的路径。

**Comment by fangpanpan** [comment]
当前目录您输入```pwd```就知道了，绝对路径是您输入的这样。不过为什么您的日志显示的是'demo.csv" file找不到？您插入的是“demo.csv"还是”11.csv"？

**Comment by hhhyb** [comment]
这个导入数据现在是你们文档里面的demo我能导成功，但是我自己我新建了一个表，建表语句是  CREATE TABLE dm_test (timestamp_field_name TIMESTAMP,EQUIP_ID binary(20),EQUIP_NAME nchar(20),DOT_NAME nchar(10),LINE_ID nchar(20),LINE_NAME nchar(10),STATION_ID nchar(30),STATION_NAME nchar(20),OCCUR_DATE TIMESTAMP,MEASTYPE nchar(20),MAXVALUE double,MAXTIME double,MINVALUE double,MINTIME nchar(20),AVGVALUE double,LOADRATE double,SUM_VALUE double,MWH_VALUE double,PMWH_VALUE double,NMWH_VALUE double,DIFF_VALUE double,DATASOURCE nchar(10),CIRCLE nchar(10),LOAD_TIME TIMESTAMP)
然后在csv文件里面我就放了两条数据，格式是这样的

就报错下面这个

是什么原因，我建的表有问题还是csv文件有问题？


 




------------------ 原始邮件 ------------------
发件人: "fangpanpan"<notifications@github.com>; 
发送时间: 2019年8月13日(星期二) 下午5:17
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>; 
抄送: "拥抱."<1396988252@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [taosdata/TDengine] 使用命令通过csv文件导入数据一直不成功 (#340)




当前目录您输入pwd就知道了，绝对路径是您输入的这样。不过为什么您的日志显示的是'demo.csv" file找不到？您插入的是“demo.csv"还是”11.csv"？

**Comment by fangpanpan** [comment]
> 这个导入数据现在是你们文档里面的demo我能导成功，但是我自己我新建了一个表，建表语句是 CREATE TABLE dm_test (timestamp_field_name TIMESTAMP,EQUIP_ID binary(20),EQUIP_NAME nchar(20),DOT_NAME nchar(10),LINE_ID nchar(20),LINE_NAME nchar(10),STATION_ID nchar(30),STATION_NAME nchar(20),OCCUR_DATE TIMESTAMP,MEASTYPE nchar(20),MAXVALUE double,MAXTIME double,MINVALUE double,MINTIME nchar(20),AVGVALUE double,LOADRATE double,SUM_VALUE double,MWH_VALUE double,PMWH_VALUE double,NMWH_VALUE double,DIFF_VALUE double,DATASOURCE nchar(10),CIRCLE nchar(10),LOAD_TIME TIMESTAMP) 然后在csv文件里面我就放了两条数据，格式是这样的 就报错下面这个 是什么原因，我建的表有问题还是csv文件有问题？
> […](#)

我没有看见csv文件里的数据格式？ 还有报错下面是有个图片吗？我这里没有显示。

**Comment by hhhyb** [comment]
------------------ 原始邮件 ------------------
发件人: "fangpanpan"<notifications@github.com>; 
发送时间: 2019年8月13日(星期二) 下午5:59
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>; 
抄送: "拥抱."<1396988252@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [taosdata/TDengine] 使用命令通过csv文件导入数据一直不成功 (#340)



 
这个导入数据现在是你们文档里面的demo我能导成功，但是我自己我新建了一个表，建表语句是 CREATE TABLE dm_test (timestamp_field_name TIMESTAMP,EQUIP_ID binary(20),EQUIP_NAME nchar(20),DOT_NAME nchar(10),LINE_ID nchar(20),LINE_NAME nchar(10),STATION_ID nchar(30),STATION_NAME nchar(20),OCCUR_DATE TIMESTAMP,MEASTYPE nchar(20),MAXVALUE double,MAXTIME double,MINVALUE double,MINTIME nchar(20),AVGVALUE double,LOADRATE double,SUM_VALUE double,MWH_VALUE double,PMWH_VALUE double,NMWH_VALUE double,DIFF_VALUE double,DATASOURCE nchar(10),CIRCLE nchar(10),LOAD_TIME TIMESTAMP) 然后在csv文件里面我就放了两条数据，格式是这样的 就报错下面这个 是什么原因，我建的表有问题还是csv文件有问题？
 …
  
我没有看见csv文件里的数据格式？ 还有报错下面是有个图片吗？我这里没有显示。

**Comment by hhhyb** [comment]
您在看看是不是我的建表建的有问题


------------------ 原始邮件 ------------------
发件人: "fangpanpan"<notifications@github.com>;
发送时间: 2019年8月13日(星期二) 下午5:59
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
抄送: "拥抱."<1396988252@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [taosdata/TDengine] 使用命令通过csv文件导入数据一直不成功 (#340)



 
这个导入数据现在是你们文档里面的demo我能导成功，但是我自己我新建了一个表，建表语句是 CREATE TABLE dm_test (timestamp_field_name TIMESTAMP,EQUIP_ID binary(20),EQUIP_NAME nchar(20),DOT_NAME nchar(10),LINE_ID nchar(20),LINE_NAME nchar(10),STATION_ID nchar(30),STATION_NAME nchar(20),OCCUR_DATE TIMESTAMP,MEASTYPE nchar(20),MAXVALUE double,MAXTIME double,MINVALUE double,MINTIME nchar(20),AVGVALUE double,LOADRATE double,SUM_VALUE double,MWH_VALUE double,PMWH_VALUE double,NMWH_VALUE double,DIFF_VALUE double,DATASOURCE nchar(10),CIRCLE nchar(10),LOAD_TIME TIMESTAMP) 然后在csv文件里面我就放了两条数据，格式是这样的 就报错下面这个 是什么原因，我建的表有问题还是csv文件有问题？
 …
  
我没有看见csv文件里的数据格式？ 还有报错下面是有个图片吗？我这里没有显示。

**Comment by fangpanpan** [comment]
> 您在看看是不是我的建表建的有问题
> […](#)

您的建表没什么问题，可以创建成功。 请问报的是什么错误？

**Comment by hhhyb** [comment]
这是文件格式

这是报的错







------------------ 原始邮件 ------------------
发件人: "fangpanpan"<notifications@github.com>; 
发送时间: 2019年8月13日(星期二) 晚上6:13
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>; 
抄送: "拥抱."<1396988252@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [taosdata/TDengine] 使用命令通过csv文件导入数据一直不成功 (#340)



 
您在看看是不是我的建表建的有问题
 …
  
您的建表没什么问题，可以创建成功。 请问报的是什么错误？

**Comment by fangpanpan** [comment]
“文件格式” 和“报的错“下面我都只能看见一行空白，请问您是贴了图吗？
