### ISSUE TITLE
Does the table generated by TDengine  support dynamic addition?

### ISSUE THREAD

**Issue by destiny-cj** [taosdata/TDengine#3401]

**Comment by sangshuduo** [comment]
可以在应用中使用 alter table tbname add column 来增加列

**Comment by Aries-Lee1991** [comment]
@destiny-cj “可以在应用中使用 alter table tbname add column 来增加列”，这个建议是否解决了您的问题？

**Comment by destiny-cj** [comment]
这种形式不太满足需求，后续会支持这种功能么？

**Comment by Aries-Lee1991** [comment]
> 这种形式不太满足需求，后续会支持这种功能么？

不太明白你的问题。我们已经是支持这种功能的，具体方法就是 alter table tbname add column。能否告知下你的具体需求？

**Comment by destiny-cj** [comment]
举个例子：就像influxdb一样，我插入的数据多加了一列会自动生成在表里面，这种功能，你说的方法是可以实现，但是不太方便

**Comment by shansr** [comment]
使用jdbcTemplate 执行语句 alter table stbname add column type  成功后，在 Cli工具中执行 decribe stb，并不能马上看到添加的column。并且用jdbcTemplate执行语句 alter table stbname add column type  成功后，再插入对应字段的值程序报错。

**Comment by hjxilinx** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
