### ISSUE TITLE
When running specific SQL, taosd will report segmentation fault

### ISSUE THREAD

**Issue by jedy** [taosdata/TDengine#3408]
**Bug Description**
服务器报Segmentation fault

**To Reproduce**
1. 使用taosdemo生成test.meters
2. 运行sql：select sum(f1) from meters interval(1h) sliding(30m);
3. 服务器报错退出

**Screenshots**
![image](https://user-images.githubusercontent.com/1589263/92357375-4fe3e300-f11a-11ea-9e7b-86e69137cef0.png)
![image](https://user-images.githubusercontent.com/1589263/92357453-71dd6580-f11a-11ea-90c3-f37d32d78609.png)

**Environment (please complete the following information):**
 - OS: CentOS 6.9
 - TDengine Version ver-2.0.3.0，自己编译的

**Comment by jedy** [comment]
taosdemo默认参数生成的，meters一共995826000条数据

**Comment by jedy** [comment]
![image](https://user-images.githubusercontent.com/1589263/92364738-1618d980-f126-11ea-9ce3-960582187e9d.png)

**Comment by Shawshank-Smile** [comment]
看不到图片了，如果能够复现的话，请加我微信：13720014098，我来远程。

**Comment by jedy** [comment]
可以复现，但因为是生产服务器，无法开放权限

**Comment by hjxilinx** [comment]
sliding 的中计算滑动窗口的功能有问题，我们会尽快修复。

**Comment by hjxilinx** [comment]
这个问题已经修复，关闭该 issue.
