### ISSUE TITLE
Query the nchar type data as none

### ISSUE THREAD

**Issue by Lao-Zhong** [taosdata/TDengine#3410]
终端sql查询正常，但是在python方法中使用sql查询就是None，请问这是什么原因
![微信图片_20200907154243](https://user-images.githubusercontent.com/39207755/92361322-ce438380-f120-11ea-9274-451ed8310a35.png)
![微信图片_20200907154247](https://user-images.githubusercontent.com/39207755/92361334-d0a5dd80-f120-11ea-940f-34685fee6bc2.png)

**Comment by sangshuduo** [comment]
请提供版本信息和 Python 相关代码

**Comment by Lao-Zhong** [comment]
> 请提供版本信息和Python相关代码

taos client version:1.6.6.0
python version: 3.5.2
![Snipaste_2020-09-07_15-54-26](https://user-images.githubusercontent.com/39207755/92362420-90475f00-f122-11ea-90ee-379473b211e3.png)
![微信图片_20200907154247](https://user-images.githubusercontent.com/39207755/92362429-93424f80-f122-11ea-9951-3f386c0dae10.png)
![Snipaste_2020-09-07_15-55-06](https://user-images.githubusercontent.com/39207755/92362436-94737c80-f122-11ea-9932-1438a3794c66.png)

**Comment by Lao-Zhong** [comment]
> 请提供版本信息和Python相关代码

taos客户端版本：1.6.6.0
python版本：3.5.2
![Snipaste_2020-09-07_15-54-26](https://user-images.githubusercontent.com/39207755/92362518-b1a84b00-f122-11ea-825e-b5c1fa715229.png)
![Snipaste_2020-09-07_15-53-13](https://user-images.githubusercontent.com/39207755/92362543-b836c280-f122-11ea-8869-a8515866b451.png)
![Snipaste_2020-09-07_15-55-06](https://user-images.githubusercontent.com/39207755/92362564-bff66700-f122-11ea-8f21-0edd75995307.png)

**Comment by Shawshank-Smile** [comment]
1.6的开源版本，现阶段原则上只能由开源社区来支持。建议尽快测试、升级2.0版本。

**Comment by plum-lihui** [comment]
TDengine官网已经发布了2.0.3.0版本，请使用最新的版本测试。多谢！
