### ISSUE TITLE
A few questions about TDengine

### ISSUE THREAD

**Issue by QIANGEGEGE** [taosdata/TDengine#3416]
我有一些问题想咨询下，看了文档后有如下几点疑问：
1. 目前我们大概有6k测温设备那么就就需要创建6k个设备表，一个超级表对么？
2. 后续设备大概会增到2w左右，表多会不会影响（每个表不会超过20个字段）？
3. 我们采集频率大概为1分钟一条，目前6k设备如果使用需不需要上集群？
4. 我们需要保存2年的历史数据大概存储成本会是多少？

非常期待期待回答，谢谢！

**Comment by Shawshank-Smile** [comment]
您的所有问题，都可以用一句谚语回答：“Don't be shy，just try”，taosdemo会帮到您。

**Comment by zyyang-taosdata** [comment]
1. 是的，因为这6K个设备的检测的物理量都动态的，而name、type、location这样的静态信息一般是不变的，所以，使用一张超级表，每个设备表都可以使用这个超级表的schema创建。
2. 超级表的设计正是为了解决表多的场景，比如查询某个设备的数据，那么通过tag标签进行过滤，加快查询速度。请正确区分tag和field的概念，静态字段放在tag，动态的物理量放在table的schema中。
3. 这个可以估算一下，请参考：https://www.taosdata.com/cn/documentation/administrator/#%E5%AE%B9%E9%87%8F%E8%A7%84%E5%88%92.

**Comment by QIANGEGEGE** [comment]
好的，感谢热情的回复，这边和领导商量先试试再说。
