### ISSUE TITLE
Data retention, similar to keep function

### ISSUE THREAD

**Issue by sytpb** [taosdata/TDengine#3419]
企业数据经常有遇到这样的情况，比如设定一个月，就是希望某个库或者某个表总是保留最后一个月的，是用最后一条数据时间向前算起， 类似TD keep , 但是有区别，  keep 是用当前最新时间往前算，这里想说的是最后一条记录时间为准往前算， 这样的话数据库或表总是保留一段数据，现在的keep ,后面如果一段时间没有数据，会清空了数据库或表。 

希望TD 团队可以考虑下，有没有必要。

**Comment by Shawshank-Smile** [comment]
有没有试想过，如果按照您的功能，一条将来的错误数据，就可以删库跑路，剩下孤零零的最后一条数据？

**Comment by sytpb** [comment]
哈哈，如果是出于恶意破坏就得另说了， 直接drop 掉，或者把服务器时间改成未来，现在keep 不一样能导致数据库删掉数据吗？ ：）

**Comment by Shawshank-Smile** [comment]
现在的不会，您提的是我们很早的版本修复的一个bug。

**Comment by sytpb** [comment]
还利用这个规则, 说明肯定是内部员工,那是人的问题,不是数据库的问题了,不应把问题归于DB,   另一个情况因为未来一条错误数据, 这个原因也在于这个错误先发生. ..

**Comment by sytpb** [comment]
> 有没有试想过，如果按照您的功能，一条将来的错误数据，就可以删库跑路，剩下孤零零的最后一条数据？

如果有这个功能,这个问题也不能算上DB头上.   :)

**Comment by Shawshank-Smile** [comment]
who is the boss? My man!  ^_^
