### ISSUE TITLE
表名长度过长，不支持：invalid SQL: name too long

### ISSUE THREAD

**Issue by lnparker** [taosdata/TDengine#342]
您好，在使用超级表， 写数据时自动建子表，其中一个tag的值太长了(100字节+)，会报错：“invalid SQL: name too long”。请问有解决方法么？或者有相应的配置可以设定？

**Comment by plum-lihui** [comment]
是的，表名最多支持64字节。

**Comment by plum-lihui** [comment]
目前对表名、列名、tag名都最大支持64字节。你说的tag值应该是没有限制的，只是限制一条sql语句的总长不能超过65380字节。
能把这条报错的sql语句发上来看一下吗？

**Comment by sapphire36** [comment]
请问是否可以将“invalid SQL: name too long”错误设置为warning级别,加入自动截取tag的功能,对超过64字节的tag自动取其前64位? 这样可以一定程度上避免由于用户tag设置问题而导致程序报错. 不知道这样是否可行?

**Comment by lnparker** [comment]
> 目前对表名、列名、tag名都最大支持64字节。你说的tag值应该是没有限制的，只是限制一条sql语句的总长不能超过65380字节。
> 能把这条报错的sql语句发上来看一下吗？

您好，是基于tag的自动建表，表名包含了tag值的

**Comment by lnparker** [comment]
> 目前对表名、列名、tag名都最大支持64字节。你说的tag值应该是没有限制的，只是限制一条sql语句的总长不能超过65380字节。
> 能把这条报错的sql语句发上来看一下吗？

您好，表名最大支持的也不是64字节，我亲测是64个字符吧？

**Comment by plum-lihui** [comment]
对于tag名是会自动截取前面的64字节的。

**Comment by plum-lihui** [comment]
@lnparker 请把sql语句发出来，我们针对实际语句说起来更清楚。多谢！

**Comment by lnparker** [comment]
insert into etl_1___2194431849217_e7cdcd8e3b851ae7b6b54717872753a7e0e8d82d24914ad8f8e49c5eddb24ea1 using super3 tags('1', '_', '2194431849217', 'e7cdcd8e3b851ae7b6b54717872753a7e0e8d82d24914ad8f8e49c5eddb24ea1') values('1565679686722', '2', '2194431849217555555', '2206318885121', '2', '168268500', 'chat_id2070817533city_id_locate15city_id_select15');

**Comment by lnparker** [comment]
您好，super3是我们的超级表，有四个tag，其中有一个tag的值较长：e7cdcd8e3b851ae7b6b54717872753a7e0e8d82d24914ad8f8e49c5eddb24ea1

**Comment by lnparker** [comment]
字表的表名取得是四个tag的拼接，这样表名就超了64字节的长度限制

**Comment by lnparker** [comment]
@plum-lihui 麻烦帮看下有解决方案么

**Comment by plum-lihui** [comment]
目前的处理如下：
对于表名、列名，如果超过64字节就返回sql错误；
对于列的值，如果超过指定的长度，就自动截取到指定的最大长度。
后续我们会考虑修改成动态长度，不再限制名称的长度，但由于考虑到前后版本兼容问题，需要点时间才能发布。

**Comment by lnparker** [comment]
> 目前的处理如下：
> 对于表名、列名，如果超过64字节就返回sql错误；
> 对于列的值，如果超过指定的长度，就自动截取到指定的最大长度。
> 后续我们会考虑修改成动态长度，不再限制名称的长度，但由于考虑到前后版本兼容问题，需要点时间才能发布。

好的 谢谢
