### ISSUE TITLE
Error in data from blm_prometheus to TDengine

### ISSUE THREAD

**Issue by zhenghf1985** [taosdata/TDengine#3423]
prometheus采集的数据含有双引号，导致建表错误。

**Comment by xiaopingcs** [comment]
刚修改了一下blm_prometheus的程序，你再试试
需要用 go build重新编译一下

**Comment by zhenghf1985** [comment]
BLM_PRM2020/09/08 10:48:23 server.go:588: execSql Error: invalid SQL: tags number not matched sqlcmd: create table if not exists MD5_0abf1eb39dc0ccf928ccdd0265ad9e9d using kube_endpoint_labels tags("369e1bf6b9cf01b5c909c85d900c7b08","tke-movie-v2-springboot","xxxx:8443","kube-state-metrics","movie",null,null,null,null,null,null,null)

tag个数又不对了 少了一个

**Comment by xiaopingcs** [comment]
可以把prometheus发送的数据发一下吗

**Comment by Aries-Lee1991** [comment]
> 可以把prometheus发送的数据发一下吗

@zhenghf1985
