### ISSUE TITLE
There is no taodump in v2.0

### ISSUE THREAD

**Issue by zhenghf1985** [taosdata/TDengine#3424]
**Bug Description**

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by Shawshank-Smile** [comment]
是的。因为2.0和1.6的进行了结构性的重构，数据存储是完全不兼容的。为了确保客户的数据安全，目前数据迁移官方会提供一定技术支持，而不是简单的提供工具。

**Comment by Lao-Zhong** [comment]
请问有好的数据迁移方案吗？
