### ISSUE TITLE
v2.0.3，DB error: Unable to resolve FQDN when client connect to server in docker.

### ISSUE THREAD

**Issue by rennner** [taosdata/TDengine#3427]
使用win10安装2.0.3 cli，centos7安装2.0.3版 docker image，
docker run -d --name taos2.0   -v /home/docker/taos2.0:/var/lib/taos  -p 6030-6042:6030-6042 -p 6030-6042:6030-6042/udp tdengine/tdengine 

win10 cmd执行：
taos -h   centos7的ip
show users  
提示无法解析fqdn
![image](https://user-images.githubusercontent.com/37169223/92429849-c853ae00-f1c5-11ea-9a50-55951e4ae90b.png)

确认防火墙已关闭。
==================================================
                new log file                      
==================================================
09/08 10:59:09.811000 0x00005098 UTL localEp is: DESKTOP-1VKVP30:6030
09/08 10:59:09.811000 0x00005098 UTL timezone not configured, use default
09/08 10:59:09.869000 0x00005098 UTL locale not configured, set to default:Chinese_China.936
09/08 10:59:09.869000 0x00005098 UTL charset not configured, set to default:cp936
09/08 10:59:09.869000 0x00005098 UTL    taos config & system info:
09/08 10:59:09.869000 0x00005098 UTL ==================================
09/08 10:59:09.869000 0x00005098 UTL  firstEp:                DESKTOP-xxx:6030 
09/08 10:59:09.869000 0x00005098 UTL  secondEp:               DESKTOP-xxx:6030 
09/08 10:59:09.869000 0x00005098 UTL  fqdn:                   DESKTOP-xxx 
09/08 10:59:09.869000 0x00005098 UTL  serverPort:             6030 
09/08 10:59:09.869000 0x00005098 UTL  configDir:              C:/TDengine/cfg 
09/08 10:59:09.869000 0x00005098 UTL  logDir:                 C:/TDengine/log 
09/08 10:59:09.869000 0x00005098 UTL  scriptDir:              C:/TDengine/script 
09/08 10:59:09.869000 0x00005098 UTL  arbitrator:              
09/08 10:59:09.869000 0x00005098 UTL  numOfThreadsPerCore:    1.000000 
09/08 10:59:09.869000 0x00005098 UTL  rpcTimer:               1000(ms)
09/08 10:59:09.869000 0x00005098 UTL  rpcMaxTime:             600(s)
09/08 10:59:09.869000 0x00005098 UTL  shellActivityTimer:     3(s)
09/08 10:59:09.869000 0x00005098 UTL  tableMetaKeepTimer:     7200(s)
09/08 10:59:09.869000 0x00005098 UTL  compressMsgSize:        -1 
09/08 10:59:09.869000 0x00005098 UTL  maxSQLLength:           65480(byte)
09/08 10:59:09.869000 0x00005098 UTL  maxNumOfOrderedRes:     100000 
09/08 10:59:09.869000 0x00005098 UTL  timezone:               not configured 
09/08 10:59:09.869000 0x00005098 UTL  locale:                 Chinese_China.936 
09/08 10:59:09.869000 0x00005098 UTL  charset:                cp936 
09/08 10:59:09.869000 0x00005098 UTL  numOfLogLines:          10000000 
09/08 10:59:09.869000 0x00005098 UTL  asyncLog:               1 
09/08 10:59:09.869000 0x00005098 UTL  debugFlag:              0 
09/08 10:59:09.869000 0x00005098 UTL  rpcDebugFlag:           131 
09/08 10:59:09.869000 0x00005098 UTL  tmrDebugFlag:           131 
09/08 10:59:09.869000 0x00005098 UTL  cDebugFlag:             131 
09/08 10:59:09.869000 0x00005098 UTL  jniDebugFlag:           131 
09/08 10:59:09.869000 0x00005098 UTL  odbcDebugFlag:          131 
09/08 10:59:09.869000 0x00005098 UTL  uDebugFlag:             131 
09/08 10:59:09.869000 0x00005098 UTL  qDebugFlag:             131 
09/08 10:59:09.869000 0x00005098 UTL  tsdbDebugFlag:          131 
09/08 10:59:09.869000 0x00005098 UTL  gitinfo:                community 
09/08 10:59:09.869000 0x00005098 UTL  gitinfoOfInternal:      internal 
09/08 10:59:09.869000 0x00005098 UTL  buildinfo:              Built at 2020-09-05 22:14:00 
09/08 10:59:09.869000 0x00005098 UTL  version:                2.0.3.0 
09/08 10:59:09.869000 0x00005098 UTL  maxBinaryDisplayWidth:  30 
09/08 10:59:13.640000 0x00003d48 UTL ERROR failed get the ip address, fqdn:06cbe93d9a0a, code:11001, reason:不知道这样的主机。 
09/08 10:59:13.640000 0x00003d48 RPC ERROR TSC, failed to resolve FQDN:06cbe93d9a0a
09/08 10:59:13.640000 0x00003d48 RPC ERROR TSC 000001E6CEC18E20, failed to set up connection(Unable to resolve FQDN)
09/08 10:59:13.740000 0x000023d8 TSC ERROR 000001E6CEC1E300 add into queued async res, code:Syntax errr in SQL
09/08 10:59:17.400000 0x00003d48 UTL ERROR failed get the ip address, fqdn:06cbe93d9a0a, code:11001, reason:不知道这样的主机。 
09/08 10:59:17.400000 0x00003d48 RPC ERROR TSC, failed to resolve FQDN:06cbe93d9a0a
09/08 10:59:17.400000 0x00003d48 RPC ERROR TSC 000001E6CEC18E20, failed to set up connection(Unable to resolve FQDN)

**Comment by Aries-Lee1991** [comment]
参考FAQ第6条：https://www.taosdata.com/cn/documentation/faq/

**Comment by rennner** [comment]
1、您好，我按照FAQ6，修改了docker宿主机的hostname，并在win10的hosts添加了FQDN映射，可以ping通centos的机器名。但win10 cli依然提示无法解析fqdn，请问还需要做什么设置，docker镜像需要做什么配置吗？
2、请问2.0的windows 32位版本的taos.dll的什么时候能发布？

**Comment by sangshuduo** [comment]
有没有指定暴露端口？

**Comment by rennner** [comment]
有保留端口的。
docker run -d --name taos2.0 -v /home/docker/taos2.0:/var/lib/taos -p 6030-6042:6030-6042 -p 6030-6042:6030-6042/udp tdengine/tdengine

![image](https://user-images.githubusercontent.com/37169223/92576777-7ccffb80-f2bc-11ea-96dc-187b28abee4b.png)

**Comment by Shawshank-Smile** [comment]
请问，宿主机能够ping通docker内部的IP吗？
如果不能够ping通，需要先解决这个问题。如果可以，就是改一下配置，加我微信：13720014098，我来远程您一下。

**Comment by Shawshank-Smile** [comment]
已经帮其配置问题，问题解决。

**Comment by Flyerison** [comment]
what？？解决方案贴下啊，兄嘚 @Shawshank-Smile

**Comment by rennner** [comment]
官方给了一个内部文档，但是没有看明白，希望官方能能出一下易读的文档（官方网站9.11日出了一个配置说明，但不是docker的）， @Flyerison

**Comment by Flyerison** [comment]
官方给出的FQDN问题解释：https://www.taosdata.com/blog/2020/09/11/1824.html，thanks @rennner 
仅说明了安装包安装的解决方法，从中可以推导出docker安装（单机，非集群！）的解决方案：
说白了就是网络寻址问题，docker网络默认桥接模式，只要给docker容器设置hostname主机名即可：
docker run -h hostname ...
![image](https://user-images.githubusercontent.com/28044926/93034756-b5315a00-f66d-11ea-9ea0-5122b2a03069.png)
![image](https://user-images.githubusercontent.com/28044926/93035319-3e955c00-f66f-11ea-8472-bb5288b1f2ec.png)
客户端（Windows10）就参照文档添加一下hosts文件的IP域名映射即可
最后JDBC2.0.4 使用hostname:port连接即可

**Comment by rennner** [comment]
我这里按您说的还是没有解决问题。说不清问题到底出现在哪，还是要谢谢 @Flyerison

**Comment by cicistudio2000** [comment]
@rennner 兄弟，我终于找到办法了。不要设置-h hostname, 创建容器时所有的用默认配置：

创建容器：docker run -d --name tdengine -p 6030-6042:6030-6042 -p 6030-6042:6030-6042/udp tdengine/tdengine:latest
进入容器内部：docker exec -it tdengine bash
执行hostname命令, 获取当前的hostname，貌似默认就是docker的containerid

再到host文件中修改为，替换
[宿主机器ip] [获取到的hostname]

然后再利用客户端连接这个[hostname]就可以了。

**Comment by cicistudio2000** [comment]
更新：我把原来已经映射的文件再宿主机中全部清空，再重新创建运行容器，好像也可以了：
参考：
docker run --name tdengine \
--hostname="mytest" \
-v /home/tdenginedb/data:/var/lib/taos \
-v /home/tdenginedb/log:/var/log/taos \
-p 6030-6042:6030-6042 \
-p 6030-6042:6030-6042/udp \
--restart=always \
-d tdengine/tdengine:latest

**Comment by rennner** [comment]
@cicistudio2000 兄弟，确实如你所说，清空宿主机映射目录后重启运行容器就可以了，非常感谢。

最后做个总结（本issue不涉及集群和涛思版本升级，仅是taos2.0.3的单个docker容器环境搭建）：
1、宿主机中创建映射目录（目录不要含有以前的涛思运行数据，特别是/var/lib/taos对应的映射目录）
2、创建容器：docker run --name tdengine --hostname="mytest" -v /home/tdenginedb/data:/var/lib/taos -v /home/tdenginedb/log:/var/log/taos -p 6030-6042:6030-6042 -p 6030-6042:6030-6042/udp --restart=always
-d tdengine/tdengine
3、再到windows的host文件中增加：[宿主机器ip] mytest

最后，感谢官方，感谢 @cicistudio2000 @Flyerison 提供的方法和思路。

**Comment by daconglee** [comment]
客户端（Windows10）就参照文档添加一下hosts文件的IP域名映射即可

**Comment by rennner** [comment]
@daconglee 这个问题已经结了。如果真如你所说的那么简单，就不用讨论那么多了。

**Comment by codering** [comment]
> @cicistudio2000 兄弟，确实如你所说，清空宿主机映射目录后重启运行容器就可以了，非常感谢。
> 
> 最后做个总结（本issue不涉及集群和涛思版本升级，仅是taos2.0.3的单个docker容器环境搭建）：
> 1、宿主机中创建映射目录（目录不要含有以前的涛思运行数据，特别是/var/lib/taos对应的映射目录）
> 2、创建容器：docker run --name tdengine --hostname="mytest" -v /home/tdenginedb/data:/var/lib/taos -v /home/tdenginedb/log:/var/log/taos -p 6030-6042:6030-6042 -p 6030-6042:6030-6042/udp --restart=always
> -d tdengine/tdengine
> 3、再到windows的host文件中增加：[宿主机器ip] mytest
> 
> 最后，感谢官方，感谢 @cicistudio2000 @Flyerison 提供的方法和思路。

先前的数据不要了？

**Comment by 419845351** [comment]
大佬们，你们使用docker的话，数据是怎么备份的呢？删掉容器，数据咋办呢？

**Comment by sangshuduo** [comment]
@419845351 用 docker volume

**Comment by woshipptaku** [comment]
> [宿主机器ip]

的确是就好了

**Comment by rmokerone** [comment]
感觉莫名其妙，本来IP直接就能连上，为什么非要弄FQDN限制下。

**Comment by pkptzx** [comment]
关于docker的这个问题,为什么不写到文档里,说好的`快速体验`呢?体验了个寂寞~~~

**Comment by CraxGrix** [comment]
> 关于docker的这个问题,为什么不写到文档里,说好的`快速体验`呢?体验了个寂寞~~~

文档的确写的不咋地。。。每次搞配置都恼火的要死
