### ISSUE TITLE
Error in query. TDengine Error: invalid num of fields!

### ISSUE THREAD

**Issue by zhouzhiy** [taosdata/TDengine#3431]
**Bug Description**

windows客户端版本：TDengine-client-2.0.3.0-Windows-x64.exe
服务器端版本：TDengine-server-2.0.3.0-Linux-x64.rpm
驱动版本：2.0.4
问题描述：
springboot集成mybatis
mapper中的sql：select last(peroid_time) as peroid_time,last(value) as value from iot_data.td_01_012e00000011_00d00017_01
resultMap:
```
<resultMap id="BaseResultMap" type="com.glodon.data.entity.ScadaValueVo" >
                <result column="peroid_time" property="peroidTime" jdbcType="TIMESTAMP" />
                <result column="value" property="value" jdbcType="DOUBLE" />
                <result column="gather_key" property="gatherKey" jdbcType="VARCHAR" />
    </resultMap>
```
超级表结构：
create table td_012e000000a1 (peroid_time TIMESTAMP,value FLOAT,data_type INT) TAGS (type INT);
sql执行报错信息：
Cause: java.sql.SQLException: TDengine Error: invalid num of fields!
; uncategorized SQLException; SQL state [null]; error code [0]; TDengine Error: invalid num of fields!; nested exception is java.sql.SQLException: TDengine Error: invalid num of fields!
[hs_err_pid32192.log](https://github.com/taosdata/TDengine/files/5186595/hs_err_pid32192.log)

**Comment by cleverpig** [comment]
Please fix this wrong in the offical guide( https://www.taosdata.com/en/documentation/connector/#Java-Connector ):
![image](https://user-images.githubusercontent.com/580435/96336145-0f2fa000-10b0-11eb-91f5-f792f3c516ab.png)
Jdbc 1.0 doesn't work with server 2.0, It's waste time of developer for searching and find problem.
Jdbc 2.0up version will work on the servder which is 2.0up Version!
