### ISSUE TITLE
Query interrupted (Out of memory), 0 row(s) in set (0.086905s)

### ISSUE THREAD

**Issue by freegodly** [taosdata/TDengine#3432]
写入几百万条数据后，查询报错，我需要修改哪里的配置？
taos> select * from raw_data_stb  where sample_time = '2020-09-08 14:30:00' ;
Query interrupted (Out of memory), 0 row(s) in set (0.086905s)

**Comment by Aries-Lee1991** [comment]
返回结果集过大，程序会自动不处理。上限是10万行。
