### ISSUE TITLE
jdbc配置集群连接方式

### ISSUE THREAD

**Issue by weicz1221** [taosdata/TDengine#3433]
查看了关于TAOSC的相关文档，内嵌于JDBC，应用都是通过taosc而不是直接连接集群中的数据节点与整个集群进行交互的。查看了相关驱动代码，没找到相应的办法。关于使用JDBC连接集群的配置方式，能不能给个示例，或者思路？谢谢

**Comment by zyyang-taosdata** [comment]
jdbcUrl里写master的fqdn就可以连，不需要做特殊配置。

**Comment by weicz1221** [comment]
假如我本来有3台服务器的集群server01,server02,server03,  server01是master节点，3台服务器正常运行，jdbcUrl里写的是server01，这时可以正常访问，假如这是server01服务器挂掉了，有没有什么办法在不干预应用程序的情况下，保存应用程序正常访问数据库。本来我的想法是通过nginx进行代理，尝试了一下，没有连接成功，

nignx配置如下：

stream {
    upstream tdengin {
        hash $remote_addr consistent;
        server server01:6030 max_fails=3 fail_timeout=30s;
	server server02:6030 max_fails=3 fail_timeout=30s;
	server server03:6030 max_fails=3 fail_timeout=30s;
    }
    server {
        listen 6030;
        proxy_connect_timeout 30s;
        proxy_timeout 600s;
        proxy_pass tdengin;
    }
}

jdbc连接：url: jdbc:TAOS://localhost:6030/demo


针对这样的需求，不知道您有什么好的建议？

**Comment by zyyang-taosdata** [comment]
可以在taosc.cfg里配置了firstEp和secondEp，taosc会根据firstEp和secondEp的配置来做故障转移

**Comment by chuangtim** [comment]
@zyyang-taosdata 不对，master掉线就不能连接
