### ISSUE TITLE
Incomplete SQL statement 

### ISSUE THREAD

**Issue by huangbotao** [taosdata/TDengine#3434]
**Incomplete SQL statement **
在创建超级表的时候用单引号扩这超级表名，在用超级表的模版创建子表的时候，抛出异常如下，请帮忙查看是什么原因？

1.使用的版本 TDengine 2.0.1.0
2.创建的超级表语句： `CREATE TABLE IF NOT EXISTS 'ACLN' (ts TIMESTAMP, 'H' DOUBLE  ) TAGS (station_id BINARY(64), envionment BINARY(64));`
3.用超级表模版创建子表的语句：`CREATE TABLE CAxxx_xxxx02 USING 'ACLN' TAGS('CAxxxx01','online');`
4.抛出的异常：`DB error: invalid SQL: Incomplete SQL statement`

说明：以上的异常信息是所有异常信息
我还尝试了别的创建语句，都是这样的异常
![image](https://user-images.githubusercontent.com/36856212/92450534-23010000-f1ee-11ea-9198-2703c2e5c4aa.png)

**Comment by zyyang-taosdata** [comment]
database、stable、table的名称不需要加单引号

**Comment by huangbotao** [comment]
> database、stable、table的名称不需要加单引号

这里的单引号，是为了保证大小写一致，如果不加单引号，的话TDengine会统一转化为小写

**Comment by huangbotao** [comment]
> database、stable、table的名称不需要加单引号

在TDengine中默认将大写字符全部转为小写处理，如果需要保留大写字符，需要用单引号括起来。我这里的单引号去掉就会全部转为小写，影响业务查询。有没有保持大小写不变的其他方式建超级表，并可以用超级表模版创建子表的方案？

**Comment by zyyang-taosdata** [comment]
```
taos> use test;
Database changed.

taos> create table 'ACLN' (ts timestamp, 'H' double) tags(station_id nchar(64),environment binary(64));
Query OK, 0 row(s) affected (0.007610s)

taos> show stables;
              name              |      created_time       | columns |  tags  |   tables    |
============================================================================================
 ACLN                           | 2020-09-10 18:26:12.848 |       2 |      2 |           0 |
Query OK, 1 row(s) in set (0.001981s)

taos> create table 'CAxxx_xxx02' using 'ACLN' tags("CAxxx01","online");

taos> create table 'CAxxx_xxx02' using "ACLN" tags("CAxxx01","online");
Query OK, 0 row(s) affected (0.009519s)

taos> show tables;
           table_name           |      created_time       | columns |          stable_name           |
======================================================================================================
 weather                        | 2020-09-10 17:53:05.577 |       3 |                                |
 CAxxx_xxx02                    | 2020-09-10 18:29:16.243 |       2 | ACLN                           |
Query OK, 2 row(s) in set (0.013443s)
```
