### ISSUE TITLE
 Start taosd, the log file time is in doubt

### ISSUE THREAD

**Issue by whwqs** [taosdata/TDengine#3435]
关闭taosd，清除文件后，重启taosd，日志文件上面的时间感觉不对。
步骤：
1、systemctl stop taosd
2、rm -rf /var/lib/taos
3、rm -rf /var/log/taos
4、systemctl start taosd
打开taosdlog.0，不太理解日志的时间：
==================================================
                new log file                      
==================================================
09/08 16:09:20.472483 0x7fa15280d740 UTL localEp is: redis.sp.loc:6030
09/08 16:09:20.472901 0x7fa15280d740 UTL timezone is set to Asia/Shanghai by config file
09/09 03:09:20.472946 0x7fa15280d740 UTL timezone format changed to (CDT, +0900)
09/09 03:09:20.472955 0x7fa15280d740 UTL    taos config & system info:
09/09 03:09:20.472958 0x7fa15280d740 UTL ==================================
09/09 03:09:20.472961 0x7fa15280d740 UTL  firstEp:                redis.sp.loc:6030 
09/09 03:09:20.472965 0x7fa15280d740 UTL  secondEp:               redis.sp.loc:6030 
09/09 03:09:20.472967 0x7fa15280d740 UTL  fqdn:                   redis.sp.loc 
09/09 03:09:20.472970 0x7fa15280d740 UTL  serverPort:             6030 
09/09 03:09:20.472973 0x7fa15280d740 UTL  configDir:              /etc/taos 
前面两行是当前时间9月8日，后面的时间就变成了9月9日
[taosdlog.zip](https://github.com/taosdata/TDengine/files/5187101/taosdlog.zip)

**Comment by Aries-Lee1991** [comment]
您好， 看了这三行，是时区改变了，时间肯定是跟着时区走的啊。你先确认一下服务器的时区。
09/08 16:09:20.472483 0x7fa15280d740 UTL localEp is: redis.sp.loc:6030
09/08 16:09:20.472901 0x7fa15280d740 UTL timezone is set to Asia/Shanghai by config file
09/09 03:09:20.472946 0x7fa15280d740 UTL timezone format changed to (CDT, +0900)

**Comment by zyyang-taosdata** [comment]
taosdlog里有一行会打印当前启动实例的时区，检查一下是不是因为时区变化造成的

```
UTL  timezone:                (CST, +0800) 
```

**Comment by zyyang-taosdata** [comment]
在taos.cfg里设置了时区，所以时区会变更，时间也会变化。

**Comment by whwqs** [comment]
在linux服务器上：
ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime 设置时区为东八区 原来的时区是 -0300
date -s "17:12:00 2020-09-08" 修改成正确时间
ok，一切正常了
