### ISSUE TITLE
After running taosdemo, after printing "Inserting data..." on the screen, there is no other printing, which has been the same for more than ten minutes

### ISSUE THREAD

**Issue by whwqs** [taosdata/TDengine#3444]
[root@redis ~]# taosdemo
###################################################################
# Server IP:                         localhost:0
# User:                              root
# Password:                          taosdata
# Use metric:                        true
# Datatype of Columns:               int int int int int int int float
# Binary Length(If applicable):      -1
# Number of Columns per record:      3
# Number of Threads:                 10
# Number of Tables:                  10000
# Number of Data per Table:          100000
# Records/Request:                   1000
# Database name:                     test
# Table prefix:                      t
# Delete method:                     0
# Test time:                         2020-09-09 09:37:05
###################################################################

Press enter key to continue
Creating meters super table...
meters created!
create table......
Creating table from 0 to 999
Creating table from 1000 to 1999
Creating table from 2000 to 2999
Creating table from 3000 to 3999
Creating table from 4000 to 4999
Creating table from 5000 to 5999
Creating table from 6000 to 6999
Creating table from 7000 to 7999
Creating table from 8000 to 8999
Creating table from 9000 to 9999
Spent 18.0625 seconds to create 10000 tables with 10 connections
Inserting data......

**Comment by plum-lihui** [comment]
从指定的参数看，这次执行taosdemo要插入10亿条记录（Number of Tables: 10000 * Number of Data per Table: 100000），应该需要稍微长点时间，当然还与所在的机器配置相关。
是否taosdemo仍然处于正常插入数据中，可以启动一个taos，检查一下是否表的记录数还在继续增长。
taos> use test;
taos> seletc count(*) from meters;
多执行几次，是不是每次查询的结果都还在增长，说明还没有结束。

你也可以少插入点记录数，比如1000万条，taosdemo应该很快就能执行完成。

**Comment by whwqs** [comment]
应该是虚拟机配置太低，使得运行慢
