### ISSUE TITLE
 Cause: java.sql.SQLException: TDengine Error: Invalid message

### ISSUE THREAD

**Issue by tony358** [taosdata/TDengine#3448]
TDengine使用版本为2.0.3.0   客户端java应用为windows环境，使用taos-jdbcdriver为2.0.4

java应用的jdbc配置信息如下：
      url: jdbc:TAOS://192.168.2.52:6030/iomp
      username: root
      password: taosdata
      driver-class-name: com.taosdata.jdbc.TSDBDriver

客户端应用在执行SQL查询时，出错详细信息如下：
### Cause: java.sql.SQLException: TDengine Error: Invalid message
; uncategorized SQLException; SQL state []; error code [-2147481855]; TDengine Error: Invalid message; nested exception is java.sql.SQLException: TDengine Error: Invalid message

有使用taos命令是可以正常查询的。
![image](https://user-images.githubusercontent.com/26424684/92552888-41213b80-f294-11ea-97ba-f7037b70db00.png)

TDengine日志信息如下:
09/09 11:28:40.526288 0x7f452b30e740 MON start monitor module
09/09 11:28:40.526311 0x7f452b30e740 DND TDengine is initialized successfully
09/09 11:28:40.526342 0x7f45177e6700 HTP http server init success at 6041
09/09 11:28:40.538769 0x7f45294e9700 MON starting to initialize monitor service ..
09/09 11:28:40.540444 0x7f45207f8700 MND user:monitor login from 192.168.2.52, result:success
09/09 11:28:40.541389 0x7f4516618700 MON dnode:master52:6030 is started
09/09 11:28:40.543770 0x7f4516618700 MON monitor service init success
09/09 11:28:41.029527 0x7f45217fa700 VND vgId:2, not exist
09/09 11:28:41.029655 0x7f45237fe700 DND module status:6 is received, start mnode module
09/09 11:28:41.029693 0x7f45237fe700 MND mnode module already started...
09/09 11:28:41.029964 0x7f45217fa700 VND vgId:2, save vnode cfg successed
09/09 11:28:41.030044 0x7f45217fa700 VND vgId:2, vnode is created, walLevel:1 fsyncPeriod:3000
09/09 11:28:41.030160 0x7f45217fa700 VND vgId:2, read vnode cfg successfully, replcia:1
09/09 11:28:41.030177 0x7f45217fa700 VND vgId:2, dnode:1, master52:6040
09/09 11:28:41.030265 0x7f45217fa700 VND vgId:2, read vnode version successfully, version:31
09/09 11:28:41.032676 0x7f45217fa700 VND vgId:2, sync role changed from offline to master
09/09 11:28:41.032704 0x7f45217fa700 DND force send status msg to mnode
09/09 11:28:41.032935 0x7f45217fa700 VND vgId:3, not exist
09/09 11:28:41.033198 0x7f45217fa700 VND vgId:3, save vnode cfg successed
09/09 11:28:41.033267 0x7f45217fa700 VND vgId:3, vnode is created, walLevel:1 fsyncPeriod:3000
09/09 11:28:41.033372 0x7f45217fa700 VND vgId:3, read vnode cfg successfully, replcia:1
09/09 11:28:41.033388 0x7f45217fa700 VND vgId:3, dnode:1, master52:6040
09/09 11:28:41.033471 0x7f45217fa700 VND vgId:3, read vnode version successfully, version:2
09/09 11:28:41.034941 0x7f45217fa700 VND vgId:3, sync role changed from offline to master
09/09 11:28:41.034965 0x7f45217fa700 DND force send status msg to mnode
09/09 11:29:04.433081 0x7f45207f8700 MND user:root login from 192.168.2.190, result:success
09/09 11:29:11.378333 0x7f4515616700 QRY ERROR qmsg:0x7f44fc001088 illegal value of output columns 22016
09/09 11:29:11.378937 0x7f4514e15700 QRY ERROR qmsg:0x7f44fc001088 illegal value of output columns 22016
09/09 11:29:11.379653 0x7f44dffff700 QRY ERROR qmsg:0x7f44fc001088 illegal value of output columns 22016
09/09 11:29:11.380204 0x7f44df7fe700 QRY ERROR qmsg:0x7f44fc001088 illegal value of output columns 22016

后面TDengine换成2.0.1.1的版本，没有这个问题。

**Comment by sangshuduo** [comment]
2.0.3.1 已经解决了这个问题，谢谢

**Comment by tony358** [comment]
@sangshuduo 好的，收到。
