### ISSUE TITLE
Unable to resolve FQDN

### ISSUE THREAD

**Issue by GhostHow** [taosdata/TDengine#3450]
使用 JDBC连接，报错Unable to resolve FQDN。
使用taos.exe -h 192.168.8.61   连接成功

**Comment by GhostHow** [comment]
![1599637757(1)](https://user-images.githubusercontent.com/37834032/92572104-8d7d7300-f2b6-11ea-92ca-c3c30c861392.jpg)

**Comment by GhostHow** [comment]
![1599638916(1)](https://user-images.githubusercontent.com/37834032/92572254-c3baf280-f2b6-11ea-8c87-9bb8f9490203.jpg)

**Comment by GhostHow** [comment]
![1599640829(1)](https://user-images.githubusercontent.com/37834032/92575714-434ac080-f2bb-11ea-90ad-cbecde2d93fe.jpg)

**Comment by GhostHow** [comment]
追踪代码到jni方法，产生异常

**Comment by Aries-Lee1991** [comment]
@GhostHow 参考https://www.taosdata.com/cn/documentation/faq/，第六条，看看是否可以解决。

**Comment by hjxilinx** [comment]
原因是，在启动数据库之后重新修改了 FQDN,将 FQDN 重置为原来的值以后，连接正常。
