### ISSUE TITLE
Chinese characters display garbled and some of them storage failed by jdbc 2.0.4 

### ISSUE THREAD

**Issue by 379547990** [taosdata/TDengine#3456]
版本信息：
服务端：TDengine-server-2.0.1.1-Linux-x64 + ubuntu 18.04_x64
客户端：Springboot+mybatis + JDBC 2.0.4 + TDengine-client-2.0.1.1-Windows-x64  + Win10

mybatis mapper 配置如下：
![image](https://user-images.githubusercontent.com/70123240/92625279-07cfe680-f2fb-11ea-8e5c-98e55457464f.png)

jdbc 配置
![image](https://user-images.githubusercontent.com/70123240/92625079-d820de80-f2fa-11ea-89c9-ad6775720929.png)
以下是一些测试场景
ubuntu服务端执行insert 包含**中文**字段语句,select  查询正常
例如：
taos> insert into rainstation.S_57037 using rainstation.monitoring tags('57037','耀州') (ts, name, c
ode,rainfall) values ('2006-01-19 17:00:00.000', '耀州', '57037','0.0');
Query OK, 1 row(s) affected (0.003638s)

taos> select * from s_57037;
           ts            |              name              |    code    |       rainfall       |
===============================================================================================
 2006-01-19 17:00:00.000 | 耀州                           | 57037      |              0.00000 |
Query OK, 1 row(s) in set (0.156975s)

客户端java 接口入库测试
**name 包含“耀州” 异常了**
![image](https://user-images.githubusercontent.com/70123240/92623776-49f82880-f2f9-11ea-9354-80f402ae844b.png)

下面把 **name  字段改成 湖北，执行，返回正常**
![image](https://user-images.githubusercontent.com/70123240/92623965-8cba0080-f2f9-11ea-85a7-2d42d4c42f44.png)
执行查询操作，查找到 **湖北  变成乱码**了，耀州 没有入库成功
<pre>taos&gt; select * from s_5364611;
           ts            |              name              |    code    |       rainfall       |
===============================================================================================
 2006-01-01 00:00:00.100 | 婀栧寳                         | 5364611    |         999999.00000 |
Query OK, 1 row(s) in set (0.004162s)
</pre>

**Comment by hjxilinx** [comment]
中文使用 nchar 类型的字段存储，不要使用 binary 存储。此外还必须要保证客户端正确设置了 charset 信息。

**Comment by 379547990** [comment]
> 中文使用 nchar 类型的字段存储，不要使用 binary 存储。此外还必须要保证客户端正确设置了 charset 信息。
建表试用的  nchar 类型， 客户端配置是默认的，没有修改 ，默认也是   utf-8
create table if not exists rainstation.monitoring(ts timestamp, name NCHAR(10),code BINARY(8), rainfall float)
TAGS (station_code BINARY(8), station_name NCHAR(10));

**Comment by hjxilinx** [comment]
win10的机器，默认的 charset 是  cp936。 不是 utf-8。但是你需要将您的 JAVA 文件编码设置成为 utf-8.

**Comment by hjxilinx** [comment]
您的 URL 中，最好不要把 log 库作为默认的连接库。可以不指定默认的连接库。

**Comment by 379547990** [comment]
> win10的机器，默认的 charset 是 cp936。 不是 utf-8。但是你需要将您的 JAVA 文件编码设置成为 utf-8.

![image](https://user-images.githubusercontent.com/70123240/92693005-92562b80-f377-11ea-84ad-6c02a701e19b.png)
您说的是 客户端配置文件吗

**Comment by hjxilinx** [comment]
是的，设置为 
charset CP936

**Comment by 379547990** [comment]
> 是的，设置为
> charset CP936
我把 java  程序部署到 ubuntu 服务器上测试 中文正常
![image](https://user-images.githubusercontent.com/70123240/92863047-094dfb80-f42e-11ea-9155-b5ec0e806e85.png)

<pre>taos&gt; select * from  rainstation.s_6789_fxl;
           ts            |              name              |    code    |       rainfall       |
===============================================================================================
 2006-01-01 00:00:00.100 | 马超                           | 6789_fxl   |         999999.00000 |
Query OK, 1 row(s) in set (0.141465s)

taos&gt; 
</pre>
win 10 上面部署java 程序测试 ，并把 编码改到 charset CP936  ，依然还是出现乱码。
![image](https://user-images.githubusercontent.com/70123240/92863469-8b3e2480-f42e-11ea-8009-64e5b6fc7016.png)

**Comment by 379547990** [comment]
![image](https://user-images.githubusercontent.com/70123240/92872820-fee52f00-f438-11ea-874b-34fcc94ef538.png)
JDBC  设置 编码 后，window 机器入库，显示正常
<pre>taos&gt; select * from rainstation.s_678910;
           ts            |              name              |    code    |       rainfall       |
===============================================================================================
 2006-01-01 00:00:00.100 | 椹秴                          | 678910     |         999999.00000 |
 2006-01-01 00:00:01.100 | 马超2                          | 678910     |         999999.00000 |
Query OK, 2 row(s) in set (0.004769s)
</pre>

**Comment by fake2ky** [comment]
从2.4升级到2.6就出现问题了.  
按照jdbc-url的方式设置才能成功 ,  这是否存在win10无法读取cfg配置问题.
