### ISSUE TITLE
Query STable  by tags, timestamp exception

### ISSUE THREAD

**Issue by lxp119** [taosdata/TDengine#3458]
超级表
create table if not exists iot_meters (ts timestamp,v1 double,v2 double,v3 double,v4 double ,v5 double) TAGS(group_id int,device_id int);
插入2万张
查询语句：
select count(*), avg(v1) from iot_meters where device_id = 10001 interval(10a);
select count(*), avg(v1) from iot_meters where device_id>10000 and device_id<10002 interval(10a);
![1](https://user-images.githubusercontent.com/69295314/92674865-cbc77080-f350-11ea-880e-ba41a22b3c20.png)
[1.txt](https://github.com/taosdata/TDengine/files/5198837/1.txt)

**Comment by lxp119** [comment]
最新版本

**Comment by yihaoDeng** [comment]
你可以试试在在进入taos -r， 然后做类似的查询， 看看多次返回的第一列是不是相同， 并把结果和日志贴给我们

**Comment by lxp119** [comment]
使用taos - r 后 数据都一样。使用taos  还是之前那样子，时而正常时而不正常。
[result+log.zip](https://github.com/taosdata/TDengine/files/5200801/result%2Blog.zip)

**Comment by yihaoDeng** [comment]
> 使用taos - r 后 数据都一样。使用taos 还是之前那样子，时而正常时而不正常。
> [result+log.zip](https://github.com/taosdata/TDengine/files/5200801/result%2Blog.zip)

请问你用的什么精度的，ms还是us

**Comment by lxp119** [comment]
us

**Comment by yihaoDeng** [comment]
> us

好的， develop分支已经解决了这个问题， 很快能发版
