### ISSUE TITLE
Remove the dependency StringUtils in JDBC Driver.

### ISSUE THREAD

**Issue by Edassap** [taosdata/TDengine#3459]
It's seems that no necessary to include the StringUtils in this driver.Without the dependency we can use it as driver in DataGrip, implement the data visualizing directly! Isn't that delicious? Take it into your consideration! Thanks!(Just a tool , and I don't want learn java for this tool simply)

**Comment by hjxilinx** [comment]
Thanks for your suggestions. 
We have removed the dependency on StringUtil. And it will be available in next release in two weeks.
