### ISSUE TITLE
The data is not stored in the database, but the interface returns 1

### ISSUE THREAD

**Issue by JackeyWin** [taosdata/TDengine#3461]
导入时间戳重复的数据，实际数据丢弃，未入库，但接口返回1，希望返回0

使用1.6版本时，接口还能够返回0，升级到2.0版本之后，接口都是返回1

目前环境中可能出现时间戳相同，但实际数据有差异的数据，我想把数据都处理入库，需要判断接口的返回值，现在执行executeUpdate，数据未入库，返回值也是1，可能会造成数据丢失

**Comment by sangshuduo** [comment]
谢谢，我们评估一下

**Comment by hzcheng** [comment]
请问update能解决你们现在遇到的问题吗？

**Comment by hjxilinx** [comment]
麻烦把您的场景更加清楚地描述一下。谢谢！
是否是由于时间戳精度不够导致的时间戳重复（有多条记录均均有相同的秒级精度的时间戳），从而导致数据无法入库？

**Comment by JackeyWin** [comment]
数据源的时间精度只能到毫秒级，所以会有可能产生时间戳相同的数据，但是这些数据实际可能是不相同的，现在数据源的时间精度无法修改，只能我后端这边来处理。
我看滔思的文档，遇到时间戳相同的数据，是会被丢弃的，我在实际测试中，数据确实并没有入库，但是执行executeUpdate接口返回的数据却是1，这里返回的应该是被影响的数据行数吧？不然成功入库和被丢弃的数据返回都是1，我这里就没法判断哪些数据需要做处理，之前使用的版本好像是可以返回0的，是不是接口做了什么修改？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taosdata/TDengine"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月10日(星期四) 下午3:23
收件人:&nbsp;"taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送:&nbsp;"鬼画符"<583115474@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [taosdata/TDengine] 数据未入库，但接口返回1 (#3461)





 
麻烦把您的场景更加清楚地描述一下。谢谢！
 是否是由于时间戳精度不够导致的时间戳重复（有多条记录均均有相同的秒级精度的时间戳），从而导致数据无法入库？

**Comment by hjxilinx** [comment]
简单的一点的处理方法，建库到微秒进度。
每条记录在毫秒精度基础上，在微秒精度位使用流水号轮转，每一条记录+1， 流水号到999以后，重复从0再次开始。
如果系统中同一个毫秒没有超过1000条记录均可。

**Comment by hzcheng** [comment]
2.0的接口确实有修改，返回值指的是该批数据中在库中的条数，所以，没有跟新入库也会返回1。2.0在架构上避免了1.6的那种机制。

**Comment by JackeyWin** [comment]
OK，应该可以满足我的需求

 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "haojun Liao"<notifications@github.com&gt;; 
发送时间: 2020年9月10日(星期四) 下午3:35
收件人: "taosdata/TDengine"<TDengine@noreply.github.com&gt;; 
抄送: "鬼画符"<583115474@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [taosdata/TDengine] The data is not stored in the database, but the interface returns 1 (#3461)





 
简单的一点的处理方法，建库到微秒进度。
 每条记录在毫秒精度基础上，在微秒精度位使用流水号轮转，每一条记录+1， 流水号到999以后，重复从0再次开始。
 如果系统中同一个毫秒没有超过1000条记录均可。
