### ISSUE TITLE
The windows client can't connect to the linux server

### ISSUE THREAD

**Issue by moziie** [taosdata/TDengine#3467]
无法建立连接后，日志文件中最后一行ERROR TSC, failed to create eventfd(File exists)，我已经按照FAQ中步骤处理过，能ping通，端口6030到6042全部打开，防火墙也关了，但是依旧报错无法建立连接，请问哪里还有问题呢，补充一下linux服务器上使用taos -h ip也无法建立连接，但是使用taos -h 127.0.0.1就可以

**Comment by sangshuduo** [comment]
先解决 Linux 上连接，把 /etc/taos/taos.cfg 中 debugFlag 设为 135，然后用 taos -h ip -c /etc/taos 连不上后再看一下 /var/log/taos/taoslog0.0 最近一段的错误输出是什么？

**Comment by localvar** [comment]
failed to create eventfd(File exists) 本身不是严重问题，它实际上是由于无法建立连接导致的。
对于无法连接的问题，您可以把远程连接方式发到 bmzhang@taosdata.com 吗？

**Comment by moziie** [comment]
> 先解决 Linux 上连接，把 /etc/taos/taos.cfg 中 debugFlag 设为 135，然后用 taos -h ip -c /etc/taos 连不上后再看一下 /var/log/taos/taoslog0.0 最近一段的错误输出是什么？

日志文件最新内容 new log file                      
==================================================
09/10 15:22:30.178125 0x7fdffa6cb200 UTL all debug flag are set to 135
09/10 15:22:30.178342 0x7fdffa6cb200 UTL localEp is: VM-0-3-centos:6030
09/10 15:22:30.178489 0x7fdffa6cb200 UTL timezone not configured, set to system default: (CST, +0800)
09/10 15:22:30.178549 0x7fdffa6cb200 UTL ERROR locale not configured, set to system default:en_US.utf8
09/10 15:22:30.178557 0x7fdffa6cb200 UTL WARN charset not configured, set to system default:UTF-8
09/10 15:22:30.178571 0x7fdffa6cb200 UTL    taos config & system info:
09/10 15:22:30.178575 0x7fdffa6cb200 UTL ==================================
09/10 15:22:30.178576 0x7fdffa6cb200 UTL  firstEp:                VM-0-3-centos:6030 
09/10 15:22:30.178577 0x7fdffa6cb200 UTL  secondEp:               VM-0-3-centos:6030 
09/10 15:22:30.178579 0x7fdffa6cb200 UTL  fqdn:                   VM-0-3-centos 
09/10 15:22:30.178580 0x7fdffa6cb200 UTL  serverPort:             6030 
09/10 15:22:30.178581 0x7fdffa6cb200 UTL  configDir:              /var/log/taos 
09/10 15:22:30.178582 0x7fdffa6cb200 UTL  logDir:                 /var/log/taos 
09/10 15:22:30.178584 0x7fdffa6cb200 UTL  scriptDir:              /etc/taos 
09/10 15:22:30.178585 0x7fdffa6cb200 UTL  arbitrator:              
09/10 15:22:30.178586 0x7fdffa6cb200 UTL  numOfThreadsPerCore:    1.000000 
09/10 15:22:30.178596 0x7fdffa6cb200 UTL  rpcTimer:               1000(ms)
09/10 15:22:30.178597 0x7fdffa6cb200 UTL  rpcMaxTime:             600(s)
09/10 15:22:30.178599 0x7fdffa6cb200 UTL  shellActivityTimer:     3(s)
09/10 15:22:30.178600 0x7fdffa6cb200 UTL  tableMetaKeepTimer:     7200(s)
09/10 15:22:30.178601 0x7fdffa6cb200 UTL  compressMsgSize:        -1 
09/10 15:22:30.178603 0x7fdffa6cb200 UTL  maxSQLLength:           65480(byte)
09/10 15:22:30.178604 0x7fdffa6cb200 UTL  maxNumOfOrderedRes:     100000 
09/10 15:22:30.178606 0x7fdffa6cb200 UTL  timezone:                (CST, +0800) 
09/10 15:22:30.178607 0x7fdffa6cb200 UTL  locale:                 en_US.utf8 
09/10 15:22:30.178608 0x7fdffa6cb200 UTL  charset:                UTF-8 
09/10 15:22:30.178610 0x7fdffa6cb200 UTL  numOfLogLines:          10000000 
09/10 15:22:30.178611 0x7fdffa6cb200 UTL  asyncLog:               1 
09/10 15:22:30.178613 0x7fdffa6cb200 UTL  debugFlag:              135 
09/10 15:22:30.178614 0x7fdffa6cb200 UTL  rpcDebugFlag:           135 
09/10 15:22:30.178615 0x7fdffa6cb200 UTL  tmrDebugFlag:           131 
09/10 15:22:30.178617 0x7fdffa6cb200 UTL  cDebugFlag:             135 
09/10 15:22:30.178618 0x7fdffa6cb200 UTL  jniDebugFlag:           135 
09/10 15:22:30.178619 0x7fdffa6cb200 UTL  odbcDebugFlag:          135 
09/10 15:22:30.178621 0x7fdffa6cb200 UTL  uDebugFlag:             135 
09/10 15:22:30.178622 0x7fdffa6cb200 UTL  qDebugFlag:             135 
09/10 15:22:30.178624 0x7fdffa6cb200 UTL  tsdbDebugFlag:          135 
09/10 15:22:30.178625 0x7fdffa6cb200 UTL  gitinfo:                1527828603722a0ed8ea706439e8c172a13b7eb1 
09/10 15:22:30.178626 0x7fdffa6cb200 UTL  gitinfoOfInternal:       
09/10 15:22:30.178628 0x7fdffa6cb200 UTL  buildinfo:              Built by root at 2020-08-26 12:00 
09/10 15:22:30.178629 0x7fdffa6cb200 UTL  version:                2.0.2.1 
09/10 15:22:30.178630 0x7fdffa6cb200 UTL  maxBinaryDisplayWidth:  30 
09/10 15:22:30.178632 0x7fdffa6cb200 UTL  os pageSize:            4096(KB)
09/10 15:22:30.178634 0x7fdffa6cb200 UTL  os openMax:             100001
09/10 15:22:30.178635 0x7fdffa6cb200 UTL  os streamMax:           16
09/10 15:22:30.178636 0x7fdffa6cb200 UTL  os numOfCores:          8
09/10 15:22:30.178638 0x7fdffa6cb200 UTL  os totalDisk:           0.000000(GB)
09/10 15:22:30.178639 0x7fdffa6cb200 UTL  os totalMemory:         15875(MB)
09/10 15:22:30.178641 0x7fdffa6cb200 UTL  os sysname:             Linux
09/10 15:22:30.178642 0x7fdffa6cb200 UTL  os nodename:            VM-0-3-centos
09/10 15:22:30.178643 0x7fdffa6cb200 UTL  os release:             4.18.0-80.el8.x86_64
09/10 15:22:30.178644 0x7fdffa6cb200 UTL  os version:             #1 SMP Tue Jun 4 09:19:46 UTC 2019
09/10 15:22:30.178645 0x7fdffa6cb200 UTL  os machine:             x86_64
09/10 15:22:30.178648 0x7fdffa6cb200 UTL ==================================
09/10 15:22:30.178649 0x7fdffa6cb200 TSC starting to initialize TAOS client ...
09/10 15:22:30.178650 0x7fdffa6cb200 TSC Local End Point is:VM-0-3-centos:6030
09/10 15:22:30.178904 0x7fdffa6cb200 UTL tsc scheduler is initialized, numOfThreads:4
09/10 15:22:30.178995 0x7fdffa6cb200 UTL tmr scheduler is initialized, numOfThreads:1
09/10 15:22:30.179211 0x7fdffa6cb200 TSC client is initialized successfully
09/10 15:22:30.179227 0x7fdffa6cb200 TSC try to create a connection to 192.168.49.30:0, user:root db:(null)
09/10 15:22:30.179253 0x7fdffa6cb200 UTL pool:0x19fa650 is setup, maxId:5000
09/10 15:22:30.179726 0x7fdffa6cb200 RPC TSC TCP client is initialized, ip:0:0
09/10 15:22:30.179736 0x7fdffa6cb200 UTL open udp socket:0x0:0
09/10 15:22:30.179808 0x7fdffa6cb200 RPC TSC UDP connection is initialized, ip:0:0 threads:1
09/10 15:22:30.179815 0x7fdffa6cb200 RPC TSC rpc is openned, threads:1 sessions:5000
09/10 15:22:30.179817 0x7fdffa6cb200 TSC dnodeConn:0x19fa570 is created, user:root
09/10 15:22:30.179825 0x7fdffa6cb200 TSC 0x1a681d0 SQL cmd:connect will be processed, name:(null), type:0
09/10 15:22:30.179829 0x7fdffa6cb200 RPC malloc mem: 0x1a69a20
09/10 15:22:30.179840 0x7fdff48d8700 RPC TSC UDP thread is created, index:0
09/10 15:22:30.179841 0x7fdffa6cb200 RPC TSC 0x7fdff51a8188 client connection is allocated, uid:0xf51b5a06
09/10 15:22:30.179983 0x7fdffa6cb200 RPC TSC UDP connection is setup, ip:6030e931:6030 localPort:60235
09/10 15:22:30.179990 0x7fdffa6cb200 RPC TSC 0x7fdff51a8188 0x1a681d0, connect is sent to 192.168.49.30:6030, len:345 sig:0x01000000:0x00000000:39411
09/10 15:22:31.184186 0x7fdff6b76700 RPC TSC 0x7fdff51a8188 0x1a681d0, expected connect-rsp is not received
09/10 15:22:31.184203 0x7fdff6b76700 RPC TSC 0x7fdff51a8188 0x1a681d0, re-send msg:connect to 192.168.49.30:6030
09/10 15:22:31.184210 0x7fdff6b76700 RPC TSC 0x7fdff51a8188 0x1a681d0, connect is sent to 192.168.49.30:6030, len:345 sig:0x01000000:0x00000000:39411
09/10 15:22:32.189181 0x7fdff6b76700 RPC TSC 0x7fdff51a8188 0x1a681d0, expected connect-rsp is not received
09/10 15:22:32.189194 0x7fdff6b76700 RPC TSC 0x7fdff51a8188 0x1a681d0, re-send msg:connect to 192.168.49.30:6030
09/10 15:22:32.189204 0x7fdff6b76700 RPC TSC 0x7fdff51a8188 0x1a681d0, connect is sent to 192.168.49.30:6030, len:345 sig:0x01000000:0x00000000:39411
09/10 15:22:33.194180 0x7fdff6b76700 RPC TSC 0x7fdff51a8188 0x1a681d0, expected connect-rsp is not received
09/10 15:22:33.194191 0x7fdff6b76700 RPC TSC 0x7fdff51a8188 0x1a681d0, re-send msg:connect to 192.168.49.30:6030
09/10 15:22:33.194197 0x7fdff6b76700 RPC TSC 0x7fdff51a8188 0x1a681d0, connect is sent to 192.168.49.30:6030, len:345 sig:0x01000000:0x00000000:39411
09/10 15:22:34.199181 0x7fdff6b76700 RPC TSC 0x7fdff51a8188 0x1a681d0, expected connect-rsp is not received
09/10 15:22:34.199195 0x7fdff6b76700 RPC TSC 0x7fdff51a8188 0x1a681d0, failed to send msg:connect to 192.168.49.30:6030
09/10 15:22:34.199204 0x7fdff6b76700 RPC TSC 0x7fdff51a8188 0x1a681d0, rpc connection is released
09/10 15:22:34.199206 0x7fdff6b76700 RPC TSC 0x1a681d0, connection error happens
09/10 15:22:34.199231 0x7fdff6b76700 TSC 0x1a681d0 SQL cmd:connect, code:Unable to establish connection rspLen:0
09/10 15:22:34.199241 0x7fdff6b76700 RPC free mem: 0x1a69a20
09/10 15:22:34.199262 0x7fdffa6cb200 TSC 0x1a681d0 start to free sql object
09/10 15:22:34.199301 0x7fdffa6cb200 TSC 0x1a681d0 start to free local reducer
09/10 15:22:34.199304 0x7fdffa6cb200 TSC 0x1a681d0 local reducer has been freed, abort
09/10 15:22:34.199311 0x7fdffa6cb200 TSC 0x1a681d0 SqlObj is freed by app, qhandle is null
09/10 15:22:34.199353 0x7fdffa6cb200 RPC TSC TCP client is stopped
09/10 15:22:34.199402 0x7fdff48d8700 RPC TSC UDP socket was closed, exiting(Success)
09/10 15:22:34.199527 0x7fdffa6cb200 RPC TSC UDP is stopped
09/10 15:22:34.199796 0x7fdff50d9700 RPC TSC TCP thread get stop event, exiting...
09/10 15:22:34.199883 0x7fdffa6cb200 RPC TSC TCP client is cleaned up
09/10 15:22:34.199910 0x7fdffa6cb200 RPC TSC UDP is cleaned up
09/10 15:22:34.199915 0x7fdffa6cb200 RPC TSC rpc is closed
09/10 15:22:34.200018 0x7fdffa6cb200 UTL pool:0x19fa650 is cleaned
09/10 15:22:34.200032 0x7fdffa6cb200 RPC TSC rpc resources are released
09/10 15:22:34.200034 0x7fdffa6cb200 TSC 0x1a68100 DB connection is closed, dnodeConn:0x19fa570

**Comment by hjxilinx** [comment]
这里没有错误信息。您可以直接把全部连不上的情况下的日志全部打包直接发到 @localvar 的邮箱。

**Comment by moziie** [comment]
可以了，参考这个https://www.taosdata.com/blog/2019/07/26/514.html

**Comment by hjxilinx** [comment]
OK
