### ISSUE TITLE
TDengine Error: Unable to establish connection

### ISSUE THREAD

**Issue by zhuhedong** [taosdata/TDengine#3468]
![image](https://user-images.githubusercontent.com/44915307/92689258-4a340a80-f371-11ea-942c-8bbd452315f0.png)

**Comment by sangshuduo** [comment]
请参考以下 FAQ：https://www.taosdata.com/cn/documentation/faq/

**Comment by zhuhedong** [comment]
已经按照这个检查了一边，都是好的，还是不行

**Comment by sangshuduo** [comment]
可以把相关代码贴一下吗？

**Comment by sangshuduo** [comment]
可以把相关代码贴一下吗？

**Comment by zhuhedong** [comment]
用的是你们examples文件夹里的springbootdemo项目

**Comment by zyyang-taosdata** [comment]
先检查使用taos的客户端是否能够连通taosd实例

**Comment by zhuhedong** [comment]
windows 平台，  6041端口可以直接使用，  其他端口用nc 也可以连通

**Comment by zhangyang1995** [comment]
请教一下最后如何解决的@zhuhedong

**Comment by zhuhedong** [comment]
检查数据库服务器一些端口开放权限

--------------原始邮件--------------
发件人："zhangyang1995 "<notifications@github.com&gt;;
发送时间：2020年9月29日(星期二) 上午10:46
收件人："taosdata/TDengine" <TDengine@noreply.github.com&gt;;
抄送："zhuhedong "<winter@winterblog.cn&gt;;"Mention "<mention@noreply.github.com&gt;;
主题：Re: [taosdata/TDengine] TDengine Error: Unable to establish connection (#3468)
-----------------------------------

 

 
请教一下最后如何解决的@zhuhedong

**Comment by zhangyang1995** [comment]
> 检查数据库服务器一些端口开放权限
> […](#)
> --------------原始邮件-------------- 发件人："zhangyang1995 "<notifications@github.com&gt;; 发送时间：2020年9月29日(星期二) 上午10:46 收件人："taosdata/TDengine" <TDengine@noreply.github.com&gt;; 抄送："zhuhedong "<winter@winterblog.cn&gt;;"Mention "<mention@noreply.github.com&gt;; 主题：Re: [taosdata/TDengine] TDengine Error: Unable to establish connection (#3468) ----------------------------------- 请教一下最后如何解决的@zhuhedong — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

已经解决！！ 非常感谢！！！
