### ISSUE TITLE
taosd收集json格式的日志

### ISSUE THREAD

**Issue by kevinniu666** [taosdata/TDengine#347]
背景
看了官方的文档，通过telegraf来搭建监控系统。
https://www.taosdata.com/blog/2019/07/10/a-quick-deployment-of-an-operational-monitoring-system-using-tdengine/
通过对telegraf的调研，可以通过[inputs.file]对日志文件进行监控，但是安装官方demo配置以后，无法将字符型的日志收录到Taosd中，参考文件如下:
https://github.com/influxdata/telegraf/tree/master/plugins/parsers/json
我的telegraf配置:

[global_tags]

[agent]
  interval = "10s"
  round_interval = true

  metric_batch_size = 1000

  metric_buffer_limit = 10000

  collection_jitter = "0s"

  flush_interval = "10s"
  flush_jitter = "0s"

  precision = ""

  debug = true

  logfile = "/var/log/telegraf/telegraf.log"

   logfile_rotation_interval = "1d"

   logfile_rotation_max_size = "100MB"

   logfile_rotation_max_archives = 5

  hostname = "telegraf"
  omit_hostname = false

[[outputs.http]]
  url = "http://localhost:6020/telegraf/alilog"
  method = "POST"
  username = "root"
  password = "taosdata"
  data_format = "json"
  json_timestamp_units = "1ms" 
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.disk]]

  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

[[inputs.diskio]]

[[inputs.kernel]]

[[inputs.mem]]

[[inputs.processes]]

[[inputs.swap]]

[[inputs.system]]

[[inputs.file]]
   files = ["/data/source_logs/*.log"]
   data_format = "json"

   name_override = "alilogs"
   json_string_fields = ["b_my_field"]

在taosd里面收录到的数据如下:
taos> select * from  alilogs_telegraf;
          ts          |           f_a           |          f_b_c          |
===========================================================================
 19-08-14 12:00:30.000|              5.000000000|              6.000000000|
 19-08-14 12:00:40.000|              5.000000000|              6.000000000|
 19-08-14 12:00:50.000|              5.000000000|              6.000000000|
Query OK, 3 row(s) in set (0.000344s)

**Comment by kevinniu666** [comment]
日志文件内容:
[root@localhost source_logs]# pwd
/data/source_logs
[root@localhost source_logs]# cat 2.log
{
    "a": 5,
    "b": {
        "c": 6,
        "my_field": "description"
    },
    "my_tag_1": "foo",
    "name": "my_json"
}

**Comment by guanshengliang** [comment]
TDengine与Telegraf接口，其原理是解析来自telegraf的json请求内容。每个json请求的格式类似
```
        {     
            "fields": {
                "field_1": 30,
                "field_2": 4,
                "field_N": 59,
                "n_images": 660
            },
            "name": "docker",
            "tags": {
                "host": "raynor"
            },
            "timestamp": 1458229140
        }
```
因此，您给出的这种文件格式，接口解析不了，所以无法入库。
这种情况，您需要编写程序，拼接语句以便入库

**Comment by kevinniu666** [comment]
现在反应出来的现象是，数字类型的可以入库，但是字符类型的不能入库。你的意思是telegraf发送到TDEngine的json格式不对？但是为什么一部分能入库呢？

**Comment by guanshengliang** [comment]
因为恰好有一部分能解析，具体可以参看tgHandle.c

**Comment by kevinniu666** [comment]
那只有等TDEngine再强大一点了，加油。等你好了，就迁移

**Comment by kevinniu666** [comment]
希望TDEngine可以出收录日志的解决方案，谢谢。
