### ISSUE TITLE
Assertion `size <= 4096' failed.

### ISSUE THREAD

**Issue by changfeng823** [taosdata/TDengine#3470]
按创建时间倒序查，报错如图。
![微信图片_20200910152627](https://user-images.githubusercontent.com/24929737/92694665-f8dc4900-f379-11ea-82ff-33bc80d628cd.png)

**Comment by hjxilinx** [comment]
麻烦提供运行的TDengine版本号。

**Comment by changfeng823** [comment]
> 麻烦提供运行的TDengine版本号。

我们用的版本是tdengine:2.0.1.1

**Comment by hjxilinx** [comment]
您好，这个是一个查询的 bug，使用全局排序查询的时候会触发。我们会尽快修复。

**Comment by changfeng823** [comment]
> 您好，这个是一个查询的 bug，使用全局排序查询的时候会触发。我们会尽快修复。

我看了一下我们有个字段一开始长度设了5000，报了这个错改成了4096，就是图上的大小，还是报，然后又改小，改成4000，就好了。

**Comment by hjxilinx** [comment]
恩，是的。排序有个4096的限制，我已经修复了这个问题，去掉了这个限制。在下个版本中会整合进来。
