### ISSUE TITLE
show database by win 7 client，DB error: Unable to establish connection

### ISSUE THREAD

**Issue by whwqs** [taosdata/TDengine#3471]
win7上运行 taos -h redis.sp.loc
正常进入taos>界面
运行use test;
正常返回
运行show databases;
返回报错：DB error: Unable to establish connection

**Comment by Aries-Lee1991** [comment]
看一下：https://www.taosdata.com/cn/documentation/faq/
第五条，是否能解决你的问题？

**Comment by whwqs** [comment]
use test;这个命令与show databases;不是同一个机制吗？

**Comment by sangshuduo** [comment]
一直都是可以 use test; 不能 show databases; 吗？请参考一下这篇博客检查一下 https://www.taosdata.com/blog/2020/09/08/1816.html

**Comment by whwqs** [comment]
create database 、create table都可以，insert 、show系列都不行。从代码看：
 pConn = rpcGetConnFromCache(pRpc->pCache, pEpSet->fqdn[pEpSet->inUse], pEpSet->port[pEpSet->inUse], pContext->connType);
  if ( pConn == NULL || pConn->user[0] == 0) {
    **pConn = rpcOpenConn(pRpc, pEpSet->fqdn[pEpSet->inUse], pEpSet->port[pEpSet->inUse], pContext->connType);**
  } 
返回有问题时会进入黑体代码，没问题的都不会进黑体代码，百试不爽

**Comment by whwqs** [comment]
rpcmain.c 766行

**Comment by whwqs** [comment]
connType 为RPC_CONN_TCPC的感觉缓存不了

**Comment by whwqs** [comment]
文档里的命令在linux服务器上运行，报错：
[root@redis ~]# taos -n client -h 127.0.0.1 -P 6030 -e 6042 -l 16000
taos: invalid option -- 'n'
Try `taos --help' or `taos --usage' for more information.

**Comment by sangshuduo** [comment]
@whwqs taos -n client -h 127.0.0.1 -P 6030 -e 6042 -l 16000 这个命令在 2.0.3.0 才有，或者你更新到最新版本试试？

**Comment by whwqs** [comment]
我用源代码方式，获取develop分支最新可以吗

**Comment by yihaoDeng** [comment]
应该是TCP连接建立不了， UDP可以， 至于为什么insert插入不行， 应该是insert的时候需要获取meta 信息， 获取meta 用的是TCP,  你可以检查下你的防火墙是不是开着， 如果还不能解决， 麻烦附下日志

**Comment by whwqs** [comment]
好

**Comment by whwqs** [comment]
拉取最新代码，taos 2.0.3.0，一切正常，原来版本是2.0.0.6
