### ISSUE TITLE
taosd core when query with group by

### ISSUE THREAD

**Issue by hedefei** [taosdata/TDengine#3476]
**Bug Description**
taosd core when query with “group by”

**To Reproduce**
1. Go to taos shell
2. Type in 'select pagenum,count(pagenum) from access192020 where logtime >1598880281005 group by pagenum;'
   pagenum column def：pagenum BINARY(64)；
 “ access192020 where logtime >1598880281005” has about 50 thousand records：
taos> select count(pagenum) from access192020 where logtime >1598880281005;
    count(pagenum)     |
========================
                 53969 |
Query OK, 1 row(s) in set (0.004001s)

3. See error
taosd: /usr/local/tsdb/TDengine-ver-2.0.3.0/src/query/src/qUtil.c:157: clearFirstNTimeWindow: Assertion `p != ((void *)0)' failed.
Aborted (core dumped)

**Expected Behavior**
correct result

**Screenshots**
none

**Environment (please complete the following information):**
 - OS:  CentOS 7.2
 - Memory, CPU, current Disk Space： enough
 - TDengine Version [2.0.3.0]

**Additional Context**
none

**Comment by yihaoDeng** [comment]
@hedefei  it is a bug, we will fix it later

**Comment by hedefei** [comment]
@yihaoDeng what's the condition and data status that cause this issue to happen？
i‘am thinking about how to avoid the bug before you fix it...

**Comment by hjxilinx** [comment]
In order to avoid this bug, please do not group by [binary|nchar] type column.
We will fix this bug in the next released version.

**Comment by songtianyi** [comment]
solved? @hjxilinx 
```
taos> DESCRIBE gate_99;
             Field              |        Type        |   Length    |    Note    |
=================================================================================
 ts                             | TIMESTAMP          |           8 |            |
 flow_no                        | NCHAR              |          20 |            |
 channel                        | NCHAR              |          15 |            |
 trade                          | NCHAR              |           7 |            |
 cnt                            | FLOAT              |           4 |            |
 client_id                      | INT                |           4 |            |
 branch                         | NCHAR              |          15 |            |
 create_at                      | BIGINT             |           8 |            |
 src                            | NCHAR              |          39 |            |
 dst                            | NCHAR              |          39 |            |
 code                           | INT                |           4 |            |
 msg                            | NCHAR              |         125 |            |
 ts_in                          | BIGINT             |           8 |            |
 ts_out                         | BIGINT             |           8 |            |
 lapse                          | INT                |           4 |            |
Query OK, 15 row(s) in set (0.000456s)

taos> select * from gate_99 group by client_id;

DB error: invalid SQL: projection query on columns not allowed
taos>
```

**Comment by hjxilinx** [comment]
客户端解析 SQL 的时候关闭的 nchar 的功能。后面我已经打开这个过滤，下周发布的新版本应该可以使用。
