### ISSUE TITLE
About Windows server

### ISSUE THREAD

**Issue by zhuqiyun** [taosdata/TDengine#3478]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the circumstance is and what the associated problem is. Ex. I'm using TDengine for this use case: [...]. But I'm always frustrated when [...]

**Describe your desired behavior**
A clear and concise description of what you want to happen. Ex. I want TDengine to be able to do [...] when I try to do [...] with it.

**Describe your solutions/suggestions if you've any**
A clear and concise description of any solutions/suggestions to this problem or features you've considered.

**Additional context**

**Comment by sangshuduo** [comment]
是指服务器端的 Windows 版本？

**Comment by zhuqiyun** [comment]
> 是指服务器端的 Windows 版本？

是的

**Comment by sangshuduo** [comment]
暂时还没有具体时间表
