### ISSUE TITLE
采集侧支持kafka问题，文档里有说明么？还是通过restful方式？

### ISSUE THREAD

**Issue by kidari** [taosdata/TDengine#348]
> 目前TDengine在数据采集侧，已经支持Telegraf, Kafka，后续还将支持MQTT,OPC等。

**Comment by guanshengliang** [comment]
kafka的订阅接收的数据不是自描述的，而TDengine的数据模型是严格结构化的
因此如果使用kfaka，收到数据后要包装成SQL语句，然后通过jdbc或者restful存到TDengine中
不能通过简单的配置直接接收kfaka数据

**Comment by kidari** [comment]
那修改下blog吧，容易产生歧义
