### ISSUE TITLE
Query use "min" in sql  crashed!

### ISSUE THREAD

**Issue by Edassap** [taosdata/TDengine#3481]
all based in 2.0.3.0;
here are informations:
sql: select instrument_id, last_price, min(bid_price1) from test1;
And this table is very large, about more than 600w records;
![image](https://user-images.githubusercontent.com/16076576/92834604-caf41480-f40c-11ea-8ef7-8cb7ebac0c53.png)

**Comment by sangshuduo** [comment]
We will try to reproduce it.

**Comment by hjxilinx** [comment]
min/max/top/bottom/first/last 这种选择型函数不支持与普通列混合进行查询(可以与 timestamp、tag 标签进行混合查询)，解析器遇到这种情况的没有正确报错。我们已经修复了这个问题，并整合到下一个发布版本中。
谢谢！
