### ISSUE TITLE
taosdemo pthread_join is blocked

### ISSUE THREAD

**Issue by whwqs** [taosdata/TDengine#3483]
1、代码调试方式运行 taosdemo -h redis.sp.loc  -t 2 -n 10
2、代码在taosdemo.c 1054行（下面黑体）走第二次后阻塞不往下走：
  pthread_create(pids + i, NULL, createTable, t_info);
  }
  
  for (int i = 0; i < threads; i++) {
    **pthread_join(pids[i], NULL);**
  }

  double t = getCurrentTime() - ts;
  printf("Spent %.4f seconds to create %d tables with %d connections\n", t, ntables, threads);
3、表正常创建，数据不会插入，界面显示：
Press enter key to continue
Creating meters super table...
meters created!
create table......
Creating table from 0 to 0
Creating table from 1 to 1
4、代码是今天最新

**Comment by whwqs** [comment]
只一个表时，建表插入没问题：如taosdemo -t 1 -n 10000 
超过一个表时，比如：taosdemo -t 3 -n 100 ，会提示建表信息后阻塞住，ctrl+c 退出
在shell中 show tables可以看到 t0 t1 t2，
select * from t0; 正常返回，但记录为空： Query OK, 0 row(s) in set (0.002263s)
select * from t1; 
select * from t2;
均错误返回：DB error: Invalid table ID
我感觉是multiThreadCreateTable方法中线程多线程建表导致的，因此修改代码如下：
last = t_info->end_table_id + 1;
    t_info->use_metric = use_metric;
    t_info->cols = cols;
    pthread_create(pids + i, NULL, createTable, t_info);
    **printf("create table %d ing,press any continue...", i);
    (void)getchar();**
  }
  
  for (int i = 0; i < threads; i++) {
    **//pthread_join(pids[i], NULL);屏蔽**
  }
在win7下用vs2019，加参数 -h redis.sp.loc -t 3 -n 10000,运行taosdemo项目，
结果：正常建表和插入了数据
从DB error: Invalid table ID看是否是线程的数据上下文串了，我接下来尝试看一下

**Comment by plum-lihui** [comment]
是在windows下出现的问题？在linux上有测试，也出现同样的问题么？

**Comment by whwqs** [comment]
一样的

**Comment by whwqs** [comment]
linux 服务端直接运行 taosdemo -t 3 -n 100 ，也会卡在建完表的提示，而实际只有t0表建好了，但没有数据，select * from t1 提示DB error: Invalid table ID，我上面怀疑是上下文串了，应该不是，刚才调了。

**Comment by whwqs** [comment]
应该是线程阻塞方式，刚才把代码改成下面，是可以的：
    last = t_info->end_table_id + 1;
    t_info->use_metric = use_metric;
    t_info->cols = cols;
    pthread_create(pids + i, NULL, createTable, t_info);
    **pthread_join(pids[i], NULL);**
  }
  
  for (int i = 0; i < threads; i++) {
    **//pthread_join(pids[i], NULL);**
  }
但这就不是多线程了

**Comment by whwqs** [comment]
在代码中加休眠好像可以解决问题，循环中每启动一个创建多表的线程就休眠一下。
感觉bug的根本原因应该还是服务端接收到连续间隔很短的创建表的命令，处理有问题。
为什么这样说？
比如：taosdemo -t 3 -n 10 
ctrl+c 退出阻塞，taos进入shell
use test 
show tables 可以看见 t0 t1 t2
但select * from t0 正常，但没有记录（本应该有10条记录才对）
select * from t1 与 select * from t2 均报DB error: Invalid table ID，
以上说明服务端收到了创建表的命令，虽然创建了表，但只有第一个表是正常创建，因为创建后面的表出错，导致客户端代码阻塞在建表线程等待处，不能进入后面插入记录代码。
进测试，下面的修改的代码可以正常工作：（位于taosdemo.c 1050）
pthread_create(pids + i, NULL, createTable, t_info);
    **//休眠
    struct timespec tsWait;
    tsWait.tv_sec = 0;
    tsWait.tv_nsec = 500 * 1000000L;//500毫秒，这个地方也许与服务端的性能有关，性能差的可能要设大一点
    pthread_delay_np(&tsWait);**
  }
  
  for (int i = 0; i < threads; i++) {
    pthread_join(pids[i], NULL);
  }

**Comment by plum-lihui** [comment]
多谢！我们按照你的操作也会验证仔细验证一下。

**Comment by plum-lihui** [comment]
1、=================   执行 taosdemo =======================
ubuntu@ubuntu-7060 ~/TDengine/debug (develop)$ ./build/bin/taosdemo -t 3 -n 100
###################################################################
# Server IP:                         localhost:0
# User:                              root
# Password:                          taosdata
# Use metric:                        true
# Datatype of Columns:               int int int int int int int float
# Binary Length(If applicable):      -1
# Number of Columns per record:      3
# Number of Threads:                 10
# Number of Tables:                  3
# Number of Data per Table:          100
# Records/Request:                   1000
# Database name:                     test
# Table prefix:                      t
# Delete method:                     0
# Test time:                         2020-09-14 09:42:45
###################################################################

Press enter key to continue

failed to open log file:/var/log/taos/taoslog0.0, reason:Permission denied
failed to open log file in directory:/var/log/taos
Creating meters super table...
meters created!
create table......
Creating table from 0 to 0
Creating table from 1 to 1
Creating table from 2 to 2
Spent 0.3078 seconds to create 3 tables with 3 connections
Inserting data......
SYNC Insert with 3 connections:
Spent 0.0149 seconds to insert 300 records with 1000 record(s) per request: 20103.39 records/second
ubuntu@ubuntu-7060 ~/TDengine/debug (develop)$


2、===================taos 登录，查看结果=========================
taos> use test;
Database changed.

taos> show stables;
              name              |      created_time       | columns |  tags  |   tables    |
============================================================================================
 meters                         | 2020-09-14 09:42:46.813 |       4 |      2 |           3 |
Query OK, 1 row(s) in set (0.001661s)

taos> select count(*) from meters;
       count(*)        |
========================
                   300 |
Query OK, 1 row(s) in set (0.004089s)

taos> show tables;
           table_name           |      created_time       | columns |          stable_name           |
======================================================================================================
 t1                             | 2020-09-14 09:42:46.819 |       4 | meters                         |
 t2                             | 2020-09-14 09:42:46.819 |       4 | meters                         |
 t0                             | 2020-09-14 09:42:46.823 |       4 | meters                         |
Query OK, 3 row(s) in set (0.002437s)

taos> select count(*) from t0;
       count(*)        |
========================
                   100 |
Query OK, 1 row(s) in set (0.002413s)

taos> select count(*) from t1;
       count(*)        |
========================
                   100 |
Query OK, 1 row(s) in set (0.002407s)

taos> select count(*) from t2;
       count(*)        |
========================
                   100 |
Query OK, 1 row(s) in set (0.002295s)

taos>

**Comment by plum-lihui** [comment]
这是我在linux上做的测试，按照你的参数，没有问题。 
如果你的环境能够复现，请能让我远程看一下。微信：13611161621。
多谢！

**Comment by whwqs** [comment]
刚才在linux上，taosdemo -t 10000 -n 1000
是正常的，不能复现，
在win7上，taosdemo -h reids.sp.loc -t 100 -n 100 也正常了
win7上，把参数调大有问题，我再多试几下

**Comment by whwqs** [comment]
我们这里每天会关服务器，第二天重开，不知是不是与当时的情况有关，重启后好了，我稍后再试linux的情况

**Comment by plum-lihui** [comment]
目前看是windows上执行taosdemo，设置多线程、大量表的情况下，不是很稳定。这个我们会再跟踪一下。
