### ISSUE TITLE
After many queries, the memory consumption of taos remains high

### ISSUE THREAD

**Issue by lxp119** [taosdata/TDengine#3484]
查询 超级表五万个子表的最后一条记录，查询一下内存就增大，并且没有查询的时候 TAOS 所占的内存居高不下，下面是sql语句和截图；
虚拟机配置图：
![image](https://user-images.githubusercontent.com/69295314/92878919-20e1b000-f43f-11ea-89ba-a8c35ad54eec.png)
虚拟机系统使用deepin20
查询sql图  内存统计图：
![微信图片_20200911145952](https://user-images.githubusercontent.com/69295314/92879282-7d44cf80-f43f-11ea-856a-a2978d051605.png)
![微信图片_20200911145943](https://user-images.githubusercontent.com/69295314/92879291-7f0e9300-f43f-11ea-86d3-33b8e8b18120.png)

日志包：
[taos.zip](https://github.com/taosdata/TDengine/files/5207213/taos.zip)

**Comment by hjxilinx** [comment]
请问您的客户端运行在 Linux 上还是 Windows 上？

**Comment by lxp119** [comment]
虚拟机：系统deepin20  客户端和服务器在一块。
是的 taosd 内存下不去。

**Comment by hjxilinx** [comment]
这个问题我们注意到了，不是内存泄露的问题。是由于 glibc 没有将 free 掉的内存还给 os，导致看到的taosd内存占用越来越大。 我们后面会处理这个问题。
