### ISSUE TITLE
no JDBC Driver in package

### ISSUE THREAD

**Issue by lzuan** [taosdata/TDengine#35]
When I'd like to configure Matlab connetcor (https://www.taosdata.com/en/documentation/connections-with-other-tools/#Matlab)
JDBCDriver-1.0.0-dist.jar is not found in TDengine package.Please check.

**Comment by ttii** [comment]
toby@ubuntu:~/work/TDengine:master$ cd build/
toby@ubuntu:~/work/TDengine/build:master$ cmake .. && cmake --build .
-- Project source directory: /home/toby/work/TDengine
-- Build Debug Version
-- Project binary output path: /home/toby/work/TDengine/build
-- Executable files output path: /home/toby/work/TDengine/build/build/bin
-- Project library output path: /home/toby/work/TDengine/build/build/lib
-- Check targe platform x64, pass
-- Use the iconv functions in GLIBC
-- build version 
CMake Error at src/client/CMakeLists.txt:30 (SET_TARGET_PROPERTIES):
  set_target_properties called with incorrect number of arguments.


-- MVN is not installed and JDBC is not compiled
-- Configuring incomplete, errors occurred!
See also "/home/toby/work/TDengine/build/CMakeFiles/CMakeOutput.log".

**Comment by hzcheng** [comment]
@lzuan Which package did you use, RPM, DEB, or Tarball? 
Besides, if you are using Matlab on Windows, the JDBC relies on TDengine .dll library, which is a milestone next week.

**Comment by hzcheng** [comment]
@ttii Maven is required to compile the JDBC package. On centos, use `yum install maven`. On Ubuntu, use `apt install mvn`.

**Comment by lzuan** [comment]
@hzcheng  Firstly I install TDengine from the source code(Maven is not insalled), so JDBC Driver is absent. Then DEB package is used on Ubuntu 16.04, and taos-jdbcdriver-1.0.0-dist.jar is in /usr/local/taos/connector/.
I am using Matlab on Ubuntu 16.04, however the connect instruction is about windows. Could you release  the configuration  of Matlab connetcor on Ubuntu?

**Comment by johnnyhou327** [comment]
Hi @lzuan , connecting TDengine in Matlab on a Ubuntu OS will rely on either JDBC driver or the ODBC driver. We currently haven't yet tried configuring Matlab connectivity on any Linux OS due the extremely busy schedule, but we strongly encourage developers to try to do some research on the driver installation and configuration steps. The DLL for Windows OS is expected to be released before Aug. You may wait for that DLL and then try Matlab connections from a Windows OS.
