### ISSUE TITLE
After the deployment of the Ubuntu, taos connet failed.The taosd has been started and the firewall has been closed.

### ISSUE THREAD

**Issue by CxMachine** [taosdata/TDengine#3500]
【安装环境】
TDengine版本：TDengine-server-2.0.2.1-Linux-x64.tar.gz
Ubuntu版本：Ubuntu 12.04 LTS
Linux内核版本：Linux ubuntu 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
【出错信息】
root@ubuntu:/usr/local/src# taos
Welcome to the TDengine shell from Linux, Client Version:2.0.2.1
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.
taos connect failed, reason: Unable to establish connection.

**Comment by Aries-Lee1991** [comment]
参考一下：https://www.taosdata.com/cn/documentation/faq/
第5条，看是否能解决

**Comment by sangshuduo** [comment]
TDengine 默认使用 systemd 管理 taosd 服务。12.04 太老了，用的不是 systemd 。

**Comment by CxMachine** [comment]
> 参考一下：https://www.taosdata.com/cn/documentation/faq/
> 第5条，看是否能解决
不能解决，QFN是正确的
输入taos命令后，/var/log/taos/taoslog0.0 打印的错误信息如下：
09/14 05:42:53.486289 0x7f9dfab77700 RPC ERROR TSC 0x7f9df5fb7188 0x13cc0d0, failed to send, msgLen:345 written:-1, reason:Invalid argument

**Comment by CxMachine** [comment]
> TDengine 默认使用 systemd 管理 taosd 服务。12.04 太老了，用的不是 systemd 。

是的，用的service命令管理的

**Comment by CxMachine** [comment]
> > 参考一下：https://www.taosdata.com/cn/documentation/faq/
> > 第5条，看是否能解决
> > 不能解决，QFN是正确的
> > 输入taos命令后，/var/log/taos/taoslog0.0 打印的错误信息如下：
> > 09/14 05:42:53.486289 0x7f9dfab77700 RPC ERROR TSC 0x7f9df5fb7188 0x13cc0d0, failed to send, msgLen:345 written:-1, reason:Invalid argument

查看/var/var/log/taos/taosdlog.1日志，发现不断在输出以下信息：
09/14 05:49:40.835916 0x7f3c5bfff700 RPC WARN DND-C 0x7f3c63fdd478 (nil), too many redirects, quit
09/14 05:49:40.835928 0x7f3c5bfff700 DND mnode EP list for peer is changed, numOfEps:2 inUse:1
09/14 05:49:40.835934 0x7f3c5bfff700 DND mnode index:0 6030:6030
09/14 05:49:40.835939 0x7f3c5bfff700 DND mnode index:1 ubuntu:6030
09/14 05:49:40.835945 0x7f3c5bfff700 DND ERROR status rsp is received, error:Redirect
09/14 05:49:41.841838 0x7f3c57ff7700 DND msg:status will be processed in mpeer queue
09/14 05:49:41.841884 0x7f3c57ff7700 MND (nil), msg:status in mpeer queue, will be redireced, numOfEps:0 inUse:0
09/14 05:49:41.842453 0x7f3c57ff7700 DND msg:status will be processed in mpeer queue
09/14 05:49:41.842551 0x7f3c57ff7700 MND (nil), msg:status in mpeer queue, will be redireced, numOfEps:0 inUse:0
09/14 05:49:41.843962 0x7f3c57ff7700 DND msg:status will be processed in mpeer queue
09/14 05:49:41.844015 0x7f3c57ff7700 MND (nil), msg:status in mpeer queue, will be redireced, numOfEps:0 inUse:0
09/14 05:49:41.845859 0x7f3c57ff7700 DND msg:status will be processed in mpeer queue
09/14 05:49:41.845907 0x7f3c57ff7700 MND (nil), msg:status in mpeer queue, will be redireced, numOfEps:0 inUse:0
09/14 05:49:41.845949 0x7f3c57ff7700 DND msg:status will be processed in mpeer queue
09/14 05:49:41.845951 0x7f3c57ff7700 MND (nil), msg:status in mpeer queue, will be redireced, numOfEps:0 inUse:0
09/14 05:49:41.845970 0x7f3c57ff7700 DND msg:status will be processed in mpeer queue
09/14 05:49:41.845971 0x7f3c57ff7700 MND (nil), msg:status in mpeer queue, will be redireced, numOfEps:0 inUse:0

**Comment by sangshuduo** [comment]
https://www.taosdata.com/cn/getting-started/#%E5%BF%AB%E6%8D%B7%E5%AE%89%E8%A3%85

> 目前，TDengine只支持在使用[`systemd`](https://en.wikipedia.org/wiki/Systemd)做进程服务管理的linux系统上安装。

12.04 太老了，请使用 18.04 或者 20.04
