### ISSUE TITLE
Do you support developing plug-ins on TD Engine to enhance its functions?

### ISSUE THREAD

**Issue by charleswu52** [taosdata/TDengine#3502]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the circumstance is and what the associated problem is. Ex. I'm using TDengine for this use case: [...]. But I'm always frustrated when [...]

**Describe your desired behavior**
A clear and concise description of what you want to happen. Ex. I want TDengine to be able to do [...] when I try to do [...] with it.

**Describe your solutions/suggestions if you've any**
A clear and concise description of any solutions/suggestions to this problem or features you've considered.

**Additional context**

**Comment by sangshuduo** [comment]
Not yet. Any suggestion?

**Comment by charleswu52** [comment]
I want to try to use external machine learning plug-ins to provide optimization services for the database. Therefore, it is not known whether the database supports plug-ins before this.

**Comment by sangshuduo** [comment]
Really sorry about this. The core part of the TDengine is programmed by C language. And we and few talented guys from the community developed a series of connectors for using different languages to access the database. Not sure what layer data structure or information your ML algorithm needs to consume. However, we do encourage anyone to extend the functions for the TDengine. Please let us know what we can help with. Thanks.
