### ISSUE TITLE
unreadable code with NCHAR type 

### ISSUE THREAD

**Issue by sytpb** [taosdata/TDengine#3504]
TD Ver  2.0.3   

Table structure:
![微信图片_20200914082032](https://user-images.githubusercontent.com/12178686/93032243-0f78ed80-f663-11ea-98ca-0c34cb08dff3.png)

INSERT sql : 
`INSERT INTO sun.orders_corpid USING sun.orders TAGS ('corpid') VALUES (now,${this.orderID},'userid','${body.name}','cargo_id',1,'d_company','d_contact','d_tel','custid','1',120);`

CASE 1:
SELECT sql in shell, it is normal . 
![微信图片_20200914082501](https://user-images.githubusercontent.com/12178686/93032357-caa18680-f663-11ea-8b51-7e6208845197.png)

CASE 2:
conector nodejs 

result output with Pretty() and Query() , unreadable code happen, 

![微信图片_20200914082942](https://user-images.githubusercontent.com/12178686/93032554-dc375e00-f664-11ea-8668-2f8cd190e05c.png)

![微信图片_20200914082949](https://user-images.githubusercontent.com/12178686/93032553-d80b4080-f664-11ea-8f75-7b845006fc98.png)

**Comment by sangshuduo** [comment]
怀疑是编码问题，TDengine NCHAR 用的 Unicode

**Comment by sytpb** [comment]
问下，有解决办法了吗？

**Comment by sangshuduo** [comment]
@sytpb 你的代码里有没有设置使用 Unicode ？

**Comment by sytpb** [comment]
哦，需要我设置成unicode 啊，我以为是connector 代码的问题，那我试一下。

**Comment by sytpb** [comment]
nodesj 怎么设置？ 没有查到设unicode 方法。 。。。

**Comment by sangshuduo** [comment]
就是和 javascript 设置一样吧

**Comment by sytpb** [comment]
2.0.3 现在2.0.10 问题同样存在， 查了一下文档，js 默认是支持utf8 unicode 的，不需要设置，建议官方验证一下。

**Comment by sangshuduo** [comment]
现在还有这个问题吗？

**Comment by sangshuduo** [comment]
close as no response for a long time. please reopen it if you have the same issue.
