### ISSUE TITLE
the keyword 'fill'  can only used in  select function_list？

### ISSUE THREAD

**Issue by nari-dongx** [taosdata/TDengine#3514]
fill插值只能用在SELECT function_list？
比如想查一张表每隔10分钟一次的值，考虑插值，该如何实现？

**Comment by hjxilinx** [comment]
select count(*) from table_name interval(10m) fill(prev);
统计每10分钟的数值总数，如果没有，使用前一个10分钟窗口 的结果填充。

**Comment by nari-dongx** [comment]
比如，一个测点最近1分钟有60个值，我想查询每隔10秒的值，返回6个值，这样子的效果

**Comment by nari-dongx** [comment]
比如，一个测点最近1分钟有60个值，我想查询每隔10秒的值，如果某个时间点没有值，则向前直到有值的点，共返回6个值，这样子的填充效果

**Comment by hjxilinx** [comment]
The newly release version support inerpolation query.
This issue was closed because it has been inactive for too many days.
