### ISSUE TITLE
Assertion `pFillInfo->start == ts' failed

### ISSUE THREAD

**Issue by tony358** [taosdata/TDengine#3517]
OS: CentOS7     tdengine ver:  docker 2.0.1.1 or  2.0.3.1 

The table structure information is as follows:
![image](https://user-images.githubusercontent.com/26424684/93064092-b7b1a500-f6a9-11ea-9432-5306d1102524.png)

An error occurred while executing the following SQL query:
 select sum(video_lose) from asset_camera_diagnosis interval(10m) fill(prev);
![image](https://user-images.githubusercontent.com/26424684/93064594-47efea00-f6aa-11ea-8eb2-fa2426d26c99.png)

**Comment by xiaopingcs** [comment]
这是一个有效的bug，我们这边可以重现，谢谢。我们会在之后的版本修复

**Comment by xiaopingcs** [comment]
this issue has been fixed
