### ISSUE TITLE
client hang when insert data

### ISSUE THREAD

**Issue by huangbotao** [taosdata/TDengine#3524]
**Bug Description**
在TDengine集群中某一个节点上用，client写入数据时，client卡住不返回。

**To Reproduce**
1. 在插入前提交曾提交过一次超级表的ddl操作，增加了一个字段。
ALTER TABLE xxx ADD COLUMN 'tb_xxx' double;

2. 然后执行数据插入操作
insert into PARxxxP02 (ts, 'tb_Cxxxxtus') values(1600138440760, 1.0)

**Screenshots**
![image](https://user-images.githubusercontent.com/36856212/93161754-cfd70200-f745-11ea-98ff-7f1897282823.png)
![image](https://user-images.githubusercontent.com/36856212/93161761-d36a8900-f745-11ea-854f-eb8d2d78989e.png)

**Environment (please complete the following information):**
 - OS:  CentOS 7.2
 - 4C 16G
 - TDengine Version 2.0.1.0

**Comment by localvar** [comment]
您可以提供下完整的表结构吗？

**Comment by huangbotao** [comment]
> 您可以提供下完整的表结构和相关日志吗？

可以，我发你邮箱吧，麻烦给我打个招呼  huangbotao@enn.cn

**Comment by huangbotao** [comment]
> 您可以提供下完整的表结构和相关日志吗？

表结构信息：
[tableSchema.log](https://github.com/taosdata/TDengine/files/5223184/tableSchema.log)
日志信息，就是上面的图片内容，没有更多的日志了。

**Comment by localvar** [comment]
由于字段太多，为避免一些不必要的录入错误，请您将一些示例语句发到我的邮箱：bmzhang@taosdata.com
包括：
* 创建数据库、超级表、子表的语句
* 修改超级表的 ddl 语句
* 出问题的 insert 语句

谢谢

**Comment by localvar** [comment]
另外，您也可以修改 /etc/taos/taos.cfg 增加 `debugflag 135` 打开全部日志，重现错误，然后看日志中是否有有价值的内容。

**Comment by huangbotao** [comment]
> 另外，您也可以修改 /etc/taos/taos.cfg 增加 `debugflag 135` 打开全部日志，重现错误，然后看日志中是否有有价值的内容。

请查收下邮件。
