### ISSUE TITLE
windows client cannot connect to Linux server of a different time zone

### ISSUE THREAD

**Issue by nari-dongx** [taosdata/TDengine#3530]
linux服务器采用GMT0时区，windows客户机采用CST+8，两边显示的时间是一样的。
现在taosd.conf这个文件timezone怎么改，客户端都无法登录
![image](https://user-images.githubusercontent.com/54769021/93182987-ffe5cb80-f76c-11ea-8a94-7326d24fdcd3.png)

**Comment by plum-lihui** [comment]
GMT0与 CST+8 不是一个时区，从截图中也能看出来，正好相差8个小时。
所以，需要将客户端和服务端设置成同一个时区。
你可以在客户端和服务端的taos.cfg 配置文件中，都设置一下：
timezone              Asia/Shanghai (CST, +0800)
然后再试试。

**Comment by nari-dongx** [comment]
> GMT0与 CST+8 不是一个时区，从截图中也能看出来，正好相差8个小时。
> 所以，需要将客户端和服务端设置成同一个时区。
> 你可以在客户端和服务端的taos.cfg 配置文件中，都设置一下：
> timezone Asia/Shanghai (CST, +0800)
> 然后再试试。

那如果业务确实不在同一个时区，可以通过配置文件配吗

**Comment by plum-lihui** [comment]
上面的回答应该有点误解，服务器上对于业务的时戳是没有时区概念的，是客户端上才有时区，但两者之间的时间需要校准一致，比如同步相同的NTP服务器。
