### ISSUE TITLE
超级表STable的删除有方便的办法吗？

### ISSUE THREAD

**Issue by txeagle** [taosdata/TDengine#354]
必须先将通过STable创建的表先删除，然后才能删除超级表。当级联表很多时就麻烦了，除非写代码来删除。

**Comment by guanshengliang** [comment]
这个功能很必要，会安排到研发计划，提供SQL语句实现此功能

**Comment by guanshengliang** [comment]
Version 1.6.4.4 already supports this operation, you can download and try
The syntax for deleting super tables and deleting ordinary tables is the same
