### ISSUE TITLE
failed to create more than 1454 sub-tables at one time based on the super table, and have no error occurred.

### ISSUE THREAD

**Issue by zzandyc** [taosdata/TDengine#3540]
==================================================
                new log file                      
==================================================
09/16 12:32:40.760848 0x7f2dc4020b80 UTL localEp is: ubuntu:6030
09/16 12:32:40.761234 0x7f2dc4020b80 UTL ERROR locale not configured, set to system default:en_US.UTF-8
09/16 12:32:40.761268 0x7f2dc4020b80 UTL WARN charset not configured, set to system default:UTF-8
09/16 12:32:40.761306 0x7f2dc4020b80 UTL timezone is set to Asia/Shanghai by config file
09/16 12:32:40.761322 0x7f2dc4020b80 UTL timezone format changed to (CST, +0800)
09/16 12:32:40.761329 0x7f2dc4020b80 UTL    taos config & system info:
09/16 12:32:40.761331 0x7f2dc4020b80 UTL ==================================
09/16 12:32:40.761334 0x7f2dc4020b80 UTL  firstEp:                ubuntu:6030 
09/16 12:32:40.761336 0x7f2dc4020b80 UTL  secondEp:               ubuntu:6030 
09/16 12:32:40.761338 0x7f2dc4020b80 UTL  fqdn:                   ubuntu 
09/16 12:32:40.761340 0x7f2dc4020b80 UTL  serverPort:             6030 
09/16 12:32:40.761342 0x7f2dc4020b80 UTL  configDir:              /etc/taos 
09/16 12:32:40.761344 0x7f2dc4020b80 UTL  logDir:                 /var/log/taos 
09/16 12:32:40.761346 0x7f2dc4020b80 UTL  scriptDir:              /etc/taos 
09/16 12:32:40.761347 0x7f2dc4020b80 UTL  arbitrator:              
09/16 12:32:40.761349 0x7f2dc4020b80 UTL  numOfThreadsPerCore:    1.000000 
09/16 12:32:40.761354 0x7f2dc4020b80 UTL  rpcTimer:               1000(ms)
09/16 12:32:40.761355 0x7f2dc4020b80 UTL  rpcMaxTime:             600(s)
09/16 12:32:40.761356 0x7f2dc4020b80 UTL  shellActivityTimer:     3(s)
09/16 12:32:40.761357 0x7f2dc4020b80 UTL  tableMetaKeepTimer:     7200(s)
09/16 12:32:40.761359 0x7f2dc4020b80 UTL  compressMsgSize:        -1 
09/16 12:32:40.761361 0x7f2dc4020b80 UTL  maxSQLLength:           100000(byte)
09/16 12:32:40.761362 0x7f2dc4020b80 UTL  maxNumOfOrderedRes:     100000 
09/16 12:32:40.761363 0x7f2dc4020b80 UTL  timezone:               (CST, +0800) 
09/16 12:32:40.761365 0x7f2dc4020b80 UTL  locale:                 en_US.UTF-8 
09/16 12:32:40.761366 0x7f2dc4020b80 UTL  charset:                UTF-8 
09/16 12:32:40.761368 0x7f2dc4020b80 UTL  numOfLogLines:          10000000 
09/16 12:32:40.761369 0x7f2dc4020b80 UTL  logKeepDays:            0 
09/16 12:32:40.761370 0x7f2dc4020b80 UTL  asyncLog:               1 
09/16 12:32:40.761372 0x7f2dc4020b80 UTL  debugFlag:              0 
09/16 12:32:40.761373 0x7f2dc4020b80 UTL  rpcDebugFlag:           131 
09/16 12:32:40.761375 0x7f2dc4020b80 UTL  tmrDebugFlag:           131 
09/16 12:32:40.761376 0x7f2dc4020b80 UTL  cDebugFlag:             131 
09/16 12:32:40.761378 0x7f2dc4020b80 UTL  jniDebugFlag:           131 
09/16 12:32:40.761380 0x7f2dc4020b80 UTL  odbcDebugFlag:          131 
09/16 12:32:40.761381 0x7f2dc4020b80 UTL  uDebugFlag:             131 
09/16 12:32:40.761383 0x7f2dc4020b80 UTL  qDebugFlag:             131 
09/16 12:32:40.761385 0x7f2dc4020b80 UTL  tsdbDebugFlag:          131 
09/16 12:32:40.761387 0x7f2dc4020b80 UTL  gitinfo:                community 
09/16 12:32:40.761388 0x7f2dc4020b80 UTL  gitinfoOfInternal:      internal 
09/16 12:32:40.761390 0x7f2dc4020b80 UTL  buildinfo:              Built at 2020-09-15 16:12:55 
09/16 12:32:40.761392 0x7f2dc4020b80 UTL  version:                2.0.3.0 
09/16 12:32:40.761393 0x7f2dc4020b80 UTL  maxBinaryDisplayWidth:  30 
09/16 12:32:40.761397 0x7f2dc4020b80 UTL  os pageSize:            4096(KB)
09/16 12:32:40.761399 0x7f2dc4020b80 UTL  os openMax:             1024
09/16 12:32:40.761400 0x7f2dc4020b80 UTL  os streamMax:           16
09/16 12:32:40.761402 0x7f2dc4020b80 UTL  os numOfCores:          4
09/16 12:32:40.761403 0x7f2dc4020b80 UTL  os totalDisk:           0.000000(GB)
09/16 12:32:40.761405 0x7f2dc4020b80 UTL  os totalMemory:         15986(MB)
09/16 12:32:40.761409 0x7f2dc4020b80 UTL  os sysname:             Linux
09/16 12:32:40.761415 0x7f2dc4020b80 UTL  os nodename:            ubuntu
09/16 12:32:40.761418 0x7f2dc4020b80 UTL  os release:             5.4.0-47-generic
09/16 12:32:40.761419 0x7f2dc4020b80 UTL  os version:             #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020
09/16 12:32:40.761420 0x7f2dc4020b80 UTL  os machine:             x86_64
09/16 12:32:40.761425 0x7f2dc4020b80 UTL ==================================
09/16 12:32:41.265687 0x7f2dc4020b80 UTL cache:tableMeta will be cleaned up
==================================================
                new log file                      
==================================================
09/16 12:33:27.400534 0x7fdce5328b80 UTL localEp is: ubuntu:6030
09/16 12:33:27.400860 0x7fdce5328b80 UTL ERROR locale not configured, set to system default:en_US.UTF-8
09/16 12:33:27.400889 0x7fdce5328b80 UTL WARN charset not configured, set to system default:UTF-8
09/16 12:33:27.400922 0x7fdce5328b80 UTL timezone is set to Asia/Shanghai by config file
09/16 12:33:27.400933 0x7fdce5328b80 UTL timezone format changed to (CST, +0800)
09/16 12:33:27.400936 0x7fdce5328b80 UTL    taos config & system info:
09/16 12:33:27.400937 0x7fdce5328b80 UTL ==================================
09/16 12:33:27.400939 0x7fdce5328b80 UTL  firstEp:                ubuntu:6030 
09/16 12:33:27.400940 0x7fdce5328b80 UTL  secondEp:               ubuntu:6030 
09/16 12:33:27.400941 0x7fdce5328b80 UTL  fqdn:                   ubuntu 
09/16 12:33:27.400943 0x7fdce5328b80 UTL  serverPort:             6030 
09/16 12:33:27.400944 0x7fdce5328b80 UTL  configDir:              /etc/taos 
09/16 12:33:27.400945 0x7fdce5328b80 UTL  logDir:                 /var/log/taos 
09/16 12:33:27.400947 0x7fdce5328b80 UTL  scriptDir:              /etc/taos 
09/16 12:33:27.400948 0x7fdce5328b80 UTL  arbitrator:              
09/16 12:33:27.400949 0x7fdce5328b80 UTL  numOfThreadsPerCore:    1.000000 
09/16 12:33:27.400960 0x7fdce5328b80 UTL  rpcTimer:               1000(ms)
09/16 12:33:27.400962 0x7fdce5328b80 UTL  rpcMaxTime:             600(s)
09/16 12:33:27.400963 0x7fdce5328b80 UTL  shellActivityTimer:     3(s)
09/16 12:33:27.400965 0x7fdce5328b80 UTL  tableMetaKeepTimer:     7200(s)
09/16 12:33:27.400966 0x7fdce5328b80 UTL  compressMsgSize:        -1 
09/16 12:33:27.400968 0x7fdce5328b80 UTL  maxSQLLength:           100000(byte)
09/16 12:33:27.400969 0x7fdce5328b80 UTL  maxNumOfOrderedRes:     100000 
09/16 12:33:27.400970 0x7fdce5328b80 UTL  timezone:               (CST, +0800) 
09/16 12:33:27.400972 0x7fdce5328b80 UTL  locale:                 en_US.UTF-8 
09/16 12:33:27.400973 0x7fdce5328b80 UTL  charset:                UTF-8 
09/16 12:33:27.400974 0x7fdce5328b80 UTL  numOfLogLines:          10000000 
09/16 12:33:27.400976 0x7fdce5328b80 UTL  logKeepDays:            0 
09/16 12:33:27.400977 0x7fdce5328b80 UTL  asyncLog:               1 
09/16 12:33:27.400978 0x7fdce5328b80 UTL  debugFlag:              0 
09/16 12:33:27.400980 0x7fdce5328b80 UTL  rpcDebugFlag:           131 
09/16 12:33:27.400981 0x7fdce5328b80 UTL  tmrDebugFlag:           131 
09/16 12:33:27.400982 0x7fdce5328b80 UTL  cDebugFlag:             131 
09/16 12:33:27.400983 0x7fdce5328b80 UTL  jniDebugFlag:           131 
09/16 12:33:27.400985 0x7fdce5328b80 UTL  odbcDebugFlag:          131 
09/16 12:33:27.400986 0x7fdce5328b80 UTL  uDebugFlag:             131 
09/16 12:33:27.400987 0x7fdce5328b80 UTL  qDebugFlag:             131 
09/16 12:33:27.400989 0x7fdce5328b80 UTL  tsdbDebugFlag:          131 
09/16 12:33:27.400990 0x7fdce5328b80 UTL  gitinfo:                community 
09/16 12:33:27.400991 0x7fdce5328b80 UTL  gitinfoOfInternal:      internal 
09/16 12:33:27.400993 0x7fdce5328b80 UTL  buildinfo:              Built at 2020-09-15 16:12:55 
09/16 12:33:27.400994 0x7fdce5328b80 UTL  version:                2.0.3.0 
09/16 12:33:27.400995 0x7fdce5328b80 UTL  maxBinaryDisplayWidth:  30 
09/16 12:33:27.400997 0x7fdce5328b80 UTL  os pageSize:            4096(KB)
09/16 12:33:27.400999 0x7fdce5328b80 UTL  os openMax:             1024
09/16 12:33:27.401000 0x7fdce5328b80 UTL  os streamMax:           16
09/16 12:33:27.401001 0x7fdce5328b80 UTL  os numOfCores:          4
09/16 12:33:27.401002 0x7fdce5328b80 UTL  os totalDisk:           0.000000(GB)
09/16 12:33:27.401004 0x7fdce5328b80 UTL  os totalMemory:         15986(MB)
09/16 12:33:27.401007 0x7fdce5328b80 UTL  os sysname:             Linux
09/16 12:33:27.401008 0x7fdce5328b80 UTL  os nodename:            ubuntu
09/16 12:33:27.401010 0x7fdce5328b80 UTL  os release:             5.4.0-47-generic
09/16 12:33:27.401011 0x7fdce5328b80 UTL  os version:             #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020
09/16 12:33:27.401012 0x7fdce5328b80 UTL  os machine:             x86_64
09/16 12:33:27.401015 0x7fdce5328b80 UTL ==================================
09/16 12:33:27.846679 0x7fdcd1ffb700 TSC ERROR 0x7fdcd42ede40 get tableMeta failed, code:Table does not exist
09/16 12:33:27.846701 0x7fdcc77fe700 TSC ERROR 0x7fdcc02efc70 get tableMeta failed, code:Table does not exist
09/16 12:33:27.846758 0x7fdcc77fe700 TSC ERROR 0x7fdcc02efc70 add into queued async res, code:Table does not exist
09/16 12:33:27.846716 0x7fdcd1ffb700 TSC ERROR 0x7fdcd42ede40 add into queued async res, code:Table does not exist
09/16 12:33:27.848996 0x7fdcd1ffb700 TSC ERROR 0x7fdcd42d2100 get tableMeta failed, code:Table does not exist
09/16 12:33:27.849070 0x7fdcd1ffb700 TSC ERROR 0x7fdcd42d2100 add into queued async res, code:Table does not exist
09/16 12:33:27.848996 0x7fdcc77fe700 TSC ERROR 0x7fdcc02f6f20 get tableMeta failed, code:Table does not exist
09/16 12:33:27.849102 0x7fdcc77fe700 TSC ERROR 0x7fdcc02f6f20 add into queued async res, code:Table does not exist
09/16 12:33:27.851912 0x7fdcd1ffb700 TSC ERROR 0x7fdcd42ced60 get tableMeta failed, code:Table does not exist
09/16 12:33:27.851954 0x7fdcd1ffb700 TSC ERROR 0x7fdcd42ced60 add into queued async res, code:Table does not exist
09/16 12:33:27.851960 0x7fdcc77fe700 TSC ERROR 0x7fdcc02ed620 get tableMeta failed, code:Table does not exist
09/16 12:33:27.405759 0x7fdce5328b80 UTL cache:tableMeta will be cleaned up

**Comment by xiaopingcs** [comment]
@hjxilinx 麻烦看一下
