### ISSUE TITLE
查询数据报DB error: Out of memory

### ISSUE THREAD

**Issue by zhenghf1985** [taosdata/TDengine#3541]
通过Python脚本从kafka读数据，然后插入Tdengine集群，
总共数据约3G 
taos> select count(*) from meters;

DB error: Out of memory
taos> select count(TBNAME) from meters;
     count(tbname)     |
========================
               1725140 |
Query OK, 1 row(s) in set (0.112526s)

taos> select * from meters limit 10;
Query interrupted (Out of memory), 0 row(s) in set (0.057932s)

**Comment by xiaopingcs** [comment]
麻烦使用show dnodes命令看一下结果。如果有log麻烦也发一下。详细log需要在taos.cfg里面把debugFlag设置成135，然后重启taosd。

**Comment by zhenghf1985** [comment]
taos> show dnodes;
   id   |                 end_point                  | vnodes | cores  |     status     |   role   |       create_time       |
==============================================================================================================================
      1 | tx-bigdata-tdengine-01-48-33:6030          |      8 |      8 | ready          | any      | 2020-09-16 10:18:32.057 |
      2 | tx-bigdata-tdengine-02-48-47:6030          |      8 |      8 | ready          | any      | 2020-09-16 10:21:51.913 |
      3 | tx-bigdata-tdengine-03-35-189:6030         |      9 |      8 | ready          | any      | 2020-09-16 10:23:43.603 |
Query OK, 3 row(s) in set (0.001021s)

修改之后，起不来了
[root@tx-bigdata-tdengine-01-48-33 ~]# systemctl restart taosd
[root@tx-bigdata-tdengine-01-48-33 ~]# taos

Welcome to the TDengine shell from Linux, Client Version:2.0.3.1
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

taos connect failed, reason: Unable to establish connection.

**Comment by xiaopingcs** [comment]
log发一下

**Comment by zhenghf1985** [comment]
[1.log](https://github.com/taosdata/TDengine/files/5230736/1.log)

**Comment by yihaoDeng** [comment]
> [1.log](https://github.com/taosdata/TDengine/files/5230736/1.log)

能远程登陆你那边码

**Comment by yihaoDeng** [comment]
> [1.log](https://github.com/taosdata/TDengine/files/5230736/1.log)

@zhenghf1985

**Comment by zhenghf1985** [comment]
腾讯云的机器 有安全组的 估计是不可以  我发完整的日志吧
[2.log](https://github.com/taosdata/TDengine/files/5231124/2.log)

**Comment by sangshuduo** [comment]
@zhenghf1985 请 stop taosd ，然后编辑 /etc/taos/taos.cfg 增加一条 debugFlag 135，再 start taosd，然后再查询，请再发一下相应的log

**Comment by kinghuisFFFF** [comment]
How to **solve** it，Please tell me, thank you @zhenghf1985
