### ISSUE TITLE
DB error: Invalid Sync Configuration

### ISSUE THREAD

**Issue by moziie** [taosdata/TDengine#3543]
三台服务器搭建集群后成功
![image](https://user-images.githubusercontent.com/70946068/93306653-c11a4900-f832-11ea-8051-a1c0bd05f2e6.png)
然后在其中一台服务器上创建表操作
CREATE TABLE db000001 USING smeters TAGS ("Beijing.chaoyang", "DID100001", "MID200001", "UID300001");
提示DB error: Invalid Sync Configuration无效的同步配置，我想问是哪个配置哪一项会引起这个问题，还是说我集群部署的问题呀

**Comment by xiaopingcs** [comment]
麻烦你把log文件发一下。详细log，需要在/etc/taos/taos.cfg文件中把debugFlag设置为135，然后重启服务器生效。

**Comment by moziie** [comment]
我换了一个服务器做master,把另外两个重新安装了一下就可以了，谢谢
