### ISSUE TITLE
docker运行后，taos命令提示以下内容，并且终端不可操作

### ISSUE THREAD

**Issue by opera123** [taosdata/TDengine#3546]
docker运行后，taos命令提示以下内容，并且终端不可操作：
![image](https://user-images.githubusercontent.com/19199235/93312954-6a187200-f83a-11ea-993d-46f147a45343.png)

**Comment by opera123** [comment]
[root@localhost opt]# docker exec -it e0 bash
[root@e0926fd51bb7 TDengine-server]# taos

Welcome to the TDengine shell from Linux, Client Version:2.0.3.1
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

No stream device
[root@e0926fd51bb7 TDengine-server]#

**Comment by xiaopingcs** [comment]
你进去之后启动taosd了么? 我这边试过了没有问题
`xiaoping@XiaoPings-MBP ~ % docker exec -it dev bash
[root@dev TDengine-server]# ls
connector  driver  examples  install.sh  taos.tar.gz
[root@dev TDengine-server]# ps -ax|grep taosd
  244 pts/1    S+     0:00 grep --color=auto taosd
[root@dev TDengine-server]# cd /usr/bin/
[root@dev bin]# ls taos*
taos  taosd  taosdemo
[root@dev bin]# nohup ./taosd > /dev/null 2>&1 &
[1] 246
[root@dev bin]# ps -ax|grep taosd
  246 pts/1    Sl     0:00 ./taosd
  288 pts/1    S+     0:00 grep --color=auto taosd
[root@dev bin]# taos

Welcome to the TDengine shell from Linux, Client Version:2.0.3.1
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

taos> show databases;
              name              |      created_time       |   ntables   |   vgroups   | replica | quorum |  days  |    keep1,keep2,keep(D)     |  cache(MB)  |   blocks    |   minrows   |   maxrows   | wallevel |    fsync    | comp | precision |    status    |
===================================================================================================================================================================================================================================================================
 log                            | 2020-09-16 08:48:35.851 |           4 |           1 |       1 |      1 |     10 | 30,30,30                   |           1 |           3 |         100 |        4096 |        1 |        3000 |    2 | us        | ready        |
Query OK, 1 row(s) in set (0.003149s)

taos> create database test;
Query OK, 0 row(s) affected (0.011005s)

taos> use test;
Database changed.`

**Comment by opera123** [comment]
![image](https://user-images.githubusercontent.com/19199235/93315642-dd6fb300-f83d-11ea-9441-4b5d1fa5be19.png)
[root@localhost opt]# docker exec -it e0 bash
[root@e0926fd51bb7 TDengine-server]# 
[root@e0926fd51bb7 TDengine-server]# ls
connector  driver  examples  install.sh  output.txt  taos.tar.gz
[root@e0926fd51bb7 TDengine-server]# ps -ax| grep taosd
     1 ?        Ssl   10:26 taosd
   217 pts/0    S+     0:00 grep --color=auto taosd
[root@e0926fd51bb7 TDengine-server]# cd /usr/bin/
[root@e0926fd51bb7 bin]# ls taos*
taos  taosd  taosdemo
[root@e0926fd51bb7 bin]# nohup ./taosd > /dev/null 2>&1 &
[1] 219
[root@e0926fd51bb7 bin]# ps -ax|grep taosd
     1 ?        Ssl   10:38 taosd
   222 pts/0    S+     0:00 grep --color=auto taosd
[1]+  Done                    nohup ./taosd > /dev/null 2>&1
[root@e0926fd51bb7 bin]# taos

Welcome to the TDengine shell from Linux, Client Version:2.0.3.1
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

taos> 


可以了，感谢！！！

**Comment by xiaopingcs** [comment]
问题已解决

**Comment by opera123** [comment]
![image](https://user-images.githubusercontent.com/19199235/93323258-f7fa5a00-f846-11ea-840a-6595503cf55e.png)
退出docker后，再进入，又是这个问题，哎。。。

**Comment by xiaopingcs** [comment]
你在docker 里面把 /etc/taos/tao.cfg 文件里面的debugFlag设置成135，然后重启taosd，然后把log发给我们看看，log在/var/log/taos/目录

**Comment by opera123** [comment]
好的，临时有点事处理一下，明天处理一下


---原始邮件---
发件人: &quot;Xiao Ping&quot;<notifications@github.com&gt;
发送时间: 2020年9月16日(周三) 晚上6:09
收件人: &quot;taosdata/TDengine&quot;<TDengine@noreply.github.com&gt;;
抄送: &quot;Author&quot;<author@noreply.github.com&gt;;&quot;opera123&quot;<2441875989@qq.com&gt;;
主题: Re: [taosdata/TDengine] docker运行后，taos命令提示以下内容，并且终端不可操作 (#3546)




 
你在docker 里面把 /etc/taos/tao.cfg 文件里面的debugFlag设置成135，然后重启taosd，然后把log发给我们看看，log在/var/log/taos/目录
 
&mdash;

**Comment by opera123** [comment]
09/16 08:49:50.240889 0x7f23cefc1700 HTP ERROR context:0x7f23360efc70, fd:718, ip:172.17.0.1:33542, code:400, error:Syntax errr in SQL
09/16 08:49:50.240930 0x7f23ccfbd700 TSC ERROR 0x7f238c5b8860 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.240959 0x7f23cc7bc700 TSC ERROR 0x7f23702ed1b0 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.240978 0x7f23ccfbd700 TSC ERROR 0x7f238c806480 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.241001 0x7f23ce7c0700 HTP ERROR context:0x7f2336100660, fd:174, ip:172.17.0.1:33546, user:root, query error, taos:0x7f238c2c7c50, code:Syntax errr in SQL, sqlObj:0x7f23702ef500
09/16 08:49:50.241014 0x7f23ce7c0700 HTP ERROR context:0x7f2336100660, fd:174, ip:172.17.0.1:33546, code:400, error:Syntax errr in SQL
09/16 08:49:50.241077 0x7f23ccfbd700 TSC ERROR 0x7f238c5babb0 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.241228 0x7f23cc7bc700 TSC ERROR 0x7f237053f490 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.241244 0x7f23ccfbd700 TSC ERROR 0x7f238c8087e0 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.241276 0x7f23cc7bc700 TSC ERROR 0x7f2370541610 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.241310 0x7f23ce7c0700 HTP ERROR context:0x7f2336111050, fd:719, ip:172.17.0.1:33548, user:root, query error, taos:0x7f238c2c7c50, code:Syntax errr in SQL, sqlObj:0x7f238c5bf250
09/16 08:49:50.241319 0x7f23ce7c0700 HTP ERROR context:0x7f2336111050, fd:719, ip:172.17.0.1:33548, code:400, error:Syntax errr in SQL
09/16 08:49:50.241324 0x7f23cefc1700 HTP ERROR context:0x7f2336121a40, fd:720, ip:172.17.0.1:33550, user:root, query error, taos:0x7f238c2c7c50, code:Syntax errr in SQL, sqlObj:0x7f23702f1850
09/16 08:49:50.241335 0x7f23cefc1700 HTP ERROR context:0x7f2336121a40, fd:720, ip:172.17.0.1:33550, code:400, error:Syntax errr in SQL
09/16 08:49:50.241370 0x7f23ccfbd700 TSC ERROR 0x7f238c5bcf00 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.241416 0x7f23cc7bc700 TSC ERROR 0x7f23702ef500 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.241539 0x7f23ce7c0700 HTP ERROR context:0x7f2336132430, fd:721, ip:172.17.0.1:33552, user:root, query error, taos:0x7f238c2c7c50, code:Syntax errr in SQL, sqlObj:0x7f238c2c9cb0
09/16 08:49:50.241547 0x7f23cefc1700 HTP ERROR context:0x7f2336142e20, fd:722, ip:172.17.0.1:33554, user:root, query error, taos:0x7f238c2c7c50, code:Syntax errr in SQL, sqlObj:0x7f23702f3ba0
09/16 08:49:50.241555 0x7f23ce7c0700 HTP ERROR context:0x7f2336132430, fd:721, ip:172.17.0.1:33552, code:400, error:Syntax errr in SQL
09/16 08:49:50.241556 0x7f23cefc1700 HTP ERROR context:0x7f2336142e20, fd:722, ip:172.17.0.1:33554, code:400, error:Syntax errr in SQL
09/16 08:49:50.241610 0x7f23ccfbd700 TSC ERROR 0x7f238c5bef00 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.241638 0x7f23cc7bc700 TSC ERROR 0x7f23702f1500 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.241827 0x7f23cefc1700 HTP ERROR context:0x7f2336153810, fd:723, ip:172.17.0.1:33556, user:root, query error, taos:0x7f238c2c7c50, code:Syntax errr in SQL, sqlObj:0x7f238c315a20
09/16 08:49:50.241844 0x7f23cefc1700 HTP ERROR context:0x7f2336153810, fd:723, ip:172.17.0.1:33556, code:400, error:Syntax errr in SQL
09/16 08:49:50.241918 0x7f23ccfbd700 TSC ERROR 0x7f238c80ab40 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.241991 0x7f23ccfbd700 TSC ERROR 0x7f238c80ccc0 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.242028 0x7f23ce7c0700 HTP ERROR context:0x7f2336164200, fd:90, ip:172.17.0.1:33558, user:root, query error, taos:0x7f238c2c7c50, code:Syntax errr in SQL, sqlObj:0x7f237003a300
09/16 08:49:50.242039 0x7f23cc7bc700 TSC ERROR 0x7f23702f39f0 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.242045 0x7f23ce7c0700 HTP ERROR context:0x7f2336164200, fd:90, ip:172.17.0.1:33558, code:400, error:Syntax errr in SQL
09/16 08:49:50.242086 0x7f23cc7bc700 TSC ERROR 0x7f2370543b40 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.242162 0x7f23cefc1700 HTP ERROR context:0x7f2336174bf0, fd:91, ip:172.17.0.1:33560, user:root, query error, taos:0x7f238c2c7c50, code:Syntax errr in SQL, sqlObj:0x7f238c317bd0
09/16 08:49:50.242173 0x7f23cefc1700 HTP ERROR context:0x7f2336174bf0, fd:91, ip:172.17.0.1:33560, code:400, error:Syntax errr in SQL
09/16 08:49:50.242187 0x7f23ccfbd700 TSC ERROR 0x7f238c2c9cb0 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.242221 0x7f23cc7bc700 TSC ERROR 0x7f2370545cc0 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.242228 0x7f23ccfbd700 TSC ERROR 0x7f238c315a20 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.242265 0x7f23cc7bc700 TSC ERROR 0x7f2370548010 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.242315 0x7f23ce7c0700 HTP ERROR context:0x7f23361855e0, fd:172, ip:172.17.0.1:33562, user:root, query error, taos:0x7f238c2c7c50, code:Syntax errr in SQL, sqlObj:0x7f23700501d0
09/16 08:49:50.242327 0x7f23ce7c0700 HTP ERROR context:0x7f23361855e0, fd:172, ip:172.17.0.1:33562, code:400, error:Syntax errr in SQL
09/16 08:49:50.242425 0x7f23cefc1700 HTP ERROR context:0x7f23361a69c0, fd:64, ip:172.17.0.1:33566, user:root, query error, taos:0x7f238c2c7c50, code:Syntax errr in SQL, sqlObj:0x7f2370052500
09/16 08:49:50.242441 0x7f23cefc1700 HTP ERROR context:0x7f23361a69c0, fd:64, ip:172.17.0.1:33566, code:400, error:Syntax errr in SQL
09/16 08:49:50.242532 0x7f23cc7bc700 TSC ERROR 0x7f237003a300 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.242582 0x7f23cc7bc700 TSC ERROR 0x7f237054a360 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.242598 0x7f23ccfbd700 TSC ERROR 0x7f238c2e4a60 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.242645 0x7f23ccfbd700 TSC ERROR 0x7f238c80f1f0 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.242661 0x7f23cc7bc700 TSC ERROR 0x7f237054c6b0 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.242677 0x7f23cefc1700 HTP ERROR context:0x7f2336195fd0, fd:180, ip:172.17.0.1:33564, user:root, query error, taos:0x7f238c2c7c50, code:Syntax errr in SQL, sqlObj:0x7f238c366ae0
09/16 08:49:50.242689 0x7f23cefc1700 HTP ERROR context:0x7f2336195fd0, fd:180, ip:172.17.0.1:33564, code:400, error:Syntax errr in SQL
09/16 08:49:50.242738 0x7f23ccfbd700 TSC ERROR 0x7f238c811370 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.242828 0x7f23ce7c0700 HTP ERROR context:0x7f23361c7da0, fd:176, ip:172.17.0.1:33570, user:root, query error, taos:0x7f238c2c7c50, code:Syntax errr in SQL, sqlObj:0x7f2370054740
09/16 08:49:50.242845 0x7f23ce7c0700 HTP ERROR context:0x7f23361c7da0, fd:176, ip:172.17.0.1:33570, code:400, error:Syntax errr in SQL
09/16 08:49:50.242900 0x7f23ccfbd700 TSC ERROR 0x7f238c8136c0 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.242953 0x7f23cefc1700 HTP ERROR context:0x7f23361b73b0, fd:106, ip:172.17.0.1:33568, user:root, query error, taos:0x7f238c2c7c50, code:Syntax errr in SQL, sqlObj:0x7f238c368e10
09/16 08:49:50.242966 0x7f23cefc1700 HTP ERROR context:0x7f23361b73b0, fd:106, ip:172.17.0.1:33568, code:400, error:Syntax errr in SQL
09/16 08:49:50.242977 0x7f23cc7bc700 TSC ERROR 0x7f23700501d0 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.243004 0x7f23ccfbd700 TSC ERROR 0x7f238c366ae0 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.243021 0x7f23cc7bc700 TSC ERROR 0x7f23700524e0 add into queued async res, code:Syntax errr in SQL
09/16 08:49:50.243072 0x7f23ce7c0700 HTP ERROR context:0x7f239be8c890, fd:711, ip:172.17.0.1:33528, user:root, query error, taos:0x7f238c2c7c50, code:Syntax errr in SQL, sqlObj:0x7f23702f5ef0
09/16 08:49:50.243088 0x7f23ce7c0700 HTP ERROR context:0x7f239be8c890, fd:711, ip:172.17.0.1:33528, code:400, error:Syntax errr in SQL
09/16 08:49:50.243187 0x7f23cefc1700 HTP ERROR context:0x7f23361e9180, fd:183, ip:172.17.0.1:33574, user:root, query error, taos:0x7f238c2c7c50, code:Syntax errr in SQL, sqlObj:0x7f2370094b40
09/16 08:49:50.243198 0x7f23cefc1700 HTP ERROR context:0x7f23361e9180, fd:183, ip:172.17.0.1:33574, code:400, error:Syntax errr in SQL
09/16 08:49:50.243343 0x7f23ce7c0700 HTP ERROR context:0x7f23361d8790, fd:178, ip:172.17.0.1:33572, user:root, query error, taos:0x7f238c2c7c50, code:Syntax errr in SQL, sqlObj:0x7f238c3698c0

**Comment by 419845351** [comment]
您好，请问这个问题解决了吗，我的docker镜像版本是2.0.6.0 也出现这个问题

**Comment by xiaopingcs** [comment]
> 您好，请问这个问题解决了吗，我的docker镜像版本是2.0.6.0 也出现这个问题

请问你具体是什么问题，报什么错

**Comment by opera123** [comment]
没有


---原始邮件---
发件人: &quot;jiangjiang&quot;<notifications@github.com&gt;
发送时间: 2020年12月28日(周一) 下午3:10
收件人: &quot;taosdata/TDengine&quot;<TDengine@noreply.github.com&gt;;
抄送: &quot;Author&quot;<author@noreply.github.com&gt;;&quot;opera123&quot;<2441875989@qq.com&gt;;
主题: Re: [taosdata/TDengine] docker运行后，taos命令提示以下内容，并且终端不可操作 (#3546)




 
您好，请问这个问题解决了吗，我的docker镜像版本是2.0.6.0 也出现这个问题
 
&mdash;

**Comment by 419845351** [comment]
使用镜像启动，进入容器后执行taos。提示no stream device。
我们测试环境可以正常用。生产环境用不了。
方便加好友看一下吗。
![image](https://user-images.githubusercontent.com/29766247/103197195-9014de80-4920-11eb-9281-c4934674c565.png)

**Comment by 419845351** [comment]
![Uploading image.png…]()
进入容器，执行taos。提示No stream device

**Comment by xiaopingcs** [comment]
你好，我这个无法复现这个问题，可以远程看一下吗，麻烦安装好向日葵， 然后添加我微信：xiaopingsf

**Comment by opera123** [comment]
没有解决这个问题。。。我改用其他时序数据库了


---原始邮件---
发件人: &quot;Xiao Ping&quot;<notifications@github.com&gt;
发送时间: 2020年12月28日(周一) 下午4:34
收件人: &quot;taosdata/TDengine&quot;<TDengine@noreply.github.com&gt;;
抄送: &quot;Author&quot;<author@noreply.github.com&gt;;&quot;opera123&quot;<2441875989@qq.com&gt;;
主题: Re: [taosdata/TDengine] docker运行后，taos命令提示以下内容，并且终端不可操作 (#3546)




 
你好，我这个无法复现这个问题，可以远程看一下吗，麻烦安装好向日葵， 然后添加我微信：xiaopingsf
 
&mdash;

**Comment by sangshuduo** [comment]
新版本已经解决了这个问题
