### ISSUE TITLE
关于数据一致性和完整性的疑问

### ISSUE THREAD

**Issue by ppd0705** [taosdata/TDengine#355]
看文档中集群设计中的描述，数据节点master/slave是asynchronous方式同步的，请问可以进一步介绍一下具体过程吗？以及对于集群数据一致性和完整性保证是怎么样的？

**Comment by guanshengliang** [comment]
白皮书上有简略回答，其他信息还属于未公开的内容

**Comment by jtao1735** [comment]
采用的机制与redis的asynchronous复制完全一样。有兴趣了解的话，请看redis的文档

**Comment by ppd0705** [comment]
好的， 谢谢
