### ISSUE TITLE
mass log output continuing

### ISSUE THREAD

**Issue by sytpb** [taosdata/TDengine#3554]
hi TD team , 

![微信图片_20200917080130](https://user-images.githubusercontent.com/12178686/93404124-f4ed8100-f8bb-11ea-995e-2488b74f002c.png)
![微信图片_20200917080457](https://user-images.githubusercontent.com/12178686/93404289-63324380-f8bc-11ea-9f3d-42af927ec3e2.png)

the same log information happen continually....  

sometimes  i found my select query returning slowly ,  so i tracked the log file  with tail -f....   ,    and i found that situation 。。 

is that any problem？

**Comment by localvar** [comment]
please update taosd configuration file and set `debugflag` to `131` and try again.
the path of the file is `/etc/taos/taos.cfg`.

**Comment by sytpb** [comment]
![image](https://user-images.githubusercontent.com/12178686/93834770-98b9a100-fcaf-11ea-849e-8e584501636d.png)

the file is too big to upload to  github , how to  send the log file  to you  ?
