### ISSUE TITLE
 TDengine is unable to query

### ISSUE THREAD

**Issue by moziie** [taosdata/TDengine#3555]
我搭建好集群，3台centos，然后跑测试插入数据，频率是每分钟插入一次，一共500张表，跑了一晚上第二天来了差不多40W+的数据量，但我使用了一次查询功能后就无法再次查询，使用select语句无法检索出结果一直显示正在执行语句，但是此时我的插入程序依旧是可以插入数据的，而且我尝试切换库操作use db;也是可以执行的。
处理1：停掉我的插入程序再次查询，依旧无法执行select
处理2：top命令查看服务器此时cpu和内存占用量
![image](https://user-images.githubusercontent.com/70946068/93409691-ffaf1280-f8c9-11ea-9641-3ce33ab823c8.png)
发现占用不高哇，就很奇怪不知道是哪里出的问题，然后重启了一下其中一个
重启前
![image](https://user-images.githubusercontent.com/70946068/93409442-7dbee980-f8c9-11ea-99fd-63f308c1f06e.png)
重启后
![image](https://user-images.githubusercontent.com/70946068/93409455-86afbb00-f8c9-11ea-9f0f-b0d75bd54790.png)
感觉这是唯一的变化，然后再查询就可以了(笑哭)
还有当时监控插件也跟着卡了就是这个
![image](https://user-images.githubusercontent.com/70946068/93409740-1a818700-f8ca-11ea-8228-15fef6bd80ee.png)
所以我想把这个问题抛出来问下有没有人遇到过类似的或者有人知道是什么原因导致的，交流交流我也学习学习哈哈

**Comment by yihaoDeng** [comment]
底层用了TCP／UDP， 查询用了TCP，插入用的UDP， 然后你这个是目前能正常工作，如果要正在查出问题， 你需要把日志级别设置为135， 出了问题请把日志发给我们

**Comment by moziie** [comment]
> 底层用了TCP／UDP， 查询用了TCP，插入用的UDP， 然后你这个是目前能正常工作，如果要正在查出问题， 你需要把日志级别设置为135， 出了问题请把日志发给我们

嗯好的，不过我重启后又遇到一个新问题，就是我本地一直连接的是VM-0-3-centos:6030这一个，但是重启之后再连接VM-0-3-centos:6030就超时，然后连接VM-0-6-centos:6030就可以，是与上面图里的role（master/slave）有关系么，还是说我的集群搭的有问题

**Comment by moziie** [comment]
昨天我又尝试一整晚插入数据，然后今天问题复现了，我发现了这个
![11](https://user-images.githubusercontent.com/70946068/93542500-c5a64500-f98b-11ea-9f05-045c69315ec9.png)
我感觉就是这个影响到select无法返回结果卡住，但是我不知道为啥会这样
然后我测试的插入数据逻辑是这样的

- for (int i = 1; i <501; i++) {
- tDengineMapper.insertMyByDb(prefixDb+i,engineData);
- }

每隔一分钟循环向500张表中插入数据

**Comment by moziie** [comment]
@yihaoDeng 期待大佬帮忙看下，要是看不出啥问题，我今天调了debug135但是重启之后就好了，下班把debug调成 135跑一晚 明天就可以贴日志了

**Comment by yihaoDeng** [comment]
@moziie 你的日志呢

**Comment by moziie** [comment]
> @moziie 你的日志呢

不好意思，问题已经解决了忘记说了，改了下插入的算法，就没在出过这个问题所以就没贴日志，感谢感谢
