### ISSUE TITLE
通过csv文件方式导入数据，导入的数据不完整，而且导的数据不是全部的数据

### ISSUE THREAD

**Issue by hhhyb** [taosdata/TDengine#356]
我的csv文件有一百万数据，第一次执行命令insert into taos_test file /usr/local/taos/bin/kk.csv;
报的错是日志提交失败，查询数量的话，表里面有一些数据但不是csv文件里的全部数据，然后再执行一次命令，执行结束后，查询数量表里面只有163024条数据。
之后再执行命令就不会再增加了。
![报错1](https://user-images.githubusercontent.com/42267833/63069780-e6ab9380-bf4a-11e9-861c-d3f1500f11c9.png)
我的问题是为什么日志会提交失败，导致我没办法找原因，这个问题怎么解决。
第二是数据表是不是有设置大小的问题，为什么只能导进去固定数量的数据。

**Comment by hzcheng** [comment]
您csv文件中的数据是属于一张表的是吗？而且时间戳递增？

**Comment by hhhyb** [comment]
是一张表，时间戳是递增的



------------------ 原始邮件 ------------------
发件人: "hzcheng"<notifications@github.com>; 
发送时间: 2019年8月15日(星期四) 中午11:25
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>; 
抄送: "拥抱."<1396988252@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [taosdata/TDengine] 通过csv文件方式导入数据，导入的数据不完整，而且导的数据不是全部的数据 (#356)




您csv文件中的数据是属于一张表的是吗？而且时间戳递增？

**Comment by plum-lihui** [comment]
您方便将这个csv文件提供给我们来验证一下吗？这样定位分析更方便更快一点。

**Comment by hhhyb** [comment]
可以的，
建表语句：CREATE TABLE taos_test(timestamp_field_name TIMESTAMP,MAX_VALUE BINARY(100),MAX_FDL BINARY(100),MAX_YDL BINARY(100));




------------------ 原始邮件 ------------------
发件人: "plum-lihui"<notifications@github.com>;
发送时间: 2019年8月15日(星期四) 中午11:51
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
抄送: "拥抱."<1396988252@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [taosdata/TDengine] 通过csv文件方式导入数据，导入的数据不完整，而且导的数据不是全部的数据 (#356)




您方便将这个csv文件提供给我们来验证一下吗？这样定位分析更方便更快一点。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


从QQ邮箱发来的超大附件

kk.csv (53.42M, 2019年09月14日 11:54 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=0c6363653c2a9f9e6b3a27364261044d00065452540704561a5a5255534c025052534e5c5458014f035201065756555a03005351646736095c4d001612610b&code=7cceda6b

**Comment by plum-lihui** [comment]
一、csv文件格式不对：2019-08-21 02:00:25.000',"""100""","""200""","""300"""
时间戳开始少了一个单引号、后面的三个字段，为什么使用那么多的引号？正确格式：
'2019-08-21 02:00:25.000', "100", "200", "300"
二、文件后面的记录不完整，从995513行开始，只有3个逗号。
2019-08-21 02:00:35.000',"""100""","""200""","""300"""
2019-08-21 02:00:36.000',"""100""","""200""","""300"""
2019-08-21 02:00:38.000',"""100""","""200""","""300"""
,,,
,,,

生成正确的csv格式后，再测试吧。

**Comment by hhhyb** [comment]
好的，我试试



------------------ 原始邮件 ------------------
发件人: "plum-lihui"<notifications@github.com>; 
发送时间: 2019年8月15日(星期四) 中午1:29
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>; 
抄送: "拥抱."<1396988252@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [taosdata/TDengine] 通过csv文件方式导入数据，导入的数据不完整，而且导的数据不是全部的数据 (#356)




一、csv文件格式不对：2019-08-21 02:00:25.000',"""100""","""200""","""300"""
 时间戳开始少了一个单引号、后面的三个字段，为什么使用那么多的引号？正确格式：
 '2019-08-21 02:00:25.000', "100", "200", "300"
 二、文件后面的记录不完整，从995513行开始，只有3个逗号。
 2019-08-21 02:00:35.000',"""100""","""200""","""300"""
 2019-08-21 02:00:36.000',"""100""","""200""","""300"""
 2019-08-21 02:00:38.000',"""100""","""200""","""300"""
 ,,,
 ,,,
 
生成正确的csv格式后，再测试吧。
