### ISSUE TITLE
DB error: Invalid Vgroup ID(centos8)

### ISSUE THREAD

**Issue by moziie** [taosdata/TDengine#3562]
搭建的集群，然后中午三台服务器上分别重启了一下taosd--命令:**sudo systemctl restart taosd**，然后连接后查询显示DB error: Invalid Vgroup ID
![image](https://user-images.githubusercontent.com/70946068/93426891-727eb480-f8ef-11ea-95f1-7532e56f5e16.png)
这是哪里出门问题了

**Comment by moziie** [comment]
[taoslog2.zip](https://github.com/taosdata/TDengine/files/5236703/taoslog2.zip)
这是日志文件 bugflag 143

**Comment by guanshengliang** [comment]
从客户端的日志来看，分析不出什么问题。猜测是集群不同步导致的。为了分析出问题，您把三台机器日志清空，把/etc/taos/taos.cfg的debugFlag设置为143，然后重启一下机器的各个节点。执行一下查询，如果还是失败，那么分别把日志上传一下，我来看看是什么问题
