### ISSUE TITLE
query stable bug：SHOW STABLES [LIKE tb_name_wildcar]

### ISSUE THREAD

**Issue by jasonsoso** [taosdata/TDengine#3569]
执行SHOW STABLES均正常，name|created_time|columns|tags|tables等字段都正常
taos> SHOW STABLES;
              name              |      created_time       | columns |  tags  |   tables    |
============================================================================================
 event_1_fire_alarm             | 2020-09-17 09:32:37.234 |       4 |      2 |           1 |
 event_1_temp_sensor            | 2020-09-17 09:32:50.677 |       2 |      2 |           0 |
 prop_1293032718550515712       | 2020-09-11 10:22:18.699 |       3 |      1 |           1 |
 prop_1                         | 2020-09-11 13:54:35.775 |       4 |      1 |           1 |
 event_1293032718550515712_fire | 2020-09-17 10:20:00.502 |       5 |      2 |           1 |
Query OK, 5 row(s) in set (0.002802s)

执行SHOW STABLES [LIKE tb_name_wildcar]不正常，created_time|columns|tags|tables等字段都不正常
taos> SHOW STABLES LIKE 'event_1293032718550515712_fire_alarm' ;
              name              |      created_time       | columns |  tags  |   tables    |
============================================================================================
 event_1293032718550515712_fire | 1970-01-01 08:00:00.000 |       0 |      0 |           0 |
Query OK, 1 row(s) in set (0.003345s)

**Comment by jasonsoso** [comment]
日志如下：
09/17 16:50:09.541948 0x7f7b847f6700 DND msg:status will be processed in mpeer queue
09/17 16:50:09.917210 0x7f7bd37fe700 DND 0x7f7b74001170, msg:heartbeat will be processed in mread queue
09/17 16:50:09.975873 0x7f7bd27fc700 DND 0x7ff310001170, msg:heartbeat will be processed in mread queue
09/17 16:50:10.546932 0x7f7b847f6700 DND msg:status will be processed in mpeer queue
09/17 16:50:10.793806 0x7f7b80fef700 MND user:root, auth info is returned
09/17 16:50:10.794079 0x7f7bd37fe700 DND 0x7ff308019a20, msg:show will be processed in mread queue
09/17 16:50:10.794133 0x7f7bd37fe700 MND 0x7f7b680029f0, show is put into cache, data:0x7f7b68002590 index:122
09/17 16:50:10.794177 0x7f7bd37fe700 MND 0x7f7b680029f0, show type:show stables index:122, get meta finished, numOfRows:5 cols:5 result:success
09/17 16:50:10.794207 0x7f7bd37fe700 MND 0x7f7b680029f0, show is released, force:false data:0x7f7b68002590 index:122
09/17 16:50:10.794748 0x7f7bd27fc700 DND 0x7ff308019a20, msg:retrieve will be processed in mread queue
09/17 16:50:10.794830 0x7f7bd27fc700 MND 0x7f7b680029f0, show is accquired from cache, data:0x7f7b68002590, index:122
09/17 16:50:10.794842 0x7f7bd27fc700 MND 0x7f7b680029f0, show type:show stables index:122, start retrieve data, numOfReads:0 numOfRows:5
09/17 16:50:10.794865 0x7f7bd27fc700 MND 0x7f7b680029f0, show type:show stables index:122, stop retrieve data, rowsRead:1 rowsToRead:5
09/17 16:50:10.794869 0x7f7bd27fc700 MND 0x7f7b680029f0, retrieve not completed yet
09/17 16:50:10.794872 0x7f7bd27fc700 MND 0x7f7b680029f0, show is released, force:false data:0x7f7b68002590 index:122
09/17 16:50:10.795309 0x7f7bd37fe700 DND 0x7ff308019a20, msg:retrieve will be processed in mread queue
09/17 16:50:10.795354 0x7f7bd37fe700 MND 0x7f7b680029f0, show is accquired from cache, data:0x7f7b68002590, index:122
09/17 16:50:10.795368 0x7f7bd37fe700 MND 0x7f7b680029f0, show type:show stables index:122, start retrieve data, numOfReads:1 numOfRows:5
09/17 16:50:10.795379 0x7f7bd37fe700 MND 0x7f7b680029f0, show is already read finished, numOfReads:1 numOfRows:5
09/17 16:50:10.795392 0x7f7bd37fe700 MND 0x7f7b680029f0, show type:show stables index:122, stop retrieve data, rowsRead:0 rowsToRead:0
09/17 16:50:10.795398 0x7f7bd37fe700 MND 0x7f7b680029f0, retrieve completed
09/17 16:50:10.795403 0x7f7bd37fe700 MND 0x7f7b680029f0, show is released, force:true data:0x7f7b68002590 index:122
09/17 16:50:10.795409 0x7f7bd37fe700 MND 0x7f7b680029f0, show is destroyed, data:0x7f7b68002590 index:122
09/17 16:50:11.421876 0x7f7bd27fc700 DND 0x7f7b74001170, msg:heartbeat will be processed in mread queue
09/17 16:50:11.481254 0x7f7bd37fe700 DND 0x7ff310001170, msg:heartbeat will be processed in mread queue
09/17 16:50:11.552453 0x7f7b847f6700 DND msg:status will be processed in mpeer queue
09/17 16:50:12.556798 0x7f7b847f6700 DND msg:status will be processed in mpeer queue

**Comment by sangshuduo** [comment]
前面建表过程的SQL语句是怎样的？

**Comment by sangshuduo** [comment]
确实是个 bug，我们尽快解决一下

**Comment by yihaoDeng** [comment]
这个BUG， 我们已经修复，请等等下一个版本， 或者develop 分支直接编译即可
