### ISSUE TITLE
tdengine for aarch64 移植

### ISSUE THREAD

**Issue by dvt0551** [taosdata/TDengine#357]
在中标麒麟操作系统7.（64位）、cent-os-7.6/64(aarch64)  移植成功
中标麒麟:Linux ta_p 4.14.0-49.el7a.1.aarch64 #1 SMP Mon Nov 26 14:19:51 CST 2018 aarch64 aarch64 aarch64 GNU/Linux

Linux localhost.localdomain 4.14.0-115.el7a.0.1.aarch64 #1 SMP Sun Nov 25 20:54:21 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux

不成功的是：
Linux ubuntu18042lts 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:23:38 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux

下面为修改地方：
编译参数如下：（修改CMakeList.txt)
SET(COMMON_FLAGS "-std=gnu99 -Wall -fPIC  -g  -mlittle-endian -Wno-char-subscripts -mstrict-align -fsigned-char  -D_FILE_OFFSET_BITS=64 -D_LARGE_FILE")
修改代码tcrc32.c：使用软件crc
/*#include <nmmintrin.h>
*/
#include <stdio.h>
#include <stdlib.h>

#include "tcrc32c.h"
//todo : use the original source code
#pragma GCC diagnostic ignored "-Wunused-function"

.....
uint32_t (*crc32c)(uint32_t crci, crc_stream bytes, size_t len) = NULL;

void taosResolveCRC() {
/*  int sse42;
  SSE42(sse42);
  crc32c = sse42 ? crc32c_hw : crc32c_sf;
*/
  crc32c=crc32c_sf;
        /* return sse42 ? crc32c_hw(crci, bytes, len) : crc32c_sf(crci, bytes, len);
   */
}

修改:vnodeMeter.c 617行关于线程锁元操作
 pthread_mutex_lock(&(pVnode->vmutex));
  pVnode->vnodeStatistic.pointsWritten+=points * (pObj->numOfColumns - 1);
 // __sync_fetch_and_add((int64_t *)&(pVnode->vnodeStatistic.pointsWritten), (int64_t) points * (pObj->numOfColumns - 1));
   
  pVnode->vnodeStatistic.totalStorage+= points * pObj->bytesPerPoint;

  //__sync_fetch_and_add(&(pVnode->vnodeStatistic.totalStorage), points * pObj->bytesPerPoint);

  //pthread_mutex_lock(&(pVnode->vmutex));

  if (pObj->lastKey > pVnode->lastKey) pVnode->lastKey = pObj->lastKey;

  if (firstKey < pVnode->firstKey) pVnode->firstKey = firstKey;

不然会报如下错误
[New Thread 0xffffaf44f200 (LWP 6538)]
[New Thread 0xffffaec0f200 (LWP 6539)]

Program received signal SIGBUS, Bus error.
0x00000000004786d0 in vnodeInsertPoints (pObj=0x6a7f50, cont=0x6c8690 "", contLen=106, source=4 '\004', param=0x0, sversion=0, 
    numOfInsertPoints=0xfffffffff080) at /opt/td/TDengine/src/system/src/vnodeMeter.c:617
617       __sync_fetch_and_add((int64_t *)&(pVnode->vnodeStatistic.pointsWritten), (int64_t) points * (pObj->numOfColumns - 1));
Missing separate debuginfos, use: debuginfo-install glibc-2.17-260.el7_6.6.aarch64

**Comment by plum-lihui** [comment]
Great work！

**Comment by dvt0551** [comment]
ubuntu 18.04.3lts无法启动 出现如下错误
08/19 14:25:50.804926 ffffa8ac11f0 TSC 0xffff68000c20 Async SQL result:-29 taosres:(nil)
08/19 14:25:50.804933 ffffa8ac11f0 ERROR MON monitor:0xffff68000b20, connect to taosd failed, code:-29
属于127.0.0.1 无法访问 因为本系统不支持ip-v4
修改/etc/rc.local

root@ubuntu18042lts:/opt/td/TDengine# cat /etc/hosts
10.10.25.47     ubuntu18042lts

# The following lines are desirable for IPv6 capable hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
# ::1     localhost ip6-localhost ip6-loopback
# ff02::1 ip6-allnodes
# ff02::2 ip6-allrouters

重启动网络服务
systemctl restart networking

搞定aarch64环境的移植问题
其实个人认为这是一个bug，使用RPC（127.0.0.1）方式，最好启动的时候测试一下127.0.0.1是否可ping通。不然检查太费劲。

**Comment by ohmyheartbeat** [comment]
你好 能指出修改的代码文件的路径吗

**Comment by ohmyheartbeat** [comment]
找到了，是tcrc32c.c文件，在src/util/src/下1350行；vnodeMeter.c在src/system/src下第615行

**Comment by dvt0551** [comment]
是的
想做arm32的移植，目前没有环境
您有对应的虚拟机环境吗
谢谢！
（kvm的虚拟机）


------------------ 原始邮件 ------------------
发件人: "ohmyheartbeat"<notifications@github.com>;
发送时间: 2019年9月3日(星期二) 下午4:09
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
抄送: "沉默寡人"<841046078@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [taosdata/TDengine] tdengine for aarch64 移植 (#357)




找到了，是tcrc32c.c文件，在src/util/src/下1350行；vnodeMeter.c在src/system/src下第615行

**Comment by dhdljd** [comment]
> ubuntu 18.04.3lts无法启动 出现如下错误
> 08/19 14:25:50.804926 ffffa8ac11f0 TSC 0xffff68000c20 Async SQL result:-29 taosres:(nil)
> 08/19 14:25:50.804933 ffffa8ac11f0 ERROR MON monitor:0xffff68000b20, connect to taosd failed, code:-29
> 属于127.0.0.1 无法访问 因为本系统不支持ip-v4
> 修改/etc/rc.local
> root@ubuntu18042lts:/opt/td/TDengine# cat /etc/hosts
> 10.10.25.47     ubuntu18042lts
> The following lines are desirable for IPv6 capable hosts
> 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
> ::1     localhost ip6-localhost ip6-loopback
> ff02::1 ip6-allnodes
> ff02::2 ip6-allrouters
> 重启动网络服务
> systemctl restart networking
> 搞定aarch64环境的移植问题
> 其实个人认为这是一个bug，使用RPC（127.0.0.1）方式，最好启动的时候测试一下127.0.0.1是否可ping通。不然检查太费劲。

@dvt0551 您好，按照您的方法，已经在树莓派的ubuntu18.04安装成功，但是taos客户端命令，连接失败，不知道是不是您说的ip-4的问题，这一段能否请您再说的详细一些？谢谢！

**Comment by plum-lihui** [comment]
可以把配置文件的调试开关打开，再taos连接一下，然后分析一下日志。看看是什么原因。@dhdljd

**Comment by dhdljd** [comment]
> 可以把配置文件的调试开关打开，再taos连接一下，然后分析一下日志。看看是什么原因。@dhdljd

重启树莓派以后，调试开关是打开了，但是这回服务端也起不来了。
直接报错 Bus error (core dumped)，之前还是在客户端连接的时候报这个错误。
![image](https://user-images.githubusercontent.com/53200354/65830017-27ceeb80-e2de-11e9-9905-fc53c9b7da8c.png)

**Comment by dvt0551** [comment]
我都遇到过 ～127.0.0.1 bus error &nbsp;客户端无法连接debug 可以搞定的
 
---原始邮件---
发件人: "dhdljd"<notifications@github.com&gt;
发送时间: 2019年9月29日(星期日) 下午5:26
收件人: "taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"dvt0551"<841046078@qq.com&gt;;
主题: Re: [taosdata/TDengine] tdengine for aarch64 移植 (#357)


 
可以把配置文件的调试开关打开，再taos连接一下，然后分析一下日志。看看是什么原因。@dhdljd
  
重启树莓派以后，调试开关是打开了，但是这回服务端也起不来了。
 直接报错 Bus error (core dumped)，之前还是在客户端连接的时候报这个错误。

**Comment by plum-lihui** [comment]
那只能用gdb启动taosd，一点一点来调试，把需要修改的地方都修改了。

**Comment by nanjj** [comment]
```
mkdir build
cd build
cmake .. -DCPUTYPE=aarch64
cmake . --build
```
