### ISSUE TITLE
C++ api taos_query() insert error but return success

### ISSUE THREAD

**Issue by mxmkeep** [taosdata/TDengine#3573]
**Bug Description**
TAOS_RES* taos_query(TAOS *taos, const char *sql)
insert插入语句错误，但没返回NULL，还是成功，只是no是乱码
err=success no=-2147482782

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by yihaoDeng** [comment]
并不是乱码， 你可以对照https://www.taosdata.com/cn/documentation/taos-error-code/， 查看对应的错误信息

**Comment by mxmkeep** [comment]
> 并不是乱码， 你可以对照[https://www.taosdata.com/cn/documentation/taos-error-code/，](https://www.taosdata.com/cn/documentation/taos-error-code/%EF%BC%8C) 查看对应的错误信息

那就是得双条件判断是否执行成功？
if(TAOS_RES == NULL || taos_errno(TAOS_RES) != 0)
  error .........
