### ISSUE TITLE
TDEngine on single node cannot restart

### ISSUE THREAD

**Issue by MrDingDing** [taosdata/TDengine#3574]
数据库里存了3500亿数据之后 想要修改参数时 重启服务起不来了， 两个日志文件taosdlog.0和taosdlog.1一直在刷日志
<img width="655" alt="WeChat Image_20200917194124" src="https://user-images.githubusercontent.com/38071648/93465877-f2237800-f91d-11ea-9afc-fbe30ae78bf7.png">

<img width="816" alt="WeChat Image_20200917194216" src="https://user-images.githubusercontent.com/38071648/93465871-f0f24b00-f91d-11ea-98ba-f892d523a32a.png">

**Comment by sangshuduo** [comment]
请在 /etc/taos/taos.cfg 中打开调试标识

debugFlag 135

然后启动 systemctl start taosd

看一下 log 中的错误信息是什么

**Comment by Aries-Lee1991** [comment]
@MrDingDing 这个问题您这边是否解决？如果没有解决，麻烦把日志信息附一下。

**Comment by sangshuduo** [comment]
暂时关闭，如果有更详细信息我们再打开这个 issue 来看。
