### ISSUE TITLE
子表很多，对超级表进行连续查询，没有结果

### ISSUE THREAD

**Issue by lnparker** [taosdata/TDengine#358]
如题，子表很多(基于设备与信息类别建字表，所以子表很多，几百万至少)，对超级表进行连续查询，将连续查询的结果写到一张表里，CREATE TABLE q AS SELECT COUNT(*) ,  AVG(dt_ts_event) ,  SUM(elem_index) ,  MAX(cli_type) FROM super  INTERVAL(1M) SLIDING(1M); 但是每分钟到这张表里查询都查询不到结果。

**Comment by lnparker** [comment]
测试过如果不采用超级表，而使用单表，连续查询是有结果的。但是如果使用单表，很多设备的采集时间是一致的，会导致数据冲突

**Comment by lnparker** [comment]
@hjxilinx 您好，请问你们在测试的时候有遇到类似的场景么，是子表太多的时候连续查询性能会下降么

**Comment by hjxilinx** [comment]
我们没有测试过百万级别的表的连续查询。如果表的数量少一点，超级表的连续查询有结果吗？如果表的数量少了以后有结果。
那么请把没有结果的那个场景的日志提供给我，我们可以协助分析解决。日志可发送到：hjliao@taosdata.com

**Comment by lnparker** [comment]
hi，您好，我可能没有表达清楚，我们业务的使用场景是采集设备上的事件信息，所以设备大概率会超过百万甚至千万级别，目前我们在测试的当只有几千张子表甚至更少，连续查询也没有结果

**Comment by lnparker** [comment]
对应的日志已经发到邮箱，辛苦帮定位一下

**Comment by lnparker** [comment]
@hjxilinx 帮忙看一下，谢谢

**Comment by lnparker** [comment]
又做了一个测试，超级表的根据tag建立的子表仅有10张表，连续查询也是没有结果的，超级表也仅有7个字段，请问超级表是暂时不支持连续查询么

**Comment by lnparker** [comment]
![image](https://user-images.githubusercontent.com/5960644/63247782-74afb300-c298-11e9-95f7-ee20d8ac5952.png)

**Comment by lnparker** [comment]
上图中的q表就是存放连续查询结果的表，只有7个字段，10张子表

**Comment by lnparker** [comment]
@guanshengliang hello？帮看下？

**Comment by hzcheng** [comment]
您留下您的邮箱吧，我们会发联系方式给您，帮您看下
