### ISSUE TITLE
Error reported while stop a node in cluster

### ISSUE THREAD

**Issue by dingwei92** [taosdata/TDengine#3582]
**General Questions**
1.3台服务器集群部署的时候，在一台服务器上执行systemctl stop taosd,在其他2台服务器上执行查询语句，会报DB error: Database not ready

日志
09/18 13:53:39.135286 0x7f52adcb1700 RPC ERROR TSC 0x7f52980108f0, failed to set up connection(Unable to establish connection)
09/18 13:53:39.145806 0x7f52adcb1700 TSC WARN 0x7f52980108f0 it shall renew table meta, code:Database not ready, retry:1
09/18 13:53:39.147856 0x7f52adcb1700 RPC ERROR TSC 0x7f52980108f0, failed to set up connection(Unable to establish connection)
09/18 13:53:39.151321 0x7f52adcb1700 TSC WARN 0x7f52980108f0 it shall renew table meta, code:Database not ready, retry:2
09/18 13:53:39.355194 0x7f52adcb1700 RPC ERROR TSC 0x7f52980108f0, failed to set up connection(Unable to establish connection)
09/18 13:53:39.358194 0x7f52adcb1700 TSC WARN 0x7f52980108f0 it shall renew table meta, code:Database not ready, retry:3
09/18 13:53:39.761621 0x7f52adcb1700 RPC ERROR TSC 0x7f52980108f0, failed to set up connection(Unable to establish connection)
09/18 13:53:39.764841 0x7f52adcb1700 TSC WARN 0x7f52980108f0 it shall renew table meta, code:Database not ready, retry:4
09/18 13:53:40.569129 0x7f52adcb1700 RPC ERROR TSC 0x7f52980108f0, failed to set up connection(Unable to establish connection)
09/18 13:53:40.572738 0x7f52adcb1700 TSC WARN 0x7f52980108f0 it shall renew table meta, code:Database not ready, retry:5
09/18 13:53:42.176857 0x7f52adcb1700 RPC ERROR TSC 0x7f52980108f0, failed to set up connection(Unable to establish connection)
09/18 13:53:42.180036 0x7f52adcb1700 TSC WARN 0x7f52980108f0 it shall renew table meta, code:Database not ready, retry:6
09/18 13:53:42.180054 0x7f52adcb1700 TSC ERROR 0x7f52980108f0 max retry 5 reached, give up

**Comment by guanshengliang** [comment]
要看您是几个副本，如果单副本的数据库，那么停止一台机器确实不能继续提供服务。
不知道，您这个测试的目的是什么，是测试高可用性吗？

**Comment by guanshengliang** [comment]
There is no reply for a long time
