### ISSUE TITLE
TDengine 2.0.3.1  and jdbc 2.0.4, run official demo, can't get result by "how tables"

### ISSUE THREAD

**Issue by hsn999** [taosdata/TDengine#3584]
数据库 2.0.3.1  jdbc 2.0.4  按demo操作，show tables看不到表 ，数据写进去了，按stable可以查

INSERT INTO dev_005 using iot.meters tags(?, ?) (ts, deviceId,currentA,voltageA) values (?,?, ?, ?) 

show tables 看不到 dev_005

**Comment by sangshuduo** [comment]
@hsn999 请问这个问题是解决了吗？能否分享一下如何解决的？

**Comment by hsn999** [comment]
默认数据库的问题，demo的默认数据库是log，因此创建的的表都写到log数据库下面了！但是查询stable又可以查询到数据，查子表不行！，把springcloud配置文件的库 配置改成自己的就好了

**Comment by hsn999** [comment]
这应该也是个bug，如果stable是哪个库，子表就应该写到那个库

**Comment by sangshuduo** [comment]
@zyyang-taosdata 是不是这个问题在新版本里已经解决了？我跑 jdbcdemo 看起来没什么问题
