### ISSUE TITLE
request to support geo-info data

### ISSUE THREAD

**Issue by jasonsoso** [taosdata/TDengine#3586]
地理坐标类型(Geo-point)在应用中的一些特殊使用场景
比如一些筛选，或者方圆几公里的共享单车等等场景
所以建议添加Geo-point的支持，谢谢！

**Comment by sangshuduo** [comment]
谢谢，我们会评估这个需求。

**Comment by trj832000** [comment]
@sangshuduo  is any plan for geo-data  ?

**Comment by sangshuduo** [comment]
> @sangshuduo is any plan for geo-data ?

no news to announce so far. I think it would be accelerated if a paid version customer requests.

**Comment by curtiseng** [comment]
I found the geo feature supported at  https://github.com/taosdata/TDengine/pull/21037, Which version contains the geo feature, is that have support in the cloud product?

**Comment by sangshuduo** [comment]
> I found the geo feature supported at #21037, Which version contains the geo feature, is that have support in the cloud product?

Yes. Thanks @dinglezhang 's contribution. TDenigne already supports GEO data type from 3.0.5.0 in the database engine. We will develop to support GEO data type in the connectors.
The TDengine cloud would upgrade the database release a bit later.

**Comment by sangshuduo** [comment]
@jasonsoso @trj832000 @curtiseng welcome to raise your feature request for any special GEO function then we can prioritize them. Thanks.

**Comment by watchpoints** [comment]
感兴趣
