### ISSUE TITLE
DB error: invalid SQL: only one selectivity function allowed in presence of tags f unction

### ISSUE THREAD

**Issue by sexbee** [taosdata/TDengine#3589]
**Bug Description**

2.0.3.1 

SQL:
select last_row(*) ,location, admiddate, adidate,  pname, age , psex, height, weight from db_mrnost.st_mrnxst where onoff = "no" and location ="x4f" group by tbname;
ERR:

DB error: invalid SQL: only one selectivity function allowed in presence of tags f
unction

**Comment by sangshuduo** [comment]
Thanks for reporting. We will resolve this issue.

**Comment by hjxilinx** [comment]
location, admiddate, adidate, pname, age , psex, height, weight 都是标签吗？
如果是的，那么在2.0.4.0版本中已经修复了这个问题。

**Comment by sexbee** [comment]
经过测试，2.0.4.0 版本未解决该问题。

**Comment by sangshuduo** [comment]
@sexbee 请问你需要什么 SQL 命令？可以详细解释一下吗？

**Comment by sexbee** [comment]
@sangshuduo  thanks  2.0.5.1   be solved!
