### ISSUE TITLE
ROS support?

### ISSUE THREAD

**Issue by MikoyChinese** [taosdata/TDengine#36]
Hi,
The data publishing from ros is also have timestamp and data.
So does it mean that the TDengine can replace the ros Subscriber and Publisher Node? And every sensor's data insert the super table, and When I need to analy the data, select it.
Maybe you can wrrite the document about ROS example or support, Thanks this outstanding project, it will be successful.

Yours sincerely,
**Mikoy Chinese**.

**Comment by jtao1735** [comment]
ROS means Robot Operating System? may you share a little bit background information? we can take a look. Thanks
