### ISSUE TITLE
Questions about cluster

### ISSUE THREAD

**Issue by moziie** [taosdata/TDengine#3600]
我部署了tdengine集群在3台服务器上，现在是三个节点，但是当主master这个节点宕机后，如何保证我的项目依旧可以使用tdengine服务，是tdengine自带服务还是需要我自己额外配置其他功能来实现；
1、目前我测试宕掉正在连接的tdengine服务，他是无法连接到集群的另外两个中任何一个；
2、当我将宕掉的服务重新开启，虽然能连接但是无法执行插入语句；
因为我在官网文档中找不到答案，所以在此提问，期待您的回复为我解惑！

**Comment by applesun8799** [comment]
对，我测试也是这个问题，顶你上去****

**Comment by hzcheng** [comment]
建库的时候有指定副本数吗（replica）？

**Comment by moziie** [comment]
使用中的这个库没有指定副本数，默认是1

> 建库的时候有指定副本数吗（replica）？

**Comment by plum-lihui** [comment]
使用的哪个版本呢？

**Comment by moziie** [comment]
版本是2.0.3linux系统是centos8

**Comment by plum-lihui** [comment]
应用连接集群时，只要开始指定集群中任何一个可用的节点就可以了。后续如果有节点断机，内部会自动进行切换的。

**Comment by moziie** [comment]
> 应用连接集群时，只要开始指定集群中任何一个可用的节点就可以了。后续如果有节点断机，内部会自动进行切换的。

![1600741956(1)](https://user-images.githubusercontent.com/70946068/93839262-fb666900-fcbe-11ea-97b5-d4ddb3387bf3.jpg)
我是这样配置的。连接的是VM-0-3-centos这一台，我手动断掉这个就无法连接tdengine服务了，查询VM-0-6-centos这个变成master，然后我再次启动VM-0-3-centos成为slave，项目虽然重新连接但是只能执行查询语句，插入语句无法执行

**Comment by plum-lihui** [comment]
方便的话，远程定位吧，凭这些信息无法分析是什么原因。微信：13611161621

**Comment by moziie** [comment]
好的
