### ISSUE TITLE
How to use `where in`

### ISSUE THREAD

**Issue by WuYunlong** [taosdata/TDengine#3602]
目前有一个需求是这样的   

create table meters (ts timestamp, a int, b int);
create table t1 USING meters;
create table t2 USING meters;

insert into t1 (now , 1, 10);
insert into t1 (now , 2, 10);
insert into t1 (now , 2, 10);
insert into t1 (now , 3, 10);
insert into t1 (now , 4, 10);

insert into t2 (now , 5, 10);
insert into t2 (now , 6, 10);
insert into t2 (now , 6, 10);
insert into t2 (now , 7, 10);
insert into t2 (now , 8, 10);

现在我需要得到 a=2 || a=6 的b的平均值  我要如何编写sql

select AVG(b) from meters where a=2 or a=6; 
这样是可以可以满足2个a的情况 但是在实际操作中 a 可能能达到 200多个值 要这样一直or下去吗

where a in (2, 6)
这样的sql不被支持。

**Comment by localvar** [comment]
抱歉，这个功能暂时还不支持，但已在后续版本计划中，请关注。
