### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment（Java开发应用程序，在Windows正常运行，在Linux出现异常）

### ISSUE THREAD

**Issue by Mrgongm** [taosdata/TDengine#3603]
**Bug Description**
通过java -jar 启动jar包，windows正常。Linux会报错：
Failed to write core dump. Core dumps have been disabled.

**To Reproduce**
1. java -jar ByTaosDemo.jar
2. 报错：
```
(base) beiyang@beiyang:~/NetBeansProjects/MADPS$ java -jar ByTaosDemo.jar 
java.library.path:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f276ae678a4, pid=22183, tid=0x00007f276a3d3700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_251-b08) (build 1.8.0_251-b08)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.251-b08 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libbsd.so.0+0x68a4]  MD5Pad+0x24
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/beiyang/NetBeansProjects/MADPS/hs_err_pid22183.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
已放弃 (核心已转储)
```

**Environment (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - Memory 16GB, CPU: 8  Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz, current Disk Space 1TB
 - TDengine Version [e.g. 2.0.3.1]
 - 开发工具：Netbeans-8.2

**Additional Context**
[提供源码和编译的jar包 ByTaosDemo.zip](https://github.com/taosdata/TDengine/files/5253735/ByTaosDemo.zip)

**Comment by Mrgongm** [comment]
JDBC:taos-jdbcdriver-2.0.4

**Comment by Mrgongm** [comment]
发现jdbc版本未更新，将taos-jdbcdriver更新至2.0.5版本，该问题得到解决。

但连接数据库失败（Windows与Linux均失败）。

**Comment by zyyang-taosdata** [comment]
taos-jdbcdriver-2.0.5有bug，我们会尽快修复改问题，请暂时使用jdbcdriver-2.0.4

**Comment by Mrgongm** [comment]
> taos-jdbcdriver-2.0.5有bug，我们会尽快修复改问题，请暂时使用jdbcdriver-2.0.4

感谢！
但很抱歉，jdbcdriver-2.0.4暂无法使用，期待新版本早日发布，辛苦了

**Comment by Mrgongm** [comment]
> taos-jdbcdriver-2.0.5有bug，我们会尽快修复改问题，请暂时使用jdbcdriver-2.0.4

我看到taos-jdbcdriver-2.0.6.jar已经发布，但该问题仍然存在（Windows连接成功，Linux报错Failed to write core dump. Core dumps have been disabled. ）

**Comment by ZhangJiaLei123** [comment]
我再windows上还没有连接成功,请问您是怎么做到的?
环境:
``` 
Server: TDengine-server-2.0.4.0-Linux-x64
Windows10: TDengine-client-2.0.4.0-Windows-x64
Jar:taos-jdbcdriver-2.0.6.jar
```
运行官方的JDBCDemo结果如下:
https://github.com/taosdata/TDengine/issues/3636#issuecomment-697203010

**Comment by zyyang-taosdata** [comment]
从你的描述我看到，你是在windows环境下用TSDBSyncSample的代码去访问TDengine实例，请做如下检查：

在你的windows10开发机器上，C:\TDengine目录下执行命令行工具taos.exe -h 192.168.0.11
如果在windows的client端，无法连接到server端的taosd实例，请参考官网的文档，配置fqdn
FAQ：
官网FAQ

**Comment by Mrgongm** [comment]
> 我下载并尝试查看你的程序，但是你的源码没有使用UTF-8编码，并且，你的程序使用awt，你应该是在用java开发桌面端应用，这样的程序本身就不是跨平台。
> ![image](https://user-images.githubusercontent.com/69311263/94095396-3bab2000-fe54-11ea-9e57-6a847752d434.png)

@zyyang-taosdata 
1、源码使用的是UTF-8编码，由于我的失误，上传了被加密过的代码，非常抱歉。
2、您说得对，我使用java开发桌面端应用，程序中用到awt。
3、使用开发工具Netbeans制作jar包，使用 java -jar **.jar 运行，不是跨平台但应该可以启动。

**Comment by Mrgongm** [comment]
问题出现后我也尝试过寻找方法解决，在尝试过程中，发现一个现象：

当我先打开应用界面，后连接TDengine时，会出现该“Failed to write core dump. Core dumps have been disabled.”错误，
但如果先连接TDengine，后打开应用界面，则正常启动

**To Reproduce：**
```
  public static void main(String[] args) {
        //测试TD连接
        TaosUtil taosUtil = new TaosUtil();
        taosUtil.testConnect();
        //打开frame
        TestTaosJFrame taosJFrame = new TestTaosJFrame();
        taosJFrame.setVisible(true);
    }
//连接正常，界面启动正常
```
```
 public static void main(String[] args) {
        //打开frame
        TestTaosJFrame taosJFrame = new TestTaosJFrame();
        taosJFrame.setVisible(true);
        //测试TD连接
        TaosUtil taosUtil = new TaosUtil();
        taosUtil.testConnect();
    }
//连接异常，界面无法启动
```

![error](https://user-images.githubusercontent.com/42021493/94240838-6b3a5500-ff46-11ea-9638-4c34aabf71e5.png)




源码如下：
[ByTaosDemo.zip](https://github.com/taosdata/TDengine/files/5281268/ByTaosDemo.zip)
