### ISSUE TITLE
jdbc2.0.5 ‘s mistake

### ISSUE THREAD

**Issue by realskyzou** [taosdata/TDengine#3604]
private static final String URL_PREFIX = "jdbc:TAOS://";

String lowerUrl = url.toLowerCase();//转小写？？？
        if (!lowerUrl.startsWith(URL_PREFIX) && !lowerUrl.startsWith(URL_PREFIX1)) {
            return null;
        }

**Comment by zyyang-taosdata** [comment]
是的，taos-jdbcdriver-2.0.5有问题，我们会尽快修改这个问题，请暂时不要升级jdbc版本‘、

**Comment by zyyang-taosdata** [comment]
已经在taos-jdbcdriver-2.0.6里修复
