### ISSUE TITLE
Report DB error: Unable to establish connection while creating tables

### ISSUE THREAD

**Issue by moziie** [taosdata/TDengine#3605]
**### 环境：**正在使用中的tdengine，3台服务器3节点集群，有一个数据库存在数据，新建了一个数据库并设置副本数为3
### 操作****：在新建的数据库中创建超级表没有问题，使用此超级表创建子表的时候报错，在超级表查询没有问题
![1600671938(1)](https://user-images.githubusercontent.com/70946068/93739933-103df080-fc1c-11ea-9ed3-0bdf31dede9f.jpg)
![1600671956(1)](https://user-images.githubusercontent.com/70946068/93739936-12a04a80-fc1c-11ea-9cbd-9fa87c8f61ce.jpg)
![1600671973(1)](https://user-images.githubusercontent.com/70946068/93739939-13d17780-fc1c-11ea-8915-30da8710d0b0.jpg)
![1600671985(1)](https://user-images.githubusercontent.com/70946068/93739944-1502a480-fc1c-11ea-9ad8-e6d6609e97cd.jpg)

**Comment by hzcheng** [comment]
可否运行show mnodes; 和show dnodes;命令来查看下集群状态？

**Comment by moziie** [comment]
![1600741476(1)](https://user-images.githubusercontent.com/70946068/93838921-d9201b80-fcbd-11ea-88e6-8d73234ea402.jpg)
操作过程

**Comment by Shawshank-Smile** [comment]
请加我微信：13720014098， 需要远程登录上去定位一下。

**Comment by moziie** [comment]
谢谢，已解决因为只有三个节点，数据库设置的是3个副本，但是我其中一个节点远程连接服务不可用导致了这个问题
