### ISSUE TITLE
使用SQL脚本创建数据库时偶尔无法读取sql脚本

### ISSUE THREAD

**Issue by wanghh1024** [taosdata/TDengine#361]
sql脚本如下
create database if not exists db3
create table if not exists db3.tb3 (ts timestamp, male nchar(20), famale nchar(20))
import into db3.tb3 file test.csv
使用taos>source test.sql;指令执行sql脚本后出现乱码，如图
![image](https://user-images.githubusercontent.com/53716678/63083334-0a86cd80-bf7b-11e9-9533-c045dee0eca1.png)
这种情况是偶尔出现，求问该如何解决。

**Comment by sangshuduo** [comment]
还有这个问题吗？我们新发布了 2.0 版本，请试用一下新版本
