### ISSUE TITLE
Cannot find taosdump after compiling and installation 

### ISSUE THREAD

**Issue by ziyunie** [taosdata/TDengine#3610]
编译安装成功后，进入usr/local/taos/bin/目录找不到taosdump文件
是需要单独安装吗？

**Comment by ziyunie** [comment]
![image](https://user-images.githubusercontent.com/22341897/93744606-b4c43080-fc24-11ea-89f5-0d4017e51eba.png)

**Comment by hzcheng** [comment]
taosdump在新的代码中已经移除了
