### ISSUE TITLE
use rmtaos to uninstall TDengine 2.0.3.0, recompile and install and failed to start the service

### ISSUE THREAD

**Issue by zzandyc** [taosdata/TDengine#3620]
![image](https://user-images.githubusercontent.com/6856676/93836553-be49a900-fcb5-11ea-892e-04817ca49c59.png)

**Comment by hzcheng** [comment]
您的运行环境是什么？

**Comment by zzandyc** [comment]
我是在虚拟机中运行的，虚拟机安装的是ubuntu20.04

**Comment by sangshuduo** [comment]
请提供一下完整的编译安装命令

**Comment by sangshuduo** [comment]
请提供一下完整的编译安装命令

**Comment by zzandyc** [comment]
![Uploading image.png…]()

**Comment by zzandyc** [comment]
![image](https://user-images.githubusercontent.com/6856676/93843405-476bda80-fccc-11ea-9181-d028e142910c.png)

**Comment by zzandyc** [comment]
make成功了：
![image](https://user-images.githubusercontent.com/6856676/93843615-032d0a00-fccd-11ea-9343-cc2f8186cb75.png)

make install失败：
![image](https://user-images.githubusercontent.com/6856676/93843655-2952aa00-fccd-11ea-8421-b2358df48cc0.png)

**Comment by zzandyc** [comment]
找到问题了，我将在windows下下载的源码，复制到虚拟机linux中，这样就会有问题，我在虚拟机中下载源码编译就没问题，应该是一些文件权限的问题。
