### ISSUE TITLE
how to use TDengine-client-2.0.3.1-Windows-x64.exe

### ISSUE THREAD

**Issue by find404** [taosdata/TDengine#3622]
**系统**
![image](https://user-images.githubusercontent.com/18007166/93841560-8c8d0e00-fcc6-11ea-859b-9657ca72c6e8.png)

**软件版本**
TDengine-client-2.0.3.1-Windows-x64.exe

**安装完成之后，无客户端可点**
![image](https://user-images.githubusercontent.com/18007166/93841599-a62e5580-fcc6-11ea-853b-8e5bf06a4b2c.png)

**Comment by sangshuduo** [comment]
@find404 你好，客户端需要在命令行中使用，可以用 cmd.exe 开一个命令行窗口，默认安装位置在 C:\\TDengine，然后执行 taos.exe -h \<服务器 FQDN:port>

**Comment by find404** [comment]
麻烦在问下，能接入navicat嘛？或者其他windows可视化的客户端？

**Comment by find404** [comment]
还有个问题，有PHP的开发连接器嘛？

**Comment by sangshuduo** [comment]
接入 navicat 和 php 连接器目前都还没有，如果有人愿意做我们可以提供支持。

**Comment by find404** [comment]
php 连接器我可以写一个，看了官网的，好像只有C有异步API，想接入到PHP中。

**Comment by sangshuduo** [comment]
欢迎

**Comment by find404** [comment]
其实还是PHP使用RESTful Connector，封装成对象哈，能不能有点详细的RESTful Connector的完整方法文档？比如异步API

**Comment by sangshuduo** [comment]
这种讨论我们挪到微信吧 :)
