### ISSUE TITLE
group+order时，order by 和 limit没生效

### ISSUE THREAD

**Issue by mxmkeep** [taosdata/TDengine#3623]
**Bug Description**
order by 和limit都没起作用
group by和count有统计出来
select remote_addr,count(*) as ss from http group by remote_addr order by ss desc limit 1000;
 221.192.180.155                |                     1 |
 221.192.180.177                |                   262 |
 221.192.180.252                |                    54 |
 221.210.180.254                |                   355 |
 221.229.166.191                |                   536 |
 221.229.204.132                |                   205 |
 222.174.234.158                |                   317 |
 222.186.180.132                |                   265 |
 222.216.160.142                |                   572 |
 222.217.136.203                |                   733 |
 222.217.237.143                |                   347 |
 222.217.246.213                |                  1876 |
 222.218.112.235                |                   849 |
 222.248.218.157                |                     4 |
 222.248.241.184                |                  1150 |
 223.104.103.148                |                     2 |
 223.104.178.234                |                    97 |
 223.104.182.192                |                     6 |
 223.104.193.153                |                    10 |
 223.104.213.238                |                     9 |
 223.104.246.229                |                     1 |
 223.104.255.164                |                    14 |
 223.150.112.195                |                   475 |
 223.155.208.116                |                    24 |
 223.166.151.233                |                    30 |
 223.166.151.234                |                    78 |
 223.166.151.235                |                    54 |
 223.166.151.237                |                    86 |
 223.167.152.124                |                   107 |
 223.167.152.125                |                    54 |
 223.213.112.145                |                  1717 |

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by hjxilinx** [comment]
如果需要对 group 分组后的结果进行输出的限制，需要使用 slimit ， soffset。limit/offset 是对分组内部的结果数量进行控制。
所以你的 SQL 应该写为：

```
select remote_addr,count(*) as ss from http group by remote_addr order by ss desc slimit 1000;
```
现在暂不支持按照 count 的结果进行排序。
