### ISSUE TITLE
包引用循环

### ISSUE THREAD

**Issue by lacezeng** [taosdata/TDengine#3625]
使用golang连接器访问TDengine集群时，提示包引用循环
![image](https://user-images.githubusercontent.com/71378259/93842629-2acea300-fcca-11ea-93b5-d89fffddb998.png)

代码如下:
![image](https://user-images.githubusercontent.com/71378259/93842739-75e8b600-fcca-11ea-8de0-155a3ccd0c68.png)

**Comment by localvar** [comment]
请您以文本形式贴一下代码。

**Comment by plum-lihui** [comment]
我将你截图显示的main.go的源码抄下来，编译了一下，没有问题，能够正常编译出执行文件。请确认一下目录下是不是只有main.go，没有其他go源文件了？

**Comment by lacezeng** [comment]
感谢～
下面是main.go目录及代码，taosSql是用的master分支
![image](https://user-images.githubusercontent.com/71378259/93958630-7ac06f00-fd89-11ea-85ad-f46439925248.png)
package main

import (
	"database/sql"
	_ "github.com/taosdata/driver-go/taosSql"
)

var (
	DRIVER_NAME    = "taosSql"
	user           = "root"
	password       = "taosdata"
	host           = "127.0.0.1"
	port           = 6030
	dbName         = "test"
	dataSourceName = fmt.Sprintf("%s:%s@/tcp(%s:%d)/%s?interpolateParams=true", user, password, host, port, dbName)
)

func main() {
	db, err := sql.Open(DRIVER_NAME, dataSourceName)
	if err != nil {
		return
	}

	_, err = db.Exec("create table tt002 (ts timestamp, name binary(10))")
	if err != nil {
		return
	}
}
