### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by whljava** [taosdata/TDengine#363]
x![image](https://user-images.githubusercontent.com/49359483/63085706-b67ee780-bf80-11e9-8d73-5a3da3e46ea9.png)
![image](https://user-images.githubusercontent.com/49359483/63085731-c5fe3080-bf80-11e9-86ab-2bee3ebea8b7.png)
电脑是64位的系统但是无法安装

**Comment by plum-lihui** [comment]
不好意思，发布的版本上传可能出了问题，请重新下载。
