### ISSUE TITLE
Failed to connect the Linux docker by Windows 10

### ISSUE THREAD

**Issue by liuyang77886** [taosdata/TDengine#3637]
TDengine服务在centos6.9的docker上。全是今天安装的。docker也是最新拉取的
docker：  docker run -d -v /etc/taos:/etc/taos -p 6030:6030 -p 6035:6035 -p 6041:6041 -p 6030-6040:6030-6040/udp tdengine/tdengine
在服务端运行taos
Welcome to the TDengine shell from Linux, Client Version:2.0.4.0
在客户端运行：C:\TDengine>taos -h 192.168.110.142
Welcome to the TDengine shell from Linux, Client Version:2.0.3.1
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.
taos connect failed, reason: Invalid client version.

java链接报错java.sql.SQLException: TDengine Error: Invalid client version
centos6.9的防火墙我是关闭了的
service iptables stop
iptables：将链设置为政策 ACCEPT：nat filter [确定]
iptables：清除防火墙规则：[确定]
iptables：正在卸载模块：[确定]
[root@cdh5 ~]# service iptables status
表格：filter
Chain INPUT (policy ACCEPT)
num  target     prot opt source               destination         
Chain FORWARD (policy ACCEPT)
num  target     prot opt source               destination         
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination   

windows日志taoslog.1：
==================================================
                new log file                      
==================================================
09/22 18:19:58.130000 0x000037a4 UTL ERROR taosMkDir not implemented yet
09/22 18:19:58.131000 0x000037a4 UTL all debug flag are set to 143
09/22 18:19:58.131000 0x000037a4 UTL localEp is: 192.168.110.142:6030
09/22 18:19:58.131000 0x000037a4 UTL    taos config & system info:
09/22 18:19:58.131000 0x000037a4 UTL ==================================
09/22 18:19:58.131000 0x000037a4 UTL  firstEp:                192.168.110.142:6030 
09/22 18:19:58.131000 0x000037a4 UTL  secondEp:               192.168.110.142:6030 
09/22 18:19:58.131000 0x000037a4 UTL  fqdn:                   192.168.110.142 
09/22 18:19:58.131000 0x000037a4 UTL  serverPort:             6030 
09/22 18:19:58.131000 0x000037a4 UTL  configDir:              C:/TDengine/cfg 
09/22 18:19:58.131000 0x000037a4 UTL  logDir:                 C:/TDengine/log 
09/22 18:19:58.131000 0x000037a4 UTL  scriptDir:              C:/TDengine/script 
09/22 18:19:58.131000 0x000037a4 UTL  arbitrator:              
09/22 18:19:58.131000 0x000037a4 UTL  numOfThreadsPerCore:    0.000000 
09/22 18:19:58.131000 0x000037a4 UTL  rpcTimer:               1000(ms)
09/22 18:19:58.131000 0x000037a4 UTL  rpcMaxTime:             600(s)
09/22 18:19:58.131000 0x000037a4 UTL  shellActivityTimer:     3(s)
09/22 18:19:58.131000 0x000037a4 UTL  tableMetaKeepTimer:     7200(s)
09/22 18:19:58.131000 0x000037a4 UTL  compressMsgSize:        -1 
09/22 18:19:58.131000 0x000037a4 UTL  maxSQLLength:           65480(byte)
09/22 18:19:58.131000 0x000037a4 UTL  maxNumOfOrderedRes:     100000 
09/22 18:19:58.131000 0x000037a4 UTL  timezone:               (UTC, +0800) 
09/22 18:19:58.131000 0x000037a4 UTL  locale:                 Chinese (Simplified)_China.936 
09/22 18:19:58.131000 0x000037a4 UTL  charset:                UTF-8 
09/22 18:19:58.131000 0x000037a4 UTL  numOfLogLines:          10000000 
09/22 18:19:58.131000 0x000037a4 UTL  asyncLog:               1 
09/22 18:19:58.131000 0x000037a4 UTL  debugFlag:              143 
09/22 18:19:58.131000 0x000037a4 UTL  rpcDebugFlag:           143 
09/22 18:19:58.131000 0x000037a4 UTL  tmrDebugFlag:           131 
09/22 18:19:58.131000 0x000037a4 UTL  cDebugFlag:             143 
09/22 18:19:58.131000 0x000037a4 UTL  jniDebugFlag:           143 
09/22 18:19:58.131000 0x000037a4 UTL  odbcDebugFlag:          143 
09/22 18:19:58.131000 0x000037a4 UTL  uDebugFlag:             143 
09/22 18:19:58.131000 0x000037a4 UTL  qDebugFlag:             143 
09/22 18:19:58.131000 0x000037a4 UTL  tsdbDebugFlag:          143 
09/22 18:19:58.131000 0x000037a4 UTL  gitinfo:                community 
09/22 18:19:58.131000 0x000037a4 UTL  gitinfoOfInternal:      internal 
09/22 18:19:58.131000 0x000037a4 UTL  buildinfo:              Built at 2020-09-11 17:51:51 
09/22 18:19:58.131000 0x000037a4 UTL  version:                2.0.3.1 
09/22 18:19:58.131000 0x000037a4 UTL  maxBinaryDisplayWidth:  30 
09/22 18:19:58.131000 0x000037a4 TSC starting to initialize TAOS client ...
09/22 18:19:58.131000 0x000037a4 TSC Local End Point is:192.168.110.142:6030
09/22 18:19:58.131000 0x000037a4 UTL tsc scheduler is initialized, numOfThreads:2
09/22 18:19:58.131000 0x000037a4 UTL tmr scheduler is initialized, numOfThreads:1
09/22 18:19:58.132000 0x000037a4 TSC client is initialized successfully
09/22 18:19:58.132000 0x000037a4 UTL pool:000000003A9C2310 is setup, maxId:5000
09/22 18:19:58.132000 0x000037a4 RPC TSC TCP client is initialized, ip:0:0
09/22 18:19:58.132000 0x000037a4 UTL open udp socket:0x0:0
09/22 18:19:58.134000 0x000037a4 RPC TSC UDP connection is initialized, ip:0:0 threads:1
09/22 18:19:58.134000 0x000037a4 RPC TSC rpc is openned, threads:1 sessions:5000
09/22 18:19:58.134000 0x000037a4 TSC dnodeConn:0000000000F81360 is created, user:root
09/22 18:19:58.134000 0x000037a4 TSC 00000000010710E0 SQL cmd:connect will be processed, name:(null), type:0
09/22 18:19:58.134000 0x000037a4 RPC malloc mem: 000000003AA5B9E0
09/22 18:19:58.134000 0x000037a4 RPC TSC 000000003AF6A1B8 client connection is allocated, uid:0x3af76f81
09/22 18:19:58.134000 0x000037a4 RPC TSC UDP connection is setup, ip:8e6ea8c0:6030 localPort:55314
09/22 18:19:58.134000 0x00004a7c RPC TSC UDP thread is created, index:0
09/22 18:19:58.134000 0x000037a4 RPC TSC 000000003AF6A1B8 00000000010710E0, connect is sent to 192.168.110.142:6030, len:345 sig:0x01000000:0x00000000:27782
09/22 18:19:58.135000 0x00004a7c RPC UDP malloc mem: 000000003AA5BE30
09/22 18:19:58.135000 0x00004a7c RPC TSC 000000003AF6A1B8 00000000010710E0, connect-rsp received from 0x8e6ea8c0:6030, parse code:0x0 len:84 sig:0x27000000:0x01000000:27782 code:0x80000204
09/22 18:19:58.135000 0x00004a7c TSC 00000000010710E0 SQL cmd:connect, code:Invalid client version rspLen:0
09/22 18:19:58.135000 0x00004a7c RPC free mem: 000000003AA5BE30
09/22 18:19:58.135000 0x00004a7c RPC free mem: 000000003AA5B9E0
09/22 18:19:58.135000 0x000037a4 TSC 00000000010710E0 start to free sql object
09/22 18:19:58.135000 0x000037a4 TSC 00000000010710E0 start to free local reducer
09/22 18:19:58.135000 0x000037a4 TSC 00000000010710E0 local reducer has been freed, abort
09/22 18:19:58.135000 0x000037a4 TSC 00000000010710E0 SqlObj is freed by app, qhandle is null
09/22 18:19:58.135000 0x000037a4 RPC TSC TCP client is stopped
09/22 18:19:58.135000 0x00004a7c RPC TSC UDP socket was closed, exiting(No error)
09/22 18:19:58.136000 0x000037a4 RPC TSC UDP is stopped
09/22 18:19:58.136000 0x000037a4 RPC TSC 000000003AF6A1B8 00000000010710E0, rpc connection is released
09/22 18:19:58.136000 0x000037a4 RPC ERROR TSC, failed to create eventfd(File exists)
09/22 18:19:58.232000 0x00006d38 RPC TSC TCP thread get stop event, exiting...
09/22 18:19:58.232000 0x000037a4 RPC TSC TCP client is cleaned up
09/22 18:19:58.232000 0x000037a4 RPC TSC UDP is cleaned up
09/22 18:19:58.232000 0x000037a4 RPC TSC rpc is closed
09/22 18:19:58.232000 0x000037a4 UTL pool:000000003A9C2310 is cleaned
09/22 18:19:58.233000 0x000037a4 RPC TSC rpc resources are released
09/22 18:19:58.233000 0x000037a4 TSC 0000000000F8E050 DB connection is closed, dnodeConn:0000000000F81360
09/22 18:19:58.233000 0x000037a4 JNI ERROR jobj:00000000031DEDF8, conn:0000000000000000, connect to database failed, host=192.168.110.142, user=root, dbname=dbtest, port=6030
09/22 18:19:58.234000 0x000037a4 JNI ERROR jobj:00000000031DED78, connection is closed

**Comment by liuyang77886** [comment]
win10的配置文件：
 firstEp               192.168.110.142:6030 
  fqdn                  192.168.110.142
serverPort            6030
 logDir                C:/TDengine/log

服务端的配置文件没有，提示采用的默认配置

**Comment by liuyang77886** [comment]
centos6上执行netstat -tlnp|grep 60
tcp        0      0 :::6035                     :::*                        LISTEN      8664/docker-proxy   
tcp        0      0 :::6041                     :::*                        LISTEN      8576/docker-proxy   
tcp        0      0 :::6030                     :::*                        LISTEN      8707/docker-proxy

**Comment by ZhangJiaLei123** [comment]
我也遇到了同样的情况,运行demo中的java,c,c#的代码,都失败了.其中c#的运行结果,提示连接成功,但是数据库查看并没有创建成功.
c#测试控制台输出如下:
```  bat
---------------------------------------------------------------
Starting Testing...
---------------------------------------------------------------
连接到TDengine成功
create database if not exists db 成功
use db 成功
create table if not exists st(ts timestamp, v1 bool, v2 tinyint, v3 smallint, v4 int, v5 bigint, v6 float, v7 double, v8 binary(10), v9 nchar(10)) tags(t1 int) 成功
create table if not exists t0 using st tags(0) 成功
create table if not exists t1 using st tags(1) 成功
create table if not exists t2 using st tags(2) 成功
create table if not exists t3 using st tags(3) 成功
create table if not exists t4 using st tags(4) 成功
create table if not exists t5 using st tags(5) 成功
create table if not exists t6 using st tags(6) 成功
create table if not exists t7 using st tags(7) 成功
create table if not exists t8 using st tags(8) 成功
create table if not exists t9 using st tags(9) 成功
成功创建数据库和表
总计 0 行插入, 100000 行失败, 消耗时间: 0 秒.
select * from db.t0
field count: 0
查询不完整, Error -2147483637总计 0 行插入, 0行查询, 消耗时间: 0 秒.
---------------------------------------------------------------
Stop Testing...
---------------------------------------------------------------
```

**Comment by liuyq-617** [comment]
@liuyang77886 现在来看，您的客户端和服务端版本不一致，导致连接不上

**Comment by liuyq-617** [comment]
@ZhangJiaLei123 您的问题和这个不一样，提一个新的issue吧

**Comment by liuyang77886** [comment]
客户端的版本，我也是拿的最新的啊，  都是从官网拿的。  就算版本不一致，也不应该出这样的问题吧

**Comment by liuyang77886** [comment]
我这里，公司还购买了集群的商业版，    有没有人能帮忙解决啊，网上查资料，资料都查不到。

**Comment by liuyq-617** [comment]
>taos connect failed, reason: Invalid client version.

这个报错就是说您的客户端和服务端版本不一致，您服务端是2.0.4.0，客户端是2.0.3.1
您再到官网去下载，客户端和服务端要求版本号一致

**Comment by liuyq-617** [comment]
> 我这里，公司还购买了集群的商业版， 有没有人能帮忙解决啊，网上查资料，资料都查不到。

您是哪家公司的啊，我们企业版都有单独微信群，你可以直接到群里提问
