### ISSUE TITLE
where  and or 出错

### ISSUE THREAD

**Issue by wsf1990** [taosdata/TDengine#364]
![image](https://user-images.githubusercontent.com/8774884/63086018-81bf6000-bf81-11e9-9f2c-fb1384190cdc.png)

如图，执行 单个条件显示34条，执行and显示1条，执行or同样是一条，是否BUG？

**Comment by hjxilinx** [comment]
不同列之间的查询条件不支持 or ，所有的 or 系统自动默认为 and 但是并不给出提示。后续版本会支持or的操作。
