### ISSUE TITLE
Issues about cluster efficiency

### ISSUE THREAD

**Issue by moziie** [taosdata/TDengine#3640]
### 操作：d1为master，本地windows客户端使用taos -h d1连接，测试执行查询语句效率
![4](https://user-images.githubusercontent.com/70946068/93954579-983d0b00-fd80-11ea-857d-918e276bf163.jpg)
查询很快基本在0.3s以内，然后我停掉了d1，按文档中所说客户端会自动连接到新的master，然后我再次执行查询语句；
停掉d1(就是图中VM-0-3-centos)
![2](https://user-images.githubusercontent.com/70946068/93954893-21ecd880-fd81-11ea-8ea4-835b3e2ab6c1.jpg)
执行查询语句结果
![3](https://user-images.githubusercontent.com/70946068/93954906-2f09c780-fd81-11ea-8609-96f18d51c53d.jpg)
查询时间基本在4s以上，意味着效率严重下滑(这里没有测试插入语句效率)
请问我这种情况正常吗，如若不应该出现此现象请问如何排查问题如何调试
客户端日志
[taoslog.zip](https://github.com/taosdata/TDengine/files/5265026/taoslog.zip)

**Comment by yihaoDeng** [comment]
你可以多测试几次， 查询是不是刚开始比较缓慢， 之后就回复正常了（0.3）, 插入同理， 还有， 你附的图片我打不开， 你可以贴文本

**Comment by moziie** [comment]
嗯好我再继续测试一下

**Comment by Aries-Lee1991** [comment]
@moziie 您试了之后还有问题吗？

**Comment by moziie** [comment]
> @moziie 您试了之后还有问题吗？

又尝试了一下，增加查询次数到50次，响应的时间还是很慢，前后没有变化，然后过了半个小时再次测试查询依旧很慢
测试语句select count(*) from smeters;
select count(*) from db0001;
select max(volatagea) from smeters;
select max(volatagea) from db0001;

**Comment by moziie** [comment]
测试场景，后台跑插入语句的同时，windos客户端连接到d1(VM-0-3-centos)，测试查询时间，
sql:select count(*) from smeters;和 select avg(voltagea), max(activeenergy), min(powerfactorb) from smeters;
配置截图
![1](https://user-images.githubusercontent.com/70946068/94335018-f67d1e80-000a-11eb-9e00-02373eefef78.png)
数据量在450w+，两条sql查询结果在1.2s左右,单条sql分别测试5~6次，隔10分钟跑一次，跑三次单条sql总测试15次+
其中一次查询结果截图:
![2](https://user-images.githubusercontent.com/70946068/94335007-e402e500-000a-11eb-83b1-2f7efa9eeae0.png)
![3](https://user-images.githubusercontent.com/70946068/94335012-e8c79900-000a-11eb-88a3-605f1be89ea3.png)
停掉d1(VM-0-3-centos),重复之前测试流程，
配置截图
![1-1](https://user-images.githubusercontent.com/70946068/94335038-1876a100-000b-11eb-911c-71f97d8560ec.png)
其中一次查询结果截图：
![2-2](https://user-images.githubusercontent.com/70946068/94335044-2c220780-000b-11eb-8ff9-5deda9715836.png)
![3-3](https://user-images.githubusercontent.com/70946068/94335046-2f1cf800-000b-11eb-92a9-9562bf8d791d.png)
可以看到响应结果时间均在6s左右，请问我应该调整那里的参数来使之效率提高呢
最后附上客户端日志,debugflag135
[taoslog.zip](https://github.com/taosdata/TDengine/files/5286319/taoslog.zip)
期待大佬回复^_^

**Comment by wy-w** [comment]
![9cea9647efbb4d06823eb6f2c9ec023c](https://user-images.githubusercontent.com/55778678/94335957-d56bfc00-0011-11eb-970a-7c496c7b1607.jpg)
