### ISSUE TITLE
When show tables, query interrupted (Data expired), 22700 row(s) in set (7.320644s)

### ISSUE THREAD

**Issue by malinco** [taosdata/TDengine#3649]
Bug Description
执行Show tables时发生中断，Query interrupted (Data expired), 22700 row(s) in set (7.320644s)

To Reproduce
1.前置条件：
预先生成100000张表，并在每个表里插入1W条数据；
2.执行taos命令
3. 执行show tables;
4. 出现执行中断

Expected Behavior
Query interrupted (Data expired), 22700 row(s) in set (7.320644s)

Screenshots

Environment (please complete the following information):

OS: Ubuntu 16.04 server
16GB, i5 8600 3.10GHZ, 1T SSD
TDengine Version [ 2.0.3.1]
Additional Context
无

**Comment by hjxilinx** [comment]
是 show 操作的时候，需要同步刷屏。管理节点设置了最大的句柄保留时间是6秒，超过6秒后会自动释放句柄。
这个问题我们在下一个版本会修复该问题。避免这个问题的方式是可以将结果从定向到文件。

**Comment by fenghua1997** [comment]
TDengine 经过一年多的努力后，解决了不少 bug ，已经有了更稳定的版本，欢迎更新使用。
