### ISSUE TITLE
taosdemo 运行错误 “reason: failed to connect to server”

### ISSUE THREAD

**Issue by dermarr** [taosdata/TDengine#365]
用 taosdemo 测试，为了模拟大量建表的情况，修改taosdemo建库命令如下：
```
# diff taosdemo.c.orig taosdemo.c
375c375
<   sprintf(command, "create database %s;", db_name);
---
>   sprintf(command, "create database %s tables 10000;", db_name);
```

然后运行 taosdemo 命令如下：
`# ./taosdemo -t 1800000 -n 300 -r 300 -l 3 -b INT -c 10`

insert数据错误如下：
```
Creating meters super table...
meters created!
Creating 180000 table(s)......
Table(s) created!
Inserting data......
Failed to run insert into test.t52298 values (1500000000000, 2, 0, 5) (1500000000001, 0, 3, 6)...
reason: failed to connect to server
```

**Comment by johnnyhou327** [comment]
@dermarr 您测试机器的硬件配置怎样的

**Comment by dermarr** [comment]
@johnnyhou327 
CPU:     E5-2682  2 core
MEM:    4GB
HD:       40GB

Thanks!

**Comment by fangpanpan** [comment]
> @johnnyhou327
> CPU: E5-2682 2 core
> MEM: 4GB
> HD: 40GB
> 
> Thanks!

according to your CPU cores, if you didn't change default configuration /etc/taos/taos/cfg. The max number of tables you can create is 49000. (1000 tables per vnode, totally 50vnodes with on vnode used).

**Comment by dermarr** [comment]
@fangpanpan 

hi, 谢谢回复，
我修改了taosdemo代码，用“create database test tables 10000;”建的表（从其它issue解答中看到的办法），没有修改其它地方，
```
# diff taosdemo.c.orig taosdemo.c
375c375
<   sprintf(command, "create database %s;", db_name);
---
>   sprintf(command, "create database %s tables 10000;", db_name);
```

看起来表是建立成功的，如下
![image](https://user-images.githubusercontent.com/31396739/63151113-4ed9a280-c03b-11e9-957b-bbd0d24bd311.png)

问题发生在写入数据的时候

**Comment by fangpanpan** [comment]
您能看看taosd是否还在运行? (ps aux |grep taosd).  以及您能看看您磁盘还有空间吗？用默认值的话会生成十几个g的数据，不清楚您已经写了多少数据了。

**Comment by dermarr** [comment]
问题发生的时候taosd在运行， 当时看磁盘有空间。
之前发生过磁盘没空间时的错误信息是 “reason: commit log init failed”

有几个现象，
1. 问题在我的环境必现
2.  如果表的数量少一些，比如10000个表，不会发生错误
3. 增加metric列数好像会更容易触发问题，即更少的表就可以触发问题
4. 问题发生后，drop database，表删除的非常缓慢，一秒几百个表这种速度，不知道正常应该是多少。
5. 当drop database完成后，磁盘空间反而没有了，此时用du 看应该还有很多空间（/var/lib/taos 128MB，/var/log/taos 256MB），df看没空间。重启taosd，磁盘空间恢复。

**Comment by fangpanpan** [comment]
请问您用的是最新版的1.6.1.6tdengine吗？而且按您修改的参数，1个vnode建1万张表，您也只能建49万张表。 如果除了“failed to connect to server”之外没有别的错误信息了，那只能打开日志（debugflag=135)，清空/var/lib 和/var/log下的东西，重新跑一趟看看是什么错误了。

**Comment by dermarr** [comment]
version 1.6.1.5
建了18万表
没看到别的错误信息

似乎是因为内存不够的原因，把 cache/rows/tblock/ablock改到最小，跑成功了。

我再改回去试试

**Comment by dermarr** [comment]
应该是内存不足相关，但是没找到错误log，下面是最后能看到 insert record 的地方

![image](https://user-images.githubusercontent.com/31396739/63157456-96672b00-c049-11e9-8e7d-70992fe9af14.png)

问题出现后会丢磁盘空间，重启taosd才能恢复
