### ISSUE TITLE
Run the C# demo, the log prompts success, but looking at the server database, it is not successfully written

### ISSUE THREAD

**Issue by ZhangJiaLei123** [taosdata/TDengine#3650]
环境配置:
```
Server: TDengine-server-2.0.4.0-Linux-x64
Windows10: TDengine-client-2.0.4.0-Windows-x64
```
服务器（防火墙已关闭）数据库类表如下：
```
taos> show databases;
              name              |      created_time       |   ntables   |   vgroups   | replica | quorum |  days  |    keep1,keep2,keep(D)     |  cache(MB)  |   blocks    |   minrows   |   maxrows   | wallevel |    fsync    | comp | precision |    status    |
===================================================================================================================================================================================================================================================================
 log                            | 2020-09-22 14:27:21.173 |           4 |           1 |       1 |      1 |     10 | 30,30,30                   |           1 |           3 |         100 |        4096 |        1 |        3000 |    2 | us        | ready        |
 farm_iot                       | 2020-09-22 16:51:33.728 |           1 |           1 |       1 |      1 |      2 | 3650,3650,3650             |          16 |           6 |         100 |        4096 |        1 |        3000 |    2 | ms        | ready        |
 db                             | 2020-09-23 09:54:28.496 |           2 |           1 |       1 |      1 |      2 | 3650,3650,3650             |          16 |           6 |         100 |        4096 |        1 |        3000 |    2 | ms        | ready        |
Query OK, 3 row(s) in set (0.000821s)
```
运行官方的examples中的C#结果如下:
经检查,数据库中的表,并没有成功创建.
``` 
---------------------------------------------------------------
Starting Testing...
---------------------------------------------------------------
连接到TDengine成功
create database if not exists db 成功
use db 成功
create table if not exists st(ts timestamp, v1 bool, v2 tinyint, v3 smallint, v4 int, v5 bigint, v6 float, v7 double, v8 binary(10), v9 nchar(10)) tags(t1 int) 成功
create table if not exists t0 using st tags(0) 成功
create table if not exists t1 using st tags(1) 成功
create table if not exists t2 using st tags(2) 成功
create table if not exists t3 using st tags(3) 成功
create table if not exists t4 using st tags(4) 成功
create table if not exists t5 using st tags(5) 成功
create table if not exists t6 using st tags(6) 成功
create table if not exists t7 using st tags(7) 成功
create table if not exists t8 using st tags(8) 成功
create table if not exists t9 using st tags(9) 成功
成功创建数据库和表
总计 0 行插入, 100000 行失败, 消耗时间: 0 秒.
select * from db.t0
field count: 0
查询不完整, Error -2147483637总计 0 行插入, 0行查询, 消耗时间: 0 秒.
---------------------------------------------------------------
Stop Testing...
---------------------------------------------------------------
```
执行后,服务器检查:
> 其中的t1和t0是我自己手动添加的。
```
taos> show tables;
           table_name           |      created_time       | columns |          stable_name           |
======================================================================================================
 t1                             | 2020-09-23 09:55:57.682 |      10 | st                             |
 t0                             | 2020-09-23 09:55:45.880 |      10 | st                             |
Query OK, 2 row(s) in set (0.000965s)

```
 

> 对部分控制台输出做了汉化,

**Comment by No54** [comment]
2.0版本的connector是不是还没有C#的支持？

**Comment by Aries-Lee1991** [comment]
> 2.0版本的connector是不是还没有C#的支持？

是的，2.0版本暂时还不支持C#。

**Comment by Aries-Lee1991** [comment]
> 环境配置:
> 
> ```
> Server: TDengine-server-2.0.4.0-Linux-x64
> Windows10: TDengine-client-2.0.4.0-Windows-x64
> ```
> 
> 服务器（防火墙已关闭）数据库类表如下：
> 
> ```
> taos> show databases;
>               name              |      created_time       |   ntables   |   vgroups   | replica | quorum |  days  |    keep1,keep2,keep(D)     |  cache(MB)  |   blocks    |   minrows   |   maxrows   | wallevel |    fsync    | comp | precision |    status    |
> ===================================================================================================================================================================================================================================================================
>  log                            | 2020-09-22 14:27:21.173 |           4 |           1 |       1 |      1 |     10 | 30,30,30                   |           1 |           3 |         100 |        4096 |        1 |        3000 |    2 | us        | ready        |
>  farm_iot                       | 2020-09-22 16:51:33.728 |           1 |           1 |       1 |      1 |      2 | 3650,3650,3650             |          16 |           6 |         100 |        4096 |        1 |        3000 |    2 | ms        | ready        |
>  db                             | 2020-09-23 09:54:28.496 |           2 |           1 |       1 |      1 |      2 | 3650,3650,3650             |          16 |           6 |         100 |        4096 |        1 |        3000 |    2 | ms        | ready        |
> Query OK, 3 row(s) in set (0.000821s)
> ```
> 
> 运行官方的examples中的C#结果如下:
> 经检查,数据库中的表,并没有成功创建.
> 
> ```
> ---------------------------------------------------------------
> Starting Testing...
> ---------------------------------------------------------------
> 连接到TDengine成功
> create database if not exists db 成功
> use db 成功
> create table if not exists st(ts timestamp, v1 bool, v2 tinyint, v3 smallint, v4 int, v5 bigint, v6 float, v7 double, v8 binary(10), v9 nchar(10)) tags(t1 int) 成功
> create table if not exists t0 using st tags(0) 成功
> create table if not exists t1 using st tags(1) 成功
> create table if not exists t2 using st tags(2) 成功
> create table if not exists t3 using st tags(3) 成功
> create table if not exists t4 using st tags(4) 成功
> create table if not exists t5 using st tags(5) 成功
> create table if not exists t6 using st tags(6) 成功
> create table if not exists t7 using st tags(7) 成功
> create table if not exists t8 using st tags(8) 成功
> create table if not exists t9 using st tags(9) 成功
> 成功创建数据库和表
> 总计 0 行插入, 100000 行失败, 消耗时间: 0 秒.
> select * from db.t0
> field count: 0
> 查询不完整, Error -2147483637总计 0 行插入, 0行查询, 消耗时间: 0 秒.
> ---------------------------------------------------------------
> Stop Testing...
> ---------------------------------------------------------------
> ```
> 
> 执行后,服务器检查:
> 
> > 其中的t1和t0是我自己手动添加的。
> 
> ```
> taos> show tables;
>            table_name           |      created_time       | columns |          stable_name           |
> ======================================================================================================
>  t1                             | 2020-09-23 09:55:57.682 |      10 | st                             |
>  t0                             | 2020-09-23 09:55:45.880 |      10 | st                             |
> Query OK, 2 row(s) in set (0.000965s)
> ```
> 
> > 对部分控制台输出做了汉化,

2.0 暂时还不支持 C#
