### ISSUE TITLE
How to know that the inserted data is discarded due to duplicate timestamps

### ISSUE THREAD

**Issue by mxmkeep** [taosdata/TDengine#3652]
请问如何知道因插入时间戳重复而被丢弃的数据量？
测试并且查看日志没找到相关信息

**Comment by yihaoDeng** [comment]
这个没有办法知道，之后我们会发布更新功能， 插入重复时间戳会直接更新的

**Comment by mxmkeep** [comment]
> 这个没有办法知道，之后我们会发布更新功能， 插入重复时间戳会直接更新的

好的，谢谢
但还是希望在日志里能够体现出来，这样就能统计有多少数据被丢弃，我们好调整入库逻辑
