### ISSUE TITLE
Compile failure in Linux

### ISSUE THREAD

**Issue by lacezeng** [taosdata/TDengine#3653]
在Linux环境下静态编译go代码失败，如图:
![image](https://user-images.githubusercontent.com/71378259/94014353-fd731980-fddd-11ea-8386-020856b09beb.png)
直接用go build编译没有问题，如图:
![image](https://user-images.githubusercontent.com/71378259/94014426-17146100-fdde-11ea-8650-ff5850790d2c.png)

**Comment by sangshuduo** [comment]
应该是因为用了 cgo ，所以不能 CGO\_ENABLED=0

**Comment by sangshuduo** [comment]
应该是因为用了 cgo ，所以不能 CGO\_ENABLED=0

**Comment by lacezeng** [comment]
thanks～
