### ISSUE TITLE
How to create accounts to restrict the permissions of different users?

### ISSUE THREAD

**Issue by lacezeng** [taosdata/TDengine#3654]
希望可以通过不同的account来控制权限，在文档中只找到创建用户的方法，但是创建出来的用户权限是全局的，如图:
![image](https://user-images.githubusercontent.com/71378259/94014877-ba657600-fdde-11ea-9105-07ee1fa8046b.png)

**Comment by plum-lihui** [comment]
account只有企业版才有，支持分账户控制权限，社区版是没有。
