### ISSUE TITLE
The number of records finally inserted by taosdemo is wrong

### ISSUE THREAD

**Issue by malinco** [taosdata/TDengine#3655]
**Bug Description**
taosdemo工具最终插入记录数目不对

**To Reproduce**
1. 执行taosdemo -n 100000
2. 等待将近1个小时
3. 如下：
###################################################################
# Server IP:                         localhost:0
# User:                              root
# Password:                          taosdata
# Use metric:                        true
# Datatype of Columns:               int int int int int int int float 
# Binary Length(If applicable):      -1
# Number of Columns per record:      3
# Number of Threads:                 10
# Number of Tables:                  100000
# Number of Data per Table:          100000
# Records/Request:                   1000
# Database name:                     test_01
# Table prefix:                      t
# Delete method:                     0
# Test time:                         2020-09-23 16:42:53
###################################################################

Press enter key to continue
Creating meters super table...
meters created!
create table......
Creating table from 0 to 9999
Creating table from 10000 to 19999
Creating table from 20000 to 29999
Creating table from 30000 to 39999
Creating table from 40000 to 49999
Creating table from 50000 to 59999
Creating table from 60000 to 69999
Creating table from 70000 to 79999
Creating table from 80000 to 89999
Creating table from 90000 to 99999
Spent 81.6716 seconds to create 100000 tables with 10 connections
Inserting data......
SYNC Insert with 10 connections:
Spent 3465.1017 seconds to insert 1410065408 records with 1000 record(s) per request: 406933.34 records/second

**Expected Behavior**
正确插入10,000,000,000条数据

**Screenshots**

**Environment (please complete the following information):**
OS: Ubuntu 16.04 server
16GB, i5 8600 3.10GHZ, 1T SSD
TDengine Version [ 2.0.3.1]

**Additional Context**

**Comment by liuyq-617** [comment]
1. 我针对2.0.3.1版本带的taosdemo进行了测试，测试成功，未复现出您说的情况

2. 您的命令参数和您发送的日志不太对应，不用-t 参数，表数量默认是10000
3. 麻烦提供一下数据库的日志，我们进一步来判断一下问题

**Comment by Aries-Lee1991** [comment]
> 1. 我针对2.0.3.1版本带的taosdemo进行了测试，测试成功，未复现出您说的情况
> 2. 您的命令参数和您发送的日志不太对应，不用-t 参数，表数量默认是10000
> 3. 麻烦提供一下数据库的日志，我们进一步来判断一下问题

@malinco

**Comment by malinco** [comment]
@Aries-Lee1991 我使用设置的表数量是100,000，不是默认的10,000，我这里是必现啊。还会出现负数呢
root@SH-11F3-A20-0402:/usr/local/taos/examples/python# taosdemo -d i50w10w -t 500000 -n 100000    
###################################################################
# Server IP:                         localhost:0
# User:                              root
# Password:                          taosdata
# Use metric:                        true
# Datatype of Columns:               int int int int int int int float 
# Binary Length(If applicable):      -1
# Number of Columns per record:      3
# Number of Threads:                 10
# Number of Tables:                  500000
# Number of Data per Table:          100000
# Records/Request:                   1000
# Database name:                     i50w10w
# Table prefix:                      t
# Delete method:                     0
# Test time:                         2020-09-25 10:20:20
###################################################################

Press enter key to continue
Creating meters super table...
meters created!
create table......
Creating table from 0 to 49999
Creating table from 50000 to 99999
Creating table from 100000 to 149999
Creating table from 150000 to 199999
Creating table from 200000 to 249999
Creating table from 250000 to 299999
Creating table from 300000 to 349999
Creating table from 350000 to 399999
Creating table from 400000 to 449999
Creating table from 450000 to 499999
Spent 655.2909 seconds to create 500000 tables with 10 connections
Inserting data......
SYNC Insert with 10 connections:
Spent 37678.9015 seconds to insert -1539607552 records with 1000 record(s) per request: -40861.26 records/second

**Comment by plum-lihui** [comment]
这个负数应该是使用的变量不对，溢出了导致的问题。这个我们修正一下。
