### ISSUE TITLE
after ALTER USER root PASS ，can not exec Taos ,taos connect failed, reason: Authentication failure

### ISSUE THREAD

**Issue by umanan** [taosdata/TDengine#3661]
**Bug Description**
after ALTER USER root PASS ，can not exec Taos ,

**To Reproduce**
1. Go to 'taos'
2. Type in 'ALTER USER root PASS 'iquerY_89';'
3. exit
4.taos, taos connect failed, reason: Authentication failure

**Screenshots**

**Environment (please complete the following information):**
 - OS: CentOS Linux release 7.8.2003 (Core)
 - Memory：available：1326, CPU 0%，, current Disk Space：Avail： 36G
 - TDengine Version [2.0.0.1]

**Additional [Context**](url)

**Comment by sangshuduo** [comment]
you need run "taos -u root -p" then input the new password to enter the shell prompt.
