### ISSUE TITLE
 The csv exported from version 1.6.5 cannot be imported into version 2.0.4

### ISSUE THREAD

**Issue by w858269620** [taosdata/TDengine#3662]
**Bug Description**
从1.6.5版本导出的csv无法导入2.0.4版本

**To Reproduce**
1、超级表语句
create table if not exists combinerbox (ts timestamp,P2M1 float,P2M2 float,P2M3 float,P2M4 float,P2M5 float,P2M6 float,P2M7 float,P2M8 float,P2M9 float,P2M10 float,P2M11 float,P2M12 float,P2M13 float,P2M14 float,P2M15 float,P2M16 float,P2M17 float,P2M18 float,P2M19 float,P2M20 float,P2M21 float,P2M22 float,P2M23 float,P2M24 float,P2M25 float,P2M26 float,P2M27 float,P2M28 float,P2M29 float,P2M30 float,P2M31 float,P2M32 float,P2M33 float,P2M34 float,P2M35 float,P2M36 int,P2M37 int,P2M38 int,P2M39 int,P2M40 int,P2M41 int,P2M42 int,P2M43 int,P2M44 int,P2M45 int,P2M46 int,P2M47 int,P2M48 int,P2M49 int,P2M50 int,P2M51 int,P2M52 int,P2M53 int,P2M54 int,P2M55 int,P2M56 int,P2M57 int,P2M58 int,P2M59 int,P2M60 int,P2M61 int,P2M62 int,P2M63 int,P2M64 int,P2M65 int,P2M66 int,P2M67 int,P2M68 int,P2M69 int,P2M70 int,P2M71 int,P2M72 int,P2M73 int,P2M74 int,P2M75 int,P2M76 int,P2M77 int,P2M78 int,P2M79 int,P2M80 int,P2M81 int,P2M82 int,P2M83 int,P2M84 int,P2M85 int,P2M86 int,P2M87 int,P2M88 int,P2M89 int,P2M90 int,P2M91 int,P2M92 int,P2M93 int) tags (projectSn binary(32),gatewaySn binary(32),deviceAddress int);

2、子表语句
create table t1m1msl1115060829m2m8 using combinerbox tags ('SL1115060829','2',8);

3、csv文件内容（部分）
ts,p2m1,p2m2,p2m3,p2m4,p2m5,p2m6,p2m7,p2m8,p2m9,p2m10,p2m11,p2m12,p2m13,p2m14,p2m15,p2m16,p2m17,p2m18,p2m19,p2m20,p2m21,p2m22,p2m23,p2m24,p2m25,p2m26,p2m27,p2m28,p2m29,p2m30,p2m31,p2m32,p2m33,p2m34,p2m35,p2m36,p2m37,p2m38,p2m39,p2m40,p2m41,p2m42,p2m43,p2m44,p2m45,p2m46,p2m47,p2m48,p2m49,p2m50,p2m51,p2m52,p2m53,p2m54,p2m55,p2m56,p2m57,p2m58,p2m59,p2m60,p2m61,p2m62,p2m63,p2m64,p2m65,p2m66,p2m67,p2m68,p2m69,p2m70,p2m71,p2m72,p2m73,p2m74,p2m75,p2m76,p2m77,p2m78,p2m79,p2m80,p2m81,p2m82,p2m83,p2m84,p2m85,p2m86,p2m87,p2m88,p2m89,p2m90,p2m91,p2m92,p2m93
'2018-12-18 13:11:11.000',NULL,619.77002,2.89000,2.74000,2.77000,3.30000,3.52000,3.95000,3.33000,2.96000,2.77000,2.80000,3.11000,2.89000,2.99000,3.49000,3.33000,2.58000,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
'2018-12-18 13:16:11.000',NULL,619.77002,2.86000,2.71000,2.74000,3.24000,3.49000,3.89000,3.30000,2.92000,2.77000,2.80000,3.05000,2.86000,2.92000,3.42000,2.52000,2.58000,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
'2018-12-18 13:21:11.000',NULL,612.28003,2.83000,2.64000,2.74000,3.21000,3.46000,3.89000,3.33000,2.89000,2.77000,2.80000,3.05000,2.83000,2.89000,3.39000,2.55000,2.58000,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
'2018-12-18 13:26:11.000',NULL,619.77002,2.74000,2.58000,2.61000,3.11000,3.36000,3.77000,3.17000,2.80000,2.68000,2.80000,2.92000,2.74000,2.80000,3.30000,2.40000,2.58000,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
'2018-12-18 13:31:11.000',NULL,614.15997,2.71000,2.58000,2.61000,3.05000,3.30000,3.70000,3.17000,2.77000,2.68000,2.80000,2.92000,2.68000,2.77000,3.24000,2.43000,2.58000,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
'2018-12-18 13:36:11.000',NULL,621.65002,2.61000,2.46000,2.49000,2.96000,3.17000,3.61000,3.02000,2.68000,2.52000,2.80000,2.83000,2.58000,2.68000,3.14000,2.30000,2.58000,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
'2018-12-18 13:46:11.000',NULL,621.65002,2.52000,2.37000,2.40000,2.83000,3.05000,3.46000,2.89000,2.55000,2.46000,2.80000,2.71000,2.49000,2.55000,2.99000,2.21000,2.58000,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
'2018-12-18 13:51:11.000',NULL,621.65002,2.43000,2.27000,2.30000,2.71000,2.96000,3.33000,2.80000,2.46000,2.37000,2.80000,2.61000,2.37000,2.46000,2.86000,2.12000,2.58000,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
'2018-12-18 13:56:11.000',NULL,616.03003,2.33000,2.24000,2.27000,2.64000,2.89000,3.30000,2.80000,2.40000,2.33000,2.80000,2.55000,2.33000,2.40000,2.80000,2.12000,2.58000,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL

**Expected Behavior**
导入无数据

**Screenshots**
![image](https://user-images.githubusercontent.com/28639191/94126422-2bae3300-fe8a-11ea-94e0-aabd967ae1dc.png)

**Environment (please complete the following information):**
 - OS:CentOS
 - Memory 2G, CPU:1C, current Disk Space:40G
 - TDengine Version 2.0.4

**Additional Context**

**Comment by Aries-Lee1991** [comment]
![image](https://user-images.githubusercontent.com/48907085/94128137-5600f000-fe8c-11ea-8654-dc21ad2b7893.png)
csv文件导入时，麻烦把表头删掉再导入。
