### ISSUE TITLE
how to issue group by query against both tags and normal columns

### ISSUE THREAD

**Issue by kejianchan** [taosdata/TDengine#3666]
场景：
统计不同固件版本的设备的离线率。

假如超级表是equipment，标签是device_no, 还有若干个字段，其中一个是verison_no版本号。

按照关系型数据库sql 应该是 select count(*) from equipment group by device_no, version_no;

但是使用tdengine这个sql会出错。因为version_no是一个字段.

请教一下，如何实现类似的需求

**Comment by hjxilinx** [comment]
TDengine 中不能同时支持同时包含 标签和普通列的 group by 操作，只能全部使用标签或者使用单个普通列。
后面我们会考虑支持这个功能。

**Comment by codering** [comment]
> TDengine 中不能同时支持同时包含 标签和普通列的 group by 操作，只能全部使用标签或者使用单个普通列。
> 后面我们会考虑支持这个功能。

我建的是普通表，按任何一个普通字段group by 都会出错，是什么原因？

```
Welcome to the TDengine shell from Linux, Client Version:2.0.4.0

  log_time         |            task_id             |            position            |              uid               
==================================================================================================================
 2020-09-25 17:22:04.353 | c6d17af0568a4084accbd9a8089f16 | p2                             | E03333                        
 2020-09-27 11:25:35.581 | efc8f223e39c452db0367972d7b56a | p2                             | E08100008CBC3CCC_595       
 2020-09-27 16:58:15.152 | efc8f223e39c452db0367972d7b56a | p1                             | E08100008CBC3646_857      
 2020-09-27 16:58:17.512 | efc8f223e39c452db0367972d7b56a | p2                             | E08100008CBC3646_857


taos> select uid from device group by uid;

DB error: invalid SQL: not allowed column type for group by

```

**Comment by codering** [comment]
搜索了下，group by 目前只支持 超级表？

**Comment by hjxilinx** [comment]
普通列也可以的。但是只能有一个普通列，每次 group by 的时候。

**Comment by codering** [comment]
> 普通列也可以的。但是只能有一个普通列，每次 group by 的时候。
> 
> 普通列 group by 操作只能针对 int/bigint/smallint/tinyint/bool
> 
> 在2.0.4.0版本中能支持 binary/nchar 类型。浮点类型和 timestamp 类型不能进行 group by 操作。

我就是用的2.0.4.0版本，除了log_time，其他字段都是nchar类型。 普通列group by有问题。

**Comment by hjxilinx** [comment]
This issue was closed because it has been inactive for too many days.
