### ISSUE TITLE
ARM架构安装问题server return invalid json format, code: 502, msg: Bad Gateway

### ISSUE THREAD

**Issue by zeus87101430** [taosdata/TDengine#3667]
安装环境：
1、操作系统基于ARM架构下的CentOS-7-aarch64-Minimal-1810；
2、TDengine-enterprise-server-2.0.4.0-Linux-aarch64；
3、云平台硬件为华为鲲鹏Kunpeng 920,32 Core@2.6GHz；
问题：
安全完成之后，通过6060端口登录之后提示“server return invalid json format, code: 502, msg: Bad Gateway”。

**Comment by plum-lihui** [comment]
TDengine-enterprise-server-2.0.4.0-Linux-aarch64这个安装包是在华为鲲鹏+中标麒麟上编译出来的，直接安装到centos系统中，我们没有验证过这种情况。你可以直接使用源码编译安装试试。
