### ISSUE TITLE
race in timer control life cycle management

### ISSUE THREAD

**Issue by localvar** [taosdata/TDengine#367]
this is not a problem at present as all timer controllers are created during process startup and destroyed before process termination. but this will become a problem when timer controllers are created and destroyed dynamically, as it designed to. 

i think this issue has already been noticed, because `taosTmrCleanUp` does much less job then it should do and memory pool deallocation is postponed to the creation of a time controller. 
https://github.com/taosdata/TDengine/blob/542da25452bc529e6802f9c41636f5c6a3f92ef9/src/util/src/ttimer.c#L208-L210

but this does not solve the problem: when a timer controller is freed in `taosTmrCleanUp`, it is possible that it still under processing by another thread in `taosTimerLoopFunc`, and even after the controller is re-created as a new one.

this result in many unexpected things and really buggy.

**Comment by jtao1735** [comment]
As you noticed, this is a problem when timer controller is created and destroyed dynamically. We will have a fix later, thanks.

**Comment by localvar** [comment]
thanks for reply, I've created a PR for this, please review and check if it is good or not.

BTW, there seems a plan to support ARM, if so, more attention need to be payed, because the memory model of ARM is weak whilst x86/x64 is strong, so code safe in x86/x64 may become unsafe in ARM.

for example, in the timer implementation, `pCtrl->signature = pCtrl` is used to mark the completion of initialization, and `if (pCtrl->signature)` is used to check whether `pCtrl` is a valid timer controller or not in the timer thread, this is fine in x86/x64, but could be a problem in ARM.
