### ISSUE TITLE
How to write only two tags if three tags exist in super table. 

### ISSUE THREAD

**Issue by 379547990** [taosdata/TDengine#3670]
Ubuntu 18.04   TDengine-server-2.0.1.1-Linux-x64     , JDBC  2.0.4
超级表 rainstation.monitoring 有三个标签， .code ,name ,tType 
如果入库语句**只写两个标签，会报错非法的语句，入库失败**。
 insert into             rainstation.S_${station.code} using rainstation.monitoring tags(#{station.code },#{station.name })            (ts, name, code,rainfall)             values             ( #{station.ts,jdbcType = TIMESTAMP}, #{station.name}, #{station.code},#{station.rainFall,jdbcType=FLOAT})

如果**写全三个标签 会正常入库**。
  insert into            rainstation.S_${station.code} using rainstation.monitoring tags(#{station.code },#{station.name },#{station.tType })   (ts, name, code,rainfall)     values   ( #{station.ts,jdbcType = TIMESTAMP}, #{station.name}, #{station.code},#{station.rainFall,jdbcType=FLOAT})

**Comment by hjxilinx** [comment]
标签需要对应匹配。如果您只想写入需要的标签，可以使用标签动态绑定的方式。insert into normal_table using super_table(tag1, tag2) tags(tag_value1, tags_value2) values(col1_val, col2_val,....)。这部分信息我们稍后会补充到文档。

**Comment by 379547990** [comment]
用法问题，已经解决
