### ISSUE TITLE
一条语句中多个四则运算数据同化的问题

### ISSUE THREAD

**Issue by WindHors** [taosdata/TDengine#3673]
**Bug Description**

![image](https://user-images.githubusercontent.com/13620064/94228752-43d88d80-ff30-11ea-8875-13a586e13deb.png)
同一条sql语句中进行多个列的四则运算，结果所有列都展示的是第一列的数据。

**Screenshots**
![image](https://user-images.githubusercontent.com/13620064/94228752-43d88d80-ff30-11ea-8875-13a586e13deb.png)

**Environment (please complete the following information):**
 - OS: CentOS7.8
 - Memory, CPU, current Disk Space
 - TDengine Version 2.0.1 和Version 2.0.3

**Comment by hjxilinx** [comment]
请更新新的版本，这个问题已经在2.0.4版本中进行了修复。
