### ISSUE TITLE
The queries from client of Windows platform will cause taosd  crash

### ISSUE THREAD

**Issue by zjq22** [taosdata/TDengine#3676]
**Bug Description**
windows 客户端执行select count(*) 语句报Invalid message错误；
执行select * from xxx语句后服务端直接异常关闭

**To Reproduce**
1. select count(*) form test.t9910 报Invalid message错误；
2. 执行select * from xxx语句后服务端直接异常关闭

**Expected Behavior**
帮忙看看是客户端配置问题，还是系统的一个BUG.
**Screenshots**
![捕获](https://user-images.githubusercontent.com/71868781/94236498-e9dfc400-ff3f-11ea-84d9-99f9382fa3ba.JPG)

左边为windows客户端，右边为ubuntu服务端。
一提交select * from xxx这条语句后服务端就挂了
**Environment (please complete the following information):**
 - OS: ubuntu9.3.0

 - TDengine Version 2.0.3.0

**Comment by hjxilinx** [comment]
应该是 Window 的客户端不是最新2.0.3最新的。2.0.3有过一次升级，导致的消息体协议变更，会导致出现您这里的问题。
建议您将服务器和window 客户端升级成2.0.4试一试。
