### ISSUE TITLE
java Driver com.taosdata.jdbc.TSDBDriver claims to not accept jdbcUrl, jdbc:TAOS://rock:6030/test

### ISSUE THREAD

**Issue by lonelyleaf** [taosdata/TDengine#3680]
**Bug Description**
`java.lang.RuntimeException: Driver com.taosdata.jdbc.TSDBDriver claims to not accept jdbcUrl, jdbc:TAOS://rock:6030/test`

your jdbc driver seems have a bug in driver's  `acceptsURL()` method.😂

**To Reproduce**
use springboot to connect taos,

**Expected Behavior**

**Screenshots**
![bug1](https://user-images.githubusercontent.com/9879800/94248470-1bad5680-ff51-11ea-9a96-23dd239df197.png)
![bug2](https://user-images.githubusercontent.com/9879800/94248473-1d771a00-ff51-11ea-8176-3f8c13362c0c.png)

**Environment (please complete the following information):**
 - java jdbc: com.taosdata.jdbc:taos-jdbcdriver:2.0.6'

**Comment by zyyang-taosdata** [comment]
thank you, we have fix this bug in taos-jdbcdriver-2.0.7, please update your jdbcdriver in you project.

**Comment by lonelyleaf** [comment]
It's ok now😀
