### ISSUE TITLE
我想知道你们详细的压缩算法思路，但是找不到压缩算法的代码

### ISSUE THREAD

**Issue by huangsheng7271** [taosdata/TDengine#3684]
我最近几天一直在看官方的文档，发现TDengine的读/写性能和压缩率上面都要比InfluxDB快上很多。我特别想知道您们是做了那些优化，才能达到如此效果。我有几个猜测：
一：TDengine采用的是C语言来编写，而InfluxDB是用的Go语言，所以“基因“就要优秀很多。
二：通过研究https://www.taosdata.com/cn/documentation/architecture/#缓存与持久化这篇文档，发现你们在压缩算法那里将InfluxDB的snappy替换成了Lz4。

但是就通过这两个地方能得到如此大的提升，我还是觉得很不可思议。所以猜测你们在压缩那里费了功夫，特别想知道详细细节。所以还恳请官方大大答疑解惑。感谢！！！

**Comment by hzcheng** [comment]
您可以搜索文件tsCompression.c，或者点击这个链接：https://github.com/taosdata/TDengine/blob/master/src/util/src/tcompression.c

**Comment by huangsheng7271** [comment]
感谢！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taosdata/TDengine"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月27日(星期天) 上午10:53
收件人:&nbsp;"taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送:&nbsp;"ζ 在路上╰"<1490085442@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [taosdata/TDengine] 我想知道你们详细的压缩算法思路，但是找不到压缩算法的代码 (#3684)





 
您可以搜索文件tsCompression.c，或者点击这个链接：https://github.com/taosdata/TDengine/blob/master/src/util/src/tcompression.c
