### ISSUE TITLE
Execute taosdemo -d demo2 -t 2000000 -n 100000，taosdemo hung，and number of record stop at 161150922000

### ISSUE THREAD

**Issue by malinco** [taosdata/TDengine#3685]
Bug Description
Execute taosdemo -d demo2 -t 2000000 -n 100000，taosdemo hung，and the number of record stop at 161150922000

To Reproduce
1.前置条件：
Execute taosdemo -d demo2 -t 2000000 -n 100000
2.About 48 hours later，select count(*) from meters;
3. taosdemo hung，the number of record stop at 161150922000;
4. detail results：
taos> select count(*) from meters;
       count(*)        |
========================
          161150922000 |
Query OK, 1 row(s) in set (60.097181s)

taos> select count(*) from meters;
       count(*)        |
========================
          161150922000 |
Query OK, 1 row(s) in set (39.667680s)

Expected Behavior
taosdemo hung，the number of record stop at 161150922000;

Screenshots
Look at the Step 4 of To Reproduce

Environment (please complete the following information):

OS: Ubuntu 16.04 server
16GB, i5 8600 3.10GHZ, 1T SSD
TDengine Version [ 2.0.3.1]
Additional Context
无

**Comment by plum-lihui** [comment]
1、taosd的状况如何？有没有出现crash，产生core了么？
2、有没有打开调试开关，将debugflag  设置成  135，如果设置了，请将taosdemo所在的客户端日志发送出来，我们分析下。
多谢！

**Comment by malinco** [comment]
没有crash，公司不能外发数据。你们可以试着复现一下，我这里必现的

**Comment by plum-lihui** [comment]
TDengine经过一年多的努力后，解决了不少bug，已经有了更稳定的版本，可以更新取用。
多谢！
