### ISSUE TITLE
Cannot create table by REST API.

### ISSUE THREAD

**Issue by micli** [taosdata/TDengine#3697]
**Bug Description**
User sends a request by curl to create table, response shows succeeded but table does not exist.

**To Reproduce**
1. Login to TDengine Server.
2. Send create table request by curl as documentation described.
```shell
curl -H 'Authorization: Basic cm9vdDp0YW9zZGF0YQ==' -d 'USE testdb; CREATE TABLE mqtt_msg (ts timestamp, msgid NCHAR(64), topic NCHAR(255), qos TINYINT, payload BINARY(1024), arrived timestamp);' localhost:6041/rest/sql
```
The response shows succeeded:
```shell
{"status":"succ","head":["affected_rows"],"data":[[0]],"rows":0}
```
3. Login taos command line by root/taosdata and check table:
```shell
> taos --user=root --password=taosdata

Welcome to the TDengine shell from Linux, Client Version:2.0.3.0
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

taos> use testdb;
Database changed.

taos> select * from mqtt_msg;

DB error: Table does not exist
```
4. If run create table statement alone in taos command line, table created successfully.
```shell
taos> CREATE TABLE mqtt_msg (ts timestamp, msgid NCHAR(64), topic NCHAR(255), qos TINYINT, payload BI
NARY(1024), arrived timestamp);
Query OK, 0 row(s) affected (0.100608s)

taos> select * from mqtt_msg;
Query OK, 0 row(s) in set (0.012229s)
```

**Expected Behavior**
Table mqtt_msg can be create succeeded by curl request.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Memory, CPU, current Disk Space
 - TDengine Version 2.0.3.0

**Additional Context**

**Comment by sangshuduo** [comment]
The RESTFul API doesn't support execute two or more database operations in one line.

Please use:

curl -H 'Authorization: Basic cm9vdDp0YW9zZGF0YQ==' -d 'CREATE TABLE testdb.mqtt\_msg (ts timestamp, msgid NCHAR(64), topic NCHAR(255), qos TINYINT, payload BINARY(1024), arrived timestamp);' localhost:6041/rest/sql

**Comment by micli** [comment]
Thanks for your reply. By many times retry, I figure out it to same reason. I think we should notify users that RESTful API only support one SQL statement one time.
