### ISSUE TITLE
cntos7上从编译报错到编译成功的过程。

### ISSUE THREAD

**Issue by maymay1982** [taosdata/TDengine#37]
MVN is not installed and JDBC is not compiled.
安装了MVN和JDBC，仍然报错：
CMake Error at src/client/CMakeLists.txt:30 (SET_TARGET_PROPERTIES):
  SET_TARGET_PROPERTIES called with incorrect number of arguments.

-- MVN is installed and JDBC will be compiled
-- Configuring incomplete, errors occurred!
See also "/home/TDengine-master/build/CMakeFiles/CMakeOutput.log".

**Comment by maymay1982** [comment]
换了台ubuntu16.04的机器，还是报同样的错，奇怪，大家都没这样的问题吗？

**Comment by 2efPer** [comment]
在项目根目录make，然后在cd 到build目录，make --build . 
估计是和这个相关。
可以参考https://github.com/2efPer/tdengine-docker/blob/master/server/Dockerfile

**Comment by maymay1982** [comment]
好的，谢谢陶老师，这会不在办公室，明天我试试。今天看到您50岁的时候还在抠代码，真是很敬佩。发自我的华为手机-------- 原始邮件 --------主题：Re: [taosdata/TDengine] cntos7上编译报错。 (#37)发件人：2efper 收件人：taosdata/TDengine 抄送：maymay1982 ,Author 在项目根目录make，然后在cd 到build目录，make --build .

估计是和这个相关。

可以参考https://github.com/2efPer/tdengine-docker/blob/master/server/Dockerfile



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/taosdata/TDengine/issues/37?email_source=notifications\u0026email_token=AHEAQAPDGGEKSNTDR56CAPDP7RS47A5CNFSM4IDT6WA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZ5QC3Y#issuecomment-511377775",

"url": "https://github.com/taosdata/TDengine/issues/37?email_source=notifications\u0026email_token=AHEAQAPDGGEKSNTDR56CAPDP7RS47A5CNFSM4IDT6WA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZ5QC3Y#issuecomment-511377775",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by maymay1982** [comment]
刚检查了，是在build目录下make的，还是报同样的错。

**Comment by maymay1982** [comment]
cmake版本是3.14，跟这个有关系吗？

**Comment by coder-chriswang** [comment]
本人也是cmake报错，一样的错误，版本3.15

**Comment by coder-chriswang** [comment]
能否提供 taos-xxxxxxxxx.tar.gz？ 这样，无需每个体验开发者，走一样的编译流程了。

**Comment by lengyuyan** [comment]
MVN is not installed and JDBC is not compiled
同样的错误

**Comment by maymay1982** [comment]
用了陶老师团队昨天发布的版本后，已成功编译。

**Comment by maymay1982** [comment]
> 
> 
> MVN is not installed and JDBC is not compiled
> 同样的错误

首先，你要装一下apache-maven-3.5.4-bin，并且需要在/etc/profile里配置；其次，要装一下jdk，并且需要在/etc/profile里配置（具体路径根据自己的安装情况更改）：
JAVA_HOME=/home/jdk1.8.0_191
export JRE_HOME=$JAVA_HOME/jre
export PATH=$JAVA_HOME/bin:$JAVA_HOME/jre/bin:$PATH
export CLASSPATH=$CLASSPATH:.:$JAVA_HOME/lib:$JAVA_HOME/jre/lib
MAVEN_HOME=/usr/local/apache-maven-3.5.4
export MAVEN_HOME
export PATH=${PATH}:${MAVEN_HOME}/bin
