### ISSUE TITLE
我要在windows上使用c++ 来连接使用TDengine，但工程编不过

### ISSUE THREAD

**Issue by 704667987** [taosdata/TDengine#370]
1、对tdengine-windows-client-x64-1.6.1.4.exe  进行安装。安装路径C:\TDengine
2、切换到C:\TDengine\examples\c； 目录存在CMakeLists.txt 文件
![image](https://user-images.githubusercontent.com/33055155/63141379-0eb4f880-c018-11e9-88e3-f27ee9b47965.png)
![image](https://user-images.githubusercontent.com/33055155/63141633-0a3d0f80-c019-11e9-954f-ca9f7f1a33f1.png)

![image](https://user-images.githubusercontent.com/33055155/63141405-23918c00-c018-11e9-953f-2b7800699e26.png)
3、生成完工程后，编译出现很多错误，其中#include <unistd.h> 、#include <pthread.h>、#include <sys/time.h> 我是通过MinGW 插件安装的。
![image](https://user-images.githubusercontent.com/33055155/63141868-f2b25680-c019-11e9-8b57-0709d94459a1.png)

是否哪里还需要设置？

**Comment by guanshengliang** [comment]
windows下，仅在vs2013版本经过测试，其他编译环境未进行过验证
如需windows端调试，直接到网站上下载编译好的windows客户端

**Comment by 704667987** [comment]
> 窗下，仅在vs2013版本经过测试，compile-其他未环境过进行验证
> 如需窗端调试，直接到网站上下载编译好的窗户客户端

vs2013版本我也试过，我看错误的提标像是我加载的头文件不太对。编译好的窗户客户端在哪里下载？我没有找到入口。

**Comment by guanshengliang** [comment]
严格按照这篇博客，可以编译通过
```
https://www.taosdata.com/blog/2019/07/26/如何编译tdengine的windows客户端/
```
windows客户端下载地址
```
https://www.taosdata.com/cn/getting-started/
```

**Comment by netantz** [comment]
there is no pthread (pthread.h etc) library with Visual Studio. How did you get it compiled?
also there is no stdbool.h in VS so windows/os.h has issue.

**Comment by netantz** [comment]
also I tried mingw x64 build, apparently cmake passes cl.exe options to gcc.exe, which won't work.  :-)
@guanshengliang is VC (cl.exe) the only workable compiler on Windows?

**Comment by netantz** [comment]
试了下VS2010， VS2019 都不行。

看来只能试一下VS2013。装个VS系统里到处留垃圾，实在不想试了。

**Comment by guanshengliang** [comment]
您好，windows的编译环境非常复杂，而TDengine对windows的定位只是提供一个相对容易的开发环境，生产环境运行是推荐linux的。
1.如果不喜欢折腾，官网上有对应linux版本的windows客户端，里面有编译好的taos.dll，如果找不到下载链接，可以报告网站方面的相关问题。
2.如果喜欢折腾，那么弄个VS2013也不算很麻烦
