### ISSUE TITLE
query exception DB error: Invalid Vgroup ID

### ISSUE THREAD

**Issue by weicz1221** [taosdata/TDengine#3703]
**Bug Description**
服务器异常重启后，查询数据发生异常，DB error: Invalid Vgroup ID，这个库的数据量大概有500多亿行数据

其中有一个库的发生的异常是：DB error: Unable to establish connection，查询log数据库则是正常。
![image](https://user-images.githubusercontent.com/49259303/94399054-4558be80-0199-11eb-895f-a69e55309f90.png)

**Environment (please complete the following information):**
 - OS: CentOS 7.0
 - Memory 16G ， CPU 16核， current Disk Space 500G
 - TDengine Version ：Version:2.0.3.1

**Additional Context**
服务器主机异常关机后一起，单节点

**Comment by weicz1221** [comment]
`

Welcome to the TDengine shell from Linux, Client Version:2.0.3.1
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

taos> use log;
Database changed.

taos> show tables;
           table_name           |      created_time       | columns |          stable_name           |
======================================================================================================
 slowquery                      | 2020-09-19 10:12:05.332 |       5 |                                |
 dn1                            | 2020-09-19 10:12:05.318 |      15 | dn                             |
 log                            | 2020-09-19 10:12:05.292 |       4 |                                |
 acct_root                      | 2020-09-19 10:12:05.326 |      22 | acct                           |
Query OK, 4 row(s) in set (0.045876s)

taos> select count(*) from dn;
       count(*)        |
========================
                 25405 |
Query OK, 1 row(s) in set (0.007401s)

taos> use iot;
Database changed.

taos> select count(*) from itemtag;

DB error: Unable to establish connection
taos> use iot_data;
Database changed.


`

**Comment by weicz1221** [comment]
09/28 15:04:00.076716 0x7f1047fff700 VND ERROR vgId:153, failed to read vnode version, content is null

09/28 15:04:00.081708 0x7f1047fff700 VND ERROR vgId:157, failed to read vnode version, content is null

在日志中有这样的异常日志

**Comment by weicz1221** [comment]
[taosdlog.zip](https://github.com/taosdata/TDengine/files/5291833/taosdlog.zip)
相关日志，服务异常关机的日志被删掉了，这个是重启后的日志，估计是在写version.json的时候集群突然关机时导致的

**Comment by guanshengliang** [comment]
从日志上找不到具体原因，你下载一个向日葵，加下我的微信geiseil，我远程看一下。

**Comment by guanshengliang** [comment]
2052版本已经私信发给你，您验证一下是否还有此问题

**Comment by weicz1221** [comment]
已验证，数据可以查出

**Comment by cddonald** [comment]
你好，我也遇到了这个问题，后来是怎么解决的？

**Comment by weicz1221** [comment]
> 你好，我也遇到了这个问题，后来是怎么解决的？

2052版本以后的版本已经解决了这个问题，你可以试一下新版本
