### ISSUE TITLE
DB error: Unable to establish connection

### ISSUE THREAD

**Issue by zhangyang1995** [taosdata/TDengine#3715]
我是虚拟机centos7部署的TDengine 使用的windows的client      
 在windows tao -h ip 可以连接到但是输入命令就显示 
DB error: Unable to establish connection

C:\TDengine>taos -h 192.168.84.131

Welcome to the TDengine shell from Linux, Client Version:2.0.4.0
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

taos> show databases;

DB error: Unable to establish connection
taos> show databases;

DB error: Unable to establish connection
taos>

**Comment by zhangyang1995** [comment]
服务端版本TDengine-server-2.0.4.0-Linux-x64.tar.gz        
客户端版本TDengine-client-2.0.4.0-Windows-x64.exe (3.1M)

**Comment by zhangyang1995** [comment]
已经解决需要服务端开放udp端口！！！

**Comment by deuxmille** [comment]
打开了6030-6041的udp，2.0.7.0版本仍然有这个问题。服务端需要开放哪个udp端口？

**Comment by deuxmille** [comment]
hostname和fqdn改一致后解决。

**Comment by dullduck** [comment]
fqdn 改成ip试试

**Comment by lzl-anonym** [comment]
防火墙一定要关闭！！！
