### ISSUE TITLE
CenterOS 8 默认占用内存很高

### ISSUE THREAD

**Issue by sz-justinwang** [taosdata/TDengine#3718]
测试环境：
OS：CenterOS 8
Memory： 10g
Cpu: 4
Disk:  41.6/53.7G 使用率  
安装TDengine-server-2.0.4.0-Linux-x64.rpm，导入taosDemo ，配置grafana，

状况：

在不做任何查询的情况下，taos系统内存占用率很高，一致没有释放资源
导致系统卡死

ps auxw --sort=rss
USER         PID %CPU %MEM    VSZ             RSS           TTY      STAT START   TIME COMMAND
root          1293  177   88.2      19647912    8871444 ?    Ssl  09:36 119:27 /usr/bin/taosd

**Comment by yihaoDeng** [comment]
请注明下版本

**Comment by sz-justinwang** [comment]
grafana:
 grafana-7.2.0-1.x86_64.rpm
OS:
centos-release-8.2-2.2004.0.1.el8.x86_64

**Comment by hjxilinx** [comment]
您的查询语句是什么样的？

**Comment by sz-justinwang** [comment]
在grafana里面创建一个dashboard
添加两个Query
select avg(f1) from test.meters  where ts>=$from and ts<=$to and loc='beijing'  interval($interval)
select avg(f2) from test.meters  where ts>=$from and ts<=$to and loc='beijing'  interval($interval)

**Comment by sangshuduo** [comment]
试一下在 /etc/taos/taos.cfg 里设置 debugFlag 0

**Comment by sz-justinwang** [comment]
> 试一下在 /etc/taos/taos.cfg 里设置 debugFlag 0
非常感谢，配置文件里面默认是#，应该是关闭日志功能的，修改配置后，内存仍然无法释放

![微信图片_20201010144340](https://user-images.githubusercontent.com/72057154/95648055-04509a80-0b07-11eb-887d-6783aea9e4be.png)

在没有执行查询前，free内存使用率
![微信图片_20201010144709](https://user-images.githubusercontent.com/72057154/95648131-80e37900-0b07-11eb-9d2a-0be11eca6558.png)

执行面板查询后
![微信图片_20201010145235](https://user-images.githubusercontent.com/72057154/95648243-41695c80-0b08-11eb-901a-aba212623318.png)

**Comment by sz-justinwang** [comment]
show queries；
select * from log.slowquery;
已无链接，但是内存占用较高

![image](https://user-images.githubusercontent.com/72057154/95650062-aaa29d00-0b13-11eb-91e4-5bc796dc188c.png)
![image](https://user-images.githubusercontent.com/72057154/95650077-c73ed500-0b13-11eb-9a3a-b17bc2115f28.png)

**Comment by yu285** [comment]
pls upgrade to newest version
