### ISSUE TITLE
select 语句报：DB error: invalid SQL: alias name too long

### ISSUE THREAD

**Issue by Darcty** [taosdata/TDengine#3720]
需求是查询某个测点当天的数据，之前一个多月都是好的，今天这个表的数据突然查不出来了，看了下日志发现这个问题。
差不多十几个超级表吧，写法都一样的，就这个表今天突然就查询报错了
version is 1.6.6.1
sql语句这样写报错，换个写法可以查出数据来
taos> SELECT P13M11 as val,ts from iot_energy.t_power_quality_monitor_d2780bf5a7f227f973277a461c4d5ec5 where ts>1601308800742 and ts<1601395199742 order by ts ;
DB error: invalid SQL: alias name too long

这样写可以查出来

> taos> SELECT P13M11 as val,ts from iot_energy.t_power_quality_monitor where device_id='d2780bf5a7f227f973277a461c4d5ec5' and ts>1601308800742 and ts<1601395199742 order by ts;

        val         |          ts          |
============================================
             0.00000| 20-09-29 04:04:09.000|
             0.00000| 20-09-29 05:57:03.000|
             0.00000| 20-09-29 05:47:47.000|
             0.00000| 20-09-29 05:39:28.000|
             0.00000| 20-09-29 04:09:09.000|
			 
count 语句有同样的问题
taos> select count(*) from iot_energy.t_power_quality_monitor_d2780bf5a7f227f973277a461c4d5ec5;
DB error: invalid SQL: alias name too long
taos> select count(*) from iot_energy.t_power_quality_monitor where device_id='d2780bf5a7f227f973277a461c4d5ec5';
      count(*)       

======================
                 8035|
Query OK, 1 row(s) in set (0.044831s)
taos> 

表结构

> taos> describe t_power_quality_monitor;

                             Field                              |      Type      |  Length   |  Note  |
=======================================================================================================
ts                                                              |TIMESTAMP       |          8|        |
projectsn                                                       |BINARY          |         50|        |
gatewaysn                                                       |BINARY          |         50|        |
deviceaddress                                                   |INT             |          4|        |
p13m1                                                           |FLOAT           |          4|        |
p13m2                                                           |FLOAT           |          4|        |
p13m3                                                           |FLOAT           |          4|        |
p13m4                                                           |FLOAT           |          4|        |
p13m5                                                           |FLOAT           |          4|        |
p13m6                                                           |FLOAT           |          4|        |
p13m7                                                           |FLOAT           |          4|        |
p13m8                                                           |FLOAT           |          4|        |
p13m9                                                           |FLOAT           |          4|        |
p13m10                                                          |FLOAT           |          4|        |
p13m11                                                          |FLOAT           |          4|        |
p13m12                                                          |FLOAT           |          4|        |
p13m13                                                          |FLOAT           |          4|        |
p13m14                                                          |FLOAT           |          4|        |
p13m15                                                          |FLOAT           |          4|        |
p13m16                                                          |FLOAT           |          4|        |
p13m17                                                          |FLOAT           |          4|        |
p13m18                                                          |FLOAT           |          4|        |
p13m19                                                          |FLOAT           |          4|        |
p13m20                                                          |FLOAT           |          4|        |
p13m21                                                          |FLOAT           |          4|        |
p13m22                                                          |FLOAT           |          4|        |
p13m23                                                          |FLOAT           |          4|        |
p13m24                                                          |FLOAT           |          4|        |
p13m25                                                          |FLOAT           |          4|        |
p13m26                                                          |FLOAT           |          4|        |
p13m27                                                          |FLOAT           |          4|        |
p13m28                                                          |FLOAT           |          4|        |
p13m29                                                          |FLOAT           |          4|        |
p13m30                                                          |FLOAT           |          4|        |
p13m31                                                          |FLOAT           |          4|        |
p13m32                                                          |FLOAT           |          4|        |
p13m33                                                          |FLOAT           |          4|        |
p13m34                                                          |FLOAT           |          4|        |
p13m35                                                          |FLOAT           |          4|        |
p13m36                                                          |FLOAT           |          4|        |
p13m37                                                          |FLOAT           |          4|        |
p13m38                                                          |FLOAT           |          4|        |
p13m39                                                          |FLOAT           |          4|        |
p13m40                                                          |FLOAT           |          4|        |
p13m41                                                          |FLOAT           |          4|        |
p13m42                                                          |FLOAT           |          4|        |
p13m43                                                          |FLOAT           |          4|        |
p13m44                                                          |FLOAT           |          4|        |
p13m45                                                          |FLOAT           |          4|        |
p13m46                                                          |FLOAT           |          4|        |
p13m47                                                          |FLOAT           |          4|        |
p13m48                                                          |FLOAT           |          4|        |
p13m49                                                          |FLOAT           |          4|        |
p13m50                                                          |FLOAT           |          4|        |
p13m51                                                          |FLOAT           |          4|        |
p13m52                                                          |FLOAT           |          4|        |
p13m53                                                          |FLOAT           |          4|        |
p13m54                                                          |FLOAT           |          4|        |
p13m55                                                          |FLOAT           |          4|        |
p13m56                                                          |FLOAT           |          4|        |
p13m57                                                          |FLOAT           |          4|        |
p13m58                                                          |FLOAT           |          4|        |
p13m59                                                          |FLOAT           |          4|        |
p13m60                                                          |FLOAT           |          4|        |
p13m61                                                          |FLOAT           |          4|        |
p13m62                                                          |FLOAT           |          4|        |
p13m63                                                          |FLOAT           |          4|        |
p13m64                                                          |FLOAT           |          4|        |
p13m65                                                          |FLOAT           |          4|        |
p13m66                                                          |FLOAT           |          4|        |
p13m67                                                          |FLOAT           |          4|        |
p13m68                                                          |FLOAT           |          4|        |
p13m69                                                          |FLOAT           |          4|        |
p13m70                                                          |FLOAT           |          4|        |
p13m71                                                          |FLOAT           |          4|        |
p13m72                                                          |FLOAT           |          4|        |
p13m73                                                          |FLOAT           |          4|        |
p13m74                                                          |FLOAT           |          4|        |
p13m75                                                          |FLOAT           |          4|        |
p13m76                                                          |FLOAT           |          4|        |
p13m77                                                          |FLOAT           |          4|        |
p13m78                                                          |FLOAT           |          4|        |
p13m79                                                          |FLOAT           |          4|        |
p13m80                                                          |FLOAT           |          4|        |
p13m81                                                          |FLOAT           |          4|        |
p13m82                                                          |FLOAT           |          4|        |
p13m83                                                          |FLOAT           |          4|        |
p13m84                                                          |FLOAT           |          4|        |
p13m85                                                          |FLOAT           |          4|        |
p13m86                                                          |FLOAT           |          4|        |
p13m87                                                          |FLOAT           |          4|        |
p13m88                                                          |FLOAT           |          4|        |
p13m89                                                          |FLOAT           |          4|        |
p13m90                                                          |FLOAT           |          4|        |
p13m91                                                          |FLOAT           |          4|        |
p13m92                                                          |FLOAT           |          4|        |
p13m93                                                          |FLOAT           |          4|        |
p13m94                                                          |FLOAT           |          4|        |
p13m95                                                          |FLOAT           |          4|        |
p13m96                                                          |FLOAT           |          4|        |
p13m97                                                          |FLOAT           |          4|        |
p13m98                                                          |FLOAT           |          4|        |
p13m99                                                          |FLOAT           |          4|        |
p13m100                                                         |FLOAT           |          4|        |
p13m101                                                         |FLOAT           |          4|        |
p13m102                                                         |FLOAT           |          4|        |
p13m103                                                         |FLOAT           |          4|        |
p13m104                                                         |FLOAT           |          4|        |
p13m105                                                         |FLOAT           |          4|        |
p13m106                                                         |FLOAT           |          4|        |
p13m107                                                         |FLOAT           |          4|        |
p13m108                                                         |FLOAT           |          4|        |
p13m109                                                         |FLOAT           |          4|        |
p13m110                                                         |FLOAT           |          4|        |
p13m111                                                         |FLOAT           |          4|        |
p13m112                                                         |FLOAT           |          4|        |
p13m113                                                         |FLOAT           |          4|        |
p13m114                                                         |FLOAT           |          4|        |
p13m115                                                         |FLOAT           |          4|        |
p13m116                                                         |FLOAT           |          4|        |
p13m117                                                         |FLOAT           |          4|        |
p13m118                                                         |FLOAT           |          4|        |
p13m119                                                         |FLOAT           |          4|        |
p13m120                                                         |FLOAT           |          4|        |
sts                                                             |TIMESTAMP       |          8|        |
device_id                                                       |BINARY          |         32|tag     |
Query OK, 126 row(s) in set (0.001755s)

**Comment by hjxilinx** [comment]
是不是文件名太长了？您可以试一试一个短一点的文件名是否正常？

**Comment by hjxilinx** [comment]
This issue was closed because it has been inactive for too many days.
