### ISSUE TITLE
dnode offline after drop and create again

### ISSUE THREAD

**Issue by olajowon** [taosdata/TDengine#3725]
![image](https://user-images.githubusercontent.com/18394195/94544928-72cb6800-027e-11eb-93e2-3374da25f6bf.png)

![image](https://user-images.githubusercontent.com/18394195/94528890-9933d800-026b-11eb-9378-f585f97a64e5.png)

如我第一个图片，我新添加的node id 是 8、9，而日志里一直检查的是 2、3；还有虽然显示离线，但是加新node后，在其他两个节点 show dnodes 也能查看新加的node，只是状态是离线，而且show mnodes 也查不到新加的Node

**Comment by olajowon** [comment]
taos> show dnodes;
   id   |                 end_point                  | vnodes | cores  |     status     |   role   |       create_time       |

      1 | tdengine-prod-001:6030     |      1 |      4 | ready          | any      | 2020-09-29 11:29:22.016 |
      8 | tdengine-prod-002:6030     |      0 |      0 | offline        | any      | 2020-09-29 15:44:21.637 |
      9 | tdengine-prod-003:6030     |      0 |      0 | offline        | any      | 2020-09-29 15:44:26.018 |
Query OK, 3 row(s) in set (0.000698s)

taos> show mnodes;
   id   |                 end_point                  |      role      |       create_time       |

      1 | tdengine-prod-001:6030     | master         | 2020-09-29 11:29:22.016 |
Query OK, 1 row(s) in set (0.000724s)

**Comment by olajowon** [comment]
09/29 15:49:47.166054 0x7f35787f8700 MND ERROR dnode id:2, nicetuan-op-drm-tdengine-prod-002:6030 not exist
09/29 15:49:47.329678 0x7f35787f8700 DND msg:status will be processed in mpeer queue
09/29 15:49:47.840230 0x7f3578ff9700 DND 0x7f1674001170, msg:heartbeat will be processed in mread queue
09/29 15:49:47.846921 0x7f35797fa700 DND 0x7fa424001170, msg:heartbeat will be processed in mread queue
09/29 15:49:47.907006 0x7f35787f8700 DND msg:status will be processed in mpeer queue
09/29 15:49:47.907033 0x7f35787f8700 MND ERROR dnode id:3, nicetuan-op-drm-tdengine-prod-003:6030 not exist
09/29 15:49:47.920992 0x7f3578ff9700 DND 0x7f4a50001170, msg:heartbeat will be processed in mread queue
09/29 15:49:48.171022 0x7f35787f8700 DND msg:status will be processed in mpeer queue
09/29 15:49:48.171046 0x7f35787f8700 MND ERROR dnode id:2, nicetuan-op-drm-tdengine-prod-002:6030 not exist
09/29 15:49:48.232909 0x7f35797fa700 DND 0x7fe918001170, msg:heartbeat will be processed in mread queue
09/29 15:49:48.329643 0x7f3578ff9700 DND 0x7f354c001170, msg:heartbeat will be processed in mread queue
09/29 15:49:48.329676 0x7f35787f8700 DND msg:status will be processed in mpeer queue

**Comment by sangshuduo** [comment]
如果之前写入过数据，drop 后要删了数据文件再加回来

**Comment by zhangyang1995** [comment]
> 如果之前写入过数据，drop 后要删了数据文件再加回来

请问如何删除数据文件是哪个文件啊 东西有点多 害怕删除错了
[root@node1 taos]# ls
dnode  mnode  vnode  vnode_bak
[root@node1 taos]# cd dnode/
[root@node1 dnode]# ls
dnodeCfg.json  mnodeEpSet.json
[root@node1 dnode]# cd ..
[root@node1 taos]# ls
dnode  mnode  vnode  vnode_bak
[root@node1 taos]# cd vnode
[root@node1 vnode]# ls
vnode2
[root@node1 vnode]# cd vnode2/
[root@node1 vnode2]# ls
config.json  tsdb  version.json  wal
[root@node1 vnode2]# ls
config.json  tsdb  version.json  wal
[root@node1 vnode2]# cd ..
[root@node1 vnode]# ls
vnode2
[root@node1 vnode]# cd ..
[root@node1 taos]# ls
dnode  mnode  vnode  vnode_bak

**Comment by sangshuduo** [comment]
需要删掉 /var/lib/taos 目录下的所有文件。另外就是建议提前做一个规划，配置好 taos.cfg 之后再启动 taosd ，然后写数据。
