### ISSUE TITLE
TDengine's Search performance

### ISSUE THREAD

**Issue by moziie** [taosdata/TDengine#3727]
### 环境：
系统：linux centos8,8核16G内存，挂载50G硬盘，应用安装了tdengine，grafana,其他都是云服务器自带的一些东西
### 表结构：
数据库6个，包含自带log和udb库；
测试的库中只有一个超级表，执行describe meterdata.smeters;
             Field              |        Type        |   Length    |    Note    |
 ts                             | TIMESTAMP          |           8 |            |
 activeenergy                   | FLOAT              |           4 |            |
 positiveenergy                 | FLOAT              |           4 |            |
 activepower                    | FLOAT              |           4 |            |
 activepowera                   | FLOAT              |           4 |            |
 activepowerb                   | FLOAT              |           4 |            |
 activepowerc                   | FLOAT              |           4 |            |
 positivepower                  | FLOAT              |           4 |            |
 positivepowera                 | FLOAT              |           4 |            |
 positivepowerb                 | FLOAT              |           4 |            |
 positivepowerc                 | FLOAT              |           4 |            |
 powerfactor                    | FLOAT              |           4 |            |
 powerfactora                   | FLOAT              |           4 |            |
 powerfactorb                   | FLOAT              |           4 |            |
 powerfactorc                   | FLOAT              |           4 |            |
 voltagea                       | FLOAT              |           4 |            |
 voltageb                       | FLOAT              |           4 |            |
 voltagec                       | FLOAT              |           4 |            |
 currenta                       | FLOAT              |           4 |            |
 currentb                       | FLOAT              |           4 |            |
 currentc                       | FLOAT              |           4 |            |
 location                       | BINARY             |          64 | TAG        |
 deviceid                       | BINARY             |          64 | TAG        |
 mspid                          | BINARY             |          64 | TAG        |
 userid                         | BINARY             |          64 | TAG        |
包含1000张子表，共有数据650W左右；
### 测试查询结果
taos> select avg(voltagea), max(activeenergy), min(powerfactorb) from meterdata.smeters;
       avg(voltagea)       |  max(activeenergy)   |  min(powerfactorb)   |
               6.641772019 |           2790.00000 |              0.91000 |
Query OK, 1 row(s) in set (0.831616s)

taos> select avg(voltagea), max(activeenergy), min(powerfactorb) from meterdata.smeters;
       avg(voltagea)       |  max(activeenergy)   |  min(powerfactorb)   |
               6.641772019 |           2790.00000 |              0.91000 |
Query OK, 1 row(s) in set (0.845519s)

taos> select avg(voltagea), max(activeenergy), min(powerfactorb) from meterdata.smeters;
       avg(voltagea)       |  max(activeenergy)   |  min(powerfactorb)   |
               6.641772019 |           2790.00000 |              0.91000 |
Query OK, 1 row(s) in set (0.833254s)

taos> select avg(voltagea), max(activeenergy), min(powerfactorb) from meterdata.smeters;
       avg(voltagea)       |  max(activeenergy)   |  min(powerfactorb)   |
               6.641772019 |           2790.00000 |              0.91000 |
Query OK, 1 row(s) in set (0.834580s)

taos> select avg(voltagea), max(activeenergy), min(powerfactorb) from meterdata.smeters;
       avg(voltagea)       |  max(activeenergy)   |  min(powerfactorb)   |
               6.641772019 |           2790.00000 |              0.91000 |
Query OK, 1 row(s) in set (0.834278s)

taos> select avg(voltagea), max(activeenergy), min(powerfactorb) from meterdata.smeters;
       avg(voltagea)       |  max(activeenergy)   |  min(powerfactorb)   |
               6.641772019 |           2790.00000 |              0.91000 |
Query OK, 1 row(s) in set (0.834338s)

taos> select avg(voltagea), max(activeenergy), min(powerfactorb) from meterdata.smeters;
       avg(voltagea)       |  max(activeenergy)   |  min(powerfactorb)   |
               6.641772019 |           2790.00000 |              0.91000 |
Query OK, 1 row(s) in set (0.832085s)

taos> select avg(voltagea), max(activeenergy), min(powerfactorb) from meterdata.smeters;
       avg(voltagea)       |  max(activeenergy)   |  min(powerfactorb)   |
               6.641772019 |           2790.00000 |              0.91000 |
Query OK, 1 row(s) in set (0.836898s)

taos> select avg(voltagea), max(activeenergy), min(powerfactorb) from meterdata.smeters;
       avg(voltagea)       |  max(activeenergy)   |  min(powerfactorb)   |
               6.641772019 |           2790.00000 |              0.91000 |
Query OK, 1 row(s) in set (0.835763s)

taos> select avg(voltagea), max(activeenergy), min(powerfactorb) from meterdata.smeters;
       avg(voltagea)       |  max(activeenergy)   |  min(powerfactorb)   |
               6.641772019 |           2790.00000 |              0.91000 |
Query OK, 1 row(s) in set (0.838616s)
10次连续查询结果返回均在0.83s秒左右；
### top命令平常服务器cpu/内存情况
top - 15:44:06 up 56 days, 22:55,  2 users,  load average: 0.02, 0.06, 0.01
Tasks: 161 total,   1 running, 160 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.1 us,  0.1 sy,  0.0 ni, 99.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  15875.7 total,   8376.2 free,   1957.2 used,   5542.2 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  13638.5 avail Mem 
taos查询的时候，显示cpu使用率会显著上升到50%+，内存占比达到12%+，检索完毕会立刻回降，
iowait占比在查询过程中变化不大，最大达到过0.2 wa
### 我的问题
我的使用场景是做智慧城市，智能电表这一块，tdengine用来存储收集到的参数，预估未来使用前期就会有将近1万张表；
600多万的数据聚合查询将近一秒钟对我的业务场景来说效率有点低，所以我想请专业人员帮我看看如何提高效率？
28号的直播我看了，100亿的数据聚合查询将近3秒，可是我这600多万就快1秒了，应该如何调试？
### 后续
后面我还会继续测试然后把测试结果贴上来，慢慢增加子表的数量以及数据量到更多，谢谢

**Comment by hjxilinx** [comment]
有可能是数据块的 block 太小导致数据块太多，所以对于性能有影响。您可以按一下步骤操作，然后将日志提供给我们分析：
1. 设置 debugFlag 135
2. 重启 taosd
3. 执行查询，然后将日志的最后的100万行（压缩以后）提供给我们。
