### ISSUE TITLE
操作TD提示Invalid Vgroup ID

### ISSUE THREAD

**Issue by yebel1120** [taosdata/TDengine#3729]
最初目的是想从A服务器访问B服务器的TD
1.修改taos.cfg配置文件
```bash
# first fully qualified domain name (FQDN) for TDengine system
firstEp                 192.168.11.172:6030

# second fully qualified domain name (FQDN) for TDengine system, for cluster only
# secondEp              cluster_hostname2:6030

# local fully qualified domain name (FQDN)
fqdn                    192.168.11.172

# first port number for the connection (12 continuous UDP/TCP port number are used) 
serverPort              6030
```
2.重启TD，在B服务器上进行TD操作，提示DB error: Invalid Vgroup ID
```sql
Welcome to the TDengine shell from Linux, Client Version:2.0.4.0
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

taos> use test;
Database changed.

taos> select * from d1001;

DB error: Invalid Vgroup ID
```
DB error: Invalid Vgroup ID应该如何处理？？

日志如下
[taosdlog.0.txt](https://github.com/taosdata/TDengine/files/5297590/taosdlog.0.txt)
[taoslog0.0.txt](https://github.com/taosdata/TDengine/files/5297594/taoslog0.0.txt)

**Comment by xiaopingcs** [comment]
你好，你这个是单机不是集群，是吧？如果是单机的话，基本不需要修改taos.cfg。你把修改的配置注释掉，然后重启taosd试试，重启之前最后把127.0.0.1 hostname加入到/etc/hosts文件中。这样应该不会有问题。如果你需要配置集群，可以参考一下这篇文章： https://www.taosdata.com/blog/2020/09/11/1824.html

**Comment by yebel1120** [comment]
user@user:/etc$ cat hosts
127.0.0.1 localhost
127.0.1.1 user

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

hosts文件上原来已经有127.0.0.1。还原taos.cfg，A服务器访问不了B上的TD，会提示TDengine Error: Unable to resolve FQDN

**Comment by xiaopingcs** [comment]
这是很常见的问题，我们的官网FAQ也有回答。A服务器上的host文件也需要修改，需要添加B服务器的ip hostname到A服务器的/etc/hosts文件就没有问题了，不需要修改taos.cfg文件

**Comment by yebel1120** [comment]
理解了，没配好A的hosts。谢谢
