### ISSUE TITLE
error: alter user developer priviledge 'write'

### ISSUE THREAD

**Issue by quchunhui** [taosdata/TDengine#3736]
按照官网的提示，执行修改用户权限的语句提示错误；
怀疑官网的priviledge拼写错误，所以尝试了privilege，一样失败。 
taos> alter user developer privilege 'write';

DB error: invalid SQL: invalid user rights
taos> alter user developer priviledge 'write';

DB error: syntax error near "priviledge 'write';"

**Comment by xiaopingcs** [comment]
ALTER USER admin PRIVILEGE read;  
去掉单引号就可以了，文档可能会让人误解，我们会更新一下。麻烦试一下，如果没有问题，请把这个issue关掉。谢谢

**Comment by quchunhui** [comment]
已解决。

**Comment by windsome** [comment]
docker方式运行tdengine/tdengine:3.0.1.4，修改用户权限，不管是用`priviledge`还是`privilege`都报错。
```
taos> ALTER USER test PRIVILEDGE write;

DB error: syntax error near "priviledge write;" (0.000125s)
taos> ALTER USER test PRIVILEGE write;

DB error: syntax error near "privilege write;" (0.000118s)

```

**Comment by yu285** [comment]
https://docs.taosdata.com/taos-sql/grant/
