### ISSUE TITLE
V2.0.4.0 , client driver exception：tscUtil.c:427: tscFreeSqlObj: Assertion `ref >= 0' failed.

### ISSUE THREAD

**Issue by rennner** [taosdata/TDengine#3737]
使用C#调研客户端驱动，秒级写入数据，运行一会儿后就报错，导致程序崩溃。
win10内异常如下：
![image](https://user-images.githubusercontent.com/37169223/94652141-23dc0c00-032c-11eb-887e-c55e8aaeb610.png)

Centos7中报错如下：
![image](https://user-images.githubusercontent.com/37169223/94652258-4cfc9c80-032c-11eb-8a25-e55ce350d000.png)

程序执行的插入语句类似这种：
insert into  th_ys_dd_scyx_func_cs using taghistory tags ('ys.dd.scyx_func-cs') values ('2020-09-30 14:51:20','0.25829825',1,'0.40759492') 
 th_ys_dd_scyx_tag using taghistory tags ('ys.dd.scyx_tag') values ('2020-09-30 14:51:20','0.25829825',1,'0.40759492') 
 th_ys_dd_scyx_var using taghistory tags ('ys.dd.scyx_var') values ('2020-09-30 14:51:20','0.411905',1,'0.40789968') 
 th_ys_dd_scyx_func_s using taghistory tags ('ys.dd.scyx_func-s') values ('2020-09-30 14:51:20','25.829824',1,'40.75949') 

超级表定义如下：
create table if not exists TagHistory (time timestamp, Value binary(20), Qualitie TINYINT, PreValue binary(20)) tags (Tagid nchar(100))

**Comment by rennner** [comment]
请问这个问题在2.0.5中有没有解决，目前产品想支持taosdb，但总有各种问题无法继续，

**Comment by winder9090** [comment]
同样碰到这个问题

**Comment by hjxilinx** [comment]
请问是只有 C#客户端有问题吗？

**Comment by hjxilinx** [comment]
@winder9090 请问您也是用的C#

**Comment by guanshengliang** [comment]
请 @hjxilinx  来处理

**Comment by winder9090** [comment]
> 请问是只有 C#客户端有问题吗？

是，在win10 上用的Maikebing.Data.Taos连接

**Comment by hjxilinx** [comment]
@rennner 您的也是使用的 Maikebing.Data.Taos 来连接处理遇到的问题吗？

**Comment by hjxilinx** [comment]
@winder9090 ，您测试过非 c#的驱动吗？

**Comment by winder9090** [comment]
> @winder9090 ，您测试过非 c#的驱动吗？
没有

**Comment by hjxilinx** [comment]
这个问题容易出吗？方便我们远程检查一下吗？

**Comment by rennner** [comment]
@hjxilinx 也是使用的 Maikebing.Data.Taos

**Comment by hjxilinx** [comment]
为什么你的截图中有个 CentOS 的截图？在 Linux 中也有问题吗？

**Comment by rennner** [comment]
对。win10和linux一样的错误。

**Comment by hjxilinx** [comment]
我方便远程看一下吗?Linux环境下的错误

**Comment by rennner** [comment]
明天可以吗，我需要准备一下环境。方便留个邮箱吗，我加你微信

**Comment by hjxilinx** [comment]
hjliao@taosdata.com

**Comment by rennner** [comment]
已发邮件

**Comment by winder9090** [comment]
这问题解决了吗

**Comment by hjxilinx** [comment]
C#驱动存在两次关闭连接的问题，需要 @maikebing 修复一下这个问题。
我已经将容错两次关闭的代码合并到 release/s102分支中（对应2.0.4.0）版本。
在下周发布的版本中也已经整合。@rennner @winder9090

**Comment by rennner** [comment]
@maikebing 给您提了一个issue

**Comment by hjxilinx** [comment]
@winder9090 , pull release/s103分支的 最新代码然后自己编译一个版本就行。
