### ISSUE TITLE
tdengine-windows-client-x64-1.6.1.6.exe中没有jdbc的驱动包

### ISSUE THREAD

**Issue by zkitcast** [taosdata/TDengine#374]
tdengine-windows-client-x64-1.6.1.6.exe安装完毕后，在安装目录下并没有jdbc的驱动包。
求大佬分享一个TDengine的驱动包，邮箱theday226@126.com

**Comment by guanshengliang** [comment]
linux和windows的jdbc驱动是相同的，因此windows在编译的时候没有将jdbc打到压缩包里面。

暂时您先从linux中拷贝过来使用。

下次发版本时，我们会将jdbc打到windows包里面。
