### ISSUE TITLE
2.0.4.0-incompitable between taos or taosd binary built from source with official release

### ISSUE THREAD

**Issue by lyc10000h** [taosdata/TDengine#3740]
编译出来的taos程序，在build/build/bin目录通过命令：
./taos -c ../../test/cfg -h <ip>
连接远程taosd，如果是自编译版本，则可以正常使用；如果是官方发布的，则tao 程序core dump，输出：
taos: .../TDengine/src/util/src/tarray.c:95: taosArrayGetP: Assertion `index < pArray->size' failed.
已放弃 (core dumped)

是本来就不兼容，还是编译时有相关参数，还是其他原因？
以上测试都是使用2.0.4.0，在centos和ubuntu下编译测试都是这样的结果

**Comment by sangshuduo** [comment]
不建议混合使用正式发布版本和自己编译的二进制
