### ISSUE TITLE
偶发性down掉

### ISSUE THREAD

**Issue by lnparker** [taosdata/TDengine#375]
错误信息如下：TDengine/src/client/src/tscServer.c:538: tscLaunchMetricSubQueries: Assertion `numOfVnodes > 0' failed.

**Comment by lnparker** [comment]
@fangpanpan @hjxilinx 请问是这个是个已知问题还是什么情况？

**Comment by hjxilinx** [comment]
这个问题应该是错误流程中没有正确处理，还请提供更多的信息便于我们解决这个问题。

**Comment by lnparker** [comment]
基于空数据的超级表创建连续查询，数据库到计算查询的时间点就会挂掉
