### ISSUE TITLE
centos7+go1.15.2+libtaos.so.2.0.4.0, run driver_test.go failed at taos_connect()!

### ISSUE THREAD

**Issue by zskylark** [taosdata/TDengine#3751]
对go的支持很差，go的驱动也只能支持linux下编译，win下编译不出来与之cgo配合的库。
我在centos7下跑driver_test.go报错： taos_connect() fail!
db, err := sql.Open(DRIVER_NAME, dataSourceName)
if err != nil {
	t.Fatalf("error on:  sql.open %s", err.Error())
	return
}
defer db.Close()
dbt := &DBTest{t, db}
// prepare data
dbt.db.Exec("DROP TABLE IF EXISTS test")  <-- 执行到此处必报错：taos_connect() fail!
另外，直接用taos连数据库没问题，说明地址和端口没错，服务器也没问题。

**Comment by sangshuduo** [comment]
可以跑一下 TDengine/tests/examples/go 试一下吗？
