### ISSUE TITLE
"show tables" command, table_name column incomplete display

### ISSUE THREAD

**Issue by tianyu94** [taosdata/TDengine#3754]
**Bug Description**
`show tables` 命令显示的表名只能显示30个字符，但文档里说明“支持表名最大长度为193”，希望能改进这个地方，避免容易出现 table not exists 的低级错误（本人 show tables 时根据打印的表名来操作，因此造成了此问题）

**To Reproduce**
1. Go to 'enter taos command line'
2. Type in `show tables;`
3. See error, **If table name greater than 30 length, will cause incomplete display**

**Expected Behavior**
full table name

**Screenshots**
None

**Environment (please complete the following information):**
 - OS: [CentOS 8.0]
 - TDengine Version [2.0.4.0]

**Additional Context**
None

**Comment by sangshuduo** [comment]
试试：show tables\\G;

**Comment by tianyu94** [comment]
> 试试：show tables\G;

好的，Thx

```
taos> show tables\G;
*************************** 1.row ***************************
  table_name: test_1jklsdfjsdlkj12k4kljkfldsf1234jkldf
created_time: 2020-10-07 09:40:35.053
     columns: 2
 stable_name: 
*************************** 2.row ***************************
  table_name: test_2jklsdfjsdlkj12k4kljkfldsf1234jkldf
created_time: 2020-10-07 09:40:59.558
     columns: 2
 stable_name: 
Query OK, 2 row(s) in set (0.000947s)
```
