### ISSUE TITLE
how use Windows client connect to the TDengine server on Linux machine?

### ISSUE THREAD

**Issue by yuqidi** [taosdata/TDengine#3758]
初次使用TDengine，在Linux服务器部署了TDengine，如何在本地Windows系统上访问并使用TDengine数据库，哪位给详细说下，谢谢谢谢！ 本地已经下载了Windows客户端并且安装了python连接包，但是还是提示我连接失败，求指导！

**Comment by moziie** [comment]
连接失败一般就是防火墙或端口的问题呀，你可以把连接失败截图呀日志呀弄上来看看

**Comment by sangshuduo** [comment]
https://www.taosdata.com/blog/2020/09/11/1824.html

**Comment by Aries-Lee1991** [comment]
@yuqidi 如上所说，按照我们给的这篇博客，您的问题得到解决了吗？
