### ISSUE TITLE
Does TD 1.6 support previous timestamp insertion

### ISSUE THREAD

**Issue by ll10020163** [taosdata/TDengine#3772]
TD1.6 
数据最后一条插入的时间是   '2020-02-28 16:35:17.000'。
需要插入  '2020-02-28 16:35:17.000'  之前的数据 例如ts   '2020-02-28 16:35:16.000'  是插入不进去的是吧？ 我测试是无法插入的。
但是 目前TD 2.0 是支持的。

仅仅确认下。

如果TD1.6 想插入之前时间的数据还有其他方法么？

**Comment by hzcheng** [comment]
1.6支持过往时间插入，不过需要用import命令，而不是insert命令。建议您升级使用2.0。2.0对于乱序数据的支持要比1.6好非常多，且2.0中去除了import命令，insert命令就可以插入顺序数据和历史数据。

**Comment by ll10020163** [comment]
> 1.6支持过往时间插入，不过需要用import命令，而不是insert命令。建议您升级使用2.0。2.0对于乱序数据的支持要比1.6好非常多，且2.0中去除了import命令，insert命令就可以插入顺序数据和历史数据。

多谢

**Comment by ll10020163** [comment]
> 1.6支持过往时间插入，不过需要用import命令，而不是insert命令。建议您升级使用2.0。2.0对于乱序数据的支持要比1.6好非常多，且2.0中去除了import命令，insert命令就可以插入顺序数据和历史数据。

测试了下  TD2.0.4.0  版本  import 还是可以使用的是考虑到兼容TD1.6 么？

**Comment by hzcheng** [comment]
是为了1.6的兼容，不过文档中已经删除。
