### ISSUE TITLE
springboot项目使用2.0.4.0驱动和java1.8无法连接数据库，提示no taos in java.library.path；使用java11就可以了

### ISSUE THREAD

**Issue by SuyunGit** [taosdata/TDengine#3775]
springboot的项目，开发环境是win10，已经安装了2.0.4.0的客户端，库环境正常，数据库服务端在centos7上，版本2.0.4.0，无论在服务器上还是在win10上使用taos命令都能连接数据库并正常使用，但是在项目中，项目驱动版本是2.0.4.0，jdk1.8时就提示“no taos in java.library.path”，把jdk版本改成11或更高的版本，就能正常连接查询。并且TDengine客户端提供的demo中，也是同样的问题。请问高版本不支持java1.8吗？我部署数据库时看到的是支持1.8版本的。

**Comment by zyyang-taosdata** [comment]
你可能使用了taos-jdbcdriver-2.0.2版本的jdbc driver。请尝试修改你maven依赖，将taos-jdbcdriver的版本改为2.0.4。

**Comment by SuyunGit** [comment]
> 你可能使用了taos-jdbcdriver-2.0.2版本的jdbc driver。请尝试修改你maven依赖，将taos-jdbcdriver的版本改为2.0.7。

我之前使用的是2.0.4版本的，刚刚改成2.0.7的版本，jdk改回1.8，springboot项目似乎没什么问题了，但是jdbc的demo还是不行

**Comment by zyyang-taosdata** [comment]
如果你是使用test/example/connector/JDBC里的测试代码，检查你的pom.xml，确认没有使用java11的编译级别。如果你是IDEA开发环境，可能得检查你的编译器是否设置java 11的编译级别。或者，你可以贴一下你报错的截图。

**Comment by SuyunGit** [comment]
`"C:\Program Files (x86)\Java\jdk1.8.0_261\bin\java.exe" -javaagent:C:\Users\suyun\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\202.7319.50\lib\idea_rt.jar=52239:C:\Users\suyun\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\202.7319.50\bin -Dfile.encoding=UTF-8 -classpath "C:\Program Files (x86)\Java\jdk1.8.0_261\jre\lib\charsets.jar;C:\Program Files (x86)\Java\jdk1.8.0_261\jre\lib\deploy.jar;C:\Program Files (x86)\Java\jdk1.8.0_261\jre\lib\ext\access-bridge-32.jar;C:\Program Files (x86)\Java\jdk1.8.0_261\jre\lib\ext\cldrdata.jar;C:\Program Files (x86)\Java\jdk1.8.0_261\jre\lib\ext\dnsns.jar;C:\Program Files (x86)\Java\jdk1.8.0_261\jre\lib\ext\jaccess.jar;C:\Program Files (x86)\Java\jdk1.8.0_261\jre\lib\ext\jfxrt.jar;C:\Program Files (x86)\Java\jdk1.8.0_261\jre\lib\ext\localedata.jar;C:\Program Files (x86)\Java\jdk1.8.0_261\jre\lib\ext\nashorn.jar;C:\Program Files (x86)\Java\jdk1.8.0_261\jre\lib\ext\sunec.jar;C:\Program Files (x86)\Java\jdk1.8.0_261\jre\lib\ext\sunjce_provider.jar;C:\Program Files (x86)\Java\jdk1.8.0_261\jre\lib\ext\sunmscapi.jar;C:\Program Files (x86)\Java\jdk1.8.0_261\jre\lib\ext\sunpkcs11.jar;C:\Program Files (x86)\Java\jdk1.8.0_261\jre\lib\ext\zipfs.jar;C:\Program Files (x86)\Java\jdk1.8.0_261\jre\lib\javaws.jar;C:\Program Files (x86)\Java\jdk1.8.0_261\jre\lib\jce.jar;C:\Program Files (x86)\Java\jdk1.8.0_261\jre\lib\jfr.jar;C:\Program Files (x86)\Java\jdk1.8.0_261\jre\lib\jfxswt.jar;C:\Program Files (x86)\Java\jdk1.8.0_261\jre\lib\jsse.jar;C:\Program Files (x86)\Java\jdk1.8.0_261\jre\lib\management-agent.jar;C:\Program Files (x86)\Java\jdk1.8.0_261\jre\lib\plugin.jar;C:\Program Files (x86)\Java\jdk1.8.0_261\jre\lib\resources.jar;C:\Program Files (x86)\Java\jdk1.8.0_261\jre\lib\rt.jar;C:\TDengine\examples\JDBC\JDBCDemo\target\classes;C:\Users\suyun\Workstation\repository\maven\com\taosdata\jdbc\taos-jdbcdriver\2.0.7\taos-jdbcdriver-2.0.7.jar;C:\Users\suyun\Workstation\repository\maven\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;C:\Users\suyun\Workstation\repository\maven\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar" TSDBSyncSample
Arguments format: host tables loop batchs
---------------------------------------------------------------
Start testing...
---------------------------------------------------------------

JDBC URL to use:
jdbc:TAOS://192.168.1.37:6030/?user=root&password=taosdata

---------------------------------------------------------------
Start creating databases and tables...
Exception in thread "main" java.lang.UnsatisfiedLinkError: no taos in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.taosdata.jdbc.TSDBJNIConnector.<clinit>(TSDBJNIConnector.java:25)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:193)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at TSDBSyncSample.doCreateDbAndTable(TSDBSyncSample.java:84)
	at TSDBSyncSample.main(TSDBSyncSample.java:44)

Process finished with exit code 1
`
这是驱动版本为2.0.7的报错信息，用的是jdbcdemo测试的

**Comment by zyyang-taosdata** [comment]
这个no taos in java.library.path报错是说没有找到你的taos.dll，检查C:\\windows\System32目录下是否有taos.dl这个本地方法库

**Comment by SuyunGit** [comment]
检查了很多次，这个库肯定是有的，而且我还把2.0.4.0版本的客户端安装包里面的库复制替换过，以确保版本正确

**Comment by zyyang-taosdata** [comment]
在微信群里么？我远程帮你看一下吧

**Comment by 419845351** [comment]
我也有这个问题，在服务器上使用docker安装了tdengine。再使用springbootdemo连接不上。能帮我看一下吗。419845351，谢谢。

**Comment by zyyang-taosdata** [comment]
> 我也有这个问题，在服务器上使用docker安装了tdengine。再使用springbootdemo连接不上。能帮我看一下吗。419845351，谢谢。

参考一下这个文档吧
https://github.com/taosdata/TDengine/blob/develop/tests/examples/JDBC/JDBCDemo/README-jdbc-windows.md

**Comment by SuyunGit** [comment]
真的是很奇怪，开发工具是idea，java是1.8，不管是使用连接池还是直接JDBC，在`System.loadLibrary("taos");`时，总是会报错：`no taos in java.library.path`，然后我将`System.getProperty("java.library.path")`信息在数据库进行连接之前打印出来为：`C:\Windows\System32`；当我切换到jdk11时，同样在连接之前打印出`System.getProperty("java.library.path")`，发现是和Java1.8是一样的，但是`System.loadLibrary("taos");`语句就会正常加载库，真的是求解 @zyyang-taosdata

**Comment by zyyang-taosdata** [comment]
您好，这个是因为我们发布jdbc安装包编译时候的历史问题了，请更新到最新的jdbc版本就可以了。目前最新的是taos-jdbcdriver-2.0.9

**Comment by zyyang-taosdata** [comment]
> 真的是很奇怪，开发工具是idea，java是1.8，不管是使用连接池还是直接JDBC，在`System.loadLibrary("taos");`时，总是会报错：`no taos in java.library.path`，然后我将`System.getProperty("java.library.path")`信息在数据库进行连接之前打印出来为：`C:\Windows\System32`；当我切换到jdk11时，同样在连接之前打印出`System.getProperty("java.library.path")`，发现是和Java1.8是一样的，但是`System.loadLibrary("taos");`语句就会正常加载库，真的是求解 @zyyang-taosdata

您好，这个是因为我们发布jdbc安装包编译时候的历史问题了，请更新到最新的jdbc版本就可以了。目前最新的是taos-jdbcdriver-2.0.9

**Comment by SuyunGit** [comment]
咱们说的不是一个问题，不过我的问题解决了。是我大意了，居然用了32位的jdk，不好意思，给你们添麻烦了

**Comment by holypost** [comment]
> > 真的是很奇怪，开发工具是idea，java是1.8，不管是使用连接池还是直接JDBC，在`System.loadLibrary("taos");`时，总是会报错：`no taos in java.library.path`，然后我将`System.getProperty("java.library.path")`信息在数据库进行连接之前打印出来为：`C:\Windows\System32`；当我切换到jdk11时，同样在连接之前打印出`System.getProperty("java.library.path")`，发现是和Java1.8是一样的，但是`System.loadLibrary("taos");`语句就会正常加载库，真的是求解 @zyyang-taosdata
> 
> 您好，这个是因为我们发布jdbc安装包编译时候的历史问题了，请更新到最新的jdbc版本就可以了。目前最新的是taos-jdbcdriver-2.0.9

`<dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>3.2.11</version>
        </dependency>`

还是这样的问题，不知道怎么解决了，我JDK 17，td server是3.3.0.0

![image](https://github.com/taosdata/TDengine/assets/154062060/c66aa193-22ab-41d0-91aa-48f03cbb3a3a)
