### ISSUE TITLE
RPC ERROR TSC 0000024FDAD7D620 0000024FDB02E8D0, failed to send, msgLen:96 written:-1, reason:No error

### ISSUE THREAD

**Issue by apesmall** [taosdata/TDengine#3776]
windows10下，可以连接上TDengine，但是没办法使用数据库，查看都不行。虚拟机上可以创建查看。看了客户端日志，报如下错误：RPC ERROR TSC 0000024FDAD7D620 0000024FDB02E8D0, failed to send, msgLen:96 written:-1, reason:No error

**Comment by yihaoDeng** [comment]
这个是window上的client 去连接linux上的server?

**Comment by apesmall** [comment]
> 这个是window上的client 去连接linux上的server?

是的，这个日志也是window上的日志。

**Comment by apesmall** [comment]
问题解决了，降低版本后没有这个问题了。之前用的2.0.1.1，现在换成1.6.6.1就没有这种情况了
