### ISSUE TITLE
The restful interface dynamically creates sub-table, the table name is created incorrectly

### ISSUE THREAD

**Issue by codering** [taosdata/TDengine#3781]
**Bug Description**
通过restful方式动态创建子表，表名超过32个字符，创建后表名不正确。通过toas客户端查看超级表的所有子表发现每个表名只有32个字符， 单独查看子表，会提示表不存在。

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [docker]
 - Memory, CPU, current Disk Space
 - TDengine Version [2.0.4.0]

**Additional Context**

**Comment by codering** [comment]
是客户端显示问题，超过32位的都显示不全。

**Comment by guanshengliang** [comment]
show tables 语句确实只显示前32个字符。
您的这个问题，与使用哪种接口，没有关系。但为了验证您的问题，您可以将SQL语句贴出来。我来验证一下，是否存在此现象。

**Comment by codering** [comment]
我看了，是显示的问题

**Comment by guanshengliang** [comment]
好的，那我来将这个问题关闭。
