### ISSUE TITLE
driver-go: could not determine kind of name for C.taos_fetch_lengths

### ISSUE THREAD

**Issue by songtianyi** [taosdata/TDengine#3789]
**Bug Description**
Go build error when import  github.com/taosdata/driver-go/taosSql

**To Reproduce**
edit `t.go`
```go
package main

import (
	_ "github.com/taosdata/driver-go/taosSql"
)

func main() {

}
```
run this file with module off
```
GO111MODULE=off go run t.go
```

**Expected Behavior**
program exit without error 

**Screenshots**
```
[root@nap-99 ~]# GO111MODULE=off go run t.go
# github.com/taosdata/driver-go/taosSql
go/src/src/github.com/taosdata/driver-go/taosSql/result.go:94:12: could not determine kind of name for C.taos_fetch_lengths
```

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version **tdengine-1.6.3.0-3.x86_64**

**Additional Context**

**Comment by localvar** [comment]
As v2.0 is released two months ago, please upgrade TDengine to latest version and try again.
