### ISSUE TITLE
python3连接TDengine失败（connect to TDengine failed）

### ISSUE THREAD

**Issue by wyy5763** [taosdata/TDengine#379]
执行read_example.py报错

connect to TDengine failed
connection is closed
Traceback (most recent call last):
  File "****\TDengine-master\tests\examples\python\read_example.py", line 35, in <module>
    raise(err)
  File "*****\TDengine-master\tests\examples\python\read_example.py", line 32, in <module>
    c1.execute('create database db')
  File "C:\Python37\lib\site-packages\taos\cursor.py", line 121, in execute
    raise ProgrammingError(CTaosInterface.errStr(self._connection._conn))
taos.error.ProgrammingError: login disconnected, login again

**Comment by wyy5763** [comment]
环境：win10 64位
客户端：tdengine-windows-client-x64-1.6.1.5.exe
python版本：3.7.2
taos模块安装成功
![image](https://user-images.githubusercontent.com/54097903/63163030-d4b71700-c056-11e9-8424-831baedbc17b.png)

**Comment by fangpanpan** [comment]
您用taos -h "host" 能连上server吗？

**Comment by wyy5763** [comment]
![image](https://user-images.githubusercontent.com/54097903/63212195-41074880-c133-11e9-8d97-9ffe135c1c12.png)
服务端版本（安装在Linux系统上）：server version:1.5.2.10  client version:1.5.2.10
客户端版本（安装win10系统上）： client version:1.6.1.5

**Comment by fangpanpan** [comment]
客户端版本需要和服务端版本一致才行。

**Comment by yiluohan1234** [comment]
我之前也遇到过这个问题，能不能做下版本的兼容

**Comment by fangpanpan** [comment]
> 我之前也遇到过这个问题，能不能做下版本的兼容

谢谢您的意见，目前我们的代码偶有改动所以需要服务端和客户端版本一致，以后我们会考虑版本的兼容的。

**Comment by Janus-Xu** [comment]
@fangpanpan win客户端版本和ubundu的server版本一致，可还是连不上，是什么原因？
![image](https://user-images.githubusercontent.com/6883877/63663473-17b28080-c7f5-11e9-9edb-97ab9e1cee96.png)
![image](https://user-images.githubusercontent.com/6883877/63663487-2436d900-c7f5-11e9-8d9a-93ee69c52319.png)
python接口调用也是一样问题
![image](https://user-images.githubusercontent.com/6883877/63663511-3b75c680-c7f5-11e9-98a2-e27bad144d7d.png)

**Comment by fangpanpan** [comment]
> @fangpanpan win客户端版本和ubundu的server版本一致，可还是连不上，是什么原因？
> ![image](https://user-images.githubusercontent.com/6883877/63663473-17b28080-c7f5-11e9-9edb-97ab9e1cee96.png)
> ![image](https://user-images.githubusercontent.com/6883877/63663487-2436d900-c7f5-11e9-8d9a-93ee69c52319.png)
> python接口调用也是一样问题
> ![image](https://user-images.githubusercontent.com/6883877/63663511-3b75c680-c7f5-11e9-98a2-e27bad144d7d.png)
您可以在win电脑上先用ping检查一下“192.168.2.89”网络连接吗？

**Comment by Janus-Xu** [comment]
> > @fangpanpan win客户端版本和ubundu的server版本一致，可还是连不上，是什么原因？
> > ![image](https://user-images.githubusercontent.com/6883877/63663473-17b28080-c7f5-11e9-9edb-97ab9e1cee96.png)
> > ![image](https://user-images.githubusercontent.com/6883877/63663487-2436d900-c7f5-11e9-8d9a-93ee69c52319.png)
> > python接口调用也是一样问题
> > ![image](https://user-images.githubusercontent.com/6883877/63663511-3b75c680-c7f5-11e9-98a2-e27bad144d7d.png)
> > 您可以在win电脑上先用ping检查一下“192.168.2.89”网络连接吗？

ping通的
![image](https://user-images.githubusercontent.com/6883877/63665281-43396900-c7fd-11e9-88de-08f796e65d5f.png)

**Comment by fangpanpan** [comment]
> > > @fangpanpan win客户端版本和ubundu的server版本一致，可还是连不上，是什么原因？
> > > ![image](https://user-images.githubusercontent.com/6883877/63663473-17b28080-c7f5-11e9-9edb-97ab9e1cee96.png)
> > > ![image](https://user-images.githubusercontent.com/6883877/63663487-2436d900-c7f5-11e9-8d9a-93ee69c52319.png)
> > > python接口调用也是一样问题
> > > ![image](https://user-images.githubusercontent.com/6883877/63663511-3b75c680-c7f5-11e9-98a2-e27bad144d7d.png)
> > > 您可以在win电脑上先用ping检查一下“192.168.2.89”网络连接吗？
> 
> ping通的
> ![image](https://user-images.githubusercontent.com/6883877/63665281-43396900-c7fd-11e9-88de-08f796e65d5f.png)

那C:\TDengine 下的日志里报了什么错误吗？

**Comment by Janus-Xu** [comment]
> > > > @fangpanpan win客户端版本和ubundu的server版本一致，可还是连不上，是什么原因？
> > > > ![image](https://user-images.githubusercontent.com/6883877/63663473-17b28080-c7f5-11e9-9edb-97ab9e1cee96.png)
> > > > ![image](https://user-images.githubusercontent.com/6883877/63663487-2436d900-c7f5-11e9-8d9a-93ee69c52319.png)
> > > > python接口调用也是一样问题
> > > > ![image](https://user-images.githubusercontent.com/6883877/63663511-3b75c680-c7f5-11e9-98a2-e27bad144d7d.png)
> > > > 您可以在win电脑上先用ping检查一下“192.168.2.89”网络连接吗？
> > 
> > 
> > ping通的
> > ![image](https://user-images.githubusercontent.com/6883877/63665281-43396900-c7fd-11e9-88de-08f796e65d5f.png)
> 
> 那C:\TDengine 下的日志里报了什么错误吗？

每次发请求log里只有这个信息：
![image](https://user-images.githubusercontent.com/6883877/63666395-eb513100-c801-11e9-8a02-229f91abe7aa.png)

**Comment by fangpanpan** [comment]
> > > > > @fangpanpan win客户端版本和ubundu的server版本一致，可还是连不上，是什么原因？
> > > > > ![image](https://user-images.githubusercontent.com/6883877/63663473-17b28080-c7f5-11e9-9edb-97ab9e1cee96.png)
> > > > > ![image](https://user-images.githubusercontent.com/6883877/63663487-2436d900-c7f5-11e9-8d9a-93ee69c52319.png)
> > > > > python接口调用也是一样问题
> > > > > ![image](https://user-images.githubusercontent.com/6883877/63663511-3b75c680-c7f5-11e9-98a2-e27bad144d7d.png)
> > > > > 您可以在win电脑上先用ping检查一下“192.168.2.89”网络连接吗？
> > > 
> > > 
> > > ping通的
> > > ![image](https://user-images.githubusercontent.com/6883877/63665281-43396900-c7fd-11e9-88de-08f796e65d5f.png)
> > 
> > 
> > 那C:\TDengine 下的日志里报了什么错误吗？
> 
> 每次发请求log里只有这个信息：
> ![image](https://user-images.githubusercontent.com/6883877/63666395-eb513100-c801-11e9-8a02-229f91abe7aa.png)

这个code:0是成功的。您能将日志全部打开吗？就是在/etc/taos/taos.cfg里加上debugflag 135

**Comment by Janus-Xu** [comment]
> > > > > > @fangpanpan win客户端版本和ubundu的server版本一致，可还是连不上，是什么原因？
> > > > > > ![image](https://user-images.githubusercontent.com/6883877/63663473-17b28080-c7f5-11e9-9edb-97ab9e1cee96.png)
> > > > > > ![image](https://user-images.githubusercontent.com/6883877/63663487-2436d900-c7f5-11e9-8d9a-93ee69c52319.png)
> > > > > > python接口调用也是一样问题
> > > > > > ![image](https://user-images.githubusercontent.com/6883877/63663511-3b75c680-c7f5-11e9-98a2-e27bad144d7d.png)
> > > > > > 您可以在win电脑上先用ping检查一下“192.168.2.89”网络连接吗？
> > > > 
> > > > 
> > > > ping通的
> > > > ![image](https://user-images.githubusercontent.com/6883877/63665281-43396900-c7fd-11e9-88de-08f796e65d5f.png)
> > > 
> > > 
> > > 那C:\TDengine 下的日志里报了什么错误吗？
> > 
> > 
> > 每次发请求log里只有这个信息：
> > ![image](https://user-images.githubusercontent.com/6883877/63666395-eb513100-c801-11e9-8a02-229f91abe7aa.png)
> 
> 这个code:0是成功的。您能将日志全部打开吗？就是在/etc/taos/taos.cfg里加上debugflag 135

打开了，您看下
![image](https://user-images.githubusercontent.com/6883877/63667447-5b61b600-c806-11e9-8abf-3cca017c4814.png)

**Comment by fangpanpan** [comment]
> > > > > > > @fangpanpan win客户端版本和ubundu的server版本一致，可还是连不上，是什么原因？
> > > > > > > ![image](https://user-images.githubusercontent.com/6883877/63663473-17b28080-c7f5-11e9-9edb-97ab9e1cee96.png)
> > > > > > > ![image](https://user-images.githubusercontent.com/6883877/63663487-2436d900-c7f5-11e9-8d9a-93ee69c52319.png)
> > > > > > > python接口调用也是一样问题
> > > > > > > ![image](https://user-images.githubusercontent.com/6883877/63663511-3b75c680-c7f5-11e9-98a2-e27bad144d7d.png)
> > > > > > > 您可以在win电脑上先用ping检查一下“192.168.2.89”网络连接吗？
> > > > > 
> > > > > 
> > > > > ping通的
> > > > > ![image](https://user-images.githubusercontent.com/6883877/63665281-43396900-c7fd-11e9-88de-08f796e65d5f.png)
> > > > 
> > > > 
> > > > 那C:\TDengine 下的日志里报了什么错误吗？
> > > 
> > > 
> > > 每次发请求log里只有这个信息：
> > > ![image](https://user-images.githubusercontent.com/6883877/63666395-eb513100-c801-11e9-8a02-229f91abe7aa.png)
> > 
> > 
> > 这个code:0是成功的。您能将日志全部打开吗？就是在/etc/taos/taos.cfg里加上debugflag 135
> 
> 打开了，您看下
> ![image](https://user-images.githubusercontent.com/6883877/63667447-5b61b600-c806-11e9-8abf-3cca017c4814.png)

这个客户端的日志没有看出什么？server端的日志您能再看看吗？日志太多的话，您可以将/var/log/taos/下面的东西全清空了再重启taosd。

**Comment by Janus-Xu** [comment]
> > > > > > > > @fangpanpan win客户端版本和ubundu的server版本一致，可还是连不上，是什么原因？
> > > > > > > > ![image](https://user-images.githubusercontent.com/6883877/63663473-17b28080-c7f5-11e9-9edb-97ab9e1cee96.png)
> > > > > > > > ![image](https://user-images.githubusercontent.com/6883877/63663487-2436d900-c7f5-11e9-8d9a-93ee69c52319.png)
> > > > > > > > python接口调用也是一样问题
> > > > > > > > ![image](https://user-images.githubusercontent.com/6883877/63663511-3b75c680-c7f5-11e9-98a2-e27bad144d7d.png)
> > > > > > > > 您可以在win电脑上先用ping检查一下“192.168.2.89”网络连接吗？
> > > > > > 
> > > > > > 
> > > > > > ping通的
> > > > > > ![image](https://user-images.githubusercontent.com/6883877/63665281-43396900-c7fd-11e9-88de-08f796e65d5f.png)
> > > > > 
> > > > > 
> > > > > 那C:\TDengine 下的日志里报了什么错误吗？
> > > > 
> > > > 
> > > > 每次发请求log里只有这个信息：
> > > > ![image](https://user-images.githubusercontent.com/6883877/63666395-eb513100-c801-11e9-8a02-229f91abe7aa.png)
> > > 
> > > 
> > > 这个code:0是成功的。您能将日志全部打开吗？就是在/etc/taos/taos.cfg里加上debugflag 135
> > 
> > 
> > 打开了，您看下
> > ![image](https://user-images.githubusercontent.com/6883877/63667447-5b61b600-c806-11e9-8abf-3cca017c4814.png)
> 
> 这个客户端的日志没有看出什么？server端的日志您能再看看吗？日志太多的话，您可以将/var/log/taos/下面的东西全清空了再重启taosd。

把之前的都清了重启，发了一次请求，截得日志，麻烦您帮看下了
[taosd.log](https://github.com/taosdata/TDengine/files/3540217/taosd.log)

**Comment by fangpanpan** [comment]
您发给我的都是server端的日志。您能再操作一次吗？
在server端：
1. sudo systemctl stop taosd
2. rm -rf /var/log/taos/*
3. sudo systemctl start taosd

在win客户端 重新再连一次“taos -h"。 

然后拜托您将windows电脑上”c:\tdengine\“下的客户端日志 和server端日志一起打包发给我吗？

**Comment by fangpanpan** [comment]
> > > > > > > > > @fangpanpan win客户端版本和ubundu的server版本一致，可还是连不上，是什么原因？
> > > > > > > > > ![image](https://user-images.githubusercontent.com/6883877/63663473-17b28080-c7f5-11e9-9edb-97ab9e1cee96.png)
> > > > > > > > > ![image](https://user-images.githubusercontent.com/6883877/63663487-2436d900-c7f5-11e9-8d9a-93ee69c52319.png)
> > > > > > > > > python接口调用也是一样问题
> > > > > > > > > ![image](https://user-images.githubusercontent.com/6883877/63663511-3b75c680-c7f5-11e9-98a2-e27bad144d7d.png)
> > > > > > > > > 您可以在win电脑上先用ping检查一下“192.168.2.89”网络连接吗？
> > > > > > > 
> > > > > > > 
> > > > > > > ping通的
> > > > > > > ![image](https://user-images.githubusercontent.com/6883877/63665281-43396900-c7fd-11e9-88de-08f796e65d5f.png)
> > > > > > 
> > > > > > 
> > > > > > 那C:\TDengine 下的日志里报了什么错误吗？
> > > > > 
> > > > > 
> > > > > 每次发请求log里只有这个信息：
> > > > > ![image](https://user-images.githubusercontent.com/6883877/63666395-eb513100-c801-11e9-8a02-229f91abe7aa.png)
> > > > 
> > > > 
> > > > 这个code:0是成功的。您能将日志全部打开吗？就是在/etc/taos/taos.cfg里加上debugflag 135
> > > 
> > > 
> > > 打开了，您看下
> > > ![image](https://user-images.githubusercontent.com/6883877/63667447-5b61b600-c806-11e9-8abf-3cca017c4814.png)
> > 
> > 
> > 这个客户端的日志没有看出什么？server端的日志您能再看看吗？日志太多的话，您可以将/var/log/taos/下面的东西全清空了再重启taosd。
> 
> 把之前的都清了重启，发了一次请求，截得日志，麻烦您帮看下了
> [taosd.log](https://github.com/taosdata/TDengine/files/3540217/taosd.log)



您发给我的都是server端的日志。您能不能再操作一次？
server端：
1. sudo systemctl stop taosd
2. rm -rf /var/log/taos/*
3. sudo systemctl start taosd

在windows客户端，清空"c:\TDengine"下的日志，再连一次“taos -h"。 

然后拜托您将server端日志和Windows客户端日志一起打包发给我吗？

**Comment by Janus-Xu** [comment]
> > > > > > > > > > @fangpanpan win客户端版本和ubundu的server版本一致，可还是连不上，是什么原因？
> > > > > > > > > > ![image](https://user-images.githubusercontent.com/6883877/63663473-17b28080-c7f5-11e9-9edb-97ab9e1cee96.png)
> > > > > > > > > > ![image](https://user-images.githubusercontent.com/6883877/63663487-2436d900-c7f5-11e9-8d9a-93ee69c52319.png)
> > > > > > > > > > python接口调用也是一样问题
> > > > > > > > > > ![image](https://user-images.githubusercontent.com/6883877/63663511-3b75c680-c7f5-11e9-98a2-e27bad144d7d.png)
> > > > > > > > > > 您可以在win电脑上先用ping检查一下“192.168.2.89”网络连接吗？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > ping通的
> > > > > > > > ![image](https://user-images.githubusercontent.com/6883877/63665281-43396900-c7fd-11e9-88de-08f796e65d5f.png)
> > > > > > > 
> > > > > > > 
> > > > > > > 那C:\TDengine 下的日志里报了什么错误吗？
> > > > > > 
> > > > > > 
> > > > > > 每次发请求log里只有这个信息：
> > > > > > ![image](https://user-images.githubusercontent.com/6883877/63666395-eb513100-c801-11e9-8a02-229f91abe7aa.png)
> > > > > 
> > > > > 
> > > > > 这个code:0是成功的。您能将日志全部打开吗？就是在/etc/taos/taos.cfg里加上debugflag 135
> > > > 
> > > > 
> > > > 打开了，您看下
> > > > ![image](https://user-images.githubusercontent.com/6883877/63667447-5b61b600-c806-11e9-8abf-3cca017c4814.png)
> > > 
> > > 
> > > 这个客户端的日志没有看出什么？server端的日志您能再看看吗？日志太多的话，您可以将/var/log/taos/下面的东西全清空了再重启taosd。
> > 
> > 
> > 把之前的都清了重启，发了一次请求，截得日志，麻烦您帮看下了
> > [taosd.log](https://github.com/taosdata/TDengine/files/3540217/taosd.log)
> 
> 您发给我的都是server端的日志。您能不能再操作一次？
> server端：
> 
> 1. sudo systemctl stop taosd
> 2. rm -rf /var/log/taos/*
> 3. sudo systemctl start taosd
> 
> 在windows客户端，清空"c:\TDengine"下的日志，再连一次“taos -h"。
> 
> 然后拜托您将server端日志和Windows客户端日志一起打包发给我吗？


包含客户端和服务器端日志，服务器是启动后发了一次请求的log
[taoslog.0-client.log](https://github.com/taosdata/TDengine/files/3540655/taoslog.0-client.log)
[taosdlog.0.server.log](https://github.com/taosdata/TDengine/files/3540657/taosdlog.0.server.log)

**Comment by fangpanpan** [comment]
> > > > > > > > > > > @fangpanpan win客户端版本和ubundu的server版本一致，可还是连不上，是什么原因？
> > > > > > > > > > > ![image](https://user-images.githubusercontent.com/6883877/63663473-17b28080-c7f5-11e9-9edb-97ab9e1cee96.png)
> > > > > > > > > > > ![image](https://user-images.githubusercontent.com/6883877/63663487-2436d900-c7f5-11e9-8d9a-93ee69c52319.png)
> > > > > > > > > > > python接口调用也是一样问题
> > > > > > > > > > > ![image](https://user-images.githubusercontent.com/6883877/63663511-3b75c680-c7f5-11e9-98a2-e27bad144d7d.png)
> > > > > > > > > > > 您可以在win电脑上先用ping检查一下“192.168.2.89”网络连接吗？
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > ping通的
> > > > > > > > > ![image](https://user-images.githubusercontent.com/6883877/63665281-43396900-c7fd-11e9-88de-08f796e65d5f.png)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 那C:\TDengine 下的日志里报了什么错误吗？
> > > > > > > 
> > > > > > > 
> > > > > > > 每次发请求log里只有这个信息：
> > > > > > > ![image](https://user-images.githubusercontent.com/6883877/63666395-eb513100-c801-11e9-8a02-229f91abe7aa.png)
> > > > > > 
> > > > > > 
> > > > > > 这个code:0是成功的。您能将日志全部打开吗？就是在/etc/taos/taos.cfg里加上debugflag 135
> > > > > 
> > > > > 
> > > > > 打开了，您看下
> > > > > ![image](https://user-images.githubusercontent.com/6883877/63667447-5b61b600-c806-11e9-8abf-3cca017c4814.png)
> > > > 
> > > > 
> > > > 这个客户端的日志没有看出什么？server端的日志您能再看看吗？日志太多的话，您可以将/var/log/taos/下面的东西全清空了再重启taosd。
> > > 
> > > 
> > > 把之前的都清了重启，发了一次请求，截得日志，麻烦您帮看下了
> > > [taosd.log](https://github.com/taosdata/TDengine/files/3540217/taosd.log)
> > 
> > 
> > 您发给我的都是server端的日志。您能不能再操作一次？
> > server端：
> > 
> > 1. sudo systemctl stop taosd
> > 2. rm -rf /var/log/taos/*
> > 3. sudo systemctl start taosd
> > 
> > 在windows客户端，清空"c:\TDengine"下的日志，再连一次“taos -h"。
> > 然后拜托您将server端日志和Windows客户端日志一起打包发给我吗？
> 
> 包含客户端和服务器端日志，服务器是启动后发了一次请求的log
> [taoslog.0-client.log](https://github.com/taosdata/TDengine/files/3540655/taoslog.0-client.log)
> [taosdlog.0.server.log](https://github.com/taosdata/TDengine/files/3540657/taosdlog.0.server.log)

从日志上看，客户端发送的请求server收到了并建立了connection，但是server端发回的信息客户端迟迟收不到就将connection关掉了，所以可能还是网络问题。所以您能用netcat 测试一下您的端口udp/tcp能不能收发信息？

**Comment by Janus-Xu** [comment]
> > > > > > > > > > > > @fangpanpan win客户端版本和ubundu的server版本一致，可还是连不上，是什么原因？
> > > > > > > > > > > > ![image](https://user-images.githubusercontent.com/6883877/63663473-17b28080-c7f5-11e9-9edb-97ab9e1cee96.png)
> > > > > > > > > > > > ![image](https://user-images.githubusercontent.com/6883877/63663487-2436d900-c7f5-11e9-8d9a-93ee69c52319.png)
> > > > > > > > > > > > python接口调用也是一样问题
> > > > > > > > > > > > ![image](https://user-images.githubusercontent.com/6883877/63663511-3b75c680-c7f5-11e9-98a2-e27bad144d7d.png)
> > > > > > > > > > > > 您可以在win电脑上先用ping检查一下“192.168.2.89”网络连接吗？
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > ping通的
> > > > > > > > > > ![image](https://user-images.githubusercontent.com/6883877/63665281-43396900-c7fd-11e9-88de-08f796e65d5f.png)
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 那C:\TDengine 下的日志里报了什么错误吗？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 每次发请求log里只有这个信息：
> > > > > > > > ![image](https://user-images.githubusercontent.com/6883877/63666395-eb513100-c801-11e9-8a02-229f91abe7aa.png)
> > > > > > > 
> > > > > > > 
> > > > > > > 这个code:0是成功的。您能将日志全部打开吗？就是在/etc/taos/taos.cfg里加上debugflag 135
> > > > > > 
> > > > > > 
> > > > > > 打开了，您看下
> > > > > > ![image](https://user-images.githubusercontent.com/6883877/63667447-5b61b600-c806-11e9-8abf-3cca017c4814.png)
> > > > > 
> > > > > 
> > > > > 这个客户端的日志没有看出什么？server端的日志您能再看看吗？日志太多的话，您可以将/var/log/taos/下面的东西全清空了再重启taosd。
> > > > 
> > > > 
> > > > 把之前的都清了重启，发了一次请求，截得日志，麻烦您帮看下了
> > > > [taosd.log](https://github.com/taosdata/TDengine/files/3540217/taosd.log)
> > > 
> > > 
> > > 您发给我的都是server端的日志。您能不能再操作一次？
> > > server端：
> > > 
> > > 1. sudo systemctl stop taosd
> > > 2. rm -rf /var/log/taos/*
> > > 3. sudo systemctl start taosd
> > > 
> > > 在windows客户端，清空"c:\TDengine"下的日志，再连一次“taos -h"。
> > > 然后拜托您将server端日志和Windows客户端日志一起打包发给我吗？
> > 
> > 
> > 包含客户端和服务器端日志，服务器是启动后发了一次请求的log
> > [taoslog.0-client.log](https://github.com/taosdata/TDengine/files/3540655/taoslog.0-client.log)
> > [taosdlog.0.server.log](https://github.com/taosdata/TDengine/files/3540657/taosdlog.0.server.log)
> 
> 从日志上看，客户端发送的请求server收到了并建立了connection，但是server端发回的信息客户端迟迟收不到就将connection关掉了，所以可能还是网络问题（可能是防火墙）。所以您能用netcat 测试一下您的端口udp/tcp能不能收发信息？

感谢！解决了
确实是服务器发送客户端收不到，才注意到win用的无线是172段，交换机在下层，而服务器是有线192网段在上层，所以数据回传不了，给win加了个192的一对一绑定映射就可以了。
