### ISSUE TITLE
Grafana can't show DashBoard

### ISSUE THREAD

**Issue by sz-justinwang** [taosdata/TDengine#3790]
Grafana 版本：grafana-7.2.0-1.x86_64
CenterOS：CentOS Linux release 8.2.2004 (Core) 
TD版本：TDengine-server-2.0.4.0-Linux-x64

生产环境搭建好Grafana链接后起初可以链接TD展示面板数据，生产断电重启后数据无法展示
排查后发现，Grafana链接正常，taos命令窗口查询正常

![image](https://user-images.githubusercontent.com/72057154/95644289-3dc5dd80-0ae8-11eb-8e99-5970ebf8cfb5.png)

**Comment by liuyq-617** [comment]
您点击按钮GENERATE SQL，显示的sql语句是什么啊

**Comment by sz-justinwang** [comment]
select avg(value) from jk.jiankong where ts>=&from and ts<=&to interval(20000a);

**Comment by sz-justinwang** [comment]
> 您点击按钮GENERATE SQL，显示的sql语句是什么啊



> 您点击按钮GENERATE SQL，显示的sql语句是什么啊

select avg(value) from jk.jiankong where ts>=&from and ts<=&to interval(20000a);

**Comment by liuyq-617** [comment]
在grafana里，请使用$作为变量符

**Comment by sz-justinwang** [comment]
> 在grafana里，请使用$作为变量符

非常感谢

**Comment by sz-justinwang** [comment]
> 在grafana里，请使用$作为变量符

非常感谢
