### ISSUE TITLE
官方文档上说的windows 客户端连接工具在哪里下载

### ISSUE THREAD

**Issue by fdjhcg** [taosdata/TDengine#38]
![image](https://user-images.githubusercontent.com/19942839/61201411-01ee6d80-a717-11e9-9866-12d76d7183a8.png)

# 请问有人知道在哪里下载吗，服务器上不让开发，现在只能在window上开发

**Comment by maymay1982** [comment]
你是怎么编译通过的？没遇到这个问题吗：
CMake Error at src/client/CMakeLists.txt:30 (SET_TARGET_PROPERTIES):
  SET_TARGET_PROPERTIES called with incorrect number of arguments.

**Comment by fdjhcg** [comment]
我用的deb ,安装包 但是现在我要在不能再服务器上开发，只能在本地开发，没有jdbc 驱动

**Comment by hjxilinx** [comment]
Clients library on windows will be available in a few days. @fdjhcg

**Comment by hjxilinx** [comment]
@mamay1982, We have fix this problem, you can pull the latest code and try again.

**Comment by fdjhcg** [comment]
好的，谢谢 @hjxilinx

**Comment by hjxilinx** [comment]
@fdjhcg, windows library will be available in a few days.

**Comment by guanshengliang** [comment]
我们会在7月27日提交windows客户端代码

**Comment by guanshengliang** [comment]
Windows客户端代码已经提交，dll已经可以在官网下载
