### ISSUE TITLE
Parse error when RESTful api is called

### ISSUE THREAD

**Issue by robotspace** [taosdata/TDengine#3800]
**Compile and install database using code on development branch. Integrate it with openresty by RESTful api. Parse error though different content type is appointed in http header.** 

10/12 12:27:31.267600 0x7f4f1efe9700 HTP context:0x7f4f14042510, fd:22, is created, data:0x7f4f14041940
10/12 12:27:31.267603 0x7f4f1efe9700 UTL cache:restc data:0x7f4f14041940 extend expire time: 1602476854267
10/12 12:27:31.267605 0x7f4f1efe9700 UTL cache:restc, key:0x7f4f14041948, 0x7f4f14041940 released, refcnt:0, data in trashcan:0
10/12 12:27:31.267613 0x7f4f1efe9700 HTP context:0x7f4f14042510, fd:22, ip:127.0.0.1:38560, thread:rest1 numOfContexts:71 totalContext:141, accept a new connection
10/12 12:27:31.267639 0x7f4f1f7ea700 UTL cache:restc, key:0x7f4f1f7e9d70, 0x7f4f14041940 is retrieved from cache, refcnt:1
10/12 12:27:31.267650 0x7f4f1f7ea700 HTP context:0x7f4f14042510, fd:22, method:POST target:/rest/sql version:HTTP/1.1
10/12 12:27:31.267659 0x7f4f1f7ea700 HTP ERROR context:0x7f4f14042510, fd:22, parser state:5, char:[:]3a, oom
10/12 12:27:31.267663 0x7f4f1f7ea700 HTP ERROR context:0x7f4f14042510, fd:22, parse failed, httpCode:507 parseCode:4393 reason:failed to parse sp
10/12 12:27:31.267665 0x7f4f1f7ea700 HTP ERROR context:0x7f4f14042510, fd:22, failed to parse, state:5
10/12 12:27:31.267667 0x7f4f1f7ea700 HTP ERROR context:0x7f4f14042510, fd:22, parse failed, ret:-1 i:92 len:256 buf:POST /rest/sql HTTP/1.1
User-Agent: lua-resty-http/0.14 (Lua) ngx_lua/10017
Authorization::  Basic cm9vdDp0YW9zZGF0YQ==
Content-Length: 26
Content-Type: application/x-www-form-urlencoded;charset=utf-8
Host: 127.0.0.1:6041

select * from xxxxxx.track
10/12 12:27:31.267670 0x7f4f1f7ea700 HTP ERROR context:0x7f4f14042510, fd:22, parse failed, ret:-1 code:-2147479255 close connect
10/12 12:27:31.267673 0x7f4f1f7ea700 HTP ERROR context:0x7f4f14042510, fd:22, code:507, error:failed to parse sp

**Comment by robotspace** [comment]
I've find the root cause. One more ':' is added because of disunderstanding of authorization error.

**Comment by sangshuduo** [comment]
@robotspace may I know your email address?

**Comment by robotspace** [comment]
@sangshuduo 75638994@qq.com
