### ISSUE TITLE
超级表的聚合语句中使用sliding的时候报Redirect错误

### ISSUE THREAD

**Issue by quchunhui** [taosdata/TDengine#3801]
问题描述：
在超级表中执行聚合语句，加上sliding之后，报错：DB error: Redirect
因为官方文档上没有对sliding的使用描述，请问sliding是否可以作用在超级表上？

如何重现：
在超级表的聚合查询语句中，加上sliding

版本：
TDengine版本：2.0.4.0
服务器：Linux Centos 8

**Comment by sangshuduo** [comment]
请提供完整 SQL 语句

**Comment by quchunhui** [comment]
再现不出来了，先关掉吧。重新安装了系统之后，加上sliding也可以执行了。原因不明。以后再现了再重新创建issue吧。

**Comment by quchunhui** [comment]
close
