### ISSUE TITLE
查询效率问题

### ISSUE THREAD

**Issue by zhangyang1995** [taosdata/TDengine#3802]
1张超级表1W张子表放10亿数据，效率是否高于一张表放10亿的数据？

**Comment by hjxilinx** [comment]
会有不显著（几百毫秒） 左右的差别。

**Comment by zhangyang1995** [comment]
> 会有不显著（几百毫秒） 左右的差别。

我现在测试一台TDengine服务器，一个客户端while（true）写入数据，另一个客户端查询数据，查询的时候效率很低，如果写入暂停的话，查询效率恢复正常，这样只能读写分离来规避吗？有没有其他方案。

**Comment by zhangyang1995** [comment]
系统监控
TDengine启动后，会自动创建一个监测数据库SYS，并自动将服务器的CPU、内存、硬盘空间、带宽、请求数、磁盘读写速度、慢查询等信息定时写入该数据库。TDengine还将重要的系统操作（比如登录、创建、删除数据库等）日志以及各种错误报警信息记录下来存放在SYS库里。系统管理员可以从CLI直接查看这个数据库，也可以在WEB通过图形化界面查看这些监测信息。

这些监测信息的采集缺省是打开的，但可以修改配置文件里的选项enableMonitor将其关闭或打开。



这个监控数据库我使用sql use sys; 看不到  登录的用户名是root，配置文件中是打开的
# enable/disable system monitor 
# monitor               1
这里还需要什么样的操作吗？@hjxilinx

**Comment by zyyang-taosdata** [comment]
```
taos> use log;
Database changed.

taos> show tables;
           table_name           |      created_time       | columns |          stable_name           |
======================================================================================================
 acct_root                      | 2020-10-07 15:33:29.484 |      22 | acct                           |
 dn1                            | 2020-10-07 15:33:29.483 |      15 | dn                             |
 slowquery                      | 2020-10-07 15:33:29.485 |       5 |                                |
 log                            | 2020-10-07 15:33:29.478 |       4 |                                |
Query OK, 4 row(s) in set (0.001699s)

taos> select * from dn1 limit 2\G;
*************************** 1.row ***************************
        ts: 2020-10-07 15:34:00.445282
 cpu_taosd: 3.19479
cpu_system: 3.29479
 cpu_cores: 1
 mem_taosd: 5.64453
mem_system: 863.95703
 mem_total: 990
 disk_used: 13.53206
disk_total: 36
band_speed: 3.86673
   io_read: 17.51172
  io_write: 200.86816
  req_http: 0
req_select: 0
req_insert: 0

```
你说的是要看log库么？可能文档没有更新

**Comment by zhangyang1995** [comment]
> ```
> taos> use log;
> Database changed.
> 
> taos> show tables;
>            table_name           |      created_time       | columns |          stable_name           |
> ======================================================================================================
>  acct_root                      | 2020-10-07 15:33:29.484 |      22 | acct                           |
>  dn1                            | 2020-10-07 15:33:29.483 |      15 | dn                             |
>  slowquery                      | 2020-10-07 15:33:29.485 |       5 |                                |
>  log                            | 2020-10-07 15:33:29.478 |       4 |                                |
> Query OK, 4 row(s) in set (0.001699s)
> 
> taos> select * from dn1 limit 2\G;
> *************************** 1.row ***************************
>         ts: 2020-10-07 15:34:00.445282
>  cpu_taosd: 3.19479
> cpu_system: 3.29479
>  cpu_cores: 1
>  mem_taosd: 5.64453
> mem_system: 863.95703
>  mem_total: 990
>  disk_used: 13.53206
> disk_total: 36
> band_speed: 3.86673
>    io_read: 17.51172
>   io_write: 200.86816
>   req_http: 0
> req_select: 0
> req_insert: 0
> ```
> 
> 你说的是要看log库么？可能文档没有更新

感谢是log库没错了 以前没仔细看log库是做什么的现在明白了！
