### ISSUE TITLE
[doc] 文档链接问题与建议-快速开始

### ISSUE THREAD

**Issue by futurist** [taosdata/TDengine#3803]
**Bug Description**

下面这个页面上，点击快捷安装，会404：

https://www.taosdata.com/cn/getting-started/

**Additional Context**
另外，这个页面可以多一些指向文档的链接，如在底部demo之后，放一个链接跳转到文档页

**Comment by Aries-Lee1991** [comment]
@futurist 感谢您的建议，之前我们是想将快速上手页面内容公开给社区开发者维护，但后来发现这件事情不可行，因此在移动页面的时候，忘了删掉后面的svg图标。已经修复。
