### ISSUE TITLE
taos cli improvement

### ISSUE THREAD

**Issue by futurist** [taosdata/TDengine#3804]
**Bug Description**

In `taos` cli, cannot interrupt `select * from table` if table is very big.

**To Reproduce**
1. In shell enter `taosdemo`, follow and you get the big table `test.meters`
2. Run `select count(*) from test.meters;`
3. Bang!!!! You cannot stop it, `Ctrl+C` not work

**Expected Behavior**
Like `mongo` cli, big table should show limited records from cli, and a way to get more.

Andy many handy commands in other cli but not available in taos cli:

- `help`
- `show dbs`

**At least it should have a `help` command**, otherwise it's not like a reasonable product! 

**Environment (please complete the following information):**
 - OS: Debian 9
 - Memory, CPU, current Disk Space
 - TDengine Version 2.0.5.0

**Additional Context**

**Comment by hjxilinx** [comment]
ctrl+c not work is a known bug, and we will fixed it in the next released version.
