### ISSUE TITLE
'Unable to establish connection' when inserting data

### ISSUE THREAD

**Issue by wzf55555** [taosdata/TDengine#3808]
![image](https://user-images.githubusercontent.com/40660395/95715461-7efeee80-0c9c-11eb-912b-14a2b436b661.png)

**Comment by wzf55555** [comment]
客户端与服务端都使用最新版本2.0.5 ，jdbc连接，能获得到Connection 但是执行插入报错。配置FQDN后还是不行。上图就是配置FQDN后的结果。

**Comment by wzf55555** [comment]
防火墙都已关闭。

**Comment by sangshuduo** [comment]
用 taos 可以执行插入 SQL 命令吗？

**Comment by wzf55555** [comment]
可以的

**Comment by wzf55555** [comment]
![image](https://user-images.githubusercontent.com/40660395/95726061-081d2200-0cab-11eb-8e98-e9d5ee473fb4.png)

**Comment by sangshuduo** [comment]
请问用的哪个版本的 JDBC driver ？

**Comment by wzf55555** [comment]
![image](https://user-images.githubusercontent.com/40660395/95803883-d603d280-0d33-11eb-9b1f-696d936faa0f.png)

**Comment by quchunhui** [comment]
试试2.0.8版本的jdbc，我用2.0.8版本的可以正常插入。服务器的版本也是2.0.5.0

**Comment by wzf55555** [comment]
升级驱动后连接报错
![image](https://user-images.githubusercontent.com/40660395/95811326-9ba33100-0d45-11eb-94fa-d2c080ae1921.png)

**Comment by zyyang-taosdata** [comment]
谢谢您的问题，我需要client端的日志来排查这个问题。
1. 清理历史日志：C:\\TDengine\log
2. 重新启动你的java程序，执行插入SQL，并产生这个报错信息。
3. 将C:\\TDengine\log下的日志上传到当前issue。
谢谢～

**Comment by Aries-Lee1991** [comment]
@wzf55555 您好问题解决了吗？如果没有解决，还请麻烦按照如上所属，配合我们的研发同学 @zyyang-taosdata 一起排查这个问题。

**Comment by wzf55555** [comment]
解决了配置FQDN
