### ISSUE TITLE
after inserting data to a super table for a while,  last(price) of select first(price), last(price) from tbl interval(1d) returns null

### ISSUE THREAD

**Issue by lexcui** [taosdata/TDengine#3809]
**Bug Description**
有一个程序负责逐条插入数据到超级表的子表。另一个程序接收客户端jdbc的查询请求。查询语句类似select first(price),last(price) from tbl interval(1h); 在大概一小时内查询返回的行中有一部分行的 first值是有值的，last值为null。大概一小时以后，再执行查询则会返回正常的数据。

**To Reproduce**
建立超级表子表tbl，向里面逐条插入数据。待数据插入一定量之后，停止插入。
用taos客户端查询，语句为 select first(price),last(price) from tbl interval(1h); 

**Expected Behavior**
返回时间间隔内的第一个值和最后一个值。如果第一个值有值，则最后一个值也应该有值而不应该为null。

**Snapshot**
![opensuse-laptop](https://ftp.bmp.ovh/imgs/2020/10/326b01da069be1e5.jpg)

**Environment (please complete the following information):**
 - OS: RHEL 7.6
 - TDengine Version  1.6.5.9

**Comment by sangshuduo** [comment]
用 taos 执行 **select first(price), last(price) from tbl interval(1d)** 的结果是什么？

**Comment by lexcui** [comment]
附件是一张执行出错的截图。你可以看到 ，first都是有值的，但是last里有的行没有值。




发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Shuduo Sang<mailto:notifications@github.com>
发送时间: 2020年10月12日 16:51
收件人: taosdata/TDengine<mailto:TDengine@noreply.github.com>
抄送: Lex Cui<mailto:lexcui@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [taosdata/TDengine] 在超级表子表插入数据后一段时间内，查询 select first(price), last(price) from tbl interval(1d) 返回的last(price)为null (#3809)


用 taos 执行 select first(price), last(price) from tbl interval(1d) 的结果是什么？

―

**Comment by sangshuduo** [comment]
貌似邮件附件的图片在 GitHub 里不显示

**Comment by lexcui** [comment]
抱歉没有图床，在github issue里没上传图片。


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Shuduo Sang<mailto:notifications@github.com>
发送时间: 2020年10月12日 16:54
收件人: taosdata/TDengine<mailto:TDengine@noreply.github.com>
抄送: Lex Cui<mailto:lexcui@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [taosdata/TDengine] 在超级表子表插入数据后一段时间内，查询 select first(price), last(price) from tbl interval(1d) 返回的last(price)为null (#3809)


貌似邮件附件的图片在 GitHub 里不显示

―

**Comment by lexcui** [comment]
我编辑了原问题，增加了出错的截图

**Comment by lexcui** [comment]
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Cui Lex<mailto:lexcui@hotmail.com>
发送时间: 2020年10月12日 16:54
收件人: taosdata/TDengine<mailto:reply@reply.github.com>; taosdata/TDengine<mailto:TDengine@noreply.github.com>
抄送: Author<mailto:author@noreply.github.com>
主题: 回复: [taosdata/TDengine] 在超级表子表插入数据后一段时间内，查询 select first(price), last(price) from tbl interval(1d) 返回的last(price)为null (#3809)

抱歉没有图床，在github issue里没上传图片。


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Shuduo Sang<mailto:notifications@github.com>
发送时间: 2020年10月12日 16:54
收件人: taosdata/TDengine<mailto:TDengine@noreply.github.com>
抄送: Lex Cui<mailto:lexcui@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [taosdata/TDengine] 在超级表子表插入数据后一段时间内，查询 select first(price), last(price) from tbl interval(1d) 返回的last(price)为null (#3809)


貌似邮件附件的图片在 GitHub 里不显示

―

**Comment by sangshuduo** [comment]
TDengine 1.6.5.9？我们都迁移到 2.0 了，试一下最新版本吧 TDengine 2.0.5.1 和 JDBC 2.0.8

**Comment by Aries-Lee1991** [comment]
@lexcui 是否已经升级了版本，升级后是否还存在这个问题？

**Comment by sangshuduo** [comment]
如果 2.0 再出现类似问题请报一个新 issue
