### ISSUE TITLE
社区版只有一个核有负载

### ISSUE THREAD

**Issue by sagewjq** [taosdata/TDengine#381]
一个超级表导入300万数据，查询在一秒内跑出来，导入500万要90多秒才能跑出来，此时CPU只有一个核(共16核)在跑，其它的都是0，有什么参数可以让多核同时参与运算吗

**Comment by fangpanpan** [comment]
目前还是一个核在跑，我们框架还在改动中，以后可以让多核同时参与。

**Comment by sagewjq** [comment]
企业版 可以支持多核么

**Comment by hzcheng** [comment]
企业版是可以的。开源版很快也可以
