### ISSUE TITLE
请问taos告警模块能否指定json文本

### ISSUE THREAD

**Issue by nzxxs4** [taosdata/TDengine#3811]
就是curl -d '@rule.json' http://localhost:8100/api/update-rule命令中的‘@rule.json’
能否换成‘{"name":"abc","sql","select * from test","expr":10,"for":"0"......}’

**Comment by localvar** [comment]
curl 支持这种写法，具体请参阅 curl 的文档。

**Comment by kon3155** [comment]
rule.json是否支持多个规则，即[{},{},{}]？

**Comment by huskar-t** [comment]
@kon3155 yes,we support
