### ISSUE TITLE
create table report 'Unexpected generic error in mnode'

### ISSUE THREAD

**Issue by yinfi** [taosdata/TDengine#3812]
**Bug Description**
完成集群搭建后，可以创建超级表，但是在创建表的时候出现如下报错：
![image](https://user-images.githubusercontent.com/3062749/95728221-d6598a80-0cad-11eb-8016-b7e6501b8740.png)

**To Reproduce**
1. 创建超级表
2. 创建子表：create table if not exists md5_8d4543fd6f3554276020431e89a1372a using _net_if_all_tcpnum tags("cnsz22pl0123","all")
3. 报错：Unexpected generic error in mnode

**Expected Behavior**
完成新表创建.

**Screenshots**
![image](https://user-images.githubusercontent.com/3062749/95728221-d6598a80-0cad-11eb-8016-b7e6501b8740.png)

**Environment (please complete the following information):**
 - OS:CentOS Linux release 7.4.1708 (Core)
 - Memory 16g, CPU 8, current Disk Space 200g
 - TDengine Version 2.0.5.0

**Additional Context**
执行数据插入是可以的，日志没有看到报错日志

**Comment by sangshuduo** [comment]
请 @guanshengliang 看一下

**Comment by guanshengliang** [comment]
这些信息还不够
请下载一个向日葵，加下我的微信 geiseil，远程分析一下原因

**Comment by guanshengliang** [comment]
There is no reply for a long time, and this problem has been located and solved in 2.0.9.0
