### ISSUE TITLE
streamId keeps changing but query result is same, and sometimes reports 'Unable to establish connection'

### ISSUE THREAD

**Issue by quchunhui** [taosdata/TDengine#3822]
**Bug Description**
创建了一个连续查询，以实现将数据降维，将结果数据存储到另一个库中。
连续查询创建之后，查看show streams;，可以看到streamId一直在变化，可是结果库中的数据却一直没有改变。

**To Reproduce**
1. 创建一个数据库（qch_test），并通过程序一直想里面写数据（我这里是10秒写入1条）
2. 创建连续查询，并将查询结果放入另一个数据库中（qch_cq）。语句：create table qch_cq.device_data_up_sum as select sum(AI_PICK_UDATA) from qch_test.st_device_data_up interval(1m) sliding(30s) order by time desc;
3. 查看连续查询状态。发现其streamId是一直都在变化的。不太了解stream的机理，不清楚这种状态是否正确。
![image](https://user-images.githubusercontent.com/18110478/95806842-44985e80-0d3b-11eb-8c8f-2a89e258e6da.png)
4. 查看连续查询的结果数据。语句：select * from device_data_up_sum order by time desc;
现象1：结果数据一直没有变化（程序写入一直没有停）
现象2：间歇性出现DB error: Unable to establish connection
![image](https://user-images.githubusercontent.com/18110478/95806883-672a7780-0d3b-11eb-8f10-a00d8536223c.png)

**Expected Behavior**
连续查询可以正确、稳定的执行，

**Screenshots**

**Environment (please complete the following information):**
 - OS: Linux Centos8
 - Memory, CPU, current Disk Space：8核16G内存，100GB磁盘
 - TDengine Version：2.0.5.0

**Comment by Aries-Lee1991** [comment]
您的这个Issue我们工程师都在：https://github.com/taosdata/TDengine/issues/3821 这里面进行回复了。所以，这个Issue，我就关闭了。
