### ISSUE TITLE
select not show the data inserted

### ISSUE THREAD

**Issue by songtianyi** [taosdata/TDengine#3824]
**General Questions**

select not show the data just inserted.
```
taos> insert into gate_99 (ts, flow_no, code, msg) values ('2020-10-13 10:33:20', 'bu2h3s5fhclvmjn21920', 200, 'OK');
Query OK, 1 row(s) affected (0.000812s)

taos> select * from gate_99 where code=200;
Query OK, 0 row(s) in set (0.055821s)
```
the table described as following
```
taos> describe gate_99;
             Field              |        Type        |   Length    |    Note    |
=================================================================================
 ts                             | TIMESTAMP          |           8 |            |
 flow_no                        | NCHAR              |          20 |            |
 channel                        | NCHAR              |          15 |            |
 trade                          | NCHAR              |           7 |            |
 cnt                            | FLOAT              |           4 |            |
 client_id                      | INT                |           4 |            |
 branch                         | NCHAR              |          15 |            |
 create_at                      | BIGINT             |           8 |            |
 src                            | NCHAR              |          39 |            |
 dst                            | NCHAR              |          39 |            |
 code                           | INT                |           4 |            |
 msg                            | NCHAR              |         125 |            |
Query OK, 12 row(s) in set (0.000235s)
```

**Comment by yihaoDeng** [comment]
@songtianyi 有版本号吗

**Comment by songtianyi** [comment]
> @songtianyi 有版本号吗

TDengine-server-2.0.4.0-Linux-x64.rpm

**Comment by yihaoDeng** [comment]
@songtianyi 
select * from gate_ 99  where ts = '2020-10-13 10:33:20' 是不是能查到你插入的数据， 所有值是不是和你插入的数据一样

**Comment by songtianyi** [comment]
> @songtianyi
> select * from gate_ 99 where ts = '2020-10-13 10:33:20' 是不是能查到你插入的数据， 所有值是不是和你插入的数据一样
```
taos> select * from gate_ 99 where ts = '2020-10-13 10:33:20';
段错误(吐核)
```

**Comment by songtianyi** [comment]
> @songtianyi
> select * from gate_ 99 where ts = '2020-10-13 10:33:20' 是不是能查到你插入的数据， 所有值是不是和你插入的数据一样

不一样，是另外一条，看起来是没插进去。但是插入失败，没有错误提示？
```
taos> insert into gate_99 (ts, flow_no, code, msg) values ('2020-10-13 14:20:20', 'bu2ke95fhcltldo7bi3g', 200, 'OK');
Query OK, 1 row(s) affected (0.000685s)

taos> select * from gate_99 where ts='2020-10-13 14:20:20';
           ts            |            flow_no             |            channel             |             trade              |         cnt          |  client_id  |             branch             |       create_at       |              src               |              dst               |    code     |              msg               |
============================================================================================================================================================================================================================================================================================================================================
 2020-10-13 14:20:20.000 | bu2ke95fhcltldo7bi30           | app                            | deposit                        |             63.79000 |       10006 | sz                             |            1602570020 | 192.168.1.99                   | 192.168.1.99                   |        NULL | NULL                           |
Query OK, 1 row(s) in set (0.025998s)

taos>
```

**Comment by yihaoDeng** [comment]
> > @songtianyi
> > select * from gate_ 99 where ts = '2020-10-13 10:33:20' 是不是能查到你插入的数据， 所有值是不是和你插入的数据一样
> 
> 不一样，是另外一条，看起来是没插进去。但是插入失败，没有错误提示？
> 
> ```
> taos> insert into gate_99 (ts, flow_no, code, msg) values ('2020-10-13 14:20:20', 'bu2ke95fhcltldo7bi3g', 200, 'OK');
> Query OK, 1 row(s) affected (0.000685s)
> 
> taos> select * from gate_99 where ts='2020-10-13 14:20:20';
>            ts            |            flow_no             |            channel             |             trade              |         cnt          |  client_id  |             branch             |       create_at       |              src               |              dst               |    code     |              msg               |
> ============================================================================================================================================================================================================================================================================================================================================
>  2020-10-13 14:20:20.000 | bu2ke95fhcltldo7bi30           | app                            | deposit                        |             63.79000 |       10006 | sz                             |            1602570020 | 192.168.1.99                   | 192.168.1.99                   |        NULL | NULL                           |
> Query OK, 1 row(s) in set (0.025998s)
> 
> taos>
> ```

**Comment by yihaoDeng** [comment]
@songtianyi  那很明显了，我们目前针对同一个时间戳的写， 只保留最旧的那条记录，新的写记录（insert）不会保存，也不会报错。 这个问题得等我们支持update/delete 会修正这个问题， 谢谢您的issuse
