### ISSUE TITLE
timestamp returned by RESTful Connector is not CST

### ISSUE THREAD

**Issue by yhao1107** [taosdata/TDengine#3831]
使用RESTful Connector查询获取数据时查询到得时间与北京时间不对应，条件查询时间是11:00:00,查出来是3:00:00，相差八小时，说明时区不对。使用客户端查询出来的时间是对的。文档没有找到相应得函数或者解决办法，是否有时间转换的方法，
![image](https://user-images.githubusercontent.com/39080944/95828441-922ac080-0d67-11eb-9405-26b280b597d4.png)

**Comment by guanshengliang** [comment]
通常使用的url为  http://ip:port/rest/sql，但同时支持http://ip:port/rest/sqlt和http://ip:port/rest/sqlutc

- rest/sql 将数字格式的timestamp，按照服务器时区转换为字符串
- rest/sqlt 返回数字格式的timestamp
- rest/sqlutc 将数字格式的timestamp，转换为UTC时间字符串

例如
{
    "status": "succ",
    "head": [
        "ts",
        "i"
    ],
    "data": [
        [
            "2020-10-15T14:24:52.701+0800",
            1
        ]
    ],
    "rows": 1
}

**Comment by guanshengliang** [comment]
done
