### ISSUE TITLE
Invalid client version

### ISSUE THREAD

**Issue by Kittoa** [taosdata/TDengine#3832]
taosd安装在服务器A上，版本是2.0.3.1，然后拿了A服务器上的taos.h和libtaos.so到了机器B上编写程序，连接数据库报错Invalid client version，

不知道为什么版本总是2.0.0.0，客户端错误日志如下：
==================================================
                new log file
==================================================
10/13 07:58:43.323213 0x7f6931b190c0 UTL all debug flag are set to 135
10/13 07:58:43.323218 0x7f6931b190c0 UTL localEp is: 192.168.66.214:6030
10/13 07:58:43.323399 0x7f6931b190c0 UTL timezone not configured, set to system default:Etc/UTC (UTC, +0000)
10/13 07:58:43.323425 0x7f6931b190c0 UTL ERROR locale not configured, set to system default:en_US.UTF-8
10/13 07:58:43.323429 0x7f6931b190c0 UTL WARN charset not configured, set to system default:UTF-8
10/13 07:58:43.323445 0x7f6931b190c0 UTL    taos config & system info:
10/13 07:58:43.323446 0x7f6931b190c0 UTL ==================================
10/13 07:58:43.323447 0x7f6931b190c0 UTL  firstEp:                192.168.66.214:6030
10/13 07:58:43.323448 0x7f6931b190c0 UTL  secondEp:               192.168.66.214:6030
10/13 07:58:43.323448 0x7f6931b190c0 UTL  fqdn:                   192.168.66.214
10/13 07:58:43.323449 0x7f6931b190c0 UTL  serverPort:             6030
10/13 07:58:43.323450 0x7f6931b190c0 UTL  configDir:              /etc/taos
10/13 07:58:43.323451 0x7f6931b190c0 UTL  logDir:                 /var/log/taos
10/13 07:58:43.323452 0x7f6931b190c0 UTL  scriptDir:              /etc/taos
10/13 07:58:43.323452 0x7f6931b190c0 UTL  arbitrator:
10/13 07:58:43.323453 0x7f6931b190c0 UTL  numOfThreadsPerCore:    1.000000
10/13 07:58:43.323456 0x7f6931b190c0 UTL  rpcTimer:               1000(ms)
10/13 07:58:43.323457 0x7f6931b190c0 UTL  rpcMaxTime:             600(s)
10/13 07:58:43.323458 0x7f6931b190c0 UTL  shellActivityTimer:     3(s)
10/13 07:58:43.323459 0x7f6931b190c0 UTL  tableMetaKeepTimer:     7200(s)
10/13 07:58:43.323459 0x7f6931b190c0 UTL  compressMsgSize:        -1
10/13 07:58:43.323460 0x7f6931b190c0 UTL  maxSQLLength:           65480(byte)
10/13 07:58:43.323461 0x7f6931b190c0 UTL  maxNumOfOrderedRes:     100000
10/13 07:58:43.323462 0x7f6931b190c0 UTL  timezone:               Etc/UTC (UTC, +0000)
10/13 07:58:43.323463 0x7f6931b190c0 UTL  locale:                 en_US.UTF-8
10/13 07:58:43.323464 0x7f6931b190c0 UTL  charset:                UTF-8
10/13 07:58:43.323464 0x7f6931b190c0 UTL  numOfLogLines:          10000000
10/13 07:58:43.323465 0x7f6931b190c0 UTL  asyncLog:               1
10/13 07:58:43.323466 0x7f6931b190c0 UTL  debugFlag:              135
10/13 07:58:43.323467 0x7f6931b190c0 UTL  rpcDebugFlag:           135
10/13 07:58:43.323467 0x7f6931b190c0 UTL  tmrDebugFlag:           131
10/13 07:58:43.323468 0x7f6931b190c0 UTL  cDebugFlag:             135
10/13 07:58:43.323469 0x7f6931b190c0 UTL  jniDebugFlag:           135
10/13 07:58:43.323469 0x7f6931b190c0 UTL  odbcDebugFlag:          135
10/13 07:58:43.323470 0x7f6931b190c0 UTL  uDebugFlag:             135
10/13 07:58:43.323471 0x7f6931b190c0 UTL  qDebugFlag:             135
10/13 07:58:43.323472 0x7f6931b190c0 UTL  tsdbDebugFlag:          135
10/13 07:58:43.323472 0x7f6931b190c0 UTL  gitinfo:                8df8b7d9930342dd34ba13df160a7d538fad7bc7
10/13 07:58:43.323473 0x7f6931b190c0 UTL  gitinfoOfInternal:
10/13 07:58:43.323474 0x7f6931b190c0 UTL  buildinfo:              Built by root at 2020-08-03 17:21
10/13 07:58:43.323474 0x7f6931b190c0 UTL  version:                2.0.0.0
10/13 07:58:43.323475 0x7f6931b190c0 UTL  maxBinaryDisplayWidth:  30
10/13 07:58:43.323476 0x7f6931b190c0 UTL  os pageSize:            4096(KB)
10/13 07:58:43.323477 0x7f6931b190c0 UTL  os openMax:             1024
10/13 07:58:43.323478 0x7f6931b190c0 UTL  os streamMax:           16
10/13 07:58:43.323478 0x7f6931b190c0 UTL  os numOfCores:          1
10/13 07:58:43.323479 0x7f6931b190c0 UTL  os totalDisk:           0.000000(GB)
10/13 07:58:43.323480 0x7f6931b190c0 UTL  os totalMemory:         1970(MB)
10/13 07:58:43.323482 0x7f6931b190c0 UTL  os sysname:             Linux
10/13 07:58:43.323482 0x7f6931b190c0 UTL  os nodename:            
10/13 07:58:43.323483 0x7f6931b190c0 UTL  os release:             4.15.0-118-generic
10/13 07:58:43.323484 0x7f6931b190c0 UTL  os version:             #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020
10/13 07:58:43.323484 0x7f6931b190c0 UTL  os machine:             x86_64
10/13 07:58:43.323486 0x7f6931b190c0 UTL ==================================
10/13 07:58:43.323487 0x7f6931b190c0 TSC starting to initialize TAOS client ...
10/13 07:58:43.323488 0x7f6931b190c0 TSC Local End Point is:192.168.66.214:6030
10/13 07:58:43.323530 0x7f6931b190c0 UTL tsc scheduler is initialized, numOfThreads:2
10/13 07:58:43.323591 0x7f6931b190c0 UTL tmr scheduler is initialized, numOfThreads:1
10/13 07:58:43.323618 0x7f6931b190c0 TSC client is initialized successfully
10/13 07:58:43.323631 0x7f6931b190c0 UTL pool:0x55d37797c190 is setup, maxId:5000
10/13 07:58:43.324188 0x7f6931b190c0 RPC TSC TCP client is initialized, ip:0:0
10/13 07:58:43.324193 0x7f6931b190c0 UTL open udp socket:0x0:0
10/13 07:58:43.324222 0x7f6931b190c0 RPC TSC UDP connection is initialized, ip:0:0 threads:1
10/13 07:58:43.324224 0x7f6931b190c0 RPC TSC rpc is openned, threads:1 sessions:5000
10/13 07:58:43.324225 0x7f6931b190c0 TSC dnodeConn:0x55d37797c0b0 is created, user:root
10/13 07:58:43.324233 0x7f6931b190c0 TSC 0x55d3779aaf00 SQL cmd:connect will be processed, name:(null), type:0
10/13 07:58:43.324245 0x7f6931b190c0 RPC TSC 0x7f692d62f188 client connection is allocated, uid:0x2d640e75
10/13 07:58:43.324247 0x7f6931b190c0 RPC TSC UDP connection is setup, ip:d642a8c0:6030 localPort:42266
10/13 07:58:43.324252 0x7f6931b190c0 RPC TSC 0x7f692d62f188 0x55d3779aaf00, connect is sent to 192.168.66.214:6030, len:345 sig:0x01000000:0x00000000:37418
10/13 07:58:43.324377 0x7f692cd5f700 RPC TSC UDP thread is created, index:0
10/13 07:58:43.332648 0x7f692cd5f700 RPC UDP malloc mem: 0x7f6920000b20
10/13 07:58:43.332687 0x7f692cd5f700 RPC TSC 0x7f692d62f188 0x55d3779aaf00, connect-rsp received from 0xd642a8c0:6030, parse code:0x0 len:84 sig:0xaf010000:0x01000000:37418 code:0x80000204
10/13 07:58:43.332717 0x7f692cd5f700 TSC 0x55d3779aaf00 SQL cmd:connect, code:Invalid client version rspLen:0
10/13 07:58:43.332738 0x7f6931b190c0 TSC 0x55d3779aaf00 start to free sql object
10/13 07:58:43.332742 0x7f6931b190c0 TSC 0x55d3779aaf00 start to free local reducer
10/13 07:58:43.332743 0x7f6931b190c0 TSC 0x55d3779aaf00 local reducer has been freed, abort
10/13 07:58:43.332747 0x7f6931b190c0 TSC 0x55d3779aaf00 SqlObj is freed by app, qhandle is null
10/13 07:58:43.332751 0x7f6931b190c0 RPC TSC TCP client is stopped
10/13 07:58:43.332797 0x7f692cd5f700 RPC TSC UDP socket was closed, exiting(Success)
10/13 07:58:43.332858 0x7f6931b190c0 RPC TSC UDP is stopped
10/13 07:58:43.332865 0x7f6931b190c0 RPC TSC 0x7f692d62f188 0x55d3779aaf00, rpc connection is released

**Comment by localvar** [comment]
B机器以前是否安装过其它版本？请在 B 机器上安装对应版本的 taos 客户端后再尝试一下。

**Comment by Kittoa** [comment]
B机器上我只装过2.0.0.1的docker，宿主机上没有安装过，我想知道的是这个版本信息是写在哪里了，用的是2.0.3.1相应版本的libtaos.so为什么回去获取到其他的版本号？

**Comment by localvar** [comment]
请检查下 /usr/local/taos/driver 文件夹下有哪些文件，这是 libtaos.so 的实际存放位置，其它文件都是符号链接。

**Comment by Kittoa** [comment]
A机器上目录是这样子的：
root@8bgazeo:# tree /usr/local/taos/
/usr/local/taos/
├── bin
│   ├── taos
│   ├── taosd
│   └── taosdemo
├── cfg
│   ├── taos.cfg -> /etc/taos/taos.cfg
│   └── taos.cfg.org
├── connector
│   ├── go
│   ├── grafanaplugin
│   │   ├── dashboard
│   │   │   ├── import_dashboard.png
│   │   │   ├── tdengine_dashboard.png
│   │   │   └── tdengine-grafana.json
│   │   ├── dist
│   │   │   ├── css
│   │   │   │   └── query-editor.css
│   │   │   ├── dashboard
│   │   │   │   ├── import_dashboard.png
│   │   │   │   ├── tdengine_dashboard.png
│   │   │   │   └── tdengine-grafana.json
│   │   │   ├── datasource.js
│   │   │   ├── datasource.js.map
│   │   │   ├── img
│   │   │   │   └── taosdata_logo.png
│   │   │   ├── module.js
│   │   │   ├── module.js.map
│   │   │   ├── partials
│   │   │   │   ├── config.html
│   │   │   │   └── query.editor.html
│   │   │   ├── plugin.json
│   │   │   ├── query_ctrl.js
│   │   │   ├── query_ctrl.js.map
│   │   │   └── README.md
│   │   ├── Gruntfile.js
│   │   ├── LICENSE
│   │   ├── package.json
│   │   ├── package-lock.json
│   │   ├── README.md
│   │   ├── spec
│   │   │   ├── datasource_spec.js
│   │   │   └── test-main.js
│   │   ├── src
│   │   │   ├── css
│   │   │   │   └── query-editor.css
│   │   │   ├── datasource.js
│   │   │   ├── img
│   │   │   │   └── taosdata_logo.png
│   │   │   ├── module.js
│   │   │   ├── partials
│   │   │   │   ├── config.html
│   │   │   │   └── query.editor.html
│   │   │   ├── plugin.json
│   │   │   └── query_ctrl.js
│   │   └── yarn.lock
│   ├── python
│   │   ├── linux
│   │   │   ├── python2
│   │   │   │   ├── LICENSE
│   │   │   │   ├── README.md
│   │   │   │   ├── setup.py
│   │   │   │   └── taos
│   │   │   │       ├── cinterface.py
│   │   │   │       ├── connection.py
│   │   │   │       ├── constants.py
│   │   │   │       ├── cursor.py
│   │   │   │       ├── dbapi.py
│   │   │   │       ├── error.py
│   │   │   │       ├── __init__.py
│   │   │   │       └── subscription.py
│   │   │   └── python3
│   │   │       ├── LICENSE
│   │   │       ├── README.md
│   │   │       ├── setup.py
│   │   │       └── taos
│   │   │           ├── cinterface.py
│   │   │           ├── connection.py
│   │   │           ├── constants.py
│   │   │           ├── cursor.py
│   │   │           ├── dbapi.py
│   │   │           ├── error.py
│   │   │           ├── __init__.py
│   │   │           └── subscription.py
│   │   └── windows
│   │       ├── python2
│   │       │   ├── LICENSE
│   │       │   ├── README.md
│   │       │   ├── setup.py
│   │       │   └── taos
│   │       │       ├── cinterface.py
│   │       │       ├── connection.py
│   │       │       ├── constants.py
│   │       │       ├── cursor.py
│   │       │       ├── dbapi.py
│   │       │       ├── error.py
│   │       │       ├── __init__.py
│   │       │       └── subscription.py
│   │       └── python3
│   │           ├── LICENSE
│   │           ├── README.md
│   │           ├── setup.py
│   │           └── taos
│   │               ├── cinterface.py
│   │               ├── connection.py
│   │               ├── constants.py
│   │               ├── cursor.py
│   │               ├── dbapi.py
│   │               ├── error.py
│   │               ├── __init__.py
│   │               └── subscription.py
│   └── taos-jdbcdriver-2.0.0-dist.jar
├── data -> /var/lib/taos
├── driver
│   └── libtaos.so.2.0.3.1
├── examples
│   ├── bash
│   │   ├── demo.csv
│   │   └── demo.sql
│   ├── c
│   │   ├── apitest.c
│   │   ├── asyncdemo.c
│   │   ├── CMakeLists.txt
│   │   ├── demo.c
│   │   ├── makefile
│   │   ├── prepare.c
│   │   ├── stream.c
│   │   └── subscribe.c
│   ├── C#
│   │   ├── TDengineDriver.cs
│   │   └── TDengineTest.cs
│   ├── go
│   │   └── src
│   │       └── taosapp
│   │           └── taosapp.go
│   ├── JDBC
│   │   ├── JDBCDemo
│   │   │   ├── pom.xml
│   │   │   ├── readme.md
│   │   │   └── src
│   │   │       └── main
│   │   │           └── java
│   │   │               └── TSDBSyncSample.java
│   │   ├── springbootdemo
│   │   │   ├── mvnw
│   │   │   ├── mvnw.cmd
│   │   │   ├── pom.xml
│   │   │   ├── readme.md
│   │   │   └── src
│   │   │       ├── main
│   │   │       │   ├── java
│   │   │       │   │   └── com
│   │   │       │   │       └── taosdata
│   │   │       │   │           └── jdbc
│   │   │       │   │               └── springbootdemo
│   │   │       │   │                   ├── controller
│   │   │       │   │                   │   └── WeatherController.java
│   │   │       │   │                   ├── dao
│   │   │       │   │                   │   └── WeatherMapper.java
│   │   │       │   │                   ├── domain
│   │   │       │   │                   │   └── Weather.java
│   │   │       │   │                   ├── service
│   │   │       │   │                   │   └── WeatherService.java
│   │   │       │   │                   └── SpringbootdemoApplication.java
│   │   │       │   └── resources
│   │   │       │       ├── application.properties
│   │   │       │       └── mapper
│   │   │       │           └── WeatherMapper.xml
│   │   │       └── test
│   │   │           └── java
│   │   │               └── com
│   │   │                   └── taosdata
│   │   │                       └── jdbc
│   │   │                           └── springbootdemo
│   │   │                               └── SpringbootdemoApplicationTests.java
│   │   └── SpringJdbcTemplate
│   │       ├── pom.xml
│   │       ├── readme.md
│   │       └── src
│   │           ├── main
│   │           │   ├── java
│   │           │   │   └── com
│   │           │   │       └── taosdata
│   │           │   │           └── jdbc
│   │           │   │               └── App.java
│   │           │   └── resources
│   │           │       └── applicationContext.xml
│   │           └── test
│   │               └── java
│   │                   └── com
│   │                       └── taosdata
│   │                           └── jdbc
│   │                               └── AppTest.java
│   ├── lua
│   │   ├── build.sh
│   │   ├── lua_connector.c
│   │   ├── README.md
│   │   └── test.lua
│   ├── matlab
│   │   └── TDengineDemo.m
│   ├── nodejs
│   │   ├── node-example.js
│   │   └── node-example-raw.js
│   ├── python
│   │   └── read_example.py
│   ├── R
│   │   └── command.txt
│   └── rust
│       ├── build.rs
│       ├── Cargo.toml
│       ├── examples
│       │   ├── demo.rs
│       │   └── subscribe.rs
│       ├── README.md
│       └── src
│           ├── bindings.rs
│           ├── lib.rs
│           ├── subscriber.rs
│           ├── tdengine.rs
│           └── utils.rs
├── include
│   ├── taoserror.h
│   └── taos.h
├── init.d
│   └── taosd
├── log -> /var/log/taos
└── script
    ├── post.sh
    └── preun.sh

86 directories, 142 files

B机器上没有这个目录。

**Comment by Kittoa** [comment]
是我的链接文件出问题，本地的libtaos.so没有链接到libtaos.so.1，程序去找libtaos.so.1了，这个是之前的2.0.0.0的库，多谢你的回答。
