### ISSUE TITLE
show stables returns wrong child table count

### ISSUE THREAD

**Issue by quchunhui** [taosdata/TDengine#3834]
**Bug Description**
创建了超级表以及表，通过show tables与show stables查看结果，
发现两个结果集存在不一致的情况。超级表的tables数不正确，具体请参考下面的截图。

**To Reproduce**
这两个表一致在测试用，无法清楚的记起中间进行了哪些操作。

**Expected Behavior**
show tables与show stables的数据应该一致。

**Screenshots**
![image](https://user-images.githubusercontent.com/18110478/95835590-fe5df200-0d70-11eb-87b6-6f374d5278dd.png)

**Comment by guanshengliang** [comment]
该问题已经处理，是在修改超级表时，一个数字计算错误导致。
已经提交代码到develop分支，您下次发版的时候更新即可。

**Comment by guanshengliang** [comment]
2052版本已经私信发给你，您验证一下是否还有此问题

**Comment by guanshengliang** [comment]
done
