### ISSUE TITLE
Unable to resolve FQDN

### ISSUE THREAD

**Issue by qiuyan0528** [taosdata/TDengine#3836]
环境：windows 10 下docker
TDengine服务版本：docker images： latest（2.0.5.1）
TDengine客户端：windows x64 2.0.5.1
以上均为在同一台windows宿主机下。

问题1：客户端只能通过-h指定127.0.0.1才能连接服务，如下图
![image](https://user-images.githubusercontent.com/252830/95844996-3159b300-0d7c-11eb-9015-cb92f478017f.png)

问题2：连接成功后，创建数据库失败
![image](https://user-images.githubusercontent.com/252830/95845145-6403ab80-0d7c-11eb-9799-ce1a2313caab.png)

**Comment by localvar** [comment]
启动 docker 时请使用 --hostname 指定机器名，并请参考：https://www.taosdata.com/blog/2020/09/11/1824.html

**Comment by qiuyan0528** [comment]
上面的参考看过，问题依然存在。

（1）服务启动：
docker run -d -v D:\develop\tdengine\etc\taos:/etc/taos -v D:\develop\tdengine\var\lib\taos:/var/lib/taos -v D:\develop\tdengine\var\log\taos:/var/log/taos -p 6030:6030 -p 6035:6035 -p 6041:6041 -p 6030-6040:6030-6040/udp -h node01 tdengine/tdengine

（2）修改host
![image](https://user-images.githubusercontent.com/252830/95849172-af6c8880-0d81-11eb-9149-af0b86be6758.png)
（3）验证host
![image](https://user-images.githubusercontent.com/252830/95849229-c4491c00-0d81-11eb-8c3b-4a0eeca76d01.png)

（4）客户端连接成功
![image](https://user-images.githubusercontent.com/252830/95849289-d925af80-0d81-11eb-8034-33fcb54b90e0.png)

**（5）创建数据库依旧失败**
![image](https://user-images.githubusercontent.com/252830/95849369-f5c1e780-0d81-11eb-9dbe-ec958b13ee71.png)

**Comment by liuyq-617** [comment]
把IP地址修改一下，不能在服务端使用127.0.0.1

**Comment by qiuyan0528** [comment]
地址修改了仍然不行
![image](https://user-images.githubusercontent.com/252830/95947347-f9f11200-0e20-11eb-9ce7-c4a22c3449c5.png)

![image](https://user-images.githubusercontent.com/252830/95947498-53594100-0e21-11eb-8b86-d67de46db931.png)

**Comment by liuyq-617** [comment]
你先进入docker里，然后输入taos登录。show dnodes 这个命令查看一下，查一下目前的FQDN是什么？
如果和你配置的不一样，就把之前的数据文件删除了，然后再启动docker

**Comment by qiuyan0528** [comment]
![Uploading image.png…]()

**Comment by liuyq-617** [comment]
* 删除原有的数据文件，默认在服务端的/var/lib/taos。如果有映射的时候，就把映射的文件给删除
* 重启服务端，再去连接

**Comment by qiuyan0528** [comment]
问题解决，十分感谢
