### ISSUE TITLE
selector funcs support transform funcs

### ISSUE THREAD

**Issue by songtianyi** [taosdata/TDengine#3839]
**Describe your desired behavior**
```
taos> select MAX(ts_out - ts_in) from gate_99;

DB error: invalid SQL: invalid parameters
taos>
```
Any plan for this operation?

**Comment by hjxilinx** [comment]
Yes，this function is in our development roadmap.

**Comment by hjxilinx** [comment]
This issue was closed because it has been inactive for too many days.
