### ISSUE TITLE
GO  并发写入时，遇到invalid DB

### ISSUE THREAD

**Issue by vonlippmann** [taosdata/TDengine#384]
我在testdb 库中创建了10个表，我试图使用10个协程并发的向10个表中写入时序数据，以观测写入性能，代码如下;

``` go
//rows 表示要向该表中插入多少行数据
//insertData 将会向指定的表中插入随机生成的rows行数据
func testQpsInsert(db *sql.DB,tableList []string,num int64,rows int64){
	for _,table:= range tableList{
		wg.Add(1)
		go insertData(db,table,rows)
	}
	wg.Wait()
}
```
但是这样会遇到invalid DB 错误
如果我串行的执行就没有问题，代码如下：
```go
//rows 表示要向该表中插入多少行数据
//insertData 将会向指定的表中插入随机生成的rows行数据
func testQpsInsert(db *sql.DB,tableList []string,num int64,rows int64){
	for _,table:= range tableList{
		insertData(db,table,rows)
	}
}
```
同样的，如果我试图使用协程并发的创建表时，总是只能创建一部分，然后报未选择数据库的错误。

是我代码写的有问题还是怎么回事？还请不吝赐教

**Comment by plum-lihui** [comment]
您好！感谢使用tdengine。您的这个问题是这样的：单个数据库连接，在同一时刻只能有一个线程调用API。客户应用可以建立多个连接，进行多线程的数据写入或查询处理。
所以，要测试多线程并发写入性能的话，每个线程要独立创建连接，也就是代码中db *sql.DB，各个线程自己创建与数据库的链接。

**Comment by vonlippmann** [comment]
那是不是意味着用db.setMaxOpenConns来设置池中最大连接数是没有意义的，因为任何时候都只能有一个线程能接入连接池，也就是本质上并没有数据库连接池。

所以如果我有10000个表，假设我开10000个协程，那么我要创建10000个数据库连接，这可能不太好。

因此也就是意味着，我只能创建适当的协成，比如100个，然后每个协程顺序的去处理100个表，而不是1个协程1个表，是这样吗？

**Comment by plum-lihui** [comment]
目前tdengine实现的go driver只是go/sql/driver的一个子集，并不受连接池限制。
客户端和服务端都没有连接数的限制，只要资源足够，理论上是可以建立足够多的链接。
实际使用中，可以根据业务的需要来建立连接。后面你描述的是正确的。
