### ISSUE TITLE
order by count(*) limit 100...will this feature be supported?

### ISSUE THREAD

**Issue by mxmkeep** [taosdata/TDengine#3848]
order by count(*) limit 100
请问有计划支持数据top n的功能么？
这个功能对业务比较重要

**Comment by hjxilinx** [comment]
按照聚合结果排序？
暂时还没有安排到开发序列中。

**Comment by mxmkeep** [comment]
> 按照聚合结果排序？
> 暂时还没有安排到开发序列中。

是的，例如 select count(*) as ss from tab1 group by col1 order by ss desc limit 100;
这样才能取top的数据，不然需要把大量数据取回在自己程序里排序

**Comment by hjxilinx** [comment]
好的，这部分功能还没有暂没有列入计划中。

**Comment by peterchenhdu** [comment]
有同样需求，不知道支持了没

**Comment by korimas** [comment]
也需要这个功能

**Comment by shaoguanlee** [comment]
同上,希望该功能能加入开发计划

**Comment by hjxilinx** [comment]
本年度发布的 3.0 版本会提供该功能的支持。
