### ISSUE TITLE
BINARY 长度设置255 实际插入时只插入字符串前30个字节

### ISSUE THREAD

**Issue by ChuTingxu** [taosdata/TDengine#3855]
描述：
数据表中一个字段设置为长度255的binary，但实际插入时发现只有前30个字节的字符串成功插入表中。
版本：
ver-2.0.4.0
创建库：
create database testtable
创建表
CREATE TABLE gc_fuse_super (revTime timestamp,targetId int,targetIdsOrig binary(255),targetHkType TINYINT,targetType smallint,targetLevel smallint,log double,lat double,height float,direction float
,heading smallint,speed float,status tinyint,rot smallint,targetName binary(30),callSign binary(20),imo int,destn binary(20),eta binary(30),draft float,countryId binary(3),countryName binary(255),
length smallint,breadth smallint,sf binary(255))  TAGS (tagFuseId int, tagHkType TINYINT);
插入：
INSERT INTO gc_fuse_0001 USING gc_fuse_super TAGS (5511,1) VALUES (1602571239000 ,5511,"208945~308445~805945~507445",1,11,0,38.19831008309901,46.77803316959258,0.0,319.2692565917969,319,6.435270309448242,0,0,"TEKHFLOTETS","AB",0,"",""
,0.0,"0","格陵兰",0,0,'{"toStern":0,"fixin":0,"toStarboard":0,"toPort":0,"toBow":0,"aisClass":0}');
Query OK, 1 row(s) affected (0.034703s)xin":0,"toStarboard":0,"toPort":0,"toBow":0,"aisClass":0}');
查询：
select sf from gc_fuse_0001;
结果:
               sf               |
=================================
 {"toStern":0,"fixin":0,"toStar |
Query OK, 1 row(s) in set (0.004316s)
注：sf字段设置为255长度binary ，插入数据'{"toStern":0,"fixin":0,"toStarboard":0,"toPort":0,"toBow":0,"aisClass":0}'，实际表中数据 {"toStern":0,"fixin":0,"toStar

**Comment by xiaopingcs** [comment]
不是只插入了前30个字节，是terminal默认显示的长度为30。你可以在 terminal 中通过命令 set max_binary_display_width 255动态修改此选项。看数据是否可以完全显示。

**Comment by ChuTingxu** [comment]
是可以显示，谢谢。
另外还有个问题请教下TDengine Error: invalid SQL: '' (invalid int data)
这个报错是sql语句中有字符的数据不合法？还是有int类型数据不合法？没怎么理解什么意思




> 
> 
> 不是只插入了前30个字节，是terminal默认显示的长度为30。你可以在 terminal 中通过命令 set max_binary_display_width 255动态修改此选项。看数据是否可以完全显示。

**Comment by xiaopingcs** [comment]
> 是可以显示，谢谢。
> 另外还有个问题请教下TDengine Error: invalid SQL: '' (invalid int data)
> 这个报错是sql语句中有字符的数据不合法？还是有int类型数据不合法？没怎么理解什么意思
> 
> > 不是只插入了前30个字节，是terminal默认显示的长度为30。你可以在 terminal 中通过命令 set max_binary_display_width 255动态修改此选项。看数据是否可以完全显示。

int 类型的数据范围是[-2^31+1, 2^31-1], -2^31用作Null
可能你的int类型数据越界了，也可能是别的问题，需要看具体的sql语句。

**Comment by airx** [comment]
这个terminal显示设定也太扯了，以为是本身bug，还清空表，又用新机器重新安装。
