### ISSUE TITLE
windows driver is x86，but C:\TDengine\driver\taos.dll is x64

### ISSUE THREAD

**Issue by rennner** [taosdata/TDengine#3864]
windows驱动安装完x86版本为什么C:\TDengine\driver\taos.dll 还是x64位的?

特意又安装了64位版本，md5结果是一样的，不知道是什么情况。

**Comment by rennner** [comment]
安装的2.0.5.1版本客户端

**Comment by plum-lihui** [comment]
不好意思，这个打包的时候出了点问题，我们正处理，马上修复。

**Comment by rennner** [comment]
请问正确的x86驱动什么时候能发布？

**Comment by rennner** [comment]
官方已更新。
