### ISSUE TITLE
How to create a query variable in Grafana?

### ISSUE THREAD

**Issue by zjli-2019** [taosdata/TDengine#3869]
I have create a query variable in Grafana, but nothing is displayed in the dropdown list of the variable.

The query can validated in a Panel, showing that it will give a list of Array.

**Comment by Aries-Lee1991** [comment]
can u provide more info.?such as the version, the steps, and the screenshot？

**Comment by zjli-2019** [comment]
I have created a stable like this:

```shell
create database crash;
use crash;
create table thermo_data ( ts timestamp, temperature float ) TAGS ( dev_id NCHAR(20) );
```

Insert some data:

```sql
insert into aaa using thermo_data tags ("FB:CD:99:33:12:EF") values (now, 222.3) ;
insert into abb using thermo_data tags ("FC:CD:99:33:12:EF") values (now, 222.3) ;
```

Now I want the variable containing the list of `dev_id`s, so the query is:

```sql
select dev_id from crash.thermo_data
```

But nothing is shown in the dropdown list of the variable.

**Comment by liuyq-617** [comment]
Not supported yet

**Comment by 784134748** [comment]
When will this feature be supported

**Comment by liuyq-617** [comment]
> When will this feature be supported
is already supported
