### ISSUE TITLE
binaray(100)是变长么？

### ISSUE THREAD

**Issue by lnparker** [taosdata/TDengine#387]
比如我定义某个字段是binary(100)，那么如果某一条记录该字段只有20个字符，是只占用20个字符的空间，而不是100个么?

**Comment by lnparker** [comment]
如果超过100个，比如某一条记录该字段只有300个字符，会自动扩展么

**Comment by plum-lihui** [comment]
是固定长度的，只有20个字符，也是预留100字节；如果超过100，则会自动截取到100。
