### ISSUE TITLE
how to group by day or minute?

### ISSUE THREAD

**Issue by mxmkeep** [taosdata/TDengine#3872]
我想按天或按分钟统计数据
但td不支持DATE_FORMAT() 函数
而且还不支持按timestamp group by？
请问要实现这样的统计，SQL可以怎么写？

**Comment by localvar** [comment]
使用 interval，例如：
`select count(*) from meters interval(1m);`
会每分钟生成一条数据。

**Comment by mxmkeep** [comment]
> 使用 interval，例如：
> `select count(*) from meters interval(1m);`
> 会每分钟生成一条数据。

thanks
