### ISSUE TITLE
How to judge whether the table is created successfully

### ISSUE THREAD

**Issue by wodejavazuihao29** [taosdata/TDengine#3874]
现在，有个需求，就是动态创建表后，判断一下是否成功，MySQL里面有个information_schema表可以查询是否存在，不知道 TDengine有没有

**Comment by Aries-Lee1991** [comment]
> 现在，有个需求，就是动态创建表后，判断一下是否成功，MySQL里面有个information_schema表可以查询是否存在，不知道 TDengine有没有

taos> DESCRIBE 表名;

**Comment by wodejavazuihao29** [comment]
好的，谢谢
