### ISSUE TITLE
Rename table, field, or extend nchar length

### ISSUE THREAD

**Issue by lauthrul** [taosdata/TDengine#3875]
Highly recommend some feature support of basic table alter operations, such as **rename table**, **rename field**, or **extend nchar length**. Currently, there is only one way to change a table structure: adding a new one and delete the old one, but this will loss data for the table.
I know tdengine is not allow to modify data, but these operations have no affection with datas. Please considering supporting these features, thanks!

**Comment by zyyang-taosdata** [comment]
感谢您的建议，目前仅支持直接修改标签列的名称。
ALTER TABLE stb_name CHANGE TAG old_tag_name new_tag_name;
如果在查询中需要改名可以使用select as：
select fieldName as newName from tbName
我们会后面的版本升级中考虑您的意见，非常感谢～

**Comment by tomuGo** [comment]
可以自己维护字段的对应关系,查询保存的时候,用修改前的字段

**Comment by yu285** [comment]
nchar 扩展已经支持，rename table /filed 可以通过企业版的视图来变相支持
