### ISSUE TITLE
Python query NCHAR data but the result is None

### ISSUE THREAD

**Issue by Lao-Zhong** [taosdata/TDengine#3878]
Python通过JDBC的方式查询NCHAR类型的字段数据为None，读取不出，在shell终端下查询返回正常数据，请问这是什么原因？配置文件里的charset是UTF-8

**Comment by sangshuduo** [comment]
Python 通过 JDBC 的方式。。。

能详细描述一下吗？

**Comment by Lao-Zhong** [comment]
> Python通过JDBC的方式。。。
> 
> 能详细描述一下吗？

taos.connect(host='127.0.0.1', port=6020, user='root', password='123456', database='bd', config="/etc/taos", charset="UTF-8")

**Comment by sangshuduo** [comment]
port 为什么是 6020？

**Comment by zyyang-taosdata** [comment]
TDengine的默认端口是6030

**Comment by cddonald** [comment]
我也遇到了一样的问题，python 读出的中文数据是None

**Comment by sangshuduo** [comment]
@cddonald  可以详细描述一下如何重现吗？

**Comment by sangshuduo** [comment]
没有更新，关闭。
