### ISSUE TITLE
修改表结构报错

### ISSUE THREAD

**Issue by wsf1990** [taosdata/TDengine#388]
修改表结构，报错如下：

```
taos> ALTER TABLE table_name DROP COLUMN test;

TSDB error: App error
```

**Comment by wsf1990** [comment]
还有一个问题：通过脚本修改字段后，在shell脚本中describe看不到变化情况，必须断开shell重新连接才可以看到变化。

**Comment by hjxilinx** [comment]
shell端有一个cache用来缓存schema。您可以强制reset使用如下命令：
reset query cache.

对于第一个问题，您那里有关于该表的schema信息提供吗？

**Comment by wsf1990** [comment]
我想第一个问题应该跟第二个问题有关系，大概是我使用脚本修改了之后，在客户端又alter，但并未清理缓存，所以出错了。

**Comment by sangshuduo** [comment]
还有这个问题吗？我们新发布了 2.0 版本，请试用一下新版本

**Comment by wsf1990** [comment]
好的，最近没有用到这个，用的时候我测试一下，谢谢！

**Comment by sangshuduo** [comment]
也可以加入我们的技术讨论群随时交流

![](https://www.taosdata.com/assets/images/tdengine.png)
