### ISSUE TITLE
'group by tbname limit'  DOESN'T WORK

### ISSUE THREAD

**Issue by Jerry-Kwok** [taosdata/TDengine#3884]
RELATED SQL:
create table position (ts timestamp, lon double, lat double) tags (equip_no binary(50));

insert into position_1 using position tags ('vcl-1') values 
('2020-07-08 22:50:00.001',114.1,38.2),
('2020-08-08 21:40:02.021',115.1,37.2),
('2020-09-08 13:10:53.321',120.12,25.9);

insert into position_2 using position tags ('vcl-2') values 
('2020-07-09 02:42:00.001',114.51,38.62),
('2020-08-09 15:43:32.021',125.41,55.2),
('2020-09-09 23:40:33.321',123.12,35.9);

select last_row(ts) as ts, last_row(lon) as lon, last_row(lat) as lat, equip_no from position group by tbname limit 1;

BUT I GOT 2 ROWS, GROUP BY TBNAME LIMIT 1 DOESN'T WORK

**Comment by localvar** [comment]
please use `slimit` instead of `limit` in this case, refer: https://github.com/taosdata/TDengine/issues/3623

**Comment by Jerry-Kwok** [comment]
thanks!

**Comment by shaoguanlee** [comment]
我有一个问题,为何要引入`slimit`和`soffset`这两个新的概念呢?TDengine自身应该是知道`limit`是想分页的吧?`slimit`为何不在数据库内部处理了呢?
