### ISSUE TITLE
jdbc连接问题

### ISSUE THREAD

**Issue by nzxxs4** [taosdata/TDengine#3888]
`public class test {
    public static void main(String[] args) throws Exception {
        Class.forName("com.taosdata.jdbc.TSDBDriver");
        String jdbcUrl = "jdbc:TAOS://192.168.1.100:6030/udb?user=root&password=taosdata";
        Connection connection = DriverManager.getConnection(jdbcUrl);

        Statement stmt = connection.createStatement();
        stmt.executeUpdate("create database if not exists db");
        stmt.executeUpdate("use db");
        stmt.executeUpdate("create table if not exists tb (ts timestamp, temperature int, humidity float)");
    }
}`

有这个数据库，请教，为啥连不上呢

**Comment by zyyang-taosdata** [comment]
先检查你的运行环境，是否安装了TDengine的客户端，使用客户端的shell是否能正常连接到taosd实例。另外，提问的时候请把报错信息贴出来。

**Comment by ewsq** [comment]
要注意jdbc的版本要匹配，即的TDengine-client-2.0.5.1-Windows-x64.exe版本也要匹配，目前他们2.+和1.+是不能混用的。这两个都需要与服务器端的版本一致。

**Comment by nzxxs4** [comment]
多谢两位 @ewsq @zyyang-taosdata 我按照两位的检查替换之后报错“Unexpected generic error in RPC”
而后参考https://www.taosdata.com/cn/documentation/faq/第6条 已经解决，感谢帮助
