### ISSUE TITLE
一边自动创建表，一边查询子表数量，发现子表数变少的情况。

### ISSUE THREAD

**Issue by quchunhui** [taosdata/TDengine#3889]
**Bug Description**
写了一个大批量插入数据的java测试程序（为了测试单列模式），程序中生成如下所示SQL，持续插入数据。
insert into product1_device2_ai_point1 using st_device_data_up tags ("Product1","Device1","AI_POINT1","测点1","double","0","100000","1","℃","测点描述1") values ("2020-10-16 16:58:32.277",3258);

这时候在控制台使用select count(tbname) from st_device_data_up语句查询子表数量，发现存在数量变少的情况，而实际上是一直在增加的。

**To Reproduce**
暂时不知道如何再现

**Screenshots**
![image](https://user-images.githubusercontent.com/18110478/96266236-016b1380-0ff9-11eb-833d-46c2e8e0ba8f.png)

**Environment (please complete the following information):**
 - OS: Linux Centos8
 - Memory, CPU, current Disk Space：8核16GB
 - TDengine Version：2.5.0.1

**Additional Context**
子表数量与实际相符

**Comment by hjxilinx** [comment]
最终的表的数量正确吗？

**Comment by yihaoDeng** [comment]
你好， 我在本地做这个浮现工作， 多个线程插入数据自动建表， 并且一个读线程持续读子表的数量，都没有能浮现你所说的情况， 按照你的方式， 最后子表的数量符合预期吗？ @quchunhui

**Comment by lzqdename** [comment]
用HTTP插入的方式，基本100%复现

**Comment by quchunhui** [comment]
先关闭，在新版本测试，发现问题再说

**Comment by hjxilinx** [comment]
请问新版本有这个问题吗？
