### ISSUE TITLE
使用R连接TAOS

### ISSUE THREAD

**Issue by Accelerator-BUGS** [taosdata/TDengine#389]
我在按文档内容使用R通过JDBC接口连接数据库时：
> drv<-JDBC("com.taosdata.jdbc.TSDBDriver","JDBCDriver-1.0.0-dist.jar", identifier.quote="\"")
Error in .jfindClass(as.character(driverClass)[1]) : 
  java.lang.ClassNotFoundException

应该是没有TDengine的JDBC驱动，但是我找不到在哪里可以获取。

**Comment by plum-lihui** [comment]
安装完成后，在安装目录/usr/local/taos下，有一个connector的目录，里面有jdbc的驱动

**Comment by Accelerator-BUGS** [comment]
十分感谢，第一步已经成功实现，我把taos-jdbcdriver-1.0.1-dist.jar放在了Java\jre1.8.0_221\lib\ext文件夹中。但是在执行第二步时再次出现了问题。
> drv<-JDBC("com.taosdata.jdbc.TSDBDriver","taos-jdbcdriver-1.0.1-dist.jar", identifier.quote="\"")
> conn<-dbConnect(drv,"jdbc:TSDB://10.111.18.141:3838/?user=root&password=taosdata","root","taosdata")
Error in .jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", as.character(url)[1],  : 
  java.lang.NoClassDefFoundError: Could not initialize class com.taosdata.jdbc.TSDBJNIConnector
我不太懂JAVA，查了一下大概是因为没有这个类，但是在jar中是有找到TSDBJNIConnector这个类的，不知道是哪里出现了问题。

补充：Window10 R3.5.3 尝试连接Ubuntu18.10的TAOS数据库

**Comment by sangshuduo** [comment]
还有这个问题吗？我们新发布了 2.0 版本，请试用一下新版本

**Comment by TommyLemon** [comment]
taos-jdbcdriver 2.0.38 也有这个问题
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/5738175/179292115-5bebb82e-c1c9-4e0e-8597-5223feb1796e.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/5738175/179292246-a8dd11e6-8ad1-4805-9c48-243625267742.png">

```xml
    <dependency>
      <groupId>com.taosdata.jdbc</groupId>
      <artifactId>taos-jdbcdriver</artifactId>
      <version>2.0.38</version>
    </dependency>
```
