### ISSUE TITLE
TDengine是否可以使用子查询 / TDengine是否有对时间操作的时间函数

### ISSUE THREAD

**Issue by wy-w** [taosdata/TDengine#3894]
![5d2e076fa5e0ae17e7695e88951de1a](https://user-images.githubusercontent.com/55778678/96331740-5b6be780-1092-11eb-8c8b-7cdcc9117f20.png)
文档没有相关查询样例

**Comment by sangshuduo** [comment]
select t1 from table\_1 union all select t1 from table\_2;

**Comment by wy-w** [comment]
> 从table_1中选择t1，并全部从table_2中选择t1；
能简单地用sql表达下么

**Comment by wy-w** [comment]
咱们这边有没有对时间进行操作的函数
