### ISSUE TITLE
server crashed when windows's client connected

### ISSUE THREAD

**Issue by cleverpig** [taosdata/TDengine#3897]
**Bug Description**
I used windows client(version 2.0.5.1) connect to server side(version 2.0.5.1)  on centos7, but server crashed and reported this backtrace.
======= Backtrace: =========
/lib64/libc.so.6(+0x81299)[0x7f929e2cd299]
/app/install/git-storage/TDengine/debug/build/lib/libtaos.so.1(rpcFreeCont+0x2d)[0x7f929ee53f62]
taosd(mnodeCleanupMsg+0x34)[0x4279d6]
taosd[0x415d89]
taosd[0x415e35]
taosd[0x415f1f]
/lib64/libpthread.so.0(+0x7ea5)[0x7f929e621ea5]
/lib64/libc.so.6(clone+0x6d)[0x7f929e34a8dd]
======= Memory map: ========
00400000-004cd000 r-xp 00000000 fd:00 14232332                           /usr/local/taos/bin/taosd
006cc000-006cd000 r--p 000cc000 fd:00 14232332                           /usr/local/taos/bin/taosd
006cd000-006d0000 rw-p 000cd000 fd:00 14232332                           /usr/local/taos/bin/taosd
006d0000-006d4000 rw-p 00000000 00:00 0 
01804000-01a71000 rw-p 00000000 00:00 0                                  [heap]
7f9238000000-7f9238022000 rw-p 00000000 00:00 0 
7f9238022000-7f923c000000 ---p 00000000 00:00 0 
7f9240000000-7f9240021000 rw-p 00000000 00:00 0 
7f9240021000-7f9244000000 ---p 00000000 00:00 0 
7f9244000000-7f9244035000 rw-p 00000000 00:00 0 
7f9244035000-7f9248000000 ---p 00000000 00:00 0 
7f9248000000-7f9248021000 rw-p 00000000 00:00 0 
7f9248021000-7f924c000000 ---p 00000000 00:00 0 
7f924c000000-7f924c021000 rw-p 00000000 00:00 0 
7f924c021000-7f9250000000 ---p 00000000 00:00 0 
7f9250000000-7f9250021000 rw-p 00000000 00:00 0 
7f9250021000-7f9254000000 ---p 00000000 00:00 0 
7f9254000000-7f9254021000 rw-p 00000000 00:00 0 
7f9254021000-7f9258000000 ---p 00000000 00:00 0 
7f9258000000-7f9258021000 rw-p 00000000 00:00 0 
7f9258021000-7f925c000000 ---p 00000000 00:00 0 
7f925f7ff000-7f925f800000 ---p 00000000 00:00 0 
7f925f800000-7f9260000000 rw-p 00000000 00:00 0 
7f9260000000-7f9260021000 rw-p 00000000 00:00 0 
7f9260021000-7f9264000000 ---p 00000000 00:00 0 
7f9264000000-7f9264075000 rw-p 00000000 00:00 0 
7f9264075000-7f9268000000 ---p 00000000 00:00 0 
7f9268000000-7f9268021000 rw-p 00000000 00:00 0 
7f9268021000-7f926c000000 ---p 00000000 00:00 0 
7f926c7e9000-7f926c7ea000 ---p 00000000 00:00 0 
7f926c7ea000-7f926cfea000 rw-p 00000000 00:00 0 
7f926cfea000-7f926cfeb000 ---p 00000000 00:00 0 
7f926cfeb000-7f926d7eb000 rw-p 00000000 00:00 0 
7f926d7eb000-7f926d7ec000 ---p 00000000 00:00 0 
7f926d7ec000-7f926dfec000 rw-p 00000000 00:00 0 
7f926dfec000-7f926dfed000 ---p 00000000 00:00 0 
7f926dfed000-7f926e7ed000 rw-p 00000000 00:00 0 
7f926e7ed000-7f926e7ee000 ---p 00000000 00:00 0 
7f926e7ee000-7f926efee000 rw-p 00000000 00:00 0 
7f926efee000-7f926efef000 ---p 00000000 00:00 0 
7f926efef000-7f926f7ef000 rw-p 00000000 00:00 0 
7f926f7ef000-7f926f7f0000 ---p 00000000 00:00 0 
7f926f7f0000-7f926fff0000 rw-p 00000000 00:00 0 
7f926fff0000-7f926fff1000 ---p 00000000 00:00 0 
7f926fff1000-7f92707f1000 rw-p 00000000 00:00 0 
7f92707f1000-7f92707f2000 ---p 00000000 00:00 0 
7f92707f2000-7f9270ff2000 rw-p 00000000 00:00 0 
7f9270ff2000-7f9270ff3000 ---p 00000000 00:00 0 
7f9270ff3000-7f92717f3000 rw-p 00000000 00:00 0 
7f92717f3000-7f92717f4000 ---p 00000000 00:00 0 
7f92717f4000-7f9271ff4000 rw-p 00000000 00:00 0 
7f9271ff4000-7f9271ff5000 ---p 00000000 00:00 0 
7f9271ff5000-7f92727f5000 rw-p 00000000 00:00 0 
7f92727f5000-7f92727f6000 ---p 00000000 00:00 0 
7f92727f6000-7f9272ff6000 rw-p 00000000 00:00 0 
7f9272ff6000-7f9272ff7000 ---p 00000000 00:00 0 
7f9272ff7000-7f92737f7000 rw-p 00000000 00:00 0 
7f92737f7000-7f92737f8000 ---p 00000000 00:00 0 
7f92737f8000-7f9273ff8000 rw-p 00000000 00:00 0 
7f9273ff8000-7f9273ff9000 ---p 00000000 00:00 0 
7f9273ff9000-7f92747f9000 rw-p 00000000 00:00 0 
7f92747f9000-7f92747fa000 ---p 00000000 00:00 0 
7f92747fa000-7f9274ffa000 rw-p 00000000 00:00 0 
7f9274ffa000-7f9274ffb000 ---p 00000000 00:00 0 
7f9274ffb000-7f92757fb000 rw-p 00000000 00:00 0 
7f92757fb000-7f92757fc000 ---p 00000000 00:00 0 
7f92757fc000-7f9275ffc000 rw-p 00000000 00:00 0 
7f9275ffc000-7f9275ffd000 ---p 00000000 00:00 0 
7f9275ffd000-7f92767fd000 rw-p 00000000 00:00 0 
7f92767fd000-7f92767fe000 ---p 00000000 00:00 0 
7f92767fe000-7f9276ffe000 rw-p 00000000 00:00 0 
7f9276ffe000-7f9276fff000 ---p 00000000 00:00 0 
7f9276fff000-7f92777ff000 rw-p 00000000 00:00 0 
7f92777ff000-7f9277800000 ---p 00000000 00:00 0 
7f9277800000-7f9278000000 rw-p 00000000 00:00 0 
7f9278000000-7f9278021000 rw-p 00000000 00:00 0 
7f9278021000-7f927c000000 ---p 00000000 00:00 0 
7f927c3ce000-7f927c3e3000 r-xp 00000000 fd:00 84                         /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f927c3e3000-7f927c5e2000 ---p 00015000 fd:00 84                         /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f927c5e2000-7f927c5e3000 r--p 00014000 fd:00 84                         /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f927c5e3000-7f927c5e4000 rw-p 00015000 fd:00 84                         /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f927c5e4000-7f927c5e5000 ---p 00000000 00:00 0 
7f927c5e5000-7f927cde5000 rw-p 00000000 00:00 0 
7f927cde5000-7f927cdf1000 r-xp 00000000 fd:00 34832                      /usr/lib64/libnss_files-2.17.so
7f927cdf1000-7f927cff0000 ---p 0000c000 fd:00 34832                      /usr/lib64/libnss_files-2.17.so
7f927cff0000-7f927cff1000 r--p 0000b000 fd:00 34832                      /usr/lib64/libnss_files-2.17.so
7f927cff1000-7f927cff2000 rw-p 0000c000 fd:00 34832                      /usr/lib64/libnss_files-2.17.so
7f927cff2000-7f9282ffe000 rw-p 00000000 00:00 0 
7f9282ffe000-7f9282fff000 ---p 00000000 00:00 0 
7f9282fff000-7f92837ff000 rw-p 00000000 00:00 0 
7f92837ff000-7f9283800000 ---p 00000000 00:00 0 
7f9283800000-7f9284000000 rw-p 00000000 00:00 0 
7f9284000000-7f928405d000 rw-p 00000000 00:00 0 
7f928405d000-7f9288000000 ---p 00000000 00:00 0 
7f9288000000-7f9288021000 rw-p 00000000 00:00 0 
7f9288021000-7f928c000000 ---p 00000000 00:00 0 
7f928c000000-7f928c12e000 rw-p 00000000 00:00 0 
7f928c12e000-7f9290000000 ---p 00000000 00:00 0 
7f92900e6000-7f92903e9000 rw-p 00000000 00:00 0 
7f92903e9000-7f92903ea000 ---p 00000000 00:00 0 
7f92903ea000-7f9290bea000 rw-p 00000000 00:00 0 
7f9290bea000-7f9290beb000 ---p 00000000 00:00 0 
7f9290beb000-7f92913eb000 rw-p 00000000 00:00 0 
7f92913eb000-7f92913ec000 ---p 00000000 00:00 0 
7f92913ec000-7f9291bec000 rw-p 00000000 00:00 0 
7f9291bec000-7f9291bed000 ---p 00000000 00:00 0 
7f9291bed000-7f92923ed000 rw-p 00000000 00:00 0 
7f92923ed000-7f92923ee000 ---p 00000000 00:00 0 
7f92923ee000-7f9292bee000 rw-p 00000000 00:00 0 
7f9292bee000-7f9292bef000 ---p 00000000 00:00 0 
7f9292bef000-7f92933ef000 rw-p 00000000 00:00 0 
7f92933ef000-7f92933f0000 ---p 00000000 00:00 0 
7f92933f0000-7f9293bf0000 rw-p 00000000 00:00 0 
7f9293bf0000-7f9293bf1000 ---p 00000000 00:00 0 
7f9293bf1000-7f92943f1000 rw-p 00000000 00:00 0 
7f92943f1000-7f92943f2000 ---p 00000000 00:00 0 
7f92943f2000-7f9294bf2000 rw-p 00000000 00:00 0 
7f9294bf2000-7f9294bf3000 ---p 00000000 00:00 0 
7f9294bf3000-7f92954b0000 rw-p 00000000 00:00 0 
7f92954b0000-7f92954b1000 ---p 00000000 00:00 0 
7f92954b1000-7f9295cb1000 rw-p 00000000 00:00 0 
7f9295cb1000-7f9295cb2000 ---p 00000000 00:00 0 
7f9295cb2000-7f9296507000 rw-p 00000000 00:00 0 
7f9296507000-7f9296508000 ---p 00000000 00:00 0 
7f9296508000-7f9296d08000 rw-p 00000000 00:00 0 
7f9296d08000-7f9296d09000 ---p 00000000 00:00 0

**Environment (please complete the following information):**
 - Server OS: [CentOS 7.0]
 - Client OS: [Windows 10]
 - TDengine Version [2.0.5.1] — compiled by source code on github.

**Comment by sangshuduo** [comment]
Thanks for your reporting. It might be the same issue we just fixed. Please try the next version.

**Comment by cleverpig** [comment]
Ok!
I found this exception caused by compiled taosd server.
So I switch to the offical version,the exception gone.

**Comment by sangshuduo** [comment]
Got it. Please don't use compiled software for the product using purpose. It would be not quite stable.
