### ISSUE TITLE
java.sql.SQLException: TDengine Error: Unable to resolve FQDN

### ISSUE THREAD

**Issue by ewsq** [taosdata/TDengine#3899]
**Bug Description**
java.sql.SQLException: TDengine Error: Unable to resolve FQDN

**To Reproduce**
1. 在某机上安装好“TDengine-server-2.0.5.1”
2. 安装“TDengine-client-2.0.5.1-Windows-x64.exe”
3. java客户端导包
<dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>2.0.4</version>
        </dependency>
4.编辑示例
package com.vcare.taos.demo;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;

public class HikariCPDemo {
    public static void main(String[] args) throws SQLException {
        HikariConfig config = new HikariConfig();
        //config.setDataSourceClassName("com.taosdata.jdbc.TSDBDriver");
        config.setJdbcUrl("jdbc:TAOS://192.168.10.234:6030/db");
        //jdbc:TAOS://192.168.10.112:6020/?user=root&password=taosdata
        config.setUsername("root");
        config.setPassword("taosdata");
        config.setMinimumIdle(3);           //minimum number of idle connection
        config.setMaximumPoolSize(10);      //maximum number of connection in the pool
        config.setConnectionTimeout(10000); //maximum wait milliseconds for get connection from pool
        config.setIdleTimeout(60000);       // max idle time for recycle idle connection
        //config.setConnectionTestQuery("describe db.dn"); //validation query
        config.setValidationTimeout(3000);   //validation query timeout
        HikariDataSource ds = new HikariDataSource(config); //create datasource
        Connection connection = ds.getConnection(); // get connection
        Statement statement = connection.createStatement(); // get statement
        //query or insert
        try {
            HashMap hm = null;
            boolean IsLowerCase = true;
            String sqlStr="select * from t where ts>='2019-07-01 00:00:00' and ts<'2019-07-23 00:00:00'";
            ResultSet rs = statement.executeQuery(sqlStr);
            int colCnt = rs.getMetaData().getColumnCount();
            while (rs.next()) {
                hm = new HashMap();
                for (int i = 1; i <= colCnt; i++) {
                    if(IsLowerCase){
                        hm.put(rs.getMetaData().getColumnName(i).toLowerCase(),getString(rs.getString(i)));
                    }else{
                        hm.put(rs.getMetaData().getColumnName(i),getString(rs.getString(i)));
                    }

                    System.out.println("=================================================================:");
                    if(IsLowerCase){
                        System.out.println(rs.getMetaData().getColumnName(i).toLowerCase()+ "::" + rs.getString(i));
                    }else{
                        System.out.println(rs.getMetaData().getColumnName(i)+ "::" + rs.getString(i));
                    }
                    System.out.println(rs.getMetaData().getColumnName(i)+ "::" + rs.getString(i));
                    System.out.println("=================================================================:");

                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
        }
        connection.close(); // put back to conneciton pool
    }
    public static String getString(String getStringValue) throws SQLException {
        return getStringValue == null ? "" : getStringValue;
    }
}
5.运行后提示：java.sql.SQLException: TDengine Error: Unable to resolve FQDN
6.根据提示猜测，需要修改客户端hosts，这里这样做的目的是什么？为什么要让客户端必须配置FQDN呢？而代码中明明是可以写IP地址的，这样做是不是不太友好？影响入门应用？建议降低这个门槛，很不人不一定明白为什么要修改hosts。如果说配置集群之间，这个还可以理解，这个直接限制客户端应用，感觉不是太好。

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Comment by sangshuduo** [comment]
在 Windows 上用 taos -h 可以连吗？

**Comment by ewsq** [comment]
taos -h 在windows下执行显示：'taos' 不是内部或外部命令，也不是可运行的程序或批处理文件。

**Comment by ewsq** [comment]
这个问题没有验证一下吗？要配置客户机hosts有些奇怪，如果我的程序与服务器不放在一个网络怎么办？

**Comment by sangshuduo** [comment]
FQDN设计的目的就是如果域名，即使 IP 地址修改也无需改应用

顺便说，在 Windows 上默认安装在 C:/TDengine 目录下，执行 taos.exe

**Comment by ewsq** [comment]
> FQDN设计的目的就是如果域名，即使 IP 地址修改也无需改应用
> 
> 顺便说，在 Windows 上默认安装在 C:/TDengine 目录下，执行 taos.exe

谢谢，象这种连接信息一般都在程序的配置文件中写着，改config不比改hosts来得容易？hosts是系统级文件，建议还是不要这样的好。一般的数据库都没有这样做的，感觉这样做也没有什么好处。

**Comment by yejuns** [comment]
在你的windows系统C盘下应该有个TDengine文件夹，里面有taos.exe，就是连接到server的client，要在这里执行taos -h。我这边虽然可以连接过去，但依然会出现 
`DB error: Unable to resolve FQDN`

**Comment by yejuns** [comment]
> taos -h 在windows下执行显示：'taos' 不是内部或外部命令，也不是可运行的程序或批处理文件。

在你的windows系统C盘下应该有个TDengine文件夹，里面有taos.exe，就是连接到server的client，要在这里执行taos -h。我这边虽然可以连接过去，但依然会出现
`DB error: Unable to resolve FQDN`
请问你通过JDBC接入成功了吗？该如何配置呢？谢谢。

**Comment by yejuns** [comment]
我在配置完服务器的FQDN后，使用JDBC仍旧显示`DB error: Unable to resolve FQDN`,在windows客户端使用tans也是一样的结果，具体情况如图片所示：
![image](https://user-images.githubusercontent.com/28998248/96559458-aafb1f00-12ef-11eb-9d79-bfe6fa2015ad.png)
能ping通，说明FQDN配置成功。但为什么还是无法解析指令呢？谢谢

**Comment by hans1980775481** [comment]
我也遇到这个问题  ，请问您解决了吗
![Uploading image.png…]()

**Comment by ewsq** [comment]
> > taos -h 在windows下执行显示：'taos' 不是内部或外部命令，也不是可运行的程序或批处理文件。
> 
> 在你的windows系统C盘下应该有个TDengine文件夹，里面有taos.exe，就是连接到server的client，要在这里执行taos -h。我这边虽然可以连接过去，但依然会出现
> `DB error: Unable to resolve FQDN`
> 请问你通过JDBC接入成功了吗？该如何配置呢？谢谢。

成了呀，注意几点：
1、无论windows还是linux，都需要配置hosts
2、版本注意对应

**Comment by ewsq** [comment]
> 我也遇到这个问题 ，请问您解决了吗

这个问题估计是他们设计就是这样的，在他们解决之前估计只能去改hosts了

**Comment by sangshuduo** [comment]
对，这个是设计。

https://www.taosdata.com/blog/2020/09/11/1824.html

**Comment by flykarry** [comment]
我也遇到了这个问题，总改hosts很麻烦的呀，单机与小型集群，用域名就是画蛇添足

**Comment by hp027** [comment]
TDengine 很好,我是新人, 我用的很难受, 所以我是放弃了, 如果有感受跟我一致的请给我点个❤️

**Comment by proxiti** [comment]
糟糕的设计。
