### ISSUE TITLE
使用源码编译安装，使用taosd启动服务，报错，求助为什么？

### ISSUE THREAD

**Issue by zhangzhongshuai** [taosdata/TDengine#390]
报的错误为：
ERROR MND-SDB failed to open file:/var/lib/taos/mgmt/user.db
ERROR MND failed to init user data
ERROR MND failed to init users
ERROR DND TDengine mgmt initialization failed
HTP http service cleanup
MON dnode:219.216.65.84 is stopped
MON monitor service cleanup
MON dnode:219.216.65.84 is stopped

**Comment by hjxilinx** [comment]
taosd之前有过服务崩溃吗？

**Comment by zhangzhongshuai** [comment]
> taosd之前有过服务崩溃吗？

这是我第一次安装运行，之前用的是安装包安装没遇到问题，这是第一次用源码编译安装发现的

**Comment by plum-lihui** [comment]
两种不同的安装方式同时在一个环境使用的话，会引起冲突。在使用另外一种方式的时候，要先卸载清除掉之前安装包。不知道你是什么环境？之前使用的是什么安装包？最好先完全清除一下。具体方法，请看涛思官网的博客，有一篇介绍各种安装包的安装和卸载的。

**Comment by zhangzhongshuai** [comment]
> 两种不同的安装方式同时在一个环境使用的话，会引起冲突。在使用另外一种方式的时候，要先卸载清除掉之前安装包。不知道你是什么环境？之前使用的是什么安装包？最好先完全清除一下。具体方法，请看涛思官网的博客，有一篇介绍各种安装包的安装和卸载的。

安装包安装和源码编译安装我用的是两台不同电脑，也就是说，源码编码安装之前这台电脑没有安装国TDengine，环境是Ubuntu18.04，另外，源码编译安装重新安装的话也需要完全清除吗？怎么清除？

**Comment by plum-lihui** [comment]
同一种安装方式的话，不需要清除，程序会自动处理的。
你这种错误现象，会不会是权限问题引起的，使用了sudo 吗？
你可以先清除一下： sudo rm -rf   /var/lib/taos
                                 sudo rm -rf   /var/log/taos
