### ISSUE TITLE
TDengine2.0 cluster, the memory is not released.

### ISSUE THREAD

**Issue by only311** [taosdata/TDengine#3901]
目前情况是，两台服务器部署了个集群，有一台的TDengine内存一直占用，不会释放掉。

![微信图片_20201019094619](https://user-images.githubusercontent.com/32408192/96392903-14940400-11f0-11eb-8080-83c0927a9aa9.png)
![微信图片_20201019094612](https://user-images.githubusercontent.com/32408192/96392907-15c53100-11f0-11eb-8107-2196df9ca872.png)

**Comment by sangshuduo** [comment]
为什么要释放掉？

**Comment by only311** [comment]
> 为什么要释放掉？
![微信图片_20201019180433](https://user-images.githubusercontent.com/32408192/96431038-8e021580-1235-11eb-812c-f5c7edc23a63.png)


一直占用大量内存服务器资源不够，上面有张图贴错了，其中一台占用比较高一直下不去

**Comment by sangshuduo** [comment]
有多少张表？多少数据？

**Comment by liangyuanpeng** [comment]
是指有数据过期了还是指两台服务器负载不平衡？

**Comment by sangshuduo** [comment]
TDengine 为了快速写入和查询，会在内存中维护比较多的内存，和表的数量相关。
