### ISSUE TITLE
DND ERROR failed to lock file:/var/lib/taos/dnode/.running ret:-1[Resource temporarily unavailable], database may be running, quit

### ISSUE THREAD

**Issue by ewsq** [taosdata/TDengine#3904]
**Bug Description**
安装并首次启动，然后执行taos正常，也可以正常操作数据库，但执行taosd，出现以下错误：
DND ERROR failed to lock file:/var/lib/taos/dnode/.running ret:-1[Resource temporarily unavailable], database may be running, quit

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [2.5.1]

[root@elastic01 log]# rpm -q centos-release
centos-release-7-8.2003.0.el7.centos.x86_64

**Comment by sangshuduo** [comment]
后台已经有一个 taosd 在运行吧？

**Comment by ewsq** [comment]
> 后台已经有一个 taosd 在运行吧？

噢，taosd是启动程序？我还以为这个是查看日志的呢，启动程序不是使用的“systemctl restart taosd”？直接执行taosd也可以？

**Comment by sangshuduo** [comment]
@ewsq 是的，可以直接执行看到输出，不过最好只在需要调试的时候这么用，正常部署还是应该用 systemctl
