### ISSUE TITLE
select指定字段查询为空

### ISSUE THREAD

**Issue by Kittoa** [taosdata/TDengine#3909]
如图，根据指定字段查询不出来，版本是2.0.3.1
![image](https://user-images.githubusercontent.com/17596488/96399111-2087c200-1200-11eb-86eb-b25aa8d56879.png)

而且查询的数据，新加入的数据排在了前面，之前的数据排在了后面
![image](https://user-images.githubusercontent.com/17596488/96407246-8df11e00-1213-11eb-98e8-5460fbcf9a6c.png)

select * from tableA grouby by columnA  order by timestamp;
查询结果排序是按照columnA的字符串顺序，并没有按照后面的时间顺序

**Comment by sangshuduo** [comment]
sql语句分号前加  \\G 试试是不是显示的不完整

**Comment by Kittoa** [comment]
多谢，确实是不完整，我想让group by的结果按照时间顺序显示，有什么办法吗？
