### ISSUE TITLE
为什么不做成标准的 sql 服务器，而是提供各种语言的 connector 呢？

### ISSUE THREAD

**Issue by qianyiwen2019** [taosdata/TDengine#391]
个人理解，如果在 manager node 和 data node 上面再做一个标准的 sql 服务器，用于解析 sql，生成执行计划，分发请求，merge 结果，返回给用户。类似于一些 mysql 代理这样对外提供服务，就不需要写很多 connector 了。用户用各种语言的自带的连接库即可。
现在这样做成 connector，是出于什么考虑呢？
是为了让计算发生在用户侧，减少 dnode 性能损耗吗？还是为了减少运维压力？
或者说是我没理解对？

**Comment by robotspace** [comment]
你没理解对。首先，没有标准的sql服务器，其次，目前所有的数据库都有各种connector。

**Comment by chenglingsu2019** [comment]
> 你没理解对。首先，没有标准的sql服务器，其次，目前所有的数据库都有各种connector。

谢谢解答。我的意思是TDengine 是否能做成类似兼容 mysql 标准连接的一个服务。类似于阿里公有云上的 DRDS。它自己作为一个服务器存在，用户可以通过各种语言各种库去连接，就像连接mysql 一样。TDengine 并不需要发布 connector，用户使用时也不需要引入 TDengine 的二方包。TDengine 的角色就和 mysql 完全一样。
当然这样做的话，sql解析，分发查询，merge结果就要发生在 TDengine 的服务器上了。我理解：现在的这些过程其实是发生在用户侧的吧。

**Comment by robotspace** [comment]
我的理解，目前taosc这个单元作为客户端代理就充当了你所指的DRDS角色，负责sql 解析和结果集合并。服务端因为采用了集群设计，没有哪个节点适合做sql解析和数据集合并。

**Comment by robotspace** [comment]
降低接入难度肯定是努力的方向，也包括完善接入服务，但是“标准”很难定义，毕竟Oracle和Mysql的语法也不一致。

**Comment by qianyiwen2019** [comment]
> 我的理解，目前taosc这个单元作为客户端代理就充当了你所指的DRDS角色，负责sql 解析和结果集合并。服务端因为采用了集群设计，没有哪个节点适合做sql解析和数据集合并。
谢谢解答。
taosc确实是行使了DRDS的功能，但它本身更像是依附于客户APP的一个中间件。据我所知，阿里的DRDS最开始也是以中间件的形式发布jar包给用户的，但进入阿里公有云之后，为了贴合用户习惯，减少用户依赖，将它变成了服务器模式，用户关心的东西更少，客户侧的运维和机器成本也更低（比如大量数据merge这种操作，发生在客户侧是很吃内存的）。
至于说“服务端因为采用了集群设计，没有哪个节点适合做sql解析和数据集合并。”我想这个应该不成问题，如果真做成服务器，那肯定是单独的资源单独的节点。
当然，以上都是我在试用时的一些想法。。。并非质疑你们的模式。

**Comment by robotspace** [comment]
建议你看一下官网上的集群设计方案，但是目前社区版并未实现，我倒是很想实现这个集群方案:) 欢迎你测试我提供的tests/examples/lua connector，用户侧的负载并不大。将来如果你布署这个服务器的话，应该也是server+client模式，阿里云上那个是SaaS模式。另外，我也是个吃瓜群众，观点不代表官方。

**Comment by wanghaisheng** [comment]
@robotspace  lua 代码没有更新吗 只有query吗

**Comment by robotspace** [comment]
> @robotspace lua 代码没有更新吗 只有query吗

有的，我这两天就整理一下，提个PR。
