### ISSUE TITLE
[taosd-v2.0.5.1] Http restful API query result issue: data size and rows in result not match

### ISSUE THREAD

**Issue by sudo168** [taosdata/TDengine#3910]
**Bug Description**
case 1: 结果集有5条数据返回，但是rows为12 （这个是describe查询结果）: 
{"status":"succ","head":["Field","Type","Length","Note"],"data":[["ts","TIMESTAMP",8,""],["table_name","BINARY",128,""],["symbol","BINARY",64,""],["partition_tag","INT",4,""],["user_id","BIGINT",8,""]],"rows":12}

case 2: 查询语句本身没有查到数据，但是row居然为5， 结果返回如下（这个是select查询结果）：
{"status":"succ","head":["ts","table_name","symbol","partition_tag","user_id"],"data":[],"rows":5}

这两个case查询是有关联的：
首先，select * from table limit 0,10; //这个查询有7条数据返回，data size跟rows都是7
接着执行describe table; 返回的结果集就是上面的case 1
再接着执行select * from table limit 10,10; 返回的结果集就是上面的case 2

bug已经很明显了。

**Environment:**
 - OS: Ubuntu 18.04.1 LTS
 - TDengine Version 2.0.5.1

**Comment by sangshuduo** [comment]
可以写一下完整的 SQL 语句吗？

**Comment by sangshuduo** [comment]
No new information. Close it.
