### ISSUE TITLE
How can I change default 6041 port to others under the taos cluster? 

### ISSUE THREAD

**Issue by cleverpig** [taosdata/TDengine#3911]
**General Questions**
How can I change default 6041 port to others under the taos cluster? 
Because this port is confilct with another server port on the node host.
BTW, we can use different restapi port in every node? just like kafka cluster.

---- This is the log output ----
10/19 11:17:40.189948 0x7faaf6149740 DND storage directory is initialized
10/19 11:17:40.190073 0x7faaf6149740 DND dnode read is opened, min worker:48 max worker:96
10/19 11:17:40.190096 0x7faaf6149740 DND dnode write is opened, max worker 48
10/19 11:17:40.190108 0x7faaf6149740 DND dnode mread is opened
10/19 11:17:40.190117 0x7faaf6149740 DND dnode mwrite is opened
10/19 11:17:40.190125 0x7faaf6149740 DND dnode mpeer is opened
10/19 11:17:40.191037 0x7faaf6149740 DND inter-dnodes rpc client is opened
10/19 11:17:40.192201 0x7faaf6149740 DND inter-dnodes RPC server is opened
10/19 11:17:40.192319 0x7faaf6149740 UTL ERROR bind tcp server socket failed, 0x0:6041(Address already in use)
10/19 11:17:40.192351 0x7faaf6149740 UTL ERROR failed to create TCP server socket, port:6041 (Address already in use)

**Comment by sangshuduo** [comment]
The TDengine use a series of continuous ports. The default setting is from 6030 to 6042. You can change the default start port to another number. Then other ports will use the following ports.

**Comment by cleverpig** [comment]
> The TDengine use a series of continuous ports. The default setting is from 6030 to 6042. You can change the default start port to another number. Then other ports will use the following ports.

So I can make these change?

- change the port from 16030 to 16042 on node1
- change the port from 26030 to 26042 on node2
- change the port from 26030 to 26042 on node3

and make them work together as "One Taos Cluster"?

**Comment by cleverpig** [comment]
I got this exception when I ran the 2 nodes with different port 16030 and 26030, seem like cluster will use the 6030 as default:

![image](https://user-images.githubusercontent.com/580435/96419674-0ad9c300-1227-11eb-9ac4-757dfef64c7c.png)

**Comment by cleverpig** [comment]
Mark and waiting for response... @guanshengliang

**Comment by guanshengliang** [comment]
The port of TDengine can only be configured through ServerPort.
The ports of all modules are generated by calculation, among them, httpPort is calculated by ServerPort+11.

However, once fqdn and serverPort are configured, they cannot be modified, otherwise TDengine cannot be started again.
We expect that within 3 weeks, the issue of fqdn and serverPort modification will be resolved

**Comment by cleverpig** [comment]
> The port of TDengine can only be configured through ServerPort.
> The ports of all modules are generated by calculation, among them, httpPort is calculated by ServerPort+11.
> 
> However, once fqdn and serverPort are configured, they cannot be modified, otherwise TDengine cannot be started again.
> We expect that within 3 weeks, the issue of fqdn and serverPort modification will be resolved

Cool!  👍  :=)

**Comment by cleverpig** [comment]
> The port of TDengine can only be configured through ServerPort.
> The ports of all modules are generated by calculation, among them, httpPort is calculated by ServerPort+11.
> 
> However, once fqdn and serverPort are configured, they cannot be modified, otherwise TDengine cannot be started again.
> We expect that within 3 weeks, the issue of fqdn and serverPort modification will be resolved

Does 2.0.6 version work for this?

**Comment by guanshengliang** [comment]
After version 2.0.7, find /var/ lib/taos/dnode/dnodeEps.json, modify the FQDN and port corresponding to dnodeI
d, and restart the service.

Make sure that this file is the same for all machines in the cluster

**Comment by cleverpig** [comment]
> After version 2.0.7, find /var/ lib/taos/dnode/dnodeEps.json, modify the FQDN and port corresponding to dnodeI
> d, and restart the service.
> 
> Make sure that this file is the same for all machines in the cluster

great job! I will check! :+1:

**Comment by guanshengliang** [comment]
There is no reply for a long time, and this problem has been located and solved in 2.0.9.0
