### ISSUE TITLE
2.0.4版本缺少taosdump工具，如何导出整个数据库？

### ISSUE THREAD

**Issue by yebel1120** [taosdata/TDengine#3912]
如题，taosdump是否有其他下载途径能单独安装？
还是新版本只能用csv的方式导出数据库？
请指教，谢谢

**Comment by Aries-Lee1991** [comment]
> 如题，taosdump是否有其他下载途径能单独安装？
> 还是新版本只能用csv的方式导出数据库？
> 请指教，谢谢

开源版本目前不再提供taosdump了，出了可以按照csv方式导出外，你也可以自己写一个脚本来导出，不会很复杂。
