### ISSUE TITLE
how spark get super table's tbname?

### ISSUE THREAD

**Issue by perayb** [taosdata/TDengine#3913]
参考官方BLOG的[spark示例](https://www.taosdata.com/blog/2020/06/18/1614.html)加载超级表到dataframe之后，执行`select("tbname")`报错：
```
org.apache.spark.sql.AnalysisException: cannot resolve '`tbname`' given input columns: [... ...];;
'Project ['tbname]
```
**问题描述**：使用spark读取超级表时，如何能够获取到数据对应的子表名称呢？

**Comment by sangshuduo** [comment]
select tbname from \<super table name>

**Comment by aybthebest** [comment]
spark中使用如下方式加载超级表之后，执行`.select`提示无法解析`tbname`
``` scala
    val tableDf = sparkSession.read
      .format("jdbc")
      .option("url", s"jdbc:TAOS://$tdJdbc/$tdDb?charset=UTF-8&locale=en_US.UTF-8")
      .option("driver", "com.taosdata.jdbc.TSDBDriver")
      .option("dbtable", stable)
      .option("user", tdUserName)
      .option("password", tdPasswd)
      .option("fetchsize", "1000")
      .load()
      // 这里无法获取到子表名，提示错误
      .select("tbname")
```

spark中有办法执行`select tbname from <super table name>`这个语句吗？

**Comment by sangshuduo** [comment]
jdbc 都应该可以啊

**Comment by aybthebest** [comment]
Spark Jdbc的`dbtable`字段是支持`subquery`功能的，使得Spark可以load查询语句作为一张表，参考
>[Spark jdbc在mysql的连接示例](https://stackoverflow.com/questions/43174838/how-to-use-a-subquery-for-dbtable-option-in-jdbc-data-source)。
以mysql下的查询语句为例：
``` sql
(select * from table1) as table1
```
该功能会将SQL转化为：
``` sql
SELECT * FROM (select * from table1) as table1 WHERE 1=0
```
而TDengine暂时不支持上述查询语句，因此无法使用Spark的`subquery` load表的功能。
我们暂时是在超级表中新增`子表名标签`作为替代方案。

**Comment by sangshuduo** [comment]
close as issue resolved.
