### ISSUE TITLE
create cluster but a node is offline

### ISSUE THREAD

**Issue by zxd-wyy** [taosdata/TDengine#3915]
taos Version:2.0.5.1。
![image](https://user-images.githubusercontent.com/71641198/96419991-7d4aa300-1227-11eb-81ce-be577a06abbf.png)
报错信息。
hosts 主节点配置：
![image](https://user-images.githubusercontent.com/71641198/96420154-b256f580-1227-11eb-9ac8-3644139bb847.png)
子节点hosts配置：
![image](https://user-images.githubusercontent.com/71641198/96420268-dfa3a380-1227-11eb-90b9-ae3131b22b34.png)
hosts 主节点taos.cfg配置：
![image](https://user-images.githubusercontent.com/71641198/96420350-fc3fdb80-1227-11eb-86df-a68c2968e8f4.png)
子节点taos.cfg配置：
![image](https://user-images.githubusercontent.com/71641198/96420409-1083d880-1228-11eb-837a-03e9e1067ba9.png)
ping hzyf002 ，pingyzyf003，两台服务器互ping都是通的。
telnet 192.168.2.40 6030 ,telnet 192.168.2.41 6030，两台服务器互相telnet也是通的。但是显示子节点离线

**Comment by sangshuduo** [comment]
UDP 也通吗？有开防火墙吗？ firewall-cmd --list-port 输出什么？

**Comment by ewsq** [comment]
前天刚遇到，我是在first节点添加的有测试数据，然后直接添加其它节点，执行完添加执行就死翘翘了，看日志有报错，就是连接不到，查看taosd的状态又是正常的，各机用ping也是可以正常ping通的，就是无法连接了。

最后的处理办法是重装接所有节点，保持所有节点都没有数据，然后再一个节点一个节点添加就正常了。

卸载：
[root@cluster01 ~]# 
systemctl stop taosd
rpm -e TDengine
rm -fr /etc/taos/taos.cfg
rm -fr /etc/taos
rm -fr /var/lib/taos
rm -fr /var/log/taos
rm -fr /usr/bin/taos
rm -fr /usr/bin/taosdemo
rm -fr /usr/bin/taosd
rm -fr /usr/local/taos
rm -fr /usr/include/taos.h
rm -fr /usr/include/taoserror.h
rm -fr /etc/systemd/system/multi-user.target.wants/taosd.service
rm -fr /etc/systemd/system/taosd.service
find / -name taos*

**Comment by zxd-wyy** [comment]
我先试试看，
![image](https://user-images.githubusercontent.com/71641198/96526764-1a9de980-12b1-11eb-89f5-9d20cd868cff.png)
防火墙都关闭了的

**Comment by sangshuduo** [comment]
@zxd-wyy 试试上面朋友的方法： 最后的处理办法是重装接所有节点，保持所有节点都没有数据，然后再一个节点一个节点添加就正常了。

**Comment by jtao1735** [comment]
很简单的错误，怎么taos.cfg里的FQDN配置为hostname? 这需要配置为本机的FQDN，比如hzyf01, hzyf002

**Comment by zxd-wyy** [comment]
按照上面的朋友操作了，可以了 谢谢
