### ISSUE TITLE
Windos client command line specify config file led taos exit

### ISSUE THREAD

**Issue by cddonald** [taosdata/TDengine#3917]
2.0.5版本，windos客户端版本2.0.5.1，在windos上用python插入中文，在Python里读取，或者是Linux 数据库本地读取，都是正常的，但是Windos命令行中查询出来是乱码，所以我想指定配置文件，但是在windos 命令行指定配置文件，直接就显示 taos 停止运行。  具体命令行语句如下：taos -h 10.11.0.1 -c  C:\TDengine\cfg

**Comment by sangshuduo** [comment]
确实是有问题，我们尽快解决一下

**Comment by sangshuduo** [comment]
@cddonald  新版本（2.0.6.0）已经解决了这个问题
