### ISSUE TITLE
sql parse exception

### ISSUE THREAD

**Issue by xujiesh0510** [taosdata/TDengine#3918]
version 2.0.4

   'is null'  和 'is not null‘   查询结果有bug。
svariables   是超级表，VariableName ，tenantId  都是tag
 

taos> select  Count(*) as Val,'-' as dimension,'-' as metric   from  svariables   where VariableName is not  null and  tenantId =1   AND Ts >= '2020-04-19 16:59:30' ;

DB error: Unable to establish connection
taos> select  Count(*) as Val,'-' as dimension,'-' as metric   from  svariables   where VariableName is   null and  tenantId =1   AND Ts >= '2020-04-19 16:59:30' ;

DB error: Unable to establish connection
taos> select  Count(*) as Val,'-' as dimension,'-' as metric   from  svariables   where VariableName is null   AND Ts >= '2020-04-19 16:59:30' ;
Query OK, 0 row(s) in set (0.002806s)

select  Count(*) as Val,'-' as dimension,'-' as metric   from  svariables   where VariableName is not  null   AND Ts >= '2020-04-19 16:59:30' ;
Query OK, 1 row(s) in set (0.132861s)

**Comment by sangshuduo** [comment]
我们会尽快解决这个问题

**Comment by sangshuduo** [comment]
新版本已解决。
