### ISSUE TITLE
when drop table a: show tables related to metric exist 

### ISSUE THREAD

**Issue by yfgcq** [taosdata/TDengine#392]
when drop table userpassrecord
userpassrecord is a stable and have child table
show: tables related to metric exist

**Comment by guanshengliang** [comment]
Cascade deletion is not supported yet.
We will develop this feature later.

**Comment by yfgcq** [comment]
first drop table and drop stable

**Comment by guanshengliang** [comment]
similar to #354, we will arrange it to development task
