### ISSUE TITLE
src/sync/CMakeLists.txt doesn't remove tarbitrator.c from SRC

### ISSUE THREAD

**Issue by jieatcoderrect** [taosdata/TDengine#3922]
**Bug Description**
CMakeLists.txt under src/sync tries to remove src/tarbitrator.c from SRC when building libsync.a because src/tarbitrator.c includes a main() function which pollutes the library.

`  LIST(REMOVE_ITEM SRC ./src/tarbitrator.c)
`

Unfortunately, the path "./src/tarbitrator.c" doesn't work. It should be "src/tarbitrator.c" （without "./").

**To Reproduce**
1. mkdir build
2. cd build
3. cmake ..
4. make taosd
5. nm build/lib/libsync.a | grep main

You can find main() function from tarbitrator.c is included into the library.

**Expected Behavior**
N/A

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Any
 - Memory, CPU, current Disk Space
 - TDengine Version commit 95aa2442e

**Additional Context**

**Comment by guanshengliang** [comment]
Thank you very much, it is indeed a problem, I will deal with it immediately

**Comment by guanshengliang** [comment]
done
