### ISSUE TITLE
How to count population effectively

### ISSUE THREAD

**Issue by yfgcq** [taosdata/TDengine#393]
1、按照设备分表，tags就是设备的属性
2、怎么高效查询统计通行的人的属性，比如人次（独立通行人数）？
   WHERE <tag_name>
   GROUP BY <tag_name>
3、或者怎么设计这种stable table tags,不按照设备分表，按照通行的人（一人一表）这样tags就有userid了？？？

**Comment by liutao77** [comment]
是不是要统计独立的人的出现次数？
个人理解，数据是否按每个人产生？每个人是否有提前能够确定的且不变的ID，如果有，感觉可以用人的ID作为表ID或者tag值来存储？

**Comment by johnnyhou327** [comment]
@yfgcq 这个场景如果查询上是想追踪个人轨迹，并且人数不多比如500万以内，那么每人一表是可以的，userid作为标签打在每个人的表上。这样查询独立人次就是统计子表的数目。
还有一种思路是按照卡口建表，这个要求同一时刻通过该卡口的人只有一个，这样可以每个卡口一张表来存数据，每条记录就是当前时刻通过该卡口的人的信息，包括userid等。查询人次，后面会提供一个类似distinct的函数，目前考虑用hyperloglog做模糊查询，不然服务端压力会很大。

**Comment by yfgcq** [comment]
@johnnyhou327 卡扣就是通行设备吧？
现在统计查询纬度比较多，有访客、受访人、受访人部门、通行方式、通行区域等

**Comment by guanshengliang** [comment]
这种情况，并不是TDengine假设的典型物联网场景，很难达到非常快的查询速度。
1.如果按人建表，人非常多，而每个人的数据记录数又非常少；
2.按照通行设备建表则是常见的方式，可以缩小表的数目；查询上只能采用值过滤语句，通过时间和通信设备的筛选条件，将查询的数据集限定在100万条记录以内，仍然能够达到秒级的查询速度。
