### ISSUE TITLE
TDengine Does not support select * from table where 1=1/2

### ISSUE THREAD

**Issue by chengduhaha** [taosdata/TDengine#3934]
taos> select * from data_after_clean_wyx where 1=2;

DB error: Invalid SQL statement
taos> select * from data_after_clean_wyx where 1=1;

DB error: Invalid SQL statement

**Comment by Shawshank-Smile** [comment]
"where  1=1 " haven't supported
![image](https://user-images.githubusercontent.com/46439638/96677726-c4a96e80-13a2-11eb-8a4f-88b44cb3b150.png)
 yet.
Try this:
