### ISSUE TITLE
"no taos in java.library.path" when running JDBCdemo 

### ISSUE THREAD

**Issue by willemmiao** [taosdata/TDengine#394]
Linux服务器上源码部署成功了。
在本地使用JDBCDEMO运行报错：
`/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin/java -Djava.library.path=/Users/willem/.m2/repository/taos/taos/v1 -Djava.library.path=/Users/willem/Downloads/JDBC/lib -Dfile.encoding=UTF-8 -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/lib/tools.jar:/Users/willem/Downloads/JDBC/JDBCDemo/target/classes:/Users/willem/.m2/repository/com/taosdata/jdbc/taos-jdbcdriver/1.0.1/taos-jdbcdriver-1.0.1.jar TSDBSyncSample
Arguments format: host tables loop batchs
---------------------------------------------------------------
Start testing...
---------------------------------------------------------------

JDBC URL to use:
jdbc:TAOS://172.22.31.200:0/?user=root&password=taosdata

---------------------------------------------------------------
Start creating databases and tables...
Exception in thread "main" java.lang.UnsatisfiedLinkError: no taos in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.taosdata.jdbc.TSDBJNIConnector.<clinit>(TSDBJNIConnector.java:25)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:133)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at TSDBSyncSample.doCreateDbAndTable(TSDBSyncSample.java:84)
	at TSDBSyncSample.main(TSDBSyncSample.java:44)

Process finished with exit code 1
`

在项目里面已经手动添加了jar文件。
也添加了libtaos.so.1.6.1.5
不知道什么原因了，
改怎么操作呢
谢谢

**Comment by guanshengliang** [comment]
报错信息很明确
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no taos in java.library.path
```
所以，将libtaos.so设置到java.library.path指向的路径中

**Comment by willemmiao** [comment]
> 报错信息很明确
> 
> ```
> Exception in thread "main" java.lang.UnsatisfiedLinkError: no taos in java.library.path
> ```
> 
> 所以，将libtaos.so设置到java.library.path指向的路径中

我已经设置了的。

`willemdeMacBook-Pro:lib willem$ pwd
/Users/willem/Downloads/JDBC/lib
willemdeMacBook-Pro:lib willem$ ls
libtaos.so
willemdeMacBook-Pro:lib willem$ `

`-Djava.library.path=/Users/willem/Downloads/JDBC/lib`

![image](https://user-images.githubusercontent.com/10069378/63498710-06b5f680-c4f9-11e9-80e3-0c78431b17f8.png)

![image](https://user-images.githubusercontent.com/10069378/63498741-19303000-c4f9-11e9-9668-9bee7178e32f.png)

请问是哪里出的问题呢

**Comment by johnnyhou327** [comment]
@willemmiao 现在TDengine还没有Mac os的客户端

**Comment by willemmiao** [comment]
> @willemmiao 现在TDengine还没有Mac os的客户端

噢。。谢谢。
所以只能使用window或者Linux电脑来做开发吗？
有计划出mac os客户端吗？

**Comment by johnnyhou327** [comment]
@willemmiao 目前官方给出的客户端驱动只有windows和linux的，macos后面应该会开发，但目前还没详细时间。建议看看社区有没有其他开发者做mac客户端吧。

**Comment by derchLee** [comment]
> @willemmiao 现在TDengine还没有Mac os的客户端

你好，我在Windows上用java程序按照JDBCDemo中的方法连接在linux上安装的taos的时候也是提示：Exception in thread "main" java.lang.UnsatisfiedLinkError: no taos in java.library.path。

**Comment by always-james** [comment]
您好，在使用taos时遇到如下问题：
创建数据库连接不成功，提示如下错误：
09/08 17:13:56.050000 0x3857472 TSC failed to set locale:en_US.UTF-8, restore locale:
09/08 17:13:56.050000 0x3857472 TSC charset:936 is not valid in locale, charset remains:

代码中配置如下：
       connProps.setProperty(TSDBDriver.PROPERTY_KEY_USER, "root");
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_PASSWORD, "taosdata");
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_CONFIG_DIR, "/etc/taos");
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_CHARSET, "UTF-8");
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_LOCALE, "en_US.UTF-8");
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_TIME_ZONE, "UTC+8");
不知道"locale"、"charset"和“timezone"该如何设置值，通过跟踪代码发现，如果不设置，就取系统默认的Charset、Locale、TimeZone，但不设置值也会报错。
通过调用Java API：Charset、Locale、TimeZone得到具体的名称设置在代码中，依然会报设置的值不正确。
那么这三个设置项的值该如何参考呢？
谢谢。

**Comment by sangshuduo** [comment]
还有这个问题吗？我们新发布了 2.0，请试用一下新版本

**Comment by cbschina** [comment]
> 还有这个问题吗？我们新发布了 2.0，请试用一下新版本

mac os 的客户端什么时候 发布呢？mac 开发还是报错

**Comment by hans1980775481** [comment]
這個問題是怎麽解決的呢

**Comment by mushanzi1216** [comment]
同问 mac端开发会一直报这个错误嘛？
no taos in java.library.path: [/Users/guodong/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .].

**Comment by sangshuduo** [comment]
暂时不支持 Mac 系统

**Comment by MelodyI** [comment]
[参考](https://www.cnblogs.com/EasonJim/p/9445282.html)
操作系统：OSX
JDK: 1.8
```
export JAVA_LIBRARY_PATH=/usr/local/lib
```
配置好以后可以正常运行

**Comment by blackmaxer** [comment]
Connection conn = DriverManager.getConnection(jdbcUrl, connProps);
为啥我用官网的demo，一直卡在这一步，执行不下去，也没个超时时间。。。

**Comment by holypost** [comment]
> [参考](https://www.cnblogs.com/EasonJim/p/9445282.html)，操作系统：OSX，JDK: 1.8`export JAVA_LIBRARY_PATH=/usr/local/lib`，配置好以后可以正常运行。

/usr/lib
/usr/lib64
/usr/local/lib
..
都加了也还是报这个错误
