### ISSUE TITLE
WHERE中使用OR关键字时执行结果错误

### ISSUE THREAD

**Issue by zhengbaomin** [taosdata/TDengine#3943]
**Bug Description**
查询条件中使用OR关键字时得到的结果不正确

**Expected Behavior**
能够正确查询出结果

**Screenshots**
![图片](https://user-images.githubusercontent.com/45037393/96664033-82713480-1384-11eb-8b42-f8efbda81256.png)

**Comment by hjxilinx** [comment]
TDengine 暂不支持跨列的 or 多条件连接查询。
参见：https://www.taosdata.com/cn/documentation/taos-sql/#%E6%95%B0%E6%8D%AE%E6%9F%A5%E8%AF%A2
![Snip20201021_6](https://user-images.githubusercontent.com/8252296/96694536-2b3a8680-13bb-11eb-8626-64d9453ad9b4.png)
