### ISSUE TITLE
jdbc 测试案例不能通过

### ISSUE THREAD

**Issue by super-sponge** [taosdata/TDengine#3944]
最近在做presto适配tdengine这块工作， 发现develop分支下面的jdbc 驱动模块，测试案例不能通过。请规范下。具体如下
1. casees 下面的测试应该是连接本地taos的。在执行mvn test 之前还得启动taos才行
2. TSDBDriverTest 类下面的测试案例明显存在问题。 

建议是否可以采用testcontainer使用容器技术重新构建jdbc这块的驱动。

**Comment by zilunmiyan** [comment]
> 最近在做presto适配tdengine这块工作， 发现develop分支下面的jdbc 驱动模块，测试案例不能通过。请规范下。具体如下
请教下一下，fpresto没有提供官方的对TDengine的connector，自己适配难度会很大吗？

**Comment by zilunmiyan** [comment]
请教下一下，presto没有提供官方的对TDengine的connector，自己适配难度会很大吗？ @super-sponge

**Comment by super-sponge** [comment]
读取的我们做过，难度不大



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月06日 16:32 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [taosdata/TDengine] jdbc 测试案例不能通过 (#3944) |

请教下一下，presto没有提供官方的对TDengine的connector，自己适配难度会很大吗？ @super-sponge
