### ISSUE TITLE
集群status not received 日志

### ISSUE THREAD

**Issue by zhangyang1995** [taosdata/TDengine#3946]
10/21 13:11:06.140570 0x7f16bdffb700 DND msg:status will be processed in mpeer queue
10/21 13:11:06.140627 0x7f16bdffb700 MND vgId:2, not exist in dnode:1 and status is ready, send create msg
10/21 13:11:06.140635 0x7f16bdffb700 MND vgId:2, send create all vnodes msg, numOfVnodes:1 db:0.log
10/21 13:11:06.140640 0x7f16bdffb700 MND vgId:2, index:0, send create vnode msg to dnode node1:6030, ahandle:(nil)
10/21 13:11:06.140772 0x7f16c6ffd700 DND (nil), msg:create-vnode will be processed
10/21 13:11:06.140813 0x7f16c6ffd700 VND vgId:2, not exist
10/21 13:11:06.140828 0x7f16c6ffd700 DND vgId:2, create vnode msg is received
10/21 13:11:06.140949 0x7f16c6ffd700 VND vgId:2, save vnode cfg, replica:1
10/21 13:11:06.140990 0x7f16c6ffd700 VND vgId:2, save vnode cfg, nodeId:1 nodeEp:node1:6030
10/21 13:11:06.141405 0x7f16c6ffd700 VND vgId:2, save vnode cfg successed
10/21 13:11:06.141482 0x7f16c6ffd700 VND vgId:2, vnode is created, walLevel:1 fsyncPeriod:3000
10/21 13:11:06.141624 0x7f16c6ffd700 VND vgId:2, read vnode cfg successfully, replcia:1
10/21 13:11:06.141638 0x7f16c6ffd700 VND vgId:2, dnode:1, node1:6040
10/21 13:11:06.141783 0x7f16c6ffd700 VND vgId:2, read vnode version successfully, version:16
10/21 13:11:06.141942 0x7f16c6ffd700 DND pVnode:0x7f169c001710, write queue:0x7f169c000b80 is allocated
10/21 13:11:06.141952 0x7f16c6ffd700 DND pVnode:0x7f169c001710, read queue:0x7f169c000c00 is allocated
10/21 13:11:06.141960 0x7f16c6ffd700 CQ  vgId:2, CQ is opened
10/21 13:11:06.142695 0x7f16c6ffd700 WAL wal:/var/lib/taos/vnode/vnode2/wal, 0 files are moved for restoration
10/21 13:11:06.142871 0x7f16c6ffd700 WAL wal:/var/lib/taos/vnode/vnode2/wal/wal0, it is created
10/21 13:11:06.142961 0x7f16c6ffd700 WAL wal:/var/lib/taos/vnode/vnode2/wal, it is open, level:1 fsyncPeriod:3000
10/21 13:11:06.143200 0x7f16c6ffd700 SYN vgId:2 peer:node1:6040, it is configured
10/21 13:11:06.143245 0x7f16c6ffd700 SYN vgId:2 peer:node1:6040, start to check peer connection after 2120 ms
10/21 13:11:06.143258 0x7f16c6ffd700 SYN vgId:2, this node is not configured
10/21 13:11:06.143264 0x7f16c6ffd700 SYN vgId:2, cleanup sync
10/21 13:11:06.143269 0x7f16c6ffd700 SYN vgId:2 peer:node1:6040, it is removed
10/21 13:11:06.143273 0x7f16c6ffd700 SYN vgId:2 peer:node1:6040, resource is freed
10/21 13:11:06.143279 0x7f16c6ffd700 VND ERROR vgId:2, failed to open sync module, replica:1 reason:Invalid Sync Configuration
10/21 13:11:06.143364 0x7f16c6ffd700 CQ  vgId:2, stop all CQs
10/21 13:11:06.143371 0x7f16c6ffd700 CQ  vgId:2, CQ is closed
10/21 13:11:06.143436 0x7f16c6ffd700 WAL wal:/var/lib/taos/vnode/vnode2/wal/wal0, it is removed
10/21 13:11:07.145899 0x7f16bdffb700 DND msg:status will be processed in mpeer queue
10/21 13:11:07.145955 0x7f16bdffb700 MND vgId:2, not exist in dnode:1 and status is ready, send create msg
10/21 13:11:07.145962 0x7f16bdffb700 MND vgId:2, send create all vnodes msg, numOfVnodes:1 db:0.log
10/21 13:11:07.145968 0x7f16bdffb700 MND vgId:2, index:0, send create vnode msg to dnode node1:6030, ahandle:(nil)
10/21 13:11:07.146119 0x7f16c6ffd700 DND (nil), msg:create-vnode will be processed
10/21 13:11:07.146138 0x7f16c6ffd700 VND vgId:2, not exist
10/21 13:11:07.146149 0x7f16c6ffd700 DND vgId:2, create vnode msg is received
10/21 13:11:07.146270 0x7f16c6ffd700 VND vgId:2, save vnode cfg, replica:1
10/21 13:11:07.146309 0x7f16c6ffd700 VND vgId:2, save vnode cfg, nodeId:1 nodeEp:node1:6030
10/21 13:11:07.146715 0x7f16c6ffd700 VND vgId:2, save vnode cfg successed
10/21 13:11:07.146761 0x7f16c6ffd700 VND vgId:2, vnode is created, walLevel:1 fsyncPeriod:3000
10/21 13:11:07.146860 0x7f16c6ffd700 VND vgId:2, read vnode cfg successfully, replcia:1
10/21 13:11:07.146954 0x7f16c6ffd700 VND vgId:2, dnode:1, node1:6040
10/21 13:11:07.147057 0x7f16c6ffd700 VND vgId:2, read vnode version successfully, version:16
10/21 13:11:07.147147 0x7f16c6ffd700 DND pVnode:0x7f169c001710, write queue:0x7f169c000b80 is allocated
10/21 13:11:07.147156 0x7f16c6ffd700 DND pVnode:0x7f169c001710, read queue:0x7f169c000c00 is allocated
10/21 13:11:07.147163 0x7f16c6ffd700 CQ  vgId:2, CQ is opened
10/21 13:11:07.148192 0x7f16c6ffd700 WAL wal:/var/lib/taos/vnode/vnode2/wal, 0 files are moved for restoration
10/21 13:11:07.148348 0x7f16c6ffd700 WAL wal:/var/lib/taos/vnode/vnode2/wal/wal0, it is created
10/21 13:11:07.148358 0x7f16c6ffd700 WAL wal:/var/lib/taos/vnode/vnode2/wal, it is open, level:1 fsyncPeriod:3000
10/21 13:11:07.148880 0x7f16c6ffd700 SYN vgId:2 peer:node1:6040, it is configured
10/21 13:11:07.148897 0x7f16c6ffd700 SYN vgId:2 peer:node1:6040, start to check peer connection after 2120 ms
10/21 13:11:07.148911 0x7f16c6ffd700 SYN vgId:2, this node is not configured
10/21 13:11:07.148917 0x7f16c6ffd700 SYN vgId:2, cleanup sync
10/21 13:11:07.148921 0x7f16c6ffd700 SYN vgId:2 peer:node1:6040, it is removed
10/21 13:11:07.148927 0x7f16c6ffd700 SYN vgId:2 peer:node1:6040, resource is freed
10/21 13:11:07.148934 0x7f16c6ffd700 VND ERROR vgId:2, failed to open sync module, replica:1 reason:Invalid Sync Configuration
10/21 13:11:07.149044 0x7f16c6ffd700 CQ  vgId:2, stop all CQs
10/21 13:11:07.149059 0x7f16c6ffd700 CQ  vgId:2, CQ is closed
10/21 13:11:07.149137 0x7f16c6ffd700 WAL wal:/var/lib/taos/vnode/vnode2/wal/wal0, it is removed
10/21 13:11:08.151298 0x7f16bdffb700 DND msg:status will be processed in mpeer queue
10/21 13:11:08.151367 0x7f16bdffb700 MND vgId:2, not exist in dnode:1 and status is ready, send create msg
10/21 13:11:08.151380 0x7f16bdffb700 MND vgId:2, send create all vnodes msg, numOfVnodes:1 db:0.log
10/21 13:11:08.151389 0x7f16bdffb700 MND vgId:2, index:0, send create vnode msg to dnode node1:6030, ahandle:(nil)
10/21 13:11:08.151547 0x7f16c6ffd700 DND (nil), msg:create-vnode will be processed
10/21 13:11:08.151567 0x7f16c6ffd700 VND vgId:2, not exist
10/21 13:11:08.151581 0x7f16c6ffd700 DND vgId:2, create vnode msg is received
10/21 13:11:08.151753 0x7f16c6ffd700 VND vgId:2, save vnode cfg, replica:1
10/21 13:11:08.151843 0x7f16c6ffd700 VND vgId:2, save vnode cfg, nodeId:1 nodeEp:node1:6030
10/21 13:11:08.152297 0x7f16c6ffd700 VND vgId:2, save vnode cfg successed
10/21 13:11:08.152378 0x7f16c6ffd700 VND vgId:2, vnode is created, walLevel:1 fsyncPeriod:3000
10/21 13:11:08.152525 0x7f16c6ffd700 VND vgId:2, read vnode cfg successfully, replcia:1
10/21 13:11:08.152569 0x7f16c6ffd700 VND vgId:2, dnode:1, node1:6040
10/21 13:11:08.152756 0x7f16c6ffd700 VND vgId:2, read vnode version successfully, version:16
10/21 13:11:08.152936 0x7f16c6ffd700 DND pVnode:0x7f169c001710, write queue:0x7f169c000b80 is allocated
10/21 13:11:08.152949 0x7f16c6ffd700 DND pVnode:0x7f169c001710, read queue:0x7f169c000c00 is allocated
10/21 13:11:08.152958 0x7f16c6ffd700 CQ  vgId:2, CQ is opened
10/21 13:11:08.153799 0x7f16c6ffd700 WAL wal:/var/lib/taos/vnode/vnode2/wal, 0 files are moved for restoration
10/21 13:11:08.153980 0x7f16c6ffd700 WAL wal:/var/lib/taos/vnode/vnode2/wal/wal0, it is created
10/21 13:11:08.154015 0x7f16c6ffd700 WAL wal:/var/lib/taos/vnode/vnode2/wal, it is open, level:1 fsyncPeriod:3000
10/21 13:11:08.154156 0x7f16c6ffd700 SYN vgId:2 peer:node1:6040, it is configured
10/21 13:11:08.154163 0x7f16c6ffd700 SYN vgId:2 peer:node1:6040, start to check peer connection after 2120 ms
10/21 13:11:08.154168 0x7f16c6ffd700 SYN vgId:2, this node is not configured
10/21 13:11:08.154172 0x7f16c6ffd700 SYN vgId:2, cleanup sync
10/21 13:11:08.154174 0x7f16c6ffd700 SYN vgId:2 peer:node1:6040, it is removed
10/21 13:11:08.154179 0x7f16c6ffd700 SYN vgId:2 peer:node1:6040, resource is freed
10/21 13:11:08.154186 0x7f16c6ffd700 VND ERROR vgId:2, failed to open sync module, replica:1 reason:Invalid Sync Configuration
10/21 13:11:08.154286 0x7f16c6ffd700 CQ  vgId:2, stop all CQs
10/21 13:11:08.154329 0x7f16c6ffd700 CQ  vgId:2, CQ is closed
10/21 13:11:08.154394 0x7f16c6ffd700 WAL wal:/var/lib/taos/vnode/vnode2/wal/wal0, it is removed

**Comment by zhangyang1995** [comment]
@sangshuduo

**Comment by guanshengliang** [comment]
在第一次启动之后，你又修改了FQDN导致的问题，现在版本一旦fqdn配置之后，不能再修改。
后续版本我们会解决此问题。

**Comment by zhangyang1995** [comment]
> 在第一次启动之后，你又修改了FQDN导致的问题，现在版本一旦fqdn配置之后，不能再修改。
> 后续版本我们会解决此问题。

好的 感谢您的回答。
