### ISSUE TITLE
Error in querying tag

### ISSUE THREAD

**Issue by cddonald** [taosdata/TDengine#3952]
2.0.5版本，statics是一个超级表，code与exchange是超级表的tag， 以下两个语句：
select * from statics where updatetime='2020-10-21 00:00:00'
select code from statics where updatetime='2020-10-21 00:00:00'
查出来的记录条数不一样，对于 select code from statics where updatetime='2020-10-21 00:00:00' 这个语句，updatetime='2020-10-21 00:00:00'的限制没有用，会查出所有的code，而且只要只查tag字段就有问题，如果查询字段里有非tag字段，就没有问题。

**Comment by hjxilinx** [comment]
This bug has been fixed, and please download and try the newly released version.
