### ISSUE TITLE
How to insert Null values

### ISSUE THREAD

**Issue by cddonald** [taosdata/TDengine#3953]
我有多行数据想一起插入，但是有几行的某些字段是空值，如何用sql语句直接插入NULL？

**Comment by ll10020163** [comment]
看类型 字符串的可以用 ''  , int等数字类型必须给初始值。 ts 的用 now 插入当前时间或者你自定义时间。

**Comment by cddonald** [comment]
所以double必须要初始值是么，或者我只能一行一行插入，没有插入的字段会自动置为NUlLL？

**Comment by hjxilinx** [comment]
This issue was closed because it has been inactive for too many days.
