### ISSUE TITLE
Batch insertion of data into different sub tables causes taosd coredump

### ISSUE THREAD

**Issue by freecite** [taosdata/TDengine#3955]
**Bug Description**
   往不同的子表中批量插入数据

**To Reproduce**
生成了coredump文件

#0  0x00007ff3678f54af in __memmove_avx_unaligned_erms () from /lib64/libc.so.6
#1  0x000000000042ae9a in mnodeSaveQueryStreamList (pConn=0x7ff2fc001150, pHBMsg=0x7ff2c8029478) at /root/TDengine/src/mnode/src/mnodeProfile.c:305
#2  0x00000000004312be in mnodeProcessHeartBeatMsg (pMsg=0x7ff2c8028ba0) at /root/TDengine/src/mnode/src/mnodeShow.c:257
#3  0x000000000042ce4b in mnodeProcessRead (pMsg=0x7ff2c8028ba0) at /root/TDengine/src/mnode/src/mnodeRead.c:83
#4  0x0000000000415d71 in dnodeProcessMnodeReadQueue (param=0x1f0cff0) at /root/TDengine/src/dnode/src/dnodeMRead.c:173
#5  0x00007ff367b5c50b in start_thread () from /lib64/libpthread.so.0
#6  0x00007ff36789438f in clone () from /lib64/libc.so.6

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [ fedora27 ]
 - Memory, CPU, current Disk Space
 - TDengine Version [2.0.5.1]

**Additional Context**

**Comment by guanshengliang** [comment]
加一下我的微信 geiseil，远程看一下

**Comment by guanshengliang** [comment]
在另外一个场景下，完全复现了此crash，这应该是客户端与服务端版本号时，因为通信协议修改导致的Crash。
更可能的是，升级服务端之后，客户端没有升级，或者客户端进程没有退出。
后续我们会做更加严格的检查，禁止连接；目前需要确保两者版本完全一致。

**Comment by guanshengliang** [comment]
There is no reply for a long time, and this problem has been located and solved in 2.0.9.0
