### ISSUE TITLE
Can I select one record every several rows?

### ISSUE THREAD

**Issue by wsf1990** [taosdata/TDengine#396]
如题，tdengine 能够实现每隔几条取出一条的功能吗？或者是否支持 rownumber 函数？

**Comment by guanshengliang** [comment]
目前不支持

**Comment by guanshengliang** [comment]
可以采用interval语句实现近似功能，例如
```
select last(*) from t interval(1m);  
```

**Comment by wsf1990** [comment]
考虑过此方法，但是我每条数据之间的时间间隔是不定的，这样无法确定interval的时间。

**Comment by guanshengliang** [comment]
目前没有其他办法，您只能全取出来自行处理

**Comment by wsf1990** [comment]
假如有几亿条，这个就完全没法操作了

**Comment by guanshengliang** [comment]
什么样的业务场景，看看是否一个典型的物联网需求

**Comment by wsf1990** [comment]
多个传感器实时采集的数据，1s可能有上千条，我现在需要绘制图表，如果是一年的数据，这个量就非常大了，所以我考虑间隔取出，绘制图表。

**Comment by guanshengliang** [comment]
这种情况为什么不能用interval呢

**Comment by wsf1990** [comment]
问题就在于每个传感器的时间间隔可能不一致

**Comment by guanshengliang** [comment]
当前版本不能处理这类问题
如果项目上有需要，可以联系我公司商务
