### ISSUE TITLE
The CPU load is too high when querying by JDBC

### ISSUE THREAD

**Issue by sanliang125** [taosdata/TDengine#3962]
**Bug Description**
项目运行的过程中，对taosd数据进行查询时，CPU负载过高，在200+%左右，而且查询速度很慢。
数据的查询频率为100ms/次。
 
**Environment **
OS: CentOS 7.8
Memory  16G, CPU   6 core , current Disk Space: 1T
TDengine Version 2.5.0.1
taos-jdbcdriver Version: 2.0.8

**Comment by yihaoDeng** [comment]
@sanliang125  主要查询语句可以贴一下吗， 还有你的机器配置？ IO是不是过高？

**Comment by sanliang125** [comment]
> @sanliang125 �主要查询语句可以贴一下吗， 还有你的机器配置？ IO是不是过高？

**CPU** :至强E-2336 六核 3.4G ,**Mmeory:** 16G，**HDD：**1T

**Comment by sanliang125** [comment]
> @sanliang125 �主要查询语句可以贴一下吗， 还有你的机器配置？ IO是不是过高？
```
      SELECT
            last_row ( ts ) AS ts,
            last_row ( DATA ) AS DATA,
            type_name as typeName
        FROM
            temperature
        WHERE
            sensor_id = 30
            AND sc_id = '10245212'
        GROUP BY
            loc,
            type_name,
            unit,
            phase;
```

**Comment by yihaoDeng** [comment]
这个语句并不会有很高的CPU消耗， 1. 你可以把日志级别设置的低一点 2.  或者你方便远程吗， 我们可以远程看一下。 @sanliang125

**Comment by sanliang125** [comment]
> 这个语句并不会有很高的CPU消耗， 1. 你可以把日志级别设置的低一点 2. 或者你方便远程吗， 我们可以远程看一下。 @sanliang125

我这边方便远程，我加您了。
