### ISSUE TITLE
insert error no=-2147483114

### ISSUE THREAD

**Issue by mxmkeep** [taosdata/TDengine#3965]
这种SQL用C的api去入的时候会报错no=-2147483114，直接终端入就不会
insert into http_hk_proxy01_0___403400 using http tags('hk','',00,0,0,0403400) values('2020-10-22 11:02:11.991453','61.219.11.153','\\x01A\\x02\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00',00.043,00,00,'172.31.174.177','','','','',0400,'http',0,0,00,'default_http_server',0,'',0,'2020-10-22 11:02:00.000000',0,'',080,0,'',05118,0,'',0,1603335731000000,0,0,'','',0,'','');

**Comment by localvar** [comment]
感谢提交问题，我们后面会分析处理。

**Comment by localvar** [comment]
因为 c 语言本身也会进行转义，您可以提供 c 调用时的源码吗？

**Comment by mxmkeep** [comment]
> 因为 c 语言本身也会进行转义，您可以提供 c 调用时的源码吗？

代码也提交到了GitHub上，入库在writetaos函数
https://github.com/mxmkeep/rsyslog-omtaos/blob/main/omtaos/omtaos.c

**Comment by mxmkeep** [comment]
create table http (
  time_local timestamp,
  remote_addr binary(64),
  request binary(1200),
  request_time double,
  request_length bigint,
  bytes_sent bigint,
  server_addr binary(64),
  http_referer binary(1200),
  http_user_agent binary(1200),
  http_x_forwarded_for binary(1200),
  http_cookie binary(1200),
  status SMALLINT,
  scheme binary(10),
  upstream_response_time double,
  upstream_status SMALLINT,
  body_bytes_sent bigint,
  host binary(128),
  up_req int,
  flag binary(64),
  cid_req_min bigint,
  time_min timestamp,
  aid int,
  ck_h binary(128),
  sv_pt int,
  cid_cc_rate int,
  pdata_h binary(128),
  pid int,
  ct_len int,
  in_flag binary(64),
  ip_conns int,
  conn_start timestamp,
  ul_port int,
  fw_id int,
  ats_via binary(32),
  rr_st binary(32),
  defid int,
  upstream_addr binary(64),
  attr binary(256)
)
tags(
  mc_name binary(32),
  custom_hostname_key binary(128),
  custom_user_id int,
  did int,
  cid int,
  custom_err_code int
);

**Comment by sangshuduo** [comment]
我们内部讨论了一下，认为这个转义处理不应该由 API 来做，taos shell 是处理了之后转给底层，应用这边应该也是这么来处理，否则会破坏底层的一致性
