### ISSUE TITLE
tag name can't be ”cluster“

### ISSUE THREAD

**Issue by yinfi** [taosdata/TDengine#3969]
接收监控数据，数据tag中包含”cluster“，在创建表过程中，显示invalid tag name。
![image](https://user-images.githubusercontent.com/3062749/96953176-10832180-1523-11eb-84be-8176e4af8eba.png)
在创建表名的时候也会出现一些报错。
使用手册中对表名和tag名称都没有明确不能包含哪些字符，请问哪里有明确的说明。或者尽量减少这种对用户输入限制。

**Comment by yihaoDeng** [comment]
tag 属于TDengine 的关键词，当然不会用在普通字符中， 目前没有一个这样的文档， 目前我们整理类似的文档，敬请期待

**Comment by yihaoDeng** [comment]
目前没有一个这样的文档， 目前我们整理类似的文档，敬请期待
