### ISSUE TITLE
"locale:en_US.UTF-8": Need I edit the configuration file for client on Windows

### ISSUE THREAD

**Issue by whljava** [taosdata/TDengine#397]
![image](https://user-images.githubusercontent.com/49359483/63480637-2e8b6700-c4c5-11e9-8470-611bb13d4441.png)
运行不出错但是一直报未能设置locale:en_US.UTF-8
是不是客户端的配置里面需要改什么东西

**Comment by guanshengliang** [comment]
需要设置正确的`locale`
很有可能是您的机器不支持`en_US.UTF-8`
如果不使用中文或者nchar字段，那么不会有任何影响
