### ISSUE TITLE
{"status":"error","code":1536,"desc":"Invalid table ID"}

### ISSUE THREAD

**Issue by gaosong1206** [taosdata/TDengine#3972]
**Bug Description**
接口类型：restful 接口
1、新建超级表A，根据超级表A新建A_1以及A-2，向表A_1,A_2中插入数据成功；
2、删除超级表A；
3、再次新建超级表A，根据超级表A新建A_1以及A-2，向表A_1,A_2中中插入数据失败，但是在taos客户端中执行sql语句可以插入成功
4、重启数据库，插入数据成功。

**To Reproduce**
1. curl -u root:taosdata -d 'create database if not exists ksh;' 192.168.2.66:6041/rest/sql
2. curl -u root:taosdata -d 'create table if not exists ksh.Table1(DataTime  timestamp ,DataQuality binary(256), temperature INT,humidity INT,hair INT)tags (ObjectID BINARY(256),ObjectName BINARY(256),ProjectName BINARY(256),Location BINARY(256));' 192.168.2.66:6041/rest/sql
3.curl -u root:taosdata -d 'create table if not exists ksh.Table1_Object1 using ksh.Table1 tags("1","Object1","project01","XiAn");' 192.168.2.66:6041/rest/sql
4.curl -u root:taosdata -d 'create table if not exists ksh.Table1_Object2 using ksh.Table1 tags("1","Object1","project01","XiAn");' 192.168.2.66:6041/rest/sql
5.curl -u root:taosdata -d 'insert into ksh.Table1_Object1 (datatime,dataquality,temperature,humidity,hair) values ("2020-10-23 17:27:44.137","192",642,642,632) ksh.Table1_Object2(datatime,dataquality,temperature,humidity,hair) values("2020-10-23 17:27:44.137","192",628,626,623); ' 192.168.2.66:6041/rest/sql

6.curl -u root:taosdata -d 'drop table if exists ksh.Table1;' 192.168.2.66:6041/rest/sql

7. curl -u root:taosdata -d 'create table if not exists ksh.Table1(DataTime  timestamp ,DataQuality binary(256), temperature INT,humidity INT,hair INT)tags (ObjectID BINARY(256),ObjectName BINARY(256),ProjectName BINARY(256),Location BINARY(256));' 192.168.2.66:6041/rest/sql
8.curl -u root:taosdata -d 'create table if not exists ksh.Table1_Object1 using ksh.Table1 tags("1","Object1","project01","XiAn");' 192.168.2.66:6041/rest/sql
9.curl -u root:taosdata -d 'create table if not exists ksh.Table1_Object2 using ksh.Table1 tags("1","Object1","project01","XiAn");' 192.168.2.66:6041/rest/sql
10.curl -u root:taosdata -d 'insert into ksh.Table1_Object1 (datatime,dataquality,temperature,humidity,hair) values ("2020-10-23 17:27:44.137","192",642,642,632) ksh.Table1_Object2(datatime,dataquality,temperature,humidity,hair) values("2020-10-23 17:27:44.137","192",628,626,623); ' 192.168.2.66:6041/rest/sql

11.返回错误值：{"status":"error","code":1536,"desc":"Invalid table ID"}

12.如果直接在taos客户端中执行插入sql语句的命令，可以插入数据成功

13.重启数据库后，插入数据成功。

**Environment (please complete the following information):**
 - OS: CentOS 7.0或NeoKylin Linux Advanced Server V7Update4
 - TDengine Version：2.0.5.0

**log
10/23 22:17:08.661386 0x7f2bc0bb1700 DND 0x7f2b8001c120, rpc msg:submit will be processed in vwrite queue
10/23 22:17:08.661410 0x7f2bc0bb1700 TDB ERROR vgId:3 failed to get table to insert data, uid 844424946917849 tid 1
10/23 22:17:08.661416 0x7f2bc0bb1700 TDB ERROR vgId:3 failed to insert data since Invalid table ID
10/23 22:17:08.661507 0x7f2ba17e0700 TSC WARN 0x7f2b8001c120 it shall renew table meta, code:Invalid table ID, retry:1
10/23 22:17:08.662024 0x7f2baa7f2700 MND user:root, auth info is returned
10/23 22:17:08.662070 0x7f2bad7f8700 DND 0x7f2b6c00c8c0, msg:table-meta will be processed in mread queue
10/23 22:17:08.662074 0x7f2bad7f8700 MND app:0x7f2b6c00c8c0:0x7f2b74000dc0, table:0.ksh.table1_object1, table meta msg is received from thandle:0x1bdb020, createFlag:0
10/23 22:17:08.662100 0x7f2bad7f8700 MND app:0x7f2b6c00c8c0:0x7f2b74000dc0, table:0.ksh.table1_object1, uid:844424980473126 table meta is retrieved, vgId:3 sid:3
10/23 22:17:08.662327 0x7f2bc0bb1700 DND 0x7f2b8001c120, rpc msg:submit will be processed in vwrite queue
10/23 22:17:08.662347 0x7f2bc0bb1700 TDB ERROR vgId:3 failed to get table to insert data, uid 844424963695171 tid 2
10/23 22:17:08.662352 0x7f2bc0bb1700 TDB ERROR vgId:3 failed to insert data since Invalid table ID
10/23 22:17:08.662382 0x7f2ba17e0700 TSC WARN 0x7f2b8001c120 it shall renew table meta, code:Invalid table ID, retry:2
10/23 22:17:08.662578 0x7f2badff9700 DND 0x7f2b6c00c8c0, msg:table-meta will be processed in mread queue
10/23 22:17:08.662584 0x7f2badff9700 MND app:0x7f2b6c00c8c0:0x7f2b74000d70, table:0.ksh.table1_object1, table meta msg is received from thandle:0x1bdb020, createFlag:0
10/23 22:17:08.662597 0x7f2badff9700 MND app:0x7f2b6c00c8c0:0x7f2b74000d70, table:0.ksh.table1_object1, uid:844424980473126 table meta is retrieved, vgId:3 sid:3
10/23 22:17:08.662949 0x7f2bc0bb1700 DND 0x7f2b8001c120, rpc msg:submit will be processed in vwrite queue
10/23 22:17:08.662991 0x7f2bc0bb1700 TDB ERROR vgId:3 failed to get table to insert data, uid 844424963695171 tid 2
10/23 22:17:08.662999 0x7f2bc0bb1700 TDB ERROR vgId:3 failed to insert data since Invalid table ID
10/23 22:17:08.663136 0x7f2ba17e0700 TSC WARN 0x7f2b8001c120 it shall renew table meta, code:Invalid table ID, retry:3
10/23 22:17:08.663552 0x7f2bad7f8700 DND 0x7f2b6c00c8c0, msg:table-meta will be processed in mread queue
10/23 22:17:08.663578 0x7f2bad7f8700 MND app:0x7f2b6c00c8c0:0x7f2b74000d70, table:0.ksh.table1_object1, table meta msg is received from thandle:0x1bdb020, createFlag:0
10/23 22:17:08.663624 0x7f2bad7f8700 MND app:0x7f2b6c00c8c0:0x7f2b74000d70, table:0.ksh.table1_object1, uid:844424980473126 table meta is retrieved, vgId:3 sid:3
10/23 22:17:08.664074 0x7f2bc0bb1700 DND 0x7f2b8001c120, rpc msg:submit will be processed in vwrite queue
10/23 22:17:08.664106 0x7f2bc0bb1700 TDB ERROR vgId:3 failed to get table to insert data, uid 844424963695171 tid 2
10/23 22:17:08.664111 0x7f2bc0bb1700 TDB ERROR vgId:3 failed to insert data since Invalid table ID
10/23 22:17:08.664137 0x7f2ba17e0700 TSC WARN 0x7f2b8001c120 it shall renew table meta, code:Invalid table ID, retry:4
10/23 22:17:08.664203 0x7f2badff9700 DND 0x7f2b6c00c8c0, msg:table-meta will be processed in mread queue
10/23 22:17:08.664211 0x7f2badff9700 MND app:0x7f2b6c00c8c0:0x7f2b74000d70, table:0.ksh.table1_object1, table meta msg is received from thandle:0x1bdb020, createFlag:0
10/23 22:17:08.664234 0x7f2badff9700 MND app:0x7f2b6c00c8c0:0x7f2b74000d70, table:0.ksh.table1_object1, uid:844424980473126 table meta is retrieved, vgId:3 sid:3
10/23 22:17:08.664474 0x7f2bc0bb1700 DND 0x7f2b8001c120, rpc msg:submit will be processed in vwrite queue
10/23 22:17:08.664498 0x7f2bc0bb1700 TDB ERROR vgId:3 failed to get table to insert data, uid 844424963695171 tid 2
10/23 22:17:08.664502 0x7f2bc0bb1700 TDB ERROR vgId:3 failed to insert data since Invalid table ID
10/23 22:17:08.664525 0x7f2ba17e0700 TSC WARN 0x7f2b8001c120 it shall renew table meta, code:Invalid table ID, retry:5
10/23 22:17:08.664583 0x7f2bad7f8700 DND 0x7f2b6c00c8c0, msg:table-meta will be processed in mread queue
10/23 22:17:08.664597 0x7f2bad7f8700 MND app:0x7f2b6c00c8c0:0x7f2b74000d70, table:0.ksh.table1_object1, table meta msg is received from thandle:0x1bdb020, createFlag:0
10/23 22:17:08.664611 0x7f2bad7f8700 MND app:0x7f2b6c00c8c0:0x7f2b74000d70, table:0.ksh.table1_object1, uid:844424980473126 table meta is retrieved, vgId:3 sid:3
10/23 22:17:08.664894 0x7f2bc0bb1700 DND 0x7f2b8001c120, rpc msg:submit will be processed in vwrite queue
10/23 22:17:08.664917 0x7f2bc0bb1700 TDB ERROR vgId:3 failed to get table to insert data, uid 844424963695171 tid 2
10/23 22:17:08.664921 0x7f2bc0bb1700 TDB ERROR vgId:3 failed to insert data since Invalid table ID
10/23 22:17:08.664939 0x7f2ba17e0700 TSC WARN 0x7f2b8001c120 it shall renew table meta, code:Invalid table ID, retry:6
10/23 22:17:08.664941 0x7f2ba17e0700 TSC ERROR 0x7f2b8001c120 max retry 5 reached, give up
10/23 22:17:08.664967 0x7f2ba7fed700 HTP ERROR context:0x1bd3cd0, fd:24, user:root, query error, code:Invalid table ID, sqlObj:0x7f2b80000a70
10/23 22:17:08.664981 0x7f2ba7fed700 HTP ERROR context:0x1bd3cd0, fd:24, code:400, error:Invalid table ID
10/23 22:17:08.690777 0x7f2badff9700 DND 0x7f2b88001170, msg:heartbeat will be processed in mread queue
10/23 22:17:09.231391 0x7f2bad7f8700 DND 0x7f2b6c004e20, msg:heartbeat will be processed in mread queue
10/23 22:17:09.620934 0x7f2bacff7700 DND msg:status will be processed in mpeer queue
10/23 22:17:09.987953 0x7f2badff9700 DND 0x7fd7e0001170, msg:heartbeat will be processed in mread queue
10/23 22:17:10.195765 0x7f2bad7f8700 DND 0x7f2b88001170, msg:heartbeat will be processed in mread queue
10/23 22:17:10.625796 0x7f2bacff7700 DND msg:status will be processed in mpeer queue
10/23 22:17:10.736048 0x7f2badff9700 DND 0x7f2b6c004e20, msg:heartbeat will be processed in mread queue
10/23 22:17:11.492534 0x7f2bad7f8700 DND 0x7fd7e0001170, msg:heartbeat will be processed in mread queue
10/23 22:17:11.631108 0x7f2bacff7700 DND msg:status will be processed in mpeer queue
10/23 22:17:11.700921 0x7f2badff9700 DND 0x7f2b88001170, msg:heartbeat will be processed in mread queue
10/23 22:17:12.241262 0x7f2bad7f8700 DND 0x7f2b6c004e20, msg:heartbeat will be processed in mread queue
10/23 22:17:12.636229 0x7f2bacff7700 DND msg:status will be processed in mpeer queue
10/23 22:17:12.997714 0x7f2badff9700 DND 0x7fd7e0001170, msg:heartbeat will be processed in mread queue
10/23 22:17:13.206112 0x7f2bad7f8700 DND 0x7f2b88001170, msg:heartbeat will be processed in mread queue

**Comment by localvar** [comment]
我们已经重现，后面会处理。

**Comment by gaosong1206** [comment]
请问问题处理了吗？

**Comment by lzqdename** [comment]
这个我也碰到过，前一秒sql插入还是好好的，后一秒也是这个错误。。。

**Comment by fenghua1997** [comment]
This issue was closed because it has been inactive for too many days.
