### ISSUE TITLE
could documentation of alert module be more detailed?

### ISSUE THREAD

**Issue by shuanger051** [taosdata/TDengine#3974]
文档上写的东西看不懂啊，数据流程图没有。那上面写了"tdengine": "root:taosdata@/tcp(127.0.0.1:0)/", 这句话什么意思？能否多敲几个字说明一下，文档让人看的真想骂人。还有那示例 127.0.0.1:0 后面那个端口0 是啥意思，这个跟taos默认的6030端口是什么关系？？写demo的时候，能不能贴近下实例不要自由随意发挥，文档是给别人看的，又不是给自己的开发人员看的。

**Comment by yihaoDeng** [comment]
谢谢建议，已经更新了
