### ISSUE TITLE
insertion failure when timestamp is before current time. Return results: Query OK, 0 rows affected

### ISSUE THREAD

**Issue by wxtcstt** [taosdata/TDengine#398]
taos> insert into t values ('2019-08-22 11:01:00', 10);
Query OK, 0 row(s) affected (0.000589s)

taos> insert into t values ('2019-08-22 11:04:00', 10);
Query OK, 0 row(s) affected (0.000418s)

taos> insert into t values ('2019-08-22 100:04:00', 10);

TSDB error: invalid SQL: near "8-22 100:04:00', 10);" syntax error

taos> insert into t values ('2019-08-22 10:04:00', 10);
Query OK, 0 row(s) affected (0.000420s)

taos> insert into t values ('2019-08-22 15:04:00', 10);
Query OK, 1 row(s) affected (0.000391s)

taos> insert into t values ('2019-08-22 5:04:00', 10);
Query OK, 0 row(s) affected (0.000610s)

**Comment by LijunYu81** [comment]
同样的问题，我的版本是1.6.1.5
taos> insert into points_1  values  ('2019-08-20 07:45:39.000',178.9619327724561,450.9247835516004);
Query OK, 0 row(s) affected (0.001008s)

**Comment by LijunYu81** [comment]
同样的问题，我的版本是1.6.1.5，points_1是超级表points的子表
taos> insert into points_1  values  ('2019-08-20 07:45:39.000',178.9619327724561,450.9247835516004);
Query OK, 0 row(s) affected (0.001008s)

**Comment by guanshengliang** [comment]
执行如下语句，获取该表中最后一条语句的时间戳
```
select last(*) from points_1
```
看看新进入的时间戳是否满足单调增长的条件

**Comment by guanshengliang** [comment]
也可将`insert`关键字替换为`import`
