### ISSUE TITLE
data migration

### ISSUE THREAD

**Issue by wzf55555** [taosdata/TDengine#3987]
把1.6服务器中的数据使用dump工具导出，然后使用2.0中的dump导入。
导出来的数据都是十几个G的文件。导入总是报错如下如：
![QQ图片20201024213505](https://user-images.githubusercontent.com/40660395/97083125-bd06f580-1640-11eb-8772-35aae6cab9e3.png)
显示多少行错误但是没有显示实际问题。
这种文件太大出现问题根本没有快速定位问题。
![QQ图片20201024213505](https://user-images.githubusercontent.com/40660395/97084117-546f4700-1647-11eb-94eb-59f651eda468.png)
最后还报错。（总线错误，吐核）

**Comment by Shawshank-Smile** [comment]
工具的问题，需要具体分析，请li hui处理。

**Comment by plum-lihui** [comment]
错误提示中有显示是那一行的sql有问题，请将那行贴上来看下。是不是导出的时候出现了问题。
