### ISSUE TITLE
what happening if all new connectors would not be closed

### ISSUE THREAD

**Issue by treemp3** [taosdata/TDengine#399]
使用MongoDB的时候，是可以新建连接不用关闭（close）的。
TDengine会怎么样？
频繁新建、关闭连接，是否会影响性能？连接如何重用？有超时时间吗？有无连接池？
比如WEB程序接收物联网数据，是针对每个请求新建一个数据库连接吗？
TDengine推荐的做法是什么呢？

**Comment by guanshengliang** [comment]
```
使用C、java等语言，调用libtaos.so创建链接的，通过udp和tcp传递数据
1.保持长链接，不要每次使用打开然后关闭
2.每次链接的创建会消耗资源，并花费少量时间
3.如果存在过多未关闭的链接，链接数将可能会被耗光
4.mongo可以这么做，猜测是其内部采用了连接池
```
```
如果采用http接口
1.尽量使用http1.1协议，会提升效率
2.如果采用1.0协议，并不会有问题
```

**Comment by treemp3** [comment]
谢谢回复，保持长链接有个问题就是，当链接因为网络原因中断之后，新接收的请求就无法响应了（报错）。
可以借鉴下mongo的做法吗，在数据库层做一个连接池，当连接无活动或超时，自动释放。
这样确实可以省开发人员很多事，也是个人喜欢MongoDB的一点。

**Comment by treemp3** [comment]
保持长连接的话，那也就是说，conn对象常驻内存，不需要调用conn.close()了是吧。
我用的是Python。
如果不需要close的话，共用conn对象会不会引起冲突呢，因为clear_result_set()是conn对象的方法。
如果cursorA和cursorB共用conn对象，cursorA正在查询，cursorB调用了clear_result_set()会怎么样呢

**Comment by treemp3** [comment]
怎么不回复呢，我不得不考虑：自己做一个Python3版的数据库连接池管理，哎。

**Comment by treemp3** [comment]
我做了一个简单的数据库连接管理，不知道对不对，请大佬指教：
`#! /usr/bin/env python
# -*- coding: utf-8 -*-
"""
TDengine client libs.
"""
import logging
import traceback

import taos

__author__ = 'foxiyang@qq.com'

DB_CONN_LIST = []  # 数据库连接池


def db_conn():
    """连接数据库"""
    if DB_CONN_LIST:
        conn = DB_CONN_LIST.pop()
    else:
        conn = taos.connect(host="192.168.1.226", user="root", password="taosdata", database="iot")
    return conn


def db_query(sql):
    """执行查询SQL语句"""
    cols, data = (None, None)
    conn = None
    cursor = None
    try:
        conn = db_conn()
        cursor = conn.cursor()
        cursor.execute(sql)
        cols = [desc[0] for desc in cursor.description]
        data = cursor.fetchall()
    except:
        if cursor:
            cursor.close()
        if conn:
            conn.close()
        logging.error(traceback.format_exc())
    else:
        cursor.close()
        DB_CONN_LIST.append(conn)

    return cols, data


def db_update(sql):
    """执行更新SQL语句"""
    affected_rows = 0  # 影响的记录数
    conn = None
    cursor = None
    try:
        conn = db_conn()
        cursor = conn.cursor()
        affected_rows = cursor.execute(sql)
    except:
        if cursor:
            cursor.close()
        if conn:
            conn.close()
        logging.error(traceback.format_exc())
    else:
        cursor.close()
        DB_CONN_LIST.append(conn)
    return affected_rows
`

**Comment by guanshengliang** [comment]
长连接的意思只是连接用到的资源不回收，但是driver会定时检查连接的健康情况，并重连。
因此不存在网络中断再回复，而导致连接不可用的情况。

**Comment by guanshengliang** [comment]
你先的链接管理没问题，只是每次都要执行SQL语句都需要新建和关闭连接。
我想你有能力，自己开发一个连接池

**Comment by treemp3** [comment]
大佬好，代码中并没有关闭连接，关闭的是cursor

**Comment by guanshengliang** [comment]
OK，那是我看错了
