### ISSUE TITLE
linux上部署成功，但是本地window却连不上

### ISSUE THREAD

**Issue by hlz5857475** [taosdata/TDengine#3991]
我是通过git clone https://github.com/taosdata/TDengine.git 下载源码安装的，请问linux上查看service的版本的命令是什么，taos --v  看到client版本是2.0.5.1，那么service的本版也是这个吗？
我在window上想用通过idea连接TDengine开发，必须要在windows上安装客户端吗，服务端，客户端，驱动的版本号必须是一样的吗

**Comment by ll10020163** [comment]
https://github.com/taosdata/TDengine/issues/3960     配置下FQDN

**Comment by hlz5857475** [comment]
配置过了呢

**Comment by sangshuduo** [comment]
看 #3994 是windows已经连上了，所以这个 issue 可以关了吧？
