### ISSUE TITLE
after modify config file on windows client can connect to TDengine on Linux  but the springboot demo can't connect to

### ISSUE THREAD

**Issue by hlz5857475** [taosdata/TDengine#3994]
参照 SpringBoot + Mybatis Demo ，本地host文件也指定完毕，项目一启动，linux中的TDengine状态就变为failed
taosd.service - TDengine server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since 一 2020-10-26 14:37:12 CST; 821ms ago
  Process: 50174 ExecStart=/usr/bin/taosd (code=killed, signal=ABRT)
 Main PID: 50174 (code=killed, signal=ABRT)

10月 26 14:37:12 lz.com systemd[1]: taosd.service: main process exited, code=killed, status=6/ABRT
10月 26 14:37:12 lz.com systemd[1]: Unit taosd.service entered failed state.
10月 26 14:37:12 lz.com systemd[1]: taosd.service failed.
10月 26 14:37:12 lz.com systemd[1]: taosd.service holdoff time over, scheduling restart.
10月 26 14:37:12 lz.com systemd[1]: Stopped TDengine server service.
10月 26 14:37:12 lz.com systemd[1]: start request repeated too quickly for taosd.service
10月 26 14:37:12 lz.com systemd[1]: Failed to start TDengine server service.
10月 26 14:37:12 lz.com systemd[1]: Unit taosd.service entered failed state.
10月 26 14:37:12 lz.com systemd[1]: taosd.service failed.

idea控制台显示
2020-10-26 14:49:36.964 ERROR 16916 --- [           main] o.a.tomcat.jdbc.pool.ConnectionPool      : Unable to create initial connections of pool.
java.sql.SQLException: TDengine Error: Unable to establish connection

windows客户端的日志文件显示
10/26 14:49:36.833000 0x00002654 RPC ERROR TSC, failed to create eventfd(No such file or directory)
10/26 14:49:36.935000 0x00002654 JNI ERROR jobj:0000000002AAD230, conn:0000000000000000, connect to database failed, host=192.168.203.129, user=root, dbname=log, port=6030
10/26 14:49:36.943000 0x00002654 JNI ERROR jobj:0000000002AAD1B0, connection is closed
10/26 14:49:36.976000 0x00002654 RPC ERROR TSC, failed to create eventfd(Invalid argument)
10/26 14:49:37.020000 0x00002654 RPC ERROR TSC, failed to create eventfd(Invalid argument)
10/26 14:49:37.122000 0x00002654 RPC ERROR TSC, failed to create eventfd(Invalid argument)
10/26 14:49:42.219000 0x00002b9c RPC ERROR TSC, failed to create eventfd(No error)

这个问题困扰好久了，哪位大佬帮忙看一下

**Comment by ll10020163** [comment]
看这个https://github.com/taosdata/TDengine/issues/3960   FQDN

**Comment by hlz5857475** [comment]
本地idea启动项目，就会把linux中的TDengine搞崩，但是windows本地启动客户端去连接就可以成功，这是为何，

**Comment by zyyang-taosdata** [comment]
这个应该是你环境配置的问题，检查你的server防火墙是否关闭，client端是否配置hosts文件
