### ISSUE TITLE
call "select * from super table" sql statement will crash the taosd

### ISSUE THREAD

**Issue by cleverpig** [taosdata/TDengine#3996]
**Bug Description**
I found call "select * from super table" sql statement will crash the taosd.

**To Reproduce**
1. run 'taos' to connect taosd which has super table;
2. type any sql statement to select * from a super table;

**Expected Behavior**
Even though it's caller's failure and incorrect operation, but I think fix it better for improve user experience.

**Screenshots**
This is taos client sreensnapshot:
![image](https://user-images.githubusercontent.com/580435/97149278-7ed81600-17a7-11eb-930e-6e13682c6d8c.png)

This is taos server log:
![image](https://user-images.githubusercontent.com/580435/97149319-8f888c00-17a7-11eb-9ee1-6cc8d9da7d3d.png)

**Environment (please complete the following information):**
 - OS: [CentOS 7.0]
 - TDengine Version [2.0.5.1]

**Comment by sangshuduo** [comment]
It's really strange. I use select \* from super table day by day and did not see this kind of issue. Could you please provide more information like the database's schema, the number of tables, the number of records, etc.

**Comment by cleverpig** [comment]
Ok! It's about weather data.

Super Table（has station_id and station_name tags）：
![image](https://user-images.githubusercontent.com/580435/97664410-7b999e80-1ab5-11eb-9d6a-7e5a4bec41ac.png)

Table(station_id='a1313',station_name='hebei'):
![image](https://user-images.githubusercontent.com/580435/97664828-9704a980-1ab5-11eb-92b8-bb02df4d9a64.png)

Table data sample:
![image](https://user-images.githubusercontent.com/580435/97665149-ab48a680-1ab5-11eb-9355-7622e93959a1.png)

**Comment by cleverpig** [comment]
@sangshuduo

**Comment by sangshuduo** [comment]
@cleverpig could you please try the latest version 2.0.6 for verification?

**Comment by cleverpig** [comment]
> @cleverpig could you please try the latest version 2.0.6 for verification?

Ok, I will try the new version!

**Comment by cleverpig** [comment]
latest version 2.0.6 is ok!
BTW: I use sourcecode compiled binary, It works too! THANKS sir!
