### ISSUE TITLE
能不能提供一个 Docker 容器版本？

### ISSUE THREAD

**Issue by abel533** [taosdata/TDengine#40]
能不能提供一个 Docker 容器版本？

可以更方便的快速入手使用或学习。

**Comment by 2efPer** [comment]
可以参考这个https://github.com/2efPer/tdengine-docker

**Comment by abel533** [comment]
`CMD ["./build/bin/taosd","-c","test/cfg"]` 路径不对。

即使修改正确路径后，仍然启动不了。

有类似下面的错误：

```
sh-4.2# ./taosd --help
option file:/etc/taos/taos.cfg not found, all options are set to system default
07/15 09:19:11.849539 7fd981b5a740 UTL timezone not configured, set to system default: (UTC, +0000)
07/15 09:19:11.849568 7fd981b5a740 UTL locale not configured, set to system default:C
failed to get charset, please set the valid charset in config file
07/15 09:19:11.849581 7fd981b5a740 UTL failed to get charset, please set the valid charset in config file
sh-4.2# ./taos
option file:/etc/taos/taos.cfg not found, all options are set to system default
failed to get charset, please set the valid charset in config file

```

**Comment by 2efPer** [comment]
> `CMD ["./build/bin/taosd","-c","test/cfg"]` 路径不对。
> 
> 即使修改正确路径后，仍然启动不了。
> 
> 有类似下面的错误：
> 
> ```
> sh-4.2# ./taosd --help
> option file:/etc/taos/taos.cfg not found, all options are set to system default
> 07/15 09:19:11.849539 7fd981b5a740 UTL timezone not configured, set to system default: (UTC, +0000)
> 07/15 09:19:11.849568 7fd981b5a740 UTL locale not configured, set to system default:C
> failed to get charset, please set the valid charset in config file
> 07/15 09:19:11.849581 7fd981b5a740 UTL failed to get charset, please set the valid charset in config file
> sh-4.2# ./taos
> option file:/etc/taos/taos.cfg not found, all options are set to system default
> failed to get charset, please set the valid charset in config file
> ```
服务进程绝对路径是/app/TDengine-master/build/build/bin/taosd
配置文件目录是在/app/TDengine-master/build/test/cfg/
启动服务必须加-c 参数跟配置文件目录，你改正确路径之后那个问题应该是没指定配置文件目录。

原来那个目录确实是我写错路径了，当时没用后台进程运行，没注意这个，刚刚更新了一版应该没问题了。

**Comment by abel533** [comment]
已经可以使用了，非常感谢！！！

运行容器后通过 exec 进入，然后执行 `build/bin/taos -c test/cfg` 即可进入 taos 命令行。

**Comment by xinqiyang** [comment]
非常赞啊。我们尝试下这个docker的版本。。。。

**Comment by qswang123** [comment]
> 已经可以使用了，非常感谢！！！
> 运行容器后通过 exec 进入，然后执行 build/bin/taos -c test/cfg 即可进入 taos 命令行。

按照你说的方法运行后报了一个错误：TSDB error: failed to connect to server，请指教，谢谢

**Comment by xinqiyang** [comment]
build 了docker， 一个是   server ， 开放了 端口 6020， 6030， 6035 
ae44ba578984        coinphd/taos         "./build/bin/taosd -…"   5 minutes ago       Up 5 minutes        0.0.0.0:6020->6020/tcp, 0.0.0.0:6030->6030/tcp, 0.0.0.0:6035->6035/tcp, 0.0.0.0:10322->22/tcp   taos_taosubuntu_1

build了一个客户端，  通过客户端去连接  服务器端 
04dffcbc2c7d        coinphd/taosdev      "./build/bin/taosd -…"   12 minutes ago      Up 12 minutes       0.0.0.0:6031->6031/tcp                                                                          dev_taosubuntu_1

提示连接失败。。。。 
root@taosubuntu:/app/TDengine-master/build/build/bin# ./taos
07/16 15:49:04.357496 7f6d729b1b80 ERROR UTL can't get card name from ip:192.168.1.103
07/16 15:49:04.360462 7f6d729b1b80 ERROR UTL failed to bind udp socket: 99 (Cannot assign requested address), 192.168.1.103:0
TSDB error: App error

配置文件： 

# Internal IP address of the server, which can be acquired by using ifconfig command.
internalIp            192.168.1.103

# client local IP
localIp               192.168.1.103


难道只能通过本地访问么，docker的2个docker直接如何访问 ？

**Comment by forjyoung** [comment]
执行 taosd 命令报错 "failed to get charset, please set the valid charset in config file"，修改 /etc/taos/taos.cfg 的 charset，明确指定字符集。
