### ISSUE TITLE
 taos failed to connect to server after upgrading to 1.6.1.6

### ISSUE THREAD

**Issue by 59471032** [taosdata/TDengine#400]
[root@pigx-rabbitmq ~]# taos

Welcome to the TDengine shell, client version:1.6.1.6  
TSDB error: failed to connect to server

**Comment by guanshengliang** [comment]
看看taosd进程是否还在
```
ps -ef | grep taosd
```

**Comment by guanshengliang** [comment]
如果进程不在，可以尝试执行
```
sudo gdb taosd
```
如果有错误信息，截图出来
