### ISSUE TITLE
user permission

### ISSUE THREAD

**Issue by aybthebest** [taosdata/TDengine#4004]
目前对于用户权限有以下两个需求：
1. 限制不同的库/表对不同的用户访问
2. 类似Mysql的`GRANT`功能，可将特定的库/表权限分配给其他用户

想问一下：
1. 企业版是否支持上述权限管理功能？
2. 社区版后续是否有相关的开发计划？

**Comment by guanshengliang** [comment]
现阶段对权限考虑不多，时序数据库通常不会在这方面有过多考虑。即便是系统中采用关系型数据库，权限这方面也多是由业务层处理。

当然不排除特定业务场景中确实有这方面的需求，因此企业版中有这方面的考虑，但是也并不完善，因为还没实际的来自生产方面的需求，您可以与销售联系，看看是否在可以在企业版中做定制开发。

**Comment by Aries-Lee1991** [comment]
您的这种需求，请邮件联系：support@taosdata.com，或者微信添加：tdengine。
