### ISSUE TITLE
remote backup

### ISSUE THREAD

**Issue by moziie** [taosdata/TDengine#4005]
现在有一部分业务数据了,为了安全考虑做异地备份,请问应该怎么做;如果做了异地备份请问如何操作恢复备份数据呢

**Comment by hzcheng** [comment]
直接将数据文件夹的内容（默认为/var/lib/taos）打包拷贝出去就可以了。要恢复的话，再把数据打包拷贝回来就可以了（前提是hostname不变）。

**Comment by moziie** [comment]
请问如果想实现增量备份的话,请问有什么实现思路或者方法吗

**Comment by Robinsir** [comment]
遇到同样的问题
