### ISSUE TITLE
关于订阅中的联表查询

### ISSUE THREAD

**Issue by ChuTingxu** [taosdata/TDengine#4009]
订阅单个表的数据正常，但订阅的sql语句改为联表查询时，出现异常。tb1，tb2为超级表，id为标签，time为时间戳
select * from tb1,tb2 where tb1.id = tb2.id and tb1.time = tb2.time
问题一：该条语句在终端中执行正常，但耗时在0.19s，两个数据表中各只有一条数据，这个速度是否是正常速度？
问题二：当在订阅中的sql语句使用上面的联表查询时报错，我不清楚订阅是否支持联表查询语句？
![1603777159(1)](https://user-images.githubusercontent.com/25150748/97264275-9a9ef300-185f-11eb-9e07-e4205c11bbb4.jpg)

**Comment by localvar** [comment]
目前订阅使用的 sql 语句 “只能是 select 语句，只应查询原始数据，只能按时间正序查询数据”，而这种连表查询实际会出现不按时间正序的情况，所以还不能支持。相应的错误报告方式我们会在后面改的友好一些。
