### ISSUE TITLE
libtaos.so not found, after I install python connector in the Raspberry Pi

### ISSUE THREAD

**Issue by wxtcstt** [taosdata/TDengine#401]

**Comment by guanshengliang** [comment]
尝试配置环境变量
```
LD_LIBRARY_PATH
```

**Comment by wxtcstt** [comment]
> 尝试配置环境变量
> 
> ```
> LD_LIBRARY_PATH
> ```

在树莓派上 pip install 提示安装成功，之后找不到任何taos相关的.so ,全盘搜索 find /  -name *taos* 没有找到

**Comment by fangpanpan** [comment]
> > 尝试配置环境变量
> > ```
> > LD_LIBRARY_PATH
> > ```
> 
> 在树莓派上 pip install 提示安装成功，之后找不到任何taos相关的.so ,全盘搜索 find / -name _*taos_* 没有找到

在tdengine安装成功后就会生成libtaos.so，请问您成功安装了tdengine吗？以及您是用源码安装（build/bin/)还是用安装包安装(/usr/local/taos/driver/)？

**Comment by skyformat99** [comment]
树莓派的是啥CPU？ 难度不应该重新编译吗？
