### ISSUE TITLE
large sql cannot be used in v2.0.6 even after enlarge maxSQLLength

### ISSUE THREAD

**Issue by huawenyao** [taosdata/TDengine#4014]
单机版2.0.6
插入sql语句300行数据 7W字符 报错
只插入100行数据时OK
修改maxSQLLength 属性等于  1024000 重启taosd 仍然无效
java  druid连接池  jdbcTemplate.execute执行的插入

建表语句

CREATE TABLE t_inf_share (
  ts timestamp,
  share_id binary(64),
  parent_id binary(64),
  share_chain binary(500),
  tenant_id binary(64),
  product_code binary(64),
  from_user_id binary(64),
  user_id binary(64),
  nickname nchar(64),
  avatar nchar(255) ,
  share_type tinyint(2) ,
  share_level  tinyint(4),
  share_source_code binary(64) ,
  share_data nchar(1000),
  status tinyint(2) ,
  domain binary(64) ,
  channel nchar(64) ,
  created_at timestamp,
  created_by binary(64),
  updated_at timestamp ,
  updated_by binary(64),
  is_deleted tinyint(2));
  
样例数据：
insert into  t_inf_share  values(1603786834478,'000012f0','b1dcdd40','b1dcdd40-','null','null','hxjt2142BTkvFig0','hxjt2142BTkvFig0','null','null','1','1','hxjt2142_card','hxjt2142_card','1','zhiwu','wechat','2020-05-04 12:30:39.0','null','2020-05-04 12:30:39.0','null','0')

**Comment by zyyang-taosdata** [comment]
maxSQLLength参数需要在客户端设置并确保生效，请检查client的配置文件中是否设置了maxSQLLength，并检查应用程序的是否指定了其他配置文件

**Comment by zyyang-taosdata** [comment]
如果没问题的话，请关闭这个issue

**Comment by huawenyao** [comment]
ok
