### ISSUE TITLE
rust bindings outdated

### ISSUE THREAD

**Issue by songtianyi** [taosdata/TDengine#4016]
tdengine 的最新的接口做了很多变更，但是 `tests/examples/rust` 还未同步支持，最近的更新是15个月之前的。
我针对最新的接口做了适配 [tdengine-rust-bindings](https://github.com/songtianyi/tdengine-rust-bindings).
现在不确定是直接覆盖 `tests/examples/rust` 目录，还是像go一样，以submodule的形式链接上去？

**Comment by sangshuduo** [comment]
connector 有其他考虑需要用 submodule，比如提交到各自生态的仓库或市场的需求。如果没有这个需要建议覆盖方式。

**Comment by songtianyi** [comment]
感谢。
参考你的建议，我觉得链接的形式更好一点。
1. 目前 rust binding 支持的接口不多，后续变更，使用第三方仓库比较好维护，不用频繁pr到tdengine
2. 剥离责任，第三方代码如果直接放在tdengine，且tdengine没有专人维护，影响不好。
3. rust binding 属于一个 lib，可以发布在crate仓库，供上层业务使用，不用copy代码过去。
