### ISSUE TITLE
grafanal添加tdengine插件连接不上，服务端确认在正常工作，通过taos可以操作服务端

### ISSUE THREAD

**Issue by duanfeixiang** [taosdata/TDengine#4017]
1. 确认tdengine服务端正常工作：
![image](https://user-images.githubusercontent.com/39833797/97288157-6ee03500-1880-11eb-9f85-fd1a7b46b945.png)

2. 使用插件连接tdengine测试连接时提示如下错误：
![image](https://user-images.githubusercontent.com/39833797/97288170-73a4e900-1880-11eb-9e33-2a8d125621d5.png)

3. grafana中查看日志，error信息为：
![image](https://user-images.githubusercontent.com/39833797/97288107-5a03a180-1880-11eb-99c2-aae5fd9b2413.png)

请问这种是什么原因导致的呢？

**Comment by xiaopingcs** [comment]
端口错了，应该是6041
请参考https://www.taosdata.com/cn/documentation/connections-with-other-tools/#Grafana

**Comment by xiaopingcs** [comment]
如果没有问题，请关闭这个issue

**Comment by duanfeixiang** [comment]
> 如果没有问题，请关闭这个issue

确实是没用restful 6041端口连接导致的，问题已经解决，非常感谢！
