### ISSUE TITLE
When using the RESTful interface to query data, the rows field returned by the same SQL query will increase

### ISSUE THREAD

**Issue by jonathanwx** [taosdata/TDengine#4018]
使用rest接口查询数据时，使用相同sql查询返回rows字段会产生递增
![image](https://user-images.githubusercontent.com/6824364/97291293-b5d02980-1884-11eb-981f-4a6186ddceb5.png)
![image](https://user-images.githubusercontent.com/6824364/97291336-c1235500-1884-11eb-8724-c105aa62cad2.png)

**Comment by xiaopingcs** [comment]
你表里面的数据不会增加，一直都是只有2条数据么？

**Comment by jonathanwx** [comment]
表里边就两条数据，工具用的postman
比如用count聚类查询，第一次rows是1，快速点击send，rows就变成了2，第三次变成了3，实际只有一条数据
又比如用正常的select 表里边就两条数据，查询出来第一次rows是2，快速点击send，第二次就是4
rows实际返回结果是 **点击次数*实际记录数**

另外如果查询之间有5秒的间隔的话rows返回正常。tdengine的版本是2.0.5.1

**Comment by jonathanwx** [comment]
> 你表里面的数据不会增加，一直都是只有2条数据么？

表里边就两条数据，工具用的postman
比如用count聚类查询，第一次rows是1，快速点击send，rows就变成了2，第三次变成了3，实际只有一条数据
又比如用正常的select 表里边就两条数据，查询出来第一次rows是2，快速点击send，第二次就是4
rows实际返回结果是 点击次数*实际记录数

另外如果查询之间有5秒的间隔的话rows返回正常。tdengine的版本是2.0.5.1

**Comment by xiaopingcs** [comment]
> > 你表里面的数据不会增加，一直都是只有2条数据么？
> 
> 表里边就两条数据，工具用的postman
> 比如用count聚类查询，第一次rows是1，快速点击send，rows就变成了2，第三次变成了3，实际只有一条数据
> 又比如用正常的select 表里边就两条数据，查询出来第一次rows是2，快速点击send，第二次就是4
> rows实际返回结果是 点击次数*实际记录数
> 
> 另外如果查询之间有5秒的间隔的话rows返回正常。tdengine的版本是2.0.5.1

谢谢反馈，我这边在Postman里面可以看到同样的问题，可能是个bug，我让我们团队的人看看

**Comment by xiaopingcs** [comment]
你好，这个应该不是bug。请看我们的文档：https://www.taosdata.com/cn/documentation/connector/#RESTful-Connector。我们必要的header参数只有Authorization这一个，其他的header参数可以说都是非必要的。在Postman 里的header里面自动添加了很多非必要的header，如果你取消Connection这个header这个选项就可以得到正确的结果，rows不会再增加。
请确认，如果没有问题的话可以把这个issue 关闭掉

**Comment by codering** [comment]
没看懂，为什么header会影响结果。。。这说不通吧！

**Comment by jonathanwx** [comment]
> 你好，这个应该不是bug。请看我们的文档：[https://www.taosdata.com/cn/documentation/connector/#RESTful-Connector。我们必要的header参数只有Authorization这一个，其他的header参数可以说都是非必要的。在Postman](https://www.taosdata.com/cn/documentation/connector/#RESTful-Connector%E3%80%82%E6%88%91%E4%BB%AC%E5%BF%85%E8%A6%81%E7%9A%84header%E5%8F%82%E6%95%B0%E5%8F%AA%E6%9C%89Authorization%E8%BF%99%E4%B8%80%E4%B8%AA%EF%BC%8C%E5%85%B6%E4%BB%96%E7%9A%84header%E5%8F%82%E6%95%B0%E5%8F%AF%E4%BB%A5%E8%AF%B4%E9%83%BD%E6%98%AF%E9%9D%9E%E5%BF%85%E8%A6%81%E7%9A%84%E3%80%82%E5%9C%A8Postman) 里的header里面自动添加了很多非必要的header，如果你取消Connection这个header这个选项就可以得到正确的结果，rows不会再增加。
> 请确认，如果没有问题的话可以把这个issue 关闭掉

嗯 去掉其他的正常了
