### ISSUE TITLE
about jdbc connector

### ISSUE THREAD

**Issue by XPHLXiaoMingChuan** [taosdata/TDengine#4027]
public TDengineUtil(String url, String username, String password, boolean databaseColumnHumpToLine) throws ClassNotFoundException, SQLException
    {
        Class.forName("com.taosdata.jdbc.TSDBDriver");
        String jdbcUrl = url;
        Properties connProps = new Properties();
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_USER, username);
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_PASSWORD, password);
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_CONFIG_DIR, "/etc/taos");
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_CHARSET, "UTF-8");
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_LOCALE, "en_US.UTF-8");
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_TIME_ZONE, "UTC-8");
        this.connection = DriverManager.getConnection(jdbcUrl, connProps);
        this.databaseColumnHumpToLine = databaseColumnHumpToLine;
    }

 public static void main(String[] args) throws Exception
    {
        TDengineUtil util = new TDengineUtil("jdbc:TAOS://xxxxxxx:6035/tsdb","root","taosdata",true);

        System.out.println(util.getList("select * from  m_5f696abc82c677d3ac8b16f1",IotReceiptUploadDataEntity.class));
    }

运行时总是返回TDengine Error: Authentication failure

**Comment by XPHLXiaoMingChuan** [comment]
数据库和客户端都是2.0.4.0版本的，在客户端上可以访问

**Comment by xiaopingcs** [comment]
端口改成6030试试？

**Comment by zyyang-taosdata** [comment]
默认的端口是6030，参考新的开发文档。https://www.taosdata.com/cn/documentation20/connector-java/

**Comment by XPHLXiaoMingChuan** [comment]
好的，感谢

**Comment by zyyang-taosdata** [comment]
> 好的，感谢

windows环境下jdbc开发的话，参考一下这个文档吧：
https://github.com/taosdata/TDengine/blob/develop/tests/examples/JDBC/JDBCDemo/README-jdbc-windows.md
