### ISSUE TITLE
Can TD provide a tool for data structure import and export?

### ISSUE THREAD

**Issue by shuanger051** [taosdata/TDengine#4036]
@jtao1735 陶总好，我是杭州一家物联网公司的CTO，目前我们公司（TOB模式）已经开始在客户生产环境启用TDEngine，预计年后会大规模推广，目前已经在UAT环境检测。但是目前我们面临一个问题。我们在给客户部署TD时，里面的建表语句属于产品化的，例如A客户使用的表结构和B客户使用的表结构都是一样的，不同的只是两个客户的物联数据。目前TDEngine的建表语句我们都是记录在文档里然后再一条条的向客户环境进行执行，这个工作对于我们的实施人员而言非常的不便。贵司能否提供一个支持SQL导入导出的工具客户端，方便我们做产品化部署。感谢涛思，祝贵司越来越好。

**Comment by Aries-Lee1991** [comment]
您好，您这种情况，请通过邮件联系我们这边的支持人员：support@taosdata.com。

**Comment by arielyang** [comment]
This issue was closed because it has been inactive for too many days.
