### ISSUE TITLE
grafana could not set variables 

### ISSUE THREAD

**Issue by yinfi** [taosdata/TDengine#4037]
**Bug Description**
在grafana中无法设置变量数据。

**To Reproduce**
1.创建一个grafana看板
2.设置granfna变量
3.设置过程中报如下错误：
![image](https://user-images.githubusercontent.com/3062749/97516396-fd160180-19cd-11eb-9574-4c54dbc60e02.png)

**Expected Behavior**
能够设置变量数据

**Comment by liuyq-617** [comment]
Not supported yet
