### ISSUE TITLE
how to use ‘group by’

### ISSUE THREAD

**Issue by wodejavazuihao29** [taosdata/TDengine#4038]
请问下，group by 语句后面的column有啥限制吗？
![QQ截图20201029103208](https://user-images.githubusercontent.com/34804831/97518610-8cbdaf00-19d2-11eb-8a88-8f627c795cbe.png)
后来，我又新建了一个测试表，还是不行，帮忙看一下
![req](https://user-images.githubusercontent.com/34804831/97520653-b4af1180-19d6-11eb-940c-c22abaa7926e.png)

**Comment by hjxilinx** [comment]
plan_id 列的类型是什么？

**Comment by wodejavazuihao29** [comment]
nchar(32)

**Comment by wodejavazuihao29** [comment]
一开始以为是字段长度的问题，我又新建了一个测试表还是不行，帮忙看一下

![444](https://user-images.githubusercontent.com/34804831/97520498-57b35b80-19d6-11eb-8bf2-4284a05d9436.png)

**Comment by wodejavazuihao29** [comment]
![req](https://user-images.githubusercontent.com/34804831/97520561-7dd8fb80-19d6-11eb-8eec-83e962932e49.png)

**Comment by wodejavazuihao29** [comment]
刚才搜索其它lssues，发现也有这个问题，不知道这个group by 是bug吗

**Comment by wodejavazuihao29** [comment]
目前使用的单机版2.0.4

**Comment by codering** [comment]
我遇到过，改成binary类型就可以。不包含中文得还是用binary吧，虽然官方说可以用nchar排序，但我没成功过。

**Comment by wodejavazuihao29** [comment]
> 我遇到过，改成binary类型就可以。不包含中文得还是用binary吧，虽然官方说可以用nchar排序，但我没成功过。

可以了，谢谢
