### ISSUE TITLE
high memory consumption

### ISSUE THREAD

**Issue by xujiesh0510** [taosdata/TDengine#4047]
docker 版本 2.0.6.0
整个库只有几MB 大小。超级表聚合再 按分钟降采样，内存占用比较高，一次查询几百MB. 同一个sql查询一次内存涨一次。
涨到2GB 多一点，就不涨了。稍有些不同查询的并发量，内存就不够了。

sql:
select VariableName as 'Metric', Min(Val) as Val   from   db.svariables   where  tenantId =1697  AND Ts >= '2020-10-28 16:00:00' and Ts <= '2020-10-29 15:59:59'  interval(1m)  group by  VariableName  ; 

相关文件已经发送给了  houjiangyi 。

**Comment by xujiesh0510** [comment]
沟通后，虽然说标签比较大，但是   内存占用比较高，一次查询几百MB，无法释放。

**Comment by yihaoDeng** [comment]
有这样的机制， 不过具体问题得具体分析，你的问题我稍后问下houjiangyi

**Comment by xujiesh0510** [comment]
另外测了下2.0.4 版本 占用内存会降到 900多MB 的时候不再上涨，似乎内存管理表现的好些
