### ISSUE TITLE
Error in `taos': free(): invalid next size (normal)

### ISSUE THREAD

**Issue by yaobo-lab** [taosdata/TDengine#4054]
数据库版本：version: 2.0.6.0

建表语句：
`CREATE TABLE t_sub_msg (ts timestamp, topic NCHAR(64), qos TINYINT, payload BINARY(5000)) TAGS(productId NCHAR(32), deviceId NCHAR(32));`

插入内容语句：
`INSERT INTO d9170386 USING t_sub_msg TAGS ("1774", "9170386") VALUES (1604022505482,'123','0','123123123 \n  _/home/wind/Project/go-lib/lib/_obj/_cgo_gotypes.go:50 +0xa4\nviceID\":\"9170386\",\"message
\":\"2020-10-29 16:52:06.718[DEBUG][IOTReporter.cpp:416] iot info : {\\\"status\\\":0,\\\"cmd\\\":\\\"request_client_res_list\\\",\\\"msg\\\":\\\"\\\",\\\"seqno\\\":\\\"7227\\\",\\\"data\\\":{\\\"res_no_list
\\\":null}}\",\"productSubType\":\"4\",\"productType\":\"177\",\"timestamp\":1603961536,\"type\":\"info\"}\n{\"appno\":\"aamUpdateService\",\"frmDeviceID\":\"9170386\",\"message\":\"2020-10-29 16:52:09.759[I
NFO][IOTReporter.cpp:187] request resNolist info\",\"productSubType\":\"4\",\"productType\":\"177\",\"timestamp\":1603961536,\"type\":\"info\"}\n{\"appno\":\"aamUpdateService\",\"frmDeviceID\":\"9170386\",\"
message\":\"2020-10-29 16:52:09.759[INFO][IOTReporter.cpp:235] iot write success: {\\\"cmd\\\":\\\"request_client_res_list\\\",\\\"seqno\\\":\\\"7228\\\"}\",\"productSubType\":\"4\",\"productType\":\"177\",\
"timestamp\":1603961536,\"type\":\"info\"}\n{\"appno\":\"aamUpdateService\",\"frmDeviceID\":\"9170386\",\"message\":\"\",\"productSubType\":\"4\",\"productType\":\"177\",\"timestamp\":1603961536,\"type\":\"i
nfo\"}\n{\"appno\":\"aamUpdateService\",\"frmDeviceID\":\"9170386\",\"message\":\"2020-10-29 16:52:09.760[DEBUG][IOTReporter.cpp:416] iot info : {\\\"status\\\":0,\\\"cmd\\\":\\\"request_client_res_list\\\",
\\\"msg\\\":\\\"\\\",\\\"seqno\\\":\\\"7228\\\",\\\"data\\\":{\\\"res_no_list\\\":null}}\",\"productSubType\":\"4\",\"productType\":\"177\",\"timestamp\":1603961536,\"type\":\"info\"}\n{\"appno\":\"aamUpdate
Service\",\"frmDeviceID\":\"9170386\",\"message\":\"2020-10-29 16:52:10.554[INFO][ProcessorDaemon.cpp:111] line:send signal 0 to process\",\"productSubType\":\"4\",\"productType\":\"177\",\"timestamp\":16039
61536,\"type\":\"info\"}\n{\"appno\":\"aamUpdateService\",\"frmDeviceID\":\"9170386\",\"message\":\"2020-10-29 16:52:12.806[INFO][IOTReporter.cpp:187] request resNolist info\",\"productSubType\":\"4\",\"prod
uctType\":\"177\",\"timestamp\":1603961536,\"type\":\"info\"}\n{\"appno\":\"aamUpdateService\",\"frmDeviceID\":\"9170386\",\"message\":\"2020-10-29 16:52:12.806[INFO][IOTReporter.cpp:235] iot write success: 
{\\\"cmd\\\":\\\"request_client_rermDeviceID\":\"9170386\",\"message\":\"2020-10-29 16:52:06.718[DEBUG][IOTReporter.cpp:416] iot info : {\\\"status\\\":0,\\\"cmd\\\":\\\"request_client_res_list\\\",\\\"msg\\
\":\\\"\\\",\\\"seqno\\\":\\\"7227\\\",\\\"data\\\":{\\\"res_no_list\\\":null}}\",\"productSubType\":\"4\",\"productType\":\"177\",\"timestamp\":1603961536,\"type\":\"info\"}\n{\"appno\":\"aamUpdateService\"
,\"frmDeviceID\":\"9170386\",\"message\":\"2020-10-29 16:52:09.759[INFO][IOTReporter.cpp:187] request resNolist info\",\"productSubType\":\"4\",\"productType\":\"177\",\"timestamp\":1603961536,\"type\":\"inf
o\"}\n{\"appno\":\"aamUpdateService\",\"frmDeviceID\":\"9170386\", OTReporter.cpp:187] request resNolist info\",\"productSubType\":\"4\",\"productType\":\"177\",\"timestamp\":1603961536,\"type\":\"info\"}\n{
\"appno\":\"aamUpdateService\",\"frmDeviceID\":\"9170386\",\"message\":\"2020-10-29 16:52:09.759[INFO][IOTReporter.cpp:235] iot write success: {\\\"cmd\\\":\\\"request_client_res_list\\\",\\\"seqno\\\":\\\"7
228\\\"}\",\"productSubType\":\"4\",\"productType\":\"177\",\"timestamp\":1603961536,\"type\":\"info\"}\n{\"appno\":\"aamUpdateService\",\"frmDeviceID\":\"9170386\",\"message\":\"\",\"productSubType\":\"4\",
\"productType\":\"177\",\"timestamp\":1603961536,\"type\":\"info\"}\n{\"appno\":\"aamUpdateService\",\"frmDeviceID\":\"9170386\",\"message\":\"2020-10-29 16:52:09.760[DEBUG][IOTReporter.cpp:416] iot info : {
\\\"status\\\":0,\\\"cmd\\\":\\\"request_client_res_list\\\",\\\"msg\\\":\\\"\\\",\\\"seqno\\\":\\\"7228\\\",\\\"data\\\":{\\\"res_no_list\\\":null}}\",\"productSubType\":\"4\",\"productType\":\"177\",\"time
stamp\":1603961536,\"type\":\"info\"}\n{\"appno\":\"aamUpdateService\",\"frmDeviceID\":\"9170386\",\"message\":\"2020-10-29 16:52:10.554[INFO][ProcessorDaemon.cpp:111] line:send signal 0 to process\",\"produ
ctSubType\":\"4\",\"productType\":\"177\",\"timestamp\":1603961536,\"type\":\"info\"}\n{\"appno\":\"aamUpdateService\",\"frmDeviceID\":\"9170386\",\"message\":\"2020-10-29 16:52:12.806 \"seqno\\\":\\\"7228\\
\",\\\"data\\\":{\\\"res_no_list\\\":null}}\",\"productSubType\":\"4\",\"productType\":\"177\",\"timestamp\":1603961536,\"type\":\"info\"}\n{\"appno\":\"aamUpdateService\",\"frmDeviceID\":\"9170386\",\"messa
ge\":\"2020-10-29 16:52:10.554[INFO][ProcessorDaemon.cpp:111] line:send signal 0 to process\",\"productSubType\":\"4\",\"productType\":\"177\",\"timestamp\":1603961536,\"type\":\"info\"}\n{\"appno\":\"aamUpd
ateService\",\"frmDeviceID\":\"9170386\",\"message\":\"2020-10-29 16:52:12.806[INFO][IOTReporter.cpp:187] request resNolist info\",\"productSubType\":\"4\",\"productType\":\"177\",\"timestamp\":1603961536,\"
type\":\"info\"}\n{\"appno\":\"aamUpdateService\",\"frmDeviceID\":\"9170386\",\"message\":\"2020-10-29 16:52:12.806[INFO][IOTReporter.cpp:235] iot write success: {\\\"cmd\\\":\\\"request_client_re');`

直接运行插入语句。出错：
`*** Error in taos: free(): invalid next size (normal): 0x00007fdca4010760 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81299)[0x7fdccb64c299]
/lib64/libtaos.so.1(+0x47253)[0x7fdccbbfc253]
/lib64/libtaos.so.1(tsParseInsertSql+0x66e)[0x7fdccbbfdbd6]
/lib64/libtaos.so.1(tsParseSql+0x19e)[0x7fdccbbfe63c]
/lib64/libtaos.so.1(tscTableMetaCallBack+0x53b)[0x7fdccbc37762]
/lib64/libtaos.so.1(tscProcessMsgFromServer+0xa27)[0x7fdccbc39258]
/lib64/libtaos.so.1(+0x105c4f)[0x7fdccbcbac4f]
/lib64/libtaos.so.1(+0x10607e)[0x7fdccbcbb07e]
/lib64/libtaos.so.1(+0x105b35)[0x7fdccbcbab35]
/lib64/libtaos.so.1(+0x1097e3)[0x7fdccbcbe7e3]
/lib64/libpthread.so.0(+0x7ea5)[0x7fdccb9a0ea5]
/lib64/libc.so.6(clone+0x6d)[0x7fdccb6c98dd]`

**Comment by yihaoDeng** [comment]
这确实是个BUG， 我们已经修复提交到develop 分支， 如果你着急， 直接从develop编译，如果不着急， 等我们下周的发版

**Comment by sangshuduo** [comment]
2.0.7.0 版本已修复。
