### ISSUE TITLE
C++连接器两个麻烦问题

### ISSUE THREAD

**Issue by airx** [taosdata/TDengine#4058]
1、调用taos_query处理的sql，当sql有问题的时候，也不返回null，这样都不方便知道到sql有没有问题。
2、当把taosdb关闭了的时候，taos_query处理的sql也不返回错误，这样不方便我们进行异常监控。

**Comment by yihaoDeng** [comment]
pSql = taos_query(con, qstr); int32_t code = taos_errno(pSql); 可以通过这个获取错误err code, 并通过taos_errno(con)获取对应的err msg

**Comment by airx** [comment]
那这样岂不是每次调用都要去提取错误码，不提直观与否，这样有效率问题吗？

**Comment by yihaoDeng** [comment]
错误码保存在当前结构体中

**Comment by sangshuduo** [comment]
Not a bug. Close it.
