### ISSUE TITLE
failed to connect to server in the centos7

### ISSUE THREAD

**Issue by qb-yunwei** [taosdata/TDengine#406]
[root@localhost ~]# taos

Welcome to the TDengine shell, client version:1.6.1.7  
TSDB error: failed to connect to server
本地访问taos 提示连接超时

**Comment by hzcheng** [comment]
shell和客户端在同一台机器上吗？

**Comment by hzcheng** [comment]
您的server在运行着是吗？这个是刚一装好就出现的还是运行了一段时间后出现的？

**Comment by sangshuduo** [comment]
no update, close it.
