### ISSUE TITLE
It's too slow to query data in taos

### ISSUE THREAD

**Issue by qb-yunwei** [taosdata/TDengine#407]
taos> select count(*) from devicelog;
      count(*)       |
======================
              3531557|
Query OK, 1 row(s) in set (88.348063s)

taos> select count(*) from  devicelog;
      count(*)       |
======================
             19019173|
Query OK, 1 row(s) in set (169.768086s)

**Comment by hzcheng** [comment]
请问您的数据时间跨度很大吗？数据特点大概是什么样的？

**Comment by sangshuduo** [comment]
no update, close.
