### ISSUE TITLE
java Springboot program reports: Unable to resolve FQDN

### ISSUE THREAD

**Issue by lordtang** [taosdata/TDengine#4070]
**Bug Description**
环境如下:在Azure的Ubuntu虚拟机上安装了TDengine v2.0.6
创建数据库log
在win10上运行springbootdemo,程序启动正常spring.datasource.url=jdbc:TAOS://node1:6030/log
使用tao.exe -h 主机ip能正常访问，能ping通
![image](https://user-images.githubusercontent.com/35823484/97823891-54311480-1cf5-11eb-9752-733d3ad98dd2.png)

已经正确配置了FQDN Springboot程序报错:Unable to resolve FQDN
![image](https://user-images.githubusercontent.com/35823484/97823761-da992680-1cf4-11eb-9a24-66143edad0a0.png)
驱动版本分别尝试了2.0.4/2.0.6/2.0.8,均失败
![image](https://user-images.githubusercontent.com/35823484/97823929-7460d380-1cf5-11eb-912f-e239d55b9487.png)

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 14.0 LST]
- Driver :2.0.8/2.0.4/2.0.6
 - TDengine Version 2.0.6

**Additional Context**

**Comment by ll10020163** [comment]
虚拟机上我的也不好用，只有服务器可以使用。

**Comment by sangshuduo** [comment]
taos.exe -h node1 可以吗？

**Comment by lordtang** [comment]
> taos.exe -h node1 可以吗？

感谢回复!
执行taos.exe -h node1可以连上，但是执行查询就会报错 Unable to resolve FQDN
![image](https://user-images.githubusercontent.com/35823484/97835163-82721c80-1d14-11eb-8e63-a9ead0e4807f.png)

**Comment by lordtang** [comment]
> 虚拟机上我的也不好用，只有服务器可以使用。

你好!你测试过服务器可以但是虚拟机不行吗？你用的服务器和客户端的版本是多少？

**Comment by sangshuduo** [comment]
请参考 #3836

**Comment by lordtang** [comment]
> 请参考 #3836

按照#3836执行了，删除了lib/taos文件夹下的所有文件；
重启了taod服务，也尝试重启了虚拟机
 Unable to resolve FQDN错误仍然存在；
服务端执行show dnodes的结果如下图:
![image](https://user-images.githubusercontent.com/35823484/97847404-84df7100-1d2a-11eb-86e3-5cc53667a0ec.png)

**Comment by sangshuduo** [comment]
你在 Windows 端启动 taos.exe 指定的 FQDN 是 show dnodes 看到的吗？你在Windows 上能 ping 通这个 FQDN吗？

**Comment by lordtang** [comment]
解决步骤如下:
1.安装TDTengine(V2.0.6)时提示输入节点，输入node1:3306
2.修改/etc/taos/taos.cfg,如下图所示
![image](https://user-images.githubusercontent.com/35823484/97859307-6635a600-1d3b-11eb-98fb-ffd1ac6bcf83.png)

3.修改开发的电脑的host文件，C:\Windows\System32\drivers\etc\host修改
![image](https://user-images.githubusercontent.com/35823484/97859807-13102300-1d3c-11eb-988b-08cb1c46d5e1.png)

完成上面的步骤重启服务，重新连接即可
并非TDengine的bug,但是对于没有配置FQDN的经验的同学来说难免有些门槛；希望TDengine能完善文档
