### ISSUE TITLE
docker stop and start again, prompt: taos connect failed, reason: Unable to establish connection.

### ISSUE THREAD

**Issue by 419845351** [taosdata/TDengine#4074]
**Bug Description**
docker容器stop之后再次启动，提示：taos connect failed, reason: Unable to establish connection.

**To Reproduce**
1. 在两台服务器上使用docker搭建了tdengine
2. docker容器stop之后，再次启动容器，执行taos命令，提示：taos connect failed, reason: Unable to establish connection.
3. 查看docker日志如下：

11/02 06:43:36.747515 0x7efc9bfff700 DND ERROR status rsp is received, error:Unable to establish connection
11/02 06:43:36.878771 0x7efc9bfff700 RPC WARN DND-C 0x7efca1f4d300 (nil), too many redirects, quit
11/02 06:43:36.878813 0x7efc817f5700 DND ERROR user:monitor, auth msg received from mnodes, error:Unable to establish connection
11/02 06:43:37.087362 0x7efc82ff8700 MON ERROR failed to connect to database, reason:Unable to establish connection
11/02 06:43:37.752464 0x7efc9bfff700 RPC WARN DND-C 0x7efca1f4d300 (nil), too many redirects, quit
11/02 06:43:37.752492 0x7efc9bfff700 DND mnode EP list for peer is changed, numOfEps:2 inUse:1
11/02 06:43:37.752503 0x7efc9bfff700 DND mnode index:0 192.168.155.46:6030
11/02 06:43:37.752523 0x7efc9bfff700 DND mnode index:1 192.168.155.44:6030
11/02 06:43:37.752537 0x7efc9bfff700 DND ERROR status rsp is received, error:Unable to establish connection
11/02 06:43:37.883792 0x7efc9bfff700 RPC WARN DND-C 0x7efca1f4d300 (nil), too many redirects, quit
11/02 06:43:37.883833 0x7efc817f5700 DND ERROR user:monitor, auth msg received from mnodes, error:Unable to establish connection
11/02 06:43:38.090595 0x7efc9bfff700 RPC WARN DND-C 0x7efca1f4d300 (nil), too many redirects, quit
11/02 06:43:38.090633 0x7efc817f5700 DND ERROR user:monitor, auth msg received from mnodes, error:Unable to establish connection
11/02 06:43:38.757363 0x7efc9bfff700 RPC WARN DND-C 0x7efca1f4d300 (nil), too many redirects, quit
11/02 06:43:38.757390 0x7efc9bfff700 DND mnode EP list for peer is changed, numOfEps:2 inUse:1
11/02 06:43:38.757402 0x7efc9bfff700 DND mnode index:0 192.168.155.46:6030
11/02 06:43:38.757421 0x7efc9bfff700 DND mnode index:1 192.168.155.44:6030
11/02 06:43:38.757432 0x7efc9bfff700 DND ERROR status rsp is received, error:Unable to establish connection
11/02 06:43:39.092412 0x7efc9bfff700 RPC WARN DND-C 0x7efca1f4d300 (nil), too many redirects, quit
11/02 06:43:39.092450 0x7efc817f5700 DND ERROR user:monitor, auth msg received from mnodes, error:Unable to establish connection
11/02 06:43:39.764188 0x7efc9bfff700 RPC WARN DND-C 0x7efca1f4d300 (nil), too many redirects, quit
11/02 06:43:39.764213 0x7efc9bfff700 DND mnode EP list for peer is changed, numOfEps:2 inUse:1
11/02 06:43:39.764224 0x7efc9bfff700 DND mnode index:0 192.168.155.46:6030
11/02 06:43:39.764233 0x7efc9bfff700 DND mnode index:1 192.168.155.44:6030
11/02 06:43:39.764245 0x7efc9bfff700 DND ERROR status rsp is received, error:Unable to establish connection
11/02 06:43:40.097781 0x7efc9bfff700 RPC WARN DND-C 0x7efca1f4d300 (nil), too many redirects, quit
11/02 06:43:40.097823 0x7efc817f5700 DND ERROR user:monitor, auth msg received from mnodes, error:Unable to establish connection
11/02 06:43:40.767482 0x7efc9bfff700 RPC WARN DND-C 0x7efca1f4d300 (nil), too many redirects, quit
11/02 06:43:40.767507 0x7efc9bfff700 DND mnode EP list for peer is changed, numOfEps:2 inUse:1
11/02 06:43:40.767518 0x7efc9bfff700 DND mnode index:0 192.168.155.46:6030
11/02 06:43:40.767527 0x7efc9bfff700 DND mnode index:1 192.168.155.44:6030
11/02 06:43:40.767545 0x7efc9bfff700 DND ERROR status rsp is received, error:Unable to establish connection
11/02 06:43:41.102518 0x7efc9bfff700 RPC WARN DND-C 0x7efca1f4d300 (nil), too many redirects, quit
11/02 06:43:41.102642 0x7efc817f5700 DND ERROR user:monitor, auth msg received from mnodes, error:Unable to establish connection
11/02 06:43:41.772438 0x7efc9bfff700 RPC WARN DND-C 0x7efca1f4d300 (nil), too many redirects, quit
11/02 06:43:41.772491 0x7efc9bfff700 DND mnode EP list for peer is changed, numOfEps:2 inUse:1
11/02 06:43:41.772510 0x7efc9bfff700 DND mnode index:0 192.168.155.46:6030
11/02 06:43:41.772520 0x7efc9bfff700 DND mnode index:1 192.168.155.44:6030
11/02 06:43:41.772530 0x7efc9bfff700 DND ERROR status rsp is received, error:Unable to establish connection

4. docker启动命令如下：
docker run --name tdengine2.0.6.0 -d -e TZ=Asia/Shanghai -v /etc/taos/taos.cfg:/etc/taos/taos.cfg -v /etc/taos/data:/var/lib/taos -v /etc/taos/log:/var/log/taos -p 6030:6030 -p 6035:6035 -p 6041:6041 -p 6030-6040:6030-6040/udp -h node01 192.168.155.100:8082/tdengine:v2.0.6.0 
镜像启动的时候没有此问题

5. 使用的docker镜像版本为2.0.6.0

**Comment by sangshuduo** [comment]
两台服务器上用 Docker 跑集群吗？

**Comment by 419845351** [comment]
是的，我下载了TDengine-arbitrator-2.0.6.0-linux-x64.tar文件，并且安装到了服务器上。

**Comment by 419845351** [comment]
taos.cfg是如下配置的：
# first fully qualified domain name (FQDN) for TDengine system
# taosd启动时，主动连接的集群中第一个dnode的end point, 默认值为localhost:6030。
firstEp               192.168.155.46:6030

# second fully qualified domain name (FQDN) for TDengine system, for cluster only
# taosd启动时，如果first连接不上，尝试连接集群中第二个dnode的end point, 默认值为空。
secondEp              192.168.155.44:6030

           
# 必须配置为本数据节点的FQDN，如果本机只有一个hostname, 可注释掉本配置
fqdn                  192.168.155.46


# 配置本数据节点的端口号，缺省是6030
serverPort            6030


# 服务端节点数为偶数的时候，需要配置，请参考《Arbitrator的使用》的部分
arbitrator            192.168.155.46:6042

**Comment by 419845351** [comment]
我把映射出来的文件删除掉，就可以正常启动。
那我历史数据怎么保存呢？删除或者停容器之后，怎么再导入历史数据呢？

**Comment by sangshuduo** [comment]
可以用 docker volume 来持久化数据

**Comment by 419845351** [comment]
ok，谢谢。
还是那个问题，如果映射出来的/etc/taos/data下数据不为空，容器启动就会报错，这个怎么解决呢？

**Comment by sangshuduo** [comment]
怀疑是新的 docker 里的 fqdn 变了导致的，可以去启动 docker 的时候用 --hostname 指定 hostname，包括把 /etc 目录也用 volume 的方式管理起来，保证每次启动 hostname, hosts, taos.cfg 等文件内容都不变，就可以了。你可以参考一下其他已经解决的 issue

**Comment by 419845351** [comment]
docker run --name tdengine2.0.6.0 -d -e TZ=Asia/Shanghai  **-v /etc/taos/taos.cfg:/etc/taos/taos.cfg -v /etc/taos/data:/var/lib/taos -v /etc/taos/log:/var/log/taos** -p 6030:6030 -p 6035:6035 -p 6041:6041 -p 6030-6040:6030-6040/udp **-h node01** 192.168.155.100:8082/tdengine:v2.0.6.0 
您说的这些，我启动命令里应该都有，那我再去找一找其他的issue吧，谢谢。

**Comment by 419845351** [comment]
你好，我这个问题依然存在，在其他issue中没找到解决方法。
tdengine在docker上运行一段时间后，**删除容器**后再次执行docker run，会提示:
11/10 03:55:04.714606 0x7fe2e0b8c700 RPC WARN DND-C 0x7fe2e2447300 (nil), too many redirects, quit
11/10 03:55:04.714636 0x7fe2e0b8c700 DND mnode EP list for peer is changed, numOfEps:2 inUse:1
11/10 03:55:04.714646 0x7fe2e0b8c700 DND mnode index:0 192.168.155.46:6030
11/10 03:55:04.714656 0x7fe2e0b8c700 DND mnode index:1 192.168.155.44:6030
11/10 03:55:04.714675 0x7fe2e0b8c700 DND ERROR status rsp is received, error:Unable to establish connection
11/10 03:55:05.205339 0x7fe2e0b8c700 RPC WARN DND-C 0x7fe2e2447300 (nil), too many redirects, quit
11/10 03:55:05.205404 0x7fe2d2527700 DND ERROR user:monitor, auth msg received from mnodes, error:Unable to establish connection


启动命令如下：
docker run --name tdengine2.0.6.0 -d -e TZ=Asia/Shanghai -v /etc/localtime:/etc/localtime -v /etc/timezone:/etc/timezone  -v /etc/taos/taos.cfg:/etc/taos/taos.cfg -v /etc/taos/data:/var/lib/taos -v /etc/taos/log:/var/log/taos -p 6030:6030 -p 6035:6035 -p 6041:6041 -p 6030-6040:6030-6040/udp --hostname node01 192.168.155.100:8082/tdengine:v2.0.6.0 
我已经把文件映射出来了，并且指定了hostname 

按照文档检查hostname：
![image](https://user-images.githubusercontent.com/29766247/98626676-3004b180-234d-11eb-87fc-2086b8a4d8c7.png)

**Comment by 419845351** [comment]
我查了一下，发现两个服务器下的/etc/taos/data/mnode/wal/wal0文件不一样。
作为从的那台服务器 wal0文件 是空的。

**Comment by 419845351** [comment]
启动时报错如下：
11/10 07:18:33.946308 0x7ff0329ba280 UTL ==================================
11/10 07:18:33.946317 0x7ff0329ba280 DND start to initialize TDengine on node02:6030
11/10 07:18:33.946557 0x7ff0329ba280 DND storage directory is initialized
11/10 07:18:33.946606 0x7ff0329ba280 DND dnode read is opened, min worker:2 max worker:4
11/10 07:18:33.946631 0x7ff0329ba280 DND dnode write is opened, max worker 2
11/10 07:18:33.947460 0x7ff0329ba280 DND inter-dnodes rpc client is opened
11/10 07:18:33.947819 0x7ff0329ba280 DND inter-dnodes RPC server is opened
11/10 07:18:33.948765 0x7ff0329ba280 DND there are total vnodes:0, openned:0 failed:0
11/10 07:18:33.948781 0x7ff0329ba280 DND dnode mgmt is initialized
11/10 07:18:33.948976 0x7ff0329ba280 DND dnode mgmt timer is initialized
11/10 07:18:33.949289 0x7ff0329ba280 DND shell rpc server is opened
11/10 07:18:33.949384 0x7ff0329ba280 HTP start http server ...
11/10 07:18:33.949480 0x7ff0329ba280 HTP http result queue is opened
11/10 07:18:33.950361 0x7ff0329ba280 MON monitor module start
11/10 07:18:33.950386 0x7ff0329ba280 DND TDengine is initialized successfully
11/10 07:18:33.950628 0x7ff027cfd700 HTP http server init success at 6041
11/10 07:18:44.467778 0x7ff032010700 UTL ERROR failed to get the ip address, fqdn:node01, code:-3, reason:Temporary failure in name resolution
11/10 07:18:44.467812 0x7ff032010700 RPC ERROR DND-C, failed to resolve FQDN:node01
11/10 07:18:44.467926 0x7ff032010700 RPC ERROR DND-C (nil), failed to set up connection(Unable to resolve FQDN)
11/10 07:18:44.472597 0x7ff0307b8700 UTL ERROR failed to get the ip address, fqdn:node01, code:-2, reason:Name or service not known
11/10 07:18:44.472630 0x7ff0307b8700 RPC ERROR DND-C, failed to resolve FQDN:node01
11/10 07:18:44.472641 0x7ff0307b8700 RPC ERROR DND-C (nil), failed to set up connection(Unable to resolve FQDN)
11/10 07:18:44.475717 0x7ff0307b8700 UTL ERROR failed to get the ip address, fqdn:node01, code:-2, reason:Name or service not known
11/10 07:18:44.475740 0x7ff0307b8700 RPC ERROR DND-C, failed to resolve FQDN:node01
11/10 07:18:44.475752 0x7ff0307b8700 RPC ERROR DND-C (nil), failed to set up connection(Unable to resolve FQDN)
11/10 07:18:44.479479 0x7ff0307b8700 UTL ERROR failed to get the ip address, fqdn:node01, code:-2, reason:Name or service not known
11/10 07:18:44.479514 0x7ff0307b8700 RPC ERROR DND-C, failed to resolve FQDN:node01
11/10 07:18:44.479526 0x7ff0307b8700 RPC ERROR DND-C (nil), failed to set up connection(Unable to resolve FQDN)
11/10 07:18:44.482811 0x7ff0307b8700 UTL ERROR failed to get the ip address, fqdn:node01, code:-2, reason:Name or service not known
11/10 07:18:44.482835 0x7ff0307b8700 RPC ERROR DND-C, failed to resolve FQDN:node01
11/10 07:18:44.482846 0x7ff0307b8700 RPC ERROR DND-C (nil), failed to set up connection(Unable to resolve FQDN)
11/10 07:18:44.486400 0x7ff0307b8700 UTL ERROR failed to get the ip address, fqdn:node01, code:-2, reason:Name or service not known
11/10 07:18:44.486429 0x7ff0307b8700 RPC ERROR DND-C, failed to resolve FQDN:node01
11/10 07:18:44.486440 0x7ff0307b8700 RPC ERROR DND-C (nil), failed to set up connection(Unable to resolve FQDN)
11/10 07:18:44.486587 0x7ff0307b8700 RPC WARN DND-C 0x7ff032073188 (nil), too many redirects, quit
11/10 07:18:44.486605 0x7ff0307b8700 DND mnode EP list for peer is changed, numOfEps:2 inUse:1
11/10 07:18:44.486614 0x7ff0307b8700 DND mnode index:0 node01:6030
11/10 07:18:44.486623 0x7ff0307b8700 DND mnode index:1 node02:6030
