### ISSUE TITLE
question about aggregation for time 

### ISSUE THREAD

**Issue by ChuTingxu** [taosdata/TDengine#4075]
场景，需要获得一个超级表内多个字表多条件下一段时间内的所有数据，由于数据过多需要进行稀释，TDegine提供了分隔时间INTERVAL关键字，如果对单个子表利用last函数与时间分隔可以达成获得间隔时间的数据，但是last函数如果对超级表操作，只按时间返回一条数据，不能按照每个子表分别查出数据然后合在一起返回。
请问查询这里有什么解决方案么？达成对超级表多个子表一段时间内多条件间隔时间取值然后返回。

**Comment by sangshuduo** [comment]
group by tbname
