### ISSUE TITLE
alert crash issue

### ISSUE THREAD

**Issue by shuanger051** [taosdata/TDengine#4078]
告警模块的alert组件，2.0.6版本，会经常性的宕机，自动kill进程，目前发现alert模块，能正常运行的时间不超过1小时，有时候几分钟就挂了。有一个条件可以这样操作，在alert模块中添加一个rule，然后再用一个完全一模一样的rule调用更新或新增方法。直接就会宕机。

error 信息 如下：
runtime stack:
runtime.throw(0x9b5c47, 0x2a)
	/home/ubuntu/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/home/ubuntu/go/src/runtime/signal_unix.go:704 +0x4ac

goroutine 192 [syscall]:
runtime.cgocall(0x8d3f80, 0xc000055b10, 0xc000055b40)
	/home/ubuntu/go/src/runtime/cgocall.go:133 +0x5b fp=0xc000055ae0 sp=0xc000055aa8 pc=0x41037b
github.com/taosdata/driver-go/taosSql._Cfunc_taos_close(0x7fde4c2f6920)
	_cgo_gotypes.go:180 +0x45 fp=0xc000055b10 sp=0xc000055ae0 pc=0x81d005
github.com/taosdata/driver-go/taosSql.(*taosConn).taos_close.func1(0xc000077020)
	/home/ubuntu/gopath/pkg/mod/github.com/taosdata/driver-go@v0.0.0-20200727182616-1a3b1941c206/taosSql/taosSqlCgo.go:86 +0x55 fp=0xc000055b48 sp=0xc000055b10 pc=0x823975
github.com/taosdata/driver-go/taosSql.(*taosConn).taos_close(0xc000077020)
	/home/ubuntu/gopath/pkg/mod/github.com/taosdata/driver-go@v0.0.0-20200727182616-1a3b1941c206/taosSql/taosSqlCgo.go:86 +0x2b fp=0xc000055b60 sp=0xc000055b48 pc=0x821ccb
github.com/taosdata/driver-go/taosSql.(*taosConn).Close(0xc000077020, 0x0, 0x0)
	/home/ubuntu/gopath/pkg/mod/github.com/taosdata/driver-go@v0.0.0-20200727182616-1a3b1941c206/taosSql/connection.go:70 +0x31 fp=0xc000055b78 sp=0xc000055b60 pc=0x81d7f1
database/sql.(*driverConn).finalClose.func2()
	/home/ubuntu/go/src/database/sql/sql.go:592 +0x49 fp=0xc000055bb0 sp=0xc000055b78 pc=0x73d389
database/sql.withLock(0xa2eda0, 0xc000212a20, 0xc000055c38)
	/home/ubuntu/go/src/database/sql/sql.go:3284 +0x69 fp=0xc000055be0 sp=0xc000055bb0 pc=0x73cf89
database/sql.(*driverConn).finalClose(0xc000212a20, 0x0, 0xc000055cb8)
	/home/ubuntu/go/src/database/sql/sql.go:590 +0x130 fp=0xc000055c78 sp=0xc000055be0 pc=0x72edb0
database/sql.finalCloser.finalClose-fm(0xc000078000, 0xa2b4a0)
	/home/ubuntu/go/src/database/sql/sql.go:636 +0x2f fp=0xc000055ca0 sp=0xc000055c78 pc=0x73f6cf
database/sql.(*driverConn).Close(0xc000212a20, 0xc000212a20, 0x0)
	/home/ubuntu/go/src/database/sql/sql.go:571 +0x135 fp=0xc000055cf0 sp=0xc000055ca0 pc=0x72ebd5
database/sql.(*DB).putConn(0xc000078000, 0xc000212a20, 0x0, 0x0, 0xa2ed01)
	/home/ubuntu/go/src/database/sql/sql.go:1391 +0x1ef fp=0xc000055d50 sp=0xc000055cf0 pc=0x7330af
database/sql.(*driverConn).releaseConn(...)
	/home/ubuntu/go/src/database/sql/sql.go:475
database/sql.(*driverConn).releaseConn-fm(0x0, 0x0)
	/home/ubuntu/go/src/database/sql/sql.go:474 +0x4b fp=0xc000055d88 sp=0xc000055d50 pc=0x73f74b
database/sql.(*Rows).close(0xc00007f480, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/go/src/database/sql/sql.go:3180 +0x164 fp=0xc000055df0 sp=0xc000055d88 pc=0x73c9a4
database/sql.(*Rows).Close(...)
	/home/ubuntu/go/src/database/sql/sql.go:3151
database/sql.(*Rows).Next(0xc00007f480, 0xc000010168)
	/home/ubuntu/go/src/database/sql/sql.go:2839 +0xb8 fp=0xc000055e50 sp=0xc000055df0 pc=0x73aed8
github.com/taosdata/alert/app.(*Rule).run(0xc00011e680, 0xc000078000)
	/home/ubuntu/ver_release_workspace/TDinternal/community/alert/app/rule.go:369 +0x356 fp=0xc000055f88 sp=0xc000055e50 pc=0x7fb9d6
github.com/taosdata/alert/app.runRules.func1.1(0xc000078000, 0xc00011e680)
	/home/ubuntu/ver_release_workspace/TDinternal/community/alert/app/rule.go:497 +0x7e fp=0xc000055fd0 sp=0xc000055f88 pc=0x7fe53e
runtime.goexit()
	/home/ubuntu/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000055fd8 sp=0xc000055fd0 pc=0x477881
created by github.com/taosdata/alert/app.runRules.func1
	/home/ubuntu/ver_release_workspace/TDinternal/community/alert/app/rule.go:494 +0xb4

goroutine 1 [chan receive]:
main.main()
	/home/ubuntu/ver_release_workspace/TDinternal/community/alert/cmd/alert/main.go:174 +0x39d

goroutine 19 [select]:
database/sql.(*DB).connectionOpener(0xc00009f520, 0xa344e0, 0xc0000ce640)
	/home/ubuntu/go/src/database/sql/sql.go:1126 +0xf5
created by database/sql.OpenDB
	/home/ubuntu/go/src/database/sql/sql.go:740 +0x12a

goroutine 5 [select]:
database/sql.(*DB).connectionOpener(0xc000078000, 0xa344e0, 0xc000066040)
	/home/ubuntu/go/src/database/sql/sql.go:1126 +0xf5
created by database/sql.OpenDB
	/home/ubuntu/go/src/database/sql/sql.go:740 +0x12a

goroutine 30 [select]:
github.com/taosdata/alert/app.runRules()
	/home/ubuntu/ver_release_workspace/TDinternal/community/alert/app/rule.go:480 +0x23f
created by github.com/taosdata/alert/app.initRule
	/home/ubuntu/ver_release_workspace/TDinternal/community/alert/app/rule.go:631 +0x76

goroutine 31 [select]:
github.com/taosdata/alert/app.pushAlerts()
	/home/ubuntu/ver_release_workspace/TDinternal/community/alert/app/rule.go:542 +0x185
created by github.com/taosdata/alert/app.initRule
	/home/ubuntu/ver_release_workspace/TDinternal/community/alert/app/rule.go:632 +0x8e

goroutine 32 [IO wait]:
internal/poll.runtime_pollWait(0x7fde8bdeb110, 0x72, 0x0)
	/home/ubuntu/go/src/runtime/netpoll.go:220 +0x55
internal/poll.(*pollDesc).wait(0xc00007e018, 0x72, 0x0, 0x0, 0x9a48e2)
	/home/ubuntu/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/home/ubuntu/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc00007e000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/go/src/internal/poll/fd_unix.go:394 +0x1fc
net.(*netFD).accept(0xc00007e000, 0xc0000761b0, 0x41ab78, 0xc000044c00)
	/home/ubuntu/go/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc00000e0c0, 0xc000054dc8, 0x41ab78, 0x30)
	/home/ubuntu/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00000e0c0, 0x971a60, 0xc0000761b0, 0x927800, 0xe84fc0)
	/home/ubuntu/go/src/net/tcpsock.go:261 +0x65
net/http.(*Server).Serve(0xc000144000, 0xa33360, 0xc00000e0c0, 0x0, 0x0)
	/home/ubuntu/go/src/net/http/server.go:2937 +0x266
net/http.(*Server).ListenAndServe(0xc000144000, 0x0, 0x0)
	/home/ubuntu/go/src/net/http/server.go:2866 +0xb7
main.serveWeb.func1(0xc000144000)
	/home/ubuntu/ver_release_workspace/TDinternal/community/alert/cmd/alert/main.go:44 +0x2f
created by main.serveWeb
	/home/ubuntu/ver_release_workspace/TDinternal/community/alert/cmd/alert/main.go:43 +0x1a5

goroutine 34 [syscall]:
os/signal.signal_recv(0x0)
	/home/ubuntu/go/src/runtime/sigqueue.go:147 +0x9d
os/signal.loop()
	/home/ubuntu/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/home/ubuntu/go/src/os/signal/signal.go:150 +0x45

**Comment by localvar** [comment]
谢谢反馈，后面我们会处理

**Comment by localvar** [comment]
我们无法重现这个问题，能提供下您的rule和表结构吗？

**Comment by shuanger051** [comment]
超级表：
taos> describe super_device;
             Field              |        Type        |   Length    |    Note    |
=================================================================================
 ts                             | TIMESTAMP     |           8 |            |
 wind_speed             | INT                  |           4 |            |
 temp                       | INT                  |           4 |            |
 test                          | INT                  |           4 |            |
 location                   | NCHAR           |          50 | TAG        |
 owner_name           | NCHAR           |          50 | TAG        |
 ceo                          | NCHAR           |          10 | TAG        |
 house_number        | NCHAR           |          20 | TAG        |

子表：
![image](https://user-images.githubusercontent.com/11718316/98319214-3a584000-201b-11eb-855a-9d11a219eee6.png)

子表数据：
taos> select * from device1001;
           ts            | wind_speed  |    temp     |    test     |
====================================================================
 2020-10-28 11:17:07.036 |           1 |          27 |        NULL |
 2020-10-28 11:17:21.363 |           1 |          27 |        NULL |
 2020-10-28 11:17:22.871 |           1 |          27 |        NULL |
 2020-10-28 11:17:25.412 |           1 |          26 |        NULL |
 2020-10-28 11:17:28.209 |           1 |          25 |        NULL |

规则文件：
{"name": "温度低于24度","sql": "select avg(temp) as avgTemp from platform.device1003 where ts > now - 10s","expr": "avgTemp < 24 ", "period": "10s","for": "0s","labels": { "ruleName": "温度低于24度" },"annotations": {"description":"公司：灵长智能科技有限公司，房间编号：B3135，温度低于24度，请检查是否设置正确","summary": "温度低于24度.","cust_code":"100001"}}
