### ISSUE TITLE
 Time zone and character configuration is error in docker

### ISSUE THREAD

**Issue by jadedrip** [taosdata/TDengine#4083]
**Bug Description**
Docker 启动时提示 
11/03 02:49:48.773068 0x7f0a6f09e280 UTL ERROR Invalid locale:en_US.UTF-8, please set the valid locale in config file
11/03 02:49:48.773408 0x7f0a6f09e280 UTL timezone is set to Asia/Shanghai by config file
11/03 02:49:48.773491 0x7f0a6f09e280 UTL timezone format changed to (Asia, +0000)

日志的时间名下不对

然后不断打印
11/03 02:50:20.603024 0x7f0a647f8700 DND 0x1c4247d7f60, msg:heartbeat will be processed in mread queue
11/03 02:50:20.972614 0x7f0a62ff5700 DND msg:status will be processed in mpeer queue
11/03 02:50:21.392700 0x7f0a63ff7700 DND 0x7f0a34001410, msg:heartbeat will be processed in mread queue
11/03 02:50:21.977584 0x7f0a62ff5700 DND msg:status will be processed in mpeer queue
11/03 02:50:22.107463 0x7f0a637f6700 DND 0x1c4247d7f60, msg:heartbeat will be processed in mread queue

**To Reproduce**
1. 设置 taos.cfg
timezone              Asia/Shanghai (CST, +0800)
locale                en_US.UTF-8
charset               UTF-8

我通过在 docker 启动命令里添加  -v /usr/share/zoneinfo/:/usr/share/zoneinfo/  修复了时区问题，但字符问题无法修复，貌似是 docker 里的 linux 缺少很多文件。

2. 启动 docker
docker run -d -p 6030:6030 -p 6035:6035 -p 6041:6041 -p 6030-6040:6030-6040/udp -v /root/TDengine/etc/:/etc/taos -v /root/TDengine/logs/:/var/log/taos -v /root/TDengine/db:/var/lib/taos -v /usr/share/i18n/:/usr/share/i18n/ -v /usr/share/zoneinfo/:/usr/share/zoneinfo/ tdengine/tdengine

3. See error

**Expected Behavior**
字符和时区正常

**Screenshots**

**Environment (please complete the following information):**
 - OS: CentOS Linux release 7.8.2003
 - Memory, CPU, current Disk Space
 - TDengine Version 2.0.6.0

**Additional Context**

**Comment by sangshuduo** [comment]
不是太理解问题，可以先一步一步来吗？比如只用最少的参数启动 tdengine docker 镜像，然后慢慢加参数看是哪步出的问题

**Comment by jadedrip** [comment]
已经是最少参数了啊，只是设置了 timezone , locale

**Comment by sangshuduo** [comment]
docker run -d tdengine/tdengine 有问题吗？

**Comment by jadedrip** [comment]
可以起来，然后日志里打印这些错误。

**Comment by sangshuduo** [comment]
@jadedrip 可以详细描述一下吗？你是用的什么 Linux 发行版和版本做 host OS？安装的 Docker 是什么版本？Host OS 的 locale 和时区 charset 是什么？然后你用 docker run -d tdengine/tdengine 有什么输出？用 docker exec -it \<container id> bash 进入到容器中里能否用 taos 命令连上 taosd ？cat /var/log/taosdlog.0 看到的内容是什么？

**Comment by sangshuduo** [comment]
@jadedrip 可以详细描述一下吗？你是用的什么 Linux 发行版和版本做 host OS？安装的 Docker 是什么版本？Host OS 的 locale 和时区 charset 是什么？然后你用 docker run -d tdengine/tdengine 有什么输出？用 docker exec -it \<container id> bash 进入到容器中里能否用 taos 命令连上 taosd ？cat /var/log/taosdlog.0 看到的内容是什么？

**Comment by jadedrip** [comment]
[taosdlog.0.txt](https://github.com/taosdata/TDengine/files/5498411/taosdlog.0.txt)

**Comment by jadedrip** [comment]
OS: CentOS Linux release 7.8.2003

**Comment by sangshuduo** [comment]
这是我们 docker 镜像没有设置 locale 导致的，不影响功能。如果你希望添加 locale，可以在 docker 中执行

 apt update

apt install locals

locale-gen en\_US.UTF-8

然后在退出 docker 环境，执行 docker commit 保存修改

**Comment by jadedrip** [comment]
但是这样 docker 不能开箱即用很不爽啊，timezone 和 locals 都会影响日志输出吧，起码我没加映射前时间打印都是错的。docker 里必要的环境还是加下吧。
