### ISSUE TITLE
SpringBoot+TDengine Jdbc运行一段时间后SpringBoot进程异常退出

### ISSUE THREAD

**Issue by IZ-ONE** [taosdata/TDengine#4085]
项目代码在运行了一段时间之后，java项目报以下错误，然后整个项目宕机，taosd未宕机(有时java进程和taos进程都异常退出)

运行环境:
  OS: CentOS Linux release 7.7.1908 (Core)
  Memory: 16G
  TDengine Version :2.0.5

主要异常日志:
---------------  T H R E A D  ---------------

Current thread (0x00007f8b0802e800):  JavaThread "taos connection closer" daemon [_thread_in_native, id=35646, stack(0x00007f8a8f5bd000,0x00007f8a8f6be000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x00000000000002d0

Registers:
RAX=0x0000000000000000, RBX=0x00007f8b2fb5f4e0, RCX=0x00007f8bc9e98ecd, RDX=0x0000000000000a01
RSP=0x00007f8a8f6bc2d0, RBP=0x00007f8a8f6bc320, RSI=0x0000000000000000, RDI=0x0000000000000000
R8 =0x0000000000000000, R9 =0x656420656c696620, R10=0x00007f8a8f6bbea0, R11=0x00007f8bc9e97b40
R12=0x0000000000000000, R13=0x00007f8b2fb5f4e0, R14=0x00007f8a8f6bc4c8, R15=0x00007f8b0802e800
RIP=0x00007f8bc9e97b41, EFLAGS=0x0000000000010206, CSGSFS=0x0000000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007f8a8f6bc2d0)
0x00007f8a8f6bc2d0:   00007f8b2fb5f4e0 00007f8b2f53096d
0x00007f8a8f6bc2e0:   00007f8aac002890 00007f8aac002ae0
0x00007f8a8f6bc2f0:   00007f8a8f6bc320 0000000000000068
0x00007f8a8f6bc300:   0000000000000001 00007f8a00000000
0x00007f8a8f6bc310:   000000000802e800 28b8f81dca5f2600
0x00007f8a8f6bc320:   00007f8a8f6bc350 00007f8b2f531350
0x00007f8a8f6bc330:   0000000000000000 00007f8aac002ae0
0x00007f8a8f6bc340:   00007f8aac002b50 00007f8aac002ae0
0x00007f8a8f6bc350:   00007f8a8f6bc380 00007f8b2f52b561
0x00007f8a8f6bc360:   00000006c8d92108 00007f8aac002890
0x00007f8a8f6bc370:   000013898f6bc3b0 00007f8aac002890
0x00007f8a8f6bc380:   00007f8a8f6bc3b0 00007f8b2f499cdb
0x00007f8a8f6bc390:   0100000000000000 00007f8aac004030
0x00007f8a8f6bc3a0:   00007f8ab8061f40 00007f8aac002890
0x00007f8a8f6bc3b0:   00007f8a8f6bc3f0 00007f8b2f46721e
0x00007f8a8f6bc3c0:   00000006ce108458 00007f8aac004030
0x00007f8a8f6bc3d0:   00000007c0021c80 00000000d904ad3e
0x00007f8a8f6bc3e0:   00007f8aac004030 00007f8ab8061f40
0x00007f8a8f6bc3f0:   00007f8a8f6bc430 00007f8b2f479c8c
0x00007f8a8f6bc400:   00000006ce108458 00007f8aac004030
0x00007f8a8f6bc410:   00007f8a8f6bc4c8 00007f8b0802e9f8
0x00007f8a8f6bc420:   00007f8bb20547a8 00007f8aac004030
0x00007f8a8f6bc430:   00007f8a8f6bc498 00007f8bb47ac087
0x00007f8a8f6bc440:   00000006ce108408 00007f8bb5e79c74
0x00007f8a8f6bc450:   0000000000000003 00007f8a8f6bc458
0x00007f8a8f6bc460:   0000000000000000 00007f8a8f6bc4c8
0x00007f8a8f6bc470:   00007f8b2fb5fbb0 0000000000000000
0x00007f8a8f6bc480:   00007f8b2fb5f4e0 0000000000000000
0x00007f8a8f6bc490:   00007f8a8f6bc4d0 0000000000000000
0x00007f8a8f6bc4a0:   00007f8bb7303eac 0000000000000000
0x00007f8a8f6bc4b0:   00007f8bb47a7a56 00007f8aac004030
0x00007f8a8f6bc4c0:   000000076f846040 00000006d74f4078 

Instructions: (pc=0x00007f8bc9e97b41)
0x00007f8bc9e97b21:   d1 f7 d9 81 fa 00 f0 ff ff 0f 47 c1 48 81 c4 98
0x00007f8bc9e97b31:   00 00 00 5b 5d c3 b8 03 00 00 00 eb ef 66 90 53
0x00007f8bc9e97b41:   8b 87 d0 02 00 00 48 89 fb 85 c0 0f 8e 8e 00 00
0x00007f8bc9e97b51:   00 e8 f9 31 00 00 8b 83 08 03 00 00 89 c2 83 ca 

Register to memory mapping:

RAX=0x0000000000000000 is an unknown value
RBX={method} {0x00007f8b2fb5f4e0} 'closeConnectionImp' '(J)I' in 'com/taosdata/jdbc/TSDBJNIConnector'
RCX=0x00007f8bc9e98ecd: sem_post+0x3d in /lib64/libpthread.so.0 at 0x00007f8bc9e8b000
RDX=0x0000000000000a01 is an unknown value
RSP=0x00007f8a8f6bc2d0 is pointing into the stack for thread: 0x00007f8b0802e800
RBP=0x00007f8a8f6bc320 is pointing into the stack for thread: 0x00007f8b0802e800
RSI=0x0000000000000000 is an unknown value
RDI=0x0000000000000000 is an unknown value
R8 =0x0000000000000000 is an unknown value
R9 =0x656420656c696620 is an unknown value
R10=0x00007f8a8f6bbea0 is pointing into the stack for thread: 0x00007f8b0802e800
R11=0x00007f8bc9e97b40: pthread_cancel+0 in /lib64/libpthread.so.0 at 0x00007f8bc9e8b000
R12=0x0000000000000000 is an unknown value
R13={method} {0x00007f8b2fb5f4e0} 'closeConnectionImp' '(J)I' in 'com/taosdata/jdbc/TSDBJNIConnector'
R14=0x00007f8a8f6bc4c8 is pointing into the stack for thread: 0x00007f8b0802e800
R15=0x00007f8b0802e800 is a thread

Stack: [0x00007f8a8f5bd000,0x00007f8a8f6be000],  sp=0x00007f8a8f6bc2d0,  free space=1020k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libpthread.so.0+0xcb41]  pthread_cancel+0x1
C  [libtaos.so.2.0.5.0+0x10d350]  taosCleanUpTcpClient+0x65
C  [libtaos.so.2.0.5.0+0x107561]  rpcClose+0x101
C  [libtaos.so.2.0.5.0+0x75cdb]  tscCloseTscObj+0x7f
C  [libtaos.so.2.0.5.0+0x4321e]  taos_close+0x1c7
C  [libtaos.so.2.0.5.0+0x55c8c]  Java_com_taosdata_jdbc_TSDBJNIConnector_closeConnectionImp+0xc5
j  com.taosdata.jdbc.TSDBJNIConnector.closeConnectionImp(J)I+0
J 24337 C1 com.taosdata.jdbc.TSDBJNIConnector.closeConnection()V (55 bytes) @ 0x00007f8bb7303eac [0x00007f8bb7303e20+0x8c]
J 24336 C1 com.taosdata.jdbc.TSDBConnection.close()V (41 bytes) @ 0x00007f8bb51f4b4c [0x00007f8bb51f4980+0x1cc]
J 23448 C1 com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(Ljava/sql/Connection;Ljava/lang/String;)V (110 bytes) @ 0x00007f8bb8693e04 [0x00007f8bb8693280+0xb84]
J 23034 C1 com.zaxxer.hikari.pool.HikariPool$$Lambda$1393.run()V (16 bytes) @ 0x00007f8bb5719a7c [0x00007f8bb5719920+0x15c]
J 23104 C2 java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (225 bytes) @ 0x00007f8bb85268d0 [0x00007f8bb8526760+0x170]
J 22921 C1 java.util.concurrent.ThreadPoolExecutor$Worker.run()V (9 bytes) @ 0x00007f8bb4bf4dc4 [0x00007f8bb4bf4cc0+0x104]
J 22273 C1 java.lang.Thread.run()V (17 bytes) @ 0x00007f8bb7d3c8c4 [0x00007f8bb7d3c780+0x144]
v  ~StubRoutines::call_stub
V  [libjvm.so+0x697a76]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x1056
V  [libjvm.so+0x697f81]  JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*)+0x321
V  [libjvm.so+0x698427]  JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*)+0x47
V  [libjvm.so+0x71789e]  thread_entry(JavaThread*, Thread*)+0x7e
V  [libjvm.so+0xa813f3]  JavaThread::thread_main_inner()+0x103
V  [libjvm.so+0xa8153c]  JavaThread::run()+0x11c
V  [libjvm.so+0x930198]  java_start(Thread*)+0x108
C  [libpthread.so.0+0x7e65]  start_thread+0xc5

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.taosdata.jdbc.TSDBJNIConnector.closeConnectionImp(J)I+0
J 24337 C1 com.taosdata.jdbc.TSDBJNIConnector.closeConnection()V (55 bytes) @ 0x00007f8bb7303eac [0x00007f8bb7303e20+0x8c]
J 24336 C1 com.taosdata.jdbc.TSDBConnection.close()V (41 bytes) @ 0x00007f8bb51f4b4c [0x00007f8bb51f4980+0x1cc]
J 23448 C1 com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(Ljava/sql/Connection;Ljava/lang/String;)V (110 bytes) @ 0x00007f8bb8693e04 [0x00007f8bb8693280+0xb84]
J 23034 C1 com.zaxxer.hikari.pool.HikariPool$$Lambda$1393.run()V (16 bytes) @ 0x00007f8bb5719a7c [0x00007f8bb5719920+0x15c]
J 23104 C2 java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (225 bytes) @ 0x00007f8bb85268d0 [0x00007f8bb8526760+0x170]
J 22921 C1 java.util.concurrent.ThreadPoolExecutor$Worker.run()V (9 bytes) @ 0x00007f8bb4bf4dc4 [0x00007f8bb4bf4cc0+0x104]
J 22273 C1 java.lang.Thread.run()V (17 bytes) @ 0x00007f8bb7d3c8c4 [0x00007f8bb7d3c780+0x144]
v  ~StubRoutines::call_stub`

**Comment by zyyang-taosdata** [comment]
您好，我需要客户端的日志来排查这个问题，客户端的日志的存放目录：C：/TDengine/log（windows）或者/var/log/taos（linux）。请按如下步骤收集报错日志：
1. 清理历史日志，删除或备份日志文件
2. 将配置文件C：/TDengine/cfg/taos.cfg(windows)或者/etc/taos/taos.cfg(linux)中添加debugFlag 135
3. 重新启动应用，并制造报错。
4. 将报错的日志发送给我，zyyang@taosdata.com

**Comment by IZ-ONE** [comment]
附件为微服务进程异常退出时所截取的数据库日志片段及进程异常退出时的日志记录,从操作系统的coredump打印时间来看进程异常退出时间大概是14:26




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taosdata/TDengine"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月3日(星期二) 下午3:02
收件人:&nbsp;"taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送:&nbsp;"😊 "<969053963@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [taosdata/TDengine] SpringBoot+TDengine Jdbc运行一段时间后SpringBoot进程异常退出 (#4085)





 
您好，我需要客户端的日志来排查这个问题，客户端的日志的存放目录：C：/TDengine/log（windows）或者/var/log/taos（linux）。请按如下步骤收集报错日志：
  
清理历史日志，删除或备份日志文件
 
将配置文件C：/TDengine/cfg/taos.cfg(windows)或者/etc/taos/taos.cfg(linux)中添加debugFlag 135
 
重新启动应用，并制造报错。
 
将报错的日志发送给我，zyyang@taosdata.com

**Comment by IZ-ONE** [comment]
附件为进程异常退出前后完整的数据库日志




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taosdata/TDengine"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月3日(星期二) 下午3:02
收件人:&nbsp;"taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送:&nbsp;"😊 "<969053963@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [taosdata/TDengine] SpringBoot+TDengine Jdbc运行一段时间后SpringBoot进程异常退出 (#4085)





 
您好，我需要客户端的日志来排查这个问题，客户端的日志的存放目录：C：/TDengine/log（windows）或者/var/log/taos（linux）。请按如下步骤收集报错日志：
  
清理历史日志，删除或备份日志文件
 
将配置文件C：/TDengine/cfg/taos.cfg(windows)或者/etc/taos/taos.cfg(linux)中添加debugFlag 135
 
重新启动应用，并制造报错。
 
将报错的日志发送给我，zyyang@taosdata.com
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

taosdlog.tgz (362.49M, 2020年12月06日 15:47 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=2463663993516ade6ef4a400476400185006500e03510203485b025b0249060451504b5b5456511a570703585302060655515f0e61683243040c155d0d0b551911041c395c&t=exs_ftn_download&code=ecf9ad27

**Comment by liangyuanpeng** [comment]
将日志直接上传在这个issue会更好，如果其他人遇到类似的问题也可以作为参考

**Comment by IZ-ONE** [comment]
[taosdlog.1.gz](https://github.com/taosdata/TDengine/files/5508745/taosdlog.1.gz)
[Uploading hs_err_pid35733.log…]()

**Comment by sanliang125** [comment]
这个问题是否已经解决了呀？

**Comment by IZ-ONE** [comment]
您好，这边上礼拜经过验证问题暂时未得到有效解决，把版本升级到最新版本(2.0.10)发版本后，两个服务都出现进程异常退出了(一个只对taos进行查询的服务，一个会频繁的进行新增操作)，之前老版本时候只有那个频繁新增的服务会出现异常退出。现在已经把版本暂时回退到2.0.4


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taosdata/TDengine"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月22日(星期天) 晚上9:58
收件人:&nbsp;"taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送:&nbsp;"Tragedy of X"<969053963@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [taosdata/TDengine] SpringBoot+TDengine Jdbc运行一段时间后SpringBoot进程异常退出 (#4085)





 
这个问题是否已经解决了呀？

**Comment by pytao08** [comment]
你好，这个问题有规避方案没？我之前也遇到这个问题

**Comment by IZ-ONE** [comment]
> 你好，这个问题有规避方案没？我之前也遇到这个问题

目前还没解决，还是会时不时无规律性的异常退出

**Comment by duanfeixiang** [comment]
我也遇到这个问题了，一模一样的错误。
这个bug有点致命，直接让java进程崩溃退出了，感觉像一颗定时炸弹一样。不知道官方大佬们什么时候能抽空分析解决一下这个问题。

**Comment by zyyang-taosdata** [comment]
从报错信息看到，这是一个段错误，我建议使用2.0.8.0版本的TDengine，注意，使用2.0.8.0版本需要将taos-jdbcdriver-2.0.12。

**Comment by IZ-ONE** [comment]
如果要升级数据库版本,TDengin有什么迁移数据的解决方案么




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taosdata/TDengine"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月1日(星期二) 下午3:42
收件人:&nbsp;"taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送:&nbsp;"Tragedy of X"<969053963@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [taosdata/TDengine] SpringBoot+TDengine Jdbc运行一段时间后SpringBoot进程异常退出 (#4085)





 
从报错信息看到，这是一个段错误，我建议使用2.0.8.0版本的TDengine，注意，使用2.0.8.0版本需要将taos-jdbcdriver-2.0.12。

**Comment by zyyang-taosdata** [comment]
使用taosdump这个工具可以做数据迁移，请参考：https://www.taosdata.com/blog/2020/03/09/1334.html

**Comment by IZ-ONE** [comment]
之前低版本时迁移数据我使用过taosdump这个工具，迁移到了现在的2.0.5，但是这个版本在bin目录下没发现这个工具了(以前是在bin目录下的)
![Uploading taos.png…]()

**Comment by IZ-ONE** [comment]
之前低版本时迁移数据我使用过taosdump这个工具，迁移到了现在的2.0.5，但是这个版本在bin目录下没发现这个工具了(以前是在bin目录下的)
![taos](https://user-images.githubusercontent.com/49674640/100714490-c8dc9900-33f0-11eb-8203-25236f732449.png)

**Comment by zyyang-taosdata** [comment]
> 之前低版本时迁移数据我使用过taosdump这个工具，迁移到了现在的2.0.5，但是这个版本在bin目录下没发现这个工具了(以前是在bin目录下的)
> ![taos](https://user-images.githubusercontent.com/49674640/100714490-c8dc9900-33f0-11eb-8203-25236f732449.png)

taosdump那个只是依赖libtaos.so，用老版本的taosdump也可以倒数据。在本周日将要发布的版本里面，会有把taosdump打包进去。
