### ISSUE TITLE
How to design the table

### ISSUE THREAD

**Issue by jadedrip** [taosdata/TDengine#4088]
TDengine 貌似没有联表查询和更新数据的操作，我这边有一个需求，部分数据上来存盘以后，过一段时间需要被认领到某个人名下。查询历史记录的时候，还能看到这个数据被谁认领了。

MySql 的话比较简单，我创建个字段 update 下这条数据或者 弄个新表，联表 Left join 查询一下就好了， TDengine 的话，不能 update 这条数据，也不能另外搞张表来 join, 请问应该怎么办？

**Comment by codering** [comment]
我觉得目前该用关系数据库还是得用，tdengine适用场景有限。一个系统原本就不一定只用单一的DB。

**Comment by jadedrip** [comment]
数据表本身会很大，并且是物联网的，挺符合 TDengine 的特性，所以考虑改成 TDengine，但在记录上附加数据的需求难住我了。

**Comment by jadedrip** [comment]
没人知道应该怎么弄吗？

**Comment by codering** [comment]
认领记录相对来说数据量不会大吧？不管怎样，认领记录肯定要存储的。假设这个物联网相关的表为A，认领记录表为B，那B里面肯定会存A的id，从而产生逻辑关联。如果单次查询返回数据量不大，不用join，查询两次是不是也可以接受？

**Comment by jadedrip** [comment]
查出几百几千的 id, 然后再拿这些 id 去查询？貌似龊了点吧。 TDengine 没法实现类似的功能吗？看来不能用它了
