### ISSUE TITLE
table join performance

### ISSUE THREAD

**Issue by xujiesh0510** [taosdata/TDengine#4092]
一模一样的 join 语句，在 命令行执行很快1秒内，但是到restful 接口里面执行很慢，慢到30秒超时。

select  a.ts ,a.val,b.val  from    a  ,   b  where a.ts = b.ts   and a.ts >= '{arg.QueryStartTime:yyyy-MM-dd HH:mm:ss}' and a.ts <= '{arg.QueryEndTime:yyyy-MM-dd HH:mm:ss}'   order by ts asc limit 1;

**Comment by plum-lihui** [comment]
你使用的哪个版本的taosd？ 确认resetful端口是通的么？
请将taosd的配置文件debugflag    135，然后重新启动taosd后，再测试一次，如果还不成功，将taosd的日志发送上来，我们分析一下。
