### ISSUE TITLE
did not support PERCENTILE for stable

### ISSUE THREAD

**Issue by yinfi** [taosdata/TDengine#4097]
**Bug Description**
文档显示支持对超级表使用PERCENTILE，但实际不支持。

**To Reproduce**
1. 执行如下命令：SELECT PERCENTILE(value, 20) FROM openfalcon._load_5min;
2. 报错如下：
![image](https://user-images.githubusercontent.com/3062749/98064864-4fec2f00-1e8e-11eb-9030-1ed88bd0538c.png)
在文档中说明是支持的：
![image](https://user-images.githubusercontent.com/3062749/98064953-66928600-1e8e-11eb-8681-7c7830cabf81.png)

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by xiaopingcs** [comment]
你好，这个是文档的问题，谢谢指正，文档修改已经提交。估计今天晚点会在网站上更新。
如果你要对超级表使用 percentile，可以使用apercentile 这个函数，不过这个函数现在也有点问题，我们正在修复中
