### ISSUE TITLE
建议社区版本先放一个简单的cluster版本

### ISSUE THREAD

**Issue by mckingstar** [taosdata/TDengine#41]
作为大数据平台，最基本的cluster看不到，是很难令人信服的。
加油加油！

**Comment by mislayming** [comment]
顶~

**Comment by zplzpl** [comment]
感觉应该参考elastic的模式，而不是influxdb. 不是想白嫖，而是真正好的东西，不用怕没人买单；elastic的市值说明了一切；

**Comment by zplzpl** [comment]
不得吐槽一下；事实上，来实际用taos我想大部分的普通程序员，但如果有些效果自己都无法印证，根本无法再上推；

**Comment by sangshuduo** [comment]
2.0 版本集群已经开源
