### ISSUE TITLE
After the TDengine cluster stops the first started dnode, the command line cannot be accessed

### ISSUE THREAD

**Issue by lacezeng** [taosdata/TDengine#4100]
1. server端版本: 2.0.0.0
2. 环境: Linux ubuntu18.04
3. 问题描述：
    3.1 三台机器搭建TDengine集群，FQDN分别为form1, form2, form3(form1为第一个启动的节点,form3为最后加入的节点)
    3.2 停掉form3的taosd进程之后，集群能正常访问，show dnodes显示form3状态为offline，其他两个节点为ready;
    3.3 停掉form1之后，集群无法访问
    
![image](https://user-images.githubusercontent.com/71378259/98067283-33eb8c00-1e94-11eb-8519-6769a0ad161f.png)

    3.4 停掉form2之后，集群可以访问，但所有节点都显示offline(该问题目前无法复现，出现过三五次)
    
![image](https://user-images.githubusercontent.com/71378259/98067344-567da500-1e94-11eb-93ec-2cdfbd7cbb02.png)

4. 问题点: 我看博客上说TDengine集群的高可用应该是半数以下节点异常集群仍能保持正常工作，请问上述问题是什么原因？
谢谢～

**Comment by wangyazhou1313** [comment]
3.4 停掉form2之后，集群可以访问，但所有节点都显示offline(该问题目前无法复现，出现过三五次)      是在停掉form1以后停掉form2还是单独停止form2？ 如果form1 和form2都停掉，超过半数结点异常，此时不能正常工作是正常的。

**Comment by jtao1735** [comment]
如果这个问题依然存在，能否把每个节点taos.cfg里debugFlag设置为143，然后重新来做一遍，把日志贴在这里，我来仔细分析一下
