### ISSUE TITLE
Error in inserting data: Syntax errr in SQL, Unable to establish connection

### ISSUE THREAD

**Issue by zhgqiang** [taosdata/TDengine#4101]
![image](https://user-images.githubusercontent.com/8361981/98071436-7ade7f00-1e9e-11eb-9500-98af21e8afae.png)
![image](https://user-images.githubusercontent.com/8361981/98071443-85991400-1e9e-11eb-8937-543e0b8c6768.png)
![image](https://user-images.githubusercontent.com/8361981/98071461-8f227c00-1e9e-11eb-9ad2-b5c35a1fcd08.png)
1. go程序和rest插入数据都会报Syntax errr in SQL
2. 客户端插入超级表偶尔正常，子表插入是正常的
3. docker部署的数据库版本2.0.4.0
4. go驱动用sql.open  并设置SetMaxIdleConns和SetMaxOpenConns连接池后 报Unable to establish connection

go驱动
	db, err := sql.Open("taosSql", "root:taosdata@/tcp(127.0.0.1:0)/tsdb")
	if err != nil {
		log.Fatalf("Open database error: %s\n", err)
	}

taos server 
![image](https://user-images.githubusercontent.com/8361981/98123219-86589700-1eec-11eb-9904-11aba26e0f13.png)

**Comment by freemine** [comment]
i suffer the same problem.

for the time being, suggest using 'nchar' rather than 'binary'. 'nchar' is stored as unicode (ucs-4le), and it'll be automatically converted to/from local charset where your go app is running.
