### ISSUE TITLE
TDengine2.0.6.0

### ISSUE THREAD

**Issue by wll3241** [taosdata/TDengine#4104]
Hi:
     关于集群安装我有个疑问，我用 rpm 安装 TDengine2.0.6.0 我不清楚什么时候能输入该集群任何一个在线的物理节点的FQDN:端口号(默认6030)；
   因为安装时根本没有地方允许我去输入Enter FQDN信息。
![s](https://user-images.githubusercontent.com/45379836/98084860-6f4b8200-1eb7-11eb-84b6-aec3662583fe.png)

**Comment by wangyazhou1313** [comment]
https://www.taosdata.com/cn/documentation/cluster/

**Comment by wll3241** [comment]
我是安装这个文档安装的 
执行 rpm -iv TDengine-server-2.0.6.0-Linux-x64.rpm 命令后并没有时间去输入FQDN

**Comment by wll3241** [comment]
我用 RESTful 的形式去连接单机(6核6G)的TDengine
我插入10000条数据 耗时  105564ms 
![7BC1A9FC-715C-4af8-A7F2-3FB83DC9BC5C](https://user-images.githubusercontent.com/45379836/98090783-79717e80-1ebf-11eb-966e-12488f70974f.png)
我的代码样例如下：
![C22E1477-F39B-4a8e-A389-5E4C94B23E61](https://user-images.githubusercontent.com/45379836/98090953-b5a4df00-1ebf-11eb-8e1a-c4a30d1f6d96.png)

**Comment by wll3241** [comment]
> 你好，可以查看官方文档里关于集群搭建的这一部分https://www.taosdata.com/cn/documentation/cluster/

我就是看着文档来安装的

**Comment by wxlevel** [comment]
![image](https://user-images.githubusercontent.com/38063110/98192881-e3893280-1f56-11eb-9062-9d4a96c09073.png)
我们按照官方文档一步步来的，反复对照 就只有 这个没有给集群配置域名。
