### ISSUE TITLE
restful error in where clause about binary column, but succeed in the terminal

### ISSUE THREAD

**Issue by spjiang** [taosdata/TDengine#412]
**restful where字符串（BINARY）错误**

projectid BINARY(64)

取消“ projectid='6e1f24875853404fb3d978d740056e65' ” 是可以执行的，

加上就不行了
select count(*) from parking_capture_car.capture_car where capturetime>=NOW-30d and projectid='6e1f24875853404fb3d978d740056e65' INTERVAL(1d) GROUP BY carid

错误报告：
POST http://192.168.200.167:9200/rest/sql` resulted in a `400 Bad Request` response:\n{\"status\":\"error\",\"code\":28,\"desc\":\"invalid SQL\"}

**Comment by spjiang** [comment]
如果是问题，能早点修复吗？下周一要提测了。--

**Comment by hjxilinx** [comment]
请提供一下表的schema。我们尽快修复。谢谢！

**Comment by spjiang** [comment]
create table parking_capture_car.capture_car(
capturetime timestamp,
captureid BINARY(64),
platenumber BINARY(64),
backgroundimage BINARY(180),
image BINARY(180),
createtime INT(10),
inouttype TINYINT,
peoplecode BINARY(64),
parkingid BINARY(64),
cameraname BINARY(64),
cameraip BINARY(64),
latitude BINARY(64),
longitude BINARY(64),
vehicletype INT(10),
vehiclecolor INT(10),
vehiclelogo INT(10),
vehiclesublogo INT(10),
vehiclemodel INT(10),
nonmotortype INT(10),
jacketcolor INT(10),
trouserscolor INT(10),
withglass TINYINT,
agegroup INT(10),
isride TINYINT,
gender TINYINT,
withbag TINYINT,
withthings TINYINT,
withhat TINYINT,
jackettype INT(10),
trouserstype INT(10),
withmask TINYINT,
hairstyle INT(10),
cyclingpersonnumber TINYINT,
platetype TINYINT,
platecolor TINYINT,
cameraid BINARY(64),
channelid BINARY(64),
provincecode BIGINT,
citycode BIGINT,
areacode BIGINT,
projectid BINARY(64)
)
tags(
carid BINARY(64)
);

**Comment by spjiang** [comment]
@hjxilinx 情况怎么样了呢？

**Comment by guanshengliang** [comment]
如有需要企业版或者付费服务支持，可以联系我们商务对接侯江燚，微信号/手机号18937155812。

**Comment by guanshengliang** [comment]
从你的超级表的`schema`来看，`provincecode,citycode,areacode,projectid`作为`tag`更加合理

**Comment by guanshengliang** [comment]
你的问题，我们本地环境未能复现，因此按照如下步骤，以便于我们定位问题
1.到官网下载最新版本安装（目前是1.6.1.7）
2.停止服务
```
sudo systemctl stop taosd
```
3.清空日志
```
rm -rf /var/log/taos/*
```
4.开启全量日志，即修改/etc/taos/taos.cfg，增加一行
```
debugFlag 135
```
5.启动服务
```
sudo systemctl start taosd
```
6.重新开始您的测试
7.将文件夹/var/log/taos/*下的日志文件打包
```
cd /var/log/taos
sudo tar -czvf log.tar.gz *
```
8.将压缩文件上传，以便分析

**Comment by spjiang** [comment]
使用环境docker
目前可以了，
操作流程：
1、开启全量日志，即修改/etc/taos/taos.cfg，增加一行；
2、rm -rf /var/log/taos/*   
3、重启docker tdengine 服务
4、重启docker engine
