### ISSUE TITLE
mnode high avalibility question

### ISSUE THREAD

**Issue by yinfi** [taosdata/TDengine#4126]
mnode一个节点挂掉后，会自动选择新节点作为mnode，满足副本要求吗？ 从目前的实验看是不会的，一个mnode节点挂掉就会导致整个集群不可用

**Comment by sangshuduo** [comment]
请参考： https://www.taosdata.com/cn/documentation/cluster/#mnode%E7%9A%84%E9%AB%98%E5%8F%AF%E7%94%A8%E6%80%A7
