### ISSUE TITLE
每次升级都得同步升级客户端

### ISSUE THREAD

**Issue by weicz1221** [taosdata/TDengine#4139]
taos server每次升级后，对应的客户端都需要同步升级到相同的版本，使用jdbc驱动连接还需要拷贝dll 或者 so文件到系统目录下，非常麻烦，建议：
1、升级小版本，客户端版本适当的做兼容。
2、jdbc驱动把dll文件和so文件打到jar包中，不要手动拷贝

**Comment by liangyuanpeng** [comment]
> 每次升级都得同步升级客户端   

这不是一种友好的做法，期待后续会有改进 :)

**Comment by sangshuduo** [comment]
谢谢建议
