### ISSUE TITLE
Would you provide other data insertion language besides SQL?

### ISSUE THREAD

**Issue by holmescn** [taosdata/TDengine#414]
TDengine 提供的 仿 SQL 入口确实降低了很多学习的成本，但是，我一直有这样一个想法就是：SQL 真的是合适的数据插入方法吗？无论是标准的 MySQL 数据库还是 TDengine 这样的专用数据库，每次插入数据，不但要浪费 “INSERT INTO tablename  (col1, col2, ...) VALUES ...” 这么多，其实完全没用的附加信息，而且还要在客户端费力的对插入数据进行格式化，遇到 BINARY 的数据的时候，还要进行额外的编码工作，浮点数据还要考虑格式化的精度。更要加上指令传输到服务器上的解析、格式校验等一些列的工作。客户端的格式化工作可能会引入缓存区溢出漏洞等问题。

我觉得，提供直接的 insert API，并通过某种二进制序列化协议，比如类似 BSON、msgpack 或者其他更加简化的版本，不但减少了自己格式化 SQL 语句可能带来的一些麻烦，可能也会在服务器处理 ingres 的时候，效率略有提高。

**Comment by hjxilinx** [comment]
非常感谢您的建议，我们会考虑在TD后续的功能中增加对二进制协议的支持。

SQL作为最通用的语言，其简单性和易用性是毫无疑问，系统提供SQL可以极大地降低使用的门槛。并且更多的时候，SQL语句的解析本身并不构成系统的瓶颈。
至于您提到的float的精度问题，SQL中可以通过动态绑定（prepareStatement）以及setFloat/setDouble这类的函数来避免精度损失。
