### ISSUE TITLE
EMQ rule engine write TDengine failed

### ISSUE THREAD

**Issue by su600** [taosdata/TDengine#4145]
EMQ X（Docker）
TDengine（Docker 2.0.6）
已在EMQ中添加TDengine为资源，已创建相应的规则，连接测试成功，EMQ监控中规则均已命中，但是并未成功写入数据
TDengine中报错为：

11/07 03:39:44.592649 0x7f0afed5f700 HTP ERROR context:0x7f0ae44b9190, **fd:26, parser state:10, unexpected char:[ ]20,**
11/07 03:39:44.593227 0x7f0afed5f700 HTP ERROR context:0x7f0ae44b9190, fd:26, parse failed, httpCode:400 parseCode:4398 reason:failed to parse header key,
11/07 03:39:44.593470 0x7f0afed5f700 HTP ERROR context:0x7f0ae44b9190, fd:26, failed to parse, state:10,
11/07 03:39:44.594136 0x7f0afed5f700 HTP ERROR context:0x7f0ae44b9190, fd:26, parse failed, ret:-1 i:145 len:243 buf:POST /rest/sql HTTP/1.1
content-type: application/json
content-length: 65
te: 
host: 192.168.3.29:6041
connection: keep-alive
authorization : Basic cm9vdDp0YW9zZGF0YQ==
INSERT INTO n500t.t VALUES(
  now,436,424,415,408,426,418
)
11/07 03:39:44.594462 0x7f0afed5f700 HTP ERROR context:0x7f0ae44b9190, fd:26, parse failed, ret:-1 code:-2147479250 close connect,
11/07 03:39:44.594886 0x7f0afed5f700 HTP ERROR context:0x7f0ae44b9190, fd:26, code:400, error:failed to parse header key,
11/07 03:39:44.595506 0x7f0afed5f700 HTP ERROR context:0x7f0ae44b9190, is already released, refCount:-1,
11/07 03:39:44.602346 0x7f0afed5f700 HTP ERROR context:0x7f0ae44b9190, is already released, refCount:-1,

![emq_to_tdengine](https://user-images.githubusercontent.com/40174401/98431271-c9825800-20ee-11eb-9c2a-a49b9d48be5e.png)

**请问这是什么问题？如何解决 谢谢**

**Comment by sangshuduo** [comment]
表结构是怎样的？

**Comment by su600** [comment]
@sangshuduo 
表结构如下：
(ts timestamp,real1 int, real2 int, real3 int, real4 int, real5 int, real6 int) 
![image](https://user-images.githubusercontent.com/40174401/98440900-7f24c980-2136-11eb-8991-1e7ead19cb0b.png)

**Comment by sangshuduo** [comment]
貌似 Authorization 后面多了一个空格

**Comment by su600** [comment]
> 貌似 Authorization 后面多了一个空格

这。。。 果然是这样
EMQ添加资源的时候测试连接都是正常的。。。EMQ的小坑

谢谢
