### ISSUE TITLE
failed to flush data to disk, reason:Result set too large to be sorted

### ISSUE THREAD

**Issue by taoruifu** [taosdata/TDengine#4154]
ERROR sub:0x7f74880527d0 failed to flush data to disk, reason:Result set too large to be sorted
11/02 06:36:27.166931 0x7f74aac21740 UTL  version:                2.0.4.0
11/02 06:36:27.166933 0x7f74aac21740 UTL  maxBinaryDisplayWidth:  30
11/02 06:36:27.166934 0x7f74aac21740 UTL  os pageSize:            4096(KB)
11/02 06:36:27.166935 0x7f74aac21740 UTL  os openMax:             1048576
11/02 06:36:27.166937 0x7f74aac21740 UTL  os streamMax:           16
11/02 06:36:27.166938 0x7f74aac21740 UTL  os numOfCores:          48
11/02 06:36:27.166939 0x7f74aac21740 UTL  os totalDisk:           0.000000(GB)
11/02 06:36:27.166941 0x7f74aac21740 UTL  os totalMemory:         257432(MB)
11/02 06:36:27.166944 0x7f74aac21740 UTL  os sysname:             Linux
11/02 06:36:27.166945 0x7f74aac21740 UTL  os nodename:            10-51-135-23
11/02 06:36:27.166946 0x7f74aac21740 UTL  os release:             4.15.0-45-generic
11/02 06:36:27.166947 0x7f74aac21740 UTL  os version:             #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019
11/02 06:36:27.166948 0x7f74aac21740 UTL  os machine:             x86_64
11/02 06:36:27.166952 0x7f74aac21740 UTL ==================================
11/02 06:37:04.788957 0x7f7499d4d700 UTL ERROR cache:tableMeta, key:0x7f7490019f8c, not in cache, retrieved failed, reason: empty cache
11/02 06:42:26.252160 0x7f7499d4d700 UTL ERROR cache:tableMeta, key:0x7f7490019f8c, not in cache, retrieved failed
11/02 07:10:55.458018 0x7f7499d4d700 TSC ERROR 0x7f7490010940 add into queued async res, code:Syntax errr in SQL
11/02 07:11:23.237756 0x7f749ad4f700 TSC ERROR 0x7f74900109d0 sub:0x7f74880527d0 num of OrderedRes is too many, max allowed:100000 , current:100800
11/02 07:11:23.237770 0x7f749ad4f700 TSC ERROR sub:0x7f74880527d0 failed to flush data to disk, reason:Result set too large to be sorted
11/02 07:11:23.237774 0x7f749ad4f700 TSC ERROR 0x7f74900109d0 sub:0x7f74880527d0 retrieve failed,code:Result set too large to be sorted,orderOfSub:2 failed.no more retry,set global code:Result set too large to be sorted
11/02 07:11:23.237777 0x7f749ad4f700 TSC ERROR 0x7f74900109d0 retrieve from 5 vnode(s) completed,code:Result set too large to be sorted.FAILED.
11/02 07:11:52.187749 0x7f7499d4d700 TSC ERROR 0x7f7490010a40 add into queued async res, code:Syntax errr in SQL
11/02 07:11:58.868927 0x7f7499d4d700 TSC ERROR 0x7f7490010a40 add into queued async res, code:Syntax errr in SQL

**Comment by taoruifu** [comment]
增加 vnode有没有缓解效果？存储时不是已经排好序了，为什么要限制OrderedRes数量

**Comment by sangshuduo** [comment]
参考  #3451
