### ISSUE TITLE
使用dump导出报错

### ISSUE THREAD

**Issue by wzf55555** [taosdata/TDengine#4155]
![导出报错](https://user-images.githubusercontent.com/40660395/98492999-68848c80-2274-11eb-8c46-c81b860a7de0.jpg)

**Comment by sangshuduo** [comment]
请提供OS, TDengine 版本信息

**Comment by wzf55555** [comment]
centos7
TDengine: 2.0.5.1

**Comment by sangshuduo** [comment]
taosdump 在 2.0 不再支持了
