### ISSUE TITLE
when using goroutine concurrently for pressure test to access TDengine, taos_connect() fail!

### ISSUE THREAD

**Issue by onionsc** [taosdata/TDengine#4159]
**Bug Description**
尝试添加一个benchmark对TDengine进行压测，当使用多个goroutine并发向TDengine插入数据，一段时间后会出错，提示"taos_connect() fail"，只有出错前的row成功插入。
如果只用一个goroutine一般可以成功插入所有row，但偶尔也会突然发生"段错误（核心已转储）".

日志：
==================================================
     new log file                      
==================================================
11/09 12:17:35.796872 0x7f8b53ffe700 UTL localEp is: ubuntu-18.04.shared:6030
11/08 20:17:35.797159 0x7f8b53ffe700 UTL WARN timezone not configured, set to system default:America/Los_Angeles (PDT, -0700)
11/08 20:17:35.797221 0x7f8b53ffe700 UTL WARN locale not configured, set to system default:zh_CN.UTF-8
11/08 20:17:35.797238 0x7f8b53ffe700 UTL WARN charset not configured, set to system default:UTF-8
11/08 20:17:35.797266 0x7f8b53ffe700 UTL    taos config & system info:
11/08 20:17:35.797277 0x7f8b53ffe700 UTL ==================================
11/08 20:17:35.797279 0x7f8b53ffe700 UTL  firstEp:                ubuntu-18.04.shared:6030 
11/08 20:17:35.797281 0x7f8b53ffe700 UTL  secondEp:               ubuntu-18.04.shared:6030 
11/08 20:17:35.797282 0x7f8b53ffe700 UTL  fqdn:                   ubuntu-18.04.shared 
11/08 20:17:35.797284 0x7f8b53ffe700 UTL  serverPort:             6030 
11/08 20:17:35.797285 0x7f8b53ffe700 UTL  configDir:              /etc/taos 
11/08 20:17:35.797286 0x7f8b53ffe700 UTL  logDir:                 /var/log/taos 
11/08 20:17:35.797287 0x7f8b53ffe700 UTL  scriptDir:              /etc/taos 
11/08 20:17:35.797288 0x7f8b53ffe700 UTL  arbitrator:              
11/08 20:17:35.797289 0x7f8b53ffe700 UTL  numOfThreadsPerCore:    1.000000 
11/08 20:17:35.797304 0x7f8b53ffe700 UTL  rpcTimer:               1000(ms)
11/08 20:17:35.797307 0x7f8b53ffe700 UTL  rpcMaxTime:             600(s)
11/08 20:17:35.797308 0x7f8b53ffe700 UTL  shellActivityTimer:     3(s)
11/08 20:17:35.797310 0x7f8b53ffe700 UTL  tableMetaKeepTimer:     7200(s)
11/08 20:17:35.797312 0x7f8b53ffe700 UTL  compressMsgSize:        -1 
11/08 20:17:35.797313 0x7f8b53ffe700 UTL  maxSQLLength:           65480(byte)
11/08 20:17:35.797314 0x7f8b53ffe700 UTL  maxNumOfOrderedRes:     100000 
11/08 20:17:35.797315 0x7f8b53ffe700 UTL  timezone:               America/Los_Angeles (PDT, -0700) 
11/08 20:17:35.797316 0x7f8b53ffe700 UTL  locale:                 zh_CN.UTF-8 
11/08 20:17:35.797317 0x7f8b53ffe700 UTL  charset:                UTF-8 
11/08 20:17:35.797318 0x7f8b53ffe700 UTL  numOfLogLines:          10000000 
11/08 20:17:35.797320 0x7f8b53ffe700 UTL  logKeepDays:            0 
11/08 20:17:35.797321 0x7f8b53ffe700 UTL  asyncLog:               1 
11/08 20:17:35.797322 0x7f8b53ffe700 UTL  debugFlag:              0 
11/08 20:17:35.797323 0x7f8b53ffe700 UTL  rpcDebugFlag:           131 
11/08 20:17:35.797324 0x7f8b53ffe700 UTL  tmrDebugFlag:           131 
11/08 20:17:35.797325 0x7f8b53ffe700 UTL  cDebugFlag:             131 
11/08 20:17:35.797326 0x7f8b53ffe700 UTL  jniDebugFlag:           131 
11/08 20:17:35.797327 0x7f8b53ffe700 UTL  odbcDebugFlag:          131 
11/08 20:17:35.797328 0x7f8b53ffe700 UTL  uDebugFlag:             131 
11/08 20:17:35.797329 0x7f8b53ffe700 UTL  qDebugFlag:             131 
11/08 20:17:35.797330 0x7f8b53ffe700 UTL  tsdbDebugFlag:          131 
11/08 20:17:35.797331 0x7f8b53ffe700 UTL  gitinfo:                community 
11/08 20:17:35.797333 0x7f8b53ffe700 UTL  gitinfoOfInternal:      internal 
11/08 20:17:35.797334 0x7f8b53ffe700 UTL  buildinfo:              Built at 2020-11-05 18:56:44 
11/08 20:17:35.797335 0x7f8b53ffe700 UTL  version:                2.0.5.1 
11/08 20:17:35.797336 0x7f8b53ffe700 UTL  maxBinaryDisplayWidth:  30 
11/08 20:17:35.797338 0x7f8b53ffe700 UTL  os pageSize:            4096(KB)
11/08 20:17:35.797339 0x7f8b53ffe700 UTL  os openMax:             65535
11/08 20:17:35.797340 0x7f8b53ffe700 UTL  os streamMax:           16
11/08 20:17:35.797341 0x7f8b53ffe700 UTL  os numOfCores:          4
11/08 20:17:35.797342 0x7f8b53ffe700 UTL  os totalDisk:           0.000000(GB)
11/08 20:17:35.797343 0x7f8b53ffe700 UTL  os totalMemory:         3939(MB)
11/08 20:17:35.797346 0x7f8b53ffe700 UTL  os sysname:             Linux
11/08 20:17:35.797347 0x7f8b53ffe700 UTL  os nodename:            ubuntu-18.04.shared
11/08 20:17:35.797348 0x7f8b53ffe700 UTL  os release:             4.15.0-122-generic
11/08 20:17:35.797349 0x7f8b53ffe700 UTL  os version:             #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020
11/08 20:17:35.797350 0x7f8b53ffe700 UTL  os machine:             x86_64
11/08 20:17:35.797353 0x7f8b53ffe700 UTL ==================================
11/08 20:17:46.487031 0x7f8b6bffe700 RPC ERROR TSC, failed to call epoll_ctl(Bad file descriptor)
11/08 20:17:47.513856 0x7f8a6ffff700 RPC ERROR TSC, failed to call epoll_ctl(Bad file descriptor)
11/08 20:17:48.073181 0x7f8b53ffe700 RPC ERROR TSC, failed to call epoll_ctl(Bad file descriptor)
11/08 20:17:49.131143 0x7f8b832f0700 RPC ERROR TSC, failed to call epoll_ctl(Bad file descriptor)
11/08 20:17:49.432812 0x7f8a5fffe700 TMR ERROR TSC too many timer controllers, failed to create timer controller.
11/08 20:17:49.433031 0x7f8a5fffe700 RPC ERROR TSC failed to init timers
11/08 20:17:49.433134 0x7f8a5fffe700 TSC ERROR failed to init connection to TDengine

有时候日志中还有个别 RPC ERROR TSC, failed to call epoll_ctl(Invalid argument)这样的错误和大量 RPC ERROR TSC, failed to call epoll_ctl(Bad file descriptor)

**Environment :**
 - OS: ubuntu 18.04.5
 - TDengine Version 2.0.5.1

**Additional Context**
使用cgo，利用提供的C API连接TDengine和执行语句.
服务端和客户端版本都是2.0.5.1
使用的测试有1个super table，每个表400列，tag有1列，1000张表，数据有300W行

**Comment by sangshuduo** [comment]
请问服务器硬件配置是怎样的？并发数多少？能否分享相关代码？

**Comment by sangshuduo** [comment]
请问服务器硬件配置是怎样的？并发数多少？能否分享相关代码？

**Comment by sangshuduo** [comment]
请问服务器硬件配置是怎样的？并发数多少？能否分享相关代码？

**Comment by onionsc** [comment]
> 请问服务器硬件配置是怎样的？并发数多少？能否分享相关代码？

目前还没有在服务器上跑，只是在Ubuntu虚拟机上简单试了下，4G内存。

![1604922417183](https://user-images.githubusercontent.com/43346703/98537515-58949900-22c4-11eb-9509-83d7e5fbe9d9.jpg)

代码是基于https://github.com/timescale/tsbs.git这个项目，开启goroutine的部分是所有DB公共的，所以没有改动过。生成和加载TDengine数据是参考https://github.com/liu0x54/timeseriesdatabase-comparisons.git，两个项目加载数据的逻辑相似，都是scan扫描数据，开启并发在函数processBatch中创建连接，执行，defer关闭连接。
看日志信息本来以为是最大打开文件数不够，从1024改成65355也没用。跑的时候用top观察CPU能达到200%以上

**Comment by sangshuduo** [comment]
totalDisk: 0.000000(GB)

是磁盘空间都用光了？

**Comment by onionsc** [comment]
> totalDisk: 0.000000(GB)
> 
> 是磁盘空间都用光了？

没有，磁盘空间还剩很多

**Comment by onionsc** [comment]
试了一下相同的数据用TDengine1.6.4.4版本跑就没有问题

**Comment by sangshuduo** [comment]
@onionsc 应该是用和 https://github.com/liu0x54/timeseriesdatabase-comparisons/blob/master/go.mod 相同的 driver-go 版本连接到适应 1.6 TDengine 的驱动。你试试改成：

<table><tbody><tr><td>github.com/taosdata/driver-go develop</td></tr></tbody></table>

**Comment by onionsc** [comment]
> @onionsc 应该是用和 https://github.com/liu0x54/timeseriesdatabase-comparisons/blob/master/go.mod 相同的 driver-go 版本连接到适应 1.6 TDengine 的驱动。你试试改成：
> 
> github.com/taosdata/driver-go develop

已经试过，还是没用

**Comment by sangshuduo** [comment]
@onionsc 有 core 文件吗？能否用 gdb taosd core 然后 bt 看一下最后的 call stack？

**Comment by sangshuduo** [comment]
没有更多信息，暂时关闭。如果有更多信息我们再看

**Comment by renyujie518** [comment]
我也遇到相似的问题，我感觉是协程泄露的问题，不知您是否解决该问题，可否分享下解决方案，非常感谢

**Comment by onionsc** [comment]
> 我也遇到相似的问题，我感觉是协程泄露的问题，不知您是否解决该问题，可否分享下解决方案，非常感谢

现在是暂时改成了使用http的方式发送数据

**Comment by xiangxud** [comment]
协程并发访问的确问题多，我也毫无头绪
