### ISSUE TITLE
DB error: Unable to establish connection

### ISSUE THREAD

**Issue by yuhuafeng1109** [taosdata/TDengine#4165]
windows客户端执行sql报错，连接异常？ 

![image](https://user-images.githubusercontent.com/74179157/98522339-87544480-22af-11eb-8c8c-94f2e3dad234.png)

![image](https://user-images.githubusercontent.com/74179157/98522365-90451600-22af-11eb-828d-368b36d3a9cf.png)

在服务器端创建成功了demo库和t表，并插入了两条数据。但是客户端查询失败：DB error: Unable to establish connection。

有朋友遇到过吗，按照官方说明也设置了hostname 。

**Comment by sangshuduo** [comment]
参考 #3715 #3250

**Comment by yuhuafeng1109** [comment]
已解决，谢谢！ @sangshuduo
