### ISSUE TITLE
扩大了maxSQLLength之后，仍然提示TDengine Error: Invalid SQL statement，是maxSQLLength没有生效吗？

### ISSUE THREAD

**Issue by quchunhui** [taosdata/TDengine#4169]
在验证单列模式下批量写入数据，所以sql语句很长，尝试将maxSQLLength扩大了10本，由原来的65480调整到654800，
执行sql插入报错如下
![image](https://user-images.githubusercontent.com/18110478/98626930-da7cd480-234d-11eb-8ba6-f4d7c3bbd73a.png)

如果将SQL语句调整的短一些，就没有问题，所以感觉maxSQLLength这个参数的调整并没有生效，能否帮忙看一下呢？

**Comment by zzandyc** [comment]
1.将maxSQLLength前的"#"号去掉
2.systemctl restart taosd
试试

**Comment by zyyang-taosdata** [comment]
maxSQLLength在client端生效，所以，请确保在您的客户端配置文件/etc/taos/taos.cfg（linux系统）或者C:\\TDengine\etc\taos.cfg（windows系统）中配置了maxSQLLength。这个参数不需要在server端修改和重启server。

**Comment by quchunhui** [comment]
已解决
