### ISSUE TITLE
will you develop a Mac OS version?

### ISSUE THREAD

**Issue by liuxin95** [taosdata/TDengine#417]
**Is your feature request related to a problem? Please describe.**
出于好奇clone工程到mac os里，准备撸一把代码。发现不支持mac os
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:78 (MESSAGE):
  The current platform is not Linux or Windows, stop compile

-- Configuring incomplete, errors occurred!
See also "/Users/liuxin/Project/c/TDengine/cmake-build-debug/CMakeFiles/CMakeOutput.log".

[Finished]

**Describe your desired behavior**
不考虑支持一下mac os的吗？

**Comment by fangpanpan** [comment]
已经有贡献者在开发了, TDengine团队会在9月初启动这项工作,但我们也会根据自身的研发能力按照优先级对各种需求进行排序。

**Comment by fangpanpan** [comment]
Some contributors are developing this. Our group also plans to launch this but we will need to schedule multiple developments according to their priority.
