### ISSUE TITLE
Unable to establish connection occasionally appears during the writing in batches

### ISSUE THREAD

**Issue by quchunhui** [taosdata/TDengine#4175]
**Bug Description**
在做批量写入性能测试的时候，写入过程中出现Unable to establish connection

**To Reproduce**
暂时不清楚100%再现方式

**Expected Behavior**
1、测试样例程序地址：https://github.com/quchunhui/java-demo/blob/master/tdengine/src/main/java/com/rexel/tdengine/api/InsertBatch.java
2、是采用的单列模型，批量写入，自动创建子表的方式

**Screenshots**
![image](https://user-images.githubusercontent.com/18110478/98673643-9a8c1080-2392-11eb-87bd-608e5c5dc3a8.png)

**Environment (please complete the following information):**
 - OS: Linux Centos 8
 - Memory, CPU, current Disk Space：8核16G内存，100GB磁盘
 - TDengine Version [e.g. 1.6.1.7]：2.0.7.0

**Additional Context**
错误日志：
java.sql.SQLException: TDengine Error: Unable to establish connection
	at com.taosdata.jdbc.TSDBJNIConnector.executeQuery(TSDBJNIConnector.java:135)
	at com.taosdata.jdbc.TSDBStatement.executeUpdate(TSDBStatement.java:98)
	at com.rexel.tdengine.api.InsertBatch.batchInsert(InsertBatch.java:86)
	at com.rexel.tdengine.api.InsertBatch.main(InsertBatch.java:65)

**Comment by lzqdename** [comment]
我也碰到了这个，就是压测过程中发现了各种不稳定问题

**Comment by quchunhui** [comment]
关闭，新版本中未能复现问题。
