### ISSUE TITLE
The retention policy of the database does not take effect

### ISSUE THREAD

**Issue by MorganArthur** [taosdata/TDengine#4198]
1）我测试创建了一个keep 1的数据库
taos> CREATE DATABASE demo_1 keep 1 days 1 blocks 4;
Query OK, 0 row(s) affected (0.006000s)

2）之后再建超级表、普通表
taos> CREATE TABLE classroom (ts timestamp, classroom_name nchar(100), classroom_type nchar(100)) TAGS (school_name nchar(100), school_id int);
Query OK, 0 row(s) affected (0.007000s)

taos> CREATE TABLE classroom_0 USING classroom TAGS ("郑州大学",1);
Query OK, 0 row(s) affected (0.081000s)

3）然后我向数据库添加了一条数据
taos> insert into classroom_0 values(1605076470819,"物理3班","理科");
Query OK, 1 row(s) affected (0.002000s)
该日期是2020-11-11 14:34:30.819，我是在2020-11-12 14:32左右的是后新增的；
等到2020-11-12 14:35之后我在查该表
taos> select * from demo_1.classroom_0;
 ts | classroom_name | classroom_type |
---- | ----------------- | ------------------
 2020-11-11 14:34:30.819 | ????3?? | ???? |

Query OK, 1 row(s) in set (0.039000s)
数据并没有被删除。

是我哪里设置的不对吗？

**Comment by liuyq-617** [comment]
过期删除的机制是，删除磁盘中过期的数据文件。你的这个数据还未写入到磁盘中，所以没有被删除掉。

**Comment by MorganArthur** [comment]
好的，谢谢。
