### ISSUE TITLE
“alloc vnode failed, free vnodes:0” and “more dnodes are needed” Error: can't create tables after 63000 tables were created.

### ISSUE THREAD

**Issue by 1075482900** [taosdata/TDengine#420]
客户端显示：failed to create table, reason:more dnodes are needed
服务端显示：08/24 18:09:09.625843 7fd5320b2700 ERROR MND vgroup:0 alloc vnode failed, free vnodes:0

不管是单独创建63000个表，还是使用超级表创建63000个字表，都会出现这个错误，请问是要修改哪个配置才能增加可以创建表的数量吗？我们需要的表的数量至少是百万级的。

**Comment by fangpanpan** [comment]
请问您一个vnode里面建了多少张表 (参数：tables，默认1000)？以及您的服务器是什么配置，多少个核？（一般会建50个vnodes, 从服务端日志里可以看到）还有您能看看你的磁盘空间剩多少吗？

**Comment by 1075482900** [comment]
这里的配置都是用的是tdengine的默认配置，没有改过。
机器8核16G内存，磁盘空间剩余50G（50%）。

这里机器资源应该还不是瓶颈，感觉还是配置的问题，求指点。

**Comment by 1075482900** [comment]
![image](https://user-images.githubusercontent.com/13177557/63645839-e07e9980-c738-11e9-8047-e1fb0b804bea.png)
这个是出错后database的截图

**Comment by fangpanpan** [comment]
> 
> 
> 这里的配置都是用的是tdengine的默认配置，没有改过。
> 机器8核16G内存，磁盘空间剩余50G（50%）。
> 
> 这里机器资源应该还不是瓶颈，感觉还是配置的问题，求指点。

你的机器是8核的，总共会有8*8vnodes, 一个vnode上可以建1000张表，log 用掉一个vnode后，您能用63个vnode,那么最多您可以建63*1000=63000张表。所以您可以根据您的需要更改tables（每个vnode建多少张表）这个参数。语法：create database demo tables [***(默认1000，您根据需要更改）]

**Comment by 1075482900** [comment]
好的  请教下，这个建表数量增加会有什么负面影响吗？  比如如果建表数量很大会爆内存吗？

**Comment by fangpanpan** [comment]
如果表的数量增加，那么占用的内存确实会涨，您还可以修改和内存相关的参数（ablocks, tblocks，参见[https://www.taosdata.com/cn/documentation/administrator/#服务端配置](url)

**Comment by 1075482900** [comment]
如果我把tables参数改的很大且我的表数量无限增加的话，占用的内存也会无限增加吗？

**Comment by 1075482900** [comment]
1. 如果我把tables参数改的很大且我的表数量无限增加的话，占用的内存也会无限增加吗？ 
2. tables这个数值的大小上限是多少呢？

**Comment by hjxilinx** [comment]
table的数量受限于系统可用缓存的大小和内存大小限制，默认每个虚拟节点的最大上限是220000个表。受限于系统缓存数量，每个虚拟节点的缓存块的数量限制是409600个缓存块，所以不调整缓存数量的情况下，每个虚拟节点的表的最大值是102400个。
