### ISSUE TITLE
单机部署时，拷贝/var/lib/taos 后重启失败

### ISSUE THREAD

**Issue by gufeng2016** [taosdata/TDengine#4203]
第一台机器taos,cfg未做任何改动，hostname为tdengine_01，启动后正常运行，给它造了一批数据后，stop它
将 /var/lib/taos 拷贝到机器2，hostname为tdengine_02 ，启动时候报错，报错信息如下

` ERROR failed to get the ip address, fqdn:tdengine_01, code:-2, reason:Name or service not known
tdengine_02 | 11/13 01:03:32.912820 0x7fe77fbff700 RPC ERROR DND-C, failed to resolve FQDN:tdengine_01
tdengine_02 | 11/13 01:03:32.912837 0x7fe77fbff700 RPC ERROR DND-C (nil), failed to set up connection(Unable to resolve FQDN)
tdengine_02 | 11/13 01:03:32.912861 0x7fe77fbff700 DND ERROR status rsp is received, error:Unable to resolve FQDN
tdengine_02 | 11/13 01:03:33.413416 0x7fe77fbff700 UTL ERROR failed to get the ip address, fqdn:tdengine_01, code:-2, reason:Name or service not known
tdengine_02 | 11/13 01:03:33.413460 0x7fe77fbff700 RPC ERROR TSC, failed to resolve FQDN:tdengine_01
tdengine_02 | 11/13 01:03:33.413476 0x7fe77fbff700 RPC ERROR TSC 0x7fe7540c0b10, failed to set up connection(Unable to resolve FQDN)
tdengine_02 | 11/13 01:03:34.058015 0x7fe77fbff700 UTL ERROR failed to get the ip address, fqdn:tdengine_01, code:-2, reason:Name or service not known
tdengine_02 | 11/13 01:03:34.058059 0x7fe77fbff700 RPC ERROR DND-C, failed to resolve FQDN:tdengine_01
tdengine_02 | 11/13 01:03:34.058075 0x7fe77fbff700 RPC ERROR DND-C (nil), failed to set up connection(Unable to resolve FQDN)
tdengine_02 | 11/13 01:03:34.058107 0x7fe77fbff700 DND ERROR status rsp is received, error:Unable to resolve FQDN`

从日志信息看来，像是 /var/lib/taos 里面有记录tdengine_01的信息，只说是tdengine_01找不到

 
![1605230341](https://user-images.githubusercontent.com/24515196/99016074-456a1d80-2591-11eb-8789-c27c35331c71.jpg)

**Comment by guanshengliang** [comment]
这是一个数据迁移的问题。TDengine是根据hostname唯一标志一台机器的，在数据文件从机器A移动机器B时，注意如下两件事：
- 2.0.6及以前的版本，重新配置机器B的hostname为机器A的hostname
- 2.0.7及以后的版本，到/var/lib/taos/dnode下，修复dnodeEps.json的dnodeId对应的FQDN，重启。确保机器内所有机器的此文件是完全相同的。

**Comment by guanshengliang** [comment]
There is no reply for a long time, and this problem has been located and solved in 2.0.9.0
