### ISSUE TITLE
Three machines, one stopped, Write Action refused

### ISSUE THREAD

**Issue by lzqdename** [taosdata/TDengine#4214]
部署了3台机器
![image](https://user-images.githubusercontent.com/7373911/99052914-c944f980-25d3-11eb-83e7-2e61419aba50.png)

数据库信息，设置备份数为3
![image](https://user-images.githubusercontent.com/7373911/99053647-04472d00-25d4-11eb-8fa6-adbc212d9b7b.png)

写入数据，很好，40万/秒【批量写入】
![image](https://user-images.githubusercontent.com/7373911/99053516-f8f40180-25d3-11eb-813c-fece967573ab.png)

然后手动停掉其中一台(通过那个stop命令)
![image](https://user-images.githubusercontent.com/7373911/99053476-f09bc680-25d3-11eb-9e2e-d44d8fb8b5a9.png)

观察客户端写入【HTTP请求发给剩下的2台】，已经无法写入，请求次数直接降低为0，报错如下：
![image](https://user-images.githubusercontent.com/7373911/99054141-280a7300-25d4-11eb-87f8-a4253bb79696.png)

查看存活的其中1台机器的日志，如下
![image](https://user-images.githubusercontent.com/7373911/99054828-5720e480-25d4-11eb-9690-6099cb26fa22.png)

然后，重启杀死的机器，客户端逐渐可以写入，过程如图
![image](https://user-images.githubusercontent.com/7373911/99054609-496b5f00-25d4-11eb-8c43-9b44cbe52d9e.png)

**Comment by guanshengliang** [comment]
我近期会处理这个问题

**Comment by lzqdename** [comment]
> 我近期会处理这个问题

现在能得出结论是不是bug吗？还是说后面再来分析呢？

**Comment by guanshengliang** [comment]
这几天改了不少关于同步的BUG，下周一之前会发布2.08版本。
你更新之后，如果还有类似问题。可以把配置文件的debugFlag 设置为143，然后截取出错时最近2分钟之内的三台机器的日志，我再仔细分析。

**Comment by lzqdename** [comment]
> 这几天改了不少关于同步的BUG，下周一之前会发布2.08版本。
> 你更新之后，如果还有类似问题。可以把配置文件的debugFlag 设置为143，然后截取出错时最近2分钟之内的三台机器的日志，我再仔细分析。

好的，加油！

**Comment by guanshengliang** [comment]
As of version 2.2, this problem has been alleviated. You can also look forward to the 3.0 version in the second half of the year. The synchronization module has been refactored using the raft algorithm
