### ISSUE TITLE
SQL containing a string "rp" gives an "Invalid SQL" error

### ISSUE THREAD

**Issue by baocj** [taosdata/TDengine#422]
create table  tqjk (ts timestamp, ua float,ub float,uc float,ia float,ib float,ic float,i0 float,ap float ,apa float,apb float,apc float,rp float,rpa float,rpb float,rpc float,pf float,pfa float,pfb float,pfc float,tap float,tap1 float,tap2 float,tap3 float,tap4 float,event int,ta float,tb float,tc float,tn float,te float) tags (zddz int, modbusid int)；

TSDB error: invalid SQL: syntax error near "rp float,rpa float,rpb float,rpc flo
at,pf float,pfa float,pfb float,pfc float,tap float,tap1 float,tap2 float,tap3 f
loat,tap4 float,event int,ta float,tb float,tc float,tn float,te float) tags (zd
dz int, modbusid int);"

把rp改成rp1或者其他可以保存，
create table  tqjk (ts timestamp, ua float,ub float,uc float,ia float,ib float,ic float,i0 float,ap float ,apa float,apb float,apc float,rp1 float,rpa float,rpb float,rpc float,pf float,pfa float,pfb float,pfc float,tap float,tap1 float,tap2 float,tap3 float,tap4 float,event int,ta float,tb float,tc float,tn float,te float) tags (zddz int, modbusid int);

Query OK, 1 row(s) affected (0.003000s)

**Comment by johnnyhou327** [comment]
@baocj "rp" happens to be a reserved key word in TDengine. A full list of the reserved key words are currently not in the online documentation. We will update the key word list and all the error codes/messages in the online docs as soon as we can.
