### ISSUE TITLE
taosdemo执行问题

### ISSUE THREAD

**Issue by QIANGEGEGE** [taosdata/TDengine#4224]
**General Questions**
这边使用 taosdemo 遇到一个问题，具体问题描述如下:
   当执行taosdemo命令后 生成大概1亿数据就停止了。

日志报错是以下信息：

11/14 18:21:37.591996 0x7f8a4340b740 UTL localEp is: td1:6030
11/14 18:21:37.592284 0x7f8a4340b740 UTL WARN timezone not configured, set to system default: (CST, +0800)
11/14 18:21:37.592343 0x7f8a4340b740 UTL WARN locale not configured, set to system default:en_US.UTF-8
11/14 18:21:37.592356 0x7f8a4340b740 UTL WARN charset not configured, set to system default:UTF-8
11/14 18:21:37.592397 0x7f8a4340b740 UTL    taos config & system info:
11/14 18:21:37.592403 0x7f8a4340b740 UTL ==================================
11/14 18:21:37.592406 0x7f8a4340b740 UTL  firstEp:                td1:6030 
11/14 18:21:37.592408 0x7f8a4340b740 UTL  secondEp:               td1:6030 
11/14 18:21:37.592410 0x7f8a4340b740 UTL  fqdn:                   td1 
11/14 18:21:37.592413 0x7f8a4340b740 UTL  serverPort:             6030 
11/14 18:21:37.592415 0x7f8a4340b740 UTL  configDir:              /etc/taos 
11/14 18:21:37.592417 0x7f8a4340b740 UTL  logDir:                 /var/log/taos 
11/14 18:21:37.592420 0x7f8a4340b740 UTL  scriptDir:              /etc/taos 
11/14 18:21:37.592422 0x7f8a4340b740 UTL  arbitrator:              
11/14 18:21:37.592424 0x7f8a4340b740 UTL  numOfThreadsPerCore:    1.000000 
11/14 18:21:37.592444 0x7f8a4340b740 UTL  rpcTimer:               1000(ms)
11/14 18:21:37.592447 0x7f8a4340b740 UTL  rpcMaxTime:             600(s)
11/14 18:21:37.592449 0x7f8a4340b740 UTL  shellActivityTimer:     3(s)
11/14 18:21:37.592452 0x7f8a4340b740 UTL  tableMetaKeepTimer:     7200(s)
11/14 18:21:37.592454 0x7f8a4340b740 UTL  compressMsgSize:        -1 
11/14 18:21:37.592457 0x7f8a4340b740 UTL  maxSQLLength:           65480(byte)
11/14 18:21:37.592459 0x7f8a4340b740 UTL  maxNumOfOrderedRes:     100000 
11/14 18:21:37.592461 0x7f8a4340b740 UTL  timezone:                (CST, +0800) 
11/14 18:21:37.592464 0x7f8a4340b740 UTL  locale:                 en_US.UTF-8 
11/14 18:21:37.592466 0x7f8a4340b740 UTL  charset:                UTF-8 
11/14 18:21:37.592468 0x7f8a4340b740 UTL  numOfLogLines:          10000000 
11/14 18:21:37.592471 0x7f8a4340b740 UTL  logKeepDays:            0 
11/14 18:21:37.592473 0x7f8a4340b740 UTL  asyncLog:               1 
11/14 18:21:37.592475 0x7f8a4340b740 UTL  debugFlag:              0 
11/14 18:21:37.592478 0x7f8a4340b740 UTL  rpcDebugFlag:           131 
11/14 18:21:37.592480 0x7f8a4340b740 UTL  tmrDebugFlag:           131 
11/14 18:21:37.592482 0x7f8a4340b740 UTL  cDebugFlag:             131 
11/14 18:21:37.592484 0x7f8a4340b740 UTL  jniDebugFlag:           131 
11/14 18:21:37.592487 0x7f8a4340b740 UTL  odbcDebugFlag:          131 
11/14 18:21:37.592489 0x7f8a4340b740 UTL  uDebugFlag:             131 
11/14 18:21:37.592491 0x7f8a4340b740 UTL  qDebugFlag:             131 
11/14 18:21:37.592493 0x7f8a4340b740 UTL  tsdbDebugFlag:          131 
11/14 18:21:37.592495 0x7f8a4340b740 UTL  gitinfo:                a511bc421d537450941512cf97d55ab71e4678c4 
11/14 18:21:37.592498 0x7f8a4340b740 UTL  gitinfoOfInternal:      NULL 
11/14 18:21:37.592500 0x7f8a4340b740 UTL  buildinfo:              Built at 2020-11-10 11:18 
11/14 18:21:37.592503 0x7f8a4340b740 UTL  version:                2.0.7.0 
11/14 18:21:37.592505 0x7f8a4340b740 UTL  maxBinaryDisplayWidth:  30 
11/14 18:21:37.592507 0x7f8a4340b740 UTL  tempDir:                /tmp/ 
11/14 18:21:37.592510 0x7f8a4340b740 UTL  os pageSize:            4096(KB)
11/14 18:21:37.592512 0x7f8a4340b740 UTL  os openMax:             1000000
11/14 18:21:37.592514 0x7f8a4340b740 UTL  os streamMax:           16
11/14 18:21:37.592516 0x7f8a4340b740 UTL  os numOfCores:          2
11/14 18:21:37.592518 0x7f8a4340b740 UTL  os totalDisk:           0.000000(GB)
11/14 18:21:37.592521 0x7f8a4340b740 UTL  os totalMemory:         3789(MB)
11/14 18:21:37.592526 0x7f8a4340b740 UTL  os sysname:             Linux
11/14 18:21:37.592528 0x7f8a4340b740 UTL  os nodename:            td1
11/14 18:21:37.592530 0x7f8a4340b740 UTL  os release:             3.10.0-1062.18.1.el7.x86_64
11/14 18:21:37.592532 0x7f8a4340b740 UTL  os version:             #1 SMP Tue Mar 17 23:49:17 UTC 2020
11/14 18:21:37.592534 0x7f8a4340b740 UTL  os machine:             x86_64
11/14 18:21:37.592544 0x7f8a4340b740 UTL ==================================
11/14 18:22:28.859929 0x7f8a3a5ce700 TSC ERROR 0x7f8a1400d870 get table-meta failed, code:Unable to establish connection
11/14 18:22:28.859967 0x7f8a3a5ce700 TSC ERROR 0x7f8a1400d870 add into queued async res, code:Unable to establish connection
11/14 18:22:30.069073 0x7f8a3a5ce700 TSC WARN 0x7f8a34005960 it shall renew table meta, code:Unable to establish connection, retry:1
11/14 18:22:48.891872 0x7f8a3a5ce700 TSC ERROR 0x7f8a1001aa50 get table-meta failed, code:Unable to establish connection
11/14 18:22:48.891891 0x7f8a3a5ce700 TSC ERROR 0x7f8a1001aa50 add into queued async res, code:Unable to establish connection
11/14 18:22:49.896600 0x7f8a3a5ce700 TSC WARN 0x7f8a24016840 it shall renew table meta, code:Unable to establish connection, retry:1
11/14 18:22:50.303822 0x7f8a3a5ce700 TSC ERROR 0x7f89f40074a0 get table-meta failed, code:Unable to establish connection
11/14 18:22:50.303858 0x7f8a3a5ce700 TSC ERROR 0x7f89f40074a0 add into queued async res, code:Unable to establish connection
11/14 18:22:50.914816 0x7f8a3a5ce700 TSC ERROR 0x7f8a28009f80 get table-meta failed, code:Unable to establish connection
11/14 18:22:50.914835 0x7f8a3a5ce700 TSC ERROR 0x7f8a28009f80 add into queued async res, code:Unable to establish connection
11/14 18:22:51.036831 0x7f8a3a5ce700 TSC ERROR 0x7f89f8006a90 get table-meta failed, code:Unable to establish connection
11/14 18:22:51.036850 0x7f8a3a5ce700 TSC ERROR 0x7f89f8006a90 add into queued async res, code:Unable to establish connection
11/14 18:22:51.520641 0x7f8a3a5ce700 TSC WARN 0x7f8a08017d40 it shall renew table meta, code:Unable to establish connection, retry:1

装机环境是
腾讯云  centos 7.6    2g4h

**Comment by QIANGEGEGE** [comment]
单机环境

**Comment by sangshuduo** [comment]
taosdemo的命令行参数是什么？

**Comment by QIANGEGEGE** [comment]
> taosdemo的命令行参数是什么？  你好，没有附加命令。直接就是taosdemo。

**Comment by sangshuduo** [comment]
麻烦在 /etc/taos/taos.cfg 中打开 debugFlag 143 再跑一下，然后请把 /var/log/taos 压缩后发上来

**Comment by sangshuduo** [comment]
@QIANGEGEGE 没有更多信息我先暂时关闭，如果有更新我们再看
