### ISSUE TITLE
armv7-a bus error

### ISSUE THREAD

**Issue by xiaoyanrui** [taosdata/TDengine#4229]
**Bug Description**
I compiled TDengine on Ubuntu16.04 use Cross compiler arm-poky-linux-gnueabi-xxx gcc version 5.3.0 (GCC), run on the IMX6UL(armv7-a, 32bit) chip, taos runs without any problem, but taosd has a bus error

**To Reproduce**
Platform: Linux corecloud 4.1.15-1.2.0+gc95e082 #1 SMP PREEMPT Sun Nov 1 19:31:39 CST 2020 armv7l GNU/Linux
1. copy 'libtaos.so.1' to /lib/, copy 'taos.cfg' and 'taosd' in same directory
2. Type in './taosd -c ./'
3. See bus error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Linux 4.1.15-1.2.0+gc95e082]
 - Memory: 256MB; CPU: 1  ARMv7 Processor rev 5 (v7l); current Disk Space: system remain 30%(60MB), sdcard remain 100%(4GB)
 - TDengine Version: 2.0.6.0

**Additional Context**

11/16 00:22:25.615097 0x76ff4000 DND start to initialize TDengine
11/16 00:22:25.616659 0x76ff4000 DND dnode storage is initialized at /mnt/disk/data/dnode
11/16 00:22:25.617423 0x76ff4000 DND dnode cfg is initialized
11/16 00:22:25.618257 0x76ff4000 DND dnode eps is initialized
11/16 00:22:25.622061 0x76ff4000 UTL localEp is: localhost:6030
11/16 00:22:25.627911 0x76ff4000 UTL ERROR open file:/proc/690/io failed
11/16 00:22:25.628657 0x76ff4000 UTL WARN timezone not configured, set to system default: (UTC, +0000)
11/16 00:22:25.629115 0x76ff4000 UTL WARN locale not configured, set to system default:C
11/16 00:22:25.630248 0x76ff4000 UTL    taos config & system info:
11/16 00:22:25.630701 0x76ff4000 UTL ==================================
11/16 00:22:25.631028 0x76ff4000 UTL  firstEp:                localhost:6030 
11/16 00:22:25.631348 0x76ff4000 UTL  secondEp:               localhost:6030 
11/16 00:22:25.631656 0x76ff4000 UTL  fqdn:                   localhost 
11/16 00:22:25.631950 0x76ff4000 UTL  serverPort:             6030 
11/16 00:22:25.632248 0x76ff4000 UTL  configDir:              ./ 
11/16 00:22:25.632529 0x76ff4000 UTL  logDir:                 /mnt/disk/log 
11/16 00:22:25.632844 0x76ff4000 UTL  scriptDir:              /etc/taos 
11/16 00:22:25.633129 0x76ff4000 UTL  dataDir:                /mnt/disk/data 
11/16 00:22:25.633418 0x76ff4000 UTL  arbitrator:              
11/16 00:22:25.633705 0x76ff4000 UTL  numOfThreadsPerCore:    1.000000 
11/16 00:22:25.634046 0x76ff4000 UTL  numOfCommitThreads:     1 
11/16 00:22:25.634347 0x76ff4000 UTL  ratioOfQueryThreads:    0.500000 
11/16 00:22:25.634683 0x76ff4000 UTL  numOfMnodes:            3 
11/16 00:22:25.634983 0x76ff4000 UTL  vnodeBak:               1 
11/16 00:22:25.635302 0x76ff4000 UTL  telemetryReporting:     1 
11/16 00:22:25.635589 0x76ff4000 UTL  balance:                1 
11/16 00:22:25.635882 0x76ff4000 UTL  balanceInterval:        300 
11/16 00:22:25.636650 0x76ff4000 UTL  role:                   0 
11/16 00:22:25.636974 0x76ff4000 UTL  maxTmrCtrl:             512 
11/16 00:22:25.637289 0x76ff4000 UTL  monitorInterval:        30(s)
11/16 00:22:25.637593 0x76ff4000 UTL  offlineThreshold:       8640000(s)
11/16 00:22:25.637920 0x76ff4000 UTL  rpcTimer:               1000(ms)
11/16 00:22:25.638220 0x76ff4000 UTL  rpcMaxTime:             600(s)
11/16 00:22:25.638508 0x76ff4000 UTL  statusInterval:         1(s)
11/16 00:22:25.638799 0x76ff4000 UTL  shellActivityTimer:     3(s)
11/16 00:22:25.639077 0x76ff4000 UTL  tableMetaKeepTimer:     7200(s)
11/16 00:22:25.639368 0x76ff4000 UTL  minSlidingTime:         10(ms)
11/16 00:22:25.639654 0x76ff4000 UTL  minIntervalTime:        10(ms)
11/16 00:22:25.639937 0x76ff4000 UTL  maxStreamCompDelay:     20000(ms)
11/16 00:22:25.640246 0x76ff4000 UTL  maxFirstStreamCompDelay:10000(ms)
11/16 00:22:25.640537 0x76ff4000 UTL  retryStreamCompDelay:   10(ms)
11/16 00:22:25.640820 0x76ff4000 UTL  streamCompDelayRatio:   0.100000 
11/16 00:22:25.641166 0x76ff4000 UTL  maxVgroupsPerDb:        0 
11/16 00:22:25.641462 0x76ff4000 UTL  maxTablesPerVnode:      1000000 
11/16 00:22:25.641754 0x76ff4000 UTL  minTablesPerVnode:      1000 
11/16 00:22:25.642041 0x76ff4000 UTL  tableIncStepPerVnode:   1000 
11/16 00:22:25.642353 0x76ff4000 UTL  cache:                  16(Mb)
11/16 00:22:25.642643 0x76ff4000 UTL  blocks:                 6 
11/16 00:22:25.642930 0x76ff4000 UTL  days:                   10 
11/16 00:22:25.643213 0x76ff4000 UTL  keep:                   3650 
11/16 00:22:25.643504 0x76ff4000 UTL  minRows:                100 
11/16 00:22:25.643791 0x76ff4000 UTL  maxRows:                4096 
11/16 00:22:25.644070 0x76ff4000 UTL  comp:                   2 
11/16 00:22:25.644352 0x76ff4000 UTL  walLevel:               1 
11/16 00:22:25.644661 0x76ff4000 UTL  fsync:                  3000 
11/16 00:22:25.644946 0x76ff4000 UTL  replica:                1 
11/16 00:22:25.645316 0x76ff4000 UTL  quorum:                 1 
11/16 00:22:25.645619 0x76ff4000 UTL  update:                 0 
11/16 00:22:25.645916 0x76ff4000 UTL  compressMsgSize:        -1 
11/16 00:22:25.646757 0x76ff4000 UTL  maxSQLLength:           65480(byte)
11/16 00:22:25.647121 0x76ff4000 UTL  maxNumOfOrderedRes:     100000 
11/16 00:22:25.647623 0x76ff4000 UTL  queryBufferSize:        -1(byte)
11/16 00:22:25.647955 0x76ff4000 UTL  timezone:                (UTC, +0000) 
11/16 00:22:25.648264 0x76ff4000 UTL  locale:                 C 
11/16 00:22:25.648565 0x76ff4000 UTL  charset:                UTF-8 
11/16 00:22:25.648856 0x76ff4000 UTL  maxShellConns:          5000 
11/16 00:22:25.649149 0x76ff4000 UTL  maxConnections:         5000 
11/16 00:22:25.649436 0x76ff4000 UTL  minimalLogDirGB:        0.100000(GB)
11/16 00:22:25.649788 0x76ff4000 UTL  minimalTmpDirGB:        0.100000(GB)
11/16 00:22:25.650142 0x76ff4000 UTL  minimalDataDirGB:       0.500000(GB)
11/16 00:22:25.650476 0x76ff4000 UTL  mnodeEqualVnodeNum:     4 
11/16 00:22:25.650765 0x76ff4000 UTL  http:                   1 
11/16 00:22:25.651056 0x76ff4000 UTL  mqtt:                   0 
11/16 00:22:25.651346 0x76ff4000 UTL  monitor:                1 
11/16 00:22:25.651632 0x76ff4000 UTL  httpEnableRecordSql:    0 
11/16 00:22:25.651916 0x76ff4000 UTL  telegrafUseFieldNum:    0 
11/16 00:22:25.652217 0x76ff4000 UTL  httpMaxThreads:         2 
11/16 00:22:25.652508 0x76ff4000 UTL  restfulRowLimit:        10240 
11/16 00:22:25.652793 0x76ff4000 UTL  numOfLogLines:          10000000 
11/16 00:22:25.653075 0x76ff4000 UTL  logKeepDays:            0 
11/16 00:22:25.653355 0x76ff4000 UTL  asyncLog:               1 
11/16 00:22:25.653643 0x76ff4000 UTL  debugFlag:              0 
11/16 00:22:25.653923 0x76ff4000 UTL  mDebugFlag:             135 
11/16 00:22:25.654202 0x76ff4000 UTL  dDebugFlag:             135 
11/16 00:22:25.654508 0x76ff4000 UTL  sDebugFlag:             135 
11/16 00:22:25.654789 0x76ff4000 UTL  wDebugFlag:             135 
11/16 00:22:25.655075 0x76ff4000 UTL  sdbDebugFlag:           135 
11/16 00:22:25.655366 0x76ff4000 UTL  rpcDebugFlag:           131 
11/16 00:22:25.655650 0x76ff4000 UTL  tmrDebugFlag:           131 
11/16 00:22:25.656141 0x76ff4000 UTL  cDebugFlag:             131 
11/16 00:22:25.656477 0x76ff4000 UTL  jniDebugFlag:           131 
11/16 00:22:25.656786 0x76ff4000 UTL  odbcDebugFlag:          131 
11/16 00:22:25.657113 0x76ff4000 UTL  uDebugFlag:             131 
11/16 00:22:25.657405 0x76ff4000 UTL  httpDebugFlag:          131 
11/16 00:22:25.657701 0x76ff4000 UTL  mqttDebugFlag:          131 
11/16 00:22:25.657988 0x76ff4000 UTL  monitorDebugFlag:       131 
11/16 00:22:25.658274 0x76ff4000 UTL  qDebugFlag:             131 
11/16 00:22:25.658558 0x76ff4000 UTL  vDebugFlag:             131 
11/16 00:22:25.658835 0x76ff4000 UTL  tsdbDebugFlag:          131 
11/16 00:22:25.659143 0x76ff4000 UTL  cqDebugFlag:            135 
11/16 00:22:25.659438 0x76ff4000 UTL  tscEnableRecordSql:     0 
11/16 00:22:25.659731 0x76ff4000 UTL  enableCoreFile:         0 
11/16 00:22:25.660018 0x76ff4000 UTL  gitinfo:                community 
11/16 00:22:25.660299 0x76ff4000 UTL  gitinfoOfInternal:      internal 
11/16 00:22:25.660578 0x76ff4000 UTL  buildinfo:              Built at 2020-11-16 01:01:35 
11/16 00:22:25.660859 0x76ff4000 UTL  version:                2.0.6.0 
11/16 00:22:25.661161 0x76ff4000 UTL  maxBinaryDisplayWidth:  30 
11/16 00:22:25.661446 0x76ff4000 UTL  tempDir:                /tmp/ 
11/16 00:22:25.661747 0x76ff4000 UTL  os pageSize:            4096(KB)
11/16 00:22:25.662049 0x76ff4000 UTL  os openMax:             1024
11/16 00:22:25.662339 0x76ff4000 UTL  os streamMax:           16
11/16 00:22:25.662619 0x76ff4000 UTL  os numOfCores:          1
11/16 00:22:25.662900 0x76ff4000 UTL  os totalDisk:           3.740234(GB)
11/16 00:22:25.663221 0x76ff4000 UTL  os totalMemory:         242(MB)
11/16 00:22:25.663587 0x76ff4000 UTL  os sysname:             Linux
11/16 00:22:25.663895 0x76ff4000 UTL  os nodename:            corecloud
11/16 00:22:25.664255 0x76ff4000 UTL  os release:             4.1.15-1.2.0+gc95e082
11/16 00:22:25.664558 0x76ff4000 UTL  os version:             #1 SMP PREEMPT Sun Nov 1 19:31:39 CST 2020
11/16 00:22:25.664924 0x76ff4000 UTL  os machine:             armv7l
11/16 00:22:25.665232 0x76ff4000 UTL ==================================
11/16 00:22:25.666523 0x76ff4000 DND dnode minfos is initialized
11/16 00:22:25.667929 0x76ff4000 WAL wal module is initialized, refId:2
11/16 00:22:25.668559 0x76ff4000 DND dnode check is initialized
11/16 00:22:25.668968 0x76ff4000 DND dnode vread is initialized, min worker:1 max worker:2
11/16 00:22:25.669326 0x76ff4000 DND dnode vwrite is initialized, max worker 1
11/16 00:22:25.678445 0x76ff4000 DND dnode inter-dnodes rpc client is initialized
11/16 00:22:25.681620 0x76ff4000 DND dnode inter-dnodes RPC server is initialized
11/16 00:22:25.687112 0x76ff4000 DND there are total vnodes:0, openned:0 failed:0
11/16 00:22:25.687330 0x76ff4000 DND dnode mgmt is initialized
11/16 00:22:25.687843 0x76ff4000 MND starting to initialize mnode ...
11/16 00:22:25.695104 0x76ff4000 MND sdb write is opened
11/16 00:22:25.695626 0x76ff4000 SDB open sdb wal for restore
11/16 00:22:25.697687 0x76ff4000 MND dnode:1, fqdn:corecloud.localdomain ep:corecloud.localdomain:6030 port:6030, do insert action
11/16 00:22:25.698378 0x76ff4000 MND mnode:1, fqdn:corecloud.localdomain ep:corecloud.localdomain:6030 port:6030, do insert action
11/16 00:22:25.700314 0x76ff4000 MND cluster id is set to 0d1d550e-dd34-4940-9a01-86efb755eebc
11/16 00:22:25.700762 0x76ff4000 MND update mnodes epSet, numOfEps:1 
11/16 00:22:25.701152 0x76ff4000 MND mnode:1, ep:corecloud.localdomain:6030 master
11/16 00:22:25.701927 0x76ff4000 SDB sdb is restored, ver:7 totalRows:7 numOfTables:9
11/16 00:22:25.702347 0x76ff4000 MND dnode:1 set access:0 to 0
11/16 00:22:25.703171 0x76ff4000 MND mnode is initialized successfully
11/16 00:22:25.704408 0x76ff4000 DND dnode modules is initialized
11/16 00:22:25.704694 0x76ff4000 DND dnode mgmt timer is initialized
11/16 00:22:25.706750 0x76ff4000 DND dnode shell rpc server is initialized
11/16 00:22:25.707499 0x76ff4000 DND dnode telemetry is initialized
11/16 00:22:25.707738 0x76ff4000 HTP start http server ...
11/16 00:22:25.708227 0x76ff4000 HTP http result queue is opened
11/16 00:22:25.712763 0x67603460 HTP http server init success at 6041
11/16 00:22:25.713309 0x76ff4000 MON monitor module start
11/16 00:22:25.713685 0x76ff4000 DND TDengine is initialized successfully
Bus error

**Comment by sangshuduo** [comment]
我们在树莓派上没遇到这个问题，我们没有相同硬件，可以帮忙用 gdb 跑一下看 bus error 发生在哪个语句吗？

**Comment by xiaoyanrui** [comment]
好的，我尝试一下

**Comment by sangshuduo** [comment]
@xiaoyanrui 有什么发现吗？

**Comment by xiaoyanrui** [comment]
看起来4字节对齐后应该没问题了
