### ISSUE TITLE
count(*) of a table is not stable

### ISSUE THREAD

**Issue by lzqdename** [taosdata/TDengine#4231]
HTTP客户端在插入数据，然后后端shell不停查询count,结果发现数量还有减少的情况

taos> select count(*) from iotdb.iot_ct_666_d001_current;
       count(*)        |
========================
                396913 |
Query OK, 1 row(s) in set (0.156388s)

taos> select count(*) from iotdb.iot_ct_666_d001_current;
       count(*)        |
========================
                390951 |
Query OK, 1 row(s) in set (0.853597s)

taos> select count(*) from iotdb.iot_ct_666_d001_current;
       count(*)        |
========================
                368840 |
Query OK, 1 row(s) in set (1.236051s)

taos> select count(*) from iotdb.iot_ct_666_d001_current;
       count(*)        |
========================
                408833 |
Query OK, 1 row(s) in set (0.163119s)

taos> select count(*) from iotdb.iot_ct_666_d001_current;
       count(*)        |
========================
                409864 |
Query OK, 1 row(s) in set (0.141000s)

taos> select count(*) from iotdb.iot_ct_666_d001_current;
       count(*)        |
========================
                374958 |
Query OK, 1 row(s) in set (0.445545s)

taos> select count(*) from iotdb.iot_ct_666_d001_current;
       count(*)        |
========================
                411962 |
Query OK, 1 row(s) in set (0.137392s)

taos> select count(*) from iotdb.iot_ct_666_d001_current;
       count(*)        |
========================
                442331 |
Query OK, 1 row(s) in set (0.550542s)

taos> select count(*) from iotdb.iot_ct_666_d001_current;
       count(*)        |
========================
                488671 |
Query OK, 1 row(s) in set (0.512975s)

taos> select count(*) from iotdb.iot_ct_666_d001_current;
       count(*)        |
========================
                442955 |
Query OK, 1 row(s) in set (0.219353s)

**Comment by sangshuduo** [comment]
@lzqdename 请问是什么版本？另外是单线程写入还是多线程写入？

**Comment by lzqdename** [comment]
> @lzqdename 请问是什么版本？另外是单线程写入还是多线程写入？
TDengine-server-2.0.7.0-Linux-x64.tar.gz 
多线程HTTP写入

**Comment by sangshuduo** [comment]
@lzqdename 是不是和另一个问题  #4214 相同环境？也是 replica 3 ？

**Comment by hzcheng** [comment]
> > @lzqdename 请问是什么版本？另外是单线程写入还是多线程写入？
> > TDengine-server-2.0.7.0-Linux-x64.tar.gz
> > 多线程HTTP写入

查询的是超级表吗？写入的数据是顺序还是乱序的？

**Comment by WtyFile** [comment]
我使用的2.0.8，在count超级表的时候，查出的结果的是超级表下子表最多的条数

**Comment by sangshuduo** [comment]
现在还有这个问题吗？
