### ISSUE TITLE
System is not stable

### ISSUE THREAD

**Issue by lzqdename** [taosdata/TDengine#4235]
卸载3台机器上的taosd,然后重新安装，HTTP压测
-------------------------------------------------------
org.apache.http.conn.HttpHostConnectException: Connect to 192.168.11.171:6041 [/192.168.11.171] failed: Connection refused: connect
org.apache.http.conn.HttpHostConnectException: Connect to 192.168.11.172:6041 [/192.168.11.172] failed: Connection refused: connect
org.apache.http.conn.HttpHostConnectException: Connect to 192.168.11.171:6041 [/192.168.11.171] failed: Connection refused: connect
org.apache.http.conn.HttpHostConnectException: Connect to 192.168.11.172:6041 [/192.168.11.172] failed: Connection refused: connect
org.apache.http.conn.HttpHostConnectException: Connect to 192.168.11.171:6041 [/192.168.11.171] failed: Connection refused: connect
org.apache.http.conn.HttpHostConnectException: Connect to 192.168.11.171:6041 [/192.168.11.171] failed: Connection refused: connect

然后我就去机器上查看
[root@node02 TDengine-server-2.0.7.0]#lsof -i:6041
[root@node02 TDengine-server-2.0.7.0]#ps -ef|grep tao
root      37802      1 99 11:37 ?        00:00:10 /usr/bin/taosd
root      37886   2521  0 11:37 pts/0    00:00:00 grep --color=auto tao
[root@node02 TDengine-server-2.0.7.0]#netstat -antp|grep 6041
[root@node02 TDengine-server-2.0.7.0]#netstat -antp|grep 6041
[root@node02 TDengine-server-2.0.7.0]#netstat -antp|grep 6041
[root@node02 TDengine-server-2.0.7.0]#netstat -antp|grep 6030
tcp        0      0 192.168.11.172:6030     192.168.0.100:45250     TIME_WAIT   -                   
tcp        0      0 192.168.11.172:29740    192.168.11.171:6030     TIME_WAIT   -                   
tcp        0      0 192.168.11.172:6030     192.168.11.172:63058    TIME_WAIT   -                   
tcp        0      0 192.168.11.172:6030     192.168.11.171:24018    TIME_WAIT   -                   
tcp        0      0 192.168.11.172:58386    192.168.0.100:6030      TIME_WAIT   -                   
[root@node02 TDengine-server-2.0.7.0]#systemctl status taosd
● taosd.service - TDengine server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2020-11-16 11:37:01 CST; 43s ago
 Main PID: 37802 (taosd)
   CGroup: /system.slice/taosd.service
           └─37802 /usr/bin/taosd

Nov 16 11:37:01 node02 systemd[1]: Started TDengine server service.
Nov 16 11:37:01 node02 TDengine:[37802]: Starting TDengine service...
Nov 16 11:37:37 node02 TDengine:[37802]: Started TDengine service successfully.
[root@node02 TDengine-server-2.0.7.0]#netstat -antp|grep 6030
tcp        0      0 0.0.0.0:6030            0.0.0.0:*               LISTEN      37802/taosd         
tcp        0      0 192.168.11.172:6030     192.168.0.100:45250     TIME_WAIT   -                   
tcp        0      0 192.168.11.172:6030     192.168.11.171:24036    TIME_WAIT   -                   
tcp        0      0 192.168.11.172:6030     192.168.11.172:63074    TIME_WAIT   -                   
[root@node02 TDengine-server-2.0.7.0]#netstat -antp|grep 6041
[root@node02 TDengine-server-2.0.7.0]#systemctl status taosd
● taosd.service - TDengine server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2020-11-16 11:38:01 CST; 5s ago
 Main PID: 38129 (taosd)
   CGroup: /system.slice/taosd.service
           └─38129 /usr/bin/taosd

Nov 16 11:38:01 node02 systemd[1]: Started TDengine server service.
Nov 16 11:38:01 node02 TDengine:[38129]: Starting TDengine service...
Nov 16 11:38:02 node02 TDengine:[38129]: Started TDengine service successfully.
[root@node02 TDengine-server-2.0.7.0]#netstat -antp|grep 6041
tcp        0      0 0.0.0.0:6041            0.0.0.0:*               LISTEN      38129/taosd 

。。。

好吧，我再继续启动HTTP客户端，结果又报错
400 {"status":"error","code":1536,"desc":"Invalid table ID"}
{"status":"error","code":1536,"desc":"Invalid table ID"}
java.lang.Exception: {"status":"error","code":1536,"desc":"Invalid table ID"}
400 {"status":"error","code":1536,"desc":"Invalid table ID"}
{"status":"error","code":1536,"desc":"Invalid table ID"}
java.lang.Exception: {"status":"error","code":1536,"desc":"Invalid table ID"}
400 {"status":"error","code":1536,"desc":"Invalid table ID"}
{"status":"error","code":1536,"desc":"Invalid table ID"}
400 {"status":"error","code":1536,"desc":"Invalid table ID"}
{"status":"error","code":1536,"desc":"Invalid table ID"}
java.lang.Exception: {"status":"error","code":1536,"desc":"Invalid table ID"}
java.lang.Exception: {"status":"error","code":1536,"desc":"Invalid table ID"}
400 {"status":"error","code":1536,"desc":"Invalid table ID"}
{"status":"error","code":1536,"desc":"Invalid table ID"}

**Comment by sangshuduo** [comment]
集群硬件是什么配置？压测是多少线程？

在 /etc/taos/taos.cfg 中可以增大 httpMaxThreads 来调节性能

**Comment by lzqdename** [comment]
> 集群硬件是什么配置？压测是多少线程？
> 
> 在 /etc/taos/taos.cfg 中可以增大 httpMaxThreads 来调节性能

配置都是三四十core
压测线程30个线程，httpMaxThreads已经设置为36了
系统及其不稳定。。。我有点慌了

**Comment by sangshuduo** [comment]
@lzqdename 请问是什么版本的 TDengine？

**Comment by lzqdename** [comment]
> @lzqdename 请问是什么版本的 TDengine？

2.0.7.0 最新版本

**Comment by sangshuduo** [comment]
@lzqdename  可以试试用超级表+子表，插入数据自动建表的方式

**Comment by lzqdename** [comment]
用的就是超级表+子表，插入数据自动创建表的方式！

**Comment by stephenkgu** [comment]
v2.4 could resolve this issue.
