### ISSUE TITLE
服务正常运行，一段时间后项目无法连接服务，但虚拟机里操作taos正常

### ISSUE THREAD

**Issue by MorganArthur** [taosdata/TDengine#4237]
**Bug Description**
我使用vm创建三台虚拟机搭建集群，服务正常运行，上午我使用java项目测试连接并添加数据、查询等都没有问题，中午我将java项目停掉，TDengine服务没有停，下午的时候我再启动java项目，就报taos connect failed, reason: Invalid timestamp.，之后我再使用Windows的TDengine客户端连接服务集群同样是上边的错误。于是我在服务器上查看服务的运行状态都是running，并且可以taos进去进行sql查询。

服务器操作：
![image](https://user-images.githubusercontent.com/24489342/99215793-f92c1100-280e-11eb-8e86-16ea863ac35a.png)
客户端操作：
![image](https://user-images.githubusercontent.com/24489342/99215830-11039500-280f-11eb-8392-7b9f213af18a.png)

 - OS: centos7.5
 - TDengine Version: 2.0.7

**Comment by MorganArthur** [comment]
这是连接失败时，客户端的日志
[taoslog.zip](https://github.com/taosdata/TDengine/files/5544288/taoslog.zip)

**Comment by MorganArthur** [comment]
我尝试将三个节点的服务都重启了一边，客户端依然连不上

**Comment by sangshuduo** [comment]
可以用 date 看一下3个 vm的系统时间是不是有不一致，另外建议安装 ntp daemon 保持系统时间始终准确

**Comment by MorganArthur** [comment]
ok，我同步完时间之后，再起服务已经可以了
