### ISSUE TITLE
Where is the executable "rmtaos" that uninstalls TDengine?

### ISSUE THREAD

**Issue by lst789** [taosdata/TDengine#424]
如上

**Comment by johnnyhou327** [comment]
The ``rmtaos`` command doesn't come with the ``deb`` package or ``rpm`` package installation. If you used the above packages to install TDengine, then you might want to try ``dpkg -i``  and ``rpm -e`` respectively to uninstall TDengine on different platforms. Please note that neither of those methods removes the data files, you need to manually remove the data files defaulted in ``/var/lib/taos`` if you're sure they are no longer needed.

**Comment by johnnyhou327** [comment]
@lst789  The ``rmtaos`` command doesn't come with the ``deb`` package or ``rpm`` package installation. If you used the above packages to install TDengine, then you might want to try ``dpkg -i``  and ``rpm -e`` respectively to uninstall TDengine on different platforms. Please note that neither of those methods removes the data files, you need to manually remove the data files defaulted in ``/var/lib/taos`` if you're sure they are no longer needed.
