### ISSUE TITLE
question about docker installation 

### ISSUE THREAD

**Issue by yishierniao36** [taosdata/TDengine#4242]
**General Questions**
我在使用docker安装tdengine的时候，会显示连不上FQDN，具体报错日志如下：
 starting to initialize mnode ...
11/16 07:19:05.274536 0x7f37bb104740 MND sdb write is opened
11/16 07:19:05.274564 0x7f37bb104740 SDB open sdb wal for restore
11/16 07:19:05.275007 0x7f37bb104740 MND cluster id is set to a869c228-a4f5-4347-bf30-b20e4e4bc5c9
11/16 07:19:05.275025 0x7f37bb104740 MND update mnodes epSet, numOfEps:1 
11/16 07:19:05.275047 0x7f37bb104740 MND mnode:1, ep:095c8b4b5b28:6030 master
11/16 07:19:05.275360 0x7f37bb104740 SDB sdb is restored, ver:16 totalRows:15 numOfTables:9
11/16 07:19:05.275386 0x7f37bb104740 MND dnode:1 set access:0 to 0
11/16 07:19:05.275540 0x7f37bb104740 MND mnode is initialized successfully
11/16 07:19:05.275556 0x7f37bb104740 SDB work as mnode, replica:1
11/16 07:19:05.275562 0x7f37bb104740 SDB mnode:1, 095c8b4b5b28:6040
11/16 07:19:25.295652 0x7f37bb104740 UTL ERROR failed get the ip address, fqdn:095c8b4b5b28, code:-2, reason:Name or service not known
11/16 07:19:25.296493 0x7f37bb104740 DND dnode mgmt timer is initialized
11/16 07:19:25.297459 0x7f37bb104740 DND shell rpc server is opened
11/16 07:19:25.297514 0x7f37bb104740 HTP start http server ...
11/16 07:19:25.297843 0x7f37bb104740 HTP http result queue is opened
11/16 07:19:25.298246 0x7f37bb104740 MON start monitor module
11/16 07:19:25.298260 0x7f37bb104740 DND TDengine is initialized successfully
11/16 07:19:25.298307 0x7f378efe5700 HTP http server init success at 6041
11/16 07:19:25.309225 0x7f37b92dd700 MON starting to initialize monitor service ..
11/16 07:19:25.311074 0x7f37a1aff700 MND user:monitor login from 172.19.0.2, result:success
11/16 07:19:45.332127 0x7f378dfe3700 UTL ERROR failed get the ip address, fqdn:095c8b4b5b28, code:-2, reason:Name or service not known
11/16 07:19:45.332160 0x7f378dfe3700 RPC ERROR TSC, failed to resolve FQDN:095c8b4b5b28
11/16 07:19:45.332175 0x7f378dfe3700 RPC ERROR TSC 0x7f3780003940, failed to set up connection(Unable to resolve FQDN)
11/16 07:19:45.814393 0x7f37b92dd700 UTL ERROR failed get the ip address, fqdn:095c8b4b5b28, code:-2, reason:Name or service not known
11/16 07:19:45.814431 0x7f37b92dd700 RPC ERROR DND-C, failed to resolve FQDN:095c8b4b5b28
11/16 07:19:45.814444 0x7f37b92dd700 RPC ERROR DND-C (nil), failed to set up connection(Unable to resolve FQDN)
11/16 07:20:05.830646 0x7f37b92dd700 UTL ERROR failed get the ip address, fqdn:095c8b4b5b28, code:-2, reason:Name or service not known
11/16 07:20:05.830678 0x7f37b92dd700 RPC ERROR TSC, failed to resolve FQDN:095c8b4b5b28
11/16 07:20:05.830691 0x7f37b92dd700 RPC ERROR TSC 0x7f3780001170, failed to set up connection(Unable to resolve FQDN)
11/16 07:20:05.830957 0x7f37b92dd700 MON ERROR monitor:0x7f379c2c7d50, sql failed, reason:Unable to resolve FQDN, create database if not exists log replica 1 days 10 keep 30 cache 1 blocks 3 maxtables 16 precision 'us'
11/16 07:20:05.830996 0x7f37b92dd700 DND ERROR status rsp is received, error:Unable to resolve FQDN
11/16 07:20:26.854969 0x7f37b92dd700 UTL ERROR failed get the ip address, fqdn:095c8b4b5b28, code:-2, reason:Name or service not known
11/16 07:20:26.855006 0x7f37b92dd700 RPC ERROR DND-C, failed to resolve FQDN:095c8b4b5b28
11/16 07:20:26.855019 0x7f37b92dd700 RPC ERROR DND-C (nil), failed to set up connection(Unable to resolve FQDN)
11/16 07:20:46.872650 0x7f37b92dd700 UTL ERROR failed get the ip address, fqdn:095c8b4b5b28, code:-2, reason:Name or service not known
11/16 07:20:46.872691 0x7f37b92dd700 RPC ERROR TSC, failed to resolve FQDN:095c8b4b5b28
11/16 07:20:46.872707 0x7f37b92dd700 RPC ERROR TSC 0x7f3780001170, failed to set up connection(Unable to resolve FQDN)
11/16 07:20:46.872727 0x7f37b92dd700 MON starting to initialize monitor service ..
11/16 07:21:06.889807 0x7f37b92dd700 UTL ERROR failed get the ip address, fqdn:095c8b4b5b28, code:-2, reason:Name or service not known
11/16 07:21:06.889842 0x7f37b92dd700 RPC ERROR TSC, failed to resolve FQDN:095c8b4b5b28
11/16 07:21:06.889855 0x7f37b92dd700 RPC ERROR TSC 0x7f379c2dcc10, failed to set up connection(Unable to resolve FQDN)
11/16 07:21:06.890090 0x7f37b92dd700 DND ERROR status rsp is received, error:Unable to resolve FQDN
11/16 07:21:06.890399 0x7f37b92dd700 MON ERROR monitor:0x7f379c2c7d50, sql failed, reason:Unable to resolve FQDN, create database if not exists log replica 1 days 10 keep 30 cache 1 blocks 3 maxtables 16 precision 'us'
11/16 07:21:27.910295 0x7f37b92dd700 UTL ERROR failed get the ip address, fqdn:095c8b4b5b28, code:-2, reason:Name or service not known
11/16 07:21:27.910328 0x7f37b92dd700 RPC ERROR DND-C, failed to resolve FQDN:095c8b4b5b28
11/16 07:21:27.910340 0x7f37b92dd700 RPC ERROR DND-C (nil), failed to set up connection(Unable to resolve FQDN)
11/16 07:21:47.931136 0x7f37b92dd700 UTL ERROR failed get the ip address, fqdn:095c8b4b5b28, code:-2, reason:Name or service not known
11/16 07:21:47.931182 0x7f37b92dd700 RPC ERROR TSC, failed to resolve FQDN:095c8b4b5b28
11/16 07:21:47.931192 0x7f37b92dd700 RPC ERROR TSC 0x7f3780001170, failed to set up connection(Unable to resolve FQDN)
11/16 07:21:47.931211 0x7f37b92dd700 MON starting to initialize monitor service ..
11/16 07:22:07.949374 0x7f37b92dd700 UTL ERROR failed get the ip address, fqdn:095c8b4b5b28, code:-2, reason:Name or service not known
11/16 07:22:07.949415 0x7f37b92dd700 RPC ERROR TSC, failed to resolve FQDN:095c8b4b5b28
11/16 07:22:07.949428 0x7f37b92dd700 RPC ERROR TSC 0x7f379c2dcc10, failed to set up connection(Unable to resolve FQDN)
11/16 07:22:07.949680 0x7f37b92dd700 DND ERROR status rsp is received, error:Unable to resolve FQDN
11/16 07:22:07.949751 0x7f37b92dd700 MON ERROR monitor:0x7f379c2c7d50, sql failed, reason:Unable to resolve FQDN, create database if not exists log replica 1 days 10 keep 30 cache 1 blocks 3 maxtables 16 precision 'us'

后面我该如何操作

**Comment by sangshuduo** [comment]
@yishierniao36 参考一下其他人提的 docker 相关 issue，启动 docker 要设置 hostname，并在 taos.cfg 中指定相同的hostname 作为 FQDN
