### ISSUE TITLE
Failed to insert Chinese characters

### ISSUE THREAD

**Issue by MorganArthur** [taosdata/TDengine#4245]
我使用java程序连接tdengine集群，进行插入数据时，有个字段我设置的时NCHAR(255)。但是运行时却报错了

![image](https://user-images.githubusercontent.com/24489342/99233039-a9a90d80-282d-11eb-9dff-ce86cfaa634d.png)

而我在服务端使用sql语句直接插入确是成功的。

![image](https://user-images.githubusercontent.com/24489342/99233137-ccd3bd00-282d-11eb-8ce6-48537f9ccfc5.png)

这两张表都是使用device超级表模板建立的表。

我在此之前建立单节点的tdengine时测试插入中文时，还是程序可以成功的。

这个我不确定是哪里出了问题。

这个问题感觉和我的差不多  [Illegal byte sequence](https://github.com/taosdata/TDengine/issues/3887)

 - OS: CentOS 7.5
 - TDengine Version: 2.0.7

**Comment by MorganArthur** [comment]
同样的程序我现在又跑了一下可以插入中文了，但却全是乱码

![image](https://user-images.githubusercontent.com/24489342/99235817-4de08380-2831-11eb-8fad-3ced8c320619.png)

**Comment by zyyang-taosdata** [comment]
处理中文乱码的问题，请确保在java的客户端中指定字符集：
jdbc:TAOS://taosdemo.com:6030/test?user=root&password=taosdata&charset=UTF-8&locale=en_US.UTF-8&timezone=UTC-8
这个问题你可以按下面的步骤来排查：
1. 清空客户端的日志文件；日志文件位于C:\\TDengine\log下（windows环境），/var/log/taos（linux环境）
2. 在url中指定字符集，重启应用，插入中文，
3. 打开log日志taoslogX.X，观察字符集的设定是否生效。


![image](https://user-images.githubusercontent.com/69311263/99342174-3b645980-28c6-11eb-8d46-881c6bd40744.png)

**Comment by MorganArthur** [comment]
现在情况是这样子的：

我使用测试用例去插入数据的时候，中文字段是正常插入的。

![image](https://user-images.githubusercontent.com/24489342/99342439-ce9d8f00-28c6-11eb-981b-6849f0098cf7.png)

当我启动springboot项目，定时插入数据的时候就报错了。乱码是偶尔出现的情况，绝大部分都是报错无法插入。

![image](https://user-images.githubusercontent.com/24489342/99342496-eecd4e00-28c6-11eb-97c5-8cd2bc020c02.png)
![image](https://user-images.githubusercontent.com/24489342/99342656-597e8980-28c7-11eb-8a57-bc3a87760d3c.png)


我这样子写无法正常生成datasource

![image](https://user-images.githubusercontent.com/24489342/99342582-2e943580-28c7-11eb-85f9-bb5fa1998093.png)

代码是没有任何改动的，测试用例的运行情况和应用启动后的运行情况却不一样。

**Comment by zyyang-taosdata** [comment]
使用springboot的时候，配置datasource，把taos-jdbcdriver的版本改成2.0.11试一下

**Comment by MorganArthur** [comment]
好的，2.0.11驱动版本可以使用了，插入数据都正常了
