### ISSUE TITLE
使用prometheus作为数据源，向blm_prometheus写入数据，报taos_connect() fail!

### ISSUE THREAD

**Issue by xierunzi** [taosdata/TDengine#4252]
对blm_prometheus做了一些修改，否则无法创建db、stable。现在已经能够正常写入数据了。
但目前写入大约20秒出头，blm_prometheus日志中就会报大量taos_connect() fail!
![image](https://user-images.githubusercontent.com/65679911/99241661-1ece1000-2839-11eb-8d00-eed07a1e733e.png)

taos日志中，看到以下的错误
![image](https://user-images.githubusercontent.com/65679911/99241801-51780880-2839-11eb-82a5-fe534308d2fc.png)

**Comment by xierunzi** [comment]
TDengine版本2.0.7.0

**Comment by sangshuduo** [comment]
@xierunzi 请先升级至 2.0.9.0，看是否还有这个问题

**Comment by xiangxud** [comment]
升级到2.0.10.0仍然有这个问题，是单机版的问题吗

**Comment by xiangxud** [comment]
12/17 01:26:54.341521 0x7f7e6a445700 RPC ERROR TSC 0x10d9, failed to set up connection(Unable to resolve FQDN)
12/17 01:26:54.341533 0x7f7e6a445700 UTL ERROR failed to get the ip address, fqdn:node1, since:Too many open files
12/17 01:26:54.341535 0x7f7e6a445700 RPC ERROR TSC, failed to resolve FQDN:node112/17 01:26:54.341536 0x7f7e6a445700 RPC ERROR TSC 0x10dc, failed to set up connection(Unabl
e to resolve FQDN)
12/17 01:26:54.341549 0x7f7e6a445700 UTL ERROR failed to get the ip address, fqdn:node1, since:Too many open files
12/17 01:26:54.341551 0x7f7e6a445700 RPC ERROR TSC, failed to resolve FQDN:node112/17 01:26:54.341552 0x7f7e6a445700 RPC ERROR TSC 0xb9e, failed to set up connection(Unable
 to resolve FQDN)
12/17 01:26:54.915418 0x7f7e6a445700 UTL ERROR failed to get the ip address, fqdn:node1, since:Too many open files
12/17 01:26:54.915430 0x7f7e6a445700 RPC ERROR TSC, failed to resolve FQDN:node112/17 01:26:54.915434 0x7f7e6a445700 RPC ERROR TSC 0x227e, failed to set up connection(Unabl
e to resolve FQDN)

**Comment by xiangxud** [comment]
解决DB error: Unable to establish connection 
172.16.5.71 数据库服务器所在机器IP,不能用127.0.0.1 ，亲测可行
重置数据库，使用ip而不是fqdn来启动TDengine。
方法是：
1、systemctl stop taosd
2、rm -rf /var/lib/taos
3、vi /etc/taos/taos.cfg，在其中增加一行
firstEp 172.16.5.71:6030
fqdn 172.16.5.71
4、systemctl restart taosd
5、linux机器上，taos连接后，show dnodes，看看fqdn是不是变为了172.16.5.71
6、windows机器上，用taos -h 172.16.5.71试一下

**Comment by xierunzi** [comment]
> 解决DB error: Unable to establish connection
> 172.16.5.71 数据库服务器所在机器IP,不能用127.0.0.1 ，亲测可行
> 重置数据库，使用ip而不是fqdn来启动TDengine。
> 方法是：
> 1、systemctl stop taosd
> 2、rm -rf /var/lib/taos
> 3、vi /etc/taos/taos.cfg，在其中增加一行
> firstEp 172.16.5.71:6030
> fqdn 172.16.5.71
> 4、systemctl restart taosd
> 5、linux机器上，taos连接后，show dnodes，看看fqdn是不是变为了172.16.5.71
> 6、windows机器上，用taos -h 172.16.5.71试一下

好的感谢，不过目前我没有用这个插件做prometheus数据写入了。自己写了一个Java版本。

**Comment by xiangxud** [comment]
运行了一段时间后又发现了新的问题
[root@node1 taos]# tail -f taoslog0.1
12/20 01:49:20.478237 0x7f160a94b700 RPC ERROR TSC failed to create TCP client epoll
12/20 01:49:20.478268 0x7f160a94b700 UTL ERROR failed to open udp socket: 24 (Too many open files)
12/20 01:49:20.478271 0x7f160a94b700 RPC ERROR TSC failed to open UDP socket 0:0
12/20 01:49:20.478273 0x7f160a94b700 RPC ERROR TSC failed to init network, port:0
12/20 01:49:20.478435 0x7f160a94b700 TSC ERROR failed to init connection to TDengine
12/20 01:49:20.478893 0x7f160a94b700 RPC ERROR TSC failed to create TCP client epoll
12/20 01:49:20.478939 0x7f160a94b700 UTL ERROR failed to open udp socket: 24 (Too many open files)
12/20 01:49:20.478944 0x7f160a94b700 RPC ERROR TSC failed to open UDP socket 0:0
12/20 01:49:20.478947 0x7f160a94b700 RPC ERROR TSC failed to init network, port:0
12/20 01:49:20.479025 0x7f160a94b700 TSC ERROR failed to init connection to TDengine
12/20 01:49:30.478227 0x7f160a94b700 RPC ERROR TSC failed to create TCP client epoll
12/20 01:49:30.478339 0x7f160a94b700 UTL ERROR failed to open udp socket: 24 (Too many open files)
12/20 01:49:30.478368 0x7f160a94b700 RPC ERROR TSC failed to open UDP socket 0:0
12/20 01:49:30.478372 0x7f160a94b700 RPC ERROR TSC failed to init network, port:0
12/20 01:49:30.478513 0x7f160a94b700 TSC ERROR failed to init connection to TDengine
12/20 01:49:30.478928 0x7f160a94b700 RPC ERROR TSC failed to create TCP client epoll
12/20 01:49:30.478977 0x7f160a94b700 UTL ERROR failed to open udp socket: 24 (Too many open files)
12/20 01:49:30.478985 0x7f160a94b700 RPC ERROR TSC failed to open UDP socket 0:0
12/20 01:49:30.478991 0x7f160a94b700 RPC ERROR TSC failed to init network, port:0
12/20 01:49:30.479471 0x7f160a94b700 TSC ERROR failed to init connection to TDengine
12/20 01:49:30.485611 0x7f160a94b700 RPC ERROR TSC failed to create TCP client epoll
12/20 01:49:30.485685 0x7f160a94b700 UTL ERROR failed to open udp socket: 24 (Too many open files)
12/20 01:49:30.485693 0x7f160a94b700 RPC ERROR TSC failed to open UDP socket 0:0
12/20 01:49:30.485696 0x7f160a94b700 RPC ERROR TSC failed to init network, port:0
12/20 01:49:30.485895 0x7f160a94b700 TSC ERROR failed to init connection to TDengine
12/20 01:49:30.486356 0x7f160a94b700 RPC ERROR TSC failed to create TCP client epoll
12/20 01:49:30.486405 0x7f160a94b700 UTL ERROR failed to open udp socket: 24 (Too many open files)
12/20 01:49:30.486411 0x7f160a94b700 RPC ERROR TSC failed to open UDP socket 0:0
12/20 01:49:30.486415 0x7f160a94b700 RPC ERROR TSC failed to init network, port:0
12/20 01:49:30.486554 0x7f160a94b700 TSC ERROR failed to init connection to TDengine
12/20 01:49:40.475657 0x7f160a94b700 RPC ERROR TSC failed to create TCP client epoll
12/20 01:49:40.475739 0x7f160a94b700 UTL ERROR failed to open udp socket: 24 (Too many open files)
12/20 01:49:40.475743 0x7f160a94b700 RPC ERROR TSC failed to open UDP socket 0:0
12/20 01:49:40.475746 0x7f160a94b700 RPC ERROR TSC failed to init network, port:0
12/20 01:49:40.475807 0x7f160a94b700 TSC ERROR failed to init connection to TDengine
12/20 01:49:40.476179 0x7f160a94b700 RPC ERROR TSC failed to create TCP client epoll
12/20 01:49:40.476217 0x7f160a94b700 UTL ERROR failed to open udp socket: 24 (Too many open files)
12/20 01:49:40.476220 0x7f160a94b700 RPC ERROR TSC failed to open UDP socket 0:0
12/20 01:49:40.476222 0x7f160a94b700 RPC ERROR TSC failed to init network, port:0
12/20 01:49:40.476255 0x7f160a94b700 TSC ERROR failed to init connection to TDengine
12/20 01:49:40.477161 0x7f160a94b700 RPC ERROR TSC failed to create TCP client epoll
12/20 01:49:40.477190 0x7f160a94b700 UTL ERROR failed to open udp socket: 24 (Too many open files)
12/20 01:49:40.477194 0x7f160a94b700 RPC ERROR TSC failed to open UDP socket 0:0
12/20 01:49:40.477197 0x7f160a94b700 RPC ERROR TSC failed to init network, port:0
12/20 01:49:40.477266 0x7f160a94b700 TSC ERROR failed to init connection to TDengine
12/20 01:49:40.477548 0x7f160a94b700 RPC ERROR TSC failed to create TCP client epoll
12/20 01:49:40.477570 0x7f160a94b700 UTL ERROR failed to open udp socket: 24 (Too many open files)
12/20 01:49:40.477572 0x7f160a94b700 RPC ERROR TSC failed to open UDP socket 0:0
12/20 01:49:40.477574 0x7f160a94b700 RPC ERROR TSC failed to init network, port:0
12/20 01:49:40.477611 0x7f160a94b700 TSC ERROR failed to init connection to TDengine
12/20 01:49:50.478350 0x7f13e27bc700 RPC ERROR TSC failed to create TCP client epoll
12/20 01:49:50.478447 0x7f13e27bc700 UTL ERROR failed to open udp socket: 24 (Too many open files)
12/20 01:49:50.478453 0x7f13e27bc700 RPC ERROR TSC failed to open UDP socket 0:0
12/20 01:49:50.478455 0x7f13e27bc700 RPC ERROR TSC failed to init network, port:0
12/20 01:49:50.478550 0x7f13e27bc700 TSC ERROR failed to init connection to TDengine
12/20 01:49:50.478998 0x7f13e27bc700 RPC ERROR TSC failed to create TCP client epoll
12/20 01:49:50.479040 0x7f13e27bc700 UTL ERROR failed to open udp socket: 24 (Too many open files)
12/20 01:49:50.479044 0x7f13e27bc700 RPC ERROR TSC failed to open UDP socket 0:0
12/20 01:49:50.479046 0x7f13e27bc700 RPC ERROR TSC failed to init network, port:0
12/20 01:49:50.479143 0x7f13e27bc700 TSC ERROR failed to init connection to TDengine
12/20 01:49:50.480539 0x7f13e27bc700 RPC ERROR TSC failed to create TCP client epoll
12/20 01:49:50.480589 0x7f13e27bc700 UTL ERROR failed to open udp socket: 24 (Too many open files)
12/20 01:49:50.480592 0x7f13e27bc700 RPC ERROR TSC failed to open UDP socket 0:0
12/20 01:49:50.480594 0x7f13e27bc700 RPC ERROR TSC failed to init network, port:0

**Comment by sangshuduo** [comment]
请使用最新的 blm\_prometheus 代码编译

**Comment by anjia0532** [comment]
用新版的blm_prometheus重新编译，或者用docker hub上的最新的2.0.0.0 往 tdengine/tdengine:2.0.16.0 和 tdengine/tdengine:2.0.17.0 写数据都不行

```
BLM_PRM2021/03/12 03:05:51 server.go:157: host: ip
BLM_PRM2021/03/12 03:05:51 server.go:158: 172.18.5.18:6030
BLM_PRM2021/03/12 03:05:51 server.go:159:   port:
BLM_PRM2021/03/12 03:05:51 server.go:160: 10203
BLM_PRM2021/03/12 03:05:51 server.go:161:   database:
BLM_PRM2021/03/12 03:05:51 server.go:162: prometheus
BLM_PRM2021/03/12 03:05:51 server.go:569: taosDriverName:taosSql,url:root:taosdata@/tcp(172.18.5.18:6030)/
BLM_PRM2021/03/12 03:05:51 server.go:574: Open database success
BLM_PRM2021/03/12 03:05:52 server.go:578: create database if not exists prometheus  ,result:taos_connect() fail!
BLM_PRM2021/03/12 03:05:52 server.go:580: use prometheus  ,result:taos_connect() fail!
BLM_PRM2021/03/12 03:05:53 server.go:603: taos_connect() fail!
BLM_PRM2021/03/12 03:06:01 server.go:595: execSql Error: taos_connect() fail! sqlcmd: create table if not exists go_gc_duration_seconds (ts timestamp, value double) tags(taghash binary(34),t_instance binary(128),t_job binary(128),t_monitor binary(128),t_quantile binary(128))
```
