### ISSUE TITLE
TSDBDriver claims to not accept jdbcUrl

### ISSUE THREAD

**Issue by Michaelove** [taosdata/TDengine#4253]
在centos 7 上安装了tdengine2.0.6，同时也会运行一个springboot项目，连接驱动用的时2.0.6。项目启动的时会连接tdengine，启动过程中不报错，但是进行数据交互的时候会出现错误。错误内容：java.lang.RuntimeException: Driver com.taosdata.jdbc.TSDBDriver claims to not accept jdbcUrl, jdbc:TAOS://XXX.XXX.XXX.XXX:6030/mgd。

**Comment by sangshuduo** [comment]
请参考官方例子 https://github.com/taosdata/TDengine/tree/develop/tests/examples/JDBC

**Comment by Michaelove** [comment]
这是driver版本的问题，换成2.0.7就行了
