### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by lsxredrain** [taosdata/TDengine#4261]
**Bug Description**
 compile error
**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. master]

**Additional Context**
/root/TDengine/src/connector/odbc/src/todbc.c: In function ‘doSQLConnect’:
/root/TDengine/src/connector/odbc/src/todbc.c:402:3: error: implicit declaration of function ‘strndup’ [-Werror=implicit-function-declaration]
   const char *serverName = SDUP(ServerName,     NameLength1);
   ^
/root/TDengine/src/connector/odbc/src/todbc.c:93:50: error: incompatible implicit declaration of built-in function ‘strndup’ [-Werror]
 #define SDUP(s,n)      (s ? (s[n] ? (const char*)strndup((const char*)s,n) : (const char*)s) : strdup(""))
                                                  ^
/root/TDengine/src/connector/odbc/src/todbc.c:402:28: note: in expansion of macro ‘SDUP’
   const char *serverName = SDUP(ServerName,     NameLength1);
                            ^
/root/TDengine/src/connector/odbc/src/todbc.c:402:3: error: implicit declaration of function ‘strdup’ [-Werror=implicit-function-declaration]
   const char *serverName = SDUP(ServerName,     NameLength1);
   ^
/root/TDengine/src/connector/odbc/src/todbc.c:93:96: error: incompatible implicit declaration of built-in function ‘strdup’ [-Werror]
 #define SDUP(s,n)      (s ? (s[n] ? (const char*)strndup((const char*)s,n) : (const char*)s) : strdup(""))
                                                                                                ^
/root/TDengine/src/connector/odbc/src/todbc.c:402:28: note: in expansion of macro ‘SDUP’
   const char *serverName = SDUP(ServerName,     NameLength1);
                            ^
/root/TDengine/src/connector/odbc/src/todbc.c: In function ‘doSQLExecDirect’:
/root/TDengine/src/connector/odbc/src/todbc.c:93:50: error: incompatible implicit declaration of built-in function ‘strndup’ [-Werror]
 #define SDUP(s,n)      (s ? (s[n] ? (const char*)strndup((const char*)s,n) : (const char*)s) : strdup(""))
                                                  ^
/root/TDengine/src/connector/odbc/src/todbc.c:605:22: note: in expansion of macro ‘SDUP’
   const char *stxt = SDUP(StatementText, TextLength);
                      ^
/root/TDengine/src/connector/odbc/src/todbc.c:93:96: error: incompatible implicit declaration of built-in function ‘strdup’ [-Werror]
 #define SDUP(s,n)      (s ? (s[n] ? (const char*)strndup((const char*)s,n) : (const char*)s) : strdup(""))
                                                                                                ^
/root/TDengine/src/connector/odbc/src/todbc.c:605:22: note: in expansion of macro ‘SDUP’
   const char *stxt = SDUP(StatementText, TextLength);
                      ^
/root/TDengine/src/connector/odbc/src/todbc.c: In function ‘doSQLDriverConnect’:
/root/TDengine/src/connector/odbc/src/todbc.c:93:50: error: incompatible implicit declaration of built-in function ‘strndup’ [-Werror]
 #define SDUP(s,n)      (s ? (s[n] ? (const char*)strndup((const char*)s,n) : (const char*)s) : strdup(""))
                                                  ^
/root/TDengine/src/connector/odbc/src/todbc.c:2052:28: note: in expansion of macro ‘SDUP’
   const char *connStr    = SDUP(szConnStrIn, cbConnStrIn);
                            ^
/root/TDengine/src/connector/odbc/src/todbc.c:93:96: error: incompatible implicit declaration of built-in function ‘strdup’ [-Werror]
 #define SDUP(s,n)      (s ? (s[n] ? (const char*)strndup((const char*)s,n) : (const char*)s) : strdup(""))
                                                                                                ^
/root/TDengine/src/connector/odbc/src/todbc.c:2052:28: note: in expansion of macro ‘SDUP’
   const char *connStr    = SDUP(szConnStrIn, cbConnStrIn);
                            ^
/root/TDengine/src/connector/odbc/src/todbc.c: In function ‘doSQLDescribeCol’:
/root/TDengine/src/connector/odbc/src/todbc.c:2172:5: error: implicit declaration of function ‘strnlen’ [-Werror=implicit-function-declaration]
     *NameLength = strnlen(field->name, sizeof(field->name));
     ^
cc1: all warnings being treated as errors

**Comment by sangshuduo** [comment]
@lsxredrain 请问这是哪个branch？在什么OS上编译的？编译器版本多少？

**Comment by lsxredrain** [comment]
master分支，在cenots 7.2版本，编译过程参照git上操作步骤执行的

**Comment by lsxredrain** [comment]
Centos 7:
sudo yum install -y gcc gcc-c++ make cmake3 epel-release git
sudo yum remove -y cmake
sudo ln -s /usr/bin/cmake3 /usr/bin/cmake
To install openjdk-8:

sudo yum install -y java-1.8.0-openjdk
To install Apache Maven:

sudo yum install -y maven
Build TDengine
On Linux platform
mkdir debug && cd debug
cmake .. && cmake --build .

**Comment by lsxredrain** [comment]
[root@VM-0-6-centos debug]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)

**Comment by lsxredrain** [comment]
[root@VM-0-6-centos TDengine]# git branch
* develop
[root@VM-0-6-centos TDengine]#

**Comment by sangshuduo** [comment]
@lsxredrain OK，我们尽快解决，谢谢
