### ISSUE TITLE
Can twa support interval?

### ISSUE THREAD

**Issue by Drazen08** [taosdata/TDengine#4265]
版本是2.0.6 通过twa函数在非超表查询点位数据，sql末尾增加了interval 后，直接中断查询，请问一下，这个函数支持interval关键字吗？

查询sql：
select twa(point_value) from t_3825674681959431_0 where  point_time <= '2020-11-10 20:40:19' and point_time >= '2020-11-10 20:30:19' INTERVAL(1m) fill(null);

**Comment by hjxilinx** [comment]
TWA 函数现在应该计算结果有问题，建议暂时不要使用。
我们后面会这个问题。

**Comment by hjxilinx** [comment]
TWA 函数在2.0.9.x 版本中已经修复并可以正常使用。
