### ISSUE TITLE
 last_row(*)  header display incorrect

### ISSUE THREAD

**Issue by maikebing** [taosdata/TDengine#4269]
**Bug Description**
 last_row(*)  返回的数据列名现在全是     last_row(ts)   ， 原来是    last_row(字段名)

**To Reproduce**
select last_row(*) from iotsharp.telemetrydata where deviceid='9749ff047caa4b1f9f53967706fb0c73' group by deviceid,keyname;

 

**Screenshots**
 
![image](https://user-images.githubusercontent.com/3445167/99408206-edce0800-292a-11eb-923e-2ae0904ca026.png)

![image](https://user-images.githubusercontent.com/3445167/99410194-2838a480-292d-11eb-964f-46d9e6d896c5.png)

**Environment (please complete the following information):**

 - TDengine Version [2.0.7.0]

**Comment by stephenkgu** [comment]
是 develop HEAD代码吗？

**Comment by maikebing** [comment]
docker  中的版本。 2.0.7.0

**Comment by maikebing** [comment]
这个修复后的镜像什么时候出？生产中着急用。

**Comment by stephenkgu** [comment]
这个要下周了

**Comment by maikebing** [comment]
能不能帮忙给搞个临时小版本，

**Comment by stephenkgu** [comment]
你的 docker 实例多吗？

**Comment by sangshuduo** [comment]
@maikebing 可以自己在 develop 分支编译一个

**Comment by maikebing** [comment]
@stephenkgu     恩， 就一个， 但是在生产中。 

@sangshuduo   docker脚本我看还比较麻烦。 

docker pull tdengine/tdengine:develop  
这个   tag   十个月前的。 怎么没更新？是不是自动推送坏掉了？

**Comment by sangshuduo** [comment]
docker 和版本发布一起更新，没有特意更新 :develop

**Comment by PascalMing** [comment]
first没问题
另外建议Last不要改变列名。原来ts，还是用ts，不要改为last(ts)。这样上层映射好处理。
