### ISSUE TITLE
How to connect TDengine with NIFI?

### ISSUE THREAD

**Issue by dddsssggg** [taosdata/TDengine#4271]
在NiFi中使用处理器ExecuteSQL获取tdengine数据库信息时，报错
![a](https://user-images.githubusercontent.com/74594395/99468829-7d4fd700-297c-11eb-8031-911a222e6988.png)
其中处理器的配置信息如下
![b](https://user-images.githubusercontent.com/74594395/99468942-b8eaa100-297c-11eb-844b-71372f4106d2.png)
数据库连接池的配置信息如下
![c](https://user-images.githubusercontent.com/74594395/99469009-d881c980-297c-11eb-9163-ca6b67eae26d.png)
确定数据库及表存在并有数据，请问配置信息有错误嘛，报错是什么原因？

**Comment by stephenkgu** [comment]
这是一个NiFi使用问题，建议查看下NiFi的使用手册。
