### ISSUE TITLE
Is it normal taosd uses 22GB memory?

### ISSUE THREAD

**Issue by quchunhui** [taosdata/TDengine#4275]
在项目服务器上搭建了TDengine集群（3个节点，centos8，每个节点8核64GB内存），集群采用的3副本，
为了模拟3年的数据来验证查询性能，写了一个批量写入的程序，程序地址
https://github.com/quchunhui/java-demo/blob/master/tdengine/src/main/java/com/rexel/tdengine/api/MockData.java
由于需要模拟3年的数据，采用了多线程的方式写入，每个线程负责1个月的数据，共36个线程同时写入。
此时用systemctl status taosd查看状态，发现taosd占用了20多个G的内存，请问这个内存大小是否正常？
是否可以设置这个内存的上限？担心占用太多，影响其他组件的运行，集群中还有消息队列，Flink，Yarn等大数据组件在运行。

taod截图
![image](https://user-images.githubusercontent.com/18110478/99478424-54850d00-298f-11eb-8daf-f85447a67c9e.png)
数据库截图
![image](https://user-images.githubusercontent.com/18110478/99478461-649cec80-298f-11eb-9e4f-e62218ee079b.png)

**Comment by stephenkgu** [comment]
alter database stress_test blocks 12;

**Comment by quchunhui** [comment]
更正一下，我的电脑配置是64G，目前taod已经用到54个G了，
数据库的block数16，cache16MB，请问，这个54G都用在了什么地方？是如何计算的？还望解答。
如果td自己就占用了这么多内存，对整个集群的影响太大了。
![image](https://user-images.githubusercontent.com/18110478/99663713-f8f77400-2aa1-11eb-9950-ab331ab256d7.png)
![image](https://user-images.githubusercontent.com/18110478/99663651-e2e9b380-2aa1-11eb-94fb-b2063624773b.png)

**Comment by stephenkgu** [comment]
表的数量大概多少？

**Comment by quchunhui** [comment]
在新版本中测试，如果发现问题再重新起票
