### ISSUE TITLE
TSDB error:server-client date time unsynced 

### ISSUE THREAD

**Issue by willemmiao** [taosdata/TDengine#429]
源码在Linux上安装server端成功了。
‘
Welcome to the TDengine shell, client version:1.6.1.5  server version:1.6.1.5
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.
’
在Windows上安装了客服端。链接报错：
‘
Welcome to the TDengine shell, client version:1.6.1.7
TSDB error:server-client date time unsynced 
’
客户端和服务端版本不一致吗？
怎么升级服务端版本呢？

**Comment by skyformat99** [comment]
时间不同步

**Comment by willemmiao** [comment]
> 时间不同步

时间同步了。
`Welcome to the TDengine shell, client version:1.6.1.7
TSDB error: version of client and server not match`
依然是有版本问题的。
源码安装的Linux服务端怎么更新版本呢？谢谢。

**Comment by kidari** [comment]
同问 version of client and server not match我也遇到过这个问题

**Comment by hjxilinx** [comment]
可以从git上pull最新的代码，编译完成后，使用编译生成的taosd直接替换/usr/loccal/taos/bin目录下的taosd和taos即可。

**Comment by guanshengliang** [comment]
客户端与服务端的版本号一致，这是一个基本假设。
如果你是从`www.taosdata.com`下载的windows客户端，那么需要下载同样的linux服务端。
如果你是从源码自己编译的windows客户端，那么也要保证编译linux服务端用的是同一个git版本的代码

**Comment by daconglee** [comment]
Welcome to the TDengine shell from windows, client version:1.6.5.6
DB error: server-client date time unsynced

Centos  :  version:1.6.5.6
