### ISSUE TITLE
Springboot服务异常停止

### ISSUE THREAD

**Issue by Michaelove** [taosdata/TDengine#4293]
虚拟机中安装有tdengine和一个springboot服务，发生的情况是springboot服务运行一段时间之后，项目会宕机，taos未发生宕机，查看报告，发现是中途连接失败，故障日志的一部分是“Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again”。请问该怎么解决

**Comment by zyyang-taosdata** [comment]
感谢您的问题，从你描述的情况很难定位问题的位置。为了方便定位你的问题，请你
1. 在springboot应用的那台虚拟机下清空日志，日志的存放路径默认在C:\\TDengine\log（windows上）或/var/log/taos（linux上）下。
2. 重启springboot应用，并制造报错。
3. 分析报错日志，查找ERROR。
如果自己解决不了，可以把报错的日志粘贴过来

**Comment by YiuTerran** [comment]
这明显和项目无关，建议关闭掉该问题 @zyyang-taosdata
