### ISSUE TITLE
外网 通过restful api 访问 无返回

### ISSUE THREAD

**Issue by tinybright** [taosdata/TDengine#43]
内网访问正常

**Comment by hjxilinx** [comment]
该版本当前只能绑定1个IP地址，内外网的问题，我们会尽快处理。

**Comment by xinqiyang** [comment]
我们这边，部署的是docker， 2个docker直接互相访问也不成功。 

@hjxilinx   这个地方，绑定一个ip地址在哪里咋个设置啊。 。。。

**Comment by xinqiyang** [comment]
部署同一台，用 docker ，2个实例访问，这里也提示出错啊。。。。。 
@hjxilinx  帮忙看看。。。 ip在哪里设置
用自带的connector访问不到，这个是啥情况。 配置绑定的ip在哪里设置的？ 

root@taosubuntudev:/data/coinphd/ai/coinphd/tests# python -m unittest taostest.TaosTest.test_basic
07/16 14:57:14.714396 7f8ee9e24080 TSC set config file directory:/etc/taos
option file:/etc/taos/taos.cfg not found, all options are set to system default
connect to TDengine failed
connection is closed
E
======================================================================
ERROR: test_basic (taostest.TaosTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/coinphd/ai/coinphd/tests/taostest.py", line 38, in test_basic
    raise (err)
  File "/data/coinphd/ai/coinphd/tests/taostest.py", line 35, in test_basic
    c1.execute('create database db1')
  File "/usr/local/lib/python3.7/site-packages/taos/cursor.py", line 113, in execute
    raise ProgrammingError(CTaosInterface.errStr(self._connection._conn))
taos.error.ProgrammingError: login disconnected, login again

----------------------------------------------------------------------
Ran 1 test in 1.074s

FAILED (errors=1)
root@taosubuntudev:/data/coinphd/ai/coinphd/tests#

这里http可以访问到
root@taosubuntudev:/data/coinphd/ai/coinphd/tests# curl 192.168.1.103:6020
{"status":"error","code":1002,"desc":"http url is not support"}root@taosubuntudev:/data/coinphd/ai/coinphd/tests#

**Comment by johnnyhou327** [comment]
@tinybright 可以参考一下 [Issue73](https://github.com/taosdata/TDengine/issues/73) 中的解决方式

**Comment by maikebing** [comment]
可以使用nginx  解决

**Comment by maikebing** [comment]
server {
        listen 80;
        server_name  td.gitclub.cn;
        #Redirects all traffic
        location / {
            proxy_pass  http://localhost:6020;
            #limit_req   zone=one burst=10 nodelay;
		proxy_redirect 			off;
		proxy_set_header 		Host 			$host;
		proxy_set_header		X-Real-IP 		$remote_addr;
		proxy_set_header		X-Forwarded-For	$proxy_add_x_forwarded_for;
		proxy_set_header    X-Forwarded-Proto $scheme;
		client_max_body_size 	10m;
		client_body_buffer_size 128k;
		proxy_connect_timeout 	90;
		proxy_send_timeout 		90;
		proxy_read_timeout 		90;
		proxy_buffers			32 4k;
             }
}
