### ISSUE TITLE
how to establish connection through jdbc.TSDBDriver in the docker?

### ISSUE THREAD

**Issue by kidari** [taosdata/TDengine#430]
Class.forName("com.taosdata.jdbc.TSDBDriver");
        String jdbcUrl = url;
        Properties connProps = new Properties();
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_USER, username);
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_PASSWORD, password);
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_CONFIG_DIR, "/etc/taos");
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_CHARSET, "UTF-8");
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_TIME_ZONE, "UTC-8");
        this.connection = DriverManager.getConnection(jdbcUrl, connProps);
        this.databaseColumnHumpToLine = databaseColumnHumpToLine;
如题容器中没有安装taosd，taosd安装在数据库服务器中

**Comment by fangpanpan** [comment]
您可以做端口映射。

**Comment by kidari** [comment]
The container running in application server doesn't exist TSDB when we run program in it,but jdbc.TSDB Driver needs to connect the taos client firstly.I don't think it is wise  to use docker connect with host taos client.How to establish?

**Comment by hzcheng** [comment]
So you want to deploy your application in container, right? You can try to copy the dynamic library _libtaos.so_ to the container as well as the JDBC driver package. Put them in the right place.
