### ISSUE TITLE
创建超级表出错

### ISSUE THREAD

**Issue by yishierniao36** [taosdata/TDengine#4307]
我在创建表的时候有很多都创建失败了，是哪里有问题吗？
具体sql如下：
CREATE TABLE IF NOT EXISTS a1XvHMe728p (create_time timestamp,planValue INT,onlamp INT,alarmRows NCHAR(1000),difference DOUBLE,type INT,Consumption FLOAT,online INT,savingRate DOUBLE,offlamp INT,offline INT,normallamp INT,name NCHAR(500),status INT,handled INT,onRate DOUBLE,alarmCount INT,actualValue DOUBLE,alarmTotal INT,alarmlamp INT,extant INT,onlineRate DOUBLE) TAGS (device_id binary(64),device_name nchar(150))

CREATE TABLE IF NOT EXISTS a1Ci3yRPEpp (create_time timestamp,Illumination FLOAT,Illumination_min_time INT,Humidity_num INT,Illumination_max INT,Humidity_min FLOAT,Temperature_max FLOAT,Humidity_max_time INT,Temperature FLOAT,Pressure_num INT,Humidity_max FLOAT,Pressure_max FLOAT,Battery_max INT,Illumination_num INT,Pressure_sum FLOAT,Pressure_avg FLOAT,Humidity_sum FLOAT,Temperature_min FLOAT,Battery_min_time INT,Temperature_avg FLOAT,Battery INT,Sunshine_seconds INT,Temperature_sum FLOAT,Humidity FLOAT,Battery_num INT,Illumination_sum INT,Battery_min INT,Battery_sum INT,Temperature_max_time INT,Pressure_min FLOAT,Humidity_min_time INT,Battery_avg FLOAT,Width INT,Illumination_avg FLOAT,Image NCHAR(500),Illumination_max_time INT,Temperature_min_time INT,Pressure_min_time INT,Temperature_num INT,Pressure_max_time INT,Height INT,Humidity_avg FLOAT,Battery_max_time INT,Illumination_min INT,Pressure FLOAT) TAGS (device_id binary(64),device_name nchar(150))

报错信息如下;
![图片](https://user-images.githubusercontent.com/10684150/99791675-e85a0300-2b60-11eb-8594-fb0c59ca48b7.png)

**Comment by yishierniao36** [comment]
有些表他是能创建成功的，就很奇怪，数据库版本是2.0.7.0

**Comment by sangshuduo** [comment]
错误信息：Error: Unable to establish connections

请使用客户端先验证和服务端连接是否有问题

**Comment by yishierniao36** [comment]
客户端查询都是可以的

**Comment by yishierniao36** [comment]
> 错误信息：Error: Unable to establish connections
> 
> 请使用客户端先验证和服务端连接是否有问题

客户端查询是可以的，连接没问题

**Comment by sangshuduo** [comment]
先在 taos.cfg 中把 debugFlag 设成 143，清空 log，然后重复建表过程，上传 log 我们看一下吧

**Comment by yishierniao36** [comment]
好的

**Comment by yishierniao36** [comment]
[taosdlog.txt](https://github.com/taosdata/TDengine/files/5579071/taosdlog.txt)
是这个日志吗

**Comment by yishierniao36** [comment]
> 
> 
> 先在 taos.cfg 中把 debugFlag 设成 143，清空 log，然后重复建表过程，上传 log 我们看一下吧

是这个日志吗
[taosdlog.txt](https://github.com/taosdata/TDengine/files/5579072/taosdlog.txt)

**Comment by sangshuduo** [comment]
这个是服务端 taosd 的 log，而且里面的时间是 17号。应该发 Windows 上类似 taoslog0.0 这样的 log，默认位置在 C:\\TDengine\\log 目录

**Comment by yishierniao36** [comment]
[taoslog.zip](https://github.com/taosdata/TDengine/files/5580811/taoslog.zip)
您看下，是这个吧

**Comment by yishierniao36** [comment]
暂时先用restful的方式处理了

**Comment by sangshuduo** [comment]
@yishierniao36 是这个 log ，麻烦把同时间的服务端 log 也发一下， taosdlog 开头的。谢谢

**Comment by yishierniao36** [comment]
同时间的服务端的日志找不到了。。。
我发现只是通过驱动连接会有这个问题，在服务端通过命令或者通过restful接口都没问题

**Comment by sangshuduo** [comment]
长时间无更新。关闭。
