### ISSUE TITLE
It doesn't work to set dafaultUser, defaultPass in the RESTful taos.cfg

### ISSUE THREAD

**Issue by spjiang** [taosdata/TDengine#431]

**Comment by guanshengliang** [comment]
The restful interface must provide authentication information
for the request from http does not have any local configuration file

**Comment by spjiang** [comment]
curl -H 'Authorization: Basic <TOKEN>' -d '<SQL>' <ip>:<PORT>/rest/sql
TOKEN为{username}:{password}经过Base64编码之后的字符串，例如root:taosdata编码后为cm9vdDp0YW9zZGF0YQ==

username 和 password 使用的是配置文件中新的用户名和密码，结果是不行的，必须使用root,taosdata才可以

**Comment by guanshengliang** [comment]
修改配置文件中的默认密码，不会修改数据库的密码。
配置文件中的默认密码，只是客户端登录时的一个默认值。
