### ISSUE TITLE
macos 使用idea 链接数据库报错

### ISSUE THREAD

**Issue by lixin888888** [taosdata/TDengine#4311]
macos 使用idea 链接数据库

报错显示如下：
无法加载原生库。

no taos in java.library.path: [/Users/lixin/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .].
no taos in java.library.path: [/Users/lixin/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]

**Comment by sangshuduo** [comment]
TDengine 暂不支持 Mac OS
