### ISSUE TITLE
taos 2.0版本实时查询过程中存储连接数据库失败

### ISSUE THREAD

**Issue by zyl66** [taosdata/TDengine#4314]
一边采用java多线程池往taos2.0实时插入数据（能插入成功），一边采用python语言每30s查询taos的实时数据，能正常返回结果，运行一段时间后(约2个月后），发现查询过程中出现连接数据库失败（每查询一次，连接一次数据库模式）；但把taos升级到2.0.7，原程序没作任何修改，发现运行不到2天，出现查询过程中连接数据库失败（每查询一次，连接一次数据库模式），请问如何解决

**Comment by sangshuduo** [comment]
@zyl66 请提供一下具体失败错误信息和包含服务端和客户端的 log，最好修改 debugFlag 为 135 。谢谢！

**Comment by sangshuduo** [comment]
@zyl66  如果没有更多信息，我先暂时关闭，提供更多信息后我们再看
