### ISSUE TITLE
taos2.0 data lost even not expired?

### ISSUE THREAD

**Issue by zyl66** [taosdata/TDengine#4315]
taos2.0在建库时，表数据的保存时间设置为7天，发现有些表数据保存成功后的第4天时，t1是通过超表创建成功，经sql核查有t1表，执行select * from t1，提示t1表不存在，请指教，谢谢

**Comment by sangshuduo** [comment]
@zyl66 可以描述的更详细些吗？具体的版本号？单机部署还是集群部署？执行的SQL具体语句。谢谢！

**Comment by sangshuduo** [comment]
@zyl66 如果没有更多信息我先暂时关闭
