### ISSUE TITLE
2.0.8.x 版本升级提示

### ISSUE THREAD

**Issue by hjxilinx** [taosdata/TDengine#4317]
**2.0.8.x 版本升级提示**
最新发布的版本 2.0.8.x 在 driver 层更改了读取数据的方式，所以使用 Python 和 JDBC 的应用需要同步升级相关的 Python 和 JDBC 连接器到最新版本（JDBC 2.0.12及以上， Python ），否则启动应用会报告错误。

1. 升级 JDBC 版本方式，更新 maven 文件信息如下：

```
<!-- https://mvnrepository.com/artifact/com.taosdata.jdbc/taos-jdbcdriver -->
<dependency>
    <groupId>com.taosdata.jdbc</groupId>
    <artifactId>taos-jdbcdriver</artifactId>
    <version>2.0.12</version>
</dependency>
```

2. 升级 Python 连接器的方式：
卸载之前安装的驱动：`pip3 uninstall taos`
安装新驱动，安装启动的方式参见官方文档 [Python-Connector](https://www.taosdata.com/cn/documentation/connector/#Python-Connector) 使用说明

**Comment by PascalMing** [comment]
能发布每次升级修正的Bug和新增功能列表不？

**Comment by sangshuduo** [comment]
https://github.com/taosdata/TDengine/releases/tag/ver-2.0.8.0

**Comment by WtyFile** [comment]
python在windows和linux的不能做成whl直接pip吗
