### ISSUE TITLE
Hope to support global variable in the grafana plugin in the future

### ISSUE THREAD

**Issue by denwork** [taosdata/TDengine#432]
在添加完Variables全局变量后，无法在INPUT SQL中引用。
select avg(f_usage_idle) from zabbix.cpu_usage WHERE t_host=$node and ts>=$from and ts<$to interval($interval)

**Comment by guanshengliang** [comment]
This is indeed a problem, we will processe it in the near future.

**Comment by guanshengliang** [comment]
This issue has been resolved, the code is on the develop branch, you can download and use

**Comment by Jerry217** [comment]
> 
> 
> This issue has been resolved, the code is on the develop branch, you can download and use

could you please write down the download link? I can't find it, thank you!

**Comment by sangshuduo** [comment]
@Jerry217 

https://github.com/taosdata/grafanaplugin

**Comment by Jerry217** [comment]
> 
> 
> @Jerry217 
> 
> https://github.com/taosdata/grafanaplugin

thank you very much for quickly reply! my mistake, actially,my mean is this feature below.  
anyone solve this ? https://github.com/taosdata/grafanaplugin/issues/11

**Comment by Jerry217** [comment]
> 
> 
> @Jerry217 
> 
> https://github.com/taosdata/grafanaplugin

Template downlist menu
![QQ截图20210115192456](https://user-images.githubusercontent.com/41631882/104720472-fcd50900-5767-11eb-8138-78c48607a4e2.png)

**Comment by Jerry217** [comment]
> 
> 
> > @Jerry217
> > https://github.com/taosdata/grafanaplugin
> 
> Template downlist menu
> ![QQ截图20210115192456](https://user-images.githubusercontent.com/41631882/104720472-fcd50900-5767-11eb-8138-78c48607a4e2.png)

Can't set dashboard menu list,got error
**Templating
Template variables could not be initialized: e.metricFindQuery is not a function**

**Comment by huoshuaibing** [comment]
@sangshuduo
