### ISSUE TITLE
install TDengine-server has error

### ISSUE THREAD

**Issue by eyeshot** [taosdata/TDengine#4322]
I install  TDengine with TDengine-server-2.0.8.0-Linux-x64.rpm:
rpm -ivh TDengine-server-2.0.8.0-Linux-x64.rpm , it tips:
error: Failed dependencies:
	libc.so.6(GLIBC_2.14)(64bit) is needed by tdengine-2.0.8.0-3.x86_64
but my  CentOS6.8 has GLIBC_2.14, 
[root@2o5fkeswoq9xsxxj software]# strings /lib64/libc.so.6 | grep GLIBC
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_2.13
GLIBC_2.14
GLIBC_PRIVATE.
[root@2o5fkeswoq9xsxxj lib64]# ll libc.so.6 
lrwxrwxrwx 1 root root 12 Nov 23 10:06 libc.so.6 -> libc-2.14.so

what is the problem? thanks.

**Comment by plum-lihui** [comment]
We verify it on centos7, please upgrade to centos7。thanks！
