### ISSUE TITLE
Windows CLI: can't tell cli options -p and -P 

### ISSUE THREAD

**Issue by longyn** [taosdata/TDengine#4324]
**Bug Description**
Use -p (password) and -P (Port) at the same time.
``` bash
taos -P 6030 -p 123456
```
**Get wrong options**

**To Reproduce**

**Expected Behavior**
Can input -P and -p together or long options support.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10 ]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by plum-lihui** [comment]
-p （password不能直接输入，只能先 写上 -p，然后回车，有提示输入密码）。
![image](https://user-images.githubusercontent.com/52318143/102971275-0f2aa100-4534-11eb-93ea-e5cbd1a15ca0.png)
