### ISSUE TITLE
TDB ERROR vgId:10 invalid file v10f3320.h_back_1606175605943 exists, ignore it

### ISSUE THREAD

**Issue by quchunhui** [taosdata/TDengine#4325]
**Bug Description**
模拟程序批量写入数据，其中一个节点挂掉，一直启动不起来，systemctl status taosd显示一直starting状态，日志中提示
TDB ERROR vgId:10 invalid file v10f3320.h_back_1606175605943 exists, ignore it

**Screenshots**
![image](https://user-images.githubusercontent.com/18110478/100030901-8256cf80-2e2f-11eb-948b-c97756cd57be.png)
![image](https://user-images.githubusercontent.com/18110478/100030805-4f144080-2e2f-11eb-8f31-ec5ecdf00417.png)

**Environment (please complete the following information):**
 - OS: CentOS 8.0
 - Memory, CPU, current Disk Space：24核，64G内存
 - TDengine Version：2.0.8.0

**Comment by quchunhui** [comment]
分片：1
cache：16
block：12
超级表：1
子表：5000
数据库keep：3650
数据库days：5

**Comment by quchunhui** [comment]
补充一点：
由于遇到了[#4319](https://github.com/taosdata/TDengine/issues/4319)这个问题，集群有2.0.7.0升级到了2.0.8.0
升级的顺序是这样的：
1、systemctl stop taosd
2、删除data目录
3、卸载2.0.7.0
4、安装2.0.8.0
在重新安装之后，虽然已经彻底删除掉了数据文件，不过在系统启动之后，通过命令（select last_row(*) from supertable）查看最后一条数据，发现却是删除之前的记录。

**Comment by yushan-yaojin** [comment]
> 补充一点：
> 由于遇到了[#4319](https://github.com/taosdata/TDengine/issues/4319)这个问题，集群有2.0.7.0升级到了2.0.8.0
> 升级的顺序是这样的：
> 1、systemctl stop taosd
> 2、删除data目录
> 3、卸载2.0.7.0
> 4、安装2.0.8.0
> 在重新安装之后，虽然已经彻底删除掉了数据文件，不过在系统启动之后，通过命令（select last_row(*) from supertable）查看最后一条数据，发现却是删除之前的记录。

你好，可以看下我报的那个bug吗，bug编码:4326

**Comment by quchunhui** [comment]
【模拟程序地址】
https://github.com/quchunhui/java-demo/blob/master/tdengine/src/main/java/com/rexel/tdengine/api/MockData.java
【参数说明】
参数1：产品数
参数2：设备数
参数3：测点数：
参数4：模拟开始时间
参数5：模拟结束时间：
参数6：采集频率（秒）
【启动命令样例】
如5000个测点（1产品*50设备*100测点，模拟2015至2017年，采集频率为5s/次）的命令：
nohup java -classpath /home/radmin/package/tdengine-1.0-jar-with-dependencies.jar com.rexel.tdengine.api.MockData 1 50 100 "2015-02-01 00:00:00.000" "2017-12-31 23:59:59.999" 5 >/home/radmin/package/java_mock_thread.log &
【TDengine地址】
https://github.com/quchunhui/java-demo/blob/master/tdengine/src/main/java/com/rexel/tdengine/utils/TdUtils.java
这个里面写的固定的地址，修改这里就可以。

**Comment by hzcheng** [comment]
此问题已在最新的develop代码修复，您可以拉去最新代码来测试。

**Comment by quchunhui** [comment]
在新版本测试，如有问题在起新票
