### ISSUE TITLE
genFinalResWithoutFill: Assertion `overflow < pRes->numOfRows' failed.`

### ISSUE THREAD

**Issue by yushan-yaojin** [taosdata/TDengine#4326]
windows客户端报错：
![image](https://user-images.githubusercontent.com/23131866/100033685-a0273300-2e35-11eb-88ed-54b0bdf83c16.png)

linux客户端报错：
`java: /home/ubuntu/ver_release_workspace/TDinternal/community/src/client/src/tscLocalMerge.c:879: genFinalResWithoutFill: Assertion `overflow < pRes->numOfRows' failed.`

今天忽然报这个错，这是什么原因了

**Comment by localvar** [comment]
请提供下相关日志，软件的版本信息，以及出现问题的场景（在进行什么操作，所执行的语句是什么），谢谢！

**Comment by yushan-yaojin** [comment]
2.0.7版本，刚升级到2.0.8版本也出现这个问题了，查询sql都是很简单的，以下是mapp文件，都特别简单的查询，我再检查下我的sql是不是有问题

![image](https://user-images.githubusercontent.com/23131866/100039768-e5049700-2e40-11eb-9358-fda98e76aa66.png)



`<sql id="infoSql">
        <where>
            <if test="unitNo!=null and unitNo!=''">
                and unit_no=#{unitNo}
            </if>
            <if test="deviceType!=null">
                and device_type=#{deviceType}
            </if>
            <if test="siteId!=null and siteId!=''">
                and site_id =#{siteId}
            </if>
            <if test="defaultId!=null and defaultId!=''">
                and ${defaultId}
            </if>
            <if test="dataType!=null and dataType !=''">
                and data_type=#{dataType}
            </if>
            <if test="deviceId!=null and deviceId!=''">
                and device_id=#{deviceId}
            </if>
        </where>
    </sql>

    <sql id="limit_sql">
        <if test="limit!=null">
            limit ${limit}
        </if>
        <if test="offset!=null">
            offset ${offset}
        </if>
    </sql>

    <select id="listInfo" resultType="com.cn.web.shuizhi.vo.DeviceInfoExt">
        select
        *
        from data_log
        <include refid="infoSql"/>
        order by id desc
        <include refid="limit_sql"/>
    </select>

    <select id="listInfo_COUNT1" resultType="java.lang.Long">
        select count(id) from data_log
        <include refid="infoSql"/>
    </select>

    <sql id="errorSearchSql">
        <where>
            <if test="unitNo!=null and unitNo !=''">
                and unit_no=#{unitNo}
            </if>
            <if test="siteId!=null and siteId !=''">
                and site_id=#{siteId}
            </if>
            <if test="errorTxt!=null and errorTxt!=''">
                and error_txt=#{errorTxt}
            </if>
            <if test="start!=null and start!=''">
                and time>=#{start}
            </if>
            <if test="stop!=null and stop!=''">
                and time &lt;=#{stop}
            </if>
            <if test="defaultId!=null and defaultId!=''">
                and ${defaultId}
            </if>
            <if test="deviceId!=null and deviceId!=''">
                and device_id=#{deviceId}
            </if>
        </where>
    </sql>

    <select id="listError" resultType="com.cn.web.shuizhi.vo.DeviceErrorExt">
        select
        *
        from data_error
        <include refid="errorSearchSql"/>
        order by id desc
        <include refid="limit_sql"/>
    </select>
    <select id="listError_COUNT1" resultType="java.lang.Long">
        select
        count(id)
        from data_error
        <include refid="errorSearchSql"/>
    </select>

    <select id="listErrorOk" resultType="com.cn.web.shuizhi.vo.DeviceErrorExt">
        select
        *
        from data_error_ok
        <include refid="errorSearchSql"/>
        order by id desc
        <include refid="limit_sql"/>
    </select>
    <select id="listErrorOk_COUNT1" resultType="java.lang.Long">
        select
        count(id)
        from data_error_ok
        <include refid="errorSearchSql"/>
    </select>

    <select id="findErrorOk" resultType="com.cn.iot.log.DeviceErrorEntity">
        select * from data_error_ok where link_id=#{linkId}
    </select>

    <select id="findError" resultType="com.cn.iot.log.DeviceErrorEntity">
        select * from data_error where link_id=#{linkId}
    </select>`

**Comment by yushan-yaojin** [comment]
这个bug再没出现，好郁闷，都点了好多次，再也没出现。这一个月一直很稳定，忽然出现的，然后，大约10点40后再没出现过。这边没做任何操作。
会不会跟taos数据库 服务器有啥关系，这是内存占用。
![image](https://user-images.githubusercontent.com/23131866/100058675-b26c9580-2e64-11eb-9d36-b441b391e948.png)

**Comment by localvar** [comment]
谢谢提供信息，具体原因目前还不好判断，我们后面会分析解决。

**Comment by fenghua1997** [comment]
This issue was closed because it has been inactive for too many days.
