### ISSUE TITLE
乱序插入是否对性能有影响

### ISSUE THREAD

**Issue by nieyuanqing** [taosdata/TDengine#4328]
从TDengine的文档上提到：时序数据：存放于vnode里，由data、head和last三个文件组成，数据量大，查询量取决于应用场景。容许乱序写入，但暂时不支持删除和更新操作。  

问题：
是否表示后续再补充之前时间的数据记录，也是可以的？对性能是否有影响？

**Comment by localvar** [comment]
允许乱序插入，性能会有一定的下降。

**Comment by nieyuanqing** [comment]
性能下降严重么？

**Comment by nieyuanqing** [comment]
性能下将主要是对哪些方面有影响？

**Comment by sangshuduo** [comment]
写入性能可能下降10%
