### ISSUE TITLE
Failed to insert data when create database using precision us

### ISSUE THREAD

**Issue by cztong** [taosdata/TDengine#433]
创建微秒级数据库
![image](https://user-images.githubusercontent.com/7899882/63761963-96421780-c8f4-11e9-80bc-6685e7a7e1bd.png)
![image](https://user-images.githubusercontent.com/7899882/63761998-a6f28d80-c8f4-11e9-8b17-1df2f0dc2365.png)
如果时间戳为‘0’，会使用系统时间，
![image](https://user-images.githubusercontent.com/7899882/63762077-cee1f100-c8f4-11e9-8f4a-80b07f79e5df.png)
![image](https://user-images.githubusercontent.com/7899882/63762112-dacdb300-c8f4-11e9-9cdf-aaa651f19f94.png)
20条数据只有2条微秒数据成功插入，18条失败。
![image](https://user-images.githubusercontent.com/7899882/63762227-0d77ab80-c8f5-11e9-8db6-2ec4d7b2d663.png)

**Comment by fangpanpan** [comment]
按照您的程序，你拼接的sql 语句是不是类似于insert into table_name values (0, int)(0,int)(0,int)? 如果这样的话，这一条只会插入一条数据，因为三条记录里的时间戳是同一时间的。

**Comment by guanshengliang** [comment]
不要在批量语句中使用0
因为SQL解析非常快，可能是20条记录生成的时间戳都是相同的，所以只能写入很小一部分
