### ISSUE TITLE
questions for creating database with parameters

### ISSUE THREAD

**Issue by trdmm** [taosdata/TDengine#4331]
还没开始用,只是在虚拟机中用docker中搭了个集群,如有什么不对的,望理解!!!

**FAQ**第三问[技术博客](https://www.taosdata.com/blog/2019/12/03/965.html)
其中博客中提到的和文档中提到好像不一样

1. 博客中说 `tables` --每个vnode中允许创建表的最大值.通常在4-20000之间.
但是我看**taos.cfg**配置文件中`maxTablesPerVnode`默认为100W.

2. 博客下面所说的`maxTables`默认65W,在**taos.cfg**中没这个配置项,而且不知道这个跟上面的100W的关系.

3. `cache`参数,博客中单位是**字节**,文档中是**MB**.不知道哪个为准?

另外,如果博客内容过时了,那么新的解决办法是什么?  :D

![博客.png](https://i.loli.net/2020/11/24/OXtjh8bTNBSPxuo.png)
![服务端配置.png](https://i.loli.net/2020/11/24/mWlz1uETwkASsxd.png)

**Comment by xiaopingcs** [comment]
你好，欢迎提问。这个博客的内容确实过时了。 
1. 现在maxTablesPerVnode默认值是100万
2. 我们已经没有maxTables, ablocks, tblocks, tables参数
3. cache现在默认值是16MB

由于我们迭代较快，我们所有新的文档都会在https://www.taosdata.com/cn/documentation/ 这个页面更新，请以这个页面的内容为准，其他比较久远的博客只能当做参考。

**Comment by trdmm** [comment]
> 你好，欢迎提问。这个博客的内容确实过时了。
> 
> 1. 现在maxTablesPerVnode默认值是100万
> 2. 我们已经没有maxTables, ablocks, tblocks, tables参数
> 3. cache现在默认值是16MB
> 
> 由于我们迭代较快，我们所有新的文档都会在https://www.taosdata.com/cn/documentation/ 这个页面更新，请以这个页面的内容为准，其他比较久远的博客只能当做参考。

好的,谢谢

这样的话,是不是除了`maxTablesPerVnode`之外,就没其他限制数量的了?
不够的话就直接加内存就行了吧?

**Comment by xiaopingcs** [comment]
> 

不好意思，忘记回复了。除了 maxTablesPerVnode， 我们还有 maxVgroupsPerDb 是用来控制 vnode 的数量的。
这个问题我先关闭了，如果还有问题麻烦开一个新的issue，我们正确及时回复。
