### ISSUE TITLE
long text query

### ISSUE THREAD

**Issue by xujiesh0510** [taosdata/TDengine#4334]
版本 2.0.8
使用restful接口，针对 超级表的tag的过滤查询有问题，当筛选条件是长文本的时候查询不到结果

select *  from stableaaas where taga ='7_测试监控变量名字超长测试监控变量名字超长测试监控变量名字超长测试监控变量名字超长';

**Comment by xiaopingcs** [comment]
你好，我这边使用你的例子curl了一下是没有问题的：
root@develop:~/TDengine/debug/build/bin# curl -H 'Authorization: Basic cm9vdDp0YW9zZGF0YQ==' -d "select * from db.longtag where tg='7_测试监控变量名字超长测试监控变量名字超长测试监控变量名字超长测试监控变量名字超长'" 127.0.0.1:6041/rest/sql
{"status":"succ","head":["ts","val","tg"],"data":[["2020-11-25 13:44:51.719",1,"7_测试监控变量名字超长测试监控变量名字超长测试监控变量名字超长测试监控变量名字超长"]],"rows":1}

请问你的表结构是什么样的？
