### ISSUE TITLE
is the insertion limit of records 2841 in one table?

### ISSUE THREAD

**Issue by cztong** [taosdata/TDengine#434]
文档里说明可以单表插入多条记录；
![image](https://user-images.githubusercontent.com/7899882/63820864-77d42e80-c97d-11e9-9120-673a8f5431cf.png)
当我insert into t0 values(1566959764160911,2842)(1566959764160934,2843)(1566959764160944,2844)... values数量为2841条时成功插入数据库，2842条就报TDengine Error: invalid SQL: invalid SQL:
![image](https://user-images.githubusercontent.com/7899882/63821509-d69aa780-c97f-11e9-93ae-6c69556ef410.png)
请问，这个values上限就是2841吗？还是有参数可以调整？

**Comment by guanshengliang** [comment]
SQL语句最长不能超过64000，您需要限制SQL语句的长度
