### ISSUE TITLE
如何查询 某段时间段内变量值发生变化的时间点?

### ISSUE THREAD

**Issue by Luokun2016** [taosdata/TDengine#4340]
**查询变量值发生变化的时间点**
table中存储的int类型变量，需要查找24h 内变量值持续的时间段。
目前table中是，每秒存一次值。
如：
|  ts| val  |
|  ----  | ----  |
| 2020-11-25 01:01:00  | 1 |
| 2020-11-25 01:01:02  | 1 |
| 2020-11-25 01:01:03  | 1 |
| ...  | ... |
| 2020-11-25 01:01:10  | 1 |
| 2020-11-25 01:01:11  | 2 |
| ...  | ... |

**需要的查询结果如下**：
变量值：1   时间段：2020-11-25 01:01:00 -- 202011-25 01:10:00
变量值：2   时间段：2020-11-25 01:10:01 -- 202011-25 01:30:00
变量值：1   时间段：2020-11-25 01:30:01 -- 202011-25 01:40:00

**Comment by Luokun2016** [comment]
查找初始值
select ts, val from fclouddevc.tb4073913875454492672 where ts >= NOW - 24h limit 1
[
	"2020-11-24 08:58:00.000",
	333.000000000
]

查找下一次变化值
select ts, val from fclouddevc.tb4073913875454492672 where ts >= '2020-11-24 08:58:00.000' and val != 333  limit 1
[
	"2020-11-24 12:34:00.000",
	335.000000000
]

select ts, val from fclouddevc.tb4073913875454492672 where ts >= '2020-11-24 12:34:00.000' and val != 335  limit 1
[
	"2020-11-24 12:35:00.000",
	445.000000000
]

select ts, val from fclouddevc.tb4073913875454492672 where ts >= '2020-11-24 12:35:00.000' and val != 445  limit 1
[
	"2020-11-24 12:38:00.000",
	555.000000000
]

select ts, val from fclouddevc.tb4073913875454492672 where ts >= '2020-11-24 12:38:00.000' and val != 555  limit 1
[
	"2020-11-24 12:48:00.000",
	665.000000000
]

**Comment by Luokun2016** [comment]
我是用循环查询方法，还有没有其他好的方法。
查找初始值
select ts, val from fclouddevc.tb4073913875454492672 where ts >= NOW - 24h limit 1
[
	"2020-11-24 08:58:00.000",
	333.000000000
]

查找下一次变化值
select ts, val from fclouddevc.tb4073913875454492672 where ts >= '2020-11-24 08:58:00.000' and val != 333  limit 1
[
	"2020-11-24 12:34:00.000",
	335.000000000
]

select ts, val from fclouddevc.tb4073913875454492672 where ts >= '2020-11-24 12:34:00.000' and val != 335  limit 1
[
	"2020-11-24 12:35:00.000",
	445.000000000
]

select ts, val from fclouddevc.tb4073913875454492672 where ts >= '2020-11-24 12:35:00.000' and val != 445  limit 1
[
	"2020-11-24 12:38:00.000",
	555.000000000
]

select ts, val from fclouddevc.tb4073913875454492672 where ts >= '2020-11-24 12:38:00.000' and val != 555  limit 1
[
	"2020-11-24 12:48:00.000",
	665.000000000
]

**Comment by xiaopingcs** [comment]
@localvar 我们的TDengine alert可以实现这个吗？

**Comment by localvar** [comment]
> @localvar 我们的TDengine alert可以实现这个吗？

不能，alert是周期性执行，对整个周期内的数据执行统一的计算，而不能用来找到某条确定的记录。
这是一个功能需求，需要增加一个专用的函数才行。

**Comment by PascalMing** [comment]
为什么不直接存变化量呢？
然后可以用TDengine函数直接获取指定时间点数据。

**Comment by Luokun2016** [comment]
> 为什么不直接存变化量呢？
> 然后可以用TDengine函数直接获取指定时间点数据。

数据采集，不仅仅只是变换才采集。也有每分钟采集的数据。

**Comment by Luokun2016** [comment]
tdengine支持查询值变化的时间点吗？或者统计不同值持续时间吗？

**Comment by fenghua1997** [comment]
This issue was closed because it has been inactive for too many days.
