### ISSUE TITLE
单机扩展集群

### ISSUE THREAD

**Issue by nieyuanqing** [taosdata/TDengine#4341]
Hi，
先单机实例（1个DNODE），等到数据一定规模后，然后online扩展成集群（3个DNOE），支持么？
数据副本能够从1个升级成3个么？

**Comment by xiaopingcs** [comment]
这个是支持的，但是要保证每一个新添加的节点没有数据

**Comment by nieyuanqing** [comment]
好的，多谢，关闭了。
