### ISSUE TITLE
the righ parenthesis is missing in the result field name

### ISSUE THREAD

**Issue by machine-w** [taosdata/TDengine#4342]
以这样的方式访问restful api的话：
curl -u root:taosdata -d 'SELECT (c1 + (c3 * c2)) FROM "test01.d3"'  ip:6041/rest/sql

返回：

{"status":"succ","head":["c1 + (c3 * c2"],"data":xxxx}

head:中的信息缺少一半括号，如果把括号放到前面也一样。。。

**Comment by liuyq-617** [comment]
麻烦提供一下您的数据库版本号，操作系统等信息。否则是无法帮您准确定位问题的

**Comment by machine-w** [comment]
TDengine-server-2.0.6.0-Linux-x64.rpm

centos7

**Comment by liuyq-617** [comment]
请升级到2.0.8.0

**Comment by machine-w** [comment]
升级到2.0.8.0，问题依旧

**Comment by hjxilinx** [comment]
表达式中的如果有括号会导致括号丢失，这个是2.0.8.x都有的问题。本周将要发布的版本2.0.9.x已经修复这个问题。
