### ISSUE TITLE
diff does not support simultaneous query of multiple columns

### ISSUE THREAD

**Issue by machine-w** [taosdata/TDengine#4344]
运行：
curl -u root:taosdata -d 'SELECT DIFF(c1),DIFF(c3) FROM "test01.d3"' localhost:6041/rest/sql
返回：
{"status":"error","code":512,"desc":"invalid SQL: invalid SQL: functions can not be mixed up"}

**Comment by Aries-Lee1991** [comment]
please add the version info.

**Comment by machine-w** [comment]
TDengine-server-2.0.6.0-Linux-x64.rpm
centos7

**Comment by hjxilinx** [comment]
diff 不支持多个列，只能单个列。因为 diff 函数要返回相关的 timestamp。
