### ISSUE TITLE
interval start(end) time of query range required or time range too large

### ISSUE THREAD

**Issue by machine-w** [taosdata/TDengine#4347]
run:

curl -u root:taosdata -d 'SELECT AVG(c1) AS aa, FIRST(c1) AS bb FROM "taos_test.meter1"  WHERE ts > ("2020-11-24 21:56:10.965872") INTERVAL(10m) FILL(PREV) "  GROUP BY des' localhost:6041/rest/sql

error:

invalid SQL: start(end) time of query range required or time range too large

**Comment by Aries-Lee1991** [comment]
please add the log and the version info.

**Comment by localvar** [comment]
there are superfluous symbols in the statement, are they typo?
please try below command and get back to us if the issue is still there:

```
curl -u root:taosdata -d 'SELECT AVG(c1) AS aa, FIRST(c1) AS bb FROM taos_test.meter1 WHERE ts > "2020-11-24 21:56:10.965872" INTERVAL(10m) FILL(PREV) GROUP BY des' localhost:6041/rest/sql
```

**Comment by machine-w** [comment]
TDengine-server-2.0.6.0-Linux-x64.rpm
centos7

去掉多余的括号和引号，结果一样
curl -u root:taosdata -d 'SELECT AVG(c1) AS aa, FIRST(c1) AS bb FROM taos_test.meter1 WHERE ts > "2020-11-24 21:56:10.965872" INTERVAL(10m) FILL(PREV) GROUP BY des' localhost:6041/rest/sql

**Comment by localvar** [comment]
这个结果是正常的，在使用 `fill`时，必须同时指定查询的开始和结束时间。

**Comment by monkeyKinn** [comment]
> 这个结果是正常的，在使用 `fill`时，必须同时指定查询的开始和结束时间。
请教一下

建表sql:
CREATE TABLE qtch_bms_cloud.point_value (
	create_time TIMESTAMP NOT NULL,
	point_value NCHAR,
	origin_time TIMESTAMP,
	device_id NCHAR,
	point_id NCHAR,
	CONSTRAINT create_time PRIMARY KEY (create_time)
);
以下查询sql:
SELECT
	create_time,
	point_value,
	origin_time
FROM
	qtch_bms_cloud.point_value
WHERE
	device_id = '10114'
	AND point_id = '1762305700492509185'
	AND origin_time >= '2024-04-01 10:13:28' AND origin_time <='2024-04-02 10:13:28'
INTERVAL(1h)
FILL(PREV)

报错:desc: Start(end) time of query range required or time range too large
