### ISSUE TITLE
order by v2.0.7.0

### ISSUE THREAD

**Issue by sim-wangyan** [taosdata/TDengine#4348]
order by ts : 
DB error: No such file or directory
order by tag:
DB error: invalid SQL: only support order by primary timestamp or queried column

What is the meaning of the error?

**Comment by Aries-Lee1991** [comment]
please add the version and the log info.

**Comment by yihaoDeng** [comment]
@sim-wangyan

**Comment by sim-wangyan** [comment]
版本：v2.0.7.0
LOG: DB error: No such file or directory 和 DB error: invalid SQL: only support order by primary timestamp or queried column

**Comment by sim-wangyan** [comment]
taos> select count(id) from t_heat_supply where city = "北京市" group by zone;

DB error: No such file or directory；

各种问题
