### ISSUE TITLE
使用http接口执行了语句后服务死了

### ISSUE THREAD

**Issue by mijjjj** [taosdata/TDengine#435]
**Bug Description**

**To Reproduce**
1.使用http接口发送查询语句 select * from taiyuan_db.equipmentstatus       order by ts desc  limit 50 OFFSET 0

**Expected Behavior**
返回超时，查询服务器显示服务关闭

**Screenshots**
![TIM截图20190828104129](https://user-images.githubusercontent.com/37797122/63821717-95ef5e00-c980-11e9-99c3-c5ee4bd766fd.png)

**Environment (please complete the following information):**
 - OS: [e.g. ubuntu 18.04]
 - TDengine Version [e.g. 1.6.1.6]

**Additional Context**

**Comment by guanshengliang** [comment]
可以将生成测试数据的程序贴出来，以便我们复现问题

**Comment by plum-lihui** [comment]
已经远程定位，多谢支持！
我们修复bug后会发布新的版本。
