### ISSUE TITLE
TDengine Error: more dnodes are needed

### ISSUE THREAD

**Issue by hiei17** [taosdata/TDengine#436]
create到第49000个表的时候报错
TDengine Error: more dnodes are needed

空间充足

另一个问题我也看了, 我vim /etc/taos/taos.cfg
看了有什么配置可以改的 改了长得像的 maxTables ,没有用 请问 该改什么配置? 只能加核吗
我们大概需要二百个表(二百万个设备)

**Comment by fangpanpan** [comment]
按照您的配置您大概会有49个vnode可以用，默认每个vnode上建1000张表。 您可以在创建database时用"create database db tables **", ** 就是每个vnode上建的表数（例如，2000000/49）。不过实际能建表数还要受内存限制，不知道您的服务器配置怎么样？

**Comment by hiei17** [comment]
create database db tables 2000000;
create database db tables 2000000/49;

 都不行 TSDB error: invalid option

另外  除了白皮书和 https://www.taosdata.com/cn/documentation/ 还有什么可以看的 吗
您说的好像在里面都没见过

**Comment by fangpanpan** [comment]
您可以看看[https://www.taosdata.com/cn/documentation/administrator/#客户端配置](url)里服务端配置里的那些参数，里面有‘tables’这个参数的说明。“2000000/49” 是指将总表数除以vnode数得到每vnode里的建表数（tables），不是说直接写成“2000000/49”。

**Comment by hiei17** [comment]
这个我调过 开始调太大了
报错
 ERROR UTL config option:tables, input value:2000000, out of range[4.000000, 220000.000000], use default value:1000
我调成  220000 
![image](https://user-images.githubusercontent.com/10015375/63908119-935c3980-ca50-11e9-99d6-9b47d5f7de0d.png)
没报错
但是建库都不让我建了
![image](https://user-images.githubusercontent.com/10015375/63908095-73c51100-ca50-11e9-9870-918ac1168dfb.png)

**Comment by fangpanpan** [comment]
> 这个我调过 开始调太大了
> 报错
> ERROR UTL config option:tables, input value:2000000, out of range[4.000000, 220000.000000], use default value:1000
> 我调成 220000
> ![image](https://user-images.githubusercontent.com/10015375/63908119-935c3980-ca50-11e9-99d6-9b47d5f7de0d.png)
> 没报错
> 但是建库都不让我建了
> ![image](https://user-images.githubusercontent.com/10015375/63908095-73c51100-ca50-11e9-9870-918ac1168dfb.png)

您能说一下报的什么错误吗？

**Comment by hjxilinx** [comment]
您好，每个virtual node中的表的数量除了硬编码的最大限制220000以外，还受限于每个virtual node系统允许的配置的cacheblock，系统中默认允许的cacheblock数量的最大是409600个block，默认每个表有4个缓存块，所以最大值实际上是409600/4 = 102400 个表。
这个错误信息的具体内容您可以在/var/log/taosdlog.1/0中看到。
建议您配置每个virtual node中包含表数量50000。这样一共保证virtual node的数量在50个左右即可。

**Comment by hiei17** [comment]
我用把taos.cfg的tables配置注掉
 create database db tables 50000; 建库成功
但是还是不行 
报错TDengine Error: sdb error 这次只到1847张表
我是在虚拟机上试验的 8G内存 4cpu 数据目录挂载硬盘300g

**Comment by hjxilinx** [comment]
如果您的日志的配置打开了以后，请将日志发送到hjliao@taosdata.com，便于我们分析。谢谢！

**Comment by gihugui** [comment]
我今天也是遇到了相同的问题，。求如何解决呀

**Comment by fangpanpan** [comment]
> 
> 
> 我今天也是遇到了相同的问题，。求如何解决呀

请问您的问题具体是怎样的？以及您进行了哪些操作，有设置tables 这个配置项吗？

**Comment by fangpanpan** [comment]
> 
> 
> > > 我今天也是遇到了相同的问题。求如何解决呀
> > 
> > 
> > 请问您的问题具体是怎样的？以及您进行了什么操作，有设置表这个配置项吗？
> 
> 报错：Save , error : more dnodes are needed 然后我修改了taos.cfg 里面tables 设置了一个10W ，重启服务，并没有什么用。 我现在准备删除数据库，再创建试试

一般来说您至少有50个vnode，现在您每个vnode里建10W张表，那么您打算总共建500W张表？

**Comment by gihugui** [comment]
![image](https://user-images.githubusercontent.com/43509035/65561724-18fed680-df76-11e9-8704-16c340da042b.png)

红色标记的这两个数据库，都插入不了新的表。 只有删除里面的表才能插入成功

**Comment by gihugui** [comment]
是这样子的，这两个数据库都插入不了新表。。。只有我删除里面的一张表后才能插入新的。这个机器是4核
设置配置没有用。不知道如何解决








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "fangpanpan"<notifications@github.com&gt;; 
发送时间: 2019年9月24日(星期二) 晚上9:46
收件人: "taosdata/TDengine"<TDengine@noreply.github.com&gt;; 
抄送: "胡桂"<812376073@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [taosdata/TDengine] TDengine Error: more dnodes are needed (#436)



   
我今天也是遇到了相同的问题。求如何解决呀
  
请问您的问题具体是怎样的？以及您进行了什么操作，有设置表这个配置项吗？
  
报错：Save , error : more dnodes are needed 然后我修改了taos.cfg 里面tables 设置了一个10W ，重启服务，并没有什么用。 我现在准备删除数据库，再创建试试
  
一般来说您至少有50个vnode，现在您每个vnode里建10W张表，那么您打算总共建500W张表？

**Comment by gihugui** [comment]
![image](https://user-images.githubusercontent.com/43509035/65561801-60856280-df76-11e9-8b80-d4bde2ba525d.png)

这个数据库对应的容量好像只有8000 ，我删除里面的N个表后，才能新插入N长表。给我的感觉就最多8000了

**Comment by fangpanpan** [comment]
4核的话，那么默认配置总共有50个vnodes， 您画红线的两个数据库已经占满了38+8=46个vnodes， 然后其他四个数据库占了4个vnodes， 所以对于画红线的两个数据库您已经没有多余的vnodes可以用来建表了。

**Comment by gihugui** [comment]
好的，我知道了。要升级硬件。。感谢回答

**Comment by gihugui** [comment]
我测试一下先

**Comment by sudo168** [comment]
@fangpanpan 4核的话，那么默认配置总共有50个vnodes。这个在配置文件里对应的是哪个？我看numOfVnodesPerCore  默认的是8。按照这个4核的话只有32个vnodes啊。是我理解错了还是？
