### ISSUE TITLE
创建集群加入第三个节点失败

### ISSUE THREAD

**Issue by nieyuanqing** [taosdata/TDengine#4363]
Hi，
集群一共三个节点，创建第一个节点成功，创建第二个节点并加入成功，但是创建第三个节点失败，日志信息如下：
==================================================
                new log file
==================================================
11/26 18:09:34.612288 0x7f6c4bb15740 DND start to initialize TDengine
11/26 18:09:34.612414 0x7f6c4bb15740 DND dnode storage is initialized at /opt/soft/taos/data/dnode
11/26 18:09:34.612443 0x7f6c4bb15740 DND failed to read /opt/soft/taos/data/dnode/dnodeCfg.json, file not exist
11/26 18:09:34.612459 0x7f6c4bb15740 DND dnode cfg is initialized
11/26 18:09:34.612532 0x7f6c4bb15740 DND failed to read /opt/soft/taos/data/dnode/dnodeEps.json, file not exist
11/26 18:09:34.612550 0x7f6c4bb15740 DND dnode eps is initialized
11/26 18:09:34.612565 0x7f6c4bb15740 UTL localEp is: h3.bigdata.bi:6030
11/26 18:09:34.613540 0x7f6c4bb15740 UTL WARN timezone not configured, set to system default: (CST, +0800)
11/26 18:09:34.613658 0x7f6c4bb15740 UTL WARN locale not configured, set to system default:zh_CN.UTF-8
11/26 18:09:34.613680 0x7f6c4bb15740 UTL WARN charset not configured, set to system default:UTF-8
11/26 18:09:34.613761 0x7f6c4bb15740 UTL    taos config & system info:
11/26 18:09:34.613800 0x7f6c4bb15740 UTL ==================================
11/26 18:09:34.613808 0x7f6c4bb15740 UTL  firstEp:                h2.bigdata.bi:6030
11/26 18:09:34.613815 0x7f6c4bb15740 UTL  secondEp:               h3.bigdata.bi:6030
11/26 18:09:34.613821 0x7f6c4bb15740 UTL  fqdn:                   h3.bigdata.bi
11/26 18:09:34.613827 0x7f6c4bb15740 UTL  serverPort:             6030
11/26 18:09:34.613834 0x7f6c4bb15740 UTL  configDir:              /opt/soft/taos/cfg
11/26 18:09:34.613840 0x7f6c4bb15740 UTL  logDir:                 /opt/soft/taos/log
11/26 18:09:34.613845 0x7f6c4bb15740 UTL  scriptDir:              /etc/taos
11/26 18:09:34.613851 0x7f6c4bb15740 UTL  dataDir:                /opt/soft/taos/data
11/26 18:09:34.613857 0x7f6c4bb15740 UTL  arbitrator:
11/26 18:09:34.613862 0x7f6c4bb15740 UTL  numOfThreadsPerCore:    1.000000
11/26 18:09:34.613897 0x7f6c4bb15740 UTL  numOfCommitThreads:     1
11/26 18:09:34.613903 0x7f6c4bb15740 UTL  ratioOfQueryThreads:    0.500000
11/26 18:09:34.613910 0x7f6c4bb15740 UTL  numOfMnodes:            3
11/26 18:09:34.613916 0x7f6c4bb15740 UTL  vnodeBak:               1
11/26 18:09:34.613927 0x7f6c4bb15740 UTL  telemetryReporting:     1
11/26 18:09:34.613933 0x7f6c4bb15740 UTL  balance:                1
11/26 18:09:34.613938 0x7f6c4bb15740 UTL  balanceInterval:        300
11/26 18:09:34.613944 0x7f6c4bb15740 UTL  role:                   0
11/26 18:09:34.613953 0x7f6c4bb15740 UTL  maxTmrCtrl:             512
11/26 18:09:34.613962 0x7f6c4bb15740 UTL  monitorInterval:        30(s)
11/26 18:09:34.613969 0x7f6c4bb15740 UTL  offlineThreshold:       8640000(s)
11/26 18:09:34.613978 0x7f6c4bb15740 UTL  rpcTimer:               1000(ms)
11/26 18:09:34.613984 0x7f6c4bb15740 UTL  rpcMaxTime:             600(s)
11/26 18:09:34.613994 0x7f6c4bb15740 UTL  statusInterval:         1(s)
11/26 18:09:34.614000 0x7f6c4bb15740 UTL  shellActivityTimer:     3(s)
11/26 18:09:34.614005 0x7f6c4bb15740 UTL  tableMetaKeepTimer:     7200(s)
11/26 18:09:34.614010 0x7f6c4bb15740 UTL  minSlidingTime:         10(ms)
11/26 18:09:34.614015 0x7f6c4bb15740 UTL  minIntervalTime:        10(ms)
11/26 18:09:34.614021 0x7f6c4bb15740 UTL  maxStreamCompDelay:     20000(ms)
11/26 18:09:34.614028 0x7f6c4bb15740 UTL  maxFirstStreamCompDelay:10000(ms)
11/26 18:09:34.614038 0x7f6c4bb15740 UTL  retryStreamCompDelay:   10(ms)
11/26 18:09:34.614045 0x7f6c4bb15740 UTL  streamCompDelayRatio:   0.100000
11/26 18:09:34.614056 0x7f6c4bb15740 UTL  maxVgroupsPerDb:        0
11/26 18:09:34.614062 0x7f6c4bb15740 UTL  maxTablesPerVnode:      1000000
11/26 18:09:34.614072 0x7f6c4bb15740 UTL  minTablesPerVnode:      1000
11/26 18:09:34.614078 0x7f6c4bb15740 UTL  tableIncStepPerVnode:   1000
11/26 18:09:34.614088 0x7f6c4bb15740 UTL  cache:                  16(Mb)
11/26 18:09:34.614094 0x7f6c4bb15740 UTL  blocks:                 6
11/26 18:09:34.614101 0x7f6c4bb15740 UTL  days:                   10
11/26 18:09:34.614111 0x7f6c4bb15740 UTL  keep:                   3650
11/26 18:09:34.614117 0x7f6c4bb15740 UTL  minRows:                100
11/26 18:09:34.614127 0x7f6c4bb15740 UTL  maxRows:                4096
11/26 18:09:34.614133 0x7f6c4bb15740 UTL  comp:                   2
11/26 18:09:34.614140 0x7f6c4bb15740 UTL  walLevel:               1
11/26 18:09:34.614149 0x7f6c4bb15740 UTL  fsync:                  3000
11/26 18:09:34.614155 0x7f6c4bb15740 UTL  replica:                1
11/26 18:09:34.614163 0x7f6c4bb15740 UTL  quorum:                 1
11/26 18:09:34.614172 0x7f6c4bb15740 UTL  update:                 0
11/26 18:09:34.614179 0x7f6c4bb15740 UTL  compressMsgSize:        -1
11/26 18:09:34.614186 0x7f6c4bb15740 UTL  maxSQLLength:           65480(byte)
11/26 18:09:34.614195 0x7f6c4bb15740 UTL  maxNumOfOrderedRes:     100000
11/26 18:09:34.614201 0x7f6c4bb15740 UTL  queryBufferSize:        -1(byte)
11/26 18:09:34.614210 0x7f6c4bb15740 UTL  timezone:                (CST, +0800)
11/26 18:09:34.614217 0x7f6c4bb15740 UTL  locale:                 zh_CN.UTF-8
11/26 18:09:34.614226 0x7f6c4bb15740 UTL  charset:                UTF-8
11/26 18:09:34.614232 0x7f6c4bb15740 UTL  maxShellConns:          5000
11/26 18:09:34.614239 0x7f6c4bb15740 UTL  maxConnections:         5000
11/26 18:09:34.614249 0x7f6c4bb15740 UTL  minimalLogDirGB:        0.100000(GB)
11/26 18:09:34.614255 0x7f6c4bb15740 UTL  minimalTmpDirGB:        0.100000(GB)
11/26 18:09:34.614261 0x7f6c4bb15740 UTL  minimalDataDirGB:       0.500000(GB)
11/26 18:09:34.614268 0x7f6c4bb15740 UTL  mnodeEqualVnodeNum:     4
11/26 18:09:34.614275 0x7f6c4bb15740 UTL  http:                   1
11/26 18:09:34.614284 0x7f6c4bb15740 UTL  mqtt:                   0
11/26 18:09:34.614290 0x7f6c4bb15740 UTL  monitor:                1
11/26 18:09:34.614300 0x7f6c4bb15740 UTL  httpEnableRecordSql:    0
11/26 18:09:34.614306 0x7f6c4bb15740 UTL  telegrafUseFieldNum:    0
11/26 18:09:34.614314 0x7f6c4bb15740 UTL  httpMaxThreads:         2
11/26 18:09:34.614323 0x7f6c4bb15740 UTL  restfulRowLimit:        10240
11/26 18:09:34.614330 0x7f6c4bb15740 UTL  numOfLogLines:          10000000
11/26 18:09:34.614339 0x7f6c4bb15740 UTL  logKeepDays:            0
11/26 18:09:34.614346 0x7f6c4bb15740 UTL  asyncLog:               1
11/26 18:09:34.614354 0x7f6c4bb15740 UTL  debugFlag:              0
11/26 18:09:34.614361 0x7f6c4bb15740 UTL  mDebugFlag:             135
11/26 18:09:34.614370 0x7f6c4bb15740 UTL  dDebugFlag:             135
11/26 18:09:34.614376 0x7f6c4bb15740 UTL  sDebugFlag:             135
11/26 18:09:34.614386 0x7f6c4bb15740 UTL  wDebugFlag:             135
11/26 18:09:34.614392 0x7f6c4bb15740 UTL  sdbDebugFlag:           135
11/26 18:09:34.614402 0x7f6c4bb15740 UTL  rpcDebugFlag:           131
11/26 18:09:34.614407 0x7f6c4bb15740 UTL  tmrDebugFlag:           131
11/26 18:09:34.614415 0x7f6c4bb15740 UTL  cDebugFlag:             131
11/26 18:09:34.614424 0x7f6c4bb15740 UTL  jniDebugFlag:           131
11/26 18:09:34.614430 0x7f6c4bb15740 UTL  odbcDebugFlag:          131
11/26 18:09:34.614437 0x7f6c4bb15740 UTL  uDebugFlag:             131
11/26 18:09:34.614446 0x7f6c4bb15740 UTL  httpDebugFlag:          131
11/26 18:09:34.614452 0x7f6c4bb15740 UTL  mqttDebugFlag:          131
11/26 18:09:34.614461 0x7f6c4bb15740 UTL  monitorDebugFlag:       131
11/26 18:09:34.614468 0x7f6c4bb15740 UTL  qDebugFlag:             131
11/26 18:09:34.614477 0x7f6c4bb15740 UTL  vDebugFlag:             131
11/26 18:09:34.614483 0x7f6c4bb15740 UTL  tsdbDebugFlag:          131
11/26 18:09:34.614490 0x7f6c4bb15740 UTL  cqDebugFlag:            135
11/26 18:09:34.614500 0x7f6c4bb15740 UTL  tscEnableRecordSql:     0
11/26 18:09:34.614506 0x7f6c4bb15740 UTL  enableCoreFile:         0
11/26 18:09:34.614516 0x7f6c4bb15740 UTL  gitinfo:                community
11/26 18:09:34.614522 0x7f6c4bb15740 UTL  gitinfoOfInternal:      internal
11/26 18:09:34.614532 0x7f6c4bb15740 UTL  buildinfo:              Built at 2020-11-25 23:06:14
11/26 18:09:34.614538 0x7f6c4bb15740 UTL  version:                2.0.8.0
11/26 18:09:34.614545 0x7f6c4bb15740 UTL  maxBinaryDisplayWidth:  30
11/26 18:09:34.614550 0x7f6c4bb15740 UTL  tempDir:                /tmp/
11/26 18:09:34.614563 0x7f6c4bb15740 UTL  os pageSize:            4096(KB)
11/26 18:09:34.614572 0x7f6c4bb15740 UTL  os openMax:             65536
11/26 18:09:34.614577 0x7f6c4bb15740 UTL  os streamMax:           16
11/26 18:09:34.614582 0x7f6c4bb15740 UTL  os numOfCores:          40
11/26 18:09:34.614590 0x7f6c4bb15740 UTL  os totalDisk:           8643.615234(GB)
11/26 18:09:34.614603 0x7f6c4bb15740 UTL  os totalMemory:         128365(MB)
11/26 18:09:34.614616 0x7f6c4bb15740 UTL  os sysname:             Linux
11/26 18:09:34.614624 0x7f6c4bb15740 UTL  os nodename:            hotel_test_126
11/26 18:09:34.614630 0x7f6c4bb15740 UTL  os release:             3.10.0-1127.19.1.el7.x86_64
11/26 18:09:34.614637 0x7f6c4bb15740 UTL  os version:             #1 SMP Tue Aug 25 17:23:54 UTC 2020
11/26 18:09:34.614646 0x7f6c4bb15740 UTL  os machine:             x86_64
11/26 18:09:34.614652 0x7f6c4bb15740 UTL ==================================
11/26 18:09:34.614677 0x7f6c4bb15740 DND failed to read /opt/soft/taos/data/dnode/mnodeEpSet.json, file not exist
11/26 18:09:34.614692 0x7f6c4bb15740 DND dnode minfos is initialized
11/26 18:09:34.614764 0x7f6c4bb15740 WAL wal thread is launched
11/26 18:09:34.614791 0x7f6c4bb15740 WAL wal module is initialized, refId:2
11/26 18:09:34.614941 0x7f6c4bb15740 DND dnode check is initialized
11/26 18:09:34.614963 0x7f6c4bb15740 DND dnode vread is initialized, min worker:40 max worker:80
11/26 18:09:34.614978 0x7f6c4bb15740 DND dnode vwrite is initialized, max worker 40
11/26 18:09:34.614992 0x7f6c4bb15740 DND dnode mread worker:0 is created
11/26 18:09:34.615001 0x7f6c4bb15740 DND dnode mread worker:1 is created
11/26 18:09:34.615005 0x7f6c4bb15740 DND dnode mread worker:2 is created
11/26 18:09:34.615009 0x7f6c4bb15740 DND dnode mread worker:3 is created
11/26 18:09:34.615014 0x7f6c4bb15740 DND dnode mread is initialized, workers:4 qset:0x19c0150
11/26 18:09:34.615019 0x7f6c4bb15740 DND dnode mwrite worker:0 is created
11/26 18:09:34.615023 0x7f6c4bb15740 DND dnode mwrite is initialized, workers:1 qset:0x19c0210
11/26 18:09:34.615028 0x7f6c4bb15740 DND dnode mpeer worker:0 is created
11/26 18:09:34.615033 0x7f6c4bb15740 DND dnode mpeer is initialized, workers:1 qset:0x19c1470
11/26 18:09:34.615993 0x7f6c4bb15740 DND dnode inter-dnodes rpc client is initialized
11/26 18:09:34.616975 0x7f6c4bb15740 DND dnode inter-dnodes RPC server is initialized
11/26 18:09:34.617071 0x7f6c4bb15740 SYN 0x1a2dd00 TCP pool is created
11/26 18:09:34.617123 0x7f6c4bb15740 SYN sync module initialized successfully
11/26 18:09:34.617281 0x7f6c4bb15740 DND start 40 threads to open 0 vnodes
11/26 18:09:34.617295 0x7f6c4bb15740 DND there are total vnodes:0, openned:0 failed:0
11/26 18:09:34.617302 0x7f6c4bb15740 DND dnode mgmt is initialized
11/26 18:09:34.617328 0x7f6c4bb15740 MND mnode module won't start, asMaster:0 fileExist:0
11/26 18:09:34.617482 0x7f6c4bb15740 DND dnode modules is initialized
11/26 18:09:34.617497 0x7f6c4bb15740 DND dnode mgmt timer is initialized
11/26 18:09:34.618165 0x7f6c4bb15740 DND dnode shell rpc server is initialized
11/26 18:09:34.618220 0x7f6c4bb15740 DND dnode telemetry is initialized
11/26 18:09:34.618227 0x7f6c4bb15740 HTP start http server ...
11/26 18:09:34.618313 0x7f6c4bb15740 HTP http result queue is opened
11/26 18:09:34.618815 0x7f6c307e8700 HTP http server init success at 6041
11/26 18:09:34.619284 0x7f6c4bb15740 MON monitor module start
11/26 18:09:34.619299 0x7f6c4bb15740 DND TDengine is initialized successfully
11/26 18:09:35.123015 0x7f6c41c8c700 DND minfos is changed, numOfEps:2 inUse:0
11/26 18:09:35.123043 0x7f6c41c8c700 DND minfo:0 h1.bigdata.bi:6030
11/26 18:09:35.123051 0x7f6c41c8c700 DND minfo:1 h2.bigdata.bi:6030
11/26 18:09:35.123232 0x7f6c41c8c700 DND ERROR status rsp is received, error:Cluster cfg inconsistent
11/26 18:09:36.126350 0x7f6c41c8c700 DND ERROR status rsp is received, error:Cluster cfg inconsistent
11/26 18:09:37.131290 0x7f6c41c8c700 DND ERROR status rsp is received, error:Cluster cfg inconsistent
11/26 18:09:38.136276 0x7f6c41c8c700 DND ERROR status rsp is received, error:Cluster cfg inconsistent
11/26 18:09:39.141804 0x7f6c41c8c700 DND ERROR status rsp is received, error:Cluster cfg inconsistent
11/26 18:09:40.146321 0x7f6c41c8c700 DND ERROR status rsp is received, error:Cluster cfg inconsistent
11/26 18:09:41.151398 0x7f6c41c8c700 DND ERROR status rsp is received, error:Cluster cfg inconsistent
11/26 18:09:42.156329 0x7f6c41c8c700 DND ERROR status rsp is received, error:Cluster cfg inconsistent
11/26 18:09:43.161314 0x7f6c41c8c700 DND ERROR status rsp is received, error:Cluster cfg inconsistent
11/26 18:09:44.166552 0x7f6c41c8c700 DND ERROR status rsp is received, error:Cluster cfg inconsistent
11/26 18:09:45.171277 0x7f6c41c8c700 DND ERROR status rsp is received, error:Cluster cfg inconsistent

**Comment by nieyuanqing** [comment]
配置文件的差异：
# first fully qualified domain name (FQDN) for TDengine system
firstEp                   h1.bigdata.bi:6030

# local fully qualified domain name (FQDN)
fqdn                      h3.bigdata.bi

**Comment by sangshuduo** [comment]
第三个节点配置的和另外的不一样

firstEp: h2.bigdata.bi

secondEp: h3.bigdata.bi:6030

**Comment by nieyuanqing** [comment]
Hi，
第三个节点的配置：firstEp设置成h1.bigdata.bi， h2.bigdata.bi同样报错，另外，没有设定secondEp参数。

**Comment by nieyuanqing** [comment]
第一个节点配置：
firstEp:                h1.bigdata.bi:6030
secondEp:               h1.bigdata.bi:6030
fqdn:                   h1.bigdata.bi

第二个节点配置：
firstEp:                h1.bigdata.bi:6030
secondEp:               h2.bigdata.bi:6030
fqdn:                   h2.bigdata.bi

第三个节点配置：
firstEp:                h1.bigdata.bi:6030
secondEp:               h3.bigdata.bi:6030
fqdn:                   h3.bigdata.bi

第二个节点没有问题，第三个节点有问题。 从配置看，并不要求secondEp保持一致。

**Comment by nieyuanqing** [comment]
show dnodes信息如下：
taos> show dnodes;
   id   |           end_point            | vnodes | cores  |    status    |  role   |       create_time       |       offline reason       |
============================================================================================================================================
      1 | h1.bigdata.bi:6030             |      1 |      4 | ready        | any     | 2020-11-26 17:10:16.408 |                            |
      2 | h2.bigdata.bi:6030             |      0 |      4 | ready        | any     | 2020-11-26 17:35:58.805 |                            |
      4 | h3.bigdata.bi:6030             |      0 |      0 | offline      | any     | 2020-11-27 12:17:13.153 | dnodeId not match          |
Query OK, 3 row(s) in set (0.003092s)

**Comment by nieyuanqing** [comment]
多谢， 已经找到原因， 第三台系统的locale和前两台不一致。

**Comment by nieyuanqing** [comment]
localectl  set-locale LANG=zh_CN.UTF8
