### ISSUE TITLE
 2.0.8.0 alert error: Invalid time value

### ISSUE THREAD

**Issue by sexbee** [taosdata/TDengine#4365]
**Bug Description**

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**
Add any other context about the problem here
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Uptodate 2.0.8.0 alert error:

RangeError: Invalid time value
    at Date.toISOString (<anonymous>)

function convertStringToTS(str) {
    let date = new Date(str);
    date.setHours(date.getHours() + 8)
    let tsArr = date.toISOString().split("T");
    return "\'" + tsArr[0] + " " + tsArr[1].substring(0, tsArr[1].length - 1) + "\'";
};
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
2.0.7.0 normal

**Comment by sexbee** [comment]
2.0.8.0 版本的  时间数据读出格式变了？还是tdconnector里面数据转换改变了?

**Comment by localvar** [comment]
您好，麻烦按照模板详细描述下问题，现在的内容我们看不出您想做什么，遇到了什么问题，希望我们在哪些方面提供帮助。
