### ISSUE TITLE
DB error: invalid SQL: binary column not support this operator

### ISSUE THREAD

**Issue by duanjz** [taosdata/TDengine#4367]
taos> select *  from d027135010003 where  version_name is null  order by cjsj asc limit 10 ;

DB error: invalid SQL: binary column not support this operator

version_name 是binary  型的，请问is null的taos  sql语句怎么写？

**Comment by hjxilinx** [comment]
请提供版本号

**Comment by hjxilinx** [comment]
This issue was closed because it has been inactive for too many days.
