### ISSUE TITLE
Can't name the table starting with a number

### ISSUE THREAD

**Issue by mmooyyii** [taosdata/TDengine#437]
按文档所述，需要一个设备建一个表，但是数字开头的设备编号是很常见的。如果需要表名前需要拼接英文字符，查询时又会有些麻烦。
是否考虑表名支持使用双引号，
比如 create table "1" (ts timestamp,value1 int); select * from "1";

**Comment by plum-lihui** [comment]
表名必须是 字母或下划线开头，不能是数字开头。

**Comment by thomasbrook** [comment]
不太理解 设备号是数字开头 一看就是不太规范 我公司设备号 厂家编码+年月日+序列号

**Comment by LeeGaning** [comment]
列名也不支持数字开头
其实电表这类编号就是纯数字的
