### ISSUE TITLE
how to configure client to access server when NAT port mapping enabled

### ISSUE THREAD

**Issue by deuxmille** [taosdata/TDengine#4380]
taosd运行在公司的192.168.10.93上的ubuntu里（taosnode1），局域网的其他机器可以正常使用taos客户端连接。想在非局域网环境也连接使用taosnode1，通过有公网IP（假设为204.204.10.10）的路由器将192.168.10.93的6030-6042端口NAT到公网IP（假设为204.204.10.10）的9330-9342端口，TCP和UDP都做了映射。

非局域网环境的机器，通过c connector连接 204.204.10.10 9330，taos_connect函数返回的是有效的指针，会直接返回Unable to resolve FQDN
客户端log如下：
|2020-11-28 22:04:57|deuxmille::TaosConnector::Sync => command = [select * from test.meters where loc='shanghai' limit 10]
|2020-11-28 22:05:00|TDengine error: code = -2147483627, msg = Unable to resolve FQDN
服务器的log如下：
11/27 15:04:57.626007 0x7f23437fe700 DND 0x7f233c0cf470, msg:heartbeat will be processed in mread queue
11/27 15:04:57.795798 0x7f2352ffd700 DND msg:status will be processed in mpeer queue
11/27 15:04:57.917617 0x7f23537fe700 DND 0x7fa700001410, msg:heartbeat will be processed in mread queue
11/27 15:04:58.120358 0x7f22e9fc2700 MND user:root, auth info is returned
11/27 15:04:58.120506 0x7f2341ffb700 DND 0x2f2cf70, msg:connect will be processed in mread queue
11/27 15:04:58.120532 0x7f2341ffb700 MND connId:205, is created, user:root ip:116.235.128.225:56489
11/27 15:04:58.120806 0x7f2341ffb700 MND user:root login from 116.235.128.225, result:success
11/27 15:04:58.121032 0x7f22eafc4700 MND user:monitor, auth info is returned
11/27 15:04:58.121110 0x7f233b7fe700 DND 0x7f22d000b600, msg:table-meta will be processed in mread queue
11/27 15:04:58.121129 0x7f233b7fe700 MND app:0x7f22d000b600:0x7f22c000d440, table:0.log.log, table meta msg is received from thandle:0x108fee8, createFlag:0
11/27 15:04:58.121141 0x7f233b7fe700 MND app:0x7f22d000b600:0x7f22c000d440, table:0.log.log, uid:562949970201318 table meta is retrieved, vgId:2 sid:1
11/27 15:04:58.121431 0x7f2327fff700 SYN vgId:2, replica:1 nodeRole:master qtype:0 ver:15017
11/27 15:04:58.800777 0x7f2352ffd700 DND msg:status will be processed in mpeer queue
11/27 15:04:59.130764 0x7f23437fe700 DND 0x7f233c0cf470, msg:heartbeat will be processed in mread queue
11/27 15:04:59.422133 0x7f23537fe700 DND 0x7fa700001410, msg:heartbeat will be processed in mread queue

尝试在该非局域网环境的机器hosts文件上添加一句"204.204.10.10 taosnode1"，ping taosnode1成功，这个时候通过c connector连接204.204.10.10 9330，会直接返回Unable to establish connection
客户端log如下：
|2020-11-29 01:14:20|deuxmille::TaosConnector::Sync => command = [select * from test.meters where loc='shanghai' limit 10]
|2020-11-29 01:14:21|TDengine error: code = -2147483637, msg = Unable to establish connection
服务器的log如下：
11/28 17:14:19.295133 0x7f11b9ffb700 DND 0x7f11a00cefd0, msg:heartbeat will be processed in mread queue
11/28 17:14:19.410024 0x7f11baffd700 DND msg:status will be processed in mpeer queue
11/28 17:14:20.065680 0x7f114cfaf700 MND user:root, auth info is returned
11/28 17:14:20.065772 0x7f11b97fa700 DND 0x341ad40, msg:connect will be processed in mread queue
11/28 17:14:20.065796 0x7f11b97fa700 MND connId:4, is created, user:root ip:116.235.128.225:62503
11/28 17:14:20.065916 0x7f11b97fa700 MND user:root login from 116.235.128.225, result:success
11/28 17:14:20.066036 0x7f11b1ffb700 SYN vgId:2, replica:1 nodeRole:master qtype:0 ver:18192
11/28 17:14:20.414891 0x7f11baffd700 DND msg:status will be processed in mpeer queue
11/28 17:14:20.800595 0x7f11bb7fe700 DND 0x7f11a00cefd0, msg:heartbeat will be processed in mread queue

求教通过NAT端口映射之后的客户端配置方法。

**Comment by sangshuduo** [comment]
@deuxmille 请参考 https://www.taosdata.com/blog/2020/09/08/1816.html 测试相关端口是否可以访问

**Comment by deuxmille** [comment]
win版本taos没有-n client option

**Comment by deuxmille** [comment]
局域网的其他机器可以正常使用taos客户端连接。

是不是应该跟服务器端没什么关系。

**Comment by sangshuduo** [comment]
Windows 可以用 PowerShell 下 Test-NetConnection 命令来测试端口是否可以访问

**Comment by sangshuduo** [comment]
Windows 可以用 PowerShell 下 Test-NetConnection 命令来测试端口是否可以访问

**Comment by sangshuduo** [comment]
另外也许可以搞个 ddns

**Comment by PascalMing** [comment]
用nginx和hosts可以做多重解析，应该可以。

**Comment by sangshuduo** [comment]
无更新，关闭。

**Comment by haojiawei111** [comment]
解决了吗？ 我也一样的问题，代理端口84，客户端连接不上，日志显示客户端去连接6030端口了。 版本：3.3.2.0
![image](https://github.com/user-attachments/assets/bf326584-c009-4b6a-86aa-f3ad771ee43e)
