### ISSUE TITLE
Cluster high availability deployment

### ISSUE THREAD

**Issue by lacezeng** [taosdata/TDengine#4391]
关于Tdengine的高可用集群部署，有几个问题想请教一下:
1. 同一个dnode可不可以存在多份相同副本？
我测试了一下，三个节点三副本的情况下，停掉一台机器的taosd进程后，insert还是能成功，但是vgroup有一个dnode显示状态为offline。
![image](https://user-images.githubusercontent.com/71378259/100587605-c106f100-332b-11eb-818a-f538ea7c68c6.png)

2. 有数据的情况下，mnode所在节点任意宕机一个，是否集群就不正常了？
测试中发现，1. master mnode所在dnode停掉之后，集群直接无连接；2. slave node 停掉之后，无法插入数据。
(三节点两个mnode，数据双副本)

**Comment by Shawshank-Smile** [comment]
(三节点两个mnode，数据双副本)
回复：默认管理节点组应该是3；数据双副本需要使用Arbitrator，请参看官网文档。


1. master mnode所在dnode停掉之后，集群直接无连接；
回复：应该是只配置了FirstEP，建议配置secondEP。

2. slave node 停掉之后，无法插入数据。
回复：请详细描述一下复现步骤，多一些现场的截图。

**Comment by yakir-Yang** [comment]
集群对外提供的连接地址，如何做到高可用？
