### ISSUE TITLE
Data from http client would not be updated after inserting data to a new table 

### ISSUE THREAD

**Issue by mijjjj** [taosdata/TDengine#440]
版本：
ubuntu 18.04
taos 1.6.1.7

问题：
超级表新增子表后插入一条数据，通过后台可以查询到这条数据，但通过http接口查询是查不到这条数据，但过了几分钟后又能查询到，旧表不会，单单查子表也没问题

![TIM截图20190829100357](https://user-images.githubusercontent.com/37797122/63904664-699d1580-ca44-11e9-8b55-6cd485a0ae01.png)
![TIM截图20190829100408](https://user-images.githubusercontent.com/37797122/63904666-6a35ac00-ca44-11e9-88fd-c72c519c12b2.png)

**Comment by plum-lihui** [comment]
由于在client端的cach中metric meta还没有超时更新，没有新建子表的信息，所以查询不到新建子表的记录。过了几分钟后又能查询到，是由于cache超时后，更新了metric meta。
在后续版本中实现cache同步后，会解决这个问题。
