### ISSUE TITLE
taos.error.ProgrammingError: too slow

### ISSUE THREAD

**Issue by gozhhu** [taosdata/TDengine#441]
**Bug Description**
A "too slow" exception is found.

**To Reproduce**
1. Message: "TAOS ERROR: INSERT INTO tbl USING stbl_history TAGS (xxx) VALUES ('1566864002679', '2019-08-27', '0', '0.00', '0', '0.00', '0', '0')"
Arguments: (ProgrammingError('too slow',),)

**Expected Behavior**
Run as other Insert sqls.

**Environment (please complete the following information):**
 - OS: CentOS 7
 - Memory: 8G, CPU 2G x2, current Disk Space: > 4G
 - TDengine Version e.g. 1.6.1.6

**Comment by gozhhu** [comment]
after that, taod has a high cpu usage without any sql execution:
--------------------------------
62.1%  138:16.41 taosd

**Comment by hzcheng** [comment]
Which version did you use?

**Comment by hzcheng** [comment]
您能否将debug flag打开（在/etc/taos/taos.cfg中添加debugFlag 15), 然后重启服务，让配置生效，然后再将这个问题重复下，将/var/log/taos下的日志问天打包发我们邮箱：hzcheng@taosdata.com，非常感谢！

**Comment by gozhhu** [comment]
how do not know I can speak chinese? :) by the way I can not reproduce this bug again, it is not common, but, It looks unstable for me.

**Comment by hzcheng** [comment]
Thanks for you reporting and your log. The problem seems like a bug we fixed a few days ago. To confirm that, a question we want an answer is: DId you use **import** to import historical data? 

Besides, would you like to send me the data file "/data/taos-data/tsdb/vnode4/db/v4f1812.head" so that I can make it sure. Thanks!

**Comment by hzcheng** [comment]
Also, can you send the file "/data/taos-data/tsdb/vnode4/meterObj.v4" to me? Thanks!

**Comment by gozhhu** [comment]
上次报错应该用的不是import操作。当时还不知道有import操作。
我等会发过来

**Comment by sangshuduo** [comment]
@gozhhu 这个问题还存在吗？
