### ISSUE TITLE
The result of aggregation through JDBC is inconsistent with that by shell client

### ISSUE THREAD

**Issue by quchunhui** [taosdata/TDengine#4415]
同样的语句jdbc的查询结果与通过客户端查询的结果存在差异。

【查询语句】：
select first(value) as first, last(value) as last, min(value) as min, max(value) as max, spread(value) as spread, avg(value) as avg, sum(value) as sum, count(value) as count from rexel_privatization.st_device_data_up  where ( productKey = "a1B6t6ZG6oR" and ( pointId = "AI01_0001" or  pointId = "AI01_0002")) and  time >= "2020-12-01 00:00:00.000" and  time < "2020-12-02 00:00:00.000"  interval(1d)   group by productKey, deviceName, pointId
【JDBC的聚合结果】：（存储到了mysql当中）
![image](https://user-images.githubusercontent.com/18110478/100881944-864ab780-34e9-11eb-8d66-8afda2d4244b.png)
【通过shell客户端聚合的结果】：
![image](https://user-images.githubusercontent.com/18110478/100882002-9b274b00-34e9-11eb-91a2-bd6c7ebe1759.png)

我个人初步怀疑是时区的问题，我的JDBC客户端的设置如下：
![image](https://user-images.githubusercontent.com/18110478/100882088-bbefa080-34e9-11eb-9c0e-349bf5b58567.png)

tdengine的相关配置未做修改，使用的是默认的值。

请问，能否帮忙提供一下调查的方向或者线索呢？

**Comment by quchunhui** [comment]
修改客户端的time_zone为UTC-8之后，结果倒是一致了，
能否帮忙讲解一下原理吗？这样后面再用的时候，可以少踩坑了。
比如：td默认的时区，客户端建议使用的时区等。

**Comment by zyyang-taosdata** [comment]
使用Java访问TDengine，指定时区、字符集的位置有3个地方：
1. jdbcUrl
2. Properties
3. 配置文件（只有在jdbc中不指定host和port时才会采用客户端的配置文件）
并且，优先级有1到3递减。详细内容请参考：https://www.taosdata.com/cn//documentation20/connector-java/
TDengine中，客户端与服务端的时间同步需要保持在15分钟之内，如果客户端和服务端的时区不一致，必然会超出15分钟。

**Comment by quchunhui** [comment]
close
