### ISSUE TITLE
超级表查询中文支持Bug

### ISSUE THREAD

**Issue by PascalMing** [taosdata/TDengine#4416]
select tbname,tagname from iot_int where tagname='计数器1'  查询时 ，集成环境下可以正常返回结果，打包后查询没有结果集返回
去掉where条件，结果集可以返回中文。用结果集的中文拼接SQL继续查，同样没有结果

TDengine Client 查询同样不支持中文。

系统环境：
    服务端:Centos8, TDengine2.0.7
   客户端:Win10 x64,JDK1.8，taos-jdbcdriver 2.0.13

超级表创建：
CREATE TABLE IF NOT EXISTS iot_int(ts timestamp, v int) TAGS (tagname binary(128))")

JAVA工程pom.xml配置：
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <maven.compiler.encoding>UTF-8</maven.compiler.encoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

**Comment by yihaoDeng** [comment]
所以你的意思是中午不支持条件查询 @PascalMing

**Comment by PascalMing** [comment]
> 所以你的意思是中午不支持条件查询 @PascalMing

集成环境Eclipse和idea直接跑可以，打包运行不支持

**Comment by hjxilinx** [comment]
我认为是配置文件的原因。打包后的程序加载的配置文件对于系统的 charset 的设置有问题。所以请把打包后的程序启动后的日志可以贴在这里，我们协助分析一下。

**Comment by PascalMing** [comment]
> 我认为是配置文件的原因。打包后的程序加载的配置文件对于系统的 charset 的设置有问题。所以请把打包后的程序启动后的日志可以贴在这里，我们协助分析一下。

搞定，谢谢。
查了日志，打包后虽然与调试用的同一台设备，但使用的字符集不同，调试时使用TDengine Client Driver驱动的，直接跑的又是另外一个。
使用指定参数解决了此问题。
String jdbcUrl = "jdbc:TAOS://"+taosAddr+"/?user=root&password=taosdata";

        Properties connProps = new Properties();
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_USER, "root");
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_PASSWORD, "taosdata");
        //connProps.setProperty(TSDBDriver.PROPERTY_KEY_CONFIG_DIR, "/etc/taos");
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_CHARSET, "UTF-8");
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_LOCALE, "en_US.UTF-8");
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_TIME_ZONE, "UTC-8");
        Connection conn = DriverManager.getConnection(jdbcUrl, connProps);

建议TDengine设计时所有缺省参数保持一致。
