### ISSUE TITLE
the performance of query

### ISSUE THREAD

**Issue by wanghuahui** [taosdata/TDengine#4419]
ts                             | TIMESTAMP          |           8 |            |
 oprnum                         | BINARY             |          64 |            |
 plateno                        | NCHAR              |          20 |            |
 imgtime                        | BINARY             |          32 |            |
 deviceid                       | BINARY             |          32 |            |
 location                       | NCHAR              |          20 | TAG        |
 platetag                       | NCHAR              |          20 | TAG        |
上面为超级表字段，以车牌为子表名称创建了约400万个子表，每个表里有几十到上百条记录，超级表其中一个标签也是车牌号，以车牌号进行查询，显示耗时4-5秒，这种用时正常吗？有没有优化空间？怎样才能做到毫秒级查询？

**Comment by wanghuahui** [comment]
有人能给个优化思路吗，提高查询速度

**Comment by localvar** [comment]
请贴一下您实际使用的查询语句。

**Comment by wanghuahui** [comment]
select * from plates where platetag='具体车牌号码';
其中plates为超级表，车牌记录时间跨度从2020/01/01-2020/07/31
多谢

**Comment by robotspace** [comment]
看起来您这个问题适合直接查询子表，不应该查询超级表。

**Comment by hjxilinx** [comment]
本周发布的新版本（2.0.9.x）对于 projection 查询的性能进行了优化，您可以使用新版本试一试。

**Comment by wanghuahui** [comment]
好的，多谢。我试下新版本。
