### ISSUE TITLE
查询速度太慢

### ISSUE THREAD

**Issue by cztong** [taosdata/TDengine#442]
官方文档读取速度如下：
![image](https://user-images.githubusercontent.com/7899882/63926248-1778e600-ca7e-11e9-9015-e8864b10d5d3.png)
实际测试结果：
![image](https://user-images.githubusercontent.com/7899882/63926294-31b2c400-ca7e-11e9-9838-2f99646b4c63.png)
时间跨度不超过1小时，
mysql查询16w数据时间如下：
![image](https://user-images.githubusercontent.com/7899882/63926467-79d1e680-ca7e-11e9-802f-abcaa2727d47.png)
同样都是select * from table,和mysql差距明显。
请问官网中20000000/s查询速度是怎么查的？

**Comment by hzcheng** [comment]
您这是把数据都打印到屏幕了？MYSQL的结果有输出到屏幕吗？

**Comment by hzcheng** [comment]
您这是把数据都打印到屏幕了？MYSQL的结果有输出到屏幕吗？

**Comment by cztong** [comment]
好吧，不能按照打印的结果来测试。
