### ISSUE TITLE
2.0.8.2不支持td2.0-connector

### ISSUE THREAD

**Issue by chuangtim** [taosdata/TDengine#4429]
环境：

> 1. centos7
> 2. taosd: 2.0.8.2
> 3. taos客户端：2.0.8.2
> 3. "td2.0-connector": "^2.0.2"

代码如下：
`
const taos = require('td2.0-connector');
var conn = taos.connect({host:"taosd1", user:"root", password:"123",port:0});
var c1 = conn.cursor();
c1.execute('use xxx;');
async function test() {
 let result = await c1.query('select * from gw_app_log_1AE96D13004B1200', true);
 console.log(JSON.stringify(result));
}

test();
`

结果如下：
`
{"data":[{"data":["2020-12-03T00:53:06.161Z","\u0010",53,"5"],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4},{"data":[null,null,null,null],"length":4}],"rowcount":67,"fields":[{"_field":{"name":"ts","type":9,"bytes":8},"name":"ts","type":"Timestamp"},{"_field":{"name":"tid","type":8,"bytes":36},"name":"tid","type":"Binary"},{"_field":{"name":"cid","type":3,"bytes":2},"name":"cid","type":"Small Int"},{"_field":{"name":"log","type":8,"bytes":150},"name":"log","type":"Binary"}]}`

**Comment by chuangtim** [comment]
更新td2.0-connector版本，顺便将日志修改下，生产环境下回影响性能，谢谢
![image](https://user-images.githubusercontent.com/8262851/100995215-73d88880-3592-11eb-8892-6e6f04237ca8.png)

**Comment by chuangtim** [comment]
> 经过测试，目前写入性能有问题，每秒1000条写入，会出现CPU狂飙，停止写入后，CPU会正常

![image](https://user-images.githubusercontent.com/8262851/101118767-b5b20f00-3624-11eb-9a77-8a544b8409ac.png)

**Comment by zyyang-taosdata** [comment]
感谢您的问题，在2.0.8.0中，TDengine-client修改了查询数据的相关实现以提升查询性能，修改了libtaos.so（taos.dll）的接口，目前nodejs的驱动还没有完成对2.0.8.0以上版本的适配。我建议你可以选择JDBC或使用Restful接口来进行应用开发，这两个接口更新速度是和TDengine的版本一致的。

**Comment by chuangtim** [comment]
如果说用2.0.6.0版本呢，就不存在这个问题？

**Comment by zyyang-taosdata** [comment]
我觉得你可以自行验证一下，TDengine的安装卸载都是很简单的。td2.0-connector的使用请参考官方文档和github上的示例程序。

**Comment by hjxilinx** [comment]
建议升级到最新的版本进行尝试。
