### ISSUE TITLE
JDBC+TDengine insert data with multiple threads led crash

### ISSUE THREAD

**Issue by k-kang1** [taosdata/TDengine#4444]
项目是通过JDBC直接连taos库的，目前发现在多线程插入同一张表（超级表）时，如果插入数据压力过大会使得程序进程崩溃。

运行环境:
OS:Red Hat Enterprise Linux Server release 7.3 (Maipo)
TDengine Version :2.0.8.0

异常日志：
[err_log.zip](https://github.com/taosdata/TDengine/files/5641138/err_log.zip)

**Comment by sangshuduo** [comment]
@k-kang1 请问 JDBC driver 版本是多少？

**Comment by k-kang1** [comment]
> @k-kang1 请问 JDBC driver 版本是多少？

2.0.12

**Comment by zyyang-taosdata** [comment]
从报错信息来看，你的应用程序触发了某个段错误，如果查看官网可以发现，2.0.8.0版本的TDengine已经被撤销，建议对TDengine进行版本升级
