### ISSUE TITLE
TDengine syntax, like INTERVAL( 100s ) should INTERVAL ( "100s" )

### ISSUE THREAD

**Issue by sim-wangyan** [taosdata/TDengine#4452]
Syntax bug, because "100s" is string,  should write "" in the SQL

**Comment by hjxilinx** [comment]
我还是不太明白，您能否将应用的具体场景及原因说得更为清楚一些，这样我们更容易判断这个需求是否是一个通用需求，才能决定是否支持。

**Comment by sim-wangyan** [comment]
往INTERVAL(?) 传参数，是一个通用的需要，如果传null, SQL里应该没有INTERVAL函数，如果传的是字符串，SQL就应该加上引号.  为啥order by 后面没引号，limit, offset后面也没引号，因为要么是字段要么是数字。现在不支持引号，看看写应用代码时，需要怎么处理(1行写成2行，还得用“+”号拼接): 
<img width="479" alt="TDengine_interval" src="https://user-images.githubusercontent.com/19405905/101317259-1d709000-3899-11eb-8b18-9de0780bd714.png">

**Comment by hjxilinx** [comment]
好的，我们后面看看如何处理。

**Comment by hjxilinx** [comment]
This issue was closed because it has been inactive for too many days.
