### ISSUE TITLE
taos client for Windows connecting server failed with Unable to establish connection error

### ISSUE THREAD

**Issue by ideazoom** [taosdata/TDengine#4460]
服务端已配置FQDN，客户端的HOSTS文件中也配置了对应的FQDN地址。
在taos 客户端连接时可以连接上，执行SQL命令时报Unable to establish connection错误。
服务端和客户端的防火墙已关闭。
服务端：centOS 7  (虚拟机)
客户端：windows10
错误日志文件：
[taos.log](https://github.com/taosdata/TDengine/files/5648337/taos.log)

**Comment by andyfu007** [comment]
I got the same bug to yours, Can you tell me which 2.*  TDengine is good for this?

**Comment by andyfu007** [comment]
> I got the same bug to yours, Can you tell me which 2.* TDengine is good for this?

我遇见同样的问题，谁能告诉我，哪个2以上的版本是没有这个问题的，我不能一个一个的去试验，谢谢！

**Comment by sangshuduo** [comment]
之前是对有配置过 IPv6 Windows的处理的bug，最新版本应该已经解决了这个问题。

**Comment by stephenkgu** [comment]
This issue was closed because it has been inactive for too many days.
