### ISSUE TITLE
'setOptions' '(ILjava/lang/String;)I' in 'com/taosdata/jdbc/TSDBJNIConnector'

### ISSUE THREAD

**Issue by quchunhui** [taosdata/TDengine#4466]
在通过jdbc调用tdengine的聚合的时候，提示gcc异常退出，日志中报错如下，
请问，从日志中能看出来什么？或者在使用jdbc的时候，设置什么参数可以解决这个错误码？
![image](https://user-images.githubusercontent.com/18110478/101285463-3e48cf00-3820-11eb-833a-dfa8e64a98c0.png)

**Comment by sangshuduo** [comment]
@quchunhui 请提供 TDengine 和 JDBC cocnnector 版本信息，如果不是新版本，请使用 2.0.9.0 和 JDBC 2.0.14.0 ，是否还有这个问题？

**Comment by sangshuduo** [comment]
长时间无更新，关闭。
