### ISSUE TITLE
集群中一个服务器关机，导致Unable to establish connection

### ISSUE THREAD

**Issue by zhyhuayong** [taosdata/TDengine#4467]
第一台服务器配置
```
firstEp                   taosnode1:6030
fqdn                      taosnode1
serverPort                6030
```

第二台服务器配置
```
firstEp                   taosnode1:6030
secondEp		  taosnode2:6030
fqdn                      taosnode2
serverPort                6030
```

加入集群后，运行 SHOW DNODES; 显示正常

![image](https://user-images.githubusercontent.com/23372028/101307898-851be080-3883-11eb-82e1-6ed15e596375.png)

然后我把taosnode2服务给关了。就报错了
![image](https://user-images.githubusercontent.com/23372028/101307976-b3012500-3883-11eb-8a95-cfe1e8c4e7eb.png)

taosnode1 日志 
![image](https://user-images.githubusercontent.com/23372028/101308007-c8764f00-3883-11eb-9a56-0d5f4cd124f7.png)

**Comment by zhyhuayong** [comment]
期望结果，是不影响主服务的使用

**Comment by sangshuduo** [comment]
可以配置 firstEp 和 secondEP

**Comment by sangshuduo** [comment]
加入集群后不能作为单机服务器使用。
