### ISSUE TITLE
Software support for 32-bit system

### ISSUE THREAD

**Issue by nari-dongx** [taosdata/TDengine#447]
什么时候可以支持32位系统？

**Comment by plum-lihui** [comment]
还在计划中，估计年底左右。您说的32位系统，是x86的系统，还是arm的系统？

**Comment by nari-dongx** [comment]
x86的




Best Regards

*************************************
    董  雪
   国电南瑞中德公司 应用开发部
   15295748600
   dongx405110@163.com
*************************************
 
From: plum-lihui
Date: 2019-09-03 09:18
To: taosdata/TDengine
CC: nari-dongx; Author
Subject: Re: [taosdata/TDengine] Software support for 32-bit system (#447)
还在计划中，估计年底左右。您说的32位系统，是x86的系统，还是arm的系统？
