### ISSUE TITLE
现在时间戳可以乱序插入了？

### ISSUE THREAD

**Issue by jadedrip** [taosdata/TDengine#4474]
我从 taos 的文档上理解插入数据的时间戳必须是有序的，但我使用 jdbc 环境做了测试，发现可以乱序插入数据，所以现在支持时间戳乱序插入了吗？
另外我插入了两条时间戳一样的数据，也没任何提示，但数据库里只有一条，所以数据冲突也是不会提示的吗？

PS: 测试版本 2.0.9

**Comment by sangshuduo** [comment]
是的，支持乱序。
插入相同时间戳数据默认后面插入的丢弃，不会提示。如果创建数据库的时候设置参数 update，例如 create database db update 1，后面插入的相同时间戳的数据会覆盖前面的数据。
