### ISSUE TITLE
Whether TDengine supports the distinct function?

### ISSUE THREAD

**Issue by AlexForMRD** [taosdata/TDengine#448]
TDengine是否考虑过滤去重, 类似MySQL那样, 因为有些查询是需要去重的, 没有这方面的支持数据统计查询不太好处理.

**Comment by hjxilinx** [comment]
您说的去重是说
>select distinct column_name from foo_table.

如上SQL语句中的distinct的功能吗？

**Comment by AlexForMRD** [comment]
是的, 类似 select count(distinct column_name) from foo_table.

**Comment by hjxilinx** [comment]
您可以提供使用这个函数的具体的场景吗？我不知道什么情况下需要这样的处理。谢谢！

**Comment by AlexForMRD** [comment]
我的场景是这样的: 我们的人脸识别会识别到很多的流水记录, 我们把这些记录存到TDengine里, 统计时需要按照interval()来统计, 但是需要去掉这个时间段相同的人, 即同一个人在一个interval里只算一个人. 我想统计的是这个interval内有多少个人(去重的结果)

**Comment by hjxilinx** [comment]
这样的需求可以使用count(distinct column_name)来查询。但是目前也仅限于此，其他函数的distinct我们暂不考虑支持。并且这个值并不是一个精确值，是一个准确度较高的近似值。

**Comment by AlexForMRD** [comment]
> 这样的需求可以使用count(distinct column_name)来查询。但是目前也仅限于此，其他函数的distinct我们暂不考虑支持。并且这个值并不是一个精确值，是一个准确度较高的近似值。

是的, 这样能满足业务就行.

**Comment by leiweibo** [comment]
>     select count(stock_symbol) from t_stock ;
>     count(stock_symbol) |
>     ======================
>             5128388|

但我执行 
> select count(distinct stocky_symbol) from t_stock;
直接报错
> TSDB error: invalid SQL: syntax error near "stock_symbol) from t_stock ;"

请问是哪个地方我的语法不对

**Comment by hjxilinx** [comment]
现在暂时不支持count(distinct stocky_symbol)，稍后的版本会支持该功能。

**Comment by zsp042** [comment]
现在支持了吗？

**Comment by chengjunjian** [comment]
这一稍后支持， 就是3年啊，到现在也没支持

**Comment by zhuyuan2015** [comment]
> 现在暂时不支持count(distinct stocky_symbol)，稍后的版本会支持该功能。

**这一稍后支持， 就是4年啊，到现在也没支持**

**Comment by HejiaHo** [comment]
这一稍后支持， 就是5年啊，到现在也没支持

> > 现在暂时不支持count(distinct stocky_symbol)，稍后的版本会支持该功能。
> 
> **这一稍后支持， 就是4年啊，到现在也没支持**

这一稍后支持， 就是5年啊，到现在也没支持

其实可以换种方式实现同样的效果，性能也不错
```sql
SELECT 
    count(1)
FROM (
    SELECT 
        DISTINCT symbol
    FROM stock
)
```

**Comment by HejiaHo** [comment]
> > 现在暂时不支持count(distinct stocky_symbol)，稍后的版本会支持该功能。
> 
> **这一稍后支持， 就是4年啊，到现在也没支持**

这一稍后支持， 就是5年啊，到现在也没支持

其实可以换种方式实现同样的效果，性能也不错
```sql
SELECT 
    count(1)
FROM (
    SELECT 
        DISTINCT symbol
    FROM stock
)
```

**Comment by yu285** [comment]
> > 现在暂时不支持count(distinct stocky_symbol)，稍后的版本会支持该功能。
> 
> **这一稍后支持， 就是4年啊，到现在也没支持**

![image](https://github.com/taosdata/TDengine/assets/74105241/e09f9a75-ff7e-47fa-9aa6-fcf2f78147bd)

**Comment by gedachao** [comment]
> > > 现在暂时不支持count(distinct stocky_symbol)，稍后的版本会支持该功能。
> > 
> > 
> > **这一稍后支持， 就是4年啊，到现在也没支持**
> 
> 这一稍后支持， 就是5年啊，到现在也没支持
> 
> 其实可以换种方式实现同样的效果，性能也不错
> 
> ```sql
> SELECT 
>     count(1)
> FROM (
>     SELECT 
>         DISTINCT symbol
>     FROM stock
> )
> ```

说好三年，三年之后又三年，三年之后又三年，都快十年了老大
