### ISSUE TITLE
集群版查询写入速度无提升；如何适应车联网架构

### ISSUE THREAD

**Issue by TheyAllCallMeTiga** [taosdata/TDengine#4487]
一台机器写入3G数据，使用的python，创建的超级表，按车划分，每次写1万条数据，需要850秒左右
按时间范围查询数据，花费46秒
搭建两台机器以后，重新写入读取一样。

集群版对效率有提升吗？还是说只做了备份

以后会支持修改和删除吗，有部分数据不太好，有时候需要删除或者修改值

我们有部分数据中，很多条数据是用的一个时间戳，在表中好像不是太好存储

**Comment by sangshuduo** [comment]
@WtyFile 请提供详细部署和使用过程
目前最新版本支持修改，需要在建数据库的时候指定 update 1 参数。暂时不支持删除。
不太理解什么叫用的一个时间戳不太好存储。请详细描述场景，数据内容，表结构等。

**Comment by WtyFile** [comment]
部署是在一台机器上启动，创建超级表，create table car(time timestamp,x double,y double....)tags(car binary(20));
写入数据由于需要写入超级表，每个csv数据文件中都会有不同车辆的数据，还需先用python读入，分组后再循环每次写入10000条（因为单条sql最多1MB），耗时850s左右；greenplum三机器耗时2200s，可以直接将整个csv   copy_from到数据库，不需要额外处理数据，感觉比tdengine方便。

然后两台机器重新部署tdengine，创建库表操作一致，然后show dnodes两个ready，写入读取数据时间相对单机不变，greenplum同时根据时间范围测读取数据，要比tdengine快很多

车子图像识别到的车道线数据是没有时间戳的，数据文件为 车id+时间.csv。 内容为
实线、[[x y z],[x y z],[x y z]...]、黄色
虚线、[[x y z],[x y z],[x y z]...]、黄色
虚线、[[x y z],[x y z],[x y z]...]、白色
这种格式，在tdengine中时间戳是唯一的，如何存储比较合适

**Comment by sangshuduo** [comment]
TDengine 支持使用 insert into tb1 file 'path/data.csv'; 语句把 CSV 文件插入到数据库中，CSV 内结构需要和表结构一致，结合上下文猜测你们的CSV里没有时间戳信息，需要先补充这一列才行。

写入方法没有看到是否使用多线程，batch size 多少。实现机制上 TDengine 可以支持大量客户端并发写入，可以利用客户端机器的性能加速。

TDengine 主要处理时序数据，如果没有时间戳或者根据时间范围查询的需求，是不适合用 TDengine 的。
