### ISSUE TITLE
新装 2.0.9.0 集群 求助，碰到：user:monitor, failed to auth user, mnode is not master

### ISSUE THREAD

**Issue by jadedrip** [taosdata/TDengine#4488]
新集群 1号机启动没有问题。
2号节点和3号节点 日志一直在刷 
12/08 17:07:23.505334 0x7fdd647f8700 MND user:root, failed to auth user, mnode is not master
12/08 17:07:23.505377 0x7fdd647f8700 DND user:root, send auth msg to mnodes
12/08 17:07:23.505945 0x7fdd647f8700 DND user:root, auth msg received from mnodes
12/08 17:07:23.506110 0x7fdd3f7fe700 MND msg:0x7fdd18000ca0, app:0x9 type:show in mread queue is redirected, numOfEps:2 inUse:0
12/08 17:07:23.739541 0x7fdd3effd700 MND msg:0x7fdd24000e30, app:0x3 type:heartbeat in mread queue is redirected, numOfEps:2 inUse:0
12/08 17:07:24.487436 0x7fdd3f7fe700 MND msg:0x7fdd24000e30, app:0x3 type:heartbeat in mread queue is redirected, numOfEps:2 inUse:0
12/08 17:07:25.244601 0x7fdd3effd700 MND msg:0x7fdd24000e30, app:0x3 type:heartbeat in mread queue is redirected, numOfEps:2 inUse:0
12/08 17:07:25.992414 0x7fdd3f7fe700 MND msg:0x7fdd24000e30, app:0x3 type:heartbeat in mread queue is redirected, numOfEps:2 inUse:0
12
这样的信息，在主节点上进入 taos shell 可以看到

taos> show dnodes;
   id   |           end_point            | vnodes | cores  |   status   | role  |       create_time       |      offline reason      |
======================================================================================================================================
      1 | redisSentinel1:6030            |      1 |      4 | ready      | any   | 2020-12-08 17:06:04.470 |                          |
      2 | redisSentinel2:6030            |      0 |      4 | ready      | any   | 2020-12-08 17:06:49.127 |                          |
      3 | redisSentinel3:6030            |      0 |      4 | ready      | any   | 2020-12-08 17:06:52.921 |                          |
Query OK, 3 row(s) in set (0.006782s)

请问这是怎么回事啊？我哪里没配置对吗？
附上日志，谁帮忙看看吧，拜托了。

[taosdlog.zip](https://github.com/taosdata/TDengine/files/5658137/taosdlog.zip)

**Comment by guanshengliang** [comment]
这是一个已知的BUG，下周发版时应该就会修复了。

**Comment by jadedrip** [comment]
有什么临时解决的办法吗？

**Comment by guanshengliang** [comment]
这个不影响使用，请 @xiaopingcs 验证一下新版本还有没有问题

**Comment by jadedrip** [comment]
新版本貌似已经 OK 了
