### ISSUE TITLE
Is there any way to select the newest record in multiple sub tables of one super table

### ISSUE THREAD

**Issue by effun** [taosdata/TDengine#449]
I have a super table with many sub tables attached. Now I want to select the newest one record from each sub table, and combine them into one single result set. Thus, I can tell user what status their devices are in real-time.
Is there any way to archive that in one SQL statement?
Thank you.

**Comment by hzcheng** [comment]
Yes, we have that function. Suppose the super table is **st**, just use:
```
select last_row(*) from st group by tbname;
```
in which, _tbname_ is a keyword meaning the name of the tables.

**Comment by effun** [comment]
It works, Thanks a lot.

`Query OK, 8760 row(s) in set (0.905333s)`
