### ISSUE TITLE
maximum number of sessions:300 is reached

### ISSUE THREAD

**Issue by Lao-Zhong** [taosdata/TDengine#4492]
server-version 1.6， client-version 1.6，python-3.6.9，每次insert都connect，插完后close；目前是大量的错误【login disconnected, login again.】
![Snipaste_2020-12-09_09-16-55](https://user-images.githubusercontent.com/39207755/101560943-5aef2d80-39ff-11eb-8830-e8631563d72f.png)

**Comment by sangshuduo** [comment]
@Lao-Zhong 请使用新版本，1.6 不再支持了。谢谢！

**Comment by Lao-Zhong** [comment]
> @ Lao-Zhong请使用新版本，1.6不再支持了。谢谢！
目前稳定的版本是多少，2.0.5.2？
