### ISSUE TITLE
TD1.6.6.1版本从默认目录迁移至数据盘/data/taos不生效

### ISSUE THREAD

**Issue by limitimes** [taosdata/TDengine#4493]
TD1.6.6.1版本单机从默认目录/var/lib/taos迁移至数据盘/data/taos不生效，配置文件已修改，服务重启依然不生效，数据仍然写到默认目录，这是为何？系统盘空间已爆满，在线等，谢谢。

**Comment by sangshuduo** [comment]
@limitimes  请使用新版本，1.6 不再支持了。谢谢！
