### ISSUE TITLE
集群中 TDengine 版本不一致的情况下，是否可以正常工作？

### ISSUE THREAD

**Issue by jadedrip** [taosdata/TDengine#4498]
考虑到业务需要，一般不能停机升级。那么当集群中某个节点版本更新以后，整个集群是否能够正常工作？

如果必须集群中所有机器版本一致，那么升级成本就有点大了，必须停机升级了。

**Comment by xiaopingcs** [comment]
这个我们目前不支持，会提示版本不匹配
taos> show dnodes;
   id   |           end_point            | vnodes | cores  |   status   | role  |       create_time       |      offline reason      |
======================================================================================================================================
      1 | node1:6030                     |      0 |      1 | ready      | any   | 2020-12-05 14:23:03.564 |                          |
      2 | node2:6030                     |      2 |      2 | offline    | any   | 2020-12-05 14:23:31.180 | version not match        |
      3 | node3:6030                     |      3 |      2 | ready      | any   | 2020-12-05 14:23:35.287 |                          |
Query OK, 3 row(s) in set (0.012966s)

**Comment by jadedrip** [comment]
停机升级的成本有点大，如果能保持接口稳定，最好还是支持不同版本共存比较好。

**Comment by chuangtim** [comment]
如果集群节点多，这个更新成本太高了

**Comment by jadedrip** [comment]
嗯，所以靠谱的做法是不更新……

zhuangtim ***@***.***> 于2021年7月31日周六 上午11:25写道：
