### ISSUE TITLE
官网RPM下载链问题

### ISSUE THREAD

**Issue by gaxuhongyu** [taosdata/TDengine#45]
立即开始页面：输入邮箱地址后图标一直旋转，无返回，且未收到相关下载链接邮件。

**Comment by nickevin** [comment]
下载确实有问题，异常信息：很抱歉，由于服务器问题，我们暂时无法处理你的请求。

**Comment by StoneT2000** [comment]
对不起，今天下载安装包的人实在是太多了，腾讯企业邮箱现在有限制了。我们正在处理这件事。

**Comment by gaxuhongyu** [comment]
> 对不起，今天下载安装包的人实在是太多了，腾讯企业邮箱现在有限制了。我们正在处理这件事。

现在已经能够下载了，谢谢！
