### ISSUE TITLE
taos_consume

### ISSUE THREAD

**Issue by cjjcode** [taosdata/TDengine#450]
java 调用TSDBJNIConnector，调用subscribe从当前时间订阅成功，根据文档提示，consume将会阻塞直到有新的数据，但是当前现象：并不会阻塞，而是循环load全表数据。请教一下，是否我的调用有问题还是当前设计如此？

**Comment by cjjcode** [comment]
我的代码如下：

TSDBJNIConnector connector=new TSDBJNIConnector();
long sub=connector.subscribe(......)//成功返回
while(true){
data=connector.consume(sub);
//消费data成功，但是不会阻塞，而是循环消费表中数据。
}

**Comment by liangyuanpeng** [comment]
如果是循环消费数据，不建议使用这一块功能，因为这不是一个正确的设计方式

**Comment by Flyerison** [comment]
@cjjcode 可以发一下代码吗？一直没有成功。。。

**Comment by localvar** [comment]
您好，目前2.0版已经发布，java的订阅接口进行了改进，所以现在关闭这个问题，如果您仍有订阅方面的需求，请参考：
https://www.taosdata.com/cn/documentation/connector-java/
