### ISSUE TITLE
alert 相关问题，请问一下，感谢

### ISSUE THREAD

**Issue by nzxxs4** [taosdata/TDengine#4502]
1.![image](https://user-images.githubusercontent.com/46189402/101596967-fa78e400-3a30-11eb-9b3a-932fbc13a531.png)
这个应该怎么改一下去掉\u0000
2.告警模块会时不时断开,问题类似于https://github.com/taosdata/TDengine/issues/4078

**Comment by nzxxs4** [comment]
图片内容就是
"summary":"主机aiops.web\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000内存超过70%

**Comment by xiaopingcs** [comment]
请问你是执行什么命令出现的这个问题？

**Comment by localvar** [comment]
这些乱码应该来自于报警规则，请检查规则的定义。

**Comment by nzxxs4** [comment]
你好 我是使用telegraf采集到taos数据库中，telegraf输入到文件还没有后面的空格，到taos数据库中就有了
![Uploading image.png…]()

**Comment by nzxxs4** [comment]
![捕获2](https://user-images.githubusercontent.com/46189402/101886395-5f217380-3bd6-11eb-8341-3ceb81152ae2.PNG)

**Comment by localvar** [comment]
这些 0 字符来自与数据库中查出的数据，请 @plum-lihui 帮助看是 go driver 的问题，还是原始数据有问题。

**Comment by plum-lihui** [comment]
使用telegraf采集到taos数据库中，是使用go程序完成插入的么？
插入到tdengine数据库后，先在taos shell查询看一下，显示的数据是不是正确的。
