### ISSUE TITLE
进入终端慢，查询速度慢

### ISSUE THREAD

**Issue by jonathanwx** [taosdata/TDengine#4503]
刚安装的tdengine使用taos进入shell差不多需要1分钟

使用show databases 需要20s
![image](https://user-images.githubusercontent.com/6824364/101597695-044f1700-3a32-11eb-8c4d-0bdce49e22bb.png)

配置如下
![image](https://user-images.githubusercontent.com/6824364/101597740-16c95080-3a32-11eb-92c7-61e63571bd0b.png)

cpu信息
![image](https://user-images.githubusercontent.com/6824364/101597873-437d6800-3a32-11eb-8347-04dd35d4e564.png)

磁盘速度测试
![image](https://user-images.githubusercontent.com/6824364/101598136-a8d15900-3a32-11eb-90a4-6ccce1f57e65.png)

**Comment by xiaopingcs** [comment]
你好，请把taos.cfg中的debugFlag设置为135，然后再试一次，把/var/log/taos/里面的log发过来我们看看

**Comment by sangshuduo** [comment]
长时间无回复，关闭
