### ISSUE TITLE
使用统一Connection进行数据插入操作，插入1000次左右连接断开

### ISSUE THREAD

**Issue by okjay** [taosdata/TDengine#4504]
**Bug Description**
tdengine 版本 2.0.9.0
使用语言：java
使用连接方式
private void initTaoS(String url, String user, String pwd) {
        try {
            Class.forName("com.taosdata.jdbc.TSDBDriver");
            Properties connProps = new Properties();
            connProps.setProperty(TSDBDriver.PROPERTY_KEY_USER, user);
            connProps.setProperty(TSDBDriver.PROPERTY_KEY_PASSWORD, pwd);
            connProps.setProperty(TSDBDriver.PROPERTY_KEY_CHARSET, "UTF-8");
            connProps.setProperty(TSDBDriver.PROPERTY_KEY_LOCALE, "en_US.UTF-8");
            connProps.setProperty(TSDBDriver.PROPERTY_KEY_TIME_ZONE, "UTC-8");
            this.mConnection = DriverManager.getConnection(url, connProps);
        } catch (Exception e) {
        }
    }
/**
创建表和查询等操作
*/
    private boolean execute(Connection connection, String sql) throws SQLException {
        Statement statement = connection.createStatement();
        boolean success = statement.execute(sql);
        statement.close();
        return success;
    }

使用mConnection进行 建表  插入数据不释放mConnection，释放再程序退出的时候处理
每次大概处理1000左右数据的时候会出现
TDengine Error: Unable to establish connection
日志中无明显的错误，只有这个failed
12/09 15:39:38.814074 0x7f45d37f6700 MND ERROR msg:0x7f4584000d60, app:0x55a table:0.dev_status.t2c37c5415fdc, failed to get table meta, table not exist
12/09 15:39:43.822669 0x7f45d27f4700 MND user:root, auth info is returned

**Comment by okjay** [comment]
jdbc版本2.0.12

**Comment by zyyang-taosdata** [comment]
感谢您的问题，从描述来看，我认为这个错误是由于client端在获取不到表的metadata造成的。我需要您粘贴应用报错和客户端日志，来进一步排查。请：
1. 清空客户端日志，并将taos.cfg中的debugFlag参数设置为135。
2. 重启java应用，并制造这个报错，将日志内容粘贴。日志taoslog.X默认在C:\\TDengine\log（windows）或/var/log/taos（linux）上。
谢谢。

**Comment by sangshuduo** [comment]
长时间没有回复，关闭
