### ISSUE TITLE
DB error: Unable to resolve FQDN

### ISSUE THREAD

**Issue by Lao-Zhong** [taosdata/TDengine#4506]
server有1.6.0.1升级到2.0.5.1后，client-2.0.5.1，show databases; 就报错了
![Snipaste_2020-12-09_16-11-54](https://user-images.githubusercontent.com/39207755/101602733-80992880-3a39-11eb-90d0-0fc9d561f071.png)
![Snipaste_2020-12-09_16-14-27](https://user-images.githubusercontent.com/39207755/101602800-a0305100-3a39-11eb-8974-e4112e824ac0.png)

**Comment by xiaopingcs** [comment]
请参考这篇文章： https://www.taosdata.com/blog/2020/09/11/1824.html

**Comment by xiaopingcs** [comment]
这个是很直接的问题，修改host之后应该就没有问题
