### ISSUE TITLE
after firstEp is expelled from the cluster, the cluster cannot be connected

### ISSUE THREAD

**Issue by lacezeng** [taosdata/TDengine#4508]
说明： 以下截图中可能存在master mnode不一致的情况，原因是测试中有对部分mnode做stop和start操作，导致master mnode切换了。
1. 问题点：master mnode节点被驱逐出集群后集群无法连接，为什么？
![image](https://user-images.githubusercontent.com/71378259/101624312-be577a80-3a54-11eb-806a-1a3d3017e9ee.png)
![image](https://user-images.githubusercontent.com/71378259/101624472-ed6dec00-3a54-11eb-9526-e28118a68852.png)

2. 配置信息: 版本2.0.9.0，集群节点数为4，mnode数为3，mnode分别为122,123,124。arbitrator为112。offlineThreshold为60。节点role默认。其他配置也默认。

3. 问题描述:
   3.1 停掉任意一个mnode节点，在被驱逐之前，集群数据库操作都正常，只是响应时间略有延迟，如下:
![image](https://user-images.githubusercontent.com/71378259/101625123-f4e1c500-3a55-11eb-807e-ba52b3c2540e.png)
![image](https://user-images.githubusercontent.com/71378259/101625507-76395780-3a56-11eb-86cf-6d44416c96f7.png)

   3.2 停掉slave mnode 123之后直至其被驱逐出集群，集群仍然正常。
![image](https://user-images.githubusercontent.com/71378259/101626353-ce248e00-3a57-11eb-8093-45c0078d55c6.png)

   3.3 停掉master mnode 直至其被驱逐出集群，之后集群开始无法连接。(做这一步之前除了log db其他的db已经被清理掉)
![image](https://user-images.githubusercontent.com/71378259/101626824-74709380-3a58-11eb-8bb0-31d56fdc6a01.png)
![image](https://user-images.githubusercontent.com/71378259/101627100-ce715900-3a58-11eb-80e6-c1bb013a2f57.png)

**Comment by sangshuduo** [comment]
112 有跑 tarbitrator 吗？为什么同时在 112 上跑 taosd 和 arbitrator？

**Comment by sangshuduo** [comment]
集群最后剩一个 mnode 是无法提供服务的，这是正常行为。

**Comment by lacezeng** [comment]
1. 112 有跑 tarbitrator 吗？为什么同时在 112 上跑 taosd 和 arbitrator？
问题：arbitrator不是在taosd的配置文件里面配置之后集群知道的吗？还是说arbitrator只能独立跑在一台集群外的机器上吗？
2. 集群最后剩一个 mnode 是无法提供服务的，这是正常行为。
问题：请问是怎么得出"集群只剩一个mnode"这个结论的呢？我的集群是四个节点，三个mnode，每个测试场景都是在集群正常的情况下进行的，应该不存在只剩最后一个mnode这种情况吧?
