### ISSUE TITLE
taosd throws error message after running for about 3 to 4 days

### ISSUE THREAD

**Issue by shiyongabc** [taosdata/TDengine#451]
错误信息：ERROR RPC TSC-mgmt cid:0 sid:1 id:monitor, dataLen:193 writtenLen:-1, not good, reason:Invalid argument

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.3]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.0]

**Comment by guanshengliang** [comment]
数据库不能正常使用？
还是仅仅打出一条出错日志

**Comment by shiyongabc** [comment]
不能正常使用，需要重启才能使用




------------------ 原始邮件 ------------------
发件人: "slguan"<notifications@github.com>;
发送时间: 2019年9月4日(星期三) 上午9:37
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
抄送: ""<574773374@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [taosdata/TDengine] 运行三四天后taosd报错 (#451)




数据库不能正常使用？
 还是仅仅打出一条出错日志

**Comment by guanshengliang** [comment]
这是一个比较古老的RPC的BUG
您的版本是1.6.1.0，这是刚开源时的版本，截止现在两个月时间里，我们修复了很多BUG
您可以拉新的代码或者版本进行测试
