### ISSUE TITLE
Can't run the service after installing tdengine-1.6.1.7.deb

### ISSUE THREAD

**Issue by pyfrog** [taosdata/TDengine#452]
Selecting previously unselected package tdengine.
(Reading database ... 52398 files and directories currently installed.)
Preparing to unpack tdengine-1.6.1.7.deb ...
Unpacking tdengine (1.6.1.7) ...
Setting up tdengine (1.6.1.7) ...
Start to install TDEngine...
sed: can't read /etc/inittab: No such file or directory
cp: cannot stat '%{init_d_dir}/taosd': No such file or directory
grep: /etc/inittab: No such file or directory
update-rc.d: error: unable to read /etc/init.d/taosd

TDengine is installed successfully!

To configure TDengine : edit /etc/taos/taos.cfg
To start TDengine     : sudo update-rc.d taosd default   for the first time
                      : sudo service taosd start  after
To access TDengine    : use taos in shell

TDengine is installed successfully!

输入taos：
Welcome to the TDengine shell, client version:1.6.1.7
TSDB error: failed to connect to server

于是启动
systemctl start taosd  提示：
Failed to start taosd.service: Unit taosd.service not found.

**Comment by guanshengliang** [comment]
请提供一下操作系统信息
从你给出的信息来看，这个操作系统比较老，不支持systemctl
