### ISSUE TITLE
DB error: Invalid Sync Configuration

### ISSUE THREAD

**Issue by zengchenri** [taosdata/TDengine#4524]
按照官网的提示，安装TDEngine服务后出现

**Comment by zengchenri** [comment]
添加附件:[files.zip](https://github.com/taosdata/TDengine/files/5676779/files.zip)

**Comment by sangshuduo** [comment]
log 里有 node1:6030 这样的 fqdn ，cfg 里没有，是数据目录有之前的旧数据吧？

**Comment by zengchenri** [comment]
是之前有数据造成的,sudo rm -rf /var/lib/taos/ 删除就可以了，非常感谢
