### ISSUE TITLE
查询性能

### ISSUE THREAD

**Issue by wanghuahui** [taosdata/TDengine#4525]
Ubuntu 16.04，taos: Client Version:2.0.9.0
按照taosdemo例子，将超级表中f1,f2,f3类型换成binary(16)，binary(16)和nchar(16)，查询子表中某个值，速度没有int类型快，是否字符型比int型查询效率低？
生成1000万个子表，每个子表标签唯一，按标签过滤查询时耗时数秒，并没有“千万级别规模的标签数据查询可以在毫秒级别返回”，有什么改进操作？或者你们文档中说的毫秒级别返回是在什么数据类型、什么条件下实现的？

**Comment by sangshuduo** [comment]
性能和数据建模、系统配置、硬件配置等都有关系。
