### ISSUE TITLE
Unable to resolve FQDN

### ISSUE THREAD

**Issue by hhfcyong** [taosdata/TDengine#4528]
windows环境，go语言连接。
FQDN本地hosts也配置了，ping也没有问题。但是代码连接数据库依然Unable to resolve FQDN

**Comment by sangshuduo** [comment]
信息太少，请先看下官网文档 FAQ 自查一下。

**Comment by dullduck** [comment]
[root@xxx TDengine-client-2.0.16.0]# taos -h xx.xx.xx.xx

Welcome to the TDengine shell from Linux, Client Version:2.0.16.0
Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.


taos> show databases;
              name              |      created_time       |   ntables   |   vgroups   | replica | quorum |  days  |   keep0,keep1,keep(D)    |  cache(MB)  |   blocks    |   minrows   |   maxrows   | wallevel |    fsync    | comp | cachelast | precision | update |   status   |
====================================================================================================================================================================================================================================================================================
 demo                           | 2021-02-18 15:40:16.291 |           1 |           1 |       1 |      1 |     10 | 3650,3650,3650           |          16 |           6 |         100 |        4096 |        1 |        3000 |    2 |         0 | ms        |      0 | ready      |
 log                            | 2021-02-18 15:31:24.123 |           4 |           1 |       1 |      1 |     10 | 30,30,30                 |           1 |           3 |         100 |        4096 |        1 |        3000 |    2 |         0 | us        |      0 | ready      |
Query OK, 2 row(s) in set (0.035868s)

taos> use demo;
Database changed.

taos> show tables;
           table_name           |      created_time       | columns |          stable_name           |          uid          |     tid     |    vgId     |
==========================================================================================================================================================
 t                              | 2021-02-18 15:40:55.657 |       2 |                                |       844424946914141 |           1 |           3 |
Query OK, 1 row(s) in set (0.040467s)

taos> select * from t;

**DB error: Unable to resolve FQDN (0.175752s)**



客户端连接服务器后（两者不是同一个机器），怎么不能执行select查询呢？
