### ISSUE TITLE
Questions about the design of data storage

### ISSUE THREAD

**Issue by withgakki** [taosdata/TDengine#453]
![image](https://user-images.githubusercontent.com/39128271/64167102-16c7c180-ce7b-11e9-91a8-3562aff37d5b.png)
请问，在tsdb文件夹下除了meterObj.v0记录表信息外，都是符号连接，主要信息都是在data下的，这样tsdb下存在这样的引用的设计是为什么呢

**Comment by withgakki** [comment]
就是没懂为什么要有这样的链接引用 😢

**Comment by hzcheng** [comment]
主要是为了统一接口，尤其是在配置多块硬盘时统一接口。

**Comment by withgakki** [comment]
> 主要是为了统一接口，尤其是在配置多块硬盘时统一接口。

大概懂你的意思了，还有一个问题请教下：
![image](https://user-images.githubusercontent.com/39128271/64253860-c4f16b00-cf50-11e9-9167-d4346cc7cbb2.png)
针对标签（tag）查询到子表是怎么进行的？是meters.db带有tag信息，一行一行的过滤么
