### ISSUE TITLE
about query log

### ISSUE THREAD

**Issue by wanghuahui** [taosdata/TDengine#4532]
**taos> select count(*) from meters;**
10亿条数据
Query OK, 1 row(s) in set (0.760020s)
下面是打印日志，在加粗的地方有两处明显耗时，这是什么原因导致，有解决办法吗？

12/11 11:16:41.022297 0x7f7f557c8700 MND user:root, auth info is returned
12/11 11:16:41.022436 0x7f7f9e7fc700 MND msg:0x7f7f24000db0, app:0x7 table:0.test.meters, table meta msg is received from thandle:0x1bfefd8, createFlag:0
12/11 11:16:41.022503 0x7f7f9e7fc700 MND msg:0x7f7f24000db0, app:0x7 stable:0.test.meters, uid:1564677807513647783 table meta is retrieved
12/11 11:16:41.024840 0x7f7f55fc9700 MND user:root, auth info is returned
12/11 11:16:41.025662 0x7f7f557c8700 MND user:root, auth info is returned
12/11 11:16:41.025860 0x7f7f55fc9700 MND user:root, auth info is returned
12/11 11:16:41.026444 0x7f7f557c8700 MND user:root, auth info is returned
12/11 11:16:41.026936 0x7f7f55fc9700 MND user:root, auth info is returned
12/11 11:16:41.027435 0x7f7f557c8700 MND user:root, auth info is returned
12/11 11:16:41.027562 0x7f7f7e7fc700 VND QInfo:0x7f7e94000b50 register qhandle to connect:0x1bff440
12/11 11:16:41.027578 0x7f7f7e7fc700 VND vgId:53, QInfo:0x7f7e94000b50, dnode query msg disposed, create qhandle and returns to app
12/11 11:16:41.027606 0x7f7f7e7fc700 VND QInfo:0x7f7e94000b50 add to vread queue for exec query
12/11 11:16:41.027714 0x7f7f7e7fc700 VND vgId:53, QInfo:0x7f7e94000b50, dnode continues to exec query
12/11 11:16:41.027846 0x7f7f5ffd7700 VND QInfo:0x7f7e7c000b50 register qhandle to connect:0x1bff2c8
12/11 11:16:41.027871 0x7f7f5ffd7700 VND vgId:52, QInfo:0x7f7e7c000b50, dnode query msg disposed, create qhandle and returns to app
12/11 11:16:41.027901 0x7f7f5ffd7700 VND QInfo:0x7f7e7c000b50 add to vread queue for exec query
12/11 11:16:41.027990 0x7f7f5ffd7700 VND vgId:52, QInfo:0x7f7e7c000b50, dnode continues to exec query
12/11 11:16:41.028213 0x7f7f7c7f8700 VND QInfo:0x7f7e78000b50 register qhandle to connect:0x1bfefd8
12/11 11:16:41.028214 0x7f7f957fa700 VND vgId:53, QInfo:0x7f7e94000b50, retrieve msg is disposed, free:22, conn:0x1bff440
12/11 11:16:41.028298 0x7f7f7c7f8700 VND vgId:50, QInfo:0x7f7e78000b50, dnode query msg disposed, create qhandle and returns to app
12/11 11:16:41.028307 0x7f7f957fa700 VND QInfo:0x7f7e94000b50 register qhandle to connect:0x1bff440
12/11 11:16:41.028322 0x7f7f7c7f8700 VND QInfo:0x7f7e78000b50 add to vread queue for exec query
12/11 11:16:41.028328 0x7f7f6c7e4700 VND vgId:50, QInfo:0x7f7e78000b50, dnode continues to exec query
12/11 11:16:41.028342 0x7f7f7ffff700 VND QInfo:0x7f7e98000ad0 register qhandle to connect:0x1bff5b8
12/11 11:16:41.028357 0x7f7f7ffff700 VND vgId:54, QInfo:0x7f7e98000ad0, dnode query msg disposed, create qhandle and returns to app
12/11 11:16:41.028383 0x7f7f7ffff700 VND QInfo:0x7f7e98000ad0 add to vread queue for exec query
12/11 11:16:41.028418 0x7f7f7c7f8700 VND vgId:54, QInfo:0x7f7e98000ad0, dnode continues to exec query
12/11 11:16:41.028596 0x7f7f7b7f6700 VND vgId:50, QInfo:0x7f7e78000b50, retrieve msg is disposed, free:22, conn:0x1bfefd8
12/11 11:16:41.028629 0x7f7f7b7f6700 VND QInfo:0x7f7e78000b50 register qhandle to connect:0x1bfefd8
12/11 11:16:41.028636 0x7f7f7f7fe700 VND vgId:54, QInfo:0x7f7e98000ad0, retrieve msg is disposed, free:22, conn:0x1bff5b8
12/11 11:16:41.028655 0x7f7f7f7fe700 VND QInfo:0x7f7e98000ad0 register qhandle to connect:0x1bff5b8
12/11 11:16:41.028909 0x7f7f6dfe7700 VND QInfo:0x7f7e80000b50 register qhandle to connect:0x1bff150
12/11 11:16:41.028942 0x7f7f6dfe7700 VND vgId:51, QInfo:0x7f7e80000b50, dnode query msg disposed, create qhandle and returns to app
12/11 11:16:41.028987 0x7f7f96ffd700 VND vgId:51, QInfo:0x7f7e80000b50, dnode continues to exec query
12/11 11:16:41.029521 0x7f7f7dffb700 VND QInfo:0x7f7e8c000b80 register qhandle to connect:0x1bff8a8
12/11 11:16:41.029527 0x7f7f7dffb700 VND vgId:56, QInfo:0x7f7e8c000b80, dnode query msg disposed, create qhandle and returns to app
12/11 11:16:41.029531 0x7f7f7dffb700 VND QInfo:0x7f7e8c000b80 add to vread queue for exec query
12/11 11:16:41.029552 0x7f7f7effd700 VND vgId:56, QInfo:0x7f7e8c000b80, dnode continues to exec query
12/11 11:16:41.028265 0x7f7f55fc9700 MND user:root, auth info is returned
12/11 11:16:41.029585 0x7f7f7ffff700 VND vgId:56, QInfo:0x7f7e8c000b80, retrieve msg is disposed, free:22, conn:0x1bff8a8
12/11 11:16:41.029590 0x7f7f7ffff700 VND QInfo:0x7f7e8c000b80 register qhandle to connect:0x1bff8a8
12/11 11:16:41.028254 0x7f7f95ffb700 VND vgId:52, QInfo:0x7f7e7c000b50, retrieve msg is disposed, free:22, conn:0x1bff2c8
12/11 11:16:41.029616 0x7f7f95ffb700 VND QInfo:0x7f7e7c000b50 register qhandle to connect:0x1bff2c8
12/11 11:16:41.029824 0x7f7f747ee700 VND QInfo:0x7f7e88000bb0 register qhandle to connect:0x1bff730
12/11 11:16:41.029827 0x7f7f747ee700 VND vgId:55, QInfo:0x7f7e88000bb0, dnode query msg disposed, create qhandle and returns to app
12/11 11:16:41.029833 0x7f7f747ee700 VND QInfo:0x7f7e88000bb0 add to vread queue for exec query
12/11 11:16:41.029852 0x7f7f747ee700 VND vgId:55, QInfo:0x7f7e88000bb0, dnode continues to exec query
12/11 11:16:41.030178 0x7f7f6d7e6700 VND QInfo:0x7f7e68000b80 register qhandle to connect:0x1bffa20
12/11 11:16:41.030182 0x7f7f6d7e6700 VND vgId:57, QInfo:0x7f7e68000b80, dnode query msg disposed, create qhandle and returns to app
12/11 11:16:41.030185 0x7f7f6d7e6700 VND QInfo:0x7f7e68000b80 add to vread queue for exec query
12/11 11:16:41.030209 0x7f7f6d7e6700 VND vgId:57, QInfo:0x7f7e68000b80, dnode continues to exec query
12/11 11:16:41.033339 0x7f7f6dfe7700 VND QInfo:0x7f7e80000b50 add to vread queue for exec query
12/11 11:16:41.033407 0x7f7f6dfe7700 VND vgId:55, QInfo:0x7f7e88000bb0, retrieve msg is disposed, free:22, conn:0x1bff730
12/11 11:16:41.033413 0x7f7f6dfe7700 VND QInfo:0x7f7e88000bb0 register qhandle to connect:0x1bff730
12/11 11:16:41.033461 0x7f7f94ff9700 VND vgId:51, QInfo:0x7f7e80000b50, retrieve msg is disposed, free:22, conn:0x1bff150
12/11 11:16:41.033468 0x7f7f94ff9700 VND QInfo:0x7f7e80000b50 register qhandle to connect:0x1bff150
12/11 11:16:41.033475 0x7f7f7dffb700 VND vgId:57, QInfo:0x7f7e68000b80, retrieve msg is disposed, free:22, conn:0x1bffa20
**12/11 11:16:41.033480 0x7f7f7dffb700 VND QInfo:0x7f7e68000b80 register qhandle to connect:0x1bffa20
12/11 11:16:41.365823 0x7f7f95ffb700 VND QInfo:0x7f7e7c000b50 add to vread queue for exec query**
12/11 11:16:41.365881 0x7f7f95ffb700 VND vgId:52, QInfo:0x7f7e7c000b50, dnode continues to exec query
12/11 11:16:41.365952 0x7f7f95ffb700 VND vgId:52, QInfo:0x7f7e7c000b50, retrieve msg is disposed, free:22, conn:0x1bff2c8
12/11 11:16:41.365958 0x7f7f95ffb700 VND QInfo:0x7f7e7c000b50 register qhandle to connect:0x1bff2c8
12/11 11:16:41.365961 0x7f7f95ffb700 VND QInfo:0x7f7e7c000b50 exec completed, free handle:1
12/11 11:16:41.369136 0x7f7f7f7fe700 VND QInfo:0x7f7e98000ad0 add to vread queue for exec query
12/11 11:16:41.369142 0x7f7f5ffd7700 VND vgId:54, QInfo:0x7f7e98000ad0, dnode continues to exec query
12/11 11:16:41.369258 0x7f7f95ffb700 VND vgId:54, QInfo:0x7f7e98000ad0, retrieve msg is disposed, free:22, conn:0x1bff5b8
12/11 11:16:41.369265 0x7f7f95ffb700 VND QInfo:0x7f7e98000ad0 register qhandle to connect:0x1bff5b8
12/11 11:16:41.369267 0x7f7f95ffb700 VND QInfo:0x7f7e98000ad0 exec completed, free handle:1
12/11 11:16:41.370398 0x7f7f6dfe7700 VND QInfo:0x7f7e88000bb0 add to vread queue for exec query
12/11 11:16:41.370404 0x7f7f7c7f8700 VND vgId:55, QInfo:0x7f7e88000bb0, dnode continues to exec query
12/11 11:16:41.370464 0x7f7f5ffd7700 VND vgId:55, QInfo:0x7f7e88000bb0, retrieve msg is disposed, free:22, conn:0x1bff730
12/11 11:16:41.370471 0x7f7f5ffd7700 VND QInfo:0x7f7e88000bb0 register qhandle to connect:0x1bff730
12/11 11:16:41.370473 0x7f7f5ffd7700 VND QInfo:0x7f7e88000bb0 exec completed, free handle:1
12/11 11:16:41.373086 0x7f7f7f7fe700 VND vgId:56, QInfo:0x7f7e8c000b80, dnode continues to exec query
12/11 11:16:41.373080 0x7f7f7ffff700 VND QInfo:0x7f7e8c000b80 add to vread queue for exec query
12/11 11:16:41.373202 0x7f7f95ffb700 VND vgId:56, QInfo:0x7f7e8c000b80, retrieve msg is disposed, free:22, conn:0x1bff8a8
12/11 11:16:41.373209 0x7f7f95ffb700 VND QInfo:0x7f7e8c000b80 register qhandle to connect:0x1bff8a8
12/11 11:16:41.373212 0x7f7f95ffb700 VND QInfo:0x7f7e8c000b80 exec completed, free handle:1
12/11 11:16:41.375490 0x7f7f957fa700 VND QInfo:0x7f7e94000b50 add to vread queue for exec query
12/11 11:16:41.375519 0x7f7f747ee700 VND vgId:53, QInfo:0x7f7e94000b50, dnode continues to exec query
12/11 11:16:41.375596 0x7f7f7c7f8700 VND vgId:53, QInfo:0x7f7e94000b50, retrieve msg is disposed, free:22, conn:0x1bff440
12/11 11:16:41.375604 0x7f7f7c7f8700 VND QInfo:0x7f7e94000b50 register qhandle to connect:0x1bff440
12/11 11:16:41.375607 0x7f7f7c7f8700 VND QInfo:0x7f7e94000b50 exec completed, free handle:1
12/11 11:16:41.377836 0x7f7f7dffb700 VND QInfo:0x7f7e68000b80 add to vread queue for exec query
12/11 11:16:41.377841 0x7f7f6dfe7700 VND vgId:57, QInfo:0x7f7e68000b80, dnode continues to exec query
12/11 11:16:41.377926 0x7f7f5ffd7700 VND vgId:57, QInfo:0x7f7e68000b80, retrieve msg is disposed, free:22, conn:0x1bffa20
12/11 11:16:41.377932 0x7f7f5ffd7700 VND QInfo:0x7f7e68000b80 register qhandle to connect:0x1bffa20
**12/11 11:16:41.377934 0x7f7f5ffd7700 VND QInfo:0x7f7e68000b80 exec completed, free handle:1
12/11 11:16:41.775905 0x7f7f94ff9700 VND QInfo:0x7f7e80000b50 add to vread queue for exec query**
12/11 11:16:41.775932 0x7f7f7effd700 VND vgId:51, QInfo:0x7f7e80000b50, dnode continues to exec query
12/11 11:16:41.776032 0x7f7f7f7fe700 VND vgId:51, QInfo:0x7f7e80000b50, retrieve msg is disposed, free:22, conn:0x1bff150
12/11 11:16:41.776041 0x7f7f7f7fe700 VND QInfo:0x7f7e80000b50 register qhandle to connect:0x1bff150
12/11 11:16:41.776044 0x7f7f7f7fe700 VND QInfo:0x7f7e80000b50 exec completed, free handle:1
12/11 11:16:41.780899 0x7f7f7b7f6700 VND QInfo:0x7f7e78000b50 add to vread queue for exec query
12/11 11:16:41.780930 0x7f7f7b7f6700 VND vgId:50, QInfo:0x7f7e78000b50, dnode continues to exec query
12/11 11:16:41.781019 0x7f7f95ffb700 VND vgId:50, QInfo:0x7f7e78000b50, retrieve msg is disposed, free:22, conn:0x1bfefd8
12/11 11:16:41.781028 0x7f7f95ffb700 VND QInfo:0x7f7e78000b50 register qhandle to connect:0x1bfefd8
12/11 11:16:41.781029 0x7f7f95ffb700 VND QInfo:0x7f7e78000b50 exec completed, free handle:1
12/11 11:17:26.444590 0x7f7fa83b9700 MND balance function is scheduled by timer

**Comment by sangshuduo** [comment]
10条记录 0.76 秒还不满足需求吗?

**Comment by wanghuahui** [comment]
taosdemo提供的用例，同样10亿数据，count(*)用时几十毫秒，为什么会有这么大差异？日志信息中两处明显耗时是什么原因造成的？

**Comment by sangshuduo** [comment]
请把 taos.cfg 里的 qDebugFlag 改成 135 再跑一次，然后把 log 以附件的形式贴上来我们看一下。

另外硬件配置是什么?

**Comment by sangshuduo** [comment]
没有更多信息，暂时关闭。
