### ISSUE TITLE
服务端rpcClose不能关闭

### ISSUE THREAD

**Issue by whwqs** [taosdata/TDengine#4534]
**Bug Description**
（1）服务端rpcClose不能关闭
（2）屏蔽rpcTcp.c 197行pthread_join(pServerObj->thread, NULL); rpcClose可以关闭，但再服务端rpcOpen报错

**To Reproduce**
（1）void * pRpc = rpcOpen(服务端信息); rpcClose(pRpc);  可出现
（2）先屏蔽代码，然后：void * pRpc = rpcOpen(服务端信息); rpcClose(pRpc); rpcOpen(服务端信息); 可出现

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by sangshuduo** [comment]
请提供完整过程描述，最好包含相关代码

**Comment by whwqs** [comment]
win 7 下：
（1）服务端rpcClose不能关闭：
复现bug示例代码：
`#include "trpc.h"
#include <tglobal.h>

int main(int argc, char* argv[]) {

   SRpcInit rpcInit;
  memset(&rpcInit, 0, sizeof(rpcInit));
  rpcInit.localPort = 7000;
  rpcInit.label = "SER";
  rpcInit.numOfThreads = 1;
  rpcInit.cfp = NULL;
  rpcInit.sessions = 1000;
  rpcInit.idleTime = tsShellActivityTimer * 1500;
  rpcInit.afp = NULL;
  rpcInit.connType = TAOS_CONN_SERVER;
  void* pRpc = rpcOpen(&rpcInit);
  if (NULL != pRpc) {
    rpcClose(pRpc);
  }
  return 0;
}
`
初步分析原因，应该是线程被阻塞在rpcTcp.c第232行
connFd = accept(pServerObj->fd, (struct sockaddr *)&caddr, &addrlen);
（2）如果解决上面的bug，保证了rpcClose能正常关闭，这时用下面的代码会在初始化定时器时产生使用空指针的bug
`#include "trpc.h"
#include <tglobal.h>

int main(int argc, char* argv[]) {

   SRpcInit rpcInit;
  memset(&rpcInit, 0, sizeof(rpcInit));
  rpcInit.localPort = 7000;
  rpcInit.label = "SER";
  rpcInit.numOfThreads = 1;
  rpcInit.cfp = NULL;
  rpcInit.sessions = 1000;
  rpcInit.idleTime = tsShellActivityTimer * 1500;
  rpcInit.afp = NULL;
  rpcInit.connType = TAOS_CONN_SERVER;
  void* pRpc = rpcOpen(&rpcInit);
  if (NULL != pRpc) {
    rpcClose(pRpc);
    pRpc = rpcOpen(&rpcInit);
  }
  return 0;
}
`
初步分析是因为rpcClose后tmrCtrlMutex变成空，再一次rpcOpen，因为taosTmrModuleInit只能执行一次，tmrCtrlMutex没有办法再初始化。

**Comment by sangshuduo** [comment]
您的目的是什么呢?

**Comment by sangshuduo** [comment]
您的目的是什么呢?

**Comment by whwqs** [comment]
服务端调用rpcClose，代码只能走到rpcMain.c的第325行，然后阻塞在此，后面的工作无法进行了。

**Comment by sangshuduo** [comment]
不是太明白，这和使用 TDengine 对时序数据处理有关吗？

**Comment by whwqs** [comment]
如果支持云架构，我开了两个实例，后来想关一个，用一个就可以，你这关不了，就是问题啊！

**Comment by sangshuduo** [comment]
还是不明白您为什么需要直接使用内部接口。客户端应用使用TDengine官方连接器API。服务端目前只支持Linux，如果需要在同一台机器启动两个taosd实例可以使用不同的端口。

**Comment by whwqs** [comment]
这段时间主要想把rpc这块单独拿出来用，在我的fork中做了一些尝试，rpc机制不错，然后在做服务端关闭时发现这些问题。也不是什么大问题。

**Comment by whwqs** [comment]
在使用rpc中有时会出现服务端UdP收到消息不能被parse,然后freerpccontent抱不可读闪存错误。

**Comment by sangshuduo** [comment]
这已经超过TDengine产品和服务的范围了。欢迎针对TDengine产品本身的问题进行讨论或者贡献代码。

**Comment by whwqs** [comment]
好的，这个问题先关闭了。

**Comment by whwqs** [comment]
虽然已经关闭了，但今天尝试解决了里面提到的两个问题，并在linux和windows下验证通过，为此记录一下，也许有些帮助。
解决（1）rpcClose阻塞问题：
只需要修改rpcTcp.c文件，我把代码贴在下面，**粗体**是需要添加的代码：
`
......
typedef struct {
  SOCKET      fd;
  uint32_t    ip;
  uint16_t    port;
  char        label[TSDB_LABEL_LEN];
  int         numOfThreads;
  void *      shandle;
  SThreadObj **pThreadObj;
  pthread_t   thread;
  **bool         stop;//for taosAcceptTcpConnection**
} SServerObj;

......

void *taosInitTcpServer(uint32_t ip, uint16_t port, char *label, int numOfThreads, void *fp, void *shandle) {
  SServerObj *pServerObj;
  SThreadObj *pThreadObj;

  pServerObj = (SServerObj *)calloc(sizeof(SServerObj), 1);
  if (pServerObj == NULL) {
    tError("TCP:%s no enough memory", label);
    terrno = TAOS_SYSTEM_ERROR(errno); 
    return NULL;
  }

  pServerObj->fd = -1;
  taosResetPthread(&pServerObj->thread);
  pServerObj->ip = ip;
  pServerObj->port = port;
  tstrncpy(pServerObj->label, label, sizeof(pServerObj->label));
  pServerObj->numOfThreads = numOfThreads;
  **pServerObj->stop = false;//init false**

  pServerObj->pThreadObj = (SThreadObj **)calloc(sizeof(SThreadObj *), numOfThreads);
  if (pServerObj->pThreadObj == NULL) {
    tError("TCP:%s no enough memory", label);
    terrno = TAOS_SYSTEM_ERROR(errno); 
    free(pServerObj);
    return NULL;
  }

 ......
void taosStopTcpServer(void *handle) {
  SServerObj *pServerObj = handle;

  if (pServerObj == NULL) return;
  if(pServerObj->fd >=0) shutdown(pServerObj->fd, SHUT_RD);

  if (taosCheckPthreadValid(pServerObj->thread)) {  
    **//for break taosAcceptTcpConnection
    SOCKET   sockFd;
    pServerObj->stop = true;//set true for taosAcceptTcpConnection when accept below socket to break
    uint32_t peerIp = taosGetIpFromFqdn("127.0.0.1");    
    sockFd = taosOpenTcpClientSocket(peerIp, pServerObj->port, 0);**    
    if (taosComparePthread(pServerObj->thread, pthread_self())) {
      pthread_detach(pthread_self());
    } else {
      pthread_join(pServerObj->thread, NULL);
    }
    **taosCloseSocket(sockFd);**
  }

  tDebug("%s TCP server is stopped", pServerObj->label);
}

......

static void *taosAcceptTcpConnection(void *arg) {
  SOCKET             connFd = -1;
  struct sockaddr_in caddr;
  int                threadId = 0;
  SThreadObj        *pThreadObj;
  SServerObj        *pServerObj;

  pServerObj = (SServerObj *)arg;
  tDebug("%s TCP server is ready, ip:0x%x:%hu", pServerObj->label, pServerObj->ip, pServerObj->port);

  while (1) {
    socklen_t addrlen = sizeof(caddr);
    connFd = accept(pServerObj->fd, (struct sockaddr *)&caddr, &addrlen);
    
   
**if (pServerObj->stop) 
{
      //when accept rpcClose sended socket
      tDebug("%s TCP server stop accepting new connections by rpcClose, exiting", pServerObj->label);
      break;
    }**

    if (connFd == -1) {
      if (errno == EINVAL) {
        tDebug("%s TCP server stop accepting new connections, exiting", pServerObj->label);
        break;
      }

      tError("%s TCP accept failure(%s)", pServerObj->label, strerror(errno));
      continue;
    }    
......
`

**Comment by whwqs** [comment]
解决（2）rpcClose正常关闭后，再一次rpcOpen开启服务端，tmrCtrlMutex为空的问题，只需要修改ttimer.c，如下：
`
......
void taosTmrCleanUp(void* handle) {
  tmr_ctrl_t* ctrl = (tmr_ctrl_t*)handle;
  if (ctrl == NULL || ctrl->label[0] == 0) {
    return;
  }

  tmrDebug("%s timer controller is cleaned up.", ctrl->label);
  ctrl->label[0] = 0;

  pthread_mutex_lock(&tmrCtrlMutex);
  ctrl->next = unusedTmrCtrl;
  numOfTmrCtrl--;
  unusedTmrCtrl = ctrl;
  pthread_mutex_unlock(&tmrCtrlMutex);

  if (numOfTmrCtrl <=0) {
    taosUninitTimer();

    taosCleanUpScheduler(tmrQhandle);

    for (int i = 0; i < tListLen(wheels); i++) {
      time_wheel_t* wheel = wheels + i;
      pthread_mutex_destroy(&wheel->mutex);
      free(wheel->slots);
    }

    pthread_mutex_destroy(&tmrCtrlMutex);

    for (size_t i = 0; i < timerMap.size; i++) {
      timer_list_t* list = timerMap.slots + i;
      tmr_obj_t* t = list->timers;
      while (t != NULL) {
        tmr_obj_t* next = t->mnext;
        free(t);
        t = next;
      }
    }
    free(timerMap.slots);
    free(tmrCtrls);
**// 添加下面代码**
    //restore tmrModuleInit
    #if defined(LINUX)
        tmrModuleInit = 0;
    #elif defined(WINDOWS)
        tmrModuleInit.done = PTW32_FALSE;
        tmrModuleInit.lock = 0;
        tmrModuleInit.reserved1 = 0;
        tmrModuleInit.reserved2 = 0;
    #endif
**// 添加结束**
    tmrDebug("timer module is cleaned up");
  }
}
......
`
