### ISSUE TITLE
Invalid use of fetchall

### ISSUE THREAD

**Issue by Lao-Zhong** [taosdata/TDengine#4537]
**Bug Description**

![Snipaste_2020-12-11_15-56-39](https://user-images.githubusercontent.com/39207755/101877825-92a9d100-3bc9-11eb-89d0-1743a8113bb4.png)
![Snipaste_2020-12-11_15-56-02](https://user-images.githubusercontent.com/39207755/101877866-a1908380-3bc9-11eb-835a-d171c4360b72.png)

**Comment by sangshuduo** [comment]
tbname 的用法请参考官方文档 https://www.taosdata.com/cn/documentation/taos-sql/
