### ISSUE TITLE
RESTful Connector

### ISSUE THREAD

**Issue by iotsharer** [taosdata/TDengine#454]
使用RESTful Connector是否可以支持在同时body里连续存在多个sql语句，例如：
create database if not exists db1
use db1
create table if not exists tb1 (ts timestamp, temperature int, humidity float)
insert into tb1 values('2010-07-23 11:01:02.000', 37, 50.1)
insert into tb1 values(now, 36, 47.8);    
insert into tb1 values(now+1a, 38, 65.3); 
当然可以通过多次调用RESTful API实现，但是不知道这样是否就失去了使用TDgine的价值
（因为官方文档相关内容较少，本人刚刚接触RESTful 可能更多的是自身原因，不知道正确的调用方法该如何写）

**Comment by plum-lihui** [comment]
一次post请求，只能携带一条sql语句。比如create database， create table， insert into等。
但insert into是可以合并的，例如你上面的几条insert语句合并如下：
insert into tb1 values('2010-07-23 11:01:02.000', 37, 50.1)  (now, 36, 47.8) (now+1a, 38, 65.3);
当然还有多张table也可以合并，比如：insert into tb1 values('2010-07-23 11:01:02.000', 37, 50.1)  (now, 36, 47.8) (now+1a, 38, 65.3) tb2 values('2010-07-23 11:01:02.000', 37, 50.1)  (now, 36, 47.8) (now+1a, 38, 65.3) tbn values ().......;  但要保证一条sql语句不能超过64k。
