### ISSUE TITLE
查询数据时间多了8个小时

### ISSUE THREAD

**Issue by zed-hj** [taosdata/TDengine#4552]
Bug Description：
在window10 系统中使用客户端直连工具查询结果时间是对的，
但是linux 上查询出来的结果多了8小时，加了时间判断返回的数量也是对的。

**这是windows客户端查出来的数据**：
![image](https://user-images.githubusercontent.com/35823876/101980489-b4c25280-3ca0-11eb-8e52-172b73c83c6a.png)

**这是linux客户端的数据**：
![image](https://user-images.githubusercontent.com/35823876/101980524-fc48de80-3ca0-11eb-84aa-a8802b8a69ec.png)

**tdengine启动日志**：

TDengine:[1]: Starting TDengine service...
12/12 17:40:26.334912 0x7f3d30c05740 UTL the old unlimited para: rlim_cur=18446744073709551615, rlim_max=18446744073709551615
12/12 17:40:26.334952 0x7f3d30c05740 UTL the new unlimited para: rlim_cur=18446744073709551615, rlim_max=18446744073709551615
12/12 17:40:26.334991 0x7f3d30c05740 UTL _sysctl(kern_core_uses_pid) set fail: Function not implemented
12/12 17:40:26.334998 0x7f3d30c05740 UTL The old core_uses_pid[4]: 0
12/12 17:40:26.335007 0x7f3d30c05740 UTL _sysctl(kern_core_uses_pid) get fail: Function not implemented
12/12 17:40:26.335013 0x7f3d30c05740 UTL The new core_uses_pid[4]: 0
12/12 17:40:26.335891 0x7f3d30c05740 UTL localEp is: izwz9h6831v1p5a8i1jckqz:6030
12/12 17:40:26.337062 0x7f3d30c05740 UTL ERROR locale not configured, set to system default:en_US.UTF-8
12/12 17:40:26.337094 0x7f3d30c05740 UTL WARN charset not configured, set to system default:UTF-8
12/12 17:40:26.337198 0x7f3d30c05740 UTL timezone is set to Asia/Shanghai by config file
12/12 17:40:26.337213 0x7f3d30c05740 UTL timezone format changed to (CST, +0800)
12/12 17:40:26.337224 0x7f3d30c05740 UTL    taos config & system info:
12/12 17:40:26.337233 0x7f3d30c05740 UTL ==================================
12/12 17:40:26.337242 0x7f3d30c05740 UTL  firstEp:                izwz9h6831v1p5a8i1jckqz:6030
12/12 17:40:26.337252 0x7f3d30c05740 UTL  secondEp:               izwz9h6831v1p5a8i1jckqz:6030
12/12 17:40:26.337259 0x7f3d30c05740 UTL  fqdn:                   izwz9h6831v1p5a8i1jckqz
12/12 17:40:26.337266 0x7f3d30c05740 UTL  serverPort:             6030
12/12 17:40:26.337273 0x7f3d30c05740 UTL  configDir:              /etc/taos
12/12 17:40:26.337279 0x7f3d30c05740 UTL  logDir:                 /var/log/taos
12/12 17:40:26.337287 0x7f3d30c05740 UTL  scriptDir:              /etc/taos
12/12 17:40:26.337299 0x7f3d30c05740 UTL  dataDir:                /var/lib/taos
12/12 17:40:26.337308 0x7f3d30c05740 UTL  arbitrator:
12/12 17:40:26.337318 0x7f3d30c05740 UTL  numOfThreadsPerCore:    1.000000
12/12 17:40:26.337354 0x7f3d30c05740 UTL  ratioOfQueryThreads:    0.500000
12/12 17:40:26.337364 0x7f3d30c05740 UTL  numOfMnodes:            3
12/12 17:40:26.337375 0x7f3d30c05740 UTL  vnodeBak:               1
12/12 17:40:26.337384 0x7f3d30c05740 UTL  telemetryReporting:     1
12/12 17:40:26.337394 0x7f3d30c05740 UTL  balance:                1
12/12 17:40:26.337403 0x7f3d30c05740 UTL  balanceInterval:        300
12/12 17:40:26.337412 0x7f3d30c05740 UTL  role:                   0
12/12 17:40:26.337421 0x7f3d30c05740 UTL  maxTmrCtrl:             512
12/12 17:40:26.337431 0x7f3d30c05740 UTL  monitorInterval:        30(s)
12/12 17:40:26.337440 0x7f3d30c05740 UTL  offlineThreshold:       8640000(s)
12/12 17:40:26.337449 0x7f3d30c05740 UTL  rpcTimer:               1000(ms)
12/12 17:40:26.337459 0x7f3d30c05740 UTL  rpcMaxTime:             600(s)
12/12 17:40:26.337468 0x7f3d30c05740 UTL  statusInterval:         1(s)
12/12 17:40:26.337478 0x7f3d30c05740 UTL  shellActivityTimer:     3(s)
12/12 17:40:26.337488 0x7f3d30c05740 UTL  tableMetaKeepTimer:     7200(s)
12/12 17:40:26.337497 0x7f3d30c05740 UTL  minSlidingTime:         10(ms)
12/12 17:40:26.337504 0x7f3d30c05740 UTL  minIntervalTime:        10(ms)
12/12 17:40:26.337514 0x7f3d30c05740 UTL  maxStreamCompDelay:     20000(ms)
12/12 17:40:26.337525 0x7f3d30c05740 UTL  maxFirstStreamCompDelay:10000(ms)
12/12 17:40:26.338823 0x7f3d30c05740 UTL  retryStreamCompDelay:   10(ms)
12/12 17:40:26.338836 0x7f3d30c05740 UTL  streamCompDelayRatio:   0.100000
12/12 17:40:26.338847 0x7f3d30c05740 UTL  maxVgroupsPerDb:        0
12/12 17:40:26.338866 0x7f3d30c05740 UTL  maxTablesPerVnode:      1000000
12/12 17:40:26.338875 0x7f3d30c05740 UTL  minTablesPerVnode:      1000
12/12 17:40:26.338883 0x7f3d30c05740 UTL  tableIncStepPerVnode:   1000
12/12 17:40:26.338892 0x7f3d30c05740 UTL  cache:                  16(Mb)
12/12 17:40:26.338900 0x7f3d30c05740 UTL  blocks:                 6
12/12 17:40:26.338909 0x7f3d30c05740 UTL  days:                   2
12/12 17:40:26.338917 0x7f3d30c05740 UTL  keep:                   3650
12/12 17:40:26.338927 0x7f3d30c05740 UTL  minRows:                100
12/12 17:40:26.338936 0x7f3d30c05740 UTL  maxRows:                4096
12/12 17:40:26.338946 0x7f3d30c05740 UTL  comp:                   2
12/12 17:40:26.338954 0x7f3d30c05740 UTL  walLevel:               1
12/12 17:40:26.338964 0x7f3d30c05740 UTL  fsync:                  3000
12/12 17:40:26.338973 0x7f3d30c05740 UTL  replica:                1
12/12 17:40:26.338983 0x7f3d30c05740 UTL  quorum:                 1
12/12 17:40:26.338992 0x7f3d30c05740 UTL  compressMsgSize:        -1
12/12 17:40:26.339001 0x7f3d30c05740 UTL  maxSQLLength:           65480(byte)
12/12 17:40:26.339017 0x7f3d30c05740 UTL  maxNumOfOrderedRes:     100000
12/12 17:40:26.339027 0x7f3d30c05740 UTL  timezone:               (CST, +0800)
12/12 17:40:26.339036 0x7f3d30c05740 UTL  locale:                 en_US.UTF-8
12/12 17:40:26.339045 0x7f3d30c05740 UTL  charset:                UTF-8
12/12 17:40:26.339065 0x7f3d30c05740 UTL  maxShellConns:          5000
12/12 17:40:26.339074 0x7f3d30c05740 UTL  maxConnections:         5000
12/12 17:40:26.339083 0x7f3d30c05740 UTL  minimalLogDirGB:        0.100000(GB)
12/12 17:40:26.339093 0x7f3d30c05740 UTL  minimalTmpDirGB:        0.100000(GB)
12/12 17:40:26.339103 0x7f3d30c05740 UTL  minimalDataDirGB:       0.500000(GB)
12/12 17:40:26.339113 0x7f3d30c05740 UTL  mnodeEqualVnodeNum:     4
12/12 17:40:26.339122 0x7f3d30c05740 UTL  http:                   1
12/12 17:40:26.339131 0x7f3d30c05740 UTL  mqtt:                   0
12/12 17:40:26.339140 0x7f3d30c05740 UTL  monitor:                1
12/12 17:40:26.339149 0x7f3d30c05740 UTL  httpCacheSessions:      1000
12/12 17:40:26.339158 0x7f3d30c05740 UTL  httpEnableRecordSql:    0
12/12 17:40:26.339167 0x7f3d30c05740 UTL  telegrafUseFieldNum:    0
12/12 17:40:26.339175 0x7f3d30c05740 UTL  httpMaxThreads:         2
12/12 17:40:26.339184 0x7f3d30c05740 UTL  restfulRowLimit:        10240
12/12 17:40:26.339192 0x7f3d30c05740 UTL  numOfLogLines:          10000000
12/12 17:40:26.339201 0x7f3d30c05740 UTL  asyncLog:               1
12/12 17:40:26.339210 0x7f3d30c05740 UTL  debugFlag:              0
12/12 17:40:26.339220 0x7f3d30c05740 UTL  mDebugFlag:             135
12/12 17:40:26.339229 0x7f3d30c05740 UTL  dDebugFlag:             135
12/12 17:40:26.339238 0x7f3d30c05740 UTL  sDebugFlag:             135
12/12 17:40:26.339247 0x7f3d30c05740 UTL  wDebugFlag:             135
12/12 17:40:26.339256 0x7f3d30c05740 UTL  sdbDebugFlag:           135
12/12 17:40:26.339265 0x7f3d30c05740 UTL  rpcDebugFlag:           131
12/12 17:40:26.339274 0x7f3d30c05740 UTL  tmrDebugFlag:           131
12/12 17:40:26.339283 0x7f3d30c05740 UTL  cDebugFlag:             131
12/12 17:40:26.339292 0x7f3d30c05740 UTL  jniDebugFlag:           131
12/12 17:40:26.339302 0x7f3d30c05740 UTL  odbcDebugFlag:          131
12/12 17:40:26.339312 0x7f3d30c05740 UTL  uDebugFlag:             131
12/12 17:40:26.339321 0x7f3d30c05740 UTL  httpDebugFlag:          131
12/12 17:40:26.339331 0x7f3d30c05740 UTL  mqttDebugFlag:          131
12/12 17:40:26.339341 0x7f3d30c05740 UTL  monitorDebugFlag:       131
12/12 17:40:26.339350 0x7f3d30c05740 UTL  qDebugFlag:             131
12/12 17:40:26.339361 0x7f3d30c05740 UTL  vDebugFlag:             131
12/12 17:40:26.339371 0x7f3d30c05740 UTL  tsdbDebugFlag:          131
12/12 17:40:26.339380 0x7f3d30c05740 UTL  tscEnableRecordSql:     0
12/12 17:40:26.339390 0x7f3d30c05740 UTL  enableCoreFile:         1
12/12 17:40:26.339400 0x7f3d30c05740 UTL  gitinfo:                ae1966332948147bacce3d32f9ad539ab8721db2
12/12 17:40:26.339410 0x7f3d30c05740 UTL  gitinfoOfInternal:
12/12 17:40:26.339420 0x7f3d30c05740 UTL  buildinfo:              Built by root at 2020-08-20 15:44
12/12 17:40:26.339430 0x7f3d30c05740 UTL  version:                2.0.1.1
12/12 17:40:26.339440 0x7f3d30c05740 UTL  maxBinaryDisplayWidth:  30
12/12 17:40:26.339451 0x7f3d30c05740 UTL  os pageSize:            4096(KB)
12/12 17:40:26.339461 0x7f3d30c05740 UTL  os openMax:             1048576
12/12 17:40:26.339469 0x7f3d30c05740 UTL  os streamMax:           16
12/12 17:40:26.339479 0x7f3d30c05740 UTL  os numOfCores:          2
12/12 17:40:26.339487 0x7f3d30c05740 UTL  os totalDisk:           492.027588(GB)
12/12 17:40:26.339499 0x7f3d30c05740 UTL  os totalMemory:         15885(MB)
12/12 17:40:26.339523 0x7f3d30c05740 UTL  os sysname:             Linux
12/12 17:40:26.339544 0x7f3d30c05740 UTL  os nodename:            izwz9h6831v1p5a8i1jckqz
12/12 17:40:26.339553 0x7f3d30c05740 UTL  os release:             3.10.0-1127.19.1.el7.x86_64
12/12 17:40:26.339564 0x7f3d30c05740 UTL  os version:             #1 SMP Tue Aug 25 17:23:54 UTC 2020
12/12 17:40:26.339578 0x7f3d30c05740 UTL  os machine:             x86_64
12/12 17:40:26.339587 0x7f3d30c05740 UTL ==================================

Environment (please complete the following information):
tdengine版本：**2.0.11**

[file.zip](https://github.com/taosdata/TDengine/files/5687863/file.zip)

**Comment by sangshuduo** [comment]
经了解，使用版本为 2.0.1.1 ，暂时关闭。请 @zed-hj 使用新版本验证后如果有问题再看。
