### ISSUE TITLE
查询性能测试后数据查不到了（磁盘文件在），重启TDengine集群后数据又可以查到

### ISSUE THREAD

**Issue by duanbt** [taosdata/TDengine#4556]
**描述**
一个超级表（3副本，1个tag，11列），1000个子表，共导入172800000行数据，10秒一个采集点，数据时间跨度20天。
在进行查询性能测试后，表中数据count为0且查不到数据（测试前，count正常），重启TDegnine集群后，count正常且数据可查到。

查询性能测试：
查询包含简单查询、聚合查询和多设备聚合查询。三类查询按照 7:2:1 混合。
简单查询：查询20天内某一个小时内，指定设备的指定传感器的所有值
聚合查询：查询20天内某一个小时内，指定设备的指定传感器的聚合值(max、 min、 avg、count值)
多设备聚合查询：查询20天内某一个小时内，随机十个设备的指定传感器的聚合值(max、 min、 avg、count值)

**查询请求/s**
在3分钟左右的持续测试下，每秒读请求约 2000个，测试完发现数据查不到了，count为0。
![Image 44](https://user-images.githubusercontent.com/40535211/102031834-2362f580-3df2-11eb-9d54-6b90b27772ba.png)

**环境:**
 - OS: Ubuntu 16.04.5
 - CPU，Memory：2核 4G
 - TDengine Version： 2.0.9.0 （3节点集群）

**Comment by sangshuduo** [comment]
@duanbt 请问能重现吗？能否在 taos.cfg 中开启 debugFlag 为 135 后重现，然后请把 log 以文件的形式附上，我们尽快看一下，谢谢！

**Comment by duanbt** [comment]
> @duanbt 请问能重现吗？能否在 taos.cfg 中开启 debugFlag 为 135 后重现，然后请把 log 以文件的形式附上，我们尽快看一下，谢谢！

今天又测了一次，没复现出来，周六时候出现了两次...

**Comment by sangshuduo** [comment]
@duanbt 好的，我先暂时关闭此 issue，如果后面出现类似问题，请再提交相关 log。
