### ISSUE TITLE
GO CONNECTOR 2.0.9 无法创建超级表

### ISSUE THREAD

**Issue by amuluo24** [taosdata/TDengine#4557]
使用命令行操作都是可以的 但是无法试用GO CONNECTOR 编程进行创建超级表
报 error msg---> Unable to establish connection 
创建数据库和创建数据表都是可以的

**Comment by amuluo24** [comment]
sql 语句长度是否有限制 如果有哪里可以修改长度限制

**Comment by amuluo24** [comment]
测试了go connector 发送SQL 语句有长度限制 如果修改

**Comment by sangshuduo** [comment]
@amuluo24 请分享一下相关代码便于我们重现。

**Comment by amuluo24** [comment]
create table if not exists sbr(ts timestamp,  x1 binary(40),x2 binary(10),x3 binary(10),x4 binary(40),x5 binary(20),x6 binary(40),x7 binary(40),x8 binary(10),x9 binary(10),x10 binary(20),x11 binary(20),x12 int,x13 int,x14 int,x15 int) tags (t binary(10))"

**Comment by amuluo24** [comment]
这句SQL 用GO CONNECTOR  会报 Unable to establish connection

**Comment by sangshuduo** [comment]
我在 2.0.10.0 上修改 examples/go/taosdemo.go 简单试了一下，没问题，你也可以试试，如果还有问题我们再看。

**Comment by amuluo24** [comment]
create table if not exists sbr(ts timestamp, x1 binary(40),x2 binary(10),x3 binary(10),x4 binary(40),x5 binary(20),x6 binary(40),x7 binary(40),x8 binary(10),x9 binary(10),x10 binary(20),x11 binary(20),x12 int,x13 int,x14 int,x15 int,x16 int ,x17 int，x18 int ,x19 int) tags (t binary(10))"不好意思 我把正确的长度发出来了 你试试这个

**Comment by amuluo24** [comment]
有限长度是可以的 所以我现在都是只能创建了再ALTER TABLE 添加列

**Comment by sangshuduo** [comment]
x17 int 和  x18 int 之间的逗号是中文
