### ISSUE TITLE
select by ts got 0 rows

### ISSUE THREAD

**Issue by Jerry-Kwok** [taosdata/TDengine#4564]
**Bug Description**
基于ts做指定时段的数据查询，查不到符合条件的记录，把时段放大一下，就可查出了

**To Reproduce**
```
taos> select ts,tbName from position where ts > '2020-09-15 12:40:00' and ts < '2020-09-15 12:50:00' limit 10;
```
           ts            |             tbname             |
===========================================================
 2020-09-15 12:40:17.000 | position_7130725273            |
 2020-09-15 12:41:17.000 | position_7130725273            |
 2020-09-15 12:43:00.000 | position_6200910326            |
 2020-09-15 12:48:00.000 | position_6200910326            |
 2020-09-15 12:41:24.000 | position_7060504462            |
 2020-09-15 12:43:24.000 | position_7060504462            |
 2020-09-15 12:45:24.000 | position_7060504462            |
 2020-09-15 12:47:24.000 | position_7060504462            |
 2020-09-15 12:49:24.000 | position_7060504462            |
 2020-09-15 12:40:53.000 | position_7060519857            |
Query OK, 10 row(s) in set (0.139482s)

```
taos> select ts,tbName from position where ts > '2020-09-15 12:45:00' and ts < '2020-09-15 12:50:00' limit 10;
```
Query OK, 0 row(s) in set (0.312428s)

**Expected Behavior**
无论查询时段如何变化，满足条件的记录应均能被查出

**Screenshots**
![tsdata-bug](https://user-images.githubusercontent.com/44646098/102062306-7effa400-3e2f-11eb-8505-e3f95712730e.png)

**Environment (please complete the following information):**
 - OS: CentOS 7.0
 - Memory, CPU, current Disk Space: Aliyun ECS 4 vCPU, 32 GiB, 163 G free 
 - TDengine Version 2.0.9.0

**Additional Context**

**Comment by hjxilinx** [comment]
position_7060504462 这个表，精确的查询能查到吗？
select * from position_7060504462 where ts = '2020-09-15 12:49:24.000';

**Comment by Jerry-Kwok** [comment]
能查到

**Comment by hjxilinx** [comment]
你是在官网下载的安装包还是自己编译的版本？

**Comment by Jerry-Kwok** [comment]
docker hub上下载的镜像——docker pull tdengine/tdengine:2.0.9.0

**Comment by hjxilinx** [comment]
你 pull 一下2.0.10.0的镜像试一试,2.0.9.0版本有的地方有问题。

**Comment by Jerry-Kwok** [comment]
好的

**Comment by Jerry-Kwok** [comment]
我运行2.0.10.0镜像去加载2.0.9.0的数据，run不起来，指令如下，容器名没有变化，与之前docker run相比，仅修改了命令结尾的镜像版本，还需要其他操作么？
```
docker run --name tdengine2.0.9.0 -d -e TZ=Asia/Shanghai --add-host=yt-taos-test-2090:<ip> -v /etc/jerry-temp/taos/taos2.0.9.0/cfg:/etc/taos -v /etc/jerry-temp/taos/taos2.0.9.0/data:/var/lib/taos -v /etc/jerry-temp/taos/taos2.0.9.0/log:/var/log/taos -p 6020-6050:6020-6050/udp -p 6020-6050:6020-6050 tdengine/tdengine:2.0.10.0
```

**Comment by Jerry-Kwok** [comment]
看docker hub中昨天发布了2.0.9.1，也尝试用2.0.9.1加载现有数据(2.0.9.0)，可以run起来，切换db正常，执行select挂掉

**Comment by hjxilinx** [comment]
我的邮箱是 hjliao@taosdata.com， 您可以把你的联系方式给我，我远程给您看看。

**Comment by hjxilinx** [comment]
在2.0.12.x版本中该问题已经修复。
