### ISSUE TITLE
请问在docker容器中安装客户端，并且想修改maxSQLLength，应该修改哪个文件才能生效？

### ISSUE THREAD

**Issue by 419845351** [taosdata/TDengine#4567]
**General Questions**
 如题，在docker容器中安装客户端成功后。

想要修改maxSQLLength，要怎么做？没有找到tao.cfg文件。

![image](https://user-images.githubusercontent.com/29766247/102078907-b168cb80-3e46-11eb-86fa-a965b96774e0.png)

**Comment by sangshuduo** [comment]
/etc/taos/taos.cfg
