### ISSUE TITLE
error: package tdengine is not installed while it shows "TDEngine is removed successfully when execute "remove.sh" although I installed sucessfully using centos 7.6 source code

### ISSUE THREAD

**Issue by derchLee** [taosdata/TDengine#457]
**Bug Description**
centos7.6源码安装成功，执行remove.sh的时候提示tdengine包没有安装。
**To Reproduce**
源码安装TDengine，安装成功了，并且可以正常操作数据库；
执行remobe.sh的时候提示当前系统是centos，tdengine包没有被安装。但是还提示删除成功。
![image](https://user-images.githubusercontent.com/40223756/64221076-33590d80-cefe-11e9-9e32-2f246521ecbe.png)

**Comment by plum-lihui** [comment]
这个提示的原因：是因为我们发布了三种安装包，有时候会有用户同时使用，会出现相互冲突，导致卸载不干净，在remove.sh脚本中，会强制执行一下卸载tdengine的rpm包。如果曾经安装过rpm包，就会清理安装环境，如果没有安装过rpm包，就会出现这个提示。
