### ISSUE TITLE
超级字段超过30个 无法创建表

### ISSUE THREAD

**Issue by amuluo24** [taosdata/TDengine#4570]
我之前的发过的 不是不能执行 是超过一定字段就不行了

**Comment by amuluo24** [comment]
那个ISSUE 我没说明白 但我发现已经被关了

**Comment by sangshuduo** [comment]
#4557 回复了，麻烦 issue 写下完整的重现过程，否则我们也很难帮你

**Comment by amuluo24** [comment]
如果是中文出错 我就不要问您了啊  我那段是手打(在这个输入框) 你可以把中文换成半角 试试就知道了 我是真心想帮助你们 共同找到问题
