### ISSUE TITLE
invalid SQL: '窑' (Invalid argument)

### ISSUE THREAD

**Issue by yuhuafeng1109** [taosdata/TDengine#4572]
insert插入内容NCHAR内容中包含中文字'窑'，插入失败，报错：invalid SQL: '窑' (Invalid argument)

**Comment by sangshuduo** [comment]
下午微信群里应该回复了，还有问题吗？

请提供更多信息，包括 TDengine 版本，系统信息，系统 locale ，taos.cfg ，完整 insert 指令，屏幕截图。
