### ISSUE TITLE
第三次发帖 针对超级表数据过长无法创建的问题

### ISSUE THREAD

**Issue by amuluo24** [taosdata/TDengine#4579]
create table if not exists taost(ts timestamp, x1 binary(40),x2 binary(40),x3 binary(40),x4 binary(40),x5 binary(20),x6 binary(40),x7 binary(40),x8 binary(10),x9 binary(10),x10 binary(20),x11 binary(20),x12 int,x13 int) tags (x99 binary(30))

create table if not exists taost(ts timestamp, x1 binary(40),x2 binary(40),x3 binary(40),x4 binary(40),x5 binary(20),x6 binary(40),x7 binary(40),x8 binary(10),x9 binary(10),x10 binary(20),x11 binary(20),x12 int,x13 int,x14 int,x15 int) tags (x99 binary(30))
第一个SQL 可以执行 
第二个SQL无法执行返回下面的错误
 error msg---> Unable to establish connection
谢谢 请求贵方的帮助

**Comment by sangshuduo** [comment]
我用 TDengine 2.0.10.0 ，修改 examples/go/taosdemo.go 中建超级表语句第 163 行，使用你说的第二个SQL语句的表结构，编译执行，我这里没有问题，参见下面屏幕输出。你用的是什么版本？可以把 taos.cfg ，  taoslog ， taosdlog 几个文件发上来吗？

$ taos -s "drop database test;"

Welcome to the TDengine shell from Linux, Client Version:2.0.10.0

Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.

taos> drop database test;

Query OK, 0 row(s) affected (0.005551s)

root@centos7-5 /TDengine-server-2.0.10.0/examples/go $ ./taosdemo

\============= args parse result: =============

hostName:               127.0.0.1

serverPort:           6030

usr:                  root

password:             taosdata

dbName:               test

tablePrefix:          d

numOftables:          2

numOfRecordsPerTable: 10

numOfRecordsPerReq:   3

numOfThreads:         1

startTimestamp:       2020-10-01 08:00:00\[1601510400000\]

\================================================

Please press enter key to continue....

\======== create database success! ========

\======== end demo ========

root@centos7-5 /TDengine-server-2.0.10.0/examples/go $ taos -s "describe test.taost"

Welcome to the TDengine shell from Linux, Client Version:2.0.10.0

Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.

taos> describe test.taost

            Field              |       Type       |   Length    |   Note   |

\=============================================================================

ts                             | TIMESTAMP        |           8 |          |

x1                             | BINARY           |          40 |          |

x2                             | BINARY           |          40 |          |

x3                             | BINARY           |          40 |          |

x4                             | BINARY           |          40 |          |

x5                             | BINARY           |          20 |          |

x6                             | BINARY           |          40 |          |

x7                             | BINARY           |          40 |          |

x8                             | BINARY           |          10 |          |

x9                             | BINARY           |          10 |          |

x10                            | BINARY           |          20 |          |

x11                            | BINARY           |          20 |          |

x12                            | INT              |           4 |          |

x13                            | INT              |           4 |          |

x14                            | INT              |           4 |          |

x15                            | INT              |           4 |          |

x99                            | BINARY           |          30 | TAG      |

Query OK, 17 row(s) in set (0.001542s)

**Comment by sangshuduo** [comment]
我用 TDengine 2.0.10.0 ，修改 examples/go/taosdemo.go 中建超级表语句第 163 行，使用你说的第二个SQL语句的表结构，编译执行，我这里没有问题，参见下面屏幕输出。你用的是什么版本？可以把 taos.cfg ，  taoslog ， taosdlog 几个文件发上来吗？

$ taos -s "drop database test;"

Welcome to the TDengine shell from Linux, Client Version:2.0.10.0

Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.

taos> drop database test;

Query OK, 0 row(s) affected (0.005551s)

root@centos7-5 /TDengine-server-2.0.10.0/examples/go $ ./taosdemo

\============= args parse result: =============

hostName:               127.0.0.1

serverPort:           6030

usr:                  root

password:             taosdata

dbName:               test

tablePrefix:          d

numOftables:          2

numOfRecordsPerTable: 10

numOfRecordsPerReq:   3

numOfThreads:         1

startTimestamp:       2020-10-01 08:00:00\[1601510400000\]

\================================================

Please press enter key to continue....

\======== create database success! ========

\======== end demo ========

root@centos7-5 /TDengine-server-2.0.10.0/examples/go $ taos -s "describe test.taost"

Welcome to the TDengine shell from Linux, Client Version:2.0.10.0

Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.

taos> describe test.taost

            Field              |       Type       |   Length    |   Note   |

\=============================================================================

ts                             | TIMESTAMP        |           8 |          |

x1                             | BINARY           |          40 |          |

x2                             | BINARY           |          40 |          |

x3                             | BINARY           |          40 |          |

x4                             | BINARY           |          40 |          |

x5                             | BINARY           |          20 |          |

x6                             | BINARY           |          40 |          |

x7                             | BINARY           |          40 |          |

x8                             | BINARY           |          10 |          |

x9                             | BINARY           |          10 |          |

x10                            | BINARY           |          20 |          |

x11                            | BINARY           |          20 |          |

x12                            | INT              |           4 |          |

x13                            | INT              |           4 |          |

x14                            | INT              |           4 |          |

x15                            | INT              |           4 |          |

x99                            | BINARY           |          30 | TAG      |

Query OK, 17 row(s) in set (0.001542s)

**Comment by amuluo24** [comment]
OK 一会我发下

发自我的iPhone

**Comment by amuluo24** [comment]
使用的2.10.0版本
配置文件如下 是否是服务有什么配置设置的不对 请指正


linwei2005ren@163.com
 
发件人： Shuduo Sang
发送时间： 2020-12-15 23:01
收件人： taosdata/TDengine
抄送： 林伟; Author
主题： Re: [taosdata/TDengine] 第三次发帖 针对超级表数据过长无法创建的问题 (#4579)
我用 TDengine 2.0.10.0 ，修改 examples/go/taosdemo.go 中建超级表语句第 163 行，使用你说的第二个SQL语句的表结构，编译执行，我这里没有问题，参见下面屏幕输出。你用的是什么版本？可以把 taos.cfg ，  taoslog ， taosdlog 几个文件发上来吗？
$ taos -s "drop database test;"
Welcome to the TDengine shell from Linux, Client Version:2.0.10.0
Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.
taos> drop database test;
Query OK, 0 row(s) affected (0.005551s)
root@centos7-5 /TDengine-server-2.0.10.0/examples/go $ ./taosdemo
============= args parse result: =============
hostName:               127.0.0.1
serverPort:           6030
usr:                  root
password:             taosdata
dbName:               test
tablePrefix:          d
numOftables:          2
numOfRecordsPerTable: 10
numOfRecordsPerReq:   3
numOfThreads:         1
startTimestamp:       2020-10-01 08:00:00[1601510400000]
================================================
Please press enter key to continue....
======== create database success! ========
======== end demo ========
root@centos7-5 /TDengine-server-2.0.10.0/examples/go $ taos -s "describe test.taost"
Welcome to the TDengine shell from Linux, Client Version:2.0.10.0
Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.
taos> describe test.taost
            Field              |       Type       |   Length    |   Note   |
=============================================================================
ts                             | TIMESTAMP        |           8 |          |
x1                             | BINARY           |          40 |          |
x2                             | BINARY           |          40 |          |
x3                             | BINARY           |          40 |          |
x4                             | BINARY           |          40 |          |
x5                             | BINARY           |          20 |          |
x6                             | BINARY           |          40 |          |
x7                             | BINARY           |          40 |          |
x8                             | BINARY           |          10 |          |
x9                             | BINARY           |          10 |          |
x10                            | BINARY           |          20 |          |
x11                            | BINARY           |          20 |          |
x12                            | INT              |           4 |          |
x13                            | INT              |           4 |          |
x14                            | INT              |           4 |          |
x15                            | INT              |           4 |          |
x99                            | BINARY           |          30 | TAG      |
Query OK, 17 row(s) in set (0.001542s)

**Comment by amuluo24** [comment]
语句使用GO DRIVER 执行   我在服务器上用命令行执行也是可以的_，但是用GO 驱动 编写代码执行时不行的  谢谢

**Comment by amuluo24** [comment]
使用的是2.10.0版本

**Comment by amuluo24** [comment]
########################################################
#                                                      #
#                  TDengine Configuration              #
#   Any questions, please email support@taosdata.com   #
#                                                      #
########################################################

# first fully qualified domain name (FQDN) for TDengine system
# firstEp                   hostname:6030

# local fully qualified domain name (FQDN)
#fqdn                      td1

# first port number for the connection (12 continuous UDP/TCP port number are used) 
# serverPort                6030

# log file's directory
logDir                    /mnt/taos/log

# data file's directory
 #dataDir                   /var/lib/taos
 dataDir                   /mnt/taos/lib

# temporary file's directory
tempDir                   /mnt/taos/tmp

# the arbitrator's fully qualified domain name (FQDN) for TDengine system, for cluster only   
# arbitrator                arbitrator_hostname:6042     

# number of threads per CPU core
# numOfThreadsPerCore       1.0

# the proportion of total threads responsible for query
# ratioOfQueryThreads       0.5

# number of management nodes in the system
# numOfMnodes               3

# enable/disable backuping vnode directory when removing dnode
# vnodeBak                  1

# if report installation / use information
 telemetryReporting        0

# enable/disable load balancing
# balance                   1

# role for dnode. 0 - any, 1 - mnode, 2 - dnode
# role                      0

# max timer control blocks
# maxTmrCtrl                512

# time interval of system monitor, seconds 
# monitorInterval           30

# number of seconds allowed for a dnode to be offline, for cluster only 
# offlineThreshold          8640000

# RPC re-try timer, millisecond
# rpcTimer                  300

# RPC maximum time for ack, seconds. 
# rpcMaxTime                600

# time interval of dnode status reporting to mnode, seconds, for cluster only 
# statusInterval            1

# time interval of heart beat from shell to dnode, seconds
# shellActivityTimer        3

# time of keeping table meta data in cache, seconds
# tableMetaKeepTimer        7200

# minimum sliding window time, milli-second
# minSlidingTime            10

# minimum time window, milli-second
# minIntervalTime           10

# maximum delay before launching a stream compution, milli-second
# maxStreamCompDelay        20000

# maximum delay before launching a stream computation for the first time, milli-second
# maxFirstStreamCompDelay   10000

# retry delay when a stream computation fails, milli-second
# retryStreamCompDelay      10

# the delayed time for launching a stream computation, from 0.1(default, 10% of whole computing time window) to 0.9
# streamCompDelayRatio      0.1

# max number of vgroups per db, 0 means configured automatically
# maxVgroupsPerDb           0

# max number of tables per vnode
# maxTablesPerVnode         1000000

# cache block size (Mbyte)
# cache                     16

# number of cache blocks per vnode
# blocks                    6

# number of days per DB file
 days                  10

# number of days to keep DB file
 keep                  3650

# minimum rows of records in file block
# minRows               100

# maximum rows of records in file block
# maxRows               4096

# the number of acknowledgments required for successful data writing
# quorum                1     

# enable/disable compression
# comp                  2

# write ahead log (WAL) level, 0: no wal; 1: write wal, but no fysnc; 2: write wal, and call fsync
# walLevel              1

# if walLevel is set to 2, the cycle of fsync being executed, if set to 0, fsync is called right away
# fsync                 3000

# number of replications, for cluster only 
# replica               1

# the compressed rpc message, option:
#  -1 (no compression)
#   0 (all message compressed),
# > 0 (rpc message body which larger than this value will be compressed)
# compressMsgSize       -1

# max length of an SQL
 maxSQLLength          102400

# the maximum number of records allowed for super table time sorting
 #maxNumOfOrderedRes    100000

# system time zone
 timezone              Asia/Shanghai (CST, +0800)

# system locale
 locale                en_US.UTF-8

# default system charset
 charset               UTF-8

# max number of connections allowed in dnode
 maxShellConns         5000

# max numerber of connections allowed in client 
 maxConnections        5000

# stop writing logs when the disk size of the log folder is less than this value
# minimalLogDirGB       0.1

# stop writing temporary files when the disk size of the log folder is less than this value
# minimalTmpDirGB       0.1

# stop writing data when the disk size of the log folder is less than this value
# minimalDataDirGB      0.1

# One mnode is equal to the number of vnode consumed
# mnodeEqualVnodeNum    4

# enbale/disable http service
# http                  1

# enable/disable system monitor 
# monitor               1

# enable/disable recording the SQL statements via restful interface
# httpEnableRecordSql   0

# number of threads used to process http requests
 httpMaxThreads        200

# maximum number of rows returned by the restful interface
# restfulRowLimit       10240

# The following parameter is used to limit the maximum number of lines in log files.
# max number of rows per log filters
# numOfLogLines         10000000

# enable/disable async log
# asyncLog              1

# time of keeping log files, days
# logKeepDays           0


# The following parameters are used for debug purpose only.
# debugFlag 8 bits mask: FILE-SCREEN-UNUSED-HeartBeat-DUMP-TRACE_WARN-ERROR
# 131: output warning and error, 135: output debug, warning and error, 143 : output trace, debug, warning and error to log.
# 199: output debug, warning and error to both screen and file
# 207: output trace, debug, warning and error to both screen and file

# debug flag for all log type, take effect when non-zero value
#debugFlag             135

# debug flag for meta management messages
# mDebugFlag            135

# debug flag for dnode messages
# dDebugFlag            135

# debug flag for sync module
# sDebugFlag            135

# debug flag for WAL
# wDebugFlag            135

# debug flag for SDB
# sdbDebugFlag          135

# debug flag for RPC 
# rpcDebugFlag          131

# debug flag for TAOS TIMER
# tmrDebugFlag          131

# debug flag for TDengine client 
# cDebugFlag            131

# debug flag for JNI
# jniDebugflag          131

# debug flag for storage
# uDebugflag            131

# debug flag for http server
# httpDebugFlag         131

# debug flag for monitor
# monitorDebugFlag      131

# debug flag for query
 qDebugflag            135

# debug flag for vnode
# vDebugflag            131

# debug flag for http server
# tsdbDebugFlag         131

# debug flag for continue query
# cqDebugFlag           131

# enable/disable recording the SQL in taos client
tscEnableRecordSql    1

# generate core file when service crash
# enableCoreFile        1

# maximum display width of binary and nchar fields in the shell. The parts exceeding this limit will be hidden
# maxBinaryDisplayWidth 30

# enable/disable telemetry reporting
# telemetryReporting    1

**Comment by amuluo24** [comment]
我在服务器上跑GO 执行SQL 也是可以的 在非服务器环境不行 请指正 什么原因 很困惑

**Comment by sangshuduo** [comment]
@amuluo24 非服务器环境是指没有安装过任何 TDengine 安装包吗？客户端也没装？

**Comment by amuluo24** [comment]
1. 我分别在window和LINUX 环境下 测试的  我指的环境是 我本地的开发环境 当然也是装了客户端了不然短的SQL 也不会执行成功
2. 您可以测试下 在本地自己的电脑上用开发工具跑一次GO 驱动程序 执行下我下面的语句  create table if not exists taost(ts timestamp, x1 binary(40),x2 binary(40),x3 binary(40),x4 binary(40),x5 binary(20),x6 binary(40),x7 binary(40),x8 binary(10),x9 binary(10),x10 binary(20),x11 binary(20),x12 int,x13 int,x14 int,x15 int) tags (x99 binary(30))

**Comment by plum-lihui** [comment]
在我自己的虚拟机linxu上跑了一下，就是在go的测试代码中添加了 你的这个建表语句，正常成功。
如果你测试还有问题的话，请在配置文件中打开调试开关：debugflag    135
跑一次后，将客户端的日志文件发送上来，我们看下就知道是不是成功，如果不成功的话，是什么原因。

**Comment by amuluo24** [comment]
难道是windows环境的问题？


发自我的iPhone
