### ISSUE TITLE
Data loss of one super table

### ISSUE THREAD

**Issue by yushan-yaojin** [taosdata/TDengine#4581]
一个库里面有三张超级表，其它两个超级表的数据好好的，另一个超级表的数据全丢了，全没了。昨天晚上下班前还是好好的。

**Comment by sangshuduo** [comment]
@yushan-yaojin 请问是什么版本？单机还是集群？有没有副本？方便远程吗？

**Comment by yushan-yaojin** [comment]
> @yushan-yaojin 请问是什么版本？单机还是集群？有没有副本？方便远程吗？

2.0.10 版本。 单机版，我把表删掉，重建又好了。

**Comment by sangshuduo** [comment]
如果能重现请把相关日志附上，谢谢！
