### ISSUE TITLE
DB error: invalid SQL: row length exceeds max length (0.003137s)

### ISSUE THREAD

**Issue by okjay** [taosdata/TDengine#4582]
**Bug Description**
插入sql超过长度，再配置文件中已经配置了
版本：2.0.9.0
Welcome to the TDengine shell from Linux, Client Version:2.0.9.0
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.
配置：
# max length of an SQL
maxSQLLength          1048576

已经进行了处理
创建表的sql

CREATE TABLE IF NOT EXISTS st201c1200001186741av300418007fd0000000000000000000000000000000040 (event_time_stamp TIMESTAMP,sys_ts_recv TIMESTAMP,sys_ts_trans TIMESTAMP,sn BINARY(32),data_type INT,f_tankwaterlevel BINARY(50),f_singleresntime BINARY(50),f_hightempremindstatus BINARY(50),f_workhour6 BINARY(50),f_workhour7 BINARY(50),f_workhour8 BINARY(50),f_workhour9 BINARY(50),f_workhour2 BINARY(50),f_workhour3 BINARY(50),f_workhour4 BINARY(50),f_workhour5 BINARY(50),f_totalworktime BINARY(50),f_forcedelete BINARY(50),f_dateyy BINARY(50),f_workhour0 BINARY(50),f_zerocoldwatermode BINARY(50),f_oyworkdaysat BINARY(50),f_workhour1 BINARY(50),f_tankcode BINARY(50),f_flowstatus BINARY(50),f_pwm BINARY(50),f_ecojudgetemp BINARY(50),f_workdaywed BINARY(50),f_runfanspd BINARY(50),f_timemm BINARY(50),f_selfteststatus BINARY(50),f_cycfuncselect BINARY(50),f_showercode BINARY(50),f_ecostatus BINARY(50),f_totalusegasl BINARY(50),f_voicemoduleonoffstatus BINARY(50),f_defworkdaytue BINARY(50),f_allworkhour14 BINARY(50),f_allworkhour15 BINARY(50),f_inwatertemp BINARY(50),f_allworkhour16 BINARY(50),f_allworkhour17 BINARY(50),f_allworkhour18 BINARY(50),f_allworkhour19 BINARY(50),f_allresthour1 BINARY(50),f_burntime1hourremindstatus BINARY(50),f_allresthour0 BINARY(50),f_allresthour3 BINARY(50),f_allresthour2 BINARY(50),f_allworkhour20 BINARY(50),f_allworkhour21 BINARY(50),f_allresthour5 BINARY(50),f_allworkhour22 BINARY(50),f_allresthour4 BINARY(50),f_voicemodulevolume BINARY(50),f_allworkhour23 BINARY(50),f_allresthour7 BINARY(50),f_allresthour6 BINARY(50),f_allresthour9 BINARY(50),f_allresthour8 BINARY(50),f_alarmmutestatus BINARY(50),f_defworkhour9 BINARY(50),f_defworkdaysat BINARY(50),f_defworkhour5 BINARY(50),f_defworkhour6 BINARY(50),f_defworkhour7 BINARY(50),f_waterusedstatus BINARY(50),f_smartenergysavingstatus BINARY(50),f_defworkhour8 BINARY(50),f_defworkhour1 BINARY(50),f_defworkhour2 BINARY(50),f_smarttempsensingstatus BINARY(50),f_defworkhour3 BINARY(50),f_defworkhour4 BINARY(50),f_curveid BINARY(50),f_defworkhour0 BINARY(50),f_allworkhour10 BINARY(50),f_allworkhour11 BINARY(50),f_allworkhour12 BINARY(50),f_allworkhour13 BINARY(50),f_oyworkdaytue BINARY(50),f_allworkdaywed BINARY(50),f_discalestatus BINARY(50),f_scourstate BINARY(50),f_realtimepower BINARY(50),f_oyworkdaywed BINARY(50),f_defworkdaywed BINARY(50),f_workdaytue BINARY(50),f_datemm BINARY(50),f_userwaterburntime BINARY(50),f_safeselfteststatus BINARY(50),f_curvedownloadsuccess BINARY(50),f_workdaysat BINARY(50),f_oyworkhour11 BINARY(50),f_oyworkhour12 BINARY(50),f_oyworkhour13 BINARY(50),f_oyworkhour14 BINARY(50),f_oyworkhour15 BINARY(50),f_oyworkhour16 BINARY(50),f_resthour19 BINARY(50),f_oyworkhour17 BINARY(50),f_resthour18 BINARY(50),f_oyworkhour18 BINARY(50),f_resthour17 BINARY(50),f_resthour16 BINARY(50),f_resthour15 BINARY(50),f_allworkdayfri BINARY(50),f_resthour14 BINARY(50),f_resthour13 BINARY(50),f_resthour12 BINARY(50),f_resthour11 BINARY(50),f_resthour10 BINARY(50),f_oyworkhour10 BINARY(50),f_workdaysun BINARY(50),f_allworkdaymon BINARY(50),f_watercyclefinish BINARY(50),f_oyresthour8 BINARY(50),f_oyresthour7 BINARY(50),f_oyresthour9 BINARY(50),f_oyresthour4 BINARY(50),f_oyresthour3 BINARY(50),f_oyresthour6 BINARY(50),f_oyresthour5 BINARY(50),f_oyresthour0 BINARY(50),f_oyresthour2 BINARY(50),f_curvemanualsetsuccess BINARY(50),f_oyresthour1 BINARY(50),f_targettemp BINARY(50),f_resthour23 BINARY(50),f_resthour22 BINARY(50),f_resthour21 BINARY(50),f_resthour20 BINARY(50),f_alarmmoduleexist BINARY(50),f_zerocoldwatertargettemp BINARY(50),f_tankwateringstatus BINARY(50),f_workdaythu BINARY(50),f_outwatertemp BINARY(50),f_workhour10 BINARY(50),f_workhour12 BINARY(50),f_onoffstatus BINARY(50),f_workhour11 BINARY(50),f_targetratedpower BINARY(50),f_workhour14 BINARY(50),f_workhour13 BINARY(50),f_workhour16 BINARY(50),f_workhour15 BINARY(50),f_resthour9 BINARY(50),f_workhour18 BINARY(50),f_workhour17 BINARY(50),f_workhour19 BINARY(50),f_resthour5 BINARY(50),f_defworkhour22 BINARY(50),f_resthour6 BINARY(50),f_defworkhour21 BINARY(50),f_resthour7 BINARY(50),f_resthour8 BINARY(50),f_defworkhour23 BINARY(50),f_resthour1 BINARY(50),f_oyworkhour9 BINARY(50),f_resthour2 BINARY(50),f_oyworkhour8 BINARY(50),f_resthour3 BINARY(50),f_resthour4 BINARY(50),f_oyworkhour5 BINARY(50),f_oyworkhour22 BINARY(50),f_oyworkhour4 BINARY(50),f_oyworkhour23 BINARY(50),f_flamestatus BINARY(50),f_oyworkhour7 BINARY(50),f_resthour0 BINARY(50),f_oyworkhour6 BINARY(50),f_oyworkhour1 BINARY(50),f_oyworkhour0 BINARY(50),f_defworkhour20 BINARY(50),f_oyworkhour3 BINARY(50),f_oyworkhour2 BINARY(50),f_defresthour8 BINARY(50),f_defresthour9 BINARY(50),f_workhour21 BINARY(50),f_defresthour4 BINARY(50),f_workhour20 BINARY(50),f_cycantifreezingstatus BINARY(50),f_defresthour5 BINARY(50),f_workhour23 BINARY(50),f_defresthour6 BINARY(50),f_oyworkhour20 BINARY(50),f_voicemodulebroadcaststatus BINARY(50),f_workhour22 BINARY(50),f_defresthour7 BINARY(50),f_oyworkhour21 BINARY(50),f_defresthour0 BINARY(50),f_defworkhour19 BINARY(50),f_defresthour1 BINARY(50),f_defworkhour18 BINARY(50),f_allworkdaysat BINARY(50),f_defresthour2 BINARY(50),f_defresthour3 BINARY(50),f_cloudsmartcommandnum BINARY(50),rep_biz_name_cd BINARY(50),f_oyworkhour19 BINARY(50),f_defworkhour11 BINARY(50),f_voicemodulewakestatus BINARY(50),f_defworkhour10 BINARY(50),f_defworkhour13 BINARY(50),f_defworkhour12 BINARY(50),f_defworkhour15 BINARY(50),f_defworkhour14 BINARY(50),f_defworkhour17 BINARY(50),f_smartcapacitychangestatus BINARY(50),f_defworkhour16 BINARY(50),f_oyworkdaymon BINARY(50),f_fanselfcleaningstatus BINARY(50),f_defworkdaymon BINARY(50),f_allworkhour0 BINARY(50),f_energysavingstatus BINARY(50),f_ratedpower BINARY(50),f_oyworkdayfri BINARY(50),f_allworkhour2 BINARY(50),f_allworkhour1 BINARY(50),f_curwaterflux BINARY(50),f_allworkhour4 BINARY(50),f_allworkhour3 BINARY(50),f_allworkhour6 BINARY(50),f_pressurizesupported BINARY(50),f_allworkhour5 BINARY(50),sys_ver BINARY(50),f_zerocoldwaterfuncexist BINARY(50),f_allworkhour8 BINARY(50),f_allworkhour7 BINARY(50),f_cloudsmartrunningstatus BINARY(50),f_defworkdayfri BINARY(50),f_realtimepowerpct BINARY(50),f_allworkhour9 BINARY(50),f_covalue BINARY(50),f_voicemoduleerrcode BINARY(50),f_pumprunningstatus BINARY(50),f_cloudsmartquerystopmm BINARY(50),f_alarmdetectionstatus BINARY(50),f_oyresthour14 BINARY(50),f_cloudsmartcycletime BINARY(50),f_oyresthour15 BINARY(50),f_oyresthour12 BINARY(50),f_oyresthour13 BINARY(50),f_oyresthour10 BINARY(50),f_oyresthour11 BINARY(50),f_tankcurrentflux BINARY(50),f_voicemoduleautobroadcaststatus BINARY(50),f_pressurizemode BINARY(50),f_pipeantifreezingstatus BINARY(50),f_targetcurveid BINARY(50),f_valvestatus BINARY(50),f_oyworkdaysun BINARY(50),f_allresthour22 BINARY(50),f_allresthour23 BINARY(50),f_oyresthour23 BINARY(50),f_burntimehalfhourremindstatus BINARY(50),f_oyresthour21 BINARY(50),f_totalwaterl BINARY(50),seq_num BINARY(50),f_oyresthour22 BINARY(50),f_defworkdaysun BINARY(50),f_oyresthour20 BINARY(50),f_workdaymon BINARY(50),f_defresthour14 BINARY(50),f_defresthour13 BINARY(50),f_nfcstatus BINARY(50),f_defresthour12 BINARY(50),f_timehh BINARY(50),f_defresthour11 BINARY(50),f_defresthour10 BINARY(50),f_oyresthour18 BINARY(50),f_oyresthour19 BINARY(50),f_oyresthour16 BINARY(50),f_oyresthour17 BINARY(50),f_allworkdaysun BINARY(50),f_userscenefunccode BINARY(50),f_defresthour19 BINARY(50),f_prtlversion BINARY(50),f_defresthour18 BINARY(50),f_singlecyclefinish BINARY(50),f_fanstatus BINARY(50),f_defresthour17 BINARY(50),f_defresthour16 BINARY(50),f_defresthour15 BINARY(50),f_week BINARY(50),f_allworkdaythu BINARY(50),f_defresthour23 BINARY(50),f_defresthour22 BINARY(50),f_defresthour21 BINARY(50),f_defresthour20 BINARY(50),f_ch4value BINARY(50),f_ctrpriority BINARY(50),f_defworkdaythu BINARY(50),f_zerocoldwaterstatus BINARY(50),f_voicecommandnumber BINARY(50),rep_biz_type_cd BINARY(50),f_allworkdaytue BINARY(50),f_cloudsmartperiodquerynum BINARY(50),f_safetylockstatus BINARY(50),f_allresthour10 BINARY(50),f_cloudsmartquerystartmm BINARY(50),f_allresthour17 BINARY(50),f_workdayfri BINARY(50),f_netcfgstatus BINARY(50),f_allresthour18 BINARY(50),f_tanktargettemp BINARY(50),f_allresthour15 BINARY(50),f_allresthour16 BINARY(50),f_allresthour13 BINARY(50),f_altitudeadaptationstatus BINARY(50),f_allresthour14 BINARY(50),f_allresthour11 BINARY(50),f_allresthour12 BINARY(50),f_backwatertemp BINARY(50),f_allresthour19 BINARY(50),f_waterfallmode BINARY(50),f_allresthour20 BINARY(50),f_oyworkdaythu BINARY(50),f_tanktargetflux BINARY(50),f_allresthour21 BINARY(50),f_uvsterilizationstatus BINARY(50),f_datedd BINARY(50),f_indoortemperature BINARY(50)) TAGS (type_id BINARY(64),category BINARY(5),prod_code BINARY(15))

**Comment by sangshuduo** [comment]
https://www.taosdata.com/cn/documentation/administrator/#TDengine%E5%8F%82%E6%95%B0%E9%99%90%E5%88%B6%E4%B8%8E%E4%BF%9D%E7%95%99%E5%85%B3%E9%94%AE%E5%AD%97

*   记录的最大长度：包括时间戳8 byte，不能超过16KB
