### ISSUE TITLE
curl -h   alert: DB error: syntax error near ?

### ISSUE THREAD

**Issue by sexbee** [taosdata/TDengine#4586]
taos> curl -h 'Authorization: Basic cm9vdDp0YW9zZGF0YQ==' -d 'insert into db_mnit
.m5990470 using db_mnit.st_mnit tags( u4,599047) values(2020-12-16 13:0
5:44.734,HP1608095280401279,b019,dingxming,no,no,null,null,null,null,null)' 127.0.0.1:6041/rest/sql;

DB error: syntax error near "curl -h 'Authorization: Basic cm9vdDp0YW9zZG (0.000068s)

**Comment by stephenkgu** [comment]
Do execute your curl command in your bash or other shell, not the taos shell which can only execute SQL statements.

**Comment by sexbee** [comment]
curl: (6) Could not resolve host: 13:05
{"status":"error","code":4357,"desc":"no auth info input"}r

**Comment by stephenkgu** [comment]
Double check you curl command line is correct and complete.

> curl: (6) Could not resolve host: 13:05

your host is 127.0.0.1, not 13:05, so check your command line is complete.

**Comment by sexbee** [comment]
curl -h 'Authorization: Basic cm9vdDp0YW9zZGF0YQ==' -d  'insert into db_mnit
.m5990470 using db_mnit.st_mnit tags(u4,599047) values(2020-12-16 13:0
5:44.734,HP1608095280401279,b019,dingxming,no,no,null,null,null,null,null)' 127.0.0.1:6041/rest/sql;

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

{"status":"error","code":534,"desc":"Syntax error in SQL”}%


Sql 这种情况下如何写？

**Comment by stephenkgu** [comment]
This issue was closed because it has been inactive for too many days.
