### ISSUE TITLE
Incorrect JSON array of AlertManager（TDengine alert v2.0.10.0）

### ISSUE THREAD

**Issue by maoyaowu** [taosdata/TDengine#4587]
**TDengine alert v2.0.10.0. The posted json body get wrong**
I check that , the json data received from my tomcat is:
**Screenshots**

[{"startsAt":"2020-12-16T10:52:01.005509326+08:00","endsAt":"0001-01-01T00:00:00Z","values":{"host":"hbsy_monitor","max_value":6.323381014899853,"path":"/"},"labels":{"host":"hbsy_monitor","path":"/","ruleName":"hbsy_disk"},"annotations":{"summary":"hbsy_monitor  / value:6.323381014899853"}}{"startsAt":"2020-12-16T10:52:01.005713705+08:00","endsAt":"0001-01-01T00:00:00Z","values":{"host":"hbsy_monitor","max_value":17.72412783530572,"path":"/boot"},"labels":{"host":"hbsy_monitor","path":"/boot","ruleName":"hbsy_disk"},"annotations":{"summary":"hbsy_monitor  /boot value:17.72412783530572"}}{"startsAt":"2020-12-16T10:52:01.005741505+08:00","endsAt":"0001-01-01T00:00:00Z","values":{"host":"hbsy_monitor","max_value":0.24243557645334635,"path":"/home"},"labels":{"host":"hbsy_monitor","path":"/home","ruleName":"hbsy_disk"},"annotations":{"summary":"hbsy_monitor  /home value:0.24243557645334635"}}{"startsAt":"2020-12-16T10:52:01.005766386+08:00","endsAt":"0001-01-01T00:00:00Z","values":{"host":"hbsy_monitor","max_value":0.19415760869565218,"path":"/data1"},"labels":{"host":"hbsy_monitor","path":"/data1","ruleName":"hbsy_disk"},"annotations":{"summary":"hbsy_monitor  /data1 value:0.19415760869565218"}}null

**Expected Behavior**
the posted json data should be corrected formated json format.

**Environment (please complete the following information):**
 - OS: CentOS 7.6
 - Memory, CPU, current Disk Space
 - TDengine Alert Version v2.0.10.0

**Comment by localvar** [comment]
hi @maoyaowu, I checked the source code and don't think this is possible, please verify again this is the data your application received. and if you are sure, please setup a remote connection for us to help investigate what happens, thanks.

**Comment by maoyaowu** [comment]
=======================this is my java code =========	
`	        BufferedReader reader = null;
		reader = request.getReader();
		StringBuffer lineBuffer = new StringBuffer();
		boolean tag;
		
              do {
			lineBuffer.append(reader.readLine());
		} while (tag = reader.read() != -1);

		logger.info("######json string#" + lineBuffer.toString());`
======================
I use springMvc4.0.0 .The application is deployed in tomcat7.x

**Comment by maoyaowu** [comment]
[INFO] [2020-12-16 15:57:00][FileController]######header string#{content-length=4810, host=10.254.253.223:8080, content-type=application/json, accept-encoding=gzip, user-agent=Go-http-client/1.1}

**Comment by maoyaowu** [comment]
How can i setup a remote connection for you?

**Comment by localvar** [comment]
> How can i setup a remote connection for you?

pls send your contact information like wechat id to bmzhang@taosdata.com.

**Comment by maoyaowu** [comment]
my wechat id is "maoyaowu3721", thinks a lot.
