### ISSUE TITLE
A problem in the connected-car demo code

### ISSUE THREAD

**Issue by lqlstudio1** [taosdata/TDengine#459]
车联网的测试程序中,插入的数据是按照每张表插完44000条数据,在插入下一张表的数据.这样对于数据库来说它可以很快的达到一个块的大小然后落盘.但是我们实际应用中是不同的设备在同时插入数据,所以,我这边把测试代码修改了一下 for (int table = 0; table < 100000; ++table) {
     sprintf(sql, "create table v%d using vehicles tags(%d, 't%d')", table, table, table);
     if (taos_query(taos, sql) != 0) {
       printf("failed to create table t%d, reason:%s\n", table, taos_errstr(taos));
       exit(1);
     }
 

    }

  
        for (int loop = 0; loop < 44; loop++) {   
        
       for (int row = 0; row < 1000; row++) {   
         for (int table = 0; table < 100000; ++table)  
         {
          int len = sprintf(sql, "insert into v%d values", table);  
          len += sprintf(sql + len, "(%ld,%d,%d,%d,%d,%d)", 1561910400000L + 60000L * (row + loop * 1000L), row+loop * 10L, row+loop * 21L, row*21+loop, (row+loop)*3, (row+2*loop)*6);   
          if (taos_query(taos, sql) != 0) {     
         printf("failed to insert table t%d, reason:%s\n", table, taos_errstr(taos));   
       } 
          
          }
       }   
       
     }
发现插入的速度很慢,我到现在为止已经运行了2个小时了,我搜索了下每台车才插入不到500,总数不超过4800w.
我的配置是4核8g的服务器.

**Comment by lqlstudio1** [comment]
程序现在还没跑完,如果结束后,我会更新下结果.

**Comment by lqlstudio1** [comment]
目前运行了三个小时18分钟,已经插入了8190w的数据,总数是44亿,看来只能明天早上看看结果了.

**Comment by fangpanpan** [comment]
您现在是一条一条数据的插入，所以速度比较慢。其实不同表也可以批量插入多条，命令可以写成“insert into table1 values () table 2 values () table 3 values ()”这样的。

**Comment by guanshengliang** [comment]
每次请求只包含一条数据的写入方法，其写入时间主要和网络有关。
举例来说，每次请求产生一次网络来回，假如这个时间是1ms，那么单线程的情况下，1秒时间最多写入1000条数据，这是硬件问题不是软件问题。
解决这个问题只有两种方法：
+ 增大线程数量
+ 增大每批写入的数据条数
你的批量写入方法可以通过上面给出的SQL示例完成
```
insert into table1 values () table 2 values () table 3 values ()
```
