### ISSUE TITLE
"Invalid SQL" when inserting with a batch size of 1000

### ISSUE THREAD

**Issue by vonlippmann** [taosdata/TDengine#460]
批量插入千行以上的数据总是提示invalid sql，800行都没问题，然后我把插入千行的sql语句粘贴到taos终端尝试一下，结果taos终端直接奔溃了，不停的在粘贴滚动，根本停不下来。这是什么情况？

**Comment by guanshengliang** [comment]
The maximum sql statement is 64K.

**Comment by hzcheng** [comment]
向taos终端中粘贴大数据量的语句目前有bug，不建议粘贴大的语句。可以将语句写在文件中，然后用source执行。

**Comment by vonlippmann** [comment]
好，我看了一下，我的正好65kb了，不是批量插入能提高性能吗，为什么对这个做限制呢？我就用了两个浮点值，三个标签，1000行都到不了。
