### ISSUE TITLE
DB error: Out of DNodes

### ISSUE THREAD

**Issue by qihangcom** [taosdata/TDengine#4605]
创建表时出现错误DB error: Out of DNodes
日志：
0x7fc46f7fe700 MND app:0x7f3330010910:0x7fc454000aa0, table:0.test.vb_pk317450367073779712, failed to get available vgroup, reason:Out of DNodes

**Comment by powersam** [comment]
刚遇到这个问题 解决了。
创建表出现out of Dnodes DB error 主要是由于系统参数限制

maxTablesPerVnode:  设定每个vnode中能够创建的最大表个数。默认值：1000000。
maxVgroupsPerDb:    每个数据库中能够使用的最大vnode个数。  每个DB可以创建固定数目的vnode，默认与CPU核数相同

所以你可以更改这两个参数中的其中一个来突破限制 （不清楚对性能影响）

**Comment by cpvmrd** [comment]
应该是创建了一个副本数大于1的DB
