### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by zhangshuyuanzz** [taosdata/TDengine#461]
- 

- 
![1567651484(1)](https://user-images.githubusercontent.com/35170358/64308045-96b07180-cfca-11e9-8d04-6ed138792115.jpg)
**Bug Description**

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by guanshengliang** [comment]
This problem has been fixed
You can pull the code and try again
