### ISSUE TITLE
double类型字段，值中位数太多

### ISSUE THREAD

**Issue by wzf55555** [taosdata/TDengine#4610]
有没有函数可以保留几位小数返回给服务器。
![image](https://user-images.githubusercontent.com/40660395/102469914-4a3d5800-408e-11eb-8790-c8fdf1afb9c9.png)
页面显示位数太多。
数据量太大，java代码中逐条修改保留位数返回页面，影响效率。

**Comment by localvar** [comment]
显示多少位小数可以在将 double 转成字符串时进行控制，是应用程序的责任，与 tdengine 无关。

**Comment by wzf55555** [comment]
前面说过了，数据量很大，就为了保留小数这个字段就要把数据遍历一遍，消耗太大。有个类似于mysql一样的round函数可以直接保留。
