### ISSUE TITLE
关闭连接时tdengine-driver导致JVM crash

### ISSUE THREAD

**Issue by duanfeixiang** [taosdata/TDengine#4612]
**Bug Description**
关闭数据库连接时，tdengine-driver导致JVM crash，导致整个应用崩溃

**To Reproduce**
都是普通平常的操作，一直有数据写入，也有查询

**Expected Behavior**
查询或者插入失败，抛个异常也还好，应用做下重试啥的，但是直接导致应用crash，这就不可控了

**Screenshots**
![image](https://user-images.githubusercontent.com/39833797/102478030-149d6c80-4098-11eb-9dbb-f2a2ffefb4cd.png)
![image](https://user-images.githubusercontent.com/39833797/102478055-1bc47a80-4098-11eb-9970-34b0a35acf2d.png)

**Environment (please complete the following information):**
 - TDengine Version 2.0.7.0
 - taos-driver： 2.0.11
 (看报错应该是与客户端的库文件有关)

**Comment by sangshuduo** [comment]
@duanfeixiang 请说明一下如何重现这个问题，最好附上相关代码

**Comment by duanfeixiang** [comment]
> @duanfeixiang 请说明一下如何重现这个问题，最好附上相关代码

我还不知道如何去重现，出现的概率挺高，重启服务不到一天就又会crash。我这边出现问题的场景是持续有数据写入，每秒总的数据量50条，三台客户端消费，客户端spring连接池管理连接，最大连接数20条。

通过分析crash文件可以看到，是关闭数据库连接时libtaos.so  taosCleanUpTcpClient方法出现了问题，详细调用链过程见上图，可以仔细分析下这个方法的代码。

建议官方复现问题可以尝试持续写入数据过程中，关闭数据库连接池中部分连接。

**Comment by zyyang-taosdata** [comment]
从jvm的信息看是在执行close方法时，触发了某个段错误，在调用本地方法taos.dll时触发的，我建议升级TDengine版本来尝试解决这个问题。

**Comment by duanfeixiang** [comment]
> 从jvm的信息看是在执行close方法时，触发了某个段错误，在调用本地方法taos.dll时触发的，我建议升级TDengine版本来尝试解决这个问题。

请问libtaos.so taosCleanUpTcpClient这个方法从2.0.7.0之后有没有修改？

**Comment by zyyang-taosdata** [comment]
> > @duanfeixiang 请说明一下如何重现这个问题，最好附上相关代码
> 
> 我还不知道如何去重现，出现的概率挺高，重启服务不到一天就又会crash。我这边出现问题的场景是持续有数据写入，每秒总的数据量50条，三台客户端消费，每个客户端都由spring连接池管理连接，最大连接数20条。
> 
> 通过分析crash文件可以看到，是关闭数据库连接时libtaos.so taosCleanUpTcpClient方法出现了问题，详细调用链过程见上图，可以仔细分析下这个方法的代码。
> 
> 建议官方复现问题可以尝试持续写入数据过程中，关闭数据库连接池中部分连接。

我们做过持续写入的测试，在使用连接池时，对连接进行关闭是很正常的操作，如果你是尝试复现问题，我建议你可以关注libtaos.so的实现本身。

**Comment by zyyang-taosdata** [comment]
> > 从jvm的信息看是在执行close方法时，触发了某个段错误，在调用本地方法taos.dll时触发的，我建议升级TDengine版本来尝试解决这个问题。
> 
> 请问libtaos.so taosCleanUpTcpClient这个方法从2.0.7.0之后有没有修改？

我不太清楚这个方法是否有做修改，如果想了解详细的变化，我建议你可以去看源码，每个版本在release中都有对应的分支。

**Comment by duanfeixiang** [comment]
> > > 从jvm的信息看是在执行close方法时，触发了某个段错误，在调用本地方法taos.dll时触发的，我建议升级TDengine版本来尝试解决这个问题。
> > 
> > 
> > 请问libtaos.so taosCleanUpTcpClient这个方法从2.0.7.0之后有没有修改？
> 
> 我不太清楚这个方法是否有做修改，如果想了解详细的变化，我建议你可以去看源码，每个版本在release中都有对应的分支。

看了下，分支太多了，请问对外提供的版本是从哪个分支出的？我去check下这个方法从2.0.7.0之后有没有修改过，如果有修改过我可以尝试升级后观察下，如果都没有没有修改过，升级是没有用的，还是要继续定位下原因了。

**Comment by duanfeixiang** [comment]
> @duanfeixiang 请说明一下如何重现这个问题，最好附上相关代码

https://github.com/taosdata/TDengine/issues/4232
你好，刚才翻记录看到之前别人也提过一个类似的问题，最终都是执行到代码  libtaos.so   taosStopTcpThread --> pthread_cancel  crash了，看说明2.0.7.0里面也是没有解决的，请教一下，这个当时定位是什么原因导致的，2.0.8.0里面合入了吗？

**Comment by zyyang-taosdata** [comment]
> > @duanfeixiang 请说明一下如何重现这个问题，最好附上相关代码
> 
> #4232
> 你好，刚才翻记录看到之前别人也提过一个类似的问题，最终都是执行到代码 libtaos.so taosStopTcpThread --> pthread_cancel crash了，看说明2.0.7.0里面也是没有解决的，请教一下，这个当时定位是什么原因导致的，2.0.8.0里面合入了吗？

我问了维护client的同事，这个错误在2.0.10.0版本中已经修复。

**Comment by sangshuduo** [comment]
@duanfeixiang 换新版本问题解决了吗？我先关闭，如果没有解决请重新打开

**Comment by duanfeixiang** [comment]
> @duanfeixiang 换新版本问题解决了吗？我先关闭，如果没有解决请重新打开

嗯嗯，升级到2.0.10.0版本之后，再没出现过crash的问题了，谢谢
