### ISSUE TITLE
急！！！golang 查询avg sum等函数，scan获取的数据均是异常数据

### ISSUE THREAD

**Issue by mitty1987** [taosdata/TDengine#4613]
在数据库里直接执行sql 查询avg等数据都是正常的，但在golang中查询数据均是异常数据
version:
2.0.10.0
sql:
select avg(atmosphere), sum(tsp), 
				avg(noise)) from tb1 where ts >= 1608224400000 and ts < 1608228000000
code:
err := rows.Scan(&atmosphere2, &tsp2, &noise)
类型均是*float64，

**Comment by sangshuduo** [comment]
请贴一下 describe tb1 ， taos 里执行select 和 go 代码里执行的结果

**Comment by mitty1987** [comment]
db里查询结果
![image](https://user-images.githubusercontent.com/11976492/102573185-dac87680-4128-11eb-821c-d0556d415f6f.png)
go执行结果：
![image](https://user-images.githubusercontent.com/11976492/102575539-3f3a0480-412e-11eb-9653-e57d06145c75.png)

**Comment by sangshuduo** [comment]
我用 TDengine 自带的 examples/go/taosdemo.go 改了几行代码做的简单测试没有问题。有点怀疑是不是你服务端和应用用的时区不一样导致的时间范围内没有数据？

**Comment by sangshuduo** [comment]
类型均是\*float64

---

类型应该是 float64，scan的时候用 & 才对吧？

**Comment by mitty1987** [comment]
用了&的，死马当活马医，我试了各种都不行。说到时区，我也个问题，我用的TDengine docker时区是+8的，主机也是+8，但是这里传非时间戳就始终多8小时...没办法才改成时间戳，现在应该不是时区的问题了，因为如果没有数据是rows count=0 。然后相同条件下用last数据就是正常的

**Comment by mitty1987** [comment]
去掉ts区间，得到结果 atmosphere: -3567852400000000147496354429844586496.0000...
这...

**Comment by sangshuduo** [comment]
初步判断是你的代码的问题，可能就是指针用的不对。没有代码我也帮不上忙了。

**Comment by mitty1987** [comment]
rows, err := CurrentTaosDB.db.Query("select last(atmosphere), avg(atmosphere) from HZYW0HZ0010054 ")
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	defer rows.Close()
	var atmosphere1 float32
	var atmosphere2 float64
	if rows.Next() {
		err := rows.Scan(&atmosphere1, &atmosphere2)
		if err != nil {
			fmt.Println(err)
			return nil, err
		}
		fmt.Printf("last atmosphere: %f \n avg atmosphere: %f \n avg", atmosphere1, atmosphere2)
	}

**Comment by mitty1987** [comment]
头疼...我go换了几个版本试了一下还是不行...还有可能会什么原因？

**Comment by sangshuduo** [comment]
@mitty1987 go是跑在什么平台上？

**Comment by datafeng** [comment]
你们taos golang的DB驱动用的是哪个？

**Comment by mitty1987** [comment]
环境:
Linux 31d32f4840e6 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 Linux
@sangshuduo

**Comment by mitty1987** [comment]
驱动就是用的最新版本2.0.10.0里带的那个libtaos.so.2.0.10.0
@datafeng

**Comment by sangshuduo** [comment]
@mitty1987 我在 Centos7.8.2003, go 1.15.2 ，TDengine 2.0.10.0 

![](https://user-images.githubusercontent.com/825729/102605144-d23f6280-415f-11eb-95cb-dbb410c8c3a1.png)

![](https://user-images.githubusercontent.com/825729/102605343-19c5ee80-4160-11eb-8396-143c44b4306c.png)

**Comment by mitty1987** [comment]
我算是没有折了...
我写了干净的独立代码，查询的是taos自带的log数据库
![image](https://user-images.githubusercontent.com/11976492/102610800-c2784c00-4168-11eb-809a-baf956a52838.png)
在docker centos里跑
![image](https://user-images.githubusercontent.com/11976492/102610855-db80fd00-4168-11eb-9b9a-30a12623fd01.png)
还是这样
每次运行的结果还不一样
![image](https://user-images.githubusercontent.com/11976492/102610908-f5224480-4168-11eb-90ee-7fba7ee977ff.png)
啊....崩溃中！

**Comment by mitty1987** [comment]
我建了新的docker数据库...依旧如此...这太诡异了吧，会不会是taos的docker版本有问题？

**Comment by sangshuduo** [comment]
我用 docker tdengine/tdengine:latest 镜像，内部安装 go 1.13 ，没问题

**Comment by sangshuduo** [comment]
看起来不是 TDengine 的问题，请 @mitty1987  再自查一下，暂时关闭。
