### ISSUE TITLE
data copy migration failed

### ISSUE THREAD

**Issue by lacezeng** [taosdata/TDengine#4618]
问题：数据副本迁移失败，是什么原因？三副本跟两副本一样的现象。
集群配置：节点数4，mnode默认3个，离线驱逐时间设置为60秒，其他配置默认。

问题描述:
1. 集群正常时的mnode和dnode如下:
![image](https://user-images.githubusercontent.com/71378259/102571950-d189da80-4125-11eb-8eef-0b3050239047.png)

![image](https://user-images.githubusercontent.com/71378259/102572006-f2523000-4125-11eb-8ae9-f58bc97a952a.png)

2. 在122节点上执行 systemctl stop taosd之后
![image](https://user-images.githubusercontent.com/71378259/102572083-23326500-4126-11eb-843b-efa96b20e27e.png)

3. 离线被驱逐时间设置成60秒了，大概三分半钟左右122节点状态变为dropping，mnode此时仍是offline状态，此时可看出另外一个节点多了一个vnode
![image](https://user-images.githubusercontent.com/71378259/102572271-9045fa80-4126-11eb-9928-8de32c09ee3c.png)

4. 此时vgroup内的的状态如下图，所有vnode已经处于unsynced状态，没有online的vnode了:
![image](https://user-images.githubusercontent.com/71378259/102572337-c1bec600-4126-11eb-93d7-617b292dfa72.png)

5. 等到20分钟时仍保持3和4的状态，此时，在122上手动执行 systemctl start taosd，集群瞬间恢复正常，122被驱逐成功，vnode迁移成功，vgroup恢复正常。
![image](https://user-images.githubusercontent.com/71378259/102572545-650fdb00-4127-11eb-8078-c5512c94727a.png)

![image](https://user-images.githubusercontent.com/71378259/102572572-748f2400-4127-11eb-8070-5f75e052a5e2.png)

**Comment by sangshuduo** [comment]
@lacezeng 你用的是什么版本？我用自己编译的 develop 分支重复这个过程，在第4步的时候也没问题，vnode迁移成功。如下图：centos7-3 被停下后，vnode 从 centos7-3 迁移到 centos7-2。我又在其他dnode试了，也没问题。

![](https://user-images.githubusercontent.com/825729/102578803-f8e8a380-4135-11eb-8ea7-33891dc1db13.png)

**Comment by lacezeng** [comment]
版本是2.0.9.0，linux安装包: TDengine-server-2.0.9.0-Linux-x64.tar.gz
![image](https://user-images.githubusercontent.com/71378259/102595914-5e975880-4153-11eb-9fc0-d08b507266b3.png)

**Comment by sangshuduo** [comment]
新代码没发现这个问题，这种情况通常我们不会调试旧版本了。等后面新版本发布了你再试试
