### ISSUE TITLE
聚合操作放在client端导致网络传输数据量过大

### ISSUE THREAD

**Issue by subjectxbj** [taosdata/TDengine#462]
比方说我现在要对一亿条数据进行Average操作，按照TDEngine的设计，需要在client端做聚合操作，那么就需要从数据节点读取所有一亿条数据然后在本地做Average计算，这样的数据量会很大，传输可能会花很长时间。这样会不会导致操作延迟呢？

**Comment by guanshengliang** [comment]
仅不同vnode的聚合结果可能需要在客户端集合一下
单表的大量数据聚合均在服务端进行，不会产生大量的数据传输

**Comment by subjectxbj** [comment]
我想也应该是这样子设计的。只是下面这篇文档里面的表述貌似不太清楚：
https://www.taosdata.com/cn/documentation/more-on-system-architecture/#存储设计

···
当所有查询涉及的数据节点返回结果后，客户端将每个数据节点查询的结果集再次进行聚合（针对本案例，即将所有结果再次进行累加），累加的结果即为最后的查询结果。第二阶段聚合并不是所有的查询都需要。例如，针对数据的列选取操作，实际上是不需要第二阶段聚合。
···
