### ISSUE TITLE
使用`use db`命令后，无法创建表

### ISSUE THREAD

**Issue by hongguangguo** [taosdata/TDengine#4626]
![Screenshot from 2020-12-18 15-43-40](https://user-images.githubusercontent.com/12960656/102588246-1d4d7b80-4148-11eb-8062-c673cdb83a60.png)

1.`show database;`命令提示有这个数据库

2.客户端和服务端不在同一台机器，但客户端能链接服务端,并且已经配置了hostname

**Comment by sangshuduo** [comment]
@hongguangguo 什么版本？show dnodes, show mnodes, use db 后 show vgroups 输出是什么？

**Comment by PascalMing** [comment]
以前好像可以。最近试了不行，调用就出错 use db就出错。
可以在getconn中指定db，避免使用use db就行。用完就关，下次用再开或多开几个conn

**Comment by sangshuduo** [comment]
建议升级到最新版本，有问题再报
