### ISSUE TITLE
About the design of data blocks in each data file

### ISSUE THREAD

**Issue by subjectxbj** [taosdata/TDengine#464]
设计文档中介绍数据块结构如下：
···
[列1信息]
[列2信息]
...
[列N信息]
[列1数据]
[列2数据]
...
[列N数据]
···

也就是说一个列数据中保存多个该列的历史数据，然后下一个列数据保存另外一个列的历史数据。那这样的话，如果往列1数据里面添加数据，必须把列2...数据都得往后面移，这样子效率不是很低吗？

或者是说数据一旦写入磁盘，不会再插入新数据？新的数据保存在缓存，直到下一次写磁盘到一个新的文件？

**Comment by hzcheng** [comment]
文章可能描述不太清楚。是这样的，data文件是只追加的，且是以块的形式向后追加的。假设有
2张表，文件的形式可能如下
```
[table 1 block 1] [table 2 block 1] [table 2 block 2] [table 1 block 2]....
```
数据块中的组织形式是按列存储的。
因此属于同一张表的数据不会严格连续，而是以块的形式分布在文件中。因此不需要挪动数据块。
