### ISSUE TITLE
DNS problem led the issue the windows client cannot connect the server on the ali cloud

### ISSUE THREAD

**Issue by limanyi185** [taosdata/TDengine#4642]
new log file                      
==================================================
12/21 17:35:35.147000 0x00002e54 UTL all debug flag are set to 135
12/21 17:35:35.147000 0x00002e54 UTL all debug flag are set to 135
12/21 17:35:35.152000 0x00002e54 UTL localEp is: DESKTOP-2VAORRG:6030
12/21 17:35:35.152000 0x00002e54 UTL timezone not configured, use default
12/21 17:35:35.177000 0x00002e54 UTL locale not configured, set to default:Chinese_China.936
12/21 17:35:35.177000 0x00002e54 UTL charset not configured, set to default:cp936
12/21 17:35:35.177000 0x00002e54 UTL    taos config & system info:
12/21 17:35:35.177000 0x00002e54 UTL ==================================
12/21 17:35:35.177000 0x00002e54 UTL  firstEp:                node1:6030 
12/21 17:35:35.177000 0x00002e54 UTL  secondEp:               DESKTOP-2VAORRG:6030 
12/21 17:35:35.177000 0x00002e54 UTL  fqdn:                   DESKTOP-2VAORRG 
12/21 17:35:35.177000 0x00002e54 UTL  serverPort:             6030 
12/21 17:35:35.177000 0x00002e54 UTL  configDir:              cfg 
12/21 17:35:35.177000 0x00002e54 UTL  logDir:                 C:/TDengine/log 
12/21 17:35:35.177000 0x00002e54 UTL  scriptDir:              C:/TDengine/script 
12/21 17:35:35.177000 0x00002e54 UTL  arbitrator:              
12/21 17:35:35.177000 0x00002e54 UTL  numOfThreadsPerCore:    1.000000 
12/21 17:35:35.177000 0x00002e54 UTL  rpcTimer:               1000(ms)
12/21 17:35:35.177000 0x00002e54 UTL  rpcMaxTime:             600(s)
12/21 17:35:35.177000 0x00002e54 UTL  shellActivityTimer:     3(s)
12/21 17:35:35.177000 0x00002e54 UTL  tableMetaKeepTimer:     7200(s)
12/21 17:35:35.177000 0x00002e54 UTL  compressMsgSize:        -1 
12/21 17:35:35.177000 0x00002e54 UTL  maxSQLLength:           65480(byte)
12/21 17:35:35.177000 0x00002e54 UTL  maxNumOfOrderedRes:     100000 
12/21 17:35:35.177000 0x00002e54 UTL  keepColumnName:         0 
12/21 17:35:35.177000 0x00002e54 UTL  timezone:               not configured 
12/21 17:35:35.177000 0x00002e54 UTL  locale:                 Chinese_China.936 
12/21 17:35:35.177000 0x00002e54 UTL  charset:                cp936 
12/21 17:35:35.177000 0x00002e54 UTL  numOfLogLines:          10000000 
12/21 17:35:35.177000 0x00002e54 UTL  logKeepDays:            0 
12/21 17:35:35.177000 0x00002e54 UTL  asyncLog:               1 
12/21 17:35:35.177000 0x00002e54 UTL  debugFlag:              135 
12/21 17:35:35.177000 0x00002e54 UTL  rpcDebugFlag:           135 
12/21 17:35:35.177000 0x00002e54 UTL  tmrDebugFlag:           131 
12/21 17:35:35.177000 0x00002e54 UTL  cDebugFlag:             135 
12/21 17:35:35.177000 0x00002e54 UTL  jniDebugFlag:           135 
12/21 17:35:35.177000 0x00002e54 UTL  odbcDebugFlag:          135 
12/21 17:35:35.177000 0x00002e54 UTL  uDebugFlag:             135 
12/21 17:35:35.177000 0x00002e54 UTL  qDebugFlag:             135 
12/21 17:35:35.177000 0x00002e54 UTL  tsdbDebugFlag:          135 
12/21 17:35:35.177000 0x00002e54 UTL  gitinfo:                community 
12/21 17:35:35.177000 0x00002e54 UTL  gitinfoOfInternal:      internal 
12/21 17:35:35.177000 0x00002e54 UTL  buildinfo:              Built at 2020-12-20 21:58:09 
12/21 17:35:35.177000 0x00002e54 UTL  version:                2.0.11.0 
12/21 17:35:35.177000 0x00002e54 UTL  maxBinaryDisplayWidth:  30 
12/21 17:35:35.177000 0x00002e54 UTL  tempDir:                C:\Users\569\AppData\Local\Temp 
12/21 17:35:35.177000 0x00002e54 TSC starting to initialize TAOS client ...
12/21 17:35:35.177000 0x00002e54 TSC Local End Point is:DESKTOP-2VAORRG:6030
12/21 17:35:35.177000 0x00002e54 UTL tsc scheduler is initialized, numOfThreads:2
12/21 17:35:35.178000 0x00002e54 UTL tmr scheduler is initialized, numOfThreads:1
12/21 17:35:35.178000 0x00002e54 TSC client is initialized successfully
12/21 17:35:35.178000 0x00002e54 TSC try to create a connection to node1:6030, user:root db:(null)
12/21 17:35:35.178000 0x00002e54 UTL pool:0000026C5E2A8610 is setup, maxId:5000
12/21 17:35:35.178000 0x00002e54 RPC TSC TCP client is initialized, ip:0:0
12/21 17:35:35.178000 0x00002e54 UTL open udp socket:0x0:0
12/21 17:35:35.179000 0x00002e54 RPC TSC UDP connection is initialized, ip:0:0 threads:1
12/21 17:35:35.179000 0x00002e54 RPC TSC rpc is opened, threads:1 sessions:5000
12/21 17:35:35.179000 0x00002e54 TSC dnodeConn:0000026C5E2B3510 is created, user:root
12/21 17:35:35.179000 0x00002e54 TSC 0000026C5E4C70A0 add to tscObj:0000026C5E2AA2D0, ref:2
12/21 17:35:35.179000 0x00002e54 TSC 0000026C5E4C70A0 SQL cmd:connect will be processed, name:(null), type:0
12/21 17:35:35.179000 0x00003084 RPC TSC UDP thread is created, index:0
12/21 17:35:35.180000 0x00002e54 RPC TSC 0000026C6032A1B8 client connection is allocated, uid:0x60330e31
12/21 17:35:35.180000 0x00002e54 RPC TSC UDP connection is setup, ip:e6b8b276:6030 localPort:55780
12/21 17:35:35.180000 0x00002e54 RPC TSC 0000026C6032A1B8 0000000000000002, connect is sent to node1:6030, len:373 sig:0x01000000:0x00000000:17030
12/21 17:35:36.184000 0x00001fc8 RPC TSC 0000026C6032A1B8 0000000000000002, expected connect-rsp is not received
12/21 17:35:36.184000 0x00001fc8 RPC TSC 0000026C6032A1B8 0000000000000002, re-send msg:connect to node1:6030
12/21 17:35:36.184000 0x00001fc8 RPC TSC 0000026C6032A1B8 0000000000000002, connect is sent to node1:6030, len:373 sig:0x01000000:0x00000000:17030
12/21 17:35:37.189000 0x00001fc8 RPC TSC 0000026C6032A1B8 0000000000000002, expected connect-rsp is not received
12/21 17:35:37.189000 0x00001fc8 RPC TSC 0000026C6032A1B8 0000000000000002, re-send msg:connect to node1:6030
12/21 17:35:37.189000 0x00001fc8 RPC TSC 0000026C6032A1B8 0000000000000002, connect is sent to node1:6030, len:373 sig:0x01000000:0x00000000:17030
12/21 17:35:38.194000 0x00001fc8 RPC TSC 0000026C6032A1B8 0000000000000002, expected connect-rsp is not received
12/21 17:35:38.194000 0x00001fc8 RPC TSC 0000026C6032A1B8 0000000000000002, re-send msg:connect to node1:6030
12/21 17:35:38.194000 0x00001fc8 RPC TSC 0000026C6032A1B8 0000000000000002, connect is sent to node1:6030, len:373 sig:0x01000000:0x00000000:17030
12/21 17:35:39.199000 0x00001fc8 RPC TSC 0000026C6032A1B8 0000000000000002, expected connect-rsp is not received
12/21 17:35:39.199000 0x00001fc8 RPC TSC 0000026C6032A1B8 0000000000000002, failed to send msg:connect to node1:6030
12/21 17:35:39.199000 0x00001fc8 RPC TSC 0000026C6032A1B8 0000000000000002, rpc connection is released
12/21 17:35:39.199000 0x00001fc8 RPC TSC 0000000000000002, connection error happens
12/21 17:35:39.199000 0x00001fc8 TSC 0000026C5E4C70A0 SQL cmd:connect, code:Unable to establish connection rspLen:0
12/21 17:35:39.199000 0x00002e54 TSC 0000026C5E4C70A0 free sqlObj in cache
12/21 17:35:39.199000 0x00002e54 TSC 0000026C5E4C70A0 start to free sqlObj
12/21 17:35:39.199000 0x00002e54 TSC 0000026C5E4C70A0 free sqlObj completed, tscObj:0000026C5E2AA2D0 ref:1
12/21 17:35:39.199000 0x00002e54 TSC 0000026C5E2AA2D0 try to free tscObj and close dnodeConn:0000026C5E2B3510
12/21 17:35:39.199000 0x00002e54 TSC 0000026C5E2AA2D0 all sqlObj are freed, free tscObj and close dnodeConn:0000026C5E2B3510
12/21 17:35:39.199000 0x00002e54 RPC TSC TCP client is stopped
12/21 17:35:39.199000 0x00003084 RPC TSC UDP socket was closed, exiting(No error)
12/21 17:35:39.199000 0x00002e54 RPC TSC UDP is stopped
12/21 17:35:39.199000 0x00002e54 RPC TSC TCP client will be cleaned up
12/21 17:35:39.214000 0x0000144c RPC TSC TCP thread get stop event, exiting...
12/21 17:35:39.214000 0x0000144c RPC TSC TCP thread exits ...
12/21 17:35:39.214000 0x00002e54 RPC TSC UDP is cleaned up
12/21 17:35:39.214000 0x00002e54 RPC TSC rpc is closed
12/21 17:35:39.214000 0x00002e54 UTL pool:0000026C5E2A8610 is cleaned
12/21 17:35:39.214000 0x00002e54 RPC TSC rpc resources are released
12/21 17:35:39.214000 0x00002e54 TSC 0000026C5E2AA2D0 DB connection is closed, dnodeConn:0000026C5E2B3510
12/21 17:35:39.216000 0x00002e54 TSC start to cleanup client environment
12/21 17:35:39.684000 0x000018c8 UTL tableMeta refresh threads quit
12/21 17:35:39.684000 0x00002e54 UTL cache:tableMeta will be cleaned up
==================================================
                new log file                      
==================================================
12/22 09:00:55.331000 0x00001f9c UTL all debug flag are set to 135
12/22 09:00:55.331000 0x00001f9c UTL all debug flag are set to 135
12/22 09:00:55.338000 0x00001f9c UTL localEp is: DESKTOP-2VAORRG:6030
12/22 09:00:55.338000 0x00001f9c UTL timezone not configured, use default
12/22 09:00:55.363000 0x00001f9c UTL locale not configured, set to default:Chinese_China.936
12/22 09:00:55.363000 0x00001f9c UTL charset not configured, set to default:cp936
12/22 09:00:55.363000 0x00001f9c UTL    taos config & system info:
12/22 09:00:55.363000 0x00001f9c UTL ==================================
12/22 09:00:55.363000 0x00001f9c UTL  firstEp:                node1:6030 
12/22 09:00:55.363000 0x00001f9c UTL  secondEp:               DESKTOP-2VAORRG:6030 
12/22 09:00:55.363000 0x00001f9c UTL  fqdn:                   DESKTOP-2VAORRG 
12/22 09:00:55.363000 0x00001f9c UTL  serverPort:             6030 
12/22 09:00:55.363000 0x00001f9c UTL  configDir:              cfg 
12/22 09:00:55.363000 0x00001f9c UTL  logDir:                 C:/TDengine/log 
12/22 09:00:55.363000 0x00001f9c UTL  scriptDir:              C:/TDengine/script 
12/22 09:00:55.363000 0x00001f9c UTL  arbitrator:              
12/22 09:00:55.363000 0x00001f9c UTL  numOfThreadsPerCore:    1.000000 
12/22 09:00:55.363000 0x00001f9c UTL  rpcTimer:               1000(ms)
12/22 09:00:55.363000 0x00001f9c UTL  rpcMaxTime:             600(s)
12/22 09:00:55.363000 0x00001f9c UTL  shellActivityTimer:     3(s)
12/22 09:00:55.363000 0x00001f9c UTL  tableMetaKeepTimer:     7200(s)
12/22 09:00:55.363000 0x00001f9c UTL  compressMsgSize:        -1 
12/22 09:00:55.363000 0x00001f9c UTL  maxSQLLength:           65480(byte)
12/22 09:00:55.363000 0x00001f9c UTL  maxNumOfOrderedRes:     100000 
12/22 09:00:55.363000 0x00001f9c UTL  keepColumnName:         0 
12/22 09:00:55.363000 0x00001f9c UTL  timezone:               not configured 
12/22 09:00:55.363000 0x00001f9c UTL  locale:                 Chinese_China.936 
12/22 09:00:55.363000 0x00001f9c UTL  charset:                cp936 
12/22 09:00:55.363000 0x00001f9c UTL  numOfLogLines:          10000000 
12/22 09:00:55.363000 0x00001f9c UTL  logKeepDays:            0 
12/22 09:00:55.363000 0x00001f9c UTL  asyncLog:               1 
12/22 09:00:55.363000 0x00001f9c UTL  debugFlag:              135 
12/22 09:00:55.363000 0x00001f9c UTL  rpcDebugFlag:           135 
12/22 09:00:55.363000 0x00001f9c UTL  tmrDebugFlag:           131 
12/22 09:00:55.363000 0x00001f9c UTL  cDebugFlag:             135 
12/22 09:00:55.363000 0x00001f9c UTL  jniDebugFlag:           135 
12/22 09:00:55.363000 0x00001f9c UTL  odbcDebugFlag:          135 
12/22 09:00:55.363000 0x00001f9c UTL  uDebugFlag:             135 
12/22 09:00:55.363000 0x00001f9c UTL  qDebugFlag:             135 
12/22 09:00:55.363000 0x00001f9c UTL  tsdbDebugFlag:          135 
12/22 09:00:55.363000 0x00001f9c UTL  gitinfo:                community 
12/22 09:00:55.363000 0x00001f9c UTL  gitinfoOfInternal:      internal 
12/22 09:00:55.363000 0x00001f9c UTL  buildinfo:              Built at 2020-12-20 21:58:09 
12/22 09:00:55.363000 0x00001f9c UTL  version:                2.0.11.0 
12/22 09:00:55.363000 0x00001f9c UTL  maxBinaryDisplayWidth:  30 
12/22 09:00:55.363000 0x00001f9c UTL  tempDir:                C:\Users\569\AppData\Local\Temp 
12/22 09:00:55.363000 0x00001f9c TSC starting to initialize TAOS client ...
12/22 09:00:55.363000 0x00001f9c TSC Local End Point is:DESKTOP-2VAORRG:6030
12/22 09:00:55.363000 0x00001f9c UTL tsc scheduler is initialized, numOfThreads:2
12/22 09:00:55.363000 0x00001f9c UTL tmr scheduler is initialized, numOfThreads:1
12/22 09:00:55.364000 0x00001f9c TSC client is initialized successfully
12/22 09:00:55.364000 0x00001f9c TSC try to create a connection to node1:6030, user:root db:(null)
12/22 09:00:55.364000 0x00001f9c UTL pool:00000255302D62D0 is setup, maxId:5000
12/22 09:00:55.364000 0x00001f9c RPC TSC TCP client is initialized, ip:0:0
12/22 09:00:55.364000 0x00001f9c UTL open udp socket:0x0:0
12/22 09:00:55.364000 0x00001f9c RPC TSC UDP connection is initialized, ip:0:0 threads:1
12/22 09:00:55.364000 0x00001f9c RPC TSC rpc is opened, threads:1 sessions:5000
12/22 09:00:55.364000 0x00001f9c TSC dnodeConn:00000255302DFD90 is created, user:root
12/22 09:00:55.364000 0x00001f9c TSC 000002553226F210 add to tscObj:00000255302DFAE0, ref:2
12/22 09:00:55.364000 0x00001f9c TSC 000002553226F210 SQL cmd:connect will be processed, name:(null), type:0
12/22 09:00:55.364000 0x00001748 RPC TSC UDP thread is created, index:0
12/22 09:00:57.639000 0x00001f9c UTL ERROR failed to get the ip address, fqdn:node1, since:不知道这样的主机。 
12/22 09:00:57.639000 0x00001f9c RPC ERROR TSC, failed to resolve FQDN:node1
12/22 09:00:57.639000 0x00001f9c RPC ERROR TSC 0000000000000002, failed to set up connection(Unable to resolve FQDN)
12/22 09:00:57.639000 0x00003480 RPC TSC 0000000000000002, connection error happens
12/22 09:00:57.639000 0x00003480 TSC 000002553226F210 SQL cmd:connect, code:Unable to resolve FQDN rspLen:0
12/22 09:00:57.639000 0x00001f9c TSC 000002553226F210 free sqlObj in cache
12/22 09:00:57.639000 0x00001f9c TSC 000002553226F210 start to free sqlObj
12/22 09:00:57.639000 0x00001f9c TSC 000002553226F210 free sqlObj completed, tscObj:00000255302DFAE0 ref:1
12/22 09:00:57.639000 0x00001f9c TSC 00000255302DFAE0 try to free tscObj and close dnodeConn:00000255302DFD90
12/22 09:00:57.639000 0x00001f9c TSC 00000255302DFAE0 all sqlObj are freed, free tscObj and close dnodeConn:00000255302DFD90
12/22 09:00:57.639000 0x00001f9c RPC TSC TCP client is stopped
12/22 09:00:57.639000 0x00001748 RPC TSC UDP socket was closed, exiting(No error)
12/22 09:00:57.640000 0x00001f9c RPC TSC UDP is stopped
12/22 09:00:57.640000 0x00001f9c RPC TSC TCP client will be cleaned up
12/22 09:00:57.681000 0x00001218 RPC TSC TCP thread get stop event, exiting...
12/22 09:00:57.681000 0x00001218 RPC TSC TCP thread exits ...
12/22 09:00:57.681000 0x00001f9c RPC TSC UDP is cleaned up
12/22 09:00:57.681000 0x00001f9c RPC TSC rpc is closed
12/22 09:00:57.681000 0x00001f9c UTL pool:00000255302D62D0 is cleaned
12/22 09:00:57.681000 0x00001f9c RPC TSC rpc resources are released
12/22 09:00:57.681000 0x00001f9c TSC 00000255302DFAE0 DB connection is closed, dnodeConn:00000255302DFD90
12/22 09:00:57.683000 0x00001f9c TSC start to cleanup client environment
12/22 09:00:57.867000 0x00003764 UTL tableMeta refresh threads quit
12/22 09:00:57.867000 0x00001f9c UTL cache:tableMeta will be cleaned up
==================================================
                new log file                      
==================================================
12/22 09:03:59.659000 0x00003658 UTL all debug flag are set to 135
12/22 09:03:59.659000 0x00003658 UTL all debug flag are set to 135
12/22 09:03:59.664000 0x00003658 UTL localEp is: DESKTOP-2VAORRG:6030
12/22 09:03:59.664000 0x00003658 UTL timezone not configured, use default
12/22 09:03:59.690000 0x00003658 UTL locale not configured, set to default:Chinese_China.936
12/22 09:03:59.690000 0x00003658 UTL charset not configured, set to default:cp936
12/22 09:03:59.690000 0x00003658 UTL    taos config & system info:
12/22 09:03:59.690000 0x00003658 UTL ==================================
12/22 09:03:59.690000 0x00003658 UTL  firstEp:                node1:6030 
12/22 09:03:59.690000 0x00003658 UTL  secondEp:               DESKTOP-2VAORRG:6030 
12/22 09:03:59.690000 0x00003658 UTL  fqdn:                   DESKTOP-2VAORRG 
12/22 09:03:59.690000 0x00003658 UTL  serverPort:             6030 
12/22 09:03:59.690000 0x00003658 UTL  configDir:              cfg 
12/22 09:03:59.690000 0x00003658 UTL  logDir:                 C:/TDengine/log 
12/22 09:03:59.690000 0x00003658 UTL  scriptDir:              C:/TDengine/script 
12/22 09:03:59.690000 0x00003658 UTL  arbitrator:              
12/22 09:03:59.690000 0x00003658 UTL  numOfThreadsPerCore:    1.000000 
12/22 09:03:59.690000 0x00003658 UTL  rpcTimer:               1000(ms)
12/22 09:03:59.690000 0x00003658 UTL  rpcMaxTime:             600(s)
12/22 09:03:59.690000 0x00003658 UTL  shellActivityTimer:     3(s)
12/22 09:03:59.690000 0x00003658 UTL  tableMetaKeepTimer:     7200(s)
12/22 09:03:59.690000 0x00003658 UTL  compressMsgSize:        -1 
12/22 09:03:59.690000 0x00003658 UTL  maxSQLLength:           65480(byte)
12/22 09:03:59.690000 0x00003658 UTL  maxNumOfOrderedRes:     100000 
12/22 09:03:59.690000 0x00003658 UTL  keepColumnName:         0 
12/22 09:03:59.690000 0x00003658 UTL  timezone:               not configured 
12/22 09:03:59.690000 0x00003658 UTL  locale:                 Chinese_China.936 
12/22 09:03:59.690000 0x00003658 UTL  charset:                cp936 
12/22 09:03:59.690000 0x00003658 UTL  numOfLogLines:          10000000 
12/22 09:03:59.690000 0x00003658 UTL  logKeepDays:            0 
12/22 09:03:59.690000 0x00003658 UTL  asyncLog:               1 
12/22 09:03:59.690000 0x00003658 UTL  debugFlag:              135 
12/22 09:03:59.690000 0x00003658 UTL  rpcDebugFlag:           135 
12/22 09:03:59.690000 0x00003658 UTL  tmrDebugFlag:           131 
12/22 09:03:59.690000 0x00003658 UTL  cDebugFlag:             135 
12/22 09:03:59.690000 0x00003658 UTL  jniDebugFlag:           135 
12/22 09:03:59.690000 0x00003658 UTL  odbcDebugFlag:          135 
12/22 09:03:59.690000 0x00003658 UTL  uDebugFlag:             135 
12/22 09:03:59.690000 0x00003658 UTL  qDebugFlag:             135 
12/22 09:03:59.690000 0x00003658 UTL  tsdbDebugFlag:          135 
12/22 09:03:59.690000 0x00003658 UTL  gitinfo:                community 
12/22 09:03:59.690000 0x00003658 UTL  gitinfoOfInternal:      internal 
12/22 09:03:59.690000 0x00003658 UTL  buildinfo:              Built at 2020-12-20 21:58:09 
12/22 09:03:59.690000 0x00003658 UTL  version:                2.0.11.0 
12/22 09:03:59.690000 0x00003658 UTL  maxBinaryDisplayWidth:  30 
12/22 09:03:59.690000 0x00003658 UTL  tempDir:                C:\Users\569\AppData\Local\Temp 
12/22 09:03:59.690000 0x00003658 TSC starting to initialize TAOS client ...
12/22 09:03:59.690000 0x00003658 TSC Local End Point is:DESKTOP-2VAORRG:6030
12/22 09:03:59.690000 0x00003658 UTL tsc scheduler is initialized, numOfThreads:2
12/22 09:03:59.690000 0x00003658 UTL tmr scheduler is initialized, numOfThreads:1
12/22 09:03:59.691000 0x00003658 TSC client is initialized successfully
12/22 09:03:59.691000 0x00003658 TSC try to create a connection to node1:6030, user:root db:(null)
12/22 09:03:59.691000 0x00003658 UTL pool:00000190C12262F0 is setup, maxId:5000
12/22 09:03:59.691000 0x00003658 RPC TSC TCP client is initialized, ip:0:0
12/22 09:03:59.691000 0x00003658 UTL open udp socket:0x0:0
12/22 09:03:59.691000 0x00003658 RPC TSC UDP connection is initialized, ip:0:0 threads:1
12/22 09:03:59.691000 0x00003658 RPC TSC rpc is opened, threads:1 sessions:5000
12/22 09:03:59.691000 0x00003658 TSC dnodeConn:00000190C122E120 is created, user:root
12/22 09:03:59.691000 0x00003658 TSC 00000190C127B640 add to tscObj:00000190C2F93E10, ref:2
12/22 09:03:59.691000 0x00003658 TSC 00000190C127B640 SQL cmd:connect will be processed, name:(null), type:0
12/22 09:03:59.691000 0x0000203c RPC TSC UDP thread is created, index:0
12/22 09:03:59.693000 0x00003658 RPC TSC 00000190C31AB1B8 client connection is allocated, uid:0xc31ae573
12/22 09:03:59.693000 0x00003658 RPC TSC UDP connection is setup, ip:e6b8b276:6030 localPort:64999
12/22 09:03:59.693000 0x00003658 RPC TSC 00000190C31AB1B8 0000000000000002, connect is sent to node1:6030, len:373 sig:0x01000000:0x00000000:2328
12/22 09:04:00.695000 0x00003770 RPC TSC 00000190C31AB1B8 0000000000000002, expected connect-rsp is not received
12/22 09:04:00.695000 0x00003770 RPC TSC 00000190C31AB1B8 0000000000000002, re-send msg:connect to node1:6030
12/22 09:04:00.695000 0x00003770 RPC TSC 00000190C31AB1B8 0000000000000002, connect is sent to node1:6030, len:373 sig:0x01000000:0x00000000:2328
12/22 09:04:01.696000 0x00003770 RPC TSC 00000190C31AB1B8 0000000000000002, expected connect-rsp is not received
12/22 09:04:01.696000 0x00003770 RPC TSC 00000190C31AB1B8 0000000000000002, re-send msg:connect to node1:6030
12/22 09:04:01.696000 0x00003770 RPC TSC 00000190C31AB1B8 0000000000000002, connect is sent to node1:6030, len:373 sig:0x01000000:0x00000000:2328
12/22 09:04:02.701000 0x00003770 RPC TSC 00000190C31AB1B8 0000000000000002, expected connect-rsp is not received
12/22 09:04:02.701000 0x00003770 RPC TSC 00000190C31AB1B8 0000000000000002, re-send msg:connect to node1:6030
12/22 09:04:02.701000 0x00003770 RPC TSC 00000190C31AB1B8 0000000000000002, connect is sent to node1:6030, len:373 sig:0x01000000:0x00000000:2328
12/22 09:04:03.705000 0x00003770 RPC TSC 00000190C31AB1B8 0000000000000002, expected connect-rsp is not received
12/22 09:04:03.705000 0x00003770 RPC TSC 00000190C31AB1B8 0000000000000002, failed to send msg:connect to node1:6030
12/22 09:04:03.705000 0x00003770 RPC TSC 00000190C31AB1B8 0000000000000002, rpc connection is released
12/22 09:04:03.705000 0x00003770 RPC TSC 0000000000000002, connection error happens
12/22 09:04:03.705000 0x00003770 TSC 00000190C127B640 SQL cmd:connect, code:Unable to establish connection rspLen:0
12/22 09:04:03.705000 0x00003658 TSC 00000190C127B640 free sqlObj in cache
12/22 09:04:03.705000 0x00003658 TSC 00000190C127B640 start to free sqlObj
12/22 09:04:03.705000 0x00003658 TSC 00000190C127B640 free sqlObj completed, tscObj:00000190C2F93E10 ref:1
12/22 09:04:03.705000 0x00003658 TSC 00000190C2F93E10 try to free tscObj and close dnodeConn:00000190C122E120
12/22 09:04:03.705000 0x00003658 TSC 00000190C2F93E10 all sqlObj are freed, free tscObj and close dnodeConn:00000190C122E120
12/22 09:04:03.705000 0x00003658 RPC TSC TCP client is stopped
12/22 09:04:03.705000 0x0000203c RPC TSC UDP socket was closed, exiting(No error)
12/22 09:04:03.705000 0x00003658 RPC TSC UDP is stopped
12/22 09:04:03.705000 0x00003658 RPC TSC TCP client will be cleaned up
12/22 09:04:03.720000 0x00001be0 RPC TSC TCP thread get stop event, exiting...
12/22 09:04:03.720000 0x00001be0 RPC TSC TCP thread exits ...
12/22 09:04:03.720000 0x00003658 RPC TSC UDP is cleaned up
12/22 09:04:03.720000 0x00003658 RPC TSC rpc is closed
12/22 09:04:03.720000 0x00003658 UTL pool:00000190C12262F0 is cleaned
12/22 09:04:03.720000 0x00003658 RPC TSC rpc resources are released
12/22 09:04:03.720000 0x00003658 TSC 00000190C2F93E10 DB connection is closed, dnodeConn:00000190C122E120
12/22 09:04:03.722000 0x00003658 TSC start to cleanup client environment
12/22 09:04:04.197000 0x000024b0 UTL tableMeta refresh threads quit
12/22 09:04:04.197000 0x00003658 UTL cache:tableMeta will be cleaned [up](url)

**Comment by sangshuduo** [comment]
打开 UDP 端口后问题解决
