### ISSUE TITLE
double类型字段，值中位数太多 #4610

### ISSUE THREAD

**Issue by wzf55555** [taosdata/TDengine#4643]
![image](https://user-images.githubusercontent.com/40660395/102840778-8bdb5380-443e-11eb-87c3-72ad4fc841d5.png)
什么鬼。这就给关闭了。

**Comment by localvar** [comment]
关闭的原因是这样的：

首先：浮点数在计算机内部是以 IEEE754 标准定义的格式保存的，所以有多少位小数和性能之间没有直接关系，具体请您参考这个标准的相关文档。
第二：将浮点数显示出来的时候，必然涉及到一个转为字符串的过程，在这个过程中您可以控制小数的位数。
第三：相比在应用端进行转换，在数据库端进行转换往往意味着更低的运行效率和更大的数据传输量，对性能更不利。
第四：根据我个人的经验，正常情况下，在现代计算机上，多显示几位小数对性能的影响微乎其微，所以我怀疑您的性能问题在程序的其它地方。
