### ISSUE TITLE
use goroutine taosdemo insert data, got TMR ERROR TSC too many timer controllers, failed to create timer controller.   

### ISSUE THREAD

**Issue by renyujie518** [taosdata/TDengine#4652]
参照taosdemo.go的多协程插入数据，运行一段时间后  报错
This command has error:INSERT INTO rule_5 VALUES ("2020-12-18 17:12:06.000","g002",0.081650);
panic: taos_connect() fail!
goroutine 404 [running]:

tail日志文件如下：
12/22 14:51:25.162228 0x7f1c2e9d1dc0 UTL    taos config & system info:
12/22 14:51:25.162233 0x7f1c2e9d1dc0 UTL ==================================
12/22 14:51:25.162237 0x7f1c2e9d1dc0 UTL  firstEp:                ubuntu:6030 
12/22 14:51:25.162241 0x7f1c2e9d1dc0 UTL  secondEp:               ubuntu:6030 
12/22 14:51:25.162245 0x7f1c2e9d1dc0 UTL  fqdn:                   ubuntu 
12/22 14:51:25.162250 0x7f1c2e9d1dc0 UTL  serverPort:             6030 
12/22 14:51:25.162254 0x7f1c2e9d1dc0 UTL  configDir:              /etc/taos 
12/22 14:51:25.162258 0x7f1c2e9d1dc0 UTL  logDir:                 /var/log/taos 
12/22 14:51:25.162262 0x7f1c2e9d1dc0 UTL  scriptDir:              /etc/taos 
12/22 14:51:25.162266 0x7f1c2e9d1dc0 UTL  arbitrator:              
12/22 14:51:25.162271 0x7f1c2e9d1dc0 UTL  numOfThreadsPerCore:    1.000000 
12/22 14:51:25.162278 0x7f1c2e9d1dc0 UTL  rpcTimer:               1000(ms)
12/22 14:51:25.162283 0x7f1c2e9d1dc0 UTL  rpcMaxTime:             600(s)
12/22 14:51:25.162287 0x7f1c2e9d1dc0 UTL  shellActivityTimer:     3(s)
12/22 14:51:25.162291 0x7f1c2e9d1dc0 UTL  tableMetaKeepTimer:     7200(s)
12/22 14:51:25.162295 0x7f1c2e9d1dc0 UTL  compressMsgSize:        -1 
12/22 14:51:25.162299 0x7f1c2e9d1dc0 UTL  maxSQLLength:           65480(byte)
12/22 14:51:25.162303 0x7f1c2e9d1dc0 UTL  maxNumOfOrderedRes:     100000 
12/22 14:51:25.162308 0x7f1c2e9d1dc0 UTL  timezone:               Asia/Shanghai (CST, +0800) 
12/22 14:51:25.162312 0x7f1c2e9d1dc0 UTL  locale:                 en_US.UTF-8 
12/22 14:51:25.162316 0x7f1c2e9d1dc0 UTL  charset:                UTF-8 
12/22 14:51:25.162320 0x7f1c2e9d1dc0 UTL  numOfLogLines:          10000000 
12/22 14:51:25.162324 0x7f1c2e9d1dc0 UTL  logKeepDays:            0 
12/22 14:51:25.162328 0x7f1c2e9d1dc0 UTL  asyncLog:               1 
12/22 14:51:25.162332 0x7f1c2e9d1dc0 UTL  debugFlag:              0 
12/22 14:51:25.162336 0x7f1c2e9d1dc0 UTL  rpcDebugFlag:           131 
12/22 14:51:25.162341 0x7f1c2e9d1dc0 UTL  tmrDebugFlag:           131 
12/22 14:51:25.162345 0x7f1c2e9d1dc0 UTL  cDebugFlag:             131 
12/22 14:51:25.162350 0x7f1c2e9d1dc0 UTL  jniDebugFlag:           131 
12/22 14:51:25.162354 0x7f1c2e9d1dc0 UTL  odbcDebugFlag:          131 
12/22 14:51:25.162359 0x7f1c2e9d1dc0 UTL  uDebugFlag:             131 
12/22 14:51:25.162363 0x7f1c2e9d1dc0 UTL  qDebugFlag:             131 
12/22 14:51:25.162367 0x7f1c2e9d1dc0 UTL  tsdbDebugFlag:          131 
12/22 14:51:25.162371 0x7f1c2e9d1dc0 UTL  gitinfo:                14179afe05d13a100215ffea8f2cdd3091c9e17a 
12/22 14:51:25.162375 0x7f1c2e9d1dc0 UTL  gitinfoOfInternal:      1ce07a2e025989e77ac3496f072391d84db1c26d 
12/22 14:51:25.162379 0x7f1c2e9d1dc0 UTL  buildinfo:              Built at 2020-10-27 19:32 
12/22 14:51:25.162383 0x7f1c2e9d1dc0 UTL  version:                2.0.6.0 
12/22 14:51:25.162387 0x7f1c2e9d1dc0 UTL  maxBinaryDisplayWidth:  30 
12/22 14:51:25.162392 0x7f1c2e9d1dc0 UTL  os pageSize:            4096(KB)
12/22 14:51:25.162396 0x7f1c2e9d1dc0 UTL  os openMax:             8192
12/22 14:51:25.162400 0x7f1c2e9d1dc0 UTL  os streamMax:           16
12/22 14:51:25.162404 0x7f1c2e9d1dc0 UTL  os numOfCores:          2
12/22 14:51:25.162409 0x7f1c2e9d1dc0 UTL  os totalDisk:           0.000000(GB)
12/22 14:51:25.162414 0x7f1c2e9d1dc0 UTL  os totalMemory:         3908(MB)
12/22 14:51:25.162420 0x7f1c2e9d1dc0 UTL  os sysname:             Linux
12/22 14:51:25.162424 0x7f1c2e9d1dc0 UTL  os nodename:            ubuntu
12/22 14:51:25.162429 0x7f1c2e9d1dc0 UTL  os release:             5.4.0-58-generic
12/22 14:51:25.162432 0x7f1c2e9d1dc0 UTL  os version:             #64~18.04.1-Ubuntu SMP Wed Dec 9 17:11:11 UTC 2020
12/22 14:51:25.162436 0x7f1c2e9d1dc0 UTL  os machine:             x86_64
12/22 14:51:25.162442 0x7f1c2e9d1dc0 UTL ==================================
12/22 14:52:31.882881 0x7f1c054d6700 TMR ERROR TSC too many timer controllers, failed to create timer controller.
12/22 14:52:31.882961 0x7f1c054d6700 RPC ERROR TSC failed to init timers
12/22 14:52:31.883709 0x7f1c054d6700 TSC ERROR failed to init connection to TDengine
12/22 14:52:31.886178 0x7f1bee7fc700 TMR ERROR TSC too many timer controllers, failed to create timer controller.
12/22 14:52:31.886241 0x7f1bee7fc700 RPC ERROR TSC failed to init timers
12/22 14:52:31.886751 0x7f1bee7fc700 TSC ERROR failed to init connection to TDengine

猜想可能是协程泄露问题。经过反复试验发现其中的一部分代码修改如下即可，但会大大降低效率：
原代码：
rwlock.RLock() 
	for i := 0; i <= (len(Validrules) - 1); i++ {
		wg.Add(1)
		go TDengine_AggergateselectAndInsert(i)
		//wg.Wait()
	}
	rwlock.RUnlock() 
	wg.Wait()

修改后：
rwlock.RLock() 
	for i := 0; i <= (len(Validrules) - 1); i++ {
		wg.Add(1)
		go TDengine_AggergateselectAndInsert(i)
		wg.Wait()
	}
	rwlock.RUnlock() 
	//wg.Wait()
这样好像就行了，但实际上导致上一个协程执行完才能执行下一个，这没有达到多协程插入数据的目标，请教各位如何解决这个问题

备注：
wd.Done()在函数TDengine_AggergateselectAndInsert(i)内
TDengine_AggergateselectAndInsert(i)主要完成的功能即”query后在rows.Next()里scan并且立马insert语句插入新子表，然后close rows“

追问：
查完立马插是为了模仿连续查询create table avg_velocity as select avg(velocity) from st_znsllj interval(1m) sliding(30s);
但实际操作的时候发现想要停止连续查询是需要杀掉指定进程，这无法在程序里实现，只能通过命令行kill，请教在连续查询中如和加入停止的策略

**Comment by xiangxud** [comment]
并发访问有问题吗

**Comment by sangshuduo** [comment]
执行 taosdemo 的完整参数是什么？
go 的版本是多少？

**Comment by xiangxud** [comment]
golang 1.15 code 改自balongma prometheus server



---Original---

**Comment by sangshuduo** [comment]
我们近期会有新的机制解决这个问题。短期内可以尝试在 taos.cfg 中修改 maxTmrCtrl 参数，改大一点，看是否有改善。

**Comment by xiangxud** [comment]
感觉用golang操作tdengine问题比较多，目前项目没有办法只有暂时另选方案，期待你们的完善解决方案



---Original---
