### ISSUE TITLE
interval 偏移量问题

### ISSUE THREAD

**Issue by Luokun2016** [taosdata/TDengine#4654]
**需求**
前提 tdengine中存的数据的 时间戳为UTC时间
例如
```
       ......
       [
            "2020-12-21 23:57:00.000",
            2.000000000
        ],
        [
            "2020-12-21 23:58:00.000",
            2.000000000
        ],
        [
            "2020-12-21 23:59:00.000",
            2.000000000
        ],
        [
            "2020-12-22 00:00:00.000",
            2.000000000
        ],
        [
            "2020-12-22 00:01:00.000",
            2.000000000
        ],
        [
            "2020-12-22 00:02:00.000",
            2.000000000
        ],
        [
            "2020-12-22 00:03:00.000",
            2.000000000
        ],
        [
            "2020-12-22 00:04:00.000",
            2.000000000
        ],
        [
            "2020-12-22 00:05:00.000",
            2.000000000
        ],
       .......
```

目标: 需要按天（UTC+8对应的天）聚合求和值。
例如：需要聚合UTC+8 时区 12月22日的数据的和（即tdengine中ts从 2020-12-21 16:00:00至2020-12-23 15:59:59的数据和），需要怎么处理？ 

1. 使用`select sum(val) from fcloudqa.tb4697793857629192192 where ts > '2020-12-20 00:00:00.000' and ts < '2020-12-27 23:59:59.999' interval(1d, 8h)` 
查询结果
```
{
    "status": "succ",
    "head": [
        "ts",
        "sum(val)"
    ],
    "data": [
        [
            "2020-12-20 08:00:00.000",
            562.000000000
        ],
        [
            "2020-12-21 08:00:00.000",
            2836.000000000
        ]
    ],
    "rows": 2
}
```
结果并不包含12-22的数据

2. 使用`select sum(val) from fcloudqa.tb4697793857629192192 where ts > '2020-12-20 00:00:00.000' and ts < '2020-12-27 23:59:59.999' interval(1d)`
查询结果
```
{
    "status": "succ",
    "head": [
        "ts",
        "sum(val)"
    ],
    "data": [
        [
            "2020-12-21 00:00:00.000",
            2482.000000000
        ],
        [
            "2020-12-22 00:00:00.000",
            918.000000000
        ]
    ],
    "rows": 2
}
```
聚合的结果是UTC对应得每天的结果，不是想要的UTC+8对应天的结果

**Comment by Luokun2016** [comment]
@hjxilinx @xiaopingcs 求助，有没有解决方案啊

**Comment by Luokun2016** [comment]
[文档](https://github.com/taosdata/TDengine/blob/develop/documentation20/webdocs/markdowndocs/TAOS%20SQL-ch.md#%E6%97%B6%E9%97%B4%E7%BB%B4%E5%BA%A6%E8%81%9A%E5%90%88) 中提到：聚合时间段的长度由关键词INTERVAL指定，最短时间间隔10毫秒（10a），并且支持偏移（**偏移必须小于间隔**）.

**Comment by kartist** [comment]
``` sql 
SELECT function_list FROM stb_name
  [WHERE where_condition]
  INTERVAL (interval [, offset])
  [FILL ({ VALUE | PREV | NULL | LINEAR})]
  [GROUP BY tags]
```

有没有尝试过使用 FILL ? 
如 
```sql
select sum(val) from fcloudqa.tb4697793857629192192 where ts > '2020-12-20 00:00:00.000' and ts < '2020-12-27 23:59:59.999' interval(1d, 8h) fill(null)
```

**Comment by xiaopingcs** [comment]
你可以试试sliding
interavl(1d) sliding(8h)?

**Comment by Luokun2016** [comment]
> 你可以试试sliding
> interavl(1d) sliding(8h)?

使用 `sliding(8h)`后，时间间隔就不是 1天了

`select sum(val) from fcloudqa.tb4697793857629192192 where ts > '2020-12-20 00:00:00.000' and ts < '2020-12-27 23:59:59.999' interval(1d) sliding(8h)`

```
{
    "status": "succ",
    "head": [
        "ts",
        "sum(val)"
    ],
    "data": [
        [
            "2020-12-20 08:00:00.000",
            562.000000000
        ],
        [
            "2020-12-20 16:00:00.000",
            1522.000000000
        ],
        [
            "2020-12-21 00:00:00.000",
            2482.000000000
        ],
        [
            "2020-12-21 08:00:00.000",
            2880.000000000
        ],
        [
            "2020-12-21 16:00:00.000",
            2872.000000000
        ],
        [
            "2020-12-22 00:00:00.000",
            2872.000000000
        ],
        [
            "2020-12-22 08:00:00.000",
            2806.000000000
        ],
        [
            "2020-12-22 16:00:00.000",
            2806.000000000
        ],
        [
            "2020-12-23 00:00:00.000",
            2806.000000000
        ],
        [
            "2020-12-23 08:00:00.000",
            2132.000000000
        ],
        [
            "2020-12-23 16:00:00.000",
            1180.000000000
        ],
        [
            "2020-12-24 00:00:00.000",
            220.000000000
        ]
    ],
    "rows": 12
}
```

**Comment by Luokun2016** [comment]
> ```sql
> SELECT function_list FROM stb_name
>   [WHERE where_condition]
>   INTERVAL (interval [, offset])
>   [FILL ({ VALUE | PREV | NULL | LINEAR})]
>   [GROUP BY tags]
> ```
> 
> 有没有尝试过使用 FILL ?
> 如
> 
> ```sql
> select sum(val) from fcloudqa.tb4697793857629192192 where ts > '2020-12-20 00:00:00.000' and ts < '2020-12-27 23:59:59.999' interval(1d, 8h) fill(null)
> ```

使用`select sum(val) from fcloudqa.tb4697793857629192192 where ts > '2020-12-20 00:00:00.000' and ts < '2020-12-27 23:59:59.999' interval(1d ,8h) fill(null)`
可以查询到UTC+8 时区每天的数据总和。
但是 每5分钟的数据总和，没办法查。因为 [聚合时间段的长度由关键词INTERVAL指定，最短时间间隔10毫秒（10a），并且支持偏移（偏移必须小于间隔）.](https://github.com/taosdata/TDengine/issues/4654#issuecomment-751142258)
```
{
    "status": "succ",
    "head": [
        "ts",
        "sum(val)"
    ],
    "data": [
        [
            "2020-12-19 08:00:00.000",
            null
        ],
        [
            "2020-12-20 08:00:00.000",
            562.000000000
        ],
        [
            "2020-12-21 08:00:00.000",
            2880.000000000
        ],
        [
            "2020-12-22 08:00:00.000",
            2806.000000000
        ],
        [
            "2020-12-23 08:00:00.000",
            2132.000000000
        ],
        [
            "2020-12-24 08:00:00.000",
            null
        ],
        [
            "2020-12-25 08:00:00.000",
            null
        ],
        [
            "2020-12-26 08:00:00.000",
            null
        ],
        [
            "2020-12-27 08:00:00.000",
            null
        ]
    ],
    "rows": 9
}
```

**Comment by hjxilinx** [comment]
当前时间区间的生成是按照服务器所在的时区区间生成的查询窗口，如果您的服务器设置是 UTC+8(东八区？），那么可以按照您的要求生成结果。
TDengine 当前并不支持按照客户端指定的时区生成滑动（翻转）时间窗口。

**Comment by hjxilinx** [comment]
如果您使用了 offset 来让窗口滑动，那么您需要设置正确的起始和结束的时间（带指定时区的时间戳）.

`select sum(val) from fcloudqa.tb4697793857629192192 where ts > '2020-12-20T00:00:00+8:00' and ts < '2020-12-28 00:00:00+8:00' interval(1d, 8h)`;

**Comment by Luokun2016** [comment]
> interval(1d, 8h)

**Comment by Luokun2016** [comment]
> 如果您使用了 offset 来让窗口滑动，那么您需要设置正确的起始和结束的时间（带指定时区的时间戳）.
> 
> `select sum(val) from fcloudqa.tb4697793857629192192 where ts > '2020-12-20T00:00:00+8:00' and ts < '2020-12-28T00:00:00+8:00' interval(1d, 8h)`;

但是, 如果想要每5分钟聚合一次即`interval(5m, 8h)`就不行

**Comment by hjxilinx** [comment]
临时解决策略：修改服务器时区为指定时区就行。

彻底解决策略：TDengine 支持按照客户端指定时区生成时间窗口，后面我们会提供该功能。

**Comment by Luokun2016** [comment]
> 临时解决策略：修改服务器时区为指定时区就行。
> 彻底解决策略：TDengine 支持按照客户端指定时区生成时间窗口，后面我们会提供该功能。
> 另，东八区是 UTC-8。不是 UTC+8。

Tdengine支持时间窗口左移吗？
**tdengine中的时间戳为UTC时间**
例如使用
`select sum(val) from fcloudqa.tb4697793857629192192 where ts > '2020-12-20 00:00:00.000' and ts < '2020-12-27 23:59:59.999' interval(1d)`
查出的结果为：
```
{
    "status": "succ",
    "head": [
        "ts",
        "sum(val)"
    ],
    "data": [
        [
            "2020-12-21 00:00:00.000",
            2482.000000000
        ],
        [
            "2020-12-22 00:00:00.000",
            918.000000000
        ]
    ],
    "rows": 2
}
```
其中`2020-12-21 00:00:00.000`和`2020-12-22 00:00:00.000`为**UTC时间**，
现在需要聚合出**UTC+8**时区，每天的结果。
即需要查询结果中的时间点，**向左移8个小时**，例如
```
"data": [
        [
            "2020-12-20 16:00:00.000",
            xxx
        ],
        [
            "2020-12-21 16:00:00.000",
            xxx
        ]
```
那么才对应UTC+8时区的`2020-12-21 00:00:00.000`和`2020-12-22 00:00:00.000`

@hjxilinx

**Comment by Luokun2016** [comment]
使用taosdemo 的测试数据进行测试
```
taos> select avg(f1) from test.t1 where ts >= '2017-07-14 16:00:00:000' and ts < '2017-07-15 16:00:00:000' interval(24h);
           ts            |          avg(f1)          |
======================================================
 2017-07-14 08:00:00.000 |               4.500277778 |
 2017-07-15 08:00:00.000 |               4.479289686 |
Query OK, 2 row(s) in set (0.003563s)

taos> select avg(f1) from test.t1 where ts >= '2017-07-14 16:00:00:000' and ts < '2017-07-15 16:00:00:000' interval(24h) sliding(24h);
           ts            |          avg(f1)          |
======================================================
 2017-07-14 08:00:00.000 |               4.500277778 |
 2017-07-15 08:00:00.000 |               4.479289686 |
Query OK, 2 row(s) in set (0.003623s)
```

查询的结果时间点如何才能从`2017-07-14 16:00:00:000`开始，而不是` 2017-07-14 08:00:00.000`?

**Comment by yipingdeng** [comment]
业务应用场景：
取设备的日间数据（时间用户可以自由设置，例如：8:00到20:00）和夜间（根据日间时间推送夜间时间 20:00到第二天早晨8:00）数据做对比分析处理。

这种业务场景通过窗口可以怎么处理。主要offset和sliding要小于窗口宽度interval

**Comment by twinkleeyes** [comment]
> 使用taosdemo 的测试数据进行测试
> 
> ```
> taos> select avg(f1) from test.t1 where ts >= '2017-07-14 16:00:00:000' and ts < '2017-07-15 16:00:00:000' interval(24h);
>            ts            |          avg(f1)          |
> ======================================================
>  2017-07-14 08:00:00.000 |               4.500277778 |
>  2017-07-15 08:00:00.000 |               4.479289686 |
> Query OK, 2 row(s) in set (0.003563s)
> 
> taos> select avg(f1) from test.t1 where ts >= '2017-07-14 16:00:00:000' and ts < '2017-07-15 16:00:00:000' interval(24h) sliding(24h);
>            ts            |          avg(f1)          |
> ======================================================
>  2017-07-14 08:00:00.000 |               4.500277778 |
>  2017-07-15 08:00:00.000 |               4.479289686 |
> Query OK, 2 row(s) in set (0.003623s)
> ```
> 
> 查询的结果时间点如何才能从`2017-07-14 16:00:00:000`开始，而不是` 2017-07-14 08:00:00.000`?

请问这个问题最后是如何解决的呢
