### ISSUE TITLE
query questions

### ISSUE THREAD

**Issue by skyone123** [taosdata/TDengine#4673]
tdengine出现问题，查询表的内容，count，没有返回，其他的关于库，表标签查询很快，
![image](https://user-images.githubusercontent.com/42952917/102950126-e4752400-4504-11eb-8226-181627b555b8.png)
下面是taoslog最后内容
![image](https://user-images.githubusercontent.com/42952917/102950223-27cf9280-4505-11eb-8fba-1464c05e5477.png)

配置文件采用默认，配置

**Comment by skyone123** [comment]
之前是可以正常运行的，运行两天后就出现这样查询问题，想看下什么原因造成的

**Comment by sangshuduo** [comment]
请提供更多信息，TDengine 版本，单机部署还是集群部署， show stables 结果，show vgroups 结果，show dnodes 结果，show mnodes 结果

**Comment by skyone123** [comment]
> 请提供更多信息，TDengine版本，单机部署或扩展部署，显示稳定结果，显示vgroups结果，显示dnodes结果，显示mnodes结果

您好，tdengine版本:2.0.9.0    是单机部署版本
![image](https://user-images.githubusercontent.com/42952917/102954639-ed6af300-450e-11eb-8719-4054331d4992.png)
鉴于刚才重启tdengine，然后查询正常了，

**Comment by sangshuduo** [comment]
建议升级到最新版本，有类似问题再更新到这里

**Comment by skyone123** [comment]
> 建议升级到最新版本，有类似问题再更新到这里

嗯嗯，好的，后面有问题会再更新，谢谢您
