### ISSUE TITLE
compile step by step by README but got error: cannot find -lThreads::Threads

### ISSUE THREAD

**Issue by goodpaperman** [taosdata/TDengine#4674]
**Bug Description**
clone and compile on linux, but got error

**To Reproduce**
1. git clone https://github.com/taosdata/TDengine.git && cd TDengine
2. git submodule update --init --recursive
3. mkdir debug && cd debug && cmake .. && cmake --build .
4. see error

**Expected Behavior**
can pass compile

**Screenshots**

**Environment (please complete the following information):**
 - OS: NeoKylin (Linux localhost.localdomain 3.10.0-862.9.1.nd7.zx.18.x86_64 #1 SMP Tue Nov 12 09:16:38 CST 2019 x86_64 x86_64 x86_64 GNU/Linux)
 - Memory: 8G, CPU 4 core, current Disk Space: 40 G 
 - TDengine Version: 2.0.9.0

**Additional Context**
gmake[2]: Entering directory '/home/vmware/code/TDengine/debug'
/usr/bin/cmake -E cmake_progress_report /home/vmware/code/TDengine/debug/CMakeFiles 
[  9%] Building C object deps/MQTT-C/CMakeFiles/reconnect_subscriber.dir/examples/reconnect_subscriber.c.o
cd /home/vmware/code/TDengine/debug/deps/MQTT-C && /usr/bin/cc  -DLINUX -DUSE_LIBICONV -D_LIBC_REENTRANT -D_LINUX -D_MQTT -D_M_X64 -D_REENTRANT -D_TD_LINUX -D_TD_LINUX_64 -D__USE_POSIX -g -std=gnu99 -Wall -Werror -fPIC -g3 -gdwarf-2 -msse4.2 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILE -O0 -DDEBUG -I/home/vmware/code/TDengine/deps/cJson/inc -I/home/vmware/code/TDengine/deps/lz4/inc -I/home/vmware/code/TDengine/src/inc -I/home/vmware/code/TDengine/src/os/inc -I/home/vmware/code/TDengine/src/util/inc -I/home/vmware/code/TDengine/src/common/inc -I/home/vmware/code/TDengine/deps/MQTT-C/include    -o CMakeFiles/reconnect_subscriber.dir/examples/reconnect_subscriber.c.o   -c /home/vmware/code/TDengine/deps/MQTT-C/examples/reconnect_subscriber.c
Linking C executable ../../build/bin/reconnect_subscriber
cd /home/vmware/code/TDengine/debug/deps/MQTT-C && /usr/bin/cmake -E cmake_link_script CMakeFiles/reconnect_subscriber.dir/link.txt --verbose=1
/usr/bin/cc  -g -std=gnu99 -Wall -Werror -fPIC -g3 -gdwarf-2 -msse4.2 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILE -O0 -DDEBUG    CMakeFiles/reconnect_subscriber.dir/examples/reconnect_subscriber.c.o  -o ../../build/bin/reconnect_subscriber -rdynamic -lThreads::Threads ../../build/lib/libmqttc.a 
/usr/bin/ld: cannot find -lThreads::Threads
collect2: 错误：ld 返回 1
deps/MQTT-C/CMakeFiles/reconnect_subscriber.dir/build.make:89: recipe for target 'build/bin/reconnect_subscriber' failed
gmake[2]: *** [build/bin/reconnect_subscriber] Error 1
gmake[2]: Leaving directory '/home/vmware/code/TDengine/debug'
CMakeFiles/Makefile2:383: recipe for target 'deps/MQTT-C/CMakeFiles/reconnect_subscriber.dir/all' failed
gmake[1]: *** [deps/MQTT-C/CMakeFiles/reconnect_subscriber.dir/all] Error 2
gmake[1]: Leaving directory '/home/vmware/code/TDengine/debug'
Makefile:140: recipe for target 'all' failed
gmake: *** [all] Error 2

**Comment by sangshuduo** [comment]
gcc 和 cmake 的版本是多少？

**Comment by goodpaperman** [comment]
> 
> 
> gcc 和 cmake 的版本是多少？

$gcc --version
gcc (GCC) 4.9.2 20141101 (NeoKylin 4.9.2-1)
Copyright © 2014 Free Software Foundation, Inc.
本程序是自由软件；请参看源代码的版权声明。本软件没有任何担保；
包括没有适销性和某一专用目的下的适用性担保。

$ cmake --version
cmake version 3.0.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by sangshuduo** [comment]
猜测是 cmake 版本过低导致的，我没有这个环境不好复现，你升级 cmake 到一个比较新的版本试试

**Comment by goodpaperman** [comment]
> 
> 
> 猜测是 cmake 版本过低导致的，我没有这个环境不好复现，你升级 cmake 到一个比较新的版本试试

修改了一下  CMakeLists.txt 的内容后上面的问题绕过了：
$ cat CMakeLists.txt 
CMAKE_MINIMUM_REQUIRED(VERSION 2.8)
IF (CMAKE_VERSION VERSION_LESS 3.0)
  PROJECT(TDengine CXX)
  SET(PROJECT_VERSION_MAJOR "${LIB_MAJOR_VERSION}")
  SET(PROJECT_VERSION_MINOR "${LIB_MINOR_VERSION}")
  SET(PROJECT_VERSION_PATCH"${LIB_PATCH_VERSION}")
  SET(PROJECT_VERSION "${LIB_VERSION_STRING}")
ELSE ()
  CMAKE_POLICY(SET CMP0048 NEW)
  PROJECT(TDengine VERSION "${LIB_VERSION_STRING}" LANGUAGES CXX)
ENDIF ()

SET(TD_ACCOUNT FALSE)
SET(TD_ADMIN FALSE)
SET(TD_GRANT FALSE)
**SET(TD_MQTT FALSE)**
SET(TD_TSDB_PLUGINS FALSE)

SET(TD_COVER FALSE)
SET(TD_MEM_CHECK FALSE)

SET(TD_PAGMODE_LITE FALSE)
SET(TD_SOMODE_STATIC FALSE)
SET(TD_POWER FALSE)
SET(TD_GODLL FALSE)

SET(TD_COMMUNITY_DIR ${PROJECT_SOURCE_DIR})
MESSAGE(STATUS "Community directory: " ${TD_COMMUNITY_DIR})

INCLUDE(cmake/input.inc)
INCLUDE(cmake/platform.inc)
INCLUDE(cmake/define.inc)
INCLUDE(cmake/env.inc)
INCLUDE(cmake/version.inc)
INCLUDE(cmake/install.inc)

ADD_SUBDIRECTORY(deps)
ADD_SUBDIRECTORY(src)
ADD_SUBDIRECTORY(tests)

INCLUDE(CPack)

将 TD_MQTT 设置为 FALSE 可绕过该问题。不过为什么 CMakeLists.txt 里指定的 cmake 最低版本为 2.8，而我 3.0.2 的版本就出问题了呢？

**Comment by sangshuduo** [comment]
Building

At the moment, TDengine only supports building and running on Linux systems. You can choose to install from packages or from the source code. This quick guide is for installation from the source only.

To build TDengine, use CMake 3.5 or higher versions in the project directory.

====
文档里要求是 CMake 3.5 以上，代码可能没有及时同步

**Comment by goodpaperman** [comment]
> 
> 
> Building
> 
> At the moment, TDengine only supports building and running on Linux systems. You can choose to install from packages or from the source code. This quick guide is for installation from the source only.
> 
> To build TDengine, use CMake 3.5 or higher versions in the project directory.
> 
> ====
> 文档里要求是 CMake 3.5 以上，代码可能没有及时同步


更新到 3.5.2 版本编译没问题了
$ cmake --version
cmake version 3.5.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
