### ISSUE TITLE
Restful API multithreading requests batch SQL import, resulting in node hang up

### ISSUE THREAD

**Issue by yaohang** [taosdata/TDengine#4675]
开了十个线程请求 Restful API 接口导入数据，每次请求拼接1000条数据，样例如下：

import INTO  trace.trace_430100  USING trace.user_trace TAGS ("长沙","430100") VALUES ("2020-06-12 00:20:17.156522","c5848e554496c3b00e8d4c5848e55449",8,430100,"长沙","中国-湖南省-长沙市-天心区-xxxxxx","FW","192.168.1.102","社保查询","SBCX2",67963.11,"2020-06-12 00:20:17.156522","2020-06-12 00:21:25","null", "null", "null", "null", "null", "2") ("2020-06-12 12:23:11.632441","c5848e554496c3b00e8d4c5848e55449",8,430100,"长沙","中国-湖南省-长沙市-天心区-xxxxxx","FW","192.168.1.102","社保查询","SBCX2",39557.844,"2020-06-12 12:23:11.632441","2020-06-12 12:23:51","null", "null", "null", "null", "null", "2")  trace.trace_510100  USING trace.user_trace TAGS ("成都市","510100") VALUES ("2020-06-18 06:39:06.149139","81acfb3e84657b1c9c94c0863422bc5c",2,510100,"成都市","China-Sichuan-Chengdu-Chenghua-xxxxxx","FW","192.168.3.28","社保服务","SBFW",398059.75,"2020-06-18 06:39:06.149139","2020-06-18 06:45:44","f64684381383116022bba7c5848e55449", "null", "null", "null", "null", "null") 

目前 TDengine 的环境是三台机器组成的集群，请求了其中一台机器导入数据，程序启动后，该节点瞬间被击跪了。通过其他节点查看信息：

![WX20201223-112727](https://user-images.githubusercontent.com/6006527/102955895-dd084780-4511-11eb-855b-332750ae5fd4.png)

环境信息：4核，16G 100G 硬盘，centos 7.6 TDengine 2.0.11

通过查看日志发现是 SQL 长度超出最大限制导致节点挂了。
==================================================
                new log file                      
==================================================
12/23 11:17:03.573145 0x7f020f323740 DND start to initialize TDengine
12/23 11:17:03.573217 0x7f020f323740 DND step:dnode-tfile is initialized
12/23 11:17:03.573237 0x7f020f323740 DND step:dnode-rpc is initialized
12/23 11:17:03.573247 0x7f020f323740 UTL localEp is: 0012-0004.novalocal:6030
12/23 11:17:03.573683 0x7f020f323740 UTL WARN timezone not configured, set to system default: (CST, +0800)
12/23 11:17:03.573792 0x7f020f323740 UTL WARN locale not configured, set to system default:en_US.UTF-8
12/23 11:17:03.573812 0x7f020f323740 UTL WARN charset not configured, set to system default:UTF-8
12/23 11:17:03.573869 0x7f020f323740 UTL    taos config & system info:
12/23 11:17:03.573878 0x7f020f323740 UTL ==================================
12/23 11:17:03.573884 0x7f020f323740 UTL  firstEp:                0027.novalocal:6030 
12/23 11:17:03.573889 0x7f020f323740 UTL  secondEp:               0012-0004.novalocal:6030 
12/23 11:17:03.573894 0x7f020f323740 UTL  fqdn:                   0012-0004.novalocal 
12/23 11:17:03.573901 0x7f020f323740 UTL  serverPort:             6030 
12/23 11:17:03.573909 0x7f020f323740 UTL  configDir:              /etc/taos 
12/23 11:17:03.573914 0x7f020f323740 UTL  logDir:                 /var/log/taos 
12/23 11:17:03.573923 0x7f020f323740 UTL  scriptDir:              /etc/taos 
12/23 11:17:03.573928 0x7f020f323740 UTL  dataDir:                /var/lib/taos 
12/23 11:17:03.573936 0x7f020f323740 UTL  arbitrator:              
12/23 11:17:03.573941 0x7f020f323740 UTL  numOfThreadsPerCore:    1.000000 
12/23 11:17:03.573964 0x7f020f323740 UTL  numOfCommitThreads:     1 
12/23 11:17:03.573969 0x7f020f323740 UTL  ratioOfQueryCores:      1.000000 
12/23 11:17:03.573978 0x7f020f323740 UTL  numOfMnodes:            3 
12/23 11:17:03.573983 0x7f020f323740 UTL  vnodeBak:               1 
12/23 11:17:03.573992 0x7f020f323740 UTL  telemetryReporting:     1 
12/23 11:17:03.573997 0x7f020f323740 UTL  balance:                1 
12/23 11:17:03.574001 0x7f020f323740 UTL  balanceInterval:        300 
12/23 11:17:03.574005 0x7f020f323740 UTL  role:                   0 
12/23 11:17:03.574014 0x7f020f323740 UTL  maxTmrCtrl:             512 
12/23 11:17:03.574019 0x7f020f323740 UTL  monitorInterval:        30(s)
12/23 11:17:03.574027 0x7f020f323740 UTL  offlineThreshold:       8640000(s)
12/23 11:17:03.574033 0x7f020f323740 UTL  rpcTimer:               1000(ms)
12/23 11:17:03.574041 0x7f020f323740 UTL  rpcMaxTime:             600(s)
12/23 11:17:03.574047 0x7f020f323740 UTL  statusInterval:         1(s)
12/23 11:17:03.574055 0x7f020f323740 UTL  shellActivityTimer:     3(s)
12/23 11:17:03.574060 0x7f020f323740 UTL  tableMetaKeepTimer:     7200(s)
12/23 11:17:03.574068 0x7f020f323740 UTL  minSlidingTime:         10(ms)
12/23 11:17:03.574073 0x7f020f323740 UTL  minIntervalTime:        10(ms)
12/23 11:17:03.574082 0x7f020f323740 UTL  maxStreamCompDelay:     20000(ms)
12/23 11:17:03.574087 0x7f020f323740 UTL  maxFirstStreamCompDelay:10000(ms)
12/23 11:17:03.574095 0x7f020f323740 UTL  retryStreamCompDelay:   10(ms)
12/23 11:17:03.574101 0x7f020f323740 UTL  streamCompDelayRatio:   0.100000 
12/23 11:17:03.574111 0x7f020f323740 UTL  maxVgroupsPerDb:        0 
12/23 11:17:03.574116 0x7f020f323740 UTL  maxTablesPerVnode:      1000000 
12/23 11:17:03.574124 0x7f020f323740 UTL  minTablesPerVnode:      1000 
12/23 11:17:03.574129 0x7f020f323740 UTL  tableIncStepPerVnode:   1000 
12/23 11:17:03.574137 0x7f020f323740 UTL  cache:                  16(Mb)
12/23 11:17:03.574143 0x7f020f323740 UTL  blocks:                 6 
12/23 11:17:03.574151 0x7f020f323740 UTL  days:                   10 
12/23 11:17:03.574157 0x7f020f323740 UTL  keep:                   3650 
12/23 11:17:03.574165 0x7f020f323740 UTL  minRows:                100 
12/23 11:17:03.574170 0x7f020f323740 UTL  maxRows:                4096 
12/23 11:17:03.574179 0x7f020f323740 UTL  comp:                   2 
12/23 11:17:03.574184 0x7f020f323740 UTL  walLevel:               1 
12/23 11:17:03.574192 0x7f020f323740 UTL  fsync:                  3000 
12/23 11:17:03.574198 0x7f020f323740 UTL  replica:                1 
12/23 11:17:03.574210 0x7f020f323740 UTL  quorum:                 1 
12/23 11:17:03.574215 0x7f020f323740 UTL  update:                 0 
12/23 11:17:03.574224 0x7f020f323740 UTL  compressMsgSize:        -1 
12/23 11:17:03.574229 0x7f020f323740 UTL  maxSQLLength:           65480(byte)
12/23 11:17:03.574237 0x7f020f323740 UTL  maxNumOfOrderedRes:     100000 
12/23 11:17:03.574248 0x7f020f323740 UTL  queryBufferSize:        -1(byte)
12/23 11:17:03.574256 0x7f020f323740 UTL  retrieveBlockingModel:  0 
12/23 11:17:03.574262 0x7f020f323740 UTL  keepColumnName:         0 
12/23 11:17:03.574270 0x7f020f323740 UTL  timezone:                (CST, +0800) 
12/23 11:17:03.574276 0x7f020f323740 UTL  locale:                 en_US.UTF-8 
12/23 11:17:03.574293 0x7f020f323740 UTL  charset:                UTF-8 
12/23 11:17:03.574298 0x7f020f323740 UTL  maxShellConns:          5000 
12/23 11:17:03.574307 0x7f020f323740 UTL  maxConnections:         5000 
12/23 11:17:03.574312 0x7f020f323740 UTL  minimalLogDirGB:        0.100000(GB)
12/23 11:17:03.574321 0x7f020f323740 UTL  minimalTmpDirGB:        0.100000(GB)
12/23 11:17:03.574326 0x7f020f323740 UTL  minimalDataDirGB:       0.500000(GB)
12/23 11:17:03.574335 0x7f020f323740 UTL  mnodeEqualVnodeNum:     4 
12/23 11:17:03.574340 0x7f020f323740 UTL  flowctrl:               1 
12/23 11:17:03.574348 0x7f020f323740 UTL  http:                   1 
12/23 11:17:03.574353 0x7f020f323740 UTL  mqtt:                   0 
12/23 11:17:03.574362 0x7f020f323740 UTL  monitor:                1 
12/23 11:17:03.574367 0x7f020f323740 UTL  stream:                 1 
12/23 11:17:03.574375 0x7f020f323740 UTL  httpEnableRecordSql:    0 
12/23 11:17:03.574380 0x7f020f323740 UTL  telegrafUseFieldNum:    0 
12/23 11:17:03.574388 0x7f020f323740 UTL  httpMaxThreads:         2 
12/23 11:17:03.574393 0x7f020f323740 UTL  restfulRowLimit:        10240 
12/23 11:17:03.574402 0x7f020f323740 UTL  numOfLogLines:          10000000 
12/23 11:17:03.574407 0x7f020f323740 UTL  logKeepDays:            0 
12/23 11:17:03.574411 0x7f020f323740 UTL  asyncLog:               1 
12/23 11:17:03.574420 0x7f020f323740 UTL  debugFlag:              0 
12/23 11:17:03.574425 0x7f020f323740 UTL  mDebugFlag:             131 
12/23 11:17:03.574433 0x7f020f323740 UTL  dDebugFlag:             135 
12/23 11:17:03.574438 0x7f020f323740 UTL  sDebugFlag:             135 
12/23 11:17:03.574447 0x7f020f323740 UTL  wDebugFlag:             135 
12/23 11:17:03.574452 0x7f020f323740 UTL  sdbDebugFlag:           131 
12/23 11:17:03.574460 0x7f020f323740 UTL  rpcDebugFlag:           135 
12/23 11:17:03.574465 0x7f020f323740 UTL  tmrDebugFlag:           131 
12/23 11:17:03.574473 0x7f020f323740 UTL  cDebugFlag:             135 
12/23 11:17:03.574479 0x7f020f323740 UTL  jniDebugFlag:           131 
12/23 11:17:03.574487 0x7f020f323740 UTL  odbcDebugFlag:          131 
12/23 11:17:03.574492 0x7f020f323740 UTL  uDebugFlag:             131 
12/23 11:17:03.574501 0x7f020f323740 UTL  httpDebugFlag:          131 
12/23 11:17:03.574506 0x7f020f323740 UTL  mqttDebugFlag:          131 
12/23 11:17:03.574514 0x7f020f323740 UTL  monDebugFlag:           131 
12/23 11:17:03.574519 0x7f020f323740 UTL  qDebugFlag:             131 
12/23 11:17:03.574527 0x7f020f323740 UTL  vDebugFlag:             135 
12/23 11:17:03.574532 0x7f020f323740 UTL  tsdbDebugFlag:          131 
12/23 11:17:03.574540 0x7f020f323740 UTL  cqDebugFlag:            131 
12/23 11:17:03.574546 0x7f020f323740 UTL  enableRecordSql:        0 
12/23 11:17:03.574554 0x7f020f323740 UTL  enableCoreFile:         0 
12/23 11:17:03.574559 0x7f020f323740 UTL  gitinfo:                950dd612f23fe71e5f51ff6262fb900b20245ce1 
12/23 11:17:03.574567 0x7f020f323740 UTL  gitinfoOfInternal:      NULL 
12/23 11:17:03.574573 0x7f020f323740 UTL  buildinfo:              Built at 2020-12-20 21:37 
12/23 11:17:03.574582 0x7f020f323740 UTL  version:                2.0.11.0 
12/23 11:17:03.574587 0x7f020f323740 UTL  maxBinaryDisplayWidth:  30 
12/23 11:17:03.574595 0x7f020f323740 UTL  tempDir:                /tmp/ 
12/23 11:17:03.574614 0x7f020f323740 UTL  os pageSize:            4096(KB)
12/23 11:17:03.574619 0x7f020f323740 UTL  os openMax:             65536
12/23 11:17:03.574624 0x7f020f323740 UTL  os streamMax:           16
12/23 11:17:03.574632 0x7f020f323740 UTL  os numOfCores:          4
12/23 11:17:03.574637 0x7f020f323740 UTL  os totalDisk:           35.100040(GB)
12/23 11:17:03.574647 0x7f020f323740 UTL  os totalMemory:         16045(MB)
12/23 11:17:03.574660 0x7f020f323740 UTL  os sysname:             Linux
12/23 11:17:03.574669 0x7f020f323740 UTL  os nodename:            0012-0004.novalocal
12/23 11:17:03.574674 0x7f020f323740 UTL  os release:             3.10.0-957.el7.x86_64
12/23 11:17:03.574682 0x7f020f323740 UTL  os version:             #1 SMP Thu Nov 8 23:39:32 UTC 2018
12/23 11:17:03.574687 0x7f020f323740 UTL  os machine:             x86_64
12/23 11:17:03.574695 0x7f020f323740 UTL ==================================
12/23 11:17:03.574701 0x7f020f323740 DND step:dnode-globalcfg is initialized
12/23 11:17:03.574740 0x7f020f323740 DND dnode storage is initialized at /var/lib/taos/dnode
12/23 11:17:03.574749 0x7f020f323740 DND step:dnode-storage is initialized
12/23 11:17:03.574834 0x7f020f323740 DND read file /var/lib/taos/dnode/dnodeCfg.json successed
12/23 11:17:03.574879 0x7f020f323740 DND dnodeId is set to 3, clusterId is set to a169647f-8b88-4017-bf74-0344cc58e65a
12/23 11:17:03.575047 0x7f020f323740 DND successed to write /var/lib/taos/dnode/dnodeCfg.json
12/23 11:17:03.575061 0x7f020f323740 DND dnode cfg is initialized
12/23 11:17:03.575065 0x7f020f323740 DND step:dnode-cfg is initialized
12/23 11:17:03.575140 0x7f020f323740 DND read file /var/lib/taos/dnode/dnodeEps.json successed
12/23 11:17:03.575150 0x7f020f323740 DND print dnodeEp, dnodeNum:3
12/23 11:17:03.575152 0x7f020f323740 DND dnode:1, dnodeFqdn:0027.novalocal dnodePort:6030
12/23 11:17:03.575154 0x7f020f323740 DND dnode:2, dnodeFqdn:0026.novalocal dnodePort:6030
12/23 11:17:03.575156 0x7f020f323740 DND dnode:3, dnodeFqdn:0012-0004.novalocal dnodePort:6030
12/23 11:17:03.575167 0x7f020f323740 DND print dnodeEp, dnodeNum:3
12/23 11:17:03.575172 0x7f020f323740 DND dnode:1, dnodeFqdn:0027.novalocal dnodePort:6030
12/23 11:17:03.575175 0x7f020f323740 DND dnode:2, dnodeFqdn:0026.novalocal dnodePort:6030
12/23 11:17:03.575177 0x7f020f323740 DND dnode:3, dnodeFqdn:0012-0004.novalocal dnodePort:6030
12/23 11:17:03.575198 0x7f020f323740 DND dnode eps is initialized
12/23 11:17:03.575206 0x7f020f323740 DND step:dnode-eps is initialized
12/23 11:17:03.575248 0x7f020f323740 DND read file /var/lib/taos/dnode/mnodeEpSet.json successed
12/23 11:17:03.575257 0x7f020f323740 DND print minfos, mnodeNum:3 inUse:0
12/23 11:17:03.575263 0x7f020f323740 DND mnode index:1, 0027.novalocal:6030
12/23 11:17:03.575271 0x7f020f323740 DND mnode index:2, 0026.novalocal:6030
12/23 11:17:03.575276 0x7f020f323740 DND mnode index:3, 0012-0004.novalocal:6030
12/23 11:17:03.575309 0x7f020f323740 DND print minfos, mnodeNum:3 inUse:0
12/23 11:17:03.575319 0x7f020f323740 DND mnode index:1, 0027.novalocal:6030
12/23 11:17:03.575324 0x7f020f323740 DND mnode index:2, 0026.novalocal:6030
12/23 11:17:03.575329 0x7f020f323740 DND mnode index:3, 0012-0004.novalocal:6030
12/23 11:17:03.575338 0x7f020f323740 DND dnode minfos is initialized
12/23 11:17:03.575343 0x7f020f323740 DND step:dnode-minfos is initialized
12/23 11:17:03.575397 0x7f020f323740 WAL wal thread is launched
12/23 11:17:03.575406 0x7f020f323740 WAL wal module is initialized, refId:3
12/23 11:17:03.575411 0x7f020f323740 DND step:dnode-wal is initialized
12/23 11:17:03.575506 0x7f020f323740 SYN 0x1dd2f90 TCP pool is created
12/23 11:17:03.575521 0x7f020f323740 SYN sync module initialized successfully
12/23 11:17:03.575527 0x7f020f323740 DND step:dnode-sync is initialized
12/23 11:17:03.575605 0x7f020f323740 DND dnode check is initialized
12/23 11:17:03.575616 0x7f020f323740 DND step:dnode-check is initialized
12/23 11:17:03.575625 0x7f020f323740 UTL worker:vquery is initialized, min:4 max:4
12/23 11:17:03.575637 0x7f020f323740 UTL worker:vfetch is initialized, min:4 max:4
12/23 11:17:03.575645 0x7f020f323740 DND step:dnode-vread is initialized
12/23 11:17:03.575654 0x7f020f323740 DND dnode vwrite is initialized, max worker 4
12/23 11:17:03.575659 0x7f020f323740 DND step:dnode-vwrite is initialized
12/23 11:17:03.575676 0x7f020f323740 VND vmworker:0 is created
12/23 11:17:03.575684 0x7f020f323740 VND vmworker is initialized, num:1 qset:0x1dd47f0
12/23 11:17:03.575716 0x7f020f323740 VND vmworker:0 is launched, total:1
12/23 11:17:03.575722 0x7f020f323740 VND vmworker queue:0x1dd4860 is allocated
12/23 11:17:03.575725 0x7f020f323740 DND step:vnode-worker is initialized
12/23 11:17:03.575730 0x7f020f323740 DND step:vnode-write is initialized
12/23 11:17:03.575736 0x7f020f323740 DND step:vnode-read is initialized
12/23 11:17:03.575746 0x7f020f323740 DND step:vnode-hash is initialized
12/23 11:17:03.575802 0x7f020f323740 DND step:tsdb-queue is initialized
12/23 11:17:03.575815 0x7f020f323740 UTL worker:vmgmt is initialized, min:1 max:1
12/23 11:17:03.575845 0x7f020f323740 DND dnode vmgmt is initialized
12/23 11:17:03.575854 0x7f020f323740 DND step:dnode-vmgmt is initialized
12/23 11:17:03.575864 0x7f020f323740 DND dnode mread worker:0 is created
12/23 11:17:03.575870 0x7f020f323740 DND dnode mread worker:1 is created
12/23 11:17:03.575872 0x7f020f323740 DND dnode mread is initialized, workers:2 qset:0x1dd5730
12/23 11:17:03.575875 0x7f020f323740 DND step:dnode-mread is initialized
12/23 11:17:03.575880 0x7f020f323740 DND dnode mwrite worker:0 is created
12/23 11:17:03.575886 0x7f020f323740 DND dnode mwrite is initialized, workers:1 qset:0x1dd57d0
12/23 11:17:03.575888 0x7f020f323740 DND step:dnode-mwrite is initialized
12/23 11:17:03.575893 0x7f020f323740 DND dnode mpeer worker:0 is created
12/23 11:17:03.575899 0x7f020f323740 DND dnode mpeer is initialized, workers:1 qset:0x1dd5860
12/23 11:17:03.575902 0x7f020f323740 DND step:dnode-mpeer is initialized
12/23 11:17:03.576313 0x7f020f323740 RPC DND-C TCP client is initialized, ip:0:0
12/23 11:17:03.576375 0x7f020f323740 RPC DND-C UDP connection is initialized, ip:0:0 threads:1
12/23 11:17:03.576382 0x7f020f323740 RPC DND-C rpc is opened, threads:1 sessions:2048
12/23 11:17:03.576387 0x7f020f323740 DND dnode inter-dnodes rpc client is initialized
12/23 11:17:03.576392 0x7f020f323740 DND step:dnode-client is initialized
12/23 11:17:03.576412 0x7f01ff2d0700 RPC DND-C UDP thread is created, index:0
12/23 11:17:03.576587 0x7f020f323740 RPC DND-S TCP server is initialized, ip:0x0 port:6035 numOfThreads:1
12/23 11:17:03.576612 0x7f01fe2ce700 RPC DND-S TCP server is ready, ip:0x0:6035
12/23 11:17:03.576663 0x7f020f323740 RPC DND-S UDP connection is initialized, ip:0:6035 threads:1
12/23 11:17:03.576669 0x7f020f323740 RPC DND-S rpc is opened, threads:1 sessions:2048
12/23 11:17:03.576672 0x7f020f323740 DND dnode inter-dnodes RPC server is initialized
12/23 11:17:03.576680 0x7f01fdacd700 RPC DND-S UDP thread is created, index:0
12/23 11:17:03.576685 0x7f020f323740 DND step:dnode-server is initialized
12/23 11:17:03.576745 0x7f020f323740 DND start 4 threads to open 1 vnodes
12/23 11:17:03.576811 0x7f01fd2cc700 DND thread:0, start to open 1 vnodes
12/23 11:17:03.576947 0x7f01fd2cc700 VND vgId:3, load vnode cfg successfully, replcia:1
12/23 11:17:03.576963 0x7f01fd2cc700 VND vgId:3, dnode:3, 0012-0004.novalocal:6040
12/23 11:17:03.577022 0x7f01fd2cc700 DND dnode vwrite worker:0 is launched
12/23 11:17:03.577026 0x7f01fd2cc700 DND pVnode:0x7f01f80008c0, dnode vwrite queue:0x7f01f8001320 is allocated
12/23 11:17:03.577045 0x7f01fcacb700 DND dnode vwrite worker:0 is running
12/23 11:17:03.578125 0x7f01fd2cc700 WAL vgId:3, object is initialized
12/23 11:17:03.578142 0x7f01fd2cc700 WAL vgId:3, wal:0x7f01f8031670 is opened, level:1 fsyncPeriod:3000
12/23 11:17:03.578167 0x7f01fd2cc700 WAL vgId:3, file:/var/lib/taos/vnode/vnode3/wal/wal1, will be restored
12/23 11:17:03.578252 0x7f01fd2cc700 WAL vgId:3, file:/var/lib/taos/vnode/vnode3/wal/wal1, restore success, wver:0
12/23 11:17:03.578340 0x7f01fd2cc700 WAL vgId:3, wal:0x7f01f8031670 file:/var/lib/taos/vnode/vnode3/wal/wal1, it is removed
12/23 11:17:03.578386 0x7f01fd2cc700 WAL vgId:3, file:/var/lib/taos/vnode/vnode3/wal/wal1, it is created
12/23 11:17:03.578471 0x7f01fd2cc700 VND vgId:3, vnode is opened in /var/lib/taos/vnode/vnode3, pVnode:0x7f01f80008c0
12/23 11:17:03.581656 0x7f01fd2cc700 SYN vgId:3, nodeId:3, it is configured, ep:0012-0004.novalocal:6040
12/23 11:17:03.581676 0x7f01fd2cc700 SYN vgId:3, 1 replicas are configured, quorum:1 role:master
12/23 11:17:03.581703 0x7f01fd2cc700 VND vgId:3, sync role changed from offline to master
12/23 11:17:03.581723 0x7f01fd2cc700 DND vgId:3, is opened by thread:0
12/23 11:17:03.581728 0x7f01fd2cc700 DND thread:0, total vnodes:1, opened:1 failed:0
12/23 11:17:03.581800 0x7f020f323740 DND there are total vnodes:1, opened:1
12/23 11:17:03.581824 0x7f020f323740 DND step:dnode-vnodes is initialized
12/23 11:17:03.581920 0x7f020f323740 DND dnode modules is initialized
12/23 11:17:03.581932 0x7f020f323740 HTP start http server ...
12/23 11:17:03.581999 0x7f020f323740 HTP http result queue is opened
12/23 11:17:03.582412 0x7f01eaccd700 HTP http server init success at 6041
12/23 11:17:03.582869 0x7f020f323740 TSC client is initialized successfully
12/23 11:17:03.582881 0x7f020f323740 MON monitor module start
12/23 11:17:03.582893 0x7f020f323740 DND step:dnode-modules is initialized
12/23 11:17:03.583153 0x7f020f323740 RPC SHELL TCP server is initialized, ip:0x0 port:6030 numOfThreads:2
12/23 11:17:03.583165 0x7f01e7afb700 RPC SHELL TCP server is ready, ip:0x0:6030
12/23 11:17:03.583215 0x7f01e72fa700 RPC SHELL UDP thread is created, index:0
12/23 11:17:03.583259 0x7f020f323740 RPC SHELL UDP connection is initialized, ip:0:6030 threads:2
12/23 11:17:03.583266 0x7f020f323740 RPC SHELL rpc is opened, threads:2 sessions:5000
12/23 11:17:03.583269 0x7f020f323740 DND dnode shell rpc server is initialized
12/23 11:17:03.583269 0x7f01e6af9700 RPC SHELL UDP thread is created, index:1
12/23 11:17:03.583276 0x7f020f323740 DND step:dnode-shell is initialized
12/23 11:17:03.583294 0x7f020f323740 DND dnode status timer is initialized
12/23 11:17:03.583304 0x7f020f323740 DND step:dnode-statustmr is initialized
12/23 11:17:03.583340 0x7f020f323740 DND dnode telemetry is initialized
12/23 11:17:03.583349 0x7f020f323740 DND step:dnode-telemetry is initialized
12/23 11:17:03.583355 0x7f020f323740 DND TDengine is initialized successfully
12/23 11:17:04.088324 0x7f020e236700 RPC DND-C 0x7f020f183188 client connection is allocated, uid:0xf18cf4d
12/23 11:17:04.088346 0x7f020e236700 RPC DND-C UDP connection is setup, ip:9ade16ac:6035 localPort:10543
12/23 11:17:04.088352 0x7f020e236700 RPC DND-C 0x7f020f183188 (nil), status is sent to 0027.novalocal:6035, len:682 sig:0x01000000:0x00000000:29548
12/23 11:17:04.089051 0x7f01ff2d0700 RPC DND-C 0x7f020f183188 (nil), status-rsp received from 0x9ade16ac:6035, parse code:0x0 len:1235 sig:0x09000000:0x01000000:29548 code:0x0
12/23 11:17:04.346610 0x7f01ebccf700 RPC TSC TCP client is initialized, ip:0:0
12/23 11:17:04.346673 0x7f01ebccf700 RPC TSC UDP connection is initialized, ip:0:0 threads:1
12/23 11:17:04.346679 0x7f01ebccf700 RPC TSC rpc is opened, threads:1 sessions:5000
12/23 11:17:04.346682 0x7f01ebccf700 TSC dnodeConn:0x7f01dc07fe50 is created, user:root
12/23 11:17:04.346706 0x7f01e512a700 RPC TSC UDP thread is created, index:0
12/23 11:17:04.346722 0x7f01ebccf700 TSC 0x7f01dc17c330 add to tscObj:0x7f01dc17bfa0, ref:2
12/23 11:17:04.346757 0x7f01ebccf700 TSC 0x7f01dc17c330 SQL cmd:connect will be processed, name:(null), type:0
12/23 11:17:04.346886 0x7f01ebccf700 RPC TSC 0x7f01e592c188 client connection is allocated, uid:0xe5930250
12/23 11:17:04.346894 0x7f01ebccf700 RPC TSC UDP connection is setup, ip:9ade16ac:6030 localPort:30730
12/23 11:17:04.346905 0x7f01ebccf700 RPC TSC 0x7f01e592c188 0x2, connect is sent to 0027.novalocal:6030, len:373 sig:0x01000000:0x00000000:5743
12/23 11:17:04.346961 0x7f01ebccf700 TSC 0x7f01d8000920 DB async connection is opening
12/23 11:17:04.347753 0x7f01e512a700 RPC TSC 0x7f01e592c188 0x2, connect-rsp received from 0x9ade16ac:6030, parse code:0x0 len:767 sig:0x2b000000:0x01000000:5743 code:0x0
12/23 11:17:04.347807 0x7f01e512a700 TSC 0x7f01dc17c330 reset retry counter to be 0 due to success rsp, old:0
12/23 11:17:04.347940 0x7f01e512a700 TSC 0x7f01dc17c330 SQL cmd:connect, code:success rspLen:683
12/23 11:17:04.347959 0x7f01e512a700 TSC 0x7f01dc17c330 epSet.fqdn[0]: 0027.novalocal, pObj:0x7f01dc17bfa0
12/23 11:17:04.347961 0x7f01e512a700 TSC 0x7f01dc17c330 epSet.fqdn[1]: 0026.novalocal, pObj:0x7f01dc17bfa0
12/23 11:17:04.347963 0x7f01e512a700 TSC 0x7f01dc17c330 epSet.fqdn[2]: 0012-0004.novalocal, pObj:0x7f01dc17bfa0
12/23 11:17:04.347979 0x7f01e512a700 TSC 0x7f01d0001170 add to tscObj:0x7f01dc17bfa0, ref:3
12/23 11:17:04.347985 0x7f01e512a700 TSC 0x7f01d0001170 HB is allocated, pObj:0x7f01dc17bfa0
12/23 11:17:04.347994 0x7f01e512a700 TSC 0x7f01dc17c330 free sqlObj in cache
12/23 11:17:04.348039 0x7f01e512a700 TSC ERROR sql string exceeds max length:65480

如上所述，如果是 SQL 长度的问题，系统本身针对这种情况有处理机制吗，不应该直接跪了吧。
同问，如果修改配置文件中的属性，最大可以配置多少。

**Comment by sangshuduo** [comment]
数据库是单副本还是多副本？offline 是网络断了还是 taosd 崩溃了？可以通过 ps ax|grep taosd 看一下，如果是 taosd 崩溃了可以设置 coredump （参考 https://www.thegeekdiary.com/how-to-enable-core-dump-for-applications-on-centos-rhel/），这样调试起来更方便一些

**Comment by yaohang** [comment]
是 taosd 崩溃了。这是查看相关进程信息：
[root@0012-0004 crash]# ps ax|grep taosd
31803 pts/0    S+     0:00 grep --color=auto taosd

coredump 我这边配置的有点问题，好像没有生成，我再试试，另外，如果我通过配置文件属性调大这个 sql 的限制，最大可以支持多少。

**Comment by yaohang** [comment]
是默认的单副本

**Comment by sangshuduo** [comment]
最大可以支持 1MB

**Comment by sangshuduo** [comment]
2.0.14.0 应该解决这个问题了
