### ISSUE TITLE
Docker installation, JDBC connection cannot execute SQL

### ISSUE THREAD

**Issue by RookieXv** [taosdata/TDengine#4686]
我用docker安装的tdengine，在win10机器上使用jdbc连接，执行类似【语句1】“show users;”的可以执行成功，但是执行其他sql【语句2】报 TDengine Error: Unable to resolve FQDN

【语句1】String sql = "show users;";
【语句2】String sql = "select * from log.dn1;"; 

这是我的docker命令
docker run \
--name tdengine \
--restart always \
-d \
-v td_data_vol:/var/lib/taos \
-v td_log_vol:/var/log/taos \
-p 16030:6030 \
-p 16035:6035 \
-p 16041:6041 \
-p 16030-16040:6030-6040/udp \
tdengine/tdengine

这是我的taos.cfg
firstEp                   宿主机ip:16030

这是我的jdbcUrl
String jdbcUrl = "jdbc:TAOS://宿主机ip:16030/log";

**Comment by Aries-Lee1991** [comment]
请附上日志等详细信息。

**Comment by zyyang-taosdata** [comment]
在docker中检查1. docker容器的hostname，2，容器中taosd实例的dnodes，保证本机可以通过hostname访问到docker容器中的taosd实例

**Comment by HQDragon** [comment]
wsl2里面使用taosd服务，在host上用python connector也会出现这样的错误

**Comment by Xiejinwei93** [comment]
怎么没人说话了，这个怎么解决的哇
![image](https://user-images.githubusercontent.com/66400694/125908874-38103a27-d14a-4444-9d54-8eede10fa43c.png)

**Comment by zyyang-taosdata** [comment]
关于fqdn的问题，可以参考一下这片文档，https://mp.weixin.qq.com/s/hRpPXh77mXRg95VuNB4Lmw
