### ISSUE TITLE
使用sum函数与自己加的数据有出入

### ISSUE THREAD

**Issue by wy-w** [taosdata/TDengine#4694]
问题：使用sql  sum函数后，查询出的数据，与自己查看原始数据加起来的略微有些出入
数据库版本：2.0.7.0
数据库表结构：
![image](https://user-images.githubusercontent.com/55778678/103055641-ca574680-45d5-11eb-9c8b-7189f21b201f.png)

原始数据：
![image](https://user-images.githubusercontent.com/55778678/103055681-e22eca80-45d5-11eb-9a5f-03f859f5d096.png)
使用原始数据自己加的总和：
        2020-12-24 09:40:00.000              **367.12**

使用sql  中的sum函数（其他函数未检测）
2020-12-24 09:40:00.000 |             367.550003052
![image](https://user-images.githubusercontent.com/55778678/103055816-3fc31700-45d6-11eb-85b3-3b5fa3743a84.png)
查询出的数据：
![image](https://user-images.githubusercontent.com/55778678/103055866-61bc9980-45d6-11eb-9c90-7c966e8c84fd.png)

**Comment by sangshuduo** [comment]
interval 结果时间戳是起始时间。

09:20.00 365.77.. 是 9:20.00 到 9:30.00 两条相加的值

09:30.00 366.69是9:30.00 到 9:40.00 两条相加的值

**Comment by wy-w** [comment]
> interval结果最初是开始时间。
> 
> 09：20.00 365.77 ..是9：20.00到9：30.00两条相加的值
> 
> 09：30.00 366.69是9：30.00到9：40.00两条相加的值

![image](https://user-images.githubusercontent.com/55778678/103056914-4dc66700-45d9-11eb-8e40-ea574f024f65.png)
就说上面的数据吧，我计算9.40的数据  这里应该是9.35的数据+9.40的数据吧，是这意思么

**Comment by sangshuduo** [comment]
9:40:00 是 9:40:00 到 9:50:00 之间的数据

**Comment by wy-w** [comment]
> 9:40:00 是 9:40:00 到 9:50:00 之间的数据

这样的话是不是计算总和的时候会少数据啊，比如我计算9.10的总和（9.10-9.20**_前_**的数据）计算9.20的总和（9.20-9.30**### 前**的数据）
这样会漏掉9.20前-9.20的数据和啊

可能表达的不是很清楚，可以看下图
![103056914-4dc66700-45d9-11eb-8e40-ea574f024f65](https://user-images.githubusercontent.com/55778678/103068663-8fb2d580-45f8-11eb-9a66-6bf8df4d6ab6.png)

**Comment by wy-w** [comment]
![image](https://user-images.githubusercontent.com/55778678/103069221-e1a82b00-45f9-11eb-9fb3-ce8bee9c6545.png)
像我发的这种数据，计算中会遗漏掉一部分数据（这样加出来的总和也就不对了）
![103056914-4dc66700-45d9-11eb-8e40-ea574f024f65](https://user-images.githubusercontent.com/55778678/103069232-e967cf80-45f9-11eb-9590-08883061c668.png)
我感觉用黄绿色标出来的这个就是遗漏掉的数据，求和时就会将这段时间的数据抛弃吧
