### ISSUE TITLE
Million level data query slow

### ISSUE THREAD

**Issue by yaohang** [taosdata/TDengine#4697]
测试环境：集群部署，版本2.0.11。
目前创建了一张超级表，数据总量在1500w 左右，其中一张表的数据有450w，基于一个业务字段等值比较查询，耗时30多秒，请问如何优化。
另外，TDengine 只能对 ts 和 tag 建索引，那么类似这种普通的业务字段如果要检索的情况下，性能如何保障。
```
taos> use trace;
Database changed.

taos> select count(*) from trace_510100;
       count(*)        |
========================
               4538806 |
Query OK, 1 row(s) in set (0.043660s)

taos> select * from trace_510100 where thing_code='81acfb3e84657b1c9c94c0863422bc5c';
Query OK, 0 row(s) in set (36.834698s)

taos> 
```

**Comment by xiaopingcs** [comment]
你好，麻烦看一下show dnodes 和 show vgroups的结果

**Comment by yaohang** [comment]
taos> show dnodes;
   id   |           end_point            | vnodes | cores  |   status   | role  |       create_time       |      offline reason      |
======================================================================================================================================
      1 | 0027.novalocal:6030            |      2 |      4 | ready      | any   | 2020-12-23 14:25:24.268 |                          |
      2 | 0026.novalocal:6030            |      1 |      4 | ready      | any   | 2020-12-23 14:25:47.081 |                          |
      3 | 0012-0004.novalocal:6030       |      1 |      4 | ready      | any   | 2020-12-23 14:25:47.084 |                          |
Query OK, 3 row(s) in set (0.002970s)



taos> show vgroups;
    vgId     |   tables    |  status  | onlineVnodes | v1Dnode | v1Status  | v2Dnode | v2Status  | v3Dnode | v3Status  |
========================================================================================================================
           3 |          32 | ready    |            3 |       3 | master    |       2 | slave     |       1 | slave     |
Query OK, 1 row(s) in set (0.003005s)



请问TDengine 只能对 ts 和 tag 建索引，那么类似这种普通的业务字段在大数据量下检索，性能如何保障。

**Comment by xiaopingcs** [comment]
@hjxilinx 这个查询时间合理吗

**Comment by yaohang** [comment]
没有用到时间条件

**Comment by yaohang** [comment]
请问TDengine 只能对 ts 和 tag 建索引，那么类似这种普通的业务字段在大数据量下检索，性能如何保障。

**Comment by hjxilinx** [comment]
TD 的字符串过滤无法利用索引，需要全数据扫描，性能不会太好。

**Comment by sunshine-smdbs** [comment]
全匹配的话，从原理上就是全表扫描，会比较慢。即使用索引，也会比较大。
这个字段的取值范围是多大？能具体说说场景吗？ @yaohang

**Comment by xiaopingcs** [comment]
Closing this issue since there is no response for too many days.
