### ISSUE TITLE
After downgrading from version 2.0.11.0 to version 2.0.8.0, query data throws exception

### ISSUE THREAD

**Issue by huangbotao** [taosdata/TDengine#4698]
[root@tnode-online1 opt]# rpm -i--oldpackage -vh  TDengine-server-2.0.8.0-Linux-x64.rpm 
rpm: -i--oldpackage: unknown option
[root@tnode-online1 opt]# rpm -Uvh --oldpackage  TDengine-server-2.0.8.0-Linux-x64.rpm 
Preparing...                          ################################# [100%]
Updating / installing...
   1:tdengine-2.0.8.0-3               ################################# [ 50%]
Start to install TDEngine...
Created symlink from /etc/systemd/system/multi-user.target.wants/taosd.service to /etc/systemd/system/taosd.service.

Enter FQDN:port (like h1.taosdata.com:6030) of an existing TDengine cluster node to join
OR leave it blank to build one:

Enter your email address for priority support or enter empty to skip: 

To configure TDengine : edit /etc/taos/taos.cfg
To start TDengine     : sudo systemctl start taosd
To access TDengine    : use taos in shell

TDengine is installed successfully!
Cleaning up / removing...
   2:tdengine-2.0.11.0-3              warning: file /usr/local/taos/driver/libtaos.so.2.0.11.0: remove failed: No such file or directory
################################# [100%]
[root@tnode-online1 opt]# scp TDengine-server-2.0.8.0-Linux-x64.rpm tnode-online2:/opt/
Warning: Permanently added 'tnode-online2,10.39.50.84' (ECDSA) to the list of known hosts.
TDengine-server-2.0.8.0-Linux-x64.rpm                                                                                                                      100% 6293KB   6.2MB/s   00:00    
[root@tnode-online1 opt]# scp TDengine-server-2.0.8.0-Linux-x64.rpm tnode-online3:/opt/
Warning: Permanently added 'tnode-online3,10.39.50.85' (ECDSA) to the list of known hosts.
TDengine-server-2.0.8.0-Linux-x64.rpm                                                                                                                      100% 6293KB   6.2MB/s   00:00    
[root@tnode-online1 opt]# systemctl start taosd
[root@tnode-online1 opt]# systemctl status taosd
● taosd.service - TDengine server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2020-12-24 13:04:25 CST; 23s ago
 Main PID: 12773 (taosd)
   CGroup: /system.slice/taosd.service
           └─12773 /usr/bin/taosd

Dec 24 13:04:25 tnode-online1 systemd[1]: Started TDengine server service.
Dec 24 13:04:25 tnode-online1 systemd[1]: Starting TDengine server service...
Dec 24 13:04:25 tnode-online1 TDengine:[12773]: Starting TDengine service...
Dec 24 13:04:30 tnode-online1 TDengine:[12773]: Started TDengine service successfully.
[root@tnode-online1 opt]# taos

Welcome to the TDengine shell from Linux, Client Version:2.0.8.0
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

taos> use metric_data;
Database changed.

taos> select * from table_name_un1;

DB error: Invalid Vgroup ID (3.006345s)
taos>

**Comment by huangbotao** [comment]
taos> show databases;
              name              |      created_time       |   ntables   |   vgroups   | replica | quorum |  days  |    keep1,keep2,keep(D)     |  cache(MB)  |   blocks    |   minrows   |   maxrows   | wallevel |    fsync    | comp | precision | update |    status    |
============================================================================================================================================================================================================================================================================
 log                            | 2020-12-24 00:11:32.927 |           6 |           1 |       1 |      1 |     10 | 30,30,30                   |           1 |           3 |         100 |        4096 |        1 |        3000 |    2 | us        |      0 | ready        |
 metric_data                    | 2020-12-23 17:24:36.568 |      396763 |          24 |       3 |      1 |     10 | 365,365,365                |          16 |           6 |         100 |        4096 |        1 |        3000 |    2 | ms        |      1 | ready        |
Query OK, 2 row(s) in set (0.001059s)

taos> show stables;
              name              |      created_time       | columns |  tags  |   tables    |
============================================================================================
 stb_metric                     | 2020-12-23 17:29:46.692 |       3 |      6 |      323341 |
 stb_execute_log                | 2020-12-23 17:28:52.679 |      10 |      6 |           0 |
 stb_execute_rule               | 2020-12-23 17:29:21.223 |      10 |      5 |           0 |
 stb_multi_metric_agg_result    | 2020-12-23 17:29:55.173 |       6 |      4 |       73422 |
Query OK, 4 row(s) in set (0.000773s)

taos> select count(*) from stb_metric;

DB error: Invalid Vgroup ID (24.277348s)

**Comment by huangbotao** [comment]
```sh

taos> show databases;
              name              |      created_time       |   ntables   |   vgroups   | replica | quorum |  days  |    keep1,keep2,keep(D)     |  cache(MB)  |   blocks    |   minrows   |   maxrows   | wallevel |    fsync    | comp | precision | update |    status    |
============================================================================================================================================================================================================================================================================
 log                            | 2020-12-24 00:11:32.927 |           6 |           1 |       1 |      1 |     10 | 30,30,30                   |           1 |           3 |         100 |        4096 |        1 |        3000 |    2 | us        |      0 | ready        |
 metric_data                    | 2020-12-23 17:24:36.568 |      396763 |          24 |       3 |      1 |     10 | 365,365,365                |          16 |           6 |         100 |        4096 |        1 |        3000 |    2 | ms        |      1 | ready        |
Query OK, 2 row(s) in set (0.001059s)

taos> show stables;
              name              |      created_time       | columns |  tags  |   tables    |
============================================================================================
 stb_metric                     | 2020-12-23 17:29:46.692 |       3 |      6 |      323341 |
 stb_execute_log                | 2020-12-23 17:28:52.679 |      10 |      6 |           0 |
 stb_execute_rule               | 2020-12-23 17:29:21.223 |      10 |      5 |           0 |
 stb_multi_metric_agg_result    | 2020-12-23 17:29:55.173 |       6 |      4 |       73422 |
Query OK, 4 row(s) in set (0.000773s)

taos> select count(*) from stb_metric;

DB error: Invalid Vgroup ID (24.277348s)

```

**Comment by huangbotao** [comment]
```sh

taos> show vgroups;
    vgId     |   tables    |   status   | onlineVnodes | v1Dnode |  v1Status   | v2Dnode |  v2Status   | v3Dnode |  v3Status   |
================================================================================================================================
           3 |       17000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
           4 |       17000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
           5 |       17000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
           6 |       17000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
           7 |       17000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
           8 |       17000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
           9 |       17000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
          10 |       17000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
          11 |       17000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
          12 |       17000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
          13 |       17000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
          14 |       17000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
          15 |       16763 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
          16 |       16000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
          17 |       16000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
          18 |       16000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
          19 |       16000 | ready      |            0 |       3 | offline     |       2 | unsynced    |       1 | unsynced    |
          20 |       16000 | ready      |            0 |       3 | offline     |       2 | unsynced    |       1 | unsynced    |
          21 |       16000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
          22 |       16000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
          23 |       16000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
          24 |       16000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
          25 |       16000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
          26 |       16000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
Query OK, 24 row(s) in set (0.000870s)

```

**Comment by fenghuazzm** [comment]
This issue was closed because it has been inactive for too many days.
