### ISSUE TITLE
Taos shell startup failed

### ISSUE THREAD

**Issue by francis-du** [taosdata/TDengine#47]
### Screenshot : 
![image](https://user-images.githubusercontent.com/25944814/61210867-6bc74100-a730-11e9-9566-1aac4f70d52c.png)

**Comment by guanshengliang** [comment]
不太清楚您的这个环境，近期我们会放出windows客户端，

**Comment by francis-du** [comment]
### 好的，感谢，很期待！

**Comment by francis-du** [comment]
### @guanshengliang 好的，感谢回复，很期待

**Comment by riyun1989** [comment]
> ### Taos shell startup failed
> ### Version : tdengine-1.6.0.0.deb
> ### OS version : Windows 10 WSL Ubuntu 18.04.2 LTS
> ### Screenshot :
> ![image](https://user-images.githubusercontent.com/25944814/61210867-6bc74100-a730-11e9-9566-1aac4f70d52c.png)

我猜你是win10的系统，然后安装的wlx。因为我也碰到这个同样的问题

**Comment by riyun1989** [comment]
@francis-du 跟你碰到同样的问题

**Comment by riyun1989** [comment]
@guanshengliang  src/util/src/tsocket.c文件中的这段代码：`if (taosSetSockOpt(sockFd, SOL_SOCKET, SO_NO_CHECK, (void *)&nocheck, sizeof(nocheck)) < 0) {
    pError("setsockopt SO_NO_CHECK failed: %d (%s)", errno, strerror(errno));
    close(sockFd);
    return -1;
  }`，我猜这个启动错误是这里报出来了，但不知道这个判断以及方法是做什么用的。

**Comment by riyun1989** [comment]
@guanshengliang  日志设置为debug，看到类似这样的错误信息：` UTL open udp socket:192.168.5.67:0
07/17 16:25:34.216341 7fce9d5a0b80 ERROR UTL setsockopt SO_NO_CHECK failed: 92 (Protocol not available)
07/17 16:25:34.217030 7fce9d5a0b80 ERROR RPC TSC-vnode failed to open UDP socket 192.168.5.67:0
07/17 16:25:34.217707 7fce9d5a0b80 ERROR RPC TSC-vnode, failed to init network, 192.168.5.67:0`，192.168.5.67为本机内网ip，后面的端口为什么会是0呢？

**Comment by guanshengliang** [comment]
@riyun1989  如果编译不过，这个可以注释掉
目前不只支持wsl
因为有些linux的函数在wsl中是没有的，可以通过vmware安装一个完整的虚拟机来继续测试

**Comment by guanshengliang** [comment]
Windows客户端代码已经提交，dll可以在官网下载

**Comment by zimengpan** [comment]
> #339 已经为WSL提供了暂时的支持，请再尝试一下 

> #339 has provided with a temporary workaround, please pull and try again
