### ISSUE TITLE
Can TDengine develop in the ARM?

### ISSUE THREAD

**Issue by adminlzq6** [taosdata/TDengine#470]
我通过教程已经可以在Ubuntu下运行，但是网上并没有关于如何移植arm的相关信息，根据自己的经验有很多错误，如果可以移植，请问能给出教程吗？

**Comment by fangpanpan** [comment]
arm 平台下的版本仍在开发中。

**Comment by plum-lihui** [comment]
arm平台版本还在开发排期中，估计仍然需要一点时间才能开源发布。
