### ISSUE TITLE
Chinese garbled

### ISSUE THREAD

**Issue by chaixingyao-code** [taosdata/TDengine#4700]
liunx系统，导出成.sql文件，打开.sql文件
USE test;
CREATE TABLE IF NOT EXISTS test.device1001 USING test.operation TAGS ('\xe8\xae\xad\xe7\xbb\x83\xe6\xa8\xa1\xe6\x8b\x9f\xe5\x99\xa81\xe5\x8f\xb7', '1\xe5\x8f\xb7-\xe5\x88\x86\xe7\xb3\xbb\xe7\xbb\x9f1', '\xe7\xb1\xbb\xe5\x9e\x8b1', '\xe8\xae\xbe\xe5\xa4\x874', 'device1001');

最终会导致，导入的时候因为乱码问题，普通表创建不成功！！

**Comment by chaixingyao-code** [comment]
版本是：TDengine-server-2.0.0.1-Linux-x64.tar.gz

**Comment by plum-lihui** [comment]
这个应该是在写入的时候设置的编码，与使用taosdump导出时设置的编码不一致，从而出现这种情况。

你插入数据是怎么插入的，与taosdump运行的环境是在同一个系统上么？

**Comment by chaixingyao-code** [comment]
> 这个应该是在写入的时候设置的编码，与使用taosdump导出时设置的编码不一致，从而出现这种情况。
> 
> 你插入数据是怎么插入的，与taosdump运行的环境是在同一个系统上么？

暂时解决了，我创建超级表的时候，因为某些字段是字符串，所有我定义的是‘’BINARY”类型。
我发现把这些字段，改成“NCHAR”类型，导出后他就不会乱码了，不乱码就能导入成功！！
我也不知道为什么‘’BINARY”类型不行。
