### ISSUE TITLE
windows x64 Invalid client version 

### ISSUE THREAD

**Issue by god-pane** [taosdata/TDengine#4708]
**Bug Description**
- 编辑taos.cfg文件，将firstEP修改为TDengine服务器的End Point后
- 启用CMD 连接

“

**Result**
PS C:\TDengine> .\taos.exe

Welcome to the TDengine shell from Linux, Client Version:2.0.11.0
Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.

taos connect failed, reason: Invalid client version.

**log**
==================================================
12/24 19:40:32.069000 0x000006a4 UTL localEp is: DESKTOP-3AR9EIK:6030
12/24 19:40:32.069000 0x000006a4 UTL timezone not configured, use default
12/24 19:40:32.109000 0x000006a4 UTL locale not configured, set to default:Chinese_China.936
12/24 19:40:32.109000 0x000006a4 UTL charset not configured, set to default:cp936
12/24 19:40:32.109000 0x000006a4 UTL    taos config & system info:
12/24 19:40:32.109000 0x000006a4 UTL ==================================
12/24 19:40:32.109000 0x000006a4 UTL  firstEp:                10.5.17.45:6030 
12/24 19:40:32.109000 0x000006a4 UTL  secondEp:               DESKTOP-3AR9EIK:6030 
12/24 19:40:32.109000 0x000006a4 UTL  fqdn:                   DESKTOP-3AR9EIK 
12/24 19:40:32.109000 0x000006a4 UTL  serverPort:             6030 
12/24 19:40:32.109000 0x000006a4 UTL  configDir:              C:/TDengine/cfg 
12/24 19:40:32.109000 0x000006a4 UTL  logDir:                 C:/TDengine/log 
12/24 19:40:32.109000 0x000006a4 UTL  scriptDir:              C:/TDengine/script 
12/24 19:40:32.109000 0x000006a4 UTL  arbitrator:              
12/24 19:40:32.109000 0x000006a4 UTL  numOfThreadsPerCore:    1.000000 
12/24 19:40:32.109000 0x000006a4 UTL  rpcTimer:               1000(ms)
12/24 19:40:32.109000 0x000006a4 UTL  rpcMaxTime:             600(s)
12/24 19:40:32.109000 0x000006a4 UTL  shellActivityTimer:     3(s)
12/24 19:40:32.109000 0x000006a4 UTL  tableMetaKeepTimer:     7200(s)
12/24 19:40:32.109000 0x000006a4 UTL  compressMsgSize:        -1 
12/24 19:40:32.109000 0x000006a4 UTL  maxSQLLength:           65480(byte)
12/24 19:40:32.109000 0x000006a4 UTL  maxNumOfOrderedRes:     100000 
12/24 19:40:32.109000 0x000006a4 UTL  timezone:               not configured 
12/24 19:40:32.109000 0x000006a4 UTL  locale:                 Chinese_China.936 
12/24 19:40:32.109000 0x000006a4 UTL  charset:                cp936 
12/24 19:40:32.109000 0x000006a4 UTL  numOfLogLines:          10000000 
12/24 19:40:32.110000 0x000006a4 UTL  logKeepDays:            0 
12/24 19:40:32.110000 0x000006a4 UTL  asyncLog:               1 
12/24 19:40:32.110000 0x000006a4 UTL  debugFlag:              0 
12/24 19:40:32.110000 0x000006a4 UTL  rpcDebugFlag:           131 
12/24 19:40:32.110000 0x000006a4 UTL  tmrDebugFlag:           131 
12/24 19:40:32.110000 0x000006a4 UTL  cDebugFlag:             131 
12/24 19:40:32.110000 0x000006a4 UTL  jniDebugFlag:           131 
12/24 19:40:32.110000 0x000006a4 UTL  odbcDebugFlag:          131 
12/24 19:40:32.110000 0x000006a4 UTL  uDebugFlag:             131 
12/24 19:40:32.110000 0x000006a4 UTL  qDebugFlag:             131 
12/24 19:40:32.110000 0x000006a4 UTL  tsdbDebugFlag:          131 
12/24 19:40:32.110000 0x000006a4 UTL  gitinfo:                community 
12/24 19:40:32.110000 0x000006a4 UTL  gitinfoOfInternal:      internal 
12/24 19:40:32.110000 0x000006a4 UTL  buildinfo:              Built at 2020-12-13 11:56:07 
12/24 19:40:32.110000 0x000006a4 UTL  version:                2.0.10.0 
12/24 19:40:32.110000 0x000006a4 UTL  maxBinaryDisplayWidth:  30 
12/24 19:40:32.110000 0x000006a4 UTL  tempDir:                C:\Users\pane\AppData\Local\Temp 
12/24 19:40:32.612000 0x000006a4 UTL cache:tableMeta will be cleaned up

**Comment by sangshuduo** [comment]
服务端还是2.0.10.0？

**Comment by god-pane** [comment]
服务端版本是2.0.4.0

**Comment by sangshuduo** [comment]
服务端和客户端需要都升级到相同版本
