### ISSUE TITLE
一个库里的数据导出来，想导到另一个库里，实现起来太麻烦

### ISSUE THREAD

**Issue by chaixingyao-code** [taosdata/TDengine#4714]
把test  Datebases里的所有数据导出来，
导入到另一个test2  Datebases里面
实现起来太麻烦，因为.sql文件里面使用的都是test，还的手动把test改成test2，要么就写脚本：

数据量大的话，根本实现不了。没有其他数据库那么方便，后期能不能加入这样的功能。让库之间的导入更方便些。

**Comment by sangshuduo** [comment]
请列举其他数据库提供的方法，我们评估一下
