### ISSUE TITLE
data export then import to another table failed

### ISSUE THREAD

**Issue by moziie** [taosdata/TDengine#4716]
version :2.0.11.0
操作步骤:
1/超级表增加新列，类型int
2/执行select * from 子表1 >> "test.csv";
3/编辑test.csv，删除第一行描述信息，修改新增加列数值，修改null为22
4/执行insert into 子表3 file "test.csv";
然后提示DB error: Need to reconfigure table (0.000369s)
（1）数据信息
![image](https://user-images.githubusercontent.com/70946068/103120470-dbc25080-46b2-11eb-9df4-1b74f8a964d1.png)
（2）表结构信息
![image](https://user-images.githubusercontent.com/70946068/103120492-f1d01100-46b2-11eb-8c4c-0ef9e9034a3b.png)
（3）导出数据信息
![image](https://user-images.githubusercontent.com/70946068/103120529-16c48400-46b3-11eb-8759-aaeeb47dc9eb.png)
（4）修改后要导入信息
![image](https://user-images.githubusercontent.com/70946068/103120566-470c2280-46b3-11eb-9024-fca944a9e146.png)

**Comment by moziie** [comment]
显示的日志
12/25 15:46:59.564205 0x7f84c63b7700 TSC ERROR 0x7f84bc0108f0 add into queued async res, code:Need to reconfigure table
12/25 15:47:00.196582 0x7f84c63b7700 TSC ERROR 0x7f84bc0108f0 add into queued async res, code:Need to reconfigure table
12/25 15:47:00.596703 0x7f84c63b7700 TSC ERROR 0x7f84bc0108f0 add into queued async res, code:Need to reconfigure table
12/25 15:47:01.164673 0x7f84c63b7700 TSC ERROR 0x7f84bc0108f0 add into queued async res, code:Need to reconfigure table
12/25 15:47:16.420159 0x7f84c63b7700 TSC ERROR 0x7f84bc0108f0 add into queued async res, code:Need to reconfigure table

**Comment by sangshuduo** [comment]
下一个版本会解决这个问题
