### ISSUE TITLE
TDengine 2.0.8.2 show tables  slow (only 6 tables)

### ISSUE THREAD

**Issue by powersam** [taosdata/TDengine#4717]
taos> show tables;
           table_name           |      created_time       | columns |          stable_name           |          uid          |     tid     |    vgId     |
==========================================================================================================================================================
 therm2                         | 2020-12-16 01:47:37.013 |       2 | thermometer                    |       844424983047053 |           3 |           3 |
 t                              | 2020-12-15 06:15:49.539 |       2 |                                |       844424946924843 |           1 |           3 |
 therm1                         | 2020-12-16 01:47:05.128 |       2 | thermometer                    |       844424966269613 |           2 |           3 |
 therm4                         | 2020-12-16 01:47:52.333 |       2 | thermometer                    |       844425016602009 |           5 |           3 |
 therm3                         | 2020-12-16 01:47:47.010 |       2 | thermometer                    |       844424999824527 |           4 |           3 |
 d1002                          | 2020-12-17 07:17:57.987 |       4 | meters                         |       844425050157133 |           7 |           3 |
Query OK, 6 row(s) in set (21.744943s)

taos> exit
[root@td01 ~]# taos

Welcome to the TDengine shell from Linux, Client Version:2.0.8.2
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

**Comment by sangshuduo** [comment]
请提供更多信息，例如单机部署还是集群部署，硬件配置，数据数量包含超级表的数量、表的数量、记录数量，top信息等。
另外建议升级到最新版本

**Comment by sangshuduo** [comment]
无更新，关闭。
