### ISSUE TITLE
Response is too slow if query tag !=*

### ISSUE THREAD

**Issue by wsf1990** [taosdata/TDengine#472]
执行如下语句，无任何响应：

```
select count(*) from stable  where f1 != 1 and name <> "123";
```

我的超级表建了一个 name 的 tag，对此字段执行 <> 异常的慢，执行 = 正常。

**Comment by hjxilinx** [comment]
How many tables do you have?

**Comment by wsf1990** [comment]
About thirty.

**Comment by wsf1990** [comment]
I test it again, and found this not just caused by tag column <>, The reason is set two <> condition on two different columns.

**Comment by hjxilinx** [comment]
<> on normal columns? not just tags, right?

**Comment by wsf1990** [comment]
yes

**Comment by hjxilinx** [comment]
What type is this normal column? And what is the total elapsed time on this column?

**Comment by wsf1990** [comment]
I had test dobule and binary, all were same. Maybe two mintues.

**Comment by hjxilinx** [comment]
Well, the TDengine does not index the normal columns, so the filter operation is fulfilled by scan all data blocks within the given time window. In some cases, the pre-computing information may be involved to speedup this procedure. However, if the numeric value are randomly distributed, scan all data blocks may cause a relative long period. Besides , this speedup by pre-computing information can not be applied to binary column.
