### ISSUE TITLE
客户端查看时数据显示不全怎么办

### ISSUE THREAD

**Issue by caojianwudong** [taosdata/TDengine#4720]
通过taos客户端查看数据库时，有几个字段存储的binary数据比较长，客户端上通过sql语句查询时，数据显示不全，怎么办，客户端着怎么设置以下可以将字段中的所有数据都显示在终端上啊

**Comment by sangshuduo** [comment]
https://www.taosdata.com/cn/documentation20/faq/

由于 taos shell 在终端中显示宽度有限，有可能比较长的表名显示不全，如果按照显示的不全的表名进行相关操作会发生 Table does not exist 错误。解决方法可以是通过修改 taos.cfg 文件中的设置项 maxBinaryDisplayWidth， 或者直接输入命令 set max_binary_display_width 100。或者在命令结尾使用 \G 参数来调整结果的显示方式。

**Comment by caojianwudong** [comment]
可以了，谢谢楼上
