### ISSUE TITLE
安全漏洞

### ISSUE THREAD

**Issue by Donald-Chun** [taosdata/TDengine#4721]
1. 通过安装包安装后，taosd服务默认以root账号启动。
2. 不管在/etc/taos/taos.cfg 如何配置，taosd服务总是监听 0.0.0.0:6030，这意味着如果服务器不配置防火墙规则，那taosd服务就是在裸奔。

**Comment by sangshuduo** [comment]
安全是系统问题，需要系统管理员来管理整个系统的安全问题。当然数据库自身的安全问题也可以讨论。
