### ISSUE TITLE
静态链接库不可用

### ISSUE THREAD

**Issue by caojianwudong** [taosdata/TDengine#4722]
编译出来后，把.a文件拷贝出来后，编译的时候老是报错
/usr/bin/ld: /home/***/TDengine-ver-2.0.11.0/src/util/src/tutil.c:380: undefined reference to `uDebugFlag'
/usr/bin/ld: /home/***/TDengine-ver-2.0.11.0/src/util/src/tutil.c:380: undefined reference to `tscEmbedded'
/usr/bin/ld: /home/***/TDengine-ver-2.0.11.0/src/util/src/tutil.c:380: undefined reference to `uDebugFlag'
collect2: error: ld returned 1 exit status

**Comment by sangshuduo** [comment]
目前静态库不是 TDengine 发布的一部分。毕竟没有经过严格测试，也不太推荐使用静态库的方式。
如果一定要使用静态库，需要链接 build/lib 下其他的 .a 文件。参考命令如下：

gcc -static -fPIC demo.c -o demo -L<TDengine>/debug/build/lib -ltaos_static -ltrpc -ltutil -pthread -lquery -ltsdb -lcommon -ltutil -llz4 -losdetail -los -lz -lm -lrt
