### ISSUE TITLE
taos.error.ProgrammingError: Timestamp data out of range

### ISSUE THREAD

**Issue by powersam** [taosdata/TDengine#4729]
start_time = datetime.datetime(2001, 7, 1)

value = c1.execute("insert into t values ('%s', %d, %f, '%s')" % (start_time, i, random.randint(1,10)/10.0, 'hello'))

出错：
taos.error.ProgrammingError: Timestamp data out of range

啥情况呢

**Comment by xiaopingcs** [comment]
数据库默认保存3650天的数据，如果想保存2001年的数据，需要修改keep， alter database dbname keep 8000就应该没问题了

**Comment by powersam** [comment]
> 数据库默认保存3650天的数据，如果想保存2001年的数据，需要修改keep， alter database dbname keep 8000就应该没问题了
经过测试按你提供的方案修改保留时间 时可以存储2001年的数据，这个问题应该已经明确。
接着问：
   为何我自动生成数据到未来2021年1月7日就同样报错误 taos.error.ProgrammingError: Timestamp data out of range
对还没到时间的数据存储也是有参数规定吗？
