### ISSUE TITLE
failed to connect to taosd on the aliyun 

### ISSUE THREAD

**Issue by jiawei123** [taosdata/TDengine#473]
taos_ 6020已经在监听中，telnet连接的了，nc访问不了报错11004，客户端也连接不上

**Comment by guanshengliang** [comment]
1.实验本机连接，验证是否数据库问题
2.同一个区域申请另一台机器，验证是否局域网或者防火墙问题

**Comment by jiawei123** [comment]
在阿里云轻应用服务器中，需要将taos占用端口既需要TCP协议也需要UDP协议
