### ISSUE TITLE
python-taos 和 taos shell 小数输出不一致

### ISSUE THREAD

**Issue by olajowon** [taosdata/TDengine#4737]
同样的sql

SELECT LAST(value) FROM t_cdb2f259cbbdc3a9a056872d85d9a6c7 WHERE ts>=1609051677000 AND ts<1609055277999 INTERVAL (1m) FILL (NULL);

python 
![image](https://user-images.githubusercontent.com/18394195/103166270-60e86980-485b-11eb-846f-c799f4cd8a74.png)

shell
![image](https://user-images.githubusercontent.com/18394195/103166278-78bfed80-485b-11eb-94aa-143af24aad8e.png)

shell 输出的才是想要的，和插入的一致

**Comment by olajowon** [comment]
python: 
(datetime.datetime(2020, 12, 27, 15, 42), 0.019999999552965164), (datetime.datetime(2020, 12, 27, 15, 43), 0.029999999329447746)

shell:
2020-12-27 15:42:00.000 |              0.02000 |
 2020-12-27 15:43:00.000 |              0.03000 |

**Comment by sangshuduo** [comment]
浮点数是有精度损失
