### ISSUE TITLE
 Can't find taos.h in the go connector

### ISSUE THREAD

**Issue by nieaowei** [taosdata/TDengine#474]
# tuoxie-user-handle-service/taosSql
../taosSql/result.go:23:10: fatal error: 'taos.h' file not found
#include <taos.h>
         ^~~~~~~~
1 error generated.

**Comment by fangpanpan** [comment]
Could you find "taos.h" in the /usr/include/ ?

**Comment by plum-lihui** [comment]
使用tdengine的go驱动，依赖有两个，一个是taos.h，一个libtaos.so。这在安装包中都有，安装tdengine时，自动将taos.h链接到/usr/include下，将libtaos.so链接到/usr/lib下。
安装后，请确认一下，这两个目录下的文件时候是正确的。

**Comment by ZSCLM** [comment]
我在CentOS机器上安装了数据库的服务端，然后在windows的机器上运行go项目，也报了这个错误，请问需要如何配置呢？

**Comment by ZSCLM** [comment]
> 使用tdengine的go驱动，依赖有两个，一个是taos.h，一个libtaos.so。这在安装包中都有，安装tdengine时，自动将taos.h链接到/usr/include下，将libtaos.so链接到/usr/lib下。
> 安装后，请确认一下，这两个目录下的文件时候是正确的。

我在CentOS机器上安装了数据库的服务端，然后在windows的机器上运行go项目，也报了这个错误，请问需要如何配置呢？或者说go的驱动也只能在Linux系统上生效？

**Comment by fangpanpan** [comment]
请问您在Windows下安装了客户端吗？以及您确认了这两个文件taos.h 和libtao.so 存在？

**Comment by ZSCLM** [comment]
> 请问您在Windows下安装了客户端吗？以及您确认了这两个文件taos.h 和libtao.so 存在？

客户端是安装了的，您是指默认安装在C:\TDengine的那个吧？另外 taos.h 和 libtao.so 我都从服务端下载下来了，分别需要放置在windows系统下的什么地方？

**Comment by fangpanpan** [comment]
您将C:\TDengine\driver\taos.dll拷贝到C:\windows\system32目录下了吗？Windows下，所有TDengine的连接器，均需依赖taos.dll。

**Comment by ZSCLM** [comment]
> 您将C:\TDengine\driver\taos.dll拷贝到C:\windows\system32目录下了吗？Windows下，所有TDengine的连接器，均需依赖taos.dll。

已经拷贝了，如图：
![image](https://user-images.githubusercontent.com/5078654/65824150-a1db8200-e296-11e9-910a-13537f103146.png)

**Comment by nieaowei** [comment]
> > 请问您在Windows下安装了客户端吗？以及您确认了这两个文件taos.h 和libtao.so 存在？
> 
> 客户端是安装了的，您是指默认安装在C:\TDengine的那个吧？另外 taos.h 和 libtao.so 我都从服务端下载下来了，分别需要放置在windows系统下的什么地方？

似乎可以尝试将动态库和头文件拷贝至项目目录，修改result.go文件中的lib目录以及include目录

**Comment by chuannull** [comment]
> 请问您在Windows下安装了客户端吗？以及您确认了这两个文件taos.h 和libtao.so 存在？

你好, Windows下安装了客户端只找到了C:\TDengine\include\taos.h没有libtao.so? libtao.so只在CentOS机器上有?

**Comment by plum-lihui** [comment]
so的库是linux下才有的，windows下是dll的库。

**Comment by chuannull** [comment]
> so的库是linux下才有的，windows下是dll的库。

请问如何在windows下用go连接？按照教程在windows下go get会报找不到taos.h

**Comment by plum-lihui** [comment]
现在不支持windows下使用go链接，因为我们没有发布windows下go链接使用的dll库。

**Comment by chuannull** [comment]
> 现在不支持windows下使用go链接，因为我们没有发布windows下go链接使用的dll库。

噢噢，那有发布计划吗

**Comment by plum-lihui** [comment]
暂时排在比较靠后
