### ISSUE TITLE
> 数据库默认保存3650天的数据，如果想保存2001年的数据，需要修改keep， alter database dbname keep 8000就应该没问题了

### ISSUE THREAD

**Issue by powersam** [taosdata/TDengine#4741]
> 数据库默认保存3650天的数据，如果想保存2001年的数据，需要修改keep， alter database dbname keep 8000就应该没问题了
经过测试按你提供的方案修改保留时间 时可以存储2001年的数据，这个问题应该已经明确。
接着问：
   为何我自动生成数据到未来2021年1月7日就同样报错误 taos.error.ProgrammingError: Timestamp data out of range
对还没到时间的数据存储也是有参数规定吗？

_Originally posted by @powersam in https://github.com/taosdata/TDengine/issues/4729#issuecomment-751562014_

**Comment by sangshuduo** [comment]
这是由另一个参数 days 控制的，默认值为10。但是不建议修改
