### ISSUE TITLE
will TDengine support Mac?

### ISSUE THREAD

**Issue by MelodyI** [taosdata/TDengine#4746]
这个问题前面有人提了，[连接](https://github.com/taosdata/TDengine/issues/3191)
现在问题被关闭了，是不准备解决了吗

**Comment by sangshuduo** [comment]
优先级比较低，除非有付费用户需求。

**Comment by MelodyI** [comment]
服务器端没有能理解，客户端（至少驱动）要有一个。

**Comment by MelodyI** [comment]
没有驱动写程序太痛苦

**Comment by ljzorz** [comment]
对呀，客户端至少要有吧，很多用mac开发的程序员

**Comment by sangshuduo** [comment]
新的 develop 分支已经支持 Mac 下编译，欢迎试用
