### ISSUE TITLE
alert crash

### ISSUE THREAD

**Issue by nzxxs4** [taosdata/TDengine#4747]
今天用alert批量插入规则，4条，直接崩溃，然后就起来之后坚持不到10s。
是通过go编译的，有没有可能版本的问题，应该用go哪个版本去编译呢，alert用的是最新的那个版本，跟tdengine版本有关吗
下面是错误日志：
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2d0 pc=0x7f914eef3b81]

runtime stack:
runtime.throw(0x9ba1d2, 0x2a)
	/home/ubuntu/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/home/ubuntu/go/src/runtime/signal_unix.go:704 +0x4ac

goroutine 40 [syscall]:
runtime.cgocall(0x8d7c90, 0xc00039db10, 0xc00039db40)
	/home/ubuntu/go/src/runtime/cgocall.go:133 +0x5b fp=0xc00039dae0 sp=0xc00039daa8 pc=0x4102fb
github.com/taosdata/driver-go/taosSql._Cfunc_taos_close(0x7f910803d790)
	_cgo_gotypes.go:146 +0x45 fp=0xc00039db10 sp=0xc00039dae0 pc=0x8205a5
github.com/taosdata/driver-go/taosSql.(*taosConn).taos_close.func1(0xc0000202a0)
	/home/ubuntu/gopath/pkg/mod/github.com/taosdata/driver-go@v0.0.0-20201113094317-050667e5b4d0/taosSql/taosSqlCgo.go:83 +0x55 fp=0xc00039db48 sp=0xc00039db10 pc=0x827655
github.com/taosdata/driver-go/taosSql.(*taosConn).taos_close(0xc0000202a0)
	/home/ubuntu/gopath/pkg/mod/github.com/taosdata/driver-go@v0.0.0-20201113094317-050667e5b4d0/taosSql/taosSqlCgo.go:83 +0x2b fp=0xc00039db60 sp=0xc00039db48 pc=0x82592b
github.com/taosdata/driver-go/taosSql.(*taosConn).Close(0xc0000202a0, 0x0, 0x0)
	/home/ubuntu/gopath/pkg/mod/github.com/taosdata/driver-go@v0.0.0-20201113094317-050667e5b4d0/taosSql/connection.go:70 +0x31 fp=0xc00039db78 sp=0xc00039db60 pc=0x820e31
database/sql.(*driverConn).finalClose.func2()
	/home/ubuntu/go/src/database/sql/sql.go:592 +0x49 fp=0xc00039dbb0 sp=0xc00039db78 pc=0x7408c9
database/sql.withLock(0xa33880, 0xc0001a4090, 0xc00039dc38)
	/home/ubuntu/go/src/database/sql/sql.go:3284 +0x69 fp=0xc00039dbe0 sp=0xc00039dbb0 pc=0x7404c9
database/sql.(*driverConn).finalClose(0xc0001a4090, 0x0, 0xc00039dcb8)
	/home/ubuntu/go/src/database/sql/sql.go:590 +0x130 fp=0xc00039dc78 sp=0xc00039dbe0 pc=0x7322f0
database/sql.finalCloser.finalClose-fm(0xc000220000, 0xa2ff40)
	/home/ubuntu/go/src/database/sql/sql.go:636 +0x2f fp=0xc00039dca0 sp=0xc00039dc78 pc=0x742c0f
database/sql.(*driverConn).Close(0xc0001a4090, 0xc0001a4090, 0x0)
	/home/ubuntu/go/src/database/sql/sql.go:571 +0x135 fp=0xc00039dcf0 sp=0xc00039dca0 pc=0x732115
database/sql.(*DB).putConn(0xc000220000, 0xc0001a4090, 0x0, 0x0, 0xa33801)
	/home/ubuntu/go/src/database/sql/sql.go:1391 +0x1ef fp=0xc00039dd50 sp=0xc00039dcf0 pc=0x7365ef
database/sql.(*driverConn).releaseConn(...)
	/home/ubuntu/go/src/database/sql/sql.go:475
database/sql.(*driverConn).releaseConn-fm(0x0, 0x0)
	/home/ubuntu/go/src/database/sql/sql.go:474 +0x4b fp=0xc00039dd88 sp=0xc00039dd50 pc=0x742c8b
database/sql.(*Rows).close(0xc000186100, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/go/src/database/sql/sql.go:3180 +0x164 fp=0xc00039ddf0 sp=0xc00039dd88 pc=0x73fee4
database/sql.(*Rows).Close(...)
	/home/ubuntu/go/src/database/sql/sql.go:3151
database/sql.(*Rows).Next(0xc000186100, 0xc00009fc70)
	/home/ubuntu/go/src/database/sql/sql.go:2839 +0xb8 fp=0xc00039de50 sp=0xc00039ddf0 pc=0x73e418
github.com/taosdata/alert/app.(*Rule).run(0xc00009fc70, 0xc000220000)
	/home/ubuntu/ver_release_workspace/TDinternal/community/alert/app/rule.go:371 +0x356 fp=0xc00039df88 sp=0xc00039de50 pc=0x7fef76
github.com/taosdata/alert/app.runRules.func1.1(0xc000220000, 0xc00009fc70)
	/home/ubuntu/ver_release_workspace/TDinternal/community/alert/app/rule.go:499 +0x7e fp=0xc00039dfd0 sp=0xc00039df88 pc=0x801ade
runtime.goexit()
	/home/ubuntu/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00039dfd8 sp=0xc00039dfd0 pc=0x477801
created by github.com/taosdata/alert/app.runRules.func1
	/home/ubuntu/ver_release_workspace/TDinternal/community/alert/app/rule.go:496 +0xb4

goroutine 1 [chan receive]:
main.main()
	/home/ubuntu/ver_release_workspace/TDinternal/community/alert/cmd/alert/main.go:174 +0x39d

goroutine 19 [select]:
database/sql.(*DB).connectionOpener(0xc00009f6c0, 0xa39000, 0xc0000ce640)
	/home/ubuntu/go/src/database/sql/sql.go:1126 +0xf5
created by database/sql.OpenDB
	/home/ubuntu/go/src/database/sql/sql.go:740 +0x12a

goroutine 34 [select]:
database/sql.(*DB).connectionOpener(0xc000220000, 0xa39000, 0xc000218000)
	/home/ubuntu/go/src/database/sql/sql.go:1126 +0xf5
created by database/sql.OpenDB
	/home/ubuntu/go/src/database/sql/sql.go:740 +0x12a

goroutine 25 [select]:
github.com/taosdata/alert/app.runRules()
	/home/ubuntu/ver_release_workspace/TDinternal/community/alert/app/rule.go:482 +0x23f
created by github.com/taosdata/alert/app.initRule
	/home/ubuntu/ver_release_workspace/TDinternal/community/alert/app/rule.go:633 +0x76

goroutine 26 [select]:
github.com/taosdata/alert/app.pushAlerts()
	/home/ubuntu/ver_release_workspace/TDinternal/community/alert/app/rule.go:544 +0x185
created by github.com/taosdata/alert/app.initRule
	/home/ubuntu/ver_release_workspace/TDinternal/community/alert/app/rule.go:634 +0x8e

goroutine 27 [IO wait]:
internal/poll.runtime_pollWait(0x7f914f73cf70, 0x72, 0x0)
	/home/ubuntu/go/src/runtime/netpoll.go:220 +0x55
internal/poll.(*pollDesc).wait(0xc000186018, 0x72, 0x0, 0x0, 0x9a8dc2)
	/home/ubuntu/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/home/ubuntu/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000186000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/go/src/internal/poll/fd_unix.go:394 +0x1fc
net.(*netFD).accept(0xc000186000, 0xc000020180, 0x41aaf8, 0xc000080000)
	/home/ubuntu/go/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc00000e060, 0xc00005bdc8, 0x41aaf8, 0x30)
	/home/ubuntu/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00000e060, 0x975d60, 0xc000020180, 0x92b8c0, 0xe8afc0)
	/home/ubuntu/go/src/net/tcpsock.go:261 +0x65
net/http.(*Server).Serve(0xc000138000, 0xa37e40, 0xc00000e060, 0x0, 0x0)
	/home/ubuntu/go/src/net/http/server.go:2937 +0x266
net/http.(*Server).ListenAndServe(0xc000138000, 0x0, 0x0)
	/home/ubuntu/go/src/net/http/server.go:2866 +0xb7
main.serveWeb.func1(0xc000138000)
	/home/ubuntu/ver_release_workspace/TDinternal/community/alert/cmd/alert/main.go:44 +0x2f
created by main.serveWeb
	/home/ubuntu/ver_release_workspace/TDinternal/community/alert/cmd/alert/main.go:43 +0x1a5

goroutine 29 [syscall]:
os/signal.signal_recv(0x0)
	/home/ubuntu/go/src/runtime/sigqueue.go:147 +0x9d
os/signal.loop()
	/home/ubuntu/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/home/ubuntu/go/src/os/signal/signal.go:150 +0x45

**Comment by localvar** [comment]
方便把您的联系方式发到 bmzhang@taosdata.com 吗？这看起来是 c 连接器的问题，需要远程查一下

**Comment by nzxxs4** [comment]
谢谢您，我们的环境连接热点 就不能连接x-shell，不太好实现远程，请问需要查那几部分，我截图给您，或邮箱给您，另外 会不会是因为规则name太长呢，有无限制。

规则是这样的：

{
  "name": "次要告警4b29f664225249089e4c86bf0122a234内存使用率高",
  "state": 0,
  "sql": "select last_row(f_used_percent) as uup from host.mem where (t_host = 'aiops.web' or  t_host = 'db.taos')  and ts>now-10s group by t_host",
  "for": "20s",
  "period": "10s",
  "expr": "uup > 14",
  "labels": {
    "alertLevel": "500",
    "alertLevelName": "严重告警",
    "alertType": "0",
    "group": "主机",
    "group_code": "host",
    "ruleName": "内存使用率高"
  },
  "annotations": {
    "monitorObj": "com.je.core.util.bean.DynaBean@1ba9a77,",
    "summary": "严重告警: 内存使用率高用户使用率的最新记录值为：{{$values.uup}} 监控对象：主机名: {{$values.t_host}} "
  }
}

从启动到崩溃是这样的：
[root@db alert]# ./alert -cfg=alert.cfg 
<input>:1:70: invalid char literal
<input>:1:95: invalid char literal
<input>:1:70: invalid char literal
<input>:1:95: invalid char literal
<input>:1:70: invalid char literal
<input>:1:95: invalid char literal
<input>:1:70: invalid char literal
<input>:1:95: invalid char literal
2020-12-29T10:44:14.588+0800	INFO	log/log.go:49	total 4 rules loaded
2020-12-29T10:44:14.588+0800	INFO	log/log.go:44	Listening at port: 8100
{"startsAt":"2020-12-29T10:44:40.602619079+08:00","endsAt":"0001-01-01T00:00:00Z","values":{"t_host":"db.taos\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","uup":20.445592},"labels":{"alertLevel":"500","alertLevelName":"严重告警","alertType":"0","group":"主机","group_code":"host","ruleName":"内存使用率高","t_host":"db.taos\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"},"annotations":{"monitorObj":"com.je.core.util.bean.DynaBean@1ba9a77,","summary":"严重告警: 内存使用率高用户使用率的最新记录值为：20.445592 \n监控对象：主机名: db.taos\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 "}}
................................
................................
{"startsAt":"2020-12-29T10:48:01.015681615+08:00","endsAt":"0001-01-01T00:00:00Z","values":{"t_host":"db.taos\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","uup":20.556123},"labels":{"alertLevel":"500","alertLevelName":"严重告警","alertType":"0","group":"主机","group_code":"host","ruleName":"内存使用率高","t_host":"db.taos\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"},"annotations":{"monitorObj":"com.je.core.util.bean.DynaBean@1ba9a77,","summary":"严重告警: 内存使用率高用户使用率的最新记录值为：20.556123 \n监控对象：主机名: db.taos\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 "}}
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2d0 pc=0x7fe6a7f5ab81]

runtime stack:
runtime.throw(0x9bf7af, 0x2a)
	/root/soft/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/root/soft/go/src/runtime/signal_unix.go:679 +0x46a

goroutine 91 [syscall]:
runtime.cgocall(0x8cb420, 0xc00014db00, 0xc00014db30)
	/root/soft/go/src/runtime/cgocall.go:133 +0x5b fp=0xc00014dad0 sp=0xc00014da98 pc=0x40aceb
github.com/taosdata/driver-go/taosSql._Cfunc_taos_close(0x7fe6280028d0)
	_cgo_gotypes.go:176 +0x41 fp=0xc00014db00 sp=0xc00014dad0 pc=0x801891
github.com/taosdata/driver-go/taosSql.(*taosConn).taos_close.func1(0xc000304c00)
	/root/go/pkg/mod/github.com/taosdata/driver-go@v0.0.0-20200727182616-1a3b1941c206/taosSql/taosSqlCgo.go:86 +0x55 fp=0xc00014db38 sp=0xc00014db00 pc=0x807fd5
github.com/taosdata/driver-go/taosSql.(*taosConn).taos_close(0xc000304c00)
	/root/go/pkg/mod/github.com/taosdata/driver-go@v0.0.0-20200727182616-1a3b1941c206/taosSql/taosSqlCgo.go:86 +0x2b fp=0xc00014db50 sp=0xc00014db38 pc=0x80636b
github.com/taosdata/driver-go/taosSql.(*taosConn).Close(0xc000304c00, 0x0, 0x0)
	/root/go/pkg/mod/github.com/taosdata/driver-go@v0.0.0-20200727182616-1a3b1941c206/taosSql/connection.go:70 +0x31 fp=0xc00014db68 sp=0xc00014db50 pc=0x801fc1
database/sql.(*driverConn).finalClose.func2()
	/root/soft/go/src/database/sql/sql.go:573 +0x49 fp=0xc00014dba0 sp=0xc00014db68 pc=0x728049
database/sql.withLock(0xa5c8c0, 0xc000302600, 0xc00014dc28)
	/root/soft/go/src/database/sql/sql.go:3184 +0x69 fp=0xc00014dbd0 sp=0xc00014dba0 pc=0x727cb9
database/sql.(*driverConn).finalClose(0xc000302600, 0x992620, 0x7fe67c0081b0)
	/root/soft/go/src/database/sql/sql.go:571 +0x130 fp=0xc00014dc68 sp=0xc00014dbd0 pc=0x71a530
database/sql.finalCloser.finalClose-fm(0xc00009c000, 0xa58180)
	/root/soft/go/src/database/sql/sql.go:617 +0x2f fp=0xc00014dc90 sp=0xc00014dc68 pc=0x72a20f
database/sql.(*driverConn).Close(0xc000302600, 0xc000302600, 0x0)
	/root/soft/go/src/database/sql/sql.go:552 +0x12b fp=0xc00014dce0 sp=0xc00014dc90 pc=0x71a35b
database/sql.(*DB).putConn(0xc00009c000, 0xc000302600, 0x0, 0x0, 0xa5c801)
	/root/soft/go/src/database/sql/sql.go:1329 +0x202 fp=0xc00014dd50 sp=0xc00014dce0 pc=0x71e292
database/sql.(*driverConn).releaseConn(...)
	/root/soft/go/src/database/sql/sql.go:473
database/sql.(*driverConn).releaseConn-fm(0x0, 0x0)
	/root/soft/go/src/database/sql/sql.go:472 +0x4b fp=0xc00014dd88 sp=0xc00014dd50 pc=0x72a28b
database/sql.(*Rows).close(0xc000302680, 0x0, 0x0, 0x0, 0x0)
	/root/soft/go/src/database/sql/sql.go:3088 +0x15f fp=0xc00014ddf0 sp=0xc00014dd88 pc=0x72771f
database/sql.(*Rows).Close(...)
	/root/soft/go/src/database/sql/sql.go:3059
database/sql.(*Rows).Next(0xc000302680, 0xc0002028f0)
	/root/soft/go/src/database/sql/sql.go:2748 +0xb8 fp=0xc00014de50 sp=0xc00014ddf0 pc=0x725cd8
github.com/taosdata/alert/app.(*Rule).run(0xc0002028f0, 0xc00009c000)
	/root/TDengine-develop/alert/app/rule.go:369 +0x34a fp=0xc00014df88 sp=0xc00014de50 pc=0x7e14ea
github.com/taosdata/alert/app.runRules.func1.1(0xc00009c000, 0xc0002028f0)
	/root/TDengine-develop/alert/app/rule.go:497 +0x7e fp=0xc00014dfd0 sp=0xc00014df88 pc=0x7e3f5e
runtime.goexit()
	/root/soft/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00014dfd8 sp=0xc00014dfd0 pc=0x46a601
created by github.com/taosdata/alert/app.runRules.func1
	/root/TDengine-develop/alert/app/rule.go:494 +0xb4

goroutine 1 [chan receive]:
main.main()
	/root/TDengine-develop/alert/cmd/alert/main.go:174 +0x396

goroutine 6 [select]:
database/sql.(*DB).connectionOpener(0xc00016c000, 0xa62280, 0xc00002c6c0)
	/root/soft/go/src/database/sql/sql.go:1052 +0xe8
created by database/sql.OpenDB
	/root/soft/go/src/database/sql/sql.go:722 +0x15d

goroutine 7 [select]:
database/sql.(*DB).connectionResetter(0xc00016c000, 0xa62280, 0xc00002c6c0)
	/root/soft/go/src/database/sql/sql.go:1065 +0xfb
created by database/sql.OpenDB
	/root/soft/go/src/database/sql/sql.go:723 +0x193

goroutine 35 [select]:
database/sql.(*DB).connectionResetter(0xc00009c000, 0xa62280, 0xc000094000)
	/root/soft/go/src/database/sql/sql.go:1065 +0xfb
created by database/sql.OpenDB
	/root/soft/go/src/database/sql/sql.go:723 +0x193

goroutine 34 [select]:
database/sql.(*DB).connectionOpener(0xc00009c000, 0xa62280, 0xc000094000)
	/root/soft/go/src/database/sql/sql.go:1052 +0xe8
created by database/sql.OpenDB
	/root/soft/go/src/database/sql/sql.go:722 +0x15d

goroutine 18 [select]:
github.com/taosdata/alert/app.runRules()
	/root/TDengine-develop/alert/app/rule.go:480 +0x239
created by github.com/taosdata/alert/app.initRule
	/root/TDengine-develop/alert/app/rule.go:631 +0x73

goroutine 19 [select]:
github.com/taosdata/alert/app.pushAlerts()
	/root/TDengine-develop/alert/app/rule.go:542 +0x182
created by github.com/taosdata/alert/app.initRule
	/root/TDengine-develop/alert/app/rule.go:632 +0x8b

goroutine 20 [IO wait]:
internal/poll.runtime_pollWait(0x7fe67e324f70, 0x72, 0x0)
	/root/soft/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc00019e018, 0x72, 0x0, 0x0, 0x9ae68e)
	/root/soft/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/root/soft/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc00019e000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/soft/go/src/internal/poll/fd_unix.go:384 +0x1d4
net.(*netFD).accept(0xc00019e000, 0xe3605a2db7660501, 0xc0003100a0, 0xe3605a2db7660596)
	/root/soft/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc00018c020, 0x5fea98d3, 0xc000188dc8, 0x48b7f6)
	/root/soft/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00018c020, 0xc000188e18, 0x18, 0xc000200f00, 0x6c801c)
	/root/soft/go/src/net/tcpsock.go:261 +0x64
net/http.(*Server).Serve(0xc000220000, 0xa610c0, 0xc00018c020, 0x0, 0x0)
	/root/soft/go/src/net/http/server.go:2901 +0x25d
net/http.(*Server).ListenAndServe(0xc000220000, 0x0, 0x0)
	/root/soft/go/src/net/http/server.go:2830 +0xb7
main.serveWeb.func1(0xc000220000)
	/root/TDengine-develop/alert/cmd/alert/main.go:44 +0x2f
created by main.serveWeb
	/root/TDengine-develop/alert/cmd/alert/main.go:43 +0x199

goroutine 21 [syscall]:
os/signal.signal_recv(0x0)
	/root/soft/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/root/soft/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.Notify.func1
	/root/soft/go/src/os/signal/signal.go:127 +0x44

**Comment by localvar** [comment]
用这种方式调试，难度有点太高了。
另外，您前后两次贴的信息应该不是同一个版本的程序生成的，第一次的程序版本比较新。

**Comment by shuanger051** [comment]
这个问题，我也经常遇到。我们还发现了一个必现的过程，之前我已经提缺陷了。issue 编号 4078

**Comment by huskar-t** [comment]
@nzxxs4 @shuanger051 try to update the go-driver version

**Comment by fenghuazzm** [comment]
Closing this issue since there is no response for too many days.
