### ISSUE TITLE
error while loading shared libraries: libtaos.so.1 

### ISSUE THREAD

**Issue by nieaowei** [taosdata/TDengine#475]
os: centos7
version: taos-1.6.1.7-linux-2019-08-22-17-35.tar.gz (3.0M)

**Comment by fangpanpan** [comment]
Could you provide more information about this error? Like your operation (start taosd?), error information displayed on the screen? Have you installed taosd before and this time you installed a new version?

**Comment by songtianyi** [comment]
有人解决嘛

**Comment by fangpanpan** [comment]
> 有人解决嘛
Could you provide more information about the error? How could we repeat this error? Such information can help us figure out the problem.

**Comment by songtianyi** [comment]
[rust]# rpm -q tdengine
tdengine-1.6.3.0-3.x86_64
[rust]# cargo run --example subscribe
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/examples/subscribe`
target/debug/examples/subscribe: error while loading shared libraries: libtaos.so.1: cannot open shared object file: No such file or directory
[rust]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[rust]# cat /proc/version
Linux version 3.10.0-693.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Tue Aug 22 21:09:27 UTC 2017
[root@nap-99 rust]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by songtianyi** [comment]
在上述环境下，按照rust的example里的Readme里写的命令执行，出现这个错误。

**Comment by fangpanpan** [comment]
您在/usr/local/taos/driver/ 下面能找到类似 libtaos.so.1.6.3.0 以及在/usr/lib/下面能找到libtaos.so.1 （会软连接到/usr/local/taos/driver/下面的那个libtaos.so)  和 libtaos.so 这个文件吗？

**Comment by songtianyi** [comment]
# find . -name libtaos.so*
./usr/lib/libtaos.so.1
./usr/lib/libtaos.so
./usr/local/taos/driver/libtaos.so.1.6.3.0

**Comment by fangpanpan** [comment]
> # find . -name libtaos.so*
> ./usr/lib/libtaos.so.1
> ./usr/lib/libtaos.so
> ./usr/local/taos/driver/libtaos.so.1.6.3.0

那您看看libtaos.so.1 的软连接是否正确连接到了最下面的libtaosso.1.6.3.0?

**Comment by songtianyi** [comment]
你们ci用的啥环境

**Comment by fangpanpan** [comment]
> 你们ci用的啥环境

ubuntu 和centos 都用。通常这个动态库是libtaos.so 软连接到libtaos.so.1, libtaos.so.1 软连接到 /usr/local/taos/driver/libtaos.so.1.6.*.*. 现在您的动态库文件存在，那就是找不到了。

**Comment by chuannull** [comment]
> > 你们ci用的啥环境
> 
> ubuntu 和centos 都用。通常这个动态库是libtaos.so 软连接到libtaos.so.1, libtaos.so.1 软连接到 /usr/local/taos/driver/libtaos.so.1.6._._. 现在您的动态库文件存在，那就是找不到了。您可以参考一下这个添加路径[https://github.com/taosdata/TDengine/issues/484](url)

你好, 你发的链接找不到了, 有其他的说明吗?我和提问者情况一样
