### ISSUE TITLE
start the service fail

### ISSUE THREAD

**Issue by flzx3qc** [taosdata/TDengine#476]
use taosd command to start service,then failed.The error log is shown below:
09/08 14:55:05.324749 7f31f1a17740 UTL timezone not configured, set to system default: (CST, +0800)
09/08 14:55:05.324852 7f31f1a17740 UTL locale not configured, set to system default:en_US.UTF-8
09/08 14:55:05.324879 7f31f1a17740 UTL charset not configured, set to system default:UTF-8
09/08 14:55:05.324963 7f31f1a17740 ERROR DND failed to lock file:/var/lib/taos/.running ret:-1, database may be running, quit

**Comment by elephantjohn** [comment]
hi i am meeting the same question,how to resolve this problem?
