### ISSUE TITLE
reason: Vnode memory is full because commit failed

### ISSUE THREAD

**Issue by powersam** [taosdata/TDengine#4761]
Does anyone can help me ?

**Comment by powersam** [comment]
does anyone give me some solution?

**Comment by powersam** [comment]
重启大法也不好使，重启完释放内存依然报错。

**Comment by sangshuduo** [comment]
请参考文档规划硬件资源配置：
https://www.taosdata.com/cn/documentation/administrator/#%E5%AE%B9%E9%87%8F%E8%A7%84%E5%88%92
