### ISSUE TITLE
query performance

### ISSUE THREAD

**Issue by 279zlj** [taosdata/TDengine#4769]
1.创建了一个超级表，数据大概1400W+，全表查询就用了30分钟，怎么优化？
2.修改taos.cfg文件的maxNumOfOrderedRes，修改后重启taosd，输入taosd看里面的配置信息没有修改到

**Comment by sangshuduo** [comment]
1. 具体查询语句是什么？机器配置是什么？表结构？
2. 能否贴一下截图？

**Comment by 279zlj** [comment]
查询语句： select ts, lon, lat, mmsi from dtest.ship where ts > "2018-3-30 15:11:36" and ts < "2018-12-30 15:11:36";
配置：
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          20
MemTotal:       65835692 kB
disk:             2T
三节点：
   id   |           end_point            | vnodes | cores  |    status    |  role   |       create_time       |       offline reason       |
============================================================================================================================================
      1 | 1:6030                       |     32 |     20 | ready        | any     | 2020-11-04 12:13:05.534 |                            |
      2 | 2:6030         |     53 |     32 | ready        | any     | 2020-12-29 15:37:57.811 |                            |
      3 | 3:6030                      |     18 |     12 | ready        | any     | 2020-12-29 15:38:03.250 |                            |

表结构：
![微信截图_20201231094911](https://user-images.githubusercontent.com/34158264/103390083-74dae680-4b4d-11eb-97dc-5742cfcc4bf7.png)

**Comment by 279zlj** [comment]
Field              |        Type        |   Length    |    Note    |
=================================================================================
 ts                             | TIMESTAMP          |           8 |            |
 shipname                       | BINARY             |         180 |            |
 lon                            | FLOAT              |           4 |            |
 lat                            | FLOAT              |           4 |            |
 turn                           | FLOAT              |           4 |            |
 speed                          | FLOAT              |           4 |            |
 course                         | FLOAT              |           4 |            |
 heading                        | INT                |           4 |            |
 ship_width                     | FLOAT              |           4 |            |
 ship_length                    | FLOAT              |           4 |            |
 status_text                    | BINARY             |         120 |            |
 accuracy                       | BOOL               |           1 |            |
 shiptype_text                  | BINARY             |         180 |            |
 category                       | BINARY             |          10 |            |
 mmsi                           | BINARY             |          20 | TAG        |

**Comment by sangshuduo** [comment]
这个语句会查出来多少条记录？30分钟是包含显示输出的时间吗？

**Comment by sangshuduo** [comment]
没有更新，关闭此 issue

**Comment by 279zlj** [comment]
30分钟时包括输出，但是输出csv文件也需要1分多种，数据只有一千万多
