### ISSUE TITLE
DB file corrupted

### ISSUE THREAD

**Issue by gozhhu** [taosdata/TDengine#477]
**Bug Description**
    raise ProgrammingError(CTaosInterface.errStr(self._connection._conn))
taos.error.ProgrammingError: DB file corrupted

**To Reproduce**
1. Run some executions
2. See error

**Environment (please complete the following information):**
 - CentOS 7.0
 - 8G, 2.0G x 2, 25G
 - TDengine Version: 1.6.1.7（我用的是debug version，有详细日志）

**Additional Context**
这是我第二次出错，第一次我以为是硬盘满了才出现的这个问题。于是删掉全部数据重来，结果又出现了。。。

**Comment by effun** [comment]
我也有这个问题，请问你的问题解决了吗，我现在用的版本是1.6.6.2

**Comment by gozhhu** [comment]
没有解决。用了新包似乎没遇到了。

**Comment by effun** [comment]
我已经弃用TDengine了，数据丢得太厉害。

**Comment by sangshuduo** [comment]
请使用新版本试试
