### ISSUE TITLE
data storage is not balance, only one node be used --version 2.0.8.2

### ISSUE THREAD

**Issue by powersam** [taosdata/TDengine#4774]
5个TDnode(TD01-TD-5) 
数据目录/u01/taosd

操作 ：
 insert to stb 6亿数据。 
发现问题：
    所有数据只存放在TD04节点，其他4个节点无数据，将TD04 磁盘撑爆。

**Comment by sangshuduo** [comment]
多少个子表？

**Comment by powersam** [comment]
> 多少个子表？

一张子表

**Comment by sangshuduo** [comment]
只是符合设计的行为。

参见官方文档：
“TDengine将一张表（一个数据采集点）的所有数据都存放在一个vnode里，而不会让同一个采集点的数据分布到两个或多个dnode上”
https://www.taosdata.com/cn/documentation/architecture/#%E5%AD%98%E5%82%A8%E6%A8%A1%E5%9E%8B%E4%B8%8E%E6%95%B0%E6%8D%AE%E5%88%86%E5%8C%BA%E3%80%81%E5%88%86%E7%89%87
