### ISSUE TITLE
 cluster IO not balance

### ISSUE THREAD

**Issue by huangbotao** [taosdata/TDengine#4777]
**Bug Description**
版本：2.0.8.0
集群3节点
系统：centos 7.2.x

在写入数据时，集群表现为节点1的负载 = (节点2的负载 + 节点3的负载)

按照官方给的信息，这种负载情况，应该不会持续。集群内部会进行自动负载均衡，默认情况下这个配置是打开的，我这边也检查了配置，确实是打开的。

![image](https://user-images.githubusercontent.com/36856212/103339115-78be2880-4abb-11eb-9bba-f46235ca0c01.png)

**Comment by huangbotao** [comment]
@localvar @sangshuduo  帮忙看下这个问题

**Comment by sangshuduo** [comment]
换新版本再试一下

**Comment by huangbotao** [comment]
这个跟版本有关系吗？

**Comment by sangshuduo** [comment]
我们在不断改进，新版本可能解决了这个问题。如果还有问题，请提供复现步骤。我们会在新版本基础上看如何复现解决。

**Comment by huangbotao** [comment]
理解。TDengine-server-2.0.12.1-Linux-x64.rpm  这个版本是当前最新版本吧？

**Comment by sangshuduo** [comment]
是的。很快会有2.0.13.0 发版
