### ISSUE TITLE
Kubernetes Deploy Mode

### ISSUE THREAD

**Issue by swartz-k** [taosdata/TDengine#4778]
**Is your feature request related to a problem? Please describe.**
Hey all, We wanna use TDengine on Kubernetes. But I dont see any docs，is there any problem runing in k8s or somethings?

**Describe your desired behavior**
As helm chart is popular in kubernetes to deploy service，If can use `helm install tdengine` to install a cluster in kubernetes，that will be wonderful.

**Describe your solutions/suggestions if you've any**
If possible，I can contribute helm chart and test it in my cluster.

**Comment by sangshuduo** [comment]
@swartz-k there are some customers who already deployed TDengine in K8S although so far we don't have an official helm. Any contribution is welcomed. Please let me know if you need some assists from us.

**Comment by swartz-k** [comment]
> @swartz-k there are some customers who already deployed TDengine in K8S although so far we don't have an official helm. Any contribution is welcomed. Please let me know if you need some assists from us.

So kind of you. I have already write a chart to install them. Just thinking If ther is a offical chart will be a nice way to use it.

**Comment by dullduck** [comment]
@swartz-k  can you share your helm charts for  TDengine？

**Comment by uk0** [comment]
see .http://firsh.me/2021/04/23/tdengine-on-k8s/
