### ISSUE TITLE
locale charset设置报错

### ISSUE THREAD

**Issue by always-james** [taosdata/TDengine#478]
@zimengpan 
您好，在使用taos时遇到如下问题：
创建数据库连接不成功，提示如下错误：
09/08 17:13:56.050000 0x3857472 TSC failed to set locale:en_US.UTF-8, restore locale:
09/08 17:13:56.050000 0x3857472 TSC charset:936 is not valid in locale, charset remains:

代码中配置如下：
connProps.setProperty(TSDBDriver.PROPERTY_KEY_USER, "root");
connProps.setProperty(TSDBDriver.PROPERTY_KEY_PASSWORD, "taosdata");
connProps.setProperty(TSDBDriver.PROPERTY_KEY_CONFIG_DIR, "/etc/taos");
connProps.setProperty(TSDBDriver.PROPERTY_KEY_CHARSET, "UTF-8");
connProps.setProperty(TSDBDriver.PROPERTY_KEY_LOCALE, "en_US.UTF-8");
connProps.setProperty(TSDBDriver.PROPERTY_KEY_TIME_ZONE, "UTC+8");
不知道"locale"、"charset"和“timezone"该如何设置值，通过跟踪代码发现，如果不设置，就取系统默认的Charset、Locale、TimeZone，但不设置值也会报错。
通过调用Java API：Charset、Locale、TimeZone得到具体的名称设置在代码中，依然会报设置的值不正确。
那么这三个设置项的值该如何参考呢？
谢谢。

**Comment by zimengpan** [comment]
请参考#397 #273

**Comment by always-james** [comment]
您好，问题依然存在，附件是服务器端的配置文件。
[taos.zip](https://github.com/taosdata/TDengine/files/3589283/taos.zip)
代码调试，是在TSDBJNIConnector类的initImp(configDir);失败的：
![image](https://user-images.githubusercontent.com/30729482/64512113-444bb980-d318-11e9-9885-60b6a3bce5f7.png)
切换了几个不同的Locale，报同样的错：
在Linux上执行 locale -a:
zh_CN
zh_CN.gb18030
zh_CN.gb2312
zh_CN.gbk
zh_CN.utf8
尝试在代码中切换这些值，同时在配置文件中也做相应的修改，也报错：
![image](https://user-images.githubusercontent.com/30729482/64512284-9db3e880-d318-11e9-938b-ccd3d951e263.png)

**Comment by always-james** [comment]
代码：
![1568016168(1)](https://user-images.githubusercontent.com/30729482/64513511-48c5a180-d31b-11e9-9f7d-c4d6471b3eee.jpg)

**Comment by whljava** [comment]
你的问题现在解决了吗？我也是这个问题我纠结好久了

**Comment by hjxilinx** [comment]
@always-james 
please check if your Linux system support the locale you have specified in java code.
by using  command.

>locale

 The output of command 

>locale -a

is not recommended.

**Comment by hjxilinx** [comment]
@always-james ,可否将您的错误日志完整的贴出来看看。
