### ISSUE TITLE
Query interrupted (No such file or directory), 0 row(s) in set (0.001022s)

### ISSUE THREAD

**Issue by chuangtim** [taosdata/TDengine#4786]
`taosd version: 2.0.6.0`

> 使用以下命令操作后出现数据全部丢失并且无法写入

`alter database test keep 7;`

> 异常以下：

`Query interrupted (No such file or directory), 0 row(s) in set (0.001022s)
`

**Comment by sangshuduo** [comment]
新版本有这个问题吗？

**Comment by chuangtim** [comment]
目前没办法使用新版本，2.0.6.0以上没办法支持nodejs,nodejs客户端库不支持

**Comment by sangshuduo** [comment]
不太理解 2.0.6.0 以上没法支持 nodejs 的说法是哪里来的。参见：https://www.taosdata.com/cn/documentation/connector/#Node.js-Connector

**Comment by hjxilinx** [comment]
可以升级到最新的版本，最新的版本已经修复了 nodejs 的所有问题。
