### ISSUE TITLE
td2.0-connector 2.0.4 failed to connect 2.0.12.1 

### ISSUE THREAD

**Issue by chuangtim** [taosdata/TDengine#4789]

**Comment by sangshuduo** [comment]
td2.0-connector 2.0.4 连 2.0.12.1 没问题。
出的错误信息是什么？单机本地测试还是连另外一台服务器？

**Comment by chuangtim** [comment]
连另外一台服务器，测试过有问题，2.0.4连2.0.6没问题

**Comment by sangshuduo** [comment]
@chuangtim 没有任何出错信息描述，我们也帮不上忙啊。我这边看是没问题的。
