### ISSUE TITLE
No result return when filtering by timestamp, while actually data exists in the table.

### ISSUE THREAD

**Issue by vinnyyou** [taosdata/TDengine#479]
taos> select * from meters limit 5;
          ts          |    f1     |    f2     |    f3     |  areaid   |   loc    |
==================================================================================
 17-07-14 10:40:00.000|          5|          3|          1|          1|beijing   |
 17-07-14 10:40:00.001|          9|          1|          6|          1|beijing   |
 17-07-14 10:40:00.002|          9|          4|          0|          1|beijing   |
 17-07-14 10:40:00.003|          6|          9|          1|          1|beijing   |
 17-07-14 10:40:00.004|          5|          5|          5|          1|beijing   |
Query OK, 5 row(s) in set (0.025839s)

taos> select * from meters where ts = '17-07-14 10:40:00.002';
Query OK, 0 row(s) in set (0.037340s)

**Comment by fangpanpan** [comment]
could you change your timestamp format in your sql query statement like "select * from meters where ts = '**20**17-07-14 10:40:00.002';" and take a try again?

**Comment by vinnyyou** [comment]
taos> select * from meters limit 10;
          ts          |    f1     |    f2     |    f3     |  areaid   |   loc    |
==================================================================================
 17-07-13 22:40:00.000|          5|          3|          1|          1|beijing   |
 17-07-13 22:40:00.001|          9|          1|          6|          1|beijing   |
 17-07-13 22:40:00.002|          9|          4|          0|          1|beijing   |
 17-07-13 22:40:00.003|          6|          9|          1|          1|beijing   |
 17-07-13 22:40:00.004|          5|          5|          5|          1|beijing   |
 17-07-13 22:40:00.005|          4|          4|          9|          1|beijing   |
 17-07-13 22:40:00.006|          8|          6|          3|          1|beijing   |
 17-07-13 22:40:00.007|          0|          5|          2|          1|beijing   |
 17-07-13 22:40:00.008|          3|          2|          9|          1|beijing   |
 17-07-13 22:40:00.009|          2|          5|          8|          1|beijing   |
Query OK, 10 row(s) in set (0.027615s)

taos> select * from meters where ts = '2017-07-13 10:40:00.003';
Query OK, 0 row(s) in set (1.020798s)

It seems it's timezone problem, the current zimezone is America/New_York, when I change it to  Asia/Shanghai, it's correct

**Comment by fangpanpan** [comment]
Glad to hear that the problem is solved. Because the query timestamp is string, we will convert the string to epoch format (according to the taos client time zone) for filtering.
