### ISSUE TITLE
对于TDengine cluster , 单个实例内存的大小是否限制了整个数据库的大小。

### ISSUE THREAD

**Issue by powersam** [taosdata/TDengine#4797]
在实际使用过程当中，发现内存满了之后回出现insert 拒绝的情况，vnode memoery full because commit failed.
当尝试重启或者新增节点的时候重新insert 数据依然是无法insert 

TDengine version 2.0.8.2

**Comment by sangshuduo** [comment]
关于硬件资源规划请参考文档：https://www.taosdata.com/cn/documentation/administrator/#%E5%AE%B9%E9%87%8F%E8%A7%84%E5%88%92
