### ISSUE TITLE
tag值不变的问题

### ISSUE THREAD

**Issue by 419845351** [taosdata/TDengine#4798]
1.超级表建表语句：
create table metric_data_t(measure_time timestamp,value double) tags (metric_code binary(128), producer_code binary(128), device_sn binary(128), channel binary(16), metric_id binary(20));

2.插入数据，sql如下：
insert into A1AC65BC57C6FAF1441DF5CCFB149D3CB using metric_data_t tags('xy_signalpower','szxy','YG123456789085', '' ,'121278')  values (1558519200000,1.99) ;

3.修改tags和values，再次插入数据
insert into A1AC65BC57C6FAF1441DF5CCFB149D3CB using metric_data_t tags('xy_signalpower','szxy','YG123456789085', '' ,'999')  values (1558605600000,2.99) ;

查询插入结果，两天记录的tag值都是121278 。

请问插入数据的时候，tags不会改变吗？

**Comment by jadedrip** [comment]
Tag 是打在表上的，表示这个表的属性，因此一个表只能有一个 Tag。一个超级表可以有多个表。

**Comment by 419845351** [comment]
一个表的tag传入不同的值，结果不变么

**Comment by sangshuduo** [comment]
tag是在表上的，只能通过 alter table 方式修改。参见：https://www.taosdata.com/cn/documentation/taos-sql/#%E8%B6%85%E7%BA%A7%E8%A1%A8-STable-%E4%B8%AD-TAG-%E7%AE%A1%E7%90%86
