### ISSUE TITLE
请问是否有分布式相关的介绍

### ISSUE THREAD

**Issue by XLPE** [taosdata/TDengine#48]
rt

**Comment by jtao1735** [comment]
刚写了一篇博文，对TDengine的分布式做了简单介绍，请看https://www.taosdata.com/blog/2019/07/16/tdengine%e9%9b%86%e7%be%a4%e8%ae%be%e8%ae%a1/

**Comment by XLPE** [comment]
> 刚写了一篇博文，对TDengine的分布式做了简单介绍，请看https://www.taosdata.com/blog/2019/07/16/tdengine%e9%9b%86%e7%be%a4%e8%ae%be%e8%ae%a1/

非常感谢您的分享
