### ISSUE TITLE
how to config the zabbix to use tdengine

### ISSUE THREAD

**Issue by zhouhuicong** [taosdata/TDengine#480]
怎么配置zabbix去使用tdengine

**Comment by guanshengliang** [comment]
There is currently no official solution.

**Comment by zhouhuicong** [comment]
能否将一些创建普通数据库用户和赋权的语法整理一下，线上手册没有找到

> There is currently no official solution.

**Comment by zhouhuicong** [comment]
创建用户查看https://www.taosdata.com/cn/documentation/administrator/#%E7%94%A8%E6%88%B7%E7%AE%A1%E7%90%86
创建的用户默认有所有权限(修改其他用户密码不行)

**Comment by zhouhuicong** [comment]
尝试将测试环境zabbix3.0.20的mysql数据库替换成tdengine ,替换思路创建zabbix库和普通用户，然后建表。目前卡在表结构改造上。 等待官方解决方案（**现在看zabbix这种表结构设置上很难满足tdengine的需要**）
zabbix的表结构设置不满足要求
1）表的第一个字段必须是TIMESTAMP，并且系统自动将其设为主键
所以手工添加TIMESTAMP 
2) 表的每行长度不能超过4096字节；
hosts 表的长度远远超出设置，将所有2048 varchar的长度改成 512 

将建表语句进行了初步改造，仍然不符合tdengine的要求。
cd /usr/share/doc/zabbix-server-mysql-3.0.20 
zcat create.sql.gz  >  create_taos.sql
vi create_taos.sql
将ENGINE=InnoDB全部替换掉
将`全部替换成空
将varchar 全部替换成NCHAR
将integer 全部替换成int 
将text 替换成nchar(256)
去掉PRIMARY KEY (xxxx)
去掉unsigned                           NOT NULL
将索引全部去掉。
![image](https://user-images.githubusercontent.com/40559605/64585473-736f3300-d3cb-11e9-943c-3c8e42e274aa.png)
![image](https://user-images.githubusercontent.com/40559605/64585485-8124b880-d3cb-11e9-8606-5bb66531af59.png)

**Comment by guanshengliang** [comment]
zabbix的适配确实没做过
但是也有考虑过在Devops领域发力，待我们内部评估后确定是否开展。

**Comment by tomcraz** [comment]
> 尝试将测试环境zabbix3.0.20的mysql数据库替换成tdengine ,替换思路创建zabbix库和普通用户，然后建表。目前卡在表结构改造上。 等待官方解决方案（**现在看zabbix这种表结构设置上很难满足tdengine的需要**）
> zabbix的表结构设置不满足要求
> 1）表的第一个字段必须是TIMESTAMP，并且系统自动将其设为主键
> 所以手工添加TIMESTAMP
> 2) 表的每行长度不能超过4096字节；
> hosts 表的长度远远超出设置，将所有2048 varchar的长度改成 512
> 
> 将建表语句进行了初步改造，仍然不符合tdengine的要求。
> cd /usr/share/doc/zabbix-server-mysql-3.0.20
> zcat create.sql.gz > create_taos.sql
> vi create_taos.sql
> 将ENGINE=InnoDB全部替换掉
> 将`全部替换成空
> 将varchar 全部替换成NCHAR
> 将integer 全部替换成int
> 将text 替换成nchar(256)
> 去掉PRIMARY KEY (xxxx)
> 去掉unsigned NOT NULL
> 将索引全部去掉。
> ![image](https://user-images.githubusercontent.com/40559605/64585473-736f3300-d3cb-11e9-943c-3c8e42e274aa.png)
> ![image](https://user-images.githubusercontent.com/40559605/64585485-8124b880-d3cb-11e9-8606-5bb66531af59.png)
问题解决了吗？看了下你的表，建议分成两张或多张表来存；目前看你遇到的问题是一条记录总的长度超过4096了；建议按数据类型分成多张表，比如数据类型的放在一张标里；nchar类型的放在其他表里。

**Comment by tomcraz** [comment]
> > > 这些名字能修改吗
> > > […](#)
> > > ------------------ Original ------------------ From: zhouhuicong <[notifications@github.com](mailto:notifications@github.com)> Date: Thu,Sep 12,2019 7:06 PM To: taosdata/TDengine <[TDengine@noreply.github.com](mailto:TDengine@noreply.github.com)> Cc: tomcraz <[6847267@qq.com](mailto:6847267@qq.com)>, Comment <[comment@noreply.github.com](mailto:comment@noreply.github.com)> Subject: Re: [taosdata/TDengine] how to config the zabbix to use tdengine (#480) ====表名是 uses 也不可以。 CREATE TABLE users ( -> userstimestamp TIMESTAMP , -> userid bigint , -> alias nchar(100) , -> name nchar(100) , -> surname nchar(100) , -> passwd nchar(32) , -> url nchar(255) , -> autologin int , -> autologout int , -> lang nchar(5) , -> refresh int , -> type int , -> theme nchar(128) , -> attempt_failed int , -> attempt_ip nchar(39) , -> attempt_clock int , -> rows_per_page int -> ) ; TSDB error: invalid SQL: syntax error near "users ( userstimestamp timestamp , userid bigint , alias nchar(100) , name " — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
> > 
> > 
> > =======
> > 还是一开始的问题，一旦我改了表结构和表名，我就必须改zabbix的存储逻辑了。
> 
> 现在我只是添加了TIMESTAMP的化，可能还可以比较顺利的能跑起来。 其他的地方改了，肯定就玩不转了。

可以通过修改开源代码，把保留的关键字改了，来规避这个问题：
以users这个关键字来说，如果想把表名为users，可以这样修改：
前提条件：在http://www.hwaci.com/sw/lemon/这里下载lemon.c 和lempar.c，编译出lemon的执行文件。参考https://www.codeproject.com/Articles/1056460/Generating-a-High-Speed-Parser-Part-Lemon
修改步骤：
1.修改src/inc/sql.y里面的66行，把show users和后面的show_users都加上一个s；
2.在src/client/src/tscSQLParser.c 里面把SHOW_USERS改成SHOW_USERSS;
3.在src/inc/tsql.h 113行，SHOW_USERS改成SHOW_USERSS
4.用lemon编译sql.y,把生成的sql.out文件删除，把生成的sql.c移动到src/util/src/
5.把src/util/src/ttokenizer.c 中第81行USERS改成USERSS，TK_USERS改成TK_USERSS
6.把src/inc/sql.h的内容，拷贝粘贴到src/inc/tsqldef.h中#define TDENGINE_TSQLDEF_H 后面，替换原有内容，直到最后#endif
7.再编译TDengine，运行试试，应该可以create table users了
