### ISSUE TITLE
服务端查询时间和客户端查询出来时间不一致

### ISSUE THREAD

**Issue by chuangtim** [taosdata/TDengine#4801]
```
taosd: 2.0.6.0
td2.0-connector: 2.0.4
```

> 服务端
时区配置： Mon, 04 Jan 2021 07:38:29 +0000
查询记录结果如下：
![image](https://user-images.githubusercontent.com/8262851/103512100-23ab5980-4ea3-11eb-80e2-a0d06e70529c.png)
这个结果显示是对

> 客户端
时区配置也是 UTC时区
查询结果代码如下：
![image](https://user-images.githubusercontent.com/8262851/103512236-59e8d900-4ea3-11eb-8972-f2a10730b481.png)
查询结果：
![image](https://user-images.githubusercontent.com/8262851/103512284-6836f500-4ea3-11eb-901e-344f851da5c2.png)

正确结果应该是服务端一致，为啥客户端还要转换？

**Comment by chuangtim** [comment]
从RESTFUL接口测试也是正确
![image](https://user-images.githubusercontent.com/8262851/103513880-763a4500-4ea6-11eb-960f-7f16259cb7b8.png)

**Comment by sangshuduo** [comment]
前面服务端时区设置是什么？
然后客户端的代码+entry.getTimezoneOffset是您自己写的吧？
RESTFul等于是用服务端内置的客户端，所以和服务端结果相同，是符合预期的。

**Comment by chuangtim** [comment]
> 前面服务端时区设置是什么？
> 然后客户端的代码+entry.getTimezoneOffset是您自己写的吧？
> RESTFul等于是用服务端内置的客户端，所以和服务端结果相同，是符合预期的。

对，entry.getTimezoneOffset是我自己写的，entry对象是从td2.0获取，没改动，现在是客户端为啥要转换时间？

**Comment by chuangtim** [comment]
> 前面服务端时区设置是什么？
> 然后客户端的代码+entry.getTimezoneOffset是您自己写的吧？
> RESTFul等于是用服务端内置的客户端，所以和服务端结果相同，是符合预期的。

服务端时区设置UTC时区，cfg文件没修改

**Comment by sangshuduo** [comment]
客户端时区设置是指系统吗？客户端的 taos.cfg 里时区有没有设置？

**Comment by chuangtim** [comment]
> 客户端时区设置是指系统吗？客户端的 taos.cfg 里时区有没有设置？

是的，系统时区就是UTC时区，客户端taos.cfg没修改过

**Comment by chuangtim** [comment]
> > 客户端时区设置是指系统吗？客户端的 taos.cfg 里时区有没有设置？
> 
> 是的，系统时区就是UTC时区，客户端taos.cfg没修改过

**Comment by sangshuduo** [comment]
找到原因所以关闭了？

**Comment by chuangtim** [comment]
> 找到原因所以关闭了？

点错了，没找到原因

**Comment by chuangtim** [comment]
你可以测试下，这个很明显的可以复现出来的

**Comment by sangshuduo** [comment]
我测试了没问题啊，一个Ubuntu 服务器跑 taosd，时区设置为 UTC+0，然后写入数据。在另一台机器，社区设置为CST时区，运行 taos -h <server>，查询，结果显示为+8的时间。修改第二台机器时区为 UTC+0 ，查询，显示和服务器端写入时间相同的时间。使用 tests/examples/nodejs/nodejsChecker.js 写入数据也没有任何错误，都是符合预期的结果。

**Comment by chuangtim** [comment]
不是写数据，你应该读出来显示出来

**Comment by chuangtim** [comment]
使用POSTMAN使用restful查询，显示字符串和timestamp对不上,看最后一条记录，1609779745962和2021-01-04 09:02:25.962对不上，使用转换出来日期对不上
![image](https://user-images.githubusercontent.com/8262851/103522526-78f06680-4eb5-11eb-9efc-794ae8a273b2.png)
![image](https://user-images.githubusercontent.com/8262851/103522578-8ad20980-4eb5-11eb-9037-ae35bebcfe85.png)
