### ISSUE TITLE
所有步骤都配置没问题，也可以ping通但是就是客户端发现不了服务端。

### ISSUE THREAD

**Issue by wennimade** [taosdata/TDengine#4805]
![a649459ebab5a1a36fb71aa73cc36d0](https://user-images.githubusercontent.com/34495919/103537763-f45f1180-4ecf-11eb-9cfb-e84e5499c1de.png)

**Comment by sangshuduo** [comment]
@wennimade 请上传完整 log 文本文件

**Comment by wennimade** [comment]
[taoslog.txt](https://github.com/taosdata/TDengine/files/5767524/taoslog.txt)

**Comment by sangshuduo** [comment]
已解决，防火墙问题
