### ISSUE TITLE
continue query command failed

### ISSUE THREAD

**Issue by hw2499** [taosdata/TDengine#4807]
连续查询语句： create table query_res1 as select avg(avg_current) as avg_c,device_id from tds_device_info interval(1m) ;
这里面tds_device_info是超级表
问题：
数据同步失败。
后台报错信息：
01/04 22:13:19.974140 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 local merge abort due to error occurs, code:success
01/04 22:13:29.218225 0x7fcbf9af8700 TSC ERROR qhandle is NULL
01/04 22:13:29.218274 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 add into queued async res, code:Invalid qhandle
01/04 22:13:29.218281 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 stream:0x7fcbf0000d70, retrieve data failed, code:0x80000201, retry in 11000ms
01/04 22:13:40.233871 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 local merge abort due to error occurs, code:success
01/04 22:13:53.463201 0x7fcbf9af8700 TSC ERROR qhandle is NULL
01/04 22:13:53.463253 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 add into queued async res, code:Invalid qhandle
01/04 22:13:53.463282 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 stream:0x7fcbf0000d70, retrieve data failed, code:0x80000201, retry in 11000ms
01/04 22:14:04.498437 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 local merge abort due to error occurs, code:success
01/04 22:14:17.538497 0x7fcbf9af8700 TSC ERROR qhandle is NULL
01/04 22:14:17.538539 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 add into queued async res, code:Invalid qhandle
01/04 22:14:17.538549 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 stream:0x7fcbf0000d70, retrieve data failed, code:0x80000201, retry in 11000ms
01/04 22:14:28.564385 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 local merge abort due to error occurs, code:success
01/04 22:14:40.768504 0x7fcbf9af8700 TSC ERROR qhandle is NULL
01/04 22:14:40.768553 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 add into queued async res, code:Invalid qhandle
01/04 22:14:40.768562 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 stream:0x7fcbf0000d70, retrieve data failed, code:0x80000201, retry in 11000ms
01/04 22:14:51.796295 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 local merge abort due to error occurs, code:success
01/04 22:15:05.724613 0x7fcbf9af8700 TSC ERROR qhandle is NULL
01/04 22:15:05.724662 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 add into queued async res, code:Invalid qhandle
01/04 22:15:05.724673 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 stream:0x7fcbf0000d70, retrieve data failed, code:0x80000201, retry in 12000ms
01/04 22:15:17.748831 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 local merge abort due to error occurs, code:success
01/04 22:15:29.618946 0x7fcbf9af8700 TSC ERROR qhandle is NULL
01/04 22:15:29.619007 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 add into queued async res, code:Invalid qhandle
01/04 22:15:29.619015 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 stream:0x7fcbf0000d70, retrieve data failed, code:0x80000201, retry in 11000ms
01/04 22:15:40.640106 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 local merge abort due to error occurs, code:success
01/04 22:15:46.804005 0x7fcbf9af8700 TSC ERROR qhandle is NULL
01/04 22:15:46.804056 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 add into queued async res, code:Invalid qhandle
01/04 22:15:46.804064 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 stream:0x7fcbf0000d70, retrieve data failed, code:0x80000201, retry in 11000ms
01/04 22:15:57.824519 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 local merge abort due to error occurs, code:success
01/04 22:16:05.224543 0x7fcbf9af8700 TSC ERROR qhandle is NULL
01/04 22:16:05.224584 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 add into queued async res, code:Invalid qhandle
01/04 22:16:05.224591 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 stream:0x7fcbf0000d70, retrieve data failed, code:0x80000201, retry in 10000ms
01/04 22:16:15.240730 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 local merge abort due to error occurs, code:success
01/04 22:16:32.829022 0x7fcbf9af8700 TSC ERROR qhandle is NULL
01/04 22:16:32.829114 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 add into queued async res, code:Invalid qhandle
01/04 22:16:32.829123 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 stream:0x7fcbf0000d70, retrieve data failed, code:0x80000201, retry in 11000ms
01/04 22:16:43.855709 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 local merge abort due to error occurs, code:success
01/04 22:16:52.639554 0x7fcbf9af8700 TSC ERROR qhandle is NULL
01/04 22:16:52.639602 0x7fcbf9af8700 TSC ERROR 0x7fcbf0003470 add into queued async res, code:Invalid qhandle

**Comment by hjxilinx** [comment]
该问题已经修复，将在本周发布版本中增加该 patch
