### ISSUE TITLE
空间占用的问题

### ISSUE THREAD

**Issue by qihangcom** [taosdata/TDengine#4808]
为什么数据库重启后，空间占用差别特别大呢
如：
重启前：
12K     ./dnode
24K     ./mnode
180M    ./vnode ---这个
36K     ./vnode_bak
重启后：
12K     ./dnode
24K     ./mnode
14M     ./vnode---这个
36K     ./vnode_bak

**Comment by sangshuduo** [comment]
可能是WAL的数据，如果不影响功能可以不必理会。
