### ISSUE TITLE
TAOS_ROW taos_consume(TAOS_SUB *tsub)

### ISSUE THREAD

**Issue by cjjcode** [taosdata/TDengine#481]
文档描述：该函数用来获取订阅的结果，用户应用程序将其置于一个无限循环语句。如果数据库有新记录到达，该API将返回该最新的记录。如果没有新的记录，**该API将阻塞**。如果返回值为空，说明系统出错。

当前现象：jni调用并不会阻塞，希望能提供解决方案或思路。

补充：客户端在windows系统会有此问题，linux符合预期

**Comment by guanshengliang** [comment]
最近会对时间驱动订阅方法进行改造，以便其支持SQL语句和超级表的订阅
将同时修复这个BUG
