### ISSUE TITLE
run same SQL command by RESTful got different result

### ISSUE THREAD

**Issue by Alec01** [taosdata/TDengine#4811]
**Bug Description**
查询历史数据的脚本如下
```sql
select ts, val from fcloudqa.tb4697793856287014912 where ts >= '2020-12-30 03:08:08' and ts <= '2021-01-05 03:08:06' order by ts asc
```

**To Reproduce**
1. 通过rest接口传递上述sql给TdEngine执行，观察返回结果

**Expected Behavior**
结果是一致的，不论调用频次，但实际结果是调用快了，结果少很多，排查原因是TdEngine返回的内容直接少了很多。

**Screenshots**
![截图_20210105142220](https://user-images.githubusercontent.com/20262947/103613389-751a1e00-4f61-11eb-8a8a-2e2df1ef2ba9.gif)

![image](https://user-images.githubusercontent.com/20262947/103613488-98dd6400-4f61-11eb-81ce-2b7793b784ae.png)

![image](https://user-images.githubusercontent.com/20262947/103613534-a85cad00-4f61-11eb-9e9d-d44ee66477d8.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Memory, Intel(R) Core(TM) i5-4590
 
![image](https://user-images.githubusercontent.com/20262947/103613731-0a1d1700-4f62-11eb-83e7-f9474a45a641.png)

 - TDengine Version 2.0.10.0

**Additional Context**

**Comment by sangshuduo** [comment]
请升级到最新版本再看是不是还有这个问题

**Comment by Alec01** [comment]
> 请升级到最新版本再看是不是还有这个问题

今晚升级一下，看看是否能解决

**Comment by Alec01** [comment]
> > 请升级到最新版本再看是不是还有这个问题
> 
> 今晚升级一下，看看是否能解决

已经升级到最新版本 2.0.13.0 ，问题依然存在

**Comment by sangshuduo** [comment]
用 curl 写个脚本测试一下呢？排除一下工具的问题

**Comment by codering** [comment]
有可能是header原因，see #4018

**Comment by Alec01** [comment]
> 有可能是header原因，see #4018

![截图_20210106104628](https://user-images.githubusercontent.com/20262947/103723219-88ce8e80-500c-11eb-9a6c-2784a15a439f.gif)

请查看上面的操作，Header 已经去掉了。可以看到调用快了之后TdEngine返回的结果不同。

**Comment by Alec01** [comment]
> 用 curl 写个脚本测试一下呢？排除一下工具的问题

![image](https://user-images.githubusercontent.com/20262947/103725506-b407ac80-5011-11eb-837d-de0016b09322.png)

![image](https://user-images.githubusercontent.com/20262947/103725540-c681e600-5011-11eb-9dd5-42f6c884b1c0.png)

![image](https://user-images.githubusercontent.com/20262947/103725555-cd105d80-5011-11eb-8235-3e5d7c3338e4.png)

![image](https://user-images.githubusercontent.com/20262947/103725566-d3063e80-5011-11eb-9980-eef823c49478.png)

curl 抓包的结果，一样的sql 不一样的返回值。

**Comment by sangshuduo** [comment]
是单机部署还是集群？方便远程吗？

**Comment by Alec01** [comment]
curl 比较特殊，一个命令跑完了就没了。不存在HttpClient并发的机会。

大部分定制化服务在调用RestAPI时会单例一个HttpClient或者使用HttpClientFactory重复使用，测试发现当单例的HttpClient在高并发调用TDEngine RestAPI的时候会由于调用频次不同，结果也不一样。

定制化服务不太可能每次调用RestAPI时都像curl新开进程并实例化一个HttpClient，因为就算你显示的释放HttpClient，操作系统的socket资源也不会立即释放

参考这里的说明：
https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

所以这个问题不能因为curl命令没问题就不是TdEngine的bug, curl 其实也有问题，比如配合fiddler抓包一样结果不一致。

**Comment by sangshuduo** [comment]
我写了个python的程序起多个进程 RESTful请求 并发查询没有看到有什么不一致问题。感觉这种多次点击的操作很像浏览器刷新网站时没等刷出网页内容再次刷新的内容显示中断。

**Comment by Alec01** [comment]
这个问题通过修改/etc/taos/taos.cfg配置文件中的restfulRowLimit，将其调大后基本每次返回的结果是一样的了
```
restfulRowLimit     614400
```
