### ISSUE TITLE
not find "taos_stmt_num_params" in tao.lib

### ISSUE THREAD

**Issue by wjffsx** [taosdata/TDengine#4817]
**Bug Description**
taos.h 中包含 函数 “”taos_stmt_num_params“ 和 “”taos_stmt_get_param“

链接过程中发现 tao.lib 没有这个函数
 通过 dumpbin -exports taos.dll 检查，确实没有发现

         51   32 0002F7A0 taos_stmt_add_batch
         52   33 0002F740 taos_stmt_bind_param
         53   34 0002F660 taos_stmt_close
         54   35 0002F840 taos_stmt_execute
         55   36 0002F140 taos_stmt_init
         56   37 0002F340 taos_stmt_prepare
         57   38 0002F920 taos_stmt_use_result

**Comment by sangshuduo** [comment]
odbc 用的函数接口，如果有修改的好主意，欢迎PR

**Comment by sangshuduo** [comment]
no update. close this issue first. please open it if it needs to be discussed furthermore.
