### ISSUE TITLE
Suggest to add month-on-month & year-on-year comparison feature

### ISSUE THREAD

**Issue by sjqzhang** [taosdata/TDengine#482]
在监控领域同比，环比的需求比较强烈，还有多指标联合查询也比较多（这个是不是可以通过多个where条件来满足？），例如：内存使有率80%，CPU负载大于40%，网络40%以上等多指标联合查询也是比较常见的需求。

**Comment by hjxilinx** [comment]
Thanks for your suggestions. We will consider to take this feature into the roadmap.
