### ISSUE TITLE
libtaos.so cause "A fatal error has been detected by the Java Runtime Environment"

### ISSUE THREAD

**Issue by moziie** [taosdata/TDengine#4820]
linux centos8 and TDengine version 2.0.7.0
项目运行会突然停掉，查看日志发现jvm崩溃了而且可能与调用libtaos.dll有关系，但是具体问题原因不清楚，希望能得到官方专业人员协助搞清楚哪里的问题，部分日志内容如下：

 A fatal error has been detected by the Java Runtime Environment:
  SIGSEGV (0xb) at pc=0x00007fb2bfeffb84, pid=3599518, tid=0x00007fb184df9700
 JRE version: OpenJDK Runtime Environment (8.0_262-b10) (build 1.8.0_262-b10)
 Java VM: OpenJDK 64-Bit Server VM (25.262-b10 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 C  [libpthread.so.0+0xfb84]  pthread_cancel+0x4
 Core dump written. Default location: /home/xmm/fanwu-datamonitor/target/core or core.3599518

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

Stack: [0x00007fb184cf9000,0x00007f

b184dfa000],  sp=0x00007fb184df84b8,  free space=1021k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libpthread.so.0+0xfb84]  pthread_cancel+0x4
C  [libtaos.so+0x1217ff]  taosCleanUpTcpClient+0x65
C  [libtaos.so+0x11ad08]  rpcClose+0x101
C  [libtaos.so+0x3a3af]  tscCloseTscObj+0x61
C  [libtaos.so+0x13c574]  taosReleaseRef+0x1f5
C  [libtaos.so+0x89157]  taos_close+0x2ac
C  [libtaos.so+0x2ed39]  Java_com_taosdata_jdbc_TSDBJNIConnector_closeConnectionImp+0xc5
J 20914  com.taosdata.jdbc.TSDBJNIConnector.closeConnectionImp(J)I (0 bytes) @ 0x00007fb2aa664d70 [0x00007fb2aa664cc0+0xb0]
J 20913 C1 com.taosdata.jdbc.TSDBJNIConnector.closeConnection()V (55 bytes) @ 0x00007fb2a98e2cec [0x00007fb2a98e2c60+0x8c]
J 20912 C1 com.taosdata.jdbc.TSDBConnection.close()V (41 bytes) @ 0x00007fb2a98e370c [0x00007fb2a98e3540+0x1cc]
J 20591 C1 com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(Ljava/sql/Connection;Ljava/lang/String;)V (113 bytes) @ 0x00007fb2ac8dea1c [0x00007fb2ac8de220+0x7fc]
J 20616 C1 com.zaxxer.hikari.pool.HikariPool$$Lambda$1256.run()V (16 bytes) @ 0x00007fb2ab08f6bc [0x00007fb2ab08f560+0x15c]
J 22895 C2 java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (225 bytes) @ 0x00007fb2ababbcf4 [0x00007fb2ababbb80+0x174]
J 20305 C1 java.util.concurrent.ThreadPoolExecutor$Worker.run()V (9 bytes) @ 0x00007fb2a9a1f004 [0x00007fb2a9a1ef00+0x104]
J 20274 C1 java.lang.Thread.run()V (17 bytes) @ 0x00007fb2ab039544 [0x00007fb2ab039400+0x144]
v  ~StubRoutines::call_stub
V  [libjvm.so+0x69f7e5]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0xc55
V  [libjvm.so+0x69cf4f]  JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*)+0x27f
V  [libjvm.so+0x69d507]  JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*)+0x77
V  [libjvm.so+0x739c8f]  thread_entry(JavaThread*, Thread*)+0x7f
V  [libjvm.so+0xb2aefc]  JavaThread::thread_main_inner()+0x20c
V  [libjvm.so+0xb2b269]  JavaThread::run()+0x309
V  [libjvm.so+0x9544d2]  java_start(Thread*)+0x162
C  [libpthread.so.0+0x82de]  start_thread+0xfe

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 20914  com.taosdata.jdbc.TSDBJNIConnector.closeConnectionImp(J)I (0 bytes) @ 0x00007fb2aa664cf8 [0x00007fb2aa664cc0+0x38]
J 20913 C1 com.taosdata.jdbc.TSDBJNIConnector.closeConnection()V (55 bytes) @ 0x00007fb2a98e2cec [0x00007fb2a98e2c60+0x8c]
J 20912 C1 com.taosdata.jdbc.TSDBConnection.close()V (41 bytes) @ 0x00007fb2a98e370c [0x00007fb2a98e3540+0x1cc]
J 20591 C1 com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(Ljava/sql/Connection;Ljava/lang/String;)V (113 bytes) @ 0x00007fb2ac8dea1c [0x00007fb2ac8de220+0x7fc]
J 20616 C1 com.zaxxer.hikari.pool.HikariPool$$Lambda$1256.run()V (16 bytes) @ 0x00007fb2ab08f6bc [0x00007fb2ab08f560+0x15c]
J 22895 C2 java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (225 bytes) @ 0x00007fb2ababbcf4 [0x00007fb2ababbb80+0x174]
J 20305 C1 java.util.concurrent.ThreadPoolExecutor$Worker.run()V (9 bytes) @ 0x00007fb2a9a1f004 [0x00007fb2a9a1ef00+0x104]
J 20274 C1 java.lang.Thread.run()V (17 bytes) @ 0x00007fb2ab039544 [0x00007fb2ab039400+0x144]
v  ~StubRoutines::call_stub
[hs_err_pid3599518.log](https://github.com/taosdata/TDengine/files/5768970/hs_err_pid3599518.log)

**Comment by sangshuduo** [comment]
请升级到TDengine最新版本和 JDBC driver 2.0.15
