### ISSUE TITLE
The write speed of a cluster is decreased

### ISSUE THREAD

**Issue by jadedrip** [taosdata/TDengine#4833]
3台机器组成集群，taro.cfg 中 quorum=1，numOfMnodes=2，replica=2
数据库的 replica 也为 2

1. Minimal reproduce step (Required)
暂停任意一台机器的 tado 模拟宕机

2. What did you expect to see? (Required)
写入速度影响不大

3. What did you see instead (Required)
写入速度骤降，每条写入的 sql 执行时间达到秒级。

特别的，同一链接，如果写入过一次的表（不是超级表），再次写入速度会很快，但当尝试写入另一张新表时又很慢（秒级）。直接使用 taos 客户端即可测试。

4. What is your TDengine version? (Required)
v2.0.13.0

**Comment by sunshine-smdbs** [comment]
请问，写入数据的模型是怎么样的？多少个超级表，每个超级表有多少个子表，子表的宽度是多少？

----

Excuse me, what is the model for writing data? How many super tables, how many sub tables does each super table have, and what is the width of the sub tables?

**Comment by jadedrip** [comment]
和表的数据量完全没关系，全新的超级表就是这样。测试只要集群停一台机器，然后直接用 taos 客户端随便写一条数据就可以发现了。

**Comment by sunshine-smdbs** [comment]
👌已复现

**Comment by sunshine-smdbs** [comment]
@jadedrip 2.0.15.0 已改进，请尝试。
--------------
Version 2.0.15.0 Has improved this problem, please have a try.

**Comment by jadedrip** [comment]
@sunshine-smdbs 升级到 2.0.15.0 了，反而不对了啊。
停一台机器的情况下，数据写入直接超时失败了
![image](https://user-images.githubusercontent.com/2951787/106422113-f6010280-6498-11eb-86b1-ca94e79b207b.png)
![image](https://user-images.githubusercontent.com/2951787/106422138-02855b00-6499-11eb-9df2-477c42d1b04f.png)

**Comment by jadedrip** [comment]
但是很奇怪的是，我后来又试了一几次次，又正常了。

**Comment by jadedrip** [comment]
![image](https://user-images.githubusercontent.com/2951787/106424358-01562d00-649d-11eb-918b-05ab06b69688.png)
反复测试了几次，目前观察到的情况，三台里停下某台，会导致某些写入变长，长的能到几十秒，然后过一会儿貌似就好了。
比以前的情况好了些。

**Comment by sunshine-smdbs** [comment]
是的，这里有个sync的机制问题。后续会有更彻底的解决。
