### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by xiangxud** [taosdata/TDengine#4839]
**Bug Description**

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**
cd /home/TDengine/debug/src/kit/taosdemox && /usr/bin/cmake3 -E cmake_link_script CMakeFiles/taosdemox.dir/link.txt --verbose=1
/bin/cc -g -std=gnu99 -Wall -Werror -fPIC -gdwarf-2 -msse4.2 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILE -O0 -g3 -DDEBUG  -rdynamic CMakeFiles/taosdemox.dir/taosdemox.c.o  -o ../../../build/bin/taosdemox  -Wl,-rpath,/home/TDengine/debug/build/lib ../../../../deps/libcurl/lib/libcurl.a ../../../build/lib/libtaos.so.2.0.13.0 ../../../build/lib/libcJson.a ../../../build/lib/libquery.a ../../../build/lib/libtsdb.a ../../../build/lib/libtrpc.a ../../../build/lib/libcommon.a ../../../build/lib/libtutil.a ../../../build/lib/liblz4.a ../../../build/lib/libosdetail.a ../../../build/lib/libos.a ../../../build/lib/libz.a -lpthread -lm -lrt 
/bin/ld: ../../../../deps/libcurl/lib/libcurl.a(libcurl_la-http.o): unrecognized relocation (0x2a) in section `.text'
/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
gmake[2]: *** [build/bin/taosdemox] Error 1
gmake[2]: Leaving directory `/home/TDengine/debug'
gmake[1]: *** [src/kit/taosdemox/CMakeFiles/taosdemox.dir/all] Error 2
gmake[1]: Leaving directory `/home/TDengine/debug'
gmake: *** [all] Error 2
[root@node1 debug]#

**Comment by sangshuduo** [comment]
gcc, cmake, make 版本号是多少？

**Comment by xiangxud** [comment]
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
cmake3 version 3.17.3
GNU Make 3.82

**Comment by sangshuduo** [comment]
我这没问题

1. docker pull centos:7
2. docker run -dit --name centos7 centos:7 bash
3. docker exec -it centos7 bash
4. yum install epel-release
5. yum install gcc gcc-c++ git cmake3 make git
6. git clone https://github.com/taosdata/TDengine
7. cd TDengine
8. mkdir TDengine
9. cmakd3 ..
10. make

![image](https://user-images.githubusercontent.com/825729/103843971-d3670e00-50d3-11eb-8af5-8dca83d72909.png)

**Comment by xiangxud** [comment]
mkdir debug &amp;&amp; cd debug cmake .. &amp;&amp; cmake --build 我执行的命令



---Original---

**Comment by sangshuduo** [comment]
是不是您的系统里同时装了 cmake 和 cmake3 两个包啊？centos 里面要装 cmake3 才有 3.x ，还有一个 cmake 是2.x，所以我执行了 cmake3 ..

**Comment by sangshuduo** [comment]
no update so close this issue.

**Comment by xiangxud** [comment]
vmware15+centos7 not success,vmware+ubuntu18 ok

**Comment by sangshuduo** [comment]
@xiangxud 你再 pull 一下 develop 分支，对 cmake 版本作了强制限制最低 3.5 ，然后看出错信息是什么

**Comment by xiangxud** [comment]
Scanning dependencies of target taosdemox
make[2]: Leaving directory `/home/TDengine/debug'
make  -f src/kit/taosdemox/CMakeFiles/taosdemox.dir/build.make src/kit/taosdemox/CMakeFiles/taosdemox.dir/build
make[2]: Entering directory `/home/TDengine/debug'
[ 62%] Building C object src/kit/taosdemox/CMakeFiles/taosdemox.dir/taosdemox.c.o
cd /home/TDengine/debug/src/kit/taosdemox && /bin/cc -DLINUX -DTD_LOWA_CURL -DUSE_LIBICONV -D_LIBC_REENTRANT -D_LINUX -D_MQTT -D_M_X64 -D_REENTRANT -D_TD_LINUX -D_TD_LINUX_64 -D__USE_POSIX -I/home/TDengine/deps/cJson/inc -I/home/TDengine/deps/lz4/inc -I/home/TDengine/src/inc -I/home/TDengine/src/os/inc -I/home/TDengine/src/util/inc -I/home/TDengine/src/common/inc -I/home/TDengine/src/client/inc -I/home/TDengine/deps/libcurl/include  -g -std=gnu99 -Wall -Werror -fPIC -gdwarf-2 -msse4.2 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILE -O0 -g3 -DDEBUG   -std=gnu11 -o CMakeFiles/taosdemox.dir/taosdemox.c.o   -c /home/TDengine/src/kit/taosdemox/taosdemox.c
[ 62%] Linking C executable ../../../build/bin/taosdemox
cd /home/TDengine/debug/src/kit/taosdemox && /usr/bin/cmake3 -E cmake_link_script CMakeFiles/taosdemox.dir/link.txt --verbose=1
/bin/cc -g -std=gnu99 -Wall -Werror -fPIC -gdwarf-2 -msse4.2 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILE -O0 -g3 -DDEBUG   CMakeFiles/taosdemox.dir/taosdemox.c.o  -o ../../../build/bin/taosdemox  -Wl,-rpath,/home/TDengine/debug/build/lib ../../../../deps/libcurl/lib/libcurl.a ../../../build/lib/libtaos.so.2.0.13.0 ../../../build/lib/libcJson.a ../../../build/lib/libquery.a ../../../build/lib/libtsdb.a ../../../build/lib/libtrpc.a ../../../build/lib/libcommon.a ../../../build/lib/libtutil.a ../../../build/lib/liblz4.a ../../../build/lib/libosdetail.a ../../../build/lib/libos.a ../../../build/lib/libz.a -lpthread -lm -lrt 
/bin/ld: ../../../../deps/libcurl/lib/libcurl.a(libcurl_la-http.o): unrecognized relocation (0x2a) in section `.text'
/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [build/bin/taosdemox] Error 1
make[2]: Leaving directory `/home/TDengine/debug'
make[1]: *** [src/kit/taosdemox/CMakeFiles/taosdemox.dir/all] Error 2
make[1]: Leaving directory `/home/TDengine/debug'
make: *** [all] Error 2
[root@node1 debug]#

**Comment by sangshuduo** [comment]
binutils >=2.26

**Comment by xiangxud** [comment]
yum install binutils  ,更新到2.27版后编译成功了
