### ISSUE TITLE
about python connector

### ISSUE THREAD

**Issue by nieyuanqing** [taosdata/TDengine#4840]
通过Python访问TDengine连接问题：
是每次访问创建一个连接：conn = taos.connect(host="127.0.0.1", user="root", password="taosdata", config="/etc/taos")
还是创建连接后一直持有，持续使用？
如果连接出现异常呢，怎么检测？

TDengine是否有类似mysql连接池相同的机制的Connector？

**Comment by xiaopingcs** [comment]
创建一个连接成功之后， 可以持续使用，如果使用了conn.close()这个方法，连接会被关闭掉，无法使用。
连接出现异常使用正常的try, except就可以捕获。

连接池 python的我们没有用过，不过java连接器是可以支持和连接池一起使用的，可以参考这个文档：https://www.taosdata.com/cn//documentation20/connector-java/
