### ISSUE TITLE
移植TDengine到32位ARM上

### ISSUE THREAD

**Issue by subjectxbj** [taosdata/TDengine#485]
花了一天时间移植TDengine到32位ARM系统上，基于musl libc.

现在taosd跑起来了
···
[develop] ~/TDengine/build/build/bin # uname -a
Linux develop 4.4.60 #2 SMP PREEMPT Wed Sep 4 19:24:03 UTC 2019 armv7l Linux

[develop] ~/TDengine/build/build/bin # ./taosd &
[develop] ~/TDengine/build/build/bin # 09/09 09:28:31.289221 76f584d8 ERROR UTL open file:/proc/3649/io failed
09/09 09:28:31.289285 76f584d8 UTL timezone not configured, set to system default: (UTC, +0000)
09/09 09:28:31.289306 76f584d8 UTL locale not configured, set to system default:C.UTF-8
09/09 09:28:31.289325 76f584d8 UTL charset not configured, set to system default:UTF-8
09/09 09:28:31.289448 76f584d8 UTL    taos config & system info:
09/09 09:28:31.289464 76f584d8 UTL ==================================
09/09 09:28:31.289479 76f584d8 UTL  internalIp:             192.168.1.215
09/09 09:28:31.289501 76f584d8 UTL  serverIp:               0.0.0.0
09/09 09:28:31.289515 76f584d8 UTL  localIp:                0.0.0.0
09/09 09:28:31.289533 76f584d8 UTL  httpIp:                 0.0.0.0
09/09 09:28:31.289548 76f584d8 UTL  httpPort:               6020
09/09 09:28:31.289567 76f584d8 UTL  mgmtShellPort:          6030
09/09 09:28:31.289581 76f584d8 UTL  vnodeShellPort:         6035
09/09 09:28:31.289599 76f584d8 UTL  configDir:              /etc/taos
09/09 09:28:31.289613 76f584d8 UTL  dataDir:                /var/lib/taos
09/09 09:28:31.289630 76f584d8 UTL  logDir:                 /var/log/taos
09/09 09:28:31.289644 76f584d8 UTL  scriptDir:              /etc/taos
09/09 09:28:31.289658 76f584d8 UTL  numOfThreadsPerCore:    1.000000
09/09 09:28:31.289676 76f584d8 UTL  ratioOfQueryThreads:    0.500000
09/09 09:28:31.289693 76f584d8 UTL  numOfVnodesPerCore:     8
09/09 09:28:31.289707 76f584d8 UTL  numOfTotalVnodes:       0
09/09 09:28:31.289723 76f584d8 UTL  tables:                 1000
09/09 09:28:31.289737 76f584d8 UTL  cache:                  16384(byte)
09/09 09:28:31.289753 76f584d8 UTL  rows:                   4096
09/09 09:28:31.289768 76f584d8 UTL  fileBlockMinPercent:    0.050000
09/09 09:28:31.289783 76f584d8 UTL  ablocks:                4
09/09 09:28:31.289799 76f584d8 UTL  tblocks:                100
09/09 09:28:31.289813 76f584d8 UTL  monitorInterval:        30(s)
09/09 09:28:31.289829 76f584d8 UTL  rpcTimer:               300(ms)
09/09 09:28:31.289843 76f584d8 UTL  rpcMaxTime:             600(s)
09/09 09:28:31.289859 76f584d8 UTL  ctime:                  3600(s)
09/09 09:28:31.289873 76f584d8 UTL  statusInterval:         1(s)
09/09 09:28:31.289889 76f584d8 UTL  shellActivityTimer:     3(s)
09/09 09:28:31.289903 76f584d8 UTL  meterMetaKeepTimer:     7200(s)
09/09 09:28:31.289919 76f584d8 UTL  metricMetaKeepTimer:    600(s)
09/09 09:28:31.289932 76f584d8 UTL  maxUsers:               1000
09/09 09:28:31.289948 76f584d8 UTL  maxDbs:                 1000
09/09 09:28:31.289962 76f584d8 UTL  maxTables:              650000
09/09 09:28:31.289978 76f584d8 UTL  maxVGroups:             1000
09/09 09:28:31.289992 76f584d8 UTL  minSlidingTime:         10(ms)
09/09 09:28:31.290008 76f584d8 UTL  minIntervalTime:        10(ms)
09/09 09:28:31.290021 76f584d8 UTL  maxStreamCompDelay:     20000(ms)
09/09 09:28:31.290035 76f584d8 UTL  maxFirstStreamCompDelay:10000(ms)
09/09 09:28:31.290049 76f584d8 UTL  retryStreamCompDelay:   10(ms)
09/09 09:28:31.290064 76f584d8 UTL  clog:                   1
09/09 09:28:31.290078 76f584d8 UTL  comp:                   2
09/09 09:28:31.290093 76f584d8 UTL  days:                   10
09/09 09:28:31.290106 76f584d8 UTL  keep:                   3650
09/09 09:28:31.290122 76f584d8 UTL  defaultDB:
09/09 09:28:31.290135 76f584d8 UTL  defaultUser:            root
09/09 09:28:31.290150 76f584d8 UTL  timezone:                (UTC, +0000)
09/09 09:28:31.290165 76f584d8 UTL  locale:                 C.UTF-8
09/09 09:28:31.290180 76f584d8 UTL  charset:                UTF-8
09/09 09:28:31.290193 76f584d8 UTL  maxShellConns:          2000
09/09 09:28:31.290209 76f584d8 UTL  maxMeterConnections:    10000
09/09 09:28:31.290223 76f584d8 UTL  maxMgmtConnections:     2000
09/09 09:28:31.290239 76f584d8 UTL  maxVnodeConnections:    10000
09/09 09:28:31.290252 76f584d8 UTL  minimalLogDirGB:        0.100000(GB)
09/09 09:28:31.290270 76f584d8 UTL  minimalTmpDirGB:        0.100000(GB)
09/09 09:28:31.290289 76f584d8 UTL  minimalDataDirGB:       0.500000(GB)
09/09 09:28:31.290313 76f584d8 UTL  enableHttp:             1
09/09 09:28:31.290331 76f584d8 UTL  enableMonitor:          1
09/09 09:28:31.290345 76f584d8 UTL  httpCacheSessions:      100
09/09 09:28:31.290358 76f584d8 UTL  telegrafUseFieldNum:    0
09/09 09:28:31.290373 76f584d8 UTL  httpMaxThreads:         2
09/09 09:28:31.290387 76f584d8 UTL  httpEnableCompress:     0
09/09 09:28:31.290402 76f584d8 UTL  numOfLogLines:          10000000
09/09 09:28:31.290416 76f584d8 UTL  asyncLog:               1
09/09 09:28:31.290431 76f584d8 UTL  debugFlag:              131
09/09 09:28:31.290445 76f584d8 UTL  mDebugFlag:             135
09/09 09:28:31.290458 76f584d8 UTL  dDebugFlag:             131
09/09 09:28:31.290472 76f584d8 UTL  sdbDebugFlag:           135
09/09 09:28:31.290485 76f584d8 UTL  taosDebugFlag:          131
09/09 09:28:31.290499 76f584d8 UTL  tmrDebugFlag:           131
09/09 09:28:31.290512 76f584d8 UTL  cDebugFlag:             199
09/09 09:28:31.290526 76f584d8 UTL  jniDebugFlag:           131
09/09 09:28:31.290539 76f584d8 UTL  odbcDebugFlag:          131
09/09 09:28:31.290552 76f584d8 UTL  uDebugFlag:             131
09/09 09:28:31.290566 76f584d8 UTL  httpDebugFlag:          131
09/09 09:28:31.290579 76f584d8 UTL  monitorDebugFlag:       131
09/09 09:28:31.290593 76f584d8 UTL  qDebugFlag:             131
09/09 09:28:31.290606 76f584d8 UTL  gitinfo:                44f8a3d73d839b2b840b9c80243ec0edf0f5d5ab
09/09 09:28:31.290621 76f584d8 UTL  buildinfo:              Built by slguan at 2019-08-22 16:51
09/09 09:28:31.290636 76f584d8 UTL  version:                1.6.1.7
09/09 09:28:31.290649 76f584d8 UTL  dataDir:                /var/lib/taos
09/09 09:28:31.290663 76f584d8 UTL  os pageSize:            1422724272(KB)
09/09 09:28:31.290679 76f584d8 UTL  os openMax:             1422724272
09/09 09:28:31.290692 76f584d8 UTL  os streamMax:           1422724272
09/09 09:28:31.290708 76f584d8 UTL  os numOfCores:          4
09/09 09:28:31.290720 76f584d8 UTL  os totalDisk:           28.064709(GB)
09/09 09:28:31.290737 76f584d8 UTL  os totalMemory:         886(MB)
09/09 09:28:31.290751 76f584d8 UTL  os sysname:             Linux
09/09 09:28:31.290765 76f584d8 UTL  os nodename:            develop
09/09 09:28:31.290777 76f584d8 UTL  os release:             4.4.60
09/09 09:28:31.290793 76f584d8 UTL  os version:             #2 SMP PREEMPT Wed Sep 4 19:24:03 UTC 2019
09/09 09:28:31.290806 76f584d8 UTL  os machine:             armv7l
09/09 09:28:31.290820 76f584d8 UTL ==================================
09/09 09:28:31.290833 76f584d8 DND Server IP address is:192.168.1.215
09/09 09:28:31.290857 76f584d8 DND starting to initialize TDengine engine ...
09/09 09:28:31.295978 76f584d8 TSC taos client is initialized successfully
09/09 09:28:31.299136 76f584d8 DND vnode is initialized successfully
09/09 09:28:31.299226 76f584d8 MND starting to initialize TDengine mgmt ...
09/09 09:28:31.300276 76f584d8 MND first access, set total vnodes:50
09/09 09:28:31.344175 76f584d8 MND TDengine mgmt is initialized successfully
09/09 09:28:31.344207 76f584d8 HTP starting to initialize http service ...
09/09 09:28:31.344360 76f584d8 DND TDengine is initialized successfully
09/09 09:28:31.344413 7580ed44 HTP http service init success at ip:0.0.0.0:6020
···

但是跑taos shell发现创建database失败：
···
[develop] ~/TDengine/build/build/bin # ./taos

Welcome to the TDengine shell, client version:1.6.1.7  09/09 09:33:51.709376 76fa64d8 ERROR UTL open file:/proc/3715/io failed
09/09 09:33:51.710004 76fa64d8 TSC starting to initialize TAOS client ...
09/09 09:33:51.710021 76fa64d8 TSC Local IP address is:0.0.0.0
09/09 09:33:51.714891 76fa64d8 TSC taos client is initialized successfully
09/09 09:33:51.714959 76fa64d8 TSC try to create a connection to 0.0.0.0
09/09 09:33:51.715039 76fa64d8 TSC 0x55e57ee0 SQL cmd:28 will be processed, name:
09/09 09:33:51.715077 76fa64d8 TSC 0x55e57ee0 msg:connect is sent to server
09/09 09:33:51.715555 76fa64d8 TSC 0x55e57ee0 send msg ret:117 code:0 sig:0x55e57ee0
09/09 09:33:51.715934 76e81d44 TSC 0x55e57ee0 msg:0x55e58dec is received from server, pConn:0x76b100bc
09/09 09:33:51.715971 76e81d44 TSC 0x55e57ee0 cmd:28 code:0 rsp len:63
09/09 09:33:51.716026 76e81d44 TSC 0x76b100bc ip:0x0:999:1451:0x76a33010 added, connections in cache:1
09/09 09:33:51.716067 76fa64d8 TSC 0x55e57e10 DB connection is opened
server version:1.6.1.7
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

taos> create database db;
09/09 09:34:24.120452 76a32d44 TSC 0x55e57ee0 SQL: create database db; pObj:0x55e57e10
09/09 09:34:24.120637 76a32d44 TSC 0x55e57ee0 SQL cmd:4 will be processed, name:0.db
09/09 09:34:24.120705 76a32d44 TSC 0x76b10214 ip:0x0:999:1451:0x76a33050 removed, connections in cache:0
09/09 09:34:24.120761 76a32d44 TSC 0x55e57ee0 msg:create-db is sent to server
09/09 09:34:24.120953 76a32d44 TSC 0x55e57ee0 send msg ret:237 code:0 sig:0x55e57ee0
09/09 09:34:24.121325 76e81d44 TSC 0x55e57ee0 msg:0x55e6b03c is received from server, pConn:0x76b102c0
09/09 09:34:24.121350 76e81d44 TSC 0x55e57ee0 cmd:4 code:45 rsp len:21
09/09 09:34:24.121371 76e81d44 TSC 0x76b102c0 ip:0x0:999:1451:0x76a33070 added, connections in cache:1
09/09 09:34:24.121420 76a32d44 TSC 0x55e57ee0 SQL result:45, invalid option pObj:0x55e57e10
09/09 09:34:24.121460 76a32d44 TSC 0x55e57ee0 start to free local reducer
09/09 09:34:24.121495 76a32d44 TSC 0x55e57ee0 local reducer has been freed, abort

TSDB error: invalid option

09/09 09:34:24.121561 76a32d44 TSC 0x55e57ee0 start to free result
09/09 09:34:24.121596 76a32d44 TSC 0x55e57ee0 qhandle is null, abort free, fp:0
09/09 09:34:24.121631 76a32d44 TSC 0x55e57ee0 start to free local reducer
09/09 09:34:24.121665 76a32d44 TSC 0x55e57ee0 local reducer has been freed, abort
taos> show databases;
09/09 09:45:01.537459 76a32d44 TSC 0x55e57ee0 SQL: show databases; pObj:0x55e57e10
09/09 09:45:01.537649 76a32d44 TSC 0x55e57ee0 SQL cmd:22 will be processed, name:
09/09 09:45:01.537718 76a32d44 TSC 0x76b102c0 ip:0x0:999:1451:0x76a33070 removed, connections in cache:0
09/09 09:45:01.537775 76a32d44 TSC 0x55e57ee0 msg:show is sent to server
09/09 09:45:01.537990 76a32d44 TSC 0x55e57ee0 send msg ret:149 code:0 sig:0x55e57ee0
09/09 09:45:01.538567 76e6ad44 TSC 0x55e57ee0 msg:0x55e6affc is received from server, pConn:0x76b1036c
09/09 09:45:01.538597 76e6ad44 TSC 0x55e57ee0 cmd:22 code:0 rsp len:1300
09/09 09:45:01.538675 76a32d44 TSC 0x55e57ee0 SQL result:0, success pObj:0x55e57e10
09/09 09:45:01.538836 76a32d44 TSC 0x55e57ee0 SQL cmd:23 will be processed, name:
09/09 09:45:01.538863 76a32d44 TSC 0x55e57ee0 msg:retrieve is sent to server
09/09 09:45:01.539220 76e81d44 TSC 0x55e57ee0 msg:0x55e6b44c is received from server, pConn:0x76b1036c
09/09 09:45:01.539220 76a32d44 TSC 0x55e57ee0 send msg ret:126 code:0 sig:0x55e57ee0
09/09 09:45:01.539265 76e81d44 TSC 0x55e57ee0 cmd:23 code:0 rsp len:43
09/09 09:45:01.539317 76a32d44 TSC 0x76b1036c ip:0x0:999:1451:0x76a33090 added, connections in cache:1
09/09 09:45:01.539342 76a32d44 TSC 0x55e57ee0 start to free result
09/09 09:45:01.539362 76a32d44 TSC 0x55e57ee0 start to free local reducer
09/09 09:45:01.539378 76a32d44 TSC 0x55e57ee0 local reducer has been freed, abort
09/09 09:45:01.539397 76a32d44 TSC 0x55e57ee0 sql result is freed
Query OK, 0 row(s) in set (0.001956s)

taos>
···

感觉还是有问题，代码里面用了很多Not Portable的东西，可移植性需要进一步健全。

**Comment by plum-lihui** [comment]
是的，这个工作我们还在开发排期了。希望后续能一起努力完成arm版本的移植。

**Comment by subjectxbj** [comment]
建议不要仅仅依赖gnu libc，还要考虑兼容musl libc。大量嵌入式系统都是基于musl libc的，代码里面有不少引用的头文件和宏定义只在gnu libc里面有，但是在musl libc里面不存在。
