### ISSUE TITLE
连续查询

### ISSUE THREAD

**Issue by MelodyI** [taosdata/TDengine#4853]
用电统计，用电量递增，统计每天用了多少度电

查询原始用电数据
taos> select * from am5411;
|ts|qa|alarm|
|---|---|---|
| 2020-01-08 15:17:56.612 |               0.000000000 |      0 |
|2020-01-08 16:35:17.951 |             100.000000000 |      0 |
|2020-01-09 01:52:24.784 |             200.000000000 |      0 |
|2020-01-09 21:54:31.485 |             300.000000000 |      0 |

Query OK, 4 row(s) in set (0.003975s)

查询每个时间点实际用电数
taos> select diff(qa) from am5411;
|ts|diff(qa)|
|---|---|
|2020-01-08 16:35:17.951 |             100.000000000 |
|2020-01-09 01:52:24.784 |             100.000000000 |
|2020-01-09 21:54:31.485 |             100.000000000 |

Query OK, 3 row(s) in set (0.002997s)

创建连续查询
taos> create table am5411_diff as select diff(qa) from am5411;

DB error: invalid SQL: functions not allowed in select clause
taos>

**Comment by sangshuduo** [comment]
目前不支持这种语法

**Comment by MelodyI** [comment]
有其它的解决方法吗
