### ISSUE TITLE
created new user and password in taos shell, but cannot connect to server

### ISSUE THREAD

**Issue by binshuilong** [taosdata/TDengine#4855]
1.命令行中创建用户
CREATE USER allynav  PASS 'sTmun5PuprpQt1XvjEVW';
ALTER USER allynav PRIVILEGE read;
//执行show users;显示如下
![image](https://user-images.githubusercontent.com/39979820/103871919-a1bc6a00-5108-11eb-85fa-852e04dcb33a.png)

2.然后使用新账户密码连接
![image](https://user-images.githubusercontent.com/39979820/103872033-cadcfa80-5108-11eb-9890-e1922ee8fbf6.png)
//出现错误
![image](https://user-images.githubusercontent.com/39979820/103872062-d8928000-5108-11eb-89a5-d1728a442c58.png)

**Comment by sangshuduo** [comment]
确定用 taos shell 和用户名密码能连吗？

**Comment by binshuilong** [comment]
> 确定用 taos shell 和用户名密码能连吗？

![image](https://user-images.githubusercontent.com/39979820/103883580-5b6f0700-5118-11eb-8b8c-f5b6aeb6b1c7.png)
是可以连接的,但是通过go-connector 还是会出现如下错误:
![image](https://user-images.githubusercontent.com/39979820/103883678-80637a00-5118-11eb-85b0-3852dcfcb843.png)

**Comment by binshuilong** [comment]
> > 确定用 taos shell 和用户名密码能连吗？
> 
> ![image](https://user-images.githubusercontent.com/39979820/103883580-5b6f0700-5118-11eb-8b8c-f5b6aeb6b1c7.png)
> 是可以连接的,但是通过go-connector 还是会出现如下错误:
> ![image](https://user-images.githubusercontent.com/39979820/103883678-80637a00-5118-11eb-85b0-3852dcfcb843.png)

但是我如果用root账号登录,是可以的

**Comment by sangshuduo** [comment]
应该是密码长度超长了，最大16个字符。

**Comment by sangshuduo** [comment]
新版本2.0.14.0应该解决了
