### ISSUE TITLE
关于使用docker.挂载/etc/taos目录,挂载后的目录找不到taos.cfg文件

### ISSUE THREAD

**Issue by pigwing** [taosdata/TDengine#4858]
按照 相关文档,使用docker运行.并且对应目录的挂载,但是/etc/taos这个目录挂载出现问题.服务器中的/etc/taos文件夹内并不存在taos.cfg文件,进入docker内部查看.find / -name taos.cfg.显示在/usr/local/taos/cfg/taos.cfg,但在docker内这也不是个文件,是个文件夹.

docker run -d -v /etc/taos:/etc/taos -p 6030:6030 -p 6035:6035 -p 6041:6041 -p 6030-6040:6030-6040/udp tdengine/tdengine:2.0.13.0

**Comment by qq289736032** [comment]
我也遇到这个问题，真扯淡
