### ISSUE TITLE
wrong sql (group by) cause exit

### ISSUE THREAD

**Issue by MelodyI** [taosdata/TDengine#4860]
taos> select first(qa) - last(qa) as qa from ammeter where ts >= '2020-01-01 00:00:00' interval(1d) group by factory;
taos: /home/taos/git/v20/TDinternal/community/src/client/src/tscUtil.c:917: tscFieldInfoGetOffset: Assertion `pInfo != NULL && pInfo->pSqlExpr != NULL' failed.
Aborted

**Comment by sangshuduo** [comment]
什么版本？

**Comment by MelodyI** [comment]
Welcome to the TDengine shell from Linux, Client Version:2.0.6.0
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

**Comment by sangshuduo** [comment]
请升级到最新版再试一下

**Comment by MelodyI** [comment]
问题已修复：版本2.0.13.0

**Comment by MelodyI** [comment]
问题已修复：版本2.0.13.0
