### ISSUE TITLE
query result with duplicate field

### ISSUE THREAD

**Issue by MelodyI** [taosdata/TDengine#4861]
查询语句`select first(qa) - last(qa) as qa, factory from ammeter where ts >= '2020-01-01 00:00:00' interval(1d) group by factory;`返回四列:ts、qa、factory、factory

**Comment by sangshuduo** [comment]
请升级到最新版再试一下

**Comment by MelodyI** [comment]
问题依然存在

Welcome to the TDengine shell from Linux, Client Version:2.0.13.0
Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.

taos> select first(qa) - last(qa) as qa, factory from ammeter where ts >= '2020-01-01 00:00:00' interval(1d) group by factory;
           ts            |            qa             |            factory             |            factory             |

**Comment by sangshuduo** [comment]
请问表结构是怎样的？ describe ammeter

**Comment by MelodyI** [comment]
taos>  describe ammeter;
             Field              |       Type       |   Length    |   Note   |
=============================================================================
 ts                             | TIMESTAMP        |           8 |          |
 qa                             | DOUBLE           |           8 |          |
 alarm                          | SMALLINT         |           2 |          |
 factory                        | NCHAR            |          10 | TAG      |
 line                           | NCHAR            |          10 | TAG      |
 unit                           | NCHAR            |          10 | TAG      |
Query OK, 6 row(s) in set (0.000517s)

**Comment by sangshuduo** [comment]
这样是不是就可以了：select first(qa) - last(qa) as qa from ammeter where ts >= '2020-01-01 00:00:00' interval(1d) group by factory;

**Comment by MelodyI** [comment]
2.0.13.0上可以，2.0.6.0不行。
