### ISSUE TITLE
2.0.8.0 cluster failed to start

### ISSUE THREAD

**Issue by huangbotao** [taosdata/TDengine#4867]
**Bug Description**
2.0.8.0 集群版本启动失败

**Expected Behavior**
集群原来运行良好，突然收到报警，服务异常。检查服务状态如下（三个节点相同）
```sh
# systemctl status taosd
● taosd.service - TDengine server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Fri 2021-01-08 19:18:27 CST; 2min 34s ago
  Process: 25443 ExecStart=/usr/bin/taosd (code=killed, signal=ABRT)
 Main PID: 25443 (code=killed, signal=ABRT)

Jan 08 19:18:27 tnode-online1 systemd[1]: Unit taosd.service entered failed state.
Jan 08 19:18:27 tnode-online1 systemd[1]: taosd.service failed.
Jan 08 19:18:27 tnode-online1 systemd[1]: taosd.service holdoff time over, scheduling restart.
Jan 08 19:18:27 tnode-online1 systemd[1]: start request repeated too quickly for taosd.service
Jan 08 19:18:27 tnode-online1 systemd[1]: Failed to start TDengine server service.
Jan 08 19:18:27 tnode-online1 systemd[1]: Unit taosd.service entered failed state.
Jan 08 19:18:27 tnode-online1 systemd[1]: taosd.service failed.
```

然后分别在三台服务器上做了服务启动的操作 ` systemctl start taosd `

这里是taosdlog 日志文件
[taosdlog.tar.gz](https://github.com/taosdata/TDengine/files/5786994/taosdlog.tar.gz)

**Screenshots**
![image](https://user-images.githubusercontent.com/36856212/104011950-e53ad500-51e9-11eb-8e99-a609fdb80cb9.png)

**Environment (please complete the following information):**
 - OS: [CentOS 7.2.x]
 - Memory 16G , CPU 8 core, current Disk Space 1000G
 - TDengine Version [2.0.8.0]

@sangshuduo 麻烦看下这个问题的原因是啥，谢谢

**Comment by sangshuduo** [comment]
2.0.8之后我们对集群功能做了很多改进和bugfix，建议升级到新版本。目前的log中由于 debugFlag 没开，有帮助的信息不大。

**Comment by huangbotao** [comment]
升级到最新版本就能启动了吗？

**Comment by sangshuduo** [comment]
建议清除数据目录，用新版本重新搭建一个全新的集群。
