### ISSUE TITLE
你们的产品可以做个和iotdb的对比分析吗？我们在做技术选型

### ISSUE THREAD

**Issue by daconglee** [taosdata/TDengine#4870]
你们的产品可以做个和iotdb的对比分析吗？我们在做技术选型，不知道你们的和iotdb那个优势大。

**Comment by shanshitao** [comment]
你们最终选的是哪个产品？

**Comment by daconglee** [comment]
iotdb不支持c#,我们选择了influx

**Comment by flykarry** [comment]
还得用自己的模型去测试，否则都是人家产品最高速的模型，没意义

**Comment by etchn** [comment]
> iotdb不支持c#,我们选择了influx

太逗了，让A和B比，然后选了C。。。

**Comment by makerlee** [comment]
> iotdb不支持c#,我们选择了influx

influxDB集群版本不是闭源了吗

**Comment by liangyuanpeng** [comment]
> > iotdb不支持c#,我们选择了influx
> 
> influxDB集群版本不是闭源了吗

是的 集群版本没有开源

**Comment by AylaAsia-Joshua** [comment]
https://iotdb.apache.org/zh/UserGuide/Master/Comparison/TSDB-Comparison.html
每家测试都是自己最牛逼

**Comment by panda00hi** [comment]
同在做技术选型，看了TDengine的各种评测对比感觉还不错的，后来又发现有个cnosdb的，抛出了和TDengine的对比，现在反而纠结了https://www.cnosdb.com/content/cnosdb/latest/other/tsdb-comparisions.html

**Comment by arielyang** [comment]
> 同在做技术选型，看了TDengine的各种评测对比感觉还不错的，后来又发现有个cnosdb的，抛出了和TDengine的对比，现在反而纠结了https://www.cnosdb.com/content/cnosdb/latest/other/tsdb-comparisions.html

首先没有提供测试源码。在当前情况下，看测试结果也是 TDengine 最优。

另外就是新产品一般还是需要几年真实生产场景打磨稳定性滴
