### ISSUE TITLE
One character parenthesis ')' is missed

### ISSUE THREAD

**Issue by tjnh05** [taosdata/TDengine#4872]
**Bug Description**
One character parenthesis ')' is missed at end of the line.

**To Reproduce**
1. Open URL https://www.taosdata.com/en/documentation/connector/#Python-Connector  in browser.
2. Scroll to the section "Query the database" 
3. Last line has no parenthesis ')' as below:
   print("ts=%s, temperature=%d, humidity=%f" %(data[0], data[1],data[2])

**Expected Behavior**
The last line should be as below:
  print("ts=%s, temperature=%d, humidity=%f" %(data[0], data[1],data[2]))

**Screenshots**

**Environment (please complete the following information):**
N/A

**Additional Context**
N/A

**Comment by sangshuduo** [comment]
Please submit a PR to fix it. Thanks.

**Comment by sangshuduo** [comment]
fixed it. thanks.
