### ISSUE TITLE
Error in using JDBC connector

### ISSUE THREAD

**Issue by whljava** [taosdata/TDengine#488]
我在这个论坛上看的还是前面的前辈提出的问题（因为我实在没看解决方案）
09/10 09:53:37.785000 0x19829888 TSC failed to set locale:en_US.UTF-8, restore locale:
09/10 09:53:37.785000 0x19829888 TSC charset:936 is not valid in locale, charset remains:
无论我在客户端和虚拟机上如何改配置都是没用  一直报这个错误 
关于这方面的帖子我也看了没有给出这方面的解答

**Comment by plum-lihui** [comment]
请参考 issue #272

**Comment by whljava** [comment]
> 请参考问题[＃272](https://github.com/taosdata/TDengine/issues/272)

没用的  这关于这方面的帖子我看了好几遍了  但是刚才我试了一下把
//        connProps.setProperty(TSDBDriver.PROPERTY_KEY_CHARSET, "UTF-8");
//        connProps.setProperty(TSDBDriver.PROPERTY_KEY_LOCALE, "en_US.UTF-8");
//        connProps.setProperty(TSDBDriver.PROPERTY_KEY_TIME_ZONE, "UTC-8");
给注释掉倒是能插入了  及时字符串类型的也可以了  那这样会不会有什么影响啊

**Comment by guanshengliang** [comment]
字符集只对nchar字段有影响

**Comment by whljava** [comment]
> 字符集只对nchar字段有影响

那我现在要是存字符串的话  这个字符集怎么设置

**Comment by guanshengliang** [comment]
Execute the following command, to see the locale configuration of your system, such as
```
root@taos:~# locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: ?????????
LANG=zh_CN.UTF-8
LANGUAGE=zh_CN:zh
LC_CTYPE=UTF-8
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER="zh_CN.UTF-8"
LC_NAME="zh_CN.UTF-8"
LC_ADDRESS="zh_CN.UTF-8"
LC_TELEPHONE="zh_CN.UTF-8"
LC_MEASUREMENT="zh_CN.UTF-8"
LC_IDENTIFICATION="zh_CN.UTF-8"
LC_ALL=
```
Then modify the configuration file, set the correct locale
```
vi /etc/taos/taos.cfg
```
Add one line
```
locale zh_CN.UTF-8
```
