### ISSUE TITLE
taosdump failed, error msg：failed to run command describe xxx_1_HAM111_1

### ISSUE THREAD

**Issue by czwer** [taosdata/TDengine#4888]
你好，请教一个执行taosdump数据导出时问题，提示报错：
./taosdump -c /etc/taos/ -o /dump/tdengine/20210112 -u user -p password -B abc  -t 500 -N 1 -T 2
====== arguments config ======
host: (null)
user: user
password: password
port: 0
cversion:
mysqlFlag: 0
outpath: /dump/tdengine/20210112
inpath:
encode: (null)
all_databases: 0
databases: 1
schemaonly: 0
with_property: 0
start_time: 0
end_time: 9223372036854775807
data_batch: 1
max_sql_len: 65480
table_batch: 500
thread_num: 2
allow_sys: 0
abort: 0
isDumpIn: 0
arg_list_len: 1
arg_list[0]: abc
==============================
failed to run command describe xxx_1_HAM111_1
failed to run command describe yyy_1_HAM111_1
dump out rows: 0

通过客户端连接TDengine后，选择要导出的数据库：
执行describe xxx_1_HAM111_1报同样错误：“failed to run command describe xxx_1_HAM111_1”；
执行‘describe xxx_1_HAM111_1’正常执行，与上面的命令区别是含单引号',请问这种情况下，如何导出数据，进行备份？望回复，十分感谢！

**Comment by sangshuduo** [comment]
没看懂，taos shell 里需要加单引号才能执行成功？不加单引号不行？如果这样就不只是 taosdump 问题，连 taos shell 都有问题了。能否截图看一下？

**Comment by czwer** [comment]
@sangshuduo :
1.上面粘贴的就是脱敏后的报错：只是替换了账户密码，表名称其他信息都是完整的；
2.在taos shell中执行sql时，我这面也都是加了单引号：‘’,因TDengine默认把大写转小写，加上后可以正常执行；
3.问题描述：创建的表都使用了单引号'表名称',导出数据时，taosdump中包含describe 表名称的过程，taosdump执行describe 表名称 的时候没有加‘’，导致了报错（根据https://github.com/taosdata/TDengine/issues/665这个指导，发现describe '表名称'时正常，单独执行describe 表名称 的时候就报：failed to run command describe）。
4.可以创建一个包含单引号的表，表名称为大写，就可以重现问题；

**Comment by sangshuduo** [comment]
明白了，我们尽快看如何解决这种问题

**Comment by plum-lihui** [comment]
如果在创建库、表的时候，对表名使用了引号，且里面使用的有大写字母，则会出现这种问题。
当前最新的develop分支代码已经解决了该问题。

**Comment by czwer** [comment]
@plum-lihui ,你好，请问下哪个tag版本也已经修复该问题了？当前使用的版本：ver-2.0.9.0 可以直接升级到对应tag版本吗？望回复，谢谢！

**Comment by sangshuduo** [comment]
@czwer taosdump 目前重构后变成独立的 taosTools 的一部分，请使用单独的 taosTools 安装包安装使用。如果新版本有其他问题也可以提交到 taosTools 项目，这个 issue 暂时关闭
