### ISSUE TITLE
create database with  UPPER case name but cannot use

### ISSUE THREAD

**Issue by gufeng2016** [taosdata/TDengine#4889]
TDengine 版本 2.0.13.0
环境，单机，使用语言java
bug步骤：
1、使用官方的德鲁伊连接池示例，创建好连接，然后执行create database IF NOT EXISTS iot_platform_tenantMark04  KEEP 3650 DAYS 10 BLOCKS 4  UPDATE 1;运行成功
2、使用连接jdbc:TAOS://tdengine01:6030/iot_platform_tenantMark04，此时数据库报错：create connection SQLException, url: jdbc:TAOS://tdengine01:6030/iot_platform_tenantMark04, errorCode -2, state 
3、使用shell操作，提示Invalid database name ，删除也是如此
![image](https://user-images.githubusercontent.com/24515196/104322831-5b0fab00-5520-11eb-85ae-f35af50d5a62.png)

查看log grep ERROR* 错误如下
![image](https://user-images.githubusercontent.com/24515196/104322912-74185c00-5520-11eb-99c4-6605a1bebb2e.png)

查看shuj数据库详情使用：show databases\G; 
得到：
![image](https://user-images.githubusercontent.com/24515196/104322961-85f9ff00-5520-11eb-9520-b3cd03003f75.png)
在 taos shell 里 alter dnode 1 debugFlag 135 然后 drop database 一次

![image](https://user-images.githubusercontent.com/24515196/104323035-9f9b4680-5520-11eb-9a0a-fa0af503d102.png)

这是log包，
[taos.log.zip](https://github.com/taosdata/TDengine/files/5802486/taos.log.zip)
王大神解决

**Comment by sangshuduo** [comment]
试试 drop database 'iot_platform_tenantMark01'

**Comment by gufeng2016** [comment]
也不行哦，还是提示数据库名不对

**Comment by sangshuduo** [comment]
新的 develop 分支代码针对这个问题做了修复

**Comment by sangshuduo** [comment]
close as issue resolved.
