### ISSUE TITLE
squirrel-sql failed to connect TDengine

### ISSUE THREAD

**Issue by dacaibi2019** [taosdata/TDengine#4893]
想利用Squirrel-sql友好的管理Tdengine,在适配中遇到问题，想请求帮助。
![image](https://user-images.githubusercontent.com/52227141/104399997-c8f1bc00-558c-11eb-88e5-8e447ac9201e.png)
配置文件如下：
![image](https://user-images.githubusercontent.com/52227141/104400278-34d42480-558d-11eb-9f63-897542834461.png)

![image](https://user-images.githubusercontent.com/52227141/104400395-651bc300-558d-11eb-8776-0cd971fa4c57.png)
连接后就会报错误：
taos: TDengine Error: Unable to establish connection
class java.sql.SQLException: TDengine Error: Unable to establish connection
想请教是否有人适配过此工具，或者看下我的配置是否有问题？

**Comment by sangshuduo** [comment]
这是在 docker 里跑 taosd 吗？可以参考一下https://github.com/taosdata/TDengine/issues/4865

**Comment by dacaibi2019** [comment]
非常感谢你的回答，我同一台机器通过taosd  shell和taos studio连接的时候是可以连接的,查看过端口设置，都是关闭的；配置squirrel-sql 连接报错。

**Comment by dacaibi2019** [comment]
> 这是在 docker 里跑 taosd 吗？可以参考一下#4865
没有在docker里跑。

**Comment by sangshuduo** [comment]
请对照 FAQ 中相关章节自查一下：https://www.taosdata.com/cn/documentation20/faq/。

**Comment by dacaibi2019** [comment]
> 请对照 FAQ 中相关章节自查一下：[https://www.taosdata.com/cn/documentation20/faq/。](https://www.taosdata.com/cn/documentation20/faq/%E3%80%82)

好的，我再重新检查检查。

**Comment by sangshuduo** [comment]
@dacaibi2019 后来解决了吗？

**Comment by sangshuduo** [comment]
no update, close
