### ISSUE TITLE
nchar

### ISSUE THREAD

**Issue by gufeng2016** [taosdata/TDengine#4900]
**Bug Description**

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by Aries-Lee1991** [comment]
见https://github.com/taosdata/TDengine/issues/4901
