### ISSUE TITLE
nchar cannot support Chinese

### ISSUE THREAD

**Issue by gufeng2016** [taosdata/TDengine#4901]
TDengine 版本 2.0.13.0
环境，单机，使用语言java
bug步骤：
使用java连接插入记录，语句如下insert into dsl_modelmark001_lmvleruy22 values(now, "yingwen","有中文","yingwen");
执行后结果为：
![image](https://user-images.githubusercontent.com/24515196/104487181-ba94b600-5607-11eb-932e-520a5a16b72f.png)
中文无法显示出来
使用java客户端可以查询出来
![image](https://user-images.githubusercontent.com/24515196/104489174-4ad3fa80-560a-11eb-9785-e633b3b32e87.png)

也就是shell无法显示中文
问题2：使用德鲁伊连接池无法写入中文：
以下是错误提示
org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [insert into  dsl_modelmark001_lmvleruy22 ( ts  , change_type , status_after , status_before  ) values (  1610559692079 ,  "我是大佬" ,  "搞死你" ,  "这是什么呢" ) ;]; SQL state []; error code [-2147483114]; TDengine Error: invalid SQL: '搞死你' (Invalid argument); nested exception is java.sql.SQLException: TDengine Error: invalid SQL: '搞死你' (Invalid argument)

将插入语句复制到shell脚本出，中文全部变成了空格
![image](https://user-images.githubusercontent.com/24515196/104489212-558e8f80-560a-11eb-984a-4a9d427dd0c9.png)

使用单独的java连接可以插入成功，同样是shell也是看不到中文，但是可以通过查出来中文
请问大神使用德鲁伊连接池要怎样查能插入和查询出中文，深夜码代码不易，请早点回复

**Comment by MelodyI** [comment]
FROM tdengine/tdengine:latest
RUN apt-get -y update && apt-get -y install locales locales-all
ENV LANG zh_CN.utf8

这样就支持中文了

**Comment by Aries-Lee1991** [comment]
@gufeng2016 按照上述操作，正常了吗？

**Comment by CallMeAdong** [comment]
疑惑，直接DML插入带中文数据,能插入但全乱码了，而Java插入直接报错，错误如下：
org.springframework.jdbc.UncategorizedSQLException: 
### Error updating database.  Cause: java.sql.SQLException: TDengine Error: invalid SQL: '雅园居小区/小区门1' (Illegal byte sequence)
### The error may exist in com/thinmoo/cloud/business/acc/mapper/AccNormalOpenDoorlogMapper.java (best guess)
### The error may involve com.thinmoo.cloud.business.acc.mapper.AccNormalOpenDoorlogMapper.executeInsertSql-Inline
### The error occurred while setting parameters

**Comment by Jawliet** [comment]
> 疑惑，版本2.0.14，直接DML插入带中文数据,能插入但全乱码了，而Java插入直接报错，错误如下：
> org.springframework.jdbc.UncategorizedSQLException:
> 
> ### Error updating database. Cause: java.sql.SQLException: TDengine Error: invalid SQL: '雅园居小区/小区门1' (Illegal byte sequence)
> ### The error may exist in com/thinmoo/cloud/business/acc/mapper/AccNormalOpenDoorlogMapper.java (best guess)
> ### The error may involve com.thinmoo.cloud.business.acc.mapper.AccNormalOpenDoorlogMapper.executeInsertSql-Inline
> ### The error occurred while setting parameters

如果是Windows，修改 C:\TDengine\cfg charset 的注释打开
