### ISSUE TITLE
Unable to compile on alpine

### ISSUE THREAD

**Issue by Feynman83** [taosdata/TDengine#4902]
/TDengine/src/os/inc/osArm32.h:78:10: fatal error: error.h: No such file or directory
   78 | #include <error.h>

**Comment by Aries-Lee1991** [comment]
请补充详细信息，TDengine版本号、详细日志信息、编译步骤。

**Comment by plum-lihui** [comment]
在编译的参数中指定了 Alpine系统吗？
如果使用release.sh脚本编译的话，请指定 -o Alpine，可以看命令帮助；
如果是直接使用cmake & make方式编译，请在cmake 指定 -DOSTYPE=Alpine

**Comment by Feynman83** [comment]
OK
