### ISSUE TITLE
终端查询，子表名称显示不全

### ISSUE THREAD

**Issue by opjk** [taosdata/TDengine#4904]
**Bug Description**
taos> select TBNAME from his_ac_telemetry;
             tbname             |
=================================
 shihu_a8048408522b6c5a073e0... |
 shihu_4257c708a593b78fb2c05... |
 shihu_52dafd336e536c183e63a... |
Query OK, 3 row(s) in set (0.005903s)

想查单个子表都找不到表名。

**Comment by sangshuduo** [comment]
# select TBNAME from his\_ac\_telemetry\\G;
