### ISSUE TITLE
Crash happened when using JDBC connector

### ISSUE THREAD

**Issue by only311** [taosdata/TDengine#491]
[INFO ] 19:27:46.948 [pool-7-thread-2] cn.wizzer.app.bp.modules.hotwater.save.SaveHotwaterData - INSERT INTO S_HT_DATA_19709368 USING S_HT_DATA TAGS ('19709368', NULL, '15') VALUES (now, 315.0,82.0 ,0.0 ,-10000.0 ,21 ,0 ,false ,false ,false ,false ,NULL ,NULL ,NULL ,NULL ,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
[INFO ] 19:27:46.955 [pool-2-thread-3] cn.wizzer.app.bp.modules.hotwater.decode.AbstractHotwaterFN - save.hotwaterFrameData success
[DEBUG] 19:27:46.955 [pool-2-thread-3] cn.wizzer.app.bp.modules.hotwater.decode.AbstractHotwaterFN - 保存上行报文结束
[DEBUG] 19:27:48.171 [pool-1-thread-2] cn.hutool.log.LogFactory - Use [Slf4j] Logger As Default.
[DEBUG] 19:27:48.185 [pool-1-thread-2] cn.hutool.http.cookie.GlobalCookieManager - Add Cookie from local store: []
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffadc4f46ae, pid=13004, tid=0x0000000000000b0c
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [taos.dll+0x246ae]
#
# Core dump written. Default location: E:\workspace2019\eics-based-nutzwk\hs_err_pid13004.mdmp
#
# An error report file with more information is saved as:
# E:\workspace2019\eics-based-nutzwk\hs_err_pid13004.log
[hs_err_pid13004.log](https://github.com/taosdata/TDengine/files/3595407/hs_err_pid13004.log)

#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by only311** [comment]
taos> INSERT INTO S_HT_DATA_19709368 USING S_HT_DATA TAGS ('19709368', NULL, '15') VALUES (now, 315.0,82.0 ,0.0 ,-10000.0 ,21 ,0 ,false ,false ,false ,false ,NULL ,NULL ,NULL ,NULL ,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
Query OK, 1 row(s) affected (0.001000s)

taos>

**Comment by only311** [comment]
手动能插入。应该还是jdbc的驱动问题

**Comment by only311** [comment]
用http的接口插入成功
[INFO ] 19:33:58.880 [pool-7-thread-4] cn.wizzer.app.bp.modules.hotwater.save.SaveHotwaterData - INSERT INTO db.S_HT_DATA_19709368 USING db.S_HT_DATA TAGS ('19709368', NULL, '13') VALUES (now, NULL,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,'137;120102;163' ,0.0 ,9.0 ,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
[INFO ] 19:33:58.887 [pool-2-thread-3] cn.wizzer.app.bp.modules.hotwater.decode.AbstractHotwaterFN - save.hotwaterFrameData success
[DEBUG] 19:33:58.887 [pool-2-thread-3] cn.wizzer.app.bp.modules.hotwater.decode.AbstractHotwaterFN - 保存上行报文结束
[INFO ] 19:33:58.922 [pool-7-thread-4] cn.wizzer.app.bp.modules.hotwater.save.SaveHotwaterData - {"status":"succ","head":["affected_rows"],"data":[[1]],"rows":1}

**Comment by guanshengliang** [comment]
1.大数据量下的测试，希望您在windows下测试后再linux下进行，windows客户端我们测试的不多
2.如果需要解决这个问题，请将你的java程序打成jar包，便于我们进行问题复现和处理

**Comment by guanshengliang** [comment]
Add my wechat geiseil, to solve this problem

**Comment by guanshengliang** [comment]
This problem has not happened again in the test environment, close it
