### ISSUE TITLE
Invalid SQL statement

### ISSUE THREAD

**Issue by binshuilong** [taosdata/TDengine#4911]
1.当我新增数据的时候,会出现这个问题,Invalid SQL statement
2.但是我执行建表语句是能执行成功的

3.我修改了client,maxSql配置,配置如下
![image](https://user-images.githubusercontent.com/39979820/104573497-ebb8c900-568f-11eb-8ee8-923b80f67817.png)

**Comment by sangshuduo** [comment]
请说明版本信息，平台信息，完整执行过程
