### ISSUE TITLE
taosd connect fail UTL ERROR failed to open udp socket: 24 (Too many open files),疑是协程泄露

### ISSUE THREAD

**Issue by xiangxud** [taosdata/TDengine#4913]
这个可能是我的bug,不是taosd的Bug
vmware 15+ centos7 + go1.15 taosd 2.0.15 代码 Prometheus server 改，代码见末尾
      

[taoslog0.log](https://github.com/taosdata/TDengine/files/5814877/taoslog0.log)

[taosd.zip](https://github.com/taosdata/TDengine/files/5814893/taosd.zip)

**Comment by sangshuduo** [comment]
可以写一个可以编译运行的简单版本示例程序吗？

**Comment by xiangxud** [comment]
[test.zip](https://github.com/taosdata/TDengine/files/5819153/test.zip)
cd test
go mod tidy
 设置见tansfer.yml
  taosd:     #for TDengine 
    enabled: true
    name: "taosd"
    config:  
      daemonIP: "192.168.2.248"   #改成自己的服务器IP
      daemonName: "192.168.2.248" #改成自己的服务器IP
      serverPort: 6030
      apiport: 6020
      dbuser: "root"
      dbpassword: "taosdata"
      dbName: "n9e"
      taosDriverName: "taosSql"
      httpworkers: 10
      sqlworkers: 5   #并发协程数
      batchSize: 5 #入库并发
      buffersize: 100 #入库缓存
      queryworkers: 10 查询并发
      querydatachs: 10 查询并发
      callTimeout: 1000
      debugprt: 2 #if 0 not print, if 1 print the sql,
      taglen: 128
      taglimit: 1024
      tagnumlimit: 128
      keep: 3650 #5 years数据保留期
      days: 30    #一个月1个文件
      blocks: 4     #内存块
      url: ""
      tdurl: ""
      tagstr: ""

**Comment by sangshuduo** [comment]
我们不可能帮您看这么复杂的程序。如果能有一个比较短没有其他业务逻辑的测试程序证明是 TDengine 的问题我们再看。

**Comment by xiangxud** [comment]
这个代码基本上跟你们提供的bailongma Prometheus server 一样的，我只是增加了一些配置和查询，自动建表逻辑也是原来的，查询表结构我用sql，没有用restful，你们还有类试的例程吗，多协程查询和入库的就行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "fangpanpan"<notifications@github.com&gt;; 
发送时间: 2021年1月21日(星期四) 下午5:06
收件人: "taosdata/TDengine"<TDengine@noreply.github.com&gt;; 
抄送: "365603975"<365603975@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [taosdata/TDengine] taosd connect fail UTL ERROR failed to open udp socket: 24 (Too many open files),疑是协程泄露 (#4913)





 
我们不可能帮您看这么复杂的程序。如果能有一个比较短没有其他业务逻辑的测试程序证明是 TDengine 的问题我们再看。

**Comment by sangshuduo** [comment]
各个连接器都有相应示例程序，安装官方安装宝后在 /usr/local/taos/examples 目录下。github 源代码在 TDengine/tests/examples 目录下。如果是 Bailongma 的 bug ，欢迎到  taosdata/Bailongma 项目中提 issue，请尽量用最简单的方式证明。谢谢！

**Comment by xiangxud** [comment]
有可能是机器性能问题，协程开多了，我虚拟机只有一核3G



---原始邮件---
发件人: "Shuduo Sang"<notifications@github.com&gt;
发送时间: 2021年1月21日(周四) 下午5:53
收件人: "taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送: "xiangxud"<365603975@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [taosdata/TDengine] taosd connect fail UTL ERROR failed to open udp socket: 24 (Too many open files),疑是协程泄露 (#4913)




 
各个连接器都有相应示例程序，安装官方安装宝后在 /usr/local/taos/examples 目录下。github 源代码在 TDengine/tests/examples 目录下。如果是 Bailongma 的 bug ，欢迎到 &nbsp;taosdata/Bailongma 项目中提 issue，请尽量用最简单的方式证明。谢谢！
