### ISSUE TITLE
Bus error happens run on imx6 board

### ISSUE THREAD

**Issue by Feynman83** [taosdata/TDengine#4914]
# ./taosd
01/01 00:00:52.531013 0xb6fb6010 DND start to initialize TDengine
01/01 00:00:52.531475 0xb6fb6010 DND step:dnode-tfile is initialized
01/01 00:00:52.534640 0xb6fb6010 DND step:dnode-rpc is initialized
01/01 00:00:52.539136 0xb6fb6010 UTL localEp is: Xbrother:6030
01/01 00:00:52.545185 0xb6fb6010 UTL WARN timezone not configured, set to system default:Etc/UTC (UTC, +0000)
01/01 00:00:52.545444 0xb6fb6010 UTL WARN locale not configured, set to system default:C
01/01 00:00:52.548175 0xb6fb6010 UTL    taos config & system info:
01/01 00:00:52.548363 0xb6fb6010 UTL ==================================
01/01 00:00:52.548532 0xb6fb6010 UTL  firstEp:                Xbrother:6030 
01/01 00:00:52.548692 0xb6fb6010 UTL  secondEp:               Xbrother:6030 
01/01 00:00:52.548872 0xb6fb6010 UTL  fqdn:                   Xbrother 
01/01 00:00:52.549033 0xb6fb6010 UTL  serverPort:             6030 
01/01 00:00:52.549376 0xb6fb6010 UTL  configDir:              /etc/taos 
01/01 00:00:52.549527 0xb6fb6010 UTL  logDir:                 /home/td-engin/log 
01/01 00:00:52.549816 0xb6fb6010 UTL  scriptDir:              /etc/taos 
01/01 00:00:52.550287 0xb6fb6010 UTL  dataDir:                /home/td-engin/data 
01/01 00:00:52.550609 0xb6fb6010 UTL  arbitrator:              
01/01 00:00:52.550771 0xb6fb6010 UTL  numOfThreadsPerCore:    1.000000 
01/01 00:00:52.551205 0xb6fb6010 UTL  numOfCommitThreads:     1 
01/01 00:00:52.551654 0xb6fb6010 UTL  ratioOfQueryCores:      1.000000 
01/01 00:00:52.552076 0xb6fb6010 UTL  numOfMnodes:            3 
01/01 00:00:52.552493 0xb6fb6010 UTL  vnodeBak:               1 
01/01 00:00:52.552905 0xb6fb6010 UTL  telemetryReporting:     1 
01/01 00:00:52.553357 0xb6fb6010 UTL  balance:                1 
01/01 00:00:52.553661 0xb6fb6010 UTL  balanceInterval:        300 
01/01 00:00:52.554113 0xb6fb6010 UTL  role:                   0 
01/01 00:00:52.554563 0xb6fb6010 UTL  maxTmrCtrl:             512 
01/01 00:00:52.554903 0xb6fb6010 UTL  monitorInterval:        30(s)
01/01 00:00:52.555377 0xb6fb6010 UTL  offlineThreshold:       8640000(s)
01/01 00:00:52.555864 0xb6fb6010 UTL  rpcTimer:               1000(ms)
01/01 00:00:52.556629 0xb6fb6010 UTL  rpcMaxTime:             600(s)
01/01 00:00:52.557104 0xb6fb6010 UTL  statusInterval:         1(s)
01/01 00:00:52.557521 0xb6fb6010 UTL  shellActivityTimer:     3(s)
01/01 00:00:52.557956 0xb6fb6010 UTL  minSlidingTime:         10(ms)
01/01 00:00:52.558386 0xb6fb6010 UTL  minIntervalTime:        10(ms)
01/01 00:00:52.559369 0xb6fb6010 UTL  maxStreamCompDelay:     20000(ms)
01/01 00:00:52.559933 0xb6fb6010 UTL  maxFirstStreamCompDelay:10000(ms)
01/01 00:00:52.560532 0xb6fb6010 UTL  retryStreamCompDelay:   10(ms)
01/01 00:00:52.560778 0xb6fb6010 UTL  streamCompDelayRatio:   0.100000 
01/01 00:00:52.561060 0xb6fb6010 UTL  maxVgroupsPerDb:        0 
01/01 00:00:52.561216 0xb6fb6010 UTL  maxTablesPerVnode:      1000000 
01/01 00:00:52.561363 0xb6fb6010 UTL  minTablesPerVnode:      1000 
01/01 00:00:52.561573 0xb6fb6010 UTL  tableIncStepPerVnode:   1000 
01/01 00:00:52.561705 0xb6fb6010 UTL  cache:                  16(Mb)
01/01 00:00:52.561854 0xb6fb6010 UTL  blocks:                 6 
01/01 00:00:52.562237 0xb6fb6010 UTL  days:                   10 
01/01 00:00:52.562503 0xb6fb6010 UTL  keep:                   3650 
01/01 00:00:52.562621 0xb6fb6010 UTL  minRows:                100 
01/01 00:00:52.562736 0xb6fb6010 UTL  maxRows:                4096 
01/01 00:00:52.562873 0xb6fb6010 UTL  comp:                   2 
01/01 00:00:52.563075 0xb6fb6010 UTL  walLevel:               1 
01/01 00:00:52.563191 0xb6fb6010 UTL  fsync:                  3000 
01/01 00:00:52.563329 0xb6fb6010 UTL  replica:                1 
01/01 00:00:52.563447 0xb6fb6010 UTL  quorum:                 1 
01/01 00:00:52.563668 0xb6fb6010 UTL  update:                 0 
01/01 00:00:52.563810 0xb6fb6010 UTL  compressMsgSize:        -1 
01/01 00:00:52.563947 0xb6fb6010 UTL  maxSQLLength:           65480(byte)
01/01 00:00:52.564168 0xb6fb6010 UTL  maxNumOfOrderedRes:     100000 
01/01 00:00:52.564288 0xb6fb6010 UTL  queryBufferSize:        -1(byte)
01/01 00:00:52.564533 0xb6fb6010 UTL  retrieveBlockingModel:  0 
01/01 00:00:52.564672 0xb6fb6010 UTL  keepColumnName:         0 
01/01 00:00:52.564887 0xb6fb6010 UTL  timezone:               Etc/UTC (UTC, +0000) 
01/01 00:00:52.565030 0xb6fb6010 UTL  locale:                 C 
01/01 00:00:52.565148 0xb6fb6010 UTL  charset:                UTF-8 
01/01 00:00:52.565263 0xb6fb6010 UTL  maxShellConns:          5000 
01/01 00:00:52.565397 0xb6fb6010 UTL  maxConnections:         5000 
01/01 00:00:52.565618 0xb6fb6010 UTL  minimalLogDirGB:        0.100000(GB)
01/01 00:00:52.565745 0xb6fb6010 UTL  minimalTmpDirGB:        0.100000(GB)
01/01 00:00:52.565965 0xb6fb6010 UTL  minimalDataDirGB:       0.100000(GB)
01/01 00:00:52.566113 0xb6fb6010 UTL  mnodeEqualVnodeNum:     4 
01/01 00:00:52.566231 0xb6fb6010 UTL  flowctrl:               1 
01/01 00:00:52.566448 0xb6fb6010 UTL  slaveQuery:             1 
01/01 00:00:52.566585 0xb6fb6010 UTL  adjustMaster:           1 
01/01 00:00:52.566727 0xb6fb6010 UTL  http:                   1 
01/01 00:00:52.566940 0xb6fb6010 UTL  mqtt:                   0 
01/01 00:00:52.567056 0xb6fb6010 UTL  monitor:                1 
01/01 00:00:52.567275 0xb6fb6010 UTL  stream:                 1 
01/01 00:00:52.567413 0xb6fb6010 UTL  httpEnableRecordSql:    0 
01/01 00:00:52.567550 0xb6fb6010 UTL  telegrafUseFieldNum:    0 
01/01 00:00:52.567770 0xb6fb6010 UTL  httpMaxThreads:         2 
01/01 00:00:52.567888 0xb6fb6010 UTL  restfulRowLimit:        10240 
01/01 00:00:52.568106 0xb6fb6010 UTL  numOfLogLines:          10000000 
01/01 00:00:52.568223 0xb6fb6010 UTL  logKeepDays:            0 
01/01 00:00:52.568363 0xb6fb6010 UTL  asyncLog:               1 
01/01 00:00:52.568477 0xb6fb6010 UTL  debugFlag:              0 
01/01 00:00:52.568693 0xb6fb6010 UTL  mDebugFlag:             131 
01/01 00:00:52.568833 0xb6fb6010 UTL  dDebugFlag:             135 
01/01 00:00:52.568971 0xb6fb6010 UTL  sDebugFlag:             135 
01/01 00:00:52.569186 0xb6fb6010 UTL  wDebugFlag:             135 
01/01 00:00:52.569306 0xb6fb6010 UTL  sdbDebugFlag:           131 
01/01 00:00:52.569519 0xb6fb6010 UTL  rpcDebugFlag:           131 
01/01 00:00:52.569659 0xb6fb6010 UTL  tmrDebugFlag:           131 
01/01 00:00:52.569777 0xb6fb6010 UTL  cDebugFlag:             131 
01/01 00:00:52.569987 0xb6fb6010 UTL  jniDebugFlag:           131 
01/01 00:00:52.570249 0xb6fb6010 UTL  odbcDebugFlag:          131 
01/01 00:00:52.570390 0xb6fb6010 UTL  uDebugFlag:             131 
01/01 00:00:52.570585 0xb6fb6010 UTL  httpDebugFlag:          131 
01/01 00:00:52.570707 0xb6fb6010 UTL  mqttDebugFlag:          131 
01/01 00:00:52.570847 0xb6fb6010 UTL  monDebugFlag:           131 
01/01 00:00:52.571087 0xb6fb6010 UTL  qDebugFlag:             131 
01/01 00:00:52.571229 0xb6fb6010 UTL  vDebugFlag:             135 
01/01 00:00:52.571433 0xb6fb6010 UTL  tsdbDebugFlag:          131 
01/01 00:00:52.571572 0xb6fb6010 UTL  cqDebugFlag:            131 
01/01 00:00:52.571709 0xb6fb6010 UTL  enableRecordSql:        0 
01/01 00:00:52.571926 0xb6fb6010 UTL  enableCoreFile:         0 
01/01 00:00:52.572044 0xb6fb6010 UTL  gitinfo:                community 
01/01 00:00:52.572372 0xb6fb6010 UTL  gitinfoOfInternal:      internal 
01/01 00:00:52.572513 0xb6fb6010 UTL  buildinfo:              Built at 2021-01-14 09:25:18 
01/01 00:00:52.572715 0xb6fb6010 UTL  version:                2.0.13.0 
01/01 00:00:52.572915 0xb6fb6010 UTL  maxBinaryDisplayWidth:  30 
01/01 00:00:52.573167 0xb6fb6010 UTL  tempDir:                /tmp/ 
01/01 00:00:52.573500 0xb6fb6010 UTL  os pageSize:            4096(KB)
01/01 00:00:52.573874 0xb6fb6010 UTL  os openMax:             1024
01/01 00:00:52.574328 0xb6fb6010 UTL  os streamMax:           16
01/01 00:00:52.574684 0xb6fb6010 UTL  os numOfCores:          4
01/01 00:00:52.574956 0xb6fb6010 UTL  os totalDisk:           14.198212(GB)
01/01 00:00:52.575446 0xb6fb6010 UTL  os totalMemory:         2006(MB)
01/01 00:00:52.575604 0xb6fb6010 UTL  os sysname:             Linux
01/01 00:00:52.575805 0xb6fb6010 UTL  os nodename:            Xbrother
01/01 00:00:52.575967 0xb6fb6010 UTL  os release:             5.4.86
01/01 00:00:52.576103 0xb6fb6010 UTL  os version:             #2 SMP Thu Jan 14 21:02:08 CST 2021
01/01 00:00:52.576330 0xb6fb6010 UTL  os machine:             armv7l
01/01 00:00:52.576449 0xb6fb6010 UTL ==================================
01/01 00:00:52.576587 0xb6fb6010 DND step:dnode-globalcfg is initialized
01/01 00:00:52.580744 0xb6fb6010 DND dnode storage is initialized at /home/td-engin/data/dnode
01/01 00:00:52.580913 0xb6fb6010 DND step:dnode-storage is initialized
01/01 00:00:52.582629 0xb6fb6010 DND read file /home/td-engin/data/dnode/dnodeCfg.json successed
01/01 00:00:52.582829 0xb6fb6010 DND dnodeId is set to 1, clusterId is set to 61bbaad1-0c7d-46e7-a834-a9dcef64e868
01/01 00:00:52.584507 0xb6fb6010 DND successed to write /home/td-engin/data/dnode/dnodeCfg.json
01/01 00:00:52.584658 0xb6fb6010 DND dnode cfg is initialized
01/01 00:00:52.584782 0xb6fb6010 DND step:dnode-cfg is initialized
01/01 00:00:52.586441 0xb6fb6010 DND read file /home/td-engin/data/dnode/dnodeEps.json successed
01/01 00:00:52.586746 0xb6fb6010 DND dnode eps is initialized
01/01 00:00:52.586975 0xb6fb6010 DND step:dnode-eps is initialized
01/01 00:00:52.587957 0xb6fb6010 DND read file /home/td-engin/data/dnode/mnodeEpSet.json successed
01/01 00:00:52.588095 0xb6fb6010 DND print minfos, mnodeNum:1 inUse:0
01/01 00:00:52.588212 0xb6fb6010 DND mnode index:1, Xbrother:6030
01/01 00:00:52.588369 0xb6fb6010 DND print minfos, mnodeNum:1 inUse:0
01/01 00:00:52.588517 0xb6fb6010 DND mnode index:1, Xbrother:6030
01/01 00:00:52.588635 0xb6fb6010 DND dnode minfos is initialized
01/01 00:00:52.588870 0xb6fb6010 DND step:dnode-minfos is initialized
01/01 00:00:52.589541 0xb6fb6010 WAL wal module is initialized, refId:3
01/01 00:00:52.589661 0xb6fb6010 DND step:dnode-wal is initialized
01/01 00:00:52.592343 0xb6fb6010 DND step:dnode-sync is initialized
01/01 00:00:52.592615 0xb6fb6010 DND dnode check is initialized
01/01 00:00:52.592937 0xb6fb6010 DND step:dnode-check is initialized
01/01 00:00:52.593202 0xb6fb6010 UTL worker:vquery is initialized, min:4 max:4
01/01 00:00:52.593597 0xb6fb6010 UTL worker:vfetch is initialized, min:4 max:4
01/01 00:00:52.593889 0xb6fb6010 DND step:dnode-vread is initialized
01/01 00:00:52.594257 0xb6fb6010 DND dnode vwrite is initialized, max worker 4
01/01 00:00:52.594618 0xb6fb6010 DND step:dnode-vwrite is initialized
01/01 00:00:52.595437 0xb6fb6010 DND step:vnode-worker is initialized
01/01 00:00:52.595767 0xb6fb6010 DND step:vnode-write is initialized
01/01 00:00:52.596050 0xb6fb6010 DND step:vnode-read is initialized
01/01 00:00:52.596435 0xb6fb6010 DND step:vnode-hash is initialized
01/01 00:00:52.599204 0xb6fb6010 DND step:tsdb-queue is initialized
01/01 00:00:52.599470 0xb6fb6010 UTL worker:vmgmt is initialized, min:1 max:1
01/01 00:00:52.600180 0xb6fb6010 DND dnode vmgmt is initialized
01/01 00:00:52.600457 0xb6fb6010 DND step:dnode-vmgmt is initialized
01/01 00:00:52.600898 0xb6fb6010 DND step:dnode-mread is initialized
01/01 00:00:52.601352 0xb6fb6010 DND step:dnode-mwrite is initialized
01/01 00:00:52.601953 0xb6fb6010 DND step:dnode-mpeer is initialized
01/01 00:00:52.628163 0xb6fb6010 DND dnode inter-dnodes rpc client is initialized
01/01 00:00:52.628712 0xb6fb6010 DND step:dnode-client is initialized
01/01 00:00:52.631778 0xb6fb6010 DND dnode inter-dnodes RPC server is initialized
01/01 00:00:52.632141 0xb6fb6010 DND step:dnode-server is initialized
01/01 00:00:52.635524 0xb6fb6010 DND start 4 threads to open 1 vnodes
01/01 00:00:52.637942 0xae7ae450 VND vgId:2, load vnode cfg successfully, replcia:1
01/01 00:00:52.638215 0xae7ae450 VND vgId:2, dnode:1, Xbrother:6040
01/01 00:00:52.639104 0xae7ae450 VND vgId:2, read /home/td-engin/data/vnode/vnode2/version.json successfully, fver:4
01/01 00:00:52.650531 0xae7ae450 WAL vgId:2, file:/home/td-engin/data/vnode/vnode2/wal/wal1, will be restored
01/01 00:00:52.651382 0xae7ae450 WAL vgId:2, file:/home/td-engin/data/vnode/vnode2/wal/wal1, restore success, wver:0
01/01 00:00:52.653134 0xae7ae450 WAL vgId:2, wal:0xade24370 file:/home/td-engin/data/vnode/vnode2/wal/wal1, it is removed
01/01 00:00:52.656208 0xae7ae450 VND vgId:2, sync role changed from offline to master
01/01 00:00:52.657134 0xb6fb6010 DND there are total vnodes:1, opened:1
01/01 00:00:52.657325 0xb6fb6010 DND step:dnode-vnodes is initialized
01/01 00:00:52.660072 0xb6fb6010 MND starting to initialize mnode ...
01/01 00:00:52.661802 0xb6fb6010 DND step:sdbref is initialized
01/01 00:00:52.662532 0xb6fb6010 DND step:profile is initialized
01/01 00:00:52.662729 0xb6fb6010 DND step:cluster is initialized
01/01 00:00:52.662894 0xb6fb6010 DND step:accts is initialized
01/01 00:00:52.663053 0xb6fb6010 DND step:users is initialized
01/01 00:00:52.663360 0xb6fb6010 DND step:dnodes is initialized
01/01 00:00:52.663585 0xb6fb6010 DND step:dbs is initialized
01/01 00:00:52.663752 0xb6fb6010 DND step:vgroups is initialized
01/01 00:00:52.665067 0xb6fb6010 DND step:tables is initialized
01/01 00:00:52.665258 0xb6fb6010 DND step:mnodes is initialized
01/01 00:00:52.665693 0xb6fb6010 MND vgId:1, sdb write is opened
01/01 00:00:52.666225 0xb6fb6010 SDB vgId:1, open sdb wal for restore
01/01 00:00:52.666611 0xb6fb6010 WAL vgId:1, file:/home/td-engin/data/mnode/wal/wal0, will be restored
01/01 00:00:52.668905 0xb6fb6010 MND dnode:1, fqdn:Xbrother ep:Xbrother:6030 port:6030 is created
01/01 00:00:52.669134 0xb6fb6010 MND mnode:1, fqdn:Xbrother ep:Xbrother:6030 port:6030 is created
01/01 00:00:52.670572 0xb6fb6010 WAL vgId:1, file:/home/td-engin/data/mnode/wal/wal0, restore success, wver:16
01/01 00:00:52.671074 0xb6fb6010 SDB vgId:1, sdb wal load success
01/01 00:00:52.671375 0xb6fb6010 SDB vgId:1, sdb start to check for integrity
01/01 00:00:52.671574 0xb6fb6010 SDB vgId:1, sdb:cluster is checked, rows:1
01/01 00:00:52.671741 0xb6fb6010 SDB vgId:1, sdb:dnodes is checked, rows:1
01/01 00:00:52.671992 0xb6fb6010 MND vgId:1, update mnodes epSet, numOfMnodes:1
01/01 00:00:52.672189 0xb6fb6010 MND vgId:1, mnodes epSet is set, num:1 inUse:0
01/01 00:00:52.672368 0xb6fb6010 MND vgId:1, mnode:1, fqdn:Xbrother shell:6030 peer:6035
01/01 00:00:52.672650 0xb6fb6010 SDB vgId:1, sdb:mnodes is checked, rows:1
01/01 00:00:52.672934 0xb6fb6010 SDB vgId:1, sdb:accounts is checked, rows:1
01/01 00:00:52.673086 0xb6fb6010 SDB vgId:1, sdb:users is checked, rows:3
01/01 00:00:52.673238 0xb6fb6010 SDB vgId:1, sdb:dbs is checked, rows:1
01/01 00:00:52.673391 0xb6fb6010 SDB vgId:1, sdb:vgroups is checked, rows:1
01/01 00:00:52.673535 0xb6fb6010 SDB vgId:1, sdb:stables is checked, rows:2
01/01 00:00:52.673677 0xb6fb6010 SDB vgId:1, sdb:ctables is checked, rows:4
01/01 00:00:52.673825 0xb6fb6010 SDB vgId:1, sdb is restored, mver:16 rows:15 tables:9
01/01 00:00:52.673992 0xb6fb6010 DND step:sdb is initialized
01/01 00:00:52.674592 0xb6fb6010 MND dnode:1 set access:0 to 0
01/01 00:00:52.674904 0xb6fb6010 DND step:balance is initialized
01/01 00:00:52.675090 0xb6fb6010 DND step:grant is initialized
01/01 00:00:52.675902 0xb6fb6010 DND step:show is initialized
01/01 00:00:52.676077 0xb6fb6010 MND mnode is initialized successfully
01/01 00:00:52.676370 0xb6fb6010 SDB vgId:1, work as mnode, replica:1
01/01 00:00:52.676666 0xb6fb6010 SDB vgId:1, mnode:1, Xbrother:6040
01/01 00:00:52.677450 0xb6fb6010 SDB vgId:1, mnode role changed from master to master
01/01 00:00:52.677618 0xb6fb6010 SDB vgId:1, update mnodes role, replica:1
01/01 00:00:52.677770 0xb6fb6010 SDB vgId:1, mnode:1, role:master
01/01 00:00:52.677930 0xb6fb6010 MND vgId:1, update mnodes epSet, numOfMnodes:1
01/01 00:00:52.678208 0xb6fb6010 MND vgId:1, mnodes epSet is set, num:1 inUse:0
01/01 00:00:52.678367 0xb6fb6010 MND vgId:1, mnode:1, fqdn:Xbrother shell:6030 peer:6035
01/01 00:00:52.679126 0xb6fb6010 DND dnode modules is initialized
01/01 00:00:52.679299 0xb6fb6010 HTP start http server ...
01/01 00:00:52.680118 0xb6fb6010 HTP http result queue is opened
01/01 00:00:52.683195 0xa1ae4450 HTP http server init success at 6041
01/01 00:00:52.683883 0xb6fb6010 MON monitor module start
01/01 00:00:52.684029 0xb6fb6010 DND step:dnode-modules is initialized
01/01 00:00:52.685842 0xb6fb6010 DND dnode shell rpc server is initialized
01/01 00:00:52.686000 0xb6fb6010 DND step:dnode-shell is initialized
01/01 00:00:52.686151 0xb6fb6010 DND dnode status timer is initialized
01/01 00:00:52.686270 0xb6fb6010 DND step:dnode-statustmr is initialized
01/01 00:00:52.686773 0xb6fb6010 DND dnode telemetry is initialized
01/01 00:00:52.687012 0xb6fb6010 DND step:dnode-telemetry is initialized
01/01 00:00:52.687136 0xb6fb6010 DND TDengine is initialized successfully
01/01 00:00:53.200369 0xa7af0450 MND dnode:1, from offline to online
01/01 00:00:53.692250 0xa8af2450 MND user:monitor login from 127.0.0.1, result:success

Bus error

**Comment by Feynman83** [comment]
message form serial console

# [ 2314.296320] Alignment trap: not handling instruction ed8a0a00 at [<b6e7560c>]
[ 2314.303519] 8<--- cut here ---
[ 2314.306661] Unhandled fault: alignment exception (0x801) at 0x018ca906
[ 2314.313210] pgd = 5fd349c6
[ 2314.316043] [018ca906] *pgd=8a272831

**Comment by Feynman83** [comment]
# cat /proc/cpu/alignment 
User:		6
System:		0 (0x0)
Skipped:	2
Half:		0
Word:		0
DWord:		4
Multi:		0
User faults:	2 (fixup)

**Comment by sangshuduo** [comment]
是代码有数据结构在arm32平台对齐的问题，因为我们这里没有相应硬件不好测试，你可以试试这里改一下，如果OK的话可以给我们提个 PR

$ git diff  
diff --git a/src/inc/taosmsg.h b/src/inc/taosmsg.h  
index 2dee6dc..8f9aa27 100644  
\--- a/src/inc/taosmsg.h  
+++ b/src/inc/taosmsg.h  
@@ -615,6 +615,7 @@ typedef struct {  
  int32\_t  maxtablesPerVnode;  
  int32\_t  maxVgroupsPerDb;  
  char     arbitrator\[TSDB\_EP\_LEN\];   // tsArbitrator  
\+  char     reserve\[2\];  
  char     timezone\[64\];              // tsTimezone  
  int64\_t  checkTime;                 // 1970-01-01 00:00:00.000  
  char     locale\[TSDB\_LOCALE\_LEN\];   // tsLocale

**Comment by Feynman83** [comment]
按照上面改了没有，还是报错
我coredump了下：
(gdb) bt
#0  0xb6ea554e in isNull (type=<error reading variable: Cannot access memory at address 0xb65>,
    val=<error reading variable: Cannot access memory at address 0xb69>) at /TDengine/src/inc/taosdef.h:206
#1  vectorRemainder (left=<error reading variable: Cannot access memory at address 0x11>,
    numLeft=<error reading variable: Cannot access memory at address 0xd>,
    leftType=<error reading variable: Cannot access memory at address 0x9>,
    right=<error reading variable: Cannot access memory at address 0x5>,
    numRight=<error reading variable: Cannot access memory at address 0x1de5>,
    rightType=<error reading variable: Cannot access memory at address 0x1de9>,
    output=<error reading variable: Cannot access memory at address 0x1ded>,
    order=<error reading variable: Cannot access memory at address 0x1df1>)
    at /TDengine/src/query/src/qArithmeticOperator.c:2265
Backtrace stopped: Cannot access memory at address 0x1de1

**Comment by Feynman83** [comment]
是对double 这个类型得指针地址没对齐照成的

**Comment by sangshuduo** [comment]
diff --git a/src/query/inc/qAst.h b/src/query/inc/qAst.h  
index 39af7261e..733a2375e 100644  
\--- a/src/query/inc/qAst.h  
+++ b/src/query/inc/qAst.h  
@@ -60,6 +60,7 @@ typedef struct SExprTraverseSupp {  
  
typedef struct tExprNode {  
  uint8\_t nodeType;  
\+  char    reserve\[3\];  
  union {  
    struct {  
      uint8\_t optr;             // filter operator  
 

试试这样行不行？

如果您有余力解决欢迎自己移植并贡献 PR 给 TDengine

**Comment by Feynman83** [comment]
#define ARRAY_LIST_OP_REM(left, right, _left_type, _right_type, len1, len2, out, op, _res_type, _ord) \
  {                                                                                                   \
    int32_t i = (_ord == TSDB_ORDER_ASC) ? 0 : MAX(len1, len2) - 1;                                   \
    int32_t step = (_ord == TSDB_ORDER_ASC) ? 1 : -1;                                                 \
                                                                                                      \
    if (len1 == (len2)) {                                                                             \
      for (; i >= 0 && i < (len2); i += step, (out) += 1) {                                           \
        if (isNull((char *)&(left[i]), _left_type) || isNull((char *)&(right[i]), _right_type)) {     \
          SET_DOUBLE_NULL(out);                                                                       \
          continue;                                                                                   \
        }                                                                                             \
        *(out) = (double)(left)[i] - ((int64_t)(((double)(left)[i]) / (right)[i])) * (right)[i];      \
      }                                                                                               \
    } else if (len1 == 1) {   

这些代码片段 left，right 都是void* 类型，是32bit在armv7 架构下，但是在 isNull 函数下

*(uint64_t *)val 这个操作设计到对64bit的读取，这样会不会成了非对齐的数据访问了

static FORCE_INLINE bool isNull(const char *val, int32_t type) {
  switch (type) {
    case TSDB_DATA_TYPE_BOOL:
      return *(uint8_t *)val == TSDB_DATA_BOOL_NULL;
    case TSDB_DATA_TYPE_TINYINT:
      return *(uint8_t *)val == TSDB_DATA_TINYINT_NULL;
    case TSDB_DATA_TYPE_SMALLINT:
      return *(uint16_t *)val == TSDB_DATA_SMALLINT_NULL;
    case TSDB_DATA_TYPE_INT:
      return *(uint32_t *)val == TSDB_DATA_INT_NULL;
    case TSDB_DATA_TYPE_BIGINT:
    case TSDB_DATA_TYPE_TIMESTAMP:
      return *(uint64_t *)val == TSDB_DATA_BIGINT_NULL;
    case TSDB_DATA_TYPE_FLOAT:
      return *(uint32_t *)val == TSDB_DATA_FLOAT_NULL;
    case TSDB_DATA_TYPE_DOUBLE:
      return *(uint64_t *)val == TSDB_DATA_DOUBLE_NULL;

**Comment by Feynman83** [comment]
void arithmeticTreeTraverse(tExprNode *pExprs, int32_t numOfRows, char *pOutput, void *param, int32_t order,
                                char *(*getSourceDataBlock)(void *, const char*, int32_t)) {
  if (pExprs == NULL) {
    return;
  }

  tExprNode *pLeft = pExprs->_node.pLeft;
  tExprNode *pRight = pExprs->_node.pRight;

  /* the left output has result from the left child syntax tree */
  char *pLeftOutput = (char*)malloc(sizeof(int64_t) * numOfRows);
  if (pLeft->nodeType == TSQL_NODE_EXPR) {
    arithmeticTreeTraverse(pLeft, numOfRows, pLeftOutput, param, order, getSourceDataBlock);
  }

  /* the right output has result from the right child syntax tree */
  char *pRightOutput = malloc(sizeof(int64_t) * numOfRows);
  char *pdata = malloc(sizeof(int64_t) * numOfRows);


在这个函数中 pdata 这个内存都忘了释放了

**Comment by sangshuduo** [comment]
@Feynman83 现在还有问题吗？

**Comment by sangshuduo** [comment]
close as no reponse for a long time. please open it if still need help.
