### ISSUE TITLE
批量创建数据表失败

### ISSUE THREAD

**Issue by opjk** [taosdata/TDengine#4915]
**Bug Description**
按照文档说明 批量创建数据表
CREATE TABLE [IF NOT EXISTS] tb_name1 USING stb_name TAGS (tag_value1, ...) tb_name2 USING stb_name TAGS (tag_value2, ...) ...;

只有排在sql首位的表创建成功，后面的表都失败了。

**Comment by sangshuduo** [comment]
请问参考的是哪个文档？

**Comment by sangshuduo** [comment]
批量建表功能将在 2.0.14.0 开始支持

**Comment by opjk** [comment]
哦哦，查看一下 版本，用的 2.0.13.0 版本， 14版本能下载了么？

**Comment by sangshuduo** [comment]
@opjk 正在流程中，很快就会发布
