### ISSUE TITLE
Some queries in real scenarios (continuous query, last record, subquery, subscribe)

### ISSUE THREAD

**Issue by Janus-Xu** [taosdata/TDengine#492]
版本 1.6.1.7
场景：测试单区域4个温湿度传感器，一共8个区域；
1、间隔获取固定窗口内数据新增量，记录数据丢包情况；
2、系统实时刷新(间隔5秒内可接受)获取各区域最新的平均温湿度数据值；

表结构：Stable  th_sensor  temp,hum为遥测温湿度；
tag: sp区域；sn传感器编号; 创建32个子表对应；

Q1：创建子表不方便；
这一批sql是代码批量生成的，th1-th32，但下次新增传感器建表，如何快速按照之前的命名方式，了解到下一个该33了？
如果有模板名称会简单不少；在stable中定义子表范式类似th[i=1,i++],系统自动生成下一个子表名称，创建时就关心tag就可以了；

Q2：如何同时查看子表的data和tag？tag值查不到，不知道现在tag里面type有哪些备选值，目前只有group by 才能看到；比较麻烦；

Q3：连续查询功能无返回数据
想用连续查询返回数据结果给server，参照文档创建
CREATE TABLE QUERY_RES AS  SELECT COUNT(*)  FROM th_sensor group by sn INTERVAL(1M) SLIDING(30S) 
无数据返回，至于调用API taos_stream没有找到相关具体介绍
![image](https://user-images.githubusercontent.com/6883877/64629229-641cd380-d425-11e9-8b6f-1fa5b1152125.png)

Q4：时间戳相同，Last默认选出的唯一一条是怎么来的？
标红是last查出来的唯一一条，分组后对应4条时间写入相同
![image](https://user-images.githubusercontent.com/6883877/64632070-fd9ab400-d42a-11e9-8769-a89e89adddfd.png)
另外加上函数以后怎么分别起别名？

Q5：区域最新的平均值无法操作
在Last基础上做平均；试了子查询好像不支持；
![image](https://user-images.githubusercontent.com/6883877/64632090-05f2ef00-d42b-11e9-8fec-eb432d1f1369.png)

Q6：发布订阅
还没尝试，有具体例子么？订阅和sql定时查询数据性能对比有么

**Comment by guanshengliang** [comment]
Q1:通过SQL语句来描述子表范式非常麻烦，传感器一定会与一个唯一标志，不论是ID或者是多个TAG的组合，可以通过这些生成表名
Q2:通过下图中的语句可以查看各表的TAG，如果需要TAG和DATA同时显示，需要通过超级表查询
![image](https://user-images.githubusercontent.com/28882257/64661715-5b092200-d478-11e9-954b-f4638a10b073.png)
![image](https://user-images.githubusercontent.com/28882257/64661755-868c0c80-d478-11e9-93f0-c9c0bfaf4584.png)

**Comment by guanshengliang** [comment]
Q3:目前还不支持GroupBy操作，此项功能近期会开发
Q4:对于超级表，如果存在多个表的最后时间戳相同，last(*)随机选取其中一条
Q5:目前不支持子查询工作，下个大版本会增加SQL Functions之间的计算，也包括子查询
Q6:近期会对订阅功能进行改造，也在下个大版本中支持，改造分两个阶段
+ 时间驱动的订阅，订阅内容支持SQL语句、支持超级表，这个阶段订阅通过sql定时查询来实现
+ 事件驱动的订阅，这个阶段订阅通过触发器来实现，性能会更好

**Comment by Janus-Xu** [comment]
> Q3:目前连续查询还不支持GroupBy操作，此项功能近期会开发
> Q4:对于超级表，如果存在多个表最后时间戳相同的情况，last(*)随机选取其中一条
> Q5:目前不支持子查询工作，下个大版本会增加SQL Functions之间的计算，也包括子查询
> Q6:近期会对订阅功能进行改造，也在下个大版本中支持，改造分两个阶段
> 
> * 时间驱动的订阅，订阅内容支持SQL语句、支持超级表，这个阶段订阅通过sql定时查询来实现
> * 事件驱动的订阅，这个阶段订阅通过触发器来实现，性能会更好

去掉group by 还是没数据返回；
![image](https://user-images.githubusercontent.com/6883877/64670620-6409eb80-d498-11e9-910d-c8bb5a6c78b1.png)

其他的问题基本了解了，至于您说迭代feature，下个大版本预计什么时间发布？
如果是现在使用的话，上面的两个场景有什么建议的方案么？
目前看好像没法再tdengine中完成数据处理，需要再在code中自己做再层业务了

**Comment by guanshengliang** [comment]
Q3:目前连续查询还不支持GroupBy操作，`预计11月初`
Q5:目前不支持子查询工作，下个大版本会增加SQL Functions之间的计算，也包括子查询，`预计11月初`
Q6:近期会对订阅功能进行改造，也在下个大版本中支持，改造分两个阶段
+ 时间驱动的订阅，订阅内容支持SQL语句、支持超级表，这个阶段订阅通过sql定时查询来实现 `预计10月中`
+ 事件驱动的订阅，这个阶段订阅通过触发器来实现，性能会更好 `预计12月底`

**Comment by guanshengliang** [comment]
我的同事 @localvar 正在开展这方面的研发工作
等C语言版本稳定之后，会陆续支持C#和Java语言
