### ISSUE TITLE
add NodeJS Connector to Node-Red

### ISSUE THREAD

**Issue by kevinpan45** [taosdata/TDengine#4923]
参考
https://flows.nodered.org/add/node

**Comment by kevinpan45** [comment]
https://github.com/kp45-tech/node-red-contrib-tdengine
我已经实现了

**Comment by sangshuduo** [comment]
> https://github.com/kp45-tech/node-red-contrib-tdengine 我已经实现了

welcome to contribute to TDengine as a PR

**Comment by kevinpan45** [comment]
#9433
