### ISSUE TITLE
查询字段200的表，返回结果不完整，出现Query interrupted的疑似报错

### ISSUE THREAD

**Issue by Murphy-Claus** [taosdata/TDengine#4926]
**Bug Description**
查询字段200的表，返回结果不完整，出现Query interrupted的疑似报错

**To Reproduce**
1.创建表
CREATE TABLE IF NOT EXISTS foo (recordTime TIMESTAMP,v1 INT,v2 INT,v3 INT,v4 INT,v5 INT,v6 INT,v7 INT,v8 INT,v9 INT,v10 INT,v11 INT,v12 INT,v13 INT,v14 INT,v15 INT,v16 INT,v17 INT,v18 INT,v19 INT,v20 INT,v21 INT,v22 INT,v23 INT,v24 INT,v25 INT,v26 INT,v27 INT,v28 INT,v29 INT,v30 INT,v31 INT,v32 INT,v33 INT,v34 INT,v35 INT,v36 INT,v37 INT,v38 INT,v39 INT,v40 INT,v41 INT,v42 INT,v43 INT,v44 INT,v45 INT,v46 INT,v47 INT,v48 INT,v49 INT,v50 INT,v51 INT,v52 INT,v53 INT,v54 INT,v55 INT,v56 INT,v57 INT,v58 INT,v59 INT,v60 INT,v61 INT,v62 INT,v63 INT,v64 INT,v65 INT,v66 INT,v67 INT,v68 INT,v69 INT,v70 INT,v71 INT,v72 INT,v73 INT,v74 INT,v75 INT,v76 INT,v77 INT,v78 INT,v79 INT,v80 INT,v81 INT,v82 INT,v83 INT,v84 INT,v85 INT,v86 INT,v87 INT,v88 INT,v89 INT,v90 INT,v91 INT,v92 INT,v93 INT,v94 INT,v95 INT,v96 INT,v97 INT,v98 INT,v99 INT,v100 INT,v101 INT,v102 INT,v103 INT,v104 INT,v105 INT,v106 INT,v107 INT,v108 INT,v109 INT,v110 INT,v111 INT,v112 INT,v113 INT,v114 INT,v115 INT,v116 INT,v117 INT,v118 INT,v119 INT,v120 INT,v121 INT,v122 INT,v123 INT,v124 INT,v125 INT,v126 INT,v127 INT,v128 INT,v129 INT,v130 INT,v131 INT,v132 INT,v133 INT,v134 INT,v135 INT,v136 INT,v137 INT,v138 INT,v139 INT,v140 INT,v141 INT,v142 INT,v143 INT,v144 INT,v145 INT,v146 INT,v147 INT,v148 INT,v149 INT,v150 INT,v151 INT,v152 INT,v153 INT,v154 INT,v155 INT,v156 INT,v157 INT,v158 INT,v159 INT,v160 INT,v161 INT,v162 INT,v163 INT,v164 INT,v165 INT,v166 INT,v167 INT,v168 INT,v169 INT,v170 INT,v171 INT,v172 INT,v173 INT,v174 INT,v175 INT,v176 INT,v177 INT,v178 INT,v179 INT,v180 INT,v181 INT,v182 INT,v183 INT,v184 INT,v185 INT,v186 INT,v187 INT,v188 INT,v189 INT,v190 INT,v191 INT,v192 INT,v193 INT,v194 INT,v195 INT,v196 INT,v197 INT,v198 INT,v199 INT,v200 INT,v201 INT,v202 INT,v203 INT,v204 INT,v205 INT,v206 INT,v207 INT,v208 INT,v209 INT,v210 INT,v211 INT,v212 INT,v213 INT,v214 INT,v215 INT,v216 INT,v217 INT,v218 INT,v219 INT,v220 INT,v221 INT,v222 INT,v223 INT,v224 INT);
注意：当前字段是我们的需求，建议测试的时候使用更多的字段；
2.插入数据
      每隔10秒插入一条记录，尽可能多插入，我们的环境是24天的数据
3.查询表
select v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12,v13,v14,v15,v16,v17,v18,v19,v20,v21,v22,v23,v24,v25,v26,v27,v28,v29,v30,v31,v32,v33,v34,v35,v36,v37,v38,v39,v40,v41,v42,v43,v44,v45,v46,v47,v48,v49,v50,v51,v52,v53,v54,v55,v56,v57,v58,v59,v60,v61,v62,v63,v64,v65,v66,v67,v68,v69,v70,v71,v72,v73,v74,v75,v76,v77,v78,v79,v80,v81,v82,v83,v84,v85,v86,v87,v88,v89,v90,v91,v92,v93,v94,v95,v96,v97,v98,v99,v100,v101,v102,v103,v104,v105,v106,v107,v108,v109,v110,v111,v112,v113,v114,v115,v116,v117,v118,v119,v120,v121,v122,v123,v124,v125,v126,v127,v128,v129,v130,v131,v132,v133,v134,v135,v136,v137,v138,v139,v140,v141,v142,v143,v144,v145,v146,v147,v148,v149,v150,v151,v152,v153,v154,v155,v156,v157,v158,v159,v160,v161,v162,v163,v164,v165,v166,v167,v168,v169,v170,v171,v172,v173,v174,v175,v176,v177,v178,v179,v180,v181,v182,v183,v184,v185,v186,v187,v188,v189,v190,v191,v192,v193,v194,v195,v196,v197,v198,v199,v200,v201,v202,v203,v204,v205,v206,v207,v208,v209,v210,v211,v212,v213,v214,v215,v216,v217,v218,v219,v220,v221,v222,v223,v224,recordTime from foo where recordTime > 2021-01-15 00:00:00 and recordTime <= 2021-01-16 00:00:00;
时间可做改动

**Expected Behavior**
查询字段200的表，返回结果不完整，出现Query interrupted的疑似报错

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu18.04]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 11.13]

**Additional Context**

**Comment by sangshuduo** [comment]
微信群已回复：刷屏太慢，超过6s 钟客户端没有向服务器拉取数据，服务器自动关闭了查询句柄，所以报 invalid handle 错误。你可以把查询结果从定向到文件中，避免刷屏导致的超时。
