### ISSUE TITLE
How does taosdata store and compress large repetitive metrics?

### ISSUE THREAD

**Issue by super-sponge** [taosdata/TDengine#493]
我在项目中经常会存储一些固定指标，例如监控hbase的数据，其中有regionserver在线数量，region offline数量这些值绝大部分都是固定值，只有在出现异常时才会有变动。 我很想了解对于这种绝大部分都是固定值的数据，tasodata有没有特殊的处理。是通过选择对应的压缩算法来降低存储呢？还是采用特殊的数据存储方式？

**Comment by guanshengliang** [comment]
没有针对这类数据做优化，从数据层面上不太容易识别数据的变化趋势
但是，对于相同数据，尤其是整型数据的压缩比很好。
