### ISSUE TITLE
query tags from table

### ISSUE THREAD

**Issue by MelodyI** [taosdata/TDengine#4937]
如何查询表的tags

**Comment by sangshuduo** [comment]
describe \<tbname>

**Comment by MelodyI** [comment]
taos> describe tbnameA;
|Field              |        Type        |   Length    |              Note              |
|---|---|---|---|
 ts                             | TIMESTAMP          |           8 |                                |
 qa                             | DOUBLE             |           8 |                                |
 factory                        | NCHAR              |          10 | TAG                            |
 line                           | NCHAR              |          10 | TAG                            |
