### ISSUE TITLE
go开启1000个协程,同时向随机数据表写入,会出现连接错误!

### ISSUE THREAD

**Issue by binshuilong** [taosdata/TDengine#4949]
1.新增代码
![image](https://user-images.githubusercontent.com/39979820/104981576-d5ba5800-5a43-11eb-889c-1dda906c5cb3.png)
2.出现错误
![image](https://user-images.githubusercontent.com/39979820/104981600-e23eb080-5a43-11eb-8e0d-22528a53b58e.png)
3.版本信息
ver 2.0.13.0
docker安装版

**Comment by sangshuduo** [comment]
目前可以尝试修改 taos.cfg 中 maxTmrCtrl ，后续会有更好的机制来支持更多并发。
