### ISSUE TITLE
query time question

### ISSUE THREAD

**Issue by 279zlj** [taosdata/TDengine#4951]
目前有一个tdengine集群，三节点，超级表结构，总的1500w+数据，但是查询挺慢的。我用导出csv文件的方法读出数据也需要50+s快一分钟的时间。想知道是有什么原因
![image](https://user-images.githubusercontent.com/34158264/104982377-7d845580-5a45-11eb-9fa5-a39dc6b43c2c.png)
使用的库：
![image](https://user-images.githubusercontent.com/34158264/104982499-c50ae180-5a45-11eb-91d9-f1d32cdbb593.png)

**Comment by 279zlj** [comment]
表接口如下：
![image](https://user-images.githubusercontent.com/34158264/104982673-216e0100-5a46-11eb-9211-732ba290c5e3.png)

**Comment by 279zlj** [comment]
节点1：
20核 64G ubuntu
节点2：
32核 125G ubuntu
节点3：
12核 64G centos
查询语句：
select ts, lon, lat, mmsi from dtest.info where ts > “” and ts < “” >> data.csv 数据量：1000W+ 耗时：50+s

**Comment by sangshuduo** [comment]
同样的查询语句 >> /dev/null 大概多长时间？

**Comment by sangshuduo** [comment]
同样的查询语句 >> /dev/null 大概多长时间？

**Comment by 279zlj** [comment]
> 同样的查询语句 >> /dev/null 大概多长时间？

差不多时间，导出data.csv 53s ，/dev/null 51s

**Comment by sangshuduo** [comment]
那说明挺正常的呀

**Comment by 279zlj** [comment]
> 那说明挺正常的呀

1000+W读出需要1分钟算正常耗时吗？

**Comment by sangshuduo** [comment]
每秒钟30万还不够吗？
