### ISSUE TITLE
request more sql functions

### ISSUE THREAD

**Issue by cmdares** [taosdata/TDengine#4958]
为了使用tdengine在物联场景上替代当下流行的技术如clickhouse，greenplum等方案，建议考虑sql能力尽量兼容或贴合，比如可否对标支持sql2003标准。也可借鉴gp和ch的常用函数，如时间、位置、距离、数组等优秀的函数。
看好td的引擎，存储，运维，整合的四大优势，在这点上来看是其他平台所不能同时具备的。希望官方希望能够补全和延伸SQL的能力，使得该平台更为完善和易用。
同时对向量化和simd这两种技术不明觉厉，想知道在这块的应用方面，td引擎是否有更好的使用和突破。
最后感谢团队的付出!
持续关注该项目的进步。

**Comment by sangshuduo** [comment]
谢谢你的建议
