### ISSUE TITLE
where is the sample code for (publisher/subscriber)

### ISSUE THREAD

**Issue by qhfGitHub** [taosdata/TDengine#496]
数据订阅的示例代码具体在哪个文件夹下

**Comment by guanshengliang** [comment]
Sample code for data subscription has not been announced
Sample code will be released after the recent refactoring of the data subscription code

**Comment by guanshengliang** [comment]
it may take 1-2 months.

**Comment by guanshengliang** [comment]
我的同事 @localvar 正在开展这方面的研发工作
等C语言版本稳定之后，会陆续支持C#和Java语言

**Comment by localvar** [comment]
@qhfGitHub ，示例代码已提交到：https://github.com/taosdata/TDengine/blob/develop/tests/examples/c/subscribe.c
