### ISSUE TITLE
Java driver will crash when it is continuously inserted into the database

### ISSUE THREAD

**Issue by jiumoji** [taosdata/TDengine#4970]
**Bug Description**
使用JAVA驱动持续向数据库插入数据, 目标是录入1000亿条数据, 经过一段时间(大约一天)录入几百亿数据后, JAVA虚拟机崩溃了. 在我的服务器上每次运行必定复现. 
崩溃日志见附件的hs_err_pid45240.log

**To Reproduce**
建表语句为: 
create table safety_realtime_history(ts timestamp,value FLOAT,alarm BINARY(64)) TAGS (point_id BINARY(64), mine_code BINARY(64)) ;
java版的写入程序见附件的TaosTest.java
驱动版本为
<dependency>
	<groupId>com.taosdata.jdbc</groupId>
	<artifactId>taos-jdbcdriver</artifactId>
	<version>2.0.15</version>
</dependency>

**Environment (please complete the following information):**
 - OS:  CentOS 7.8
 - Memory, CPU, current Disk Space : 64 cores, 256GB, 15TB
 - TDengine Version :  [community/TDengine-server-2.0.3.1-Linux-x64.rpm[][
[hs_err_pid45240.log](https://github.com/taosdata/TDengine/files/5841966/hs_err_pid45240.log)
[TaosTest.log](https://github.com/taosdata/TDengine/files/5841976/TaosTest.log)

](url)

**Comment by zyyang-taosdata** [comment]
从crash信息可以看到是的应用程序触发了某个段错误，在你的centos7.8系统下应该会生成一个core.xxxx，xxxx为那个java应用程序的pid号，请将这个core文件添加到这个issue中来，我需要这个core文件来定位错误，谢谢

**Comment by zyyang-taosdata** [comment]
https://github.com/taosdata/TDengine/issues/4916

**Comment by zyyang-taosdata** [comment]
this issue was closed due to a lack of maintenance and sufficient information for a long time
