### ISSUE TITLE
Invalid result set pointer

### ISSUE THREAD

**Issue by flykarry** [taosdata/TDengine#4974]
**Bug Description**
5线程插入，报异常

**To Reproduce**
``` java
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.time.DateFormatUtils;

import java.sql.*;
import java.util.*;
import java.util.concurrent.CountDownLatch;
public class JDBCDemo {
    private static String host;
    private static String driverType = "jni";
    private static final String dbName = "tecs";
    private Connection connection;

    public static void main(String[] args) throws InterruptedException {
//        for (int i = 0; i < args.length; i++) {
//            if ("-host".equalsIgnoreCase(args[i]) && i < args.length - 1)
//                host = args[++i];
//            if ("-driverType".equalsIgnoreCase(args[i]) && i < args.length - 1) {
//                driverType = args[++i];
//                if (!"jni".equalsIgnoreCase(driverType) && !"restful".equalsIgnoreCase(driverType))
//                    printHelp();
//            }
//        }
//
//        if (host == null) {
//            printHelp();
//        }

        host = "e41850e95e53";

        JDBCDemo demo = new JDBCDemo();
        demo.init();
        demo.createDatabase();
        demo.useDatabase();
        demo.dropTable();
        demo.createTable();
        demo.insertBatch();
//        demo.select();
//        demo.dropTable();
        demo.close();
        Thread.sleep(1000 * 60 * 60);
    }

    CountDownLatch countDownLatch = new CountDownLatch(5);

    private void insertBatch() throws InterruptedException {
        Calendar calendar = Calendar.getInstance();
        calendar.add(Calendar.MINUTE, -5);
        List<String> ids = new ArrayList<>();
        for (int i = 0; i < 10000; i++) {
            countDownLatch = new CountDownLatch(5);
            String format = DateFormatUtils.format(calendar.getTime(), "yyyy-MM-dd HH:mm:ss");
            insertSingle(ids, format, i);
            insertSingle(ids, format, i);
            insertSingle(ids, format, i);
            insertSingle(ids, format, i);
            insertSingle(ids, format, i);
            countDownLatch.await();
            Thread.sleep(1000);
            System.out.println("第" + i + "次五千万数据插入完毕");
        }
    }

    private void insertSingle(List<String> ids, String format, int index) {
        new Thread(() -> {
            System.out.println(Thread.currentThread().getName() + "开始插入数据");
            String sql = "";
            for (int j = 0; j < 10000000; j++) {
                if (index == 0) {
                    ids.add(UUID.randomUUID().toString().replace("-", ""));
                }
                if (j % 500 == 0 && StringUtils.isNotEmpty(sql)) {
                    sql = "insert into basedata values" + sql;
                    exuete(sql);
                    sql = "";
                } else {
                    sql += "('" + format + "', " + new Random().nextDouble() * 10000 + ", '" + ids.get(j) + "')";
                }
                if (j % 100000 == 0) {
                    System.out.println(Thread.currentThread().getName() + "完成" + j);
                }
            }
            if (StringUtils.isNotEmpty(sql)) {
                sql = "insert into basedata values" + sql;
                exuete(sql);
            }
            countDownLatch.countDown();
            System.out.println(Thread.currentThread().getName() + "插入完毕");
        }).start();
    }

    private void exuete(String sql) {
        try (Statement statement = connection.createStatement()) {
            long start = System.currentTimeMillis();
            boolean execute = statement.execute(sql);
            long end = System.currentTimeMillis();
//            printSql(sql, execute, (end - start));
        } catch (SQLException e) {
            e.printStackTrace();

        }
    }

    private void init() {
        // get connection
        try {
            String url = "jdbc:TAOS://" + host + ":6030/?user=root&password=taosdata";
            if (driverType.equals("restful")) {
                Class.forName("com.taosdata.jdbc.rs.RestfulDriver");
                url = "jdbc:TAOS-RS://" + host + ":6041/?user=root&password=taosdata";
            } else {
                Class.forName("com.taosdata.jdbc.TSDBDriver");
            }
            Properties properties = new Properties();
            properties.setProperty("charset", "UTF-8");
            properties.setProperty("locale", "en_US.UTF-8");
            properties.setProperty("timezone", "UTC-8");
            System.out.println("get connection starting...");
            connection = DriverManager.getConnection(url, properties);
            if (connection != null)
                System.out.println("[ OK ] Connection established.");
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
    }

    private void createDatabase() {
        String sql = "create database if not exists " + dbName;
        exuete(sql);
    }

    private void useDatabase() {
        String sql = "use " + dbName;
        exuete(sql);
    }

    private void select() {
        final String sql = "select * from basedata";
        executeQuery(sql);
    }

    private void executeQuery(String sql) {
        try (Statement statement = connection.createStatement()) {
            long start = System.currentTimeMillis();
            ResultSet resultSet = statement.executeQuery(sql);
            long end = System.currentTimeMillis();
            printSql(sql, true, (end - start));
            printResult(resultSet);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void printResult(ResultSet resultSet) throws SQLException {
        ResultSetMetaData metaData = resultSet.getMetaData();
        while (resultSet.next()) {
            for (int i = 1; i <= metaData.getColumnCount(); i++) {
                String columnLabel = metaData.getColumnLabel(i);
                String value = resultSet.getString(i);
                System.out.printf("%s: %s\t", columnLabel, value);
            }
            System.out.println();
        }
    }


    private void createTable() {
        final String sql = "create table basedata (ts timestamp, value double, paramId BINARY(36))";
        exuete(sql);
    }

    private void printSql(String sql, boolean succeed, long cost) {
        System.out.println("[ " + (succeed ? "OK" : "ERROR!") + " ] time cost: " + cost + " ms, execute statement ====> " + sql);
    }


    private void close() {
        try {
            if (connection != null) {
                this.connection.close();
                System.out.println("connection closed.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void dropTable() {
        final String sql = "drop table if exists " + dbName + ".basedata";
        exuete(sql);
    }

    private static void printHelp() {
        System.out.println("Usage: java -jar JdbcDemo.jar -host <hostname> -driverType <jni|restful>");
        System.exit(0);
    }

    private void insert() {
        final String sql = "insert into basedata values(now, 20.5, 'uuidtest1111111')";
        exuete(sql);
    }


}
```

**Expected Behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/14309127/105279945-a6425180-5be3-11eb-9a5c-77f87fc91879.png)

**Environment (please complete the following information):**
 - OS:  ubuntu 16.04
 - Memory, CPU, current Disk Space
 - TDengine Version 2.0.14.0

**Additional Context**

**Comment by flykarry** [comment]
我这个使用方法好像不对，但是这个异常也确实存在

**Comment by xiaopingcs** [comment]
我这边没有复现这个问题，这个程序运行非常慢
你这个程序也有点问题。
1. 所有时间戳都是一样的，所以你程序最多只能写入一条记录
2. batchSize可能会超过限制，我们目前单个sql语句最大长度是1M, 需要在taos.cfg里面配置。

建议你先把循环次数改小 batchSize方法里面的循环次数先改成10，insertSingle 方法里面的循环改成100。先看看程序能不能运行完成并达到预期效果。如果可以完成再将循环次数还原。如果还是有同样的错误，我们这边再分析。

**Comment by flykarry** [comment]
> 我这边没有复现这个问题，这个程序运行非常慢
> 你这个程序也有点问题。
> 
> 1. 所有时间戳都是一样的，所以你程序最多只能写入一条记录
> 2. batchSize可能会超过限制，我们目前单个sql语句最大长度是1M, 需要在taos.cfg里面配置。
> 
> 建议你先把循环次数改小 batchSize方法里面的循环次数先改成10，insertSingle 方法里面的循环改成100。先看看程序能不能运行完成并达到预期效果。如果可以完成再将循环次数还原。如果还是有同样的错误，我们这边再分析。

后来我发现了他插入的只有一个点了，所以我这个使用方法确实不对
不过这个异常确实是在，而且是跑一段时间会出现，出现后程序就会停止了，任何线程都不写数了。我已经复现3次以上了
这个问题不是立刻出现，就是运行一段时间出现的，运行时长也不一定，docker占用空间从在400M以下发生的，循环改小了之后出现的概率就低了
sql没有超过长度

**Comment by flykarry** [comment]
> 我这边没有复现这个问题，这个程序运行非常慢
> 你这个程序也有点问题。
> 
> 1. 所有时间戳都是一样的，所以你程序最多只能写入一条记录
> 2. batchSize可能会超过限制，我们目前单个sql语句最大长度是1M, 需要在taos.cfg里面配置。
> 
> 建议你先把循环次数改小 batchSize方法里面的循环次数先改成10，insertSingle 方法里面的循环改成100。先看看程序能不能运行完成并达到预期效果。如果可以完成再将循环次数还原。如果还是有同样的错误，我们这边再分析。

看下这个，也会报哪个错

` java
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.time.DateFormatUtils;

import java.sql.*;
import java.util.*;
import java.util.concurrent.CountDownLatch;

public class JDBCDemo {
    private static String host;
    private static String driverType = "jni";
    private static final String dbName = "tecs";
    private Connection connection;

    public static void main(String[] args) throws InterruptedException {
//        for (int i = 0; i < args.length; i++) {
//            if ("-host".equalsIgnoreCase(args[i]) && i < args.length - 1)
//                host = args[++i];
//            if ("-driverType".equalsIgnoreCase(args[i]) && i < args.length - 1) {
//                driverType = args[++i];
//                if (!"jni".equalsIgnoreCase(driverType) && !"restful".equalsIgnoreCase(driverType))
//                    printHelp();
//            }
//        }
//
//        if (host == null) {
//            printHelp();
//        }

        host = "e41850e95e53";

        JDBCDemo demo = new JDBCDemo();
        demo.init();
        demo.createDatabase();
        demo.useDatabase();
//        demo.dropTable();
//        demo.createTable();
        demo.insertBatch();
//        demo.select();
//        demo.dropTable();
        Thread.sleep(1000 * 60 * 60);
        demo.close();
    }


    private void insertBatch() throws InterruptedException {
        Calendar calendar = Calendar.getInstance();
        calendar.add(Calendar.MINUTE, -5);
        for (int i = 0; i < 100; i++) {
            insertSingle();
        }
        Thread.sleep(1000);
    }

    private void insertSingle() {
        new Thread(() -> {
            System.out.println(Thread.currentThread().getName() + "开始插入数据");
            String sql = "";
            for (int j = 0; j < 1000000; j++) {
                String id = UUID.randomUUID().toString().replace("-", "");
                Calendar calendar = Calendar.getInstance();
                for (int i = 0; i < 10000; i++) {
                    if (i % 500 == 0 && StringUtils.isNotEmpty(sql)) {
                        sql = "INSERT INTO base_" + id + " USING basedata TAGS ('" + id + "') VALUES" + sql;
                        exuete(sql);
                        sql = "";
                    } else {
                        calendar.add(Calendar.MINUTE, -new Random().nextInt(10));
                        String format = DateFormatUtils.format(calendar.getTime(), "yyyy-MM-dd HH:mm:ss");
                        sql += " ('" + format + "', " + new Random().nextDouble() * 10000 + ")";
                    }
                }
                System.out.println(Thread.currentThread().getName() + ",第" + j + "个参数：" + id + "完成10000条写入");
            }
            System.out.println(Thread.currentThread().getName() + "插入完毕");
        }).start();
    }

    private void exuete(String sql) {
        try (Statement statement = connection.createStatement()) {
            long start = System.currentTimeMillis();
            boolean execute = statement.execute(sql);
            long end = System.currentTimeMillis();
//            printSql(sql, execute, (end - start));
        } catch (SQLException e) {
            e.printStackTrace();

        }
    }

    private void init() {
        // get connection
        try {
            String url = "jdbc:TAOS://" + host + ":6030/?user=root&password=taosdata";
            if (driverType.equals("restful")) {
                Class.forName("com.taosdata.jdbc.rs.RestfulDriver");
                url = "jdbc:TAOS-RS://" + host + ":6041/?user=root&password=taosdata";
            } else {
                Class.forName("com.taosdata.jdbc.TSDBDriver");
            }
            Properties properties = new Properties();
            properties.setProperty("charset", "UTF-8");
            properties.setProperty("locale", "en_US.UTF-8");
            properties.setProperty("timezone", "UTC-8");
            System.out.println("get connection starting...");
            connection = DriverManager.getConnection(url, properties);
            if (connection != null)
                System.out.println("[ OK ] Connection established.");
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
    }

    private void createDatabase() {
        String sql = "create database if not exists " + dbName;
        exuete(sql);
    }

    private void useDatabase() {
        String sql = "use " + dbName;
        exuete(sql);
    }

    private void select() {
        final String sql = "select * from basedata";
        executeQuery(sql);
    }

    private void executeQuery(String sql) {
        try (Statement statement = connection.createStatement()) {
            long start = System.currentTimeMillis();
            ResultSet resultSet = statement.executeQuery(sql);
            long end = System.currentTimeMillis();
            printSql(sql, true, (end - start));
            printResult(resultSet);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void printResult(ResultSet resultSet) throws SQLException {
        ResultSetMetaData metaData = resultSet.getMetaData();
        while (resultSet.next()) {
            for (int i = 1; i <= metaData.getColumnCount(); i++) {
                String columnLabel = metaData.getColumnLabel(i);
                String value = resultSet.getString(i);
                System.out.printf("%s: %s\t", columnLabel, value);
            }
            System.out.println();
        }
    }


    private void createTable() {
        final String sql = "create table basedata (ts timestamp, value double) TAGS (paramId binary(36));";
        exuete(sql);
    }

    private void printSql(String sql, boolean succeed, long cost) {
        System.out.println("[ " + (succeed ? "OK" : "ERROR!") + " ] time cost: " + cost + " ms, execute statement ====> " + sql);
    }


    private void close() {
        try {
            if (connection != null) {
                this.connection.close();
                System.out.println("connection closed.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void dropTable() {
        final String sql = "drop table if exists " + dbName + ".basedata";
        exuete(sql);
    }

    private static void printHelp() {
        System.out.println("Usage: java -jar JdbcDemo.jar -host <hostname> -driverType <jni|restful>");
        System.exit(0);
    }

    private void insert() {
        final String sql = "insert into basedata values(now, 20.5, 'uuidtest1111111')";
        exuete(sql);
    }


}
`

**Comment by xiaopingcs** [comment]
@zyyang-taosdata 你帮看看，我这边还是复现不了，只会出connection太多会被强制关闭的错

**Comment by zyyang-taosdata** [comment]
好的，我看一下，这个问题非常有价值
