### ISSUE TITLE
query tags from table

### ISSUE THREAD

**Issue by MelodyI** [taosdata/TDengine#4975]
taos> describe tbnameA;
|Field|Type|Length|Note|
|---|---|---|---|
|ts|TIMESTAMP|8||
|qa|DOUBLE|8||
|factory|NCHAR|10|TAG|
|line|NCHAR|10|TAG|

taos> select ts, qa factory, line from tbnameA;

DB error: invalid SQL: functions mixed up in table query

**Comment by Aries-Lee1991** [comment]
please add the log and the version info. .

**Comment by sangshuduo** [comment]
a comma missed between qa and factory
