### ISSUE TITLE
一个超级表的子表可以存储间隔不同吗？一个子表可以更改存储间隔吗？

### ISSUE THREAD

**Issue by flykarry** [taosdata/TDengine#4976]
**Performance Issue** 
一个超级表的子表可以存储间隔不同吗？一个子表可以更改存储间隔吗？
问题1：比如电力系统，重点仪表采集间隔短，非重点采集间隔长，但是数据结构一致，可以用同一个超级表吗？
问题2：比如因个别原因，需要加快采集速度，但是存储结构没有变，现在数据库能否支持？性能如何？

**Comment by sangshuduo** [comment]
默认精度是毫秒，也可以在创建数据库的时候指定精度为微秒。
