### ISSUE TITLE
initTableMemIterator assertion failed

### ISSUE THREAD

**Issue by chinajuanbob** [taosdata/TDengine#4978]
on v2.0.8.0

Hit this log:

taosd: /home/ubuntu/ver_release_workspace/TDinternal/community/src/tsdb/src/tsdbRead.c:474: initTableMemIterator: Assertion `pCheckInfo->lastKey <= key' failed.

Any effects?

**Comment by hjxilinx** [comment]
how about downloading the latest version and try again?

**Comment by hjxilinx** [comment]
This issue was closed because it has been inactive for too many days.
