### ISSUE TITLE
how to create tables and write data if I have 1000 metrics

### ISSUE THREAD

**Issue by scdxin** [taosdata/TDengine#498]
应用场景一个设备有1000个测点左右，测点名称有的比较长，有点比较短，按照表每行不能超过4096字节规则，（前期分测点也不太好分，测点名长度不一，组合sql的时候不知道到那个测点就超字节了）每个表存储的测点数就可能不一样，或超字节导致sql错误建表不成功。能不能有方法固定一个表能存多少个测点呢？还有在存储一条数据的时候组合一条sql语句存储，如我存储数据是1S存储一次数据，如果表太多，组合插入的这个数据周期应该大于1S，而达不到每秒存储。这个是我这种做法问题还是说还有其它方法来实现秒级数据存储呢？谢谢

**Comment by guanshengliang** [comment]
First of all, TDengin only supports 256 columns, preferably no more than 100 columns.
Therefore, you need to abstract the data, Split data from one device into multiple tables.
For devices with different fields, you can only use it as a different type of device to build a super table.
If you want to strictly control the data frequency, you can only record the processing time every time you write, and discard this time in the next polling.

**Comment by scdxin** [comment]
单个测点名称限定了最多多少个字节吗？
