### ISSUE TITLE
TDengine Error: Out of DNodes。创建子表时报错

### ISSUE THREAD

**Issue by 307476485** [taosdata/TDengine#4983]
超级表创建成功，但是创建子表是报错。
错误日志为：
01/21 17:36:57.472885 0x7f09cb7de700 DND msg:0x7f095c0008d0, app:0x283 type:create-table is reput into mwrite queue:0x10a5e90, retry times:0
01/21 17:36:57.472933 0x7f09e42ca700 MND ERROR db:0.automation, no enough dnode to alloc 3 vnodes to vgroup, reason:Out of DNodes
配置文件该修改什么？望大神指导呀、、、

**Comment by ranningw** [comment]
> 超级表创建成功，但是创建子表是报错。
> 错误日志为：
> 01/21 17:36:57.472885 0x7f09cb7de700 DND msg:0x7f095c0008d0, app:0x283 type:create-table is reput into mwrite queue:0x10a5e90, retry times:0
> 01/21 17:36:57.472933 0x7f09e42ca700 MND ERROR db:0.automation, no enough dnode to alloc 3 vnodes to vgroup, reason:Out of DNodes
> 配置文件该修改什么？望大神指导呀、、、

请教如何解决的？
