### ISSUE TITLE
DBeaver Enterprise 7.1.0驱动TDengine失败！

### ISSUE THREAD

**Issue by steptt** [taosdata/TDengine#4998]
添加驱动，添加工件中，再group id中添加“com.taosdata.jdbc”,artifact Id中添加“taos-jdbcdriver”,添加后，下去驱动也成功，但最终测试时提示“No suitable driver found for jdbc:taos://***:6030/test”

**Comment by zyyang-taosdata** [comment]
这个应该是你环境的问题，No suitable driver found意味着使用DriverManager没有查找到可以匹配jdbc driver。
另外，url的开头为：jdbc:TAOS://
