### ISSUE TITLE
docker instance with 6.6B records restart, cannont provide service

### ISSUE THREAD

**Issue by flykarry** [taosdata/TDengine#5000]
**Bug Description**
之前测试的66亿数据插入完毕，单模方式，660000万张子表，删除超级表后，重启docker,无法建立连接，CPU占满
如果在处理其他事项，也应该能提供服务才好

**Screenshots**
![image](https://user-images.githubusercontent.com/14309127/105450794-33ee7180-5cb6-11eb-9cf1-82059c3d046e.png)

![image](https://user-images.githubusercontent.com/14309127/105450619-d0644400-5cb5-11eb-9282-4d19deb1f367.png)

![image](https://user-images.githubusercontent.com/14309127/105450507-8e3b0280-5cb5-11eb-808d-27340dd7a652.png)

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by sangshuduo** [comment]
taosd 应该在处理 WAL 回放，数据量大回放时间长，直到回放完才能提供服务

**Comment by sangshuduo** [comment]
taosd 应该在处理 WAL 回放，数据量大回放时间长，直到回放完才能提供服务

**Comment by flykarry** [comment]
> taosd 应该在处理 WAL 回放，数据量大回放时间长，直到回放完才能提供服务

要是有这种情况，那岂不是等待回放期间的数据都会丢失？

**Comment by sangshuduo** [comment]
你说的是回放期间新插入的数据吗？集群可以解决啊。
