### ISSUE TITLE
What if the database can't put data with the same timestamp

### ISSUE THREAD

**Issue by whljava** [taosdata/TDengine#501]
数据批量写入时  有主键时间戳重复的会被自动冲掉怎么办？

**Comment by fangpanpan** [comment]
时间戳相同的记录写入不同的表是可以了。因为我们一般一个设备建一张表，然后一个设备一般一个时间戳只会发送一条记录。

**Comment by whljava** [comment]
> 时间戳相同的记录写入不同的表是可以了。因为我们一般一个设备建一张表，然后一个设备一般一个时间戳只会发送一条记录。
嗯嗯  了解了解  但是要是想迁移以前的数据的时候怎么办   我直接从我们数据库读出来再进行存储就会出现数据丢失的问题

**Comment by whljava** [comment]
> 时间戳相同的记录写入不同的表是可以了。因为我们一般一个设备建一张表，然后一个设备一般一个时间戳只会发送一条记录。

嗯嗯 了解了解 但是要是想迁移以前的数据的时候怎么办 我直接从我们数据库读出来再进行存储就会出现数据丢失的问题

**Comment by guanshengliang** [comment]
The data model of the two databases is different, so you need to process  the timestamp problem y when exporting data.
For example, when a duplicate timestamp occurs, the duplicate data can be increased by 1 millisecond.

**Comment by whljava** [comment]
正常的进行循环集合往数据库插入  插入tdengine的主键给的默认0，怎么可以做到知道哪条数据是重复时间戳数据然后让这条数据的主键+1a？？

**Comment by whljava** [comment]
> The data model of the two databases is different, so you need to process the timestamp problem y when exporting data.
> For example, when a duplicate timestamp occurs, the duplicate data can be increased by 1 millisecond.

正常的进行循环集合往数据库插入 插入tdengine的主键给的默认0，怎么可以做到知道哪条数据是重复时间戳数据然后让这条数据的主键+1a？？

**Comment by guanshengliang** [comment]
We do not recommend writing with 0
If it is historical data, the record have a timestamp
If it is real-time data, there must be data generation time.
If there is no data generation time, it means that it is not time series data.

**Comment by guanshengliang** [comment]
sorry, I pressed the wrong button
