### ISSUE TITLE
taos-jdbcdriver-2.0.17 不支持占位符

### ISSUE THREAD

**Issue by sz-justinwang** [taosdata/TDengine#5030]
TdEngine的jdbc是否对SQL占位符不支持？

运行环境：

taos-jdbcdriver-2.0.17
Logstash 6.8.6 + logstash-output-jdbc-5.4.0
 
![image](https://user-images.githubusercontent.com/72057154/105792240-2f7dcd80-5fc2-11eb-8fe8-7975aabb4dc5.png)

错误信息：
[logstash.outputs.jdbc    ] JDBC - Exception. Not retrying {:exception=>java.sql.SQLFeatureNotSupportedException: this operation is NOT supported currently!, :statement=>"INSERT INTO [__tableName] USING supper_gateway tags(?,?,?,?,?) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",

**Comment by zyyang-taosdata** [comment]
如果使用JDBC-RESTful方式的话，至少使用taos-jdbcdriver-2.0.18版本。
另外，目前，JDBC-RESTful还没有实现PreparedStatment接口，这个会在将来提供支持。

**Comment by cmdares** [comment]
一则防止注入，二则能否提大批量并发高写入速度。希望能够加快实现该功能。
谢谢。

**Comment by sz-justinwang** [comment]
非常感谢，目前我们用jdbc-restful实现了，不过从产品本身来说还是希望提供此功能
