### ISSUE TITLE
continuous call add tag command of restful api trigger "Syntax error in SQL"

### ISSUE THREAD

**Issue by machine-w** [taosdata/TDengine#5045]
run:
for i in {1..6}; do curl -u root:taosdata -d 'alter table "testdatabase.testtable" add tag "test'$i'" INT' localhost:6041/rest/sql; done

results:
{"status":"error","code":534,"desc":"Syntax error in SQL"}{"status":"succ","head":["ttest2"],"data":[[0]],"rows":0}{"status":"error","code":534,"desc":"Syntax error in SQL"}{"status":"succ","head":["ttest4"],"data":[[0]],"rows":0}{"status":"error","code":534,"desc":"Syntax error in SQL"}{"status":"succ","head":["ttest6"],"data":[[0]],"rows":0}

server version: 2.0.14.0

**Comment by stephenkgu** [comment]
try this line:
for i in {1..6}; do curl -u root:taosdata -d "alter table testdatabase.testtable add tag testc$i INT" localhost:6041/rest/sql; done

It's an issue with the quotes surrounding the table name: *testdatabase.testtable*.

**Comment by machine-w** [comment]
I got it. I suggest that next version  of restful api can preferable support the quotes surrounding the table name or field name. in order to reduce polysemy

**Comment by stephenkgu** [comment]
We have tracked this issue, maybe support quotes in the near future, thanks for the suggestion.
