### ISSUE TITLE
question about upper case and lower case table name 

### ISSUE THREAD

**Issue by Skyofmine** [taosdata/TDengine#5078]
**Bug Description**
执行的sql语句和实际的大小写不符合

**To Reproduce**
1. create 超级表，表名为大写
2. 实际创建的表名却是小写

**Expected Behavior**
执行的对象名称应和sql语句中的大小写匹配

**Screenshots**
![image](https://user-images.githubusercontent.com/12237997/106224913-1756ba00-621f-11eb-845a-d195bad5cdbe.png)

**Environment (please complete the following information):**
 - OS: windows
 - TDengine Version  2.0.14

**Additional Context**
默认所有表名小写可以解决

**Comment by xiataya** [comment]
<img width="1095" alt="WX20210130-171104@2x" src="https://user-images.githubusercontent.com/24431754/106352456-3d16b880-631e-11eb-9833-5d3d8a3178fb.png">

**Comment by sangshuduo** [comment]
“TDengine对SQL语句中的英文字符不区分大小写，自动转化为小写执行。因此用户大小写敏感的字符串及密码，需要使用单引号将字符串引起来。”

https://www.taosdata.com/cn/documentation/taos-sql/
