### ISSUE TITLE
Error in queryOnMultiDataFiles when "select count(*)" from large amount of data

### ISSUE THREAD

**Issue by sagewjq** [taosdata/TDengine#508]
导入4.8亿条数据，到4亿时还能查询出来，再多select count(*)全部数据时就报以下错误，taosd服务终止；一个stable下有69万个table,数据目录有93G，约4.8亿条数据
taosd: /home/soft/TDengine-master/src/system/src/vnodeQueryProcess.c:354: queryOnMultiDataFiles: Assertion `(pBlock->keyFirst >= pQuery->lastKey && pBlock->keyLast <= pQuery->ekey && (((((pQuery)->order.order) == 1) ? 1 : -1) == 1)) || (pBlock->keyFirst >= pQuery->ekey && pBlock->keyLast <= pQuery->lastKey && !(((((pQuery)->order.order) == 1) ? 1 : -1) == 1))' failed.
已放弃(吐核)

**Comment by hjxilinx** [comment]
您好，触发这个判断条件的情况可能是写入后的数据文件有问题。请问使用的TD的版本号？

**Comment by sagewjq** [comment]
TD的版本1.6.1.6

**Comment by hjxilinx** [comment]
你可以尝试使用github上的最新的版本测试一下是否还有上述问题， 如果问题依旧，可以将日志发送到hjliao@taosdata.com，我们会提供日志分析协助。
