### ISSUE TITLE
restful request led taosd crash

### ISSUE THREAD

**Issue by yinfi** [taosdata/TDengine#5088]
**Bug Description**
通过restful接口查询导致内存溢出

**To Reproduce**
1. 通过grafana快速刷新dashboard
2. 刷新几次后卡住并异常中断
3. 通过show dnodes发现关联节点离线并自动重启，产生core文件
![image](https://user-images.githubusercontent.com/3062749/106276246-464a4b80-6272-11eb-9693-d1ef45809829.png)

4. 查看dmesg发现报如下错误：
kernel: taosd[19742]: segfault at ffffffffffffabf0 ip 00007f8fec271768 sp 00007f8f0dffac48 error 7 in libc-2.17.so[7f8fec128000+1b6000]

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: CentOS 7.0
 - Memory 16g, CPU 8核
 - TDengine Version 2.0.0.14

**Additional Context**

**Comment by sangshuduo** [comment]
请问数据库是几个副本？describe stb输出什么？刷新的频率是多少？

**Comment by yinfi** [comment]
三副本，配置了十个不同的stb，每个都不一样，但是总列数差不多，都是10列以内。点击grafana刷新页面，一秒2-3次的样子

**Comment by sangshuduo** [comment]
New TDengine use a stand-alone component taosAdapter to provide REST service. Please try it to see if the issue is resolved.
