### ISSUE TITLE
code:404, error:invalid url format

### ISSUE THREAD

**Issue by xiataya** [taosdata/TDengine#5090]
Environment (please complete the following information):
OS: Ubuntu 16
TDengine Version latest(docker)
emqx:4.2.3

When I use emqx and TDengine,this happens.
II refer to the tutorial [https://v.qq.com/x/page/r3139w0qcsz.html](url) [https://blog.csdn.net/klandor2008/article/details/107829431](url)
And some of these parts worked. But the import part failed.
![image](https://user-images.githubusercontent.com/24431754/106352271-9382f780-631c-11eb-8642-8bd37c81f41d.png)
  So how can I fix `01/30 08:49:23.382643 0x7f9b5bfec700 HTP ERROR context:0x7f9b6803b9f0, fd:23, code:404, error:invalid url format`.

<img width="921" alt="WX20210130-165005@2x" src="https://user-images.githubusercontent.com/24431754/106352063-3d618480-631b-11eb-907f-2772b334ebe6.png">

**Comment by xiataya** [comment]
![image](https://user-images.githubusercontent.com/24431754/106352597-65eb7d80-631f-11eb-8766-37a948af7843.png)

**Comment by sangshuduo** [comment]
please refer to the blog [https://www.taosdata.com/blog/2020/08/04/1722.html](https://www.taosdata.com/blog/2020/08/04/1722.html) and check again.

**Comment by xiataya** [comment]
> please refer to the blog https://www.taosdata.com/blog/2020/08/04/1722.html and check again.

thanks for reply.
I want to ask "01/30 08:49:23.382643 0x7f9b5bfec700 HTP ERROR context:0x7f9b6803b9f0, fd:23, code:404, error:invalid url format."
whats the reason for this?

**Comment by sangshuduo** [comment]
No enough information now. Please attach more detailed steps and screenshot.

**Comment by xiataya** [comment]
> No enough information now. Please attach more detailed steps and screenshot.

大佬，中文沟通吧。

**Comment by sangshuduo** [comment]
“响应动作” 和 “资源管理” 两个页面的截图贴一下

**Comment by xiataya** [comment]
响应动作：
![image](https://user-images.githubusercontent.com/24431754/106357884-e58b4380-6343-11eb-8b5e-02d39ab2e661.png)
资源管理：
![image](https://user-images.githubusercontent.com/24431754/106357911-0ce21080-6344-11eb-89ee-05963aa18a87.png)

**Comment by sangshuduo** [comment]
在运行 TDengine 的Linux 上执行 sudo tcpdump -s 0 -A 'tcp dst port 6041' 看抓到的数据包是什么

**Comment by xiataya** [comment]
> 在运行 TDengine 的Linux 上执行 sudo tcpdump -s 0 -A 'tcp dst port 6041' 看抓到的数据包是什么

目前是docker中运行的。
我先问下，如何更改官方docker镜像的时区，目前怀疑是这个问题

**Comment by xiataya** [comment]
![image](https://user-images.githubusercontent.com/24431754/106360942-2c823480-6356-11eb-98dc-bf5c8c7f9529.png)
这个是抓包内容

**Comment by sangshuduo** [comment]
看起来 POST /rest/sqlhttp://...:6041/restsql 这里的问题，但是为什么会拼接成这样的 url 就不太清楚了，应该不是 TDengine 的问题，你可以请 EMQ 的人看一下

**Comment by xiataya** [comment]
> 看起来 POST /rest/sqlhttp://...:6041/restsql 这里的问题，但是为什么会拼接成这样的 url 就不太清楚了，应该不是 TDengine 的问题，你可以请 EMQ 的人看一下

十分感谢，找到问题了！，响应动作中的path可以不写，会重复！
![image](https://user-images.githubusercontent.com/24431754/106361691-3312ab00-635a-11eb-8f97-d655b4e3b093.png)
