### ISSUE TITLE
.net core的驱动？

### ISSUE THREAD

**Issue by kingflyok** [taosdata/TDengine#51]
1、是否可以提供一下.net core的数据库驱动
2、是否有集群版本

**Comment by hjxilinx** [comment]
c#的API 开发包我们会在最近一两周发布。集群的版本暂时还不提供。

**Comment by melone18** [comment]
@ 请问下C#的api是封装C++的还是基于原生开发的？

**Comment by hjxilinx** [comment]
使用C#直接调用taos.dll中的c api提供服务。暂没有原生的开发包。

**Comment by zuozhiwen** [comment]
如果对linux和windows打对应编译的nuget包，应该是可以的。我觉得用C实现，使用C#导入的形式效率是更高的，毕竟C#底层也是用相同的方式调用CLR的。

**Comment by maikebing** [comment]
@kingflyok 
https://github.com/maikebing/Maikebing.EntityFrameworkCore.Taos

**Comment by guanshengliang** [comment]
我们会在7月27号递交windows客户端，但封装成nuget包还需要再等等

**Comment by kingflyok** [comment]
谢谢非常感谢 我想咨询一下 企业版如何购买 费用是多少

**Comment by hzcheng** [comment]
@kingflyok 您可以联系business@taosdata.com

**Comment by guanshengliang** [comment]
关于C#的问题，请在 #51 继续提问

**Comment by guanshengliang** [comment]
TDengine团队将在研发计划中增加dapper框架的支持

**Comment by ArgoZhang** [comment]
> TDengine团队将在研发计划中增加dapper框架的支持

个人觉得 dapper 仅仅是一个orm框架而已，应该先支持 .net/.netcore 然后各种orm相对应的我觉得网友自己都会做的

**Comment by ttgzs** [comment]
> TDengine团队将在研发计划中增加dapper框架的支持

C# 的client在哪里可以看到？

**Comment by guanshengliang** [comment]
TDengine在windows下对JAVA/Python的支持，是通过调用windows下的taos.dll来实现的，taos.dll通过UDP/TCP与服务端通信。如果想用使用C#访问数据库，有两种方法
1.调用此动态链接库（taos.dll)，通过UDP/TCP与服务端通信，此方法可以在examples文件夹中看到
2.通过Restful接口与服务端通信，可以参考
`https://github.com/maikebing/Maikebing.EntityFrameworkCore.Taos`
官方的C#的ORM框架还没有开发，即便安排到开发计划，也是基于windows下的taos.dll进行，即将C语言函数通过C#语言进行封装。
如果所说的.net/.netcore是指用.net framework重新包装一下通信协议，那么官方没有这个开发计划。

**Comment by thicktao** [comment]
dapper框架的支持在哪里可以看到呢？

**Comment by staneee** [comment]
是否应该先通过包装c sdk支持ADO.NET标准，其余上层orm适配可以社区实现。

**Comment by maikebing** [comment]
@staneee  https://github.com/maikebing/Maikebing.EntityFrameworkCore.Taos

**Comment by vagile-cn** [comment]
> TDengine在windows下对JAVA/Python的支持，是通过调用windows下的taos.dll来实现的，taos.dll通过UDP/TCP与服务端通信。如果想用使用C#访问数据库，有两种方法
> 1.调用此动态链接库（taos.dll)，通过UDP/TCP与服务端通信，此方法可以在examples文件夹中看到
> 2.通过Restful接口与服务端通信，可以参考
> `https://github.com/maikebing/Maikebing.EntityFrameworkCore.Taos`
> 官方的C#的ORM框架还没有开发，即便安排到开发计划，也是基于windows下的taos.dll进行，即将C语言函数通过C#语言进行封装。
> 如果所说的.net/.netcore是指用.net framework重新包装一下通信协议，那么官方没有这个开发计划。

那么 linux下是如何实现的呢？我司.net 已经不存在windowns服务器了= =

**Comment by maikebing** [comment]
linux 下   .net core的驱动Maikebing.EntityFrameworkCore.Taos  调用的 是 libtaos.so

**Comment by maikebing** [comment]
TDengine 2.0 最新适配版本 已经发布。 兼容Windows 64位， Linux 64  位 系统

https://github.com/maikebing/Maikebing.EntityFrameworkCore.Taos/releases/tag/v2.0.123

**Comment by vagile-cn** [comment]
> linux 下 .net core的驱动Maikebing.EntityFrameworkCore.Taos 调用的 是 libtaos.so

这样的话 是需要自己编译嘛？

**Comment by maikebing** [comment]
@vagile-cn  不需要， nuget 里面引用就行了
