### ISSUE TITLE
how to use tags to get one table data when execute query sql

### ISSUE THREAD

**Issue by cjjcode** [taosdata/TDengine#510]
1.create table if not exists **futures**(updatetime timestamp,sid binary(4),...) tags (market binary(20),symbol binary(20) );
建表成功
2. insert into SR001 **using** **futures** **tags**(czce,sr001) values('',''....)
自动建子表SR001 成功，数据插入成功
当使用tags来查询select * from futures where  market =czce and symbol =sr001;
结果为0；
当用表字段来过滤 select * from futures where sid =''  是能查到数据的。
所以问题是：怎样使用tag查询一张子表的数据，而不是表字段来过滤。

还有一个问题:
当字段过多时，客户端通过JDBC执行sql语句会失败，SQLException:failed  to connect to server，当我减少一些字段时是成功的 ，同样的sql在服务端执行是成功的。所以限制是什么呢？

**Comment by fangpanpan** [comment]
请问您用的是最新版的tdengine吗？以及您插入的字段值都是字符串，那么您在插入和查询时输入的值都没有加上引号（“”）吗？

**Comment by cjjcode** [comment]
> 请问您用的是最新版的tdengine吗？以及您插入的字段值都是字符串，那么您在插入和查询时输入的值都没有加上引号（“”）吗？

感谢您的帮助，版本1.6.1.7。关于使用tags过滤的问题找到原因了，插入数据tag是大写，自动转成了小写，请问这个是有配置项吗？另外，客户端执行sql有长度或大小限制吗？debug日志开启，没有报错，但是客户端依然是failed to connect to server.该sql在服务端可成功执行。

**Comment by fangpanpan** [comment]
在插入字符串的时候，如果您没有加引号的话，我们会自动转成小写。如果您希望保留大写，加上引号就可以了。这个没有配置项。sql有长度限制，不能超过64k。
