### ISSUE TITLE
TDengine error:database memory is full for commit failed

### ISSUE THREAD

**Issue by moziie** [taosdata/TDengine#5108]
测试demo跑数据插入的时候，提示TDengine error:database memory is full for commit failed（数据库内存已满无法提交），请问应该如何解决。
当前是在8核16G三台linux系统机器上搭建的集群，12张超级表，10万子表，70亿数据量。

**Comment by dapan1121** [comment]
Usually it's caused by fully tmp directory, please check if the tmp directory is full.

**Comment by moziie** [comment]
> Usually it's caused by fully tmp directory, please check if the tmp directory is full.

ok，检查了一遍发现问题了，谢谢

**Comment by cheny5100** [comment]
@moziie 你好 我也遇到该问题了，请问你是怎么解决的呢

**Comment by cheny5100** [comment]
@dapan1121 你好，我也遇到该问题了，可能是什么问题，该如何排查呢
