### ISSUE TITLE
debug go by dlv on windows led exception

### ISSUE THREAD

**Issue by pkf** [taosdata/TDengine#5110]
**Bug Description**
下面的代码，在win10下直接编译可正常运行，检查数据库发现数据库和表正确建立。
但是 如果使用调试模式就会报错。

> PS D:\goworks\hello> go run .\main.go
> 开始连接TDengine......
> 已连接TDengine
> 11
> 22
> 33
> PS D:\goworks\hello> dlv debug .\main.go
> Type 'help' for list of commands.
> (dlv) c
> 开始连接TDengine......
> 已连接TDengine
> Exception 0xc0000005 0x1 0x0 0x7ffe8c059513
> PC=0x7ffe8c059513
> 
> runtime: unknown pc 0x7ffe8c059513
> stack: frame={sp:0xf7ddfff470, fp:0x0} stack=[0x0,0xf7ddfffd00)
> 000000f7ddfff370:  cccccccccccccccc  00007ffed881a9f0
> 000000f7ddfff380:  0000026037122c38  00007ffed8804149
> 000000f7ddfff390:  000000f7ddfff438  00007ffed8830200
> 000000f7ddfff3a0:  0000000000000003  0000000000000000
> 000000f7ddfff3b0:  0000000000000000  0000000002030000

```
package main

import (
	"database/sql"
	"fmt"
	"os"

	_ "github.com/taosdata/driver-go/taosSql"
)

func main() {

	fmt.Println("开始连接TDengine......")
	db, err := sql.Open("taosSql", "root:taosdata@/tcp(wsl2:6030)/")
	if err != nil {
		fmt.Printf("Open database error: %s\n", err)
		os.Exit(1)
	}

	fmt.Println("已连接TDengine")

	sqlStr := "drop database if exists godb"
	_, err = db.Exec(sqlStr)
	if err != nil {
		fmt.Printf("删除数据库失败: %s\n", err)
		return
	}
	fmt.Println("11")

	// create database
	sqlStr = "create database godb keep 3650 days 30"
	_, err = db.Exec(sqlStr)
	if err != nil {
		fmt.Printf("创建数据库失败: %s\n", err)
		return
	}
	fmt.Println("22")

	sqlStr = "create table if not exists godb.gotable (ts timestamp, current float, voltage int, phase float) tags(location binary(64), groupId int);"
	_, err = db.Exec(sqlStr)
	if err != nil {
		fmt.Printf("创建表失败: %s\n", err)
		return
	}
	fmt.Println("33")
	err = db.Close()
	if err != nil {
		fmt.Printf("关闭数据库失败: %s\n", err)
		return
	}
}
```

网上查了很多资料，但自己不能解决。
参考 https://www.coder.work/article/209537

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. WIN10 20H2]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 2.0.15.0]

**Additional Context**

**Comment by pkf** [comment]
在linux下用同样代码和方法测试，没有问题

**Comment by huskar-t** [comment]
@pkf I try to reproduce。
env: 
go1.16.5
windows 10 20H2
dlv 1.7.1
go-driver v0.0.0-20210625015412-3971249c9425

output:

> PS E:\self\test2>  dlv debug .\main.go
Type 'help' for list of commands.
(dlv) c
开始连接TDengine......
已连接TDengine
11
22
33

please describe your reproduction steps in detail

**Comment by sangshuduo** [comment]
close as no response for a long time. please reopen it if still need help.
