### ISSUE TITLE
taos.dll crash

### ISSUE THREAD

**Issue by OrangeEffects** [taosdata/TDengine#5123]
**Bug Description**
插入数据时taos.dll随机崩溃，Assertion failed!

**To Reproduce**
1. 连续调用 taos_query, 只有基本insert语句
2. 没有规律，可能立即crash，可能跑几个小时crash

**Expected Behavior**
无论发生任何内部错误，query返回失败就行，别crash啊，稳定和容错才是首要的
release版程序怎么还有assert? 换成条件判断不行么

**Screenshots**
![taos dll crash](https://user-images.githubusercontent.com/78457233/106689549-1e107300-660b-11eb-8d98-0c2debaa946a.png)

Microsoft Visual C++ Runtime Library 
Assertion failed!
Program:C:\Windows\SYSTEM32\taos.dll
File:D:\0-ver_release_room\TDinternal\community\s...\tarray.c
Line:95
Expression：index < pArray->size

**Environment (please complete the following information):**
 - OS: windows server 2012
 - TDengine Version 2.0.13.0 2.0.14.0 2.0.15.0

**Additional Context**
\src\util\src\tarray.c Line:95

void* taosArrayGetP(const SArray* pArray, size_t index) {
  assert(index < pArray->size);
  
  void* d = TARRAY_GET_ELEM(pArray, index);
  
  return *(void**)d;
}

**Comment by OrangeEffects** [comment]
测试场景补充：

1.SQL语句长度63k，形如“INSERT t1 USING STable ...   t2 USING STable ... ”  批量多表插入。
2.单线程，如上述crash。
3.多线程，独立连接，insert操作的table也不重叠，多个线程同时crash（Assertion failed 弹窗）。看上去和dll内部全局状态有关。

**Comment by sangshuduo** [comment]
@OrangeEffects  方便分享一下表结构和代码吗？

**Comment by sangshuduo** [comment]
@OrangeEffects  方便分享一下表结构和代码吗？

**Comment by OrangeEffects** [comment]
> @OrangeEffects  方便分享一下表结构和代码吗？

表结构:
 CREATE TABLE stable1 (ts TIMESTAMP,v1 TINYINT,v2 TINYINT,v3 SMALLINT,v4 TINYINT,v5 TINYINT,v6 SMALLINT,v7 TINYINT,v8 TINYINT,v9 TINYINT,v10 TINYINT,v11 TINYINT,v12 TINYINT )TAGS (yy BINARY(10)); 
 
数据库操作：
int pos=0;
for(...) //从队列循环取数据 pOne
{
	 if(pos==0)
	 {
		 pos=sprintf_s(m_sql_buf,DB_SQL_BUF_MAX,"INSERT INTO");
	 }
	 pos+=sprintf_s(m_sql_buf+pos,DB_SQL_BUF_MAX-pos," t_%s USING stable1 TAGS(\"aa\")(ts,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12)VALUES(%u%03d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d)"
		 ,pOne->name
		 ,pOne->time_utc_sec
		 ,pOne->time_utc_ms
		 ,pOne->v1
		 ,pOne->v2
		 ,pOne->v3
		 ,pOne->v4
		 ,pOne->v5
		 ,pOne->v6
		 ,pOne->v7
		 ,pOne->v8
		 ,pOne->v9
		 ,pOne->v10
		 ,pOne->v11
		 ,pOne->v12
		 );
 }

if(pos>0)
{
	m_td_result=taos_query(m_taos, m_sql_buf);
	taos_free_result(m_td_result);
}

**Comment by sangshuduo** [comment]
please try TDengine latest version and open it if still need help.
