### ISSUE TITLE
 ERROR 0x7f5aa000a0d0 local merge abort due to error occurs, code:success

### ISSUE THREAD

**Issue by Fmyao** [taosdata/TDengine#5124]
TD版本：2.0.14.0
问题描述：在TD服务端所在服务器上使用taos连接后，当group by查询的数据是空的就会报错ERROR 0x7f5aa000a0d0 local merge abort due to error occurs, code:success，但是在另外一台服务器（部署了同版本的客户端）使用taos命令连接后，查询不报此错误。
SQL查询语句：
select last(pv) as maxPv,min(pv) as minPv,device_id as deviceId,device_name as deviceName,point_name as pointName,ratio from service_values where device_id='xjlsb_1' and  point_name='XS99temp' and ts >= '2021-01-30 00:00:00' group by device_id,device_name,point_name,ratio
其中：
service_values为超级表，device_id等于‘xjlsb_1’以及point_name等于XS99temp的数据目前表中还没有。

**Comment by Shawshank-Smile** [comment]
本质上，都是使用的同一客户端，这种问题是不应该的。
建议检查taosd所在的服务器，是不是原有版本没有卸载干净？如果可以稳定复现，请把报错日志和报错信息传一下吧。

**Comment by Fmyao** [comment]
应该不是原来的版本没删除干净，我刚才，先执行rm -rf /var/log/taos,再执行 rm -rf /var/lib/taos、rm -rf  /etc/taos/taos.cfg、rmtaos进行了卸载，然后解压2.0.14.0安装包，重新./install.sh进行了安装。
然后重新建库建表，一开始超级表下没有子表的时候group by查询没有报错。在这个超级表下建了一个子表，然后group by 查不是这个子表中的数据（这个子表的device_id="20070158",point_name="HJXK07"），日志中报错如下：
![image](https://user-images.githubusercontent.com/50644859/106716196-18ca1d00-6639-11eb-868e-ba61b215c508.png)
![image](https://user-images.githubusercontent.com/50644859/106716217-22538500-6639-11eb-9576-558eed778be5.png)
附报错日志taoslog0.0:
[taoslog0.0.txt](https://github.com/taosdata/TDengine/files/5916931/taoslog0.0.txt)

**Comment by Shawshank-Smile** [comment]
请使用最新的版本，如果问题还能复现，请加我微信：wxid_j4cp3qymawr522，我来远程看看。

**Comment by Fmyao** [comment]
最新版本没有这个问题
