### ISSUE TITLE
taos connect failed, reason: Invalid app version.

### ISSUE THREAD

**Issue by sjmGit** [taosdata/TDengine#5135]
**Bug Description**
最新版客户端2.0..15.0连接服务端时报错：taos connect failed, reason: Invalid app version.
服务端跟客户端都是今天全新安装的。

![image](https://user-images.githubusercontent.com/50550695/106748451-352d8000-6660-11eb-94ef-1701a5fcc5ba.png)

**Comment by Shawshank-Smile** [comment]
会不会原来的没有卸载干净，请详细描述什么情况下报的错，截图或者日志完整一些。

**Comment by sjmGit** [comment]
> 会不会原来的没有卸载干净，请详细描述什么情况下报的错，截图或者日志完整一些。

都是第一次装，我是在本地虚拟机装的。以前没有残留。问题是出现在客户端连接服务器的时候报这个错，服务端我能正常使用


![1](https://user-images.githubusercontent.com/50550695/106834559-a9077100-66d0-11eb-9d5b-fdf8498767aa.png)

**Comment by Shawshank-Smile** [comment]
unable to establish connection
check the config and read FAQ on official websiteand

**Comment by azhen318** [comment]
具体是哪些config？
我也是第一次安装2.0.16；
服务端能连接，win客户端就是连接不上，端口确认是telnet没有问题

**Comment by Shawshank-Smile** [comment]
请参考一下内容：
https://www.taosdata.com/blog/2020/11/11/1941.html
taosdata.com/blog/2020/11/11/1961.html
https://www.taosdata.com/cn/documentation/cluster
https://www.taosdata.com/cn/documentation/faq

**Comment by azhen318** [comment]
![image](https://user-images.githubusercontent.com/33944883/108448723-3637f180-729d-11eb-8509-910c439771a4.png)
服务器正常；
![image](https://user-images.githubusercontent.com/33944883/108448778-4f40a280-729d-11eb-9db3-9dc1250ae5ca.png)
![image](https://user-images.githubusercontent.com/33944883/108448809-5cf62800-729d-11eb-9494-1e344d651b2c.png)
客户端配置；
6030~6042端口都打开，客户端还是连接不上

**Comment by Shawshank-Smile** [comment]
Do you have any supplementary information?
At present, this kind of configuration is not successful, it is difficult to encounter.

**Comment by azhen318** [comment]
Tks for you response。I have find the problem，because I download wrong  win-client type，and wrong  taos.dll  file。

**Comment by wenlongwljs** [comment]
我也遇到这种情况，是windows 客户端问题，Idea连接显示 [9044] JNI ERROR (2354): JNI connection is NULL.
驱动版本：
        
        <dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>2.0.33</version>
        </dependency>
数据库版本：Version:2.1.3.0

客户端连接报错：
Welcome to the TDengine shell from Linux, Client Version:2.1.3.2
Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.

taos connect failed, reason: Unable to establish connection.

windows客户端版本：TDengine-client-2.1.3.2-Windows-x64.exe

程序放到服务器上面可以正常运行，在本机windows系统上面无法连接到linux数据库。

**Comment by wenlongwljs** [comment]
@azhen318 你是下载的那个版本的客户端

**Comment by TomThread** [comment]
how to solved?
