### ISSUE TITLE
 Query data wrong result with restful connector

### ISSUE THREAD

**Issue by shamanhuang** [taosdata/TDengine#5137]
同一条查询语句，短时间内请求查询多次，返回结果和rows都错了。

正常有1181条记录，短时间连续查询两次，rows返回3029条，怎么解决多线程并发查询数据错乱问题？

**Comment by Shawshank-Smile** [comment]
Software version,？system environment,？reproduction method？

**Comment by shamanhuang** [comment]
Version:2.0.4.0,system centos7 ,/rest/sql

**Comment by Shawshank-Smile** [comment]
Please update the latest version. If you have any questions, please leave a message

**Comment by shamanhuang** [comment]
短时间内请求多次就会出现以下数据
{"status":"succ","head":["ts","diffweight"],"data":[["2021-01-06 22:22:03.000000",0.00000]],"rows":10414}

**Comment by Shawshank-Smile** [comment]
Have you update to the latest version yet?

**Comment by shamanhuang** [comment]
2.0.15.0

**Comment by Shawshank-Smile** [comment]
如果问题依然存在的话，请加我微信：13720014098，我远程看一下。

**Comment by yuhuangdada** [comment]
我也遇到这个问题了， 现在这个问题解决了吗？@shamanhuang

**Comment by shamanhuang** [comment]
> 我也遇到这个问题了， 现在这个问题解决了吗？@shamanhuang

把headers的Connection:keep-alive 取消了
