### ISSUE TITLE
feature: remove after close for tfs

### ISSUE THREAD

**Issue by freemine** [taosdata/TDengine#5142]
tfs related issue.
src/vnode/src/vnodeMain.c:
```
362   if (pVnode->wal) {
363     if (code != 0) {
364       vError("vgId:%d, failed to commit while close tsdb repo, keep wal", pVnode->vgId);
365     } else {
366       walRemoveAllOldFiles(pVnode->wal);
367     }
368     walClose(pVnode->wal);
369     pVnode->wal = NULL;
370   }
```
if pVnode->wal->tfd is still open, remove would fail on windows platform. (this is confirmed when i am porting windows taosd)

**Comment by Shawshank-Smile** [comment]
Thank you my man! 
Has been sent to the original engineer.

**Comment by guanshengliang** [comment]
I found this problem yesterday and fixed it. I'm dealing with Windows platform, but it's not very high priority.
There are still many cases that have not been passed, and it will not be officially released until they have been passed
