### ISSUE TITLE
Can you give the specific FQDN in the log?

### ISSUE THREAD

**Issue by pigwing** [taosdata/TDengine#5149]
按照教程配置了相关的host配置如下图
![1](https://user-images.githubusercontent.com/8393545/106868119-5b5b2a80-6709-11eb-9586-c0da60c42659.png)
![2](https://user-images.githubusercontent.com/8393545/106868171-6ca43700-6709-11eb-9246-c516f14f9fe5.png)
![3](https://user-images.githubusercontent.com/8393545/106868186-7037be00-6709-11eb-8a2a-5c9d45b92b60.png)
![4](https://user-images.githubusercontent.com/8393545/106868191-72018180-6709-11eb-8cd1-9fa5ffc23bfe.png)
![5](https://user-images.githubusercontent.com/8393545/106868196-7463db80-6709-11eb-8529-a2524e8be074.png)
但是windows客户端只要发出查询指令就会报FQDN异常,但是log也没详细说明具体是哪里匹配不上.

**Comment by Shawshank-Smile** [comment]
请问端口都开了吗？TCP/UDP 6030-6042供26个。

**Comment by pigwing** [comment]
@Shawshank-Smile 已经解决了.是客户端的访客策略问题,需要所有节点都配置FQDN,客户端会到所有节点抓取对应目标数据,并不是汇总到first节点一并返回,我一开始以为是所有节点数据都回回到first节点返回的,所以没有配置额外节点的FQDN信息.

**Comment by Shawshank-Smile** [comment]
Nice, see you.
