### ISSUE TITLE
a few records is missing after multiple-data insert query

### ISSUE THREAD

**Issue by Janus-Xu** [taosdata/TDengine#515]
**Bug Description**
更改table-schema后，新建stable，tables导入数据，
再次执行插入多条记录query，对比之前数据发现数据存在丢失。对比如下：
![image](https://user-images.githubusercontent.com/6883877/65009223-8ab79e80-d93e-11e9-8b6f-8f0a7dc211a4.png)
检查16点数据，发现少了16:03:28的数据
![image](https://user-images.githubusercontent.com/6883877/65009302-bcc90080-d93e-11e9-9f5b-7dc4f62f1474.png)
query确认语句中包含数据
![image](https://user-images.githubusercontent.com/6883877/65009335-d66a4800-d93e-11e9-8c07-367607956a12.png)
在console手工补数据成功。
![image](https://user-images.githubusercontent.com/6883877/65009367-f7cb3400-d93e-11e9-8a43-7ea9cba6babf.png)
尝试query改为import，没有任何变化，只能是如上方式一个个找出来补进去。

请问这个情况产生的原因是什么？batch 的方式是否存在丢包的可能性？和数据量有关么，目前控制是1250条记录插入，小于64k

**Environment 
 - OS: Ubuntu 16.04.1
 - TDengine Version [1.6.1.7]

**Comment by plum-lihui** [comment]
客户端启动了多少个线程进行insert 呢？ 有采用多线程吗？以及有没有多个线程insert 同一张表的情况？

**Comment by Janus-Xu** [comment]
> 客户端启动了多少个线程进行insert 呢？ 有采用多线程吗？以及有没有多个线程insert 同一张表的情况？

用python的接口起了一个客户端循环insert数据，没用多线程

**Comment by fangpanpan** [comment]
可以将您的python code发给我们吗？我们看能不能复现这个问题。

**Comment by rainmaple** [comment]
我们的项目也遇上这个问题，多线程在对表进行插入时候，确实会出现表记录缺失的问题，这是我的项目源欢迎对场景进行复现https://github.com/rainmaple/tsbm
