### ISSUE TITLE
The data returned by querying through the Resetful API is out of order in time

### ISSUE THREAD

**Issue by yuhuangdada** [taosdata/TDengine#5150]
**Bug Description**

- version：2.0.15.0

- description：通过resetful api查询返回的数据有时间乱序的问题，

如果调用过于频繁的话，有一定几率出现顺序错乱的现象，能不能帮忙看看是啥原因呢？这是我截的一部分api返回值，
![WechatIMG1821](https://user-images.githubusercontent.com/19163166/106879631-5badf280-6716-11eb-9a4b-71bad930f64d.png)

- sql 语句：

SELECT SUM(tx) AS tx,SUM(rx) AS rx FROM datausage_hourly.datausage WHERE deviceId = '6011134faafdc3092fa7ab78' AND ts > 1611643541814 AND ts <= 1612248341814 AND  (type = 'sim1' or type = 'sim2') interval(5m) fill(null) GROUP BY type；

- 数据包：
[data.csv.zip](https://github.com/taosdata/TDengine/files/5924957/data.csv.zip)

**Comment by Shawshank-Smile** [comment]
what's the exact mean of "顺序错乱"?

**Comment by yuhuangdada** [comment]
查询出来的数据，ts时间有乱序的情况。比如 正常情况应该是[2021-01-26 16：15：00.000，2021-01-26 16：20：00.000，2021-01-26 16：25：00.000]， 实际情况是这样的[2021-01-26 16：15：00.000  ，2021-01-26 17：45：00.000，2021-01-26 16：25：00.000]，其中第二数据是不对的

**Comment by zyyang-taosdata** [comment]
1. 如果是使用JDBC-RESTful的话，taos-jdbcdriver的版本需要在2.0.18以上。
2. 我查看了您的data.csv文件，这个应该是您的数据，我会使用这些数据尝试复现这个问题。
感谢你的问题～

**Comment by zyyang-taosdata** [comment]
在最新版本里已经修复了这个问题，请更新tdengine和taos-jdbcdriver的版本
