### ISSUE TITLE
Field value is missing

### ISSUE THREAD

**Issue by MelodyI** [taosdata/TDengine#5153]
taos> select sum(qa) from stable1 where ts >= '2021-01-30 00:00:00.000' and ts <= '2021-02-05 23:59:59.999' interval(1d) group by tbname, tag1, tag2 order by tbname;
|ts|sum(qa)|tbname|tag1|tag2|
|---|---|---|---|---|
|2021-01-30 00:00:00.000 |0.000000000 | tb1| A|**_missing_**|
|2021-01-31 00:00:00.000 |1.000000000 | tb1| A|4#|
|2021-02-01 00:00:00.000 |0.000000000 | tb1| A|4#|
|2021-02-02 00:00:00.000 |0.000000000 | tb1| A|4#|
|2021-02-03 00:00:00.000 |0.000000000 | tb1| A|4#|
|2021-02-04 00:00:00.000 |0.000000000 | tb1| A|4#|
|2021-02-05 00:00:00.000 |0.000000000 | tb1| A|4#|
|2021-01-30 00:00:00.000 |0.000000000 | tb2| A|**_missing_**|
|2021-01-31 00:00:00.000 |0.000000000 | tb2 | A|4#|
|2021-02-01 00:00:00.000 |0.000000000 | tb2 | A|4#|
|2021-02-02 00:00:00.000 |0.000000000 | tb2 | A|4#|
|2021-02-03 00:00:00.000 |0.000000000 | tb2 | A|4#|
|2021-02-04 00:00:00.000 |0.000000000 | tb2 | A|4#|
|2021-02-05 00:00:00.000 |0.000000000 | tb2 | A|4#|

版本:2.0.14.0

**Comment by Shawshank-Smile** [comment]
can you share me the software version number, and table schema?

**Comment by MelodyI** [comment]
# taos -u root -p

Welcome to the TDengine shell from Linux, Client Version:2.0.14.0
Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.


taos> describe stable1;
|Field |Type|Length |Note|
---|---|---|---|
|ts| TIMESTAMP|  8 | |
|qa| DOUBLE  |  8 | |
|alarm| SMALLINT|  2 | |
|factory  | NCHAR| 10 | TAG|
|tag1 | NCHAR| 10 | TAG|
|tag2 | NCHAR| 10 | TAG|
Query OK, 6 row(s) in set (0.000928s)

**Comment by MelodyI** [comment]
Is the problem being solved？

**Comment by hjxilinx** [comment]
This problem has been sovled in the new released version of TDengine. Close this issue.
