### ISSUE TITLE
Batch insert data prompt: invalid result set pointer

### ISSUE THREAD

**Issue by moziie** [taosdata/TDengine#5174]
批量数据插入时候，程序报错提示Invalid result set pointer，过一会儿提示TDengine Error: Unable to establish connection，此时再去使用systemctl status taosd查看taosd服务，发现服务不可用
程序部署linux：centos7,8核16G三台三节点集群，版本2.0.14
测试demo:
测试期望是每分钟插入50万个电表数据，定时执行

public class DemoTD {

    private final static String prefixDb ="000000";
    private ThreadPoolExecutor threadPoolExecutor;

    @Scheduled(cron = "0 0/1 * * * ?")
    public void createTable(){

        Connection connection =null;
        threadPoolExecutor = new ThreadPoolExecutor(128,512,10, TimeUnit.SECONDS,
                new LinkedBlockingQueue<>(200000),new ThreadPoolExecutor.CallerRunsPolicy());
        try {
            HikariConfig config = new HikariConfig();
            config.setJdbcUrl("jdbc:TAOS://127.0.0.1:6030/fanwu");
            config.setDriverClassName("com.taosdata.jdbc.TSDBDriver");
            config.setUsername("root");
            config.setPassword("taosdata");
            config.setMinimumIdle(5);           //minimum number of idle connection
            config.setMaximumPoolSize(20);      //maximum number of connection in the pool
            config.setConnectionTimeout(10000); //maximum wait milliseconds for get connection from pool
            config.setIdleTimeout(60000);       // max idle time for recycle idle connection
            config.setValidationTimeout(3000);
            HikariDataSource ds = new HikariDataSource(config); //create datasource
            connection = ds.getConnection(); // get connection
            Statement ss = connection.createStatement();
            Integer total = 500000;
            int count = 2000;
            for (int i = 0; i < total/count; i++) {
                int ii = i;
                threadPoolExecutor.execute(() ->{
                    for (int j = ii*count+1; j <= (ii+1)*count; j++) {
                        String electricMeterid = j < 10 ? prefixDb+"00000"+j:prefixDb+"0000"+j;
                        if (j > 99 && j< 1000){
                            electricMeterid = prefixDb+"000"+j;
                        }
                        if (j > 999 && j<10000) {
                            electricMeterid = prefixDb+"00"+j;
                        }
                        if (j>9999 && j<100000){
                            electricMeterid = prefixDb+"0"+j;
                        }
                        if (j>100000){
                            electricMeterid = prefixDb+""+j;
                        }
                        StringBuffer sql = new StringBuffer("insert into ");
                        String myRawvalue = "{\n" +
                                "\t\"ts\": \""+formatTimeStamp(new Date())+"\",\n" +
                                "\t\"positiveEnergy\": \""+1000000+"\",\n" +
                                "\t\"activeEnergy\": \""+1000000+"\",\n" +
                                "\t\"activePower\": \""+getMyRandom(5000,6000)+"\",\n" +
                                "\t\"activePowerA\": \""+getMyRandom(1600,2000)+"\",\n" +
                                "\t\"activePowerB\": \""+getMyRandom(1600,2000)+"\",\n" +
                                "\t\"activePowerC\": \""+getMyRandom(1600,2000)+"\",\n" +
                                "\t\"positivePower\": \""+getMyRandom(600,700)+"\",\n" +
                                "\t\"positivePowerA\": \""+getMyRandom(200,230)+"\",\n" +
                                "\t\"positivePowerB\": \""+getMyRandom(200,230)+"\",\n" +
                                "\t\"positivePowerC\": \""+getMyRandom(200,230)+"\",\n" +
                                "\t\"powerFactor\": \""+getMyRandom(480,510)+"\",\n" +
                                "\t\"powerFactorA\": \""+getMyRandom(480,510)+"\",\n" +
                                "\t\"powerFactorB\": \""+getMyRandom(480,510)+"\",\n" +
                                "\t\"powerFactorC\": \""+getMyRandom(480,510)+"\",\n" +
                                "\t\"voltageA\": \""+getMyRandom(2180,2210)+"\",\n" +
                                "\t\"voltageB\": \""+getMyRandom(2190,2220)+"\",\n" +
                                "\t\"voltageC\": \""+getMyRandom(2180,2220)+"\",\n" +
                                "\t\"currentA\": \""+getMyRandom(2100,3100)+"\",\n" +
                                "\t\"currentB\": \""+getMyRandom(1900,2900)+"\",\n" +
                                "\t\"currentC\": \""+getMyRandom(2100,2900)+"\",\n" +
                                "\t\"hCurrentA\": \""+getMyRandom(1000,1600)+"\",\n" +
                                "\t\"hCurrentB\": \""+getMyRandom(1000,1600)+"\",\n" +
                                "\t\"hCurrentC\": \""+getMyRandom(1000,1600)+"\",\n" +
                                "\t\"hVoltageA\": \""+getMyRandom(150,300)+"\",\n" +
                                "\t\"hVoltageB\": \""+getMyRandom(150,300)+"\",\n" +
                                "\t\"hVoltageC\": \""+getMyRandom(150,300)+"\",\n" +
                                "\t\"hPositivePower\": \""+getMyRandom(180,360)+"\",\n" +
                                "\t\"hPositivePowerA\": \""+getMyRandom(60,120)+"\",\n" +
                                "\t\"hPositivePowerB\": \""+getMyRandom(60,120)+"\",\n" +
                                "\t\"hPositivePowerC\": \""+getMyRandom(60,120)+"\",\n" +
                                "\t\"hActivePower\": \""+getMyRandom(235,613)+"\",\n" +
                                "\t\"hActivePowerB\": \""+getMyRandom(100,200)+"\",\n" +
                                "\t\"hActivePowerA\": \""+getMyRandom(100,210)+"\",\n" +
                                "\t\"hActivePowerC\": \""+getMyRandom(100,210)+"\",\n" +
                                "\t\"angleAtoB\": \""+getMyRandom(1195,1213)+"\",\n" +
                                "\t\"angleAtoC\": \""+getMyRandom(2386,2414)+"\",\n" +
                                "\t\"angleBtoC\": \""+getMyRandom(1195,1213)+"\"\n" +
                                "}";

                        EngineData engineData=JSON.parseObject(org.apache.commons.lang3.StringEscapeUtils.unescapeJava(myRawvalue), EngineData.class);
                        sql.append("ae").append(electricMeterid).append(" values ").append("('")
                                .append(engineData.getTs()).append("'").append(",")
                                .append(engineData.getActiveEnergy()).append(") ")
                                .append("pe").append(electricMeterid).append(" values ").append("('")
                                .append(engineData.getTs()).append("'").append(",")
                                .append(engineData.getPositiveEnergy()).append(") ")
                                .append("ac").append(electricMeterid).append(" values ").append("('")
                                .append(engineData.getTs()).append("'").append(",")
                                .append(engineData.getActivePower()).append(",")
                                .append(engineData.getActivePowerA()).append(",")
                                .append(engineData.getActivePowerB()).append(",")
                                .append(engineData.getActivePowerC()).append(") ")
                                .append("po").append(electricMeterid).append(" values ").append("('")
                                .append(engineData.getTs()).append("'").append(",")
                                .append(engineData.getPositivePower()).append(",")
                                .append(engineData.getPositivePowerA()).append(",")
                                .append(engineData.getPositivePowerB()).append(",")
                                .append(engineData.getPositivePowerC()).append(") ")
                                .append("cu").append(electricMeterid).append(" values ").append("('")
                                .append(engineData.getTs()).append("'").append(",")
                                .append(engineData.getCurrentA()).append(",")
                                .append(engineData.getCurrentB()).append(",")
                                .append(engineData.getCurrentC()).append(") ")
                                .append("vo").append(electricMeterid).append(" values ").append("('")
                                .append(engineData.getTs()).append("'").append(",")
                                .append(engineData.getVoltageA()).append(",")
                                .append(engineData.getVoltageB()).append(",").append(engineData.getVoltageC())
                                .append(") ")
                                .append("pf").append(electricMeterid).append(" values ").append("('")
                                .append(engineData.getTs()).append("'").append(",")
                                .append(engineData.getPowerFactor()).append(",")
                                .append(engineData.getPowerFactorA()).append(",")
                                .append(engineData.getPowerFactorB()).append(",")
                                .append(engineData.getPowerFactorC()).append(") ")
                                .append("hc").append(electricMeterid).append(" values ").append("('")
                                .append(engineData.getTs()).append("'").append(",")
                                .append(engineData.getHCurrentA()).append(",")
                                .append(engineData.getHCurrentB()).append(",")
                                .append(engineData.getHCurrentC()).append(") ")
                                .append("hv").append(electricMeterid).append(" values ").append("('")
                                .append(engineData.getTs()).append("'").append(",")
                                .append(engineData.getHVoltageA()).append(",")
                                .append(engineData.getHVoltageB()).append(",").append(engineData.getHVoltageC())
                                .append(") ")
                                .append("ha").append(electricMeterid).append(" values ").append("('")
                                .append(engineData.getTs()).append("'").append(",")
                                .append(engineData.getHActivePower()).append(",")
                                .append(engineData.getHActivePowerA()).append(",")
                                .append(engineData.getHActivePowerB()).append(",")
                                .append(engineData.getHActivePowerC()).append(") ")
                                .append("hp").append(electricMeterid).append(" values ").append("('")
                                .append(engineData.getTs()).append("'").append(",")
                                .append(engineData.getHPositivePower()).append(",")
                                .append(engineData.getHPositivePowerA()).append(",")
                                .append(engineData.getHPositivePowerB()).append(",")
                                .append(engineData.getHPositivePowerC()).append(") ")
                                .append("an").append(electricMeterid).append(" values ").append("('")
                                .append(engineData.getTs()).append("'").append(",")
                                .append(engineData.getAngleAtoB()).append(",")
                                .append(engineData.getAngleBtoC()).append(",")
                                .append(engineData.getAngleAtoC()).append(")");
                        try {
                            ss.execute(sql.toString());
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }
                });
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }
    public Float getMyRandom(Integer n,Integer m){
        double big = Math.random() * (m - n) + n;
        BigDecimal bd = new BigDecimal(big);
        return bd.setScale(3, BigDecimal.ROUND_HALF_UP).floatValue();
    }
    public static String formatTimeStamp(Date date) {
        return new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS").format(date);
    }
}

@Data
public class EngineData implements Serializable {

    private static final long serialVersionUID = 1L;

    private String ts;
    private Float activeEnergy;
    private Float positiveEnergy;
    private Float activePower; 
    private Float activePowerA; 
    private Float activePowerB; 
    private Float activePowerC; 
    private Float positivePower;
    private Float positivePowerA;
    private Float positivePowerB;
    private Float positivePowerC;
    private Float powerFactor;
    private Float powerFactorA;
    private Float powerFactorB;
    private Float powerFactorC;
    private Float voltageA;
    private Float voltageB;
    private Float voltageC;
    private Float currentA;
    private Float currentB;
    private Float currentC;
    private Float hVoltageA;
    private Float hVoltageB;
    private Float hVoltageC;
    private Float hCurrentA;
    private Float hCurrentB;
    private Float hCurrentC;
    private Float hActivePower;
    private Float hActivePowerA;
    private Float hActivePowerB;
    private Float hActivePowerC;
    private Float hPositivePower;
    private Float hPositivePowerA;
    private Float hPositivePowerB;
    private Float hPositivePowerC;
    private Float angleAtoB;
    private Float angleAtoC;
    private Float angleBtoC;
}
demo运行大概有5分钟就开始报错Invalid result set pointer，请问是哪里出的问题，这个错误的原因是什么，谢谢

**Comment by Shawshank-Smile** [comment]
不要在一个connection中多线程服用Statement。在下个版本的jdbc-driver里会修复这个问题

**Comment by moziie** [comment]
> 不要在一个connection中多线程服用Statement。在下个版本的jdbc-driver里会修复这个问题

请问目前版本做测试的时候，如果使用线程进行插入应该如何创建connection与Statement，如何使用

**Comment by zyyang-taosdata** [comment]
> > 不要在一个connection中多线程服用Statement。在下个版本的jdbc-driver里会修复这个问题
> 
> 请问目前版本做测试的时候，如果使用线程进行插入应该如何创建connection与Statement，如何使用

在2.0.19版本中已经修复了invalid result set pointer这个问题，Connection和Statement的线程安全问题已经解决。至于，如何使用Connection和Statement，可以参考一下官网文档：https://www.taosdata.com/cn//documentation20/connector-java/

**Comment by moziie** [comment]
> > > 不要在一个connection中多线程服用Statement。在下个版本的jdbc-driver里会修复这个问题
> > 
> > 
> > 请问目前版本做测试的时候，如果使用线程进行插入应该如何创建connection与Statement，如何使用
> 
> 在2.0.19版本中已经修复了invalid result set pointer这个问题，Connection和Statement的线程安全问题已经解决。至于，如何使用Connection和Statement，可以参考一下官网文档：https://www.taosdata.com/cn//documentation20/connector-java/

好的谢谢我去调整逻辑，简单试了下2.0.19的jdbc执行statement.execute(sql)语句执行成功但是返回值是false,不知道您是否注意到这个问题

**Comment by moziie** [comment]
for(int i=1;i<100000;i++){
 Statement statement = connection.createStatement();
  threadPoolExecutor.execute(() ->{
       statement.execute(sql);
});
}
这样跑程序的话，5~10分钟报错java.sql.SQLException: ERROR (8000000b): Unable to establish connection
一路找下去，但不太明白问题出在哪里
       Long pSql = 0l;
        try {
            /**在这里执行的这个方法返回的pSql值影响下面逻辑判断**/
            pSql = this.executeQueryImp(sql.getBytes(TaosGlobalConfig.getCharset()), this.taos);
            taosInfo.stmt_count_increment();
        } catch (Exception e) {
            e.printStackTrace();
            this.freeResultSetImp(this.taos, pSql);
            throw new SQLException(TSDBConstants.WrapErrMsg("Unsupported encoding"));
        }
       /**到这里使用pSql获取code判断，不为0*/
        int code = this.getErrCode(pSql);
        if (code != 0) {
            affectedRows = -1;
            String msg = this.getErrMsg(pSql);

            this.freeResultSetImp(this.taos, pSql);
            /**抛出这个错误*/
            throw new SQLException(TSDBConstants.WrapErrMsg(msg), "", code);
        }
请问我这样使用方式有问题吗

**Comment by moziie** [comment]
invalid result set pointer错误，换了jdbc版本后解决，关闭
