### ISSUE TITLE
Query speed and efficiency

### ISSUE THREAD

**Issue by xiangxud** [taosdata/TDengine#5180]
How to optimize query speed and efficiency 
3w rows use 10s
taos> use log;
taos> select * from dn;
Query OK, 30448 row(s) in set (10.545586s)
[root@mqttserver debug]# taosd -v
02/07 10:05:34.572291 0x7fe70cc34740 TMR ttimer monotonic clock source:X86 TSC @ 2500 ticks/us
02/07 10:05:34.572558 0x7fe70cc34740 DND start to initialize TDengine
02/07 10:05:34.572607 0x7fe70cc34740 DND step:dnode-tfile is initialized
02/07 10:05:34.572622 0x7fe70cc34740 DND step:dnode-rpc is initialized
02/07 10:05:34.572631 0x7fe70cc34740 UTL localEp is: 172.16.0.149:6030
02/07 10:05:34.572973 0x7fe70cc34740 UTL WARN timezone not configured, set to system default: (CST, +0800)
02/07 10:05:34.573044 0x7fe70cc34740 UTL WARN locale not configured, set to system default:en_US.UTF-8
02/07 10:05:34.573067 0x7fe70cc34740 UTL WARN charset not configured, set to system default:UTF-8
02/07 10:05:34.573095 0x7fe70cc34740 UTL    taos config & system info:
02/07 10:05:34.573103 0x7fe70cc34740 UTL ==================================
02/07 10:05:34.573113 0x7fe70cc34740 UTL  firstEp:                x'x'x:6030
02/07 10:05:34.573120 0x7fe70cc34740 UTL  secondEp:               x'x'x:6030
02/07 10:05:34.573128 0x7fe70cc34740 UTL  fqdn:                   x'x'x
02/07 10:05:34.573135 0x7fe70cc34740 UTL  serverPort:             6030
02/07 10:05:34.573142 0x7fe70cc34740 UTL  configDir:              /etc/taos
02/07 10:05:34.573150 0x7fe70cc34740 UTL  logDir:                 /var/log/taos
02/07 10:05:34.573157 0x7fe70cc34740 UTL  scriptDir:              /etc/taos
02/07 10:05:34.573164 0x7fe70cc34740 UTL  arbitrator:
02/07 10:05:34.573172 0x7fe70cc34740 UTL  numOfThreadsPerCore:    1.000000
02/07 10:05:34.573191 0x7fe70cc34740 UTL  numOfCommitThreads:     1
02/07 10:05:34.573198 0x7fe70cc34740 UTL  ratioOfQueryCores:      1.000000
02/07 10:05:34.573206 0x7fe70cc34740 UTL  numOfMnodes:            3
02/07 10:05:34.573213 0x7fe70cc34740 UTL  vnodeBak:               1
02/07 10:05:34.573220 0x7fe70cc34740 UTL  telemetryReporting:     1
02/07 10:05:34.573227 0x7fe70cc34740 UTL  balance:                1
02/07 10:05:34.573234 0x7fe70cc34740 UTL  balanceInterval:        300
02/07 10:05:34.573241 0x7fe70cc34740 UTL  role:                   0
02/07 10:05:34.573249 0x7fe70cc34740 UTL  maxTmrCtrl:             512
02/07 10:05:34.573256 0x7fe70cc34740 UTL  monitorInterval:        30(s)
02/07 10:05:34.573263 0x7fe70cc34740 UTL  offlineThreshold:       8640000(s)
02/07 10:05:34.573271 0x7fe70cc34740 UTL  rpcTimer:               1000(ms)
02/07 10:05:34.573278 0x7fe70cc34740 UTL  rpcMaxTime:             600(s)
02/07 10:05:34.573285 0x7fe70cc34740 UTL  statusInterval:         1(s)
02/07 10:05:34.573292 0x7fe70cc34740 UTL  shellActivityTimer:     3(s)
02/07 10:05:34.573299 0x7fe70cc34740 UTL  minSlidingTime:         10(ms)
02/07 10:05:34.573306 0x7fe70cc34740 UTL  minIntervalTime:        10(ms)
02/07 10:05:34.573313 0x7fe70cc34740 UTL  maxStreamCompDelay:     20000(ms)
02/07 10:05:34.573320 0x7fe70cc34740 UTL  maxFirstStreamCompDelay:10000(ms)
02/07 10:05:34.573327 0x7fe70cc34740 UTL  retryStreamCompDelay:   10(ms)
02/07 10:05:34.573335 0x7fe70cc34740 UTL  streamCompDelayRatio:   0.100000
02/07 10:05:34.573359 0x7fe70cc34740 UTL  maxVgroupsPerDb:        0
02/07 10:05:34.573366 0x7fe70cc34740 UTL  maxTablesPerVnode:      1000000
02/07 10:05:34.573373 0x7fe70cc34740 UTL  minTablesPerVnode:      1000
02/07 10:05:34.573379 0x7fe70cc34740 UTL  tableIncStepPerVnode:   1000
02/07 10:05:34.573386 0x7fe70cc34740 UTL  cache:                  16(Mb)
02/07 10:05:34.573393 0x7fe70cc34740 UTL  blocks:                 6
02/07 10:05:34.573399 0x7fe70cc34740 UTL  days:                   10
02/07 10:05:34.573405 0x7fe70cc34740 UTL  keep:                   3650
02/07 10:05:34.573412 0x7fe70cc34740 UTL  minRows:                100
02/07 10:05:34.573419 0x7fe70cc34740 UTL  maxRows:                4096
02/07 10:05:34.573425 0x7fe70cc34740 UTL  comp:                   2
02/07 10:05:34.573432 0x7fe70cc34740 UTL  walLevel:               1
02/07 10:05:34.573438 0x7fe70cc34740 UTL  fsync:                  3000
02/07 10:05:34.573445 0x7fe70cc34740 UTL  replica:                1
02/07 10:05:34.573451 0x7fe70cc34740 UTL  quorum:                 1
02/07 10:05:34.573458 0x7fe70cc34740 UTL  update:                 0
02/07 10:05:34.573467 0x7fe70cc34740 UTL  compressMsgSize:        -1
02/07 10:05:34.573474 0x7fe70cc34740 UTL  maxSQLLength:           65480(byte)
02/07 10:05:34.573481 0x7fe70cc34740 UTL  maxNumOfOrderedRes:     100000
02/07 10:05:34.573487 0x7fe70cc34740 UTL  queryBufferSize:        -1(byte)
02/07 10:05:34.573494 0x7fe70cc34740 UTL  retrieveBlockingModel:  0
02/07 10:05:34.573501 0x7fe70cc34740 UTL  keepColumnName:         0
02/07 10:05:34.573507 0x7fe70cc34740 UTL  timezone:                (CST, +0800)
02/07 10:05:34.573514 0x7fe70cc34740 UTL  locale:                 en_US.UTF-8
02/07 10:05:34.573521 0x7fe70cc34740 UTL  charset:                UTF-8
02/07 10:05:34.573528 0x7fe70cc34740 UTL  maxShellConns:          5000
02/07 10:05:34.573534 0x7fe70cc34740 UTL  maxConnections:         5000
02/07 10:05:34.573541 0x7fe70cc34740 UTL  minimalLogDirGB:        1.000000(GB)
02/07 10:05:34.573548 0x7fe70cc34740 UTL  minimalTmpDirGB:        1.000000(GB)
02/07 10:05:34.573555 0x7fe70cc34740 UTL  minimalDataDirGB:       1.000000(GB)
02/07 10:05:34.573562 0x7fe70cc34740 UTL  mnodeEqualVnodeNum:     4
02/07 10:05:34.573568 0x7fe70cc34740 UTL  flowctrl:               1
02/07 10:05:34.573575 0x7fe70cc34740 UTL  slaveQuery:             1
02/07 10:05:34.573581 0x7fe70cc34740 UTL  adjustMaster:           1
02/07 10:05:34.573588 0x7fe70cc34740 UTL  http:                   1
02/07 10:05:34.573594 0x7fe70cc34740 UTL  mqtt:                   0
02/07 10:05:34.573601 0x7fe70cc34740 UTL  monitor:                1
02/07 10:05:34.573607 0x7fe70cc34740 UTL  stream:                 1
02/07 10:05:34.573614 0x7fe70cc34740 UTL  httpEnableRecordSql:    0
02/07 10:05:34.573620 0x7fe70cc34740 UTL  telegrafUseFieldNum:    0
02/07 10:05:34.573627 0x7fe70cc34740 UTL  httpMaxThreads:         2
02/07 10:05:34.573633 0x7fe70cc34740 UTL  restfulRowLimit:        10240
02/07 10:05:34.573640 0x7fe70cc34740 UTL  numOfLogLines:          10000000
02/07 10:05:34.573647 0x7fe70cc34740 UTL  logKeepDays:            0
02/07 10:05:34.573653 0x7fe70cc34740 UTL  asyncLog:               1
02/07 10:05:34.573660 0x7fe70cc34740 UTL  debugFlag:              0
02/07 10:05:34.573666 0x7fe70cc34740 UTL  mDebugFlag:             131
02/07 10:05:34.573673 0x7fe70cc34740 UTL  dDebugFlag:             135
02/07 10:05:34.573679 0x7fe70cc34740 UTL  sDebugFlag:             135
02/07 10:05:34.573686 0x7fe70cc34740 UTL  wDebugFlag:             135
02/07 10:05:34.574185 0x7fe70cc34740 UTL  sdbDebugFlag:           131
02/07 10:05:34.574198 0x7fe70cc34740 UTL  rpcDebugFlag:           131
02/07 10:05:34.574204 0x7fe70cc34740 UTL  tmrDebugFlag:           131
02/07 10:05:34.574211 0x7fe70cc34740 UTL  cDebugFlag:             131
02/07 10:05:34.574217 0x7fe70cc34740 UTL  jniDebugFlag:           131
02/07 10:05:34.574224 0x7fe70cc34740 UTL  odbcDebugFlag:          131
02/07 10:05:34.574230 0x7fe70cc34740 UTL  uDebugFlag:             131
02/07 10:05:34.574245 0x7fe70cc34740 UTL  httpDebugFlag:          131
02/07 10:05:34.574251 0x7fe70cc34740 UTL  mqttDebugFlag:          131
02/07 10:05:34.574258 0x7fe70cc34740 UTL  monDebugFlag:           131
02/07 10:05:34.574264 0x7fe70cc34740 UTL  qDebugFlag:             131
02/07 10:05:34.574271 0x7fe70cc34740 UTL  vDebugFlag:             135
02/07 10:05:34.574277 0x7fe70cc34740 UTL  tsdbDebugFlag:          131
02/07 10:05:34.574283 0x7fe70cc34740 UTL  cqDebugFlag:            131
02/07 10:05:34.574290 0x7fe70cc34740 UTL  enableRecordSql:        0
02/07 10:05:34.574297 0x7fe70cc34740 UTL  enableCoreFile:         0
02/07 10:05:34.574303 0x7fe70cc34740 UTL  gitinfo:                c2215eb214bed8345180600537d695b8bba076e1
02/07 10:05:34.574310 0x7fe70cc34740 UTL  gitinfoOfInternal:      c2215eb214bed8345180600537d695b8bba076e1
02/07 10:05:34.574317 0x7fe70cc34740 UTL  buildinfo:              Built at 2021-02-06 22:54:07
02/07 10:05:34.574324 0x7fe70cc34740 UTL  version:                2.0.14.0
02/07 10:05:34.574331 0x7fe70cc34740 UTL  maxBinaryDisplayWidth:  30
02/07 10:05:34.574338 0x7fe70cc34740 UTL  tempDir:                /tmp/
02/07 10:05:34.574349 0x7fe70cc34740 UTL  os pageSize:            4096(KB)
02/07 10:05:34.574356 0x7fe70cc34740 UTL  os openMax:             65535
02/07 10:05:34.574362 0x7fe70cc34740 UTL  os streamMax:           16
02/07 10:05:34.574368 0x7fe70cc34740 UTL  os numOfCores:          2
02/07 10:05:34.574374 0x7fe70cc34740 UTL  os totalDisk:           0.000000(GB)
02/07 10:05:34.574382 0x7fe70cc34740 UTL  os totalMemory:         7821(MB)
02/07 10:05:34.574395 0x7fe70cc34740 UTL  os sysname:             Linux
02/07 10:05:34.574401 0x7fe70cc34740 UTL  os nodename:            mqttserver
02/07 10:05:34.574408 0x7fe70cc34740 UTL  os release:             3.10.0-1062.7.1.el7.x86_64
02/07 10:05:34.574414 0x7fe70cc34740 UTL  os version:             #1 SMP Mon Dec 2 17:33:29 UTC 2019
02/07 10:05:34.574420 0x7fe70cc34740 UTL  os machine:             x86_64
02/07 10:05:34.574427 0x7fe70cc34740 UTL  dataDir: /var/lib/taos
02/07 10:05:34.574434 0x7fe70cc34740 UTL ==================================
02/07 10:05:34.574440 0x7fe70cc34740 DND step:dnode-globalcfg is initialized
02/07 10:05:34.574489 0x7fe70cc34740 TFS disk /var/lib/taos is mounted to tier level 0 id 0
02/07 10:05:34.574562 0x7fe70cc34740 DND ERROR failed to lock file:/var/lib/taos/dnode/.running ret:-1[Resource tempo
rarily unavailable], database may be running, quit

ali yun centos 7 cpu Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz mem 8G
# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    2
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
Stepping:              4
CPU MHz:               2499.990
BogoMIPS:              4999.98
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              33792K
NUMA node0 CPU(s):     0,1
lsmem
RANGE                                  SIZE  STATE REMOVABLE BLOCK
0x0000000000000000-0x000000000fffffff  256M online        no   0-1
0x0000000010000000-0x0000000017ffffff  128M online       yes     2
0x0000000018000000-0x000000007fffffff  1.6G online        no  3-15
0x0000000080000000-0x0000000087ffffff  128M online       yes    16
0x0000000088000000-0x00000000bfffffff  896M online        no 17-23
0x0000000100000000-0x000000010fffffff  256M online        no 32-33
0x0000000110000000-0x0000000117ffffff  128M online       yes    34
0x0000000118000000-0x0000000137ffffff  512M online        no 35-38
0x0000000138000000-0x000000013fffffff  128M online       yes    39
0x0000000140000000-0x0000000147ffffff  128M online        no    40
0x0000000148000000-0x0000000177ffffff  768M online       yes 41-46
0x0000000178000000-0x000000023fffffff  3.1G online        no 47-71

Memory block size:       128M
Total online memory:       8G
Total offline memory:      0B

**Comment by Shawshank-Smile** [comment]
Huge Question ...
It involves thread writing mode, writing frequency, table schema, etc,
In addition, cache, block, days and other parameters need to be adjusted

**Comment by xiangxud** [comment]
yes ，this is Huge Question。I use default config ，query tdengine‘s internal default database log ，table is dn，I think the default config is best performance settings，Do you have any reference documents for this.

**Comment by Shawshank-Smile** [comment]
Query the dabase log?   "3w rows use 10s"？
show me the info:
taos

show dnodes;
show mnodes;
use log;
show vgroups;

**Comment by xiangxud** [comment]
[root@mqttserver ~]# taos

Welcome to the TDengine shell from Linux, Client Version:2.0.14.0
Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.

taos> show dnodes;
   id   |           end_point            | vnodes | cores  |   status   | role  |       create_time       |      offl
ine reason      |
=====================================================================================================================
=================
      1 | 172.16.0.149:6030              |      2 |      2 | ready      | any   | 2021-01-27 19:48:05.914 |
                |
Query OK, 1 row(s) in set (0.000903s)

taos> show mnodes;
   id   |           end_point            |     role     |       create_time       |
===================================================================================
      1 | 172.16.0.149:6030              | master       | 2021-01-27 19:48:05.916 |
Query OK, 1 row(s) in set (0.016405s)

taos> use log;
Database changed.

taos> show vgroups;
    vgId     |   tables    |  status  |   onlines   | v1_dnode | v1_status |
============================================================================
           2 |           4 | ready    |           1 |        1 | master    |
Query OK, 1 row(s) in set (0.016277s)

taos>select * from dn;
......
           79.74414 |           0 |           0 |          44 |           1 | 172.16.0.149:6030              |
 2021-02-07 19:32:48.841128 |              0.11589 |            100.00000 |           2 |            103.87109 |
      7682.00781 |        7821 |              9.58743 |          78 |             15.36667 |             54.36328 |
           92.84961 |           0 |           0 |          63 |           1 | 172.16.0.149:6030              |
 2021-02-07 19:33:19.039021 |              0.09939 |            100.00000 |           2 |            103.87109 |
      7684.33984 |        7821 |              9.58730 |          78 |             18.12172 |             54.36328 |
           76.25781 |           0 |           0 |          38 |           1 | 172.16.0.149:6030              |
 2021-02-07 19:33:49.201284 |              0.11607 |            100.00000 |           2 |            103.87109 |
      7683.20312 |        7821 |              9.58711 |          78 |             15.26771 |             54.36328 |
           99.29492 |           0 |           0 |          76 |           1 | 172.16.0.149:6030              |
 2021-02-07 19:34:19.419239 |              0.11587 |            100.00000 |           2 |            103.87109 |
      7685.32422 |        7821 |              9.58696 |          78 |             18.40573 |             54.36328 |
           79.99805 |           0 |           0 |          44 |           1 | 172.16.0.149:6030              |
 2021-02-07 19:34:49.564081 |              0.13274 |            100.00000 |           2 |            103.87109 |
      7687.31250 |        7821 |              9.58677 |          78 |             16.27813 |             52.68164 |
           94.15039 |           0 |           0 |          71 |           1 | 172.16.0.149:6030              |
 2021-02-07 19:35:19.744099 |              0.09944 |            100.00000 |           2 |            103.87109 |
      7687.33984 |        7821 |              9.58662 |          78 |             25.51510 |             54.79492 |
           84.95020 |           0 |           0 |          44 |           1 | 172.16.0.149:6030              |
 2021-02-07 19:35:49.932988 |              0.11599 |            100.00000 |           2 |            103.87109 |
      7686.38672 |        7821 |              9.58644 |          78 |             16.71380 |             54.57910 |
           97.30371 |           0 |           0 |          70 |           1 | 172.16.0.149:6030              |
Query OK, 31638 row(s) in set (10.806497s)

taos>

**Comment by Shawshank-Smile** [comment]
where is the info about "3w rows use 10s"？

**Comment by xiangxud** [comment]
Query OK, 31638 row(s) in set (10.806497s)

**Comment by Shawshank-Smile** [comment]
select * from dn >> file

**Comment by xiangxud** [comment]
taos> use log;
Database changed.

taos> select * from dn >>dn20211220934
   -> ;
Query OK, 67688 row(s) in set (1.855158s)

taos>
