### ISSUE TITLE
Industrial Internet of things application scenarios

### ISSUE THREAD

**Issue by zhou-hao** [taosdata/TDengine#5181]
类似OPC-UA方式采集数据，一个点位可以理解为一列数据，但是每一个点位的采集频率可能是不同的，无法按一行一行的数据来存储。这种场景下，怎么设计表结构比较合适。

**Comment by Shawshank-Smile** [comment]
Single column mode can be adopted, one table for each point.

**Comment by zhou-hao** [comment]
比如一个分组下，有1000个点位，如果一个点位就是一个表，那要同时获取这1000个点位的数据值，就只能执行1000次查询了？

**Comment by Shawshank-Smile** [comment]
In theory. However, if you want to get the latest data, you can use last_ Row group by TBNAME.
