### ISSUE TITLE
select count(*) with DB Error: no such file or directory

### ISSUE THREAD

**Issue by deuxmille** [taosdata/TDengine#5187]
崭新的机器，装上2.0.15.0，建立数据库，建立超级表。
这个时候select * 和 select count( * ) from这个超级表，返回都是0。
然后插入一些数据到这个超级表。
select * 能返回这些数据，但是select count( * )则会返回DB Error: no such file or directory。

系统
处理器	AMD Ryzen 7 5800X 8-Core Processor                3.80 GHz
机带 RAM	32.0 GB
系统类型	64 位操作系统, 基于 x64 的处理器
机器上安装的vmware workstation 16.0
在虚拟机里安装ubuntu 20.04 server

以上操作在另一台物理机器上安装的ubuntu上并不会有问题。

操作截图、命令、以及taosd的log附件于下方。

[deuxmille_taos_issue_20210207.zip](https://github.com/taosdata/TDengine/files/5938657/deuxmille_taos_issue_20210207.zip)

**Comment by sangshuduo** [comment]
发现了原因是 tempDir 指定到了一个不存在的目录。我们研究一下如何解决。

**Comment by deuxmille** [comment]
手动建立tmp文件夹解决问题。需要你们程序初始化的时候做好文件夹检查和建立。

**Comment by sangshuduo** [comment]
close as issue resolved.
