### ISSUE TITLE
How to fix? >> reason:invalid SQL: syntax error near

### ISSUE THREAD

**Issue by NTDary** [taosdata/TDengine#519]
![](https://i.imgur.com/aY2FMdy.jpg)

I tried Export from TDengine Shell in c ++, but there was an error reason: invalid SQL: syntax error near "block0.csv;"

**Comment by fangpanpan** [comment]
SQL syntax: "select * from <tb_name> >> a.csv" can export your query results to a file.

**Comment by NTDary** [comment]
I can export file by directly enter that command in the terminal, but when I use C/C++ program:

      sprintf(command1,"select * from tmpjwclab1 >> block.csv");
      printf("%s\n",command1);
      if (taos_query(taos, command1) != 0) {
        printf("Export fail:%s\n", taos_errstr(taos));
        exit(1);
      }else{
        printf("Export success\n");
      }

I can not export file, it return: syntax error near ">> block.csv"

Help me, please

**Comment by hjxilinx** [comment]
execute the SQL expression in the shell. And you will get a csv file
>select * from tmpjwclab1 >> block.csv;

**Comment by NTDary** [comment]
It work, but I want to do it by a C/C++ program.

Is there anyway to help me !

**Comment by fangpanpan** [comment]
> 
> 
> It work, but I want to do it by a C/C++ program.
> 
> Is there anyway to help me !

you can refer to our demo c code in [https://github.com/taosdata/TDengine/blob/master/tests/examples/c/demo.c](url).  On line 79-105, it shows how to retrieve the query result "row". Then you can write the query result to a file in C program.

**Comment by NTDary** [comment]
It will take alot of time to export a file (1M size) 

I think the query function of taos lib has bug, can you share me the source, I will try to debug.

**Comment by plum-lihui** [comment]
The export file API  has not been implemented  by C。

**Comment by NTDary** [comment]
How can i delete some lines in STable? 
Please help me with this problem.

**Comment by fangpanpan** [comment]
Now we don't support the operation like deleting some lines. Add/Drop some columns is supported.
