### ISSUE TITLE
加入新的集群节点 提示 sync confirm expired

### ISSUE THREAD

**Issue by zhangzhenguo100865** [taosdata/TDengine#5190]
我截取了部分日志不知道能否看出来问题。。
02/08 09:26:57.454049 0x7fd1d66f6700 DND dnode:1, dnodeFqdn:hadoop1 dnodePort:40065
02/08 09:26:57.454061 0x7fd1d66f6700 DND dnode:2, dnodeFqdn:hadoop2 dnodePort:40067
02/08 09:26:57.454067 0x7fd1d66f6700 DND dnode:3, dnodeFqdn:hadoop3 dnodePort:40072
02/08 09:26:57.454073 0x7fd1d66f6700 DND dnode:4, dnodeFqdn:kafka1 dnodePort:40032
02/08 09:26:57.454088 0x7fd1d66f6700 DND dnode:5, dnodeFqdn:kafka2 dnodePort:40038
02/08 09:26:57.454095 0x7fd1d66f6700 DND dnode:6, dnodeFqdn:kafka3 dnodePort:40042
02/08 09:26:57.454101 0x7fd1d66f6700 DND dnode:14, dnodeFqdn:zookeeper dnodePort:40078
02/08 09:26:57.456188 0x7fd1d66f6700 DND successed to write /var/lib/taos/dnode/dnodeEps.json
02/08 09:26:57.744261 0x7fd1d2a2e700 MND dnode:14, from offline to online
02/08 09:26:58.221977 0x7fd1cbfff700 MND user:monitor login from 172.17.102.10, result:success
02/08 09:26:58.222632 0x7fd0bff65700 TSC ERROR 0x7fd0880009b0 invoke user specified function due to error occured, code:Database is balancing
02/08 09:26:58.222722 0x7fd0bff65700 MON ERROR save log failed, reason:Database is balancing
02/08 09:26:58.248560 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 09:26:58.533407 0x7fd1e5e33700 DND msg:0x7fd098000920, app:0x8 type:create-table is reput into mwrite queue:0x26f3de0, retry times:1
02/08 09:26:58.838331 0x7fd1e5e33700 DND msg:0x7fd098000920, app:0x8 type:create-table is reput into mwrite queue:0x26f3de0, retry times:2
02/08 09:26:59.088583 0x7fd1e5e33700 SYN vgId:1, forward info expired, hver:3022559 curtime:1612747619088 savetime:1612747616908
02/08 09:26:59.143409 0x7fd1e5e33700 DND msg:0x7fd098000920, app:0x8 type:create-table is reput into mwrite queue:0x26f3de0, retry times:3
02/08 09:26:59.253501 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 09:26:59.393566 0x7fd1e5e33700 SYN vgId:1, forward info expired, hver:3022559 curtime:1612747619393 savetime:1612747616908
02/08 09:26:59.393631 0x7fd1e5e33700 SDB ERROR vgId:1, row:0x7fd08c0fec50:14 hver:3022559 action:insert, failed to foward since Sync confirm expired
02/08 09:26:59.393747 0x7fd1e5e33700 MND vgId:1, update mnodes epSet, numOfMnodes:3
02/08 09:26:59.393800 0x7fd1e5e33700 MND vgId:1, mnodes epSet is set, num:3 inUse:0
02/08 09:26:59.393833 0x7fd1e5e33700 MND vgId:1, mnode:1, fqdn:hadoop1 shell:40065 peer:40070
02/08 09:26:59.393861 0x7fd1e5e33700 MND vgId:1, mnode:2, fqdn:hadoop2 shell:40067 peer:40072
02/08 09:26:59.393930 0x7fd1e5e33700 MND vgId:1, mnode:3, fqdn:hadoop3 shell:40072 peer:40077
02/08 09:26:59.448356 0x7fd1e5e33700 DND msg:0x7fd098000920, app:0x8 type:create-table is reput into mwrite queue:0x26f3de0, retry times:4
02/08 09:26:59.753416 0x7fd1e5e33700 DND msg:0x7fd098000920, app:0x8 type:create-table is reput into mwrite queue:0x26f3de0, retry times:5
02/08 09:26:59.759178 0x7fd1d2a2e700 MND ERROR dnode:14, zookeeper:40078 not exist
02/08 09:26:59.898633 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 09:27:00.058434 0x7fd1e5e33700 DND msg:0x7fd098000920, app:0x8 type:create-table is reput into mwrite queue:0x26f3de0, retry times:6
02/08 09:27:00.363399 0x7fd1e5e33700 DND msg:0x7fd098000920, app:0x8 type:create-table is reput into mwrite queue:0x26f3de0, retry times:7
02/08 09:27:00.668432 0x7fd1e5e33700 DND msg:0x7fd098000920, app:0x8 type:create-table is reput into mwrite queue:0x26f3de0, retry times:8
02/08 09:27:00.764171 0x7fd1d2a2e700 MND ERROR dnode:14, zookeeper:40078 not exist
02/08 09:27:00.903545 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 09:27:00.973428 0x7fd1e5e33700 DND msg:0x7fd098000920, app:0x8 type:create-table is reput into mwrite queue:0x26f3de0, retry times:9
02/08 09:27:00.974218 0x7fd1d5ef5700 MND ERROR msg:0x7fd098000920, app:0x8 table:0.log.dn14, failed to create in dnode, vgId:2 sid:180 uid:562952975343519, result:Database is balancing thandle:0xf28a638 incomingTs:1612747618 curTs:1612747620 retryTimes:10
02/08 09:27:01.528541 0x7fd1e5e33700 SYN vgId:1, forward info expired, hver:3022560 curtime:1612747621528 savetime:1612747619394
02/08 09:27:01.769188 0x7fd1d2a2e700 MND ERROR dnode:14, zookeeper:40078 not exist
02/08 09:27:01.833458 0x7fd1e5e33700 SYN vgId:1, forward info expired, hver:3022560 curtime:1612747621833 savetime:1612747619394
02/08 09:27:01.833515 0x7fd1e5e33700 SDB ERROR vgId:1, row:0x7fd08c0fec50:14 hver:3022560 action:delete, failed to foward since Sync confirm expired
02/08 09:27:01.908626 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 09:27:02.278478 0x7fd1e5e33700 DND msg:0x7fd098000920, app:0xa type:create-table is reput into mwrite queue:0x26f3de0, retry times:1
02/08 09:27:02.583426 0x7fd1e5e33700 DND msg:0x7fd098000920, app:0xa type:create-table is reput into mwrite queue:0x26f3de0, retry times:2
02/08 09:27:02.774164 0x7fd1d2a2e700 MND ERROR dnode:14, zookeeper:40078 not exist
02/08 09:27:02.888459 0x7fd1e5e33700 DND msg:0x7fd098000920, app:0xa type:create-table is reput into mwrite queue:0x26f3de0, retry times:3
02/08 09:27:02.913545 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 09:27:03.059418 0x7fd1e5e33700 SYN vgId:1, forward info expired, hver:3022561 curtime:1612747623059 savetime:1612747620974
02/08 09:27:03.193341 0x7fd1e5e33700 DND msg:0x7fd098000920, app:0xa type:create-table is reput into mwrite queue:0x26f3de0, retry times:4
02/08 09:27:03.363474 0x7fd1e5e33700 SYN vgId:1, forward info expired, hver:3022561 curtime:1612747623363 savetime:1612747620974
02/08 09:27:03.363523 0x7fd1e5e33700 SDB ERROR vgId:1, row:0x7fd08c0ff180:0.log.dn14 hver:3022561 action:delete, failed to foward since Sync confirm expired
02/08 09:27:03.498334 0x7fd1e5e33700 DND msg:0x7fd098000920, app:0xa type:create-table is reput into mwrite queue:0x26f3de0, retry times:5
02/08 09:27:03.779297 0x7fd1d2a2e700 MND ERROR dnode:14, zookeeper:40078 not exist
02/08 09:27:03.803386 0x7fd1e5e33700 DND msg:0x7fd098000920, app:0xa type:create-table is reput into mwrite queue:0x26f3de0, retry times:6
02/08 09:27:03.918598 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 09:27:04.108406 0x7fd1e5e33700 DND msg:0x7fd098000920, app:0xa type:create-table is reput into mwrite queue:0x26f3de0, retry times:7
02/08 09:27:04.413450 0x7fd1e5e33700 DND msg:0x7fd098000920, app:0xa type:create-table is reput into mwrite queue:0x26f3de0, retry times:8
02/08 09:27:04.718512 0x7fd1e5e33700 DND msg:0x7fd098000920, app:0xa type:create-table is reput into mwrite queue:0x26f3de0, retry times:9
02/08 09:27:04.719329 0x7fd1d5ef5700 MND ERROR msg:0x7fd098000920, app:0xa table:0.log.dn14, failed to create in dnode, vgId:2 sid:181 uid:562952992121127, result:Database is balancing thandle:0xf28a638 incomingTs:1612747621 curTs:1612747624 retryTimes:10
02/08 09:27:04.784275 0x7fd1d2a2e700 MND ERROR dnode:14, zookeeper:40078 not exist
02/08 09:27:04.923516 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 09:27:05.789314 0x7fd1d2a2e700 MND ERROR dnode:14, zookeeper:40078 not exist
02/08 09:27:05.928523 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode

**Comment by guanshengliang** [comment]
这个问题已经进入我们内部任务系统，后续会持续跟踪。但是您给提供的这些信息是不够的。请您做如下工作
1.升级所有机器的版本到最新版本（现在应该是2.0.15.0）
2.确定所有机器的taosd进程都存在
3.将一个小时以内的新日志，打包上传

**Comment by zhangzhenguo100865** [comment]
前两个问题我这边确定是对的，端口都是打开的状态。

**Comment by zhangzhenguo100865** [comment]
第三个问题。日志的话，是所有节点的都要吗？

**Comment by guanshengliang** [comment]
是啊，但一个没办法看。另外，如果有远程环境的话，我今天晚上9点左右，可以看一下

**Comment by zhangzhenguo100865** [comment]
好的，那晚上我可以给您开个远程

**Comment by zhangzhenguo100865** [comment]
另外，我这边还出现了一个情况，就是我删除一个节点，节点状态一直是 dropping。这个是后台在同步数据吗？大概多久能完成，我看到日志有报错

**Comment by zhangzhenguo100865** [comment]
02/08 10:48:57.243489 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:48:58.248560 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:48:59.253525 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:00.258434 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:01.263489 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:02.268502 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:03.273551 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:04.278481 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:05.283577 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:06.288500 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:07.293619 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:08.298603 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:09.303610 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:10.308680 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:11.313730 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:12.318523 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:13.323560 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:14.328527 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:15.333525 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:16.338585 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:17.343557 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:18.348573 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:19.353576 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:20.358532 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:21.363505 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:22.368604 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:23.373669 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:24.378574 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:25.383580 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:26.388451 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode
02/08 10:49:26.992929 0x7fd0c0f67700 TSC ERROR 0x7fd1af18bcf0 invoke user specified function due to error occured, code:Database is balancing
02/08 10:49:26.993133 0x7fd0cdf81700 MON ERROR failed to save system info, reason:Database is balancing, sql:insert into log.dn1 values(1612752566989665, 4.321198, 4.421197, 8, 1031.496094, 7551.707031, 7974, 29.194096, 58, 29208.662109, 11767.587891, 90415.765625, 0, 0, 0)
02/08 10:49:27.393643 0x7fd0d1786700 MND vgId:2, replica:1 numOfVnodes:2, try remove one vnode

**Comment by huchaogithup** [comment]
04/09 04:21:54.695029 00000022 MND ERROR msg:0x7fe4e802e900, app:0x36c7 table:0.nss_test.s_2_1183_2_1009226_default_979046_979046,1183,'default',1009226,'/', failed to create in dnode, vgId:6 sid:87543 uid:1690318604765433, result:Sync confirm expired thandle:0x7fe56d778688 incomingTs:1649478093 curTs:1649478114 retryTimes:2
04/09 04:21:54.695172 00000022 MND ERROR msg:0x7fe4e8050400, app:0x36c8 table:0.nss_test.a_19_22053466_33_316327_37733445_default_316327_316327,22053466,'default',37733445, failed to create in dnode, vgId:6 sid:87544 uid:1690318621542551, result:Sync confirm expired thandle:0x7fe56d77a0f8 incomingTs:1649478093 curTs:1649478114 retryTimes:2
04/09 04:21:54.695268 00000022 MND ERROR msg:0x7fe4e80229a0, app:0x36c6 table:0.nss_test.a_833_21806649_1470_752071_40350570_default_752071_752071,21806649,'default',40350570, failed to create in dnode, vgId:6 sid:87545 uid:1690318638319995, result:Sync confirm expired thandle:0x7fe56d773158 incomingTs:1649478093 curTs:1649478114 retryTimes:2
04/09 04:21:54.695349 00000022 MND ERROR msg:0x7fe4cc030fd0, app:0x36ca table:0.nss_test.a_910_22053346_1622_68645_726057_default_68645_68645,22053346,'default',726057,'INCR', failed to create in dnode, vgId:6 sid:87546 uid:1690318655097846, result:Sync confirm expired thandle:0x7fe56d778c68 incomingTs:1649478093 curTs:1649478114 retryTimes:2
04/09 04:21:54.695428 00000022 MND ERROR msg:0x7fe4d8019900, app:0x36cd table:0.nss_test.s_211_4322_446_4138824_default_211814_211814,4322,'default',4138824, failed to create in dnode, vgId:6 sid:87547 uid:1690318671875610, result:Sync confirm expired thandle:0x7fe56d77ae30 incomingTs:1649478093 curTs:1649478114 retryTimes:2
04/09 04:21:54.695508 00000022 MND ERROR msg:0x7fe4e800b820, app:0x36ce table:0.nss_test.s_1_1_13_1957487_default_148710_148710,1,'default',1957487, failed to create in dnode, vgId:6 sid:87548 uid:1690318688653296, result:Sync confirm expired thandle:0x7fe56d7738b0 incomingTs:1649478093 curTs:1649478114 retryTimes:2
04/09 04:21:54.695578 00000022 MND ERROR msg:0x7fe4d004f9b0, app:0x36d6 table:0.nss_test.a_19_1951718_1348_64032_358187_default_64032_64032,1951718,'default',358187, failed to create in dnode, vgId:6 sid:87549 uid:1690318705432113, result:Sync confirm expired thandle:0x7fe56d7767b0 incomingTs:1649478093 curTs:1649478114 retryTimes:2
04/09 04:21:54.695667 00000022 MND ERROR msg:0x7fe4d8013f30, app:0x36d5 table:0.nss_test.a_19_21582061_6020_569881_7494379_default_569881_569881,21582061,'default',7494379,'direct', failed to create in dnode, vgId:6 sid:87550 uid:1690318722209322, result:Sync confirm expired thandle:0x7fe56d777950 incomingTs:1649478093 curTs:1649478114 retryTimes:2
04/09 04:21:54.695748 00000022 MND ERROR msg:0x7fe4e8008fa0, app:0x36d8 table:0.nss_test.s_1_1_10_82963_default_385281_385281,1,'default',82963,'sda', failed to create in dnode, vgId:6 sid:87551 uid:1690318738987448, result:Sync confirm expired thandle:0x7fe56d779b18 incomingTs:1649478093 curTs:1649478114 retryTimes:2
04/09 04:21:54.695828 00000022 MND ERROR msg:0x7fe4d0003780, app:0x36da table:0.nss_test.a_16_21849016_9717_787790_25452346_default_787790_787790,21849016,'default',25452346, failed to create in dnode, vgId:6 sid:87552 uid:1690318755764857, result:Sync confirm expired thandle:0x7fe56d77b298 incomingTs:1649478093 curTs:1649478114 retryTimes:2
04/09 04:21:54.695901 00000022 MND ERROR msg:0x7fe4f40375e0, app:0x36de table:0.nss_test.s_1_10160077_11_41846_default_84984_84984,10160077,'default',41846,'sda', failed to create in dnode, vgId:6 sid:87553 uid:1690318772542287, result:Sync confirm expired thandle:0x7fe56d774470 incomingTs:1649478093 curTs:1649478114 retryTimes:2
04/09 04:21:54.695963 00000022 MND ERROR msg:0x7fe4f4014650, app:0x36df table:0.nss_test.a_921_22053571_4269_569918_7024736_default_569918_b6014de250df2aec44f34c80d40e42cd, failed to create in dnode, vgId:6 sid:87554 uid:1690318789319678, result:Sync confirm expired thandle:0x7fe56d77ab40 incomingTs:1649478093 curTs:1649478114 retryTimes:2
04/09 04:21:54.696025 00000022 MND ERROR msg:0x7fe4d0037360, app:0x36e4 table:0.nss_test.s_1_1_18_2750924_default_627716_627716,1,'default',2750924, failed to create in dnode, vgId:6 sid:87555 uid:1690318806097233, result:Sync confirm expired thandle:0x7fe56d772888 incomingTs:1649478093 curTs:1649478114 retryTimes:2
04/09 04:21:54.696088 00000022 MND ERROR msg:0x7fe4d002a800, app:0x36e3 table:0.nss_test.s_1_1_7_3066825_default_97030_97030,1,'default',3066825,'0', failed to create in dnode, vgId:6 sid:87556 uid:1690318822874488, result:Sync confirm expired thandle:0x7fe56d779f80 incomingTs:1649478093 curTs:1649478114 retryTimes:2
04/09 04:21:54.696150 00000022 MND ERROR msg:0x7fe4d801fdd0, app:0x36e6 table:0.nss_test.a_877_22053085_1575_68645_726057_default_68645_4dc592099c7e3e5b52f8448002723596, failed to create in dnode, vgId:6 sid:87557 uid:1690318839652234, result:Sync confirm expired thandle:0x7fe56d779538 incomingTs:1649478093 curTs:1649478114 retryTimes:2
04/09 04:21:54.696212 00000022 MND ERROR msg:0x7fe4cc033a80, app:0x36ea table:0.nss_test.a_2412_22053600_4903_68645_726057_default_68645_68645,22053600,'default',726057,'$batch_rpc_biz_pool', failed to create in dnode, vgId:6 sid:87558 uid:1690318856430593, result:Sync confirm expired thandle:0x7fe56d775900 incomingTs:1649478093 curTs:1649478114 retryTimes:2
04/09 04:21:54.696274 00000022 MND ERROR msg:0x7fe4f400ac30, app:0x36ef table:0.nss_test.a_877_4157370_1579_56135_390064_default_56135_56135,4157370,'default',390064, failed to create in dnode, vgId:6 sid:87559 uid:1690318873208612, result:Sync confirm expired thandle:0x7fe56d773a28 incomingTs:1649478093 curTs:1649478114 retryTimes:2
04/09 04:21:54.696337 00000022 MND ERROR msg:0x7fe4d005afe0, app:0x36f3 table:0.nss_test.s_2_1183_2_28124375_default_536166_536166,1183,'default',28124375,'/', failed to create in dnode, vgId:6 sid:87560 uid:1690318889986471, result:Sync confirm expired thandle:0x7fe56d7774e8 incomingTs:1649478093 curTs:1649478114 retryTimes:2
04/09 04:21:54.696398 00000022 MND ERROR msg:0x7fe4cc0054f0, app:0x36f2 table:0.nss_test.s_1_1_18_340191_default_804608_804608,1,'default',340191, failed to create in dnode, vgId:6 sid:87561 uid:1690318906763689, result:Sync confirm expired thandle:0x7fe56d774bc8 incomingTs:1649478093 curTs:1649478114 retryTimes:2
04/09 04:21:54.696464 00000022 MND ERROR msg:0x7fe4d00126b0, app:0x36f1 table:0.nss_test.s_53_1061_69_13920_default_20955_20955,1061,'default',13920, failed to create in dnode, vgId:6 sid:87562 uid:1690318923540813, result:Sync confirm expired thandle:0x7fe56d774a50 incomingTs:1649478093 curTs:1649478114 retryTimes:2
04/09 04:21:54.696525 00000022 MND ERROR msg:0x7fe4cc038140, app:0x36f5 table:0.nss_test.s_5259_21819460_10020_56276_default_50108_50108,21819460,'default',56276,'/tmp/.app', failed to create in dnode, vgId:6 sid:87563 uid:1690318940318087, result:Sync confirm expired thandle:0x7fe56d7796b0 incomingTs:1649478093 curTs:1649478114 retryTimes:2
04/09 04:21:54.696586 00000022 MND ERROR msg:0x7fe4d001ef20, app:0x36f8 table:0.nss_test.a_19_22053466_30_316327_37734739_default_316327_316327,22053466,'default',37734739, failed to create in dnode, vgId:6 sid:87564 uid:1690318957095395, result:Sync confirm expired thandle:0x7fe56d778978 incomingTs:1649478093 curTs:1649478114 retryTimes:2
04/09 04:21:54.696648 00000022 MND ERROR msg:0x7fe4cc0619e0, app:0x36fc table:0.nss_test.a_731_22053189_1278_863428_41271817_default_863428_4f267ebb14b11b230bd4a910d2ad888c, failed to create in dnode, vgId:6 sid:87565 uid:1690318973872722, result:Sync confirm expired thandle:0x7fe56d778220 incomingTs:1649478093 curTs:1649478114 retryTimes:2
04/09 04:21:54.696709 00000022 MND ERROR msg:0x7fe4e800e9b0, app:0x36ff table:0.nss_test.s_1_1_13_53794_default_68098_68098,1,'default',53794, failed to create in dnode, vgId:6 sid:87566 uid:1690318990650059, result:Sync confirm expired thandle:0x7fe56d776348 incomingTs:1649478093 curTs:1649478114 retryTimes:2

**Comment by huchaogithup** [comment]
我这边也是 出现较面积 sync confirm expired

**Comment by huchaogithup** [comment]
服务器压力都不大 很空闲

**Comment by huchaogithup** [comment]
show vgroups;
    vgId     |   tables    |  status  |   onlines   | v1_dnode | v1_status | v2_dnode | v2_status | compacting  |
=================================================================================================================
           3 |       87992 | ready    |           1 |        2 | master    |        1 | syncing   |           0 |
           4 |       88000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
           5 |       88000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
           6 |       87958 | ready    |           1 |        2 | master    |        1 | unsynced  |           0 |
           7 |       88000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
           8 |       88000 | ready    |           1 |        2 | master    |        1 | unsynced  |           0 |
           9 |       88000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          10 |       88000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          11 |       88000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          12 |       88000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          13 |       88000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          14 |       88000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          15 |       88000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          16 |       88000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          17 |       88000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          18 |       88000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          19 |       88000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          20 |       87686 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          21 |       87000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          22 |       87000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          23 |       87000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          24 |       87000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          25 |       87000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          26 |       87000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          27 |       87000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          28 |       87000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          29 |       87000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          30 |       87000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          31 |       87000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          32 |       87000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          33 |       87000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          34 |       87000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          35 |       87000 | ready    |           1 |        1 | master    |        2 | syncing   |           0 |
          36 |       87000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          37 |       87000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          38 |       87000 | ready    |           1 |        2 | master    |        1 | syncing   |           0 |
          39 |       87000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          40 |       87000 | ready    |           1 |        2 | master    |        1 | unsynced  |           0 |
          41 |       87000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          42 |       87000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          43 |       87000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          44 |       87000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          45 |       87000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          46 |       87000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          47 |       87000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          48 |       87000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          49 |       87000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          50 |       87000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          51 |       87000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          52 |       87000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          53 |       87000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          54 |       87000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          55 |       87000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          56 |       87000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          57 |       87000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          58 |       87000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          59 |       87000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          60 |       87000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          61 |       87000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          62 |       87000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          63 |       87000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          64 |       87000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |
          65 |       87000 | ready    |           2 |        1 | master    |        2 | slave     |           0 |
          66 |       87000 | ready    |           2 |        2 | master    |        1 | slave     |           0 |

**Comment by huchaogithup** [comment]
vrgoup出现unsync 长时间不能自己恢复 有命令手动恢复吗
