### ISSUE TITLE
java.sql.SQLException: ERROR (8000000b): Unable to establish connection

### ISSUE THREAD

**Issue by moziie** [taosdata/TDengine#5191]
环境信息：java跑测试插入数据，多线程插入10000个点的数据；版本2.0.14，服务端Linux centos7 1核2G，window10跑java程序
现象：程序跑起来5~10分钟，报错java.sql.SQLException: ERROR (8000000b): Unable to establish connection，此时去服务端查看TDengine状态，systemctl status taosd，发现服务自己停了
附上demo程序（java）以及客户端服务端日志（由于日志文件太多无法上传，如您看到这个问题望提供邮箱）
private static Connection connection = null;
    private ThreadPoolExecutor threadPoolExecutor;
    private static String prefixDb="000000";

    public static String formatTimeStamp(Date date) {
        return new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS").format(date);
    }

    public Float getMyRandom(Integer n,Integer m){
        double big = Math.random() * (m - n) + n;
        BigDecimal bd = new BigDecimal(big);
        return bd.setScale(3, BigDecimal.ROUND_HALF_UP).floatValue();
    }

    public void createTable() throws SQLException {

        threadPoolExecutor = new ThreadPoolExecutor(128,512,10, TimeUnit.SECONDS,
                new LinkedBlockingQueue<>(100000),new ThreadPoolExecutor.CallerRunsPolicy());
        try {
            if (connection == null){
                HikariConfig config = new HikariConfig();
                config.setJdbcUrl("jdbc:TAOS://fw_24_ll:6030/fanwu");
                config.setDriverClassName("com.taosdata.jdbc.TSDBDriver");
                config.setUsername("root");
                config.setPassword("taosdata");
                config.setMinimumIdle(3);
                config.setMaximumPoolSize(10);
                config.setConnectionTimeout(10000);
                config.setIdleTimeout(60000);
                config.setValidationTimeout(3000);
                HikariDataSource ds = new HikariDataSource(config);
                connection = ds.getConnection();
            }
            Integer total = 10000;
            int count = 1000;
            for (int i = 0; i < total/count; i++) {
                int ii = i;
                threadPoolExecutor.execute(() ->{
                    for (int j = ii*count+1; j <= (ii+1)*count; j++) {
                        Statement statement = null;
                        try {
                            statement = connection.createStatement();
                        } catch (SQLException throwables) {
                            throwables.printStackTrace();
                        }
                        String electricMeterid = j < 10 ? prefixDb+"00000"+j:prefixDb+"0000"+j;
                        if (j > 99 && j< 1000){
                            electricMeterid = prefixDb+"000"+j;
                        }
                        if (j > 999 && j<10000) {
                            electricMeterid = prefixDb+"00"+j;
                        }
                        if (j>9999 && j<100000){
                            electricMeterid = prefixDb+"0"+j;
                        }
                        if (j>100000){
                            electricMeterid = prefixDb+""+j;
                        }
                        StringBuffer sql = new StringBuffer("insert into ");
                        String myRawvalue = "{\n" +
                                "\t\"ts\": \""+formatTimeStamp(new Date())+"\",\n" +
                                "\t\"positiveEnergy\": \""+100000+"\",\n" +
                                "\t\"activeEnergy\": \""+1000000+"\",\n" +
                                "\t\"activePower\": \""+getMyRandom(5000,6000)+"\",\n" +
                                "\t\"activePowerA\": \""+getMyRandom(1600,2000)+"\",\n" +
                                "\t\"activePowerB\": \""+getMyRandom(1600,2000)+"\",\n" +
                                "\t\"activePowerC\": \""+getMyRandom(1600,2000)+"\",\n" +
                                "\t\"positivePower\": \""+getMyRandom(600,700)+"\",\n" +
                                "\t\"positivePowerA\": \""+getMyRandom(200,230)+"\",\n" +
                                "\t\"positivePowerB\": \""+getMyRandom(200,230)+"\",\n" +
                                "\t\"positivePowerC\": \""+getMyRandom(200,230)+"\",\n" +
                                "\t\"powerFactor\": \""+getMyRandom(480,510)+"\",\n" +
                                "\t\"powerFactorA\": \""+getMyRandom(480,510)+"\",\n" +
                                "\t\"powerFactorB\": \""+getMyRandom(480,510)+"\",\n" +
                                "\t\"powerFactorC\": \""+getMyRandom(480,510)+"\",\n" +
                                "\t\"voltageA\": \""+getMyRandom(2180,2210)+"\",\n" +
                                "\t\"voltageB\": \""+getMyRandom(2190,2220)+"\",\n" +
                                "\t\"voltageC\": \""+getMyRandom(2180,2220)+"\",\n" +
                                "\t\"currentA\": \""+getMyRandom(2100,3100)+"\",\n" +
                                "\t\"currentB\": \""+getMyRandom(1900,2900)+"\",\n" +
                                "\t\"currentC\": \""+getMyRandom(2100,2900)+"\",\n" +
                                "\t\"hCurrentA\": \""+getMyRandom(1000,1600)+"\",\n" +
                                "\t\"hCurrentB\": \""+getMyRandom(1000,1600)+"\",\n" +
                                "\t\"hCurrentC\": \""+getMyRandom(1000,1600)+"\",\n" +
                                "\t\"hVoltageA\": \""+getMyRandom(150,300)+"\",\n" +
                                "\t\"hVoltageB\": \""+getMyRandom(150,300)+"\",\n" +
                                "\t\"hVoltageC\": \""+getMyRandom(150,300)+"\",\n" +
                                "\t\"hPositivePower\": \""+getMyRandom(180,360)+"\",\n" +
                                "\t\"hPositivePowerA\": \""+getMyRandom(60,120)+"\",\n" +
                                "\t\"hPositivePowerB\": \""+getMyRandom(60,120)+"\",\n" +
                                "\t\"hPositivePowerC\": \""+getMyRandom(60,120)+"\",\n" +
                                "\t\"hActivePower\": \""+getMyRandom(235,613)+"\",\n" +
                                "\t\"hActivePowerB\": \""+getMyRandom(100,200)+"\",\n" +
                                "\t\"hActivePowerA\": \""+getMyRandom(100,210)+"\",\n" +
                                "\t\"hActivePowerC\": \""+getMyRandom(100,210)+"\",\n" +
                                "\t\"angleAtoB\": \""+getMyRandom(1195,1213)+"\",\n" +
                                "\t\"angleAtoC\": \""+getMyRandom(2386,2414)+"\",\n" +
                                "\t\"angleBtoC\": \""+getMyRandom(1195,1213)+"\"\n" +
                                "}";
                        EngineData engineData = JSON.parseObject(org.apache.commons.lang3.StringEscapeUtils.unescapeJava(myRawvalue), EngineData.class);
                        //拼接sql
                        sql.append("ae").append(electricMeterid).append(" values ").append("('")
                                .append(engineData.getTs()).append("'").append(",")
                                .append(engineData.getActiveEnergy()).append(") ")
                                .append("pe").append(electricMeterid).append(" values ").append("('")
                                .append(engineData.getTs()).append("'").append(",")
                                .append(engineData.getPositiveEnergy()).append(") ")
                                .append("ac").append(electricMeterid).append(" values ").append("('")
                                .append(engineData.getTs()).append("'").append(",")
                                .append(engineData.getActivePower()).append(",")
                                .append(engineData.getActivePowerA()).append(",")
                                .append(engineData.getActivePowerB()).append(",")
                                .append(engineData.getActivePowerC()).append(") ")
                                .append("po").append(electricMeterid).append(" values ").append("('")
                                .append(engineData.getTs()).append("'").append(",")
                                .append(engineData.getPositivePower()).append(",")
                                .append(engineData.getPositivePowerA()).append(",")
                                .append(engineData.getPositivePowerB()).append(",")
                                .append(engineData.getPositivePowerC()).append(") ")
                                .append("cu").append(electricMeterid).append(" values ").append("('")
                                .append(engineData.getTs()).append("'").append(",")
                                .append(engineData.getCurrentA()).append(",")
                                .append(engineData.getCurrentB()).append(",")
                                .append(engineData.getCurrentC()).append(") ")
                                .append("vo").append(electricMeterid).append(" values ").append("('")
                                .append(engineData.getTs()).append("'").append(",")
                                .append(engineData.getVoltageA()).append(",")
                                .append(engineData.getVoltageB()).append(",").append(engineData.getVoltageC())
                                .append(") ")
                                .append("pf").append(electricMeterid).append(" values ").append("('")
                                .append(engineData.getTs()).append("'").append(",")
                                .append(engineData.getPowerFactor()).append(",")
                                .append(engineData.getPowerFactorA()).append(",")
                                .append(engineData.getPowerFactorB()).append(",")
                                .append(engineData.getPowerFactorC()).append(") ")
                                .append("hc").append(electricMeterid).append(" values ").append("('")
                                .append(engineData.getTs()).append("'").append(",")
                                .append(engineData.getHCurrentA()).append(",")
                                .append(engineData.getHCurrentB()).append(",")
                                .append(engineData.getHCurrentC()).append(") ")
                                .append("hv").append(electricMeterid).append(" values ").append("('")
                                .append(engineData.getTs()).append("'").append(",")
                                .append(engineData.getHVoltageA()).append(",")
                                .append(engineData.getHVoltageB()).append(",").append(engineData.getHVoltageC())
                                .append(") ")
                                .append("ha").append(electricMeterid).append(" values ").append("('")
                                .append(engineData.getTs()).append("'").append(",")
                                .append(engineData.getHActivePower()).append(",")
                                .append(engineData.getHActivePowerA()).append(",")
                                .append(engineData.getHActivePowerB()).append(",")
                                .append(engineData.getHActivePowerC()).append(") ")
                                .append("hp").append(electricMeterid).append(" values ").append("('")
                                .append(engineData.getTs()).append("'").append(",")
                                .append(engineData.getHPositivePower()).append(",")
                                .append(engineData.getHPositivePowerA()).append(",")
                                .append(engineData.getHPositivePowerB()).append(",")
                                .append(engineData.getHPositivePowerC()).append(") ")
                                .append("an").append(electricMeterid).append(" values ").append("('")
                                .append(engineData.getTs()).append("'").append(",")
                                .append(engineData.getAngleAtoB()).append(",")
                                .append(engineData.getAngleBtoC()).append(",")
                                .append(engineData.getAngleAtoC()).append(") ");
                        try {
                            boolean execute = statement.execute(sql.toString());
                            statement.close();
                        } catch (Exception e) {
                            e.printStackTrace();
                            log.error(">>>>>>>ERROR:错误表号-->>"+electricMeterid);
                        }
                    }
                });
            }
        }catch (Exception e){
            e.printStackTrace();
            if (connection !=null && !connection.isClosed()){
                connection.close();
            }
        }
}
测试程序跑的时候，服务端cpu占用6%左右，内存占用60%左右

**Comment by Shawshank-Smile** [comment]
一般是开的线程过多，句柄耗尽导致。可以检查一下。

**Comment by moziie** [comment]
> 一般是开的线程过多，句柄耗尽导致。可以检查一下。

请问插入数据时，推荐开多少个线程可以效率最高而又不会出现这种情况

**Comment by Shawshank-Smile** [comment]
Depending on the machine resources, your machine is 1-core. The problem is that the handle is exhausted, which is not directly related to tdengine.
Your question is quite another one. The number of threads can be adjusted by CPU and memory utilization.
