### ISSUE TITLE
systemctl start taosd ERROR

### ISSUE THREAD

**Issue by chevinlin** [taosdata/TDengine#5197]
systemctl status taosd.service

● taosd.service
   Loaded: error (Reason: Invalid argument)
   Active: inactive (dead)

Feb 15 17:37:39 izuf67fphe0t1amep6if56z systemd[1]: taosd.service lacks both ExecStart= and ExecStop= setting. Refusing.
Feb 15 17:37:46 izuf67fphe0t1amep6if56z systemd[1]: taosd.service lacks both ExecStart= and ExecStop= setting. Refusing.
Feb 15 17:45:51 izuf67fphe0t1amep6if56z systemd[1]: taosd.service lacks both ExecStart= and ExecStop= setting. Refusing.
Feb 15 17:46:35 izuf67fphe0t1amep6if56z systemd[1]: taosd.service lacks both ExecStart= and ExecStop= setting. Refusing.
Feb 15 17:48:59 izuf67fphe0t1amep6if56z systemd[1]: taosd.service lacks both ExecStart= and ExecStop= setting. Refusing.
Feb 15 17:58:23 izuf67fphe0t1amep6if56z systemd[1]: taosd.service lacks both ExecStart= and ExecStop= setting. Refusing.
Feb 15 17:58:25 izuf67fphe0t1amep6if56z systemd[1]: taosd.service lacks both ExecStart= and ExecStop= setting. Refusing.
Feb 15 17:58:47 izuf67fphe0t1amep6if56z systemd[1]: taosd.service lacks both ExecStart= and ExecStop= setting. Refusing.
Feb 15 17:59:23 izuf67fphe0t1amep6if56z systemd[1]: taosd.service lacks both ExecStart= and ExecStop= setting. Refusing.
Feb 15 17:59:31 izuf67fphe0t1amep6if56z systemd[1]: taosd.service lacks both ExecStart= and ExecStop= setting. Refusing.

**Comment by Shawshank-Smile** [comment]
需要使用root的权限安装，如果还有问题，我来远程看看。

**Comment by tigerhu2008** [comment]
这个问题还没有解决。版本v1.6.6.0，v2.4.0.0都试过。OS版本CentOS Linux release 8.4.2105.
taosd.service文件是空的。
