### ISSUE TITLE
求支持Nodejs connectors

### ISSUE THREAD

**Issue by wucangeo** [taosdata/TDengine#52]
希望社区版能够支持Nodejs开发。

**Comment by StoneT2000** [comment]
Work is being done on it, but no guarantee at the moment

**Comment by jhyvictory** [comment]
通过mysql connector能连接td吗？

**Comment by StoneT2000** [comment]
你说的是 mysql 的 NodeJS connector 吗?

**Comment by StoneT2000** [comment]
Hi @wucangeo 
刚刚加了 Node.js connector
请看这个：https://github.com/taosdata/tdengine/tree/master/src/connector/nodejs
文档：https://www.taosdata.com/en/documentation/connector/#Node.js-Connector

**Comment by wucangeo** [comment]
效率太高了！点赞！

> Hi @wucangeo
> 刚刚加了 Node.js connector
> 请看这个：https://github.com/taosdata/tdengine/tree/master/src/connector/nodejs
> 文档：https://www.taosdata.com/en/documentation/connector/#Node.js-Connector
> Node.js connector的文档暂时没有中文版
