### ISSUE TITLE
how to count the number of tables not the number of data from stables

### ISSUE THREAD

**Issue by kidari** [taosdata/TDengine#520]
i can get the table's name by using (group by) from stables, get number of data by using (count(*)) .But i can't get the number of tables from stables.

**Comment by fangpanpan** [comment]
you can find "ntables" from the sql command "show databases". "ntables" tells you the number of tables in this databases; 
sql command "show stables" will tell you the number of tables belonging to this stable.

**Comment by hjxilinx** [comment]
>select count(tbname) from a_super_table_name.

The above SQL get the number of tables that are created according to  the "a_super_table_name"

> select tbname from a_super_table_name.

The above SQL show all tables that are create according to the super table with the name of "a_super_table_name"

NOTE:
"tbname" is a keyword in TDengine.
"a_super_table_name" is the super table that user specified.
