### ISSUE TITLE
2.0.16.0 rpm 依赖检测失败，需要python3

### ISSUE THREAD

**Issue by OrangeEffects** [taosdata/TDengine#5200]
**General Questions**

安装包 TDengine-server-2.0.16.0-Linux-x64.rpm
centOS 7

错误：依赖检测失败：
        /usr/bin/python3 被 tdengine-2.0.16.0-3.x86_64 需要

说好的“不依赖任何第三方软件”？

**Comment by dullduck** [comment]
遇到同样的问题。即使生成文件/usr/bin/python3，安装rpm包还是会报这个错误。

**Comment by sangshuduo** [comment]
这是因为 rpm 打包时自动检测到包含的 Python3 示例程序，而添加的依赖。可以使用 rpm -ivh --nodeps 命令安装。另外也可以使用 tar.gz 格式安装包。

**Comment by sangshuduo** [comment]
这是因为 rpm 打包时自动检测到包含的 Python3 示例程序，而添加的依赖。可以使用 rpm -ivh --nodeps 命令安装。另外也可以使用 tar.gz 格式安装包。

**Comment by dullduck** [comment]
tar.gz包可以安装，参照这里：https://www.taosdata.com/blog/2019/08/09/566.html

**Comment by OrangeEffects** [comment]
well

**Comment by sangshuduo** [comment]
谢谢指出这个问题。下一个版本会去掉这个依赖，用普通的 rpm 安装命令就可以安装。
