### ISSUE TITLE
Cluster question

### ISSUE THREAD

**Issue by killhurry** [taosdata/TDengine#5203]
If the cluster exceeds 3 nodes, the cluster cannot be connected if both nodes configured by Firstep and Secondep are down.

**Comment by Shawshank-Smile** [comment]
Only the first time, Firstep or Secondep is used. Cluster information will be cached in the client.
Further more， if the first time "Firstep and Secondep are down", DBA must show up for check.

**Comment by killhurry** [comment]
ok,thansk!
