### ISSUE TITLE
python 导出数据到csv异常

### ISSUE THREAD

**Issue by Lao-Zhong** [taosdata/TDengine#5210]
cursor.execute(‘SELECT * FROM bohai.g52253075400 >> /data/tests/tables/g52253075400.csv;’）执行失败，但是在终端上执行是正产的，请问这是什么原因？
![112](https://user-images.githubusercontent.com/39207755/108333943-6a170680-720c-11eb-86fa-e5f4e8a382c6.png)

cursor.execute(‘SELECT * FROM bohai.g52253075400;’）执行是正常的

**Comment by sangshuduo** [comment]
这不是 bug。

并不是所有 taos shell 里可以执行的命令在 python 连接器里都可以执行，python 连接器不是调 taos shell，而且更底层的接口。
