### ISSUE TITLE
Aggregate query super table, calculation result error

### ISSUE THREAD

**Issue by zhangzhenguo100865** [taosdata/TDengine#5217]
写入操作已经停止，三次的count查询结果都不一致
![image](https://user-images.githubusercontent.com/31802798/108458843-6b9a0a80-72b0-11eb-916b-292cadde4a57.png)
![image](https://user-images.githubusercontent.com/31802798/108459711-2a0a5f00-72b2-11eb-83cb-daeae75589f7.png)

**Comment by zhangzhenguo100865** [comment]
第三次的查询结果数量比第二次还要小

**Comment by Shawshank-Smile** [comment]
Please upgrade to the latest version. If you have any questions, please add my wechat.

**Comment by zhangzhenguo100865** [comment]
![image](https://user-images.githubusercontent.com/31802798/108496457-06acd780-72e5-11eb-9f0c-2bc0d522adac.png)
更新到最新版本还是有这个问题

**Comment by guanshengliang** [comment]
As of version 2.2, this problem has been alleviated. You can also look forward to the 3.0 version in the second half of the year. The synchronization module has been refactored using the raft algorithm
