### ISSUE TITLE
failed to connect to server

### ISSUE THREAD

**Issue by cjjcode** [taosdata/TDengine#522]
版本1.6.1.7，sql在服务端执行ok,但是在客户端执行，报错TDengine Error: failed to connect to server。当我减少一些字段执行是ok的。上次有说长度小于64kb,所以，我想知道是哪里有超时配置或者其他配置？？我用的默认配置，没有修改过，此问题不是随机的，可以复现。
CREATE TABLE IF NOT EXISTS futures(lastUpdateTime TIMESTAMP, mdStreamID BINARY(4),securityID BINARY(20), fixDTradingStatus BINARY(10), lastPx BINARY(20), highPx BINARY(20), lowPx BINARY(20), avgPx BINARY(20), openInterest BINARY(20), totalVolumeTraded BINARY(20), totalValueTraded BINARY(20), mdEntryPxB1 BINARY(20), mdEntrySizeB1 BINARY(20), mdEntryPositionNoB1 BINARY(20), mdEntryPxB2 BINARY(20), mdEntrySizeB2 BINARY(20), mdEntryPositionNoB2 BINARY(20), mdEntryPxB3 BINARY(20), mdEntrySizeB3 BINARY(20), mdEntryPositionNoB3 BINARY(20), mdEntryPxB4 BINARY(20), mdEntrySizeB4 BINARY(20), mdEntryPositionNoB4 BINARY(20), mdEntryPxB5 BINARY(20), mdEntrySizeB5 BINARY(20), mdEntryPositionNoB5 BINARY(20), mdEntryPxS1 BINARY(20), mdEntrySizeS1 BINARY(20), mdEntryPositionNoS1 BINARY(20), mdEntryPxS2 BINARY(20), mdEntrySizeS2 BINARY(20), mdEntryPositionNoS2 BINARY(20), mdEntryPxS3 BINARY(20), mdEntrySizeS3 BINARY(20), mdEntryPositionNoS3 BINARY(20), mdEntryPxS4 BINARY(20), mdEntrySizeS4 BINARY(20), mdEntryPositionNoS4 BINARY(20), mdEntryPxS5 BINARY(20), mdEntrySizeS5 BINARY(20), mdEntryPositionNoS5 BINARY(20), exchange BINARY(20))TAGS(market  BINARY(20),symbol BINARY(20))；

**Comment by guanshengliang** [comment]
I don' understand what you said about the client side and server side.
the error info
`TDengine Error: failed to connect to server`
May be a network problem

**Comment by guanshengliang** [comment]
If you are accessing Linux services from Windows client, you can pay attention to the firewall.

**Comment by cjjcode** [comment]
> I don' understand what you said about the client side and server side.
> the error info
> `TDengine Error: failed to connect to server`
> May be a network problem



> If you are accessing Linux services from Windows client, you can pay attention to the firewall.

如你所说，我正是从windows client 访问Linux service .
首先，windows client执行sql是成功的。所以应该不是防火墙问题。
然后，同样的sql,当我减少sql长度（如上建表sql减少一些字段），是执行成功的。

**Comment by cjjcode** [comment]
> > I don' understand what you said about the client side and server side.
> > the error info
> > `TDengine Error: failed to connect to server`
> > May be a network problem
> 
> > If you are accessing Linux services from Windows client, you can pay attention to the firewall.
> 
> 如你所说，我正是从windows client 访问Linux service .
> 首先，windows client执行sql是成功的。所以应该不是防火墙问题。
> 然后，同样的sql,当我减少sql长度（如上建表sql减少一些字段），是执行成功的。

windows client 执行的是java程序，在examples>JDBCDemo中替换sql,没有修改任何配置

**Comment by guanshengliang** [comment]
Add my wechat `geiseil`, to solve this problem

**Comment by alon-zhong** [comment]
这个问题我们也经常碰到。用客户端（无论是.net 或 java）连接TD，执行一条查询语句，结果行数一多就报“failed to connect to server”，加上约束减少结果行数就ok，把出问题的语句复制到TD服务器，在shell下执行也完全没问题

**Comment by guanshengliang** [comment]
You can add my WeChat `geiseil`  to solve this problem.
But the premise is that, you can reproduce the problem, and provide a way to access you remote machine.
