### ISSUE TITLE
support  distinct + group by  

### ISSUE THREAD

**Issue by xujiesh0510** [taosdata/TDengine#5223]
distinct 功能目前有点弱， 试了下 group by 后 再 distinct  会报错

 select distinct devicename from svariables  group by tenantid;

 invalid SQL: retrieve tags not compatible with group by or interval query

能增强下 distinct 功能么？支持group by ，后续可以支持到 包括 非 tag 字段

**Comment by hjxilinx** [comment]
The requried feature has been supported in TDengine.
