### ISSUE TITLE
recover data

### ISSUE THREAD

**Issue by kaiyangyang** [taosdata/TDengine#5225]
在1.6.x与2.0.14.0 docker版本(已将/var/lib/taos挂载出来)，现需要将数据迁移到另外一台机器上去，如何迁移呢

**Comment by kaiyangyang** [comment]
我发现在docker版的2.0.14.0(其他版本没有试)，把/var/lib/taos目录下的文件(除了dnode)替换为迁移的文件，然后修改dnode中的dnodeCfg.json的clusterId为迁移数据的clusterId其他不变，重启docker后，原先的数据库与数据表中的数据都有，不知道这样迁移会不会有什么问题(光看数据库和数据表中的数据是没有问题)

**Comment by Shawshank-Smile** [comment]
no problem

**Comment by ohhhyuan** [comment]
我想问下，你是直接把datadir目录映射到容器里了吗，我也是这样操作的，但是容器TD查不到数据
