### ISSUE TITLE
TSDB error: too many sessions on server导致无法使用

### ISSUE THREAD

**Issue by AlexForMRD** [taosdata/TDengine#523]
我之前使用的是1.6.1.7版本, 然后程序每次都创建连接, 关闭连接这个没有问题, 后来我升级到1.6.2.0版本后发现后台报了大量的错误如下: 
![image](https://user-images.githubusercontent.com/53466568/65105069-4ee80c00-da06-11e9-9ddf-eb5f239a9b0d.png)

导致TDengine无法使用, 然后我到Linux服务器上重启了TDengine, 在服务器上使用taos命令还是一样的无法进入. 如下显示:
![image](https://user-images.githubusercontent.com/53466568/65105117-763ed900-da06-11e9-9969-e16ff335d031.png)

**Comment by guanshengliang** [comment]
Add my wechat `geiseil`, to solve this problem

**Comment by AlexForMRD** [comment]
> Add my wechat `geiseil`, to solve this problem

你们的同事已经给我解决了, 谢谢!

**Comment by guanshengliang** [comment]
Ok, that's great.
