### ISSUE TITLE
Modify DataX to support TDengine 

### ISSUE THREAD

**Issue by wgzhao** [taosdata/TDengine#5233]
DataX 是阿里开源的一款通用数据库采集工具，我[fork该项目](https://github.com/wgzhao/datax)并做了大量更新，最近也增加了对 TDengine 数据库的支持，包括数据写入和数据读取

- 读取插件文档说明(<https://github.com/wgzhao/DataX/blob/master/docs/src/main/sphinx/reader/tdenginereader.md>)
- 写入插件文档说明(<https://github.com/wgzhao/DataX/blob/master/docs/src/main/sphinx/writer/tdenginewriter.md>)

祝 TDengine 越来越好

**Comment by Shawshank-Smile** [comment]
可以加我们其他同事，或者我的微信：13720014098。这样我们可以一起进行测试，以及其他方面的合作。

**Comment by cpvmrd** [comment]
Thank you for your contribution.

**Comment by fenghuazzm** [comment]
Thank you for contribution！
Today TDengine is getting better and better.
