### ISSUE TITLE
query the data in the super table and remove the TBNAME in the where restriction, the query results will be less

### ISSUE THREAD

**Issue by deuxmille** [taosdata/TDengine#5234]
taos> select tbname,* from stable_tick where tbname like 'ag2106' and action_timestamp_>'2021-02-09 20:00:00' and action_timestamp_<'2021-02-10 20:00:00' and trading_date_=20210210 >> /dev/null;
Query OK, 43323 row(s) in set (0.574407s)

taos> select tbname,* from stable_tick where tbname like 'SH600519' and action_timestamp_>'2021-02-09 20:00:00' and action_timestamp_<'2021-02-10 20:00:00' and trading_date_=20210210 >> /dev/null;
Query OK, 5042 row(s) in set (0.614521s)

taos> select tbname,* from stable_tick where action_timestamp_>'2021-02-09 20:00:00' and action_timestamp_<'2021-02-10 20:00:00' and trading_date_=20210210 >> /dev/null;
Query OK, 20877 row(s) in set (0.947138s)

第三句话想查询超级表中所有符合该时间区间的数据，查询结果太少了。

**Comment by Shawshank-Smile** [comment]
I need to know the table schema
