### ISSUE TITLE
DB error: Unable to establish connection (12.037000s)

### ISSUE THREAD

**Issue by wuyuexiaolong** [taosdata/TDengine#5237]
官网rpm文件安装在虚拟机，已开放6030-6041端口。

win10客户端连接。
问题：可以查询数据库名，表名，但是查询表的数据会出现错误。
           使用idea连接也是一样的情况。

详细情况：

C:\TDengine>taos -h 192.168.65.128

Welcome to the TDengine shell from Linux, Client Version:2.0.16.0
Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.

taos> use test;
Query OK, 0 row(s) affected (0.001000s)

taos> select * from t1 limit 10;

DB error: Unable to establish connection (12.034000s)
taos>

**Comment by wuyuexiaolong** [comment]
卸载了很多次数据库后问题发生了变化，
taos> use demo;
Query OK, 0 row(s) affected (0.001000s)

taos> show tables;
           table_name           |      created_time       | columns |          stable_name           |          uid          |     tid     |    vgId     |
==========================================================================================================================================================
 t                              | 2021-02-22 15:50:30.242 |       2 |                                |       844424946914185 |           1 |           3 |
Query OK, 1 row(s) in set (0.016000s)

taos> select * from t;

DB error: Unable to resolve FQDN (0.003000s)
taos>

**Comment by Shawshank-Smile** [comment]
Read the FAQ for more info
