### ISSUE TITLE
Can I get the count of tables from stable with some requirements？

### ISSUE THREAD

**Issue by kidari** [taosdata/TDengine#524]
such as:get the number of tables ,their last_row (ts>now-1d).

**Comment by guanshengliang** [comment]
I don't fully understand your question.
The number of tables in the super table can be obtained by the following SQL statement.

![image](https://user-images.githubusercontent.com/28882257/65134383-cafa4800-da36-11e9-924b-77c7b86cb06e.png)

**Comment by kidari** [comment]
How to get the number of tables that their last_row's time is later than now-1d? from a super table

**Comment by guanshengliang** [comment]
This feature is not yet supported and will be implemented in about 2 months.

**Comment by guanshengliang** [comment]
@hjxilinx  Is this job planned？
