### ISSUE TITLE
arm32 Taosd free space detection error

### ISSUE THREAD

**Issue by Tommua** [taosdata/TDengine#5242]
错误信息：ERROR free disk size: 0.213924 GB, too little, quit
描述：taosd检测空间大小时，tasod程序把已用空间当成了空闲空间，一开始开发板只使用了200M多的空间，log一直打印空闲空间只有200M,程序直接退出，当拷贝了1个G的大文件到开发板之后在运行，taosd服务才启动起来

**Comment by stephenkgu** [comment]
develop 分支已修复，本周的 2.0.17.0 版本会包含这个修复。
