### ISSUE TITLE
arm32 taosd：An exception is reported after the service is successfully started

### ISSUE THREAD

**Issue by Tommua** [taosdata/TDengine#5243]
taosd程序在开发板上运行后始终会出现等一会就挂了，异常信息如下：
Alignment trap: not handling instruction edc37a00 at [<76c65456>]
Unhandled fault: alignment exception (0x801) at 0x7507a3e6
pgd = 8b94c000
[7507a3e6] *pgd=8a546831, *pte=83f0e75f, *ppte=83f0ec7f
![mmexport1613993844532](https://user-images.githubusercontent.com/51266286/108703337-6f928a80-7545-11eb-8254-7851fc7e27c2.png)

**Comment by plum-lihui** [comment]
这个应该地址没有对齐的错误引起的，请取最新的版本测试吧。
