### ISSUE TITLE
TDengine restful Connector,insert data error

### ISSUE THREAD

**Issue by moziie** [taosdata/TDengine#5254]
environments:
linux:centos7 三节点集群,cpu:8,ARM:16G
使用emqx broker创建规则引擎通过restful Connector连接tdengine批量插入数据时报错，数据未插入成功
下面截取的一段日志:
import into 'test.cu000000003941' (ts,currentA,currentB,currentC) values (now,2397.837,2664.855,2283.288);POST /rest/sql HTTP/1.1
content-length: 76
host: 192.168.1.9:6041
content-type: application/json
Authorization: Basic cm9vdDp0YW9zZGF0YQ==

import into 'test.pe000000007480' (ts,positiveEnergy) values (now,10000.0);POST /rest/sql HTTP/1.1
content-length: 76
host: 192.168.1.9:6041
content-type: application/json
Authorization: Basic cm9vdDp0YW9zZGF0YQ==

import into 'test.pe000000001504' (ts,positiveEnergy) values (now,10000.0);POST /rest/sql HTTP/1.1
content-length: 76
host: 192.168.1.9:6041
content-type: application/json
Authorization: Basic cm9vdD
02/23 16:40:22.026424 0x7f9713b22700 HTP ERROR context:0x7f9448629e80, fd:1078, parse failed, ret:-1 code:-2147479246 close connect
02/23 16:40:22.026438 0x7f9713b22700 HTP ERROR context:0x7f9448629e80, fd:1078, code:507, error:failed to parse end section
02/23 16:40:22.026494 0x7f9713b22700 HTP ERROR context:0x7f9448629e80, is already released, refCount:-1
02/23 16:40:22.026543 0x7f9713b22700 HTP ERROR context:0x7f944862a560, fd:1080, parser state:14, unexpected char:[P]50
02/23 16:40:22.026595 0x7f9713b22700 HTP ERROR context:0x7f944862a560, fd:1080, parse failed, httpCode:507 parseCode:4402 reason:failed to parse end section
02/23 16:40:22.026616 0x7f9713b22700 HTP ERROR context:0x7f944862a560, fd:1080, failed to parse, state:14
02/23 16:40:22.026627 0x7f9713b22700 HTP ERROR context:0x7f944862a560, fd:1080, parse failed, ret:-1 i:222 len:3825 buf:POST /rest/sql HTTP/1.1
content-length: 76
host: 192.168.1.9:6041
content-type: application/json
Authorization: Basic cm9vdDp0YW9zZGF0YQ==

import into 'test.pe000000005463' (ts,positiveEnergy) values (now,10000.0);POST /rest/sql HTTP/1.1
content-length: 144
host: 192.168.1.9:6041
content-type: application/json
Authorization: Basic cm9vdDp0YW9zZGF0YQ==

import into 'test.po000000004778' (ts,positivePower,positivePowerA,positivePowerB,positivePowerC) values (now,606.626,221.639,228.362,206.121);POST /rest/sql HTTP/1.1
content-length: 76
host: 192.168.1.9:6041
content-type: application/json
Authorization: Basic cm9vdDp0YW9zZGF0YQ==

import into 'test.pe000000003105' (ts,positiveEnergy) values (now,10000.0);POST /rest/sql HTTP/1.1
content-length: 76
host: 192.168.1.9:6041
content-type: applicat
02/23 16:40:22.026661 0x7f9713b22700 HTP ERROR context:0x7f944862a560, fd:1080, parse failed, ret:-1 code:-2147479246 close connect
02/23 16:40:22.026676 0x7f9713b22700 HTP ERROR context:0x7f944862a560, fd:1080, code:507, error:failed to parse end section
02/23 16:40:22.026744 0x7f9713b22700 HTP ERROR context:0x7f944862a560, is already released, refCount:-1
02/23 16:40:22.026853 0x7f9713b22700 HTP ERROR context:0x7f944862b320, fd:1082, parser state:14, unexpected char:[P]50
02/23 16:40:22.026918 0x7f9713b22700 HTP ERROR context:0x7f944862b320, fd:1082, parse failed, httpCode:507 parseCode:4402 reason:failed to parse end section
02/23 16:40:22.026941 0x7f9713b22700 HTP ERROR context:0x7f944862b320, fd:1082, failed to parse, state:14
02/23 16:40:22.026952 0x7f9713b22700 HTP ERROR context:0x7f944862b320, fd:1082, parse failed, ret:-1 i:222 len:4096 buf:POST /rest/sql HTTP/1.1
content-length: 76
host: 192.168.1.9:6041
content-type: application/json
**webhook配置**
![image](https://user-images.githubusercontent.com/70946068/108821186-2fd8ab00-75f8-11eb-953f-bc6306266011.png)

**Comment by HendSame** [comment]
import into ？

**Comment by moziie** [comment]
> import into ？

嗯官方文档中有说明，历史记录写入：可使用IMPORT或者INSERT命令，IMPORT的语法，功能与INSERT完全一样。

**Comment by fenghuazzm** [comment]
This issue was closed because it has been inactive for too many days.
