### ISSUE TITLE
 Does TDengine support connection pool like Druid?

### ISSUE THREAD

**Issue by AlexForMRD** [taosdata/TDengine#526]
先说说我的使用的场景:
1. 因为开源版本只有50个Vnode, 每个Vnode我设置为5000张表的话, 也才只能支持25w张表, 所以我在业务上做了分配, 比如预计有250w张表, 我分了10台机器去部署TDengine, 然后再业务上去判断我应该连哪台服务器上的TDengine, 我用了原生的JDBC方式写了10个工具类, 但是这样后台会报错:

![image](https://user-images.githubusercontent.com/53466568/65143231-069d0e00-da47-11e9-9597-36f93087427a.png)

所以我想问下: 如何支持连多个不同服务器上的数据库, 我多次Class.forName(TSDB_DRIVER); 这样会报错, 说在另一个程序里已经加载了.

**Comment by guanshengliang** [comment]
TDengine client does not support access to multiple machines in different clusters.
You can continue to increase the number of tables to 50000 or increase the configuration of the machine.
Or you can consider buying a cluster version to solve this problem.
