### ISSUE TITLE
python AttributeError: module 'taos' has no attribute 'connect'

### ISSUE THREAD

**Issue by god-pane** [taosdata/TDengine#5265]
**Bug Description**
- 在windows 本地安装了taos客户端，且配置好地址和端口，能通过cmd正常连接到taos服务端
- cd C:\TDengine\connector\python\windows   pip install python3\ 执行成功
- 编写代码如下
![image](https://user-images.githubusercontent.com/9427959/108968345-9c68ae00-76bb-11eb-81da-397e2dfc49ba.png)
- 运行后报错

**Environment (please complete the following information):**
 - OS: [e.g. win 10]
 - TDengine Version [e.g. 2.0.14.0]

**Comment by Shawshank-Smile** [comment]
使用的不是TDengine的taos，Python 本地库中也有一个其他软件的taos库

**Comment by hfcn123** [comment]
> 使用的不是TDengine的taos，Python 本地库中也有一个其他软件的taos库

看了文档也不知道官方的是哪个啊？正常应该引入哪个呢？
