### ISSUE TITLE
Insufficient /tmp directory space ： DB error: System out of disk space 

### ISSUE THREAD

**Issue by jadedrip** [taosdata/TDengine#5266]
TDengine 版本 2.0.15.0

客户端机器 /tmp 目录空间为 300M 左右
登录官方 taos 客户端，执行带 count(*) 或者 order by 的查询会报异常：

DB error: System out of disk space 

查看 /var/taos/taoslogX.X 文件，发现如下错误日志：

02/24 11:27:54.665049 0x7f4d027fc700 TSC ERROR 0x7f4cf0030d20 sub:0x7f4ce40072e0 client disk space remain 0.305 GB, need at least 1.000 GB, stop query

修改 /etc/taos.cfg 下的 tempDir 配置为其他盘，无效果

然后我联系运维把 /tmp 扩容到了 2G，问题消失

所以结论来了:
1. 目前版本客户端 /tmp 需要至少要有 1G 空间
2. taos.cfg 里的 tempDir 配置不影响客户端

官方以后是否会优化一下，为啥客户端还需要这么大磁盘的临时空间啊，我其实根本没这么多数据的。

**Comment by Shawshank-Smile** [comment]
Thanks for your advice

**Comment by arielyang** [comment]
This issue was closed because it has been inactive for too many days.
