### ISSUE TITLE
How can I create a new son table automatically ?

### ISSUE THREAD

**Issue by sexbee** [taosdata/TDengine#527]
"...可使用自动建表语法来实现写入数据时里用超级表定义的表结构自动创建不存在的子表，若该表已存在则不会建立新表.." & "向表tb_name中插入一条或多条记录，如果tb_name这张表不存在，则会用超级表stb_name定义的表结构以及用户指定的标签值(即tag1_value…)来创建名为tb_name新表，并将用户指定的值写入表中。如果tb_name已经存在，则建表过程会被忽略..."

1.这里的“自动”做何解？是指写入数据时自动判断表如不存在则自动调用建表语句？因为建表语句不同，那么如何确定是引用哪一句或者说是哪一个超表的建表语句？
2.同一张表，插入数据时间戳可以指定，但是会自动判断不能早于上一条时间戳，否则忽略，即不能中间插一条进去？

**Comment by fangpanpan** [comment]
1. 自动建表指的是当表不存在时也可以用超级表来插入数据。 "insert into tb_name using stb_name values () tags()". 在插入数据的时候如tb_name 不存在会建一个表叫tb_name。表的schema由超级表stb_name定。
2. 如果想中间插，可以用import 命令。
