### ISSUE TITLE
Version: 2.0.16 Super table has several million sub-tables, one table for each device, and the total number of records is 40 billion. taos suspended animation

### ISSUE THREAD

**Issue by sj-dev** [taosdata/TDengine#5271]
版本：2.0.16
超级表 的子表有一百万个，每一个设备一个表，记录数之和400亿。
select last(*) from testdb.tb_net_meter_data group by did。
多个客户端执行这一个后，taos处理假死状态，也无法再查询数据了，也无法查询中止耗时较大的语句。

1、建议提供正在执行语句查询与终止功能。
2、设置超时时间，SqL执行时间超过指定时间，自动终止，防止taos整体假死。

**Comment by Shawshank-Smile** [comment]
Please upgrade to the latest version and use last_row(*)
