### ISSUE TITLE
About the use of TDEngine's Tag

### ISSUE THREAD

**Issue by deltacat** [taosdata/TDengine#5273]
这是个关于最佳实践的问题。不确定是否合适在此提出。

先介绍下背景：
我们在做物联网相关研发，一年多之前在时序数据选型做了些调查，最终从 TDEngine、Dolphin、OpenTSDB、Influxdb…… 等备选中选择了 InfluxDB。但是随着业务量的增长，InfluxDB 在使用中也遇到了性能瓶颈，一方面我们在尝试基于 InfluxDB 进行二次开发提升或规避性能和容量问题，另一方面也在重新考量成熟产品更换的可能。于是视线回到当初本该是首选的 TDEngine。

在这个过程中我们发现一个问题：TDEngine和InfluxDB都有 Tag 的使用，并且都是为了加快查询速度。在我的理解中，二者很多地方设计思路有相似之处比如，DB -> DB, STable -> measurment, Table -> series。
但是 tag 有巨大的差别，在我看来，TDEngine 的 Table 是面向设备，而 InfluxDB 的 Series 是面向时间和数据点，同一个设备的数据，可以通过不同tagvalue的组合分为若干series。这导致如果同一个设备的数据有不同的类型，在同一个超级表中无法实现，除非子表的ID通过类似tag的组合来命名。

这样面临的问题是，100万终端设备，由于存在不同的tag ，最终 series 数量轻松突破亿级。这在需要对不同终端聚合统计时性能问题很大。
回到 TDEngine，似乎要满足上述要求，就需要同等级别的子表。一方面违背了文档中的设计，另一方面也存在类似的性能问题。同时，每个子表在逻辑存储上是独立文件，多表查询应该会收到打开文件数量的限制。

由于没能在官网文档中找到相关的说明，因而在此提问看看是否有已知案例或建议。另一方面我们也会继续尝试试验以及查阅源码。

**Comment by Shawshank-Smile** [comment]
What are your core views and needs?

**Comment by deltacat** [comment]
> What are your core views and needs?

主要有两种用途：
一种是测量数据，这个基本上没什么问题，TDEngine的设计应该基本相符。
另一种是终端与服务的海量上下行通讯，当然包括测量的上报，这个跟具体业务无关，但是有相当多的tag用于数据分析。这里是问题所在。

**Comment by zuodengchao** [comment]
> > What are your core views and needs?
> 
> 主要有两种用途： 一种是测量数据，这个基本上没什么问题，TDEngine的设计应该基本相符。 另一种是终端与服务的海量上下行通讯，当然包括测量的上报，这个跟具体业务无关，但是有相当多的tag用于数据分析。这里是问题所在。

我也有相同的疑惑，当我查询的时候，把一些列放入到查询条件的时候，会增加查询的时间。尤其是字符串的列
