### ISSUE TITLE
 The database is deleted when there is still data on the hard disk. Too many vnode nodes

### ISSUE THREAD

**Issue by wuyuexiaolong** [taosdata/TDengine#5281]
版本 2.0.16
数据库里面除了一个log库，没啥了，为啥占用空间这么大？

而且就两个节点也没有那么多vnode，为啥存储目录里面却有好多个vnode文件夹？

![image](https://user-images.githubusercontent.com/56399420/109133175-af4cb280-778f-11eb-8a24-36405c875b09.png)

**Comment by Shawshank-Smile** [comment]
This is the data that was previously deleted, to prevent accidental deletion of the automatic backup, you can receive the deletion.
