### ISSUE TITLE
Table log.dn used disk data error 

### ISSUE THREAD

**Issue by zhangfeng114** [taosdata/TDengine#5283]
**Table log.dn used disk data error**

I upgraded from 2.0.11 to 2.0.16 version, this is the result of the current version 2.0.16 query ：
![1](https://user-images.githubusercontent.com/20456459/109241150-d056e700-7813-11eb-86e3-f2a922997102.png)

 result of  `df -h` query :
![2](https://user-images.githubusercontent.com/20456459/109241664-ace06c00-7814-11eb-98d9-963a223d09f9.png)

The data changes at the time of my upgrade are as follows ：
![3](https://user-images.githubusercontent.com/20456459/109241767-dbf6dd80-7814-11eb-9c26-fc70027073de.png)

**It can be seen that the data in version 11 is correct. What changes have you made?**

**Comment by yu285** [comment]
this display issue will be fixed in the next version.
Thank  you for your support of  TDengine.
