### ISSUE TITLE
void pointer when inserting large amount of data by multiple threads?

### ISSUE THREAD

**Issue by rainmaple** [taosdata/TDengine#529]
**Bug Description**
低版本如1.0.1的jdbcdriver在安装目录下的确有，在项目中也将本地的jar包安装部署成maven依赖，但是开发时会遇上版本不匹配的错误，有高版本的driver提供么,或者说这个支持不了简单的压力测试？

**Environment (please complete the following information):**
 - OS: [ CentOS 7]
 - Memory,current Disk Space enough
 - TDengine Version [1.6.1.7]

**Additional Context**
```
java.sql.SQLException: TDengine Error: version of client and server not match
        at com.taosdata.jdbc.TSDBJNIConnector.connect(TSDBJNIConnector.java:100)
        at com.taosdata.jdbc.TSDBConnection.connect(TSDBConnection.java:64)
        at com.taosdata.jdbc.TSDBConnection.<init>(TSDBConnection.java:56)15:03:29.226 
```

**Comment by guanshengliang** [comment]
This error has nothing to do with the stress test.
Jdbcdriver depends on libtaos.so, and libtaos.so needs to match server

**Comment by guanshengliang** [comment]
Your test code may not be on the same machine as the server
So you should update libtaos.so in the client machine with the same way

**Comment by rainmaple** [comment]
> Your test code may not be on the same machine as the server
> So you should update libtaos.so in the client machine with the same way

but my test code is on the same  machine as the server. but the problems is stills exisits

**Comment by guanshengliang** [comment]
You can add my WeChat `geiseil` to solve this problem.
The premise is that you can reproduce the problem on a public network server and allow me to log in via ssh.

**Comment by rainmaple** [comment]
i think you can test taosdb use our benchmark, code is here: https://github.com/rainmaple/tsbm. besides, maven pom  need to be added in your local to test.

**Comment by guanshengliang** [comment]
ok, we will arrange someone to try

**Comment by guanshengliang** [comment]
Jdbc can support mybatis now, you can download new version and try again
