### ISSUE TITLE
是否支持一分钟内插入千万级别的数据

### ISSUE THREAD

**Issue by moziie** [taosdata/TDengine#5290]
业务场景：1千万台电表设备，每分钟采集一次数据上传存储供后续分析处理使用。请问TDengine是否支持高频次的数据插入

**Comment by yu285** [comment]
您好，TDengine尤其适合高效处理海量（千万或者更多量级）的数据源，我们完全可以轻松处理分钟级别的插入频率。

具体部署欢迎联系我们，我们可以提供技术支持，本人微信：15652223354
