### ISSUE TITLE
 Single node TDengine ，why CPU consumption is so high？

### ISSUE THREAD

**Issue by liuyuinsdu** [taosdata/TDengine#5294]
![image](https://user-images.githubusercontent.com/4965941/109369748-83b3f000-7895-11eb-81ab-52dc9c556a86.png)
单点配置，为什么数据库占用CPU这么高？

**Comment by zhangfeng114** [comment]
你后台运行下`ps  -ef | grep taos`,看是不是有很多数据库连接没关？

**Comment by sangshuduo** [comment]
这个问题已经修复中

**Comment by sangshuduo** [comment]
Please try latest version TDengine. Feel free to reopen it if it still happens.
