### ISSUE TITLE
csv导入异常问题

### ISSUE THREAD

**Issue by XLPE** [taosdata/TDengine#53]
场景一（字段包含字符串）:
表结构:create table if not exists test_stat (its timestamp, name binary(40),succ_count int);
导入500万行记录，导入过程中出现:
data is already imported to file
decomp_size:-1, Error decompress in LZ4 algorithm!

场景二（字段不包含字符串）:
表结构:create table if not exists test_stat (its timestamp,succ_count int);
导入1亿行记录，导入过程中出现:
taosd: /home/plum/git/tdengine/src/system/src/vnodeImport.c:96: vnodeCloseFileForImport: Assertion `pHinfo->compInfoOffset' failed.
Aborted

两种场景下导入失败后，DB异常退出后无法再启动。

请问一下，目前开源版本是否是内部的精简版本，觉得问题挺多的。并且实验过程中，还出现过一次段错误。

期盼您的答复:)

**Comment by plum-lihui** [comment]
您好！ 非常感谢能将出现的问题提交给我们。
我们重复了这个测试，但没有能复现同样的问题。您能将这个测试出现的问题的日志发送给我们分析吗？
缺省配置的话，日志在/var/log/taos目录，请把这个目录下的文件压缩发送给我:huili@taosdata.com。
再次感谢！

**Comment by plum-lihui** [comment]
另外，缺省配置下，日志只会记录错误的信息，而一般的跟踪信息不会记录，不利于定位问题。因此测试前，可以修改一下配置文件，将其中的跟踪调试开关打开。此时需要重新启动程序，才能生效。配置文件在/etc/taos/taos.cfg。
请将如下的开关都打开，并修改成135：
# debug flag for meta management messages
  mDebugFlag            135

# debug flag for dnode messages
 dDebugFlag            135

# debug flag for TDengine SDB
 sdbDebugFlag          135

# debug flag for RPC 
 taosDebugFlag         135

# debug flag for basic utils
 debugFlag             135

# debug flag for TDengine client 
 cDebugFlag            135

# debug flag for http server
 httpDebugFlag         135

# debug flag for system monitor 
 monitorDebugFlag      135

# debug flag for TAOS TIMER
 tmrDebugFlag          135

**Comment by plum-lihui** [comment]
“data is already imported to file”：这个信息，应该是csv文件中有时间戳相同的记录。

**Comment by XLPE** [comment]
> “data is already imported to file”：这个信息，应该是csv文件中有时间戳相同的记录。不知道您的csv文件中的数据记录是怎么生成的？

请问时间戳的格式是不是必须是2019-07-15 00:00:00,而不能是数字时间戳1563120000？

**Comment by plum-lihui** [comment]
两种格式都支持。但第一种需要用单引号引起来：'2019-07-15 00:00:00'; 第二种必须是毫秒单位的值。

**Comment by plum-lihui** [comment]
如果可以的话，或许将您的csv文件给我们，我们来运行测试一次，看是否能复现问题？

**Comment by XLPE** [comment]
> 如果可以的话，或许将您的csv文件给我们，我们来运行测试一次，看是否能复现问题？

昨天一直碰到，后来没办法，用C客户端解析csv导入成功了。奇怪，今天用同样的方式，我也重现不了了
