### ISSUE TITLE
taos connect failed, reason: Unable to establish connection.

### ISSUE THREAD

**Issue by zengzeng-x** [taosdata/TDengine#5301]
最开始提示 server disk:/var/log/taos space remain 0.000 GB, total 91.5 GB, stop print log.
server disk:/var/log/taos space remain 0.000 GB, total 91.5 GB, stop print log.
server disk:/var/log/taos space remain 0.000 GB, total 91.5 GB, stop print log.
server disk:/var/log/taos space remain 0.000 GB, total 91.5 GB, stop print log.
server disk:/var/log/taos space remain 0.000 GB, total 91.5 GB, stop print log.
server disk:/var/log/taos space remain 0.000 GB, total 91.5 GB, stop print log.
server disk:/var/log/taos space remain 0.000 GB, total 91.5 GB, stop print log.
server disk:/var/log/taos space remain 0.000 GB, total 91.5 GB, stop print log.
server disk:/var/log/taos space remain 0.000 GB, total 91.5 GB, stop print log.
server disk:/var/log/taos space remain 0.000 GB, total 91.5 GB, stop print log.
server disk:/var/log/taos space remain 0.000 GB, total 91.5 GB, stop print log.
server disk:/var/log/taos space remain 0.000 GB, total 91.5 GB, stop print log.
server disk:/var/log/taos space remain 0.000 GB, total 91.5 GB, stop print log.
server disk:/var/log/taos space remain 0.000 GB, total 91.5 GB, stop print log.

然后我把存储log的目录修改了，
在通过 taos 进入的时候 就报 taos connect failed, reason: Unable to establish connection.
下面是查看状态
[root@10-43-75-17 taos]# systemctl status taosd
● taosd.service - TDengine server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Mon 2021-03-01 11:12:45 CST; 28s ago
  Process: 361734 ExecStart=/usr/bin/taosd (code=exited, status=255)
 Main PID: 361734 (code=exited, status=255)

这个是什么原因导致的呢？

**Comment by moziie** [comment]
可以尝试命令行输入 taosd 查看console是否有报错提示信息^_^

**Comment by zengzeng-x** [comment]
![Uploading image.png…]()

**Comment by zengzeng-x** [comment]
03/01 14:08:41.219681 0x7fb76f81d740 DND read file /var/lib/taos/dnode/mnodeEpSet.json successed
03/01 14:08:41.219693 0x7fb76f81d740 DND print minfos, mnodeNum:1 inUse:0
03/01 14:08:41.219703 0x7fb76f81d740 DND mnode index:1, 10-43-75-17:6030
03/01 14:08:41.219727 0x7fb76f81d740 DND print minfos, mnodeNum:1 inUse:0
03/01 14:08:41.219739 0x7fb76f81d740 DND mnode index:1, 10-43-75-17:6030
03/01 14:08:41.219749 0x7fb76f81d740 DND dnode minfos is initialized
03/01 14:08:41.219789 0x7fb76f81d740 WAL wal module is initialized, refId:3
03/01 14:08:41.219883 0x7fb76f81d740 UTL ERROR failed to get disk size, tmpDir:/tmp errno:No such file or directory
03/01 14:08:41.219897 0x7fb76f81d740 DND ERROR free disk size: 0.000000 GB, too little, quit
03/01 14:08:41.219945 0x7fb76f81d740 DND ERROR failed to check item:disk

提示磁盘不够 但是我刚才释放了磁盘 现在 
/dev/mapper/centos-root               92G   79G  8.3G  91% /  还有8.3G可以用

**Comment by jadedrip** [comment]
刚发现的，/tmp 目录需要有至少1G空间

**Comment by zengzeng-x** [comment]
感谢帮助 已经解决

**Comment by ruixiwu** [comment]
我的ARM盒子总共500M空间， 所说tsengine支持边缘计算， 结果启动时遇到如下问题：

04/23 11:23:14.537519 00000582 DND step:dnode-cfg is initialized
04/23 11:23:14.538325 00000582 DND dnode eps is initialized
04/23 11:23:14.538937 00000582 DND step:dnode-eps is initialized
04/23 11:23:14.539717 00000582 DND dnode minfos is initialized
04/23 11:23:14.540205 00000582 DND step:dnode-minfos is initialized
04/23 11:23:14.540970 00000582 WAL wal module is initialized, rsetId:3
04/23 11:23:14.541919 00000582 DND step:dnode-wal is initialized
04/23 11:23:14.543181 00000582 DND step:dnode-sync is initialized
04/23 11:23:14.544217 00000582 DND ERROR free disk size: 0.240799 GB, too little, quit
04/23 11:23:14.545224 00000582 DND ERROR failed to check item:disk
# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root                 3.5G    588.7M      2.7G  17% /
devtmpfs                222.1M         0    222.1M   0% /dev
tmpfs                   246.6M         0    246.6M   0% /dev/shm
tmpfs                   246.6M         0    246.6M   0% /tmp
tmpfs                   246.6M         0    246.6M   0% /run
# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root                 3.5G    588.8M      2.7G  17% /
devtmpfs                222.1M         0    222.1M   0% /dev
tmpfs                   246.6M         0    246.6M   0% /dev/shm
tmpfs                   246.6M         0    246.6M   0% /tmp
tmpfs                   246.6M         0    246.6M   0% /run
