### ISSUE TITLE
No correct result in Grafana when use "like" , which is different from the result in taos shell

### ISSUE THREAD

**Issue by wangxue1990** [taosdata/TDengine#5309]
1、问题描述
在grafana中使用like语句，不能产生正确结果，和在taos命令行结果不一致
qq:896414622

**Comment by yu285** [comment]
请添加我的微信15652223354，方便处理配置问题

**Comment by wangxue1990** [comment]
找到两个原因：1，like 后跟的字符用双引号，可能和json解析有关；2、不能超过24个字节，汉字的话也就是12.5个字；
