### ISSUE TITLE
关于TD与Activemq的结合

### ISSUE THREAD

**Issue by Magic757086354** [taosdata/TDengine#531]
目前AMQ服务器不支持消息持久化到TD中吗？
请问有没有人尝试过AMQ的二次开发，实现消息持久化到TD中？
如何实现的，谢谢。
另外，AMQ中Topic方式的消息推送，当客户端消费消息后，数据库中消息就会失去记录，如何能实现推送的所有消息内容，在服务器端持续化到数据库，以用于第三方数据分析用。

**Comment by guanshengliang** [comment]
the message from activeMQ can't be fully recognised by TDengine.
we will think about it
and you can also do this thing in a custom way

**Comment by Magic757086354** [comment]
> the message from activeMQ can't be fully recognised by TDengine.
> we will think about it
> and you can also do this thing in a custom way

请问目前有没有哪些消息broker（支持MQTT协议的broker ）可以实现消息持久化到TD。
谢谢！

**Comment by guanshengliang** [comment]
we will support EMQ in about two months

**Comment by guanshengliang** [comment]
@liu0x54  Is this job planned

**Comment by liu0x54** [comment]
We have solution to support AMQ Now, some extra APIs needed.

**Comment by sangshuduo** [comment]
EMQ 开源版和企业版都支持了存储数据到 TDengine
