### ISSUE TITLE
性能测试问题

### ISSUE THREAD

**Issue by think157** [taosdata/TDengine#5316]
---- Spent 17351.464844 seconds to insert 100000000 records, speed: 5763.202148 Rows/Second
测试环境是单个物理机是24c，64G内存组成的3个dnode的集群
对比官方测试差距较大，请问是什么原因呢？

**Comment by dullduck** [comment]
你这个和我的单机版, 8核8G的机器测试的数据差不多.  测试的数据是官方的1/3到1/4
