### ISSUE TITLE
error: Failed dependencies: /usr/bin/python3 is needed by tdengine-2.0.16.0-3.x86_64

### ISSUE THREAD

**Issue by dockerlvze** [taosdata/TDengine#5319]
**Bug Description**

When I install tdengine with rpm,I found question like this:
[root@docker2 ~]#  rpm -ivh TDengine-server-2.0.16.0-Linux-x64.rpm 
error: Failed dependencies:
        /usr/bin/python3 is needed by tdengine-2.0.16.0-3.x86_64
[root@docker2 ~]# 

**centos default python version is 2.7,i reinstall python version 3,but the problem still exist:**

[root@docker2 ~]# cat /etc/redhat-release 
**CentOS Linux release 7.6.1810 (Core)** 
[root@docker2 ~]# uname -a
Linux docker2 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[root@docker2 ~]# python
**Python 3.6.1** (default, Feb 28 2021, 22:04:14) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
 quit()
[root@docker2 ~]# ll
total 24892
-rw-------.  1 root  root     1272 Mar 20  2020 anaconda-ks.cfg
drwxr-xr-x. 10 root  root     4096 Mar 27  2020 atsea-sample-shop-app
-rw-r--r--.  1 root  root  6803977 Mar 26  2020 atsea-sample-shop-app-master.zip
-rw-r--r--.  1 root  root    15448 Nov  1 04:35 epel-release-latest-7.noarch.rpm
drwxrwxr-x.  5 mysql mysql      90 Mar  1 11:35 TDengine-server-2.0.16.0
-rw-r--r--.  1 root  root  9106004 Mar  1 11:03 TDengine-server-2.0.16.0-Linux-x64.rpm
-rw-r--r--.  1 root  root  9398005 Mar  1 10:38 TDengine-server-2.0.16.0-Linux-x64.tar-1.gz
[root@docker2 ~]# rpm -ivh TDengine-server-2.0.16.0-Linux-x64.rpm 
**error: Failed dependencies:
        /usr/bin/python3 is needed by tdengine-2.0.16.0-3.x86_64**
[root@docker2 ~]# ll /usr/bin/python3
lrwxrwxrwx. 1 root root 30 Mar  1 11:09 /usr/bin/python3 -> /usr/local/python3/bin/python3
[root@docker2 ~]# 

I suspect this is a bug,thank you.

**Comment by yushan-yaojin** [comment]
这么装：
rpm -ivh  --nodeps  TDengine-server-2.0.16.0-Linux-x64.rpm

**Comment by sangshuduo** [comment]
下个版本会解决这个问题
