### ISSUE TITLE
ERROR failed to get disk size, dataDir:/var/lib/taos errno:No such file or directory

### ISSUE THREAD

**Issue by dockerlvze** [taosdata/TDengine#5321]
![image](https://user-images.githubusercontent.com/62325373/109745200-78065780-7c0e-11eb-88d2-381ce2fc1c5a.png)
配置集群时，官方文档上有个地方是清理/var/lib/taos/下的文件，按照文档上执行会把/var/lib/taos目录直接删除，发现日志有报错，需要手动再建立taos目录，是否应该写rm -rf /var/lib/taos/* 
![image](https://user-images.githubusercontent.com/62325373/109745436-cfa4c300-7c0e-11eb-8bfa-9aa1ba223ac5.png)

**Comment by yu285** [comment]
Hi, we have corrected the issue that you gave feedback.
Thanks for your seriousness, thanks for your support to TDengine

![image](https://user-images.githubusercontent.com/74105241/110270229-5a673280-8000-11eb-8cd4-cf41c32140b3.png)
