### ISSUE TITLE
UTL ERROR failed to get the ip address

### ISSUE THREAD

**Issue by sj-dev** [taosdata/TDengine#5337]
我使用k8s布署，但是只有域名，没有固定IP，但是taos集群一启动，就需要将域名转成IP，有一些pod没有启动，还没有IP，导致都无法启动，有什么办法解决吗？为什么一定要用IP，不能用域名呢？
UTL ERROR failed to get the ip address, fqdn:taos-1.ss.iot-ns.svc.cluster.local, since:Name or service not know
k8s平台是没有固定IP的，只有域名

**Comment by sj-dev** [comment]
主要是K8S平台的IP是动态的，所有Pod之间的访问都是使用域名的。在Pod1启动的时候，Pod2,Pod3还没有启动，所以ping这一个域名是空的。同时Pod2和Pod3没有启动，也无法知道启动后的IP是多少的。

**Comment by sangshuduo** [comment]
TDengine 使用 fqdn 应该没有这个问题，taosd 启动后会尝试重连其他节点，后面的节点启动后不就可以了吗？

**Comment by sj-dev** [comment]
假如一直在尝试也好，主要的问题应该是taosd启动后发现没有Pod2这一个IP，解析成了Name or service not know导致docker启动的镜像进程就关闭了。如果启动的过程一直在等待，那应该不会出现上面的问题。

**Comment by zitsen** [comment]
Sugguest to use helm to install TDengine on k8s. See https://taosdata.github.io/TDengine-Operator/zh/2.2-tdengine-with-helm.html

Reopen the issue if not solved.
