### ISSUE TITLE
Insert data according to table tags

### ISSUE THREAD

**Issue by whljava** [taosdata/TDengine#534]
不能根据子表的标签进行插入数据吗？ 想要插入数据的时候必须还得知道这条数据所在的表名吗？
是TDengine没有提供这个功能还是我没找到？？？

**Comment by hzcheng** [comment]
不能根据子表标签插入数据，因为标签有时候不能唯一确定子表。比如车作为子表，车的颜色作为标签，那么很多车可能都拥有颜色为红色的标签，因此不能唯一确定。除非你可以确定你的表的tag可以唯一确定一张子表。
