### ISSUE TITLE
安装2.0.16.0 报错

### ISSUE THREAD

**Issue by zengzeng-x** [taosdata/TDengine#5344]
rpm -iv TDengine-server-2.0.16.0-Linux-x64.rpm
error: Failed dependencies:
        /usr/bin/python3 is needed by tdengine-2.0.16.0-3.x86_64

linux系统 centos7

是需要安装python环境吗？

**Comment by sangshuduo** [comment]
rpm -ivh --nodeps

下个版本会解决这个问题
