### ISSUE TITLE
fail to insert data after adding a tag

### ISSUE THREAD

**Issue by tanghuangthree** [taosdata/TDengine#5349]
**Bug Description**
version: 2.0.14.0
system: linux
新添加一个tag，随后insert数据失败。新增加tag的值任然为null。
可以如下截图：
![image](https://user-images.githubusercontent.com/19163166/109942932-9d2ebf00-7d0f-11eb-8b22-dc861a9a57d2.png)

**Comment by sangshuduo** [comment]
已知问题，下个版本会包含问题修复。

**Comment by yuhuangdada** [comment]
请问具体在那个版本修复了。

**Comment by sangshuduo** [comment]
下一个版本，2.0.17.0

**Comment by cpvmrd** [comment]
[TDengine 2.0.17](https://www.taosdata.com/cn/getting-started/#%E9%80%9A%E8%BF%87%E5%AE%89%E8%A3%85%E5%8C%85%E5%AE%89%E8%A3%85) has released. 
Please try again.

**Comment by cpvmrd** [comment]
This issue was closed because it has been inactive for too many days.
