### ISSUE TITLE
使用Python Connector连接远程TDengine失败

### ISSUE THREAD

**Issue by ohmyheartbeat** [taosdata/TDengine#535]
1.TDengine服务端部署在腾讯云的服务器上，连接代码在本地
2.本地上使用curl的方式能够获取到查询结果，使用taso -h <ip>提示TSDB error: failed to connect to server，同样在服务器上使用这个命令报相同的错误

**Comment by ohmyheartbeat** [comment]
目前经过配置安全组，服务器上使用taos -h可以正常进入命令行，但使用sdk的方式还是连接失败

**Comment by hzcheng** [comment]
您云上机器的端口号有在安全组里面放行吗？
