### ISSUE TITLE
When I use mybatis, last_row fails, the result is null

### ISSUE THREAD

**Issue by spark-wz** [taosdata/TDengine#5365]
**Bug Description**

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by yu285** [comment]
请添加微信15652223354，为您看下
