### ISSUE TITLE
In linux taos shell ,   TDengine can't query normal table tag with offset 

### ISSUE THREAD

**Issue by xxmiao1006** [taosdata/TDengine#5376]
**Bug Description**
在linux taos命令行使用offset 无法查询普通表标签列的问题

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**
当offset大于0时无法显示普通表标签列的值
![image](https://user-images.githubusercontent.com/37374467/110286260-978eed00-801f-11eb-91a1-df917a1c0da2.png)

**Environment (please complete the following information):**
 - OS: [CentOS 7.0]
 - TDengine Version [2.0.16.0]

**Additional Context**

**Comment by yu285** [comment]
已在与研发同事沟通反馈，烦请耐心等待。

**Comment by yu285** [comment]
这个问题已经在2.0.17被修复
