### ISSUE TITLE
how to use mybatis to connect to TDengine

### ISSUE THREAD

**Issue by whljava** [taosdata/TDengine#538]
查询文档发现没有连接mybatis的配置  然后我自己试了一下是有mysql的那一套结果发现没有写cfgdir配置的地方   有没有使用过mabtis连接的发一下项目看下可以吗？

**Comment by guanshengliang** [comment]
we will give a complete solution in about two months

**Comment by guanshengliang** [comment]
jdbc can support mybatis now, you can download and try again
