### ISSUE TITLE
offlineThreshold didn't take effect

### ISSUE THREAD

**Issue by moziie** [taosdata/TDengine#5383]
env:
centos7,8核16G，三节点集群，版本2.0.15
配置参数offlineThreshold    6000 （10分钟）
![image](https://user-images.githubusercontent.com/70946068/110410085-4cc6b100-80c3-11eb-9df3-5be286a54383.png)

测试让其中一个节点宕机，等待时间超过offlineThreshold时间，按文档中描述应该会出现
‘该数据节点离线超过一定时间（taos.cfg里配置参数offlineThreshold控制时长)，系统将自动把该数据节点删除，产生系统报警信息，触发负载均衡流程。如果该被删除的数据节点重新上线时，它将无法加入集群，需要系统管理员重新将其添加进集群才会开始工作。’
![image](https://user-images.githubusercontent.com/70946068/110410138-6667f880-80c3-11eb-810b-f00a88cb1a16.png)
但是现在宕机节点一直处于offline状态，并没有被系统删除，手动drop节点则一直处于dropping 状态
配置文件中的offlineThreshold参数如何配置才能生效

**Comment by cpvmrd** [comment]
请问启动日志中显示的offlineThreshold参数正确吗？

**Comment by moziie** [comment]
> 请问启动日志中显示的offlineThreshold参数正确吗？

![image](https://user-images.githubusercontent.com/70946068/112235488-b628f100-8c79-11eb-9b2c-2c7ebaac4926.png)
启动日志上显示的是我设置的数值

**Comment by cpvmrd** [comment]
This issue was closed because it has been inactive for too many days.
