### ISSUE TITLE
Trying  to import CSV with TAOS IMPORT , but got an error while compiling time  as below 

### ISSUE THREAD

**Issue by se7enshidb** [taosdata/TDengine#5384]
[root@sdw3 importSampleData]$ GO111MODULE=off go build -o bin/taosimport app/main.go
import/import_config.go:9:2: cannot find package "github.com/pelletier/go-toml" in any of:
	/usr/lib/golang/src/github.com/pelletier/go-toml (from $GOROOT)
	/home/shidb/gitrepo/go/src/github.com/pelletier/go-toml (from $GOPATH)
app/main.go:22:2: cannot find package "github.com/taosdata/driver-go/taosSql" in any of:
	/usr/lib/golang/src/github.com/taosdata/driver-go/taosSql (from $GOROOT)
	/home/shidb/gitrepo/go/src/github.com/taosdata/driver-go/taosSql (from $GOPATH)

@plum-lihui 

同时taosdemox也无法导入指定的csv文件
https://www.taosdata.com/blog/2020/12/29/2135.html

**Comment by cpvmrd** [comment]
Please refer to https://stackoverflow.com/questions/13214029/go-build-cannot-find-package-even-though-gopath-is-set.
