### ISSUE TITLE
TDengine-ver-2.0.17.0 version.c version error

### ISSUE THREAD

**Issue by nieyuanqing** [taosdata/TDengine#5385]
# cat src/util/src/version.c
char version[12] = "2.0.16.0";
char compatible_version[12] = "2.0.0.0";
char gitinfo[48] = "no git commit id";
char gitinfoOfInternal[48] = "";
char buildinfo[64] = "Built at 2021-03-09 11:57:09";

void libtaos_2_0_16_0_Linux_x32_stable() {};

src/util/src/version.c输出版本还是2.0.16.0

**Comment by cpvmrd** [comment]
I will rebuild the project and confirm if it is a problem.

**Comment by cpvmrd** [comment]
有可能发版分支和develop分支当时没同步，已解决。
