### ISSUE TITLE
Using TAOS-JDBC 2.0.20 to connect to TDengine cluster.Stop firstEP node, read Taos.cfg to use secondEP,  then error happened:java.sql.SQLException: JNI ERROR (2354): JNI connection is NULL 

### ISSUE THREAD

**Issue by icecreamlb** [taosdata/TDengine#5395]
**Bug Description**

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by icecreamlb** [comment]
Class.forName("com.taosdata.jdbc.TSDBDriver");
        String jdbcUrl = "jdbc:TAOS://:/pointdata?user=root&password=taosdata";
        Properties connProps = new Properties();
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_CHARSET, "UTF-8");
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_LOCALE, "en_US.UTF-8");
        connProps.setProperty(TSDBDriver.PROPERTY_KEY_TIME_ZONE, "UTC-8");
        Connection conn = DriverManager.getConnection(jdbcUrl, connProps);

**Comment by zyyang-taosdata** [comment]
我来看一下

**Comment by icecreamlb** [comment]
好的，感谢，希望发布新版也可以在交流群里面学习

**Comment by zyyang-taosdata** [comment]
在最新版本里已经修复了这个问题，请更新tdengine和taos-jdbcdriver的版本

**Comment by cxntsh** [comment]
> 在最新版本里已经修复了这个问题，请更新tdengine和taos-jdbcdriver的版本

最新的版本貌似也有这个问题，Demo 就是 Client 安装包里面的。 #5539

**Comment by zyyang-taosdata** [comment]
> > 在最新版本里已经修复了这个问题，请更新tdengine和taos-jdbcdriver的版本
> 
> 最新的版本貌似也有这个问题，Demo 就是 Client 安装包里面的。 #5539

**Comment by icecreamlb** [comment]
这个应该是 jar包的问题 ，需要同时 “更新tdengine和taos-jdbcdriver的版本”，而且目前这个版本已经应用生产了，tdengine 更新的话，会影响原有的数据

**Comment by zyyang-taosdata** [comment]
> 这个应该是 jar包的问题 ，需要同时 “更新tdengine和taos-jdbcdriver的版本”，而且目前这个版本已经应用生产了，tdengine 更新的话，会影响原有的数据

你用新的jar包解决了么？如果解决了，把这个解决这个问题需要的TDengine版本和taos-jdbc版本写出来吧？

**Comment by icecreamlb** [comment]
已经解决问题了，TDengine  还是原来的版本2.0.17， taos-jdbc 版本更新为 2.0.22。
