### ISSUE TITLE
centos 6.5 安装报错

### ISSUE THREAD

**Issue by caoxinjava001** [taosdata/TDengine#54]
您好
centos 6.5 出现如下报错信息
cd /home/sofe/Td/TDengine/TDengine-master/build/src/rpc && /usr/bin/cc -DLINUX -D_LIBC_REENTRANT -D_LINUX -D_M_X64 -D_REENTRANT -D__USE_POSIX -g -std=gnu99 -Wall -fPIC -malign-double -Wno-char-subscripts -malign-stringops -msse4.2 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILE -O0 -DDEBUG -I/home/sofe/Td/TDengine/TDengine-master/src/inc -I/home/sofe/Td/TDengine/TDengine-master/src/rpc/./inc -o CMakeFiles/trpc.dir/src/ttcpclient.c.o -c /home/sofe/Td/TDengine/TDengine-master/src/rpc/src/ttcpclient.c
/home/sofe/Td/TDengine/TDengine-master/src/rpc/src/ttcpclient.c: In function ‘taosOpenTcpClientConnection’:
/home/sofe/Td/TDengine/TDengine-master/src/rpc/src/ttcpclient.c:276: error: ‘EPOLLWAKEUP’ undeclared (first use in this function)
/home/sofe/Td/TDengine/TDengine-master/src/rpc/src/ttcpclient.c:276: error: (Each undeclared identifier is reported only once
/home/sofe/Td/TDengine/TDengine-master/src/rpc/src/ttcpclient.c:276: error: for each function it appears in.)
gmake[2]: Leaving directory /home/sofe/Td/TDengine/TDengine-master/build' gmake[2]: *** [src/rpc/CMakeFiles/trpc.dir/src/ttcpclient.c.o] Error 1 gmake[1]: Leaving directory /home/sofe/Td/TDengine/TDengine-master/build'
gmake[1]: *** [src/rpc/CMakeFiles/trpc.dir/all] Error 2

**Comment by winshining** [comment]
系统的内核版本太低，EPOLLWAKEUP是3.5版本的Linux内核引入的，详情见[epoll_ctl manual](http://www.man7.org/linux/man-pages/man2/epoll_ctl.2.html)，建议维护人添加configure检测系统版本
