### ISSUE TITLE
number limit of tags of the super table

### ISSUE THREAD

**Issue by leigoCQ** [taosdata/TDengine#540]
超级表，标签可以使用时间戳之外的其他TDengine支持的数据类型，标签的个数最多为6个。但往往实际应用中不止6个，可以不进行限制自由扩展吗？

**Comment by hjxilinx** [comment]
The maximum number of tags for one super table be increased up to around 18 soon, which seems to be enough for most cases.

**Comment by leigoCQ** [comment]
> The maximum number of tags for one super table will be increased up to around 18 soon, which seems to be enough for most cases.  ref #385

请问下什么时候能更新发布呢？

**Comment by hjxilinx** [comment]
这个月就会推送最新的版本，能够支持32个tags
