### ISSUE TITLE
TSDB error: client no disk space

### ISSUE THREAD

**Issue by alon-zhong** [taosdata/TDengine#541]
**Bug Description**
从window命令行访问服务端，select count(*) from 超级表名，报错：client no disk space

**To Reproduce**
1. 服务端从1.6.1.6升级到1.6.2.0
2. windows 10先卸载掉1.6.1.6客户端，再安装1.6.2.0
3. windows 10上命令窗口运行taos.exe，连接服务器
4. 顺利连接上，运行show stables，正常响应
5. select count(*) from 子表名，正常响应
6. select count(*) from 超级表名，报错：client no disk space
7. 在另外一台电脑 windows server 2012上，重现错误

**Environment (please complete the following information):**
 - OS: [windows 10]
 - Memory 8G, CPU i7, current Disk Space 19.7G
 - TDengine Version [1.6.2.0]

**Comment by leigoCQ** [comment]
我也是升级到1.6.2.0，在访问超级表聚合数据的时候，当条件标签中包含bigint如id=5391488729654023311的时候就报同样的错误=>TSDB error: client no disk space

**Comment by guanshengliang** [comment]
I have successfully reproduced the problem, and will solve it as soon as possible.
![image](https://user-images.githubusercontent.com/28882257/65402872-b5549c00-de03-11e9-916e-c304883c8d44.png)

**Comment by baocj** [comment]
Welcome to the TDengine shell, client version:1.6.2.1  server version:1.6.2.1
Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.

taos> use db;
Query OK, 1 row(s) affected (0.001000s)

taos> select count(*) from s_ht_data;

TSDB error: client no disk space

taos> show stables;

**Comment by guanshengliang** [comment]
This problem has been fixed
You can pull the latest code or wait for a new release
