### ISSUE TITLE
2.0.17.0 service stop , single node  

### ISSUE THREAD

**Issue by codezhy** [taosdata/TDengine#5415]
复现过程, 服务挂掉后, 再也启动不了了

taos> CREATE DATABASE truck_location KEEP 3650 DAYS 10 BLOCKS 4 UPDATE 1;
Query OK, 0 of 0 row(s) in database (0.006196s)

taos> use truck_location;
Database changed.

taos> CREATE STABLE location_meters (positiontime timestamp, latitude double, longitude double, source int,vec1 float,vec2 float,direction int,recei
veTime timestamp) TAGS (vehicleno NCHAR(64), platecolor int,channelid int);
Query OK, 0 of 0 row(s) in database (0.006938s)

taos> CREATE TABLE IF NOT EXISTS t0000000 USING location_meters (platecolor) tags (2);
Query OK, 0 of 0 row(s) in database (0.040186s)

taos> drop table t0000000;

**Comment by liuyuinsdu** [comment]
看一下log，是不是报连接不上6035端口，我也是drop table导致服务挂掉了

**Comment by cpvmrd** [comment]
This issue was closed because it has been inactive for too many days.
