### ISSUE TITLE
M1 MacBook Pro can't install client

### ISSUE THREAD

**Issue by Wizzercn** [taosdata/TDengine#5416]
**Bug Description**
[ ] TDengine-client-2.0.17.0 % ./install_client.sh
```
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
```

**Comment by yu285** [comment]
Hi, currently the TDengine client can be installed in Windows and Linux only.

If you want to connect to TDengine,  you can choose the RESTFUL interface.

Please refer to the link for details：https://www.taosdata.com/cn/documentation/connector#restful
