### ISSUE TITLE
unable to establish connection with port 6035

### ISSUE THREAD

**Issue by liuyuinsdu** [taosdata/TDengine#5417]
![image](https://user-images.githubusercontent.com/4965941/110760224-74677600-8289-11eb-98b5-7c9de17bf3e5.png)
客户端也一直连不上
![image](https://user-images.githubusercontent.com/4965941/110760312-8d702700-8289-11eb-9745-9cfc46247e60.png)

**Comment by moziie** [comment]
你是几个节点的集群呀，都得起来才能连上的

**Comment by yu285** [comment]
不提供具体细节这边很难调查，可以加我微信15652223354，帮您排查修复

**Comment by hiwooNum1** [comment]
> 不提供具体细节这边很难调查，可以加我微信15652223354，帮您排查修复

兄弟，解决没？ 我也遇到此问题
