### ISSUE TITLE
DatabaseMetaData.getTables() desn't return the correct tables.

### ISSUE THREAD

**Issue by caesarhawk** [taosdata/TDengine#5419]
**Bug Description**

 if the database doesn't exist, it will return the  tables of the last db it scans .

**To Reproduce**
write the following code 
DatabaseMetaData md= con.getMetaData();
ResultSet colRet = md.getTables(db+"www",db, tableName,null);  // db doesn't exist

**Expected Behavior**
return null

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by cpvmrd** [comment]
It is suggested to update your TDengine version to 2.0.x.

**Comment by cpvmrd** [comment]
This issue was closed because it has been inactive for too many days.
