### ISSUE TITLE
DatabaseMetaData.getColumns(),ResultRet.getString("TABLE_NAME") Can't get the correct value

### ISSUE THREAD

**Issue by caesarhawk** [taosdata/TDengine#5420]
**Bug Description**

 DatabaseMetaData m_DBMetaData = con.getMetaData();
 HikariProxyResultSet colRet = (HikariProxyResultSet) m_DBMetaData.getColumns(db,"%", tableName,"%");
colRet.getString("COLUMN_NAME");  
 // should return colunm name ,but return TABLE_NAME

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by cpvmrd** [comment]
It is suggested to update your TDengine version to 2.0.x.

**Comment by cpvmrd** [comment]
This issue was closed because it has been inactive for too many days.
