### ISSUE TITLE
关于连接池的使用

### ISSUE THREAD

**Issue by nieyuanqing** [taosdata/TDengine#5422]
Hi，
关于Python Connector TDengine这样的用法是否可以？
1. 服务启动时，创建若干个连接的连接池。
2. 多线程共享连接池资源。
3. 每一次execute时，从连接池取出该连接资源，使用完成后，换回连接池。
4. 连接资源线程获取后，独享使用，使用期间，其他线程无法使用，直到换回连接池资源。

**Comment by yu285** [comment]
已反馈，请等待消息

**Comment by sangshuduo** [comment]
请参考 https://github.com/taosdata/TDengine/issues/5397 的回复
另外 Python 因为有 GIL 的问题，使用线程并不能带来什么好处

**Comment by nieyuanqing** [comment]
哥们，已经用了线程了， 上面的实现方案是否是安全的？

**Comment by sangshuduo** [comment]
这么问我们没法回答。有具体问题再反馈吧，附上详细问题描述和相关代码

**Comment by nieyuanqing** [comment]
主线程持续插入行为采集数据；
辅助线程，分析设备离线，预处理后插入数据记录。
两个逻辑无法同步进行，为每个线程分配一个connection的做法有点丑陋，就设置连接池供两个线程使用。

**Comment by nieyuanqing** [comment]
我想确认一下常规线程池的做法对TDengine 的connection是否有效？

**Comment by nieyuanqing** [comment]
这是TDengine的官方文档描述：
注意：2.0及以上版本 TDengine 推荐数据库应用的每个线程都建立一个独立的连接，或基于线程建立连接池。而不推荐在应用中将该连接 (TAOS*) 结构体传递到不同的线程共享使用。基于 TAOS 结构体发出的查询、写入等操作具有多线程安全性，但 “USE statement” 等状态量有可能在线程之间相互干扰。此外，C 语言的连接器可以按照需求动态建立面向数据库的新连接（该过程对用户不可见），同时建议只有在程序最后退出的时候才调用 taos_close 关闭连接。

**Comment by nieyuanqing** [comment]
从官方文档描述，线程池应该是可以的，但是描述较为简单，还是想确认一下。
