### ISSUE TITLE
A multi-condition query Bug which  select expression  is not a primary-key column

### ISSUE THREAD

**Issue by nieyuanqing** [taosdata/TDengine#5432]
taos> select count(*) from pingback where pt >= "2020-12-31 14:00:00" and pt < "2021-01-01 14:00:00" and item != "14" and id=64  order by pt ASC;
       count(*)        |
========================
                  1696 |
Query OK, 1 row(s) in set (0.016713s)

taos>
taos> select count(*) from pingback where pt >= "2020-12-31 14:00:00" and pt < "2021-01-01 14:00:00" and item != "14" and item != "110" and id=64  order by pt ASC;
       count(*)        |
========================
                 15748 |
Query OK, 1 row(s) in set (0.019725s)

第二条sql在第一条sql的基础上多了条件：item != "110", 结果第二条SQL查询结果还比第一个多。第二条sql 两个item字段条件，像是查询时，sql非法，将item的两个条件自动过滤了。

**Comment by yu285** [comment]
您好，请提供一下如下信息以便帮您定位问题。：
操作系统及版本：
数据库版本：
是否docker：
show databases截图：

**Comment by nieyuanqing** [comment]
操作系统及版本：CentOS Linux release 7.8.2003 (Core)
数据库版本：version: 2.0.16.0
是否docker： 否
![show_databases](https://user-images.githubusercontent.com/24584358/111935503-915c3e80-8afe-11eb-8ecd-ba64eb6701ae.png)

show databases截图：见附件。

**Comment by nieyuanqing** [comment]
上传show databases的图有问题，补充一下文本信息：
taos> show databases;
              name              |      created_time       |   ntables   |   vgroups   | replica | quorum |  days  |   keep0,keep1,keep(D)    |  cache(MB)  |   blocks    |   minrows   |   maxrows   | wallevel |    fsync    | comp | cachelast | precision | update |   status   |
====================================================================================================================================================================================================================================================================================
 log                            | 2021-03-10 21:38:22.484 |           4 |           1 |       1 |      1 |     10 | 30,30,30                 |           1 |           3 |         100 |        4096 |        1 |        3000 |    2 |         0 | us        |      0 | ready      |
 pingback                       | 2021-03-11 16:40:22.114 |         329 |           1 |       1 |      1 |     10 | 3650,3650,3650           |          16 |           6 |         100 |        4096 |        1 |        3000 |    2 |         0 | ms        |      0 | ready      |
Query OK, 2 row(s) in set (0.010278s)

**Comment by yu285** [comment]
this issue has been fixed , you can upgrade it to 2.0.18 to test it .

**Comment by nieyuanqing** [comment]
好的，多谢，我们测试验证。
