### ISSUE TITLE
tdengine memory limit problem

### ISSUE THREAD

**Issue by caojianwudong** [taosdata/TDengine#5438]
Memory Size = maxVgroupsPerDb * (blocks * cache + 10Mb) + numOfTables * (tagSizePerTable + 0.5Kb)
问题：-------------------------------------------------------------------------------------------------------------------
安装上面的公式，我将/etc/taos/taos.cfg文件中的maxVgroupsPerDb设为1后重启服务，其他值都为默认，那么taosd的占用内存应该不会超过200M 吧，但是实际内存占用超过了300M,这是什么原因导致的、

**Comment by yu285** [comment]
请问您有多少张表呢，超级表字段是什么样的呢？需要具体分析的话可以联系我们，微信：15652223354

**Comment by caojianwudong** [comment]
数据库只有两个基本表，没有用到超级表

**Comment by dullduck** [comment]
我也感觉这个容量评估的公式不准。同时taos也没有限制最大内存使用的参数，急需！

**Comment by yu285** [comment]
我们暂时没有做这个限制，是因为想用前期的合理规划来最大化我们的性能。而限制内存默认是放弃了一部分性能，防止系统崩溃。上述内存是粗略估算+还要加上一些常备的冗余部分。  您公司急需的话，可以添加我的微信：15652223354，我们研究一下其他方案。

**Comment by yu285** [comment]
> 我也感觉这个容量评估的公式不准。同时taos也没有限制最大内存使用的参数，急需！

您好，我们十分重视您的需求。因此需要调研一下，您急需最大内存使用参数的原因是什么？是出于安全考虑还是其他呢？

**Comment by yu285** [comment]
关于内存的描述，官网已经更新，https://www.taosdata.com/cn/documentation/administrator。
