### ISSUE TITLE
Can not reinstalling tdengine. undefined symbol: tsDiskCfg

### ISSUE THREAD

**Issue by 14799678** [taosdata/TDengine#5452]
hi everyone:
     I have a question about reinstalling tdengine.In my team,we want to use 2.0.7 tdengine subsitude the old one version 2.0.3.0. The old one file is  tar.gz . And after I remove.sh the old version,I install the 2.0.7 version using the rpm package .when I command systemctl start taosd ,There was the erro "
Mar 15 19:03:00 hix47 systemd[1]: taosd.service: main process exited, code=exited, status=127/n/a
Mar 15 19:03:00 hix47 systemd[1]: Unit taosd.service entered failed state.
Mar 15 19:03:00 hix47 systemd[1]: taosd.service failed.
Mar 15 19:03:01 hix47 systemd[1]: taosd.service holdoff time over, scheduling restart.
Mar 15 19:03:01 hix47 systemd[1]: Stopped TDengine server service.
-- Subject: Unit taosd.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit taosd.service has finished shutting down.
Mar 15 19:03:01 hix47 systemd[1]: start request repeated too quickly for taosd.service
Mar 15 19:03:01 hix47 systemd[1]: Failed to start TDengine server service.
"
I try to type the command "./taosd" get error "undefined symbol: tsDiskCfg"

So can anyone help me to resolve this problem,or any suggestion.thanks
my os version is 
uname -a
Linux hix47 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
"CentOS Linux release 7.8.2003 (Core)"
ali cloud.

Thanks.

**Comment by stephenkgu** [comment]
ldd ./taosd

**Comment by yu285** [comment]
这是中景恒基云端物联-运维-侯汝全的问题，我们已经在微信上私信后解决，可以等问题关掉了。
