### ISSUE TITLE
can 'distinct' be used?

### ISSUE THREAD

**Issue by zhaisa** [taosdata/TDengine#5454]
select distinct id from stb1;why tell me that DB error: invalid SQL: only support distinct one tag (0.005590s)

**Comment by yu285** [comment]
please provide the version you are using currently. then we could find why this happened.

**Comment by zhaisa** [comment]
the version  is 2.0.17

**Comment by yu285** [comment]
can you show me the output of " describe stb1"  and "show stables"

**Comment by zhaisa** [comment]
![image](https://user-images.githubusercontent.com/26134879/112262138-18004f80-8ca8-11eb-86cc-3133adf49263.png)

**Comment by yu285** [comment]
Currently  , the keyword Distinct  only support  executing on the tag in super table but not the normal column
