### ISSUE TITLE
Docker:   taos connect failed, reason: Unable to establish connection

### ISSUE THREAD

**Issue by 379547990** [taosdata/TDengine#5456]
一 、docker  容器与端口映射状态查询正常
C:\Users\Administrator>docker ps
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATU
             PORTS
                                                            NAMES
5c6594050785        tdengine/tdengine           "taosd"                  2 hours ago         Up 2
urs          0.0.0.0:6030->6030/tcp, 6031-6034/tcp, 0.0.0.0:6035->6035/tcp, 6036-6040/tcp, 0.0.0.0
041->6041/tcp, 0.0.0.0:6030-6040->6030-6040/udp, 6042/tcp   tdengine2.0.17.0
9f54d730e764        onlyoffice/documentserver   "/bin/sh -c /app/onl"   6 months ago        Up 22
urs
                                                           onlyoffice

C:\Users\Administrator>docker port 5c6594050785
6030/tcp -> 0.0.0.0:6030
6040/udp -> 0.0.0.0:6040
6030/udp -> 0.0.0.0:6030
6034/udp -> 0.0.0.0:6034
6035/tcp -> 0.0.0.0:6035
6041/tcp -> 0.0.0.0:6041
6031/udp -> 0.0.0.0:6031
6033/udp -> 0.0.0.0:6033
6039/udp -> 0.0.0.0:6039
6032/udp -> 0.0.0.0:6032
6035/udp -> 0.0.0.0:6035
6036/udp -> 0.0.0.0:6036
6037/udp -> 0.0.0.0:6037
2、容器内部访问正常
root@td225:~/TDengine-server-2.0.17.0# taos;

Welcome to the TDengine shell from Linux, Client Version:2.0.17.0
Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.

taos> show databases;
              name              |      created_time       |   ntables   |   vgroups   | replica | qu
orum |  days  |   keep0,keep1,keep(D)    |  cache(MB)  |   blocks    |   minrows   |   maxrows   | w
allevel |    fsync    | comp | cachelast | precision | update |   status   |
====================================================================================================
====================================================================================================
============================================================================
 log                            | 2021-03-16 02:06:21.676 |           4 |           1 |       1 |
   1 |     10 | 30,30,30                 |           1 |           3 |         100 |        4096 |
      1 |        3000 |    2 |         0 | us        |      0 | ready      |
Query OK, 1 row(s) in set (0.005105s)

taos> exit
root@td225:~/TDengine-server-2.0.17.0# ls
connector  driver  examples  install.sh  taos.tar.gz

3、宿主机连接docker 容器失败
c:\TDengine>taos -h 127.0.0.1 -p 6300

Welcome to the TDengine shell from Linux, Client Version:2.0.17.0
Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.

taos connect failed, reason: Unable to establish connection.

c:\TDengine>taos -h td225

Welcome to the TDengine shell from Linux, Client Version:2.0.17.0
Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.

taos connect failed, reason: Unable to establish connection.

**Comment by yu285** [comment]
可以添加我微信15652223354，给您看一下

**Comment by jtcheng** [comment]
I use below shell script to startup the `tdengine` container and works well:
```
$ cat tdengine.sh
#!/bin/bash
# startup tdengine
set -e

docker run -d --rm -p 6030-6042:6030-6042/tcp -p 6030-6042:6030-6042/udp tdengine/tdengine
```

```
$ tdengine.sh
30dec0d28e76bbf78fd2c2d92cc5136e80f8c39edb06e7084c53db2e039e9c4d

$ taos

Welcome to the TDengine shell from Linux, Client Version:2.1.3.0
Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.

taos> show dnodes;
   id   |           end_point            | vnodes | cores  |   status   | role  |       create_time       |      offline reason      |
======================================================================================================================================
      1 | 30dec0d28e76:6030              |      1 |      6 | ready      | any   | 2021-07-09 12:10:48.976 |                          |
Query OK, 1 row(s) in set (0.009913s)

taos>
```

**Comment by julyzz** [comment]
请问该问题解决了么？我也遇到了同样的问题，版本号：2.0.20.13

**Comment by yu285** [comment]
> 

如果问题仍未解决，可以添加微信15652223354，给您看一下
