### ISSUE TITLE
create table with time interval

### ISSUE THREAD

**Issue by liudican** [taosdata/TDengine#5473]
我在liunx环境taos数据库中执行：
`taos> create table linear2 as select voltage from meters interval(1m)  fill(linear);

DB error: invalid SQL: functions not allowed in CQ (0.000110s`
请问是TDengine不支持吗?谢谢

**Comment by cpvmrd** [comment]
暂不支持，可以参考下这里的SQL语法：https://www.taosdata.com/cn/documentation/taos-sql 。

**Comment by cpvmrd** [comment]
This issue was closed because it has been inactive for too many days.
