### ISSUE TITLE
Number of sessions reached limit

### ISSUE THREAD

**Issue by steven-design** [taosdata/TDengine#5478]
**Bug Description**
Jdk1.8版本，我运行java程序后，用Jmeter压测，每秒50万测点上报数据。
运行30秒左右，java程序运行报错如下：
java.sql.SQLException: TDengine ERROR (8000000a): Number of sessions reached limit
        at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:65)
        at com.taosdata.jdbc.TSDBJNIConnector.executeQuery(TSDBJNIConnector.java:153)
        at com.taosdata.jdbc.TSDBStatement.execute(TSDBStatement.java:88)
        at com.chint.iot.data.write.datasource.config.TDengineUtil.executeSql(TDengineUtil.java:131)
        at com.chint.iot.data.write.kafka.consumer.PointDataService$1.run(PointDataService.java:146)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: CentOS 7.4
 - Memory 32G, CPU i5 8th, current Disk Space 30G
 - TDengine Version [2.0.17]

**Additional Context**

**Comment by yihaoDeng** [comment]
多少线程写TD?

**Comment by chixueli** [comment]
程序报错
用Jmeter压测，每秒50万测点上报数据。
运行30秒左右，java程序运行报错如下：
java.sql.SQLException: TDengine ERROR (8000000a): Number of sessions reached limit
问题回答
以上是报错，是在处理大量网络连(高并发）受到CentOS 7.4 socket最大连接数所受的各种限制 需要优化操作系统 参数 配置
建议优化如下
 首先修改 默认同时打开文件数量，最大 20万
第二 修改默认的 socket 最大网络连接数量 ，例如可以修改配置 打开600万的连接，
参考配置如下，复制以下脚本 在linux 系统窗口运行即可
#!/bin/bash

#set ulimit
if ! grep -q "ulimit -SHn 102400" /etc/rc.local;then
    echo "ulimit -SHn 102400" >> /etc/rc.local
fi

if ! grep -q "add limit" /etc/security/limits.conf;then
cat >> /etc/security/limits.conf << EOF
#########add limit###################
*           soft   nofile       200000
*           hard   nofile       200000
EOF
echo "ulimit -SHn 102400" >> /etc/rc.local
fi

#disable ipv6
cat << EOF
+---------------------------------+
| === Welcome to Disable IPV6 === |
+---------------------------------+
EOF
if ! grep -q "Disable IPV6" /etc/modprobe.conf;then
    echo "#####isable IPV6#####" >> /etc/modprobe.conf
    echo "alias net-pf-10 off" >> /etc/modprobe.conf
    echo "alias ipv6 off" >> /etc/modprobe.conf
fi
/sbin/chkconfig --level 35 ip6tables off
echo "ipv6 is disabled!"

#disable selinux
sed -i '/SELINUX/s/enforcing/disabled/' /etc/selinux/config
echo "selinux is disabled,you must reboot!"

#vim
sed -i "8 s/^/alias vi=vim/" /root/.bashrc
if ! grep -q "syntax on" /root/.vimrc;then
echo 'syntax on' >> /root/.vimrc
fi

#zh_cn
#sed -i -e 's/^LANG=.*/LANG=zh_CN.UTF-8/' /etc/sysconfig/i18n


#init_ssh
ssh_cf="/etc/ssh/sshd_config" 
sed -i "s/#UseDNS yes/UseDNS no/" $ssh_cf
#client
service sshd restart
echo "ssh is init is ok.............."


#tunoff services
#--------------------------------------------------------------------------------
cat << EOF
+--------------------------------------------------------------+
|         === Welcome to Tunoff services ===                   |
+--------------------------------------------------------------+
EOF
#---------------------------------------------------------------------------------
for i in `ls /etc/rc3.d/S*|grep -v 'local'`
do
    CURSRV=`echo $i|cut -c 15-`
    echo $CURSRV
    case $CURSRV in
        crond | network | sshd | rsyslog | salt-minion | zabbix-agent )
        echo "Base services, Skip!"
        ;;
        *)
        echo "change $CURSRV to off"
        chkconfig --level 235 $CURSRV off
        service $CURSRV stop
        ;;
    esac
done
echo "service is init is ok.............."

if ! grep -q "add kernel optimize" /etc/sysctl.conf;then
cat >> /etc/sysctl.conf << EOF
#######add kernel optimize###########
net.ipv4.ip_forward = 0
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.default.accept_source_route = 0
kernel.sysrq = 0
kernel.core_uses_pid = 1
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_synack_retries = 1
net.ipv4.tcp_syn_retries = 1
#net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_tw_reuse = 1
vm.swappiness = 0
net.ipv4.ip_local_port_range="1024 65530"
net.ipv4.tcp_fin_timeout = 3
net.ipv4.ip_nonlocal_bind=1
net.ipv4.tcp_keepalive_intvl = 20
net.ipv4.tcp_keepalive_probes = 3
net.ipv4.tcp_keepalive_time = 60
EOF
fi

/sbin/sysctl -p > /dev/null 2>&1
echo "sysctl set OK!!"

**Comment by chixueli** [comment]
第二种 方法是在 Jmeter 设置每秒钟发送数据包的数量，例如 5~10万

**Comment by yu285** [comment]
RPC 模块内部有一个 session 的 ID Pool，无法申请客户端或服务端 ID 时，代表 ID 用完了，也就是链接过多。此时返回 0x8000000a （Number of sessions reached limit）这个错误，客户端可以按情况处理，如果是写入，可以延迟一定时间后再次写入即可。

相当于提示，而并非错误。

**Comment by chixueli** [comment]
如果是写入，可以延迟一定时间后再次写入即可。我认为还是性能和处理能力的问题，会对物联网业务造成一定的影响，这是服务器端的程序，不应该有这样的问题，不是提示就解决的，还是真正从设计去处理
这样就违背Tdengine的设计原则，应该实时处理用户的大容量，高并发，高性能
还是程序设计欠缺的地方。
迟学礼

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Yu ***@***.***>
发送时间: 2021年4月22日 19:22
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [taosdata/TDengine] Number of sessions reached limit (#5478)


RPC 模块内部有一个 session 的 ID Pool，无法申请客户端或服务端 ID 时，代表 ID 用完了，也就是链接过多。此时返回 0x8000000a （Number of sessions reached limit）这个错误，客户端可以按情况处理，如果是写入，可以延迟一定时间后再次写入即可。

相当于提示，而并非错误。

―

**Comment by stephenkgu** [comment]
session 这个和两个实际因素有关系：所用集群的处理速度和你配置的 session 容量，通过参数 maxConnections 可以配置，但是这个最大值是10万，在这个具体的压测场景中，需要修正一下测试方法，可以采用多进程的方式，单个进程使用最大值估计也会出现这个错误码。
如果确定自己的客户端确实配置相当高，可以重新改下这个最大值。
50万测点的实际场景中是不会出现这个问题的，这50万个测点不会在一个进程里。

**Comment by chixueli** [comment]
我认为是两个维度 一是 持续不间断的处理消息量 是否平稳，第二是 并发连接数，并发连接 不需要50万 需要的是稳定 ，在性能测试要平稳不能是心电图似的波峰波谷起伏大

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Minglei Jin ***@***.***>
发送时间: Friday, April 23, 2021 11:03:02 AM
收件人: taosdata/TDengine ***@***.***>
抄送: chixueli ***@***.***>; Comment ***@***.***>
主题: Re: [taosdata/TDengine] Number of sessions reached limit (#5478)


session 这个和两个实际因素有关系：所用集群的处理速度和你配置的 session 容量，通过参数 maxConnections 可以配置，但是这个最大值是10万，在这个具体的压测场景中，需要修正一下测试方法，可以采用多进程的方式，单个进程使用最大值估计也会出现这个错误码。
如果确定自己的客户端确实配置相当高，可以重新改下这个最大值。
50万测点的实际场景中是不会出现这个问题的，这50万个测点不会在一个进程里。

―
