### ISSUE TITLE
2.0.12 data insertion exception

### ISSUE THREAD

**Issue by Lao-Zhong** [taosdata/TDengine#5480]
**Bug Description**
Ubuntu18.04，Python 3.6.9 ，taos 2.0.12
RESTful Connector 或 Python Connector的方式写入历史数据，时不时会报Syntax error in SQL，但已确认SQL语句是正确的；
如：
"""
IMPORT INTO bohai.g54190104759 (ts, dt, latitude, longitude, speed, course, elev, mcc, mnc, bs, genre) 
USING bohai.locators TAGS('54190104759', '{"ACC": "11", "GPS_STATE": "1", "LAT": "0", "LNG": "0", "RELAY": "0", "flag": 1, "GPS": "1", "BD": "1", "GLONASS": "0", "GALILEO": "0", "MOVE": 1, "VOLTAGE": 0, "CURRENT": 0, "POWER": 100, "BATTERY_POWER": 100, "DORMANT": 9, "POWER_STATE": 0, "updateTime": "2021-03-18 11:13:53"}')
VALUES ('2021-03-18 11:13:50', '2021-03-18 11:13:50', 47.325467, 123.152155, 3.8, 66, 0, 460, 0, '{"total": 0, "baseStation": []}', 0);
"""
错误信息如下：
[ERROR][2021-03-18 11:13:57,932]:apps:[executeSQL]:[32] >>> syntax error near '2021-03-18 11:13:50', '2021-03-18 11:13:50', 47.325467, 123.152' () expected)
taos.error.ProgrammingError: syntax error near '2021-03-18 11:13:50', '2021-03-18 11:13:50', 47.325467, 123.152' () expected)

taosdlog.1的错误日志：
0x7fbd2f9d7700 TSC ERROR 0x7fb468d30150 async insert parse error, code:Syntax error in SQL
0x7fbd2f9d7700 TSC ERROR 0x7fb468d30150 add into queued async res, code:Syntax error in SQL

**Comment by yu285** [comment]
请添加我的微信：15652223354讨论具体细节。

**Comment by yu285** [comment]
现已更新至18
