### ISSUE TITLE
need support connection by domain name

### ISSUE THREAD

**Issue by webclerk** [taosdata/TDengine#549]
I'm using TDengine for this use case: 
try to using client connect the server by domain name, but failed.

I want TDengine to be able to do support connection by domain name.

**Comment by guanshengliang** [comment]
Ok, we will put it into the R&D plan.
It can be released in early November

**Comment by webclerk** [comment]
thanks a lot.

**Comment by guanshengliang** [comment]
Version 2.0 supports fqdn, you can download and test

**Comment by guanshengliang** [comment]
This issue has been resolved, and this issue has not been replied for a long time, so close it
