### ISSUE TITLE
python connector problem 

### ISSUE THREAD

**Issue by chaoji90** [taosdata/TDengine#5514]
**Bug Description**
运行如下代码连接数据库服务taosd

```
import os
import taos
import multiprocessing as mp

conn = taos.connect(host='taosd', user="root", password="taosdata", config="/etc/taos")

c1 = conn.cursor()
conn.close()

def writeDb():
    conn = taos.connect(host='taosd', user="root", password="taosdata", config="/etc/taos")
    c1 = conn.cursor()
    print('Child Process id : %s, Parent Process id : %s' % (os.getpid(), os.getppid()))
    conn.close()

pool = mp.Pool(processes=10)
[pool.apply(writeDb) for _ in range(10)]
```

程序在writeDb()的taos.connect()语句完全阻塞，这个多进程用法有问题么？还是说python连接器暂不支持多进程？

**Comment by sangshuduo** [comment]
进程阻塞不是因为你用了 pool.apply 吗？

**Comment by chaoji90** [comment]
> 进程阻塞不是因为你用了 pool.apply 吗？

我理解pool.apply后会阻塞父进程，等待子进程执行结束。
`pool.apply(writeDb) for _ in range(10)`
依次启动10个子进分别运行writeDb。
当前程序阻塞在def writeDb()中的语句
`conn = taos.connect(host='taosd', user="root", password="taosdata", config="/etc/taos")`

请问子进程在执行connect为何会阻塞？什么情况下taos.connect会阻塞？

**Comment by chaoji90** [comment]
> 进程阻塞不是因为你用了 pool.apply 吗？

如果将
`[pool.apply(writeDb) for _ in range(10)]`
修改为
`[pool.apply_async(writeDb) for _ in range(10)]`
10个子进程全部启动，并且全部阻塞在了def writeDb中的
`conn = taos.connect(host='taosd', user="root", password="taosdata", config="/etc/taos")`
代码如下
`import os
import taos
import multiprocessing as mp

conn = taos.connect(host='taosd', user="root", password="taosdata", config="/etc/taos")

c1 = conn.cursor()
conn.close()

def writeDb():
    print('enter')
    conn = taos.connect(host='taosd', user="root", password="taosdata", config="/etc/taos")
    c1 = conn.cursor()
    print('Child Process id : %s, Parent Process id : %s' % (os.getpid(), os.getppid()))
    conn.close()

pool = mp.Pool(processes=10)
[pool.apply_async(writeDb) for _ in range(10)]
pool.close()
pool.join()`

**Comment by chaoji90** [comment]
运行如下程序，则连接无问题，是连接器对mp多进程支持的问题吧
```
import os
import taos
import multiprocessing as mp

#单独启动一个进程进行bootstrap来测试
def bootstrap():
    conn = taos.connect(host='taosd', user="root", password="taosdata", config="/etc/taos")

    c1 = conn.cursor()
    conn.close()

def writeDb():
    print('enter')
    conn = taos.connect(host='taosd', user="root", password="taosdata", config="/etc/taos")
    c1 = conn.cursor()
    print('Child Process id : %s, Parent Process id : %s' % (os.getpid(), os.getppid()))
    conn.close()

p = mp.Process(target=bootstrap)
p.start()
p.join()

pool = mp.Pool(processes=5)
[pool.apply_async(writeDb) for _ in range(10)]
pool.close()
pool.join()
```

**Comment by sangshuduo** [comment]
你试试 subprocess https://stackoverflow.com/questions/2276117/python-multiprocessing-process-vs-standalone-python-vm

**Comment by fenghuazzm** [comment]
This issue was closed because it has been inactive for too many days.
