### ISSUE TITLE
 After importing plug-in, "HTTP Error Bad Gateway" error happened during Grafana configuration

### ISSUE THREAD

**Issue by litstockz** [taosdata/TDengine#5517]
grafana7.2和Tdengine2.0.17.0都是容器版，复制插件后，还是失败，出现HTTP Error Bad Gateway
![image](https://user-images.githubusercontent.com/10656412/111903993-88785800-8a7f-11eb-9148-a1315b5a544f.png)

**Comment by yu285** [comment]
咱们这边的fqdn是否可以确保正常连接访问？端口是确定可以telnet通的吗？

**Comment by litstockz** [comment]
@yu285 
![image](https://user-images.githubusercontent.com/10656412/111932201-e8124a00-8af7-11eb-8ead-05ab5e4295dc.png)
![image](https://user-images.githubusercontent.com/10656412/111932218-f19bb200-8af7-11eb-9a01-8f273a053532.png)
然后我按官网文件绑定端口
docker run -d -v /etc/taos:/etc/taos -p 6030:6030 -p 6035:6035 -p 6041:6041 -p 6030-6040:6030-6040/udp tdengine/tdengine:2.0.17.0  
报错
> docker: Error response from daemon: driver failed programming external connectivity on endpoint fervent_wright (087d79762305c56a70787b35d48f20aa916c8468110f7e20005bbe4dcccaa11d): Error starting userland proxy: listen tcp4 0.0.0.0:6041: bind: address already in use.

**Comment by yu285** [comment]
两个docker中间要隔着虚拟机通信，不是很方便诊断。建议微信交流15652223354
