### ISSUE TITLE
java.sql.SQLException: TDengine Error: failed to connect to server

### ISSUE THREAD

**Issue by linzhenyao** [taosdata/TDengine#553]
踩过各种环境问题，终于来到这里 然后死活链不上 用http://****/db?user=root&password=taosdata" 服务器提示ERROR HTP context:0x7f609ef65010, fd:22, ip:180.139.214.209:41231, code:404, error:1002:http url is not support

**Comment by guanshengliang** [comment]
` curl -u root:taosdata -d  'show databases;' 127.0.0.1:6020/restful`

**Comment by guanshengliang** [comment]
![image](https://user-images.githubusercontent.com/28882257/65491936-9c6ee800-dee2-11e9-83a7-81eca8867c62.png)

**Comment by linzhenyao** [comment]
![image](https://user-images.githubusercontent.com/22067059/65671232-72036300-e079-11e9-8bb7-063e935f7ccb.png)

**Comment by linzhenyao** [comment]
是window开发环境下不能连Linux环境上的TDengine吗

**Comment by jiaoyilun** [comment]
> 是window开发环境下不能连Linux环境上的TDengine吗

我win10环境， 本机docker启动了个服务，windows下死活连不上，把服务部署在centos下，windows连上了

**Comment by guanshengliang** [comment]
TDengine用了很多端口，docker需要进行端口映射才可以
