### ISSUE TITLE
spark Invalid Resultset pointer!

### ISSUE THREAD

**Issue by zengzeng-x** [taosdata/TDengine#5544]
用spark JDBC并行去查询sql报错 

报错如下：
<img width="1326" alt="WeChatWorkScreenshot_a132e190-bc6f-45e3-a89a-9be3341c3a62" src="https://user-images.githubusercontent.com/79821027/112106115-343cb780-8be8-11eb-8668-30ca550a1c69.png">

spark3.1 版本
Tdengine 2.0.18 版本
taos-jdbcDirver 2.0.22版本

**Comment by cpvmrd** [comment]
日志检查过了吗？

**Comment by fenghuazzm** [comment]
This issue was closed because it has been inactive for too many days.
