### ISSUE TITLE
too many msg:10017 in vwqueue, flow control....

### ISSUE THREAD

**Issue by peterchenhdu** [taosdata/TDengine#5549]
执行批量插入的时候，一直报如下错误，请问是什么原因，过一段时间又好了

03/23 15:44:03.407365 0x7f00142b9700 VND vgId:3, commit over, fver:2784472 vver:2786150
03/23 15:44:03.414533 0x7f00142b9700 WAL vgId:3, file:/data/taos/vnode/vnode3/wal/wal1647, it is removed
03/23 15:44:03.415071 0x7effbb7f6700 VND vgId:3, too many msg:10014 in vwqueue, flow control 13ms
03/23 15:44:03.415476 0x7f00142b9700 VND vgId:3, successed to write /data/taos/vnode/vnode3/version.json, fver:2784472
03/23 15:44:03.428219 0x7effbb7f6700 VND vgId:3, too many msg:10015 in vwqueue, flow control 13ms
03/23 15:44:03.441350 0x7effbb7f6700 VND vgId:3, too many msg:10016 in vwqueue, flow control 13ms
03/23 15:44:03.454490 0x7effbb7f6700 VND vgId:3, too many msg:10017 in vwqueue, flow control 13ms
03/23 15:44:03.467638 0x7effbb7f6700 VND vgId:3, too many msg:10018 in vwqueue, flow control 13ms
03/23 15:44:03.480772 0x7effbb7f6700 VND vgId:3, too many msg:10019 in vwqueue, flow control 13ms
03/23 15:44:03.493926 0x7effbb7f6700 VND vgId:3, too many msg:10020 in vwqueue, flow control 13ms
03/23 15:44:03.507068 0x7effbb7f6700 VND vgId:3, too many msg:10021 in vwqueue, flow control 13ms
03/23 15:44:03.520215 0x7effbb7f6700 VND vgId:3, too many msg:10022 in vwqueue, flow control 13ms
03/23 15:44:03.533342 0x7effbb7f6700 VND vgId:3, too many msg:10023 in vwqueue, flow control 13ms
03/23 15:44:03.546464 0x7effbb7f6700 VND vgId:3, too many msg:10024 in vwqueue, flow control 13ms
03/23 15:44:03.559599 0x7effbb7f6700 VND vgId:3, too many msg:10025 in vwqueue, flow control 13ms
03/23 15:44:03.572730 0x7effbb7f6700 VND vgId:3, too many msg:10026 in vwqueue, flow control 13ms
03/23 15:44:03.585865 0x7effbb7f6700 VND vgId:3, too many msg:10027 in vwqueue, flow control 13ms
03/23 15:44:03.598993 0x7effbb7f6700 VND vgId:3, too many msg:10028 in vwqueue, flow control 13ms
03/23 15:44:03.600795 0x7effbbff7700 VND vgId:3, start commit, fver:2784472 vver:2786150
03/23 15:44:03.600810 0x7effbbff7700 WAL vgId:3, file:/data/taos/vnode/vnode3/wal/wal1648, it is closed while renew
03/23 15:44:03.601965 0x7effbbff7700 WAL vgId:3, file:/data/taos/vnode/vnode3/wal/wal1649, it is created and open while renew
03/23 15:44:03.601991 0x7f00142b9700 TDB vgId:3 start to commit! keyFirst 1514736000000 keyLast 1544706000000 numOfRows 1676343 meta rows: 0

03/23 15:53:22.965275 0x7f00045b9700 RPC ERROR SHELL 0x7f002011f8b8 read error, leftLen:20050 retLen:-1 FD:0x7effb0000ac0
03/23 15:53:22.966288 0x7f00035b7700 RPC ERROR SHELL 0x7f002011f740 read error, leftLen:20050 retLen:-1 FD:0x7effb0000c00
03/23 15:53:22.968193 0x7f00142b9700 WAL vgId:3, file:/data/taos/vnode/vnode3/wal/wal1928, it is removed
03/23 15:53:22.969700 0x7f00142b9700 VND vgId:3, successed to write /data/taos/vnode/vnode3/version.json, fver:3255990
03/23 15:53:22.976681 0x7f00035b7700 RPC ERROR SHELL 0x7f002011f5c8 read error, leftLen:20050 retLen:-1 FD:0x7effb0000a00
03/23 15:53:22.980225 0x7f00045b9700 RPC ERROR SHELL (nil) read error, leftLen:20070 retLen:-1 FD:0x7effb0000ac0
03/23 15:53:22.981948 0x7f00035b7700 RPC ERROR SHELL (nil) read error, leftLen:20070 retLen:-1 FD:0x7effb0000900
03/23 15:53:22.994807 0x7f00045b9700 RPC ERROR SHELL 0x7f002011fe98 read error, leftLen:20050 retLen:-1 FD:0x7effb0000900
03/23 15:53:23.001740 0x7f0003db8700 RPC ERROR SHELL 0x7f002011fba8 read error, leftLen:20050 retLen:-1 FD:0x7effb0000cc0
03/23 15:53:23.006031 0x7f00035b7700 RPC ERROR SHELL (nil) read error, leftLen:20070 retLen:-1 FD:0x7effb0000900
03/23 15:53:23.007994 0x7f0002db6700 RPC ERROR SHELL (nil) read error, leftLen:20070 retLen:-1 FD:0x7effb0000900
03/23 15:53:23.008619 0x7f00045b9700 RPC ERROR SHELL (nil) read error, leftLen:20070 retLen:-1 FD:0x7effb0000ac0
03/23 15:53:23.012061 0x7f00035b7700 RPC ERROR SHELL 0x7f002011fa30 read error, leftLen:20050 retLen:-1 FD:0x7effb0000a00
03/23 15:53:23.016398 0x7f0003db8700 RPC ERROR SHELL 0x7f0020120010 read error, leftLen:20050 retLen:-1 FD:0x7effb0000cc0
03/23 15:53:23.022325 0x7f0003db8700 RPC ERROR SHELL (nil) read error, leftLen:20070 retLen:-1 FD:0x7effb0000cc0
03/23 15:53:23.024917 0x7f00035b7700 RPC ERROR SHELL (nil) read error, leftLen:20070 retLen:-1 FD:0x7effb0000cc0
03/23 15:53:23.025177 0x7f0002db6700 RPC ERROR SHELL (nil) read error, leftLen:20070 retLen:-1 FD:0x7effb0000a00
03/23 15:53:23.035293 0x7f0002db6700 RPC ERROR SHELL (nil) read error, leftLen:20070 retLen:-1 FD:0x7effb0000900

**Comment by cpvmrd** [comment]
We will check it.

**Comment by yu285** [comment]
您好，此类问题可以添加微信15652223354，便于提供其他信息，从而定位问题
