### ISSUE TITLE
After alter table add column ，TDengine  super table couldn't  be inserted with column's name

### ISSUE THREAD

**Issue by jadedrip** [taosdata/TDengine#5557]
**Bug Description**
alter table add column 添加字段以后，不能通过 insert into sos_xxx(ts, desc_) 这样带 字段名形式的 sql 来写入数据，会报各种 sql 解析错误

**To Reproduce**

step1: 确认表
taos> describe sos;
             Field              |         Type         |   Length    |   Note   |
=================================================================================
 ts                             | TIMESTAMP            |           8 |          |
 desc_                          | NCHAR                |         255 |          |
 tel_device_id                  | BINARY               |          36 | TAG      |
Query OK, 3 row(s) in set (0.036000s)

taos> insert into sos_86566804029644x(ts, desc_) using sos tags('86566804029644x') VALUES(1616567337000,'T1');
Query OK, 1 of 1 row(s) in database (0.110000s)

step2: 加字段
taos> alter table sos add column big_ nchar(255);
Query OK, 0 of 0 row(s) in database (0.097000s)

taos> insert into sos_86566804029644x(ts, desc_) using sos tags('86566804029644x') VALUES(1616567337000,'T1');

**DB error: invalid SQL: '865668(ts, desc_) values(1616567337000,'T1');' (string data overflow) (0.004000s)**

去除字段表后写入正常

taos> insert into sos_86566804029644x using sos tags('86566804029644x') VALUES(1616567337000,'T1','');
Query OK, 1 of 1 row(s) in database (0.005000s)

**Expected Behavior**
能通过带字段的 insert 写入数据

**Screenshots**

**Environment (please complete the following information):**
 - OS: CentOS 7.0
 - Memory, CPU, current Disk Space
 - TDengine Version 2.0.17

**Additional Context**

**Comment by yu285** [comment]
已提交问题，烦请耐心等待

**Comment by yu285** [comment]
该问题已经在TDengine2.0.19中修复。
