### ISSUE TITLE
How does a TDengine cluster provide a highly available connection way？

### ISSUE THREAD

**Issue by yakir-Yang** [taosdata/TDengine#5560]
集群对外提供的连接方式如何做到高可用？

比如我有三台机器：
 - qat-tdengine-1
 - qat-tdengine-2
 - qat-tdengine-3

应用去连接 tdengine 必须有个连接地址，如果是 qat-tdengine-1:6030 ，一旦 qat-tdengine-1 机器宕机了，外部应用正好发起了新的连接，这时候不就无法连接到 tdengine 集群了吗？（因为这个IP qat-tdengine-1 不可达了）

我尝试过在 TDengine 集群外层，加一个 VIP + 负载均衡，但是用这种方式无法正常连接到 TDengine 集群。

**Comment by yu285** [comment]
TDengine集群可以容纳单个、多个甚至几千个数据节点，应用只需要向集群中任何一个数据节点发起连接即可。连接时，需要提供的网络参数是一数据节点的End Point(FQDN加配置的端口号）。


至于负载均衡还是连接不到，这个可能是你挂掉的这个节点已经导致集群不可用了，并不是连接问题，这个要视具体情况而定，建议您提供报错截图以供参考。

**Comment by yakir-Yang** [comment]
连接时，需要提供的网络参数是一数据节点的End Point(FQDN加配置的端口号）。
----------------

谢谢回复，先看第一个问题。

如果集群对外暴露的连接方式（既客户端连接时的网络参数），是通过单一一个数据节点 Endpoint。当这个数据节点发生宕机后，客户端就无法正常新建连接了，会有这个问题吗？我理解只有客户端连接的 网络参数，支持集群中多个数据节点的 Endpoint 配置（"qat-tdengine-1:6030,qat-tdengine-2:6030,qat-tdengine-3:6030"） ，才有可能避免这个问题。

**Comment by sunshine-smdbs** [comment]
> 连接时，需要提供的网络参数是一数据节点的End Point(FQDN加配置的端口号）。
> 
> 谢谢回复，先看第一个问题。
> 
> 如果集群对外暴露的连接方式（既客户端连接时的网络参数），是通过单一一个数据节点 Endpoint。当这个数据节点发生宕机后，客户端就无法正常新建连接了，会有这个问题吗？我理解只有客户端连接的 网络参数，支持集群中多个数据节点的 Endpoint 配置（"qat-tdengine-1:6030,qat-tdengine-2:6030,qat-tdengine-3:6030"） ，才有可能避免这个问题。

一般来说，集群不适合对外暴露的，因为通讯模型限制了。而且安全问题也是个非常个性化的问题。
连接的时候，可以配置多个ep，firstEp, secondEp, thirdEp，用于候选。

**Comment by yakir-Yang** [comment]
> > 连接时，需要提供的网络参数是一数据节点的End Point(FQDN加配置的端口号）。
> > 谢谢回复，先看第一个问题。
> > 如果集群对外暴露的连接方式（既客户端连接时的网络参数），是通过单一一个数据节点 Endpoint。当这个数据节点发生宕机后，客户端就无法正常新建连接了，会有这个问题吗？我理解只有客户端连接的 网络参数，支持集群中多个数据节点的 Endpoint 配置（"qat-tdengine-1:6030,qat-tdengine-2:6030,qat-tdengine-3:6030"） ，才有可能避免这个问题。
> 
> 一般来说，集群不适合对外暴露的，因为通讯模型限制了。而且安全问题也是个非常个性化的问题。

我指仅是内网暴露的范畴，给业务程序通过 内网地址 连接到 tdengine 集群，并不考虑对公网暴露进而引发的安全性风险。

> 连接的时候，可以配置多个ep，firstEp, secondEp, thirdEp，用于候选。

请教下如何在 客户端 实现配置多个 ep ，以 C 客户端为例，taos_connect 感觉只能配置单个 IP 。

`DLL_EXPORT TAOS *taos_connect(const char *ip, const char *user, const char *pass, const char *db, uint16_t port);`

**Comment by yu285** [comment]
建议您把连接信息写到配置层面而不是应用程序里面。这样，初次访问集群的时候客户端会去读取taos.cfg里的firstEP参数并访问，firstEP如果挂掉了，会去读取secondEP，这样完成高可用。之后，每个节点就都会拥有整个集群的信息，这样当某个管理节点挂掉，便会自动切换到另一台上。

我们是十分不建议在应用程序端指定ip的，写死ip并不利于维护，也不利于应对意外情况的发生。

**Comment by yu285** [comment]
> > 一般来说，集群不适合对外暴露的，因为通讯模型限制了。而且安全问题也是个非常个性化的问题。
> 
> 我指仅是内网暴露的范畴，给业务程序通过 内网地址 连接到 tdengine 集群，并不考虑对公网暴露进而引发的安全性风险。
> 
> > 连接的时候，可以配置多个ep，firstEp, secondEp, thirdEp，用于候选。
> 
> 请教下如何在 客户端 实现配置多个 ep ，以 C 客户端为例，taos_connect 感觉只能配置单个 IP 。
> 
> `DLL_EXPORT TAOS *taos_connect(const char *ip, const char *user, const char *pass, const char *db, uint16_t port);`

建议您把连接信息写到配置层面而不是应用程序里面。这样，初次访问集群的时候客户端会去读取taos.cfg里的firstEP参数并访问，firstEP如果挂掉了，会去读取secondEP，这样完成高可用。之后，每个节点就都会拥有整个集群的信息，这样当某个管理节点挂掉，便会自动切换到另一台上。

我们是十分不建议在应用程序端指定ip的，写死ip并不利于维护，也不利于应对意外情况的发生。

**Comment by yakir-Yang** [comment]
以 taosimport 压测工具为例，它如果希望有个高可靠的方式，连接 tdegnine 集群，有啥办法吗？（回复里面提的 taos.cfg 应该是集群的配置，在客户端应该没有才对）。现在 taosimport 只能把 host 指定为单个 tdengine 节点，如果这个节点宕机了，那 taosimport 就无法连接 tdengine 集群了。

**Comment by yu285** [comment]
是这样，你担心的是在指定连接ip的时候这个节点挂掉。

但是实际使用的时候，我们是不建议用这种方式连接集群的。

我们可以把你想连的服务器写到taos.cfg的firstEP参数里面，然后secondEP作为backup。

在默认连接的时候他就会去连接firstEP，当firstEP出现你说的问题之后，他会自动去找secondEP。

从而完成你说的高可用

**Comment by yakir-Yang** [comment]
客户端也支持从本地的 /etc/taos/taos.cfg 中读取集群的配置，只要在对应 taos.cfg 中配置对应的 firstEp & secondEp 即可，亲验可用

**Comment by zhouyf605** [comment]
> 
还有thirdEp ？ 从来没见过这个参数

**Comment by matchmen** [comment]
> 发生

使用的JDBC-JNI吗？JDBC-RESFUL怎么配置呢

**Comment by moonService** [comment]
jdbc驱动怎么指定taos.cfg

**Comment by zhouyf605** [comment]
https://docs.taosdata.com/reference/connector/java    官方文档  有讲解的
