### ISSUE TITLE
Question： Unable to resolve FQDN 

### ISSUE THREAD

**Issue by RedKeys** [taosdata/TDengine#5580]
开发机是win10的
TDengine 服务器 是在这个开发机的 VMware 上装的 **ubuntu 18.0.4 - server 64 位**
TDengine 版本是 **2.0.18**
两台机器是 不同的 独立ip：win10是**192.168.101.9**，TDengine 服务器是**192.168.101.37**
开发机node.js版本 **12.21.0**

win10 按照官方文档 配置了 hosts 文件，并且能ping通，但是还会报错：Unable to resolve FQDN
请问这个还需要怎么处理?

![image](https://user-images.githubusercontent.com/35087454/112565230-af37e500-8e17-11eb-95d9-f15af070b4f6.png)

**Comment by yu285** [comment]
6030的端口有没有telnet过？

**Comment by RedKeys** [comment]
6030 端口是通过的。

**Comment by RedKeys** [comment]
大神们有什么方法没？卡在这儿啦！！！
JAVA 也报这个，客户端也报这个。
![image](https://user-images.githubusercontent.com/35087454/112599222-9f85c400-8e4a-11eb-8323-0051a9b7c0ac.png)

**Comment by yu285** [comment]
> 大神们有什么方法没？卡在这儿啦！！！
> JAVA 也报这个，客户端也报这个。
> ![image](https://user-images.githubusercontent.com/35087454/112599222-9f85c400-8e4a-11eb-8323-0051a9b7c0ac.png)

请添加微信15652223354帮您看看

**Comment by RedKeys** [comment]
感谢贵公司的技术致辞！！！！
解决方法：
这个问题是因为 hosts 文件里的 主机名配置错误，应该使用 TDengine 服务器的主机名，
ubuntu 主机名通过 hostname 命令查看
![image](https://user-images.githubusercontent.com/35087454/112607479-3b67fd80-8e54-11eb-8d20-6162630d3e1a.png)
