### ISSUE TITLE
Error: /usr/local/koa2/node_modules/ref/build/Release/binding.node: invalid ELF

### ISSUE THREAD

**Issue by sexbee** [taosdata/TDengine#559]
/usr/local/koa2/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: /usr/local/koa2/node_modules/ref/build/Release/binding.node: invalid ELF header
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

**Comment by sexbee** [comment]
const taos = require('td-connector');
var conn = taos.connect({host:"127.0.0.1", user:"xxxx", password:"xxxx", config:"/etc/taos",port:22});
 var c1 = conn.cursor();

**Comment by StoneT2000** [comment]
Please tell me the following to help me debug:
What version of Node js are you using?
Client version of taos? What system?
What version of gcc or whichever c/c++ compiler you are using?
Python version?

**Comment by sexbee** [comment]
ubuntu 19.06 nodejs 10.6.1 
Welcome to the TDengine shell, client version:1.6.2.0  server version:1.6.2.0

**Comment by sexbee** [comment]
GNU Make 4.2.1
为 x86_64-pc-linux-gnu 编译
//
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu

**Comment by sexbee** [comment]
Python version 2.7.16

**Comment by StoneT2000** [comment]
@sexbee
Try the command
‘npm rebuild’ in the directory containing the node-modules folder where contains ‘node-gyp’ amongst other modules. Then test the starter code again and let me know what happens.

Make sure taos is running and node-gyp is installed
