### ISSUE TITLE
Data resampling based on column criteria 

### ISSUE THREAD

**Issue by zzeric** [taosdata/TDengine#5590]
现在interval只支持对时间的重采样，能否增加对某列数值的变化幅度进行重采样，比如说价格每变化超过10元重采样一次，或者价格每变化超过1%，这个对金融数据很有意义。

**Comment by cpvmrd** [comment]
收到，感谢建议，我们内部讨论一下。

**Comment by cpvmrd** [comment]
This issue was closed because it has been inactive for too many days.
