### ISSUE TITLE
TDengine  client connection high available ( jdbc-jni )

### ISSUE THREAD

**Issue by stringhuang** [taosdata/TDengine#5614]
目前遇到问题：【Tdengine 客户端连接 jdbc-jni 高可用】

我现在使用开源版Tdengine 2.0.16.0，总共3个物理节点，运行3个dnoe，3个monde，1个arbitrator。

我的数据库副本设置为2，当其中一个dnode offline的时候，集群依然是高可用。

我现在遇到的问题是，如何做客户端连接的高可用，我没有选择jdbc-restful方案，因为他和mybatis-plus结合得不好，也考虑到写入性能。所以，我选择使用jdbc-jni方式。

我在3个物理节点外面包装一层haproxy监听端口16030，然后再把流量转发到物理节点的6030，但是，通过16030进行连接，报错” aos connect failed, reason: Unable to establish connection.”。

我的haproxy主要配置如下： frontend taosd mode tcp bind *:16030 default_backend taosd maxconn 50000 timeout client 600s

backend taosd mode tcp # 模式tcp balance roundrobin # 采用轮询的负载算法 timeout server 40s timeout check 4000 server node-1 10.99.11.220:6030 check inter 30s fall 2 rise 5 weight 1 maxconn 2000 server node-2 10.99.11.221:6030 check inter 30s fall 2 rise 5 weight 1 maxconn 2000 server node-3 10.99.11.222:6030 check inter 30s fall 2 rise 5 weight 1 maxconn 2000

正常连接如下： taos -h 10.99.11.222 -u root -ptaosdata -P 6030

Welcome to the TDengine shell from Linux, Client Version:2.0.16.0 Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.

taos> exit

报错连接如下： taos -h 10.99.11.222 -u root -ptaosdata -P 16030

Welcome to the TDengine shell from Linux, Client Version:2.0.16.0 Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.

taos connect failed, reason: Unable to establish connection.

我想请教，是否tdengine client不支持外层包裹负载均衡进行连接？

**Comment by yakir-Yang** [comment]
我和你问了同一个问题：https://github.com/taosdata/TDengine/issues/5560

**Comment by yu285** [comment]
是这样，您担心的是在客户端指定连接ip的时候这个节点挂掉。

但是实际使用的时候，我们是不建议用这种方式连接集群的。

我们可以把你想连的服务器写到客户端的taos.cfg的firstEP参数里面，然后secondEP作为backup。

在默认连接的时候他就会去连接firstEP，当firstEP出现你说的问题之后，他会自动去找secondEP。

从而完成你说的高可用。

这样您是无需配置外层负载均衡的。

**Comment by yakir-Yang** [comment]
客户端也支持从本地的 /etc/taos/taos.cfg 中读取集群的配置，只要在对应 taos.cfg 中配置对应的 firstEp & secondEp 即可，亲验可用

**Comment by yakir-Yang** [comment]
> 我想请教，是否tdengine client不支持外层包裹负载均衡进行连接？

**Comment by yu285** [comment]
是这样，您担心的是在客户端指定连接ip的时候这个节点挂掉。

但是实际使用的时候，我们是不建议用这种方式连接集群的。

我们可以把你想连的服务器写到客户端的taos.cfg的firstEP参数里面，然后secondEP作为backup。

在默认连接的时候他就会去连接firstEP，当firstEP出现你说的问题之后，他会自动去找secondEP。

从而完成你说的高可用。

这样您是无需配置外层负载均衡的。

如果您想用网络负载均衡形成另一种高可用也是完全可以的，只要留意楼上所回答的注意事项即可。

**Comment by szlyunnan** [comment]
我知道不是使用ip, 使用的是fqdn; 就是想知道配置文件或者url的方式如何连接群集。
客户端是在容器里部署的, 而且使用的是配置中心; 可以不用taos.cfg文件吗？通过taos.cfg文件感觉不是很灵活。

**Comment by XW512** [comment]
> 我知道不是使用ip, 使用的是fqdn; 就是想知道配置文件或者url的方式如何连接群集。 客户端是在容器里部署的, 而且使用的是配置中心; 可以不用taos.cfg文件吗？通过taos.cfg文件感觉不是很灵活。
> 
> 就像连接kafka群集一样 kafka1:9092,kafka2:9092,kafka3:9092

你好，你最终的解决方案是什么？
