### ISSUE TITLE
use docker-compose to deploy tdengine:ERROR dnode:1, localEp is different from a5e27b397f1d:6030 in dnodeEps.json and need reconfigured

### ISSUE THREAD

**Issue by muphy1112** [taosdata/TDengine#5615]
每次在docker-compose.yml中修改了TDengine相关的信息就会启动不了TD容器（tdengine），每次都要将整个数据清空启动，这肯定不是长久的办法，数据会丢失

错误日志：
DND ERROR dnode:1, localEp is different from a5e27b397f1d:6030 in dnodeEps.json and need reconfigured
DND Failed to start TDengine, please check the log at:/var/log/taos

调查原因是因为容器ID改变导致，目前只能修改持久化配置中的一下文件实现，不过太过麻烦，有什么办法吗
mnode/wal/wal0
vnode/vnode2/config.json
dnode/dnodeEps.json
dnode/mnodeEpSet.json
![image](https://user-images.githubusercontent.com/34815400/112808656-cbec4b00-90ab-11eb-9985-caf64b14119a.png)

**Comment by yu285** [comment]
您好，我们的dockerid频繁改动的具体场景是什么呢？

**Comment by muphy1112** [comment]
目前只是需要对一些技术点做测试，测试过程中需要改端口，或者路径，也不是经常改

**Comment by yu285** [comment]
对于测试环境的这种偶发现象，暂时没办法优化，烦请理解哈。

**Comment by Archer1003** [comment]
容器 id 可以使用主机名称 hostname ，只需要在创建容器时给定容器名称。将dnodeEps.json 中 dnodeFqdn改为主机名称即可
