### ISSUE TITLE
Install the 2.0.16 version of the TDengine, report an error: taos connect failed, reason: Unable to establish connection.

### ISSUE THREAD

**Issue by chenyihongyi** [taosdata/TDengine#5619]
>

**Comment by chenyihongyi** [comment]
03/30 06:38:44.714515 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:38:53.815452 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:39:02.916899 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:39:11.977476 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:39:21.068600 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:39:30.140453 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:39:39.230180 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:39:48.314286 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:39:57.387192 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:40:06.471198 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:40:15.575450 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:40:24.690174 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:40:33.766448 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:40:42.878979 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:40:51.942976 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:41:01.028181 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:41:10.131476 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:41:19.266188 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:41:28.363445 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:41:37.470446 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:41:46.577362 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:41:55.651181 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:42:04.721376 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:42:13.795448 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:42:22.854184 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:42:31.926625 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:42:41.012208 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:42:50.075450 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:42:59.197193 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:43:08.292101 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:43:17.496182 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:43:26.590637 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:43:35.697196 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:43:44.770172 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:43:53.876214 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:44:03.006321 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:44:12.120450 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:44:21.205444 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection
03/30 06:44:30.274290 0x7f11ba708700 MON ERROR failed to connect to database, reason:Unable to establish connection

**Comment by yu285** [comment]
您好，对于配置问题请添加微信15652223354方便排查

**Comment by yu285** [comment]
您好，如果仍有问题，请联系。

该问题暂时关闭。
