### ISSUE TITLE
c1.execute('insert     这里的”‘“ 是单引号？

### ISSUE THREAD

**Issue by sexbee** [taosdata/TDengine#562]
//c1.execute('insert into db.weather values(' + insertData.join(',') + ' );');
    var query = c1.query('insert into db.weather values(?, ?, ?, ?, ?);').bind(insertData);
    query.execute();
  }
//////
c1.query('i       这里的”‘“ 是单引号？如何动态插入values  tags？

**Comment by sexbee** [comment]
看懂了，是ES5的拼接。不过 ' + insertData.join(',') + ' ) 之后，会不会把原先的int、bigint等转换成了字符串？

**Comment by fangpanpan** [comment]
是的，会将数值转成字符串拼成SQL语句。
