### ISSUE TITLE
When use  "where timestamp = xxx"，select  couldn't show up  result

### ISSUE THREAD

**Issue by nanjj** [taosdata/TDengine#5620]
```
taos> create database demo;
taos> use demo;
taos> create table speeds(ts timestamp, deleted_at timestamp, speed float);
Query OK, 0 of 0 row(s) in database (0.007847s)
taos> insert into speeds values(now, 1, 1.1);
Query OK, 1 of 1 row(s) in database (0.001762s)
taos> select * from speeds;
           ts            |       deleted_at        |        speed         |
===========================================================================
 2021-03-30 01:16:58.466 | 1970-01-01 00:00:00.001 |              1.10000 |
Query OK, 1 row(s) in set (0.002961s)
taos> select * from speeds where deleted_at =  1;
Query OK, 0 row(s) in set (0.003411s)  #!! 为啥为空？
taos> select * from speeds where deleted_at >= 1 and deleted_at <=1; 
           ts            |       deleted_at        |        speed         |
===========================================================================
 2021-03-30 01:16:58.466 | 1970-01-01 00:00:00.001 |              1.10000 |
Query OK, 1 row(s) in set (0.002912s)
```

client version and server version:
```
taos> select server_version();
 server_version() |
===================
 2.0.18.0         |
Query OK, 1 row(s) in set (0.000177s)

taos> select client_version();
 client_version() |
===================
 2.0.18.0         |
Query OK, 1 row(s) in set (0.000177s)
```
OS:
```
 cat /etc/os-release
NAME="EulerOS"
VERSION="2.0 (SP8)"
ID="euleros"
```

**Comment by yu285** [comment]
已经记录问题，烦请等待，多谢理解

**Comment by yu285** [comment]
> taos> create database demo;
> taos> use demo;
> taos> create table speeds(ts timestamp, deleted_at timestamp, speed float);
> Query OK, 0 of 0 row(s) in database (0.007847s)
> taos> insert into speeds values(now, 1, 1.1);
> Query OK, 1 of 1 row(s) in database (0.001762s)
> taos> select * from speeds;
>            ts            |       deleted_at        |        speed         |
> ===========================================================================
>  2021-03-30 01:16:58.466 | 1970-01-01 00:00:00.001 |              1.10000 |
> Query OK, 1 row(s) in set (0.002961s)
> taos> select * from speeds where deleted_at =  1;
> Query OK, 0 row(s) in set (0.003411s)  #!! 为啥为空？
> taos> select * from speeds where deleted_at >= 1 and deleted_at <=1; 
>            ts            |       deleted_at        |        speed         |
> ===========================================================================
>  2021-03-30 01:16:58.466 | 1970-01-01 00:00:00.001 |              1.10000 |
> Query OK, 1 row(s) in set (0.002912s)

请您提供一下数据库版本信息，以及操作系统信息。

**Comment by nanjj** [comment]
@yu285 database version has been provided above.

**Comment by yu285** [comment]
![image](https://user-images.githubusercontent.com/74105241/117434688-9155b800-af5f-11eb-8a1f-4a2364b09baa.png)
this issue has been fixed  now , u can upgrade your TDengine, thank u .
