### ISSUE TITLE
JNI result set is null

### ISSUE THREAD

**Issue by zengzeng-x** [taosdata/TDengine#5624]
Java 
JDBC 版本：taosjdbc-2.0.22
Tdengine 版本 2.0.18

执行SQL
SELECT ts as ts, tileid as tileId, lat as lat, lon as lon, altitude as altitude, gps as gps, gyro as gyro, fourwheels as fourwheels, speedpulse as speedpulse, gnssmeasurement as gnssmeasurement, vin as vin  FROM ecarx_ihu_can WHERE ts >= 1616169600000 AND ts <= 1616256000000 LIMIT 50000 OFFSET 3500000;

分页循环查询，
这个SQL 在控制台是可以执行

Tdengine 服务器没有报错信息
这是java JDBC报出的错。

<img width="1383" alt="e160f336-6ae3-4eb1-b5ba-cb7439c7fc17" src="https://user-images.githubusercontent.com/79821027/112929593-58017f80-914b-11eb-82bf-313c7d0415d8.png">

**Comment by cpvmrd** [comment]
@yu285 is helping to check it.

**Comment by yu285** [comment]
用户休假未归无法提供具体信息，并表示需要的话会再提。
