### ISSUE TITLE
Is there some SQL statements for performance analysis like 'SHOW PROCESSLIST'?

### ISSUE THREAD

**Issue by Jerry-Kwok** [taosdata/TDengine#5633]
Is there some SQL statements for performance analysis like 'SHOW PROCESSLIST'?
thx

**Comment by yu285** [comment]
We don't have that kind of tool currently, we are using the log under /var/log/taos  (default location ) to record 
CPU, memory, hard disk space, bandwidth, number of requests, disk I/O speed, slow queries, and other information.

**Comment by Jerry-Kwok** [comment]
Thank you for your response, but I don't find related info in the log files, could you tell me the key words of the performance parameters in the log files? thx

**Comment by yu285** [comment]
you could set parameter debugFlag  to 131（ERROR and WARNING） ,135（ ERROR and WARNING DEBUGGING）  143（  ERROR and WARNING DEBUGGING and TRACING）then restart taosd service to  make it work.

the larger value is , the more specific  information the log would record. you can find the SQL you are running and trace it over there.

**Comment by Jerry-Kwok** [comment]
Thanks a lot
