### ISSUE TITLE
DB error: Permission denied

### ISSUE THREAD

**Issue by alen123** [taosdata/TDengine#5641]
版本号：2.0.18.0
进行函数查询的时候提示 DB error: Permission denied
![image](https://user-images.githubusercontent.com/9209243/113131193-7d77b180-924f-11eb-9ef1-69c8dcbb29d7.png)
请问下是什么原因

**Comment by cpvmrd** [comment]
请检查一下TDengine要用到的文件（https://www.taosdata.com/cn/documentation/administrator#directories）的读写权限和当前系统登陆用户的读写权限是否匹配。

**Comment by alen123** [comment]
ok，已解决。3Q
