### ISSUE TITLE
the error when make deb package

### ISSUE THREAD

**Issue by rainsh2021** [taosdata/TDengine#5647]
虚拟机系统环境：ubuntu 12.04
CMAKE版本：3.15.4
GCC版本：5.4.1
TDengine源码版本：2.0.5.0
当前状态：已完成x86环境的源码编译并生成taos/taosd等核心程序，需要制作对应的deb安装包。
操作步骤如下：
root@ubuntn-virtual-machine:/third/TDengine# ./packaging/release.sh 
verMode=edge verType=stable cpuType=x64 osType=Linux pagMode=full soMode=dynamic dbName=taos verNumber= verNumberComp=2.0.0.0
please enter correct version

> 修改release.sh文件，将verNumber参数赋值

root@ubuntn-virtual-machine:/third/TDengine# ./packaging/release.sh 
verMode=edge verType=stable cpuType=x64 osType=Linux pagMode=full soMode=dynamic dbName=taos verNumber=2.0.5.1 verNumberComp=2.0.5.1
=======================new version number: 2.0.5.1, compatible version: 2.0.5.1======================================
fatal: Not a git repository (or any of the parent directories): .git

> 执行git init

root@ubuntn-virtual-machine:/third/TDengine# git init
Initialized empty Git repository in /third/TDengine/.git/
root@ubuntn-virtual-machine:/third/TDengine# ./packaging/release.sh 
verMode=edge verType=stable cpuType=x64 osType=Linux pagMode=full soMode=dynamic dbName=taos verNumber=2.0.5.1 verNumberComp=2.0.5.1
=======================new version number: 2.0.5.1, compatible version: 2.0.5.1======================================
fatal: Needed a single revision

> 该错误需要如何处理？

**Comment by cpvmrd** [comment]
在packaging目录下执行release.sh试试呢

**Comment by rainsh2021** [comment]
> 在packaging目录下执行release.sh试试呢

一样的错误，fatal: Needed a single revision，之前有测试过2.0.5.0中的这个打包功能吗？

**Comment by sangshuduo** [comment]
为什么要编译 2.0.5？我们只支持最新版本 和 develop 分支

**Comment by rainsh2021** [comment]
> 为什么要编译 2.0.5？我们只支持最新版本 和 develop 分支

老哥，目前2.0.5.0已经编译过了，现在是要打包。之前编译不过不是仅是2.0.5.0， develop和2.0.5.2、2.0.10.0一样编不过，必须修改一些inc和cmakelist参数才可以。

**Comment by rainsh2021** [comment]
> 打开packaging目录下release.sh, 发现有一段判断语句，这个是不是意味着没法制作x86版本的安装包？

#check support cpu type
if [[ "$cpuType" == "x64" ]] || [[ "$cpuType" == "aarch64" ]] || [[ "$cpuType" == "aarch32" ]] || [[ "$cpuType" == "mips64" ]] ; then
  if [ "$verMode" != "cluster" ]; then
    cmake ../    -DCPUTYPE=${cpuType} -DOSTYPE=${osType} -DSOMODE=${soMode} -DDBNAME=${dbName} -DVERTYPE=${verType} -DVERDATE="${build_time}" -DGITINFO=${gitinfo} -DGITINFOI=${gitinfoOfInternal} -DVERNUMBER=${verNumber} -DVERCOMPATIBLE=${verNumberComp} -DPAGMODE=${pagMode}
  else
    cmake ../../ -DCPUTYPE=${cpuType} -DOSTYPE=${osType} -DSOMODE=${soMode} -DDBNAME=${dbName} -DVERTYPE=${verType} -DVERDATE="${build_time}" -DGITINFO=${gitinfo} -DGITINFOI=${gitinfoOfInternal} -DVERNUMBER=${verNumber} -DVERCOMPATIBLE=${verNumberComp}
  fi
else
  echo "input cpuType=${cpuType} error!!!"
  exit 1
fi

**Comment by fenghuazzm** [comment]
This issue was closed because it has been inactive for too many days.
