### ISSUE TITLE
The result of TOP function seems like unnormal

### ISSUE THREAD

**Issue by peterchenhdu** [taosdata/TDengine#5657]
查出来的结果，不是按照tag_value排序的，而是按时间戳，》？？？？？？
![image](https://user-images.githubusercontent.com/12928352/113369080-fcc1ce00-9392-11eb-9adc-6555b9cd651d.png)
![image](https://user-images.githubusercontent.com/12928352/113369526-23cccf80-9394-11eb-81af-9001c235c0de.png)

版本信息：TDengine-server-2.0.16.0

**Comment by yu285** [comment]
您好，top 默认输出是按照时间升序，如果要按照值排序，可以这样: order xxx  by  desc;
