### ISSUE TITLE
high CPU usage

### ISSUE THREAD

**Issue by 59471032** [taosdata/TDengine#567]
[bbi@localhost sebs]$ top
top - 14:52:11 up 3 days,  3:57,  3 users,  load average: 1.53, 0.92, 0.79
Tasks: 412 total,   1 running, 411 sleeping,   0 stopped,   0 zombie
%Cpu(s):  4.5 us,  7.3 sy,  0.0 ni, 86.6 id,  0.2 wa,  0.0 hi,  1.3 si,  0.0 st
KiB Mem :  8009104 total,   944748 free,  5133000 used,  1931356 buff/cache
KiB Swap:  8257532 total,  8257012 free,      520 used.  2554736 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                                                  
 6944 root      20   0 1762060 138504   1472 S  45.4  1.7   1187:10 taosd                                                                                                                                                                                                    
13941 bbi       20   0 5920336 367672  14952 S   1.7  4.6   3:59.81 java                                                                                                                                                                                                     
19206 bbi       20   0 5728480 667832  19180 S   1.7  8.3   4:18.04 java                                                                                                                                                                                                     
15827 bbi       20   0 5730192 414092  14872 S   1.3  5.2   3:44.44 java 

没有任何应用在调用taosd，cpu一直在高位。

**Comment by hzcheng** [comment]
能否在/var/log/taos文件加下运行：
```
tail -f taosdlog*
```

几秒钟后ctrl+c停止，截图看下taosd服务在做什么工作。

**Comment by 59471032** [comment]
09/27 14:27:15.991526 7ff8c0251700 ERROR RPC DND-shell cid:0, maximum number of sessions:300 is reached
09/27 14:27:15.991559 7ff8c0251700 ERROR RPC DND-shell cid:0, maximum number of sessions:300 is reached
09/27 14:27:15.991564 7ff8d3588700 ERROR MON monitor:0x7ff8b40008c0, save log failed, code:-65
09/27 14:27:15.991622 7ff8d3d89700 ERROR MON monitor:0x7ff8b40008c0, save log failed, code:-65
09/27 14:27:15.991703 7ff8b8b86700 DND vid:0, committing to file, firstKey:1569320366387205 lastKey:1569320366387204 ssid:0 esid:32
09/27 14:27:15.991724 7ff8d3d89700 ERROR MON monitor:0x7ff8b40008c0, save log failed, code:-65
09/27 14:27:15.991838 7ff8d3d89700 ERROR MON monitor:0x7ff8b40008c0, save log failed, code:-65
09/27 14:27:15.992244 7ff8b8b86700 ERROR DND vid:0, head file:/data/taos/tsdb/vnode0/db/v0f1816.head corrupted
09/27 14:27:15.992437 7ff8b8b86700 DND vid:0, committing is over
09/27 14:27:15.992509 7ff8b9b88700 DND vid:0, committing to file, firstKey:1569320366387205 lastKey:1569320366387204 ssid:0 esid:32
09/27 14:27:15.992976 7ff8b9b88700 ERROR DND vid:0, head file:/data/taos/tsdb/vnode0/db/v0f1816.head corrupted
09/27 14:27:15.993141 7ff8b9b88700 DND vid:0, committing is over
09/27 14:27:15.993222 7ff8b8b86700 DND vid:0, committing to file, firstKey:1569320366387205 lastKey:1569320366387204 ssid:0 esid:32
09/27 14:27:15.993711 7ff8b8b86700 ERROR DND vid:0, head file:/data/taos/tsdb/vnode0/db/v0f1816.head corrupted
09/27 14:27:15.993882 7ff8b8b86700 DND vid:0, committing is over
09/27 14:27:15.995979 7ff8b9b88700 DND vid:0, committing to file, firstKey:1569320366387205 lastKey:1569320366387204 ssid:0 esid:32
09/27 14:27:15.996444 7ff8b9b88700 ERROR DND vid:0, head file:/data/taos/tsdb/vnode0/db/v0f1816.head corrupted
09/27 14:27:15.996657 7ff8b9b88700 DND vid:0, committing is over
09/27 14:27:16.037110 7ff8b9b88700 DND vid:0, committing to file, firstKey:1569320366387205 lastKey:1569320366387204 ssid:0 esid:32
09/27 14:27:16.037770 7ff8b9b88700 ERROR DND vid:0, head file:/data/taos/tsdb/vnode0/db/v0f1816.head corrupted
09/27 14:27:16.037976 7ff8b9b88700 DND vid:0, committing is over
09/27 14:27:16.038099 7ff8b8b86700 DND vid:0, committing to file, firstKey:1569320366387205 lastKey:1569320366387204 ssid:0 esid:32
09/27 14:27:16.038330 7ff8c0251700 ERROR RPC DND-shell cid:0, maximum number of sessions:300 is reached
09/27 14:27:16.038604 7ff8b8b86700 ERROR DND vid:0, head file:/data/taos/tsdb/vnode0/db/v0f1816.head corrupted
09/27 14:27:16.038769 7ff8b8b86700 DND vid:0, committing is over
09/27 14:27:16.038868 7ff8b9b88700 DND vid:0, committing to file, firstKey:1569320366387205 lastKey:1569320366387204 ssid:0 esid:32
09/27 14:27:16.038874 7ff8d3d89700 ERROR MON monitor:0x7ff8b40008c0, save log failed, code:-65
09/27 14:27:16.038904 7ff8c0251700 ERROR RPC DND-shell cid:0, maximum number of sessions:300 is reached
09/27 14:27:16.038964 7ff8c0251700 ERROR RPC DND-shell cid:0, maximum number of sessions:300 is reached
09/27 14:27:16.038997 7ff8c0251700 ERROR RPC DND-shell cid:0, maximum number of sessions:300 is reached
09/27 14:27:16.039025 7ff8c0251700 ERROR RPC DND-shell cid:0, maximum number of sessions:300 is reached
09/27 14:27:16.039045 7ff8c0251700 ERROR RPC DND-shell cid:0, maximum number of sessions:300 is reached
09/27 14:27:16.039071 7ff8c0251700 ERROR RPC DND-shell cid:0, maximum number of sessions:300 is reached
09/27 14:27:16.039101 7ff8c0251700 ERROR RPC DND-shell cid:0, maximum number of sessions:300 is reached
09/27 14:27:16.039125 7ff8d3588700 ERROR MON monitor:0x7ff8b40008c0, save log failed, code:-65
09/27 14:27:16.039150 7ff8d3588700 ERROR MON monitor:0x7ff8b40008c0, save log failed, code:-65
09/27 14:27:16.039163 7ff8d3588700 ERROR MON monitor:0x7ff8b40008c0, save log failed, code:-65
09/27 14:27:16.039208 7ff8d3588700 ERROR MON monitor:0x7ff8b40008c0, save log failed, code:-65
09/27 14:27:16.039232 7ff8d3588700 ERROR MON monitor:0x7ff8b40008c0, save log failed, code:-65
09/27 14:27:16.039248 7ff8d3588700 ERROR MON monitor:0x7ff8b40008c0, save log failed, code:-65
09/27 14:27:16.039287 7ff8d3588700 ERROR MON monitor:0x7ff8b40008c0, save log failed, code:-65
09/27 14:27:16.039322 7ff8b9b88700 ERROR DND vid:0, head file:/data/taos/tsdb/vnode0/db/v0f1816.head corrupted
09/27 14:27:16.039519 7ff8b9b88700 DND vid:0, committing is over
09/27 14:27:16.039644 7ff8b8b86700 DND vid:0, committing to file, firstKey:1569320366387205 lastKey:1569320366387204 ssid:0 esid:32
09/27 14:27:16.040240 7ff8b8b86700 ERROR DND vid:0, head file:/data/taos/tsdb/vnode0/db/v0f1816.head corrupted
09/27 14:27:16.040486 7ff8b8b86700 DND vid:0, committing is over
09/27 14:27:16.040625 7ff8b9b88700 DND vid:0, committing to file, firstKey:1569320366387205 lastKey:1569320366387204 ssid:0 esid:32
09/27 14:27:16.041073 7ff8b9b88700 ERROR DND vid:0, head file:/data/taos/tsdb/vnode0/db/v0f1816.head corrupted
09/27 14:27:16.041246 7ff8b9b88700 DND vid:0, committing is over
09/27 14:27:16.041356 7ff8b8b86700 DND vid:0, committing to file, firstKey:1569320366387205 lastKey:1569320366387204 ssid:0 esid:32
09/27 14:27:16.042019 7ff8b8b86700 ERROR DND vid:0, head file:/data/taos/tsdb/vnode0/db/v0f1816.head corrupted
09/27 14:27:16.042248 7ff8b8b86700 DND vid:0, committing is over
09/27 14:27:16.042317 7ff8b9b88700 DND vid:0, committing to file, firstKey:1569320366387205 lastKey:1569320366387204 ssid:0 esid:32
09/27 14:27:16.042799 7ff8b9b88700 ERROR DND vid:0, head file:/data/taos/tsdb/vnode0/db/v0f1816.head corrupted
09/27 14:27:16.042959 7ff8b9b88700 DND vid:0, committing is over
09/27 14:27:16.043041 7ff8b8b86700 DND vid:0, committing to file, firstKey:1569320366387205 lastKey:1569320366387204 ssid:0 esid:32
09/27 14:27:16.043511 7ff8b8b86700 ERROR DND vid:0, head file:/data/taos/tsdb/vnode0/db/v0f1816.head corrupted
09/27 14:27:16.043713 7ff8b8b86700 DND vid:0, committing is over
09/27 14:27:16.043783 7ff8b9b88700 DND vid:0, committing to file, firstKey:1569320366387205 lastKey:1569320366387204 ssid:0 esid:32
09/27 14:27:16.044203 7ff8b9b88700 ERROR DND vid:0, head file:/data/taos/tsdb/vnode0/db/v0f1816.head corrupted
09/27 14:27:16.044366 7ff8b9b88700 DND vid:0, committing is over
09/27 14:27:16.044442 7ff8b8b86700 DND vid:0, committing to file, firstKey:1569320366387205 lastKey:1569320366387204 ssid:0 esid:32
09/27 14:27:16.044972 7ff8b8b86700 ERROR DND vid:0, head file:/data/taos/tsdb/vnode0/db/v0f1816.head corrupted
09/27 14:27:16.045140 7ff8b8b86700 DND vid:0, committing is over
09/27 14:27:16.045208 7ff8b9b88700 DND vid:0, committing to file, firstKey:1569320366387205 lastKey:1569320366387204 ssid:0 esid:32
09/27 14:27:16.045223 7ff8c0251700 ERROR RPC DND-shell cid:0, maximum number of sessions:300 is reached
09/27 14:27:16.045308 7ff8d3588700 ERROR MON monitor:0x7ff8b40008c0, save log failed, code:-65
09/27 14:27:16.045636 7ff8b9b88700 ERROR DND vid:0, head file:/data/taos/tsdb/vnode0/db/v0f1816.head corrupted
09/27 14:27:16.045800 7ff8b9b88700 DND vid:0, committing is over
09/27 14:27:16.045871 7ff8b8b86700 DND vid:0, committing to file, firstKey:1569320366387205 lastKey:1569320366387204 ssid:0 esid:32
09/27 14:27:16.046314 7ff8b8b86700 ERROR DND vid:0, head file:/data/taos/tsdb/vnode0/db/v0f1816.head corrupted
09/27 14:27:16.046473 7ff8b8b86700 DND vid:0, committing is over
09/27 14:27:16.046548 7ff8b9b88700 DND vid:0, committing to file, firstKey:1569320366387205 lastKey:1569320366387204 ssid:0 esid:32
09/27 14:27:16.046561 7ff8c0251700 ERROR RPC DND-shell cid:0, maximum number of sessions:300 is reached
09/27 14:27:16.046783 7ff8d3d89700 ERROR MON monitor:0x7ff8b40008c0, save log failed, code:-65
09/27 14:27:16.046961 7ff8b9b88700 ERROR DND vid:0, head file:/data/taos/tsdb/vnode0/db/v0f1816.head corrupted
09/27 14:27:16.047146 7ff8b9b88700 DND vid:0, committing is over
09/27 14:27:16.047223 7ff8b8b86700 DND vid:0, committing to file, firstKey:1569320366387205 lastKey:1569320366387204 ssid:0 esid:32
09/27 14:27:16.047513 7ff8b8b86700 ERROR DND vid:0, head file:/data/taos/tsdb/vnode0/db/v0f1816.head corrupted
09/27 14:27:16.047646 7ff8b8b86700 DND vid:0, committing is over
09/27 14:27:16.047704 7ff8c0251700 ERROR RPC DND-shell cid:0, maximum number of sessions:300 is reached
09/27 14:27:16.047763 7ff8d3588700 ERROR MON monitor:0x7ff8b40008c0, save log failed, code:-65
^C

**Comment by hzcheng** [comment]
您用的是什么版本？

**Comment by 59471032** [comment]
Welcome to the TDengine shell, client version:1.6.2.1

**Comment by hzcheng** [comment]
方便把您微信号发hzcheng@taosdata.com，我们加您微信看下吧？
