### ISSUE TITLE
Is the 'last' function supported in data subscription SQL? 

### ISSUE THREAD

**Issue by ChuTingxu** [taosdata/TDengine#5672]
尝试在数据订阅的sql语句中使用last等函数，报错
TDengine Error: failed to create subscription
tdengine是否不支持在数据订阅中使用函数？

**Comment by cpvmrd** [comment]
暂不支持。可以参考文档中的案例来使用：https://www.taosdata.com/cn/documentation/advanced-features#subscribe。

**Comment by ChuTingxu** [comment]
> 暂不支持。可以参考文档中的案例来使用：[https://www.taosdata.com/cn/documentation/advanced-features#subscribe。](https://www.taosdata.com/cn/documentation/advanced-features#subscribe%E3%80%82)

关于文档中，数据订阅似乎还有一个问题，插入时自动建表的语句，不会返回该条数据 只有当该表第二条进入时才会反回第二条数据

**Comment by cpvmrd** [comment]
> > 暂不支持。可以参考文档中的案例来使用：[https://www.taosdata.com/cn/documentation/advanced-features#subscribe。](https://www.taosdata.com/cn/documentation/advanced-features#subscribe%E3%80%82)
> 
> 关于文档中，数据订阅似乎还有一个问题，插入时自动建表的语句，不会返回该条数据 只有当该表第二条进入时才会反回第二条数据

收到，这个我们再测试一下。感谢反馈。

**Comment by cpvmrd** [comment]
> > 暂不支持。可以参考文档中的案例来使用：[https://www.taosdata.com/cn/documentation/advanced-features#subscribe。](https://www.taosdata.com/cn/documentation/advanced-features#subscribe%E3%80%82)
> 
> 关于文档中，数据订阅似乎还有一个问题，插入时自动建表的语句，不会返回该条数据 只有当该表第二条进入时才会反回第二条数据

我们用2.0.18测试是正常的。你用的版本是？
