### ISSUE TITLE
run a long sql through cmd, DB error:Unable to establish connection

### ISSUE THREAD

**Issue by YuMiaoPy** [taosdata/TDengine#5679]
I have built a TDengine cluster with three nodes，as below：
![image](https://user-images.githubusercontent.com/40236700/113514364-a4601b80-95a0-11eb-90df-ec4dd735cd76.png)
OS: [CentOS 7.6]
Memory 20G, CPU 20核,  Disk 2T
TDengine Version [2.0.18.0]
when I insert a simple sql through the command line，it works well. But when I insert a long sql as below, it fails.
I have run the long sql on a stand-alone tDengine，it works well, where can prove the sql is right.
场景描述：
节点1主机名：tdengine1.ny.shuanghui.net
节点2主机名：tdengine2.ny.shuanghui.net
节点3主机名：tdengine3.ny.shuanghui.net
[taos.cfg的maxSQLLength均设置为：700000]
我在节点1的命令行执行较长的sql语句，结果报错如下：
![image](https://user-images.githubusercontent.com/40236700/113514891-af687b00-95a3-11eb-92f3-6a381c95f2ab.png)
附上debugFlag为135之后的跟踪日志，以及完整的sql语句，在线求助~

[sql.txt](https://github.com/taosdata/TDengine/files/6254929/sql.txt)
[node1-log.zip](https://github.com/taosdata/TDengine/files/6254934/node1-log.zip)
[node2-log.zip](https://github.com/taosdata/TDengine/files/6254936/node2-log.zip)
[node3-log.zip](https://github.com/taosdata/TDengine/files/6254937/node3-log.zip)

**Comment by cpvmrd** [comment]
@yu285 will help to check it.

**Comment by yu285** [comment]
> I have built a TDengine cluster with three nodes，as below：
> ![image](https://user-images.githubusercontent.com/40236700/113514364-a4601b80-95a0-11eb-90df-ec4dd735cd76.png)
> OS: [CentOS 7.6]
> Memory 20G, CPU 20核, Disk 2T
> TDengine Version [2.0.18.0]
> when I insert a simple sql through the command line，it works well. But when I insert a long sql as below, it fails.
> I have run the long sql on a stand-alone tDengine，it works well, where can prove the sql is right.
> 场景描述：
> 节点1主机名：tdengine1.ny.shuanghui.net
> 节点2主机名：tdengine2.ny.shuanghui.net
> 节点3主机名：tdengine3.ny.shuanghui.net
> [taos.cfg的maxSQLLength均设置为：700000]
> 我在节点1的命令行执行较长的sql语句，结果报错如下：
> ![image](https://user-images.githubusercontent.com/40236700/113514891-af687b00-95a3-11eb-92f3-6a381c95f2ab.png)
> 附上debugFlag为135之后的跟踪日志，以及完整的sql语句，在线求助~
> 
> [sql.txt](https://github.com/taosdata/TDengine/files/6254929/sql.txt)
> [node1-log.zip](https://github.com/taosdata/TDengine/files/6254934/node1-log.zip)
> [node2-log.zip](https://github.com/taosdata/TDengine/files/6254936/node2-log.zip)
> [node3-log.zip](https://github.com/taosdata/TDengine/files/6254937/node3-log.zip)

您好，已收到您的问题正在排查。方便的话可以加我微信加快处理效率：15652223354，问题解决后会在本问题中添加解决方案。

**Comment by yu285** [comment]
请问中间有客户端参与吗？
