### ISSUE TITLE
Alert rule expr can not have ' or "

### ISSUE THREAD

**Issue by leeningli** [taosdata/TDengine#5714]
**Bug Description**
When I add alert rule,the error is as follow:
<input>:1:98: invalid char literal
{"level":"error","ts":1617784031.7527323,"caller":"log/log.go:64","msg":"failed to parse rule: expression syntax error","stacktrace":"github.com/taosdata/alert/utils/log.Error\n\t/home/ubuntu/ver_release_workspace/TDinternal/community/alert/utils/log/log.go:64\ngithub.com/taosdata/alert/app.onUpdateRule\n\t/home/ubuntu/ver_release_workspace/TDinternal/community/alert/app/app.go:78\nnet/http.HandlerFunc.ServeHTTP\n\t/home/ubuntu/go/src/net/http/server.go:2042\nnet/http.(*ServeMux).ServeHTTP\n\t/home/ubuntu/go/src/net/http/server.go:2417\nmain.(*httpHandler).ServeHTTP\n\t/home/ubuntu/ver_release_workspace/TDinternal/community/alert/cmd/alert/main.go:31\nnet/http.serverHandler.ServeHTTP\n\t/home/ubuntu/go/src/net/http/server.go:2843\nnet/http.(*conn).serve\n\t/home/ubuntu/go/src/net/http/server.go:1925"}

my alert rule is as folllow:(expr cannot have ' or ")
{"annotations":
{"msg":"org==tn000001,solaceip=={{$values.solaceip}} adminstatus is shutdown,alerttime is {{$values.ts}}"},
"labels":{"level":"critical","receiveType":"mail","receivers":"1507045477@qq.com,leeing227@163.com"},
**"expr":"adminstatus == 'shutdown'",**
"for":"5s","name":"sync_adminstatus_alert","period":"15s","sql":"select ts,solaceip,adminstatus from rsmmeshmetric_tn000001.sync;"}

**Comment by cpvmrd** [comment]
I think it is a problem of Grafana. Please check its document.

**Comment by yu285** [comment]
The expr of Alert tool currently only supports the digital computation but not string.

You may could change  column type to meet that .

Thanks.
