### ISSUE TITLE
imx6ull cannot query data

### ISSUE THREAD

**Issue by BestHYY** [taosdata/TDengine#5722]
交叉编译的taosd运行在imx6ull平台，可以正常管理用户、数据库，可以正常建表、插入数据，但是查询时报错，报错信息如下：
taos> select * from test;
Query interrupted (Invalid handle), 0 row(s) in set (0.021866s)
taosd日志如下：
04/07 10:49:42.622366 00028759 VND ERROR vgId:2, invalid qId in retrieving result, code:Invalid handle, QInfo:5

**Comment by cpvmrd** [comment]
感谢支持TDengine。

我们希望支持尽可能多的软硬件平台，不过目前研发资源还比较紧张，希望有能力的用户能帮助解决并提交代码到TDengine。

**Comment by BestHYY** [comment]
可以帮我分析一下这个问题出在哪里吗？我的建库、建表、管理用户功能都正常，插入数据也回复正常，但是查询就会报错，TDENGINE版本2.0.19.0

**Comment by cpvmrd** [comment]
> 可以帮我分析一下这个问题出在哪里吗？我的建库、建表、管理用户功能都正常，插入数据也回复正常，但是查询就会报错，TDENGINE版本2.0.19.0

有更多日志信息吗，或者我找人远程连接看一下。

**Comment by BestHYY** [comment]
log文件见附件，其他操作成功没有单独的一条log，但是每次查询都会失败并且多一条ERROR的log
远程调试的话需要我提供哪些信息？
[taosdlog.txt](https://github.com/taosdata/TDengine/files/6282720/taosdlog.txt)
[taosinfo.txt](https://github.com/taosdata/TDengine/files/6282721/taosinfo.txt)
[taoslog0.txt](https://github.com/taosdata/TDengine/files/6282722/taoslog0.txt)
[taoslog1.txt](https://github.com/taosdata/TDengine/files/6282723/taoslog1.txt)

**Comment by sangshuduo** [comment]
请拉一下最新的 develop 分支代码编译试一下

**Comment by cpvmrd** [comment]
This issue was closed because it has been inactive for too many days.
