### ISSUE TITLE
A question about records inserting on 2 machines 

### ISSUE THREAD

**Issue by azhuoinfogs** [taosdata/TDengine#5724]
**Bug Description**
c语言测试demo:
连接机器A stardb 插入数据， 然后再次连接机器B stardb 插入数据, 操作成功， 但数据没有真正插入B.

**To Reproduce**
测试代码：

int main(int argc, char *argv[]) {
  char      qstr[1024];

  // connect to server
  if (argc < 3) {
    printf("please input server-ip \n");
    return 0;
  }

  TAOS *taos = taos_connect(argv[1] /*机器1 ip*/, "root", "taosdata", NULL, 0);
  if (taos == NULL) {
    printf("failed to connect to server, reason:%s\n", "null taos"/*taos_errstr(taos)*/);
    exit(1);
  }

  Test(taos, qstr, 1);
  taos_close(taos);

  TAOS *taos1 = taos_connect(argv[2]/*机器2 ip*/, "root", "taosdata", NULL, 0);
  if (taos1 == NULL) {
    printf("failed to connect to server, reason:%s\n", "null taos"/*taos_errstr(taos)*/);
    exit(1);
  }
  Test(taos1, qstr, 1);
  taos_close(taos1);
  taos_cleanup();
}
void Test(TAOS *taos, char *qstr, int index)  {
  printf("==================test at %d\n================================", index);
  // queryDB(taos, "drop database if exists demo");
  queryDB(taos, "create database if not exists demo");
  TAOS_RES *result;
  queryDB(taos, "use demo");
  sprintf(qstr, "create table if not exists m1 (ts timestamp, ti tinyint, si smallint, i int, bi bigint, f float, d double, b binary(10))");
  queryDB(taos, qstr);
  printf("success to create table\n");

  int i = 0;
  for (i = 0; i < 10; ++i) {
    sprintf(qstr, "insert into m1 values (%" PRId64 ", %d, %d, %d, %d, %f, %lf, '%s')",  (uint64_t)(1546300800000 + i * 1000), i, i, i, i*10000000, i*1.0, i*2.0, "hello");
    printf("qstr: %s\n", qstr);
    
    // note: how do you wanna do if taos_query returns non-NULL
    // if (taos_query(taos, qstr)) {
    //   printf("insert row: %i, reason:%s\n", i, taos_errstr(taos));
    // }
    TAOS_RES *result1 = taos_query(taos, qstr);
    if (result1 == NULL || taos_errno(result1) != 0) {
      printf("failed to insert row, reason:%s\n", taos_errstr(result1));    
      taos_free_result(result1);
      exit(1);
    } else {
      printf("insert row: %i\n", i);
    }
    taos_free_result(result1);
  }
  printf("success to insert rows, total %d rows\n", i);
}

测试结果;
机器1：客户端taos查询到插入的数据。
机器2：客户端taos没有查询到插入的数据。
![image](https://user-images.githubusercontent.com/16376634/113962719-d1d7ee00-985a-11eb-946f-4957edb2d6cb.png)

**Additional Context**
在连接机器2后， 如果使用不同的table 名称， 如：机器1table :m1, 机器2table：m2, 重复以上步骤， 
连接机器1 stardb 插入数据， 然后再次连接机器2 stardb 插入数据, 操作成功， 问题不复现，机器2 上可以查询到数据。

**Comment by yu285** [comment]
您好，请添加微信15652223354，方便沟通给您定位问题。

**Comment by yu285** [comment]
您好，经确认，TDengine目前暂不支持在一个taosc（客户端）中连接两个taosd（主进程）。

未来会修复，请注意使用。
