### ISSUE TITLE
Support  table-based data expiration rule 

### ISSUE THREAD

**Issue by xujiesh0510** [taosdata/TDengine#5727]
目前数据过期只支持 数据库层面设置数据过期， 这样不够灵活。
能支持 基于表的数据过期规则么？

**Comment by cpvmrd** [comment]
你好，这个需求有合理性，我会反馈给研发讨论。不过应该需要一定的时间。

**Comment by xujiesh0510** [comment]
好的，非常感谢。

**Comment by cpvmrd** [comment]
This issue was closed because it has been inactive for too many days.
