### ISSUE TITLE
Is there any index for the second tag?

### ISSUE THREAD

**Issue by wuqingzhi128** [taosdata/TDengine#5728]
我看官网并没有介绍,很详细的索引机制，我想问一下，对超级表的tag的第一列的取值做全内存的索引，那么假如查找第二列的tag的时候，那么就不会走索引了吗

**Comment by yu285** [comment]
您好，tag是以表为单位一起存放于内存的。不分第一二列。

**Comment by wuqingzhi128** [comment]
![image](https://user-images.githubusercontent.com/66063598/114363409-ee518e80-9baa-11eb-9539-5bf606f62a93.png)
您好这个是官方文章上面的一段话，这个第一列应该怎么理解，对了咱们tdengine 有群吗

**Comment by yu285** [comment]
已与该问题提出者微信交流。
