### ISSUE TITLE
A question about query speed

### ISSUE THREAD

**Issue by zhugekaoyu** [taosdata/TDengine#574]
尊敬的taosdata老师们：
  你们好！感谢贵司开源如此优秀的产品，向你们致敬！
  最近在研究千万级数据量的查询性能，遇到问题，需要求助你们，麻烦给予解答，感谢！
  我创建了两张超级表，第一个超级表(dwd_lgt_clt)有10个字段，10个子表，每个子表300万数据量，只有一个tag(company_code)从超级表中查询某一条数据，用时很快，0.01到0.02秒之间，具体请看下图：
![image](https://user-images.githubusercontent.com/50863811/65816759-2fd15180-e232-11e9-8398-2e300911a71d.png)
![image](https://user-images.githubusercontent.com/50863811/65817276-ce13e600-e237-11e9-93ed-a09a61ee9f96.png)
![image](https://user-images.githubusercontent.com/50863811/65816781-9e161400-e232-11e9-9d25-f66da2f87c07.png)
![image](https://user-images.githubusercontent.com/50863811/65816794-be45d300-e232-11e9-9e54-dc2c2ce31f3b.png)
第二张超级表有12个字段，目前只有两个子表，270多万数据，也是一个tag(warehousecode)但是从超级表查询一条数据，用时就得11秒多
![image](https://user-images.githubusercontent.com/50863811/65816844-6b205000-e233-11e9-8698-221ffd88b56e.png)
![image](https://user-images.githubusercontent.com/50863811/65817315-34990400-e238-11e9-9a62-531a114dda6b.png)
![image](https://user-images.githubusercontent.com/50863811/65816857-8d19d280-e233-11e9-8920-46d0908dbe9c.png)
![image](https://user-images.githubusercontent.com/50863811/65817183-c30c8600-e236-11e9-9d2d-c7089c6b46b9.png)
第二张表比第一张表多了2个字段，在使用tag的过滤下，都是从300万左右的表中查询记录，第二个查询非常慢，不知问题出在哪里？是字段个数有限制吗？两个表的查询条件都是rcp_code，dwd_lgt_clt表此字段类型是bigint，第二张dwd_lgt_clt_sign_pkg_ty此字段是BINARY，不知道和这个有没有关系，但是我司实际的业务场景此字段只能用字符串。。还请研发者给予指点，为何查询速度差这么多。不胜感激！

**Comment by hzcheng** [comment]
应该是由于两个rcp_code的类型不一样导致的吧。第一个的rcp_code是一个bigint类型的。第二个的rcp_code是binary(100)类型的。过滤对比bigint类型应该是远远快于字符串类型的的过滤查询。

**Comment by zhugekaoyu** [comment]
问题是rcp_code此字段真实业务场景需要用字符串类型，请问如何做到查询速度更快一点呢？

**Comment by zhugekaoyu** [comment]
如果我们把字符串改成hash的数值存储，查询会变快吗

**Comment by hzcheng** [comment]
可以加快的，不过你们能保证字符串和hash值一一对应吗？

**Comment by hzcheng** [comment]
这个加速过滤的功能我们也在工作列表中，会在后续开发中优化的。

**Comment by zhugekaoyu** [comment]
这个不太好保证，经过测试，不同的单号可能对应的hash值是相同的......

**Comment by hjxilinx** [comment]
@zhugekaoyu ，如果您查询的数据不是全部字段，建议只提取需要的字段，因为TDengine采用的列式存储，提取过多的列会对查询性能有一定的影响，我们后面会针对全部字段的数据读取进行读操作的合并。对性能有一定的提升作用。
