### ISSUE TITLE
alter assertion failed on Windows 

### ISSUE THREAD

**Issue by ChuTingxu** [taosdata/TDengine#5752]
程序在运行一段时间后会弹出
![f47be730f3d2acc7be291ac35d17775](https://user-images.githubusercontent.com/25150748/114157043-ccab9980-9955-11eb-8a40-8f2ce55c88d7.png)

我不清楚这个意味着什么

 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [2.0.18]

**Comment by sangshuduo** [comment]
具体是做了什么操作呢？

**Comment by ChuTingxu** [comment]
> 具体是做了什么操作呢？
java开启一个线程去订阅数据，然后将订阅的数据持续存入内存中的一个队列中，使用的druid连接池。

**Comment by ChuTingxu** [comment]
另外还有几个线程持续将数据存入taos中

**Comment by ChuTingxu** [comment]
存入taos的线程 订阅taos存入队列的线程 从队列中取出存入mysql的线程。这几个线程分别运行没有问题，同时运行大约4min左右就会报这个错误

**Comment by fenghuazzm** [comment]
This issue was closed because it has been inactive for too many days.
