### ISSUE TITLE
Please ignore the install_service in packaging/tools/make_install.sh when make install inside docker environment.

### ISSUE THREAD

**Issue by holmescn** [taosdata/TDengine#576]
**Bug Description**
When doing `make install` inside a docker environment with ubuntu 16.04 or 18.04 image, the `make_install.sh` always try to install SysVInit service which is not needed inside a docker environment. Since the init service is not installed, the `make_install.sh` always raise errors and stop running. After I comment the `install_service` function inside the script. All is done.

**To Reproduce**
1. `docker run -it --rm ubuntu:16.04 bash`
2. `apt install -y cmake build-essential git`
3. clone the repository and do building as the Getting Started guide.
4. run `make install` after `cmake --build .`

**Expected Behavior**
TDengine installed correctly.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04/18.04 inside docker
 - Memory, CPU, current Disk Space
 - TDengine Version 1.6.2.0, master

**Additional Context**

**Comment by anjia0532** [comment]
```
    # ...
    cmake .. && cmake --build . && \
    mkdir -p /tmp/TDengine/packaging/deb/init.d && \
    cp /tmp/TDengine/packaging/deb/taosd /tmp/TDengine/packaging/deb/init.d/taosd && \
    make install && \
    # ...
```

**Comment by holmescn** [comment]
@anjia0532 There are a 100+ methods to walk around the issue but a few lines of code to fix it in upstream.

**Comment by anjia0532** [comment]
@holmescn 直接用 makepkg.sh ,打包最小二进制。

**Comment by holmescn** [comment]
@anjia0532 What I mentioned here is an issue not a question...
