### ISSUE TITLE
TSDB error: too many sessions on server

### ISSUE THREAD

**Issue by Leehom23** [taosdata/TDengine#577]
How to increase the number of sessions

**Comment by hzcheng** [comment]
Did you close the result set and close the connection when you do not need it?

**Comment by jtao1735** [comment]
May you set "debugFlag 135" in taos.cfg in both server and client side, and re-run the testing? If it happens again, please post the log here, we can help out

**Comment by liangyuanpeng** [comment]
maybe need more detail message，log or code

**Comment by Leehom23** [comment]
> Did you close the result set and close the connection when you do not need it?

taos -h 172.20.23.23 -s "use db; insert into child_table $1/${yesterday}/$file " > /dev/null 2>&1
i just use this command to import csv data to taos. one file for one thread. then i increse the value of
“pre-allocated number of http sessions“. then i  solve it. but another question is i the speed of importing csv to taos,18,000 every  second。i think it's too slowly.

**Comment by jtao1735** [comment]
> > Did you close the result set and close the connection when you do not need it?
> 
> taos -h ip -s "use db; insert into child_table $1/${yesterday}/$file " > /dev/null 2>&1
> i just use this command to import csv data to taos. one file for one thread. then i increse the value of
> “pre-allocated number of http sessions“. then i solve it. but another question is i the speed of importing csv to taos,18,000 every second。i think it's too slowly.

For single thread, 18000 every second is ok. You shall use multiple threads or clients to import data. Around 20 threads or clients will drive the server to the top performance

**Comment by Leehom23** [comment]
> > > Did you close the result set and close the connection when you do not need it?
> > 
> > 
> > taos -h ip -s "use db; insert into child_table $1/${yesterday}/$file " > /dev/null 2>&1
> > i just use this command to import csv data to taos. one file for one thread. then i increse the value of
> > “pre-allocated number of http sessions“. then i solve it. but another question is i the speed of importing csv to taos,18,000 every second。i think it's too slowly.
> 
> For single thread, 18000 every second is ok. You shall use multiple threads or clients to import data. Around 20 threads or clients will drive the server to the top performance

i use multiple threads to  import data , the taos server response "server error".then i find the server is down.

**Comment by sangshuduo** [comment]
Please try latest stable release to see if the issue still exist.
