### ISSUE TITLE
taosd eat memory when doing stress testing with taosimport tool

### ISSUE THREAD

**Issue by wanyikang** [taosdata/TDengine#5778]
**Bug Description**
all three nodes eat memory when i do stress testing

**To Reproduce**
1. install TDengine-server-2.0.18.0 on 3 nodes, only change maxSQLLength=1000000 except other necessary config
2. install taoimport on the other two cloud machine, and edit edit cfg.toml to add case, i will paste the cfg and json data
3. execute the following cmd on 32c test machine:
> bin/taosimport -cfg config/cfg.toml -cases pot_electric -hnum 60 -vnum 0 -host tdengine-node1 -user performance_test -password pt123 -dbparam 'replica 3' -dropdb 1 -auto 1 -start "2020-03-07 00:00:00.000" -interval 30000 -batch 600 -thread 32
4. execute the following cmd on 8c test machine:
> bin/taosimport -cfg config/cfg.toml -cases camera_detection -hnum 600 -vnum 0 -host tdengine-node1 -user performance_test -password pt123 -dbparam 'replica 3' -auto 1 -start "2020-03-07 00:00:00.000" -interval 30000 -batch 400 -thread 6 -db test_camera_detectio
5. wait for 20 min, and the memory usage will reach 99.7%

**Expected Behavior**
memory usage is stable and relative low

**Screenshots**
![tdengine1](https://user-images.githubusercontent.com/5843919/114334517-46719c00-9b7d-11eb-91fe-8e3197e7e55a.png)
![tdengine2](https://user-images.githubusercontent.com/5843919/114334527-4e314080-9b7d-11eb-82f3-d2a886e93492.png)
![tdengine3](https://user-images.githubusercontent.com/5843919/114334536-525d5e00-9b7d-11eb-8b7b-a8873230b04e.png)

**Environment (please complete the following information):**
tdengine version: TDengine-server-2.0.18.0-Linux-x64.deb
cloud host deploy: 4c16g, disk 300g, 3 nodes, ubuntu server 16.04
testing host deploy: one machine 32c64g, another one 8c8g

**Additional Context**
I think there may be memory leak in taosd

**Comment by wanyikang** [comment]
cfg.toml
# 传感器场景
[sensor_info]                               # 场景名称
format = "csv"                              # 样例数据文件格式，可以是 json 或 csv，具体字段应至少包含 subTableName、tags、fields 指定的字段。
filePath = "data/sensor_info.csv"           # 样例数据文件路径，程序会循环使用该文件数据
separator = ","                             # csv 样例文件中字段分隔符，默认逗号

stname = "sensor_info"                      # 超级表名称
subTableName = "devid"                      # 使用样例数据中指定字段当作子表名称一部分，子表名称格式为 t_subTableName_stname，扩展表名为 t_subTableName_stname_i。
timestamp = "ts"                            # 使用 fields 中哪个字段当作主键，类型必须为 timestamp
timestampType="millisecond"                 # 样例数据中主键时间字段是 millisecond 还是 dateTime 格式
#timestampTypeFormat = "2006-01-02 15:04:05.000"  # 主键日期时间格式，timestampType 为 dateTime 时需要指定
tags = [
    # 标签列表，name 为标签名称，type 为标签类型
    { name = "location",           type = "binary(20)" },
    { name = "color",              type = "binary(16)" },
    { name = "devgroup",           type = "int" },
]

fields = [
    # 字段列表，name 为字段名称，type 为字段类型
    { name = "ts",                  type = "timestamp" },
    { name = "temperature",         type = "int" },
    { name = "humidity",            type = "float" },
]

# 摄像头检测场景
[camera_detection]                          # 场景名称
format = "json"                             # 样例数据文件格式，可以是 json 或 csv，具体字段应至少包含 subTableName、tags、fields 指定的字段。
filePath = "data/camera_detection.json"     # 样例数据文件路径，程序会循环使用该文件数据
#separator = ","                            # csv 样例文件中字段分隔符，默认逗号, 如果是 json 文件可以不用配置
 
stname = "camera_detection"                 # 超级表名称
subTableName = "sensor_id"                  # 使用样例数据中指定字段当作子表名称一部分，子表名称格式为 t_subTableName_stname，扩展表名为 t_subTableName_stname_i。
timestamp = "ts"                            # 使用 fields 中哪个字段当作主键，类型必须为 timestamp
timestampType="dateTime"                    # 样例数据中主键时间字段是 millisecond 还是 dateTime 格式
timestampTypeFormat = "2006-01-02 15:04:05.000"  # 主键日期时间格式，timestampType 为 dateTime 时需要指定
tags = [
    # 标签列表，name 为标签名称，type 为标签类型
    { name = "home_id",           type = "binary(30)" },
    { name = "object_type",       type = "int" },
    { name = "object_kind",       type = "binary(20)" },
]

fields = [
    # 字段列表，name 为字段名称，type 为字段类型
    { name = "ts",                type = "timestamp" },
    { name = "states",            type = "tinyint" },
    { name = "battery_voltage",   type = "float" },
]

# electric场景
[pot_electric]                              # 场景名称
format = "json"                             # 样例数据文件格式，可以是 json 或 csv，具体字段应至少包含 subTableName、tags、fields 指定的字段。
filePath = "data/pot_electric.json"         # 样例数据文件路径，程序会循环使用该文件数据
#separator = ","                            # csv 样例文件中字段分隔符，默认逗号, 如果是 json 文件可以不用配置
 
stname = "pot_electric"                     # 超级表名称
subTableName = "mtid"                       # 使用样例数据中指定字段当作子表名称一部分，子表名称格式为 t_subTableName_stname，扩展表名为 t_subTableName_stname_i。
timestamp = "time"                          # 使用 fields 中哪个字段当作主键，类型必须为 timestamp
timestampType="dateTime"                    # 样例数据中主键时间字段是 millisecond 还是 dateTime 格式
timestampTypeFormat = "2006-01-02 15:04:05.000"  # 主键日期时间格式，timestampType 为 dateTime 时需要指定
tags = [
    # 标签列表，name 为标签名称，type 为标签类型
    { name = "cid",           type = "int" },
]

fields = [
    # 字段列表，name 为字段名称，type 为字段类型
    { name = "time",                     type = "timestamp" },
    { name = "eq_type",                  type = "binary(30)" },  
    { name = "data_topic",               type = "binary(30)" },  
    { name = "sid",                      type = "binary(50)" },
    { name = "soft_hardware_version",    type = "binary(30)" },
    { name = "meter_sn",                 type = "binary(50)" },
    { name = "data_key",                 type = "binary(50)" },
    { name = "mtid",                     type = "int" },
    { name = "pid",                      type = "int" },
    { name = "ua",                       type = "float" },  
    { name = "ub",                       type = "float" }, 
    { name = "uc",                       type = "float" }, 
    { name = "ia",                       type = "float" }, 
    { name = "ib",                       type = "float" }, 
    { name = "ic",                       type = "float" }, 
    { name = "pa",                       type = "float" }, 
    { name = "pb",                       type = "float" }, 
    { name = "pc",                       type = "float" }, 
    { name = "pttl",                     type = "float" },
    { name = "qa",                       type = "float" }, 
    { name = "qb",                       type = "float" },
    { name = "qc",                       type = "float" },
    { name = "qttl",                     type = "float" }, 
    { name = "sa",                       type = "float" },  
    { name = "sb",                       type = "float" }, 
    { name = "sc",                       type = "float" }, 
    { name = "sttl",                     type = "float" }, 
    { name = "cosa",                     type = "float" },
    { name = "cosb",                     type = "float" },
    { name = "cosc",                     type = "float" },
    { name = "costtl",                   type = "float" },
    { name = "phA",                      type = "float" }, 
    { name = "phB",                      type = "float" },
    { name = "phC",                      type = "float" },
    { name = "kvarha_minus",             type = "float" }, 
    { name = "kvarhb_minus",             type = "float" },
    { name = "kvarhc_minus",             type = "float" },
    { name = "kvarha_plus",              type = "float" },
    { name = "kvarhb_plus",              type = "float" },
    { name = "kvarhc_plus",              type = "float" },
    { name = "kwha_minus",               type = "float" }, 
    { name = "kwhb_minus",               type = "float" },
    { name = "kwhc_minus",               type = "float" },
    { name = "kwha_plus",                type = "float" },
    { name = "kwhb_plus",                type = "float" },
    { name = "kwhc_plus",                type = "float" },
    { name = "angleAB",                  type = "float" }, 
    { name = "angleAC",                  type = "float" },
    { name = "kwhttl_minus",             type = "float" },
    { name = "kwhttl_plus",              type = "float" },
    { name = "kvarhttl_minus",           type = "float" }, 
    { name = "kvarhttl_plus",            type = "float" },  
    { name = "ctnum",                    type = "float" }, 
    { name = "freq",                     type = "float" }, 
    { name = "mdp",                      type = "float" },
    { name = "mdptime",                  type = "timestamp" },
    { name = "mdkwh",                    type = "float" }, 
    { name = "mdkwhtime",                type = "timestamp" }, 
    { name = "ubl",                      type = "float" }, 
    { name = "ibl",                      type = "float" }, 
    { name = "fdia",                     type = "float" }, 
    { name = "fdua",                     type = "float" },
    { name = "fdib",                     type = "float" },
    { name = "fdub",                     type = "float" },
    { name = "fdic",                     type = "float" },
    { name = "fduc",                     type = "float" },
    { name = "fdpttl",                   type = "float" },
    { name = "fdpa",                     type = "float" },   
    { name = "fdpb",                     type = "float" },
    { name = "fdpc",                     type = "float" },
    { name = "hrpttl",                   type = "float" },
    { name = "hrpa",                     type = "float" }, 
    { name = "hrpb",                     type = "float" },
    { name = "hrpc",                     type = "float" },
    { name = "thdia",                    type = "float" }, 
    { name = "hr2ia",                    type = "float" },
    { name = "hr3ia",                    type = "float" },
    { name = "hr4ia",                    type = "float" },
    { name = "hr5ia",                    type = "float" },
    { name = "hr6ia",                    type = "float" },
    { name = "hr7ia",                    type = "float" },
    { name = "hr8ia",                    type = "float" },
    { name = "hr9ia",                    type = "float" },
    { name = "hr10ia",                   type = "float" }, 
    { name = "hr11ia",                   type = "float" },
    { name = "hr12ia",                   type = "float" },
    { name = "hr13ia",                   type = "float" },
    { name = "hr14ia",                   type = "float" },
    { name = "hr15ia",                   type = "float" },
    { name = "hr16ia",                   type = "float" },
    { name = "hr17ia",                   type = "float" },
    { name = "thdib",                    type = "float" }, 
    { name = "hr2ib",                    type = "float" },
    { name = "hr3ib",                    type = "float" },
    { name = "hr4ib",                    type = "float" },
    { name = "hr5ib",                    type = "float" },
    { name = "hr6ib",                    type = "float" },
    { name = "hr7ib",                    type = "float" },
    { name = "hr8ib",                    type = "float" },
    { name = "hr9ib",                    type = "float" },
#    { name = "hr10ib",                   type = "float" }, 
#    { name = "hr11ib",                   type = "float" },
#    { name = "hr12ib",                   type = "float" },
#    { name = "hr13ib",                   type = "float" },
#    { name = "hr14ib",                   type = "float" },
#    { name = "hr15ib",                   type = "float" },
#    { name = "hr16ib",                   type = "float" },
#    { name = "hr17ib",                   type = "float" },
#    { name = "thdic",                    type = "float" }, 
#    { name = "hr2ic",                    type = "float" },
#    { name = "hr3ic",                    type = "float" },
#    { name = "hr4ic",                    type = "float" },
#    { name = "hr5ic",                    type = "float" },
#    { name = "hr6ic",                    type = "float" },
#    { name = "hr7ic",                    type = "float" },
#    { name = "hr8ic",                    type = "float" },
#    { name = "hr9ic",                    type = "float" },
#    { name = "hr10ic",                   type = "float" }, 
#    { name = "hr11ic",                   type = "float" },
#    { name = "hr12ic",                   type = "float" },
#    { name = "hr13ic",                   type = "float" },
#    { name = "hr14ic",                   type = "float" },
#    { name = "hr15ic",                   type = "float" },
#    { name = "hr16ic",                   type = "float" },
#    { name = "hr17ic",                   type = "float" },
#    { name = "thdua",                    type = "float" }, 
#    { name = "hr2ua",                    type = "float" },
#    { name = "hr3ua",                    type = "float" },
#    { name = "hr4ua",                    type = "float" },
#    { name = "hr5ua",                    type = "float" },
#    { name = "hr6ua",                    type = "float" },
#    { name = "hr7ua",                    type = "float" },
#    { name = "hr8ua",                    type = "float" },
#    { name = "hr9ua",                    type = "float" },
#    { name = "hr10ua",                   type = "float" }, 
#    { name = "hr11ua",                   type = "float" },
#    { name = "hr12ua",                   type = "float" },
#    { name = "hr13ua",                   type = "float" },
#    { name = "hr14ua",                   type = "float" },
#    { name = "hr15ua",                   type = "float" },
#    { name = "hr16ua",                   type = "float" },
#    { name = "hr17ua",                   type = "float" },
#    { name = "thdub",                    type = "float" }, 
#    { name = "hr2ub",                    type = "float" },
#    { name = "hr3ub",                    type = "float" },
#    { name = "hr4ub",                    type = "float" },
#    { name = "hr5ub",                    type = "float" },
#    { name = "hr6ub",                    type = "float" },
#    { name = "hr7ub",                    type = "float" },
#    { name = "hr8ub",                    type = "float" },
#    { name = "hr9ub",                    type = "float" },
#    { name = "hr10ub",                   type = "float" }, 
#    { name = "hr11ub",                   type = "float" },
#    { name = "hr12ub",                   type = "float" },
#    { name = "hr13ub",                   type = "float" },
#    { name = "hr14ub",                   type = "float" },
#    { name = "hr15ub",                   type = "float" },
#    { name = "hr16ub",                   type = "float" },
#    { name = "hr17ub",                   type = "float" },
#    { name = "thduc",                    type = "float" }, 
#    { name = "hr2uc",                    type = "float" },
#    { name = "hr3uc",                    type = "float" },
#    { name = "hr4uc",                    type = "float" },
#    { name = "hr5uc",                    type = "float" },
#    { name = "hr6uc",                    type = "float" },
#    { name = "hr7uc",                    type = "float" },
#    { name = "hr8uc",                    type = "float" },
#    { name = "hr9uc",                    type = "float" },
#    { name = "hr10uc",                   type = "float" }, 
#    { name = "hr11uc",                   type = "float" },
#    { name = "hr12uc",                   type = "float" },
#    { name = "hr13uc",                   type = "float" },
#    { name = "hr14uc",                   type = "float" },
#    { name = "hr15uc",                   type = "float" },
#    { name = "hr16uc",                   type = "float" },
#    { name = "hr17uc",                   type = "float" }
]

**Comment by wanyikang** [comment]
# 传感器场景
[sensor_info]                               # 场景名称
format = "csv"                              # 样例数据文件格式，可以是 json 或 csv，具体字段应至少包含 subTableName、tags、fields 指定的字段。
filePath = "data/sensor_info.csv"           # 样例数据文件路径，程序会循环使用该文件数据
separator = ","                             # csv 样例文件中字段分隔符，默认逗号

stname = "sensor_info"                      # 超级表名称
subTableName = "devid"                      # 使用样例数据中指定字段当作子表名称一部分，子表名称格式为 t_subTableName_stname，扩展表名为 t_subTableName_stname_i。
timestamp = "ts"                            # 使用 fields 中哪个字段当作主键，类型必须为 timestamp
timestampType="millisecond"                 # 样例数据中主键时间字段是 millisecond 还是 dateTime 格式
#timestampTypeFormat = "2006-01-02 15:04:05.000"  # 主键日期时间格式，timestampType 为 dateTime 时需要指定
tags = [
    # 标签列表，name 为标签名称，type 为标签类型
    { name = "location",           type = "binary(20)" },
    { name = "color",              type = "binary(16)" },
    { name = "devgroup",           type = "int" },
]

fields = [
    # 字段列表，name 为字段名称，type 为字段类型
    { name = "ts",                  type = "timestamp" },
    { name = "temperature",         type = "int" },
    { name = "humidity",            type = "float" },
]

# 摄像头检测场景
[camera_detection]                          # 场景名称
format = "json"                             # 样例数据文件格式，可以是 json 或 csv，具体字段应至少包含 subTableName、tags、fields 指定的字段。
filePath = "data/camera_detection.json"     # 样例数据文件路径，程序会循环使用该文件数据
#separator = ","                            # csv 样例文件中字段分隔符，默认逗号, 如果是 json 文件可以不用配置
 
stname = "camera_detection"                 # 超级表名称
subTableName = "sensor_id"                  # 使用样例数据中指定字段当作子表名称一部分，子表名称格式为 t_subTableName_stname，扩展表名为 t_subTableName_stname_i。
timestamp = "ts"                            # 使用 fields 中哪个字段当作主键，类型必须为 timestamp
timestampType="dateTime"                    # 样例数据中主键时间字段是 millisecond 还是 dateTime 格式
timestampTypeFormat = "2006-01-02 15:04:05.000"  # 主键日期时间格式，timestampType 为 dateTime 时需要指定
tags = [
    # 标签列表，name 为标签名称，type 为标签类型
    { name = "home_id",           type = "binary(30)" },
    { name = "object_type",       type = "int" },
    { name = "object_kind",       type = "binary(20)" },
]

fields = [
    # 字段列表，name 为字段名称，type 为字段类型
    { name = "ts",                type = "timestamp" },
    { name = "states",            type = "tinyint" },
    { name = "battery_voltage",   type = "float" },
]

# electric场景
[pot_electric]                              # 场景名称
format = "json"                             # 样例数据文件格式，可以是 json 或 csv，具体字段应至少包含 subTableName、tags、fields 指定的字段。
filePath = "data/pot_electric.json"         # 样例数据文件路径，程序会循环使用该文件数据
#separator = ","                            # csv 样例文件中字段分隔符，默认逗号, 如果是 json 文件可以不用配置
 
stname = "pot_electric"                     # 超级表名称
subTableName = "mtid"                       # 使用样例数据中指定字段当作子表名称一部分，子表名称格式为 t_subTableName_stname，扩展表名为 t_subTableName_stname_i。
timestamp = "time"                          # 使用 fields 中哪个字段当作主键，类型必须为 timestamp
timestampType="dateTime"                    # 样例数据中主键时间字段是 millisecond 还是 dateTime 格式
timestampTypeFormat = "2006-01-02 15:04:05.000"  # 主键日期时间格式，timestampType 为 dateTime 时需要指定
tags = [
    # 标签列表，name 为标签名称，type 为标签类型
    { name = "cid",           type = "int" },
]

fields = [
    # 字段列表，name 为字段名称，type 为字段类型
    { name = "time",                     type = "timestamp" },
    { name = "eq_type",                  type = "binary(30)" },  
    { name = "data_topic",               type = "binary(30)" },  
    { name = "sid",                      type = "binary(50)" },
    { name = "soft_hardware_version",    type = "binary(30)" },
    { name = "meter_sn",                 type = "binary(50)" },
    { name = "data_key",                 type = "binary(50)" },
    { name = "mtid",                     type = "int" },
    { name = "pid",                      type = "int" },
    { name = "ua",                       type = "float" },  
    { name = "ub",                       type = "float" }, 
    { name = "uc",                       type = "float" }, 
    { name = "ia",                       type = "float" }, 
    { name = "ib",                       type = "float" }, 
    { name = "ic",                       type = "float" }, 
    { name = "pa",                       type = "float" }, 
    { name = "pb",                       type = "float" }, 
    { name = "pc",                       type = "float" }, 
    { name = "pttl",                     type = "float" },
    { name = "qa",                       type = "float" }, 
    { name = "qb",                       type = "float" },
    { name = "qc",                       type = "float" },
    { name = "qttl",                     type = "float" }, 
    { name = "sa",                       type = "float" },  
    { name = "sb",                       type = "float" }, 
    { name = "sc",                       type = "float" }, 
    { name = "sttl",                     type = "float" }, 
    { name = "cosa",                     type = "float" },
    { name = "cosb",                     type = "float" },
    { name = "cosc",                     type = "float" },
    { name = "costtl",                   type = "float" },
    { name = "phA",                      type = "float" }, 
    { name = "phB",                      type = "float" },
    { name = "phC",                      type = "float" },
    { name = "kvarha_minus",             type = "float" }, 
    { name = "kvarhb_minus",             type = "float" },
    { name = "kvarhc_minus",             type = "float" },
    { name = "kvarha_plus",              type = "float" },
    { name = "kvarhb_plus",              type = "float" },
    { name = "kvarhc_plus",              type = "float" },
    { name = "kwha_minus",               type = "float" }, 
    { name = "kwhb_minus",               type = "float" },
    { name = "kwhc_minus",               type = "float" },
    { name = "kwha_plus",                type = "float" },
    { name = "kwhb_plus",                type = "float" },
    { name = "kwhc_plus",                type = "float" },
    { name = "angleAB",                  type = "float" }, 
    { name = "angleAC",                  type = "float" },
    { name = "kwhttl_minus",             type = "float" },
    { name = "kwhttl_plus",              type = "float" },
    { name = "kvarhttl_minus",           type = "float" }, 
    { name = "kvarhttl_plus",            type = "float" },  
    { name = "ctnum",                    type = "float" }, 
    { name = "freq",                     type = "float" }, 
    { name = "mdp",                      type = "float" },
    { name = "mdptime",                  type = "timestamp" },
    { name = "mdkwh",                    type = "float" }, 
    { name = "mdkwhtime",                type = "timestamp" }, 
    { name = "ubl",                      type = "float" }, 
    { name = "ibl",                      type = "float" }, 
    { name = "fdia",                     type = "float" }, 
    { name = "fdua",                     type = "float" },
    { name = "fdib",                     type = "float" },
    { name = "fdub",                     type = "float" },
    { name = "fdic",                     type = "float" },
    { name = "fduc",                     type = "float" },
    { name = "fdpttl",                   type = "float" },
    { name = "fdpa",                     type = "float" },   
    { name = "fdpb",                     type = "float" },
    { name = "fdpc",                     type = "float" },
    { name = "hrpttl",                   type = "float" },
    { name = "hrpa",                     type = "float" }, 
    { name = "hrpb",                     type = "float" },
    { name = "hrpc",                     type = "float" },
    { name = "thdia",                    type = "float" }, 
    { name = "hr2ia",                    type = "float" },
    { name = "hr3ia",                    type = "float" },
    { name = "hr4ia",                    type = "float" },
    { name = "hr5ia",                    type = "float" },
    { name = "hr6ia",                    type = "float" },
    { name = "hr7ia",                    type = "float" },
    { name = "hr8ia",                    type = "float" },
    { name = "hr9ia",                    type = "float" },
    { name = "hr10ia",                   type = "float" }, 
    { name = "hr11ia",                   type = "float" },
    { name = "hr12ia",                   type = "float" },
    { name = "hr13ia",                   type = "float" },
    { name = "hr14ia",                   type = "float" },
    { name = "hr15ia",                   type = "float" },
    { name = "hr16ia",                   type = "float" },
    { name = "hr17ia",                   type = "float" },
    { name = "thdib",                    type = "float" }, 
    { name = "hr2ib",                    type = "float" },
    { name = "hr3ib",                    type = "float" },
    { name = "hr4ib",                    type = "float" },
    { name = "hr5ib",                    type = "float" },
    { name = "hr6ib",                    type = "float" },
    { name = "hr7ib",                    type = "float" },
    { name = "hr8ib",                    type = "float" },
    { name = "hr9ib",                    type = "float" }
]

**Comment by wanyikang** [comment]
#传感器场景
[sensor_info]                               # 场景名称
format = "csv"                              # 样例数据文件格式，可以是 json 或 csv，具体字段应至少包含 subTableName、tags、fields 指定的字段。
filePath = "data/sensor_info.csv"           # 样例数据文件路径，程序会循环使用该文件数据
separator = ","                             # csv 样例文件中字段分隔符，默认逗号

stname = "sensor_info"                      # 超级表名称
subTableName = "devid"                      # 使用样例数据中指定字段当作子表名称一部分，子表名称格式为 t_subTableName_stname，扩展表名为 t_subTableName_stname_i。
timestamp = "ts"                            # 使用 fields 中哪个字段当作主键，类型必须为 timestamp
timestampType="millisecond"                 # 样例数据中主键时间字段是 millisecond 还是 dateTime 格式
#timestampTypeFormat = "2006-01-02 15:04:05.000"  # 主键日期时间格式，timestampType 为 dateTime 时需要指定
tags = [
    # 标签列表，name 为标签名称，type 为标签类型
    { name = "location",           type = "binary(20)" },
    { name = "color",              type = "binary(16)" },
    { name = "devgroup",           type = "int" },
]

fields = [
    # 字段列表，name 为字段名称，type 为字段类型
    { name = "ts",                  type = "timestamp" },
    { name = "temperature",         type = "int" },
    { name = "humidity",            type = "float" },
]

#摄像头检测场景
[camera_detection]                          # 场景名称
format = "json"                             # 样例数据文件格式，可以是 json 或 csv，具体字段应至少包含 subTableName、tags、fields 指定的字段。
filePath = "data/camera_detection.json"     # 样例数据文件路径，程序会循环使用该文件数据
#separator = ","                            # csv 样例文件中字段分隔符，默认逗号, 如果是 json 文件可以不用配置
 
stname = "camera_detection"                 # 超级表名称
subTableName = "sensor_id"                  # 使用样例数据中指定字段当作子表名称一部分，子表名称格式为 t_subTableName_stname，扩展表名为 t_subTableName_stname_i。
timestamp = "ts"                            # 使用 fields 中哪个字段当作主键，类型必须为 timestamp
timestampType="dateTime"                    # 样例数据中主键时间字段是 millisecond 还是 dateTime 格式
timestampTypeFormat = "2006-01-02 15:04:05.000"  # 主键日期时间格式，timestampType 为 dateTime 时需要指定
tags = [
    # 标签列表，name 为标签名称，type 为标签类型
    { name = "home_id",           type = "binary(30)" },
    { name = "object_type",       type = "int" },
    { name = "object_kind",       type = "binary(20)" },
]

fields = [
    # 字段列表，name 为字段名称，type 为字段类型
    { name = "ts",                type = "timestamp" },
    { name = "states",            type = "tinyint" },
    { name = "battery_voltage",   type = "float" },
]

#electric场景
[pot_electric]                              # 场景名称
format = "json"                             # 样例数据文件格式，可以是 json 或 csv，具体字段应至少包含 subTableName、tags、fields 指定的字段。
filePath = "data/pot_electric.json"         # 样例数据文件路径，程序会循环使用该文件数据
#separator = ","                            # csv 样例文件中字段分隔符，默认逗号, 如果是 json 文件可以不用配置
 
stname = "pot_electric"                     # 超级表名称
subTableName = "mtid"                       # 使用样例数据中指定字段当作子表名称一部分，子表名称格式为 t_subTableName_stname，扩展表名为 t_subTableName_stname_i。
timestamp = "time"                          # 使用 fields 中哪个字段当作主键，类型必须为 timestamp
timestampType="dateTime"                    # 样例数据中主键时间字段是 millisecond 还是 dateTime 格式
timestampTypeFormat = "2006-01-02 15:04:05.000"  # 主键日期时间格式，timestampType 为 dateTime 时需要指定
tags = [
    # 标签列表，name 为标签名称，type 为标签类型
    { name = "cid",           type = "int" },
]

fields = [
    # 字段列表，name 为字段名称，type 为字段类型
    { name = "time",                     type = "timestamp" },
    { name = "eq_type",                  type = "binary(30)" },  
    { name = "data_topic",               type = "binary(30)" },  
    { name = "sid",                      type = "binary(50)" },
    { name = "soft_hardware_version",    type = "binary(30)" },
    { name = "meter_sn",                 type = "binary(50)" },
    { name = "data_key",                 type = "binary(50)" },
    { name = "mtid",                     type = "int" },
    { name = "pid",                      type = "int" },
    { name = "ua",                       type = "float" },  
    { name = "ub",                       type = "float" }, 
    { name = "uc",                       type = "float" }, 
    { name = "ia",                       type = "float" }, 
    { name = "ib",                       type = "float" }, 
    { name = "ic",                       type = "float" }, 
    { name = "pa",                       type = "float" }, 
    { name = "pb",                       type = "float" }, 
    { name = "pc",                       type = "float" }, 
    { name = "pttl",                     type = "float" },
    { name = "qa",                       type = "float" }, 
    { name = "qb",                       type = "float" },
    { name = "qc",                       type = "float" },
    { name = "qttl",                     type = "float" }, 
    { name = "sa",                       type = "float" },  
    { name = "sb",                       type = "float" }, 
    { name = "sc",                       type = "float" }, 
    { name = "sttl",                     type = "float" }, 
    { name = "cosa",                     type = "float" },
    { name = "cosb",                     type = "float" },
    { name = "cosc",                     type = "float" },
    { name = "costtl",                   type = "float" },
    { name = "phA",                      type = "float" }, 
    { name = "phB",                      type = "float" },
    { name = "phC",                      type = "float" },
    { name = "kvarha_minus",             type = "float" }, 
    { name = "kvarhb_minus",             type = "float" },
    { name = "kvarhc_minus",             type = "float" },
    { name = "kvarha_plus",              type = "float" },
    { name = "kvarhb_plus",              type = "float" },
    { name = "kvarhc_plus",              type = "float" },
    { name = "kwha_minus",               type = "float" }, 
    { name = "kwhb_minus",               type = "float" },
    { name = "kwhc_minus",               type = "float" },
    { name = "kwha_plus",                type = "float" },
    { name = "kwhb_plus",                type = "float" },
    { name = "kwhc_plus",                type = "float" },
    { name = "angleAB",                  type = "float" }, 
    { name = "angleAC",                  type = "float" },
    { name = "kwhttl_minus",             type = "float" },
    { name = "kwhttl_plus",              type = "float" },
    { name = "kvarhttl_minus",           type = "float" }, 
    { name = "kvarhttl_plus",            type = "float" },  
    { name = "ctnum",                    type = "float" }, 
    { name = "freq",                     type = "float" }, 
    { name = "mdp",                      type = "float" },
    { name = "mdptime",                  type = "timestamp" },
    { name = "mdkwh",                    type = "float" }, 
    { name = "mdkwhtime",                type = "timestamp" }, 
    { name = "ubl",                      type = "float" }, 
    { name = "ibl",                      type = "float" }, 
    { name = "fdia",                     type = "float" }, 
    { name = "fdua",                     type = "float" },
    { name = "fdib",                     type = "float" },
    { name = "fdub",                     type = "float" },
    { name = "fdic",                     type = "float" },
    { name = "fduc",                     type = "float" },
    { name = "fdpttl",                   type = "float" },
    { name = "fdpa",                     type = "float" },   
    { name = "fdpb",                     type = "float" },
    { name = "fdpc",                     type = "float" },
    { name = "hrpttl",                   type = "float" },
    { name = "hrpa",                     type = "float" }, 
    { name = "hrpb",                     type = "float" },
    { name = "hrpc",                     type = "float" },
    { name = "thdia",                    type = "float" }, 
    { name = "hr2ia",                    type = "float" },
    { name = "hr3ia",                    type = "float" },
    { name = "hr4ia",                    type = "float" },
    { name = "hr5ia",                    type = "float" },
    { name = "hr6ia",                    type = "float" },
    { name = "hr7ia",                    type = "float" },
    { name = "hr8ia",                    type = "float" },
    { name = "hr9ia",                    type = "float" },
    { name = "hr10ia",                   type = "float" }, 
    { name = "hr11ia",                   type = "float" },
    { name = "hr12ia",                   type = "float" },
    { name = "hr13ia",                   type = "float" },
    { name = "hr14ia",                   type = "float" },
    { name = "hr15ia",                   type = "float" },
    { name = "hr16ia",                   type = "float" },
    { name = "hr17ia",                   type = "float" },
    { name = "thdib",                    type = "float" }, 
    { name = "hr2ib",                    type = "float" },
    { name = "hr3ib",                    type = "float" },
    { name = "hr4ib",                    type = "float" },
    { name = "hr5ib",                    type = "float" },
    { name = "hr6ib",                    type = "float" },
    { name = "hr7ib",                    type = "float" },
    { name = "hr8ib",                    type = "float" },
    { name = "hr9ib",                    type = "float" }
]

**Comment by wanyikang** [comment]
自定义场景下的json数据文件
[pot_electric.zip](https://github.com/taosdata/TDengine/files/6293603/pot_electric.zip)

**Comment by wanyikang** [comment]
I do test again, and this time only one node memory full
![t1](https://user-images.githubusercontent.com/5843919/114373805-8eacb080-9bb5-11eb-8244-15f59c70d160.png)
![t2](https://user-images.githubusercontent.com/5843919/114373817-90767400-9bb5-11eb-89c6-d41742f86e42.png)
![t3](https://user-images.githubusercontent.com/5843919/114373829-92d8ce00-9bb5-11eb-9914-fba9239d31c8.png)

**Comment by wanyikang** [comment]
@yu285 ,any thought?

**Comment by yu285** [comment]
Currently , 2.0.19 has fixed this issue .
