### ISSUE TITLE
float can closed auto supplement？ or other data form？

### ISSUE THREAD

**Issue by liuhuanone** [taosdata/TDengine#578]
我插入的数据是两位小数，如65.09，结果会自动补充，65,090000，怎么不让自动补充，限制小说点位数

**Comment by hzcheng** [comment]
是在shell中吗？如果在您自己的应用中，您应该可以自己配置显示的精度。

**Comment by liuhuanone** [comment]
> 是在shell中吗？如果在您自己的应用中，您应该可以自己配置显示的精度
我是通过restful查询获取的数据，通过taos客户端查看数据也是一样的。在应用端批量处理不方便

**Comment by liuhuanone** [comment]
> 是在shell中吗？如果在您自己的应用中，您应该可以自己配置显示的精度。

我是通过restful查询获取的数据，通过taos客户端查看数据也是一样的。在应用端批量处理不方便

**Comment by fangpanpan** [comment]
目前我们还没有配置可以设置小数点的显示位数。如果您是因为数据太长客户端查看不方便，那么您可以在命令后面加上\G 从行显示变成列显示。
