### ISSUE TITLE
"select ... limit " doesn't take effect on version 2.0.19

### ISSUE THREAD

**Issue by shitongy** [taosdata/TDengine#5790]
**Bug Description**
2.0.19版本带有 LIMIT 子句的 SELECT 语句，设置起始行参数无效

**To Reproduce**
1. 设置查询
select * from tabel limit 0,10; 
select * from tabel limit 10,10; 
2. 检查查询结果
3. 起始行参数没有效果，均从第一行开始查询十行后展示结果

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - TDengine Version [e.g. 2.0.19.1]

**Additional Context**

**Comment by yu285** [comment]
![image](https://user-images.githubusercontent.com/74105241/115184910-60792480-a111-11eb-812b-a0fb9094196e.png)
您好，这边使用19.1版本，并没能复现出您的问题。可以微信交流详情：15652223354。

**Comment by yu285** [comment]
> **Bug Description**
> 2.0.19版本带有 LIMIT 子句的 SELECT 语句，设置起始行参数无效
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. 设置查询
>    select * from tabel limit 0,10;
>    select * from tabel limit 10,10;
> 2. 检查查询结果
> 3. 起始行参数没有效果，均从第一行开始查询十行后展示结果
> 
> **Expected Behavior**
> 
> **Screenshots**
> 
> **Environment (please complete the following information):**
> 
> * OS: [e.g. CentOS 7.0]
> * TDengine Version [e.g. 2.0.19.1]
> 
> **Additional Context**

您好，请问问题如何了？

**Comment by shitongy** [comment]
您好，
&nbsp; &nbsp; &nbsp;drop表之后重新建表，问题解决，暂时没有复现出来。没有其它的异常操作，怀疑是集群中，客户端使用rpm包安装，服务端使用的tar包安装导致。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taosdata/TDengine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月24日(星期六) 下午5:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [taosdata/TDengine] "select ... limit " doesn't take effect on version 2.0.19 (#5790)





  
Bug Description
 2.0.19版本带有 LIMIT 子句的 SELECT 语句，设置起始行参数无效
 
To Reproduce
 Steps to reproduce the behavior:
  
设置查询
 select * from tabel limit 0,10;
 select * from tabel limit 10,10;
 
检查查询结果
 
起始行参数没有效果，均从第一行开始查询十行后展示结果
  
Expected Behavior
 
Screenshots
 
Environment (please complete the following information):
  
OS: [e.g. CentOS 7.0]
 
TDengine Version [e.g. 2.0.19.1]
  
Additional Context
  
您好，请问问题如何了？

**Comment by yu285** [comment]
好的，那先关闭此github问题，如有需要可以添加微信15652223354交流
