### ISSUE TITLE
Using subquery,Abnormal exit of program 

### ISSUE THREAD

**Issue by yushxzh** [taosdata/TDengine#5791]
**Bug Description**
Using subquery segmentation fault (core damped)

**To Reproduce**
1. login 
2. Execute SQL "SELECT
	day_gen
FROM (
	SELECT
		day_gen
	FROM
		photovoltaic
	WHERE
		ts > '2021-04-06 00:00:00'
		AND ts < '2021-04-07 00:00:00'
	ORDER BY
		ts DESC
	LIMIT 100)"
3. Abnormal exit of program,Segmentation fault (core dumped)

**Expected Behavior**
Normal execution, return result

**Screenshots**
![WX20210413-105327](https://user-images.githubusercontent.com/8110962/114490001-a7b17200-9c46-11eb-8183-b44014275e91.png)

**Environment (please complete the following information):**
 - OS: [Ubuntu 18.04.5 LTS]
 - 16G Memory, 4 Core CPU, current Disk Space 956G
 - TDengine Version [2.0.18]

**Comment by cpvmrd** [comment]
Nested query is not supported in TDengine.

**Comment by cpvmrd** [comment]
This issue was closed because it has been inactive for too many days.
