### ISSUE TITLE
 timestamp out of range

### ISSUE THREAD

**Issue by yikuide** [taosdata/TDengine#580]
**Bug Description**
timestamp limits on TDengine server version:1.6.2.2

**To Reproduce**
1. Go to taos shell
2. Type in follows sql commands:
  create database if not exists db1;
  use db1;
  create table if not exists tb1 (ts timestamp, temperature int, humidity float);
  insert into tb1 values('2010-01-01 00:00:00.000', 37, 50.1);
  insert into tb1 values('2009-01-01 00:00:00.000', 37, 50.1);
3. See error
   TSDB error: timestamp out of range
**Expected Behavior**
  '2009-01-01 00:00:00.000' should be treated as a valid timestamp

**Screenshots**
![image](https://user-images.githubusercontent.com/21164213/65829295-91e39280-e2d6-11e9-884b-09339d61b3b7.png)

**Environment**
 - OS:  Ubuntu 18.04.2 LTS
 - Memory: 64g, CPU: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz, current Disk Space: 6.9T
 - TDengine Version:  1.6.2.2

**Comment by hjxilinx** [comment]
The default retention time for a database is 10 YEARS, which is acquired by the following command:

> show databases;

The timestamp of "2009-01-01 00:00:00.000" has beyond the retention period.

**Comment by yikuide** [comment]
thks
