### ISSUE TITLE
sort the supertable : Result set too large to be sorted

### ISSUE THREAD

**Issue by huimiezhe** [taosdata/TDengine#5815]
![Uploading 1.png…]()

**Comment by jadedrip** [comment]
明知道数据量大还排序？想吧数据库搞挂？

**Comment by huimiezhe** [comment]
那如果不排序，我查看最新的传感器数据得从最后一页开始看？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月14日(星期三) 下午5:29
收件人: ***@***.***&gt;; 
抄送: "低@***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [taosdata/TDengine] 超级表数据量大时排序出错，提示Result set too large to be sorted (#5815)






明知道数据量大还排序?想吧数据库搞挂?

—
您正在接收此消息，因为您编写了线程。
直接回复此邮件，在GitHub上查看，或取消订阅.

**Comment by jadedrip** [comment]
设定时间范围，把结果的数据量降下来，然后再排序。排序本身是非常耗资源的操作，任何数据库都一样，不能对大数据集排序。

**Comment by huimiezhe** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月14日(星期三) 下午5:56
收件人: ***@***.***&gt;; 
抄送: "低@***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [taosdata/TDengine] 超级表数据量大时排序出错，提示Result set too large to be sorted (#5815)





 
设定时间范围，把结果的数据量降下来，然后再排序。排序本身是非常耗资源的操作，任何数据库都一样，不能对大数据集排序。

**Comment by cpvmrd** [comment]
可以看下maxNumOfOrderedRes 参数。

**Comment by huimiezhe** [comment]
> 可以看下maxNumOfOrderedRes参数。

这个在哪看，是可以修改的吗

**Comment by cpvmrd** [comment]
> > 可以看下maxNumOfOrderedRes参数。
> 
> 这个在哪看，是可以修改的吗

在服务端配置文件中修改。

**Comment by yu285** [comment]
在/etc/taos/taos.cfg中可以看到，可以修改，上限100万。

**Comment by huimiezhe** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月19日(星期一) 上午9:54
收件人: ***@***.***&gt;; 
抄送: "低@***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [taosdata/TDengine] sort the supertable : Result set too large to be sorted (#5815)





   
可以看下maxNumOfOrderedRes参数。
  
这个在哪看，是可以修改的吗
  
在服务端配置文件中修改。

**Comment by huimiezhe** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yu ***@***.***&gt;; 
发送时间: 2021年4月19日(星期一) 中午1:24
收件人: ***@***.***&gt;; 
抄送: "低@***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [taosdata/TDengine] sort the supertable : Result set too large to be sorted (#5815)





 
在/etc/taos/taos.cfg中可以看到，可以修改，上限100万。
