### ISSUE TITLE
Can't find the super table containing capital letters

### ISSUE THREAD

**Issue by Hawke323** [taosdata/TDengine#582]
例如describe SuperTableExample则会返回invalid table
尽管再次建表的话则会提示表已经存在
同时无法以该表为模板创建子表，会显示invalid table

**Comment by hjxilinx** [comment]
TDengine 不区分表名的大小写。您可以通过show tables查看已经创建的表。

**Comment by Hawke323** [comment]
> TDengine 不区分表名的大小写。您可以通过show tables查看已经创建的表。

确实是可以查看到的，但describe无法查到名称含有大写字母的表，insert into <子表名称> using <超级表名>时也会显示找不到超级表，会影响到业务逻辑
希望能自动在建表时改为小写，或者加入对大写字母的支持

**Comment by hjxilinx** [comment]
您是否将表名用引号引起来了？

**Comment by Hawke323** [comment]
> 您是否将表名用引号引起来了？

没有
倒是新建了一个同名但均为小写的super table后，可以通过describe大写表名来查看结构了，也可以通过insert xxxx using XXXX插入子表了，但是插入的子表也属于小写super table名下而非大写的名下

taos> show stables;
                              name                              |     created time     |columns| tags  |  tables   |
====================================================================================================================
ExampleDataClass                                                | 19-09-29 15:32:50.286|      5|      3|          0|
exampledataclass                                                | 19-09-29 16:40:05.083|      5|      3|          1|
Query OK, 17 row(s) in set (0.000579s)

虽然大写表下的tables是0，但是可以通过select * from ExampleDataClass; 返回和select * from exampledataclass;一样的结果

**Comment by Hawke323** [comment]
**补充一下**，我是通过Prepared Statement建这些表的，表名是通过setString的方法对占位符赋值进行输入的。

**Comment by hjxilinx** [comment]
那应该是TD的JDBC中的Prepared Statement有问题，默认情况下TD会对SQL语句中所有非字符串全部转换成为小写。您如果需要删除多余的那个Super table，可以使用单引号将具有大写字母的表引起来。

> drop table 'ExampleDataClass'

来删掉。

**Comment by Hawke323** [comment]
> 那应该是TD的JDBC中的Prepared Statement有问题，默认情况下TD会对SQL语句中所有非字符串全部转换成为小写。您如果需要删除多余的那个Super table，可以使用单引号将具有大写字母的表引起来。
> 
> > drop table 'ExampleDataClass'
> 
> 来删掉。

嗯，TD的JDBC中的Prepared Statement存在很多问题，只能暂时使用普通的Statement来代替了
