### ISSUE TITLE
No effect when assign values to the placeholder using Prepared Statement.

### ISSUE THREAD

**Issue by Hawke323** [taosdata/TDengine#583]
无论如何在对占位符赋值时指定Index，PreparedStatement依然会按照调用setXXX的顺序进行赋值。

例如如下报错信息：
Para #6 is int, value = null
Para #7 is char, value = "abcd"
Para #2 is char, value = "wtf"
Para #8 is boolean, value = true
Para #3 is boolean, value = null
java.sql.SQLException: TDengine Error: invalid SQL: invalid SQL: near "values  ('NULL','"abcd"','"wtf"',true,'NULL')" syntax error

程序是期望按照从上到下的顺序，对6 7 2 8 3位置的占位符进行对应的赋值
但是实际上可以看见参数并未按照提供的占位符index（是6 7 2 8 3）进行赋值，而是按照调用的顺序赋值（1 2 3 4 5），导致('NULL','"abcd"','"wtf"',true,'NULL')的结果

**Comment by hjxilinx** [comment]
PrepareStatement 现在有点问题，我们后面会修复这个问题。建议您先不要使用PrepareStatement.

**Comment by Hawke323** [comment]
> PrepareStatement 现在有点问题，我们后面会修复这个问题。建议您先不要使用PrepareStatement.

辛苦了 还希望能尽快推出PrepareStatement的toString功能，方便debug时候使用
谢谢！

**Comment by guanshengliang** [comment]
Check if this feature is currently supported @xieyinglin
