### ISSUE TITLE
can not create table

### ISSUE THREAD

**Issue by druidfund** [taosdata/TDengine#5834]
**Bug Description**
 install  tdengine 2.0.19.1 and use taosdemo to insert demo data, report:
create database test success!

ERROR: Failed to run create table if not exists test.t0 using test.meters tags (0, 'shanghai') , reason: Cluster not ready
ERROR: queryDbExec() failed. buffer:
create table if not exists test.t0 using test.meters tags (0, 'shanghai')
ERROR: Failed to run create table if not exists test.t1000 using test.meters tags (1000, 'shanghai') , reason: Cluster not ready

**To Reproduce**
1. install tdengine 2.0.19.1 
2. run taosdemo
4. press enter
5. see error

**Screenshots**
![image](https://user-images.githubusercontent.com/48118383/114981929-4fd26f80-9ec1-11eb-814a-95b560d8535f.png)

**Environment (please complete the following information):**
 - OS: [CentOS 7.3]
 - TDengine Version [2.0.19.1 ]

**Comment by cpvmrd** [comment]
检查一下FQDN配置。

**Comment by druidfund** [comment]
> FQDN

不是集群，只是单机版也需要配置FQDN吗？

**Comment by yu285** [comment]
> > FQDN
> 
> 不是集群，只是单机版也需要配置FQDN吗？

您好，关于配置问题请添加微信15652223354方便快速排查，也方便日后问题沟通。
