### ISSUE TITLE
timestamp field comparing invaild

### ISSUE THREAD

**Issue by sytpb** [taosdata/TDengine#5835]
ver 2.18 

![image](https://user-images.githubusercontent.com/12178686/114981595-d3d82780-9ec0-11eb-893d-eb428de2a0ec.png)
data in tables as 
![image](https://user-images.githubusercontent.com/12178686/114982685-57dedf00-9ec2-11eb-95d8-f3fcfb6db3cb.png)

[something look like unnormal for field outstamp]
![image](https://user-images.githubusercontent.com/12178686/114982133-9fb13680-9ec1-11eb-8355-d187f6d1e2b3.png)

[correct for field stamp ]
![image](https://user-images.githubusercontent.com/12178686/114982297-d71fe300-9ec1-11eb-9ff7-a9e06ce1b0bc.png)

bug or something i was wrong ?

**Comment by sytpb** [comment]
![Uploading image.png…]()

**Comment by sytpb** [comment]
![image](https://user-images.githubusercontent.com/12178686/114982633-47c6ff80-9ec2-11eb-91c7-86ce05ce04e1.png)

**Comment by yu285** [comment]
> ver 2.18
> 
> ![image](https://user-images.githubusercontent.com/12178686/114981595-d3d82780-9ec0-11eb-893d-eb428de2a0ec.png)
> data in tables as
> ![image](https://user-images.githubusercontent.com/12178686/114982685-57dedf00-9ec2-11eb-95d8-f3fcfb6db3cb.png)
> 
> [something look like unnormal for field outstamp]
> ![image](https://user-images.githubusercontent.com/12178686/114982133-9fb13680-9ec1-11eb-8355-d187f6d1e2b3.png)
> 
> [correct for field stamp ]
> ![image](https://user-images.githubusercontent.com/12178686/114982297-d71fe300-9ec1-11eb-9ff7-a9e06ce1b0bc.png)
> 
> bug or something i was wrong ?

we will discuss this scenario  ,will let u know once get  result.

**Comment by yu285** [comment]
we have create a task to fix this , will let u know once it is fixed .

**Comment by yu285** [comment]
This issue has been fixed in the 2.0.20 version . please upgrade your TDengine , thanks .
