### ISSUE TITLE
How to configure the number of threads in taos_connect?

### ISSUE THREAD

**Issue by hubblezzhu** [taosdata/TDengine#5837]
您好，我在linux下使用 <taos.h> 中 的taos_connect后发现会创建很多个线程
请问下有没有设置方法可以让只起一个连数据库的线程？非常感谢！

**Comment by cpvmrd** [comment]
客户端配置文件中有个参数：numOfThreadsPerCore(默认是1.0）。

用到的线程数为：numOfThreadsPerCore * coreNum/2。

**Comment by hubblezzhu** [comment]
可以将numOfThreadsPerCore设置为 0.0 吗

**Comment by hubblezzhu** [comment]
> 客户端配置文件中有个参数：numOfThreadsPerCore(默认是1.0）。
> 
> 用到的线程数为：numOfThreadsPerCore * coreNum/2。

非常感谢 ：）

**Comment by cpvmrd** [comment]
> 可以将numOfThreadsPerCore设置为 0.0 吗

不可以。
