### ISSUE TITLE
can't load library if using java web application to connect to the server in a docker

### ISSUE THREAD

**Issue by jiaoyilun** [taosdata/TDengine#585]
java web应用部署在docker里，基础镜像为jdk8，
我尝试把.so类库放在usr/lib64,  /usr/local/lib/, 带不带tos文件夹，
还尝试使用System.load(), System.loadLibrary()
各种方法都试了，都是提示no taos  in java.library.path

**Comment by guanshengliang** [comment]
使用tar包安装，解压后执行install_client.sh脚本可以只安装客户端。
如果只拷贝libtaos.so，那么参考正确安装的机器，将libtaos.so拷贝到`/usr/local/taos/lib`，并且设置好对应的软连接。

**Comment by liangyuanpeng** [comment]
@guanshengliang  Maybe the client should be easier to use

**Comment by jiaoyilun** [comment]
> 使用tar包安装，解压后执行install_client.sh脚本可以只安装客户端。
> 如果只拷贝libtaos.so，那么参考正确安装的机器，将libtaos.so拷贝到`/usr/local/taos/lib`，并且设置好对应的软连接。

需要建立什么样的软连接，没看到相关资料

**Comment by jiaoyilun** [comment]
> 使用tar包安装，解压后执行install_client.sh脚本可以只安装客户端。
> 如果只拷贝libtaos.so，那么参考正确安装的机器，将libtaos.so拷贝到`/usr/local/taos/lib`，并且设置好对应的软连接。

已经在镜像内打包执行install_client.sh成功，执行taos时，提示
failed to get charset, please set the valid charset in config file

**Comment by jiaoyilun** [comment]
已解决，在docker镜像内打包了安装包并执行了install_client,同时修改了包内的配置文件中的编码，问题暂时解决，但是真心是很不方便
