### ISSUE TITLE
DROP DATABASE seems to leave behind a table when using the "tables" configuration option

### ISSUE THREAD

**Issue by mrigger** [taosdata/TDengine#586]
Hi everyone,

consider the following sequence of statements:

```
CREATE DATABASE db tables 1;
USE db;
CREATE TABLE t0(c0 TIMESTAMP, c1 int);
CREATE TABLE t1(c0 TIMESTAMP, c1 int);
-- INSERT INTO t1(c0) VALUES (0); results in "TSDB error: invalid query message"
DROP DATABASE db;
CREATE DATABASE db;
USE db;
CREATE TABLE t0(c0 TIMESTAMP, c1 int);
CREATE TABLE t1(c0 TIMESTAMP, c1 int); -- TSDB error: table already there
```

Note that the first database is created with `tables 1` configuration option. When trying to insert into `t1`, the `INSERT` statement fails with `TSDB error: invalid query message`, which likely already demonstrates a bug; if creating this table is illegal, the `CREATE TABLE` should have failed with an error. Even after dropping the database, and creating a new one with the same name, the second `CREATE TABLE` for t1 fails with `TSDB error: table already there`, even though the `DROP DATABASE` should have deleted it.

I found this bug on the latest trunk 3bf7180 using Ubuntu.

**Comment by jtao1735** [comment]
this is a bug triggered by "tables 1" option

**Comment by guanshengliang** [comment]
We will fix this bug as soon as possible.

**Comment by guanshengliang** [comment]
This is a bug when assigning the sid of the table
Will not be allowed to create a database of tables 1, the minimum tables is set to 2
The fix code has been submitted to the master, the next version 1.6.4.5 will include this fix

**Comment by mrigger** [comment]
Thank you very much for the fix!

**Comment by guanshengliang** [comment]
Version 2.0 has been fixed and this problem does not exist, you can download and test it

**Comment by guanshengliang** [comment]
This issue has been resolved, and this issue has not been replied for a long time, so close it
