### ISSUE TITLE
Does database / table / field name support Chinese Character ?

### ISSUE THREAD

**Issue by arbilence** [taosdata/TDengine#5860]
taos>  create database "test1";
Query OK, 0 of 0 row(s) in database (0.007976s)
taos>  create database "test测试";
DB error: invalid SQL: invalid db name (0.000612s)

C驱动测试代码:
================================Failed to run create table if not exists m1 (ts timestamp, ti tinyint, si smallint, i int, bi bigint, f float, d double, b binary(10), 数量 int), reason: syntax error near 'unrecognized token: "数量 int)"'

**Comment by cpvmrd** [comment]
不支持。

**Comment by arbilence** [comment]
Thanks.
