### ISSUE TITLE
insertion performs drops drastically when arbitrary node in the cluster down using the restful way

### ISSUE THREAD

**Issue by xuyihan997** [taosdata/TDengine#5867]
工作任务，需要写了一个flink作业处理数据写入tdengine。
同事已经搭好 3个节点的集群，版本是2.0.8.2。
DB备份数也是3。
因为要提交到yarn上跑，所以只能使用restful connector。
flink sink并行度也设为是3，初始化每一个subtask各连一个tdengine节点ip发送http请求。如果一个节点故障后，会连接到随机另一个可用节点。三个节点都正常时，写入平稳。

现在出现问题是为了测试tdengine高可用。手动停掉随机一个tdengine节点后，模拟故障。出现以下情况：

（1）多数情况写入效率从几W/秒降到几十/秒，没有明显报错。手动恢复停掉节点，写入效率马上恢复。
（2）少数情况：手动恢复节点后，报错vnode memory full because commit failed，无法写入。

**Comment by cpvmrd** [comment]
我们着手排查一下。

**Comment by cpvmrd** [comment]
建议升级到最新到2.0.19.1版本测试。最新版本解决了之前存在的一些问题。

如果仍然存在，我们可以让研发同事远程一起调试定位下问题。

**Comment by cpvmrd** [comment]
This issue was closed because it has been inactive for too many days.
