### ISSUE TITLE
Likely typo in configuration option "abloks"

### ISSUE THREAD

**Issue by mrigger** [taosdata/TDengine#587]
Consider the following statement:

`CREATE DATABASE test abloks 0;`

This statement results in an error `TSDB error: invalid SQL: syntax error near "abloks 0;"`. I think the configuration option `abloks` in the documentation at https://www.taosdata.com/en/documentation/administrator/#Configuration-on-Server should be spelled as `ablocks` instead, which would cause the statement to execute successfully.

**Comment by jtao1735** [comment]
Yes, it is a spelling error

**Comment by jtao1735** [comment]
it is fixed
