### ISSUE TITLE
java.sql.SQLException: TDengine ERROR (80000600): Invalid table ID

### ISSUE THREAD

**Issue by feigudian** [taosdata/TDengine#5873]
**Bug Description**
When 1000 threads write to tdengine, errors return like below:
java.sql.SQLException: TDengine ERROR (80000600): Invalid table ID

Another kind of error returns at the same time:
java.sql.SQLException: TDengine ERROR (80000014): Database not ready

Total Requests of Writing is 100,000,000, Failed Requests is 19748

log below:
04/21 10:44:21.663735 00042155 DND msg:0x7fd7c8001140, app:0xf36233 type:create-table is reput into mwrite queue:0x138eaa0, retry times:0
04/21 10:44:21.664098 00042352 TDB ERROR vgId:3 failed to get table to insert data, uid 844438318559607 tid 798
04/21 10:44:21.664140 00042352 TDB ERROR vgId:3 failed to insert data since Invalid table ID

**To Reproduce**
1000 Threads writing using JMeter through JDBC

**Expected Behavior**
NO ERRORS RETURN

**Screenshots**

**Environment**
 - OS: CentOS 7.8.2003
 - Memory: 256GB
 - CPU: 2.2GHz 48 processors
 - current Disk Space: 30GB
 - TDengine Version: 2.0.19.1

**Additional Context**

**Comment by yu285** [comment]
You can add my WeChat 15652223354 for further investigation .

thank u

**Comment by yu285** [comment]
可能是自动减表期间，建表操作还没同步完，就发起了写入导致。也有可能是UDP不稳定，导致建表同步失败，这样也会导致出这个问题。所以这是自动减表的一个坏处，在网络不稳的时候，可能会出问题。

所以建议非必要情况下，使用正常减表加普通写入。必要情况下，在配置文件写上rpcforceTcp 1 （建议直接升级到2.4.0.10） ，从而激活强制TCP通信，更稳定。

**Comment by xleili** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
