### ISSUE TITLE
Invalid insertion sql after upgrading from 2.0.8 to 2.0.20

### ISSUE THREAD

**Issue by xuyihan997** [taosdata/TDengine#5876]

**Comment by xuyihan997** [comment]
原本使用2.0.8.2，原插入语句使用自动建表特性，选择【部分】字段插入，类似于下面这样：
INSERT INTO DBNAME.TABLENAME USING DBNAME.STABLENAME TAGS (TAG1,TAG2) (ts，字段1) VALUES （ts，值1）。
现在升级到了2.0.20.0，这样的插入语句就要报invalid sql，原因似乎是不再支持选择部分表字段，即上面 （ts，字段1）这块。

**Comment by xuyihan997** [comment]
请问这是否是bug还是有意为之。如果刻意设计成这样，那不是意味这我之前写的所有sql因为升级版本全部都要修改，这样的体验未免。。。

**Comment by cpvmrd** [comment]
> 原本使用2.0.8.2，原插入语句使用自动建表特性，选择【部分】字段插入，类似于下面这样：
> INSERT INTO DBNAME.TABLENAME USING DBNAME.STABLENAME TAGS (TAG1,TAG2) (ts，字段1) VALUES （ts，值1）。
> 现在升级到了2.0.20.0，这样的插入语句就要报invalid sql，原因似乎是不再支持选择部分表字段，即上面 （ts，字段1）这块。

抱歉造成困扰。这个之前在设计上的语法是这样：

INSERT INTO tb_name USING stb_name (tag_name1, ...) TAGS (tag_value1, ...) VALUES (field_value1, ...);

tag_name绑定逻辑上应该这样写。不过之前的写法也支持。2.0.20.0版本解决了之前的一个bug，限制了这种语法。之后版本会考虑重新开放。

**Comment by cpvmrd** [comment]
> 请问这是否是bug还是有意为之。如果刻意设计成这样，那不是意味这我之前写的所有sql因为升级版本全部都要修改，这样的体验未免。。。

这个肯定不会。兼容性很重要。

**Comment by xuyihan997** [comment]
> > 原本使用2.0.8.2，原插入语句使用自动建表特性，选择【部分】字段插入，类似于下面这样：
> > INSERT INTO DBNAME.TABLENAME USING DBNAME.STABLENAME TAGS (TAG1,TAG2) (ts，字段1) VALUES （ts，值1）。
> > 现在升级到了2.0.20.0，这样的插入语句就要报invalid sql，原因似乎是不再支持选择部分表字段，即上面 （ts，字段1）这块。
> 
> 抱歉造成困扰。这个之前在设计上的语法是这样：
> 
> INSERT INTO tb_name USING stb_name (tag_name1, ...) TAGS (tag_value1, ...) VALUES (field_value1, ...);
> 
> tag_name绑定逻辑上应该这样写。不过之前的写法也支持。2.0.20.0版本解决了之前的一个bug，限制了这种语法。之后版本会考虑重新开放。

感谢你的回复.
我今天又试了下。
如下语句不行:
INSERT INTO tb_name USING stb_name (tag_name1, ...) TAGS (tag_value1, ...) （field_name1,...) VALUES (field_value1, ...);
但是前移成下面这样也就可以了:
INSERT INTO tb_name （field_name1,...) USING stb_name (tag_name1, ...) TAGS (tag_value1, ...)  VALUES (field_value1, ...);

**Comment by robotspace** [comment]
> 感谢你的回复.
> 我今天又试了下。
> 如下语句不行:
> INSERT INTO tb_name USING stb_name (tag_name1, ...) TAGS (tag_value1, ...) （field_name1,...) VALUES (field_value1, ...);
> 但是前移成下面这样也就可以了:
> INSERT INTO tb_name （field_name1,...) USING stb_name (tag_name1, ...) TAGS (tag_value1, ...) VALUES (field_value1, ...);

You've found the rabbit hole.

**Comment by fenghuazzm** [comment]
This issue was closed because it has been inactive for too many days.
