### ISSUE TITLE
suggest resultSet.getString in jdbc.rs.RestfulDriver to return literal when there is no record

### ISSUE THREAD

**Issue by Yuanbo-2019** [taosdata/TDengine#5879]
【Feature Request】
当库中没有记录的时候，使用jdbc.rs.RestfulDriver的resultSet.getString会抛出空指针异常。
![image](https://user-images.githubusercontent.com/57087115/115558505-64f63680-a2e5-11eb-801d-3147c86b2938.png)

【版本】
![image](https://user-images.githubusercontent.com/57087115/115558932-cb7b5480-a2e5-11eb-8c3c-42076f762b53.png)

【建议】
建议改成跟TSDBDriver一样可以返回字面量null，这样可以不用在调用时候处理异常。

**Comment by cpvmrd** [comment]
> 建议改成跟TSDBDriver一样可以返回字面量null，这样可以不用在调用时候处理异常。

可以参考一下JDBC的API：https://docs.oracle.com/javase/8/docs/api/java/sql/ResultSet.html

_if the value is SQL NULL, the value returned is null_

如果直接返回null，语义会冲突。

**Comment by cpvmrd** [comment]
This issue was closed because it has been inactive for too many days.
