### ISSUE TITLE
Erro Export

### ISSUE THREAD

**Issue by KhanhNguyen-2809** [taosdata/TDengine#588]
I am building a program and using TDengine. I encountered an error when exporting the file, the data returned only one row for all. If used on another computer, the data returned is correct. Can anybody help me solve this problem.
![Screenshot from 2019-10-02 10-39-09](https://user-images.githubusercontent.com/56059114/66016443-e36f6580-e500-11e9-8ba5-386b7082c501.png)
Meanwhile my database data:
![Screenshot from 2019-10-02 10-41-23](https://user-images.githubusercontent.com/56059114/66016531-3517f000-e501-11e9-80b7-baa74e736e0f.png)
I am sure that I have exported the correct table.
Thanks for watching.

**Comment by jtao1735** [comment]
May you post your code for exporting data here?
