### ISSUE TITLE
Inserting the "+" and "-" strings fails

### ISSUE THREAD

**Issue by mrigger** [taosdata/TDengine#589]
Consider the following statements:

```
CREATE TABLE t0(c0 TIMESTAMP, c1 BINARY(1));
INSERT INTO t0(c0, c1) VALUES (0, "-");
```
The `INSERT` fails with an error `TSDB error: invalid SQL: near "values (0, "-");" syntax error`. I would not expect this error, because inserting other single ASCII characters succeeds. For example, `INSERT INTO t0(c0, c1) VALUES (0, ".");` executes without error. It seems that this error only occurs for the strings `"-"` and `"+"`. When inserting strings such as `"-a"` or `"+3"`, this error also does not occur.

**Comment by plum-lihui** [comment]
There is a bug in string processing. When'-'and'+' are encountered, they are treated as positive and negative symbols instead of transparent strings.
We'll fix it soon.

**Comment by mrigger** [comment]
Any news on this?

**Comment by sangshuduo** [comment]
already fixed in new version.
