### ISSUE TITLE
给项目提出一些建议

### ISSUE THREAD

**Issue by linghongtao** [taosdata/TDengine#59]
一个开源项目要想快速传播和推广，离不开傻瓜化的安装文档，和方便的资源支持，为了方便我这样的低级程序员可以傻瓜上手，希望贵司做以下改进：
1安装文件可以支持wget +地址形式获得，而不是现在的输入邮箱，windows下载，然后还要上传到服务器，我知道你们想推广产品，不过开源版本还是建议变成wget获取的，这样会让更多我这样的沙雕程序员爱上项目，从而广泛使用。
2希望给予更详细的针对wget后的安装文档和相关的问题排查，解决办法。
3现在的使用方法介绍狠不错，api的使用案例建议更丰富一点，尤其是流行语言的api，希望更丰富，普通程序员，没有人会c的望能理解。
4希望尽快和spark，flink集成，并且有windows的仿真开发平台，方便沙雕普通程序员开发调试。

最后总结，任何一个开源项目，最后都是得普通程序员得天下，建议完毕，谢谢

**Comment by hjxilinx** [comment]
非常感谢，我们会认真考虑！

**Comment by yigemaserwang** [comment]
怎么能说是沙雕普通程序员呢，你这埋汰自己还是埋汰大家

**Comment by linghongtao** [comment]
主要是今天早上下载了贵司的软件包，往公司集群上传，结果因为公司集群安全原因，一直传不上去，感觉直接能力不行啊，另外贵司后面会有相关分布式理论原理类的介绍吗，如果有更好，因为我在培训学校兼职做老师，刚好科普给学生

**Comment by jtao1735** [comment]
关于TDengine的分布式，请参考这篇博文：https://www.taosdata.com/blog/2019/07/16/tdengine%e9%9b%86%e7%be%a4%e8%ae%be%e8%ae%a1/

**Comment by coder-chriswang** [comment]
@linghongtao 你的建议让我补充一下的东西，希望TDengine能很好地考虑一下Java生态，真的！
Java 和 物联网
“我确信 Java 的未来在物联网。我很希望 Oracle 及其伙伴们，会将注意力集中到为 Java 提供彻底的端到端的存储解决方案上：从终端设备开始，穿过网关，直至企业后端。构造这样一个故事，并且将其运作成功，这将有助于巩固 Java 未来 20 年里的地位。这不仅仅对整个产业蕴含着巨大的机会，而且我认为 Java 可以在这方面做得很好。”Mike Milinkovich （Eclipse 基金会执行董事）如此说道。

Oracle 对此表示赞同，前研发副总裁 Georges Saab 说：“ Java 是物联网时代最佳的技术。物联网遇到的很多挑战，都是20世纪90年代 Java 在桌面和客户端领域面对过的。你已经有了大量不同的硬件系统。你希望开发者们可以看清系统的细枝末节，深入理解它，并逐步向它迁移。Java 是少数允许你实现以上想法的技术。 ”

**Comment by hvritual** [comment]
> @linghongtao 你的建议让我补充一下的东西，希望TDengine能很好地考虑一下Java生态，真的！
> Java 和 物联网
> “我确信 Java 的未来在物联网。我很希望 Oracle 及其伙伴们，会将注意力集中到为 Java 提供彻底的端到端的存储解决方案上：从终端设备开始，穿过网关，直至企业后端。构造这样一个故事，并且将其运作成功，这将有助于巩固 Java 未来 20 年里的地位。这不仅仅对整个产业蕴含着巨大的机会，而且我认为 Java 可以在这方面做得很好。”Mike Milinkovich （Eclipse 基金会执行董事）如此说道。
> 
> Oracle 对此表示赞同，前研发副总裁 Georges Saab 说：“ Java 是物联网时代最佳的技术。物联网遇到的很多挑战，都是20世纪90年代 Java 在桌面和客户端领域面对过的。你已经有了大量不同的硬件系统。你希望开发者们可以看清系统的细枝末节，深入理解它，并逐步向它迁移。Java 是少数允许你实现以上想法的技术。 ”

只是因为利益关系罢了，IOT更多是需要去了解为什么需要IOT，怎么让IOT不鸡肋；目前太多为IOT而IOT了，数据被存储 80%以上的数据没有用途

**Comment by coder-chriswang** [comment]
> > @linghongtao 你的建议让我补充一下的东西，希望TDengine能很好地考虑一下Java生态，真的！
> > Java 和 物联网
> > “我确信 Java 的未来在物联网。我很希望 Oracle 及其伙伴们，会将注意力集中到为 Java 提供彻底的端到端的存储解决方案上：从终端设备开始，穿过网关，直至企业后端。构造这样一个故事，并且将其运作成功，这将有助于巩固 Java 未来 20 年里的地位。这不仅仅对整个产业蕴含着巨大的机会，而且我认为 Java 可以在这方面做得很好。”Mike Milinkovich （Eclipse 基金会执行董事）如此说道。
> > Oracle 对此表示赞同，前研发副总裁 Georges Saab 说：“ Java 是物联网时代最佳的技术。物联网遇到的很多挑战，都是20世纪90年代 Java 在桌面和客户端领域面对过的。你已经有了大量不同的硬件系统。你希望开发者们可以看清系统的细枝末节，深入理解它，并逐步向它迁移。Java 是少数允许你实现以上想法的技术。 ”
> 
> 只是因为利益关系罢了，IOT更多是需要去了解为什么需要IOT，怎么让IOT不鸡肋；目前太多为IOT而IOT了，数据被存储 80%以上的数据没有用途

IoT是趋势，所有的设备数据上报存储，都是有意义的，生态需要数据试错。即便80%的数据没有用途，那也是一种前行和探索。为了IoT而IoT?这不是一个主观意识问题，这是客观趋势，未来的世界就是万物互联的世界。所有的国内外大厂都在布局，从云端存储，到平台建设，不管设备上传什么数据，就算用途为0，也照样存储。
TDengine作为刚开源的物联网数据存储中间件，采取积极的态度去拥抱Java生态，这也应该是一种趋势。我们谈论的不该是这种数据有没有用途，即便是没有用途，那实际生产中，Hadoop生态与Java生态结合的大行其道，已经在资本上走在前面了，这是应当借鉴和学习的。
酒香不怕巷子深的时代真的已经过去，用技术和性能取胜，应顺势而大为，才是弯道超车的关键！

**Comment by hvritual** [comment]
> > > @linghongtao 你的建议让我补充一下的东西，希望TDengine能很好地考虑一下Java生态，真的！
> > > Java 和 物联网
> > > “我确信 Java 的未来在物联网。我很希望 Oracle 及其伙伴们，会将注意力集中到为 Java 提供彻底的端到端的存储解决方案上：从终端设备开始，穿过网关，直至企业后端。构造这样一个故事，并且将其运作成功，这将有助于巩固 Java 未来 20 年里的地位。这不仅仅对整个产业蕴含着巨大的机会，而且我认为 Java 可以在这方面做得很好。”Mike Milinkovich （Eclipse 基金会执行董事）如此说道。
> > > Oracle 对此表示赞同，前研发副总裁 Georges Saab 说：“ Java 是物联网时代最佳的技术。物联网遇到的很多挑战，都是20世纪90年代 Java 在桌面和客户端领域面对过的。你已经有了大量不同的硬件系统。你希望开发者们可以看清系统的细枝末节，深入理解它，并逐步向它迁移。Java 是少数允许你实现以上想法的技术。 ”
> > 
> > 
> > 只是因为利益关系罢了，IOT更多是需要去了解为什么需要IOT，怎么让IOT不鸡肋；目前太多为IOT而IOT了，数据被存储 80%以上的数据没有用途
> 
> IoT是趋势，所有的设备数据上报存储，都是有意义的，生态需要数据试错。即便80%的数据没有用途，那也是一种前行和探索。为了IoT而IoT?这不是一个主观意识问题，这是客观趋势，未来的世界就是万物互联的世界。所有的国内外大厂都在布局，从云端存储，到平台建设，不管设备上传什么数据，就算用途为0，也照样存储。
> TDengine作为刚开源的物联网数据存储中间件，采取积极的态度去拥抱Java生态，这也应该是一种趋势。我们谈论的不该是这种数据有没有用途，即便是没有用途，那实际生产中，Hadoop生态与Java生态结合的大行其道，已经在资本上走在前面了，这是应当借鉴和学习的。
> 酒香不怕巷子深的时代真的已经过去，用技术和性能取胜，应顺势而大为，才是弯道超车的关键！

如果是为了迎合java 我觉得kafka+flink 就已经做了很多东西 关于TDengine 个人更多的是将方向放在周边的监控、简易部署、简易拓展方面，而不是关注语言端的东西，关于语言 我还是希望多考虑go 而不是采用目前的CGO前行（个人想法），java生态在这么长时间积累后真的很好，但是开发者更多的是喜欢简单的东西，例如简单依赖，简单部署

**Comment by coder-chriswang** [comment]
> > > > @linghongtao 你的建议让我补充一下的东西，希望TDengine能很好地考虑一下Java生态，真的！
> > > > Java 和 物联网
> > > > “我确信 Java 的未来在物联网。我很希望 Oracle 及其伙伴们，会将注意力集中到为 Java 提供彻底的端到端的存储解决方案上：从终端设备开始，穿过网关，直至企业后端。构造这样一个故事，并且将其运作成功，这将有助于巩固 Java 未来 20 年里的地位。这不仅仅对整个产业蕴含着巨大的机会，而且我认为 Java 可以在这方面做得很好。”Mike Milinkovich （Eclipse 基金会执行董事）如此说道。
> > > > Oracle 对此表示赞同，前研发副总裁 Georges Saab 说：“ Java 是物联网时代最佳的技术。物联网遇到的很多挑战，都是20世纪90年代 Java 在桌面和客户端领域面对过的。你已经有了大量不同的硬件系统。你希望开发者们可以看清系统的细枝末节，深入理解它，并逐步向它迁移。Java 是少数允许你实现以上想法的技术。 ”
> > > 
> > > 
> > > 只是因为利益关系罢了，IOT更多是需要去了解为什么需要IOT，怎么让IOT不鸡肋；目前太多为IOT而IOT了，数据被存储 80%以上的数据没有用途
> > 
> > 
> > IoT是趋势，所有的设备数据上报存储，都是有意义的，生态需要数据试错。即便80%的数据没有用途，那也是一种前行和探索。为了IoT而IoT?这不是一个主观意识问题，这是客观趋势，未来的世界就是万物互联的世界。所有的国内外大厂都在布局，从云端存储，到平台建设，不管设备上传什么数据，就算用途为0，也照样存储。
> > TDengine作为刚开源的物联网数据存储中间件，采取积极的态度去拥抱Java生态，这也应该是一种趋势。我们谈论的不该是这种数据有没有用途，即便是没有用途，那实际生产中，Hadoop生态与Java生态结合的大行其道，已经在资本上走在前面了，这是应当借鉴和学习的。
> > 酒香不怕巷子深的时代真的已经过去，用技术和性能取胜，应顺势而大为，才是弯道超车的关键！
> 
> 如果是为了迎合java 我觉得kafka+flink 就已经做了很多东西 关于TDengine 个人更多的是将方向放在周边的监控、简易部署、简易拓展方面，而不是关注语言端的东西，关于语言 我还是希望多考虑go 而不是采用目前的CGO前行（个人想法），java生态在这么长时间积累后真的很好，但是开发者更多的是喜欢简单的东西，例如简单依赖，简单部署

那就让我们共同期待，TDengine后续会采取怎样的动作吧

**Comment by sudemo** [comment]
大佬总是觉得我们也是大佬，所以说的简洁，奈何我等是弱鸡[摊手]
