### ISSUE TITLE
The "<>" and "=" operators do not work for NCHAR columns

### ISSUE THREAD

**Issue by mrigger** [taosdata/TDengine#590]
Consider the following statements:

```
CREATE TABLE t0(c0 TIMESTAMP, c1 NCHAR(1));
INSERT INTO t0(c0, c1) VALUES(0, "a");
SELECT * FROM t0 WHERE c1 = "a";
```

The query results in an error `TSDB error: invalid SQL: nchar column not available for filter`.
The [documentation](https://www.taosdata.com/en/documentation/taos-sql/#Data-Query) explicitly states that the operators "<>" and "=" can be used on columns of all data types, so I would expect that they can also be used on `NCHAR` columns.

When replacing the `NCHAR` with `BINARY`, the query works as expected:
```
          c0          |c1|
==========================
 19-10-03 16:51:49.623|a |
Query OK, 1 row(s) in set (0.001756s)
```

**Comment by plum-lihui** [comment]
It's not currently supported, but it will soon be improved in subsequent versions.
