### ISSUE TITLE
 Assertion `strncasecmp(token->z, "false", 5) == 0' failed.

### ISSUE THREAD

**Issue by WLLS253** [taosdata/TDengine#5902]
When I fuzz the Tdengine in linux , i get an assertion failture 
Welcome to the TDengine shell from Linux, Client Version:2.0.19.0
Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.

taos> SELECT bool 't' AS true;
taos: /home/xxx/opt/projects/databases/TDengine/src/common/src/tvariant.c:38: tVariantCreate: Assertion `strncasecmp(token->z, "false", 5) == 0' failed.
fish: “./build/bin/taos -c test/cfg” terminated by signal SIGABRT (Abort)

![Screenshot from 2021-04-24 11-24-41](https://user-images.githubusercontent.com/52878813/115945768-b40fb780-a4ef-11eb-9c2f-51225f5613ed.png)
![Screenshot from 2021-04-24 11-25-28](https://user-images.githubusercontent.com/52878813/115945792-d6a1d080-a4ef-11eb-9f13-46b624326273.png)

**Environment (please complete the following information):**
 - OS: [ubuntu 20.04]
 - TDengine Version [2.0.19]

**Comment by WLLS253** [comment]
The stack trace of the assertion failure
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f50e75f392e in __GI_abort () at abort.c:100
#2  0x00007f50e75f3729 in __assert_fail_base (fmt=0x7f50e7789588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7f50e7b310e8 "strncasecmp(token->z, \"false\", 5) == 0", 
    file=0x7f50e7b310a0 "/home/wzy/opt/projects/databases/TDengine/src/common/src/tvariant.c", line=38, function=<optimized out>) at assert.c:92
#3  0x00007f50e7604f36 in __GI___assert_fail (assertion=0x7f50e7b310e8 "strncasecmp(token->z, \"false\", 5) == 0", 
    file=0x7f50e7b310a0 "/home/wzy/opt/projects/databases/TDengine/src/common/src/tvariant.c", line=38, function=0x7f50e7b317b8 <__PRETTY_FUNCTION__.9590> "tVariantCreate")
    at assert.c:101
#4  0x00007f50e78952ca in tVariantCreate (pVar=0x7f50cc10c5c0, token=0x7f50cc0024a0) at /home/wzy/opt/projects/databases/TDengine/src/common/src/tvariant.c:38
#5  0x00007f50e7a6d65a in tSqlExprCreateIdValue (pToken=0x7f50cc0024a0, optrType=2) at /home/wzy/opt/projects/databases/TDengine/src/query/src/qSqlParser.c:138
#6  0x00007f50e7a7bf4d in yy_reduce (yypParser=0x7f50cc001f80, yyruleno=225, yyLookahead=9, yyLookaheadToken=...)
    at /home/wzy/opt/projects/databases/TDengine/src/query/src/sql.c:3167
#7  0x00007f50e7a7d9ec in Parse (yyp=0x7f50cc001f80, yymajor=9, yyminor=..., pInfo=0x7f50d3ffe9a0) at /home/wzy/opt/projects/databases/TDengine/src/query/src/sql.c:3565
#8  0x00007f50e7a6d357 in qSqlParse (pStr=0x7f50cc102a10 "select bool 't' as true;") at /home/wzy/opt/projects/databases/TDengine/src/query/src/qSqlParser.c:71
#9  0x00007f50e783e4b9 in tsParseSql (pSql=0x7f50cc101670, initial=true) at /home/wzy/opt/projects/databases/TDengine/src/client/src/tscParseInsert.c:1331
#10 0x00007f50e782e7b9 in doAsyncQuery (pObj=0x560ed83665d0, pSql=0x7f50cc101670, fp=0x7f50e7867870 <waitForQueryRsp>, param=0x560ed83665d0, 
    sqlstr=0x7f50e02e1010 "SELECT bool 't' AS true;", sqlLen=24) at /home/wzy/opt/projects/databases/TDengine/src/client/src/tscAsync.c:63
#11 0x00007f50e7867aba in taos_query_c (taos=0x560ed83665d0, sqlstr=0x7f50e02e1010 "SELECT bool 't' AS true;", sqlLen=24, res=0x560ed7141600 <result>)
    at /home/wzy/opt/projects/databases/TDengine/src/client/src/tscSql.c:344
#12 0x00007f50e7867b69 in taos_query_h (taos=0x560ed83665d0, sqlstr=0x7f50e02e1010 "SELECT bool 't' AS true;", res=0x560ed7141600 <result>)
    at /home/wzy/opt/projects/databases/TDengine/src/client/src/tscSql.c:359
#13 0x0000560ed713488c in shellRunCommandOnServer (con=0x560ed83665d0, command=0x7f50e02e1010 "SELECT bool 't' AS true;")
    at /home/wzy/opt/projects/databases/TDengine/src/kit/shell/src/shellEngine.c:314
#14 0x0000560ed71342c9 in shellRunSingleCommand (con=0x560ed83665d0, command=0x7f50e02e1010 "SELECT bool 't' AS true;")
    at /home/wzy/opt/projects/databases/TDengine/src/kit/shell/src/shellEngine.c:189
#15 0x0000560ed7134651 in shellRunCommand (con=0x560ed83665d0, command=0x7f50e02e1028 "") at /home/wzy/opt/projects/databases/TDengine/src/kit/shell/src/shellEngine.c:259
#16 0x0000560ed713845e in shellLoopQuery (arg=0x560ed83665d0) at /home/wzy/opt/projects/databases/TDengine/src/kit/shell/src/shellLinux.c:358
#17 0x00007f50e77c9609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#18 0x00007f50e76f0293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by fenghuazzm** [comment]
This issue was closed because it has been inactive for too many days.
