### ISSUE TITLE
Segmentation fault in taos shell command

### ISSUE THREAD

**Issue by WLLS253** [taosdata/TDengine#5903]
The stack  trace recoed with core dump
Core was generated by `./build/bin/taos -c ../release/test/cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f06835ee0ef in destroyAllSelectClause (pClause=0x1) at /home/wzy/opt/projects/databases/TDengine/src/query/src/qSqlParser.c:811
811       if (pClause == NULL || pClause->numOfClause == 0) {
[Current thread is 1 (Thread 0x7f066f7fe700 (LWP 325288))]
(gdb) bt
#0  0x00007f06835ee0ef in destroyAllSelectClause (pClause=0x1) at /home/wzy/opt/projects/databases/TDengine/src/query/src/qSqlParser.c:811
#1  0x00007f06835ed819 in destroyFromInfo (pFromInfo=0x7f0668107a30) at /home/wzy/opt/projects/databases/TDengine/src/query/src/qSqlParser.c:564
#2  0x00007f06835ee098 in destroyQuerySqlNode (pQuerySql=0x7f066832e040) at /home/wzy/opt/projects/databases/TDengine/src/query/src/qSqlParser.c:802
#3  0x00007f06835ee126 in destroyAllSelectClause (pClause=0x7f066f7fdb18) at /home/wzy/opt/projects/databases/TDengine/src/query/src/qSqlParser.c:817
#4  0x00007f06835ee539 in SqlInfoDestroy (pInfo=0x7f066f7fdb10) at /home/wzy/opt/projects/databases/TDengine/src/query/src/qSqlParser.c:906
#5  0x00007f06833bd559 in tsParseSql (pSql=0x7f066832bf70, initial=true) at /home/wzy/opt/projects/databases/TDengine/src/client/src/tscParseInsert.c:1339
#6  0x00007f06833ad7b9 in doAsyncQuery (pObj=0x55a997dce5f0, pSql=0x7f066832bf70, fp=0x7f06833e6870 <waitForQueryRsp>, param=0x55a997dce5f0, 
    sqlstr=0x7f067c661010 "SELECT x, y,         atan2d(y, x),         atan2d(y, x) IN (-90,0,90,180) AS atan2d_exact  FROM (SELECT 10*cosd(a),ring) returns xfloat8 immutable strict    language internal as 'int8in';", sqlLen=187) at /home/wzy/opt/projects/databases/TDengine/src/client/src/tscAsync.c:63
#7  0x00007f06833e6aba in taos_query_c (taos=0x55a997dce5f0, 
    sqlstr=0x7f067c661010 "SELECT x, y,         atan2d(y, x),         atan2d(y, x) IN (-90,0,90,180) AS atan2d_exact  FROM (SELECT 10*cosd(a),ring) returns xfloat8 immutable strict    language internal as 'int8in';", sqlLen=187, res=0x55a996cfe600 <result>) at /home/wzy/opt/projects/databases/TDengine/src/client/src/tscSql.c:344
#8  0x00007f06833e6b69 in taos_query_h (taos=0x55a997dce5f0, 
    sqlstr=0x7f067c661010 "SELECT x, y,         atan2d(y, x),         atan2d(y, x) IN (-90,0,90,180) AS atan2d_exact  FROM (SELECT 10*cosd(a),ring) returns xfloat8 immutable strict    language internal as 'int8in';", res=0x55a996cfe600 <result>) at /home/wzy/opt/projects/databases/TDengine/src/client/src/tscSql.c:359
#9  0x000055a996cf188c in shellRunCommandOnServer (con=0x55a997dce5f0, 
    command=0x7f067c661010 "SELECT x, y,         atan2d(y, x),         atan2d(y, x) IN (-90,0,90,180) AS atan2d_exact  FROM (SELECT 10*cosd(a),ring) returns xfloat8 immutable strict    language internal as 'int8in';") at /home/wzy/opt/projects/databases/TDengine/src/kit/shell/src/shellEngine.c:314
#10 0x000055a996cf12c9 in shellRunSingleCommand (con=0x55a997dce5f0, 
    command=0x7f067c661010 "SELECT x, y,         atan2d(y, x),         atan2d(y, x) IN (-90,0,90,180) AS atan2d_exact  FROM (SELECT 10*cosd(a),ring) returns xfloat8 immutable strict    language internal as 'int8in';") at /home/wzy/opt/projects/databases/TDengine/src/kit/shell/src/shellEngine.c:189
#11 0x000055a996cf1651 in shellRunCommand (con=0x55a997dce5f0, command=0x7f067c6610cb "") at /home/wzy/opt/projects/databases/TDengine/src/kit/shell/src/shellEngine.c:259
#12 0x000055a996cf545e in shellLoopQuery (arg=0x55a997dce5f0) at /home/wzy/opt/projects/databases/TDengine/src/kit/shell/src/shellLinux.c:358
#13 0x00007f0683348609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#14 0x00007f068326f293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Environment (please complete the following information):**
 - OS: [ubuntu 20.04
 - Memory, CPU, current Disk Space
 - TDengine Version [2.0.19]

**Comment by yu285** [comment]
请添加微信15652223354，做具体排查沟通
