### ISSUE TITLE
dnode offline . how to fix?

### ISSUE THREAD

**Issue by auhjin** [taosdata/TDengine#5904]
taos> show dnodes;
   id   |           end_point            | vnodes | cores  |   status   | role  |       create_time       |      offline reason      |
======================================================================================================================================
      1 | Master:6030                    |      1 |      4 | ready      | any   | 2021-04-24 01:13:28.406 |                          |
      4 | Slave2:6030                    |      0 |      0 | offline    | any   | 2021-04-24 16:53:27.885 | dnodeId not match        |
      5 | Slave3:6030                    |      0 |      0 | offline    | any   | 2021-04-24 16:54:09.636 | status not received      |

**Comment by yu285** [comment]
需要提供更多信息方便排查，请添加微信15652223354做具体分析
