### ISSUE TITLE
can not find cfg while starting with relative path 

### ISSUE THREAD

**Issue by WLLS253** [taosdata/TDengine#5908]
**Bug Description**
![Screenshot from 2021-04-25 13-04-03](https://user-images.githubusercontent.com/52878813/115981525-096ac800-a5c7-11eb-8f7f-ef5634ff5971.png)

**To Reproduce**
1. start database  with relative path 
2. change the path of the db
3. start database again with relative path

**Expected Behavior**
database is runing

**Environment (please complete the following information):**
 - OS: [ubuntu 20.04]
 - TDengine Version [2.0.19]

**Comment by stephenkgu** [comment]
cd ../release
and try again.
or sed -i "s/release/release_copy/g" ./test/cfg/taos.cfg and try again.

**Comment by WLLS253** [comment]
这个bug的原因似乎是因为test/cfg中记录的绝对路径，而非相对路径，这导致只要移动或者修改数据库的名称都会导致数据库无法启动。个人人为，如果为了数据库更好的扩展性和平台通用性，是否可以考虑对cfg的配置文件记录模式进行一下完善
