### ISSUE TITLE
Unexpected result when using arithmetic expressions in WHERE clause

### ISSUE THREAD

**Issue by mrigger** [taosdata/TDengine#591]
Consider the following statements:

```
CREATE TABLE t0(c0 TIMESTAMP, c1 INT);
INSERT INTO t0 VALUES(0, 1);
SELECT * FROM t0 WHERE c1=(c1*1);
```
I would expect the WHERE condition to evaluate to true, since multipliying c1 by 1 should yield c1 again. However, the row in this table is not fetched. Also comparisons with other arithmetic expressions seem to malfunction. For example, the query `SELECT * FROM t0 WHERE c1=(c1+0);` also does not fetch the row.

**Comment by hjxilinx** [comment]
TDengine does not support the arithmetic operation in the Where clause. Only the arithmetic expression in the Selection clause is allowed.

**Comment by mrigger** [comment]
Thanks for the response! Wouldn't it be better then to fail with an error rather than silently computing an incorrect result?

**Comment by jtao1735** [comment]
> Thanks for the response! Wouldn't it be better then to fail with an error rather than silently computing an incorrect result?

Yes, good suggestion
