### ISSUE TITLE
Stack smashing error

### ISSUE THREAD

**Issue by sexbee** [taosdata/TDengine#592]
Create stable:

create table st_m (ts timestamp,Message binary(30),Id int,tname binary(20),Sta binary(40),Rha binary(30),Sp tinyint,RsR tinyint,CCI float,SIi float,HsR smallint,PVC tinyint,SVV float,CCVO float,SV float,Pul tinyint,dP float,Tbl float,CVs float,APs smallint,APd smallint,APm smallint,NPs smallint,NPd smallint,NPm smallint,PP float,PPs float,PPd float,PPm float,BS float,PAP float,CPm float,CPd float,GF float,SV float,PV float,CDO float,CDI float,ITV float,ITI float,EVW float,EVWI float,GEV float,GVI float,CKI float,PPI float,LCTW float,LVSTW float,LCTTWI float,LVTTSWI float,RTTCW float,RTTVSW float,RCTTWI float,RVTTSWI float,SV float) tags(location binary(20),bRid binary(10));

TAOS config default;

Err:Stack smashing error

**Comment by plum-lihui** [comment]
===There are three identical column names： PV。 and  after changing to a column name with different names, it can be created normally.  There was no stack smashing error. As follows：

create table st_m (ts timestamp,Message binary(30),Id int,tname binary(20),Sta binary(40),Rha binary(30),Sp tinyint,RsR tinyint,CCI float
,SIi float,HsR smallint,PVC tinyint,SVV float,CCVO float,SV float,Pul tinyint,dP float,Tbl float,CVs float,APs smallint,APd smallint,APm smalli
nt,NPs smallint,NPd smallint,NPm smallint,PP float,PPs float,PPd float,PPm float,BS float,PAP float,CPm float,CPd float,GF float,SV float,PV fl
oat,CDO float,CDI float,ITV float,ITI float,EVW float,EVWI float,GEV float,GVI float,CKI float,PPI float,LCTW float,LVSTW float,LCTTWI float,LV
TTSWI float,RTTCW float,RTTVSW float,RCTTWI float,RVTTSWI float,SV float) tags(location binary(20),bRid binary(10));

TSDB error: invalid SQL: duplicated column names

create table st_m (ts timestamp,Message binary(30),Id int,tname binary(20),Sta binary(40),Rha binary(30),Sp tinyint,RsR tinyint,CCI float
,SIi float,HsR smallint,PVC tinyint,SVV float,CCVO float,SV1 float,Pul tinyint,dP float,Tbl float,CVs float,APs smallint,APd smallint,APm small
int,NPs smallint,NPd smallint,NPm smallint,PP float,PPs float,PPd float,PPm float,BS float,PAP float,CPm float,CPd float,GF float,SV float,PV f
loat,CDO float,CDI float,ITV float,ITI float,EVW float,EVWI float,GEV float,GVI float,CKI float,PPI float,LCTW float,LVSTW float,LCTTWI float,L
VTTSWI float,RTTCW float,RTTVSW float,RCTTWI float,RVTTSWI float,SV3 float) tags(location binary(20),bRid binary(10));
Query OK, 1 row(s) affected (0.013926s)

show stables;
                              name                              |     created time     |columns| tags  |  tables   |
====================================================================================================================
st_m                                                            | 19-10-04 09:43:41.178|     55|      2|          0|
Query OK, 1 row(s) in set (0.008926s)
