### ISSUE TITLE
Can't connect to TDengine under docker cluster environment?

### ISSUE THREAD

**Issue by liudican** [taosdata/TDengine#5920]
一个服务器使用docker搭建2个tdengine数据库，对外改变端口映射，通过连接器连接不上tdengine数据库？

**Comment by yu285** [comment]
您好，首先请确保集群工作正常。其次，请提供报错信息如（报错截图，服务端+客户端的taos.cfg,hosts文件 ）。

也请排查客户端与宿主机是否有跨网段现象。

也可以添加微信15652223354做具体排查
