### ISSUE TITLE
the shell client  is forced hanging 

### ISSUE THREAD

**Issue by WLLS253** [taosdata/TDengine#5925]
**Bug Description**
the shell client  is forced hanging  when I input a sql like INSERT INTO NAME_TBL(xxxxxx');

**To Reproduce**
the sheetshort will help to reproduce：
![Screenshot from 2021-04-26 13-22-35](https://user-images.githubusercontent.com/52878813/116033060-5320e480-a693-11eb-8443-8f83156922a5.png)

**Expected Behavior**
it should return a warning like "DB error：xxxxxxx"

**Environment (please complete the following information):**
 - OS: [ubuntu 20.04]
 - TDengine Version [2.0.19]

**Comment by yu285** [comment]
请添加微信 15652223354做具体排查，问题解决后会把解决方案更新于此。
