### ISSUE TITLE
maybe an unicode issue

### ISSUE THREAD

**Issue by effun** [taosdata/TDengine#593]
Syntax error occured while executing the following statement:
`insert into test values(1570259352306, 9, 4, 9, 'Row #10/1000', '行号 #10/1000', 650.3419180635093, True, 45.20559);`

TSDB error: invalid SQL: near "号 #10/1000', 650.3419180635093, true, 45.20559);" syntax error

The `test` table was created like below.
`create table test(
  ts timestamp,
  int32 int,
  int16 smallint,
  byte smallint,
  str binary(10),
  nstr nchar(10),
  dbl double,
  bo bool,
  flt float
);`

The statement can execute successfully by removing character from the string constant, like `'号 #10/1000'` or `'行号 #1/1000'`.

**Environment:**
 - OS: Windows 10, CentOS 7
 - TDengine Version 1.6.2.2

I'v tested the statement in both Windows client and Linux client, neither works.

**Comment by plum-lihui** [comment]
The “str binary(10), nstr nchar(10)“ columns defined are all 10 character lengths， but when insert， the values （'Row #10/1000', '行号 #10/1000'）exceed the defined length。so there is invalid SQL。

**Comment by plum-lihui** [comment]
![image](https://user-images.githubusercontent.com/52318143/66387565-c94cf000-e9f6-11e9-8caa-b1f30b9dfd41.png)

**Comment by effun** [comment]
OMG, what a silly question, my bad.

But, anyway, it is NOT a **syntax error** at all. Is it possible to make the error message more specifically.
