### ISSUE TITLE
How can I Insert binary data into tdengine

### ISSUE THREAD

**Issue by BestHYY** [taosdata/TDengine#5931]
TDENGINE的binary类型是否支持插入非可见字符？比如我想插入0x00, 0x01, 0x02, 0x03的4字节二进制数据到数据库中的名为bin的binary类型的列，sql语句应该怎么写？

**Comment by cpvmrd** [comment]
虽然 Binary 类型在底层存储上支持字节型的二进制字符，但不同编程语言对二进制数据的处理方式并不保证一致，因此建议在 Binary 类型中只存储 ASCII 可见字符，而避免存储不可见字符。

**Comment by BestHYY** [comment]
找到文档了，现在只支持写入字符串，但是建议提供任意binary写入的功能，很多原始数据需要直接保存，但是不一定全是字符串

**Comment by cpvmrd** [comment]
> 找到文档了，现在只支持写入字符串，但是建议提供任意binary写入的功能，很多原始数据需要直接保存，但是不一定全是字符串

收到，感谢建议，我反馈给研发团队。

**Comment by wangxiufeng1104** [comment]
二进制数据存储的问题解决了吗？
