### ISSUE TITLE
how to import csv file to database & If sampled time is not monotonic increasing, how can i insert the data?

### ISSUE THREAD

**Issue by SMD12138** [taosdata/TDengine#594]
**Performance Issue** 
Any questions related to TDengine's performance can be discussed here.

**Problem Description** 
A clear and concise description of what the problem is.

**To Reproduce**
1. Database parameters used: 
 ```show databases```
2. Verbs used: Insert/Import/Select?
3. Describe the total amount of data
4. Observed performance vs. expected performance

**Screenshots**

**Environment (please complete the following information):**

* OS: [e.g. CentOS 7.0]
* Memory, CPU, current Disk Space
* TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by plum-lihui** [comment]
一、导入csv文件的数据命令：	IMPORT INTO <tb_name> FILE <filename>;
二、每2分钟采集一次，时间戳不就是递增的吗？

**Comment by SMD12138** [comment]
我是建了一个超级表press
然后又建了子表s1，语句如下，部分csv如图，为什么一直数据导不进去TDengine里







---原始邮件---
发件人: "plum-lihui"<notifications@github.com&gt;
发送时间: 2019年10月8日(星期二) 下午5:46
收件人: "taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"SMD12138"<2099291871@qq.com&gt;;
主题: Re: [taosdata/TDengine] 你好，想问一下怎么把csv文件导入数据库，还有压力传感器每2分钟采集一次数据，但是用采集时间作为时间戳的话，就不是递增了，这种怎末解决 (#594)



一、导入csv文件的数据命令：IMPORT INTO <tb_name&gt; FILE ;
 二、每2分钟采集一次，时间戳不就是递增的吗？

**Comment by SMD12138** [comment]
你好，我弄了创表语句，按照您说的导入语句导入，怎么导不进去

**Comment by plum-lihui** [comment]
邮件回复你了。
