### ISSUE TITLE
failed to install client

### ISSUE THREAD

**Issue by whnforyaheen** [taosdata/TDengine#595]
请问下https://juejin.im/post/5d8dbcadf265da5bb15284e9#heading-1链接内容里，我执行到cmake .. -G "NMake Makefiles"的时候不能正常输出，生成的目录结构也不是文档给出的结构，是什么原因呢？

输出如下：
C:\Users\Administrator>C:\Program Files\tdengine\TDengine-master
'C:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\Administrator>cd C:\Program Files\tdengine\TDengine-master

C:\Program Files\tdengine\TDengine-master>makedir nmake
'makedir' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Program Files\tdengine\TDengine-master>mkdir nmake

C:\Program Files\tdengine\TDengine-master>cd nmake

C:\Program Files\tdengine\TDengine-master\nmake>cmake .. -G "NMake Makefiles"
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (PROJECT):
  The CMAKE_C_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

CMake Error at CMakeLists.txt:2 (PROJECT):
  The CMAKE_CXX_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "C:/Program Files/tdengine/TDengine-master/nmake/CMakeFiles/CMakeOutput
.log".
See also "C:/Program Files/tdengine/TDengine-master/nmake/CMakeFiles/CMakeError.
log".

**Comment by guanshengliang** [comment]
vs2013下的编译经过验证，其他编译器下的编译方法未随时验证。
从您的错误来看，应该是编译环境的问题

**Comment by guanshengliang** [comment]
No feedback for more than 1 month, so we closed this issue
