### ISSUE TITLE
Could 'account' be used as a field name? 

### ISSUE THREAD

**Issue by Mojicode** [taosdata/TDengine#5957]
**Bug Description**
在Ubuntu系统中编译安装的taos数据库，发现一个奇怪现象：执行一条SQL时， 里面一个字段名为【account】，但是执行失败，然后简单修改下account单词就执行成功了，难道account是关键字不能作为字段名用？截图如下：

![image](https://user-images.githubusercontent.com/30165217/116364364-b5feb100-a836-11eb-9811-cd51ff1a037e.png)

**Expected Behavior**
期望能使用account作为字段名

**Environment (please complete the following information):**
 - OS: [Ubuntu 16.04.7 LTS]
 - TDengine Version [2.0.19.0]
 - $ taosd -V
community version: 2.0.19.0 compatible_version: 2.0.0.0
gitinfo: ec74d6c0a89a891f5b7979d884713d816aedf37b
gitinfoI: ec74d6c0a89a891f5b7979d884713d816aedf37b
buildinfo: Built at 2021-04-06 17:43:10

**Comment by cpvmrd** [comment]
account是系统保留字。 https://www.taosdata.com/cn/documentation/administrator#keywords

**Comment by Mojicode** [comment]
> account是系统保留字。 https://www.taosdata.com/cn/documentation/administrator#keywords

不好意思，我搜索的范围不够，之前没有搜到。
