### ISSUE TITLE
TDengine 启动时执行命令systemctl start taosd 不起作用，报错信息如下，由于找不到localEp 文件，不知道如何更改配置

### ISSUE THREAD

**Issue by zhuyongh** [taosdata/TDengine#5958]
04/28 18:05:23.489622 00032304 ==================================================
04/28 18:05:23.489651 00032304 ===================  new note  ===================
04/28 18:05:23.489654 00032304 ==================================================
04/28 18:05:23.490007 00032304 TMR ttimer monotonic clock source:X86 TSC @ 2100 ticks/us
04/28 18:05:23.490480 00032304 DND start to initialize TDengine
04/28 18:05:23.490529 00032304 DND step:dnode-tfile is initialized
04/28 18:05:23.490542 00032304 DND step:dnode-rpc is initialized
04/28 18:05:23.490926 00032304 UTL localEp is: localhost:6030
04/28 18:05:23.491334 00032304 UTL WARN timezone not configured, set to system default: (CST, +0800)
04/28 18:05:23.491389 00032304 UTL WARN locale not configured, set to system default:en_US.UTF-8
04/28 18:05:23.491401 00032304 UTL WARN charset not configured, set to system default:UTF-8
04/28 18:05:23.491439 00032304 UTL    check global cfg completed
04/28 18:05:23.491445 00032304 UTL ==================================
04/28 18:05:23.491450 00032304 UTL    taos config & system info:
04/28 18:05:23.491454 00032304 UTL ==================================
04/28 18:05:23.491458 00032304 UTL  firstEp:                localhost:6030 
04/28 18:05:23.491463 00032304 UTL  secondEp:               localhost:6030 
04/28 18:05:23.491467 00032304 UTL  fqdn:                   localhost 
04/28 18:05:23.491472 00032304 UTL  serverPort:             6030 
04/28 18:05:23.491476 00032304 UTL  configDir:              /etc/taos 
04/28 18:05:23.491481 00032304 UTL  logDir:                 /var/log/taos 
04/28 18:05:23.491485 00032304 UTL  scriptDir:              /etc/taos 
04/28 18:05:23.491489 00032304 UTL  arbitrator:              
04/28 18:05:23.491494 00032304 UTL  numOfThreadsPerCore:    1.000000 
04/28 18:05:23.491508 00032304 UTL  numOfCommitThreads:     4 
04/28 18:05:23.491513 00032304 UTL  ratioOfQueryCores:      1.000000 
04/28 18:05:23.491517 00032304 UTL  numOfMnodes:            3 
04/28 18:05:23.491522 00032304 UTL  vnodeBak:               1 
04/28 18:05:23.491526 00032304 UTL  telemetryReporting:     1 
04/28 18:05:23.491531 00032304 UTL  balance:                1 
04/28 18:05:23.491535 00032304 UTL  balanceInterval:        300 
04/28 18:05:23.491539 00032304 UTL  role:                   0 
04/28 18:05:23.491544 00032304 UTL  maxTmrCtrl:             512 
04/28 18:05:23.491548 00032304 UTL  monitorInterval:        30(s)
04/28 18:05:23.491552 00032304 UTL  offlineThreshold:       8640000(s)
04/28 18:05:23.491557 00032304 UTL  rpcTimer:               1000(ms)
04/28 18:05:23.491561 00032304 UTL  rpcMaxTime:             600(s)
04/28 18:05:23.491565 00032304 UTL  statusInterval:         1(s)
04/28 18:05:23.491569 00032304 UTL  shellActivityTimer:     3(s)
04/28 18:05:23.491573 00032304 UTL  minSlidingTime:         10(ms)
04/28 18:05:23.491577 00032304 UTL  minIntervalTime:        10(ms)
04/28 18:05:23.491581 00032304 UTL  maxStreamCompDelay:     20000(ms)
04/28 18:05:23.491586 00032304 UTL  maxFirstStreamCompDelay:10000(ms)
04/28 18:05:23.491590 00032304 UTL  retryStreamCompDelay:   10(ms)
04/28 18:05:23.491594 00032304 UTL  streamCompDelayRatio:   0.100000 
04/28 18:05:23.491599 00032304 UTL  maxVgroupsPerDb:        0 
04/28 18:05:23.491604 00032304 UTL  maxTablesPerVnode:      1000000 
04/28 18:05:23.491608 00032304 UTL  minTablesPerVnode:      1000 
04/28 18:05:23.491612 00032304 UTL  tableIncStepPerVnode:   1000 
04/28 18:05:23.491616 00032304 UTL  cache:                  16(Mb)
04/28 18:05:23.491620 00032304 UTL  blocks:                 6 
04/28 18:05:23.491625 00032304 UTL  days:                   10 
04/28 18:05:23.491629 00032304 UTL  keep:                   3650 
04/28 18:05:23.491633 00032304 UTL  minRows:                100 
04/28 18:05:23.491637 00032304 UTL  maxRows:                4096 
04/28 18:05:23.491641 00032304 UTL  comp:                   2 
04/28 18:05:23.491645 00032304 UTL  walLevel:               1 
04/28 18:05:23.491649 00032304 UTL  fsync:                  3000 
04/28 18:05:23.491659 00032304 UTL  replica:                1 
04/28 18:05:23.491664 00032304 UTL  partitions:             4 
04/28 18:05:23.491668 00032304 UTL  quorum:                 1 
04/28 18:05:23.491672 00032304 UTL  update:                 0 
04/28 18:05:23.491676 00032304 UTL  compressMsgSize:        -1 
04/28 18:05:23.491680 00032304 UTL  maxSQLLength:           1048576(byte)
04/28 18:05:23.491686 00032304 UTL  maxNumOfOrderedRes:     100000 
04/28 18:05:23.491691 00032304 UTL  queryBufferSize:        -1(byte)
04/28 18:05:23.491695 00032304 UTL  retrieveBlockingModel:  0 
04/28 18:05:23.491699 00032304 UTL  keepColumnName:         0 
04/28 18:05:23.491703 00032304 UTL  timezone:                (CST, +0800) 
04/28 18:05:23.491707 00032304 UTL  locale:                 en_US.UTF-8 
04/28 18:05:23.491712 00032304 UTL  charset:                UTF-8 
04/28 18:05:23.491716 00032304 UTL  maxShellConns:          50000 
04/28 18:05:23.491720 00032304 UTL  maxConnections:         5000 
04/28 18:05:23.491725 00032304 UTL  minimalLogDirGB:        1.000000(GB)
04/28 18:05:23.491729 00032304 UTL  minimalTmpDirGB:        1.000000(GB)
04/28 18:05:23.491734 00032304 UTL  minimalDataDirGB:       2.000000(GB)
04/28 18:05:23.491738 00032304 UTL  mnodeEqualVnodeNum:     4 
04/28 18:05:23.491742 00032304 UTL  flowctrl:               1 
04/28 18:05:23.491746 00032304 UTL  slaveQuery:             1 
04/28 18:05:23.491750 00032304 UTL  adjustMaster:           1 
04/28 18:05:23.491755 00032304 UTL  http:                   1 
04/28 18:05:23.491758 00032304 UTL  mqtt:                   0 
04/28 18:05:23.491762 00032304 UTL  monitor:                1 
04/28 18:05:23.491766 00032304 UTL  stream:                 1 
04/28 18:05:23.491770 00032304 UTL  httpEnableRecordSql:    0 
04/28 18:05:23.491775 00032304 UTL  telegrafUseFieldNum:    0 
04/28 18:05:23.491778 00032304 UTL  httpMaxThreads:         4 
04/28 18:05:23.491782 00032304 UTL  restfulRowLimit:        10240 
04/28 18:05:23.491786 00032304 UTL  numOfLogLines:          10000000 
04/28 18:05:23.491790 00032304 UTL  logKeepDays:            0 
04/28 18:05:23.491795 00032304 UTL  asyncLog:               1 
04/28 18:05:23.491799 00032304 UTL  debugFlag:              0 
04/28 18:05:23.491803 00032304 UTL  mDebugFlag:             131 
04/28 18:05:23.491807 00032304 UTL  dDebugFlag:             135 
04/28 18:05:23.491811 00032304 UTL  sDebugFlag:             135 
04/28 18:05:23.491815 00032304 UTL  wDebugFlag:             135 
04/28 18:05:23.491819 00032304 UTL  sdbDebugFlag:           131 
04/28 18:05:23.491823 00032304 UTL  rpcDebugFlag:           131 
04/28 18:05:23.491827 00032304 UTL  tmrDebugFlag:           131 
04/28 18:05:23.491831 00032304 UTL  cDebugFlag:             131 
04/28 18:05:23.491856 00032304 UTL  jniDebugFlag:           131 
04/28 18:05:23.491861 00032304 UTL  odbcDebugFlag:          131 
04/28 18:05:23.491866 00032304 UTL  uDebugFlag:             131 
04/28 18:05:23.491870 00032304 UTL  httpDebugFlag:          131 
04/28 18:05:23.491874 00032304 UTL  mqttDebugFlag:          131 
04/28 18:05:23.491877 00032304 UTL  monDebugFlag:           131 
04/28 18:05:23.491881 00032304 UTL  qDebugFlag:             131 
04/28 18:05:23.491885 00032304 UTL  vDebugFlag:             135 
04/28 18:05:23.491889 00032304 UTL  tsdbDebugFlag:          131 
04/28 18:05:23.491893 00032304 UTL  cqDebugFlag:            131 
04/28 18:05:23.491911 00032304 UTL  enableRecordSql:        0 
04/28 18:05:23.491915 00032304 UTL  enableCoreFile:         0 
04/28 18:05:23.491919 00032304 UTL  gitinfo:                ca29298d3fb990db8d0c08c215f9048638a1210d 
04/28 18:05:23.491924 00032304 UTL  gitinfoOfInternal:      NULL 
04/28 18:05:23.491928 00032304 UTL  buildinfo:              Built at 2021-04-18 17:34 
04/28 18:05:23.491932 00032304 UTL  version:                2.0.20.0 
04/28 18:05:23.491936 00032304 UTL  maxBinaryDisplayWidth:  30 
04/28 18:05:23.491940 00032304 UTL  tempDir:                /tmp/ 
04/28 18:05:23.491945 00032304 UTL  os pageSize:            4096(KB)
04/28 18:05:23.491950 00032304 UTL  os openMax:             1024
04/28 18:05:23.491957 00032304 UTL  os streamMax:           16
04/28 18:05:23.491961 00032304 UTL  os numOfCores:          8
04/28 18:05:23.491965 00032304 UTL  os totalDisk:           0.000000(GB)
04/28 18:05:23.491969 00032304 UTL  os usedDisk:            0.000000(GB)
04/28 18:05:23.491973 00032304 UTL  os availDisk:           0.000000(GB)
04/28 18:05:23.491977 00032304 UTL  os totalMemory:         7822(MB)
04/28 18:05:23.491985 00032304 UTL  os sysname:             Linux
04/28 18:05:23.491989 00032304 UTL  os nodename:            localhost.localdomain
04/28 18:05:23.491993 00032304 UTL  os release:             3.10.0-514.el7.x86_64
04/28 18:05:23.491997 00032304 UTL  os version:             #1 SMP Tue Nov 22 16:42:41 UTC 2016
04/28 18:05:23.492001 00032304 UTL  os machine:             x86_64
04/28 18:05:23.492006 00032304 UTL  dataDir: /var/lib/taos
04/28 18:05:23.492010 00032304 UTL ==================================
04/28 18:05:23.492014 00032304 DND step:dnode-globalcfg is initialized
04/28 18:05:23.492053 00032304 TFS disk /var/lib/taos is mounted to tier level 0 id 0
04/28 18:05:23.492111 00032304 DND dnode storage is initialized at /var/lib/taos/dnode
04/28 18:05:23.492118 00032304 DND step:dnode-storage is initialized
04/28 18:05:23.492163 00032304 DND read file /var/lib/taos/dnode/dnodeCfg.json successed
04/28 18:05:23.492184 00032304 DND dnodeId is set to 1, clusterId is set to 1cc12794-327f-4059-ac40-a944d4dfb0cd
04/28 18:05:23.500829 00032304 DND successed to write /var/lib/taos/dnode/dnodeCfg.json
04/28 18:05:23.500851 00032304 DND dnode cfg is initialized
04/28 18:05:23.500856 00032304 DND step:dnode-cfg is initialized
04/28 18:05:23.500921 00032304 DND read file /var/lib/taos/dnode/dnodeEps.json successed
04/28 18:05:23.500968 00032304 DND ERROR dnode:1, localEp is different from 1ocalhost:6030 in dnodeEps.json and need reconfigured
04/28 18:05:23.501014 00032304 DND Failed to start TDengine, please check the log at:/var/log/taos

**Comment by zjfsdnu** [comment]
localEp is different from 1ocalhost:6030 in dnodeEps.json and need reconfigured

提示应该很清楚了

**Comment by zhuyongh** [comment]
哦！不好意思，眼拙了，愣是半天没看出来，谢谢。
