### ISSUE TITLE
failed to import csv file

### ISSUE THREAD

**Issue by SMD12138** [taosdata/TDengine#596]
`[我先建了一个超级表，然后又建了子表，按照导入语句进行导入，结果显示没有数据插入

**Comment by plum-lihui** [comment]
1、csv文件格式不对，应该与表的列类型对应的数据，且是文本文件，不能是二进制文件。
2、文件路径要加引号，且如果与客户端执行程序不在同一个路径下，需要使用绝对路径。

**Comment by SMD12138** [comment]
您好！非常感谢您的回复！我更改了文件格式，但是路径一直是不正确

我是将文件保存在这个文件路径下，发现出现以上错误。
然后，把文件保存在taos安装目录下，

执行导入





------------------ 原始邮件 ------------------
发件人: "plum-lihui"<notifications@github.com>;
发送时间: 2019年10月9日(星期三) 上午10:16
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
抄送: "努力努力"<2099291871@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [taosdata/TDengine] 导入CSV文件失败 (#596)




1、csv文件格式不对，应该与表的列类型对应的数据，且是文本文件，不能是二进制文件。
 2、文件路径要加引号，且如果与客户端执行程序不在同一个路径下，需要使用绝对路径。

**Comment by plum-lihui** [comment]
能够远程吗？可以的话，帮你看一下。这样很快就能搞定。




------------------ 原始邮件 ------------------
发件人: "SMD12138"<notifications@github.com>;
发送时间: 2019年10月9日(星期三) 上午10:39
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
抄送: "李珲"<2849823933@qq.com>;"Assign"<assign@noreply.github.com>;
主题: Re: [taosdata/TDengine] 导入CSV文件失败 (#596)



您好！非常感谢您的回复！我更改了文件格式，但是路径一直是不正确 
 
 我是将文件保存在这个文件路径下，发现出现以上错误。 
 然后，把文件保存在taos安装目录下， 
 
 执行导入 
 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "plum-lihui"<notifications@github.com>; 
 发送时间: 2019年10月9日(星期三) 上午10:16 
 收件人: "taosdata/TDengine"<TDengine@noreply.github.com>; 
 抄送: "努力努力"<2099291871@qq.com>;"Author"<author@noreply.github.com>; 
 主题: Re: [taosdata/TDengine] 导入CSV文件失败 (#596) 
 
 
 
 
 1、csv文件格式不对，应该与表的列类型对应的数据，且是文本文件，不能是二进制文件。 
  2、文件路径要加引号，且如果与客户端执行程序不在同一个路径下，需要使用绝对路径。

**Comment by SMD12138** [comment]
可以的，我能加你qq吗我的是2099291871



---原始邮件---
发件人: "plum-lihui"<notifications@github.com&gt;
发送时间: 2019年10月9日(星期三) 上午10:44
收件人: "taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"SMD12138"<2099291871@qq.com&gt;;
主题: Re: [taosdata/TDengine] 导入CSV文件失败 (#596)


能够远程吗？可以的话，帮你看一下。这样很快就能搞定。 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "SMD12138"<notifications@github.com&gt;; 
 发送时间: 2019年10月9日(星期三) 上午10:39 
 收件人: "taosdata/TDengine"<TDengine@noreply.github.com&gt;; 
 抄送: "李珲"<2849823933@qq.com&gt;;"Assign"<assign@noreply.github.com&gt;; 
 主题: Re: [taosdata/TDengine] 导入CSV文件失败 (#596) 
 
 
 
 您好！非常感谢您的回复！我更改了文件格式，但是路径一直是不正确  
   
  我是将文件保存在这个文件路径下，发现出现以上错误。  
  然后，把文件保存在taos安装目录下，  
   
  执行导入  
   
   
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: "plum-lihui"<notifications@github.com&gt;;  
  发送时间: 2019年10月9日(星期三) 上午10:16  
  收件人: "taosdata/TDengine"<TDengine@noreply.github.com&gt;;  
  抄送: "努力努力"<2099291871@qq.com&gt;;"Author"<author@noreply.github.com&gt;;  
  主题: Re: [taosdata/TDengine] 导入CSV文件失败 (#596)  
   
   
   
   
  1、csv文件格式不对，应该与表的列类型对应的数据，且是文本文件，不能是二进制文件。  
   2、文件路径要加引号，且如果与客户端执行程序不在同一个路径下，需要使用绝对路径。

**Comment by zhuchunwu** [comment]
能说一下怎么解决的吗，我也遇到同样的问题

**Comment by zhuchunwu** [comment]
解决了，发现问题是csv文件不能有表头，只能都是数据，而且时间需要用引号
