### ISSUE TITLE
python3 获取Binary类型的tag打印为'\x06'

### ISSUE THREAD

**Issue by d8txc** [taosdata/TDengine#5970]
window Client Version:2.0.16.0
使用python3查询select last(ts) as ts, last(status) as status from tm_well where ts>now-10m group by tmid
其中tmid位Binary类型，在客户端和java环境下使用正常，python3查询结果中tag tmid 为乱码或错误或为空。
查询结果如下：
(datetime.datetime(2021, 4, 29, 17, 40, 57), 0, '\x06'), (datetime.datetime(2021, 4, 29, 17, 40, 57), 1, '\x06'),(datetime.datetime(2021, 4, 29, 17, 40, 50), 1, '\n')
正常数据应为：
(datetime.datetime(2021, 4, 29, 17, 40, 57), 0, 'CQ2FCKcK1G'), (datetime.datetime(2021, 4, 29, 17, 40, 57), 1, 'CQ2DsAoXHU'),(datetime.datetime(2021, 4, 29, 17, 40, 50), 1, 'CQ2BY93SQU')

**Comment by zitsen** [comment]
使用taos shell 查询是否可以得到正确结果？

**Comment by d8txc** [comment]
> 使用taos shell查询是否可以得到正确的结果？

是的，taos shell ，dataGraip均查询正常，补充：
普通表中为Binary类型的字段查询结果也为乱码或错误或为空。

**Comment by zitsen** [comment]
@d8txc 方便的话请搜索 zitsen 加我微信交流

**Comment by d8txc** [comment]
> @ d8txc方便的话请搜索zitsen加我微信交流

已添加，请通过

**Comment by d8txc** [comment]
问题已解决，将2.0.20.0客户端的connector文件夹覆盖到2.0.16.0客户端的同目录下，重新pip 安装python -m pip install python3\后查询返回数据正常
