### ISSUE TITLE
how to fast insert 200million records?

### ISSUE THREAD

**Issue by Leehom23** [taosdata/TDengine#599]
两个亿的数据请问有什么比较快的导入方式么？

**Comment by fangpanpan** [comment]
不知道您用哪种接口进行导入？我们建议您用c的接口。一般多线程批量导入会快些。

**Comment by Leehom23** [comment]
> 不知道您用哪种接口进行导入？我们建议您用c的接口。一般多线程批量导入会快些。
因为是历史的数据，我用的官网提供的insert into tablefile allcol2.csv .用shell去调度的。我先看下c吧，看是否快一点。

**Comment by Leehom23** [comment]
> 不知道您用哪种接口进行导入？我们建议您用c的接口。一般多线程批量导入会快些。

我试了demo中提供的代码。报这个错，请问怎么处理呢？
./demo: error while loading shared libraries: libtaos.so.1: cannot open shared object file: No such file or directory

**Comment by Leehom23** [comment]
> 不知道您用哪种接口进行导入？我们建议您用c的接口。一般多线程批量导入会快些。

我这边尝试用c的测试demo导入一千万条，大约1秒钟1万多条，感觉这速度不快啊

**Comment by fangpanpan** [comment]
> > 不知道您用哪种接口进行导入？我们建议您用c的接口。一般多线程批量导入会快些。
> 
> 我这边尝试用c的测试demo导入一千万条，大约1秒钟1万多条，感觉这速度不快啊

请问您是一次插入多条记录吗？是多线程还是单线程？以及您的一条数据里有几个字段？

**Comment by Leehom23** [comment]
> > > 不知道您用哪种接口进行导入？我们建议您用c的接口。一般多线程批量导入会快些。
> > 
> > 
> > 我这边尝试用c的测试demo导入一千万条，大约1秒钟1万多条，感觉这速度不快啊
> 
> 请问您是一次插入多条记录吗？是多线程还是单线程？以及您的一条数据里有几个字段？

我是把demo.c中的代码改为：
`int i = 0;
  for (i = 0; i < 100000000; ++i) {
    sprintf(qstr, "insert into m1 values (%ld, %d)", 1546300800000 + i, i * 10);
    if (taos_query(taos, qstr)) {
      printf("failed to insert row: %i, reason:%s\n", i, taos_errstr(taos));
    }
  }
`
测试的这个里面只有两个字段。

**Comment by fangpanpan** [comment]
> > > > 不知道您用哪种接口进行导入？我们建议您用c的接口。一般多线程批量导入会快些。
> > > 
> > > 
> > > 我这边尝试用c的测试demo导入一千万条，大约1秒钟1万多条，感觉这速度不快啊
> > 
> > 
> > 请问您是一次插入多条记录吗？是多线程还是单线程？以及您的一条数据里有几个字段？
> 
> 我是把demo.c中的代码改为：
> `int i = 0; for (i = 0; i < 100000000; ++i) { sprintf(qstr, "insert into m1 values (%ld, %d)", 1546300800000 + i, i * 10); if (taos_query(taos, qstr)) { printf("failed to insert row: %i, reason:%s\n", i, taos_errstr(taos)); } } `
> 测试的这个里面只有两个字段。

demo.c 里面里面是单线程单条插入，这种情况下插入速度大概就是2万/秒。一般我们建议一次插入多条数据（只要sql语句不超过64k）。 上面代码里的qstr可以多条拼接一下成 insert into m1 values (%ld, %d) (%ld, %d) (%ld, %d) (%Ld, %d)....。 假如您一次拼接了1千条记录，那么插入速度会大大提高。

**Comment by Leehom23** [comment]
> > > > > 不知道您用哪种接口进行导入？我们建议您用c的接口。一般多线程批量导入会快些。
> > > > 
> > > > 
> > > > 我这边尝试用c的测试demo导入一千万条，大约1秒钟1万多条，感觉这速度不快啊
> > > 
> > > 
> > > 请问您是一次插入多条记录吗？是多线程还是单线程？以及您的一条数据里有几个字段？
> > 
> > 
> > 我是把demo.c中的代码改为：
> > `int i = 0; for (i = 0; i < 100000000; ++i) { sprintf(qstr, "insert into m1 values (%ld, %d)", 1546300800000 + i, i * 10); if (taos_query(taos, qstr)) { printf("failed to insert row: %i, reason:%s\n", i, taos_errstr(taos)); } } `
> > 测试的这个里面只有两个字段。
> 
> demo.c 里面里面是单线程单条插入，这种情况下插入速度大概就是2万/秒。一般我们建议一次插入多条数据（只要sql语句不超过64k）。 上面代码里的qstr可以多条拼接一下成 insert into m1 values (%ld, %d) (%ld, %d) (%ld, %d) (%Ld, %d)....。 假如您一次拼接了1千条记录，那么插入速度会大大提高。

不好意思，我刚才才看到，有个asyndemo.c的代码好像是多线程操作多表的。我现在有很多的csv文件，用c语言处理的话，需要读取csv解析csv中的字段值，这样用c可以么？

**Comment by fangpanpan** [comment]
> > > > > > 不知道您用哪种接口进行导入？我们建议您用c的接口。一般多线程批量导入会快些。
> > > > > 
> > > > > 
> > > > > 我这边尝试用c的测试demo导入一千万条，大约1秒钟1万多条，感觉这速度不快啊
> > > > 
> > > > 
> > > > 请问您是一次插入多条记录吗？是多线程还是单线程？以及您的一条数据里有几个字段？
> > > 
> > > 
> > > 我是把demo.c中的代码改为：
> > > `int i = 0; for (i = 0; i < 100000000; ++i) { sprintf(qstr, "insert into m1 values (%ld, %d)", 1546300800000 + i, i * 10); if (taos_query(taos, qstr)) { printf("failed to insert row: %i, reason:%s\n", i, taos_errstr(taos)); } } `
> > > 测试的这个里面只有两个字段。
> > 
> > 
> > demo.c 里面里面是单线程单条插入，这种情况下插入速度大概就是2万/秒。一般我们建议一次插入多条数据（只要sql语句不超过64k）。 上面代码里的qstr可以多条拼接一下成 insert into m1 values (%ld, %d) (%ld, %d) (%ld, %d) (%Ld, %d)....。 假如您一次拼接了1千条记录，那么插入速度会大大提高。
> 
> 不好意思，我刚才才看到，有个asyndemo.c的代码好像是多线程操作多表的。我现在有很多的csv文件，大概两个亿行记录。用c语言处理的话，需要读取csv解析csv中的字段值，这样用c可以么？或者有别的建议么。我准备用超级表然后再创建很多子表？我看官网给的测试代码都没有建超级表，这样语法不是有局限性么。

[https://github.com/taosdata/TDengine/blob/master/tests/comparisonTest/tdengine/tdengineTest.c](url) 这个代码是从文本文件里读取数据（一亿条记录），建超级表，然后多线程批量插入子表里（100个子表），您可以参考一下。（关于这个代码的用途可参考[https://www.taosdata.com/blog/2019/07/19/tdengine与influxdb对比测试/](url)

**Comment by Leehom23** [comment]
> > > > > > > 不知道您用哪种接口进行导入？我们建议您用c的接口。一般多线程批量导入会快些。
> > > > > > 
> > > > > > 
> > > > > > 我这边尝试用c的测试demo导入一千万条，大约1秒钟1万多条，感觉这速度不快啊
> > > > > 
> > > > > 
> > > > > 请问您是一次插入多条记录吗？是多线程还是单线程？以及您的一条数据里有几个字段？
> > > > 
> > > > 
> > > > 我是把demo.c中的代码改为：
> > > > `int i = 0; for (i = 0; i < 100000000; ++i) { sprintf(qstr, "insert into m1 values (%ld, %d)", 1546300800000 + i, i * 10); if (taos_query(taos, qstr)) { printf("failed to insert row: %i, reason:%s\n", i, taos_errstr(taos)); } } `
> > > > 测试的这个里面只有两个字段。
> > > 
> > > 
> > > demo.c 里面里面是单线程单条插入，这种情况下插入速度大概就是2万/秒。一般我们建议一次插入多条数据（只要sql语句不超过64k）。 上面代码里的qstr可以多条拼接一下成 insert into m1 values (%ld, %d) (%ld, %d) (%ld, %d) (%Ld, %d)....。 假如您一次拼接了1千条记录，那么插入速度会大大提高。
> > 
> > 
> > 不好意思，我刚才才看到，有个asyndemo.c的代码好像是多线程操作多表的。我现在有很多的csv文件，大概两个亿行记录。用c语言处理的话，需要读取csv解析csv中的字段值，这样用c可以么？或者有别的建议么。我准备用超级表然后再创建很多子表？我看官网给的测试代码都没有建超级表，这样语法不是有局限性么。
> 
> [https://github.com/taosdata/TDengine/blob/master/tests/comparisonTest/tdengine/tdengineTest.c](url) 这个代码是从文本文件里读取数据（一亿条记录），建超级表，然后多线程批量插入子表里（100个子表），您可以参考一下。（关于这个代码的用途可参考[https://www.taosdata.com/blog/2019/07/19/tdengine与influxdb对比测试/](url)

感谢，感谢，我看一下。

**Comment by jtao1735** [comment]
> > > > > > > > 不知道您用哪种接口进行导入？我们建议您用c的接口。一般多线程批量导入会快些。
> > > > > > > 
> > > > > > > 
> > > > > > > 我这边尝试用c的测试demo导入一千万条，大约1秒钟1万多条，感觉这速度不快啊
> > > > > > 
> > > > > > 
> > > > > > 请问您是一次插入多条记录吗？是多线程还是单线程？以及您的一条数据里有几个字段？
> > > > > 
> > > > > 
> > > > > 我是把demo.c中的代码改为：
> > > > > `int i = 0; for (i = 0; i < 100000000; ++i) { sprintf(qstr, "insert into m1 values (%ld, %d)", 1546300800000 + i, i * 10); if (taos_query(taos, qstr)) { printf("failed to insert row: %i, reason:%s\n", i, taos_errstr(taos)); } } `
> > > > > 测试的这个里面只有两个字段。
> > > > 
> > > > 
> > > > demo.c 里面里面是单线程单条插入，这种情况下插入速度大概就是2万/秒。一般我们建议一次插入多条数据（只要sql语句不超过64k）。 上面代码里的qstr可以多条拼接一下成 insert into m1 values (%ld, %d) (%ld, %d) (%ld, %d) (%Ld, %d)....。 假如您一次拼接了1千条记录，那么插入速度会大大提高。
> > > 
> > > 
> > > 不好意思，我刚才才看到，有个asyndemo.c的代码好像是多线程操作多表的。我现在有很多的csv文件，大概两个亿行记录。用c语言处理的话，需要读取csv解析csv中的字段值，这样用c可以么？或者有别的建议么。我准备用超级表然后再创建很多子表？我看官网给的测试代码都没有建超级表，这样语法不是有局限性么。
> > 
> > 
> > [https://github.com/taosdata/TDengine/blob/master/tests/comparisonTest/tdengine/tdengineTest.c](url) 这个代码是从文本文件里读取数据（一亿条记录），建超级表，然后多线程批量插入子表里（100个子表），您可以参考一下。（关于这个代码的用途可参考[https://www.taosdata.com/blog/2019/07/19/tdengine与influxdb对比测试/](url)
> 
> 感谢，感谢，我看一下。

现在插入速度提高了吗？

**Comment by Leehom23** [comment]
> > > > > > > > > 不知道您用哪种接口进行导入？我们建议您用c的接口。一般多线程批量导入会快些。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我这边尝试用c的测试demo导入一千万条，大约1秒钟1万多条，感觉这速度不快啊
> > > > > > > 
> > > > > > > 
> > > > > > > 请问您是一次插入多条记录吗？是多线程还是单线程？以及您的一条数据里有几个字段？
> > > > > > 
> > > > > > 
> > > > > > 我是把demo.c中的代码改为：
> > > > > > `int i = 0; for (i = 0; i < 100000000; ++i) { sprintf(qstr, "insert into m1 values (%ld, %d)", 1546300800000 + i, i * 10); if (taos_query(taos, qstr)) { printf("failed to insert row: %i, reason:%s\n", i, taos_errstr(taos)); } } `
> > > > > > 测试的这个里面只有两个字段。
> > > > > 
> > > > > 
> > > > > demo.c 里面里面是单线程单条插入，这种情况下插入速度大概就是2万/秒。一般我们建议一次插入多条数据（只要sql语句不超过64k）。 上面代码里的qstr可以多条拼接一下成 insert into m1 values (%ld, %d) (%ld, %d) (%ld, %d) (%Ld, %d)....。 假如您一次拼接了1千条记录，那么插入速度会大大提高。
> > > > 
> > > > 
> > > > 不好意思，我刚才才看到，有个asyndemo.c的代码好像是多线程操作多表的。我现在有很多的csv文件，大概两个亿行记录。用c语言处理的话，需要读取csv解析csv中的字段值，这样用c可以么？或者有别的建议么。我准备用超级表然后再创建很多子表？我看官网给的测试代码都没有建超级表，这样语法不是有局限性么。
> > > 
> > > 
> > > [https://github.com/taosdata/TDengine/blob/master/tests/comparisonTest/tdengine/tdengineTest.c](url) 这个代码是从文本文件里读取数据（一亿条记录），建超级表，然后多线程批量插入子表里（100个子表），您可以参考一下。（关于这个代码的用途可参考[https://www.taosdata.com/blog/2019/07/19/tdengine与influxdb对比测试/](url)
> > 
> > 
> > 感谢，感谢，我看一下。
> 
> 现在插入速度提高了吗？

这几天有点忙别的，等这两天忙完把c编译完看看效果。

**Comment by sangshuduo** [comment]
no update, close it.
