### ISSUE TITLE
arm 平台下编译出错！

### ISSUE THREAD

**Issue by lllwan** [taosdata/TDengine#6]
/usr/bin/cmake -H/data/TDengine -B/data/TDengine/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /data/TDengine/build/CMakeFiles /data/TDengine/build/CMakeFiles/progress.marks
/usr/bin/make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/data/TDengine/build'
/usr/bin/make -f deps/zlib-1.2.11/CMakeFiles/z.dir/build.make deps/zlib-1.2.11/CMakeFiles/z.dir/depend
make[2]: Entering directory '/data/TDengine/build'
cd /data/TDengine/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/TDengine /data/TDengine/deps/zlib-1.2.11 /data/TDengine/build /data/TDengine/build/deps/zlib-1.2.11 /data/TDengine/build/deps/zlib-1.2.11/CMakeFiles/z.dir/DependInfo.cmake --color=
Scanning dependencies of target z
make[2]: Leaving directory '/data/TDengine/build'
/usr/bin/make -f deps/zlib-1.2.11/CMakeFiles/z.dir/build.make deps/zlib-1.2.11/CMakeFiles/z.dir/build
make[2]: Entering directory '/data/TDengine/build'
[  0%] Building C object deps/zlib-1.2.11/CMakeFiles/z.dir/src/adler32.c.o
cd /data/TDengine/build/deps/zlib-1.2.11 && /usr/bin/cc  -DLINUX -D_LIBC_REENTRANT -D_LINUX -D_M_X64 -D_REENTRANT -D__USE_POSIX -I/data/TDengine/deps/zlib-1.2.11/./inc  -g -std=gnu99 -Wall -fPIC -malign-double -Wno-char-subscripts -malign-stringops -msse4.2 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILE -O0 -DDEBUG   -std=gnu11 -o CMakeFiles/z.dir/src/adler32.c.o   -c /data/TDengine/deps/zlib-1.2.11/src/adler32.c
cc: error: unrecognized command line option '-malign-double'; did you mean '-falign-jumps'?
cc: error: unrecognized command line option '-malign-stringops'; did you mean '-Wwrite-strings'?
cc: error: unrecognized command line option '-msse4.2'
deps/zlib-1.2.11/CMakeFiles/z.dir/build.make:65: recipe for target 'deps/zlib-1.2.11/CMakeFiles/z.dir/src/adler32.c.o' failed
make[2]: *** [deps/zlib-1.2.11/CMakeFiles/z.dir/src/adler32.c.o] Error 1
make[2]: Leaving directory '/data/TDengine/build'
CMakeFiles/Makefile2:106: recipe for target 'deps/zlib-1.2.11/CMakeFiles/z.dir/all' failed
make[1]: *** [deps/zlib-1.2.11/CMakeFiles/z.dir/all] Error 2
make[1]: Leaving directory '/data/TDengine/build'
Makefile:130: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by guanshengliang** [comment]
The arm version is under development, it may take a few months

**Comment by chenqiang2080** [comment]
remove the "-malign-double"、“-malign-stringops” and "-msse4.2"

**Comment by chenqiang2080** [comment]
remove x86 hardware crc32, use the crc32c_sf，and take care unaligned problem.

**Comment by plum-lihui** [comment]
Yes, these changes are necessary. Thanks！

**Comment by qinglingzhiqing** [comment]
> remove x86 hardware crc32, use the crc32c_sf，and take care unaligned problem.

I don't understand, how to remove x86 hardware crc32 and replace it cre32c_sf?  
I don't know how to set this parameter.

**Comment by plum-lihui** [comment]
In tcrc32c.c file,  replace crc32c_hw() with crc32c_sf().

**Comment by qinglingzhiqing** [comment]
> In tcrc32c.c file,  replace crc32c_hw() with crc32c_sf().

Thanks. There is something wrong with -msse4.2 when I remove it from CMAKELISTs.
#TDengine/src/util/src/tcrc32c.c:20:10: fatal error: nmmintrin.h: No such file or directory
