### ISSUE TITLE
Can you provide a package that has been compiled for the major operating system version?

### ISSUE THREAD

**Issue by highfei2011** [taosdata/TDengine#60]
This will avoid the problems caused by many compilations.This can avoid many problems caused by compilation.

**Comment by hjxilinx** [comment]
please visit the website page to get the binary version.
https://www.taosdata.com/en/getting-started/#Quick%20Start

**Comment by highfei2011** [comment]
TDengine only runs on Linux  :)

**Comment by hjxilinx** [comment]
The client and development toolkit on windows will be available in a few days.

**Comment by highfei2011** [comment]
I am looking forward!
