### ISSUE TITLE
docker: no matching manifest for windows/amd64 10.0.17763 in the manifest list entries

### ISSUE THREAD

**Issue by qiankunshe** [taosdata/TDengine#6001]
**General Questions**
你好，我在windows server 2019 中用docker 安装 tdengine 时显示 docker: no matching manifest for windows/amd64 10.0.17763 in the manifest list entries ，我用的docker 版本是 20.10.5

**Comment by yu285** [comment]
会不会是docker设置问题：https://blog.csdn.net/weixin_39305029/article/details/105062218，您参考下

**Comment by qiankunshe** [comment]
对的就是这个原因，现在可以了
