### ISSUE TITLE
error:DNode does not exist

### ISSUE THREAD

**Issue by realwrtoff** [taosdata/TDengine#6002]
版本号：Welcome to the TDengine shell from Linux, Client Version:2.1.0.0
docker 启动，firstEp 和 fqn 配置 127.0.0.1 

2021/5/4 下午8:27:4205/04 12:27:42.893538 00000001 DND dnode shell rpc server is initialized
2021/5/4 下午8:27:4205/04 12:27:42.893550 00000001 DND step:dnode-shell is initialized
2021/5/4 下午8:27:4205/04 12:27:42.893560 00000001 DND dnode status timer is initialized
2021/5/4 下午8:27:4205/04 12:27:42.893565 00000001 DND step:dnode-statustmr is initialized
2021/5/4 下午8:27:4205/04 12:27:42.893607 00000001 DND dnode telemetry is initialized
2021/5/4 下午8:27:4205/04 12:27:42.893612 00000001 DND step:dnode-telemetry is initialized
2021/5/4 下午8:27:4205/04 12:27:42.893617 00000001 DND TDengine is initialized successfully
2021/5/4 下午8:27:42TDengine:[1]: Started TDengine service successfully.
2021/5/4 下午8:27:4305/04 12:27:43.399110 00000023 DND ERROR status rsp is received, error:DNode does not exist
2021/5/4 下午8:27:4405/04 12:27:44.403133 00000023 DND ERROR status rsp is received, error:DNode does not exist
2021/5/4 下午8:27:4505/04 12:27:45.403105 00000023 DND ERROR status rsp is received, error:DNode does not exist
2021/5/4 下午8:27:4605/04 12:27:46.403093 00000023 DND ERROR status rsp is received, error:DNode does not exist

**Comment by shuiche-it** [comment]
我也遇到了同样的问题：
[root@iZwzn9Z TDengine]# /usr/local/taos/bin/taosd
05/18 15:20:43.122994 00001850 DND start to initialize TDengine
05/18 15:20:43.123049 00001850 DND step:dnode-tfile is initialized
05/18 15:20:43.123062 00001850 DND step:dnode-rpc is initialized
05/18 15:20:43.123289 00001850 UTL localEp is: iZwz92yb2jcy7ub0acpjn9Z:6030
05/18 15:20:43.124489 00001850 UTL WARN timezone not configured, set to system default:Asia/Shanghai (CST, +0800)
05/18 15:20:43.124553 00001850 UTL WARN locale not configured, set to system default:zh_CN.UTF-8
05/18 15:20:43.124566 00001850 UTL WARN charset not configured, set to system default:UTF-8
05/18 15:20:43.124612 00001850 UTL    check global cfg completed
05/18 15:20:43.124619 00001850 UTL ==================================
05/18 15:20:43.124626 00001850 UTL    taos config & system info:
05/18 15:20:43.124632 00001850 UTL ==================================
05/18 15:20:43.124638 00001850 UTL  firstEp:                iZwz92yb2jcy7ub0acpjn9Z:6030 
05/18 15:20:43.124647 00001850 UTL  secondEp:               iZwz92yb2jcy7ub0acpjn9Z:6030 
05/18 15:20:43.124653 00001850 UTL  fqdn:                   iZwz92yb2jcy7ub0acpjn9Z 
05/18 15:20:43.124660 00001850 UTL  serverPort:             6030 
05/18 15:20:43.124667 00001850 UTL  configDir:              /etc/taos 
05/18 15:20:43.124673 00001850 UTL  logDir:                 /var/log/taos 
05/18 15:20:43.124680 00001850 UTL  scriptDir:              /etc/taos 
05/18 15:20:43.124687 00001850 UTL  arbitrator:              
05/18 15:20:43.124693 00001850 UTL  numOfThreadsPerCore:    1.000000 
05/18 15:20:43.124707 00001850 UTL  numOfCommitThreads:     4 
05/18 15:20:43.124715 00001850 UTL  ratioOfQueryCores:      1.000000 
05/18 15:20:43.124722 00001850 UTL  numOfMnodes:            3 
05/18 15:20:43.124748 00001850 UTL  vnodeBak:               1 
05/18 15:20:43.124755 00001850 UTL  telemetryReporting:     1 
05/18 15:20:43.124762 00001850 UTL  balance:                1 
05/18 15:20:43.124768 00001850 UTL  balanceInterval:        300 
05/18 15:20:43.124774 00001850 UTL  role:                   0 
05/18 15:20:43.124780 00001850 UTL  maxTmrCtrl:             512 
05/18 15:20:43.124787 00001850 UTL  monitorInterval:        30(s)
05/18 15:20:43.124793 00001850 UTL  offlineThreshold:       864000(s)
05/18 15:20:43.124799 00001850 UTL  rpcTimer:               1000(ms)
05/18 15:20:43.124806 00001850 UTL  rpcMaxTime:             600(s)
05/18 15:20:43.124812 00001850 UTL  statusInterval:         1(s)
05/18 15:20:43.124818 00001850 UTL  shellActivityTimer:     3(s)
05/18 15:20:43.124824 00001850 UTL  minSlidingTime:         10(ms)
05/18 15:20:43.124831 00001850 UTL  minIntervalTime:        10(ms)
05/18 15:20:43.124837 00001850 UTL  maxStreamCompDelay:     20000(ms)
05/18 15:20:43.124844 00001850 UTL  maxFirstStreamCompDelay:10000(ms)
05/18 15:20:43.124850 00001850 UTL  retryStreamCompDelay:   10(ms)
05/18 15:20:43.124856 00001850 UTL  streamCompDelayRatio:   0.100000 
05/18 15:20:43.124876 00001850 UTL  maxVgroupsPerDb:        0 
05/18 15:20:43.124883 00001850 UTL  maxTablesPerVnode:      1000000 
05/18 15:20:43.124889 00001850 UTL  minTablesPerVnode:      1000 
05/18 15:20:43.124895 00001850 UTL  tableIncStepPerVnode:   1000 
05/18 15:20:43.124901 00001850 UTL  cache:                  16(Mb)
05/18 15:20:43.124906 00001850 UTL  blocks:                 6 
05/18 15:20:43.124912 00001850 UTL  days:                   10 
05/18 15:20:43.124918 00001850 UTL  keep:                   3650 
05/18 15:20:43.124924 00001850 UTL  minRows:                100 
05/18 15:20:43.124930 00001850 UTL  maxRows:                4096 
05/18 15:20:43.124935 00001850 UTL  comp:                   2 
05/18 15:20:43.124940 00001850 UTL  walLevel:               1 
05/18 15:20:43.124947 00001850 UTL  fsync:                  3000 
05/18 15:20:43.124953 00001850 UTL  replica:                1 
05/18 15:20:43.124959 00001850 UTL  partitions:             4 
05/18 15:20:43.124965 00001850 UTL  quorum:                 1 
05/18 15:20:43.124971 00001850 UTL  update:                 0 
05/18 15:20:43.124976 00001850 UTL  compressMsgSize:        -1 
05/18 15:20:43.124983 00001850 UTL  maxSQLLength:           1048576(byte)
05/18 15:20:43.124992 00001850 UTL  maxNumOfOrderedRes:     100000 
05/18 15:20:43.124998 00001850 UTL  queryBufferSize:        -1(byte)
05/18 15:20:43.125003 00001850 UTL  retrieveBlockingModel:  0 
05/18 15:20:43.125010 00001850 UTL  keepColumnName:         0 
05/18 15:20:43.125016 00001850 UTL  timezone:               Asia/Shanghai (CST, +0800) 
05/18 15:20:43.125023 00001850 UTL  locale:                 zh_CN.UTF-8 
05/18 15:20:43.125029 00001850 UTL  charset:                UTF-8 
05/18 15:20:43.125036 00001850 UTL  maxShellConns:          50000 
05/18 15:20:43.125042 00001850 UTL  maxConnections:         5000 
05/18 15:20:43.125048 00001850 UTL  minimalLogDirGB:        1.000000(GB)
05/18 15:20:43.125055 00001850 UTL  minimalTmpDirGB:        1.000000(GB)
05/18 15:20:43.125062 00001850 UTL  minimalDataDirGB:       2.000000(GB)
05/18 15:20:43.125069 00001850 UTL  mnodeEqualVnodeNum:     4 
05/18 15:20:43.125075 00001850 UTL  flowctrl:               1 
05/18 15:20:43.125082 00001850 UTL  slaveQuery:             1 
05/18 15:20:43.125087 00001850 UTL  adjustMaster:           1 
05/18 15:20:43.125094 00001850 UTL  http:                   1 
05/18 15:20:43.125100 00001850 UTL  mqtt:                   0 
05/18 15:20:43.125107 00001850 UTL  monitor:                1 
05/18 15:20:43.125113 00001850 UTL  stream:                 1 
05/18 15:20:43.125119 00001850 UTL  httpEnableRecordSql:    0 
05/18 15:20:43.125126 00001850 UTL  telegrafUseFieldNum:    0 
05/18 15:20:43.125132 00001850 UTL  httpMaxThreads:         2 
05/18 15:20:43.125138 00001850 UTL  restfulRowLimit:        10240 
05/18 15:20:43.125145 00001850 UTL  numOfLogLines:          10000000 
05/18 15:20:43.125151 00001850 UTL  logKeepDays:            0 
05/18 15:20:43.125158 00001850 UTL  asyncLog:               1 
05/18 15:20:43.125164 00001850 UTL  debugFlag:              0 
05/18 15:20:43.125171 00001850 UTL  mDebugFlag:             131 
05/18 15:20:43.125177 00001850 UTL  dDebugFlag:             135 
05/18 15:20:43.125184 00001850 UTL  sDebugFlag:             135 
05/18 15:20:43.125190 00001850 UTL  wDebugFlag:             135 
05/18 15:20:43.125196 00001850 UTL  sdbDebugFlag:           131 
05/18 15:20:43.125203 00001850 UTL  rpcDebugFlag:           131 
05/18 15:20:43.125209 00001850 UTL  tmrDebugFlag:           131 
05/18 15:20:43.125215 00001850 UTL  cDebugFlag:             131 
05/18 15:20:43.125221 00001850 UTL  jniDebugFlag:           131 
05/18 15:20:43.125227 00001850 UTL  odbcDebugFlag:          131 
05/18 15:20:43.125232 00001850 UTL  uDebugFlag:             131 
05/18 15:20:43.125238 00001850 UTL  httpDebugFlag:          131 
05/18 15:20:43.125243 00001850 UTL  mqttDebugFlag:          131 
05/18 15:20:43.125249 00001850 UTL  monDebugFlag:           131 
05/18 15:20:43.125354 00001850 UTL  qDebugFlag:             131 
05/18 15:20:43.125362 00001850 UTL  vDebugFlag:             135 
05/18 15:20:43.125373 00001850 UTL  tsdbDebugFlag:          131 
05/18 15:20:43.125379 00001850 UTL  cqDebugFlag:            131 
05/18 15:20:43.125385 00001850 UTL  enableRecordSql:        0 
05/18 15:20:43.125390 00001850 UTL  enableCoreFile:         0 
05/18 15:20:43.125396 00001850 UTL  gitinfo:                7a03092edd06d3247d4c1bbe796d55f51c3a1c53 
05/18 15:20:43.125402 00001850 UTL  gitinfoOfInternal:      NULL 
05/18 15:20:43.125408 00001850 UTL  buildinfo:              Built at 2021-05-01 22:01 
05/18 15:20:43.125414 00001850 UTL  version:                2.1.0.0 
05/18 15:20:43.125420 00001850 UTL  maxBinaryDisplayWidth:  30 
05/18 15:20:43.125425 00001850 UTL  tempDir:                /tmp/ 
05/18 15:20:43.125433 00001850 UTL  os pageSize:            4096(KB)
05/18 15:20:43.125438 00001850 UTL  os openMax:             65535
05/18 15:20:43.125444 00001850 UTL  os streamMax:           16
05/18 15:20:43.125450 00001850 UTL  os numOfCores:          2
05/18 15:20:43.125455 00001850 UTL  os totalDisk:           0.000000(GB)
05/18 15:20:43.125472 00001850 UTL  os usedDisk:            0.000000(GB)
05/18 15:20:43.125478 00001850 UTL  os availDisk:           0.000000(GB)
05/18 15:20:43.125488 00001850 UTL  os totalMemory:         8001(MB)
05/18 15:20:43.125497 00001850 UTL  os sysname:             Linux
05/18 15:20:43.125503 00001850 UTL  os nodename:            iZwz92yb2jcy7ub0acpjn9Z
05/18 15:20:43.125509 00001850 UTL  os release:             2.6.32-696.10.1.el6.x86_64
05/18 15:20:43.125514 00001850 UTL  os version:             #1 SMP Tue Aug 22 18:51:35 UTC 2017
05/18 15:20:43.125520 00001850 UTL  os machine:             x86_64
05/18 15:20:43.125527 00001850 UTL  dataDir: /var/lib/taos
05/18 15:20:43.125533 00001850 UTL ==================================
05/18 15:20:43.125538 00001850 DND step:dnode-globalcfg is initialized
05/18 15:20:43.125586 00001850 TFS disk /var/lib/taos is mounted to tier level 0 id 0
05/18 15:20:43.125669 00001850 DND dnode storage is initialized at /var/lib/taos/dnode
05/18 15:20:43.125676 00001850 DND step:dnode-storage is initialized
05/18 15:20:43.125706 00001850 DND dnode cfg is initialized
05/18 15:20:43.125711 00001850 DND step:dnode-cfg is initialized
05/18 15:20:43.125767 00001850 DND dnode eps is initialized
05/18 15:20:43.125774 00001850 DND step:dnode-eps is initialized
05/18 15:20:43.125796 00001850 DND dnode minfos is initialized
05/18 15:20:43.125802 00001850 DND step:dnode-minfos is initialized
05/18 15:20:43.125851 00001850 WAL wal module is initialized, rsetId:3
05/18 15:20:43.125858 00001850 DND step:dnode-wal is initialized
05/18 15:20:43.125941 00001850 DND step:dnode-sync is initialized
05/18 15:20:43.125996 00001850 DND dnode check is initialized
05/18 15:20:43.126003 00001850 DND step:dnode-check is initialized
05/18 15:20:43.126010 00001850 UTL worker:vquery is initialized, min:2 max:2
05/18 15:20:43.126016 00001850 UTL worker:vfetch is initialized, min:2 max:2
05/18 15:20:43.126020 00001850 DND step:dnode-vread is initialized
05/18 15:20:43.126026 00001850 DND dnode vwrite is initialized, max worker 2
05/18 15:20:43.126030 00001850 DND step:dnode-vwrite is initialized
05/18 15:20:43.126069 00001850 DND step:vnode-backup is initialized
05/18 15:20:43.151210 00001850 DND step:vnode-worker is initialized
05/18 15:20:43.151240 00001850 DND step:vnode-write is initialized
05/18 15:20:43.151246 00001850 DND step:vnode-read is initialized
05/18 15:20:43.151255 00001850 DND step:vnode-hash is initialized
05/18 15:20:43.151372 00001850 DND step:tsdb-queue is initialized
05/18 15:20:43.151383 00001850 UTL worker:vmgmt is initialized, min:1 max:1
05/18 15:20:43.151419 00001850 DND dnode vmgmt is initialized
05/18 15:20:43.151427 00001850 DND step:dnode-vmgmt is initialized
05/18 15:20:43.151444 00001850 DND step:dnode-mread is initialized
05/18 15:20:43.151458 00001850 DND step:dnode-mwrite is initialized
05/18 15:20:43.151483 00001850 DND step:dnode-mpeer is initialized
05/18 15:20:43.201489 00001850 DND dnode inter-dnodes rpc client is initialized
05/18 15:20:43.201545 00001850 DND step:dnode-client is initialized
05/18 15:20:43.202171 00001850 DND dnode inter-dnodes RPC server is initialized
05/18 15:20:43.202184 00001850 DND step:dnode-server is initialized
05/18 15:20:43.202229 00001850 DND start 2 threads to open 0 vnodes
05/18 15:20:43.202237 00001850 DND there are total vnodes:0, opened:0
05/18 15:20:43.202243 00001850 DND step:dnode-vnodes is initialized
05/18 15:20:43.202262 00001850 MND starting to initialize mnode ...
05/18 15:20:43.202500 00001850 DND step:sdbref is initialized
05/18 15:20:43.202619 00001850 DND step:profile is initialized
05/18 15:20:43.202640 00001850 DND step:cluster is initialized
05/18 15:20:43.202650 00001850 DND step:accts is initialized
05/18 15:20:43.202660 00001850 DND step:users is initialized
05/18 15:20:43.202669 00001850 DND step:dnodes is initialized
05/18 15:20:43.202676 00001850 DND step:dbs is initialized
05/18 15:20:43.202685 00001850 DND step:vgroups is initialized
05/18 15:20:43.202965 00001850 DND step:tables is initialized
05/18 15:20:43.202976 00001850 DND step:mnodes is initialized
05/18 15:20:43.203008 00001850 MND vgId:1, sdb write is opened
05/18 15:20:43.203034 00001850 SDB vgId:1, open sdb wal for restore
05/18 15:20:43.203061 00001850 WAL vgId:1, file:/var/lib/taos/mnode/wal/wal0, will be restored
05/18 15:20:43.203113 00001850 MND dnode:1, fqdn: ep::6030 port:6030 is created
05/18 15:20:43.203125 00001850 MND mnode:1, fqdn: ep::6030 port:6030 is created
05/18 15:20:43.203163 00001850 WAL vgId:1, file:/var/lib/taos/mnode/wal/wal0, restore success, wver:7
05/18 15:20:43.203180 00001850 SDB vgId:1, sdb wal load success
05/18 15:20:43.203184 00001850 SDB vgId:1, sdb start to check for integrity
05/18 15:20:43.203191 00001850 SDB vgId:1, sdb:cluster is checked, rows:1
05/18 15:20:43.203197 00001850 SDB vgId:1, sdb:dnodes is checked, rows:1
05/18 15:20:43.203201 00001850 MND vgId:1, update mnodes epSet, numOfMnodes:1
05/18 15:20:43.203212 00001850 MND vgId:1, mnodes epSet is set, num:1 inUse:0
05/18 15:20:43.203218 00001850 MND vgId:1, mnode:1, fqdn: shell:6030 peer:6035
05/18 15:20:43.203223 00001850 SDB vgId:1, sdb:mnodes is checked, rows:1
05/18 15:20:43.203228 00001850 SDB vgId:1, sdb:accounts is checked, rows:1
05/18 15:20:43.203232 00001850 SDB vgId:1, sdb:users is checked, rows:3
05/18 15:20:43.203236 00001850 SDB vgId:1, sdb:dbs is checked, rows:0
05/18 15:20:43.203240 00001850 SDB vgId:1, sdb:vgroups is checked, rows:0
05/18 15:20:43.203244 00001850 SDB vgId:1, sdb:stables is checked, rows:0
05/18 15:20:43.203248 00001850 SDB vgId:1, sdb:ctables is checked, rows:0
05/18 15:20:43.203252 00001850 SDB vgId:1, sdb is restored, mver:7 rows:7 tables:9
05/18 15:20:43.203259 00001850 DND step:sdb is initialized
05/18 15:20:43.203294 00001850 MND dnode:1 set access:0 to 0
05/18 15:20:43.203304 00001850 DND step:balance is initialized
05/18 15:20:43.203310 00001850 DND step:grant is initialized
05/18 15:20:43.203390 00001850 DND step:show is initialized
05/18 15:20:43.203398 00001850 MND mnode is initialized successfully
05/18 15:20:43.203486 00001850 DND dnode modules is initialized
05/18 15:20:43.203497 00001850 HTP start http server ...
05/18 15:20:43.203555 00001850 HTP http result queue is opened
05/18 15:20:43.203914 00001883 HTP http server init success at 6041
05/18 15:20:43.204305 00001850 MON monitor module start
05/18 15:20:43.204316 00001850 DND step:dnode-modules is initialized
05/18 15:20:43.205034 00001850 DND dnode shell rpc server is initialized
05/18 15:20:43.205051 00001850 DND step:dnode-shell is initialized
05/18 15:20:43.205060 00001850 DND dnode status timer is initialized
05/18 15:20:43.205064 00001850 DND step:dnode-statustmr is initialized
05/18 15:20:43.205103 00001850 DND dnode telemetry is initialized
05/18 15:20:43.205111 00001850 DND step:dnode-telemetry is initialized
05/18 15:20:43.205117 00001850 DND TDengine is initialized successfully
05/18 15:20:43.711547 00001863 DND ERROR status rsp is received, error:DNode does not exist
05/18 15:20:44.715894 00001863 DND ERROR status rsp is received, error:DNode does not exist
05/18 15:20:45.720877 00001863 DND ERROR status rsp is received, error:DNode does not exist
05/18 15:20:46.726111 00001863 DND ERROR status rsp is received, error:DNode does not exist
05/18 15:20:47.730912 00001863 DND ERROR status rsp is received, error:DNode does not exist
05/18 15:20:48.735875 00001863 DND ERROR status rsp is received, error:DNode does not exist
05/18 15:20:49.740890 00001863 DND ERROR status rsp is received, error:DNode does not exist
05/18 15:20:50.745917 00001863 DND ERROR status rsp is received, error:DNode does not exist
^[c05/18 15:20:51.750895 00001863 DND ERROR status rsp is received, error:DNode does not exist
05/18 15:20:52.755882 00001863 DND ERROR status rsp is received, error:DNode does not exist
05/18 15:20:53.760889 00001863 DND ERROR status rsp is received, error:DNode does not exist
05/18 15:20:54.765896 00001863 DND ERROR status rsp is received, error:DNode does not exist
05/18 15:20:55.770944 00001863 DND ERROR status rsp is received, error:DNode does not exist
05/18 15:20:56.776035 00001863 DND ERROR status rsp is received, error:DNode does not exist
05/18 15:20:57.780899 00001863 DND ERROR status rsp is received, error:DNode does not exist

**Comment by dingweihao** [comment]
原因找到：先使用旧版本，后来切换新版本，加载新版本之前，先清除了旧版本的数据，忘记清除/var/log/taos的内容。把该目录清除后，问题消失。记录在此，共享
