### ISSUE TITLE
why the elapsed time  of  SQL in TDengine shell is different from  the sql   run in  "taosdemo -s file.sql" ?

### ISSUE THREAD

**Issue by YiFlower** [taosdata/TDengine#6016]
我在使用TDengine shell执行一条sql，大概需要2.5s左右：
`taos> select sum(point_value) from t1 union all select sum(point_value) from t2 union all select sum(point_value) from t3 union all select sum(point_value) from t4 union allselect sum(point_value) from t5 union all...;
     sum(point_value)      |
--------------------------------------
     50000740506.562576294 |
     49996624635.307662964 |
     50002893802.827201843 |
     49996877021.113235474 |
     49999111051.163093567 |
     50002441404.520187378 |
     50001024342.718170166 |
     50001024877.116317749 |
     49997724769.185867310 |
     50004136530.500869751 |
Query OK, 10 row(s) in set (2.457249s)`
这条sql是查询demo超级表下面的十张子表，使用union all连接查询。

然后我使用taosdemo，执行taosdemo -h cdh3.macro.com -d traindb -y -q 1   -s ./sum命令：
`[root@cdh1 testFile]# taosdemo -h cdh3.macro.com -d traindb  -y -q 1   -s ./sum
run ./sum took 0.040306 second(s)`
这个明显的差距让我感到不解。

我进一步直接查询超级表，在使用TDengine shell查询：
`taos> select sum(point_value) from demo;
     sum(point_value)      |
--------------------------------------
    500002598941.009277344 |
Query OK, 1 row(s) in set (1.723467s)
`
相比之下，而使用taosdemo：
`[root@cdh1 testSuper]# taosdemo -h cdh3.macro.com -d traindb -y -q 1   -s ./sum
run ./sum took 1.612993 second(s)
`

明显前者的差距更大。
这是为什么呢？

**Comment by yu285** [comment]
建议在taosdemo中先把sql结果输出到csv文件中，看看是否跑出相同的内容。
