### ISSUE TITLE
TDEngine seems not working on Ubuntu 18.04.3 installed on raspberry pi 3B+ 

### ISSUE THREAD

**Issue by neoitec** [taosdata/TDengine#602]
**Bug Description**
The service won't start. It shows failed

**To Reproduce**
1. Install TDengine on Ubuntu 18.04.3 with raspberry pi 3 as host

2. service won't start

3. "service taosd status" with out comment "restart=always"
taosd.service: Failed to execute command: Exec format error
taosd.service: Failed at step EXEC spawning /usr/bin/taosd: Exec format error

**Expected Behavior**
To run normally

**Environment (please complete the following information):**
 - OS: Linux ubuntu 4.15.0-1048-raspi2 #52-Ubuntu SMP PREEMPT Wed Sep 18 08:57:33 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
 - Raspberry pi 3 B +
 - TDengine Version 1.6.2.2

**Comment by hzcheng** [comment]
Currently, we don't support ARM architecture. That version will be released at the end of this year.
