### ISSUE TITLE
question of taosdump about table length

### ISSUE THREAD

**Issue by qiaogli** [taosdata/TDengine#6042]
![image](https://user-images.githubusercontent.com/83851179/117523478-1c2fc480-afeb-11eb-9dec-833d5df34ac8.png)

taosdump 导出的create table的语句表名有缺失，insert的时候就会报 Table does not exist，是导出的时候对表名长度有限制吗

**Comment by sangshuduo** [comment]
原来的表名是多长?

**Comment by qiaogli** [comment]
截图上insert语句的是原来的表名是长度是65个字符，但是导出的create语句创建的表名只能显示前面64个，业务上的话还有可能更长，我看了几个导出的create语句都是只能显示前64个字符，业务上小于64字符的就没问题，大于64字符的就有问题

**Comment by sangshuduo** [comment]
@qiaogli 好的，我们尽快修复这个问题，谢谢

**Comment by sangshuduo** [comment]
这个问题已经在新版本里解决了
