### ISSUE TITLE
Is there any performance comparison with Promethus TSDB or Dolphindb?

### ISSUE THREAD

**Issue by dingrui37** [taosdata/TDengine#605]
请问有没有跟Promethus TSDB的对比？
以及国内浙江智臾的dolphindb的对比？

**Comment by fangpanpan** [comment]
在我们公司网站的[首页](https://www.taosdata.com/cn/)我们有做过和influxdb, clickhouse, cassandra, opentsdb的对比，目前还没有做和Promethus TSDB以及Dolphindb的对比，以后我们会考虑加进去。如果您有兴趣的话，也可以自己测试一下。

**Comment by TS668** [comment]
你们做的这些性能测试，能不能标一下你们哪些用了预计算？感觉你们的很多测试项目，你们用了预计算，但是别人没有用预计算。这样的结果，对别人非常不公平。如果你们有意这样做的话，甚至可以说是作弊。

**Comment by fangpanpan** [comment]
> 你们做的这些性能测试，能不能标一下你们哪些用了预计算？感觉你们的很多测试项目，你们用了预计算，但是别人没有用预计算。这样的结果，对别人非常不公平。如果你们有意这样做的话，甚至可以说是作弊。

请问您可以详细解释一下您所说的预计算是指什么吗？我们所理解的预计算是关于数据库的数据写入和存储设计的，不专门针对一次测试，请问您说我们做的而别人没有用的预计算具体指的是什么？

**Comment by dingrui37** [comment]
@fangpanpan 我看到了，其实我主要想了解和Promethus的对比，因为Promethus有很多厂商在使用，并且生态也比较好，而dolphindb并没有开源，我们应该不会考虑使用，看其官网介绍“每秒百万级数据写入。万亿级数据毫秒级查询与秒级计算响应。”，但是这个说法太模糊了。

**Comment by TS668** [comment]
@fangpanpan 我指的是查询方面的测试。一些计算任务，你们是插入的时候已经提前算好了，别人没有提前算。这样直接拿来比，你们当然会比别人快很多。

**Comment by fangpanpan** [comment]
> @fangpanpan 我指的是查询方面的测试。一些计算任务，你们是插入的时候已经提前算好了，别人没有提前算。这样直接拿来比，你们当然会比别人快很多。



> @fangpanpan 我指的是查询方面的测试。一些计算任务，你们是插入的时候已经提前算好了，别人没有提前算。这样直接拿来比，你们当然会比别人快很多。

那请问oracle 等很多数据库都有索引，算不算预计算？以及您了解了influxdb、clickhouse等数据库有没有预计算？

**Comment by fangpanpan** [comment]
> 索引有索引的好处和坏处。一般索引不归于预计算的范畴。
> 
> 我没有别的意思，大家都是专业人士，你们做这些测试，最好说清楚是怎么回事儿，apple和apple比，orange和orange比，但是不要把查询自己的提前计算好的速度和别人当场算的速度拿来对比。influxdb、clickhouse有没有预计算，你们应该在测试项目里面注明啊。
> 
> 毕竟工业物联网领域，能用到预计算结果的场景不多。

请问您能先给一个预计算的定义吗？然后我们才好说是提前计算好还是当场算的。我之前说了，我们的预计算是关于数据库的数据写入和存储设计的，不专门针对一次测试。

**Comment by liu0x54** [comment]
> @fangpanpan 我看到了，其实我主要想了解和Promethus的对比，因为Promethus有很多厂商在使用，并且生态也比较好，而dolphindb并没有开源，我们应该不会考虑使用，看其官网介绍“每秒百万级数据写入。万亿级数据毫秒级查询与秒级计算响应。”，但是这个说法太模糊了。

prometheus使用方式上有些区别，是主动去查询的方式；而tdengine是接收数据上报的方式；可能使用方式和配置上差别也挺大的

**Comment by jtao1735** [comment]
> 索引有索引的好处和坏处。一般索引不归于预计算的范畴。
> 
> 我没有别的意思，大家都是专业人士，你们做这些测试，最好说清楚是怎么回事儿，apple和apple比，orange和orange比，但是不要把查询自己的提前计算好的速度和别人当场算的速度拿来对比。influxdb、clickhouse有没有预计算，你们应该在测试项目里面注明啊。
> 
> 毕竟工业物联网领域，能用到预计算结果的场景不多。

我们对于简单的sum, avg类的操作，按照时间段是有预计算的。欢迎看我们代码是怎么实现的，我们的测试代码、数据集也是公开的，欢迎自己亲自对比
