### ISSUE TITLE
springbootdemo

### ISSUE THREAD

**Issue by git846486188** [taosdata/TDengine#6065]
执行插入操作，中文"北京"识别为北京，报错， jdbc驱动版本2.0.28，taos服务版本2.1.0.0
![image](https://user-images.githubusercontent.com/44331938/117603971-dad41c00-b186-11eb-8d00-a81d46d570cb.png)

**Comment by zyyang-taosdata** [comment]
感谢您的提问，我来检查一下

**Comment by zyyang-taosdata** [comment]
https://github.com/taosdata/TDengine/issues/4916
