### ISSUE TITLE
 What is 'UTL ERROR failed to connect socket, ip:0xbf1d6927, port:80(poll error/conn timeout)' ?

### ISSUE THREAD

**Issue by HendSame** [taosdata/TDengine#6066]
**General Questions**

If all the ways above couldn't help, please clearly and concisely describe what the question is.

What is it  in the file : /var/log/taos/taosinfo.0?

They all look fine！
But I have find a error log :

```
 UTL ERROR failed to connect socket, ip:0xbf1d6927, port:80(poll error/conn timeout)
```

Is that a problem？

TDengine version: 2.1.0.0

**Comment by yu285** [comment]
does it work fine ?
