### ISSUE TITLE
failed to get charset, please set the valid charset in config file

### ISSUE THREAD

**Issue by charleswu52** [taosdata/TDengine#607]
系统:Ubuntu16.04 lts serve
提示错误：Welcome to the TDengine shell from linux, client version:1.6.2.2, failed to get charset, please set the valid charset in config file
怎么解决？

**Comment by fangpanpan** [comment]
您可以将taos.cfg 文件里的locale 那一行的注释取消

**Comment by holmescn** [comment]
在 Docker ubuntu:18.04 中遇到了同样的问题，已经取消了 locale 前面的注释和 charset 前面的注释，安装了 locales，并在 locale.gen 中取消了 en_US.UTF-8 和 zh_CN.UTF-8 的注释，重新生成了 locale-gen。问题仍然没有解决……

**Comment by xaseven** [comment]
Shell的原因，今天手贱用了下Royal TSX（相当于windows的XShell ，以前用自带的Terminal都好着呢,今天登录后发现提示：-bash: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
用机器自带的Terminal登录就没问题
