### ISSUE TITLE
Select different result records with same condition

### ISSUE THREAD

**Issue by nanjj** [taosdata/TDengine#6073]
**Bug Description**
Select different result records with same condition

**To Reproduce**
1. Create database and use it
    ```
    create database testit precision 'us' update 1;
    use testit;
    ```
2. Create stable and tables, prepare data
    ```
    create stable testit(ts timestamp, delay int) tags(status int);
    create table testit0 using testit tags(0);
    create table testit1 using testit tags(1);
    insert into testit0(ts) values(now);
    insert into testit0(ts, delay) values(now, 10);
    insert into testit1(ts) values(now);
    select * from testit;  #=>
               ts             |    delay    |   status    |
    =========================================================
     2021-05-10 08:27:56.524292 |        NULL |           0 |
     2021-05-10 08:27:56.550771 |          10 |           0 |
     2021-05-10 08:27:58.215590 |        NULL |           1 |
   ```
3. Select with where condition
    ```
    select ts, delay, status from testit where delay is not NULL; #=>
                 ts             |    delay    |   status    |
    =========================================================
     2021-05-10 08:27:56.550771 |          10 |           0 |

   select status from testit where delay is not NULL; #=>
        status    |
    ==============
                 0 |
                 1 |
    ```
    You can see the second query select the status = 1 out, why?

**Expected Behavior**
Only one record should be selected with same condition.

**Screenshots**
![image](https://user-images.githubusercontent.com/640746/117631317-b1c78180-b1ae-11eb-938d-0c555d4b8511.png)

**Environment (please complete the following information):**
 ```
taos> select server_version();
 server_version() |
===================
 2.1.0.0          |
Query OK, 1 row(s) in set (0.000179s)

taos> select client_version();
 client_version() |
===================
 2.1.0.0          |
Query OK, 1 row(s) in set (0.000178s)
 ```

**Additional Context**

**Comment by yu285** [comment]
we are working on this, please wait . thanks for understanding

**Comment by yu285** [comment]
currently，we don't support the select  tag separately ,it will return a result set which has no repeated rows .

if you use "select ts,status xxxxxx" it would give u a correct feedback .

we are working on it , so as to expect to return a error or warning when user run "select  tag xxx  where xxx"

**Comment by nanjj** [comment]
@yu285 but, why not to support the scenario? what's the block issue?

**Comment by yu285** [comment]
Because tag is just one single static row of data  ,if you have 100000 rows , it would return 100000 repeated rows ,it is meaningless
