### ISSUE TITLE
TDError.DatabaseError.ProgrammingError:-xx  

### ISSUE THREAD

**Issue by sexbee** [taosdata/TDengine#609]
**Bug Description**
td-connector  insert data into taosdatd ,alert error sometimes 

create tables with st_tablename  :
insert into `${dataname}` using st_tablename  values(file1,file2,file3...);====>TDError.DatabaseError.ProgrammingError:-48;

create tables without st_tablename  :+1: 
insert into `${dataname}`   values(file1,file2,file3...);====> ok

when column(BINARY) includ "" or  "^" or else ======> TDError.DatabaseError.ProgrammingError:--64 or 112;  alert  err sometime

**Comment by StoneT2000** [comment]
Update td-connector to newest version 1.3.2
Added fix for bug where error messages were outputting as just a number, not the actual error string. #610
