### ISSUE TITLE
taosd reports segmentation fault

### ISSUE THREAD

**Issue by BestHYY** [taosdata/TDengine#6096]
使用develop分支版本(libtaos版本为**libtaos.so.2.1.0.0**)和之前的版本(**libtaos.so.2.0.19.0**)，使用arm-linux-gnueabihf-gcc交叉编译运行在imx6ull开发板上，taosd在运行一段时间后出现**segmentation fault**，gdb调试获取到的堆栈信息如下

Thread 21 "taosd" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x6a0ff460 (LWP 12888)]
0x76f4d4da in copyOneRowFromMem (pQueryHandle=0x745f8d50, capacity=4096, numOfRows=873, row=0x67129909, numOfCols=7, pTable=0x6a92bd50, pSchema=0x6a92be18)
    at /home/yyhuang/Projects/TDengine/src/tsdb/src/tsdbRead.c:1410
1410    /home/yyhuang/Projects/TDengine/src/tsdb/src/tsdbRead.c: No such file or directory.
(gdb) bt
#0  0x76f4d4da in copyOneRowFromMem (pQueryHandle=0x745f8d50, capacity=4096, numOfRows=873, row=0x67129909, numOfCols=7, pTable=0x6a92bd50, pSchema=0x6a92be18)
    at /home/yyhuang/Projects/TDengine/src/tsdb/src/tsdbRead.c:1410
#1  0x76f4fec6 in tsdbReadRowsFromCache (pCheckInfo=0x745fb8a0, maxKey=9223372036854775, maxRowsToRead=4096, win=0x745f8d76, pQueryHandle=0x745f8d50)
    at /home/yyhuang/Projects/TDengine/src/tsdb/src/tsdbRead.c:2321
#2  0x76f4ba14 in hasMoreDataInCache (pHandle=0x745f8d50) at /home/yyhuang/Projects/TDengine/src/tsdb/src/tsdbRead.c:825
#3  0x76f4fb78 in doHasDataInBuffer (pQueryHandle=0x745f8d50) at /home/yyhuang/Projects/TDengine/src/tsdb/src/tsdbRead.c:2240
#4  0x76f50758 in tsdbNextDataBlock (pHandle=0x745f8d50) at /home/yyhuang/Projects/TDengine/src/tsdb/src/tsdbRead.c:2528
#5  0x76f04256 in doTableScanImpl (param=0x745fba80, newgroup=0x6a0fed53) at /home/yyhuang/Projects/TDengine/src/query/src/qExecutor.c:4154
#6  0x76f042c8 in doTableScan (param=0x745fba80, newgroup=0x6a0fed53) at /home/yyhuang/Projects/TDengine/src/query/src/qExecutor.c:4203
#7  0x76f05598 in doArithmeticOperation (param=0x74510b78, newgroup=0x6a0fed53) at /home/yyhuang/Projects/TDengine/src/query/src/qExecutor.c:4802
#8  0x76f05700 in doLimit (param=0x74510bb8, newgroup=0x6a0fed53) at /home/yyhuang/Projects/TDengine/src/query/src/qExecutor.c:4856
#9  0x76f1e6f2 in qTableQuery (qinfo=0x745fb318, qId=0x6a0fede0) at /home/yyhuang/Projects/TDengine/src/query/src/queryMain.c:243
#10 0x54af796a in vnodeProcessQueryMsg (pVnode=0x6a900470, pRead=0x74513638) at /home/yyhuang/Projects/TDengine/src/vnode/src/vnodeRead.c:290
#11 0x54af7000 in vnodeProcessRead (vparam=0x6a900470, pRead=0x74513638) at /home/yyhuang/Projects/TDengine/src/vnode/src/vnodeRead.c:52
#12 0x54ac1b44 in dnodeProcessReadQueue (wparam=0x54b68808) at /home/yyhuang/Projects/TDengine/src/dnode/src/dnodeVRead.c:131
#13 0x76bd85b4 in start_thread (arg=0x0) at pthread_create.c:335
#14 0x76b79c5c in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:89 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by sangshuduo** [comment]
@BestHYY  arm32 平台移植工作还在进行中，欢迎报 issue 或者提 PR fix，谢谢
