### ISSUE TITLE
  Why TDengine installation package  would trigger assertion

### ISSUE THREAD

**Issue by Mojicode** [taosdata/TDengine#6103]
官网提供的不应该是release的包吗？为什么还会触发断言？

**Comment by yu285** [comment]
已经反馈，请您稍等

**Comment by yu285** [comment]
已经反馈，请您稍等

**Comment by sangshuduo** [comment]
@Mojicode 谢谢你的问题。在 Release 版本使用断言退出其实也是一种软件开发哲学，Pragmatic Programmer 中称为 crash early。这种方法是否适合大家可能有见仁见智的观点，有一些相关讨论的文章可以参考：https://softwareengineering.stackexchange.com/questions/266468/coerce-bad-input-or-always-crash-early 。TDengine 目前选择了使用这种方法，这样可以帮助我们尽快定位问题，尽快改进和修复。

**Comment by Mojicode** [comment]
> @Mojicode 谢谢你的问题。在 Release 版本使用断言退出其实也是一种软件开发哲学，Pragmatic Programmer 中称为 crash early。这种方法是否适合大家可能有见仁见智的观点，有一些相关讨论的文章可以参考：https://softwareengineering.stackexchange.com/questions/266468/coerce-bad-input-or-always-crash-early 。TDengine 目前选择了使用这种方法，这样可以帮助我们尽快定位问题，尽快改进和修复。

但是作为客户端的库来使用的话，不容易让调用者捕获异常，从而进行处理。反而使得调用者也停止运行了。我觉得是不是你们的server端使用这种方法合适一点，但是库的话是不是应该把错误抛给外面上层？

**Comment by sangshuduo** [comment]
@Mojicode 能否列出不应该断言的具体代码行数，我们需要仔细评估一下，谢谢

**Comment by arielyang** [comment]
This issue was closed because it has been inactive for too many days.
