### ISSUE TITLE
forced to quit after inserting two thousands records from csv files

### ISSUE THREAD

**Issue by SMD12138** [taosdata/TDengine#611]
数据导入显示：
error in taos :double free or corruption

**Comment by fangpanpan** [comment]
请问您的csv文件里每条记录是什么样的，有多少字段，以及如果有日志的话，可以将日志发给我们吗？

**Comment by SMD12138** [comment]
这是部分的日志，我的数据在别人虚拟机上是可以导入的，但是我的总是导进去两千条之后就会显示出这个，我是第一次接触TD，希望得到您的帮助和指导，您能远程一下吗?






------------------ 原始邮件 ------------------
发件人: "fangpanpan"<notifications@github.com>;
发送时间: 2019年10月12日(星期六) 中午1:22
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
抄送: "努力努力"<2099291871@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [taosdata/TDengine] 导入csv 文件，两千多条之后，就会被强制退出 (#611)




请问您的csv文件里每条记录是什么样的，有多少字段，以及如果有日志的话，可以将日志发给我们吗？

**Comment by fangpanpan** [comment]
> 这是部分的日志，我的数据在别人虚拟机上是可以导入的，但是我的总是导进去两千条之后就会显示出这个，我是第一次接触TD，希望得到您的帮助和指导，您能远程一下吗?
> […](#)

我们先看看，然后再约个时间远程一下？现在我还在远程看别的问题。

**Comment by SMD12138** [comment]
好的，您先看一下是什么问题。今天下午大概可以吗？




------------------ 原始邮件 ------------------
发件人: "fangpanpan"<notifications@github.com>;
发送时间: 2019年10月12日(星期六) 下午2:30
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
抄送: "努力努力"<2099291871@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [taosdata/TDengine] forced to quit after inserting two thousandsrecords from csv files (#611)



 
这是部分的日志，我的数据在别人虚拟机上是可以导入的，但是我的总是导进去两千条之后就会显示出这个，我是第一次接触TD，希望得到您的帮助和指导，您能远程一下吗?
 …
  
我们先看看，然后再约个时间远程一下？现在我还在远程看别的问题。

**Comment by fangpanpan** [comment]
> 好的，您先看一下是什么问题。今天下午大概可以吗？
> […](#)

好的，我现在的远程结束后就联系您。您可以先将加微信的方法发到fpang@taosdata.com.
