### ISSUE TITLE
The results are different through the Application and the Linux Taos client

### ISSUE THREAD

**Issue by Mojicode** [taosdata/TDengine#6115]
**Bug Description**
我们自己的程序通过动态库操作TDengine报错，错误提示“illegal column name”，然后造成段错误引起程序退出。
但是同样的SQL语句直接在taos里面执行正常。具体可见下面截图：
造成段错误截图：
![image](https://user-images.githubusercontent.com/30165217/118074905-8a0c2f80-b3e1-11eb-8e5f-d79abe70d099.png)
在taos里面运行正常：
![image](https://user-images.githubusercontent.com/30165217/118074927-9b553c00-b3e1-11eb-9f51-cddfbbbf433d.png)

**Expected Behavior**
程序调用库也返回正确结果。

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - TDengine Version 2.0.19.0
 - TDengine是分支develop，【commit ec74d6c0a89a891f5b7979d884713d816aedf37b】自行编译的。

**Comment by sangshuduo** [comment]
方便贴一下代码吗？我用 [https://github.com/taosdata/TDengine/blob/develop/tests/examples/c/demo.c](https://github.com/taosdata/TDengine/blob/develop/tests/examples/c/demo.c)x​​​​​​​

**Comment by sangshuduo** [comment]
方便贴一下代码吗？我用 [https://github.com/taosdata/TDengine/blob/develop/tests/examples/c/demo.c](https://github.com/taosdata/TDengine/blob/develop/tests/examples/c/demo.c) 把column 名字修改​​​​​​​为和你一样的，没有问题

**Comment by Mojicode** [comment]
> 方便贴一下代码吗？我用 https://github.com/taosdata/TDengine/blob/develop/tests/examples/c/demo.c 把column 名字修改​​​​​​​为和你一样的，没有问题

整体代码较多，我只放最后调用动态库的代码：

```
pSql = taos_query(taosSession_, command);
code = taos_errno(pSql);
```

其中taosSession_是跟数据库的连接session，command就是那条SQL语句，在执行前我会进行输出日志。
![image](https://user-images.githubusercontent.com/30165217/118085346-d745cc80-b3f4-11eb-97a7-d7d4387ad4eb.png)

重点是看那个core文件，就是上面的截图，发现是库在调用tscInvalidSQLErrMsg时，构造错误消息的时候，传的msg指针是0x0，导致格式化字符串失败，进而引起的segment fault。

**Comment by Mojicode** [comment]
> 方便贴一下代码吗？我用 https://github.com/taosdata/TDengine/blob/develop/tests/examples/c/demo.c 把column 名字修改​​​​​​​为和你一样的，没有问题

顺便请教一下，就是TSDB_CODE_TSC_ACTION_IN_PROGRESS错误码代表什么含义？这也是我在另一个issue里面的问题，就是我从官网下的包，结果在这个错误码的地方触发了断言，也导致了库的奔溃。

**Comment by hjxilinx** [comment]
TSDB_CODE_TSC_ACTION_IN_PROGRESS 的意思是当前SQL 解析中断，需要从管理节点获取查询表的元数据信息，然后重新开始解析。
建议你使用 master 版本进行测试，develop 分支变动很频繁。
可能这个问题已经不存在了。

**Comment by Mojicode** [comment]
> TSDB_CODE_TSC_ACTION_IN_PROGRESS 的意思是当前SQL 解析中断，需要从管理节点获取查询表的元数据信息，然后重新开始解析。
> 建议你使用 master 版本进行测试，develop 分支变动很频繁。
> 可能这个问题已经不存在了。

官网提供下载的安装包是master分支编的吗

**Comment by hjxilinx** [comment]
是的。你也可以使用 master 分支的编译使用。

**Comment by Mojicode** [comment]
> 2.0.x的才是 master 分支编译的。2.1.x 的是 develop 分支编译的，稳定性不如2.0.x 版本的。

好的，我先下master分支重新编译试下，谢谢

**Comment by arielyang** [comment]
This issue was closed because it has been inactive for too many days.
