### ISSUE TITLE
failed to connect to server in the query using jdbc client when there are 18 columns in the records

### ISSUE THREAD

**Issue by chenxianrui** [taosdata/TDengine#612]
**Bug Description**
##尝试
###我不断的增加字段，当发现到18个字段以上时，它会报以下错误：
![image](https://user-images.githubusercontent.com/51564660/66694663-7a4dd600-ece8-11e9-8f28-a317605f1e4b.png)
###以下是我的相关代码：
![image](https://user-images.githubusercontent.com/51564660/66694674-a0737600-ece8-11e9-9a25-0c2f5719290b.png)

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by fangpanpan** [comment]
我们看一下会不会复现这个问题。如果您有日志的话，可以将日志发给我们吗？

**Comment by chenxianrui** [comment]
已经发送了

**Comment by chenxianrui** [comment]
------------------ 原始邮件 ------------------
发件人: "fangpanpan"<notifications@github.com>;
发送时间: 2019年10月12日(星期六) 中午1:24
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
抄送: "#"<2463019831@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [taosdata/TDengine] failed to connect to server in the queryusing jdbc client when there are 18 columns in the records (#612)




我们看一下会不会复现这个问题。如果您有日志的话，可以将日志发给我们吗？

**Comment by chenxianrui** [comment]
我们用的是社区版，并不是企业版

**Comment by fangpanpan** [comment]
> 我们用的是社区版，并不是企业版

好的，明白了。不过我没有看到日志，您可以再发一次到fpang@taosdata.com吗？谢谢。

**Comment by chenxianrui** [comment]
收到了吗？我现在又发了一遍
------------------ 原始邮件 ------------------
发件人: "fangpanpan"<notifications@github.com>;
发送时间: 2019年10月12日(星期六) 下午3:35
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
抄送: "#"<2463019831@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [taosdata/TDengine] failed to connect to server in the queryusing jdbc client when there are 18 columns in the records (#612)



 
我们用的是社区版，并不是企业版
  
好的，明白了。不过我没有看到日志，您可以再发一次到fpang@taosdata.com吗？谢谢。

**Comment by fangpanpan** [comment]
> 收到了吗？我现在又发了一遍 ------------------ 原始邮件 ------------------ 发件人: "fangpanpan"<notifications@github.com>; 发送时间: 2019年10月12日(星期六) 下午3:35 收件人: "taosdata/TDengine"<TDengine@noreply.github.com>; 抄送: "#"<2463019831@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [taosdata/TDengine] failed to connect to server in the queryusing jdbc client when there are 18 columns in the records (#612) 我们用的是社区版，并不是企业版 好的，明白了。不过我没有看到日志，您可以再发一次到fpang@taosdata.com吗？谢谢。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我还是没有收到带日志的邮件。请问您是发到fpang@taosdata.com了吗？
