### ISSUE TITLE
Have you abandoned the best language in the world, PHP?

### ISSUE THREAD

**Issue by qw576483** [taosdata/TDengine#613]
PHP是世界上最好的语言啊

**Comment by robotspace** [comment]
No, I don't think so. Will you pls give a patch to implement PHP connector? If repo owners refuse to merge it, then Yes, they abandon PHP.

**Comment by codeMingo** [comment]
+1
I hope the author can support PHP

**Comment by qw576483** [comment]
> No, I don't think so. Will you pls give a patch to implement PHP connector? If repo owners refuse to merge it, then Yes, they abandon PHP.

I can't do it... i am new
