### ISSUE TITLE
Some good suggestions to TDengine

### ISSUE THREAD

**Issue by cmdares** [taosdata/TDengine#6137]
https://blog.csdn.net/weixin_39973492/article/details/113392191
在网上看到了一篇文章，写的不错。希望社区关注一下里边提及的内容，加强tdengine的能力。
感谢！

**Comment by yu285** [comment]
多谢，我们会仔细研究下

**Comment by yu285** [comment]
TDengine有隐藏关键字，tbname可以查询或者聚合，来识别不同子表。

TDengine支持乱序写入
