### ISSUE TITLE
 select query  is wrong when use  “or” 

### ISSUE THREAD

**Issue by yangweng** [taosdata/TDengine#6141]
服务器，客户端版本号：2.1.0.0
select * from stable_name where field1 = 1
有数据返回
select * from stable_name where field2 = 1
也有数据返回
select * from stable_name where field1 = 1 or field2 = 1
没有数据返回

**Comment by yu285** [comment]
![image](https://user-images.githubusercontent.com/74105241/118476114-b2788e80-b73f-11eb-91b8-4085bdf19e8e.png)

taos> select server_version()
   -> ;
 server_version() |
===================
 2.0.20.0         |
Query OK, 1 row(s) in set (0.001832s)

20没有出现问题，21理论上没有做修改，您能发一下截图吗？

**Comment by yangweng** [comment]
taos> select server_version();
 server_version() |
===================
 2.1.0.0          |
Query OK, 1 row(s) in set (0.002000s)

**Comment by yangweng** [comment]
这个就是截图，条件字段的数据类型是bigint，我查了一下别类型好像可以
![123](https://user-images.githubusercontent.com/10009305/118604972-5c135a80-b7e8-11eb-8b26-397e2857e5e0.png)

**Comment by yu285** [comment]
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/74105241/119218861-179ffb80-bb15-11eb-8ced-71786ab191d0.png">
奇怪，没有复现。你加我微信吧15652223354，方便交流

**Comment by yu285** [comment]
不好意思，是我们暂不支持跨列的or，后面会支持这个功能的。
