### ISSUE TITLE
windows 64bits Go connector  taosSql._Cfunc_taos_connect function doesn't work properly

### ISSUE THREAD

**Issue by yaofei517** [taosdata/TDengine#6142]
```
goroutine 1 [syscall]:
github.com/taosdata/driver-go/taosSql._Cfunc_taos_connect(0x13694365e20, 0x13694362030, 0x13694362070, 0x136943620b0, 0x20300010000178e, 0x0)
	_cgo_gotypes.go:160 +0x50
```

代码：
```go
func InitTDengineDB() error {
	td := global.GVA_CONFIG.TDengine
	url := fmt.Sprintf("%s:%s@/tcp(%s:%d)/test",
		td.Username, td.Password,
		td.Host, td.Port,
	)
	var err error
	TDengineDB, err := sql.Open("taosSql", url)
	if err != nil {
		global.GVA_LOG.Error("打开TDengine失败：" + err.Error())
		return err
	}
	// crash
	result, err := TDengineDB.Exec("select * from test.t0 limit 10")

	if err != nil {
		global.GVA_LOG.Error("打开TDengine失败：" + err.Error())
		return err
	}
	fmt.Printf("查询结果:%#v\n", result)
	return nil
}
```

window32位没问题，客户端taos.exe，32位和64位连接都没问题

**Comment by zitsen** [comment]
@yaofei517 能否提供下数据类型( describe table )

**Comment by yaofei517** [comment]
数据库使用的官方的docker示例项目

**Comment by yaofei517** [comment]
> @yaofei517 能否提供下数据类型( describe table )

数据库使用的是官方的docker镜像，在执行到Exec函数时会出错，应该和表没有关系，因为我尝试执行“show databases”语句都会导致崩掉。

**Comment by yaofei517** [comment]
经过测试发现在windows_x64平台下go打包后可以正常调用接口，在debug时会出错。使用go 1.5,1.6版本结果一致，使用vscode与goland的结果一致，调用其他C动态库没有出现此问题。
改写taos_connect函数，增加日志，发现在go debug时C中可以正常建立连接，在返回结果到go时出错。
分析认为是taos-go连接器与go-dlv的兼容问题

**Comment by yaofei517** [comment]
终于发现了这个蛋疼的问题，在vscode中默认的调试程序为 _debug_bin，没有 “.” 这个符号，taosGetCurrentAPPName 不成功的截取导致访问了无效的地址

![image](https://user-images.githubusercontent.com/41509375/118940415-45edd180-b983-11eb-81f7-857f9131f238.png)
