### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by qaiofeng** [taosdata/TDengine#615]
![ZV(4YTLZY8(MCGD4DYP}(8T](https://user-images.githubusercontent.com/56526888/66735373-c0e23280-ee98-11e9-93f7-f54937e047de.png)

If all the ways above couldn't help, please clearly and concisely describe what the question is.
mkdir build && cd build
cmake .. && cmake --build .

文档中这是怎么做

**Comment by plum-lihui** [comment]
tdengine在linux支持源码安装和安装包安装
一、源码安装：从github下载源码后，编译安装：在tdengine的根目录下，执行编译命令：
mkdir build && cd build
cmake .. && cmake --build
make install
然后就可以根据提示启动tdengine服务，进行操作体验；

二、安装包安装：从官网下载安装包，tdengine提供三种安装包，具体使用过程，请参考官网博客：
https://www.taosdata.com/blog/2019/08/09/tdengine多种安装包的安装和卸载/
