### ISSUE TITLE
springboot-JDBC configuration incompatible when there is another database using JPA

### ISSUE THREAD

**Issue by lingfliu** [taosdata/TDengine#6150]
application.properties
`spring.datasource.url=jdbc:TAOS://tsdb_dev.xyz:6030/tb_name
spring.datasource.username=root
spring.datasource.password=taosdata
spring.datasource.driver-class-name=com.taosdata.jdbc.TSDBDriver
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
`

build.gradle
`
plugins {
    id 'org.springframework.boot' version '2.4.5'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'java'
}

...

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.7.0'

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    compileOnly 'org.projectlombok:lombok:1.18.20'
    annotationProcessor 'org.projectlombok:lombok:1.18.20'
    testCompileOnly 'org.projectlombok:lombok:1.18.20'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.20'

    compile group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.14.1'
    compile group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.14.1'

    implementation 'com.google.code.gson:gson:2.8.6'

    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    compile group: 'com.taosdata.jdbc', name: 'taos-jdbcdriver', version: '2.0.18'
}

`

@Configuration
public class TsdbConfig {

    //TODO 6030 not compatible with JPA (autoscan cannot be disabled)
//    final String driverClassName = "com.taosdata.jdbc.TSDBDriver";
//    final String jdbcUrl = "jdbc:TAOS://tsdb_dev.xyz:6030/physiox_sig";
    final String driverClassName = "com.taosdata.jdbc.rs.RestfulDriver";
    final String jdbcUrl = "jdbc:TAOS-RS://tsdb_dev.xyz:6041/physiox_sig";

    final String username = "root";
    final String password = "taosdata";

  

    @Bean(name = "tsdbDataSource")
//    @ConfigurationProperties(prefix="spring.tsdbdatasource")
    public DataSource tsdbDataSource() {
        DataSourceBuilder builder = DataSourceBuilder.create();
        builder.driverClassName(driverClassName);
        builder.url(jdbcUrl);
        builder.username(username);
        builder.password(password);

        return builder.build();

//        DriverManagerDataSource driverManagerDataSource = new DriverManagerDataSource();
//        driverManagerDataSource.setDriverClassName("com.taosdata.jdbc.TSDBDriver");
//        driverManagerDataSource.setUrl("jdbc:TAOS://localhost:6041/physiox_sig");
//        driverManagerDataSource.setUsername("root");
//        driverManagerDataSource.setPassword("taosdata");

    }

    @Bean(name = "tsdbTemplate")
    public JdbcTemplate tsdbTemplate(DataSource tsdbDataSource) {
        return new JdbcTemplate(tsdbDataSource);
    }

}
`

**Comment by lingfliu** [comment]
问题：springboot配置JPA框架之后，Tsdb jdbc 配置6030接口后会扫描所有添加了entity注解的数据类，紧接着报错unable to resolve FQDN，换用Restful接口后能够连接上。

**Comment by yu285** [comment]
请添加微信15652223354做具体排查

**Comment by Xiejinwei93** [comment]
怎么解决的？
![image](https://user-images.githubusercontent.com/66400694/125908969-23167628-1b33-4063-9a9f-f001a2c7fb5f.png)

**Comment by lingfliu** [comment]
1. 阿里云服务器的设置问题，需要开启对应端口的 ，本地需要手动设置DNS
2. JPA扫描时执行扫描的package

**Comment by lingfliu** [comment]
1. 阿里云服务器的设置问题，需要开启对应端口的 ，本地需要手动设置DNS
2. JPA扫描时执行扫描的package

**Comment by lingfliu** [comment]
1. 阿里云服务器的设置问题，需要开启对应端口的 ，本地需要手动设置DNS
2. JPA扫描时执行扫描的package

**Comment by Xiejinwei93** [comment]
目前是使用的华为云的服务器，针对装了taos数据库的这台服务器我已经开了端口啦，能连接上去，但是不能查询
![image](https://user-images.githubusercontent.com/66400694/125917272-232d38b5-8743-4bcd-9ece-f590161cc3d1.png)

**Comment by yu285** [comment]
> 目前是使用的华为云的服务器，针对装了taos数据库的这台服务器我已经开了端口啦，能连接上去，但是不能查询
> ![image](https://user-images.githubusercontent.com/66400694/125917272-232d38b5-8743-4bcd-9ece-f590161cc3d1.png)

要打开6030-6041的TCP个UDp才可以，如果还不可以可以添加我的微信15652223354
