### ISSUE TITLE
CSV导入错误   csv import failed!   已放弃 (核心已转储)

### ISSUE THREAD

**Issue by xhero05** [taosdata/TDengine#6160]
taos> describe test;
             Field              |         Type         |   Length    |   Note   |
=================================================================================
 ts                             | TIMESTAMP            |           8 |          |
 value                          | FLOAT                |           4 |          |
 tagcode                        | NCHAR                |          30 |          |
 cn_name                        | NCHAR                |          30 |          |
Query OK, 4 row(s) in set (0.001343s

数据格式  没有表头， nchar用 '' 框起来了  uft-8编码
'2017-07-01 00:00:00',0.663,'JQZ-AT9202','可燃气体检测C101D东南'
'2017-07-01 00:00:01',0.676,'JQZ-AT9202','可燃气体检测C101D东南'
'2017-07-01 00:00:02',0.663,'JQZ-AT9202','可燃气体检测C101D东南'
'2017-07-01 00:01:00',0.663,'JQZ-AT9202','可燃气体检测C101D东南'
'2017-07-01 00:01:01',0.676,'JQZ-AT9202','可燃气体检测C101D东南'
版本：2.1.0.0 

taos> use device;
Database changed.

taos> INSERT INTO test FILE '/home/room/voice/devicem.csv'
   -> ;
taos: /home/room/download/TDengine-develop/src/client/src/tscAsync.c:290: tscAsyncResultCallback: Assertion `pSql->res.code != TSDB_CODE_SUCCESS' failed.
已放弃 (核心已转储)

**Comment by yu285** [comment]
2.0.20问题并未出现，已经建议用户升级
