### ISSUE TITLE
failed to connect to server

### ISSUE THREAD

**Issue by qaiofeng** [taosdata/TDengine#617]
这个问题怎么解决

**Comment by jtao1735** [comment]
Please use the issue template to list the steps for the error you encounter. In addition, please upload the log file in both client and server. Otherwise, it is impossible to find out the reason

**Comment by qaiofeng** [comment]
![image](https://user-images.githubusercontent.com/56526888/66884403-ad9fa600-f003-11e9-9179-2fca5e57a068.png)

**Comment by guanshengliang** [comment]
从日志上来看，是通过windows连接linux数据库，分析这类问题一般采用如下步骤
- 判定在linux本机是否可以连接，确定数据库运行正常
- 判定windows和linux的网络是否通畅，可采取ping命令
- 判定是否存在windows或者linux的防火墙的问题，参照`https://www.taosdata.com/cn/documentation/administrator/#服务端配置 ` 中的端口
- 打开客户端和服务端的日志，即增加一行`debugFlag 135`，检查网络消息流，如果消息没有返回，那么是网络问题，否则会有错误码

**Comment by guanshengliang** [comment]
No feedback for more than 1 month, so we closed this issue
