### ISSUE TITLE
can't find ...

### ISSUE THREAD

**Issue by qaiofeng** [taosdata/TDengine#618]
你们的图标

**Comment by qaiofeng** [comment]
![image](https://user-images.githubusercontent.com/56526888/66811361-86919780-ef63-11e9-9548-bcc2f65f1731.png)

**Comment by fangpanpan** [comment]
请问您可以将问题描述得更详细些吗？这样也方便我们帮您解决问题。

**Comment by guanshengliang** [comment]
您需要按照`https://www.taosdata.com/blog/2019/07/10/使用tdengine快速搭建运维监测系统/`  安装grafana插件

**Comment by guanshengliang** [comment]
目前没有与grafana官方建立合作关系，因此需要手动配置grafana

**Comment by guanshengliang** [comment]
No feedback for more than 1 month, so we closed this issue
