### ISSUE TITLE
taosdump 导出报错

### ISSUE THREAD

**Issue by cmkcmk181** [taosdata/TDengine#6183]
TDEngine Version: 2.1.0.0
Ubuntu 18.04

执行导出命令：
 sudo ./taosdump -o /home/data-2021-05-21 -u root -p taosdata -A -N 200 -T 4

报错如下：
====== arguments config ======
host: (null)
user: root
password: taosdata
port: 0
cversion:
mysqlFlag: 0
outpath: /home/data-2021-05-21
inpath:
resultFile: ./dump_result.txt
encode: (null)
all_databases: 1
databases: 0
schemaonly: 0
with_property: 0
start_time: 0
end_time: 9223372036854775807
data_batch: 200
max_sql_len: 65480
table_batch: 500
thread_num: 4
allow_sys: 0
abort: 0
isDumpIn: 0
arg_list_len: 2
debug_print: 0
arg_list[0]: sudo
arg_list[1]: ./taosdump
==============================
failed to open file /home/data-2021-05-21/dbs.sql

**Comment by sangshuduo** [comment]
是不是读写权限问题？

**Comment by cmkcmk181** [comment]
不是权限的问题，用taosdump --all-databases这个是可以的，但加参数后就报错了

**Comment by cmkcmk181** [comment]
可以了，谢谢，是权限的问题
