### ISSUE TITLE
博客【使用TDengine快速搭建车联网平台】提供的样例代码执行时会报错

### ISSUE THREAD

**Issue by malinco** [taosdata/TDengine#62]
报错详情如下：
./test: error while loading shared libraries: libtaos.so.1: cannot open shared object file: No such file or directory

**Comment by coder-chriswang** [comment]
我这可以正常运行，请问你确定完成安装测试了吗？
![image](https://user-images.githubusercontent.com/40193732/61270518-84893280-a7d4-11e9-89fe-8404a34ebb7a.png)

**Comment by malinco** [comment]
> 我这可以正常运行，请问你确定完成安装测试了吗？
> ![image](https://user-images.githubusercontent.com/40193732/61270518-84893280-a7d4-11e9-89fe-8404a34ebb7a.png)

安装是成功的，如下图：
![image](https://user-images.githubusercontent.com/7393081/61275252-26624c80-a7e0-11e9-9fe9-f4d70b78d230.png)

但是运行test脚本仍然失败，如下图：
![image](https://user-images.githubusercontent.com/7393081/61275303-43971b00-a7e0-11e9-98ad-926430cba1d0.png)

**Comment by malinco** [comment]
备注一下：
操作系统： ubutnu 14.04 server 版

**Comment by coder-chriswang** [comment]
@malinco 我这执行脚本是可以的（我这边采用的CentOS 7），你看一下，再排除环境版本问题
![image](https://user-images.githubusercontent.com/40193732/61275752-32024300-a7e1-11e9-908d-d88d5fd92cb6.png)

**Comment by malinco** [comment]
@coder-chriswang 我又试了ubuntu 16.04还是不行，只能装centos试试了。

**Comment by zhangchi0923** [comment]
请问libtaos.so.1的问题解决了吗，我是CentOS7，可以在/usr/lib/下找到libtaos.so文件，但是全局都没有libtaos.so.1




------------------ 原始邮件 ------------------
发件人: "malinco"<notifications@github.com>;
发送时间: 2019年7月16日(星期二) 下午3:42
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [taosdata/TDengine] 博客【使用TDengine快速搭建车联网平台】提供的样例代码执行时会报错 (#62)



 
我这可以正常运行，请问你确定完成安装测试了吗？
 
  
安装是成功的，如下图：
 
 
但是运行test脚本仍然失败，如下图：

**Comment by malinco** [comment]
@zhangchi0923 @coder-chriswang 没有解决，我新装了CentOS7系统，还是有同样的问题。

**Comment by zhangchi0923** [comment]
我也是，我试了以下几种方法：
1.ln -s /usr/local/taos/driver/libtaos.so ./libtaos.so (之前的issues里有人提到过)
2.输出环境变量
3.修改ld.so.conf.d文件
都不管用，你可以参考下==

**Comment by malinco** [comment]
@coder-chriswang 为什么你的版本是1.6.1.0，而我在官网下的是1.6.0.0？

**Comment by zhangchi0923** [comment]
> @coder-chriswang 为什么你的版本是1.6.1.0，而我在官网下的是1.6.0.0？

昨天更新的

**Comment by coder-chriswang** [comment]
@malinco 昨天编译安装的，还算顺利。没有遇到您说的相关问题。
步骤我总结了一下，供参考：
1、环境安装：
选择一台有网络权限的CentOS 7的虚拟机(JDK已经下载配置安装)：
(1)安装gcc
(2)安装Cmake2.8
(3)安装git，执行命令yum install git
(4)安装maven,在/etc/profile中配置maven环境变量
export MAVEN_HOME=/usr/local/apache-maven-3.3.9
export PATH=$PATH:$JAVA_HOME/bin:$MAVEN_HOME/bin:$HADOOP_HOME/bin
export CLASSPATH=.:$JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib/dt.jar:$CLASSPATH

2、下载源码，进行编译安装：
cd /opt 目录，执行git clone， 将源码download
cd /opt/TDengine目录，执行以下脚本：
mkdir build && cd build
cmake .. && cmake --build .（不要遗漏最后的英文小点.）
make install
至此，编译安装完毕

3、服务相关命令：
查询服务状态：sudo systemctl status taosd
启动服务进程：sudo systemctl start taosd
停止服务进程：sudo systemctl stop taosd
重启服务进程：sudo systemctl restart taosd
4、创建测试数据库、表：
启动taosd，执行启动该服务进程，然后查询进程状态；
running之后，执行taos,进入客户端模式；
创建数据库：create database car;
使用数据库：use car；
创建表：create table trip (ts timestamp, speed int);
插入数据：insert into trip values ('2019-07-16 00:00:00', 1);
查询所有数据：select * from trip;

**Comment by zhangchi0923** [comment]
![image](https://user-images.githubusercontent.com/27287620/61423761-963d1800-a943-11e9-8b75-7e1a5dcb1c7e.png)
make时博客中给出的test.c会报这个错误
test.c中49、50行的‘｝’是否重复？

**Comment by malinco** [comment]
@coder-chriswang @zhangchi0923 问题已解决，感觉是版本问题，deb包，rpm包的版本是1.6.0.0，而tar包是1.6.1.0，改用tar包重新安装后正常。

**Comment by songtianyi** [comment]
> @coder-chriswang @zhangchi0923 问题已解决，感觉是版本问题，deb包，rpm包的版本是1.6.0.0，而tar包是1.6.1.0，改用tar包重新安装后正常。

tdengine-1.6.3.0-3.x86_64
一样有问题，我是用rust的example 报这个错误
