### ISSUE TITLE
Hope Continuous Query table  could be same as  super table

### ISSUE THREAD

**Issue by Fmyao** [taosdata/TDengine#6209]
**Is your feature request related to a problem? Please describe.**
我用连续查询语句group by 标签列，但是这个标签列在连接查询建的结果表中只是一个普通列

**Describe your desired behavior**
连续查询语句：
create table test052401 as select point_name,avg(pv) from service_values where ts>now-365d and ts<
now-120d interval(1m) sliding(30s) group by point_name;
结果表的结构：
![image](https://user-images.githubusercontent.com/50644859/119289226-c4e15380-bc7c-11eb-9803-718c02feb0b4.png)

**Describe your solutions/suggestions if you've any**
希望连接查询建的结果表中支持标签列，也就是支持建子表。

**Comment by yu285** [comment]
we will discuss on that , thanks for your advice .

**Comment by yu285** [comment]
可以尝试下最新版本的TDengine 2.4.0.18，应该已经优化了这个问题
具体语法：

CREATE TABLE [IF NOT EXISTS]  table_name  

                  TO  supertable_name   [ SPLIT column_name ]

                  AS SELECT column_name1, column_name2, ...   FROM  supertable_name WHERE ... GROUP BY tbname ;
