### ISSUE TITLE
Restful Connector  how to close connection ?

### ISSUE THREAD

**Issue by ZodiacWind** [taosdata/TDengine#6212]
使用Restful API进行数据库操作的话，在操作结束后，是否需要关闭连接？（以避免内存泄露？）如果需要的话，应当如何操作？

谢谢！

**Comment by yu285** [comment]
这个应该是不需要的。

如果是短连接就自动释放了，长连接的话取决于你们的业务场景，一般也不会开太多连接的吧。

**Comment by ZodiacWind** [comment]
是的，我们会有一些长链接（数量不会很多）。非常感谢！
