### ISSUE TITLE
create table xx as select ... from xx where ts>now-100d interval(1m) group by ... 

### ISSUE THREAD

**Issue by Fmyao** [taosdata/TDengine#6214]
**Bug Description**
TD集群版本：2.0.14.0
create table 连接查询语句使用group by 查询但是并没有达到预期的分组效果

**To Reproduce**
meters1表结构：
![image](https://user-images.githubusercontent.com/50644859/119305282-1e587b00-bc9b-11eb-9341-92394033618c.png)
meters1表数据：
![image](https://user-images.githubusercontent.com/50644859/119305861-e271e580-bc9b-11eb-8a60-be64301275d8.png)
连接查询语句： create table test0524meter as select point,sum(pv) from meters1 where ts>now-100d interval(1m) gro
up by point;
语句执行完成后，
test0524meter表结构以及表数据：
![image](https://user-images.githubusercontent.com/50644859/119305384-41832a80-bc9b-11eb-8cc1-77fbbdca7d55.png)
![image](https://user-images.githubusercontent.com/50644859/119305944-00d7e100-bc9c-11eb-9ba6-8120b2dea0bf.png)
向meters1表新增数据：
insert into t_27777 using meters1 tags("27777//MF00") values("2021-05-24 14:05:47",10) ;
insert into t_27777_mf00 using meters1 tags("27777_MF00") values("2021-05-24 14:05:47",10) ;
meters1表数据：
![image](https://user-images.githubusercontent.com/50644859/119306543-e6523780-bc9c-11eb-9720-711412f7676d.png)
test0524meter结果表数据：
![image](https://user-images.githubusercontent.com/50644859/119306570-f1a56300-bc9c-11eb-9768-dc06e4971340.png)

**Expected Behavior**
预期是在test0524meter表中ts为“2021-05-24 14:05:00.000”的记录有两条，一条如上图test0524meter结果表所示point为“27777/MF00”，一条point为“27777_MF00”，并且这两条数据的sum计算结果（sum_pv_）都为10，但实际结果只有一条point为“27777/MF00”的。

**Environment (please complete the following information):**
 - OS: CentOS 7
 - Memory, CPU, current Disk Space
 - TDengine Version 2.0.14.0

**Comment by yu285** [comment]
请测试下最新版本，应该不会有这个问题了

**Comment by yu285** [comment]
https://docs.taosdata.com/get-started/
