### ISSUE TITLE
Build go application with tdengine go-connector for linux+amd64 raise errors.

### ISSUE THREAD

**Issue by blair-long** [taosdata/TDengine#6227]
**Bug Description**
尝试在windows下build能在linux+amd64架构下的应用程序，正常build windows exe是正常编译，且正常运行的。但是build linux的包go-connector相关的代码就会报错。

**To Reproduce**
Steps to reproduce the behavior see below:
![image](https://user-images.githubusercontent.com/35720431/119486591-006a4380-bd8b-11eb-93ae-f8e0d016750a.png)

**Environment (please complete the following information):**
 - OS: Windows 10家庭中文版  20H2
 - Go Version: 1.15.6

**Comment by zitsen** [comment]
Currently, TDengine's Go connector uses cgo (calling libtaos or taos.dll) to connect with taosd server, and CGO is not supported for go build cross-compiling on windows to linux. https://github.com/golang/go/issues/40129 has a solution, you may check it.

CGO当前不支持在Windows上交叉编译linux。如果您感兴趣，可以看下 https://github.com/golang/go/issues/40129

The issue will be closed.

**Comment by blair-long** [comment]
谢谢！
