### ISSUE TITLE
Suggest to provide a non-sql way to insert data 

### ISSUE THREAD

**Issue by Cutie-Sakura** [taosdata/TDengine#6232]
我是一个物联网部门的开发者, 使用TDengine的过程中觉得总是在拼接字符串sql, 虽然现代计算机运行速度很快,但是基于物联网数据的特性,几亿几白亿的微小性能损耗累加起来也是一种浪费.
    从边缘端采集的数据一般都是自定义协议的tcp,使用的byte传输数据, ,平台接受,将byte安装大小端等规则解析成基础数据类型, 存储的时候又将基础数据类型转化为字符串拼接起来. 然后调用TDengine提供的驱动包 个人猜测TDengine 在做将字符串转化为基础数据类型,进行存储和传输.
   建议提供一个非sql的数据插入方式, 节约 基础数据类型->> 字符串 -->> 基础数据类型 这部过程的运算消耗.
 一个浮点数3.1415926  ,占4byte, 转化成"3.1415926" 占9byte,浮点数精度越高,位数越多,转换后占用的内存越大,总觉得不划算.

**Comment by sangshuduo** [comment]
参考： 参数绑定API

[https://www.taosdata.com/cn/documentation/connector#c-cpp](https://www.taosdata.com/cn/documentation/connector#c-cpp)
