### ISSUE TITLE
query bug？

### ISSUE THREAD

**Issue by peterchenhdu** [taosdata/TDengine#6239]
版本：2.0.16.0
这个查询为什么不对？
问题1：插入数据end_time为null时，自动变为1970-01-01 08:00:00.000，这样设计不太合适吧，为什么不直接为null
问题2：查询end_time为1970-01-01 08:00:00.000的数据，查询不出来，且有问题，如图
![image](https://user-images.githubusercontent.com/12928352/119620884-12ee8680-be38-11eb-8340-5caa4b700b1b.png)

**Comment by peterchenhdu** [comment]
![image](https://user-images.githubusercontent.com/12928352/119627384-b773c700-be3e-11eb-83c9-429fbba096a6.png)

**Comment by yu285** [comment]
2.0.16版本问题较多，基本已经修复，请升级到2.0.20再试试呢

**Comment by yu285** [comment]
请问有升级吗？问题还存在吗
