### ISSUE TITLE
how to connect to TDengine server using python connector on Windows

### ISSUE THREAD

**Issue by qaiofeng** [taosdata/TDengine#624]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the circumstance is and what the associated problem is. Ex. I'm using TDengine for this use case: [...]. But I'm always frustrated when [...]

**Describe your desired behavior**
A clear and concise description of what you want to happen. Ex. I want TDengine to be able to do [...] when I try to do [...] with it.

**Describe your solutions/suggestions if you've any**
A clear and concise description of any solutions/suggestions to this problem or features you've considered.

**Additional context**

**Comment by fangpanpan** [comment]
(1) 您可以参考这篇文章[https://www.taosdata.com/blog/2019/07/26/如何编译tdengine的windows客户端/](url)安装Windows客户端
（2） 然后您参考python connector 的安装[https://www.taosdata.com/cn/documentation/connector/#Python-Connector](url)，您需要pip install windows 目录下的python2/python3
（3） 如需在windows下使用C#、Java、Python等语言，将C:\TDengine\driver\taos.dll拷贝到C:\windows\system32目录下即可。所有TDengine的连接器，均需依赖taos.dll。
（4） 然后您可以参考代码[https://github.com/taosdata/TDengine/tree/master/tests/examples/python](url)使用python connnector了

**Comment by qaiofeng** [comment]
我i现在的问题是 在windows连不上 服务端 # internalIp            服务器ip
# localIp               windows  ip

**Comment by guanshengliang** [comment]
please refer to #625
