### ISSUE TITLE
C/C++ Connector中解析taos_fetch_row返回的一个元组(一行)的数据有bug

### ISSUE THREAD

**Issue by libulb** [taosdata/TDengine#6240]
taos中的表数据如下：
![image](https://user-images.githubusercontent.com/48210187/119621569-dd966880-be38-11eb-861a-7e9479fdfb0b.png)
使用taos进行分组查询：
![image](https://user-images.githubusercontent.com/48210187/119621671-fb63cd80-be38-11eb-9404-31cb7238e497.png)
c编程进行同样的查询，结果如下：
![image](https://user-images.githubusercontent.com/48210187/119621856-2fd78980-be39-11eb-9f60-51f8ee18d657.png)
发现，由于IP所占用的字节数不同，占用字节数少的数据会使用上面的数据进行填充。

**Comment by yu285** [comment]
请问这是什么版本

**Comment by jiaoqiyuan** [comment]
@yu285 我在 `ver-2.1.1.0` 版本测试复现了这个问题。

**Comment by wwbgo** [comment]
同样遇到了这个问题，2.1.1 c库客户端，字符串类型读取字节会被覆盖

**Comment by jiaoqiyuan** [comment]
我看了一下代码，应该时使用 `taos_fetch_row` 时，没有给第一个参数赋初始值造成的，比如：

将

```c
char str[256];
taos_print_row(temp, row, fields, num_fields);
```

改为：

```c
char str[256] = {0};
taos_print_row(temp, row, fields, num_fields);
```

就可以正确查询数据了。测试了一下，while 中声明数组时，如果不初始化，下次使用的还是上次保留的值，猜测：一个循环结束后数组的内存空间没有被回收而是直接利用，对应内存中的数据也保留，影响下一次使用。

所以，声明一个数组的同时给其赋初始值是个好习惯。

**Comment by libulb** [comment]
> 请问这是什么版本

2.0.16

**Comment by libulb** [comment]
> 我看了一下代码，应该时使用 `taos_fetch_row` 时，没有给第一个参数赋初始值造成的，比如：
> 
> 将
> 
> ```c
> char str[256];
> taos_print_row(temp, row, fields, num_fields);
> ```
> 
> 改为：
> 
> ```c
> char str[256] = {0};
> taos_print_row(temp, row, fields, num_fields);
> ```
> 
> 就可以正确查询数据了。测试了一下，while 中声明数组时，如果不初始化，下次使用的还是上次保留的值，猜测：一个循环结束后数组的内存空间没有被回收而是直接利用，对应内存中的数据也保留，影响下一次使用。
> 
> 所以，声明一个数组的同时给其赋初始值是个好习惯。

对的。需要对上次使用过的内存进行清理。谢谢！

**Comment by libulb** [comment]
![Uploading image.png…]()

**Comment by wwbgo** [comment]
> 同样遇到了这个问题，2.1.1 c库客户端，字符串类型读取字节会被覆盖
> 经测试发现,在一个stable下面有多个子表的情况下,时间交错,按时间排序,string长度不等 就会出现短的字节数组会被上一个长的字节填充

看了一下午的源码,我的解决方案是使用taos_fetch_lengths方法获取当前行的字节长度,根据长度读取字符串

**Comment by jiaoqiyuan** [comment]
> > 同样遇到了这个问题，2.1.1 c库客户端，字符串类型读取字节会被覆盖
> > 经测试发现,在一个stable下面有多个子表的情况下,时间交错,按时间排序,string长度不等 就会出现短的字节数组会被上一个长的字节填充
> 
> 看了一下午的源码,我的解决方案是使用taos_fetch_lengths方法获取当前行的字节长度,根据长度读取字符串

这种方法肯定也可以，先获取数据长度，再读取指定长度。读取数据前再 fetch length 一下就怕数据量大时影响速度，毕竟多了一个 fetch 操作，我还没看这部分的源码，不太确定哈。
