### ISSUE TITLE
Result of rate function is infinite 

### ISSUE THREAD

**Issue by jiangzeyin** [taosdata/TDengine#6241]
**Bug Description**
基本正常的数据 使用 rate 出现无穷大的情况

**To Reproduce**

1. ` SELECT * FROM mqtt.t_time_log_47835422257d81d7f1faa39952a7285d3fc28ac2 where milli_second BETWEEN 1622016397000 AND 1622016397999 ;`

![image](https://user-images.githubusercontent.com/16408873/119628106-60babd00-be3f-11eb-9d8a-4251e4659f20.png)

2. `SELECT rate(v) as diff FROM mqtt.t_time_log_47835422257d81d7f1faa39952a7285d3fc28ac2 where milli_second BETWEEN 1622016397000 AND 1622016397999 interval(1m) sliding(1s);`

![image](https://user-images.githubusercontent.com/16408873/119628229-7def8b80-be3f-11eb-9878-db4887025229.png)

3. 
![image](https://user-images.githubusercontent.com/16408873/119628272-8647c680-be3f-11eb-98d8-a0c66833754d.png)

**Expected Behavior**
 正常情况 rate 结果应该是1

 TDengine Version 2.1.1.0

**Comment by yu285** [comment]
收到您的反馈，我们会处理

**Comment by yu285** [comment]
https://docs.taosdata.com/get-started/

该问题应该修复了，请测试新版本是否有这个问题。
