### ISSUE TITLE
cann't connect to TDengine server on Windows client

### ISSUE THREAD

**Issue by qaiofeng** [taosdata/TDengine#625]
47.103.20.221
--

**Comment by guanshengliang** [comment]
通过windows连接linux数据库，分析这类问题一般采用如下步骤

- 判定在linux本机是否可以连接，确定数据库运行正常
- 判定windows和linux的网络是否通畅，可采取ping命令
- 判定是否存在windows或者linux的防火墙的问题，参照`https://www.taosdata.com/cn/documentation/administrator/#服务端配置` 中的端口
- 打开客户端和服务端的日志，即增加一行debugFlag 135，检查网络消息流，如果消息没有返回，那么是网络问题，否则会有错误码

**Comment by qaiofeng** [comment]
![image](https://user-images.githubusercontent.com/56526888/66895115-991fd580-f024-11e9-83c1-e4f31198c513.png)

**Comment by guanshengliang** [comment]
![image](https://user-images.githubusercontent.com/28882257/66895459-74782d80-f025-11e9-8067-96b12831cd7c.png)

从这张图看，是防火墙的问题。
如果是云主机，还需要修改安全组。

**Comment by qaiofeng** [comment]
6030 6035 6020 我都加了安全组

**Comment by qaiofeng** [comment]
![image](https://user-images.githubusercontent.com/56526888/66895951-80182400-f026-11e9-979d-fcb3f68f8bb1.png)
![image](https://user-images.githubusercontent.com/56526888/66895967-8d351300-f026-11e9-84a7-6aa5d879864f.png)

**Comment by qaiofeng** [comment]
![image](https://user-images.githubusercontent.com/56526888/66896009-a50c9700-f026-11e9-9b7b-0a1464cdb791.png)
![image](https://user-images.githubusercontent.com/56526888/66896027-b0f85900-f026-11e9-86c2-e1910f9a6c17.png)

**Comment by qaiofeng** [comment]
![image](https://user-images.githubusercontent.com/56526888/66897486-ad1a0600-f029-11e9-80a6-040a6e9527ed.png)

**Comment by guanshengliang** [comment]
全放开，如果能连上，说明确实是网络问题
这样，再继续研究该开发那个端口的问题

**Comment by guanshengliang** [comment]
47.103.20.221 是云服务器的外网IP，云服务还有私有IP
从windows上肯定连接不上私有IP

**Comment by guanshengliang** [comment]
你已经实验过，把所有端口都放开，但还是连接不上吗

**Comment by qaiofeng** [comment]
通过telnet指令去检测服务的端口，完全没问题，但是去连接数据库，显示连接失败

**Comment by guanshengliang** [comment]
并不是说你开发端口的操作有问题，而是说的开发的端口还不够，因而让你把所有端口都放开。

上面让你按照
`https://www.taosdata.com/cn/documentation/administrator/#服务端配置`
开放端口，估计你没仔细看，我把关键的部分贴过来
- mgmtShellPort：管理节点与客户端通信使用的TCP/UDP端口号（默认值是6030）。此端口号在内向后连续的5个端口都会被UDP通信占用，即UDP占用[6030-6034]，同时TCP通信也会使用端口[6030]。
- vnodeShellPort：数据节点与客户端通信使用的TCP/UDP端口号（默认值是6035）。此端口号在内向后连续的5个端口都会被UDP通信占用，即UDP占用[6035-6039]，同时TCP通信也会使用端口[6035]

再精简些
TCP 6030
UDP 6030-6034
TCP 6035
UDP 6035-6039

**Comment by guanshengliang** [comment]
把端口全部临时打开，验证能不能连上，之后再关闭，应该对你很容易
为什么就不按照我说的来呢

**Comment by qaiofeng** [comment]
ok了，感谢
