### ISSUE TITLE
How to acquire the tag name of some certain table?

### ISSUE THREAD

**Issue by zliangliang1024** [taosdata/TDengine#6253]
当前有一个超级表，下设若干子表，当我查询某一个表时，如何知道他的TAG是什么

**Comment by yu285** [comment]
select 标签名 from readings where tbname like '表名字';

**Comment by zliangliang1024** [comment]
1. 不指定数据库：DB error: Database not specified or available (0.000272s)
2. 指定数据库：DB error: Table does not exist (0.001023s)

**Comment by zliangliang1024** [comment]
步骤
1. taosdemo
2. taos -u root -p
3. use test；
4. select t1 from readings where tbname like 't5114';

**Comment by zliangliang1024** [comment]
use <database>;
select tbname ,标签名 from <超级表> where tbname like '表名字';
