### ISSUE TITLE
RESTful login with any password

### ISSUE THREAD

**Issue by 1406990759** [taosdata/TDengine#626]
**Bug Description**
A B 两个客户端（通过RESTful连接）A 密码错误 B 密码正确  只要B连接过 A不管什么密码都能连接成功

**To Reproduce**
1. 重启TDengine
2. 通过A（随机密码） 客户端连接（authentication failure）
3. 通过B（正确密码） 客户端连接（成功查询到数据）
4. 通过A（随机密码） 客户端连接（成功查询到数据）

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by guanshengliang** [comment]
确实是一个BUG，近期会解决
非常感谢

**Comment by guanshengliang** [comment]
fixed in v1.6.4.3
