### ISSUE TITLE
TDengine memory consumption  increase continuously 

### ISSUE THREAD

**Issue by moziie** [taosdata/TDengine#6267]
环境:centos7，8核16G，三节点集群，60万子表，taos版本2.0.17
问题：初始启动taos占用内存4%~5%，随着数据插入使用，taos占用内存之间增多一直到占用内存32%左右，占用内存大会影响其他程序运行，重启taos后内存占用就会降下来
此时日志如下
05/28 09:10:15.829889 00013778 WAL vgId:19, file:/home/fanwu/lib/taos/vnode/vnode19/wal/wal18, it is removed
05/28 09:10:15.832292 00013778 VND vgId:19, successed to write /home/fanwu/lib/taos/vnode/vnode19/version.json, fver:7878740
05/28 09:10:16.013322 00013778 TDB vgId:22 start to commit! keyFirst 1622160901788 keyLast 1622164202878 numOfRows 1379668 meta rows: 0
05/28 09:10:17.879508 00013778 TDB vgId:22 commit over, succeed
05/28 09:10:17.906027 00013778 WAL vgId:22, file:/home/fanwu/lib/taos/vnode/vnode22/wal/wal18, it is removed
05/28 09:10:17.908284 00013778 VND vgId:22, successed to write /home/fanwu/lib/taos/vnode/vnode22/version.json, fver:7878740
05/28 09:10:18.126599 00013778 TDB vgId:25 start to commit! keyFirst 1622160901816 keyLast 1622164202913 numOfRows 1379668 meta rows: 0
05/28 09:10:20.061223 00013778 TDB vgId:25 commit over, succeed
感觉已经开始进行落盘写入操作，但是内存占用不会变，随后我调整了blocks参数由6调整到3并重启后，再次进行测试，同样也是内存占用一直增高到32%左右，请问这是时序库机制就是如此还是我配置参数有问题？

**Comment by yu285** [comment]
您说的taos进程值得应该是taosd进程？

**Comment by moziie** [comment]
> 您说的taos进程值得应该是taosd进程？

是的taosd进程
![image](https://user-images.githubusercontent.com/70946068/120739197-b79d5200-c523-11eb-8e7e-c91be72d9adc.png)

**Comment by yu285** [comment]
请添加微信15652223354，方便排查，问题解决后，我们会把解决方案写到github上。

**Comment by arielyang** [comment]
This issue was closed because it has been inactive for too many days.
