### ISSUE TITLE
How to check the disk usage of a sub-table ？

### ISSUE THREAD

**Issue by zliangliang1024** [taosdata/TDengine#6269]
想查看一下某个子表或者某个普通表的磁盘占用，该如何查看，目录`/var/lib/taos/vnode/ `似乎查看不到具体某个表的磁盘占用

**Comment by yu285** [comment]
是的，只能查看整个数据库的占用。

除非你只有一个子表，那么vnode里面的就是你的这个子表的大小

**Comment by zliangliang1024** [comment]
好的，了解，谢谢
