### ISSUE TITLE
Data lost during large amount of rows insertion

### ISSUE THREAD

**Issue by zliangliang1024** [taosdata/TDengine#6272]
一次插入1万条，分100次插入，共100万数据，时间密度为 1毫秒 1a，
int affectedRows = stmt.executeUpdate("insert into " + tableName + " values " + sql + ";");
affectedRows 返回100次10000，即返回插入成功了
最后查询总数只有6万多条，

是大批量插入有Bug吗，还是时间密度太过于紧密，如果过于紧密这个边界值是多少，1S中大概支持多少的并发量数据插入

**Comment by topcloud-xx** [comment]
timestamp must be different，check your code

**Comment by topcloud-xx** [comment]
timestamp must be different，check your code

**Comment by yu285** [comment]
子表时间戳不能相同，请确认下

**Comment by zliangliang1024** [comment]
好的，我确认下，谢谢
