### ISSUE TITLE
Multi-columns mode is a kind of resource wasting?

### ISSUE THREAD

**Issue by jamesZHANG500** [taosdata/TDengine#6293]
请教一下 如果设计超级表结构有很多列，但是每次插入只插入部分列，比如设计表结构有几十列

但是相同时间戳单次插入可能只有三四列，其他列默认为NULL ,这样对性能和存储是不是影响很大，期待回复

谢谢！

**Comment by hjxilinx** [comment]
存储上由于压缩的存在，null 对于磁盘占用基本可以忽略。
对于查询来说，TDengine 有内置的查询过滤手段可以尽可能的降低 NULL 带来的 overhead。
总的来说，有影响，但是不大。
