### ISSUE TITLE
insert into语句失败

### ISSUE THREAD

**Issue by effun** [taosdata/TDengine#63]
第一次使用，碰到个奇怪的问题，表结构如下
create table t1(ts timestamp, lng int, lat int);
插入数据语句如下
insert into t1 values ('2019-7-16 11:16', 12, 23);
这条语句报错
TSDB error: invalid SQL: near "019-7-16 11:16', 12, 23);" syntax error
看看貌似语句没有错，百思不得其解，望指点。

操作系统 CentOS 7.6，运行在Hyper-V上。

**Comment by Astone-Chou** [comment]
看起来是 11:16 后面缺了秒

**Comment by effun** [comment]
果然是缺了秒，问题已经解决。
