### ISSUE TITLE
error when monitor initialize monitor service 

### ISSUE THREAD

**Issue by Allenscript** [taosdata/TDengine#630]
**Bug Description**
error when monitor initialize monitor service 
error code : -28
create database if not exists log ....

**To Reproduce**
1. root@localhost ~#:taosd

it seem when monitorSysteminit , can't create database log

**Comment by guanshengliang** [comment]
You can stop the service, delete the log folder `/var/lib/taos`, add a line of `debugFlag 135` to the configuration file `/etc/taos/taos.cfg`, and then paste the log.
This makes it easy for me to find the problem

**Comment by Allenscript** [comment]
Trace like this.
user:monitor login from 127.0.0.1, code:0
10/19 00:05:08.379613 75a5f470 ERROR MON monitor:0x6a400470, sql failed, code:-45, create database if not exists log replica 1 days 10 keep 30 rows 1024 cache 2048 ablocks 2 tblocks 32 tables 32 precision 'us'
10/19 00:05:11.567024 748ff470 MON starting to initialize monitor service ..
10/19 00:05:11.569131 76260470 ERROR MON monitor:0x6a400470, sql failed, code:-45, create database if not exists log replica 1 days 10 keep 30 rows 1024 cache 2048 ablocks 2 tblocks 32 tables 32 precision 'us'

**Comment by Allenscript** [comment]
new trace
10/19 18:08:16.299058 75a98470 ERROR MON monitor:0x6a400470, save system info failed, code:-105 insert into log.dn_192_168_31_170 values(1995194868, 522791.750000, 522791.843750, 4, 24.929688, 787.601562, 875, 7.546799, 15, 2.598438, 2.684570, 73.620117, 0, 0, 1)
10/19 18:08:46.498857 71529470 ERROR DND vid:0 sid:2 id:0.log.dn_192_168_31_170, invalid timestamp to insert, numOfPoints:1 firstKey: 1912306 lastKey: 1955591280 
10/19 18:08:46.499196 75a98470 ERROR MON monitor:0x6a400470, save system info failed, code:-105 insert into log.dn_192_168_31_170 values(1955591280, 27452.832031, 27452.931641, 4, 25.238281, 788.375000, 875, 7.638496, 15, 13.545053, 32.582031, 86.935547, 0, 0, 1)

**Comment by guanshengliang** [comment]
You can add my wechat `geiseil`
So that I can locate this bug

**Comment by guanshengliang** [comment]
这可能是一个BUG，我还在排查
初步诊断是获取监控程序本身获取时间戳时，时间戳取值不对
本应是微秒的时间戳，但现在是秒的时间戳

**Comment by guanshengliang** [comment]
this bug is already fixed, you can download and try again
