### ISSUE TITLE
Can multiple columns with the timestamp data type exist in one table?

### ISSUE THREAD

**Issue by Magic757086354** [taosdata/TDengine#631]
请问，
数据表字段可以有两个时间戳吗？
除了第一列必须的时间戳，想再添加一个时间戳字段用于存储传感器采集数据的时间，而不是存储数据的时间。
但是发现无论是表字段定义binary[]类型，传入String类型的时间戳（如“”yyyy-MM-dd HH:mm:ss.SSS“”）。
还是表字段定义timestamp类型，传入Timestamp类型的时间戳（如：yyyy-MM-dd HH:mm:ss.SSS）。
都失败，语法显示没错，编译运行就invalid SQ。
请问是不支持两个时间戳吗？
很急，感谢！

**Comment by fangpanpan** [comment]
普通列的字段也可以是timestamp 类型。请问您可以将sql 语句在编译运行时打印出来，然后发给我们吗？

**Comment by Magic757086354** [comment]
`class PushCallback{
Timestamp ts = new Timestamp(format.parse(r[2]).getTime());
TDB.doExecuteInsertWD("now", 0, MainNum, AuxNum , ts, r[i+1]);}`

`class TDB{
sql = "create table if not exists " + metricsName[0] + " (SubTime timestamp,MainNum int,AuxNum int,PubTime timestamp, windirection binary(20)) tags(Main int,Aux int)";
public static void doExecuteInsertWD(String time,int table,int MainNum,int AuxNum,Timestamp PubTime,String v1){} }`

![image](https://user-images.githubusercontent.com/22852166/67075189-4299cf00-f1bd-11e9-9040-743f41a740ce.png)
@fangpanpan

**Comment by fangpanpan** [comment]
> `class PushCallback{ Timestamp ts = new Timestamp(format.parse(r[2]).getTime()); TDB.doExecuteInsertWD("now", 0, MainNum, AuxNum , ts, r[i+1]);}`
> 
> `class TDB{
> sql = "create table if not exists " + metricsName[0] + " (SubTime timestamp,MainNum int,AuxNum int,PubTime timestamp, windirection binary(20)) tags(Main int,Aux int)";
> 
> public static void doExecuteInsertWD(String time,int table,int MainNum,int AuxNum,Timestamp PubTime,String v1){} }`
> 
> ![image](https://user-images.githubusercontent.com/22852166/67075189-4299cf00-f1bd-11e9-9040-743f41a740ce.png)
> @fangpanpan

您的sql语句里 PubTime 那一列插入的值没有加上引号。

**Comment by Magic757086354** [comment]
`sql.append(tablePrefix[1]).append(table).append(" values").append("(").append(time).append(",").append(MainNum)
	             .append(",").append(AuxNum).append(",").append("'").append(PubTime).append("'").append(",").append(v1).append(")");`

谢谢！确实是没有append("'")
![image](https://user-images.githubusercontent.com/22852166/67077114-1f711e80-f1c1-11e9-9c71-4efb94f17769.png)

**Comment by Magic757086354** [comment]
@fangpanpan  请问现在社区版支持集群了吗？有没有相关DEMO。

**Comment by fangpanpan** [comment]
> @fangpanpan 请问现在社区版支持集群了吗？有没有相关DEMO。

目前还不支持集群，我们正在考虑是否开源集群的事情。

**Comment by Magic757086354** [comment]
@fangpanpan 好的，谢谢。
