### ISSUE TITLE
enableMicrosecond 参数在配置文件中找不到，值是 true 或者 false？

### ISSUE THREAD

**Issue by zliangliang1024** [taosdata/TDengine#6314]
想要时间精度高一点，时间戳想存成微秒，但是报 Timestamp Out Of Range，在 /etc/taos/taos/taos.cfg 修改文件时，无此参数

 gitinfo:                7a03092edd06d3247d4c1bbe796d55f51c3a1c53 
 gitinfoOfInternal:      NULL 
 buildinfo:              Built at 2021-05-01 22:01 
 version:                2.1.0.0

**Comment by zliangliang1024** [comment]
create database name PRECISION ‘us’

**Comment by yu285** [comment]
please use PRECISION ‘us’ but not enableMicrosecond , it is a old parameter in 1.6 version
