### ISSUE TITLE
how to receive mq data?

### ISSUE THREAD

**Issue by qaiofeng** [taosdata/TDengine#632]
可以说下流程或代码吗

**Comment by liu0x54** [comment]
In brief it takes tree steps to input data from MQ into TDengine. 1. pull data from MQ,such as Kafka and Rabbitmq, etc., 2. parse the data and rewrite it into a TDengine supported SQL line, 3. call the API of TAOS to input it into TDengine. There are several connectors to input data into TDengine, please refer to https://www.taosdata.com/cn/documentation/connector/

Another way is use telegraf as an agent to pull data from MQ( support Kafka,rabbitmq, and so on), and write to TDengine, as per https://www.taosdata.com/cn/documentation/connections-with-other-tools/#Telegraf

hope this help.

**Comment by qaiofeng** [comment]
[[outputs.http]]
[[inputs   ]] 我这儿这么配置呢

**Comment by liu0x54** [comment]
Which MQ are you going to use，and what's the data looks like？We could help you better with more detail.



------------------ Original ------------------

**Comment by qaiofeng** [comment]
telegraf如何与LMQ连接，在配置文件中telegraf.conf如何配置？

**Comment by qaiofeng** [comment]
json格式的数据

**Comment by liu0x54** [comment]
Which LMQ? The light MQ service provided by Aliyun? Seems the LMQ supports MQTT, maybe you can set the inputs as MQTT.

**Comment by qaiofeng** [comment]
是的，阿里云的，

**Comment by qaiofeng** [comment]
[[inputs.mqtt_consumer]]
    servers = ["http://"]
    topics = [to]
    connection_timeout = "30s"
    max_undelivered_messages = 1000
    persistent_session = false
    client_id = "3"
    username = ""
    password = ""
    insecure_skip_verify =false
    data_format = "json"
这么配置对吗

**Comment by liu0x54** [comment]
服务器地址没配？要配上吧，另外没有配置认证信息？是LMQ服务里就没有配吗，建议把阿里云控制台的LMQ信息截屏贴一下

------------------ Original ------------------

**Comment by qaiofeng** [comment]
配置了，telegraf会有社么显示

**Comment by qaiofeng** [comment]
配置已经没问题了
但web页面并没有出现connection

**Comment by qaiofeng** [comment]
在这个过程当中，我需要用到influxdb吗

**Comment by qaiofeng** [comment]
[[outputs.http]]
[[outputs.http]]
   url = "http://127.0.0.1:6020/telegraf/udb"
   method = "POST"
   username = "root"
   password = "taosdata"
   data_format = "json"
   json_timestamp_units = "1ms"

[agent]
   hostname = "gsl"
   metric_batch_size = 30
   interval = "10s"
   debug = true
   omit_hostname = false

hostname 我怎么确定其唯一性，我的设备有好多

**Comment by qaiofeng** [comment]
接下来我该怎么让数据接通呢，目前的话我没有收到mq传过来的数据

**Comment by liu0x54** [comment]
https://github.com/influxdata/telegraf/blob/master/plugins/outputs/file/README.md
你可以先按这个说明把telegraf的out设定为file，输出到一个指定的file中，先确定有没有数据输出到file，如果有了，请把file文件发给我一下tliu@taosdata.com,然后再按涛思的文档修改telegraf的输出到tdengine。

**Comment by qaiofeng** [comment]
没有文件生成

**Comment by liu0x54** [comment]
加下我的微信吧tom-lt

**Comment by qaiofeng** [comment]
加了

**Comment by liu0x54** [comment]
> 加了
没看到，再加一下？

**Comment by liu0x54** [comment]
The TAOS team is developing a tool to grab data from several sources in the near future, please wait a while.
