### ISSUE TITLE
一亿数据按照时间执行排序取前十，报错

### ISSUE THREAD

**Issue by zliangliang1024** [taosdata/TDengine#6322]
一亿数据按照时间排序，去前十条，直接error

DB error: Result set too large to be sorted (0.102456s)

order 的数量级边界大概多少啊？

**Comment by zliangliang1024** [comment]
超级表限制为100万，子表似乎没有限制，插入1亿毫秒级响应

**Comment by yu285** [comment]
子表没有限制
