### ISSUE TITLE
no taosdemo command?

### ISSUE THREAD

**Issue by zhangguangkuo** [taosdata/TDengine#633]

**Comment by fangpanpan** [comment]
请问您是在什么操作时出现的这个错误？是在安装之后吗？

**Comment by zhangguangkuo** [comment]
安装之后出现的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"fangpanpan"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月18日(星期五) 下午2:18
收件人:&nbsp;"taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送:&nbsp;"阔"<945272565@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [taosdata/TDengine] no taosdemo command? (#633)




请问您是在什么操作时出现的这个错误？是在安装之后吗？

**Comment by fangpanpan** [comment]
> 安装之后出现的
> […](#)

请问您是用什么安装的？以及您安装完了后在/usr/local/taos/bin 下面都有什么命令？

**Comment by fangpanpan** [comment]
请问您是用什么安装的？以及您安装完了后在/usr/local/taos/bin 下面都有什么命令？
