### ISSUE TITLE
how to improve insertion speed

### ISSUE THREAD

**Issue by 17600668975** [taosdata/TDengine#634]
插入100W条数据速度很慢java程序10分钟source导入sql 2分钟

java单线程插入,速度慢和列有关吗 15列 
![1571392527(1)](https://user-images.githubusercontent.com/56669821/67084930-80ecb980-f1d0-11e9-9128-dbf2d6c97d55.jpg)

**Comment by xieyinglin** [comment]
请问你目前一条 insert 语句批量插入多少条记录

**Comment by 17600668975** [comment]
> 请问你目前一条insert语句批量插入多少条记录

20条

**Comment by xieyinglin** [comment]
可以加到 50 试下，目前一条 insert 不能超多 4KB

**Comment by 17600668975** [comment]
> 可以加到 50 试下，目前一条 insert 不能超过 4KB

超过20就报错了 应该和列数量有关,有没有其他的瓶颈呢? 
我看官网的C示例可以指定多个客户端插入 , 实际业务中如何保证数据强一致性?

**Comment by jtao1735** [comment]
请帖一下你写的Java程序。原则上，单线程能达到每秒一万以上的插入速度。可以多个线程插入，但是每个数据源只能从一个线程插入

**Comment by 17600668975** [comment]
package com.taos.demo.dao;

import com.taos.demo.entity.AisDynamic;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

@Repository
public class TaosDao {

    private final static Logger logger = LoggerFactory.getLogger(TaosDao.class);

    @Autowired
    private JdbcTemplate jdbcTemplate;

    /**
     * 新增数据
     * @param obj
     * @return
     */
    public int insertData(AisDynamic obj){
        return jdbcTemplate.update("INSERT INTO ais_"+obj.getMmsi()+" USING ais_model TAGS (?) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                obj.getMmsi(),obj.getRecordDatetime(),obj.getLongitude(),obj.getLatitude(),obj.getDirection(),obj.getHeading(),
                obj.getSpeed(),obj.getStatus(),obj.getRot(),obj.getPositionAccuracy(),obj.getUtcHour(),
                obj.getUtcMinute(),obj.getUtcSecond(),obj.getMessageId(),obj.getRevDatetime(),obj.getSourceId());
    }

    /**
     * 新增子表
     * @param num
     * @return
     */
    public void createTable(int num){
        jdbcTemplate.update("create table ais_"+num+" using ais_model tags (?)",num);
    }

    /**
     * 删除数据
     * @param obj
     * @return
     */
    public int deleteData(Object obj){
        String sql = "deleteSql";
        return jdbcTemplate.update(sql,obj);
    }

    /**
     * 查询数据
     * @param selectSql
     * @return
     */
    public List<Integer> selectData(String selectSql){
        String sql = selectSql;
        RowMapper<Integer> rowMapper = new RowMapper<Integer>() {
            @Override
            public Integer mapRow(ResultSet arg0, int arg1) throws SQLException {
                Integer integer = new Integer(0);
                if(arg0.wasNull()) {
                    return integer;
                }
                integer = arg0.getInt(1);
                return integer;
            }
        };
        logger.info("\n---------------------------------------------------------------");
        logger.info("Start select data...");
        int start = (int) System.currentTimeMillis();
        List<Integer> resultList = jdbcTemplate.query(sql,rowMapper);
        int end = (int) System.currentTimeMillis();
        logger.info("Select completed!");
        logger.info("Time spend "+ (end - start)/ 1000 +" seconds.");
        return resultList;
    }

}

**Comment by 17600668975** [comment]
/**
     * 插入shipNum个表的数据
     * @return
     * @throws SQLException
     * @throws IOException
     */
    @RequestMapping("/timeSpeed")
    public Map lookView(int shipNum) throws SQLException, IOException {
        List<AisVO> aisVOListisVO = new ArrayList();
        Map map = new HashMap();
        int sumTime = 0;
        int num = 0;
        for(int i=100000000;i<100000+shipNum;i++) {
            List<AisDynamic> aisDynamicList = new ArrayList<AisDynamic>();
            File file = new File("E:/100CSVFile/"+i+"ship.csv");
            BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(new FileInputStream(file), "utf-8"));
            String line = null;
            while ((line = bufferedReader.readLine()) != null) {
                // 数据行
                String[] items = line.split(",");
                AisDynamic aisDynamic =new AisDynamic();
                aisDynamic.setRecordDatetime(timeStamp2Date(items[0]));
                aisDynamic.setMmsi(Integer.parseInt(items[1]));
                aisDynamic.setLongitude(Integer.parseInt(items[2]));
                aisDynamic.setLatitude(Integer.parseInt(items[3]));
                aisDynamic.setDirection(Integer.parseInt(items[4]));
                aisDynamic.setHeading(Integer.parseInt(items[5]));
                aisDynamic.setSpeed(Integer.parseInt(items[6]));
                aisDynamic.setStatus(Integer.parseInt(items[7]));
                aisDynamic.setRot(Integer.parseInt(items[8]));
                aisDynamic.setPositionAccuracy(Integer.parseInt(items[9]));
                aisDynamic.setUtcHour(Integer.parseInt(items[10]));
                aisDynamic.setUtcMinute(Integer.parseInt(items[11]));
                aisDynamic.setUtcSecond(Integer.parseInt(items[12]));
                aisDynamic.setMessageId(Integer.parseInt(items[13]));
                aisDynamic.setRevDatetime(Integer.parseInt(items[14]));
                aisDynamic.setSourceId(Integer.parseInt(items[15]));
                aisDynamicList.add(aisDynamic);
            }
            if (bufferedReader != null) {
                bufferedReader.close();
            }
            int successCount = 0;
            int errorCount = 0;
            int start = (int) System.currentTimeMillis();
            for (AisDynamic aisDynamic:aisDynamicList) {
                if (1==TaosService.insertData(aisDynamic)){
                    ++successCount;
                }else {
                    ++errorCount;
                }
            }
            int end = (int) System.currentTimeMillis();
            AisVO aisVO = new AisVO();
            aisVO.setNum(++num);
            aisVO.setSuccessNum(successCount);
            aisVO.setErrorNum(errorCount);
            aisVO.setStartTime(timeStamp2Date(String.valueOf(start)));
            aisVO.setEndTime(timeStamp2Date(String.valueOf(end)));
            aisVO.setTimeSpend((end - start)/ 1000);
            aisVO.setMmsi(i);
            aisVOListisVO.add(aisVO);
            //返回平均处理时间
            sumTime +=(end - start)/ 1000;
        }
        map.put("data",aisVOListisVO);
        map.put("avgTime",sumTime/100);
        return map;
    }

**Comment by 17600668975** [comment]
public void insert10Data(List<AisDynamic> aisDynamicList){
        int flag = 0;
        StringBuilder insertSQL = new StringBuilder("INSERT INTO ais_"+aisDynamicList.get(0).getMmsi()+" USING ais_model TAGS ("+aisDynamicList.get(0).getMmsi()+") VALUES");
        for(AisDynamic obj:aisDynamicList){
            insertSQL.append("('"+obj.getRecordDatetime()+"',"+obj.getLongitude()+","+obj.getLatitude()+","+obj.getDirection()+","+obj.getHeading()+","+
                    obj.getSpeed()+","+obj.getStatus()+","+obj.getRot()+","+obj.getPositionAccuracy()+","+obj.getUtcHour()+","+
                    obj.getUtcMinute()+","+obj.getUtcSecond()+","+obj.getMessageId()+","+obj.getRevDatetime()+","+obj.getSourceId()+") ");

            ++flag;
            if (0==flag%10){
                taosDao.insertDataBySplic(insertSQL);
                insertSQL = new StringBuilder("INSERT INTO ais_"+aisDynamicList.get(0).getMmsi()+" USING ais_model TAGS ("+aisDynamicList.get(0).getMmsi()+") VALUES");
            }
            if(!(0==aisDynamicList.size()%10)){
                if(flag==aisDynamicList.size()){
                    taosDao.insertDataBySplic(insertSQL);
                }
            }


        }

**Comment by 17600668975** [comment]
/**
     * 新增数据by拼接
     * @param insertSql
     * @return
     */
    public int insertDataBySplic(StringBuilder insertSql){
        return jdbcTemplate.update(insertSql.toString());

**Comment by xieyinglin** [comment]
目前我们这边 jdbc 单表单线程测试一般都能达到 2w/s，请把你的 java 程序、建表语句、测试数据打包发 ylxie@taosdata.com ，我这边调试看看。

**Comment by xieyinglin** [comment]
你好，我这边使用你的代码测了一下单线程插入 100w 耗时 19.78 s，我这边测试的版本为 1.6.2.2，请问你测试的版本是多少？

![image](https://user-images.githubusercontent.com/41858839/67451638-8f652600-f653-11e9-8dad-9db74c78f398.png)

**Comment by xieyinglin** [comment]
提高速度的建议：
    1. 最好一个线程写一张表，因为 TDengine 设计是一个设备一张表，这样可以提高插入和查询速度。
    2. insert 时可以拼接批量sql 提高并发（目前 preparedstatement 已开发完成，正在测试中）。

注意：目前一条记录的大小不能超过 4KB，一条 Sql （如批量 insert） 语句长度不能超过 64KB。

**Comment by 17600668975** [comment]
速度問題已經解決,目前單綫程插入2w+/s   TDengine果然强大  會一直關注支持taos

**Comment by sanliang125** [comment]
> 速度問題已經解決,目前單綫程插入2w+/s TDengine果然强大 會一直關注支持taos

请问最终是怎么解决的呢？
