### ISSUE TITLE
[nodejs] ERROR in installing td-connector 

### ISSUE THREAD

**Issue by ohmyheartbeat** [taosdata/TDengine#635]
53 warnings and 6 errors generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/Cellar/node/12.11.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user/WebstormProjects/demo/node_modules/ref
gyp ERR! node -v v12.11.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm WARN demo@1.0.0 No description
npm WARN demo@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref@1.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ref@1.3.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by ohmyheartbeat** [comment]
系统：macOS 10.14.6
gcc node-gyp make都安装好了 Python版本2.7.10

**Comment by fangpanpan** [comment]
我们tdengine server 暂时还不支持Mac 系统，可装在Mac 系统上版本还在开发中。

**Comment by ohmyheartbeat** [comment]
使用js的connect库，也需要安装tdengine server吗？我的tdengine server是安装在公有云的ubuntu服务器上

**Comment by fangpanpan** [comment]
> 使用js的connect库，也需要安装tdengine server吗？我的tdengine server是安装在公有云的ubuntu服务器上

但是需要安装client端的。

**Comment by ohmyheartbeat** [comment]
好吧
