### ISSUE TITLE
python error: module object has no attribute "connect"

### ISSUE THREAD

**Issue by ohmyheartbeat** [taosdata/TDengine#636]
![图片](https://user-images.githubusercontent.com/31534021/67139722-d46d0f00-f285-11e9-91b9-74745295ae5e.png)

**Comment by fangpanpan** [comment]
您可以再具体描述一下这个错误发生的过程吗？看您上面的过程，taos.connect 是执行成功过的？

**Comment by ohmyheartbeat** [comment]
我是在python交互式命令行写的，首先安装python2的connect库，然后导入taos库，使用connect方法，成功连接上了，退出python交互式命令行再进入 导入taos成功 再使用connect方法就提示找不到了

**Comment by hzcheng** [comment]
您当前文件夹下有个taos.pyc，您看是不是在运行demo.py的时候import将这个文件导入了。您可以把taos.pyc给删除或挪动到其他地方，然后试下

**Comment by ohmyheartbeat** [comment]
ok
