### ISSUE TITLE
failed to connect to server" : can't find answers from FAQ

### ISSUE THREAD

**Issue by hzj1216000** [taosdata/TDengine#637]
![image](https://user-images.githubusercontent.com/7333799/67153102-31b0a100-f316-11e9-96bd-7c1e33e7d597.png)
![image](https://user-images.githubusercontent.com/7333799/67153106-3e34f980-f316-11e9-8378-ac7b35b1435e.png)
![image](https://user-images.githubusercontent.com/7333799/67153110-455c0780-f316-11e9-8c08-509e359b1070.png)
![image](https://user-images.githubusercontent.com/7333799/67153113-4db44280-f316-11e9-943d-80d0ffe6638a.png)
![image](https://user-images.githubusercontent.com/7333799/67153113-4db44280-f316-11e9-943d-80d0ffe6638a.png)
端口上通的
![image](https://user-images.githubusercontent.com/7333799/67153124-66bcf380-f316-11e9-8371-c116ab3caca6.png)
服务也是启动的
![image](https://user-images.githubusercontent.com/7333799/67153127-74727900-f316-11e9-9d51-dc1c89a0c0d3.png)
但就是联接不到服务器
改到我内网的一台centOS 上安装的taos就能用

**Comment by xieyinglin** [comment]
1. 请问通过 taos shell client 是否可以登录

**Comment by xieyinglin** [comment]
2
