### ISSUE TITLE
How to query multiple newest record then  sum them up?

### ISSUE THREAD

**Issue by lemonxiao0** [taosdata/TDengine#6370]
目前场景如下。
1. 多种设备上传数据，一般是隔一段时间上传，如30秒等
2. 现在想要查询如最近5分钟，所有设备最新上传的记录值，并求和输出

sql语句如何实现这个需求，目前测试均不行
。

**Comment by yu285** [comment]
我们马上将会支持嵌套查询，请耐心等待。

**Comment by lemonxiao0** [comment]
期待新版本
