### ISSUE TITLE
The issue when create super table  in 1.6

### ISSUE THREAD

**Issue by bluewaterstar** [taosdata/TDengine#6373]
**Bug Description**
存在来自超级表1的子表1；超级表2结构不同于超级表1，子表2使用超级表2为模板，使用插入记录时自动建表，若子表2名字和子表1相同，不是报子表已存在，而是报：无效sql，非法数据类型。（尽管tag也不相同）

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by yu285** [comment]
1.6大部分问题已经被修复，且由于重构原因不便于提供技术支持，请更新至2.0.20
