### ISSUE TITLE
invalid sql error when inserting from multiple clients

### ISSUE THREAD

**Issue by 17600668975** [taosdata/TDengine#638]
![image](https://user-images.githubusercontent.com/56669821/67258102-9eb46a00-f4c1-11e9-99b1-d934965b8f68.png)
![image](https://user-images.githubusercontent.com/56669821/67258127-b986de80-f4c1-11e9-8d76-ba35e521023c.png)
多线程写入出现问题

**Comment by 17600668975** [comment]
[hs_err_pid15592.log](https://github.com/taosdata/TDengine/files/3753776/hs_err_pid15592.log)
JVM 崩溃

**Comment by fangpanpan** [comment]
您可以发一下TdTest.java 吗？或者您描述一下您建数据库，建超级表，建子表的过程？

**Comment by 17600668975** [comment]
> 您可以发一下TdTest.java 吗？或者您描述一下您建数据库，建超级表，建子表的过程？

package com.taos.demo;

import com.taos.demo.entity.AisDynamic;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * @单线程test
 * @xieshiqi
 */

public class TdTest implements Runnable {
    private static Logger LOGGER = LoggerFactory.getLogger(TdTest.class);

    private static final String TSDB_DRIVER = "com.taosdata.jdbc.TSDBDriver";

    private static String DB_NAME = "aisdata";

    private static String jdbcUrl = "jdbc:TAOS://180.76.60.102:6020/aisdata?user=root&password=taosdata&useSSL=false";

    private static String inputFile = "D:\\100CSVFile\\";

    private static int shipNum = 10;

    private static AtomicInteger atomicInteger;

    private static List<AisDynamic> aisDynamicList;

    private static AtomicInteger aisDynamicListNum;

    private static Statement stm;

    private static final int reqCount = 35;

    private static AtomicBoolean threadFlag;

    private static ExecutorService service;

    private final long awaitTime = 5 * 1000;

    static {
        try {
            //载入驱动
            Class.forName(TSDB_DRIVER);
            //初始化原子指针
            atomicInteger = new AtomicInteger(0);
            threadFlag = new AtomicBoolean(false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) throws IOException, SQLException {

        Connection connection = null;
        Statement statement = null;
        Long costTime = 0L;
        String sql_prev = "";
        try {
            //初始化DB连接
            connection = DriverManager.getConnection(jdbcUrl);
            LOGGER.info("-------------------------------Successfully Connection");
            stm = connection.createStatement();

            LOGGER.info("-------------------------------import data");
            aisDynamicList = dto2Bean();
            aisDynamicListNum = new AtomicInteger(aisDynamicList.size());
            LOGGER.info("-------------------------------Successfully import data");

            sql_prev = "use " + DB_NAME;
            stm.executeUpdate(sql_prev);

            LOGGER.info("-------------------------------create threadPool");

            // 创建固定数量的线程池
            service = Executors.newFixedThreadPool(10);


            LOGGER.info("-------------------------------import data");
            boolean fals= true ;
            long startTime = System.currentTimeMillis();
            while(!threadFlag.get()){
                service.execute(new TdTest());
            }
            long endTime = System.currentTimeMillis();
            costTime = (endTime - startTime) / 1000;
            LOGGER.info("-------------------------------Successfully Time:" + costTime + " /10000*10");
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            statement.close();
            connection.close();
            service.shutdown();
        }
    }


    public static List<AisDynamic> dto2Bean() throws IOException {

        List<AisDynamic> aisDynamicList = new ArrayList<AisDynamic>();
        for (int i = 100000000; i < 100000000 + shipNum; i++) {
            File file = new File(inputFile + i + "ship.csv");
            BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(new FileInputStream(file), "utf-8"));
            String line = null;
            while ((line = bufferedReader.readLine()) != null) {
                // 数据行
                String[] items = line.split(",");
                AisDynamic aisDynamic = new AisDynamic();
                aisDynamic.setRecordDatetime(items[0]);
                aisDynamic.setMmsi(Integer.parseInt(items[1]));
                aisDynamic.setLongitude(Integer.parseInt(items[2]));
                aisDynamic.setLatitude(Integer.parseInt(items[3]));
                aisDynamic.setDirection(Integer.parseInt(items[4]));
                aisDynamic.setHeading(Integer.parseInt(items[5]));
                aisDynamic.setSpeed(Integer.parseInt(items[6]));
                aisDynamic.setStatus(Integer.parseInt(items[7]));
                aisDynamic.setRot(Integer.parseInt(items[8]));
                aisDynamic.setPositionAccuracy(Integer.parseInt(items[9]));
                aisDynamic.setUtcHour(Integer.parseInt(items[10]));
                aisDynamic.setUtcMinute(Integer.parseInt(items[11]));
                aisDynamic.setUtcSecond(Integer.parseInt(items[12]));
                aisDynamic.setMessageId(Integer.parseInt(items[13]));
                aisDynamic.setRevDatetime(Integer.parseInt(items[14]));
                aisDynamic.setSourceId(Integer.parseInt(items[15]));
                aisDynamicList.add(aisDynamic);
            }
            if (bufferedReader != null) {
                bufferedReader.close();
            }
        }
        return aisDynamicList;
    }


    @Override
    public void run() {

        int flag = atomicInteger.get();
        AisDynamic obj = aisDynamicList.get(flag);
        int i = atomicInteger.addAndGet(reqCount);

        StringBuilder insertSQL = new StringBuilder("INSERT INTO ais_" + obj.getMmsi() + " USING ais_model TAGS (" + obj.getMmsi() + ") VALUES");

        if (aisDynamicListNum.get() > reqCount) {
            for (int j = flag; j < i; j++) {
                insertSQL.append("('" + obj.getRecordDatetime() + "'," + obj.getLongitude() + "," + obj.getLatitude() + "," + obj.getDirection() + "," + obj.getHeading() + "," +
                        obj.getSpeed() + "," + obj.getStatus() + "," + obj.getRot() + "," + obj.getPositionAccuracy() + "," + obj.getUtcHour() + "," +
                        obj.getUtcMinute() + "," + obj.getUtcSecond() + "," + obj.getMessageId() + "," + obj.getRevDatetime() + "," + obj.getSourceId() + ") ");
            }
            aisDynamicListNum.addAndGet(-i);
        }

        if ((aisDynamicListNum.get() < reqCount && aisDynamicListNum.get() > 0)) {
            for (int j = flag; j < aisDynamicList.size(); j++) {
                insertSQL.append("('" + obj.getRecordDatetime() + "'," + obj.getLongitude() + "," + obj.getLatitude() + "," + obj.getDirection() + "," + obj.getHeading() + "," +
                        obj.getSpeed() + "," + obj.getStatus() + "," + obj.getRot() + "," + obj.getPositionAccuracy() + "," + obj.getUtcHour() + "," +
                        obj.getUtcMinute() + "," + obj.getUtcSecond() + "," + obj.getMessageId() + "," + obj.getRevDatetime() + "," + obj.getSourceId() + ") ");
                threadFlag.getAndSet(true);
            }
        }

        try {
//            System.out.println(insertSQL.toString());
            stm.executeUpdate(insertSQL.toString());
            Thread.sleep(20);
        } catch (SQLException | InterruptedException e) {
            e.printStackTrace();
        }

        if (threadFlag.get() == true) {

            service.shutdown();
            try {
                if (!service.awaitTermination(awaitTime, TimeUnit.MILLISECONDS)) {
                    // 超时的时候向线程池中所有的线程发出中断(interrupted)。
                    service.shutdownNow();
                }
            } catch (InterruptedException e) {
                // awaitTermination方法被中断的时候也中止线程池中全部的线程的执行。
                System.out.println("awaitTermination interrupted: " + e);
                service.shutdownNow();
            }

        }
    }
}

**Comment by fangpanpan** [comment]
您建数据库aisdata 和超级表ais_model的语句是怎样的？

**Comment by 17600668975** [comment]
> 您建数据库aisdata 和超级表ais_model的语句是怎样的？

create database aisdata;

create table ais_model(record_datatime timestamp(10),longitude int,latitude int,
direction smallint,heading smallint,speed smallint,status tinyint,rot smallint,position_accuracy tinyint,utc_hour tinyint,utc_minute tinyint,utc_second tinyint,message_id tinyint,rev_datetime int,source_id tinyint) tags(mmsi int);

**Comment by 17600668975** [comment]
@fangpanpan

**Comment by fangpanpan** [comment]
您方便teamvierer 远程看看吗？（可以将办法发到fpang@taosdata.com），或者截一下show stables; 后的结果的截图？这里报错都是说sql语法的问题，说不能用非超级表的表来建表。

**Comment by 17600668975** [comment]
已发

**Comment by xieyinglin** [comment]
你好，刚才远程看了下你的代码，目前不支持多线程使用同一个 connection，请修改成一个线程使用一个 connection。

**Comment by 17600668975** [comment]
> 你好，刚才远程看了下你的代码，目前不支持多线程使用同一个 connection，请修改成一个线程使用一个 connection。

好的 谢谢您 我试试
