### ISSUE TITLE
C# demo needed: how to fetch the query result in Windows c# client

### ISSUE THREAD

**Issue by cnlstar** [taosdata/TDengine#639]
如题，现有WIDOWS的C#例程中：
在TDengineTest.cs中：

        String sql = "select * from " + this.dbName + "." + tablePrefix + i;
        Console.WriteLine(sql);

        int code = TDengine.Query(conn, sql);
        if (code != TDengine.TSDB_CODE_SUCCESS)
        {
          Console.WriteLine(sql + " failure, reason: " + TDengine.Error(conn));
          ExitProgram();
        }

在TDengineDriver.cs中：

    [DllImport("taos.dll", EntryPoint = "taos_query", CallingConvention = CallingConvention.StdCall)]
    static extern public int Query(long taos, string sqlstr);

如需要提取上述“sql"形成的SQL语句查询得到数据，如何处理？能提供这部分的示例代码吗？

**Comment by localvar** [comment]
你贴的代码下面就是处理数据的示例
https://github.com/taosdata/TDengine/blob/bd3db150e541395fe5990666de3ca386b677b5d2/tests/examples/C%23/TDengineTest.cs#L332-L358
