### ISSUE TITLE
Result of FILL(PREV) is not correct 

### ISSUE THREAD

**Issue by leoasc** [taosdata/TDengine#6395]
**Bug Description**
FILL(PREV) NULL数据应该按上一个非NULL值填充，结果返回了NULL

**To Reproduce**
![image](https://user-images.githubusercontent.com/45965121/120968322-4e277880-c79b-11eb-81f4-ca15bd0abfab.png)

**Expected Behavior**
查询语句为：
select last(va),last(vb),last(vc),last(ia),last(ib),last(ic),last(pa),last(pb),last(pc),last(t) from o_547_30a8907761834c9fa96a5f887f61d74a_s 
where ts >='2021-05-29 11:00:00' and ts<='2021-05-29 16:30:00' interval(30m) fill(prev) order by ts desc limit 10;
2021-05-29 15:30:00.000 这条记录的NULL数据应该前面的非NULL值填充，结果直接返回了NULL。

出现问题的版本为2.0.3.0

**Comment by hjxilinx** [comment]
建议升级一下版本到最新的版本，2.0.20.x 这个问题应该已经修复了。
