### ISSUE TITLE
/etc/taos/taos.cfg 这个文件里面的配置项目有详细说明么

### ISSUE THREAD

**Issue by xinqiyang** [taosdata/TDengine#64]
/etc/taos/taos.cfg 这个文件里面的配置项目有详细说明么

**Comment by jtao1735** [comment]
请看用户手册 https://www.taosdata.com/cn/documentation/administrator/#%E6%9C%8D%E5%8A%A1%E7%AB%AF%E9%85%8D%E7%BD%AE

**Comment by xinqiyang** [comment]
谢谢，在这里找到了
build后的， 默认的在这里修改。  谢谢 @jtao1735   老板亲自回复问题，感谢。 
TDengine-master/packaging/cfg/taos.cfg
