### ISSUE TITLE
public network access not work using reverse proxy

### ISSUE THREAD

**Issue by Janus-Xu** [taosdata/TDengine#640]
**Bug Description**
希望公网访问内网tdengine数据库，便于本地调试；内网6020的tcp口是正常访问的；通过反向代理映射到外网IP和端口后无法联通；

**Expected Behavior**
希望修改port，现在均为0，此逻辑导致防火墙白名单等很多操作都没法设置；
希望可以支持代理IP port访问；

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.4]
 - TDengine Version [e.g. 1.6.2.2]

**Comment by guanshengliang** [comment]
HTTP端口为6020，可以通过映射进行访问
其他端口还有很多，您参考https://www.taosdata.com/cn/documentation/administrator/#服务端配置
在开放这些端口的前提下，在共有云上访问的时候，可以配置publicIP
而涉及端口映射的问题，目前没有进行过相关调试
