### ISSUE TITLE
Hope to add the function of last N 

### ISSUE THREAD

**Issue by bhdweb** [taosdata/TDengine#6408]
目前有last_row(*)，获取最新的一条记录，而没有获取最新的N条件记录的方法。但是业务场景经常有显示最新10条数据的需求。本想着可以通过 limit 来做，但是存储的是升序的，这时就想到的了order by，结果因为数据量太量不能order by

目前为了实现需求只能曲线救国了，利用last(*)函数配合时间区间来取N条数据，业务方动态更改这个时间区间

**Comment by hjxilinx** [comment]
请问 您的需求是 超级表内数据的全局有序的情况下需要最近的 N 条记录？

**Comment by kaybinwong** [comment]
不一定是超级表，也可以是子表。
这类应该是一个很常见且有用的查询，比如查询某个条件下最后N条数据。
可以在limit子句上考虑，标量值若为负整数，返回最后指定数目的记录。
@hjxilinx

**Comment by fenghuazzm** [comment]
This issue was closed because it has been inactive for too many days.
