### ISSUE TITLE
Timestamp precision question

### ISSUE THREAD

**Issue by 3018diao** [taosdata/TDengine#6426]
1. I want to ask if TDengine supports nanosecond timestamps.
2. I am currently using version 2.1.2. When I want to change the precision of the database timestamp (ms -> us), the system prompts that there is an error. Is there a problem with my grammar?

taos> create database demo PRECISION US;
DB error: syntax error near "us;" (0.002000s)

Thank you for your help

**Comment by yu285** [comment]
taos> create database demo PRECISION 'us' ;
Query OK, 0 of 0 row(s) in database (0.001194s)


pls try this one
