### ISSUE TITLE
常规业务系统可以使用tdengine吗？

### ISSUE THREAD

**Issue by xiaopenggithub** [taosdata/TDengine#6433]
1.比如常规的新闻网站：
数据表大概有：
1文章分类表
2文章表
3会员信息表
4文章点赞表
5文章评论表

另外，想咨询一下  热词分析 是否可以实现，比如统计所有文章中词频最高的前n个词

**Comment by hjxilinx** [comment]
不是时序类型的非结构化数据，效果不会太明显。

**Comment by xiaopenggithub** [comment]
好滴，谢谢
