### ISSUE TITLE
What is the reason for this issue?

### ISSUE THREAD

**Issue by laurelzhu** [taosdata/TDengine#6435]
Caused by: java.sql.SQLException: TDengine Error: invalid resultset pointer!，然后我的程序就发生了oom
我的查询结果集本身只有七八条数据，是多线程执行，之前单线程执行的时候好像没出现过这个问题，不知道有没有这方面原因
另外，还有一个异常日志：java: /home/ubuntu/ver_release_workspace/TDinternal/community/src/client/src/tscSubquery.c:1504: tscFetchDatablockForSubquery: Assertion `pSql->subState.numOfSub >= 1' failed.不知道和前面的有没有关联
jdbcdriver版本：2.0.1，服务器版本2.1.0
谢谢大家！

**Comment by laurelzhu** [comment]
td resultset pointer  1504

**Comment by hjxilinx** [comment]
每个线程之间不要共享连接对象。会出现未定义行为。
