### ISSUE TITLE
connect to TDengine failed

### ISSUE THREAD

**Issue by qaiofeng** [taosdata/TDengine#644]
![image](https://user-images.githubusercontent.com/56526888/67452702-a3f6ed80-f656-11e9-8618-65807f4a87fc.png)
成功运行1分钟后，出现这种状况，怎么解决呢

**Comment by liu0x54** [comment]
能否简单介绍下你的部署情况，TDengine部署在哪里？从哪里连的TDengine？如果都是云服务器上的话，两个机器是否在同一可用区？还是中间跨了公网？

**Comment by qaiofeng** [comment]
部署在云服务器上，LMQ服务器上的数据直接插入到tdengine，两台服务器在同一可用区

**Comment by liu0x54** [comment]
经过线下沟通定位是因为用户自己开发的数据写入程序处理有些异常导致的，用户在每次收到消息队列消息后写入TDengine时都新建了一个连接，但在写入程序遇到异常后没有close连接，导致连接资源耗尽，后续再写入时无法建立连接。
