### ISSUE TITLE
Insert failed with taos-jdbcdriver 2.0.30（taos-jdbcdriver 2.0.27 is fine）

### ISSUE THREAD

**Issue by NickZhang1024** [taosdata/TDengine#6461]
BINARY、NCHAR字段类型均不能插入除数字之外的字符，比如a、b、c等

不是程序问题，taos-jdbcdriver 2.0.27版本是可以运行的，taos-jdbcdriver 2.0.28 ~ 2.0.30均不能用

之前提过问题，但没人重视

**Comment by NickZhang1024** [comment]
不要再把我提的问题关掉了

**Comment by NickZhang1024** [comment]
https://github.com/taosdata/TDengine/issues/6251

**Comment by yu285** [comment]
已经安排同事排查，之前误关，不好意思

**Comment by yu285** [comment]
请问之前的问题怎样了
