### ISSUE TITLE
invalid sql

### ISSUE THREAD

**Issue by GhostHow** [taosdata/TDengine#648]
大佬帮我看看哪的语法错误

taos> describe tskv;
                             Field                              |      Type      |  Length   |  Note  |
=======================================================================================================
ts                                                              |TIMESTAMP       |          8|        |
tenant_id                                                       |NCHAR           |         50|        |
boolean_value                                                   |BOOL            |          1|        |
entity_id                                                       |NCHAR           |         50|        |
double_value                                                    |DOUBLE          |          8|        |
str_value                                                       |NCHAR           |         50|        |
long_value                                                      |BIGINT          |          8|        |
name                                                            |NCHAR           |         50|        |
Query OK, 8 row(s) in set (0.000166s)

taos> insert into tskv (ts,tenant_id,boolean_value,entity_id,double_value,str_value,long_value,name) VALUES(1571966170849,'1e9dea6ca2aa2c0b3be4b3812b0e430','NULL','1e9e9967966b090be12333cb96effef','NULL','NULL',26,'temperature');

TSDB error: invalid SQL: near "6,'temperature');" syntax error

**Comment by fangpanpan** [comment]
请问您用的是什么时候的安装包？我这边测试这条语句是可以执行的。

**Comment by GhostHow** [comment]
官网上的哪个tar.gz包




------------------ 原始邮件 ------------------
发件人: "fangpanpan"<notifications@github.com>;
发送时间: 2019年10月25日(星期五) 中午11:55
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
抄送: "245455914"<245455914@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [taosdata/TDengine] invalid sql (#648)




请问您用的是什么时候的安装包？我这边测试这条语句是可以执行的。

**Comment by GhostHow** [comment]
官网上的tar.gz包




------------------ 原始邮件 ------------------
发件人: "fangpanpan"<notifications@github.com>;
发送时间: 2019年10月25日(星期五) 中午11:55
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
抄送: "245455914"<245455914@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [taosdata/TDengine] invalid sql (#648)




请问您用的是什么时候的安装包？我这边测试这条语句是可以执行的。

**Comment by fangpanpan** [comment]
> 官网上的哪个tar.gz包
> […](#)

您可以用GitHub上的最新代码编译一下，安装最新的tdengine再试一下吗？
