### ISSUE TITLE
need C# taos_subscribe etc.  example

### ISSUE THREAD

**Issue by cookiestay** [taosdata/TDengine#649]
i try do it like this!

`[DllImport("taos.dll", EntryPoint = "taos_consume", CallingConvention = CallingConvention.StdCall)]
static extern public IntPtr Consume(long sub);`

but find this error
![新建位图图像](https://user-images.githubusercontent.com/56292109/67547228-0e7c5c00-f731-11e9-912d-63b1c4a5cce8.png)

**Comment by guanshengliang** [comment]
This function will be modified in the near future.
There are still bugs, don't use it now
