### ISSUE TITLE
能提供TDengine的集群方案吗？

### ISSUE THREAD

**Issue by jato333** [taosdata/TDengine#65]
TDengine单机环境部署并运行正常，它支持集群方式吗？最好有集群的部署文档，期待中......

**Comment by HuarenYu** [comment]
商业版才提供集群，线性扩展功能。

**Comment by jato333** [comment]
TDengine的Java-driver在哪里下载？

**Comment by HuarenYu** [comment]
官网可以下载

**Comment by jtao1735** [comment]
我们昨天已经将集群设计文档公开，请看https://www.taosdata.com/cn/documentation/more-on-system-architecture/#TDengine%E9%9B%86%E7%BE%A4%E8%AE%BE%E8%AE%A1

等待时机成熟，我们会开源集群版的。现在物联网、车联网、工业互联网领域，绝大部分人是用Hadoop系统处理大数据，TDengine在这个细分领域，是远胜Hadoop. TDengine只会细耕这个领域，只想把物联网大数据做好。

我们会马上提供企业版给大家免费试用，敬请期待

**Comment by jato333** [comment]
亲自测试了一下，描述一下自己的疑虑：1、没有删除（用于数据迁移）和更新（支（用于支持未来的场景，毕竟状态时刻在发生）操作；2、除时间作为主键外，能否支持UUID这样的信息？不妥之处，还请谅解。

**Comment by jtao1735** [comment]
> 亲自测试了一下，描述一下自己的疑虑：1、没有删除（用于数据迁移）和更新（支（用于支持未来的场景，毕竟状态时刻在发生）操作；2、除时间作为主键外，能否支持UUID这样的信息？不妥之处，还请谅解。

TDengine仅仅支持删除库和表，还支持过期删除数据，只是不支持单条记录的删除。对于数据迁移场景，看不出TDengine有问题。你提到的更新操作，实际上是要把状态作为表中的一列不停记录下来，没有问题。

UUID没有问题。

**Comment by sangshuduo** [comment]
2.0 版本集群已经开源
