### ISSUE TITLE
taos shell crash when select last(*) from stable on windows 10

### ISSUE THREAD

**Issue by langshuo** [taosdata/TDengine#650]
**Bug Description**
1、在windows 10 上，taos shell 执行select last(*) from超级表，taos shell崩溃，但是select last(*) from普通表是成功的，last_row和first函数存在同样问题。
2、在taos server的centos上运行taos shell，执行last、last_row和first函数访问超级表和普通表都是成功的。

**Environment (please complete the following information):**
 - taos server OS: CentOS 7.0
 - taos client OS: Windows 10
 - Memory, CPU, current Disk Space
 - TDengine Version: 1.6.3.0

**Comment by fangpanpan** [comment]
我们试一下看看会不会复现。请问您可以描述一下您的数据库基本信息，比如多少表，多少字段，字段类型，多少条数据之类的？以及您可以在配置文件里taos.cfg 里加上debugflag 135 然后将日志 taoslog* 和 taosdlog* 发给我们吗？谢谢了。

**Comment by langshuo** [comment]
附件是导出的数据库脚本和taoslog，taosdlog太大了没上传。估计应该容易复现，我刚才重新建库，包含两张表，只有两个字段，各插入100条记录，问题就再现了。同时发现select count(*) from 超级表也有类似问题。
[sqlAndlog.zip](https://github.com/taosdata/TDengine/files/3774464/sqlAndlog.zip)

**Comment by fangpanpan** [comment]
谢谢您的信息。我们也复现了这个问题，接下来我们会查一下问题所在。

**Comment by guanshengliang** [comment]
使用网站上下载的版本，确实能复现问题。
但回滚到当时的代码，重新编译却不能重现，而当时的调试文件已经冲掉了，所以不好定位。
您再下载一下1.6.3.0的windows客户端试一下，刚才又重新BUILD并上传到网站了。

**Comment by langshuo** [comment]
重新下载客户端后问题已解决，谢谢！

**Comment by zengxiaopang** [comment]
能不能不要给我发了



---Original---
