### ISSUE TITLE
Nested query error

### ISSUE THREAD

**Issue by leoasc** [taosdata/TDengine#6517]
**Bug Description**
试了一下2.1.3.0版的嵌套查询，不像以前那样会报语法错误了，但是查询会失败并且导致客户端异常退出。

**To Reproduce**

![image](https://user-images.githubusercontent.com/45965121/122339972-483c4f00-cf74-11eb-9e6c-7d7a7db5b1af.png)

**Environment (please complete the following information):**
 - OS:WIN10
 - TDengine Version 2.1.3.0

**Additional Context**

**Comment by yu285** [comment]
请问在linux服务端直接查询有这样的现象吗？

**Comment by leoasc** [comment]
服务器上操作没问题
出现问题的客户端也是2.1.3.0的

**Comment by leoasc** [comment]
在服务器上做了简单查询测试。
嵌套内的数据：
taos> select last(level)level from u_alarm group by deviceid;
    level    |            deviceid            |
===============================================
           1 | 572c454739db4f4a860cf3be31f... |
           1 | ad3248d6fb7d40e3823c3451f1c... |
           1 | dfc6d2dc105d427cb1a86081663... |
Query OK, 3 row(s) in set (0.007312s)

一般嵌套查询正常：
taos> select avg(level) from (select last(level)level from u_alarm group by deviceid);
        avg(level)         |
============================
               1.000000000 |
Query OK, 1 row(s) in set (0.003527s)

嵌套+group by 结果异常：
taos> select avg(level),deviceid from (select last(level)level from u_alarm group by deviceid) group by deviceid;
        avg(level)         |            deviceid            |
=============================================================
               0.000000000 | dfc6d2dc105d427cb1a86081663... |
               0.000000000 |                                |
               0.000000000 |                                |
Query OK, 3 row(s) in set (0.003258s)

双重嵌套查询直接报错退出：
taos> select * from (select avg(level) from (select last(level)level from u_alarm group by deviceid));
Floating point exception (core dumped)

其中，嵌套+group by 查询是比较实用的功能，比如第一层查询使用last(*) 按设备分组拿到每个设备最新的数据，
第二层查询再次对结果进行按区域分组统计，得到每个区域最新的统计数据。

**Comment by yu285** [comment]
现在还不支持 三层嵌套查询
