### ISSUE TITLE
how to return last row with table tags in each sub-tables under certain super table?

### ISSUE THREAD

**Issue by langshuo** [taosdata/TDengine#652]
**Is your feature request related to a problem? Please describe.**
use case：
     展示所有设备的最新状态数据。
**Describe your desired behavior**
   当查询时，能够一次返回超级表下面所有普通表（设备）的最新数据并能够区分每个设备。

**Describe your solutions/suggestions if you've any**
   如果last_row函数支持返回所有普通表的字段值和tags值，每个表是一条记录，即可满足要求。

**Comment by fangpanpan** [comment]
"select last_row(*) from stable_name group by tbname,tag_name " can work. 
[tbname is our keyword, need not to be changes; 
stable_name is your super table's name;
tag_name is the name of tag columns;]

**Comment by langshuo** [comment]
采用你提供的方法，问题已经解决，谢谢！
