### ISSUE TITLE
How to use group by

### ISSUE THREAD

**Issue by graceZxy** [taosdata/TDengine#6522]
taos> select * from  task_service_table limit 2;
          time           |              item              |             value              |
============================================================================================
 2020-05-01 15:33:18.000 | task_service_table             | 2020-05-01 23:33:18            |
 2020-06-01 00:00:00.000 | task_table                     | 2020-06-01 00:00:00            |
Query OK, 2 row(s) in set (0.005197s)

taos> select * from  task_service_table group by item ;

DB error: invalid SQL: projection query on columns not allowed (0.000146s)
taos> select count(*),item from  task_service_table group by item ;
       count(*)        |              item              |
=========================================================
                    12 | task_service_table             |
                     1 | task_table                     |
Query OK, 2 row(s) in set (0.002010s)

taos> select count(*),item,value from  task_service_table group by item ;

DB error: invalid SQL: projection query on columns not allowed (0.000147s)

当我单独使用group by的时候，提示错误。加上聚合函数时能正常使用。但是需要拿到其他字段，该怎么操作？

**Comment by graceZxy** [comment]
![image](https://user-images.githubusercontent.com/64307322/122352386-ac194480-cf81-11eb-90ac-154e2c831ae9.png)

**Comment by graceZxy** [comment]
![taos](https://user-images.githubusercontent.com/64307322/122352885-18944380-cf82-11eb-8cb7-98245cc0811a.png)

**Comment by yu285** [comment]
group by 是分组，后面一定要加聚合函数。

如果你单纯地想取出很多行数据，用where就好了。
