### ISSUE TITLE
 JNI ERROR (2354): JNI connection is NULL

### ISSUE THREAD

**Issue by lexang** [taosdata/TDengine#6525]
**Bug Description**
project  examples\JDBC\springbootdemo in TDengine-client-2.1.2.0-Windows-x64   error:JNI connection is NULL

**error :** 
JNI ERROR (2354): JNI connection is NULL
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:72) ~[taos-jdbcdriver-2.0.30.jar:na]

**version:**
TDengine-client-2.1.2.0-Windows-x64 
Dengine-server-2.1.2.0    in  vm    Docker deployment    -p 6030:6030 -p 6035:6035 -p 6040 -p 6041:6041
taos-jdbcdriver-2.0.30.jar  or 2.0.28

They are all the latest

**config:**
spring.datasource.driver-class-name=com.taosdata.jdbc.TSDBDriver
spring.datasource.url=jdbc:TAOS://192.168.2.58:6030/test?timezone=UTC-8&charset=UTF-8&locale=en_US.UTF-8
spring.datasource.username=root
spring.datasource.password=taosdata

**Comment by zyyang-taosdata** [comment]
JNI connection is NULL，这个报错的原因主要是：
你使用的是JDBC-JNI的方式，在建立连接时，JNI方法返回了一个NULL值，jdbcdriver报错。这个报错通常是由于网络配置或者client与taosd的时区不一致等问题产生的。
解决的方法：
检查你的client，通过shell是否能够连通docker内的taosd实例。

**Comment by lexang** [comment]
我不知道到底是甚原因 现在好了 
因为我做了两步操作 一是在服务器自己搭建了个tdengine  没用docker的 我没试好了没就 接着去链接 链接的时候我复制的密码 然后连接上了 最后我试了下输入错误密码 也会报JNI connection is NULL    我觉得我的是密码错误原因。
报错信息太迷惑人了   这个问题我搞了一下午 上网各种查 最后应该是我键盘原因 密码输错导致 ，，，，，，，，，  


还有个问题也是报错错误迷惑了我 ：TDengine Error: Table does not exist    我反复检查 表是在的  
语句是这样 ：insert into meteorology_#{snCode}  USING  meteorology   

最后我debug  发现 sql语句是这样 insert into meteorology_‘des344’   最后我改成 insert into meteorology_${snCode}  USING  meteorology   就好了 。。。。

**Comment by lexang** [comment]
我不知道到底是甚原因 现在好了 
因为我做了两步操作 一是在服务器自己搭建了个tdengine  没用docker的 我没试好了没就 接着去链接 链接的时候我复制的密码 然后连接上了 最后我试了下输入错误密码 也会报JNI connection is NULL    我觉得我的是密码错误原因。
报错信息太迷惑人了   这个问题我搞了一下午 上网各种查 最后应该是我键盘原因 密码输错导致 ，，，，，，，，，  


还有个问题也是报错错误迷惑了我 ：TDengine Error: Table does not exist    我反复检查 表是在的  
语句是这样 ：insert into meteorology_#{snCode}  USING  meteorology   

最后我debug  发现 sql语句是这样 insert into meteorology_‘des344’   最后我改成 insert into meteorology_${snCode}  USING  meteorology   就好了 。。。。

**Comment by lexang** [comment]
> JNI connection is NULL，这个报错的原因主要是：
> 你使用的是JDBC-JNI的方式，在建立连接时，JNI方法返回了一个NULL值，jdbcdriver报错。这个报错通常是由于网络配置或者client与taosd的时区不一致等问题产生的。
> 解决的方法：
> 检查你的client，通过shell是否能够连通docker内的taosd实例。



我不知道到底是甚原因 现在好了 
因为我做了两步操作 一是在服务器自己搭建了个tdengine  没用docker的 我没试好了没就 接着去链接 链接的时候我复制的密码 然后连接上了 最后我试了下输入错误密码 也会报JNI connection is NULL    我觉得我的是密码错误原因。
报错信息太迷惑人了   这个问题我搞了一下午 上网各种查 最后应该是我键盘原因 密码输错导致 ，，，，，，，，，  


还有个问题也是报错错误迷惑了我 ：TDengine Error: Table does not exist    我反复检查 表是在的  
语句是这样 ：insert into meteorology_#{snCode}  USING  meteorology   

最后我debug  发现 sql语句是这样 insert into meteorology_‘des344’   最后我改成 insert into meteorology_${snCode}  USING  meteorology   就好了 。。。。

**Comment by lexang** [comment]
我这次在服务器安装 都是最新版  密码可对了 也不行   看来是版本不匹配问题 
版本如下 ：
TDengine-client-2.1.2.0-Windows-x64
Dengine-server-2.1.3.0
taos-jdbcdriver-2.0.30.jar

报错 JNI ERROR (2354): JNI connection is NULL.  
不知道你们最新版怎么用 ？？？？？

**Comment by zyyang-taosdata** [comment]
我的建议是：
1. 在config/taos.cfg中将debugFlag设置为135，清理log/taoslogX.X日志，然后制造报错。
2. 检查log/taoslogX.X中的日志，日志中有较详细的错误信息。

**Comment by lexang** [comment]
> 我的建议是：
> 
> 1. 在config/taos.cfg中将debugFlag设置为135，清理log/taoslogX.X日志，然后制造报错。
> 2. 检查log/taoslogX.X中的日志，日志中有较详细的错误信息。



在window客户端设置吗

**Comment by lexang** [comment]
> 我的建议是：
> 
> 1. 在config/taos.cfg中将debugFlag设置为135，清理log/taoslogX.X日志，然后制造报错。
> 2. 检查log/taoslogX.X中的日志，日志中有较详细的错误信息。

我现在是window客户端连不上服务器   ☹  版本降了也没有

**Comment by lexang** [comment]
> 我的建议是：
> 
> 1. 在config/taos.cfg中将debugFlag设置为135，清理log/taoslogX.X日志，然后制造报错。
> 2. 检查log/taoslogX.X中的日志，日志中有较详细的错误信息。

06/29 18:29:30.630000 00018224 TSC starting to initialize TAOS client ...
06/29 18:29:30.630000 00018224 TSC Local End Point is:DESKTOP-PEO5CFV:6030
06/29 18:29:30.630000 00018224 UTL tsc scheduler is initialized, numOfThreads:6
06/29 18:29:30.630000 00018224 TMR ttimer monotonic clock source:POSIX clock_gettime
06/29 18:29:30.630000 00018224 UTL tmr scheduler is initialized, numOfThreads:1
06/29 18:29:30.631000 00018224 TSC TableMeta:0000016FE156BF40
06/29 18:29:30.631000 00018224 TSC client is initialized successfully
06/29 18:29:30.631000 00018224 UTL pool:0000016FE16D1CB0 is setup, maxId:5000
06/29 18:29:30.631000 00018224 TMR ttimer monotonic clock source:POSIX clock_gettime
06/29 18:29:30.631000 00018224 UTL open udp socket:0x0:0
06/29 18:29:30.631000 00018224 UTL open udp socket:0x0:0
06/29 18:29:30.631000 00018224 UTL open udp socket:0x0:0
06/29 18:29:30.631000 00018224 UTL open udp socket:0x0:0
06/29 18:29:30.631000 00016360 RPC TSC UDP thread is created, index:1
06/29 18:29:30.631000 00004944 RPC TSC UDP thread is created, index:0
06/29 18:29:30.631000 00018224 UTL open udp socket:0x0:0
06/29 18:29:30.631000 00016308 RPC TSC UDP thread is created, index:2
06/29 18:29:30.631000 00018224 UTL open udp socket:0x0:0
06/29 18:29:30.631000 00011648 RPC TSC UDP thread is created, index:3
06/29 18:29:30.631000 00018224 RPC TSC UDP connection is initialized, ip:0:0 threads:6
06/29 18:29:30.631000 00018224 RPC TSC rpc is opened, threads:6 sessions:5000
06/29 18:29:30.631000 00008320 RPC TSC UDP thread is created, index:4
06/29 18:29:30.631000 00018224 UTL cache:rpcObj, key:00000017E0BFA2A0, 0000016FE14D6C50 added into cache, added:1624962570631, expire:1624962575631, totalNum:1 totalSize:617bytes size:520bytes
06/29 18:29:30.631000 00018224 TSC 0000016FE1A401E0 new SqlObj from 0000016FE19F3950, total in tscObj:1, total:1
06/29 18:29:30.631000 00018224 TSC 0000016FE1A401E0 SQL cmd:connect will be processed, name:, type:0
06/29 18:29:30.631000 00000868 RPC TSC UDP thread is created, index:5
06/29 18:29:30.631000 00018224 RPC TSC 0000016FE3DE81B8 client connection is allocated, uid:0xe3df2b5e
06/29 18:29:30.631000 00018224 RPC TSC UDP connection is setup, ip:6cdf6527:6030 localPort:63914
06/29 18:29:30.631000 00018224 RPC TSC 0000016FE3DE81B8 0000000000000002, connect is sent to 39.101.223.108:6030, len:377 sig:0x01000000:0x00000000:26895
06/29 18:29:31.636000 00019936 RPC TSC 0000016FE3DE81B8 0000000000000002, expected connect-rsp is not received
06/29 18:29:31.636000 00019936 RPC TSC 0000016FE3DE81B8 0000000000000002, re-send msg:connect to 39.101.223.108:6030
06/29 18:29:31.636000 00019936 RPC TSC 0000016FE3DE81B8 0000000000000002, connect is sent to 39.101.223.108:6030, len:377 sig:0x01000000:0x00000000:26895
06/29 18:29:32.641000 00019936 RPC TSC 0000016FE3DE81B8 0000000000000002, expected connect-rsp is not received
06/29 18:29:32.641000 00019936 RPC TSC 0000016FE3DE81B8 0000000000000002, re-send msg:connect to 39.101.223.108:6030
06/29 18:29:32.641000 00019936 RPC TSC 0000016FE3DE81B8 0000000000000002, connect is sent to 39.101.223.108:6030, len:377 sig:0x01000000:0x00000000:26895
06/29 18:29:33.646000 00019936 RPC TSC 0000016FE3DE81B8 0000000000000002, expected connect-rsp is not received
06/29 18:29:33.646000 00019936 RPC TSC 0000016FE3DE81B8 0000000000000002, re-send msg:connect to 39.101.223.108:6030
06/29 18:29:33.646000 00019936 RPC TSC 0000016FE3DE81B8 0000000000000002, connect is sent to 39.101.223.108:6030, len:377 sig:0x01000000:0x00000000:26895

**Comment by zyyang-taosdata** [comment]
> > 我的建议是：
> > 
> > 1. 在config/taos.cfg中将debugFlag设置为135，清理log/taoslogX.X日志，然后制造报错。
> > 2. 检查log/taoslogX.X中的日志，日志中有较详细的错误信息。
> 
> 我现在是window客户端连不上服务器 ☹ 版本降了也没有

你把远程的方式发我邮箱吧，我们帮你看看。我的邮箱：zyyang@taosdata.com

**Comment by lexang** [comment]
> > > 我的建议是：
> > > 
> > > 1. 在config/taos.cfg中将debugFlag设置为135，清理log/taoslogX.X日志，然后制造报错。
> > > 2. 检查log/taoslogX.X中的日志，日志中有较详细的错误信息。
> > 
> > 
> > 我现在是window客户端连不上服务器 ☹ 版本降了也没有
> 
> 你把远程的方式发我邮箱吧，我们帮你看看。我的邮箱：[zyyang@taosdata.com](mailto:zyyang@taosdata.com)



我把udp  tcp端口都开了   就行了

**Comment by jjhgxk** [comment]
这个问题我也遇到了 也不知道怎么解决 昨天用还好好的 今天test就提示这个错误
