### ISSUE TITLE
Select operation on super table  order by desc is slow

### ISSUE THREAD

**Issue by lynn2chen** [taosdata/TDengine#6527]
1.5亿的数据量，倒序不带条件查询要1分钟以上，为什么不能默认倒序？作为时序数据库，每次肯定是想看到最新的记录

**Comment by yu285** [comment]
1.5亿数据量，是没办法排序的。您确定不是查的普通表吗？

**Comment by xForMe** [comment]
> 1.5亿数据量，是没办法排序的。您确定不是查的普通表吗？

意思说超级表可以秒级相应？

**Comment by lynn2chen** [comment]
> 1.5亿数据量，是没办法排序的。您确定不是查的普通表吗？
不是查的普通表，因为想查看 所有记录最新的记录，不能排序，默认查询倒序也行啊，不然没法查了

**Comment by zhuangQingGuang** [comment]
> 1.5亿数据量，是没办法排序的。你确定不是查的普通表吗？

现在最大排序量还是20W条吗

**Comment by yu285** [comment]
> > 1.5亿数据量，是没办法排序的。你确定不是查的普通表吗？
> 
> 现在最大排序量还是20W条吗

超级表排序最大开放到100万

**Comment by yu285** [comment]
> 1.5亿数据量，是没办法排序的。您确定不是查的普通表吗？
> 不是查的普通表，因为想查看 所有记录最新的记录，不能排序，默认查询倒序也行啊，不然没法查了

这个暂时确实做不到，如果取得是最新的一条记录，可以用last函数+group by
