### ISSUE TITLE
timestamp column did not support <=

### ISSUE THREAD

**Issue by duwenhua** [taosdata/TDengine#653]
taos> select * from t;
          ts          |     a     |
===================================
 19-07-15 00:00:00.000|          1|
 19-07-15 00:01:00.000|          2|
 19-07-15 01:00:00.000|          2|
Query OK, 3 row(s) in set (0.001075s)

taos> select * from t where ts>'19-07-15 00:00:00';
          ts          |     a     |
===================================
 19-07-15 00:00:00.000|          1|
 19-07-15 00:01:00.000|          2|
 19-07-15 01:00:00.000|          2|
Query OK, 3 row(s) in set (0.000846s)

taos> 
taos> select * from t where ts>='19-07-15 00:00:00' and ts <='19-11-15 00:00:00' ;
Query OK, 0 row(s) in set (0.000164s)

**Comment by hjxilinx** [comment]
@duwenhua. You should use the correct timestamp format. The "Year" part should be full year number. E.g., the correct SQL expression of your last SQL should be as follows:

```
SELECT * 
FROM t 
WHERE ts>='2019-07-15 00:00:00' AND ts<='2019-11-15 00:00:00';
```
