### ISSUE TITLE
IDEA 连接TDengine 可视化报错

### ISSUE THREAD

**Issue by POPIWEN0209** [taosdata/TDengine#6538]
数据库连接成功
![1624005913(1)](https://user-images.githubusercontent.com/71167273/122533916-9f195580-d054-11eb-8809-75fe1638d738.jpg)
但是点开确报错了
![image](https://user-images.githubusercontent.com/71167273/122534142-d425a800-d054-11eb-9a31-494e7f01b57f.png)
错误代码是：
<failed to load>
java.sql.SQLException: ERROR (2315): unknown taos type in tdengine
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:69)
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:56)
	at com.taosdata.jdbc.TSDBConstants.taosType2JdbcType(TSDBConstants.java:128)
	at com.taosdata.jdbc.TSDBResultSetMetaData.getColumnType(TSDBResultSetMetaData.java:154)
	in RemoteResultSetMetaDataImpl.getFixedColumnType(RemoteResultSetMetaDataImpl.java:105)

**Comment by lexang** [comment]
这个社区不太活跃啊  我提问的问题也都没人理  哎

**Comment by zyyang-taosdata** [comment]
我从图片中看不到您使用的taos-jdbcdriver版本，所以不能确定这是不是driver里的一个bug，我的建议是：
1. 使用最新版本的driver，注意，在IDEA database中配置driver时需要使用taos-jdbcdriver-2.x.x.-dist.jar。
2. 可以clone TDengine的代码，然后进入到src/connector/jdbc目录下，用mvn package编译一个dist包。
3. 也可以尝试使用jdbc-restful的方式连接TDengine数据库

**Comment by xForMe** [comment]
> 数据库连接成功
> ![1624005913(1)](https://user-images.githubusercontent.com/71167273/122533916-9f195580-d054-11eb-8809-75fe1638d738.jpg)
> 但是点开确报错了
> ![image](https://user-images.githubusercontent.com/71167273/122534142-d425a800-d054-11eb-9a31-494e7f01b57f.png)
> 错误代码是：
> 
> java.sql.SQLException: ERROR (2315): unknown taos type in tdengine
> at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:69)
> at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:56)
> at com.taosdata.jdbc.TSDBConstants.taosType2JdbcType(TSDBConstants.java:128)
> at com.taosdata.jdbc.TSDBResultSetMetaData.getColumnType(TSDBResultSetMetaData.java:154)
> in RemoteResultSetMetaDataImpl.getFixedColumnType(RemoteResultSetMetaDataImpl.java:105)

我在mac下使用他们源代码mvn clean install 的包 走rs的，是可以成功的

**Comment by POPIWEN0209** [comment]
> > 数据库连接成功
> > ![1624005913(1)](https://user-images.githubusercontent.com/71167273/122533916-9f195580-d054-11eb-8809-75fe1638d738.jpg)
> > 但是点开确报错了
> > ![image](https://user-images.githubusercontent.com/71167273/122534142-d425a800-d054-11eb-9a31-494e7f01b57f.png)
> > 错误代码是：
> > java.sql.SQLException: ERROR (2315): unknown taos type in tdengine
> > at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:69)
> > at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:56)
> > at com.taosdata.jdbc.TSDBConstants.taosType2JdbcType(TSDBConstants.java:128)
> > at com.taosdata.jdbc.TSDBResultSetMetaData.getColumnType(TSDBResultSetMetaData.java:154)
> > in RemoteResultSetMetaDataImpl.getFixedColumnType(RemoteResultSetMetaDataImpl.java:105)
> 
> 我在mac下使用他们源代码mvn clean install 的包 走rs的，是可以成功的

**Comment by POPIWEN0209** [comment]
![image](https://user-images.githubusercontent.com/71167273/122695367-c483aa80-d272-11eb-8f08-dd62e55fdba1.png)
这个是Driver.jar
