### ISSUE TITLE
Chinese characters are displayed as gibberish

### ISSUE THREAD

**Issue by qhfGitHub** [taosdata/TDengine#654]
?useUnicode=true&characterEncoding=utf8 在连接池中配置这个属性   
在windows环境下向linux服务器中Tdengine插入数据，中文是乱码  linux下的环境字符集是zh_CN.UTF-8

**Comment by hjxilinx** [comment]
The encoding is used by TDengine client to understand the input data.
In Windows platform, the default system encoding is CP936 for Simplified Chinese Edition, not utf-8.
Multi-bytes characters, e.g., the Chinese characters, are stored in TDengine in UCS-4LE.

You should change the attributions in the connection as follows:
```
?characterEncoding=CP936
```

**Comment by qhfGitHub** [comment]
> 
> 
> The encoding is used by TDengine client to understand the input data.
> In Windows platform, the default system encoding is CP936 for Simplified Chinese Edition, not utf-8.
> Multi-bytes characters, e.g., the Chinese characters, are stored in TDengine in UCS-4LE encoding.
> 
> You should change the charset attribution in the connection string as follows:
> 
> ```
> ?characterEncoding=CP936
> ```

就是说Tdengine存储的汉字是按照UCS-4LE编码存储，查看数据库中
![图片](https://user-images.githubusercontent.com/22113323/67743818-cde75000-fa5a-11e9-8218-e08395906819.png)
这是正确的数据

**Comment by hjxilinx** [comment]
您的截图，正确的数据？I don't get it.

**Comment by qhfGitHub** [comment]
> 
> 
> 您的截图，正确的数据？I don't get it.

这是我通过windows插入的中文 ，在数据库中插入撑这个   我通过windows查询方法查询出来的也是正常的汉字

**Comment by hjxilinx** [comment]
OK， 但是这样做不正确，不建议这样做。

**Comment by qhfGitHub** [comment]
> 
> 
> OK， 但是这样做不正确，不建议这样做。

正确的方式是啥

**Comment by hjxilinx** [comment]
```
characterEncoding=CP936. 
```
设置成这样。然后将宽字符写入nchar字段，这样不管是Linux还是Windows的客户端去出来的数据都是正常的，不会显示出现乱码。

**Comment by qhfGitHub** [comment]
> 
> 
> ```
> characterEncoding=CP936. 
> ```
> 
> 设置成这样。然后将宽字符写入nchar字段，这样不管是Linux还是Windows的客户端取出来的数据都是正常的，不会显示出现乱码。

![图片](https://user-images.githubusercontent.com/22113323/67821639-af379680-faf8-11e9-8e39-578512cd4684.png)
![图片](https://user-images.githubusercontent.com/22113323/67821713-e9089d00-faf8-11e9-9190-4d02d63036af.png)


我按照你说的配置了   使用的是连接池  执行sql插入 但是在linux下还是乱码 问下还需要配置什么东西吗

**Comment by johnnyhou327** [comment]
@qhfGitHub are you using JDBC to connect? If so, try add "charset=cp936" to the JDBC url and see if it helps. An example for the JDBC URL would be like 
`jdbc:TAOS://127.0.0.1:0/db?user=root&password=taosdata&charset=cp936`

**Comment by qhfGitHub** [comment]
> 
> 
> @qhfGitHub are you using JDBC to connect? If so, try add "charset=cp936" to the JDBC url and see if it helps. An example for the JDBC URL would be like
> `jdbc:TAOS://127.0.0.1:0/db?user=root&password=taosdata&charset=cp936`

好了 谢谢
