### ISSUE TITLE
changing the keep to 100 years，insert the data before 1970，unable to write normally

### ISSUE THREAD

**Issue by umbrellachen** [taosdata/TDengine#655]
name              |     created time     |  ntables  |  vgroups  |replica| days  |  keep1,keep2,keep(D)   |  tables   |   rows    | cache(b)  |      ablocks       |tblocks| ctime(s)  | clog | comp |time precision|  status  |
==============================================================================================================================================================================================================================================
log                             | 19-10-29 07:00:05.144|          3|          1|      1|     10|30,30,30                |         32|       1024|       2048|             2.00000|     32|       3600|     1|     2|us            |ready     |
weadb                           | 19-10-29 07:17:26.532|          0|          0|      1|     10|36500,36500,36500       |       1000|       4096|      16384|             4.00000|    100|       3600|     1|     2|ms            |ready     |
Query OK, 2 row(s) in set (0.001723s)
=================================================
taos> import into n_57584_prs using prs_hour tags(57584, 3, 161, 110, 50) values ('1950-01-30 16:00:00', 1016);
Query OK, 0 row(s) affected (0.045181s)
------------------------------
Insert 1950 data. The return value is 0
===========================================================
taos> import into n_57584_prs using prs_hour tags(57584, 3, 161, 110, 50) values ('1970-01-30 16:00:00', 1016);
Query OK, 1 row(s) affected (0.000571s)
------------------------------
Insert 1970 data. The return value is 1

**Comment by plum-lihui** [comment]
因为UTC时间从1970开始计算的，插入这之前的数据、以及keep 100年，我们还得考虑一下怎么处理。

**Comment by umbrellachen** [comment]
感谢您的回复，我们也会持续测试，帮助你们提升产品性能





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"plum-lihui"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月1日(星期五) 晚上6:31
收件人:&nbsp;"taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送:&nbsp;"抵铕づ期待~~"<47083420@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [taosdata/TDengine] changing the keep to 100 years，insert the data before 1970，unable to write normally (#655)




因为UTC时间从1970开始计算的，插入这之前的数据、以及keep 100年，我们还得考虑一下怎么处理。

**Comment by plum-lihui** [comment]
非常感谢！有问题，请提交issue就行，我们会及时回复。
