### ISSUE TITLE
taos connect failed, reason: Unable to establish connection.

### ISSUE THREAD

**Issue by HugoPu** [taosdata/TDengine#6558]
**Bug Description**
Installed TDengine-server-2.1.2 on Centos 7 as mentioned in this [video](https://www.taosdata.com/blog/2020/11/11/1941.html), the taosd ran successfully, but I couldn't connect to TDengine with taos command.

**To Reproduce**
1. Go to `command line`
2. Type in `taos -h td1`
3. See error
`taos connect failed, reason: Unable to establish connection.`

**Expected Behavior**
Connect successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/22905948/122698941-fe58af00-d27a-11eb-8cc0-87f9a09b0d2d.png)

**Environment (please complete the following information):**
 - OS: CentOS Linux release 7.2.1511 (Core) on Hyper-V
 - Memory, CPU, current Disk Space
 - TDengine Version [2.1.2]

**Additional Context**

**Comment by yu285** [comment]
please make sure your ports 6030-6041 is open both for TCP and UDP

**Comment by HugoPu** [comment]
防火墙关，telnet测试端口能连通
![image](https://user-images.githubusercontent.com/22905948/122703688-b5a5f380-d284-11eb-859e-f435dcc39bfe.png)

**Comment by HugoPu** [comment]
> please make sure your ports 6030-6041 is open both for TCP and UDP

防火墙挂了，telnet测试端口能连通
![image](https://user-images.githubusercontent.com/22905948/122703819-fbfb5280-d284-11eb-985c-743ae3b4ea0a.png)

**Comment by HugoPu** [comment]
> please make sure your ports 6030-6041 is open both for TCP and UDP

防火墙关了，telnet端口能连通
![image](https://user-images.githubusercontent.com/22905948/122704111-92c80f00-d285-11eb-80f5-008080ab4638.png)

**Comment by yu285** [comment]
是云服务器吗？

**Comment by HugoPu** [comment]
> 是云服务器吗？

不是，Hyper-V上的本地虚拟服务器

**Comment by HugoPu** [comment]
换了一个系统，同样的步骤在ubuntu 18.04 上没问题，在Centos 7.2上有问题
