### ISSUE TITLE
C.taos_query is never return results

### ISSUE THREAD

**Issue by hydaizd** [taosdata/TDengine#6585]
When I use driver-go to query, the program has not returned the result, through Debug, finally locate the problem appeared in the driver-go taosSqlCgo.go file.
```golang
func (mc *taosConn) taosQuery(sqlstr string) (int, error) {
	//csqlstr := (*UserChar)(unsafe.Pointer(&sqlstr))

	csqlstr := C.CString(sqlstr)
	defer C.free(unsafe.Pointer(csqlstr))
	if mc.result != nil {
		C.taos_free_result(mc.result)
		mc.result = nil
	}
	mc.result = unsafe.Pointer(C.taos_query(mc.taos, csqlstr))
	//mc.result = unsafe.Pointer(C.taos_query_c(mc.taos, csqlstr.Str, C.uint32_t(csqlstr.Len)))
	code := C.taos_errno(mc.result)
	if 0 != code {
		errStr := C.GoString(C.taos_errstr(mc.result))
		mc.taos_error()
		return 0, errors.New(errStr)
	}

	// read result and save into mc struct
	num_fields := int(C.taos_field_count(mc.result))
	if 0 == num_fields { // there are no select and show kinds of commands
		mc.affectedRows = int(C.taos_affected_rows(mc.result))
		mc.insertId = 0
	}

	return num_fields, nil
}
```
during the execution of this line of code: 
```golang
mc.result = unsafe.Pointer(C.taos_query(mc.taos, csqlstr))
```
The program has been waiting for no result to return, this problem is not a 100 percent occurrence, but there is a chance of occurrence, but the probability is relatively high.

Because my program uses the database connection pool, because this line of code has not returned the result, every time it appears, it will consume a connection resource, and eventually it will exhaust the connection pool resource, causing all the queries to crash.

Operating environment information is as follows:
golang version：go1.16.5 windows/amd64
taosdb server：2.0.14
taos.dll version：2.0.14

**Comment by sangshuduo** [comment]
Please upgrade TDengine to latest release and try again.the

**Comment by hydaizd** [comment]
I installed the same version 2.0.14 locally and this issue did not occur.
