### ISSUE TITLE
TDengine Windows Clinet 2.1.3.0, taos connect failed, reason: Invalid app version

### ISSUE THREAD

**Issue by NickZhang1024** [taosdata/TDengine#6599]
I found a problem with versioning, TDengine Windows Clinet 2.1.2.0, taos connect to Linux Server 2.1.2.0, 2.1.0.0 is success, but TDengine Windows Clinet update to 2.1.3.0, taos connect to Linux Server 2.1.2.0, 2.1.0.0 failed, reason: Invalid app version

**Comment by yu285** [comment]
please make both side version consistent, it is not a bug.
