### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by qswang123** [taosdata/TDengine#66]
运行  systemctl start build/bin/taosd 命令，提示错误信息：
Failed to get D-Bus connection: Operation not permitted

**Comment by coder-chriswang** [comment]
@qswang123 安装步骤，请确定一直是在build文件夹进行的，make install 以后应该就可以直接用 sudo systemctl start taosd启动
我这里是OK的

**Comment by hzcheng** [comment]
您好，docker默认是不提供admin权限的，因此不能运行systemctl命令，您可以用--privilege选项，或者在docker-compfile.yml中添加sys_add:true选项。另外，如果您可以参考https://blog.csdn.net/qishidiguadan/article/details/96284529这篇博客，关于在docker中编译和运行TDengine。
