### ISSUE TITLE
Error when integrating Tdengine with mybatis: the column. data type is float in TDengine, BigDecimal in java and this column value is null

### ISSUE THREAD

**Issue by chenzanlee** [taosdata/TDengine#661]
![image](https://user-images.githubusercontent.com/16750457/67837704-9ea01400-fb2a-11e9-9ae3-d35700dcc270.png)
![image](https://user-images.githubusercontent.com/16750457/67837720-a8297c00-fb2a-11e9-8c9c-254f87036df6.png)
如上，acc_electricity_usage字段在涛思数据库中为float类型，java中为BigDicimal类型，当值为null时，mybaits设置参数，经jdbc执行处理为sql语句时，会将null处理为'NULL'，这种情况下TDengine会视为无效的sql语句而抛错。

**Comment by xieyinglin** [comment]
你好，我这边测试没有发现问题，请拉取最新代码测试下。
另请使用最新 taos-jdbcdriver-1.0.2.jar。
https://mvnrepository.com/artifact/com.taosdata.jdbc/taos-jdbcdriver

![image](https://user-images.githubusercontent.com/41858839/67915541-4884ac80-fbce-11e9-8988-7e4893a63812.png)

![image](https://user-images.githubusercontent.com/41858839/67915566-605c3080-fbce-11e9-9076-564f21974b8b.png)

**Comment by chenzanlee** [comment]
你好，谢谢，我这边按你给的方案，替换成最新的taos-jdbcdriver-1.0.2.jar，问题解决。但是新的驱动jar包又引入了新的问题，我通过mybatis插入的标签值全部变成了问号。我将驱动替换回原来的版本，标签值设置正确。
![image](https://user-images.githubusercontent.com/16750457/67946483-71cc2980-fc1c-11e9-8891-3bdbd564a631.png)
![image](https://user-images.githubusercontent.com/16750457/67946502-7b559180-fc1c-11e9-8c95-29188df7344b.png)
我之前的驱动版本是 com.taosdata.jdbcdriver-1.0.1</version.

如图上所示， 执行select device_id,unit_link_id from evc_alarm_data;显示这两个值为？号。我删除表格后，回退驱动版本后，重新执行原来的测试用例，标签值设置正确。

**Comment by chenzanlee** [comment]
![image](https://user-images.githubusercontent.com/16750457/67946825-1f3f3d00-fc1d-11e9-8067-54d408e44046.png)
附上我的代码bu fen部分截图。
![image](https://user-images.githubusercontent.com/16750457/67946885-4bf35480-fc1d-11e9-97b2-8cd4d01f57ff.png)

**Comment by xieyinglin** [comment]
由于考虑到在写入超级表的子表时，如果子表已经存在，则不会更新已存在子表的标签，所以当时设计如果 subTableName 为静态就忽略处理标签，为了快速解决这个问题，请把 ${subTableName} 、${superTableName} 替换成  #{subTableName} 、#{superTableName}

后续我会修复下这个问题，兼容 $ 、#  的使用，但还是注意`如果子表已经存在则不会更新已存在子表的标签`

**Comment by chenzanlee** [comment]
> 由于考虑到在写入超级表的子表时，如果子表已经存在，则不会更新已存在子表的标签，所以当时设计如果 subTableName 为静态就忽略处理标签，为了快速解决这个问题，请把 ${subTableName} 、${superTableName} 替换成 #{subTableName} 、#{superTableName}
> 
> 后续我会修复下这个问题，兼容 $ 、# 的使用，但还是注意`如果子表已经存在则不会更新已存在子表的标签`

我之前是使用#号的，但是当时使用#号导致表名中混入了字符串的引号，所以后面改成使用$.我当时的场景是xxx#{subTableNamePostfix}这种。xxx是写死的超级表名，也就是子表的前缀。

**Comment by xieyinglin** [comment]
确实存在表名有单引号问题，我这边修复下

**Comment by xieyinglin** [comment]
我修复了 taos-jdbcdriver-1.0.2.jar 标签值为 ？的问题，tableName 目前还是只能使用 ${}
