### ISSUE TITLE
go build error: undefined reference to `taosGetErrno'

### ISSUE THREAD

**Issue by hydaizd** [taosdata/TDengine#6611]
When driver-go bag verion is github.com/taosdata/driver-go v0.0.0-20210127143907-31dc97ac06b1 and TDengine version is 2.0.14.0, go build is normal. But after upgrade to the latest version, this problem appears.

Go build reported the following error in windows os:

![image](https://user-images.githubusercontent.com/52842376/123240147-a2a85300-d512-11eb-82bb-c2dfbfd8ed49.png)

driver-go pull the latest bag (github.com/taosdata/driver-go v0.0.0-20210609071024-b8f76da4a708) and TDengine already upgraded to version 2.1.3.0

![image](https://user-images.githubusercontent.com/52842376/123240647-0f235200-d513-11eb-93bf-6a0ed8529f9c.png)

The result of the go env command is as follows:

![image](https://user-images.githubusercontent.com/52842376/123242111-49412380-d514-11eb-8518-1a15a99a3b09.png)

Please tell me why?

**Comment by zitsen** [comment]
Sorry for that, statement api is not exported in Win DLL, that why your build is failed.

Currently, if you do not need the statement api, you could use an older version of driver-go:

```sh
go get github.com/taosdata/driver-go/taosSql@2bd1b495d5f35652c1ac1740664541d14658c617
```

**Comment by zitsen** [comment]
The problem sbould only affact windows client.

**Comment by hydaizd** [comment]
This older version doesn't have a subscription feature. When will the problem be fixed?

**Comment by zitsen** [comment]
@hydaizd please use win branch:

```sh
go get github.com/taosdata/driver-go/taosSql@win
```
