### ISSUE TITLE
JDBC can't connect to TAOSDATA

### ISSUE THREAD

**Issue by maxin1** [taosdata/TDengine#6619]
涛思数据库连接失败

jar:2.0.31
class:com.taosdata.jdbc.rs.RestfulDriver
jdbc:TAOS-RS://cps-server190:6041/log
exception:Driver class 'org.apache.http.protocol.HttpContext' not found.

jar:2.0.31
class:com.taosdata.jdbc.TSDBDriver
jdbc:TAOS://cps-server190:6030/log
TDengine-client-2.1.3.0-Windows-x64.exe
exception:[9044] JNI ERROR (2354): JNI connection is NULL

jar:2.0.18
class:com.taosdata.jdbc.TSDBDriver
jdbc:TAOS://cps-server190:6030/log
TDengine-client-2.1.3.0-Windows-x64.exe
exception：TDengine Error: Unable to resolve FQDN.

jar:2.0.18
class:com.taosdata.jdbc.rs.RestfulDriver
jdbc:TAOS-RS://cps-server190:6041/log
exception：Driver class 'org.apache.http.protocol.HttpContext' not found.

安装集群版本是：2.1.1.0，是不是jdbc-driver版本和集群版本不一致导致的，那么，2.1.1.0的版本适用的jdbc-driver版本是多少呢？

**Comment by yu285** [comment]
2.0.31的jdbc要和2.1.3.0数据库配合使用，还不知道您的数据库版本。

除此之外：exception：TDengine Error: Unable to resolve FQDN.

看到了这个，可能是除了jdbc版本不匹配以外，还有一些配置原因。

可以添加微信15652223354帮您排查

**Comment by maxin1** [comment]
问题已经解决！更换jdbc-driver版本为2.0.30，并且节点域名换成ip，jdbc可以连接到taos
