### ISSUE TITLE
Subscribe to the failure

### ISSUE THREAD

**Issue by hydaizd** [taosdata/TDengine#6649]
When the program starts, the subscription fails if the SQL query result set subscribed to is empty. In fact, an empty query result set is normal for an application that has just gone live, should not be subscribed directly to fail.

![image](https://user-images.githubusercontent.com/52842376/123577245-09c15280-d806-11eb-9658-10bbebb6acf1.png)

**Comment by hydaizd** [comment]
After a number of debugging, found that query is the super table, if there is no child table under the super table has this problem

**Comment by yu285** [comment]
hi sorry for delay responese ， could u provide us  your code ,then we can reproduce it
