### ISSUE TITLE
how to upgrade new version of TDengine and backup

### ISSUE THREAD

**Issue by xujiesh0510** [taosdata/TDengine#665]
Q1: How do i  do backup since community version of TDengine is not distributed  ?
Q2: How to upgrade TDengine  to a new version ?

**Comment by xujiesh0510** [comment]
Any answer will be much appricated.

**Comment by fangpanpan** [comment]
Q1: you only need to backup your data folder (default is /var/lib/taos) by making a compressed file. (Because the tsdb folder is a soft link, compressed file can main this soft link)
Q2: you can stop TDengine and then install the enterprise version of TDengine. After starting the TDengine, you can query all data in your previous database. 

Since enterprise version is distributed, you can install TDengine in another machine and then join this machine with the current machine to build a cluster.

**Comment by szlyunnan** [comment]
@fangpanpan 
I want to only to backup data for crontab everyday, How can I do it?

**Comment by fangpanpan** [comment]
> @fangpanpan
> I want to only to backup data for crontab everyday, How can I do it?

1） write a bash script like td_backup.sh, then add a line '59 23 * * * root td_backup.sh' on /etc/crontab. 
2) restart crontab 

example for td_backup.sh:
 backup_folder=/backup/tdegnine/
cd /var/lib
tar czf taos.tar.gz taos
rm -rf $backup_folder/*
mv taos.tar.gz $backup_folder/

**Comment by szlyunnan** [comment]
@fangpanpan thanks your reply

some issue:
1. That's the only way？to backup /var/lib/taos floder?
2. can't use taosdum?

**Comment by fangpanpan** [comment]
> @fangpanpan thanks your reply
> 
> some issue:
> 
> 1. That's the only way？to backup /var/lib/taos floder?
> 2. can't use taosdum?

1. taosdump can be used. execute './taosdump --help' and then you will know how to use this command
A simple example:
taosdump database_name table_name; 
[Then you will find a taos.sql file]. 
[if you want to dump all data saved in taos.sql, the command is as follows:]
taosdump -i taos.sql

**Comment by szlyunnan** [comment]
when I use taosdump 
export some failed, like these:
failed to run command describe test_quote
failed to run command describe test
failed to run command describe test
failed to run command describe test_idx
failed to run command describe test
failed to run command describe test_quote
failed to run command describe test_idx
failed to run command describe test
failed to run command describe test
failed to run command describe test
failed to run command describe test
failed to run command describe test_quote
failed to run command describe test_quote
failed to run command describe test
failed to run command describe test
failed to run command describe test_quote
failed to run command describe test
failed to run command describe test
failed to run command describe test
failed to run command describe test_idx
failed to run command describe test
failed to run command describe test
failed to run command describe test_idx
failed to run command describe test
failed to run command describe test
failed to run command describe test
failed to run command describe test`
`

**Comment by szlyunnan** [comment]
Whether need to stop the database？

**Comment by fangpanpan** [comment]
> Whether need to stop the database？

database need not to stop. Could you try the failed command above like "describe test" in the taos> ?

**Comment by szlyunnan** [comment]
test is my database table name

**Comment by fangpanpan** [comment]
> test is my database table name

but from your report of using taosdump. The command 'describe test' failed. So I want to know whether it can be  executed successfully in the taos>

**Comment by szlyunnan** [comment]
yes, successfully in taos. I running.

**Comment by szlyunnan** [comment]
I run taosdump in host A to backup host B databases

**Comment by fangpanpan** [comment]
> yes, successfully in taos. I running.

There could be some bugs in the taosdump. It can be the database is too large. You can try We will consider to fix these bugs. Now you can backup the data folder /var/lib/taos. This folder can be moved to other machine and the data still can be read by tdengine.

**Comment by fangpanpan** [comment]
> I run taosdump in host A to backup host B databases

host A and host B are joined to a cluster? in host A, you can query databases in Host B?

**Comment by szlyunnan** [comment]
thanks.

**Comment by szlyunnan** [comment]
> host A and host B are joined to a cluster? in host A, you can query databases in Host B?

not cluster, but Host A can connection to Host B and query

**Comment by szlyunnan** [comment]
when excute in Host B faild too
