### ISSUE TITLE
Csharp invokes ConnectTDengine  issue

### ISSUE THREAD

**Issue by domedut** [taosdata/TDengine#6652]
**Bug Description**
Asp.net 5.0 csharp API, 构造函数中两次调用 ConnectTDengine 失败
**To Reproduce**
1. Asp.net 5.0 csharp API, 构造函数中 调用. TDengineDirect 构造，并调用 ConnectTDengine，第一次没问题。
2. 当第二次进入上述步骤，就会报错
 ```System.AccessViolationException:“Attempted to read or write protected memory. This is often an indication that other memory is corrupt.” ```csharp

**Expected Behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/12593721/123594083-d7bde980-d821-11eb-8775-c74ec54ef31d.png)
**Environment (please complete the following information):**
 - OS: [win10]
 - Memory, CPU, current Disk Space
 - TDengine Version [2.0.20.0]

**Additional Context**

**Comment by sangshuduo** [comment]
@domedut 可以把完整可编译运行的代码贴一下吗？

**Comment by arielyang** [comment]
This issue was closed because it has been inactive for too many days.
