### ISSUE TITLE
Taosd services hangs up when executing select/create query

### ISSUE THREAD

**Issue by HedyLni** [taosdata/TDengine#6663]
**Bug Description**
version:                2.1.1.0 
After restart taosd service,  no result is returned when executing select/create query from TAOS shell. Before taosd services running correctly for some time:

    taos> select * from t_3fd71a6b_3676_484c_a0db_c1cdf89e0490_anquanmen ;

    ^C
    DB error: Query terminated (610.493229s)

    taos> create table t1(ts timestamp, v1 int);
    
    DB error: Processing of request timed out (604.518419s)
    taos> select * from t_3fd71a6b_3676_484c_a0db_c1cdf89e0490_anquanmen;

The last query is lasting for 30min with no data returned.

日志：
[taoslog.txt](https://github.com/taosdata/TDengine/files/6730464/taoslog.txt)
[taosdlog.txt](https://github.com/taosdata/TDengine/files/6730466/taosdlog.txt)

**Comment by yu285** [comment]
maybe the reason is some big query hang in background, then make every other operation has no result back.

if restart taosd service could not resolve it , pls add Wechat 15652223354 for more help
