### ISSUE TITLE
How to get metrics of TDengine itself?

### ISSUE THREAD

**Issue by chinajuanbob** [taosdata/TDengine#6665]
How to get metrics of TDengine itself?
Thanks!

**Comment by sangshuduo** [comment]
do you mean openmetrics interface?

**Comment by arielyang** [comment]
Check this: TDinsight https://www.taosdata.com/docs/cn/v2.0/tools/insight

**Comment by fenghuazzm** [comment]
Closing this issue since there is no response for too many days.
