### ISSUE TITLE
Is there anyone using TDengine in production environment？

### ISSUE THREAD

**Issue by flykarry** [taosdata/TDengine#6674]
有人在生产环境启用了吗？什么数据量？稳定性如何？

**Comment by YiuTerran** [comment]
更新太频繁了，每次都是一堆FIX-BUG，真的不敢用…

**Comment by cpvmrd** [comment]
> 有人在生产环境启用了吗？什么数据量？稳定性如何？

这里有很多用户案例：https://www.taosdata.com/cn/blog/?categories=4。

**Comment by leoasc** [comment]
我们是有实际用的，坑挺大的，不是特别着急的话，建议观望等待后面功能完善的版本。
目前遇到主要的问题：
1、稳定性：之前有查询可以让TD崩溃，是什么查询忘了，到现在都有心理阴影。
2、功能完善度：主要是缺少join和嵌套查询，这个只有自己写代码对查询结果进行二次处理，现在新版对嵌套查询是支持了，但还是不完善。
3、聚合查询结果异常，刚提了BUG 。。

**Comment by yu285** [comment]
> 我们是有实际用的，坑挺大的，不是特别着急的话，建议观望等待后面功能完善的版本。
> 目前遇到主要的问题：
> 1、稳定性：之前有查询可以让TD崩溃，是什么查询忘了，到现在都有心理阴影。
> 2、功能完善度：主要是缺少join和嵌套查询，这个只有自己写代码对查询结果进行二次处理，现在新版对嵌套查询是支持了，但还是不完善。
> 3、聚合查询结果异常，刚提了BUG 。。

您使用的2.0.3是去年的版本，这一年我们修复了很多使用问题，服务端已经比较稳定了，您的那个问题麻烦提供一下建表语句和数据，我们可以在新版本复现一下，大概率已经修复。
