### ISSUE TITLE
Create table service is not available

### ISSUE THREAD

**Issue by xujiesh0510** [taosdata/TDengine#669]
Enviroment:
docker image from official.
when i try to create 100000 tables using one adonet session , server throws exceptions：

Maikebing.Data.Taos.TaosException (0x80004005): Server is not available
at Maikebing.Data.Taos.TaosException.ThrowExceptionForRC(String _commandText, TaosErrorResult taosError)
at Maikebing.Data.Taos.TaosCommand.ExecuteReader(CommandBehavior behavior)
at Maikebing.Data.Taos.TaosCommand.ExecuteNonQuery()

If i let the thread sleep 2 ms after creating a table,the exception disappears.

So, i think this is a performance issue .

**Comment by xujiesh0510** [comment]
here is the test code:

 public class CreateTableManager
    {
        private static TaosConnection _connection;
        public static async Task  Create(int metricCount)
        {
            for (int i = 0; i < metricCount; i++)
            {
                try
                {
                  await  CreateTable(i);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                }
                Console.WriteLine(i);
            }
            _connection.Close();

        }

        private static async Task CreateTable(int x)
        {

            string database = "db";
            var builder = new TaosConnectionStringBuilder()
            {
                DataSource = "http://192.168.100.41:6020/rest/sql",
                DataBase = database,
                Username = "root",
                Password = "taosdata"
            };
            //Example for ADO.Net 
            if (_connection == null)
            {
                _connection = new TaosConnection(builder.ConnectionString);
                _connection.Open();
            }
            
            _connection.CreateCommand($"create table if not exists {database}.t{x} (ts timestamp, cdata float);")
                    .ExecuteNonQuery();
           await Task.Delay(2);
        }
    }

**Comment by guanshengliang** [comment]
You can put the program into a stand-alone package, or other ways to reproduce the problem, such as a cloud machine.
So that I can solve the problem

**Comment by xujiesh0510** [comment]
I think it's the c# client library(Maikebing)  bug,switching to invoke http method , error disappears.
