### ISSUE TITLE
TDengine ERROR (8000000b): Unable to establish connection

### ISSUE THREAD

**Issue by zouyadong008** [taosdata/TDengine#6691]
运行网方demo ,通过sql 创建数据库和表都 能成功，就是 执行行 查询和插入失败，我在网上看不少人碰到这个问题呀。服务端和 客户端都 是最新版，我用的jdbc:TAOS 这种方法连tdengine的，没有用restful。服务上的防火墙我关闭了应该 不存端口没有全的问题吧

**Comment by zouyadong008** [comment]
感觉tdengine 除了restul接口可用，原生的驱动完全不可用

**Comment by xleili** [comment]
如果用JNI的连接方式：
Class.forName("com.taosdata.jdbc.TSDBDriver");
String jdbcUrl = "jdbc:TAOS://taosdemo.com:6030/test?user=root&password=taosdata";
Connection conn = DriverManager.getConnection(jdbcUrl);
几个排查方向
1，有安装有tdengine的server或者cleint 2 taosshell 可以连接到server  3:端口6030是不是通的 4:URL 写的对不对

**Comment by zouyadong008** [comment]
我都或以 连上去 成功创建数库 和 数据表，就是无法 查询和插入

在 2021-06-30 19:56:41，"xiaolei li" ***@***.***> 写道：


如果用JNI的连接方式：
Class.forName("com.taosdata.jdbc.TSDBDriver");
String jdbcUrl = "jdbc:TAOS://taosdemo.com:6030/test?user=root&password=taosdata";
Connection conn = DriverManager.getConnection(jdbcUrl);
几个排查方向
1，有安装有tdengine的server或者cleint 2 taosshell 可以连接到server 3:端口6030是不是通的 4:URL 写的对不对

**Comment by sangshuduo** [comment]
请问是什么运行环境？TDengine 和 JDBC 版本是多少？

**Comment by zouyadong008** [comment]
TDengine-server-2.1.2.0

<dependency>
<groupId>com.taosdata.jdbc</groupId>
<artifactId>taos-jdbcdriver</artifactId>
<version>2.0.31</version>
</dependency>


我发现不少人遇到这个错，最后的方案都是转用 restful方式了



在 2021-06-30 20:26:07，"Shuduo Sang" ***@***.***> 写道：

请问是什么运行环境？TDengine 和 JDBC 版本是多少？

**Comment by sangshuduo** [comment]
server 和 client 都是 Linux 吗？用 taos 可以连上 server 进行操作吗？

**Comment by zouyadong008** [comment]
window client 可以连接成功 但只能创建数据库  和 创建表 不可以 查询表数据，也不能插入数据

在 2021-06-30 22:58:52，"Shuduo Sang" ***@***.***> 写道：


server 和 client 都是 Linux 吗？用 taos 可以连上 server 进行操作吗？

**Comment by sangshuduo** [comment]
现象上很像是 TCP 不通导致的。可以参考一下 FAQ 相关部分 https://www.taosdata.com/cn/documentation/faq

**Comment by zouyadong008** [comment]
PS C:\TDengine> taos -V
version: 2.1.3.0
PS C:\TDengine> taos -n client -h 192.168.244.3 -P 6030 -e 6042 -l 1000
wrong options
taos shell is used to test the TDengine database
-h
TDengine server FQDN to connect. The default host is localhost.
-p
The password to use when connecting to the server.
-P
The TCP/IP port number to use for the connection
-u
The user name to use when connecting to the server.
-A
The user auth to use when connecting to the server.
-c
Configuration directory.
-C
Dump configuration.
-s
Commands to run without enter the shell.
-r
Output time as unsigned long..
-f
Script to run without enter the shell.
-d
Database to use when connecting to the server.
-t
Time zone of the shell, default is local.
-n
Net role when network connectivity test, default is startup, options: client|server|rpc|startup|sync.
-l
Packet length used for net test, default is 1000 bytes.
-V
Print program version.
PS C:\TDengine>

按照官方的档是操作的，指令完全不能识别呀，文档是不是很久没更新了



在 2021-06-30 23:25:17，"Shuduo Sang" ***@***.***> 写道：

现象上很像是 TCP 不通导致的。可以参考一下 FAQ 相关部分 https://www.taosdata.com/cn/documentation/faq

**Comment by zouyadong008** [comment]
PS C:\TDengine> taos -n client -h 192.168.244.3 -P 6030 -u root -p zyd123456
07/01 09:11:13.813000 00010476 UTL work as client, host:192.168.244.3 startPort:6030 endPort:6041 pkgLen:1000

07/01 09:11:13.816000 00010476 UTL server ip:192.168.244.3 is resolved from host:192.168.244.3
successed to test TCP port:6030


现在 没有-e 的参数呀



At 2021-07-01 09:08:25, "zyd200888" ***@***.***> wrote:

PS C:\TDengine> taos -V
version: 2.1.3.0
PS C:\TDengine> taos -n client -h 192.168.244.3 -P 6030 -e 6042 -l 1000
wrong options
taos shell is used to test the TDengine database
-h
TDengine server FQDN to connect. The default host is localhost.
-p
The password to use when connecting to the server.
-P
The TCP/IP port number to use for the connection
-u
The user name to use when connecting to the server.
-A
The user auth to use when connecting to the server.
-c
Configuration directory.
-C
Dump configuration.
-s
Commands to run without enter the shell.
-r
Output time as unsigned long..
-f
Script to run without enter the shell.
-d
Database to use when connecting to the server.
-t
Time zone of the shell, default is local.
-n
Net role when network connectivity test, default is startup, options: client|server|rpc|startup|sync.
-l
Packet length used for net test, default is 1000 bytes.
-V
Print program version.
PS C:\TDengine>

按照官方的档是操作的，指令完全不能识别呀，文档是不是很久没更新了



在 2021-06-30 23:25:17，"Shuduo Sang" ***@***.***> 写道：

现象上很像是 TCP 不通导致的。可以参考一下 FAQ 相关部分 https://www.taosdata.com/cn/documentation/faq

**Comment by zouyadong008** [comment]
PS C:\TDengine> taos -h 192.168.244.3 -P 6030 -u root -p zyd123456

Welcome to the TDengine shell from Linux, Client Version:2.1.3.0
Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.

taos> show databases;
name | created_time | ntables | vgroups | replica | quorum | days | keep | cache(MB) | blocks | minrows | maxrows | wallevel | fsync | comp | cachelast | precision | update | status |
====================================================================================================================================================================================================================================================================================
test | 2021-06-23 17:35:58.613 | 5 | 1 | 1 | 1 | 10 | 3650 | 16 | 6 | 100 | 4096 | 1 | 3000 | 2 | 0 | ms | 0 | ready |
log | 2021-06-23 11:41:02.502 | 4 | 1 | 1 | 1 | 10 | 30 | 1 | 3 | 100 | 4096 | 1 | 3000 | 2 | 0 | us | 0 | ready |
power | 2021-06-29 21:00:19.309 | 10000 | 2 | 1 | 1 | 5 | 3650 | 16 | 4 | 100 | 4096 | 1 | 3000 | 2 | 0 | ms | 0 | ready |
Query OK, 3 row(s) in set (0.056000s)

taos> use log;
Query OK, 0 of 0 row(s) in database (0.006000s)

taos> show tables;
table_name | created_time | columns | stable_name | uid | tid | vgId |
==========================================================================================================================================================
acct_root | 2021-06-23 11:41:02.520 | 22 | acct | 562950003756663 | 3 | 2 |
dn1 | 2021-06-23 11:41:02.518 | 15 | dn | 562949986979119 | 2 | 2 |
slowquery | 2021-06-23 11:41:02.522 | 5 | | 562950020534135 | 4 | 2 |
log | 2021-06-23 11:41:02.511 | 4 | | 562949970201317 | 1 | 2 |
Query OK, 4 row(s) in set (0.041000s)

taos> select * from log;

DB error: Unable to establish connection (12.051000s)



在 2021-07-01 09:12:10，"zyd200888" ***@***.***> 写道：

PS C:\TDengine> taos -n client -h 192.168.244.3 -P 6030 -u root -p zyd123456
07/01 09:11:13.813000 00010476 UTL work as client, host:192.168.244.3 startPort:6030 endPort:6041 pkgLen:1000

07/01 09:11:13.816000 00010476 UTL server ip:192.168.244.3 is resolved from host:192.168.244.3
successed to test TCP port:6030


现在 没有-e 的参数呀



At 2021-07-01 09:08:25, "zyd200888" ***@***.***> wrote:

PS C:\TDengine> taos -V
version: 2.1.3.0
PS C:\TDengine> taos -n client -h 192.168.244.3 -P 6030 -e 6042 -l 1000
wrong options
taos shell is used to test the TDengine database
-h
TDengine server FQDN to connect. The default host is localhost.
-p
The password to use when connecting to the server.
-P
The TCP/IP port number to use for the connection
-u
The user name to use when connecting to the server.
-A
The user auth to use when connecting to the server.
-c
Configuration directory.
-C
Dump configuration.
-s
Commands to run without enter the shell.
-r
Output time as unsigned long..
-f
Script to run without enter the shell.
-d
Database to use when connecting to the server.
-t
Time zone of the shell, default is local.
-n
Net role when network connectivity test, default is startup, options: client|server|rpc|startup|sync.
-l
Packet length used for net test, default is 1000 bytes.
-V
Print program version.
PS C:\TDengine>

按照官方的档是操作的，指令完全不能识别呀，文档是不是很久没更新了



在 2021-06-30 23:25:17，"Shuduo Sang" ***@***.***> 写道：

现象上很像是 TCP 不通导致的。可以参考一下 FAQ 相关部分 https://www.taosdata.com/cn/documentation/faq

**Comment by sangshuduo** [comment]
@zouyadong008 你试试用 fqdn，在 windows/system32/drivers/etc/hosts 里添加对 IP 的映射。Linux 端先把数据删掉，/etc/taos.cfg 里用 fqdn，重新起服务端

**Comment by zouyadong008** [comment]
好的



在 2021-07-01 09:33:26，"Shuduo Sang" ***@***.***> 写道：

@zouyadong008 你试试用 fqdn，在 windows/system32/drivers/etc/hosts 里添加对 IP 的映射。Linux 端先把数据删掉，/etc/taos.cfg 里用 fqdn，重新起服务端

**Comment by zouyadong008** [comment]
我解决了，但不你这个方法，你们官网的文档要更新一下了 重点是在第3条，你们一直在引导用户做无用功。还是要感谢你们的用心解答，真心希望你们的产品越来越好。



解决方案如下：
1.clients需要配置FQDN /etc/hosts 里面配置192.168.128.160 td1.
2.server端修改主机的名字，/etc/hostname 中添加td1
3.server端修改/var/lib/taos/dnode/下的dnodeEps.json，mnodeEpSet.json中的localhost替换为修改过的hostname td1.
4.重启之后，发现windows client能够成功连接server，并能够进行select * from table; 和select count(*) from table; 操作。















在 2021-07-01 09:33:26，"Shuduo Sang" ***@***.***> 写道：

@zouyadong008 你试试用 fqdn，在 windows/system32/drivers/etc/hosts 里添加对 IP 的映射。Linux 端先把数据删掉，/etc/taos.cfg 里用 fqdn，重新起服务端
