### ISSUE TITLE
能够提供与Java结合更好的例子？

### ISSUE THREAD

**Issue by coder-chriswang** [taosdata/TDengine#67]
@jtao1735 陶老师，您好！
上午花了一个小时。完成编译安装，已经TDengine跑起来，上手操作了。
但看完指导文档之后，文章中提到的有关Java的，taos-jdbcdriver-1.0.0-dist.jar和demo工程以及订阅相关的例子，个人觉得指导性还是感觉平淡了些。
能够结合时下生态良好的SpringBoot给出好的结合例子？
这样子，连接TSDB之后，完整地完成一个对数据入库，查询展示的。
个人建议，谢谢！

**Comment by coder-chriswang** [comment]
![image](https://user-images.githubusercontent.com/40193732/61274974-7b519300-a7df-11e9-985e-9d3917a47ec7.png)

**Comment by hjxilinx** [comment]
没有找到libtaos.so文件，在 .bash_profile 或 .bashrc 文件中添加libtaos.so的所在目录。如果libtaos.so在/usr/lib目录下，添加该目录到LD_LIBRARY_PATH环境变量中：
export LD_LIBRARY_PATH=.:/usr/lib/:/usr/local/lib:$LD_LIBRARY_PATH.

然后执行：source ~/.bash_profile 或 source ~/.bashrc
在某些版本的CentOS上会有这个问题。

**Comment by hjxilinx** [comment]
对于与springboot整合的例子我们后续会整理发布出来，
一个比较典型的应用，您可以参考一下：
https://www.taosdata.com/blog/2019/07/10/使用tdengine快速搭建运维监测系统/

**Comment by coder-chriswang** [comment]
@hjxilinx 您好！很高兴能得到您的回复！
libtaos.so目前在/usr/lib目录下，但我没有明白您所指的添加路径是怎么一回事
是直接将export LD_LIBRARY_PATH=.:/usr/lib/:/usr/local/lib:$LD_LIBRARY_PATH.
添加到如下文件中吗?
![image](https://user-images.githubusercontent.com/40193732/61289156-45220c80-a7fb-11e9-8078-160be0d84802.png)

**Comment by coder-chriswang** [comment]
@hjxilinx 按照官方文档中执行命令，找不到
![image](https://user-images.githubusercontent.com/40193732/61338904-15f8b300-a86e-11e9-8c12-09a34b567bc7.png)

**Comment by coder-chriswang** [comment]
@hjxilinx 请问能解释指导一下吗，谢谢！

**Comment by hjxilinx** [comment]
@coder-chriswang, sorry for the inconvenience.
pdf中的操作步骤不适用编译开源代码。
您需要按照github上的README上的步骤进行操作。抱歉！
在源代码目录中按一下步骤执行：
mkdir build && cd build
cmake .. && cmake --build .

是把libtaos.so路径放在.bash_profile中。完成以后还要执行 source ~/.bash_profile 
看图：
![snap](https://user-images.githubusercontent.com/8252296/61436355-3196b300-a96d-11e9-8da7-dbb9cdc3ceeb.png)
