### ISSUE TITLE
no taos.cfg configuration file in docker

### ISSUE THREAD

**Issue by qq289736032** [taosdata/TDengine#6701]

**Comment by qq289736032** [comment]
![image](https://user-images.githubusercontent.com/25926714/124062110-c0ba0a00-da62-11eb-9c73-93acd8ac3b50.png)

**Comment by jtcheng** [comment]
最新的`docker` 镜像可以工作，没能复现你说的问题：
```
$ docker image ls | grep tdengine
tdengine/tdengine         latest       d5954c7e35b9   22 hours ago    148MB

$ docker container run -d tdengine/tdengine
8ca23bad92a8ee0d23251301fd42158d9c2a0b46d24d829a90bf2bfe75ff33be

$ docker container exec -it 8ca23 /bin/bash
root@8ca23bad92a8:~/TDengine-server-2.1.3.2# ls -l /etc/taos/taos.cfg
-rw-r--r-- 1 root root 8015 Jun 30 09:16 /etc/taos/taos.cfg
root@8ca23bad92a8:~/TDengine-server-2.1.3.2#
```

**Comment by qq289736032** [comment]
> 最新的`docker` 镜像可以工作，没能复现你说的问题：
> 
> ```
> $ docker image ls | grep tdengine
> tdengine/tdengine         latest       d5954c7e35b9   22 hours ago    148MB
> 
> $ docker container run -d tdengine/tdengine
> 8ca23bad92a8ee0d23251301fd42158d9c2a0b46d24d829a90bf2bfe75ff33be
> 
> $ docker container exec -it 8ca23 /bin/bash
> root@8ca23bad92a8:~/TDengine-server-2.1.3.2# ls -l /etc/taos/taos.cfg
> -rw-r--r-- 1 root root 8015 Jun 30 09:16 /etc/taos/taos.cfg
> root@8ca23bad92a8:~/TDengine-server-2.1.3.2#
> ```

我是昨天拉取下来的镜像

**Comment by qq289736032** [comment]
> 最新的`docker` 镜像可以工作，没能复现你说的问题：
> 
> ```
> $ docker image ls | grep tdengine
> tdengine/tdengine         latest       d5954c7e35b9   22 hours ago    148MB
> 
> $ docker container run -d tdengine/tdengine
> 8ca23bad92a8ee0d23251301fd42158d9c2a0b46d24d829a90bf2bfe75ff33be
> 
> $ docker container exec -it 8ca23 /bin/bash
> root@8ca23bad92a8:~/TDengine-server-2.1.3.2# ls -l /etc/taos/taos.cfg
> -rw-r--r-- 1 root root 8015 Jun 30 09:16 /etc/taos/taos.cfg
> root@8ca23bad92a8:~/TDengine-server-2.1.3.2#
> ```

配置文件挂载的时候，宿主机和容器内都找不到该文件

**Comment by jtcheng** [comment]
```
docker container run -d  -v /Users/jtcheng/test:/etc/taos tdengine/tdengine
$ docker container exec -it fc3655 /bin/bash
root@fc3655a741b1:~/TDengine-server-2.1.3.2# ls /etc/taos/
taos.cfg  taos.cfg1
```
`-v /Users/jtcheng/test:/etc/taos` use absolute path, you can see that I added  one more file ` taos.cfg1` to that directory.

**Comment by yu285** [comment]
没有配置文件会选取默认的参数配置，如果需要可以在本地指定然后映射。
