### ISSUE TITLE
JDBC connection issue 

### ISSUE THREAD

**Issue by zouyadong008** [taosdata/TDengine#6715]
最开是
jdbc:TAOS-RS 是可以正常连接使用
jdbc:TAOS 不可以
我费了一天的时间解决了jdbc:TAOS连接成功无法查询和插入的问题，结果jdbc:TAOS-RS 直接就连接不上报  {"status":"error","code":11,"desc":"Unable to establish connection"}，真是无语了，吹的这么牛，结果用户就在测试阶段就碰到各种坑。

**Comment by jjhgxk** [comment]
我也差不多 我都不敢深入使用

**Comment by zyyang-taosdata** [comment]
建议你把错误信息写清楚一点，比如你url是怎么写的

**Comment by yu285** [comment]
请您提供一下具体信息，确保自己的基础配置无误，如果已经成功使用麻烦通知我们关闭issue。如果没有使用成功，可以添加微信15652223354做具体排查
