### ISSUE TITLE
 Why the capitalized column name will be converted to lowercase？ shall we keep using capital letter?

### ISSUE THREAD

**Issue by zouyadong008** [taosdata/TDengine#6716]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the circumstance is and what the associated problem is. Ex. I'm using TDengine for this use case: [...]. But I'm always frustrated when [...]

**Describe your desired behavior**
A clear and concise description of what you want to happen. Ex. I want TDengine to be able to do [...] when I try to do [...] with it.

**Describe your solutions/suggestions if you've any**
A clear and concise description of any solutions/suggestions to this problem or features you've considered.

**Additional context**

**Comment by yu285** [comment]
TDengine的使用对于大小写不敏感，您可以用大写使用
