### ISSUE TITLE
Taosd is unable to start due to the frequent up and down

### ISSUE THREAD

**Issue by jjhgxk** [taosdata/TDengine#6718]
问题情况:由于启动频繁,导致了服务端无法正常启动,我等待了三四个小时,想重启启动,还是有这样的情况, 提示下面一段话 但是按照操作并没有有  输入Systemctl status taosd 首先状态是failed 其次下面有一段话就是request start too quick,
![image](https://user-images.githubusercontent.com/62579413/124209682-96c51e00-db1c-11eb-8d69-fcda8c7d6317.png)
 想请问 遇到这样的情况 该如何操作 启动这块是不是设置了启动策略

**Comment by yu285** [comment]
等待一会再启动不能解决问题吗？
