### ISSUE TITLE
SHOW STABLES LIKE  'xxx'  issue

### ISSUE THREAD

**Issue by Cutie-Sakura** [taosdata/TDengine#6722]
使用版本 TDengine-server-2.1.0.0;

 # 前提条件 

执行
> SHOW STABLES
>> 有如下13个表
1. stable_6816f32b_9d79_4ca3_9820_0236f61e7267_warning,1621220504220,6,7,2
2. stable_6816f32b_9d79_4ca3_9820_0236f61e7267_measured,1621220504206,6,7,2
3. stable_f6bdafeb_3f37_49d6_b40f_3274c1c32d99_measured,1625120923599,3,7,1
4. stable_9aeca69e_c2be_41a9_beda_a8f0dc1bcdf4_position,1625194419501,5,7,1
5. stable_f4d197f2_b5e9_471a_b8d4_2c8f74de459c_position,1625121696893,5,7,2
6. stable_f4d197f2_b5e9_471a_b8d4_2c8f74de459c_measured,1625121696880,5,7,2
7. stable_9aeca69e_c2be_41a9_beda_a8f0dc1bcdf4_warning,1625194419511,6,7,1
8. stable_6816f32b_9d79_4ca3_9820_0236f61e7267_position,1621220504214,5,7,2
9. stable_f6bdafeb_3f37_49d6_b40f_3274c1c32d99_warning,1625120923679,6,7,1
10. stable_f6bdafeb_3f37_49d6_b40f_3274c1c32d99_position,1625120923656,5,7,1
11. stable_f4d197f2_b5e9_471a_b8d4_2c8f74de459c_warning,1625121696902,6,7,2
12. event,1621221538790,34,3,6
13. stable_9aeca69e_c2be_41a9_beda_a8f0dc1bcdf4_measured,1625194419480,4,7,1

# 正常的查询 

执行
> SHOW STABLES LIKE  "stable_%_measured"
 显示

1. stable_6816f32b_9d79_4ca3_9820_0236f61e7267_measured
2. stable_f6bdafeb_3f37_49d6_b40f_3274c1c32d99_measured
3. stable_f4d197f2_b5e9_471a_b8d4_2c8f74de459c_measured
4. stable_9aeca69e_c2be_41a9_beda_a8f0dc1bcdf4_measured

正常

 执行
> SHOW STABLES LIKE  "stable_%_position"
 显示

1. stable_9aeca69e_c2be_41a9_beda_a8f0dc1bcdf4_position
2. stable_f4d197f2_b5e9_471a_b8d4_2c8f74de459c_position
3. stable_6816f32b_9d79_4ca3_9820_0236f61e7267_position
4. stable_f6bdafeb_3f37_49d6_b40f_3274c1c32d99_position

正常

# bug出现的地方

执行

>> sql 中的空格是 提交bug时候加的,否则github显示的sql 与实际运行不一致

 SHOW STABLES LIKE  "stable _ % _ warning"
 显示
没有数据 
SHOW STABLES LIKE  "stable _ % _ warning"
[2021-07-02 17:08:26] 0 rows retrieved in 33 ms (execution: 8 ms, fetching: 25 ms)

 执行 SHOW STABLES LIKE  "stable%warning"
 SHOW STABLES LIKE  "stable%warning"
[2021-07-02 17:08:50] 4 rows retrieved starting from 1 in 29 ms (execution: 6 ms, fetching: 23 ms)
显示

1. stable_6816f32b_9d79_4ca3_9820_0236f61e7267_warning
2. stable_9aeca69e_c2be_41a9_beda_a8f0dc1bcdf4_warning
3. stable_f6bdafeb_3f37_49d6_b40f_3274c1c32d99_warning
4. stable_f4d197f2_b5e9_471a_b8d4_2c8f74de459c_warning

才正常

**Comment by yu285** [comment]
我们确认一下

**Comment by yu285** [comment]
是这样，_本身就是另一个通配符，所以写成这样就可以了： show stables like  'stable\_%\_arning';

说明：可在like中使用通配符进行名称的匹配，这一通配符字符串最长不能超过24字节。
通配符匹配：1）’%’ (百分号)匹配0到任意个字符；2）’_’下划线匹配一个字符。

我们会在官网加上这块关于下划线转义描述。

**Comment by jtcheng** [comment]
@yu285
You can see the PR #6729 , this is the code logic error.
```
(gdb) b mnodeRetrieveShowSuperTables
(gdb) p *pShow
$1 = {db = "0.jtcheng", '\000' <repeats 34 times>, type = 7 '\a', numOfColumns = 5, index = 4, rowSize = 211, numOfRows = 14, pIter = 0x0, ppShow = 0x7fac28006d00, offset = {0, 195, 203, 205, 207, 0 <repeats 1019 times>}, bytes = {195,
    8, 2, 2, 4, 0 <repeats 1019 times>}, numOfReads = 0, maxReplica = 0 '\000', reserved0 = "", payloadLen = 16, payload = 0x7fac28004c78 "stable_%_warning\325\001"}
(gdb) p pattern
$2 = 0x7fac24001aa0 "stable_%_warning"
```
`payloadLen = 16, payload = 0x7fac28004c78 "stable_%_warning\325\001"`
The match pattern in server side use `stable_%_warning\325\001` instead of `stable_%_warning`, so you can not match anythings.
