### ISSUE TITLE
SQL state []; error code [-2147482828]; TDengine ERROR (80000334): Out of DNodes; nested exception is java.sql.SQLException: TDengine ERROR (80000334): Out of DNodes

### ISSUE THREAD

**Issue by lexang** [taosdata/TDengine#6730]
SQL state []; error code [-2147482828]; TDengine ERROR (80000334): Out of DNodes; nested exception is java.sql.SQLException: TDengine ERROR (80000334): Out of DNodes

springboot mybatis  创建子表报错

**Comment by cpvmrd** [comment]
请介绍下系统当前的节点数量、表的数量等信息。再描述下复现步骤。我们再来检查。
