### ISSUE TITLE
How can I check how much disk space the database occupies, the size of each table, and whether the data is compressed?

### ISSUE THREAD

**Issue by 3018diao** [taosdata/TDengine#6733]
How can I check how much disk space the database occupies, the size of each table, and whether the data is compressed?

**Comment by yu285** [comment]
数据压缩与否是通过comp参数控制的，默认情况下一定会被压缩的。可以进行一个自己简单的计算，计算自己的行长度和总行数。https://mp.weixin.qq.com/s/VyLc_3Au801zXTXUHrCyLw，这篇文章后面有计算压缩率的方法，也有看单独数据库占用大小的方法。

具体到单表大小，目前还没有
