### ISSUE TITLE
taos connect failed, reason: Invalid client version.

### ISSUE THREAD

**Issue by zjjstart** [taosdata/TDengine#6740]
**Screenshots**
![image](https://user-images.githubusercontent.com/38005711/124416336-574f3980-dd89-11eb-8ff7-fd7ccbbbedae.png)

![image](https://user-images.githubusercontent.com/38005711/124416089-caa47b80-dd88-11eb-98a1-cd329dc55824.png)

接盘侠刚接手这个服务
其中开发环境的服务登录不进去,报这个错误
跪求大佬帮忙看看这是咋回事啊
taos 的服务版本应该是2.0.4.0这个版本

**Comment by cpvmrd** [comment]
确认下客户端版本，看来是客户端版本和服务器版本不一致。

**Comment by yu285** [comment]
您好，请问问题解决了吗

**Comment by yu285** [comment]
如果还有问题，请添加微信15652223354做技术支持
