### ISSUE TITLE
TAOS-RS write err: TDengine ERROR (60e): Invalid creation of table

### ISSUE THREAD

**Issue by PascalMing** [taosdata/TDengine#6755]
**Bug Description**
采用TAOS-RS写入数据时，可能写入失效，报“TDengine ERROR (60e): Invalid creation of table”错误。
sql单独在taos执行和采用TAOS执行正常

SQL：
INSERT INTO taos_c004  USING opc_loger.log_kafka2taos TAGS ('c004','Opc-C004') VALUES ('2021-07-06 13:33:50.0050',25564,145400,2976,698,1305,5,968,'2021-07-06 13:33:49.362');

库与超级表
CREATE DATABASE IF NOT EXISTS opc_loger keep 365;
CREATE TABLE IF NOT EXISTS log_kafka2taos (ts timestamp, pid int,total BIGINT,cycle int,iotint int,iotfloat int,iotstring int,iotbool int,kafkats timestamp) TAGS (factory binary(32) ,topic binary(32));

JAVA代码：
        Statement stmt = null;
        stmt = con.createStatement();
        stmt.executeUpdate(sql);

Environment (please complete the following information):**
 - Taos OS: Centos8
 - Dev：Win10,Java
 - TDengine Version 2.1.3.2
 - taos-jdbcdriver 2.0.32

**Comment by yu285** [comment]
我们复现一下

**Comment by aiuni** [comment]
你好，请问这个问题解决了吗？我和你遇到了同样的问题，代码中执行报错，打印的SQL在taos正常执行并执行成功。

**Comment by aiuni** [comment]
> 你好，请问这个问题解决了吗？我和你遇到了同样的问题，代码中执行报错，打印的SQL在taos正常执行并执行成功。

我解决了。因为我配置数据源连接的数据库，和语句指定的超级表所在的数据库不一致。
