### ISSUE TITLE
maximum session is reached

### ISSUE THREAD

**Issue by jtao1735** [taosdata/TDengine#677]
**Bug Description**
No client can connect to server since no free sessions available

**To Reproduce**
1. use a not existing user name to connect to server
2: the server will return an error
3: client connects to server again, and try a few thousand times.

**Comment by hjxilinx** [comment]
The corresponding fix patch is [77b20bf](https://github.com/taosdata/TDengine/commit/77b20bf138369b5ffef40c1f1a094771329950c7)
