### ISSUE TITLE
restfulapi get url http://127.0.0.1:6041/rest/login/root/taosdata, sometime return 400  (Bad Request)

### ISSUE THREAD

**Issue by mockte** [taosdata/TDengine#6770]
restfulapi get url http://127.0.0.1:6041/rest/login/root/taosdata, sometime return 400  (Bad Request),

{status: "error", code: 4354, desc: "invalid url format"}
code: 4354
desc: "invalid url format"
status: "error"

GET http://127.0.0.1:6041/favicon.ico 400 (Bad Request)

**Comment by yu285** [comment]
which version?
