### ISSUE TITLE
使用go驱动安装goclient运行不成功

### ISSUE THREAD

**Issue by ypyaaa** [taosdata/TDengine#6776]
在代码中引入TDengineclient 包去连接TdEngineserver不成功 
报错
![image](https://user-images.githubusercontent.com/19565638/124696262-4af8e700-df17-11eb-9a8f-2d42795763de.png)
client 版本 2.0.10.0 
server 版本  2.0.10.0 
go 版本 1.16.3
引入go module 版本 github.com/taosdata/driver-go v0.0.0-20210706085040-976d33c51c3d

**Comment by sangshuduo** [comment]
TDengine 版本太老了

**Comment by ypyaaa** [comment]
> TDengine 版本太老了

![image](https://user-images.githubusercontent.com/19565638/124713248-e481c200-df32-11eb-93df-18c2a51f2259.png)
升到2.1.3.2 报错Unable to establish connection 检查端口如上图所示

**Comment by ypyaaa** [comment]
> TDengine 版本太老了



> TDengine 版本太老了

![image](https://user-images.githubusercontent.com/19565638/124719290-915f3d80-df39-11eb-9379-9a84236c655d.png)
![image](https://user-images.githubusercontent.com/19565638/124719366-a340e080-df39-11eb-8cb6-def13fd33b2d.png)

在windows下连续查询两次失败一次成功返回数据 这是什么原因呢。。。

**Comment by sangshuduo** [comment]
要看失败时的 log 才能确定

**Comment by ypyaaa** [comment]
> 要看失败时的 log 才能确定

可以close掉了 连接还未初始化    去插入的时候 报这个错
