### ISSUE TITLE
2.0.31 jdbc driver error

### ISSUE THREAD

**Issue by qiuyan0528** [taosdata/TDengine#6782]
直接运行springbootdemo例子，将驱动改成2.0.31版本，报错。

![image](https://user-images.githubusercontent.com/252830/124712246-a59f3c80-df31-11eb-842d-b82adca52e5e.png)

命令行连接正常
![image](https://user-images.githubusercontent.com/252830/124712318-bfd91a80-df31-11eb-9d0d-5ba1a3cfb062.png)

程序启动报错
![image](https://user-images.githubusercontent.com/252830/124712082-7092ea00-df31-11eb-8279-d3913838335e.png)
![image](https://user-images.githubusercontent.com/252830/124712144-80123300-df31-11eb-89df-fd3bca6b9c8c.png)

**Comment by yu285** [comment]
请留意下官网的版本匹配信息：JDBC 2.0.31要和数据库2.1.3.0以上配合使用
