### ISSUE TITLE
cluster node offline status

### ISSUE THREAD

**Issue by Angle-bo** [taosdata/TDengine#6786]
服务版本2.1.3.2
![image](https://user-images.githubusercontent.com/16486675/124724721-d3d74900-df3e-11eb-8d05-a2fb0730b3b2.png)
![image](https://user-images.githubusercontent.com/16486675/124724809-e3ef2880-df3e-11eb-82a3-5e8ea605827c.png)
在主节点上shell查看集群节点
![image](https://user-images.githubusercontent.com/16486675/124724863-f5d0cb80-df3e-11eb-9602-35d4ffdbfac8.png)
搭建感觉好繁琐，没有mysql，redis，Hadoop这种那么容易啊。

**Comment by yu285** [comment]
配置问题阅读文档可以解决的，您可以加我微信——15652223354帮您看下
