### ISSUE TITLE
what's the plan for MQTT integration

### ISSUE THREAD

**Issue by masterchen** [taosdata/TDengine#68]
what's the plan for MQTT integration

**Comment by jtao1735** [comment]
MQTT is in our priority list, we will integrate it soon.

**Comment by masterchen** [comment]
sounds good ,if you have exact release date that will be more professional

**Comment by guanshengliang** [comment]
Please send your request to a slguan@taosdata.com, so that we can optimize the design and start develop

**Comment by guanshengliang** [comment]
My colleague @liu0x54  will be responsible for writing this part of the code. 
If you have any questions, you can consult him

**Comment by liu0x54** [comment]
Hi, actually we have solution to import MQTT data into TDengine now.
Please describe your data format and let's see if it can be imported into TDengine.
