### ISSUE TITLE
IDEA Database bug

### ISSUE THREAD

**Issue by Angle-bo** [taosdata/TDengine#6802]
服务版本：2.1.3.2
jdbc驱动版本：2.0.32或2.0.31
![image](https://user-images.githubusercontent.com/16486675/124857437-e6a15a80-dfde-11eb-9c3b-59330974c48d.png)
使用console查询没问题，可视化工具报错
![image](https://user-images.githubusercontent.com/16486675/124857146-5cf18d00-dfde-11eb-9bbb-f0f5d121a0e2.png)

问题二：
同样的插入数据命令，console里报错，是需要特殊配置什么吗？
![image](https://user-images.githubusercontent.com/16486675/124857573-1ea89d80-dfdf-11eb-98f6-590455625a75.png)
![image](https://user-images.githubusercontent.com/16486675/124857755-75ae7280-dfdf-11eb-9264-53e7bf8994b8.png)

**Comment by yu285** [comment]
https://github.com/taosdata/TDengine/issues/6602

您看看这个能帮助您吗
