### ISSUE TITLE
com.taosdata.jdbc.rs.RestfulPreparedStatement.clearParameters null Pointer exception issue

### ISSUE THREAD

**Issue by ntucz** [taosdata/TDengine#6809]
![image](https://user-images.githubusercontent.com/22786757/124890123-4f51fc80-e00a-11eb-96fc-e34994f5d3ff.png)
当输入参数没有任何查询条件的时候，会在com.taosdata.jdbc.rs.RestfulPreparedStatement.clearParameters的213行抛出空指针，这里需要做一个判空。

**Comment by yu285** [comment]
感谢您的贡献，可以加您微信吗？我拉您进我们的贡献者群。我的微信15652223354
