### ISSUE TITLE
performance issue of TDengine

### ISSUE THREAD

**Issue by SCY-ICT** [taosdata/TDengine#6819]
我有一张超级表，数据量为5千万左右，有的条件去查询超级表的时候特别慢

select * from gc_event_super where  event_id =103 and event_level =1 and handleType =2 limit 10
这条sql执行的时间平均在2.多秒

但是当这张超级表中只有5条event_id 为108的数据，这条sql的执行时间为200多秒

请问如何解决
还有就是如果不直接查询子表的话，如何能将查询速度控制在50ms以内

**Comment by yu285** [comment]
数据库版本是哪个？此外，查询性能比较复杂，涉及集群架构和数据建模，所以可能微信沟通更好一些

可加：15652223354
