### ISSUE TITLE
questions about restful configuration

### ISSUE THREAD

**Issue by xueshan007050** [taosdata/TDengine#682]
**General Questions**
1、http配置请求能否有详细示例。
在centos 8上配置了涛思数据库后，创建了taosdemo后，在浏览器里输入
http://127.0.0.1:6020/rest/test  返回的是error提示没有验证
{"status":"error","code":1011,"desc":"no auth info input"}
http时在那里输入用户名和密码？
2、在taos.cfg中有配置两个参数
a、# internalIp            127.0.0.1
internallp 如果有10个IP地址，怎么书写方法？
b、# client local IP
# localIp               127.0.0.1
client ip，客户端IP也都需要在这里标明吗？如果有30个客户端怎么表示，能否示意？
3、如果在window上连接centos服务器端的涛思数据库，windows上作为客户端，windows需要安装软件吗？

**Comment by guanshengliang** [comment]
通过basic authentication方法进行身份验证

**Comment by xiangxud** [comment]
我用grafana测试数据源也没测试通，具体是怎么回事啊

**Comment by guanshengliang** [comment]
在windows或者linux等平台上，通过restful接口访问时，只需要开6020端口
在windows64平台上，下载client，官网上有下载链接，下载之后关闭防火墙，即可访问
localIp和restful接口没有关联，localIp不需要配置，仅在需要指定通讯端口时才需要

**Comment by xiangxud** [comment]
Ok,云服务平台要开端口

**Comment by guanshengliang** [comment]
From the feedback, the problem has been resolved, so we close it
