### ISSUE TITLE
  when count(1)=0,TDengine show "0 row(s) in set " which would lead to "NullPointerExecption" in Mybatis

### ISSUE THREAD

**Issue by xForMe** [taosdata/TDengine#6823]
![image](https://user-images.githubusercontent.com/8530198/125067494-ebe9cc80-e0e6-11eb-8ce8-b15d620f2209.png)

查询为空的时候直接返回0记录，会导致mybatis 抛出NullPointerException
![image](https://user-images.githubusercontent.com/8530198/125067689-29e6f080-e0e7-11eb-8e00-c16deb0ad4bf.png)

**Comment by yu285** [comment]
产品最初设计的时候就是这样，其他时序数据库也有如此设计，这一点我们可以优化。

**Comment by xForMe** [comment]
这个在哪个版本会发布
