### ISSUE TITLE
centos6.5 in TDengine-Server service taosd start error

### ISSUE THREAD

**Issue by twenty-threes** [taosdata/TDengine#6841]
[root@vm-ggs TDengine-server-2.0.20.9]# service taosd start
/etc/init.d/taosd: line 38: log_action_begin_msg: command not found

**Comment by sangshuduo** [comment]
Would you mind to upgrade CentOS to 7.x?

**Comment by twenty-threes** [comment]
> Would you mind to upgrade CentOS to 7.x?

不行，公司服务器

**Comment by sangshuduo** [comment]
@twenty-threes 是解决了所以关掉的吗？可以 sudo taosd -c /etc/taos & 的方式执行

**Comment by twenty-threes** [comment]
没有解决，使用

**Comment by twenty-threes** [comment]
没有解决，使用sudo taosd -c /etc/taos & 
sudo taosd -c /etc/taos &
[2] 21701
[root@vm-ggs TDengine-server-2.0.20.9]# taosd: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by taosd)
taosd: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/lib/libtaos.so.1)
[2]+  Exit 1                  sudo taosd -c /etc/taos
[root@vm-ggs TDengine-server-2.0.20.9]# taos
taos: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by taos)
taos: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/lib/libtaos.so.1)

**Comment by twenty-threes** [comment]
service taosd status 显示也不对劲：
[root@vm-ggs TDengine-server-2.0.20.9]# service taosd status
/etc/init.d/taosd: line 81: status_of_proc: command not found

**Comment by sangshuduo** [comment]
需要自己编译

**Comment by twenty-threes** [comment]
编译? 请问是需要升级glibc吗，glibc最低配置为2.14?

**Comment by sangshuduo** [comment]
我们不在太老的系统上做验证，所以不太确定会不会有问题，但是道理上应该不用升级 glibc，但是不排除 gcc 版本太低有编译不过去的代码。

**Comment by sangshuduo** [comment]
closed as long time no response. please open it if still need help.
