### ISSUE TITLE
Docker  repository issue

### ISSUE THREAD

**Issue by baabaaox** [taosdata/TDengine#6848]
啊 怎么总是把已有的镜像删掉，这样搞很麻烦咧，每次都应为这个要去升级客户端驱动

**Comment by saiyn** [comment]
我都是push到自己的docker hub账号上的

**Comment by baabaaox** [comment]
@saiyn 思来想去，我打算切换成 RESTful API，现在这样部署太难受了，如果有变动根本没法自动化部署，编译还要先得去下载最新的驱动，最新的驱动呢还得填邮箱才能获取下载链接，必须要这样手动去更新文件后才能构建新镜像
