### ISSUE TITLE
tag is null 

### ISSUE THREAD

**Issue by sytpb** [taosdata/TDengine#6860]
ver 2.1.2 

 INSERT INTO sun.orders_corpid USING sun.orders TAGS ('corpid') (stamp,orderid)  VALUES (now,'1626242590293121');

![image](https://user-images.githubusercontent.com/12178686/125577951-13d64d5b-7fae-4cd3-8359-44d107fbbe8d.png)

**Comment by sytpb** [comment]
db update from 2.0.12 ,now app doesn't work ,hope a solution , thanks .

**Comment by sytpb** [comment]
close this issue , as i can't reproduct it .

**Comment by yu285** [comment]
后续有使用问题，可以添加我的微信15652223354
