### ISSUE TITLE
如何使用win10系统当作客户端连入集群?

### ISSUE THREAD

**Issue by xlkingdom** [taosdata/TDengine#6865]
在linux下建立好服务端之后，想在win10系统下构建一个客户端，taos.cfg中的firstEP和FQDN，hosts都按教程修改了，但始终连不上tdengine，一直提示taos connect failed, reason: Unable to establish connection. 。集群那块的文档只写了需要检查taosd是否启动，但本人不知道如何在win10下启动taosd。
ps：win10客户端这边和Linux服务端这边可以互相ping通，而且客户端和服务端两台电脑的防火墙都开放了6030-6042端口。

**Comment by yu285** [comment]
如有后续有其他使用问题，可以添加微信15652223354
