### ISSUE TITLE
 How to deploy the client on linux (32bit) system and then connect to the server which is on the 64bit system?

### ISSUE THREAD

**Issue by zhangshuyuanzz** [taosdata/TDengine#687]
请问一下，是否有支持32位linux系统的taos库呢？

---------------------
服务器是64位设备。客户端是32位Linux（X86）系统，单纯在想linux32系统上使用C语言连接服务器，想问下，依赖库在哪里能找到呢

**Comment by plum-lihui** [comment]
非常抱歉！现在我们不支持32位的系统。后续我们会发布支持ARM 32位的系统，但对X86不会发布32位的系统。

**Comment by zhangshuyuanzz** [comment]
> 非常抱歉！现在我们不支持32位的系统。后续我们会发布支持ARM 32位的系统，但对X86不会发布32位的系统。

不，服务器已经设置完成，我想了解下，x86的32位linux系统如何能够连接数据库？是否目前有解决方案呢

**Comment by fangpanpan** [comment]
x86 我们不打算支持32位的客户端，等arm版出来后我们可以32位client 去连64位服务端。

**Comment by plum-lihui** [comment]
> > 非常抱歉！现在我们不支持32位的系统。后续我们会发布支持ARM 32位的系统，但对X86不会发布32位的系统。
> 
> 不，服务器已经布置完成了。我想了解的是，x86的32位linux系统如何能够连接数据库？是否目前有解决方案呢
===========================================
我们只发布了X86的64位的客户端lib库，如果想在x86的32位linux链接tdengine服务的话，只能使用restful接口，具体的使用方式请看一下官方文档。多谢！

**Comment by duwenhua** [comment]
可否将windows 64位的客户端改成32位的客户端编译出来，目前确实还有很多x86的服务器在用，请予以支持，十分感谢！

**Comment by plum-lihui** [comment]
这个目前实在是没有人力来做这个工作了。你可以下载源码自己试试，有问题可以交流。
实在抱歉！



2849823933@qq.com
 
From: duwenhua
Date: 2019-11-17 22:14
To: taosdata/TDengine
CC: plum-lihui; Assign
Subject: Re: [taosdata/TDengine] How to deploy the client on linux (32bit) system and then connect to the server which is on the 64bit system? (#687)
可否将windows 64位的客户端改成32位的客户端编译出来，目前确实还有很多x86的服务器在用，请予以支持，十分感谢！

**Comment by duwenhua** [comment]
目前你们还没有公开windows 64位的客户端的源码，可否将windows  的客户端予以公开？

**Comment by plum-lihui** [comment]
开源代码就包含了客户端的源码，在windwos的vs里面编译就行。
请参考官网中一篇博客：
https://www.taosdata.com/blog/2019/07/26/%E5%A6%82%E4%BD%95%E7%BC%96%E8%AF%91tdengine%E7%9A%84windows%E5%AE%A2%E6%88%B7%E7%AB%AF/ 



2849823933@qq.com
 
From: duwenhua
Date: 2019-11-19 23:53
To: taosdata/TDengine
CC: plum-lihui; Assign
Subject: Re: [taosdata/TDengine] How to deploy the client on linux (32bit) system and then connect to the server which is on the 64bit system? (#687)
目前你们还没有公开windows 64位的客户端的源码，可否将windows 的客户端予以公开？

**Comment by plum-lihui** [comment]
开源就全部公开了啊。
https://www.taosdata.com/blog/2019/07/26/%E5%A6%82%E4%BD%95%E7%BC%96%E8%AF%91tdengine%E7%9A%84windows%E5%AE%A2%E6%88%B7%E7%AB%AF/



2849823933@qq.com
 
From: duwenhua
Date: 2019-11-19 23:53
To: taosdata/TDengine
CC: plum-lihui; Assign
Subject: Re: [taosdata/TDengine] How to deploy the client on linux (32bit) system and then connect to the server which is on the 64bit system? (#687)
目前你们还没有公开windows 64位的客户端的源码，可否将windows 的客户端予以公开？
