### ISSUE TITLE
Upgrade to Tdengine 2.1.3.0 (cluster), query statement error

### ISSUE THREAD

**Issue by IZ-ONE** [taosdata/TDengine#6874]
**Jdbc驱动版本：**
2.0.31
**Client版本：**
2.1.3.0
**服务器集群版本：**
2.1.3.0
**使用框架：**
SpringBoot+Mybatis
![QQ截图20210715164720](https://user-images.githubusercontent.com/49674640/125758626-c5daceb3-50c5-40f1-b74b-56d6b3eaac5d.png)

试了好几个查询Sql，都报这个错误(显示在时间条件附近有语法错误)，升级之前皆正常
升级之前的版本：服务端2.0.15 + Jdbc驱动2.0.18

**Comment by IZ-ONE** [comment]
我这边打断点发现源码中到调用native方法执行sql时，sql中的查询参数都没有加上相应的封闭符，如字符串、时间中该有的引号
![a](https://user-images.githubusercontent.com/49674640/125769622-9f4bd871-f058-494d-962e-71b131cf0ef1.png)

**Comment by yu285** [comment]
收到，我们看一下

**Comment by xleili** [comment]
您的mybatis版本是什么那？

**Comment by IZ-ONE** [comment]
> 您的mybatis版本是什么那？

**Mybatis** ：3.5.5
**Mybatis-Spring** : 2.0.5
