### ISSUE TITLE
Aggregated  query  issue in interval function

### ISSUE THREAD

**Issue by leoasc** [taosdata/TDengine#6875]
**Bug Description**
今天试了一下2.4.1版本，嵌套查询功能，包括对子查询进行group,已经比较完善了。
然后试了一下前面有问题的时间聚合插值，先是按小时聚合，结果正常。
`select last(*) from u_alarm where ts >='2020-12-31 00:00:00' and ts<='2021-01-01 00:00:00' group by deviceid interval(1h) fill(prev);`
![image](https://user-images.githubusercontent.com/45965121/125760012-391c9a5e-ef4e-4582-9a17-d7a696dd7612.png)

后面按天聚合，就出问题了，返回超时后查询服务节点挂了：
`taos> select last(*) from u_cmd where ts>='2020-12-15 00:00:00' and ts<='2021-01-01 00:00:00' interval(1d) fill(prev);

DB error: Unable to establish connection (8.316000s)`
`taos> show dnodes;
   id   |           end_point            | vnodes | cores  |   status   | role  |       create_time       |      offline reason      |
======================================================================================================================================
      1 | blyes1.taosdata.com:6030       |      1 |      4 | ready      | any   | 2020-12-23 22:01:10.369 |                          |
      2 | blyes2.taosdata.com:6030       |      1 |      4 | ready      | any   | 2020-12-23 22:05:15.609 |                          |
      3 | blyes3.taosdata.com:6030       |      2 |      4 | offline    | any   | 2020-12-23 22:05:21.527 | status msg timeout       |
Query OK, 3 row(s) in set (0.042000s)`

**Environment (please complete the following information):**

 - TDengine Version 2.4.1.0

**Comment by yu285** [comment]
请问这个问题是稳定复现吗？每次查询都会有这样的结果吗？

是不是单副本？

**Comment by leoasc** [comment]
@yu285 稳定复现，试过不同的表，只要按天填充都会出这个问题。按分钟、小时、甚至24小时都不会出现这个问题。有可能是单副本

**Comment by yu285** [comment]
这个问题我们已经在跟进了

**Comment by yu285** [comment]
> @yu285 稳定复现，试过不同的表，只要按天填充都会出这个问题。按分钟、小时、甚至24小时都不会出现这个问题。有可能是单副本

这个问题让客户端和服务端属于同一时区应该可以解决，麻烦试下
