### ISSUE TITLE
Asynchronous Python client on top of asyncio?

### ISSUE THREAD

**Issue by honglei** [taosdata/TDengine#6891]
Like aioinflux for InfluxDB: https://aioinflux.readthedocs.io/en/stable/
asyncpg for Postgresql : https://github.com/MagicStack/asyncpg

**Comment by zitsen** [comment]
Thanks for your contributing. I'm working on a refactoring of python connector, after refactoring, TDengine will support partially asyncchronous operations in python stage. And I'll take a look into asyncio, that would help, thanks.

**Comment by fenghuazzm** [comment]
This issue was closed because it has been inactive for too many days.
