### ISSUE TITLE
TDengine‘s  alert and subscribe functions

### ISSUE THREAD

**Issue by ntucz** [taosdata/TDengine#6892]
看了官网文档，
1. 报警功能必须结合AlertManager使用，可我的应用需要安装AlertManager干什么呢？
"receivers": {
    "alertManager": "http://127.0.0.1:9093/api/v1/alerts"
  }
这个写法太死了，receivers的配置为啥不能是自己应用的一个url，协商好通用的接收报文格式，自己应用接收到告警后，想怎么处理就怎么处理。

2. 订阅功能taos_subscribe  taos_consume  taos_unsubscribe 这3个api是C++接口，如果我用的是java开发怎么办？

**Comment by zyyang-taosdata** [comment]
The TDengine consists of the server, client, and alarm module. The Alert module is a tool provided by TDengine for data monitoring and alarm. It can monitor the changes of the data in the table. For specific usage, please refer to: https://github.com/taosdata/TDengine/blob/master/alert/README_cn.md

Alert pushes alerts to alertManager mainly in the hope of being compatible with Prometheus' ecology. If there are better suggestions for the alert module design, they can be discussed in the issue, and we will take suggestions from the community in our future releases

About using a subscription interface in Java, you can refer to: https://www.taosdata.com/cn/documentation/connector/java
---
TDengine包括：服务端、客户端、报警模块三部分。alert模块是TDengine提供的一个用于数据监控报警的工具，能够监测表中数据的变化，具体的用法请参考：https://github.com/taosdata/TDengine/blob/master/alert/README_cn.md

alert将报警信息推送到alertManager主要是希望能够兼容prometheus的生态，如果对于alert模块的设计有更好的建议，可以在issue中讨论，我们的未来的版本中会采纳来自社区的建议

关于在java中使用订阅接口，可以参阅：https://www.taosdata.com/cn/documentation/connector/java
