### ISSUE TITLE
 DB error: Invalid value in client 

### ISSUE THREAD

**Issue by zhang506281581** [taosdata/TDengine#6898]
**Bug Description**
对 TAOS 中某超级表做了**新增列**的操作, 新增列操作成功后对该超级表进行select或alter等操作时报 **DB error: Invalid value in client**

**To Reproduce**
1. 使用终端 '连接 taos 客户端'.并切换数据库
2. 输入 ' ALTER STABLE bms ADD COLUMN re NCHAR(10); ' 操作超级表
3. 报错: DB error: Invalid value in client (0.000894s)

**Expected Behavior**
超级表新增列后应可正常访问操作

**Screenshots**
![image](https://user-images.githubusercontent.com/31986422/126028643-fb1230ed-6b23-4645-a263-ba26d963d6f4.png)

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - TDengine Version [2.0.18]

**Comment by yu285** [comment]
您好，我使用2.0.18并未能复现这个情况，请您添加微信15652223354做具体排查
