### ISSUE TITLE
【文档吐槽专用】WE HATE BAD DOCUMENTATIONS!!! (Welcome to comment on our documents)

### ISSUE THREAD

**Issue by johnnyhou327** [taosdata/TDengine#690]
世界上没有完美的文档。这个置顶问题是吐槽TDengine文档的最好地方。
问卷调查传送门：[你对TDengine的文档满意吗](https://www.wjx.cn/jq/49418125.aspx)
请填花1分钟填写一下传送门中的问题，然后在楼下开始吐槽吧！

There is no perfect documentation in the world. This pinned issue is the best place that everyone criticize TDengine's documentation. 
Gate to the questionnaire: [Let's be mean to TDengine's documentation](https://www.wjx.cn/jq/49434466.aspx)
Please fill out the questionnaire for real quick and then share your opinions below!

**Comment by lst789** [comment]
程序示例太少；
对一些运行中的异常，解释说明不够；
文档不够详细。应该想国外的文档一样不厌其详，毕竟用户水平不一。

**Comment by zhuchunwu** [comment]
数据导入能不能写个demo，这个导入应该有一些需要注意的细节，现在的文档没有说明，导入不成功也不知道为什么

**Comment by Tyxiang** [comment]
建议按这个：
https://github.com/ruanyf/document-style-guide/blob/master/docs/structure.md
重新组织下文档的结构。
现在有点不知道吐哪的感觉。

**Comment by Tyxiang** [comment]
我先吐点低级错误，就是关于 RESTful Connector 章节，基本上跟 RESTful 没有一毛钱关系，应该改为 HTTP Connector 。

**Comment by Tyxiang** [comment]
再吐槽个看完文档以后感觉最棘手的问题：“到底咋安装呢？”

**Comment by LiangDaShi** [comment]
是， JAVA 的示例在 win10 上就跑不了

[JAVA Sample failed in win10 #775](https://github.com/taosdata/TDengine/issues/775)

**Comment by kingice** [comment]
怎么建表，引擎支持什么index，不支持什么，从哪找？毫无头绪。

**Comment by LiangDaShi** [comment]
先把他们官网上的文档看了
tdengine 在 sql 语句上有点想 mysql，但注意这个不是 mysql
超级表就没有关联查询，普通表有 （join 查询）
还有就是可以看下他们官网上的实例
实例列表
使用TDengine快速搭建车联网平台（强烈推荐）


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hello mars"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月28日(星期四) 下午2:38
收件人:&nbsp;"taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送:&nbsp;"lmaster"<407987823@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [taosdata/TDengine] 【文档吐槽专用】WE HATE BAD DOCUMENTATIONS!!! (Welcome to comment on our documents) (#690)




怎么建表，引擎支持什么index，不支持什么，从哪找？毫无头绪。

**Comment by genelet** [comment]
There is a GOLANG package for TDengine: https://github.com/genelet/taodbi
我的一个GO语言package，放在 GitHub上，欢迎大家使用。其中有不少使用说明。

**Comment by JulianZhao** [comment]
是否可以在文档中增加一些JOIN的说明，搜索整个文档就在一个地方提了一下。

```
在Join查询中，带前缀的*和不带前缀*返回的结果有差别， *返回全部表的所有列数据（不包含标签），带前缀的通配符，则只返回该表的列数据。
```

实际试用JOIN遇到很多错误提示，看来有很多限制，没有文档摸不着头脑：
```
DB error: invalid SQL: not support ordinary column join
DB error: invalid SQL: illegal column name
DB error: invalid SQL: tags in join condition not support binary/nchar types
DB error: invalid SQL: timestamp join condition missing
DB error: invalid SQL: = is expected in join expression
```

**Comment by zhuangQingGuang** [comment]
文档超级表页面，上面提到标签不能超过32个，下面又说标签总数不能超过6个？

**Comment by sangshuduo** [comment]
2.0 文档 https://www.taosdata.com/cn/documentation/ 请针对每个问题提交 issue
