### ISSUE TITLE
go driver has some problems

### ISSUE THREAD

**Issue by kitianFresh** [taosdata/TDengine#6901]
taos Sql/taos.go:21:10: fatal error: 'taos.h' file not found;

should i must download  this header file in my computer??  i use mac to run the  https://github.com/taosdata/driver-go/blob/develop/taosSql/driver_test.go

![image](https://user-images.githubusercontent.com/8846958/126031849-fe0b8259-6eb1-4f17-a713-50cbf723aa3e.png)

**Comment by sangshuduo** [comment]
It uses the cgo interface. So please make sure the header file and library (dylib extension on Mac) is well placed.
