### ISSUE TITLE
Insert get stuck and end up with an exception.

### ISSUE THREAD

**Issue by akingbr** [taosdata/TDengine#6905]
server( centos7， 2.0.18）
测试程序window（client也是2.018 x64）
驱动jdbc 2.0.18

下午测试connect ok。从官网抄了几个sql，测试写入：
           Statement stmt = connection.createStatement();
       //     stmt.executeUpdate("create database if not exists test");
         //   stmt.executeUpdate("create table if not exists tb (ts timestamp, temperature int, humidity float)");
            int affectedRows = stmt.executeUpdate("insert into test.tb values(now, 23, 10.3) (now + 1s, 20, 9.3);");//***
            ResultSet resultSet = stmt.executeQuery("select * from test.tb");
每次走到这都卡住，过不去，然后抛异常：

ERROR Message: TDengine Error: Unable to establish connection
ERROR Code: -2147483637
java.sql.SQLException: TDengine Error: Unable to establish connection
	at com.taosdata.jdbc.TSDBJNIConnector.executeQuery(TSDBJNIConnector.java:135)
	at com.taosdata.jdbc.TSDBStatement.executeUpdate(TSDBStatement.java:100)
	at test.taosi.TDEngineTemplate.test(TDEngineTemplate.java:60)
	at test.taosi.Startup.main(Startup.java:20)

执行创建库和表的sql，都ok。。。。为啥

**Comment by akingbr** [comment]
吧相同sql，复制到centos的taos客户端，可以插入

**Comment by akingbr** [comment]
吧jdbc，window-client linux-server 全部替换 2.0.20 版本
      //      int affectedRows = stmt.executeUpdate("insert into test.tb values(now, 23, 10.3)");
            ResultSet resultSet = stmt.executeQuery("select * from test.tb");
查询，和插入都还会卡住，走不下去，

**Comment by yu285** [comment]
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/74105241/126061055-d598672a-46c5-4305-aca4-be23b21239a9.png">

请根据官网的版本对应表使用jdbc，如果还是有类似问题，我们再看。

**Comment by yu285** [comment]
您好，问题解决了吗，如果没有可以添加15652223354——备注请加上github issue 号码

**Comment by kaybinwong** [comment]
环境一样，
taopy（2.1.0,、2.2.0）跟taoshell（2.4.0）在window10下一样的问题，
其他Linux客户端能正常查询。

win配置
```
# first fully qualified domain name (FQDN) for TDengine system
firstEp                   node2.mizar.com:6030
```

网络互通
![image](https://user-images.githubusercontent.com/5570216/147621059-099e4743-1e9b-4dc3-9e5f-caa57cda83ad.png)

windowns taoshell操作
![image](https://user-images.githubusercontent.com/5570216/147621688-57e7b53e-e75d-4db2-96a1-cdd61ee8ab34.png)

linux客户端操作
![image](https://user-images.githubusercontent.com/5570216/147621667-0e349e8c-63e0-472d-90ab-a2123350dcd8.png)

**Comment by kaybinwong** [comment]
fixed，应该是安装时配置了firstEp，但又没设置fqdn
