### ISSUE TITLE
testdemo has a bug! The location parameter is name as loction, please change to location.

### ISSUE THREAD

**Issue by ranningw** [taosdata/TDengine#6909]
**Bug Description**
testdemo has a bug! The location parameter is name as loction, please change to location.

testdemo里面有bug。 使用testdemo命令。完成后，在taos shell中查询**location**="beijing"的记录总条数：返回invalid operation。发现问题是建表时，location误写为loction。所以要使用**loction**="beijing"查询才可以得到正确的输出。

请涛思团队修改下！
谢谢！

by Ranning

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by sangshuduo** [comment]
谢谢指出，这就改

**Comment by sangshuduo** [comment]
最新代码已修复
