### ISSUE TITLE
import taos OSError:【Errno 2】No such file or directory:'/usr/lib/python2.7/site-packages/taos-1.4.15-py2.7.egg' 

### ISSUE THREAD

**Issue by ybobxx** [taosdata/TDengine#691]
centos7.5系统自带python2.7。从github下载Taos 的python客户端连接Taos, 安装后import taos时一直报错 OSError:【Errno 2】No such file or directory:'/usr/lib/python2.7/site-packages/taos-1.4.15-py2.7.egg'   我的服务器版本安装的是1.6.3.0版。而提示下载的python客户端是taos-1.4.15版。是不是必须客户端版本和服务器版本必须一致才能使用？另外，github下载的python客户端只有一个src/connector/python/linux/python2安装文件，能匹配最新版服务器连接时用吗？

**Comment by fangpanpan** [comment]
1. 客户端和服务器必须要版本一致，但这个不针对python connector
2. 请问您是如何安装tdengine 服务端和taos connector?
3. 您可以打开python ， import sys; print(sys.path), 在那些路径下看看能不能找到taos-1.4.15-*.egg
4. 您可以直接将python2/ 下面的taos 文件夹拷贝到当前目录，然后再import taos 试试？

**Comment by ybobxx** [comment]
2，我是通过pip install src/connector/python/[linux|windows]/python2/安装的
3，安装好后，在/usr/lib/python2.7/site-packages/下面能看到taos 和taos-1.4.15-py2.7.egg-info两个文件。但是import taos任然报错OSError:libtaos.so: cannot open shared object file: No such file or directory
4,将python2/下面taos文件夹直接拷贝到/usr/lib/python2.7/site-packages/下，import taos依旧同样错误OSError:libtaos.so:  cannot open shared object file: No such file or directory
怀疑是否是 python2客户端默认安装路径不对，python2无法找到taos路径。src/connector/python/[linux|windows]/python2/安装包内是否无法自动添加路径。

**Comment by fangpanpan** [comment]
> 
> 
> 2，我是通过pip install src/connector/python/[linux|windows]/python2/安装的
> 3，安装好后，在/usr/lib/python2.7/site-packages/下面能看到taos 和taos-1.4.15-py2.7.egg-info两个文件。但是import taos任然报错OSError:libtaos.so: cannot open shared object file: No such file or directory
> 4,将python2/下面taos文件夹直接拷贝到/usr/lib/python2.7/site-packages/下，import taos依旧同样错误OSError:libtaos.so: cannot open shared object file: No such file or directory
> 怀疑是否是 python2客户端默认安装路径不对，python2无法找到taos路径。src/connector/python/[linux|windows]/python2/安装包内是否无法自动添加路径。

关于第4点，我是指您可以将python 包拷贝到您执行Python命令或脚本的目录，如果这种情况下import taos 还是无法成功的话，那么就是python2无法找到taos 路径了

**Comment by ybobxx** [comment]
在/usr/lib 下面能找到libtaos.so，是不是系统没有自动调用taos的动态库，需要配置环境路径？

**Comment by fangpanpan** [comment]
> 
> 
> 在/usr/lib 下面能找到libtaos.so，是不是系统没有自动调用taos的动态库，需要配置环境路径？

如果您将tao文件夹直接拷贝过来import taos 能成功，现在又能找到libtaos.so， 那么如果报no such file or dirctory (不管是对libtao.so 还是taos) ，就是需要配置环境路径让系统找到了。

**Comment by ybobxx** [comment]
问题解决了，就是需要配置环境路径的问题。配置好环境路径后import taos成功。
