### ISSUE TITLE
testdemo has a bug! search groupID return invalid operation.

### ISSUE THREAD

**Issue by ranningw** [taosdata/TDengine#6910]
**Bug Description**
testdemo has a bug! search groupID return invalid operation.
 The groupID parameter is name as groupid, please change to groupID .

testdemo里面有bug。 使用testdemo命令。完成后，在taos shell中查询groupID="beijing"的记录：返回invalid operation。发现问题是建表时，groupID误写为groupid。所以要使用groupid=10查询才可以得到正确的输出。

**Comment by sangshuduo** [comment]
谢谢指出，这就改

**Comment by sangshuduo** [comment]
groupID 是 INT 型，这个没错
