### ISSUE TITLE
testdemo has a bug! search table t10 return invalid operation.

### ISSUE THREAD

**Issue by ranningw** [taosdata/TDengine#6912]
**Bug Description**
testdemo has a bug! search table t10 return invalid operation.

testdemo里面有bug。 使用testdemo命令。完成后，在taos shell中查询"对表 t10 按 10s 进行平均值、最大值和最小值聚合统计"的记录：返回invalid operation。
表10是什么？是groupID =10吗？

select avg(current), max(voltage), min(phase) from test.**t10** interval(10s);
返回invalid operation

请涛思团队修改下！
谢谢！

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by sangshuduo** [comment]
这里是文档修改有遗漏，现在的表名应该是 d10。groupID 是 tag

**Comment by Eliacy** [comment]
文档上把表名写错了。已经把线上文档修正为 d10 。添麻烦啦，不好意思～
