### ISSUE TITLE
taosd crash in the query

### ISSUE THREAD

**Issue by carlziess** [taosdata/TDengine#693]
**Bug Description**
taosd: /mnt/hgfs/work/TDengine/src/system/src/vnodeQueryImpl.c:1297: validateQueryRangeAndData: Assertion `(startKey >= pQuery->lastKey && startKey <= pQuery->ekey && pQuery->skey <= pQuery->lastKey && QUERY_IS_ASC_QUERY(pQuery)) || (startKey <= pQuery->lastKey && startKey >= pQuery->ekey && pQuery->skey >= pQuery->lastKey && !QUERY_IS_ASC_QUERY(pQuery))' failed.

**To Reproduce**
服务端在运行过程中因为oom被杀掉了，然后能正常拉起服务，但一查询就崩溃了

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: CentOS Linux release 7.6.1810 (Core) 
 - TDengine Version taos.1.6.2.2

**Additional Context**

**Comment by hjxilinx** [comment]
您使用的版本是什么?

**Comment by carlziess** [comment]
> 您使用的版本是什么?
taos.1.6.2.2

**Comment by hjxilinx** [comment]
您在github上拉取1.6.4.0的版本试一试，看如何。如果还是不行，请确认服务器日志打开的情况下，把查询发生错误时候的日志提供给我。hjliao@taosdata.com。谢谢
