### ISSUE TITLE
select with group by issue

### ISSUE THREAD

**Issue by xForMe** [taosdata/TDengine#6933]
这边好像对常量或者now这种函数不支持
![image](https://user-images.githubusercontent.com/8530198/126247455-8427d636-306f-46f8-a067-057389124397.png)

select last(ts) as ts,last(pressure) as pressure,last(temperature) as temperature,last(mass_flow_rate) as flow,device_id,draw_type,'01' as data_ts  from enn_iot  group by device_id,draw_type;

**Comment by yu285** [comment]
这个不是bug，这是因为你用了group by，前面都要使用聚合函数。

**Comment by xForMe** [comment]
> 这个不是bug，这是因为你用了group by，前面都要使用聚合函数。

那应该怎么写呢，我才可以加入这个常量呢

**Comment by yu285** [comment]
这个应该没什么办法，如果他是静态的数据，你就把它做成标签吧。
