### ISSUE TITLE
using C# Connector with Unity targeting WebGL

### ISSUE THREAD

**Issue by SeanNi1221** [taosdata/TDengine#6942]
I'm using Unity to build an IoT platform targeting WebGL platform. Environments :
Development: Unity 2019.4,    C#,     Windows10.
Application(Server): CentOS7, local TDengine database.

I Tried C# Connector. It worked perfectly in the Development environment, but failed to work in the Application environment, because it seems to be impossible to access taos.dll from the built WebGL files.

So I'm totally confused:
Should I try another one of the Connectors?  Or should I continue struggling with the C# connector and try Cross Compiling the taos.dll into C# or JS?

Please kindly give me a suggestion about this. Unity has massive users worldwide, and I didn't find any information on how to connect TDengine with Unity by now.
Thank you!

**Comment by sangshuduo** [comment]
Interesting topic. Sorry I can't provide any suggestion since I have no idea how to reproduce or verify with Unity/WebGL. Could you describe how to build a minimal demo app? May I know what's scenario and what benefit TDengine bring to you? Would you consider using RESTful to access TDengine?

**Comment by SeanNi1221** [comment]
Unity was design as a cross-platform game engine, but also widely used in manufacturer, healthcare, real world simulation and other vision-oriented scenarios because it can significantly accelerate the Graph and Physics simulation development processes.

The application I'm building has a full 3D interface representing the interior structure of a building with various categories of devices and sensors inside it.  Each node has an data panel showing it's value and history, detailes, etc. That's why I'm using Unity as the main SDK for the project. 
Since the 3D scene's scale can extend to a street block or a whole city with all the associated IoT nodes in the future, I decided to try TDengine as a superior data solution over Mysql and others.

In Unity you work like this:
1. Composite the 3d scenes and UI system inside the Unity Editor(running on Windows).
2. Code in C# using Unity Scripting API for every logic/behavior, then Compile everything inside the Unity Editor.
3.Choose one of the supported target platforms( Windows, IOS, Android, WebGL ...). Then click "build", and Unity automatically generated all the files for the     application of the selected platform, including the .exe for Windows or the .html for WebGL. It uses some I don't know what intermediate language to achieve this.

I put the TdengineDriver.cs and Taos.dll inside my project folder. It worked as expected both in the Editor and in Windows platform build app. The Tdengine was running on a CentOS machine other than the application client.

The problem is my target platform is actually WebGL, which wouldn't reasonably work with the taos.dll.

I hope it won't be too confusing, but I guess you got my point of the inevitable cross-platform developing.

Could you tell me where can I find the source code for taos.dll?  I'm considering to recompile it into C#.
If that failed, I guess I'll switch to Restful API.

Thanks for the patience!

**Comment by SeanNi1221** [comment]
> Interesting topic. Sorry I can't provide any suggestion since I have no idea how to reproduce or verify with Unity/WebGL. Could you describe how to build a minimal demo app? May I know what's scenario and what benefit TDengine bring to you? Would you consider using RESTful to access TDengine?

**Comment by sangshuduo** [comment]
TDengine does support multiple platform including Linux, Windows and Mac. Although not full function on Windows or Mac so far. I'd be very happy to see if it can be port to WebGL platform. I guess it's a huge effort.

The source code and build system you can just refer to the repo you are posting question. :) It's 700K lines source code of C, python and other language.

**Comment by SeanNi1221** [comment]
> Interesting topic. Sorry I can't provide any suggestion since I have no idea how to reproduce or verify with Unity/WebGL. Could you describe how to build a minimal demo app? May I know what's scenario and what benefit TDengine bring to you? Would you consider using RESTful to access TDengine?

Unity is a cross-platform game engine, but also widely used in manufacturer, healthcare, real world simulation, and other vision-oriented scenarios because it can significantly accelerate the Graph and Physics simulation development processes.

The application I'm building has a full-3D interface representing the interior structure of a building with various categories of devices and sensors inside it. Each node has a data panel showing its value and history, and detailes, etc. That's why I'm using Unity as the main SDK for the project.
Since the 3D scene's scale can extend to a street block or a whole city with all the associated IoT nodes in the future, I decided to try TDengine as a superior data solution over Mysql and others.

In Unity you work like this:

1.Composite the 3d scenes and UI system inside the Unity Editor(running on Windows).

2.Code in C# using Unity Scripting API for every logic/behavior, then Compile everything inside the Unity Editor.

3.Choose one of the supported target platforms( Windows, IOS, Android, WebGL ...). Then click "build", and Unity automatically generates all the needed files for the application of the selected platform, including the .exe for Windows or the .html for WebGL. It uses some I don't know what intermediate language to achieve this.

I put the TdengineDriver.cs and Taos.dll inside my project folder. It worked as expected in both the Editor and the built app for Windows, with TDengine running on a CentOS machine other than the application client.

The problem is my target platform is actually WebGL, which wouldn't reasonably work with the taos.dll.

I hope it won't be too confusing, but I guess you got my point of the inevitable cross-platform developing.

Could you tell me where can I find the source code for taos.dll? I'm considering to recompile it into C#.
If that failed, I guess I'll switch to Restful API.

Thanks for the patience!

**Comment by SeanNi1221** [comment]
> TDengine does support multiple platform including Linux, Windows and Mac. Although not full function on Windows or Mac so far. I'd be very happy to see if it can be port to WebGL platform. I guess it's a huge effort.
> 
> The source code and build system you can just refer to the repo you are posting question. :) It's 700K lines source code of C, python and other language.

OK. I'll report the result here after I try.

**Comment by fenghuazzm** [comment]
This issue was closed because it has been inactive for too many days.
