### ISSUE TITLE
Not support multiple group by in Outer Query

### ISSUE THREAD

**Issue by xForMe** [taosdata/TDengine#6960]
外层不支持嵌套多个group by
![image](https://user-images.githubusercontent.com/8530198/126448274-ec95bb6a-aa8d-4bb8-9751-dd4e19d726aa.png)
但是嵌套单个是可以的
![image](https://user-images.githubusercontent.com/8530198/126449057-d99c0de7-177c-42de-9960-4a15ff151a45.png)

**Comment by yu285** [comment]
我们会继续完善嵌套，目前确实还有很多使用边界

**Comment by cmdares** [comment]
的确，如果能够让社区的开发者体验性能和便捷，真的需要花费大量精力的投入SQL能力提升！
持续关注！

**Comment by xForMe** [comment]
> 我们会继续完善嵌套，目前确实还有很多使用边界

我看见5天前这个issue关闭了，最新版本已经支持 multiple group by in Outer Query 了吗
