### ISSUE TITLE
RESTful concurrent write “Syntax error in SQL”

### ISSUE THREAD

**Issue by lich0821** [taosdata/TDengine#6987]
**Bug Description**
启用两个应用，同时往往一台TDengine服务器上的两个数据库插入数据，会出现 `{'status': 'error', 'code': 534, 'desc': 'Syntax error in SQL'}`异常。

**To Reproduce**
至少两个应用插入数据即可复现，难点在于同时，可能需要多次重复。

**Expected Behavior**
多个应用插入数据互不干扰。

**Environment (please complete the following information):**
```
taos> SELECT SERVER_VERSION();
 server_version() |
===================
 2.1.3.0          |
Query OK, 1 row(s) in set (0.000163s)

taos> SELECT CLIENT_VERSION();
 client_version() |
===================
 2.1.3.0          |
Query OK, 1 row(s) in set (0.000120s)

taos> 
```

**Comment by yu285** [comment]
咱们可以复现的话，请添加微信15652223354，我们可以远程看下

**Comment by lich0821** [comment]
> 咱们可以复现的话，请添加微信15652223354，我们可以远程看下

这个复现比较麻烦，我试试写一个必现的脚本。

**Comment by lich0821** [comment]
上次之后就没再搞了。后来升级了版本，再也没复现出来了。
