### ISSUE TITLE
Confirmation of nchar data type

### ISSUE THREAD

**Issue by korimas** [taosdata/TDengine#6988]
有个问题请教下，

关于nchar，文档的描述如下：
`记录包含多字节字符在内的字符串，如中文字符。每个 nchar 字符占用 4 bytes 的存储空间。字符串两端使用单引号引用，字符串内的单引号需用转义字符 \’。nchar 使用时须指定字符串大小，类型为 nchar(10) 的列表示此列的字符串最多存储 10 个 nchar 字符，会固定占用 40 bytes 的空间。如果用户字符串长度超出声明长度，将会报错。`

那就是说，定义了nchar(10)，无论有没有存满10个中文字符，这个字段都会占用调40bytes的空间是吗？
如果这个字段可能比较长的话，比如nchar(255)，是不是太浪费磁盘空间了。

**Comment by yu285** [comment]
目前是这样，但是存储部分、传输部分，都是可以开启压缩的，这样就不会有明显的问题了。

**Comment by korimas** [comment]
@yu285 不太清除你们的压缩原理，是说压缩后，那部分空闲的空间会被切掉吗？

**Comment by yu285** [comment]
> @yu285 不太清楚你们的压缩原理，是说压缩后，那部分没用到的空间会被切掉吗？

是的，不会占用多余空间
