### ISSUE TITLE
TDengine timestamp  doesn't match  client side

### ISSUE THREAD

**Issue by zsf-01** [taosdata/TDengine#7009]
插入数据到TDengine后，服务端查询这一条数据 的时间戳跟插入的时间戳不一致，客户端查询这一条数据时间戳跟服务端又不一致。时间戳这一列是第一列 并且插入的是历史数据（年月日分都跟插入的一直，只有小时不一致）。

插入语句：INSERT INTO n802344030600001_w21003 USING mnt_factor_item_data TAGS ("N802344030600001", 'w21003') VALUES ('2021-7-23 07:04:00:000',3, 999,'N802344030600002','w21003',19,'COD','mg/L',4,2,'大空港片区',1,'龙翔北路监测控制站',1,'龙翔北路水监测设备',3,'龙翔北路监测终端');
![微信图片_20210723224207](https://user-images.githubusercontent.com/73337889/126798762-1f0291b1-ab96-47e2-bc7c-c4bdbf53a6e1.png)

**Comment by zsf-01** [comment]
> 插入数据到TDengine后，服务端查询这一条数据 的时间戳跟插入的时间戳不一致，客户端查询这一条数据时间戳跟服务端又不一致。时间戳这一列是第一列 并且插入的是历史数据（年月日分都跟插入的一直，只有小时不一致）。
> 
> 插入语句：INSERT INTO n802344030600001_w21003 USING mnt_factor_item_data TAGS ("N802344030600001", 'w21003') VALUES ('2021-7-23 07:04:00:000',3, 999,'N802344030600002','w21003',19,'COD','mg/L',4,2,'大空港片区',1,'龙翔北路监测控制站',1,'龙翔北路水监测设备',3,'龙翔北路监测终端');

**Comment by yu285** [comment]
一般是时区设置问题，可以添加微信15652223354做具体排查
