### ISSUE TITLE
interval using help wanted

### ISSUE THREAD

**Issue by yipingdeng** [taosdata/TDengine#7016]
当前版本：2.0.16

select count(*) from dn where ts>now -2d INTERVAL(10m,15m) sliding(20);

如上sql：interval = 10，offset = 15，sliding=20
问题描述：
当offset >= interval 或者sliding >= interval 查询报错

![image](https://user-images.githubusercontent.com/19529607/126930954-eccdcbfa-4d03-47d1-9005-4c7acbd0ce19.png)

业务应用场景：
取设备的日间数据（时间用户可以自由设置）和夜间（根据日间时间推送夜间时间）数据做对比分析处理。

**Comment by yipingdeng** [comment]
你好，这个确认是问题了吗，会在后续版本修复吗？

**Comment by yipingdeng** [comment]
@yu285 你好，这个确认是问题了吗，会在后续版本修复吗？

**Comment by yu285** [comment]
sliding是为了防止时间不连续

offset毕竟是偏离量～本身就没有大面积移动的意思

如果真的是要偏移很大，完全可以通过指定开始时间+interval offset来达到同样的目的。
