### ISSUE TITLE
SQL demo issue in documents

### ISSUE THREAD

**Issue by lucienbao** [taosdata/TDengine#7024]
https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/02.getting-started/docs.md#tdengine-%E6%9E%81%E9%80%9F%E4%BD%93%E9%AA%8C
这个文档中，极速体验里面对于标签groupdId的拼写是错误的，实际应该是groupId，请更正说明和语句中的groupdId。

**Comment by lucienbao** [comment]
另外groupid的值是设置为0-9的，不是1-10，这里的描述也是错误的。
taos> select distinct groupid from test.meters;
   groupid   |
==============
           0 |
           1 |
           2 |
           3 |
           4 |
           5 |
           6 |
           7 |
           8 |
           9 |
Query OK, 10 row(s) in set (0.009790s)

**Comment by yu285** [comment]
您好，taosdemo由于需求增多一直在变化中，所以文档出现了不能匹配最新内容的情况，我们尽快修复。

请使用https://www.taosdata.com/blog/2020/12/29/2135.html做更多了解
