### ISSUE TITLE
build cluster under Docker environment, Dnodes are offline.

### ISSUE THREAD

**Issue by ranningw** [taosdata/TDengine#7028]
build cluster under Docker environment, Dnodes are offline.

在linux系统，用docker建立集群，添加dnode，dnode处于offline

不知如何解决？

**Comment by ranningw** [comment]
建立好的3个container（taosnode1，2，3）可以ping。

**Comment by yu285** [comment]
可以添加微信15652223354做具体配置排查

**Comment by ranningw** [comment]
已解决
