### ISSUE TITLE
命令行客户端对参数的解析有bug

### ISSUE THREAD

**Issue by eltonchaw7** [taosdata/TDengine#7056]
$ taos -h 127.0.0.1 -p 46030 -u root
taos: Too many arguments
Try `taos --help' or `taos --usage' for more information.

**Comment by sangshuduo** [comment]
猜测你是想指定网络端口，指定端口用 -P，大写的 P。小写 -p 是输入密码，输入密码需要和 -p 紧贴，所以显示这个错误信息

**Comment by eltonchaw7** [comment]
> 猜测你是想指定网络端口，指定端口用 -P，大写的 P。小写 -p 是输入密码，输入密码需要和 -p 紧贴，所以显示这个错误信息

我为了不暴露IP所以重新打字把-P打成小写了，不过按您的提示，确实是加密码参数时 -p 没紧贴密码，谢谢！

**Comment by nullobject0x01** [comment]
什么傻逼解析还要贴紧密码，--help有个b用
