### ISSUE TITLE
over 300 concurrent connections , below core dump

### ISSUE THREAD

**Issue by jason-000** [taosdata/TDengine#7075]
over 300 concurrent connections , below core dump

我司在做券商大并发压力测试中，单机越过300用户连接，时报dump错误。

这行连接报错
TAOS *taos = taos_connect("td1", "root", "taosdata", "testdb", 6030);

以下是gdb的截图，截图放不上来，以下是粘贴的

(gdb) where
#0  0x00007fb2b0934f81 in pthread_join (threadid=140404954195712, thread_return=0x7ffea3944d80) at pthread_join.c:92
#1  0x00007fb2b061ec03 in taosStopTcpThread (pThreadObj=0x137b0b0) at 
    /home/ubuntu/workroom/jenkins/TDinternal/community/src/rpc/src/rpcTcp.c:188
#2  0x00007fb2b061f8d5 in taosCleanUpTcpClient (chandle=0x137ab50) at 
    /home/ubuntu/workroom/jenkins/TDinternal/community/src/rpc/src/rpcTcp.c:384
#3  0x00007fb2b061f801 in taosInitTcpClient (ip=0, port=0, label=0x135c084 "TSC", numOfThreads=40, fp=0x7fb2b061b2cc 
    <rpcProcessMsgFromPeer>, shandle=0x135c070)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/rpc/src/rpcTcp.c:365
#4  0x00007fb2b06185f0 in rpcOpen (pInit=0x7ffea3943230) at 
    /home/ubuntu/workroom/jenkins/TDinternal/community/src/rpc/src/rpcMain.c:308
#5  0x00007fb2b03ca1fe in tscAcquireRpc (key=0x7ffea3943820 "root:taosdata:td1:6030", user=0x42e8ea "root", 
    secretEncrypt=0x7ffea39437d0 "\334ž\320HQ\376\310T\300\065\262\344\002c\266", ppRpcObj=0x7ffea3943500)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/client/src/tscSystem.c:101
#6  0x00007fb2b03ae4ff in taosConnectImpl (ip=0x42e8ef "td1", user=0x42e8ea "root", pass=0x42e8e1 "taosdata", auth=0x0, 
     db=0x42e8da "testdb", port=6030, 
    fp=0x7fb2b03ae94e <syncConnCallback>, param=0x0, taos=0x7ffea3943a98) at 
    /home/ubuntu/workroom/jenkins/TDinternal/community/src/client/src/tscSql.c:99
#7  0x00007fb2b03aea12 in taos_connect_internal (ip=0x42e8ef "td1", user=0x42e8ea "root", pass=0x42e8e1 "taosdata", 
    auth=0x0, db=0x42e8da "testdb", port=6030)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/client/src/tscSql.c:189
#8  0x00007fb2b03aec57 in taos_connect (ip=0x42e8ef "td1", user=0x42e8ea "root", pass=0x42e8e1 "taosdata", db=0x42e8da 
    "testdb", port=6030)
     at /home/ubuntu/workroom/jenkins/TDinternal/community/src/client/src/tscSql.c:226
#9  0x000000000040720a in main (argc=22, argv=0x7ffea3944d88) at SpxACodeDemo0.15.cpp:385

 - OS:CentOS 7.0]
 - TDengine Version [e.g. 20.0.20.10]

**Comment by cmdares** [comment]
环境什么配置，数据量多大出的问题。
测下最新版本，看看这个问题是否还存在。
官方的同学，帮助看下。
关注！

**Comment by fenghuazzm** [comment]
This issue was closed because it has been inactive for too many days.
TDengine is being more and more stable, thank you for your continued attention and recommend you use the latest version .
