### ISSUE TITLE
Taosd crashed, and no return results for aggregation query like avg, max and min

### ISSUE THREAD

**Issue by uk0** [taosdata/TDengine#708]
**Bug Description**
1. 数量过大无法计算数据 `select avg(vol_c),max(vol_c),min(vol_c) from fmex.btc_p_info WHERE ts<now INTERVAL(3m) order by ts desc  limit 10;` 没有返回值 表中数据 大约 30w
2. sql错误 会导致Taosd 死亡
3. 配置文件里面的配置 log data 目录无法被使用，defaultPass 没有生效、

**To Reproduce**
1. 启动 Taosd
2. 执行sql `select avg(vol_c),max(vol_c),min(vol_c) from fmex.btc_p_info WHERE ts<now INTERVAL(3m) order by ts desc  limit 1000;`  这样之行错误的sql 会导致 Taos 死掉，下面是报错。
3.  `taosd: /home/taosdata/TDengine/src/system/detail/src/vnodeQueryImpl.c:3955: getTimestampInDiskBlock: Assertion `pQuery->pos >= 0 && pQuery->pos < pBlock->numOfPoints' failed.`

**Environment (please complete the following information):**
 - OS: Ubuntu18
 - Memory 16GB, CPU i7 8700 , current Disk Space SSD 460GB
 - TDengine Version ：1.6.4.0

**Comment by hjxilinx** [comment]
您的SQL语句中，确定时间范围是
> ts> now

**Comment by uk0** [comment]
这个是我测试 的时候出现的 有时候 有 有时候没有 现在换了版本已经没有了 没有的结果是正确的 。当前版本   client version:1.6.3.1 server version:1.6.3.1

**Comment by hjxilinx** [comment]
查询的时候，如果使用now，客户端会自动按照客户端所在的时区，将now的时间转换为unix timestamp，并将查询结果发往服务器。
所以使用now在不同的时候执行，获取的结果是不一样的。

**Comment by hjxilinx** [comment]
第三个问题，defaultPass现在暂时还不能配置。您所说的配置log /data没有生效的问题，请确认一下有权限来进行写操作。

**Comment by hjxilinx** [comment]
第二个crash的问题，如果您方便，我可以远程协助来确认问题。联系方式您可以邮件给我hjliao@taosdata.com
