### ISSUE TITLE
Restful show database not specified 

### ISSUE THREAD

**Issue by wangcongzhen** [taosdata/TDengine#7087]
tdengine版本  TDengine-server-2.0.19.1

<dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>2.0.33</version>
        </dependency>!

NCHAR(6) , humidity NCHAR(6) , pm25 NCHAR(6) , temperature NCHAR(6) , volume NCHAR(6) ) TAGS (Device NCHAR(20)); 
15:32:55 [async-service-99] DEBUG c.y.r.m.t.S.createpressureTesttable - ==> Parameters: 
15:32:55 [async-service-99] INFO  o.a.http.impl.execchain.RetryExec - I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://xxxxxxxxxx:6041: The target server failed to respond
15:32:55 [async-service-99] INFO  o.a.http.impl.execchain.RetryExec - Retrying request to {}->http://xxxxxxxxxx:6041
15:32:55 [async-service-467] DEBUG c.y.r.m.t.S.createpressureTesttable - <==    Updates: 0
15:32:55 [async-service-99] DEBUG c.y.r.m.t.S.createpressureTesttable - <==    Updates: 0
15:32:55 [async-service-99] DEBUG c.y.r.m.t.S.insertDatapressureTest - ==>  Preparing: INSERT INTO db.F44 USING db.data TAGS ("test") VALUES(now,17.7,31.1,160.75,44.4,0,1,44.98,73.22,49.43,76.47); 
15:32:55 [async-service-99] DEBUG c.y.r.m.t.S.insertDatapressureTest - ==> Parameters: 
15:32:55 [async-service-99] DEBUG c.y.r.m.t.S.insertDatapressureTest - <==    Updates: 1
15:32:55 [async-service-163] DEBUG c.y.r.m.t.S.createpressureTesttable - ==>  Preparing: CREATE STABLE IF NOT EXISTS db.data (ts TIMESTAMP, CO NCHAR(6) , NO2 NCHAR(6) , PM10 NCHAR(6) , SO2 NCHAR(6) , area NCHAR(6) , class NCHAR(6) , humidity NCHAR(6) , pm25 NCHAR(6) , temperature NCHAR(6) , volume NCHAR(6) ) TAGS (Device NCHAR(20)); 
15:32:55 [async-service-388] DEBUG c.y.r.m.t.S.createpressureTesttable - ==>  Preparing: CREATE STABLE IF NOT EXISTS db.data (ts TIMESTAMP, CO NCHAR(6) , NO2 NCHAR(6) , PM10 NCHAR(6) , SO2 NCHAR(6) , area NCHAR(6) , class NCHAR(6) , humidity NCHAR(6) , pm25 NCHAR(6) , temperature NCHAR(6) , volume NCHAR(6) ) TAGS (Device NCHAR(20)); 
15:32:55 [async-service-44] DEBUG c.y.r.m.t.S.createpressureTesttable - ==>  Preparing: CREATE STABLE IF NOT EXISTS db.data (ts TIMESTAMP, CO NCHAR(6) , NO2 NCHAR(6) , PM10 NCHAR(6) , SO2 NCHAR(6) , area NCHAR(6) , class NCHAR(6) , humidity NCHAR(6) , pm25 NCHAR(6) , temperature NCHAR(6) , volume NCHAR(6) ) TAGS (Device NCHAR(20)); 
15:32:55 [async-service-262] DEBUG c.y.r.m.t.S.createpressureTesttable - ==>  Preparing: CREATE STABLE IF NOT EXISTS db.data (ts TIMESTAMP, CO NCHAR(6) , NO2 NCHAR(6) , PM10 NCHAR(6) , SO2 NCHAR(6) , area NCHAR(6) , class NCHAR(6) , humidity NCHAR(6) , pm25 NCHAR(6) , temperature NCHAR(6) , volume NCHAR(6) ) TAGS (Device NCHAR(20)); 
15:32:55 [async-service-163] DEBUG c.y.r.m.t.S.createpressureTesttable - ==> Parameters: 
15:32:55 [async-service-44] DEBUG c.y.r.m.t.S.createpressureTesttable - ==> Parameters: 
15:32:55 [async-service-262] DEBUG c.y.r.m.t.S.createpressureTesttable - ==> Parameters: 
15:32:55 [async-service-388] DEBUG c.y.r.m.t.S.createpressureTesttable - ==> Parameters: 

15:32:55 [async-service-395] DEBUG c.y.r.m.t.S.createpressureTesttable - ==>  Preparing: CREATE STABLE IF NOT EXISTS db.data (ts TIMESTAMP, CO NCHAR(6) , NO2 NCHAR(6) , PM10 NCHAR(6) , SO2 NCHAR(6) , area NCHAR(6) , class NCHAR(6) , humidity NCHAR(6) , pm25 NCHAR(6) , temperature NCHAR(6) , volume NCHAR(6) ) TAGS (Device NCHAR(20)); 
15:32:55 [async-service-395] DEBUG c.y.r.m.t.S.createpressureTesttable - ==> Parameters: 
15:32:55 [async-service-117] WARN  com.zaxxer.hikari.pool.PoolBase - TDengineDruidCP - Failed to validate connection com.taosdata.jdbc.rs.RestfulConnection@1cc2f562 (TDengine ERROR (380): Database not specified or available)
15:32:55 [async-service-90] WARN  com.zaxxer.hikari.pool.PoolBase - TDengineDruidCP - Failed to validate connection com.taosdata.jdbc.rs.RestfulConnection@3b30ef23 (TDengine ERROR (380): Database not specified or available)
15:32:55 [async-service-500] WARN  com.zaxxer.hikari.pool.PoolBase - TDengineDruidCP - Failed to validate connection com.taosdata.jdbc.rs.RestfulConnection@70962f55 (TDengine ERROR (380): Database not specified or available)
15:32:55 [async-service-163] DEBUG c.y.r.m.t.S.createpressureTesttable - <==    Updates: 0
15:32:55 [async-service-44] DEBUG c.y.r.m.t.S.createpressureTesttable - <==    Updates: 0
15:32:55 [async-service-404] WARN  com.zaxxer.hikari.pool.PoolBase - TDengineDruidCP - Failed to validate connection com.taosdata.jdbc.rs.RestfulConnection@2909596c (TDengine ERROR (380): Database not specified or available)
15:32:55 [async-service-404] DEBUG c.y.r.m.t.S.createpressureTesttable - ==>  Preparing: CREATE STABLE IF NOT EXISTS db.data (ts TIMESTAMP, CO NCHAR(6) , NO2 NCHAR(6) , PM10 NCHAR(6) , SO2 NCHAR(6) , area NCHAR(6) , class NCHAR(6) , humidity NCHAR(6) , pm25 NCHAR(6) , temperature NCHAR(6) , volume NCHAR(6) ) TAGS (Device NCHAR(20)); 
15:32:55 [async-service-404] DEBUG c.y.r.m.t.S.createpressureTesttable - ==> Parameters: 
15:32:55 [async-service-110] DEBUG c.y.r.m.t.S.createpressureTesttable - ==>  Preparing: CREATE STABLE IF NOT EXISTS db.data (ts TIMESTAMP, CO NCHAR(6) , NO2 NCHAR(6) , PM10 NCHAR(6) , SO2 NCHAR(6) , area NCHAR(6) , class NCHAR(6) , humidity NCHAR(6) , pm25 NCHAR(6) , temperature NCHAR(6) , volume NCHAR(6) ) TAGS (Device NCHAR(20)); 
15:32:55 [async-service-110] DEBUG c.y.r.m.t.S.createpressureTesttable - ==> Parameters: 
15:32:55 [async-service-453] WARN  com.zaxxer.hikari.pool.PoolBase - TDengineDruidCP - Failed to validate connection com.taosdata.jdbc.rs.RestfulConnection@177182af (TDengine ERROR (380): Database not specified or available)
15:32:55 [async-service-230] DEBUG c.y.r.m.t.S.createpressureTesttable - <==    Updates: 0
15:32:55 [async-service-471] DEBUG c.y.r.m.t.S.createpressureTesttable - ==>  Preparing: CREATE STABLE IF NOT EXISTS db.data (ts TIMESTAMP, CO NCHAR(6) , NO2 NCHAR(6) , PM10 NCHAR(6) , SO2 NCHAR(6) , area NCHAR(6) , class NCHAR(6) , humidity NCHAR(6) , pm25 NCHAR(6) , temperature NCHAR(6) , volume NCHAR(6) ) TAGS (Device NCHAR(20)); 

****

**Comment by yu285** [comment]
用restful的时候，一定要确保sql里的表名前有数据库名字。

这样就不会出现这个问题了。

**Comment by wangcongzhen** [comment]
看sql已经指定了数据库的名字

**Comment by yu285** [comment]
您是指 insert into dbname.tablename xxxxx 这种格式吗？ 还是在前面use dbname？

**Comment by yu285** [comment]
不好意思。JDBC 2.0.33要和TDengine 2.1.3以上的版本配合使用。

**Comment by yu285** [comment]
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/74105241/128150160-ed6d8c1c-e176-46a6-a5c3-4680118ceeb2.png">

**Comment by wangcongzhen** [comment]
那TDengine可以在线升级吗？

**Comment by yu285** [comment]
> 那TDengine可以在线升级吗？

暂时还不可以，需要停止一下服务

**Comment by wangcongzhen** [comment]
有在线升级的文档或者博客吗

**Comment by yu285** [comment]
> 有在线升级的文档或者博客吗

暂时还不能在线升级，只能停止服务。

1./var/lib/taos 目录做一下备份
2.rmtaos删除TDengine软件（不会删除数据，配置文件，日志）
3.安装新的数据库软件
4.升级后检查数据库是否正常工作。
