### ISSUE TITLE
Taos ： Time leads to inaccurate counting

### ISSUE THREAD

**Issue by uk0** [taosdata/TDengine#709]
####  存在问题 
      1. 手动将系统时间 修改成 2019年11月12号19:09:00  插入第一条数据 A
      2. 手动将系统时间 2019年11月12号15:09:00 插入第二条数据 B (Result 0 Row 这是为什么)
      3 进行count（） 发现数据条数不会变动，last 看到的最新的是 A 
     

数据已经插入数据库那么我想提取这部分数据 该如何提取 。不知道算不算 bug// /// ：）

**Comment by hjxilinx** [comment]
您的描述中说的，手动修改是什么意思？
您可以select * from table_name的方式取出来数据是否last返回的就是最后的记录。

**Comment by uk0** [comment]
我是手动修改的时间 系统时间 。

**Comment by uk0** [comment]
这个情况 是我自己的 用错服务器启动导致的  后来改回来 发现数据 insert result 0 row  还没有其他错误   我就检查了一下最新一条的时间 发现是 19点的数据。

**Comment by uk0** [comment]
我不确定我的误操作 得出来的现象 是不是 bug 如果不是 麻烦您帮我 close 掉。

**Comment by hzcheng** [comment]
你的客户端和服务端在同一台机器上吗？

**Comment by hjxilinx** [comment]
写入数据的时候您采用了now来作为时间戳来进行写入，并且写入的客户端是与taosd服务在同一台机器是吗？

**Comment by uk0** [comment]
是的 
都在一台机器上

**Comment by uk0** [comment]
不好意思 刚才 我可能没有描述清楚 请您谅解  我修改了 我的步骤 请您查看。

**Comment by hjxilinx** [comment]
affected rows是0，表示没有写入成功。因为TDengine的设计要求，时间序列应该是一个单调递增的数列。你这里的情况，对应的应该是实际场景中的时间戳乱序的问题。
您可以使用
```
import into table_name xxxxx....
```
替换
```
insert into table_name xxxx .....
```

再执行一次即可。

**Comment by uk0** [comment]
好的 谢谢 您 。
