### ISSUE TITLE
python fetchall error OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by CreateModel** [taosdata/TDengine#7095]
连接时每次都在fetchall出错。
报错：
Traceback (most recent call last):
  File "E:/BigDataProject/data_monitor_sdsd.py", line 13, in <module>
    data =c1.fetchall()
  File "E:\BigDataProject\venv\lib\site-packages\taos-2.0.4-py3.8.egg\taos\cursor.py", line 174, in fetchall
  File "E:\BigDataProject\venv\lib\site-packages\taos-2.0.4-py3.8.egg\taos\cinterface.py", line 527, in fetchBlock
  File "E:\BigDataProject\venv\lib\site-packages\taos-2.0.4-py3.8.egg\taos\cinterface.py", line 24, in _crow_timestamp_to_python
  File "E:\BigDataProject\venv\lib\site-packages\taos-2.0.4-py3.8.egg\taos\cinterface.py", line 9, in _convert_millisecond_to_datetime
OSError: [Errno 22] Invalid argument

环境：win10, 客户端TDengin-client-2.0.17.0-Windows-x64 安装库为taos 2.0.4，使用pycharm

以下为运行代码：

import taos
import datetime
conn = taos.connect(host="192.100.30.104",port=6030, user="root", password="taosdata",database='test')
c1 = conn.cursor()
try:
    c1.execute('select * from beiqijia')

except Exception as e:
    conn.close()
    raise (e)

# 拉取查询结果
data =c1.fetchall()
print(data)

**Comment by sangshuduo** [comment]
试试最新版本？

**Comment by CreateModel** [comment]
因为项目已经部署，服务器在用的版本就是这个。客户端必须保持一致。 话说你们考虑做一下版本兼容吗？这个版本问题在实际项目后期维护上挺费劲的。



发自我的iPhone


------------------ Original ------------------
From: Shuduo Sang ***@***.***&gt;
Date: Sat,Jul 31,2021 0:13 PM
To: taosdata/TDengine ***@***.***&gt;
Cc: CreateModel ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [taosdata/TDengine] python fetchall error OSError: [Errno 22] Invalid argument (#7095)





 
试试最新版本？

**Comment by sangshuduo** [comment]
试试单独升级 python connector 呢？

数据可以保持大版本兼容，bugfix很难啊

**Comment by CreateModel** [comment]
单独升级不太会，怎么操作呢？今天试了一下，在Linux服务器上跑python连接的脚本，也运行不出来数据。我们服务器上布的2.0.17版本的。 后来我换成http连接，可以正常拿到数据。



发自我的iPhone


------------------ Original ------------------
From: Shuduo Sang ***@***.***&gt;
Date: Sat,Jul 31,2021 1:07 PM
To: taosdata/TDengine ***@***.***&gt;
Cc: CreateModel ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [taosdata/TDengine] python fetchall error OSError: [Errno 22] Invalid argument (#7095)





 
试试单独升级 python connector 呢？
 
数据可以保持大版本兼容，bugfix很难啊

**Comment by CreateModel** [comment]
还有个问题想请教一下，如果我在服务器上升级服务端版本，之前存进去的数据还在吗？



发自我的iPhone


------------------ Original ------------------
From: Shuduo Sang ***@***.***&gt;
Date: Sat,Jul 31,2021 1:07 PM
To: taosdata/TDengine ***@***.***&gt;
Cc: CreateModel ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [taosdata/TDengine] python fetchall error OSError: [Errno 22] Invalid argument (#7095)





 
试试单独升级 python connector 呢？
 
数据可以保持大版本兼容，bugfix很难啊

**Comment by sangshuduo** [comment]
git clone [https://github.com/taosdata/TDengine](https://github.com/taosdata/TDengine)

pip3 install TDengine/src/connector/python/

数据还在，2.0.x.x 和 2.y.y.y 之间数据兼容

**Comment by CreateModel** [comment]
谢谢 ，我周一上班的时候试一试。辛苦啦！



发自我的iPhone


------------------ Original ------------------
From: Shuduo Sang ***@***.***&gt;
Date: Sat,Jul 31,2021 7:58 PM
To: taosdata/TDengine ***@***.***&gt;
Cc: CreateModel ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [taosdata/TDengine] python fetchall error OSError: [Errno 22] Invalid argument (#7095)





 
git clone https://github.com/taosdata/TDengine
 
pip3 install TDengine/src/connector/python/
 
数据还在，2.0.x.x 和 2.y.y.y 之间数据兼容

**Comment by fenghuazzm** [comment]
This issue was closed because it has been inactive for too many days.
