### ISSUE TITLE
JDBC cluster doesn't work

### ISSUE THREAD

**Issue by chuangtim** [taosdata/TDengine#7096]
taosd: 2.0.20.0
taos maven版本号：2.0.27

jdbc连接taosd集群的master节点，当master节点掉线后无法切换，报错误。
`Caused by: java.sql.SQLException: TDengine ERROR (8000000b): Unable to establish connection`

**Comment by yu285** [comment]
您好，在连接的时候请不要在url指定ip，这样就会自动读取客户端配置文件taos.cfg里的firstEP和secondEP完成高可用。
