### ISSUE TITLE
官网文档有笔误

### ISSUE THREAD

**Issue by qinzuoyan** [taosdata/TDengine#71]
https://www.taosdata.com/blog/2019/04/03/%e7%89%a9%e8%81%94%e7%bd%91%e5%a4%a7%e6%95%b0%e6%8d%ae%e9%a2%86%e5%9f%9f%e8%bf%8e%e6%9d%a5%e5%88%9b%e4%b8%9a%e8%80%81%e5%b0%86%ef%bc%8c%e8%93%84%e5%8a%9b%e8%80%8c%e4%b8%ba%e7%9b%b4%e6%8e%a5%e5%af%b9/

`支持 JDBCODBC、REST 接口` 改为 `支持 JDBC、ODBC、REST 接口`？

**Comment by jtao1735** [comment]
谢谢
