### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by sunashe** [taosdata/TDengine#710]
**Bug Description**
make error with linux 2.6.32-431.el6.x86_64

cd /usr/local/ashe/TDengine/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /usr/local/ashe/TDengine /usr/local/ashe/TDengine/src/os/linux /usr/local/ashe/TDengine/build /usr/local/ashe/TDengine/build/src/os/linux /usr/local/ashe/TDengine/build/src/os/linux/CMakeFiles/os.dir/DependInfo.cmake --color=
Scanning dependencies of target os
gmake[2]: Leaving directory `/usr/local/ashe/TDengine/build'
/usr/bin/gmake -f src/os/linux/CMakeFiles/os.dir/build.make src/os/linux/CMakeFiles/os.dir/build
gmake[2]: Entering directory `/usr/local/ashe/TDengine/build'
/usr/bin/cmake -E cmake_progress_report /usr/local/ashe/TDengine/build/CMakeFiles 12
[ 11%] Building C object src/os/linux/CMakeFiles/os.dir/src/tlinux.c.o
cd /usr/local/ashe/TDengine/build/src/os/linux && /usr/bin/cc  -DLINUX -D_LIBC_REENTRANT -D_M_X64 -D_REENTRANT -D__USE_POSIX -g -std=gnu99 -Wall -fPIC -malign-double -g -Wno-char-subscripts -malign-stringops -msse4.2 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILE -O0 -DDEBUG -I/usr/local/ashe/TDengine/src/os/linux/inc -I/usr/local/ashe/TDengine/src/inc    -o CMakeFiles/os.dir/src/tlinux.c.o   -c /usr/local/ashe/TDengine/src/os/linux/src/tlinux.c
/usr/local/ashe/TDengine/src/os/linux/src/tlinux.c: 在函数‘__sync_val_load_32’中:
/usr/local/ashe/TDengine/src/os/linux/src/tlinux.c:345: 警告：隐式声明函数‘__atomic_load_n’
/usr/local/ashe/TDengine/src/os/linux/src/tlinux.c:345: 错误：‘__ATOMIC_ACQUIRE’未声明(在此函数内第一次使用)
/usr/local/ashe/TDengine/src/os/linux/src/tlinux.c:345: 错误：(即使在一个函数内多次出现，每个未声明的标识符在其
/usr/local/ashe/TDengine/src/os/linux/src/tlinux.c:345: 错误：所在的函数内也只报告一次。)
/usr/local/ashe/TDengine/src/os/linux/src/tlinux.c: 在函数‘__sync_val_restore_32’中:
/usr/local/ashe/TDengine/src/os/linux/src/tlinux.c:349: 警告：隐式声明函数‘__atomic_store_n’
/usr/local/ashe/TDengine/src/os/linux/src/tlinux.c:349: 错误：‘__ATOMIC_RELEASE’未声明(在此函数内第一次使用)
gmake[2]: *** [src/os/linux/CMakeFiles/os.dir/src/tlinux.c.o] 错误 1
gmake[2]: Leaving directory `/usr/local/ashe/TDengine/build'
gmake[1]: Leaving directory `/usr/local/ashe/TDengine/build'
gmake[1]: *** [src/os/linux/CMakeFiles/os.dir/all] 错误 2
gmake: *** [all] 错误 2

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by sunashe** [comment]
tag ver-1.6.3.1

**Comment by localvar** [comment]
请用 `gcc --version` 检查一下gcc的版本号，看是否低于4.7.0，是的话升级gcc后再试试看问题是否依然存在。
