### ISSUE TITLE
Does TDengine  support ODBC?

### ISSUE THREAD

**Issue by liuyl1992** [taosdata/TDengine#7104]
**Is your feature request related to a problem? Please describe.**
tdengine 缺少ODBC驱动，目前只有JDBC驱动，ODBC驱动可以做到更好的语言无关性，希望能得到支持，

**Describe your desired behavior**
目前程序有.netcore和.net两类，希望通过抽象的ODBC驱动可以更好的融入到tdengine

**Describe your solutions/suggestions if you've any**
目前主流数据库基本都提供了ODBC，比如clinkhouse,mysql等。希望优秀的tdengine也能支持odbc

**Additional context**

**Comment by sangshuduo** [comment]
@liuyl1992   参见 src/connector/odbc

**Comment by fenghuazzm** [comment]
This issue was closed because it has been inactive for too many days.
