### ISSUE TITLE
【crash】 Too many tdengine-extbuf files in /tmp

### ISSUE THREAD

**Issue by korimas** [taosdata/TDengine#7118]
/tmp目录下有很多tdengine-extbuf文件，总大小6G多。

问下这个文件是什么，为什么会生成，怎么排查问题。

怎么不让它生成，把磁盘都占满了，所有服务都挂。

**Comment by korimas** [comment]
![image](https://user-images.githubusercontent.com/15672287/127946240-6266cb85-6fb8-466d-91dc-ee10b515b6d3.png)

**Comment by yu285** [comment]
经排查，是安装目录含有中文问题，故作关闭处理。

**Comment by alanackart** [comment]
我们出现的情况是jdbc查询, ResultSet没有调用close方法(lack of calling close method of ResultSet)， 调了这个方法后，  tdengine-extbuf文件在查询结束后就会自动消失了

**Comment by alanackart** [comment]
https://www.taosdata.com/cn/documentation/connector/java

resultSet.close();
stmt.close();
conn.close();
注意务必要将 connection 进行关闭，否则会出现连接泄露。

**Comment by korimas** [comment]
> https://www.taosdata.com/cn/documentation/connector/java
> 
> 结果集.close(); stmt.close(); conn.close(); 注意必须要连接进行关闭，否则会出现连接泄露。

是的，我们也发现了，是连接泄漏导致的。
