### ISSUE TITLE
 JDBC-RESTful  in springboot  query issue

### ISSUE THREAD

**Issue by tuyujie** [taosdata/TDengine#7135]
1.使用 JDBC-JNI 查询数据：正常

2.使用postman调用http://xxxx:6041/rest/sql获取数据：正常

3.使用JDBC-RESTful调用获取数据：异常
![image](https://user-images.githubusercontent.com/58453170/127988564-d7cf1083-8e43-4fd3-b9da-6ae1636946e3.png)

4.taos-jdbcdriver版本：2.0.25

5.对应配置：
![image](https://user-images.githubusercontent.com/58453170/127988733-92bc7a96-1969-49a0-aa77-cf7a468d64bd.png)

**Comment by yu285** [comment]
咱们数据库是什么版本

**Comment by tuyujie** [comment]
> 咱们数据库是什么版本



> 咱们数据库是什么版本



> 咱们数据库是什么版本

2.0.17
