### ISSUE TITLE
 Result set too large to be sorted

### ISSUE THREAD

**Issue by Angle-bo** [taosdata/TDengine#7138]
2.1.3.2版本，集群模式，查询排序报错。更改配置依然报错。maxNumOfOrderedRes 100000000

**Comment by Angle-bo** [comment]
单机版，修改 maxNumOfOrderedRes    100000000 重启服务，依然报错Result set too large to be sorted

**Comment by yu285** [comment]
这个参数当前最大只能开到100万。

**Comment by Angle-bo** [comment]
啊。那有没有啥好的解决方案，根据字段排序的。

**Comment by yu285** [comment]
> 啊。那有没有啥好的解决方案，根据字段排序的。

当前的排序只有子表的时间列排序是无限制的，超级表的时间列排序是最大100万，对于普通列的排序暂时还不支持

**Comment by korimas** [comment]
时序数据库还需要按时间排序？
从头拿还是从尾拿数据而已，用limit就行。比如：
```sql
select * from xxxx limit count-length, length
```
以上伪代码。


比较不理解的是tdengine的排序逻辑，难不成tdengine真的去本来就有序的数据里再比较了一堆时间戳？我觉得是不是走歪了。
@yu285
