### ISSUE TITLE
write performance issue

### ISSUE THREAD

**Issue by xujiesh0510** [taosdata/TDengine#717]
配置：4C 16G 实体机。
表：总共10万张表，每个表1个监控点字段
测试程序：c# 使用http接口，8线程每秒写入 10万（每秒每张表写入1个点，总共10万张表，那么每秒要写10万张表），每个http 请求 发送1000个监控点数据。
结果： 大概 500毫秒完成10万数据点插入，写了3小时多吧，但是会出现60多秒完成一次写入的情况。
配置文件只改了每个 vnode 10000 张表

下图是打印出来的 完成一次写入需要的时间（有1次特别耗时）：
![image](https://user-images.githubusercontent.com/10271679/68850303-bcff3580-070e-11ea-95b9-0225bdde7955.png)

![image](https://user-images.githubusercontent.com/10271679/68875539-f7cc9200-073d-11ea-8337-c1541eb031e1.png)

cpu 内存都不高，dstat 看磁盘读写也没持续写1分钟，偶尔有写入。不知道什么情况

过滤掉1s内的写入，还是有些写入超时（测试时间12小时）
![image](https://user-images.githubusercontent.com/10271679/68914847-e06fc200-079a-11ea-9492-6b8bb6b03e50.png)

**Comment by xujiesh0510** [comment]
把图片另存为，改后缀名为 7z，解压即是c#工程源码
![ConsoleApp2](https://user-images.githubusercontent.com/10271679/68852795-98f22300-0713-11ea-8f65-0e9b78bc92c5.jpg)

**Comment by guanshengliang** [comment]
这个问题原因已经清楚，可能是数据落盘时的一个线程锁导致。
近期重构代码时，将去尝试修复这个问题。 @hzcheng

**Comment by jtao1735** [comment]
这个问题要处理，1：跑一下他们提供的C#程序，看我们自己的测试结果，2：要一下对方日志。我个人判断是，不可能落盘要一分钟时间。

**Comment by guanshengliang** [comment]
@xujiesh0510  
您好，我尝试编译运行你的程序时，发现编译器版本不够。目前机器没有空间再安装一个VS2019，请您将编译好的可执行文件打包发给我的信箱，感谢您的配合。
slguan@taosdata.com

**Comment by hjxilinx** [comment]
@xujiesh0510 ，问题的原因我们已经确认，SQL异步解析的问题，下一个版本会处理这个问题，简单的避免这个问题的方法是将metermetaKeepTimer 的时间延长到10个小时。可以将这个问题的发生的时间延长到10个小时。

**Comment by guanshengliang** [comment]
After WeChat communication, this issue has been resolve, so we close it
