### ISSUE TITLE
Getting Started page sql error

### ISSUE THREAD

**Issue by liuwenju** [taosdata/TDengine#7171]
taos> select avg(current), max(voltage), min(phase) from test.meters where groupdId=10;

DB error: invalid SQL: illegal column name 

Change groupdId to groupId it work

**Comment by sangshuduo** [comment]
groupId=10

**Comment by liuwenju** [comment]
![image](https://user-images.githubusercontent.com/10233397/128282121-bc46fe59-fd78-4b88-a4e9-ab242df01c3f.png)

The error still exists

**Comment by sangshuduo** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/10233397/128282121-bc46fe59-fd78-4b88-a4e9-ab242df01c3f.png)
> 
> The error still exists

谢谢，这是一个文档拼写错误，我们随后改正。
