### ISSUE TITLE
win10 client can connect TDengine but not select or insert 

### ISSUE THREAD

**Issue by s1-001** [taosdata/TDengine#7175]
CentOS 7

UDP  6030  6035 端口也开放了
windows能正常连接数据库
但是连接上去以后无法对表操作

**Comment by yu285** [comment]
https://mp.weixin.qq.com/s/hRpPXh77mXRg95VuNB4Lmw

配置问题，请参考这篇文章的场景1和场景2。

如果还有疑问可以添加微信15652223354。

**Comment by s1-001** [comment]
> https://mp.weixin.qq.com/s/hRpPXh77mXRg95VuNB4Lmw
> 
> 配置问题，请参考这篇文章的场景 1 和场景 2。
> 
> 如果还有疑问可以添加微信15652223354。
