### ISSUE TITLE
can't connect server use golang driver on windows

### ISSUE THREAD

**Issue by qingshenyijiu** [taosdata/TDengine#718]
**Bug Description**
Windows环境下，使用golang driver无法连接到服务端，报错taos_connect() fail!
使用Windows 客户端 taos.exe 能正常链接到服务端。
golang driver dsn：root:taosdata@tcp(172.16.35.46:60300)/db
taos.exe： taos.exe -h 172.16.35.46 -P 60300
![QQ截图20191114203708](https://user-images.githubusercontent.com/14091724/68857877-c6909980-071e-11ea-8dab-ff7521b27ab1.png)
![QQ截图20191114203828](https://user-images.githubusercontent.com/14091724/68857879-c85a5d00-071e-11ea-8ba8-345b3e84659d.png)

**Environment (please complete the following information):**
 - OS: win10
 - GoVersion: 1.13
 - TDengine Version [e.g. 1.6.3.0]

**Comment by qingshenyijiu** [comment]
我尝试使用java jdbc连接，一样也是报错连接不上服务端，怀疑是taos.dllll库有问题？

![QQ截图20191115112126](https://user-images.githubusercontent.com/14091724/68914652-3c861680-079a-11ea-8f1f-867ff9658d3e.png)

**Comment by plum-lihui** [comment]
目前go driver还不支持windows版本，因为里面使用cgo，暂时只是在linux环境下调用libtaos.so。没有在windows下适配使用taos.dll。
java的问题请@xieyinglin 帮忙看一下。

**Comment by xieyinglin** [comment]
你好，
1. 请使用最新版本 jdbcdriver 再试下
<dependency>
    <groupId>com.taosdata.jdbc</groupId>
    <artifactId>taos-jdbcdriver</artifactId>
    <version>1.0.3</version>
</dependency>

2. 如果还是不行，请把 客户端和 server 的 log 发邮箱 ylxie@taosdata.com ，我们根据 log 分析下

**Comment by qingshenyijiu** [comment]
java 使用最新版还是不行，服务端无日志，客户端直接连不上服务器。

![QQ截图20191118094107](https://user-images.githubusercontent.com/14091724/69018541-e1496380-09e7-11ea-969e-97620a7e8c90.png)

**Comment by xieyinglin** [comment]
你好，默认 window下 客户端日志在 c:\TDengine\log\ 目录下

**Comment by qingshenyijiu** [comment]
这是客户端日志，服务端没打印出任何日志。

![QQ图片20191119094930](https://user-images.githubusercontent.com/14091724/69109195-ef63b680-0ab1-11ea-9e94-987854becf79.png)

**Comment by xieyinglin** [comment]
可以在服务端 /etc/taos/taos.cfg 中增加一列 debugFlag，这样再重启下就可以看到服务端是否接收到客户端请求了，如果还是不行是否可以进行远程，这样效率更高点，如可以请把远程信息发邮箱 ylxie@taosdata.com 

注：远程可以使用 向日葵、teamviewer 等，或者有公有服务器也行

**Comment by qingshenyijiu** [comment]
你好，服务端debug都打开了，没打印任何日志。我测试过抓网络包。用taos.exe能抓到包，但是用java jdbc服务端没抓到任何包。应该就是客户端的问题。

**Comment by xieyinglin** [comment]
方便的话还是远程看下吧
