### ISSUE TITLE
RESTful接口返回空值问题

### ISSUE THREAD

**Issue by effun** [taosdata/TDengine#72]
数据库的空值通过JSON返回时，采用了字符串表达式 "NULL"，例如：
{ "2019-7-16 11:12:13", 1, "NULL" }
是否能改为标准的JSON表达方式null
{ "2019-7-16 11:12:13", 1, null }

**Comment by guanshengliang** [comment]
这个我会调研一下，看看是不是修改。

**Comment by effun** [comment]
感谢回复，希望会有所改进。
