### ISSUE TITLE
failed to read /var/lib/taos/dnode/dnodeCfg.json content is null

### ISSUE THREAD

**Issue by lwfdeveloper** [taosdata/TDengine#7206]
1、taos集群突然不可用，排查日志得出，磁盘空间占满，清理磁盘空间后重启taos，追踪日志读取不到 配置文件 ，ERROR failed to read /var/lib/taos/dnode/dnodeCfg.json, content is null
 
2、为什么使用taos集群后会写入大文件，类似 core.1955 这种文件命名的大文件，每个文件cd都有 30G 以上
查看 dnodeCfg.json 这个文件是空的，非常疑惑！！！

08/06 09:07:50.171247 00002844 UTL  os release:             3.10.0-693.el7.x86_64
08/06 09:07:50.171250 00002844 UTL  os version:             #1 SMP Tue Aug 22 21:09:27 UTC 2017
08/06 09:07:50.171252 00002844 UTL  os machine:             x86_64
08/06 09:07:50.171255 00002844 UTL  dataDir: /var/lib/taos
08/06 09:07:50.171257 00002844 UTL ==================================
08/06 09:07:50.171260 00002844 DND step:dnode-globalcfg is initialized
08/06 09:07:50.171285 00002844 TFS disk /var/lib/taos is mounted to tier level 0 id 0
08/06 09:07:50.172299 00002844 DND dnode storage is initialized at /var/lib/taos/dnode
08/06 09:07:50.172311 00002844 DND step:dnode-storage is initialized
08/06 09:07:50.172325 00002844 DND ERROR failed to read /var/lib/taos/dnode/dnodeCfg.json, content is null
08/06 09:07:50.172332 00002844 DND dnode cfg is initialized
08/06 09:07:50.172335 00002844 DND step:dnode-cfg is initialized
08/06 09:07:50.172366 00002844 DND read file /var/lib/taos/dnode/dnodeEps.json successed
08/06 09:07:50.172383 00002844 DND dnode eps is initialized
08/06 09:07:50.172386 00002844 DND step:dnode-eps is initialized
08/06 09:07:50.172404 00002844 DND read file /var/lib/taos/dnode/mnodeEpSet.json successed
08/06 09:07:50.172407 00002844 DND print minfos, mnodeNum:2 inUse:0
08/06 09:07:50.172409 00002844 DND mnode index:1, h1.taosdata.com:6030
08/06 09:07:50.172412 00002844 DND mnode index:2, h2.taosdata.com:6030
08/06 09:07:50.172429 00002844 DND print minfos, mnodeNum:2 inUse:0
08/06 09:07:50.172431 00002844 DND mnode index:1, h1.taosdata.com:6030
08/06 09:07:50.172434 00002844 DND mnode index:2, h2.taosdata.com:6030
08/06 09:07:50.172436 00002844 DND dnode minfos is initialized
08/06 09:07:50.172439 00002844 DND step:dnode-minfos is initialized
08/06 09:07:50.172467 00002844 WAL wal module is initialized, rsetId:3
08/06 09:07:50.172470 00002844 DND step:dnode-wal is initialized
08/06 09:07:50.172513 00002844 DND step:dnode-sync is initialized
08/06 09:07:50.172548 00002844 DND dnode check is initialized
08/06 09:07:50.172551 00002844 DND step:dnode-check is initialized
08/06 09:07:50.172557 00002844 UTL worker:vquery is initialized, min:16 max:16
08/06 09:07:50.172561 00002844 UTL worker:vfetch is initialized, min:4 max:4

08/06 09:07:50.176294 00002865 VND vgId:5, read /var/lib/taos/vnode/vnode5/version.json successfully, fver:2477274
08/06 09:07:50.180899 00002864 VND vgId:3, load vnode cfg successfully, replcia:2
08/06 09:07:50.180785 00002862 VND vgId:2, load vnode cfg successfully, replcia:1
08/06 09:07:50.180910 00002864 VND vgId:3, dnode:2, h2.taosdata.com:6040
08/06 09:07:50.180917 00002862 VND vgId:2, dnode:1, h1.taosdata.com:6040
08/06 09:07:50.180919 00002864 VND vgId:3, dnode:1, h1.taosdata.com:6040
08/06 09:07:50.181330 00002862 VND vgId:2, read /var/lib/taos/vnode/vnode2/version.json successfully, fver:75744
08/06 09:07:50.182197 00002864 VND vgId:3, read /var/lib/taos/vnode/vnode3/version.json successfully, fver:2
08/06 09:07:50.218964 00002862 WAL vgId:2, file:/var/lib/taos/vnode/vnode2/wal/wal1, will be restored
08/06 09:07:50.219415 00002862 WAL vgId:2, file:/var/lib/taos/vnode/vnode2/wal/wal1, restore success, wver:0
08/06 09:07:50.220281 00002862 WAL vgId:2, wal:0x7fce3802c7f0 file:/var/lib/taos/vnode/vnode2/wal/wal1, it is removed
08/06 09:07:50.232524 00002862 VND vgId:2, sync role changed from offline to master
08/06 09:07:50.232542 00002862 QRY vgId:2, set querymgmt reopen
08/06 09:07:50.386495 00002863 WAL vgId:6, file:/var/lib/taos/vnode/vnode6/wal/wal1, will be restored
08/06 09:07:50.386524 00002863 TDB ERROR vgId:6 failed to get table to insert data, uid 1688849877332693 tid 1
08/06 09:07:50.386599 00002863 TDB ERROR vgId:6 failed to insert data since Invalid table ID
08/06 09:07:50.386606 00002863 TDB ERROR vgId:6 failed to get table to insert data, uid 1688849877332693 tid 1
08/06 09:07:50.386609 00002863 TDB ERROR vgId:6 failed to insert data since Invalid table ID
08/06 09:07:50.387255 00002864 WAL vgId:3, file:/var/lib/taos/vnode/vnode3/wal/wal1, will be restored
08/06 09:07:50.387279 00002864 WAL vgId:3, file:/var/lib/taos/vnode/vnode3/wal/wal1, restore success, wver:0
08/06 09:07:50.387308 00002864 WAL vgId:3, wal:0x7fce24031af0 file:/var/lib/taos/vnode/vnode3/wal/wal1, it is removed
08/06 09:07:50.387588 00002864 VND vgId:3, sync role changed from offline to unsynced
08/06 09:07:50.387600 00002864 QRY vgId:3, set querymgmt reopen
08/06 09:07:50.531563 00002910 VND vgId:3, sync role changed from unsynced to slave
08/06 09:07:50.575543 00002865 WAL vgId:5, file:/var/lib/taos/vnode/vnode5/wal/wal1, will be restored

master上已经被清空了这个文件: var/lib/taos/dnode
![image](https://user-images.githubusercontent.com/37934377/128441621-b49d8207-e6a0-45cd-967f-d4deabb3d58e.png)

![image](https://user-images.githubusercontent.com/37934377/128441661-ffa0c2b7-7b8d-4f25-bb41-a5ee5f4dd65f.png)

salve上还存在这个文件: var/lib/taos/dnode

![image](https://user-images.githubusercontent.com/37934377/128441795-e45f0e29-519e-48f6-a747-94849c8bfc0e.png)

**Comment by yu285** [comment]
您好，可以添加微信15652223354帮您排查

**Comment by watchpoints** [comment]
解决了吗?我遇到同样问题 ，修改了/etc/taos/taos.cfg  dataDir路径 解决。
主要磁盘空间过小 这提示/var/lib/taos/dnode/dnodeCfg.json 不友好
