### ISSUE TITLE
taos connect failed, reason: Unable to establish connection

### ISSUE THREAD

**Issue by liujian016** [taosdata/TDengine#7207]
请问此问题如何解决？

我做了如下动作；
停止了taos服务；
修改了/etc/taos/taos.cfg文件中的路径分别为  mnt/taoslog和mnt/taosdata

结果是：
taos服务无法启动报错，如下图；
![image](https://user-images.githubusercontent.com/24954338/128442569-219615f3-d927-4e41-acbb-8e18059b8b2e.png)

**Comment by yu285** [comment]
已经联系到用户
