### ISSUE TITLE
/etc/taos/taos.cfg  doesn't  update configuration 

### ISSUE THREAD

**Issue by liujian016** [taosdata/TDengine#7208]
请问，我修改cfg之后，似乎没有加载成功，是哪里出错了么？

详细步骤如下：

1） stop服务
2）手动修改了taos.cfg文件如下图所示；
3）taosd -c /etc/taos/taos.cfg (也尝试过taos -c /etc/taos/taos.cfg)
4)  修改新路径的权限为777
5）重启服务；
6) taos -C查询，结果显示我的修改并未成功，显示的路径还是默认路径；

![Uploading image.png…]()

**Comment by yu285** [comment]
注意去掉注释符号。
