### ISSUE TITLE
spring boot + mybatis，SQL report an error 

### ISSUE THREAD

**Issue by s1-001** [taosdata/TDengine#7216]
<update id="dropDB">
        drop database if exists test
    </update>

    <update id="createDB">
        create database if not exists test
    </update>

    <update id="createSuperTable">
        create table if not exists test.weather(ts timestamp, temperature float, humidity float) tags(location nchar(64), groupId int)
    </update>
这几个不需要传入参数的是可以直接执行的，但是
<update id="createTable" parameterType="com.taosdata.example.springbootdemo.domain.Weather">
        create table if not exists test.t#{groupId} using test.weather tags(#{location}, #{groupId})
    </update>
这个传入了参数的，是会报错的 ，  把参数改成真实数据，是可以正常执行的

`Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@8bd076a] was not registered for synchronization because synchronization is not active
JDBC Connection [com.taosdata.jdbc.rs.RestfulConnection@2091833] will not be managed by Spring
==>  Preparing: create table if not exists test.t? using test.weather tags(?, ?) 
==> Parameters: 1(Integer), 北京(String), 1(Integer)
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@8bd076a]

org.springframework.jdbc.UncategorizedSQLException: 
### Cause: java.sql.SQLException: TDengine ERROR (216): Syntax error in SQL
; uncategorized SQLException; SQL state []; error code [534]; TDengine ERROR (216): Syntax error in SQL; nested exception is java.sql.SQLException: TDengine ERROR (216): Syntax error in SQL
`

**Comment by yu285** [comment]
请问jdbc版本和数据库版本分别是？

**Comment by s1-001** [comment]
> 好像jdbc版本和数据库版本分别是？

是的  可能是demo里面的依赖2.18 和最新的服务端版本不行，
我依赖改为2.0.33配version: 2.1.5.0的服务端就可以了
