### ISSUE TITLE
What if I do not need a tag, what is the tags value while create stable.

### ISSUE THREAD

**Issue by liukch** [taosdata/TDengine#7227]
在官方示例中, 就智能电表来说, 它的 location 与 groupId 是 tag
但是 location 与 groupId 不可能是一成不变的
假设我更换了电表的维护组, 那么我可以 alter 这张表把 groupId 设为新的值
但是当我 select 一个老的 timestamp 的时候, groupId 字段就已经是新的值了, 但是当时创建这条数据时的维护组明明就不是当前的这个组, 这就是一条数据被篡改的错误数据
因为设备序列号是表名, 而表名是唯一的, 所以也不可能在更换了 groupId 之后重新创建新表

所以我不是很理解这个 tag 的设计有什么意义, 所以我在做模型设计的时候遇到了思路上的问题
我觉得任何字段都是可以更改的, 更改了就意味着原来的数据发生了错误, 因此他们都不适合做 tag
但是创建 STABLE 的时候又要求必须至少有一个 tag, 所以我不知道该怎么做了

**Comment by yu285** [comment]
数据分为静态数据和动态数据，TDengine的理念是一个设备一张表，这样描述这个设备的信息就是静态数据，为了节约存储和增加聚合查询的效率。TDengine把这个静态数据提取出来做成了标签——比如，设备型号，设备名字，设备地理位置等等。

**Comment by liukch** [comment]
@yu285  静态数据跟动态数据分离我能理解, 但是根据官方只能电表的例子, groupId 设备的维护组看似是一个静态数据, 但是绝对静态吗?
肯定不是, 数据的维护组是有可能变动的, 一旦变动, 请问这个数据模型该如何处理? 使用 alter 语句将 groupId 这个 tag 改变吗?
那么就是我上面提到的问题

**Comment by yu285** [comment]
如果确认我们的设备有些数据确实是会变动的，可以通过多加tag来存储历史tag信息。对查询写入不会有什么影响
