### ISSUE TITLE
 Is it possible to change the datatype of certain column

### ISSUE THREAD

**Issue by malongcn** [taosdata/TDengine#723]
官方文档对列的操作只有“增加列”和“删除列”，没有“修改列属性”

我做了测试：
列“ct1”原属性是binary(20)，想改为“int”，如下操作：
taos> alter table test_column alter column ct1 int;

报错：
TSDB error: invalid SQL: syntax error near "alter column ct1 int;"

**Comment by hzcheng** [comment]
暂时不支持的
