### ISSUE TITLE
precision "us" in the taos.cfg file doesn't work

### ISSUE THREAD

**Issue by malongcn** [taosdata/TDengine#725]
需要时间戳的精度到“微秒”
经过测试，配置文件 /etc/taos/taos.cfg中按如下配置，微妙都不起作用
precision             "us"
precision             ‘us’
precision             us

无论是老库，还是修改配置文件后建新库，插入数据后查看，都没有支持到“微秒”

建库时指定为“us”是起作用的

**Comment by hjxilinx** [comment]
配置文件中的默认选项不建议使用，新版本调整为只通过建库的时候指定。
