### ISSUE TITLE
describe database.table  show result ,but table has been dropped 

### ISSUE THREAD

**Issue by seanchann** [taosdata/TDengine#7259]
**Bug Description**

1. 通过cli控制台删除数据库
2. 通过http的restful接口发起describe的操作，仍然可以正常的返回表的说明，但是cli是正确的返回找不到表

` describe(describe callmetric.prometheus) result {"status":"succ","head":["Field","Type","Length","Note"],"column_meta":[["Field",8,64],["Type",8,20],["Length",4,4],["Note",8,8]],"data":[["ts","TIMESTAMP",8,""],["value","DOUBLE",8,""],["taghash","BINARY",34,"TAG"],["t_host_name","BINARY",32,"TAG"],["t_instance","BINARY",32,"TAG"],["t_job","BINARY",32,"TAG"],["t_port","BINARY",32,"TAG"],["t_scheme","BINARY",32,"TAG"],["t_service_name","BINARY",32,"TAG"]],"rows":9},`

`DB error: Table does not exist (0.000678s)`

**Expected Behavior**

1. http的restful接口访问describe也可以正确的返回为table不存在

**Environment (please complete the following information):**
 - OS: CentOS Linux 8 (Core)
 - 2Core4G, 100G disk
 - TDengine Version :2.1.3.2

**Comment by yu285** [comment]
we will check this

**Comment by yu285** [comment]
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/74105241/131477489-17ab5c7b-45d1-453a-81ec-ab237e3d0896.png">

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/74105241/131478014-107bb8c5-cc33-4cca-a370-03fe8c15380a.png">

2.1.7.2 restful可以正确的返回结果
