### ISSUE TITLE
[14376941.795851] taosd[23224]: segfault at 10 ip 00007f595074c4b5 sp 00007f593f32d480 error 4 in libtaos.so.2.0.20.12[7f5950456000+39f000] TDengine crash

### ISSUE THREAD

**Issue by szlyunnan** [taosdata/TDengine#7265]
**Bug Description**
三个节点的群集, 一直都在运行的; 一段时间后, 突然群集挂了; 起不来。
之前的版本是2.0.20.9, 升级到2.0.20.12还是报图片的错误。

![image](https://user-images.githubusercontent.com/12928768/128705875-c4595323-4383-480e-b635-99ed352afafd.png)

**Environment (please complete the following information):**
 - OS: [ubuntu 18.04]
 - 16G
 - 4C
 - 20G
 - TDengine Version [2.0.20.12]

**Comment by yu285** [comment]
请添加微信15652223354做具体排查
