### ISSUE TITLE
Insert float data ,the result is int, why?

### ISSUE THREAD

**Issue by xiangxud** [taosdata/TDengine#729]
The data floating point data type is used to create the table. The Taos shell is inserted into the table as floating point data. The data returned by the query table column is int data type

**Comment by fangpanpan** [comment]
Could you tell us some of your sql commands and post a screenshot of the data returned? We will try to repeat it and figure out the problem. Thank you.

**Comment by xiangxud** [comment]
感谢及时回复，TD是一个了不起的创新，我准备先在小项目中试用，请多多指导。
我又仔细看了一下，问题没有重现，当时是用nodejs转储mqtt数据到td，发现数据不能变成浮点数，今天用taos shell 测试了一下有对了，程序还没试，不知道是不是json转换时自动四舍五入了
taos&gt; INSERT INTO soil2 VALUES ('2019-11-16 11:12:00.000', 20.89,68.91,17.63);
Query OK, 1 row(s) affected (0.120000s)


taos&gt; select * from soil2;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ts&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; |&nbsp; &nbsp; &nbsp; &nbsp; temp&nbsp; &nbsp; &nbsp; &nbsp; |&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;wc&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; ec&nbsp; &nbsp; &nbsp;|
=============================================================================
&nbsp;19-11-09 00:01:00.000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2089.00000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 6891.00000|&nbsp; &nbsp; &nbsp; &nbsp;1763|
&nbsp;19-11-09 00:01:40.000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2085.00000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 6895.00000|&nbsp; &nbsp; &nbsp; &nbsp;1768|
&nbsp;19-11-09 00:01:50.000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2084.00000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 6896.00000|&nbsp; &nbsp; &nbsp; &nbsp;1767|
&nbsp;19-11-09 00:02:20.000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2081.00000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 6898.00000|&nbsp; &nbsp; &nbsp; &nbsp;1762|
&nbsp;19-11-09 00:02:30.000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2084.00000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 6894.00000|&nbsp; &nbsp; &nbsp; &nbsp;1764|
&nbsp;19-11-09 00:03:20.000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2083.00000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 6898.00000|&nbsp; &nbsp; &nbsp; &nbsp;1763|
&nbsp;19-11-16 11:12:00.000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 20.89000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 68.91000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;17|
Query OK, 7 row(s) in set (0.243000s)


taos&gt; select * from soil;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ts&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; |&nbsp; &nbsp; &nbsp; &nbsp; temp&nbsp; &nbsp; &nbsp; &nbsp; |&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;wc&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; ec&nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp; location&nbsp; &nbsp; &nbsp; |&nbsp; &nbsp;type&nbsp; &nbsp; |
==============================================================================================================
&nbsp;19-11-09 00:01:30.000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2086.00000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 6894.00000|&nbsp; &nbsp; &nbsp; &nbsp;1768|wwg&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 4|
&nbsp;19-11-09 00:02:10.000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2082.00000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 6898.00000|&nbsp; &nbsp; &nbsp; &nbsp;1764|wwg&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 4|
&nbsp;19-11-09 00:03:00.000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2088.00000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 6894.00000|&nbsp; &nbsp; &nbsp; &nbsp;1763|wwg&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 4|
&nbsp;19-11-09 00:03:10.000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2088.00000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 6896.00000|&nbsp; &nbsp; &nbsp; &nbsp;1762|wwg&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 4|
&nbsp;19-11-09 00:01:10.000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2088.00000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 6892.00000|&nbsp; &nbsp; &nbsp; &nbsp;1764|wwg&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 3|
&nbsp;19-11-09 00:01:20.000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2087.00000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 6893.00000|&nbsp; &nbsp; &nbsp; &nbsp;1769|wwg&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 3|
&nbsp;19-11-09 00:02:00.000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2083.00000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 6897.00000|&nbsp; &nbsp; &nbsp; &nbsp;1765|wwg&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 3|
&nbsp;19-11-09 00:02:40.000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2086.00000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 6894.00000|&nbsp; &nbsp; &nbsp; &nbsp;1764|wwg&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 3|
&nbsp;19-11-09 00:02:50.000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2087.00000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 6892.00000|&nbsp; &nbsp; &nbsp; &nbsp;1763|wwg&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 3|
&nbsp;19-11-09 00:03:30.000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2085.00000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 6899.00000|&nbsp; &nbsp; &nbsp; &nbsp;1760|wwg&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 3|
&nbsp;19-11-09 00:01:00.000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2089.00000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 6891.00000|&nbsp; &nbsp; &nbsp; &nbsp;1763|wwg&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2|
&nbsp;19-11-09 00:01:40.000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2085.00000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 6895.00000|&nbsp; &nbsp; &nbsp; &nbsp;1768|wwg&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2|
&nbsp;19-11-09 00:01:50.000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2084.00000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 6896.00000|&nbsp; &nbsp; &nbsp; &nbsp;1767|wwg&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2|
&nbsp;19-11-09 00:02:20.000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2081.00000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 6898.00000|&nbsp; &nbsp; &nbsp; &nbsp;1762|wwg&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2|
&nbsp;19-11-09 00:02:30.000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2084.00000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 6894.00000|&nbsp; &nbsp; &nbsp; &nbsp;1764|wwg&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2|
&nbsp;19-11-09 00:03:20.000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2083.00000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 6898.00000|&nbsp; &nbsp; &nbsp; &nbsp;1763|wwg&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2|
&nbsp;19-11-16 11:12:00.000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 20.89000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 68.91000|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;17|wwg&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2|
Query OK, 17 row(s) in set (0.445000s)



// MQTT 处理订阅消息回调
&nbsp;async function handleMessage(topic, message) {
&nbsp; try {
&nbsp; &nbsp; console.log(topic,message.toString());
&nbsp; &nbsp;//土壤传感器&nbsp;
&nbsp; &nbsp;if(topic.includes("SOIL"))
&nbsp; &nbsp;{
&nbsp; &nbsp; // JSON 转对象
&nbsp; &nbsp; const p = JSON.parse(message.toString());
&nbsp; &nbsp; // 处理浮点数据&nbsp;
&nbsp; &nbsp; const resp = await exec(`
&nbsp; &nbsp; &nbsp; INSERT INTO db_iotmorel.soil${p.RealSoil.Addr} values(
&nbsp; &nbsp; &nbsp; &nbsp;'{p.RealSoil.DATE+' ' +p.RealSoil.TIME}',
&nbsp; &nbsp; &nbsp; &nbsp; {p.RealSoil.TEMP},
&nbsp; &nbsp; &nbsp; &nbsp; {p.RealSoil.WC},
&nbsp; &nbsp; &nbsp; &nbsp; {p.RealSoil.EC},
&nbsp; &nbsp; &nbsp; );`);
&nbsp; &nbsp; console.log(`Exec success:`, resp.data);
}
else
{
&nbsp; //光照传感器
&nbsp; &nbsp;if(topic.includes("ILLUM"))
&nbsp; {
&nbsp; &nbsp; // JSON 转对象
&nbsp; &nbsp; const p = JSON.parse(message.toString());
&nbsp; &nbsp; // 处理浮点数据&nbsp;
&nbsp; &nbsp; const resp = await exec(`
&nbsp; &nbsp; &nbsp; INSERT INTO db_iotmorel.illum${p.RealILLum.Addr} values(
&nbsp; &nbsp; &nbsp; &nbsp; '{p.RealILLum.DATE+' ' +p.RealILLum.TIME}',
&nbsp; &nbsp; &nbsp; &nbsp; {p.RealILLum.TEMP},
&nbsp; &nbsp; &nbsp; &nbsp; {p.RealILLum.WC},
&nbsp; &nbsp; &nbsp; &nbsp; {p.RealILLum.ILLUM},
&nbsp; &nbsp; &nbsp; );`);
&nbsp; &nbsp; console.log(`Exec success:`, resp.data);
&nbsp; }
}
&nbsp; } catch (e) {
&nbsp; &nbsp; console.log(
&nbsp; &nbsp; &nbsp; "exec insert error:",
&nbsp; &nbsp; &nbsp; e.message,
&nbsp; &nbsp; &nbsp; e.response ? e.response.data : ""
&nbsp; &nbsp; );
&nbsp; }
}




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"fangpanpan"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月16日(星期六) 上午9:42
收件人:&nbsp;"taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送:&nbsp;"365603975"<365603975@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [taosdata/TDengine] Insert float data ,the result is int, why? (#729)




Could you tell us some of your sql commands and post a screenshot of the data returned? We will try to repeat it and figure out the problem. Thank you.

**Comment by fangpanpan** [comment]
好的，再有问题的话，欢迎您再提出来。
