### ISSUE TITLE
data not updated when timestamp dumplicated

### ISSUE THREAD

**Issue by qcj212487** [taosdata/TDengine#7306]
TDengine Version：2.1.6-beta
![taosbug](https://user-images.githubusercontent.com/65710124/128989617-4997bb5a-3260-4a9f-9173-00c92e2c4ee5.png)

**Comment by yu285** [comment]
建库的时候 update 参数打开为1了吗？

**Comment by qcj212487** [comment]
update设置的是1
![taosbug2](https://user-images.githubusercontent.com/65710124/128997492-ea9964b0-3820-46ea-a482-f93de9293279.png)

**Comment by yu285** [comment]
last求的是最后一行的非null值，所以你这么看不精确。还是直接把整行数据查出来再插入，这样测试。

**Comment by qcj212487** [comment]
上面是简单的命令行测试，实际程序运行中是一个对象插入更新。

**Comment by cosmic-jc** [comment]
@qcj212487 Thanks for your feedback. Since the problem seems not to appear in our testing, could you plz provide the sql you are using?

**Comment by qcj212487** [comment]
换了台电脑安装相同版本，测试正常。另一台电脑是升级到2.1.6，有什么区别吗，是不是和原来的数据有关系？
![taobug](https://user-images.githubusercontent.com/65710124/129168839-ee9319ed-f9e7-47c6-8cde-d75d11248a3f.png)

**Comment by cosmic-jc** [comment]
I don't think this is related to old data or any upgrading.  Can you still recurring this problem in your old computer or by some steps in your new environment? More details are necessary for us to find out what was happening.

**Comment by cosmic-jc** [comment]
Feel free to reopen it if any progress.
