### ISSUE TITLE
A database cannot be deleted when it has a name more than 30 characters. 

### ISSUE THREAD

**Issue by Sublarge** [taosdata/TDengine#735]
**Bug Description**
if a database has a big name over 30 characters, it cannot be deleted.But drop command return a ok.
**To Reproduce**
1. Execute ` create database bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb;  ` 
and  ` drop database bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb; `
2.  The database is still existed.
3. And if create a table in this database, you will get a   ' table name too long '

**Expected Behavior**
I think this is only a little problem and can be solved by checking the length of database name consistently when created and drop it.

**Environment (please complete the following information):**
ubuntu + official deb package
centos(In docker) + the source from github cloned 

ps: sorry for my poor English

**Comment by plum-lihui** [comment]
多谢！我们也能复现这个问题，定位到问题原因了，会在后续版本解决。
