### ISSUE TITLE
Advisable to use as a mysql replacement primary datastore?

### ISSUE THREAD

**Issue by superdolt** [taosdata/TDengine#7363]
1. Advisable to use as a mysql replacement primary datastore?
2. What's the underlying storage layer? rocksdb?

**Comment by sangshuduo** [comment]
1. Please refer to https://www.taosdata.com/en/documentation/evaluation#scenes to see if your scenario is fitable.
2. We design and develop the storage layer from scratch.

**Comment by hiqsociety** [comment]
1. actually, i read that but it's very vague. it doesnt really say if possible to be used a replacement as primary datastore.
2. possible to send the link for reference on how the storage layer work?
3. how does the clustering/distribution work in detail? (this is to accommodate data design and usage for scalability reasons)
4. possible to list caveats and limitations of using this db in detail? e.g. upper memory limit (what to look out for), disk io issues (with compaction?) large 10TB range db usage? production deployments oops to look out for? so we can do capacity, data design and maintenance preparation work.

**Comment by sangshuduo** [comment]
>     1. actually, i read that but it's very vague. it doesnt really say if possible to be used as replacement as primary datastore.
> 
>     2. possible to send the link for reference on how the storage layer work?
> 
>     3. how does the clustering/distribution work in detail? (this is to accommodate data design and usage for scalability reasons)
> 
>     4. possible to list caveats and limitations of using this db in detail? e.g. upper memory limit (what to look out for), disk io issues (with compaction?) large 10TB range db usage? production deployments oops to look out for? so we can do capacity, data design and maintenance preparation work.

You can find some articles from https://tdengine.medium.com and we will reveal more in the near future.

**Comment by superdolt** [comment]
ok i've read through the medium articles.

is it advisable to migrate production mysql database to tdengine?

**Comment by sangshuduo** [comment]
> ok i've read through the medium articles.
> 
> is it advisable to migrate production mysql database to tdengine?

we are working on it. stay tuned please.

**Comment by superdolt** [comment]
pls do some benchmarks against victoriametrics too. thx

**Comment by fenghuazzm** [comment]
This issue was closed because it has been inactive for too many days.
