### ISSUE TITLE
multiple group by in Outer Query  not supported in 2.1.6 yet

### ISSUE THREAD

**Issue by xForMe** [taosdata/TDengine#7379]
https://github.com/taosdata/TDengine/issues/6960#issue-949413686
![image](https://user-images.githubusercontent.com/8530198/129496960-db074f8a-6b4f-499c-902c-a273bafe5826.png)
我今天测试了multiple group by in Outer Query 这个issue，发下在最新的2.1.6.0版本下依旧不支持

**Comment by yu285** [comment]
![image](https://github.com/taosdata/TDengine/assets/74105241/43237e3f-4824-40e5-8d09-a211ba24d88c)
3.0 已经对查询进行了大幅度优化。目前已经支持改语法。
