### ISSUE TITLE
failed to connect to server

### ISSUE THREAD

**Issue by xiangxud** [taosdata/TDengine#738]
**Bug Description**

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**
Add any other context about the problem here

When I was testing, I found that querying a table would be unstable, and sometimes I would report an error to Query interrupted (failed to connect to server), for some reason.

taos> select *from soil where ts>'2019-11-18 03:00:00.00';
Query interrupted (failed to connect to server), 0 row(s) in set (1.110000s)

taos> select * from soil where ts>'2019-11-18 03:00:00.00';
Query interrupted (failed to connect to server), 0 row(s) in set (1.145000s)

taos> select * from soil where ts>'2019-11-18 06:00:00.00';
          ts          |        temp        |         wc         |    ec     | deviceid0 | deviceid1 | deviceid2 |   addr    |
=============================================================================================================================
 19-11-18 06:01:14.000|            14.03000|            29.77000|         97|    3670072|  894259223|  540489296|          1|
 19-11-18 06:02:39.000|            14.03000|            29.77000|         97|    3670072|  894259223|  540489296|          1|
 19-11-18 06:05:30.000|            14.03000|            29.77000|         97|    3670072|  894259223|  540489296|          1|
 19-11-18 06:06:56.000|            14.03000|            29.77000|         97|    3670072|  894259223| 
。。。。。
taos> select * from soil;
          ts          |        temp        |         wc         |    ec     | deviceid0 | deviceid1 | deviceid2 |   addr    |
=============================================================================================================================
 19-11-18 00:43:01.000|            14.99000|            29.83000|        255|    3670072|  894259223|  540489296|          1|
 19-11-18 00:44:27.000|            14.99000|            29.77000|        255|    3670072|  894259223|  540489296|          1|
 19-11-18 00:45:52.000|            14.99000|            29.77000|        255|    3670072|  894259223|  540489296|          1|
 19-11-18 00:47:17.000|            14.97000|            29.77000|        255|    3670072|  894259223|  540489296|          1|
 19-11-18 00:47:46.000|            14.97000|            29.77000|        255|    3670072|  894259223|  540489296|          1|
Query OK, 289 row(s) in set (4.103000s)

taos> select * from soil;
Query interrupted (failed to connect to server), 0 row(s) in set (1.164000s)

taos>

**Comment by hjxilinx** [comment]
这个表现看着是网络有问题？请问客户端和服务器是在同一台机器吗？

**Comment by xiangxud** [comment]
不在同一机器，这个对网络要求这么高吗，立即返回错误，感觉不出延时就返回错误，有时多几个列名就不行，另外insert时前面不跟列名就报错，只有数值时不能插入报列名错



发自我的iPhone


------------------ Original ------------------

**Comment by hjxilinx** [comment]
不是的，因为TDengine默认使用了UDP的通讯协议，UDP在某些网络上有MTU最大值的问题，由于UDP包大于一个阈值以后，会出现UDP丢包的现象。您的网络是否有这个问题，您可以使用NC命令来测试。

如果希望在这个网络环境下使用，可以稍等一下，后面我们升级的版本会提供TCP的连接选项。

**Comment by xiangxud** [comment]
明白了，谢谢。另外还有一个问题我用tdengine 做grafana 数据源在页面刷新时发现有时数据很长时间不能更新，还有出现query error409 conflict,不知道什么原因

这个也跟网络有关系吗，我是这方面的菜鸟，打扰您了


发自我的iPhone


------------------ Original ------------------

**Comment by xieyinglin** [comment]
页面刷新数据不能更新，可以先通过清除浏览器缓存排除下这方面的原因。
还有能描述下出现 409 问题时的环境么，我看看这边能否复现下
