### ISSUE TITLE
restful api 如何获得token ?官方例子没看见用户名密码登录的api说明

### ISSUE THREAD

**Issue by maikebing** [taosdata/TDengine#74]
如题

**Comment by guanshengliang** [comment]
现在仅支持Basic Authorization，其他授权方法暂不支持

**Comment by maikebing** [comment]
那 token如何获取呢？固定死的？

**Comment by effun** [comment]
Basic验证很简单，首先拼接用户名和密码成一个字符串，中间用冒号分开，然后转换为其字节数组的Base64字符串即可。我用的是UTF8编码没有问题，中文没有试过，应该也不会用得到。

**Comment by maikebing** [comment]
感谢 @effun
