### ISSUE TITLE
A divide by zero bug in qExtbuffer.c

### ISSUE THREAD

**Issue by yiyuaner** [taosdata/TDengine#7408]
In the file `qExtbuffer.c`, the function `createExtMemBuffer` has the following [code](https://github.com/taosdata/TDengine/blob/9f5df9184a52472bcdce04ef33e5f7b6d89390cf/src/query/src/qExtbuffer.c#L37-#L39):

```
pMemBuffer->nElemSize = elemSize;
pMemBuffer->numOfElemsPerPage = (pMemBuffer->pageSize - sizeof(tFilePage)) / pMemBuffer->nElemSize;
```

If the second argument `elemSize` is zero, a divide by zero bug will happen. 
Function `tscCreateGlobalMergerEnv` in `tscGlobalmerge.c` may call `createExtMemBuffer` with a zero value, since it has the following [code](https://github.com/taosdata/TDengine/blob/develop/src/client/src/tscGlobalmerge.c#L429-#L459):
```
int32_t rlen = 0;
...
if (rlen != 0) {
    capacity = nBufferSizes / rlen;
}
... 
// may pass a zero rlen, leading to divide by zero
createExtMemBuffer(nBufferSizes, rlen, pg, pModel);
```

**Comment by fenghuazzm** [comment]
This issue was closed because it has been inactive for too many days.
