### ISSUE TITLE
fields in the 'group by' clause of a continuous query are missed

### ISSUE THREAD

**Issue by malongcn** [taosdata/TDengine#741]
问题：
        创建连续查询，并回写到库中，新建的连续查询结果的表和实际sql输出显示的列不一致：
新建的表中的字段只有时间戳“ts”和一个“count___”, 并没有定义查询时由group by定义的字段

--创建连续查询
taos> create table test_stream as select count(*) from jiankong interval(20s) sliding(10s) group by type, subtype;
Query OK, 1 row(s) affected (0.000297s)

--上述连续查询实际的输出示例：
taos>  select count(*) from jiankong interval(20s)  group by type, subtype;
           ts            |      count(*)       |   type   | subtype  |
======================================================================
 19-11-18 16:53:00.000000|                 2220|delivrd   |delivrd   |
 19-11-18 16:54:00.000000|                 2220|delivrd   |delivrd   |
 19-11-18 16:54:20.000000|                  940|delivrd   |delivrd   |
 19-11-18 16:50:40.000000|                13440|send      |send      |
 19-11-18 16:54:00.000000|                46630|send      |send      |
 19-11-18 16:54:20.000000|                19856|send      |send      |
 19-11-18 16:50:40.000000|                   32|undeliv   |BALANCE   |
 19-11-18 16:51:00.000000|                  112|undeliv   |BALANCE   |
 
 
--自动创建的连续查询的表中实际的数据： 
taos> select * from test_stream;
           ts            |      count___       |
================================================
 19-11-18 16:53:00.000000|                 2220|
 19-11-18 16:53:10.000000|                 1120|
 19-11-18 16:53:20.000000|                 1116|
 19-11-18 16:53:30.000000|                 1124|
 19-11-18 16:53:40.000000|                 1100|
 19-11-18 16:53:50.000000|                 1100|
 19-11-18 16:54:00.000000|                 1100|
 19-11-18 16:54:10.000000|                 1120|
 19-11-18 16:54:20.000000|                 1100|
 19-11-18 16:54:30.000000|                 1120|
 19-11-18 16:54:40.000000|                 1100|
Query OK, 11 row(s) in set (0.000654s)

**Comment by localvar** [comment]
连续查询目前还不能很好的支持 group by，这个问题已经在我们的计划列表里，后续会完善这方面的功能。

**Comment by malongcn** [comment]
知道了，谢谢，支持group by还是很有用处的。
