### ISSUE TITLE
K8s starts four replicas to build the cluster, including three MNodes. One mNode is stopped manually. After the restart, the restarted MNode remains offline, and log. dn3 fails to be created. Database is balancing

### ISSUE THREAD

**Issue by zzhangzd** [taosdata/TDengine#7419]
版本：2.1.6.0

日志：
08/17 02:24:10.569866 00000067 HTP http result queue is opened
08/17 02:24:10.570307 00000094 HTP http server init success at 6041
08/17 02:24:10.570473 00000067 MON monitor module start
08/17 02:24:10.570496 00000067 DND step:dnode-modules is initialized
08/17 02:24:10.571182 00000067 DND dnode shell rpc server is initialized
08/17 02:24:10.571209 00000067 DND step:dnode-shell is initialized
08/17 02:24:10.571228 00000067 DND dnode status timer is initialized
08/17 02:24:10.571231 00000067 DND step:dnode-statustmr is initialized
08/17 02:24:10.571273 00000067 DND dnode telemetry is initialized
08/17 02:24:10.571278 00000067 DND step:dnode-telemetry is initialized
08/17 02:24:10.571281 00000067 DND TDengine is initialized successfully
08/17 02:24:12.013450 00000080 DND print minfos, mnodeNum:1 inUse:0
08/17 02:24:12.013503 00000080 DND mnode index:1, td-tdengine-0.td-tdengine.default.svc.cluster.local:6030
08/17 02:24:12.014397 00000080 DND successed to write /var/lib/taos/dnode/mnodeEpSet.json
08/17 02:24:12.014439 00000080 DND dnodeId is set to 3, clusterId is set to 26a9c70b-fb56-4015-98ad-bf5112b07428
08/17 02:24:12.014801 00000080 DND successed to write /var/lib/taos/dnode/dnodeCfg.json
08/17 02:24:12.015121 00000080 DND successed to write /var/lib/taos/dnode/dnodeEps.json
08/17 02:24:14.623131 00000085 MON ERROR failed to exec sql:create table if not exists log.dn3 using log.dn tags(3, 'td-tdengine-2.td-tdengine.default.svc.cluster.local:6030'), reason:Database is balancing
08/17 02:24:17.663756 00000085 MON ERROR failed to exec sql:create table if not exists log.dn3 using log.dn tags(3, 'td-tdengine-2.td-tdengine.default.svc.cluster.local:6030'), reason:Database is balancing
08/17 02:24:20.708859 00000085 MON ERROR failed to exec sql:create table if not exists log.dn3 using log.dn tags(3, 'td-tdengine-2.td-tdengine.default.svc.cluster.local:6030'), reason:Database is balancing
08/17 02:24:23.744003 00000085 MON ERROR failed to exec sql:create table if not exists log.dn3 using log.dn tags(3, 'td-tdengine-2.td-tdengine.default.svc.cluster.local:6030'), reason:Database is balancing

**Comment by fenghua1997** [comment]
请问是用的涛思官方的 k8s 方案吗？

**Comment by fenghuazzm** [comment]
Closing this issue since there is no response for too many days.
