### ISSUE TITLE
Grafana blockign TaosData plugin as it is unsigned

### ISSUE THREAD

**Issue by vibhubithar** [taosdata/TDengine#7430]
Based on instructions mentioned at https://www.taosdata.com/en/documentation/connections#grafana when tried adding taosdata as a plugin i got error message 

Unsigned plugins were found during plugin initialization. Grafana Labs cannot guarantee the integrity of these plugins. We recommend only using signed plugins.
The following plugins are disabled and not shown in the list below:

    taosdata-tdengine-datasource

Missing signature

**To Reproduce**
1. install latest grafana OSS 8.1.1
2. sudo cp -rf /usr/local/taos/connector/grafanaplugin /var/lib/grafana/plugins/tdengine
3. Click Add data source to enter the Add Data Source page, and enter TDengine in the query box to select Add, as shown in the 

**Expected Behavior**
should be able to add taosdb as [plugin]

**Screenshots**
![grafana-taodb](https://user-images.githubusercontent.com/10491706/129788212-43b0ba05-e46a-438c-942c-3e43af69485d.png)

**Environment (please complete the following information):**
 - OS: ubuntu 18.04
 - Memory, CPU, current Disk Space
 - TDengine Version 2.1.6.0

**Additional Context**

**Comment by sangshuduo** [comment]
Please modify grafana.ini file and add following lines:

[plugins]
enable_alpha = true
allow_loading_unsigned_plugins = taosdata-tdengine-datasource

**Comment by vibhubithar** [comment]
Thanks, @sangshuduo , it worked

Is this a workaround for time being? as the documentation doesn't mention this

Also, the configuration changes to the grafana.ini were not reflected as I forgot to remove ';' semicolon as weirdly they are used to comment the line :)

**Comment by sangshuduo** [comment]
> 
> 
> Thanks, @sangshuduo , it worked
> 
> Is this a workaround for time being? as the documentation doesn't mention this
> 
> Also, the configuration changes to the grafana.ini were not reflected as I forgot to remove ';' semicolon as weirdly they are used to comment the line :)

yes, the extra configuration just need by grafana 8.
we are working on grafana plugin refactoring. later we will submit to grafana official plugin repository.
