### ISSUE TITLE
Is there anyone interested in adding a space (punctuation) between Chinese characters and English terms in the documentation? 

### ISSUE THREAD

**Issue by Aries-Lee1991** [taosdata/TDengine#7438]
[**English description**] For enhancing the readability and understandability of TDengine’s documents, is there anyone interested in adding a space (punctuation) between Chinese characters and English terms in the documentation? 

Take “类标准SQL” for instance, you are expected to add a space between “类标准” and “SQL”, then the revised version should be “类标准 SQL”

Here is the link of document:[evaluation.md]( https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/01.evaluation/docs.md)

[**中文描述**] 为了优化文档可读性，有人愿意为这篇文档中相邻中英文字符间加上空格吗？

以“类标准SQL”为例，你需要在“类标准”和“SQL”之间加上空格，最终呈现为“类标准 SQL”。

文档链接：[evaluation.md]( https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/01.evaluation/docs.md)

**Comment by chitramdasgupta** [comment]
I would like to do this. Can I be assigned this issue?

**Comment by RhnSharma** [comment]
I would like to take this one.

**Comment by jackwener** [comment]
I am willing to take this task up

**Comment by Aries-Lee1991** [comment]
LGTM

**Comment by Aries-Lee1991** [comment]
@jackwener https://github.com/taosdata/TDengine/pull/7476 is submitted to the master branch, but the default branch of TDengine project is develop. Your name will appear in the contributor list only when you submit to the develop branch. Therefore, please resubmit to the develop branch. Thank you.

**Comment by jackwener** [comment]
@Aries-Lee1991 It's ok. Thanks for your remind.

**Comment by Aries-Lee1991** [comment]
@jackwener We will make a certificate for the new contributor and give a souvenir. Can you leave your contact information?
