### ISSUE TITLE
no taos in java.library.path

### ISSUE THREAD

**Issue by bluewaterstar** [taosdata/TDengine#7493]
**Bug Description**
在装有TD客户端的服务器拉取kafka数据到TD服务端的时候，客户端程序报：
java.lang.UnsatisfiedLinkError: no taos in java.library.path

**To Reproduce**
已经按官网的提示，确定对应目录里添加了libtaos.so，jdk的lib也添加了，但还是报这个错误

**Expected Behavior**
希望能帮忙解决一下，不胜感激

**Screenshots**
![43b7874f8bc276f0a20d790af7a35dd](https://user-images.githubusercontent.com/39643648/130210721-f951b131-0c29-4539-a378-34326f1d76c2.png)
![image](https://user-images.githubusercontent.com/39643648/130211004-60da612a-8ce1-4f33-978f-914c9991248a.png)

![image](https://user-images.githubusercontent.com/39643648/130210834-cde8d3c0-c4f3-4906-9de5-6c3b2375dfe5.png)

**Environment (please complete the following information):**
 CentOS 7.0
java version "1.8.0_261"
TD version: 2.0.20.12

**Additional Context**

**Comment by bluewaterstar** [comment]
解决了，要把libtaos.so这个包，拷入linux根目录 / ，试了一周，太难了。。。

**Comment by bluewaterstar** [comment]
解决了，要把libtaos.so这个包，拷入linux根目录 / ，试了一周，太难了。。。

**Comment by DomiPapa** [comment]
如果在mac环境下的idea 可以采用如下思路
1、指定依赖的非Java库文件路径
<img width="749" alt="image" src="https://user-images.githubusercontent.com/33115671/226079864-b292cd69-1fe7-4af8-a654-65e883bb04b7.png">
2、确认jdk版本与taosclient版本都是x64或者arm64

**Comment by z153114659** [comment]
> 解决了，要把libtaos.so这个包，拷入linux根目录 / ，试了一周，太难了。。。

请问你们有升到3点几的版本吗  我这边装了客户端 部署还是报了这个Lib

**Comment by sangshuduo** [comment]
本质上这是个 Java 环境配置的问题，和 TDengine 没什么关系

**Comment by maxid** [comment]
就是没有做好云原生
