### ISSUE TITLE
Is there anyone interested in completing part of the English documentation?

### ISSUE THREAD

**Issue by zhaoyanggh** [taosdata/TDengine#7495]
In the Chinese documentation (https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/04.model/docs.md), under the "创建库(Create a database)" title and within "注意(note)", there are three things that need to be noticed. 
However, in the corresponding English documentation (https://github.com/taosdata/TDengine/blob/develop/documentation20/en/04.model/docs.md) at the same location, there are only two. Is there anyone willing to translate the missing one and add it to English documentation?

**Comment by lovetaitai** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

Thanks, assigned it to you.

**Comment by Aries-Lee1991** [comment]
#7698 was merged.
