### ISSUE TITLE
concurrent query performance issue

### ISSUE THREAD

**Issue by sj-dev** [taosdata/TDengine#7503]
#最小值0 表示只有1个查询线程；最大值2表示最大建立2倍CPU核数的查询线程。默认为1，表示最大和CPU核数相等的查询线程。该值可以为小数，即0.5表示最大建立CPU核数一半的查询线程。
ratioOfQueryCores       2.0   （测试有用,最大值只能2.0）
参数中调整上面这一个可以进行多线程查询了，而且二个查询不会相互影响，但是三个就会影响的。

测试方式：
select  count(*) from t1;  正常返回需要10秒；
select  count(*) from t2;  正常返回需要2秒；

二个线程同时查询t1;一个线程同时查询t2;
t2返回的时间变成了8秒。说明线程之间存在干扰。

一个线程查询t1，一个线程查询t2
t2返回是正常的2秒，说明线程之间没有干扰。

请问ratioOfQueryCores这一个操作系统有多少核，是通过那一个查询出来的。是下列那一个？
1、查看 CPU 物理个数
　　grep 'physical id' /proc/cpuinfo | sort -u | wc -l
2、查看 CPU 核心数量
　　grep 'core id' /proc/cpuinfo | sort -u | wc -l
3、查看 CPU 线程数
　　grep 'processor' /proc/cpuinfo | sort -u | wc -l

**Comment by sj-dev** [comment]
<img width="437" alt="image" src="https://user-images.githubusercontent.com/10184494/130263397-ee76f62b-6cea-4e75-91f3-4e3f52cdff16.png">
但是我服务器是2核，是不是应该同时支持2*2=4才对，为什么不配置的时候，感觉只有1个核心同时可以查询不影响，配置成2.0了，就可以2个查询同时查，相互不影响了。为什么不是4个相互不影响呢？

**Comment by trivita** [comment]
processor的数量是线程数
cpu cores是物理核数
有smt的情况下，processor的总数是cpu cores的2倍，关键是你得有smt

**Comment by trivita** [comment]
Simultaneous multithreading (SMT)

**Comment by sj-dev** [comment]
请问，您说的这一个需要怎么样才可以开启，现在我们的都是centos7环境，有相关的资料提供怎么开启吗？
