### ISSUE TITLE
query issue on tag 

### ISSUE THREAD

**Issue by xForMe** [taosdata/TDengine#7504]
data_ts是时间戳格式，tag字段，查询>的时候没有查询到任何数据，但是数据库中存在满足的条件
![image](https://user-images.githubusercontent.com/8530198/130313661-446399d5-543b-44ae-89cd-438d3d8c5618.png)

**Comment by yu285** [comment]
1) TAGS 列的数据类型不能是 timestamp 类型；（从 2.1.3.0 版本开始，TAGS 列中支持使用 timestamp 类型，但需注意在 TAGS 中的 timestamp 列写入数据时需要提供给定值，而暂不支持四则运算，例如 NOW + 10s 这类表达式）
