### ISSUE TITLE
Is there anyone intersted in helping us with the documentation?

### ISSUE THREAD

**Issue by jiacy-jcy** [taosdata/TDengine#7511]
Here are some errors both in the chinese documentation(https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/01.evaluation/docs.md) and english documentation(https://github.com/taosdata/TDengine/blob/develop/documentation20/en/01.evaluation/docs.md) such as incorrect abbreviations.The document mistakenly wrote IoT instead of IoT,Taos Data instead of TAOS Data. Is there anyone willing to help us to fix these errors in the near future?

我们的中文文档和英文文档存在一些描述错误，比如错将IoT写为IOT，错将TAOS Data写为Taos Data，有人愿意帮助我们校对一下这两个文档，并对类似错误进行修正么？

**Comment by daniellekush** [comment]
I'd like to help with the English documentation. Unfortunately the link you sent for it leads to a page that cannot be found.

**Comment by Aries-Lee1991** [comment]
> I'd like to help with the English documentation. Unfortunately the link you sent for it leads to a page that cannot be found.

Hi, @daniellekush, are you still doing this task？

**Comment by Aries-Lee1991** [comment]
This task is currently unmanned. Does anyone want to do it?

**Comment by richard1230** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

Assigned it to you

**Comment by Aries-Lee1991** [comment]
@richard1230 How's the issue going?

**Comment by Aries-Lee1991** [comment]
> @richard1230 How's the issue going?

the task is delayed.  @richard1230 
If you haven't done it, I will release the task

**Comment by Aries-Lee1991** [comment]
This task is currently unmanned. Does anyone want to do it?

**Comment by hibriansun** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

Assigned it to you

**Comment by Aries-Lee1991** [comment]
@hibriansun We will make a certificate for the new contributor and give a souvenir. Can you leave your contact information or add my wechat (690754649).
