### ISSUE TITLE
JDBC Driver can not be found

### ISSUE THREAD

**Issue by mudalu** [taosdata/TDengine#76]
The official website and github can not be found.

**Comment by francis-du** [comment]
### 1.You can build this source code
https://github.com/taosdata/TDengine/tree/master/src/connector/jdbc
### 2.Go to your installation location to find it.
 `/usr/local/taos/connector/taos-jdbcdriver-1.0.0-dist.jar`

**Comment by mudalu** [comment]
> ### 1.You can build this source code
> https://github.com/taosdata/TDengine/tree/master/src/connector/jdbc
> 
> ### 2.Go to your installation location to find it.
> `/usr/local/taos/connector/taos-jdbcdriver-1.0.0-dist.jar`

Thanks.so,what's the location of subscribe-1.0.1-sources .jar?

**Comment by plum-lihui** [comment]
subscribe在开源版本暂时还没有发布，正在整合中，很快就会更新发布。

**Comment by johnnyhou327** [comment]
@mudalu The ``subscribe-1.0.1-sources.jar`` is part of the commercial version of TDengine and is not released to this open-sourced project yet.
