### ISSUE TITLE
timestamp

### ISSUE THREAD

**Issue by MasonYangD** [taosdata/TDengine#760]
你好：
我想问下，假设我数据库中一张表，插入第一条数据时间戳为2019-11-22 18：00：00，之后插入数据的时间戳必须大于该时间吗？测试过，如果小于该时间戳是无法插入数据库的。
谢谢

**Comment by fangpanpan** [comment]
如果您使用insert语句进行插入的话，那么时间戳必须是递增的，如果要插入历史数据，可以用import

**Comment by MasonYangD** [comment]
如果我一直用import写入数据可以吗？有什么影响吗？
我测试了在写入20万条数据时，数据库崩了，且无法启动，报如下错误
11/25 10:53:55.043195 7ffa26eee740 HTP failed to open telegraf schema config file:/etc/taos/taos.telegraf.cfg, use default schema
11/25 10:53:55.046370 7ffa26eee740 ERROR DND vid:1 sid:2 id:0.data.s505_2019_1, data is already imported to file
11/25 10:53:55.046688 7ffa26eee740 ERROR DND vid:1 sid:2 id:0.data.s505_2019_1, data is already imported to file

**Comment by fangpanpan** [comment]
> 如果我一直用import写入数据可以吗？有什么影响吗？
> 我测试了在写入20万条数据时，数据库崩了，且无法启动，报如下错误
> 11/25 10:53:55.043195 7ffa26eee740 HTP failed to open telegraf schema config file:/etc/taos/taos.telegraf.cfg, use default schema
> 11/25 10:53:55.046370 7ffa26eee740 ERROR DND vid:1 sid:2 id:0.data.s505_2019_1, data is already imported to file
> 11/25 10:53:55.046688 7ffa26eee740 ERROR DND vid:1 sid:2 id:0.data.s505_2019_1, data is already imported to file

可以一直用import，如果时间是顺序的，import的操作和insert是一样的。您是在用telegraph 导入数据吗？ 具体问题可能需要远程过去查看一下，您可以将微信号发到fpan@taosdata.com.

**Comment by MasonYangD** [comment]
你好，已发送至邮箱

我并未用telegraph，我是在用R，写入数据。当用insert时，数据写入会少很多(因为时间戳未递增)，后用import写入，直接导致数据库崩溃。

**Comment by sangshuduo** [comment]
请使用 2.0 验证，如果有问题请提交新 issue
