### ISSUE TITLE
Error "Invalid or incomplete multibyte or wide character" is reported when using C/C ++ taos_query to insert nchar characters. How can I insert nchar Chinese characters correctly?

### ISSUE THREAD

**Issue by Yuanbo-2019** [taosdata/TDengine#7627]
问题： 使用taos_query向有nchar类型的表插入中文字符，报错Invalid or incomplete multibyte or wide character，QString, char *,wchar_t怎么转都不行

版本： 2.0.20.9

编码：utf-8

代码：
![image](https://user-images.githubusercontent.com/57087115/130954689-c102b99e-c214-480b-8358-47990270fb12.png)
![image](https://user-images.githubusercontent.com/57087115/130954605-d421c5b2-9715-4643-89ab-04d536276461.png)
![image](https://user-images.githubusercontent.com/57087115/130950882-ee7c149d-9530-4601-a39a-7c27cf4a05b4.png)

报错：
![image](https://user-images.githubusercontent.com/57087115/130950795-dffa6238-07d3-4dfc-bb0e-4ab071feed2e.png)

**Comment by yu285** [comment]
是在win的客户端跑的吗

**Comment by hjxilinx** [comment]
请和操作系统编码保持一致，在配置文件中通过locale设置编码。
