### ISSUE TITLE
In order to improve accuracy, could someone unify the word in the following place in the article?

### ISSUE THREAD

**Issue by jiajingbin** [taosdata/TDengine#7628]
To be precise, this word should be unified with other places
![image](https://user-images.githubusercontent.com/39030567/130955684-9309291f-c356-4e48-b104-2576bc15bf90.png)

**Comment by citizen233** [comment]
pick up challenge

**Comment by jiajingbin** [comment]
> pick up challenge

Thanks, MD link is ---> https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/10.cluster/docs.md

**Comment by jiajingbin** [comment]
> pick up challenge

Assigned it to you

**Comment by zhanglianlei** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge
@zhanglianlei 
sorry, The task has been assigned to @citizen233 . 
Here are two tasks that have not been assigned. If you are interested, you can have a look.
https://github.com/taosdata/TDengine/issues/7629
https://github.com/taosdata/TDengine/issues/7648
