### ISSUE TITLE
In order to improve rigor, could someone unify this word with the taos.cfg

### ISSUE THREAD

**Issue by jiajingbin** [taosdata/TDengine#7629]
This word is not consistent with taos.cfg configuration file as following picture, and actually more than these two items are not accurate.
![image](https://user-images.githubusercontent.com/39030567/130957019-3b6b9357-80e6-44d4-8d13-40511c7e5afa.png)

**Comment by citizen233** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

I saw you doing another task（https://github.com/taosdata/TDengine/issues/7628）. Each novice can only do one task

**Comment by jiajingbin** [comment]
> pick up challenge

Thanks, and MD link is ---> https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/10.cluster/docs.md

**Comment by z1q1q7** [comment]
pick up challenge

**Comment by jiajingbin** [comment]
> pick up challenge

Thanks, MD link is ---> https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/10.cluster/docs.md

**Comment by jiajingbin** [comment]
> pick up challenge

Assigned it to you
