### ISSUE TITLE
advice reader to configure hosts 

### ISSUE THREAD

**Issue by xleili** [taosdata/TDengine#7648]
github doc link：https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/08.connector/docs.md
 In this paragraph circled with red rectangle.

![wormhunter1](https://user-images.githubusercontent.com/85657333/131077072-fe41a974-eda2-439b-8ef3-f238ec8ffed3.png)

It is better to advice the user to configure their hosts file. Becuase this is very easy for reader to forget to edit their hosts file which will lead to the client cannot  establish connection with the server. Some time will occur this error "unable to resolve FQDN"

Compare with installation client on windows at the link https://www.taosdata.com/cn/documentation/connector.  especially the tips.

**Comment by zhanglianlei** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

One person can only be one task's assignee.

**Comment by Aries-Lee1991** [comment]
This task is currently unmanned. Does anyone want to do it?

**Comment by RobbieDragon233** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

Assigned it to you.

**Comment by Aries-Lee1991** [comment]
@RobbieDragon233 We will make a certificate for the new contributor and give a souvenir. Can you leave your contact information or add my wechat (690754649).
