### ISSUE TITLE
the explaination of tdengine's  support platform matrix  should be more clear

### ISSUE THREAD

**Issue by xleili** [taosdata/TDengine#7650]
offical document link:https://www.taosdata.com/cn/documentation/connector
contribute on GitHub link:https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/08.connector/docs.md
![wormhunt2](https://user-images.githubusercontent.com/85657333/131078829-29009575-61d9-4efe-8726-59de4a3d0de5.png)

Like the picture there are some brief explanation for every label that appears in this matrix . At first, I think these not clear enough and sometime will lead misunderstanding. eg. the statement of solid circle which just notice that official just test this platform, and I still not sure that is tdengine is supporting the corresponding platform or not.  secondly, also missed the explanation of "--".

**Comment by citizen233** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
I saw you doing another task（https://github.com/taosdata/TDengine/issues/7628）. Each novice can only do one task

**Comment by z1q1q7** [comment]
pick up challenge

**Comment by xleili** [comment]
assigned it to you

**Comment by Aries-Lee1991** [comment]
@z1q1q7 We will make a certificate for the new contributor and give a souvenir. Can you leave your contact information or add my wechat (690754649).
