### ISSUE TITLE
Translation for "Downsampling"

### ISSUE THREAD

**Issue by glzhao89** [taosdata/TDengine#7652]
In document "TAOS SQL" section:
https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/12.taos-sql/docs.md

![截屏2021-08-27 下午2 12 23](https://user-images.githubusercontent.com/36554565/131080860-e51f8b7b-b7ba-4cf0-abf4-2894cb7aadb8.png)

The Chinese translation for "downsampling" is "降频", which has meaning "reduce frequency".  The original meaning for English word  "downsampling" should be "reduce sampling rate/frequency" of time-series data/signal. It would be better to pick up a more accurate Chinese word for better understanding.

**Comment by sangshuduo** [comment]
应该是降采样吧

**Comment by glzhao89** [comment]
> 应该是降采样吧

Exactly. Looking for contributors who're interested for making this change :)

**Comment by kartist** [comment]
pick up challenge

**Comment by glzhao89** [comment]
> pick up challenge

Thanks. assigned it to you.

**Comment by Aries-Lee1991** [comment]
#7697 was merged.

**Comment by Aries-Lee1991** [comment]
We will make a certificate for the new contributor and give a souvenir. Can you leave your contact information or add my wechat (690754649). @kartist
