### ISSUE TITLE
Database is balancing issue

### ISSUE THREAD

**Issue by zzhangzd** [taosdata/TDengine#7657]
08/27 15:44:10.655570 00000046 DND dnode telemetry is initialized

08/27 15:44:10.655585 00000046 DND step:dnode-telemetry is initialized

08/27 15:44:10.655589 00000046 DND TDengine is initialized successfully

08/27 15:44:40.663142 00000117 TSC ERROR 0xd async result callback, code:Database is balancing

08/27 15:44:40.663218 00000097 MON ERROR failed to save system info, reason:Database is balancing, sql:insert into log.dn2 values(1630050280660324, 0.025388, 12.249561, 16, 15.710938, 21847.714844, 64428, 15.807659, 196, 35.561718, 87.989258, 95.678711, 0, 0, 0)

08/27 15:45:10.667465 00000118 TSC ERROR 0x1a async result callback, code:Database is balancing

08/27 15:45:10.667545 00000097 MON ERROR failed to save system info, reason:Database is balancing, sql:insert into log.dn2 values(1630050310666815, 0.029631, 11.680918, 16, 17.500000, 21875.832031, 64428, 15.808041, 196, 39.672657, 80.340820, 38.736328, 3, 0, 1)

08/27 15:45:40.671848 00000119 TSC ERROR 0x1c async result callback, code:Database is balancing

08/27 15:45:40.671919 00000097 MON ERROR failed to save system info, reason:Database is balancing, sql:insert into log.dn2 values(1630050340671067, 0.029642, 12.402871, 16, 17.500000, 21874.644531, 64428, 15.808655, 196, 35.651043, 49.373047, 23.776367, 0, 0, 0)

08/27 15:46:10.675286 00000120 TSC ERROR 0x1e async result callback, code:Database is balancing

08/27 15:46:10.675369 00000097 MON ERROR failed to save system info, reason:Database is balancing, sql:insert into log.dn2 values(1630050370674617, 0.027531, 12.147395, 16, 17.757812, 21892.238281, 64428, 15.809055, 196, 36.217186, 50.975586, 24.459961, 0, 0, 0)

08/27 15:46:40.679288 00000117 TSC ERROR 0x20 async result callback, code:Database is balancing

08/27 15:46:40.679382 00000097 MON ERROR failed to save system info, reason:Database is balancing, sql:insert into log.dn2 values(1630050400678567, 0.027521, 12.744517, 16, 18.253906, 21892.773438, 64428, 15.809677, 196, 41.507290, 51.276367, 24.715820, 0, 0, 1)

08/27 15:47:10.683019 00000118 TSC ERROR 0x22 async result callback, code:Database is balancing

08/27 15:47:10.683100 00000097 MON ERROR failed to save system info, reason:Database is balancing, sql:insert into log.dn2 values(1630050430682264, 0.029633, 11.908390, 16, 18.253906, 21920.214844, 64428, 15.810066, 196, 41.909374, 50.975586, 24.715820, 0, 0, 1)

08/27 15:47:40.686656 00000119 TSC ERROR 0x24 async result callback, code:Database is balancing

08/27 15:47:40.686733 00000097 MON ERROR failed to save system info, reason:Database is balancing, sql:insert into log.dn2 values(1630050460686053, 0.029614, 12.004230, 16, 18.253906, 21897.562500, 64428, 15.810665, 196, 40.839321, 50.975586, 24.459961, 0, 0, 0)

08/27 15:48:10.690312 00000120 TSC ERROR 0x26 async result callback, code:Database is balancing

08/27 15:48:10.690378 00000097 MON ERROR failed to save system info, reason:Database is balancing, sql:insert into log.dn2 values(1630050490689708, 0.029652, 11.650958, 16, 18.253906, 21920.863281, 64428, 15.811077, 196, 40.048176, 49.373047, 23.776367, 0, 0, 0)

08/27 15:48:40.693971 00000117 TSC ERROR 0x28 async result callback, code:Database is balancing

08/27 15:48:40.694055 00000097 MON ERROR failed to save system info, reason:Database is balancing, sql:insert into log.dn2 values(1630050520693315, 0.033897, 12.425321, 16, 18.253906, 21864.578125, 64428, 15.811684, 196, 40.685677, 50.976562, 24.459961, 0, 0, 0)

08/27 15:49:10.697485 00000118 TSC ERROR 0x2a async result callback, code:Database is balancing

08/27 15:49:10.697578 00000097 MON ERROR failed to save system info, reason:Database is balancing, sql:insert into log.dn2 values(1630050550696811, 0.033872, 12.007791, 16, 18.253906, 21884.582031, 64428, 15.812073, 196, 40.728386, 50.976562, 24.459961, 0, 0, 0)

08/27 15:49:40.701105 00000119 TSC ERROR 0x2c async result callback, code:Database is balancing

08/27 15:49:40.701167 00000097 MON ERROR failed to save system info, reason:Database is balancing, sql:insert into log.dn2 values(1630050580700447, 0.035971, 12.450275, 16, 18.253906, 21897.644531, 64428, 15.812679, 196, 40.541405, 50.976562, 24.459961, 0, 0, 0)

08/27 15:50:10.704752 00000120 TSC ERROR 0x2e async result callback, code:Database is balancing

08/27 15:50:10.704839 00000097 MON ERROR failed to save system info, reason:Database is balancing, sql:insert into log.dn2 values(1630050610704058, 0.033902, 11.759720, 16, 18.253906, 21908.636719, 64428, 15.813118, 196, 40.761196, 50.977539, 24.459961, 0, 0, 0)

08/27 15:50:40.708070 00000117 TSC ERROR 0x30 async result callback, code:Database is balancing

08/27 15:50:40.708158 00000097 MON ERROR failed to save system info, reason:Database is balancing, sql:insert into log.dn2 values(1630050640707499, 0.029651, 12.207726, 16, 18.253906, 21898.722656, 64428, 15.813744, 196, 39.892189, 49.375000, 23.776367, 0, 0, 0)

08/27 15:51:10.711849 00000118 TSC ERROR 0x32 async result callback, code:Database is balancing

08/27 15:51:10.711927 00000097 MON ERROR failed to save system info, reason:Database is balancing, sql:insert into log.dn2 values(1630050670711134, 0.025396, 11.423855, 16, 18.253906, 21912.468750, 64428, 15.814137, 196, 40.469273, 50.978516, 24.459961, 0, 0, 0)

08/27 15:51:40.716026 00000119 TSC ERROR 0x34 async result callback, code:Database is balancing

08/27 15:51:40.716110 00000097 MON ERROR failed to save system info, reason:Database is balancing, sql:insert into log.dn2 values(1630050700715291, 0.027516, 12.197858, 16, 18.253906, 21914.562500, 64428, 15.814720, 196, 40.363022, 50.978516, 24.459961, 0, 0, 0)

08/27 15:52:10.719517 00000120 TSC ERROR 0x36 async result callback, code:Database is balancing

08/27 15:52:10.719589 00000097 MON ERROR failed to save system info, reason:Database is balancing, sql:insert into log.dn2 values(1630050730718848, 0.027556, 12.061217, 16, 18.253906, 21923.550781, 64428, 15.815121, 196, 40.717449, 50.978516, 24.459961, 0, 0, 0)

**Comment by zzhangzd** [comment]
Tdengine 集群，使用过程中删掉一个slave 节点，节点重启后不能重新加入到集群里面，状态显示offline，日志报错Database is balancing Database is balancing issue，然后再删除另外一个slave节点，集群崩溃，自始至终未对master节点做任何操作

**Comment by zzhangzd** [comment]
Tdengine 集群，使用过程中删掉一个slave 节点，节点重启后不能重新加入到集群里面，状态显示offline，日志无报错但是show mnodes 显示offline，然后再删除另外一个slave节点，集群崩溃，自始至终未对master节点做任何操作

**Comment by zzhangzd** [comment]
镜像版本 ： zitsen/tdengine-server:2.1.1.0

**Comment by yu285** [comment]
麻烦使用最新的 3.2.2.0 版本
