### ISSUE TITLE
TDengine Tag using help wanted

### ISSUE THREAD

**Issue by xForMe** [taosdata/TDengine#7659]
![image](https://user-images.githubusercontent.com/8530198/131101406-7f32fe21-8d14-43f3-a1a9-2f554b105bb5.png)
现有的一批数据
插入之后data_ts（tag字段）不对
![image](https://user-images.githubusercontent.com/8530198/131101390-2bfdeea7-8489-4a8d-9a7a-66a2d1b48379.png)

**Comment by kartist** [comment]
你这个使用方式存在问题,  tdengine中的 tag是创建表的时候已经指定了, 如果同一个表数据插入时, 指定的tag不一样,是不生效的,
如果业务场景存在同一个设备要不同的tag, 可以考虑将表名调整为 时间+设备

**Comment by xForMe** [comment]
多谢
