### ISSUE TITLE
core dump when insert 

### ISSUE THREAD

**Issue by z1q1q7** [taosdata/TDengine#7666]
**Bug Description**
写入数据的过程中taosd core了,而且再也启动不起来了，一起来就core

**To Reproduce**
改造influx_inspect支持读出数据格式化并写入taos...
具体哪部分数据导致的还不清楚

**Expected Behavior**
无论如何服务端不应该退出

**Screenshots**
core gdb bt看:
(gdb) bt
#0  0x00007ff73cc3f387 in raise () from /lib64/libc.so.6
#1  0x00007ff73cc40bb8 in abort () from /lib64/libc.so.6
#2  0x00007ff73cc381a6 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007ff73cc38252 in __assert_fail () from /lib64/libc.so.6
#4  0x00007ff73d9c27ac in dataColAppendVal (pCol=0x7ff59402bc50, value=0x7ff5940b1590,
    numOfRows=2880, maxPoints=4096)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/common/src/tdataformat.c:267
#5  0x00007ff73d9c436e in tdMergeTwoDataCols (target=0x7ff594008900, src1=0x7ff59402ab40,
    iter1=0x7ff72b2b71f4, limit1=606, src2=0x7ff594008930, iter2=0x7ff72b2b71f0, limit2=2880,
    tRows=3486, forceSetNull=false)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/common/src/tdataformat.c:581
#6  0x00007ff73d9c3f12 in tdMergeDataCols (target=0x7ff594008900, source=0x7ff594008930,
    rowsToMerge=2880, pOffset=0x7ff72b2b71f0, forceSetNull=false)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/common/src/tdataformat.c:549
#7  0x00007ff73da902c8 in tsdbLoadBlockData (pReadh=0x7ff72b2b76a8, pBlock=0x7ff59402bdd8,
    pBlkInfo=0x0)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbReadImpl.c:262
#8  0x00007ff73daa59bd in tsdbMergeMemData (pCommith=0x7ff72b2b7650, pIter=0x7ff594008a70, bidx=0)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbCommit.c:1160
#9  0x00007ff73daa38bd in tsdbCommitToTable (pCommith=0x7ff72b2b7650, tid=17)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbCommit.c:828
#10 0x00007ff73daa28ed in tsdbCommitToFile (pCommith=0x7ff72b2b7650, pSet=0x7ff72043bb20, fid=1886)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbCommit.c:584
#11 0x00007ff73daa252b in tsdbCommitTSData (pRepo=0x7ff68c001090)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbCommit.c:509
#12 0x00007ff73da9f140 in tsdbCommitData (pRepo=0x7ff68c001090)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbCommit.c:102
#13 0x00007ff73da9a52a in tsdbLoopCommit (arg=0x0)
    at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbCommitQueue.c:186
#14 0x00007ff73cfdeea5 in start_thread () from /lib64/libpthread.so.0
#15 0x00007ff73cd0796d in clone () from /lib64/libc.so.6

**Comment by z1q1q7** [comment]
> 请问是什么版本？

taos --version
version: 2.1.7.2

最新版

**Comment by z1q1q7** [comment]
今

> **Bug Description**
> 写入数据的过程中taosd core了,而且再也启动不起来了，一起来就core
> 
> **To Reproduce**
> 改造influx_inspect支持读出数据格式化并写入taos...
> 具体哪部分数据导致的还不清楚
> 
> **Expected Behavior**
> 无论如何服务端不应该退出
> 
> **Screenshots**
> core gdb bt看:
> (gdb) bt
> #0 0x00007ff73cc3f387 in raise () from /lib64/libc.so.6
> #1 0x00007ff73cc40bb8 in abort () from /lib64/libc.so.6
> #2 0x00007ff73cc381a6 in __assert_fail_base () from /lib64/libc.so.6
> #3 0x00007ff73cc38252 in __assert_fail () from /lib64/libc.so.6
> #4 0x00007ff73d9c27ac in dataColAppendVal (pCol=0x7ff59402bc50, value=0x7ff5940b1590,
> numOfRows=2880, maxPoints=4096)
> at /home/ubuntu/workroom/jenkins/TDinternal/community/src/common/src/tdataformat.c:267
> #5 0x00007ff73d9c436e in tdMergeTwoDataCols (target=0x7ff594008900, src1=0x7ff59402ab40,
> iter1=0x7ff72b2b71f4, limit1=606, src2=0x7ff594008930, iter2=0x7ff72b2b71f0, limit2=2880,
> tRows=3486, forceSetNull=false)
> at /home/ubuntu/workroom/jenkins/TDinternal/community/src/common/src/tdataformat.c:581
> #6 0x00007ff73d9c3f12 in tdMergeDataCols (target=0x7ff594008900, source=0x7ff594008930,
> rowsToMerge=2880, pOffset=0x7ff72b2b71f0, forceSetNull=false)
> at /home/ubuntu/workroom/jenkins/TDinternal/community/src/common/src/tdataformat.c:549
> #7 0x00007ff73da902c8 in tsdbLoadBlockData (pReadh=0x7ff72b2b76a8, pBlock=0x7ff59402bdd8,
> pBlkInfo=0x0)
> at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbReadImpl.c:262
> #8 0x00007ff73daa59bd in tsdbMergeMemData (pCommith=0x7ff72b2b7650, pIter=0x7ff594008a70, bidx=0)
> at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbCommit.c:1160
> #9 0x00007ff73daa38bd in tsdbCommitToTable (pCommith=0x7ff72b2b7650, tid=17)
> at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbCommit.c:828
> #10 0x00007ff73daa28ed in tsdbCommitToFile (pCommith=0x7ff72b2b7650, pSet=0x7ff72043bb20, fid=1886)
> at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbCommit.c:584
> #11 0x00007ff73daa252b in tsdbCommitTSData (pRepo=0x7ff68c001090)
> at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbCommit.c:509
> #12 0x00007ff73da9f140 in tsdbCommitData (pRepo=0x7ff68c001090)
> at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbCommit.c:102
> #13 0x00007ff73da9a52a in tsdbLoopCommit (arg=0x0)
> at /home/ubuntu/workroom/jenkins/TDinternal/community/src/tsdb/src/tsdbCommitQueue.c:186
> #14 0x00007ff73cfdeea5 in start_thread () from /lib64/libpthread.so.0
> #15 0x00007ff73cd0796d in clone () from /lib64/libc.so.6

我把datadir全部清理掉重来没多久就能复现，但因为数据量有些大，我也不确定是哪条导致的...

**Comment by cosmic-jc** [comment]
Fixed
