### ISSUE TITLE
Is there anyone interested in adding the missing connector for English document?

### ISSUE THREAD

**Issue by zhaoyanggh** [taosdata/TDengine#7685]
In our English documentation(https://github.com/taosdata/TDengine/blob/develop/documentation20/en/05.insert/docs.md), 
![Screen Shot 2021-08-30 at 9 22 46 AM](https://user-images.githubusercontent.com/47117543/131272882-2aa1f8c0-15c9-452f-b98b-425f4678efaa.png)
There is a brief introduction of our connectors, however, as we can see in our Chinese documentation(https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/05.insert/docs.md): 
![Screen Shot 2021-08-30 at 9 25 31 AM](https://user-images.githubusercontent.com/47117543/131273073-e6f3f2ad-41d3-4b71-a300-7867d60db336.png)
There is one more connector we also support. So can someone be willing to add the missing connector to the English document?

**Comment by zhanglianlei** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

Thanks, assigned it to you.

**Comment by Aries-Lee1991** [comment]
done

**Comment by zhanglianlei** [comment]
> > pick up challenge
> 
> Thanks, assigned it to you.

> OK

**Comment by zhanglianlei** [comment]
> > pick up challenge
> 
> Thanks, assigned it to you.

Please review the correction: https://github.com/taosdata/TDengine/pull/7723

**Comment by Aries-Lee1991** [comment]
@zhanglianlei We will make a certificate for the new contributor and give a souvenir. Can you leave your contact information or add my wechat (690754649).

**Comment by zhanglianlei** [comment]
@Aries-Lee1991 ok, I add your wechat, sincerely thanks!
