### ISSUE TITLE
请问，taos.dll文件在哪可以找到，或是如何生成的呢？

### ISSUE THREAD

**Issue by coder-chriswang** [taosdata/TDengine#77]
Windows上连接访问Linux上已经部署创建好的TSDB
目前已经创建相关表结构，想做一个基于SpringBoot的项目，完成INSERT，SELECT的相关操作
我已经将jdbcdriver的jar包导入至本地maven仓库，
![image](https://user-images.githubusercontent.com/40193732/61340244-16944800-a874-11e9-9487-724bcb253b05.png)
但工程目前报错，原因应该是找不到taos.dll文件，因为工程没有配置
![image](https://user-images.githubusercontent.com/40193732/61340213-f06ea800-a873-11e9-96e2-d73c84437339.png)
请问，taos.dll文件在哪可以找到，或是如何生成的？
期待回复，谢谢！

**Comment by coder-chriswang** [comment]
@jtao1735 陶老师，我没有搞明白文档中的这句话：
![image](https://user-images.githubusercontent.com/40193732/61340866-c1a60100-a876-11e9-90fb-549b926cbef2.png)

**Comment by plum-lihui** [comment]
不好意思，目前开源版本还没有发布dll，现在正在整合中，很快就会更新发布。

**Comment by coder-chriswang** [comment]
@plum-lihui 好的，谢谢！期待！
昨天看到Taos开源的消息，马不停蹄地就开始了安装测试，类mysql的操作console和亲切的类sql语法，很快就上手了，感觉很好。
但本人作为一个Javaer，想着如果应用端能像使用mysql那样使用taos，那对于从事物联网行业的Javaer而言，是一件很幸福的事情了，不会再因大数据而被冗杂的Hadoop，HBase等组件所困扰。我想这也是TDengine选择开源的一个初衷吧。
希望taos越来越好！希望国产开源越来越好！

**Comment by plum-lihui** [comment]
多谢支持！@coder-chriswang

**Comment by sunzhuyong** [comment]
我也是昨天安装了，也同样报这个错。希望快点支持windows

**Comment by vzhougm** [comment]
感觉不太妙 😂

**Comment by lookalook** [comment]
加油哇， 现在就卡在dll 这了

**Comment by hzcheng** [comment]
#55

**Comment by nileblack** [comment]
windows client被杀毒软件干掉了
