### ISSUE TITLE
benchmark : when set -hnum 6000  with TDengine/importSampleData/ tool, many tables have no datas in fact.

### ISSUE THREAD

**Issue by t00350320** [taosdata/TDengine#7702]
**Is your feature request related to a problem? Please describe.*

1、https://github.com/taosdata/TDengine/tree/develop/importSampleData
we cant find the ZIP tool as you said "直接下载 ZIP 文件解压". Actually there is no "bin" folder under this project.
Finally , i got the binary by  downloading and compiling the sourcecode 

2、app/app -cfg config/cfg.toml -cases sensor_info -hnum 2 -vnum 0 -start "2019-12-12 00:00:00.000" -interval 5000
 seems work well.  

And then, i have a benchmark case:
60000 points/s need to in sert. So 
"app/app -cfg config/cfg.toml -cases camera_detection -hnum 6000 -vnum 0 -start "2019-12-12 00:00:00.000" -interval 5000"

The file "importSampleData/data/camera_detection.json" shows 10 sensor_ids' datas, so 10*6000=60000, just fit my requirement.

But after exec above cmd, i check the table info, find  there was no datas in many tables like:
taos> select count(*) from t_s108_camera_detection_3;
Query OK, 0 row(s) in set (0.003053s)

So, i wonder, how you confirm your systerm can support high write cases? Or may some  improper parameters in cmd?

Env info:
linux 64bit , 25C376G
TDengine, version: 2.1.3.2

**Comment by huskar-t** [comment]
@t00350320 I did not reproduce successfully, please provide some program running logs

**Comment by t00350320** [comment]
oh,i guess it's not a problem. I found the datas hours later, because  the threads need some time to insert history datas. So you'd better add some tips or notice, when another guy want to use this tool to test performance.
thank you anyway.

**Comment by huskar-t** [comment]
thanks for your issue. We will consider making some improvements

**Comment by t00350320** [comment]
hi， i  found another issue, please help to check:
when i exec below two tests:
 nohup   ./app/app_1 -cfg config/cfg.toml -cases sensor_info -hnum 6000 -batch 1000 -thread 50 -vnum 0 -start "2021-08-31 16:23:00.000" -interval 1000  >/dev/null 2>&1 &
 nohup ./app/app -cfg config/cfg.toml -cases camera_detection -hnum 6000  -batch 1000 -thread 50 -vnum 0 -start "2021-08-31 11:30:00.000" -interval 5000  >/dev/null 2>&1 &

the sensor table datas lost like:
![20210831202701471](https://user-images.githubusercontent.com/41465048/131502363-7468e36c-1086-4b0b-a5bf-946ea5035c93.png)

select ts,temperature from test_20210831.t_7_sensor_info_999;  

table  t_7_sensor_info_999 lost many datas.

So, how can i make a believable perfonrmance test by this tool or another way?

Thank you.

**Comment by zyyang-taosdata** [comment]
If you are performing write performance tests, you can use taosdemo to simulate large concurrent writes.
you can find the taosdemo in /usr/local/taos/bin
Reference for taosdemo: [taosdemo](https://www.taosdata.com/blog/2020/12/29/2135.html)

**Comment by t00350320** [comment]
> If you are performing write performance tests, you can use taosdemo to simulate large concurrent writes.
> you can find the taosdemo in /usr/local/taos/bin
> Reference for taosdemo: [taosdemo](https://www.taosdata.com/blog/2020/12/29/2135.html)

thank you for your advice, but it doesn't work too.


{
    "filetype": "insert",
    "cfgdir": "/etc/taos",
    "host": "127.0.0.1",
    "port": 6030,
    "user": "root",
    "password": "taosdata",
    "thread_count": 50,                   
    "thread_count_create_tbl": 50,        
    "result_file": "./insert_res.txt",   
    "confirm_parameter_prompt": "no",    
    "insert_interval": 0,         
    "interlace_rows": 100,        
    "num_of_records_per_req": 100,
    "databases": [{
        "dbinfo": {
            "name": "db",
            "drop": "yes",                
            "replica": 1,
            "days": 10,
            "cache": 16,
            "blocks": 8,
            "precision": "ms",
            "keep": 3650,
            "minRows": 100,
            "maxRows": 4096,
            "comp":2,
            "walLevel":1,
            "cachelast":0,
            "quorum":1,
            "fsync":3000,
            "update": 0
        },
        "super_tables": [{
            "name": "stb",
            "child_table_exists":"no",   
            "childtable_count": 60000,   
            "childtable_prefix": "stb_", 
            "auto_create_table": "no",   
            "batch_create_tbl_num": 5,   
            "data_source": "rand",       
            "insert_mode": "taosc",      
            "insert_rows": 0,       
            "childtable_limit": 10,      
            "childtable_offset":100,     
            "interlace_rows": 0,         
            "insert_interval":0,         
            "max_sql_len": 1024000,      
            "disorder_ratio": 0,         
            "disorder_range": 1000,      
            "timestamp_step": 10,         
            "start_timestamp": "2021-09-01 10:24:00.000",  
            "sample_format": "csv",       
            "sample_file": "./sample.csv",   
            "tags_file": "",              
            "columns": [{"type": "INT"}, {"type": "DOUBLE", "count":10}, {"type": "BINARY", "len": 16, "count":3}, {"type": "BINARY", "len": 32, "count":6}],
            "tags": [{"type": "TINYINT", "count":2}, {"type": "BINARY", "len": 16, "count":5}]
        }]
    }]
}

================ demo.json parse result END================

create database db success!

Spent 9.6090 seconds to create 60000 tables with 50 thread(s)


taos> select count(*) from stb;
Query OK, 0 row(s) in set (0.013655s)

Some parameter  error?

**Comment by t00350320** [comment]
i want to test the real time write performance test, more than 60000 device/s. 
the taosdemo may used for history datas insert?
