### ISSUE TITLE
Query last time, the result time jumps unfortunately

### ISSUE THREAD

**Issue by t00350320** [taosdata/TDengine#7714]
**Bug Description**
exec the 
xx/TDengine/importSampleData

 nohup ./app/app -cfg config/cfg.toml -cases sensor_info -hnum 6000 -batch 10000 -thread 100 -vnum 0 -start "2019-12-12 00:00:00.000" -interval 5000  &

when query last time, the result jumps like:
taos> select last(*) from s_sensor_info where location = 'beijing';
        last(ts)         | last(temperature) |    last(humidity)    |
=====================================================================
 2021-08-30 16:38:55.190 |                26 |             18.78012 |
Query OK, 1 row(s) in set (0.958540s)

taos> select last(*) from s_sensor_info where location = 'beijing';
        last(ts)         | last(temperature) |    last(humidity)    |
=====================================================================
 2020-01-26 01:43:37.540 |                23 |             14.68890 |
Query OK, 1 row(s) in set (1.016103s)

taos> select last(*) from s_sensor_info where location = 'beijing';
        last(ts)         | last(temperature) |    last(humidity)    |
=====================================================================
 2021-08-30 16:38:55.190 |                26 |             18.78012 |
Query OK, 1 row(s) in set (1.028743s)

**Environment (please complete the following information):**
 - OS: gcc version 4.8.5 20150623 (Red Hat 4.8.5-36
 - 25C376G，disk-700G
 - TDengine Version [version: 2.1.3.2]

**Comment by ranningw** [comment]
Hi! Do you have lark (in chinese 飞书)？we can discuss how to solve the problem.
Please add the link to add my lark contact:   https://www.feishu.cn/invitation/page/add_contact/?token=1f4mb9fe-65fa-48a3-b35f-21d466e3523c&amp;unique_id=KJBGdz1tzz0NDckZL4swIA==

**Comment by fenghuazzm** [comment]
This issue was closed because it has been inactive for too many days.
