### ISSUE TITLE
how to create tables covering different device types?

### ISSUE THREAD

**Issue by liupeizhi** [taosdata/TDengine#773]
我看到的文档都是一张表代表一个设备或者设备类型，实际上是宽表，但是物联网方面，如果是做平台级的话，可能针对千千万万种设备类型，一般的表结构是这样的：(设备ID，模型，属性名称，属性值)，这样的设计能兼容不同设备类型，请问这样情况下，TD还适用吗？
还有一种情况可能要做不同设备类型的关联分析，这种情况能cover吗？
TD是偏于关系型还是非关系型？

**Comment by LiangDaShi** [comment]
@liupeizhi 官网这个也是这个样子啊

**Comment by hjxilinx** [comment]
1. 可以使用单列的模式，和OpenTSDB，prometheus采用单列的模式来建模，每一列一个表，这样就可以适应模式不同的需求的建模。
2. 可以针对每一类型的设备建模，每种类别的设备一个超级表来建模。

TD和普通的数据库不一样，不支持进行关联分析。
