### ISSUE TITLE
affected rows is wrong using batch insert

### ISSUE THREAD

**Issue by qingshenyijiu** [taosdata/TDengine#774]
**Bug Description**
数据批量写入并且自动建表，返回的结果 affected rows 有时候是错误的，而且错误是随机的。
实际数据有真实入库，但是客户端返回结果affected rows 小于 insert rows。

**客户端代码**
![客户端代码](https://user-images.githubusercontent.com/14091724/69608461-78ef2780-1062-11ea-88b9-0a4000d9186f.png)
**客户端日志**
![客户端日志](https://user-images.githubusercontent.com/14091724/69608566-b5228800-1062-11ea-8aa4-9c8721216cec.png)
**服务端日志**
![服务端日志](https://user-images.githubusercontent.com/14091724/69608704-f9158d00-1062-11ea-96fb-ffd8100de37b.png)
**客户端插入条数**
![客户端插入条数](https://user-images.githubusercontent.com/14091724/69608825-2a8e5880-1063-11ea-99b3-00cc10c42d23.png)
**服务端真实入库条数**
![服务端真实入库条数](https://user-images.githubusercontent.com/14091724/69608886-48f45400-1063-11ea-8e64-11d1302f4d61.png)

**Environment (please complete the following information):**
 - OS: [CentOS 7.0]
 - TDengine Version [e.g. 1.6.3.1]

**Comment by hzcheng** [comment]
您能提供一个更全面的客户端程序吗？最好我们能够运行。或者您再描述更清楚一些，具体几个线程，一个insert语句有多少条记录等。

**Comment by qingshenyijiu** [comment]
一个stable一个线程，多个stable并发，一个insert语句条数不一定，可能一条可能多条。

**Comment by sangshuduo** [comment]
请使用一下新版本，谢谢
