### ISSUE TITLE
import failes because of labels as first row in csv

### ISSUE THREAD

**Issue by vibhubithar** [taosdata/TDengine#7746]
**Bug Description**
Export command adds labels as first row of CSV, then when same files is used for import it fails

**To Reproduce**
1. export table to csv
2. import using csvfile
3. DB error: Syntax error in SQL (0.002312s) - also this error is not helpful

**Expected Behavior**
 export command should not add label as first row as import command doesnt expect first row to be labels 

**Environment (please complete the following information):**
 - OS: ubuntu 18.04
 - TDengine Version 2.6.1
**Additional Context**

**Comment by yu285** [comment]
yes,we need to remove first row  when import ， we should remind this  or remove it

**Comment by vibhubithar** [comment]
i am trying to script end of day data offload to the central system. which means my raspberry pi device will collecting data all day locally and will be offline, then at the end of the day it will become online and export data out of the local system create CSV file, transfer it to another system where import script will then insert data into the central database. Challenge is I have to write extra code to remove the first line of labels from the CSV. Can there be a flag while exporting so that it doesn't enter the label line into the CSV? or is there a better way to do sync between 2 databases ?
