### ISSUE TITLE
Is anybody insterested to help us to modify the documention?

### ISSUE THREAD

**Issue by jiacy-jcy** [taosdata/TDengine#7757]
Here are some case formatting errors in our English documention(https://github.com/taosdata/TDengine/blob/develop/documentation20/en/03.architecture/docs.md). There are some sentences where the beginning letter is incorrectly lowercase.We need someone careful to help us to modify the decumention.

我们的英文文档中存在一些格式错误，有些段落的句子被错误的使用小写字母开头，希望能有细心的人帮我们纠正一下错误。

**Comment by z1q1q7** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

You have claimed other tasks. Each person can claim only one.

**Comment by Aries-Lee1991** [comment]
This task is currently unmanned. Does anyone want to do it?

**Comment by Cerdore** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

Assigned it to you.

**Comment by Cerdore** [comment]
Hello! I have a question. Is this a spelling mistake here?
![image](https://user-images.githubusercontent.com/24353799/132333478-442c842e-d0a0-4e97-9564-ca9eaba50b3b.png)
![image](https://user-images.githubusercontent.com/24353799/132333525-a96facd6-523c-43af-872e-67914ff22cd1.png)
This looks more like “meta” data.

**Comment by Cerdore** [comment]
Hi!  One more question. When "taosc" appears at the beginning of a sentence, should it be capitalized?
![image](https://user-images.githubusercontent.com/24353799/132354270-8f1bc8ad-98c8-4a37-82d9-c8e88c44b5df.png)
![image](https://user-images.githubusercontent.com/24353799/132354381-18988367-5809-4c3c-9a56-f454dbfc72b2.png)

**Comment by Aries-Lee1991** [comment]
@jiacy-jcy  Please take a look at his question

**Comment by jiacy-jcy** [comment]
> 
> 
> Hello! I have a question. Is this a spelling mistake here?
> ![image](https://user-images.githubusercontent.com/24353799/132333478-442c842e-d0a0-4e97-9564-ca9eaba50b3b.png)
> ![image](https://user-images.githubusercontent.com/24353799/132333525-a96facd6-523c-43af-872e-67914ff22cd1.png)
> This looks more like “meta” data. @Aries-Lee1991

You are right.The correct description would be 'Meta Data'.

**Comment by jiacy-jcy** [comment]
> 
> 
> Hi! One more question. When "taosc" appears at the beginning of a sentence, should it be capitalized?
> ![image](https://user-images.githubusercontent.com/24353799/132354270-8f1bc8ad-98c8-4a37-82d9-c8e88c44b5df.png)
> ![image](https://user-images.githubusercontent.com/24353799/132354381-18988367-5809-4c3c-9a56-f454dbfc72b2.png)

I think we should change taosc or Taosc to TAOSC ,no matter where it appears in the paragraph

**Comment by Cerdore** [comment]
> > Hello! I have a question. Is this a spelling mistake here?
> > ![image](https://user-images.githubusercontent.com/24353799/132333478-442c842e-d0a0-4e97-9564-ca9eaba50b3b.png)
> > ![image](https://user-images.githubusercontent.com/24353799/132333525-a96facd6-523c-43af-872e-67914ff22cd1.png)
> > This looks more like “meta” data. @Aries-Lee1991
> 
> You are right.The correct description would be 'Meta Data'.

'Meta Data', not the 'meta data'?

**Comment by Cerdore** [comment]
> > Hi! One more question. When "taosc" appears at the beginning of a sentence, should it be capitalized?
> > ![image](https://user-images.githubusercontent.com/24353799/132354270-8f1bc8ad-98c8-4a37-82d9-c8e88c44b5df.png)
> > ![image](https://user-images.githubusercontent.com/24353799/132354381-18988367-5809-4c3c-9a56-f454dbfc72b2.png)
> 
> I think we should change taosc or Taosc to TAOSC ,no matter where it appears in the paragraph

Modified in the English version.

**Comment by Aries-Lee1991** [comment]
@Cerdore How's the issue going?

**Comment by Cerdore** [comment]
> @Cerdore How's the issue going?
I submitted my PR two days ago. Please help me look at it, thanks!
https://github.com/taosdata/TDengine/pull/7830

**Comment by Cerdore** [comment]
> > @Cerdore How's the issue going?
> > I submitted my PR two days ago. Please help me look at it, thanks!
> > #7830

@Aries-Lee1991

**Comment by Aries-Lee1991** [comment]
@Cerdore We will make a certificate for the new contributor and give a souvenir. Can you leave your contact information or add my wechat (690754649).
