### ISSUE TITLE
Improvement on English documentation in TAOS SQL section

### ISSUE THREAD

**Issue by glzhao89** [taosdata/TDengine#7762]
![截屏2021-09-02 上午10 43 19](https://user-images.githubusercontent.com/36554565/131774922-73e878e9-21f9-4e03-a47a-7fed9d88833b.png)

The document in English version has some inaccuracies in translation compared to Chinese version and can be further improved. Anyone interested on making the changes indicated from above picture?

**Comment by Linexl** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

Assigned it to you.

**Comment by Linexl** [comment]
Do I need to edit all the contents in the document? @Aries-Lee1991
