### ISSUE TITLE
windows client installation path  incorrect

### ISSUE THREAD

**Issue by xleili** [taosdata/TDengine#7764]
while read the Chinese version  of connector document i found the little mistake. Hope some can help and fix this.
GitHub link:https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/08.connector/docs.md
issue: the installation path of the windows client is not right, cause this is case sensitive.
![image-2021-08-30-19-49-15-094](https://user-images.githubusercontent.com/85657333/131777717-cc285239-ccd1-46ef-b3b2-27793eb7e6b2.png)

**Comment by Cxka** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

Assigned it to you

**Comment by ConnorChen97** [comment]
> > pick up challenge
> 
> Assigned it to you

Please review this pr: #7786

**Comment by Aries-Lee1991** [comment]
@ConnorChen97 We will make a certificate for the new contributor and give a souvenir. Can you leave your contact information or add my wechat (690754649).

**Comment by ConnorChen97** [comment]
> @ConnorChen97 We will make a certificate for the new contributor and give a souvenir. Can you leave your contact information or add my wechat (690754649).

Thks, I add your wechat.
