### ISSUE TITLE
In order to improve accuracy, could someone change this sentence to be more reasonable in the article?

### ISSUE THREAD

**Issue by jiajingbin** [taosdata/TDengine#7768]
![image](https://user-images.githubusercontent.com/39030567/131806900-2809b8c5-c701-4903-8f79-7a6aae884658.png)
The sequence description is incorrect and root account is not necessary.

**Comment by jiajingbin** [comment]
MD link is ---> https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/10.cluster/docs.md

**Comment by NickOpen** [comment]
pick up challenge

**Comment by tinybright** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

Assigned it to you

**Comment by Aries-Lee1991** [comment]
@tinybright We will make a certificate for the new contributor and give a souvenir. Can you leave your contact information or add my wechat (690754649).
