### ISSUE TITLE
"slimit" no effect while use taos-cli 

### ISSUE THREAD

**Issue by shaoguanlee** [taosdata/TDengine#7775]
# 使用taos命令进入cli客户端

## limit
数据量较大,且**不**使用limit查询数据时
```text
[100 Rows showed, and more rows are fetching but will not be showed. You can ctrl+c to stop or wait.]
[You can add limit statement to show more or redirect results to specific file to get all.]
```
使用limit后该提示消失,这是正常逻辑

## slimit
当**不**使用slimit时
```text
[100 Rows showed, and more rows are fetching but will not be showed. You can ctrl+c to stop or wait.]
[You can add limit statement to show more or redirect results to specific file to get all.]
Query OK, 90494 row(s) in set (3.150301s)
```
当**使用**slimit时
```text
[100 Rows showed, and more rows are fetching but will not be showed. You can ctrl+c to stop or wait.]
[You can add limit statement to show more or redirect results to specific file to get all.]
Query OK, 1000 row(s) in set (3.005877s)
```
此时的逻辑和limit并不一样

另外我想问一下,引入`slimit`这个概念是有什么考虑吗?从数据库的角度,应该能理解`group by limit`里的`limit`就是这里的`slimit`的意思吧?

**Comment by hjxilinx** [comment]
两个层次的问题：
limit是针对group by 以后形成的分组内的输出进行限制（在TDengine的查询过程中，单个分组（group）也可能有很多的输出结果，此时limit就是来控制组内的输出结果数量）。
而slimit 是限制的分组 （group）数量。

**Comment by hjxilinx** [comment]
普通的数据库在针对有分组（group）的情况，其查询结果一般来说针对每个分组（group）只会有一条记录输出，所以不需要针对每个分组内部再次进行控制输出数量。
一个简单的例子：
`select count(*) from super_table_name group by tbname`;
只有一行输出结果。
`select count(*) from super_table_name interval(1s) group by tbname`
会针对每个表，再次使用 1sec 长度的时间窗口切分数据形成每个分组的多行输出结果。

**Comment by arielyang** [comment]
This issue was closed because it has been inactive for too many days.
