### ISSUE TITLE
coredump in gcBuildQueryJson

### ISSUE THREAD

**Issue by xplizm** [taosdata/TDengine#7783]
**Bug Description**
taosd产生coredump问题，gdb定位core信息发现在gcBuildQueryJson

**To Reproduce**
系统运行过程中产生多个core文件（均在gcBuildQueryJson方法中），未知如何触发此问题

**Expected Behavior**

**Screenshots**
[New LWP 5461]
[New LWP 5499]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/bin/taosd'.
Program terminated with signal 11, Segmentation fault.
#0  0x000056308db735cf in gcBuildQueryJson (pContext=0x7fdfdc0008c0, cmd=0x7fdfe00014a0, result=0x7fdfcc048ab0, numOfRows=682) at /home/ubuntu/workroom/jenkins/TDinternal/community/src/plugins/http/src/httpGcJson.c:154
154	/home/ubuntu/workroom/jenkins/TDinternal/community/src/plugins/http/src/httpGcJson.c: No such file or directory.
Missing separate debuginfos, use: debuginfo-install glibc-2.17-324.el7_9.x86_64

**Environment (please complete the following information):**
 - OS:  CentOS 7.9_x64
 - Memory, CPU, current Disk Space：Memory 96G， Disk 1T
 - TDengine Version：TDengine-server-2.0.20.13-Linux-x64

**Additional Context**

**Comment by yu285** [comment]
已经修复过
