### ISSUE TITLE
libtaos.so issue

### ISSUE THREAD

**Issue by lucienbao** [taosdata/TDengine#7794]
客户端操作系统：CentOS 7.9
TDengine Version：2.1.7.2-beta x64
应用程序：dotnet core 3.1 app, 以 systemd service模式运行。
异常描述：之前用的TDengine Version 2.0.20.10 x64，程序正常运行了一周多，后面为了TDengine能支持in查询，卸载了稳定版的2.0.20.10版本，安装了2.1.7.2-beta版本。然后客户端的应用程序启动的时候就报下方的错误。

Sep  6 17:54:07 localhost systemd: qualitytaosservice2.service holdoff time over, scheduling restart.
Sep  6 17:54:07 localhost systemd: Stopped DotNetCore Application running on CentOS.
Sep  6 17:54:07 localhost systemd: Started DotNetCore Application running on CentOS.
Sep  6 17:54:08 localhost kernel: dotnet[81116]: segfault at 1e5 ip 00007fc6af1aa6ba sp 00007fc6afffc350 error 4 in libtaos.so.2.1.7.2[7fc6af16d000+472000]
Sep  6 17:54:08 localhost abrt-hook-ccpp: Process 81105 (dotnet) of user 0 killed by SIGSEGV - ignoring (repeated crash)
Sep  6 17:54:08 localhost systemd: qualitytaosservice2.service: main process exited, code=killed, status=11/SEGV
Sep  6 17:54:08 localhost systemd: Unit qualitytaosservice2.service entered failed state.
Sep  6 17:54:08 localhost systemd: qualitytaosservice2.service failed.

**Comment by lucienbao** [comment]
找到原因了，我使用的Maikebing.Data.Taos没有同步更新2.2.0.0的TDengineDriver，2.0.20.10版本客户端与2.2.0.0版本客户端的taos.dll的c++接口不一样了。

**Comment by maikebing** [comment]
是毫秒和纳秒的问题嘛？还是？

**Comment by maikebing** [comment]
有没有具体信息， 比如可能是哪一个 接口？

**Comment by lucienbao** [comment]
> 有没有具体信息， 比如可能是哪一个 接口？

应该是2.1/2.2版本的TDengineDriver里面端口号类型从int类型变成了short类型，而2.0版本的TDengineDriver还是int类型导致的。
