### ISSUE TITLE
windows client information not correct

### ISSUE THREAD

**Issue by 5rKI5pWP5by6** [taosdata/TDengine#7797]
显示的是linux的信息
Welcome to the TDengine shell from Linux, Client Version:2.0.20.13
Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.

**Comment by sangshuduo** [comment]
谢谢，我们在新版本（2.2.x）中应该已经修复了

**Comment by yu285** [comment]
请问问题还存在吗
