### ISSUE TITLE
配置功能不是很方便，同时最好是界面式的操作，就像navicat，plsqldeveloper，ssms等的客户端，会比较方便

### ISSUE THREAD

**Issue by 5rKI5pWP5by6** [taosdata/TDengine#7798]
配置功能不是很方便，同时最好是界面式的操作，就像navicat，plsqldeveloper，ssms等的客户端，会比较方便

**Comment by ConnorChen97** [comment]
参考官方文档：https://www.taosdata.com/cn/documentation20/

官方文档提供了一些工具：
https://www.taosdata.com/blog/2020/08/27/1767.html
https://github.com/skye0207/TDengineGUI
