### ISSUE TITLE
请问对文本字符串检索的功能支持的怎么样？

### ISSUE THREAD

**Issue by malinco** [taosdata/TDengine#78]

**Comment by yasinasama** [comment]
![image](https://user-images.githubusercontent.com/15014408/61363128-0c933900-a8b6-11e9-8d7d-5767dbc15784.png)

并不支持

**Comment by hjxilinx** [comment]
nchar并太适合进行检索和过滤， binary格式的字段可以进行检索和过滤。另，tags中的字符串（binary nchar）可以进行精确匹配和模糊查询。
