### ISSUE TITLE
TD2.2.0 JDBC 进程不能自动退出

### ISSUE THREAD

**Issue by DongDongDing** [taosdata/TDengine#7803]
![image](https://user-images.githubusercontent.com/25541272/132282425-207e81a3-8aa4-48d2-a4b2-c96f05417e37.png)
执行完程序后，进程不能自动结束，之前测试2.0.20.13执行完成后进程会自动结束，现在测试2.2.0进程不能自动结束

**Comment by yu285** [comment]
JDBC版本是？

**Comment by DongDongDing** [comment]
> JDBC版本是？

2.0.31

**Comment by zyyang-taosdata** [comment]
From the screenshot, I guess you are using parameter binding to insert. This kind of rough description of the problem makes it difficult to help you analyze and locate the problem.

**Comment by xleili** [comment]
we found this problem in 2.1.6.0 window client , we are working on this problem.

**Comment by DongDongDing** [comment]
最新版本我测试了，发现这个问题解决了，谢谢
