### ISSUE TITLE
The error occurred while setting parameters

### ISSUE THREAD

**Issue by Jackhzf** [taosdata/TDengine#7824]
运行官网实例代码springbootdemo，报如下错误：
### Cause: java.sql.SQLException: TDengine ERROR (216): Syntax error in SQL
; uncategorized SQLException; SQL state []; error code [534]; TDengine ERROR (216): Syntax error in SQL; nested exception is java.sql.SQLException: TDengine ERROR (216): Syntax error in SQL] with root cause

{
    "timestamp": "2021-09-08T04:02:16.031+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "\r\n### Error updating database.  Cause: java.sql.SQLException: TDengine ERROR (216): Syntax error in SQL\r\n### The error may exist in com/taosdata/example/springbootdemo/dao/WeatherMapper.xml\r\n### The error may involve com.taosdata.example.springbootdemo.dao.WeatherMapper.createTable-Inline\r\n### The error occurred while setting parameters\r\n### SQL: create table if not exists test.t0 using test.weather tags(?, ?);\r\n### Cause: java.sql.SQLException: TDengine ERROR (216): Syntax error in SQL\n; uncategorized SQLException; SQL state []; error code [534]; TDengine ERROR (216): Syntax error in SQL; nested exception is java.sql.SQLException: TDengine ERROR (216): Syntax error in SQL",
    "trace": "org.springframework.jdbc.UncategorizedSQLException: \r\n### Error updating database.  Cause: java.sql.SQLException: TDengine ERROR (216): Syntax error in SQL\r\n### The error may exist in com/taosdata/example/springbootdemo/dao/WeatherMapper.xml\r\n### The error may involve com.taosdata.example.springbootdemo.dao.WeatherMapper.createTable-Inline\r\n### The error occurred while setting parameters\r\n### SQL: create table if not exists test.t0 using test.weather tags(?, ?);\r\n### Cause: java.sql.SQLException: TDengine ERROR (216): Syntax error in SQL\n; uncategorized SQLException; SQL state []; error code [534]; TDengine ERROR (216): Syntax error in SQL; nested exception is java.sql.SQLException: TDengine ERROR (216): Syntax error in SQL\r\n\tat org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89)\r\n\tat org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)\r\n\tat org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)\r\n\tat org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:88)\r\n\tat org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)\r\n\tat com.sun.proxy.$Proxy70.update(Unknown Source)\r\n\tat org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:287)\r\n\tat org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:67)\r\n\tat org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:93)\r\n\tat com.sun.proxy.$Proxy71.createTable(Unknown Source)\r\n\tat com.taosdata.example.springbootdemo.service.WeatherService.init(WeatherService.java:33)\r\n\tat com.taosdata.example.springbootdemo.controller.WeatherController.init(WeatherController.java:25)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)\r\n\tat org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)\r\n\tat org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)\r\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)\r\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)\r\n\tat org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)\r\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)\r\n\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)\r\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)\r\n\tat org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)\r\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:634)\r\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)\r\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:741)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\r\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\r\n\tat org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\r\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\r\n\tat org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)\r\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\r\n\tat org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)\r\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\r\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)\r\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)\r\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)\r\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)\r\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)\r\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)\r\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)\r\n\tat org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)\r\n\tat org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)\r\n\tat org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)\r\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579)\r\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\r\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\r\n\tat java.lang.Thread.run(Thread.java:748)\r\nCaused by: java.sql.SQLException: TDengine ERROR (216): Syntax error in SQL\r\n\tat com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:73)\r\n\tat com.taosdata.jdbc.rs.RestfulStatement.executeOneUpdate(RestfulStatement.java:136)\r\n\tat com.taosdata.jdbc.rs.RestfulStatement.executeUpdate(RestfulStatement.java:57)\r\n\tat com.taosdata.jdbc.rs.RestfulStatement.execute(RestfulStatement.java:99)\r\n\tat com.taosdata.jdbc.rs.RestfulPreparedStatement.execute(RestfulPreparedStatement.java:239)\r\n\tat com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:497)\r\n\tat org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)\r\n\tat org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)\r\n\tat org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)\r\n\tat org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)\r\n\tat org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)\r\n\tat org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)\r\n\t... 57 more\r\n",
    "path": "/weather/init"
}

执行创建数据库和超级表没问题，使用超级表创建表就报错，请问什么原因

**Comment by xleili** [comment]
what is your tdengine and JDBC version?

**Comment by zyyang-taosdata** [comment]
please change the taos-jdbcdriver to the latest version and try again

**Comment by Jackhzf** [comment]
tdengine： Version:2.2.0.0
taos-jdbcdriver：2.0.28
问题我已经找到使用mybatis处理字符串的时候它不会加引号，必须手动添加引号才可以，
报错代码CREATE TABLE IF NOT EXISTS test.t#{groupId} USING test.weather TAGS(#{location}, #{groupId});不加引号，
正确代码：CREATE TABLE IF NOT EXISTS test.t#{groupId} USING test.weather TAGS('#{location}', #{groupId});
不知道为什么会这样？

**Comment by Jackhzf** [comment]
taos-jdbcdriver：2.0.28，可能有bug吧。
taos-jdbcdriver：2.0.34，升级到2.0.34就可以了。不加引号也不报错了。

**Comment by dxy9** [comment]
升级 taos-jdbcdriver：2.0.34 之后还是有这种情况，插入单条值的数据可以，插入多条时还是报错 TDengine ERROR (216)

**Comment by dxy9** [comment]
2021-11-22 15:12:47.346 DEBUG 15728 --- [nio-8081-exec-3] c.t.e.s.dao.WeatherMapper.insertBatch    : ==>  Preparing: insert into test.t? (ts, temperature, humidity, note) values (?, ?, ?, ?) (?, ?, ?, ?) 
2021-11-22 15:12:47.346 DEBUG 15728 --- [nio-8081-exec-3] c.t.e.s.dao.WeatherMapper.insertBatch    : ==> Parameters: 1(Integer), 2021-11-22 15:12:47.327(Timestamp), 3.0(Float), 5.0(Float), null, 2021-11-22 15:12:47.327(Timestamp), 3.0(Float), 5.0(Float), null
2021-11-22 15:12:47.400 ERROR 15728 --- [nio-8081-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.jdbc.UncategorizedSQLException: 
### Error updating database.  Cause: java.sql.SQLException: TDengine ERROR (216): Syntax error in SQL
### The error may exist in com/taosdata/example/springbootdemo/dao/WeatherMapper.xml
### The error may involve com.taosdata.example.springbootdemo.dao.WeatherMapper.insertBatch-Inline
### The error occurred while setting parameters
### SQL: insert into test.t? (ts, temperature, humidity, note)             values                                              (?, ?, ?, ?)                                              (?, ?, ?, ?)
### Cause: java.sql.SQLException: TDengine ERROR (216): Syntax error in SQL
; uncategorized SQLException; SQL state []; error code [534]; TDengine ERROR (216): Syntax error in SQL; nested exception is java.sql.SQLException: TDengine ERROR (216): Syntax error in SQL] with root cause

java.sql.SQLException: TDengine ERROR (216): Syntax error in SQL
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:75) ~[taos-jdbcdriver-2.0.34.jar:na]
