### ISSUE TITLE
Doc improvement: python connector en doc, linux connector path incorrect 

### ISSUE THREAD

**Issue by xleili** [taosdata/TDengine#7838]
Doc link: https://github.com/taosdata/TDengine/blob/develop/documentation20/en/08.connector/docs.md
In this document at Python connector paragraph, the describe of python connector path  under linux , is not correct.  
Can someone help us fix this and submit. Thank you.
Hint: You can compare with the same document of the Chinese version. 
link :https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/08.connector/docs.md

The screenshot:
![image](https://user-images.githubusercontent.com/85657333/132620414-a4c1074a-72b7-4462-b7b8-6dc80d0cd604.png)

**Comment by Aries-Lee1991** [comment]
We will make a certificate for the new contributor and give a souvenir. Can you leave your contact information or add my wechat (690754649). @Jellal-HT
