### ISSUE TITLE
The image typesetting of the English document is incorrect

### ISSUE THREAD

**Issue by jiacy-jcy** [taosdata/TDengine#7844]
![图片](https://user-images.githubusercontent.com/57592088/132648504-cdc8d7aa-be34-4f41-88ce-d8cd385121ba.png)
Here is the Chinese documentation picture,pitcure 3 is the TDengine Master Writing Process.But in English documentation,image cannot be displayed.
As a result of this problem, other images in the document also have errors.
We hope someone can help us fix this problem.
Specific repair methods are as follows: According to Chinese documentation ,modify the English documentation.Make the illustrations in the two documents consistent.
Here is the link of Chinese document:https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/03.architecture/docs.md
Here is the link of English document:https://github.com/taosdata/TDengine/blob/develop/documentation20/en/03.architecture/docs.md

And the link of picture maybe useful:https://github.com/taosdata/TDengine/blob/develop/documentation20/en/images/architecture/write_master.png
https://github.com/taosdata/TDengine/blob/develop/documentation20/en/images/architecture/write_slave.png

**Comment by daaaaaaaaaaa** [comment]
It seems that the pictures of Chinese documents cannot be displayed?

**Comment by daaaaaaaaaaa** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

Assigned it to you.

**Comment by Aries-Lee1991** [comment]
> It seems that the pictures of Chinese documents cannot be displayed?
> ![中文文档无法显示图片](https://user-images.githubusercontent.com/51794124/132951663-40e7d919-6041-4164-909d-dfe8a68927a7.PNG)

And the link of picture maybe useful:https://github.com/taosdata/TDengine/blob/develop/documentation20/en/images/architecture/write_master.png
https://github.com/taosdata/TDengine/blob/develop/documentation20/en/images/architecture/write_slave.png

**Comment by Aries-Lee1991** [comment]
@daaaaaaaaaaa We will make a certificate for the new contributor and give a souvenir. Can you leave your contact information or add my wechat (690754649).
