### ISSUE TITLE
restful to TDengine through explorer  timeout.

### ISSUE THREAD

**Issue by CP3cham** [taosdata/TDengine#7849]
在浏览器端通过rest发起部署在阿里云服务器上的节点，因为涉及跨域，且为非简单请求（request headers里包含了身份认证信息），按规则默认先发起一此预检请求，返回正常后再发起正式请求。

在实际发送中预检返回正常，但是正式发起请求总是超时（我在代码里设置了5s的时延），但是通过curl工具却返回正常

预检请求信息：
请求 URL: http://120.24.54.73:6041/rest/sql
请求方法: OPTIONS
状态代码: 200 OK
远程地址: 120.24.54.73:6041
引用站点策略: strict-origin-when-cross-origin

预检响应信息：
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, authorization
Access-Control-Allow-Methods: *
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 3600
Connection: Keep-Alive
Content-Length: 67
Content-Type: application/json;charset=utf-8
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Access-Control-Request-Headers: authorization
Access-Control-Request-Method: POST
Connection: keep-alive
Host: 120.24.54.73:6041
Origin: null
Sec-Fetch-Mode: cors
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36 Edg/93.0.961.38

正式请求信息：
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Authorization: Basic cm9vdDp0YW9zZGF0YQ==
Connection: keep-alive
Content-Length: 14
Content-Type: application/x-www-form-urlencoded
Host: 120.24.54.73:6041
Origin: null
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36 Edg/93.0.961.38
**Expected Behavior**

**Environment (please complete the following information):**
 - OS: Ubuntu 20.x
 - TDengine Version：2.0.20.12

**Additional Context**
用抓包工具抓取的curl成功请求的信息：
> POST /rest/sql HTTP/1.1
> Host: 120.24.54.73:6041
> User-Agent: curl/7.64.1
> Accept: */*
> Authorization: Basic cm9vdDp0YW9zZGF0YQ==
> Content-Length: 15
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 15 out of 15 bytes
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin:*
< Content-Type: application/json;charset=utf-8
< Transfer-Encoding: chunked
<

**Comment by yu285** [comment]
we will check on this
