### ISSUE TITLE
 this operation is NOT supported currently!

### ISSUE THREAD

**Issue by xysshgmq** [taosdata/TDengine#7858]
我在用你们springbootdemo这个项目连接TDengine 时报错，启动没有问题。进行数据库连接的时候有了问题
TDengine ：版本：2.0.16.0
taos-jdbcdriver：版本：2.0.18
application.properties配置：
![image](https://user-images.githubusercontent.com/72612109/132787669-2e08c2f4-0bfb-4530-a8c8-5494e678f86d.png)
报错信息：
![image](https://user-images.githubusercontent.com/72612109/132787728-d13cddcd-8899-4513-bc68-9992aeee5a15.png)

**Comment by sangshuduo** [comment]
请使用最新版本 JDBC 驱动

**Comment by xysshgmq** [comment]
请问是使用最新的spring-jdbc 还是taos-jdbcdriver


***@***.***
 
From: Shuduo Sang
Date: 2021-09-10 10:32
To: taosdata/TDengine
CC: xysshgmq; Author
Subject: Re: [taosdata/TDengine] this operation is NOT supported currently! (#7858)
请使用最新版本 JDBC 驱动
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sangshuduo** [comment]
taos jdbcdriver

**Comment by xysshgmq** [comment]
好的，已解决。
你们官网的文档上的对应版本应该重点突出这个。有点误导人。刚才才注意到



***@***.***
 
From: Shuduo Sang
Date: 2021-09-13 10:37
To: taosdata/TDengine
CC: xysshgmq; Author
Subject: Re: [taosdata/TDengine] this operation is NOT supported currently! (#7858)
taos jdbcdriver
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sangshuduo** [comment]
官网文档在 https://github.com/taosdata/TDengine/tree/develop/documentation20 中，欢迎提 PR 修改
