### ISSUE TITLE
Inconsistent description for setting timestamp resolution options in Chinese/English documents

### ISSUE THREAD

**Issue by glzhao89** [taosdata/TDengine#7859]
![image](https://user-images.githubusercontent.com/36554565/132787800-aeb7ccda-2410-45ec-bb5b-a7805de1ea0a.png)
![image](https://user-images.githubusercontent.com/36554565/132787815-91c501e8-fe21-43f5-a009-fdf7acd81489.png)

The description for changing database timestamp resolution in English document is deprecated. Anyone interested in updating it referring to latest Chinese documentation?

The links for documentations:
Chinese version: https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/12.taos-sql/docs.md
English version: https://github.com/taosdata/TDengine/blob/develop/documentation20/en/12.taos-sql/docs.md

**Comment by CTZxVULKAN** [comment]
Would you like me to change the entire [section](https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/12.taos-sql/docs.md#%E6%94%AF%E6%8C%81%E7%9A%84%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B) ?
