### ISSUE TITLE
Can't update data though insert again

### ISSUE THREAD

**Issue by MelodyI** [taosdata/TDengine#7884]
# taos -u root -p

Welcome to the TDengine shell from Linux, Client Version:2.0.20.10
Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.

taos> show databases \G;
*************************** 4.row ***************************
               name:****
       created_time: 2021-02-19 17:54:13.461
            ntables: 121
            vgroups: 1
            replica: 1
             quorum: 1
               days: 10
keep0,keep1,keep(D): 3650,3650,3650
          cache(MB): 16
             blocks: 6
            minrows: 100
            maxrows: 4096
           wallevel: 1
              fsync: 3000
               comp: 2
          cachelast: 0
          precision: ms
             update: 1
             status: ready

taos> select * from tb0001 where ts = '2021-09-12 00:48:32.762';
|ts|qa|qb|r|
|---|---|---|---|
|2021-09-12 00:48:32.762 |         -429446.800000000 |         7220263.900000000 |                      NULL |

Query OK, 1 row(s) in set (0.002354s)

taos> insert into tb0001(ts, qa, qb, r) values('2021-09-12 00:48:32.762', 0, 7220263.900000000, NULL);
Query OK, 1 of 1 row(s) in database (0.000577s)

taos> select * from tb0001 where ts = '2021-09-12 00:48:32.762';
|ts|qa|qb|r|
|---|---|---|---|
|2021-09-12 00:48:32.762 |         -429446.800000000 |         7220263.900000000 |                      NULL |

Query OK, 1 row(s) in set (0.001845s)

**Comment by boxiaobj** [comment]
Can't reproduce the error on 2.0.20.10
Can you share more details?

**Comment by MelodyI** [comment]
tdengine docker version upgrade from 2.0.14.0 to 2.0.20.10

**Comment by fenghuazzm** [comment]
This issue was closed because it has been inactive for too many days.
