### ISSUE TITLE
taosdump export specific table

### ISSUE THREAD

**Issue by Lao-Zhong** [taosdata/TDengine#7892]
**Bug Description**
$ taosdump -c /etc/taos/ -o /data/tests/bhiot/tables -u root -p taosdata bohai g65300499012 -S 1622476800000 -E 1631203200000 -t 500 -B 60 -T 8

Why does taosdump include data from other tables
![11111](https://user-images.githubusercontent.com/39207755/133044907-d108a70a-91ad-4fe2-91e9-522a4a00f7ce.png)

version: 2.0.20.17
![2222](https://user-images.githubusercontent.com/39207755/133064452-b3f92d9a-f6f7-4f6e-af49-a66b424e5a70.png)

**Comment by sangshuduo** [comment]
这个应该是某个比较老的版本了吧？

**Comment by Lao-Zhong** [comment]
> 这应该是某个特定老的版本吧？
version: 2.0.20.17
![2222](https://user-images.githubusercontent.com/39207755/133063964-faa0752e-7cb4-4a69-b760-27c07f4abaa8.png)

**Comment by Lao-Zhong** [comment]
> 这应该是某个特定的老版本吧？
version: 2.0.20.17， 这应该不算很旧的版本吧
![2222](https://user-images.githubusercontent.com/39207755/133064135-28de3bc4-b178-408b-b979-e285ee487766.png)

**Comment by sangshuduo** [comment]
这是在 2.0 分支上编译的吧？如果不使用官方发布版本自行编译建议使用 master 或 develop 分支编译。通常 master 分支更稳定。
