### ISSUE TITLE
请问下开源的产品是不是不支持分布式多机部署

### ISSUE THREAD

**Issue by mseaspring** [taosdata/TDengine#79]
请问下开源的产品是不是不支持分布式多机部署，开源的是只支持单机吗？

**Comment by plum-lihui** [comment]
是的。开源版本仅支持单机部署，企业版本才支持集群部署。

**Comment by mseaspring** [comment]
好的谢谢，加油，争取早日开放集群版本。

**Comment by jtao1735** [comment]
Please check https://www.taosdata.com/cn/documentation/more-on-system-architecture/#%E9%9B%86%E7%BE%A4%E8%AE%BE%E8%AE%A1 for the design of distributed system.
