### ISSUE TITLE
RPC ERROR TSC 0x7f53a8032de8 0x17890, failed to send, msgLen:86 written:-1, reason:Broken pipe

### ISSUE THREAD

**Issue by 784134748** [taosdata/TDengine#7923]
**Environment (please complete the following information):**
 - OS: docker ubuntu
 - TDengine Version: 2.0.20.13

![image](https://user-images.githubusercontent.com/16873072/133259938-1cfeec69-96c3-4144-960a-2f1b18475c4c.png)

**Comment by zhwentao** [comment]
i met the same bug with ver 2.2.2.0
