### ISSUE TITLE
When I use 'while' to run the parameter binding program, the memory keeps increasing, and I think the program has a memory leak

### ISSUE THREAD

**Issue by DongDongDing** [taosdata/TDengine#7935]
**Bug Description**

When I use 'while' to run the parameter binding program, the memory keeps increasing, and I think the program has a memory leak

![image](https://user-images.githubusercontent.com/25541272/133402689-dd88768a-0a58-49ea-8b7d-830d59f18bfa.png)
![image](https://user-images.githubusercontent.com/25541272/133402730-77533a2a-67ee-46bf-8838-e5ceeea42c45.png)

code:

 public static void main(String[] args) throws SQLException {

        List<RealTimeData> list = Lists.newArrayList();
        long l = System.currentTimeMillis() - 1000000;
        boolean flag = true;
        while (flag) {
            for (int i = 0; i < 100; i++) {
                RealTimeData rd = new RealTimeData();
                rd.setTs(l + 1);
                rd.setLongitude(11000L);
                rd.setLatitude(10000L);
                rd.setAltitude(100);
                rd.setSpeed(100);
                rd.setOptType(2);
                rd.setGuid("123456");
                rd.setOriginByte("abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz");
                list.add(rd);
            }
            long startTime = System.currentTimeMillis();
            bindTest(list, "mec.t_1");
            System.out.println(System.currentTimeMillis() - startTime);

        }
    }

    public static void bindTest(List<RealTimeData> list, String table) throws SQLException {
        Connection connection = getConnection();
        String sql = "insert into ? using mec.s_real_time tags (?) (ts, speed, longitude, latitude, altitude, guid, system_time, origin_byte) VALUES (?, ?, ?, ?, ?, ?, Now, ?)";
        TSDBPreparedStatement s = (TSDBPreparedStatement) connection.prepareStatement(sql);
        ArrayList<Long> ts = new ArrayList<>();
        ArrayList<Integer> speed = new ArrayList<>();
        ArrayList<Long> longitude = new ArrayList<>();
        ArrayList<Long> latitude = new ArrayList<>();
        ArrayList<Long> altitude = new ArrayList<>();
        ArrayList<String> guid = new ArrayList<>();
        ArrayList<String> originByte = new ArrayList<>();

        ts.addAll(list.stream().map(i -> i.getTs()).collect(Collectors.toList()));
        speed.addAll(list.stream().map(i -> i.getSpeed()).collect(Collectors.toList()));
        longitude.addAll(list.stream().map(i -> i.getLongitude()).collect(Collectors.toList()));
        latitude.addAll(list.stream().map(i -> i.getLatitude()).collect(Collectors.toList()));
        altitude.addAll(list.stream().map(i -> i.getAltitude()).collect(Collectors.toList()));
        guid.addAll(list.stream().map(i -> i.getGuid()).collect(Collectors.toList()));
        originByte.addAll(list.stream().map(i -> i.getOriginByte()).collect(Collectors.toList()));
        s.setTableName(table);
        s.setTagInt(0, 2);
        s.setTimestamp(0, ts);
        s.setInt(1, speed);
        s.setLong(2, longitude);
        s.setLong(3, latitude);
        s.setLong(4, altitude);
        s.setNString(5, guid, 20);
        s.setString(6, originByte, 1000);

        s.columnDataAddBatch();
        s.columnDataExecuteBatch();
        s.columnDataClearBatch();
        s.close();
        connection.close();
    }

**Environment (please complete the following information):**
 - OS: [window 10]
 - TDengine Version [2.2.0.1]

**Additional Context**

**Comment by DongDongDing** [comment]
taos-driver version 2.0.34

**Comment by zyyang-taosdata** [comment]
thanks for your test case, and I will try to find out if there is a memory leak.

**Comment by huolibo** [comment]
i think the memory sustainable growth because the variable(list) is not released in you code 'List<RealTimeData> list = Lists.newArrayList();'. 
suggest this variable(list) define in while body.

**Comment by DongDongDing** [comment]
Sorry, this is my mistake, but I put it in it, and after running for an hour, the submitted memory is still increasing, and finally the program terminates

**Comment by huolibo** [comment]
how about paste you main code or the memory use's picture? well, the better way is use jconsole to analysis the memory state or add ‘-XX:+HeapDumpOnOutOfMemoryError’ when you start the program.

**Comment by DongDongDing** [comment]
我的代码就是一个死循环，不断往数据库中插入数据，程序不到五分钟就会崩溃，已提交内存会不断增加,接着内存会到100%

`
package com.taosdata.example;

import com.google.common.collect.Lists;
import com.taosdata.jdbc.TSDBPreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import java.util.stream.Collectors;

public class BindTest {

    public static void main(String[] args) throws SQLException, InterruptedException {
        long l = System.currentTimeMillis() - 1000000;
        boolean flag = true;
        while (flag) {
            List<RealTimeData> list = Lists.newArrayList();
            for (int i = 0; i < 1000; i++) {
                RealTimeData rd = new RealTimeData();
                rd.setTs(l + 1);
                rd.setLongitude(11000L);
                rd.setLatitude(10000L);
                rd.setAltitude(100);
                rd.setSpeed(100);
                rd.setOptType(2);
                rd.setGuid("123456");
                rd.setOriginByte("abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz");
                list.add(rd);
            }
            long startTime = System.currentTimeMillis();
            try {
                bindTest(list, "mec.t_1");
            }catch (Exception e){
                e.printStackTrace();
            }
            System.out.println(System.currentTimeMillis() - startTime);
        }
    }

    public static void bindTest(List<RealTimeData> list, String table) throws SQLException {
        Connection connection = getConnection();
        String sql = "insert into ? using mec.s_real_time tags (?) (ts, speed, longitude, latitude, altitude, guid, system_time, origin_byte) VALUES (?, ?, ?, ?, ?, ?, Now, ?)";
        TSDBPreparedStatement s = (TSDBPreparedStatement) connection.prepareStatement(sql);
        ArrayList<Long> ts = new ArrayList<>();
        ArrayList<Integer> speed = new ArrayList<>();
        ArrayList<Long> longitude = new ArrayList<>();
        ArrayList<Long> latitude = new ArrayList<>();
        ArrayList<Long> altitude = new ArrayList<>();
        ArrayList<String> guid = new ArrayList<>();
        ArrayList<String> originByte = new ArrayList<>();

        ts.addAll(list.stream().map(i -> i.getTs()).collect(Collectors.toList()));
        speed.addAll(list.stream().map(i -> i.getSpeed()).collect(Collectors.toList()));
        longitude.addAll(list.stream().map(i -> i.getLongitude()).collect(Collectors.toList()));
        latitude.addAll(list.stream().map(i -> i.getLatitude()).collect(Collectors.toList()));
        altitude.addAll(list.stream().map(i -> i.getAltitude()).collect(Collectors.toList()));
        guid.addAll(list.stream().map(i -> i.getGuid()).collect(Collectors.toList()));
        originByte.addAll(list.stream().map(i -> i.getOriginByte()).collect(Collectors.toList()));
        s.setTableName(table);
        s.setTagInt(0, 2);
        s.setTimestamp(0, ts);
        s.setInt(1, speed);
        s.setLong(2, longitude);
        s.setLong(3, latitude);
        s.setLong(4, altitude);
        s.setNString(5, guid, 20);
        s.setString(6, originByte, 1000);

        s.columnDataAddBatch();
        s.columnDataExecuteBatch();
        s.columnDataClearBatch();
        s.close();
        connection.close();
    }

    private static Connection getConnection() {
        final String url = "jdbc:TAOS://mec02:6030/?user=root&password=taosdata";
        Connection connection1 = null;
        try {
            Class.forName("com.taosdata.jdbc.TSDBDriver");
            Properties properties = new Properties();
            properties.setProperty("charset", "UTF-8");
            properties.setProperty("locale", "en_US.UTF-8");
            properties.setProperty("timezone", "UTC-8");
            System.out.println("get connection starting...");
            connection1 = DriverManager.getConnection(url, properties);
            if (connection1 != null)
                System.out.println("[ OK ] Connection established.");
            return connection1;
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println("[ ERROR! ] Connection establish failed.");
            e.printStackTrace();
        }
        return null;
    }
}

`
![image](https://user-images.githubusercontent.com/25541272/133575403-5fd97834-3397-4c43-afac-809713eace4c.png)

![image](https://user-images.githubusercontent.com/25541272/133574916-c7e3a72b-d41a-4ad9-b07f-f81a258bf719.png)

![image](https://user-images.githubusercontent.com/25541272/133575548-43eb13ae-b5ff-4264-8c79-b8a23bdbefef.png)

**Comment by huolibo** [comment]
ye, I've also noticed the same thing. memory keeps increasing. but i am not sure what cause this, may be jdbc or jni code. I'll let you know when i figure it out.

**Comment by xiaopenggogo** [comment]
咋解决的，C#也是这个样子。

**Comment by huolibo** [comment]
上面的示例使用参数绑定的方式，但是在插入结束没有调用释放资源的 API，造成内存使用持续增长。
虽然上面也调用了 columnDataClearBatch() API （此 API 仅是辅助 GC）。columnDataCloseBatch() 才是真正释放资源的 API。
由于这两个 API 具有迷惑性，在新版本 JDBC 中已经将 columnDataClearBatch 废弃了。
具体可参考 [参数绑定](https://docs.taosdata.com/reference/connector/java/#通过参数绑定写入数据)
