### ISSUE TITLE
EN Doc of  Python  connector  doesn't match with CN doc

### ISSUE THREAD

**Issue by xleili** [taosdata/TDengine#7942]
![image](https://user-images.githubusercontent.com/85657333/133430234-cfe066a7-60f5-41e4-bd8a-43cd4a86aa8b.png)

From the red circle in in the  screen shot , it's is easy to find that the EN description of python connector doesn't match with the CN version. In this situation  i think that  CN describes more appropriate. 
Wish someone will help us fix this doc, Thank you. 
Edit link: https://github.com/taosdata/TDengine/blob/develop/documentation20/en/08.connector/docs.md

**Comment by junaire** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

Assigned it to you.

**Comment by Aries-Lee1991** [comment]
@junaire We will make a certificate for the new contributor and give a souvenir. Can you leave your contact information or add my wechat (690754649).
