### ISSUE TITLE
The issue of select super table with tag

### ISSUE THREAD

**Issue by caizhenboy** [taosdata/TDengine#7955]
举例：从超级表meters中根据标签location 查询出 location值为 ： A , B , C的子表的数据
select * from meters where location in (A,B,C);  

我目前版本不支持in操作，请问怎么根据标签去过滤，在支持in之前 这样的sql应该是怎么写的呢？提前感谢您百忙之中为我解惑。

**Comment by fenghuazzm** [comment]
不能使用 in 的话可以用 or 来连接条件
