### ISSUE TITLE
Missing description in English documentation

### ISSUE THREAD

**Issue by glzhao89** [taosdata/TDengine#7966]
![image](https://user-images.githubusercontent.com/36554565/133595850-14987e3a-13eb-4084-9405-a5d3af0344c6.png)
![image](https://user-images.githubusercontent.com/36554565/133596001-f1e07db1-8a3d-430b-8379-31d5190ca4a8.png)

In the document TAOS SQL section, the English version is missing some description when describing use/switching database SQL clause compared to the Chinese version. Anyone interested in updating the English documentation? Below is the link to this section:
https://github.com/taosdata/TDengine/blob/develop/documentation20/en/12.taos-sql/docs.md

**Comment by Crane-Mocker** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

Assigned it to you.

**Comment by Aries-Lee1991** [comment]
@Crane-Mocker We will make a certificate for the new contributor and give a souvenir. Can you leave your contact information or add my wechat (690754649).
