### ISSUE TITLE
Missing Hyperlink in English Doc

### ISSUE THREAD

**Issue by glzhao89** [taosdata/TDengine#7967]
![image](https://user-images.githubusercontent.com/36554565/133597307-84dcdecd-5c03-43b2-943b-fe997d955bc4.png)
![image](https://user-images.githubusercontent.com/36554565/133597390-d839f144-7b29-4771-8764-cd5b38234df9.png)

There's a hyperlink missing in the English doc compared to the Chinese version. Anyone interested in linking the corresponding content to the right section?

Below is the link to this section:
https://github.com/taosdata/TDengine/blob/develop/documentation20/en/12.taos-sql/docs.md

**Comment by yyt6801** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

Assigned it to you.

**Comment by Aries-Lee1991** [comment]
@yyt6801 We will make a certificate for the new contributor and give a souvenir. Can you leave your contact information or add my wechat (690754649).
