### ISSUE TITLE
taos.cfg文件中以及官方文档中描述东八区的问题

### ISSUE THREAD

**Issue by lucienbao** [taosdata/TDengine#7976]
taos.cfg文件中以及官方文档中描述北京时间东八区用UTC-8，那我想问，美国旧金山时间西八区请问怎么表达？UTC--8吗？

taos.cfg配置

 system time zone
 timezone              Asia/Shanghai (CST, +0800)
 system time zone (for windows 10)
 timezone              UTC-8

官网地址
https://www.taosdata.com/cn/documentation/administrator#timezone

**Comment by dongyanqiong** [comment]
在POSIX标准中，UTC-8代表东八区，UTC+8代表西八区。TDengine使用的是POSIX Timezone标准。
