### ISSUE TITLE
How to install for python-connector

### ISSUE THREAD

**Issue by ybobxx** [taosdata/TDengine#798]
PC system: Centos7.5-x86_64
python:2.7.5
Install python-connector for TDengine-1.6.3.1 process:
1,Download  TDengine-1.6.3.1-3.x86_64.rpm (1.5M) from > https://www.taosdata.com/cn/getting-started/

2,Locate to folder location for  "TDengine-1.6.3.1-3.x86_64.rpm"
  Install commond: **rpm -ivh TDengine-1.6.3.1-3.x86_64.rpm** 

3,After install finished, Input :"taos", you can into TDengine client operate face.

4,Download Source  code from > https://github.com/taosdata/TDengine
  Locate to folder location for  "TDengine-develop\src\connector\python\linux\python2\"
   Install commond: **pip install python2** 
   After install finished,you can see "libtaos.so" in the path“/usr/lib”

5, Input >" python">"import taos"
  Error display::  "OSERROR:libtaos.so: can't open shared********"
 because the path for libtaos.so is not correct, so need to add new path:
  commond: *vi /etc/profile*
  add code: "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib"
  save and reboot centos7

6,Input “python" and "import taos",
  result: "OK", we can import taos .

A question: How to install the TDengine client from soure code package ,not install from TDengine-1.6.3.1-3.x86_64.rpm package?

**Comment by fangpanpan** [comment]
1
a) After you download the source code, execute './packaging/release.sh' 
b) cd release/, tar xzf taos-1.6.3.1-linux-2019-11-07-11-17.tar.gz 
c) cd taos-1.6.3.1-linux-2019-11-07-11-17
d)./install.sh
2
a) mkdir build &cd build
b)cmake .. & make --build .
c) cp build/lib/libtaos.so* /usr/lib 
d) ./build/bin/taosd -c /etc/taos
3
a) mkdir build &cd build
b)cmake .. & make --build .
c) make install

For python driver,
1
a) cd src/connector/python/linux
b)pip install python2
2
a) cp src/connector/python/linux/python2/taos ./
b) in the current directory, python and then in the python terminal, import taos
