### ISSUE TITLE
Can tdengine support billions of device?

### ISSUE THREAD

**Issue by kingice** [taosdata/TDengine#799]
我们准备用这个收集很多细小设备，打个比方，比如一个手机算一个设备，那场景需要支持亿级的手机设备的数据，我们想加一个tag就是设备id，那样是否会变成亿级的小表？请问这种设计让tdengine支持没有问题吧？我们不想做一些聚合，因为可能需要单独查询某个设备的log。

**Comment by guanshengliang** [comment]
亿级设备在设计层面上是可以支持的，但需要一些调优，并且对机器配置的要求也比较高。
如果真有这么多设备，那么市场规模想必也是很大，建议与我们商务(jyhou@taosdata.com)建立联系，以便获得更好的技术支持
