### ISSUE TITLE
Could someone modify the display issues as pictures

### ISSUE THREAD

**Issue by jiajingbin** [taosdata/TDengine#7991]
![image](https://user-images.githubusercontent.com/39030567/133781851-cf3bac52-e4fc-4fc7-b653-15cc6788ce6b.png)

![image](https://user-images.githubusercontent.com/39030567/133781557-63adaa1d-0ba6-4606-bc9b-47e10e9ccdb4.png)

**Comment by jiajingbin** [comment]
Link----->https://www.taosdata.com/cn/documentation/administrator

**Comment by BugCui** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

Assigned it to you.

**Comment by BugCui** [comment]
modify the display issues #8035

**Comment by Aries-Lee1991** [comment]
@BugCui We will make a certificate for the new contributor and give a souvenir. Can you leave your contact information or add my wechat (690754649).
