### ISSUE TITLE
希望能变成一个可以用go编译的库

### ISSUE THREAD

**Issue by sjqzhang** [taosdata/TDengine#8]
这么好的db，如果支持用go编译，并能作为一个库使用该多好，这样go应用程序可以将自己的应用和tdengine 编译在一起，只有一个可执行文件，就像leveldb一样可以作为一个库使用。

**Comment by hzcheng** [comment]
Thanks for your suggestion. We will consider it.

**Comment by lluck42** [comment]
那岂不是要用go重写么，1.13再做应该应该会更好吧，会支持二进制数据格式

**Comment by sjqzhang** [comment]
还用重写go支持c编译的

**Comment by lluck42** [comment]
只听说过 cgo ，没听说过支持 c 编译

发送自 Windows 10 版邮件应用

发件人: 小张
发送时间: 2019年7月15日 8:18
主题: Re: [taosdata/TDengine] 希望能变成一个可以用go编译的库 (#8)

还用重写go支持c编译的

**Comment by p1stol** [comment]
高兴的搓搓手。

**Comment by fdjhcg** [comment]
![image](https://user-images.githubusercontent.com/19942839/61200465-0bc2a180-a714-11e9-9239-a234a8139e96.png)
请问window 的客户端连接工具在哪里下载，服务器不方便开发。

**Comment by fdjhcg** [comment]
## 请问大神们，window 的客户端连接工具在哪里下载，服务器不方便开发

**Comment by Abson** [comment]
其实可以用 Go 写，提供 C 接口

**Comment by plum-lihui** [comment]
@fdjhcg windows的dll正在全力开发中，预计下周就会官网发布，敬请关注！

**Comment by plum-lihui** [comment]
用go重写整个客户端确实时一个很好的想法，但我们暂时没有这个计划，欢迎感兴趣者加入社区，成为贡献者。
感谢大家的关注和使用！

**Comment by zimengpan** [comment]
关于go重写，官方能否先指导一下大方向，比如核心代码逻辑，高优先级需要实现的功能、最低运行条件、开发过程时踩过的坑等等。目前只是读码的话，虽然comments写得算很清晰，但是实际编写之前对某些功能的设计初衷还是比较含糊
