### ISSUE TITLE
未来是否提供对GIS数据的支持？ Are there future support for GIS data?

### ISSUE THREAD

**Issue by yangjiurong** [taosdata/TDengine#80]
TDengin的大神们，未来TDengin提供对GIS数据的支持吗？例如PostGIS。

Gods of TDengin, will TDengin provide support for GIS data in the future? For example, PostGIS.

**Comment by hjxilinx** [comment]
会支持GIS相关功能，主要面向GPS定位坐标信息的查询和处理。其他的多边形、线暂时还没有考虑。
