### ISSUE TITLE
Question for CLA: Do we need to manually sign the CLA before our contribution?

### ISSUE THREAD

**Issue by FeynmanZhou** [taosdata/TDengine#800]
给 TDengine 贡献代码是否需要在线注册提交这个 CLA 协议？  
https://github.com/taosdata/TDengine/blob/develop/CONTRIBUTING.md

我在 CLA  页面没看到可以点 agree 的选项呀 https://www.taosdata.com/en/contributor/， 
是不是提交 PR 则默认同意这个 CLA ？

期待回复

**Comment by hzcheng** [comment]
目前没有手动签的选项，如果您提交了pull request，就是默认您同意了协议。

**Comment by FeynmanZhou** [comment]
明白，感谢回复
