### ISSUE TITLE
Is anybody interested to help us to modify the documentation?

### ISSUE THREAD

**Issue by zhaoyanggh** [taosdata/TDengine#8018]
There are some connectors missing in The Efficient Data Writing page, with both Chinese and English. Links are:
https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/05.insert/docs.md and
https://github.com/taosdata/TDengine/blob/develop/documentation20/en/05.insert/docs.md
<img width="1016" alt="Screen Shot 2021-09-22 at 9 39 28 AM" src="https://user-images.githubusercontent.com/47117543/134269924-24e30a97-cc69-4937-924a-f97fc7ea7eba.png">
<img width="626" alt="Screen Shot 2021-09-22 at 9 39 18 AM" src="https://user-images.githubusercontent.com/47117543/134269933-742578f2-8b97-486c-9010-96ae5338e647.png">
To find the missing connectors, you can check the Efficient Data Querying page, with the links:
https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/06.queries/docs.md or
https://github.com/taosdata/TDengine/blob/develop/documentation20/en/06.queries/docs.md

**Comment by lyleshaw** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

Assigned it to you.

**Comment by Aries-Lee1991** [comment]
@lyleshaw We will make a certificate for the new contributor and give a souvenir. Can you leave your contact information or add my wechat (690754649).
