### ISSUE TITLE
oom crashd  DND SField checksum error

### ISSUE THREAD

**Issue by 1406990759** [taosdata/TDengine#802]
**Bug Description**
 内存不足 oom后  重启崩溃
sudo  systemctl start taosd  启动失败
 
错误日志
taosd.service - TDengine server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Sat 2019-11-30 12:37:51 CST; 13min ago
  Process: 11546 ExecStart=/usr/bin/taosd (code=dumped, signal=SEGV)
 Main PID: 11546 (code=dumped, signal=SEGV)

Nov 30 12:37:50 SPIDER04 systemd[1]: taosd.service: main process exited, code=dumped, status=11/SEGV
Nov 30 12:37:50 SPIDER04 systemd[1]: Unit taosd.service entered failed state.
Nov 30 12:37:50 SPIDER04 systemd[1]: taosd.service failed.
Nov 30 12:37:51 [SPIDER04](`url`) systemd[1]: taosd.service holdoff time over, scheduling restart.
Nov 30 12:37:51 SPIDER04 systemd[1]: Stopped TDengine server service.
Nov 30 12:37:51 SPIDER04 systemd[1]: start request repeated too quickly for taosd.service
Nov 30 12:37:51 SPIDER04 systemd[1]: Failed to start TDengine server service.
Nov 30 12:37:51 SPIDER04 systemd[1]: Unit taosd.service entered failed state.
Nov 30 12:37:51 SPIDER04 systemd[1]: taosd.service failed.

 

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space [8G]
 - TDengine Version [e.g. 1.6.3.1]

**Additional Context**

**Comment by 1406990759** [comment]
<img width="1006" alt="WX20191130-142423@2x" src="https://user-images.githubusercontent.com/20317001/69896870-e363d880-137e-11ea-9913-1c7da2f96262.png">

**Comment by fangpanpan** [comment]
请问有办法远程去查看一下情况吗？您可以将远程的方法发到fpan@taosdata.com.
