### ISSUE TITLE
 TDB ERROR vgId:9 failed to insert data since Invalid table ID

### ISSUE THREAD

**Issue by bsmwrq** [taosdata/TDengine#8021]
**General Questions**
![image](https://user-images.githubusercontent.com/43392635/134296841-9615fa05-9a74-4268-8697-8749ffc44bac.png)
![image](https://user-images.githubusercontent.com/43392635/134296944-cce0b7da-930d-4130-be05-a684dd82cf50.png)
![image](https://user-images.githubusercontent.com/43392635/134297106-62c84d88-0ebb-40d9-8cdf-a83a085f9e8e.png)

请问启动时候失败了，这个是怎么回事？
I got this when i use command " ./taosd ",how can i resolve it ? pls help.

**Comment by yu285** [comment]
现在服务能起来吗

**Comment by yu285** [comment]
关于Invalid table ID  报错原理可参考：https://www.taosdata.com/tdengine-engineering/14534.html

并且建议迁移到 3.0 新版本上。
