### ISSUE TITLE
Insert Chinese character issue

### ISSUE THREAD

**Issue by zhuxindi** [taosdata/TDengine#8038]
通过c++客户端插入中文到数据表中出现异常：
用taos_query函数依次执行sql语句如下：
1、建表（正常）
create table if not exists 'DeviceEvent_project000000000000000000000001_product000000000000000000000001_device000000000000000000000001' (ts timestamp,id binary(36),name binary(128),content nchar(4000))
2、插入英文数据（正常）
insert into 'DeviceEvent_project000000000000000000000001_product000000000000000000000001_device000000000000000000000001' values (1632287634578,"evnet-0000-0000-0000-000000000002","on_alarm","test")
3、插入中文数据（正常）
insert into 'DeviceEvent_project000000000000000000000001_product000000000000000000000001_device000000000000000000000001' values (1632287634578,"evnet-0000-0000-0000-000000000002","on_alarm","中国")
4、插入中文数据（异常！提示错误invalid operation:  (Illegal byte sequence)）
insert into 'DeviceEvent_project000000000000000000000001_product000000000000000000000001_device000000000000000000000001' values (1632287634578,"evnet-0000-0000-0000-000000000002","on_alarm","设备")
5、通过taos命令查询数据库中，确认前2条插入语句成功将数据插入，第三条插入语句未将数据插入
taos> select * from DeviceEvent_project000000000000000000000001_product000000000000000000000001_device000000000000000000000001;
           ts            |               id               |              name              |            content             |
=============================================================================================================================
 2021-09-22 13:13:54.478 | evnet-0000-0000-0000-000000... | on_alarm                       | test                           |
 2021-09-22 13:13:54.578 | evnet-0000-0000-0000-000000... | on_alarm                       | 涓浗                          |
Query OK, 2 row(s) in set (0.006265s)
目前发现只有插入“设备”2个字时提示出错，其他汉字及英文未发现问题
使用的客户端为TDengine-client-2.2.0.0-Windows-x64.exe 服务端为TDengine-server-2.2.0.0-Linux-x64.rpm

**Comment by sxyseo** [comment]
这边MacOS下编译的最新版本
插入中文正常返回，查询没有结果，时间相差25小时40分钟的样子～


`
taos> create table if not exists 'DeviceEvent_project000000000000000000000001_product000000000000000000000001_device00000000000000
0000000001' (ts timestamp,id binary(36),name binary(128),content nchar(4000)) ;
Query OK, 0 of 0 row(s) in database (0.000937s)

taos> insert into 'DeviceEvent_project000000000000000000000001_product000000000000000000000001_device000000000000000000000001' val
ues (1632287634578,"evnet-0000-0000-0000-000000000002","on_alarm","test") ;
Query OK, 1 of 1 row(s) in database (0.006088s)

taos> insert into 'DeviceEvent_project000000000000000000000001_product000000000000000000000001_device000000000000000000000001' val
ues (1632287634578,"evnet-0000-0000-0000-000000000002","on_alarm","设备") ;
Query OK, 1 of 1 row(s) in database (0.001606s)

taos> insert into 'DeviceEvent_project000000000000000000000001_product000000000000000000000001_device000000000000000000000001' val
ues (1632287634578,"evnet-0000-0000-0000-000000000002","on_alarm","中国");
Query OK, 1 of 1 row(s) in database (0.000399s)

taos> select * from DeviceEvent_project000000000000000000000001_product000000000000000000000001_device000000000000000000000001;
           ts            |               id               |              name              |            content             |
=============================================================================================================================
 2021-09-22 13:13:54.578 | evnet-0000-0000-0000-000000... | on_alarm                       | test                           |
Query OK, 1 row(s) in set (0.038076s)
`

![image](https://user-images.githubusercontent.com/8522164/134465751-c0c03699-bf60-4e0e-be9e-dec1c4edd1d4.png)

**Comment by winshining** [comment]
@zhuxindi 你给出的几个插入操作的时间戳都是一样的，是想更新数据吗？服务端有没有配置 update 参数？
按照你给出的版本没有复现问题：
![image-2021-09-23-16-48-16-678](https://user-images.githubusercontent.com/3250905/134479919-5de4c77b-1834-426f-bce1-1796664ee8a9.png)

**Comment by winshining** [comment]
@zhuxindi 请问是用 taos shell 还是用其他的 connector (例如 Java)写入的数据？如果是其他的 connector，字符编码不对就无法写入数据

**Comment by arielyang** [comment]
This issue was closed because it has been inactive for too many days.
