### ISSUE TITLE
[bug] Returned result is incorrect using max() function

### ISSUE THREAD

**Issue by zhuchunwu** [taosdata/TDengine#804]
**Screenshots**
![image](https://user-images.githubusercontent.com/8374876/69898008-748e7b80-138e-11ea-9606-20433054f495.png)

上图所示的数据中，max(y) 应该是 -10.00000, 而结果是 0.00000

**Environment :**
 - TDengine Version: 1.6.3.1

**Comment by hjxilinx** [comment]
bug has been fixed in the newly release version.
