### ISSUE TITLE
grafana couldn't filter new variables by intervals

### ISSUE THREAD

**Issue by 784134748** [taosdata/TDengine#8072]
![截屏2021-09-26 上午1 37 57](https://user-images.githubusercontent.com/16873072/134780991-eba6d6b1-aed1-4353-b683-4468adf9bd91.png)

![截屏2021-09-26 上午1 38 33](https://user-images.githubusercontent.com/16873072/134780997-b2d0e7f9-6d2b-4e12-952a-0f464a026f09.png)

添加时间范围后无法筛选出对应的数据

**Comment by afwerar** [comment]
![image](https://user-images.githubusercontent.com/20500927/134800571-6eb18ebf-9506-4665-a2fa-670cfb363c6d.png)
你可以这样使用时间变量

**Comment by 784134748** [comment]
![image](https://user-images.githubusercontent.com/16873072/134801294-8b8a17c3-61ec-4ac8-bbe6-f7fea979182d.png)
高版本已经不识别这种写法了耶
