### ISSUE TITLE
docker run快速启动现在启动不了

### ISSUE THREAD

**Issue by zzzhanghongli** [taosdata/TDengine#8077]
**Bug Description**

>docker run tdengine/tdengine

>docker logs tdengine

server disk:/var/log/taos space remain 0.000 GB, total 58.4 GB, stop print log.
server disk:/var/log/taos space remain 0.000 GB, total 58.4 GB, stop print log.
server disk:/var/log/taos space remain 0.000 GB, total 58.4 GB, stop print log.
server disk:/var/log/taos space remain 0.000 GB, total 58.4 GB, stop print log.
server disk:/var/log/taos space remain 0.000 GB, total 58.4 GB, stop print log.
server disk:/var/log/taos space remain 0.000 GB, total 58.4 GB, stop print log.
server disk:/var/log/taos space remain 0.000 GB, total 58.4 GB, stop print log

**Comment by zitsen** [comment]
Seems your /var or / disk is out of space.

**Comment by zzzhanghongli** [comment]
> Seems your /var or / disk is out of space.

docker run tdengine/tdengine

service is not runing...

**Comment by sangshuduo** [comment]
please paste the output of command 'df -H'

**Comment by zzzhanghongli** [comment]
> please paste the output of command 'df -H'

 holyzhang@holyzhang  ~  df -H                                                                                               ✔  4420  19:29:47
Filesystem       Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk1s1s1   1.0T    15G   525G     3%  553781 9767424379    0%   /
devfs            194k   194k     0B   100%     654          0  100%   /dev
/dev/disk1s5     1.0T   9.7G   525G     2%      11 9767978149    0%   /System/Volumes/VM
/dev/disk1s3     1.0T   421M   525G     1%    1694 9767976466    0%   /System/Volumes/Preboot
/dev/disk1s6     1.0T   2.6M   525G     1%      19 9767978141    0%   /System/Volumes/Update
/dev/disk1s2     1.0T   449G   525G    47% 3259038 9764719122    0%   /System/Volumes/Data
map auto_home      0B     0B     0B   100%       0          0  100%   /System/Volumes/Data/home

**Comment by zzzhanghongli** [comment]
![image](https://user-images.githubusercontent.com/13790325/134806551-9832cb87-7564-48a0-81e9-80a6d9bcca4a.png)

**Comment by zzzhanghongli** [comment]
> please paste the output of command 'df -H'

![image](https://user-images.githubusercontent.com/13790325/134806799-0a0ab054-ffc9-4d5b-89ca-708a83398ed1.png)

other docker service  ok... only taos no start...

**Comment by zzzhanghongli** [comment]
> please paste the output of command 'df -H'

i know.

![image](https://user-images.githubusercontent.com/13790325/134807404-799bd278-2ab5-4de4-937a-d3a47f1ea847.png)

![image](https://user-images.githubusercontent.com/13790325/134807424-1aa88010-8e96-43a1-9bf0-c3fb9ebf1d87.png)


ok. taos start .thinks.
