### ISSUE TITLE
Invalid app version

### ISSUE THREAD

**Issue by lexang** [taosdata/TDengine#8096]
server version:2.2.0.0
client versin: taos-jdbcdriver  2.0.34

error:
java.sql.SQLException: JNI ERROR (2354): Invalid app version
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:74)

documentation: 
aos-jdbcdriver 版本     TDengine 版本     JDK 版本
2.0.33 - 2.0.34              2.0.3.0 及以上      1.8.x 
2.0.31 - 2.0.32              2.1.3.0 及以上      1.8.x 

why????

**Comment by yu285** [comment]
TDengine客户端和服务端版本号要强一致

比如服务端2.0.20.xx 客户端也要2.0.20.xx

**Comment by yu285** [comment]
不是的，请您看下这篇文章：
https://mp.weixin.qq.com/s/ZFe0Rft6URSaC4IucBQTqQ
