### ISSUE TITLE
源码编译版本不支持leastsquares？

### ISSUE THREAD

**Issue by zh4af** [taosdata/TDengine#81]
使用GitHub源码在ubuntu上编译，分别运行build目录下的taosd和taos，
./build/bin/taosd -c test/cfg
./build/bin/taos -c test/cfg

在taos shell执行下面命令：
taso> use log;
taos> select leastsquares(cpu_taosd) from dn_172_31_33_8  where ts >= now-30m;
TSDB error: invalid SQL: invalid parameters

官网文档上是有leastsquares命令的使用，但是这里报错

**Comment by hjxilinx** [comment]
文档有误，我们一会儿修正。正确的使用方法是：
select leastsquares(cpu_taosd, 1, 1) from  from dn_172_31_33_8 where ts >= now-30m;  第一个参数是：x轴起始值，第二个参数是X轴步长的值（增量），这两个参数根据自己的需求设置即可。
