### ISSUE TITLE
Query the collection of the latest data columns in a super table

### ISSUE THREAD

**Issue by a1371083012** [taosdata/TDengine#8110]
How to query the latest column of each table in the super table and the last data set? 
![image](https://user-images.githubusercontent.com/46132710/135197108-9ed85562-79f9-440f-875e-df20b8d0f1e6.png)
I want the result to look like a collection of the last column of 512 tables.
thank!

**Comment by yu285** [comment]
select last_row(*) from super table  group by tbname
