### ISSUE TITLE
How to make field auto increment just like MySql AUTO_INCREMENT

### ISSUE THREAD

**Issue by codecvt** [taosdata/TDengine#812]
Issue in English:
How to make field auto increment just like MySql AUTO_INCREMEN ?

Issue in Chinese:
怎样实现表字段的“自增”? 就像MySql的 `AUTO_INCREMENT`所提供的功能。

Thanks.

**Comment by plum-lihui** [comment]
抱歉，目前TDengine没有这样的设计和实现。而是以timestamp字段做key

**Comment by plum-lihui** [comment]
抱歉，TDengine目前没有这样的设计和实现，主要以timestamp字段做key。

**Comment by codecvt** [comment]
Thanks for your suggestion
