### ISSUE TITLE
group + order  by not work

### ISSUE THREAD

**Issue by chuangtim** [taosdata/TDengine#8128]
**Bug Description**
`select count(*) as ss from gw_state group by gid order by ss;`
使用以上语句查询，提示以下错误，gid是TAG, 难道别名无法order by?
`DB error: invalid SQL: invalid column name (0.001565s)`

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - TDengine Version [2.0.20.10]

**Comment by chuangtim** [comment]
@guanshengliang @hjxilinx

**Comment by zhmeng** [comment]
@yu285  请问现在支持 count后，按照 count 列 group 了吗？

**Comment by hjxilinx** [comment]
外面套一个外层查询就可以排序了。
<code>
select * from (select count(*) as ss from gw_state group by gid) order by ss asc;\
</code>
