### ISSUE TITLE
In some certain cases,Database rejected connection

### ISSUE THREAD

**Issue by shaoguanlee** [taosdata/TDengine#8139]
## 环境
版本： 2.2.0.2
Win10 Docker 单机，镜像ID：143ac3978db2
CPU：11400F，6核12线程
硬盘: TOSHIBA DT01ACA100
内存：16G
.wslconfig: memory 8G
当前数据目录大小: 经过compact后约30G

## 过程描述
在控制台使用select count（*） from supertable 对一个有100W数据表，累计数据量为3Y的超级表进行统计查询
查询过程中，被服务端断开连接，之后无法再次连接上数据库服务器
在此期间未对数据库进行其它操作
怀疑是查询压力过大导致服务器假死，观察并经过半个小时的等待之后，使用控制台可以连接上数据库服务器

```
taos> select count(*) from c_entrance;
PS C:\Users\admin> docker exec -it tdengine bash
root@a3183b973629:~/TDengine-server-2.2.0.2# taos

Welcome to the TDengine shell from Linux, Client Version:2.2.0.2
Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.

taos connect failed, reason: Unable to establish connection.

root@a3183b973629:~/TDengine-server-2.2.0.2# taos

Welcome to the TDengine shell from Linux, Client Version:2.2.0.2
Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.

taos connect failed, reason: Unable to establish connection.
```

## 疑惑
1. 查询压力大时，数据库断开所有客户端的连接是否是正常行为？
2. 再遇到这种情况时，该如何应对？

**Comment by yu285** [comment]
请问查询过程中，数据库服务有没有挂掉过又重新启动了？
