### ISSUE TITLE
String escape failed

### ISSUE THREAD

**Issue by 1406990759** [taosdata/TDengine#817]
**Bug Description**
 1.6.4.0  \' 转义失败 
 1.6.3.0  \' 转义正常 

1.6.4.0  超长截断报错(string data overflow)
1.6.3.0  正常截断

**To Reproduce**
1. create database  if not exists test;
2. create table if not exists test.demo  (ts timestamp, task_id binary(40),  message binary(20));
3. INSERT INTO test.demo(ts, task_id,  message) VALUES(0, '123', '11111\\'99911111') ;
4. See error DB error: invalid SQL: syntax error near "') ;" () expected) 

5.INSERT INTO test.demo(ts, task_id,  message) VALUES(0, '123', '111119999911111999991111199999') ;
6. See error DB error: invalid SQL: syntax error near "111119999911111999991111199999') ;" (string data overflow)

 
**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.4.0]

**Additional Context**

**Comment by plum-lihui** [comment]
由于在进行代码优化整理，多进行了一次转义符的处理，会很快完成修复。
多谢！
