### ISSUE TITLE
Is there anyone interested in adding a space (punctuation) between Chinese characters and English terms in the documentation?

### ISSUE THREAD

**Issue by Aries-Lee1991** [taosdata/TDengine#8181]
[English description] For enhancing the readability and understandability of TDengine’s documents, is there anyone interested in adding a space (punctuation) between Chinese characters and English terms in the documentation?

Take “位置Location” for instance, you are expected to add a space between “位置” and “Location”, then the revised version should be “位置 Location”

Here is the link of document: [03.architecture](https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/03.architecture/docs.md)

[中文描述] 为了优化文档可读性，有人愿意为这篇文档中相邻中英文字符间加上空格吗？

以“位置Location”为例，你需要在“位置”和“Location”之间加上空格，最终呈现为“位置 Location”。

文档链接：[03.architecture](https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/03.architecture/docs.md)

**Comment by augfool** [comment]
Please Assign to me

**Comment by Aries-Lee1991** [comment]
> Please Assign to me

Assigned it to you.

**Comment by Aries-Lee1991** [comment]
This task is currently unmanned. Does anyone want to do it?

**Comment by Aries-Lee1991** [comment]
> Maybe I can try?

Sorry, the issue is assigned.

**Comment by DerrickRose2019** [comment]
> > I can try to fix it!
> 
> OK，Assigned it to you.

Thanks
