### ISSUE TITLE
Supplement the parameter descriptions

### ISSUE THREAD

**Issue by Aries-Lee1991** [taosdata/TDengine#8184]
在 [12.taos-sql](https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/12.taos-sql/docs.md) 数据库管理部分提到了UPDATE参数，但现有文档没有表述清楚UPDATE在不同赋值时的含义。
UPDATE设为0时，表示不允许更新数据，后发送的相同时间戳的数据会被直接丢弃；
UPDATE设为1时，表示更新全部列数据，即如果更新一个数据行，其中某些列没有提供取值，那么这些列会被设为 NULL；
UPDATE设为2时，表示支持更新部分列数据，即如果更新一个数据行，其中某些列没有提供取值，那么这些列会保持原有数据行中的对应值。

有感兴趣的朋友可以将上述描述修改到文档中吗？文档仓库： [12.taos-sql](https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/12.taos-sql/docs.md)

**Comment by jaingmengmeng** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

Assigned it to you.

**Comment by Aries-Lee1991** [comment]
@jaingmengmeng We will make a certificate for the new contributor and give a souvenir. Can you leave your contact information or add my wechat (690754649).
