### ISSUE TITLE
Adding a space (punctuation) between Chinese characters and English terms in the documentation

### ISSUE THREAD

**Issue by Aries-Lee1991** [taosdata/TDengine#8185]
[English description] For enhancing the readability and understandability of TDengine’s documents, is there anyone interested in adding a space (punctuation) between Chinese characters and English terms in the documentation?

Take “SQL命令” for instance, you are expected to add a space between “SQL” and “命令”, then the revised version should be “SQL 命令”

Here is the link of document: [04.model](https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/04.model/docs.md)

[中文描述] 为了优化文档可读性，有人愿意为这篇文档中相邻中英文字符间加上空格吗？

以“SQL命令”为例，你需要在“SQL”和“命令”之间加上空格，最终呈现为“SQL 命令”。

文档链接：[04.model](https://github.com/taosdata/TDengine/blob/develop/documentation20/cn/04.model/docs.md)

**Comment by luharuka** [comment]
@Aries-Lee1991    mail id:-  rishabhluharuka@gmail.com

**Comment by luharuka** [comment]
hey @Aries-Lee1991 any update you have not merged it
