### ISSUE TITLE
请问TDengine 的 Grafana 插件在哪里

### ISSUE THREAD

**Issue by ghost281** [taosdata/TDengine#82]
Shengliang Guan 在“使用TDengine快速搭建运维监测系统”一文中提到“配置Grafana，TDengine 的 Grafana 插件 code/examples/grafana 目录下，”，怎么没有这个code/examples/grafana目录呢

**Comment by plum-lihui** [comment]
不好意思，文档描述有误。应该是在/usr/local/taos/connector/grafana目录下。

**Comment by ghost281** [comment]
I've found it,thanks.
