### ISSUE TITLE
jdbc连接taos部署了一个程序，如何制作成docker镜像运行

### ISSUE THREAD

**Issue by kct12345** [taosdata/TDengine#8235]
请教一个问题我jdbc连接taos部署了一个程序，我制作成docker镜像运行，提示找不到java.lang.UnsatisfiedLinkError: no taos in java.library.path，猜测是libtaos.so找不到，我制作镜像的时候已经把他复制进去了。

我的DockerFile如下
FROM openjdk:8-jdk-alpine

VOLUME /tmp

EXPOSE 8081

ADD ./taos-jb-service.jar /app.jar
ADD ./libtaos.so.2.0.20.17 /usr/lib
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENV JAVA_OPTS=""

ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]
~

**Comment by huolibo** [comment]
我基于centos镜像构建的环境将libtaos.so放在/usr/lib下。然后copy一份taos.cfg到/etc/taos目录下。可以正常执行。建议先手动构建调试成功后，再编写Dockerfile文件。

**Comment by sangshuduo** [comment]
暂时不支持 在alpine 环境下运行

**Comment by kct12345** [comment]
> 我基于centos镜像构建的环境将libtaos.so放在/usr/lib下。然后copy一份taos.cfg到/etc/taos目录下。可以正常执行。建议先手动构建调试成功后，再编写Dockerfile文件。

验证成功
