### ISSUE TITLE
The pointer is NULL  in \src\client\src\tscUtil.c

### ISSUE THREAD

**Issue by star-db-bugs** [taosdata/TDengine#8236]
**Bug Description**
The pointer is NULL bug in \src\client\src\tscUtil.c 
in line 2484,function tscExprAddParams.
**To Reproduce**
```
 1 assert (pExpr != NULL || argument != NULL || bytes != 0);
 2 tVariantCreateFromBinary(&pExpr->param[pExpr->numOfParams], argument, bytes, type);
```
in this assert if pExpr == NULL,argument != NULL,and bytes != 0
the pExpr->param[pExpr->numOfParams] is a bug of the pointer is NULL.
This is the reported by my automatic tool. Please answer me whether I am wrong. Looking forward to your reply

**Comment by sangshuduo** [comment]
$ git blame src/client/src/tscUtil.c -L 2714,2720

output:
8875149dde25 (Haojun Liao 2020-11-16 14:39:00 +0800 2714)   assert (pExpr != NULL || argument != NULL || bytes != 0);
^57492cc12d (hzcheng     2019-07-11 16:36:16 +0800 2715)
^57492cc12d (hzcheng     2019-07-11 16:36:16 +0800 2716)   // set parameter value
^57492cc12d (hzcheng     2019-07-11 16:36:16 +0800 2717)   // transfer to tVariant from byte data/no ascii data
c2e91fcb751 (slguan      2019-11-07 18:12:26 +0800 2718)   tVariantCreateFromBinary(&pExpr->param[pExpr->numOfParams], argument, bytes, type);
^57492cc12d (hzcheng     2019-07-11 16:36:16 +0800 2719)   pExpr->numOfParams += 1;
875149dde25 (Haojun Liao 2020-11-16 14:39:00 +0800 2720)

re-assign this issue to Shengliang Guan
