### ISSUE TITLE
时间筛选条件不生效

### ISSUE THREAD

**Issue by Alec01** [taosdata/TDengine#8259]
**Bug Description**
时间筛选条件不生效

**To Reproduce**
1. 执行SQL语句“select VariableName as 'Metric',first(FirstValue) as Val   from fcloudqa.svariableaggregations  where  Ts >= '2021-10-14 00:00:00'  AND Ts <= '2021-10-14 23:59:59' interval(24h, 0h) group by VariableName  ;”
2. See result
![截图_20214215104225](https://user-images.githubusercontent.com/20262947/137423998-fa1d136c-a783-47c7-ac14-108fd13ab783.png)

**Expected Behavior**
期望时间筛选条件Ts >= '2021-10-14 00:00:00'  AND Ts <= '2021-10-14 23:59:59' 生效，所以结果应该都在2021-10-14日内，但TdEngine返回结果却是：2021-10-13 08:00:00.000

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Memory, CPU, current Disk Space
 - TDengine Version 2.0.16.0

**Additional Context**

**Comment by yu285** [comment]
请问这是哪个版本

**Comment by yu285** [comment]
看到版本了，这个版本很久了。建议换新，应该不会有这个问题了 2.2.0.5
