### ISSUE TITLE
 tdengine-1.6.3.1-3.x86_64 update to TDengine-1.6.4.1-3.x86_64  error

### ISSUE THREAD

**Issue by 59471032** [taosdata/TDengine#827]
`base/7/x86_64                                                                                                                                            | 3.6 kB  00:00:00     
docker-ce-stable/x86_64                                                                                                                                  | 3.5 kB  00:00:00     
epel/x86_64/metalink                                                                                                                                     | 8.7 kB  00:00:00     
epel/x86_64                                                                                                                                              | 5.3 kB  00:00:00     
epel/x86_64/updateinfo                                                                                                                                   | 1.0 MB  00:00:00     
epel/x86_64/primary_db                                                                                                                                   | 6.9 MB  00:00:00     
extras/7/x86_64                                                                                                                                          | 2.9 kB  00:00:00     
mysql-connectors-community/x86_64                                                                                                                        | 2.5 kB  00:00:00     
mysql-tools-community/x86_64                                                                                                                             | 2.5 kB  00:00:00     
mysql57-community/x86_64                                                                                                                                 | 2.5 kB  00:00:00     
pgdg10/7/x86_64                                                                                                                                          | 3.6 kB  00:00:00     
pgdg10/7/x86_64/primary_db                                                                                                                               | 401 kB  00:00:02     
pgdg11/7/x86_64                                                                                                                                          | 3.6 kB  00:00:00     
pgdg11/7/x86_64/primary_db                                                                                                                               | 358 kB  00:00:02     
pgdg12/7/x86_64                                                                                                                                          | 3.6 kB  00:00:00     
pgdg12/7/x86_64/primary_db                                                                                                                               | 133 kB  00:00:00     
pgdg94/7/x86_64                                                                                                                                          | 3.6 kB  00:00:00     
pgdg95/7/x86_64                                                                                                                                          | 3.6 kB  00:00:00     
pgdg95/7/x86_64/primary_db                                                                                                                               | 397 kB  00:00:03     
pgdg96/7/x86_64                                                                                                                                          | 3.6 kB  00:00:00     
pgdg96/7/x86_64/primary_db                                                                                                                               | 409 kB  00:00:03     
remi-safe                                                                                                                                                | 3.0 kB  00:00:00     
remi-safe/primary_db                                                                                                                                     | 1.6 MB  00:00:06     
updates/7/x86_64                                                                                                                                         | 2.9 kB  00:00:00     

Dependencies Resolved

================================================================================================================================================================================
 Package                                 Arch                                  Version                                   Repository                                        Size
================================================================================================================================================================================
Installing:
 TDengine                                x86_64                                1.6.4.1-3                                 /TDengine-1.6.4.1                                 11 M

Transaction Summary
================================================================================================================================================================================
Install  1 Package

Total size: 11 M
Installed size: 11 M
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test

Transaction check error:
  file /usr/local/taos/bin/taos from install of TDengine-1.6.4.1-3.x86_64 conflicts with file from package tdengine-1.6.3.1-3.x86_64
  file /usr/local/taos/bin/taosd from install of TDengine-1.6.4.1-3.x86_64 conflicts with file from package tdengine-1.6.3.1-3.x86_64
  file /usr/local/taos/init.d/taosd from install of TDengine-1.6.4.1-3.x86_64 conflicts with file from package tdengine-1.6.3.1-3.x86_64
  file /usr/local/taos/bin/taosdemo from install of TDengine-1.6.4.1-3.x86_64 conflicts with file from package tdengine-1.6.3.1-3.x86_64
  file /usr/local/taos/bin/taosdump from install of TDengine-1.6.4.1-3.x86_64 conflicts with file from package tdengine-1.6.3.1-3.x86_64
  file /usr/local/taos/cfg/taos.cfg from install of TDengine-1.6.4.1-3.x86_64 conflicts with file from package tdengine-1.6.3.1-3.x86_64
  file /usr/local/taos/connector/go/src/taosSql/rows.go from install of TDengine-1.6.4.1-3.x86_64 conflicts with file from package tdengine-1.6.3.1-3.x86_64
  file /usr/local/taos/connector/go/src/taosSql/taosSqlCgo.go from install of TDengine-1.6.4.1-3.x86_64 conflicts with file from package tdengine-1.6.3.1-3.x86_64
  file /usr/local/taos/connector/go/src/taosSql/utils.go from install of TDengine-1.6.4.1-3.x86_64 conflicts with file from package tdengine-1.6.3.1-3.x86_64
  file /usr/local/taos/connector/taos-jdbcdriver-1.0.2-dist.jar from install of TDengine-1.6.4.1-3.x86_64 conflicts with file from package tdengine-1.6.3.1-3.x86_64
  file /usr/local/taos/examples/JDBC/readme.md from install of TDengine-1.6.4.1-3.x86_64 conflicts with file from package tdengine-1.6.3.1-3.x86_64
  file /usr/local/taos/examples/R/command.txt from install of TDengine-1.6.4.1-3.x86_64 conflicts with file from package tdengine-1.6.3.1-3.x86_64
  file /usr/local/taos/examples/go/src/taosapp/taosapp.go from install of TDengine-1.6.4.1-3.x86_64 conflicts with file from package tdengine-1.6.3.1-3.x86_64
  file /usr/local/taos/examples/lua/lua_connector.c from install of TDengine-1.6.4.1-3.x86_64 conflicts with file from package tdengine-1.6.3.1-3.x86_64
  file /usr/local/taos/examples/lua/test.lua from install of TDengine-1.6.4.1-3.x86_64 conflicts with file from package tdengine-1.6.3.1-3.x86_64
  file /usr/local/taos/examples/matlab/TDengineDemo.m from install of TDengine-1.6.4.1-3.x86_64 conflicts with file from package tdengine-1.6.3.1-3.x86_64
  file /usr/local/taos/examples/python/read_example.py from install of TDengine-1.6.4.1-3.x86_64 conflicts with file from package tdengine-1.6.3.1-3.x86_64
  file /usr/local/taos/include/taos.h from install of TDengine-1.6.4.1-3.x86_64 conflicts with file from package tdengine-1.6.3.1-3.x86_64
  file /usr/local/taos/script/post.sh from install of TDengine-1.6.4.1-3.x86_64 conflicts with file from package tdengine-1.6.3.1-3.x86_64
  file /usr/local/taos/script/preun.sh from install of TDengine-1.6.4.1-3.x86_64 conflicts with file from package tdengine-1.6.3.1-3.x86_64

Error Summary
-------------
`

**Comment by plum-lihui** [comment]
由于包名将社区版和企业版统一修改成TDengine，所以需要先卸载一下老版本，但不会删除数据库和配置文件，再安装新版本就可以了。

**Comment by schenton** [comment]
> 由于包名将社区版和企业版统一修改成TDengine，所以需要先卸载一下老版本，但不会删除数据库和配置文件，再安装新版本就可以了。

请问，如何卸载老版本？  我直接从1.6.3.1 升级到1.6.4.3 不成功。 想先卸载，再重装试试。

**Comment by sangshuduo** [comment]
主要是几个目录 /etc/taos/, /var/lib/taos, /var/log/taos 和 /usr/local/taos
