### ISSUE TITLE
datatype is error for C code abs_max.c

### ISSUE THREAD

**Issue by wenzhouwww** [taosdata/TDengine#8274]
https://github.com/taosdata/TDengine/blob/develop/tests/script/sh/abs_max.c

in function abs_max.c , the datatype of output is error when the input is bigint ,but output is int , and lib function abs() only can support int32_t as input!
![image](https://user-images.githubusercontent.com/27729854/137471901-553ab211-c481-4d58-bfcc-e31db4cb5a99.png)

**Comment by mahmoudmohamed22** [comment]
can you assign me to solve issue?

**Comment by wjsvec** [comment]
#8279

**Comment by wjsvec** [comment]
[https://github.com/taosdata/TDengine/pull/8279](url)
I am a new hand, first Pull requests
