### ISSUE TITLE
DB error: Invalid table ID

### ISSUE THREAD

**Issue by xiangxud** [taosdata/TDengine#8278]
taos> select * from stocksurgicalsuit;

DB error: Invalid table ID (0.003212s)
taos> select * from stocksurgicalsuit;

DB error: Invalid table ID (0.002583s)
taos> show stables;
              name              |      created_time       | columns |  tags  |   tables    |
============================================================================================
 heart                          | 2021-10-07 23:23:48.446 |       7 |      6 |           1 |
 stocksurgicalsuit              | 2021-10-07 13:47:24.016 |       3 |      5 |          36 |
Query OK, 2 row(s) in set (0.000839s)

taos> describe stocksurgicalsuit;
             Field              |         Type         |   Length    |   Note   |
=================================================================================
 ts                             | TIMESTAMP            |           8 |          |
 goodsid                        | BINARY               |         100 |          |
 goodsrfidcode                  | BINARY               |         100 |          |
 taghash                        | BINARY               |          34 | TAG      |
 deviceid                       | BINARY               |         128 | TAG      |
 goodssize                      | BINARY               |         128 | TAG      |
 goodstatus                     | BINARY               |         128 | TAG      |
 goodstype                      | BINARY               |         128 | TAG      |
Query OK, 8 row(s) in set (0.000264s)

taos> select * from stocksurgicalsuit;

DB error: Invalid table ID (0.002587s)
taos> select * from heart;

DB error: Invalid table ID (0.002750s)
taos> show variables;
           name           |             value              |
============================================================
 defaultJSONStrType       | binary                         |
 deadLockKillQuery        | 0                              |
 version                  | 2.2.0.5                        |
 buildinfo                | Built at 2021-10-15 22:15:13   |
 gitinfoOfInternal        | 5d843053320ab0e9ff915a82367... |
 gitinfo                  | 5d843053320ab0e9ff915a82367... |
 telegrafUseFieldNum      | 0                              |
 topicBinaryLen           | 16000                          |
 stream                   | 1                              |
 monitor                  | 1                              |
 mqtt                     | 0                              |
 http                     | 1                              |
 adjustMaster             | 1                              |
 slaveQuery               | 1                              |
 flowctrl                 | 1                              |
 mnodeEqualVnodeNum       | 4                              |
 minimalDataDirGB         | 2.000000                       |
 minimalTmpDirGB          | 1.000000                       |
 minimalLogDirGB          | 1.000000                       |
 maxConnections           | 5000                           |
 maxShellConns            | 50000                          |
 charset                  | UTF-8                          |
 locale                   | en_US.UTF-8                    |
 timezone                 |  (CST, +0800)                  |
 keepColumnName           | 0                              |
 retrieveBlockingModel    | 0                              |
 queryBufferSize          | -1                             |
 maxNumOfOrderedRes       | 1000000                        |
 maxRegexStringLen        | 128                            |
 maxWildCardsLength       | 100                            |
 maxSQLLength             | 1048576                        |
 compressColData          | -1                             |
 compressMsgSize          | -1                             |
 cachelast                | 0                              |
 update                   | 0                              |
 quorum                   | 1                              |
 partitions               | 4                              |
 replica                  | 1                              |
 fsync                    | 3000                           |
 walLevel                 | 1                              |
 comp                     | 2                              |
 precision                | 0                              |
 maxRows                  | 4096                           |
 minRows                  | 100                            |
 keep                     | 3650                           |
 days                     | 10                             |
 blocks                   | 6                              |
 cache                    | 16                             |
 tableIncStepPerVnode     | 1000                           |
 minTablesPerVnode        | 1000                           |
 maxTablesPerVnode        | 1000000                        |
 maxVgroupsPerDb          | 0                              |
 streamCompDelayRatio     | 0.100000                       |
 retryStreamCompDelay     | 10000                          |
 maxFirstStreamCompDela   | 10000                          |
 maxStreamCompDelay       | 20000                          |
 minIntervalTime          | 1                              |
 minSlidingTime           | 10                             |
 statusInterval           | 1                              |
 offlineThreshold         | 864000                         |
 maxTmrCtrl               | 512                            |
 balanceInterval          | 300                            |
 balance                  | 1                              |
 telemetryReporting       | 1                              |
 vnodeBak                 | 1                              |
 numOfMnodes              | 1                              |
 maxNumOfDistinctRes      | 10000000                       |
 arbitrator               |                                |
Query OK, 68 row(s) in set (0.001294s)

**Comment by yungchow** [comment]
请问这个问题解决了吗,我们也有遇到同样的报错,我们是2.1.3.2版本

**Comment by yu285** [comment]
> 请问这个问题解决了吗,我们也有遇到同样的报错,使用select first(*) from stable会报错,使用select * from stable正常,我们是2.1.3.2版本

加微信15652223354排查一下吧

**Comment by xiangxud** [comment]
我的重新建表后就好了

**Comment by yu285** [comment]
> 请问这个问题解决了吗,我们也有遇到同样的报错,使用select first(*) from stable会报错,使用select * from stable正常,我们是2.1.3.2版本

可能是自动减表期间，建表操作还没同步完，就发起了写入导致。也有可能是UDP不稳定，导致建表同步失败，这样也会导致出这个问题。所以这是自动减表的一个坏处，在网络不稳的时候，可能会出问题。

所以建议非必要情况下，使用正常减表加普通写入。必要情况下，在配置文件写上rpcforceTcp    1 （建议直接升级到2.4.0.10）  ，从而激活强制TCP通信，更稳定。

**Comment by yu285** [comment]
> 我的重新建表后就好了

可能是自动减表期间，建表操作还没同步完，就发起了写入导致。也有可能是UDP不稳定，导致建表同步失败，这样也会导致出这个问题。所以这是自动减表的一个坏处，在网络不稳的时候，可能会出问题。

所以建议非必要情况下，使用正常减表加普通写入。必要情况下，在配置文件写上rpcforceTcp 1 （建议直接升级到2.4.0.10） ，从而激活强制TCP通信，更稳定。

**Comment by xiangxud** [comment]
好的，谢谢你的专业指导意见

**Comment by yungchow** [comment]
> 

谢谢指导,我们后续升级到最新版本再观察
