### ISSUE TITLE
mgmtCheckMeterLimit() with 2 arguments is not implemented

### ISSUE THREAD

**Issue by xcalibyte-guard** [taosdata/TDengine#828]
**Bug Description**
There are 2 declaration with the same function name mgmtCheckMeterLimit, but the one with 2 arguments is not implemented, but called.
int mgmtCheckMeterLimit(SAcctObj *pAcct, SCreateTableMsg *pCreate);
int mgmtCheckMeterLimit(SAcctObj *pAcct) { return 0; }

**To Reproduce**
1. Go to '.\TDengine-develop\src\system\detail\src\mgmtMeter.c'
2. Type in 'mgmtCheckMeterLimit'
    int mgmtCheckMeterLimit(SAcctObj *pAcct, SCreateTableMsg *pCreate);
    int code = mgmtCheckMeterLimit(pAcct, pCreate);
    BUT mgmtCheckMeterLimit() with 2 arguments is not implemented
3. There is a implement with 1 argument in .\TDengine-develop\src\system\lite\src\mgmtAcct.spec.c
    int mgmtCheckMeterLimit(SAcctObj *pAcct) { return 0; }

**The Result**
the compiler would be OK. However, the runtime may crash.

**Comment by plum-lihui** [comment]
确实有误，应该都是两个参数。我们会修复这个bug。
多谢！
