### ISSUE TITLE
Is there anyone interested in fixing bug in the program, about the create_table error?

### ISSUE THREAD

**Issue by happyguoxy** [taosdata/TDengine#8296]
Bug Description
In table/create.py  The spelling of the word is wrong.

To Reproduce

Go to 'https://github.com/taosdata/TDengine/blob/develop/tests/pytest/table/create.py'
Type in 'os.system("rm -rf table/create1.py.sql")'
See error:os.system("rm -rf table/create.py.sql"). The spelling of the word is wrong,because this script name is create.py. is not create1.py.
Expected Behavior

<img width="482" alt="image" src="https://user-images.githubusercontent.com/66111494/137679675-7786fa6e-a3bb-4e8a-b2b9-8c8ac6c18c52.png">

**Comment by Aries-Lee1991** [comment]
> Please Assign this issue to me, I can try to fix it.

Assigned it to you.
