### ISSUE TITLE
怎么在docker外部使用Connector

### ISSUE THREAD

**Issue by hlh6512500** [taosdata/TDengine#83]
这是我build的docker
<img width="1608" alt="WX20190717-125550@2x" src="https://user-images.githubusercontent.com/25762992/61348314-b95bbf00-a892-11e9-8994-572750f7ae03.png">

当我在docker里，使用golang连接器去链接：localhost 或者127.0.0.1，是可以的
<img width="720" alt="WX20190717-125611@2x" src="https://user-images.githubusercontent.com/25762992/61348400-0a6bb300-a893-11e9-98a7-5cbe25722069.png">

当我在docker里面或者docker外面，使用本机的内网地址去连接taos服务端时却不行了
<img width="793" alt="WX20190717-125702@2x" src="https://user-images.githubusercontent.com/25762992/61348422-2707eb00-a893-11e9-8178-ea214d4daa7f.png">
![image](https://user-images.githubusercontent.com/25762992/61348519-94b41700-a893-11e9-8884-0cb524d5f1da.png)

这是我的配置文件
![image](https://user-images.githubusercontent.com/25762992/61348471-633b4b80-a893-11e9-8d0d-71094ceec882.png)

**Comment by xinqiyang** [comment]
internalIp: 对外提供服务的IP地址，默认取第一个IP地址
mgmtShellPort：管理节点与客户端通信使用的TCP/UDP端口号（默认值是6030）。此端口号在内向后连续的5个端口都会被UDP通信占用，即UDP占用[6030-6034]，同时TCP通信也会使用端口[6030]。
vnodeShellPort：数据节点与客户端通信使用的TCP/UDP端口号（默认值是6035）。此端口号在内向后连续的5个端口都会被UDP通信占用，即UDP占用[6035-6039]，同时TCP通信也会使用端口[6035]


# Internal IP address of the server, which can be acquired by using ifconfig command.
internalIp            52.193.169.241

# client local IP
localIp               52.193.169.241

这里需要用udp 

docker-compose 里面需要连打开udp端口。 

        ports:
            - "6020:6020"
            - "6030:6030/udp"
            - "6031:6031/udp"
            - "6032:6032/udp"
            - "6033:6033/udp"
            - "6034:6034/udp"
            - "6035:6035/udp"
            - "6036:6036/udp"
            - "6037:6037/udp"
            - "6038:6038/udp"
            - "6039:6039/udp"
