### ISSUE TITLE
DB error: Timestamp data out of range

### ISSUE THREAD

**Issue by Wu-Yanjiang** [taosdata/TDengine#8301]
**Bug Description**
DB error: Timestamp data out of range (0.000418s).
 when we create a database use parameters precision "ns" and keep days.

**To Reproduce**
1. CREATE DATABASE locations_ns KEEP 365000 PRECISION "ns";
2. use locations_ns ;
CREATE STABLE traces (
	ts timestamp, 
	local_time bigint
) TAGS (
	plateno nchar(10)
);
3.  INSERT INTO  vtno6666 USING traces TAGS ('no6666') VALUES (1634523381281925000, 1634523381067) ;

**Expected Behavior**
Query OK, 1 of 1 row(s) in database (0.001375s)

**Screenshots**
![b66d62a22abf2df9640724be280e0e2](https://user-images.githubusercontent.com/17618381/137694856-5c77ed3d-d0bb-4a3a-ba24-4e134b848a35.png)

![3627bede78a5f630188d542fbf202dc](https://user-images.githubusercontent.com/17618381/137695109-b362d5ed-4fb6-4559-aca7-7644b8932dc0.png)

**Environment (please complete the following information):**
 - Docker
 - TDengine Version [2.2.1.0]

**Additional Context**

**Promlem Solved**
Replace SQL  <CREATE DATABASE locations_ns KEEP 365000 PRECISION "ns";> parameter 365000 with 3650.

**Comment by yu285** [comment]
请确保时间戳大于当前时间减去keep(参数)天，小于days（参数）天。
