### ISSUE TITLE
6041 didn't work 

### ISSUE THREAD

**Issue by xiaoshuzhagen** [taosdata/TDengine#8337]
systemctl status taosd
● taosd.service - TDengine server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2021-10-20 15:08:33 CST; 48min ago
  Process: 16246 ExecStartPre=/usr/local/taos/bin/startPre.sh (code=exited, status=0/SUCCESS)
 Main PID: 16257 (taosd)
    Tasks: 57
   Memory: 30.1M
   CGroup: /system.slice/taosd.service
           └─16257 /usr/bin/taosd

Oct 20 15:08:33 ecs-29b3 systemd[1]: Starting TDengine server service...
Oct 20 15:08:33 ecs-29b3 systemd[1]: Started TDengine server service.
Oct 20 15:08:33 ecs-29b3 TDengine:[16257]: Starting TDengine service...
Oct 20 15:08:33 ecs-29b3 TDengine:[16257]: Started TDengine service successfully.

netstat -antp|grep 6030
tcp        0      0 0.0.0.0:6030            0.0.0.0:*               LISTEN      16257/taosd
netstat -antp|grep 6041
端口并没有被占用

使用restful：org.apache.http.conn.HttpHostConnectException

**Comment by sangshuduo** [comment]
什么版本？自己编译的吗？

**Comment by xiaoshuzhagen** [comment]
自己编译的6041未生效，使用安装版是没有问题的

**Comment by xiaoshuzhagen** [comment]
> 什么版本？自己编译的吗？

编译的版本端口未生效，后续使用安装版是可以正常使用的

**Comment by sangshuduo** [comment]
> 
> 
> > 什么版本？自己编译的吗？
> 
> 编译的版本端口未生效，后续使用安装版是可以正常使用的

最新代码里引入了一个 blm3 组件提供 RESTful 接口，在 Ubuntu 里 systemctl start taosd 会自动启动 blm3。不用 systemd 需要手动启动。
