### ISSUE TITLE
Who will remove the line of unnecessary code?

### ISSUE THREAD

**Issue by Aries-Lee1991** [taosdata/TDengine#8338]
As shown in line 5098, assigning value from (int32_t)strlen(tablename) to len here, but that stored value is overwritten before it can be used. Who will remove the line of unnecessary code?
![image](https://user-images.githubusercontent.com/48907085/138052419-6eb38c9a-dde8-46be-8d49-b1838eb53e4a.png)

the code is in [src/tscUtil.c](https://github.com/taosdata/TDengine/blame/develop/src/client/src/tscUtil.c)

**Comment by Monstry** [comment]
I can fix this, please assign to me
