### ISSUE TITLE
Using uninitialized value ntoken. Field ntoken.type is uninitialized. It is dangerous.

### ISSUE THREAD

**Issue by wangmm0220** [taosdata/TDengine#8339]
https://github.com/taosdata/TDengine/blob/develop/src/util/src/ttokenizer.c
Value should be initialized for safe in c language for safe.  Because uninitialized value's content is undefined. It is dangerous if use.

![image](https://user-images.githubusercontent.com/6055324/138053813-b51fe001-055e-4a1d-86ef-c4442cbd0728.png)

**Comment by Aries-Lee1991** [comment]
> I can fix this, please assign to me

Sorry, Good first issue is for novices

**Comment by NavneetKumar2907** [comment]
Hey I'm a beginner in the coding world. Can you Guide me I will try to do it.
