### ISSUE TITLE
the string longer than snprintf() sized buffer would cause memory issue

### ISSUE THREAD

**Issue by xcalibyte-guard** [taosdata/TDengine#834]
**Bug Description**
There are issues in format string used in printf/scanf/snprintf... 
Ths would case illegal read of write out of bound or output difference.

The code in question is .\TDengine-develop\src\client\src\tscSQLParser.c

**the declare:**
void getRevisedName(char* resultFieldName, int32_t functionId, int32_t maxLen, char* columnName) {
  snprintf(resultFieldName, maxLen, "%s(%s)", aAggs[functionId].aName, columnName);
}

**The caller is below:**
   getRevisedName(columnName, functionID, TSDB_COL_NAME_LEN, pSchema[pColIndex->columnIndex].name);

In this case, variable columnName is an array with size “TSDB_COL_NAME_LEN”, but pSchema[idx].name is also an array with size “TSDB_COL_NAME_LEN”. 
Also, the second arguments for snprintf() -“maxLen”is also “TSDB_COL_NAME_LEN”, but the snprintf() must assure the last char of maximum resultFieldName is ‘\0’. 
So, whatever aAggs[functionId].aName, it’s most possible to get an error output for resultFieldName.

**Comment by sangshuduo** [comment]
thanks, we will improve our code.
