### ISSUE TITLE
Buffer not null terminated

### ISSUE THREAD

**Issue by wangmm0220** [taosdata/TDengine#8340]
https://github.com/taosdata/TDengine/blob/develop/src/tsdb/src/tsdbFile.c
Calling strncpy with a maximum size argument of 128 bytes on destination array pDFile->f.aname of size 128 bytes might leave the destination string unterminated.

![image](https://user-images.githubusercontent.com/6055324/138057460-1c3ad808-9487-43c8-a9bd-7b5e319191a7.png)

**Comment by Hilbert-Yaa** [comment]
pick up challenge.

**Comment by Aries-Lee1991** [comment]
> pick up challenge.

Assigned it to you.

**Comment by Hilbert-Yaa** [comment]
@Aries-Lee1991 #8651
