### ISSUE TITLE
Buffer not null terminated

### ISSUE THREAD

**Issue by wangmm0220** [taosdata/TDengine#8342]
https://github.com/taosdata/TDengine/blob/develop/src/tsdb/src/tsdbFile.c

Calling strncpy with a maximum size argument of 128 bytes on destination array pMFile->f.aname of size 128 bytes might leave the destination string unterminated.

![image](https://user-images.githubusercontent.com/6055324/138058166-cf2958af-ce09-4f40-b3b3-819dfd54542f.png)

**Comment by whdmailbox** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

assigned it to you.

**Comment by whdmailbox** [comment]
> > pick up challenge
> 
> assigned it to you.

#8342
