### ISSUE TITLE
Division or modulo by float zero

### ISSUE THREAD

**Issue by wangmm0220** [taosdata/TDengine#8346]
https://github.com/taosdata/TDengine/blob/develop/src/query/src/tdigest.c
In expression (idx - weight_so_far) / a->weight, division by expression a->weight which may be zero has undefined behavior.
![image](https://user-images.githubusercontent.com/6055324/138063872-06beebef-f0ce-4c9c-b4bc-e08acb12ff08.png)

**Comment by Aries-Lee1991** [comment]
> Do you want me to add exception handling to this?

Can I assign it to you?

**Comment by mohitsaxenaknoldus** [comment]
> > Do you want me to add exception handling to this?
> 
> Can I assign it to you?

Sure

**Comment by mohitsaxenaknoldus** [comment]
PR: https://github.com/taosdata/TDengine/pull/8376
