### ISSUE TITLE
udp packets would be lost in the communication

### ISSUE THREAD

**Issue by MasonYangD** [taosdata/TDengine#837]
服务器是阿里云centos
终端是win10，宽带：电信光纤
使用sockettype  UDP，客户端丢包严重
使用TCP，客户端无法连接服务器端

急！！！！！！！！！！！！！！！！！！！！！

**Comment by plum-lihui** [comment]
udp的时候丢包严重，是网络的原因，还是taos的原因？ 有初步定位吗？

**Comment by hjxilinx** [comment]
是用sockettype tcp的时候，必须要确保taosd也设置了相同的配置。
```
sockettype tcp
```
需要添加到taosd配置文件中，并重启taosd服务即可。@MasonYangD

**Comment by MasonYangD** [comment]
设置了相同的配置，初步判断是网络原因。为啥其他数据库没有这种情况？

**Comment by robotspace** [comment]
其他数据库也在客户端和服务端的通讯中使用UDP吗？

**Comment by hjxilinx** [comment]
其他数据库是什么意思？ MySQL?  @MasonYangD

**Comment by MasonYangD** [comment]
是这样的，我在公司用的是公司网络，丢包严重，如果我换成另外一个网络，就正常了，我想问的是我需要在公司网络中设置什么才能解决丢包问题。
同时，我用公司网络使用MySQL，Oracle等其他数据库包括其他时序列数据库均为出现该情况。

**Comment by guanshengliang** [comment]
可以试一下TCP网络，就是把客户端所在机器和服务端所在机器的配置项socket均修改为tcp，并重启。但对于丢包问题，不一定TCP或者UDP那个就更好。
如果仍然存在丢包，我们没有更好的办法去解决这样的网络问题，您只能在自己的局域网内，部署服务和编写测试程序。编写完成后，将测试程序放在阿里云机器上运行。通过这种方式，规避网络问题

**Comment by MasonYangD** [comment]
TCP压根就连不上，udp还能连上

**Comment by guanshengliang** [comment]
客户端配置修改了吗？

**Comment by MasonYangD** [comment]
都改了

**Comment by guanshengliang** [comment]
所以，丢包问题目前没有好办法解决。所以请参照上面解决方案：

- 在自己的局域网内，部署服务和编写测试程序
- 编写完成后，将测试程序放在云机器上运行

通过这种方式，规避网络问题
