### ISSUE TITLE
Dockerfile for TDengine

### ISSUE THREAD

**Issue by mohitsaxenaknoldus** [taosdata/TDengine#8375]
**Is your feature request related to a problem? Please describe.**
No

**Describe your desired behavior**
I was thinking to create a Dockerfile for TDengine. If that is ok I can create a PR for the same.

**Describe your solutions/suggestions if you've any**
NA

**Additional context**
None

**Comment by sangshuduo** [comment]
https://github.com/taosdata/TDengine/pull/8390 merged. thanks.
