### ISSUE TITLE
开源单机版本，就不要和hadoop相比

### ISSUE THREAD

**Issue by huangyuandong** [taosdata/TDengine#84]
做不到真正的开源，就不要和hadoop相比，你们还有很长的路要走！

**Comment by xinqiyang** [comment]
能够开源就不错的啊。。。。 

未来还是可能开源cluster版本的，或者可以自己配置cluster版本。
商业公司在国内环境下，能够做到这点，还是很不容易了。 。 


如果 一台机器，能够解决小集群的问题。。。。为啥要cluster呢。
话说楼上的你用过hadoop么， 当你被坑过了之后，你就别说这些话了。

**Comment by huangyuandong** [comment]
作为大数据平台，最基本的cluster看不到，是很难令人信服的。看来你被坑了很多，而且你们的数据量很少，对数据实时性要求不高！

**Comment by chinassx** [comment]
这是国内开源第一步，以后有了cluster server就可以真正对抗Hadoop了。



chinassx@126.com
 
发件人： xinqiyang
发送时间： 2019-07-17 14:01
收件人： taosdata/TDengine
抄送： Subscribed
主题： Re: [taosdata/TDengine] 开源单机版本，就不要和hadoop相比 (#84)
能够开源就不错的啊。。。。
未来还是可能开源cluster版本的，或者可以自己配置cluster版本。
商业公司在国内环境下，能够做到这点，还是很不容易了。 。
如果 一台机器，能够解决小集群的问题。。。。为啥要cluster呢。
话说楼上的你用过hadoop么， 当你被坑过了之后，你就别说这些话了。

**Comment by jtao1735** [comment]
我们昨天已经将集群设计文档公开，请看https://www.taosdata.com/cn/documentation/more-on-system-architecture/#TDengine%E9%9B%86%E7%BE%A4%E8%AE%BE%E8%AE%A1 

等待时机成熟，我们会开源集群版的。现在物联网、车联网、工业互联网领域，绝大部分人是用Hadoop系统处理大数据，TDengine在这个细分领域，是远胜Hadoop. TDengine只会细耕这个领域，只想把物联网大数据做好。

**Comment by crazycarry** [comment]
这个也就给不懂得人吹牛的，何必认真，轻量级别tidb，说的物联网那么玄乎。现在github 也成科普网站了

**Comment by weisunding** [comment]
作者的确要实事求是，单机版的专用写入后只读数据库，无异于自己建了个索引而已，与通用型分布式大数据处理框架没有可比性！请用tdengine对非结构化数据进行map-reduce运算？可行吗，比Hadoop快10倍的软文，偷换概念了！

**Comment by ben-wangz** [comment]
单机数据库，还没有啥索引，读写能不快么……一堆性能测试……只有结论没有“快”的原因解释。
BTW, 软文写得不错

**Comment by jtao1735** [comment]
> 单机数据库，还没有啥索引，读写能不快么……一堆性能测试……只有结论没有“快”的原因解释。
> BTW, 软文写得不错

TDengine是专为物联网场景设计的大数据平台。“快”的原因，请看我们官网taosdata.com文档，里面对数据模型、存储引擎和计算引擎做了详细介绍，欢迎具体的质疑

**Comment by runzhiwang** [comment]
调研了下，有接下来几个结论
1 TDengine优化点：TDengine根据时间和设备对存储做了优化，导致读写速度快：   1.每个设备的数据是独立的，每个设备一张表，根据设备号查询不会去查其他设备的数据；2.再按时间将每个设备的大表分成小表，再将小表按时间分成块，块内数据都是按时间有序，所以可以顺序写，按时间二分查找的读以上两个原因导致TDengine在按时间、设备的查询会很快，但如果查询不是时间、设备作为筛选条件，效率也会低 。而且TDengine的这两种存储上的优化，并不适合其他场景，和hadoop没有可比性。
2．初步比较TDengine和InfluxDB：InfluxDB不会将不同设备的数据分开，TDengine按设备分表是为了保证每个块内的数据都是按时间有序的。如果TDengine不按设备分表，设备A在19:00、19:01产生两条数据，设备B在19:00产生数据，因为网络延迟等，导致设备B的这条数据比设备A的两条数据晚到TDengine，则存储的数据就是：设备A19:00数据、设备A19:01数据、设备B19:00数据，无法保证按时间有序。但TDengine这种按设备分表的假设不知道是否一定成立？如果用户设备很少，但每个设备的数据很多，那就退化成单纯的时序数据库了，这种情况下你们测过TDengine和InfluxDB的性能对比吗？我看了下你们的测试，单表数据都只是几千条。

**Comment by jackyguest** [comment]
确实感觉对场景限制太多了，最好按需等间隔：每分钟或者每小时一组数据，依次写入。
感觉像在做算术题。x1+x2+x3+..+xn 变成了 1+2+3...+100 = (100+1)*50了。

**Comment by caepek** [comment]
其实发帖之人背后是卑劣的贪婪，隔着屏幕都能感到，这个世界从来不缺乏无耻之徒
