### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by huolibo** [taosdata/TDengine#8410]
**Bug Description**
Spelling mistakes

**To Reproduce**
1. Go to 'https://github.com/taosdata/TDengine/blob/develop/src/connector/jdbc/src/main/java/com/taosdata/jdbc/TSDBResultSetWrapper.java'
2. Type in 'implemetation'
3. See error  spell implemetation

**Expected Behavior**
implemetation to implementation

**Comment by clashquest110** [comment]
hii please  asign me in this issue
