### ISSUE TITLE
Operands don't affect result

### ISSUE THREAD

**Issue by wangmm0220** [taosdata/TDengine#8443]
https://github.com/taosdata/TDengine/blob/develop/src/client/src/tscParseInsert.c
iv <= 9223372036854775807L is always true regardless of the values of its operands
![image](https://user-images.githubusercontent.com/6055324/138830720-823a413c-527b-4596-bcef-954e90ae5a80.png)

**Comment by Hilbert-Yaa** [comment]
pick up challenge.

**Comment by Aries-Lee1991** [comment]
@Hilbert-Yaa You have received other tasks：https://github.com/taosdata/TDengine/issues/8340

**Comment by Hilbert-Yaa** [comment]
Got it. Sorry I thought one could accept multiple starter issues lol.

**Comment by Aries-Lee1991** [comment]
> Got it. Sorry I thought one could accept multiple starter issues lol.

Good first issue is for new guys

**Comment by infdahai** [comment]
pick up challenge.

**Comment by softdev1008** [comment]
pick up challenge.

**Comment by Aries-Lee1991** [comment]
> pick up challenge.

Assigned it to you.
