### ISSUE TITLE
Java JDBC query error

### ISSUE THREAD

**Issue by MasonYangD** [taosdata/TDengine#845]
Java：
String sql = "select count(*) from sys_user3 where used='1' and un='admin' and ps='123456'";
Statement statement = conn.createStatement();
ResultSet rs = statement.executeQuery(sql);
rs为空。

服务器下taos
taos> select count(*) from sys_user3 where used='1' and un='admin' and ps='123456';
      count(*)       |
======================
                    1|
Query OK, 1 row(s) in set (0.002038s)

相同的sql，不知道为啥查询结果不一样，taos下查询是对的
注：JDBC是没问题的

**Comment by MasonYangD** [comment]
数据库中
建表语句：create table sys_user2 (time TIMESTAMP,username NCHAR(50),password NCHAR(50),used NCHAR(10));
表中数据：insert into sys_user2 values ('2019-12-02 10:00:00','admin','admin','1');

Java JDBC
sql:  select time,username,password,used from sys_user_2 where username='admin'
返回结果为空
当sql:  select time,username,password,used from sys_user_2 where used='1'
返回结果为1条数据

不知道为什么当where条件不同时，返回结果不同，很神奇，这应该是最基本的

**Comment by hjxilinx** [comment]
`taos` 是在什么操作系统上？Windows还是Linux? JDBC呢？

**Comment by MasonYangD** [comment]
windows

**Comment by xieyinglin** [comment]
你好，按照你给的 sql 语句我这边操作了一下没有出现你描述的情况，还请检查下你的代码。
请注意代码中查询表时指定下 database，比如 select * from test.sys_user2，或者和我测试一样，查询前执行 use test;
![image](https://user-images.githubusercontent.com/41858839/70231727-d9cedc00-1795-11ea-809f-3015608cf4a6.png)

![image](https://user-images.githubusercontent.com/41858839/70231761-ea7f5200-1795-11ea-98c1-21ce088b5307.png)

**Comment by MasonYangD** [comment]
跟你的所有操作均一样，但是返回的count确实为0，测试过多次。

**Comment by xieyinglin** [comment]
可以远程么

**Comment by MasonYangD** [comment]
嗯，我会把相关信息一并整理发过去。
再请教一个问题，如你图中2个sql，执行了2次statement.executeQuery，假如我有n个sql需要一并查询，是否有办法封装成一次executeQuery,而不需要创建n个

**Comment by xieyinglin** [comment]
考虑同时执行多个 sql 返回结果对于目前各种语言接口没有合适的处理方法，所以不能同时查询多个 sql，如果都是查询同一张表只是 where 条件不相同，可以考虑使用 mybatis 这种可以写 if 条件的方式来实现

**Comment by liurongtai** [comment]
问题解决了吗？我野遇到了相同的bug
