### ISSUE TITLE
how to get data?

### ISSUE THREAD

**Issue by zsjlqq** [taosdata/TDengine#8455]
telegraf作为采集器，主要使用Ipmi和snmp相关input插件采集上来的数据，然后output到tdengine数据库，生成下面一堆表格

taos> show tables;
           table_name           |      created_time       | columns |          stable_name           |          uid          |     tid     |    vgId     |
==========================================================================================================================================================
 md5_dda7856434a508ed2e552fc... | 2021-10-27 08:00:42.684 |       2 | snmp                           |      1970327488469798 |         158 |           7 |
 md5_84e31e6a8f6510c13b9d63c... | 2021-10-27 08:01:32.092 |       2 | ipmi_sensor                    |      1970332404269601 |         451 |           7 |
 md5_00b729dc143b5ddb8becb27... | 2021-10-27 08:00:43.315 |       2 | snmp                           |      1970329333991828 |         268 |           7 |
 md5_b793c61c299d9c6984db6be... | 2021-10-27 08:00:42.238 |       2 | snmp                           |      1970326095939838 |          75 |           7 |
 md5_c6894d65bfa2034823ed48e... | 2021-10-27 08:00:42.724 |       2 | snmp                           |      1970327605912158 |         165 |           7 |

taos> describe snmp;
             Field              |         Type         |   Length    |   Note   |
=================================================================================
 ts                             | TIMESTAMP            |           8 |          |
 value                          | DOUBLE               |           8 |          |
 hostname                       | BINARY               |          30 | TAG      |
 interface                      | BINARY               |          30 | TAG      |
 agent_host                     | BINARY               |          30 | TAG      |
 host                           | BINARY               |          30 | TAG      |
 srcip                          | BINARY               |          20 | TAG      |
 field                          | BINARY               |          40 | TAG      |
Query OK, 8 row(s) in set (0.000376s)

taos> describe ipmi_sensor;
             Field              |         Type         |   Length    |   Note   |
=================================================================================
 ts                             | TIMESTAMP            |           8 |          |
 value                          | DOUBLE               |           8 |          |
 host                           | BINARY               |          30 | TAG      |
 name                           | BINARY               |          30 | TAG      |
 server                         | BINARY               |          30 | TAG      |
 status_code                    | BINARY               |          30 | TAG      |
 unit                           | BINARY               |          30 | TAG      |
 entity_id                      | BINARY               |          30 | TAG      |
 status_desc                    | BINARY               |          30 | TAG      |
 srcip                          | BINARY               |          20 | TAG      |
 field                          | BINARY               |          40 | TAG      |
Query OK, 11 row(s) in set (0.000415s)

但是执行select * from snmp什么也没有返回，那怎么获取之前采集的数据？
taos> select * from snmp;
Query OK, 0 row(s) in set (0.040871s)

**Comment by sangshuduo** [comment]
issue resolved.
