### ISSUE TITLE
The limitation of table name

### ISSUE THREAD

**Issue by zhouwenbobo11** [taosdata/TDengine#8464]
表名要求只能用数字、字母和下划线组成，这个规则让我感到很困惑，因为设备的id有纯数字的，也有中划线的，造成了使用的时候需要把表名转换一下，而mysql的表名是不限制纯数字和中划线的。请问表名可以放开这些限制吗，TDengine对表名的这些限制是因为什么呢？

**Comment by yu285** [comment]
新版本已经可以使用下划线转义从而创建数字表
