### ISSUE TITLE
Is there anyone interested in fixing bug in the program, about the operator_cost error? 

### ISSUE THREAD

**Issue by happyguoxy** [taosdata/TDengine#8479]
Bug Description
In table/create.py The spelling of the word is wrong.

To Reproduce

Go to 'https://github.com/taosdata/TDengine/blob/develop/tests/pytest/query/operator_cost.py'

![image](https://user-images.githubusercontent.com/66111494/139254714-0b7fdad4-a95b-41d7-b187-88cafb10f3aa.png)

![image](https://user-images.githubusercontent.com/66111494/139254324-d8cc785e-bcc4-464a-a58f-46a3effb7433.png)
29   #self.ts = int(round(now * 1000))
        self.ts = 1633333333000
        self.num = 10

Expected Behavior
because time.time can cause interval 2 results .  so alter ts to be a fixed value

**Comment by Aries-Lee1991** [comment]
> pick up challenge

how is it going?

**Comment by zhanglianlei** [comment]
yes, I build a test env and reproduce it.
I have a question: alter ts to be a fixed value, is that means self.ts = 1633333333000 ?

**Comment by happyguoxy** [comment]
> yes, I build a test env and reproduce it.
> I have a question: alter ts to be a fixed value, is that means self.ts = 1633333333000 ?

yes, 1633333333000. is ok

**Comment by zhanglianlei** [comment]
ok, I have modified the issue,  I encounters some problems when I build a test env of taos client.

**Comment by zhanglianlei** [comment]
Hi, I need a help, how should I to trigger pipeline and fix the new failed in pullRequest  https://github.com/taosdata/TDengine/pull/8576
