### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by happywzy** [taosdata/TDengine#8492]
1、我的java程序想使用 JDBC-JNI的方式链接数据库，同时我的程序是通过容器部署的，但是根据文档，使用 JDBC-JNI 的 driver，taos-jdbcdriver 驱动包时需要依赖系统对应的本地函数库（Linux 下是 libtaos.so；Windows 下是 taos.dll），那在容器里运行怎么办呢？直接把这个本地函数库拷贝到容器内可以吗？

2、 我的数据上传上去之后发现有问题，可能只是一段时间内的有问题，怎么修正过来？

**Comment by yu285** [comment]
1.https://github.com/taosdata/TDengine/issues/8235
2.如果有这种情况，可以在建库的时候打开update参数为1，后续如果遇到后，可以以相同的时间戳+正确的数据再次插入，即可完成覆盖。
