### ISSUE TITLE
remove ";" in sql strings

### ISSUE THREAD

**Issue by wenzhouwww** [taosdata/TDengine#8493]
the";" in the strings should be remove ,such as follow 

![image](https://user-images.githubusercontent.com/27729854/139409518-73015029-debb-4e97-bb5b-b2ad87269b91.png)

https://github.com/taosdata/TDengine/blob/develop/tests/pytest/dbmgmt/nanoSecondCheck.py

**Comment by Aries-Lee1991** [comment]
Assigned it to you.
