### ISSUE TITLE
建议放出来cluster版本

### ISSUE THREAD

**Issue by zhanglistar** [taosdata/TDengine#85]
共建下这个引擎，感觉还是不错的

**Comment by punisher1** [comment]
@zhanglistar 使用估计可以, 免费是不可能的了

**Comment by jeaken** [comment]
留了一手

**Comment by jtao1735** [comment]
我们昨天已经将集群设计文档公开，请看https://www.taosdata.com/cn/documentation/more-on-system-architecture/#TDengine%E9%9B%86%E7%BE%A4%E8%AE%BE%E8%AE%A1

等待时机成熟，我们会开源集群版的。现在物联网、车联网、工业互联网领域，绝大部分人是用Hadoop系统处理大数据，TDengine在这个细分领域，是远胜Hadoop. TDengine只会细耕这个领域，只想把物联网大数据做好。

我们官网上，马上可以让大家下载企业版，让大家体验，敬请期待。

**Comment by jtao1735** [comment]
> 共建下这个引擎，感觉还是不错的

欢迎在单机版基础上，自己开发一个集群版，我们可以提供支持

**Comment by sangshuduo** [comment]
2.0 版本集群已经开源
