### ISSUE TITLE
Referencing memory after it has been freed can cause a program to crash, use unexpected values, or execute code.

### ISSUE THREAD

**Issue by xcalibyte-guard** [taosdata/TDengine#850]
**Bug Description**
.\TDengine-develop\src\util\src\ttimer.c has:
![image](https://user-images.githubusercontent.com/57699343/70192760-c3923300-1737-11ea-8453-226f308b5291.png)

**timer is free by removeTimer(),but it is reused at tmrTrace. Heap memory is assessed after it has been freed. Use of the original pointer or the memory location is now accessing illegal memory and will cause denial of service or remote execution**

**the code is pasted here for quick reference:**
static bool doStopTimer(tmr_obj_t* timer, uint8_t state) {
  if (state == TIMER_STATE_WAITING) {
    bool reusable = false;
    if (removeFromWheel(timer)) {
      removeTimer(timer->id);
      // only safe to reuse the timer when timer is removed from the wheel.
      // we cannot guarantee the thread safety of the timr in all other cases.
      reusable = true;
    }
    const char* fmt = "%s timer[id=" PRIuPTR ", fp=%p, param=%p] is cancelled.";
    tmrTrace(fmt, timer->ctrl->label, timer->id, timer->fp, timer->param);
    return reusable;
  }

**Comment by localvar** [comment]
This is not a bug, there's reference counting to the timer object and it is safe to access the memory.

**Comment by xcalibyte-guard** [comment]
But you use atomic operation with func atomic_sub_fetch(), it will return subed value not original value. If it's atomic_fetch_sub(), this issue will be safe. If use atomic_sub_fetch, it's also has a possibility on using timer after free.

**Comment by localvar** [comment]
`removeTimer` will only remove the timer from hash map, the timer will not be freed because we still hold a reference.
![image](https://user-images.githubusercontent.com/504447/70312193-1231f100-184e-11ea-8567-a88ffe256b2e.png)
