### ISSUE TITLE
how to migrate datas from mongo to tdeng by dataX?

### ISSUE THREAD

**Issue by t00350320** [taosdata/TDengine#8505]
hi, Zhiyu Yang
I have some quetions to ask you about your migration tool--dataX.
now：  
datax/plugin/reader/mongoreader  is ready  in board A
datax/plugin/writer/tdenginewrite  is ready  in board A 
mongodb collections in board A
tdenginer server in board B

1、your migration tool guide shows a td client is needed, So what about your workflow when migrating from mongodb to tdeng? Do we need a td client and start up in board A ? 
2、for dataX/job/mongo2td.json, the tdwriter's configuration is about td client or td server? 
I found no errors pop up even a tdwriter's host is set 1.1.1.1. So how can I conform the correctness of this migration tool?

**Comment by zyyang-taosdata** [comment]
thanks for your attention
Currently, datax-based migration tools do not support migration of Mongo DB. I only completed development and testing from Opentsdb to TDengine. At the same time, thank you for reminding me in your question. I will improve the above question

**Comment by cmdares** [comment]
可以向这个地方提问，看看作者的回复，https://github.com/wgzhao/Addax/
