### ISSUE TITLE
dereference a null pointer, thereby causing a segmentation fault

### ISSUE THREAD

**Issue by xcalibyte-guard** [taosdata/TDengine#851]
**Bug Description**
Dereference a null pointer, thereby causing a segmentation fault. 

**the source file is src\client\src\tscAsync.c**
![image](https://user-images.githubusercontent.com/57699343/70193147-39e36500-1739-11ea-920e-38e359c2f968.png)

**The code pasted here for quick reference.**
static void tscProcessAsyncRetrieveImpl(void *param, TAOS_RES *tres, int numOfRows, void (*fp)()) {
  SSqlObj *pSql = (SSqlObj *)tres;
  if (pSql == NULL) {  // error
    tscError("sql object is NULL");
    tscQueueAsyncError(pSql->fetchFp, param);
    return;
  }

**Comment by fangpanpan** [comment]
We will solve this problem in the pull request #866
