### ISSUE TITLE
readme url error

### ISSUE THREAD

**Issue by huolibo** [taosdata/TDengine#8514]
**Bug Description**
url path error

**To Reproduce**
1. Go to 'https://github.com/taosdata/TDengine/blob/develop/tests/examples/JDBC/readme.md'
2. Type in 'more detail'
3. https://www.taosdata.com/cn//documentation20/connector-java/

**Expected Behavior**
https://www.taosdata.com/cn/documentation20/connector/java

**Comment by gracenn1998** [comment]
Could you please assign this to me?

**Comment by Aries-Lee1991** [comment]
> Could you please assign this to me?

Assigned it to you.

**Comment by gracenn1998** [comment]
I have had the PR for fixing it but the Jenkin CI Build got fail? May I get more instruction how to deal with it?
