### ISSUE TITLE
docker 容器里面时区不对

### ISSUE THREAD

**Issue by xuejiazhi** [taosdata/TDengine#8519]
#### 宿主机
root:#/date –R
Mon ,01 Nov 2021 17:23:36 +0800

使用官方的镜像
### 容器内
root: Tdengine-server-2.0.18 #/date –R
Mon ,01 Nov 2021 09:23:36 +0800

两个时区不一致，是否设定tdengine容器的镜像。

**Comment by yu285** [comment]
problem resolved in wechat group
