### ISSUE TITLE
not handle standard library errors

### ISSUE THREAD

**Issue by xcalibyte-guard** [taosdata/TDengine#852]
**Bug Description**
Find several bugs not handling standard library errors. 

1. the source code is  src/client/src/tscProfile.c : 98
     char *sql = malloc(200);  
    ##potential risk: the return value may be NULL

2. the source code is src/client/src/tscProfile.c : 100
    int   len = snprintf(sql, 200, "insert into %s.slowquery values(now, '%s', %lld, %lld, '", tsMonitorDbName,
          pSql->pTscObj->user, pSql->stime, pSql->res.useconds);
   ##potential risk: the return value may be Negative

reference: https://wiki.sei.cmu.edu/confluence/display/c/ERR33-C.+Detect+and+handle+standard+library+errors

**Comment by plum-lihui** [comment]
1、有部分很小内存块的申请没有进行检查保护，后续会修改完成；
2、snprintf的结果也是需要进行检查，后续完成；
