### ISSUE TITLE
Is there anyone interested in fixing bug in the program, about the special_character_show error?

### ISSUE THREAD

**Issue by happyguoxy** [taosdata/TDengine#8528]
Bug Description
In insert/special_character_show.py The spelling of the word should use English,not  Chinese,.

To Reproduce

Go to 'https://github.com/taosdata/TDengine/blob/develop/tests/pytest/insert/special_character_show.py'

![image](https://user-images.githubusercontent.com/66111494/139776121-81891ace-ee4a-4138-85ae-f36a8c1a8749.png)

Expected Behavior
Test py Script should use English,not  Chinese。so should change！！

**Comment by tradercjz** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

assigned it to you.

**Comment by tradercjz** [comment]
[https://github.com/taosdata/TDengine/pull/8550](url)

**Comment by tradercjz** [comment]
[[Issue#8528] translate Chinese inito English](https://github.com/taosdata/TDengine/pull/8550)

**Comment by tradercjz** [comment]
#8550

**Comment by Aries-Lee1991** [comment]
@tradercjz how is it going?

**Comment by tradercjz** [comment]
@Aries-Lee1991 #8850

**Comment by tradercjz** [comment]
@Aries-Lee1991 [#8850](https://github.com/taosdata/TDengine/pull/8550)
