### ISSUE TITLE
would you plan to upgrade the python driver?

### ISSUE THREAD

**Issue by saiyn** [taosdata/TDengine#853]
python接口query不支持params就算了，不支持fetchone()也算了，但是fetchall()的结果没有fileds信息好难用啊，fetchall()结果可以是字典列表而不是现在的元组列表吗？或者元组列表第一个是fileds元组也可以？

还有就是社区版本的python接口如此简陋有完善计划吗？还是说可以接收PR？

企业版的python接口是一样的简陋吗？还是比较完善？

**Comment by fangpanpan** [comment]
cursor.descriptions 立刻获取fields 的信息。 目前我们短期研发计划里还没有进一步完善python接口的打算，如果您有兴趣的话，也可以成为contributor.

**Comment by saiyn** [comment]
ok, thank you for your quick response
