### ISSUE TITLE
spelling mistake in source code

### ISSUE THREAD

**Issue by xleili** [taosdata/TDengine#8564]
There are some spelling mistake in our source code, could some help to fix this and submit a pr.
position:
1:https://github.com/taosdata/TDengine/blob/develop/tests/test/c/createNormalTable.c  line 236 , word "performace"
2.https://github.com/taosdata/TDengine/blob/develop/tests/test/c/createTablePerformance.c line 224, word "performace"

Remember to assign me to review your PR. Thanks.

**Comment by chien-b1812825** [comment]
what I need to do is find this word and change it to the correct word, right ?

**Comment by xleili** [comment]
> what I need to do is find this word and change it to the correct word, right ?

yeah, find the correct word and fix it.

**Comment by xleili** [comment]
> > what I need to do is find this word and change it to the correct word, right ?
> 
> yeah, find the correct word and fix it.

would you like to fix this?  I can assign it to you.

**Comment by chien-b1812825** [comment]
I have done it
https://github.com/taosdata/TDengine/pull/8577
