### ISSUE TITLE
两个Mnode集群中，master挂掉后，集群就无法连接了

### ISSUE THREAD

**Issue by DarkGodOne** [taosdata/TDengine#8567]
我在测试集群高可用的时候，遇到了问题，配置了numOfMnodes为2，但是当master节点宕机后，slave节点并没有升级为master，导致集群无法连接以及使用。
集群：TD1,TD2,TD3
![image](https://user-images.githubusercontent.com/12151282/140252129-651f9c43-5200-4f4c-ae1a-c3a81feb387d.png)
这时集群功能正常，停到一个非mnode的节点，集群仍然可以正常使用
但是当我把TD1.zoolon关闭后，就无法连接了
![image](https://user-images.githubusercontent.com/12151282/140252265-9efa6f64-5799-4107-a078-c7ddaf0ba871.png)
麻烦解答下，是还需要在哪里配置什么么？？

**Comment by DarkGodOne** [comment]
找到解决方法了，是少部署了一个Arbitrator，在只有一个mnode的时候是不能自己选举的，所以需要依赖这个服务，启动一个这个服务就可以解决了

**Comment by yu285** [comment]
如果只挂掉slave是没问题的，但是挂了master就不行了，因为没法选主

**Comment by zjpChina** [comment]
> 找到解决方法了，是少部署了一个Arbitrator，在只有一个mnode的时候是不能自己选举的，所以需要依赖这个服务，启动一个这个服务就可以解决了

为什么我布了Arbitrator也不行，好奇怪
