### ISSUE TITLE
Debian执行install.sh失败

### ISSUE THREAD

**Issue by ddyanhui** [taosdata/TDengine#86]
Debian执行install.sh失败
另外，是不是免费的只有单机版？免费不能提供集群？

**Comment by hjxilinx** [comment]
请提供一下执行失败的错误信息。开源的版本暂时不支持集群服务。

**Comment by ddyanhui** [comment]
debian默认没有sudo命令，所以install.sh里的sudo相关命令都执行错误。
如果开源版本不支持集群服务，那就没必要测试了。

**Comment by hzcheng** [comment]
非常感谢关注，目前我们只开源单机版也是有所考虑的，我们也正在考虑集群版本的开源。我们也需要时间来完善产品，有不完美的地方敬请谅解。
