### ISSUE TITLE
when using bigint for tag， some error happend

### ISSUE THREAD

**Issue by elvin2012** [taosdata/TDengine#8611]
**Bug Description**
tags使用bigint时出现混乱

**To Reproduce**
create stable md(ts timestamp, time timestamp, dkey nchar(20), value double) tags(deviceId bigint);
create table m1428197792135909376 using md tags(1428197792135909376);
create table m1456060315241418752 using md tags(1456060315241418752);
create table m1456060315241418753 using md tags(1456060315241418753);
create table m1456060315241418754 using md tags(1456060315241418754);
create table m1456060315241418755 using md tags(1456060315241418755);
create table m1456060315241418756 using md tags(1456060315241418756);
create table m1456060315241418757 using md tags(1456060315241418757);
create table m1456060315245613056 using md tags(1456060315245613056);
create table m1456060315245613057 using md tags(1456060315245613057);
create table m1456060315245613058 using md tags(1456060315245613058);
create table m1456060315245613059 using md tags(1456060315245613059);

**Expected Behavior**
执行sql: select distinct TBNAME, deviceId from md;
出现以下结果:
{ "res": true, "count": 11, "data": [ { "tbname": "m1428197792135909376", "deviceid": 1428197792135909400 }, { "tbname": "m1456060315241418752", "deviceid": 1456060315241418800 }, { "tbname": "m1456060315241418753", "deviceid": 1456060315241418800 }, { "tbname": "m1456060315241418754", "deviceid": 1456060315241418800 }, { "tbname": "m1456060315241418755", "deviceid": 1456060315241418800 }, { "tbname": "m1456060315241418756", "deviceid": 1456060315241418800 }, { "tbname": "m1456060315241418757", "deviceid": 1456060315241418800 }, { "tbname": "m1456060315245613056", "deviceid": 1456060315245613000 }, { "tbname": "m1456060315245613057", "deviceid": 1456060315245613000 }, { "tbname": "m1456060315245613058", "deviceid": 1456060315245613000 }, { "tbname": "m1456060315245613059", "deviceid": 1456060315245613000 } ] }
deviceId出现了很多重复

**Environment (please complete the following information):**
 - OS: [ubuntu20]
 - Memory, CPU, current Disk Space
 - TDengine Version [2.2.1.3]

**Comment by yu285** [comment]
哪里出现重复的设备id，能标注一下吗
