### ISSUE TITLE
An error occurred while inserting data

### ISSUE THREAD

**Issue by Allenscript** [taosdata/TDengine#862]
在硬件为AM335X  ARM板
Ubuntu 12.04   
gcc  4.8.3 
编译通过，但数据插入方式仅支持一种，这是否为一个bug？
具体现象如下
在插入数据时，忽略column 名字进行插入就没办法插入，加入column就可以，如下图
数据表只有ts和一个int类型的变量做测试

![TD——arm](https://user-images.githubusercontent.com/18085456/70293949-dcc0df80-181c-11ea-88c1-7a73a0064fd5.png)

**Comment by Allenscript** [comment]
图挂了，我把终端内容贴上来
taos> 
taos> insert into ddd("2019-02-10 00:00:00",2);
DB error: invalid SQL: syntax error near "2019-02-10 00:00:00" (invalid column name)

taos> insert into ddd(ts,a) values("2019-02-10 00:00:00",2);
Query OK, 0 row(s) affected (0.004242s)
taos>

**Comment by Allenscript** [comment]
table_name                 |     created_time           |    columns   |                             stable                             |
ddd                             | 19-12-06 11:05:57.404|      2             |                                                                |
dd                               | 19-12-06 11:03:06.291|      4             |

**Comment by plum-lihui** [comment]
insert into ddd("2019-02-10 00:00:00",2);  这句语法错了，少了关键字 values，正确语句如下：
 insert into ddd values ("2019-02-10 00:00:00",2);

**Comment by plum-lihui** [comment]
您的arm板是32位的，还是64的位？ ubuntu 12.04 用的是32位版本还是64位版本？

**Comment by Allenscript** [comment]
好的，Thanks♪(･ω･)ﾉ
我使用的是32位的芯片+32位的系统
