### ISSUE TITLE
restful insertion encounter ：“Unable to establish connection”

### ISSUE THREAD

**Issue by YuMiaoPy** [taosdata/TDengine#8623]
部署类型：单节点
版本号：2.0.20.13
restful方式连续插入3、4个小时后，会出现Unable to establish connection：
{"status":"error","code":11,"desc":"Unable to establish connection"}
**此时通过restful执行查询操作也失效，如果重启一下td，那么立刻完成恢复正常**（restful插入+查询）

但是奇怪的时，报错问题出现在生产现场的虚拟机中，如果在阿里云服务器上部署相同tdengine，进行相同的restful插入，阿里云则一直不会出问题。
想咨询一下，服务器设置方面是否会影响restful插入？关键日志如附件
[log.zip](https://github.com/taosdata/TDengine/files/7503044/log.zip)
td配置如下：
[taos.cfg.zip](https://github.com/taosdata/TDengine/files/7503047/taos.cfg.zip)

**Comment by YuMiaoPy** [comment]
linux内核版本：3.10.0
操作系统：centOS7.6
内存：20G

**Comment by YuMiaoPy** [comment]
cpu：12核

**Comment by YuMiaoPy** [comment]
补充一点，restful报错后，仅仅是restful模块异常，taos命令行仍然可以正常执行insert、select等所有sql语句

**Comment by yu285** [comment]
可以添加微信15652223354 做问题排查
