### ISSUE TITLE
tdengine慢查询

### ISSUE THREAD

**Issue by zdx999** [taosdata/TDengine#8653]
![image](https://user-images.githubusercontent.com/32765740/141231847-fd926944-e55a-403c-b6ca-0d9cbd52bb90.png)
2.2的 linux rpm 包。rpm -ir  然后systemctl start taosd   一切都没变。然后taos进入就需要将近50s，后面使用起来查询就更不用说了，一个查询1分钟。已经发现2个现场出现这种情况了。

**Comment by zdx999** [comment]
![image](https://user-images.githubusercontent.com/32765740/141232210-f851c2f7-c907-4b6c-be81-89a0d43aa8c2.png)

**Comment by zdx999** [comment]
![image](https://user-images.githubusercontent.com/32765740/141235941-bce7098b-39db-40bb-9b12-423b8324eb6b.png)

空表20ss

**Comment by zdx999** [comment]
![image](https://user-images.githubusercontent.com/32765740/141236245-80699361-55e8-44f7-87b7-8d0eecf44a83.png)

**Comment by yu285** [comment]
请添加微信15652223354做具体排查

**Comment by zdx999** [comment]
![image](https://user-images.githubusercontent.com/32765740/141247490-ce3ab472-fc95-4cd3-830b-156794f604d4.png)

**Comment by yu285** [comment]
问题已经排查并解决
