### ISSUE TITLE
remove mark in code for jira link ,only save serial number

### ISSUE THREAD

**Issue by wenzhouwww** [taosdata/TDengine#8659]
https://github.com/taosdata/TDengine/blob/develop/tests/pytest/query/sliding.py

remove # Fix defect: https://jira.taosdata.com:18080/browse/TD-2700  , and only reserve TD-2700

**Comment by WellJay** [comment]
Please assign to me;

**Comment by Aries-Lee1991** [comment]
> Please assign to me;

**Comment by WellJay** [comment]
Thx. new pull request #8684
