### ISSUE TITLE
Encapsulate the same execution process into a function as follow 

### ISSUE THREAD

**Issue by wenzhouwww** [taosdata/TDengine#8660]
https://github.com/taosdata/TDengine/blob/develop/tests/examples/nodejs/node-example-raw.js

try {
  c1.execute('create database if not exists db;');
}
catch(err) {
  conn.close();
  throw err;
}

// Now we will use database db
try {
  c1.execute('use db;');
}
catch (err) {
  conn.close();
  throw err;
}

// Let's create a table called weather
// which stores some weather data like humidity, AQI (air quality index), temperature, and some notes as text
try {
  c1.execute('create table if not exists weather (ts timestamp, humidity smallint, aqi int, temperature float, notes binary(30));');
}
catch (err) {
  conn.close();
  throw err;
}

// Let's get the description of the table weather
try {
  c1.execute('describe db.weather');
}
catch (err) {
  conn.close();
  throw err;
}

above code should be encapsulate as an function

**Comment by WellJay** [comment]
can you assign it to me?

**Comment by Aries-Lee1991** [comment]
> can you assign it to me?

Assigned it to you.

**Comment by WellJay** [comment]
#8671
 New pull request
