### ISSUE TITLE
importing from csv file with 6 Million records failed

### ISSUE THREAD

**Issue by vibhubithar** [taosdata/TDengine#8676]
**Bug Description**
I am transferring data from an edge node to central node and there are about 6.5 M rows of data

**To Reproduce**
1. export data from a table to csv file
2. import csv file into a table
3. See error : taos> insert into upboardberry2 file 'databackup_upboardberry1_081621-111221.csv';
taos: /home/ubuntu/workroom/jenkins/TDinternal/community/src/client/src/tscUtil.c:2073: tscMergeTableDataBlocks: Assertion `finalLen <= len' failed.
Aborted (core dumped)

**Expected Behavior**
data import finished with rows entered

**Screenshots**

**Environment (please complete the following information):**
 - OS: ubuntu 20.04
 - Memory, CPU, current Disk Space
 - TDengine Version  2.1.6.0 

**Additional Context**
I tried the same process with 2.5 Million records and it worded fine but when trying with 6 Million records its failing

**Comment by yu285** [comment]
可以加微信15652223354做具体排查

**Comment by yu285** [comment]
we will check on this，could u provide the create table SQL，and the csv file to us？we need to reproduce it

**Comment by boxiaobj** [comment]
This bug has been resolved and suggest upgrade to 2.2.0.2 or above to fix this issue.

**Comment by vibhubithar** [comment]
thanks after installing the new version i was able to import all 6M rows of data in 38sec :)
