### ISSUE TITLE
ubuntu20.04 Ali Cloud， error:Unable to establish connection

### ISSUE THREAD

**Issue by famlee** [taosdata/TDengine#8677]
1、系统ubuntu20.04 
2、修改hosts ，可以ping通
3、deb文件包安装，systemctl status taosd 显示运行。
4、taos报错。error:Unable to establish connection

另外：安全组规则已经配置tcp udp都可以访问。

日志中taosinfo.0报错部分如下：

11/13 16:05:07.657353 00000625 DND step:dnode-telemetry is initialized
11/13 16:05:07.662541 00000625 DND step:dnode-script is initialized
11/13 16:05:07.662567 00000625 DND TDengine is initialized successfully
11/13 16:05:11.155669 00000636 UTL ERROR failed to connect socket, ip:0x8e170000, port:6035(poll error/conn timeout)
11/13 16:05:11.155751 00000636 RPC ERROR failed to connect to:0x8e170000:6035
11/13 16:05:11.155813 00000636 RPC ERROR DND-C (nil), failed to set up connection(Unable to establish connection)
11/13 16:05:14.167921 00000655 UTL ERROR failed to connect socket, ip:0x8e170000, port:6035(poll error/conn timeout)
11/13 16:05:14.168003 00000655 RPC ERROR failed to connect to:0x8e170000:6035
11/13 16:05:14.168015 00000655 RPC ERROR DND-C (nil), failed to set up connection(Unable to establish connection)
11/13 16:05:17.176205 00000655 UTL ERROR failed to connect socket, ip:0x8e170000, port:6035(poll error/conn timeout)
11/13 16:05:17.176322 00000655 RPC ERROR failed to connect to:0x8e170000:6035
11/13 16:05:17.176340 00000655 RPC ERROR DND-C (nil), failed to set up connection(Unable to establish connection)
11/13 16:05:20.185735 00000655 UTL ERROR failed to connect socket, ip:0x8e170000, port:6035(poll error/conn timeout)
11/13 16:05:20.185833 00000655 RPC ERROR failed to connect to:0x8e170000:6035
11/13 16:05:20.185852 00000655 RPC ERROR DND-C (nil), failed to set up connection(Unable to establish connection)
11/13 16:05:23.195509 00000655 UTL ERROR failed to connect socket, ip:0x8e170000, port:6035(poll error/conn timeout)
11/13 16:05:23.195625 00000655 RPC ERROR failed to connect to:0x8e170000:6035
11/13 16:05:23.195643 00000655 RPC ERROR DND-C (nil), failed to set up connection(Unable to establish connection)
11/13 16:05:26.200608 00000655 UTL ERROR failed to connect socket, ip:0x8e170000, port:6035(poll error/conn timeout)
11/13 16:05:26.200667 00000655 RPC ERROR failed to connect to:0x8e170000:6035
11/13 16:05:26.200677 00000655 RPC ERROR DND-C (nil), failed to set up connection(Unable to establish connection)
11/13 16:05:26.203518 00000655 RPC WARN DND-C 0x7f6122c36300 (nil), too many redirects, quit
11/13 16:05:26.203536 00000655 DND minfos is changed, numOfEps:2 inUse:1
11/13 16:05:26.203540 00000655 DND minfo:0 6030:6030
11/13 16:05:26.203543 00000655 DND minfo:1 td1:6030
11/13 16:05:26.203547 00000655 DND ERROR status rsp is received, error:Unable to establish connection
11/13 16:05:30.130498 00000655 UTL ERROR failed to connect socket, ip:0x8e170000, port:6035(poll error/conn timeout)
11/13 16:05:30.130591 00000655 RPC ERROR failed to connect to:0x8e170000:6035
11/13 16:05:30.130622 00000655 RPC ERROR DND-C (nil), failed to set up connection(Unable to establish connection)
11/13 16:05:33.140422 00000655 UTL ERROR failed to connect socket, ip:0x8e170000, port:6035(poll error/conn timeout)
11/13 16:05:33.140504 00000655 RPC ERROR failed to connect to:0x8e170000:6035
11/13 16:05:33.140515 00000655 RPC ERROR DND-C (nil), failed to set up connection(Unable to establish connection)
11/13 16:05:36.151735 00000655 UTL ERROR failed to connect socket, ip:0x8e170000, port:6035(poll error/conn timeout)
11/13 16:05:36.152597 00000655 RPC ERROR failed to connect to:0x8e170000:6035
11/13 16:05:36.152615 00000655 RPC ERROR DND-C (nil), failed to set up connection(Unable to establish connection)
11/13 16:05:39.160782 00000655 UTL ERROR failed to connect socket, ip:0x8e170000, port:6035(poll error/conn timeout)
11/13 16:05:39.160871 00000655 RPC ERROR failed to connect to:0x8e170000:6035
11/13 16:05:39.160886 00000655 RPC ERROR DND-C (nil), failed to set up connection(Unable to establish connection)
11/13 16:05:39.998667 00000656 RPC WARN DND-C 0x7f6122c37038 (nil), too many redirects, quit
11/13 16:05:39.998725 00000681 DND ERROR user:root, auth msg received from mnodes, error:Unable to establish connection
11/13 16:05:42.166299 00000655 UTL ERROR failed to connect socket, ip:0x8e170000, port:6035(poll error/conn timeout)
11/13 16:05:42.166371 00000655 RPC ERROR failed to connect to:0x8e170000:6035
11/13 16:05:42.166382 00000655 RPC ERROR DND-C (nil), failed to set up connection(Unable to establish connection)
11/13 16:05:42.173578 00000655 RPC WARN DND-C 0x7f6122c36300 (nil), too many redirects, quit
11/13 16:05:42.173602 00000655 DND minfos is changed, numOfEps:2 inUse:1
11/13 16:05:42.173606 00000655 DND minfo:0 6030:6030
11/13 16:05:42.173609 00000655 DND minfo:1 td1:6030
11/13 16:05:42.173613 00000655 DND ERROR status rsp is received, error:Unable to establish connection
11/13 16:05:45.628621 00000656 RPC WARN DND-C 0x7f6122c37038 (nil), too many redirects, quit
11/13 16:05:45.628670 00000681 DND ERROR user:root, auth msg received from mnodes, error:Unable to establish connection
11/13 16:05:46.101145 00000655 UTL ERROR failed to connect socket, ip:0x8e170000, port:6035(poll error/conn timeout)
11/13 16:05:46.101216 00000655 RPC ERROR failed to connect to:0x8e170000:6035
11/13 16:05:46.101235 00000655 RPC ERROR DND-C (nil), failed to set up connection(Unable to establish connection)
11/13 16:05:49.106657 00000655 UTL ERROR failed to connect socket, ip:0x8e170000, port:6035(poll error/conn timeout)
11/13 16:05:49.106730 00000655 RPC ERROR failed to connect to:0x8e170000:6035
11/13 16:05:49.106741 00000655 RPC ERROR DND-C (nil), failed to set up connection(Unable to establish connection)
11/13 16:05:51.248695 00000656 RPC WARN DND-C 0x7f6122c37038 (nil), too many redirects, quit
11/13 16:05:51.248746 00000681 DND ERROR user:root, auth msg received from mnodes, error:Unable to establish connection
11/13 16:05:52.110789 00000655 UTL ERROR failed to connect socket, ip:0x8e170000, port:6035(poll error/conn timeout)
11/13 16:05:52.110881 00000655 RPC ERROR failed to connect to:0x8e170000:6035
11/13 16:05:52.110907 00000655 RPC ERROR DND-C (nil), failed to set up connection(Unable to establish connection)
11/13 16:05:55.115592 00000655 UTL ERROR failed to connect socket, ip:0x8e170000, port:6035(poll error/conn timeout)
11/13 16:05:55.115675 00000655 RPC ERROR failed to connect to:0x8e170000:6035
11/13 16:05:55.115688 00000655 RPC ERROR DND-C (nil), failed to set up connection(Unable to establish connection)
11/13 16:05:56.938815 00000656 RPC WARN DND-C 0x7f6122c37038 (nil), too many redirects, quit
11/13 16:05:56.938884 00000681 DND ERROR user:root, auth msg received from mnodes, error:Unable to establish connection
11/13 16:05:58.120895 00000655 UTL ERROR failed to connect socket, ip:0x8e170000, port:6035(poll error/conn timeout)
11/13 16:05:58.120977 00000655 RPC ERROR failed to connect to:0x8e170000:6035
11/13 16:05:58.120989 00000655 RPC ERROR DND-C (nil), failed to set up connection(Unable to establish connection)
11/13 16:05:58.123656 00000655 RPC WARN DND-C 0x7f6122c36300 (nil), too many redirects, quit
11/13 16:05:58.123674 00000655 DND minfos is changed, numOfEps:2 inUse:1
11/13 16:05:58.123678 00000655 DND minfo:0 6030:6030
11/13 16:05:58.123682 00000655 DND minfo:1 td1:6030
11/13 16:05:58.123686 00000655 DND ERROR status rsp is received, error:Unable to establish connection
11/13 16:06:02.136239 00000655 UTL ERROR failed to connect socket, ip:0x8e170000, port:6035(poll error/conn timeout)
11/13 16:06:02.136322 00000655 RPC ERROR failed to connect to:0x8e170000:6035
11/13 16:06:02.136335 00000655 RPC ERROR DND-C (nil), failed to set up connection(Unable to establish connection)
11/13 16:06:05.140918 00000655 UTL ERROR failed to connect socket, ip:0x8e170000, port:6035(poll error/conn timeout)
11/13 16:06:05.141058 00000655 RPC ERROR failed to connect to:0x8e170000:6035
11/13 16:06:05.141076 00000655 RPC ERROR DND-C (nil), failed to set up connection(Unable to establish connection)
11/13 16:06:08.151254 00000655 UTL ERROR failed to connect socket, ip:0x8e170000, port:6035(poll error/conn timeout)
11/13 16:06:08.151327 00000655 RPC ERROR failed to connect to:0x8e170000:6035
11/13 16:06:08.151338 00000655 RPC ERROR DND-C (nil), failed to set up connection(Unable to establish connection)
11/13 16:06:11.161218 00000655 UTL ERROR failed to connect socket, ip:0x8e170000, port:6035(poll error/conn timeout)
11/13 16:06:11.161269 00000655 RPC ERROR failed to connect to:0x8e170000:6035
11/13 16:06:11.161280 00000655 RPC ERROR DND-C (nil), failed to set up connection(Unable to establish connection)
11/13 16:06:14.171673 00000655 UTL ERROR failed to connect socket, ip:0x8e170000, port:6035(poll error/conn timeout)
11/13 16:06:14.171764 00000655 RPC ERROR failed to connect to:0x8e170000:6035
11/13 16:06:14.171778 00000655 RPC ERROR DND-C (nil), failed to set up connection(Unable to establish connection)
11/13 16:06:14.178625 00000655 RPC WARN DND-C 0x7f6122c36300 (nil), too many redirects, quit
11/13 16:06:14.178653 00000655 DND minfos is changed, numOfEps:2 inUse:1
11/13 16:06:14.178657 00000655 DND minfo:0 6030:6030
11/13 16:06:14.178660 00000655 DND minfo:1 td1:6030
11/13 16:06:14.178668 00000655 DND ERROR status rsp is received, error:Unable to establish connection

**Comment by famlee** [comment]
补充：另外两个日志文件运行显示正常。初步怀疑IP地址部分有问题，ip:0x8e170000。

**Comment by yu285** [comment]
请添加微信15652223354做具体排查

**Comment by yu285** [comment]
问题解决，做关闭处理

**Comment by GLTSC** [comment]
怎么都是添加微信解决？不分享出来解决办法呢？
