### ISSUE TITLE
taos connect failed, reason: Unable to establish connection

### ISSUE THREAD

**Issue by SCY-ICT** [taosdata/TDengine#8680]
**Bug Description**
docker 安装taos2.2.0.2，插入一定数据以后，进taos命令行，提示

taos connect failed, reason: Unable to establish connection

日志文件中

11/10 07:06:14.888049 00000617 TDB ERROR vgId:4 failed to get table to insert data, uid 1125914302175011 tid 858
11/10 07:06:14.888078 00000617 TDB ERROR vgId:4 failed to insert data since Invalid table ID
11/10 07:06:14.888082 00000616 TDB ERROR vgId:3 failed to get table to insert data, uid 844440449298511 tid 925
11/10 07:06:14.888112 00000616 TDB ERROR vgId:3 failed to insert data since Invalid table ID
11/10 07:06:17.358092 00000023 MND msg:0x7f4e400057f0, app:0x4f9e vgId:8, is created in mnode, db:0.gc_dynamic_data replica:1
11/10 07:06:17.358133 00000023 MND msg:0x7f4e400057f0, app:0x4f9e vgId:8, index:0, dnode:1
11/10 07:06:17.358793 00000017 VND vgId:8, successed to write /var/lib/taos/vnode/vnode8/config.json
11/10 07:06:17.359070 00000017 VND vgId:8, vnode dir is created, walLevel:1 fsyncPeriod:3000
11/10 07:06:17.359227 00000017 VND vgId:8, load vnode cfg successfully, replcia:1
11/10 07:06:17.359242 00000017 VND vgId:8, dnode:1, node1:7040
11/10 07:06:17.359932 00000017 TDB vgId:8 try to restore meta
11/10 07:06:17.360011 00000017 TDB vgId:8 no meta file is restored
11/10 07:06:17.361441 00000017 VND vgId:8, sync role changed from offline to master
11/10 07:06:17.361467 00000017 DND force send status msg to mnode
11/10 07:06:17.361482 00000017 QRY vgId:8, set querymgmt reopen
11/10 07:06:17.361951 00000030 MND msg:0x7f4e400057f0, app:0x4f9e vgId:8, is created in sdb, db:0.gc_dynamic_data replica:1
11/10 07:06:17.564660 00000616 TDB ERROR vgId:3 failed to get table to insert data, uid 844425836120331 tid 54
11/10 07:06:17.564693 00000616 TDB ERROR vgId:3 failed to insert data since Invalid table ID
11/10 07:06:17.564690 00000617 TDB ERROR vgId:4 failed to get table to insert data, uid 1125905024233052 tid 305
11/10 07:06:17.564720 00000617 TDB ERROR vgId:4 failed to insert data since Invalid table ID
11/10 07:06:18.983592 00000617 TDB ERROR vgId:4 failed to get table to insert data, uid 1125903262598491 tid 200
11/10 07:06:18.983578 00000616 TDB ERROR vgId:3 failed to get table to insert data, uid 844425836120331 tid 54
11/10 07:06:18.983642 00000617 TDB ERROR vgId:4 failed to insert data since Invalid table ID
11/10 07:06:18.983651 00000616 TDB ERROR vgId:3 failed to insert data since Invalid table ID
11/10 07:06:21.366677 00000616 TDB ERROR vgId:3 failed to get table to insert data, uid 844433553757580 tid 514
11/10 07:06:21.366711 00000616 TDB ERROR vgId:3 failed to insert data since Invalid table ID
11/10 07:06:22.004303 00000617 TDB ERROR vgId:4 failed to get table to insert data, uid 1125905997326340 tid 363
11/10 07:06:22.004335 00000617 TDB ERROR vgId:4 failed to insert data since Invalid table ID
11/10 07:06:22.004350 00000618 TDB ERROR vgId:5 failed to get table to insert data, uid 1407389262364702 tid 857
11/10 07:06:22.004372 00000618 TDB ERROR vgId:5 failed to insert data since Invalid table ID
11/10 07:06:22.004386 00000616 TDB ERROR vgId:3 failed to get table to insert data, uid 844425836120331 tid 54
11/10 07:06:22.004418 00000616 TDB ERROR vgId:3 failed to insert data since Invalid table ID
11/10 07:06:23.259737 00000616 TDB ERROR vgId:3 failed to get table to insert data, uid 844426691771402 tid 105

**Environment (please complete the following information):**
 - OS: [CentOS 7]
 - Memory 128G
 - CPU Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz
 - current Disk Space 5T
 - TDengine Version 2.2.0.2

**Comment by yu285** [comment]
可以添加微信15652223354做具体排查
