### ISSUE TITLE
error when building TDengine from develop branch

### ISSUE THREAD

**Issue by lianjt** [taosdata/TDengine#8682]
**Bug Description**
when install TDengine from develop branch and executing 
`cmake .. && cmake --build .`
and see the error like blow:
`Unknown CMake command "ExternalProject_Add".`

**To Reproduce**
environment: centos 7
arch: x86_64
1. install follow the instruction on the front page
2. execute command cmake .. && cmake --build .
3. see the error

**Expected Behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/6482015/141748814-7c8aa771-b086-4b57-b2f1-87d3d28e8eee.png)

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by cpvmrd** [comment]
Please update your cmake  version up to 3.0+.  `ExternalProject_Add` is a cmake function(https://cmake.org/cmake/help/latest/module/ExternalProject.html).

**Comment by lianjt** [comment]
![image](https://user-images.githubusercontent.com/6482015/141759287-96fd10ca-b4e5-4f87-a8b7-accf3817ecdb.png)
updated and still has the problem

**Comment by sangshuduo** [comment]
solved with the official cmake3 (ver 3.17) of CentOS7.
