### ISSUE TITLE
Copy into fixed size buffer (STRING_OVERFLOW)

### ISSUE THREAD

**Issue by Aries-Lee1991** [taosdata/TDengine#8690]
https://github.com/taosdata/TDengine/blob/develop/src/client/src/tscServer.c

in line 1537

Copying p - > fullname without checking the length may overflow the 237 character fixed size string pcreate - > tablename.

![image](https://user-images.githubusercontent.com/48907085/141928610-4bcd1881-4543-4042-a08c-0eea4a2283cc.png)

**Comment by xiaohu4313888** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

Assigned it to you.

**Comment by xiaohu4313888** [comment]
I have a problem, how do I solve this problem：
throw an exception when the size exceeds the preset size of 237 or
make the target pCreate save only the first 237 characters

**Comment by hjxilinx** [comment]
Print this error message in the log file, and truncate the initial 237 characters of the full table name.

**Comment by xiaohu4313888** [comment]
thanks i'll rewrite tonight
