### ISSUE TITLE
Unused value (UNUSED_VALUE)

### ISSUE THREAD

**Issue by Aries-Lee1991** [taosdata/TDengine#8695]
https://github.com/taosdata/TDengine/blob/develop/src/query/src/qFilter.c

Assigning value from i to cEnd here, but that stored value is overwritten before it can be used.
![image](https://user-images.githubusercontent.com/48907085/141934106-7c417c42-61e0-4dd1-b246-0a6c13a5847a.png)

**Comment by prnake** [comment]
Pick up challenge

**Comment by Aries-Lee1991** [comment]
> Pick up challenge

Assigned it to you.
