### ISSUE TITLE
tar包安装后，taosd服务正常，运行taos提示“TSDB error: authentication failure”

### ISSUE THREAD

**Issue by malinco** [taosdata/TDengine#87]

**Comment by hzcheng** [comment]
请问您能提供更多信息吗？比如操作系统信息，使用场景？另外，您用tar包安装时时候用其他的包安装过？

**Comment by xincan** [comment]
第一步：systemctl status taosd,如果运行状态请 systemctl stop taosd掉
第二步： sudo rm -rf /var/lib/taos
第三步:    sudo mkdir /var/lib/taos
第四步：systemctl start taosd

第五步： taos回车，恭喜您已经进入了客户端，请开始您的表演

**Comment by malinco** [comment]
@xincan 非常感谢～

**Comment by malinco** [comment]
@hzcheng 已搞定，如xincan所提供步骤，之前没有删除彻底。
