### ISSUE TITLE
Unused value 

### ISSUE THREAD

**Issue by Aries-Lee1991** [taosdata/TDengine#8719]
https://github.com/taosdata/TDengine/blob/develop/src/util/src/tconfig.c

Assigning value true to ret here, but that stored value is overwritten before it can be used.

![image](https://user-images.githubusercontent.com/48907085/142360873-80561aa6-10d4-4085-8431-a36c65711225.png)

**Comment by cccgp** [comment]
It seems we just need to add else, right? If so, I am willing to submit a pr. @Aries-Lee1991

**Comment by Aries-Lee1991** [comment]
> It seems we just need to add else, right? If so, I am willing to submit a pr. @Aries-Lee1991

Yes, you can try it. Assigned it to you.
