### ISSUE TITLE
DB error: Invalid Vgroup ID (0.004346s)

### ISSUE THREAD

**Issue by wzm20191010** [taosdata/TDengine#8767]
![image](https://user-images.githubusercontent.com/54854351/142889898-2c5db97d-ad83-4bc0-86b3-acf7ee7c5285.png)
![image](https://user-images.githubusercontent.com/54854351/142890160-8e955234-57fc-43e6-88a0-2915d79e8986.png)
DB error: Invalid Vgroup ID (0.004346s)

**Comment by yu285** [comment]
我们用的什么版本？然后是在什么情况下出现这个问题的？

**Comment by wzm20191010** [comment]
刚开始用的2.1.3.2 版本 ，我们把TD数据库装在了Hype-v的虚拟机器&nbsp;， 刚开始还好好的， 虚拟机重启过，刚开始也没问题，然后突然一天就出现这个问题了，我们怀疑版本太旧然后就升级了2.2.2.0版本，TD启动了也成功了 ，执行show database，use databases也没问题 就是执行sql查询语句就报了这个问题


--------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taosdata/TDengine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月23日(星期二) 下午4:40
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [taosdata/TDengine] DB error: Invalid Vgroup ID (0.004346s) (Issue #8767)





 
我们用的什么版本？然后是在什么情况下出现这个问题的？
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yu285** [comment]
是全部表都这样吗还是个别表？这是一个相对比较旧的问题。近期版本已经很少出现了。

**Comment by wzm20191010** [comment]
所有表执行查询语句都不行，原来是2.1.X的版本，我以为是版本问题 现在升级到了2.2.X版本还是不行&nbsp; 


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taosdata/TDengine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月1日(星期三) 上午10:25
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [taosdata/TDengine] DB error: Invalid Vgroup ID (0.004346s) (Issue #8767)





 
是全部表都这样吗还是个别表？这是一个相对比较旧的问题。近期版本已经很少出现了。
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
