### ISSUE TITLE
Does TDengine support IPV6?

### ISSUE THREAD

**Issue by jonathanwx** [taosdata/TDengine#8769]
是否支持ipv6，或者ipv6的配置需要注意哪些

![image](https://user-images.githubusercontent.com/6824364/142961009-6718f73a-740e-4d0b-9477-b4054253cac4.png)

按照以上配置报如下错误
![image](https://user-images.githubusercontent.com/6824364/142961486-12ccf4c4-040c-49aa-b3c9-38daf2688253.png)

**Comment by yu285** [comment]
currently we don't support it yet , but will do it in the future

**Comment by fengqiangboy** [comment]
现在支持了吗？

> currently we don't support it yet , but will do it in the future

**Comment by yu285** [comment]
> 现在支持了吗？
> 
> > currently we don't support it yet , but will do it in the future
暂时还没有，我们是有特定需求吗？

**Comment by fengqiangboy** [comment]
> > 现在支持了吗？
> > > currently we don't support it yet , but will do it in the future
> > > 暂时还没有，我们是有特定需求吗？

公司内网都是IPV6的，windows客户端连接不上，报FQDN错误
