### ISSUE TITLE
TDengine docker  connection issue

### ISSUE THREAD

**Issue by wangqy1973** [taosdata/TDengine#8787]
**Bug Description**
docker方式在CentOS7（阿里云ECS）下安装tdengine，端口6030-6042在宿主机映射为36030-36042（确认安全策略中tcp/udp端口都打开了）；windows端安装Taos-client，在cfg中配置，修改相应默认端口6030为36030；运行taos.exe，连接ok，use test; , describe meters; 都OK，但是  select * from meters limit 10; 就错了，提示“DB error， Unable to establish connection;”。 打开debugFlag=135，重复操作，查看log，发现在select操作时，连接的还是6030端口，日志请看下面文件，
.
[taoslog.0.log](https://github.com/taosdata/TDengine/files/7595910/taoslog.0.log)

![微信截图_20211124212348](https://user-images.githubusercontent.com/12954281/143246637-d1a6dcac-4d4f-482f-a1ad-05a0b045ec04.png)

是我还有哪里没有配置OK吗？还是客户端程序（connector）的bug？如何处理呢？

**Comment by yu285** [comment]
配置问题需要排查，可能微信沟通更快一些，可以添加15652223354
