### ISSUE TITLE
server crash while query using groupby

### ISSUE THREAD

**Issue by qingshenyijiu** [taosdata/TDengine#881]
**Bug Description**
聚合查询会导致服务端直接挂掉，下面是挂掉时的堆栈信息
![QQ截图20191206183149](https://user-images.githubusercontent.com/14091724/70400868-fa35b980-1a67-11ea-90eb-f1e8a155fce8.png)

**Environment (please complete the following information):**
 - OS: [CentOS 7.0]
 - TDengine Version [1.6.4.1]

**Comment by qingshenyijiu** [comment]
聚合查询语句：
![QQ截图20191209094331](https://user-images.githubusercontent.com/14091724/70400964-7203e400-1a68-11ea-97ca-8561430b01c4.png)

**Comment by sangshuduo** [comment]
请使用一下新版本，谢谢
