### ISSUE TITLE
last udf cannot be with interval clause

### ISSUE THREAD

**Issue by jamesdzhang** [taosdata/TDengine#8836]
**Bug Description**
when last udf and interval clause are together. it will trigger oom and restart db.

**To Reproduce**
1. prepare amount of data.(10mill/day)
2. exec sql like 'select last(col) from tbl interval(1d)'
in Taos client.

**Expected Behavior*
hope to get the last value of col per day. 

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 8.x]
 - Memory 192g
 - TDengine Version [2.2.0.2]

**Additional Context**
none

**Comment by yu285** [comment]
May I get your data for reproducing this issue ?

I did some test ,but the query works.

or you can add my wechat 15652223354  to make a quick check

**Comment by jamesdzhang** [comment]
I got oom error. so u may produce big amount records . Then db will be cursh if u execute sql with last and interval clause altogether ( mine has 40 billion records)
