### ISSUE TITLE
Cluster DB error: Unable to resolve FQDN (11.358000s)

### ISSUE THREAD

**Issue by andyfu007** [taosdata/TDengine#8873]
**Bug Description**
centos7搭建集群后，执行sql，报DB error: Unable to resolve FQDN (11.358000s)

**To Reproduce**
1. 在centos上添加了集群，版本是2.0.20.13，一共4台机器，并建立了测试数据库test，test中建表t1，并生成了一条记录，在每个机器上查询是正常的(语句：select * from t1）
2.在windows客户端上，使用配置文件，设置了firstEp，secondEp，分别是集群中的2个机器
3. 连接集群正常，进入数据库test正常，执行查询t1表的时候，报错DB error: Unable to resolve FQDN (11.345000s)，语句非常简单
select * from t1

**Comment by yu285** [comment]
这个一般是在客户端的hosts里没有配置集群的hosts信息。
要把所有节点的fqdn和ip写进去。

就是说把linux节点的hosts信息复制一份到windows的hosts里面
