### ISSUE TITLE
Operands don't affect result 

### ISSUE THREAD

**Issue by Aries-Lee1991** [taosdata/TDengine#8881]
in https://github.com/taosdata/TDengine/blob/develop/src/os/src/detail/osTime.c

start + pInterval->sliding <= 9223372036854775807L is always true regardless of the values of its operands. 

![image](https://user-images.githubusercontent.com/48907085/144188972-051afafb-9703-4c15-b8a3-9ce32c4b59d2.png)

**Comment by Pandahunter-cloud** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

assigned it to you.

**Comment by Aries-Lee1991** [comment]
@Pandahunter-cloud  how is it going?
