### ISSUE TITLE
TDengineAlert couldn't add rules？

### ISSUE THREAD

**Issue by sphlls-hohhot** [taosdata/TDengine#8888]
[root@bogon TDengine-alert]# ./alert -cfg alert.cfg
2021-12-01T17:11:35.827+0800	INFO	log/log.go:44	upgrading database to version: 0
2021-12-01T17:11:35.854+0800	INFO	log/log.go:49	total 0 rules loaded
2021-12-01T17:11:35.855+0800	INFO	log/log.go:44	Listening at port: 8100
2021-12-01T17:11:55.281+0800	ERROR	log/log.go:64	failed to parse rule: invalid character 'ã' looking for beginning of object key string
github.com/taosdata/alert/utils/log.Error
	/home/ubuntu/workroom/jenkins/TDinternal/community/alert/utils/log/log.go:64
github.com/taosdata/alert/app.onUpdateRule
	/home/ubuntu/workroom/jenkins/TDinternal/community/alert/app/app.go:78
net/http.HandlerFunc.ServeHTTP
	/home/ubuntu/soft/go/src/net/http/server.go:2042
net/http.(*ServeMux).ServeHTTP
	/home/ubuntu/soft/go/src/net/http/server.go:2417
main.(*httpHandler).ServeHTTP
	/home/ubuntu/workroom/jenkins/TDinternal/community/alert/cmd/alert/main.go:31
net/http.serverHandler.ServeHTTP
	/home/ubuntu/soft/go/src/net/http/server.go:2843
net/http.(*conn).serve
	/home/ubuntu/soft/go/src/net/http/server.go:1925
2021-12-01T17:11:55.281+0800	DEBUG	log/log.go:39	[POST]	/api/update-rule	1.113836ms
^C'Ctrl + C' received, exiting...
2021-12-01T17:15:14.736+0800	ERROR	log/log.go:64	http: Server closed
github.com/taosdata/alert/utils/log.Error
	/home/ubuntu/workroom/jenkins/TDinternal/community/alert/utils/log/log.go:64
main.serveWeb.func1
	/home/ubuntu/workroom/jenkins/TDinternal/community/alert/cmd/alert/main.go:45
--------一添加规则就报这个错----
[root@bogon TDengine-alert]# cat alert.cfg
{
	"port": 8100,
	"database": "file:alert.db",
	"tdengine": "root:root@/tcp(127.0.0.1:0)/",
	"log": {
		"level": "debug",
		"path": ""
	},
	"receivers": {
		"alertManager": "http://127.0.0.1:9093/api/v1/alerts",
		"console": true
	}
}
--其中数据库配置那个 也是使用过默认配置文件都不行

---这是规则信息
[root@bogon ruite]# cat rule.json 
{
　　"name": "d1001_50",
　　"sql": "select avg(tdata) as avgVal  from test.d1001  order by ts desc limit 50",
　　"expr": "avgVal > 50",
　　"for": "10s",
　　"period": "1s",
　　"labels": {
　　　　"ruleName": "d1001_50"
　　},
　　"annotations": {
　　　　"summary": "设备名称:在50条数据中,平均值超过50标准,值为{{$values.avgVal}}"
　　}
}
[root@bogon ruite]# curl -d '@rule.json' http://localhost:8100/api/update-rule
[root@bogon ruite]# curl http://localhost:8100/api/list-rule
null
[root@bogon ruite]# 
-----------------------------------------------------------
都是在同一台服务器，数据库可以使用，操作系统是CentOS7_64

**Comment by yu285** [comment]
您好，我们有很多用户交流群，可以加我微信15652223354做具体排查

**Comment by Kolo7** [comment]
我也发生了这种问题，相同的告警rule，调整summary信息后，无法通过api方式更新

**Comment by huolibo** [comment]
alert ：
{
	"port": 8100,
	"database": "file:alert.db",
	"tdengine": "root:taosdata@/tcp(127.0.0.1:6030)/",
	"log": {
		"level": "debug",
		"path": "/Users/liubei/Workspaces/taos/TDengine/alert/cmd/alert/log"
	},
	"receivers": {
		"alertManager": "http://127.0.0.1:9093/api/v1/alerts",
		"console": true
	}
}
rule.json 
{
    "name": "d1001_50",
    "sql": "select avg(req_select) as avgVal from log.dn1",
    "expr": "avgVal > 0.1",
    "for": "10s",
    "period": "1s",
    "labels": {
        "ruleName": "d1001_51"
    },
    "annotations": {
        "summary": "设备名称:在50条数据中,平均值超过50标准,值为{{$values.avgVal}}"
    }
}
使用最新版TDengine-alert-2.4.0.0-Linux-x64.tar.gz
未能复现提到的bug。
可以提供下使用哪个alert版本吗？
其次确定rule.json中的sql语句在taos shell中可以正常执行。

**Comment by Kolo7** [comment]
问题无法复现了，可能是我rule写的有问题
