### ISSUE TITLE
Windows系统用python可以用TDEngine吗

### ISSUE THREAD

**Issue by jeaken** [taosdata/TDengine#89]
Windows系统下可以正常安装TDEngine的python驱动，但使用时报错；

OSError: [WinError 126] 找不到指定的模块。

时缺少东西还是python驱动不能在Windows系统下使用？

**Comment by hzcheng** [comment]
windows的dll库以及python库都会在最近公开

**Comment by squ** [comment]
用Http协议包装一下

**Comment by guanshengliang** [comment]
会采用dll的方式，因为HTTP的性能相比原生C接口会有一定量衰减

**Comment by treemp3** [comment]
刚好遇到了这个问题，mark一下。

**Comment by Janus-Xu** [comment]
issue 挂了一个月了，有预估完成的时间么
