### ISSUE TITLE
the start time of interval function

### ISSUE THREAD

**Issue by JiPengL** [taosdata/TDengine#8938]
我这边有个需求，需要计算某时间段内的10个时间点数值，由于开窗的时间可能大于10个小时，导致第一条数据时间早于开始时间太多，偏移量又不好计算，能否自动校正，或者给个偏移量计算的公式？

**Comment by sunshine-smdbs** [comment]
建议给出具体的数据例子

**Comment by yu285** [comment]
起始时间为1970-01-01 00:00:00 UTC时区，只能做固定范围的切割，这个公式不好给，但是比较容易调试。建议自己左右调整几下，
