### ISSUE TITLE
JDBC:  error when create database and tables

### ISSUE THREAD

**Issue by wangsihfu** [taosdata/TDengine#894]
我使用官方的demo创建数据库和表的时候出现了这个错误，请教下什么原因
`JDBC URL to use:
jdbc:TAOS://192.168.123.76:0/?user=root&password=taosdata

---------------------------------------------------------------
Start creating databases and tables...
`java.sql.SQLException: TDengine Error: success`
	at com.taosdata.jdbc.TSDBJNIConnector.connect(TSDBJNIConnector.java:100)
	at com.taosdata.jdbc.TSDBConnection.connect(TSDBConnection.java:64)
	at com.taosdata.jdbc.TSDBConnection.<init>(TSDBConnection.java:56)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:135)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at TSDBSyncSample.doCreateDbAndStable(TSDBSyncSample.java:48)
	at TSDBSyncSample.main(TSDBSyncSample.java:380)
Failed to execute SQL: 
Disconnected from the target VM, address: '127.0.0.1:56756', transport: 'socket'

Process finished with exit code 4`

报错的代码位置：
![image](https://user-images.githubusercontent.com/38022823/70507920-508a2180-1b68-11ea-9ba9-efb3a990e9a4.png)

**Comment by hjxilinx** [comment]
@wangsihfu ，请更新到最新的版本再试一试。

**Comment by wangsihfu** [comment]
谢谢！！我发现是这个问题了，然后更新了下，结果悲剧了，之前在你们的demo下修改的代码，现在被覆盖了，我。。------------------ 原始邮件 ------------------
发件人: "haojun Liao"<notifications@github.com>
发送时间: 2019年12月10日(星期二) 下午5:38
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
抄送: "wangsihfu"<1569069394@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [taosdata/TDengine] 创建数据库和表的时候出错 (#894)



@wangsihfu ，请更新到最新的版本再试一试。
 
&mdash;

**Comment by hjxilinx** [comment]
Sorry to hear that！我能帮上什么忙吗？

**Comment by wangsihfu** [comment]
没有了，这是我的问题，大佬还是挺专业的，一下就说出关键，话说那个java demo你们改过代码吗,为啥旧版的数据库报错。。



---原始邮件---
发件人: "haojun Liao"<notifications@github.com&gt;
发送时间: 2019年12月10日(周二) 晚上9:20
收件人: "taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"wangsihfu"<1569069394@qq.com&gt;;
主题: Re: [taosdata/TDengine] 创建数据库和表的时候出错 (#894)



Sorry to hear that！我能帮上什么忙吗？

**Comment by xieyinglin** [comment]
原来的java demo 最近没有改动，新增了 spring template 和 springboot 的 demo ,https://github.com/taosdata/TDengine/tree/develop/tests/examples/JDBC
