### ISSUE TITLE
TDengine support AWS-s3 persistence storage

### ISSUE THREAD

**Issue by t00350320** [taosdata/TDengine#8962]
嗨，tdenginer ,这边是OPPO 时序数据团队的开发。近期在使用tdengine产品过程中，根据我司的使用场景，增加了tdengine历史数据支持AWS-s3协议的持久化存储功能。目前写入和查询的自测流程已打通。因为持久化存储是贵司内部方案，不清楚是否有冲突。
方案大致如下，请帮忙审核一下。如果有需要，再详细沟通。

1、利用二级存储目录data_ocs来临时存放待上传到OCS（openshift container storage）的xx.data文件。
2、s3-adaptor。go语言实现，集成aws-s3功能，提供独立的上传/查询功能。即执行上传data文件到OCS，提供range查询OCS的功能。

对于1：
1.1 配置修改
# data file's directory
dataDir                   /home/service/var/taos/data_ocs 1 0
dataDir                   /home/service/var/taos/data 0 1

keep配置：
keep0,keep1,keep2
30,180,360

1.2 data_ocs目录如下：
/home/service/var/taos/data_ocs/vnode/vnode723/tsdb/data
ocs_uploaded.cfg   【s3-adaptor如果已上传'xx.data'到OCS，在此文件打标记。】
v723f1883.head-ver2
v723f1883.last
v723f1884.data-ver7
v723f1884.head-ver7
v723f1884.last-ver3
v723f1885.data-ver7
v723f1885.head-ver7
v723f1885.last-ver7
vnode.ocs【tdengine如果发现需要把'xx.data'上传到OCS，在此文件打标记】

1.3 流程如下：
以插入2021-08-12号数据为例：
tdengine按照预先配置的keepday与dataDir，判断出来2021-08-12号的数据，需要写入
/home/service/var/taos/data_ocs/vnode/vnode723/tsdb/data/v723f1885.data-ver7文件

tsdbCommitToFile 按照原有流程落盘。
此函数最后，进入新增功能，AppendDataToFile，将v723f1885.data-ver7名写入vnode.ocs，该文件内容为：
/home/service/var/taos/data_ocs/vnode/vnode723/tsdb/data/v723f1885.data-ver7;
xxx.data;

s3-adaptor进程轮询/home/service/var/taos/data_ocs/vnode/下的所有vnodexx/tsdb/data目录，以检查vnode.ocs。
对于其中的内容，判断是否已上传到OCS。如果已上传到OCS，则过滤不处理；如果还未处理，准备上传data文件到OCS；上传成功后，将记录写入ocs_uploaded.cfg文件，该文件内容为：s3-adaptorip;datafile;timestamp格式
10.64.42.66:3200;/home/service/var/taos/data_ocs/vnode/vnode723/tsdb/data/v723f1884.data-ver5;1638444111;
该文件中标记的原始data文件，因为已上传到OCS，会在第二天（可配，防止当天的持续本地请求）被真正删除。

tsdbLoadColData
查询时，如果ocs_uploaded.cfg中没有目标data文件，就在本地查data file; 如果有目标文件，就去S3接口查data file.

引入vnode.ocs和ocs_uploaded.cfg两个文件，其实是为了实现一个文件锁的功能，因为有如下场景：
1、当历史数据刚落盘，此时s3还未将data上传到OCS，直接去OCS查询会失败。
2、当本地历史数据正在被查询，此时s3却将data上传到OCS，并尝试删除本地文件，会导致查询失败。
3、使用s3-adaptor单独部署，可以和tdengine解耦。
对于上传进程，因为历史数据上传，本身不需要实时性，但是数量比较大，单独的上传进程可以慢慢处理。
对于查询进程。tdengine本身有汇聚功能，使用offset的查询方式，原则上后端可以提供多个s3-adaptor查询进程，提高查询效率。

**Comment by yu285** [comment]
we will take care on this

**Comment by yu285** [comment]
TDengine 3.x 企业版已经支持 3.x 存储特性，如有需求可以联系我们：微信 a15652223354
