### ISSUE TITLE
JNI ERROR (2355)

### ISSUE THREAD

**Issue by raineyJ** [taosdata/TDengine#8964]
jdbc错误：java.sql.SQLException: JNI ERROR (2355): JNI result set is NULL

数据库日志错误：VND ERROR vgId:3, invalid qId in retrieving result, code:Invalid handle, QInfo:28319682649305652

表里数据2亿  
sql执行返回500条  
有7个客户端连接并发查询同一个表

服务端ubuntu20.04  
客户端win7

**Comment by fenghuazzm** [comment]
Older versions of TDengine have this error like 'invalid handle' with some queries. Please try to upgrade to the latest version and see if there is any problem.
