### ISSUE TITLE
按文档默认步骤测试，启动出错

### ISSUE THREAD

**Issue by flybird119** [taosdata/TDengine#9]
完全按照文档的默认步骤编译和启动：
./build/bin/taosd -c test/cfg，taosd一直打印出错信息：

![image](https://user-images.githubusercontent.com/10595211/61181200-7a8cf580-a655-11e9-811a-26261a807a50.png)

**Comment by flybird119** [comment]
然后我把data目录下面的内容全部删除，再次启动taosd：
./build/bin/taosd -c test/cfg，此时taosd一直打印另外的出错信息：

![image](https://user-images.githubusercontent.com/10595211/61181276-89c07300-a656-11e9-9225-2d96dbd2bce7.png)

**Comment by hzcheng** [comment]
Do you have enough disk on your system? When TDengine starts, it needs to reserve some disk space using _mmap_ function. The error comes from a _mmap_ failure. If you have enough disks, can you give us a detailed description of your environment? Thanks!

**Comment by guanshengliang** [comment]
检查一下是不是在使用共享目录
