### ISSUE TITLE
请问如何update数据

### ISSUE THREAD

**Issue by kelvinxue** [taosdata/TDengine#90]
对某几个时间戳的数据进行更新

**Comment by johnnyhou327** [comment]
Hi @kelvinxue  TDengine目前不支持更新或删除数据记录。删除数据是定期自动删除。

**Comment by kelvinxue** [comment]
那只能删除table，重新刷全量数据？

**Comment by hjxilinx** [comment]
可以删除table，不能删除单挑记录。后面我们会支持有限度（低频）的更新操作。

**Comment by cleverpig** [comment]
mark一下，这个特性的确有待实现。
或者有没有workaround的方式？比如使用tag？

**Comment by cleverpig** [comment]
再或者像influxdb那样：
将tags 和 time  是判断时序数据库点(point)的唯一性的标准，相当于关系型数据库的复合主键。
这样当我们insert的time和tags 跟原有的数据重复时，就会覆盖掉原有数据。

**Comment by jayed008** [comment]
db 的配置文件有update这一项，改为1重启即可更新，但建议不要这么做，性能损失比较大
