### ISSUE TITLE
python3 double free or corruption

### ISSUE THREAD

**Issue by korimas** [taosdata/TDengine#9004]
使用python的sdk，发生如下错误，python进程直接crash了。
![image](https://user-images.githubusercontent.com/15672287/145340234-7178cbb1-d941-4e20-b273-1dd4990e2fd3.png)
![image](https://user-images.githubusercontent.com/15672287/145344601-112c5113-22b6-481b-b217-2c4a3dc4a1b7.png)

**Comment by korimas** [comment]
![image](https://user-images.githubusercontent.com/15672287/145370205-b8d57af3-f92c-49bd-925d-d3f62ea57157.png)

**Comment by zitsen** [comment]
请提供以下信息
1. 操作系统版本，CPU架构，
2. Python版本
3. Python连接器版本
4. 如果可能，提供最短复现脚本

**Comment by korimas** [comment]
> 请提供以下信息
> 
> 1. 操作系统版本，CPU架构，
> 2. Python版本
> 3. Python连接器版本
> 4. 如果可能，提供最短复现脚本

1、操作系统：centos7   x86_64
2、python3.6.8
3、连接器版本是和rpm包在一起的

**Comment by zitsen** [comment]
Python connection - taospy - is well tested by GitHub Actions now, please use latest version of taospy `pip3 install -U taospy`.

Re-open the issue if it does not solve your problem.
