### ISSUE TITLE
RESTful interface lead to memory increasing without bound until crash.

### ISSUE THREAD

**Issue by OrangeEffects** [taosdata/TDengine#9012]
问题:
RESTful 接口调用导致内存无限增长，直到系统挂掉

场景：
通过RESTful 接口向TDengine批量导入数据
TDengine里表不到3000张
开四个任务并行调用RESTful接口，批量insert，单条sql长度拉满（1048000）
taosd进程内存开销以大约 每分钟 0.1%（总共32GB）的速度上涨
直到taosd把内存耗尽，操作系统不响应了（taosd进程还活着，RESTful请求进不来了，ssh都不响应了，只能强制重启）

我尝试把RESTful接口并发任务数降低，taosd进程内存增长速度也相应放缓
不调用RESTful接口，taosd进程内存几乎不增长

重点怀疑是RESTful接口的问题

服务器环境：
 - OS: CentOS 8.4
 - Memory 32GB, CPU 4c/4t, 200GB
 - TDengine Version 2.2.1.3

**Comment by yu285** [comment]
请添加微信15652223354做具体排查
