### ISSUE TITLE
tdengine  consumes large amounts of I/O

### ISSUE THREAD

**Issue by wwbgo** [taosdata/TDengine#9025]
**Bug Description**
tdengine大量消耗磁盘存储IO
我们目前存储平均每秒存140k条数据条目,超过4M数据大小每秒,
但是使用下来发现tdengine的磁盘存储IO占用量远远大于我们的数据存储量,大约占用800M,IO吃满.
请问下哪里出了问题?

**To Reproduce**

**Expected Behavior**

**Screenshots**
![E5JKK {LM7{@RKO)MIBDSPG](https://user-images.githubusercontent.com/7360060/145503594-88e430e4-a223-48fa-ade4-a025e73640a7.png)
![RWGUE$(_6UA@JGX~4TZ 85P](https://user-images.githubusercontent.com/7360060/145503603-5b56b88e-629f-4efc-8967-b22de3d89477.png)
![TB2BC)5~@@P$G52PJJ2K7OY](https://user-images.githubusercontent.com/7360060/145503608-1b09e14a-9cf9-49f4-bba6-49f31a5f39e1.png)
![image](https://user-images.githubusercontent.com/7360060/145504446-4f5ee4d5-50fd-4bc7-9d4b-8cf029a70de9.png)

**Environment**
 - OS: CentOS 7.0
 - Memory: 32G, CPU: 8C, current Disk Space: 1T
 - TDengine Version: 2.2.2.0
 - 阿里云ECS, 固态硬盘: 81800 IOPS
![image](https://user-images.githubusercontent.com/7360060/145504347-576ff837-30f6-4095-a9fe-242fe5d4954e.png)

**Additional Context**

**Comment by wwbgo** [comment]
程序监控指标
![image](https://user-images.githubusercontent.com/7360060/145505203-11240881-5782-4f44-a504-c47fe4111224.png)

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
