### ISSUE TITLE
what about the performance of importing history data

### ISSUE THREAD

**Issue by trump-dev** [taosdata/TDengine#904]
车联网场景，3000台左右网关，5秒回传一次数据。目前，网关20%时候处于无网络信号的地方，数据会缓存在本地，待有信号时候上传。目前，模拟实时数据回传，数据毫无压力，可以get。
问题：如果实际使用时，有大量历史数据回传，对数据库进行插入或更新操作，性能上是否有影响或如何设计这个架构？

**Comment by guanshengliang** [comment]
Historical data import performance is not very good, try to avoid this operation.
If you must write, try to wait for the historical data to be imported before you start writing real-time data
Don't use two threads, one for real-time and one for history

**Comment by guanshengliang** [comment]
2.0版本已经发布并彻底解决了历史数据写入的问题，请使用2.0版本验证，如果还有问题，您可以提交一个新的issue
