### ISSUE TITLE
taos connect failed, reason: Unable to establish connection.

### ISSUE THREAD

**Issue by chenjuchuanandchenxi** [taosdata/TDengine#9046]
**问题描述**
在服务器上执行操作
[root@tm199 log]# taos
Welcome to the TDengine shell from Linux, Client Version:2.3.2.0
Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.

taos connect failed, reason: Unable to establish connection.

[root@tm199 log]# hostname
tm199

[root@tm199 log]# cat /etc/hosts
192.168.0.199 tm199

**环境:**
 - OS: CentOS7.6
 - TDengine-server-2.2.2.0

**日志信息**
cat taoslog0.0
12/11 13:49:51.285539 00037579 RPC ERROR TSC 0x7f329e9cf188 0x2, failed to send, msgLen:377 written:-1, reason:Invalid argument
12/11 13:49:51.589516 00037601 RPC ERROR TSC 0x7f329e9cf188 0x2, failed to send, msgLen:377 written:-1, reason:Invalid argument
12/11 13:49:51.889491 00037601 RPC ERROR TSC 0x7f329e9cf188 0x2, failed to send, msgLen:377 written:-1, reason:Invalid argument
12/11 13:49:52.189486 00037601 RPC ERROR TSC 0x7f329e9cf188 0x2, failed to send, msgLen:377 written:-1, reason:Invalid argument

cat taosdlog.0
12/11 14:06:15.276617 00037515 DND mnode index:0 6030:6035
12/11 14:06:15.276622 00037515 DND mnode index:1 tm199:6035
12/11 14:06:15.276626 00037515 DND mnode index:1 tm199:6035 set inUse to 0
12/11 14:06:15.276852 00037513 UTL ERROR failed to connect socket, ip:0x8e170000, port:6035(target host cannot be reached)
12/11 14:06:15.276912 00037513 RPC ERROR failed to connect to:0x8e170000:6035
12/11 14:06:15.276929 00037513 RPC ERROR DND-C (nil), failed to set up connection(Unable to establish connection)
12/11 14:06:15.281584 00037515 DND msg:status will be redirected, dnodeIp:192.168.0.199 user:t, numOfEps:2 inUse:1
12/11 14:06:15.281598 00037515 DND mnode index:0 6030:6035
12/11 14:06:15.281603 00037515 DND mnode index:1 tm199:6035
12/11 14:06:15.281607 00037515 DND mnode index:1 tm199:6035 set inUse to 0
12/11 14:06:15.281834 00037513 UTL ERROR failed to connect socket, ip:0x8e170000, port:6035(target host cannot be reached)
12/11 14:06:15.281889 00037513 RPC ERROR failed to connect to:0x8e170000:6035
12/11 14:06:15.281905 00037513 RPC ERROR DND-C (nil), failed to set up connection(Unable to establish connection)

**Comment by chenjuchuanandchenxi** [comment]
其他信息描述：
[root@tm199 log]# taos -n server -P 6030  -l 1000
12/11 17:13:11.031201 00023954 UTL work as server, host:tm199 startPort:6030 endPort:6041 pkgLen:1000

12/11 17:13:11.031477 00023979 UTL ERROR failed to bind TCP port:6030 since Address already in use
12/11 17:13:11.032080 00023980 UTL ERROR failed to bind UDP port:6030 since Address already in use
12/11 17:13:11.032634 00023983 UTL TCP server at port:6032 is listening
12/11 17:13:11.032661 00023981 UTL TCP server at port:6031 is listening
12/11 17:13:11.032661 00023982 UTL ERROR failed to bind UDP port:6031 since Address already in use
12/11 17:13:11.032732 00023985 UTL TCP server at port:6033 is listening
12/11 17:13:11.032751 00023984 UTL ERROR failed to bind UDP port:6032 since Address already in use
12/11 17:13:11.032787 00023986 UTL ERROR failed to bind UDP port:6033 since Address already in use
12/11 17:13:11.032913 00023987 UTL TCP server at port:6034 is listening
12/11 17:13:11.032991 00023990 UTL ERROR failed to bind UDP port:6035 since Address already in use
12/11 17:13:11.032918 00023988 UTL ERROR failed to bind UDP port:6034 since Address already in use
12/11 17:13:11.033000 00023989 UTL ERROR failed to bind TCP port:6035 since Address already in use
12/11 17:13:11.033053 00023992 UTL UDP server at port:6036 is listening
12/11 17:13:11.033067 00023991 UTL TCP server at port:6036 is listening
12/11 17:13:11.033196 00023994 UTL UDP server at port:6037 is listening
12/11 17:13:11.033219 00023993 UTL TCP server at port:6037 is listening
12/11 17:13:11.033268 00023995 UTL TCP server at port:6038 is listening
12/11 17:13:11.033299 00023996 UTL UDP server at port:6038 is listening
12/11 17:13:11.033372 00023997 UTL TCP server at port:6039 is listening
12/11 17:13:11.033405 00023998 UTL UDP server at port:6039 is listening
12/11 17:13:11.033422 00023999 UTL ERROR failed to bind TCP port:6040 since Address already in use
12/11 17:13:11.033476 00024000 UTL UDP server at port:6040 is listening
12/11 17:13:11.033509 00024001 UTL ERROR failed to bind TCP port:6041 since Address already in use
12/11 17:13:11.033534 00024002 UTL UDP server at port:6041 is listening

安装在一个单独的物理服务器上，同样一个版本安装在我的笔记本上就正常。郁闷了

**Comment by sunboy1** [comment]
client的版本要和server的版本一致，看你的服务器版本和客户端版本不一致

**Comment by yu285** [comment]
可以添加微信15652223354做具体排查

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
