### ISSUE TITLE
cannot connect to the server in a virtual machine from the windows client when trying the JDBCDemo

### ISSUE THREAD

**Issue by 471362807** [taosdata/TDengine#910]
虚拟机网络是正常的,在你们的JDBCDemo中,把ip替换成了虚拟机ip,其余不变,我也没改动安装的任何设置.但就是无法获取连接,请问咋回事呢?

`import java.sql.*;

public class TSDBSyncSample {
    private static final String JDBC_PROTOCAL = "jdbc:TAOS://";
    private static final String TSDB_DRIVER = "com.taosdata.jdbc.TSDBDriver";
    //jdbc:TAOS://127.0.0.1:6030/log?user=root&password=taosdata
    private String host = "192.168.12.131";//这个是我的虚拟机ip
    //private String host = "127.0.0.1";
    private String user = "root";
    private String password = "taosdata";
    private int port = 6030;
    private String jdbcUrl = "";

    private String databaseName = "db";
    private String metricsName = "meters";
    private String tablePrefix = "t";

    private int tablesCount = 1;
    private int loopCount = 2;
    private int batchSize = 10;
    private long beginTimestamp = 1519833600000L;

    private long rowsInserted = 0;

    static {
        try {
            Class.forName(TSDB_DRIVER);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args
     */
    public static void main(String[] args) {
        TSDBSyncSample tester = new TSDBSyncSample();
        tester.doReadArgument(args);

        System.out.println("---------------------------------------------------------------");
        System.out.println("Start testing...");
        System.out.println("---------------------------------------------------------------");

        tester.doMakeJdbcUrl();
        tester.doCreateDbAndTable();
        tester.doExecuteInsert();
        tester.doExecuteQuery();

        System.out.println("\n---------------------------------------------------------------");
        System.out.println("Stop testing...");
        System.out.println("---------------------------------------------------------------");
    }

    private void doReadArgument(String[] args) {
        System.out.println("Arguments format: host tables loop batchs");
        if (args.length >= 1) {
            this.host = args[0];
        }

        if (args.length >= 2) {
            this.tablesCount = Integer.parseInt(args[1]);
        }

        if (args.length >= 3) {
            this.loopCount = Integer.parseInt(args[2]);
        }

        if (args.length >= 4) {
            this.batchSize = Integer.parseInt(args[3]);
        }
    }

    private void doMakeJdbcUrl() {
        // jdbc:TSDB://127.0.0.1:0/dbname?user=root&password=taosdata
        System.out.println("\nJDBC URL to use:");
        //以下"test"这个入参,就是taosDemo,你们提供的那个测试脚本数据库来的
        this.jdbcUrl = String.format("%s%s:%d/%s?user=%s&password=%s", JDBC_PROTOCAL, this.host, this.port, "test",
                this.user, this.password);
        System.out.println(this.jdbcUrl);
    }

    private void doCreateDbAndTable() {
        System.out.println("\n---------------------------------------------------------------");
        System.out.println("Start creating databases and tables...");
        String sql = "";
        try (Connection conn = DriverManager.getConnection(jdbcUrl);
             Statement stmt = conn.createStatement()){

            sql = "create database if not exists " + this.databaseName;
            stmt.executeUpdate(sql);
            System.out.printf("Successfully executed: %s\n", sql);

            sql = "use " + this.databaseName;
            stmt.executeUpdate(sql);
            System.out.printf("Successfully executed: %s\n", sql);

            sql = "create table if not exists " + this.metricsName + " (ts timestamp, v1 int) tags(t1 int)";
            stmt.executeUpdate(sql);
            System.out.printf("Successfully executed: %s\n", sql);

            for (int i = 0; i < this.tablesCount; i++) {
                sql = String.format("create table if not exists %s%d using %s tags(%d)", this.tablePrefix, i,
                        this.metricsName, i);
                stmt.executeUpdate(sql);
                System.out.printf("Successfully executed: %s\n", sql);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.printf("Failed to execute SQL: %s\n", sql);
            System.exit(4);
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(4);
        }
        System.out.println("Successfully created databases and tables");
    }

    public void doExecuteInsert() {
        System.out.println("\n---------------------------------------------------------------");
        System.out.println("Start inserting data...");
        int start = (int) System.currentTimeMillis();
        StringBuilder sql = new StringBuilder("");
        try (Connection conn = DriverManager.getConnection(jdbcUrl);
             Statement stmt = conn.createStatement()){
            stmt.executeUpdate("use " + databaseName);
            for (int loop = 0; loop < this.loopCount; loop++) {
                for (int table = 0; table < this.tablesCount; ++table) {
                    sql = new StringBuilder("insert into ");
                    sql.append(this.tablePrefix).append(table).append(" values");
                    for (int batch = 0; batch < this.batchSize; ++batch) {
                        int rows = loop * this.batchSize + batch;
                        sql.append("(").append(this.beginTimestamp + rows).append(",").append(rows).append(")");
                    }
                    int affectRows = stmt.executeUpdate(sql.toString());
                    this.rowsInserted += affectRows;
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.printf("Failed to execute SQL: %s\n", sql.toString());
            System.exit(4);
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(4);
        }
        int end = (int) System.currentTimeMillis();
        System.out.println("Inserting completed!");
        System.out.printf("Total %d rows inserted, %d rows failed, time spend %d seconds.\n", this.rowsInserted,
                this.loopCount * this.batchSize - this.rowsInserted, (end - start) / 1000);
    }

    public void doExecuteQuery() {
        System.out.println("\n---------------------------------------------------------------");
        System.out.println("Starting querying data...");
        ResultSet resSet = null;
        StringBuilder sql = new StringBuilder("");
        StringBuilder resRow = new StringBuilder("");
        try (Connection conn = DriverManager.getConnection(jdbcUrl);
             Statement stmt = conn.createStatement()){
            stmt.executeUpdate("use " + databaseName);
            for (int i = 0; i < this.tablesCount; ++i) {
                sql = new StringBuilder("select * from ").append(this.tablePrefix).append(i);

                resSet = stmt.executeQuery(sql.toString());
                if (resSet == null) {
                    System.out.println(sql + " failed");
                    System.exit(4);
                }

                ResultSetMetaData metaData = resSet.getMetaData();
                System.out.println("Retrieve metadata of " + tablePrefix + i);
                for (int column = 1; column <= metaData.getColumnCount(); ++column) {
                    System.out.printf("Column%d: name = %s, type = %d, type name = %s, display size = %d\n", column, metaData.getColumnName(column), metaData.getColumnType(column),
                            metaData.getColumnTypeName(column), metaData.getColumnDisplaySize(column));
                }
                int rows = 0;
                System.out.println("Retrieve data of " + tablePrefix + i);
                while (resSet.next()) {
                    resRow = new StringBuilder();
                    for (int col = 1; col <= metaData.getColumnCount(); col++) {
                        resRow.append(metaData.getColumnName(col)).append("=").append(resSet.getObject(col))
                                .append(" ");
                    }
                    System.out.println(resRow.toString());
                    rows++;
                }

                try {
                    if (resSet != null)
                        resSet.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
                System.out.printf("Successfully executed query: %s;\nTotal rows returned: %d\n", sql.toString(), rows);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.printf("Failed to execute query: %s\n", sql.toString());
            System.exit(4);
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(4);
        }
        System.out.println("Query completed!");
    }

}
`

**Comment by 471362807** [comment]
linux防火墙已关闭
![linux防火墙已关闭且相应端口已打开](https://user-images.githubusercontent.com/31850907/70691469-1d749900-1cf4-11ea-8a9a-6bd018699300.jpg)
taos安装成功
![taos安装成功](https://user-images.githubusercontent.com/31850907/70691491-22d1e380-1cf4-11ea-8ae3-e30dea28c732.jpg)
虚拟机可以ping通
![虚拟机ping通](https://user-images.githubusercontent.com/31850907/70691557-4f85fb00-1cf4-11ea-81b7-09d4853ee628.jpg)
windows的client无法连接上虚拟机里的数据库
![windows无法连接linux虚拟机上的数据库](https://user-images.githubusercontent.com/31850907/70691674-9d026800-1cf4-11ea-8f58-f93c0b8ee40d.jpg)
日志记录
![日志](https://user-images.githubusercontent.com/31850907/70691731-c3280800-1cf4-11ea-9bda-f0ce024df3f6.jpg)

请问这问题咋搞?

**Comment by xieyinglin** [comment]
虚拟机使用的网络是 bridge 还是 nat，建议最快的排查方式是直接把程序放到虚拟机里跑一下

**Comment by guanshengliang** [comment]
From your logs, you may have configured localIp for windows. 
Don't configure this option, try it again

**Comment by guanshengliang** [comment]
The description of this issue is not clear
You may not be connected to the database
Please set debugFlag to 135, and then upload the log file

**Comment by guanshengliang** [comment]
2.0版本已经发布，请使用2.0版本验证，如果还有问题，您可以提交一个新的issue
