### ISSUE TITLE
jdbc 驱动RestfulResultSet 时间戳类型转换错误

### ISSUE THREAD

**Issue by sunboy1** [taosdata/TDengine#9108]
com.taosdata.jdbc.rs.RestfulResultSet 202 行，row.getTimestamp(colIndex);  报类型转换错误；
感觉应该这块是忘记换了 Timestamp.valueOf(value) ，看上面有通过 getString 获取

**Comment by huolibo** [comment]
遇到什么问题了吗？
上面getString是通过长度来确定时间精度。当时间精度为ms，row.getTimestamp(colIndex)使用fastjson将string转为时间。如果非ms，需要手动转换。

**Comment by sunboy1** [comment]
我本地断点试了下， 换成 Timestamp.valueOf(value) 就可以了
![05692ce4d00e7daf923dde73791884a](https://user-images.githubusercontent.com/25715404/146323418-e2fdc7a7-8e70-4b49-b688-66051eb24f33.png)

**Comment by huolibo** [comment]
fastjson 的版本是使用taos jdbc中的吗？For input string报错是parseLong()传入了时间字符串。在1.2.58版本转换前做了是否是数值校验（行数575）。怀疑是版本问题。

**Comment by sunboy1** [comment]
从 develop 中检出的版本，看pom中的版本是 1.2.76;  在 JSONArray 中已经是 string 类型了，如果在JSONArray中是判定是Timestamp类型，getTimestamp 就不会有问题。

**Comment by huolibo** [comment]
可以通过配置指定JSONArray中的时间类型，默认是String。
可以进入JSONArray中查看下castToTimestamp(value) 查看下value的值吗？我本地未能复现这个情况。

**Comment by huolibo** [comment]
如果idea有code with me功能，可以给我一个连接，我在你的环境调试下

**Comment by sunboy1** [comment]
我想表达的是，如果是我环境的问题就没事，我自己改一下，重新打包一个client 包就可以了。如果大家都有这个问题，可以解决一下，我本地换成 Timestamp.valueOf(value) 重新打一个驱动包就没问题了。

**Comment by huolibo** [comment]
了解，只是感觉这个bug很奇怪，fastJson在parseLong前做了校验，字符串还是传进去了。想知道下产生的原因。

**Comment by huolibo** [comment]
上面的测试用例可以通过吗？

**Comment by huolibo** [comment]
或是找个地方执行这段代码看有没有抛错
public static void main(String[] args) {
        String data  = "2021-08-26 16:00:37.000";
        System.out.println(TypeUtils.castToTimestamp(data));
    }

**Comment by sunboy1** [comment]
是项目的fastjson的问题
