### ISSUE TITLE
query with limit -N seems not expected

### ISSUE THREAD

**Issue by kaybinwong** [taosdata/TDengine#9114]
**Bug Description**
query by limit -N seems not expected. 
```
taos> SELECT location, groupid, current FROM test.meters where ts<'2017-07-14 10:40:08.000' and location='beijing' LIMIT -2;
            location            |   groupid   |       current        |
======================================================================
 beijing                        |           2 |              9.72066 |
 beijing                        |           2 |              9.92063 |
 beijing                        |           2 |             10.03977 |
 beijing                        |           2 |              9.80025 |
 beijing                        |           2 |              9.44038 |
 beijing                        |           2 |              9.96045 |
 beijing                        |           2 |              9.48004 |
……
 beijing                        |           2 |              9.79926 |
 beijing                        |           2 |              9.64062 |
 beijing                        |           2 |              9.96094 |
[100 Rows showed, and more rows are fetching but will not be showed. You can ctrl+c to stop or wait.]
[You can add limit statement to show more or redirect results to specific file to get all.]
Query OK, 40000000 row(s) in set (5.036146s)
```

**Expected Behavior**
expected the last 2 records on condition **ts<'2017-07-14 10:40:08.000' and location='beijing'**

**Screenshots**
nothing

**Environment (please complete the following information):**
 - OS: 
 CentOS 7.9
 - Memory, CPU, current Disk Space
 32G/12C/2T
 - TDengine Version [e.g. 1.6.1.7]
 2.2.2.0

**Additional Context**
nothing left

**Comment by yu285** [comment]
we don't support the  negative value for limit currently

**Comment by kaybinwong** [comment]
it's necessary to support support the negative value for limit. just becasue
1/ last_row(xx) only return the last row
2/ it's inefficient or imposible to use order

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
