### ISSUE TITLE
Assigning value from daysToKeep1 to newCfg.daysToKeep1 here, but that stored value is overwritten before it can be used.

### ISSUE THREAD

**Issue by Aries-Lee1991** [taosdata/TDengine#9125]
In https://github.com/taosdata/TDengine/blob/develop/src/mnode/src/mnodeDb.c, Assigning value from daysToKeep1 to newCfg.daysToKeep1 here, but that stored value is overwritten before it can be used.

see images.
![image](https://user-images.githubusercontent.com/48907085/146319140-03c6fcae-22f4-4763-a158-3ebc191cc727.png)
![image](https://user-images.githubusercontent.com/48907085/146319196-d87d5ae3-7fd0-48f7-a496-3bbef9f59e95.png)

You should add #ifdef _STORAGE…#endif, like
![middle_img_v2_d6886fc8-c313-424a-91df-27d502d0555g](https://user-images.githubusercontent.com/48907085/146319539-643a9d7a-94b5-4c39-b53d-fa2f6ea0b38c.png)

**Comment by boyxiaolong** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

Assigned it to you.
