### ISSUE TITLE
Did you intend to use sizeof (tValuePair *) instead of sizeof (tValuePair **)?

### ISSUE THREAD

**Issue by Aries-Lee1991** [taosdata/TDengine#9126]
in https://github.com/taosdata/TDengine/blob/develop/src/query/src/qAggMain.c, Passing argument pList of type tValuePair ** and argument 8 /* sizeof (tValuePair **) */ to function taosheapsort is suspicious. In this case, sizeof (tValuePair **) is equal to sizeof (tValuePair *).

![image](https://user-images.githubusercontent.com/48907085/146319846-7d3badd9-110d-4aa3-ab8a-8b1b3f6b3feb.png)

You can use sizeof (tValuePair *) instead of sizeof (tValuePair **).

**Comment by lihongxing6** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

Assigned it to you.
