### ISSUE TITLE
parameter "extraRow" was set but never used

### ISSUE THREAD

**Issue by Aries-Lee1991** [taosdata/TDengine#9127]
In https://github.com/taosdata/TDengine/blob/develop/src/tsdb/src/tsdbRead.c, parameter "extraRow" was set but never used.

On the 865th line, see the image 
![image](https://user-images.githubusercontent.com/48907085/146320522-1487ad26-d910-43df-a821-512eb65c05e3.png)

but on the 909th line, "extraRow = rimem;" should be changed to "*extraRow = rimem;"
![image](https://user-images.githubusercontent.com/48907085/146320796-bc84bac0-1f1e-4932-a5ec-7869432cd293.png)

**Comment by eggfly** [comment]
Pick up challenge

**Comment by Aries-Lee1991** [comment]
> Pick up challenge @Aries-Lee1991

assigned it to you.

**Comment by lihongxing6** [comment]
pick up challenge

**Comment by Aries-Lee1991** [comment]
> pick up challenge

Sorry, others have received the task
