### ISSUE TITLE
jdbc prepared statement error

### ISSUE THREAD

**Issue by jamesdzhang** [taosdata/TDengine#9153]
**Bug Description*
create statement like [CREATE STABLE IF NOT EXISTS ? (?) TAGS (?)]; The tags part will be filled up wrongly by quoted them automaticalky(such as)：
[CREATE STABLE IF NOT EXISTS xx.xxx (a TIMESTAMP,aa INT) TAGS ('ab BIGINT')];

**To Reproduce**
1. create prepared statement with [CREATE STABLE IF NOT EXISTS ? (?) TAGS (?)] and args of [db.stablename, colsExp, tagsExp]
2. execute student sql.
3. See error

**Expected Behavior**
建表语句CREATE STABLE IF NOT EXISTS ? (?) TAGS (?); tags部分会渲染错误，自动加上了单引号（例如）：
CREATE STABLE IF NOT EXISTS db.stableName (colExp) TAGS (tagsExp);

**Screenshots**
actually. I got [CREATE STABLE IF NOT EXISTS db.stableName (colExp) TAGS ('tagsExp');]
the tags part have been quoted with '

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine  Jdbc Version [2.0.34]
 - Class com.taosdata.jdbc.TSDBPreparedStatement.execute() 

**Additional Context**

**Comment by huolibo** [comment]
i can't figure out this is a wrong using or a bug. please post the soruce code and the error result picture

**Comment by arielyang** [comment]
This issue was closed because it has been inactive for too many days.
