### ISSUE TITLE
Unable to establish connection appears when calling taos_connect() for the second time

### ISSUE THREAD

**Issue by Yurunsoft** [taosdata/TDengine#9166]
**Bug Description**
Unable to establish connection appears when calling taos_connect() for the second time

**To Reproduce**

code:

```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <taos.h>  // TAOS header file

int main(int argc, char *argv[]) {
    printf("version:%s\n", taos_get_client_info());
    for (int i = 0; i < 10; ++i)
    {
        TAOS *taos = taos_connect("127.0.0.1", "root", "taosdata", NULL, 6030);
        if (taos)
        {
            printf("SUCCESS\n");
        }
        else
        {
            printf("errno=%d, error=%s\n", taos_errno(taos), taos_errstr(taos));
        }
        taos_close(taos);
    }
    taos_cleanup();
    return 0;
}
```

output:

```
version:2.0.22.3
SUCCESS
errno=-2147483637, error=Unable to establish connection
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
```

**Expected Behavior**
```
version:2.0.22.3
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
```

**Screenshots**

**Environment (please complete the following information):**
 - OS: Docker
 - Memory, CPU, current Disk Space
 - TDengine Version 2.0.22.3

**Additional Context**

**Comment by sangshuduo** [comment]
ran 30 times but no error, doubt it's an insular network environment issue.

shuduo@lenovo ~/work/taosdata/tmp $ ./connect
version:2.3.2.0
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
shuduo@lenovo ~/work/taosdata/tmp $ ./connect
version:2.3.2.0
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
shuduo@lenovo ~/work/taosdata/tmp $ ./connect
version:2.3.2.0
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS

**Comment by Yurunsoft** [comment]
解决了，`/etc/taos/taos.cfg` 增加：

```
rpcForceTcp 1
```
