### ISSUE TITLE
invalid sql when inserting in batch

### ISSUE THREAD

**Issue by qiangmzsx** [taosdata/TDengine#917]
**Bug Description**
taos err=invalid SQL: syntax error near "lear:30:27"]##1575958344356220@#http.retry@#0##1575958344356220" (invalid data or symbol) 

**Expected Behavior**
import sql
**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.3]
- go

**Comment by plum-lihui** [comment]
请帮批量sql的文件发送给我们看看。多谢！
