### ISSUE TITLE
There is error when i install the "td-connector" in windows or linux using node 12.13.0

### ISSUE THREAD

**Issue by gaosong1206** [taosdata/TDengine#918]
**Bug Description**
Linux：

gyp ERR! cwd /home/ksl/node_modules/ffi/node_modules/ref
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/ksl/package.json'
npm 
WARN ksl No description
npm
WARN ksl No repository field.
npm WARN ksl No README data
npm WARN ksl No license field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref@1.3.5 install: `node-gyp 
rebuild`
npm ERR! Exit status 1npm ERR! 
npm ERR! Failed at the ref@1.3.5 install script.npm ERR! This is probably not a problem with npm. There is likely additional 
logging output  above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ksl/.npm/_logs/2019-12-13T17_33_58_035Z-debug.log

windows：

C:\Windows\system32\node_modules\ref>if not defined npm_config_node_gyp (node "D
:\Software\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\.
.\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Software\node
js\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
MSBUILD : error MSB1009: 项目文件不存在。
开关:build/binding.sln
gyp ERR! build error
gyp ERR! stack Error: `D:\Software\Microsoft Visual Studio\2017\Community\MSBuil
d\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Software\nodejs\node_modules\npm\n
ode_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:272:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\Software\\nodejs\\node.exe" "D:\\Software\\nodejs\\node_mo
dules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Windows\system32\node_modules\ref
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN system32@1.0.0 No description
npm WARN system32@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref@1.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ref@1.3.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Software\nodejs\node_cache\_logs\2019-12-13T09_41_22_345Z-debug.
log

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: linux：NeoKylin 7.0 server  python-2.7.5-58.el7.x86_64、make-3.82-23.el7.x86_64
          windows7：Python 2.7.4   Visual Studio 2017
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by guanshengliang** [comment]
Looks like a question for nodeJs, you can ask @StoneT2000

**Comment by StoneT2000** [comment]
@gaosong1206 
Please try running the following
‘node-gyp rebuild’
Then ‘npm install’

If the above doesn’t work, try running rebuild again and then ’npm clean-install’

**Comment by gaosong1206** [comment]
> @gaosong1206
> Please try running the following
> `node-gyp rebuild`
> Then `npm install`
> 
> If the above doesn’t work, try running rebuild again and then `npm clean-install`

**Comment by sytpb** [comment]
> node-gyp rebuild

you means   npm install node-gyp ???

**Comment by StoneT2000** [comment]
node-gyp should be installed already, it is a package dependency

**Comment by sytpb** [comment]
> node-gyp should be installed already, it is a package dependency
my package.json 

"dependencies": {
    "body-parser": "^1.18.3",
    "cookie-parser": "~1.4.3",

    **"node-gyp": "^6.1.0",**

**Comment by StoneT2000** [comment]
yep, running npm install should have node-gyp installed along with it

**Comment by sytpb** [comment]
> yep, running npm install should have node-gyp installed along with it

but I still got the error  when run 'npm install td-connector'

gyp ERR! System Linux 3.10.0-862.el7.x86_64
gyp ERR! command "/root/sys/node-v12.16.2-linux-x64/bin/node" "/root/sys/node-v12.16.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/tst/wework_server/node_modules/ref
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref@1.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ref@1.3.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-04T08_21_44_621Z-debug.log

**Comment by sytpb** [comment]
my node-gpy  version is  6.1.0 . .. 
npm list node-gyp   got the info as below ......
wework_nodejs@0.1.1 /root/tst/wework_server
└── node-gyp@6.1.0

**Comment by StoneT2000** [comment]
Oh then can you try npm install -g node-gyp, the error log shows that it’s not 6.1.0 for some reason

**Comment by sytpb** [comment]
> Oh then can you try npm install -g node-gyp, the error log shows that it’s not 6.1.0 for some reason which might be because you have a globally installed version that’s different


npm install -g node-gyp    done 

npm install td-connector  got logs  as below ... 

../src/binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE {anonymous}::WriteObject(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/binding.cc:222:43: **error**: no matching function for call to ‘v8::Value::BooleanValue()’

......................

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/sys/node-v12.16.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 3.10.0-862.el7.x86_64
gyp ERR! command "/root/sys/node-v12.16.2-linux-x64/bin/node" "/root/sys/node-v12.16.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/tst/wework_server/node_modules/ref
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref@1.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ref@1.3.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I don't know what 's wrong . .......

**Comment by StoneT2000** [comment]
Ok i just double checked the node-fi package (which usually causes this error because it sure node-gyp) and it’s likely that you will need to downgrade node 10. Can you try running with node 10? First remove node_modules folder from your local directory and try running npm install and use node 10

**Comment by sytpb** [comment]
ok,    I have a try now ....   :)

**Comment by sytpb** [comment]
> Ok i just double checked the node-fi package (which usually causes this error because it sure node-gyp) and it’s likely that you will need to downgrade node 10. Can you try running with node 10? First remove node_modules folder from your local directory and try running npm install and use node 10

ok, I have a try now ....   :)

**Comment by sytpb** [comment]
> Ok i just double checked the node-fi package (which usually causes this error because it sure node-gyp) and it’s likely that you will need to downgrade node 10. Can you try running with node 10? First remove node_modules folder from your local directory and try running npm install and use node 10


Thanks a lot ,    td-connector installed succeed with Node V10.20 .
