### ISSUE TITLE
Unable to plot GIS data from TDengine with Grafana

### ISSUE THREAD

**Issue by stevel032** [taosdata/TDengine#9183]
We are encountering a problem of not being able to plot GIS data from TDengine with Grafana. We suspect there's a problem with data retrieval format.

The query looks like:

```
select ts,  gps_lat as lat, gps_lon as lon  from gpslogger.gpsloggerdevice where ts >=$from and ts < $to
```

The response looks like:
```
Object
  request:Object
    url:"api/datasources/proxy/1/grafana/query"
    data:Array[1]
      0:Object
        refId:"A"
        alias:""
        sql:"select ts,  gps_lat as lat, gps_lon as lon  from gpslogger.gpsloggerdevice where ts >='2021-12-09T04:37:50.326Z' and ts < '2021-12-09T04:42:50.326Z'"
    method:"POST"
    hideFromInspector:false
  response:Array[266]
    0:Object
      refId:"A"
      target:"{lon:-122.296200667}"
      datapoints:Array[6]
        0:Array[37.8893955,1639024670648]
        1:Array[37.8893955,1639024670657]
        2:Array[37.8893955,1639024670665]
        3:Array[37.8893955,1639024670677]
        4:Array[37.8893955,1639024670695]
        5:Array[37.8893955,1639024670704]
```

Enclosed is a screenshot:

<img width="1658" alt="Screen Shot 2021-12-08 at 8 46 02 PM" src="https://user-images.githubusercontent.com/55261196/146619105-eea0f593-4ca2-49b2-acef-8892703c0349.png">

More data/information to follow.

**Comment by afwerar** [comment]
He can install the latest plug-ins first, and then do so：
grafana-cli   --pluginUrl https://github.com/taosdata/grafanaplugin/releases/download/v3.1.3/tdengine-datasource-3.1.3.zip  plugins install tdengine-datasource.
![GIF 2021-11-9 22-50-58](https://user-images.githubusercontent.com/20500927/146622512-7fb0a01e-1ab9-4c71-8315-3fe531c65f14.gif)

**Comment by stevel032** [comment]
Thank you @afwerar for the super fast response. We'll be getting some partial data, and let us verify again with the data and see if everything would indeed work as expected.

**Comment by cdiwadkar16** [comment]
The data can be found here: https://drive.google.com/file/d/1nFFRKkTjv9kdVpj-zEfT0TuIsofdooGL/view?usp=sharing
Note that this is a pretty large file - 1.4G CSV file

**Comment by cdiwadkar16** [comment]
Other points to note here per customer:
1. The geo coordinates can be plotted in another Grafana plugin called Trackmap (https://grafana.com/grafana/plugins/alexandra-trackmap-panel/)
![trackmap](https://user-images.githubusercontent.com/94201190/146702870-c7e99b22-9a92-4789-a5d9-911a22d6de33.png)


2. The geo coordinates cannot be plotted in the core plugin called Geomap.
![geomap](https://user-images.githubusercontent.com/94201190/146702903-0554d4da-90f8-4a14-9bcc-37374708ccd6.png)

In both cases customer seems to be selecting "Time series" for the "Format As:" field when setting up the panel in Grafana.

**Comment by afwerar** [comment]
Ok, let me check it.

**Comment by afwerar** [comment]
Geomap has poor performance when processing large amounts of data. It is recommended that the number of display points is less than 1000.
When displaying large amounts of data coordinates, maybe Trackmap is a better choice.
Table data must be used in Geomap, and there are two other ways to display data:
![image](https://user-images.githubusercontent.com/20500927/146718527-cf896efd-0ee7-40c0-a9bb-476a2ee2204e.png)
![image](https://user-images.githubusercontent.com/20500927/146718555-51df6f02-6a43-4275-852d-92ae67ceafe5.png)

**Comment by zitsen** [comment]
Solved.
