### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by kaybinwong** [taosdata/TDengine#9188]
**Bug Description**
Segmentation fault after trying connect to server(win10 -> centos7)

**To Reproduce**
no log after changed `debugFalg` to 143
```
==================================================
                new log file                      
==================================================
```
**Expected Behavior**
A clear result to connect server

**Screenshots**
![image](https://user-images.githubusercontent.com/5570216/146643020-62c45948-20e2-49c3-abb8-24836580c0e6.png)

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
Centos 7.9
 - Memory, CPU, current Disk Space
 32G / 12C / 2T
 - TDengine Version [e.g. 1.6.1.7]
client and server are 2.2.2.10
**Additional Context**
nothing more

**Comment by yu285** [comment]
请添加一下微信15652223354，我们帮您排查一下
