### ISSUE TITLE
TDengine两天使用感想

### ISSUE THREAD

**Issue by xincan** [taosdata/TDengine#92]
1：强烈建议支持win10、winserver平台；
2：针对springboot做orm框架；
3：尽快支持docker；
4：对于驱动jar包尽快提交maven,毕竟java开发人员基数大；
5：文档尽量详细，创建用户文档太过于简单，从安装到试用基本上步步是坑（个人水平太垃圾了），然后我拉着侯江燚，侯大牛帮忙搞定，这里有一个致命问题 ， **taos -uroot -paaa也能登录（默认密码是taosdata, aaa是我随便写的，没有改配置文件）**；taos -s 'create user test pass 'test'';语句报错，特殊字符的处理方式请优化并加以说明；创建完用户后quit;或者exit退出，重新用taos -uroot -paaa登录，然后show users;能够看到所有用户，然后我drop user test;,如果是别人创建的用户我给删掉了，并且别人在程序中用到该用户那就game over了；

**Comment by xincan** [comment]
点错了

**Comment by coder-chriswang** [comment]
@xincan 我昨天在Linux搭建好TDengine之后，体验了一把，感觉很爽。
然后就基于Springboot搭建了一个工程项目，想着能不能将数据插入，查询等流程打通，但缺少dll文件，无奈啊，只能等待了

**Comment by xincan** [comment]
@coder-chriswang bug还挺多的，毕竟刚刚开源，文档等都不太完善

**Comment by vzhougm** [comment]
> @xincan 我昨天在Linux搭建好TDengine之后，体验了一把，感觉很爽。
> 然后就基于Springboot搭建了一个工程项目，想着能不能将数据插入，查询等流程打通，但缺少dll文件，无奈啊，只能等待了

饥饿营销吗？😂

**Comment by jtao1735** [comment]
谢谢你的好建议，我们继续努力

**Comment by hzcheng** [comment]
@xincan 密码问题已经解决，非常感谢关注

**Comment by tedwuusa** [comment]
> 3：尽快支持docker；

我做了一个Docker Image，用two stage build最小化才72MB，有兴趣可以关注：

https://github.com/streamlytic/TDengine-Docker

**Comment by Pingmin** [comment]
> @xincan 密码问题已经解决，非常感谢关注

@hzcheng 请把你用 git 提交所用的邮箱加到你的 GitHub 帐户中去，或用你的 GitHub 帐户邮件来提交，这样我们才能看到你的相关动态

**Comment by xincan** [comment]
对于java集成jdbc来说，在数据库安装包中找到的jdbcdriver，手动打包失败，只能在git上下载源码，进行编译后，install才能在本地的maven仓库中看到，于是乎dependency到springboot然后写个小demo却发现win10系统缺少涛思动态库，而官网的文档中有对应win的说明，就是找不到动态库的位置，应该是安装完tdengine的客户端之后才能在system32中看到，目前好像没有支持win10，所以无奈只能等待

**Comment by xincan** [comment]
每一次查询一个sql的时候，我都需要做一次数据库use，对于java开发人员来说，这是个负担，我们只好通过向aop+自定义注解去处理，对于微服务来说，每一个微服务只关心自己做的一件事，很少涉及一个微服务连多个数据库，所以，能不能做好自动处理数据库的选择

**Comment by zuozhiwen** [comment]
@xincan 关键你就算进行到使用上动态链接库下面的路还是很长。比如1.连接池问题 2.是否兼容现在主流的ORM比如mybatis

**Comment by jtao1735** [comment]
> 每一次查询一个sql的时候，我都需要做一次数据库use，对于java开发人员来说，这是个负担，我们只好通过向aop+自定义注解去处理，对于微服务来说，每一个微服务只关心自己做的一件事，很少涉及一个微服务连多个数据库，所以，能不能做好自动处理数据库的选择

TDengine容许在表名前加DB名字，这样你不用每次都用use. 比如 db1.table1, 就是指db1中的表table1, 不管你现在选择的库是什么

**Comment by xincan** [comment]
@jtao1735 谢谢陶总解答，好像官网的文档里面没有介绍？，是我没有看到吗？

**Comment by xincan** [comment]
@zuozhiwen 其实老早就知道没有类似orm的支持，但是听说后续会支持的

**Comment by dbsxdbsx** [comment]
目前好像是windows支持客户端，但是不支持启动服务，那岂不是还得另开个linux服务器了。

**Comment by boostbob** [comment]
还没法用，再等等.
