### ISSUE TITLE
Cluster TSC error， node offline

### ISSUE THREAD

**Issue by RuizheIsaf** [taosdata/TDengine#9270]
目前是在vmware中装的两个虚拟机模拟下集群部署，
按照教程安装后现在可以在两台虚拟机中操作同一个数据表，但是查看“show dnodes；”的时候从节点是“offline”，查看“show mnodes;”的时候也找不到从节点...
具体情况和日志见下图
![q1](https://user-images.githubusercontent.com/92136250/147030620-ae6cad1d-9263-4097-b8bb-f246f4f385e0.png)
![q2](https://user-images.githubusercontent.com/92136250/147030625-9af139cf-ffa6-4578-ab86-419e9be74cc5.png)
![q3](https://user-images.githubusercontent.com/92136250/147030626-65912dc7-c12f-4462-963d-3e5049d177b4.png)

**Comment by yu285** [comment]
请根据官网文档搭建，确保两个节点可以互相访问，端口打开

mnode默认确实为1，这个正常

**Comment by sunshine-smdbs** [comment]
因为节点2，在配置firstEp之前，已经单独启动过。所以节点2成为了单独的集群。因此在create dnode的过程中，无法添加到节点1的集群当中。
清除掉节点2的已有数据，即可解决问题。
