### ISSUE TITLE
SQL query response looks different in Taos CLI vs. Grafana

### ISSUE THREAD

**Issue by cdiwadkar16** [taosdata/TDengine#9297]
For this query "select ts, age, gender, emotion from gpslogger.upboardoakd1 order by ts desc limit 1 ;"

User gets the following when querying taos directly

taos> select ts, age, gender, emotion from gpslogger.upboardoakd1 order by ts de
sc limit 1 ;
           ts            |     age     |  gender  |  emotion   |
================================================================
 2021-12-20 23:51:03.702 |          22 | Male     | neutral    |

In Grafana, the user gets the following:

![image](https://user-images.githubusercontent.com/94201190/147121281-4cd374e2-6d0f-4d87-a2b3-a1eb5bad0191.png)

![image](https://user-images.githubusercontent.com/94201190/147121785-2c322fa3-9620-448a-9d07-3bf9679acfc4.png)

That is, when the same query is executed in Grafana, the user gets ts and age (1st and 2nd column). But gender and emotion (3rd and 4th column) shows up as a header for 2nd column.

Note: Please ignore the fact that the actual values returned are different. This is because the query was executed at different times.

**Comment by cdiwadkar16** [comment]
Table description:

             Field              |         Type         |   Length    |   Note   |
=================================================================================
 ts                             | TIMESTAMP            |           8 |          |
 age                            | INT                  |           4 |          |
 gender                         | BINARY               |           8 |          |
 emotion                        | BINARY               |          10 |          |
 trip_type                      | BINARY               |          20 | TAG      |
 vehicle_type                   | BINARY               |          20 | TAG      |
 model                          | BINARY               |          20 | TAG      |
 brand                          | BINARY               |          20 | TAG      |
 seats                          | INT                  |           4 | TAG      |
 mode                           | BINARY               |           6 | TAG      |
 logger_location                | BINARY               |          20 | TAG      |
 owner                          | BINARY               |          20 | TAG      |
 tripid                         | BINARY               |          20 | TAG      |
 trip_desc                      | BINARY               |          40 | TAG      |
 hardware                       | BINARY               |          40 | TAG      |

**Comment by zitsen** [comment]
In this case, if want to query data that not time-series, please choose the query format **Table** instead of **Time Series**.

![tdengine-query-as-table](https://user-images.githubusercontent.com/3772803/147510078-57ac86b9-ee22-40c0-8ff2-6c342d15699f.png)

**Comment by cdiwadkar16** [comment]
After upgrading to 2.4.0, he is getting the following errors:

INstalled 2.4.0 and grafana plugin 3.1.3 but now getting errors starting the server, please see below

vibhu@vibhu-UP-CHT01:~$ taosd
12/29 18:21:07.035759 00002433 DND start to initialize TDengine
12/29 18:21:07.036019 00002433 DND step:dnode-tfile is initialized
12/29 18:21:07.036080 00002433 DND step:dnode-rpc is initialized
12/29 18:21:07.036961 00002433 UTL localEp is: vibhu-UP-CHT01:6030
12/29 18:21:07.037829 00002433 UTL WARN timezone not configured, set to system default:America/Los_Angeles (PDT, -0700)
12/29 18:21:07.038132 00002433 UTL WARN locale not configured, set to system default:en_US.UTF-8
12/29 18:21:07.038204 00002433 UTL WARN charset not configured, set to system default:UTF-8
12/29 18:21:07.038329 00002433 UTL    check global cfg completed
12/29 18:21:07.038362 00002433 UTL ==================================
12/29 18:21:07.038391 00002433 UTL    taos config & system info:
12/29 18:21:07.038420 00002433 UTL ==================================
12/29 18:21:07.038448 00002433 UTL  firstEp:                h1.taosdata.com:6030
12/29 18:21:07.038477 00002433 UTL  secondEp:               vibhu-UP-CHT01:6030
12/29 18:21:07.038505 00002433 UTL  fqdn:                   vibhu-UP-CHT01
12/29 18:21:07.038534 00002433 UTL  serverPort:             6030
12/29 18:21:07.038616 00002433 UTL  configDir:              /etc/taos
12/29 18:21:07.038683 00002433 UTL  logDir:                 /var/log/taos
12/29 18:21:07.038738 00002433 UTL  scriptDir:              /etc/taos
12/29 18:21:07.038794 00002433 UTL  arbitrator:              
12/29 18:21:07.038851 00002433 UTL  numOfThreadsPerCore:    1.000000
12/29 18:21:07.038967 00002433 UTL  numOfCommitThreads:     4
12/29 18:21:07.039023 00002433 UTL  ratioOfQueryCores:      1.000000
12/29 18:21:07.039080 00002433 UTL  maxNumOfDistinctRes:    10000000
12/29 18:21:07.039149 00002433 UTL  numOfMnodes:            1
12/29 18:21:07.039207 00002433 UTL  vnodeBak:               1
12/29 18:21:07.039264 00002433 UTL  telemetryReporting:     1
12/29 18:21:07.039346 00002433 UTL  dnodeNopLoop:           0
12/29 18:21:07.039402 00002433 UTL  balance:                1
12/29 18:21:07.039458 00002433 UTL  balanceInterval:        300
12/29 18:21:07.039528 00002433 UTL  role:                   0
12/29 18:21:07.039601 00002433 UTL  maxTmrCtrl:             512
12/29 18:21:07.039658 00002433 UTL  monitorInterval:        30(s)
12/29 18:21:07.039713 00002433 UTL  monitorReplica:         1
12/29 18:21:07.039782 00002433 UTL  offlineThreshold:       864000(s)
12/29 18:21:07.039840 00002433 UTL  rpcTimer:               300(ms)
12/29 18:21:07.039897 00002433 UTL  rpcMaxTime:             600(s)
12/29 18:21:07.039967 00002433 UTL  rpcForceTcp:            0
12/29 18:21:07.040034 00002433 UTL  statusInterval:         1(s)
12/29 18:21:07.040091 00002433 UTL  shellActivityTimer:     3(s)
12/29 18:21:07.040146 00002433 UTL  minSlidingTime:         10(ms)
12/29 18:21:07.040215 00002433 UTL  minIntervalTime:        1(ms)
12/29 18:21:07.040271 00002433 UTL  maxStreamCompDelay:     20000(ms)
12/29 18:21:07.040325 00002433 UTL  maxFirstStreamCompDelay:10000(ms)
12/29 18:21:07.040380 00002433 UTL  retryStreamCompDelay:   10000(ms)
12/29 18:21:07.040435 00002433 UTL  streamCompDelayRatio:   0.100000
12/29 18:21:07.040512 00002433 UTL  maxVgroupsPerDb:        0
12/29 18:21:07.040568 00002433 UTL  maxTablesPerVnode:      1000000
12/29 18:21:07.040624 00002433 UTL  minTablesPerVnode:      1000
12/29 18:21:07.040680 00002433 UTL  tableIncStepPerVnode:   1000
12/29 18:21:07.040750 00002433 UTL  cache:                  16(Mb)
12/29 18:21:07.040807 00002433 UTL  blocks:                 6
12/29 18:21:07.040877 00002433 UTL  days:                   10
12/29 18:21:07.041596 00002433 UTL  keep:                   3650
12/29 18:21:07.041659 00002433 UTL  minRows:                100
12/29 18:21:07.041699 00002433 UTL  maxRows:                4096
12/29 18:21:07.041737 00002433 UTL  precision:              0
12/29 18:21:07.041774 00002433 UTL  comp:                   2
12/29 18:21:07.041813 00002433 UTL  walLevel:               1
12/29 18:21:07.041849 00002433 UTL  fsync:                  3000
12/29 18:21:07.041888 00002433 UTL  replica:                1
12/29 18:21:07.041968 00002433 UTL  partitions:             4
12/29 18:21:07.042006 00002433 UTL  quorum:                 1
12/29 18:21:07.042044 00002433 UTL  update:                 0
12/29 18:21:07.042149 00002433 UTL  cachelast:              0
12/29 18:21:07.042188 00002433 UTL  compressMsgSize:        524288
12/29 18:21:07.042228 00002433 UTL  compressColData:        -1
12/29 18:21:07.042265 00002433 UTL  maxSQLLength:           1048576(byte)
12/29 18:21:07.042298 00002433 UTL  maxWildCardsLength:     100(byte)
12/29 18:21:07.042335 00002433 UTL  maxRegexStringLen:      128(byte)
12/29 18:21:07.042374 00002433 UTL  maxNumOfOrderedRes:     1000000
12/29 18:21:07.042411 00002433 UTL  queryBufferSize:        -1(byte)
12/29 18:21:07.042443 00002433 UTL  retrieveBlockingModel:  0
12/29 18:21:07.042480 00002433 UTL  keepColumnName:         1
12/29 18:21:07.042518 00002433 UTL  timezone:               America/Los_Angeles (PDT, -0700)
12/29 18:21:07.042555 00002433 UTL  locale:                 en_US.UTF-8
12/29 18:21:07.042593 00002433 UTL  charset:                UTF-8
12/29 18:21:07.042631 00002433 UTL  maxShellConns:          50000
12/29 18:21:07.042669 00002433 UTL  maxConnections:         5000
12/29 18:21:07.042707 00002433 UTL  minimalLogDirGB:        1.000000(GB)
12/29 18:21:07.042753 00002433 UTL  minimalTmpDirGB:        1.000000(GB)
12/29 18:21:07.042794 00002433 UTL  minimalDataDirGB:       2.000000(GB)
12/29 18:21:07.042833 00002433 UTL  mnodeEqualVnodeNum:     4
12/29 18:21:07.042870 00002433 UTL  flowctrl:               1
12/29 18:21:07.042907 00002433 UTL  slaveQuery:             1
12/29 18:21:07.042945 00002433 UTL  adjustMaster:           1
12/29 18:21:07.042982 00002433 UTL  http:                   1
12/29 18:21:07.043021 00002433 UTL  mqtt:                   0
12/29 18:21:07.043060 00002433 UTL  monitor:                1
12/29 18:21:07.043096 00002433 UTL  stream:                 1
12/29 18:21:07.043134 00002433 UTL  topicBinaryLen:         16000
12/29 18:21:07.043171 00002433 UTL  httpEnableRecordSql:    0
12/29 18:21:07.043208 00002433 UTL  telegrafUseFieldNum:    0
12/29 18:21:07.043245 00002433 UTL  httpMaxThreads:         2
12/29 18:21:07.043283 00002433 UTL  restfulRowLimit:        10240
12/29 18:21:07.043321 00002433 UTL  httpDbNameMandatory:    0
12/29 18:21:07.043357 00002433 UTL  httpKeepAlive:          30000
12/29 18:21:07.043396 00002433 UTL  numOfLogLines:          10000000
12/29 18:21:07.043432 00002433 UTL  logKeepDays:            0
12/29 18:21:07.043468 00002433 UTL  asyncLog:               1
12/29 18:21:07.043505 00002433 UTL  debugFlag:              0
12/29 18:21:07.043545 00002433 UTL  mDebugFlag:             131
12/29 18:21:07.043583 00002433 UTL  dDebugFlag:             135
12/29 18:21:07.043620 00002433 UTL  sDebugFlag:             135
12/29 18:21:07.043659 00002433 UTL  wDebugFlag:             135
12/29 18:21:07.043697 00002433 UTL  sdbDebugFlag:           131
12/29 18:21:07.043733 00002433 UTL  rpcDebugFlag:           131
12/29 18:21:07.043771 00002433 UTL  tmrDebugFlag:           131
12/29 18:21:07.043810 00002433 UTL  cDebugFlag:             131
12/29 18:21:07.043848 00002433 UTL  jniDebugFlag:           131
12/29 18:21:07.043884 00002433 UTL  odbcDebugFlag:          131
12/29 18:21:07.043922 00002433 UTL  uDebugFlag:             131
12/29 18:21:07.043960 00002433 UTL  httpDebugFlag:          131
12/29 18:21:07.043999 00002433 UTL  mqttDebugFlag:          131
12/29 18:21:07.044036 00002433 UTL  monDebugFlag:           131
12/29 18:21:07.044073 00002433 UTL  qDebugFlag:             131
12/29 18:21:07.044109 00002433 UTL  vDebugFlag:             135
12/29 18:21:07.044148 00002433 UTL  tsdbDebugFlag:          131
12/29 18:21:07.044188 00002433 UTL  cqDebugFlag:            131
12/29 18:21:07.044226 00002433 UTL  enableRecordSql:        0
12/29 18:21:07.044264 00002433 UTL  enableCoreFile:         0
12/29 18:21:07.044301 00002433 UTL  gitinfo:                2b6e56a95590f05120292b9b57cb32b9d9a1a1bc
12/29 18:21:07.044354 00002433 UTL  gitinfoOfInternal:      NULL
12/29 18:21:07.044392 00002433 UTL  buildinfo:              Built at 2021-12-24 21:39
12/29 18:21:07.044431 00002433 UTL  version:                2.4.0.0
12/29 18:21:07.044493 00002433 UTL  maxBinaryDisplayWidth:  30
12/29 18:21:07.044531 00002433 UTL  tempDir:                /tmp/
12/29 18:21:07.044570 00002433 UTL  tsdbMetaCompactRatio:   0
12/29 18:21:07.044606 00002433 UTL  deadLockKillQuery:      0
12/29 18:21:07.044643 00002433 UTL  clientMerge:            0
12/29 18:21:07.044679 00002433 UTL  defaultJSONStrType:     nchar
12/29 18:21:07.044716 00002433 UTL  smlChildTableName:      
12/29 18:21:07.044753 00002433 UTL  smlTagNullName:         _tag_null
12/29 18:21:07.044790 00002433 UTL  walFlushSize:           1024(Mb)
12/29 18:21:07.044833 00002433 UTL  os pageSize:            4096(KB)
12/29 18:21:07.044872 00002433 UTL  os openMax:             1024
12/29 18:21:07.044933 00002433 UTL  os streamMax:           16
12/29 18:21:07.044970 00002433 UTL  os numOfCores:          4
12/29 18:21:07.045007 00002433 UTL  os totalMemory:         3338(MB)
12/29 18:21:07.045054 00002433 UTL  os sysname:             Linux
12/29 18:21:07.045091 00002433 UTL  os nodename:            vibhu-UP-CHT01
12/29 18:21:07.045127 00002433 UTL  os release:             5.4.0-1-generic
12/29 18:21:07.045163 00002433 UTL  os version:             #0~upboard4-Ubuntu SMP Thu Sep 23 01:47:49 UTC 2021
12/29 18:21:07.045199 00002433 UTL  os machine:             x86_64
12/29 18:21:07.045240 00002433 UTL  dataDir: /var/lib/taos
12/29 18:21:07.045278 00002433 UTL ==================================
12/29 18:21:07.045316 00002433 DND step:dnode-globalcfg is initialized
12/29 18:21:07.045548 00002433 TFS ERROR failed to mount /var/lib/taos to FS since no R/W access rights
12/29 18:21:07.045737 00002433 DND ERROR failed to init TFS since tfs invalid mount config
12/29 18:21:07.045905 00002433 DND Failed to start TDengine, please check the log at:/var/log/taos


vibhu@vibhu-UP-CHT01:~$ cd /var/log/taos/
vibhu@vibhu-UP-CHT01:/var/log/taos$ ls
taosadapter_2021_12_29_00_00.log  taosdlog.0  taosinfo.0  taoslog0.0  taoslog1.0
vibhu@vibhu-UP-CHT01:/var/log/taos$ tail -f taosadapter_2021_12_29_00_00.log
12/29 18:18:13.074000 00001347 TAOS_ADAPTER info "init plugin collectd/v1" model=plugin
12/29 18:18:13.077828 00001347 TAOS_ADAPTER info "init plugin influxdb/v1" model=plugin
12/29 18:18:13.078322 00001347 TAOS_ADAPTER info "init plugin node_exporter/v1" model=plugin
12/29 18:18:13.083617 00001347 TAOS_ADAPTER info "node_exporter disabled" model=NodeExporter
12/29 18:18:13.083653 00001347 TAOS_ADAPTER info "init plugin opentsdb/v1" model=plugin
12/29 18:18:13.084089 00001347 TAOS_ADAPTER info "init plugin opentsdb_telnet/v1" model=plugin
12/29 18:18:13.086816 00001347 TAOS_ADAPTER info "opentsdb_telnet disabled" model=opentsdb_telnet
12/29 18:18:13.086848 00001347 TAOS_ADAPTER info "all plugin init finish" model=plugin
12/29 18:18:13.089818 00001347 TAOS_ADAPTER info "UDP listening on "[::]:6044"" model=statsd
12/29 18:18:13.089962 00001347 TAOS_ADAPTER info "Started the statsd service on ":6044"" model=statsd

**Comment by zitsen** [comment]
@cdiwadkar16 In ubuntu, better to start taosd with `sudo systemctl start taosd`. The error ` ERROR failed to mount /var/lib/taos to FS since no R/W access rights` caused when you start taosd by a common user.

**Comment by cdiwadkar16** [comment]
This issue is now resolved after upgrading Grafana to 8.3.3, TDEngine to 2.4.0 and Taosdata Grafana plugin to 3.1.3.
