### ISSUE TITLE
HTTP server on port 6041 does not start - TDEngine 2.3.2.0

### ISSUE THREAD

**Issue by cdiwadkar16** [taosdata/TDengine#9298]
When TDEngine 2.3.2.0 starts, it does not start the http server on port 6041.
[taosdlog.0.txt](https://github.com/taosdata/TDengine/files/7765828/taosdlog.0.txt)
[taosinfo.0.txt](https://github.com/taosdata/TDengine/files/7765829/taosinfo.0.txt)
[taoslog0.0.txt](https://github.com/taosdata/TDengine/files/7765830/taoslog0.0.txt)

- Linux osboxes 5.11.0-41-generic #45~20.04.1-Ubuntu SMP Wed Nov 10 10:20:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- TDengine Version 2.3.2.0

**Comment by sangshuduo** [comment]
Could you please try the latest version?

**Comment by cdiwadkar16** [comment]
Hi Shuduo, actually I upgraded to 2.3.5.0 and it is fine! Thank you!
