### ISSUE TITLE
throw “string data overflow” error when i insert data. 

### ISSUE THREAD

**Issue by schenton** [taosdata/TDengine#930]
when i insert data with this sql below,  it can success.
taos> INSERT INTO seisflink.GE_BOAB__BHZ USING seismometer TAGS(GE, BOAB,-, BHZ) VALUES (1576480308495,16455) (1576480308545,16445);
Query OK, 0 row(s) affected (0.000750s)
==============================
but i only modified the tags(the third tag) value "-" to "--" , there was an error . the whole sql is below.
taos> INSERT INTO seisflink.GE_BOAB__BHZ USING seismometer TAGS(GE, BOAB,--, BHZ) VALUES (1576480308495,16455) (1576480308545,16445);
DB error: invalid SQL: syntax error near "--, bhz) values (1576480308495,16455) (1576480308545,16445);" (string data overflow)

**Comment by schenton** [comment]
Actually， in the pre-verison of taos,  the sql i mentioned above can insert data success.

**Comment by hjxilinx** [comment]
In handling the string data, you should use the **quoted string**. 
Therefore, the right SQL (if all tags are in string format) may be as follows:
> INSERT INTO seisflink.GE_BOAB__BHZ USING seismometer TAGS('GE', 'BOAB','--', 'BHZ') VALUES (1576480308495,16455) (1576480308545,16445);

The previous version does not apply the quote string check to the string(binary/nchar) data. But in the new version,  use the string without quoted in SQL string, the parsed result is UNDEFINED.

**Comment by schenton** [comment]
3q
