### ISSUE TITLE
 file descriptors are not released until the resources are used up

### ISSUE THREAD

**Issue by jrtkcoder** [taosdata/TDengine#931]
**Bug Description**
taosd后台服务运行异常，top查看，wa占用很高，taos客户端无法连接，lsof查看taosd进程,发现打开文件数量为65548，查看日志文件taosdlog.0，提示：Too many open files
**Screenshots**
![Uploading image.png…](https://rltest.oss-cn-hangzhou.aliyuncs.com/images/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20191217115905.png)

**Environment (please complete the following information):**
 - OS: Linux localhost.localdomain 3.10.0-957.10.1.el7.x86_64
 - Memory：4g, CPU：4核, current Disk Space：260G
 - TDengine Version [TDengine-1.6.4.3]

**Comment by hjxilinx** [comment]
This problem has been fixed in the develop branch, and will be merged to next released version.
