### ISSUE TITLE
1.6.4.3 RESTful no response 

### ISSUE THREAD

**Issue by Yurunsoft** [taosdata/TDengine#937]
**Bug Description**
接口传入 Auth 后，必然会导致卡死，没有任何信息返回。taosd 没有任何日志。

不传 Auth 信息能正常返回：

```js
{
    "status": "error",
    "code": 1011,
    "desc": "no auth info input"
}
```

1.6.4.3 在 WSL 有问题，虚拟机中正常。

之前在 WSL 使用 1.6.3.0 版本没有问题。

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: WSL
 - TDengine Version 1.6.4.3

**Additional Context**

**Comment by guanshengliang** [comment]
Has not been tested under wsl, I will consider recreating this problem in the near future

**Comment by guanshengliang** [comment]
新的2.0版本已经发布，您可以下载尝试。如果还有问题，您可以提一个新的issue
