### ISSUE TITLE
return NULL never run after assert(0)

### ISSUE THREAD

**Issue by misswhite** [taosdata/TDengine#938]
**Bug Description**
The function in question is taosProcessAlarmSignal( ) TDengine/src/os/linux/src/tlinux.c
The last 2 lines before "}", return NULL will never run because the function will exit at assert(0), so the function will have no return value, which is expected to be void *. Without a return value, it may result in undefined behavior. 

**Screenshots**
![image](https://user-images.githubusercontent.com/57583073/71047081-605fc200-2175-11ea-8030-0fd088e2edf6.png)

**Comment by misswhite** [comment]
please review this error

**Comment by hjxilinx** [comment]
Thanks. Already fix it in develop branch.
