### ISSUE TITLE
Node.js the "td2.0-connector" typescript d.ts file support

### ISSUE THREAD

**Issue by lilie008** [taosdata/TDengine#9380]
For node,can it support typescript's d.ts file？

**Comment by xleili** [comment]
I am not familiar with typescript， could please give some more explain about d.ts.  Why d.ts file is helpful?

**Comment by lilie008** [comment]
> 
这个解释的比较清楚，主要是前端的Js库对TypeScript的一个兼容
https://zhuanlan.zhihu.com/p/58123993

**Comment by xleili** [comment]
感谢你的建议。
d.ts file 不是可以用 
https://npmmirror.com/package/dtsmake
或者
# 从.ts生成d.ts
tsc --declaration my-file.ts
借助工具生成吗。需要我们另外在做开发吗？

**Comment by lilie008** [comment]
.ts到d.ts是可以用工具( babel、 typescript compiler)生成，但是.js并不能很好通过工具(dts-gen,dtsmake等)生成d.ts，会丢失一些类型。
现在第三方库比较通用的做法是不需要使用.ts完全重构原js库，仅需要维护开发对应对外暴露的声明文件，并添加@types前缀进行发布。
typescript项目能很方便的进行引入。

例如lodash
除了在https://www.npmjs.com/package/lodash提供js库外
还额外提供了d.ts的最新支持，前缀加上了@types
https://www.npmjs.com/package/@types/lodash

否则的话无法使用，只能考虑使用RESULTFUL进行连接

**Comment by lilie008** [comment]
> 感谢你的建议。 d.ts file 不是可以用
> 
> * https://npmmirror.com/package/dtsmake
> * 从.ts生成d.ts
>   tsc --declaration my-file.ts
>   借助工具生成吗。需要我们另外在做开发吗？

.ts到d.ts是可以用工具( babel、 typescript compiler)生成，但是.js并不能很好通过工具(dts-gen,dtsmake等)生成d.ts，会丢失一些类型。
现在第三方库比较通用的做法是不需要使用.ts完全重构原js库，仅需要维护开发对应对外暴露的声明文件，并添加**@types**前缀进行发布。
typescript项目能很方便的进行引入。

例如lodash
除了在[https://www.npmjs.com/package/lodash](https://www.npmjs.com/package/lodash)提供js库外
还额外提供了d.ts的最新支持，前缀加上了**@types**
[https://www.npmjs.com/package/@types/lodash](https://www.npmjs.com/package/@types/lodash)

否则的话无法使用，只能考虑使用RESULTFUL进行连接

**Comment by sangshuduo** [comment]
谢谢建议，TS 的更好支持会列入计划
