### ISSUE TITLE
client connect to tdengine successfully，but application couldn't 

### ISSUE THREAD

**Issue by wzm20191010** [taosdata/TDengine#9393]
部署应用的服务器单独用客户端连接可以连接上数据库服务器；  但是部署我们的应用程序上去 应用程序却连接不上数据库服务器 
报Caused by: java.sql.SQLException: TDengine ERROR (80000015): Unable to resolve FQDN的错

**Comment by yu285** [comment]
请确保客户端可以查询写入，这样才能证明配置无误。
