### ISSUE TITLE
磁盘空间使用量如何推算

### ISSUE THREAD

**Issue by effun** [taosdata/TDengine#94]
我打算用TDengine存放车辆GPS轨迹历史数据，超级表结构如下：
`create table his (
    gtime timestamp,
    lon int,
    lat int,
    speed tinyint,
    dir smallint,
    ltime timestamp)
  tags(vid binary(12))`

正常情况下每台车大约20秒记录一条数据，如果按10000辆车计算，粗算一天大约1.6G，但其它开销并没有计算在内，而数据库本身也没有找到可以查询磁盘占用量的指令，所以想请官方团队帮忙算一下实际的磁盘占用量，谢谢。

**Comment by hzcheng** [comment]
目前没有磁盘用量统计，后续会加。我们的数据默认存放在/var/lib/taos目录下，您可通过du -sh /var/lib/taos查看该文件夹的占用空间。不过这个空间并不完全准确，因为tdengine服务默认会在每个vnode中占用一个log文件，是WAL的日志文件，这个文件大小是固定的，正常关闭服务后这个文件会被删除。因此比较准确的空间统计是在正常停止TDengine服务后运行du -sh /var/lib/taos.

**Comment by effun** [comment]
@hzcheng 感谢回复
现在库里的记录数有280万+，整个taos文件夹987M，共有9个日志文件，除去日志文件大约105M，平均每条记录约40+字节，这样算下来还是差不多的。
