### ISSUE TITLE
No data is available for encoding 936.

### ISSUE THREAD

**Issue by weiwxg** [taosdata/TDengine#9402]
当表中存在列存储中文内容时，查询报以上错误。 

同时通过`Taos Shell` 查询该列中文内容不显示（服务器上查询是可以显示内容的）。

![1640587985(1)](https://user-images.githubusercontent.com/24971860/147443514-bdcf624a-c216-4b52-98b5-bda2823d79f7.png)

看起来好像是查询中文内容无法编码的问题，请问应该如何处理？

**Comment by arielyang** [comment]
看看最新版本还有这个问题吗？不知道问题是否已经解决

**Comment by arielyang** [comment]
This issue was closed because it has been inactive for too many days.
