### ISSUE TITLE
String data overflow error - when sample collection rate increased from 1Hz to 10Hz

### ISSUE THREAD

**Issue by cdiwadkar16** [taosdata/TDengine#9426]
TDEngine Version 2.1.6

taos.error.ProgrammingError: [0x0216]: invalid operation: '23:18:39.500000' (string data overflow)

This happens when i increase the GPS sample collection rate from 1 hZ to 10 Hz

Log:
vibhu@vibhu-UP-CHT01:~$ python3 /home/vibhu/up-board-share/01-python-BerryIMU-gyro-accel-compass-filters-car-taosdb-upboard/berryIMU-Gforce-TPA-GPS-taosdb.py

Found BerryIMUv3 (LSM6DSL and LIS3MDL)
Parse error: ('could not parse data', '7C\n')
2021-12-25 23:18:45.884879-08:00
2021-12-25 23:18:45.884879
1640474326053,45.00,45.00, 0.28, 0.28, 0.28,37.90,37.90,45.00,45.00,31.39,31.39,0.000244,0.000244,0.000244,0.0,0.00,0.00,'','',0.0,'',0.0,'',0.0
parseFlagError :  0
 inserting
2021-12-25 23:18:46.067093-08:00
2021-12-25 23:18:46.067093
1640474326068,45.00,45.00,-0.19,-0.19,-0.19,41.97,41.97,45.00,45.00,39.14,39.14,0.000244,0.000244,0.000244,0.0,0.00,0.00,'','',0.0,'',0.0,'',0.0
parseFlagError :  0
 inserting
2021-12-25 23:18:46.074134-08:00
2021-12-25 23:18:46.074134
1640474326074,45.00,45.00,-0.20,-0.20,-0.20,43.79,43.79,45.00,45.00,41.37,41.37,0.000244,0.000244,0.000244,0.0,0.00,0.00,'','',0.0,'',0.0,'',0.0
parseFlagError :  0
 inserting
2021-12-25 23:18:46.079571-08:00
2021-12-25 23:18:46.079571
1640474326079,-1.41,-1.41,-0.21,-0.21,-0.21,16.67,16.67,43.30,43.30,29.09,29.09,-0.01952,-0.056119999999999996,0.7940736,0.0,0.00,0.00,'','',0.0,'',0.0,'',0.0
parseFlagError :  0
 inserting
2021-12-25 23:18:46.085412-08:00
2021-12-25 23:18:46.085412
1640474326085,-1.36,-1.36,-0.20,-0.20,-0.20, 5.85, 5.85,32.05,32.05,21.89,21.89,-0.0308416,-0.0871568,1.29813856,0.0,0.00,0.00,'','',0.0,'',0.0,'',0.0
parseFlagError :  0
 inserting
2021-12-25 23:18:46.091860-08:00
2021-12-25 23:18:46.091860
1640474326092,-1.32,-1.32,-0.21,-0.21,-0.21, 1.54, 1.54,35.59,35.59,17.06,17.06,-0.03685376,-0.10763328,1.5975519360000001,0.0,0.00,0.00,'','',0.0,'',0.0,'',0.0
parseFlagError :  0
 inserting
2021-12-25 23:18:46.097765-08:00
2021-12-25 23:18:46.097765
1640474326098,-1.38,-1.38,-0.21,-0.21,-0.21,-0.21,-0.21,35.31,35.31,13.59,13.59,-0.04290105600000001,-0.11630796799999998,1.7754431616,0.0,0.00,0.00,'','',0.0,'',0.0,'',0.0
parseFlagError :  0
 inserting
2021-12-25 23:18:46.118624-08:00
2021-12-25 23:18:46.118624
1640474326119,-1.32,-1.32,-0.20,-0.20,-0.20,-0.88,-0.88,33.29,33.29,10.97,10.97,-0.0435038336,-0.1268807808,1.88744829696,0.0,0.00,0.00,'2021-12-25','23:18:39',37.88945366666667,'N',-122.29617033333334,'W',0.215
parseFlagError :  0
 inserting
2021-12-25 23:18:46.125071-08:00
2021-12-25 23:18:46.125071
1640474326125,-1.30,-1.30,-0.19,-0.19,-0.19,-1.12,-1.12,35.38,35.38, 8.42, 8.42,-0.04437358483456,-0.13146766848,1.951918578176,0.0,0.00,0.00,'2021-12-25','23:18:39',37.88945366666667,'N',-122.29617033333334,'W',0.215
parseFlagError :  0
 inserting
2021-12-25 23:18:46.136672-08:00
2021-12-25 23:18:46.136672
1640474326137,-1.28,-1.28,-0.18,-0.18,-0.18,-1.22,-1.22,38.32,38.32, 6.50, 6.50,-0.04437358483456,-0.132267801088,1.9914791469056001,0.0,0.00,0.00,'2021-12-25','23:18:39',37.88945366666667,'N',-122.29617033333334,'W',0.215
parseFlagError :  0
 inserting
2021-12-25 23:18:46.142080-08:00
2021-12-25 23:18:46.142080
1640474326142,-1.26,-1.26,-0.18,-0.18,-0.18,-1.24,-1.24,34.93,34.93, 5.06, 5.06,-0.04437358483456,-0.1358391230210048,2.01521548814336,0.0,0.00,0.00,'2021-12-25','23:18:39',37.88945366666667,'N',-122.29617033333334,'W',0.215
parseFlagError :  0
 inserting
2021-12-25 23:18:46.147160-08:00
2021-12-25 23:18:46.147160
1640474326147,-1.27,-1.27,-0.19,-0.19,-0.19,-1.26,-1.26,33.07,33.07, 3.97, 3.97,-0.044972950900736004,-0.13601984428756173,2.0317996928860165,0.0,0.00,0.00,'2021-12-25','23:18:39',37.88945366666667,'N',-122.29617033333334,'W',0.215
parseFlagError :  0
 inserting
2021-12-25 23:18:46.152639-08:00
2021-12-25 23:18:46.152639
1640474326153,-1.30,-1.30,-0.21,-0.21,-0.21,-1.29,-1.29,35.15,35.15, 3.10, 3.10,-0.04596670139455898,-0.13601984428756173,2.0326734157316095,0.0,0.00,0.00,'2021-12-25','23:18:39',37.88945366666667,'N',-122.29617033333334,'W',0.215
parseFlagError :  0
 inserting
2021-12-25 23:18:46.158741-08:00
2021-12-25 23:18:46.158741
1640474326159,-1.26,-1.26,-0.21,-0.21,-0.21,-1.28,-1.28,38.78,38.78, 2.40, 2.40,-0.044972950900736004,-0.13694378394352222,2.037004049438966,0.0,0.00,0.00,'2021-12-25','23:18:39',37.88945366666667,'N',-122.29617033333334,'W',0.215
parseFlagError :  0
 inserting
2021-12-25 23:18:46.167018-08:00
2021-12-25 23:18:46.167018
1640474326167,-1.26,-1.26,-0.23,-0.23,-0.23,-1.27,-1.27,38.28,38.28, 1.79, 1.79,-0.044972950900736004,-0.13694378394352222,2.041261629663379,0.0,0.00,0.00,'2021-12-25','23:18:39',37.88945366666667,'N',-122.29617033333334,'W',0.215
parseFlagError :  0
 inserting
2021-12-25 23:18:46.172335-08:00
2021-12-25 23:18:46.172335
1640474326172,-1.26,-1.26,-0.23,-0.23,-0.23,-1.27,-1.27,34.67,34.67, 1.32, 1.32,-0.044972950900736004,-0.13601984428756173,2.0466465777980276,0.0,0.00,0.00,'2021-12-25','23:18:39.500000',37.889454,'N',-122.29617033333334,'W',0.092
parseFlagError :  0
Traceback (most recent call last):
  File "/home/vibhu/up-board-share/01-python-BerryIMU-gyro-accel-compass-filters-car-taosdb-upboard/berryIMU-Gforce-TPA-GPS-taosdb.py", line 775, in <module>
    c1.execute(insertDataSQL)  
  File "/home/vibhu/.local/lib/python3.6/site-packages/taos/cursor.py", line 123, in execute
    self._result = taos_query(self._connection._conn, stmt)
  File "/home/vibhu/.local/lib/python3.6/site-packages/taos/cinterface.py", line 258, in taos_query
    raise ProgrammingError(errstr, errno)
taos.error.ProgrammingError: [0x0216]: invalid operation: '23:18:39.500000' (string data overflow)

**Comment by cdiwadkar16** [comment]
Note the following:

1. For this issue I have asked for sample data.
2. The super table schema is as follows:

create stable gpsloggerdevice (ts TIMESTAMP,ACCX_Angle FLOAT,ACCY_Angle FLOAT,GRYX_Angle FLOAT,GYRY_Angle FLOAT,GYRZ_Angle FLOAT,CFangleX_Angle FLOAT,CFangleY_Angle FLOAT,HEADING FLOAT,tiltCompensatedHeading FLOAT,kalmanX FLOAT,kalmanY FLOAT,xG FLOAT,yG FLOAT,ZG FLOAT,temp FLOAT, pressure FLOAT,altitude FLOAT,GPS_datestamp BINARY(10),GPS_timestamp BINARY(8),GPS_lat DOUBLE,GPS_lat_dir BINARY(2),GPS_lon DO
UBLE,GPS_lon_dir BINARY(2),RMC_speed FLOAT) TAGS (trip_type BINARY(20), vehicle_type BINARY(20), model BINARY(20), brand BINARY(20), seats INT , mode BINARY(6), logger_location BINARY(20), owner BINARY(20), tripID BINARY(20), trip_desc BINARY(40), hardware BINARY(40))

3. The CSV file will have the following columns:

CSV labels

System timestamp,ACCX Angle,ACCY Angle,GRYX Angle,GYRY Angle,GYRZ Angle,CFangleX Angle,CFangleY Angle,HEADING,tiltCompensatedHeading,kalmanX,kalmanY,xG,yG,ZG,temp, pressure,altitude,GPS_datestamp,GPS_timestamp,GPS_lat,GPS_lat_dir,GPS_lon,GPS_lon_dir,RMC_speed

**Comment by cdiwadkar16** [comment]
1. CPU speed  - 1.44 GHZ (intel atom)
2. Number of cores - 4
3. Memory - 3.3 GB
4. ubuntu 18.04.6 LTS - 64 bit

**Comment by zitsen** [comment]
The last error said

```
taos.error.ProgrammingError: [0x0216]: invalid operation: '23:18:39.500000' (string data overflow)
```

`string data overflow` usually caused by overflow data length of binary or nchar.

Eg.

```sql
create table tb1 (ts timestamp, data binary(8));
insert into tb1 (now, '23:18:39.500000');
```

I think the table schema should be changed a bit for this kind of data.

**Comment by zitsen** [comment]
> This happens when i increase the GPS sample collection rate from 1 hZ to 10 Hz

This happens because higher sampling rate result with higher resolution of timestamp, such as '23:18:35' in 1 hz requires `binary(8)` - passed, but '23:18:39.500000' in 10Hz requires `binary(15)` - overflowed.

**Comment by zitsen** [comment]
This issue was closed because it has been inactive for 14 days
