### ISSUE TITLE
using sql to subscribe data , some characters appeared in the end of the data.

### ISSUE THREAD

**Issue by hydaizd** [taosdata/TDengine#9427]
taosdb版本: 2.2.1.3

当我通过sql语句从表中订阅数据时，如：select ts,trace_id from t_bus_001，取出来的数据，其中trace_id字段的值尾部会多出一个奇怪的字符（$、#等），经过排查发现是由于trace_id字段的长度，刚好和插入的值的长度是一样的就会有这个问题。

表里面trace_id的值是：3ea31466-248b-456a-b50d-781a4399d062
通过sql订阅时，读出来的数据变成了3ea31466-248b-456a-b50d-781a4399d062$，末尾多了一个$号（有时是其他符号）

trace_id字段类型是：trace_id BINARY(36)，我将它改成trace_id BINARY(48)时，订阅取出的数据就恢复正常了。

**Comment by yu285** [comment]
we will check on this

**Comment by yu285** [comment]
可以加微信15652223354做具体排查
