### ISSUE TITLE
Driver class 'com.alibaba.fastjson.JSONObject' not found.

### ISSUE THREAD

**Issue by pacinoxiey** [taosdata/TDengine#9429]
TDengine 版本2.4.0.0 
使用ideajdbc方式连接数据库报错Driver class 'com.alibaba.fastjson.JSONObject' not found.
driver版本2.0.36

**Comment by huolibo** [comment]
maven仓库中jdbc 2.0.36不包含第三方依赖包，此jdbc需要在maven项目中使用，则会自动引入依赖。
如果在idea database连接数据库需要使用包含第三方jar的jdbc。
可以pull下develop分支，进入src/connector/jdbc。 然后执行mvn clean package -Dmaven.test.skip=true。
使用target目录下的taos-jdbcdriver-2.0.36-dist.jar在idea中连接数据库

**Comment by xiaohuq1a3z6p3** [comment]
> maven仓库中jdbc 2.0.36不包含第三方依赖包，此jdbc需要在maven项目中使用，则会自动引入依赖。 如果在idea database连接数据库需要使用包含第三方jar的jdbc。 可以pull下develop分支，进入src/connector/jdbc。 然后执行mvn clean package -Dmaven.test.skip=true。 使用target目录下的taos-jdbcdriver-2.0.36-dist.jar在idea中连接数据库

没太懂，请问方便给个详细一些的步骤吗
