### ISSUE TITLE
DB error: Duplicated join key 

### ISSUE THREAD

**Issue by sytpb** [taosdata/TDengine#9469]
ver 2.2.0.5 

Action: Join with two tables

![image](https://user-images.githubusercontent.com/12178686/147624561-f7f2f193-f516-48f3-a887-00849c11d067.png)

![image](https://user-images.githubusercontent.com/12178686/147624578-e808fe3b-996a-4625-b2b9-47eea0d4dfea.png)

taos> select * from milkyway.orders t1, sun.orders t2 where t1.corpid=t2.corpid and t1.stamp=t2.stamp;

DB error: Duplicated join key (0.001620s)

**Comment by yu285** [comment]
if there are some normal tables under the super table  have same tag value,would report this error
