### ISSUE TITLE
2.4.0.0版本，Linux服务端正常运行，windows客户端taos shell不能连通

### ISSUE THREAD

**Issue by MeehooCN** [taosdata/TDengine#9472]
Linux服务端操作系统  ubutu 16.04，TDEngine正常运行
![11](https://user-images.githubusercontent.com/68725781/147628620-d11504b5-6cc5-4193-9f82-d4370a2457d8.png)
直接在linux 通过taos -h  主机名能连通

![22](https://user-images.githubusercontent.com/68725781/147628640-169c6666-9e76-49de-9d34-baabf423fe2c.png)

在windows 10  64位机器安装 tdengine windows客户端，在windwos hosts添加FQDN记录，通过telnet 能连接linux服务端和6030端口，但是用tdengine  taos shell不能连通
![33](https://user-images.githubusercontent.com/68725781/147628742-f1477ba5-e60c-4036-8a05-bfdc6ea4b826.png)
运行Java工程，java代码报错JNI ERROR (2354): Ref is not there
![555](https://user-images.githubusercontent.com/68725781/147628802-32d05913-5a0d-42e0-8cd3-090726235c67.png)

**Comment by MeehooCN** [comment]
https://www.taosdata.com/cn/documentation/faq文档第 5条已尝试
用power shell测试网络畅通
![66](https://user-images.githubusercontent.com/68725781/147629836-0a0dec99-18ff-48cf-90af-d48048296464.png)

**Comment by sangshuduo** [comment]
请删除 C:/TDengine/log 目录下文件，修改 C:/TDengine/cfg/taos.cfg 中 debugFlag 为 135，然后用 taos.exe 重连，在失败后，把 C:/Tengine/log/ 目录下文件贴一下

**Comment by MeehooCN** [comment]
非常感谢，日志如下：
12/29 14:47:21.301000 00014688 UTL ==================================
12/29 14:47:21.301000 00014688 UTL  dataDir: C:/TDengine/data level:0 primary:1
12/29 14:47:21.301000 00014688 UTL ==================================
12/29 14:47:21.303000 00014688 TSC starting to initialize client ...
12/29 14:47:21.303000 00014688 TSC Local End Point is:WIN-UN46PV987LR:6030
12/29 14:47:21.303000 00014688 UTL tsc scheduler is initialized, numOfThreads:4
12/29 14:47:21.303000 00014688 TSC client task queue is initialized, numOfWorkers: 4
12/29 14:47:21.304000 00014688 UTL tmr scheduler is initialized, numOfThreads:1
12/29 14:47:21.304000 00014688 TSC client is initialized successfully
12/29 14:47:21.304000 00014688 TSC try to create a connection to iZbp16eo1imej1pt56qmouZ:6030, user:root db:(null)
12/29 14:47:21.304000 00014688 UTL pool:000001DF1C353810 is setup, maxId:5000
12/29 14:47:21.304000 00018788 UTL cache refresh thread starts
12/29 14:47:21.304000 00014688 UTL open udp socket:0x0:0
12/29 14:47:21.305000 00014688 UTL open udp socket:0x0:0
12/29 14:47:21.305000 00014688 UTL open udp socket:0x0:0
12/29 14:47:21.305000 00002840 RPC TSC UDP thread is created, index:0
12/29 14:47:21.305000 00014688 UTL open udp socket:0x0:0
12/29 14:47:21.305000 00014688 RPC TSC UDP connection is initialized, ip:0:0 threads:4
12/29 14:47:21.305000 00005612 RPC TSC UDP thread is created, index:1
12/29 14:47:21.305000 00014688 RPC TSC rpc is opened, threads:4 sessions:5000
12/29 14:47:21.305000 00014688 UTL cache:rpcObj, key:000000AF4CB0ECC0, 000001DF1F55C200 added into cache, added:1640760441305, expire:1640760446305, totalNum:1 totalSize:623bytes size:520bytes
12/29 14:47:21.305000 00014688 TSC 0x2 new SqlObj from 000001DF1F55C440, total in tscObj:1, total:1
12/29 14:47:21.305000 00014688 TSC 0x2 SQL cmd:connect will be processed, name:, type:0
12/29 14:47:21.305000 00011320 RPC TSC UDP thread is created, index:2
12/29 14:47:21.305000 00015160 RPC TSC UDP thread is created, index:3
12/29 14:47:21.305000 00014688 RPC TSC 000001DF1F5731B8 client connection is allocated, uid:0x1f577af1
12/29 14:47:21.305000 00014688 RPC TSC UDP connection is setup, ip:6157722f:6030 localPort:49985
12/29 14:47:21.305000 00014688 RPC TSC 000001DF1F5731B8 0000000000000002, connect is sent to iZbp16eo1imej1pt56qmouZ:6030, len:378 sig:0x01000000:0x00000000:6494
12/29 14:47:21.609000 00018836 RPC TSC 000001DF1F5731B8 0000000000000002, expected connect-rsp is not received
12/29 14:47:21.609000 00018836 RPC TSC 000001DF1F5731B8 0000000000000002, re-send msg:connect to iZbp16eo1imej1pt56qmouZ:6030
12/29 14:47:21.609000 00018836 RPC TSC 000001DF1F5731B8 0000000000000002, connect is sent to iZbp16eo1imej1pt56qmouZ:6030, len:378 sig:0x01000000:0x00000000:6494
12/29 14:47:21.914000 00018836 RPC TSC 000001DF1F5731B8 0000000000000002, expected connect-rsp is not received
12/29 14:47:21.914000 00018836 RPC TSC 000001DF1F5731B8 0000000000000002, re-send msg:connect to iZbp16eo1imej1pt56qmouZ:6030
12/29 14:47:21.914000 00018836 RPC TSC 000001DF1F5731B8 0000000000000002, connect is sent to iZbp16eo1imej1pt56qmouZ:6030, len:378 sig:0x01000000:0x00000000:6494
12/29 14:47:22.219000 00018836 RPC TSC 000001DF1F5731B8 0000000000000002, expected connect-rsp is not received
12/29 14:47:22.219000 00018836 RPC TSC 000001DF1F5731B8 0000000000000002, re-send msg:connect to iZbp16eo1imej1pt56qmouZ:6030
12/29 14:47:22.219000 00018836 RPC TSC 000001DF1F5731B8 0000000000000002, connect is sent to iZbp16eo1imej1pt56qmouZ:6030, len:378 sig:0x01000000:0x00000000:6494
![77](https://user-images.githubusercontent.com/68725781/147634674-7e6422ea-07ae-4022-aa4c-1619d06b9901.png)

**Comment by sangshuduo** [comment]
看起来就是网络不同，能不能试一下把 2.4 全部删除再用之前可以运行的 2.2 跑一次？确定一下是版本问题还是环境问题

**Comment by MeehooCN** [comment]
谢谢指点，换成2.2.2.0后，还是不通，如您说的，估计是网络问题，但是我自己有点找不到方向了，服务端的防火墙是关闭了的，云服务的安全组端口也是开放了的，并且通过telnet是可以ping通的。

**Comment by MeehooCN** [comment]
可以了，原来是云服务器的UDP端口没有放开。只放开了TCP的端口，  后来同学如果是云服务器，一定要检查云服务器的安全组是否打开TCP/UDP 端口6030-6042的访问权限
