### ISSUE TITLE
python、linux中操作的几个问题

### ISSUE THREAD

**Issue by bing0109** [taosdata/TDengine#95]
1、在linux中系统登录数据库查询表有数据，但通过python查询表中的数据返回空[]
疑似库名表名不能带下划线或太长，我用db2.t2这样的名称就可以查到，test_tdengine_db.test_table就没查到过，具体场景没完全测出来。

2、时间戳不一样，其他字段不一样，insert插入失败（不生效），不知是不是设置问题？

3、linux中登录系统，偶尔会碰到数据库掉线问题，退出重新登录数据库又可以正常操作

**Comment by hzcheng** [comment]
关于问题1，请问可不可以给个示例程序
关于问题2，您写入的时间戳对于一张表是递增的吗？如果对于一张表不是递增的，insert命令会丢弃。可以用import语句写入
关于问题3，您可以提供更多的描述信息吗？
非常感谢！

**Comment by bing0109** [comment]
### 问题1：

**数据库中查询**

 taos> _select * from db_test.table_test;_ 

>                  ts          |   num1    |   num2    |   num3    |
>  ===========================================================
>   19-07-17 15:08:26.136|          2|          7|          5|
>  Query OK, 1 row(s) in set (0.113500s)


**python接口查询**
>>> _c1.execute("select * from db_test.table_test;")_
c_void_p(94290903621760)
>>> c1.fetchall()
[]
>>>
**另外说名称较短的可以查到，重新试了下又查不到了**
taos> _select * from db1.t1;_

>           ts          |   num1    |   num2    |   num3    |
> ===========================================================
>  19-07-17 06:45:20.550|          1|          2|          3|
>  19-07-17 06:46:10.345|          1|          2|          3|
>  19-07-17 06:46:11.775|          1|          2|          3|
> Query OK, 3 row(s) in set (0.000990s)
> 

**之前查到过一次（后面两条数据是查询后插入的）**
>>> c1.execute('select * from db1.t1;')
c_void_p(94756936495232)
>>> for col in c1:
...     print(col)
...
(datetime.datetime(2019, 7, 17, 6, 45, 20, 550000), 1, 2, 3)
>>>
>>> c1.fetchall()
[]

**今天重试了一下，又查不到了**

>>> c1.execute('select * from db1.t1;')
c_void_p(94812884022400)
>>> for i in c1:
...     print(i)
...
>>> c1.fetchall()
[]
>>>


### 问题2：

**之前插入失败的数据的时间戳确实不是递增的，递增后可以正确插入
建议：插入失败的话是不是应该给个warning才比较合适**

> taos> insert into db_test.table_test values('2019-07-17 07:11:47.547116',2, 7, 6);
> Query OK, 0 row(s) affected (0.000327s)
> 
> taos> insert into db_test.table_test values('2019-07-17 07:11:47.547',2, 7, 6);
> Query OK, 0 row(s) affected (0.000313s)
> 



### 问题3：

**示例1：**

> taos> select * from t3
>    -> ;
> TSDB error: failed to connect to server
> taos> quit
> bing@chw1:~/project/0717_taos$
> bing@chw1:~/project/0717_taos$ taos
> 
> Welcome to the TDengine shell, server version:1.6.1.0  client version:1.6.1.0
> Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.
> 
> taos> select * from db2.t3;
> Query OK, 0 row(s) in set (0.000955s)
> 

**示例2：**

> _taos> select count(id) from db2.t3;
> TSDB error: failed to connect to server
> taos>
> taos> exit
> bing@chw1:~/project/0717_taos$
> bing@chw1:~/project/0717_taos$ taos
> 
> Welcome to the TDengine shell, server version:1.6.1.0  client version:1.6.1.0
> Copyright (c) 2017 by TAOS Data, Inc. All rights reserved.
> 
>  taos> select count(id) from db2.t3; 

>        count(id)      |
> ======================
>                 18649|
> Query OK, 1 row(s) in set (0.001237s)_
