### ISSUE TITLE
Python-client report error: login disconnected, login again

### ISSUE THREAD

**Issue by eltonchaw7** [taosdata/TDengine#951]
######## The code ########
class TDHelper(object):
    @staticmethod
    def connection():
        '''
        Warning: must close connection manually
        :return:
        '''
        return taos.connect(host=settings.TDENGINE_CONFIG['HOST'], user=settings.TDENGINE_CONFIG['USER'],
                            password=settings.TDENGINE_CONFIG['PASSWORD'], port=settings.TDENGINE_CONFIG['PORT'],
                            database=settings.TDENGINE_CONFIG['NAME'])

    @staticmethod
    def select(sql):
        conn = TDHelper.connection()
        try:
            cursor = conn.cursor()
            cursor.execute(sql)
            return cursor.fetchall()
        except Exception as e:
            if e.msg == 'invalid table':
                return tuple()
            logger.info(e)
            raise(e)
        finally:
            conn.close()
####### DEBUG message ########
taos.error.ProgrammingError: login disconnected, login again

**Comment by fangpanpan** [comment]
请问直接在python 的命令行里，import taos; conn = taos_connect() 这样可以连上数据库吗？

**Comment by schenton** [comment]
I also encountered whit this problem, i check the taoslog0.0 file. 
the error is :   the 2-th number of server version:1.6.4.3 not matched with client version:1.6.3.1, close connection.
I uninstall taos 1.6.3.1 and install 1.6.4.3 yestoday,    also i uninstall the python connector with "pip uninstall taos",  and reinstall the new version of python connector with "pip install python3/", but this problem still exsist. 
so ,how can i do more to reinstall python connector  to make connector run success?

**Comment by schenton** [comment]
btw, the taos connect version is 1.4.15, is the right version?

**Comment by fangpanpan** [comment]
> btw, the taos connect version is 1.4.15, is the right version?

it is the python driver version and doesn't matter.

**Comment by fangpanpan** [comment]
> I also encountered whit this problem, i check the taoslog0.0 file.
> the error is : the 2-th number of server version:1.6.4.3 not matched with client version:1.6.3.1, close connection.
> I uninstall taos 1.6.3.1 and install 1.6.4.3 yestoday, also i uninstall the python connector with "pip uninstall taos", and reinstall the new version of python connector with "pip install python3/", but this problem still exsist.
> so ,how can i do more to reinstall python connector to make connector run success?

where did you install the tdengine server and client? have you make sure that all clients are upgraded?

**Comment by schenton** [comment]
> > I also encountered whit this problem, i check the taoslog0.0 file.
> > the error is : the 2-th number of server version:1.6.4.3 not matched with client version:1.6.3.1, close connection.
> > I uninstall taos 1.6.3.1 and install 1.6.4.3 yestoday, also i uninstall the python connector with "pip uninstall taos", and reinstall the new version of python connector with "pip install python3/", but this problem still exsist.
> > so ,how can i do more to reinstall python connector to make connector run success?
> 
> where did you install the tdengine server and client? have you make sure that all clients are upgraded?

1. I install the server and client in the same machine, and use the package "TDengine-1.6.4.3.tar.gz".
2. i uninstalled the old version with remove.sh, and install the new version taos server with instal.sh.
3. then i uninstalled the connector with "pip uninstall taos" and install the new connector with "pip install python3/".

**Comment by fangpanpan** [comment]
> > > I also encountered whit this problem, i check the taoslog0.0 file.
> > > the error is : the 2-th number of server version:1.6.4.3 not matched with client version:1.6.3.1, close connection.
> > > I uninstall taos 1.6.3.1 and install 1.6.4.3 yestoday, also i uninstall the python connector with "pip uninstall taos", and reinstall the new version of python connector with "pip install python3/", but this problem still exsist.
> > > so ,how can i do more to reinstall python connector to make connector run success?
> > 
> > 
> > where did you install the tdengine server and client? have you make sure that all clients are upgraded?
> 
> 1. I install the server and client in the same machine, and use the package "TDengine-1.6.4.3.tar.gz".
> 2. i uninstalled the old version with remove.sh, and install the new version taos server with instal.sh.
> 3. then i uninstalled the connector with "pip uninstall taos" and install the new connector with "pip install python3/".

could you try 'rmtaos' command and then install the new version again? Then execute 'll /usr/lib/libtaos.so*' and show me the result?

**Comment by schenton** [comment]
lrwxrwxrwx 1 root root 21 12月 20 12:05 libtaos.so -> /usr/lib/libtaos.so.1
lrwxrwxrwx 1 root root 41 12月 20 12:05 libtaos.so.1 -> /usr/local/taos/driver/libtaos.so.1.6.4.3

**Comment by schenton** [comment]
> > > > I also encountered whit this problem, i check the taoslog0.0 file.
> > > > the error is : the 2-th number of server version:1.6.4.3 not matched with client version:1.6.3.1, close connection.
> > > > I uninstall taos 1.6.3.1 and install 1.6.4.3 yestoday, also i uninstall the python connector with "pip uninstall taos", and reinstall the new version of python connector with "pip install python3/", but this problem still exsist.
> > > > so ,how can i do more to reinstall python connector to make connector run success?
> > > 
> > > 
> > > where did you install the tdengine server and client? have you make sure that all clients are upgraded?
> > 
> > 
> > 
> > 1. I install the server and client in the same machine, and use the package "TDengine-1.6.4.3.tar.gz".
> > 2. i uninstalled the old version with remove.sh, and install the new version taos server with instal.sh.
> > 3. then i uninstalled the connector with "pip uninstall taos" and install the new connector with "pip install python3/".
> 
> could you try 'rmtaos' command and then install the new version again? Then execute 'll /usr/lib/libtaos.so*' and show me the result?

lrwxrwxrwx 1 root root 21 12月 20 12:05 libtaos.so -> /usr/lib/libtaos.so.1
lrwxrwxrwx 1 root root 41 12月 20 12:05 libtaos.so.1 -> /usr/local/taos/driver/libtaos.so.1.6.4.3

**Comment by fangpanpan** [comment]
> > > > > I also encountered whit this problem, i check the taoslog0.0 file.
> > > > > the error is : the 2-th number of server version:1.6.4.3 not matched with client version:1.6.3.1, close connection.
> > > > > I uninstall taos 1.6.3.1 and install 1.6.4.3 yestoday, also i uninstall the python connector with "pip uninstall taos", and reinstall the new version of python connector with "pip install python3/", but this problem still exsist.
> > > > > so ,how can i do more to reinstall python connector to make connector run success?
> > > > 
> > > > 
> > > > where did you install the tdengine server and client? have you make sure that all clients are upgraded?
> > > 
> > > 
> > > 
> > > 1. I install the server and client in the same machine, and use the package "TDengine-1.6.4.3.tar.gz".
> > > 2. i uninstalled the old version with remove.sh, and install the new version taos server with instal.sh.
> > > 3. then i uninstalled the connector with "pip uninstall taos" and install the new connector with "pip install python3/".
> > 
> > 
> > could you try 'rmtaos' command and then install the new version again? Then execute 'll /usr/lib/libtaos.so*' and show me the result?
> 
> lrwxrwxrwx 1 root root 21 12月 20 12:05 libtaos.so -> /usr/lib/libtaos.so.1
> lrwxrwxrwx 1 root root 41 12月 20 12:05 libtaos.so.1 -> /usr/local/taos/driver/libtaos.so.1.6.4.3

Is there any way that I can remotely work on your computer and figure out the problems? If so, you can send the method to fpang@taosdata.com.

**Comment by eltonchaw7** [comment]
The reason has been found：Database doesn't exists!
