### ISSUE TITLE
bug -  python3 taos connector 

### ISSUE THREAD

**Issue by zcl123** [taosdata/TDengine#9534]
When there is no passwd, you can't connect to taosd through python3 API.

The error screencast as followed:

![8d6282a74e54f9dc954782abe1268e3](https://user-images.githubusercontent.com/11937602/147804579-deea89dc-bda5-4272-9ea4-47545e80ed02.png)

**Comment by zitsen** [comment]
I'll check it. What's the TDengine and python connector version you're using ?

You can use `taosd -V` and `python -c "import taos; print(taos.__version__)"` to get the versions.
