### ISSUE TITLE
Can't get taosdump command in docker with V2.4.0.0

### ISSUE THREAD

**Issue by tiansfather** [taosdata/TDengine#9538]
![image](https://user-images.githubusercontent.com/16606743/147810566-b5f8f86b-3965-4088-91b6-57c764cd2676.png)

It worked in V2.0.22.0

Was it moved to somewhere?

**Comment by yu285** [comment]
We provide a few useful tools such as taosBenchmark (was named taosdemo) and taosdump. They were part of TDengine. From TDengine 2.4.0.0, taosBenchmark and taosdump were not released together with TDengine. By default, TDengine compiling does not include taos-tools. You can use 'cmake .. -DBUILD_TOOLS=true' to make them be compiled with TDengine.

you can check for detail in Readme in  https://github.com/taosdata/TDengine
