### ISSUE TITLE
服务器hostname 与taos启动后endpoint名称不一致

### ISSUE THREAD

**Issue by sutianwei** [taosdata/TDengine#9549]
1 | su.com.com:6030                |      0 |      0 | offline    | any   | 2021-12-31 21:19:43.726 | status not received 

hostname 是su.com

**Comment by sutianwei** [comment]
重新安装了服务端taos，问题解决，插入数据taos connect failed, reason: Unable to establish connection. 的问题一并消失

**Comment by yu285** [comment]
可能是安装的时候，不正规的调整了哪些参数导致的问题

如果还有疑问可以添加微信15652223354做排查处理。
