### ISSUE TITLE
FQDN  issue

### ISSUE THREAD

**Issue by deluit8** [taosdata/TDengine#9551]
在linux服务器上可以访问, 但是在windows客户端上无法访问

linux服务器上安装了taos server, 是腾讯云主机, windows客户端是我自己的电脑
进一步试了一下,可以通过windows客户端创建表, 不能查询和插入

![image](https://user-images.githubusercontent.com/65478353/147857181-d276485b-69ba-4b90-81fe-1c8ba4d92953.png)

![image](https://user-images.githubusercontent.com/65478353/147856906-29f53cba-25bc-4a9a-a220-14fb70ebf4c4.png)

![image](https://user-images.githubusercontent.com/65478353/147856881-4349fd2f-bbca-48ae-8341-ab71d6940988.png)

**Comment by yu285** [comment]
taosd | grep -i fqdn 

please show us

**Comment by Deluit8** [comment]
![image](https://user-images.githubusercontent.com/65478353/147899753-f06e0a68-6453-4624-aa74-9addbca3879e.png)

**Comment by Deluit8** [comment]
I fix the issue, show make configuration for my server.

another issue:
version 2.3.5.0

table description:
drop table `002432.SZ`;create table `002432.SZ`(ts timestamp, `open` float, `high` float, `low` float, `close` float, `change` float, `pct_chg` float, `vol` float, `amount` float, `pre_close` float);

insert into `002432.SZ` (ts,`open`,`high`,`low`,`close`,`change`,`pct_chg`,`vol`,`amount`, `pre_close`) values('2012-01-06 00:00:00.000', 8.04,8.29,8.29,8.25,0.23,2.87,33746.5,26667.2,8.02);
processing the above script, give me message 'db error Timestamp data out of range'

![image](https://user-images.githubusercontent.com/65478353/147935220-cb4aa8b8-21ca-4918-a55e-585b549354b3.png)

**Comment by yu285** [comment]
https://www.taosdata.com/tdengine-engineering
