### ISSUE TITLE
New data file is created at 8:00 but not 0:00 while using keep and days options in Ali cloud server

### ISSUE THREAD

**Issue by kosmos-zhang** [taosdata/TDengine#9553]
**Bug Description**
The new DB file is created at 8:00 but not 0:00 in Ali server while using keep and days options.

**To Reproduce**
1. Create the Taos DB with keep and days options, something like " CREATE DATABASE XXX REPLICA 1 QUORUM 1 DAYS 3 KEEP 10 BLOCKS 6"
2. Insert the data with seconds
3. 3 days later, the new DB file is created, and the last write time of the old file is at 8:00 but not 0:00

**Expected Behavior**
The last write time of the old file is 0:00

**Screenshots**
![datetime](https://user-images.githubusercontent.com/15828055/147895873-8c3e24b5-fb8a-44d6-988b-5ce889effd67.png)

**Environment (please complete the following information):**
 - OS: [CentOS 7.0]
 - Time zone: Asia/Shanghai (CST, +0800)
 - TDengine Version [2.1.3.2]

**Additional Context**
None.

**Comment by Deluit8** [comment]
it is UTC

**Comment by kosmos-zhang** [comment]
We config the timezone as Asia/Shaihai as well, and why it doesn't use the local time which we config in taos.cfg?

**Comment by arielyang** [comment]
check this blog: https://www.taosdata.com/blog/2021/09/26/3101.html
