### ISSUE TITLE
csv数据导入/join/group by实践体验

### ISSUE THREAD

**Issue by fanyunli** [taosdata/TDengine#96]
数据导入的时候，数据中时间戳字段必须是有顺序的，否则只能导入部分数据。但在时间戳有序的情况下，依旧有小部分数据导入失败，报invalid next size (normal)错误，暂且还没明白什么问题，期待其他人的回答。
join的功能，目前还未开发出来，期待。
group by功能，目前在超级表中可以使用。
希望能对大家有帮助。

**Comment by mseaspring** [comment]
x谢谢

**Comment by amosbird** [comment]
> group by功能，目前在超级表中可以使用。

我在文档没有看到这个功能, 能具体说说吗? 谢谢

**Comment by plum-lihui** [comment]
@fanyunli  “数据导入的时候，数据中时间戳字段必须是有顺序的，否则只能导入部分数据。但在时间戳有序的情况下，依旧有小部分数据导入失败，报invalid next size (normal)错误，暂且还没明白什么问题，期待其他人的回答。” 
 这个问题能给点更详细的信息吗？比如：导入方法，是shell下命令导入，还是写的app（用的java写的，还是c写的）？ 如果方便的话，是否可以将数据文件提供给我们测试一下？
多谢！

**Comment by 714139391** [comment]
超级表group by 会报错：TSDB error:invalid SQl:illegal column name，怎么解决

**Comment by hjxilinx** [comment]
groupby 使用非法的列名称吧？现在的group by还只能针对表的 tag来group by。后面升级会提供针对状态量的group by功能。

**Comment by 714139391** [comment]
我根据表的tag来group by 也是报一样的错啊

**Comment by hjxilinx** [comment]
@714139391 可否提供更详细的信息，可以将详细的信息mail 到 hjliao@taosdata.com, 邮件中可附上您的联系方式。便于我们更好协助您查找问题。
