### ISSUE TITLE
nodejs FailureMessage Object: 0x7ffce1632540

### ISSUE THREAD

**Issue by yebel1120** [taosdata/TDengine#9606]
使用github上nodejs的demo，循环插入数据时会报错，请问这个问题怎么解决？？？

代码段：
for (let i = 0; i < 1000; i++) {
    stime.setMilliseconds(stime.getMilliseconds() + interval);
    
    //console.log(stime.Format('yyyy-MM-dd HH:mm:ss.SSS'));    

    let insertData = [stime,
                      parseInt(Math.random()*100),
                      parseInt(Math.random()*300),
                      parseFloat(Math.random()*10 + 30),
                      "Note"];
    //c1.execute('insert into db.weather values(' + insertData.join(',') + ' );');
    
    //var query = c1.query('insert into db.weather values(?, ?, ?, ?, ?);').bind(insertData);
    //query.execute();
    c1.execute('insert into db.weather values(\"'+stime.Format('yyyy-MM-dd HH:mm:ss.SSS')+'\",'+parseInt(Math.random() * 100)+','+parseInt(Math.random() * 300)+','+parseFloat(Math.random()*10 + 30)+',"Note");');
  }

错误信息：
#FailureMessage Object: 0x7ffce1632540
 1: 0xaa6321  [node]
 2: 0x1a3b274 V8_Fatal(char const*, ...) [node]
 3: 0xe9afd9 v8::internal::GlobalBackingStoreRegistry::Register(std::shared_ptr<v8::internal::BackingStore>) [node]
 4: 0xbe4c38 v8::ArrayBuffer::GetBackingStore() [node]
 5: 0x9f1c70 napi_get_typedarray_info [node]
 6: 0x7f8d91dee3af  [/home/gsta/node_modules/ffi-napi/node_modules/ref-napi/prebuilds/linux-x64/node.napi.node]
 7: 0x7f8d91df097d  [/home/gsta/node_modules/ffi-napi/node_modules/ref-napi/prebuilds/linux-x64/node.napi.node]
 8: 0x7f8d91bd826c FFI::FFI::FFICall(Napi::CallbackInfo const&) [/home/gsta/node_modules/ffi-napi/build/Release/ffi_bindings.node]
 9: 0x7f8d91bdc46b Napi::details::CallbackData<void (*)(Napi::CallbackInfo const&), void>::Wrapper(napi_env__*, napi_callback_info__*) [/home/gsta/node_modules/ffi-napi/build/Release/ffi_bindings.node]
10: 0x9e8a7d  [node]
11: 0xc238db  [node]
12: 0xc24e86  [node]
13: 0xc25506 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
14: 0x1446459  [node]
非法指令 (核心已转储)

taos版本2.2.1.1
nodejs版本14.18.1

**Comment by sangshuduo** [comment]
目前支持 nodejs 10 和 12 ，还不支持 14

**Comment by yebel1120** [comment]
使用nodejs12.22.8版本，也是一样的错误。
这段代码是可以成功写库的，但是在循环写库的时候会概率性报错，有时运行100次，有时运行50次

**Comment by xleili** [comment]
我本地复现看看，能发现问题吗。

**Comment by xleili** [comment]
> 使用github上nodejs的demo，循环插入数据时会报错，请问这个问题怎么解决？？？
> 
> 代码段： for (let i = 0; i < 1000; i++) { stime.setMilliseconds(stime.getMilliseconds() + interval);
> 
> ```
> //console.log(stime.Format('yyyy-MM-dd HH:mm:ss.SSS'));    
> 
> let insertData = [stime,
>                   parseInt(Math.random()*100),
>                   parseInt(Math.random()*300),
>                   parseFloat(Math.random()*10 + 30),
>                   "Note"];
> //c1.execute('insert into db.weather values(' + insertData.join(',') + ' );');
> 
> //var query = c1.query('insert into db.weather values(?, ?, ?, ?, ?);').bind(insertData);
> //query.execute();
> c1.execute('insert into db.weather values(\"'+stime.Format('yyyy-MM-dd HH:mm:ss.SSS')+'\",'+parseInt(Math.random() * 100)+','+parseInt(Math.random() * 300)+','+parseFloat(Math.random()*10 + 30)+',"Note");');
> ```
> 
> }
> 
> 错误信息： #FailureMessage Object: 0x7ffce1632540 1: 0xaa6321 [node] 2: 0x1a3b274 V8_Fatal(char const*, ...) [node] 3: 0xe9afd9 v8::internal::GlobalBackingStoreRegistry::Register(std::shared_ptrv8::internal::BackingStore) [node] 4: 0xbe4c38 v8::ArrayBuffer::GetBackingStore() [node] 5: 0x9f1c70 napi_get_typedarray_info [node] 6: 0x7f8d91dee3af [/home/gsta/node_modules/ffi-napi/node_modules/ref-napi/prebuilds/linux-x64/node.napi.node] 7: 0x7f8d91df097d [/home/gsta/node_modules/ffi-napi/node_modules/ref-napi/prebuilds/linux-x64/node.napi.node] 8: 0x7f8d91bd826c FFI::FFI::FFICall(Napi::CallbackInfo const&) [/home/gsta/node_modules/ffi-napi/build/Release/ffi_bindings.node] 9: 0x7f8d91bdc46b Napi::details::CallbackData<void (_)(Napi::CallbackInfo const&), void>::Wrapper(napi_env___, napi_callback_info___) [/home/gsta/node_modules/ffi-napi/build/Release/ffi_bindings.node] 10: 0x9e8a7d [node] 11: 0xc238db [node] 12: 0xc24e86 [node] 13: 0xc25506 v8::internal::Builtin_HandleApiCall(int, unsigned long_, v8::internal::Isolate*) [node] 14: 0x1446459 [node] 非法指令 (核心已转储)
> 
> taos版本2.2.1.1 nodejs版本14.18.1

这错在nodejs12.22.8版本，也会出现吗？确定是同一个错误吗？

**Comment by xleili** [comment]
目前我根据你的代码去做复现，并没遇到这个问题。我把循环次数加到10000000，等结果。 
你的平台是什么？

**Comment by yebel1120** [comment]
> 目前我根据你的代码去做复现，并没遇到这个问题。我把循环次数加到10000000，等结果。 你是在windows上还是linux上运行的代码

是我nodejs的版本弄错了，12.22.8版本运行正常。请问什么时候支持node14以上版本？？还有一个问题，我看到node-red上已经有node-red-contrib-tdengine组件了，但是使用上不太明白，这方面有教程吗？？

**Comment by xleili** [comment]
> > 目前我根据你的代码去做复现，并没遇到这个问题。我把循环次数加到10000000，等结果。 你是在windows上还是linux上运行的代码
> 
> 是我nodejs的版本弄错了，12.22.8版本运行正常。请问什么时候支持node14以上版本？？还有一个问题，我看到node-red上已经有node-red-contrib-tdengine组件了，但是使用上不太明白，这方面有教程吗？？

1. node 14我们目前没有兼容node 14的计划，14上有个bug，目前解决不了；
2. node-red 可以看看这个https://blog.csdn.net/armcsdn/article/details/121417568

**Comment by sangshuduo** [comment]
暂时 node 14 官方没有解决 ffi 的 bug，未来 node 14 和 更高版本考虑通过其他接口解决

**Comment by sangshuduo** [comment]
node-red 请参考文档：https://github.com/taosdata/TDengine/tree/develop/src/connector/node-red-contrib-tdengine 或者也可以和作者 @kevinpan45 交流

**Comment by kevinpan45** [comment]
> 

node-red-contrib-tdengine配置使用可以参考https://github.com/taosdata/TDengine/tree/develop/src/connector/node-red-contrib-tdengine的README，可以在前置节点拼接好需要执行的SQL语句，通过msg.payload传递到taos query节点即可，有需要可以给我发邮件kevinpan45@163.com

**Comment by yebel1120** [comment]
> > > 目前我根据你的代码去做复现，并没遇到这个问题。我把循环次数加到10000000，等结果。 你是在windows上还是linux上运行的代码
> > 
> > 
> > 是我nodejs的版本弄错了，12.22.8版本运行正常。请问什么时候支持node14以上版本？？还有一个问题，我看到node-red上已经有node-red-contrib-tdengine组件了，但是使用上不太明白，这方面有教程吗？？
> 
> node-red-contrib-tdengine配置使用可以参考[https://github.com/taosdata/TDengine/tree/develop/src/connector/node-red-contrib-tdengine的README，可以在前置节点拼接好需要执行的SQL语句，通过msg.payload传递到taos](https://github.com/taosdata/TDengine/tree/develop/src/connector/node-red-contrib-tdengine%E7%9A%84README%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%9C%A8%E5%89%8D%E7%BD%AE%E8%8A%82%E7%82%B9%E6%8B%BC%E6%8E%A5%E5%A5%BD%E9%9C%80%E8%A6%81%E6%89%A7%E8%A1%8C%E7%9A%84SQL%E8%AF%AD%E5%8F%A5%EF%BC%8C%E9%80%9A%E8%BF%87msg.payload%E4%BC%A0%E9%80%92%E5%88%B0taos) query节点即可，有需要可以给我发邮件[kevinpan45@163.com](mailto:kevinpan45@163.com)

好的，感谢你的分享，我先学习一下

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
