### ISSUE TITLE
C# 调用TDengine接口使用last  group by  聚合查询时临时文件不释放

### ISSUE THREAD

**Issue by xiaopenggogo** [taosdata/TDengine#9607]
C# 调用TDengine接口使用last  group by  聚合查询时临时文件不释放，导致后面查询失败。
下面是客户端的日志信息
01/05 15:35:07.941000 00012496 TSC ERROR failed to save data in temporary buffer
01/05 15:35:07.941000 00012496 TSC ERROR sub:0x3caa failed to flush data to disk, reason:System out of disk space
01/05 15:35:07.941000 00012496 TSC ERROR 0x3ca7 sub:0x3caa retrieve failed, code:System out of disk space, orderOfSub:1 FAILED. no more retry, set global code:System out of disk space
01/05 15:35:08.259000 00019316 TSC ERROR 0x3ca7 sub:0x3ca9 abort further retrieval due to other queries failure,orderOfSub:0,code:System out of disk space
01/05 15:35:08.259000 00019316 TSC ERROR 0x3ca7 sub:0x3cac abort further retrieval due to other queries failure,orderOfSub:3,code:System out of disk space
01/05 15:35:08.259000 00019316 TSC ERROR 0x3ca7 retrieve from 4 vnode(s) completed,code:System out of disk space.FAILED.

**Comment by xleili** [comment]
1.这是是不是磁盘满了？
2.select last from table group by 这个语句吗

**Comment by xiaopenggogo** [comment]
磁盘没有满，有一个规律，应用程序运行查询时临时文件就会生成每次大概生成250M就会报这个错误。关闭程序在启动查询又会生成例外一组250M文件，之前的一组也不会删除。
![Uploading image.png…]()

**Comment by xiaopenggogo** [comment]
![image](https://user-images.githubusercontent.com/97154895/148212857-763fb06b-bc99-4423-b7d9-eaab7387e60a.png)

**Comment by xiaopenggogo** [comment]
语句为：select last( *) from table group by locationName

**Comment by xiaopenggogo** [comment]
而且之前的临时文件也不会自动删除，这个磁盘总会写满的。   每次运行写250M文件就报错。两个问题吧

**Comment by xleili** [comment]
用的是https://github.com/taosdata/TDengine/issues/9608这个中的驱动吗？我复现一下看看，看上去并不是驱动的的问题。

**Comment by xiaopenggogo** [comment]
嗯嗯，是的。我也再试使用你们的demo试试

**Comment by xiaopenggogo** [comment]
使用你们的demo是一样的效果，临时文件250m
![image](https://user-images.githubusercontent.com/97154895/148216908-b2be6fa9-f8bb-4edb-98ec-a5c4990da6cb.png)

**Comment by xiaopenggogo** [comment]
我的两个问题都是你在处理是吧。  那就一起吧

**Comment by xiaopenggogo** [comment]
![image](https://user-images.githubusercontent.com/97154895/148217611-9747450e-981b-450f-adb0-217eb4cc69f4.png)
