### ISSUE TITLE
C# 调用TDengine接口插入读取数据导致程序内存飙升（内存泄漏问题）

### ISSUE THREAD

**Issue by xiaopenggogo** [taosdata/TDengine#9608]
![image](https://user-images.githubusercontent.com/97154895/148182508-a17f5266-0ede-4bec-8abb-4f55121eb9a0.png)

**Comment by xiaopenggogo** [comment]
版本是2.4.0

**Comment by xiaopenggogo** [comment]
该版本有严重内存泄漏问题
ThreadPool.QueueUserWorkItem(n =>
            {
                while (true)
                {
                    ConcurrentBag<TDengneData> dengneDatas = new ConcurrentBag<TDengneData>();
                    var data = DateTime.Now;
                  
                    for (int i = 0; i < 10000; i++)
                    {
                        dengneDatas.Add(new TDengneData { insertTime = data, tagName = "tagName" + i, tagValue = random.NextDouble() });
                    }


                    Stopwatch sw = new Stopwatch();
                    sw.Start();
                    var flag = tdengneHelper.InsertTDengne(dengneDatas.ToList());
                    sw.Stop();
                    Console.WriteLine($"{DateTime.Now}------------------插入{flag}__{dengneDatas.Count}条，耗时{sw.Elapsed}");
                    Thread.Sleep(5000);
                    GC.Collect();
                }

            });



            ThreadPool.QueueUserWorkItem(n =>
            {
                while (true)
                {
                    Stopwatch sw = new Stopwatch();
                    sw.Start();
                    var readerList = tdengneHelper.ExecuteReader($"select * from {database}.{sup_Table} where insertTime>'{DateTime.Now.AddDays(-7)}' and  tagName='tagName1';");
                    sw.Stop();
                    Console.WriteLine($"{DateTime.Now}------时间查询{readerList.Count}条，耗时{sw.Elapsed}");
                    Thread.Sleep(5000); GC.Collect();
                }
            });

**Comment by xleili** [comment]
可以发一下tdengneHelper.ExecuteReader()的实现代码吗？

**Comment by xiaopenggogo** [comment]
using Core.Loging;
using Maikebing.Data.Taos;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using TDengineDriver;

namespace Core.TDengne
{
    public class TDengneHelper1
    {
        //https://github.com/taosdata/TDengine/issues
        //static TaosConnection connection = new TaosConnection();
        static string _database;
        static string _dataTable;
        static TaosConnectionStringBuilder _builder;



        /// <summary>
        /// 初始化数据库
        /// </summary>
        /// <param name="ip">ip</param>
        /// <param name="port">端口</param>
        /// <param name="userName">用户名</param>
        /// <param name="password">密码</param>
        /// <param name="database">数据库名称</param>
        /// <param name="database">表名</param>
        public TDengneHelper1(string ip, int port, string userName, string password, string database, string dataTable)
        {
            try
            {


                _database = database;
                _dataTable = dataTable;
                _builder = new TaosConnectionStringBuilder()
                {
                    DataSource = ip,
                    DataBase = database,
                    Username = userName,
                    Password = password,
                    Port = port
                };
                using (TaosConnection connection = new TaosConnection(_builder.ConnectionString))
                {
                    connection.Open();

                    //创建数据库  数据将保留365天（超过365天将被自动删除），每10天一个数据文件，内存块数为4，允许更新数据
                    // KEEP 365 DAYS 10 BLOCKS 4 UPDATE 1
                    connection.CreateCommand($"create database if not exists {database}; ").ExecuteNonQuery();
                    //使用数据库
                    connection.CreateCommand($"use {database};").ExecuteNonQuery();
                    //创建超级表               
                    connection.CreateCommand($"create table if not exists {dataTable} (insertTime timestamp, tagValue double) tags (tagName nchar(30));").ExecuteNonQuery();

                    LogHelper.Write($"TDengneServerVersion:{connection.ServerVersion}");
                    Console.WriteLine($"TDengneServerVersion:{connection.ServerVersion}");
                    Console.WriteLine($"TDengneClientVersion:{connection.ClientVersion}");
                    connection.Close();
                    Console.WriteLine("初始化数据库中……");
                };
            }
            catch (Exception ex)
            {
                LogHelper.Write(ex.Message, ex);
            }

        }
        /// <summary>
        /// 插入
        /// </summary>
        /// <param name="list"></param>
        /// <returns></returns>
        public bool InsertTDengne(List<TDengneData> list)
        {
            List<bool> flagList = new List<bool>();
            //每次批量插入有大小限制，所以需要分页插入
            try
            {

                using (TaosConnection connection = new TaosConnection(_builder.ConnectionString))
                {
                    connection.Open();

                    List<List<TDengneData>> listPage = new List<List<TDengneData>>();

                    int pagSize = 500;
                    double page = Math.Ceiling(list.Count / (double)pagSize);
                    for (int i = 0; i < page; i++)
                    {
                        listPage.Add(list.Skip(i * pagSize).Take(pagSize).ToList());
                    }
                    foreach (var itemData in listPage)
                    {
                        StringBuilder sql = new StringBuilder();

                        sql.Append("INSERT INTO ");
                        foreach (var item in itemData)
                        {
                            sql.Append($"{_database}.{item.tagName}  USING {_database}.{_dataTable} TAGS ('{item.tagName}') VALUES ({GetDataTimeToLong(item.insertTime)}, {item.tagValue}) ");
                        }

                        var aaa = connection.CreateCommand(sql.ToString()).ExecuteNonQuery() > 0;
                        flagList.Add(aaa);
                        sql.Clear();
                    };
                    connection.Close();
                    connection.Dispose();
                    return flagList.Any(n => n);
                }

            }
            catch (Exception)
            {
                return false;
            }
        }


        /// <summary>
        /// 插入
        /// </summary>
        /// <param name="Datas"></param>
        /// <returns></returns>
        public bool InsertTDengne(TDengneData Data)
        {
            try
            {
                StringBuilder sql = new StringBuilder();
                sql.Append("INSERT INTO ");
                sql.Append($"{_database}.{Data.tagName}  USING {_database}.{_dataTable} TAGS ('{Data.tagName}') VALUES ({GetDataTimeToLong(Data.insertTime)}, {Data.tagValue}) ");
                return ExecuteNonQuery(sql.ToString());
            }
            catch (Exception ex)
            {
                return false;
            }

        }

        /// <summary>
        /// 执行SQL语句
        /// </summary>
        /// <param name="sql"></param>
        /// <returns></returns>
        private bool ExecuteNonQuery(string sql)
        {
            try
            {
                using (TaosConnection connection = new TaosConnection(_builder.ConnectionString))
                {
                    connection.Open();
                    var falg = connection.CreateCommand(sql).ExecuteNonQuery() > 0;
                    connection.Close();
                    connection.Dispose();
                    //TDengine.Cleanup();
                    return falg;
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return false;
            }
        }

        /// <summary>
        /// 查询
        /// </summary>
        /// <param name="sql"></param>
        /// <returns></returns>
        public List<TDengneData> ExecuteReader(string sql)
        {
            try
            {
                using (TaosConnection connection = new TaosConnection(_builder.ConnectionString))
                {
                    connection.Open();
                    var cmd_select = connection.CreateCommand(sql).ExecuteReader().ToList<TDengneData>();
                    connection.Close();
                    connection.Dispose();

                    return cmd_select;
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return new List<TDengneData>();

            }

        }



        /// <summary>
        /// 时间转换
        /// </summary>
        /// <param name="dateTime"></param>
        /// <returns></returns>
        public long GetDataTimeToLong(DateTime dateTime)
        {
            return (long)(DateTime.Now.Subtract(new DateTime(1970, 1, 1, 0, 0, 0, 0)).TotalMilliseconds);
        }

    }
}

**Comment by xiaopenggogo** [comment]
我直接nuget的Maikebing.Data.Taos包

**Comment by xleili** [comment]
1.首先nuget的Maikebing.Data.Taos包是contributor贡献的代码。他是怎么实现的不是很熟悉。
2.需要看看这里的 connection.Dispose();生效了吗。（Dispose应该是实现了FreeRsult这个方法）；

**Comment by xiaopenggogo** [comment]
好的，我使用你们的demo试试

**Comment by xiaopenggogo** [comment]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using TDengineDriver;

namespace Core.TDengne
{
    public class TDengneHelper
    {
        static string _host;
        static short _port;
        static string _user;
        static string _password;
        static string _dbName;
        static string _dataTable;
        static string configDir = "C:/TDengine/cfg";
        private IntPtr conn = IntPtr.Zero;
        public TDengneHelper(string ip, short port, string userName, string password, string database, string dataTable)
        {
            _host = ip;
            _port = port;
            _user = userName;
            _password = password;
            _dbName = database;
            _dataTable = dataTable;
            InitTDengine();
            ConnectTDengine();
        }

        /// <summary>
        /// 初始化
        /// </summary>
        public void InitTDengine()
        {
            TDengine.Options((int)TDengineInitOption.TDDB_OPTION_CONFIGDIR, configDir);
            TDengine.Options((int)TDengineInitOption.TDDB_OPTION_SHELL_ACTIVITY_TIMER, "60");
            TDengine.Init();
        }

        /// <summary>
        /// 连接数据库
        /// </summary>
        public void ConnectTDengine()
        {
           

            this.conn = TDengine.Connect(_host, _user, _password, _dbName, _port);
            if (this.conn == IntPtr.Zero)
            {
                Console.WriteLine("连接数据库失败");
            }
            else
            {
                Console.WriteLine("连接数据库成功");
                CreateDbAndTable();
            }
        }

        /// <summary>
        /// 创建基础数据
        /// </summary>
        private void CreateDbAndTable()
        {
            ExecuteNonQuery($"create database if not exists {_dbName}");
            ExecuteNonQuery($"use {_dbName}");
            ExecuteNonQuery($"create table if not exists {_dataTable} (insertTime timestamp, tagValue double) tags (tagName nchar(30));");

        }

        /// <summary>
        /// 执行Sql语句
        /// </summary>
        /// <param name="sql"></param>
        /// <returns></returns>
        public bool ExecuteNonQuery(string sql)
        {
            IntPtr res = TDengine.Query(this.conn, sql.ToString());
            if ((res == IntPtr.Zero) || (TDengine.ErrorNo(res) != 0))
            {
                //Console.Write(sql.ToString() + " failure, ");
                if (res != IntPtr.Zero)
                {
                    Console.Write("reason: " + TDengine.Error(res));
                }
            }
            else
            {
                //Console.WriteLine(sql.ToString() + " success");
            }
            return TDengine.FreeResult(res).ToInt32() > 0;

        }

        /// <summary>
        /// 插入
        /// </summary>
        /// <param name="Datas"></param>
        /// <returns></returns>
        public bool InsertTDengne(TDengneData Data)
        {
            try
            {
                StringBuilder sql = new StringBuilder();
                sql.Append("INSERT INTO ");
                sql.Append($"{_dbName}.{Data.tagName}  USING {_dbName}.{_dataTable} TAGS ('{Data.tagName}') VALUES (now,'{Data.insertTime}', {Data.tagValue}) ");
                return ExecuteNonQuery(sql.ToString());
            }
            catch (Exception ex)
            {
                return false;
            }

        }
        /// <summary>
        /// 插入
        /// </summary>
        /// <param name="list"></param>
        /// <returns></returns>
        public bool InsertTDengne(List<TDengneData> list)
        {

            //每次批量插入有大小限制，所以需要分页插入
            try
            {
                //StringBuilder sql = new StringBuilder();

                //sql.Append("INSERT INTO ");
                //foreach (var item in list)
                //{
                //    sql.Append($"{_database}.{item.tagName}  USING {_database}.{_dataTable} TAGS ('{item.tagName}') VALUES (now,'{item.insertTime}', {item.tagValue}) ");
                //};

                //return ExecuteNonQuery(sql.ToString());


                List<List<TDengneData>> listPage = new List<List<TDengneData>>();

                int pagSize = 1000;
                double page = Math.Ceiling(list.Count / (double)pagSize);
                for (int i = 0; i < page; i++)
                {
                    listPage.Add(list.Skip(i * pagSize).Take(pagSize).ToList());
                }
                foreach (var itemData in listPage)
                {
                    StringBuilder sql = new StringBuilder();

                    sql.Append("INSERT INTO ");
                    foreach (var item in itemData)
                    {
                        sql.Append($"{_dbName}.{item.tagName}  USING {_dbName}.{_dataTable} TAGS ('{item.tagName}') VALUES ({GetDataTimeToLong(item.insertTime)}, {item.tagValue}) ");
                    }
                    Thread.Sleep(10);
                    ExecuteNonQuery(sql.ToString());
                };

                return true;


            }
            catch (Exception)
            {
                return false;
            }
        }


        /// <summary>
        /// 查询
        /// </summary>
        /// <param name="sql"></param>
        /// <returns></returns>
        public List<TDengneData> ExecuteReader(string sql)
        {
            try
            {
                long queryRows = 0;

                IntPtr res = TDengine.Query(conn, sql);
                if ((res == IntPtr.Zero) || (TDengine.ErrorNo(res) != 0))
                {
                    Console.Write(sql.ToString() + " failure, ");
                    if (res != IntPtr.Zero)
                    {
                        Console.Write("reason: " + TDengine.Error(res));
                    }
                  
                    return new List<TDengneData>();
                }
                else
                {
                    int fieldCount = TDengine.FieldCount(res);
                    Console.WriteLine("field count: " + fieldCount);

                    List<TDengineMeta> metas = TDengine.FetchFields(res);
                    for (int j = 0; j < metas.Count; j++)
                    {
                        TDengineMeta meta = (TDengineMeta)metas[j];
                        Console.WriteLine("index:" + j + ", type:" + meta.type + ", typename:" + meta.TypeName() + ", name:" + meta.name + ", size:" + meta.size);
                    }

                    IntPtr rowdata;
                    StringBuilder builder = new StringBuilder();
                    while ((rowdata = TDengine.FetchRows(res)) != IntPtr.Zero)
                    {
                        queryRows++;
                        for (int fields = 0; fields < fieldCount; ++fields)
                        {
                            TDengineMeta meta = metas[fields];
                            int offset = IntPtr.Size * fields;
                            IntPtr data = Marshal.ReadIntPtr(rowdata, offset);

                            builder.Append("---");

                            if (data == IntPtr.Zero)
                            {
                                builder.Append("NULL");
                                continue;
                            }

                            switch ((TDengineDataType)meta.type)
                            {
                                case TDengineDataType.TSDB_DATA_TYPE_BOOL:
                                    bool v1 = Marshal.ReadByte(data) == 0 ? false : true;
                                    builder.Append(v1);
                                    break;
                                case TDengineDataType.TSDB_DATA_TYPE_TINYINT:
                                    byte v2 = Marshal.ReadByte(data);
                                    builder.Append(v2);
                                    break;
                                case TDengineDataType.TSDB_DATA_TYPE_SMALLINT:
                                    short v3 = Marshal.ReadInt16(data);
                                    builder.Append(v3);
                                    break;
                                case TDengineDataType.TSDB_DATA_TYPE_INT:
                                    int v4 = Marshal.ReadInt32(data);
                                    builder.Append(v4);
                                    break;
                                case TDengineDataType.TSDB_DATA_TYPE_BIGINT:
                                    long v5 = Marshal.ReadInt64(data);
                                    builder.Append(v5);
                                    break;
                                case TDengineDataType.TSDB_DATA_TYPE_FLOAT:
                                    float v6 = (float)Marshal.PtrToStructure(data, typeof(float));
                                    builder.Append(v6);
                                    break;
                                case TDengineDataType.TSDB_DATA_TYPE_DOUBLE:
                                    double v7 = (double)Marshal.PtrToStructure(data, typeof(double));
                                    builder.Append(v7);
                                    break;
                                case TDengineDataType.TSDB_DATA_TYPE_BINARY:
                                    string v8 = Marshal.PtrToStringAnsi(data);
                                    builder.Append(v8);
                                    break;
                                case TDengineDataType.TSDB_DATA_TYPE_TIMESTAMP:
                                    long v9 = Marshal.ReadInt64(data);
                                    builder.Append(v9);
                                    break;
                                case TDengineDataType.TSDB_DATA_TYPE_NCHAR:
                                    string v10 = Marshal.PtrToStringAnsi(data);
                                    builder.Append(v10);
                                    break;
                                case TDengineDataType.TSDB_DATA_TYPE_UTINYINT:
                                    byte v11 = Marshal.ReadByte(data);
                                    builder.Append(v11);
                                    break;
                                case TDengineDataType.TSDB_DATA_TYPE_USMALLINT:
                                    ushort v12 = (ushort)Marshal.ReadInt16(data);
                                    builder.Append(v12);
                                    break;
                                case TDengineDataType.TSDB_DATA_TYPE_UINT:
                                    uint v13 = (uint)Marshal.ReadInt32(data);
                                    builder.Append(v13);
                                    break;
                                case TDengineDataType.TSDB_DATA_TYPE_UBIGINT:
                                    ulong v14 = (ulong)Marshal.ReadInt64(data);
                                    builder.Append(v14);
                                    break;
                            }
                        }
                        builder.Append("---");

                        if (queryRows <= 20)
                        {
                            Console.WriteLine(builder.ToString());
                        }
                        builder.Clear();
                    }
                }
                return new List<TDengneData>();
            }
            catch (Exception ex)
            {
                return new List<TDengneData>();

            }

        }

        /// <summary>
        /// 时间转换
        /// </summary>
        /// <param name="dateTime"></param>
        /// <returns></returns>
        public long GetDataTimeToLong(DateTime dateTime)
        {
            return (long)(DateTime.Now.Subtract(new DateTime(1970, 1, 1, 0, 0, 0, 0)).TotalMilliseconds);
        }


    }
}

**Comment by xleili** [comment]
在方法 public List<TDengneData> ExecuteReader(string sql)的最后需要用    
TDengine.FreeResult(res)释放result。
你在加上再试试看

**Comment by xiaopenggogo** [comment]
恩恩，可以了，两个问题都好了。 谢谢。
Maikebing.Data.Taos  这个难道他们没有写好吗？

**Comment by xiaopenggogo** [comment]
![image](https://user-images.githubusercontent.com/97154895/148221506-2bccfb4c-5560-4062-b6b8-88a600d68209.png)

这个看源码是有的

**Comment by xiaopenggogo** [comment]
![image](https://user-images.githubusercontent.com/97154895/148222339-62314220-c233-40c1-95a7-82ee1ab19d18.png)
搞定

**Comment by Jiang4794** [comment]
> 版本是2.4.0
我的数据插入之后也是内存飙升，可以和我说一下怎么解决吗？非常感谢
