### ISSUE TITLE
taos.exe on Windows will shut down automatically after running for a while

### ISSUE THREAD

**Issue by zhaofjim** [taosdata/TDengine#963]
Windows打开taos.exe,一会儿就自动关闭了

**Comment by guanshengliang** [comment]
The description of this issue is not clear
You may not be connected to the database
Please set debugFlag to 135, and then upload the log file

**Comment by guanshengliang** [comment]
There is no response to this issue for a long time, and this issue has been fixed in 2.0 version, so close it
