### ISSUE TITLE
[GO connector]，my application program often crashes when using rows.Next() in query

### ISSUE THREAD

**Issue by xaseven** [taosdata/TDengine#964]
程序初始化的时候，建立一个连接：
GlobalTaoDB, err = sql.Open("taosSql", connstr)
然后整个工程都使用这个全局的 GlobalTaoDB进行操作；
rows, err :=  taodb. GlobalTaoDB.Query("select * from ...")
for rows.Next(){ //经常这里是调用SDK的result.go中的taos_fetch_row的时候崩溃....
    var .....
    rows.Scan(&.....)
}

**Comment by hzcheng** [comment]
您程序是多线程的吗？如果是，建议一个线程一个连接，因为目前连接不是线程安全的。后续我们会把连接改成线程安全的。

**Comment by xaseven** [comment]
我用的beego框架，目前看来，貌似只能每Query一次，就连一次，然后再关闭连接。
貌似beego的路由函数都是不同的线程发起的；
我即使是单独给每个路由建立一个连接器的连接应该也不行；

**Comment by plum-lihui** [comment]
taos客户端目前只能支持一个线程使用一个连接，而不能多线程共用连接。这个必须保证才能保证业务正常。对于crash问题，如果是libtaos.so中，应该会有core文件生成，请发送给我们分析一下。邮箱：huili@taosdata.com
多谢！

**Comment by plum-lihui** [comment]
请取最新代码的go connector进行验证。
多谢！

**Comment by DarkGodOne** [comment]
我也遇到了同样的问题，使用的版本是2.2.1.3版本，目前驱动线程不安全，go run的机制又恰好会触发线程安全，所以导致程序崩溃，暂时解决办法是自己建立一个连接池，按照线程id进行存储，并且加锁，同一个线程访问的时候需要先加锁再访问指定的连接，即可解决该问题，如果使用defer释放锁的时候，需要注意defer调用时的当前线程可能与调用线程不在同一个线程里，所以defer时需要按照连接反查对应的锁然后释放，否则会触发解锁未上锁的mutex的错误。
希望这个机制可以直接加在go的drive里面，会省去很多麻烦

**Comment by huskar-t** [comment]
> 我也遇到了同样的问题，使用的版本是2.2.1.3版本，目前驱动线程不安全，go run的机制又恰好会触发线程安全，所以导致程序崩溃，暂时解决办法是自己建立一个连接池，按照线程id进行存储，并且加锁，同一个线程访问的时候需要先加锁再访问指定的连接，即可解决该问题，如果使用defer释放锁的时候，需要注意defer调用时的当前线程可能与调用线程不在同一个线程里，所以defer时需要按照连接反查对应的锁然后释放，否则会触发解锁未上锁的mutex的错误。 希望这个机制可以直接加在go的drive里面，会省去很多麻烦

@DarkGodOne 
有复现触发崩溃的简易用例吗?
如果使用 `github.com/taosdata/driver-go/v2/taosSql` 驱动可以直接使用 `database/sql` 的连接池

**Comment by DarkGodOne** [comment]
> > 我也遇到了同样的问题，使用的版本是2.2.1.3版本，目前驱动线程不安全，go run的机制又恰好会触发线程安全，所以导致程序崩溃，暂时解决办法是自己建立一个连接池，按照线程id进行存储，并且加锁，同一个线程访问的时候需要先加锁再访问指定的连接，即可解决该问题，如果使用defer释放锁的时候，需要注意defer调用时的当前线程可能与调用线程不在同一个线程里，所以defer时需要按照连接反查对应的锁然后释放，否则会触发解锁未上锁的mutex的错误。 希望这个机制可以直接加在go的drive里面，会省去很多麻烦
> 
> @DarkGodOne 有复现触发崩溃的简易用例吗? 如果使用 `github.com/taosdata/driver-go/v2/taosSql` 驱动可以直接使用 `database/sql` 的连接池

我记得之前不能用的，而且你们文档说最好每个线程创建一个句柄，意思是现在可以了？？？

**Comment by huskar-t** [comment]
@DarkGodOne 已经修改过了
