### ISSUE TITLE
Golang connector 插入中文字符乱码

### ISSUE THREAD

**Issue by fetaoily** [taosdata/TDengine#9660]
**使用Golang Connector 执行插入数据的操作，当有“”中文“”时报错、乱码**
**一、 插入 “单字符” 中文报错**
执行语句：
`insertRes, err := db.TaosDb.Exec(sql, "1641010332000", "'阴'", 9, 32, "'东南'", 2)`
报错信息：
`[0x216] invalid operation: '阴' (Invalid argument)`
**二、插入 “多字符” 中文乱码**
执行语句：
`insertRes, err := db.TaosDb.Exec(sql, "1641010332000", "'阴天'", 9, 32, "'东南'", 2)`
查询数据：
![image](https://user-images.githubusercontent.com/501984/148474748-1c09dad7-55c0-4255-98bd-53e6d0a17a35.png)

----
**补充说明**
SQL语句:
`INSERT INTO D110000 (ts, text, temperature, humidity, wind_direction, wind_scale) VALUES (?, ?, ?, ?, ?, ?)`
表结构：
![image](https://user-images.githubusercontent.com/501984/148475078-6f8fa339-a913-4886-aaa7-719457b4afbf.png)

taos --version 
version: 2.4.0.0

**Comment by huskar-t** [comment]
@fetaoily 请提供运行环境，尝试 gomod 使用 
`github.com/taosdata/driver-go/v2 latest`
执行 `go mod tidy`
附上测试用例

```go
func TestChinese(t *testing.T) {
	db, err := sql.Open(driverName, dataSourceName)
	if err != nil {
		t.Fatalf("error on:  sql.open %s", err.Error())
		return
	}
	defer db.Close()
	_, err = db.Exec("create database if not exists test_chinese")
	if err != nil {
		t.Error(err)
		return
	}
	_, err = db.Exec("drop table if exists test_chinese.chinese")
	if err != nil {
		t.Error(err)
		return
	}
	_, err = db.Exec("create table if not exists test_chinese.chinese(ts timestamp,value nchar(32))")
	if err != nil {
		t.Error(err)
		return
	}
	_, err = db.Exec(`INSERT INTO test_chinese.chinese (ts, value) VALUES (?, ?)`,"1641010332000", "'阴天'")
	if err != nil {
		t.Error(err)
		return
	}
	rows, err := db.Query("select * from test_chinese.chinese")
	if err != nil {
		t.Error(err)
		return
	}
	counter := 0
	for rows.Next() {
		counter += 1
		row := make([]driver.Value, 2)
		err := rows.Scan(&row[0], &row[1])
		if err != nil {
			t.Error(err)
			return
		}
		t.Log(row)
	}
	assert.Equal(t, 1, counter)
}

```

测试结果

```
=== RUN   TestChinese
    driver_test.go:487: [2022-01-01 12:12:12 +0800 CST 阴天]
--- PASS: TestChinese (442.17s)
PASS
```

**Comment by fetaoily** [comment]
@huskar-t 使用您提供的测试代码, 重新做了测试, 测试结果如下:

> 1. **Linux** 生产环境: **正常**(没有乱码)
> 2. **Windows** 开发环境: **异常**(有乱码)

Windows开发环境:

> Windows11 version 21H2(OS Build 22000.376)
> taos --version version: 2.4.0.0
> go version go1.17.2 windows/amd64

**Comment by afwerar** [comment]
你在把配置文件里的charset参数启用后再试试。
![image](https://user-images.githubusercontent.com/20500927/148745340-bd4a93da-29c4-4018-bc52-70ddb2c9222e.png)

**Comment by fetaoily** [comment]
@afwerar 已解决! 谢谢!
