### ISSUE TITLE
SQL return null value when using “where ts “ clause 

### ISSUE THREAD

**Issue by anitren** [taosdata/TDengine#9674]
### 超级表查询一个时间段的数据表达式为
  and ( ts >='2021-12-29 13:00:00.000'  and  ts <'2021-12-29 13:20:00.000' ) or  (ts >='2021-12-30 13:20:00.000'  and  ts <'2021-12-30 13:50:00.000')
查询的结果为空
  1.  and ( ts >='2021-12-29 13:00:00.000'  and  ts <'2021-12-29 13:20:00.000' )  是有结果的
  2.   and ts >='2021-12-30 13:20:00.000'  and  ts <'2021-12-30 13:50:00.000') 也是有结果的
应该为两个时间段的并集然而结果却为空

**Comment by yu285** [comment]
当前不支持多个时间段的结果返回
