### ISSUE TITLE
compile with arm-linux-gcc

### ISSUE THREAD

**Issue by zschong** [taosdata/TDengine#968]
CC=arm-linux-gcc CXX=arm-linux-g++ cmake .. -DARMVER=arm32

**Comment by plum-lihui** [comment]
CMAKE_MINIMUM_REQUIRED(VERSION 2.8) 
#PROJECT(TDengine) 
 SET(CMAKE_C_STANDARD 11) 
SET(CMAKE_VERBOSE_MAKEFILE ON) 
SET(CMAKE_SYSTEM_NAME Linux) 
set(CMAKE_C_COMPILER   /home/plum/git/armtoolchain/toolchain/host/usr/bin/arm-linux-gcc) 
set(CMAKE_CXX_COMPILER /home/plum/git/armtoolchain/toolchain/host/usr/bin/arm-linux-g++) 
 
PROJECT(TDengine)

请按照上面的语句修改CMakeListes.txt；
然后再进行编译：   sudo cmake .. -DARMVER=arm32;   sudo  make
