### ISSUE TITLE
最新版本：TD+EMQX 通过 Webhook + RESTful Connector批量插入数据,数据严重丢失问题

### ISSUE THREAD

**Issue by AdonLuo** [taosdata/TDengine#9695]
@sangshuduo mock.js 代码中我之前 const CLIENT_NUM = 100 每隔5秒100个客户端进行模拟推送，后面经测试当模拟推送的客户端数小于 6 的时候不会出现插入错误，大于6就出现了，所以并发应该很小
_Originally posted by @AdonLuo in https://github.com/taosdata/TDengine/issues/6578#issuecomment-866485941_

由于之前问题未能解决，在最新版本环境下再次测试：

测试前提: mock.js 模拟100个客户端，间隔5秒推送一次数据

场景一: 
EMQX: 4.3.7
TD：2.2.2.0
结果: 大部分插入失败,之前解释是消费能力不足，EMQX 推送返回507错误
EMQX日志
![image](https://user-images.githubusercontent.com/19642911/148679277-5dddf846-4798-4688-bf9d-1463202719fb.png)

TD日志
![image](https://user-images.githubusercontent.com/19642911/148679289-84c165d1-dd9c-4a28-9c0e-23478da705c3.png)

场景二：
EMQX:4.3.11
TD: 2.2.2.10
结果: 大部分插入失败
EMQX日志
![image](https://user-images.githubusercontent.com/19642911/148679314-1f7ebb39-7608-4cf1-9f08-0b0f14fe5e21.png)

TD日志
![image](https://user-images.githubusercontent.com/19642911/148679329-e816a2ea-a5f9-4033-80c1-9d9be277eb4a.png)

场景三：
EMQX: 4.3.11
TD：2.4.0.3 （发布新组件taosAdapter，作为TDengine的HTTP代理，替换TDengine中嵌入的旧httpd模块，接口保持不变）
结果: 无明显错误提示，但是数据量不对，命中800次，数据库插入234条，从 日志中 sessionID 可以看出 post sql 应该是有到TD的
TD日志 sessionID=800 ，实际插入条数234
![image](https://user-images.githubusercontent.com/19642911/148679353-0d3b30ca-7f4c-48b6-9cfe-5dcbe63e136d.png)
![image](https://user-images.githubusercontent.com/19642911/148679360-6c6a36b3-dd02-4dc7-a74b-f918737e7f5c.png)

EMQX日志
无错误警告日志输出
TD日志
无错误警告日志输出 ，sessionID=800 model=web

后面调整客户端数量，直至1个客户端正常，2个客户端间隔5秒同时上报，则出现数据丢失情况，未能入库，sessionID是对应上的

**Comment by sangshuduo** [comment]
好的，我们有空重现一下，图片看不清楚，就是之前的博客方法然后换成 2.4.0.3 是吧？

**Comment by AdonLuo** [comment]
@sangshuduo 你好，
是的，最终就是模拟发送http 插入sql，看能否数据不丢失，最新版本和之前版本相比，无明显的错误提示，之前版本还会报507错误。新版本从sessionID 看是收到的请求次数是正常的，实际入库的数据少了很多

**Comment by huskar-t** [comment]
@AdonLuo 如果按照以下配置
![image](https://user-images.githubusercontent.com/26872926/148713899-f3d4e11b-5ea4-4ad6-8ab3-e0f720b22322.png)
时间戳为 now 使用的是 taosd 服务器时间，如果并发过快会使时间戳重复导致看到入库的数据少。
可以修改测试脚本，将 now 改为一个自增的值，重新测试

**Comment by AdonLuo** [comment]
@huskar-t 嗯 是的，2.4 的版本通过设置数据库的时间戳级别，可以解决，测试过ns 级别没问题，us级别也还是有部分数据被丢失。
2.2 之前版本可能是httpd 方面问题，很多请求直接返回507错误，post 的 sql数据都没有到TD，2.4 新的http 代理就不会出现这种情况，数据都有到TD

**Comment by sangshuduo** [comment]
问题解决，关闭。
