### ISSUE TITLE
请问时间戳支持微妙级别该怎样设置？

### ISSUE THREAD

**Issue by density1970** [taosdata/TDengine#97]
请问有个实时金融数据一天4小时需要插入大约3000万笔数据，那么时间戳支持微妙级别（默认是毫秒级）该怎样设置？还有请问命令行程序taos支持哪些命令？  有文档说明么？

**Comment by riyun1989** [comment]
怎么感觉默认就是微妙，我安装完后查看默认的log数据里的ts字段是这样的： 19-07-18 10:25:20.173227，秒后面6位应该是微妙了吧

**Comment by density1970** [comment]
但是我安装完成后，插入一个ts字段，用now填充后,   select 的结果是 19-07-18 9:15:40.525，。。。

**Comment by density1970** [comment]
感谢您的回复！ 您说的没错，log数据库里面ts字段的确是秒后6位，但是我创建的新表，ts字段，插入now后秒后不是6位，是3位。是不是创建新表的时候要指定ts字段参数？ 




------------------ 原始邮件 ------------------
发件人: "riyun1989"<notifications@github.com>; 
发送时间: 2019年7月18日(星期四) 上午10:53
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>; 
抄送: "蓝色永恒"<7701619@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [taosdata/TDengine] 请问时间戳支持微妙级别该怎样设置？ (#97)




怎么感觉默认就是微妙，我安装完后查看默认的log数据里的ts字段是这样的： 19-07-18 10:25:20.173227，秒后面6位应该是微妙了吧

**Comment by riyun1989** [comment]
@density1970 可以看下，我也是昨天才开始看的

**Comment by riyun1989** [comment]
刚试过了，在log表中直接insert，用的也是now，但是结果是微妙：insert into log(ts,level,content,ipaddr) values(now,0,'111','192.168.0.120');，结果： 19-07-18 11:19:23.440497|     0|111                                                                             |192.168.0.120

**Comment by density1970** [comment]
我也测试了一下，在log数据库中新建表，insert, 用now，结果是微秒。  但是我新建的数据库test中,同样的建表操作，insert, 但是结果是毫秒。  看样子问题出在新建的数据库上，请指教。
  

 

 ------------------ 原始邮件 ------------------
  发件人: "riyun1989"<notifications@github.com>;
 发送时间: 2019年7月18日(星期四) 中午11:23
 收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
 抄送: "蓝色永恒"<7701619@qq.com>;"Mention"<mention@noreply.github.com>;
 主题: Re: [taosdata/TDengine] 请问时间戳支持微妙级别该怎样设置？ (#97)

 

 
刚试过了，在log表中直接insert，用的也是now，但是结果是微妙：insert into log(ts,level,content,ipaddr) values(now,0,'111','192.168.0.120');，结果： 19-07-18 11:19:23.440497| 0|111 |192.168.0.120

**Comment by density1970** [comment]
新建数据库的时候，怎么指定时间戳精度到微秒？？？
  

 

 ------------------ 原始邮件 ------------------
  发件人: "riyun1989"<notifications@github.com>;
 发送时间: 2019年7月18日(星期四) 中午11:23
 收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
 抄送: "蓝色永恒"<7701619@qq.com>;"Mention"<mention@noreply.github.com>;
 主题: Re: [taosdata/TDengine] 请问时间戳支持微妙级别该怎样设置？ (#97)

 

 
刚试过了，在log表中直接insert，用的也是now，但是结果是微妙：insert into log(ts,level,content,ipaddr) values(now,0,'111','192.168.0.120');，结果： 19-07-18 11:19:23.440497| 0|111 |192.168.0.120

**Comment by riyun1989** [comment]
我估计找到原因了，你 show databases;看下time precision这个值就知道原因了。你可以试试

**Comment by density1970** [comment]
show databases；的结果是： 除了log数据库的time precision是us， 其他库的time precision字段是ms，  问题是我怎么把自建库的time precision设置成us???

  

 ------------------ 原始邮件 ------------------
  发件人: "riyun1989"<notifications@github.com>;
 发送时间: 2019年7月18日(星期四) 中午11:53
 收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
 抄送: "蓝色永恒"<7701619@qq.com>;"Mention"<mention@noreply.github.com>;
 主题: Re: [taosdata/TDengine] 请问时间戳支持微妙级别该怎样设置？ (#97)

 

 
我估计找到原因了，你 show databases;看下time precision这个值就知道原因了。你可以试试

**Comment by riyun1989** [comment]
@density1970 查看文档，建库语句：create database test precision 'us' ;  precision有两个可选项一个是ms一个是us

**Comment by riyun1989** [comment]
文档19.1小节下面的注意，那里有数据库的可选参数配置：
![image](https://user-images.githubusercontent.com/35788805/61431921-6997f900-a961-11e9-8769-9b8cfbc848ca.png)

**Comment by density1970** [comment]
收到，谢谢！  
  

 

 ------------------ 原始邮件 ------------------
  发件人: "riyun1989"<notifications@github.com>;
 发送时间: 2019年7月18日(星期四) 中午1:39
 收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
 抄送: "蓝色永恒"<7701619@qq.com>;"Mention"<mention@noreply.github.com>;
 主题: Re: [taosdata/TDengine] 请问时间戳支持微妙级别该怎样设置？ (#97)

 

 
文档19.1小节下面的注意，那里有数据库的可选参数配置：

**Comment by wuyetuzhunan2018** [comment]
> 文档19.1小节下面的注意，那里有数据库的可选参数配置：
> ![image](https://user-images.githubusercontent.com/35788805/61431921-6997f900-a961-11e9-8769-9b8cfbc848ca.png)

你好，文档是从哪里找到的？

**Comment by density1970** [comment]
https://www.taosdata.com/cn/documentation/
  
  
  

 

 ------------------ 原始邮件 ------------------
  发件人: "wuyetuzhunan2018"<notifications@github.com>;
 发送时间: 2019年7月25日(星期四) 晚上8:28
 收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
 抄送: "蓝色永恒"<7701619@qq.com>;"Mention"<mention@noreply.github.com>;
 主题: Re: [taosdata/TDengine] 请问时间戳支持微妙级别该怎样设置？ (#97)

 

  
文档19.1小节下面的注意，那里有数据库的可选参数配置：

 
你好，文档是从哪里找到的？

**Comment by wuyetuzhunan2018** [comment]
> https://www.taosdata.com/cn/documentation/
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "wuyetuzhunan2018"<notifications@github.com>; 发送时间: 2019年7月25日(星期四) 晚上8:28 收件人: "taosdata/TDengine"<TDengine@noreply.github.com>; 抄送: "蓝色永恒"<7701619@qq.com>;"Mention"<mention@noreply.github.com>; 主题: Re: [taosdata/TDengine] 请问时间戳支持微妙级别该怎样设置？ (#97) 文档19.1小节下面的注意，那里有数据库的可选参数配置： 你好，文档是从哪里找到的？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

您好，感谢回复，我想问一下，
![image](https://user-images.githubusercontent.com/41765962/61915628-fea97c00-af77-11e9-829a-10a4024fcf07.png)包含这个图片的文档是在哪下载的？

**Comment by density1970** [comment]
不好意思，我也不记得是哪里下载到的了，我手头有这个PDF文档，如果您需要我可以发邮件给您。





------------------ 原始邮件 ------------------
发件人: "wuyetuzhunan2018"<notifications@github.com>;
发送时间: 2019年7月26日(星期五) 上午7:36
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
抄送: "蓝色永恒"<7701619@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [taosdata/TDengine] 请问时间戳支持微妙级别该怎样设置？ (#97)



 
https://www.taosdata.com/cn/documentation/
 …
 ------------------ 原始邮件 ------------------ 发件人: "wuyetuzhunan2018"notifications@github.com; 发送时间: 2019年7月25日(星期四) 晚上8:28 收件人: "taosdata/TDengine"TDengine@noreply.github.com; 抄送: "蓝色永恒"7701619@qq.com;"Mention"mention@noreply.github.com; 主题: Re: [taosdata/TDengine] 请问时间戳支持微妙级别该怎样设置？ (#97) 文档19.1小节下面的注意，那里有数据库的可选参数配置： 你好，文档是从哪里找到的？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.
  
您好，感谢回复，我想问一下，
 包含这个图片的文档是在哪下载的？

**Comment by wuyetuzhunan2018** [comment]
> 不好意思，我也不记得是哪里下载到的了，我手头有这个PDF文档，如果您需要我可以发邮件给您。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "wuyetuzhunan2018"<notifications@github.com>; 发送时间: 2019年7月26日(星期五) 上午7:36 收件人: "taosdata/TDengine"<TDengine@noreply.github.com>; 抄送: "蓝色永恒"<7701619@qq.com>;"Mention"<mention@noreply.github.com>; 主题: Re: [taosdata/TDengine] 请问时间戳支持微妙级别该怎样设置？ (#97) https://www.taosdata.com/cn/documentation/ … ------------------ 原始邮件 ------------------ 发件人: "wuyetuzhunan2018"notifications@github.com; 发送时间: 2019年7月25日(星期四) 晚上8:28 收件人: "taosdata/TDengine"TDengine@noreply.github.com; 抄送: "蓝色永恒"7701619@qq.com;"Mention"mention@noreply.github.com; 主题: Re: [taosdata/TDengine] 请问时间戳支持微妙级别该怎样设置？ (#97) 文档19.1小节下面的注意，那里有数据库的可选参数配置： 你好，文档是从哪里找到的？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread. 您好，感谢回复，我想问一下， 包含这个图片的文档是在哪下载的？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

麻烦发我一下把，"434341228@qq.com"，这是我的邮箱，十分感谢！

**Comment by density1970** [comment]
邮件已发，请查收。




------------------ 原始邮件 ------------------
发件人: "wuyetuzhunan2018"<notifications@github.com>;
发送时间: 2019年7月26日(星期五) 上午10:05
收件人: "taosdata/TDengine"<TDengine@noreply.github.com>;
抄送: "蓝色永恒"<7701619@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [taosdata/TDengine] 请问时间戳支持微妙级别该怎样设置？ (#97)



 
不好意思，我也不记得是哪里下载到的了，我手头有这个PDF文档，如果您需要我可以发邮件给您。
 …
 ------------------ 原始邮件 ------------------ 发件人: "wuyetuzhunan2018"notifications@github.com; 发送时间: 2019年7月26日(星期五) 上午7:36 收件人: "taosdata/TDengine"TDengine@noreply.github.com; 抄送: "蓝色永恒"7701619@qq.com;"Mention"mention@noreply.github.com; 主题: Re: [taosdata/TDengine] 请问时间戳支持微妙级别该怎样设置？ (#97) https://www.taosdata.com/cn/documentation/ … ------------------ 原始邮件 ------------------ 发件人: "wuyetuzhunan2018"notifications@github.com; 发送时间: 2019年7月25日(星期四) 晚上8:28 收件人: "taosdata/TDengine"TDengine@noreply.github.com; 抄送: "蓝色永恒"7701619@qq.com;"Mention"mention@noreply.github.com; 主题: Re: [taosdata/TDengine] 请问时间戳支持微妙级别该怎样设置？ (#97) 文档19.1小节下面的注意，那里有数据库的可选参数配置： 你好，文档是从哪里找到的？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread. 您好，感谢回复，我想问一下， 包含这个图片的文档是在哪下载的？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.
  
麻烦发我一下把，"434341228@qq.com"，这是我的邮箱，十分感谢！

**Comment by hsnxiaoning** [comment]
> 邮件已发，请查收。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "wuyetuzhunan2018"<notifications@github.com>; 发送时间: 2019年7月26日(星期五) 上午10:05 收件人: "taosdata/TDengine"<TDengine@noreply.github.com>; 抄送: "蓝色永恒"<7701619@qq.com>;"Mention"<mention@noreply.github.com>; 主题: Re: [taosdata/TDengine] 请问时间戳支持微妙级别该怎样设置？ (#97) 不好意思，我也不记得是哪里下载到的了，我手头有这个PDF文档，如果您需要我可以发邮件给您。 … ------------------ 原始邮件 ------------------ 发件人: "wuyetuzhunan2018"notifications@github.com; 发送时间: 2019年7月26日(星期五) 上午7:36 收件人: "taosdata/TDengine"TDengine@noreply.github.com; 抄送: "蓝色永恒"7701619@qq.com;"Mention"mention@noreply.github.com; 主题: Re: [taosdata/TDengine] 请问时间戳支持微妙级别该怎样设置？ (#97) https://www.taosdata.com/cn/documentation/ … ------------------ 原始邮件 ------------------ 发件人: "wuyetuzhunan2018"notifications@github.com; 发送时间: 2019年7月25日(星期四) 晚上8:28 收件人: "taosdata/TDengine"TDengine@noreply.github.com; 抄送: "蓝色永恒"7701619@qq.com;"Mention"mention@noreply.github.com; 主题: Re: [taosdata/TDengine] 请问时间戳支持微妙级别该怎样设置？ (#97) 文档19.1小节下面的注意，那里有数据库的可选参数配置： 你好，文档是从哪里找到的？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread. 您好，感谢回复，我想问一下， 包含这个图片的文档是在哪下载的？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread. 麻烦发我一下把，"434341228@qq.com"，这是我的邮箱，十分感谢！ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

您好，请问可以给我发一份文档吗？
我的邮箱377746620@qq.com

**Comment by lnparker** [comment]
您好，请问可以给我发一份文档吗？
我的邮箱834484158@qq.com

**Comment by zhangzl0119** [comment]
您好，请问可以给我发一份文档吗？
我的邮箱1095865334@qq.com
