### ISSUE TITLE
taos connect failed, reason: Unable to establish connection.

### ISSUE THREAD

**Issue by Loryed** [taosdata/TDengine#9715]
version：2.2.2.0
win10客户端，ubuntu1804服务端
tar安装包安装

问题：在物理机windows上的客户端连不上虚拟机上的服务端，FAQ上的都检查过，没有发现问题

另外，一开始在局域网环境下，客户端服务端安装后就能直接连接使用，最近在车上给电脑连过手机热点后就一直连不上了（不知道和这个有没有关系

后来配置过fqdn，防火墙也关了，问题还是一样

一次通过fqdn连接，客户端产生的日志：
==================================================
                new log file                      
==================================================
01/10 19:14:49.625000 00006592 UTL localEp is: louie.domain.com:6030
01/10 19:14:49.625000 00006592 UTL timezone not configured, use default
01/10 19:14:49.673000 00006592 UTL locale not configured, set to default:Chinese_China.936
01/10 19:14:49.673000 00006592 UTL charset not configured, set to default:cp936
01/10 19:14:49.673000 00006592 UTL    check global cfg completed
01/10 19:14:49.673000 00006592 UTL ==================================
01/10 19:14:49.673000 00006592 UTL    taos config & system info:
01/10 19:14:49.673000 00006592 UTL ==================================
01/10 19:14:49.673000 00006592 UTL  firstEp:                louie.domain.com:6030 
01/10 19:14:49.673000 00006592 UTL  secondEp:               louie.domain.com:6030 
01/10 19:14:49.673000 00006592 UTL  fqdn:                   louie.domain.com 
01/10 19:14:49.673000 00006592 UTL  serverPort:             6030 
01/10 19:14:49.673000 00006592 UTL  configDir:              C:\TDengine\cfg 
01/10 19:14:49.674000 00006592 UTL  logDir:                 C:\TDengine\log 
01/10 19:14:49.674000 00006592 UTL  scriptDir:              C:/TDengine/script 
01/10 19:14:49.674000 00006592 UTL  arbitrator:              
01/10 19:14:49.674000 00006592 UTL  numOfThreadsPerCore:    1.000000 
01/10 19:14:49.674000 00006592 UTL  maxNumOfDistinctRes:    10000000 
01/10 19:14:49.674000 00006592 UTL  rpcTimer:               300(ms)
01/10 19:14:49.674000 00006592 UTL  rpcMaxTime:             600(s)
01/10 19:14:49.674000 00006592 UTL  rpcForceTcp:            0 
01/10 19:14:49.674000 00006592 UTL  shellActivityTimer:     3(s)
01/10 19:14:49.674000 00006592 UTL  compressMsgSize:        -1 
01/10 19:14:49.674000 00006592 UTL  maxSQLLength:           1048576(byte)
01/10 19:14:49.674000 00006592 UTL  maxWildCardsLength:     100(byte)
01/10 19:14:49.674000 00006592 UTL  maxNumOfOrderedRes:     1000000 
01/10 19:14:49.674000 00006592 UTL  keepColumnName:         1 
01/10 19:14:49.674000 00006592 UTL  timezone:               not configured 
01/10 19:14:49.674000 00006592 UTL  locale:                 Chinese_China.936 
01/10 19:14:49.674000 00006592 UTL  charset:                cp936 
01/10 19:14:49.674000 00006592 UTL  numOfLogLines:          10000000 
01/10 19:14:49.674000 00006592 UTL  logKeepDays:            0 
01/10 19:14:49.674000 00006592 UTL  asyncLog:               1 
01/10 19:14:49.674000 00006592 UTL  debugFlag:              0 
01/10 19:14:49.674000 00006592 UTL  rpcDebugFlag:           131 
01/10 19:14:49.674000 00006592 UTL  tmrDebugFlag:           131 
01/10 19:14:49.674000 00006592 UTL  cDebugFlag:             131 
01/10 19:14:49.674000 00006592 UTL  jniDebugFlag:           131 
01/10 19:14:49.674000 00006592 UTL  odbcDebugFlag:          131 
01/10 19:14:49.674000 00006592 UTL  uDebugFlag:             131 
01/10 19:14:49.674000 00006592 UTL  qDebugFlag:             131 
01/10 19:14:49.674000 00006592 UTL  tsdbDebugFlag:          131 
01/10 19:14:49.674000 00006592 UTL  gitinfo:                06c7ae903170ae964cb59da757b97b34156aec4b 
01/10 19:14:49.674000 00006592 UTL  gitinfoOfInternal:      25b460c7320bcd9f63c4b8d6453e9bb4e392119e 
01/10 19:14:49.674000 00006592 UTL  buildinfo:              Built at 2021-11-17 15:56:03 
01/10 19:14:49.674000 00006592 UTL  version:                2.2.2.0 
01/10 19:14:49.674000 00006592 UTL  maxBinaryDisplayWidth:  30 
01/10 19:14:49.674000 00006592 UTL  tempDir:                C:\Users\jiang\AppData\Local\Temp 
01/10 19:14:49.674000 00006592 UTL  os numOfCores:          8
01/10 19:14:49.674000 00006592 UTL  os totalMemory:         7069(MB)
01/10 19:14:49.674000 00006592 UTL ==================================
01/10 19:14:49.674000 00006592 UTL  dataDir: C:/TDengine/data level:0 primary:1
01/10 19:14:49.674000 00006592 UTL ==================================

**Comment by Loryed** [comment]
补充
服务端可以正常使用
客户端发起连接后，服务端没有产生相应日志

**Comment by Loryed** [comment]
添加debug 135后日志
==================================================
                new log file                      
==================================================
01/11 10:41:49.040000 00014840 UTL all debug flag are set to 135
01/11 10:41:49.040000 00014840 UTL all debug flag are set to 135
01/11 10:41:49.040000 00014840 UTL localEp is: louie.domain.com:6030
01/11 10:41:49.040000 00014840 UTL timezone not configured, use default
01/11 10:41:49.089000 00014840 UTL locale not configured, set to default:Chinese_China.936
01/11 10:41:49.089000 00014840 UTL charset not configured, set to default:cp936
01/11 10:41:49.089000 00014840 UTL    check global cfg completed
01/11 10:41:49.089000 00014840 UTL ==================================
01/11 10:41:49.089000 00014840 UTL    taos config & system info:
01/11 10:41:49.089000 00014840 UTL ==================================
01/11 10:41:49.089000 00014840 UTL  firstEp:                louie.domain.com:6030 
01/11 10:41:49.089000 00014840 UTL  secondEp:               louie.domain.com:6030 
01/11 10:41:49.089000 00014840 UTL  fqdn:                   louie.domain.com 
01/11 10:41:49.089000 00014840 UTL  serverPort:             6030 
01/11 10:41:49.089000 00014840 UTL  configDir:              C:\TDengine\cfg 
01/11 10:41:49.089000 00014840 UTL  logDir:                 C:\TDengine\log 
01/11 10:41:49.089000 00014840 UTL  scriptDir:              C:/TDengine/script 
01/11 10:41:49.089000 00014840 UTL  arbitrator:              
01/11 10:41:49.089000 00014840 UTL  numOfThreadsPerCore:    1.000000 
01/11 10:41:49.089000 00014840 UTL  maxNumOfDistinctRes:    10000000 
01/11 10:41:49.089000 00014840 UTL  rpcTimer:               300(ms)
01/11 10:41:49.089000 00014840 UTL  rpcMaxTime:             600(s)
01/11 10:41:49.089000 00014840 UTL  rpcForceTcp:            0 
01/11 10:41:49.089000 00014840 UTL  shellActivityTimer:     3(s)
01/11 10:41:49.089000 00014840 UTL  compressMsgSize:        -1 
01/11 10:41:49.089000 00014840 UTL  maxSQLLength:           1048576(byte)
01/11 10:41:49.089000 00014840 UTL  maxWildCardsLength:     100(byte)
01/11 10:41:49.089000 00014840 UTL  maxNumOfOrderedRes:     1000000 
01/11 10:41:49.089000 00014840 UTL  keepColumnName:         1 
01/11 10:41:49.089000 00014840 UTL  timezone:               not configured 
01/11 10:41:49.089000 00014840 UTL  locale:                 Chinese_China.936 
01/11 10:41:49.089000 00014840 UTL  charset:                cp936 
01/11 10:41:49.089000 00014840 UTL  numOfLogLines:          10000000 
01/11 10:41:49.089000 00014840 UTL  logKeepDays:            0 
01/11 10:41:49.089000 00014840 UTL  asyncLog:               1 
01/11 10:41:49.089000 00014840 UTL  debugFlag:              135 
01/11 10:41:49.089000 00014840 UTL  rpcDebugFlag:           135 
01/11 10:41:49.089000 00014840 UTL  tmrDebugFlag:           131 
01/11 10:41:49.089000 00014840 UTL  cDebugFlag:             135 
01/11 10:41:49.089000 00014840 UTL  jniDebugFlag:           135 
01/11 10:41:49.089000 00014840 UTL  odbcDebugFlag:          135 
01/11 10:41:49.089000 00014840 UTL  uDebugFlag:             135 
01/11 10:41:49.089000 00014840 UTL  qDebugFlag:             135 
01/11 10:41:49.089000 00014840 UTL  tsdbDebugFlag:          135 
01/11 10:41:49.089000 00014840 UTL  gitinfo:                06c7ae903170ae964cb59da757b97b34156aec4b 
01/11 10:41:49.089000 00014840 UTL  gitinfoOfInternal:      25b460c7320bcd9f63c4b8d6453e9bb4e392119e 
01/11 10:41:49.089000 00014840 UTL  buildinfo:              Built at 2021-11-17 15:56:03 
01/11 10:41:49.089000 00014840 UTL  version:                2.2.2.0 
01/11 10:41:49.089000 00014840 UTL  maxBinaryDisplayWidth:  30 
01/11 10:41:49.089000 00014840 UTL  tempDir:                C:\Users\jiang\AppData\Local\Temp 
01/11 10:41:49.089000 00014840 UTL  os numOfCores:          8
01/11 10:41:49.089000 00014840 UTL  os totalMemory:         7069(MB)
01/11 10:41:49.089000 00014840 UTL ==================================
01/11 10:41:49.089000 00014840 UTL  dataDir: C:/TDengine/data level:0 primary:1
01/11 10:41:49.089000 00014840 UTL ==================================
01/11 10:41:49.092000 00014840 TSC starting to initialize TAOS client ...
01/11 10:41:49.092000 00014840 TSC Local End Point is:louie.domain.com:6030
01/11 10:41:49.093000 00014840 UTL tsc scheduler is initialized, numOfThreads:4
01/11 10:41:49.094000 00014840 TSC client task queue is initialized, numOfWorkers: 4
01/11 10:41:49.094000 00014840 UTL tmr scheduler is initialized, numOfThreads:1
01/11 10:41:49.095000 00014840 TSC TableMeta:000001BBD95308F0, vgroup:000001BBD952FD10 is initialized
01/11 10:41:49.095000 00014840 TSC client is initialized successfully
01/11 10:41:49.095000 00014840 TSC try to create a connection to louie.domain.com:6030, user:root db:(null)
01/11 10:41:49.095000 00014840 UTL pool:000001BBD952D900 is setup, maxId:5000
01/11 10:41:49.095000 00007232 UTL cache refresh thread starts
01/11 10:41:49.096000 00014840 UTL open udp socket:0x0:0
01/11 10:41:49.097000 00014840 UTL open udp socket:0x0:0
01/11 10:41:49.097000 00014840 UTL open udp socket:0x0:0
01/11 10:41:49.098000 00015440 RPC TSC UDP thread is created, index:0
01/11 10:41:49.098000 00014840 UTL open udp socket:0x0:0
01/11 10:41:49.098000 00002680 RPC TSC UDP thread is created, index:1
01/11 10:41:49.098000 00014840 RPC TSC UDP connection is initialized, ip:0:0 threads:4
01/11 10:41:49.098000 00014840 RPC TSC rpc is opened, threads:4 sessions:5000
01/11 10:41:49.098000 00009236 RPC TSC UDP thread is created, index:2
01/11 10:41:49.098000 00014840 UTL cache:rpcObj, key:00000075FABEEE70, 000001BBDC486970 added into cache, added:1641868909098, expire:1641868914098, totalNum:1 totalSize:616bytes size:520bytes
01/11 10:41:49.098000 00005424 RPC TSC UDP thread is created, index:3
01/11 10:41:49.098000 00014840 TSC 0x2 new SqlObj from 000001BBDC488690, total in tscObj:1, total:1
01/11 10:41:49.098000 00014840 TSC 0x2 SQL cmd:connect will be processed, name:, type:0
01/11 10:41:49.106000 00014840 RPC TSC 000001BBDC4BE1B8 client connection is allocated, uid:0xdc4c733b
01/11 10:41:49.106000 00014840 RPC TSC UDP connection is setup, ip:80d3a8c0:6030 localPort:64548
01/11 10:41:49.106000 00014840 RPC TSC 000001BBDC4BE1B8 0000000000000002, connect is sent to louie.domain.com:6030, len:377 sig:0x01000000:0x00000000:21804
01/11 10:41:49.106000 00002680 RPC TSC UDP socket was closed, exiting(No error), dataLen:-1 fd:688
01/11 10:41:49.409000 00003092 RPC TSC 000001BBDC4BE1B8 0000000000000002, expected connect-rsp is not received
01/11 10:41:49.409000 00003092 RPC TSC 000001BBDC4BE1B8 0000000000000002, re-send msg:connect to louie.domain.com:6030
01/11 10:41:49.409000 00003092 RPC TSC 000001BBDC4BE1B8 0000000000000002, connect is sent to louie.domain.com:6030, len:377 sig:0x01000000:0x00000000:21804
01/11 10:41:49.409000 00002680 RPC TSC UDP socket was closed, exiting(No error), dataLen:-1 fd:688
01/11 10:41:49.714000 00003092 RPC TSC 000001BBDC4BE1B8 0000000000000002, expected connect-rsp is not received
01/11 10:41:49.714000 00003092 RPC TSC 000001BBDC4BE1B8 0000000000000002, re-send msg:connect to louie.domain.com:6030
01/11 10:41:49.714000 00003092 RPC TSC 000001BBDC4BE1B8 0000000000000002, connect is sent to louie.domain.com:6030, len:377 sig:0x01000000:0x00000000:21804
01/11 10:41:49.714000 00002680 RPC TSC UDP socket was closed, exiting(No error), dataLen:-1 fd:688
01/11 10:41:50.019000 00003092 RPC TSC 000001BBDC4BE1B8 0000000000000002, expected connect-rsp is not received
01/11 10:41:50.019000 00003092 RPC TSC 000001BBDC4BE1B8 0000000000000002, re-send msg:connect to louie.domain.com:6030
01/11 10:41:50.019000 00003092 RPC TSC 000001BBDC4BE1B8 0000000000000002, connect is sent to louie.domain.com:6030, len:377 sig:0x01000000:0x00000000:21804
01/11 10:41:50.019000 00002680 RPC TSC UDP socket was closed, exiting(No error), dataLen:-1 fd:688

**Comment by kaybinwong** [comment]
fqdn设置了没有？

**Comment by Loryed** [comment]
重新安装和配置，已解决
