### ISSUE TITLE
C# issue

### ISSUE THREAD

**Issue by xiaopenggogo** [taosdata/TDengine#9723]
1、使用Maikebing.Data.Taos时 设置Charset = "UTF-8" 插入报错。   当去掉Charset = "UTF-8"可正常插入，但是中文列乱码。
2、修改
![image](https://user-images.githubusercontent.com/97154895/148871499-ab86d7c6-5258-4bc6-924b-04aa773f4078.png)
这个地方插入依然报错。  请问如何解决这个问题。谢谢

**Comment by xiaopenggogo** [comment]
![image](https://user-images.githubusercontent.com/97154895/148871646-739008be-e6aa-4431-b754-0896ebed5af7.png)

**Comment by sangshuduo** [comment]
Windows 吗？

**Comment by xiaopenggogo** [comment]
Windows 开发环境

**Comment by xiaopenggogo** [comment]
报错信息：
invalid operation: '低压凝汽器真空' (Invalid argument)

**Comment by xiaopenggogo** [comment]
我是windows向liunx中写数据

**Comment by sangshuduo** [comment]
确认是有问题，我们尽快修一下

**Comment by xiaopenggogo** [comment]
好的，修复完麻烦通知一声，谢谢

**Comment by xiaopenggogo** [comment]
![image](https://user-images.githubusercontent.com/97154895/149044407-ecbb969d-7b8c-46a5-81f5-c1988a18ebb2.png)
![image](https://user-images.githubusercontent.com/97154895/149044458-422fe188-6af5-4b07-8ac1-8defc63bd8c3.png)
C#程序跟ui客户端读出来都是正常的，taos客户端跟Python是乱码。

**Comment by xleili** [comment]
C#的中文是往nchar 里面insert吗？

**Comment by xiaopenggogo** [comment]
是的

**Comment by xleili** [comment]
> 是的

ok，这个问题我正在改，在windows上确实存在。

**Comment by xleili** [comment]
> 好的，修复完麻烦通知一声，谢谢

这个已经修复了。再最新的develop分支

**Comment by xiaopenggogo** [comment]
您好，请一下我更新客户端还是更新服务端。

**Comment by xleili** [comment]
> 您好，请问一下我更新客户端还是更新服务端。
这个问题不是客户端或者服务器导致的。是C# driver
的问题。更新一下c# driver. https://github.com/taosdata/TDengine/tree/develop/src/connector/C%23/src/TDengineDriver
使用sample:  https://github.com/taosdata/TDengine/tree/develop/tests/examples/C%23/insertCn

**Comment by xiaopenggogo** [comment]
![image](https://user-images.githubusercontent.com/97154895/151091961-b6ad5e8e-88e8-42cb-b56e-77d430cfac97.png)
是不是处理了这一块？    这个是net4.5使用不了哦。4.5里面没有这个方法存在

**Comment by xleili** [comment]
是修改了这部分

**Comment by xiaopenggogo** [comment]
![image](https://user-images.githubusercontent.com/97154895/151094490-570340f1-fd86-4c1e-a373-4eac94c1a684.png)
嗯嗯，对我问题不大，我能使用。

**Comment by xleili** [comment]
> ![image](https://user-images.githubusercontent.com/97154895/151094490-570340f1-fd86-4c1e-a373-4eac94c1a684.png) 嗯嗯，对我问题不大，我能使用。

记得读的时候也要读成utf-8，不然会有乱码

**Comment by xiaopenggogo** [comment]
static public IntPtr Query(IntPtr conn, string command)
        {
            IntPtr res = IntPtr.Zero;
            // IntPtr commandBuffer = Marshal.StringToCoTaskMemUTF8(command);
            IntPtr commandBuffer = MarshalManagedToNative(command);
            res = Query(conn, commandBuffer);
            return res;
        }



        static private IntPtr MarshalManagedToNative(object ManagedObj)
        {
            if (ManagedObj == null)
                return IntPtr.Zero;
            if (ManagedObj.GetType() != typeof(string))
                throw new ArgumentException("ManagedObj", "Can only marshal type of System.String");
            byte[] array = Encoding.UTF8.GetBytes((string)ManagedObj);
            int size = Marshal.SizeOf(array[0]) * array.Length + Marshal.SizeOf(array[0]);
            IntPtr ptr = Marshal.AllocHGlobal(size);
            Marshal.Copy(array, 0, ptr, array.Length);
            Marshal.WriteByte(ptr, size - 1, 0);
            return ptr;
        }


你试试这种写法是不是跟这个Marshal.StringToCoTaskMemUTF8一样的意思，我没有试，你可以试试。如果效果一样就部分运行项目版本了。
