### ISSUE TITLE
alert functionality are limited

### ISSUE THREAD

**Issue by Kolo7** [taosdata/TDengine#9726]
描述：使用alert插件配合alertmanager做告警，但是发现由于sql和alert插件的限制性，写不出复杂的告警策略。
表结构：
             Field              |         Type         |   Length    |   Note   |
=================================================================================
 ts                             | TIMESTAMP            |           8 |          |
 value                          | DOUBLE               |           8 |          |
 taghash                        | BINARY               |          34 | TAG      |
 t_appid                        | BINARY               |         128 | TAG      |
 t_application                  | BINARY               |         128 | TAG      |
 t_channel_id                   | BINARY               |         128 | TAG      |
 t_code                         | BINARY               |         128 | TAG      |
 t_env                          | BINARY               |         128 | TAG      |
 t_hostname                     | BINARY               |         128 | TAG      |
 t_idc                          | BINARY               |         128 | TAG      |
 t_instance                     | BINARY               |         128 | TAG      |
 t_job                          | BINARY               |         128 | TAG      |
 t_xgappid                      | BINARY               |         128 | TAG      |
 t_xgenv                        | BINARY               |         128 | TAG      |

t_code tag有1、701、702。

告警需求：统计五分钟内t_code=(701,702)与t_code=1之比，超过50%告警。
问题：子查询嵌套不超过两层，外部sql中group by 字段只能有一个。sql限制如此多，再加上alert插件能力也不够丰富，很多promSQL能表达的告警策略都无法实现。请问以后会考虑加强这方面的功能吗？

**Comment by sangshuduo** [comment]
有没有评估过用 TDengine 的 grafanaplugin 来做报警？

**Comment by Kolo7** [comment]
谢谢回答，我会去试下。
