### ISSUE TITLE
sprintf("   ip:%s port:%hu\n", pFdObj->ipstr, pFdObj->port);

### ISSUE THREAD

**Issue by xcalibyte-guard** [taosdata/TDengine#974]
**Bug Description**
The source file is TDengine/src/rpc/src/ttcpserver.c
Line 471, 1st parameter of sprintf( ) is missing. Code pasted:

    while (pFdObj) {
      sprintf("   ip:%s port:%hu\n", pFdObj->ipstr, pFdObj->port);
      msg = msg + strlen(msg);
      numOfFds++;
      numOfConns++;
      pFdObj = pFdObj->next;
    }

**Comment by plum-lihui** [comment]
多谢！
这个函数并没有使用，暂时注释了。
