### ISSUE TITLE
Support arithmetic operation on aggregation result

### ISSUE THREAD

**Issue by liu0x54** [taosdata/TDengine#975]
Current TDengine support aggregation function such as sum, avg,etc. And TDengine support arithmetic operation on the values. But the combination is not supported, that is,  you can query the result like: select sum(value) from supertable; you can query the result like: select value/1000 from supertable; but you can not query like: select sum(value)/1000 from supertable.

**Comment by hjxilinx** [comment]
This feature will be added very soon.
