### ISSUE TITLE
sql return NULL jdbc return “NULL”

### ISSUE THREAD

**Issue by xForMe** [taosdata/TDengine#9759]
**Bug Description**

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: CentOS 7.0
 - TDengine Version :2.2.2.0
 - jdbcType:

**Additional Context**
shell查询结果
<img width="1682" alt="2ddfe42a1bb2e80b3411a739a1bbdff" src="https://user-images.githubusercontent.com/8530198/149077080-7e60a1fd-b6da-427d-bcf2-8fd6602eeb46.png">
debug结果
<img width="1874" alt="5172104ef0271d9768277c01f92e409" src="https://user-images.githubusercontent.com/8530198/149077063-bc075148-b708-41de-81df-a352476cc3fd.png">
表结构
![image](https://user-images.githubusercontent.com/8530198/149077186-c566b268-7417-4938-9731-29c890196c8d.png)

**Comment by yijiue** [comment]
已修复：https://github.com/taosdata/TDengine/pull/10576
