### ISSUE TITLE
部署到K8s，无法正常使用

### ISSUE THREAD

**Issue by xiaopenggogo** [taosdata/TDengine#9797]
因K8S无法将同一端口同时打开UDP/TCP。我将6030跟6031建立UDP，6032-6041 TCP时。 导致客户端可以连接但是无法查询数据，使用restful可以正常操作数据库。
![image](https://user-images.githubusercontent.com/97154895/149431075-726fd121-a2e3-4a6a-ade9-0262ba3291ae.png)
![image](https://user-images.githubusercontent.com/97154895/149431126-a411fe5f-a5c8-4eda-827d-0abe4b8c0a91.png)
请问这个问题如何处理？谢谢

**Comment by xiaopenggogo** [comment]
![image](https://user-images.githubusercontent.com/97154895/149431197-e10ac75c-da23-4a1f-ba07-63a73bc8958d.png)
![image](https://user-images.githubusercontent.com/97154895/149431201-91823b52-1d8d-4acf-854b-3ae2d10e5104.png)
我尝试将一个端口同时添加TCP跟UDP报的错误。    这个问题不知道是不是 K8S的缺陷。

**Comment by xiaopenggogo** [comment]
主要问题是还是K8S无法将同一端口同时开通UDP/TCP 协议，而数据库需要这样的操作。

**Comment by zitsen** [comment]
@xiaopenggogo 
1. 不建议使用nodePort，这个配置起来会遇到很多问题，在k8s环境中建议使用restful API连接。
2. 如果一定要用nodePort，且无法解决同时绑定udp/tcp 协议，可以使用 rpcForceTcp 1 配置仅使用tcp连接。此后连接时，请保持警惕，如果连接后写入数据提示fqdn 问题，请自行解决，我们对此不负责。

**Comment by zitsen** [comment]
在k8s上的部署方案，请参考 https://taosdata.github.io/TDengine-Operator/zh/index.html

**Comment by xiaopenggogo** [comment]
这个不算缺陷，尴尬！！restful API性能有没有保障，是否会比客户端连接性能慢？

**Comment by zitsen** [comment]
性能比taosc要差一些，差多少看具体场景，我相信95%的场景下，RESTful 性能都足够满足需求。

**Comment by zitsen** [comment]
nodePort我也已经给出方案，你可以自行尝试下。

**Comment by linsmalldragon** [comment]
搞了半天,用k8s部署的是不能使用6030连接的? 文档上也没说明不行啊
