### ISSUE TITLE
列名中有保留关键字如first怎么办

### ISSUE THREAD

**Issue by duanxuelin** [taosdata/TDengine#98]
SQL如下，使用双引号依然返回Invalid SQL
```
create table db.test (__time timestamp, "first" int)
```

**Comment by hjxilinx** [comment]
TD中的列、表、数据库名称不能支持其他数据库中的使用转义字符来处理的模式，后面我们会处理这个问题。建议现在采用列名+'_'的方式来处理。例如：create table db.test(__time timestamp, first_ int);

**Comment by duanxuelin** [comment]
好的，谢谢回复
