### ISSUE TITLE
K8s部署问题

### ISSUE THREAD

**Issue by xiaopenggogo** [taosdata/TDengine#9805]
https://github.com/taosdata/TDengine/issues/9797#issue-1102642629
我觉得这个问题是依然存在的会影响客户使用的体验感，还是希望能给与解决。不能单纯的说不用吧。

**Comment by xiaopenggogo** [comment]
如果这样的解决方式我只能放弃了，比如说你们把端口全部开放出来让用户自己去配置！

**Comment by sangshuduo** [comment]
建议在相同 issue 下讨论，没必要开新 issue

**Comment by xiaopenggogo** [comment]
我这个问题是不是影响到你们声誉了，这个快就关闭了我的问题，都没有解决，干嘛关闭。。。。

**Comment by sangshuduo** [comment]
和 https://github.com/taosdata/TDengine/issues/9797 相同的问题，可以在 9797 里讨论。issue 你可以自己打开。
