### ISSUE TITLE
the dump-out data   dump in  again ,the data size turn into double

### ISSUE THREAD

**Issue by hualei731280** [taosdata/TDengine#9870]
想请问一下为什么，数据量没变 但是空间占用多了一倍，再次导入再多一倍

**Comment by yu285** [comment]
是不是没有清理vnode_bak.这里保存着被删掉的库的数据文件

**Comment by xiaolulu2017** [comment]
遇到同样问题，没有删掉库，只是导入了两遍。vnode占用的空间。

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
