### ISSUE TITLE
taosCacheRelease: Assertion `ref >= 0' failed.

### ISSUE THREAD

**Issue by allforcloud** [taosdata/TDengine#9899]
java: /home/ubuntu/ver_release_workspace/TDinternal/community/src/util/src/tcache.c:403: taosCacheRelease: Assertion `ref >= 0' failed.
运行报错，如果配置？

**Comment by allforcloud** [comment]
补充一下：是使用JDBC连接每5s访问一次TD数据库，运行大概36h会报这个错误，导致程序挂掉。

**Comment by yu285** [comment]
please provide TDengine and JDBC version
