### ISSUE TITLE
query result is different from what  i inserted

### ISSUE THREAD

**Issue by mozhou-tech** [taosdata/TDengine#9906]
**Bug Description**
query result is different from what  i inserted

**To Reproduce**

1. my ddl

             Field              |         Type         |   Length    |   Note   |
=================================================================================
 ts                             | TIMESTAMP            |           8 |          |
 emergoa                        | DOUBLE               |           8 |          |
 poklad                         | DOUBLE               |           8 |          |
 probepos                       | NCHAR                |         100 |          |
 cinnum                         | INT                  |           4 |          |
 clientid                       | NCHAR                |         100 | TAG      |
 deviceid                       | NCHAR                |          50 | TAG      |
 pos                            | NCHAR                |         100 | TAG      |
 workingface                    | NCHAR                |         100 | TAG      |

2.  the issue

![image](https://user-images.githubusercontent.com/14063414/150115778-7e2495f1-5896-4277-bd60-c90f0036fed4.png)

**Expected Behavior**
查询的结果，应当Insert语句中的一致

**Environment (please complete the following information):**
 - OS: CentOS7
 - 64G, CPU, current Disk Space
 - TDengine Version [e.g. 2.2.0]

**Comment by yu285** [comment]
tag不支持动态更新——想修改需要alter table xxx set tag xxx，具体语法官网文档可查
