### ISSUE TITLE
hope window function `INTERVAL` support specify the start time  时间窗口函数 `INTERVAL` 支持指定起始时间节点

### ISSUE THREAD

**Issue by mojerro** [taosdata/TDengine#9909]
## 时间窗口函数 `INTERVAL` 支持指定起始时间节点

**WHY**

Many time-series data have periodic characteristics, and arbitrary aggregation may not conform to these characteristics. For example, shopping malls only open from 10:00 to 20:00, and the stock market only opens at a specific period. If the data is aggregated by day, it is unreasonable to aggregate the data at the end of the first day and the first half-day of the next day.

许多时序数据都有周期性特征，随意聚合可能会不符合这些特征。比如商场只有10:00-20：00开门，股市有休市时间。如果按天聚合数据，将头一天后半天的数据与第二天前半天的数据聚合到一起，是不合理的。

**HOW**

I personally prefer to specify the start time when using the window function `INTERVAL` . And I cannot find the use case about it in the document, can someone give a piece of advice.

我个人希望在使用窗口函数 `INTERVAL` 的时候可以指定起始时间，这样分析及可视化结果会更精确。目前没有在文档上找到相关case，不知道官方有什么实现的建议或者使用文档。

**Comment by mojerro** [comment]
对sql不太熟，想确认一下如果where指定一个起始时间，是否可以做到按此时间后续进行滑动窗口运算

**Comment by yu285** [comment]
可以用offset设置起始的偏移值。

具体相关使用方式可以看看https://www.taosdata.com/blog/2021/11/12/3278.html

**Comment by mojerro** [comment]
> 可以用offset设置起始的偏移值。
> 
> 具体相关使用方式可以看看https://www.taosdata.com/blog/2021/11/12/3278.html

这篇文章讲的非常清楚了，感谢大佬
