### ISSUE TITLE
golang example get error `database not exist` and `table not exist`

### ISSUE THREAD

**Issue by mojerro** [taosdata/TDengine#9912]
**Bug Description**

get errors when running the example code. 

### error1
**go code:**
```golang
// drop database if exists
sqlStr := "drop database if exists " + dbName
_, err = db.Exec(sqlStr)
checkErr(err, sqlStr)
```

I forgot to record the error, I only remember it shows `database does not exist`, same as the error2 below

And I can run these commands successfully by using the console.

### error2
**go code:**
```golang
sqlStr := "insert into " + dbName + "." + childTblPrefix + strconv.Itoa(tID) + " values "
```
**docker error:**
```bash
01/19 18:33:11.390574 00000029 MND ERROR msg:0x7f69d0003b40, app:0xaa table:0.log.vgroup_3, failed to get table meta, table not exist
01/19 18:33:11.391065 00000067 TSC ERROR 0xa9 get multi-tableMeta failed, code:Table does not exist
01/19 18:33:11.391518 00000038 TSC ERROR 0xa9 async result callback, code:Table does not exist
01/19 18:33:11.391917 00000036 MON ERROR table vgroup_3 not exist, create table vgroup_3
```

**Screenshots**

![image](https://user-images.githubusercontent.com/15071824/150246184-37b674dc-efbb-408f-a41f-eaaefac7b3c3.png)

**Environment (please complete the following information):**
 - OS: wsl2 in win10
 - Memory, CPU, current Disk Space
 - TDengine Version:  I test with 2.4.0.0 & 2.4.0.4 by using docker
 - Golang driver with Linux client 2.4.0.0

**Comment by yu285** [comment]
we will check on this

**Comment by mojerro** [comment]
感谢大佬

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
