### ISSUE TITLE
2.4.0.0 docker image has no configurtion file 

### ISSUE THREAD

**Issue by zzandyc** [taosdata/TDengine#9928]
我使用2.4.0.0制作了一个docker镜像，并在镜像内启动了tdengine，但没有找到配置文件，Dockerfile的内容如下：
FROM ubuntu:20.04

WORKDIR /root

ARG pkgFile
ARG dirName
RUN echo ${pkgFile}
RUN echo ${dirName}

COPY ${pkgFile} /root/

RUN tar -zxf ${pkgFile}

WORKDIR /root/${dirName}/

RUN /bin/bash install.sh -e no

RUN apt-get clean && apt-get update && apt-get install -y locales && apt-get install -y net-tools && apt-get install -y iputils-ping
RUN locale-gen en_US.UTF-8

ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib"
ENV LC_CTYPE=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

EXPOSE 6030 6031 6032 6033 6034 6035 6036 6037 6038 6039 6040 6041 6042

CMD ["taosd"]

制作镜像的命令如下：
#制作镜像
docker build -f .\DockerfileTAOS --build-arg pkgFile=TDengine-server-2.4.0.0-Linux-x64.tar.gz --build-arg dirName=TDengine-server-2.4.0.0 -t tdengine:2.4.0.0 .

#运行容器
docker run -it -p 6030-6041:6030-6041 -p 6030-6041:6030-6041/udp -v /d/td/data:/var/lib/taos -v /d/td/cfg:/etc/taos -v /d/td/log:/var/log/taos --name tdengine --hostname tdeinge tdengine:2.4.0.0 /bin/bash

**Comment by yu285** [comment]
will check on it
