### ISSUE TITLE
High memory consumption with low data on the disk

### ISSUE THREAD

**Issue by perriea** [taosdata/TDengine#9943]
**Problem Description** 
I am currently working on creating a TDengine cluster in Kubernetes. The creation of the cluster was done without problem.

However, I am having some issues when importing (INSERT) or executing my queries (SELECT), the cluster is consuming a lot of memory considering the data on disk. Almost a 1:1 ratio

I don't understand where this can come from. I have many tables vs data: 
```
aos> show databases;
              name              |      created_time       |   ntables   |   vgroups   | replica | quorum |  days  |           keep           |  cache(MB)  |   blocks    |   minrows   |   maxrows   | wallevel |    fsync    | comp | cachelast | precision | update |   status   |
====================================================================================================================================================================================================================================================================================
 companies_usd                  | 2022-01-20 00:08:59.007 |        5760 |           3 |       3 |      1 |     10 | 36500                    |          16 |         100 |         100 |        4096 |        1 |        3000 |    2 |         0 | ms        |      0 | ready      |
 log                            | 2022-01-19 23:21:47.186 |          36 |           1 |       1 |      1 |     10 | 30                       |           1 |           3 |         100 |        4096 |        1 |        3000 |    2 |         0 | us        |      0 | ready      |
 companies_hkd                  | 2022-01-20 00:09:00.137 |        2326 |           3 |       3 |      1 |     10 | 36500                    |          16 |         100 |         100 |        4096 |        1 |        3000 |    2 |         0 | ms        |      0 | ready      |
 invest_accounts                | 2022-01-19 23:47:31.244 |           2 |           1 |       3 |      1 |     10 | 36500                    |          16 |         150 |         100 |        4096 |        1 |        3000 |    2 |         0 | ms        |      0 | ready      |
 companies_cny                  | 2022-01-20 00:08:59.570 |        1917 |           1 |       3 |      1 |     10 | 36500                    |          16 |         100 |         100 |        4096 |        1 |        3000 |    2 |         0 | ms        |      0 | ready      |
 companies_sgd                  | 2022-01-20 00:09:00.429 |         474 |           1 |       3 |      1 |     10 | 36500                    |          16 |         100 |         100 |        4096 |        1 |        3000 |    2 |         0 | ms        |      0 | ready      |
 companies_gbp                  | 2022-01-20 00:08:59.856 |        1282 |           2 |       3 |      1 |     10 | 36500                    |          16 |         100 |         100 |        4096 |        1 |        3000 |    2 |         0 | ms        |      0 | ready      |
 companies_cad                  | 2022-01-20 00:08:59.292 |         664 |           1 |       3 |      1 |     10 | 36500                    |          16 |         100 |         100 |        4096 |        1 |        3000 |    2 |         0 | ms        |      0 | ready      |
 companies_eur                  | 2022-01-20 00:08:58.702 |        1219 |           2 |       3 |      1 |     10 | 36500                    |          16 |         100 |         100 |        4096 |        1 |        3000 |    2 |         0 | ms        |      0 | ready      |
 currencies                     | 2022-01-19 23:47:33.206 |           8 |           1 |       3 |      1 |     10 | 36500                    |          16 |         100 |         100 |        4096 |        1 |        3000 |    2 |         0 | ms        |      0 | ready      |
Query OK, 10 row(s) in set (0.002586s)
```

My config : 
```cfg
firstEp                   tdengine-cluster-0.tdengine-cluster.database.svc.cluster.local:6030
fqdn                      tdengine-cluster-0.tdengine-cluster.database.svc.cluster.local
serverPort                6030
logDir                    /var/log/taos
dataDir                   /var/lib/taos
tempDir                   /tmp/
arbitrator                tdengine-cluster-arbitrator:6042
keepColumnName  1
http            1
httpMaxThreads  4
monitor         0
enableRecordSql 0
enableCoreFile  0
stream          0
balance         1
```

My problem persists and I can't find a solution to fix it. Is it configuration issues ? 

**Screenshots**
<img width="629" alt="Capture d’écran 2022-01-20 à 23 46 23" src="https://user-images.githubusercontent.com/15982613/150434716-aef461f6-fb31-4dd6-a59c-42c2b531c5e7.png">

I don't have much data on disk. 
<img width="1360" alt="Capture d’écran 2022-01-20 à 23 48 03" src="https://user-images.githubusercontent.com/15982613/150434745-d4b0cb7a-62e0-4940-b143-243ef96124cd.png">

Consequence, my cluster is broken ...
<img width="1037" alt="Capture d’écran 2022-01-20 à 23 50 38" src="https://user-images.githubusercontent.com/15982613/150434772-308450e9-1117-4560-8c93-b18163917ab3.png">

**Environment (please complete the following information):**

* Kubernetes
* 2Gi of Ram, 800m, 10Gi disk by node
* TDengine Version: `2.4.0.0`

**Comment by sangshuduo** [comment]
@perriea By design, TDengine will keep the table's metadata in memory as cache to accelerate the insert/query performance. If you have many tables but little data, that's normal. We assume you have tons of data in a relatively small number of tables in most IoT scenarios.

If you do want to reduce the memory consumption, you can manually execute the command `reset query cache` but we don't recommend doing that frequently if you want to leverage TDengine's performance boost capability.

**Comment by perriea** [comment]
> @perriea By design, TDengine will keep the table's metadata in memory as cache to accelerate the insert/query performance. If you have many tables but little data, that's normal. We assume you have tons of data in a relatively small number of tables in most IoT scenarios.

Thanks for your precision !

> If you do want to reduce the memory consumption, you can manually execute the command `reset query cache` but we don't recommend doing that frequently if you want to leverage TDengine's performance boost capability.

It's not my goal. Just a question, TDEngine keeps data in memory forever ? 
If not, what/when event to clear the cache ?

**Comment by sangshuduo** [comment]
> > @perriea By design, TDengine will keep the table's metadata in memory as cache to accelerate the insert/query performance. If you have many tables but little data, that's normal. We assume you have tons of data in a relatively small number of tables in most IoT scenarios.
> 
> Thanks for your precision !
> 
> > If you do want to reduce the memory consumption, you can manually execute the command `reset query cache` but we don't recommend doing that frequently if you want to leverage TDengine's performance boost capability.
> 
> It's not my goal. Just a question, TDEngine keeps data in memory forever (after call) ? If not, what/when event to clear the cache ?

If the 'data' you mention is the metadata, like the table structure of the tables, the current design is keeping them forever as we assume the number of tables would always reach its ceil at last. In the next major version of TDengine, we probably provide a flexible mechanism to dynamically manage them.

**Comment by perriea** [comment]
> If the 'data' you mention is the metadata, like the table structure of the tables, the current design is keeping them forever as we assume the number of tables would always reach its ceil at last. In the next major version of TDengine, we probably provide a flexible mechanism to dynamically manage them.

Interesting, I'll keep an eye on it. 
Thanks for all information @sangshuduo 🙏🏼
