### ISSUE TITLE
windows taos_init fail / taos_connect fail , need to restart server

### ISSUE THREAD

**Issue by OrangeEffects** [taosdata/TDengine#9955]
windows环境
APP多线程（6个独立连接）调用taos客户端DLL向数据库插入数据
APP连续运行十几天后出现异常，query失败，重新连接再也连不上
重开APP，taos_init fail（返回 -1）
用官方客户端 taos.exe 手动测试，报错 taos_init fail

重启系统，恢复正常。

能复现，重启后跑十来天又异常了。

-----------------------------------------------
不能确定是taos自己出了什么问题，也可能是我的APP有问题。
但是这个异常的影响只是针对taos（重开APP taos_init fail，其他功能正常），并且是系统层面的，一旦出现，只有重启能恢复。

请问：
taos_init 有哪些可能失败？
返回值 -1 啥也看不出来，希望后续版本能给出详细错误代码。 

环境
 - OS: windows server 2019 datacenter
 - CPU 4c/4t ,8G
 - TDengine Version 2.2.1.3

**Comment by sangshuduo** [comment]
通常无需调用 taos_init()使用 taos_connect() 即可

**Comment by OrangeEffects** [comment]
> 通常无需调用 taos_init()使用 taos_connect() 即可

我的代码确实也是这么写的， taos_init() 即使失败也继续尝试 taos_connect() ，任然失败。

我理解你说意思，taos_connect() 应该是内部有 taos_init() 部分实现，会初始化相关环境。

现在的问题是整个taos客户端dll调用全挂了，没有任何信息可以用于分析。
