### ISSUE TITLE
请教下TdEngine的UDP协议文档在哪里？

### ISSUE THREAD

**Issue by wwhai** [taosdata/TDengine#9961]
请教下TdEngine的UDP协议文档在哪里？近期准备实现个客户端，听说有UDP模式，但是没找到

**Comment by sangshuduo** [comment]
使用 UDP 或 TCP 是 TDengine 内部实现，对应用是使用 C 语言 API 或者 各种语言的 connector 或者 RESTful 的接口

**Comment by wwhai** [comment]
> 

了解 谢谢！
