### ISSUE TITLE
安装按taosd后usr./bin下没有taosBenchmark 这个命令

### ISSUE THREAD

**Issue by macbookpro2016** [taosdata/TDengine#9972]
![image](https://user-images.githubusercontent.com/24033636/150628617-492a87a6-cdf3-4f0b-94c5-ad541550485d.png)
![image](https://user-images.githubusercontent.com/24033636/150628639-e0eef014-bf7f-46f1-8948-adf5a7f1e486.png)

**Comment by sangshuduo** [comment]
需要安装独立安装包 taosTools

**Comment by macbookpro2016** [comment]
> taosTools

![image](https://user-images.githubusercontent.com/24033636/150629250-0f9ec556-6f70-4a89-98bd-86d0836a199b.png)
通过这个方式在ubantu上安装后还是没有

**Comment by sangshuduo** [comment]
如果没有修改源码需求建议从官网下载官方安装包 https://www.taosdata.com/cn/getting-started/#%E9%80%9A%E8%BF%87%E5%AE%89%E8%A3%85%E5%8C%85%E5%AE%89%E8%A3%85

**Comment by macbookpro2016** [comment]
> 如果没有修改源码需求建议从官网下载官方安装包 https://www.taosdata.com/cn/getting-started/#%E9%80%9A%E8%BF%87%E5%AE%89%E8%A3%85%E5%8C%85%E5%AE%89%E8%A3%85

问题已解决，谢谢！

**Comment by macbookpro2016** [comment]
> 如果没有修改源码需求建议从官网下载官方安装包 https://www.taosdata.com/cn/getting-started/#%E9%80%9A%E8%BF%87%E5%AE%89%E8%A3%85%E5%8C%85%E5%AE%89%E8%A3%85

建议在快速体验文档中更新上这一步骤，文档没有直接提示需要安装tools，以免给后续的使用者带来相同的疑惑
![image](https://user-images.githubusercontent.com/24033636/150644234-124d680c-a8ed-4322-a6d3-fe24946e35e1.png)

**Comment by sangshuduo** [comment]
> > 如果没有修改源码需求建议从官网下载官方安装包 https://www.taosdata.com/cn/getting-started/#%E9%80%9A%E8%BF%87%E5%AE%89%E8%A3%85%E5%8C%85%E5%AE%89%E8%A3%85
> 
> 建议在快速体验文档中更新上这一步骤，文档没有直接提示需要安装tools，以免给后续的使用者带来相同的疑惑 ![image](https://user-images.githubusercontent.com/24033636/150644234-124d680c-a8ed-4322-a6d3-fe24946e35e1.png)

谢谢，我们修改一下
