### ISSUE TITLE
reach the max retry:2, code:29

### ISSUE THREAD

**Issue by cea5** [taosdata/TDengine#999]
use jmeter to test http performence，when connection reach 6000 ，
client return error：
` java.net.SocketException: Socket operation on nonsocket: configureBlocking`
and
`java.net.SocketException: Socket Closed`

taos log：
```
12/23 17:54:24.188301 7f113b713700 ERROR HTP context:0x7f10f5ec3070, fd:-1, ip:60.190.252.114:34727, code:400, error:29:failed to connect to server
12/23 17:54:24.188420 7f113b713700 ERROR TSC 0x7f10f54f2390 reach the max retry:2, code:29
12/23 17:54:24.188423 7f113b713700 ERROR HTP context:0x7f10f604dbe0, fd:-1, ip:60.190.252.114:57836, user:root, query error, taos:0x2699da0, code:29, sqlObj:(nil)
```

**Comment by xieyinglin** [comment]
you can set `maxMgmtConnections` in taos.cfg which denotes the max connection to management node.

remember to close the connection after used it.
